### ISSUE TITLE
Problem with copy/pasting text from PDF.js

### ISSUE THREAD

**Issue by harsh05041990** [mozilla/pdf.js#10003]
Hello,

We have used PDF.js viewer to view PDF file in web browser. The PDF result is generated in PDF highlighter which is a third party API to view PDF in PDF.js viewer.

We are facing following problem :

**There is a problem with copy/pasting text from the PDF.js viewer. When text is pasted into a separate document it inserts random linebreaks throughout the text.**

- Web browser and its version:  **All Web Browsers****

I have attached following screenshot of PDF viewer where we copy the paragraph

![pdfviewer](https://user-images.githubusercontent.com/42639752/44519220-0b7b7b00-a6ea-11e8-9b67-ecb5aeca13f7.png)

After pasting the paragraph into word document, in the document it inserts random linebreaks throughout the paragraph.

I have attached the following word document screenshot.
![pdf copy-paste](https://user-images.githubusercontent.com/42639752/44520198-dae91080-a6ec-11e8-9b59-1e1fe4b448d0.png)

**Comment by retrazil** [comment]
@harsh05041990 , would it be possible to share a sample pdf to reproduce this issue ?

**Comment by Snuffleupagus** [comment]
Given that this issue is missing required information (e.g. no PDF file attached) and also that there's similar text-selection issues open already, this should probably be closed as INCOMPLETE for now.
