### ISSUE TITLE
Code splitting is not naming webpack chunk

### ISSUE THREAD

**Issue by cheryly279** [mozilla/pdf.js#10002]
Is there a reason that you guys are not naming async loaded code? This relates to code here: https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L70, though there are probably other instances of this in the code.

When I bundle my app using webpack, there is an asset with a generic name like "0" where I would expect something like maybe "pdfjs_core". I traced it back to the line of code above. It can be fixed by adding a name as the 4th argument, based on this: https://webpack.js.org/api/module-methods/#require-ensure.

Is there some reason you did not include this?

**Comment by timvandermeij** [comment]
Fixed by the pull request above.
