### ISSUE TITLE
No toolbar on viewer

### ISSUE THREAD

**Issue by JoshuaDeanEssium** [mozilla/pdf.js#10001]
Hi, so i am using bower, requireJS, backboneJS, and i believe thats all thats necessary to know in my web software. I am trying to integrate this viewer and am including everything necessary (pdf.js, worker, and web/viewer). The issue is when creating a new viewer it doesnt include the toolbar like in the demo. How am i able to get the toolbar to show up and use it accordingly?

Please help, this is not coming together easily. I just want the toolbar in there and i can hook into the events as necessary etc... 

Thank you.

![withouttoolbar](https://user-images.githubusercontent.com/34247427/44483930-6180ed80-a61a-11e8-90ba-c5d98f0ecf51.PNG)
![code](https://user-images.githubusercontent.com/34247427/44483931-6180ed80-a61a-11e8-868c-069afebb1faa.PNG)

**Comment by timvandermeij** [comment]
You are using the viewer components, but we don't have a component for the toolbar since it's custom-made for the viewer. You must implement it yourself, but you may use https://github.com/mozilla/pdf.js/blob/master/web/toolbar.js for example as a baseline.

**Comment by JoshuaDeanEssium** [comment]
it cant be implemented via requireJS as it is not set up for it, using bower to build and use makes that not a viable option. Thanks though for the quick response.
