### ISSUE TITLE
Some fonts are rendered white/invisible

### ISSUE THREAD

**Issue by bluefiish** [mozilla/pdf.js#10014]
Attach (recommended) or Link to PDF file here:
[no_text_1.pdf](https://github.com/mozilla/pdf.js/files/2323646/no_text_1.pdf)

Configuration:
- Web browsers: Google Chrome Version 68.0.3440.75 (Offizieller Build) (64-Bit) / Mozilla Firefox 61.0.1 (64-Bit)
- Operating system and its version: Windows 7 Ultimate x64 German
- PDF.js version: 2.0.787

Steps to reproduce the problem:
1. Open Demo page at: https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the given sample pdf 
3. Some of the given Text is not rendered (or rendered with a white/transparent font color)

What is the expected behavior? (add screenshot)
Text should be visible:
![image](https://user-images.githubusercontent.com/13003654/44657601-aa131f00-a9fd-11e8-866f-0ee76c3921ca.png)

This can be reproduced by (it works in all this cases):
- using Adobe Acrobat Reader
- using Build-In pdf viewers of firefox or chrome
- using firefox with pdfjs demo using following setting: https://support.mozilla.org/de/questions/974866. In my case it is not working when the setting is unchecked.
- "Recreate" the given pdf by printing it again using e.g. PDFCreator -> during this process the fonts used in the pdf are changed and suddenly visible.

What went wrong? (add screenshot)
Text is not visible:
![image](https://user-images.githubusercontent.com/13003654/44657694-00805d80-a9fe-11e8-8f28-f60966c6bf49.png)

This issue occurs with several documents of different origins.

**Comment by SamyCookie** [comment]
This issue does not occur on Debian OS with Firefox 62.0b10 and 52.9.0

**Comment by timvandermeij** [comment]
@bluefiish Do you have up-to-date graphics drivers? Try seeing if there are updates and apply them. If that doesn't work, are there any errors/warnings in the browser's console when you render this PDF file?

**Comment by SamyCookie** [comment]
For record, I cannot reproduce on Windows 10 64bit and Fx 61.0.2 either.

**Comment by kdleijer** [comment]
I can reproduce this issue with the provided PDF on my Windows 7 installation with three browsers installed
- Chrome 68 "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
- Firefox 61 "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:61.0) Gecko/20100101 Firefox/61.0"
- IE 11 "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko"
- PDF.js version: 2.0.787
- Windows 7 Professional SP1 (Dutch) 64-bit
- Intel® HD Graphics 3000 (Internal graphics-card of a Dell Latitude)

According to Windows I have the latest version of the graphics-driver,
according to Intel, this graphics-card is discontinued
https://www.intel.com/content/www/us/en/support/products/81500/graphics-drivers/graphics-for-2nd-generation-intel-processors/intel-hd-graphics-3000.html

Screenshots attached, they might include some Dutch terms (if translation needed, please let me know)
![2018-08-28_10-19-56](https://user-images.githubusercontent.com/24917428/44710673-fb2e1c00-aaac-11e8-921d-56081357db56.png)
![2018-08-28_10-21-25](https://user-images.githubusercontent.com/24917428/44710674-fb2e1c00-aaac-11e8-9d33-f5aa830d7874.png)
![2018-08-28_10-22-54](https://user-images.githubusercontent.com/24917428/44710675-fb2e1c00-aaac-11e8-8702-528e7a775ec5.png)
![2018-08-28_10-24-16](https://user-images.githubusercontent.com/24917428/44710676-fbc6b280-aaac-11e8-9d01-7cb57d8e0b16.png)
![2018-08-28_10-25-48](https://user-images.githubusercontent.com/24917428/44710677-fbc6b280-aaac-11e8-902b-2bbce35d5a87.png)

**Comment by bluefiish** [comment]
Due to your replies i tried to reproduce it on several different computers using Windows 7 and Windows 10 and different browsers.

Results:

I have no Windows 7 installation where the given pdfs is rendered correctly (except Firefox with the setting mentioned above). 

As for Windows 10 I have multiple computers where it works and multiple computers where it doesn't work using Chrome and Edge. It always worked or didn't work in both browser. Never just in one. It always worked on Windows 10 with version 1803 but never with Windows 10 version 1709.

**Comment by SamyCookie** [comment]
@bluefiish What are the graphic hardware used on your machines ? Are their graphic driver up to date ?

**Comment by bluefiish** [comment]
@SamyCookie For my Windows 7 pc, they are up to date for sure.
![image](https://user-images.githubusercontent.com/13003654/44715453-1e11fd80-aab8-11e8-91d5-cecf2b72da47.png)

I'll try to check it the for one of the Windows 10 v.1709.

**Comment by SamyCookie** [comment]
@bluefiish it seems to exist a lot more recent driver [here](https://downloadcenter.intel.com/download/27780/pilote-pour-graphiques-Intel-pour-Windows-15-40-?product=97500) (2 years younger). Could you update to see if this bug occurs after ?

**Comment by bluefiish** [comment]
@SamyCookie updated the drivers of one of our Win 10 v.1709 to the latest version. Sadly no difference. Do you need the specs of this driver too? I just tried it on a Win 10 pc as those are of our main concern. I will however try it on my Win 7 machine as well.

**Comment by SamyCookie** [comment]
> Do you need the specs of this driver too ?

Yes, thanks. That could help devs ! You can also get these informations in Firefox by using the url `about:support` and copy the relevant data in `Graphic` section

**Comment by bluefiish** [comment]
For one of my Win 10 v.1709 PCs:
![unbenannt](https://user-images.githubusercontent.com/13003654/44773874-eff0f400-ab71-11e8-85e6-657d2fcab0c3.PNG)

If I open it in Firefox 60.1.0esr (32-Bit) I get the following information:
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.0.787)
app.js:1118:6
PDF dd51917542631728a83a944fa72c7e58 [1.7 pdfFactory Pro 3.52 (Windows 7 Ultimate x64 German) / pdfFactory Pro www.context-gmbh.de] (PDF.js: 2.0.787)

**Comment by bluefiish** [comment]
@SamyCookie: Tried to install the driver from the given source. The newer driver is only available for Windows 10. Therefore I am on the newest driver on this computer (Lenovo T540p).

**Comment by duffy356** [comment]
Same for me on W7 with Google Chrome (68.0.3440.106) and IE (11) and Firefox (60.1.0).

Graphics Driver updated to:
![image](https://user-images.githubusercontent.com/4521548/44844679-db812a00-ac4b-11e8-99c6-0f963fee4aed.png)
