### ISSUE TITLE
How can I verify CA's correct

### ISSUE THREAD

**Issue by venshine** [mozilla/pdf.js#10017]
Now the number signature is shown in pdf.js viewer already, But How can I verify CA's correct, by click the signature's image.

**Comment by venshine** [comment]
![testsignfile](https://user-images.githubusercontent.com/1456580/44712821-40217500-aae4-11e8-9c4e-2e5a72f1f385.gif)

Like the picture above.

**Comment by timvandermeij** [comment]
It's not implemented. Closing since there is already a tracking issue for digital signatures: #1076
