### ISSUE TITLE
How to find the response to the XHR that download the PDF?

### ISSUE THREAD

**Issue by Ps-Pencil** [mozilla/pdf.js#10024]
In short, I would like to know where in the code the PDF is requested through XHR so I can manually cache it. 

Why I want to do it: I am writing an app for Drive which opens pdfs directly from drive and remembers the last viewed locations. The view history is synced across device. To view directly from drive, I have to use the "downloadUrl" property which has a header "Cache-Control: private, max-age=0". 

With my very limited knowledge of Javascript, I have done a global search for "XMLHttpRequest()" and added an alert before every statement that creates an XHR. However, they all don't seem to be the request that downloaded the pdf. Maybe the request is created in a way that I am not aware of.

**Comment by Ps-Pencil** [comment]
Sorry, forgot to mention the setup. I am using the pre-built viewer.html and viewer.js/pdf.js/pdf.worker.js. But once the code snippet in the unpacked source handling the XHR is identified, I can search for the relevant piece myself.

**Comment by Snuffleupagus** [comment]
> I have to use the "downloadUrl" property which has a header "Cache-Control: private, max-age=0".

First of all, please keep in mind that the PDF.js API already has support for adding custom headers to requests (regardless of type); please refer to the following JSDoc comment https://github.com/mozilla/pdf.js/blob/283f2dfcc3af2e1286e5a875891584212d72ed85/src/display/api.js#L115

> I have done a global search for "XMLHttpRequest()" and added an alert before every statement that creates an XHR.

The PDF.js library will utilize the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) whenever possible, so trying to search for `XMLHttpRequest` is going to miss part of the networking code. If the existing API parameter isn't sufficient to solve the problem, the relevant files to look at is [/src/display/network.js](https://github.com/mozilla/pdf.js/blob/master/src/display/network.js) and [/src/display/fetch_stream.js](https://github.com/mozilla/pdf.js/blob/master/src/display/fetch_stream.js).

**Comment by Saya47** [comment]
I was also wondering this, spent hours debugging with Chrome Devtools adding breakpoints etc. on network.js and pdf.js etc. or adding breakpoints on XHR event listeners etc. but can't figure this out.

Any help is appreciated!
@Snuffleupagus hello! any more hints?
@pspencil hello! did you ever figure this out?
