### ISSUE TITLE
Trouble installing pdf-view on atom

### ISSUE THREAD

**Issue by asthagiri** [mozilla/pdf.js#10027]
While other packages are installing fine, I'm having trouble with `pdf-view`.

Here is a snippet of the log file:

`
npm ERR! fetch failed https://registry.npmjs.org/fs-plus/-/fs-plus-2.10.1.tgz
npm WARN retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! fetch failed https://registry.npmjs.org/fs-plus/-/fs-plus-2.10.1.tgz
npm WARN retry will retry, error on last attempt: Error: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! fetch failed https://registry.npmjs.org/fs-plus/-/fs-plus-2.10.1.tgz
npm ERR! Darwin 16.7.0
`

Here is more:

`npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/w1/jchk9r810s5bgt4gvrmb8_f00000gp/T/apm-install-dir-11881-40129-p3jxkl.dkojx4unmi/npm-debug.log
`

**Comment by timvandermeij** [comment]
`pdf-view` is not a package maintained by Mozilla, so there is nothing we can do to fix this.

**Comment by timvandermeij** [comment]
Moreover, we have the same issue on Travis CI. It's a DNS issue at NPM which they are resolving now: https://status.npmjs.org/incidents/v22ffls5cd6h
