### ISSUE TITLE
Updates for #10004

### ISSUE THREAD

**Issue by ajaythakor** [mozilla/pdf.js#10038]
@timvandermeij we do not have the parser.js file.
Please confirm where do we need to change to update this issue.
https://github.com/mozilla/pdf.js/issues/10004
https://github.com/mozilla/pdf.js/issues/10010

**Comment by timvandermeij** [comment]
You're most likely using the build release then. In that case you'll have to wait until the next stable release.

**Comment by ajaythakor** [comment]
@timvandermeij what time will it take for the next stable release?

**Comment by timvandermeij** [comment]
There is no fixed date yet, however it's most likely soon.

**Comment by ajaythakor** [comment]
@timvandermeij any updates on this ?

**Comment by ajaythakor** [comment]
@timvandermeij thank you for the update.
