### ISSUE TITLE
PDF annotations toolbar in angular

### ISSUE THREAD

**Issue by kishandonepudi** [mozilla/pdf.js#10037]
HI Team,

how can i get annotations toolbar in pdf.js?

I am using angular 4

**Comment by timvandermeij** [comment]
We don't have any toolbar for annotations at the moment and I'm not sure what it means. When filing an issue, you need to fill out the entire template for issues to be actionable. In particular, include a screenshot of the desired functionality. However, we want to keep annotations simple in the viewer and we don't support adding/modifying annotations, only viewing them, so I don't see why we would need any toolbars for that.
