### ISSUE TITLE
Use OffscreenCanvas if available

### ISSUE THREAD

**Issue by aaronshaf** [mozilla/pdf.js#10039]
> "Now you can render your graphics off the main thread with OffscreenCanvas"

https://developers.google.com/web/updates/2018/08/offscreen-canvas

**Comment by timvandermeij** [comment]
Interesting find. If we can feature-detect this, we could try benchmarking this.

**Comment by websirnik** [comment]
@timvandermeij it is feature-detectable, see example here: https://developers.google.com/web/updates/2018/08/offscreen-canvas#use_with_popular_libraries

**Comment by phal0r** [comment]
This should give a performance boost for Chrome since in my observations rendering takes some time, especially when rendering many different pdfs including changing zoom levels. Is there already a plan to integrate this feature?

**Comment by benbro** [comment]
OffscreenCanvas is in [origin trial](https://bugzilla.mozilla.org/show_bug.cgi?id=1390089) in Firefox.

**Comment by timvandermeij** [comment]
Closing since we now use `OffscreenCanvas` if it's available (by feature detection). This was introduced by PR #14754 for image rendering performance improvements. If it's useful to use in more places, individual issues should be opened for those.
