### ISSUE TITLE
how to  implement the demo??? 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#10047]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- PDF.js version:2.0.305

i have a question.
i'd like to know the all page width, height before rendering page.
this demo is loadingbar in unrendering page.
i only know how to get page size to use this function
==> pdf.getPage(all page)  
but this function use all page render...
so how to implement loadingbar empty page size??? 
What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30399546/45132475-16470d00-b1cc-11e8-8a60-0519fb1f48ae.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The example at https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L43 shows how to do this. The `getPage` API doesn't render the page; it only renders if you call https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L54.
