### ISSUE TITLE
how to get Partial data  ??? 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#10040]
Attach (recommended) or Link to PDF file here:
this pdf url is  temporary... 
Configuration:
- Web browser and its version: chrome 
- PDF.js version:2.0.305

Steps to reproduce the problem:
1.  

pdf converting takes about 19 seconds.
this is pdf file is 34.56MB.. so how to Partial convert pdf data?? 
please help me..

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30399546/45073889-34edcb00-b11c-11e8-8840-d1a08352d69c.png)

What went wrong? (add screenshot)
at first the convert is very slow
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You don't have range requests enabled, so the whole file will need to be fetched at once before rendering, which takes quite a bit of time. Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range.
