### ISSUE TITLE
Get Document not working or displaying on iOS 11 with iPhone X

### ISSUE THREAD

**Issue by JoshuaDeanEssium** [mozilla/pdf.js#10044]
The PDF Viewer doesnt load because getDocument never resolves its promise on iOS 11 with iPhone X. If you view the demo it doesnt work there as well. See attached screenshot. Please fix or let me know if there is something that can be done to at least display the PDF for the time being. 

Thanks
![image](https://user-images.githubusercontent.com/34247427/45124654-21049200-b139-11e8-94b7-71afa3e37ecb.png)

**Comment by timvandermeij** [comment]
Do you have any errors/warnings in the console?

**Comment by brendandahl** [comment]
WFM on iOS 11.4.1 w/ iPhone X.

**Comment by JoshuaDeanEssium** [comment]
No warnings or errors in console for pdf.js.  Using iPhone X, Safari, and iOS 11

**Comment by JoshuaDeanEssium** [comment]
This is console errors from demo that doesnt load on iPhone 6S, iOS 8, safari
![errors](https://user-images.githubusercontent.com/34247427/45232804-b1101c00-b29e-11e8-8b90-7ba17ff4ac5c.PNG)

**Comment by morille** [comment]
I'm using pdf.js's core and I don't have this issue.
![xr](https://user-images.githubusercontent.com/4311899/48782290-2d32d100-ecde-11e8-8432-53a8714d0873.jpg)

**Comment by GProst** [comment]
Having the same issue with viewer, demo app doesn't work on Safari iOS as well

**Comment by GProst** [comment]
Hmm, seems like it doesn't work for me only in Browerstack. Real devices or emulators seem to load the pdf correctly. But still interesting why this happens only for iOS Safari there, other browsers and devices in Browserstack load it normally.

**Comment by madve2** [comment]
I experienced this very same thing on BrowserStack today. Spent a few hours troubleshooting this until I asked a colleague with an actual iPhone to help me out, and we also concluded that it only happens on BrowserStack, and even on BrowserStack, it only happens with iOS Safari (e.g. it works fine with iOS Chrome). Strange, as I have never exhibited such discrepancies between BrowserStack and actual devices, but here we are.

One thing I find interesting is that if you open the official demo page (or basically any other page that uses PDF.js) _with the developer tools closed_, and experience this issue, and then open the developer tools, the PDF "magically" appears in an instant. If, however, you loaded the page with the devtools already open, no amount of opening and closing will make it work.

**Comment by brendandahl** [comment]
Sounds like browser stack may not be triggering a request animation frame. You could try adding some logging.

**Comment by Snuffleupagus** [comment]
Is it actually meaningful to keep this issue open, when everything seems to point to a platform/browser specific bug (rather than a PDF.js one)? Also, given that it's apparently not consistently broken for the configuration in question; note e.g. https://github.com/mozilla/pdf.js/issues/10044#issuecomment-418924905.
