### ISSUE TITLE
issue with the last character arabic

### ISSUE THREAD

**Issue by salmen** [mozilla/pdf.js#10051]
Attach (recommended) or Link to PDF file here:
[file.pdf](https://github.com/mozilla/pdf.js/files/2360733/file.pdf)

Configuration:
- Web browser and its version: Google Chrome V 68.0.3440.106
- Operating system and its version: windows 7 
- PDF.js version: pdfjs-1.10.100-dist
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached file

What is the expected behavior? (add screenshot)
opening the same pdf file with adobe acrobat readerX  version 10.1.2. 
![expected](https://user-images.githubusercontent.com/11051314/45215640-03990a80-b296-11e8-80f0-e235eb9070dd.png)

What went wrong? (add screenshot)
the last character is represented by an empty tile. it seems like the issue is related to font encoding. The pdf is generated from crystal report 9 and font encoding is built-in. 
![fontencoding](https://user-images.githubusercontent.com/11051314/45215695-26c3ba00-b296-11e8-8a76-fc985ea8b82e.png)
. I am experiencing the same issue with chrome pdf viewer "last character is not attached to the word".

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Fixed by #9340.
