### ISSUE TITLE
Allow adding custom URL schemes to isValidProtocol

### ISSUE THREAD

**Issue by The-Compiler** [mozilla/pdf.js#10057]
I'm currently integrating PDF.js to view PDFs inside [qutebrowser](https://www.qutebrowser.org/). To do so, I serve PDF.js from a custom `qute://pdfjs/` URL which then opens the file from `qute://pdfjs/file?filename=foo.pdf`.

Due to an [issue with the backend I'm using](https://bugreports.qt.io/browse/QTBUG-70420) I need to set `PDFJS.disableCreateObjectURL = true;`. That means PDF.js falls back to downloading the URL - however, a whitelist in `utils.js` in `isValidProtocol` causes it to just ignore the download entirely.

Maybe it should be possible to configure additional trusted URL schemes? Or the scheme where the PDF was downloaded from should always be trusted? I'd be happy to try contributing this if it seems like a good idea, though I'm not sure how to add new settings exactly.

**Comment by Snuffleupagus** [comment]
> Maybe it should be possible to configure additional trusted URL schemes?

This does *not* seem like a good idea, since having the ability to change [`isValidProtocol`](https://github.com/mozilla/pdf.js/blob/bc5111d15209e55ab39891a0e6d9d4ef56b3513a/src/shared/util.js#L334-L349) (at runtime) could easily be misused to circumvent the protection that that function offers and thus render it completely moot.

> Or the scheme where the PDF was downloaded from should always be trusted?

Others will have to comment on the feasibility of such a solution; and whether it's desired functionality in the PDF.js library itself in the first place.

**Comment by The-Compiler** [comment]
To be honest I didn't really understand why this is applied to downloads at all. Looking at the history of the code:

- In #1326, @brendandahl introduced checks for URLs in PDF, as XSS protection from inside PDFs ([bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=734794))
- In #3467 / 28778e6c1b0fc9b3662a42d0883f7a3b9ab8c7d7 the same thing was applied to downloads by @yurydelendik, unfortunately without more explanation.

Looking at what it was originally intended to prevent (XSS via links inside a PDF document), allowing JS to change that list seems fine to me (if I can run JS in the context of PDF.js, I could as well just do whatever I allow PDF.js to do myself, no?).

However, I'm also confused about the change in 28778e6c1b0fc9b3662a42d0883f7a3b9ab8c7d7 - this looks a bit like what was intended was checking that the URL wasn't invalid (but why would it ever be?), not that it confirms to the scheme whitelist, right?

**Comment by yurydelendik** [comment]
> this looks a bit like what was intended was checking that the URL wasn't invalid

Yes, this the exact security issue: even if document is not displayed at all, that will prevent a download button to execute `javascript:alert('hi')` URL, when smart user decide to hit this button. This url can be provided via `?file=` parameter.

**Comment by Snuffleupagus** [comment]
> Looking at what it was originally intended to prevent (XSS via links inside a PDF document), allowing JS to change that list seems fine to me (if I can run JS in the context of PDF.js, I could as well just do whatever I allow PDF.js to do myself, no?).

The URL validation, used for e.g. link annotations, runs in a worker-thread hence it shouldn't be easy to modify this as runtime. If it were easy to change, there'd be no point in the validation in the first place.  

---

Given comments https://github.com/mozilla/pdf.js/issues/10057#issuecomment-419968571 and https://github.com/mozilla/pdf.js/issues/10057#issuecomment-420061607, this doesn't seem like something you want to support, closing as WONTFIX?
