### ISSUE TITLE
Ios 11.0.1 version of the phone bold text blur.

### ISSUE THREAD

**Issue by Z1042420083** [mozilla/pdf.js#10068]
Currently only found this version number has problems, please help us to see.
Example: https://mozilla.github.io/pdf.js/web/viewer.html?file=https://z1042420083.github.io/pdfExample/abc.pdf

**Comment by timvandermeij** [comment]
Could you provide a screenshot of the rendering problem? Moreover, which browser and browser version are you using?

**Comment by Z1042420083** [comment]
WeChat built-in browser
version 6.7.2

**Comment by timvandermeij** [comment]
Please upload a screenshot too. Note that we have had reports about WeChat before and we don't explicitly support it (see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support).

**Comment by Z1042420083** [comment]
WeChat:
![webwxgetmsgimg](https://user-images.githubusercontent.com/20398767/45594615-9ccfcb80-b9d0-11e8-954f-6bc93b21d9a2.jpg)
Screenshot of Safari browser:
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/20398767/45594625-bd982100-b9d0-11e8-829b-20d91e45749c.jpg)

**Comment by retrazil** [comment]
Hi, @Z1042420083 
Does this happen even when you zoom in?

**Comment by Snuffleupagus** [comment]
> WeChat built-in browser
> version 6.7.2

First of all, that's not a browser that we know anything about and consequently it's unsupported.

Furthermore this looks like a platform/browser bug (perhaps `canvas`-related), rather than a general PDF.js one, hence this unfortunately doesn't seem like something that can be fixed *here*.
