### ISSUE TITLE
How to load a pdf using url in pdf.js

### ISSUE THREAD

**Issue by TRemya** [mozilla/pdf.js#10065]
Configuration:
- Google chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Windows 7
- pdfjsVersion : '1.5.188'
- pdfjsBuild : '0e2d50f'

I have tried PDF.js sample application to load a pdf in html.It working fine for me. I need to load a pdf using the url (Not to browse the pdf file from system). I have a PDF list and  to click anyone of the pdf from list I want to load that particular pdf in an html. Please help to find a solution.

**Comment by timvandermeij** [comment]
You can give a URL to the `getDocument` API call (refer to https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L40-L41). For loading PDF files from another domain, read https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr.

**Comment by TRemya** [comment]
I have tried the below code
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>PDF.js</title>
  </head>
  <body>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
    <script type="text/javascript" src="https://mozilla.github.io/pdf.js/build/pdf.worker.js"></script>
    <script>
    $(document).ready(function () {
    var url = "https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf";

// Asynchronous download PDF
PDFJS.getDocument(url)
  .then(function(pdf) {
    return pdf.getPage(1);
  })
  .then(function(page) {
    // Set scale (zoom) level
    var scale = 1.5;

    // Get viewport (dimensions)
    var viewport = page.getViewport(scale);

    // Get canvas#the-canvas
    var canvas = document.getElementById('the-canvas');

    // Fetch canvas' 2d context
    var context = canvas.getContext('2d');

    // Set dimensions to Canvas
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Prepare object needed by render method
    var renderContext = {
      canvasContext: context,
      viewport: viewport
    };

    // Render PDF page
    page.render(renderContext);
  });
  })
  </script>
  <canvas id='the-canvas'></canvas>
  </body>
</html>

This shows and error 
" Uncaught ReferenceError: PDFJS is not defined
    at HTMLDocument.<anonymous> (index1.html:16)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
(anonymous) @ index1.html:16
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
w.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2

**Comment by timvandermeij** [comment]
You're using the library from `mozilla.github.io`, which is the latest (2.0) version of PDF.js. For that version the global `PDFJS` variable is removed. Refer to https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L13-L20 for how to use it in version 2.0. Note that version 1.5 that's in the original description is really old and you should definitely upgrade, but if you do, use one of the CDNs from https://github.com/mozilla/pdf.js#including-via-a-cdn instead of getting it from `mozilla.github.io` directly in the `<script>` tag.
