### ISSUE TITLE
Give find_matches_count and find_matches_count_limit proper plural forms

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#10067]
Follow-up to #10028 (as noted by @flodolo in the [pdf.js 2.0.843 update bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1489996#c9)):
> Both find_matches_count and find_matches_count_limit need proper plural forms to be correctly localized.

@Snuffleupagus, is that something you can take?

**Comment by Snuffleupagus** [comment]
> Follow-up to #10028

I think you meant issue #10052 here :-)

> @Snuffleupagus, is that something you can take?

Unfortunately I cannot guarantee that I'll have time to work on this, considering that it's (in my opinion) a fairly minor issue which as outlined in https://bugzilla.mozilla.org/show_bug.cgi?id=1489996#c12 shouldn't really affect the PDF Viewer in Firefox.
