### ISSUE TITLE
Color difference

### ISSUE THREAD

**Issue by karan-sdplabs** [mozilla/pdf.js#10079]
Attach (recommended) or Link to PDF file here: https://github.com/mozilla/pdf.js/files/1058844/ColorIssue.pdf

Configuration:
- Web browser and its version: Google Chrome v69+
- Operating system and its version: macOSX 10.13.2
- PDF.js version:  using npm modeule pdfjs-dist v2.0.489
- Is a browser extension: no

Steps to reproduce the problem:
1. using this exact code https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js

What is the expected behavior? (add screenshot)
https://drive.google.com/file/d/1nWgH1Mxx-1eNze8H7ysM0UZ0jdPD6hvn/view?usp=sharing

What went wrong? (add screenshot)
https://drive.google.com/file/d/1elzdLXmT7OC97mB8qpNGjZN17VTr4tiq/view?usp=sharing

As you can see the color difference and i know its some kind of icc profile issue but is there any way to fix this.

**Comment by karan-sdplabs** [comment]
yeah but the issue is same and i cant share my pdf so this was the perfect example

**Comment by karan-sdplabs** [comment]
will do that but is there any fix to this problem?? stuck with this issue for almost a week or 2

**Comment by SamyCookie** [comment]
ICC profiles are not yet implemented, and as far as I know nobody is working on this, do not expect a solution in a near future.

**Comment by brendandahl** [comment]
Closing as a duplicate. If you control the generation of the PDF you can try exporting it without the ICC color space and use RGB.

**Comment by varunkumarhs** [comment]
how to give change color space from cmyk to srgb in pdf.js
