### ISSUE TITLE
Issues list related to IE 11 / Edge

### ISSUE THREAD

**Issue by AdityaEVS** [mozilla/pdf.js#10083]
Hi, 

Is there any documentation exists pertaining to list of all features not supported in IE 11 & Edge?

**Comment by timvandermeij** [comment]
No, we don't have that, but if someone would like to contribute if we would be happy to add it to the wiki. I think the best way to find out what's not supported is by going through all the issues labeled with `4-ie-edge-specific` and `4-ie11-specific`.
