### ISSUE TITLE
UnexpectedResponseException and RangeError in iOS

### ISSUE THREAD

**Issue by vitorcmaia** [mozilla/pdf.js#10089]
- Web browser and its version: iOS Sencha/Cordova app, PDF is opened within getViewport(...)
- Operating system and its version: iOS 10.1.1, iPhone 5
- PDF.js version: v1.9.426
- Is a browser extension: No

Steps to reproduce the problem:
```
PDFJS.getDocument(params).then(function(pdfDoc) {
    // ...
}).then(null, function(error){
    // HERE :(
});
```

What is the expected behavior?
- I expect that the pdf files open. It works properly in the Android build.

I have a Sencha/Cordova mobile project and the app needs to open several pdf files.
When I try to open the files, I receive 2 kinds of errors in iOS (Android is OK).

Error 1: "RangeError: Maximum call stack size exceeded."
Error 2: "UnexpectedResponseException: Unexpected server response (206) when retrieving PDF."

There are older issues related to Error 2, but the current version of the lib already sets disableRange = true if isSafari or isIOS.

[PDF with Error 1](http://pac.gov.br/pub/up/relatorio/b39fb8e41748d367b97fc39525172bcb.pdf)
[PDF with Error 2](http://pac.gov.br/pub/up/relatorio/a8af372ad028771950c6c82d9dbf8262.pdf)

Thanks in Advance!

**Comment by vitorcmaia** [comment]
Update:
The problem happens in Android too. All pdfs are returning Error 1: RangeError: Maximum call stack size exceeded.

Tested in a Moto G4 Plus, Android 7.0.

It was working in Android with a very old version, 0.8.1

**Comment by Snuffleupagus** [comment]
> PDF.js version: v1.9.426

That version is quite old, and is no longer supported. Please make sure that you test with the *latest* version (i.e. `2.0`) instead, since I believe that https://github.com/mozilla/pdf.js/issues/10089#issuecomment-423266308 might not work otherwise.

**Comment by vitorcmaia** [comment]
> Please make sure that you test with the _latest_ version (i.e. `2.0`) instead

@Snuffleupagus The current stable version is 1.9.426 in the download page: https://mozilla.github.io/pdf.js/getting_started/#download
The stable version is not supported anymore?

**Comment by timvandermeij** [comment]
It looks like https://github.com/mozilla/pdf.js/blob/master/pdfjs.config never got bumped and therefore the download page never got updated. I'll create a follow-up issue for that, but the latest stable release is 1.10.100 and the latest pre-release is 2.0.550 (found here: https://github.com/mozilla/pdf.js/releases).

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and that it only affects a *particular* platform/browser (rather than the general PDF.js library), is it meaningful to keep this this issue open?
