### ISSUE TITLE
Document Rendering Slowly on Safari only (OK on Chrome) with iGPU

### ISSUE THREAD

**Issue by evadne** [mozilla/pdf.js#10085]
Attach (recommended) or Link to PDF file here:
[basho_final.pdf](https://github.com/mozilla/pdf.js/files/2398418/basho_final.pdf)

Configuration:
- Web browser and its version: Safari Version 12.0 (13606.2.11)
- Operating system and its version: macOS 10.13.6 (17G65)
- PDF.js version: Both latest and pdfjs-dist 1.10.97, other versions untested
- Is a browser extension: No

Steps to reproduce the problem:
1. Ensure the Mac is running on integrated graphics
2.  Load document in Safari with [Mozilla PDF.js Demo](https://mozilla.github.io/pdf.js/web/viewer.html?file=)
3. Load document in Chrome with [Mozilla PDF.js Demo](https://mozilla.github.io/pdf.js/web/viewer.html?file=)
4. Navigate around

What is the expected behavior? (add screenshot)
Rendition performance in Safari should not be quite so slow

What went wrong? (add screenshot)
Rendition performance in Safari is at least 10x slower than Chrome

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A, problem reproducible with stock demo

**Comment by Snuffleupagus** [comment]
> Rendition performance in Safari is at least 10x slower than Chrome

If this issue really is browser specific, it seems unlikely to be something that can/should be fixed in the PDF.js library; closing as WONTFIX or INVALID?
