### ISSUE TITLE
canvas edit

### ISSUE THREAD

**Issue by kishandonepudi** [mozilla/pdf.js#10082]
Attach (recommended) or Link to PDF file here:

Configuration:
- Chrome browser and its Version 68.0.3440.106 :
- Windows  OS and its version 10:
- PDF.js with version 5.6.0:
- Is a browser extension - no:

Steps to reproduce the problem:
1. I have implemented free-hand draw on canvas generated on pdf.js at each page.
when i press download it is not downloading the lastest canvas element. please let me know where to bind upodated canvas in download layer2.

What is the expected behavior? 
I was expecting to save the updated canvas element and download the PDF.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/17450660/45673664-ea6f4400-bb48-11e8-9b86-7451e2836afb.png)

**Comment by timvandermeij** [comment]
Downloading only gives you the raw PDF data. Depending on how you allow free-hand drawing this should result in annotations that have to be injected in the PDF stream. This is not trivial and out-of-scope for PDF.js since we don't support writing PDF files at all.
