### ISSUE TITLE
some fonts not rendered correctly(not showing up)

### ISSUE THREAD

**Issue by gHensges** [mozilla/pdf.js#10084]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 68.0.3440.106
- Operating system and its version: Windows 10 Pro, 1709 build 16299.611
- PDF.js version: Actual Demo Project
- Is a browser extension: No.

Steps to reproduce the problem:
1. Just load attached pdf.
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/45738100-daf70600-bbef-11e8-9f8f-491c2b9827b1.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/45738173-0a0d7780-bbf0-11e8-8ecd-7effea84284f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[Rechnung_nach_Import_unleserlich.pdf](https://github.com/mozilla/pdf.js/files/2395875/Rechnung_nach_Import_unleserlich.pdf)

**Comment by THausherr** [comment]
Same on W7 with FF62.

**Comment by gHensges** [comment]
Nice that it is understood where the issue is coming from. But what about a fix. Other pdf-renderer are able to deal with this kind of fonts!
