### ISSUE TITLE
Problems encountered in modifying viewer.html

### ISSUE THREAD

**Issue by XguangY** [mozilla/pdf.js#10092]
When I use PDF. Js, the default official demo can be well executed.A problem arises when modifying the demo.In the official demo, I modify let DEFAULT_URL in viewer.js = '***.pdf';Replace his default Settings and still render a 14 - page blank page when run.How to solve it?

**Comment by Snuffleupagus** [comment]
Unfortunately it's impossible to tell what the problem might be, given the *very* limited information provided.
Please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md before opening an issue, and that you provide as much of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md as possible in order for the issue to be actionable.

**Comment by timvandermeij** [comment]
Closing for now because all information from the issue template is missing. Please provide the modified viewer as a runnable example and provide the PDF file that fails to render.
