### ISSUE TITLE
canvas and text inconsistent

### ISSUE THREAD

**Issue by 76peter** [mozilla/pdf.js#10105]
![image](https://user-images.githubusercontent.com/26475878/46030141-ea161080-c127-11e8-96ba-343b71233f2e.png)

**Comment by timvandermeij** [comment]
Closing since practically all information requested in the issue template is missing. In particular, we need the PDF file itself in order to look into the issue; just a screenshot is not enough. If that's provided, we can reopen this.

**Comment by 76peter** [comment]
I tested to find that it was a problem with my web embedding, and there was no problem with opening it alone.
It could be compatibility issues caused by embedding.
thanks
