### ISSUE TITLE
Can't open file containing special character '&' on filename

### ISSUE THREAD

**Issue by italospedini** [mozilla/pdf.js#10102]
Hi. I can't open a file that contains the special character '&' on its filename.

The filename is 'MOC & Tracking.pdf'. So in the url it shows viewer.html?file=MOC%20&%20Tracking.pdf but I got 'Missing PDF file.' message. I tried to replace to 'MOC%20%26%20Tracking.pdf' and it doesn't work.

Any change I could do on viewer.js to do it works?

If I use the same file with no character & it works.

Thanks.

Attach (recommended) or Link to PDF file here:

Steps to reproduce the problem:
1.  point the url to a file with special character '&';

**Comment by timvandermeij** [comment]
You'll need to URL encode the filename. Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer.

**Comment by italospedini** [comment]
Didn't work after encode filename. Still can't find the pdf file. Any idea?
