### ISSUE TITLE
Chrome - Iframe - Preview for printing and printing are 4 times smaller than expected

### ISSUE THREAD

**Issue by cycnos** [mozilla/pdf.js#10107]
Attach (recommended) or Link to PDF file here:
Problem happens with any pdf

Configuration:
- Web browser and its version:
         Google Chrome
         Version 69.0.3497.100 (Build officiel) (64 bits)
- Operating system and its version:
          Windows 10 enterprise edition 1803
           OS version : 17134.286
- PDF.js version:    1.10.100     
- Is a browser extension:  no

Steps to reproduce the problem:

1.  Setup a pdf.js in an iframe
2. Upload a document in the pdf.js
3.  Click on the print button
4.  Chrome display a preview of the pdf for print which is two times smaller in both dimensions and therefore the document is top left.
5. If you print the document it has the dimensions displayed in the preview which are wrong

What is the expected behavior? (add screenshot)
The document should be printed in the right dimensions.

What went wrong? (add screenshot)
preview before print is 4 times smaller (width/2 and height/2) and therefore the printing is 4 time smaller than expected.

other informations : 
This problem only happens when called in iframe.
The problem only happens with Chrome (works fine with Edge and Firefox) 

=> I already tried to fix the bug by  doubling the dimensions when we are in Chrome. This workaround works fine for the iframe but when I'm not in iframe documents are two time bigger than expected.

Thanks

**Comment by Snuffleupagus** [comment]
I've just tested printing (locally) from a PDF.js demo viewer placed in an `iframe`, using PDF.js version `2.9.79`, in both Firefox Nightly 89 *and* Google Chrome Beta 90.0.4430.72, and I cannot reproduce any of the problems described above.

Given the age of this issue, and that it mentions what's now quite old versions of both Google Chrome *and* the PDF.js library, this is either completely fixed or possibly a bug in the *browser* itself (in which case we unfortunately cannot help).
