### ISSUE TITLE
How can I only load some page of the pdf file at viewer.js

### ISSUE THREAD

**Issue by hzjux001** [mozilla/pdf.js#10108]
How can I only load some page of the pdf file?
for example：
 I want the users only can see the specified page.
user1 only can see page1 and page5,
user2 only can ses page2 and page10 etc.

**Comment by timvandermeij** [comment]
The default viewer loads all pages. You can make your own components-based viewer using e.g., https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L46 to show only a subset of the pages.
