### ISSUE TITLE
Implement find bar close event in `mozilla-central`

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10115]
Refer to https://github.com/mozilla/pdf.js/pull/10100#issue-217459702.

**Comment by Snuffleupagus** [comment]
I'll try to submit the `mozilla-central` patch with a new "findbarclose" event dispatched from the browser findbar, and see what the reviewers say, once PR #10100 has landed in `mozilla-central`.

**Comment by Snuffleupagus** [comment]
The new "findbarclose" event has now landed in `mozilla-central`, so this issue can be closed as fixed :-)

**Comment by timvandermeij** [comment]
Awesome work!
