### ISSUE TITLE
Examples are not working on FF 62.0 / linux

### ISSUE THREAD

**Issue by ppazos** [mozilla/pdf.js#10124]
https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

First and third example are just blank on the HTML view.

![screenshot_2018-10-02_15-11-17](https://user-images.githubusercontent.com/1278556/46368009-77d88b00-c655-11e8-8f44-3b723c828fe6.png)

**Comment by timvandermeij** [comment]
It looks like the CDN is down. This will probably be fixed soon, but we'll keep this open to monitor the situation. Thank you for reporting.

**Comment by timvandermeij** [comment]
The examples work again. It looks like the CDN was down and slow afterwards, but is up again now.

**Comment by timvandermeij** [comment]
It looks like `cdn.mozilla.net` is still down/slow. I cannot reach http://cdn.mozilla.net/pdfjs/helloworld.pdf anymore.

@yurydelendik @brendandahl Could you contact the person in change of the CDN to report the issue?

**Comment by yurydelendik** [comment]
At this moment, it works for me. Maybe it is temporary.

**Comment by yurydelendik** [comment]
Reported https://bugzilla.mozilla.org/show_bug.cgi?id=1497881

**Comment by JohannesBe** [comment]
It's already December by now and the cdn stuff is still a problem. Can't we rehost the PDF somewhere else (e.g. on github)?

**Comment by timvandermeij** [comment]
I agree. We should switch to using the versions from GitHub, e.g., https://github.com/mozilla/pdf.js/raw/master/examples/learning/helloworld.pdf for the hello world PDF file and https://github.com/mozilla/pdf.js/raw/master/web/compressed.tracemonkey-pldi-09.pdf for the Tacemonkey PDF file.

@yurydelendik Could you perhaps adjust the Fiddles to point to these new links?

**Comment by yurydelendik** [comment]
It is cross-origin request, so nothing coming though to https://jsfiddle.net/ from https://github.com/

**Comment by yurydelendik** [comment]
Fixed by using raw.githubusercontent.com/ hosted content
