### ISSUE TITLE
Named Webpack Chunks

### ISSUE THREAD

**Issue by ccorcos** [mozilla/pdf.js#10127]
Hey there, can you add webpack chunk name comments? That way I can know which files in my build are related to this package and I can handle them separately.

https://github.com/wojtekmaj/react-pdf/issues/274

**Comment by timvandermeij** [comment]
Isn't this already implemented by #10015? If not, could you elaborate on what the issue exactly is and how you would expect it to work?

**Comment by timvandermeij** [comment]
Closing since there is no response and the issue above looks very similar, which has been fixed already.
