### ISSUE TITLE
"Invalid PDF structure" error

### ISSUE THREAD

**Issue by emme2018** [mozilla/pdf.js#10121]
Attach (recommended) or Link to PDF file here:

Configuration:
- Chrome 69.0.3497.100, Firefox 62.0.2, IE11, MS Edge, Chrome Canary
- Windows 10
- PDF.js version: 1.7.225
- Is a browser extension:

Steps to reproduce the problem:
1. Stream the document on the browser via PDF.js v1.7.225
2.

What is the expected behavior? (add screenshot)
Document is streamed and rendered successfully on the browser. 

What went wrong? (add screenshot)
Document is not getting rendered on the browser and instead seeing "Invalid PDF structure error"
![image](https://user-images.githubusercontent.com/43763872/46315077-64b4b500-c59a-11e8-9b86-6a78a06a87c7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It's not possible to resolve this without the actual PDF file and more information about your environment. Do you use the default viewer or did you make customizations?

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.
