### ISSUE TITLE
Pdf.js can't open 1.1G pdf file in Chrome

### ISSUE THREAD

**Issue by jaaazzz** [mozilla/pdf.js#10131]
Attach (recommended) or Link to PDF file here: Any file larger than 1G

Configuration:
- Web browser and its version: chrome 69.0.3497.100
- Operating system and its version: windows 10
- PDF.js version: PDF.js v1.10.100 (build: ea29ec83)
- Is a browser extension: no
![image](https://user-images.githubusercontent.com/15264991/46470647-f4ac6600-c809-11e8-8e7c-ce71a7e69139.png)

PDF.js v1.10.100 (build: ea29ec83)
信息：Invalid typed array length: 1142375667
No problem in Firefox

**Comment by timvandermeij** [comment]
Closing since the required PDF file is not provided. Moreover, this should probably be reported to the Chrome issue tracker since it seems like a browser limitation (as you don't have the issue with Firefox).
