### ISSUE TITLE
Suggested improvements for the "Benchmarking your changes" Wiki page

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#10130]
There's a couple of smaller improvements that could make sense for the https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes page:
 - In the example `benchmark.json` file, use `"rounds": 50,` instead since a lower number of rounds often doesn't given sufficient statistical confidence.
 - In the example `benchmark.json` file, use `"type": "eq"` instead since often when benchmarking is done rendering performance is what matters the most (thus giving someone copying that snippet a better starting point).
 - Change the `$ gulp generic` commands (two occurrences) to read `$ SKIP_BABEL=true gulp generic` instead. That way you're actually testing the code as-is, rather than its Babel translated version, which seems *much* more appropriate here.

**Comment by timvandermeij** [comment]
I just made the changes to the page. Thank you!
