### ISSUE TITLE
On bookmark (outline) click scale changes

### ISSUE THREAD

**Issue by RudmanMario** [mozilla/pdf.js#10147]
In web viewer when I click on the bookmark (outline) the scale of the document changes to "Page Width". This is probably not an issue but I'm not sure why is it default behavior. Is there a way to stop scale change on bookmark click?

**Comment by timvandermeij** [comment]
This is expected behavior; refer to https://github.com/mozilla/pdf.js/issues/9235#issuecomment-349107861.
