### ISSUE TITLE
CMapCompressionType is not exported in the pdf.js distribution

### ISSUE THREAD

**Issue by cemerick** [mozilla/pdf.js#10148]
As implemented in https://github.com/mozilla/pdf.js/pull/8064 and demonstrated in https://github.com/mozilla/pdf.js/issues/8881#issuecomment-327822546, a `CMapReaderFactory` must resolve a promise with an object containing a `compressionType` slot, the value of which should be one of the `CMapCompressionType` enumeration.

Unfortunately, `CMapCompressionType` is not exported by pdf.js as it is currently built, so implementing `CMapReaderFactory` requires copy/pasting the enumeration, or maybe hard-coding the value of `compressionType` (e.g. if all of the cmaps being loaded from disk are known to be compressed).

No PR at this time; I can see at least three reasonable places where `CMapCompressionType` could be exported, but I'd rather not guess at the maintainers' desired aesthetic. :smile:

**Comment by timvandermeij** [comment]
Good point. I think this should be added to https://github.com/mozilla/pdf.js/blob/6f30cbb478839df1a58d154684ad280923dcef8e/src/pdf.js#L104 since `Util` is also there and comes from the same file.
