### ISSUE TITLE
There is just NO print preview in pdf.js

### ISSUE THREAD

**Issue by MatthiasELISEE** [mozilla/pdf.js#10158]
Configuration:
- Web browser and its version: Firefox 63
- Operating system and its version: all
- PDF.js version: Firefox's version
- Is a browser extension: no

What is the expected behavior? Just like Chrome's plugin. Maybe not just as advanced

**Comment by Snuffleupagus** [comment]
The PDF viewer built-in to Firefox supports the same kind of Print Preview feature as the rest of the browser, please see e.g. https://support.mozilla.org/kb/how-print-web-pages-firefox#w_printing-a-web-page for more information on that topic.

If you're referring to Print button on the PDF viewer toolbar itself, then that one (probably for technical reason) only supports direct printing.

**Comment by timvandermeij** [comment]
Closing since this is answered by the comment above.
