### ISSUE TITLE
SVG renderer misses footnotes

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#10151]
Steps to reproduce the problem: 
Example: [r2l.pdf](https://github.com/mozilla/pdf.js/files/2470373/r2l.pdf)
````
npm install
gulp dist-install
wget https://github.com/mozilla/pdf.js/files/2470373/r2l.pdf
node examples/node/pdf2svg.js /tmp/r2l.pdf
````

What went wrong?
Footnotes are missing, from page 2 to page 16, e.g.:
![page-2](https://user-images.githubusercontent.com/274624/46828574-ce537100-cd9b-11e8-8643-fac8a2937f69.png)

**Comment by timvandermeij** [comment]
Fixed by #10162. Open issues already exist for gradient support.
