### ISSUE TITLE
Problems with CORS & PDF.JS

### ISSUE THREAD

**Issue by joeangry** [mozilla/pdf.js#10159]
Hi.
I'm trying to load a PDF from an external site which I'm also the owner of (Azure App Service). I've added the following headers to all my requests but I get an odd chain of requests whenever I try to load external PDFs.

**Headers:**

Access-Control-Expose-Headers: Accept-Ranges,Content-Encoding,Content-Length,Content-Range
Access-Control-Allow-Headers: Content-Range,Range

As you can see I get the initial 200 OK just fine followed by two 200 _OPTIONS_ requests. Finally it alternates between 200 and 206 which isn't the expecte behavior.
When I tested it on a local site the initial request got a 200 response followed by 206 until the PDF had fully loaded.

What obvious thing am I missing here?

Configuration:
- Web browser and its version: Any browser (tested on Chrome lastest, Microsoft Edge lastest, Firefox latest)
- Operating system and its version: Windows 10, 1809
- PDF.js version: v1.9.426
- Is a browser extension: No

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/4882368/47002244-b75ea700-d12c-11e8-9a02-b1dcd2a7aed7.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/4882368/47001608-25a26a00-d12b-11e8-95e7-3eb6d5430c03.png)

**Comment by Snuffleupagus** [comment]
The chances of someone being able to help here will most likely increase if you, as asked for in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), provide access to a working example (rather than just screen-shots).

**Comment by dmichon-msft** [comment]
The `Range` header is not in the set of allowed headers defined for a [Simple Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests), and therefore a CORS preflight request is always required when it is present.

**Comment by timvandermeij** [comment]
Closing as answered.

**Comment by rohitcoder** [comment]
Solved, you should use this solution https://stackoverflow.com/a/62953428/6110557 this works for me!
