### ISSUE TITLE
Implement beginAnnotations and endAnnotations for SVG

### ISSUE THREAD

**Issue by valgussev** [mozilla/pdf.js#10165]
Configuration:
- PDF.js version: 2.0.550

Steps to reproduce the problem:
1. Render document in SVG mode `renderMode="svg"`

What is the expected behavior? (add screenshot)
Rendering annotations same way as they rendered on canvas

What went wrong? (add screenshot)
```
Warning: Unimplemented operator beginAnnotations
Warning: Unimplemented operator endAnnotations
```

**Comment by mishase** [comment]
Is there any plans to implement these operators soon?
