### ISSUE TITLE
Colors are incorrectly rendered in old versions of IE11

### ISSUE THREAD

**Issue by unpollito** [mozilla/pdf.js#10178]
I'm trying to display a PDF file generated using PDFKit in IE 11.0.9600.16428 and I am finding some issues with it. This is a file containing only text, rectangles and lines of various colors. However, all of these are painted black; colors are ignored.

Said version of IE11 is a fairly old one and it does not support Uint8ClampedArray, so I added [this polyfill](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js) to work around the issue. However, even after adding the polyfill, it doesn't behave as expected and all I get are black colors. I put some breakpoints in the worker thread and realized that, even though the colors are coded in RGB, only the N methods (setStrokeColorN and so on) are being invoked.

Could you possibly shed any light into what could be causing this issue or whether there is a way in which I could add polyfills or alter the library to support old IE11 versions?

(Incidentally, this works just fine in recent versions of IE 11 such as 11.345.17134.0. It's the old ones I want to support as well.)

**Comment by parrotgeek1** [comment]
Weird. I had no idea that Microsoft improved compatibility In ie11 between windows 8 and 10. They had no reason to do that...edge exists.

**Comment by timvandermeij** [comment]
Closing since the information above should be sufficient to find out what's missing in older IE11 versions. We only support the latest IE11 in which it's indicated to work.
