### ISSUE TITLE
Current View button does not work (Bug 1484471)

### ISSUE THREAD

**Issue by IdmFoundInHim** [mozilla/pdf.js#10186]
Configuration:
- User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
- Built-in to Firefox Nightly

Steps to reproduce the problem:
1. Open a local PDF File in Firefox PDF viewer
2. Click the 'Current View' button
![image](https://user-images.githubusercontent.com/30935172/47605506-3ed1d300-d9d5-11e8-99b1-b4f3406e3c79.png)

What is the expected behavior?
The URL in the address bar should change to include a location to jump to. Additionally, the context menu options 'Open in new tab' and 'Open in new window' should open the same PDF at the current location.

What went wrong?
The URL in the address bar does not change. The context menu options 'Open in new tab' and 'Open in new window' open blank pages.

See [Bug 1484471](https://bugzilla.mozilla.org/show_bug.cgi?id=1484471) on bugzilla.mozilla.com

**Comment by timvandermeij** [comment]
Works for me on https://mozilla.github.io/pdf.js/web/viewer.html. The URL in the address bar changes. It looks like an upstream bug in Nightly then.

**Comment by Snuffleupagus** [comment]
This is already being tracked in Bugzilla, and there's really no need to track this at Github as well.
Furthermore, https://github.com/mozilla/pdf.js/pull/6480#issuecomment-148209142 should explain why this doesn't (currently) work as expected.

**Comment by timvandermeij** [comment]
Closing since this is tracked on Bugzilla already.
