### ISSUE TITLE
pdfjs-dist is still 2.0.489

### ISSUE THREAD

**Issue by fengerzh** [mozilla/pdf.js#10189]
Attach (recommended) or Link to PDF file here:
https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

What is the expected behavior? (add screenshot)
Expect to upgrade to 2.0.550 or above.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2883744/47612209-bcb6dc80-dab0-11e8-8ce4-a65ba051c976.png)

**Comment by Snuffleupagus** [comment]
This is already being tracked in https://github.com/mozilla/pdf.js/projects/5#card-14273384, hence this issue can be closed.
