### ISSUE TITLE
Partial PDF loads not working on IE11 and Edge

### ISSUE THREAD

**Issue by whjwhj** [mozilla/pdf.js#10180]
When accessing the standard viewer which you folks are hosting here:

http://mozilla.github.io/pdf.js/web/viewer.html#disableAutoFetch=true&disableStream=true

From IE11 and Edge I see the following in the inspector:

![ie11_moz_github](https://user-images.githubusercontent.com/1638384/47456753-f4fda880-d79a-11e8-8c7c-022744ff1d8c.PNG)

Please notice how it first downloaded the entire PDF (with the response code of 200) and then it downloads the entire PDF again piecemeal via a series of partial content (206) downloads. Also note the total MB transferred at the bottom is roughly twice the size of the PDF in question.

On Chrome (and Firefox) I see:

![chrome_moz_github](https://user-images.githubusercontent.com/1638384/47456881-4ad25080-d79b-11e8-96f4-6c8440d30f00.png)

Interesting it downloads the entire PDF right away as well. But at least it avoided the subsequent redundant downloads by accessing the PDF in cache? (I was careful to clear the browser's cache before all tests.)

On a much larger file (17MB vs. 993KB) on IE11 & Edge I see the following:

![ie11_larger_file](https://user-images.githubusercontent.com/1638384/47457115-d4821e00-d79b-11e8-96d0-c4e4b407d12f.PNG)

It first downloads the full 17MB via the 200 request and then downloads it ALL again via subsequent partial content 206 requests. It does this in spite of me never asking the viewer to display anything except the first page. Probably takes a good 5 minutes or so before it sucks it all down (again). The total MB transferred will eventually end up being a bit over 34MB, roughly twice the size of the PDF.

That same larger file via chrome (and firefox):

![chrome_larger_file](https://user-images.githubusercontent.com/1638384/47457288-507c6600-d79c-11e8-8d15-450fc96ee2c4.png)

The inital 200 requests cuts off with only 4K transferred and then the partial requests begin. Which is exactly what I would expect to see for ALL browsers.

The viewer I used for the larger 17MB file was a fresh v1 "stable" download from github although I downloaded and tested the v2 "beta" version as well and observed the same questionable behavior. And of course the 'tracemonkey' examples are from the viewer you folks are hosting yourselves at github.

Is this a bug? Or am I confused somehow? Whatever assistance you can offer is greatly appreciated.

whj

**Comment by freefire8** [comment]
I don't know if it could help you but i had the same behavior, i then realised that the onDocumentSuccess was setting a property in my state, then it renders the page even if the pageIndex doesn't change, then it reloads automatically, etc...

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
