### ISSUE TITLE
PDF content is empty in IE11

### ISSUE THREAD

**Issue by FengLiang1** [mozilla/pdf.js#10192]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: win 7
- PDF.js version:  master, 2.0843, 1.10
- Is a browser extension: 

Steps to reproduce the problem:
1.  Start the service and enter the URL(http://localhost:8888/web/viewer.html) by IE11

What is the expected behavior? (add screenshot)
![aa](https://user-images.githubusercontent.com/24800883/47640653-fd8d1f00-db9e-11e8-9ae2-5ce884248938.png)

**Comment by Snuffleupagus** [comment]
> Start the service and enter the URL(http://localhost:8888/web/viewer.html) by IE11

Please refer to the README, in particular https://github.com/mozilla/pdf.js#getting-the-code which explains why this doesn't work:
> [...]
>
> and then you can open:
>
> + http://localhost:8888/web/viewer.html
>
> Please keep in mind that this requires an ES6 compatible browser; refer to [Building PDF.js](https://github.com/mozilla/pdf.js/blob/master/README.md#building-pdfjs) for usage with older browsers.

The *built* viewer, see e.g. the demo available at https://mozilla.github.io/pdf.js/web/viewer.html, does work in IE11. However IE11 cannot be used for development, as is also mentioned in https://github.com/mozilla/pdf.js/wiki/Contributing#prerequisites.
