### ISSUE TITLE
v2.0.943 not available on NPM

### ISSUE THREAD

**Issue by Rhuansantos** [mozilla/pdf.js#10194]
Hi, I am looking for some bug fixes on the latest release v2.0.943. When will that become available on NPM for pdfjs-dist? I see the tag release on pdfjs-dist repo but not on NPM, did the hook failed?

**Comment by timvandermeij** [comment]
This is a known problem; it's tracked on the project board at https://github.com/mozilla/pdf.js/projects/5 and hopefully fixed somewhere this week.
