### ISSUE TITLE
Search inside PDF

### ISSUE THREAD

**Issue by wahlforss** [mozilla/pdf.js#10195]
How can I search in the PDF programmatically? I am using require('pdf-js-dist') but can't get the find controller to work. 

I want to search for sentences to tag which pages they appear in.

**Comment by timvandermeij** [comment]
Version 2.0 of PDF.js (https://github.com/mozilla/pdf.js/releases/tag/v2.0.943) will most likely published to NPM somewhere this week. It contains quite a bit of improvements for the find controller logic after the discussions in #10120.

Basically, the API usage is shown in https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js as an example. If you clone the code and edit https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L34 to set a search term, the term will be highlighted. In the new version, it should be as easy as making the find controller (https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L41-L44), linking it to the viewer (https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L46-L51) and doing a search (https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L58).

Closing as answered; see the issue above for more details if you want to integrate a find bar. Provide a runnable example on JSFiddle if you need further assistance.
