### ISSUE TITLE
Can I annotate the pdf page and store in the database like mysql?

### ISSUE THREAD

**Issue by SaddamDeveloper** [mozilla/pdf.js#10193]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
PDF.js is a library for reading PDF files, so any writing (modification) actions are unsupported by us. You can however make an overlay over the pages and store the contents of that, but that is out of scope for the project.

**Comment by Snuffleupagus** [comment]
Also, this question is already answered in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations.
