### ISSUE TITLE
Thumbnail viewer has a small visual quirk

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10209]
Steps to reproduce:

1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html in Firefox.
2. Open the thumbnail viewer.
3. Click the first thumbnail.
4. Notice the blue selection (the size of a space character) just next to the thumbnail. If you hold the click on the thumbnail, it becomes red.

**Comment by wojtekmaj** [comment]
I can't reproduce that on Firefox 63.0 🤔

**Comment by timvandermeij** [comment]
I should have mentioned that I have this with Firefox 63.0 on Linux. Perhaps it's Linux-only then.

**Comment by freginold** [comment]
I could reproduce it in Firefox 62.0.3 on a Windows 7 PC.  Just upgraded to v63.0 and it doesn't happen now.
