### ISSUE TITLE
How to get a font used on the page?

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#10204]
Hi!
In v2.0.550, fonts used for rendering, like "g_d1_f1" were openly available for the whole document to use them. React-PDF used this behavior to create identically positioned text layers over canvas rendering and for annotations rendering.
It seems like in v2.0.943 this behavior is no longer true. The fonts are not "leaking" now (which I get is a good thing) so all I'm left is a Times New Roman fallback :)
Is there a way to get the old behavior back, or somehow stop fonts from being cleaned up after rendering?

Thanks!

**Comment by wojtekmaj** [comment]
In fact, this diagnosis may be wrong. It may be caused by #10205. I could be wrong that the fonts are not available - they now just use odd characters to render text. So now I can't write the text `Sample` in a pdf.js-loaded font, I would need to write `` instead. This forces me to choose between accessibility and displaying the text nicely.

**Comment by brendandahl** [comment]
This was because of #9340
