### ISSUE TITLE
Trouble loading IEEE Explore pdfs

### ISSUE THREAD

**Issue by parthe** [mozilla/pdf.js#10208]
Attach (recommended) or Link to PDF file here: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6557543

Configuration:
- Web browser and its version: Google Chrome 70.0.3538.77
- Operating system and its version: Windows 10 version 10.0.17134 Build 17134
- PDF.js version: 2.0.673
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Click the URL from an academic network or if you have access to IEEE Explore
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5085600/47867579-25f36400-ddbf-11e8-93de-42cde31d6549.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Possible solution: 
1. Option to disable the pdf viewer for specific sites/urls.
2. This option comes as the error message on this page itself if what I have shown cannot be fixed.

**Comment by timvandermeij** [comment]
Since I don't have access to this resource, could you post the information from the "More information" button in the screenshot, and any information from the browser console? I think this is just the IEEE website that doesn't serve the PDF file correctly, but this may allow us to verify.

**Comment by parthe** [comment]
Here's what it says:

PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure

**Comment by timvandermeij** [comment]
It looks like the website is not serving the PDF files correctly. Since we cannot access this resource, I would suggest contacting IEEE Explore support directly.
