### ISSUE TITLE
Adding new tab in the sidebar gives out errors

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10212]
Hi, i am adding a custom tab together with thumbnail, attachment and outlines. but the thing is, if i click on the 4th custom button that i added and show the contents , it gives out an error because it looks like either of the first 3 buttons need to have its contents visible.

```
ui_utils.js:313 Uncaught (in promise) TypeError: Cannot read property 'div' of undefined
    at backtrackBeforeAllVisibleElements (ui_utils.js:313)
    at getVisibleElements (ui_utils.js:457)
    at PDFThumbnailViewer._getVisibleThumbs (pdf_thumbnail_viewer.js:67)
    at PDFThumbnailViewer.forceRendering (pdf_thumbnail_viewer.js:251)
    at PDFRenderingQueue.renderHighestPriority (pdf_rendering_queue.js:76)
    at continueRendering (pdf_rendering_queue.js:165)
backtrackBeforeAllVisibleElements @ ui_utils.js:313
getVisibleElements @ ui_utils.js:457
_getVisibleThumbs @ pdf_thumbnail_viewer.js:67
```
I add  the hidden class to for example the thumbnail list if i wish to have the 4th custom icon content shown. But then that error message happens and it breaks

Any Ideas?

**Comment by Snuffleupagus** [comment]
Quoting from https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
I think you need to make a custom view at https://github.com/mozilla/pdf.js/blob/master/web/pdf_sidebar.js#L164, but as indicated it's impossible to tell without a runnable example. Closing until this is provided.

**Comment by chitgoks** [comment]
I did a workaround via css and just changed the location of the first 3 views to negative value with no pointer events and a negative z-index to be sure.
