### ISSUE TITLE
pdf文件有部分不能显示

### ISSUE THREAD

**Issue by cgletufo** [mozilla/pdf.js#10211]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
我本地上传pdf文件,后台在pdf文件上添加了一些东西，放回pdf文件的url，在浏览器中通过地址栏输入或者使用embed标签可以正常看到后台处理添加的东西。但是用pdf.js,就显示不出来后台处理添加的内容。这是什么原因呢？

**Comment by wojtekmaj** [comment]
I don't think anyone would be able to help you if you ignore the whole bug template _and_ use Chinese. Would you mind filling the form correctly and in English?

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided since there is currently nothing actionable in this issue.

**Comment by sukies** [comment]
@cgletufo 我也有遇到这个问题 请问后来解决了吗？怎么解决的？
