### ISSUE TITLE
Cannot Set a Specific PDF (fixed position) when I launch viewer.html - Message: Failed to fetch PDF.js v2.0.943

### ISSUE THREAD

**Issue by fpibbs** [mozilla/pdf.js#10218]
Cannot Set a Specific PDF (fixed position) when I launch viewer.html
[test.pdf](https://github.com/mozilla/pdf.js/files/2544924/test.pdf)
![pdf_js](https://user-images.githubusercontent.com/25976329/47951935-4b6fa180-df68-11e8-8d9b-07e4b535c66b.JPG)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: pdfjs-2.0.943-dist
- Is a browser extension: Chrome Versione 70.0.3538.77 (Build ufficiale) (a 64 bit) && Unreal Engine CEF 4.20.3 embedded Chromium CEF + BLUI Plugin

Steps to reproduce the problem:
1. Cannot tell PDF.js to open a specific file (eg. test.pdf) from the start
2. Cannot set fixed position to defaulturl var

Expected behaviour: Open directly the PDF file from fixed position

What went wrong: Failed to fetch Message
Message received:

PDF.js v2.0.943 (build: dc98bf76)
Message: Failed to fetch

**Comment by timvandermeij** [comment]
Closing until more information as requested is provided.

**Comment by fpibbs** [comment]
Ok, it works perfectly and fast into Unreal Engine Chromium CEF Browser via BLUI Plugin. Thanks all for support, with XAMPP server setup on my pc.
I passed this string to the UE4 plugin: 
http://127.0.0.1/PDF.js/web/viewer.html?file=http://127.0.0.1/PDF.js/web/PDF_Unreal_PDF_JS.pdf#zoom=page-width

![it_works](https://user-images.githubusercontent.com/25976329/47954177-86350200-df87-11e8-9ff5-6443a3cf9226.JPG)

Thanks all for the support.
