### ISSUE TITLE
PDF.JS AND SOCKET.IO

### ISSUE THREAD

**Issue by phpmydev** [mozilla/pdf.js#10213]
It seems that pdf.js uses xhr and does not address the usage of sockets for streaming pdf's to the browser.
Am I mistaken?  Is there a port for socket.io?   Thanks!

**Comment by timvandermeij** [comment]
I don't know of a port for `socket.io`, but we do have support for the streams API (https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) in PDF.js.
