### ISSUE TITLE
Error : Invalid PDF structure

### ISSUE THREAD

**Issue by ephoris1** [mozilla/pdf.js#10214]
Hello, I have an issue on some websites, mostly one (that I use a lot : Moodle), where all PDF show errors and can't be viewed directly in the browser (I use the last version of Brave on Windows 10). I can dowload the PDF but not see it directly. It shows this error message :
PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure

It usually works on other websites. 

I saw others had this issue on Github but I did not find how to fix it !

Configuration:
- Version 0.55.20 Chromium: 70.0.3538.67
- Operating system and its version: last update Windows 10 pro
- PDF.js version: seems to be v2.0.673 in the error message
- Is a browser extension: no, i can't disable it on Brave, it's built-in

Steps to reproduce the problem:
1. click on a PDF link on certain websites

Edit : the PDF works when I click on the Github link below, but doesn't on Moodle. Of course, PDF on Moodle always worked on all other browsers.

[Neurophysio 4 Synapses.pdf](https://github.com/mozilla/pdf.js/files/2544315/Neurophysio.4.Synapses.pdf)
![capture](https://user-images.githubusercontent.com/44714006/47943456-6b667d00-def6-11e8-8ded-f2a7888a3b5b.PNG)

**Comment by timvandermeij** [comment]
The PDF file that you provided does render just fine on https://mozilla.github.io/pdf.js/web/viewer.html, so I think it's related to the issue above that the file is not served properly by the web server.

**Comment by ephoris1** [comment]
Unfortunately, the pdf links don't work if you're not logged in on Moodle :/ 

Note : the PDF on this site work on other browsers

The console contains a lot of "Warning: Ignoring invalid character "33" in hex string" with different numbers

**Comment by timvandermeij** [comment]
> The console contains a lot of "Warning: Ignoring invalid character "33" in hex string" with different numbers

That may also be an indication that the web server is not serving the file correctly and possibly stripped off a bit of the response, causing the rest of the payload effectively to be corrupted. I'm just not sure if we can find out for sure without any example links. Does it only happen on Moodle or also on other public websites?

**Comment by Snuffleupagus** [comment]
> Is a browser extension: no, i can't disable it on Brave, it's built-in

Based on this information, it's quite possible that the problem is with the Brave browser itself and/or how they're integration PDF.js, rather than with the PDF.js library itself.
It might be a good idea to report this bug directly to Brave *first*, to confirm that it's not a problem in the browser itself (since we'll not be able to help if that's the case).

**Comment by timvandermeij** [comment]
It looks like the website is not serving the PDF files correctly. Since we cannot access this resource, I would suggest contacting Moodle support directly.
