### ISSUE TITLE
What i have to do in my pdf.js library to show digital signature pdf in pdfJS

### ISSUE THREAD

**Issue by cgletufo** [mozilla/pdf.js#10222]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
PDF.js does not support digital signatures yet. There are open issues for tracking that: https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature
