### ISSUE TITLE
Why some texts can't be displayed?

### ISSUE THREAD

**Issue by tiantang198635** [mozilla/pdf.js#10221]
this is my code:
       var url = 'assets/pdf/xxxx.pdf'; 
	var loadingTask = pdfjsLib.getDocument(url);
	loadingTask.promise.then(function(pdf) {
	  console.log('PDF loaded');
	  
	  var pageNumber = 1;
	  pdf.getPage(pageNumber).then(function(page) {
		console.log('Page loaded');
		
		var scale = 1.5;
		var viewport = page.getViewport(scale);

		var canvas = document.getElementById('the-canvas');
		var context = canvas.getContext('2d');
		canvas.height = viewport.height;
		canvas.width = viewport.width;

		var renderContext = {
		  canvasContext: context,
		  viewport: viewport
		};
		var renderTask = page.render(renderContext);
		renderTask.then(function () {
		  console.log('Page rendered');
		});
	  });
	}, function (reason) {
	  console.error(reason);
	});
the display result like the picture:http://47.97.98.41:9090/1.png
but Actually the pdf should display like the picture:http://47.97.98.41:9090/2.png

who can help me this is why ?thanks very much!

**Comment by timvandermeij** [comment]
It looks like it's an annotation, so you should configure the annotation layer; refer to https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L55. Without the actual PDF file, we cannot provide more assistance.
