### ISSUE TITLE
Text layer cannot interpret some words properly.

### ISSUE THREAD

**Issue by yogeshtiwari1990** [mozilla/pdf.js#10225]
Attach (recommended) or Link to PDF file here:
[Rocket and spacecraft propulsion.pdf](https://github.com/mozilla/pdf.js/files/2548596/Rocket.and.spacecraft.propulsion.pdf)

Configuration:
- Chrome, firefox, ie latest vesions
- Windows 10 Home
- PDF.js version: 2.0.489
- Is a browser extension: No

Steps to reproduce the problem:
1. Goto Page 24. See last 6th line. And focus on first word 'fire officer'. See screenshot 1
2. Inspect in browser on that word to see textLayer div's. See screenshot 2

What is the expected behavior?
Would expect proper text in text layer as 'fire officer'.

What went wrong? 
Instead of 'fire officer' it cannot interpret the word and shows "®re ocer".

Screenshot 1: 
![image](https://user-images.githubusercontent.com/22951607/48001703-98d74480-e109-11e8-8ef9-08ba712d072e.png)

Screenshot 2: 
![image](https://user-images.githubusercontent.com/22951607/48001752-ccb26a00-e109-11e8-958b-5e18bacf75e0.png)

Can someone point me in right direction to fix it?

**Comment by timvandermeij** [comment]
I think this has something to do with ligatures, since `fi` in `fire` and `ff` in `officer` are often combined into one glyph.

**Comment by yogeshtiwari1990** [comment]
@timvandermeij So rendering was fixed in this [issue](https://github.com/mozilla/pdf.js/issues/1257). But in text layer it still cannot interpret it.

**Comment by Snuffleupagus** [comment]
There isn't any `ToUnicode` data to be found anywhere in this PDF file, and the textLayer is thus based on the `Encoding` data instead (which is not a problem in itself).
However, the issue is that the `Encoding` data in this PDF file is completely busted[1], and most PDF viewers will not be able to copy anything but total gibberish. For example, neither Adobe Reader (i.e. the reference implementation) or PDFium (in the Chrome browser) can copy *any* of the text successfully in this file.

This is a bug in the PDF file *itself*, and please note that the PDF.js library is already doing a *much* better job here than most other PDF viewers (since the text is mostly copyable).
Unfortunately, with no `ToUnicode` data available and only incorrect `Encoding` data, there's simply nothing that can be done here (for ligatures) and this issue is thus invalid.

---
[1] All `Differences` arrays have entries of the format `Cdd{d}`, where `d = 1, 2, ..., 9`.

**Comment by yogeshtiwari1990** [comment]
@Snuffleupagus I totally with the fact that "PDF.js library is already doing a much better job here than most other PDF viewers". 
Thank you so much for the quick answer, now i can further investigate why the PDF file doesn't have required info.

**Comment by Jun711** [comment]
Hi @Snuffleupagus,
I wonder how you checked if a pdf file contains ToUnicode. I want to check if my pdf file is caused by this same issue. thank you.

The word that's not rendered using pdf.js is a ligature (ﬁrst), with pdf.js, ﬁ is removed from the word first. and it is rendered as `rst`.

Thus, I used gpdf to see what it uncompressed into but not sure how to interpret the output from qpdf. 
`qpdf --stream-data=uncompress input.pdf output.text` is the command I used.

ﬁrst(ligature) becomes (\034rst) in qpdf output below.

```
BT
/F49 20.6625 Tf 72 605.362 Td [(Chapter)-354(1)]TJ/F50 24.7871 Tf 0 -49.813 Td [(Course)-349(Materials:)-465(Syllabus,)-349(Rubrics,)]TJ 0 -29.888 Td [(Jeopardies)]TJ/F52 14.3462 Tf 0 -57.783 Td [(1.1)-281(Deriv)31(ed)-280(cop)30(y)-280(of)-281(Rubrics)-280(for)-281(Exams)-280(and)-281(Group)-280(Pro)-61(jects)-281(in)-280(Ethics)]TJ/F68 5.9776 Tf 463.85 6.359 Td [(1)]TJ/F77 11.9552 Tf -463.85 -30.17 Td [(1.1.1)-375(Key)-375(to)-375(Links)]TJ/F14 9.9626 Tf 11.624 -18.388 Td [(\017)]TJ/F15 9.9626 Tf 13.283 0 Td [(The)-335(\034rst)-335(link)-335(connects)-335(to)-334(the)-335(Ethics)-335(Bo)28(wl)-335(assignmen)28(t)-335(for)-335(engineering)-335(and)-335(business)-335(studen)28(ts.)-449(It)-335(corre-)]TJ 0 -11.955 Td [(sp)-28(onds)-333(with)-333(the)-334(Ethics)-333(Bo)28(wl)-333(rubric)-333(displa)27(y)28(ed)-333(b)-28(elo)28(w.)]TJ/F14 9.9626 Tf -13.283 -11.955 Td [(\017)]TJ/F15 9.9626 Tf 13.283 0 Td [(The)-354(second)-355(link)-354(connects)-354(to)-355(the)-354(mo)-28(dule)-354(on)-355(dev)28(eloping)-354(rep)-28(orts)-354(on)-355(computing)-354(so)-28(cio-tec)28(hnical)-354(systems.)]TJ 0 -11.955 Td [(It)-272(outlines)-272(an)-272(assignmen)27(t)-272(where)-272(computing)-272(studen)28(ts)-272(carry)-273(out)-272(an)-272(analysis)-272(of)-272(the)-273(i)1(mpact)-273(of)-272(a)-272(computing)]TJ 0 -11.956 Td [(system)-362(on)-363(a)-362(giv)28(en)-362(so)-28(cio-tec)28(hnical)-362(system.)-532(A)-362(rubric)-362(to)-362(this)-363(activit)28(y)-362(used)-362(in)-363(computer)-362(ethics)-362(classes)-362(is)]TJ 0 -11.955 Td [(pro)28(vided)-333(b)-28(elo)28(w.)]TJ/F14 9.9626 Tf -13.283 -11.955 Td [(\017)]TJ/F15 9.9626 Tf 13.283 0 Td [(The)-297(third)-298(link)-297(t)-1(o)-297(the)-297(T)-1(hre)1(e)-298(F)83(ramew)28(orks)-297(mo)-28(dule)-298(corresp)-27(onds)-298(to)-297(a)-298(rubric)-297(b)-28(elo)28(w)-298(that)-297(examines)-298(ho)28(w)-298(w)28(ell)]TJ 0 -11.955 Td [(studen)28(ts)-334(depl)1(o)27(y)-333(the)-333(framew)28(ork)-1(s)-333(on)-333(decision-making)-333(and)-333(problem-solving)-333(outlined)-334(b)28(y)-333(this)-333(mo)-28(dule.)]TJ/F14 9.9626 Tf -13.283 -11.955 Td [(\017)]TJ/F15 9.9626 Tf 13.283 0 Td [(The)-353(\034nal)-352(link)-353(to)-353(Computing)-352(Cases)-353(pro)28(vides)-353(the)-353(reader)-352(with)-353(access)-353(to)-352(Ch)27(uc)28(k)-353(Hu\033)-77('s)-353(helpful)-353(advice)-352(on)]TJ 0 -11.955 Td [(ho)28(w)-333(to)-334(write)-333(and)-333(use)-333(rub)-1(ri)1(cs)-334(in)-333(the)-333(con)28(text)-334(of)-333(teac)28(hing)-333(computer)-333(ethics.)]TJ/F77 11.9552 Tf -24.907 -37.848 Td [(1.1.2)-375(In)31(tro)-31(duction)]TJ/F15 9.9626 Tf 0 -18.388 Td [(This)-305(mo)-28(dule)-305(pro)27(vides)-305(a)-305(range)-306(of)-305(assessmen)28(t)-306(and)-305(study)-306(m)1(aterials)-306(used)-305(in)-305(classes)-306(in)-305(business,)-311(engineering)-305(and)]TJ 0 -11.955 Td [(computer)-322(ethics.)-440(R)-1(ubric)1(s)-323(will)-322(hel)1(p)-323(y)28(ou)-322(understand)-322(the)-322(standards)-322(that)-323(wi)1(ll)-322(b)-28(e)-322(used)-322(to)-322(ass)-1(e)1(s)-1(s)-322(y)28(our)-322(writing)-322(in)]TJ 0 -11.955 Td [(essa)28(y)-361(exams)-360(and)-360(group)-361(pro)-55(jects.)-526(They)-360(also)-360(help)-361(y)28(our)-360(instructor)-361(sta)28(y)-360(fo)-28(cused)-360(on)-361(the)-360(same)-360(set)-361(of)-360(standards)]TJ 0 -11.955 Td [(when)-355(assessing)-354(the)-355(w)28(ork)-354(of)-355(the)-355(c)1(lass.)-509(Jeopardy)-354(exercises)-355(will)-354(help)-355(fo)-27(cus)-355(y)28(our)-355(study)-354(e\033orts)-355(and)-354(help)-355(y)28(ou)-355(to)]TJ 0 -11.956 Td [(iden)28(tify)-387(y)28(our)-386(strengths)-387(and)-386(w)28(eaknesses)-387(as)-386(y)28(ou)-387(prepare)-386(for)-386(class)-387(exams.)-603(A)-387(cop)28(y)-386(of)-387(the)-386(course)-386(syllabus)-387(has)]TJ 0 -11.955 Td [(b)-28(een)-376(included)-376(in)-376(case)-377(y)28(ou)-376(lose)-376(the)-377(cop)28(y)-376(giv)28(en)-377(to)-376(y)28(ou)-376(in)-377(the)-376(\034rst)-376(class.)-574(As)-376(the)-376(semester)-377(progresses,)-387(exp)-27(ect)]TJ 0 -11.955 Td [(this)-340(mo)-28(dule)-340(to)-340(c)28(hange)-340(and)-340(ev)28(en)27(tually)-340(ful\034ll)-340(the)-340(function)-340(of)-340(serving)-340(as)-340(a)-340(p)-28(ortal)-340(to)-340(other)-340(mo)-28(dules)-340(and)-340(online)]TJ 0 -11.955 Td [(materials)-333(relev)56(an)27(t)-333(to)-333(this)-334(and)-333(other)-333(classes.)]TJ/F77 11.9552 Tf 0 -27.885 Td [(1.1.3)-375(Revised)-375(Sc)31(h)1(e)-1(d)1(ule)-375(for)-375(F)93(all)-374(2011)]TJ/F37 9.9626 Tf 0 -18.388 Td [(Revised)-383(Sc)32(hedule)-383(for)-383(F)95(all)-383(2011)]TJ/F78 9.9626 Tf 0 -11.955 Td [([Media)-378(Object])]TJ/F79 6.9738 Tf 76.616 3.615 Td [(2)]TJ
ET
```
