### ISSUE TITLE
CSP violations for unsafe-inline in pdfjst-dist@2.0.943

### ISSUE THREAD

**Issue by tomtomau** [mozilla/pdf.js#10229]
Configuration:
- Chrome
- Mac OSX
- PDF.js version: pdfjs-dist `2.0.943`
- Is a browser extension: false

We have a content security policy that prevents `unsafe-inline`.

Unfortunately, after upgrading to 2.0.943, [pdfjs-dist/build/pdf.js now has a `Function("return this")` call](https://github.com/mozilla/pdfjs-dist/blob/v2.0.943/build/pdf.js#L13154) (which violates CSP.

My understanding was this was introduced when support for [async/await and generators was added to the gulpfile.js](https://github.com/mozilla/pdf.js/commit/099ed0885239f070f7c7e1d703b57cc64c3f634d#diff-b9e12334e9eafd8341a6107dd98510c9R185).

Upon searching for the babel plugin and finding the GitHub issues, I find [only two issues](https://github.com/babel/babel/issues?utf8=%E2%9C%93&q=content+security+policy) which don't really seem to be covering the issue.

I'm unsure of how to build my own version of pdfjs-dist to try and isolate to see if this is definitively the issue, so just posting this to see if I can get some help/pointers!

**Comment by Snuffleupagus** [comment]
> I'm unsure of how to build my own version of pdfjs-dist to try and isolate to see if this is definitively the issue,

For debugging purposes it will be a lot quicker to just run `gulp generic`, rather than building the entire `pdfjs-dist` repo, and then check the `pdf.js`/`pdf.worker.js` files that are created in the `build/generic/build/` directory.

Just make sure that you follow the steps outlined in https://github.com/mozilla/pdf.js#getting-the-code *first*, such that the repo is correctly setup locally and the various `gulp` commands will work.

**Comment by timvandermeij** [comment]
This is a part of generated code, so I don't think there is anything we can do about this. I would suggest to file this issue at the Babel repository instead. Thanks.

**Comment by sashapwc** [comment]
@tomtomau Have run into the same exact problem with the CSP violation on Function("return this") after upgrading and deploying to my server. Wondering what you did to try to fix this? Have you created any babel issue? And how did you track this down to the async/await code? Thankd

**Comment by timvandermeij** [comment]
Thank you for looking into this. We regularly update our dependencies, so once Babel fixes this we will upgrade too.

**Comment by tomtomau** [comment]
`@babel/runtime` requires regenerator-runtime 0.12.0, which can resolve to 0.12.1 fine, however, that is only the case for babel 7.x

pdf.js is on Babel 6.26 which pins [regenerator-runtime to 0.11](https://github.com/babel/babel/blob/v6.26.0/packages/babel-runtime/package.json)

From my understanding - if pdf.js is upgraded to Babel 7.x this problem should be resolved.

**Comment by sashapwc** [comment]
@tomtomau I think you are right. I got stuck in dependency hell and didn't realize that yeah, the new babel should work. As a workaround, if you happen to be using the pre-built pdfjs viewer, you can find references to Function("this") and replace it with the code mentioned in https://github.com/facebook/regenerator/issues/336
There are three files: build/pdf.worker.js , web/viewer.js, build/pdf.js

**Comment by tomtomau** [comment]
Yeah thanks, we've just pinned to the older version of pdf.js for no

**Comment by sashapwc** [comment]
@tomtomau Looking at Babel's yarn.lock, they still aren't using regenerator-runtime 0.12.1, so I've written an issue there as well since they will need to explicitly yarn update to 0.12.1 or 0.13

Babel issue: https://github.com/babel/babel/issues/9043

**Comment by timvandermeij** [comment]
Reopening to track the Babel upgrade on our side.

**Comment by timvandermeij** [comment]
The upgrade to Babel 7 is completed in #10293. Closing since there is nothing more we can do on our side now.
