### ISSUE TITLE
Trigger page rendered event

### ISSUE THREAD

**Issue by sovietmah** [mozilla/pdf.js#10230]
Does anyone know how to trigger page rendered event?
I want when certain page loaded and rendered succesful, and it will trigger an event for me to do extra steps.

**Comment by timvandermeij** [comment]
You can listen for the `pagerendered` event and attach a handler; refer to https://github.com/mozilla/pdf.js/blob/f6bc93402ef35675ce61a278e3abe6b93d7fd393/web/app.js#L1287.
