### ISSUE TITLE
Forms - retrieving form value

### ISSUE THREAD

**Issue by BlackWhiteValley** [mozilla/pdf.js#10235]
Hello

Is there a way how to retrieve values from Rendered forms using javascript ( just extract values to javascript, keep the pdf itself as it is)

I can see the forms once I set the renderInteractiveForms to true,
but I cannot grab their values 

in pdfjs samples for 1.6 I saw this

 var tempData = PDFJS.FormFunctionality.getFormValues();
            for (var prop in tempData) {
                data[prop]= tempData[prop];
            }

in forms sample - which is exactly what I'm looking for

but in the build from GIT, the PDFJS.FormFunctionality is null

am I doing something wrong?

Thanks

**Comment by timvandermeij** [comment]
There is no API for this yet, but it's tracked in #7613.

**Comment by BlackWhiteValley** [comment]
Ok thanks
if there any chance to say when it will be done? Let's say "not in next year" or "likelly in next year"

as well can you help me to understand why this was in version 1.6 and is not now inside?

Thanks

**Comment by timvandermeij** [comment]
Previously we only had an example, but it was very incomplete and unstructured. Now we have a structured annotation layer and we support much more annotation types. For this we had to change practically everything in terms of API, so that old example code was removed since it became dysfunctional.
