### ISSUE TITLE
PDF Object error to receive a datauristring on Browser Edge

### ISSUE THREAD

**Issue by thiagoabarros** [mozilla/pdf.js#10239]
Hi Dear,

I'm using a PDFObject with a jsPDF and jsPDF Autotable. After I build a pdf content using the jsPDF and jsPDF Autotable, I send to PDFObject the doc.output('datauristring'), this command works fine in Browser Chrome, but on Edge doesn't work, and I don't get any error from browser console.

My code is:
`<div id="my-container"></div>`
`<script src="jquery-3.2.1.min.js"></script>`
`<script src="bootstrap.min.js"></script>`
`<script src="jspdf.min.js"></script>`
`<script src="jspdf.plugin.autotable.min.js"></script>`
`<script src="pdfobject.min.js"></script>`
`$(document).ready(function(){ `

		var doc = new jsPDF({
			orientation: 'portrait',
			unit: 'mm',
			format: 'A4'
		});
		doc.text("Hello Word!", 20, 20);
		var string = doc.output('datauristring');
		PDFObject.embed(string, "#my-container");
	});`

Anybody have some idea what can be wrong?

Thank you!

Best Regards,

Thiago Barros

**Comment by Snuffleupagus** [comment]
This isn't the correct project, you probably want https://github.com/MrRio/jsPDF/ instead.
