### ISSUE TITLE
Zoomout event is not working as expected

### ISSUE THREAD

**Issue by sovietmah** [mozilla/pdf.js#10243]
I added the code below,

document.addEventListener('zoomout', function(e) {
                console.log("zoomout" + e);
          });

in order to listen to zoomout event, but when I click on zoom in or zoom out, it never execute the console.log, anyone know how to intercept the zoomout event?

**Comment by timvandermeij** [comment]
It's emitted on the event bus:

https://github.com/mozilla/pdf.js/blob/f6bc93402ef35675ce61a278e3abe6b93d7fd393/web/app.js#L1306

Therefore, you either have to listen for it on the event bus or configure the event bus to dispatch events to the DOM:

https://github.com/mozilla/pdf.js/blob/f6bc93402ef35675ce61a278e3abe6b93d7fd393/web/pdf_viewer.component.js#L39
