### ISSUE TITLE
Trying to implement multi phrase search

### ISSUE THREAD

**Issue by dgoiko** [mozilla/pdf.js#10242]
I'm trying to implement a combined word and phrase function like the one referenced in #7442 , however I'm having some trouble.

I added this to PDFLinkService (pdf.js version 2.0.943):

```
if ('busq' in params) {
    var busqJSON = params['busq'];
    var complexSearch = JSON.parse(busqJSON);
    var simpleTerms = [];
    if(Array.isArray(complexSearch)){
     	var i;
       	for(i=0; i<complexSearch.length;i++){
            var term = complexSearch[i].trim();
            if(term.includes(" ")){
        	this.eventBus.dispatch('findfromurlhashdail', {
        	    source: this,
        	    query: term,
        	    phraseSearch: true
        	});
            }else{
        	simpleTerms.push(term);
            }
        }
        if(simpleTerms.length > 0){
	    this.eventBus.dispatch('findfromurlhashdail', {
	        source: this,
	        query: simpleTerms.join(' '),
	        phraseSearch: false
	     });
        }
    }
}
```
findfromurlhashdail is basically the same than findfromurlhash but with exact word match enabled by default. You could change it with findfromurlhash and it will work.
If you provide a query string like this:
`#busq=['phrase one', 'phrase two', 'word1', 'word2']`
it searches and highlights "phrase one" using phraseSearch mode, then searches for "phrase one", and then for "word1 word2" in single word mode. 
Everything works as expected, except that every search cleans the highlights from the previous one (I've checked it with debugger).

Am I doing this the right way?

**Comment by timvandermeij** [comment]
If you do a new search, then `_updateMatches` is called at https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L288 which clears all existing matches at https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L298. If you need this behavior to be different, you should change it there.

**Comment by dgoiko** [comment]
I thought it was working, but it was a browser glitch, it still doesnt work :S

**Comment by damianfabian** [comment]
Where you able to solve this @dgoiko?

**Comment by dgoiko** [comment]
@damianfabian not really, it was buggy so I did not polst it, although this is on my schedule list for a future project, so I'll post updates when I get into this again.

**Comment by dgoiko** [comment]
{
	    key: '_calculateArrayMatch',
	    value: function _calculateWordMatch(queryArray, pageIndex, pageContent, entireWord) {
	      var matchesWithLength = [];
	      for (var i = 0, len = queryArray.length; i < len; i++) {
	        var subquery = queryArray[i];
	        var subqueryLen = subquery.length;
	        var matchIdx = -subqueryLen;
	        while (true) {
	          matchIdx = pageContent.indexOf(subquery, matchIdx + subqueryLen);
	          if (matchIdx === -1) {
	            break;
	          }
	          if (entireWord && !this._isEntireWord(pageContent, matchIdx, subqueryLen)) {
	            continue;
	          }
	          matchesWithLength.push({
	            match: matchIdx,
	            matchLength: subqueryLen,
	            skipped: false
	          });
	        }
	      }
	      if (!this._pageMatchesLength) {
	        this._pageMatchesLength = [];
	      }
	      this._pageMatchesLength[pageIndex] = [];
	      this._pageMatches[pageIndex] = [];
	      this._prepareMatches(matchesWithLength, this._pageMatches[pageIndex], this._pageMatchesLength[pageIndex]);
	    }
	  }

@damianfabian this allows the searcher to use an array as query instead of a string. Each element of the array is threated like an exact match (although you could further improve that)

**Comment by michael-leese** [comment]
How have you got on with this project?
We are trying to do something similar and attempting to find where we can put the _calculateArrayMatch() but we arent having much luck, using the repo to try and find where this is located and found it in pdf_find_controller.js and not in the text_layer_builder.js as suggested above. 
Any thoughts or ideas welcome please :-)

**Comment by aDingil** [comment]
you can just pass in an array into the find event
```js
  await eventBuses[viewerID].dispatch("find", {
    caseSensitive: false,
    highlightAll: true,
    phraseSearch: true,
    query: termsToHighlight,
  });
```

**Comment by timvandermeij** [comment]
Please refer to https://github.com/mozilla/pdf.js/issues/18206#issuecomment-2159220004, and note that we always welcome patches to improve documentation, examples, etc.
