### ISSUE TITLE
Deflate in PDF: incorrect data

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#10248]
Hi, I am making my own PDF parser and I have a problem with a following PDF file.

There is a stream starting at line 612, that has a /FlateDecode filter, and is 218 bytes long. It starts with bytes 223, 184. My INFLATEr says, that the header is invalid. However, PDF.js still reads that PDF file.

Could anybody tell me, how should I treat such stream?
[c4611_sample_explain.pdf](https://github.com/mozilla/pdf.js/files/2572869/c4611_sample_explain.pdf)

**Comment by Snuffleupagus** [comment]
The PDF.js code for parsing `FlateDecode` filters can be found in the `src/core/stream.js` file, see: https://github.com/mozilla/pdf.js/blob/960213cb6963f9bf46d6224805de2dc73fef0af4/src/core/stream.js#L310-L675

> Could anybody tell me, how should I treat such stream?
> [c4611_sample_explain.pdf](https://github.com/mozilla/pdf.js/files/2572869/c4611_sample_explain.pdf)

Browsing through the contents of that file with http://brendandahl.github.io/pdf.js.utils/browser/ shows that it's encrypted, hence you'll need to decrypt the stream *before* decoding its data. See https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js for the PDF.js code used for decryption of encrypted PDF files.

> I am making my own PDF parser and I have a problem with a following PDF file.

Please keep in mind that this is, first and foremost, a bug tracker for the PDF.js project itself, hence issues like this one is (by definition) out-of-scope.

**Comment by photopea** [comment]
@Snuffleupagus  Thanks for your answer. I do realise, that it is not a bug in pdf.js, but you are the only people I know who could help me.

I wonder why people use encryption in these PDFs, while no password is required. Your crypto.js is 1600 lines of code, while my whole PDF parser (without DEFLATE decompression and PS interpreter) is 827 lines of code. So I think I will not add the support for encryption into my library at this point.
