### ISSUE TITLE
PDFSidebarResizer: The browser does not support resizing of the sidebar. 

### ISSUE THREAD

**Issue by jav910** [mozilla/pdf.js#10252]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  IE11 browser version 11.1387.15063.0
- Operating system and its version: windows 10
- PDF.js version: v2.1.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Open it in IE it will display "PDF.js v2.1.0 (build: ?)
Message: Map is not defined" and in console it will have message as "PDFSidebarResizer: The browser does not support resizing of the sidebar." However, same is working on Chrome, firefox, ipad.

What is the expected behavior? (add screenshot)
![pdfjs](https://user-images.githubusercontent.com/8149157/48409536-15999c80-e762-11e8-9fd9-e4b48c1d7562.JPG)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Sidebar resizing is *purposely* not supported in browsers, such as IE11, that do not implement CSS variables; hence this issue is invalid.

**Comment by jav910** [comment]
Can I use pdf.js for IE11, without Sidebar resizing functionality ?

**Comment by timvandermeij** [comment]
Yes, IE11 should be mostly supported according to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsers-are-supported. Only sidebar resizing will not work.

**Comment by timvandermeij** [comment]
I don't think PDF.js 2.0 or higher will work well in IE10, but you can try. If IE10 support is really necessary, you can fall back to using PDF.js 1.10.100 (https://github.com/mozilla/pdf.js/releases/tag/v1.10.100), the final version 1 release. However, we don't recommend that and recommend to always use the latest version.
