### ISSUE TITLE
Translating mouse click coordinates to pdf

### ISSUE THREAD

**Issue by vivektiwary** [mozilla/pdf.js#10259]
Configuration:
- Web browser and its version: Chrome
- Operating system and its version: OSX High Sierra
- PDF.js version: latest
- Is a browser extension: no

I am trying to build annotation layer on top of `pdf.js`. I am trying to render the pdf using `canvas` as well as using `SVG`. One problem I am currently facing is with translating the mouse click coordinates to the pdf coordinates.

I could not get any search results about a formula for the conversion.
Do pdf.js have some conversion formula which takes into account the actual visible screen and then tries to figure out the coordinates on the pdf?

**Comment by tincann** [comment]
@vivektiwary Did you figure this out?

**Comment by babajonni** [comment]
Did you find a solution to this?

**Comment by timvandermeij** [comment]
The annotation layer is available in the source code, see https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js. The idea is that is overlays HTML elements over the canvas/SVG rendering in containers. The container creation can be found in https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L157-L177. This uses the annotation's rectangle to draw it, so you can find those coordinates.

There is no conversion from mouse click coordinates to PDF coordinates. You'll have to implement that yourself, most likely using the size of the canvas and the size of the PDF page (the bounding box).

**Comment by babajonni** [comment]
@timvandermeij  Thank you

**Comment by babajonni** [comment]
Do you have a suggested way to put a click event handler on the canvas?
