### ISSUE TITLE
pdf-dist doesnot load all pdf files in edge browser

### ISSUE THREAD

**Issue by krupa-shah** [mozilla/pdf.js#10254]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393
- Operating system and its version: windows 10 enterprise, version 1607
- PDF.js version:2.0.489
- Is a browser extension:

Steps to reproduce the problem:
1. Integrated pdf-dist and tried to open pdf file located in aws s3 bucket
2. 

What is the expected behavior? (add screenshot) All the pdf file should be loaded

What went wrong? (add screenshot) few pdf files donot get loaded in edge browser. It works completely fine with chrome and firefox. Even on edge browser, few pdf file gets displayed but few pdf file has issue.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It's most likely a combination of Edge not understanding all requests and AWS not serving the files correctly, however without access to the actual resource there is no way we can help with this. You can check the response when fetching the PDF file in the network tab to see what the issue may be.
