### ISSUE TITLE
I can't able to search the using the text

### ISSUE THREAD

**Issue by PrasannaBrabourame** [mozilla/pdf.js#10267]
Configuration:
- Web browser and its version: Chrome Version 70.0.3538.102
- Operating system and its version: Windows 10
- PDF.js version: latest build
- Is a browser extension: No

Steps to reproduce the problem:
1.  When i am uploading some pdf using browse option after pdf rendered all words are splitted seperately
2. It is very difficult for search using space

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/23032282/48686268-178bb180-ebe1-11e8-8714-7f9a1f76efb2.png)

What went wrong? (add screenshot)
I can able to search using and keyword it is showing properly no issue in it
![image](https://user-images.githubusercontent.com/23032282/48686297-3b4ef780-ebe1-11e8-9b5f-0b28b235cf7c.png)
but when i am trying to find using "and r" is showing word not found
![image](https://user-images.githubusercontent.com/23032282/48686333-6d605980-ebe1-11e8-9286-0639d9598c52.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since no PDF file is provided and we already have many open issues like this one.
