### ISSUE TITLE
'Map is not defined'

### ISSUE THREAD

**Issue by anggikolo11** [mozilla/pdf.js#10268]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Opera Mini for Android (V 27.0.2254.118423)
- Operating system and its version:
Android 5.0.1
- PDF.js version:
Latest build
- Is a browser extension:
No

Steps to reproduce the problem:
1. When I tried to open mozilla.github.io/pdf.js/web/viewer.html it can't show pdf. There was a notification 'An error occured while loading the PDF.'
2. I tried to click 'More information' button and said 'PDF.js v2.1.70 (build: 6ebdbb24) Message: Map is not defined)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![screenshot_2018-11-19-17-07-24](https://user-images.githubusercontent.com/45036819/48700609-ffd31e00-ec1e-11e8-99ac-b5183008e734.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Opera Mini for Android (V 27.0.2254.118423)

Looking at https://en.wikipedia.org/wiki/Opera_Mini, that version doesn't look very up-to-date. 

> It looks like we need a `core-js` polyfill for Opera Mini then :(

Looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility, basically every remotely modern browser[1] has at least *basic* support for `Map`.

Hence it seems, at least to me, that the most appropriate resolution is to WONTFIX this issue.

---
[1] That even includes IE11.

**Comment by timvandermeij** [comment]
Oh, the current version is 37 according to Wikipedia, not 27; I misread that. Indeed, then we can close this as won't-fix.
