### ISSUE TITLE
I can't able to search the using the text

### ISSUE THREAD

**Issue by PrasannaBrabourame** [mozilla/pdf.js#10271]
Attach (recommended) or Link to PDF file here:
https://1drv.ms/b/s!Aie9TU14Pq0ehTC0I7adIZ6rrMJR

Configuration:

- Web browser and its version: Chrome Version 70.0.3538.102
- Operating system and its version: Windows 10
- PDF.js version: latest build
- Is a browser extension: No

Steps to reproduce the problem:

1. When i am uploading some pdf using browse option after pdf rendered all words are splitted seperately
2. It is very difficult for search using space

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/23032282/48747179-69434300-ec98-11e8-96c1-f13bb473c212.png)

What went wrong? (add screenshot)
I can able to search using "and" keyword it is showing properly no issue in it
![image](https://user-images.githubusercontent.com/23032282/48747187-73654180-ec98-11e8-9783-7be3b128ab15.png)

but when i am trying to find using "and r" is showing word not found
![image](https://user-images.githubusercontent.com/23032282/48747218-92fc6a00-ec98-11e8-8f70-c4a00aa0a5f9.png)

**Comment by timvandermeij** [comment]
Closing since we have more open issues about this problem, for example #9736 and others with the `4-text-selection` label, so this is a duplicate.
