### ISSUE TITLE
Can I stream download cross-domain pdf files?

### ISSUE THREAD

**Issue by gd-ldj** [mozilla/pdf.js#10287]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It should be possible; refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr.

**Comment by gd-ldj** [comment]
However, it can't be Streaming download, it only sends one request
