### ISSUE TITLE
Reloadeing/ re-rendering due to zoom stops JS events

### ISSUE THREAD

**Issue by liebig** [mozilla/pdf.js#10297]
Link to PDF file: any PDF file

Configuration:
- Web browser and its version: Cordova
- Operating system and its version: iOS 11.4.1
- PDF.js version: v2.0.943

Steps to reproduce the problem:
Add or run this JavaScript code. PDFJS viewer.html is rendered in an iframe and ExtJS is used.
```JavaScript
var viewer = Ext.dom.Query.select('iframe')[0].contentWindow.document.getElementById("viewer");
var pdfViewer = me.el.dom.contentWindow.PDFViewerApplication.pdfViewer;
         
viewer.addEventListener('gesturechange', function(e) {

    if (e.scale < 1.0) {
        console.log("PinchOut")
        pdfViewer.currentScale = pdfViewer.currentScale - 0.01;
    } else if (e.scale > 1.0) {
        console.log("PinchIn");
        pdfViewer.currentScale = pdfViewer.currentScale + 0.01;
    }
})
```

What is the expected behavior?
When I execute the Pinch Zoom gesture (Wipe 2 fingers apart or to each other on the display), the document should be permanently zoomed in or out.

What went wrong?
If the document is reloaded/ re-rendered from a zoom size of approx < 120%, the 'gesturechange' event is no longer fired. The fingers must first be removed from the display and the pinch zoom gesture must be executed again with 2 fingers to get the event fired again. I also tried the library Hammer.JS, but unfortunately here is exactly the same behavior. If the document is further enlarged at a zoom of approx. > 120%, no re-rendering takes place and the 'gesturechange' event is further fired and everything works. Now the question would be whether you can deactivate re-rendering if necessary and only execute it again at the end of the pinch zoom?

**Comment by timvandermeij** [comment]
Pinch to zoom is not supported by the default viewer at the moment, but this is already tracked in #2582.

**Comment by liebig** [comment]
Yes I know that Pinch Zoom is not yet supported. But my question is how to disable the rerender or manage to fire the events anyway.

**Comment by robert-esht** [comment]
Try to set the PDFJS.disableTextLayer in viewer.js to "false"

`"disableTextLayer": false, ` 

then it should work.
