### ISSUE TITLE
rtl reverse search

### ISSUE THREAD

**Issue by roeycohen** [mozilla/pdf.js#10301]
PDF file:
[rtl_bad_search.pdf](https://github.com/mozilla/pdf.js/files/2612899/rtl_bad_search.pdf)

Configuration:
- Web browser and its version: Firefox 63 (directly) and pdf.js v2.0.943 (all browsers)
- Operating system and its version: windows 10
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. open the attached pdf in a new firefox tab.
2. search for "אבג"

What is the expected behavior? (add screenshot)
the search tool will found the text "אבג"

What went wrong? (add screenshot)
the search tool didn't find "אבג". BUT if i search for "גבא" then it will.

**it worth mentioning that i've created this sample using MS Excel 2016 (save as pdf).**

**Comment by MattBDev** [comment]
I noticed that `_pageContents` in pdf_find_controller.js loads the text into the array as the following string: "גבאוהדabcdef" . That explains why "אבג" doesn't return any results and "גבא" does.

**Comment by roeycohen** [comment]
hi, guys, anything new about this issue?

**Comment by timvandermeij** [comment]
It looks like this (incorrectly?) triggers bidi so it's reversed.

**Comment by Fahad-Alsaidi** [comment]
chrome works fine.

**Comment by oxcl** [comment]
this still doesn't work i don't know why it's closed
