### ISSUE TITLE
"This PDF document might not be displayed correctly": cause window.onresize event fired

### ISSUE THREAD

**Issue by WalterYongtaoWang** [mozilla/pdf.js#10311]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. add event listener for winodw.onresize
2. This listener will be fired if you display a PDF in a iframe of this we page

What is the expected behavior? (add screenshot)

It should not affect the web page layout.

What went wrong? (add screenshot)
window.innerHeight became smaller and window.onresize event fired.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Could you also provide a minimal runnable example on JSFiddle, JSBin or another server that shows the issue?

**Comment by WalterYongtaoWang** [comment]
Please check this example and browser console log:
http://remotespark.com/download/pdfjs.html

I'm not sure this is caused by the message bar ("The PDF document might not be displayed correctly") or the printing dialog.

There are 3 onresize events fired in the console log.

**Comment by Snuffleupagus** [comment]
> I'm not sure this is caused by the message bar ("The PDF document might not be displayed correctly")

The notification bar would explain why a `resize` event is fired. Please note that the notification bar itself is a *browser* feature (in Firefox), and as such this issue is invalid from the PDF.js project point of view.

**Comment by WalterYongtaoWang** [comment]
Thanks. I'll submit a bug to Firefox then.
