### ISSUE TITLE
Load all pages at once with PDFViewer

### ISSUE THREAD

**Issue by KapilJethava** [mozilla/pdf.js#10314]
How can I load all the pdf pages at once with PDFViewer, in viewer.js I found method for forceRendering method however it is not working in my case? Do we have any work around to this?

**Comment by timvandermeij** [comment]
You can do it like the SVG viewer at https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer/viewer.js#L62 which renders all pages.
