### ISSUE TITLE
pdf.js demo not working in chrome browser

### ISSUE THREAD

**Issue by PemaRekdenDorjee** [mozilla/pdf.js#10328]
Attach (recommended) or Link to PDF file here:https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version:
![image](https://user-images.githubusercontent.com/26476471/49438341-43fe1b00-f7e8-11e8-93f1-7acf918fb77f.png)

- Operating system and its version:
![image](https://user-images.githubusercontent.com/26476471/49438623-1c5b8280-f7e9-11e8-8f04-9fd9750d71fe.png)

- PDF.js version: pdf demo (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: I have added the PDF viewer  extension and result is same 
![image](https://user-images.githubusercontent.com/26476471/49438955-faaecb00-f7e9-11e8-811e-c89de07f19d2.png)

Steps to reproduce the problem:
1. open this link ( https://mozilla.github.io/pdf.js/) in chrome
2.click on demo 

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/26476471/49439081-4feadc80-f7ea-11e8-8865-6276cbc45c5a.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/26476471/49438499-b40ca100-f7e8-11e8-8ac6-d8ef0d4e04e3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by PemaRekdenDorjee** [comment]
Still not working on my side (Chrome) and there is only PDF viewer  extension installed.
![pdfnotworking](https://user-images.githubusercontent.com/26476471/50325020-90e23100-050c-11e9-86d9-9cabb6085971.PNG)


It is asking me to download the file

![pdfdownload](https://user-images.githubusercontent.com/26476471/50325081-ed455080-050c-11e9-9498-0c5a8535f9b0.PNG)

**Comment by timvandermeij** [comment]
The download manager (from the screenshot) may be interfering here; I recall having seen issues before where the download manager was the culprit. Please check if that is the case by disabling it temporarily.

**Comment by Snuffleupagus** [comment]
Given that no response to https://github.com/mozilla/pdf.js/issues/10328#issuecomment-449516278 has been given, nor any other information provided, this issue can probably be closed as incomplete for now.

**Comment by carylewis** [comment]
I can confirm that the demo at https://mozilla.github.io/pdf.js/web/viewer.html does not work in chrome.

Google Chrome is up to date
Version 73.0.3683.39 (Official Build) beta (64-bit)

I am not sure exactly when this stopped working, but it did work back in late 2018.

**Comment by timvandermeij** [comment]
Try doing a force refresh (Ctrl + F5 in Chrome I think). I had this once and it turned out that some older assets were cached.

**Comment by vahabahmadvand** [comment]
I have this problem in chrome version 79
I've solved this issue by remove PDF file type from File types in Internet download manager
