### ISSUE TITLE
How to embed pdf.js into another module intended for use in webpack projects?

### ISSUE THREAD

**Issue by marcaaron** [mozilla/pdf.js#10324]
I created a simple module for converting PDFs to image data URLs within React apps here:

https://github.com/marcaaron/react-pdf-to-image

If I import this into a webpack project e.g. `create-react-app` and then build / serve this project all goes well. But in development mode I receive the following error message in JS console.

`bootstrap:1 Uncaught ReferenceError: window is not defined`

And webpack dev server complains about this:

`./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

Steps to reproduce the problem:
1. Install package as dependency
2. Attempt to use in a `create-react-app` project

What is the expected behavior?
There would be some sort of way to add pdf.js with a worker as a dependency for other projects in development out of the box. Is this a limitation of web workers in general? Or can changes be made to the current distribution to allow this to work in all projects?

**Comment by pk-nb** [comment]
I believe this is not an issue with nesting in the package, but instead with the `requireEnsure` config [being turned off in `create-react-app`](https://github.com/facebook/create-react-app/blob/49e258b4a6d04fb7e3542d7a060c6dcad4093564/packages/react-scripts/config/webpack.config.js#L302).  

See https://github.com/mozilla/pdf.js/issues/10253. Unfortunately the only way to adjust this config currently is to eject from CRA. We have our own config where we turned this off. I wonder if PDFjs could support dynamic imports instead going forward as they are now a standard. It's a tricky export with the workers currently.

**Comment by davidawad** [comment]
So is it correct to say that **you must eject from CRA in order for your project to use PDFJS**?

**Comment by timvandermeij** [comment]
Yes, indeed.
