### ISSUE TITLE
possibly corrupted PDF, "bad XRef entry"

### ISSUE THREAD

**Issue by robx** [mozilla/pdf.js#10326]
Problematic document: [test(1).pdf](https://github.com/mozilla/pdf.js/files/2643238/test.1.pdf)

The file was generated via a generator library, https://github.com/Twinside/Rasterific/blob/master/src/Graphics/Rasterific/MicroPdf.hs, and is presumably correct. I'm looking into fixing that. Also reporting here however because the file does display fine in macOS Preview.app, and it seems that in principle you aim to display corrupt PDFs where possible.

(You can generate more such PDFs via https://arp.vllmrt.net/puzzles/draw/)

Configuration:
- Web browser and its version: Firefox 63.0.3 (64-bit)
- Operating system and its version: macOS 10.14.1 (18B2107)
- PDF.js version: 2.1.93
- Is a browser extension: don't think so

Steps to reproduce the problem:
1. upload the attached PDF file to https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? display the PDF

<img width="369" alt="screenshot 2018-12-04 at 10 41 16" src="https://user-images.githubusercontent.com/132113/49432961-295c7f80-f7b1-11e8-8fc0-283de0f19171.png">

What went wrong? no document shown, console error message:

```
Unable to initialize viewer 
Object { name: "UnknownErrorException", message: "bad XRef entry", details: "FormatError: bad XRef entry", stack: "UnknownErrorExceptionClosure@https://mozilla.github.io/pdf.js/build/pdf.js:660:37\n@https://mozilla.github.io/pdf.js/build/pdf.js:653:38\n__w_pdfjs_require__@https://mozilla.github.io/pdf.js/build/pdf.js:52:12\n@https://mozilla.github.io/pdf.js/build/pdf.js:129:23\n__w_pdfjs_require__@https://mozilla.github.io/pdf.js/build/pdf.js:52:12\n@https://mozilla.github.io/pdf.js/build/pdf.js:116:18\n@https://mozilla.github.io/pdf.js/build/pdf.js:33:18\nwebpackUniversalModuleDefinition@https://mozilla.github.io/pdf.js/build/pdf.js:31:50\n@https://mozilla.github.io/pdf.js/build/pdf.js:23:11\n" }
base_viewer.js:492:6
Unable to initialize thumbnail viewer 
Object { name: "UnknownErrorException", message: "bad XRef entry", details: "FormatError: bad XRef entry", stack: "UnknownErrorExceptionClosure@https://mozilla.github.io/pdf.js/build/pdf.js:660:37\n@https://mozilla.github.io/pdf.js/build/pdf.js:653:38\n__w_pdfjs_require__@https://mozilla.github.io/pdf.js/build/pdf.js:52:12\n@https://mozilla.github.io/pdf.js/build/pdf.js:129:23\n__w_pdfjs_require__@https://mozilla.github.io/pdf.js/build/pdf.js:52:12\n@https://mozilla.github.io/pdf.js/build/pdf.js:116:18\n@https://mozilla.github.io/pdf.js/build/pdf.js:33:18\nwebpackUniversalModuleDefinition@https://mozilla.github.io/pdf.js/build/pdf.js:31:50\n@https://mozilla.github.io/pdf.js/build/pdf.js:23:11\n" }
pdf_thumbnail_viewer.js:187:6
PDF 22d7a303f42a54b959166c55778e8c8e [1.4 - / -] (PDF.js: 2.1.93) app.js:1068:6
```

**Comment by robx** [comment]
I did a bit of digging. It turns out I can fix things by changing

```
xref
0 7
0000000000 65535 f 
0000000015 00000 n 
0000000083 00000 n 
0000000130 00000 n 
0000000191 00000 n 
0000000366 00000 n 
0000019697 00000 n 
```

to

```
xref
1 7
0000000015 00000 n 
0000000083 00000 n 
0000000130 00000 n 
0000000191 00000 n 
0000000366 00000 n 
0000019697 00000 n 
```

**Comment by Snuffleupagus** [comment]
> [...] and it seems that in principle you aim to display corrupt PDFs where possible.

Given that no PDF viewer I've tried (Adobe Reader, PDFium in Chrome, nor PDF.js) is able to open this file, which indicates that it's *really* broken, it seems (somewhat) questionable if trying to fix this is worth the time/complexity when it's so clearly the PDF generator that's at fault here.

**Comment by Snuffleupagus** [comment]
> I did a bit of digging. It turns out I can fix things by changing
> 
> ```
> xref
> 0 7
> 0000000000 65535 f 
> 0000000015 00000 n 
> 0000000083 00000 n 
> 0000000130 00000 n 
> 0000000191 00000 n 
> 0000000366 00000 n 
> 0000019697 00000 n 
> ```
> 
> to
> 
> ```
> xref
> 1 7
> 0000000015 00000 n 
> 0000000083 00000 n 
> 0000000130 00000 n 
> 0000000191 00000 n 
> 0000000366 00000 n 
> 0000019697 00000 n 
> ```

Unfortunately that does *not* really fix anything here, since the PDF file still isn't valid with such a change.
However, the reason that this appears to work is that it makes the file very *obviously* corrupt, which thus trigger fallback code-paths in most PDF viewers.

What's actually wrong with this PDF file though is that the `XRef` table is pointing to the wrong objects, i.e. the correct XRef table should actually look like this instead:
```
xref
0 7
0000000000 65535 f 
0000000015 00000 n 
0000000083 00000 n 
0000000130 00000 n 
0000019697 00000 n 
0000000191 00000 n 
0000000366 00000 n 
trailer
<<
/Size 7
/Root 1 0 R 
>>
startxref
19783
```

**Comment by robx** [comment]
As one added data-point, it does display fine with evince aka Gnome Document Viewer 3.30.0. Your call whether to close.

And thanks for that correct table, I'll look into fixing it in the generator!

**Comment by timvandermeij** [comment]
Yes, this should be fixed in the generator instead.
