### ISSUE TITLE
Is it possible to insert extra pages in pdf _pages array?

### ISSUE THREAD

**Issue by pravid** [mozilla/pdf.js#10321]
This is not an issue but requirement.
I need to insert extra pages in pdf viewer. There is an array of pdf pages (viewer._pages). Is it possible to push data to this array or is there any method available to create and add new pages to the viewer?

**Comment by timvandermeij** [comment]
I guess you could work something out, but it's not in scope of the PDF.js project to render data other than data that is available in the PDF file.
