### ISSUE TITLE
Get or Open the Initial View

### ISSUE THREAD

**Issue by paschty** [mozilla/pdf.js#10332]
We have a own Viewer which uses the PDF.js api to render PDF and i can not find a way to get the initial view (from the pdf). I tried firefox and it does not display the initial page view(defined somehow in the pdf). Is there a way to get the initial view with the pdf.js api?

Attach (recommended) or Link to PDF file here:
https://duepublico.uni-duisburg-essen.de/servlets/DerivateServlet/Derivate-46194/ICB_Report_63.pdf

Configuration:
- Web browser and its version: Firefox Quantum 63.0.3 (64-Bit)
- Operating system and its version: macOs  Mojave 10.14.1

Steps to reproduce the problem:
1. Open PDF

What is the expected behavior? (add screenshot)
The initial View is on Page 2.
![expected](https://user-images.githubusercontent.com/7668803/49526194-9a825c80-f8af-11e8-9c36-9c0b970da9e6.png)

What went wrong? (add screenshot)
The first page is displayed, instead of page 2.
![firefox](https://user-images.githubusercontent.com/7668803/49526251-bb4ab200-f8af-11e8-9703-48af89a72f67.png)

Here is our own Viewer based on PDF.js 1.6.313. (Not the same Document, also not really related)
http://mycore.de/mir/rsc/viewer/mir_derivate_00000001/document.pdf

**Comment by timvandermeij** [comment]
Okular doesn't support this either. From a quick look in the PDF browser, it looks like this effect may be caused by the `OpenAction` dictionary, but I'm not 100% sure.

**Comment by timvandermeij** [comment]
It's indeed the `OpenAction` dictionary that takes care of this and we implemented support for it in #10334 (disabled by default for now though, so you need to enable it by flipping the `disableOpenActionDestination` preference).
