### ISSUE TITLE
Viewer requests pdf.worker.js every time a PDF is opened

### ISSUE THREAD

**Issue by tohvanah** [mozilla/pdf.js#10338]
Every call to PDFViewerApplication.open(), results in a new network request for pdf.worker.js. Is this avoidable when switching between PDFs?

**Comment by Snuffleupagus** [comment]
The worker file should be cached in the browser (which WFM, when checking the "Network" tab in the devtools), meaning that the file won't be downloaded more than once anyway.

Furhtermore, as outlined in the API docs it's possible to pass in a `PDFWorker` instance when calling `getDocument`; see https://github.com/mozilla/pdf.js/blob/45c01974657dcb7bc993b2f485a2541415bf63a0/src/display/api.js#L145-L146

Hence you should be able to manually create one `PDFWorker` instance, see https://github.com/mozilla/pdf.js/blob/45c01974657dcb7bc993b2f485a2541415bf63a0/src/display/api.js#L1322-L1338 and simply pass that to all `getDocument` invocations.

**Comment by jonathan010180** [comment]
Hi, i have a problema with getDocument
same pdf in multiple data.pdf 
⚙ data.pdf | 206 | xhr | pdf.worker.js:24017 | (disk cache) | 1 ms
⚙ data.pdf | 206 | xhr | pdf.worker.js:24017 | (disk cache) | 1 ms
⚙ data.pdf | 206 | xhr | pdf.worker.js:24017 | (disk cache) | 1 ms
⚙ data.pdf | 200 | xhr | pdf.worker.js:24017 | (disk cache) | 5 ms

continuo 50.
