### ISSUE TITLE
Bot maintenance

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10342]
It looks like the Windows bot is down since it does't response to commands anymore. The Linux bot sometimes doesn't post the success/failure messages. Perhaps it's best to just restart both.

While doing that, please update the following software to the latest supported versions for the OS for some open pull requests:

- `node`
- `npm`
- `gulp` and `gulp-cli`

**Comment by timvandermeij** [comment]
@brendandahl Do you have some time to perform these actions?

**Comment by brendandahl** [comment]
Both the bots are updated and running 10.14.1. Gulp is
[18:51:12] CLI version 2.0.1
[18:51:12] Local version 3.9.1

**Comment by timvandermeij** [comment]
Thank you!
