### ISSUE TITLE
What is the cmd to open the pdf in presentation mode as default setting?

### ISSUE THREAD

**Issue by filipdns** [mozilla/pdf.js#10343]
Hello,

the viewer work fine, great job!!

I want to use it with Qt but I want to open the pdf always in presentation mode, may it possible to do that?

thank you very much

**Comment by Snuffleupagus** [comment]
For security reasons, the Fullscreen API in browsers requires that entering fullscreen mode only occurs as a result of a user-initiated event; hence this is *not* possible to support.

**Comment by filipdns** [comment]
oh, ok. I don't know what is the security problem for that but ok, thank you very much for the reply
