### ISSUE TITLE
how to approach the networkManager?? 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#10359]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- Operating system and its version:
- PDF.js version: 2.0.305
- Is a browser extension:

Steps to reproduce the problem:
i want to stopping loading pdf file.
to solve this problem, i should approach networkManger.
how to stopping loading pdf file streaming??
method is abortAllRequests(), 

link: https://github.com/mozilla/pdf.js/issues/7930

**Comment by Snuffleupagus** [comment]
>     * PDF.js version: 2.0.305

That's not an official release, please refer to https://github.com/mozilla/pdf.js/releases.

> Steps to reproduce the problem:
> i want to stopping loading pdf file.
> [...]

In that case you should call the `destroy` method on the loadingTask, see https://github.com/mozilla/pdf.js/blob/e716038b12919f2a6ad236dbfe1d8ea296b3b11e/src/display/api.js#L475-L480

**Comment by Snuffleupagus** [comment]
Generally speaking, for any piece of software really, unless you've got a specific reason you should always use the *stable* releases.

> destroy method is making worker disable. but i should use worker in my page.
> so how to abort loading file like xhr.abort()?

Unfortunately these sentences are almost impossible to understand.
Closing, and cleaning up, various resources have nothing to do with using (or not using) a worker.

> i want to stop streaming file loading..

The only guess that I can provide here is that you'd need to set `disableStream` (and possibly `disableAutoFetch` too) when calling `getDocument`; see https://github.com/mozilla/pdf.js/blob/e716038b12919f2a6ad236dbfe1d8ea296b3b11e/src/display/api.js#L188-L196

> please help me.

Unfortunately it's *very* difficult for anyone to do so, given that it's quite hard to understand exactly what your actually asking. (Most likely this is a language barrier problem, but without *clear* information there's very little that anyone can do unfortunately.)

**Comment by timvandermeij** [comment]
Closing for now unless actionable information is presented.
