### ISSUE TITLE
Map not defined

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10357]
this only happens in mobile browsers. i noticed it started with v2.0

why is this so? even the demo url of pdf.js results in this error message. please see attached.

any ideas?

![pdfjs](https://user-images.githubusercontent.com/3955470/50050101-8fd88a80-012d-11e9-849d-190639440b1b.png)

**Comment by Snuffleupagus** [comment]
Simply put, browsers without even basic native support for `Map` are not supported in PDF.js version `2.0`; based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility every even remotely modern browser (even including IE11) supports `Map`.

**Comment by chitgoks** [comment]
thank you for the explanation.
