### ISSUE TITLE
Feature Request: Add pen annotation and highlighter markup capability

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [mozilla/pdf.js#10366]
I would like to be able to highlight and annotate PDFs in Firefox (using pdf.js), and then to be able to save the changes. This is possible in MS Edge. Further, it would be good to support the Microsoft Surface pen, but baseline highlighting/annotating and saving is required first.

Configuration:
- Web browser and its version: Firefox 65.0b4
- Operating system and its version: Win 10
- PDF.js version: ? built into Firefox 65.0b4
- Is a browser extension:

What is the expected behavior? (add screenshot)
This is example behaviour in MS Edge.
![image](https://user-images.githubusercontent.com/3485184/50284584-58315180-0451-11e9-9a8c-7212c9552644.png)

**Comment by timvandermeij** [comment]
PDF.js is only a renderer, not an editor. Creating annotations is specifically out of scope for the project.

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations

**Comment by THausherr** [comment]
@CaffeinatedAndroid search for "Annotationeer".
