### ISSUE TITLE
pdf.js work in chrome, but not work in IE?

### ISSUE THREAD

**Issue by sakila1012** [mozilla/pdf.js#10361]
I use VUE，

npm install pdfjs-dist

And import component from pdfjs-dist

```
import PDFJS from "pdfjs-dist"
``` 

this way can work in IE browser,not in chrome

If I import in other ways:

```
import PDFJS from "pdfjs-dist/webpack"
``` 

this way can work in chrome browser,not in IE

why ???

**Comment by timvandermeij** [comment]
Try the examples from the https://github.com/mozilla/pdf.js/tree/master/examples directory and check the consoles for any warnings/errors. "It doesn't work" is too generic and we cannot help out with that, especially if most of the issue template details are missing.
