### ISSUE TITLE
Wrong error log for "offsetParent is not set -- cannot scroll"

### ISSUE THREAD

**Issue by dabeku** [mozilla/pdf.js#10367]
Configuration:
- Web browser and its version: Chrome (but applies to all)
- Operating system and its version: Any
- PDF.js version: pdfjs-dist v2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
Imagine (e.g. an angular) application with tabs where only the currently visible tab is attached to the DOM tree. When you want to display a large PDF and switching the tab (which will disconnect the current tab from DOM tree) it logs an error.

I am just wondering about the following code:

```
function scrollIntoView(element, spot, skipOverflowHiddenElements = false) {
// Assuming offsetParent is available (it's not available when viewer is in
  // hidden iframe or object). We have to scroll: if the offsetParent is not set
  // producing the error. See also animationStarted.
  let parent = element.offsetParent;
  if (!parent) {
    console.error('offsetParent is not set -- cannot scroll');
    return;
  }
```

Why is this logging an error? Imho if element.isConnected === false it should be ok since the view is not visible nor attached to the DOM tree.

What is the expected behavior? (add screenshot)

No error log. It should just ignore it.

What went wrong? (add screenshot)

An error is shwon in debug console.

**Comment by timvandermeij** [comment]
I think your reasoning makes sense, but I'm not that familiar with the scrolling code. Perhaps @Snuffleupagus can chime in if you have ideas about this?

**Comment by Snuffleupagus** [comment]
> Perhaps @Snuffleupagus can chime in if you have ideas about this?

Since PDF.js was written primarily for use in Firefox, rather than for use with particular JS frameworks, I fail to see the need for any changes here especially since this isn't a breaking error. Furthermore, having a notification about `scrollIntoView` not attempting to do any scrolling may also be useful in some cases.
My suggestion would be WONTFIX, or INVALID, as the appropriate resolution here.

**Comment by timvandermeij** [comment]
Agreed. Moreover, the console log can always be removed in a custom deployment. Closing.

**Comment by Aravindhsiva** [comment]
It didn't help me render the rest of the screen, when I get this kinda error, Wat is this exactly meant for??

**Comment by Bluejanis** [comment]
If I understood Snuffleupagus correctly, this error log message should be changed to a warning.

**Comment by suhail-enosis** [comment]
Still seeing this error. So, it has still not been changed to a warning?
