### ISSUE TITLE
"Back" keyboard shortcut

### ISSUE THREAD

**Issue by GandalfSaxe** [mozilla/pdf.js#10360]
One often follow internal links in a PDF dock, and has to to back. A keyboard shortcut for this would be good, rather than having to click 🙂

**Comment by Snuffleupagus** [comment]
What's wrong with the already existing (standard) keyboard shortcut, i.e. <kbd>Alt</kbd>+<kbd>←</kbd>, for going back in the history (which as far as I can tell, most if not all browsers support)?

**Comment by GandalfSaxe** [comment]
Oh good then. Nothing is wrong with that, it just wasn't listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-are-the-pdfjs-keyboard-shortcuts

**Comment by GandalfSaxe** [comment]
Oh good then. Nothing is wrong with that, it just wasn't listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions

**Comment by GandalfSaxe** [comment]
Oh good then. Nothing is wrong with that, it just wasn't listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions

**Comment by Snuffleupagus** [comment]
> it just wasn't listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions

Nor should it be, since it's a *browser* shortcut used with the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History) and not PDF.js specific functionality.

**Comment by timvandermeij** [comment]
Closing as answered.

**Comment by GandalfSaxe** [comment]
It's an incredible useful shortcut when navigating PDF files though. I think it would be useful to mention among the others, even if it's not guaranteed to work on all setups?

**Comment by GandalfSaxe** [comment]
The `Alt+Left` shortcut wasn't obvious to me by the way. On Mac it's customary to use ⌘+[ for back in all applications. ⌥+← doesn't even work for back on macOS for me, either Safari or Chrome. That's why I think it'd be useful to mention among the other shortcuts; it's hard to know otherwise.

**Comment by Snuffleupagus** [comment]
> I think it would be useful to mention among the others, even if it's not guaranteed to work on all setups?

This doesn't really make sense; if something isn't guaranteed to work, it will be more confusing than anything to mention it in the FAQ.

>  I just tried in VSCode extension [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) on my Mac. ⌥+← worked.

That's a different project, which is in no way affiliated with the PDF.js project, so I'm not sure how this is relevant here?

 > The `Alt+Left` shortcut wasn't obvious to me by the way. On Mac it's customary to use ⌘+[ for back in all applications.

The standard browser keyboard shortcuts for traversing the history could very well be different for various platforms/operating systems. (The original post didn't mention anything about the platform; it probably would have been a good idea to actually fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening the issue :-)

For an overview of the various keyboard shortcuts used in the Firefox browser, please refer to https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly which should provide information which is relevant to the actual Firefox version and operating system being used.

**Comment by GandalfSaxe** [comment]
> This doesn't really make sense; if something isn't guaranteed to work, it will be more confusing than anything to mention it in the FAQ.
Unless we can list all the options perhaps? I don't personally know what else there is besides Alt+Left though.  
> That's a different project, which is in no way affiliated with the PDF.js project, so I'm not sure how this is relevant here?
It feels relevant because this particular project simply links to your FAQ for the keybindings. And it would be nice to have them gathered in one place. I get that the back functionality is technically not this project, but I think it's such an important feature that from the user's point of view isn't different from all the other shortcuts, so would be nice to have together. 
> The standard browser keyboard shortcuts for traversing the history could very well be different for various platforms/operating systems. (The original post didn't mention anything about the platform; it probably would have been a good idea to actually fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening the issue :-)
Well I never intended it to be platform-specific :) As I said I just thought it would be fitting to have a short mention of what the keyboard shortcut for "Back" _could_ be, with no guarantees, together with all the existing keyboard shortcuts that are there. Up to you of course, I just think it's an important enough feature to warrant an exception, even if it isn't technically belonging to this project 🙂

**Comment by GandalfSaxe** [comment]
> This doesn't really make sense; if something isn't guaranteed to work, it will be more confusing than anything to mention it in the FAQ.

Unless we can list all the options perhaps? I don't personally know what else there is besides Alt+Left though.  

> That's a different project, which is in no way affiliated with the PDF.js project, so I'm not sure how this is relevant here?

It feels relevant because this particular project simply links to your FAQ for the keybindings. And it would be nice to have them gathered in one place. I get that the back functionality is technically not this project, but I think it's such an important feature that from the user's point of view isn't different from all the other shortcuts, so would be nice to have together. 

> The standard browser keyboard shortcuts for traversing the history could very well be different for various platforms/operating systems. (The original post didn't mention anything about the platform; it probably would have been a good idea to actually fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening the issue :-)

Well I never intended it to be platform-specific :) As I said I just thought it would be fitting to have a short mention of what the keyboard shortcut for "Back" _could_ be, with no guarantees, together with all the existing keyboard shortcuts that are there. Up to you of course, I just think it's an important enough feature to warrant an exception, even if it isn't technically belonging to this project 🙂
