### ISSUE TITLE
When PDF is printed, all the messy codes are displayed as blocks

### ISSUE THREAD

**Issue by 15190408121** [mozilla/pdf.js#10365]
When my PDF was printed, the text was all squares, but the picture was displayed as normal
This is my code:
let _this = this
      var iframeElt = document.createElement('iframe')
      let pdfDocs = this.pdfDoc
      function removeIframe () {
        iframeElt.parentNode.removeChild(iframeElt)
      }
      new Promise(function (resolve, reject) {
        iframeElt.frameBorder = '0'
        iframeElt.scrolling = 'no'
        iframeElt.width = '0px;'
        iframeElt.height = '0px;'
        iframeElt.style.cssText = 'position: absolute; top: 0; left: 0'
        iframeElt.onload = function () {
          resolve(this.contentWindow)
        }
        window.document.body.appendChild(iframeElt)
      })
      .then(function(win) {
        win.document.title = _this.pdfTitle + ''
        var oMeta = document.createElement('meta')
        oMeta.charset = 'GB2312'
        win.document.getElementsByTagName('head')[0].appendChild(oMeta)
        var allPages = []
        pdfJS.locale = 'zh'
//        pdfJS.cMapUrl = _this.url
//          '../../../../../assets/cmaps/'
        pdfJS.cMapPacked = true
        for (var pageNumber = 1; pageNumber <= _this.numPages; pageNumber++) {
          allPages.push(
            pdfDocs.getPage(pageNumber).then(function (page) {
              var viewport = page.getViewport(1, 0)
              var printCanvasElt = win.document.body.appendChild(win.document.createElement('canvas'))
              var pageContainer = document.createElement('div')
              pageContainer.classList.add('page-container')
              pageContainer.style.width = viewport.width + 'px'
              pageContainer.style.height = viewport.height + 'px'
              printCanvasElt.width = viewport.width
              printCanvasElt.height = viewport.height
              printCanvasElt.font = '50px Arial'
              console.log(page)
              return page.render({
                canvasContext: printCanvasElt.getContext('2d'),
                viewport: viewport,
                intent: 'print',
                normalizeWhitespace: true
              }).promise
            })
          )
        }
        Promise.all(allPages)
        .then(function() {
          win.focus() // Required for IE
          win.print()
          removeIframe()
        })
        .catch(function(err) {
          removeIframe()
          console.error('error', err)
        })
      })

**Comment by 15190408121** [comment]
![1545216882 1](https://user-images.githubusercontent.com/25787427/50216069-c3cade80-03bf-11e9-8f06-8be654e76431.jpg)

**Comment by 15190408121** [comment]
This is what it looks like to print

**Comment by 15190408121** [comment]
But I'm sorry it's not available yet and other demos are not so good

**Comment by timvandermeij** [comment]
From the filename I conclude that the text is Chinese, so you most likely need cMaps in order for this to work. The problem is that you commented this out in your code, at `// pdfJS.cMapUrl = _this.url`.

**Comment by 15190408121** [comment]
Thank you

**Comment by 15190408121** [comment]
Thank you
