### ISSUE TITLE
Printing only currently viewed page of pdf

### ISSUE THREAD

**Issue by genealogi** [mozilla/pdf.js#10364]
Is there any way of setting the print button to only print the currently viewed page of the pdf? My pdf:s can have up to several hundred pages and my users will only be interested in printing one  page at the time, probably the currently viewed one.

I've been looking all over the internet but there is nothing about this. I'm testing in Firefox 64.0 on Windows 7.

**Comment by timvandermeij** [comment]
This functionality does not exist, but it may be considered as a feature.

**Comment by Snuffleupagus** [comment]
Isn't this simply tied to the general problem of JavaScript not really being able to control print settings in the way required for this to work, thus making this more-or-less impossible to fix?

**Comment by timvandermeij** [comment]
I think what could be done is to create a canvas with only the selected page and send that for printing instead of the whole document.

**Comment by Snuffleupagus** [comment]
Yes, but that would require a whole lot of setup (not to mention UI), for something that should ideally be achieved simply through the browser printing dialog (assuming the Web platform had the required APIs).

**Comment by timvandermeij** [comment]
> This can probably be tracked with issue #8839 instead, since the general problem really is lack of browser support rather than anything else in my opinion.

I agree. This is a more general issue about missing printing APIs. I guess we could work something out without them, but printing is already difficult enough with the lacking browser support. I can be implemented in a fork though for those interested, but for now I also don't see much value for the default viewer itself. Let's track this in the issue above instead.
