### ISSUE TITLE
Deprecated API usage with examples

### ISSUE THREAD

**Issue by 7twin** [mozilla/pdf.js#10377]
Configuration:
- Web browser and its version: Firefox 64.0
- Operating system and its version: Windows 10
- PDF.js version: '2.6.1' (included directly by `//mozilla.github.io/pdf.js/build/pdf.js`)
- Is a browser extension: No

Steps to reproduce the problem:
1. include via
- `<script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>`
2. set:
- `pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';`
3. use examples from: https://mozilla.github.io/pdf.js/examples/

What went wrong? (add screenshot)

![99733b699429b48a9982577efb14fdde](https://user-images.githubusercontent.com/32747235/50388605-9198e400-0713-11e9-8bcc-d28e119f083c.png)

**Comment by timvandermeij** [comment]
The examples have already been updated with this new API usage, just not yet on JSFiddle. @yurydelendik Could you perhaps update all examples on that page with the current code from the `examples` folder?

**Comment by yurydelendik** [comment]
Fixed

**Comment by avimar** [comment]
So from version 1 to version 2, I now have to explicitly refer to `.promise`?

```
//V1
const loadPDF = await PDFJS.getDocument(file);
const pages = loadPDF.numPages;
```

Now becomes this?
```
//V2
const loadPDF = PDFJS.getDocument(file);
const pages = await loadPDF.promise.then(pfd=> pdf.numPages);
```

This doesn't seem the norm for the JS ecosystem...

**Comment by A-EL** [comment]
the view port error is die to using version 1 way:
`var viewport = pdfPage.getViewport(scale, rotate);`

change it to use GetViewportParameters :
https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L158

`var viewport = pdfPage.getViewport({scale:scale, rotate:rotate});`
