### ISSUE TITLE
Manual click events do not work in mobile browsers

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10374]
So, i noticed click events do not work when called programmatically.

for example, document.getElementById('pageNumber').click()

it does not show up the keyboard. but only does so if i tap on the pageNumber input text field.

is this because of css in the viewer?

**Comment by timvandermeij** [comment]
We don't have any code in place to prevent that, so this sounds more like a mobile browser issue than a PDF.js issue.

**Comment by chitgoks** [comment]
sorry. i forgot to mention this is for iOS browser. in android browsers like chrome it works ok.

**Comment by chitgoks** [comment]
hi @timvandermeij , these calls work ok in safari browser. but in the pdf.js viewer, it's weird why the keyboard does not show up by calling that code.

However, it does show up if i manually tap on the input text field but calling .click() doesnt.

**Comment by timvandermeij** [comment]
I don't know why that is the case, but as said we don't do anything to prevent the keyboard from showing up. It may be worth asking on e.g., StackOverflow since it looks like a generic Safari issue.
