### ISSUE TITLE
gulp dist-install

### ISSUE THREAD

**Issue by Zwe1** [mozilla/pdf.js#10370]
Attach (recommended) or Link to PDF file here:
https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Chrome/67.0.3396.99
- Operating system and its version: macOS 10.13.6
- PDF.js version: 2.0.943
- Is a browser extension: 

Steps to reproduce the problem:
1. install the pdf.js module which version is 2.0.943
2. run the demo in 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by johnye2e** [comment]
It works using node.js version 14.15.0.
