### ISSUE TITLE
PDF JS Cannot set property 'disableWorker' of undefined

### ISSUE THREAD

**Issue by arushhyber** [mozilla/pdf.js#10373]
import React from 'react';
    import VisibilitySensor from 'react-visibility-sensor';
    import {PDFJS as PDFJS } from 'pdfjs-dist';
    // import 'pdfjs-dist/web/compatibility';

    PDFJS.disableWorker = true;

   const INCREASE_PERCENTAGE = 0.2;
   const DEFAULT_SCALE = 1.1;

   class PDFViewer extends React.Component{
    constructor(props){
        super(props)
        this.state ={},
        this.onChange = this.onChange.bind(this);
     }
     componentDidUpdate(prevProps,prevState){
         // we want to render/re-render in two scenarias
         // user scrolls to the pdf
         // user zooms in
         if(prevState.isVisible === this.state.isVisible && prevProps.zoom === this.props.zoom) return;
         if(this.state.isVisible) this.fetchAndRenderPage();
    }

    onChange(isVisible){
        if(isVisible){
            this.setState({isVisible})
        }
    }
    fetchAndRenderPage(){
        const {pdf,index} = this.props;
        pdf.getPage(index).then(this.renderPage.bind(this));
    }

    renderPage(page){
        const {containerWidth,zoom} = this.props;
        const calculatedScale = (containerWidth/page.getViewPort(DEFAULT_SCALE).width);
        const scale = calculatedScale > DEFAULT_SCALE ? DEFAULT_SCALE : calculatedScale;
        const viewport = page.getViewport(scale + zoom);
        const { width, height } = viewport;
    
        const context = this.canvas.getContext('2d');
        this.canvas.width = width;
        this.canvas.height = height;
    
        page.render({
          canvasContext: context,
          viewport,
        });
    }

    render(){
        return(
            <div className="pdf-canvas">
            <VisibilitySensor onChange={this.onChange} partialVisibility >
              <canvas ref={node => this.canvas = node} width="670" height="870" />
            </VisibilitySensor>
          </div>
        )
    }
}

export default class PDFDriver extends React.Component {
    constructor(props) {
      super(props);
  
      this.state = {
        pdf: null,
        zoom: 0,
        percent: 0,
      };
  
      this.increaseZoom = this.increaseZoom.bind(this);
      this.reduceZoom = this.reduceZoom.bind(this);
      this.resetZoom = this.resetZoom.bind(this);
    }
  
    componentDidMount() {
      const { filePath } = this.props;
      const containerWidth = this.container.offsetWidth;
      PDFJS.getDocument(filePath, null, null, this.progressCallback.bind(this)).then((pdf) => {
        this.setState({ pdf, containerWidth });
      });
    }
  
    setZoom(zoom) {
      this.setState({
        zoom,
      });
    }
  
    progressCallback(progress) {
      const percent = ((progress.loaded / progress.total) * 100).toFixed();
      this.setState({ percent });
    }
  
    reduceZoom() {
      if (this.state.zoom === 0) return;
      this.setZoom(this.state.zoom - 1);
    }
  
    increaseZoom() {
      this.setZoom(this.state.zoom + 1);
    }
  
    resetZoom() {
      this.setZoom(0);
    }
  
    renderPages() {
      const { pdf, containerWidth, zoom } = this.state;
      if (!pdf) return null;
      const pages = Array.apply(null, { length: pdf.numPages });
      return pages.map((v, i) => (
        (<PDFPage
          index={i + 1}
          pdf={pdf}
          containerWidth={containerWidth}
          zoom={zoom * INCREASE_PERCENTAGE}
        />)
      ));
    }
  
    renderLoading() {
      if (this.state.pdf) return null;
      return (<div className="pdf-loading">LOADING ({this.state.percent}%)</div>);
    }
  
    render() {
      return (
        <div className="pdf-viewer-container">
          <div className="pdf-viewer" ref={node => this.container = node} >
            <div className="pdf-controlls-container">
              <div className="view-control" onClick={this.increaseZoom} >
                <i className="zoom-in" />
              </div>
              <div className="view-control" onClick={this.resetZoom}>
                <i className="zoom-reset" />
              </div>
              <div className="view-control" onClick={this.reduceZoom}>
                <i className="zoom-out" />
              </div>
            </div>
            {this.renderLoading()}
            {this.renderPages()}
          </div>
        </div>
      );
    }
  }

**Comment by Snuffleupagus** [comment]
In PDF.js version `2.0` the global `PDFJS` object has been removed and been (more-or-less) replaced with `pdfjsLib` instead (also, the `disableWorker` option was removed).

Furthermore, when opening an issue you need to actually fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and as mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md code-snippets are of no use.

**Comment by timvandermeij** [comment]
Closing as answered until more information is provided.
