### ISSUE TITLE
pdf viewer renders link annotations incorrectly

### ISSUE THREAD

**Issue by melcher74** [mozilla/pdf.js#10385]
Attach (recommended) or Link to PDF file here:
https://cvmg.ca/resources/Au83gabGuDEC94zz/2019/CVMG%20News-5201-Jan%202019.pdf

Configuration:
- Web browser and its version: Firefox Quantum V 64.0
- Operating system and its version: OS X 10.14.2
- PDF.js version: not sure
- Is a browser extension: no

Steps to reproduce the problem:
1. click on the link to view the document in the current Firefox pdf viewer (the problem can only be observed when viewing this specifc file from the link).
2. skip to page 3 of the document to see examples of bookmarks and email links as described below.

What is the expected behavior? (add screenshot)
Clickable hotspots (aka link annotations) should be displayed wihtout the border.  Viewers should see a light dotted outline, or no outline until hovered around the link.

What went wrong? (add screenshot)
In the Firefox pdf viewer, link annotations are displayed with a 1px black border around each.  This decreases readability and makes the document display inconsistent with other browsers.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
This change is not really correct - if manually changing /W to /5, we don't get a thick border with Adobe, we still have an invisible border. But IMHO Adobe is wrong: "The border width in points. If this value is 0, no border shall drawn. Default value: 1." A name is like "nothing", so default 1 should be used.
[CVMG News-5201-Jan 2019-p8.pdf](https://github.com/mozilla/pdf.js/files/2723915/CVMG.News-5201-Jan.2019-p8.pdf)

**Comment by timvandermeij** [comment]
So if it's a `Name` object, we should always draw nothing instead of the current change where we try to parse the `Name`'s value?

**Comment by THausherr** [comment]
Yes. (or use 0, which mean "draw nothing"). That would replicate the current Adobe behavior.

**Comment by timvandermeij** [comment]
Fixed now. Thank you for the feedback, @THausherr!
