### ISSUE TITLE
Canvas is not vertically aligned with the text layer

### ISSUE THREAD

**Issue by LazyJoke** [mozilla/pdf.js#10389]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Google Chrome 71.0.3578.98（正式版本） （64 位）
- Operating system and its version: mac os
- PDF.js version: v 2.0.0
- Is a browser extension:

Steps to reproduce the problem:
1. 
![image](https://user-images.githubusercontent.com/23025622/50509473-ec8a5c80-0ac0-11e9-9e68-85109a904bd6.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since no example PDF file is provided and we have quite a few other open issues in the `text-selection` category for this problem.
