### ISSUE TITLE
migration - PDFJS not found

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#10386]
I'm trying to migrate from an older version to the current, but seems like there has been a bigger change since `PDFJS` isn't found in the project

Can't find any usefull examples on how to use it the way I used to?

```
function PDF(){
	if(!PDFJS.PDFViewer || !PDFJS.getDocument){
		throw Error('PDFJS could not be initiated');
	}
	PDFJS.workerSrc = PDF_WORKER;
	
	this.load = function(url, progress, complete){
		var loading = PDFJS.getDocument(url);
		if(progress){
			loading.onProgress = progress;
		}
		loading.promise.then(complete);
	};
	
	this.render = function(pdf_page, container, page_num, scale, text_layer){
		var options = {
			container : container,
			id : page_num,
			scale : scale,
			defaultViewport : pdf_page.getViewport(scale)
		};
		if(text_layer){
			options.textLayerFactory = new PDFJS.DefaultTextLayerFactory();
			options.annotationLayerFactory = new PDFJS.DefaultAnnotationLayerFactory();
		}
		
		var view = new PDFJS.PDFPageView(options);
		view.setPdfPage(pdf_page);
		view.draw();
	};
}
```

**Comment by timvandermeij** [comment]
Yes, the `examples` folder (at https://github.com/mozilla/pdf.js/tree/master/examples) has been updated with all changes for PDF.js 2.0. Note that version 2.0 is a major bump and therefore API-breaking changes have been made. Most notably, the global `PDFJS` object is replaced by other constructs. Refer to the examples for their usage.

**Comment by clarkk** [comment]
ok

I have now downloaded the lastest version 1 and I still get the same error?

`1.10.100`

**Comment by timvandermeij** [comment]
The global `PDFJS` object should still be available there, but we really recommend to upgrade to version 2.0 since it contains a lot of improvements.
