### ISSUE TITLE
CSP Policy break unsafe-eval

### ISSUE THREAD

**Issue by chintan3100** [mozilla/pdf.js#10387]
var g = function () {
  return this;
}() || Function("return this")();

**Comment by timvandermeij** [comment]
Closing since this is a duplicate of #10229 which is fixed and will be part of the next release.

**Comment by Que3216** [comment]
When's the next release planned for?

**Comment by timvandermeij** [comment]
It's tracked in #10416 and while there is no fixed date yet, we hope to get to this soon.
