### ISSUE TITLE
ADP paystubs still render slightly incorrectly (underscores below commas and dots)

### ISSUE THREAD

**Issue by dholbert** [mozilla/pdf.js#10388]
Attach (recommended) or Link to PDF file here:
Can't provide a PDF for privacy reasons, unfortunately; but any PDF paystub from ADP (https://my.adp.com/) should do.

Configuration:
- Web browser and its version: Firefox Nightly 66.0a1 (2018-12-27) (64-bit)
- Operating system and its version: Ubuntu 18.10
- PDF.js version: Not sure. Whatever's currently shipping with Firefox Nightly.
- Is a browser extension: No; using built-in PDF.js in Firefox Nightly.

Steps to reproduce the problem:
1. View a PDF paystub from ADP (you have to work for a company that uses ADP for paystubs, e.g. Mozilla Corporation)
2. Look at a number with a comma or a period, in the main table of numbers.

What is the expected behavior? There shouldn't be an underline beneath the punctuation. Here's a screenshot from Evince (native PDF viewer):
![adp-screenshot-evince](https://user-images.githubusercontent.com/426803/50491474-663e1f80-09c7-11e9-90d4-d8787cd168fe.png)

What went wrong? There's a ghost underline beneath the punctuation. Here's a screenshot in Firefox Nightly pdf.js-based "preview" mode:
![paystub-screenshot](https://user-images.githubusercontent.com/426803/50491332-9c2ed400-09c6-11e9-9b73-ae9fbf096f39.png)

**Comment by dholbert** [comment]
(Note that this is a longstanding issue, #2126 ; that one was just closed speculatively / because it was lacking the initial-comment-template, I guess, so as requested, I filed this one since I can still reproduce.)

**Comment by timvandermeij** [comment]
Would it be possible to create a minimal PDF file to reproduce the issue? I understand that you cannot share the entire PDF file, but perhaps it's possible to only cut out the `17.65` part to get a minimal PDF file to reproduce the issue. Without it, I don't think we can really fix this.

I don't personally have experience with creating reduced test PDF files; perhaps @Snuffleupagus has some hints for how you can do this so you don't have to share the PDF?

**Comment by dholbert** [comment]
Sure, I'm open to trying! Though, I don't know how to reduce PDF files either.

(I tried opening the PDF file in LibreOffice Draw and then saving it (with or without edits), but that produces a subtly-different PDF which doesn't reproduce the issue.)

**Comment by dholbert** [comment]
OK, I was able to hand-edit a paystub PDF in emacs, and do search-and-destroy for personal bits of information.  I'm still not comfortable posting the edited PDF publicly, but I'm open to emailing it confidentially to a PDF.js developer.  @timvandermeij , can I send it to you using the "info@" email address on your personal website?  Or is there another developer I should send it to?

**Comment by timvandermeij** [comment]
Hand-editing the PDF file is most likely the easiest way given the type of rendering issue. If you want to strip metadata, you can use the commands from https://gist.github.com/hubgit/6078384. Once you've done that, you can send it to me at info@timvandermeij.nl, after which I will do a verification as well. If I also find no confidential data, I'll let you know so you can upload it here once we determined that it's clean.

**Comment by dholbert** [comment]
Thanks. I looked at that README; the `exiftool` and `qpdf` commands both fail to run (with errors about the "xref table") on my hand-edited minimized PDF, probably because one of my line-removals caused subtle breakage. But I'm not too concerned (at least for exiftool), because I used `exiftool -all:all original-paystub.pdf` to dump the metadata that the tool could remove from the original, and none of the displayed information is interesting/personal. (It's just stuff like "Author : Automatic Data Processing,Inc.")

I'll email it over to you, though I'd still prefer not to post it publicly just to be on the safe side. If we need a public testcase here, I'm hoping one can be constructed from scratch (with information from my reduced pdf), and/or my testcase can be reduced much further before it's posted publicly.

**Comment by timvandermeij** [comment]
Thank you. I'll take a look.

> I'd still prefer not to post it publicly just to be on the safe side. If we need a public testcase here, I'm hoping one can be constructed from scratch (with information from my reduced pdf), and/or my testcase can be reduced much further before it's posted publicly.

That's perfectly fine. I'm sure we'll be able to reduce it to only the required PDF objects to reproduce the issue if we need a testcase for the regression tests. I'm hoping that it can be reduced to just the amount from your screenshot and removing all other objects in the file.

**Comment by timvandermeij** [comment]
I received the file and reduced it to the bare minimum to reproduce the issue, stripping out all other objects. I have received confirmation that this file is OK to share here.

The file: 
[issue-10388-reduced.pdf](https://github.com/mozilla/pdf.js/files/2717098/issue-10388-reduced.pdf)

The issue appears to be that the dot is not a character, but an image. In the PDF file it's drawn with `/W 16 /H 17`. If I change that to `/W 16 /H 16`, the problem is resolved. Therefore, I think PDF.js tries to fill up the extra height with a different color than other viewers do, but I'm not entirely sure how we determine this in the code. Hopefully this at least guides us in the right direction for solving this.

Please note that if you want to use this file for a regression test in a patch that its XRef table needs to be fixed, because I didn't do that yet. I think you can use `pdftk` for that, but I'm not sure since I never did that before.

**Comment by janpe2** [comment]
The stream looks like this:
![kuva](https://user-images.githubusercontent.com/26090208/50849263-29870680-137f-11e9-80d2-db72725fdbec.png)
Function `Parser.prototype.findDefaultInlineStreamEnd` (in core/parser.js) searches for the operator `EI` after inline image data. The PDF has 34 bytes of image data but the function returns 33. Thus the last byte will be missing and some pixels will be replaced with black in the last pixel row.

**Comment by dholbert** [comment]
Thanks for fixing! Looking forward to seeing this in Firefox Nightly when it makes it over there.

**Comment by Snuffleupagus** [comment]
> Thanks for fixing! Looking forward to seeing this in Firefox Nightly when it makes it over there.

The patch was included in https://bugzilla.mozilla.org/show_bug.cgi?id=1519834, so it *should* be in the latest Nightly already :-)

It's *really* unfortunate that it took over six years for this bug to be fixed, given how simple the solution turned out to be, but better late than never I suppose.

**Comment by dholbert** [comment]
Indeed, it's fixed in latest linux Nightly, version 66.0a1 (2019-01-15). Thanks!
