### ISSUE TITLE
Fix bugs for the `pdfjs-dist` repository

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10391]
- The `master` branch was not updated after the last release. Find out why and if need be update it manually for now.
- The release no longer contains a clickable backlink.

**Comment by KFPJ4XL9JMNP** [comment]
Very good

**Comment by brendandahl** [comment]
For not updating master: looks like this was a stupid mistake where I left off "master" in on_release.js push command.

@timvandermeij What do you mean by "The release no longer contains a clickable backlink."

**Comment by timvandermeij** [comment]
The releases at https://github.com/mozilla/pdfjs-dist/releases contained a link to what seemed like the last commit before the tag. See the v2.0.489 release for example if you expand the description. Somehow this changed to for example "mozilla/pdf.js@tags/v2.0.943" which isn't clickable anymore. Not sure if that intended given that the "ab06013" text next to the ZIP download is clickable?

**Comment by brendandahl** [comment]
Unfortunately the [release event](https://developer.github.com/v3/activity/events/types/#releaseevent) doesn't get a sha. We could probably pull the sha from within the on_release.js script, but I don't really think it's high priority, so I won't be looking into it.

**Comment by timvandermeij** [comment]
I don't really care about it either. I'm closing this issue then because the first point should be fixed now with your change in `on_release.js` and the second point won't be fixed.
