### ISSUE TITLE
How to set default 'spread' in url query string?

### ISSUE THREAD

**Issue by mikeblackstock** [mozilla/pdf.js#10406]
I would like to be able to set a 2-page spread as part of the url.
I tried this:
https://blackstock.media/TheChamberGuitar.pdf?spread=1
and this:
https://blackstock.media/TheChamberGuitar.pdf#spread=1

but neither works. Any ideas?
Thx!

**Comment by timvandermeij** [comment]
The query parameters should not be used for this purpose and as such we don't have a means to do that. Query parameter support is limited to only the ones mentioned in the PDF specification and I don't recall this being one of them. You should use the preferences (https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L23) instead.
