### ISSUE TITLE
PDFs are getting rendered vertically mirrored 

### ISSUE THREAD

**Issue by nleanba** [mozilla/pdf.js#10400]
Configuration:
- Web browser and its version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Operating system and its version: Tried on Ubuntu 18.04 and Windows 10
- PDF.js version: 2.0.943 (current from npm)
- Is a browser extension: no

### Steps to reproduce the problem:

I've copied the code from https://mozilla.github.io/pdf.js/examples/#hello-world-with-document-load-error-handling and changed 2 things:
1. added authorization headers (works fine when in jsfiddle)
2. `viewport.height` and `.width` both are `NaN`, so I've added a fallback to viewBox-properties

```javascript
var loadingTask = pdfjsLib.getDocument({
        url: url,
        httpHeaders: {
            'Authorization': server.headers.get('Authorization')
        }
    });
    loadingTask.promise.then(function (pdf) {
        console.log('PDF loaded');

        // Fetch the first page
        var pageNumber = 1;
        pdf.getPage(pageNumber).then(function (page) {
            console.log('Page loaded');

            var scale = 1.5;
            var viewport = page.getViewport({
                scale: scale
            });

            // Prepare canvas using PDF page dimensions
            var canvas = document.getElementById('the-canvas');
            var context = canvas.getContext('2d');
            canvas.height = viewport.height ||viewport.viewBox[3]; /* viewport.height is NaN */
            canvas.width = viewport.width || viewport.viewBox[2];  /* viewport.width is also NaN */

            // Render PDF page into canvas context
            var renderContext = {
                canvasContext: context,
                viewport: viewport
            };
            var renderTask = page.render(renderContext);
            renderTask.promise.then(function () {
                console.log('Page rendered');
            });
        });
    }, function (reason) {
        // PDF loading error
        console.error(reason);
    });
```

### What is the expected behavior?

Correct Rendering of the PDF

### What went wrong? (add screenshot)

![screenshot from 2019-01-02 16-10-16](https://user-images.githubusercontent.com/25827850/50598306-a5c6a900-0eaa-11e9-8ffa-21b50b7382db.png)

As you can see, the PDF is vertically mirrored. This is not a problem with this specific PDF, as it is rendered correctly [here](https://jsfiddle.net/pdfjs/9engc9mw/) and the issue happens with any other PDFs I've tested.

I think it has something to do with viewport.height` and `.width` being `NaN` and/or the fact that the example uses a newer (2.1.something) version of PDF.js, but I'd like to use the npm package.

**Comment by timvandermeij** [comment]
I think it may be because of:

```javascript
var viewport = page.getViewport({
  scale: scale
});
```

Could you try with `var viewport = page.getViewport(scale);` to see if that works? If so, we need to make a new release because this recently changed and we updated the examples already.

**Comment by nleanba** [comment]
`var viewport = page.getViewport(scale);` fixed the problem, thank you.

**Comment by timvandermeij** [comment]
Thank you for confirming. Hopefully we can make the new release soon so the new syntax can be used.

**Comment by blackmambahk** [comment]
Has this API changed back?
In 2.1.266 I am getting a deprecation warning calling getViewport and passing a number.
Looking at the code it seems to once again expect an object to be passed with properties scale, rotation and dontFlip

**Comment by timvandermeij** [comment]
The problem before was that the documentation was changed to accept an object whereas the release for that wasn't made yet. That is now done, so for the most recent release the API expects an object. If you pass a number, however, it will still work, but also show a deprecation warning.

**Comment by ndbroadbent** [comment]
@timvandermeij Thanks for that! I was wondering if someone could please update the nodejs example: https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js
Thanks!

**Comment by stevemarksd** [comment]
I'm still getting this issue on latest using object `{scale: ...}`

**Comment by MisaelMa** [comment]
I use  page.getViewport ({scale: 1.5, rotation: 360}); with that the problem of rotation was solved for me

**Comment by Carl0608** [comment]
@MisaelMa  Me too, but it works in my local setting using page.getViewport(1)

**Comment by jcursoli** [comment]
we are using the latest version and still experiencing this issue. looks like the types expect an object as well as the api.js code in the docs. Is there a reason this issue was closed or is there a workaround?

https://github.com/mozilla/pdf.js/blob/master/src/display/api.js

```
/**
   * @param {GetViewportParameters} params - Viewport parameters.
   * @returns {PageViewport} Contains 'width' and 'height' properties
   *   along with transforms required for rendering.
   */
  getViewport({
    scale,
    rotation = this.rotate,
    offsetX = 0,
    offsetY = 0,
    dontFlip = false,
  } = {}) {
    return new PageViewport({
      viewBox: this.view,
      scale,
      rotation,
      offsetX,
      offsetY,
      dontFlip,
    });
  }
```

**Comment by kvnam** [comment]
Hey I'm using version 3.5.141 and this is still happening. I tried both `{scale: 1.5, rotation: 360, dontFlip: true}` and `getViewport(1)`, neither works. While scale is reflected correctly, the image is still vertically and horizontally mirrored.

```
const vp = page.getViewport({ scale: 1.5, dontFlip: true});
const canvas = document.createElement("canvas");
 canvas.width = config?.width || 978;
canvas.height = config?.height || 1200;
    return page
      .render({
        canvasContext: canvas.getContext("2d"),
        viewport: vp,
      })
```
This returns a flipped image.. any ideas on how to resolve this?

**Comment by Siddharth2212** [comment]
I am facing this issue on flutter web . Any solutions yet?

**Comment by andyadams** [comment]
For anyone still encountering this: In my case, the bug was because I was setting rotation on the viewport to 0, but the internal rotate value on (from the PDF itself) was set to 180, meaning that I was overriding the correct default value. I had assumed that PDF.js would apply the `rotation` parameter _after_ the default rotation, but it was not the case.
