### ISSUE TITLE
How to render more than one viewer in one template/dom

### ISSUE THREAD

**Issue by rajashekarappala** [mozilla/pdf.js#10405]
I need to render multiple pdfs in multiple viewers respectively in the same template/dom. 

I'm getting the following issue even though I'm using different canvases with different ids. I think the issue is because of the promises(of the first pdf) are not being resolved in time. which makes the second viewer break. I mean I'm getting the first pdf properly in the first viewer but second is breaking and giving the below issue. 

![image](https://user-images.githubusercontent.com/22569614/50633570-cc034c00-0f71-11e9-8526-8b286414af5a.png)

Appreciate the help! Thanks

**Comment by timvandermeij** [comment]
The error is thrown at https://github.com/mozilla/pdf.js/blob/103f4616accbd29755e6d150f0a7c2e7a6bc6546/src/display/api.js#L2402-L2406, so it looks like some canvas is being reused. Even though they have different IDs, your code may have a reference to another canvas. Without the code it's impossible to tell though, so unless that's provided as stated in the issue template, there is nothing more we can do.
