### ISSUE TITLE
Embedded fonts not rendering pdf.js 2.0+

### ISSUE THREAD

**Issue by jbovatsek** [mozilla/pdf.js#10402]
Attach (recommended) or Link to PDF file here: [arial_systemfont.pdf](https://github.com/mozilla/pdf.js/files/2722535/arial_systemfont.pdf)

Configuration:
- Web browser and its version: Chrome [Web Viewer], Firefox [Internal Extension]
- Operating system and its version: Windows 10
- PDF.js version: (as reported by dev tools) 2.1.147 (Chrome; Web Viewer), 2.0.936 (Firefox; Internal)
- Is a browser extension: Yes and No

Steps to reproduce the problem:
1. Open Attached PDF in the [WebViewer](https://mozilla.github.io/pdf.js/web/viewer.html) or latest version of FireFox

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/279430/50619917-8165cf00-0ea0-11e9-8166-388ba1d8be76.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/279430/50619932-8f1b5480-0ea0-11e9-9236-01e4f3bb4c30.png)

Console Error:
Warning: Failed to load font "g_d4_f1": SyntaxError: Invalid font data in ArrayBuffer.

Other Information:
- It appears this error began with this commit:  https://github.com/mozilla/pdf.js/commit/b76cf665ecbe5195557df3f7441b1d6db94fb0c9 
- It only appears to be certain fonts.  For example, during generation I can swap the font to [Courier New](https://github.com/mozilla/pdf.js/files/2722685/couriernew_systemfont.pdf) or [Calibri](https://github.com/mozilla/pdf.js/files/2722686/calibri_systemfont.pdf) and it works. 
- It is not a local problem, it impacts PDFs generated across many systems 
- It is not only new PDFs, all previous PDFs generated are now broken
- I've tested all PDF viewers I can find and only pdf.js has the issue.
- PDF is generated via .net using a third party library

Since pdf.js was recently updated in Firefox Quantum, clients who use firefox are now unable to read any PDFs generated.

**Comment by timvandermeij** [comment]
@brendandahl Any ideas here about what may be going on?

**Comment by brendandahl** [comment]
Strange, Firefox doesn't seem to report open type santizer errors in the browser console any more. Running ots locally on the font I see:

```
ERROR at ../src/ots.h:112 (ReadU16)
ERROR: hmtx: Failed to read side bearing 4101
ERROR at ../src/ots.cc:698 (ProcessGeneric)
ERROR: hmtx: Failed to parse table
Failed to sanitize file!
```
