### ISSUE TITLE
I want to know which files can be view other than pdf in pdf.js

### ISSUE THREAD

**Issue by vgsunil** [mozilla/pdf.js#10403]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: all modern
- Operating system and its version: win 10
- PDF.js version: Stable (v2.0.943)
- Is a browser extension: no

i want to know which other file extention can be viewed in pdf.js as basically it is converting all pages in image form to render on browser , can we use it for other file system like for simple image view with functionality of zoom  given in pdf.js or for any other file system

**Comment by Snuffleupagus** [comment]
> i want to know which other file extention can be viewed in pdf.js

None, since as is clearly mentioned in the project description: `PDF Reader in JavaScript` (at the top of https://github.com/mozilla/pdf.js).

**Comment by vgsunil** [comment]
yeh but with minor changes we can make it usefull for other file formats right?

**Comment by Snuffleupagus** [comment]
> but with minor changes we can make it useful for other file formats right?

I very much doubt that it would simple, since the viewer is written explicitly with PDF files in mind. Besides, this is clearly out-of-scope for the PDF.js project itself.

**Comment by vgsunil** [comment]
agree but as an enhancement we can try to render some other file formates in image form to display other than just pdf files to make it reusable for other file systems too

**Comment by timvandermeij** [comment]
You can try to reuse the viewer for other document file format, but I don't think you can reuse much of the core logic. Closing as answered and out of scope.
