### ISSUE TITLE
mismatch example source version and downloadable version

### ISSUE THREAD

**Issue by kimmari10** [mozilla/pdf.js#10418]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. downloaded pre-built v2.0.943
2. i was following example "Interactive examples"
 (https://jsfiddle.net/pdfjs/9engc9mw/?utm_source=website&utm_medium=embed&utm_campaign=9engc9mw)
3. but it doesn't work rendering
4. compare with my source and example source
5. i found a difference.  in line 22, it is weird parameter format.

that reason is v2.1.157 in example source

please fix it. thankyou sir

![officialexamplesource](https://user-images.githubusercontent.com/5995985/50722694-17565f80-1116-11e9-8ec4-aeed14d88950.png)
![beforescalefixed](https://user-images.githubusercontent.com/5995985/50722692-17565f80-1116-11e9-8320-22a9a2e122f5.png)
![afterscalefixed](https://user-images.githubusercontent.com/5995985/50722691-16bdc900-1116-11e9-8f46-635386073062.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Yes, we are aware of this and it will be fixed once we release the new version, for which we have a tracking issue. For now, you can use the `var viewport = page.getViewport(scale);` syntax.
