### ISSUE TITLE
Checkboxes in pdf not printed correctly (ASCII code is printed instead)

### ISSUE THREAD

**Issue by kekkc** [mozilla/pdf.js#10414]
Attach (recommended) or Link to PDF file here:
[Ärztliche-Notwendigkeitsbescheinigung.pdf](https://github.com/mozilla/pdf.js/files/2727408/Arztliche-Notwendigkeitsbescheinigung.pdf)
[Patientenfragebogen.pdf](https://github.com/mozilla/pdf.js/files/2727409/Patientenfragebogen.pdf)

Configuration:
- Web browser and its version: FF 64 (but happens with Nightly 04.01.19, too)
- Operating system and its version: Win7
- PDF.js version: ?
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached documents in Firefox
2. Print the pdf

What is the expected behavior? (add screenshot)
Checkboxes should be printed as rectangles (Seems that the pdfs were generated with Word 2010 & Foxit Phantom)
What went wrong? (add screenshot)
ASCII code is printed

**Comment by zerefwayne** [comment]
@timvandermeij I'm new to pdf.js, can I take up this issue?

**Comment by Snuffleupagus** [comment]
This is an upstream bug, and the solution will require patching of Firefox; please refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1524640#c1.

---

> I'm new to pdf.js, can I take up this issue?

This most likely isn't a good first bug.

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
