### ISSUE TITLE
PDFjs.getMetadata() - XML parse bug, onEndElement(name)

### ISSUE THREAD

**Issue by dhollenbeck** [mozilla/pdf.js#10410]
The attached test PDF throws an error in onEndElement.

https://github.com/mozilla/pdf.js/blob/1b84b2ed603a18974c701381f67ddca4b392f569/src/display/xml_parser.js#L366-L372

The problem is `this._stack.pop()` will return undefined when `this._stack` is an empty array. This will set `this._currentFragment` to undefined and line 368 will throw an error:

```bash
TypeError: Cannot read property 'length' of undefined
```

Test file: [toissue.pdf](https://github.com/mozilla/pdf.js/files/2725637/toissue.pdf)

For what it is worth I have recently looped 42,000 pdf files using PDFjs to extract meta data from them. PDFjs has worked very well with the exception of recently submitted issues regarding metadata. I did front run PDFjs with `qpdf --check` to filter out any corrupt PDF files. I used PDFjs because in addition to extracting metadata I also need to extract page content. In all, I extracted 6.3 million pages of content using PDFjs.

**Thank you very much for PDFjs!**

**Comment by timvandermeij** [comment]
> I have recently looped 42,000 pdf files using PDFjs to extract meta data from them. PDFjs has worked very well with the exception of recently submitted issues regarding metadata. [...] In all, I extracted 6.3 million pages of content using PDFjs.

Those are pretty impressive numbers! It's really good to hear that PDF.js has been useful for your work, and the feedback you gave helps us a lot to improve, so thanks for the detailed issues you filed! There is a fix for this issue as well in the PR above, so once that lands this will be closed too.
