### ISSUE TITLE
Release version 2.1

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10416]
There some some `api-minor` patches and the example code on the website changed to the new syntax for `getViewport`, which caused some confusion for people that use the NPM package. We should make a release of version 2.1 to solve this and other issues we found and fixed after version 2.0.

**Comment by wojtekmaj** [comment]
Hi Tim, is there any schedule? I'm really looking forward to this release!

**Comment by wojtekmaj** [comment]
BTW this getViewport change is a breaking change in documented area of the app, so that's actually api-major unless you support both old and new way of passing the arguments.

**Comment by timvandermeij** [comment]
I don't think we have anything in the queue holding back a release. I don't mind taking core of this, so perhaps we can already do it next week if everyone agrees (/cc @brendandahl @yurydelendik).

The `getViewport` change is backwards compatible; refer to https://github.com/mozilla/pdf.js/pull/10369/files#diff-0ecad279ed2252e3eb47a4d96ec1463cR921. The old way of calling will still work and show a deprecation notice that the user should change it. It will only be removed in a major version (3.x).

**Comment by Snuffleupagus** [comment]
> make sure I'm not forgetting about something that really needs to be in version 2.1

Ideally, issue #10391 really ought to be fixed before the next release.

**Comment by timvandermeij** [comment]
I'm able to make the release soon, but I'm a bit short on time to also address the issue mentioned above. @brendandahl Last time we released version 2.0, did you look at why the master branch for `pdfjs-dist` was not updated (see #10391). It would be nice if we can get that fixed before making a new release.

**Comment by timvandermeij** [comment]
The issue above is now done, so I'll try to make the new release this weekend unless there are major objections (please comment here in that case). Doing that will also resolve the `getViewport` confusion.

**Comment by timvandermeij** [comment]
The release of version 2.1.245 is done. However, because of misunderstood instructions on https://github.com/mozilla/pdf.js/wiki/Release-Process the version is called 2.2.2 on `pdfjs-dist` and NPM because I updated the `pdfjs.config` file before making the release. To prevent this from happening again, I updated to page to remove the section from https://github.com/mozilla/pdf.js/wiki/Release-Process/055c021ab425b3e88877a40d8cb18d3956d4832e about updating the version prefix since I read that as that it should happen first because `api-minor` changes were merged.

@brendandahl Is there a way we can change the version number to 2.1.245 on `pdfjs-dist` or NPM? I'm not sure if it's really a problem because a future release will have a higher version number anyway.

**Comment by wojtekmaj** [comment]
@timvandermeij Within 24 hours you can unpublish a version from npm. You could then publish a correct version again.

**Comment by timvandermeij** [comment]
@wojtekmaj Thank you, I didn't know that.

@brendandahl Since the process is automated, I think only the bots or someone with the Node.js publisher account can do this. If we can remove it from NPM this way first, we can then remove it from `pdfjs-dist` manually and try to create a new release.

**Comment by timvandermeij** [comment]
The following steps should be taken:

- [x] Unpublish the release on NPM
- [x] Unpublish the release on `pdfjs-dist`
  - [x] Remove the tag
  - [x] Remove the release
  - [x] Remove the commit
- [x] Unpublish the release on `pdf.js`
  - [x] Remove the tag
  - [x] Remove the release
  - [ ] Revert the `pdfjs.config` version bumps

**Comment by coder-5943123** [comment]
Any new on the re-release ofd version 2.1? I can see the pdfjs-dist package was unlisted.

**Comment by timvandermeij** [comment]
I'll make the new release this weekend.

**Comment by timvandermeij** [comment]
Closing since v2.1.266 is now published as a pre-release (`next` tag on NPM).
