### ISSUE TITLE
relative URI are not recognized as link

### ISSUE THREAD

**Issue by deMichael** [mozilla/pdf.js#10427]
Attach (recommended) or Link to PDF file here:
[testpdf.pdf](https://github.com/mozilla/pdf.js/files/2732887/testpdf.pdf)

**Configuration:**
- Web browser and its version: Firefox 64.0
- Operating system and its version: Windows 10
- PDF.js version: Commit e4d2a16 (6 Jan 2019) 
- Is a browser extension: 

**What I like to do**
I am using pdf.js to display a pdf file in the browser from a local webserver. These pdf files contain relative links like “/myotherwebapp?show=0123456” (Source from the pdf file: <</S/URI/URI(/myotherwebapp?show=0123456)>> ) and this is parsed to text instead of a link but I would need a link like “http://localhost:8080/myotherwebapp?show=0123456” 

I know relative links in pdfs are not a good way but I have to work with it.

Does anyone know how to build pdf.js so that works or what to do or do I have to manipulate the link instead?

**What I found out but could not get working**
I found this issue https://github.com/mozilla/pdf.js/issues/8771 but I did not have it working with docBaseUrl. I do not know how to add the docBaseUrl and while debugging I did not stop in this method. How to make this api call?

While debugging I found out that the value for the url in the relative links is not set. Only the value for unsafe url is set but I could not find the position where it is set.

**What I did so far (as a matter of interest)**
I checked the examples but I found nothing about this. I opened the pdf in Firefox on my windows machine like “http://localhost:8087/example.pdf” and the relative links are working. They are parsed from “/myotherwebapp?show=0123456” to “http://localhost:8087/myotherwebapp?show=0123456” so everything is well.

After this I used the viewer.html from pdf.js to display the pdf file. The url looks like “http:// localhost:8087/pdf/web/viewer.html?file=http:// localhost:8087/example.pdf” and relative links are not working anymore, there is just text. Absolute links like “https://www.google.de“ are still clickable and working.

My next step was: Checkout the pdf.js sources and get it running on my machine. I got it running and building with “gulp server” and “gulp generic” as it is described on the project website. With “gulp server” and the url “http:// localhost:8888/web/viewer.html?file=http:// localhost:8888/ example.pdf” everything was working as expected. After this, I used “gulp generic” and copied the build files to my local webserver and the relative links are not working anymore.

**Comment by Snuffleupagus** [comment]
> I found this issue #8771 but I did not have it working with docBaseUrl. I do not know how to add the docBaseUrl and while debugging I did not stop in this method. How to make this api call?

It's already described in https://github.com/mozilla/pdf.js/issues/8771#issuecomment-321810126 how to make this work, but you essentially need to call the PDF.js API in the following way:
```javascript
pdfjsLib.getDocument({
  url: /* The URL pointing to the PDF document */,
  docBaseUrl: /* The URL you wish to use a the base for relative links */,
}).promise.then(function(pdfDocument) {
  // The PDF document is loaded here...
});
```
Please find all of the current API options at https://github.com/mozilla/pdf.js/blob/e4d2a1604efdb4a49f29b4a593baea23e4470c36/src/display/api.js#L123-L202

**Comment by deMichael** [comment]
Thank you, it was the clue which I needed.

**Comment by ashleyjb** [comment]
Did this work? 

I'm trying this method in a wordpress multisite - where PDFs are replicated across many sites.  To reduce duplication - this would be perfect.

How would I put this code into the template page so that embedded links in the pdf are switched from the main domain to the subdomain?

Thanks

**Comment by chitgoks** [comment]
@Snuffleupagus  when doing pdfjsLib.getDocument({}). does this mean we cannot use the default viewer anymore and have to create our own?
