### ISSUE TITLE
PDF JS does not work in Chrome Extensions

### ISSUE THREAD

**Issue by bjgallag** [mozilla/pdf.js#10429]
Attach (recommended) or Link to PDF file here:
[test-indenture.pdf](https://github.com/mozilla/pdf.js/files/2735198/test-indenture.pdf)
Configuration:
- Web browser and its version: Chrome 71.0.3578.98
- Operating system and its version: Microsoft Windows [Version 10.0.17134.472]
- PDF.js version: pdfjs-dist 2.0.943
- Is a browser extension: Yes

Steps to reproduce the problem:
0. This is a Chrome extension and as such, you are required to use RequireJS in the require([]) format.
1. Install pdfjs-dist in root directory using npm install pdfjs-dist --save (./node_modules/pdfjs-dist/)
2. require pdfjs-dist in the popup.js script
3. Fails because all calls for RequireJS made in pdf.js are not in the require([]) format.

What is the expected behavior? (add screenshot)
Allow pdf.js to be required. My end goal is to simply extract text from the PDF, not to view using the PDF JS chrome extension in the browser.
What went wrong? (add screenshot)
Many require([]) errors. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As outlined in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), for issues with custom implementations you *need* to provide access to a complete and runnable example since it's basically impossible for anyone to help otherwise.

**Comment by timvandermeij** [comment]
Closing as answered until more information is provided. Moreover, if you only want text selection, a much easier solution would be to simply use Node.js. We even have an example for text extraction: https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L44-L51
