### ISSUE TITLE
Touch selection not working in ios 10 and android 4 above versions

### ISSUE THREAD

**Issue by gokulkrishnar** [mozilla/pdf.js#10439]
Highlight text in IPAD ios version 12.1 and samsung tablet android os version 5.0.2 is not working. Mouse selection component is available for text selection using mouse whereas is there any touch selection component available for selecting text in the above devices.Is there any solution for handling touch events in the above devices?

Also we have checked on the Mozilla PDF.js demo page, it is working fine for web browsers but not in devices

**Comment by Snuffleupagus** [comment]
Given that this is limited to particular platforms/browsers, and considering the somewhat limited information provided, it unfortunately seems unlikely to be a valid PDF.js issue; hence it's probably not meaningful to keep this issue open.
