### ISSUE TITLE
Invalid PDF structure

### ISSUE THREAD

**Issue by 630383257** [mozilla/pdf.js#10438]
hi~
I got an error when I opend some pdf files using pdf.js，although this is a rare case but a problem that needs to be solved.And there are still some files that display garbled characters when they are opened.
```
PDF.js v2.0.943 (build: dc98bf76)
信息：Invalid PDF structure
```
The following are the error files for the prompt 'Invalid PDF structure'.
[急性呼吸道感染抗生素合理使用指南（试行）（下部分）.pdf](https://github.com/mozilla/pdf.js/files/2743637/default.pdf)
[上海市1980、1990、2000年心力衰竭住院患者流行病学及治疗状况调查.pdf](https://github.com/mozilla/pdf.js/files/2743647/1980.1990.2000.pdf)
[硝酸酯治疗新进展.pdf](https://github.com/mozilla/pdf.js/files/2743671/default.pdf)

The following are the files showing garbled characters.
[黄芪对心血管系统作用的实验药理学研究进展.pdf](https://github.com/mozilla/pdf.js/files/2743662/default.pdf)
[我国中年人群心血管病主要危险因素流行现状及从80年代初至90年代末的变化趋势.pdf](https://github.com/mozilla/pdf.js/files/2743663/80.90.pdf)
[心血管系列讲座心力衰竭治疗的进展.pdf](https://github.com/mozilla/pdf.js/files/2743664/default.pdf)

Hope to get a solution,
thx.

**Comment by THausherr** [comment]
These are two different problems so it would be better to create different issues.

**Comment by timvandermeij** [comment]
The invalid PDF structure error is fixed. If the garbled characters are still an issue with https://mozilla.github.io/pdf.js/web/viewer.html, please open a new issue.

**Comment by PLQin** [comment]
```
const { success, data } = await getPDF({ fileId:1 });
if (success) {
    const blob = new Blob([data], {
        type: `application/pdf;charset-UTF-8`, // word文档为msword,pdf文档为pdf
    });
    const objectURL = URL.createObjectURL(blob);
    this.pdfUrl = objectURL;
}
```

and set request `responseType: 'blob' `
