### ISSUE TITLE
PDF rotation using PDFViewer 

### ISSUE THREAD

**Issue by nadrane** [mozilla/pdf.js#10434]
Configuration:
- Web browser and its version: Chrome 71
- Operating system and its version: OSX
- PDF.js version: 2.0.489
- Is a browser extension: No

Steps to reproduce the problem:

I'm trying to rotate a PDF using the [PDFViewer](https://github.com/mozilla/pdf.js/blob/42b7bb47511ca30e55a41c653c6bdc9d841bfb4b/web/pdf_viewer.js#L20) API. [BaseViewer](https://github.com/mozilla/pdf.js/blob/98b4aff291f68adfec7209f830892f865f8ebbef/web/base_viewer.js#L131), which PDFViewer extends, has a setter called [pagesRotation](https://github.com/mozilla/pdf.js/blob/98b4aff291f68adfec7209f830892f865f8ebbef/web/base_viewer.js#L327). I'm currently have some code that attempts to use this `pagesRotation` API, though the rotation is not reflected in the rendered PDF after setting it.

Here is a simplified version of my code that renders the initial PDF:

```js

    const pdfDocument = await pdfjs.getDocument(url);


    this.linkService = new PDFLinkService();
    this.viewer = new PDFViewer({
      container: this.containerNode,   // This is just a div HTML node
      enhanceTextSelection: true,
      removePageBorders: true,
      linkService: this.linkService
    });

    this.viewer.setDocument(pdfDocument);
    this.linkService.setDocument(pdfDocument);
    this.linkService.setViewer(this.viewer);
```

This code works wonderfully. When I try to set a rotation on the PDFViewer, however, I run into problems:

```js
this.viewer.pagesRotation = 90
```

The original PDF remains unchanged upon setting this rotation value. I thought perhaps I needed to force a [render](https://github.com/mozilla/pdf.js/blob/98b4aff291f68adfec7209f830892f865f8ebbef/web/base_viewer.js#L954) and tried this:

```js
this.viewer.pagesRotation = 90
this.viewer.forceRendering()
```

This did not cause the PDF to render in a rotated form either.

I'm wondering if someone can direct me towards an API to apply a rotation transformation to every page in a PDF. Is the API I'm using even public? Perhaps I'm just using it incorrectly. I'd appreciate any advice.

EDIT: One thing to note is that my code is rendering the PDF within the context of React. React is rendering the PDF using `ref`s, so I don't think React is the problem. With that said, I thought I'd mention it.

Thank you very much!

**Comment by Snuffleupagus** [comment]
Rotation works fine in my testing, when using e.g. the `simpleviewer` example as-is; refer to [simpleviewer.html](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.html) and [simpleviewer.js](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js).

Either you're not actually including the `pdf_viewer.css` file, which is *required*, or there's some (external) HTML and/or CSS which is interfering with the PDF.js code itself and causing issues.
Unfortunately though, it's simply impossible for anyone to provide more assistance here; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by soubhikchatterjee** [comment]
The rotation works fine in the web view, but the original file remains unchanged in the disk. Is there anyway we can save the changes to the original file on the disk?

**Comment by leohxj** [comment]
use `window.PDFViewerApplication.pdfViewer.pagesRotation` to get rorate angle,
use `window.PDFViewerApplication.rotatePages()` to set apge ratate angle.
