### ISSUE TITLE
On a web page, while opening up a link which is embedded on a pdf document, a new pdf doc opens on a double frame.

### ISSUE THREAD

**Issue by Nashiya** [mozilla/pdf.js#10430]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Operating system and its version: Windows 7 Enterprise
- PDF.js version:
- Is a browser extension:Yes

Steps to reproduce the problem:
1. PDF Viewer chrome extension is enabled...Logon to the application website, open up a pdf document...There are no issues..
2.There are some links available inside a PDF document, clicking on which opens up another pdf document on the same page...looks like a double framed one. PFA for a better understanding.
3. If PDF viewer is disabled, then the pdf document opens properly.

What is the expected behavior? (add screenshot)
PDF document through the link opens up on the same window as in screenshot...

![pdf_expected](https://user-images.githubusercontent.com/46337962/50813507-9c22c280-133c-11e9-9df4-d93dec25383e.jpg)

What went wrong? (add screenshot)
Keeping PDF Viewer chrome extension enabled, PDF document supposed to be open on same window gets opened but on a double framed screen . PFA
![duble_frame](https://user-images.githubusercontent.com/46337962/50813082-384bca00-133b-11e9-9663-a1b5a09ff5d0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
chrome://extensions/?id=oemmndcbldboiebfnladdacbdfmadadm

Please guide me and revert back to me for any queries.

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
> 
>     1. PDF Viewer chrome extension is enabled...Logon to the application website, open up a pdf document...There are no issues..
>        2.There are some links available inside a PDF document, clicking on which opens up another pdf document on the same page...looks like a double framed one. PFA for a better understanding.
> 
>     2. If PDF viewer is disabled, then the pdf document opens properly.

Without access (i.e. a link) to an actual test-case, this issue is essentially not actionable and will probably be closed as incomplete.
Note that, for PDF files embedded in `<iframe>`s, the default viewer contains functionality that *should* prevent links from opening in the same `<iframe>`.

> PDF.js version:

Please provide this information, since it's very important when reporting a bug.

**Comment by timvandermeij** [comment]
Closing as answered until more information is provided.
