### ISSUE TITLE
 Format string vulnerability in PDF.js

### ISSUE THREAD

**Issue by RootUp** [mozilla/pdf.js#10445]
Hi Team, 

**Upstream bug**: [1519031](https://bugzilla.mozilla.org/show_bug.cgi?id=1519031)
Looks like the [patch](https://github.com/mozilla/pdf.js/pull/10304) which was made for my previous bug end up with a new issue. A format string vulnerability is observed in Mozilla-PDF.js.

## Steps to reproduce:
    git clone https://github.com/mozilla/pdf.js.git
    cd pdf.js
    npm install -g gulp-cli
    npm install
    gulp server

Once the server is up and running on port 8888, send a malformed URI request with format string in GET or HEAD method.

`curl -v http://127.0.0.1:8888/%s%s`

## Trace/Debug log:
The PDF.js server gets crash, and below is the trace for same.
```
Server running at http://localhost:8888/
[12:16:22] 'server' errored after 1.01 h
[12:16:22] URIError: URI malformed
at decodeURI (<anonymous>)
at WebServer._handler (/Users/Dhiraj/Desktop/pdf.js/test/webserver.js:86:35)
at Server.emit (events.js:188:13)
at Server.EventEmitter.emit (domain.js:459:23)
at parserOnIncoming (_http_server.js:676:12)
at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

I request if some one could vouch me for my work, that would be great :)
https://mozillians.org/en-US/u/Dhiraj_Mishra/

Thanks.

**Comment by timvandermeij** [comment]
Note that the impact is very limited, just like the other patch, because it's a development webserver and it's not meant to be used in any kind of production environment. Nevertheless, we should fix this.
