### ISSUE TITLE
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.entireWord.addEventListener')

### ISSUE THREAD

**Issue by DicksB** [mozilla/pdf.js#10440]
I'm getting this error and an empty viewer (controls load, but not the PDF) on every file on several sites. Example:

https://strategicchange.mo.gov/media/pdf/dor-strategic-change

Direct URL to file:
https://strategicchange.mo.gov/sites/strategicchange/files/media/pdf/2018/08/DOR-strategic-change-new.pdf

Appears to be happening at viewer.js 443:448

**Comment by Snuffleupagus** [comment]
> Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.entireWord.addEventListener') 
>
> I'm getting this error and an empty viewer (controls load, but not the PDF) on every file on several sites.

I cannot reproduce this, using either Firefox Nightly 66 or Google Chrome 72.

> https://strategicchange.mo.gov/media/pdf/dor-strategic-change

That page utilizes a *custom implementation* of the PDF.js default viewer, hence you'll need to contact the website for support since it's not possible for anyone here to make changes to (or update) that code.

**Comment by DicksB** [comment]
My apologies -- the problem appears to be that Incapsula is serving up old copies of the library, resulting in some version mismatches. I need to figure out why it's not respecting our cache invalidations.

Regarding the custom implementation, we made a small change to the CSS to improve the contrast of a control for accessibility. It *should* otherwise be unchanged. Regardless, the problem I'm seeing clearly has nothing to do with the library. Thank you!
