### ISSUE TITLE
What is the meaning of PDFJSDev?

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#10454]
PDFJSDev has some different values, but i do not know what is the meaning of it

**Comment by Snuffleupagus** [comment]
`PDFJSDev` are the various build targets, please refer to https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/gulpfile.js#L88-L101 and the various `gulp.task` occurrences in that file; for example https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/gulpfile.js#L609-L611

**Comment by kerbskerbs** [comment]
how to use the it ?  the PDFJSDev,
 if i want to use "firefox_print_service" ,what can i do?   
because "pdf_print_service" has the bug (FIREFOX)
