### ISSUE TITLE
PDF doesn't load in incognito mode in Chrome

### ISSUE THREAD

**Issue by sanjeevpurohit** [mozilla/pdf.js#10459]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: - Chrome-71.0.3578.98
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to https://maritimeintelligence.informa.com/Key%20Accounts/2018/12/04/13/25/lloydslistspecialintroduction-us in Chrome within an incognito window
2. Click on Richard Clayton within Meet the team section and the PDF viewer opens but the pdf doesn't get loaded. Upon looking at network debug section in Chrome, I see an error (ERR_CERT_COMMON_NAME_INVALID) when it tries to load https://px.ads.linkedin.com/collect/?time=1547650575859&pid=333333333&url=https%3A%2F%2Fmaritimeintelligence.informa.com%2FKey%2520Accounts%2F2018%2F12%2F04%2F13%2F25%2Flloydslistspecialintroduction-us&fmt=js&s=1. Refer to IncognitoBrowser.PNG
3. When doing the same steps in the normal Chrome tab, the PDF loads as expected. Refer to screenshot NormalBrowser.PNG.

What is the expected behavior? (add screenshot) PDF should load as it does in normal tab (NormalBrowser.PNG)

What went wrong? (add screenshot) PDF doesn't load

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Mentioned above in Step 1

![normalbrowser](https://user-images.githubusercontent.com/21063350/51257343-ae89a580-19a7-11e9-8889-7eadd693063c.PNG)
![incognitobrowser](https://user-images.githubusercontent.com/21063350/51257345-ae89a580-19a7-11e9-9338-49f7a223f3d1.PNG)

**Comment by Snuffleupagus** [comment]
> Upon looking at network debug section in Chrome, I see an error (ERR_CERT_COMMON_NAME_INVALID) when it tries to load https://px.ads.linkedin.com/collect/?time=1547650575859&pid=333333333&url=https%3A%2F%2Fmaritimeintelligence.informa.com%2FKey%2520Accounts%2F2018%2F12%2F04%2F13%2F25%2Flloydslistspecialintroduction-us&fmt=js&s=1.

That page utilizes a *custom* implementation of the PDF.js default viewer (the version used doesn't correspond to any [official release](https://github.com/mozilla/pdf.js/releases) and it's quite out of date as well), hence you'll need to contact the website for support since it's not possible for anyone here to make changes to (or update) that code.
