### ISSUE TITLE
How to use or create PDFDataRangeTransport?

### ISSUE THREAD

**Issue by hojas** [mozilla/pdf.js#10452]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome v71
- Operating system and its version: MacOS 10.14.2
- PDF.js version: v2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. I want to know how to use PDFDataRangeTransport, there is no document about it.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I want to know how to use PDFDataRangeTransport, there is no document about it.

The API unit-tests contain (basic) examples of using `PDFDataRangeTransport`, see https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/test/unit/api_spec.js#L1451-L1546

---

The default viewer (when used in Firefox) also uses `PDFDataRangeTransport`, see https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/web/app.js#L485-L521 together with https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/web/firefoxcom.js#L201-L210 and https://github.com/mozilla/pdf.js/blob/5cb00b79676bd84554ff3368d4f14d8470916039/web/firefoxcom.js#L221-L265

**Comment by hojas** [comment]
@Snuffleupagus Thanks. But can not render the first page before downloaded the full file. How to render with ranges?

**Comment by Snuffleupagus** [comment]
> But can not render the first page before downloaded the full file. How to render with ranges?

This issue asked how to use `PDFDataRangeTransport`, and examples were provided above. It's simply impossible, for anyone, to answer follow-up questions with zero context; please refer to https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md and in particular (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing since the original question is answered.
