### ISSUE TITLE
How to reduce memory usage while using PDFJS in custom pdf viewer

### ISSUE THREAD

**Issue by bikramnayak** [mozilla/pdf.js#10451]
Attach (recommended) or Link to PDF file here: [https://github.com/bikramnayak/Angular_Repository/blob/master/file.pdf]

Configuration:
- Web browser and its version: Chrome 71.0.3578.98
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943

Steps to reproduce the problem:
1. On loading it hangs up the browser

What is the expected behavior? (add screenshot)
My viewer should use less memory as the default viewer

Detail Description of the requirement:

I am using pdfjs to create custom pdf viewer in angular 6. While uploading a pdf of 4.5 mb having 1100 pages it hangs up the browser. I am loading the pdf in chunks (524288) and creating canvases on scroll only like in default viewer of pdfjs(10 canvas at a time) others are loading icon page still my browser consumes more memory.

can any one please guide me to solve this issue?

Chunk loading :
![image](https://user-images.githubusercontent.com/2460961/51162204-5f664680-18bb-11e9-9f3a-52198def7f3d.png)

Memory Usage: 
![image](https://user-images.githubusercontent.com/2460961/51162316-bd932980-18bb-11e9-9a8b-34f3976f1715.png)

Code: 

import { Component, Input, Output, EventEmitter, OnInit, SimpleChanges, OnChanges, AfterViewInit, HostListener, ViewEncapsulation, ElementRef } from '@angular/core';
// import { PDFProgressData } from 'pdfjs-dist';
import * as PDFJS from 'pdfjs-dist/webpack.js';
import * as PDFJSViewer from 'pdfjs-dist/web/pdf_viewer.js';

@Component({
    selector: 'pdf-viewer',
    templateUrl: './pdf-viewer.component.html',
    styleUrls: ['./pdf-viewer.component.css'],
    encapsulation: ViewEncapsulation.None
})
export class PDFViewerComponent implements OnInit, OnChanges {
    @Input('header') header: Array<string>;
    @Input() viewer_id: any;
    @Input() height: any;
    @Input() width: any;
    @Input() src: any;
    @Input() textLayerMode: boolean;
    @Input() chunkSize: number;
    @Input() zoom: number;
    @Output() pageSelection: EventEmitter<any> = new EventEmitter();
    @Output() contextMenu: EventEmitter<any> = new EventEmitter();
    //@Output('on-progress') onProgress = new EventEmitter<PDFProgressData>();

    currentPageNo: number = 1;
    totalPageNo: number;
    arrCanvasWrapper = new Array();
    arrTextLayer = new Array();
    viewportScale: any;

    constructor(private element: ElementRef) {
        let pdfWorkerSrc: string = 'pdfjs-dist/build/pdf.worker.js';
        (PDFJS as any).GlobalWorkerOptions.workerSrc = pdfWorkerSrc;
    }

    ngOnInit(): void {
        this.getDefaultSetting();
        this.renderPdf();
    }
    /** 
     *  1 KB = 1024 Byte
     *  64 KB = 65536 Byte
     *  128 KB = 131072 Byte
     *  512 KB = 524288 Byte 
     *  Chunk Size to be passed as Byte
     */
    getDefaultSetting() {
        this.viewer_id = this.viewer_id == null ? 'viewer' : this.viewer_id;
        this.textLayerMode = this.textLayerMode == null ? false : this.textLayerMode;
        this.chunkSize = this.chunkSize == null ? 524288 : this.chunkSize;
        this.zoom = this.zoom == null || this.zoom == undefined ? 2.0 : this.zoom;
        this.textLayerMode = false;
        this.src = '/assets/file.pdf';
    }

    ngOnChanges(changes: SimpleChanges) {
        this.renderPdf();
    }

    clearContainer() {
        const viewer = document.getElementById(this.viewer_id);
        if (viewer != null) {
            viewer.innerHTML = '';
        }
    }
    zoomOut() {
        if (this.zoom <= 0.5)
            return;
        this.zoom = this.zoom - 0.5;
        this.renderPdf();
    }

    zoomIn() {
        this.zoom = this.zoom + 0.5;
        this.renderPdf();
    }

    renderPdf() {
        const componentRef = this;
        if (this.src == null || this.src == '' || this.src == 'undefined') {
            this.clearContainer();
            return;
        }

        var loadingTask = PDFJS.getDocument({
            url: this.src,
            // httpHeaders: this.header,
            rangeChunkSize: this.chunkSize,
            disableAutoFetch: true,
            disableStream: true
        });

        // loadingTask.onProgress = (progressData: PDFProgressData) => {
        //     this.onProgress.emit(progressData);
        //   };

        loadingTask.promise.then(function (pdfDocument) {
            componentRef.clearContainer();
            componentRef.totalPageNo = pdfDocument.numPages;
            componentRef.drawPage(pdfDocument);
        });

    }

    drawPage(pdfDocument) {
        const componentRef = this;
        const viewer = document.getElementById(componentRef.viewer_id);

        for (let i = 1; i <= pdfDocument.numPages; i++) {
            pdfDocument.getPage(i).then(function (page) {
                const scale = componentRef.zoom;
                const scaledViewport = page.getViewport(scale);
                componentRef.viewportScale = scaledViewport;
                const div = document.createElement('div');

                div.setAttribute('id', 'page-' + (page.pageIndex + 1));
                div.setAttribute('doc-page-no', (page.pageIndex + 1));
                if (page.pageIndex < 1) {
                    div.setAttribute('data-loaded', 'true');
                }
                viewer.setAttribute('style', 'height:' + scaledViewport.height + 'px; width:' + scaledViewport.width + 'px');

                div.addEventListener('click', function (event) {
                    componentRef.pageSelection.emit({ selectedPage: (page.pageIndex + 1) });
                    componentRef.currentPageNo = page.pageIndex + 1;
                }, false);

                div.addEventListener('contextmenu', function (event) {
                    componentRef.contextMenu.emit({ 'mouseEvent': event, selectedPage: (page.pageIndex + 1) });
                    componentRef.currentPageNo = page.pageIndex + 1;
                }, false);

                div.setAttribute('class', 'page');
                viewer.appendChild(div);

                let renderContext;
                if (div.getAttribute('data-loaded')) {
                    /** Creating canvas */
                    const canvasWrapperDiv = document.createElement('div');
                    const canvas = document.createElement('canvas');

                    canvasWrapperDiv.appendChild(canvas);
                    canvasWrapperDiv.className = 'canvasWrapper';
                    componentRef.arrCanvasWrapper.push(canvasWrapperDiv);
                    div.appendChild(canvasWrapperDiv);

                    const context = canvas.getContext('2d');
                    canvas.height = scaledViewport.height;
                    canvas.width = scaledViewport.width;

                    renderContext = {
                        canvasContext: context,
                        viewport: scaledViewport
                    }
                    /** End of canvas creation */
                } else {
                    /** Creating canvas */
                    const canvasWrapperDiv = document.createElement('div');
                    const canvas = document.createElement('canvas');

                    const context = canvas.getContext('2d');
                    canvas.height = scaledViewport.height;
                    canvas.width = scaledViewport.width;

                    canvasWrapperDiv.appendChild(canvas);
                    canvasWrapperDiv.className = 'canvasWrapper';

                    componentRef.arrCanvasWrapper.push(canvasWrapperDiv);
                    /** End of canvas creation */
                    const loadingIconDiv = componentRef.createLoadingIconPage(scaledViewport)
                    div.appendChild(loadingIconDiv);

                    renderContext = {
                        canvasContext: context,
                        viewport: scaledViewport
                    };
                }

                // Render PDF page
                if (componentRef.textLayerMode) {
                    page.render(renderContext)
                        .then(function () {
                            // Get text-fragments
                            const text = page.getTextContent();
                            return text;
                        })
                        .then(function (textContent) {
                            if (div.getAttribute('data-loaded')) {
                                // Create div which will hold text-fragments
                                const textLayerDiv = document.createElement('div');

                                textLayerDiv.setAttribute('class', 'textLayer');
                                div.appendChild(textLayerDiv);

                                // Create new instance of TextLayerBuilder class
                                const textLayer = new PDFJSViewer.TextLayerBuilder({
                                    textLayerDiv: textLayerDiv,
                                    pageIndex: page.pageIndex,
                                    viewport: scaledViewport
                                });

                                textLayer.setTextContent(textContent);
                                textLayer.render();
                            } else {
                                // Create div which will hold text-fragments
                                const textLayerDiv = document.createElement('div');
                                textLayerDiv.setAttribute('class', 'textLayer');

                                // Create new instance of TextLayerBuilder class
                                const textLayer = new PDFJSViewer.TextLayerBuilder({
                                    textLayerDiv: textLayerDiv,
                                    pageIndex: page.pageIndex,
                                    viewport: scaledViewport
                                });

                                textLayer.setTextContent(textContent);
                                textLayer.render();
                                componentRef.arrTextLayer.push(textLayerDiv);
                            }
                        });
                } else {
                    page.render(renderContext);
                }
            });
        }
    }

    createLoadingIconPage(scaledViewport) {
        /** Creating blank loading page */
        const loadingIconDiv = document.createElement('div');
        const image = document.createElement('img');
        image.src = '/assets/images/loading-icon.gif'
        loadingIconDiv.appendChild(image);
        loadingIconDiv.className = 'loading';

        loadingIconDiv.setAttribute('style', 'height:' + scaledViewport.height + 'px; width:' + scaledViewport.width + 'px');
        /** End of blank loading page creation */
        return loadingIconDiv;
    }

    @HostListener('window:scroll', ['$event'])
    scrollHandler(event) {
        var viewerElem = event.target;
        var childElements = event.target.childNodes;
        var contentBoundry = viewerElem.offsetHeight / 2;
        var currentElement;

        for (let i = 0; i < childElements.length; ++i) {

            var offsetTop = childElements[i].offsetTop;
            var scrollTop = viewerElem.scrollTop;
            var netScroll = offsetTop - scrollTop;
            if (netScroll < contentBoundry) {
                this.currentPageNo = i + 1;
                currentElement = childElements[i];
                currentElement.setAttribute("data-loaded", "true");
                let canvasWraper = this.arrCanvasWrapper[i];
                currentElement.removeChild(currentElement.childNodes[0]);
                currentElement.appendChild(canvasWraper);

                //let textLayer = this.arrTextLayer[i];
                //currentElement.appendChild(textLayer);
            } else {
                var elements = document.getElementsByClassName('page');
                for (let j = 0; j < elements.length; j++) {
                    if (currentElement.id != elements[j].id) {
                        elements[j].removeAttribute("data-loaded");
                        const loadingIconDiv = this.createLoadingIconPage(this.viewportScale);
                        elements[j].removeChild(elements[j].childNodes[0]);
                        elements[j].appendChild(loadingIconDiv);
                    }
                }
            }
        }
    }
}

**Comment by Snuffleupagus** [comment]
Quoting from https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, **first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues**. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
The only thing I can think of is that you're not destroying pages correctly when they go out of view, so memory only increases as you scroll. The default viewer does take care of this, which may explain the difference since I don't see that in your code. However, it's not possible to tell for sure using code snippets alone, as indicated above. Closing as answered for now.
