### ISSUE TITLE
how can i get only sidebar , zoom  and page number 

### ISSUE THREAD

**Issue by vgsunil** [mozilla/pdf.js#10469]
i want to know if i can get only code related to the sidebar generation ,  page navigation , loading all pages at a time and zoom dropdown related specific code form default pdfviewer.js . because when i try to change code in pdfviewer i got stuck in error related to promise. also if i try to remove all somecontrols from the default viewer.html it gives me an error so can anyone hrlp me by giving me specific code that i require

**Comment by timvandermeij** [comment]
The viewer is mostly split into components, see https://github.com/mozilla/pdf.js/tree/master/web, so you should be able to adapt the default viewer to your needs by removing functionality from this. However, this is out of scope for the PDF.js project, so we cannot provide assistance with that.
