### ISSUE TITLE
Element.classList.toggle does not work in IE

### ISSUE THREAD

**Issue by JorgeSolFerreira** [mozilla/pdf.js#10460]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: IE (any version)
- Operating system and its version: Windows 8/10
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Execute document.getElementsByTagName('body')[0].classList.toggle('test') on the Internet Explorer console

What is the expected behavior? (add screenshot)
Should add or remove a class to an element.

What went wrong? (add screenshot)
Throws an "invalid calling object" error

![image](https://user-images.githubusercontent.com/11443206/51264361-3bcff880-19ae-11e9-9681-76a8b5d1aa05.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by coder-5943123** [comment]
Great this was fixed in PR #10462  

When will pdfjs-dist be released in a new version?

**Comment by timvandermeij** [comment]
Hopefully really soon; we already have an open ticket for releasing version 2.1.
