### ISSUE TITLE
Text font not showing

### ISSUE THREAD

**Issue by eezhal92** [mozilla/pdf.js#10479]
Configuration:
- Web browser and its version: Chrome 71.0
- Operating system and its version: macOS sierra
- PDF.js version: 2.0.943
- Is a browser extension: no

so this is how i will write it

Hello.
I'm using PDF.js (https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer) to build a PDF viewer in my webapp. The PDF is showing up fine, but the text font isn't showing and I'm stuck.

I'm guessing that it might be due to an incorect CMapsUrl? I'm using this URL https://unpkg.com/pdfjs-dist@2.0.943/cmaps

Here's a part of the code:

```
pdfJS.getDocument({
  url: 'www.mysite.com/my-file.pdf,
  cMapUrl: 'https://unpkg.com/pdfjs-dist@2.0.943/cmaps/',
  cMapPacked: true,
});
```

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
I don't know if it's possible for the `cMapUrl` to be an external URL. Try hosting the CMaps locally to see if that solves it. Closing because if the above.
