### ISSUE TITLE
Travis CI jobs trigger doesn't work anymore

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10472]
Until a few days ago, creating or updating a pull request triggered a new Travis CI job, however all of a sudden this stopped working.

@brendandahl @yurydelendik Could you check what happened? Perhaps an expired API key or something in GitHub's project settings?

*Update:* I checked https://travis-ci.org/mozilla/pdf.js and it shows the following message: "This is not an active repository. You don't have sufficient rights to enable this repo on Travis. Please contact the admin to enable it or to receive admin rights yourself.". It looks like it somehow got disabled.

**Comment by brendandahl** [comment]
Strange, not sure it was deactivated. I just re-activated it.
