### ISSUE TITLE
Mention the current support status, or lack thereof, of the SVG backend in the FAQ

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#10488]
The SVG rendering backend, as of right now, is missing a number of features when compared to the default Canvas backend, and it's also completely untested in the current PDF.js test-suite. Even though it's more than a year old, most of the points mentioned in https://github.com/mozilla/pdf.js/issues/9211#issuecomment-347851242 probably still applies.

Hence I'd suggest that it might be a good idea to mention these caveats (somewhere) in the https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions, to set user expectations and to avoid any surprises when the SVG backend is used.

**Comment by timvandermeij** [comment]
I think this is a good idea. I have added a section about this at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends.
