### ISSUE TITLE
No noticeable effects from renderTextLayer enhanceTextSelection option

### ISSUE THREAD

**Issue by g-golden** [mozilla/pdf.js#10493]
Attach (recommended) or Link to PDF file here: 
[SampleIndependentContractorAgreementFinal-Fall2014-1.pdf](https://github.com/mozilla/pdf.js/files/2794684/SampleIndependentContractorAgreementFinal-Fall2014-1.pdf)

Configuration:
- Web browser and its version: Firefox 64.0.2
- Operating system and its version: Windows 10
- PDF.js version: pdfjs-dist 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
```javascript
import React, { Component } from 'react';
import PDFJS from 'pdfjs-dist/webpack';
import 'pdfjs-dist/web/pdf_viewer.css';

export default class extends Component {
  componentDidMount() {
    const url = 'https://cors-anywhere.herokuapp.com/https://github.com/mozilla/pdf.js/files/2794684/SampleIndependentContractorAgreementFinal-Fall2014-1.pdf';
    const container = this.docContainer;

    const renderPage = page => {
      const scale = 1.33;
      const viewport = page.getViewport(scale);
      const pageDiv = document.createElement('div');

      pageDiv.setAttribute('id', `page-${page.pageIndex + 1}`);
      pageDiv.setAttribute('class', 'doc-page');

      pageDiv.setAttribute('style', 'position: relative');

      container.appendChild(pageDiv);

      const pdfCanvas = document.createElement('canvas');
      pdfCanvas.style.position = 'absolute';

      pageDiv.appendChild(pdfCanvas);

      const context = pdfCanvas.getContext('2d');

      pdfCanvas.height = viewport.height;
      pdfCanvas.width = viewport.width;

      const renderContext = {
        canvasContext: context,
        viewport,
      };

      page
        .render(renderContext)
        .then(() => page.getTextContent())
        .then(textContent => {
          const textLayerDiv = document.createElement('div');
          textLayerDiv.setAttribute('class', 'textLayer');
          textLayerDiv.style.zIndex = 2;

          pageDiv.appendChild(textLayerDiv);

          PDFJS.renderTextLayer({
            enhanceTextSelection: true,
            textContent,
            container: textLayerDiv,
            viewport,
            textDivs: [],
          });
        });
    };

    PDFJS.getDocument(url).then(pdf => {
      for (let i = 1; i <= pdf.numPages; i++) {
        pdf.getPage(i).then(renderPage);
      }
    });
  }

  render() {
    return (
      <div
        ref={div => {
          this.docContainer = div;
        }}
      />
    );
  }
}
```

What is the expected behavior?
Non-jumpy text selection

What went wrong?
Text selection jumps to the top of the page when in between rows of text

I've read the issues on textLayerMode but I don't think the default viewer will work with my customization needs. Is the enhanceTextSelection option of renderTextLayer supposed to reduce the jumpiness of text selection? I've tried enabling and disabling the option but I see no difference in behavior.

**Comment by Snuffleupagus** [comment]
>  Is the enhanceTextSelection option of renderTextLayer supposed to reduce the jumpiness of text selection? I've tried enabling and disabling the option but I see no difference in behavior.

Not on it's own, since there's nothing in your code-snippet that's actually calling https://github.com/mozilla/pdf.js/blob/e2701d5422a43ca1810e7ce6b3aa42758f50d781/src/display/text_layer.js#L607
It's probably helpful to look at how this is implemented in the viewer components, and probably even simpler to just use the viewer components directly (see [examples here](https://github.com/mozilla/pdf.js/tree/master/examples/components)), refer to https://github.com/mozilla/pdf.js/blob/e2701d5422a43ca1810e7ce6b3aa42758f50d781/web/text_layer_builder.js#L358-L424

Finally please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by g-golden** [comment]
Thank you
