### ISSUE TITLE
xpi of pdf.js with resizable sidebar

### ISSUE THREAD

**Issue by shiftyshady** [mozilla/pdf.js#10496]
Hello, 
I would like to update the pdf.js on an old version of firefox I keep for offline stuff and  would really appreciate to know how to create xpi files from the release zip files, or get a xpi version to test.

**Comment by timvandermeij** [comment]
The extension is removed because PDF.js is now embedded in Firefox by default. Therefore, the code to build XPI files is also gone. You can try to work with https://github.com/mozilla/pdf.js/pull/9566, but I don't really see why this would even be necessary given that it's in Firefox by default.

**Comment by shiftyshady** [comment]
So how could one update pdf.js without updating firefox?
I have done it modifying omni.ja, but doing that has plenty of issues, whereas using xpi's only require to disable addon compatibility checks and it works perfectly fine.

**Comment by timvandermeij** [comment]
You cannot do that (at least easily). It's really recommended to update Firefox for security reasons and because we don't support older versions anymore.
