### ISSUE TITLE
No supprot for Indian character sets

### ISSUE THREAD

**Issue by nitintomer** [mozilla/pdf.js#10495]
Hi,

PDF.js doesn't support rendering of Indian character sets - Hindi, bengali etc.

For such charcters, it shows boxes.

Regards

Nitin

**Comment by brendandahl** [comment]
Do you have a sample PDF that has issues?

**Comment by timvandermeij** [comment]
Closing until all requested information from the issue template is provided.

**Comment by nitintomer** [comment]
Attaching fi
[Bengali.pdf](https://github.com/mozilla/pdf.js/files/2812259/Bengali.pdf)
[Malayalam.pdf](https://github.com/mozilla/pdf.js/files/2812260/Malayalam.pdf)

les.

**Comment by THausherr** [comment]
Works for me when using https://mozilla.github.io/pdf.js/web/viewer.html with FF 65.0.
