### ISSUE TITLE
How to properly extract text color and formatting ?

### ISSUE THREAD

**Issue by Alexxkrehmen** [mozilla/pdf.js#10497]
Hi,

Until the API will be fully documented, would it be possible to explain to me how I could use this library to parse a pdf file and extract all the text in it, including its formatting and colors, please ?

I know this question has already been answered here : https://github.com/mozilla/pdf.js/issues/7895
But the answer is a bit "dry"... since getOperatorList isn't documented as well and returns a huge cryptic array...

Any detailed help on this would be appreciated ^_^

Thanks !

**Comment by timvandermeij** [comment]
The example from https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L44-L51 parses a PDF file and extracts all text in it using the public `getTextContent` API.

**Comment by Alexxkrehmen** [comment]
It extracts raw text... so without any formatting information... which is what I'm looking for.

**Comment by timvandermeij** [comment]
Did you try to look what else is in the `content` object? Refer to https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L45-L46 that states that there is more in there than just the raw text.

**Comment by timvandermeij** [comment]
More specifically, you can find https://github.com/mozilla/pdf.js/blob/103f4616accbd29755e6d150f0a7c2e7a6bc6546/src/display/api.js#L787-L815. It's documented.

**Comment by Alexxkrehmen** [comment]
Yup, I had a look at it, and TextStyle doesn't contains any information about text color, which is one of the main things I'm looking for :/

**Comment by n8jadams** [comment]
☝️ Any comment on this?

I'm also looking for a way to get text color from TextStyle.

**Comment by wvanrensburg** [comment]
@timvandermeij Why was this closed? Its not available in the api. Any word on getting this?

**Comment by lucas-ssparisi** [comment]
I'd also like to retrieve the text color. As of now, it seems that `TextItem` doesn't expose a color attribute. 
Are there any updates or plans to support this?
