### ISSUE TITLE
i just want say thank you for pdf.js

### ISSUE THREAD

**Issue by sapq** [mozilla/pdf.js#10514]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 00
- Operating system and its version: 00
- PDF.js version: 00
- Is a browser extension:00

Steps to reproduce the problem:
1. i just want say thank you  for  pdf.js before i dont have jop and house and wife and a car
but when i use  the pdf,js i have big site on my country
I do not know if there's anything I can do for pdf.js
Just will say thanks to developers on pdf,js 
now i have  wife  and jop  and house  and car 
I have two staff work with me 
thank you  big thanks you save me ^^

and slam alikom
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Thank you for letting us know, and good to hear that PDF.js is working well for you!
