### ISSUE TITLE
Rendering with example does not work, no errors

### ISSUE THREAD

**Issue by aurelijusrozenas** [mozilla/pdf.js#10511]
First example from https://mozilla.github.io/pdf.js/examples/ does work with links to 2.0.943 version cdn.

Step to reproduce:
1. Open first example, and check that it does work, e.g. [default jsfiddle](https://jsfiddle.net/s2wyg7mu/). Code is not changed in any way. Result: https://prnt.sc/merr2m
2. Open [updated jsfiddle](https://jsfiddle.net/9mnqa3rh/). There is JS no errors, but document is not rendered - just empty canvas. The only thing changed is link to pdf.js and worker.js to official cdn to 2.0.943 version. Result:https://prnt.sc/merrkc

Note that this repository has latest release 2.0.943 but script included in example [http://mozilla.github.io/pdf.js/build/pdf.js](http://mozilla.github.io/pdf.js/build/pdf.js) is 2.1.233. Where is this version even coming from?

I am new to pdf.js and spent ages trying to understand why rendering does not work in my app through webpack, when the problem was not event related with webpack. I am missing something important and/or am I just stupid? :/

**Comment by Snuffleupagus** [comment]
Duplicate of #10418.

**Comment by aurelijusrozenas** [comment]
Holy moly, @Snuffleupagus, that was fast and accurate! Thanks.
For anyone coming here:
Example is not in sync with 2.0.943 version, `var viewport = page.getViewport({scale: scale});` must be replaced with `var viewport = page.getViewport(scale);`.
