### ISSUE TITLE
Recreate thumbnails

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10513]
How can you recreate the thumbnails?

I actually would like to get hold of the canvas because i wish to do something with it.

Would appreciate a sample code. 

And this is without modifying viewer.js

**Comment by Snuffleupagus** [comment]
> How can you recreate the thumbnails?
>
> I actually would like to get hold of the canvas because i wish to do something with it.

It's simply impossible for anyone to *easily* understand what you're asking about here, since there's not enough context in the question!

When opening an issue, you *must* provide enough details such that it's easy to understand what's being reported/asked; please make sure to fill out [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and that you read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
If you look at the default viewer at https://mozilla.github.io/pdf.js/web/viewer.html, each `canvas` element has an ID that you can use to fetch it. Otherwise, I agree with the comment above, so closing as answered.

**Comment by chitgoks** [comment]
hi @timvandermeij  , @Snuffleupagus 
this may be some few months after i asked about this but i have a tiny question.

does pdf.js have some way to redraw the thumbnail page by page or some workaround possibly?

I figured PDFViewerApplication.pdfSidebar._updateThumbnailViewer() would be it, but i think it wont work because the rendering has been done. im not sure which variables to reset. Even if i get to make this work, it redraws all the thumbnails.

i am interested to have a thumbnail recreated for just a specific page. is this possible?

**Comment by chitgoks** [comment]
@timvandermeij  @Snuffleupagus  id like to ask a related question. because i have managed to redraw the thumbnail on a specific page. but this seems to only work if all thumbnails of the pages are generated.

since by default only the first few thumbnails are generated based on the page first scrolled to, when i call this set of code, sometimes it works, sometimes the image is not appended.

// Recreating page 1
$('div.thumbnail[data-page-number=1] div img').remove(); // remove page 1 thumbnail image
PDFViewerApplication.pdfThumbnailViewer._thumbnails[0].renderingState = 0;
PDFViewerApplication.pdfSidebar._updateThumbnailViewer();

am i missing something here? please advise.
