### ISSUE TITLE
Issues with selecting text spanning multiple pages

### ISSUE THREAD

**Issue by dev-grant** [mozilla/pdf.js#10516]
Problem occurs on all pdf files and viewer setups I've tested, including the demo: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Firefox 65.0
- Operating system and its version: Windows 10
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Start selecting text on one page
2. Keep selecting down to another page

What went wrong? (add screenshot)
1. Text selection becomes offset to the cursor, making it impossible to select the end of a line of text (happens on firefox, but not IE or chrome): 

![pdfjs_li](https://user-images.githubusercontent.com/20716940/52173852-f7887a80-2759-11e9-946b-7d94352e8553.jpg)

2. The enhanced textLayerMode (value 2) of the pdf viewer does not work on the subsequently selected pages (the text div expansion does not trigger). Text selection jumps to the top of the page when the cursor is in between lines of text. I noticed the on click text div transformations that occur with textLayerMode 2 don't occur on these subsequent pages, even though they do occur on the starting page's selection.

3. When calling getSelection().getRangeAt(0).getClientRects() - the only rect counted as selected on subsequent pages is the entire page's div rect - as visualized by this picture, where the selection rects of the selection's starting page appear properly, but only 1 giant selection rect appears for the next page: 
![2019-02-03 02_27_36-react app](https://user-images.githubusercontent.com/20716940/52173984-db85d880-275b-11e9-8f09-8e30cbcee024.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Issue 1 can be seen here: https://mozilla.github.io/pdf.js/web/viewer.html. Issue 2 and 3 require a differently set up viewer, which I can put together an online viewer for if desired.

**Comment by burtonator** [comment]
This impacts our users too... https://getpolarized.io/

**Comment by aehlke** [comment]
ever find a workaround?

**Comment by limonovthesecond2** [comment]
The 1 issue no longer exists with PR#[17923](https://github.com/mozilla/pdf.js/pull/17923)
The 2 issue is also seems to be fixed with the PR above as we can't accidentally select the empty space between the lines
The 3 issue seems outdated

**Comment by timvandermeij** [comment]
Closing since this should be fixed indeed; thanks!
