### ISSUE TITLE
Invalid PDF structure 

### ISSUE THREAD

**Issue by robinH** [mozilla/pdf.js#10526]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: JFX 8 Webview, Firefox
- Operating system and its version: W10
- PDF.js version: 2.0.943
- Is a browser extension:no
1. Simple test pdf works in my program fine. Real ones fail
2. If I drop any of the PDFs into FF 65.0 and they render fine. It is my version or my setup which is the problem.
3. In my code, Java reads the file, encodes it, JS decodes it. First 100  and last 100 bytes of initial and decoded files are the same. Byte count is the same. Manually parsing the last 50 bytes, I see stuff like startxref, %%EOF and trailerBytes. The last 100 bytes are shown below. If the byte count is right, and the head and tails are the same, then the middle is probably ok too.
Aside(FWIW: In the js engine that does the work here, js.string.split() will only split up to 65536 items, then it folds.Looks ok but is wrong!)
4. console.log doesn't work in pdf.worker.js, so I have modified the exception 
`      throw new _util.InvalidPDFException('Invalid PDF structure at ' + position + ' msg:' + rbhmsg);`
making it very long, (file size is 290184) so I get
` InvalidPDFException: Invalid PDF structure at 290188 
msg:XRef_indexObjects... ,% seen at position=0 ,after % capture position=10 ,after readToken position=10 token=4 0 obj ,startPos=10 ,endobjRegExp.test saw true - break! ,after % capture position=36 ,after readToken position=36 token=5 0 obj ,startPos=36 ,endobjRegExp.test saw true - break! ,after % capture position=59 ,after readToken position=59 token=8 0 obj ,startPos=59 ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null
 ... about 20 more like this
,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,endobjRegExp.test saw false ,objToken=null ,
endobjRegExp.test saw false ,
objToken=null
Looking for dictionary?... ,
trailers.length =0 
     [at 87] file: viewer.html`
For a bit more info, here is the tail of the pdf.  It kind of looks normal having the right kind of things.
`decodedString tail: 48, 48, 48, 48, 48, 32, 110, 13, 10, 48, 48, 48, 48, 50, 56, 57, 50, 55, 51, 32, 48, 48, 48, 48, 48, 32, 110, 13, 10, 116, 114, 97, 105, 108, 101, 114, 10, 60, 60, 10, 47, 73, 110, 102, 111, 32, 51, 48, 32, 48, 32, 82, 10, 47, 82, 111, 111, 116, 32, 49, 32, 48, 32, 82, 10, 47, 83, 105, 122, 101, 32, 51, 49, 10, 62, 62, 10, 115, 116, 97, 114, 116, 120, 114, 101, 102, 10, 50, 56, 57, 52, 56, 50, 10, 37, 37, 69, 79, 70, 10, `
I then came across Merge pull request #10492 and added this to pdf.worker.js
This did not make any difference. But my problem seems in the same area?
Because it is JFX WebView, I have no proper debugger, so I just edited the exception.
**Question**: How can I make messages like
`(0, _util.warn)('XRef.parse - Invalid "Root" reference: "' + ex + '".');`
come out on the console? To make debugging a bit easier. Or make console.log work here?
It seems to me that this is some parsing issue where ` indexObjects: function XRef_indexObjects()` is not finding the stuff it needs to find, although manually parsing it is clearly there.
Is  FF 65.0 using identical code to 2.0.943?

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
The latest version of the PDF.js default viewer can always be found at https://mozilla.github.io/pdf.js/web/viewer.html (you can e.g. drag-and-drop a file or use the "Open File"-button to load a local file).

> Is FF 65.0 using identical code to 2.0.943?

It should be a newer version; the easiest way to check is to open a PDF file in Firefox and then check the web console, since the version number will be printed there.

For every thing else, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by robinH** [comment]
I am creating a desktop application which is mostly Java. It could well be that the problem is in Java code not JS. There is no server. I use Java to avoid CORS issues. I am not using viewer.js. I just render to a canvas as per Hello world Base64 example.

I started with the Hello world Base64 example from your web site. But your examples say a server is required which I do not use. I am using csv encoding rather than base64 and so I have no charset issues. It is slow but sure. So I need not use URLs and face CORS restrictions. I ensure scripts are loaded properly before being used.

I am not able to single-step through JS, so my best way to debug is to put some logging messages to localise the problem. Firebug does not step. My Java listens to console and logs messages.

For pdf.js I can just add console.log.  But in pdf.worker.js, that does not work, I see in the code there lines like `(0, _util.warn)('reported HTTP length is different from actual');`. I have tried adding more such lines, but I don't see anything show on the log.  

What do I have to do to enable some kind of debug logging or make _util.warn work? 

My problem would seem to be that the pdf indexes are not getting parsed in `function XRef_indexObjects()`, `var trailerBytes` and `startxrefBytes` are not getting matched although _I can see the bytes are present in the pdf dump. And it parses to the last position.

For now, I think I should debug this myself, or at least localise the issue, but it is hard when my only debug aid is the InvalidPDFException thrown.

So again, **is there some way to get  _util.warn messages working in pdf.worker.j**s (or any kind og logging) ?

**Comment by Snuffleupagus** [comment]
Unfortunately there's still no information provided which makes this a valid issue for the PDF.js project!

When asking for help with a *custom implementation*, as already mentioned in https://github.com/mozilla/pdf.js/issues/10526#issuecomment-461263693, you need to provide a runnable example.

> I am creating a desktop application which is mostly Java.

Furthermore, since PDF.js is a web-app the chance that anyone here will be able (or have time) to help with a desktop application probably isn't too great since it's not clear that the PDF.js library is at fault.

> For now, I think I should debug this myself, or at least localise the issue, but it is hard when my only debug aid is the InvalidPDFException thrown.

If you're asking for help regarding debugging Web Worker issues in a Java desktop application, then I'm afraid that is definitely out of scoop for the PDF.js issue tracker.

> So again, **is there some way to get _util.warn messages working in pdf.worker.j**s (or any kind og logging) ?

All reasonably modern browsers will forward any logging messages to the regular web console, so if that doesn't work that again points to a problem in your Java framework. (For debugging purposes, you could try loading the `pdf.worker.js` file with a script tag on the main thread, which may help with logging.)

**Comment by robinH** [comment]
> All reasonably modern browsers will forward any logging messages to the regular web console, so if that doesn't work that again points to a problem in your Java framework. (For debugging purposes, you could try loading the `pdf.worker.js` file with a script tag on the main thread, which may help with logging.)

Thank you for that information. I will try your suggestion.

It occurs to me that your Hello World Base64 on which I based my code uses the simplest of in-line text string as its pdf test source. My code deals with that ok and also another pdf I found on the internet, simple.pdf. It just has text in Helvetica font. I get problems when I encode/decode real world pdf's not made by Adobe. Instead they are from a widely used Fujitsu Scanner (which just wraps jpg's) and Statements from my (major) bank. 

I will try some minimal modifications to your Hello World base64 to process more substantial pdf's.  And perhaps try pdf's from a few other sources. That would make an easily portable test case.

But first I will try your suggestion above and try to get logging working for pdf.worker.js and see if I can find where parsing skips what it should not, which seems to me to be the problem.

Thanks again.

**Comment by Snuffleupagus** [comment]
> ... base64

Using `base64` really isn't advisable, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, since it first of all uses a lot of memory and second of all some browsers/environments are known to *truncate* long base64 strings.
Please try converting the raw PDF data to a `Uint8Array` instead, and pass that to `getDocument`; see also https://github.com/mozilla/pdf.js/blob/7d24fc34f9fb4045d49025512e5bb6989709eb13/examples/learning/helloworld64.html#L40-L42

**Comment by timvandermeij** [comment]
Closing as answered since nothing seems to indicate a problem in the PDF.js library itself.
