### ISSUE TITLE
Is there an existing function to have the thumbnail page re-rendered again?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10531]
If there is, what is it?

From what I can tell, the pagerender event will generate the pdf page when it is scrolled to. But i noticed in the thumbnail list in the sidebar,  they are pre-generated. 

is there a way to call some function to have the thumbnail be generated again?

**Comment by timvandermeij** [comment]
The update method (https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_view.js#L186) is used to update the thumbnails when rotation changes, so you might be able to call that without a rotation change to re-render the thumbnails. If that doesn't work, I think you'll need to make new `PDFThumbnailView` instances if you want to re-render.

**Comment by chitgoks** [comment]
hi tim

you could be right. doing PDFViewerApplication.pdfThumbnailViewer._thumbnails[0].update() re-renders it. 

however, i added some drawings to canvas#page3 for example in page 3 and i would like to re-render the thumbnail  based on the page 3's canvas.

im wondering if that is possible

**Comment by timvandermeij** [comment]
I don't think it's possible without creating a new thumbnail view instance.

**Comment by Snuffleupagus** [comment]
> however, i added some drawings to canvas#page3 for example in page 3 and i would like to re-render the thumbnail based on the page 3's canvas.

Just look at how this method is used throughout the viewer: https://github.com/mozilla/pdf.js/blob/14c012b6506ebed671da613bf588998bb11f7edf/web/pdf_thumbnail_view.js#L344

**Comment by chitgoks** [comment]
im currently having problem with this TempImageFactory

there does not seem to be a way to access this class.

i decided to copy the setImage() into another js file and modify from there.

**Comment by chitgoks** [comment]
i copied the contents of setImage and modified some parts like removing this

if (this.renderingState !== _pdf_rendering_queue.RenderingStates.INITIAL) ...

i got it to work: re-rendering the thumbnail page again.

however, i noticed that the original has darker color. mine looks lighter.  thoughts?
