### ISSUE TITLE
issue while trying to integrate pdf.js with our portal

### ISSUE THREAD

**Issue by VenkatapathiAmulya** [mozilla/pdf.js#10546]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
  Google Chrome,Version 72.0.3626.96 (Official Build) (64-bit) in windows
- Operating system and its version:
 deployed the pdf.js on  Ubuntu 16.04.3 LTS
- PDF.js version:latest
- Is a browser extension: yes.Wanted to you pdf.js plugin and open pdf files on windows browser using externalport(10068).10068 port is used for accessing the services from different machines.

What is the expected behavior? (add screenshot)
curl http://xxx.com:10068/
the above command should give some data.
curl http://localhost:8888
the above command also should give some data.

What went wrong? (add screenshot)
curl http://localhost:8888
got some data when tried with localhost

curl http://xxx.com:10068/
But getting some error as follows when tried to access the pdf.js using external port 10068
"curl: (7) Failed to connect to http://xxx.com port 10068: Connection refused"

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing until the requested information is provided.
