### ISSUE TITLE
Import pdf.js with typescript

### ISSUE THREAD

**Issue by cesco69** [mozilla/pdf.js#10547]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: **NODE 10**
- Operating system and its version: **LINUX/DOCKER**
- PDF.js version: **pdfjs-dist 2.2.2**
- Is a browser extension: **NO**

Steps to reproduce the problem:
1. Install **pdfjs-dist** with: `npm install pdfjs-dist --save`
2. Install **@types/pdfjs-dist** with: `npm install @types/pdfjs-dist --save-dev`
3. Import **pdfjs-dist** in a `*.ts` file: `import { PDFJS } from 'pdfjs-dist'; `
4. Use `getDocument` from `PDFJS `: `PDFJS.getDocument('my.pdf')`
5. execute the code and see the error: _PDFJS is not defined_

What is the expected behavior? 
PDFJS works on typescript

What went wrong? 
PDFJS can't export correctly the lib on typescript

Link to a viewer:
not disponible

Work around:
Import PDFJS  in this way
```
import { PDFJSStatic } from 'pdfjs-dist'; 
const PDFJS: PDFJSStatic = require('pdfjs-dist');
```

**Comment by Snuffleupagus** [comment]
>     2\. Install **@types/pdfjs-dist** with: `npm install @types/pdfjs-dist --save-dev`

Most likely, those types haven't been updated to handle PDF.js versions above `2.0`.
However please note that that's a different library, which is *not* maintained here, hence this issue is unfortunately out-of-scope/invalid here.

**Comment by MickL** [comment]
@Snuffleupagus @timvandermeij Could you please reopen? `@types/pdfjs-dist` is totally off for version >= 2 and the [Github repository](https://github.com/mozilla/pdfjs-dist) does not have any issue tracker.

**Comment by Snuffleupagus** [comment]
> Install **@types/pdfjs-dist** with: `npm install @types/pdfjs-dist --save-dev`

As mentioned in https://github.com/mozilla/pdf.js/issues/10547#issuecomment-462675381, those are *not* in any way affiliated with Mozilla or the PDF.js project. 

> `@types/pdfjs-dist`

Again this is not related to https://github.com/mozilla/pdfjs-dist, but most likely you're actually referring to these ones: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pdfjs-dist

**Comment by MickL** [comment]
`@types/pdfjs-dist` should be maintained by `mozilla/pdfjs-dist` and/or `mozilla/pdf.js` contributors. 

Only this contributors know the code and the functions and can write the required interfaces.

**Comment by timvandermeij** [comment]
There are already open issues and even PRs for this, but so far the real demand for this is low and the PRs have not really been updated. If you think this is in fact important, please consider updating the existing PRs so they can be brought in a mergeable state.

**Comment by Bluejanis** [comment]
Does pdfjs provide it's own Typescript types somewhere else?

**Comment by blasco** [comment]
why is this close? Where are the types provided and how can we include the library into a typescript project? Thank you

**Comment by timvandermeij** [comment]
Duplicate of #7909 and that was fixed just yesterday.

**Comment by nismojkee** [comment]
@timvandermeij not duplicated. #7909 about other troubles. But here asked about instructions to include library into a typescript project.
