### ISSUE TITLE
Any alternative to define/load Cmap URL

### ISSUE THREAD

**Issue by nbalaji27** [mozilla/pdf.js#10551]
For example:
I have the assets domain as abc.com and my domain is xyz.com

While I specify the abc.com URL to cmap URL, It throws CORS origin error. while I saw the code, there we are not including `withCredentials` true attribute to the xhr. 

I have 2 ways which I know to achieve:
1. abc.com should set cors headers and in pdf.js code, should include withCredentials:true
2. I should load Cmap URLs from my Application server.

Here, 
1. I can't able to set the CORS related headers (Access-control-origin,etc..) in abc.com domain as its not under my control
2. Not possible to load

Is there any alternative way to achieve it ?

`Reference of the error:`
![screen shot 2019 02 14 at 11 12 34](https://user-images.githubusercontent.com/7175074/52765566-6c0cc480-304a-11e9-8f24-2707cc5f80f7.png)

PDF JS version:- 1.10.88

**Comment by Snuffleupagus** [comment]
If you have special requirements for loading the CMap files, you should implement a *custom* `CMapReaderFactory` which you then pass to `getDocument`.

**Comment by balajinunna** [comment]
@timvandermeij Can you please give me a sample example on how to implement the custom reader factory ?

**Comment by timvandermeij** [comment]
You can pass it to `getDocument`: https://github.com/mozilla/pdf.js/blob/81f5835cd7024827e0671ccd66525df98fb15703/src/display/api.js#L167

Here is a sample: https://github.com/mozilla/pdf.js/blob/ff74a66672c2980aa3dc2dd1b6f1407026b831de/test/unit/test_utils.js#L96

**Comment by balajinunna** [comment]
Thank you @timvandermeij for the details. Whereas in the given solution, they have used fs node package to read the content. However, am not using `fs` related node package. Can you suggest me any workaround to fix it ?

Thanks in advance.!

**Comment by balajinunna** [comment]
Hi @timvandermeij a

> Thank you @timvandermeij for the details. Whereas in the given solution, they have used fs node package to read the content. However, am not using `fs` related node package. Can you suggest me any workaround to fix it ?
> 
> Thanks in advance.!

Any help ?

**Comment by Snuffleupagus** [comment]
Did you actually try searching through the code-base for `CMapReaderFactory`, which should turn up https://github.com/mozilla/pdf.js/blob/652059056c8353298e8ca2dfd2fd658c3881031a/src/display/display_utils.js#L63-L115
