### ISSUE TITLE
Hello, I now have multiple PDF files how to merge them into a PDF file Preview？

### ISSUE THREAD

**Issue by lliiuu** [mozilla/pdf.js#10552]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
Background converts an office file into several PDF files and passes them to the front end. Now need to preview under a PDF file. Can pdf. JS be implemented?
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Background converts an office file into several PDF files and passes them to the front end. Now need to preview under a PDF file. Can pdf. JS be implemented?

It's virtually impossible to understand what's actually being asked here!
My best guess is that you're asking if the PDF.js library can be used to edit PDF files in various ways, in which case the answer is *no*.
