### ISSUE TITLE
pdf.js demo not working in chrome browser

### ISSUE THREAD

**Issue by carylewis** [mozilla/pdf.js#10559]
Attach (recommended) or Link to PDF file here:

The pdf.js demo is not working in Chrome anymore

https://mozilla.github.io/pdf.js/web/viewer.html

It does not render the PDF, instead the screen flashes some black rectangles.

Configuration:
- Google Chrome is up to date
Version 73.0.3683.39 (Official Build) beta (64-bit)

- Operating system and its version:

mac os High Sierra

- PDF.js version: latest
- Is a browser extension: no
Steps to reproduce the problem:
1. visiting the https://mozilla.github.io/pdf.js/web/viewer.html
manifests the problem.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Same site works fine in Safari and Firefox on the same machine.

Chrome used to work up until later 2018.

**Comment by Snuffleupagus** [comment]
> Configuration:
> 
>     * Google Chrome is up to date
>       Version 73.0.3683.39 (Official Build) beta (64-bit)

WFM, when using the exact same version in Windows 7.

> It does not render the PDF, instead the screen flashes some black rectangles.
>
> Same site works fine in Safari and Firefox on the same machine.

That clearly points to a bug in the browser *itself*, perhaps specific to the MacOS version of Google Chrome, rather than in the PDF.js library; hence this needs to be reported to the Google Chrome developers instead.

**Comment by carylewis** [comment]
Okay, that's a fair comment, but nonetheless, PDF.js is not working on a major operating system, using a major web browser. Are there any regression tests being performed that can detect this, at least warn users.

I would like to also be able if possible, pinpoint, where the browser's implementation of javascript causes PDF.js to fail. Given the reports of PDF.js failing with flashing rectangles, when the demo page loads - where does that suggest where in the code the problem might be.

Also note, that other PDF.js samples that I have tried, also do not work.

**Comment by timvandermeij** [comment]
You could check if something is reported in the web console. This may provide a hint about what exactly is going wrong.

**Comment by Snuffleupagus** [comment]
> Are there any regression tests being performed that can detect this, at least warn users.

Tests are run before patches are landed, in both Chrome *and* Firefox, but only on Linux and Windows; see also https://github.com/mozilla/pdf.js/wiki/Bots

> I would like to also be able if possible, pinpoint, where the browser's implementation of javascript causes PDF.js to fail.

If I were to guess, this probably isn't a JavaScript bug at all but rather a `<canvas>` one.

**Comment by carylewis** [comment]
> You could check if something is reported in the web console. This may provide a hint about what exactly is going wrong.

No errors in the console logs:

```
[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"password" class=​"toolbarField">​
onloadwff.js:71 [Violation] 'setTimeout' handler took 64ms
favicon.ico:1 GET https://mozilla.github.io/favicon.ico 404
app.js:1084 PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.2.15)
ui_utils.js:165 [Violation] 'requestAnimationFrame' handler took 74ms
[Violation] Forced reflow while executing JavaScript took 74ms
```

Performing an "empty cache and hard reload" did not resolve the issue.

I will try a chromium release.

**Comment by carylewis** [comment]
The pdf.js demo works fine in Chromium:

Version 74.0.3710.0 (Developer Build) (64-bit)

Presumably when a new version of chrome is released, pdf.js  will start working again.

Thanks everyone.

**Comment by cmh1996** [comment]
> The pdf.js demo works fine in Chromium:
> 
> Version 74.0.3710.0 (Developer Build) (64-bit)
> 
> Presumably when a new version of chrome is released, pdf.js will start working again.
> 
> Thanks everyone.

when i put the pdf.js demo in the iframe, and it cannot scroll in this browser. are you?

**Comment by DarDevDuck** [comment]
It breaks again in Version 79 onwards for Android devices.

**Comment by nflorentin** [comment]
Same problem here since Chrome version 78 release on Mac OS X...
