### ISSUE TITLE
希望可以加入关灯看pdf和反色（黑底白字）效果

### ISSUE THREAD

**Issue by SAKURALFJ** [mozilla/pdf.js#10563]
大多数打开网页pdf是阅读学术论文的情况，希望可以加入关灯看pdf和反色（黑底白字）效果，达到护眼的效果。

**Comment by timvandermeij** [comment]
We can't help if the text is not in English.

**Comment by DemonCloud** [comment]
@SAKURALFJ please say English

**Comment by SAKURALFJ** [comment]
Mostly opening web PDF is the case of reading academic papers, I hope to add off the anti-color (Black background and white characters) effect, to achieve eye protection effect.

**Comment by timvandermeij** [comment]
Then it's a duplicate of #2071.
