### ISSUE TITLE
"ほ" is displayed like "は"

### ISSUE THREAD

**Issue by mitsufuji** [mozilla/pdf.js#10568]
Attach (recommended) or Link to PDF file here:

[sample01.pdf](https://github.com/mozilla/pdf.js/files/2884257/sample01.pdf)

[sample02.pdf](https://github.com/mozilla/pdf.js/files/2884258/sample02.pdf)

Configuration:
- Web browser and its version:
FireFox 65.0.1 64bit
- Operating system and its version:
Windows 10 ver 1803
- PDF.js version:
2.1.97
- Is a browser extension:
No

Steps to reproduce the problem:
1. Open sample1.pdf or sample2.pdf by FireFox.

What is the expected behavior? (add screenshot)

"ほ" want to be displayed as the ruby of "保" in sample1.pdf.
"ほう" want to be displayed as the ruby of "報" in sample2.pdf.

What went wrong? (add screenshot)

"は" is displayed as the ruby of "保" in sample1.pdf.
"はう" is displayed as the ruby of "報" in sample2.pdf.

![sample1](https://user-images.githubusercontent.com/47815682/53086691-ef498100-3548-11e9-8b8c-ed9e9476f945.png)

![sample2](https://user-images.githubusercontent.com/47815682/53086712-f8d2e900-3548-11e9-8b6b-4c83aec20015.png)

The images displayed by Edge (17.17134) on the left and FireFox (65.0.1) on the right.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by mitsufuji** [comment]
"ぼ" and "ぽ" are correctly displayed.

**Comment by Snuffleupagus** [comment]
This is a Type3 font issue which looks *very* similar to [bug 1245391](https://bugzilla.mozilla.org/show_bug.cgi?id=1245391), please note https://bugzilla.mozilla.org/show_bug.cgi?id=1245391#c6 in particular.

**Comment by Snuffleupagus** [comment]
This *may* be a regression from PR #3354, @fkaelberer would you be able to take a look?

**Comment by mitsufuji** [comment]
@Snuffleupagus 
Thanks a lot, for your information!

I modified PDF.js used in our project to set false to COMPILE_TYPE3_GLYPHS,
then "ほ" is now displayed as "ほ".

We are going to check a lot of PDF files from now on to see if other characters have not changed.

Thanks again.
