### ISSUE TITLE
table borders 

### ISSUE THREAD

**Issue by ogoletti** [mozilla/pdf.js#10566]
[ffpdfjs_bug_tablelines.pdf](https://github.com/mozilla/pdf.js/files/2875821/ffpdfjs_bug_tablelines.pdf)

Configuration:
- Web browser and its version: Firefox Quantum 65.0 (64 bits)
- Operating system and its version: macOS Mojave 10.14.3
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1. open attached pdf in firefox (drag and drop in new tab)
2. the rendering of the borders in the table changes with the level of zoom

What is the expected behavior? (add screenshot)
expected behavior (from preview/or google chrome)
<img width="1112" alt="capture d ecran 2019-02-18 a 14 47 55" src="https://user-images.githubusercontent.com/22364279/52955129-3a6a6500-338c-11e9-9dcb-769f8a8ae93b.png">
 

What went wrong? (add screenshot)
![screenshot_2019-02-18 ffpdfjs_bug_tablelines pdf](https://user-images.githubusercontent.com/22364279/52955197-5d951480-338c-11e9-8be6-565960b6da2e.png)

This pdf was modified for anonymisation reasons. 
But you can find this in the metadata of the original file : 
```
File Permissions                : rw-r--r--
File Type                       : PDF
File Type Extension             : pdf
MIME Type                       : application/pdf
PDF Version                     : 1.6
Linearized                      : No
Encryption                      : Standard V4.4 (128-bit)
User Access                     : (none)
Creator                         : Excel
Producer                        : Mac OS X 10.12.6 Quartz PDFContext
XMP Toolkit                     : Adobe XMP Core 5.4-c006 80.159825, 2016/09/16-03:31:08
Format                          : application/pdf
Creator Tool                    : Excel```

**Comment by layus** [comment]
I can reproduce this issue both with my browser.

```
Name 	    Firefox
Version 	62.0.3
Build ID 	20181010001701
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
OS 	        Linux 4.14.98

var pdfjsVersion = '2.0.625';
var pdfjsBuild = 'e8b50883';
```

and with master at https://github.com/mozilla/pdf.js/commit/ece6a31a442d8d2489817579dfc57ed371135d3a (on the same browser obviously).

**Comment by Snuffleupagus** [comment]
This looks like another case where PR #6606 might help.

**Comment by layus** [comment]
@Snuffleupagus well, it may be linked, but this issue looks different than #6606 because lines get wider as you zoom out on the page. Ratios are not preserved when zooming in and out.
