### ISSUE TITLE
Doesn't open PDFs under the domain of iopscience.iop.org

### ISSUE THREAD

**Issue by ballII** [mozilla/pdf.js#10562]
Attach (recommended) or Link to PDF file here:
https://iopscience.iop.org/article/10.1088/2515-7639/aaf263/pdf

Configuration:
- Web browser and its version: Google Chrome, Version 72.0.3626.109 (Official Build) (64-bit)
- Operating system and its version: Mac OS 10.10.5
- PDF.js version: 
- Is a browser extension: PDF Viewer ( https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm )

What went wrong?
With PDF Viewer installed, PDFs under https://iopscience.iop.org/ are still opened by Chrome's built-in PDF reader, not by the extension PDF Viewer. (Not sure if it's a problem of the extension or that of PDF.js itself.)

**Comment by timvandermeij** [comment]
@Rob--W Do you have any idea what may cause this in Chrome?

**Comment by aspiers** [comment]
The above link opens fine for me in Chrome 83.0.4103.116 (Official Build) (64-bit).

**Comment by Rob--W** [comment]
This works for me.

> an extension was hijacking the built-in PDF viewer.

If you did install a PDF Viewer based on this project, then that's exactly what I would expect.

**Comment by aspiers** [comment]
[**@Rob--W**](https://github.com/Rob--W) commented on [September 2, 2020 6:25 PM](https://github.com/mozilla/pdf.js/issues/10562#issuecomment-685884185 "2020-09-02T17:25:22Z - Replied by Github Reply Comments"):
> If you did install a PDF Viewer based on this project, then that's exactly what I would expect.

Yeah, sorry - my thinking on this was totally confused!
