### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/pdf.js#10561]
FYI: The following changes were made to this repository's wiki:

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/pdf.js/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by timvandermeij** [comment]
Thank you for doing this!
