### ISSUE TITLE
Can't get content without Metadata to calculate checksum

### ISSUE THREAD

**Issue by vv7v7** [mozilla/pdf.js#10569]
Dear Developers,

Is it possible to get content of the whole PDF file without metadata(i.e. data of creation, modification date etc.) using PDF.JS?

Thank you very much,
Best regards

**Comment by Snuffleupagus** [comment]
> Is it possible to get content of the whole PDF file without metadata(i.e. data of creation, modification date etc.) using PDF.JS?

No, and given the lack of any details it's *very* difficult to know what's *actually* being asked here.

**Comment by vv7v7** [comment]
> 
> 
> > Is it possible to get content of the whole PDF file without metadata(i.e. data of creation, modification date etc.) using PDF.JS?
> 
> No, and given the lack of any details it's _very_ difficult to know what's _actually_ being asked here.

The question is: Is it possible to get the whole document, but omit metadata? This library has method **getMetadata()**, but is there any possible way to get a method called **getContentWithoutMetadata()** or **removeMetadata()**?

**Comment by Snuffleupagus** [comment]
The answer is still no, since what you're asking would require *editing* the PDF file which is clearly mentioned in the README as out of scope for the PDF.js project; see https://github.com/mozilla/pdf.js#pdfjs-

**Comment by vv7v7** [comment]
> 
> 
> The answer is still no, since what you're asking would require _editing_ the PDF file which is clearly mentioned in the README as out of scope for the PDF.js project; see https://github.com/mozilla/pdf.js#pdfjs-

This is not to edit a PDF file, but object/instance. I mean, the logic is to read everything from data, but metadata and return these bytes.

**Comment by Snuffleupagus** [comment]
Given how PDF files are actually structured, refer to the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf), there's *generally* no good way to simply "ignore" a arbitrary parts of the PDF file in the way you suggest. The only solution would be to edit the original file to remove all traces of the Info/Metadata dictionaries, and their entries in the XRef table.

**Comment by timvandermeij** [comment]
You could implement that the metadata cannot be fetched in e.g., the viewer, but it doesn't mean that it's not parsed. You could remove the parsing too, but the data itself will still be in the stream since PDF.js does not strip or mask any data.

**Comment by vv7v7** [comment]
> 
> 
> You could implement that the metadata cannot be fetched in e.g., the viewer, but it doesn't mean that it's not parsed. You could remove the parsing too, but the data itself will still be in the stream since PDF.js does not strip or mask any data.

What do you mean? There's a method **pdf.getMetadata()** and it returns **info** parameter, isn'it it?

**Comment by vv7v7** [comment]
> 
> 
> Given how PDF files are actually structured, refer to the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf), there's _generally_ no good way to simply "ignore" arbitrary parts of the PDF file in the way you suggest. The only solution would be to edit the original file to remove all traces of the Info/Metadata dictionaries, and their entries in the XRef table.

How then is it possible to get a checksum of same document saved two times at different times which should return same value?
