### ISSUE TITLE
Getting different server errors like 503, 0 response when trying to view files through PDF.JS

### ISSUE THREAD

**Issue by Sterlingtech** [mozilla/pdf.js#10570]
Hi

We have PDF.JS integrated with our web application. We are getting the following errors when trying to view files through PDF.JS. This is happening to our users from various locations. They tried with different browsers. When we tried to open the file from our end we are able to open it without any issues. Please let us know the root cause of this issue and why it is happening?

1. Unexpected server response 503 while retrieving PDF.
2. Unexpected Server response 0 while retrieving
   PDF.jS V1.9.426 (build 2558a58d)
   Message: Unexpected Server Response (0) while retrieving
3. Invalid or corrupted PDF file, When clicked on more information Message: Invalid PDF structure(PDF.jS V1.9.426 (build 2558a58d))

Additional information: A few of our clients enabled Adobe plugins in IE.

![unexpected server response 0](https://user-images.githubusercontent.com/40163020/53114073-01d3b280-3569-11e9-896e-8117f3df5818.PNG)
![invalide or corrupted file 2](https://user-images.githubusercontent.com/40163020/53114115-1b74fa00-3569-11e9-9707-f7b94f7e79e0.PNG)
![invalide or corrupted file](https://user-images.githubusercontent.com/40163020/53114116-1c0d9080-3569-11e9-8785-5494a0f58170.PNG)

**Comment by Snuffleupagus** [comment]
> We have PDF.JS integrated with our web application. We are getting the following errors when trying to view files through PDF.JS. This is happening to our users from various locations.

This is first and foremost a *bug tracker*, and not a support forum. There's unfortunately no information provided which makes this a reproducible/valid issue, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, please note that PDF.js version `1.9.426` is no longer supported; see https://github.com/mozilla/pdf.js/releases for the latest releases.
