### ISSUE TITLE
textWidgetAnnotation values and properties

### ISSUE THREAD

**Issue by smit-modi** [mozilla/pdf.js#10571]
Attach (recommended) or Link to PDF file here: http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

Configuration:
- PDF.js version: 2.0.943
- Is a browser extension: No

I want to fetch the values from filled Acroform and save it by drawing on the same canvas and then converting it to pdf.

How can I fetch the entered values of Text box, location, font size, font type, Alignment, etc?

I saw an issue where you mentioned getAnnotation(), but I don't know how to use it. Can you please explain it in more details?

**Comment by timvandermeij** [comment]
The available properties for text widget annotations are https://github.com/mozilla/pdf.js/blob/master/test/unit/annotation_spec.js#L867-L872.

You can get the information by calling `getAnnotations` on the page object, such as we do here: https://github.com/mozilla/pdf.js/blob/ff74a66672c2980aa3dc2dd1b6f1407026b831de/test/unit/api_spec.js#L1057. The result is a data object with all information about the annotations on the page.
