### ISSUE TITLE
How to cancel a rendering canvas?

### ISSUE THREAD

**Issue by hagen666** [mozilla/pdf.js#10576]
Attach (recommended) or Link to PDF file here:
The same issue like https://github.com/mozilla/pdf.js/issues/9430.

Configuration:
- Web browser and its version: Firefox
- Operating system and its version: Windows 10
- PDF.js version:  2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1.  page.render().
2.  Re-rendering a canvas when the html is zooming.

What is the expected behavior? (add screenshot)
After zooming in/out, a more beautiful page was supposed to be painted.

What went wrong? (add screenshot)
If a new canvas is rendered, how about the old one? Because the old rendering is not stopped, could it be a waste of memory?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
As explained in the other issue, you should render on a new canvas instead of re-using an existing one. To clean up, you can call `page.cleanup()`.

**Comment by hagen666** [comment]
Thanks!
