### ISSUE TITLE
Viewer does not support local files on Chromium

### ISSUE THREAD

**Issue by schlamar** [mozilla/pdf.js#10587]
Configuration:
- Web browser and its version: QtWebEngine 5.12 (Chromium 69), Chrome 72
- Operating system and its version: Windows 7
- PDF.js version: 2.0.943, 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:
1. Open viewer locally (file:///C:/pdftest/web/viewer.html)

What is the expected behavior? 

Embedded PDF shown (it works in Firefox ESR 60).

What went wrong? 

Error in console: Fetch API cannot load file:///C:/pdftest/web/compressed.tracemonkey-pldi-09.pdf. URL scheme must be "http" or "https" for CORS request.

I have seen #9361 and #9020 but I don't think that's the solution in this case.

**Comment by Snuffleupagus** [comment]
As is clearly mentioned in the README, see https://github.com/mozilla/pdf.js#getting-the-code, not all browsers support the `file://` protocol:

> Finally, you need to start a local web server as some browsers do not allow opening PDF files using a `file://` URL.

**Comment by schlamar** [comment]
Chrome supports the file protocol, as it works with the built-in PDF viewer and with the chrome extension (which was apparently fixed in https://github.com/mozilla/pdf.js/pull/9363). So I'm pretty sure this is a bug in pdf.js and not a missing feature in Chrome.

`fetch` with file:// doesn't work in Firefox either (just try `fetch("file:///C:/pdftest/web/compressed.tracemonkey-pldi-09.pdf"` in console). So there must be a slightly difference opening the viewer in Firefox and on Chrome.

**Comment by schlamar** [comment]
OK, I found it:

    {
      var isNodeJS = __w_pdfjs_require__(4);

      if (isNodeJS()) {
        var PDFNodeStream = __w_pdfjs_require__(165).PDFNodeStream;

        pdfjsDisplayAPI.setPDFNetworkStreamFactory(function (params) {
          return new PDFNodeStream(params);
        });
      } else if (typeof Response !== 'undefined' && 'body' in Response.prototype && typeof ReadableStream !== 'undefined') {
        var PDFFetchStream = __w_pdfjs_require__(168).PDFFetchStream;

        pdfjsDisplayAPI.setPDFNetworkStreamFactory(function (params) {
          return new PDFFetchStream(params);
        });
      } else {
        var PDFNetworkStream = __w_pdfjs_require__(169).PDFNetworkStream;

        pdfjsDisplayAPI.setPDFNetworkStreamFactory(function (params) {
          return new PDFNetworkStream(params);
        });
      }
    }

My Firefox (60 ESR) doesn't have `body` in `Response.prototype`, so it is using the PDFNetworkStream (which works with file URLs).

Looks like the logic not to use `fetch` for file protocol (#9363) is totally missing in your release builts.

I assume the viewer is broken on a newer Firefox, too.
