### ISSUE TITLE
How to pass custom cookies to PDF.js fetch request?

### ISSUE THREAD

**Issue by neerajbalaji** [mozilla/pdf.js#10581]
Hi,

First of all sorry this is not exactly an issue but more of a query.( I didn't know where else to post this)

I have been going through the documentation and FAQs but I have not been able to figure out how to make PDF.js pass cookies to the fetch request that is made before rendering a PDF. I know that cookie header can be used when WithCredentials is set to true in PDF.js, but how would i do that exactly?

I have also gone through api.js that helps in enabling authentication, adding headers and cookies to the request. But i don't know exactly how to use it for my use case.

Currently, I am using PDF.js 1.10.10 and i am trying to pass cookies to private resources that resides on a  CDN. 

Would be helpful if someone can guide me how i can do this.

Thanks
Neeraj

**Comment by Snuffleupagus** [comment]
> But I don't know exactly how to use it for my use case.

And neither does anyone else, without *any* information about your configuration!

When opening an issue, you need to provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

> Currently, I am using PDF.js 1.10.10

That's *not* an official release, and even if you meant `1.10.100` that version is no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases.

> I have also gone through api.js that helps in enabling authentication, adding headers and cookies to the request.

Furthermore, there's no information about what you've *actually* tried and what did/didn't work, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by neerajbalaji** [comment]
Sorry for not providing not enough information, but I have resolved this by adding parameters.WithCredentials = true; before the parameters object is added to _pdfjsLib.getDocument() in Viewer.js. Hope this helps for anyone out there.
The issue can be closed.

Thanks
