### ISSUE TITLE
Possible to unbind certain events in eventBus?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10583]
for example, i would like to unbind the resize event

is it possible?

tried window.removeEventListener('resize', PDFViewerApplication._boundEvents.windowResize)

and PDFViewerApplication.eventBus.off('resize', PDFViewerApplication._boundEvents.windowResize)

didnt work out.

i am looking for a way to not have to comment out the lines in viewer.js

thanks

**Comment by Snuffleupagus** [comment]
There's the `PDFViewerApplication.unbindEvents`/`PDFViewerApplication.unbindWindowEvents` methods which removes all events, but for anything "special" you'll need to modify the code yourself.

(Also, as is clearly mentioned e.g. at https://mozilla.github.io/pdf.js/getting_started/, the default viewer isn't intended to be used as-is without modification anyway.)
