### ISSUE TITLE
2.0.9  2.1 以及1.0 版本出错提示：An error occurred while loading the PDF. More lnformation

### ISSUE THREAD

**Issue by babyhai** [mozilla/pdf.js#10586]
安装2.0.943 、2.1.266  、1.10.100 版本 谷歌浏览器打开 web/viewer.html   提示：
An error occurred while loading the PDF. More lnformation
PDF. js v1.10.100 (build: ea29ec83)   
Message : Failed to fetch

而从 https://mozilla.github.io/pdf.js/  页面打开 demo 页面打开PDF文件(非扫描版) 可划词翻译

**Comment by Snuffleupagus** [comment]
Unfortunately this issue contains no actionable information, and will thus be closed as INCOMPLETE.

> PDF. js v1.10.100 (build: [ea29ec8](https://github.com/mozilla/pdf.js/commit/ea29ec83e1bb4ea44d71cccc451c6b9374e10fb9))

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases.

Finally, when opening an issue you need to provide all of the details requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (including *clear* steps to reproduce the problem) *and* also make sure to write in English.
