### ISSUE TITLE
Question when PDFViewerApplication.eventBus becomes available?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10584]
Is there a way to find out when the eventBus object is available in the viewer?

I would like to listen to any of these events using my own callback function.

Or does PDF.JS throw some event when the eventBus object is available?

**Comment by timvandermeij** [comment]
You should be able to listen for the `webviewerloaded` event, which is emitted when all viewer files are loaded (see https://github.com/mozilla/pdf.js/blob/c91f437eaaff79b660805e020f4fa9d4a2a7fe65/web/viewer.js#L208-L213). Alternatively, there is the `documentinit`/`documentload` event.

**Comment by Snuffleupagus** [comment]
> Alternatively, there is the `documentinit`/`documentload` event.

In case the loading/initialization of the viewer *itself*, rather than a PDF document, is what matters here then the `localized` event is probably what you want; see https://github.com/mozilla/pdf.js/blob/de56518799b869d1cb4d313c7628a8aa956966f8/web/app.js#L168-L170

**Comment by chitgoks** [comment]
there does not seem to be any webviewerloaded in the stable version v2.0.943.

also, localized is incorrect because i am interested in getting the eventBus object. if it is not available, i cannot listen to it.

i tried document.addEventListener('localized') and the PDFViewerApplication.eventBus object is undefined.

**Comment by diesel167** [comment]
i also have the same problem - i want to set custom listener at pagesloaded event, but i can do that only after eventBus will be not null. And there is the bad way to check eventBus by setTimeout (and then you may lost your **pagesloaded** event ) . Is there is some way to get a moment when eventBus will be available to work with me?
