### ISSUE TITLE
Clear temporary canvas on JpegDecode handler

### ISSUE THREAD

**Issue by fbilleaud** [mozilla/pdf.js#10594]
Configuration:
- Web browser and its version: Safari desktop 12.0 / iOS 12
- Operating system and its version: macOS Mojave / iOS 12
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. Display several bas64 pdf with many pictures
2. Total canvas memory use exceeds the maximum limit (224 MB). error appear.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
On JpegDecode handler, temporary canvas is created to get the data on loaded picture. Canvas was not clear after and stay in memory. We can fix it by doing a ClearRect on this canvas. (line 9273)

<img width="1122" alt="capture d ecran 2019-02-28 a 10 58 04" src="https://user-images.githubusercontent.com/7128340/53558199-c8daa580-3b47-11e9-94a0-59c7e039fbae.png">

**Comment by timvandermeij** [comment]
Nice find!
