### ISSUE TITLE
cannot scroll in the latest chromium or chrome canary

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#10596]
when i put the pdf-viewer in the iframe and manually set the iframe's width, and then move the mouse pointer to the page's canvas, the container cannot scroll.

browser: latest chromium or chrome canary

**Comment by Snuffleupagus** [comment]
> browser: latest chromium or chrome canary

If this is specific to a *particular browser* (or its version) that would suggest a bug in browser itself, rather than in the PDF.js library.

Besides, without *any* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and without a runnable example this issue unfortunately isn't actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by cmh1996** [comment]
https://jsbin.com/fakimiharo/edit?html,css,output

**Comment by cmh1996** [comment]
> > browser: latest chromium or chrome canary
> 
> If this is specific to a _particular_ browser (or its version) that would suggest a bug in the browser itself, rather than in the PDF.js library.
> 
> Besides, without _any_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and without a runnable example this issue unfortunately isn't actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

this is the online demo:
https://jsbin.com/fakimiharo/edit?html,css,output
