### ISSUE TITLE
PDF does not render with exception TypeError: fonts[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by pdfhandler** [mozilla/pdf.js#10592]
Attach (recommended) or Link to PDF file here:
Unable to provide the PDF file currently due to GDPR restriction.

Configuration:
- FireFox 65.0.1, IE 11.0.9600.19266
- Windows 7:
- PDF.js version: pdfjs-2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Download the pdfjs-2.0.943.
2. Open http://../pdfjs-2.0.943-dist/web/viewer.html
3. Open PDF file.

What is the expected behavior? (add screenshot)
The PDF opens and the pages are rendered

What went wrong? (add screenshot)
The PDF opens but the viewer gets stuck trying to render. The blank pages remains with the circular animation.

![image](https://user-images.githubusercontent.com/42236192/53486658-3a9bec00-3a81-11e9-9bbe-201888449d10.png)

**Error from the console:**

"PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.0.943)" viewer.js:1291
TypeError: fonts[Symbol.iterator] is not a function

**NOTE:** This document displayed fine in v1.9.426.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Unable to provide the PDF file currently due to GDPR restriction.

Without a test-case this issue is unfortunately not actionable, and it will thus be closed as incomplete.

> PDF.js version: pdfjs-2.0.943

Can this be reproduced using the latest pre-release, see https://github.com/mozilla/pdf.js/releases, and/or with the latest default viewer, see https://mozilla.github.io/pdf.js/web/viewer.html, as well?

**Comment by timvandermeij** [comment]
Closing until the information is provided.
