### ISSUE TITLE
[Question] Best way to get the pdf geometries per page

### ISSUE THREAD

**Issue by jivanova** [mozilla/pdf.js#10593]
What's the best way to use the pdj.js core to get the geometries within a page? I saw the operatorList and was able to get information of all actions that will be made in the canvas.
```
page.getOperatorList().then(function (operatorList) {
         // normalize the operatorList.fnArray and operatorList.argsArray
}
```
However, I was wondering if you could advice another approach. I'd like to get all geometries with its properties (like linewidth,fill, etc) that should be drawn in the canvas/svg.

**Comment by timvandermeij** [comment]
I don't see another way than using the operator list since that contains all data you're looking for. Other components internally also use the operator list and perform actions based on the data in there. We don't have a single entrypoint for this kind of information.
