### ISSUE TITLE
Rendering AcroForm Field Names

### ISSUE THREAD

**Issue by joshuahutchison** [mozilla/pdf.js#10618]
When I render an Acroform, everything seems fine until I inspect and see no field names being rendered. I thought perhaps it was my implementation, so I loaded the [example](https://github.com/mozilla/pdf.js/tree/master/examples/acroforms) as is and noticed field names aren't rendering in the HTML there either.

After looking through several of these issues, I've seen plenty of language indicating field name rendering works. What am I missing?

Using v2.0.943

**Comment by Snuffleupagus** [comment]
Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, as is this will be closed as incomplete.

**Comment by joshuahutchison** [comment]
Attach (recommended) or Link to PDF file here:
    https://web.archive.org/web/20110918100215/http://www.irs.gov/pub/irs-pdf/f1040.pdf

Configuration:

Web browser and its version:

    Chrome Version 72.0.3626.121 (Official Build) (64-bit)

Operating system and its version:

    Windows 10

PDF.js version:

    v2.0.943

Is a browser extension:

    Yes

Steps to reproduce the problem: 

   1. Load your acroform [example](https://github.com/mozilla/pdf.js/tree/master/examples/acroforms).
   2. inspect HTML input.

What is the expected behavior? 

    The expected behavior is that the fieldName assigned to the field in the pdf will render as an input name attribute in HTML.

What went wrong? 

    The field names were not rendered as input name attributes in HTML

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

    N/A. Running in local dev environment.

**Comment by Nilanth** [comment]
@timvandermeij Still I face this issue.
