### ISSUE TITLE
我用iframe渲染展示pdf的，我如何在h5 移动端中手势放大缩小查看pdf

### ISSUE THREAD

**Issue by WanerYC** [mozilla/pdf.js#10611]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
We can only assist in English.
