### ISSUE TITLE
How to track worked PDF New insert text Delete text 

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#10627]
Hello,
I can't able to track new insert text,deleted text, highlighted text,comments text,replace text ,annotation from worked pdf.

In first para  author made any change in PDF document like "This are" change to "This is"  i want to track  "IS" new insert text in first para.  
[EditCorrection.pdf](https://github.com/mozilla/pdf.js/files/2945629/EditCorrection.pdf)

**Comment by Snuffleupagus** [comment]
It's virtually impossible to understand what you're actually trying to report here, please rephrase the issue and make sure that you fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with *all* of the requested information.

**Comment by a7vickey** [comment]
Please find attached pdf on  2 page 

After Introduction. please find the below text 
**"This book aims to support you."** 
In first para After "This" content  highlighted blue sticky i want to track  current position what text going to insert and  You was deleted text i want to remove "you" text current position.

**Comment by timvandermeij** [comment]
PDF.js is only a renderer, not an editor, so based on what you wrote I don't think it's possible.
