### ISSUE TITLE
PDF doesn't display - "offsetParent is not set" error 

### ISSUE THREAD

**Issue by mattkallo** [mozilla/pdf.js#10626]
Configuration:
- Web browser and its version:
Chrome - Version 72.0.3626.119 (Official Build) (64-bit)
- Operating system and its version:
macOS 10.14.2 (18C54)
- PDF.js version:
pdfjs-1.9.426
- Is a browser extension:
No

Steps to reproduce the problem:
1. Open the PDF on relatively slow connection (6 seconds to download 1.8mb PDF)
(It was working fine, the above is the only change that happened that I can think of. This happens randomly and the only correlation we could make was with the CloudFront download speed.)

What went wrong? (add screenshot)
1. PDF doesn't display. I see the below message in the console.
"offsetParent is not set -- cannot scroll viewer.js"
2. If I slightly resize the browser window,  the PDF displays. 

It may not be a bug - however is there a way to workaround this issue? 

Appreciate any help. Thanks !

**Comment by Snuffleupagus** [comment]
>     * PDF.js version:
>       pdfjs-1.9.426

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

>     1. Open the PDF on relatively slow connection (6 seconds to download 1.8mb PDF)
>        (It was working fine, the above is the only change that happened that I can think of. This happens randomly and the only correlation we could make was with the CloudFront download speed.)

Unfortunately this is nowhere near enough information for the issue to be actionable/valid, and we obviously cannot provide support for "CloudFront". Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing until more actionable information is provided.
