### ISSUE TITLE
Wiki: Update Viewer Options page with additional pagemode values

### ISSUE THREAD

**Issue by Lekensteyn** [mozilla/pdf.js#10625]
The current https://github.com/mozilla/pdf.js/wiki/Viewer-options page does not report all possible pagemode options and has formatting issues (see the backticks on the zoom line).

I've attempted to address these issues. Since Github [does not allow a PR to be created against a wiki][1], I've created a repo as workaround.
- Changes: https://github.com/Lekensteyn/pdf.js-wiki/compare/master...viewer-options
  - Convert .mediawiki to .markdown, fix formatting
  - Document additional pagemode values.
- Preview: https://github.com/Lekensteyn/pdf.js-wiki/blob/viewer-options/Viewer-options.md

Tested all documented pagemode values with http://www.jasnapaka.com/bugs/aaa.pdf#pagemode=outline (linked from #8024).

Why `pagemode=none`? While editing and previewing a figure in a PDF generated from a LaTeX document, I use `#page=7&zoom=200&pagemode=none` to ensure that the page jumps to the right position after refreshing the page. (Ideally I the full viewport position is remembered, but that is beyond the scope of this issue.)

To apply these changes, I suppose something like this could be done:
```
git checkout git@github.com:mozilla/pdf.js.wiki
cd pdf.js.wiki
git fetch https://github.com/Lekensteyn/pdf.js-wiki viewer-options
git merge viewer-options
```

 [1]: https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by Snuffleupagus** [comment]
Please note that `pagemode=outline` is a PDF.js specific feature, and as such shouldn't be advertised, since the *correct* standard value is `pagemode=bookmarks`.

**Comment by Lekensteyn** [comment]
Confirmed that bookmarks works, I've force-pushed a new version that fixes outline -> bookmarks. Thanks @Snuffleupagus!

**Comment by timvandermeij** [comment]
I have updated the wiki page with this new content. Thank you!
