### ISSUE TITLE
Pdf print on android device preview a blank page

### ISSUE THREAD

**Issue by emmanouil1989** [mozilla/pdf.js#10630]
Attach (recommended) or Link to PDF file here:
All pdfs

Configuration:
- Web browser and its version:
Google Chrome version 72.0.3626.121

- Operating system and its version:
Samsung galaxy S7( android version 7.0) and Samsung galaxy j6(android version 8.0.0).
On iOS works fine. 

- PDF.js version:
latest.

- Is a browser extension:
No

Steps to reproduce the problem:
1. Load a pdf in Chrom browser on an Android device
2. Click on print button.
3. Preview load blank page.
4. PDF is blank when is downloaded

What is the expected behaviour? (add screenshot)
Should preview the full content of pdf
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/4580086/54036064-9584c000-41b2-11e9-8b84-a08adb865b23.png)

![image](https://user-images.githubusercontent.com/4580086/54035925-59e9f600-41b2-11e9-9697-e0b6bf5db6b1.png)

**Comment by nickythorne** [comment]
Also happening here

**Comment by deliveryblueprints** [comment]
Seeing the same behaviour here also

**Comment by churstz** [comment]
I can confirm the same on the following:
* Galaxy S10 running Chrome 73.0.3683.90 
* Galaxy J3 running Chrome 72.0.3626.121

On both the S10 and the J3 when using Firefox, the "Preparing document for printing...." pops up hits 100% and hangs.

**Comment by tobiso95** [comment]
Same problem on:
- OnePlus 5T (Android 8.1.0) Chrome 75.0.3770.101
- iPhone 6s (12.3.1)

**Comment by rcarretteGroupeBRIAND** [comment]
same with S7 and latest Chrome. Any update on this please ?

**Comment by rcarretteGroupeBRIAND** [comment]
please someone to help ?

**Comment by pathomas** [comment]
I finally broke down and debugged this. Its been driving my team nuts. 
window.print is async, and the abort function was running before the device can finish rendering.
 
I put a fix in my fork, not sure what the best way is to send a pull request.
[https://github.com/pathomas/pdf.js/commit/e3205fd02421715b56fa6c98337fb568d598e11a](url)

**Comment by rcarretteGroupeBRIAND** [comment]
I personnaly gave up on this because I found a solution that don't even need PDF.js

**I'm working on a Xamarin.Forms app so my solution only works for this technology.**

To view the PDF I simply save the document to the device filesystem and then use `Device.OpenUri(new Uri(path));`

So that I can use the OS file display system which allows to provide the native methods for printing, sharing, etc. Pinch to zoom feature is also working.

Sometimes on Android, an exception could be thrown. To fix it: just add this code to `Application.OnCreate` method

`StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
 
StrictMode.SetVmPolicy(builder.Build());`

**Comment by thosch6** [comment]
I have the same problem with the following system:
- Samsung Tab A6
- Android 8.1
- pdfjs-2.2.228-dist
After the clicking the print button, the printing preview shows a blank page.

**Comment by Snuffleupagus** [comment]
Unfortunately this looks like a platform/browser-specific problem, rather than a PDF.js one, and as such it's unfortunately difficult to see that this is something we can fix here; please keep in mind that the web-platform provides quite limited control over printing via JavaScript/CSS.

**Comment by YsBunkerchain** [comment]
![image](https://user-images.githubusercontent.com/77961251/120990114-cea5a380-c7b2-11eb-814f-dbf06d5f59f3.png)
I just add a timeout to the abort. It cleans the printcontainer before the android print application open.
