### ISSUE TITLE
speedup headless getTextContent

### ISSUE THREAD

**Issue by FranckFreiburger** [mozilla/pdf.js#10631]
I am using PDF.JS as a server-side parser to get pdf text content only.
Everything works fine but processing is quite slow (10s for 20MB/120pages pdf file).
I wondering if it is possible to disable some unneeded facilities to speed up the process.

A the moment I defined my own PDFDataRangeTransport (with rangeChunkSize:4096) in order to load only the necessary amount of data (I also disableStream:true and disableAutoFetch:true)

Is it possible to go further ?

**Comment by Snuffleupagus** [comment]
> Everything works fine but processing is quite slow (10s for 20MB/120pages pdf file).

That would put the *average* text-extraction speed at ~83&nbsp;ms/page, which really doesn't seem bad at all considering that 20 MB is a fairly large PDF file. (Just for comparison, the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf) weighs in at 8.58&nbsp;MB for a 756 page document.)

Besides, what constitutes as *slow* is highly subjective, meaning that there's no proper criteria for when this issue would be considered "fixed".

> I wondering if it is possible to disable some unneeded facilities to speed up the process.

Assuming that you're only calling `getDocument`, followed by `getPage` and finally `getTextContent`, then I'm not sure what that would be!?
The PDF format is quite complex and having to parse large files will simply take time, there's really no way around that.

> Is it possible to go further?

Sorry, but this doesn't seem very actionable unfortunately; please also consider [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) when opening as issue.
