### ISSUE TITLE
PDFJS2.X can not work well in ie11 with some chinese

### ISSUE THREAD

**Issue by yuweiming2016** [mozilla/pdf.js#10649]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE11
- Operating system and its version: win7
- PDF.js version: 2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. open the demo url https://mozilla.github.io/pdf.js/web/viewer.html
2.select an pdf with chinese and i found that some pages was mess

![image](https://user-images.githubusercontent.com/22490427/54501073-0455dc00-495e-11e9-94b1-d03d82b1485b.png)

and i also found that PDFJS version 1.10.xxx can preview chinese pdf successful.

why pdfjs 1.x and 2.x was so different when pdf with chinese?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
>
>  select an pdf with chinese and i found that some pages was mess

What sort of assistance do you expect anyone to be able to provide when you leave out necessary information as requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)? As-is this issue will be closed as incomplete.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
>
>  select an pdf with chinese and i found that some pages was mess

Without access to a test-case, it's simply impossible for anyone to provide any sort of assistance or help here. (The likelihood that a IE11 specific font bug will be fixed probably isn't that great in general though.)

Please make sure that you provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue; as-is this issue will be closed as incomplete.
