### ISSUE TITLE
请问，如何设置选中的文本的背景颜色

### ISSUE THREAD

**Issue by 2638720389** [mozilla/pdf.js#10641]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
Wow, I tried google translate and it is a real text:
"How can I set the background color of the selected text?"

**Comment by timvandermeij** [comment]
Closing since this should be achieved by some CSS. Moreover, we can only provide assistance in English.
