### ISSUE TITLE
set current page does not work.

### ISSUE THREAD

**Issue by edilinux** [mozilla/pdf.js#10659]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome latest version
- Operating system and its version: Debian latest version
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. When I try set page inside a promise the set page returns: "PDFViewer._setCurrentPageNumber: "5" is out of bounds."
The PDF has 170 pages...

my code:
`
PDFViewerApplication.open('http://localhost/test.pdf').then(function(a){
//a = return undefinied
PDFViewerApplication.pdfViewer.currentPageNumber = 5;

})
`
Ps: the viewer.html is on the iframe... but when I call set page outside of open promise all works fine.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by rsshilli** [comment]
I can't get the currentPageNumber thing to work for the life of me. Here's what I'm doing instead:
```
    const page = $(`[data-page-number=${currentPage}]`)[0];
    parentContainer.scrollTop = page.offsetTop;
    parentContainer.scrollLeft = 0;
```
