### ISSUE TITLE
[AcroTex][LaTeX][eforms] radioButtons not visible

### ISSUE THREAD

**Issue by mpw-wwu** [mozilla/pdf.js#10656]
Attach (recommended) or Link to PDF file here:

[radiobuttondemo.pdf](https://github.com/mozilla/pdf.js/files/2987414/radiobuttondemo.pdf)

Configuration:
- Web browser and its version: Firefox 65.0.1 64-bit
- Operating system and its version: Ubuntu 18.04
- PDF.js version: shipped with Firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. Open PDF file

What is the expected behavior? (add screenshot)
Two radiobuttons should be visible (screenshot taken with Foxit Reader)

![Bildschirmfoto von 2019-03-20 10-35-19](https://user-images.githubusercontent.com/40468459/54674101-048bde00-4afc-11e9-963b-febfcbbb22c2.png)

What went wrong? (add screenshot)
The radiobuttons aren't visible

![Bildschirmfoto von 2019-03-20 10-35-50](https://user-images.githubusercontent.com/40468459/54674167-22594300-4afc-11e9-8d51-6cfb0306e346.png)

According to #7898 radiobuttons should be supported already. And Chrome does show them (although they still don't work).

If it is helpful, here's the source code for this pdf:

```
\documentclass{article}
\usepackage{eforms}
\begin{document}
\begin{Form}
  \noindent\radioButton{radioButtonGroup}{0.5cm}{0.5cm}{radioButtonA} radioButton A\\
  \radioButton{radioButtonGroup}{0.5cm}{0.5cm}{radioButtonB} radioButton B\\
\end{Form}
\end{document}
```

**Comment by timvandermeij** [comment]
You need to enable rendering interactive forms in order for them to become visible. This option is disabled by default since forms are still experimental. You can enable it by running `PDFViewerApplication.preferences.set('renderInteractiveForms', true);` in the web console, for example at https://mozilla.github.io/pdf.js/web/viewer.html and opening your test file. The radio buttons then render just fine. Closing as answered.

**Comment by mpw-wwu** [comment]
Ah okay, thanks for the reply.

**Comment by mpw-wwu** [comment]
Thanks, that indeed works nice.

But they aren't printed and comboFields (drop down plus textfield for self defined answers) aren't working. Should I create separate issues for those problems?

**Comment by timvandermeij** [comment]
Printing is already tracked in #7613. I'm not sure what combofields are, so for that it may be good to create a separate issue.

**Comment by MPW1412** [comment]
@timvandermeij, combo fields are drop down menus combined with text fields. So you can select pregiven values or input any text you want to.

**Comment by timvandermeij** [comment]
If you have an example PDF file with such a field, then please provide it in a new issue so we can take a look. Thanks.

**Comment by mpw-wwu** [comment]
Voilà: #10669
