### ISSUE TITLE
PDF fonts (very intermittently) not rendering in IE or Edge

### ISSUE THREAD

**Issue by hennievw** [mozilla/pdf.js#10658]
I'm experiencing a very intermittent issue where the fonts for some of our pdf files won't render. Images and shapes are being rendered but not text.
If you try again later ( say 10 minutes ) and refresh, then the document renders fine.

In the console, the following error is being printed: "Load test font never loaded."

If you were to go to the Security Settings in IE11 and set the "Font download" option to "Disable" you'll get the exact same behaviour. The setting is however set to "Enable" so this is not the cause of the problem.

I'm suspecting that the "isFontReady" function in "font_loader.js" might be failing more than 30 times, for some reason. I'm not sure why.

[test file.pdf](https://github.com/mozilla/pdf.js/files/2988520/test.file.pdf)

Configuration:
- IE and Edge. IE version: 11.379.17763.0
- Operating system and its version: Windows 10 Pro
- PDF.js version: 2.0.943

Steps to reproduce the problem:
1. Open the attached PDF in IE11 with pdf.js
2. Its intermittent,

What is the expected behavior? 
The document should render normally.

What went wrong? 
There is no text being rendered

**Comment by Snuffleupagus** [comment]
In modern, standards-compliant, browsers the fonts in PDF.js are loaded via the [Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API). This has the advantage that it's trivial to detect if/when fonts are successfully loaded, and thus it's also possible to handle any errors.

For older browsers, the font loading is a best-effort hack which simply cannot be guaranteed to always work well; please find additional information in this code: https://github.com/mozilla/pdf.js/blob/bce9ff7347266e18326fff52c201faba04a96bd7/src/display/font_loader.js#L239-L333

> I'm experiencing a very intermittent issue where the fonts for some of our pdf files won't render.

Given the "very intermittent" part of the issue description, and the fact that there's no good way to detect/handle errors for fonts that fail to load in e.g. IE11, this issue thus cannot be fixed.

---

*In closing:* There's unfortunately nothing that can be done here, and I'd thus suggest closing this issue as wontfix (or even cantfix really).
