### ISSUE TITLE
Jump to page not working properly on Mozilla, Edge and IE.

### ISSUE THREAD

**Issue by ezequiel9** [mozilla/pdf.js#10654]
There is an issue on Mozilla, Edge, and IE.

The problem begins if you want to jump to a page and your pdf has a different high of pages. 

So, for example when you pass a parameter '#page=20' and there is a page before (Eg page 18) which is lower or higher than the rest of the pages, then 19, 20 and forward will appear not at the top of the page. 

I've tried to combinate parameters but does not work on those Browsers, only work properly on Chrome.

#page=20
#page=20,0,0
#page=page-fit
...

Thanks.

**Comment by Snuffleupagus** [comment]
Please make sure that you fill out the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) with *all* of the requested information when opening an issue; as-is there's unfortunately no actionable information provided here.

**Comment by timvandermeij** [comment]
Closing until the issue template information is provided, in particular an example PDF file and exact steps to reproduce. Thanks.
