### ISSUE TITLE
pdf.js rendering too slow when are more than 50 pages

### ISSUE THREAD

**Issue by padiss80** [mozilla/pdf.js#10651]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE, Chrome and Firefox
- Operating system and its version: Windows 8.1
- PDF.js version: 2.0.489
- Is a browser extension: NO

Steps to reproduce the problem:
1.  View some pdf with more than 50 pages
2. When the canvas intended rendering all of the pages the pc is too slow, and crash the navigator.

My code is : 

function inicioCanvas1 (pdfData) {
	// Loaded via <script> tag, create shortcut to access PDF.js exports.
	var pdfjsLib = window['pdfjs-dist/build/pdf'];
	pdfjsLib.GlobalWorkerOptions.workerSrc = 'js/pdf/pdf.worker.js';
	// Using DocumentInitParameters object to load binary data.
	var loadingTask = pdfjsLib.getDocument({data: pdfData, disableAutoFetch: true, disableStream: true});
	loadingTask.promise.then(function(pdf) {	  
	  // Fetch the first page
	  var pageNumber = 1;
	  thePDF = pdf;
	  pdf.getPage( pageNumber ).then( handlePages );
	  numPages = pdf.numPages
	}, function (reason) {
	  // PDF loading error
	  console.error(reason);
	});
}

function handlePages(page) {
    //This gives us the page's dimensions at full scale
    var viewport = page.getViewport( cteScale );
    //We'll create a canvas for each page to draw it on
    var canvas = document.createElement( "canvas" );
    canvas.setAttribute("name", "canvasID");
    canvas.setAttribute("id", "canvasID");
    canvas.style.display = "block";
    canvas.style.marginLeft = "none";
    canvas.style.marginRight = "none";
    canvas.style.align = "center";
    var context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;
    var widthCanvas=canvas.width;    
    
    currPage++;
    //Draw it on the canvas
    page.render({canvasContext: context, viewport: viewport});
    
    //Add it to the web page
    $("#pdf0").append( canvas );
    //Move to next page
    if ( thePDF !== null && currPage <= numPages )
    {
        thePDF.getPage( currPage ).then( handlePages );
    }	
}

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, which advises *against* loading a large amount of pages simultaneously.

**Comment by timvandermeij** [comment]
Closing as answered since we don't really support this use case. Note that we're always working on optimizations in general.
