### ISSUE TITLE
Native Worker API is not being used.

### ISSUE THREAD

**Issue by jeffmcmahan** [mozilla/pdf.js#10650]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: *Safari 12.1 (via WKWebView)*
- Operating system and its version: *iOS 12.1*
- PDF.js version: *pdfjs-dist 2.0.943*
- Is a browser extension: *No*

Steps to reproduce the problem:
1. *Load any PDF using pdfjs (with pdf.worker.js loaded as well).*

What is the expected behavior?

*PDFJS will use a native worker thread, since `Worker` is fully implemented in Safari.*

What went wrong?

*Console prints `Warning: Setting up fake worker` on every outing.*

---

Investigation thus far: `PDFWorker_initialize` starts by checking the following three conditions, to determine whether to setup a fake worker or not:

```js
   (typeof Worker !== 'undefined') // true
&& !isWorkerDisabled // true
&& !getMainThreadWorkerMessageHandler() // false
```

These come back `true`, `true`, and `false`, respectively. The `false` condition reduces to a check on two further conditions:

```js
   window.pdfjsWorker // true
&& window.pdfjsWorker.WorkerMessageHandler // true
```

That means that if `pdfjsWorker` is defined, PDFJS will not use a native `Worker`. Well that seems odd. A cursory read through pdf.worker.js defeasibly indicates that it is not doing any sophisticated feature detection on the native `Worker` implementation, to rule out its use.

So: is the `!` preceding the failing condition above a mistake? If so, we'd predict that flipping the polarity would fix the issue. It does, at least in my case. The condition appears here:

https://github.com/mozilla/pdf.js/blob/7c9f1cc518fb19ecf8af0706d4e20bee93caeba2/src/display/api.js#L1500

If it is not a mistake, then somehow, somewhere, PDFJS is failing to recognize that Safari on iOS does not require a fake worker implementation.

**Comment by Snuffleupagus** [comment]
> Load any PDF using pdfjs (with pdf.worker.js loaded as well).

The way I'm interpreting this is that you, for some inexplicable reason, are *manually* loading the `pdf.worker.js` file (e.g. with a `<script>` tag), which thus indicates that you want to *disable* workers.

What you're *supposed* to do here, is to set the `GlobalWorkerOptions.workerSrc` to the path where the `pdf.worker.js` file can be found; please refer to e.g. the examples found at https://mozilla.github.io/pdf.js/examples/

If the above isn't enough to fix things, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by jeffmcmahan** [comment]
> you, **for some inexplicable reason,** are manually loading the pdf.worker.js file (e.g. with a <script> tag), which thus indicates that you want to disable workers.

The "inexplicable reason" is that I need to load that file from disk from an app that is running in iOS in a WKWebView instance -- **for good, sensible, complicated reasons,** and specifying the `workerSrc` was not working. So I tried a script include, and it worked. I did not realize that loading it directly would amount to telling PDFJS to disable the native worker. I rather doubt that such is explicitly documented anywhere, but either way, the knee-jerk condescension is not a good look.

**Comment by Snuffleupagus** [comment]
> The "inexplicable reason" is that I need to load that file from disk from an app that is running in iOS in a WKWebView instance -- **for good, sensible, complicated reasons,** and specifying the `workerSrc` was not working.

Sorry if my choice of wording offended you, that wasn't my intention at all! (As a non-native English speaker, I suppose that some nuances may not always translate too well.)

Also, the additional information provided above does contain a lot more context which wasn't (at least to me) readily apparent from the original post.

---

What may perhaps work instead, is to use the `GlobalWorkerOptions.workerPort` to load the `pdf.worker.js` file; see https://github.com/mozilla/pdf.js/blob/ee3cfb79863f2ddac69c029ef495cac57f36a937/src/display/worker_options.js#L18-L22
I'm not sure how relevant it is in *this* particular instance, but one example of that being used can be found in https://github.com/mozilla/pdf.js/blob/master/external/dist/webpack.js

**Comment by rushglen** [comment]
I have this issue as well, any updates?
