### ISSUE TITLE
 Error during font loading: Unable to load binary CMap at: ../web/cmaps/GBK-EUC-H.bcmap

### ISSUE THREAD

**Issue by XXXS** [mozilla/pdf.js#10660]
Help me, thank you.
error:
dom_utils.js:112 GET http://test.sifong.cn:3129/m/v3/static/pdfjs/web/cmaps/GBK-EUC-H.bcmap 404 (Not Found)
(anonymous) @ dom_utils.js:112
fetch @ dom_utils.js:78
(anonymous) @ api.js:2107
(anonymous) @ message_handler.js:105
Promise.then (async)
MessageHandler._onComObjOnMessage @ message_handler.js:104
util.js:306 Warning: Error during font loading: Unable to load binary CMap at: ../web/cmaps/GBK-EUC-H.bcmap

pdf url :http%3A%2F%2Ftest.sifong.cn%3A3129%2Freport%2FPExamUp.ashx%3Fact%3Ddown%26sFile%3DIPUQU66BOKULY68EDLPX8TM8A7H3EZ.pdf

**Comment by THausherr** [comment]
I can display http://test.sifong.cn:3129/report/PExamUp.ashx?act=down&sFile=IPUQU66BOKULY68EDLPX8TM8A7H3EZ.pdf on firefox.

**Comment by XXXS** [comment]
> 我可以在firefox上显示http://test.sifong.cn:3129/report/PExamUp.ashx?act=down&sFile=IPUQU66BOKULY68EDLPX8TM8A7H3EZ.pdf。

but  , my problem is that Chinese is not displayed.

**Comment by Snuffleupagus** [comment]
If the CMap files fail to load, that would indicate a configuration issue in your implementation. Either you haven't (correctly) specified the necessary parameters when calling `getDocument`, or you haven't actually included the CMap files themselves, see https://github.com/mozilla/pdf.js/blob/844aecf9e3bcec7c8e4fb3f35ebadb562eec8013/src/display/api.js#L163-L166

Without additional information, it isn't possible for anyone to help. Please make sure that you provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by XXXS** [comment]
@Snuffleupagus     [This is a complete example. :  ]( https://github.com/XXXS/pdf-err.git)

**Comment by Snuffleupagus** [comment]
You still haven't provided *any* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, furthermore the provided example is difficult to follow; keep the following part in mind: "please prepare a short well-documented example".

Also, this line looks suspicious since no such version of the PDF.js library exists: https://github.com/XXXS/pdf-err/blob/master/pdfjs-dist/package.json#L3

**Comment by timvandermeij** [comment]
Also, http://test.sifong.cn:3129/m/sf/pdfjs-dist/cmaps/GBK-EUC-H.bcmap in fact gives a 404 response, so this looks like a webserver configuration issue.

**Comment by XXXS** [comment]
> 另外，[http](http://test.sifong.cn:3129/m/sf/pdfjs-dist/cmaps/GBK-EUC-H.bcmap) ://test.sifong.cn:3129/m/sf/pdfjs-dist/cmaps/GBK-EUC-H.bcmap实际上给出了404响应，因此这看起来像是Web服务器配置问题。

The same error is reported when deployed on the server [Complete code](https://github.com/XXXS/pdf-err.git)

**Comment by XXXS** [comment]
> 您仍然没有提供[https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md中](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)要求的_任何_信息，此外提供的示例很难遵循; 请记住以下部分：“请准备一份记录完整的简短示例”。[](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)
> 
> 此外，这一行看起来很可疑，因为不存在这样的PDF.js库版本：[https](https://github.com/XXXS/pdf-err/blob/master/pdfjs-dist/package.json#L3)：[//github.com/XXXS/pdf-err/blob/master/pdfjs-dist/package.json#L3](https://github.com/XXXS/pdf-err/blob/master/pdfjs-dist/package.json#L3)

Version comes from pdf.js/examples/mobile-viewer/,    [Complete information](https://github.com/XXXS/pdf-err.git)

**Comment by XXXS** [comment]
The problem has been solved.   Our server is window server.   Perhaps the server does not support this file type.  
All I have to do is add a new MIME type to IIS:

File extension: .properties
MIME type: application / octet-stream

File extension: .bcmap
MIME type: application / octet-stream
