### ISSUE TITLE
add function to the viewer.js

### ISSUE THREAD

**Issue by shenliang724** [mozilla/pdf.js#10662]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: goole 
- Operating system and its version:2.0.945
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
    I want to import some functions in other jsFile  to the viewer.js .but It shows unexcepted indeniefer . why the viewer.js can't use any other js Files. I really want to solve this. please help me .thank you very much   

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Unfortunately it's very difficult to understand what's actually being reported/asked here, and the limited information provided thus far isn't really sufficient to make this a valid issue.

Please keep in mind that this is first and foremost a *bug tracker*, and not a general support forum.
