### ISSUE TITLE
Render pdf with viewer.html in React JS component

### ISSUE THREAD

**Issue by awesomesunil** [mozilla/pdf.js#10663]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chorme
- Operating system and its version: windows
- PDF.js version:2.0943
- Is a browser extension:no

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You can just embed it in an iframe, or use https://github.com/wojtekmaj/react-pdf.
