### ISSUE TITLE
Annotations not rendering correctly

### ISSUE THREAD

**Issue by rakeshkasinathan** [mozilla/pdf.js#10672]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- Operating system and its version: macOS High Sierra Version 10.13.6 (17G5019)
- PDF.js version:2.0
- Is a browser extension:No

Steps to reproduce the problem:
1. I think rendering of PDF is wrong
2. I came out the following issues,
3. While delete and insert text my inserted comment disappear
4. While reply to post comment that time my post comment is missing.

What went wrong? (add screenshot)

<img width="694" alt="Screen Shot 2019-03-23 at 12 10 20 PM" src="https://user-images.githubusercontent.com/731235/54862715-c0e7dd00-4d64-11e9-8baa-f1b00d841bc2.png">
<img width="763" alt="Screen Shot 2019-03-23 at 12 17 56 PM" src="https://user-images.githubusercontent.com/731235/54862792-c0037b00-4d65-11e9-9fab-2dba73c17ee3.png">

**Comment by timvandermeij** [comment]
Closing since it looks like this is an external library that uses PDF.js (since we don't provide the shown icon for annotations) and we don't support editing them, so please file this issue at the library's repository instead.

**Comment by rakeshkasinathan** [comment]
I have not used any external library, i have used acrobat reader to annotate, insert and delete. I had taken the screenshot form your demo link only. Here by i will attach my pdf file as well as screenshot of demo link which you have given in the GitHub.

[Passasjeren_strukturert (4) 11.pdf](https://github.com/mozilla/pdf.js/files/3001745/Passasjeren_strukturert.4.11.pdf)

<img width="1440" alt="Screen Shot 2019-03-25 at 11 24 38 AM" src="https://user-images.githubusercontent.com/731235/54898022-a6426f00-4ef0-11e9-87ea-c073842612c4.png">
<img width="1440" alt="Screen Shot 2019-03-25 at 11 24 48 AM" src="https://user-images.githubusercontent.com/731235/54898030-aa6e8c80-4ef0-11e9-8f77-3b309bda3370.png">

**Comment by THausherr** [comment]
Could it be that what you're trying to tell us, is that in Adobe Reader, the popup shows "This is a test" while in PDF.js the popup shows "My Reply"?
