### ISSUE TITLE
Contents of annotations not (completely) visible

### ISSUE THREAD

**Issue by rakeshkasinathan** [mozilla/pdf.js#10677]
I have not used any external library, i have used acrobat reader to annotate, insert and delete. I had taken the screenshot form your demo link only. Here by i will attach my pdf file as well as screenshot of demo link which you have given in the GitHub.

[Passasjeren_strukturert (4) 11.pdf](https://github.com/mozilla/pdf.js/files/3001745/Passasjeren_strukturert.4.11.pdf)

<img width="1440" alt="Screen Shot 2019-03-25 at 11 24 38 AM" src="https://user-images.githubusercontent.com/731235/54898022-a6426f00-4ef0-11e9-87ea-c073842612c4.png">
<img width="1440" alt="Screen Shot 2019-03-25 at 11 24 48 AM" src="https://user-images.githubusercontent.com/731235/54898030-aa6e8c80-4ef0-11e9-8f77-3b309bda3370.png">

_Originally posted by @rakeshkasinathan in https://github.com/mozilla/pdf.js/issues/10672#issuecomment-476064327_

**Comment by THausherr** [comment]
An idea bug report contains three things: what you were doing, what you were expecting, and what happened instead.

What were you expecting?

**Comment by Snuffleupagus** [comment]
Please don't open multiple duplicate issues, but update the original one with all the necessary information instead and then that may be re-opened when enough information has been provided.

**Comment by timvandermeij** [comment]
I agree with the comments above: what are you expecting? From the screenshots I really can't tell what the problem is. Is there text in the annotations that should not be there? Should there be more/less annotations? What is the rendering defect you're reporting?

**Comment by rakeshkasinathan** [comment]
There are two issues:

1. The comment in the insert mark (blue caret symbol) is not showing up in PDFjs. If you open the attached PDF in the Acrobat Reader, you would notice that both the insert icons have comments in them. These completely missing in PDFjs.

2. In this sticky note comment at the start of the PDF, the original comment was "This is a test" and it has reply to comment "My reply". Only "My Reply" is showing up.

I have attached the PDF that I'm using to test for your reference.   

[Passasjeren_strukturert (4) 11.pdf](https://github.com/mozilla/pdf.js/files/3011639/Passasjeren_strukturert.4.11.pdf)

**Comment by vlastimilmaca** [comment]
Hi, there is missing implementation of some annotation features like InReplyTo (your 2. issue) and groups (your 1. issue). 

This requires quite a lot of coding on both worker part and display part of pdfjs. I tried to implement the worker part, so I can provide that as pull request (https://github.com/vlastimilmaca/pdf.js/tree/annotations-enhanced-parsing), but there's gonna be some extensive coding work on display part too. I think, there will have to be some kind of side-bar (like bookmarks, attachments etc) for displaying markup annotations as discussion threads. In page area, on mouseover, there should be displayed first comment + info about how many replies and state it has (which will probably need some localized text ... not easy ...). On click, it should open discussion sidebar and focus to correct annotation thread. But that is how I see it and it will be quite a lot of work to get it done right. But worker part is probably first step ... It should not break display part, so display part work can start later.

**Comment by rakeshkasinathan** [comment]
Do you need any more clarifications from my side.

**Comment by rakeshkasinathan** [comment]
I understand that the above solution of for enhancing annotations with multiple response to a comments. We still have another outstanding issue. The insert comment with the blue caret symbol still does not display the comment it. How can we get to see the comment inside the insert comment in PDFjs.
<img width="484" alt="Screen Shot 2019-04-05 at 3 45 26 PM" src="https://user-images.githubusercontent.com/731235/55620969-e4297800-57b9-11e9-9ad0-bb40c3ce2427.png">

**Comment by vlastimilmaca** [comment]
That should do the implementation of worker part I guess … It should correctly fill-in the master annotation with content and current display layer should display it just fine. I'll try to prepare merge request over weekend and we will se where we can get :).

**Comment by a7vickey** [comment]
Hello,

How can i get CaretAnnotation,StrikeOutAnnotation position and text ranges.

**Comment by THausherr** [comment]
For caret, use the /Rectangle entry. For strikeout, use the /QuadPoints entry. See also the PDF specification.
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf
however the order of the quadpoints is wrong, see
https://stackoverflow.com/questions/9855814/pdf-spec-vs-acrobat-creation-quadpoints

**Comment by timvandermeij** [comment]
The functionality is now in the API, so since the other points here are fixed I'm closing this with #10982 as a follow-up.
