### ISSUE TITLE
Introduce unit tests for reading files with streaming

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10671]
In #10668 we removed a Firefox-specific unit test for this, but this is useful functionality to unit test. Hence the idea to introduce new unit tests for this that work in all browsers and, if only code from `fetch_stream.js` is tested, that live in their own file.

**Comment by Snuffleupagus** [comment]
> [...] introduce new unit tests for this that work in all browsers

Just to clarify: This refers to browsers with *native support* for the Fetch API and `ReadableStream`.
