### ISSUE TITLE
Javascript error if viewer is loaded in blob context

### ISSUE THREAD

**Issue by ChoOo7** [mozilla/pdf.js#10682]
I'm dynamically creating an iframe and displaying viewer in that page

I'm using blob for that

So, from the viewer context, window.location.href is "blob:http://localhost:2427/59971e86-61e9-481f-9140-b36805bd5e25"

This is causing a crash on app.js

let validateFileURL;
if (typeof PDFJSDev === 'undefined' || PDFJSDev.test('GENERIC')) {
  const HOSTED_VIEWER_ORIGINS = ['null',
    'http://mozilla.github.io', 'https://mozilla.github.io'];
  validateFileURL = function validateFileURL(file) {
    if (file === undefined) {
      return;
    }
    try {
      let viewerOrigin = new URL(window.location.href).origin || 'null';
      if (HOSTED_VIEWER_ORIGINS.includes(viewerOrigin)) {
        // Hosted or local viewer, allow for any file locations
        return;
      }
      let { origin, protocol, } = new URL(file, window.location.href); <=== HERE
PDF.js v2.2.59 (identifiant de compilation : e1b01a60)
Message : Failed to construct 'URL': Invalid URL

**Comment by Snuffleupagus** [comment]
In order for anyone to look into this, a *runnable* test-case would be needed as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing until a runnable test case is provided.
