### ISSUE TITLE
how to show input domain，when i filled domains use pdf reader show sucess，but using pdf.js show no changes

### ISSUE THREAD

**Issue by shouqibao** [mozilla/pdf.js#10693]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
No information is filled into the template and the title is not clear about what the actual problem is (what kind of "domains" are we talking about here?).

**Comment by shouqibao** [comment]
sorry，FormField

**Comment by timvandermeij** [comment]
If you mean filling in forms, that's not (yet) supported in PDF.js.
