### ISSUE TITLE
Chinese Annotations don't display

### ISSUE THREAD

**Issue by bfy** [mozilla/pdf.js#10699]

**Comment by timvandermeij** [comment]
Closing since none of the information from the issue template is provided.

**Comment by bfy** [comment]
Thank you very much for your reply！Below, the first picture is normal, the second picture is abnormal, the Chinese in the red box is not displayed, thank you again!
 [
![image](https://user-images.githubusercontent.com/2143226/55706971-0bc84c80-5a15-11e9-93cf-bc0422faf978.png)
](url)

[
![image](https://user-images.githubusercontent.com/2143226/55707112-695c9900-5a15-11e9-8302-f05cfdca66ae.png)
](url)

**Comment by THausherr** [comment]
You need to attach a PDF. If it is confidential, please create a non confidential one with the same problem.

**Comment by bfy** [comment]
> You need to attach a PDF. If it is confidential, please create a non confidential one with the same problem.

Thanks a lot

**Comment by bfy** [comment]
> Closing since none of the information from the issue template is provided.
Thank you for your help. The red font in the following file cannot be displayed in pdf.js
[
[src.pdf](https://github.com/mozilla/pdf.js/files/3130239/src.pdf)
](url)

**Comment by THausherr** [comment]
Works for me with the latest viewer on W10 with Edge or Chrome, on W7 with Firefox, but maybe it's different depending what fonts are installed on the target system.
