### ISSUE TITLE
Incorrect conversion of LATIN SMALL LIGATURE FI

### ISSUE THREAD

**Issue by arash16** [mozilla/pdf.js#10697]
Attach (recommended) or Link to PDF file here:
https://uva.onlinejudge.org/external/1/p100.pdf

Configuration:
- Web browser and its version: Node.js
- Operating system and its version: Linux Mint 18
- PDF.js version: 2.0.550 and below (I have other problems with newer versions)
- Is a browser extension: no

Steps to reproduce the problem:
1. run pdf2svg with mentioned pdf file

What went wrong? (add screenshot)
In the first line of pdf file "classified" is converted to "classi}ed"

What is the expected behavior? (add screenshot)
Expected to see unicode character 'ﬁ' (LATIN SMALL LIGATURE FI), but instead '{' is printed.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.0.550 and below (I have other problems with newer versions)

WFM, when using the `master` version of PDF.js (which is as of this writing is `2.2.107`) on Windows.

The version you're referring to is not an official release, as listed at https://github.com/mozilla/pdf.js/releases, and is thus not officially supported.
Furthermore, please note that any versions prior the latest official release are unfortunately no longer supported; hence the only suggestion would be to try use an up-to-date version of PDF.js to see if the issues persists

**Comment by timvandermeij** [comment]
Works for me too with the latest version.
