### ISSUE TITLE
image overlap and incorrect layering only on windows machines in firefox

### ISSUE THREAD

**Issue by mwilkins91** [mozilla/pdf.js#10690]
Attach (recommended) or Link to PDF file here:
The PDF can be found here: http://wivany.ufcontent.com/mozilla-native-pdf-viewer-testing/infogix-dispelling-the-data-governance-myth

Direct download here: https://content.cdntwrk.com/files/aT0xMDk1NTk4JnY9MSZpc3N1ZU5hbWU9aW5mb2dpeC1kaXNwZWxsaW5nLXRoZS1kYXRhLWdvdmVybmFuY2UtbXl0aCZjbWQ9ZCZzaWc9Yzg4MjFkYTgwZjBmNDNkZTZlYWUyMjA1MDYyZGViODY%253D

Configuration:
- Web browser and its version:
Firefox 66.0.2 (64-bit)
- Operating system and its version:
Windows 10 (Version 1803 OS Build 17134.648)
- PDF.js version:
Unsure extactly, whatever version ships as the default pdf viewer for the firefox version listed above

Steps to reproduce the problem:
1. On a windows OS, open firefox and navigate to the page hosting the pdf above or open the downloaded pdf directly.
2. View pages 5 or 6 (for example) and notice that they have rendered incorrectly (overlapping images, incorrect layering, etc)
3. compare the same pdf when viewed in chrome, safari, IE, Edge, or acrobat and notice the same errors do not occur

What is the expected behavior? (add screenshot)
https://photos.app.goo.gl/dmcxBJxVD6vVBf2K7 - This is how the pdf displays in every other browser and in acrobat, AND in firefox on other operating systems

What went wrong? (add screenshot)
https://photos.app.goo.gl/wjBkfvaL2zGYzWSE7 NOTE: this occurs both in the embedded viewer (pictured here) AND the native firefox pdf viewer (if you were to open the pdf with firefox directly)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): http://wivany.ufcontent.com/mozilla-native-pdf-viewer-testing/infogix-dispelling-the-data-governance-myth

This issue only seems to occur on a windows machine (I was not able to reproduce using a VM running windows 10 and firefox 66.0.2 on my Mac), only on actual windows hardware.

Any advice here? Am I missing something obvious or is this a bug?

**Comment by timvandermeij** [comment]
I've never seen that before. It sounds like it may have something to do with graphics drivers. Could you ensure that all drivers are updated and re-check?

**Comment by mwilkins91** [comment]
That seems to have resolved my issue! Weird, wouldn't have ever thought of that. Thanks!
