### ISSUE TITLE
FormField not show

### ISSUE THREAD

**Issue by shouqibao** [mozilla/pdf.js#10700]
replace pdf's FormField then show 
![image](https://user-images.githubusercontent.com/6976256/55301846-317faf80-5471-11e9-9ea5-8ff1a2017975.png)
button actual's 
![image](https://user-images.githubusercontent.com/6976256/55301862-4a886080-5471-11e9-9380-401d824efe9c.png)

**Comment by timvandermeij** [comment]
Closing since most of the information from the issue template is missing, most notably a PDF file to reproduce the issue and a clear description of what is actually wrong, since this doesn't become clear from the screenshots alone.
