### ISSUE TITLE
Links inside PDF file does not open in new tab

### ISSUE THREAD

**Issue by Haris-Jamil** [mozilla/pdf.js#10707]
Configuration:
- Web browser and its version: Google Chrome 73.0.3683.86
- Operating system and its version: Windows 7
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. There should be a link in PDF

I recently updated PDFJS version to 2.0.943 from 1.5.391 in our application after which the link started to open in the same tab as opened pdf. Before update link were opened in a separate tab.
I tried setting PDFJS.externalLinkTarget to PDFJS.LinkTarget.BLANK but it doesn't seem to work any more.

**Comment by timvandermeij** [comment]
The `PDFJS` global is removed in version 2.0, so that indeed doesn't work. However, `externalLinkTarget` is still available. You should be able to set it like https://github.com/mozilla/pdf.js/blob/bce9ff7347266e18326fff52c201faba04a96bd7/web/app.js#L156.
