### ISSUE TITLE
Find highlight all does not always mark words correctly

### ISSUE THREAD

**Issue by gongevangen** [mozilla/pdf.js#10708]
Attach (recommended) or Link to PDF file [here:]
[Ring 5_Final_low.pdf](https://github.com/mozilla/pdf.js/files/3033095/Ring.5_Final_low.pdf)

Configuration:
- Web browser and its version: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Operating system and its version: MacOS 10.14.3
- PDF.js version: the problem is seen in https://mozilla.github.io/pdf.js/web/viewer.html?file= so I guess that is the newest one.
- Is a browser extension: no

Steps to reproduce the problem:
1. Load Ring.5_Final_low.pdf
2. Search for Hillerød
3. Check Highlight all
4. Go to page 13

What is the expected behavior? (add screenshot)
The word Hillerød should be highlighted twice

What went wrong? (add screenshot)
Some other words are highlighted.
![Screenshot 2019-04-02 at 10 59 26](https://user-images.githubusercontent.com/25570694/55390586-c77e0d80-5537-11e9-828f-362e9a51d85b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by derekdreery** [comment]
Just like to confirm that I've also seen this issue. I'm on Linux, using the pdf.js that comes with Firefox developer edition 68.0b6, reading an academic paper with doi http://dx.doi.org/10.1016/j.jcjd.2013.10.005

**Comment by Snuffleupagus** [comment]
Fixed by #12855
