### ISSUE TITLE
Display Page borders and numbers

### ISSUE THREAD

**Issue by smit-modi** [mozilla/pdf.js#10704]
Configuration:
- PDF.js version : 2.1.262

I am using the following code to render the pdf. How can I display border and page number for each page?

```
        for (var i = 1; i <= doc.numPages; i++) {
            promise = promise.then(function (pageNum) {
                return doc.getPage(pageNum).then(function (pdfPage) {
                    // Create the page view.
                    var pdfPageView = new pdfjsViewer.PDFPageView({
                        container: container,
                        id: pageNum,
                        scale: DEFAULT_SCALE,
                        defaultViewport: pdfPage.getViewport({ scale: DEFAULT_SCALE, }),
                        annotationLayerFactory:
                            new pdfjsViewer.DefaultAnnotationLayerFactory(),
                        renderInteractiveForms: true,
                    });

                    // Associate the actual page with the view and draw it.
                    pdfPageView.setPdfPage(pdfPage);
                    return pdfPageView.draw();
                });
            }.bind(null, i));
        }
```

**Comment by timvandermeij** [comment]
It's not clear what you mean. Borders can be achieved with CSS on the `container` element. The page number is in the `pageNum` variable, so you can fill for example a `span` element with that data. Closing since this is mainly a bug tracker and not a general support forum.

**Comment by smit-modi** [comment]
I'm sorry I posted this here. Can you please redirect me to any support forum for PDFJS.

Also, by Border I meant, when I render pages. There is no line to separate two pages, just blank spaces.
I want borders around the page so I can differentiate between two pages.  

![image](https://user-images.githubusercontent.com/16932686/55361528-0f9c2200-549d-11e9-9fb2-808344d57d47.png)

**Comment by timvandermeij** [comment]
You should be able to achieve that with simple CSS styling on the `container` elements, i.e., a `border-top`/`border-bottom` styling may already be sufficient.
