### ISSUE TITLE
Add a trigger custom event when event bus is available.

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10718]
correct me if i am wrong, while perusing viewer.js i have come to the conclusion that to be able to know when the eventBus object is available, it would be good to have a custom event triggered and to which we can listen to so we can subscribe to those events registered in eventBus.

Would be a nice feature request. rather than having to modify viewer.js.

Thoughts?

**Comment by Snuffleupagus** [comment]
There's no need to implement anything here; this is already supported, albeit not as easily as you might wish.
(Note that we purposely don't want to re-dispatch all `EventBus` events to the DOM by default, since that adds unnecessary overhead for the default Firefox use-case.)

In a `GENERIC` build of the default viewer, simply listen for the [`viewerloaded` event](https://github.com/mozilla/pdf.js/blob/725a6959761883105d1b3c097aed30c841d41f83/web/viewer.js#L207-L214) e.g. like so:
```javascript
document.addEventListener('viewerloaded', function() {
  PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
});
```
That will re-dispatch all `EventBus` events globally, and you can then simply add a listener for the [`localized` event](https://github.com/mozilla/pdf.js/blob/725a6959761883105d1b3c097aed30c841d41f83/web/app.js#L168-L170) to be notified when the default viewer *itself* has been completely initialized.

**Comment by chitgoks** [comment]
i see. thank you for this @Snuffleupagus 

i forgot to mention that i was testing it using the beta v2.1 in anticipation for the next version. and there is no 'viewerloaded' so i am thinking that maybe this may not work come v2.1?

**Comment by Snuffleupagus** [comment]
> [...] and there is no 'viewerloaded' so i am thinking that maybe this may not work come v2.1?

That was a typo in https://github.com/mozilla/pdf.js/issues/10718#issuecomment-481175959, but if you actually looked at the linked code that would have been obvious :-)

**Comment by chitgoks** [comment]
ok. i have forgotten about webviewerloaded. will check it out

**Comment by Snuffleupagus** [comment]
Quoting from https://github.com/mozilla/pdf.js/issues/10718#issuecomment-481269593:

> Also, keep in mind that `eventBusDispatchToDOM` is a preference as well, so it might simply be overwritten once the preferences are read; see https://github.com/mozilla/pdf.js/blob/725a6959761883105d1b3c097aed30c841d41f83/web/app.js#L180-L184

**Comment by chitgoks** [comment]
ok . i tried to ignore that because i do not understand that part. but ill check it out. thank you for taking time to reply, even if i blurt out the same questions

**Comment by chitgoks** [comment]
@Snuffleupagus  hi jonas, i see the result now and you are correct. i manually set disablePreferences to false in viewer.js. is there a workaround to call this programmatically to set it to false? without having to re-call getDocument(). 

i think the options are set there.

**Comment by chitgoks** [comment]
@Snuffleupagus  hi jonas, i get what you mean now. i set disablePreferences to false in viewer.js and it works.

doing it programmatically PDFViewerApplicationOptions.set('disablePreferences', false);
wont work. could there be possible a workaround?

**Comment by Snuffleupagus** [comment]
> doing it programmatically PDFViewerApplicationOptions.set('disablePreferences', false);
> wont work. could there be possible a workaround

That's hardly surprising, given that the code I've quoted above clearly shows that it must be set to `true` for it to actually have any effect (and obviously it needs to be set in the `webviewerloaded` event listener, in the same way as  `eventBusDispatchToDOM`).

**Comment by chitgoks** [comment]
i actually placed it in the webviewerloaded event. i see what the problem was. i set it to false. it should be set to true. my mistake.

**Comment by diesel167** [comment]
```
document.addEventListener('webviewerloaded', function() {
  PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
});
```

this is not work for me. I have not fired webviewerloaded event (but i see that it was dispatched to document) ..

**Comment by garaboncias** [comment]
it seems eventBusDispatchToDOM option was removed:
https://github.com/mozilla/pdf.js/commit/ce1727626c8aa6e364e3b4929c72d50f711ef442
I found only this solution:
```
// pdfjs is used in an iframe, however "webviewerloaded" triggered on the original document
document.addEventListener('webviewerloaded', function initPdfViewer(event) {
let target = <Window>event["detail"].source;

// hide unnecessary buttons:
['#presentationMode', '#editorModeButtons', '#viewBookmark']
                    .forEach(selector => target.document.querySelector(selector)?.setAttribute('hidden', 'true'));

// set configuration
target['PDFViewerApplicationOptions'].set('printResolution', 600);
target['PDFViewerApplicationOptions'].set('enablePrintAutoRotate', false);

// trigger printing
target['PDFViewerApplication'].initializedPromise.then(() => {
                        target['PDFViewerApplication'].eventBus.on('pagesloaded', () => {
                            target['PDFViewerApplication'].eventBus.dispatch('print');
                        });
                    })
});
```
