### ISSUE TITLE
Big Https protocol file can't be downloaded 

### ISSUE THREAD

**Issue by todyhuang** [mozilla/pdf.js#10711]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
  IOS Mobile 
- Operating system and its version:
   windows 10 
- PDF.js version: 
  the newest one
- Is a browser extension:

Steps to reproduce the problem:
1. to view a big file(the link of this file is https protocol) online by PDF.JS . File size is around 100M, it seems the PDFJS will send two requests to the server as the following  screenshot.  The first request is try  to fetch the file using https as the file link is https, and somehow it finds the file size is large and there may be another request  to download the file ,however the second downloading request is using http protocol (not using https anymore,my file is link to the https protocol). 
2. 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
My webstie is using https protocol.If a file(the file address is https url) is to large, the PDFJS will send http(it seems something goes wrong here) request to download by the browser. When i debug,  the error can be easily discovered 
 " that request has been blocked;  content must be served over HTTPS " .
![image](https://user-images.githubusercontent.com/10398315/55543885-84b96280-56fc-11e9-91c5-a14ff20d4434.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
>     * PDF.js version:
>       the newest one

Please provide the *actual* version number when reporting an issue, since the information given doesn't really help. (Is it the latest stable version, the latest beta version, or the latest `master` version? Furthermore, what's "newest" can change quickly, making the information difficult to decipher.)

> My website is using https protocol.

As-is this issue is unfortunately not actionable, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
