### ISSUE TITLE
pdf is not rendering using pdf-viewer after custom build 

### ISSUE THREAD

**Issue by ku20043703** [mozilla/pdf.js#10729]
Configuration:
- Google Chrome 68.0.3440.75
- Windows10
- pdf.js.2.0.943

Steps to reproduce the problem:
1. I downloaded pdf.js-2.0.943 from git and then running gulp dist-install to build project as per below screenshots.
![image](https://user-images.githubusercontent.com/48914450/56027518-d3d24980-5d33-11e9-953c-b60eaf3f6379.png)

2. Afterwards I am copying all the files, folder from pdfjs-dist folder that is generated after gulp dist-install and then pasting into my project node-modules pdfjs-dist folder
![image](https://user-images.githubusercontent.com/48914450/56027765-4f33fb00-5d34-11e9-994e-bb25b582c8a8.png)

[pdfjs-dist.zip](https://github.com/mozilla/pdf.js/files/3072595/pdfjs-dist.zip)

@timvandermeij  Earlier pdf-viewer was able to show pdf with prebuilt pdfjs-dist. But Now after custom build as I explained you above its not showing pdf.

I attached pdfjs-dist folder that is generated after running build command.

I tried it for few days, but not sure what is going wrong. 

I am looking for your help on it. Your quick response will be very much helpful for me.

**Comment by Snuffleupagus** [comment]
> Earlier pdf-viewer was able to show pdf with prebuilt pdfjs-dist. But Now after custom build as I explained you above its not showing pdf.

Unfortunately it's simply impossible for anyone to assist, without access to a complete and runnable example (i.e. the code you wrote to actually call the PDF.js library/viewer); please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by ku20043703** [comment]
I didn't make any changes in pdf.js library, just downloaded and build it. and hence provided the zip of pdfjs-dist. and as earlier mentioned pdf rendering is working fine with prebuild pdf.js library. So, Hence by looking at zip can you suggest me what mistakes I could have done

**Comment by Snuffleupagus** [comment]
> So, Hence by looking at zip can you suggest me what mistakes I could have done

Keep in mind that this is first and foremost a *bug tracker*, and not a support forum.
Hence you need to provide *all* of the necessary information if you actually want someone to help you, and part of that is a *complete and runnable* example since it's not at all reasonable to expect anyone to look through many thousand lines of code to try and spot a possible error.

**Comment by dhyanaswain** [comment]
This is what I am also facing.
If I will add the prebuild pdf.js through NPM install, the required PDF files are working inside pdf-viewer, but If I am building the PDF-dist with or without changing anything in the code the required PDF files are not visible inside pdf-viewer.

**Comment by timvandermeij** [comment]
Closing since I agree with the comments from @Snuffleupagus above. It's simply not possible for us to assist with this without a runnable example. I can only suggest to try `gulp dist-install` since I'm not suring if pasting into `node_modules` works.
