### ISSUE TITLE
Reading custom ranges unit test fails intermittently

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10734]
The unit tests sometimes fail with the following line in the logs

```
TEST-UNEXPECTED-FAIL | read custom ranges | Expected 1016315 to equal 32768. Expected 1016315 to equal 507. 
```

We need to investigate why this happens. It only seems to happen on the Linux bot.

**Comment by Snuffleupagus** [comment]
> It only seems to happen on the Linux bot.

... and only in Chrome, as far as I can tell.

**Comment by timvandermeij** [comment]
This one also fails sometimes, most likely for the same reason:

```
TEST-UNEXPECTED-FAIL | read ranges with streaming | Expected 1016315 to equal 32768. Expected 1016315 to equal 507. 
```

**Comment by JulianoGTZ** [comment]
I can work on this issue :smile:

**Comment by Snuffleupagus** [comment]
> I can work on this issue

The information thus far doesn't suggest that this is a bug in the PDF.js library, given that it's specific to a particular browser *and* platform (i.e. Google Chrome on Linux).
Hence the best course of action, given the current state of this issue, would be to create a reduced test-case which reproduces this issue and then submit a bug to the Chromium project.

**Comment by JulianoGTZ** [comment]
Hi @Snuffleupagus. I will try to reproduce this error. Perhaps it has already been corrected indirectly.

**Comment by Snuffleupagus** [comment]
It's probably too early to call this fixed just yet, but this particular unit-test hasn't failed since Google Chrome was updated to version 80 on the bots. (It would be nice if the update actually fixed something, given the now intermittent reference tests :-)

**Comment by Snuffleupagus** [comment]
Should we just close this as WFM, since those unit-tests seem to be working correctly now?

**Comment by timvandermeij** [comment]
Yes, let's do that. We haven't seen it fail since the Chrome updates anymore.
