### ISSUE TITLE
Enabling links in minimal viewer

### ISSUE THREAD

**Issue by visick** [mozilla/pdf.js#10731]
I have used pdf.js to create a minimal viewer based on the "Hello World" example. My goal is to use display content from PDFs (which my users can create easily) in a Web page-like experience. Viewers won't need to interact with the PDF (zoom, search...), so this very minimal display is perfect!

However, the one feature I need is for URL links in the PDF to work. I feel like it should be possible to enable links without moving to something like viewer.js, but I've not yet been able to figure it out. Can anyone point me in the right direction? Thanks!

**Comment by Snuffleupagus** [comment]
To easily enable things like e.g. text/annotation layers you'll most likely want to use the "viewer components", which are intended as a basis for a custom viewer (and is also what powers the full [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html)); please refer to these examples: https://github.com/mozilla/pdf.js/tree/master/examples/components
