### ISSUE TITLE
Is there an option to flatten the pdf file?

### ISSUE THREAD

**Issue by phanisai4u** [mozilla/pdf.js#10737]
is this framework will flatten the PDF file, turning the form into a regular non editable pdf. Does this project offer such an option?

**Comment by Snuffleupagus** [comment]
What you're asking for would required *editing* of PDF files, which is clearly not in scope for the project as explained in the [README](https://github.com/mozilla/pdf.js#pdfjs-) and in the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations).
