### ISSUE TITLE
 Dynamically loading pdf  blurry, the same file official demo is very clear. I can't locate the problem

### ISSUE THREAD

**Issue by wolfmenwolf** [mozilla/pdf.js#10747]
Dynamically loading pdf blurry, the same file official demo is very clear. I can't locate the problem?

Use the chrome browser. Version 73.0.3683.86 (official version) (64-bit)
Here is my code：
async loadingPdf(getUint8Array, index) {

      let pdf = await pdfjsLib.getDocument({ data: getUint8Array, cMapUrl: cMapUrl, cMapPacked: cMapPacked  });
      let page = await pdf.getPage(1).then(page => {
        return page;
      });
      let canvas = document.getElementById("the-canvas" + index);

           var viewport = page.getViewport(1.7);
      if (canvas.dataset.runed) return;
      //var CSS_UNITS = 150.0/ 72.0;
      var CSS_UNITS =120.0/ 72.0;
      canvas.width = viewport.width*CSS_UNITS;
      canvas.height = viewport.height*CSS_UNITS;

    //  canvas.width = viewport.width;
   //   canvas.height = viewport.height;
      this.canvasW =
        this.canvasW > (1000 / viewport.height) * viewport.width
          ? this.canvasW
          : (1000 / viewport.height) * viewport.width;
      canvas.style.width = (1000 / viewport.height) * viewport.width;
      canvas.dataset.runed = true;
      var context = canvas.getContext('2d');

      context.mozImageSmoothingEnabled = false;
      context.webkitImageSmoothingEnabled = false;
      context.msImageSmoothingEnabled = false;
      context.imageSmoothingEnabled = false;
      await page.render({
        //enableWebGL: true,
        // canvasContext: context,
        transform: [CSS_UNITS, 0, 0, CSS_UNITS, 0, 0],
      //  transform: [1, 0, 0, 1, 0, 0],
        canvasContext: canvas.getContext("2d"),
        viewport: viewport
      });
      this.loadedPages.push(index)
    },

**Comment by wolfmenwolf** [comment]
I can't pinpoint the problem accurately, and reading all the source code obviously doesn't show up. So you need to help me take a look.

**Comment by Snuffleupagus** [comment]
When opening as issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and in this case please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md as well (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by wolfmenwolf** [comment]
Thank you, reply me in your busy schedule. I am looking at the content inside your connection. What is the detailed record? For example, what about code snippets, data json, network requests, etc?
