### ISSUE TITLE
Option to not use NodeJS Layer for loading files

### ISSUE THREAD

**Issue by hitmands** [mozilla/pdf.js#10741]
Configuration:
- Electron 4.0
- Any
- { "pdfjs-dist": "^2.1.266" }

Steps to reproduce the problem:
1. Set NodeIntegration to `true`
2. Observe how PdfJS loads files

Whenever pdf js detects the NodeJS Api, 
it uses it to retrieve files.

What is the expected behavior?
An option to set `Don't use the NodeJS layer for requesting files`

What went wrong?
Electron (NodeIntegration = true) exposes the NodeJS Api to the renderer thread, 
given that, pdfjs thinks of being into a NodeJS environment.

https://stackoverflow.com/questions/55683743/pdfjs-worker-electron-avoid-using-nodejs-for-requests

**Comment by hitmands** [comment]
https://github.com/mozilla/pdf.js/issues/10093

**Comment by hitmands** [comment]
By having a look here https://github.com/mozilla/pdf.js/pull/10681/files a fix has been merged, but apparently not released to the `pdfjs-dist` package.

![Screen Shot 2019-04-15 at 11 10 59](https://user-images.githubusercontent.com/5674833/56124765-4d09b080-5f6f-11e9-8986-7a35c7c6b2cc.png)

**Comment by timvandermeij** [comment]
Closing since this will be pushed to `pdfjs-dist` when the next release is made. It's not yet sure when this will be exactly; if you need it now, you'll have to patch it manually until the release is made.
