### ISSUE TITLE
Render canvas width and height as desktop

### ISSUE THREAD

**Issue by smit-modi** [mozilla/pdf.js#10745]
I am rendering an AcroForm in my web app. The rendered canvas size is same in desktop browsers. Even if I resize the window to small, the rendered canvas size remains same.

But when I render the same pdf in mobile or tablet the canvas size increases.
I want it to be same as the Desktop browser.

Please note, I do not want the fixed canvas size for all the pdfs. For respective pdf, I want the mobile's canvas size same as desktop's canvas size.

Following is rendered canvas in desktop:
`<canvas id="page1" moz-opaque="" width="794" height="1123" style="width: 794px; height: 1123px;"></canvas>`

Following is rendered canvas for the same pdf in mobile:
`<canvas id="page1" moz-opaque="" width="1925" height="2725" style="width: 794px; height: 1124px;"></canvas>`

The code I am using to render pdf is as below:
```
        pdfjsLib.workerSrc = "/js/Lib/pdf.worker.js";
        var DEFAULT_SCALE = 1.0;

        var container = document.getElementById('acroFormContainer');

        // Fetch the PDF document from the URL using promises.
        var loadingTask = pdfjsLib.getDocument(pathStringer);
        loadingTask.promise.then(function (doc) {
            // Use a promise to fetch and render the next page.
            var promise = Promise.resolve();
            pdfDoc = doc;

            for (var i = 1; i <= doc.numPages; i++) {
                promise = promise.then(function (pageNum) {
                    return doc.getPage(pageNum).then(function (pdfPage) {
                        // Create the page view.
                        var pdfPageView = new pdfjsViewer.PDFPageView({
                            container: container,
                            id: pageNum,
                            scale: DEFAULT_SCALE,
                            defaultViewport: pdfPage.getViewport({ scale: DEFAULT_SCALE, }),
                            annotationLayerFactory:
                                new pdfjsViewer.DefaultAnnotationLayerFactory(),
                            renderInteractiveForms: true,
                        });

                        // Associate the actual page with the view and draw it.
                        pdfPageView.setPdfPage(pdfPage);
                        return pdfPageView.draw();
                    });
                }.bind(null, i));
            }
        });
```
The snapshot when I click inspect element of the rendered canvas:
Desktop:
![Desktop3](https://user-images.githubusercontent.com/16932686/56295139-ebbe1a80-60f1-11e9-8030-f1476cc8a637.png)

Mobile:
![mobile3](https://user-images.githubusercontent.com/16932686/56295168-f4165580-60f1-11e9-8022-63efba5d860e.png)

Attach (recommended) or Link to PDF file here: http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf

Configuration:
- Web browser and its version: FireFox 66.0.2 
- Operating system and its version: Windows 10 Pro
- PDF.js version: 2.1.262
- Is a browser extension: No

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, and not a support forum; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
The difference between the two widths and heights is a factor 2.4 (for example, divide 2725 by 1123). This is most likely the device pixel ratio. You might need to take a look at https://github.com/mozilla/pdf.js/blob/c0d6e46e392b327996eb0964b7932cb5bdde1727/web/ui_utils.js#L94 and its usages to resolve this.
