### ISSUE TITLE
PDF file appearing blank Blank or missing some objects

### ISSUE THREAD

**Issue by Narender1990** [mozilla/pdf.js#10751]
Attach (recommended) or Link to PDF file here:
Production PDF Invoice: could not share.

Configuration:
- Web browser and its version: 
**Chrome**: Version 73.0.3683.103 (Official Build) (64-bit)
**Mozilla Firefox**: 65.0 (64-bit)
**Internet Explorer**: 11.1029.16299.0

- Operating system and its version: Windows 10 x64 (Version 1709, OS Build 16299.1029)

- PDF.js version:
PSD JS: 1.8.888 stable version
PDF JS: 2.0.943

- Is a browser extension: No

Steps to reproduce the problem:
1.  If we open the PDF file in PDF JS version 1.8.888 which deployed to production server. We get the blank page. Please see the screen shot.

2. If we open the PDF file in PDF JS version 2.0.943. Page is loading but some of the some content is missing.

What is the expected behavior? (add screenshot)
Missing content shall appear in the latest PDF JS viewer.

What went wrong? (add screenshot)
Info captured from developer tool.
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
viewer.html
HTML1300: Navigation occurred.
viewer.html
HTML1202: https://dummy-url/viewer.html?file=./ImageCache/20190402EM0142100001.pdf is running in Compatibility View because 'Display intranet sites in Compatibility View' is checked.
viewer.html
https://dummy-url/locale/locale.properties not found.
"en-us" resource not found
#thumbs is undefined.
#thumbs is undefined.
#thumbs_label is undefined.
#thumbs_label is undefined.
#outline is undefined.
#outline is undefined.
#outline_label is undefined.
#outline_label is undefined.
#attachments is undefined.
#attachments is undefined.
#attachments_label is undefined.
#attachments_label is undefined.
#find_label is undefined.
#find_label is undefined.
#find_previous is undefined.
#find_previous is undefined.
#find_previous_label is undefined.
#find_previous_label is undefined.
#find_next is undefined.
#find_next is undefined.
#find_next_label is undefined.
#find_next_label is undefined.
#find_highlight is undefined.
#find_highlight is undefined.
#find_match_case_label is undefined.
#find_match_case_label is undefined.
#presentation_mode is undefined.
#presentation_mode is undefined.
#presentation_mode_label is undefined.
#presentation_mode_label is undefined.
#open_file is undefined.
#open_file is undefined.
#open_file_label is undefined.
#open_file_label is undefined.
#print is undefined.
#print is undefined.
#print_label is undefined.
#print_label is undefined.
#download is undefined.
#download is undefined.
#download_label is undefined.
#download_label is undefined.
#bookmark is undefined.
#bookmark is undefined.
#bookmark_label is undefined.
#bookmark_label is undefined.
#first_page is undefined.
#first_page is undefined.
#first_page_label is undefined.
#first_page_label is undefined.
#last_page is undefined.
#last_page is undefined.
#last_page_label is undefined.
#last_page_label is undefined.
#page_rotate_cw is undefined.
#page_rotate_cw is undefined.
#page_rotate_cw_label is undefined.
#page_rotate_cw_label is undefined.
#page_rotate_ccw is undefined.
#page_rotate_ccw is undefined.
#page_rotate_ccw_label is undefined.
#page_rotate_ccw_label is undefined.
#hand_tool_enable is undefined.
#hand_tool_enable is undefined.
#hand_tool_enable_label is undefined.
#hand_tool_enable_label is undefined.
#document_properties is undefined.
#document_properties is undefined.
#document_properties_label is undefined.
#document_properties_label is undefined.
#toggle_sidebar is undefined.
#toggle_sidebar is undefined.
#toggle_sidebar_label is undefined.
#toggle_sidebar_label is undefined.
#findbar is undefined.
#findbar is undefined.
#findbar_label is undefined.
#findbar_label is undefined.
#previous is undefined.
#previous is undefined.
#previous_label is undefined.
#previous_label is undefined.
#next is undefined.
#next is undefined.
#next_label is undefined.
#next_label is undefined.
#page_label is undefined.
#page_label is undefined.
#presentation_mode is undefined.
#presentation_mode is undefined.
#presentation_mode_label is undefined.
#presentation_mode_label is undefined.
#open_file is undefined.
#open_file is undefined.
#open_file_label is undefined.
#open_file_label is undefined.
#print is undefined.
#print is undefined.
#print_label is undefined.
#print_label is undefined.
#download is undefined.
#download is undefined.
#download_label is undefined.
#download_label is undefined.
#bookmark is undefined.
#bookmark is undefined.
#bookmark_label is undefined.
#bookmark_label is undefined.
#tools is undefined.
#tools is undefined.
#tools_label is undefined.
#tools_label is undefined.
#zoom_out is undefined.
#zoom_out is undefined.
#zoom_out_label is undefined.
#zoom_out_label is undefined.
#zoom_in is undefined.
#zoom_in is undefined.
#zoom_in_label is undefined.
#zoom_in_label is undefined.
#zoom is undefined.
#zoom is undefined.
#page_scale_auto is undefined.
#page_scale_auto is undefined.
#page_scale_actual is undefined.
#page_scale_actual is undefined.
#page_scale_fit is undefined.
#page_scale_fit is undefined.
#page_scale_width is undefined.
#page_scale_width is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#page_scale_percent is undefined.
#first_page is undefined.
#first_page is undefined.
#last_page is undefined.
#last_page is undefined.
#page_rotate_cw is undefined.
#page_rotate_cw is undefined.
#page_rotate_ccw is undefined.
#page_rotate_ccw is undefined.
#error_more_info is undefined.
#error_more_info is undefined.
#error_less_info is undefined.
#error_less_info is undefined.
#error_close is undefined.
#error_close is undefined.
#password_label is undefined.
#password_label is undefined.
#password_cancel is undefined.
#password_cancel is undefined.
#password_ok is undefined.
#password_ok is undefined.
#document_properties_file_name is undefined.
#document_properties_file_name is undefined.
#document_properties_file_size is undefined.
#document_properties_file_size is undefined.
#document_properties_title is undefined.
#document_properties_title is undefined.
#document_properties_author is undefined.
#document_properties_author is undefined.
#document_properties_subject is undefined.
#document_properties_subject is undefined.
#document_properties_keywords is undefined.
#document_properties_keywords is undefined.
#document_properties_creation_date is undefined.
#document_properties_creation_date is undefined.
#document_properties_modification_date is undefined.
#document_properties_modification_date is undefined.
#document_properties_creator is undefined.
#document_properties_creator is undefined.
#document_properties_producer is undefined.
#document_properties_producer is undefined.
#document_properties_version is undefined.
#document_properties_version is undefined.
#document_properties_page_count is undefined.
#document_properties_page_count is undefined.
#document_properties_close is undefined.
#document_properties_close is undefined.
#page_of is undefined.
PDF 00e8497a9fa7aaedc98166064a2331a0 [1.2 - / -] (PDF.js: 1.8.188)
#thumb_page_title is undefined.
Error: XObject should be a stream
   at error (https://dummy-url/build/pdf.worker.js:340:5)
   at assert (https://dummy-url/build/pdf.worker.js:353:5)
   at promiseBody (https://dummy-url/build/pdf.worker.js:15822:17)
   at Promise (https://dummy-url/build/pdf.worker.js:37694:9)
   at PartialEvaluator_getOperatorList (https://dummy-url/build/pdf.worker.js:15781:7)
   at Anonymous function (https://dummy-url/build/pdf.worker.js:26214:9)
   at runHandlers (https://dummy-url/build/pdf.worker.js:37620:17)
Error: XObject should be a stream
   at error (https://dummy-url/build/pdf.worker.js:340:5)
   at assert (https://dummy-url/build/pdf.worker.js:353:5)
   at promiseBody (https://dummy-url/build/pdf.worker.js:16385:15)
   at Promise (https://dummy-url/build/pdf.worker.js:37694:9)
   at PartialEvaluator_getTextContent (https://dummy-url/build/pdf.worker.js:16217:7)
  at Anonymous function (https://dummy-url/build/pdf.worker.js:26254:9)
   at runHandlers (https://dummy-url/build/pdf.worker.js:37620:17)
Unhandled rejection: Error: XObject should be a stream
Unhandled rejection: Error: XObject should be a stream
Error: XObject should be a stream
   at error (https://dummy-url/build/pdf.worker.js:342:3)
   at assert (https://dummy-url/build/pdf.worker.js:353:5)
   at promiseBody (https://dummy-url/build/pdf.worker.js:15822:17)
   at Promise (https://dummy-url/build/pdf.worker.js:37694:9)
   at PartialEvaluator_getOperatorList (https://dummy-url/build/pdf.worker.js:15781:7)
   at Anonymous function (https://dummy-url/build/pdf.worker.js:26214:9)
   at runHandlers (https://dummy-url/build/pdf.worker.js:37620:17)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> Production PDF Invoice: could not share.

All of the other information provided below is unfortunately of no use without access to a test-case, and as-is the issue will be closed as INCOMPLETE.
Please try to either create a PDF file without sensitive information (using the same PDF software), or attempt to redact parts of the original PDF file, such that an test-case be provided.

> If we open the PDF file in PDF JS version 1.8.888 which deployed to production server. We get the blank page. Please see the screen shot.

Please note that that version is no longer supported, and only the versions marked either `Pre-release` or `Latest release` at https://github.com/mozilla/pdf.js/releases are officially supported.

> What went wrong? (add screenshot)
> Info captured from developer tool.
> DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
> ...

Since this indicates that IE11 was used, please note its limited support status as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by timvandermeij** [comment]
Closing since this is not actionable without a PDF file. If you can provide a file without sensitive information, we can reopen this.

**Comment by dylanwoo** [comment]
The effect is very similar to this ticket as well: https://github.com/mozilla/pdf.js/issues/10806
