### ISSUE TITLE
Pdfjs In safari, if there is a watermark, it can't be loaded

### ISSUE THREAD

**Issue by caihuoche** [mozilla/pdf.js#10752]
Configuration:

Web browser and its version:
   safari Any version
Operating system and its version:
   centos 7
PDF.js version:
   v2.0.943
Steps to reproduce the problem: 1. 2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/24805030/56420965-dd7b2480-62d2-11e9-801f-491c0db1b9f1.png)
This is the normal display of Google Chrome.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/24805030/56421027-321e9f80-62d3-11e9-8962-95d8e8c8634d.png)
This is in safari, by comparing Google Chrome, you can see too many loaded components, as shown in the red circle, if I delete these two components on the server, then the file can be displayed normally, but there is no Watermark

Pdfjs In safari, if there is a watermark, it can't be loaded, and the loading is very slow. It can be seen from the network that it is the reason of two components (UniGB-UTF16-H.bcmap, Adobe-GB1-UCS2.bcmap), how can I solve it?

**Comment by Snuffleupagus** [comment]
This is still missing *crucial* details in order to be actionable (and why open a duplicate issue?); without access to a test-case the issue will be closed as INCOMPLETE.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Please don't open duplicate issues. You can provide the necessary details here and we'll reopen it.
