### ISSUE TITLE
How do I combine the loader function of the official website demo with the loading that I wrote myself.

### ISSUE THREAD

**Issue by wolfmenwolf** [mozilla/pdf.js#10757]
Hello, everyone. How do I combine the loader function of the official website demo with the loading that I wrote myself? The official website dome loader code is as follows:
`function webViewerLoad() {
  let config = getViewerConfiguration();
  if (typeof PDFJSDev === 'undefined' || !PDFJSDev.test('PRODUCTION')) {
    Promise.all([
      SystemJS.import('pdfjs-web/app'),
      SystemJS.import('pdfjs-web/app_options'),
      SystemJS.import('pdfjs-web/genericcom'),
      SystemJS.import('pdfjs-web/pdf_print_service'),
    ]).then(function([app, appOptions, ...otherModules]) {
      window.PDFViewerApplication = app.PDFViewerApplication;
      window.PDFViewerApplicationOptions = appOptions.AppOptions;
      app.PDFViewerApplication.run(config);
    });
  } else {
    if (typeof PDFJSDev !== 'undefined' && PDFJSDev.test('CHROME')) {
      pdfjsWebAppOptions.AppOptions.set('defaultUrl', defaultUrl);
    }

    window.PDFViewerApplication = pdfjsWebApp.PDFViewerApplication;
    window.PDFViewerApplicationOptions = pdfjsWebAppOptions.AppOptions;

    if (typeof PDFJSDev !== 'undefined' && PDFJSDev.test('GENERIC')) {
      // Give custom implementations of the default viewer a simpler way to
      // set various `AppOptions`, by dispatching an event once all viewer
      // files are loaded but *before* the viewer initialization has run.
      const event = document.createEvent('CustomEvent');
      event.initCustomEvent('webviewerloaded', true, true, {});
      document.dispatchEvent(event);
    }

    pdfjsWebApp.PDFViewerApplication.run(config);
  }
}

if (document.readyState === 'interactive' ||
    document.readyState === 'complete') {
  webViewerLoad();
} else {
  document.addEventListener('DOMContentLoaded', webViewerLoad, true);
}
`

My own loading code is as follows:
`async loadingPdf(getUint8Array, index) {
    let pdf =  await pdfjsLib.getDocument({ data: getUint8Array, cMapUrl: cMapUrl, cMapPacked: cMapPacked  })
      let page = await pdf.getPage(1).then(page => {
        return page;
      });
      let canvas = document.getElementById("the-canvas" + index);

           var viewport = page.getViewport(1.7);
      if (canvas.dataset.runed) return;
      //var CSS_UNITS = 150.0/ 72.0;
      var CSS_UNITS =120.0/ 72.0;
      canvas.width = viewport.width*CSS_UNITS;
      canvas.height = viewport.height*CSS_UNITS;

    //  canvas.width = viewport.width;
   //   canvas.height = viewport.height;
      this.canvasW =
        this.canvasW > (1000 / viewport.height) * viewport.width
          ? this.canvasW
          : (1000 / viewport.height) * viewport.width;
      canvas.style.width = (1000 / viewport.height) * viewport.width;
      canvas.dataset.runed = true;
      var context = canvas.getContext('2d');
      context.mozImageSmoothingEnabled = false;
      context.webkitImageSmoothingEnabled = false;
      context.msImageSmoothingEnabled = false;
      context.imageSmoothingEnabled = false;
      await page.render({
        //enableWebGL: true,
        // canvasContext: context,
        transform: [CSS_UNITS, 0, 0, CSS_UNITS, 0, 0],
      //  transform: [1, 0, 0, 1, 0, 0],
        canvasContext: canvas.getContext("2d"),
        viewport: viewport
      });
      this.loadedPages.push(index);
      
    },`

**Comment by timvandermeij** [comment]
You need to fill out the issue template from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since only code snippets, as stated in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, won't help to find the problem. It's also not clear what the problem is: what does "combining" mean? You can always customize the existing code to fit your requirements.
