### ISSUE TITLE
unwanted horizontal lines on pdf file in browser

### ISSUE THREAD

**Issue by KiranWorks1061** [mozilla/pdf.js#10758]
Configuration:
- Web browser and its version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- PDF.js version: 2.0.493
- Is a browser extension: No

What went wrong? (add screenshot)
Showing unwanted horizontal lines in page #3 in pdf

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://esjp-uat.devtpit.com/viewer.html?file=jpdocs/PR/200016_PR_JP.pdf#page=3

**Comment by KiranWorks1061** [comment]
Can anyone help on this?

**Comment by janpe2** [comment]
Page 3 contains many 1-bit images that have `/Filter /CCITTFaxDecode` and `/ImageMask true`. The images are supposed to be completely transparent but in PDF.js a black line appears at the bottom of each image. I think there is a bug in the decoder [src/core/ccitt.js](https://github.com/mozilla/pdf.js/blob/master/src/core/ccitt.js). The images have also `/EncodedByteAlign true`, which could be the culprit.

**Comment by Snuffleupagus** [comment]
> http://esjp-uat.devtpit.com/viewer.html?file=jpdocs/PR/200016_PR_JP.pdf#page=3
>
> Page 3 contains many 1-bit images that have `/Filter /CCITTFaxDecode` and `/ImageMask true`.

It appears that the PDF document changed on the server (which is why we recommend *attaching* it, rather than just linking), since the third page no longer contains any /CCITTFaxDecode images; closing as INCOMPLETE for now.
