### ISSUE TITLE
How can I transfer multiple Uint8Arrays to pdfjsLib. getDocument?

### ISSUE THREAD

**Issue by cyfour** [mozilla/pdf.js#10766]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:2.2.0
- Is a browser extension:

Steps to reproduce the problem:
1. How can I transfer multiple Uint8Arrays to pdfjsLib. getDocument?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You can't. `getDocument` only opens one document. If you need to open more than one document, you need more `getDocument` calls.

**Comment by cyfour** [comment]
If I want to open multiple uint8 arrays in viewer. html, do I want to modify the PDFViewer Application? Can you provide some ideas?

**Comment by timvandermeij** [comment]
You can, but it all depends on your use case. If you want to display multiple documents at once, you also need another way of presenting the documents to the user, or use multiple iframes for example.

**Comment by cyfour** [comment]
thank you very much.
