### ISSUE TITLE
Ctrl-wheel zooming also scales UI in Chrome

### ISSUE THREAD

**Issue by kuro68k** [mozilla/pdf.js#10761]
Attach (recommended) or Link to PDF file here: Any PDF will work

Configuration:
- Web browser and its version: Chrome 73.0.3683.103 x64
- Operating system and its version: Windows 10 Pro x64
- PDF.js version: 2.0.673
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open any PDF
2. Hold CTRL key and use mouse wheel to zoom in/out

What is the expected behavior? (add screenshot)

Document is zoomed in/out

What went wrong? (add screenshot)

The PDF reader UI is also scaled. It appears that Chrome is also zooming the entire page, including the PDF reader UI, as well as the PDF reader also zooming the document.

In previous versions only the document would be zoomed.

![image](https://user-images.githubusercontent.com/2674466/56653098-d5c9d000-6684-11e9-907b-8c3cead170cf.png)

Note how the PDF viewer UI is scaled in this image. It can also be made absurdly small by zooming out:

![image](https://user-images.githubusercontent.com/2674466/56653304-4a9d0a00-6685-11e9-8b3d-d7d1de148c7f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by Snuffleupagus** [comment]
> In previous versions only the document would be zoomed.

It's not clear what "previous versions" refer to here, but this its actually a case where the Chrome *browser* itself is unfortunately breaking web compatibility; see https://developers.google.com/web/updates/2019/02/scrolling-intervention for additional details.

Generally speaking this cannot be "fixed", or rather worked-around since it's not our fault, in the PDF.js default viewer since we still support IE11 for the time being, which according to https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Browser_compatibility doesn't support the `options` object format in `addEventListener` calls.

**Comment by kuro68k** [comment]
Sorry, previous version of Chrome.

If I understand you are saying that adding `{passive: true}` would fix it, but you can't do that because it would break Internet Explorer. That's unfortunate as I rate the probability of Google relenting or Microsoft fixing IE11 as 0%.

I will attempt to fork to see if I can fix the problem based on your suggestion. Thank you.

**Comment by kuro68k** [comment]
Fork with fix here: https://github.com/kuro68k/pdf.js

**Comment by kuro68k** [comment]
I made a fixed version available for Chrome here: https://chrome.google.com/webstore/detail/pdf-viewer/khoagkdmmnmmimpmdbeapnlmkkiiikae

**Comment by timvandermeij** [comment]
The problem should be fixed by the pull request above and will be in the next release. Maybe a Chrome extension update can already be done (/cc @Rob--W for that)? That way no fork/other extension than the official one should be necessary.

**Comment by kuro68k** [comment]
Well, I should be happy it's being fixed at least. I'll pull mine once it's out.

**Comment by Rob--W** [comment]
I'll include a fix for #10645 and then publish the update.

**Comment by Rob--W** [comment]
I published an update as https://github.com/Rob--W/pdf.js/releases/tag/chrome-2.2.191
