### ISSUE TITLE
in SSR Page, nodeJS import pdfjs-dist throw error

### ISSUE THREAD

**Issue by codeInCat** [mozilla/pdf.js#10767]
nodejs.ReferenceError: Element is not defined
    at checkChildNodeRemove (/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/shared/compatibility.js:82:3)

**Comment by timvandermeij** [comment]
You really need to fill out the issue template from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md in order for this to be actionable, since we cannot help without any steps to reproduce.
