### ISSUE TITLE
Clarity issue or blur fonts when not zoomed

### ISSUE THREAD

**Issue by afsinak** [mozilla/pdf.js#10769]
Configuration:
![Screenshot 2019-04-26 at 12 25 00 PM](https://user-images.githubusercontent.com/46594945/56788946-57089a80-681e-11e9-8555-7c7a6ba7c33d.png)

the small fonts should be little more clear. Its not clear at all

A quick response would be highly appreciated. thanks in advance

**Comment by THausherr** [comment]
Please include the information requested in the template.

**Comment by timvandermeij** [comment]
You need to provide all information from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md in order for us to be able to help.
