### ISSUE TITLE
Error: Cannot find module '@webassemblyjs/ast'

### ISSUE THREAD

**Issue by mkubdev** [mozilla/pdf.js#10779]
Hello, i'm trying to test pdf.js but i can't use the demo viewer.  It seem like dependencies not working. 

**What i already test:**
- I tried to re-install nodeJS : no-effect
- I tried to rm -rf node_modules and package-lock.json then npm install : no-effect
- I tried to clear cache -f : no-effect
- I tried to rm -rf node_modules and package-lock.json, then npm install @webassemblyjs then npm install : no-effect

**Configuration:**
- Web browser and its version: Version 74.0.3729.108 (Build officiel) (64 bits)
- Operating system and its version: Windows 10 NT
- PDF.js version: latest
- Is a browser extension: no
- Node 10.15.3 
- NPM 6.4.1 
- Gulp 4.0.1.

**Steps to reproduce the problem:**
1. git clone https://github.com/mozilla/pdf.js
2. cd pdf.js
3. npm install -g gulp-cli

4. npm install

There are some Warning here : 

 ` $ canvas@2.4.1 install C:\denv\trunk\thirdparty\pdfjs\pdf.js\node_modules\canvas
   $ node-pre-gyp install --fallback-to-build`

`node-pre-gyp WARN Using needle for node-pre-gyp https download
[canvas] Success: "C:\....\pdf.js\node_modules\canvas\build\Release\canvas.node" is installed via remote`

`$ uglifyjs-webpack-plugin@0.4.6 postinstall C:\....\pdfjs\pdf.js\node_modules\uglifyjs-webpack-plugin
 $ node lib/post_install.js`

`npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN uglifyjs-webpack-plugin@0.4.6 requires a peer of webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

5. gulp server

`internal/modules/cjs/loader.js:584`
    `throw err;
    ^`

`Error: Cannot find module '@webassemblyjs/ast'`
    `at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\denv\trunk\thirdparty\pdfjs\pdf.js\node_modules\webpack\lib\wasm\WebAssemblyParser.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)`

The build is working on another computer, but mine he doesn't. Can you help me?

Best regards

**Comment by Snuffleupagus** [comment]
> The build is working on another computer, but mine he doesn't. Can you help me?

The fact that it's, by your own account, specific to a *particular computer* probably means that it's very difficult for anyone to assist from a distance (especially since there's been no similar reports).
