### ISSUE TITLE
lack of documentation for mobile viewer - open local pdf

### ISSUE THREAD

**Issue by arturgromek** [mozilla/pdf.js#10781]
I've got the mobile viewer running, but am having trouble passing the path of the file to the viewer.

It seems like the ?file= bit doesn't get checked anywhere on the mobile viewer.

I pass this as the source to a webview: file:///android_asset/pdfjs/mobile-viewer/viewer.html?file=/data/user/0/***/files/dummy.pdf

But the viewer opens whatever is set as the DEFAULT_URL in viewer.js, no matter what i pass to the webview.

When I set the DEFAULT_URL to the path of my file (/data/user/0/***/files/dummy.pdf) it opens the pdf as expected(first screenshot below). So the path and file seem to be ok.

I have tried encoding the url, but no luck there either.

Worth noting that I have been able to set the path using the default viewer, in that case I encoded the path.

Link to PDF file here(Note that I have downloaded this pdf to the device): https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

Configuration:
- Web browser and its version: Android webview browser
- Operating system and its version: Android 8.1
- PDF.js version: v2.2.156 build: f87dc427
- Is a browser extension: No

Steps to reproduce the problem:
1. Use mobile browser, and pass path of local file with ?file=[path to file]
2. file not shown

What is the expected behavior? (add screenshot)
![Screenshot_1556772261](https://user-images.githubusercontent.com/38743338/57057041-b1f03500-6ce9-11e9-8090-4ea43c1f6383.png)

What went wrong? (add screenshot)
![Screenshot_1556772327](https://user-images.githubusercontent.com/38743338/57057042-b6b4e900-6ce9-11e9-8bbd-253a27092a1c.png)

**Comment by Snuffleupagus** [comment]
> I've got the mobile viewer running, but am having trouble passing the path of the file to the viewer.

If by "the mobile viewer" you are referring to the example found at https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer, then that is as mentioned a mere *example* which can be used as a basis for building a custom viewer.

> It seems like the ?file= bit doesn't get checked anywhere on the mobile viewer.

More advanced features, such as the one mentioned, will need to be implemented by the person that's using the example viewer. (You may be able to draw some inspiration from the "default viewer", i.e. https://github.com/mozilla/pdf.js/blob/master/web/app.js)
