### ISSUE TITLE
Options doesn't work when try to get PDF from service API

### ISSUE THREAD

**Issue by hareramjha2007** [mozilla/pdf.js#10786]
Hi,

**Problem Description:**
I am trying to get the PDF from service by calling controller action. This works fine when I don't add option/parameter (e.g zoom, page etc.). 
**Working example:**
<iframe src="~/pdfjs/web/viewer.html?file=/api/[controller]/[action]?[parameter]">

When I try to add optional parameter for viewer then controller action doesn't gets called (probably file* attribute getting removed from URL). 
**Example**
<iframe src="~/pdfjs/web/viewer.html#zoom=50?file=/api/[controller]/[action]?[parameter]">

Please help me to resolve this issue.

Configuration:
- Web browser and its version: Chrome, Edge etc.
- Operating system and its version: Windows 10
- PDF.js version: Latest as on date.
- Is a browser extension: No

Steps to reproduce the problem:
1. Create any Asp.net core project and add iFrame on page.
2. Add controller and action to return you PDF(File Stream) reading from local directory or from web
3. Use above controller action to call from iFrame source. e.g. file=/api/..
4. Run the application to get result

What is the expected behavior? (add screenshot)
API call should be executed to get PDF(File Stream) and render to the UI as it is working when you don't add options.

What went wrong? (add screenshot)
Doesn't load PDF/document.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Non

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
