### ISSUE TITLE
Print misses first character of words

### ISSUE THREAD

**Issue by wagnerand** [mozilla/pdf.js#10787]
Attach (recommended) or Link to PDF file here: http://www-sop.inria.fr/members/Doliere.Some/papers/empoweb.pdf

Configuration:
- Web browser and its version: 67.0b15 (64-bit) 
- Operating system and its version: macOS 10.14.4
- PDF.js version: whatever Firefox uses
- Is a browser extension: no

Steps to reproduce the problem:
1. Open above PDF
2. Print it do a printer
3. Check print

What is the expected behavior? (add screenshot)

Print shows all characters

What went wrong? (add screenshot)

Random characters are missing throughout the entire document. For example in the title the character _A_ of _Applications_ is missing.

Downloading that PDF and printing from macOS Preview shows all characters just fine.

**Comment by timvandermeij** [comment]
Closing since this is fixed now. Most likely this is/was either an upstream issue that got fixed.
