### ISSUE TITLE
Following Getting the code but not able to open a PDF on IE11

### ISSUE THREAD

**Issue by iamankushpandit** [mozilla/pdf.js#10780]
Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 10 
- PDF.js version: latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Follow https://github.com/mozilla/pdf.js#getting-the-code. 
2. Run gulp server.
3. Open http://localhost:8888/web/viewer.html on IE 11
4. Page loads but buttons like Open file are not operational and no PDFs loaded.
5. Run the interactive demo https://mozilla.github.io/pdf.js/web/viewer.html on IE 11 it works absolutely fine.

What is the expected behavior? http://localhost:8888/web/viewer.html or pdfjs viewer  should work as https://mozilla.github.io/pdf.js/web/viewer.html on IE 11.

What went wrong? (add screenshot)
Page loads but buttons like Open file are not operational and no PDFs loaded.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Follow https://github.com/mozilla/pdf.js#getting-the-code.

Please actually read *all* of that section, since it contains the following information (which perfectly explains the situation you're facing):
> Please keep in mind that this requires an ES6 compatible browser; refer to Building PDF.js for usage with older browsers.

Furthermore, please also note that support for IE11 is limited in general; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
