### ISSUE TITLE
When converting to SVG the "fill-opacity: 1" attribute should not be added if the "fill" attribute is missing

### ISSUE THREAD

**Issue by HydraOrc** [mozilla/pdf.js#10796]
Attach (recommended) or Link to PDF file here:
 [http://www.mediafire.com/file/jz26jy0zz326pw3/hypothermia-prevention-and-management-in-adults-having-surgery-update+Dec2016.pdf](http://www.mediafire.com/file/jz26jy0zz326pw3/hypothermia-prevention-and-management-in-adults-having-surgery-update+Dec2016.pdf)

Configuration:
- Web browser and its version: Google Chrome 73.0.3683.103 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 18.04
- PDF.js version: "pdfjs-dist": "~2.0.943"
- Is a browser extension: No

Steps to reproduce the problem:
1. Upload and convert the pdf file to SVG.

What is the expected behavior?
Create the svg file without the "fill-opacity: 1" attribute since the "fill" attribute is missing.

What went wrong? (add screenshot)
The pages from 2 to the last have the "fill-opacity: 1" attribute, but do not have the "fill" attribute, so the browser paints all these pages into black color by default: [https://www.dropbox.com/s/fgrcdr5573cwf81/Screen%20Shot%202019-05-02%20at%2015.37.21.png?dl=0](https://www.dropbox.com/s/fgrcdr5573cwf81/Screen%20Shot%202019-05-02%20at%2015.37.21.png?dl=0)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): None

**Comment by janpe2** [comment]
This issue is caused by the fact that tiling patterns have not been implemented in the SVG back-end. The background of the pages contains a tiling pattern that fills the whole page with white and draws the horizontal header and footer lines. 

https://github.com/mozilla/pdf.js/blob/fef86cc3e327f0554136482fee901b52909fa37a/src/display/svg.js#L983-L989

Because `null` is returned, `<path>` elements won't have any `fill` attribute and the default value `fill="black"` makes the pages black.

**Comment by HydraOrc** [comment]
I am sorry, but looks like we are talking about different parts of the library?
```
import pdfjsLib from 'pdfjs-dist';

pdfjsLib.getDocument({
              data,
              disableFontFace: true,
              verbosity: 0,
            }).then((pdf) => {
              const numPages = pdf.numPages;

              let lastPromise = Promise.resolve(); // will be used to chain promises

              const loadPage = (pageNum) => {
                return pdf.getPage(pageNum).then((page) => {
                  const viewport = page.getViewport(1.0 /* scale */);

                  return page.getOperatorList().then((opList) => {
                    const svgGfx = new pdfjsLib.SVGGraphics(page.commonObjs, page.objs);

                    svgGfx.embedFonts = true;

                    return svgGfx.getSVG(opList, viewport).then((svgFile) => {
                    ...
```
And the final svgFile contains the problem described.
