### ISSUE TITLE
PDF loading but not displaying inside Xamarin Android WebView

### ISSUE THREAD

**Issue by NextAlexM** [mozilla/pdf.js#10798]
**Configuration:**
- Web browser and its version: Chrome? Default Android WebView on a Samsung Galaxy Tab A (2016)
- Operating system and its version: Android 8.1.0
- PDF.js version: 2.0.943
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Clone solution (https://github.com/NextAlexM/PdfApp)
2. Open "PdfApp.sln"
3. Restore nuget packages
4. Run "PdfApp.Android" on an Android device

**What is the expected behavior?**
PDF loads and displays
[Screenshot](https://raw.githubusercontent.com/NextAlexM/PdfApp/master/WorkingPdf.png)

**What went wrong?**
PDF loads but doesn't display
[Screenshot](https://raw.githubusercontent.com/NextAlexM/PdfApp/master/NonWorkingPdf.png)

**Link to a viewer:**
https://github.com/NextAlexM/PdfApp

**Comment by timvandermeij** [comment]
Could you check if there is anything in the web console (warnings/errors)?

**Comment by NextAlexM** [comment]
> Could you check if there is anything in the web console (warnings/errors)?

Sorry forgot to include this:
[Remote Chrome Console Log](https://raw.githubusercontent.com/NextAlexM/PdfApp/master/RemoteChromeConsoleLog.txt)

Last line shows the PDF has loaded:
`viewer.js:1291 PDF a542b7ae69a71147a88b29253c4b493c [1.5 Microsoft® Word 2013 / Microsoft® Word 2013] (PDF.js: 2.0.943)`

One interesting thing I've noticed is by removing `overflow: auto;` from `#viewerContainer` the page appears:
[https://raw.githubusercontent.com/NextAlexM/PdfApp/master/LoadingPdf.png](https://raw.githubusercontent.com/NextAlexM/PdfApp/master/LoadingPdf.png)

In this case it's showing a loading spinner for each page in the PDF but i've seen it display the pages correctly before (will try and get a screenshot of this)



Another point to note is this works on older version of Xamarin and lower Android targets. We originally followed [this guide](https://github.com/xamarin/docs-archive/tree/master/Recipes/xamarin-forms/Controls/display-pdf) but they are targeting a much lower version of Xamarin and Android.

**Comment by Snuffleupagus** [comment]
Is it really meaningful to keep this issue open, when everything points to a platform/browser bug (rather than a PDF.js one), since this doesn't seem like something that can be fixed *here*?
