### ISSUE TITLE
how to search when use PDFPageView?

### ISSUE THREAD

**Issue by halower** [mozilla/pdf.js#10799]
`pdfjs-dist` the bag I use is
```
     self.pdfViewer = new PDFPageView({
          container: container,
          id: self.page,
          scale: 1,
          defaultViewport: pdfPage.getViewport(1),
          textLayerFactory: textLayer,
          annotationLayerFactory: annotationLayer
        });
        self.findController = new PDFFindController({
          pdfViewer: self.pdfViewer
        });
```
but I couldn't find the related api  that PDFFindController and PDFPageViewer

**Comment by timvandermeij** [comment]
There is an example for this: https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L58

**Comment by halower** [comment]
thank you very much. the demo use `PDFViewer`, This is done. does `PDFPageView` also support search? Is there a corresponding example?

**Comment by timvandermeij** [comment]
Not that I know of. The find controller can be used on its own though it you give it the document to work on. Refer to https://github.com/mozilla/pdf.js/blob/master/test/unit/pdf_find_controller_spec.js#L63.

**Comment by TomaIvanovTomov** [comment]
And can you give as example of how to implement it ? There is huge lack of examples. After setting the find controller itself, how to set a page to search in ? There is only setDocument method. No setPdfPage for example.

**Comment by dirheim** [comment]
> There is an example for this: https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L58

Sadly this example doesn't seems to exist anymore

**Comment by calixteman** [comment]
@dirheim, it shouldn't be too complex to figure out the new url..., right ?
https://github.com/mozilla/pdf.js/blob/36dc666d0403aa6db303b1891f6f0d07171d0564/examples/components/simpleviewer.mjs#L53-L56
