### ISSUE TITLE
Introducing jQuery using Ajax to request preview of background server PDF file "Object does not support replace attribute or method" on IE

### ISSUE THREAD

**Issue by hslig** [mozilla/pdf.js#10800]
hello！
I introduced jQuery using Ajax to request a preview of the background server PDF file. "The object does not support the replace attribute or method" on IE.
                 
                                                                                                                       Dan

**Comment by Snuffleupagus** [comment]
Unfortunately there's no actionable information provided, and the issue will thus be closed as INCOMPLETE.

Please make sure to actually provide *all* of details requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, and make sure to provide clear and concise information.
Furthermore, please understand that it's not possible to provide support for jQuery in this bug tracker.

**Comment by hslig** [comment]
Attach (recommended) or Link to PDF file here: anyone

Configuration:

Web browser and its version:Internet Explorer 11  11.0.10240.16384
Operating system and its version: Window 10 Professional Edition
PDF.js version: 2.1.266
Is a browser extension:Yes 
Steps to reproduce the problem: 1. 2.
Prerequisite: Get pdf from the background, use Uint8Array conversion format
1.Open Google Chrome Preview: Normal；
2.Open IE browser preview: Object does not support "replace" property or method；
What is the expected behavior? (add screenshot)
Normal preview Pdf。
What went wrong? (add screenshot)
Object does not support "replace" property or method
![image](https://user-images.githubusercontent.com/40198058/57590740-4d8e6a80-7560-11e9-9104-f0e0c8870e55.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):Temporarily no。

Thank you very much for answering my question, I hope you can help me solve this problem.
                                                                                                                                       dan
