### ISSUE TITLE
Can we provide fancy highlight/commenting feature like in Acrobat PDF Reader in Mozilla PDF.js

### ISSUE THREAD

**Issue by ganesh24dec** [mozilla/pdf.js#10804]
Attach (recommended) or Link to PDF file here:

![sample_pdf](https://user-images.githubusercontent.com/50450130/57523595-037c6d80-7343-11e9-9f61-863396e71b1f.PNG)

Configuration:
- Web browser and its version: All
- Operating system and its version: Windows
- PDF.js version: 2.0.385
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

As of now we are able to highlight the text in PDF using PDF.js library, but can we able to provide fancy highlighting/commenting features like strike out, call out text, drawing pen, multi line highlighter in the Mozilla PDF.js?

**Please find the attached sample PDF.**

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations

**Comment by ganesh24dec** [comment]
@Snuffleupagus : We are not going to edit the PDF direct on the viewer, we are just creating an overlay on top of PDF and just using the co-ordinates we are showing the highlights, so I need to know can we use any other selections (Strike through, rectangle ) other than mouse selection

**Comment by timvandermeij** [comment]
PDF.js supports rendering these annotations, but not adding/editing them. If you want that, it should be possible to implement this, but it's out of scope for the project.

**Comment by marco-c** [comment]
FYI, we are working on basic editing features: https://github.com/mozilla/pdf.js/projects/9.
