### ISSUE TITLE
build generic isn't transpiling some property mutators to ES5 long hand

### ISSUE THREAD

**Issue by dschissler** [mozilla/pdf.js#10802]
Configuration:
- Affects IE 11:
- Windows 10:
- PDF.js version: git master
- Is a browser extension: No

Steps to reproduce the problem:
1. Build using `gulp generic`.
2. Look inside `./build/generic/build/pdf.js` and search for `JURL.prototype`.  You'll see `get href() {`, which is a property mutator in shorthand.  This should be transpiled to older ES5 syntax.

What is the expected behavior?

It should be using the older long version `Object.defineProperty`.

What went wrong?

I don't know what went wrong but I've also been unable to get webpack and babel 7 to transpile this when I build straight from `lib` in the `pdfjs-lib` NPM package.  I've confirmed that the `@babel/plugin-transform-property-mutators` plugin will convert my trivial code test but it does not result in the transpiled code around the `JURL...` area.  There are other parts which don't transpile as well.

Is Babel unable to understand this code (due to how its nested)?  Is there something strange going on like a non-standard paste-in somewhere instead of using commonJS require?

Ex: [The Babel REPL website is capable of converting this](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=ATBSFUCUBkDoAcBOB7ALmgnvApsAvMAN4BQII6AyqogJYB2A5gFzABmArnQMao3J3BK1egwAUASiKkyIRNlTtEA1AAsaAZ1gq5rANzSQAXwA0xA8Abzg27KwlSZIGq2CjVG2AH0NASToA3AEMAGxoAE0kSRzI5BSVBNU1PRWD9aMMzaKDEYED2VWRaVAx8YAByMv1zJxc3RK92dWwlQIBbXABCPAIK4AAfPoSPT3hA9XUAd0Kw4C6COnZg4MjqsjyCopKCdyTG5ro23ABqVx2vUfGpxBm54AWl4AB-cqYy4BOzkbHJ6eAWCskJzKAAFKqsMqtYoplPUkGhkFxkMF3qd6t51JBsMFArx_LhnmUAPSEt4ndYqQo0Yoos4U9SoP7lMqAoaaUaqA7tGlogCO7GaJQ-aNYiECDHadFQaTIJkyZCaDJsdiCwX5K2iXGC2ECiFgXBCwTqGnE0pko0QTT1BqN6mMwBVatNwFlRiAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=es2015&prettier=false&targets=&version=7.4.4&externalPlugins=%40babel%2Fplugin-transform-property-mutators%407.2.0%2C%40babel%2Fplugin-transform-shorthand-properties%407.2.0)

```javascript
  JURL.prototype = {
    toString: function toString() {
      return this.href;
    },

    get href() {
      if (this._isInvalid) {
        return this._url;
      }

      var authority = '';

      if (this._username !== '' || this._password !== null) {
        authority = this._username + (this._password !== null ? ':' + this._password : '') + '@';
      }

      return this.protocol + (this._isRelative ? '//' + authority + this.host : '') + this.pathname + this._query + this._fragment;
    },

    set href(value) {
      clear.call(this);
      parse.call(this, value);
    },

  // .....
  }
```

```javascript
JURL.prototype = Object.defineProperties({
  toString: function toString() {
    return this.href;
  }
}, {
  href: {
    get: function get() {
      if (this._isInvalid) {
        return this._url;
      }

      var authority = '';

      if (this._username !== '' || this._password !== null) {
        authority = this._username + (this._password !== null ? ':' + this._password : '') + '@';
      }

      return this.protocol + (this._isRelative ? '//' + authority + this.host : '') + this.pathname + this._query + this._fragment;
    },
    set: function set(value) {
      clear.call(this);
      parse.call(this, value);
    },
    configurable: true,
    enumerable: true
  }
});
```

**Comment by Snuffleupagus** [comment]
> You'll see `get href() {`, which is a property mutator in shorthand.  This should be transpiled to older ES5 syntax.

Does the current code actually lead to any *outright* failures, when running in the latest version of IE11, since according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Browser_compatibility it looks like it should work as-is?

Please also note the current support situation for IE11, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Comment by dschissler** [comment]
Yes I was getting a hard crash that it was expecting a colon at that line.  It simply doesn't like it.

**Comment by Snuffleupagus** [comment]
> Yes I was getting a hard crash that it was expecting a colon at that line. It simply doesn't like it.

Strange, the default viewer demo at https://mozilla.github.io/pdf.js/web/viewer.html loads just fine for me.

**Comment by dschissler** [comment]
I'm getting myself back to where I started to give the exact error message.

**Comment by dschissler** [comment]
@Snuffleupagus I don't think that IE11 supports the short hand property syntax.

```javascript
  JURL.prototype = {
    toString: function toString() {
      return this.href;
    },

    get href() {
 ```

So I think that it would need to be something like this.

```javascript
  JURL.prototype = {
    toString: function toString() {
      return this.href;
    },

    href: get href() {
```

This comes right out of my pdf.js generic build directory.  Its just confusing because my webpack setup is transpiling the `toString` as short hand as well so it gets hung there.

**Comment by dschissler** [comment]
The IE 11 error is `SCRIPT1003: Expected ':'` and then it points to the offending line on the next line.

**Comment by dschissler** [comment]
Dang, I take it back.  I'm not getting the parse error when I only put in the official build.  Ok well thanks for letting me talk through this.  I'll try to figure out what is going wrong with webpack and then I'll see about closing this.

**Comment by dschissler** [comment]
Thanks.
