### ISSUE TITLE
PDF with embedded JS is failing

### ISSUE THREAD

**Issue by Motard** [mozilla/pdf.js#10801]
I have some pdf's that have some js functions inside them, like mailto for example.

The pdf's were not created by me though, so I do not know how this was done, but I can see that if I click on a certain phrase in the pdf, then the email client will open. This is viewing the pdf in my Mac pdf viewer.

Now If I try to open the same pdf in my PDF.JS application, it enters in an infinite loop and never finishes loading all the pages.

**Comment by Snuffleupagus** [comment]
Please make sure to actually provide *all* of details requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, as-is there's unfortunately no actionable information provided and the issue will be closed as INCOMPLETE.

> Now If I try to open the same pdf in my PDF.JS application, it enters in an infinite loop and never finishes loading all the pages.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
