### ISSUE TITLE
Blurry content on a 4K monitor on Windows 10

### ISSUE THREAD

**Issue by Luuk3333** [mozilla/pdf.js#10807]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

### Configuration:
- Web browser and its version: Firefox version 66.0.5
- Operating system and its version: Windows 10 Pro, version 10.0.17763 Build 17763
- PDF.js version: 2.2.167
- Is a browser extension: No

### Steps to reproduce the problem:
1. Attach a 4K monitor to a PC running Windows 10
2. Change the Firefox preference `layout.css.devPixelsPerPx` to a value higher than '1'.
3. Open https://mozilla.github.io/pdf.js/web/viewer.html or a local PDF.

### What is the expected behavior?
The content of the PDF should be scaled according to the preference listed above.

### What went wrong?
pdf.js displays PDFs blurry when using a 4K monitor on Windows 10. The only preference I have changed to get Firefox set up for a 4K monitor is the preference `layout.css.devPixelsPerPx` which I've set to '1.9' resulting in Firefox nicely scaling both Firefox and websites on the 27 inch monitor. However, the more that preference is increased the more blurry the built-in viewer displays PDFs. All content of PDFs is blurry, not just text. Also, zooming does not fix the problem.

Here's a comparison between Firefox, Chrome and Edge with the latter two displaying the content correctly:
![Screenshot (434)](https://user-images.githubusercontent.com/7993406/57537172-3ddf0e00-7335-11e9-9460-d08a2c8aa191.png)

**Comment by brendandahl** [comment]
If you leave the pref layout.css.devPixelsPerPx as the default, does the text look okay?

**Comment by Luuk3333** [comment]
@brendandahl Yes. However, switching to the default of '1' will disable scaling of Firefox itself, websites and pdf.js. Causes everything to look smaller on a monitor with a higher PPI which isn't very usable.

**Comment by Luuk3333** [comment]
Firefox is reporting an incorrect devicePixelRatio of '1'. Forcing it to be '2' by setting the variable `devicePixelRatio` on line 95 of the file 'web/ui_utils.js' to '2' fixes the issue as the content is now sharp. This is not a pdf.js issue but rather a Firefox issue.

**Comment by brendandahl** [comment]
@Luuk3333 Did you file a bug upstream with Firefox? https://bugzilla.mozilla.org

**Comment by Snuffleupagus** [comment]
This *may* be related to, or even a duplicate of, https://bugzilla.mozilla.org/show_bug.cgi?id=1537955.

**Comment by Luuk3333** [comment]
> @Luuk3333 Did you file a bug upstream with Firefox? https://bugzilla.mozilla.org

I have not. However, Firefox seems to be reporting the correct device pixel ratio since version 67.0.

**Comment by tannenfreund87** [comment]
> This _may_ be related to, or even a duplicate of, https://bugzilla.mozilla.org/show_bug.cgi?id=1537955.

To connect the issues better, here is the appropriate Firefox bugreport: https://bugzilla.mozilla.org/show_bug.cgi?id=1771184
