### ISSUE TITLE
pdfjs-dist-2.1.266 does not contain viewer.html

### ISSUE THREAD

**Issue by johnsonsw100** [mozilla/pdf.js#10814]
I'm using pdfjs-dist-2.1.266 in a Cordova App.  Prior pdfjs dist packages I've used contained viewer.html but the pdfjs-dist-2.1.266 package I have does not. 

Where can I get a pdfjs-dist-2.1.266 package that contains viewer.html?

or

How can I integrate an older version of  viewer.html with pdfjs-dist-2.1.266?

**Comment by timvandermeij** [comment]
I think you're confusing `pdfjs-dist` (a separate repository with only a generic library build, i.e., no viewer assets) and the normal PDF.js releases at https://github.com/mozilla/pdf.js/releases. The latter does contain `viewer.html` since it's not a library-only build.
