### ISSUE TITLE
找不到字体，字都变成了方框

### ISSUE THREAD

**Issue by shihaha** [mozilla/pdf.js#10817]
使用的是"pdfjs-dist": "^2.0.943"
使用如下写法引入字体文件夹：
```
this.loadingTask = pdfjsLib.getDocument({
    url: data.url,
    cMapUrl: '../../node_modules/pdfjs-dist/cmaps/',
    cMapPacked: true
});
```
会报这样的错：
`Warning: Failed to load font "g_d20_f1": SyntaxError: Invalid font data in ArrayBuffer.`

**Comment by timvandermeij** [comment]
Closing since we can only help out in English and with an example PDF file as asked for in the issue template.
