### ISSUE TITLE
Android Map is not defined error

### ISSUE THREAD

**Issue by johnsonsw100** [mozilla/pdf.js#10811]
I'm using pdfjs-dist-2.1.266 in a Cordova App on an Android device (Android Version 4.4.4) and get the below error following this code:

var loadingTask = pdfjsLib.getDocument(vPDFArrayBuffer);
loadingTask.promise.then(function(_pdf) { ...

UnknowErrorException: Map is not defined.

The same app works fine in Windows 10 and iOS.  The same code works fine in a Chrome Browser on the same Android device.

Prior PDF.js versions worked fine on this Android device.

Please let me know what I can do to make pdfjs-dist-2.1.266 work in a Cordova App on an Android device.

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, older versions of Android are *explicitly* unsupported.

> Please let me know what I can do to make pdfjs-dist-2.1.266 work in a Cordova App on an Android device.

You could try adding a `Map` polyfill, similar to https://github.com/mozilla/pdf.js/blob/fef86cc3e327f0554136482fee901b52909fa37a/src/shared/compatibility.js#L211-L217

Please note: browsers which are old enough that they don't implement `Map` natively are unsupported in PDF.js version `2.0`, and the above is thus not guaranteed to work. (There's also the possibility that other things are broken as well.)

**Comment by johnsonsw100** [comment]
Okay.  Thanks for the quick response.  I didn't realize the Android version on my test device was so old.
