### ISSUE TITLE
找不到字体

### ISSUE THREAD

**Issue by shihaha** [mozilla/pdf.js#10816]
使用的是"pdfjs-dist": "^2.0.943"
使用如下写法引入字体文件夹：
```
this.loadingTask = pdfjsLib.getDocument({
    url: data.url,
    cMapUrl: '../../node_modules/pdfjs-dist/cmaps/',
    cMapPacked: true
});
```
会报这样的错：
`Warning: Failed to load font "g_d1_f3": SyntaxError: Invalid font data in ArrayBuffer.`

**Comment by timvandermeij** [comment]
Closing since we can only help out in English and with an example PDF file as asked for in the issue template.

**Comment by coolara** [comment]
declare const PDFJS: any;
 PDFJS.cMapUrl = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.288/cmaps/'; // include "/"
    PDFJS.cMapPacked = true;
