### ISSUE TITLE
Canvas-based PDF embedded in rotated SVG element does not render correctly in Chrome

### ISSUE THREAD

**Issue by fhaag** [mozilla/pdf.js#10810]
Attach (recommended) or Link to PDF file here:
I am using a publicly accessible PDF file (in this case, the PDF representation of the Wikipedia article on the HTML5 canvas) for the sake of demonstration because I couldn't get Chrome to load a local PDF file via a relative URL for my minimal working example. In my real application, I tried this with a couple of different PDF files, though, and the result was always the same.

Configuration:
- Web browser and its version: Chrome 74
- Operating system and its version: Windows 10 x64
- PDF.js version: 2.2.2
- Is a browser extension: no

Steps to reproduce the problem:
1. Create an HTML page.
2. Insert some SVG data.
3. Within that SVG data, apply a transform with a rotation.
4. Within that transformed SVG fragment, add a <foreignObject> that contains a canvas.
5. Use that canvas as a rendering target for PDF.js.

(From various resources associated with this project, my understanding is that the PDF-to-SVG renderer from PDF.js is not yet as mature and feature-complete as the canvas-based PDF renderer.)

Sample files: [pdfjsCanvasInSvg.zip](https://github.com/mozilla/pdf.js/files/3169285/pdfjsCanvasInSvg.zip)

What is the expected behavior? (add screenshot)

Firefox 66 displays `test.html` as expected:

![correct display in Firefox](https://user-images.githubusercontent.com/1283543/57574804-188af680-7440-11e9-8918-922ab508f6fe.png)

What went wrong? (add screenshot)

Chrome 74, on the other hand, displays an unexpected portion of the PDF document and does not apply the rotation:

![problematic display in Chrome](https://user-images.githubusercontent.com/1283543/57574826-58ea7480-7440-11e9-92aa-c6c72a341aff.png)

Asking about this issue [on StackOverflow](https://stackoverflow.com/questions/56080332) has so far yielded a hint that it might be a quirk in how Chrome handles the canvas. However, if I draw something simple into the canvas myself rather than having PDF.js fill the canvas (cf. `test_ok.html`), Chrome does apply the rotation also to the canvas drawing:

![correct display with simple canvas graphic in Chrome](https://user-images.githubusercontent.com/1283543/57574860-c1d1ec80-7440-11e9-9cf6-c8e5bcfb284c.png)

**This makes me wonder whether Chrome is behaving weirdly due to something specific PDF.js does while using the canvas. Is this a known issue?**

**Comment by timvandermeij** [comment]
Not that I know of. PDF.js takes the the canvas you give it and applies its drawing operators on it. In the viewer at https://mozilla.github.io/pdf.js/web/viewer.html you can verify that the canvas does not get extra properties applied to it other than `width` and `height`, so it doesn't look like PDF.js is causing the issue here.

**Comment by fhaag** [comment]
Hello Tim, thank you for your response.

I fully understand it may be tricky to find out the exact preconditions causing this, and in the end it may well be related to a quirk in how Chrome renders content. And I do understand there may be no quick solution to it.

Yet, I would like to emphasize that I have provided two small examples with the same basic structure:
- In the one using PDF.js, the issue occurs.
- In the one that does not use PDF.js, the issue does not occur.

Based upon this apparent correlation, I would have hoped that the community around the PDF.js project would have a strong interest in finding out more about this issue, if only to point out limitations of the PDF.js library due to external factors.

**Comment by timvandermeij** [comment]
I don't think PDF.js does anything out of the ordinary with the canvas, so it looks more like a bug in Chrome. Let's reopen for further investigation.

**Comment by dbrotz** [comment]
I tried removing the use of PDF.js entirely and just modified the `width` and `height` with some simple code. It causes the same rendering issues in Chrome. It looks to me like this is a bug in Chrome.

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
</head>
<body>
<svg width="800" height="600">
<rect width="100%" height="100%" fill="rgb(186, 224, 255)"/>
<g transform="rotate(-30) translate(10, 20) scale(1.5)">
    <rect x="100px" y="50px" width="100px" height="80px" stroke="red" fill="none"/>
    <foreignObject x="150px" y="300px" width="200" height="150">
        <xhtml:body margin="0px" padding="0px" width="200px" height="150px" border="1px solid black">
            <canvas width="200" height="150" id="cnv"/>
        </xhtml:body>
    </foreignObject>
</g>
</svg>
<script type="text/javascript">
var canvas = document.getElementById('cnv');

canvas.width = 595;
canvas.height = 842;

var ctx = canvas.getContext('2d');

ctx.strokeStyle = 'blue';
ctx.strokeRect(0, 0, canvas.width, canvas.height);
</script>
</body>
</html>
```

**Comment by timvandermeij** [comment]
Thank you. I would suggest to report this upstream in the Chrome bug tracker then.
