### ISSUE TITLE
Razor Page - Loading PDF from Local TempFolder

### ISSUE THREAD

**Issue by captmomo** [mozilla/pdf.js#10824]
I am trying to use the viewer to display a local file saved in the tempfolder.  
This is my current code:

      <a href="/web/viewer.html?file=file:///@Html.UrlEncoder.Encode(Model.PDFUri)">Open yourpdf.pdf with PDF.js</a>

However the PDF is not displayed. 

If I enter the file path into my mozzila browser, the pdf loads properly.

Am I passing in the string incorrectly?

here's the sample of the Model.PDFUri:

C:\\Users\\username\\AppData\\Local\\Temp\\tmp99EE.pdf

What went wrong? (add screenshot)

![Screenshot](https://user-images.githubusercontent.com/25576022/57821645-d6591080-77c3-11e9-8e1e-fd05df7dfd1f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As is clearly mentioned in the README, see https://github.com/mozilla/pdf.js#getting-the-code, most browsers won't allow opening `file://` URLs for security reasons. Hence this issue is INVALID, since it's not a limitation of the PDF.js project itself.
