### ISSUE TITLE
Bad end offset on  a particular server

### ISSUE THREAD

**Issue by VeeK727** [mozilla/pdf.js#10828]
Link to PDF file here: https://interglobixmagazine.com/demo3/download.php?id=MQ==

Configuration:
- Web browser and its version: Chrome 74.0.3729.131
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943
- Is a browser extension: No

I have created a website for PDF viewing and it works fine on my server but when I moved the website to a client's server, it stopped working. I get an error from `pdf.worker.min.js: Error: Bad end offset: 65725`.

I have read similar issues but their solution that it was a Chrome bug and fixed does not help me. Here are some requests and responses from pdfjs.
Request 1:
```
:authority: interglobixmagazine.com
:method: GET
:path: /demo3/download.php?id=MQ==
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: no-cache
cookie: _ga=GA1.2.198267131.1557558222; _gid=GA1.2.152154760.1557986690; PHPSESSID=92cf1ec98d2c3fa44ee7a1b5959ec258; __stripe_mid=0a744059-bef6-4227-b125-5e890c5a792c; __stripe_sid=08c3b544-0b55-4407-b3c6-826cdd948d5b; session=2%3A6a1fd6de7e93cb832eca95fa2568b34b59c22c3a8804ff2d09f766e20ebc2aee21b910bd4580fcce7db04159400245e2e269ebba74009649c9c0df52a44fa307%3A7dfe7b05fcb72669f9e670ea1f62ee601fa2f911aa7c774d27e6618dd135d220; _gat_UA-136193537-1=1
pragma: no-cache
referer: https://interglobixmagazine.com/demo3/publications.php
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
```

Response 1: 
```
accept-ranges: bytes
cache-control: no-store, no-cache, must-revalidate
content-length: 41953136
content-range: bytes 0-41953135/41953136
content-type: application/pdf
date: Thu, 16 May 2019 08:22:53 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: Apache
status: 200
vary: User-Agent
x-powered-by: PHP/7.2.17
```

Request 2:
```
:authority: interglobixmagazine.com
:method: GET
:path: /demo3/download.php?id=MQ==
:scheme: https
accept: */*
accept-encoding: identity
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: no-cache
cookie: _ga=GA1.2.198267131.1557558222; _gid=GA1.2.152154760.1557986690; PHPSESSID=92cf1ec98d2c3fa44ee7a1b5959ec258; __stripe_mid=0a744059-bef6-4227-b125-5e890c5a792c; __stripe_sid=08c3b544-0b55-4407-b3c6-826cdd948d5b; session=2%3A6a1fd6de7e93cb832eca95fa2568b34b59c22c3a8804ff2d09f766e20ebc2aee21b910bd4580fcce7db04159400245e2e269ebba74009649c9c0df52a44fa307%3A7dfe7b05fcb72669f9e670ea1f62ee601fa2f911aa7c774d27e6618dd135d220; _gat_UA-136193537-1=1
pragma: no-cache
range: bytes=0-65535
referer: https://interglobixmagazine.com/demo3/publications.php
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
```

Response 2:
```
accept-ranges: bytes
cache-control: no-store, no-cache, must-revalidate
Content-Length: 65536
Content-Range: bytes 0-65535/41953136
content-type: application/pdf
date: Thu, 16 May 2019 08:22:54 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
pragma: no-cache
server: Apache
status: 206
vary: User-Agent
x-powered-by: PHP/7.2.17
```

I don't understand from where am I getting 65752 bytes instead of 65536. I used `console.log` to output relevant values and I do get 65536 bytes on the old server. Please help me.

**Comment by Snuffleupagus** [comment]
> I have created a website for PDF viewing and it works fine on my server but when I moved the website to a client's server, it stopped working.

That would, quite clearly, indicate that it's a problem with a particular *server* rather than the PDF.js project itself. Hence this issue is INVALID, since it's not reasonable for a PDF.js contributor to *somehow* debug your server setup.

**Comment by VeeK727** [comment]
I totally understand but if you could point me in the right direction, that
would be greatly appreciated. If you have something on the top of your mind
that could produce an error like this, please let me know.

**Comment by VeeK727** [comment]
Can you give me a clue why pdfjs is interpreting 65752 bytes while chrome devtools show the response is 0-65536? What would add additional bytes to it?

**Comment by timvandermeij** [comment]
I don't think PDF.js has anything to do with this; it looks more like a server configuration issue. If you can in fact find a bug in PDF.js, then we can always reopen this.
