### ISSUE TITLE
Webpack should handle loading worker instead of setting workerSrc

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#10838]
When following the [Webpack example](https://github.com/mozilla/pdf.js/tree/master/examples/webpack) and importing `pdfjs-dist` with `import * as pdfjsLib from 'pdfjs-dist';` Webpack will create a `pdfjsWorker.js` and also automatically load it in the browser. The file may be named differently(hashed names, prefixes, etc.)

Still pdf.js requires to set a absolute path: `pdfjsLib.GlobalWorkerOptions.workerSrc = 'pdfjsWorker.js';`

This will let Webpack load the worker, and then pdf.js will also load the worker itself. Why is that the case? Instead we could just create a Worker and let Webpack do the loading?

Also i am having heavy trouble setting the workerSrc: The filename might be `pdfjsWorker.js` in development, but in production it has hashes and differential loading prefixes. I could use an external worker.js but then the worker(1.5mb) will be loaded twice and should not be included in Webpack bundling.

**Comment by Kailaash-Balachandran** [comment]
@MickL I'm facing the same. Did you find any workarounds?

**Comment by MickL** [comment]
No I didnt find any. I used a second, precompiled, pdfjsWorker. So as far as I see the 1.5 MB worker gets loaded twice (bundled and loaded with webpack and loaded by pdf.js again but from different source).

**Comment by wpp** [comment]
FWIW you can try importing `import pdfjsLib from 'pdfjs-dist/webpack';` which handles the url assignment automatically. It does seem to come with a caveat though, if you're using (a newer version of) create-react-app the hot module replacement doesn't seem to be compatible right now. There is an example project I've found today: https://github.com/yurydelendik/pdfjs-react

**Comment by timvandermeij** [comment]
Closing since we've changed the way we're working with Webpack to remove those dependencies from `pdfjs-dist`.

**Comment by edcheung1** [comment]
> Fantastic, thank you. You found the same resource I had been reading in my searches.
> I still have to figure out what's not working but you helped me ruling out quite a few bits.
> Kindest regards,
> Giampaolo

Hey Giampaolo,

I'm also running into the same issue. I haven't been able to completely resolve the issue, but I was able to see that the worker-loader is trying to require the `FetchCompileWasmPlugin` here:

https://github.com/webpack-contrib/worker-loader/blob/master/src/index.js#L26

Seems like there may be some inconsistencies between Webpack 4 and 5?

**Comment by giampaolo44** [comment]
> Hey Giampaolo,
> 
> I'm also running into the same issue. I haven't been able to completely resolve the issue, but I was able to see that the worker-loader is trying to require the `FetchCompileWasmPlugin` here:
> 
> https://github.com/webpack-contrib/worker-loader/blob/master/src/index.js#L26
> 
> Seems like there may be some inconsistencies between Webpack 4 and 5?

Oh great pick @edcheung1 . Do you think we should raise the issue with the Webpack team and maybe open an issue?
Looking at their website I understood to ask on SO first, [which I did without feedback so far](https://stackoverflow.com/questions/63553008/looking-for-help-to-make-npm-pdfjs-dist-work-with-webpack-and-django), so it might be a good idea.

**Comment by rettgerst** [comment]
I'm running into the same problem here. admittedly this is a super old project with a lot of out-of-date dependencies so maybe I'm missing something, but I can't get a newer version of pdfjs-dist to work where previously I had it working by importing 'pdfjs-dist/webpack'. now after updating pdfjs-dist, worker-loader and webpack, I am getting the following output:

```
WARNING in ./node_modules/worker-loader/dist/index.js
Module not found: Error: Can't resolve 'webpack/lib/web/FetchCompileAsyncWasmPlugin' in '/home/rett/projects/LSCPortalFE/node_modules/worker-loader/dist'
 @ ./node_modules/worker-loader/dist/index.js
 @ ./node_modules/worker-loader/dist/cjs.js
 @ ./node_modules/pdfjs-dist/webpack.js
 @ ./app/scripts/modules/PDFJSTools.ts
 @ ./app/scripts/UploadModalCtrl.ts
 @ ./app/scripts/angular-scripts.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 @babel/polyfill ./app/scripts/deps.js ./app/scripts/angular-scripts.js ./app/scripts/stylesheet-bundle.js

WARNING in ./node_modules/worker-loader/dist/index.js
Module not found: Error: Can't resolve 'webpack/lib/web/FetchCompileWasmPlugin' in '/home/rett/projects/LSCPortalFE/node_modules/worker-loader/dist'
 @ ./node_modules/worker-loader/dist/index.js
 @ ./node_modules/worker-loader/dist/cjs.js
 @ ./node_modules/pdfjs-dist/webpack.js
 @ ./app/scripts/modules/PDFJSTools.ts
 @ ./app/scripts/UploadModalCtrl.ts
 @ ./app/scripts/angular-scripts.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 @babel/polyfill ./app/scripts/deps.js ./app/scripts/angular-scripts.js ./app/scripts/stylesheet-bundle.js

ERROR in (webpack)/lib/node/NodeTargetPlugin.js
Module not found: Error: Can't resolve 'module' in '/home/rett/projects/LSCPortalFE/node_modules/webpack/lib/node'
 @ (webpack)/lib/node/NodeTargetPlugin.js 11:1-18
 @ ./node_modules/worker-loader/dist/index.js
 @ ./node_modules/worker-loader/dist/cjs.js
 @ ./node_modules/pdfjs-dist/webpack.js
 @ ./app/scripts/modules/PDFJSTools.ts
 @ ./app/scripts/UploadModalCtrl.ts
 @ ./app/scripts/angular-scripts.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 @babel/polyfill ./app/scripts/deps.js ./app/scripts/angular-scripts.js ./app/scripts/stylesheet-bundle.js
```

**Comment by achembarpu** [comment]
+1 FWIW facing the exact same error msgs mentioned above with a clean setup of create-react-app and using the App component from https://github.com/yurydelendik/pdfjs-react.

**Comment by mforman1** [comment]
We are also facing the exact same issue after upgrading the `pdfjs` library,
@timvandermeij can the issue be re-opened?

**Comment by Mageenz** [comment]
vue-cli4，same error

**Comment by Taschetta** [comment]
I was able to solve the problem with the responses on
https://stackoverflow.com/questions/63553008/looking-for-help-to-make-npm-pdfjs-dist-work-with-webpack-and-django

Nevertheless, as i was still facing other issues using pdfjs with vue 3... To make it work i ended up using version 2.0.943 of the pdfjs-dist package. Not the best solution, but the only way i found to make it work after a week of trial and error...

**Comment by jixbo** [comment]
> +1 FWIW facing the exact same error msgs mentioned above with a clean setup of create-react-app and using the App component from https://github.com/yurydelendik/pdfjs-react.

Currently facing the exact same issue. Did you find a fix?

**Comment by aert** [comment]
Same issue here, I followed all steps described in the sparse docs/examples and countless online blog post for old version and still no clear way to integrate pdfjs to a project.

This post shows all the hoops one went through to make it work: https://stackoverflow.com/questions/63553008/looking-for-help-to-make-npm-pdfjs-dist-work-with-webpack-and-django

Would really be nice if the dev experience was nicer, in the mean time will try to downgrade to  2.0.943 as the post above suggests ...

**Comment by drdrwhite** [comment]
Here's the fix copied from SO, posted by Siddhesh on 20th October:

> This issue seems to arise due to esModule option introduced in worker-loader@3.0.0.
> The fix for this was merged in (pre-release) pdjs-dist@2.6.347
> You can fix this by either upgrading pdfjs-dist to v2.6.347 OR downgrading worker-loader to v2.0.0

It's easiest to downgrade worker-loader, as the pdfjs-dist containing the fix has not yet been released to npm.

You can then import pdfjs-dist with:

```
let pdfjs = require("pdfjs-dist/webpack");
let loadingTask = pdfjs.getDocument(url);     
```

This works for me within a Vue.js component, in a project created by vue-cli. I'm using pdfjs-dist 2.5.207 and worker-loader 2.0.0.

**Comment by morgan4080** [comment]
Here is how I imported everything pdfjs and pdfjsworker

import * as pdfjsLib from 'pdfjs-dist';
import { pdfjsWorker } from 'pdfjs-dist/webpack'

**Comment by rnike** [comment]
thanks @morgan4080 the solution works pretty well

below is for someone who is looking for dynamic import

```ts
import type PDFJS from 'pdfjs-dist';

let loader: Promise<typeof PDFJS>;

export default async function pdfjs() {
  if (!loader) {
    loader = new Promise((resolve, reject) => {
      import('pdfjs-dist/webpack')
        .then(() => import('pdfjs-dist/build/pdf').then(resolve))
        .catch(reject);
    });
  }

  return loader;
}
```

**Comment by MddHstl** [comment]
Just leave the final solution here.

```
import * as pdfjsLib from 'pdfjs-dist/webpack';

export const pdfView = () => {
  const loadingTask = pdfjsLib.getDocument(pdfData.myPdfDoc)

  pdfData.myPdf = loadingTask.promise.then(pdf => {
    pdfData.pdfTotalPageN = pdf.numPages;
    return pdf;
  })
}
```
