### ISSUE TITLE
Render blank page in IE11

### ISSUE THREAD

**Issue by k-takio** [mozilla/pdf.js#10834]
In my environment, I view a PDF with a large number of pages, scroll quickly down a few pages, and then go back a few more pages to render a blank page.

When I scroll, all the pages have the loading indication, and when I come back, the loading indication disappears and it is blank.
(If I scroll slowly, it will render correctly, so I think there is no problem with the data.)

There is a similar issue on iOS, but some conditions such as including a large image did not match.

Does anyone have the same problem?
Also, is there any solution?

Regards

#### Configuration:
- Web browser and its version:
    Internet Explorer 11
- Operating system and its version:
    Windows 7/8.1/10
- PDF.js version:
    1.9.426 (The same was true for 1.10.88/1.10.100)

#### What is the expected behavior?
PDF loads and displays all pages.

#### What went wrong?
Some page doesn't rendered.

![blank page](https://user-images.githubusercontent.com/50812917/58001022-50b3c880-7b15-11e9-8eb7-0e15d543b492.png)

#### Steps to reproduce the problem:
1. Open a large PDF. (e.g. over 300 pages, 20 MB)
2. Scroll down about 30 pages.
3. Scroll up about 20 pages.
4. As I scroll up, I sometimes see white blank pages.
    * It may not happen at one time, but if you repeat it several times, it will surely be reproduced.
    * A blank page div element did not have a data-loaded attribute.
    * Scrolling again will never render again.
    * If I change the zoom, it will be rendered after the loading display.

**Comment by Snuffleupagus** [comment]
Unfortunately this issue contains no actionable information, since the `Attach (recommended) or Link to PDF file here:` part of the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is missing.
Furthermore, since this sounds like an issue with a custom implementation; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

>     * Web browser and its version:
>       Internet Explorer 11

Finally, please note that as outlined in the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support) support for IE 11 is limited:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
