### ISSUE TITLE
Need to show single page at a time

### ISSUE THREAD

**Issue by Vigneshjana** [mozilla/pdf.js#10835]
the user must not scroll, while clicking on next button need to show the another page is it possible?

**Comment by Snuffleupagus** [comment]
Please see the `singlepageviewer` example found in https://github.com/mozilla/pdf.js/tree/master/examples/components (which is based on https://github.com/mozilla/pdf.js/blob/master/web/pdf_single_page_viewer.js).

**Comment by Vigneshjana** [comment]
@Snuffleupagus Can you please explain how can i implement this?
