### ISSUE TITLE
Messy code rendered (in both canvas and text layer)

### ISSUE THREAD

**Issue by coolKIH** [mozilla/pdf.js#10839]
Attach (recommended) or Link to PDF file here: 
Link: http://static.sse.com.cn/disclosure/listedinfo/announcement/c/600008_2000_1.pdf
Attachment: [sh_600008_2000_1.pdf](https://github.com/mozilla/pdf.js/files/3200624/sh_600008_2000_1.pdf)

Configuration:
- Web browser and its version: Chrome/74.0.3729.131
- Operating system and its version: macOS Version 10.14.4
- PDF.js version: Stable (v2.0.943)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the problem PDF on the PDF.JS Web Viewer;
2. Obviously the whole file is rendered inappropriately, with full of messy code in both canvas layers and text layers.
3. Tests on other PDF readers: If I open the same PDF on Chrome, the file is however rendered correctly, which means the contents look correct, and I can select-and-copy the contents without messy code from the PDF. But if I open the PDF on Safari or on my native PDF reader "Preview", the same issue is observed as it is on PDFJS Viewer.

What is the expected behavior? (add screenshot)
<img width="887" alt="Screen Shot 2019-05-21 at 11 41 27 AM" src="https://user-images.githubusercontent.com/20931311/58066799-6d0b4000-7bbd-11e9-96c2-3409b13f0420.png">

What went wrong? (add screenshot)
<img width="907" alt="Screen Shot 2019-05-21 at 11 41 06 AM" src="https://user-images.githubusercontent.com/20931311/58066807-73012100-7bbd-11e9-869f-7b6b39c99b15.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Unfortunately this cannot be fixed, since the PDF file contains fonts with both non-standard *and* non-embedded font files (which the specification doesn't even allow). Note also how even Adobe Reader, i.e. the PDF reference implementation, fails to display the file correctly because of the above.

**Comment by coolKIH** [comment]
> Unfortunately this cannot be fixed, since the PDF file contains fonts which are both non-standard _and_ with non-embedded font files (which the specification doesn't even allow). Note also how even Adobe Reader, i.e. the PDF reference implementation, fails to display the file correctly because of the above.

Thanks! I imagine that such issue is more nontrivial than 100% unresolvable, when I found that Chrome was able to render the PDF successfully without any issues, which is surprisingly amazing!

**Comment by Snuffleupagus** [comment]
> I imagine that such issue is more nontrivial than 100% unresolvable,

It's unfixable from a PDF.js perspective, since it's simply impossible to include random fonts with the library itself. (We're not even, for various reasons such as legal/filesize, including the 14 standard fonts.)

**Comment by coolKIH** [comment]
> > I imagine that such issue is more nontrivial than 100% unresolvable,
> 
> It's unfixable from a PDF.js perspective, since it's simply impossible to include random fonts with the library itself. (We're not even, for various reasons such as legal/filesize, including the 14 standard fonts.)

Many thanks! Good to know that.

**Comment by coolKIH** [comment]
> Unfortunately this cannot be fixed, since the PDF file contains fonts which are both non-standard _and_ with non-embedded font files (which the specification doesn't even allow). Note also how even Adobe Reader, i.e. the PDF reference implementation, fails to display the file correctly because of the above.

Hello Snuffleupagus, you mentioned

> the PDF file contains fonts which are both non-standard and with non-embedded font files

With regards to which, I'd like to know if I can specify and use custom fonts on PDFJS when no standard fonts or embedded font files are available for the problem PDF? 

I imagine I can extend the PDFJS, adding more fonts in addition to the 14 standard fonts to it when there are some fonts missing. Would that be possible?

**Comment by coolKIH** [comment]
> > I imagine that such issue is more nontrivial than 100% unresolvable,
> 
> It's unfixable from a PDF.js perspective, since it's simply impossible to include random fonts with the library itself. (We're not even, for various reasons such as legal/filesize, including the 14 standard fonts.)

Hey Snuffleupagus, I learnt that PDFJS will try to use a fallback font from the operating system when the font is missing from [this link](https://wiki.mozilla.org/PDF.js/fonts).
Is there a way to configure the fallback font on Linux? I am not sure if I am asking a right question. If so, I really hope you would correct me. Thanks in advance!
