### ISSUE TITLE
Unable to accurately confirm when rendering has completed

### ISSUE THREAD

**Issue by 3chillies-kris** [mozilla/pdf.js#10832]
**Attach (recommended) or Link to PDF file here:** https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf

**Configuration:**
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: 2.2.2
- Is a browser extension:

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):** https://codepen.io/3chillies-kris/pen/PvjqLR

Hi folks,

I have an issue here, in that I am requiring the PDF viewer to essentially be as part of a pretend carousel (everything is positioned absolutely, z-indexed negatively, the 'current' item comes in when necessary). I need to do this, as unfortunately carousel functionality doesn't seem to play too well with it, and have been having significant issues getting a paged version to work with the Link Service.

The result of this is that I have set line 58 as a very detailed promise check to totally confirm the rendering finished, and then set some jQuery to make light additions/amends to the page. It isn't working unfortunately, and I'm struggling to understand why. This could be a limitation of my understanding of chaining promises (which is a problem I face in real life too, honestly), but it's not reflecting any of the changes I've made within the 'final' promise.

Would love to hear any feedback you may have. I've been trying to piece a lot of this together from the many wildly different tutorials/snippets out there, and my ES6 is very limited.

Thanks all.

**Comment by 3chillies-kris** [comment]
I think I can make this far easier to solve (or close either way). It's one simple question I think.

Can I have PDF.js output paged PDFs (so previous/next), based on https://mozilla.github.io/pdf.js/examples (bottom example), with the LinkService (highlighting text and clicking links) over the top of it, and a point in the right direction as to how to write it? In the research I've done, it doesn't seem possible because the various examples I've seen, on the example page above as well as the example components folder in the repo, as well as the million and one tutorials/StackOverflow posts out there about it, there's so different syntax between them all that I'm struggling to cut through the sheer noise.

I think that's the question I needed to ask in the first place!

**Comment by Snuffleupagus** [comment]
Please refer to the `viewer component" examples, which are built upon (some of) the same underlying components as used in the full viewer, see https://github.com/mozilla/pdf.js/tree/master/examples/components

There's e.g. the `singlepageviewer` example, with which it should be possible to create something along the lines of the "Previous/Next example" example but with both text-selection and annotations available by default.
