### ISSUE TITLE
InvalidPDFException when viewing the Chinese content PDF using Primeface DefaultStreamedContent

### ISSUE THREAD

**Issue by sudhansu789** [mozilla/pdf.js#10848]
Link to PDF file here:
[Chinese Content PDF Document]( https://drive.google.com/file/d/1-axLOL65IbzHfsjQqISp7bPcDb8cf3De/view )
Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 10
- PDF.js version:   PDF.js v1.0.21
- Is a browser extension: No

Steps to reproduce the problem:
Using below code to view the PDF document using `DefaultStreamedContent`.
`<pe:documentViewer locale="en"  height="600" value="#{documentMBean.pdfFile}" id="pdfDocViewer" >`

Below code to get the Stream as pdfFile.
```
byte[] documentData = null;
setPdfFile(new DefaultStreamedContent());
documentData =//Getting the byte array from DB
getPdfFile().setStream(new ByteArrayInputStream(documentData)); 
getPdfFile().setContentType("application/pdf"); 
getPdfFile().setContentEncoding("UTF-8");
```
What is the expected behavior? 

The PDF which contents Chinese should able to view in Document Viewer. 

What went wrong? 
When I upload and store a PDF file which contents Chineese charactes getting below exception in PDF Viewer.

> PDF.js v1.0.21 (build: f954cde) Message: InvalidPDFException

_Note: Plain text PDF which contents English characters working fine and able to view the PDF._

_I have tried to set different character-encoding such as UTF-8,UTF-16_
Please assist me how to resolve above exception.

**Comment by Snuffleupagus** [comment]
> PDF.js version:   PDF.js v1.0.21

That version is over *five* years old, and is thus no longer supported. Please update the the latest release, as found at https://github.com/mozilla/pdf.js/releases, *before* asking for assistance.

> Below code to get the Stream as pdfFile.

Furthermore none of this seems directly related to the PDF.js library, and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
