### ISSUE TITLE
render page to png in node exit unexpectedly

### ISSUE THREAD

**Issue by double0z** [mozilla/pdf.js#10840]
Attach (recommended) or Link to PDF file here:
链接: https://pan.baidu.com/s/1hPGBsNFeeqLMhgNqglRlNw  提取码: 554v 
or you can download from here.
https://github.com/mozilla/pdf.js/files/3205073/13.pdf

Configuration:
- Web browser and its version:chrome
- Operating system and its version: win8
- PDF.js version: 2.0.943 and 2.1beta
- Is a browser extension:no

Steps to reproduce the problem:
1. run example "examples/node/pdf2png/pdf2png.js"  but use my pdf 
2. program exit without any exception. but exit.

What is the expected behavior? (add screenshot)
i want to render png file in node envirment.

What went wrong? (add screenshot)
i don't know what went wrong .

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> 
> 链接: https://pan.baidu.com/s/1hPGBsNFeeqLMhgNqglRlNw
> 提取码: 554v

Please just attach the PDF file directly to the issue, as asked for, since navigating that web-site is *very* difficult for a non-Chinese speaker.

**Comment by double0z** [comment]
[13.pdf](https://github.com/mozilla/pdf.js/files/3205073/13.pdf)


> 
> 
> > Attach (recommended) or Link to PDF file here:
> > 链接: https://pan.baidu.com/s/1hPGBsNFeeqLMhgNqglRlNw
> > 提取码: 554v
> 
> Please just attach the PDF file directly to the issue, as asked for, since navigating that web-site is _very_ difficult for a non-Chinese speaker.

ths ,know you can download from https://github.com/mozilla/pdf.js/files/3205073/13.pdf

**Comment by KIYK** [comment]
Not sure if the cause is in node-canvas though, it happens in NodeCanvasFactory reset (pdf2png.js).
Sometime, when set a value to canvas.width and/or canvas.height, it happens.

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
> 
>     1. run example "examples/node/pdf2png/pdf2png.js"  but use my pdf
> 
>     2. program exit without any exception. but exit.

This seems to work now, based on testing with PDF.js version `2.4.456`; see https://github.com/mozilla/pdf.js/releases

The remaining font issues/warnings are already tracked in issue #4244, hence this can be closed now. /cc @timvandermeij
