### ISSUE TITLE
error while rendering svg <svg:rect> attribute height: A negative value is not valid.

### ISSUE THREAD

**Issue by sufiyalm** [mozilla/pdf.js#10841]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
chrome browser 74.0.3729.157 
- Operating system:
Windows 
- PDF.js version:
2.5.7

Steps to reproduce the problem:
1. load pdf via SVG render
Code snippet to load pdf as svg
page.getOperatorList()
            .then(function (opList) {
              var svgGfx = new PDFJS.SVGGraphics(page.commonObjs, page.objs);
              return svgGfx.getSVG(opList, viewport);
            })
            .then(function (svg) {
                svg.style.width = container.style.width;
                svg.style.height = container.style.height;
                container.appendChild(svg); 
                
            });

What is the expected behavior? (add screenshot)
pdf page should load properly
![expected](https://user-images.githubusercontent.com/48019742/58092237-2f241100-7be9-11e9-8d47-fe75f728d728.png)

What went wrong? (add screenshot)
images not loading throwing error:
Error: <svg:rect> attribute height: A negative value is not valid. ("-841.89")
![actualpdf](https://user-images.githubusercontent.com/48019742/58092026-b9b84080-7be8-11e9-9a78-fe26732818bb.png)

**Comment by timvandermeij** [comment]
Closing since, as indicated in the issue template, this is not actionable without a PDF file to reproduce the issue.
