### ISSUE TITLE
Open PDF file from URL with base64

### ISSUE THREAD

**Issue by debcal** [mozilla/pdf.js#10856]
I want to update the PDF.js script to open PDF file from URL with base64 to prevent IDM to automatically download. Please help us. I am using following code:-
------------------------
[code.txt](https://github.com/mozilla/pdf.js/files/3217252/code.txt)

**Comment by timvandermeij** [comment]
The example for `base64` PDF loading is here: https://github.com/mozilla/pdf.js/blob/2e05827b87646e621593fb26f4327f335d0a0d7a/examples/learning/helloworld64.html

**Comment by debcal** [comment]
I checked this earlier, but how would I use url of the pdf here? 

Or any other way to prevent IDM to download the pdf from our site?

**Comment by timvandermeij** [comment]
We can't provide support for IDM. You'll have to ask them instead.
