### ISSUE TITLE
Intermittent PDF Rendering Issue in Edge

### ISSUE THREAD

**Issue by martf72** [mozilla/pdf.js#10852]
Attach (recommended) or Link to PDF file here:  Sensitive document so not able to attach.

Configuration:
- Edge Version - 44.17763.1.0
- Windows 10 Pro 10.0.17763
- PDF.js version: 2.1.32
- Is a browser extension: No

Steps to reproduce the problem:
When we call the getDocument function from out JS page it doesn't recover back to the calling code not throwing any errors.

What is the expected behavior? (add screenshot)

Works fine and quickly in Chrome and Firefox with the same PDF.

What went wrong? (add screenshot)
The Viewer just hangs.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: Sensitive document so not able to attach.

Unfortunately that makes this issue INVALID, since there's nothing anyone can do to help without access to a test-case.

> Edge Version - 44.17763.1.0

Furthermore, please also note the [following section from the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.
