### ISSUE TITLE
PDF file rendered incorrectly

### ISSUE THREAD

**Issue by bernhold** [mozilla/pdf.js#10855]
Attach (recommended) or Link to PDF file here: https://doi.org/10.5281/zenodo.3019412

Configuration:
- Web browser and its version: FireFox 66.0.3 (64-bit)
- Operating system and its version:  Windows 10
- PDF.js version: unknown
- Is a browser extension: no

Steps to reproduce the problem:
1. Load PDF file
2.

What is the expected behavior? (add screenshot)
<img width="1280" alt="Capture-acrobat" src="https://user-images.githubusercontent.com/426409/58326984-5a327e80-7dfc-11e9-8cff-7d4f68c3c766.PNG">
Note horizontal colored bars heading sections, and light bulb motif in center.

What went wrong? (add screenshot)
<img width="1280" alt="Capture-pdfjs" src="https://user-images.githubusercontent.com/426409/58326971-53a40700-7dfc-11e9-901f-7888422248f5.PNG">
Note that the horizontal colored bars and the light bulb are not rendered correctly.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://doi.org/10.5281/zenodo.3019412
Zenodo uses pdf.js as a previewer, and the document has the same problem there.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: FireFox 66.0.3 (64-bit)

Fixed by PR #6606, which will be included in Firefox 68.

> Zenodo uses pdf.js as a previewer, and the document has the same problem there.

They're using PDF.js version `1.4.192`, which is many *years* out-of-date (and was never an official release either). Please ask them to update the *lastest* version, as found at https://github.com/mozilla/pdf.js/releases
