### ISSUE TITLE
Warning: Failed to load font "g_d20_f1": SyntaxError: Invalid font data in ArrayBuffer.

### ISSUE THREAD

**Issue by cyfour** [mozilla/pdf.js#10853]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version: win7
- PDF.js version:2.0.550
- Is a browser extension: chrome66

Steps to reproduce the problem:
1. G_d0_f1 font cannot be read in ASUS A555L notebook
2.No problem with other computers.
3.cmaps：http://cdn.keledge.com/files/pdfjs-dist-2.0/cmaps/

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Without access to a test-case this issue will be closed as INVALID, since there's no actionable information provided as-is.

> PDF.js version: 2.0.550

Furthermore, that's *not* an official release. Please make sure to always use the latest available releases as found at https://github.com/mozilla/pdf.js/releases

**Comment by cyfour** [comment]
Now I'll change the version to 2.0.943.

Console：
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Setting up fake worker.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f1": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f2": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f3": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f4": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f5": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f6": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f7": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f9": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f11": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d2_f12": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d3_f13": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d3_f14": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d4_f21": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d4_f23": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d4_f25": SyntaxError: Invalid font data in ArrayBuffer.
1.7a773eca695a5f874a77.1558922459921.js:19 Warning: Failed to load font "g_d4_f27": SyntaxError: Invalid font data in ArrayBuffer.

**Comment by cyfour** [comment]
![QQ图片20190527114149](https://user-images.githubusercontent.com/24726616/58394166-76405500-8074-11e9-812d-1ce56defaee3.png)

**Comment by timvandermeij** [comment]
It's impossible to debug this without the PDF file itself. If it contains sensible information, you can consider making another PDF with the same generator that also shows the issue.

**Comment by cyfour** [comment]
In that ASUS notebook, only the PDF display is wrong, and everything else is normal. Well, how should I debug it?
