### ISSUE TITLE
How to traverse annotations one by one in a page

### ISSUE THREAD

**Issue by rakeshkasinathan** [mozilla/pdf.js#10857]
I want to traverse the annotation from a annotationlayer into the pagecontent and insert textnode before or after of a annotation.

**Comment by timvandermeij** [comment]
Every page `div` contains a `div` with the `annotationLayer` class. This contains all annotations that you can loop over in JavaScript.

**Comment by rakeshkasinathan** [comment]
Could you please tell me how to get the position of Annotation. So that i will insert text node before or after Annotation.

**Comment by timvandermeij** [comment]
The `getAnnotations` API will give you the `rect` property that shows where the annotation is positioned on the page. Alternatively, if you loop over the elements in the `annotationLayer` class you can also get their position from the DOM node.

**Comment by Bharani14** [comment]
Hi,
From the below screenshot how can i get the annotation content and its dom position also what type of annotation is that such as strikeout,highlight or newly inserted? Also may i know how does the rendering of annotation in pdf js is done for specific words?
![error](https://user-images.githubusercontent.com/31505000/59028774-030bbf80-887a-11e9-95c0-f7aef522a959.png)
