### ISSUE TITLE
Facing issue where the print works only first time

### ISSUE THREAD

**Issue by buddyappsin** [mozilla/pdf.js#10866]
I have implemented the PDF js on one of my projects but it only works first time. If I cancel the print, it doesn't work until I refresh the page.

Seems like there is a bug in the library itself. Could you please update the code so that we can resolve it on our end.

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md in order the issue to be actionable/valid; as-is this issue will be closed as INCOMPLETE.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
