### ISSUE TITLE
How to set fixed width for PDFViewer

### ISSUE THREAD

**Issue by AK-Bharath** [mozilla/pdf.js#10864]
Hi,

I have the following code as below.  I am working this on a react component  I have pdf's with different widths and heights.  I want to load it in pdfviewer along with pdf find controller.  But I want the viewer to be a fixed size.  but it is not in fixed width it changes with the size of the pdf's

code I have is as follows.

``
if (!onServer) {
  PDFJS = require('pdfjs-dist/web/pdf_viewer').PDFJS;
}

export default class PDFViewer extends Component {
  @autobind
  updateDimensions() {
    if (!this._pdf) {
      return;
    }
    this._pdfViewer.currentScaleValue = 'page-fit';
  }

  constructor(props){
    super(props);

    this.state = {
       height:this.props.containerHeight,
       width:this.props.containerWidth
    }
  }
  componentWillUnmount() {
    window.removeEventListener('resize', this.updateDimensions);
  }

  _loadFile(url, highlight) {
    if (!url) {
      return;
    }

    if (this._lastUrl === url) {
      return;
    }

    this._lastUrl = url;

    // todo: update TS to allow origin from whatever domain is, but for now
    if (/https?:\/\/(www\.)?territorystories\.nt\.gov\.au/.test(url)) {
      url = `/api/proxy?url=${url}`;
    }

    var pdfViewer = new PDFJS.PDFViewer({
      container: this._container,
      removePageBorders: true,
    });

    this._pdfViewer = pdfViewer;

    var pdfFindController = new PDFJS.PDFFindController({
      pdfViewer: pdfViewer,
    });

    // don't scroll
    pdfFindController.updateMatchPosition = () => {};
    // super fragile. Just copy and paste from pdf_viewer.js in PDF.JS and
    // remove scroll.
    pdfViewer._resetCurrentPageView = function() {
        if (this.isInPresentationMode) {
           this._setScale(this._currentScaleValue, true);
        }
        var pageView = this._pages[this._currentPageNumber - 1];
    };

    if (!pdfFindController.state) {
      pdfFindController.state = {};
    }

    pdfViewer.setFindController(pdfFindController);

    this._container.addEventListener('pagesinit', async () => {
       pdfViewer.currentScaleValue = 'page-fit';

       if (highlight) {
          pdfFindController.executeCommand('find', {
              caseSensitive: false,
              findPrevious: undefined,
              phraseSearch: true,
              query: highlight,
              highlightAll: true
          });
       }
    });

    PDFJS.getDocument(url)
      .then((pdf) => {
        this._pdf = pdf;
        pdfViewer.setDocument(this._pdf);
        this.updateDimensions();
    });

   }

  _removeViewer() {
    if (this._pdf) {
      this._pdf.destroy();
      this._pdf = null;
    }
  }

  componentWillUnmount() {
    this._removeViewer();
  }

  componentDidMount() {
    window.addEventListener('resize', this.updateDimensions);
    this._loadFile(this.props.link, this.props.highlight);
  }

  componentDidUpdate(prevProps, prevState) {
     if (prevProps !== this.props) {
         this._loadFile(this.props.link,this.props.highlight);
     }
  }

  render() {
    if (!this.props.link) {
      this._removeViewer();
      return <div/>;
    }

    const item = this.props.item;

    return (
      <div id="pager1"  ref={(container) => {this._container = container;}}>
        <div className="pdfViewer col-11">
        </div>
      </div>);
  }
}
``

I had tried the following code by replacing this code 

``
  /*
    PDFJS.getDocument(url)
      .then((pdf) => {
        this._pdf = pdf;
        pdfViewer.setDocument(this._pdf);
        this.updateDimensions();
    });*/
``

with the below code

``
   var scale,viewPort,width;

    PDFJS.getDocument(url).then((pdf) => {
      this._pdf = pdf;

      pdf.getPage(1).then((page) => {
        viewPort = page.getViewport({scale:1});

        width = this.state.width;

        scale = width / viewPort.width;

      });
      pdfViewer.setDocument(this._pdf);
      pdfViewer._setScale(scale,true);
      this.updateDimensions();
    });
`` 

but I get it is ending same results with different width's for different pdf's

In package.json

I have the following

"pdfjs-dist": "^1.8.492",

I am using ^1.8.492 version of pdfjs-dist.

Any help is highly appreciated.

thanks

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
It's unclear what you actually want to achieve. Fixing the width/height of the viewer can just be done with CSS. If you mean the rendered PDF itself, then that's difficult because pages can have any size. Perhaps you're looking for the "fit width" zoom level. Other than that, without a running example and a clear description of the problem you want to solve, this is not really actionable for us.

**Comment by AK-Bharath** [comment]
Thanks for clarifying me.  Now I had fixed my issue.

Thanks for your help

**Comment by Gzbox** [comment]
@AK-Bharath    I don't know how to combine pdf.js with React. Can you tell me your way? Thank you very much. Can you post your code?
