### ISSUE TITLE
File not loading correctly on most pages

### ISSUE THREAD

**Issue by aguilaair** [mozilla/pdf.js#10876]
Attach (recommended) or Link to PDF file here:

https://examsnap.io/papers/index.php/s/mEBfMpoqrLxwXJx?path=%2FMathematics%20(0580)%2F2019%2FFeburary-March

Open 0580_m19_qp_22.pdf

Configuration:
- Web browser and its version: Chrome 74.0.3729.169
- Operating system and its version: Windows 10 Pro 64-bit (Tried in Linux too)
- PDF.js version: 1.9.426
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the file on **Chrome**
2. View question 9

What is the expected behavior? (add screenshot)

![2019-05-25 correct](https://user-images.githubusercontent.com/29983481/58720843-91dc9000-83d3-11e9-8f09-33bf94175a0d.png)

What went wrong? (add screenshot)

![2019-05-25](https://user-images.githubusercontent.com/29983481/58720850-97d27100-83d3-11e9-81a7-97cfb7e90de0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

By clicking on the file it opens the viewer

Thanks in advance!

**Comment by Snuffleupagus** [comment]
Duplicate of #10860.

**Comment by aguilaair** [comment]
Duplicate of #10860.
