### ISSUE TITLE
Gradient in pdf rendering from LaTeX output problem

### ISSUE THREAD

**Issue by Torrencem** [mozilla/pdf.js#10874]
This issue was found from generating charts from LaTeX. The code used to generate the pdf example can be [found here](https://tex.stackexchange.com/questions/493413/pgfplots-changing-plot-size-breaks-color-map)

## Attach (recommended) or Link to PDF file here:
[badexample.pdf](https://github.com/mozilla/pdf.js/files/3238778/badexample.pdf)

## Configuration:
- Web browser and its version: Tested on Firefox Quantum 67.0 (64-bit)
- Operating system and its version: Windows 10 version 10.0.17134 Build 17134
- PDF.js version: confirmed: (PDF.js: 2.2.71) and (PDF.js: 2.0.943)
- Is a browser extension: Tested using built-in browser version

## Steps to reproduce the problem:
1. Open attached pdf

## What is the expected behavior?

The top of the gradient bar to the right of the chart should not turn white at the top.

Below is a screenshot from Microsoft Edge PDF Viewer (similar results from Chrome (v74.0.3729.169), Adobe Illustrator, and Inkscape, which are all the other pdf viewers I have installed)

![image](https://user-images.githubusercontent.com/13785039/58665761-9768a600-82ff-11e9-8cf3-5338b74acf9d.png)

## What went wrong? (add screenshot)

There's a white gradient at the top of the color bar as seen below:

![image](https://user-images.githubusercontent.com/13785039/58666053-4c02c780-8300-11e9-92f0-c2e8da341766.png)

This screenshot was taken in Firefox (PDF.js: 2.2.71). Same incorrect rendering is produced by the [VSCode LaTeX workshop extension](https://github.com/James-Yu/LaTeX-Workshop) which is how this was discovered (PDF.js: 2.0.943)

**Comment by Snuffleupagus** [comment]
Possibly a duplicate of issue #7339.

**Comment by Torrencem** [comment]
@Snuffleupagus This is the same issue, nice catch! I had been searching and hadn't seen that issue. Thanks
