### ISSUE TITLE
How do I view a PDF file located in Azure Blob Storage

### ISSUE THREAD

**Issue by teemer22** [mozilla/pdf.js#10870]
Hello,

I have a MVC application here in my local that requires to view PDF files uploaded in Azure Blob storage. my PDF JS build and web folders are located in my application directory here in my dev machine. I am encountering error "file origin does not match viewer\'s". I can successfully view if the PDF is in the same folder as my JS files locally. How can I view the PDF uploaded in Azure?

URL: https://checkmateinvoice.blob.core.windows.net/invoices/helloworld.pdf

<img width="719" alt="1" src="https://user-images.githubusercontent.com/44570101/58607019-70df4680-82d0-11e9-9079-291d9f23188b.PNG">
<img width="617" alt="2" src="https://user-images.githubusercontent.com/44570101/58607020-70df4680-82d0-11e9-8aef-3222ecd50308.PNG">

**Comment by Snuffleupagus** [comment]
Please refer to PR #6916.

**Comment by teemer22** [comment]
Hi Jonas and Time, sorry I am new to javascript. I have tried to copy the codes from https://github.com/mozilla/pdf.js/pull/6916/files in my file viewer.js. Still no display of the PDF file and no error message shown.

**Comment by teemer22** [comment]
> Please refer to PR #6916.

Hi Jonas and Tim, sorry I am new to javascript. I have tried to copy the codes from https://github.com/mozilla/pdf.js/pull/6916/files in my file viewer.js. Still no display of the PDF file and no error message shown.

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is, first and foremost, a *bug tracker* and not a general support forum.

Furthermore, without *any* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) provided, nor a working example as outlined in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) it's basically impossible for anyone to help:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
