### ISSUE TITLE
Missing text when rendering PDF as html

### ISSUE THREAD

**Issue by lzzzfelipe** [mozilla/pdf.js#10883]
Attach (recommended) or Link to PDF file here: 

https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/pub/welcome.pdf

Configuration:
- Web browser and its version: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- Operating system and its version: OSX 10.13.4
- PDF.js version: 2.2.2
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the PDF and display it

What is the expected behavior? (add screenshot)

The text overlay should contain the phrase "English and French are the two official languages", the top of page 22.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/5113327/58891561-b8901480-86ba-11e9-91bc-cbed6584b1b9.png">

What went wrong? (add screenshot)

The text overlay does not contain the phrase "English and French are the two official languages", at the top of page 22.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, when using the latest version of PDF.js (which is `2.2.199` as of this writing), as found at https://mozilla.github.io/pdf.js/web/viewer.html

> PDF.js version: 2.0.0

That *exact* version number has never existed; which version did you actually test?

**Comment by lzzzfelipe** [comment]
Thanks @Snuffleupagus , I just corrected the version to `2.2.0`.
Will try with the `2.2.199` as you suggested.

**Comment by Snuffleupagus** [comment]
> I just corrected the version to `2.2.0`.

Huh, given how the versioning of PDF.js works I'm not sure if that *exact* version number has existed either...

**Comment by lzzzfelipe** [comment]
@Snuffleupagus, sorry I was given the version by a colleague and he was mistaken. I took a look at the source code now, it is actually `2.2.2` (https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.2.2/pdf.js).

**Comment by lzzzfelipe** [comment]
@Snuffleupagus , thanks for testing it out. It also works for me using the latest version. Will upgrade.
