### ISSUE TITLE
Detail not appearing for the PDF document when using the Viewer

### ISSUE THREAD

**Issue by martf72** [mozilla/pdf.js#10886]
Attach (recommended) or Link to PDF file here: 
[Royal London Sterling Credit Fund Z Inc KIID.PDF](https://github.com/mozilla/pdf.js/files/3256128/Royal.London.Sterling.Credit.Fund.Z.Inc.KIID.PDF)
- Edge Version - 44.17763.1.0
- Windows 10 Pro 10.0.17763
- PDF.js version: 2.1.32
- Is a browser extension: No

Steps to reproduce the problem:
1. Run the attached PDF through the viewer.

What is the expected behavior? (add screenshot) Viewer will display the document content as per the PDF.

What went wrong? (add screenshot) No content in the viewer.

![ScreenCapture](https://user-images.githubusercontent.com/50982868/58940192-c902c680-8770-11e9-9093-2aaa1778dfff.PNG)

The body of the document is missing when using the viewer but exists withing the PDF.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  Using Edge for the PDF.js viewer and viewing the actual PDF directly.

**Comment by Snuffleupagus** [comment]
WFM, when using PDF.js version `2.2.199` in Firefox Nightly 69.

> Edge Version - 44.17763.1.0

Please note the limited support status for that browser, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 2.1.32

Even though it's probably not relevant for *this* particular issue, please note that in general you're only advised to use officially released versions as found at https://github.com/mozilla/pdf.js/releases

**Comment by timvandermeij** [comment]
Works for me as well on Arch Linux. It looks like this should either be reported to the Edge bug tracker or it's a configuration issue. You could try updating your graphics drivers since that has already fixed many of such issues before.

**Comment by martf72** [comment]
So this isn't a browser specific issue as it's doing the same in the latest version of Chrome but the raised point of the PDF.js version being behind is worth investigating so will give that a try.

**Comment by phila66** [comment]
Hi,

I've been given the task of updating to the latest pdf.js (pdfjsVersion = '2.1.266'; var pdfjsBuild = '81f5835c';) to see if it fixes the above issue: it doesn't, be it in Chrome, Edge or Firefox. I don't think it's a browser thing.

But.. I suspect the reason it may work in one environment and not others, the console is showing the errors:
Warning: Error during font loading: this._map[charCode].charCodeAt is not a function
Warning: TypeError: Cannot read property 'length' of undefined at CFFFont_hasGlyphID

..the PDF contains four embedded fonts, Akzidenz-GroteskBE-Regular, and GeorgiaPro Bold/Italic/Regular; if you've got those installed on your PC or a family substitute it recognizes, then it may work in one place but not another.

My JS debugging skills are not up to working out exactly where/what is happening, I'm afraid.

Any more thoughts?

Thank you

**Comment by Snuffleupagus** [comment]
> Warning: Error during font loading: this._map[charCode].charCodeAt is not a function

Please see https://github.com/mozilla/pdf.js/issues/9137#issuecomment-344595455 and all the issues linked from it, i.e. this isn't a bug in the PDF.js library but an issue elsewhere in your application.

**Comment by phila66** [comment]
You're right - it works in the viewer (sorry, had missed the "Open file" option in the viewer)
Thank you for pointing me in the right direction, should be able to bash one of the developers over the head here until they give me the right answer

**Comment by phila66** [comment]
Many thanks for your speedy response: I found some ancient (circa 2011) polyfill code that was all of the form 
Array.prototype.<method>= function{}
..changing it to the 
if (!Array.prototype.getListWhere) {
    Object.defineProperty(Array.prototype, 'getListWhere', {
        value: function (key, value) {},
        configurable: false}
etc.
Has sorted the problem.
