### ISSUE TITLE
iOS find in page does not work on Firefox

### ISSUE THREAD

**Issue by tbenst** [mozilla/pdf.js#10892]
Configuration:
- Web browser and its version: Firefox 15.1
- Operating system and its version: iOS 
- PDF.js version: not sure
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a pdf on iOS Firefox 
2. Search for a word that appears
3. Open same pdf in safari
4. Search for same word
5. See word get highlighted

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Firefox 15.1
> 
> Operating system and its version: iOS

Assuming that this is referring to https://github.com/mozilla-mobile/firefox-ios, then I don't believe that it utilizes PDF.js (i.e. this project) at all and consequently this issue is thus invalid *here*.
