### ISSUE TITLE
Merging of single page pdfs

### ISSUE THREAD

**Issue by adame21** [mozilla/pdf.js#10899]
Hi,
I'm trying to use this package to merge single page pdfs on a nodejs server.
The documentation is very lacking and I find it very confusing to use especially since this package is both server and client side to my understanding.
Could I possibly get a starting point or know what are the relevant methods? I have the pdfs both as buffers and as actual files on a local folder.
Any help would be appreciated.
Thanks!

**Comment by Snuffleupagus** [comment]
> I'm trying to use this package to merge single page pdfs on a nodejs server.

That would required *editing* of PDF file, which the PDF.js project isn't intended to do as clearly outlined in both the [README](https://github.com/mozilla/pdf.js#pdfjs-) and the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations); most likely you're actually looking for a different project here.
