### ISSUE TITLE
How can i get annotation start position and text.

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#10894]
Attach (recommended) or Link to PDF file here: 
![error](https://user-images.githubusercontent.com/7369163/59188832-34480080-8b96-11e9-8be7-0d93b887208a.png)

Is there a way to find start position of an annotation word. 

On attached file i want to get position of word "**twentieth**" vice versa  need to find the word using position in "**pdf**"

**Comment by timvandermeij** [comment]
You can use the `getAnnotations` API to get all annotations with their metadata (such as `rect` for the position on the page).

**Comment by Mowmowj** [comment]
@timvandermeij  
by pdfjs api  getPageContent could reture the text line information it include the line coordinate.
is there any way to get a single word coordinate. 
for example: one text line is "it is hello world" in pdfjs text layer.
and i want get the "hello world" coordinates.
