### ISSUE TITLE
Consider renaming the beforeprint/afterprint code

### ISSUE THREAD

**Issue by jwatt** [mozilla/pdf.js#10891]
When trying to debug a Firefox related beforeprint/afterprint DOM event issue, I ended up looking at all occurrences of those strings in the code:

https://searchfox.org/mozilla-central/search?q=beforeprint

At first I thought PDF.js was using these DOM events, especially given the line:

```
    window.addEventListener('beforeprint', _boundEvents.windowBeforePrint);
    window.addEventListener('afterprint', _boundEvents.windowAfterPrint);
```

here:

https://searchfox.org/mozilla-central/rev/ee806041c6f76cc33aa3c9869107ca87cb3de371/browser/extensions/pdfjs/content/web/viewer.js#1495

I *think* that this (and all code) related to the strings "beforeprint"/"afterprint" is actually noting to do with the DOM events though.

If that is the case, it would be less confusing if these events had something to distinguish them. Perhaps "beforeprinting"/"afterprinting"?

**Comment by Snuffleupagus** [comment]
> At first I thought PDF.js was using these DOM events, especially given the line:
> ```javascript
> window.addEventListener('beforeprint', _boundEvents.windowBeforePrint);
> window.addEventListener('afterprint', _boundEvents.windowAfterPrint);
> ```

Given that these event listeners *are* actually attached to the `window`, I'm honestly confused as to what they would be listening for if not the `beforeprint`/`afterprint` DOM events!?

Changing that would first of all completely break printing of PDF files in Firefox, and secondly it also feels (at least to me) like the issue doesn't clearly outline what's actually wrong with the current code.

**Comment by jwatt** [comment]
For background, I'm making changes to the Firefox printing code. I was trying to figure out what invariants I shouldn't break, which led me to wonder if I would break the PDF.js code, but it isn't clear to me what that code is doing.

My confusion is mainly that PDF.js appears to fire its own custom "beforeprint" event:

https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/web/pdf_print_service.js#L219

but I note it also has a 'beforeprint' message:

https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/web/app.js#L1395

It is unclear to me what the interaction between the CustomEvent event and browser native 'beforeprint' Event events is. It seems strange that PDF.js would fire its own 'beforeprint' event in it's window.print() override, unless it completely bypasses the browser print code when that is called.

At any rate, it sounds like this CustomEvent is indeed supposed to trigger normal onbeforeprint handlers so, as you say, renaming is not appropriate.

**Comment by Snuffleupagus** [comment]
> My confusion is mainly that PDF.js appears to fire its own custom "beforeprint" event:
> 
> https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/web/pdf_print_service.js#L219

Please keep in mind that there's the *general* PDF.js viewer, and the one that's shipping built-in to Firefox. If you're concerned with the latter one, as it seems here, then the relevant printing code can be found in https://github.com/mozilla/pdf.js/blob/master/web/firefox_print_service.js which does not dispatch any events (DOM or otherwise).

The file you referenced contains code to support various older browsers, without proper printing support, and thus contains some "hacks" to get things to (mostly) work.
