### ISSUE TITLE
Some PDFs throw exception after Chrome 75 update

### ISSUE THREAD

**Issue by vicinting** [mozilla/pdf.js#10914]
Attach (recommended) or Link to PDF file here:
https://rockendintv.blob.core.windows.net/public/problem.pdf

Configuration:
- Web browser and its version: Chrome 75 (did not occur in Chrome 74)
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943
- Is a browser extension: not sure what this means

Steps to reproduce the problem:
1. Set above pdf as src of PDF JS
2. Get a couple of console errors:

![image](https://user-images.githubusercontent.com/4598010/59819849-f18fe080-936c-11e9-9a8d-b2dc799d51f4.png)

Some PDF files render without issues, but some do not (like the one above) and show a couple of console errors. Tried to debug but the src is bundled/minified but from what I see looks like related to parseInt and Content-Range.

**Important Note**: This did not occur when using Chrome 74, only occurred when we updated to Chrome 75. But I was able to replicate it using IE11 in the past.

**Comment by Snuffleupagus** [comment]
> This did not occur when using Chrome 74, only occurred when we updated to Chrome 75.

In that case this really sounds like a regression in the browser itself, rather than a bug in the PDF.js library, and as such you'll need to report it to the browser vendor instead (since we cannot fix bugs in the browser itself).

> But I was able to replicate it using IE11 in the past.

Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for IE11 is *very* limited in the PDF.js library (and it will be completely removed in the future).

**Comment by vicinting** [comment]
Shouldn't these errors be properly handled though? One thing I noticed is that the error is not caught in the catch method of the promise. i.e.:

```
PDFJS.getDocument(this.src)
   .then((pdf) => {
      // logic
   })
   .catch((error) => {
      **this is not called when exception is thrown**
   });
```

**Comment by THausherr** [comment]
@vicinting the redaction of your file is incomplete. Text extraction shows the word "Duffy" in the subject line.

**Comment by timvandermeij** [comment]
@vicinting That's because `getDocument` returns a loading task object and not a promise. To get the promise, you need to use `getDocument.promise.then()`; see: https://github.com/mozilla/pdf.js/blob/cad0e612622a1384093006677f8e5b9b725fc2d0/examples/components/simpleviewer.js#L68

**Comment by vicinting** [comment]
Thank you @timvandermeij, I'm not very familiar with the library and just inherited a project that used this. Should read up more on the library when I have time. Thanks!
