### ISSUE TITLE
File not redrawn in Chrome after visiting some sites (e.g., amazon.com)

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#10915]
Attach (recommended) or Link to PDF file here: https://arxiv.org/pdf/1808.01102.pdf

Configuration:
- Web browser and its version: Chrome Version 77.0.3830.3 (Official Build) canary (64-bit)
- Operating system and its version: Windows 10.0.17134 
- PDF.js version: 2.2.191
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open file
2. Open new tab
3. Open amazon.com
4. Switch back to the tab with the file

What is the expected behavior? (add screenshot)
![pdf js_correct](https://user-images.githubusercontent.com/2311076/59819777-0b600200-9332-11e9-9f2d-e21cd7778632.jpg)

What went wrong? (add screenshot)
![pdf js_bad](https://user-images.githubusercontent.com/2311076/59819787-131fa680-9332-11e9-90db-75203b933a65.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This really sounds entirely like a browser bug, rather than a PDF.js library one, and as such you'll need to report it to the browser vendor instead (since we cannot fix broken canvas rendering of the browser itself).

**Comment by qwer1304** [comment]
Except for some weird behavior:

- it happens **only** on pages drawn by the extension
- if I have **two** tabs open with the extension, when one of them gets corrupted, activating the **second** one and then switching back to the **first** one clears the problem

So it sounds like the problem is specific to the extension (not necessarilly in the extension, but to the interaction of the extension with the browser)

**Comment by qwer1304** [comment]
Found the culprit: the Set Character Encoding extension.
Closing.
Sorry.
