### ISSUE TITLE
 invalid pdf structure on IOS11 webview

### ISSUE THREAD

**Issue by weijiafen** [mozilla/pdf.js#10916]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: safari 's webview
- Operating system and its version: 11.2.6IOS
- PDF.js version: 2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. I import pdf.js at front end and set pdfjsLib.GlobalWorkerOptions.workerSrc='static/resource/pdf.worker.js'
2.var loadingTask =pdfjsLib.getDocument(file.url);
3.loadingTask.promise.then(()=>{getpage and render}).catch(()=>{toast error info})

What is the expected behavior? (add screenshot)
can preview the pdf file

What went wrong? (add screenshot)
It 's fine at first time ,but Toast ” invalid pdf structure“  at second times and afterwards.It 's fine on IOS12 and android.I think it maybe load the file on network the first time ,but use cache afterwards，there are some differences between them.I dont khow how to fix it.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> It 's fine at first time ,but Toast ” invalid pdf structure“ at second times and afterwards.It 's fine on IOS12 and android.I think it maybe load the file on network the first time ,but use cache afterwards，there are some differences between them.

This really sounds entirely like a browser bug, rather than a PDF.js library one, and as such you'll need to report it to the browser vendor instead (since we cannot fix broken caching of the browser itself).
