### ISSUE TITLE
Loading Pdf file from url directly fails

### ISSUE THREAD

**Issue by 28development** [mozilla/pdf.js#10910]
Attach (recommended) or Link to PDF file here: 
https://skillreader.fra1.digitaloceanspaces.com/files/1560499418.pdf
Furthermore the pdf file is being uploaded on digital ocean spaces(cloud), in the edit view I am trying to access the downloaded pdf file.

Configuration:
- Web browser and its version: nginx version: nginx/1.15.8
- Operating system and its version: Ubuntu 18.04.2 LTS
- PDF.js version:2.2.211 (https://mozilla.github.io/pdf.js/build/pdf.js)
- Is a browser extension:

Steps to reproduce the problem:
1. Open the edit view on my webapp and select the uploaded pdf
2. edit site loads but fails

Error:

> [[PromiseStatus]]: "rejected"
> [[PromiseValue]]: Error: Invalid page request at WorkerTransport.getPage (https://mozilla.github.io/pdf.js/build/pdf.js:11752:31) at PDFDocumentProxy.getPage (https://mozilla.github.io/pdf.js/build/pdf.js:10333:30) at renderPage (http://myapp...
> 
> api.js:2201 Uncaught (in promise) Error: Invalid page request
>     at WorkerTransport.getPage (api.js:2201)
>     at PDFDocumentProxy.getPage (api.js:620)
>     at renderPage (app.js:4874)
>     at app.js:4938

Which refers to this method:

```

            // In my create view I call it without any param, in my edit view I call it with param, so I can get the correct data from the database
            loadPdf(file) {
                const url = ((typeof file === 'undefined') || (typeof file.location === 'undefined')) ? 
                        this.uploaded.location : 
                        file.location;

                this.setElements();
                this.setCanvas();

                if (this.file.visible) this.rmPdf(false);

                this.pdfDoc = null;
                
                let pageNum = (typeof file === 'undefined' || typeof file.page_number === 'undefined') ? 1 : file.page_number,
                    pageIsRendering = false,
                    pageNumIsPending = null;

                const canvas = document.querySelector('#file-render'),
                    ctx = canvas.getContext('2d');

                // Render the page
                const renderPage = num => {
                    pageIsRendering = true;

                    console.log(this.pdfDoc.getPage(num)); // ----> error happens here

                    // Get page
                    this.pdfDoc.getPage(num).then(page => {

                        // Set scale
                        const canvasBodyWidth = document.querySelector('#canvas-body').offsetWidth;
                        const viewport = page.getViewport(canvasBodyWidth / page.getViewport(1.0).width);

                        canvas.width = viewport.width;
                        canvas.height = viewport.height;

                        const renderCtx = {
                            canvasContext: ctx,
                            viewport
                        };

                        page.render(renderCtx).promise.then(() => {
                            pageIsRendering = false;

                            if (pageNumIsPending !== null) {
                                renderPage(pageNumIsPending);
                                pageNumIsPending = null;
                            }
                        });

                        this.markElement();

                        // Output current page
                        document.querySelector('#page-num').textContent = num;
                    })
                };

```
What is the expected behavior?
The expected behavior is to load the pdf file with the given page number from the database, if there is no page number is selects the first page.

What went wrong?
The create method is identical to the method above, I just call it without a parameter.
Logging the url variable returns the correct url in both cases.

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
> 
>     1. Open the edit view on my webapp and select the uploaded pdf
> 
>     2. edit site loads but fails

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
"Invalid page request" is thrown at https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/src/display/api.js#L2201 and indicates that the page number is not within the valid range. Aside from that, the comment above applies for further assistance.

**Comment by 28development** [comment]
I fixed it, it was an error on my side somehow it did not get the correct page number.
This was wrong:

`let pageNum = (typeof file === 'undefined' || typeof file.page_number === 'undefined') ? 1 : file.page_number,`

Updated it to following:

`let pageNum = (typeof file === 'undefined' || typeof file.page_number === 'undefined') : file.page_number ? 1,`
