### ISSUE TITLE
Using `PDFViewerApplication.open` is indeed the correct way to do this and should allow you open a PDF file using raw binary data (use typed arrays). Closing as answered.

### ISSUE THREAD

**Issue by xtsudhan** [mozilla/pdf.js#10923]
Using `PDFViewerApplication.open` is indeed the correct way to do this and should allow you open a PDF file using raw binary data (use typed arrays). Closing as answered.

_Originally posted by @timvandermeij in https://github.com/mozilla/pdf.js/issues/9487#issuecomment-372036644_

**Comment by xtsudhan** [comment]
But PDFViewerApplication is undefined it is saying .

**Comment by Snuffleupagus** [comment]
Duplicate of #10922; please refrain from knowingly open duplicate issues!

**Comment by xtsudhan** [comment]
to use PDFViewerApplication.Open which js and version we need to refer as source in our javascript?

Currently I am using PDF.js 2.2.2

**Comment by Even-Lau** [comment]
I came across the same problem. Is there any solution? @xtsudhan
