### ISSUE TITLE
PDFviewerapplication is not working

### ISSUE THREAD

**Issue by xtsudhan** [mozilla/pdf.js#10922]
I try to open a pdf viewer with my base64 data . So I thought of using PDFViewerApplication.open in my javascript code but its saying PDFviewerapplication is undefined. I am referencing latest pdf.js

Or cloud you please let me know the sample javascript code to open a pdf all pages in a new window not using the canvas

**Comment by xtsudhan** [comment]
Or cloud you please let me know the sample code to open a pdf all pages in a new window not using the canvas

**Comment by Snuffleupagus** [comment]
If you ignore both https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md when opening an issue no help can/will be provided. Note in particular:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
There is a base64 data example at https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html. Other than that, the comment above applies.
