### ISSUE TITLE
Error handling when pdf.js fetch data from another server

### ISSUE THREAD

**Issue by LOGANLEEE** [mozilla/pdf.js#10928]
I'm using `viewer.html?file=\APICall\` and it works really well.
But sometimes server will return corrupted file or encoded file on purpose.
In that case, i want to execute `window.location.href = \APICall\ ` to download that file.

**summaries of this question) if viewer.html has any kind of error then execute `window.location.href` script to download directly.** 

can i get help?

Really appreciate of your effort that built this lib.
thanks.

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that this is, first and foremost, a *bug tracker* and not a general support forum.

> [...] if viewer.html has any kind of error then execute `window.location.href` script to download directly.

It's not at all clear what `window.location.href` has to do with PDF files that fail to, but it might be possible to trigger downloading from the `loadingTask.promise` rejection handler; e.g. in https://github.com/mozilla/pdf.js/blob/2cc0bfd1b17a9f111b7c05253108563276fb31b8/web/app.js#L682-L709

Finally, without *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INVALID. See also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by LOGANLEEE** [comment]
Thank you for your reply.
for more detail, i put `build`and`web`folder to public folder of react project.

To call viewer i did ` window.open('blabla/web/viewer.html?file=\API call address\', '_blank')`
then server return requested file to viewer.html.

The purpose of `window.location.href' is just calling Download API and will be returned File that i requested from server if the request file isn't fit for viewer call method.

Because some files would be encrypted or corrupted according to company's security policy.

If so, the user have to just download it and decode it by decoding program which is installed in user's local pc.

**Comment by Snuffleupagus** [comment]
> for more detail, i put `build`and`web`folder to public folder of react project.

That's not at all the details requested here, nor is it anywhere near sufficient information, please actually take the time to read and follow *all* of https://github.com/mozilla/pdf.js/issues/10928#issuecomment-505325701 carefully!

Besides, https://github.com/mozilla/pdf.js/issues/10928#issuecomment-505325701 even outlines a possible solution: Did you actually try calling `PDFViewerApplication.download()` from the `loadingTask.promise` rejection handler mentioned above?

**Comment by timvandermeij** [comment]
Closing until all of the details are provided.
