### ISSUE TITLE
Using PDFSinglePageViewer instead of PDFViewer in the viewer app causes page rendering problems in IE11 and Edge

### ISSUE THREAD

**Issue by EugeneSqr** [mozilla/pdf.js#10920]
Attach (recommended) or Link to PDF file here: https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: IE11, Edge
- Operating system and its version: Windows 10
- PDF.js version: latest code from master
- Is a browser extension: no

Steps to reproduce the problem:
1. I would like to display one page at a time; it looks like the right way would be using the ``PDFSinglePageViewer`` class. Therefore I import it the module inside app.js [here](https://github.com/mozilla/pdf.js/blob/1c9a69db82773771216bc051f4f624ee1032e102/web/app.js#L50) and using it instead of ``PDFViewer`` [here](https://github.com/mozilla/pdf.js/blob/1c9a69db82773771216bc051f4f624ee1032e102/web/app.js#L320) like this:
```javascript
this.pdfViewer = new PDFSinglePageViewer({...
```
2. Then I run ``gulp generic`` and open the test file in IE11 (or Edge) like this ``http://localhost:8888/build/generic/web/viewer.html?file=%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf``. The first page is displayed without any problems.
3. Then I navigate to the second page.

What is the expected behavior? (add screenshot)
![second-page-chrome](https://user-images.githubusercontent.com/1623068/59859533-8c94b480-9385-11e9-8ea0-ab4bf55f4b86.png)

What went wrong? (add screenshot)
![second-page-edge](https://user-images.githubusercontent.com/1623068/59858716-2e1b0680-9384-11e9-8804-6a691e52b336.png)

The problem occurs only on IE and Edge. With Chrome, Firefox, Safari it's fine both on desktops and mobile devices.

**Comment by Snuffleupagus** [comment]
> The problem occurs only on IE and Edge. With Chrome, Firefox, Safari it's fine both on desktops and mobile devices.

Unfortunately IE 11 and IE Edge are not fully supported, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, and this issue is thus INVALID.

**Comment by EugeneSqr** [comment]
Any suggestions on where to start looking, so I can try fixing it myself?

**Comment by Snuffleupagus** [comment]
> Any suggestions on where to start looking,

No idea, unfortunately.

>  so I can try fixing it myself?

Please keep in mind that, given that it's limited to IE 11/Edge, a patch touching anything *except* https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js most likely won't be accepted either since support for IE 11/Edge will be completely removed in a (yet to be decided) future PDF.js release.

**Comment by EugeneSqr** [comment]
It looks like both IE and Edge have problems with rendering pages in-memory. Therefore both ``documentFragments`` and simple in-memory divs won't work. If you want ``PDFSinglePageViewer`` to work in these browsers, consider adding a dedicated hidden div to the viewer html page and using it instead.

The [line responsible for this](https://github.com/mozilla/pdf.js/blob/1c9a69db82773771216bc051f4f624ee1032e102/web/pdf_single_page_viewer.js#L41):
```javascript
this._shadowViewer = document.createDocumentFragment();
```
should be replaced with something like this:
```javascript
this._shadowViewer = createShadowViewer();
function createShadowViewer() {
  var shadowViewer = document.createElement('div');
  shadowViewer.style.display = 'none';
  document.body.appendChild(shadowViewer);
  return shadowViewer;
}
```
