### ISSUE TITLE
"Redirected too many times error" when attempting to view all pdf files via test server on Windows

### ISSUE THREAD

**Issue by monchouchou** [mozilla/pdf.js#10933]
Attach (recommended) or Link to PDF file here:
_None_

Configuration:
- Web browser and its version: _Chrome v75_
- Operating system and its version: _Windows 10, 64-bit_
- PDF.js version: _Extension build number 213_
- Is a browser extension: _No_

Steps to reproduce the problem:
1. gulp server
2. Open Chrome and open URL http://localhost:8888/test/pdfs/?frame

What is the expected behavior? (add screenshot)
To be able to view all test pdf files in a pane.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/52257912/60285087-c720c300-992a-11e9-9b1b-109316439c74.png)

The URL entered changed from http://localhost:8888/test/pdfs**/**?frame to http://localhost:8888/test/pdfs**//**?frame, followed by a redirected too many times error.

A stack trace, based on preliminary debugging is below,

```
$ gulp server
[22:29:23] Working directory changed to ~\pdf.js
[22:29:26] Using gulpfile ~\pdf.js\gulpfile.js
[22:29:26] Starting 'server'...

### Starting local server
Server running at http://localhost:8888/
Trace: Redirection!
    at statFile (C:\Users\ragha\pdf.js\test\webserver.js:149:17)
    at FSReqWrap.oncomplete (fs.js:154:5)
Trace: Redirection!
    at statFile (C:\Users\ragha\pdf.js\test\webserver.js:149:17)
    at FSReqWrap.oncomplete (fs.js:154:5)
Trace: Redirection!
    at statFile (C:\Users\ragha\pdf.js\test\webserver.js:149:17)
    at FSReqWrap.oncomplete (fs.js:154:5)
Trace: Redirection!
    at statFile (C:\Users\ragha\pdf.js\test\webserver.js:149:17)
    at FSReqWrap.oncomplete (fs.js:154:5)
Trace: Redirection!
    at statFile (C:\Users\ragha\pdf.js\test\webserver.js:149:17)
    at FSReqWrap.oncomplete (fs.js:154:5)
```

**Comment by monchouchou** [comment]
I was trying to get started with pdf.js and encountered this issue.

I have debugged it and it seems to be an due to the _path.normalize(...)_ function used in **tests/webserver.js, line 87**.
This is within the __handler_ function of Webserver.

```
  _handler: function (req, res) {
    var url = req.url.replace(/\/\//g, '/');
    var urlParts = /([^?]*)((?:\?(.*))?)/.exec(url);
    try {
      // Guard against directory traversal attacks such as
      // `/../../../../../../../etc/passwd`, which let you make GET requests
      // for files outside of `this.root`.
      //Offending function
      var pathPart = path.normalize(decodeURI(urlParts[1]));
    }
```
Since path.normalize will return a Windows style path on a Windows system, the pathPart variable is of the form "\tests\pdfs\".

This causes the code in the function _statFile(...)_, **webserver.js, line 139**, to error out, since the RegEx shown below will evaluate to _false_, causing the block shown to be executed.

```
      if (isDir && !/\/$/.test(pathPart)) {
        res.setHeader('Location', pathPart + '/' + urlParts[2]);
        res.writeHead(301);
        res.end('Redirected', 'utf8');
        return;
      }

```
I was hoping I could work on this, since this is my first time contributing to any open source project and I'd like to learn how things work sooner rather than later.

**Comment by Snuffleupagus** [comment]
This seems to be a regression from PRs #10304 and/or #10463.

/cc @april and @timvandermeij

**Comment by april** [comment]
I can take a look at this, but it may take me a while to spin up a Windows machine and get everything working.

@monchouchou, can you share some details about your Windows setup? Is this all running under the Windows Subsystem for Linux?

**Comment by monchouchou** [comment]
@april, no, this is all on Windows 10 + MinGW. Node.js version 10.16.0 (LTS)

**Comment by monchouchou** [comment]
I do have a Linux VM that I could use if there's any specific need.

**Comment by Snuffleupagus** [comment]
> [...] but it may take me a while to spin up a Windows machine and get everything working.

Instinctively, I'd assume that this is now generally broken regardless of platform and/or operating system.
@timvandermeij I seem to recall you being on Linux; if so can you test this by running `gulp server` and then visting http://localhost:8888/test/pdfs/?frame in a browser?

**Comment by timvandermeij** [comment]
Works for me on Arch Linux. After `gulp server` I get the page with the panel on the right. If I click one of the PDF files, it loads in the left panel.

**Comment by april** [comment]
I remember running the same test on macOS without any issue. I feel like this probably would have been found before if it was a common issue, as the PRs were merged about 9 and 6 months ago, respectively.

**Comment by Snuffleupagus** [comment]
> I feel like this probably would have been found before if it was a common issue,

Well, this regression basically means that a potentially very useful tool testing/debugging is broken on Windows (which isn't exactly an uncommon OS).

**Comment by vlastimilmaca** [comment]
+1 on this ... Same issue, but I was just too lazy to debug it and report it ...

**Comment by monchouchou** [comment]
If it's alright, I think I might get started on this?

**Comment by timvandermeij** [comment]
Yes, feel free to make a patch for this.
