### ISSUE TITLE
Pages are not loading in PDF reader on Xamarin app

### ISSUE THREAD

**Issue by mohanssbs** [mozilla/pdf.js#10930]
This is a Xamarin mobile application. In the Android app, pdf reader opens when click on a ebook. But not showing any page inside the reader.

![Screenshot_2019-06-26-12-32-12](https://user-images.githubusercontent.com/29968142/60158451-c430b000-980e-11e9-8ec4-19cd7aeea997.png)
Loading like this.

![Screenshot_2019-06-26-12-32-20](https://user-images.githubusercontent.com/29968142/60158468-d01c7200-980e-11e9-8909-43294bca833e.png)
After click on PDF book, showing this. But not loading pages.

But, This works properly in January this year. But now not working. What can be the reason ?

**Comment by Snuffleupagus** [comment]
Without *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INVALID; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
