### ISSUE TITLE
Document pdfjs-dist/webpack

### ISSUE THREAD

**Issue by maclockard** [mozilla/pdf.js#10940]
The current webpack example makes no mention of this as an option or how to correctly use it with worker loader. Instead, I only found it by looking at this comment: https://github.com/mozilla/pdf.js/issues/7612#issuecomment-315180521

**Comment by dhuang612** [comment]
I would like to take a look at this, it's my first time trying to contribute to an open source project

**Comment by timvandermeij** [comment]
Exactly. I think a solution for this would be to extend https://github.com/mozilla/pdf.js/blob/master/examples/webpack/README.md with information about `pdfjs-dist/webpack`.

**Comment by mcorteel-harel** [comment]
Just to clarify, what I get from this is that if you are using webpack, you should import PDF.js this way:
```
import * as pdfjsLib from 'pdfjs-dist/webpack';
```
instead of 
```
import * as pdfjsLib from 'pdfjs-dist';
```
I was half-considering not coming back to my job and changing my name before I stumbled on this! Almost lost a full day of work on this...

**Comment by erkebek** [comment]
Would be great to have documentation also on how to use built-in viewer with Webpack.
