### ISSUE TITLE
When the number of pages loaded reaches tens of thousands, the page is a bit jammed

### ISSUE THREAD

**Issue by tanglinhai** [mozilla/pdf.js#10942]
Attach (recommended) or Link to PDF file here:
[https://tanglinhai.github.io/repo/images/pdftip.png](https://tanglinhai.github.io/repo/images/pdftip.png)
Configuration:
- Web browser and its version:  Version 74.0.3710.0 (official version) (32 bits)
- Operating system and its version:  window10
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. Reaction delay of pulling scroll bar.
2. On my 32-bit chrome browser, even pop up the pop-up window below, which suggests stopping the script running.
3. If external pages are zoomed in and out by introducing change components, the performance of changing window size will be worse.

What is the expected behavior? (add screenshot)
1. Rolling smoothness effect
2, change the window not too carton.
3. No pop-up stop script prompt

I think the reason for this is that the container div that loads the page is not the same as the content.
I provide a rolling loading container scheme, and after testing, the results are feasible.
Examples can be seen:
Effect before modification: https://tanglinhai.github.io/repo/oldPDF.html
Modified effect: https://tanglinhai.github.io/repo/newPDF.html
After the modification, some bugs were generated. After testing and repairing,a formal and feasible version was submitted.  I wanted to launch a pull request.

**Comment by tanglinhai** [comment]
The test found that it works better when the content of the page is not empty. Because GitHub personal website is not allowed to upload more than 100M files, so in this example I use 40,000 PDF pages, the content is empty. It's to reduce the volume. You can download the code in the example to load large files with content locally, which is more effective.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> https://tanglinhai.github.io/repo/images/pdftip.png

That's not a PDF file file, but rather only an image

**Comment by tanglinhai** [comment]
https://tanglinhai.github.io/repo/newPDF.html 
This should be the link you want.

**Comment by tanglinhai** [comment]
That picture is a screenshot of the problem PDF created on my 32-bit Chrome browser on my local machine

**Comment by tanglinhai** [comment]
Amendments:

1. Do not add div to the DOMTree in the PDFPageView constructor except for the first and last pages (to initialize the height of the scrollbar)

2. Page layout in page container uses absolute positioning.

3. Scroll there and load the page containers and content of the visual area. (And before you delete the container, the content will be deleted as well.)

4. To use absolute layout, we need to know the left top width height equivalence of the page. At present, the location information is stored in position in PDFPageView constructor. After calculating the location information inside, the layout operation is carried out.

5. All code that affects performance has been optimized: for example, using this layout, you don't need to know whether the scrollbar is rolling up or down, so that part of the scrollbar code can be removed.

**Comment by tanglinhai** [comment]
@Snuffleupagus This is a performance issue. It's not a PDF bug. You can also test if you have a large file with many pages locally.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> https://tanglinhai.github.io/repo/images/pdftip.png

That's not a PDF file, as requested, but rather an image. (The purpose of the issue template is to provide *all* of the requested information up-front, to save time.)

> Web browser and its version: latest
>
> PDF.js version: latest

Neither of the above are helpful either, since the word "latest" doesn't really provide any useful/meaningful information here.

---

It appears that this is the file you should have attached above: https://raw.githubusercontent.com/tanglinhai/repo/master/document/test.pdf

Opening it with any PDF viewer I've tried, including Adobe Reader, is a bit slow initially which is probably to be expected given just how long the document actually is. In practice, PDF files this large isn't that common.

> After the modification, some bugs were generated. After testing and repairing,a formal and feasible version was submitted. I wanted to launch a pull request.

The problem with your PR, assuming you're referring to #10924, was that it was *way* to large and complicated for anyone to test and review. Not to mention that it would have made the code in question almost unmaintainable, and any bugs/regressions (of which the above suggests there were a few) would have been extremely difficult to deal with.

Honestly, given the specialized use-case here (with *huge* files) it's really not at all clear that you want to add too much complication to the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) since it must be possible to maintain it. Also, please keep in mind that it's used as the PDF Viewer in Firefox, and we don't want to risk unnecessary regressions there.

**Comment by tanglinhai** [comment]
> > Attach (recommended) or Link to PDF file here:
> > https://tanglinhai.github.io/repo/images/pdftip.png
> 
> That's not a PDF file, as requested, but rather an image. (The purpose of the issue template is to provide _all_ of the requested information up-front, to save time.)
> 
> > Web browser and its version: latest
> > PDF.js version: latest
> 
> Neither of the above are helpful either, since the word "latest" doesn't really provide any useful/meaningful information here.
> 
> It appears that this is the file you should have attached above: https://raw.githubusercontent.com/tanglinhai/repo/master/document/test.pdf
> 
> Opening it with any PDF viewer I've tried, including Adobe Reader, is a bit slow initially which is probably to be expected given just how long the document actually is. In practice, PDF files this large isn't that common.
> 
> > After the modification, some bugs were generated. After testing and repairing,a formal and feasible version was submitted. I wanted to launch a pull request.
> 
> The problem with your PR, assuming you're referring to #10924, was that it was _way_ to large and complicated for anyone to test and review. Not to mention that it would have made the code in question almost unmaintainable, and any bugs/regressions (of which the above suggests there were a few) would have been extremely difficult to deal with.
> 
> Honestly, given the specialized use-case here (with _huge_ files) it's really not at all clear that you want to add too much complication to the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) since it must be possible to maintain it. Also, please keep in mind that it's used as the PDF Viewer in Firefox, and we don't want to risk unnecessary regressions there.

Modified

**Comment by Snuffleupagus** [comment]
> Effect before modification: https://tanglinhai.github.io/repo/oldPDF.html
> Modified effect: https://tanglinhai.github.io/repo/newPDF.html

I'm not really seeing/feeling a large difference in performance between the two, after the initial loading has completed.
What I do notice though, is that something as simple as scrolling pages into view isn't working correctly with the modified code which ties directly into the points made in https://github.com/mozilla/pdf.js/issues/10942#issuecomment-507997864 about testing and maintainability.

You're obviously free to modify the code for your use-case, but I'm not convinced that this belongs in the main repository for the reasons outlined above.

**Comment by tanglinhai** [comment]
@ @Snuffleupagus I've optimized the code and commented it. As for the problem you should be careful about, it's like this. The part I changed is just the code of the page loading strategy section under the web directory. I have tested all the functions in this section without any problems.

**Comment by tanglinhai** [comment]
@Snuffleupagus This may be your local machine performance is better. If the effect is more obvious on the IE browser, the scroll will be much smoother after my local modification.

**Comment by tanglinhai** [comment]
@Snuffleupagus This example PDF is empty page, if it has content, the effect is more obvious.

**Comment by tanglinhai** [comment]
@Snuffleupagus  #10942的所有问题已经改了。最新优化的和测试完整的代码已经提交了，不过还没有pull request

**Comment by tanglinhai** [comment]
@Snuffleupagus may i  apply for a pull request ?

**Comment by tanglinhai** [comment]
https://tanglinhai.github.io/repo/oldPDF.html：The code in this example, which I use as the official backbone, has never been modified.

**Comment by Snuffleupagus** [comment]
>  I have tested all the functions in this section without any problems.

As was clearly mentioned in https://github.com/mozilla/pdf.js/issues/10942#issuecomment-508001556, even something as simple as scrolling the next/previous page into view isn't working correctly with https://tanglinhai.github.io/repo/newPDF.html (and there may be more things not working correctly), hence the statement above isn't accurate.

>  If the effect is more obvious on the IE browser,

As is clearly outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for IE11 is limited and PRs specific to improving performance in that browser won't be accepted.

**Comment by tanglinhai** [comment]
> > I have tested all the functions in this section without any problems.
> 
> As was clearly mentioned in [#10942 (comment)](https://github.com/mozilla/pdf.js/issues/10942#issuecomment-508001556), even something as simple as scrolling the next/previous page into view isn't working correctly with https://tanglinhai.github.io/repo/newPDF.html (and there may be more things wrong), hence the statement above isn't accurate.
> I just tried it. I didn't find any problems. Can you tell me what the problems are?

**Comment by tanglinhai** [comment]
> > > I have tested all the functions in this section without any problems.
> > 
> > 
> > As was clearly mentioned in [#10942 (comment)](https://github.com/mozilla/pdf.js/issues/10942#issuecomment-508001556), even something as simple as scrolling the next/previous page into view isn't working correctly with https://tanglinhai.github.io/repo/newPDF.html (and there may be more things wrong), hence the statement above isn't accurate.
> > After trying again, we found no problem, and from switching the rendering mode, the response speed of pulling the scrollbar was obviously higher than that of the trunk master version, and the whole component occupied less resources than the original. There were ten thousand div pages loaded under the pdfViewer, and the performance is imaginable. This is only one PDF plug-in loaded on the whole page. In practice, the page has to load a lot of other things.

**Comment by Snuffleupagus** [comment]
If you actually compare both your examples side-by-side, it's obvious that the modified one isn't scrolling pages into view correctly when you e.g. click on the Next/Previous buttons; this took less than 15 seconds to spot and thus ties in to the points above regarding testing/maintainability of the code.

Given that something this simple is broken, it's quite likely that there's other (more complex) issues as well, which is why I don't think that all of this added complexity belongs in the default viewer.

---

Finally, you may want to try using [`PDFSinglePageViewer`](https://github.com/mozilla/pdf.js/blob/master/web/pdf_single_page_viewer.js), rather than the standard `PDFViewer`, in your implementation of the viewer. Note that the former will, as its name suggests, only display *one* page at a time and may thus alleviate some of the issues you're facing with these very long PDF documents.

**Comment by tanglinhai** [comment]
> If you actually compare both your examples side-by-side, it's obvious that the modified one isn't scrolling pages into view correctly when you e.g. click on the Next/Previous buttons; this took less than 15 seconds to spot and thus ties in to the points above regarding testing/maintainability of the code.
> 
> Given that something this simple is broken, it's quite likely that there's other (more complex) issues as well, which is why I don't think that all of this added complexity belongs in the default viewer.
> After listening to your suggestion, I tried again and found no problem. I opened two windows. One was original, the other was modified, clicked separately and displayed the same.

Is it because your local browser cached the last problematic code? Are you looking at an example at https://tanglinhai.github.io/repo/oldPDF.html  Or use my last pull request code as an example?

**Comment by Snuffleupagus** [comment]
If you actually compare the following screen-shots, it's completely obvious that the pages offsets (both vertical *and* horizontal) are off in your modified viewer:
![1](https://user-images.githubusercontent.com/2692120/60593588-60c0f800-9da3-11e9-9caa-d54f2ecb8573.png)
![2](https://user-images.githubusercontent.com/2692120/60593591-61598e80-9da3-11e9-9954-abfd418787fe.png)

Again, as already mentioned above the changes you're proposing unfortunately aren't a good fit for the default viewer given that it only seems relevant for an edge-case, is very difficult to test/review (and there's existing bugs), would make the code *extremely* difficult to read and maintain.
(There's also a possible solution mentioned in https://github.com/mozilla/pdf.js/issues/10942#issuecomment-508053554, for custom implementations of the PDF default viewer.)

**Comment by tanglinhai** [comment]
@Snuffleupagus  Thank you for your explanation.  The horizontal position left differs by 9 pixels and the vertical position by 1 pixel. It has been repaired.

Finally, there are many performance problems, so it is impossible to improve performance by changing one or two lines of code like other bugs. This modification is not accepted. I think the main problem is that the modification is too big. That's all. I'll close the problem.
