### ISSUE TITLE
PDFViewer is used on the mobile side

### ISSUE THREAD

**Issue by cyfour** [mozilla/pdf.js#10941]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. PDFViewer is used on the mobile side, because it uses the server to paginate the PDF back, so we need to load every page with PDFViewer, but it will crash in the mobile browser. How can we improve the performance of reading PDF in the mobile browser?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDFViewer is used on the mobile side, because it uses the server to paginate the PDF back, so we need to load every page with PDFViewer, but it will crash in the mobile browser. How can we improve the performance of reading PDF in the mobile browser?

It's *very* difficult to understand *exactly* what you're trying to report here, but as explained in the FAQ you should never load an entire document at once; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages
Furthermore, the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) isn't generally suited for mobile usage and you really ought to look into using e.g. the `mobile-viewer` example instead; see https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer

Finally, there isn't really enough information provided to make this an actionable/valid issue.

**Comment by cyfour** [comment]
I have a look at mobile demo, the code is as follows 
const eventBus = new EventBus(false) || getGlobalEventBus(false)
    const linkService = new pViewer.PDFLinkService({
      eventBus: this.eventBus,
      externalLinkRel: 'noopener noreferrer nofollow',
      externalLinkTarget: 0
    })
    // console.log( document.getElementById('the-canvas' + this.index))
    const l10n = pViewer.NullL10n
    // const CSS_UNITS = 96.0 / 72.0
    let pdfView = new pViewer.PDFViewer({
      container: document.getElementById("the-canvas"+index),
      id: index,
      l10n: l10n,
      linkService: linkService,
      // useOnlyCssZoom:true,
      textLayerMode: 0,
      eventBus: eventBus

    })
    eventBus.on('pagesinit', () => {
   
      const w=parseInt(pdfView.container.getElementsByClassName("page")[0].style.width);
      const scale=window.innerWidth/w*2;
      pdfView.currentScaleValue = scale;
      _this.loadedpdfIndexArr.push(index);
      this.pageArr[index]=pdfView;
      pdfView.getUint8Array=getUint8Array;
      _this.emit('img-onload',index)
      resolve(index);

    })
    linkService.setViewer(pdfView)

    const pdf = pdfjsLib.getDocument({
      data: getUint8Array, cMapUrl: cMapUrl, cMapPacked: cMapPacked
    })
   
    pdf.promise.then((pdfDocument) => {
     
      pdfView.setDocument(pdfDocument)
      linkService.setDocument(pdfDocument)
    })





But my scenario is that PDF is a separate page number and each page number needs a PDF vieweer

**Comment by timvandermeij** [comment]
Without a running example this is simply not actionable for us. What does "PDF is a separate page number" mean? Why does each page need to be its own PDF viewer? The comment from @Snuffleupagus applies for me as well; it's simply not clear what you're trying to achieve.

**Comment by cyfour** [comment]
Sorry, it's not clear what I'm describing, "PDF is a separate page number," which means that the server staff will split the entire PDF into pages and return to the front end.
