### ISSUE TITLE
"def" operator in parentheses

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#10945]
I am sorry, this is not a bug in pdf.js . I am making my own PDF parser and I don't know who else could help me :(

In my PDF, there is text and the "ToUnicode" entry, which has the CMap table specified. The PostScript inside it looks like this:
```
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
 /CIDSystemInfo

<<  /Registry (\(Adobe\))
 /Ordering (\(UCS\))
 /Supplement 0

>> def
 /CMapName  /Adobe-Identity-UCS (def)
 /CMapType (2) def
1 begincodespacerange
<0000> <FFFF>  ....
```
As you see, there is a "def" in parentheses, which denotes a String in PostScript. But for the script to run correctly, the "def" should be an operator.

Is it an error in a PDF syntax, or there is a way to interpret such "def" as an operator according to the specification?

**Comment by Snuffleupagus** [comment]
> I am sorry, this is not a bug in pdf.js . I am making my own PDF parser and I don't know who else could help me :(

Please consider using sites like https://stackoverflow.com/ which are *specifically* designed for asking questions (on a variety of topics), rather than continuously use this *bug tracker* for off-topic discussions.

**Comment by photopea** [comment]
There is almost nobody on StackOverflow understanding PDF format. My questions were unanswered for weeks :(

**Comment by Snuffleupagus** [comment]
> There is almost nobody on StackOverflow understanding PDF format. My questions were unanswered for weeks :(

While that's very unfortunate, it still doesn't make it OK to treat this *bug tracker* and the people who frequent it as your (free) personal support forum as far as I'm concerned.

> Is it an error in a PDF syntax, or there is a way to interpret such "def" as an operator according to the specification?

You might be able to answer such questions for yourself, by actually reading the PDF specification and/or the relevant code; in this case https://github.com/mozilla/pdf.js/blob/master/src/core/cmap.js

**Comment by timvandermeij** [comment]
Closing since I also agree with the above. If there is a problem related to how PDF.js works, you can always open an issue, but this is a general PDF format question. I think you'll find most answers in both the PDF specification at https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf and the relevant PDF.js code in `src/core/cmap.js`.

**Comment by girng** [comment]
@Snuffleupagus  lol  @ recommending a developer who created one of the best online image editing services available, to use stackoverflow.

**Comment by photopea** [comment]
@timvandermeij  May I interrupt you with one more question?

In this PDF on a page 3, there are nine "Do" commands, which draw full-page raster images: /X0, /X1, /X2 ... (all are JPG). The first one: /X0  is colorful, others are mostly white.

PDF.js and Adobe Reader render only the first bitmap, while skipping others (or rendering them as transparent). What is the reason of such behaviour? I can not find any information in a PDF file, which would imply it.

[TEDx new brochure 6-feb.pdf](https://github.com/mozilla/pdf.js/files/3668201/TEDx.new.brochure.6-feb.pdf)

**Comment by photopea** [comment]
@timvandermeij  I see, that drawing a white bitmap follows drawing a black text. So the bitmap should probably make the text white. 

And I see, that there is "7 Tr", which sets the text-rendering mode to "add to path for clipping". So I understand it now, sorry for disturbing :)
