### ISSUE TITLE
Error: Cannot find module 'worker-loader!./build/pdf.worker.js'

### ISSUE THREAD

**Issue by grantham500** [mozilla/pdf.js#10952]
```javascript
import pdfjs from "pdfjs-dist/webpack.js";
```
results in:

> Error: Cannot find module 'worker-loader!./build/pdf.worker.js'

```bash
npm list webpack worker-loader pdfjs-dist

+-- pdfjs-dist@2.0.943 
| `-- worker-loader@2.0.0  deduped
+-- webpack@4.35.0 
`-- worker-loader@2.0.0 
```

What could be a reason for that? The suggestion was: 
> You can use the pdfjs-dist/webpack module for PDF.js autoconfiguration.
:D

**Comment by shellliii** [comment]
Same problem here
Is there anything I can do about in order to use pdf.js?

**Comment by pengliheng** [comment]
some problem with me.
`parcel` + `vue` + `vue-pdf`
```bash
❯ yarn list vue vue-pdf parcel-bounld
yarn list v1.17.3
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ vue-pdf@4.0.7
└─ vue@2.6.10
✨  Done in 0.13s.
```

**Comment by timvandermeij** [comment]
Closing since we've changed the way we're working with Webpack to remove those dependencies from `pdfjs-dist`.

**Comment by zdm** [comment]
@timvandermeij  
so, how we can use it now?
`import pdfjs from "pdfjs-dist/webpack.js";` not works already.

**Comment by jsamayoap** [comment]
> @timvandermeij
> so, how we can use it now?
> `import pdfjs from "pdfjs-dist/webpack.js";` not works already.

+1, having the same error here as I used to import pdfjs-dist/webpack, how this should be coded now?

**Comment by tgbv** [comment]
Install `worker-loader` and try again:
```
npm install worker-loader --save-dev
```

**Comment by jsamayoap** [comment]
Thanks, @tgbv I did, after that my build complained that I need module, installed that and then worked out for me, I'm still intrigued if that would be the best way to deal with this in the long run, since now my dependencies grew in more than a hundred packages more, and now my build produces the next warnings

 warning  in ./node_modules/lazy-debug-legacy/src/functions.js
Critical dependency: the request of a dependency is an expression
 warning  in ./node_modules/lazy-debug-legacy/src/functions.js
Critical dependency: the request of a dependency is an expression

that came after adding module to my package.json

**Comment by jameseggers** [comment]
@jsamayoap I am having the same issue, not sure what is causing it yet.

**Comment by yotavm** [comment]
do we have a solution for this

**Comment by tgbv** [comment]
I'm sorry I lost the track of this @jsamayoap please attempt the following solution to avoid the warnings: https://stackoverflow.com/questions/42908116/webpack-critical-dependency-the-request-of-a-dependency-is-an-expression

**Comment by rameezcubet** [comment]
I had the same issue. I think problem is where the bundler converts the string-based import to an ugly string.

my solution was to use  like follows 

issue code 
--------
`import('pdfjs-dist/webpack') `


solution
```
-------------
import(pdfjs-dist/webpack) 
```

**Comment by rameezrami** [comment]
I had the same issue. I think problem is where the bundler converts the string-based import to an ugly string.

my solution was to use  like follows 

issue code 
--------
`import('pdfjs-dist/webpack') `


solution
```
-------------
import(pdfjs-dist/webpack) 
```

**Comment by jsamayoap** [comment]
Thanks @tgbv I've checked what you proposed on the SO link to no avail, in that case, they argue about a library called "request", but my issue is with another library, called "module", I've tried their solution, installing a fixed version of "request" and latest version of that same library, in both cases the compile produce the same reported warnings.

@rameezrami tried what you proposed but I import the library as: 
`import { getDocument, PDFLoadingTask, PDFDocumentProxy, PDFRenderParams } from 'pdfjs-dist/webpack';` 

Tried to replace that with this:
`import { getDocument, PDFLoadingTask, PDFDocumentProxy, PDFRenderParams } from pdfjs-dist/webpack;` 

Then it simply didn't compile

**Comment by GloSen** [comment]
After installing worker-loader as suggested by @tgbv I encounter an error:
_Invalid handler for event "error": got undefined
found in
---> at node_modules/vue-pdf/src/vuePdfNoSss.vue_

did anyone encounter an error like this?

**Comment by dearvn** [comment]
Pls insert code into html page:
`<base href="/">`

**Comment by dearvn** [comment]
> After installing worker-loader as suggested by @tgbv I encounter an error:
> _Invalid handler for event "error": got undefined found in ---> at node_modules/vue-pdf/src/vuePdfNoSss.vue_
> 
> did anyone encounter an error like this?
pls insert code below into html page:
`<base href="/">`
