### ISSUE TITLE
Digital sign with certificates

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#10975]
Hi,

Does pdf.js support visibility of digital signature with certificates?

**Comment by timvandermeij** [comment]
No, it doesn't. This feature is tracked in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature.

**Comment by SwatiMaheshwari** [comment]
If i comment out below lines...the digital signatures are visible
```
if (this.data.fieldType === 'Sig') {
        warn('unimplemented annotation type: Widget signature');
        return false;
      }
```

Will it breaks other things while opening pdf?

**Comment by SwatiMaheshwari** [comment]
@timvandermeij Please check above comment

**Comment by timvandermeij** [comment]
Not as far as we know, but we disabled it for a reason: the signature verification is not implemented, so without that the signatures don't have much meaning.
