### ISSUE TITLE
When I load a PDF file of more than 160 M in size, an error is reported:'Unexpected server response (500) while retrieving PDF'. But it's okay to load smaller files, and that's why.

### ISSUE THREAD

**Issue by jiao1187875445** [mozilla/pdf.js#10973]
When I load a PDF file of more than 160 M in size, an error is reported:'Unexpected server response (500) while retrieving PDF'. But it's okay to load smaller files, and that's why.

**Comment by Snuffleupagus** [comment]
Without *all* of the requested information from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this will be closed as invalid.
