### ISSUE TITLE
Single page large format displays as a blank page or incorrectly

### ISSUE THREAD

**Issue by menver** [mozilla/pdf.js#10989]
This looks to be a CAD type drawing displays as a blank page in FF, Image compressed into top inch of the page in Chrome, and fails in IE 11
Tested in PDF.js Libraries (v2.0.943).

Document to be uploaded to the ticket by customer shortly.

**Comment by erasmus76** [comment]
[ArchitecturalPlanProblemPDF_2.pdf](https://github.com/mozilla/pdf.js/files/3410726/ArchitecturalPlanProblemPDF_2.pdf)
