### ISSUE TITLE
Permission denied in page.render method

### ISSUE THREAD

**Issue by imranknp** [mozilla/pdf.js#10983]
The pdf document is not rendering in IE and Edge browsers. Its working fine in other browsers.

Code sample:

```
PDFJS.getDocument(uInt8ArrayString(base64String)).then(function (document) {
    _document.getPage(1).then(function (page) {

        var viewport = page.getViewport(scale, rotate);

        canvas.height = settings.canvasHeight = viewport.height;
        canvas.width = viewport.width;
        var context = canvas.getContext('2d');

        var renderContext = {
            canvasContext: context,
            viewport: viewport
        };

        var renderComplete = page.render(renderContext);

        console.log(renderComplete);
    });
});
```

The console result says Permission Denied in data.
![image](https://user-images.githubusercontent.com/51901937/61437175-12425a80-a95a-11e9-9e8d-1bc98a01d4d8.png)

**Comment by Snuffleupagus** [comment]
Without *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md this issue will be closed as INVALID.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> The pdf document is not rendering in IE and Edge browsers.

Finally, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support support for those browsers is *very* limited.
