### ISSUE TITLE
X-Content-Type-Options:nosniff cause error in console

### ISSUE THREAD

**Issue by derakhshanfar** [mozilla/pdf.js#10981]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- Operating system and its version:
Ubuntu 18.04
- PDF.js version:
2.1.266
- Is a browser extension:
no

Steps to reproduce the problem:
1. enable X-Content-Type-Options: nosniff in nginx
2. get this error in console
`Refused to execute script from 'http://localhost/app.worker.js?v=1.0.15' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/18225394/61409696-08880b00-a8f8-11e9-8f51-2f40812bfd80.png)
![image](https://user-images.githubusercontent.com/18225394/61410133-f6f33300-a8f8-11e9-855b-d312be2b0b44.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by derakhshanfar** [comment]
It fixed, The problem was I didn't set this:
```
pdfjsLib.GlobalWorkerOptions.workerSrc =
  '../../build/webpack/pdf.worker.bundle.js';
```

**Comment by jamminjames** [comment]
Where do you set that exactly? My error is a little different, it's for "MIME type ('application/octet-stream') is not executable".

**Comment by pf-tech** [comment]
> Where do you set that exactly? My error is a little different, it's for "MIME type ('application/octet-stream') is not executable".

I don't know if it will help you, but I had to add
AddType application/javascript .mjs

to my .htaccess file in the <IfModule mod_headers.c> section
