### ISSUE TITLE
 render PDF based on URL of PDF

### ISSUE THREAD

**Issue by amitK007** [mozilla/pdf.js#10985]
Attach (recommended) or Link to PDF file here:
How to render pdf based on URL of PDF
http://www.africau.edu/images/default/sample.pdf

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

**Comment by timvandermeij** [comment]
It's not clear what the question is, but based on the title I'm assuming you want to load a PDF file from a given URL. You can pass the URL to the `getDocument` API call, see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L128, but note that you may run into cross-domain request issues. For that, refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr.
