### ISSUE TITLE
Hiding sidebar using pagemode=none mostly non-functional

### ISSUE THREAD

**Issue by Photon89** [mozilla/pdf.js#10980]
Attach (recommended) or Link to PDF file here: See link to viewer below.

Configuration:
- Web browser and its version: Firefox 68, Chromium 75
- Operating system and its version: Manjaro Linux (stable)
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. Klick the two links provided below.
2. Observe that while the first link opens with hidden sidebar the second one shows the sidebar, though in both cases the option pagemode=none has been passed to the viewer (HTML div structure: body > outerContainer > centerContainer > iframe; src is set dynamically in https://photon89.gitlab.io/tpiq-experimental/web/script.js by the function loadPDF). 

What is the expected behavior? (add screenshot)
Sidebar should be always hidden.

What went wrong? (add screenshot)
Sidebar not always hidden.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Mostly working: https://photon89.gitlab.io/tpiq-experimental/web/new_design_index.html#test.pdf
Mostly broken: https://photon89.gitlab.io/tpiq-experimental/web/new_design_index.html#test.pdf&AM1&treeView

Thanks for any input and sorry if my JS code is ugly! :)

**Comment by Photon89** [comment]
I found a workaround and set 

`"disablePageMode": true`

in viewer.js, `getDefaultPreferences()`.

**Comment by Photon89** [comment]
Well, as I stated in my comment, I found a workaround for the issue. In the mean time the project's code has changed a lot, so the file I linked to is no longer demonstrating the issue. If anybody is interested in following up this issue, I could set up an example where it appears, otherwise I guess it can be closed.

**Comment by timvandermeij** [comment]
I also don't see anything we can do here at this point in time. If you can reproduce this with an unmodified PDF.js viewer, then please open a new issue because then we're sure that it's not any of the modifications that cause it.
