### ISSUE TITLE
"Whole word" search broken at line break

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#10994]
Attach (recommended) or Link to PDF file here:
Just use your standard tracemonkey demo.

Configuration:
- pdf.js 2.2.228 (or the latest pdf.js 2.3.x snapshot).
- Browser etc. shouldn't make a difference.

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. Type "CTRL+F" to open the find dialog
3. Type "languages". The first search result is the last word of the title.
4. Click "whole word". Now the first search result is somewhere in the first paragraph. The word "languages" of the title is no longer detected.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/3045767/61583042-e4643e00-ab32-11e9-9a8d-47a19406747f.png)

**Comment by stephanrauh** [comment]
When I copy the title to a simple text editor, there's a missing space, indeed. Maybe you're right. If so, it's still a bug, but IMHO a really hard one.

**Comment by stephanrauh** [comment]
The issue I've just linked to this topic may or may not be related to this bug. The original author claims that spaces don't make it do the clipboard after selecting and copying text from the PDF viewer.

**Comment by tavito** [comment]
I think the problem is not in selecting and copying the PDF viewer, but in rendering the text...
