### ISSUE TITLE
PDF with embedded JPEG2000 displays blank with Warning: Unable to decode image: JpxError: JPX error: Unsupported COD options (predictableTermination

### ISSUE THREAD

**Issue by ReubenChapman** [mozilla/pdf.js#11004]
Attach (recommended) or Link to PDF file here:

Configuration:
- Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- Windows10
- 2.0.943
- Is a browser extension: n/a

Steps to reproduce the problem:
1. Load sample file in any PDF.js viewer (FireFox)
2.

What is the expected behavior? (add screenshot)
PDF should be viewable as per Adobe
![acrobat](https://user-images.githubusercontent.com/49719956/61726774-20351880-ad6a-11e9-8eec-b58358ce2910.PNG)

What went wrong? (add screenshot)
Displays blank
![blank_in_firefox](https://user-images.githubusercontent.com/49719956/61726794-2925ea00-ad6a-11e9-9fba-bd94c12d3547.PNG)

Seems there are JPEG2000 images in here which are not supported because we see this error in the logs:
Warning: Unable to decode image: JpxError: JPX error: Unsupported COD options (predictableTermination)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by erasmus76** [comment]
Sample doc:
[problem.pdf](https://github.com/mozilla/pdf.js/files/3422968/problem.pdf)
