### ISSUE TITLE
Missing content #2, now with samplecode

### ISSUE THREAD

**Issue by bitsflew** [mozilla/pdf.js#11000]
Attach (recommended) or Link to PDF file here:
[https://www.dropbox.com/s/6pjiuhygnmum4s1/document.pdf?dl=1](url)

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Debian9
- PDF.js version:  pdfjs-dist 2.1.266
- Is a browser extension: NO

Steps to reproduce the problem:

Here is a small node.js sample project illustrating the issue.
[https://www.dropbox.com/s/595dza21xyl2fpw/pdf2jpg.zip?dl=1
](url)

It will render every page from the embedded pdf document to a jpeg file
NOTE: I can pnly reproduce the issue on Denian9, the code produces the correct output on macOS..

Preseequites:
Debian9,
Node v10.16.0 or v8.16.0

Installation:
cd [project-dir]
npm install
npm start

The generated jpeg files are written to [project-dir]/test/output

What is the expected behavior?

![macos-mojave-page-1](https://user-images.githubusercontent.com/488260/61622900-fd293c80-ac75-11e9-9126-68781e31bb88.jpg)

What went wrong?

![debian9-page-1](https://user-images.githubusercontent.com/488260/61622914-031f1d80-ac76-11e9-811c-78f4ac5e6d3f.jpg)

**Comment by timvandermeij** [comment]
Closing since I reopened #10992 for this instead.
