### ISSUE TITLE
Gradients do not render properly sometimes

### ISSUE THREAD

**Issue by izolenta** [mozilla/pdf.js#11018]
[lines_issue.pdf](https://github.com/mozilla/pdf.js/files/3441553/lines_issue.pdf)

Configuration:
- Chrome (latest)
- Mac Os X Mojac
- PDF.js version: latest (reproduced on pdf.js demo page)

Steps to reproduce the problem:
1. Open attached pdf in pdf.js demo viewer
2. Please note that thin line in the middle is not affected by gradient, but it should be (see screenshot below taken from Mac Os X Preview)

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/430887/62041871-5d375a00-b205-11e9-9811-97c1643ae5b9.png)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/430887/62041851-51e42e80-b205-11e9-97a3-5a1ef1b20245.png)

**Comment by MitchDizzle** [comment]
I believe I'm seeing this issue also in Firefox. Tried to look through the code and didn't find anything regarding to gradients/shading/stroke. The lines in my document are using gradients on the stroke, and fill is set to none. 
Renders properly in Microsoft Edge also.
