### ISSUE TITLE
how to render renderTextLayer in nodejs environment

### ISSUE THREAD

**Issue by sheikalthaf** [mozilla/pdf.js#11011]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: - nodjs 10.16
- Operating system and its version: - linux
- PDF.js version: - 2.2.228
- Is a browser extension: no

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
how to render RenderTextLayer in nodejs in server side?. There is two blocking things in rendering.

creating DOM element
https://github.com/mozilla/pdf.js/blob/9b7208988639c4f1841e1b8abeaf6072b17f2f43/src/display/text_layer.js#L58

creating canvas element
https://github.com/mozilla/pdf.js/blob/9b7208988639c4f1841e1b8abeaf6072b17f2f43/src/display/text_layer.js#L572

i followed the node example in this repo and it is working fine for converting the pdf2Png but can't render text layer and get the dom elements.

`any hack to make those api to be fake with dom stub or canvasFactory`

What went wrong? (add screenshot)

   getting error with dom apis

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Node.js doesn't have a DOM. Instead, you need to use something like https://github.com/jsdom/jsdom to simulate it.

**Comment by sheikalthaf** [comment]
@timvandermeij Thanks for the suggestion, but sorry for the late response.

don't know how to do that. Please help me to solve this problem. 
Any guidance will be helpfull
