### ISSUE TITLE
PDFJS.getDocument() not working

### ISSUE THREAD

**Issue by jingshenchen** [mozilla/pdf.js#11010]
![QQ图片20190726160001](https://user-images.githubusercontent.com/38178200/61935962-3cc98e80-afbe-11e9-90b7-ca65072347a5.png)
use in Mini Program，but it is some problem

**Comment by timvandermeij** [comment]
Closing since almost none of the information from the issue template is provided. This is important, because without we cannot help, especially without a runnable version. Moreover, it looks like a custom build because `previewFileCom.js` is not something from PDF.js.
