### ISSUE TITLE
Trigger printing in pdf_viewer

### ISSUE THREAD

**Issue by zagoa** [mozilla/pdf.js#11022]
Configuration:
- Web browser and its version: Brave Version 0.66.101 Chromium: 75.0.3770.142
- Operating system and its version: Ubuntu 18
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
I integrate pdfJs in my Angular project, and I wanted to custom it. It's very awesome library, my only problem is how can I trigger printing ? I integrate the pdf inside a page and window.print() trigger a print of the all page and not of the specific document, and without all the page of the pdf. 

here my (simplify) code to initialize my pdf : 
```
import * as pdfjsViewer from 'pdfjs-dist/web/pdf_viewer';

 private async pdfViewer(): Promise<void> {
    const container = document.getElementById('viewerContainer');

    // (Optionally) enable hyperlinks within PDF files.
    const pdfLinkService = new pdfjsViewer.PDFLinkService();

    // (Optionally) enable find controller.
    const pdfFindController = new pdfjsViewer.PDFFindController({
      linkService: pdfLinkService,
    });

    this.pdfElement = new pdfjsViewer.PDFViewer({
      container: container,
      linkService: pdfLinkService,
      findController: pdfFindController,
    });

    pdfLinkService.setViewer(this.pdfElement);

    // Loading document.
    const loadingTask = pdfjsLib.getDocument({
      url: this.pdfService.getPdfDocUrl(this.docId),
      httpHeaders: {
        Authorization: `Bearer ${this.authService.getAccessToken()}`
      },
      withCredentials: true,
      cMapUrl: '../../node_modules/pdfjs-dist/cmaps/',
      cMapPacked: true,
      eventBusDispatchToDOM: true
    });

    const pdfDocument = await loadingTask.promise;
    this.pdfElement.setDocument(pdfDocument);
    pdfLinkService.setDocument(pdfDocument, null);

    this.listenToEvents();
  }
```
I tried different things to print it like trigger an event in the eventBus, but when I looked into the code of `pdf_viewer` I didn't find any listener to print. I saw `pdf_print_service` but I don't understand how to pass it to my `pdf_viewer`.
 
Do you have any advise to achieve what I want (opening the printing window with only the pdf document fully loaded) ?

**Comment by timvandermeij** [comment]
Printing requires more logic than simply calling `window.print()`, unfortunately. By default the entire page will be printed, so extra logic is needed to only print the canvases. In the default viewer, this is implemented in the `beforePrint`/`afterPrint` handlers (see https://github.com/mozilla/pdf.js/blob/9b7208988639c4f1841e1b8abeaf6072b17f2f43/web/app.js#L1270). In the end, the print service (https://github.com/mozilla/pdf.js/blob/b01cc55cfd1f3947cdbc9fcf5ffc89a856052904/web/pdf_print_service.js) takes care of the required steps for printing, so you'll have to find a way to integrate that in your project. I think it's best to carefully check how the default viewer does that and implement it in your project in a similar way.

**Comment by VicJerUk** [comment]
@zagoa Mate there is an easy option to print your content  - Pdf viewer renders pages in canvas - you can convert the output from your canvas toDataUrl and append output images to an iframe then run iframe.contentWindow.print()
