### ISSUE TITLE
Project with components for use pdfjs in angular

### ISSUE THREAD

**Issue by hhfrancois** [mozilla/pdf.js#11023]
Hi, I create a library based on yours for use it easily in angular application. Would you like to add it to your wiki [here](https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications) ?
My project is here :
[github](https://github.com/hhangular/hhangular)
[website](hhangular.hhdev.fr)

Of course it's MIT licensed

Thx by advance

hhfrancois

**Comment by timvandermeij** [comment]
Done, thanks!
