### ISSUE TITLE
view pdf with hight quality

### ISSUE THREAD

**Issue by dungvvfabbi** [mozilla/pdf.js#11024]
Attach (recommended) or Link to PDF file here:
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/3451152/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Chrome, firefox, ...
- Operating system and its version: Ubuntu 18.04
- PDF.js version: 2.2.117
- Is a browser extension:

Steps to reproduce the problem:
1. How I can render pdf file with high quality like 
![Screenshot from 2019-07-31 17-15-53](https://user-images.githubusercontent.com/50563692/62204204-f194ee80-b3b6-11e9-877d-9b21c3a8e4fe.png)
 not like 
![Screenshot from 2019-07-31 17-15-06](https://user-images.githubusercontent.com/50563692/62204220-f8236600-b3b6-11e9-826a-310452013dfd.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html
How I can do that?
Thankiu so much !

**Comment by timvandermeij** [comment]
Zooming above 400% triggers canvas scaling, which makes it blurry because rendering canvasas this large causes memory issues. One of the ways to solve this is to use the SVG back-end which can zoom practically infinitely just like Adobe Reader, but that is experimental at this point in time.
