### ISSUE TITLE
White grid lines showing up in rendered & printed PDF

### ISSUE THREAD

**Issue by FFNight** [mozilla/pdf.js#11032]
Source: N/A

Configuration:
- Web browser and its version: Firefox 68.0.1 (happens on both 32-bit and 64-bit)
- Operating system and its version: Windows 7
- PDF.js version: ???
- Is a browser extension: No

Steps to reproduce the problem:
1. The source PDF file is created from Adobe Illustrator CC 2014 (Mac), when opened with Firefox, white lines will appear in the rendered image.
2. The white line does not go away when zoomed in/out.
3. When printed using the built-in print button in the pdf.js viewer in Firefox, the white lines will show up as well.
4. The current workaround for me is to download the PDF, then open it with Adobe Acrobat Reader DC before printing it out.

This is how the PDF looks when opened with Adobe Acrobat Reader DC (What I want):
![pdfjs2](https://user-images.githubusercontent.com/11225214/62259353-9ad3f700-b440-11e9-8ec6-12d6c9c105ff.png)

This is how the image shows up in Firefox and when printed out using Firefox:
![pdfjs1](https://user-images.githubusercontent.com/11225214/62259292-6829fe80-b440-11e9-92bb-22fd271c7ea5.png)
* Red arrows added manually.

**Comment by Snuffleupagus** [comment]
Probably a duplicate of #3351 (or similar).

*For future reference:* You always need to attach the PDF file in question in order for issues to be valid.

**Comment by FFNight** [comment]
Thanks for the heads up. Unfortunately I cannot share the PDF file in question as it is an organization document, but the issue is very similar to #3351 and the associated #9829.

Too bad that this issue has been persisting for so many years but there is still no resolution in sight. 

Closing this issue.
