### ISSUE TITLE
Hindi/Devnagri font display problem

### ISSUE THREAD

**Issue by prashant-saxena** [mozilla/pdf.js#11037]
[mahageeta1.pdf](https://github.com/mozilla/pdf.js/files/3460804/mahageeta1.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Firefox 68.0.1 (64-bit), Chrome 76.0.3809.87 (Official Build) (64-bit)
- Windows 10
- PDF.js 2.2.228
- No

Steps to reproduce the problem:
1.  I did some changes in the default examples/text-only/index.html.
Change
`<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.2.228/pdf.js"></script>`
2. In pdf2svg.js
```
var CMAP_URL = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.2.288/cmaps/';
var CMAP_PACKED = true;
pdfjsLib.GlobalWorkerOptions.workerSrc =
  'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.2.228/pdf.worker.js';
```
and calling
```
var loadingTask = pdfjsLib.getDocument({ url: PDF_PATH, cMapUrl: CMAP_URL,
  cMapPacked: CMAP_PACKED,});
```

What is the expected behavior? (add screenshot)
![Screenshot_2019-08-02 mahageeta1 pdf](https://user-images.githubusercontent.com/1583316/62364487-38adeb80-b53f-11e9-8bc2-6ceb05b2500e.png)

What went wrong? (add screenshot)
![Screenshot_2019-08-02 Text-only PDF js example](https://user-images.githubusercontent.com/1583316/62364507-46637100-b53f-11e9-9d8a-b82fd548ddd0.png)

As you can see that text is not getting rendered correctly. I'm trying to build a mobile pdf viewer similar to kindle app, where you can read the pdf without zooming or panning page wise. Here is the screenshot:
![Screenshot_2019-08-02 PDF JS Mobile](https://user-images.githubusercontent.com/1583316/62364858-3f892e00-b540-11e9-9296-d3c8849ee9e5.png)

What changes are required in examples/text-only to render the pdf correctly?

Regards

Prashant

**Comment by Snuffleupagus** [comment]
> What changes are required in examples/text-only to render the pdf correctly?

That example is *not* intended for actually rendering a PDF file, since the `textLayer` is used to enable text-selection/copying in the default viewer. As such there's simply no way to modify it such that it will ever work.

The correct solution would be to base your custom viewer on one of the [components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components) instead.
