### ISSUE TITLE
Cannot display figure in a pdf file generated with pdflatex 

### ISSUE THREAD

**Issue by tamuratak** [mozilla/pdf.js#11045]
Attach (recommended) or Link to PDF file here:

[from_pdftex.pdf](https://github.com/mozilla/pdf.js/files/3467425/from_pdftex.pdf)

[slice2.pdf](https://github.com/mozilla/pdf.js/files/3467447/slice2.pdf)

Configuration:
- Web browser and its version: Firefox 68.0.1 and Google Chrome 76.0.3809.87
- Operating system and its version: macOS High Sierra 10.13.6（17G8030）
- PDF.js version: 2.2.228 beta
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the attached pdf file, [from_pdftex.pdf](https://github.com/mozilla/pdf.js/files/3467425/from_pdftex.pdf), with PDF.js.
2. Figure 1 is blank.

![figure 1 blank](https://user-images.githubusercontent.com/10665499/62462347-27c0dc80-b7c2-11e9-8ab6-e86a2dc72096.png)

What is the expected behavior? (add screenshot)

Figure 1 should be displayed as Adobe Reader displays.

![2019-08-05 20 47 53](https://user-images.githubusercontent.com/10665499/62462423-59d23e80-b7c2-11e9-8c5d-2945651bd5af.png)

- The pdf file, from_pdftex.pdf, is generated with pdflatex.
- The figure, [slice2.pdf](https://github.com/mozilla/pdf.js/files/3467447/slice2.pdf),  included in the pdf file is a pdf file created with Affinity Designer.
- First reported by @rubendsa  at James-Yu/LaTeX-Workshop/issues/1577. 
- Notice that PDF.js can display slice2.pdf itself.

A source TeX file:
```tex
\documentclass[12pt]{article}
\usepackage{graphicx}

\begin{document}

\begin{figure}[h]
\begin{center}
\includegraphics[height=1in]{slice2.pdf}
\caption{\textit{Locations of the neutral point ($X_{NP}$) and center of gravity ($X_{CG})$ of an individual wing segment. }}
\label{fig:test2}
\end{center}
\end{figure}

\end{document}
```

**Comment by timvandermeij** [comment]
@tamuratak @rubendsa Is it OK with you if we add the provided `from_pdftex.pdf` file as a regression test to our test suite?

**Comment by tamuratak** [comment]
It is OK. @rubendsa How about you?

**Comment by rubendsa** [comment]
Yup, that’s okay

**Comment by timvandermeij** [comment]
Thank you both, also for reporting this. This is fixed by the pull request above.

**Comment by Snuffleupagus** [comment]
> This is fixed by the pull request above.

Please also report it to the maintainer of the PDF generator as well, so that this is fixed properly, since the PDF file is actually corrupt (the `/CS` entry in the Group dictionary points to a non-existent object).
