### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'PDFJS' of undefined", source: file:///android_asset/pdfjs/web/viewer.js (699)

### ISSUE THREAD

**Issue by swapnil591** [mozilla/pdf.js#11046]
"Uncaught TypeError: Cannot read property 'PDFJS' of undefined", source: file:///android_asset/pdfjs/web/viewer.js (699)

**Comment by timvandermeij** [comment]
It's impossible for us to help out if you don't provide the information from the issue template. I can only guess that you're using PDF.js 2.0 where the global `PDFJS` object doesn't exist anymore, so you need to change the code to not use that. Refer to the examples directory for that.
