### ISSUE TITLE
canvas 预览 PDF , canvas 会保留历史渲染文件

### ISSUE THREAD

**Issue by wsyxzxs** [mozilla/pdf.js#11044]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 我从父组件中获取到文件流，转化为blob 连接后，传入子组件，通过canvas 绘制出 PDF 的内容
2.我重新点击其他文件进行预览时，canvas 渲染的内容在第一次的基础后面，接着绘制第二次的页面。。。

What is the expected behavior? (add screenshot)
点击不同的PDF，绘制出新的 canvas，不应保留之前的数据。

What went wrong? (add screenshot)
点击不同的PDF, canvas在原有的基础上渲染出新的页面，之前的数据没有清空.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Only issues written in English will be considered, and furthermore you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue; as-is this issue will be closed as INVALID.
