### ISSUE TITLE
run webpack demo, not any buttons render in canvas 

### ISSUE THREAD

**Issue by wufeng87** [mozilla/pdf.js#11061]
I ran the webpack demo locally, the result is that it only render the first page of the pdf.
I could not interact with this pdf, like changing the page of the pdf.
Did I miss something? Thanks!

![image](https://user-images.githubusercontent.com/1686808/62771698-69a69700-bad0-11e9-8fa8-8de1b80b367b.png)

**Comment by wufeng87** [comment]
How could I render pdf like this?
![image](https://user-images.githubusercontent.com/1686808/62772422-17ff0c00-bad2-11e9-8844-aa161f0d1006.png)

**Comment by timvandermeij** [comment]
The Webpack demo is not a full viewer, but only renders the canvases. This is done to make the example minimal and easy to understand because a full viewer requires a lot of code. You'll need to use the default viewer, in the `web` folder, if you want a complete viewer.
