### ISSUE TITLE
Scanned PDF with transparent text renders slow with Safari

### ISSUE THREAD

**Issue by KeiBontakun** [mozilla/pdf.js#11060]
I found that pdf.js with Safari (both Mac and iOS devices) renders a scanned pdf very slow, 
Some bug report says it is due to large image however I found small image pdf can cause it and it is triggered by hidden text object.

I want to report Safari development team with this incompatibility but I can't see what function or API behaves different from other browsers.
Any hints?

Attach (recommended) or Link to PDF file here:
[scanned96dpi_Text.pdf](https://github.com/mozilla/pdf.js/files/3484941/scanned96dpi_Text.pdf)
[scanned96dpi_NoText.pdf](https://github.com/mozilla/pdf.js/files/3484942/scanned96dpi_NoText.pdf)

Configuration:
- Web browser and its version:
Safari 11.1.2

- Operating system and its version:
MacOS 10.11
iPod Touch 5gen

- PDF.js version:
latest
- Is a browser extension:
no

Steps to reproduce the problem:
1. Create a Image PDF without transparent text (scanned96dpi_NoText.pdf): renders fast on pdfjs
2. Create a Image PDF with transparent text (scanned96dpi_Text.pdf): renders very slow on pdfjs

What is the expected behavior? (add screenshot)
Both pdf renders in same duration.

What went wrong? (add screenshot)
PDF with transparent text renders very slow (5~10min per page)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by KeiBontakun** [comment]
Our engineer found the problem is caused by used fonts.
When the font is encoded with Surrogate Pair (ex: UniJIS-UTF16-H of V) the CMAP array gets large. And Safari takes very very long time when "window.postMessage" method passes the large array.
We created a test page and gave a feedback to Apple with no reply.

**Comment by timvandermeij** [comment]
Closing since this looks like an upstream bug that should be fixed on Apple's side.
