### ISSUE TITLE
Radio button not displayed as circles

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#11078]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- Operating system and its version: windows
- PDF.js version: 1.0.907
- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdf with pdf js version 1.0.907
2. radio button displayed as square instead of circles

What is the expected behavior? (add screenshot) 
radio button should display as circles instead of squares

What went wrong? (add screenshot)
radio button should display as circles instead of squares

Also 
Does pdf.js support editing pdfs?

**Comment by Snuffleupagus** [comment]
*Again, please provide *all* of the requested information when opening an issue.*

> Attach (recommended) or Link to PDF file here:

Without this information, the issue is INVALID.

> PDF.js version: 1.0.907

No longer supported version; see https://github.com/mozilla/pdf.js/releases

> Does pdf.js support editing pdfs?

No, as mentioned in https://github.com/mozilla/pdf.js/issues/10913#issuecomment-503181252.

**Comment by SwatiMaheshwari** [comment]
Okay can you tell me what are valid values for radio button. Can we give values other than on/off or yes/no?

**Comment by timvandermeij** [comment]
The PDF specification states that only on/off are valid values, which also makes sense for a radio button that only has two states. It sounds like you're maybe asking for #9146 which is still open, but I can't find this behavior in the specification so I'm not sure if it's even valid.
