### ISSUE TITLE
How we set data to fillable Pdf using .pdf.js

### ISSUE THREAD

**Issue by sajidsrq** [mozilla/pdf.js#11072]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You can enable AcroForms with the experimental `renderInteractiveForms` preference, but it's not feature-complete yet.

**Comment by sajidsrq** [comment]
is it possible to set or not

**Comment by sajidsrq** [comment]
What to set the  data into fillable pdf from database . is it possible
