### ISSUE TITLE
How to display toolbar in singlepage viewer

### ISSUE THREAD

**Issue by tym3515** [mozilla/pdf.js#11084]
singlepageviewer.html
how to adapt  window size without scrolling?
display toolbar in singlepage viewer?

**Comment by timvandermeij** [comment]
The single page viewer is not a complete viewer in the sense that it has a toolbar and the other default viewer features. It's just an example that shows how to make a minimal viewer yourself. If you want more advanced features like the toolbar, you'll have to make a variation of the viewer in the `web` folder.
