### ISSUE TITLE
text selection not working

### ISSUE THREAD

**Issue by roshinirose** [mozilla/pdf.js#11080]
Although I included the below mentioned files I was not unable to do the text selection. But the pdf rendered successfully.
Included file:
https://mozilla.github.io/pdf.js/build/pdf.js
https://mozilla.github.io/pdf.js/build/pdf.worker.js
https://raw.githubusercontent.com/mozilla/pdf.js/master/web/text_layer_builder.js
https://raw.githubusercontent.com/mozilla/pdf.js/master/web/ui_utils.js
https://raw.githubusercontent.com/mozilla/pdf.js/master/web/text_layer_builder.css

**Comment by Snuffleupagus** [comment]
Please see the `viewer components` examples: https://github.com/mozilla/pdf.js/tree/master/examples/components
