### ISSUE TITLE
Text and Lines are missing on iOS 12.4

### ISSUE THREAD

**Issue by dmsalex** [mozilla/pdf.js#11083]
Attach (recommended) or Link to PDF file here:
[example.pdf](https://github.com/mozilla/pdf.js/files/3518957/example.pdf)

Configuration:
- Web browser and its version:
	Safari 12.4
- Operating system and its version:
	iOS 12.4
- PDF.js version:
	Stable v2.1.266
- Is a browser extension:
	tested in viewer.html example on iPad
	
Steps to reproduce the problem:
1. Open example.pdf with viewer.html
2. Compare viewer.html result with actual pdf

What is the expected behavior? (add screenshot)	
![expected](https://user-images.githubusercontent.com/39411615/63321950-7b830800-c322-11e9-84d6-104eb0e0db41.png)

What went wrong? (add screenshot)
	Most of the Text and Lines is missing
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
	see example pdf

**Comment by Snuffleupagus** [comment]
This looks like a platform/browser bug (perhaps `canvas` related), rather than a PDF.js one, hence this unfortunately doesn't seem like that something that can be fixed *here*.
