### ISSUE TITLE
show the head of PDF.js with acromForm

### ISSUE THREAD

**Issue by Cheikhaoui** [mozilla/pdf.js#11094]
I want to show the head of PDF.js when use acroforms project
Steps to reproduce the problem:
1. example in https://github.com/mozilla/pdf.js/tree/master/examples/acroforms
What is the expected behavior? 
![image](https://user-images.githubusercontent.com/24354730/63635983-edc85500-c660-11e9-9dad-af74d0cdc2c8.png)
What went wrong? 
![image](https://user-images.githubusercontent.com/24354730/63635964-a8a42300-c660-11e9-8355-f837dbde8385.png)

**Comment by timvandermeij** [comment]
The AcroForms example is not a complete viewer, but only a minimal example of how to create a small viewer yourself. If you want a fully-fledged viewer, you'll need to adapt the default viewer in the `web` folder instead.

**Comment by Cheikhaoui** [comment]
thanks Tim for your respond , I didn't understand your idea about adapt the default viewer in the web folder if you can clarify it by an example ( I m not good with javaScript ) 
Thanks

**Comment by timvandermeij** [comment]
The default viewer at https://github.com/mozilla/pdf.js/tree/master/web is the full viewer with all functionality that the built-in PDF viewer in Firefox has. The examples in https://github.com/mozilla/pdf.js/tree/master/examples are exactly that: examples of how to built your own minimal viewer, mostly using components. They are not meant to illustrate how to build a full viewer; that requires a lot more code/logic and that's done in the `web` folder. You can create your own viewer by using the `web` folder and skinning it/stripping unnecessary parts for your use case.

**Comment by Cheikhaoui** [comment]
Hello, 
thanks again I have a question can I edit the code 
 for (var i = 1; i <= doc.numPages; i++) {
    promise = promise.then(function (pageNum) {
      return doc.getPage(pageNum).then(function (pdfPage) {
        // Create the page view.
        var pdfPageView = new pdfjsViewer.PDFPageView({
          container: container,
          id: pageNum,
          scale: DEFAULT_SCALE,
          defaultViewport: pdfPage.getViewport({ scale: DEFAULT_SCALE, }),
          annotationLayerFactory:
            new pdfjsViewer.DefaultAnnotationLayerFactory(),
          renderInteractiveForms: true,
        });

        // Associate the actual page with the view and draw it.
        pdfPageView.setPdfPage(pdfPage);
        return pdfPageView.draw();
      });
    }.bind(null, i));
  }
that if the page have a (digital signature )  do this    renderInteractiveForms: false, 
because if renderInteractiveForms: true then I can't show digital signatur 

Thank you

**Comment by timvandermeij** [comment]
Digital signatures are not supported in PDF.js yet and are tracked in https://github.com/mozilla/pdf.js/labels/4-digital-signature.

Do note that this is a bug tracker and not a general support forum, so setting up PDF.js is something you'll have to do yourself or get help from the community for.
