### ISSUE TITLE
pdf.js支持懒加载吗？

### ISSUE THREAD

**Issue by dsh225** [mozilla/pdf.js#11099]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by dsh225** [comment]
怎么设置

**Comment by timvandermeij** [comment]
Closing since we can only communicate in English.
