### ISSUE TITLE
Chrome 49.xx 无法打开

### ISSUE THREAD

**Issue by winneyLin** [mozilla/pdf.js#11100]
Chrome 49.xx 版本打开pdf流文件，报缺少PDF文件，但是在Chrome 49+以上版本是可以打开的，是否存在低版本兼容问题

**Comment by timvandermeij** [comment]
Closing since we can only communicate in English.

**Comment by winneyLin** [comment]
Version 49.xx of Chrome opens PDF stream file and reports lack of PDF file, but it can be opened in Chrome 49+ and above versions, is there any problem of low version compatibility

**Comment by timvandermeij** [comment]
Chrome 49 is over three years old, so I'm not surprised that it doesn't work anymore given that we only support recent Chrome versions. You'll have to upgrade your browser.
