### ISSUE TITLE
Text format is different when text selected on pdf.js, Acrobat Reader and Google Chrome

### ISSUE THREAD

**Issue by Jun711** [mozilla/pdf.js#11101]
Attach (recommended) or Link to PDF file here:
[pdf-file.pdf](https://github.com/mozilla/pdf.js/files/3547881/PatternRecognition_part2_2019.pdf)

Configuration:
- Web browser and its version: Chrome 76
- Operating system and its version: macOS High Sierra 10.13.6
- PDF.js version: tested using https://mozilla.github.io/pdf.js/web/viewer.html on 190827
- Is a browser extension: no

Steps to reproduce the problem:
1. Load the document
2. Open page 1, and look for text 'To solve this, we will need the EM algorithm, which stands for Expectation Maximization.'
3. Select text and right click.
4. Note that there is extra spacing between characters.

What is the expected behavior? (add screenshot)
Expect text to have no spacing like when it is opened using Acrobat Reader and Chrome browser.  

<img width="689" alt="Open PDF using Chrome Browser" src="https://user-images.githubusercontent.com/6880939/63803720-667e1a00-c8ca-11e9-8670-4a365e807076.png">

What went wrong? (add screenshot)
Extra spacing between each character.  

<img width="761" alt="Open PDF using pdf.js" src="https://user-images.githubusercontent.com/6880939/63803405-aabcea80-c8c9-11e9-8cf7-821288a204cc.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by imskr** [comment]
I want to work on it!  Please assign me.

**Comment by timvandermeij** [comment]
It's yours!

**Comment by imskr** [comment]
Why only exact specific line in that pdf showing with extra spaces on selection ?

**Comment by Snuffleupagus** [comment]
> Why only exact specific line in that pdf showing with extra spaces on selection ?

The entire purpose of this issue is to figure out *why* that happens, and then once you've found the answer try to write a patch that fixes the problem (without breaking something else in the process).

It honestly seems somewhat strange to first ask to be assigned to the issue, implying that you intend to debug/fix it, and then essentially ask *someone else* to debug it for you!?

(Whether or not this is a good beginner bug probably depends a lot on prior familiarity with the PDF spec.)

**Comment by imskr** [comment]
I understand @Snuffleupagus I just wanted some more insight. I will fix it

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
