### ISSUE TITLE
Using Base 64 with Next/Previous 

### ISSUE THREAD

**Issue by grbe1l** [mozilla/pdf.js#11117]
Looking through the code samples I can see that there is base64 example (https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html). I tried to add the previous and next buttons on that are in this example (https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html) but I cannot get it to work with the base64 instead of a actual pdf file. 

 Can this do this? and is there an example?

**Comment by Snuffleupagus** [comment]
As mention in the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file): It's not recommended to use `Base64` encoding, since it's a very inefficient way to represent binary data. Not only does it require more memory than e.g. a `Uint8Array`, some browsers may even truncate long `Base64` strings.

**Comment by timvandermeij** [comment]
Instead of passing the URL to the loading task like in the previous/next example, you can pass the `base64` data like in https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html. It can be done but, as indicated above, it's not the recommended way of working.

**Comment by grbe1l** [comment]
I don’t believe my question has been answered as I stated in the question I have seen both examples and cannot get base64 to work with next and previous buttons. Linking me to a example I already linked is not much help...

**Comment by timvandermeij** [comment]
Well, "cannot get it to work" is not something that is actionable for us, so for assistance you always need to fill out the entire issue template, give examples of what you tried so far and what exactly doesn't work. There is no complete example of what you want to achieve, but it should be possible to compose it out of the two given examples, so if that doesn't answer the question then more details are necessary...
