### ISSUE TITLE
How to force web viewer to start on page 1?

### ISSUE THREAD

**Issue by ApsGitAdmin** [mozilla/pdf.js#11114]
Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: 2.0
- Is a browser extension: No

I'm looking to enforce the web viewer to always start from the first page on load, which seems to be a similar issue to #7627, although I can't find a variable called showPreviousViewOnLoad, which I assume has been modified since that version has been asked. 

I assume it's a variable I can set in the viewer.js file, but I'm not sure what to change.

Thanks

**Comment by dhuang612** [comment]
That question was in regards to specifically Chrome.
under the folder web -> chromecom.js 
```
  let defaultManagedPrefs = Object.assign(
          {
            showPreviousViewOnLoad: true,
}
```

**Comment by ApsGitAdmin** [comment]
Is that specific to Chrome though? I want this to be a global setting, regardless of what browser you're using.

I only referenced that previous issue because it seemed to be asking a similar request. I need it to work like that, regardless of browser. 

Added to which, I don't know if I have that same distribution of the code, I got my version from here: http://mozilla.github.io/pdf.js/getting_started/ - so I don't have a chromecom.js file

**Comment by timvandermeij** [comment]
The `showPreviousViewOnLoad` preference is deprecated; see: https://github.com/mozilla/pdf.js/blob/a045a00af34b764edda5991d2bcd18541ed60536/extensions/chromium/preferences_schema.json#L5

You can set the `viewOnLoad` app option to `1` now instead to always show the first page; see https://github.com/mozilla/pdf.js/blob/a1a667809f286b761644bf34a4fb21dd524da8c8/web/app_options.js#L146

**Comment by ApsGitAdmin** [comment]
Thanks, that's worked perfectly
