### ISSUE TITLE
Viewer partially fails to render image on retina screen

### ISSUE THREAD

**Issue by 0range11** [mozilla/pdf.js#11121]
Attach (recommended) or Link to PDF file here:
[CardPicksパンフレット.pdf](https://github.com/mozilla/pdf.js/files/3577334/CardPicks.pdf)
[【構成案】セールステック営業資料.pdf](https://github.com/mozilla/pdf.js/files/3577335/default.pdf)

### Configuration:
 - Web browser and its version:
            **Google Chrome(ver. 76.0.3809.132)**
 - Operating system and its version:
            **macOS Mojave(ver. 10.14.6)**
 - PDF.js version:
           **Stable (v2.1.266)**
 - Is a browser extension:
            **No**

### Steps to reproduce the problem:
Here is my code: 
index.html
```
<div class="pdf-viewer">
  <div id="pageContainer" class="pdf-page"></div>
</div>
```

index.js
```javascript
pdfjsLib.workerSrc = '/vendor/assets/pdfjs/build/pdf.worker.js'
var pdfDoc;
var scale = 1;

var loadingTask = pdfjsLib.getDocument({
  url: #{pdf-url},
  cMapUrl: '/cmaps/',
  cMapPacked: true
})

loadingTask.promise.then(function(pdf){
  pdfDoc = pdf;
  var viewer = document.getElementById('pageContainer')
  for(page = 1; page <= pdf.numPages; page++){
    var canvas = document.createElement('canvas');
    if(page == pdf.numPages){
      canvas.className =  'pdf-page-canvas d-block m-auto'
    }else{
      canvas.className =  'pdf-page-canvas d-block m-auto pb-2'
    }
    viewer.appendChild(canvas);
    renderPage(page, canvas, viewer)
  }
})

function renderPage(pageNum, canvas, container){
  pdfDoc.getPage(pageNum).then(function(page){
    var originalViewPort = page.getViewport({scale: scale})
    var aspectScale;
    var isLandscape = true;
    if(originalViewPort.height > originalViewPort.width){
      isLandscape = false;
    }
    if(isLandscape){
      aspectScale = Math.max((container.clientWidth / originalViewPort.width), (container.clientHeight / originalViewPort.height))
    }else{
      aspectScale = Math.min((container.clientWidth / originalViewPort.width), (container.clientHeight / originalViewPort.height))
    }
    var viewport = page.getViewport({scale: aspectScale})
    var ctx = canvas.getContext('2d')
    canvas.width = (originalViewPort.width * aspectScale) * window.devicePixelRatio
    canvas.height = (originalViewPort.height * aspectScale) * window.devicePixelRatio        
    canvas.style.width = String(originalViewPort.width * aspectScale) + "px";
    canvas.style.height = String(originalViewPort.height * aspectScale) + "px";
    ctx.scale(window.devicePixelRatio,window.devicePixelRatio)  
    page.render({canvasContext: ctx, viewport: viewport});
  })
}
```
The viewer partially fails to render image when the devicePixelRatio is greater than 1.

What is the expected behavior? (add screenshot)
![スクリーンショット 2019-09-05 12 13 29](https://user-images.githubusercontent.com/54891751/64310231-50630e80-cfda-11e9-8b03-7da985cc5652.png)

What went wrong? (add screenshot)
<img width="827" alt="スクリーンショット 2019-09-05 12 14 34" src="https://user-images.githubusercontent.com/54891751/64310240-5953e000-cfda-11e9-8d35-ce84e07a8986.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Google Chrome(ver. 76.0.3809.132)
> Operating system and its version: macOS Mojave(ver. 10.14.6)
> PDF.js version: Stable (v2.1.266)

Given that this looks like a bug in the platform/browser, rather than in PDF.js, is it meaningful to keep this issue open?

---

There's perhaps also the possibility that the code doesn't take HiDPI-displays into account *correctly*, however that's very difficult to tell from just code-snippets, hence the only suggestion here would be to try e.g. the `simpleviewer` example and see if that works: https://github.com/mozilla/pdf.js/tree/master/examples/components
