### ISSUE TITLE
Remove gulp-transform dependency 

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#11125]
It appears gulp-transform has been abandoned by the author and it contains a dependency on an old version of gulp-util which has a critical security vulnerability. I don't think the vulnerability is actually an issue for our use, but it would be nice to have a clean audit of the pdf.js deps. 

I think we could replace it with something like https://gist.github.com/CITguy/079c631ac5f181939e08

**Comment by brendandahl** [comment]
@Snuffleupagus or @timvandermeij any interest in taking this on?

**Comment by 0x15F9** [comment]
Can I work on this?

**Comment by timvandermeij** [comment]
@0x15F9 Yes, please feel free to work on this.

**Comment by 0x15F9** [comment]
In which folder to I need to add the custom code to replace gulp-transform?

**Comment by timvandermeij** [comment]
I would put it in the `gulpfile.js` file itself since it's stand-alone and the replacement code should be very small. You can test your changes by running the commands that use `gulp-transform` before and after your patch and asserting that they produce the same files/changes.

**Comment by 0x15F9** [comment]
I am unable to figure the purpose of line 13 in myTransform.js athttps://gist.github.com/CITguy/079c631ac5f181939e08 . Could you  help me out?

**Comment by timvandermeij** [comment]
The comment states that `contents can only be a Buffer, Stream, or null`, so this line sets the contents of the new file. Basically, the transform function takes one file and transforms it to another file. My advice is to first look at how we use the `gulp-transform` package so the example of `myTransform` becomes more clear.

**Comment by MrNoddyInfy** [comment]
@0x15F9 are you still working on this?

**Comment by smohtadi** [comment]
Hi. I would like to work on this issue? Is it still open?

**Comment by dungeonaltaf** [comment]
Hi, Is the issue still open?

**Comment by timvandermeij** [comment]
It doesn't look like @0x15F9 is still working on this, so since @MrNoddyInfy was the next to ask they can work on it. If they cannot work on it, @smohtadi can, et cetera. Please comment here if you cannot work on it so the next one can take it.

**Comment by MrNoddyInfy** [comment]
@timvandermeij you can assign it to anyone else interested since I am not looking into this.

**Comment by timvandermeij** [comment]
@MrNoddyInfy Thank you for letting us know. @smohtadi Are you interested in picking this up?

**Comment by smohtadi** [comment]
Yes, I'll work on this.

**Comment by smohtadi** [comment]
Hi @timvandermeij, I'm planning to create a custom transform module that takes in a function and follows the logic on example provided above.
I'm wondering if you have any preference as to the location of this file.

**Comment by timvandermeij** [comment]
Since the transform function should be small, I would suggest to put it in the Gulpfile so it's self-contained.
