### ISSUE TITLE
Ink annotation popup not shown

### ISSUE THREAD

**Issue by fibbo** [mozilla/pdf.js#11122]
Attach (recommended) or Link to PDF file here:

[ink_annotation.pdf](https://github.com/mozilla/pdf.js/files/3579759/ink_annotation.pdf)

Configuration:
- Web browser and its version: Firefox Developer 70.0b3 (64-bit)
- Operating system and its version: Windows 10 1903 18362.329
- PDF.js version: [Demo page](https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the file
2. Popup for the ink annotation which has line width 1 is not shown

### _What is the expected behavior?_

When the cursor is over the ink annotation, the popup annotation should show up as a hover element.

### _What went wrong?_

The problem seems to be how PDF.js handles default missing 'BS' entries in the annotation dictionary. According to the standard a BorderStyle entry with width 1 and style solid is a default entry and doesn't need to be serialized. PDF.js seems to rely on this entry for the popup detection/display and when it's missing the popup does not show.

**Comment by THausherr** [comment]
Indeed, here's one with `/BS <<W 1>>` added and now it appears.
[ink_annotation-BS1.pdf](https://github.com/mozilla/pdf.js/files/3579916/ink_annotation-BS1.pdf)
