### ISSUE TITLE
PDF Printing

### ISSUE THREAD

**Issue by albertusgeyser** [mozilla/pdf.js#11135]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 69
- Operating system and its version: Windows 10
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1.  Do not know how to add print button / event.

I have the following and viewing my pdf on website, but would like to add print and/or download:

`var pdfData = atob(jsonStr);           
            var pdfjsLib = window['pdfjs-dist/build/pdf'];
            pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';
            var loadingTask = pdfjsLib.getDocument({data: pdfData});
            loadingTask.promise.then(function(pdf) {
            console.log('PDF loaded');
  
            // Fetch the first page
            var pageNumber = 1;
            pdf.getPage(pageNumber).then(function(page) {
            console.log('Page loaded');
    
            var scale = 1.5;
            var viewport = page.getViewport({scale: scale});

            // Prepare canvas using PDF page dimensions
            var canvas = document.getElementById('the-canvas');
            var context = canvas.getContext('2d');
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            // Render PDF page into canvas context
            var renderContext = {
            canvasContext: context,
            viewport: viewport
            };
           var renderTask = page.render(renderContext);
           renderTask.promise.then(function () {
           console.log('Page rendered');
    });
  });
}, function (reason) {
  // PDF loading error
  console.error(reason);
});
`

Hope anyone could shed light on my issue.

Thank You

Albertus Geyser

**Comment by timvandermeij** [comment]
You'll need to get the logic for that from the default viewer, i.e., https://github.com/mozilla/pdf.js/blob/master/web/app.js. This is because printing and downloading are non-trivial features that require a bit of additional code to work. For printing most logic is in the print services in the `web` folder and for downloading there is a download manager in the `web` folder.
