### ISSUE TITLE
Missing first page 

### ISSUE THREAD

**Issue by uxmaster** [mozilla/pdf.js#11139]
Attach (recommended) or Link to PDF file here:
[FR Cekada SedesUnCum.pdf](https://github.com/mozilla/pdf.js/files/3602024/FR.Cekada.SedesUnCum.pdf)

Configuration:
- Web browser and its version: Firefox 69 & Chrome 77
- Operating system and its version: Ubuntu 16.04.6 LTS
- PDF.js version: 2.3.160
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF.
2. The first page is missing. The page displayed as first is actually the second one.

What is the expected behavior? (add screenshot)
![1](https://user-images.githubusercontent.com/5693497/64721931-c3362300-d4cd-11e9-887a-e823533dd11a.png)

What went wrong? (add screenshot)
![2](https://user-images.githubusercontent.com/5693497/64721949-ca5d3100-d4cd-11e9-8b8c-a962a8ad8506.png)

**Comment by timvandermeij** [comment]
This is an interesting one. I see `Warning: Indexing all PDF objects` in the console which usually indicates that the PDF file is corrupted in some way. For example Okular seems to be able to recover from this.
