### ISSUE TITLE
PDF loading with greyed out text inside Xamarin Android WebView

### ISSUE THREAD

**Issue by duindain** [mozilla/pdf.js#11147]
Configuration:
- Web browser and its version: Chrome? Default Android WebView on a Pixel 2 emulator and Pixel 2 physical device
- Operating system and its version: Android 9 API 28
- PDF.js version: 2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. Clone solution (https://github.com/duindain/PDFjsGrey)
2. Open "pdfTester.sln"
3. Restore nuget packages
4. Run "pdfTester.Android" on a recent Android device or emulator
5. Select a pdf from the picker, (it should render grey) navigate back and reselect the same pdf from the picker (Within 3 to 10 loads it will render correctly)

What is the expected behavior? (add screenshot)
[Screenshot](https://github.com/duindain/PDFjsGrey/raw/master/PDFjs%20Rendering%20text%20correctly%20after%20two%20retries.png)

What went wrong? (add screenshot)
[Screenshot](https://github.com/duindain/PDFjsGrey/raw/master/PDFjs%20Rendering%20text%20as%20grey%20or%20disabled.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://github.com/duindain/PDFjsGrey

I've added the output from Chrome remote debugger to the repo and here, unfortunately it doesn't seem helpful as it is just a single line of text whether the pdf is rendered correctly or not

`PDF a542b7ae69a71147a88b29253c4b493c [1.5 Microsoft® Word 2013 / Microsoft® Word 2013] (PDF.js: 2.1.266)`

**Comment by duindain** [comment]
My repo may help @NextAlexM with #10798 as it does render the PDF he was having issues with
but it will have greyed out text at the moment

**Comment by Snuffleupagus** [comment]
*Generally speaking:* If this is specific to a particular platform/browser then it's unfortunately very unlikely to be a valid/actionable bug for the PDF.js library, and it's thus much more likely to be e.g. a `canvas`-related bug in the platform/browser itself.

**Comment by duindain** [comment]
This has stopped happening in the last few months

It must have been an issue on Android browser/Xamarin side as there were no updates to our application or pdf.js implementation related to this, however now the pdfs render in color correctly in the example app i provided and in our actual application

Thanks for helping investigate :)

Hopefully the example code is useful for others trying to implement a modern version of Xamarin with pdf.js
