### ISSUE TITLE
PDF not rendering in safari browser for Mac

### ISSUE THREAD

**Issue by lokesheltropy** [mozilla/pdf.js#11149]
Attach (recommended) or Link to PDF file here:
[0912154521-100101-10021005401568270729238.pdf](https://github.com/mozilla/pdf.js/files/3615575/0912154521-100101-10021005401568270729238.pdf)

Configuration:
- Web browser and its version: Safar 12.1.2
- Operating system and its version: Mac 10.14.6
- PDF.js version: 
 I was checking the latest version available at "https://mozilla.github.io/pdf.js/web/viewer.html"
- Is a browser extension: No

Steps to reproduce the problem:
1. Open safari on mac os, browse "https://mozilla.github.io/pdf.js/web/viewer.html". Upload pdf attached in this message to preview it in a browser.
2. It keeps showing loading activity. Not able to render pdf.

What is the expected behavior? (add screenshot)
[
<img width="1397" alt="Expected_Behaviour" src="https://user-images.githubusercontent.com/40492338/64948905-b16dca80-d895-11e9-8c57-197bb68198bf.png">
](url)

What went wrong? (add screenshot)
<img width="1403" alt="Actual_Behaviour" src="https://user-images.githubusercontent.com/40492338/64948928-bb8fc900-d895-11e9-978b-5648251ec37c.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): I was using "https://mozilla.github.io/pdf.js/web/viewer.html" to test it, pdf viewer.

Thank You for your time and help.

**Comment by lokesheltropy** [comment]
Team,
Could you please help, when would be the fix available?

**Comment by lokesheltropy** [comment]
Hello @timvandermeij ,
Could you please help.

**Comment by timvandermeij** [comment]
I don't know what causing this. It could be related to #7423, but since it's browser-specific it's most likely an upstream issue.

**Comment by Liuyuanjiang** [comment]
@lokesheltropy  @timvandermeij   I just hit same issue ,  
When safari open pdf (with Tradational Chiness), there's display is blank page ,
but we use safari open english and sample chinese is working well .
and safari load bcmap less than chrome 
version info : react:16.12 ,  react-pdf:5.0.0-beta.3

**Comment by Snuffleupagus** [comment]
Is it really meaningful to keep this issue open, when everything points to a platform/browser bug (rather than a PDF.js one), since this doesn't seem like something that can be fixed *here*?

**Comment by frankboehmer** [comment]
Any update here? We're seeing this problem actually quite often on Safari
