### ISSUE TITLE
Shifted chars: Looks like some greek chars in this PDF come with width zero

### ISSUE THREAD

**Issue by agruber** [mozilla/pdf.js#11150]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox/Chrome
- Operating system and its version: Ubuntu/Windows
- PDF.js version: 2.3.171
- Is a browser extension: no

Steps to reproduce the problem:
1. Load the PDF file from https://drive.google.com/open?id=10bmiFNDZwtqRLIJYRl55JgkLVxGfkgpj
2. Check the Greek symbols in the graph

What is the expected behavior? (add screenshot)

https://drive.google.com/file/d/1BzIrfaJVXmld1_QiqR4-r9jtbpodj1aQ/view?usp=sharing

What went wrong? (add screenshot)

https://drive.google.com/file/d/1RUqzdG7s4klsPo_v5BpaUeJKMETVP-xI/view?usp=sharing

**Comment by janpe2** [comment]
Fonts Times-Roman, Times-Italic, and Symbol are embedded but they don't have a `Widths` entry although it is required in embedded fonts. Acrobat Reader is somehow able to use the metrics of the corresponding standard fonts that have the same names.
