### ISSUE TITLE
first request of range request download whole pdf file？

### ISSUE THREAD

**Issue by yuweiming2016** [mozilla/pdf.js#11161]
Configuration:
- Web browser and its version: chrome 75
- Operating system and its version: centos7.3
- PDF.js version: 2.1.266
- Is a browser extension: no

I opened the pdf.js demo with chrome and I found that the range request was in effect, but why did the first request download the whole pdf file?
![image](https://user-images.githubusercontent.com/22490427/65216309-06525080-dae3-11e9-9e7a-6e4a1c0200a2.png)

What is the expected behavior? (add screenshot)
i expect result as follow:
![image](https://user-images.githubusercontent.com/22490427/65216425-6943e780-dae3-11e9-97af-b5233809edc6.png)

Am I missing something? 

http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
This is the expected result of PR #8768, which was needed to address issue #5319. Although it's not recommended to disable streaming for performance reasons, it can be done using the following option: https://github.com/mozilla/pdf.js/blob/7af66c8c1216f2be7bdb4f52975bc4b2abb387e5/src/display/api.js#L189-L191

**Comment by yuweiming2016** [comment]
@Snuffleupagus, thank you for you answer! it work for me now. may i ask why there is some performance reasons when settting disableStream=true？
