### ISSUE TITLE
Potential race condition between getDocument and destroy

### ISSUE THREAD

**Issue by 40thieves** [mozilla/pdf.js#11166]
Attach (recommended) or Link to PDF file here: See [minimal working example](https://github.com/40thieves/pdfjs-multiple-getdocument).

Configuration:
- Web browser and its version: Chrome 77
- Operating system and its version: macOS 10.13
- PDF.js version: 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:

I've created a [minimal working example](https://github.com/40thieves/pdfjs-multiple-getdocument#steps-to-reproduce) that contains the steps to reproduce

What is the expected behavior? (add screenshot)

See the [minimal working example](https://github.com/40thieves/pdfjs-multiple-getdocument#notes) for more details, but a second call to `getDocument` should not race against a call to `PDFDocumentLoadingTask.destroy()`.

However this may be unnecessary, I am not sure how PDFjs should handle scenarios like this and I could not find any documentation for this.

What went wrong? (add screenshot)

See the [minimal working example](https://github.com/40thieves/pdfjs-multiple-getdocument#notes) for more details, but a second call to `getDocument` races against `PDFDocumentLoadingTask.destroy()` meaning that the PDF fetch is run on a worker that is about to be destroyed.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

A hosted version of the minimal working example is available [here](https://silly-knuth-42fbb4.netlify.com/).

**Comment by Snuffleupagus** [comment]
You should wait for the `PDFDocumentLoadingTask.destroy()` method to complete first, since it's asynchronous, please see https://github.com/mozilla/pdf.js/blob/c289f3a969cfab14d00e4f575955ed4055c01e2a/src/display/api.js#L477-L494,

**Comment by 40thieves** [comment]
D'oh, thanks for that. I was looking at the `PDFWorker.destroy` source (which isn't async) and didn't think to look at the `PDFDocumentLoadingTask.destroy` source. That resolves my issue. Thanks again.
