### ISSUE TITLE
PDF File issue

### ISSUE THREAD

**Issue by uppalaadarsh** [mozilla/pdf.js#11164]
PDF.js v2.0.815 (build: d6927376)
Message: Invalid PDF structure
![pdf_issue](https://user-images.githubusercontent.com/20735948/65315011-f86d0000-dbb4-11e9-99de-b00474b1fc16.PNG)

 Can some one help me out on this..

**Comment by THausherr** [comment]
Please share your PDF.

**Comment by uppalaadarsh** [comment]
without PDF can it provide some solution.. as it is confidential.

**Comment by THausherr** [comment]
No. You could try viewing the file with other products and see what error messages they bring up, e.g. Apache PDFBox, VeraPDF, Chrome, Ghostscript. But most likely, it is your PDF that is to blame. Even if Adobe can display it.

**Comment by timvandermeij** [comment]
Alternatively, you could try to create a non-confidential PDF with the same generator to reproduce the issue, or remove the confidential information from the original PDF file, but without a sample PDF file or much more debugging information there is nothing we can do.
