### ISSUE TITLE
Render the entire page

### ISSUE THREAD

**Issue by heixincai** [mozilla/pdf.js#11179]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 76.0.3809.132
- Operating system and its version:Windows 7
- PDF.js version:2.2.228
- Is a browser extension:

Steps to reproduce the problem:
1.
When I import a 10-page pdf，i want to render the entire page,But it just renders the page I've located.
In the old version,i change the DEFAULT_CACHE_SIZE = 100,It is OK.
But when i upgrade the version to 2.2.228,it is not what i expected,What should i do?Thanks~

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> In the old version,i change the DEFAULT_CACHE_SIZE = 100,It is OK.

That's not recommended, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by heixincai** [comment]
> > In the old version,i change the DEFAULT_CACHE_SIZE = 100,It is OK.
> 
> That's not recommended, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages
Can you tell me how How to render a full PDF? Thank you very much~ @Snuffleupagus

**Comment by Snuffleupagus** [comment]
As is clearly outlined in the link I posted above rendering an entire file is *not* a good idea, hence that's not going to be officially supported.

(The only way to make it work would probably be to modify the [`BaseViewer._getVisiblePages`](https://github.com/mozilla/pdf.js/blob/master/web/base_viewer.js#L904) method to always treat all pages as visible.)
