### ISSUE TITLE
Trying to change the pdf opened in the viewer

### ISSUE THREAD

**Issue by cretub** [mozilla/pdf.js#11176]
Configuration:
- Web browser and its version: Any
- Operating system and its version: macOS 10.14.6
- PDF.js version: 2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. Call .open twice with a base64encoded pdf

What is the expected behavior? (add screenshot)

Change the content of the pdf viewer

What went wrong? (add screenshot)

This error occurs and pdf viewer is blank:

Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'this.pdfSidebar.reset')

Any solution or workaround?

**Comment by Snuffleupagus** [comment]
> Call .open twice with a base64encoded pdf

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Yes, this really sounds like a customization issue. Without a running example, we cannot help out with this, unfortunately.
