### ISSUE TITLE
Artifacts when rendering raster images on Raspberry Pi 4

### ISSUE THREAD

**Issue by xeloader** [mozilla/pdf.js#11170]
Attach (recommended) or Link to PDF file here:
[glass-tree-sun-labs.pdf](https://github.com/mozilla/pdf.js/files/3641322/glass-tree-sun-labs.pdf)

Configuration:
- Web browser and its version: Chromium 74.0.3729.157 Built on Raspbian , running on Raspbian 10
- Operating system and its version: Raspbian GNU/Linux 10 (buster)
- PDF.js version: 2.3.188
- Is a browser extension: No

Steps to reproduce the problem:
1. https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the pdf on a raspberry pi 4

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2003998/65413165-19ba3000-ddf1-11e9-8981-679c3077c5dd.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2003998/65413278-6998f700-ddf1-11e9-8355-7accf4f7928b.png)

**Comment by Snuffleupagus** [comment]
Given that this is specific to a particular platform/browser it's unfortunately very unlikely to be a valid/actionable bug for the PDF.js library, and it's thus much more likely to be e.g. a canvas-related bug in the platform/browser itself.

**Comment by THausherr** [comment]
Please try with another browser, e.g. Firefox.

**Comment by timvandermeij** [comment]
This breakage indeed looks like a canvas bug of the platform, so I don't think there is anything we can do about this. Please try another browser and report the issue upstream to e.g., the Chromium devs if another browser works.

**Comment by xeloader** [comment]
Thank you, it works perfectly on firefox. Made us switch from Chrome to Firefox when using Raspberry Pi 4.

**Comment by xeloader** [comment]
If anyone else has this problem. Updating the raspberry worked. Had to run it twice though, and I have no idea why.

```sh
apt update
apt upgrade
```
