### ISSUE TITLE
How to fallback to some system font when the font is not embedded?

### ISSUE THREAD

**Issue by huzjakd** [mozilla/pdf.js#11175]
Configuration:
Custom application. Any browser, Windows, version 2.1.266.

Steps to reproduce the problem:
1. Open any PDF that doesn't have some fonts embedded.
2. You get a console message about missing fonts. It is logged by evaluator.js in "loadFont" function ("fontRef not available").

What is the expected behavior?
It is all as expected.

What went wrong?
When it gets to this point, instead of the console message, I would like the pdf.js to load some default system font. I see there is a function in fonts.js: "fallbackToSystemFont" but I can't quite get it to work.

**Comment by timvandermeij** [comment]
Fixed by the pull request above.
