### ISSUE TITLE
Pdf.js viewer.html not calling all range requests

### ISSUE THREAD

**Issue by richiepriya** [mozilla/pdf.js#11174]
I have some issue in downloading the pdf using range requests. I am using spring boot application to provide download service. viewer.html makes 1st request which is cancelled since service supports range request and initiates partial request which is as expected but there are no further requests from browser, Its just 2 range requests where as i am expecting it to request till whole pdf is downloaded. Is there any special header that needs to be added in response so that browser sends all request to service. When i tried https://mozilla.github.io/pdf.js/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf link and inspect networks then i am able to see 1st request getting 200 response code which is cancelled before whole pdf is downloaded and then range requests(for all ranges) are initiated which gives 206 partial content

I have used spring boot for serving pdf by following https://gist.github.com/davinkevin/b97e39d7ce89198774b4

With these 2 set up and enabling cors requests. I am able to accomplish following

1. client is recognizing that server supports range request and is cancelling main request.
2.   client is initiating range requests
3. added headers in response : accept-ranges, content-length, content-range, accept, etag, content-type, content-disposition, last-modified, expires, Connection,vary,via,Cache-Control and exposed all of them.

**Problem faced :**

- client is initiating only 2 range requests after cancelling main request and stops there.
![sl_pdf](https://user-images.githubusercontent.com/41781231/65493822-42b1f200-ded1-11e9-8b32-8a3b1639cbd5.PNG)

Since we are using build version of pdf.js, we have not customized it. When we are trying to get pdf from another server which is a spring boot application that allows CORS request.

**Comment by Snuffleupagus** [comment]
*In its current form, the issue will be closed as incomplete/invalid since its missing too much information.*

You need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, and please make sure to follow https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Indeed. Without a working demo, there is practically nothing we can do to debug this.
