### ISSUE TITLE
Cannot load dynamic PDF file

### ISSUE THREAD

**Issue by louis123562** [mozilla/pdf.js#11172]
The 'file' parameter links to a NodeJS Script which returns a PDF File like this:

iFrame-src:
https://192.168.199.4/inc/javascript/web/viewer.html&file=192.168.199.4:8080

NodeJS:
//pdf contains the pdf as string
        res.writeHead(200, {
            'Content-Type': 'application/pdf',
            'Content-Disposition': 'attachment; filename=some_file.pdf',
            'Content-Length': pdf.length
        });
        res.end(pdf);

I just get a 404, but when typing 192.168.199.4:8080 into browser, it wants me to download the pdf file.

What can i do to get it rendered instead of a 404?

**Comment by Snuffleupagus** [comment]
This issue is currently missing all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
You might be running into a CORS issue given that the port is different; see https://stackoverflow.com/questions/19966707/cors-error-on-same-domain. Other than that it's impossible for us to provide more assistance without all information from the issue template.

**Comment by louis123562** [comment]
I fixed it meanwhile and yes, it was a CORS problem.
Thank you!
