### ISSUE TITLE
GET parameters are cut away

### ISSUE THREAD

**Issue by louis123562** [mozilla/pdf.js#11180]
I refer to #11113 and try to point it out more exactly:

**What i do in JS**
```
//preparing URL for iFrame source
let big_url = "https://example.og/inc/js/web/viewer.html?file=https://example.org?key1=value1&key2=value2";

//setting iFrame source
$("#pdfViewer").attr("src", big_url);
```

**What my NodeJS recieves (second URL in big_url)**
instead of showing me something like this:
```
key1: "value1"
key2: "value2"
```
it shows only the first key with no value:
`key1: ""`

I guess that the **app.js** cuts of the parameters maybe somewhere over here:
![grafik](https://user-images.githubusercontent.com/36068395/65686409-a02a7800-e064-11e9-9841-457c25930856.png)

Maybe you understand now?!

**Comment by Snuffleupagus** [comment]
Please note that as mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, the file URL should be encoded with `encodeURIComponent()`.

If that doesn't fix the issue, then please actually provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):

> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem.**

**Comment by louis123562** [comment]
Ah - works like a charm.
I'm very sorry for disturbing!
