### ISSUE TITLE
document.domain is wrong

### ISSUE THREAD

**Issue by worthy7** [mozilla/pdf.js#11184]
The `document.domain` property is set to `PDF.js` when it should be whatever URL we are on in accordance with:
https://developer.mozilla.org/en-US/docs/Web/API/Document/domain#Value

This is causing a bunch of problems for lots of people.

**Comment by Snuffleupagus** [comment]
Huh, there's no mention of `document.domain` *anywhere* in the PDF.js code-base; did you perhaps open this issue in the wrong repository by mistake?

If you actually intended to open an issue here, then you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by worthy7** [comment]
Sorry, perhaps this is actually a firefox issue with **it's**  custom pdf.js....

**Comment by worthy7** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1584867
