### ISSUE TITLE
`fullReader is null` error in Firefox, `Expected a function` error in Chrome

### ISSUE THREAD

**Issue by sdwang** [mozilla/pdf.js#11193]
Attach (recommended) or Link to PDF file here:
https://www.panerabread.com/foundation/documents/nutrition/Menu-Retail.PDF

Configuration:
- Web browser and its version:  Firefox 68.0.2, Chrome 77.0.3865.90
- Operating system and its version: macOS Mojave 10.14.6
- PDF.js version: 2.1.266
- Is a browser extension: false

Steps to reproduce the problem:
1. Import pdf-dist and set worker:
```
import pdfjsLib from 'pdfjs-dist';
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.js`;
```
2. Call `getDocument` in `componentDidMount`:
```
  componentDidMount() {
    const loadingTask = pdfjsLib.getDocument(`https://www.panerabread.com/foundation/documents/nutrition/Menu-Retail.PDF`);
    loadingTask.promise.then((doc) => {
      console.log(`Document loaded ${doc.numPages} page(s)`);
    }, (error) => {
      console.error(`Error during loading: ${error}`);
    });
}
```

I know there's a zero-configuration way to import pdfjs-dist but I ran into issues with that and I'd like to set the `workerSrc` directly.

What went wrong? (add screenshot)

There are different errors for Chrome and Firefox although the error occurs in the same place (in the error callback passed to loadingTask.promise.then)

Firefox:
<img width="1909" alt="Screen Shot 2019-10-02 at 09 41 00 AM" src="https://user-images.githubusercontent.com/10397350/66063732-d9496900-e4f8-11e9-876d-9c4cef3e0c4d.png">
Chrome:
<img width="870" alt="Screen Shot 2019-10-02 at 09 45 54 AM" src="https://user-images.githubusercontent.com/10397350/66064012-74424300-e4f9-11e9-8329-686636ece6f9.png">

I'm wondering if I'm setting the `workerSrc` incorrectly.  If anyone has any insight I'd greatly appreciate some help.  Thank you!

**Comment by Snuffleupagus** [comment]
> https://www.panerabread.com/foundation/documents/nutrition/Menu-Retail.PDF

That brings up a page stating:
> Access Denied
You don't have permission to access "http://www.panerabread.com/foundation/documents/nutrition/Menu-Retail.PDF" on this server.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sdwang** [comment]
I receive the same error no matter which PDF file I use.  I pulled the Panera pdf from their website and thought that it would be accessible to everyone.  Here are a few more that I tried:
http://www.africau.edu/images/default/sample.pdf
https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf

**Comment by sdwang** [comment]
Also, I'm able to load the pdf successfully using this example (https://github.com/yurydelendik/pdfjs-react) and changing the way it's importing pdfjs-dist to the way I'm doing it in my app:
```import pdfjsLib from 'pdfjs-dist';
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.js`;```
I'm guessing there's something going on in my app where the web worker isn't running correctly.  I'm wondering if anyone has encountered this issue before or has an idea where I should look.

**Comment by timvandermeij** [comment]
> I'm guessing there's something going on in my app where the web worker isn't running correctly.

Yes, if the other example works it's most likely an integration issue. However, without a working demo we are not able to help out with this, as stated above.

> I'm wondering if anyone has encountered this issue before or has an idea where I should look.

Not really, but note that nobody here is actively working with React, so this might not be the best forum to ask. In any case, we cannot help if we cannot run the full code unfortunately.

**Comment by sdwang** [comment]
Yeah, I understand it would be difficult for your team to look into it without a working demo.  I'm unable to get one up since it would be on our dev servers.

I've done some more digging and believe the issue is coming from a fetch polyfill in my app, which is causing an error here: https://github.com/mozilla/pdfjs-dist/blob/8ca1faf26b3d0e0b9f6fdce0e282bb06735a9e9d/lib/display/fetch_stream.js#L158

Thanks for taking the time to respond to my issue @timvandermeij and @Snuffleupagus.
