### ISSUE TITLE
Corrupted margins when printing on IE when viewer runs in iFrame

### ISSUE THREAD

**Issue by mihavuk** [mozilla/pdf.js#11197]
Attach (recommended) or Link to PDF file here:
compressed.tracemonkey-pldi-09.pdf is ok for test

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows Server 2016
- PDF.js version: 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:
1. Extract the attached ZIP and put the extracted "viewer iframe.html" in the same folder that web/viewer.html
[viewer iframe.zip](https://github.com/mozilla/pdf.js/files/3685173/viewer.iframe.zip) 
2. Open "viewer iframe.html" in IE browser and open any PDF (compressed.tracemonkey-pldi-09.pdf is ok)
3. Click on print button and print the document (to real printer or PDF Creator)

What is the expected behavior? (add screenshot)
Expected behavior is that the printed document is centered and looks like in the viewer

What went wrong? (add screenshot)
Actually the printed document is shifted to the right, scaled down in and some right text is cropped. See the result of printing to PDF Creator ob the link below
https://docentric-my.sharepoint.com/:b:/p/miha_vuk/EVAFW9ju89VDvpuVSKWxL1sBo1EfgDLVWvgi6UfSPshQnw?e=CfeCwT

It happens only on IE (works on Chrome and Edge) and only when viewer is embedded in iFrame.

**Comment by Snuffleupagus** [comment]
Duplicate of #8052.

In any case, please note that support for IE11 is limited as [outlined in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by mihavuk** [comment]
The fix described in #8052 works.
Thank you.
