### ISSUE TITLE
the 'headersReady' of undefined or null reference can not be retrieved.

### ISSUE THREAD

**Issue by kdogan** [mozilla/pdf.js#11192]
Configuration:
- Web browser and its version: IE11 (11.1387.16299.0)
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:

0. var d = Deferred();
1. PDFJS.GlobalWorkerOptions.workerSrc = '.../pdfjs-dist/build/pdf.worker.js'
2. var task = PDFJS.getDocument(binary);
3. task.promise.then((pdf) => {
   d.resolve(pdf.numPages);
}).catch((e) => {...});

What is the expected behavior?
-> find pdf.numPages

What went wrong?
-> the error with message "the 'headersReady' of undefined or null reference can not be retrieved." is catched. Promise is rejected

-> Same code work in chrome and firefox but not in ie11

thanks for help

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing since this is incomplete. It can be reopened once all information is provided.

**Comment by kdogan** [comment]
Hi @timvandermeij ,
i found the solution. The solution was only convert base64 to uint8array:
PDFJS.getDocument(uint8array) instead PDFJS.getDocument(base64)

this is the function to convert base64 to uint8array:

convertBase64ToUint8Array(base64){
    let base64Marker= ";base64,";
    const base64Index = base64.indexOf(base64Marker) + base64Marker.length;
    const strExpectBase64Marker = base64.substring(base64Index);
    const raw = window.atob(strExpectBase64Marker);
    const rawLength = raw.length;
    const array = new Uint8Array(new ArrayBuffer(rawLength));
    for(lent i = 0; i<rawLength ; i++) {
       array[i] = raw.charCodeAt(i);
   }
   return array;
}

best regards

**Comment by FrederickEngelhardt** [comment]
Getting a similar error with a url on ie 11. Is there a solution besides converting the url into a uint8array?

**Comment by rinfz** [comment]
If anyone is having this issue when requesting a document via a url, calling `encodeURI(url)` worked for me
