### ISSUE TITLE
PDF not rendering in Chrome for Android

### ISSUE THREAD

**Issue by obscure-d4m** [mozilla/pdf.js#11195]
Attach (recommended) or Link to PDF file here:
[page.pdf](https://github.com/mozilla/pdf.js/files/3684390/page.pdf)

Configuration:
- Web browser and its version: Chrome 77.0.3865.92
- Operating system and its version: Android 7.0
- PDF.js version: I was checking the latest version available at "https://mozilla.github.io/pdf.js/web/viewer.html"
- Is a browser extension: No

Steps to reproduce the problem:
1. Open Chrome on Android, browse "https://mozilla.github.io/pdf.js/web/viewer.html". 
2. Upload pdf attached in this message to preview it in a browser.
3. Rendering ends up showing blank page.

What is the expected behavior? (add screenshot)
![screenshot_opera](https://user-images.githubusercontent.com/53888852/66099090-9e663480-e5cf-11e9-9451-030ab8f41030.png)

What went wrong? (add screenshot)
![screenshot_chrome](https://user-images.githubusercontent.com/53888852/66099099-a58d4280-e5cf-11e9-9fc8-a73f4e20e9a6.png)

**Comment by Snuffleupagus** [comment]
Given that this bug is specific to a particular platform/browser, it's unfortunately not likely to be a valid/actionable bug for the PDF.js library and it's rather more likely to be e.g. a `canvas`-related bug in the platform/browser *itself*.

**Comment by timvandermeij** [comment]
Yes, I don't think there is anything we can do about this. Please report the issue to Chrome (upstream) instead. Thanks.
