### ISSUE TITLE
Is possiable to add span tag and class name for annotation

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#11196]
For example "Australian Securities and Investments Commission Act 2001" in the text 
"Securities" word contain strikeoutAnnotation i need to add <span class="strikeoutAnnotation">Securities</span>. please help me this method i am very struggle  on this.

**Comment by Snuffleupagus** [comment]
When opening an issue you need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) (which was also explained in e.g. issue #10627); as is this issue is INVALID.

Furthermore, it's very unclear what you're trying to ask here, but note that as previously mentioned PDF.js does not support adding annotations [which is also explained in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations).

**Comment by timvandermeij** [comment]
I agree. PDF.js does not provide editing capabilities since it's only a viewer/renderer.

**Comment by a7vickey** [comment]
For example "Australian Securities and Investments Commission Act 2001" in the text
"Securities" word contain strikeoutAnnotation i need to add `<span class="strikeoutAnnotation ">Securities</span>`. please help me this method i am very struggle on this.

**Comment by a7vickey** [comment]
> When opening an issue you need to provide _all_ of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) (which was also explained in e.g. issue #10627); as is this issue is INVALID.
> 
> Furthermore, it's very unclear what you're trying to ask here, but note that as previously mentioned PDF.js does not support adding annotations [which is also explained in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations).

Yes i know pdf js only reader and viewer. i am just asking is this possible?

**Comment by timvandermeij** [comment]
The text layer and annotation layers are DOM elements, so additional elements can be inserted if you want. It's just not something that the library itself provides.

**Comment by a7vickey** [comment]
I search all functions I can't able to find where I need to add this tag
for annotation text Please help me I am working this task more then one
month I am very struggle.

**Comment by a7vickey** [comment]
Any update mr.timvandermeij

**Comment by a7vickey** [comment]
How to fetch annotation data from pdf. what type of render process done for annotation.

**Comment by timvandermeij** [comment]
You can use the `getAnnotations` API call to get the data. Note that this is not a support forum, but a bug tracker, so this issue is closed now.

**Comment by a7vickey** [comment]
var rect=[96.3125,110.021,571.771,150.831];
is this possible to insert annotation tag into text layer  <span class="strikeoutAnnotation ">Securities</span>. please help me this method i am try solve more than month i cant able to find the right solution. are excepting any payment.
