### ISSUE TITLE
How to open PDF file with Pdf.js viewer after some PHP codes executing? (without ?file=URL_PDF)

### ISSUE THREAD

**Issue by malikshukurlu** [mozilla/pdf.js#11200]
I don't know my question title is enough good or not.
I am tried to build pdf viewer in my website with PDf.js. I know, normally it's simple as: http://example.com/pdfjs/web/viewer.html?file=PDF_NAME.pdf

But my claim is - Pdf name dont show in the address bar. I was created view.php from viewer.html codes. And I want like this:
http://example.com/pdfjs/web/view.php?file=1

So in my php page I check database and fetch fileurl from ID=1.
and finally I want to set Pdf.js viewer for to open my pdf from Fileurl. But I cant. I am lost much time for this, googling for hours, but I cant unfortunately.

It works now like -> view.php?file=PDF_NAME.pdf
But I want to like -> view.php?file="fileId"

What can I do for getting like this result? How load PDF with javascript after my php codes?
Or with .htaccess is it like this possible? (sorry for my low quality English)

- Web browser and its version:  Chrome (last)
- PDF.js version: v2.1.266

.
` // my view.php file 

// <?php (php start.)
if(isset($_GET['file'])){
  $file = mysqli_real_escape_string($db, @$_GET['file']);
}else{
  $file="";
}

if(is_numeric($file) AND $file!=""){
  $query = mysqli_query($db, "select * FROM pdf_files WHERE id='$file' ");
     if(mysqli_num_rows($query) == 1){
        $result = mysqli_fetch_assoc($sorgu);
        $filepath = $result['filepath'];
}

// ?> (php closed)
//then html codes starting (from pdfjs viewer.html) `

**Comment by Snuffleupagus** [comment]
It's unfortunately somewhat difficult to understand what you're actually trying to ask here, but please understand that that it's not really possible to for us to provide PHP integration support here.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Yes, this is out of scope for the issue tracker since this isn't a bug in PDF.js, which is what we're tracking here. For integration support, please use either IRC or open forums like StackOverflow.
