### ISSUE TITLE
Slow search of a word/phrase in pdf with more than 50 pages

### ISSUE THREAD

**Issue by sandeeppal1990** [mozilla/pdf.js#11208]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome version 77.0.3865.90
- Operating system and its version: Windows 10
- PDF.js version: 2.0.550
- Is a browser extension: No

Steps to reproduce the problem:
1. search a word that has its first occurrence after 50th page or more
2. The search will take lot of time as _extractText() of pdfFindController extracts the text on each page and it takes time. Some times it is taking more than 1 minute to give the result and this gives users a feeling that application is hanged. After the first search, the following search does not take time as the text is already extracted from the pages.

What is the expected behavior? 
The search should not take a lot of time

What went wrong?
The search was taking more than 1 minute for large pdf

**Comment by Snuffleupagus** [comment]
Most of the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is left completely blank, which means that the issue will be closed as INCOMPLETE.

**Comment by sandeeppal1990** [comment]
I have added more information to the issue description

**Comment by Snuffleupagus** [comment]
> I have added more information to the issue description

Unfortunately not *all* of it though, since the `Attach (recommended) or Link to PDF file here:` part is still missing which is *very* relevant here.

> PDF.js version: 2.0.550

That's not an official release, and it's thus unsupported; please find the latest releases at https://github.com/mozilla/pdf.js/releases

**Comment by timvandermeij** [comment]
Closing since no PDF file is provided. We can reopen this once it's added.
