### ISSUE TITLE
How load PDF file in viewer.html with javascript? (without "?file=PDF_NAME.pdf")

### ISSUE THREAD

**Issue by malikshukurlu** [mozilla/pdf.js#11201]
Hi again, my last issue didn't write correct. 
So how can I load my example.pdf file in viewer.html with javascript? which function for this?
I don't want to use the GET method (viewer.html?file=example.pdf).

I read the documentations, other issues, but I cant find or I cant understand. =/

**Comment by timvandermeij** [comment]
The `open` method on allows you to open a PDF file: https://github.com/mozilla/pdf.js/blob/master/web/app.js#L609-L618
