### ISSUE TITLE
Improve release automation

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11203]
GitHub fixed the release hook problems on their end. However, this exposed a problem in our release automation script in https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js. After making the previous pre-release stable, it pushed the previous pre-release commit to https://github.com/mozilla/pdfjs-dist again, presumably because https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js#L20 is done unconditionally. We have removed this commit manually for now, but for the next release the script should be improved.

**Comment by brendandahl** [comment]
Do we just need to add an `if (!jobInfo.prerelease) {` to that line?

**Comment by timvandermeij** [comment]
I think so. If it's a pre-release, we should not push the tag. Only stable releases should get a tag.

**Comment by timvandermeij** [comment]
I have made the pull request above that should resolve this problem. After this is merged, we can make the new release.
