### ISSUE TITLE
base_viewer.js doesn't support non-numerical page numbers

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#11216]
Attach (recommended) or Link to PDF file here:
http://www.connectedthebook.com/pdf/excerpt.pdf 

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: 2.2.228 (and probably also 2.3)
- Is a browser extension: no

Also see https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/147.

What is the expected behavior? 
The PDF file has both numerical and non-numerical page numbers. I'm using ` window.PDFViewerApplication.page = this.page;` to set the page number. With the example method, this runs havoc. The root cause seems to be the accessor ` _setCurrentPageNumber(...)`. This method assumes that the page number is a number. However, this isn't always the case, because some page numbers are roman numbers. In particular, I've identified these lines to cause trouble: 

https://github.com/mozilla/pdf.js/blob/cead77ef3a166849ee31925f5d6e011950e6fa5e/web/base_viewer.js#L199

https://github.com/mozilla/pdf.js/blob/cead77ef3a166849ee31925f5d6e011950e6fa5e/web/base_viewer.js#L224

**Comment by stephanrauh** [comment]
Maybe there's simply a clash of two different concepts:

- _setCurrentPage(page: number) uses what we could call the page index (always starting with 1).
- Some authors use a different page numeration. A frequent pattern is roman digits for the preface and arabic numbers for the rest of the document.

Is there a function accepting the author's numeration pattern as parameter? How to solve the problem? The showcase uses the author's numeration pattern, so it seems to be a problem that can be solved. At least most of the time: the input fields accepts "ix" and "v" as input, but refuses to work with "x" and "iix".

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3045767/66340957-964b2380-e946-11e9-9b10-1e498a2112d2.png">

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/cead77ef3a166849ee31925f5d6e011950e6fa5e/web/base_viewer.js#L241-L268

**Comment by timvandermeij** [comment]
What you're describing is called page labels in the PDF specification. PDF.js supports those as shown by the method from https://github.com/mozilla/pdf.js/issues/11216#issuecomment-539180888. If you use that, a page label will be translated to a page index. Note that only existing page labels work; the PDF file you linked goes to `ix` (9) and the next page label is the number 1, so `x` and `iix` have no meaning in this file since they are not page labels that exist in the file. Closing as answered.

**Comment by stephanrauh** [comment]
Thanks, guys! You've helped me a lot!
