### ISSUE TITLE
Saving (Stream Upload) PDF Forms

### ISSUE THREAD

**Issue by parmy** [mozilla/pdf.js#11215]
Attach (recommended) or Link to PDF file here:
Form coming

Configuration:
- Web browser and its version: Any pdf.js compatible browser
- Operating system and its version:Any pdf.js compatible OS 
- PDF.js version: Any
- Is a browser extension: n/a

Steps to reproduce the problem:
1. Open the attached form in a browser
2. Complete one or two fields
3. There is an option to Save the file locally - but no option to stream (upload) the file to a server

What is the expected behavior? (add screenshot)
Is it possible to override the Save File Locally behaviour to stream to a server instead?

What went wrong? (add screenshot)
n/a

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
n/a

Thanks,

Parmy

**Comment by timvandermeij** [comment]
PDF.js only has experimental support for AcroForms and there is no option yet to save the fields, so I think you're confusing PDF.js with another library/application.
