### ISSUE TITLE
Close issues only relevant for IE 11/Edge

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#11211]
As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for IE 11/Edge is limited and will eventually be completely removed:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

The idea here is obviously to eventually (or hopefully soon) remove support for these old browsers, such that most (if not all) compatibility code can be removed and the build scripts be simplified.
However, even with the current *limited* support status for IE 11/Edge, it's seems highly questionable (to me) if it makes sense to keep issues which are only relevant to IE 11/Edge open.

Basically, the open issues can be qualified into a couple of main categories:
 1. Issues that simply cannot ever be fixed, e.g. ones related to sub-par performance or ones related to blend modes.
 2. Issues which could *theoretically* be fixed, e.g. sidebar resizing in the viewer, where patches would never be accepted since it would complicate the code and hurt readability/maintenance.
 3. Issues which may be fixable, but wouldn't be limited to polyfills in `src/shared/compatibility.js` and thus won't be accepted.
 4. Issues where it's not even clear what the problem is, e.g. broken rendering. 

This leads to the conclusion that most IE 11/Edge issues either can't or won't be fixed, and that the rest would at this point in time essentially be a waste of developer/reviewer resources to even attempt to address (where technically possible).

It thus seems, at least to me, that it would be much better to close all of the relevant issues as WONTFIX, pointing to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, such that we can clean-up the tracker a little bit.[1]

This would include all issues labelled with:
 - https://github.com/mozilla/pdf.js/labels/4-ie11-specific
 - https://github.com/mozilla/pdf.js/labels/4-ie-edge-specific

... and then possibly ones satisfying the follow searches (since some issues *could* be incorrectly labelled):
 - https://github.com/mozilla/pdf.js/search?q=ie+11&state=open&type=Issues
 - https://github.com/mozilla/pdf.js/search?q=ie11&state=open&type=Issues
 - https://github.com/mozilla/pdf.js/search?q=ie&state=open&type=Issues
 - https://github.com/mozilla/pdf.js/search?q=edge&state=open&type=Issues

---
[1] It would also be clearer since having a (somewhat) large number of issue open, when they will never be fixed, could easily give users the false hope that they will someday be addressed.

**Comment by timvandermeij** [comment]
I agree with this. We don't have the resources to address IE/Edge-only issues and we haven't seen many contributions for this either. Given that `core-js` polyfills seem to have fixed most issues in those browsers, the remaining points are indeed the ones you mentioned.

**Comment by Snuffleupagus** [comment]
> [...] it would be much better to close all of the relevant issues as WONTFIX, pointing to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, such that we can clean-up the tracker a little bit

There's now been a month since this issue was opened, and (obviously) nothing has come to light which would prevent going forward with this plan as far as I can tell. Furthermore no one has objected either, although that would've needed to be accompanied by *very* good arguments.

@timvandermeij Unless you disagree with the time-line; would you mind going through and closing all the relevant issues as outlined by the links in https://github.com/mozilla/pdf.js/issues/11211#issue-503088334?

**Comment by timvandermeij** [comment]
I think I've had them all, but there were lots of search results, so I might have still missed some. If there are more, please add a comment here and we can close them.

**Comment by Snuffleupagus** [comment]
@timvandermeij Thanks a lot for doing this; it's nice to not have lots of non-actionable issues open!

**Comment by Thunderforge** [comment]
Just to clarify: are the issues that are being closed for IE/Edge limited to the [Trident](https://en.wikipedia.org/wiki/Trident_(software))/[EdgeHTML](https://en.wikipedia.org/wiki/EdgeHTML) browser engines? Will the project still accept issues for the [Chromium-based versions of Edge](https://www.pcmag.com/news/371746/chromium-based-microsoft-edge-browser-launches-in-january) (currently in beta, for general release on January 15, 2020)?

**Comment by timvandermeij** [comment]
Yes, this only applies to non-Chromium-based IE/Edge versions.
