### ISSUE TITLE
PDF page turns completely black on mobile. can still select text

### ISSUE THREAD

**Issue by canadakickass** [mozilla/pdf.js#11227]
Attach (recommended) or Link to PDF file here:
[501243.PDF](https://github.com/mozilla/pdf.js/files/3714709/501243.PDF)

Configuration:
- Web browser and its version: **Chrome on Android 77.0.3865.116**
- Operating system and its version: reproduced on Android 8.0.0 and samsung galaxy tab E
- PDF.js version: version available as demo at https://mozilla.github.io/pdf.js/ (assumed to be 2.2.228)
- Is a browser extension:

Steps to reproduce the problem:
1. drag or open the PDF from an android device into the demo version available at https://mozilla.github.io/pdf.js/
2. 

What is the expected behavior? (add screenshot): should load pages as seen here: 
![image](https://user-images.githubusercontent.com/2089205/66608435-8ae53b80-eb84-11e9-9c1c-29bcbef745e5.png)

What went wrong? (add screenshot): pdf js created blank pages. they turn black except for last page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by canadakickass** [comment]
> * Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Snuffleupagus** [comment]
If this is specific to a *particular* platform/browser then it's unfortunately very unlikely to be a valid/actionable bug in PDF.js library, and most likely it's e.g. a canvas-related bug in the platform/browser *itself*.

**Comment by timvandermeij** [comment]
Closing since this should be reported to Chrome upstream instead (and I think I have seen similar issues, so it looks like something regressed in Chrome).
