### ISSUE TITLE
PDF.js opens only First page of PDF in iOS devices

### ISSUE THREAD

**Issue by manikandanmk3** [mozilla/pdf.js#11229]
Configuration:
- Web browser and its version: All Browsers in iOS devices
- Operating system and its version: Latest iOS
- PDF.js version: 2.2.228 
- Is a browser extension: No

Steps to reproduce the problem:
1.  We are hosting lots of PDF's in our application through Content Management System and when user clicks any PDF in any browser we opens the PDF to user via pdf.js 
 
2. But we have a new problem now only specific ti iOS devices (Apple Mac, Ipad, Iphone) the user is seeing only the First page of PDF and the remaining page is not loading. For Windows desktop or Android phones we are not seeing any issues...
      We were using the older version of pdf.js but we upgraded to 2.2.228 to later version but even then it is not fixing the issue.

What is the expected behavior? Expected behavior is iOS devices PDF should open all the pages... 

Please help in identifying and fixing the issue at the earliest..

**Comment by Snuffleupagus** [comment]
This is missing the `Attach (recommended) or Link to PDF file here:` part of the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, if this is specific to a *particular* platform/browser then it's unfortunately very unlikely to be a valid/actionable bug in PDF.js library, and most likely it's e.g. a `canvas`-related bug in the platform/browser *itself*.

**Comment by manikandanmk3** [comment]
Thank you for response.. 

Sorry to miss the link : 
1. Access https://www.ey.com/ul/en/accountinglink/accounting-link-home
2. It will ask valid email id to enter .. Please enter test1.test2@ey.com
3. once successfully validated, it shows "Accounting Link Successfully validated... Click here to access".. Please click on "Click Here" link...
4. That should open the PDF and it should open all the pages of PDF in iOS devices

**Comment by Snuffleupagus** [comment]
> Operating system and its version: Latest iOS
> PDF.js version: 2.2.228

Given that this issue mentions what's now an older PDF.js version, and that this apparently only applies to a *particular* platform, it seems very unlikely to be actionable/fixable in the PDF.js library itself. If it were in fact a PDF.js bug, you'd expect it to be consistently broken *everywhere* (e.g. even in desktop browser); hence I'd suggest closing this issue.
