### ISSUE TITLE
Edge: missing or broken (replaced by little boxes) text display

### ISSUE THREAD

**Issue by kleins05** [mozilla/pdf.js#11224]
I am experiencing an issue in Edge where PDF files are rendered with text missing or replaced by little boxes in yellow and white. There is no error message on the console. The problem is intermittent and occurs every 3rd to 10th time I open a file. It can be reproduced in the online demo of PDF.js.

Looking for a workaround, I accidentally discovered that this can be fixed by disabling the webworker by statically linking pdf.worker.js in the HTML as described in commit 56a8c93. This, however, then causes intermittent errors (seemingly dependent on network latency) that suggest a broken PDF, such as "Bad (uncompressed) XRef entry: 24R". The PDF, however, is not broken and can be opened eventually if you reopen it a few times.

I am aware this might be hard or impossible to fix in pdf.js. Since this is a relevant issue in our application that needs to be fixed somehow, I would be happy to at least receive pointers as to where to look for a workaround. Thanks a lot for any help!

Attach (recommended) or Link to PDF file here:
This can be reproduced using the [test file](https://github.com/mozilla/pdf.js/files/2988520/test.file.pdf) of #10658.

Configuration:
- Web browser and its version: Edge 44.17763.771.0
- Operating system and its version: Windows 10
- PDF.js version: 2.4.21 (demo at https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open [test file](https://github.com/mozilla/pdf.js/files/2988520/test.file.pdf) in https://mozilla.github.io/pdf.js/web/viewer.html
2. If the error does not occur, open another file to replace the test file and open the test file again.
3. Repeat step 2 until the error occurs, possibly 10 times or more.

What went wrong?
Broken display of text:
![screenshot](https://user-images.githubusercontent.com/20060399/66546952-6cf4e800-eb3e-11e9-99c2-cbd6b2303c37.png)

**Comment by kleins05** [comment]
I am aware of that. As I said I understand if this cannot be fixed, but I would greatly appreciate any pointers as to where to look for a workaround from people who are familiar with the inner workings of PDF.js. Edge/IE11 usage is unfortunately still significant for our users in an office context.

**Comment by CyranMS** [comment]
Would be great if someone has an idea how to work on this.

**Comment by alizeaiter** [comment]
Having the same problem on Microsoft Edge 44.18362.387.0

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.

**Comment by djimoh5** [comment]
We found a workaround...it's not ideal but is better than nothing. If you adjust the zoom level of the PDF after the page has fully rendered, the yellow/white boxes will disappear, and the text will render correctly. So what we do is immediately after the page renders, we set the zoom level to .99, and then within a setTimeout, set it back to 100.

**Comment by kleins05** [comment]
Thanks, dijmoh5. That was helpful.

Experimenting with your workaround it noticed that the same holds true, if I just resize the browser window a little. So it seems that something goes wrong when rendering pages on first load and gets fixed upon a refresh. Therefore it is not necessary to fiddle around with the zoom level. The same can be achieved by simply updating the PageView.

Here's some code that works with the recent beta 2.4.456:
```
PDFViewerApplication.initializedPromise.then(function() {
    if (window.navigator.userAgent.indexOf("Edge") != -1) {
      PDFViewerApplication.eventBus.on("pagerendered", function onrender(e) {
        window.setTimeout(function() {
          const pages = PDFViewerApplication.pdfViewer._pages;
          for (let i = pages.length; i--; ) {
            // update all pages that have started rendering or are already rendered
            // for pages with delayed rendering there seems to be no issue
            if (pages[i].renderingState != 0) {
              pages[i].update();
            }
          }
        }, 1);

        PDFViewerApplication.eventBus.off("pagerendered", onrender);
      });
    }
});

```
