### ISSUE TITLE
Unable to scoll in pdf js viewer using arrow keys

### ISSUE THREAD

**Issue by vigneshvenkatesh** [mozilla/pdf.js#11221]
Link to PDF file here: https://freeformbuilder.000webhostapp.com/pdf/pdf.pdf

Configuration:
- Web browser and its version: Not working across all browsers and OS
- PDF.js version: 2.2.228

Link to a viewer - https://freeformbuilder.000webhostapp.com/pdf/viewer.html

Is it possible to scroll using javascript or pdf viewer scroll options?

**Comment by timvandermeij** [comment]
The link is not working. Other than that, in the viewer there is the `scrollIntoView` helper function, but you can also do scrolling with JavaScript.
