### ISSUE TITLE
Latest version of PDF.js breaks the getviewport

### ISSUE THREAD

**Issue by anuneha7** [mozilla/pdf.js#11236]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge
- Operating system and its version: Windows
- PDF.js version: Latest reading from //mozilla.github.io/pdf.js/build/pdf.js
- Is a browser extension:

Steps to reproduce the problem:
1. I have implemented the PDF viewer from the following sample with zoom functionality.
http://next.plnkr.co/edit/XQBGOhdzkX3zQ86Y?preview
2. The code is no longer rendering my PDF and gives following error:
PDFPageProxy.getViewport is called with obsolete arguments. in api.js file.

My production code is broken and need urgent help or how can I be backward compatible.

What is the expected behavior? (add screenshot) - PDF should render

What went wrong? (add screenshot) Throwing this error:
PDFPageProxy.getViewport is called with obsolete arguments.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I have implemented the PDF viewer from the following sample with zoom functionality.
> http://next.plnkr.co/edit/XQBGOhdzkX3zQ86Y?preview

That's not an official example; please find official examples at https://mozilla.github.io/pdf.js/examples/ and https://github.com/mozilla/pdf.js/tree/master/examples/ instead.

> The code is no longer rendering my PDF and gives following error:
> PDFPageProxy.getViewport is called with obsolete arguments. in api.js file.

Note that the old format has been deprecated for no less than *three* releases, with warnings printed, before being completely removed.

**Comment by timvandermeij** [comment]
Closing since the above is completely accurate. You should only be using official releases.
