### ISSUE TITLE
Font SimSun is not available

### ISSUE THREAD

**Issue by mountainsofredleaves** [mozilla/pdf.js#11233]
I used cmaps https://unpkg.com/pdfjs-dist/

google chrome console:
**Warning: Error during font loading: Font SimSun is not available**
I want to know how to generate SimSun.bcmap file through Windows`s *.ttf or *.ttc font file；

**Comment by Snuffleupagus** [comment]
When opening an issue you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, as-is this issue will be closed as INCOMPLETE since there's no actionable information provided.

**Comment by timvandermeij** [comment]
The `.bcmap` files are generated from CMap files using the tools from https://github.com/mozilla/pdf.js/tree/master/external/cmapscompress. The CMap files we use originate from Adobe, so we don't know how they are generated exactly. This is Adobe's repository: https://github.com/adobe-type-tools/cmap-resources; I would recommend to ask there for more information.

**Comment by mountainsofredleaves** [comment]
Thank you for response..

Sorry to miss the info：

Comments do not support uploading attachments in issue, so send this email。
This pdf attachment can reproduce the problem.
you provide the Adobe's repository，i not find simsun.bacmp file，i think pdf.js framework's  cmaps Folder directory ，it‘s all .cmap files exclude font simsun。
