### ISSUE TITLE
Majority of Document is Cut Off

### ISSUE THREAD

**Issue by nkizz** [mozilla/pdf.js#11230]
Attach (recommended) or Link to PDF file here: 
[Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf](https://github.com/mozilla/pdf.js/files/3717821/Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf)

Configuration:
- Web browser and its version: Google Chrome 77.0.3865.120
- Operating system and its version: Windows 10 1903 (Build 18362.418)
- PDF.js version: 2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open attached document
2. Scroll to bottom

What is the expected behavior?
In all other PDF readers, such as the one in Microsoft Edge, 139 pages are rendered
![image](https://user-images.githubusercontent.com/12008806/66656113-5e283700-ec0b-11e9-9a31-0502331338ee.png)

What went wrong? (add screenshot)
Only 15 pages are rendered
![image](https://user-images.githubusercontent.com/12008806/66656079-4b156700-ec0b-11e9-8bda-149b2ec3b4ce.png)

JS Console Messages:
```
pdf.worker.js:1710 Warning: Indexing all PDF objects
viewer.js:1502 PDF d216c1e858407c419356a28ea6096b93 [1.6 Acrobat Distiller 7.0 (Windows) / PScript5.dll Version 5.2] (PDF.js: 2.3.164 [WebGL])
pdf.worker.js:1710 Warning: Invalid absolute docBaseUrl: "file:///C:/Users/nkizz/Desktop/Textbooks/Y._Tsividis_A_First_Lab_in_Circuits_and_Electronics.pdf".
```

**Comment by Snuffleupagus** [comment]
Unfortunately this PDF file is *corrupt*, i.e. it appears to be edited such that it consists of multiple PDF documents internally, which is indicated by the `Warning: Indexing all PDF objects` console message.
