### ISSUE TITLE
pdf.js does not update document when file-content changes

### ISSUE THREAD

**Issue by astier** [mozilla/pdf.js#11240]
### configuration

- Mozilla Firefox 69.0.3
- Arch Linux
- PDF.js version: How can I figure this out?
- Is a browser extension: I use pdf.js in firefox

### problem

When a local pdf-file is opened via firefox then pdf.js does not update the document when the file changes.

My usecase is when I write pdf-files in latex then I like to display the file in firefox with the builtin pdf.js module. However, I need to frequently rebuild the file so the content of the file changes each time I recompile the respective latex-document. The problem is that pdf.js does not show the updated content of the file when it changes. Instead I need to manually reload the pdf.js-site by pressing F5.

### solution

When a pdf-file changes on the local computer then the viewer should also update the displayed document with the new content of the file.

**Comment by timvandermeij** [comment]
This question applies to the Firefox extension and that is now maintained upstream, so please file this issue at https://bugzilla.mozilla.org instead. Thanks.
