### ISSUE TITLE
Linux bot is down

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11248]
The Linux bot appears to be down since the newly generated preview from http://54.67.70.0:8877/65321f96da43bee/web/viewer.html is not reachable, whereas pages from the Windows bot are.

/cc @brendandahl @yurydelendik; could you check what's causing this and/or kick the bot?

**Comment by brendandahl** [comment]
The above link seems fine to me, still having issues?

**Comment by timvandermeij** [comment]
Not anymore. Yesterday none of the Linux bot's links worked anymore. Strange, but this is resolved now.
