### ISSUE TITLE
XFA-forms and e-sign are not displayed in svg rendering

### ISSUE THREAD

**Issue by Jarlio** [mozilla/pdf.js#11249]
Hello, I would be grateful if you guys could tell me if XFA-forms and e-sign are working in the svg-backend, if is not working I hope i helped you to spot this one for the feature . 

Until now I used the canvas rendering and XFA-forms and e-sign were seen just fine, but it loses its quality on mobile.  I start working with the svg-backend and quality improved greatly but XFA-forms and e-sign are not seen anymore though I commented the following from annotation.js and recompiled: 
```
if (data.fieldType === 'Sig') {
      data.fieldValue = null;
      this.setFlags(AnnotationFlag.HIDDEN);
}
```

Configuration:
- Chrome latest stable

**Comment by Snuffleupagus** [comment]
As mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends, the SVG back-end isn't officially supported.

**Comment by timvandermeij** [comment]
The SVG back-end doesn't have support for annotations yet (and therefore also not for AcroForms). This is tracked in #10165 and #7613, so this can be closed as a duplicate.
