### ISSUE TITLE
forms pdf libre office not working

### ISSUE THREAD

**Issue by djpco** [mozilla/pdf.js#11258]
[form1.pdf](https://github.com/mozilla/pdf.js/files/3743656/form1.pdf)

Hello, I am looking to make a pdf entry form and save it on my server after entering the information. But I can not
Thank you and good day

**Comment by timvandermeij** [comment]
Closing since this is already tracked in #7613. PDF.js only has experimental support for AcroForms and only for rendering them, not saving data.
