### ISSUE TITLE
Node Error: Bad end offset

### ISSUE THREAD

**Issue by bpetty-formfast** [mozilla/pdf.js#11254]
When reading a PDF in nodejs, saved by express' multer middleware, running in Docker I periodically get this error:

 (node:35) UnhandledPromiseRejectionWarning: Error: Bad end offset: 4096
     at ChunkedStream.onReceiveData (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:11612:15)
     at ChunkedStreamManager.onReceiveData (/usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:12134:21)
     at /usr/src/app/node_modules/pdfjs-dist/build/pdf.worker.js:11918:15
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Configuration:
- NodeJS 12.10
- Operating system and its version: Window 10 host, with a node:alpine image
- PDF.js version: pdfjs-dist 2.1.266 (through npm)

Steps to reproduce the problem:
1. Running pdfjs-dist inside of a Linux docker container, on windows, in a nodejs/express endpoint, being served a file through multer
2. I make calls to getDocument, getPage, and getAnnotations and return back formatted results.

What went wrong? (add screenshot)
All of my promises have catches, and I have everything surrounded by a catch block.  This appears to be something internal to PDFJS.  Sometimes everything hangs and I get no error at all.  The same pdf is used over and over.  Basically I expose my endpoint through swagger-ui to hit it repeatedly to produce this issue.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Yes, without a clear way to reproduce this it's impossible to tell what's causing this unfortunately.

**Comment by bpetty-formfast** [comment]
Thanks guys, I have tracked it down.  It turns out that there is a problem transferring the file with either docker or express/multer, so pdfjs isn't getting the entire file.  Since figuring that out, I have really only seen empty files, which pdfjs is handling.  I assume that before I was getting some partial PDF that was causing pdfjs to freak out.  If I can get my hands on an example pdf, I will submit it, but it is low priority right now.  Thanks again.
