### ISSUE TITLE
How to set Paper Size on print?

### ISSUE THREAD

**Issue by krygelv** [mozilla/pdf.js#11251]
I have PDF:
[PDF.pdf](https://github.com/mozilla/pdf.js/files/3733976/PDF.pdf)

which has dimensions of A4 paper:
![image](https://user-images.githubusercontent.com/26592389/66914569-5f949d80-f017-11e9-97ec-40bb85797336.png)

but on print, paper size is set to letter
![image](https://user-images.githubusercontent.com/26592389/66914468-24926a00-f017-11e9-939b-fe9f4ab2e2a3.png)

So Is there a way to set Paper size in code before print?

Thanks

**Comment by Snuffleupagus** [comment]
> So Is there a way to set Paper size in code before print?

No, since JavaScript doesn't have any way of directly influencing printer settings of the browser/system. Hence you'll unfortunately need to specify such things manually at print time.

**Comment by krygelv** [comment]
Thank you for you answer
