### ISSUE TITLE
Iframe doesn't display on ipad

### ISSUE THREAD

**Issue by ajess33** [mozilla/pdf.js#11267]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 77
- Operating system and its version: iOS 12
- PDF.js version: 2.3.1
- Is a browser extension: no

Steps to reproduce the problem:
1. View the iframe on IPad
2.

What is the expected behavior? (add screenshot)
On desktop, the iframe displays and shows the toolbar and the various buttons included in that, which is what I would like to happen when viewing it on an IPad as well

What went wrong? (add screenshot)
When I view the page in Chrome or Safari on IPad the only thing that shows up is a part of the pdf but it looks it is displayed as an image because there is no toolbar anymore.

There are no errors in the IPad console either.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

This was the article that I followed in order to achieve this: https://pspdfkit.com/blog/2018/render-pdfs-in-the-browser-with-pdf-js/

**Comment by Snuffleupagus** [comment]
> When I view the page in Chrome or Safari on IPad

If this is specific to a *particular* platform/browser, it's unlikely to be a bug in the PDF.js library and more likely to be e.g. a canvas-bug in the platform/browser *itself*.

> This was the article that I followed in order to achieve this: https://pspdfkit.com/blog/2018/render-pdfs-in-the-browser-with-pdf-js/

That website is in *no way* associated with the PDF.js project, and as such we cannot provide support for it.

Furthermore, since they only seem interested in selling their own PDF viewing software, it's entirely likely that they're not providing good PDF.js instructions either.

**Comment by ajess33** [comment]
> > When I view the page in Chrome or Safari on IPad
> 
> If this is specific to a _particular_ platform/browser, it's unlikely to be a bug in the PDF.js library and more likely to be e.g. a canvas-bug in the platform/browser _itself_.
> 
> > This was the article that I followed in order to achieve this: https://pspdfkit.com/blog/2018/render-pdfs-in-the-browser-with-pdf-js/
> 
> That website is in _no way_ associated with the PDF.js project, and as such we cannot provide support for it.
> 
> Furthermore, since they only seem interested in selling their own PDF viewing software, it's entirely likely that they're not providing good PDF.js instructions either.

Thanks a lot for the reply! That makes a lot of sense. I did end up using google drive viewer to view the pdf on ipad and that seems to be working
