### ISSUE TITLE
use pdf.js by file data

### ISSUE THREAD

**Issue by wuyunqiang** [mozilla/pdf.js#11266]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
get data like that:
<img width="1417" alt="屏幕快照 2019-10-21 下午8 06 41" src="https://user-images.githubusercontent.com/13480948/67203855-ba2a6100-f43e-11e9-940f-6edcd0b936cf.png">

What is the expected behavior? (add screenshot)
how to normal use pdf.js

What went wrong? (add screenshot)
loading bad

**Comment by timvandermeij** [comment]
You should check the various examples at https://github.com/mozilla/pdf.js/tree/master/examples. The `getDocument` API support various types of input. Closing since this is answered and no actionable information is provided.
