### ISSUE TITLE
Displaying PDF inverted

### ISSUE THREAD

**Issue by andyalmeida** [mozilla/pdf.js#11277]
**Configuration:**
- Web browser and its version: Webview component inside Xamarin.Droid
- Operating system and its version: Android
- PDF.js version:  2.2.228

**Steps to reproduce the problem:**
With the implementation we made (leitor.js) and always using the same PDF file, randomly in PDF preview sometimes opens correctly and sometimes the PDF is displayed vertically and horizontally inverted.

**What is the expected behavior? (add screenshot)**
Always open the .pdf file in the horizontal / vertical position correctly.

![WhatsApp Image 2019-10-24 at 15 55 56](https://user-images.githubusercontent.com/1422971/67517516-242e4a80-f679-11e9-8ba8-2911e4a2d088.jpeg)

**What went wrong? (add screenshot)**
The PDF file is being opened upside down on its horizontal and vertical axis.

 
![WhatsApp Image 2019-10-24 at 15 55 57](https://user-images.githubusercontent.com/1422971/67517528-28f2fe80-f679-11e9-9f6b-374efa254037.jpeg)

**Link to the code:** [https://gist.github.com/andyalmeida/95204b703bd1aea4686143a482377e75](https://gist.github.com/andyalmeida/95204b703bd1aea4686143a482377e75)

**Comment by timvandermeij** [comment]
You can check if there are warnings/errors in the console, because usually something is printed if this occurs. It looks like either an upstream issue (#5273) or a usage issue (#10521).

**Comment by andyalmeida** [comment]
Using the library to render one page at a time as the Previous/Next example, this error occurs. I really couldn't notice nothing wrong with the implementation.

I've changed to display the whole file with an scroll, and it's displaying correctly now.

**Comment by timvandermeij** [comment]
Looking at this again I think the problem is that you're getting a canvas/context only once and reuse it to render the next page. That's not intended; you should use a new canvas for every page. See also https://github.com/mozilla/pdf.js/issues/9430#issuecomment-362541750.
