### ISSUE TITLE
Compatibility with Multi-Highlight browser extensions

### ISSUE THREAD

**Issue by alexherdt** [mozilla/pdf.js#11278]
**Short:**
The [browser extension for Google Chrome](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=de) is not able to highlight keywords with the [Multi Highlight browser extension](https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji?hl=de). **But the [official demo site](https://mozilla.github.io/pdf.js/web/viewer.html) from PDF.js is able to do that.**
It would be an extremely helpful feature!

**Links:**
[Official demo file / site](https://mozilla.github.io/pdf.js/web/viewer.html) (you do not need to install extension)
[Same Demo file on another server](http://graphytastiq.com/GitHub%20PDF/compressed.tracemonkey-pldi-09.pdf) (you do need to install extension)

**Configuration:**
- Web browser and its version: Google Chrome Version 77.0.3865.120 (official build) (64-Bit)
- Operating system and its version: Windows 10 1903
- PDF.js version: 2.3.164
- Is a browser extension: [PDF Viewer 2.3.164](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=de) AND [Multi-highlight 1.20](https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji?hl=de)

**Steps to reproduce the problem:**
1. Install Multi-Highlight browser extension and open the PDF-js. demo file here "https://mozilla.github.io/pdf.js/web/viewer.html". On this demo site (without having the PDF viewer installed, you can highlight multiple keywords with the Multi-highlight browser extension for Chrome.
2. But if you install the PDF viewer as an extension in Chrome and open the same PDF in it from your local storage or any other PDF on the web then the Multi Highlighter extension does not work

**What is the expected behavior?** 
![expected behavior](https://user-images.githubusercontent.com/57000508/67565636-2dc1bc00-f726-11e9-8efb-7e8449f63286.png)

**What went wrong?**
![what went wrong](https://user-images.githubusercontent.com/57000508/67565635-2dc1bc00-f726-11e9-88b4-2e65e1acaa3f.png)

**Comment by Snuffleupagus** [comment]
Unless I'm mistaken here, for security reasons different Chrome extensions cannot directly interact with each other in the way required for this to work. /cc @Rob--W 

> On this demo site (without having the PDF viewer installed, you can highlight multiple keywords with the Multi-highlight browser extension for Chrome.

That's expected, since this is just a "normal" web-site.

**Comment by Rob--W** [comment]
This is somewhat expected, because the PDF is shown in its own extension, and Chrome does not allow extensions to run scripts in other extensions.

The only way to change this is by rendering the content in a web origin (e.g. the originally requested URL), but that is not easy. Doing so would fix this bug and https://github.com/mozilla/pdf.js/issues/6444 though.

Chrome is planning to make backwards-incompatible changes to how extensions work, so I'm not going to make any changes until their API stabilizes.

**Comment by alexherdt** [comment]
**Thank you very much for your quick and helpful answers @Rob--W  and @Snuffleupagus Snuffleupagus !**
Now I fully understand the problem. But still such a feature would be extremely cool to have in future!
So you think that developing the extension into this direction would be worth a consideration after the Chrome API has stabilized? 
Or does it not make sense in your eyes so you would never consider doing it?

**Comment by Rob--W** [comment]
> So you think that developing the extension into this direction would be worth a consideration after the Chrome API has stabilized?
> Or does it not make sense in your eyes so you would never consider doing it?

I'm not against the concept of allowing other extensions to interact with the viewer, but allowing other extensions to run arbitrary code in the viewer is a security hazard. It is difficult to get it right.

**Comment by amab8901** [comment]
I have a PDF i would like to feed into the Multi-Highlight extension. There has to be a way to do it. Is there any way for me to take the PDF content and somehow render it in a format that Multi-Highlight extension is capable of understanding? Perhaps you could add a feature that allows user to directly upload pdf into Multi-Highlight extension to perform the multi-highlighting in it? I know that NaturalReader extension has a feature like this, so it should be possible.

**Comment by Rob--W** [comment]
> I have a PDF i would like to feed into the Multi-Highlight extension. There has to be a way to do it. Is there any way for me to take the PDF content and somehow render it in a format that Multi-Highlight extension is capable of understanding?

You could save the PDF to your disk, visit the online demo at https://mozilla.github.io/pdf.js/web/viewer.html and select the PDF file in the file picker there. In theory this process could be automated.
