### ISSUE TITLE
how fpdi work with pdfjs for dynamic load pdf pages

### ISSUE THREAD

**Issue by chinull** [mozilla/pdf.js#11272]
when i use pdfjs，for a hundreds of pages pdf online viewer。i want use fpdi to pick a range of pages in pdf files。and i want use pdfjs in client set the location page in oriant pdf files pages。do that for a dynamic pdf load。or anyother ways to do this。

**Comment by timvandermeij** [comment]
It's really difficult to understand what you're asking here, but FPDI looks like a PHP library, so we obviously cannot provide support for that.
