### ISSUE TITLE
Build hangs during `npm install` on canvas

### ISSUE THREAD

**Issue by EugenMayer** [mozilla/pdf.js#11275]
I cannot finish running `npm install` since i always get stuck at

```
The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> canvas@2.6.0 install /pdf.js/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
```

I already tried to isolate the issue to ensure it is not a local issue by
 - using the official `node:10-jessie`
 - using the official `node:12-buster`

docker image as a bulld environment.

Right now, the reproduction should be easy

```
docker run --rm -it node:12-buster bash
git clone https://github.com/mozilla/pdf.js
cd pdf.js
git checkout v2.3.200
npm install -d --verbose
```

I tried to research but i did find partial / unrelated informations to similar issues.

**Comment by timvandermeij** [comment]
I cannot reproduce this outside of Docker. Perhaps some build dependencies are missing inside the Docker container? Can the container reach the internet (try pinging the `https` URL of the `gyp` package it tries to download)?

**Comment by EugenMayer** [comment]
I can perfectly reproduce this on my Linux box (latest manjaro) too.

Of course my container can reach the internet otherwise I could not download a single mom package before that.

We are talking about the official node docker image, you are aware? This is not something handcrafted / broken.. if that is not working on those and not on my standard arch based distro, there is something brewing up :)

**Comment by timvandermeij** [comment]
I notice that Travis CI builds suddenly fail with a similar error; see https://travis-ci.org/mozilla/pdf.js/builds/601803803#L236-L238. I think it's related to a newer version of Node.js for which no precompiled binaries are available...

**Comment by timvandermeij** [comment]
We might need to revert to Node 12 instead of Node 13 that we use now because I cannot find precompiled binaries and we don't have the required build dependencies in the Travis CI setup/Docker containers, nor do I think we want to. We'll have to check if that solves the issue for now.

**Comment by EugenMayer** [comment]
Since I tested with node10 and node12 I assume that is not the issue, or are you referring to node < 10 ?

**Comment by timvandermeij** [comment]
The prebuilt canvas packages are available now and the Travis CI builds succeed again. Could you try again to see if it helped?

**Comment by Snuffleupagus** [comment]
> The prebuilt canvas packages are available now and the Travis CI builds succeed again. Could you try again to see if it helped?

@timvandermeij Given that there's been no further Travis-failures related to this, and that there's also been no further comments here, should this issue just be closed now?
