### ISSUE TITLE
difference between pdfjs-dist and the minified build

### ISSUE THREAD

**Issue by EugenMayer** [mozilla/pdf.js#11274]
We used to use the `minified` gulp based build and i tried to onboard on the `pdfjs-dist` variant.

Apperently the dist variant misses

 - locale
 - viewer.html
 - viewer.css

and is fairly different named and structured. The latter is not an issue of itself, i would just need to remap, but the former is suprising - because those are not packaged differently - they are not included.

I see that even in the docs using the pdfjs-dist distribution, viewer.html is referenced: https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#from-examples

Did i miss the topic in the docs somehow or could someone please help out explaining this or how to go about this. Thank you!

**Comment by Snuffleupagus** [comment]
Please note that `pdfjs-dist` is purposely not including the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) files, as either minified or "regular" code, please note e.g. https://mozilla.github.io/pdf.js/getting_started/:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

**Comment by EugenMayer** [comment]
so i cannot use pdfjs-dist then. Since in my case i building and publishing on a private nexus including some patches ( which i merge upstream ) the unfitting package layout is not a lot of trouble to me.

On the other hand, it is a little clunky to actually build a dist package in general

```
./node_modules/.bin/gulp dist-pre
export VERSION=2.3.200-1
cat build/dist/package.json | jq ".version=\"$VERSION\"" | jq '.name="@company/pdfjs-dist"' |sponge build/dist/package.json
rm -fr build/dist/web
rm -fr build/dist/build/
rm -fr build/dist/lib
rm -fr build/dist/cmaps
rm -fr build/dist/image_decoders
cp -fr build/minified/* build/dist
rm -fr build/dist/image_decoders
npm publish build/dist --registry https://myrepo/npm
```

if you ignore the folder copy part which is basically "customizing", using `dist-pre` is not very obvious i guess. `dist` want's to do some git operations right away on your public repo, which is obvisouly not desired.

Beside my question is answered thank you, i really would love to see PDFjs to be a little more repackage-friendly since IMHO consuming it right now can become a little (too) complex.

Thanks anyway!
