### ISSUE TITLE
How can the viewer support scale when embedded in an iframe?

### ISSUE THREAD

**Issue by iMinder** [mozilla/pdf.js#11276]
I embed the viewer of PDFjs in an iframe and it works OK. The only problem is that I can not scale the viewer.

**Comment by timvandermeij** [comment]
Closing since none of the requested information from the issue template is provided. In particular, we cannot do anything without a runnable example online. The viewer should be zoomable/scalable within an iframe, so this is most likely an integration/browser-specific issue.
