### ISSUE TITLE
Draw rectangle in canvas with loaded pdf file using pdf.js

### ISSUE THREAD

**Issue by sharmavikram** [mozilla/pdf.js#11285]
I am trying to draw rectangle over a pdf file. when i draw rectangle in pdf, rectangle not draw properly.

I want to draw only one rectangle at a time, when i draw new rectangle the old rectangle should be remove, but it is not happening.

Here is my code:-

**Rendering code of pdf (Rendering is working properly)**

```
function pdfFile (file) {
   pdfjsLib.workerSrc = 'pdf.worker.js';
   pdfjsLib.getDocument(file).promise.then(function(pdfDoc) {
   pdf = pdfDoc;
   document.getElementById('page_count').textContent = pdfDoc.numPages;
   showButtonGroup(pdf);
   renderPage(pageNum);
  });
} 

 function renderPage(num) {
      pageRendering = true;
      pdf.getPage(num).then(function(page) {
      var viewport = page.getViewport({scale: scale});
      canvas.height = viewport.height;
      canvas.width = viewport.width;
      var renderContext = {
        canvasContext: ctx,
        viewport: viewport
      };
      var renderTask = page.render(renderContext);
      renderTask.promise.then(function() {
          pageRendering = false;
           if (pageNumPending !== null) {
            renderPage(pageNumPending);
            pageNumPending = null;
          }
       });
    });

   document.getElementById('page_num').textContent = num;
```
**Mouse move function not working properly**

```
function mouseMove(e) {
        if (drag) {
            ctx.clearRect(rect.startX, rect.startY, rect.w, rect.h);
            ctx.putImageData(pdfPages[pageNum], 0, 0);
            rect.w = ((e.pageX - x) - this.offsetLeft) - rect.startX;
            rect.h = ((e.pageY - y) - this.offsetTop) - rect.startY;      
            ctx.strokeStyle = color;
            ctx.strokeRect(rect.startX, rect.startY, rect.w, rect.h);
            Object.assign(data, {
                x: rect.startX,
                y: rect.startY,
                w: rect.w,
                h: rect.h
            })
            console.log(data);
        }
    }
```
**Note**
1. When i enable clearRect and putImageData function then rectangle draw properly but canvas pdf shows empty. Here is the attached image
![screenshot-127 0 0 1_5500-2019 10 29-09_03_15](https://user-images.githubusercontent.com/8896308/67735871-809fba00-fa2b-11e9-8e52-710f452b36c6.png)

2. When only enabled clearRect function then showing multiple rectangle in pdf. Here is the attached image
![screenshot-127 0 0 1_5500-2019 10 28-17_32_57](https://user-images.githubusercontent.com/8896308/67735967-c2306500-fa2b-11e9-832c-a8c02adec639.png)

Thanks,
Vikram

**Comment by timvandermeij** [comment]
It looks like the PDF.js functionality is working since the file renders. Drawing additional items on top of the canvas is not something we can support unfortunately, so we cannot help to debug this. Moreover, this issue tracker is mainly for reporting problems within the library, not for custom implementation questions.

**Comment by sharmavikram** [comment]
@timvandermeij  thank you for your reply and i have fixed the issue.

**Comment by RaviKumarNatrajan** [comment]
> @timvandermeij thank you for your reply and i have fixed the issue.

I stuck with the same issue please help me out!!
Thanks

**Comment by cygniv404** [comment]
@timvandermeij @timvandermeij - I am facing this issue also. Any suggestions?

**Comment by vipulwairagade** [comment]
@sharmavikram Hi, I am trying to draw a rectangle over pdf rendered by pdf.js. Can you please share something on it. I am bit stuck there. I will be grateful.
Thanks in advance.

**Comment by ElakiyaS** [comment]
clearrect wont work here. You need to make the rectangle as a element to remove it. 

 var element = window.document.createElement("div");
    element.className = "rectangle";

Create a element, style it on top of the rectangle. Give a class name.

    element.style.left = "50px";
    element.style.top = "460px";
    element.style.width = "281px"; 
    element.style.height = "69px";
    container.appendChild(element);
    element.style.position = "absolute";
    element.style.backgroundColor = "rgba(243, 247, 9, 0.7)";

this will fill the rectangle. once all done, remove all the rectangle class from DOM.
container.querySelectorAll(".rectangle").forEach(function (a) {
      a.remove();
    });

**Comment by dev-priyanka-3** [comment]
@timvandermeij could you please share the solution that you have applied to fix this issue

**Comment by sharmavikram** [comment]
@dev-priyanka-3 Here is solution link
https://stackoverflow.com/questions/58590845/draw-rectangle-in-canvas-with-loaded-pdf-file-using-pdf-js

**Comment by dev-priyanka-3** [comment]
Thank you @sharmavikram , it worked!!
