### ISSUE TITLE
First and Third Page Blank - Foxit Loads PDF Properly

### ISSUE THREAD

**Issue by speedplane** [mozilla/pdf.js#11287]
Attach PDF file here: [FLEXSTEEL PIPELINE TECHNOLOGIES INC vs. FEDON, DARREN LOUIS, 201834640, No. 80265332 (Texas State, Harris County, 113th District Court Jun. 7, 2018).pdf](https://github.com/mozilla/pdf.js/files/3786520/FLEXSTEEL.PIPELINE.TECHNOLOGIES.INC.vs.FEDON.DARREN.LOUIS.201834640.No.80265332.Texas.State.Harris.County.113th.District.Court.Jun.7.2018.pdf)

Configuration:
- Web browser and its version: Chrome 77
- Operating system and its version: Windows
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No, used demo

Steps to reproduce the problem:
1. Load the PDF

What is the expected behavior?
Foxit loads the first and third pages just fine.
![image](https://user-images.githubusercontent.com/671052/67821667-2c7cf000-fa94-11e9-86d9-a063d4f23f0b.png)

What went wrong? 
The first and third page of the PDF JS viewer is blank. I am willing to bet this PDF is corrupted in some way, but given that Foxit loads it fine, I would expect pdf.js to do the same.

**Comment by speedplane** [comment]
Also note the following debug output:
```
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.4.88)
app.js:1111 PDF 38e80603b6dab5e99417b4a1ba05a66e [1.3 PyPDF2 / -] (PDF.js: 2.4.88)
util.js:329 Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "FormatError: unrecognized colorspace CS0".
util.js:329 Warning: getOperatorList - ignoring errors during "GetOperatorList: page 2" task: "FormatError: unrecognized colorspace CS0".
```

**Comment by Snuffleupagus** [comment]
> The first and third page of the PDF JS viewer is blank.

This can be reproduced in Adobe Reader (i.e. the PDF reference implementation) as well, which is usually a very good indication that PDF document is severely corrupt.

Looking very briefly at the PDF document, it's indeed corrupt since the `/Resources` dictionary contains the following nonsensical entry:
```
/ColorSpace <<
/CS0 null
>>
```

**Comment by speedplane** [comment]
Thank you for fixing!
