### ISSUE TITLE
Why use img tag when printing

### ISSUE THREAD

**Issue by sunzongzheng** [mozilla/pdf.js#11293]
https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/web/pdf_print_service.js#L155-L177

I have got the canvas, why not directly use it?

I tried to use canvas directly. But I met some problems, the content of one page cannot fill up when printing.
![image](https://user-images.githubusercontent.com/12635613/67932268-800b4d00-fbfe-11e9-93a5-2a3730614cfb.png)

Here is my test repo: https://github.com/sunzongzheng/pdf.js 
Here is my commit: https://github.com/sunzongzheng/pdf.js/commit/f956a11ffb33cb90d86b3bb9bf5ccf1c100e25b5

I set the background color to let it be obvious when it cannot fill up. And I use the canvas directly.

**Comment by Snuffleupagus** [comment]
> I have got the canvas, why not directly use it?

Because browsers generally, with the exception of the Firefox-specific `mozPrintCallback`, don't support printing canvases. This is a limitation of the web platform itself, and *not* the PDF.js library.
