### ISSUE TITLE
prepare the file name in advance

### ISSUE THREAD

**Issue by dasoncheng** [mozilla/pdf.js#11291]
# Question

## Description

After using this tool([pdfkit](https://github.com/foliojs/pdfkit)) in the browser to generate PDF document, and then using Mozilla's pdf.js preview file, the file name defaults to document.pdf. How to prepare the file name in advance?
     
## Your environment

* PDF.js version: the viewer
* pdfkit version: 0.10.0
* Node version: v12.10.0
* Browser version (if applicable): firefox 69.0.1 (64-bit)
* Operating System: macOS 10.14.6

**Comment by timvandermeij** [comment]
The filename is mainly determined from the URL. Please see https://github.com/mozilla/pdf.js/blob/269168d05353e53fde81640e3198c8c303071cd6/test/unit/ui_utils_spec.js#L54-L185 for the various options you have for providing this. If PDF.js cannot find the filename, it defaults to `document.pdf`. Alternatively, I think you can pass the filename using the `Content-Disposition` header; see https://github.com/mozilla/pdf.js/blob/c5d837d2fe55e02a8152378c7a0662c30aaa7e37/src/display/network_utils.js#L60-L74.
