### ISSUE TITLE
PDF Annotations made in iOS do not render properly

### ISSUE THREAD

**Issue by mxiao6** [mozilla/pdf.js#11306]
Attach (recommended) or Link to PDF file here: 
[2018 Wrapped.pdf](https://github.com/mozilla/pdf.js/files/3806127/2018.Wrapped.pdf)

Configuration:
- Web browser and its version: Chrome 78.0.3904.70 (Official Build) (64-bit)
- Operating system and its version: MacOS 10.14.6 
- PDF.js version: v2.2.228 and the latest version in PDF.js demo (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Annotate PDF on iOS
2. Open it with PDF.js (https://mozilla.github.io/pdf.js/web/viewer.html)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/17711683/68159230-36747800-ff06-11e9-99ca-a4746d780cf1.png)

What went wrong? (add screenshot)
![image (1)](https://user-images.githubusercontent.com/17711683/68159239-3bd1c280-ff06-11e9-855e-d914eeac7d20.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
I also have this problem with the most recent development viewer. The first page only contains `Link` annotations, which render fine, and a `Square` annotation with an image in the appearance stream. The latter is rendered incorrectly like this, presumably because of the warning `Warning: Unsupported header type 1667523942 (cdef)` in the console.

**Comment by bkirkby** [comment]
here is another document with the problem image conversion from macos. our support team thinks they narrowed it down to the creation of the annotations being on iOS 13 with it's Markup tool.

[iOS+Mark+Ups2.pdf](https://github.com/mozilla/pdf.js/files/3913005/iOS%2BMark%2BUps2.pdf)
