### ISSUE TITLE
Extra spaces rendered

### ISSUE THREAD

**Issue by romulodiniz** [mozilla/pdf.js#11324]
Hello,
my app is rendering a pdf with some extra spaces on many lines. While visually it's not a very big deal, it's breaking the search + highlight function, which is working perfectly when the lines are rendered without extra spaces.

Any idea how could I fix at least the search? I'm using version pdfjs-dist-1.10.100.

Thanks in advance.

**Comment by Snuffleupagus** [comment]
You need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, as-is there's simply no actionable information here.
Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> I'm using version pdfjs-dist-1.10.100.

That version is too old to be supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases
