### ISSUE TITLE
Using PDF.js some parts of a PDF file cannot be rendered when displaying in Firefox.

### ISSUE THREAD

**Issue by saisenwest** [mozilla/pdf.js#11322]
Using PDF.js in our applications we run into the problem that some parts of a PDF file cannot be rendered when displaying them in other browsers then Google Chrome.

１．PDF
[Book.pdf](https://github.com/mozilla/pdf.js/files/3835667/Book.pdf)

２．Version
　PDF.js：v2.2.228
　Chrome：78.0.3904.97　64bit
　Firefox：70.0.1　64bit
　IE：11.418.18362.0
　Operating system：Windows10 Pro

３．The behavior at several browsers.
(1) Chrome
    The rendering takes time, but the PDF displayed correctly.
![Chrome_2](https://user-images.githubusercontent.com/57391359/68664727-24d54500-0584-11ea-9280-04eeb02ad240.png)

(2) FireFox
    Compared to above (1) the part surrounded by the red frame will not be displayed.
![FireFox_2](https://user-images.githubusercontent.com/57391359/68664765-39194200-0584-11ea-9c7a-bbf2ed86862b.png)

(3) IE
    Displaying a PDF file results in an “Index Size Error” and the rendering fails.
![IE_2](https://user-images.githubusercontent.com/57391359/68664812-49c9b800-0584-11ea-814e-b6e161cb90b3.png)

４．Steps to reproduce the problem
(1) Please download the file of above 1. PDF.
(2) Open it with PDF.js (https://mozilla.github.io/pdf.js/web/viewer.html)

Does anyone have an idea what the cause of the phenomenon described at above 3. (2) (3) could be?

Furthermore, could anyone tell us if there are any information about how to solve the above phenomenon?

We checked out the following problem, but the above phenomenon could not be avoided.
https://github.com/mozilla/pdf.js/issues/7825

**Comment by timvandermeij** [comment]
This file works for me in Firefox 70.0.1 (64-bit, Linux). Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html to see if the problem remains?

It looks like the header is composed of many small operations, judging by the rather large and repetitive flate stream, which may be too heavy for at least IE11 (for which support is limited by the way, see the FAQ).

**Comment by saisenwest** [comment]
Thank you for your quick reply. As you said, this file worked with Firefox 70.0 .1 (64-bit, Linux).
However, as shown in the question, Firefox 70.0. 1 (64-bit, Windows) does not display the part surrounded by the red frame. What are possible causes for this?

As you pointed out, the file size is large. We would like to try the web document optimization referenced at the following URL.
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize

**Comment by THausherr** [comment]
The image at Root/Pages/Kids/[0]/Resources/XObject/Im0 is huge (2787 x 17776). Could this be the "big images" problem?

**Comment by saisenwest** [comment]
Thank you for your comment.

As you said, the image is big. We will recreate the PDF and check the phenomenon again.

**Comment by THausherr** [comment]
I recommend to use a dot pattern "color" if you really want dots. If you want grey, then use grey color. Smaller file size means a better user experience because the PDF will appear faster.

**Comment by saisenwest** [comment]
Thank you for your advice. After all, how to make PDF seems to be bad.
We will recreate the PDF and check the phenomenon again.
