### ISSUE TITLE
eventBus DOM integration change now raises events on Document instead of element

### ISSUE THREAD

**Issue by Jaans** [mozilla/pdf.js#11337]
Would it be possible to change the eventBus DOM integration to again raise the DOM events on the container element like before (instead of the document)?
Changed after commit: https://github.com/mozilla/pdf.js/commit/e2e9657ed06c15c2452f2686ad3fb68a3e4aba09

We updated to the latest version of pdf.js and found this change breaks our app. We use multiple PDF viewer instances simultaneously and not having events specific to the viewer element is our biggest problem.

Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: Chrome 78
- Operating system and its version: Windows 10 1903
- PDF.js version: 2.3.200 (issue sine 2.1.266)
- Is a browser extension: No

Steps to reproduce the problem:
1. Subscribe to pdf.js viewer events on DOM (e.g. "pagesinit" or "pagechanging")
2. Event listener on container element no longer fires. Requires a change to add listener on document instead, but this causes problems when multiple viewer instances are used.

What is the expected behavior? (add screenshot)
Event raised by eventBus onto DOM should target the container element particular pdf_viewer instance (like prior to the change set https://github.com/mozilla/pdf.js/commit/e2e9657ed06c15c2452f2686ad3fb68a3e4aba09 )

What went wrong? (add screenshot)
We have multiple viewer instances, but each listened to their respective container for events. Now, events from other viewers will also be received.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by timvandermeij** [comment]
Wouldn't setting `dispatchToDOM` when constructing the event bus solve this issue?

**Comment by Snuffleupagus** [comment]
> Would it be possible to change the eventBus DOM integration to again raise the DOM events on the container element like before (instead of the document)?

*Please note:* The *only* reason that the ability to dispatch `EventBus` event to the DOM wasn't just removed, was that the Firefox integration tests depends on this behaviour. (Hence the desirable end-goal would actually be to eventually try and get rid of this completely.)

One of the goals with the changes were to reduce the amount of duplicated code and the maintenance required, by not having to manually list *every* event.

> Changed after commit: e2e9657

Note that *some* events were dispatched on the `window` even before, so it's most likely that you were lucky with the particular ones that you happened to depend upon.

> Event raised by eventBus onto DOM should target the container element particular pdf_viewer instance

Unfortunately I'm not sure if there's a *generally* good way of associating *every* possible event with the correct DOM element, but please see below...

> We use multiple PDF viewer instances simultaneously

If by "PDF viewer" you're referring to the complete [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) then please note that that one is mostly written with the intention to be used standalone, or possibly embedded in an `<iframe>` (in which case I don't *think* that the global event dispatching would pose a problem).

However, if by "PDF viewer" you're referring to e.g. the `simpleviewer` example found in https://github.com/mozilla/pdf.js/tree/master/examples/components, then the correct way to deal with this would be to create your own `EventBus` instance, and then pass that to the various viewer components; see e.g. the parameters that the `PDFViewer` accepts https://github.com/mozilla/pdf.js/blob/827eb64b75f8d0c3b4203202a7cf15c7cbd2ce26/web/base_viewer.js#L33-L66
