### ISSUE TITLE
Searching issue using findcontroller

### ISSUE THREAD

**Issue by ITsolution-git** [mozilla/pdf.js#11331]
I am using PDFFindContorller to highlight text like this.

```
this.finder.executeCommand('find', {
                caseSensitive: false, 
                findPrevious: undefined,
                highlightAll: true, 
                phraseSearch: true, 
                query: text
            })
```
This is in pdf document.
![image](https://user-images.githubusercontent.com/24530559/68843703-92719600-0696-11ea-8148-d194f4ddfbce.png)

And this is my query text.
![image](https://user-images.githubusercontent.com/24530559/68843626-6eae5000-0696-11ea-9d5e-5eae3470949c.png)
`Separate prime contracts will be awarded by the Owner for other work on the Project.`

It seems like there are 2 spaces between words in pdf. 

So I cannot find my query text using FindController.

How can I use findController to highlight/search it?

Thanks

**Comment by timvandermeij** [comment]
This is not really a find controller problem, but rather a text layer problem for which we already have many open issues, so I'm closing this one as a duplicate.
