### ISSUE TITLE
Invalid PDF structure

### ISSUE THREAD

**Issue by sotocast** [mozilla/pdf.js#11330]
[9069_10755570(1).pdf](https://github.com/mozilla/pdf.js/files/3844109/9069_10755570.1.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  Open Mozilla Firefox
2. Click in Attach File

**Comment by timvandermeij** [comment]
From a quick glance this PDF file looks corrupt. There is random data before the `%PDF` marker at the beginning of the file and the XRef table looks empty. However, for example Okular is able to recover and so should we I think.

**Comment by sotocast** [comment]
> From a quick glance this PDF file looks corrupt. There is random data before the `%PDF` marker at the beginning of the file and the XRef table looks empty. However, for example Okular is able to recover and so should we I think.

Okay, the pdf file is corrupt, but Adobe Reader, the Google Chrome viewer, etc. obviate up to 1000 characters before% PDF, which allows viewing them. Could the same be done for pdf.js? This would make it much more powerful

**Comment by sotocast** [comment]
Excellent, thank you! Works fine!
