### ISSUE TITLE
Print button not working with disabled autoFetch and stream

### ISSUE THREAD

**Issue by sharan-satkhed** [mozilla/pdf.js#11339]
Attach (recommended) or Link to PDF file here:N/A

Configuration:
- Web browser and its version: Google Chrome - Version 78.0.3904.97 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.2.228
- Is a browser extension:No
**Issue exists in all the browsers**

Steps to reproduce the problem:
1. Set **disablestream** and **disableautofetch** # params to true.
2. Request PDF document through viewer.html by passing query parameters.
**Below is the sample URL :** web/viewer.html?file=http%3A%2F%2Flocalhost%3A8062%2Fhpesc%2Fapi%2Fdocument%2Fa00004882en_us#disablestream=true&disableautofetch=true

What is the expected behavior? (add screenshot)
Should able to print the PDF document.

What went wrong? (add screenshot)
After rendering intial pages as it's **disableautofetch** to true.
On clicking Print button, print not working and giving below issue in dev console.
![image](https://user-images.githubusercontent.com/42669952/69026834-941ebf00-09f2-11ea-98d6-26a0ab8faf6c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
That's hardly surprising, considering https://github.com/mozilla/pdf.js/blob/be02e679728d86709b31aebc7e89c863512af91a/web/base_viewer.js#L461

> web/viewer.html?file=http%3A%2F%2Flocalhost%3A8062%2Fhpesc%2Fapi%2Fdocument%2Fa00004882en_us#rangeChunkSize=256000&disableStream=true&disableAutoFetch=true

*For future reference:* An example pointing to `localhost` isn't useful, since it's not possible for anyone else to actually reproduce that. Furthermore, there's also no hash parameter called `rangeChunkSize`.

**Comment by sharan-satkhed** [comment]
@Snuffleupagus,
Thanks for your swift response :)

**rangeChunkSize** is our custom parameter, please ignore.

I couldn't able to show you this issue because pdfjs deployed in our non-public environment.
This issue can be reproduced by adding **disableStream=true** and **disableAutoFetch=true** hash parameters to viewer.

I tried to reproduce this issue by using https://mozilla.github.io/pdf.js/web/viewer.html but here hash prams are not accepting.

Kindly let me know if you can reproduce the issue by adding **disableStream=true** and **disableAutoFetch=true** hash parameters to viewer or else I have to find some way to show you the issue.
