### ISSUE TITLE
PDF uses mix of fonts so disableFontFace doesn't work. 

### ISSUE THREAD

**Issue by tristansokol** [mozilla/pdf.js#11347]
Hi

I am trying to convert pdf images to pngs.  As per #11311  I've rendering the pdf document, looking at the fonts, and then trying to determine if I should use `disableFontFace:true` on a per-page basis. 
```javascript
 const pdfDocument = await pdfjsLib.getDocument({data: data}).promise;
 for (let i = 1; i <= pdfDocument.numPages; i++) {
    const page = await pdfDocument.getPage(i);
    const testText = await page.getTextContent();
    if (Object.keys(testText.styles).includes('Helvetica')||Object.keys(testText.styles).includes('Times')) {
        console.log('Helvetica/Times detected, so disabling font faces');
        pdfDocument = await pdfjsLib.getDocument({data: data, disableFontFace: false}).promise;
        page = await pdfDocument.getPage(i);
    }
...
```
However, I have discovered some pdfs do not render correctly under either scenario due to what I guess is a mix of custom and default fonts. : 
![image](https://user-images.githubusercontent.com/867661/69168314-11facd00-0abc-11ea-9e8e-46c19bbe74f0.png)
![image](https://user-images.githubusercontent.com/867661/69168391-2d65d800-0abc-11ea-9b22-407f5964b715.png)

I'm using Node, and `"pdfjs-dist": "^2.2.228"`

How could I render this pdf correctly? 
Thank you.

**Comment by Snuffleupagus** [comment]
Non-embedded (default) fonts not rendering e.g. with `disableFontFace` set is already tracked in issue #4244, of which this is thus a duplicate.

**Comment by timvandermeij** [comment]
Closing in favor of that one.
