### ISSUE TITLE
Cannot display words correctly on specific pdf with Chinese characters

### ISSUE THREAD

**Issue by willbchang** [mozilla/pdf.js#11349]
I tried different PDF files with Chinese characters, this doesn't work with PDF Viewer extension, but works well in Chrome's default pdf viewer.
I've tested with https://mozilla.github.io/pdf.js/web/viewer.html which also didn't work.

Attach (recommended) or Link to PDF file here: [test.pdf.zip](https://github.com/willbchang/test/releases/download/test/test.pdf.zip)

Configuration:
- Web browser and its version: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- Operating system and its version: macOS Catalina Version 10.15.1
- PDF.js version: V2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. [Install the extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)
2. Give PDF Viewer local file access and open this file.

What is the expected behavior? (add screenshot)
The default pdf viewer in Chrome:
![Screen Shot 2019-11-21 at 12 58 01 PM](https://user-images.githubusercontent.com/14329786/69305371-b74da680-0c5e-11ea-972a-5a505c18063f.png)

What went wrong? (add screenshot)
The PDF Viewer extension
![Screen Shot 2019-11-21 at 1 18 51 PM](https://user-images.githubusercontent.com/14329786/69306202-b0746300-0c61-11ea-83f5-b30a737ce4b8.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: [test.pdf.zip](https://github.com/willbchang/test/releases/download/test/test.pdf.zip)

That file is no longer available, hence I'd suggest closing this issue since it's not actionable in its current form.

---

To re-open this issue, please directly *attach* the PDF file itself to this issue (and not as a zip-file).

**Comment by willbchang** [comment]
[谈音乐内心听觉意识培养吴燕.pdf](https://github.com/mozilla/pdf.js/files/5899884/default.pdf)

**Comment by Snuffleupagus** [comment]
WFM, with PDF.js version 2.7.510 in Firefox Nightly 86.

**Comment by Snuffleupagus** [comment]
WFM, with PDF.js version 2.7.510 in Firefox Nightly 87.

**Comment by Snuffleupagus** [comment]
WFM, with PDF.js version `2.7.510` in Firefox Nightly 86.

**Comment by timvandermeij** [comment]
Closing since this works for me as well now.
