### ISSUE TITLE
Empty space by printing when using landscape and vertical templates in the same file

### ISSUE THREAD

**Issue by GeorgeBalat** [mozilla/pdf.js#11340]
**Attach (recommended) or Link to PDF file here:**
[Test.pdf](https://github.com/mozilla/pdf.js/files/3857916/Test.pdf)

**Configuration:**
- Web browser and its version: Chrome & Firefox
- Operating system and its version: Mac & Windows

**Steps to reproduce the problem:**
1. Use a document with both page templates (landscape + vertical)
![Bildschirmfoto 2019-11-18 um 10 44 51](https://user-images.githubusercontent.com/57895385/69041835-7b150e80-09f0-11ea-93ac-f8fc6ff4a9cf.png)

2. Click "Print" in PDF.js
![Bildschirmfoto 2019-11-18 um 10 45 20](https://user-images.githubusercontent.com/57895385/69041873-8b2cee00-09f0-11ea-9863-513888928da0.png)

**What is the expected behavior? (add screenshot)**
Same PDF as in the browser

**What went wrong? (add screenshot)**
Only vertical template with empty space on the right and on the bottom
![Bildschirmfoto 2019-11-18 um 10 45 56](https://user-images.githubusercontent.com/57895385/69042026-c9c2a880-09f0-11ea-8d51-1b433b3d3a16.png)

**Comment by GeorgeBalat** [comment]
@timvandermeij any updates on when it is going to be fixed?

**Comment by Snuffleupagus** [comment]
Probably a duplicate of #9297.
