### ISSUE TITLE
PDF Rendering not properly (JavaFX + pdf.js)

### ISSUE THREAD

**Issue by YanDieg** [mozilla/pdf.js#11344]
Hi,
i am using Java (with IDE Intellij) + JavaFx. + last build of pdf.js. 
![Annotation 2019-11-19 024425](https://user-images.githubusercontent.com/26544924/69108974-8f035380-0a76-11ea-92dc-209e4c69d91d.png)
 When i try to render the pdf, the layout-rendering is wrong. As you can see. 

It is like if pdf.js make a "re-format" of my file.

**Comment by llo-dia** [comment]
Does your pdf file work in the [online demo of pdf.js](https://mozilla.github.io/pdf.js/web/viewer.html)?
According to [this FAQ entry](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), whatever JavaScript engine is used by JavaFX may not be supported by this project.
