### ISSUE TITLE
Using viewer.js and viewer.html with base64 encoded PDF

### ISSUE THREAD

**Issue by SFLinz** [mozilla/pdf.js#11369]
Is it possible to use the viewer.js and viewer.html to render base64 encoded pdfs? I dont want to display a canvas or an iframe with the path to the pdf-file, because its too unsafe. 

Your docu says:

> You can use raw binary data to open a PDF document: use Uint8Array instead of URL in the PDFViewerApplication.open call. If you have base64 encoded data, please decode it first -- not all browsers have atob or data URI scheme support. (The base64 conversion operation uses more memory, so we recommend delivering raw PDF data as typed array in first place.)

But thats not where helpful, if you are not telling the users where to get access to PDFViewerApplication. 

I call it as follows:

`   
// Content of pdfData: 'JVBERi0xLjQKJeLjz9MKJVBERi0xLjQKJeLjz9MKJVBERi0x...  '

 var BASE64_MARKER = ';base64,';
    var pdfAsArray = convertDataURIToBinary("data:application/pdf;base64, " + document.getElementById('pdfData').value);
    window.PDFViewerApplication.open(pdfAsArray);

    function convertDataURIToBinary(dataURI) {
            var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
            var base64 = dataURI.substring(base64Index);
            var raw = window.atob(base64);
            var rawLength = raw.length;
            var array = new Uint8Array(new ArrayBuffer(rawLength));

            for (i = 0; i < rawLength; i++) {
                array[i] = raw.charCodeAt(i);
            }
            return array;
       }
`
Errors i get:

1. Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at viewer.js?14.11.2019-1:1204
2. viewer.js?14.11.2019-1:1213 Uncaught (in promise) TypeError: Cannot read property 'setPagesCount' of null
    at Object.load (viewer.js?14.11.2019-1:1213)
    at viewer.js?14.11.2019-1:1030
load @ viewer.js?14.11.2019-1:1213
(anonymous) @ viewer.js?14.11.2019-1:1030
setTimeout (async)
(anonymous) @ 1:461

But viewer.js only calls problems with that pdf. 
If I console.log the pdf I get it as follows: 

{build: "d7afb74a", version: "2.2.228", getDocument: ƒ, LoopbackPort: ƒ, PDFDataRangeTransport: ƒ, …}

I get the Page-Count and the Document looks good. But your application can't handle it. Also if I pass the pdf as path-string It just shows errors. 

I like your viewer and I would love to use him for our project, but only if it can handle base64-encoded pdfs.

More Information:

I use Codeigniter. I present the viewer.html not directly. Codeigniter is loading the view. I copied the html-code of the viewer.html to my controller. It shows up correctly. All resources are loaded correctly (pdf.js, css-styles, viewer.js, etc.). 

With PHP I read the file, which is needed by the user. Then I want to display it. So it has to be dynamicly. I want to mention that Iframes, Canvas or Objects are not good for our application. Its hard to controll their responsive Design and they are unsafe too. So thats why I want to controll the view by Codeigniter. This must be possible.. What I am doing wrong?

**Comment by Snuffleupagus** [comment]
> I like your viewer and I would love to use him for our project, [...]

Please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Furthermore, this issue is missing most of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
PDF.js does support base64 inputs; see https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html. Moreover, the `open` method of `PDFViewerApplication` supports this type of input; see https://github.com/mozilla/pdf.js/blob/master/web/app.js#L609-L617. Closing as answered, also based on the comment above; just code snippet's don't really help to reproduce the issue.

**Comment by jingxinxin** [comment]
@SFLinz Hi,Here's my solution.
You can search for the string `defaultUrl`
![image](https://user-images.githubusercontent.com/6293249/74954850-b6373b80-543e-11ea-8fdf-8a8bfef691d3.png)
And replace it with `DEFAULT_URL` like this
![image](https://user-images.githubusercontent.com/6293249/74955077-10380100-543f-11ea-9c0b-fe00b127d6da.png)
Then put the following big block of code in the viewer.html file before referencing the viewer.js.
```js
<script type="text/javascript">
  var DEFAULT_URL = '';
  var pdfUrl = document.location.search.substring(1);
  if(null == pdfUrl || '' == pdfUrl){
      var BASE64_MARKER = ';base64,';
      var preFileId = '';
      var pdfAsDataUri = sessionStorage.getItem('pdfBase64');
      var pdfAsArray = convertDataURIToBinary(pdfAsDataUri);
      DEFAULT_URL = pdfAsArray;
      function convertDataURIToBinary(dataURI) {
          var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
          var newUrl = dataURI.substring(base64Index).replace(/[\n\r]/g,'');
          var raw = window.atob(newUrl);
          var rawLength = raw.length;

          var array = new Uint8Array(new ArrayBuffer(rawLength));
          for (i = 0; i < rawLength; i++) {
              array[i] = raw.charCodeAt(i) & 0xff;
          }
          return array;
      }
  }
</script>
```
Then put the base64 format code in the local sessionStorage.
```js
sessionStorage.setItem('pdfBase64',data);
```
