### ISSUE TITLE
Impossible to find font associated to an annotation

### ISSUE THREAD

**Issue by zagoa** [mozilla/pdf.js#11364]
Configuration:
- Web browser and its version: Brave 1.0.1
- Operating system and its version: Ubuntu 18.04
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. Get FreeText annotations from a document 
2. Try to loop over to extract rect 
3. convert the list of rectangle in the viewport and inject them in the TextLayer

What is the expected behavior? 
My goal is to make available the selection on annotations. I can handle the position of rectangles, but impossible to find/get through the API the font or the font-size used during the drawing.
The annotation object doesn't contain it.

My code look like something like that
```
    const page = this.pdfElement.getPageView(pageNumber - 1);
    page.annotationLayer.pdfPage.getAnnotations()
      .then(annotations => {
        annotations
          .filter(annotation => annotation.contents)
          .forEach(annotation => 
            const convertedRect = page.viewport.convertToViewportRectangle(annotation.rect)

            const htmlElement = document.createElement('span');
            htmlElement.innerText = annotation.contents;
            htmlElement.style.left = convertedRect[0] + 'px';
            htmlElement.style.top = convertedRect[1] + 'px';
            htmlElement.style.width = convertedRect[2] + 'px';
            htmlElement.style.height = convertedRect[3] + 'px';
            page.textLayer.textLayerDiv.prepend(htmlElement);
          }
          )
      })
```

There is somewhere where I can get the font and have a span in the textLayer matching the annotation text? 

Thank for your help :) 
(PS: there is a font describe in my PDF, when I open it i can find /F: 4 and it's defined)

**Comment by Snuffleupagus** [comment]
The font information for a given annotation can be found via the `defaultAppearanceData`-property, for applicable annotation types, on the annotation-data that's returned by the `PDFPageProxy.getAnnotations` method.
