### ISSUE TITLE
Annotations not shown in pdf.js web viewer

### ISSUE THREAD

**Issue by hongnk** [mozilla/pdf.js#11362]
Attached PDF doesn't show popup annotations when view in https://mozilla.github.io/pdf.js/web/viewer.html

[Risk Advice Guide-Copy2.pdf](https://github.com/mozilla/pdf.js/files/3895671/Risk.Advice.Guide-Copy2.pdf)

Configuration:
- Web browser and its version:  all browsers, tested with Chrome and Firefox latest versions.
- Operating system and its version: all OS< tested with Windows and iOS
- PDF.js version: current (online version)

Steps to reproduce the problem:
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the above file
3. Go to page 4,hover mouse over one of the checkbox

What is the expected behavior? (add screenshot)
![Annotation 2019-11-27 154335](https://user-images.githubusercontent.com/5845263/69703693-f5e6d380-112c-11ea-9cab-6baf044749ee.png)

What went wrong? (add screenshot)
The annotation did not pop up

**Comment by Senpaistorm** [comment]
After some investigation, it seems like the popup elements are created as empty containers and not linked to their triggers(checkboxes). This is the result of PopupAnnotationElement's render method returning on a null parentElement. I believe that the popup gets rendered before its parent so when it tries to select its parent null value is returned.

**Comment by hongnk** [comment]
> After some investigation, it seems like the popup elements are created as empty containers and not linked to their triggers(checkboxes). This is the result of PopupAnnotationElement's render method returning on a null parentElement. I believe that the popup gets rendered before its parent so when it tries to select its parent null value is returned.

Thanks for quick investigation. More information: the popups worked in pdf.js version 1.1:
![Annotation 2019-11-28 064550](https://user-images.githubusercontent.com/5845263/69764296-cb3b6000-11aa-11ea-8edf-d728018bed84.png)

Note: the above test file doesn't load in pdf.js 1.1, please try this one instead (it's the original file but processed to remove internal texts):
[Risk Advice Guide-Copy3.pdf](https://github.com/mozilla/pdf.js/files/3899061/Risk.Advice.Guide-Copy3.pdf)

**Comment by hongnk** [comment]
I found that the problem is due to  element order, popupElement appears before parentElement, so when the popup is rendered, the parent is not present yet.

Temporary work-around: add a setTimeout in popup rendering function to wait for parent element to exist
(source: src/display/annotation_layer.js, replace line 679 to 703):

> var self = this
> setTimeout(function() {
>   const selector = '[data-annotation-id="${self.data.parentId}"]';
>   const parentElement = self.layer.querySelector(selector);
>   //if (!parentElement) {
>   //  return self.container;
>   //}
> 
>   const popup = new PopupElement({
>     container: self.container,
>     trigger: parentElement,
>     color: self.data.color,
>     title: self.data.title,
>     modificationDate: self.data.modificationDate,
>     contents: self.data.contents,
>   });
> 
>   // Position the popup next to the parent annotation's container.
>   // PDF viewers ignore a popup annotation's rectangle.
>   const parentLeft = parseFloat(parentElement.style.left);
>   const parentWidth = parseFloat(parentElement.style.width);
>   self.container.style.transformOrigin = '-${parentLeft + parentWidth}px -${
>     parentElement.style.top
>   }';
>   self.container.style.left = `${parentLeft + parentWidth}px`;
> 
>   self.container.appendChild(popup.render());
> }, 1)

Hope the information can help speed up official fix. Thanks.
