### ISSUE TITLE
"Dots" are not rendered in macOS Safari

### ISSUE THREAD

**Issue by paulojreis** [mozilla/pdf.js#11375]
Attach (recommended) or Link to PDF file here:
[No_dots_in_built_in_viewer_MWE.pdf](https://github.com/mozilla/pdf.js/files/3911004/No_dots_in_built_in_viewer_MWE.pdf)

Configuration:
- Web browser and its version: Safari Version 13.0.3 (14608.3.10.10.1)
- Operating system and its version: macOS Mojave Version 10.14.6 (18G1012)
- PDF.js version: 2.4.163 (the one on https://mozilla.github.io/pdf.js/web/viewer.html as of today)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open Safari (Chrome and Firefox seem to work OK)
2. Go to https://mozilla.github.io/pdf.js/web/viewer.html
3. Open the attached PDF [No_dots_in_built_in_viewer_MWE.pdf](https://github.com/mozilla/pdf.js/files/3911004/No_dots_in_built_in_viewer_MWE.pdf)

What is the expected behavior? (add screenshot)

Dots are rendered (this is a Chrome screenshot)
![Screenshot 2019-12-02 at 11 33 16](https://user-images.githubusercontent.com/10046706/69956338-9d7e5000-14f7-11ea-80ea-a1483a1c974e.png)

What went wrong? (add screenshot)

Dots are not rendered in Safari (this is a Safari screenshot)

![Screenshot 2019-12-02 at 11 33 30](https://user-images.githubusercontent.com/10046706/69956371-b6870100-14f7-11ea-80a6-167b709bfdd8.png)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari Version 13.0.3 (14608.3.10.10.1)

This would suggest a `<canvas>`-related bug in browser *itself*, rather than a bug in the PDF.js library.

**Comment by Snuffleupagus** [comment]
Is it really meaningful to keep this open, when everything points to a platform/browser bug (rather than a PDF.js one), since this doesn't seem like something that can be fixed *here*?
