### ISSUE TITLE
Opening .html file?

### ISSUE THREAD

**Issue by EtashGuha** [mozilla/pdf.js#11371]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Electron v4.2.12
- Operating system and its version: Mac OS
- PDF.js version: Most Recent
- Is a browser extension: No

Steps to reproduce the problem:
Not necessarily a problem. Let's say I wanted my application to download the html file from a website and display that using PDFJS. If I have an html file, how do I use PDFJS to view it? It seems one way to do it would be to render the html as a pdf file and then display it in PDFJS, but that seems backward as PDFJS converts it into html anyways.

**Comment by timvandermeij** [comment]
PDF.js only supports loading PDF data, so HTML data is not supported in any way. If you want that, you will have to implement this yourself, but we would recommend to just serve the PDF data.
