### ISSUE TITLE
Error getting metadata 

### ISSUE THREAD

**Issue by MadGhigno** [mozilla/pdf.js#11376]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 78.0.3904.108 (Official Build) (64-bit)
- Operating system and its version: Linux MInt (buster/sid)
- PDF.js version: 2.2.228 (tried with 2.3.200 pre-release also)
- Is a browser extension: no

Steps to reproduce the problem:

The following code contains two links in the example. The first one doesn't work and return an exception. The second one return the PDF metadata correctly

`"use strict"
var PDFJS = require("pdfjs-dist");

// THIS PDF HAS PROBLEMS
var url = "https://invest.medincell.com/wp-content/uploads/2019/11/MEDCL_CP_-Annonce-des-reésultats-semestriels-2019-2020_F.pdf";

// THIS PDF WORK AS EXPECTED
// var url = "https://www.idexx.com/files/2019-q1-earnings-release-20190501.pdf";

async function getPDFMetaDataFromUrl(url) {

    var numOfPages;
    var pdfMetadata;

    return new Promise(function (resolve, reject) {
        try {
            var loadingTask = PDFJS.getDocument(url);
            loadingTask.promise.then(function (pdf) {
                console.log('PDF loaded');
                numOfPages = pdf.numPages;

                pdf.getMetadata(numOfPages).then(function (pdfMeta) {
                    console.log('Metadata loaded');

                    // if (typeof pdfMeta["info"]["CreationDate"] !== 'undefined') {
                    //     pdfMeta["info"]["CreationDateISO"] = convertPDFDateTimeToISO(pdfMeta["info"]["CreationDate"])
                    // }
                    pdfMeta["info"]["numberOfPages"] = numOfPages;

                    resolve(pdfMeta);

                }, function (reason) {
                    // PDF loading error
                    console.error(reason);
                });

            })

        } catch (e) {
            reject(e);
        }

    })

}

async function app(url) {

    try {

        var pdfdate = await getPDFMetaDataFromUrl(url);

        console.log(pdfdate);

    } catch (e) {
        console.log("An exception occurred: "+ e);
    }

}

app(url);
`

Am I doing something wrong here ?

**Comment by Snuffleupagus** [comment]
> [https://invest.medincell.com/wp-content/uploads/2019/11/MEDCL_CP_-Annonce-des-reésultats-semestriels-2019-2020_F.pdf](https://invest.medincell.com/wp-content/uploads/2019/11/MEDCL_CP_-Annonce-des-ree%CC%81sultats-semestriels-2019-2020_F.pdf)

That link redirects to https://invest.medincell.com/, which clearly isn't a PDF document. (The issue template asks for files to be *attached* to the issue, to avoid problems with broken links.)

Assuming that you actually meant https://invest.medincell.com/wp-content/uploads/2019/11/MEDCL_CP_-Annonce-des-re%CC%81sultats-semestriels-2019-2020_FR.pdf then that file, and the `getMetadata` method, works just fine in the default viewer.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by MadGhigno** [comment]
Yes, you're right there's a redireciton in the middle, I missed it.

In this case: https://www.townofcortemadera.org/ArchiveCenter/ViewFile/Item/3103 there's no redirection but I get an exception. The file is correclty displayed in Chrome but trying to read the metadata with the example I posted returns an exception.

**Comment by Snuffleupagus** [comment]
> In this case: https://www.townofcortemadera.org/ArchiveCenter/ViewFile/Item/3103 there's no redirection but I get an exception.

That also works just fine in the default viewer, hence you'll need to actually follow the last paragraph from https://github.com/mozilla/pdf.js/issues/11376#issuecomment-560451847 since otherwise this issue won't be actionable.

**Comment by timvandermeij** [comment]
Closing since no runnable example is provided.
