### ISSUE TITLE
PDF file not rendered inside a web application when the link contains query parameters

### ISSUE THREAD

**Issue by lamisChebbi** [mozilla/pdf.js#11377]
This anomlay is reproduced for any PDF file.

Configuration:
- Web browser and its version: Chrome 78.0.3904.108
- Operating system and its version: Windows 10
- PDF.js version: 2.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Display a PDF file inside a web application using a link (I used the iframe) as described [here](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website).
2. The file will be retrieved from the backend. Add some query parameters to the link, the url will look like this **file= http://domain/serverPath?queryParam1=value1&querParam2=value2&queryParam3=value3**

What is the expected behavior? (add screenshot)
PDF file should show up.
PS: Without query parameters the file shows up correctly. The same url used to work in the previous release. 

What went wrong? (add screenshot)
The query parameters are not sent to the server. In the browser's console, the url looks like this http://domain/serverPath?queryParam1. After debugging in the viewer.js file, I noticed that
in the function webViewerInitialized, the call to parseQueryString returns wrong value. Cause the split by '&'  is done without removing the file parameter "file="

Thanks

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

**Comment by timvandermeij** [comment]
Closing since the resource above should describe the solution.

**Comment by rudolphi** [comment]
When updating from version 5.3.31 to 5.4.54, parameters within the properly encoded file parameter stopped working. This URL does work
https://sciflection.com/applet/pdfjs-5.3.31/web/viewer.html?file=%2FgetBindata.jsp%3Ftable%3DAnaData%26pk%3D11444%26field%3DanaDataBlob%26autoWrap%3Dtrue%26filePattern%3D*.pdf%26filename%3DMai20.pdf
while this one no longer does:
https://sciflection.com/applet/pdfjs-5.4.54/web/viewer.html?file=%2FgetBindata.jsp%3Ftable%3DAnaData%26pk%3D11444%26field%3DanaDataBlob%26autoWrap%3Dtrue%26filePattern%3D*.pdf%26filename%3DMai20.pdf
