### ISSUE TITLE
too many colors in viewer.css

### ISSUE THREAD

**Issue by allefeld** [mozilla/pdf.js#11372]
I'm trying to re-skin the viewer, in order to comply with

> we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.

and to make it themeable (within Atom).

However, that proves to be made extremely hard by the way the viewer is styled. I was able to replace the icons (images) by alternatives from Awesome Font. Now I'm trying to change the colors and I found that (according to [CSS Color Extractor](http://www.css-color-extractor.com/))

there are **83 unique color specifications** used in `viewer.css`,
and they result in **70 different RGBA colors**.

And that doesn't even count things linke
```
opacity: 0.2;
background: #ff0;
```

That's not just a very large number, it also means that some of the specifications are unnecessarily different. Which is consistent with the fact that the color specifications have all possible different formats:
**rgb(), rgba(), hsl(), hsla(), 3-digit hex, 6-digit hex, named (black, white, blue, yellow).**

Black is specified as **black and #000**,
transparency as **transparent, rgba(0,0,0,0), and hsla(0,0%,100%,0)**.

There are tiny variations like: **hsla(0,0%,100%,0), hsla(0,0%,100%,.02), hsla(0,0%,100%,.03), hsla(0,0%,100%,.05), hsla(0,0%,100%,.08), hsla(0,0%,100%,.09), and hsla(0,0%,100%,.15).**
Here's what that looks like on a black background:
![image](https://user-images.githubusercontent.com/1738353/69904820-66972580-13a3-11ea-8eb2-cc66eb7a4518.png)
In case you can't tell: there is a white "A" in each box, in different shades of basically invisible.

That doesn't just make it nearly impossible to comply with the ask quoted above. It is also bad design practice, and makes it extremely hard for you if at some point you're planning to actually give the viewer a modern or themeable design.

**Comment by allefeld** [comment]
In case it helps, here are the lists of color specifications generated by CSS Color Extractor, in the original form and normalized to rgba: [colors.txt](https://github.com/mozilla/pdf.js/files/3907460/colors.txt) [colors-rgba.txt](https://github.com/mozilla/pdf.js/files/3907461/colors-rgba.txt)

**Comment by timvandermeij** [comment]
I agree with your analysis that the variation in colors is too much. We should try to make it more consistent and easier to tweak the CSS.

**Comment by timvandermeij** [comment]
The pull request above unified all color specifications to RGBA with a consistent format. This reduced the number of unique color specifications from 83 to 70. I found that quite a few specifications are just opacity variations, so I'll make a follow-up issue about starting to use CSS variables to make re-skinning easier.

**Comment by allefeld** [comment]
Great, thank you! @timvandermeij
