### ISSUE TITLE
Html file not loading in WkWebView but works on UIWebView

### ISSUE THREAD

**Issue by mounika1402** [mozilla/pdf.js#11383]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Loading on WKWEBView
- Operating system and its version: iOS
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
 NSString *sPath = [[NSBundle mainBundle] pathForResource:@"pdfjs/web/viewer" ofType:@"html"];
    if(isTestLecture){
        docSeekPosition = 1;
    }
    NSString *finalPath = [NSString stringWithFormat:@"%@?file=%@#page=%d",sPath,docPath,(int)docSeekPosition];
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:finalPath]];
    [self.webView loadRequest:request];

 - Using the above lines of code to load the HTML . sPath is URL to PDF file on a server (https://......cloudfront.net...../book/AUD-0.01.pdf)
- I found a solution where the PDF is being downloaded first and then the URL is being passed to the pdfjs but I do not want to download the file; Instead directly load the file from server in the pdfJS.
- It working perfectly fine on UIWebView and we recently changed it to WKWebView and it stopped loading the PDF
What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> It working perfectly fine on UIWebView and we recently changed it to WKWebView and it stopped loading the PDF

Given the somewhat limited information provided, there's unfortunately nothing here that would indicate a bug in the PDF.js library. Rather it would seem to be platform/browser *specific*, and thus not something that can be fixed *here*.
