### ISSUE TITLE
pdf.js load many page in the Second visit  

### ISSUE THREAD

**Issue by naeemms** [mozilla/pdf.js#11386]
![xxxxz](https://user-images.githubusercontent.com/58548905/70228574-9d838780-1765-11ea-8e82-f4fa0e4fd848.jpg)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:

chrome
- Operating system and its version:
window7 
- PDF.js version:
 * Copyright 2019 Mozilla Foundation

- Is a browser extension:

Steps to reproduce the problem:
1. I have a problem which is when the visitor reads through a book and reaches the page number 60 for example... and then when he visits again for the same book he should wait to download the entire file before it opens...  load many page to open
I have modified some codes such as the file size but it didn't work! Any suggestions or instructions??
2.I tried this solution
 "disableStream": true
"disableAutoFetch"true

but still  load  many page  The flowers told me that the file was lengthened at the opening It is only 5 mb 
But I noticed if the file is 10 MB, the page opens faster
Where do I edit to make it run faster instead of downloading the previous pages?
What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://hulul-cdn1.com/ss/web/viewer.html?file=https://hulul-cdn1.com/ss/hadithw1m.pdf

**Comment by Snuffleupagus** [comment]
> I tried this solution
>        "disableStream": true
>        "disableAutoFetch"true
> [...]
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://hulul-cdn1.com/ss/web/viewer.html?file=https://hulul-cdn1.com/ss/hadithw1m.pdf

The viewer above seems, based on a quick look, to be an *unmodified* version of the default viewer. However, given the size of the code it's simply impossible to know where *exactly* you attempted to set those parameters, without a either a smaller example or a *direct* link to the relevant portion of the code.

(However, running `PDFViewerApplication.pdfDocument.loadingParams` in the console shows that *at least* the `disableAutoFetch` option wasn't actually set...)

**Comment by naeemms** [comment]
I disabled it but nothing happened 

this file  more 10 mb open fast 

https://hulul-cdn1.com/ss/web/viewer.html?file=https://hulul-cdn1.com/lg4.pdf

pdf.js work good with file more 10 mb 

I think I need to adjust the file size settings from where I can edit them

thank you

**Comment by timvandermeij** [comment]
The links are dead and this seems to be answered.
