### ISSUE TITLE
Chrome34浏览器集成pdf.js报错Unhandled promise rejection

### ISSUE THREAD

**Issue by QErMeng** [mozilla/pdf.js#11384]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by QErMeng** [comment]
错误信息：Unhandled promise rejection 
Error {stack: (...), message: "载入 PDF 时发生错误。"}

**Comment by timvandermeij** [comment]
Closing since the entire issue template is empty.
