### ISSUE TITLE
Specific PDF file does not render correctly

### ISSUE THREAD

**Issue by harrallo** [mozilla/pdf.js#11385]
Configuration:
- Web browser and its version: Chrome 78
- Operating system and its version: Windows 8.1
- PDF.js version: your demo (https://mozilla.github.io/pdf.js/web/viewer.html) and also our .net implemented library (latest)

Steps to reproduce the problem:
We have a PDF file and it does not render correctly in pdfJs.
It looks like it has rendered just a part of the page.  When I open the same PDF file with PDF reader, it looks ok.
I have also checked the PDF file with PDF validator and it says that the file is 100% valid. 
There are no errors in JS console.

Can you please let me know, what causes the problem and how to solve it?

Attach (recommended) or Link to PDF file here: 
PDF will be sent through secure exchange. Please, let me know, how that works.

**Comment by Snuffleupagus** [comment]
> Can you please let me know, what causes the problem and how to solve it?

That's, quite frankly, impossible without access to a test-case unfortunately...

> PDF will be sent through secure exchange. Please, let me know, how that works.

If the original PDF document contains sensitive information, please try to either redact it is as necessary *or* create a reduced test-case using the same PDF generator.

Please keep in that this is an *open source* project, with most people contributing in their spare time, hence the most reasonable way to get bugs fixed is generally by providing publicly available test-cases. (Also, keep in mind that a patch would be required to include tests as well.)

**Comment by harrallo** [comment]
This is the problematic pdf. We have managed to remove the sensitive data parts.
[problematic.pdf](https://github.com/mozilla/pdf.js/files/3926686/problematic.pdf)

**Comment by harrallo** [comment]
Thank you very much! That was really quick :)
