### ISSUE TITLE
Scrolling issue with pdf.js

### ISSUE THREAD

**Issue by FlinForm** [mozilla/pdf.js#11393]
Hi guys, I'm developing Android application which uses pdf.js inside a WebView.

Now we're provoding API to scroll, zoom, etc, using voice commands.

Unfortunatylly, I did not find any API to scroll pdf document programatically.
I've also tried window.scroll(), window.scrollTo(), window.scrollBy(), methods but they are not working.

Can you help me with this issue?

**Comment by timvandermeij** [comment]
The default viewer uses the `scrollIntoView` function, which, together with its usages, is probably what you're looking for: https://github.com/mozilla/pdf.js/blob/16ae7c6960c1296370c1600312f283a68e82b137/web/ui_utils.js#L109-L153

I'm not aware of any other APIs for this.
