### ISSUE TITLE
SVG renderer: Glyphs overlap

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#11394]
Glpyhs from SVG renderer overlap (HTML rendering is fine).

Steps to reproduce:
PDF: [overlap.pdf](https://github.com/mozilla/pdf.js/files/3939690/overlap.pdf)

````
npm  install
gulp  dist-install
node  examples/node/pdf2svg.js  /tmp/overlap.pdf
firefox  svgdump/*.svg
````

**Comment by ShraddhaBhojane** [comment]
Hi can I please take this?

**Comment by timvandermeij** [comment]
Sure, feel free to work on this.
