### ISSUE TITLE
[Question] how to extract the outline / catalogue / contents?

### ISSUE THREAD

**Issue by KnIfER** [mozilla/pdf.js#11396]
Pdf.js provide us with an outline sidebar for users to navigate.   

Now I would like to extract that outline .

I can see All of tha data behide them via `window.PDFViewerApplication.pdfOutlineViewer.outline` which will return a huge array. But I have no idea which outline item refer to which page ?

**Comment by Snuffleupagus** [comment]
> Now I would like to extract that outline .

This is done with the `PDFDocumentProxy.getOutline` method, see https://github.com/mozilla/pdf.js/blob/a6db0457893b7bc960d63a8aa07b9091ddea84e0/src/display/api.js#L703-L722

> But I have no idea which outline item refer to which page ?

That information can be obtained with the `PDFDocumentProxy.getPageIndex` method, see https://github.com/mozilla/pdf.js/blob/a6db0457893b7bc960d63a8aa07b9091ddea84e0/src/display/api.js#L617-L625

Please refer to the PDF specification for more information about the destination format used in PDF documents, in particular see https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.2063217

**Comment by KnIfER** [comment]
Exactly what I need!  Thank you for the very fast reply!
