### ISSUE TITLE
Error after deployment to server

### ISSUE THREAD

**Issue by WuWenL0** [mozilla/pdf.js#11408]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 79.0.3945.79
- Operating system and its version: centos7
- PDF.js version: Latest edition
- Is a browser extension:

Steps to reproduce the problem:
1. Error after deployment to server
2.Uncaught ReferenceError: require is not defined

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![微信图片_20191216170308](https://user-images.githubusercontent.com/53036149/70893392-f684d280-2025-11ea-8924-0e3c992ecf1e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
`require` should not be available in the built artifacts, so it looks like you didn't use built files. Refer to https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website for how to setup PDF.js.

**Comment by 280017423** [comment]
check the .gitignore file, is the build dir is ignored?
