### ISSUE TITLE
can't open the pdf

### ISSUE THREAD

**Issue by JiangSanJie** [mozilla/pdf.js#11405]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. the plugin show blank totally.
2.There are some runtime errors.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32502682/70691291-a50dd800-1cf3-11ea-9ec8-44ccd84c2a57.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by JiangSanJie** [comment]
I'm not a js programmer but server, and i',m bad at js. Please help me !

**Comment by timvandermeij** [comment]
The PDF file appears to be corrupt, but without the file itself this issue is incomplete.
