### ISSUE TITLE
Invalid characters are printing in PDF when we have &nbsp - NBSP (non-breaking space)  

### ISSUE THREAD

**Issue by rajacsharp** [mozilla/pdf.js#11403]
Attach (recommended) or Link to PDF file here:
[1.pdf](https://github.com/mozilla/pdf.js/files/3951841/1.pdf)

Configuration:
- Web browser and its version: 
- Operating system and its version:
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
1. Load the attached document
2. When it is rendered can notice junk characters in document bullet points 

What is the expected behavior? (add screenshot)
should display without any junk characters
This works fine when we open same file in Adobe reader and in chrome pdf viewer
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/58780677/70646718-7baa6900-1c6d-11ea-8c8d-22fe086839fe.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  tested with uploading document  this to demo viewer there also we see this problem

**Comment by rajacsharp** [comment]
@timvandermeij @janpe2 

Thanks for fixing this issue , Appreciated!.  We are waiting for this fix , Can you please provide the dist file with this fix ?

**Comment by VijaylakshmiA** [comment]
@timvandermeij 

can you please provide the dist file for fix

**Comment by rajacsharp** [comment]
@timvandermeij @janpe2 
Can you please let us know when is the next official  release ?

**Comment by Snuffleupagus** [comment]
***Please stop repeatedly spamming the bug tracker, or pinging people, asking for updates!***

There's a patch for this issue, however it's nether reviewed nor landed as of yet. Furthermore, this issue isn't severe enough to warrant back-porting to older releases and once a fix actually lands it will simply be included in an upcoming release.
