### ISSUE TITLE
Detect change of page or last page

### ISSUE THREAD

**Issue by benjy8001** [mozilla/pdf.js#11416]
Hi,

I have a question about this lib.

Is it possible to detect the page scroll (the user go to the next or the previous page) (some kind of event) ?

By the way, there is an event trigger when the user reach the last page of the pdf ?

Thanks for your help.

**Comment by timvandermeij** [comment]
In the default viewer there are events for next page/last page, see https://github.com/mozilla/pdf.js/blob/7ceb394c43de99e7c444141e0bd7abfa12ecb772/web/app.js#L1369-L1370, but those are for the user-initiated actions such as clicking a button. I think what you're looking for is the `pagechanging` event instead, see https://github.com/mozilla/pdf.js/blob/3d549f12fa6bf2a82096a0d02f3404b18170ec59/web/base_viewer.js#L235/.
