### ISSUE TITLE
PDF show a blank page when viewing

### ISSUE THREAD

**Issue by menver** [mozilla/pdf.js#11417]
Configuration:
- Web browser and its version: Chrome and FF
- Operating system and its version: Windows 10
- PDF.js version: 2.1.268 reproduced in latest
- Is a browser extension: embedded in 3rd party application.

Open PDF

Client uploading the problem PDF.
Error in console is :

PDF 190733997489a283aeb1d146a75d32b5 [1.5 Cuminas HC-PDF Encoder SDK / Cuminas DjVu# .NET SDK] (PDF.js: 2.4.43)
Warning: JPX: Trying to recover from: Codestream code 0xFF53 (COC) is not implemented
Warning: Unable to decode image: TypeError: codingStyleParameters is undefined
Warning: JPX: Trying to recover from: Codestream code 0xFF53 (COC) is not implemented

May be related to
#11052
and/ or
#9246

**Comment by menver** [comment]
Client uploading the problem PDF.
Error in console is :

PDF 190733997489a283aeb1d146a75d32b5 [1.5 Cuminas HC-PDF Encoder SDK / Cuminas DjVu# .NET SDK] (PDF.js: 2.4.43)
Warning: JPX: Trying to recover from: Codestream code 0xFF53 (COC) is not implemented
Warning: Unable to decode image: TypeError: codingStyleParameters is undefined
Warning: JPX: Trying to recover from: Codestream code 0xFF53 (COC) is not implemented

**Comment by menver** [comment]
May be related to 
https://github.com/mozilla/pdf.js/issues/11052
and/ or 
https://github.com/mozilla/pdf.js/issues/9246

**Comment by laverdure87** [comment]
[NP-10-RW-1-3.pdf](https://github.com/mozilla/pdf.js/files/3984572/NP-10-RW-1-3.pdf)

**Comment by menver** [comment]
We have had another report of this issue from a different client.

**Comment by THausherr** [comment]
That image is huge, maybe #6741 ?

**Comment by menver** [comment]
The new issue we have had the image/scan layer exceed the page boundary by a few mm. once adjusted to fit in the page it all works. not sure if that is true of the old PDF
