### ISSUE TITLE
PDFJS new promise approach password and progress callback

### ISSUE THREAD

**Issue by eromano** [mozilla/pdf.js#11420]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 78
- Operating system and its version: N/A
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:

Hi I am trying to migrate this piece of code:
```
        const loadingTask = pdfjsLib.getDocument(pdfOptions);

        loadingTask.onPassword = (callback, reason) => {
        };

        loadingTask.onProgress = (progressData) => {
        };

        loadingTask.then((pdfDocument: PDFDocumentProxy) => {

        });
```
To the new promise logic without success

I tought looking to the ``` @types/pdfjs-dist ``` types
```
declare function getDocument(
    source: PDFSource,
    pdfDataRangeTransport?: PDFDataRangeTransport,
    passwordCallback?: (fn: (password: string) => void, reason: string) => string,
    progressCallback?: (progressData: PDFProgressData) => void
): PDFLoadingTask<PDFDocumentProxy>;
```
that this would have been ok:
```
      this.pdfDocument = await pdfjsLib.getDocument({
            source: pdfOptions,
            passwordCallback: onPassword,
            progressCallback: onProgress
        }).promise;

```
But it seems not and I didn't find any good example as well in the documentation or in the example app. Any help is appreciated 

What went wrong? 
The passwordCallback and progressCallback are not valid parameters infact I don't see them in the implementation.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Hi I am trying to migrate this piece of code:
> 
> ```
>         const loadingTask = pdfjsLib.getDocument(pdfOptions);
> 
>         loadingTask.onPassword = (callback, reason) => {
>         };
> 
>         loadingTask.onProgress = (progressData) => {
>         };
> 
>         loadingTask.then((pdfDocument: PDFDocumentProxy) => {
> 
>         });
> ```

But, that's already *almost* the correct format. The only change necessary is that the last part needs to be `loadingTask.promise.then((pdfDocument: PDFDocumentProxy) => { ... });` instead; please also refer to the documentation in https://github.com/mozilla/pdf.js/blob/693240cf06dfde191532450837828f67691f5a9f/src/display/api.js#L422-L506

> I tought looking to the `@types/pdfjs-dist` types
> ...

That was the *old* format, which was removed more than two years ago. Please note that the types you're referring to are maintained in a *different* project, and as such there's no guarantee that they're correct and/or up-to-date.

**Comment by eromano** [comment]
Ok thanks for the fast response 

```
  const loadingTask = pdfjsLib.getDocument(pdfOptions);

        loadingTask.onPassword = (callback, reason) => {
        };

        loadingTask.onProgress = (progressData) => {
        };

        loadingTask.promise.then((pdfDocument: PDFDocumentProxy) => {

        });
```
works perfectly.
