### ISSUE TITLE
Slow rendering on Firefox for Mac (fast on Safari and Chrome)

### ISSUE THREAD

**Issue by samuelbradshaw** [mozilla/pdf.js#11421]
Attach (recommended) or Link to PDF file here:
https://media.ldscdn.org/pdf/music/hymns/2001-01-0000-complete-hymns-eng.pdf
(attempting to load a single page from the PDF – page 201 for example)

Configuration:
- Web browser and its version: Firefox 71.0 (64 bit)
- Operating system and its version: macOS 10.15.2 Catalina (I have not tested on other operating systems)
- PDF.js version: 2.2.228 (loaded via https://cdn.jsdelivr.net/npm/pdfjs-dist@2.2.228/build/pdf.min.js)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF.js-based viewer in Firefox.
2. Attempt to render a page from the linked PDF.

What is the expected behavior? (add screenshot)
– Page should load quickly (within a few seconds, as it does in Chrome or Safari).

What went wrong? (add screenshot)
– Page takes about to minute to load. Screenshots from Firefox and Chrome attached.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
– This is the viewer (still in development): https://singpraises.net/collections/en/hymns/joy-to-the-world/sheet-music
– The JavaScript that loads the sheet music when the page loads can be found at the bottom of the page source. This is my first time using PDF.js, so it's possible I'm doing something wrong.

<img width="956" alt="Screen Shot 2019-12-20 at 4 25 19 PM" src="https://user-images.githubusercontent.com/7323052/71298659-63f67300-2346-11ea-8c70-609e96962a15.png">

<img width="956" alt="Screen Shot 2019-12-20 at 4 25 59 PM" src="https://user-images.githubusercontent.com/7323052/71298660-63f67300-2346-11ea-8ab6-c2bd39a9cd5e.png">

**Comment by timvandermeij** [comment]
The pages load almost instantly for me on Arch Linux, so marking as a Mac-specific bug for now.

**Comment by samuelbradshaw** [comment]
Thanks for following up on this! Loading is faster now, on Firefox 88.0.1 for Mac – so, something must have been fixed in Firefox code over the past few months.
