### ISSUE TITLE
Searching function just go to the page not to the text

### ISSUE THREAD

**Issue by reesezxf** [mozilla/pdf.js#11441]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 64.0.3282.186(Official Build) (64-bit)
- Operating system and its version: Windows 7 Enterprise Edition
- PDF.js version: 1.9.426
- Is a browser extension:

Steps to reproduce the problem:
-1. I use pdfjs with django to open some pdf files in browser 
-2. when I search a text, it just go to the page not to the text, is any way to fix that?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is required.

> PDF.js version: 1.9.426

That version is too old to be supported; please find current releases at https://github.com/mozilla/pdf.js/releases

> I use pdfjs with django to open some pdf files in browser

This is primarily an open-source *bug tracker*, hence we unfortunately cannot provide specific support for various frameworks.

---

Generally speaking, this issue unfortunately contains nowhere near enough (or clear) information to be actionable.
