### ISSUE TITLE
Messed up RTL/BiDi rendering if disableFontFace is not set

### ISSUE THREAD

**Issue by rslife** [mozilla/pdf.js#11457]
## Configuration
- Web browser and its version:

```
Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
```

- Operating system and its version:

```
% uname -orm
5.3.11-arch1-1 x86_64 GNU/Linux
```

```
% glxinfo| grep '^OpenGL'
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1650/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.31
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 440.31
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.31
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

- PDF.js version:

Latest used by the website (gh-pages)

```
pdfjsLib.version
"2.4.244"
pdfjsLib.build
"3b448611"
```
- Is a browser extension:

No

## Steps to reproduce the problem

Simply render to canvas following the Hello World example.

---

Test PDF: [test.pdf](https://github.com/mozilla/pdf.js/files/4009588/test.pdf)

---

## `disableFontFace=false` (default)

![disableFontFace=0](https://user-images.githubusercontent.com/47317317/71578723-ff83a280-2b01-11ea-80e5-bbdcf5aa87ed.png)

---

## `disableFontFace=true`

![disableFontFace=1](https://user-images.githubusercontent.com/47317317/71578724-ff83a280-2b01-11ea-8c92-7a6b0e67d15b.png)

**Comment by Snuffleupagus** [comment]
Looks fine on Windows 7, when opening the file with the [demo viewer](https://mozilla.github.io/pdf.js/web/viewer.html); this might thus be a Linux bug.

**Comment by rslife** [comment]
@Snuffleupagus The viewer doesn't have the issue. Rendering to canvas does.

**Comment by Snuffleupagus** [comment]
> The viewer doesn't have the issue. Rendering to canvas does.

The viewer is rendering the document using canvases too, so that's strange...
In order to make this issue actionable, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by rslife** [comment]
Okay. I couldn't reproduce this instantly in an isolated test case, but I figured out why. `dir="rtl"` needs to be set to reproduce the issue (directly on the canvas element, or inherited which was the case in my templates). So if anyone is bumping into this, setting `dir="ltr"` explicitly on the canvas is a good work-around.

I will upload a full test if you still can't reproduce.

**Comment by timvandermeij** [comment]
The hello world example is the most simple example, so it's expected that it's lacking practically all viewer functionality where we have bidi (bidirectional text). I don't think there is anything we need to change for the hello world example itself.

**Comment by rslife** [comment]
Regardless of the triviality of the hello world example, I still think PDF rendering issues caused by `dir`/`direction` being set to `rtl` in HTML/CSS is a bug that should be solved, as it shouldn't even have the ability to affect the rendering at all.

A website that defaults or fully supports an RTL language often sets `dir` (and `lang`) in the `<html>` element itself (to be inherited by everything under it).

(I actually noticed the bug when I was already half-done writing my own embedded viewer).

**Comment by Snuffleupagus** [comment]
> I still think PDF rendering issues caused by `dir`/`direction` being set to `rtl` in HTML/CSS is a bug that should be solved,

There's no way "fix" this, in the code, until https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction becomes generally available in all browsers; hence the *only* work-around here would be to update the relevant examples to include the CSS `direction: ltr;` rule or to simply WONTFIX the issue as https://github.com/mozilla/pdf.js/issues/11457#issuecomment-569810335 suggested.

**Comment by timvandermeij** [comment]
I think we could update the examples to explicitly state the left-to-right direction. That way it's hopefully a bit more explicit and easier to change for users.

**Comment by Snuffleupagus** [comment]
> That way it's hopefully a bit more explicit and easier to change for users.

Just to clarify, the only way to not break text rendering is if the CSS `direction: ltr;` rule is set on the element holding the canvas; note how this is done in the viewer https://github.com/mozilla/pdf.js/blob/3b448611974cf896775c51b47207a10b9707a955/web/pdf_viewer.css#L23
Otherwise there *will* be breakage in the way that this issue describes.
