### ISSUE TITLE
How to cancel or destroy a getPage request with disableAutoFetch set

### ISSUE THREAD

**Issue by arelaxend** [mozilla/pdf.js#11453]
Dear pdf.js contributors,

With `disableAutoFetch set`, is there a way to cancel fetching on `getPage()` ? The same way one `destroy()` getDocument promise

It looks like it is possible but I found only internal functions.

Best, A.

**Comment by Snuffleupagus** [comment]
> With `disableAutoFetch set`, is there a way to cancel fetching on `getPage()` ?

Huh, calling `getPage` is what *causes* data to be requested (there's no cancelling involved); it's quite frankly difficult to understand what you're trying to ask here.

**Comment by arelaxend** [comment]
> it's quite frankly difficult to understand what you're trying to ask here.
Oups. With disableAutoFetch off and disableStreaming off, whenever one calls getDocument starts the fetching the entire file. One can cancel the fetching by calling destroy() on the promise, it is going to stop the GET request. 

With disableAutoFetch set, fetching occurs just after getPage, but there is no destroy() to cancel the GET 206 request in case one wants to.

**Comment by Snuffleupagus** [comment]
> [...] but there is no `destroy()` to cancel the GET 206 request in case one wants to.

There's no way of doing what you're asking, short of destroying the `loadingTask` itself (and thus closing the *entire* document).

> For example, one requires to cancel some pages currently being fetched because the user moves to other pages before the previous pages were fetched.

First of all, note that there's a couple of *different* ways that data could be loaded (using Fetch, XMLHttpRequest, or a `PDFDataRangeTransport` implementation). Secondly, there's generally speaking nothing that says that *different* pages wouldn't need data from the *same* byte range (and aborting a request would thus break other `getPage` calls).

Hence what you're asking for isn't possible, nor will not be supported either unfortunately (as outlined above, and the use-case seems fairly specialized anyway).

**Comment by arelaxend** [comment]
> Secondly, there's generally speaking nothing that says that different pages wouldn't need data from the same byte range (and aborting a request could thus break other getPage calls).

Ok. In my use case, I fetch say page [-1, current, 1] whenever the user moves to a page. If a user moves fast to another current page, I am going to cancelAllRequests().

> https://github.com/mozilla/pdf.js/blob/c3a1c679500e1e4cfa13291f2bcd58ebbba2eb14/src/display/transport_stream.js#L131-L139

Wait until all the requests are cancelled, and fetch the new [-1, current, 1] pages.
My question is: does cancelAllRequests() the best option for such scenario ?

**Comment by Snuffleupagus** [comment]
> I am going to cancelAllRequests().

As explained in https://github.com/mozilla/pdf.js/issues/11453#issuecomment-569335735 that will easily lead to all kinds of breakage, and isn't something that you should be calling manually (it's being used from `WorkerTransport.destroy`).

> I am currently using `PDFDataRangeTransport` implementation for range requests.

Please note that the *default* range request functionality in PDF.js isn't in any way connected with `PDFDataRangeTransport`, so unless you're using the API along the lines below then you're not actually using `PDFDataRangeTransport`.
```javascript
const loadingTask = getDocument({
  range: /* custom PDFDataRangeTransport here */,
  //  more parameter here
});
```

**Comment by arelaxend** [comment]
OK. I am going to `setTimeout(() => getPage(), 200);`
Thank you

**Comment by Snuffleupagus** [comment]
> What is the purpose of PDFDataRangeTransport ?

It allows completely custom data delivery, that you thus can implement in what ever way you want/need in your case (it's being used in the PDF Viewer that's built-in to the Firefox browser).

While it does allows a great deal of flexibility, it's consequently a fair bit more complex than just providing a URL when calling `getDocument` :-)

> I found no examples or use cases out there

There's the [API unit-tests](https://github.com/mozilla/pdf.js/blob/47ab4b839f6c16ff022c7152417950627d796cee/test/unit/api_spec.js#L1841-L1967) and also the default viewer usages [here](https://github.com/mozilla/pdf.js/blob/47ab4b839f6c16ff022c7152417950627d796cee/web/app.js#L563-L603), [here](https://github.com/mozilla/pdf.js/blob/47ab4b839f6c16ff022c7152417950627d796cee/web/firefoxcom.js#L253-L311), [here](https://github.com/mozilla/pdf.js/blob/47ab4b839f6c16ff022c7152417950627d796cee/web/firefoxcom.js#L233-L242) and finally [here](https://searchfox.org/mozilla-central/rev/723e61e5f6fe36e69592b7742bc10338392e53e4/browser/extensions/pdfjs/content/PdfStreamConverter.jsm#803-834) and [here](https://searchfox.org/mozilla-central/rev/723e61e5f6fe36e69592b7742bc10338392e53e4/browser/extensions/pdfjs/content/PdfStreamConverter.jsm#692-742).

**Comment by timvandermeij** [comment]
Closing as answered by the comments above.

**Comment by legistek** [comment]
I had a similar issue with very large non-linearized PDFs where `getPage` was taking a very long time for later pages because most if not the whole PDF had to be downloaded. Specifically if the user closed the document but not the app it would nonetheless keep downloading. For this `PDFDocumentLoadingTask.destroy` works well, thank you for the advice @Snuffleupagus!

I would quickly point out that it would be nice to be able to cancel an individual page load too though because, of course, page loading can sometimes take WAY longer than rendering. Hunting around the code it seems like during the `while` loop [here](https://github.com/mozilla/pdf.js/blob/42aa08563b588c60f10ec113c7e81e7d7eeb7540/src/core/catalog.js#L1084)  it'd be pretty straightforward to add a simple cancellation check on each iteration, using something akin to an optional `CancellationToken` that could be passed into `getPage` and `getPageDict`. Would that not do the trick and would you entertain a PR that did that?
