### ISSUE TITLE
Use CSS variables in `viewer.css`

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11462]
In order to make re-skinning the viewer easier, we should look into starting to use CSS variables in `viewer.css`. Not only does this reduce duplication, it also allows us and other users to more easily change the appearance of the viewer.

There is the option of using something like https://github.com/jhildenbiddle/css-vars-ponyfill in `GENERIC` builds to rewrite CSS variables at runtime so we don't need to preprocess the CSS. If that doesn't work, using `PostCSS` is a possibility since we already use it. Either way, we need to make sure that CSS variables also work for older browsers that we still support.

**Comment by PIYUSHgoyal16** [comment]
I would like to work on this issue

**Comment by timvandermeij** [comment]
Sure, go ahead. Start simple though because we first need to know if the ponyfill approach will work cross-browser.

**Comment by Shivansh2407** [comment]
@timvandermeij I would love to work on this issue . Can you please explain me what needs to be done here?

**Comment by Snuffleupagus** [comment]
> Can you please explain me what needs to be done here?

Please see https://github.com/mozilla/pdf.js/issues/11462#issue-544365487 and https://github.com/mozilla/pdf.js/issues/11462#issuecomment-571328948.

**Comment by Shivansh2407** [comment]
So Should I start from beginning in case I Have to ponyfill the css variables?

**Comment by timvandermeij** [comment]
First check if the ponyfill works by testing in all supported browsers (IE11, Edge, Chrome, Firefox, Opera, Safari). If so, we can check what variables we can create for the various colors.
