### ISSUE TITLE
no range request when getDocument

### ISSUE THREAD

**Issue by pszww** [mozilla/pdf.js#11467]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox71.0(64-bit) and chrome 74.0.3729.131
- Operating system and its version:
- PDF.js version: 2.2.228
- Is a browser extension:

Steps to reproduce the problem:
```
    console.log('---------------------------------------------');
    console.log(url);
    pdfjsLib.getDocument({url: url, rangeChunkSize: 65536,}).promise.then(function (pdfDoc_) {
        pdfDoc = pdfDoc_;
        $('#page_count').text(pdfDoc.numPages);
        total = pdfDoc.numPages;
        renderLimitPage(page);
    });
```
What went wrong? (add screenshot)
![request](https://user-images.githubusercontent.com/19218901/71712667-2bc05b80-2e41-11ea-9665-0706ef74eb80.png)
Here is one request get the entire pdf. What can i do with it to open range request ?

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
