### ISSUE TITLE
"The provided value 'moz-chunked-arraybuffer' is not a valid enum value... #6306" is a still a problem

### ISSUE THREAD

**Issue by kramsdell** [mozilla/pdf.js#11460]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 79.0.3945.88 (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. Create an Angular 6 project. use ng2-pdf-viewer 4.0.0
2.Change pdf-dist version to 2.3.200 and look in console when launching app

What is the expected behavior? (add screenshot)
To not have to warning
What went wrong? (add screenshot)
The warning is shown even though this was apparently "fixed" in a later version and the issue was closed.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Duplicate of issue #6306, which was completely fixed by the code removal in PR #10678.

> Change pdf-dist version to 2.3.200 and look in console when launching app

That quite frankly doesn't make any sense, since this has been fixed since the `v2.2.228` release of the PDF.js library; hence there's nothing more that can be done here since it's already been fixed.

**Comment by kramsdell** [comment]
After trying multiple time more to update, it appears to be fixed now. My apologies for raising alarm. Have a happy new year!
