### ISSUE TITLE
Text-Only PDF duplicates the text in create-react-app 

### ISSUE THREAD

**Issue by pbenschop** [mozilla/pdf.js#11464]
Configuration: Chrome 79.0.3945.88, Windows Server 2016, pdf.js 2.2.228.

pdf.js is hosted inside a React application derived from create-react-app. In development mode the problem does NOT occur. However, when running an optimized build created with "yarn build", text-only PDFs, display the text twice. First the proper text is displayed with the correct formatting and a split second later, the same text, this time not formatted, is shown at the top of the page (see attached screenshot).  pdf.min.js and pdf_viewer.js are loaded with script tags in index.html. Most likely, this is a build issue and not a problem with pdf.js (since it works properly in development mode). However, I cannot figure out what might be going on here. I am hoping someone will offer a suggestion how to resolve this problem. Thank you on forehand. 

Peter

![Extra-Text-PDF-Problem](https://user-images.githubusercontent.com/2353981/71645493-35ee2880-2c8e-11ea-9176-f505fb49f53f.PNG)

**Comment by timvandermeij** [comment]
I can only imagine that the styles for the text layer are not included in the built version, so perhaps the bundling/preprocessing of the CSS goes wrong because the text layer should be an invisible overlay over the formatted text. However, without a running example we cannot provide further assistance with this unfortunately.

**Comment by pbenschop** [comment]
Thanks so much, @timvandermeij, for pointing me to the css. The problem was resolved after loading pdf_viewer.css with a link tag instead of letting Webpack compile it into the build.
