### ISSUE TITLE
enable `file:` links

### ISSUE THREAD

**Issue by allefeld** [mozilla/pdf.js#11470]
I have a (reskinned) copy of `web/viewer.html` from `pdfjs-dist` in an `iframe` (within an Atom package), and I'm trying to enable `file:` links in the PDF.js viewer.

I came across #6072 which pointed to the possibility to override `isValidURL`, but then found out that it has since been replaced by `createValidAbsoluteUrl` which calls `_isValidProtocol` to check for permitted protocols.

I therefore tried to enable `file:` links by adding a line `case 'file:':` to `_isValidProtocol` in `build/pdf.js`, but this doesn't have an effect.

I also tried to monkeypatch `createValidAbsoluteUrl` after the `pdfjsLib` object is created:
```
pdfjsLib.createValidAbsoluteUrl =
  function createValidAbsoluteUrl(url, baseUrl) {
    if (!url) {
      return null;
    }

    try {
      var absoluteUrl = baseUrl ? new URL(url, baseUrl) : new URL(url);
      return absoluteUrl;
    } catch (ex) {}

    return null;
  }
```
again unsuccessfully.

How do I override `createValidAbsoluteUrl` / `_isValidProtocol` in order to enable `file:` URLs?
If possible, I would prefer a method that does not involve modifying `pdfjs-dist` files but patching created objects instead.

Configuration:
- Web browser and its version: Atom 1.42.0 / Electron 4.2.7 / Chrome 69.0.3497.128
- Operating system and its version: Debian GNU/Linux 10.2
- PDF.js version: pdfjs-2.3.200-dist

**Comment by Snuffleupagus** [comment]
For (obvious) security reasons, *browsers* themselves will generally disable linking to `file://` URLs.

> I therefore tried to enable `file:` links by adding a line `case 'file:':` to `_isValidProtocol` in `build/pdf.js`, but this doesn't have an effect.

That would suggest that the browser did indeed block the URL.

> How do I override `createValidAbsoluteUrl` / `_isValidProtocol` in order to enable `file:` URLs?

You don't, since this is a browser limitation (and furthermore there's no desire to make these methods easily configurable).

**Comment by allefeld** [comment]
The issue is that PDF.js doesn't create an `<a>` element from a `file:` URL, as it does for `http:` URLs.
This has nothing to do with the browser. Otherwise, the code in `createValidAbsoluteUrl` / `_isValidProtocol` wouldn't be necessary.

**Comment by Snuffleupagus** [comment]
> The issue is that PDF.js doesn't create an `<a>` element from a `file:` URL, as it does for `http:` URLs.

It wouldn't really help if the link elements were rendered, since the browser should still prevent navigating to `file://` URLs.

> I also tried to monkeypatch `createValidAbsoluteUrl` after the `pdfjsLib` object is created:

Please note that this won't help, since the relevant parsing is done in the worker-thread which isn't directly accessible.

**Comment by allefeld** [comment]
> It wouldn't really help if the link elements were rendered, since the browser should still prevent navigating to `file://` URLs.

Since this is all happening in Atom, where `<a>` elements generally don't do anything by themselves, this is not a problem. I've attached an event listener which takes the appropriate action, including for `http:` links.

> Please note that this won't help, since the relevant parsing is done in the worker-thread which isn't directly accessible.

Alright, so which part of the PDF.js code do I have to modify? I edited `build/pdf.js`, but that doesn't change the behavior. Do I maybe have to rebuild?

**Comment by Snuffleupagus** [comment]
> I edited `build/pdf.js`, but that doesn't change the behavior.

That's expected, since this isn't the worker-thread code. If you're editing the pre-built files directly, the file you need to make your changes in is `pdf.worker.js`.

> Do I maybe have to rebuild?

In order to facilitate updating to new PDF.js versions, it may indeed be easier to build from *source* (after applying your custom changes) rather than modifying the pre-built library files.

**Comment by allefeld** [comment]
Thanks! Editing `build/pdf.worker.js` did the trick:

![Peek 2020-01-04 17-27](https://user-images.githubusercontent.com/1738353/71769320-862beb80-2f17-11ea-96c8-67eb76260a4c.gif)

Which makes me wonder, why is identical code in `pdf.js` and `pdf.worker.js`?
