### ISSUE TITLE
Print current view/zoomed view of pdf

### ISSUE THREAD

**Issue by Anu004** [mozilla/pdf.js#11476]
Hi,

Is there any way to print only the current view of a pdf? As per the default print option in pdf.js, it will print the whole selected pages. Instead of that I want to print a selected rectangular area in the pdf. Is it possible?

**Comment by timvandermeij** [comment]
It can potentially be made, but it's not possible with the default viewer as-is. In general, printing APIs in browsers are *very* limited, so I think the only way to achieve this is to render the current view onto a new canvas and print that. This is, however, out of scope for the PDF.js project itself, but could be implemented in a custom deployment.
