### ISSUE TITLE
Wrong rendering of pattern

### ISSUE THREAD

**Issue by MichaelEischer** [mozilla/pdf.js#11473]
[pattern.pdf](https://github.com/mozilla/pdf.js/files/4022310/pattern.pdf)

Configuration:
- Firefox Nightly 73.0a1 (2020-01-04)
- macOS Mojave 10.14.6
- PDF.js version: 2.4.254
- Is a browser extension: built-in

Steps to reproduce the problem:
1. Open the PDF, zoom in to 200% for a more detailed view

What is the expected behavior?
<img width="736" alt="pattern-acrobat" src="https://user-images.githubusercontent.com/9106997/71770714-34dc2600-2f30-11ea-958d-4fea6f2b53c2.png">

What went wrong?
<img width="563" alt="pattern-pdfjs" src="https://user-images.githubusercontent.com/9106997/71770723-4a515000-2f30-11ea-8a92-cef4cac2a8f8.png">

The crosshatch pattern is rendered by pdf.js using the wrong pattern style. The other pattern style just seem to have a broken redering.

TeX source of PDF:
```tex
\documentclass[a4paper,11pt]{scrartcl}
\usepackage{tikz}
\usetikzlibrary{patterns}

\begin{document}
crosshatch pattern:
\begin{tikzpicture}
\draw[draw=black, fill=black!10, pattern=crosshatch, pattern color=black] (0,0) rectangle (1,1);
\end{tikzpicture}
\\

north east lines pattern:
\begin{tikzpicture}
\draw[draw=black, fill=black!10, pattern=north east lines, pattern color=black] (0,0) rectangle (1,1);
\end{tikzpicture}
\\

north west lines pattern:
\begin{tikzpicture}
\draw[draw=black, fill=black!10, pattern=north west lines, pattern color=black] (0,0) rectangle (1,1);
\end{tikzpicture}
\\

grid pattern:
\begin{tikzpicture}
\draw[draw=black, fill=black!10, pattern=grid, pattern color=black] (0,0) rectangle (1,1);
\end{tikzpicture}
\end{document}
```

**Comment by SamyCookie** [comment]
Since #11473, there is some tiny glitches on lines, should we reopen this ticket until rendering is perfectly effected ?
