### ISSUE TITLE
Incorrect text rendering (letter "A" sprinkled everywhere)

### ISSUE THREAD

**Issue by gima** [mozilla/pdf.js#11477]
### Attach (recommended) or Link to PDF file here:
URL: https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.693.7686&rep=rep1&type=pdf  
Attached (same file): [10.1.1.693.7686.pdf](https://github.com/mozilla/pdf.js/files/4025798/10.1.1.693.7686.pdf)

Configuration: | .
-- | --
Web browser and its version | Firefox 71.0 (64-bit)
Operating system and its version | Arch Linux
PDF.js version | Firefox 71.0 (64-bit)
Is a browser extension | Yes, Firefox's built-in PDF.js

**Steps to reproduce the problem:**
1. Open URL / Attachment
2. Observe

### What is the expected behavior? (add screenshot)
(As viewer by atril 1.22.2-3 (MATE document viewer))
![image](https://user-images.githubusercontent.com/1252061/71814885-77177b80-3086-11ea-804b-a5ada0cff42c.png)

### What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/1252061/71814875-70890400-3086-11ea-8edd-bbfadf1b01bc.png)

**Comment by timvandermeij** [comment]
I can also reproduce this on Arch Linux.

**Comment by SamyCookie** [comment]
Debian Buster 64 bits with Firefox ESR 68.3 and native PDF.js as the same bug
