### ISSUE TITLE
PDF File not working with page size [8.26 * 11.69 inch]

### ISSUE THREAD

**Issue by Cheikhaoui** [mozilla/pdf.js#11483]
Hello,
when I try to open a file with page size [8.26 * 11.69 inch] I got the message : 
An error occurred while rendering the page.
PDF.js v2.3.101 (build: 31f31930)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4352:13
CanvasGraphics_paintInlineImageXObject@resource://pdf.js/build/pdf.js:5803:27
CanvasGraphics_paintImageXObject@resource://pdf.js/build/pdf.js:5757:12
CanvasGraphics_executeOperatorList@resource://pdf.js/build/pdf.js:4625:22

-But when I resize it with foxit reader to [7.75 * 10.75] it work 
Can I resize the file in the code of PDF.JS ?

Thanks

**Comment by timvandermeij** [comment]
It looks like the original PDF file was corrupt, and resaving it with a PDF editor will usually fix this corruption. It's, however, impossible to tell without the actual PDF file.
