### ISSUE TITLE
IE11: Unhandled promise rejection 

### ISSUE THREAD

**Issue by masterbloom** [mozilla/pdf.js#11480]
I get the following errors in IE11. In other browsers it just works fine. In version 2.1.266 PDF.JS still worked in IE11.

Errors:
```
Unhandled promise rejection TypeError: Unable to get property 'then' of undefined or null reference
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'then' of undefined or null reference",
      message: "Unable to get property 'then' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'then' of undefined or null reference
   at Anonymous function (pdfjs/web/viewer.js:1204:7)
   at run (pdfjs/build/pdf.js:3269:13)
   at Anonymous function (pdfjs/build/pdf.js:3290:7)
   at flush (pdfjs/build/pdf.js:3744:9)"
   }
```

+

```
Unhandled promise rejection TypeError: Object doesn't support property or method 'getPageLayout'
   "Unhandled promise rejection"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'getPageLayout'",
      message: "Object doesn't support property or method 'getPageLayout'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'getPageLayout'
   at load (pdfjs/web/viewer.js:1210:5)
   at Anonymous function (pdfjs/web/viewer.js:1030:17)
   at run (pdfjs/build/pdf.js:3269:13)
   at Anonymous function (pdfjs/build/pdf.js:3290:7)
   at flush (pdfjs/build/pdf.js:3744:9)"
   }

```

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 10
- PDF.js version: 2.2.228
- Is a browser extension: No

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support;
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by timvandermeij** [comment]
It also doesn't state if this is about the default viewer or a modified (custom) viewer, so without a runnable example this is unfortunately not actionable.
