### ISSUE TITLE
Support HOSTED_VIEWER_ORIGINS checking with wildcard

### ISSUE THREAD

**Issue by Songyu-Wang** [mozilla/pdf.js#11484]
Attach (recommended) or Link to PDF file here:
N/A
Configuration:
- Web browser and its version: irrelevant 
- Operating system and its version: irrelevant
- PDF.js version: newest
- Is a browser extension: irrelevant

Steps to reproduce the problem:
N/A

What is the expected behavior? (add screenshot)
**Is it a good idea to support wildcard check?
For example:
`HOSTED_VIEWER_ORIGINS = ['*-myCompany.amazonaws.com']`
instead of 
`HOSTED_VIEWER_ORIGINS = ['test-myCompany.amazonaws.com','production-myCompany.amazonaws.com']`**

What went wrong? (add screenshot)
**My use case for pdf.js is to embed a pdf to our website. The pdf file is consumed from s3 bucket. 
In order to make it work, I have to modify `HOSTED_VIEWER_ORIGINS` to add the s3 url,
but in practice, it is not that easy since we have different stacks consume files from different buckets. Listing all possible buckets seems not like a good practice.** 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by Snuffleupagus** [comment]
While it would probably be *technically* possible to support this, it might not actually be desirable to do so by default in the PDF.js library.
The reason for this is that it'd essentially require supporting arbitrary regular expression matching, thus complicating the code in question considerably (and badly created regular expressions can also perform really poorly).

**Comment by Songyu-Wang** [comment]
@Snuffleupagus Maybe I am missing something here since I am not super familiar with the codebase. but from my perspective, It would be just few lines changes. For example, "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match"  or just a third party wildcard lib. Why would it `complicating the code in question considerably`?

**Comment by Snuffleupagus** [comment]
> For example, "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match" or just a third party wildcard lib.

But that would still require supporting regular expressions. Furthermore, adding third-party dependencies is something that's only done when *absolutely* necessary (and where no native functionality exists).

> It would be just few lines changes.

Note how `URL` is used to obtain a *valid* origin to compare against. Thus implementing a correct/efficient (and not too convoluted) check that compares against a regular expression, rather than a string, may not be that easy...
https://github.com/mozilla/pdf.js/blob/93aa613db7a874e6ed964f394241605d5586c142/web/app.js#L1737-L1741

**Comment by Songyu-Wang** [comment]
Well, I think it's just basic string manipulation, but up to you guys I guess...

**Comment by Snuffleupagus** [comment]
> Well, I think it's just basic string manipulation, but up to you guys I guess...

In that case, please show how you'd expect this to work :-)
Please keep in mind though: You'll need to compare actually *valid* `URL`s, rather than raw strings, in order for the solution to (generally) safe.
