### ISSUE TITLE
PDF rendering speed in Chrome 78 (or newer) is 5-10x times slower than previous version

### ISSUE THREAD

**Issue by thebauz8** [mozilla/pdf.js#11487]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 78 or newer
- Operating system and its version: Android (only Samsung and Huawei phones + tablets)
- PDF.js version: newest
- Is a browser extension: -

Steps to reproduce the problem:
1. open pdf
2. wait for rendering
3. rendering for big pdfs now takes forever
my sample pdf: 53 seconds in Chrome 78 or newer; 11 seconds in Chrome 77
same slow results on every other Samsung/Huawei phone

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

There's unfortunately nothing anyone can do here, with that part of the issue template missing.

> [...] my sample pdf: 53 seconds in Chrome 78 or newer; 11 seconds in Chrome 77

This sounds entirely like a regression in the *browser* itself, which is not possible to fix here. This thus sound like something you'd need to report to the browser developers instead.
