### ISSUE TITLE
Detech page orientation 

### ISSUE THREAD

**Issue by anglfc11415** [mozilla/pdf.js#11498]
Hi, is there a property in PDF.JS where we can identify if a page's orientation is portrait or portrait upside down (portrait mirrored)?

If a page is mirrored I would like to display text in proper form

please advise

**Comment by timvandermeij** [comment]
You can determine, given the page size, if it's portrait or landscape; see: https://github.com/mozilla/pdf.js/blob/93aa613db7a874e6ed964f394241605d5586c142/web/pdf_document_properties.js#L328

There is no property for if the page is mirrored. Perhaps you can use the text matrix to determine this, but you'd have to implement this yourself.
