### ISSUE TITLE
Get InternalLink Annotation destination coordinates

### ISSUE THREAD

**Issue by kidrobo** [mozilla/pdf.js#11494]
**Description**
We are trying to create a custom one page viewer for linking between service manuals using external links added to the annotation layer and the built in InternalLink annotations. 

**Problem**
We are having an issue highlighting the area referenced from the InternalLink. The annotationdata object has a dest array with FitR type. In Adobe, the links go to the referenced page and zoom in on the coordinates of the component. 

**Solution**
Looking for a solution to grab the coordinates so an overlay highlight can be displayed on the linked page.

Any help would be much appreciated! Thanks.

**Comment by kidrobo** [comment]
Is this sort of functionality possible? I tried a few different things using the dest array, but I was not able to get coordinates for the destination.

**Comment by Snuffleupagus** [comment]
Given the overall lack of details, it's unfortunately quite difficult to provide much assistance here; closing as INCOMPLETE for now.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
