### ISSUE TITLE
Some charcters are not displayed, while rendering using pdf.js

### ISSUE THREAD

**Issue by vigneshvenkatesh** [mozilla/pdf.js#11492]
Issue occurs in all browsers
PDF.js version: 2.2.228

Steps to reproduce the problem:
1. Download the file attached
2.View the file using pdf viewer

Please check and give a solution.

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Most likely you're not providing the necessary CMap parameters when calling `getDocument`, see https://github.com/mozilla/pdf.js/blob/4729fdc0e930154c9e4c4688b6239ed4708f0e5e/src/display/api.js#L121-L124
