### ISSUE TITLE
PDF loading is very slow and hangs

### ISSUE THREAD

**Issue by learnyst** [mozilla/pdf.js#11518]
Attach (recommended) or Link to PDF file here:
[set-2_lyst7242.pdf](https://github.com/mozilla/pdf.js/files/4076920/set-2_lyst7242.pdf)

Configuration:
- Web browser and its version:
Chrome browser, version 79

- Operating system and its version:
Mac OS, Mojave 10.14
Also same behavior in windows 10

- PDF.js version: Using the hosted demo

- Is a browser extension: No

Steps to reproduce the problem:
1. Just open the PDF in hosted demo

What is the expected behavior? (add screenshot)
PDF should load without hanging

What went wrong? (add screenshot)
PDF loading is very very slow and hangs

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by learnyst** [comment]
@timvandermeij is there any workaround to solve this performance issue?

**Comment by claudiawisniewski** [comment]
I experience the same Issue on Ubuntu 18.04.1
![2020-01-24 14-44-32](https://user-images.githubusercontent.com/56873264/73080613-66f4fe00-3ec6-11ea-9da4-96f23dfb9052.png)

**Comment by claudiawisniewski** [comment]
I'm experiencing the same Issue on Ubuntu 18.04.1 with pdfjs-dist version: "2.0.943"
![2020-01-24 14-44-32](https://user-images.githubusercontent.com/56873264/73080958-ff8b7e00-3ec6-11ea-959a-4109f3d13615.png)

**Comment by amit777** [comment]
This PDF loaded pretty slow on my macbook air circa 2015 using Preview.  I loaded it in the latest PDFJS, and it seems like similar performance (if not even slightly better).
```
const pdfjsVersion = '2.7.90';
const pdfjsBuild = '6728c8fa6';
```
