### ISSUE TITLE
How to use the search function?

### ISSUE THREAD

**Issue by xiaoyanhui123** [mozilla/pdf.js#11514]
Configuration:
- PDF.js version:2.0.943

Hi,I wanna use the search function.
My requirement is to open multiple PDFs at one time and search at the same time.
I used <iframe> to quote viewer.html, and then called the search function.
![image](https://user-images.githubusercontent.com/31909454/72492337-c8c6bf80-3857-11ea-99d5-840a70f6bee3.png)

Problem:
The first time I succeeded, but the second time only changed the value of'#findInput', without triggering search function.
susess:
![image](https://user-images.githubusercontent.com/31909454/72492323-bba9d080-3857-11ea-9827-ed5efcad63b2.png)
fail:
![image](https://user-images.githubusercontent.com/31909454/72492377-ebf16f00-3857-11ea-9a22-285432d14906.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version:2.0.943

That version is no longer supported, please find current releases at https://github.com/mozilla/pdf.js/releases
Furthermore, when opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.mdPDF.js version:2.0.943

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> PDF.js version:2.0.943

That version is no longer supported, please find current releases at https://github.com/mozilla/pdf.js/releases
Furthermore, when opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by xiaoyanhui123** [comment]
thank u man!
