### ISSUE TITLE
想实现外部按钮触发搜索功能

### ISSUE THREAD

**Issue by ChenLiuPng** [mozilla/pdf.js#11512]
![image](https://user-images.githubusercontent.com/58840360/72432560-519b1800-37d2-11ea-953e-73ad757b70d1.png)
代码:
![image](https://user-images.githubusercontent.com/58840360/72432608-6ecfe680-37d2-11ea-81d3-4dff9e2b7bfe.png)
现在问题：
值只有第一次传才有用，第二次无法生效，依然使用的是第一次传的值来搜索。请问我如何更改代码  谢谢

**Comment by timvandermeij** [comment]
We can only provide assistance in English and with all template information filled out.
