### ISSUE TITLE
Text overlay is wrong for flipped text

### ISSUE THREAD

**Issue by danielbrodin** [mozilla/pdf.js#11513]
Hi, I have multiple pdfs with both normal text and text rotated 180degrees that get the same behaviour as shown in the image, which is that the rotated text is aligned wrong. 

Each line of text seem to be correct, but the position is wrong and the text isn't rotated like it should be

[Pdf file in the screenshots](https://github.com/mozilla/pdf.js/files/4065095/Text.test.pdf)

Here is it with rotation 0 showing that the rotated text is at the wrong position
![pdf-test](https://user-images.githubusercontent.com/696872/72437648-79bf5280-37a3-11ea-9be7-3ca66245ed96.png)

Here it is rotated 180deg showing that the text layer is rotated the wrong way. Or rotated when it shouldn't be rotated that is.
![Screenshot 2020-01-15 at 14 35 32](https://user-images.githubusercontent.com/696872/72438043-521cba00-37a4-11ea-947c-ab0d4f070c30.png)

Is there any setting I have missed or is something wrong with this version or pdfjs just can't handle rotated text?

Configuration:
- Web browser and its version: Tested chrome, firefox and safari
- Operating system and its version: macOS Mojave
- PDF.js version: 2.2.228
- Is a browser extension:

**Comment by Snuffleupagus** [comment]
WFM in PDF.js version `2.4.264` in Firefox, see the following screen-shot from the default viewer (with textLayer debugging enabled):
![textlayer](https://user-images.githubusercontent.com/2692120/72438713-b724df80-37a5-11ea-9f10-255fb3152307.png)

It's not really clear *how* you're using the PDF.js library, but if if you're using the [components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components) then you may have forgotten to include the `pdf_viewer.css` file.
Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by danielbrodin** [comment]
I'm using `2.2.228` and you `2.4.264` which I can't see is available with `pdfjs-dist`. Could perhaps be something there?
When will 2.4 be released?

**Comment by Snuffleupagus** [comment]
> I'm using `2.2.228` and you `2.4.264` which I can't see is available with `pdfjs-dist`. Could perhaps be something there?

That's honestly speaking somewhat unlikely, hence please follow the instructions at the bottom of https://github.com/mozilla/pdf.js/issues/11513#issuecomment-574667278 (if the css file suggestion isn't already enough to fix this).

Furthermore, you should at least try with version `v2.3.200` as well, see https://github.com/mozilla/pdf.js/releases

> When will 2.4 be released?

No idea, but hopefully soon; it's being tracked in https://github.com/mozilla/pdf.js/issues/11495

**Comment by timvandermeij** [comment]
Closing since this appears to be answered and working.
