### ISSUE TITLE
Additional "fetch" request in Chrome network 

### ISSUE THREAD

**Issue by hexleyOlive** [mozilla/pdf.js#11527]
Hi,

Maybe someone has already encountered this issue, if yes any help will be appreciated!

Only with a website including an iframe to display a PDF, the PDF Viewer Chrome extension produces more requests compared to the default PDF viewer of Chrome.
The result is a much longer time to display PDF in the viewer.
I'm not sure if the problem come from the PDF Viewer extension, from Chrome or come from the way used to implement iframe in the website.
I'm not able to reproduce the same behavior with a simple HTML page including a iframe to display the PDF or with another website.

Anyone has an idea about the cause of these additional "fetch" request in the Chrome network activity?

Thanks

**Configuration:**
**- Web browser and its version:**
Chrome version 79.0.3945.117
**- Operating system and its version:**
macOS Mojave 10.14.6 (18G2022)
**- PDF.js version:**
2.3.164
**- Is a browser extension:**
Yes chrome extension

**What is the expected behavior? (add screenshot)**
PDF in iframe should produce same number of request and time to display compare the default PDF viewer of Chrome
Below result of request with default PDF Viewer of Chrome
<img width="1658" alt="PDF-Chrome-Standard" src="https://user-images.githubusercontent.com/8439893/72821457-cfe33880-3c70-11ea-8201-2234dc1eb2b5.png">

**What went wrong? (add screenshot)**
When PDF Viewer Chrome extension is enabled, multiple and additional "fetch" requests type are visible in the network traffic of Chrome with PDF in iFrame on a web page.
Result is: much longer time to display PDF in the viewer.
Below result of multiple request when PDF Viewer Chrome extension is enabled on the website involved.
<img width="1666" alt="PDF-Viewer-Chrome-Extension" src="https://user-images.githubusercontent.com/8439893/72821462-d5d91980-3c70-11ea-9116-17a082d1fbb6.png">

If needed, below code of web page (URL has been changed with example text):

Code on the webpage involved when Default PDF viewer of Chrome is used.
`<object data="https://example/asset/id/transform;key=create-pdf-of-article-time=1579622140999.pdf?sessionIdX=X" type="application/pdf" ng-switch-when="application/pdf" class="csLayout_absExpand" url="viewUrl">
                <embed type="application/pdf" src="https://example/asset/id/transform;key=create-pdf-of-article-time=1579622140999.pdf?sessionIdX=X">
            </object>
`

Code on the webpage involved when PDF Viewer extension is enabled:
`<object data="https://example/asset/id/transform;key=create-pdf-of-article-time=1579622140999.pdf?sessionIdX=X" type="application/not-a-pee-dee-eff-type" ng-switch-when="application/pdf" class="csLayout_absExpand" url="viewUrl" style="padding: 0px; display: inline-block;"><iframe src="chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/web/viewer.html?file=https%3A%2F%2Fexample%2Fasset%2Fid%2Ftransform%3Bkey%3Dcreate-pdf-of-article-time%3D1579622140999.pdf%3FsessionIdX%3DX" style="background: none; border: none; box-shadow: none; float: none; display: block; height: 100%; margin: 0px; max-height: none; max-width: none; position: static; transform: none; visibility: visible; width: 100%;"></iframe></object>`

Thanks

**Comment by Snuffleupagus** [comment]
> If needed, below code of web page (URL has been changed with example text):

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by hexleyOlive** [comment]
Thanks for answer.
Unfortunately, I'm not in charge of the web site involved and cannot check implementation of current PDF viewer.
I would to know if someone has already see this behavior about additional FETCH requests and if the PDF.js can be involved or not.

**Comment by Rob--W** [comment]
The screenshot shows:

1. Attempt to load .pdf plugin
2. PDF Viewer extension replaces the plugin content, by loading the PDF Viewer instead.
3. PDF Viewer extension fetches the PDF.
4. The web page forces the PDF Viewer extension to be reloaded.
5. PDF Viewer extension fetches the PDF.

Steps 1-3 are expected, step 4 is not. I think that the web page detected the content change from step 2, and unintentionally replaced the HTML in step 4.

A work-around to this problem is to patch the website to always open the PDF viewer extension upfront, instead of a PDF plugin. This can be done by prepending `chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/` to the PDF URL, and removing the `type` attribute from the `<embed>` or `<object>` tag.

**Comment by hexleyOlive** [comment]
Thanks you for these details, your help and analyze.
I close the ticket and i'll back to added additional information if needed.
