### ISSUE TITLE
How does pdf.js only print the pdf and not the full screen?

### ISSUE THREAD

**Issue by MulderNick** [mozilla/pdf.js#11525]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: any
- Operating system and its version: windows 10
- PDF.js version: v2.2.228
- Is a browser extension: false

How does pdf.js only print the rendered pdf instead of the whole .window? I have been trying replicate the print_service and went thoroughly through all the code in the print service and in app.js. I have implemented the code and the images for printing and it is rendered properly in its container element(printContainer). However i can't seem to find/decipher the code that is specifically responsible for printing the printingContainer instead of the whole window.

Could you explain how this works? It seems to be one of the major problems with printing that you cant easily print a specific element. I have found hack like replacing the content, printing, and putting back old content or some css stricks.

**Comment by Snuffleupagus** [comment]
> However i can't seem to find/decipher the code that is specifically responsible for printing the printingContainer instead of the whole window.

See https://github.com/mozilla/pdf.js/blob/ccf327538ba427e47d1ea16b1cc1d50f3340683b/web/viewer.css#L1767-L1829 and in particular https://github.com/mozilla/pdf.js/blob/ccf327538ba427e47d1ea16b1cc1d50f3340683b/web/viewer.css#L1805-L1813
