### ISSUE TITLE
CSP server restriction and bypassing them

### ISSUE THREAD

**Issue by kdzhambazov** [mozilla/pdf.js#11524]
Attach (recommended) or Link to PDF file here:
Any pdf containing a jpeg image.
Configuration:
- Web browser and its version: All browsers
- Operating system and its version: Windows 10
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open pdf containing jpeg image
2. The server has CSP restrictions for img-src and the browser blocks the blob:https://... image src url

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
The server has CSP restrictions for img-src and the browser blocks the blob:https://... image src url. 

Currently this code is been executed:
switch (type) {
          case 'JpegStream':
            imageData = data[3];
            (0, _util.loadJpegStream)(id, imageData, pageProxy.objs);
            break;

Line 1180, file api.js. The case is that the server restrictions for the CSP cannot be changed and I am looking for a solution to treat the jpeg in the pdf as an image not a JpegStream so it can bypass the blob:https://... and be set as image:data:base64...

Console error: The source list for Content Security Policy directive 'img-src' contains an invalid source: 'blob:https://xxxxxxxxxxxxxxxxx/*'. It will be ignored.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

Please provide *actual* version numbers here, see also below.

> Currently this code is been executed:
> switch (type) {
> case 'JpegStream':
> imageData = data[3];
> (0, _util.loadJpegStream)(id, imageData, pageProxy.objs);
> break;

The code in question was changed already in version `2.0.943` of the PDF.js library, which was released over a year ago, hence the version "latest" claim above doesn't look entirely correct.

Please make sure that you update to the most recent version of PDF.js; see https://github.com/mozilla/pdf.js/releases

> blob:https://... and be set as image:data:base64...

In that case, see https://github.com/mozilla/pdf.js/blob/ccf327538ba427e47d1ea16b1cc1d50f3340683b/src/display/api.js#L156-L158

Alternatively, you can disable browser decoding of JPEG images, see https://github.com/mozilla/pdf.js/blob/ccf327538ba427e47d1ea16b1cc1d50f3340683b/src/display/api.js#L113-L120
