### ISSUE TITLE
getDocument in pdfjs-dist package does not respect verbosity parameter

### ISSUE THREAD

**Issue by electrovir** [mozilla/pdf.js#11536]
This is in Node.js using the [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) npm package. That repo doesn't seem to accept issues so posting it here.

pdfjs-dist version: 2.2.228

Steps to reproduce the problem:
```typescript
import {VerbosityLevel, getDocument} from 'pdfjs-dist';
(async () => {
    await getDocument({url: 'path/to/any/pdf.pdf', verbosity: VerbosityLevel.ERRORS}).promise;
})();
```

`'path/to/any/pdf.pdf'` must be a pdf that generates warnings. Warnings are still printed even with the VerbosityLevel.ERRORS in the code above.

NOTE: pdfjs-dist might just be out of date? I noticed it was last published 4 months ago.

I did some digging and discovered the following:

By adding the following console.log in `pdf.js`:
```javascript
  var PDFWorker =
  /*#__PURE__*/
  function () {
    function PDFWorker() {
        console.log('constructing PDFWorker', (0, _util.getVerbosityLevel)());
```
I can see `0` (VerbosityLevel.ERRORS) being printed out as you would hope.

However, in `pdf.worker.js`, where the warning function is actually defined, it's not reading `verbosity` from util at all, it's simply defined within that file as `var verbosity = VerbosityLevel.WARNINGS;`. So I'm guessing simply fixing that will fix this.

FWIW I'm getting `Warning: getFontFileType: Unable to detect correct font file Type/Subtype.` from the `function warn(msg) {` definition in `pdf.worker.js` and I simply want to ignore it.

**Comment by electrovir** [comment]
Thanks for the fix! 😁 When do `pdf-dist` publishes get triggered? I'd like to try it out. 🙂

**Comment by timvandermeij** [comment]
Upon the next release, for which we already have a tracking ticket. There is no exact release date yet. In the meantime you can build PDF.js yourself if you want to try it out quickly.
