### ISSUE TITLE
Invalid pdf structure

### ISSUE THREAD

**Issue by yosefh** [mozilla/pdf.js#11531]
Hello @all,

I am currently working with Go and programming a web application. With the application it should be possible for specific users to upload PDFs and see / read them afterwards.

The Upload function works just fine, but if I try to load the pdf via Browser (PDF Viewer), the following output will be seen :

Mozilla Firefox : Version 72.02 (64-Bit)
![grafik](https://user-images.githubusercontent.com/23383863/72991412-40fe2980-3df2-11ea-8806-8fc00f90ca6c.png)

Version 79.0.3945.130 (Offizieller Build) (64-Bit)
![grafik](https://user-images.githubusercontent.com/23383863/72991677-b1a54600-3df2-11ea-8d98-e516f56c0472.png)

But if I open the PDF file on the pc with the PDF Reader, there are no errors and I can open the file without any trouble. 

![grafik](https://user-images.githubusercontent.com/23383863/72992466-0f865d80-3df4-11ea-9222-6b11d0413e1c.png)

PDF.js 
![grafik](https://user-images.githubusercontent.com/23383863/72992937-d8647c00-3df4-11ea-8d28-2df81d301729.png)

Therefore, I cannot understand the problem.
I would appreciate any tips or approachs how to fix my Problem.

Thanks

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

In this case, the `Attach (recommended) or Link to PDF file here:` part *must* be provided in order for the issue to be valid. Furthermore, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
