### ISSUE TITLE
Opening PDF links in a new tab in pdfjs-dist v2

### ISSUE THREAD

**Issue by alvgalrus** [mozilla/pdf.js#11538]
Hello,

I'd like to open all links inside a PDF in a new tab. I'm using pdf.js from the NPM distribution in order to add it to my frontend webpack.

Configuration:
- PDF.js version: pdfjs-dist v2.3.200 (next)

I've tried `PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;`, but it seems that property is no longer available in pdf.js v2.

I've also tried to set externalLinkTarget through other helper objects, but they don't seem to be available in the -dist version (especially the AppOptions class as imported in 
https://github.com/mozilla/pdf.js/blob/bce9ff7347266e18326fff52c201faba04a96bd7/web/app.js#L156 ).

Could anyone clarify this matter?

Regards,
Álvaro

P.S. I've also tried asking through IRC but everyone was idle.

**Comment by Snuffleupagus** [comment]
> I've tried `PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;`, but it seems that property is no longer available in pdf.js v2.

Correct, since PDF.js version 2 removed global configuration (since that would cause problems if you e.g. wanted to call `getDocument` more than once with different options).

> I'm using pdf.js from the NPM distribution in order to add it to my frontend webpack.

Without knowing *exactly* how you're actually using the PDF.js library (hence why [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) asks for runnable code), the following is assuming that you're using the [components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components):

The option in question, i.e. `externalLinkTarget`, is moved to the `PDFLinkService` constructor; see https://github.com/mozilla/pdf.js/blob/474fe1757e654e67d20a53774edb293aa073ce0b/web/pdf_link_service.js#L18-L42
Hence, using the "simpleviewer" example as a base, you'd have to change https://github.com/mozilla/pdf.js/blob/474fe1757e654e67d20a53774edb293aa073ce0b/examples/components/simpleviewer.js#L37-L38
to initialize it like this instead
```javascript
var pdfLinkService = new pdfjsViewer.PDFLinkService({
  externalLinkTarget: pdfjsLib.LinkTarget.BLANK,
});
```

**Comment by alvgalrus** [comment]
The problem with that example is that it loads the script manually : `<script src="../../node_modules/pdfjs-dist/web/pdf_viewer.js"></script>`. I can't call the PDFLinkService constructor.

Instead of that, my application imports PDFJS, but when I add pdfjsViewer it says `PDFJS is undefined`. If I change PDFJS to pdfjsLib, the builder says that `pdfjsLib is undefined` at setting `pdfjsLib.GlobalWorkerOptions`.

I can't really explain how is the origin PDFJS global (which the code calls three times) working with the v2 library, since it's legacy code.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by alvgalrus** [comment]
I can't share more than this as I roughly know how this works.

```
import React from 'react';
import PDFJS from 'pdfjs-dist';

PDFJS.GlobalWorkerOptions.workerSrc = '//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf.worker.min.js';

class PdfViewer extends React.Component {
    constructor() {
        super();
        this.state = {...}
        this.onPdfLoaded = this.onPdfLoaded.bind(this);
    }

    onPdfLoaded() {
        const { file } = this.props;

        // Not working in PDF.js v2
        //PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;

        const pdfLinkService = new PDFJS.PDFLinkService({
            externalLinkTarget: PDFJS.LinkTarget.BLANK,
        });

        const loadingPdf = PDFJS.getDocument(file).promise;
        loadingPdf.then(pdf => {
            pdf.getPage(1).then(page => {
                const init_page = page.getViewport({scale: 1});
                this.setState({
                    pdfRealSize: {
                        width: init_page.width,
                        height: init_page.height
                    }
                });
            });
            pdfLinkService.setDocument(pdf, null); //???
        });
    }
}
```

```
TypeError: pdfjs_dist__WEBPACK_IMPORTED_MODULE_12___default.a.PDFLinkService is not a constructor
onPdfLoaded
src/components/PdfViewer.js:52

  49 | // Not working in PDF.js v2
  50 | //PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;
  51 | 
> 52 | const pdfLinkService = new PDFJS.PDFLinkService({
       | ^     externalLinkTarget: PDFJS.LinkTarget.BLANK,
  54 | });
  55 | 
```

**Comment by alvgalrus** [comment]
To properly import all the classes, you have to do it this way:
```
import pdfjsLib from 'pdfjs-dist/webpack';
import * as pdfjsViewer from 'pdfjs-dist/web/pdf_viewer';
```

I have another problem, but not related to this one. Closing, then.
