### ISSUE TITLE
Incorrect font rendering

### ISSUE THREAD

**Issue by amelapay177** [mozilla/pdf.js#11532]
Attach (recommended) or Link to PDF file here: [ar99.pdf](https://github.com/mozilla/pdf.js/files/7086733/ar99.pdf)
https://www.dallasfed.org/fed/~/media/documents/fed/annual/1999/ar99.pdf 

Configuration:
- Web browser and its version: Firefox Browser 72.0.2 (64-bit)
- Operating system and its version: Windows 10 Enterprise version 1809
- PDF.js version: 2.4.152
- Is a browser extension:

Steps to reproduce the problem:
1. Open URL
2. Observe

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/60226822/72994265-6a03c780-3dbc-11ea-8914-42563b321546.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/60226822/72994291-77b94d00-3dbc-11ea-9de2-6214a4d4b361.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The PDF document uses *non-standard* fonts, but doesn't embed the necessary font data (e.g. the font program) needed in order for the text to render correctly.
