### ISSUE TITLE
PDF.js is not rendering parts of PDF generated by Oracle report system

### ISSUE THREAD

**Issue by wojciechklicki** [mozilla/pdf.js#11549]
Attach (recommended) or Link to PDF file here:

[test.pdf](https://github.com/mozilla/pdf.js/files/4133610/test.pdf)
This file has been edited by Acrobat Pro to remove sensitive data, but the rendering issue still persists for most of remaining elements.

Configuration:
- Web browser and its version: Chrome Wersja 79.0.3945.130 (Oficjalna wersja) (64-bitowa)
- Operating system and its version: Mac OS and Windows 10
- PDF.js version: Current from https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Open attached PDF in PDF.js and in system PDF viewer (for example Acrobat Reader) 
2. Compare text

What is the expected behavior? (add screenshot)
I expect whole text to render.
![image](https://user-images.githubusercontent.com/1452287/73443889-d2701d00-4357-11ea-83a2-3a2062601209.png)

What went wrong?
Some text is missing in PDF.js (for example part of customer number)

**Comment by Snuffleupagus** [comment]
From the console:
```
PDF 460701c9b197f541bfe39f71511ac574 [1.6 Oracle PDF driver / Oracle11gR1 AS Reports Services] (PDF.js: 2.4.264) viewer.js:1229:15
Warning: Error during font loading: Bad encoding in flate stream pdf.js:528:13
```

**Comment by wojciechklicki** [comment]
Ok, still this is a warning and standard pdf reader manages to render user readable text. The fonts does not matter in this case. The text content is important.
This PDF comes from my clients client and I cannot expect for them to understand that a crucial parts of text (marine container numbers!) can be missing sometimes when they are viewing shipment documents. This kind of behavior can destroy trust in any solutions that is using PDF.js as document viewer.

**Comment by Snuffleupagus** [comment]
> Ok, still this is a warning and standard pdf reader manages to render user readable text.

Your PDF file contains corrupt ToUnicode data, which other PDF viewers have had to implement workarounds for. (Which is what we're also forced to do here.)

All-in-all, I don't think it's entirely fair to "blame" a particular PDF viewer (or any other program really) when you're feeding it invalid data.

**Comment by wojciechklicki** [comment]
> All-in-all, I don't think it's entirely fair to "blame" a particular PDF viewer (or any other program really) when you're feeding it invalid data.

As a programmer I fully understand Your position and does not "blame" PDF viewer for this.
But end users will never accept this - from their point of view they have PDF that does not work only in my system (system that is using PDF.js).

**Comment by wojciechklicki** [comment]
#11551 fixes rendering nicely, but if You try to select and copy any text that was missed by rendering without this patch it will return gibberish. 
If I do the same from acrobat reader the text is fine.

I use the text layer for custom text mode rendering (and add some copy and paste custom functionalities), so it is even more painfull for me. Can anything be done about this ?

![image](https://user-images.githubusercontent.com/1452287/73697411-c630ea80-46de-11ea-9e85-89abfd3979c3.png)
