### ISSUE TITLE
Lock horizontal scroll - Mobile safari bug

### ISSUE THREAD

**Issue by tomerlavi** [mozilla/pdf.js#11543]
I am trying to add a function to disable horizontal scroll. Below is the code I use. While it works perfect on desktop browsers, it creates a bug in iOS browser - The document x offset is reset to 0, instead of keeping its current offset.

```
  const contentWrapper = document.getElementById("viewerContainer");
  contentWrapper.style.overflowX = "hidden";
  contentWrapper.style.WebkitOverflowScrolling = "none";

```

**Comment by Snuffleupagus** [comment]
> While it works perfect on desktop browsers, it creates a bug in iOS browser

If this is specific to a particular browser *and* platform it's quite frankly rather unlikely to be a bug in the PDF.js library, and would instead point to a browser bug; please report this to the browser vendor instead since it really doesn't seem like an actionable/valid bug *here*.
