### ISSUE TITLE
Get started with pdf.js

### ISSUE THREAD

**Issue by minedun6** [mozilla/pdf.js#11541]
Is it possible to add an example that showcases how to use this package as a drop-in kinda approach ?
Been trying to set it up since yesterday and I've been unsuccessful so far.
I'm able to use the examples provides in the examples directory but I'm trying to get the fullviewer to work.

To put anybody into perspective as to what I'm required/trying to do, here's some things that, ideally, I'd like to know how to do, either through the existing viewer, or if I can do this on my own.

* Searching: display a list of occurences in the pdf document.
* Pagination: possibility to track down what page I'm on
* Thumbnail shortcuts
* Bookmarks

These are the basic functions that I would like to know how to do through either viewer/pdfjs-core.

**Comment by Snuffleupagus** [comment]
> I'm able to use the examples provides in the examples directory but I'm trying to get the fullviewer to work.

https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website#examples is perhaps relevant here.

However, please note that there's purposely no *detailed* instructions provided regarding usage of the default viewer; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
