### ISSUE TITLE
The vertical writing mode with horizontal scaling is not rendered correctly

### ISSUE THREAD

**Issue by tamuratak** [mozilla/pdf.js#11555]
Attach (recommended) or Link to PDF file here:

[hello-abc.pdf](https://github.com/mozilla/pdf.js/files/4139771/hello-abc.pdf)

Configuration:
- Web browser and its version: Firefox 72.0.2
- Operating system and its version: macOS High Sierra 10.13.6
- PDF.js version: 2.4.321
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the attached pdf file.
2. Characters overlap.

What is the expected behavior? (add screenshot)

![スクリーンショット 2020-01-31 23 16 43](https://user-images.githubusercontent.com/10665499/73546004-cc755b80-447f-11ea-8c7b-941629b72caf.png)

What went wrong? (add screenshot)

![スクリーンショット 2020-01-31 23 17 22](https://user-images.githubusercontent.com/10665499/73546056-e1ea8580-447f-11ea-98be-ce6835247301.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
Fixed by #11556.
