### ISSUE TITLE
Page render issue

### ISSUE THREAD

**Issue by acquirenaren** [mozilla/pdf.js#11564]
I am trying to render HTML from viewer.js but the content has not been load. here is the sample of what I am trying to do

`function renderHTML(){
    var htmlContent = '<body tabindex="1" class="loadingInProgress"><div id="outerContainer"></div></body>document.getElementById('renderPDF').innerHTML = htmlContent;
}`

this code I have put in viewer.js at the beginning of the file.

When I am run the viewer.js that time all content will appear in my index.html file but pdf content not rendering

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
