### ISSUE TITLE
pdf.worker.js not loaded - try loading from the wrong location

### ISSUE THREAD

**Issue by Tecnezio** [mozilla/pdf.js#11565]
Configuration:
- Web browser and its version: firefox 72.0.2
- Operating system and its version: Linux Mint 19.3
- PDF.js version: lastest 2.2.228
- Is a browser extension: NO

I've included the last release of pdf.js into a website under the subdirectory "external/pdfjs/".
To test the website locally I've loaded the viewer on the page http://localhost/index.php?id=PDFpreview
The viewer does not load correctly "pdf.worker.js". In the debug console appear that is trying to load the pdf.worker.js from “http://localhost/build/pdf.worker.js” and is a wrong path.

I've set up in the viewer the option: 
pdfjsLib.GlobalWorkerOptions.workerSrc = 'external/pdfjs/build/pdf.worker.js';
but seems ignored.

With the old version 1.9 all was fine.
How can I set the path to load pdf.worker.js from a subdirectory correctly?

**Comment by Snuffleupagus** [comment]
If you're using the default viewer, then the configuration happens through the `AppOptions`; see https://github.com/mozilla/pdf.js/blob/master/web/app_options.js

If you don't want to edit the source code itself, you could use an event listener placed e.g. in the viewer.html file and set the `workerSrc` like so:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("workerSrc", "../custom/path/to/pdf.worker.js");
});
```
