### ISSUE TITLE
Different number of pages parsed between library and web-viewer

### ISSUE THREAD

**Issue by bradparker** [mozilla/pdf.js#11563]
First, thanks all for producing such a fantastic library. We use it heavily in our application and it's always been rock-solid.

Attach (recommended) or Link to PDF file here: 
[wiped.pdf](https://github.com/mozilla/pdf.js/files/4150833/wiped.pdf)

The above PDF is pretty strange (produced by a scanner and then edited by me to redact images) but the behavior is consistent with the original. The XRefs are super wrong (it's wrong in the original also) and the `"Hello, world"`s might be a strange way to redact images (I don't know much about PDF, sorry).

Configuration:
- Web browser and its version: Firefox Nightly (74.0a1 (2020-01-29) (64-bit)) and NodeJS (v8.15.1) 
- Operating system and its version: macOS Mojave (10.14.6)
- PDF.js version: pdfjs-dist 2.2.228
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the above PDF with https://mozilla.github.io/pdf.js/web/viewer.html and see how many pages are rendered / counted.
2. Run the following script:
    
    ```javascript
    const pdf = require("pdfjs-dist");

    const pages = async path => {
      const doc = await pdf.getDocument(path).promise;
      console.log(path, doc.numPages);
    };

    pages("./wiped.pdf")
    ```

    and see what it outputs.

    ```
    $ node .
    Warning: Indexing all PDF objects
    ./wiped.pdf 1
    ```

What is the expected behavior?

That the library does what it can to see that this PDF has two pages. It's such a gnarly PDF that this might not be possible, just opening this because the web-viewer (and Preview on macOS) seem to see two pages but the library only sees one.

What went wrong?

Viewer counts two pages, library counts one. In our app (where we use the lib) this means that the second page of PDFs like this one can't be rendered.

***

I've tried producing a PDF that has duplicate XRefs and objects that share IDs like the original does. But that didn't seem to trigger the same behavior.

See attached:
[example-broken.pdf](https://github.com/mozilla/pdf.js/files/4150858/example-broken.pdf)

(It's called "example-broken" but it seems fine, apologies).

Any help would be greatly appreciated.

**Comment by Snuffleupagus** [comment]
> PDF.js version: pdfjs-dist 2.2.228

> [...] just opening this because the web-viewer (and Preview on macOS) seem to see two pages but the library only sees one.

You're comparing *two* different versions of the PDF.js library here, since https://mozilla.github.io/pdf.js/web/viewer.html is (as of this writing) currently using PDF.js version `2.4.326`; see also https://github.com/mozilla/pdf.js/releases

**Comment by bradparker** [comment]
Ah, amazing. I just tested with latest master and it's working. Thank you! 
Any idea when 2.3 / 2.4 will be published to NPM?

**Comment by Snuffleupagus** [comment]
> Any idea when 2.3

It's already available, with a "next" tag, see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

> 2.4 will be published

Hopefully "soon", but there's no time-line; see issue #11495

**Comment by bradparker** [comment]
Looks like 2.3 still has an issue with my strange PDF, but current master works so we'll hang out for that. Thanks again :)
