### ISSUE TITLE
setInterval behaviour in PDFViewer is affected by other tabs.

### ISSUE THREAD

**Issue by singchow87** [mozilla/pdf.js#11562]
Attach (recommended) or Link to PDF file here:
(Example PDF) https://www.pdfscripting.com/public/FreeStuff/PDFSamples/JavaScriptClock.pdf

Configuration:
- Web browser and its version: Version 79.0.3945.130 (Official Build) (64-bit)
- PDF.js version: Chrome PDFViewer Extension

Steps to reproduce the problem:
1. Navigate to the link provided above.
2. Open another tab with the same link.
3. You'll notice the Clock in the first tab has stopped once you navigated to the link in the second tab.

What is the expected behavior? (add screenshot)
setInterval should not be affected by other tabs. Should be able to run independent.

What went wrong? (add screenshot)
setInterval in PDF getting affected by other tabs.

If you select "Stop Timer" in the first tab, it'll stop the "Clock" in the second tab.
Then if you select "Stop Timer" in the first tab again, it'll start the "Clock" in the first tab.

![image](https://user-images.githubusercontent.com/41834890/73664517-82d47d00-46da-11ea-8c4f-1f4665abecb8.png)
cc

**Comment by Snuffleupagus** [comment]
Your screen-shots show PDFium, i.e. the *built-in* PDF viewer in Google Chrome, which is *not* in any way affiliated with this project; hence you'll need to report this bug to the Chromium developers instead.

**Comment by singchow87** [comment]
Thank you for the info. Will report it to Chromium devs instead
