### ISSUE TITLE
CSP unsafe-inline CSS violations

### ISSUE THREAD

**Issue by Dreamsorcerer** [mozilla/pdf.js#11576]
Separating this from issue #11036 .

I am getting unsafe-inline errors for the CSS, for example on this line of code:
https://github.com/mozilla/pdf.js/blob/master/web/ui_utils.js#L893

Looks like there are several places using code like that, which would need to be changed to fix these errors.

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src ...". Either the 'unsafe-inline' keyword, a hash ('sha256-MW4Iy/yu3WipUpTMM/T6OjvUu9R6vUwutodlmYNo6qM='), or a nonce ('nonce-...') is required to enable inline execution.`

**Comment by Dreamsorcerer** [comment]
I'm not too familiar with the details here, but would it be possible to simply replace the setAttribute with a direct assignment to the width value?

`this.bar.style.width = "calc(100% - " + scrollbarWidth + "px);";`

**Comment by timvandermeij** [comment]
It looks like the pull requests above will fix this.
