### ISSUE TITLE
Corrupted PDF display under Crostini (ChromeOS Linux container)

### ISSUE THREAD

**Issue by msiniscalchi** [mozilla/pdf.js#11575]
Attach (recommended) or Link to PDF file here:
Using the demo PDF on the pdf.js website

Configuration:
- Chromium Version 79.0.3945.130 (Developer Build) built on Debian 10.2, running on Debian 10.2 (64-bit)
- Operating system and its version: Debian Buster running in the ChromeOS Linux default container ("Crostini")
- PDF.js version: whatever version the demo on the PDF.js web page uses
- Is a browser extension: NO

Steps to reproduce the problem:
1. Go to the PDF.js webpage
2. Click "Demo"

What is the expected behavior? (add screenshot)

PDF is displayed correctly

What went wrong? (add screenshot)
Most characters are simply not displayed.

![Screenshot 2020-02-07 at 6 17 22 PM](https://user-images.githubusercontent.com/668933/74075035-713eee00-49d6-11ea-8063-bac15d4e6d73.png)

Comments: I originally found out about this problem using the VScode LaTeX Workshop extension, which uses pdf.js to display PDF files produced by LaTeX. I was having the same issue with my own files---most characters just were not displayed. However, as shown above, the exact same behavior occurs when running a browser under Crostini.

If I instead visit the pdf.js website using Chrome, NOT within the Crostini container but under "regular" ChromeOS, everything works perfectly.

**Comment by Snuffleupagus** [comment]
This does look more like a `<canvas>` and/or Font loading bug in the platform/browser *itself*, rather than a general PDF.js library issue (since otherwise you'd expect it to be broken everywhere).

**Comment by msiniscalchi** [comment]
Hm. Interesting. Indeed things seem to work using Firefox-esr (68.4.1esr 64-bit). See attached screenshot. So this seems to be a Chromium-on-Crostini-specific issue. As I mentioned in the original message, the issue dues not arise with the standard Chrome browser in ChromeOS . It does however arise with Chromium 79, and with the Chromium engine built into VSCode.
![Screenshot 2020-02-08 at 1 01 19 PM](https://user-images.githubusercontent.com/668933/74090648-68502a00-4a73-11ea-8a61-86842846c088.png)

**Comment by timvandermeij** [comment]
This doesn't look like something that can be fixed on the PDF.js side. It's best to report the issue to the Chrostini developers.
