### ISSUE TITLE
Convert the various colors in `web/viewer.css` to CSS variables

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11572]
To make re-skinning the viewer easier, the various repeated colors in `web/viewer.css` should be converted to CSS variables. This way they should be easier to tweak for third-party deployments of PDF.js.

**Comment by rohanharikr** [comment]
Would like to work on this!

**Comment by Snuffleupagus** [comment]
> Would like to work on this!

As already mentioned in https://github.com/mozilla/pdf.js/issues/11572#issuecomment-583142672, this would be best done as part of other CSS modernization/improvement work:  

> Since there's already issues tracking the modernization/clean-up of the viewer UI, it'd probably make the most sense to introduce CSS variables as part of these improvements (which _really_ need to happen iteratively, since changing the entire UI in one big commit is essentially impossible to test/review).

**Comment by rohanharikr** [comment]
@Snuffleupagus Got it!

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by timvandermeij** [comment]
Fixed by #11077.
