### ISSUE TITLE
Wrong page number

### ISSUE THREAD

**Issue by Dreamsorcerer** [mozilla/pdf.js#11583]
Attach (recommended) or Link to PDF file here:
https://www.jstage.jst.go.jp/article/jsmr/55/0/55_0502/_pdf/-char/en

Configuration:
- Web browser and its version: Firefox current
- Operating system and its version: Mac OS X
- PDF.js version: 2.3.200 and native Firefox viewer

Steps to reproduce the problem:
1. Open PDF
2. The page selector shows the wrong number (+80), e.g. page 1 is 81, 2 is 82 etc.

**Comment by Dreamsorcerer** [comment]
![Screenshot 2020-02-10 at 4 53 17 pm](https://user-images.githubusercontent.com/2203121/74171124-f1a75e00-4c25-11ea-8295-f56edf9a04b7.png)

**Comment by Snuffleupagus** [comment]
This is intended behaviour, and this issue is thus INVALID, since the PDF document uses Page Labels; see http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1696265

**Comment by Snuffleupagus** [comment]
This is intended behaviour, since the PDF document uses Page Labels; see http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1696265
