### ISSUE TITLE
Retrieve specific searched highlighted text coordinates 

### ISSUE THREAD

**Issue by sureshcherry** [mozilla/pdf.js#11585]
I would like to retrieve the one of the search result Highlighted text coordinates. is there anyway to do this. I have searched the text as below

findController.executeCommand(action, {
                                        caseSensitive: false, 
                                        findPrevious: undefined,
                                        highlightAll: true, 
                                        phraseSearch: true, 
                                        query: searchText
                                });

It's highlighted the text occurrences on the PDF, Is there any way to retrieve specific highlighted text coordinates(right,left,bottom,top)

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Given that the entire [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is left blank it's somewhat difficult to know exactly what you're trying to do, but the following code may be helpful:
```javascript
var [selected] = document.getElementsByClassName("highlight selected");
selected.getBoundingClientRect();
```

Please note though that what you're asking for is not *officially* supported, and thus may not work perfectly and there's also no guarantee that it continues to work either (in future PDF.js versions).
