### ISSUE TITLE
Text from pdf document appears faded on top of the document on document preview

### ISSUE THREAD

**Issue by harsha1029708** [mozilla/pdf.js#11592]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Google Chrome Version 80.0.3987.100 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: '`-- pdfjs-dist@2.2.228' 
- Is a browser extension: NA

Steps to reproduce the problem:
1. Upload a PDF document to angular app with pdfjs viewer 
2. Observe that, all the pdf text is accumulated on the top of preview in faded text

What is the expected behavior? (add screenshot): Faded text should not appear & user should be able to select Pdf text in the same format in the document 

What went wrong? (add screenshot) Added, 

Code snippet as below 
```
public setupViewer(): void {
        this.pdfJs.disableTextLayer = false;

        this.pdfLinkService = new this.PDFJSViewer.PDFLinkService();
        this.pdfFindController = new this.PDFJSViewer.PDFFindController({ linkService: this.pdfLinkService });

        const pdfOptions: any = {
            container: this.scrollContainer.nativeElement,
            linkService: this.pdfLinkService,
            removePageBorders: false,
            textLayerMode: 1,
            findController: this.pdfFindController,
        };

        pdfOptions.annotationLayerFactory = new this.PDFJSViewer.DefaultAnnotationLayerFactory();
        this.pdfViewer = new this.PDFJSViewer.PDFViewer(pdfOptions);
        this.pdfLinkService.setViewer(this.pdfViewer);
    }
``` 
If the **textLayermode** in the above code snippet is changed to '0' or if it is removed, the faded text in the screenshot will disappear & will not allow user to select(copy) the pdf doc text.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
You're most likely not including the `pdf_viewer.css` file, which is *necessary* (note that all `html` files in the [components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components) include it).

However, note that we cannot support Angular here, and furthermore please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
