### ISSUE TITLE
loadingTask.destroy() throws worker exception

### ISSUE THREAD

**Issue by zmagyar** [mozilla/pdf.js#11595]
I'm displaying a progress bar on document loading with a Cancel button to give a chance to the user to abort the download. If I understood correctly based on #6546 calling destroy() on the loading task is the correct way to do it. But that throws an exception in the worker what I even not able to catch anywhere.

Configuration:
- Web browser and its version: Chrome 80.0.3987, Safari 13.0.5 (15608.5.11)
- Operating system and its version: MacOS 10.15.3
- PDF.js version: v2.3.200 (same in 2.2.228)
- Is a browser extension: no

Steps to reproduce the problem:
1. Call loadingTask.destroy() before getDocument resolves

What is the expected behavior? (add screenshot)
Worker should stop without exception

What went wrong? (add screenshot)
Try https://jsfiddle.net/zmagyar/uLnqk1m5/1/#
Console says: 
(index):76 Error: Worker was destroyed
    at terminateEarly (api.js:1781)
    at api.js:1827
    at Worker.MessageHandler._onComObjOnMessage (message_handler.js:147)

**Comment by Snuffleupagus** [comment]
> If I understood correctly based on #6546 calling destroy() on the loading task is the correct way to do it. But that throws an exception in the worker what I even not able to catch anywhere.

Are you sure about the "throws an exception" part, since what should be happening is that `loadingTask.promise` simply contains a *rejected* Promise (with `Worker was destroyed` as its message)?

> Worker should stop without exception
>
> What went wrong? (add screenshot)
> Try https://jsfiddle.net/zmagyar/uLnqk1m5/1/#

I'm not seeing any exception, just a rejected Promise. The fact that you choose to `console.error` the rejection reason doesn't mean that a "regular" exception was thrown from the PDF.js code.
Looking at your example (focusing on the interesting bits):
```javascript
...
loadingTask.promise.then(function(pdf) {
  ...
}, function (reason) { <-- This attaches a reject handler, hence that will stop any further error propagation.
  // PDF loading error
  console.error(reason);
}).catch((e) => console.log('It is not catching here'));

loadingTask.destroy();
```
The easiest way to handle this would be to simplify your code like so:
```javascript
...
loadingTask.promise.then(function(pdf) {
  ...
}).catch((e) => console.log('Here's the error you're expecting.'));

loadingTask.destroy();
```
or possibly:
```javascript
...
loadingTask.promise.then(function(pdf) {
  ...
}, function (reason) {
  // PDF loading error
  console.error(reason);
  throw reason;
}).catch((e) => console.log('Here's the error you're expecting.''));

loadingTask.destroy();
```

All-in-all, there doesn't seem to be anything wrong with the PDF.js library here.
(If you're new to Promises, you may find a guide such as e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises helpful.)

**Comment by doup** [comment]
I'm having the same issue, and no matter how I try to handle the promise (second `then` argument, `catch`, `await/try`) it stills bubbles up. From what I understand it's **NOT** the promise which is failing, it's the worker. So there is nothing to handle on the promise. Looks like the worker can't handle half-loaded documents (e.g. start loading a big PDF => call `loadingTask.destroy()` => get `Worker was destroyed` error).

If you search for the error in Google (`"Worker was terminated" pdf.js`) various users/libraries are having the same issue.

**Comment by Cyberhan123** [comment]
> 我遇到了同样的问题，无论我如何尝试处理承诺（第二个`then`参数，`catch`, `await/try`），它仍然会冒泡。据我所知，失败的**不是**承诺，而是工人。所以没有什么可以处理的承诺。看起来工作人员无法处理加载一半的文档（例如开始加载大 PDF => 调用`loadingTask.destroy()`=> 获取`Worker was destroyed`错误）。
> 
> 如果您在 Google ( `"Worker was terminated" pdf.js`) 中搜索错误，则各个用户/库都会遇到相同的问题。

I got same , u should make sure not call destroy method，If you call this, It's mean worker will terminate,the hold lifecycle will unmount, if you use webpack load woker. The worker just load once ,It's the error reason

**Comment by aeaton-overleaf** [comment]
There are two separate errors: 

* "Worker was destroyed" is thrown by `pdf.js` and can be caught as described above.
* "Worker was terminated" is thrown by `pdf.worker.js` and can't be caught in the same way.

**Comment by pinggi** [comment]
@doup is right.

React example - loads pdf in a component on mount:
```
useEffect(() => {
  const loadingTask = getDocument(testPdf.url);
  return () => {
    loadingTask.destroy(); // <-- we expect that it cancels the pdf loading
  };
}, []);
```

When the component is destroyed, we expect that it cancels the pdf loading and doesn't log anything to the console.
In fact it does log the exception.

It seems the exception happens here:
```
function getPdfManager(data, evaluatorOptions, enableXfa) {
  function setupDoc(data) {
    function onFailure(ex) {
       ensureNotTerminated(); <-- the code is: if (terminated) { throw new Error("Worker was terminated"); }
```

DevTools log:
![image](https://user-images.githubusercontent.com/18471834/140096279-b9e41343-9254-4fe3-8293-d484f11e239f.png)

**Comment by pinggi** [comment]
Perhaps the problem has a simple resolution - add a check if it was already destroyed:
```
if (loadingTask.destroyed) {
  loadingTask.destroy();
}
```

:-)

**Comment by codeWriter6** [comment]
I am encounter the same error, any solution?

**Comment by mikemathewson** [comment]
This issue is that the "await this._transport?.destroy();" line in the destroy() function prevents the worker from getting destroyed immediately.

The fix is to simply destroy the worker manually:

```
if (loadingTask._worker && !loadingTask._worker.destroyed) {
  loadingTask._worker.destroy()
}
if (!loadingTask.destroyed) {
  loadingTask.destroy()
}
```
