### ISSUE TITLE
Replace indirect use of deprecated 'new Buffer'

### ISSUE THREAD

**Issue by ttghr** [mozilla/pdf.js#11591]
pdf.js: function cloneValue(value)

line 11023:
`result = new value.constructor(buffer, value.byteOffset, value.byteLength);`

and line 11025:
`result = new value.constructor(value);`

are indirect calls of deprecated ` new Buffer()`

please replace with:
`result = Buffer.from(buffer, value.byteOffset, value.byteLength);`
and
`result = Buffer.from(value);`

**Comment by Snuffleupagus** [comment]
> pdf.js: function cloneValue(value)

That is a *built* file, thus not present directly in this repository, and there's consequently no development happening directly in that file. Furthermore, line numbers are not entirely meaningful without knowing which version you're referring to.
All-in-all, linking to actual source code would help immensely here!

> are indirect calls of deprecated ` new Buffer()`

Any links to e.g. [MDN](https://developer.mozilla.org/en-US/) and/or relevant specifications would also be helpful here.

---

Generally speaking, please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

**Comment by Snuffleupagus** [comment]
If I were to guess, you may be referring to this code: https://github.com/mozilla/pdf.js/blob/993a1d78259643eaef3070e641521252819c2bb9/src/display/api.js#L1491-L1509
In that case, the data in question are standard [`TypedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray)s, and should thus be perfectly fine to use e.g. as `new Uint8Array(...)` which is what the code does.

The [`Buffer`](https://nodejs.org/api/buffer.html) class is as far as I know limited to Node.js environments, and please note that we aren't (or at least shouldn't) be using that in the main code-base. See e.g. https://github.com/mozilla/pdf.js/blob/993a1d78259643eaef3070e641521252819c2bb9/src/display/node_stream.js#L166-L167 and https://github.com/mozilla/pdf.js/blob/993a1d78259643eaef3070e641521252819c2bb9/src/display/node_stream.js#L251-L252 where data read in Node.js environments are wrapped in standard `ArrayBuffer`s.

All-in-all, without additional information there doesn't appear to be much that can/should be done here.
