### ISSUE TITLE
Browser caching does not work with range request set for Firefox

### ISSUE THREAD

**Issue by docduo** [mozilla/pdf.js#11599]
Dear PDF.JS contributors,

When range requests are set and http server configured to cache contents with `public, max-age=31536000, immutable,` browser caching does not work on Firefox but strangely it works on Chrome or Safari. 

**Attach (recommended) or Link to PDF file here**: not file specific, but one can use https://public.fays.io/public/c80f5905-e4aa-4df3-8fa8-ab2dd3d04320.pdf

The server configuration is:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, PUT, POST
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Length, x-amz-request-id, x-amz-id-2, ETag
Access-Control-Max-Age: 31536000
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Cache-Control: public, max-age=31536000, immutable
```

**Configuration:**

    Web browser and its version: Firefox 73.0
    Operating system and its version: mac os x 10.15.3 
    PDF.js version: 2.2.228
    Is a browser extension: no

**Steps to reproduce the problem:** 

1. clear the browser cache
2. go to https://app.fays.io/fd7be64d-ec78-4731-9dff-7b9c8088acf9 and open the developper tool
3. refresh the page, the range request works fine but they are not cached by Firefox (private browser cache: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching)

**What is the expected behavior?**

On Chrome, when one refreshes the page, the range requests have been cached.
![Capture d’écran 2020-02-14 à 22 04 47](https://user-images.githubusercontent.com/56165819/74567427-0e20fe80-4f76-11ea-9674-e9f522dd4d10.png)
![Capture d’écran 2020-02-14 à 22 26 15](https://user-images.githubusercontent.com/56165819/74568803-1f1f3f00-4f79-11ea-9694-6551995ddb73.png)
A page refresh leads to:
![Capture d’écran 2020-02-14 à 23 49 30](https://user-images.githubusercontent.com/56165819/74574665-b4740080-4f84-11ea-9bff-c7e1bc1003fa.png)

**What went wrong?** 

On Firefox, the range requests are not cached by the private browser cache.
Also, Firefox performs in this example a 1.2MB download because the first range request has `Range: bytes=1577535-` and the response header has a code 206. 

On the other hand, PDF.JS on Chrome requests `bytes=0-262143` and the response header has a code 200. 

I don't know why it behaves differently.

![Capture d’écran 2020-02-14 à 22 02 34](https://user-images.githubusercontent.com/56165819/74567281-bbdfdd80-4f75-11ea-8844-4580a137255d.png)
![Capture d’écran 2020-02-14 à 22 26 49](https://user-images.githubusercontent.com/56165819/74568813-23e3f300-4f79-11ea-90b5-a390a277d64e.png)

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): **
https://app.fays.io/fd7be64d-ec78-4731-9dff-7b9c8088acf9

Best, A.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, the likelihood that someone will assist you is a lot greater with a *small and self-contained* example (rather than a larger viewer); please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel

**Comment by docduo** [comment]
@Snuffleupagus Of course, I have updated the description.

**Comment by docduo** [comment]
Also, 
When `disableAutoFetch is false` and `disableStream is false`, Firefox caches correctly the request with response code 200 but not 206.. with the same file.

![Capture d’écran 2020-02-15 à 00 24 32](https://user-images.githubusercontent.com/56165819/74576070-ba201500-4f89-11ea-850c-7b84eeb2b522.png)

**Comment by Snuffleupagus** [comment]
Given that caching is controlled by the *browser* itself, I'm not really sure that this is actually an actionable bug for the PDF.js library.
If anything, it sounds more like a (possibly general) bug in Firefox and I'd thus suggest reporting it in Bugzilla instead.

**Comment by docduo** [comment]
I found other online services where range requests are cached such that https://www.jango.com/music/Skarow for example.

**Comment by timvandermeij** [comment]
Yes, this is probably best reported at Bugzilla because it seems like a browser issue that we cannot resolve. Thanks!

**Comment by docduo** [comment]
For follow up: https://bugzilla.mozilla.org/show_bug.cgi?id=1615698
