### ISSUE TITLE
PDF.JS not working in Microsoft Edge but in Chrome

### ISSUE THREAD

**Issue by julianlaibach** [mozilla/pdf.js#11614]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge 17.1
- Operating system and its version: Windows 10
- PDF.js version: newest
- Is a browser extension:

Steps to reproduce the problem:
1. The Pdf is not loaded Properly, only Console log is SCRIPT0: SCRIPT0: Script Error
2. The URL of the PDF is rightly set and in Chrome it works without any Problems

What is the expected behavior? (add screenshot)
The PDF should be rendered and loaded

What went wrong? (add screenshot)
![Bildschirmfoto 2020-02-18 um 10 07 00](https://user-images.githubusercontent.com/53005042/74720668-6ab24100-5236-11ea-935e-553988964b70.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://healthjobs.ch/inserate/sachbearbeiter-in-finanzbuchhaltung-80/

**Comment by Snuffleupagus** [comment]
> PDF.js version: newest

Please provide actual version numbers, since "newest" is unfortunately of no use since it could mean any number of things (e.g. the latest stable release, the latest pre-release, or the latest `master` version).

**Comment by julianlaibach** [comment]
Sorry about that, i´m using the Version from this source //mozilla.github.io/pdf.js/build/pdf.js not sure what Version it is, since i tried using a hosted one from cdn i´m getting this error: message_handler.js:113 Uncaught Error: Unknown action from worker: undefined
    at Worker.MessageHandler._onComObjOnMessage (message_handler.js:113)

**Comment by Snuffleupagus** [comment]
> i´m using the Version from this source //mozilla.github.io/pdf.js/build/pdf.js

Do you mean that you're linking *directly* to that file? If so, please do *not* do that!
It's generally advised to use *official* releases, rather than anything else, please see https://github.com/mozilla/pdf.js/releases

> since i tried using a hosted one from cdn i´m getting this error:

Most likely, you tried to use different versions of the `pdf.js` and `pdf.worker.js` files, which is *not* supported.

---

If using an official release doesn't already fix things, then please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by julianlaibach** [comment]
Thank you for your help, new to that all.. Now integrated the worker and pdf.js... since that it works! Thank you for your time
Greetings Julian
