### ISSUE TITLE
PDFs containing pages with high resolution TIFFs render slowly

### ISSUE THREAD

**Issue by zxqx** [mozilla/pdf.js#11612]
**Attach (recommended) or Link to PDF file here**: [TEST.pdf](https://github.com/mozilla/pdf.js/files/4216176/TEST.pdf) - a contrived document containing pages with high resolution TIFFs (6592x5100)

**Configuration**:

- Web browser and its version: Chrome 80.0.3987.87
- Operating system and its version: macOS Mojave (10.14.6)
- PDF.js version: v2.3.200 _and_ latest unstable
- Is a browser extension: No

**Steps to reproduce the problem**:
1. Upload [TEST.pdf](https://github.com/mozilla/pdf.js/files/4216176/TEST.pdf) using the [Mozilla PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Scroll down to the last page

**What is the expected behavior?** The last page renders in a reasonable amount of time.

**What went wrong?** The last page takes ~15-30 seconds to render.

![Screen Shot 2020-02-17 at 3 12 20 PM](https://user-images.githubusercontent.com/1393139/74686728-02148700-5198-11ea-9dad-35eb6ea3b212.png)

**Comment by Snuffleupagus** [comment]
Rendering times improved significantly with PR #17946 (almost 50% in my quick tests), which combined with the pre-existing caching of global image-data means that we've done everything that we realistically can to fix this.
