### ISSUE TITLE
GlobalWorkerOptions is not defined 

### ISSUE THREAD

**Issue by Rui90** [mozilla/pdf.js#11611]
Hello,

I have the following code on my solution:

    const pdfjs = await import("pdfjs-dist/build/pdf");
    const pdfjsWorker = await import("pdfjs-dist/build/pdf.worker.entry");
    pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;

And this works perfectly in every browser except IE. On IE GlobalWorkerOptions = undifined, so I can't access workerSrc. Any ideia of why this is happening only on IE and what the solution might be? I already tried some different approaches, but I'm out of ideias.

**Comment by Snuffleupagus** [comment]
> And this works perfectly in every browser except IE

Well, the included snippet contains lots of code which IE cannot run natively...

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support;
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.
