### ISSUE TITLE
Browser caching does not work with range request set for Chrome when ranges overlap.

### ISSUE THREAD

**Issue by docduo** [mozilla/pdf.js#11622]
Dear contributors,

When one activate range requests with `disableAutoFetch: true` and `disableStream: true` and http server configured to cache contents with `public, max-age=31536000, immutable,` browser caching does work on Chrome.

But it does not work in all cases, basically when ranges overlap and some ranges are also requested after refreshing the tab.

**Attach (recommended) or Link to PDF file here**: not file specific, but one can use https://public.fays.io/public/580af700-5f79-44c4-8a0c-f7e976ee528f.pdf

The server configuration is:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, HEAD, PUT, POST
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Length, x-amz-request-id, x-amz-id-2, ETag
Access-Control-Max-Age: 31536000
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Cache-Control: public, max-age=31536000, immutable
```

**Configuration:**

    Web browser and its version: Chrome 80.0.3987.116
    Operating system and its version: mac os x 10.15.3 
    PDF.js version: 2.2.228
    Is a browser extension: no

**Steps to reproduce the problem:** 

1. Clear the browser cache
2. Go to https://app.fays.io/0edbaf68-35c6-4400-9838-b8a4e4a8a80b and open the developper tool. This viewer should work like the integrated viewer of PDF.JS
3. Navigate directly to the last page of the document page 76 using the green bar. The browser requests range requests for those pages and it works perfectly fine.
4. Then, refresh the tab, the ranges for page 1 have been cached. Then go directly to page 21.
5. Please, refresh the tab again. The browser cache has been cleared for this URL. Therefore the browser downloads the range requests for page 1 again..

**What is the expected behavior?**
The expected behavior is that the browser, once it caches a range request, does not download the same range later on. And that the browser does not clear the cache for the URL when range requests overlap. There should be another way to clear a cache but not this one.

**What went wrong?** 
For step 1. 2. 3. the following range requests are downloaded:
```
Page 1 DOWNLOAD
0-65535
65536-1638399
1638400-1769471
1769472-1835007
6946816-7012351
7012352-7031239
```

```
Page 76 DOWNLOAD
5177344-5242879
5242880-5308415
5308416-5373951
5373952-5439487
5505024-5570559
5570560-5636095
5636096-5701631
5701632-5767167
5767168-5832703
5832704-5898239
6094848-6160383
6422528-6488063
```

For step 4. the browser reloads the range requests for page 1.
```
Page 1 CACHE
0-65535
6946816-7012351
7012352-7031239
1769472-1835007
1638400-1769471
65536-1638399
```
And when one goes to page 21, the browser downloads the following range requests:
```
Page 21 DOWNLOAD
1900544-1966079
1966080-2031615
2031616-2097151
2097152-2162687
2162688-2228223
2228224-2293759
2293760-2359295

2490368-2555903
2555904-2621439
2621440-2686975

2818048-2883583
2883584-2949119
2949120-3145727

5898240-6029311
6029312-6094847
6094848-6160383
6160384-6422527
6422528-6488063
```

So, why does the browser clears or resets the cache for this URL at step 5?

One has checked many times and it occurs when ranges are overlapping.

In this example when one looks at the requested ranges, there is:
![chart](https://user-images.githubusercontent.com/56165819/75095137-48038d80-5592-11ea-97ee-91c4c894c65e.png)

Black color: 2 ranges for page 1
Blue color: 4 ranges for page 76
Red color: 4 ranges for page 21

When the browser requests page 21, it downloads a range that has been partially requested before, because both pages have common resources like fonts (where the blue and red lines intersect). 

It looks like the browser delete the cache entry because of this behavior. 

I am not going to dive into Chrome source code, but maybe is there a way to get around this unsatisfying behavior directly on PDF.JS ?

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): **
https://app.fays.io/0edbaf68-35c6-4400-9838-b8a4e4a8a80b

Best, A.

**Comment by Snuffleupagus** [comment]
Quoting myself from https://github.com/mozilla/pdf.js/issues/11599#issuecomment-586612729:
> Given that caching is controlled by the browser itself, I'm not really sure that this is actually an actionable bug for the PDF.js library.

Again, you'll need to report these kind of issues to the *browser vendor* rather than here.

**Comment by docduo** [comment]
> Quoting myself from [#11599 (comment)](https://github.com/mozilla/pdf.js/issues/11599#issuecomment-586612729):
> 
> > Given that caching is controlled by the browser itself, I'm not really sure that this is actually an actionable bug for the PDF.js library.
> 
> Again, you'll need to report these kind of issues to the _browser vendor_ rather than here.

I was wondering if this behavior related to range requests for pdf is an expected behavior. Is it possible to avoid requesting ranges when they overlap ?

**Comment by Snuffleupagus** [comment]
Once more, it's the *browser* that decides whether to cache network requests and *not* the PDF.js library (or any other JavaScript application).
You'll need to address further questions and/or bug reports to the *browser* developers!

**Comment by docduo** [comment]
Ok @Snuffleupagus thank you! I report here for follow up: https://bugs.chromium.org/p/chromium/issues/detail?id=1055075

**Comment by docduo** [comment]
Still, is it necessary to request the same ranges multiple times ?
