### ISSUE TITLE
missing file - pdfjs-2.2.228-dist 

### ISSUE THREAD

**Issue by flatwhite-4ever** [mozilla/pdf.js#11627]
just installed the pdf.js; when open pdfjs-2.2.228-dist > web > viewer.html, it says:" Missing PDF "file:///Users/xxxx/pdfjs-2.2.228-dist/web/compressed.tracemonkey-pldi-09.pdf". "  
can anyone help me with the issue? Thx.

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

> "file:///Users/xxxx/pdfjs-2.2.228-dist/web/compressed.tracemonkey-pldi-09.pdf"

It's possible that your problem, and its solution, is already explained in the README; see https://github.com/mozilla/pdf.js#getting-the-code
