### ISSUE TITLE
pdf preview download online, Google Chrome download content is fuzzy

### ISSUE THREAD

**Issue by bairuyu111** [mozilla/pdf.js#11633]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. When printing online through Google Chrome, the printed content is fuzzy and unclear.
2.After testing various browsers, it was found that the kernel-based browsers such as Google and Sogou have fuzzy printing problems online. Firefox's online printing is clear. This problem does not exist.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, in the *very* limited information provided thus far there's really nothing indicating that this is a valid bug in PDF.js repository.
