### ISSUE TITLE
A certain PDF is not rendered only on iOS

### ISSUE THREAD

**Issue by wada-b4** [mozilla/pdf.js#11635]
The attached PDF is not rendered properly only on iOS. It's OK for other platforms.

Attach (recommended) or Link to PDF file here:
[not-rendered-properly-on-iphone.pdf](https://github.com/mozilla/pdf.js/files/4261341/not-rendered-properly-on-iphone.pdf)

Configuration:
- Web browser and its version:
Chrome, Safari
- Operating system and its version:
iOS 13.3.1

- PDF.js version:
v1.9.426
v2.2.228

- Is a browser extension:
No

Steps to reproduce the problem:
1.  Open and render the attached file by PDF.js on iOS

What is the expected behavior? (add screenshot)
The file should be rendered like this:
<img src="https://user-images.githubusercontent.com/25608910/75441560-3ca0cf80-59a1-11ea-8a9b-5eac07b07d19.png" width="200px">

What went wrong? (add screenshot)
Nothing is drawn on iOS

This screen shot is the demo on iOS with the PDF.

<img src="https://user-images.githubusercontent.com/25608910/75506394-3c481900-5a21-11ea-9d1a-d08112628c40.png" width="200px">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
None

Added on 2020-03-05:
We got this right result in 7 minutes after opening the file.

<img src="https://user-images.githubusercontent.com/25608910/75942588-22517f00-5ed6-11ea-8a86-7f1ecbc4aed7.png" width="200px">

**Comment by wada-b4** [comment]
We got a right result in 7 minutes after opening the file. I added a scrrenshot.

**Comment by Snuffleupagus** [comment]
> The attached PDF is not rendered properly only on iOS. It's OK for other platforms.

That clearly suggests a platform/browser bug (e.g. `canvas`-related), rather than a PDF.js one, and as such it's unfortunately very difficult to see that it's actionable/fixable *here*; hence I'd suggest closing this issue.
