### ISSUE TITLE
Get computed scale value from auto, page-fit etc

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#11649]
I wish to ask if there is some helper function in pdf.js that outputs the computed scale value for the dropdown selection that outputs 'auto', 'page-fit' etc?

Tried to look in viewer.js but could not find it. maybe a feature request?

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/blob/d60c1f68b7596d32b0784c368c231655c4a2fc6f/web/base_viewer.js#L295-L302

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by chitgoks** [comment]
i found a workaround for my use case. thanks snuffle.

this is not an issue so i thought there is no need to use an issue template. next time i will.
