### ISSUE TITLE
Memory leak on node.js in page.getOperatorList()

### ISSUE THREAD

**Issue by tedgoddard** [mozilla/pdf.js#11645]
Attach (recommended) or Link to PDF file here:

https://steamcdn-a.akamaihd.net/apps/valve/Valve_NewEmployeeHandbook.pdf

Configuration:
 - node.js v13.9.0
- Operating system and its version: macOS 10.15.3 and Ubuntu 18.04
- PDF.js version: 2.2.228 and 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
1. Run attached script (named index.txt to comply with GitHub attachments). 
2. Observe that memoryUsage.arrayBuffers increases to a high value and the process memory exceeds 1GB
2. For a limited workaround, uncomment line 34. This creates a new doc instance for each page. The performance impact for this is not significant for this size of file, but is not desirable in general. This is also a likely clue for the bug if the ArrayBuffers are being attached to the document instance.

What is the expected behavior? (add screenshot)

Process memory should remain bounded as pages are processed.

What went wrong? (add screenshot)

Process memory increases as more pages are processed. 

[index.txt](https://github.com/mozilla/pdf.js/files/4269128/index.txt)

**Comment by Snuffleupagus** [comment]
> index.txt

Looking at that code there is, as far as I can tell, no attempt to clean-up resources once they're no longer needed.
Hence, once you're done with a page you need to call its `cleanup` method to release allocated resources; please see https://github.com/mozilla/pdf.js/blob/ed47f77527b0dd1647c7cd05cd59e816a176df9e/src/display/api.js#L1371-L1381

Failing to call `page.cleanup()` will cause e.g. image resources to be kept alive, which in documents with many large images will add up memory wise. Hence adding `await page.cleanup();` *after* line `await convertPageToObjects(page)` ought to help here.
