### ISSUE TITLE
Is there a way to combine multiple PDF files in the same container

### ISSUE THREAD

**Issue by devhatem** [mozilla/pdf.js#11648]

**Comment by Snuffleupagus** [comment]
No.

*For future refenerence:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Snuffleupagus** [comment]
No.

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
