### ISSUE TITLE
Some characters are not displayed in this PDF.

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#11652]
Attach (recommended) or Link to PDF file here:

Configuration:
[haha.pdf](https://github.com/mozilla/pdf.js/files/4275832/haha.pdf)

- Web browser and its version: Chrome80
- Operating system and its version: Mac10.14.6
- PDF.js version: 2.1.183
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attachment With PDF.js.
2. Open the attachment With Chrome.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/18492951/75685430-80634400-5cd5-11ea-933c-01e72bb674d2.png)

What went wrong? (add screenshot)
Some characters are not displayed.
![image](https://user-images.githubusercontent.com/18492951/75685507-9f61d600-5cd5-11ea-883f-654c0e8e0fa0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by brendandahl** [comment]
Fixed by #12186
