### ISSUE TITLE
Parenthesis with hebrew text not rendering in the correct way

### ISSUE THREAD

**Issue by kfir91** [mozilla/pdf.js#11656]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/4281200/test.pdf)

Configuration:
- Web browser and its version: Google Chrome 80.0.3987.122 
- Operating system and its version: Windows 10 64 bit
- PDF.js version: 2.0.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Open hebrew pdf file
2. Set locale to he-IL (#locale=he-IL)
3. Set textLayer to visible (#textLayer=visible)
4. The parenthesis rendering wrong.

What is the expected behavior? (add screenshot)

![1](https://user-images.githubusercontent.com/11144887/75774759-4c316700-5d59-11ea-900c-986a5697ca4b.PNG)

What went wrong? (add screenshot)

![2](https://user-images.githubusercontent.com/11144887/75774763-505d8480-5d59-11ea-82af-afaf5ba66972.PNG)

like can you see the rendering of the parenthesis wrong 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
There is no link

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

That part of the issue template is *required* in order for the issue to be actionable/valid; as-is the issue would be closed as incomplete.

> PDF.js version: The new one

Please provide *actual* version numbers, since "The new one" is unfortunately of no use since it could mean any number of things (e.g. the latest stable release, the latest pre-release, or the latest master version).

**Comment by Snuffleupagus** [comment]
> PDF.js version: The new one

Please provide *actual* version numbers, since the above is unfortunately of no use since it could mean any number of things (e.g. the latest stable release, the latest pre-release, or the latest `master` version).

**Comment by kfir91** [comment]
> > PDF.js version: The new one
> 
> Please provide _actual_ version numbers, since the above is unfortunately of no use since it could mean any number of things (e.g. the latest stable release, the latest pre-release, or the latest `master` version).

ok i changed it...

**Comment by Snuffleupagus** [comment]
> ok i changed it...
>
> PDF.js version: 2.0.0

That particular version number has never existed, hence the provided information is unfortunately *still* incomplete/confusing.

**Comment by kfir91** [comment]
> > ok i changed it...
> > PDF.js version: 2.0.0
> 
> That particular version number has never existed, hence the provided information is unfortunately _still_ incomplete/confusing.

There is no version in the readme.md file. i downloaded the code yesterday its the latest master version.

**Comment by THausherr** [comment]
It works fine for me with FF or Chrome with the latest PDF.js version (2.4.432) on W10. However I did not do these steps:

```
Set locale to he-IL (#locale=he-IL)
Set textLayer to visible (#textLayer=visible)
```
