### ISSUE TITLE
TJ operation without text but only offsets breaks rending

### ISSUE THREAD

**Issue by jsiefer** [mozilla/pdf.js#11651]
Attach (recommended) or Link to PDF file here:

Configuration:
- Creator/Producer: typeset.sh
- Firefox 73.0.1 (64-bit)
- macOS Catalina (10.15.3)
- PDF.js: 2.4.254
- Is a browser extension: YES

Steps to reproduce the problem:
A PDF operation with a not quite valid TJ operation that only contains offsets breaks the rest of the page.

Open PDF
[inline-block2.actual.pdf](https://github.com/mozilla/pdf.js/files/4275710/inline-block2.actual.pdf)
```
stream
q
1 0 0 1 0 300 cm
BT
1 0 0 1 0 -20.82 Tm
[-3092 -3343] TJ #invalid - but should not break
ET
Q
```

What is the expected behavior?
Skip the operation and continue rendering as normal.
<img width="200" alt="expected" src="https://user-images.githubusercontent.com/6014388/75681693-69e8c880-5c94-11ea-81be-4e5326a6a59d.png">

What went wrong? (add screenshot)
<img width="200" alt="actual" src="https://user-images.githubusercontent.com/6014388/75681727-79681180-5c94-11ea-90ae-f80005792358.png">

**Comment by Snuffleupagus** [comment]
> ```
> stream
> q
> 1 0 0 1 0 300 cm
> BT
> 1 0 0 1 0 -20.82 Tm
> [-3092 -3343] TJ #invalid - but should not break
> ET
> Q
> ```

The PDF document is corrupt even before the referenced line, since there must be a `Tf` (i.e. setFont) operator before the first text rendering operator.

**Comment by jsiefer** [comment]
That is true, yes

As I said, the PDF is not valid here - I just noticed that other viewers don't seem to mind that issue, thought maybe I report it.
