### ISSUE TITLE
Currently pdf when open in new tab displays angular logo as favicon, can it be changed 

### ISSUE THREAD

**Issue by UrvilMehta** [mozilla/pdf.js#11650]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The favicon is specified by the server, hence this isn't a valid PDF.js issue (note also below).

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
