### ISSUE TITLE
pdf with backgroun image not shoing 

### ISSUE THREAD

**Issue by afahmyintegral** [mozilla/pdf.js#11666]
Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/7492723/test.pdf)

Configuration:
- I tried in chrome , edge and firefox
- Windows 10 latest version
- PDF.js version latest I tried via the demo link :
- Is a browser extension:no

Steps to reproduce the problem:
1. open the file from the link above the background not showing 
2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/33306459/75962233-d0f8be00-5edc-11ea-8f00-483e54e1ad21.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/33306459/75962256-e0780700-5edc-11ea-8acd-5bbb8e37d6e7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by a7vickey** [comment]
They dont know how to fix this issue.

**Comment by T-roy69** [comment]
Unsubscribe what

**Comment by T-roy69** [comment]
I've shared an item with you:

.candycan
https://drive.google.com/file/d/1-XgAht4jhKpjMkYTQw1tKZ9EQOyWd015/view?usp=sharing&invite=CM__4JAH&ts=5e7dc003

It's not an attachment -- it's stored online. To open this item, just click  
the link above.
