### ISSUE TITLE
Option to remove header and footer rendering

### ISSUE THREAD

**Issue by kfir91** [mozilla/pdf.js#11662]
Hello,
there is any option to remove header and footer rendering?
when i copy text from end of page to start of the next page i will want that its not copy the footer in the end of the page and the header in the start of the next page.

Tnx

**Comment by Snuffleupagus** [comment]
> there is any option to remove header and footer rendering?

No; and it's not something that can/will be added either since it's *generally impossible* to detect a e.g. a header/footer (given that e.g. all text is rendered with "normal" text rendering operators, which has no context of what the text represents in the document).
