### ISSUE TITLE
Extra white spaces between words

### ISSUE THREAD

**Issue by huzjakd** [mozilla/pdf.js#11670]
Attach (recommended) or Link to PDF file here:
[page.pdf](https://github.com/mozilla/pdf.js/files/4297690/page.pdf)

Configuration:
- Web browser and its version: Any browser (but try e.g. Chrome), latest version.
- Operating system and its version: Windows 10, the latest version
- PDF.js version: I believe it is the latest: 2.2.228
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached pdf page in the default demo pdf viewer: https://mozilla.github.io/pdf.js/web/viewer.html
2. Search for "Private" or "Equity"
3. The words: "Private" and "Equity" at the top don't get correctly highlighted.
4. This seems to be because extra white spaces are inserted between the words but also on the left and the right of them.
5. Is there anything that can be done about this?

What is the expected behavior? (add screenshot)
Words "Private" and "Equity" get correctly highlighted.

What went wrong? (add screenshot)
Words not correctly highlighted.
![Screenshot_1](https://user-images.githubusercontent.com/10630729/76073916-b4bb5680-5f9a-11ea-9e80-19189b7c08ca.png)
![Screenshot_2](https://user-images.githubusercontent.com/10630729/76073919-b553ed00-5f9a-11ea-833c-f144a172d24c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by luomancs** [comment]
> Attach (recommended) or Link to PDF file here:
> [page.pdf](https://github.com/mozilla/pdf.js/files/4297690/page.pdf)
> 
> Configuration:
> 
> * Web browser and its version: Any browser (but try e.g. Chrome), latest version.
> * Operating system and its version: Windows 10, the latest version
> * PDF.js version: I believe it is the latest: 2.2.228
> * Is a browser extension: no
> 
> Steps to reproduce the problem:
> 
> 1. Open the attached pdf page in the default demo pdf viewer: https://mozilla.github.io/pdf.js/web/viewer.html
> 2. Search for "Private" or "Equity"
> 3. The words: "Private" and "Equity" at the top don't get correctly highlighted.
> 4. This seems to be because extra white spaces are inserted between the words but also on the left and the right of them.
> 5. Is there anything that can be done about this?
> 
> What is the expected behavior? (add screenshot)
> Words "Private" and "Equity" get correctly highlighted.
> 
> What went wrong? (add screenshot)
> Words not correctly highlighted.
> ![Screenshot_1](https://user-images.githubusercontent.com/10630729/76073916-b4bb5680-5f9a-11ea-9e80-19189b7c08ca.png)
> ![Screenshot_2](https://user-images.githubusercontent.com/10630729/76073919-b553ed00-5f9a-11ea-833c-f144a172d24c.png)
> 
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):


Hi, 

do you have solution for this issue? I have similar problem, my search query has one space between each word, but the pdf have two spaces, so it can not search my query. if you have a solution to this problem, could you post it? thank you.

**Comment by huzjakd** [comment]
@luomancs No, unfortunately still no solution.

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
