### ISSUE TITLE
Unsupported ShadingType

### ISSUE THREAD

**Issue by 296500148** [mozilla/pdf.js#11679]
how to solve this problem？
[第二课时 找一个数的因数和倍数.pdf](https://github.com/mozilla/pdf.js/files/4305035/default.pdf)
The background of this pdf is a bit special

**Comment by Snuffleupagus** [comment]
Duplicate of #5046.

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by 296500148** [comment]
Can I change this color? Pink looks too noticeable ...
