### ISSUE TITLE
bad XRef entry

### ISSUE THREAD

**Issue by 296500148** [mozilla/pdf.js#11678]
How to discard the problematic data so that no errors can affect the rendering of the entire page

**Comment by 296500148** [comment]
Documents need to be signed and time-sensitive,so...sorry,cannot give a valid connection,and I don't know how to upload files

**Comment by 296500148** [comment]
I looked at the source code and found that only a certain piece of data caused a problem that page pdf could not render

**Comment by 296500148** [comment]
[力已转档.pdf](https://github.com/mozilla/pdf.js/files/4304559/default.pdf)

**Comment by 296500148** [comment]
Or is there a better solution?

**Comment by Snuffleupagus** [comment]
The PDF document is corrupt enough that even Adobe Reader (i.e. the PDF reference implementation) cannot render all of it completely.

*For future reference:* When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by 296500148** [comment]
Select the file opening method for chrome to open normally,so...can this problem be solved?

**Comment by 296500148** [comment]
Select the file opening method for chrome(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36") to open normally. so...whether this problem can be solved, or can't handle this problem with pdf.js
