### ISSUE TITLE
PDF.js cannot open files with '%' in their name

### ISSUE THREAD

**Issue by wenjie-xie** [mozilla/pdf.js#11683]
Attach (recommended) or Link to PDF file here: Any PDF file with '%' in it's name, for example "100%ConcentrationTestResults.pdf"

Configuration:
- Web browser and its version: Firefox  73.0
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
1. Run the most recent build of pdf.js
2. Place the PDF with '%' in it's name in the local /test/pdfs/ folder
3. Navigate to the https://localhost:8888/test/pdfs/ and open the document you placed in it.

What is the expected behavior? (add screenshot): Open the PDF document properly

What went wrong? (add screenshot): PDF fails to open
![image](https://user-images.githubusercontent.com/36047618/76259440-fb73af80-622b-11ea-8202-5eec2bf2b163.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A, it was run locally while I was testing something else.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file
