### ISSUE TITLE
Incorrect printing on FireFox

### ISSUE THREAD

**Issue by krzbor** [mozilla/pdf.js#11682]
I'm using version 2.2.228. In the FireFox (73.0.1) browser, after printing I have a document like this:
![ff](https://user-images.githubusercontent.com/4522029/76249101-ebb39580-6242-11ea-8ba4-24260ef3de04.jpg)
The same printout from the Chrome browser:
![chrome](https://user-images.githubusercontent.com/4522029/76249122-fff79280-6242-11ea-8b8c-86c3adf366e0.jpg)

Both prints were made using Microsoft Print to PDF. My question - why is the printout on FireFox incorrectly scaled?

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md. In this case, clear and concise steps to reproduce the problem is seem especially important for this issue to be valid.

**Comment by krzbor** [comment]
Problem solved! I had a 125% printing scale selected in FireFox. I didn't know that it affected PDF printing. When printing PDF, you cannot see the scale set in FF.
