### ISSUE TITLE
I used the cmaps, but display box

### ISSUE THREAD

**Issue by Shaxin742** [mozilla/pdf.js#11684]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chorm
- Operating system and its version: vue ^2.5.0
- PDF.js version: 2.2.228
- Is a browser extension:

Steps to reproduce the problem:
1. **the cMapUrl i used the url it worked, but when i used the local path it display none**
2.**in the company work  i can only use the 2.0.943. the version 2.2.228 caused an error**

What is the expected behavior? (add screenshot)
![企业微信截图_1583919808169](https://user-images.githubusercontent.com/23325831/76403412-d9ab3180-63bf-11ea-9562-0662d18e4138.png)

What went wrong? (add screenshot)

when i download these in my project

![image](https://user-images.githubusercontent.com/23325831/76403515-fb0c1d80-63bf-11ea-953b-1e0d61dabf19.png)

**the cMapUrl i used the url it worked**
![image](https://user-images.githubusercontent.com/23325831/76377552-21ad6280-6386-11ea-9699-69050cfd2cf6.png)
![image](https://user-images.githubusercontent.com/23325831/76377756-ae582080-6386-11ea-9c95-5c52998a9315.png)

**while i used the local path it display none**
![image](https://user-images.githubusercontent.com/23325831/76377639-5faa8680-6386-11ea-9c44-2938f848f0fd.png)
![image](https://user-images.githubusercontent.com/23325831/76377725-997b8d00-6386-11ea-9739-2f2058410fe6.png)

my code
![image](https://user-images.githubusercontent.com/23325831/76378260-f75ca480-6387-11ea-9354-2aa945c72740.png)

`
  <div class="pdf-preview-container">
    <div
      ref="container"
      class="page-container"
      :style="{
        height: `${pageHeight}px`
      }"
    >
      <canvas />
    </div>
  </div>

<script>
import pdfJS from 'pdfjs-dist'；

import data from './kkk.json'；
const cMapUrl = '../../../node_modules/pdfjs-dist/cmaps/'；
export default {
  props: {
    url: {
      type: String,
      required: true
    },
    pageNo: {
      type: Number,
      required: true
    }
  },
  data () {
    return {
      doc: null,
      pageHeight: 0,
      renderList: [],
      notice: ''
    }
  },
  watch: {
    url: {
      immediate: true,
      handler (value) {
        this.getPDFFile()
      }
    }
  },
  methods: {
    getPDFFile () {
      if (!this.url) return
      pdfJS.getDocument({
        url: data.data,
        cMapUrl: cMapUrl,
        cMapPacked: true
        // CMapReaderFactory: {}
        // disableFontFace: true
      }).then(pdf => {
        this.doc = pdf
        this.$nextTick(() => {
          this.renderPage(this.pageNo)
        })
      })
    },
    // 渲染page
    renderPage (pageNo) {
      this.doc.getPage(pageNo).then(page => {
        const container = this.$refs.container
        if (!container) return
        const canvas = container.querySelector('canvas')
        if (!canvas) return
        const ctx = canvas.getContext('2d')
        const dpr = window.devicePixelRatio || 1
        const bsr = ctx.webkitBackingStorePixelRatio || ctx.mozBackingStorePixelRatio || ctx.msBackingStorePixelRatio || ctx.oBackingStorePixelRatio || ctx.backingStorePixelRatio || 1
        const ratio = dpr / bsr
        const rect = container.getBoundingClientRect()
        const viewport = page.getViewport(1)
        const width = rect.width
        const height = width / viewport.width * viewport.height
        canvas.style.width = `${width}px`
        canvas.style.height = `${height}px`
        this.pageHeight = height
        canvas.height = height * ratio
        canvas.width = width * ratio
        ctx.setTransform(ratio, 0, 0, ratio, 0, 0)
        page.render({
          canvasContext: ctx,
          viewport: page.getViewport(width / viewport.width)
        })
      })
    }
  }
}
</script>
`

**another question here:**
**in the company work  i can only use the 2.0.943. the version 2.2.228 caused an error**
**about xhr**
![image](https://user-images.githubusercontent.com/23325831/76378138-a9e03780-6387-11ea-8f1e-6ad06eaf7c41.png)
**it does showed difference**

 **i can't find the error ..........................   where did i caused it....**

![image](https://user-images.githubusercontent.com/23325831/76295546-c597ff00-62ef-11ea-908c-cc9fd86db7fe.png)

the pdf used song font (宋体) so it does't work well
if the cMapUrl i white as the url 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.288/cmaps/'. it does like blocks
![image](https://user-images.githubusercontent.com/23325831/76295847-4c4cdc00-62f0-11ea-9af5-75d861c51b40.png)

it does troubled me a long times thanks

**Comment by Shaxin742** [comment]
![企业微信截图_1583830768682](https://user-images.githubusercontent.com/23325831/76296030-89b16980-62f0-11ea-89b9-0961d395912e.png)
![企业微信截图_15838308454177](https://user-images.githubusercontent.com/23325831/76296141-b8c7db00-62f0-11ea-87ea-ba7fb77eaad0.png)

**Comment by Shaxin742** [comment]
fuck  where's my photos

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *required* in order for the issue to be actionable/valid.
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Shaxin742** [comment]
i will update it lately,  i can't upload images now.......

**Comment by Shaxin742** [comment]
ok i updated it.

**Comment by Shaxin742** [comment]
![image](https://user-images.githubusercontent.com/23325831/76383938-6b06ad80-6398-11ea-8466-49f0a21eb4ae.png)
the same version does't work also

**Comment by Snuffleupagus** [comment]
This is still not addressing any of the points from https://github.com/mozilla/pdf.js/issues/11684#issuecomment-596975251 and as such this will be closed as incomplete/invalid.

**Comment by lyn1507** [comment]
兄弟，这个问题你解决了吗？也困扰了我好久。。。
