### ISSUE TITLE
Annotation render wrong position

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#11693]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 74.0 (32-bit)
- Operating system and its version: windows 8.1  
- PDF.js version: Version 2.0 
- Is a browser extension:

Steps to reproduce the problem:
1. Annotation popup show wrong position. please  find the  attached screenshot. 
 

What went wrong? ![annotation_wrong_position](https://user-images.githubusercontent.com/7369163/76592123-6406a900-6518-11ea-9229-e0c63b2b45ca.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This information is *required* in order for the issue to be actionable/valid, as-is this issue will be closes as INCOMPLETE.

> PDF.js version: Version 2.0

That particular version number has never existed.

**Comment by a7vickey** [comment]
what incomplete you dont have knowledge to understand. Annotation pop render wrong position.  their is no issue in annotation 100% perfect no bug on annotation. i am only create the i need to decide issue is  resolved or not.

**Comment by a7vickey** [comment]
https://github.com/mozilla/pdf.js/issues/11286
