### ISSUE TITLE
Large blocks of text isn't being rendered

### ISSUE THREAD

**Issue by nkristoffersen** [mozilla/pdf.js#11697]
I'm using PDF.js to render many different PDFs from many different sources, but this particular source PDFs has issues for some reason. It also fails to fully render in Firefox directly. Chrome handles this PDF fine somehow. I've been struggling to find the root cause and solution over the past few days. Any help our guidance? I presume it is a faulty PDF but doubt I can ask the source to change their workflow.

Attach (recommended) or Link to PDF file here:
[051325202001172HfYHE46U6xM2Ywwht0S8C4A000401010900.pdf](https://github.com/mozilla/pdf.js/files/4331272/051325202001172HfYHE46U6xM2Ywwht0S8C4A000401010900.pdf)

Configuration:
- Web browser and its version: Firefox 73.0.1
- Operating system and its version: macOS 10.15.3 (although reproducible in other OS)
- PDF.js version: latest
- Is a browser extension: latest

Steps to reproduce the problem:
1. Open attached PDF file in Firefox or PDF.js viewer or PDF.js extension
2. Missing text (which can be seen in Chrome)

What is the expected behavior? (add screenshot)
<img width="1920" alt="Screen Shot 2020-03-13 at 20 13 03" src="https://user-images.githubusercontent.com/8238056/76652855-b6bb8180-6567-11ea-8c0a-5d070e2e5279.png">

What went wrong? (add screenshot)
<img width="1920" alt="Screen Shot 2020-03-13 at 20 12 26" src="https://user-images.githubusercontent.com/8238056/76652866-be7b2600-6567-11ea-97e2-e01d8c6ba313.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Fixed by the pull request above. Thank you for providing us with detailed information!
