### ISSUE TITLE
Fullscreen mode two pages doesn't work

### ISSUE THREAD

**Issue by dag7dev** [mozilla/pdf.js#11708]
Attach (recommended) or Link to PDF file here: any

Configuration:
- Web browser and its version: 74.0 (64-bit)
- Operating system and its version: Ubuntu 19.10 Mate
- PDF.js version: good question, I think the latest one? I don't know but even in past/future version there is this problem too

Steps to reproduce the problem:
1. Open a random PDF
2. Put the visualizer into "two pages mode" (click top-right button, select "Odd spreads" or "Even spreads" is the same)
3. Enable fullscreen mode

What is the expected behavior? (add screenshot)
It goes fullscreen with two pages mode.

What went wrong? (add screenshot)
It goes fullscreen with just one page.

**Comment by Snuffleupagus** [comment]
> Enable fullscreen mode

If by that you're referring to the "Presentation Mode" button on the PDF viewer toolbar, then that is *purposely* intended to be a very simple mode without any UI and/or advanced features.

Please note however that if you're instead using the actual "Full Screen" mode of the browser *itself*, which can be toggled with <kbd>F11</kbd>, then you've got access to the full PDF.js UI and functions.
