### ISSUE TITLE
2.2.228 version cannot display Chinese normally under ie11, but display normally under chrome

### ISSUE THREAD

**Issue by yuweiming2016** [mozilla/pdf.js#11701]
version 2.x can not show chinese normally，but 1.10.xxx can

1.10.xxx can display chinese normally  both ie11 and chrome
2.2.228 version cannot display Chinese normally under ie11, but display normally under chrome

did i miss something？

demo url：https://mozilla.github.io/pdf.js/es5/web/viewer.html
select pdf attach and open it

[check in it11 and chrome.pdf](https://github.com/mozilla/pdf.js/files/4335671/check.in.it11.and.chrome.pdf)

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by gzm1997** [comment]
> version 2.x can not show chinese normally，but 1.10.xxx can
> 
> 1.10.xxx can display chinese normally both ie11 and chrome
> 2.2.228 version cannot display Chinese normally under ie11, but display normally under chrome
> 
> did i miss something？
> 
> demo url：https://mozilla.github.io/pdf.js/es5/web/viewer.html
> select pdf attach and open it
> 
> [check in it11 and chrome.pdf](https://github.com/mozilla/pdf.js/files/4335671/check.in.it11.and.chrome.pdf)

hi, is there some solution to deal with this problem? 你好 请问对于中中文PDF在ie11上偶现乱码的现象有解决方案了吗 如果有是否可以告知 非常感谢

**Comment by brendandahl** [comment]
Interesting font failures:

```
downloadable font: glyf: Bad bounding box values bl=(224, 193), tr=(3, 7) in glyph 19254 (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: glyf: Failed to parse table (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f1': 'SyntaxError: An invalid or illegal string was specified'.
```
