### ISSUE TITLE
Incorrect rendering on macOS

### ISSUE THREAD

**Issue by skyline75489** [mozilla/pdf.js#11718]
Attach (recommended) or Link to PDF file here: https://pdos.csail.mit.edu/6.824/papers/vm-ft.pdf

Configuration:
- Web browser and its version: Firefox 74.0
- Operating system and its version: macOS 10.15.3
- PDF.js version:  PDF 1d2d2343d8fc3e49ada313170169d1a2 [1.5 Adobe PDF Library 8.0 / Adobe InDesign CS3 (5.0.2)] (PDF.js: 2.4.326)
- Is a browser extension: No, I guess.

Steps to reproduce the problem:
1. Open the PDF file in Firefox and check the second paragraph of "Introduction"

What is the expected behavior? (add screenshot)

![图片](https://user-images.githubusercontent.com/4710575/77150667-5c727180-6acf-11ea-8332-4a3fe6ea9733.png)

What went wrong? (add screenshot)

![图片](https://user-images.githubusercontent.com/4710575/77150696-71e79b80-6acf-11ea-94fc-e5535d76c51a.png)

**Comment by skyline75489** [comment]
The problem also exists on Firefox 68.6 ESR on Windows 10 x64.

**Comment by timvandermeij** [comment]
Thank you for reporting this. Fixed in the PR above.
