### ISSUE TITLE
Update https://www.npmjs.com/package/pdfjs-dist

### ISSUE THREAD

**Issue by KeithHenry** [mozilla/pdf.js#11712]
The npm distribution of this is at https://www.npmjs.com/package/pdfjs-dist and is on 2.2.228

That depends on https://github.com/mozilla/pdfjs-dist, which appears to be on 2.3.200

That repository doesn't accept issues, but is maintained by a bot from this one.

Please could someone with the right permissions publish https://github.com/mozilla/pdfjs-dist to https://www.npmjs.com/package/pdfjs-dist so that those of us using npm package distribution can access the current version?

**Comment by Snuffleupagus** [comment]
> The npm distribution of this is at https://www.npmjs.com/package/pdfjs-dist and is on 2.2.228

That's because that version is the current *stable* release, however the pre-release can be found at NPM with the `next` tag; see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

**Comment by KeithHenry** [comment]
@Snuffleupagus so is 2.3.200 not the current _stable_ release? I can't find documentation indicating that it is an unstable preview here, and it's about 6 months old. I would expect `next` to be 2.4.456

If 2.3.200 is not the current version should this repository reflect that 2.2.228 is?

**Comment by Snuffleupagus** [comment]
What I wrote in https://github.com/mozilla/pdf.js/issues/11712#issuecomment-601072441 was correct *at that time*.

> so is 2.3.200 not the current _stable_ release?

`2.3.200` is *now* the current stable release, see https://github.com/mozilla/pdf.js/releases, but because of (unknown) problems with NPM the tags didn't update correctly; this is already tracked in #11722.

**Comment by KeithHenry** [comment]
@Snuffleupagus OK, thanks.

**Comment by timvandermeij** [comment]
The `latest` and `next` tags on NPM have now been updated.
