### ISSUE TITLE
Stable version not pushed to NPM

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11722]
Yesterday we released beta version 2.4.456. This version was successfully pushed to NPM, but the stable version wasn't and is still at 2.2228 on NPM while it should be 2.3.200. Looking at the code this should have worked, and last release this did work, so I'm assuming something failed with contacting NPM.

@brendandahl Can you perhaps see what happened in logs, and push to NPM manually to give version 2.3.200 the `latest` tag? (The commits for `pdfjs-dist` did work this time after the recent pull request, so that was good to see.)

**Comment by brendandahl** [comment]
Updated npm, still cached on the site but should update soon.

I don't see anything in the logs about the release pr having issues.

**Comment by timvandermeij** [comment]
NPM has been updated in the meantime. Weird that it didn't work and nothing was logged, but thanks for fixing it manually!
