### ISSUE TITLE
PDFJS.externalLinkTarget settings stopped working

### ISSUE THREAD

**Issue by mariuszpala** [mozilla/pdf.js#11730]
Configuration:
- Web browser and its version: Chrome 79
- Operating system and its version: Mac and Windows
- PDF.js version: 2.3
- Is a browser extension: No

Steps to reproduce the problem:
1.  Modify viewer.html as follows:
`PDFViewerApplication.preferences.set('externalLinkTarget', 2); 
	PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;`
2. Open a PDF in it and click any link
3. Link is opened in _top not new window

What is the expected behavior? 
Links opening in new tab

What went wrong? 
The PDFJS.externalLinkTarget  setting used to work just fine in some previous release of PDFJS, it stopped working after recent update. I tried PDFViewerApplication.preferences but it doesn't work as well. 

![image](https://user-images.githubusercontent.com/12190923/77291410-7c2bb480-6cde-11ea-88db-cd260f73ab6e.png)

It works when I modify this setting in viewer.js
![image](https://user-images.githubusercontent.com/12190923/77291566-d0cf2f80-6cde-11ea-8030-c85fb6cc95c9.png)

What is the correct setting to change the externalLInkTarget to _BLANK besides modifying the core file?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.3

Sorry, but it's not entirely clear which *exact* PDF.js version you're referring to here. Please note that all PDF.js versions consist of *three* numbers, so did you perhaps mean `2.3.200` here (which as of this writing is the current stable release, see https://github.com/mozilla/pdf.js/releases).

> Modify viewer.html as follows:
> `PDFViewerApplication.preferences.set('externalLinkTarget', 2);

It's unfortunately *impossible* to tell what went wrong without a lot more information; please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---
> The PDFJS.externalLinkTarget setting used to work just fine in some previous release of PDFJS,

The `PDFJS` global was removed with the *first* release from the `2.x.y` branch of the library (specifically version `2.0.943`, which was released a year and a half ago).

> I tried `PDFViewerApplication.preferences` but it doesn't work as well.

That should work, so it's possible that you simply ran it too late (i.e. the value had already been read); again we'd need to see your actual code to tell.

**Comment by mariuszpala** [comment]
Thanks @Snuffleupagus , I understand now why the original PDFJS. part doesn't after upgrade from v 1.x. But I tried the other method as below - I simply modified viewer.html by adding a single line as on the screenshot below:
![image](https://user-images.githubusercontent.com/12190923/77359164-73bd9300-6d4b-11ea-8415-6a9fb962cd05.png)

Still links are opened in the same window. Could you guide me what should I do to make it work?

**Comment by mariuszpala** [comment]
If I move that highlighted line two lines below (after viewer.js), I still get the same issue on the console:

`Uncaught ReferenceError: PDFViewerApplication is not defined`

**Comment by mariuszpala** [comment]
OK, finally I found the solution for this, adding this code solves the problem. 
But I hope there is an easier way to set the settings in PDF.js?

```
	<script>
		function applyConfig() {
			PDFViewerApplication.preferences.set('externalLinkTarget', 2);
		}
		document.addEventListener('DOMContentLoaded', applyConfig, true);
	</script>
```

**Comment by timvandermeij** [comment]
`PDFViewerApplication` is only available if the web viewer is loaded. You can listen for that event; see https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage.
