### ISSUE TITLE
How to measure PDF download time

### ISSUE THREAD

**Issue by Joozty** [mozilla/pdf.js#11751]
Hi, I was wondering how can be the PDF download time measure. I was thinking about this solution but it probably won't work when PDF is downloaded in chunks because the promise is resolved [after first chunk is loaded](https://github.com/mozilla/pdf.js/issues/7582#issuecomment-244063437):

```jsx
async function loadPDF() {
    const startTime = Date.now()
    await pdfjs.getDocument({
        'som URL here'
    }).promise
    console.log(`PDF Download took ${Date.now() - startTime}ms`)
}
```

Many thanks in advance

**Comment by Snuffleupagus** [comment]
You sounds like `PDFDocumentProxy.getDownloadInfo` is what you want, see https://github.com/mozilla/pdf.js/blob/fa4b431091c51a82315dce7da7b848cc6498bcea/src/display/api.js#L745-L752
