### ISSUE TITLE
pdf文件使用文件流加载时，在edge上容易出现页面模糊，变色，断层，以及文件流不正确的错误

### ISSUE THREAD

**Issue by daixianbing** [mozilla/pdf.js#11764]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge 44.18362.449.0
- Operating system and its version: windows10

- PDF.js version: v2.3.000
- Is a browser extension: 

Steps to reproduce the problem:
1. java后台提供一个pdf文件流接口
2.使用viewer.html请求在edge打开

What is the expected behavior? (add screenshot)
![TIM截图20200330162953](https://user-images.githubusercontent.com/48173293/77891567-b92a1500-72a3-11ea-9072-3713c98d2913.png)
What went wrong? (add screenshot)
![TIM截图20200330162953](https://user-images.githubusercontent.com/48173293/77891567-b92a1500-72a3-11ea-9072-3713c98d2913.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by daixianbing** [comment]
![TIM截图20200330162953](https://user-images.githubusercontent.com/48173293/77892571-63ef0300-72a5-11ea-96eb-cbdce26783db.png)
![TIM图片20200330164230](https://user-images.githubusercontent.com/48173293/77892622-78cb9680-72a5-11ea-9bc3-908737619a40.jpg)
这是两种不同错误，其他浏览器未出现

**Comment by timvandermeij** [comment]
We can only assist in English and if an example PDF file is provided.

**Comment by daixianbing** [comment]
[福奇加替沙星片(福奇)120902-20200330101830.pdf](https://github.com/mozilla/pdf.js/files/4406175/120902-20200330101830.pdf)
This is an example of a PDF file

![TIM截图20200331091759](https://user-images.githubusercontent.com/48173293/77976860-b45f7280-7330-11ea-9096-34776581fe43.png)
This is how I open viewer.html

**Comment by timvandermeij** [comment]
The file renders just fine for me using Firefox and the latest PDF.js version at https://mozilla.github.io/pdf.js/web/viewer.html.
