### ISSUE TITLE
Use CSS transform instead of including RTL equivalents of images

### ISSUE THREAD

**Issue by nt1m** [mozilla/pdf.js#11766]
https://github.com/mozilla/pdf.js/blob/4ff67a518e676a2520c34a11e2c635aac6195681/web/viewer.css#L776-L816

We should just use `transform: scaleX(-1)` instead of RTL equivalents of images.

Those RTL images also cause duplicate files when packaging Firefox: https://searchfox.org/mozilla-central/rev/fa2df28a49883612bd7af4dacd80cdfedcccd2f6/browser/installer/allowed-dupes.mn#66-73

**Comment by timvandermeij** [comment]
Fixed in the PR above. Good point!
