### ISSUE TITLE
PDF Render Error

### ISSUE THREAD

**Issue by coldbess** [mozilla/pdf.js#11768]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: FireFox 74.0
- Operating system and its version: MacOS 10.14.6
- PDF.js version: 2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. Use [sample.pdf](https://github.com/mozilla/pdf.js/files/4406710/sample.pdf)

2. upload to https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
<img width="259" alt="sample" src="https://user-images.githubusercontent.com/5848499/77985935-5fc7f180-7348-11ea-8760-850eb5d1c84b.png">
What went wrong? (add screenshot)
<img width="239" alt="error" src="https://user-images.githubusercontent.com/5848499/77986052-b9c8b700-7348-11ea-8db7-cd0b3d315ad6.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): No

**Comment by timvandermeij** [comment]
I can reproduce this using Arch Linux and Firefox. The following messages show up in the console:

```
Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "RangeError: 14737632 is not a valid code point".
Warning: getTextContent - ignoring errors during "GetTextContent: page 0" task: "RangeError: 14737632 is not a valid code point".
```

**Comment by coldbess** [comment]
This link is OK
http://54.67.70.0:8877/4d1091cde93c899/web/viewer.html
Thanks a lot
