### ISSUE TITLE
Better build system documentation?

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11761]
I'm building a custom pdfjs to send you guys some PRs.

The build system isn't really documented.  

For example, I realized that there is 'gulp package' but this builds .zip files.

I want to build my own custom package and push them to npm but the setup you have is custom.

Once the .zip files are built how do you send them to npm?

I'll document this and send a PR for the build system?

**Comment by Snuffleupagus** [comment]
> I realized that there is 'gulp package' but this builds .zip files.

No such gulp target exists, did you actually mean `gulp publish` here?
If so, that gulp target is only used to produce the official releases as found at https://github.com/mozilla/pdf.js/releases

> I want to build my own custom package and push them to npm but the setup you have is custom.

Well, there's the `gulp dist` target which is used to create/publish the builds for https://github.com/mozilla/pdfjs-dist/, which is what also ends up at https://www.npmjs.com/package/pdfjs-dist (courtesy of bot scripts at https://github.com/mozilla/botio-files-pdfjs).

**Comment by burtonator** [comment]
Thanks... I sort of figured it out.  I realized that gulp dist does this and builds a new package which I can then push.

thanks!
