### ISSUE TITLE
Custom PDF viewer much much slower than standard viewer.  

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11763]
I'm trying to implement a custom PDF viewer and mine is much much slower than the standard one.  

Here's mine.  

![image](https://user-images.githubusercontent.com/45447/77866734-714ab580-71f1-11ea-8925-b96c552f4a52.png)

Note the constant "Composite Layers" ?

![image](https://user-images.githubusercontent.com/45447/77866760-90494780-71f1-11ea-9ceb-31f13d8fc40a.png)

Here's the standard viewer.

They FPS in mine is much lower.  Very choppy.  

The standard viewer is much much faster.  

I think this is possibly due to some CSS in viewer.css that might not be present in my viewer.

I think this is probably yield a lot of bugs because the viewer *needs* certain things from viewer.css which aren't really documented.

**Comment by Snuffleupagus** [comment]
As-is there's unfortunately nowhere near enough information provided to make this an actionable/valid issue!

When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by burtonator** [comment]
@Snuffleupagus Agreed and appreciate the feedback. I'm working on a reduction that I can publish that duplicates the issue.

**Comment by Snuffleupagus** [comment]
@timvandermeij Given that https://github.com/mozilla/pdf.js/issues/11763#issuecomment-605853887 still applies; let's close this as INCOMPLETE for now.
