### ISSUE TITLE
PDF.js and Browser/Environment

### ISSUE THREAD

**Issue by yahyakadiri** [mozilla/pdf.js#11778]
The browser/environement lacks native support for critical functionality used by PDF.js library (e.g `ReadableStream`); please use an ES5-compatible build instead.
![image](https://user-images.githubusercontent.com/58846469/78453578-94aab000-768a-11ea-8154-8dbf44ce7881.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
You'll need to use the `-es5` files from `pdfjs-dist` if you want to be ES5-compatible. By default we now ship non-translated builds, but the ES5 builds are also shipped so you can use them.

**Comment by Snuffleupagus** [comment]
> You'll need to use the `-es5` files from `pdfjs-dist` if you want to be ES5-compatible.

Additionally, official releases will also provide *two* kinds of builds, see the "Assets" section of e.g. https://github.com/mozilla/pdf.js/releases/tag/v2.4.456
