### ISSUE TITLE
How to merge files to imply lazy load

### ISSUE THREAD

**Issue by wideweide** [mozilla/pdf.js#11774]
To view big file:
1. I split to many little files with size 1M(or 3-5pages)
2. load first splitted file,it will be fast
3. when scroll to the end of the viewer,load the second file and merged to the viewer
It will be a better way to view big pdf file, I am not sure whether can be impled use api,or maybe need new feature ?

**Comment by samuelbradshaw** [comment]
Does your file have embedded fonts? If so, note that multiple PDF files with embedded fonts can take up significantly more space / download bandwidth than a single PDF file with the font embedded once.

**Comment by timvandermeij** [comment]
Since none of the information from the issue template is provided, this is unfortunately not actionable for us. In general we only support opening original PDF files; any splitting procedures should be implemented in a third-party deployment.
