### ISSUE TITLE
Doesn't work with PDFs stored in Azure Blob Storage

### ISSUE THREAD

**Issue by drcrook1** [mozilla/pdf.js#11782]
Attach (recommended) or Link to PDF file here:

Access to fetch at 'https://MYSTORAGEACCOUNTNAME.blob.core.windows.net/MYCONTAINERNAME/JNJ-SAMPLE.pdf?st=2020-04-05T19%3A13%3A52Z&se=2020-04-05T19%3A28%3A52Z&sp=r&sv=2017-04-17&sr=b&sig=Y7LKmPfebtPHmzU8SFIo3IOzsuhVDTEV4w/4Sr%2BEeBI%3D' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I also have an embedded sas token.

        permission = BlobPermissions(read=True)
        sas_token = bbs.generate_blob_shared_access_signature(container_name=args.storage_container, 
                                                                blob_name=blob_name,
                                                                start=now,
                                                                expiry=now + timedelta(minutes=15),
                                                                permission=permission)
        sas_url = bbs.make_blob_url(container_name=args.storage_container, blob_name=blob_name, sas_token=sas_token)

you can check out this github for reference on retreiving files form blob and converting to a sas url:

https://github.com/drcrook1/Azure_CustomVision_Blob_Connector/blob/master/src/main.py

It would be great to get this to work.

**Comment by Snuffleupagus** [comment]
> [...] has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It sounds like https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr is relevant here.

> you can check out this github for reference on retreiving files form blob and converting to a sas url:
> 
> https://github.com/drcrook1/Azure_CustomVision_Blob_Connector/blob/master/src/main.py

Unfortunately the PDF.js bug tracker is probably not the best place to get help with Python coding.

---

As-is, it's unfortunately not entirely clear that this is a valid PDF.js issue; please note:
 - When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
 - Please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):

    > The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

> you can check out this github for reference on retreiving files form blob and converting to a sas url:
> 
> https://github.com/drcrook1/Azure_CustomVision_Blob_Connector/blob/master/src/main.py

**Comment by timvandermeij** [comment]
As-is, this issue is unfortunately not actionable for us. It looks like this is a regular CORS issue, but how to resolve this in combination with Azure is not something we can really help with. Unless more actionable information is provided, we're going to have to close this.

**Comment by awesomeToan** [comment]
Hi @drcrook1 Have you fixed this issue ? I got the same issue.
