### ISSUE TITLE
Occasional wrong view for cyrillic letters

### ISSUE THREAD

**Issue by shron1010** [mozilla/pdf.js#11785]
I have a trouble with parse cyrillic PDF's in node js.  In different files sometimes  i get the right text - `пол` becomes `пол`, sometimes `пол` becomes `noJI`. As you see, script recognizes cyrillic letters as similar latin. Any suggestions? 
I use function `getTextContent()` and can't find any options for provide language. Also can do nothing after i get result, because data is wrong already.

Attached 2 samples with outputs. 1st one is right, 2nd is wrong,

[pdf1.pdf](https://github.com/mozilla/pdf.js/files/4442213/pdf1.pdf)
![pdf1output](https://user-images.githubusercontent.com/63262616/78633581-a5d20780-78aa-11ea-9965-8e3f93a5769d.jpg)

[pdf2.pdf](https://github.com/mozilla/pdf.js/files/4442214/pdf2.pdf)
![pdf2output](https://user-images.githubusercontent.com/63262616/78633576-a4a0da80-78aa-11ea-8334-5efc3505b770.jpg)

Operating system - Windows 7 x64
Nodejs version 10.14.2
PDF.js version 1.10.100 and 2.0.550, tried with both

**Comment by Snuffleupagus** [comment]
> PDF.js version 1.10.100 and 2.0.550, tried with both

Please note that both of those versions are too old to be supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

---

In the non-working PDF file, please note there isn't any `ToUnicode` data provided in *any* of the fonts in this PDF file, and it's thus impossible for text-selection/extraction to work correctly in this case.

Please note that this is a limitation of a *specific* PDF file, and not of the PDF.js library (or any other PDF viewer, since it's broken in e.g. Adobe Reader and PDFium/Google Chrome too), and without the PDF file *itself* containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.

**Comment by shron1010** [comment]
> In the non-working PDF file, please note there isn't any ToUnicode data provided in any of the fonts in this PDF file, and it's thus impossible for text-selection/extraction to work correctly in this case.

> Please note that this is a limitation of a _specific_ PDF file, and not of the PDF.js library (or any other PDF viewer, since it's broken in e.g. Adobe Reader and PDFium/Google Chrome too), and without the PDF file _itself_ containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.

Thank you very much for explaining this issue. I guessed that problem is not in library itself. Any chance to provide neccessary data to file and then parse it?

**Comment by Snuffleupagus** [comment]
> Any chance to provide neccessary data to file and then parse it?

You'd have to re-generate the PDF file itself, but with correct font data embedded in it.

**Comment by shron1010** [comment]
> You'd have to re-generate the PDF file itself, but with correct font data embedded in it.

Is it possible? I mean, get old file, extract data from it and regenerate? Will the old data already be incorrect?

**Comment by Snuffleupagus** [comment]
> I mean, get old file, extract data from it and regenerate?

Unless you originally created the PDF file yourself, fixing this is probably difficult though.

All-in-all, as explained above this isn't something that the PDF.js library and/or it's contributors can help you fix unfortunately.

**Comment by shron1010** [comment]
> All-in-all, as explained above this isn't something that the PDF.js library and/or it's contributors can help you fix unfortunately.

Thank you again. I'll go through convert to image and tessract library.
