### ISSUE TITLE
pdfjs如何监听后端的异常信息

### ISSUE THREAD

**Issue by xhlc02** [mozilla/pdf.js#11795]
pdfjs监听不了后端返回的异常信息展示，或者是如何处理

![image](https://user-images.githubusercontent.com/37562895/78958397-804b3500-7b1a-11ea-80da-9bbd4de363ee.png)
![image](https://user-images.githubusercontent.com/37562895/78958474-b4265a80-7b1a-11ea-8614-2c3fcf7f1f53.png)

![image](https://user-images.githubusercontent.com/37562895/78958495-c3a5a380-7b1a-11ea-82cc-9d49ec475613.png)

**Comment by timvandermeij** [comment]
We can only help in English and if the issue template is completely filled out.
