### ISSUE TITLE
Any solution for use custom httpHeaders?

### ISSUE THREAD

**Issue by zhuangzhuang** [mozilla/pdf.js#11792]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:

1. on file viewer.js 
https://github.com/mozilla/pdf.js/blob/4fe92605b75d7e0952738b7f1575d78145b69aeb/web/viewer.js#L214
listen event and motify appOptions

2. on file app.js  https://github.com/mozilla/pdf.js/blob/4fe92605b75d7e0952738b7f1575d78145b69aeb/web/app.js#L741 get config for api
3. but app_options.js has not option for httpHeaders , https://github.com/mozilla/pdf.js/blob/4fe92605b75d7e0952738b7f1575d78145b69aeb/src/display/api.js#L192  support this option

What is the expected behavior? (add screenshot)

suport custom httpHeader for viewer.js
i can only hook xhr, fetch for hack this moment.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Configuration:
> 
>     * Web browser and its version:
> 
>     * Operating system and its version:
> 
>     * PDF.js version:
> 
>     * Is a browser extension:

When opening an issue, you *always* need to provide the above information (since otherwise it's not guaranteed that an answer applies to the PDF.js version you're using).

However, something along the following lines ought to work:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("defaultUrl", ""); // Prevent the default "tracemonkey.pdf" file from loading.

  PDFViewerApplication.initializedPromise.then(function() {
    // The viewer has now been initialized.

    // Open your PDF file, with custom headers.
    PDFViewerApplication.open("A string containing the path to your PDF file", {
       httpHeaders: // Add your HTTP headers here.
    });
  })
});
```

**Comment by zhuangzhuang** [comment]
@Snuffleupagus thanks for your help,
