### ISSUE TITLE
Getting error while loading pdf in a viewer 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by Kiran-GitHuber** [mozilla/pdf.js#11796]
Configuration:
- Chrome Version 80.0.3987.163
-Windows 10
- PDF.js v2.3.2

Getting below error while running in tomcat server but works fine with the local node server.

Refused to display 'myserverpath/assets/pdfjs/web/viewer.html?file=myblobpath&openFile=false&download=true&viewBookmark=true&startPage=0&stopPage=466' in a frame because it set 'X-Frame-Options' to 'deny'.\

Based on couple of suggestions tried below options:
1) From serverside changed response header X-Frame-Options to "SAMEORIGIN".Still i am getting the same error.
2) Added filter inside web.xml in tomcat config. Still issue persists
![image](https://user-images.githubusercontent.com/21022883/78980701-10e63d00-7b3c-11ea-8b9c-24ac8edfce80.png)

**Comment by timvandermeij** [comment]
Unfortunately we cannot help out with Tomcat configuration since none of us appear to have experience with that. Since this is not really PDF.js-related but instead a configuration issue for Tomcat, you're best bet would be to ask for this at a Tomcat support forum.
