### ISSUE TITLE
How can I use pdfjs in iframe on https website？

### ISSUE THREAD

**Issue by ZhangXY-Magic** [mozilla/pdf.js#11793]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 80.0.3987.162
- Operating system and its version: win10
- PDF.js version:1.8.188
- Is a browser extension:

Steps to reproduce the problem:
1. I use pdfjs on my react app like the guide(https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/) use iframe
2.but it looks like iframe does not works with https，how can i use when my websit is deploy on a https websit with nginx，i really appreciate for your reply

What is the expected behavior? (add screenshot)
it's work on a https website
What went wrong? (add screenshot)
cannot load pdfjs/viewer.html with https, it works whith http
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Without a running example, there is not much we can do to help. Keep in mind that PDF.js is a normal JavaScript application, so any web server will work as long as it's configured correctly. From your description it looks like you _may_ be running into a CORS issue, so please read https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr
