### ISSUE TITLE
Package require os(darwin) not compatible with your platform(win32)

### ISSUE THREAD

**Issue by HelloDreamICome** [mozilla/pdf.js#11808]
As the title suggests

Pdfjs-dist  Can't run on the x32?

**Comment by timvandermeij** [comment]
PDF.js is a JavaScript package, so it runs on any platform. Perhaps Node.js itself no longer works on older platforms, but that is not something we have influence on. Closing since we don't do anything ourselves to block those platforms.

**Comment by HelloDreamICome** [comment]
> PDF.js is a JavaScript package, so it runs on any platform. Perhaps Node.js itself no longer works on older platforms, but that is not something we have influence on. Closing since we don't do anything ourselves to block those platforms.

It's actually a bug caused by other problems,These problems have now been sorted.thanks very much !
