### ISSUE TITLE
Rendering PDF which include shapes who have opacity (SVG renderer)

### ISSUE THREAD

**Issue by bobsingor** [mozilla/pdf.js#11812]
Attach (recommended) or Link to PDF file here:
I attached the svg as txt because of the github upload restrictions.
[page3.txt](https://github.com/mozilla/pdf.js/files/4481235/page3.txt)
[ton_page3.pdf](https://github.com/mozilla/pdf.js/files/4481237/ton_page3.pdf)

Configuration:
Web browser and its version: Latest Chrome (80.0.3987.149)
PDF.js version: pdfjs-dist (2.4.456)

Steps to reproduce the problem:
Use the PDF above in the SVG renderer and you will see that image in the middle has two cirlces. the right circle should have 3 circles around them that each has less opacity. In the SVG renderer these circles are rendered with full opacity.

**Comment by timvandermeij** [comment]
Fixed by the pull request above.
