### ISSUE TITLE
Rendering PDF which include PNG with transparent background (SVG renderer)

### ISSUE THREAD

**Issue by bobsingor** [mozilla/pdf.js#11811]
First off all, Great job on the SVG renderer. Can't wait to use it in production. We are testing the PDF's in our system and in the latest version most PDF are rendered correctly as SVG. There are a couple of bugs that I want to address and post as issues here.

Attach (recommended) or Link to PDF file here:
I attached the svg as txt because of the github upload restrictions.
[page.txt] (https://github.com/mozilla/pdf.js/files/4481179/page.txt)
[ton_page8.pdf] (https://github.com/mozilla/pdf.js/files/4481193/ton_page8.pdf)

Configuration:
- Web browser and its version: Latest Chrome (80.0.3987.149)
- PDF.js version: pdfjs-dist (2.4.456)

Steps to reproduce the problem:
Use the PDF above in the SVG renderer and you will see that the top image are being rendered with a black background. In the original it has transparent background.

**Comment by Snuffleupagus** [comment]
> Can't wait to use it in production.

That's probably not likely to happen any time soon (or even at all), considering that the SVG back-end is inherently slower (given the huge amount of DOM elements it creates) and also that it requires more memory than the default `canvas` back-end; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by timvandermeij** [comment]
Yes, for now the SVG back-end is an experimental alternative, but not ready for production use yet. Nevertheless, thank you for reporting issues since it will help to improve it!

**Comment by amelie2923** [comment]
Same problem here, images with transparent background are displayed with a black background.
Is there a solution planned for that?

![Capture d’écran 2020-07-01 à 16 36 28](https://user-images.githubusercontent.com/61972536/86244737-75ec8480-bbb9-11ea-91f7-5bcd3e521b94.png)

**Comment by davistran86** [comment]
I'm also looking for a solution for this

**Comment by dewinovitasari** [comment]
saya juga mencari solusi bagaimana baiknya
