### ISSUE TITLE
Flicker-free pdf reloading

### ISSUE THREAD

**Issue by a-reisberg** [mozilla/pdf.js#11827]
For some context, I'm using https://github.com/James-Yu/LaTeX-Workshop to edit tex files. This vscode extension uses the viewer from pdf.js to render pdf files. Every time the tex file is compiled, the pdf preview is refreshed.

Now, when pdf.js refreshes, the pdf viewer flickers which is somewhat tiring after a while. Supposedly, this is because when open is triggered, pdf.js clears out the current content, renders a white page, and waits until the new page is rendered. I think it is that white page that causes the flickering. Ideally, for this use case, it would be nice to not have this white page drawn while waiting for the new content to be rendered. Instead, pdf.js can just wait until the new render is ready and then draws.

My question is thus: is it possible/easy to implement the above if it's not there already? I would also be more than happy to give it a try if someone can point me to the right place to look (I'm completely new to this codebase).

Thanks!

**Comment by Snuffleupagus** [comment]
> For some context, I'm using https://github.com/James-Yu/LaTeX-Workshop to edit tex files. This vscode extension uses the viewer from pdf.js to render pdf files. Every time the tex file is compiled, the pdf preview is refreshed.

It's probably best to open an issue in that repository *first*, to ensure that this isn't simply an issue regarding their usage of the PDF.js library (which we cannot really provide support for here).

> Now, when pdf.js refreshes, the pdf viewer flickers which is somewhat tiring after a while. Supposedly, this is because when open is triggered, pdf.js clears out the current content, renders a white page, and waits until the new page is rendered.

Can this be reproduced with the unmodified PDF.js default viewer, when used directly, see https://github.com/mozilla/pdf.js#online-demo?
If so, then please provide *detailed* steps to reproduce this; and please remember to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.

As-is, given that this issue references a *different* project, it's unfortunately somewhat difficult to tell what the problem might be and/or if this issue is valid here.

**Comment by timvandermeij** [comment]
In general I don't really see how this can be solved. The only way to prevent flickering is if the page size doesn't change, which is not guaranteed at all when switching PDF files. If LaTeX Workshop can somehow ensure this, then they could implement that in their version of PDF.js (assuming they use the viewer components or a fork), but it's not something we can implement in the general viewer unfortunately.

**Comment by a-reisberg** [comment]
@timvandermeij Thanks for the reply.  It makes sense that this is a rather special workflow, where the updated pdf only differs from the current one in a minor way.  The issue has been raised in that repo as well, but it seems (to me) that the authors do not know pdfjs well enough and probably do not have the bandwidth.  

That's why I mentioned above that I could go about implementing it myself, if someone more familiar with the codebase gives me some pointer. Could you give me some pointer?

Thanks a lot.

**Comment by timvandermeij** [comment]
I'm assuming the default viewer is used. If a new document is opened, the `open` method in `web/app.js` is called. This method, as one of the first things, closes any existing document using the `close` method (refer to https://github.com/mozilla/pdf.js/blob/a13db5d91ae08f4d164fe75fb6f22a4eeab9e960/web/app.js#L659-L703). One of the steps there is removing the document from the viewer element at https://github.com/mozilla/pdf.js/blob/a13db5d91ae08f4d164fe75fb6f22a4eeab9e960/web/app.js#L674, so I think you'll have to look into that logic to see if you can defer the removal of the old canvas until the new one is loaded to avoid the flickering effect.

**Comment by a-reisberg** [comment]
@timvandermeij Indeed, the default viewer is used.  They use the dist version of the viewer directly (one huge viewer.js https://github.com/James-Yu/LaTeX-Workshop/blob/master/viewer/viewer.js).  But I should be able to figure it out from here.

Thanks a lot!
