### ISSUE TITLE
Set locale don't work.

### ISSUE THREAD

**Issue by renderpci** [mozilla/pdf.js#11829]
Hi

I try to set locale with PDFViewerApplicationOptions.set('locale', 'es-ES'), and it change the locale I tested by .get('locale') , but this action don't change the viewer to new language.

Configuration:
- Web browser and its version: Chrome 81.0.4044.113 , Safari   13.1 (15609.1.20.111.8)
- Operating system and its version: OSX 10.13
- PDF.js version: 2.3.200

Steps to reproduce the problem:
1. console.log(PDFViewerApplicationOptions.get('locale')); // en-US
2. PDFViewerApplicationOptions.set('locale', 'es-ES');
3. console.log(PDFViewerApplicationOptions.get('locale')); // es-ES
4. but the viewer don't change the language:

<img width="584" alt="a" src="https://user-images.githubusercontent.com/8447635/79848949-19533900-83c2-11ea-9388-43b6999c5b89.png">

Is this way the best way to change the locale? or is possible change the locale with other property?

And thanks for this amazing tool!
Best

**Comment by Snuffleupagus** [comment]
The "locale", similar to most options, must be set *before* the default viewer is initialized, and changing it afterwards won't do anything.

Following https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage, you'd have to do e.g.
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set('locale', 'es-ES');
});
```

**Comment by renderpci** [comment]
Hi Snuffleupagus, thanks for your answer, but it don't work.

I have the viewer inside one iframe and I had this way for change the application options:

```js
iframe.addEventListener("load", function() {
  const PDFViewerApplicationOptions = iframe.contentWindow['PDFViewerApplicationOptions'];
  PDFViewerApplicationOptions.set('defaultUrl', '');
  PDFViewerApplicationOptions.set('locale', 'es-ES');
})
```
the .set() of defaultUrl work perfectly
the .set() of locale don't work

As you say I try with this option:

```js
iframe.addEventListener("webviewerloaded", function() {
  const PDFViewerApplicationOptions = iframe.contentWindow['PDFViewerApplicationOptions'];
  PDFViewerApplicationOptions.set('defaultUrl', '');
  PDFViewerApplicationOptions.set('locale', 'es-ES');
})
```

the .set() of defaultUrl don't work
the .set() of locale don't work

I don't know what is the way to do this action, but I need change the locale to sync with my project config. Any suggestion ?


Thanks in advance.
Alex

**Comment by Snuffleupagus** [comment]
Well, https://github.com/mozilla/pdf.js/issues/11829#issue-603848567 didn't mention anything about using iframes :-)

Based on the code snippets, it'd guess that it's not really a PDF.js issue but rather a case of attaching the event listener to the wrong DOM element. With the caveat that it's not clear what DOM element the `iframe` name refers to, in your code snippets, I'd guess that the following should work:
```javascript
iframe.contentWindow.addEventListener("webviewerloaded", function() {
  this.PDFViewerApplicationOptions.set('defaultUrl', '');
  this.PDFViewerApplicationOptions.set('locale', 'es-ES');
});
```

If that still isn't enough, then see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by renderpci** [comment]
Snuffleupagus, thanks for your answer
Upss, sorry I forget mention the iframe situation in my first comment... 

I try to be more clear and explicit with the code:

you can see a functional example of this code here:
https://test.numisdata.org/pdfjs/index.html


 ```js
const iframe = document.createElement('iframe');
iframe.src = '/pdfjs/web/viewer.html'
 iframe.addEventListener("load", function() {
   const PDFViewerApplicationOptions = iframe.contentWindow['PDFViewerApplicationOptions'];
   PDFViewerApplicationOptions.set('defaultUrl', '');
   PDFViewerApplicationOptions.set('locale', 'es-ES');
 })
 ```
 
 the .set() of defaultUrl work perfectly
 the .set() of locale don't work
 
As you say I try with you solution that you can see it working (but not functional, see the console):
https://test.numisdata.org/pdfjs/index2.html
 
 ```js
const iframe = document.createElement('iframe');
iframe.src = '/pdfjs/web/viewer.html'
iframe.contentWindow.addEventListener("webviewerloaded", function() {
  this.PDFViewerApplicationOptions.set('defaultUrl', '');
  this.PDFViewerApplicationOptions.set('locale', 'es-ES');
});
```
The problem here is that iframe.contentWindow is not created at this point, is null, you need wait to load the iframe to get access to the .contentWindow. Is possible think in create the listener of 'webviewerloaded' inside the 'load' listener, and in these moment you can access to the iframe.contentWindow

and of course you can see this working:
https://test.numisdata.org/pdfjs/index3.html

 ```js
const iframe = document.createElement('iframe');
iframe.src = '/pdfjs/web/viewer.html'
iframe.addEventListener("load", function() {
  iframe.contentWindow.addEventListener("webviewerloaded", function() {
    this.PDFViewerApplicationOptions.set('defaultUrl', '');
    this.PDFViewerApplicationOptions.set('locale', 'es-ES');
  });
});
```

But the problem is the same, it's not possible change the locale or don't work in this point.
I can change your code and add my context lang into the defaultOptions.locale variable:

 ```js
defaultOptions.locale = {
    value: typeof navigator !== 'undefined' ? navigator.language : 'en-US',
    kind: OptionKind.VIEWER
  };
```

But it's a dirty way to do it. What is the way to change the locale?

Thanks in advance

Alex

**Comment by renderpci** [comment]
Hi again.

Well, the problem is that your custom event: webviewerloaded is only fired inside the iframe document, and it's impossible (or I don't know how get the custom event before "load" event of iframe).

I think that maybe dispatch of the custom event will be better in the 'top.document' instead 'document', dispatch it into the top.document opening the possibility to be captured the event inside or outside iframe.

My proposal is change the viewer.js from:
```js
function webViewerLoad() {
  var config = getViewerConfiguration();
  window.PDFViewerApplication = pdfjsWebApp.PDFViewerApplication;
  window.PDFViewerApplicationOptions = pdfjsWebAppOptions.AppOptions;
  var event = document.createEvent('CustomEvent');
  event.initCustomEvent('webviewerloaded', true, true, {});
  document.dispatchEvent(event);
  pdfjsWebApp.PDFViewerApplication.run(config);
}
```
to:

```js
function webViewerLoad() {
  var config = getViewerConfiguration();
  window.PDFViewerApplication = pdfjsWebApp.PDFViewerApplication;
  window.PDFViewerApplicationOptions = pdfjsWebAppOptions.AppOptions;
  var event = document.createEvent('CustomEvent');
  event.initCustomEvent('webviewerloaded', true, true, {});
  top.document.dispatchEvent(event);
  pdfjsWebApp.PDFViewerApplication.run(config);
}
```

and it's possible capture the custom event in this way:

```js
const iframe = document.createElement('iframe');
iframe.src = '/pdfjs/web/viewer.html'
document.addEventListener("webviewerloaded", function() {
  const PDFViewerApplicationOptions = iframe.contentWindow['PDFViewerApplicationOptions'];
  PDFViewerApplicationOptions.set('defaultUrl', '');
  PDFViewerApplicationOptions.set('locale', 'es-ES');
})
```
that work perfectly, try to do the same thing outside iframe and it works well too.

It's possible implement this change into the viewer.js permanently?
(I don't want change it every time that I want update the viewer.js)

Other questions, alternatives?

Thanks!
Alex
