### ISSUE TITLE
Cannot get real width of the text item

### ISSUE THREAD

**Issue by markb-trustifi** [mozilla/pdf.js#11824]
Attach (recommended) or Link to PDF file here:
[Evernote+link+inside+(malicious).pdf](https://github.com/mozilla/pdf.js/files/4499070/Evernote%2Blink%2Binside%2B.malicious.pdf)

Configuration:
- Operating system and its version: MacOS 10.14.6
- PDF.js version: 2.4.456 (dist)
- Env: Node.js 12

I cannot get the correct item width. If I combine all items in a first line I get around 347.37 (px?).
On the other hand the viewport width with scale=1 is 612px.

I'm attaching the text item transform and its style accent:
<img width="453" alt="Screen Shot 2020-04-19 at 15 59 54" src="https://user-images.githubusercontent.com/29097494/79688470-36b7c400-8257-11ea-9d0b-0338df71c56e.png">
<img width="346" alt="Screen Shot 2020-04-19 at 16 00 19" src="https://user-images.githubusercontent.com/29097494/79688473-3a4b4b00-8257-11ea-8a59-acd1d5907414.png">

**Comment by nkimadusanka** [comment]
> Attach (recommended) or Link to PDF file here:
> [Evernote+link+inside+(malicious).pdf](https://github.com/mozilla/pdf.js/files/4499070/Evernote%2Blink%2Binside%2B.malicious.pdf)
> 
> Configuration:
> 
> * Operating system and its version: MacOS 10.14.6
> * PDF.js version: 2.4.456 (dist)
> * Env: Node.js 12
> 
> I cannot get the correct item width. If I combine all items in a first line I get around 347.37 (px?).
> On the other hand the viewport width with scale=1 is 612px.
> 
> I'm attaching the text item transform and its style accent:
> <img alt="Screen Shot 2020-04-19 at 15 59 54" width="453" src="https://user-images.githubusercontent.com/29097494/79688470-36b7c400-8257-11ea-9d0b-0338df71c56e.png">
> <img alt="Screen Shot 2020-04-19 at 16 00 19" width="346" src="https://user-images.githubusercontent.com/29097494/79688473-3a4b4b00-8257-11ea-8a59-acd1d5907414.png">

@markb-trustifi  Evernote document not found

**Comment by markb-trustifi** [comment]
> Evernote document not found

@nkimadusanka What does it mean? The attached PDF is accessible.

**Comment by Snuffleupagus** [comment]
> I cannot get the correct item width. If I combine all items in a first line I get around 347.37 (px?).

 - What item width did you expect to get?
 - Why do you believe that what the PDF.js library returns is incorrect here?
 - Against what (e.g. other software and/or the PDF specification) are you comparing, when stating that the PDF.js library is incorrect?

---

Unfortunately, without a lot more information/context, this issue isn't really actionable in its current form since it's very difficult (almost impossible) for anyone else to *clearly* understand the reported problem.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by markb-trustifi** [comment]
If we look into this screenshot:
<img width="869" alt="Screen Shot 2020-05-11 at 11 56 03" src="https://user-images.githubusercontent.com/29097494/81543231-74070180-937e-11ea-9d2c-f863214fc901.png">

The total width of the page is 612px and the calculated width of the text in the first line is 347px.
Actually, now I see that it is reasonable.
Then, other question. Which symbols are considered line breakers? I assume these are the whitespace and hyphen. Are there anything else?

**Comment by Snuffleupagus** [comment]
> Which symbols are considered line breakers?

There is, for all intents and purposes, no concept of line-breaks in the PDF specification and all glyphs are (essentially) positioned individually using coordinates.
