### ISSUE TITLE
Audit places that trigger the fallback bar

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#11839]
Similar to #11838, we'd like to show the fallback bar less. We should audit and see if all the triggers make sense. This could be done during #11815.

**Comment by Snuffleupagus** [comment]
Given [bug 1705327](https://bugzilla.mozilla.org/show_bug.cgi?id=1705327) I'm guessing this is either FIXED, or possibly WONTFIX, now?

**Comment by timvandermeij** [comment]
Yes, and I think most places already got audited in issues like #11838 and others.
