### ISSUE TITLE
unexpected EOF in bcmap

### ISSUE THREAD

**Issue by Coisinini** [mozilla/pdf.js#11833]
When I used pdfjs to show a pdf file,the pdf file can not be fully displayed。
![ONLV}NDUAU%V9JQ TS{ V$J](https://user-images.githubusercontent.com/47846683/79967619-a335fb80-84c1-11ea-889b-c77f8ba1b714.png)
The console reports an error as follows：
Warning: Error during font loading: unexpected EOF in bcmap

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Coisinini** [comment]
Configuration:

Web browser and its version: chrome 73.0.3683.86
Operating system and its version: windows10
PDF.js version: 2.0.943
Is a browser extension: no
Steps to reproduce the problem:
Open a PDF file with a special font, the  file can not be fully displayed。

The console reports an error as follows：
Warning: Error during font loading: unexpected EOF in bcmap

What is the expected behavior? 
Full presentation file

What went wrong? (add screenshot)
The console reports an error as follows：
Warning: Error during font loading: unexpected EOF in bcmap

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.0.943

That version is no longer supported, please find current releases at https://github.com/mozilla/pdf.js/releases

> Open a PDF file with a special font, the file can not be fully displayed

Without the PDF file in question, this issue is unfortunately not actionable/valid.

**Comment by xiaofuhao** [comment]
I have a problem. It's strange. CMAPs package file, gradle compiled, windows and Linux are inconsistent, and then changed the compile command to solve. Probably the CMAPs package file reference problem.
