### ISSUE TITLE
Small file fragment loading redundancy

### ISSUE THREAD

**Issue by JohnJiang900526** [mozilla/pdf.js#11832]
Attach (recommended) or Link to PDF file here:  no file, You can use a 12MB pdf file for testing.

Steps to reproduce the problem:
1.
 ![image](https://user-images.githubusercontent.com/18456218/79944611-8e943c00-849e-11ea-851e-6e735483b761.png)
The size exceeds the default slice size 65535，I think this is wrong。

2.
![image](https://user-images.githubusercontent.com/18456218/79944798-08c4c080-849f-11ea-8d4f-065fdfcb5c03.png)
Add the above four lines of code in the src\display\fetch_stream.js to solve the above problem。
This is a temporary plan, I hope you have better.

3. Note that files that are too large, such as 200MB, are not a problem. Too small is no problem, focus on testing files about 13MB.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: no file, You can use a 12MB pdf file for testing.

Unless you actually provide said PDF file, this issue unfortunately isn't actionable/valid.

Furthermore this issue is missing *a lot* of the information required in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, such as
> Configuration:
> - Web browser and its version:
> - Operating system and its version:
> - PDF.js version:
> - Is a browser extension:
