### ISSUE TITLE
The examples directive in pdf.js repo, those examples's `pdf_viewer.js` is not in web/ but in components/ 

### ISSUE THREAD

**Issue by gogobook** [mozilla/pdf.js#11842]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 75.0
- Operating system and its version:ubuntu 18.04.4
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
`pdf_viewer.js` is not in web directive, but in components.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
> `pdf_viewer.js` is not in web directive, but in components.

It's very difficult to understand what you're actually trying to report/ask here; please rephrase and expand upon this in order for the issue to be actionable/valid.

**Comment by gogobook** [comment]
Hi Snuffleupagus

The [examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/),  some of them need `gulp dist-install` to generate components folder and `pdf_viewer.js` in the folder, `pdf_viewer` not in web folder.

Some of examples is  with wrong `index.html `.

**Comment by Snuffleupagus** [comment]
> The [examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/), some of them need `gulp dist-install` to generate components folder and `pdf_viewer.js` in the folder, `pdf_viewer` not in web folder.

Sorry, but this is still difficult to parse.

> Some of examples is with wrong `index.html `.

Please provide links directly to actual examples.

**Comment by gogobook** [comment]
the [svgviewer folder](https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer), and others.

**Comment by Snuffleupagus** [comment]
> the [svgviewer folder](https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer), and others.

Works for me; it's still not at all clear what *exactly* you perceive to be wrong here!?

**Comment by gogobook** [comment]
Ok, thank you help.
