### ISSUE TITLE
Text color can not render correctly

### ISSUE THREAD

**Issue by zhenlingcn** [mozilla/pdf.js#11849]
Configuration:
- Web browser and its version: Chrome 70
- Operating system and its version: Windows 10
- PDF.js version: Lastest 
- Is a browser extension: No

Steps to reproduce the problem:
1. Adding a new property of an arbitrary span.
![image](https://user-images.githubusercontent.com/18747119/80338454-f081e680-888e-11ea-97e7-fcf7e4b094ac.png)
2. Text is improperly rendered in PDF.JS.
![image](https://user-images.githubusercontent.com/18747119/80338487-02638980-888f-11ea-8244-5b944e898a49.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
The `textLayer`, which is what you appear to have edited in your screen-shot, is *only* used to enable selection/copying/searching in the PDF document and is *explicitly* not supposed to be made visible; hence this issue is INVALID.

Finally, given the limited STR provided it's not at all clear what you're even trying to achieve here.

**Comment by zhenlingcn** [comment]
There are some annotation tools highlight specific words by changing the word colour, such as the chrome extension "Words Discoverer" (https://github.com/mechatroner/aided_reading).

**Comment by Snuffleupagus** [comment]
> There are some annotation tools highlight specific words by changing the word colour,

In that case, this simply means that those tools are *not* compatible with the PDF.js library and there's simply nothing that can be done about that here.

>  such as the chrome extension "Words Discoverer" (https://github.com/mechatroner/aided_reading).

That's a completely different project, in no way affiliated with the PDF.js project, and consequently we cannot provide any support for it.

**Comment by zhenlingcn** [comment]
I want to change the code of that extension to make it compatible with PDF.JS.  Is there any feasible way to highlight a specific word in PDF.JS?
