### ISSUE TITLE
Viewer.html of 2.4.456 is not working for multiple prints

### ISSUE THREAD

**Issue by shruthiudayakumar** [mozilla/pdf.js#11841]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 81
- Operating system and its version: Windows 10 
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. Make the following code changes to  viewer.js.
//add the function below
function receiveMessage(event) {
	var selfDomain = window.location.origin ? window.location.origin : (window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port : '')); 
	if(event.origin === selfDomain && event.data){ 
		if(event.data['cmd'] === "SET_PDF_BLOBURL"){
			var ctxBlobUrl = event.data['url'];
			webViewerLoad(null,ctxBlobUrl);
		}
	}
}
// **Modify webviewerload function like below**
function webViewerLoad(event,ctxPDFPrintBlobUrl) {
  let config = getViewerConfiguration();
  window.PDFViewerApplication = pdfjsWebApp.PDFViewerApplication;
  window.PDFViewerApplicationOptions = pdfjsWebAppOptions.AppOptions;
  if(ctxPDFPrintBlobUrl){
	 config.ctxPDFBlobUrl = ctxPDFPrintBlobUrl;
  }
  pdfjsWebApp.PDFViewerApplication.run(config);
}
//**Modify webViewerInitialized function like below** 
function webViewerInitialized() {
  var appConfig = PDFViewerApplication.appConfig;
  var file;
  if(appConfig.ctxPDFBlobUrl){
	  file = appConfig.ctxPDFBlobUrl;
  }else{
  let queryString = document.location.search.substring(1);
  let params = (0, _ui_utils.parseQueryString)(queryString);
  file = 'file' in params ? params.file : _app_options.AppOptions.get('defaultUrl');
  }
//....rest of the function as is
2. Load viewer.html in an iframe and pass blob url via postmessage.
3. pagesloaded event in parent page should get triggered.

What is the expected behavior? (add screenshot)
pagesloaded event handler should get called

What went wrong? (add screenshot)
pagesloaded event handler does not get called. However same changes in 2.3.200 version's viewer.html is working fine.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by shruthiudayakumar** [comment]
Also when will 2.4.456 will be stable ?

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
