### ISSUE TITLE
External links from PDFs are not workling (correct)

### ISSUE THREAD

**Issue by remmedia** [mozilla/pdf.js#11846]
Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Upload a PDF with an external link (outside domain) to an pdf file (or sample domain below; see 4/5)
2. view this pdf with pdf.js
3. klick on the link and an empty pdf-file will be opend.
(4. if there is a link to a homepage and you click this, the homepage will be opend. if there is an link to an pdf-file (on this homepage) which is displayed with pdf.js as well, this pdf will not show up as well, just a blank page is shown)
4/5. there are also homepages which will not work if they are linked. On https://www.theorie-musik.de/training/violin-noten-lesen.php?aufl=1280 e.g. it is not possible to send form after input result. Copy same link to new tab will work.

I found this hint somewhere but have no ide how to prevent this.
Sometimes when you click a link from an application, the tab opened will have javascript disabled/sandboxed.
Error on Dev-Tools Blocked form submission to 'violin-noten-lesen.php?aufl=1280' because the form's frame is sandboxed and the 'allow-forms' permission is not set

What is the expected behavior? (add screenshot)
external pdf is shown
page (form) is working

What went wrong? (add screenshot)
external page/url is empty (pdf not shown inside external pdf.js)
form is not working

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
In particular, all of the following information is *required* in order for the issue to be actionable/valid:
> Attach (recommended) or Link to PDF file here:
>
> Configuration:
>
> - Web browser and its version:
> - Operating system and its version:
> - PDF.js version:
> - Is a browser extension:

---

> 1. Upload a PDF with an external link (outside domain) to an pdf file

There's no editing capabilities in the PDF.js library, consequently this sentence doesn't really make sense.

> 2\. view this pdf with pdf.js

The PDF file in question is does not appear to be included anywhere in this issue...

> 3\. klick on the link and an empty pdf-file will be opend.

What link? The provided STR is basically impossible to understand and follow.

> 4\. if there is a link to a homepage and you click this, the homepage will be opend. if there is an link to an pdf-file (on this homepage) which is displayed with pdf.js as well, this pdf will not show up as well, just a blank page is shown

Again, it's unfortunately not possible to easily interpret this sentence given the limited information provided above.

> 5\. there are also homepages which will not work if they are linked. On https://www.theorie-musik.de/training/violin-noten-lesen.php?aufl=1280 e.g. it is not possible to send form after input result. Copy same link to new tab will work.

It's somewhat difficult to understand how the PDF.js library is even relevant to that web-page.

> Error on Dev-Tools Blocked form submission to 'violin-noten-lesen.php?aufl=1280' because the form's frame is sandboxed and the 'allow-forms' permission is not set

It's quite frankly difficult to see how any of this would be a valid issue for the PDF.js library, since we obviously cannot provide support for working with browser sandboxing.

**Comment by remmedia** [comment]
seams it can be closed, there was still an old version 1.7 used.

**Comment by remmedia** [comment]
Attach (recommended) or Link to PDF file here:
[https.pdf](https://github.com/mozilla/pdf.js/files/4533040/https.pdf)

Configuration:
nextcloud
Web browser and its version:
different one
using chrome 81.0.4044.122 (Offizieller Build) (64-Bit)
Operating system and its version:
different
using Windows 10 Pro 10.0.18363
PDF.js version:
1.7 and 2.3.200
Is a browser extension:
no

Steps to reproduce the problem:
1. open attached file with pdf.js (inside nextcloud)
2. click the links

What is the expected behavior? (add screenshot)
for the three links
a) a pdf file is shown
b) form is working
c) on click on "Download Sample PDF File" this file is shown

What went wrong? (add screenshot)
for the three links
a) page keeps blank
b) form is not working
c) page works but on click on "Download Sample PDF File" target keeps blank

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
to reproduce the problem you can use the public demo of nextcloud:
https://try.nextcloud.com and upload the attached file.

If you right-click the links and select "open in new window" or "open in new tab" or open the pdf file with any other pdf viewer, everything works fine.

**Comment by Snuffleupagus** [comment]
> Configuration:
> nextcloud

"Nextcloud", whatever that is, is not in any way affiliated with the PDF.js project and thus we cannot provide support for it here.

> PDF.js version:
> 1.7 and 2.3.200

Note that any PDF.js version from the `1.x.y` branch is no longer supported.

> Steps to reproduce the problem:
> 
>     1. open attached file with pdf.js (inside nextcloud)
>     2. click the links

That PDF file works perfectly with the PDF.js default viewer, see https://github.com/mozilla/pdf.js#online-demo, hence this is unfortunately not a valid issue in the PDF.js repository.

> to reproduce the problem you can use the public demo of nextcloud:
> https://try.nextcloud.com and upload the attached file.

Again, this isn't the correct place for Nextcloud support; please direct further questions on this matter *directly* to Nextcloud instead.

**Comment by remmedia** [comment]
> > Configuration:
> > nextcloud
> 
> "Nextcloud", whatever that is, is not in any way affiliated with the PDF.js project and thus we cannot provide support for it here.
> 
i know but i wanted to make sure the behavior can be reproduced
> > PDF.js version:
> > 1.7 and 2.3.200
> 
> Note that any PDF.js version from the `1.x.y` branch is no longer supported.
> 
i know, therefore i updated the default version to use both
> > Steps to reproduce the problem:
> > ```
> > 1. open attached file with pdf.js (inside nextcloud)
> > 2. click the links
> > ```
> 
> That PDF file works perfectly with the PDF.js default viewer, see https://github.com/mozilla/pdf.js#online-demo, hence this is unfortunately not a valid issue in the PDF.js repository.
> 
i forget to mention that it only occours if `externallinktarget` is set to `BLANK`
> > to reproduce the problem you can use the public demo of nextcloud:
> > https://try.nextcloud.com and upload the attached file.
> 
> Again, this isn't the correct place for Nextcloud support; please direct further questions on this matter _directly_ to Nextcloud instead.
i know but as rendering of the pdf-file is done by pdf.js and not nextcloud in my mind it seams to be a bug inside pdf.js

**Comment by Snuffleupagus** [comment]
> i forget to mention that it only occurs if `externallinktarget` is set to `BLANK`

Were you actually able to reproduce the bug in the PDF.js default viewer?
In my testing, with https://mozilla.github.io/pdf.js/web/viewer.html, the links in your PDF file work just fine regardless of the `externalLinkTarget` value (note also the correct capitalisation).

> i know but as rendering of the pdf-file is done by pdf.js and not nextcloud in my mind it seams to be a bug inside pdf.js

As mentioned twice now, this works in the PDF.js default viewer hence this is *not* a valid issue here. Most likely there's some wrong with the way that Nextcloud are using the PDF.js library, but that unfortunately cannot be fixed and/or supported here.

**Comment by remmedia** [comment]
ok
just got it.
pdf.js is not working inside an `iframe` with `sandbox` parameter.
