### ISSUE TITLE
The letters stick together a bit on IE 11 (and EdgeHTML)

### ISSUE THREAD

**Issue by letsevi** [mozilla/pdf.js#11843]
Attach (recommended) or Link to PDF file here:
[ie-trouble.pdf](https://github.com/mozilla/pdf.js/files/4521047/ie-trouble.pdf)

Configuration:
- Web browser and its version: IE 11 (and EdgeHTML)
- Operating system and its version: Windows 7 Pro
- PDF.js version: 2-2-228
- Is a browser extension: No

Steps to reproduce the problem:
1. Open an attached file. The smaller the scale, the more noticeable

What is the expected behavior? (add screenshot)
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/8323814/80075298-281d2580-8553-11ea-9503-74794b5e58cd.png)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: IE 11 (and EdgeHTML)

Those browsers are no longer fully supported, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

> PDF.js version: 2.2.228

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases
