### ISSUE TITLE
Cannot display JPG image with Buffer provided

### ISSUE THREAD

**Issue by telfordho** [mozilla/pdf.js#11855]
I am trying embed following image to a mini project.
![image-0](https://user-images.githubusercontent.com/34391995/80441375-6b093f80-893d-11ea-9b9b-e64717c9a73e.jpg)

**Here's my setting:**
`{
  "name": "pdfjs",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/express": "^4.17.6",
    "fs-extra": "^9.0.0",
    "pdfjs": "^2.3.5",
    "ts-node": "^8.9.1",
    "typescript": "^3.8.3"
  },
  "scripts": {
    "start": "ts-node pdf.ts"
  }
}`

**I simply use fse to get the buffer, create a new row and cell, then call new pdf.Image( )**

import * as pdf from 'pdfjs'
import * as fse from 'fs-extra'

(async () => {
  const doc = new pdf.Document({
    font:    require('pdfjs/font/Helvetica'),
    padding: 10
  })
  doc.cell().text('Contract Title: ')
  .add(''.padStart(1))
  .add('abc', { underline: true, fontSize: 9 })

  try{
      const newImgsTable = doc.cell().table({ widths: [null] });
      let newImgsTableRow = newImgsTable.row({ lineHeight: 1.8 });
      let imageBuffer = await fse.readFile('./image-0.jpg');
      console.log(imageBuffer)
      newImgsTableRow.cell({ padding: 1 }).image(new pdf.Image(imageBuffer), { align: 'center' });
      doc.pageBreak();
  } catch(err) {
    console.log(err)
  }
  doc.pipe(fse.createWriteStream('output.pdf'))
  // render as pdf
  await doc.end()
})()

**As a result, the Buffer can be logged and pdf successfully generated after I yarn start the node. But the Image cannot be displayed.**

`<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 01 2c 01 2c 00 00 ff e2 0a 20 49 43 43 5f 50 52 4f 46 49 4c 45 00 01 01 00 00 0a 10 00 00 00 00 02 10 00 00 ... 669737 more bytes>`
<img width="341" alt="Screenshot 2020-04-28 at 10 56 03 AM" src="https://user-images.githubusercontent.com/34391995/80442330-3b5b3700-893f-11ea-93e6-36ae25c9019d.png">
<img width="1299" alt="Screenshot 2020-04-28 at 10 57 21 AM" src="https://user-images.githubusercontent.com/34391995/80442349-41e9ae80-893f-11ea-92dd-56dd7ae50ede.png">

**But when I test some other images, some images can be displayed and some can't. May I know what cause the issues and how to fix it?**

**Comment by Snuffleupagus** [comment]
It looks like this issue was opened against the wrong repository, based on the code-snippets, since you probably want https://github.com/rkusa/pdfjs instead.

---

Furthermore, when opening an issue here you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Note also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by telfordho** [comment]
Oh... Similar names. Thanks for noticing!

**Comment by telfordho** [comment]
Oh... libraries with similar names. Thanks for noticing!
