### ISSUE TITLE
IE/Edge not render text on canvas

### ISSUE THREAD

**Issue by VitaliyLavrenko** [mozilla/pdf.js#11856]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE/Edge
- Operating system and its version: Win 10
- PDF.js version: 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
1. Load PDF
2. Render page to canvas
3. Render text layer.

What is the expected behavior?
On canvas should be present text from PDF document, but at some reason in 75% it not render text on canvas, but TextLayer have text. Expected render text to be on canvas.

What went wrong? (add screenshot)
Missing text on canvas in IE/Edge.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
"pdfjs-dist": "2.3.200",

I have simple Code: Load PDF by URL, get page -> render on canvas -> render TextLayer. All other browser work good, IE/Edge we notify at some time not render text on canvas.

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by timvandermeij** [comment]
Given that it only happens in IE/Edge and also only sometimes, this seems like either an implementation issue (but no working demo is provided to be able to check this) or a browser-specific issue which should be reported to the vendor upstream. In general, we have seen that driver issues might be the cause of such issues, so I would recommend you to check that they are all up-to-date. There is not much more we can do here unfortunately.
