### ISSUE TITLE
No minified build for older browsers from 2.4.456

### ISSUE THREAD

**Issue by kleins05** [mozilla/pdf.js#11858]
There does not seem to be a way to build a minified version for older browsers. 

I used to use `gulp minified` as stated in the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#the-pdfjs-files-are-too-big-is-it-possible-to-obtain-minified-versions-of-the-js-files)

Since 2.4.456 produces a non-polyfilled build by default (SKIP_BABEL=true in gulpfile.js) and since we need to support IE11, this does not work anymore.

Whilst there is a gulp task _generic-es5_ to complement the _generic_ task, the same is missing for the _minified_ task. Is there another easy way to build a minified version for older browsers without modifying gulpfile.js? If not, would you accept a pull request, if I added it?

The FAQ should be updated, too, to mention that the minified task builds a modern browser version.

**Comment by Snuffleupagus** [comment]
> I used to use `gulp minified` as stated in the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#the-pdfjs-files-are-too-big-is-it-possible-to-obtain-minified-versions-of-the-js-files)

When the `-es5` build tasks were added, the main focus was on things needed for the builds that are published at https://github.com/mozilla/pdf.js/releases respectively https://github.com/mozilla/pdfjs-dist

> Is there another easy way to build a minified version for older browsers without modifying gulpfile.js?

No easy way currently, as far as I know.

> If not, would you accept a pull request, if I added it?

Well, that probably depends rather heavily on *exactly* what sort of solution you have in mind here.

Adding an *almost* verbatim copy of the existing `minified` task would be a non-started, and the only acceptable solution would be one that re-factors the existing build tasks such that the code is re-used between the `minified` and (new) `minified-es5` tasks. 

> The FAQ should be updated, too, to mention that the minified task builds a modern browser version.

Yes, that probably makes sense.

**Comment by timvandermeij** [comment]
I agree with the above. Having a new task `minified-es5` would indeed be acceptable if the existing code is re-used. You can take a look at the existing `-es5` tasks in the Gulpfile for inspiration. If such a solution can be made, we'll definitely review it.

**Comment by Snuffleupagus** [comment]
Having looked *briefly* at the relevant code, this is almost trivial to implement and done right the net increase is only ~10 lines of code; I might submit a patch at some point (time permitting).

**Comment by stephanrauh** [comment]
@kleins05 In the meantime, you can use the ES5 file of ngx-extended-pdf-viewer. You can get them as part of the project on npm (npm install ngx-extended-pdf-viewer) or on unpkgc.com: https://unpkg.com/browse/ngx-extended-pdf-viewer@3.2.6/assets/

BTW: I always create the ES5 file by modifying the Gulp file. It's just modifying the SKIP_BABEL line.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
