### ISSUE TITLE
Messy Code Rendered with PDFJS while Text Layers Seem Fine.

### ISSUE THREAD

**Issue by coolKIH** [mozilla/pdf.js#11857]
Attach (recommended) or Link to PDF file here:
[2020042702680_c.pdf](https://github.com/mozilla/pdf.js/files/4549490/2020042702680_c.pdf)

Configuration:
- Web browser and its version: Chrome/81.0.4044.122
- Operating system and its version: Macintosh; Intel Mac OS X 10_15_3
- PDF.js version: Stable v2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the problem PDF with PDFJS （Chinese is the primary language in the document)
2. Scroll to page 2 and see.
3. You'll find the content from page 2 is almost all messy code that is not readable.
4. Open the problem PDF with Chrome, Apple Preview, there's no rendering issue like this.
5. However, if you select and copy some messy text, the copied string looks correct, which is different from what is rendered in PDFJS.

What is the expected behavior?
The PDF should be rendered correctly. The screenshot takes page 4 as an example.
<img width="597" alt="Screen Shot 2020-04-29 at 10 23 25 AM" src="https://user-images.githubusercontent.com/20931311/80555827-0238ca80-8a04-11ea-9375-01463a375c04.png">

What went wrong?
Messy code rendered from page 2. The screenshot takes page 4 as an example.
<img width="556" alt="Screen Shot 2020-04-29 at 10 24 00 AM" src="https://user-images.githubusercontent.com/20931311/80555833-06fd7e80-8a04-11ea-9236-42487eef40ff.png">

**Comment by Snuffleupagus** [comment]
Looks fine in Firefox 77 on Windows, using PDF.js version `2.5.95`.

> PDF.js version: Stable v2.3.200

Can you reproduce using either version `v2.4.456` (i.e. the current pre-release), or with the [demo viewer](https://github.com/mozilla/pdf.js#online-demo)?

**Comment by timvandermeij** [comment]
Renders fine for me with Firefox 75.0 (64-bit) on Arch Linux.

**Comment by nkimadusanka** [comment]
Renders fine for me with Google chrome Version 79.0.3945.88 on Ubuntu.

**Comment by coolKIH** [comment]
> Looks fine in Firefox 77 on Windows, using PDF.js version `2.5.95`.
> 
> > PDF.js version: Stable v2.3.200
> 
> Can you reproduce using either version `v2.4.456` (i.e. the current pre-release), or with the [demo viewer](https://github.com/mozilla/pdf.js#online-demo)?

Yes, I am able to reproduce with the demo viewer.

I also tried Safari [Version 13.1 (15609.1.20.111.8)], which renders fine; and Firefox [Version 76.0.1], which has exactly the same problem as Chome [Version 81.0.4044.138] does.

(Sorry for the late reply. Thank you for your patience.)

**Comment by coolKIH** [comment]
> Renders fine for me with Firefox 75.0 (64-bit) on Arch Linux.

Not for Firefox 76.0.1 (64-bit) on Mac OS X 10.15.4.

**Comment by coolKIH** [comment]
When I opened the issue, I was using PDFJS local build v2.3.200.

Now with PDFJS v2.5.163 in the online demo, I am equally able to reproduce the issue with Firefox [Version 76.0.1] and Chome [Version 81.0.4044.138], both of which are the latest version at the time of writing.

**Comment by Snuffleupagus** [comment]
If this is consistently reproducible in different browsers on *one* platform, in this case MacOS, that could suggest a OS and/or possibly graphics driver problem rather than a PDF.js one.

If this actually is a PDF.js font conversion bug, then you'd generally expect it to be consistently broken *everywhere*; hence it's unfortunately (at the moment) not clear that this is an actionable PDF.js issue.

**Comment by timvandermeij** [comment]
Given that it seems to work on all platforms except MacOS, I would suggest to check the graphics driver for available updates since that could cause such corruption. I don't see anything we can do about this on the PDF.js side though.

**Comment by weibo785424079** [comment]
老哥，问题有解决吗
