### ISSUE TITLE
viewer.html in iFrame is causing other parts of my web page to no longer work

### ISSUE THREAD

**Issue by luther-cloudbase** [mozilla/pdf.js#11862]
Attach (recommended) or Link to PDF file here:
n/a - doesn't matter what pdf file

Configuration:
- Web browser and its version: Chrome Mac Version 81.0.4044.129 (Official Build) (64-bit)
- Operating system and its version: Mac OS not sure
- PDF.js version: Stable V2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. create a Quick Base application and embed the iFrame in a page and put viewer.html example into the iFrame; presumably, other web pages that have javascript capturing certain click and right-click events will also have this problem
2. Note that Form tabs, right-click events, and some other features do not work when the iFrame is displayed with viewer.html in it (which references viewer.css, viewer.js, pdf.js and pdf.worker.js)

What is the expected behavior? (add screenshot)
other events outside the iFrame would continue to work as before putting viewer.html in the iFrame

What went wrong? (add screenshot)
stated above

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
the three viewer files (css, html, js) in the web folder of the stable build download referenced above

**Comment by Snuffleupagus** [comment]
> create a Quick Base application
> ...
> Note that Form tabs, 

Unfortunately we have no idea what that "Quick Base" and "Form tabs" are, and generally we cannot really provide support for various (JavaScript) frameworks here.

---

Can you reproduce the problem when using the PDF.js library *directly*, with "Quick Base"?

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Without a running example this is not actionable for us unfortunately.
