### ISSUE TITLE
page counter is messed up for some pdfs

### ISSUE THREAD

**Issue by rogozind** [mozilla/pdf.js#11866]
In the attached PDF, when I open it the page counter is messed up:

![image](https://user-images.githubusercontent.com/10505245/80841718-fef13a80-8bcd-11ea-9858-cd782981d7d0.png)

[demo (3).pdf](https://github.com/mozilla/pdf.js/files/4566276/demo.3.pdf)

I simply downloaded the stable version, clicked on viewer.html and loaded that PDF.

 PDF 049b8fe5ed061983f78f5a8ae66f5ce2 [1.7 Acrobat Distiller 8.1.0 (Windows) / Elsevier] (PDF.js: 2.3.200)

**Comment by Snuffleupagus** [comment]
Duplicate of #11583

**Comment by rogozind** [comment]
Intersting, thank you!
