### ISSUE TITLE
Is it possible to extend pdf.js to support a new format?

### ISSUE THREAD

**Issue by xybei** [mozilla/pdf.js#11877]
Apologize first, this is not an issuer, but a question.

I need to render a new document format(similar to MS xps) using JavaScript, and it will take a lot of work if I start writing from scratch.

pdf.js is an excellent project, some work should be general for document rendering, so I want to try to expand pdf.js to support this new format. (I have some basics in PDF format)

My initial plan is to add a document parsing module, and use pdf.js as the backend for drawing, but I analyzed the class of CanvasGraphics in canvas.js and found that its APIs are designed for pdf syntax, unlike some PDF rendering engine in C language, there is a layer of general drawing API inside. In this case, I have to make a lot of changes to support the new document format, even impossible.

If I want to render the new format based on pdf.js, I want to know if the author has any good suggestions and which part is more suitable to start with.

Thanks to the authors of this excellent project！

**Comment by timvandermeij** [comment]
Some parts of PDF.js can probably be re-used, such as the viewer, but PDF.js entirely built for the PDF file format, so we can't know how much work it would be to implement another file format since we only support PDF files.
