### ISSUE TITLE
Render issue when scrolling PDFs with large JPEGs

### ISSUE THREAD

**Issue by johnhok** [mozilla/pdf.js#11878]
**Attach (recommended) or Link to PDF file here:**
[jpeg-scroll-issue.pdf](https://github.com/mozilla/pdf.js/files/4587118/jpeg-scroll-issue.pdf)

**Configuration:**
- Web browser and its version: Chrome 81.0.4044.138 (Official Build) (64-bit)
- Operating system and its version: macOS 10.15.4 (19E287) 
- PDF.js version: commit d822578450262db7290e2f33f14c6823b7140ad6 of this repo

**Steps to reproduce the problem:**
1. Open attached PDF
2. Scroll down to the middle of document
3. Observe page rendering

**What is the expected behavior?** 
When scrolling, the subsequent pages should render relatively quickly.

**What went wrong?**
The page is blank for awhile before the pages render.

## Additional Details

I believe that after this commit:
https://github.com/mozilla/pdf.js/commit/62a9c26cdae9118dea89dc18b5cad844bbc7faf5

The PDF attached starts to exhibit the described behaviour. When I revert that specific commit and test again, the render of the image is almost instantaneous.

I noticed that with the changes in the above commit, the chrome dev tools profiler shows an uptick of this routine that seems to be consuming the worker when scrolling in the document. 

![Screen Shot 2020-05-06 at 10 20 33 AM](https://user-images.githubusercontent.com/1030271/81188374-3cb1e280-8f83-11ea-976f-b6fa5d3e54d8.png)

**Comment by prashanthwagle** [comment]
s

**Comment by timvandermeij** [comment]
Fixed by the pull request above.
