### ISSUE TITLE
When new version releasing 

### ISSUE THREAD

**Issue by santoshprakash** [mozilla/pdf.js#11884]
Dear PDF.js Team , 

Im planning to upgrade pdf.js version. So let me if I can use **v2.4.456** as a stable version for development or let me know when this version officially getting a release.  

Otherwise, I will use **it v2.3.200**

**Comment by timvandermeij** [comment]
For now, use 2.3.200 since that's the stable version. It's not known yet when 2.4.456 will become stable.
