### ISSUE TITLE
Transform matrix doesn't work in Chrome

### ISSUE THREAD

**Issue by alexaaaant** [mozilla/pdf.js#11885]
Configuration:
- Google Chrome Version 81.0.4044.129:
- Window 10:
- PDF.js version 2.0.0:

I tried to apply a transformation matrix to the canvas context. In Firefox, this works; each page applies this matrix. But in chrome, only the first page of the PDF uses the matrix, while the other pages do not. Is this a problem with Google Chrome? Do I have other ways to apply the transformation matrix to all PDF files?
https://jsfiddle.net/alexaaaant/pwjkxuvz/17/

**Comment by Snuffleupagus** [comment]
> PDF.js version 2.0.0

Please note that that *exact* version number has never existed.



> I tried to apply a transformation matrix to the canvas context.

The only supported way of doing that is by providing the `transform` when rendering, as documented in the API; please see https://github.com/mozilla/pdf.js/blob/bf2ce760f0856eaebd2fc389b07932688b4449c9/src/display/api.js#L872-L898 and https://github.com/mozilla/pdf.js/blob/bf2ce760f0856eaebd2fc389b07932688b4449c9/src/display/api.js#L1004-L1020

**Comment by alexaaaant** [comment]
> > PDF.js version 2.0.0
> 
> Please note that that _exact_ version number has never existed.
> 
> > I tried to apply a transformation matrix to the canvas context.
> 
> The only supported way of doing that is by providing the `transform` when rendering, as documented in the API; please see
> 
> https://github.com/mozilla/pdf.js/blob/bf2ce760f0856eaebd2fc389b07932688b4449c9/src/display/api.js#L872-L898
> 
> and
> https://github.com/mozilla/pdf.js/blob/bf2ce760f0856eaebd2fc389b07932688b4449c9/src/display/api.js#L1004-L1020

I  tried but this did not work. 
https://jsfiddle.net/alexaaaant/2kuhn9gv/1/
Am i doing something wrong?

**Comment by alexaaaant** [comment]
Sorry, I saw my problem, I used matrix {...} instead [...] ,thank you
