### ISSUE TITLE
Rendering Issue 

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#11886]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 76.0.1 and Chrome Version 81.0.4044.129 
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension:no

Steps to reproduce the problem:
1. Open demo viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the attached PDF

What is the expected behavior? (add screenshot) It should appear as in current Firefox pdfjs viewer 

What went wrong? (add screenshot) Most of the PDF is overlayed by an orange background

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

The attached file renders correctly in the current Firefox pdfjs viewer but in the github demo viewer AND in our application the pdf renders incorrectly most of the page is obscured by an orange background

[29203_fccu-OutputPROOF.pdf](https://github.com/mozilla/pdf.js/files/4600333/29203_fccu-OutputPROOF.pdf)

**Comment by prashanthwagle** [comment]
Yes, the issue is present in Chrome 81 and Firefox 76. But Firefox 75 is rendering the pdf correctly.

**Comment by blackmambahk** [comment]
I noticed Firefox uses PDFJS 2.5 and renders correctly.
But using PDFJS 2.3 (stable) and 2.4(Beta) both render incorrectly.
Currently there is no v2.5 available on github it seems a FF specific version.
When will a generic v2.5 be available?

**Comment by timvandermeij** [comment]
2.5 is the alpha version that is not generally available. Firefox upstream periodically fetches the latest `master` version of PDF.js for testing in e.g., Firefox Nightly, but in general Firefox uses a version that is different from the releases.

Given that it works in 2.5, I can only assume a PDF.js patch or, more likely, an upstream Firefox patch fixed the rendering issue. Hence I don't think there is anything we can do here anymore.

**Comment by blackmambahk** [comment]
So no idea why FF works, it just does, and no idea when or if pdfjs will be fixed?
