### ISSUE TITLE
Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.) in Angular 8

### ISSUE THREAD

**Issue by rohitkumarMA94** [mozilla/pdf.js#11883]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by rohitkumarMA94** [comment]
Failed to load resource: The operation couldn’t be completed. (WebKitBlobResource error 1.) safari browser

**Comment by timvandermeij** [comment]
Without all information in the template, this is nothing we can do here.
