### ISSUE TITLE
PDF Print Text Corruption

### ISSUE THREAD

**Issue by jonwilks** [mozilla/pdf.js#11894]
At this time I cannot attache the original PDF or printed sample. It contains sensitive customer data. I am working to create a non-sensitive version of this issue and will append it to this issue. I will attempt to provide sufficient detail in the meantime.

Problem:
When PDF is printed (physically or to PDF), some text fields become corrupted, resulting in strings with new characters as well as missing characters. 

Details:

1. PDF's created via FOP 2.3
1. Only occurs on multi-page PDF's
1. Multi-page PDF's are created by stitching together multiple existing PDF's (via PDFBox)
1. Only noticed in bold fonts using embedded font subsets.
1. Occurring often in production, obstructing USPS tracking numbers & other critical information

Configuration:
- Firefox 76.0
- Mac OS 10.15.4, Windows 10 1909

Steps to reproduce the problem:
1. Open PDF in Firefox (pdf.js).
2. Innate print via button or menu.
3. Print to paper or to pdf.
4. Observe bold text fields. Notice the overlapped text in the string that is supposed to be "USPS Tracking". Also notice the introduction of alpha characters like 'K' into the tracking number string below the barcode which is supposed to be all numeric. 

What is the expected behavior?
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1147158/81603368-374a0300-939c-11ea-8237-ef8d9db6e509.png">

What went wrong? (add screenshot)
<img width="177" alt="image" src="https://user-images.githubusercontent.com/1147158/81603340-2d280480-939c-11ea-8f34-bbbe50d94cb9.png">

Problematic PDF:
- Print to PDF, you will notice issue on page three. 
[bad-1.pdf](https://github.com/mozilla/pdf.js/files/4729735/bad-1.pdf)

Problematic PDF Printed Result:
- See page three, text just above the 1D tracking barcode. Should say "USPS TRACKING #"
- See page three, text above sender address. Should say "USPS FIRST-CLASS PKG"
- See page three, text in small box between addresses. Should say "R005".
[bad-1-print.pdf](https://github.com/mozilla/pdf.js/files/4729741/bad-1-print.pdf)

**Comment by jonwilks** [comment]
Updated with PDF samples

**Comment by jonwilks** [comment]
Note - I am correlating the problem areas to specific fonts.

**Comment by jonwilks** [comment]
Following up on this.

**Comment by marco-c** [comment]
This appears to be working now, can you confirm @jonwilks?

**Comment by Snuffleupagus** [comment]
> This appears to be working now, can you confirm @jonwilks?

Given that there's been no response for over four months, let's close this as WORKSFORME for the time being.

**Comment by jonwilks** [comment]
Sorry for my absence. If it appears to be working that is good enough for me. Thanks y'all.
