### ISSUE TITLE
ios手机上展示的时候，后台传入数据流加载不出来，提示 Warning: AcroForm/XFA is not supported" viewer.js:6249:9

### ISSUE THREAD

**Issue by wyying** [mozilla/pdf.js#11899]
后台传入数据流，前台转为pdf的时候，在ios下，提示 Warning: AcroForm/XFA is not supported" viewer.js:6249:9这个，并且加载不出来，一直加载中，文件预览不全

**Comment by timvandermeij** [comment]
We can only help in English, and AcroForms are not supported by default, only experimentally.
