### ISSUE TITLE
ios6,7,8   open the 'view.html?file=****' is loading a long time by webview

### ISSUE THREAD

**Issue by qizhang01** [mozilla/pdf.js#11896]
open the 'view.html?file=****' is loading a long time by webview. why? But the same question no at android.

**Comment by qizhang01** [comment]
pdfversion= 2.4.456

**Comment by timvandermeij** [comment]
We can't help without all details from the issue template. There are already open issues for performance on iOS; see https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-os-ios+label%3A2-performance
