### ISSUE TITLE
Drag the scroll-bar slider to the bottom, last page is slow to load (but not if you press 'End' on the keyboard)

### ISSUE THREAD

**Issue by ewheelerinc** [mozilla/pdf.js#11902]
Attach (recommended) or Link to PDF file here:
Unfortunately, I can't because of NDA requirements, but I think you can reproduce it without---just find a big PDF of images (like an OCR'ed tagged document).

Configuration:
- Web browser and its version: Chrome 81, Firefox 68ESR (maybe 76, too)
- Operating system and its version: Linux / Windows
- PDF.js version: pdfjs-2.4.456-dist.zip
- Is a browser extension: No

Steps to reproduce the problem:
1. Load a large PDF and then scroll to the bottom by dragging the scroll-bar slider.

Note that it takes forever to load the last page.  However, if I just press "END" on my keyboard, it goes to the last page and loads quickly.   

I'm guessing that it is trying to load pages in order that they are "viewed."  If so, then this could be fixed by the Observer API (bug #10059) by or waiting a "dwell time" before rendering on mouse move.  The dwell time could probably be 10ms since I didn't dwell on any but the last page when I scrolled quickly by dragging the scroll bar to the bottom with my mouse.

What is the expected behavior? (add screenshot)
Load quickly

What went wrong? (add screenshot)

Was slow

**Comment by Snuffleupagus** [comment]
> but I think you can reproduce it without---just find a big PDF of images (like an OCR'ed tagged document).

Sorry, but you unfortunately *need* to provide a PDF document for this (or any) issue to be actionable/valid.
Given that two PDF documents can *look* very similar when rendered, that doesn't necessarily mean that they're actually using the same features.

> I'm guessing that it is trying to load pages in order that they are "viewed."

Yes, but please note that pages which are no longer visible will have their their parsing/rendering aborted to save resources. (With the exception of the 10 last seen pages, which are cached to improve general performance in the viewer.)

> If so, then this could be fixed by the Observer API (bug #10059)

Given that there are instances, in the default viewer, where we need to *synchronously* check which pages are visible it's somewhat doubtful if the "Observer API" would generally be a viable replacement for the `getVisibleElements` functionality used in the viewer.

> or waiting a "dwell time" before rendering on mouse move.

That should already be happening, by using `requestAnimationFrame`, please note https://github.com/mozilla/pdf.js/blob/8b9492a5c41d0776488a27021981b60fbf23a3bf/web/ui_utils.js#L162-L202

**Comment by Snuffleupagus** [comment]
@timvandermeij Given that this issue is still missing *crucial information* required to be actionable, and that there's been no answers thus far, should we close it as INCOMPLETE for now?

**Comment by Snuffleupagus** [comment]
@timvandermeij Given that this issue is still missing *crucial information* required to be actionable, and that there's been no additional information provided, should we close it as INCOMPLETE for now?
