### ISSUE TITLE
Pdf file stop loading into viewer suddenly with errors in console

### ISSUE THREAD

**Issue by WAHABTURK11** [mozilla/pdf.js#11906]
Configuration:
- Web browser and its version: Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Operating system and its version: Windows 10 (64-bit)
- PDF.js version: Version 2.0
- Is a browser extension: No

Suddenly stop loading pdf into viewer and gives error in console which are attached as screen shot.

What went wrong? (add screenshot)

![image (567)](https://user-images.githubusercontent.com/25074836/81976904-a779b280-9642-11ea-94f3-3aff09c44fb3.png)

![image (31)](https://user-images.githubusercontent.com/25074836/81977336-50c0a880-9643-11ea-8313-3bfd812acb31.png)

![image (32)](https://user-images.githubusercontent.com/25074836/81977356-57e7b680-9643-11ea-9955-8ceb9236d3df.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: Version 2.0

That *exact* version number has never existed; please find the latest releases at https://github.com/mozilla/pdf.js/releases

> Suddenly stop loading pdf into viewer and gives error in console which are attached as screen shot.

The screen-shots clearly show a *modified* default viewer, based on the toolbar, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
