### ISSUE TITLE
pdf2png example cannot render Japanese font

### ISSUE THREAD

**Issue by moznion** [mozilla/pdf.js#11900]
Configuration:
- Web browser and its version:
N/A? Just using pdf.js (8b9492a5c41d0776488a27021981b60fbf23a3bf) by node

- Operating system and its version:
macOS 10.15.3

- PDF.js version:
8b9492a5c41d0776488a27021981b60fbf23a3bf

- Is a browser extension:
N/A

Steps to reproduce the problem:
1. `curl -o issue.pdf https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/h25/pdf/n4100000.pdf`
2. apply the following diff:

```diff
--- a/examples/node/pdf2png/pdf2png.js
+++ b/examples/node/pdf2png/pdf2png.js
@@ -51,7 +51,7 @@ NodeCanvasFactory.prototype = {
 var pdfjsLib = require("pdfjs-dist/es5/build/pdf.js");

 // Relative path of the PDF file.
-var pdfURL = "../../../web/compressed.tracemonkey-pldi-09.pdf";
+var pdfURL = "issue.pdf";

 // Read the PDF file into a typed array so PDF.js can load it.
 var rawData = new Uint8Array(fs.readFileSync(pdfURL));
```

3. run `node pdf2png.js`

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/1422834/81829767-38cf2300-9576-11ea-896f-78f95e29ed77.png)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/1422834/81829813-45ec1200-9576-11ea-8e91-f1d48c15a5fb.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
This document is published by the Government of Japan: https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/h25/pdf/n4100000.pdf

**Comment by bobsingor** [comment]
Hi @moznion 

In order to support non-latin characters you have to include cMaps
These are located in node_modules/pdfjs-dist/cmaps

make sure to import NodeCMapReaderFactory:

```javascript
const { NodeCMapReaderFactory } = require('pdfjs-dist/lib/test/unit/test_utils');
```

then add NodeCMapReaderFactory and the cmap location to your getDocument call:

```javascript
PDFJSLib.getDocument({
  data: rawData,
  cMapUrl: 'node_modules/pdfjs-dist/cmaps/',
  cMapPacked: true,
  CMapReaderFactory: NodeCMapReaderFactory
}).promise;
```

This should solve your problem. Now you should see the japanese characters!
