### ISSUE TITLE
Gibberish text is seen on some fields

### ISSUE THREAD

**Issue by bksantiago** [mozilla/pdf.js#11909]
Attach (recommended) or Link to PDF file here:
[weird_text_blank.pdf](https://github.com/mozilla/pdf.js/files/4635069/weird_text_blank.pdf)

Configuration:

- Web browser and its version: Chrome 81.0.4044.129
- Operating system and its version: MacOS 10.15
- PDF.js version: 2.3.194
- Is a browser extension: Nope
Steps to reproduce the problem:

1. Set interactiveFields to true
2. Use the given PDF and open it via PDFJS viewer or in examples/acroforms/acroforms.html

What is the expected behavior?
- Blank fields should be displayed on the 2nd page

What went wrong?
- Gibberish text is being displayed on the 2nd page.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The PDF.js rendering matches for example the Okular rendering and the "gibberish" values are literally the field values of the annotations inside the PDF document, so I don't see anything wrong here.
