### ISSUE TITLE
Unable to load PDF in SVGViewer

### ISSUE THREAD

**Issue by chppatel** [mozilla/pdf.js#11916]
[5-19-20-7_29_32-PM.pdf](https://github.com/mozilla/pdf.js/files/4654338/5-19-20-7_29_32-PM.pdf)
We are trying to load a sample PDF file into SVGViewer. It comes out completely bank. Tried on version 2.2, 2.3 and 2.4

Both PDF file and Generated SVG attached.

![download (10)](https://user-images.githubusercontent.com/41402254/82398613-3b6fc380-9a21-11ea-9ff9-eb388c5f7b41.png)

**Comment by timvandermeij** [comment]
I have verified that this works on the current master branch. I have tested the SVG rendering mode in the default viewer, the SVG viewer example and the PDF to SVG converter Node.js example and they all produce the expected result now.
