### ISSUE TITLE
Garbled Display of Fonts

### ISSUE THREAD

**Issue by weisinger** [mozilla/pdf.js#11915]
Viewer:  https://mozilla.github.io/pdf.js/web/viewer.html
Chrome on Windows 10
When the attached PDF file is viewed, some of the fonts display as garbled text. 
[Arial, Courier, Times New Roman]
The file views correctly in Adobe Reader.
[fff.pdf](https://github.com/mozilla/pdf.js/files/4652174/fff.pdf)

**Comment by timvandermeij** [comment]
I can confirm this on Arch Linux with Firefox as well. The problem is that the fonts are not embedded in the PDF file.

**Comment by weisinger** [comment]
Yes ,there aren't any fonts embedded in the PDF.
But on Windows, these are standard fonts.  Should it be necessary to embed them?

**Comment by timvandermeij** [comment]
In general it's always necessary to embed them since it ensures that all viewers can properly display the PDF file. Not embedding fonts, even standard ones, means that not all viewers might be able to display the PDF file.

**Comment by cll0129** [comment]
请问怎么嵌入字体?

**Comment by zhanghaobin0927** [comment]
Use cool font, random code display box

**Comment by zhanghaobin0927** [comment]
Use cool font, random code display box
![image](https://user-images.githubusercontent.com/53521113/99924738-66432780-2d76-11eb-9e30-4bcadc4c76df.png)
