### ISSUE TITLE
Please take a look. Thank you

### ISSUE THREAD

**Issue by sunzhenxi** [mozilla/pdf.js#11928]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google
- Operating system and its version: Win10
- PDF.js version:  pdfjs-2.4.456-dist
- Is a browser extension: No

Steps to reproduce the problem:
1.  Now the resource goes to the local of win10, and the viewer.html file is used to preview the electronic invoice, but the content cannot be displayed. Please take a look. Thank you

**Comment by timvandermeij** [comment]
There is unfortunately nothing we can do without the actual PDF file. Closing until that is provided.

**Comment by sunzhenxi** [comment]
sorry provides originals immediately
[061002001111-55814662.pdf](https://github.com/mozilla/pdf.js/files/4673630/061002001111-55814662.pdf)
![error](https://user-images.githubusercontent.com/28771386/82755906-52d7f380-9e09-11ea-92d3-9b1312c99b3a.jpg)

**Comment by sunzhenxi** [comment]
![error](https://user-images.githubusercontent.com/28771386/82755939-8155ce80-9e09-11ea-9c97-2a4c3fba6460.jpg)

**Comment by timvandermeij** [comment]
This PDF file works fine if opened with https://mozilla.github.io/pdf.js/web/viewer.html, i.e., the latest development viewer. This means the issue will be fixed in upcoming releases.

**Comment by sunzhenxi** [comment]
Yes https://mozilla.github.io/pdf.js/web/viewer.html can be opened. The download to the local resource cannot be opened, and the display content is incomplete. cmaps introduces the address https://unpkg.com/pdfjs-dist@2.0.943/cmaps ok, but local offline resources will not work.
