### ISSUE TITLE
Cannot find module 'worker-loader!./build/pdf.worker.js' from 'webpack.js'

### ISSUE THREAD

**Issue by mcoates1** [mozilla/pdf.js#11925]
I am running `"react": "^16.13.1"` which was created using create-react-app. I am trying to run Jest tests and I keep getting the following error:

` Cannot find module 'worker-loader!./build/pdf.worker.js' from 'webpack.js'`

My import statement in my component looks like this:

`import { PDFJS } from 'pdfjs-dist/webpack'`

However, when I remove webpack from the import, the error goes away and things "seem" to work just fine.

`import { PDFJS } from 'pdfjs-dist'`

Can someone explain to me the difference between having webpack in the import statement vs not having it? Do I even need it? I've been trying to research this issue for days and have hit a wall so any input would be very helpful.

FYI, this is the version of pdfjs-dist that is in my package.json

`"pdfjs-dist": "^2.3.200"`

**Comment by mcoates1** [comment]
> @mcoates1 +1
> I'm noticing this issue as well. We notice this error as a result of installing the jupyter/latex package in jupyter lab which has pdfjs-dist as an upstream dependency.
> 
> Downstream issue is discussed [here](https://github.com/jupyterlab/jupyterlab-latex/issues/135)

@scottweitzner thanks for pointing me to the downstream issue. All I know is that pdfjs-dist uses webworkers and webworkers don't work well with Jest becuase Jest uses node from what I've read. I was hoping for a solution from the team. I've tried mocks and everything else I can think of.

**Comment by scottweitzner** [comment]
@mcoates1 No problem. It looks like the issue from my end was discussed and a fix was merged [here](https://github.com/mozilla/pdf.js/pull/11964). Looks like that change will resolve the downstream issue my team was having. 

I'd try pulling in the latest version once a patch release is made (most likely going to be v2.5.208). If that doesn't work then I'm afraid we might've had different issues with similar errors. Best of luck!

**Comment by abhimanusharma** [comment]
I am facing same issue, any resolution yet?

**Comment by benochr** [comment]
For me, adding following to the Jest configuration also worked.

```
moduleNameMapper: {
    'pdfjs-dist/webpack': 'pdfjs-dist',
}
```

**Comment by Snuffleupagus** [comment]
The `worker-loader` dependency was removed in PR #15430, so hopefully this is no longer a problem.
