### ISSUE TITLE
Chrome throws Aww Snap on specific PDF

### ISSUE THREAD

**Issue by hughanderson4** [mozilla/pdf.js#11922]
[check-this.pdf](https://github.com/mozilla/pdf.js/files/4663907/check-this.pdf)

PDF has been validated as 1.3 compliant.

It crashes all pdf.js based viewers.

**Comment by timvandermeij** [comment]
The file crashes the tab in Firefox 76.0.1 on Arch Linux too. Pages 1 to 3 render just fine, but page 4 crashes the tab. Interestingly, Okular is able to render page 4 immediately, so this indeed looks like an edge case is triggered in PDF.js. Thank you for reporting this!

**Comment by timvandermeij** [comment]
Fixed by the pull request above.

**Comment by hughanderson4** [comment]
Thanks so much for the swift response!
