### ISSUE TITLE
Is there any rotation viewer options ?

### ISSUE THREAD

**Issue by vic60400** [mozilla/pdf.js#11921]
Hi
I search a way to automaticaly rotate an iframe pdf (clockwise rotation).
Is there any rotation viewer options ?

Thanks in advance

PDF.js v2.3.2

**Comment by timvandermeij** [comment]
If you use the default viewer, you can emit the `rotatecw` or `rotateccw` on the event bus, which is the same as what clicking the buttons in the viewer would do.
