### ISSUE TITLE
incorrect position - FireFox browser

### ISSUE THREAD

**Issue by kk12837** [mozilla/pdf.js#11937]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: FireFox 76.0.1(64bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. open pdf.js view.html
2. upload pdf file.
3. it looks different between Chrome and FireFox

What is the expected behavior? (add screenshot)
![chrome](https://user-images.githubusercontent.com/7441223/82965390-8f1e7600-9ffa-11ea-81c8-965211cea887.png)

What went wrong? (add screenshot)
view on firefox
![firefox](https://user-images.githubusercontent.com/7441223/82965397-93e32a00-9ffa-11ea-9549-e92f112036cf.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Attachted pdf
[JRCHIST_wb_s1_1.1_t.pdf](https://github.com/mozilla/pdf.js/files/4685855/JRCHIST_wb_s1_1.1_t.pdf)

it is possible to reproduce on this link

https://mozilla.github.io/pdf.js/web/viewer.html

Thanks everyone

**Comment by Snuffleupagus** [comment]
This was *improved*, but not completely fixed, by PR #14175.
