### ISSUE TITLE
PDF.js Message: Unexpected server response (0) while retrieving PDF

### ISSUE THREAD

**Issue by MonkeyJian** [mozilla/pdf.js#11934]
We are suddenly getting this message on our iphone:

PDF.js v2.3.200 (build: 4ae3f9fc)
信息：Unexpected server response (0) while retrieving PDF "blob:http://xxxx/f87db189-19a2-4602-9118-b5a8e5fced4e

I get the data from server and it is binary stream.
like this http://180.169.30.6:8111/FZJ_testDic/1.png

If I use Andriod phone,it goes well
http://180.169.30.6:8111/FZJ_testDic/3.jpg

if I use IPhone,  I get the error there.
http://180.169.30.6:8111/FZJ_testDic/2.png

I also tried add '&.pdf' on end of the url, I get the same error there

Can anyone help?

**Comment by timvandermeij** [comment]
If it works on other machines, it's most likely an iOS platform/browser issue that should be reported upstream. They may not be able to handle blob URLs correctly. Unfortunately I don't think this is anything we can really help with.

**Comment by Serenade600** [comment]
https://wordpress.org/support/topic/unexpected-server-response-204-while-retrieving-pdf/
