### ISSUE TITLE
PDF rendered strangely

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#11931]
This PDF (the JPG image inside it) is rendered strangely. 

The three channels inside are RGB, while your parser thinks they are Y Cb Cr, and performs _convertYccToRgb()

Actually, the PDF in pdf.js looks the same as in Adobe Reader, but differently than in Chrome PDF viewer. But if you "cut out" a raw JPG file from the PDF, image viewers render it as the Chrome PDF viewer.

[head.pdf](https://github.com/mozilla/pdf.js/files/4679027/head.pdf)
[head.jpg](https://user-images.githubusercontent.com/15955558/82846232-1929ea00-9ee8-11ea-8f25-53a72b14160c.jpg)

**Comment by havocbcn** [comment]
In #11967 it's the explanation and the solution, I'm waiting further instructions for merging

**Comment by timvandermeij** [comment]
Fixed by the pull request above.
