### ISSUE TITLE
How to get canvas pagenum

### ISSUE THREAD

**Issue by glh20** [mozilla/pdf.js#11932]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
//============================
Hi, my english skill is so bad understand me
i want to make drawpen using canvas
so how to get canvas Pagenum
viewer.html, canvasWrapper, canvas id={page+pagenum}

![image](https://user-images.githubusercontent.com/57480200/82853606-27f0bb00-9f41-11ea-8831-fd27929bd397.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It's not really possible to fully understand what you're asking, but the `PDFViewerApplication` class holds a `page` getter that you can use: https://github.com/mozilla/pdf.js/blob/master/web/app.js#L534-L536
