### ISSUE TITLE
How to add token in http-headers?

### ISSUE THREAD

**Issue by SongJie123** [mozilla/pdf.js#11935]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows10
- PDF.js version: 2.0.943
- Is a browser extension: N

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
I'm expected to add token in http-headers.
What went wrong? (add screenshot)
In my project, I need to add the token in http-headers. However, I can't find the right place to add it. Could you please tell me how to add the token or where I can do it? I'm new at programming, so maybe the problem seems easy and stupid, but it will really help me a lot if you can answer it. Thank you very much. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You can pass additional HTTP headers in the default viewer (https://github.com/mozilla/pdf.js/blob/3b615e4ca369ff31e6399dea80383ffeffe96240/web/app.js#L714-L716) or though the API (https://github.com/mozilla/pdf.js/blob/3b615e4ca369ff31e6399dea80383ffeffe96240/src/display/api.js#L97) if you don't use the default viewer. They will be passed to the network stream that does the requests.
