### ISSUE TITLE
Ampersand & is replaced by &amp; when request a pdf file on s3

### ISSUE THREAD

**Issue by HaominZhang** [mozilla/pdf.js#11938]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: `Chrome 83.0.4103.61`
- Operating system and its version: `MacOS Catalina 10.15.4`
- PDF.js version: `mozilla.github.io/pdf.js/build/pdf.js`
- Is a browser extension: Yes

I am trying to access a pdf on s3 and the url contains multiple `&`. For example: `s3.amazon.com/files/file_name=abc.pdf&X-Amz-Algorithm=rs256&foo=bar`. When I use `dfjsLib.getDocument()`, I can see from the network that in the request the `&` replaced with `&amp;` which results in the failure of retrieving the pdf.

What is the expected behavior?

The `&` should be preserved in the request url

It used to work perfectly but I noticed it stopped working for me back in March 2020. Was there any changes made regarding this part? Is there a solution for this? Thanks

**Comment by Snuffleupagus** [comment]
> Was there any changes made regarding this part?

Assuming it used to work (and you know approximately when), then using `git bisect` to find out when/where it broke is probably the simplest solution.

> Is there a solution for this?

Unfortunately, without an actual runnable example this issue isn't really actionable; please see github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by Snuffleupagus** [comment]
Given that no reduced test-case has been provided, it's essentially impossible to do anything about this issue (assuming it even is a PDF.js problem in the first place); hence I'd suggest closing this as INCOMPLETE. /cc @timvandermeij
