### ISSUE TITLE
How to get the position of the text item 

### ISSUE THREAD

**Issue by wantao666** [mozilla/pdf.js#11936]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Chrome  80.0.3987.149（正式版本） （32 位）
- Operating system and its version:
windows10 professional
- PDF.js version:
Stable (v2.3.200)

i use the `page.getTextContent().then(data => { console.log(data) });` to get the text on the pdf like below.
![image](https://user-images.githubusercontent.com/29670394/82965053-a872f280-9ff9-11ea-93ea-b7c8323b465e.png)

 the question is that i only get the context  of the text ,but can't get the position of the text ,so how can i get the position of the text? 

i need the answer very eargerly.hope to reply soon.

**Comment by wantao666** [comment]
i see a line code in `pdf.js` like this `ctx.transform(scaleX, 0, 0, scaleY, positions[i], positions[i + 1]);`
means the last two params is the X position or Y position?
![image](https://user-images.githubusercontent.com/29670394/82969041-428a6900-a001-11ea-94f7-f128e0f4fcc7.png)

but i use the postion X and postion Y in canvas to draw a Rect. it's not the correct position,so how can i get the right position.
![image](https://user-images.githubusercontent.com/29670394/82969142-85e4d780-a001-11ea-968e-eaf1292a5d6d.png)

**Comment by Snuffleupagus** [comment]
Given that this issue is missing both the PDF document in question as well a link to any *runnable example*, this unfortunately isn't really actionable, hence the only suggestion would be to e.g. refer to the existing textLayer implementation found in https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js
