### ISSUE TITLE
Switch stable version on NPM

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11949]
It looks like updating NPM when making a release stable does not yet work, even though we looked into this before. I made version 2.4.456 stable today, but NPM still shows version 2.3.200. What did work is updating the `next` tag for pre-release 2.5.207, so it looks like the release script doesn't handle release updates correctly in contrast to release creations which work.

Please find the cause of this, and for now update the `latest` tag on NPM to version 2.4.456 manually.

**Comment by brendandahl** [comment]
Updated the tag.

**Comment by timvandermeij** [comment]
Hm, I'm not sure if it worked correctly. It has been updated, but it seems that the `v` prefix should not be there. Contrary to the GitHub tags, the NPM tags only consist of the version number. Visiting https://www.npmjs.com/package/pdfjs-dist/v/v2.4.456 also results in a not-so-gracefully handled React error on NPM, which is also surprising.

Could you re-push the latest tag with just `2.4.456` as version?

**Comment by JessWallin** [comment]
I am also getting an npm error as of this morning.

**Comment by timvandermeij** [comment]
Yes, NPM seems to have some problems with the tag name. Fortunately https://www.npmjs.com/package/pdfjs-dist/v/2.4.456 already exists, we just need to re-push the `latest` tag to fix this.

**Comment by trs** [comment]
There seems to be some issues with the latest tag and npm. Might be related to this issue.
https://www.npmjs.com/package/pdfjs-dist won't even load; `Service Unavailable`.

**Comment by brendandahl** [comment]
I update npm again. Though I used the same command as before but I guess not.

**Comment by timvandermeij** [comment]
This works now. Thanks!
