### ISSUE TITLE
PDF not properly displayed

### ISSUE THREAD

**Issue by andreamonni** [mozilla/pdf.js#1194]
pdf.js doesn't display properly this PDF:

http://db.tt/t3S8TU4V

It shows only the "template" but not the contents. I'm using:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:11.0) Gecko/20100101 Firefox/11.0
- with the latest version of the pdf.js addon from https://addons.mozilla.org/en-US/firefox/addon/pdfjs

And I've got these two errors in the error console:

Timestamp: 09/02/2012 12:22:52 PM
Error: downloadable font: rejected by sanitizer (font-family: "pdfFont2" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,AAEAAAAMAIAAAwBARFNJR47EJy8AAADMAAAacE9TLzJXOmJmAAAbPAAAAFZjbWFwMrJ/AwAAG5QAADI2Z2x5ZgAAAAAAAE3MAAAAAGhlYWTTMHMuAABNzAAAADZoaGVhBzACfwAATgQAAAAkaG10eHuuaPAAAE4oAAP/7GxvY2EAAAAAAAROFAAD...clipped...AAAEQQAABk

**Comment by brendandahl** [comment]
Sanitizer error is gone, but as mentioned above still rendered poorly

**Comment by ousia** [comment]
@andreamonni, impossible to test.

Please attach the PDF document to the issue.

**Comment by brendandahl** [comment]
Closing, the PDF doesn't exist anymore.
