### ISSUE TITLE
Pdf.js + Vue.js (v2.4 and up)

### ISSUE THREAD

**Issue by chppatel** [mozilla/pdf.js#11944]
We used SVGViewer for PDF.js and then on top we used Fabric and Vue.js to draw elements. In v2.3 it seems to work well but in 2.4 it seems to break in external libraries. Is this a larger code change and if so is there a docs on how to make it work?

**Comment by timvandermeij** [comment]
Given the limited information here, I can only assume it's related to what's stated in https://github.com/mozilla/pdf.js/releases:

```
From now on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the -es5-dist.zip suffix).
```

Therefore, library users must explicitly use the ES5 files if the solution is used for older browsers.
