### ISSUE TITLE
IE11-Print Preview Failed to Pop Up for Large Sized PDF

### ISSUE THREAD

**Issue by toniKantemirov** [mozilla/pdf.js#11956]
Hi dear all. 
I use ngx-extended-pdf-viewer.

When i click print icon in IE-11 and after "preparing document for printing window" pops up and fully prepares, the print preview window did not pop up for Large Sized PDF(for example 13 megabytes).
To compare: If we load the smaller sized PDF document, the print preview window does pop up. Please see attachment
[A17_FlightPlan.pdf](https://github.com/mozilla/pdf.js/files/4715957/A17_FlightPlan.pdf)

In Chrome everything works good.

Version info

Version of ngx-extended-pdf-viewer - 2
Desktop ()

Browser [basically Internet Explorer-11]

Created this problem before - https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/330

**Comment by Snuffleupagus** [comment]
> I use ngx-extended-pdf-viewer.

That's a *different* project, and consequently we cannot support that here.

You should test e.g. with https://mozilla.github.io/pdf.js/es5/web/viewer.html, but see below.

> In Chrome everything works good.
> [...]
> Browser [basically Internet Explorer-11]

Given that this problem is specific to IE11, there's unfortunately nothing that can be done here; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by timvandermeij** [comment]
Moreover:

> (for example 13 megabytes)

This is most likely way too much for IE, or any browser for that matter, to handle since canvases are generated for printing. This most likely exceeds memory limits.

There is no clear solution for this, other than (maybe) the experimental SVG back-end for printing only.

**Comment by toniKantemirov** [comment]
Thank you guys for all your answer.
