### ISSUE TITLE
Update https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#11959]
Following PRs https://github.com/mozilla/pdf.js/pull/11807 and https://github.com/mozilla/pdf.js/pull/11241, the ["Benchmarking your changes" Wiki-page ](https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes) needs to be updated to account for the recent changes/simplifications; I'd suggest the following changes for the respective sections (which I've successfully used in PR #11930):

```
$ git checkout master
$ gulp generic
$ cd test
$ node test.js --statsFile=stats/results/baseline.json --statsDelay=5000 --manifestFile=benchmark.json
```

```
$ cd ..
$ git checkout <feature-branch>
$ gulp generic
$ cd test
$ node test.js --statsFile=stats/results/current.json --statsDelay=5000 --manifestFile=benchmark.json
```

Finally, it's probably a good idea to also mention the `--noChrome` flag on that page as well.

**Comment by timvandermeij** [comment]
Done. Thank you!
