### ISSUE TITLE
Warning: JPX: Trying to recover from: JPX error: Out of packets

### ISSUE THREAD

**Issue by moxun33** [mozilla/pdf.js#11957]
Attach (recommended) or Link to PDF file here:
https://drive.google.com/file/d/1V3UKoqa3-WRiUlC1Mcg-iVQYib8bGACF/view?usp=sharing

Configuration:
- Web browser and its version: chrome 83.0
- Operating system and its version: Windows10 1909
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. view pdf on [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. fuzzy render  

What is the expected behavior? (add screenshot)
[![ttX51U.md.png](https://s1.ax1x.com/2020/06/02/ttX51U.md.png)](https://imgchr.com/i/ttX51U)

What went wrong? (add screenshot)
[![ttXIcF.md.png](https://s1.ax1x.com/2020/06/02/ttXIcF.md.png)](https://imgchr.com/i/ttXIcF)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome [extension): [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by yangwen1020053105** [comment]
How to solve this problem,please!

**Comment by timvandermeij** [comment]
This file is broken in Firefox too, with the following console log:

`Warning: JPX: Trying to recover from: JPX error: Out of packets`
