### ISSUE TITLE
Go over findings from static analyzers

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11965]
https://lgtm.com/projects/g/mozilla/pdf.js?mode=list is interesting and might provide PDF.js with some opportunities to improve the code.

**Comment by Snuffleupagus** [comment]
> https://lgtm.com/projects/g/mozilla/pdf.js?mode=list

The problem with that one, the last time I looked, was that it's fairly opinionated and that there doesn't appear to be a great way of ignoring *valid* patterns on e.g. a case-by-case basis.

**Comment by Snuffleupagus** [comment]
Recently LGTM has actually been helpful in flagging a couple of *valid* logical mistakes in new code, so I'm wondering if we should actually reconsider the decision to use its PR integration?

Looking e.g. at https://lgtm.com/help/lgtm/github-apps-integration, the setup doesn't look particularly difficult.

**Comment by Snuffleupagus** [comment]
> so I'm wondering if we should actually reconsider the decision to not use its PR integration?

Given that no objections have been raised here, I'll try to get the LGTM PR-integration setup sometime this week (assuming I've got the required permissions).

**Comment by timvandermeij** [comment]
Sorry, I forgot to reply. I agree that LGTM can be useful to integrate now that it has given some useful results and the false positives are (largely) silenced.

**Comment by Snuffleupagus** [comment]
As I (somewhat) suspected, enabling the LGTM PR-integration seem to require repository *ownership* since simple commit access doesn't appear to be enough.

@brendandahl When you've got time, mind following https://lgtm.com/help/lgtm/github-apps-integration to setup the LGTM PR-integration for this repository.

**Comment by Snuffleupagus** [comment]
Looking e.g. at https://github.com/mozilla/pdf.js/pull/13761/checks or https://github.com/mozilla/pdf.js/pull/13754/checks, it seems that LGTM has now been setup and that it's working :-)
