### ISSUE TITLE
Collect telemetry on all unsupported features

### ISSUE THREAD

**Issue by emalysz** [mozilla/pdf.js#11961]
In #11815, we collected telemetry on what error triggered the fallback bar. The first error message is what is shown in the fallback bar. We need expand this and collect telemetry on all error messages to give us a better understanding of the frequency of each type of error. 

Example with more than one error: 
https://www.irs.gov/pub/irs-pdf/f1040.pdf

**Comment by Snuffleupagus** [comment]
One possible way of doing this could be to decouple the showing of the fallback bar from the reporting of telemetry data, to not complicate e.g. the `PDFViewerApplication.fallback` method unnecessarily; perhaps something along these lines:

 - Remove the `PdfJsTelemetry.onFallback(featureId);` line from `ChromeActions.fallback`; see https://searchfox.org/mozilla-central/rev/559b25eb41c1cbffcb90a34e008b8288312fcd25/browser/extensions/pdfjs/content/PdfStreamConverter.jsm#499
 - Add a new case, e.g. "fallback" (or perhaps something better named) to the `switch`-block in `ChromeActions.reportTelemetry` (perhaps similar to the "documentStats" case); see https://searchfox.org/mozilla-central/rev/559b25eb41c1cbffcb90a34e008b8288312fcd25/browser/extensions/pdfjs/content/PdfStreamConverter.jsm#424-481
 - Always report telemetry in `PDFViewerApplication.fallback`, by adding something like
    ```javascript
   this.externalServices.reportTelemetry({
      type: "fallback",
      featureId,
   });
   ```
   immediately after line https://github.com/mozilla/pdf.js/blob/8fc1126b5a2b6d2fa0cfa98a061882ef21c1abc9/web/app.js#L865-L869

**Comment by emalysz** [comment]
Upstream bug to add telemetry in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1643402
