### ISSUE TITLE
How to check whether the pdf is compressed or not?

### ISSUE THREAD

**Issue by Nandhan-augment** [mozilla/pdf.js#11962]
I need to check whether the pdf is compressed or not. 

I tried with a compressed pdf file but got isCompressed: false as in the output. 

 CMapReaderFactory: DOMCMapReaderFactory { baseUrl: null, isCompressed: false },

Is there any way to find this? 

Thanks in advance

**Comment by Snuffleupagus** [comment]
> I need to check whether the pdf is compressed or not.

What do you actually mean by "compressed" here?

In PDF documents streams *may* use different filters (thus implying some form of data compression), but the filters used usually varies considerably for different streams even in a single document.

> CMapReaderFactory: DOMCMapReaderFactory { baseUrl: null, isCompressed: false },

Most likely CMaps have nothing to do with this issue...

---

Finally, as-is this issue isn't really actionable; when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Nandhan-augment** [comment]
OS: Ubuntu 18.04.4 LTS
PDF.js version: "pdfjs-dist": "^2.0.943" 
I'm using pdfdist npm to identify the properties of a pdf in backend nodejs.
I got a compressed pdf file of size 10mb but its actual size is more than 120MB. I need to find whether the pdf is compressed or not before I need to convert the pdf to jpg.
