### ISSUE TITLE
Support webassembly

### ISSUE THREAD

**Issue by this-spring** [mozilla/pdf.js#11968]
maybe just a idea:>
Why not use webassembly to parse PDF into YUV or ARGB to render through canvas？

**Comment by Snuffleupagus** [comment]
Unfortunately this

**Comment by Snuffleupagus** [comment]
This issue unfortunately seem too far from being actionable/valid as-is, and consequently it's probably not meaningful keep it open; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by this-spring** [comment]
ok, thanks i know.
