### ISSUE TITLE
hi，Can I insert a picture in the Preview PDF？

### ISSUE THREAD

**Issue by infosecliqin** [mozilla/pdf.js#11979]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
PDF.js is only a renderer, not an editor.
