### ISSUE TITLE
Feature Request Load All Thumbnails by default

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#11981]
Please correct me if i am wrong but not all thumbnails are generated unless the user scrolls downward to the last of the page.

I do not see any option that will generate all thumbnails on load so this is a feature request.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, hence no such option will be added (since a thumbnail is essentially just a page at a smaller size).
