### ISSUE TITLE
Background rendered outsize document's bounds 

### ISSUE THREAD

**Issue by keean** [mozilla/pdf.js#11986]
It seems the background (white page) is rendered outside the size of the document. In other words the white rectangle of the page is bigger than viewport.width * viewport.height. This causes problems when drawing multiple PDF images to the same canvas, or when you want to manipulate the document in the canvas (pan/zoom/rotate for example).

This affects all PDF files I have tried.

This seems to affect all web browsers I have tried, but specifically the current released versions of Firefox, Chrome and Safari, on both Linux and Mac OS X, using the current pdfjs-dist from npm.

To reproduce the problem, render the page smaller than the canvas, for example:

```typescript
public async animationFrame(context: CanvasRenderingContext2D): Promise<void> {
    if (!this.pdf) {
        return;
    }
    const canvas = createCanvas(context.canvas.width, context.canvas.height);
    const cxt = canvas.getContext('2d');
    const page = await this.pdf.getPage(1);
    const vp = page.getViewport({
        scale: 1
    });
    cxt.scale(0.5, 0.5);
    await page.render({
        canvasContext: cxt,
        viewport: vp,
    }).promise;
    context.drawImage(canvas, 0, 0);
}
```

I was able to work around this problem by setting the background of the PDF to transparent (render with option "background: 'rgba(0,0,0,0)'") and drawing the page background myself by inserting the following two lines immediately before the call to render.

```typescript
cxt.fillStyle = 'white';
cxt.fillRect(0, 0, vp.width, vp.height);
```

**Comment by Snuffleupagus** [comment]
Given the lack of overall lack of information here, since the all of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is missing *and* that only code-snippets are provided[1], this issue unfortunately doesn't really seem actionable as-is.

---

[1] Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
