### ISSUE TITLE
Show black square with JPXDecode pdf files

### ISSUE THREAD

**Issue by kenwhale** [mozilla/pdf.js#11991]
Attach (recommended) or Link to PDF file here:
[3.pdf](https://github.com/mozilla/pdf.js/files/4763757/3.pdf)

Configuration:
- Web browser and its version: Chrome 76.0.3809.87
- Operating system and its version: Windows 10
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1. open pdf
2.

What is the expected behavior? (add screenshot)
![normal](https://user-images.githubusercontent.com/26761743/84367550-f77a7380-ac06-11ea-9302-b6923de97368.jpg)

What went wrong? (add screenshot)
![show](https://user-images.githubusercontent.com/26761743/84367469-ddd92c00-ac06-11ea-9404-416622ee771a.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by linfangrong** [comment]
https://github.com/mozilla/pdf.js/pull/13698
