### ISSUE TITLE
Replace the `webpack-stream` dependency

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#11996]
With PR #11436 we became locked at a *particular* (older) version of the [`webpack-stream` dependency](https://www.npmjs.com/package/webpack-stream), because of bugs in the latest versions; see https://github.com/mozilla/pdf.js/pull/11436#issuecomment-568430643 for details.

Looking at the [GitHub-page for `webpack-stream`](https://github.com/shama/webpack-stream), it unfortunately seems that the project may be unmaintained/dead at this point given that the latest commit was in 2018.
Hence, rather than trying to update `webpack-stream` it's probably better to attempt to replace it completely instead (possibly with our own code if necessary) to ensure that we'll be able to e.g. update to Webpack 5 when it's released (which will likely be needed to *properly* support new ECMAScript features).

**Comment by timvandermeij** [comment]
This dependency is now updated to the most recent version in #12397. However, given that's it's a very inactively maintained dependency I also think we should get rid of it. Moreover, we only seem to be using it in one place in the Gulpfile...

**Comment by timvandermeij** [comment]
Now that we're using Webpack 5, the dependency got updated and there was more development on their GitHub page, do we still want to do this?

**Comment by Snuffleupagus** [comment]
> Now that we're using Webpack 5

Given that the Webpack upgrade *itself* wasn't actually blocked by the `webpack-stream` dependency, as I incorrectly assumed previously, I suppose this reduces the severity of this issue considerably.

> the dependency got updated and there was more development on their GitHub page, do we still want to do this?

To me, this all depends on whether or not they'll try to re-introduce the broken caching mechanism (which originally forced us to pin the version number).

> I guess we could make https://github.com/mozilla/pdf.js/blob/master/package.json#L61 use `^` instead of `~` now.

I suppose that could work, as long as we remember to check `webpack-stream` for any possible breakage when updating the npm packages (which I've been doing the last few times).
If you want to submit a PR with this change, and then simply close this issue, then please be my guest :-)
