### ISSUE TITLE
Remove extraction log suppression code

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11998]
I filed https://github.com/puppeteer/puppeteer/issues/5741 before and it just got fixed upstream. If version > 3.3.0 is released, we should upgrade and remove the extraction log suppression code since it's not necessary anymore.

**Comment by adbindal** [comment]
Hi @timvandermeij, I was wondering if the issue is closed or not. If yes, does it automatically gets closed via a bot or somebody needs to do it manually?

**Comment by timvandermeij** [comment]
It's not closed yet because the Puppeteer update did not work out, which is tracked in #12123. Indeed issues get closed automatically by GitHub if a pull request that lists that it fixes the issue is merged.

**Comment by timvandermeij** [comment]
We should also be able to remove the `--wait-for-browser` option passing that we currently do manually after commit https://github.com/puppeteer/puppeteer/commit/054d782c823c363c418bf478b0dbefa26673b358 is released upstream.
