### ISSUE TITLE
pdfjs.getDocument() read normal on Windows, failed on Linux

### ISSUE THREAD

**Issue by jazzwsr** [mozilla/pdf.js#11995]
Attach (recommended) or Link to PDF file here:
hello :)

Configuration:
- Web browser and its version:
  Electron 4.2.12
- Operating system and its version:
  Ubuntu 18.0
- PDF.js version:
  pdfjs-dist: 2.2.228
- Is a browser extension:
  No

Steps to reproduce the problem:
1. 
code: pdfjs.getDocument(url:'file://home/user/test.pdf')
2.
result: Get http://localhost:9080/home/user/test.pdf 404 (Not Found)

What is the expected behavior? (add screenshot)
I hope the PDF data can be read and displayed normally

What went wrong? (add screenshot)
I guess it's browser permissions

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Yes, most browsers disallow local file access; see https://stackoverflow.com/questions/14052473/go-to-local-url-with-javascript for instance. This is a browser limitation, not a PDF.js one.
