### ISSUE TITLE
pdf js pdf parsing something wriong

### ISSUE THREAD

**Issue by ersanjay1995** [mozilla/pdf.js#12006]
I used node package https://www.npmjs.com/package/pdf-parse I debug code that package does not do for the pdf parse they used pdf.js lib. 

probles indepth 
on JSON you can check the JSON data value {"text":"
-   for wrong-output screenshot you can see only one character. 
 -  for correct-output screenshot  {"text":"Honors & ....  full text on pdf 

Attach (recommended) or Link to PDF file here:
[Resume-Sanjay-Makwana.pdf](https://github.com/mozilla/pdf.js/files/4792295/Resume-Sanjay-Makwana.pdf)

Configuration:
- Web browser and its version: Google chrome  Version 80.0.3987.162
- Operating system and its version: Ubuntu 18.04
- PDF.js version: pdfjsVersion = '2.0.164
- Is a browser extension:no 

Steps to reproduce the problem:
1. some of the pdf data get properly some of pdf get every character  this the issue on pdf parse getting every character 
2.

What is the expected behavior? (add screenshot)
![correct-output](https://user-images.githubusercontent.com/14358976/84895968-c693b600-b0c0-11ea-8ff4-e114e6f3a340.png)

What went wrong? (add screenshot)
![wrong-output](https://user-images.githubusercontent.com/14358976/84896001-cc899700-b0c0-11ea-826b-2c4200b81599.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I used node package https://www.npmjs.com/package/pdf-parse I debug code that package does not do for the pdf parse they used pdf.js lib.

That is a *completely* different project, which is not affiliated with the PDF.js library and consequently we simply cannot provide support for that here; please ask for support from that project instead!

> PDF.js version: pdfjsVersion = '2.0.164

That version is not an official release, and furthermore it's too old to be supported; please find the latest PDF.js releases at https://github.com/mozilla/pdf.js/releases

> some of the pdf data get properly some of pdf get every character  this the issue on pdf parse getting every character

Unfortunately this is nowhere near enough information in order for an issue to be actionable/valid here; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
