### ISSUE TITLE
How to use FindController to navigate between matches programmatically?

### ISSUE THREAD

**Issue by m1stermanager** [mozilla/pdf.js#12014]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 83.0.4103.61
- Operating system and its version: OSX 10.14.6
- PDF.js version: pdfjs-dist 2.4.456
- Is a browser extension: no

Steps to reproduce the problem:
N/A? More of a question

What is the expected behavior? (add screenshot)
N/A

What went wrong? (add screenshot)
N/A

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

I am attempting to use `pageMatches` property on the `PDFFindController` to build a list of all matches. I would like to let a user click on one of the matches in the list and "jump" to that match as opposed to just navigating to 'next' and 'previous'. I have dug through a good amount of the pdf.js source on find controller etc and it seems like I need to navigate to the match _and_ advance the `_offset`. Is there a way to do this without extending the entire `PDFFindController`? Is there a specific event I can emit, or a particular method I'm overlooking.... or is the best path forward to extend the controller in some way so that this is possible?

**Comment by m1stermanager** [comment]
so far I've come up with the following.... if someone can tell me all of the reasons this is a bad idea please feel free :) 

This is part of a "find wrapper" i have on my side, which is a pretty simple class that just wraps up some of the details of constructing and interacting with the `FindController`, as well as gluing together the `FindBar` and `FindController`..... 

part 1 - transform the matches:
```
const matches = this.controller.pageMatches
    .flatMap((pm, i) => {
        if (pm.length) {
            return pm.map((x, j) => ({
                pageIndex: i,
                matchIndex: j,
                matchLocation: x
            }));
        }

        return [];
    })
```

part 2 - go to the match (potentially horrible idea to manipulate `FindController.selected` when one of the results is clicked....
```
this.controller.selected.pageIdx = match.pageIndex;
this.controller.selected.matchIdx = match.matchIndex;

this.linkService.page = match.pageIndex + 1;
this.eventBus.dispatch('updatetextlayermatches', {
    source: this,
    pageIndex: -1
});
```

I'm somewhat shocked at this point that it works.... I haven't put it through its paces... but I don't think its going to take _too much_ effort to tighten up any issues that will arise.

**Comment by m1stermanager** [comment]
one more note:

In order for this to work alongside the `FindBar` "next" and "previous" buttons, I had to (unfortunately) break into the non-public api for the first time....

```
this.controller._offset.pageIdx = match.pageIndex;
this.controller._offset.matchIdx = match.matchIndex;
```

If this is considered a low-hanging-fruit/easy-first-item.... I would really not mind at all creating a "moveToMatch" function or something on the public api for this. Since I've broken into the non-public api for the first time I feel like I should probably extend the PDFFindController in my instance but I feel like this is definitely useful functionality..... I'd love to create a PR for this if it is something you want in this project.

**Comment by joelpeter94** [comment]
@m1stermanager , This is great. I tried the similar approach on `updatefindmatchescount` event. It highlights the text, but does not scroll to the selected pageIdx and matchIdx. Am I missing something?

**Comment by ArkojeetSuntel** [comment]
> @m1stermanager , This is great. I tried the similar approach on `updatefindmatchescount` event. It highlights the text, but does not scroll to the selected pageIdx and matchIdx. Am I missing something?

Did you find any way to achieve that scroll to matchID?

**Comment by joelpeter94** [comment]
@ArkojeetSuntel Nope, But I used something very basic to achieve it 
``` document.getElementsByClassName("highlight")[0].scrollIntoView({ behavior: "smooth", block: "center", inline: "nearest" });```

Maybe there is a better way to do it, Let me know in case you find anything better

**Comment by bgresens** [comment]
iframeDocument.PDFViewerApplication.pdfViewer.findController.nextMatch(); worked for me
