### ISSUE TITLE
Cannot View PDF file uploaded to web folder

### ISSUE THREAD

**Issue by AGrinthal** [mozilla/pdf.js#12015]
Attach (recommended) or Link to PDF file here: any file

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  we use CuteSoft AJAX uploader to upload pdf file to our server
2. File Owner is "NETWORK SERVICE"
we cannot view the file unless we change the owner of the file to one of the other user accounts on the server.  It appears that viewerJS is looking at the owner of the file or permissions in order to view file.  If I FTP the same file to the server Viewer JS will read it. 
 
I guess my question is how does ViewerJS use file permissions to enable/disable viewing?  Not a whiz with user accounts/permissions but it appears this "Issue" has something to do with the ownership tagged onto the file when it's uploaded.  ANy direction you could give would be appreciated.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
ViewerJS is another project, so we cannot provide support here. Please file the issue at the ViewerJS project.
