### ISSUE TITLE
Open PDF without having the file path embedded on website?

### ISSUE THREAD

**Issue by jrektenwald** [mozilla/pdf.js#12013]
Is it possible to load a PDF without having the native path (which every user can change itself) on the website?

Like load it with $_POST or everything else?

**Comment by timvandermeij** [comment]
It's possible to provide binary/base64 input; see https://github.com/mozilla/pdf.js/blob/96ad60f116f420945daa29dea185eac6e558d67e/src/display/api.js#L94-L96 and https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html
