### ISSUE TITLE
Viewer not working on edge

### ISSUE THREAD

**Issue by vic60400** [mozilla/pdf.js#12019]
Configuration:
- Web browser and its version: Edge lastest
- Operating system and its version: Win10 lastest build
- PDF.js version: v2.5.207
 

Steps to reproduce the problem:

1. go to edge https://michelis.lyc.ac-amiens.fr/pdfjs/web/viewer.html?file=/upload/manuel-scolaire-2020-2021.pdf

2. work on chrome/firefox

**Comment by nhterry** [comment]
It works for me on Edge Lastest (chromium)

![image](https://user-images.githubusercontent.com/1258740/85447345-5ebeee80-b54a-11ea-8a69-b11d74b17b71.png)
