### ISSUE TITLE
iOS and Android Printing Error (Multiple Pages Per Sheet vs. 1 and Missing Pages)

### ISSUE THREAD

**Issue by nhterry** [mozilla/pdf.js#12020]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/es5/web/viewer.html

Configuration:
- Web browser and its version: Android 10 and iOS 13.5.1
- Operating system and its version: Chrome 83.0.4103.106 and Current Safari
- PDF.js version:  v2.5.207
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to Viewer https://mozilla.github.io/pdf.js/es5/web/viewer.html
2. Press Print

What is the expected behavior? (add screenshot)
1 Page per sheet should be shown and printed from the print dialog.

What went wrong? (add screenshot)
Pages are resized to show 4 per sheet (incorrect sizing). The pdf has 14 pages.  Only 3 pages are actually passed to the print dialog.

![image](https://user-images.githubusercontent.com/1258740/85443071-b3ac3600-b545-11ea-9da2-aa296bd5657a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/es5/web/viewer.html

![image](https://user-images.githubusercontent.com/1258740/85443197-d3435e80-b545-11ea-8c19-57aa01125506.png)

**Comment by Snuffleupagus** [comment]
Unfortunately this looks more like a platform/browser bug, rather than a PDF.js one, and the web-platform has (in general) quite limited support for controlling printing via JavaScript; hence I wonder if it makes sense to keep this issue open when it's unlikely to be fixable here!?

**Comment by rodrix3855** [comment]
It's a PITY that bugs related to printing are being closed. Please do not close them.
Let them community work on them.

Printing does not work on Android or iOS. So we have NO printing on mobile right now making this library useless.
I am happy to collaborate to fix this in any way I can.
