### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by dharmatv** [mozilla/pdf.js#12029]
Hi 
I am getting an error as when I load pdf file from another domain

https://snipboard.io/68QYLi.jpg

Please help me out

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

**Comment by dharmatv** [comment]
Thanks for your reply @Snuffleupagus. I am getting the file from different domains (I don't know, the pdf file came from which domain), so this solution(https://gist.github.com/yurydelendik/3452072) won't work
And I am not using any ajax, just I am loading file by using this library.
Could u please provide any other solution for this issue

**Comment by Snuffleupagus** [comment]
Given that this is a *browser* limitation (put in place for security reason), and not a PDF.js library one, we cannot really provide support for that here.

(Also, opening issues with basically no actionable information and/or runnable code provided isn't really a great way to ask for help in general...)
