### ISSUE TITLE
Large pdf is not geting printed in IE 11

### ISSUE THREAD

**Issue by sumitkumar121** [mozilla/pdf.js#12025]
When i try to print a large pdf . Few page is getting printed properly, Rest of page get printed with Blank Mark. It doesn't contain all the page.

**Steps to reproduce**

1. Open PDF with IE11
2. Print

**PDF File**
[test-9.pdf](https://github.com/mozilla/pdf.js/files/4831537/test-9.pdf)
[Original File.pdf](https://github.com/mozilla/pdf.js/files/4831539/Original.File.pdf)

**Configuration:**
- Web browser and its version: IE 11
- Operating system and its version: windows 10
- PDF.js version: v2.3.200
- Is a browser extension: NO

**What is the expected behavior?**
it should have printed all page of pdf

**What went wrong?** 
it is printing few page only.

**Comment by Snuffleupagus** [comment]
Unfortunately, browser support for custom printing (controlled by e.g. JavaScript) simply isn't that great in general; furthermore please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by sumitkumar121** [comment]
@Snuffleupagus is there any way by which i can print it properlyin IE 11

**Comment by Snuffleupagus** [comment]
> is there any way by which i can print it properlyin IE 11

Did you actually read all of https://github.com/mozilla/pdf.js/issues/12025#issuecomment-649553329, since it explains that IE11 is basically unsupported?

**Comment by timvandermeij** [comment]
Closing as answered.
