### ISSUE TITLE
How can i open local file using pdf.js ? i need this for create cordova application

### ISSUE THREAD

**Issue by ShamsSayied** [mozilla/pdf.js#12022]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: cordova android 8.0.0
- Operating system and its version: cordova android app
- PDF.js version: pdfjs-2.4.456-dist
- Is a browser extension: no

Steps to reproduce the problem:
1. i want to view a pdf file using pdf.js dist so that i can create a offline pdf reading app but it dont open local pdf file how can i fix this. is there any way to some code into my index html so that it can open default od any local pdf ?
2. i just want to open a local pdf with pdf.js without any help of servers. i want to use something like file:///book.pdf without http:// or https:// is there any way? help me with that

What is the expected behavior? (add screenshot)
https://imgur.com/Zqbdw4V
What went wrong? (add screenshot)
https://imgur.com/arzBl2N
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Browsers by default disallow access to local files; refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr for solutions.

**Comment by ShamsSayied** [comment]
Is there any way to forcefully open pdf by using viewer.html from local? when i use open file button to select pdf then it can show pdf normally so i think there must be a way to do this. @timvandermeij please helm me with that i want to create cordova cross platform app using pdf.js and i don't want to use any other pdf reader.
