### ISSUE TITLE
How can I show 2 PDFs in the same page ?

### ISSUE THREAD

**Issue by HarmanBajaj** [mozilla/pdf.js#12026]
- PDF.js version: 2.0.943

I wanted to show 2 PDFs in the same page, what all things I should take care if I am using above PDF.js version.

**Comment by timvandermeij** [comment]
First of all, always use the latest release, version 2.4.456 as of writing.

I'm assuming you mean rendering two PDF files after each other. You should be able to do something like in https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L40-L64, but in your case create two loading tasks and draw the pages onto separate canvases.
