### ISSUE TITLE
上传打包后无法进行预览

### ISSUE THREAD

**Issue by jiahui336** [mozilla/pdf.js#12033]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other t
![image](https://user-images.githubusercontent.com/54309037/85943141-abe2fc00-b960-11ea-975c-c16baf37ba1e.png)
han mozilla.github.io/pdf.js or as Firefox/Chrome extension):只出来一个框

**Comment by timvandermeij** [comment]
Support is only provided in English and with _all_ details provided.
