### ISSUE TITLE
What is the meaning of x/y coordinates in the array items of textContent.items?

### ISSUE THREAD

**Issue by johnsmith0209** [mozilla/pdf.js#12031]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Node.js v12.16.2.
- Operating system and its version: MacOS Catalina 10.15.3 (19D76)
- PDF.js version: 2.3.200
- Is a browser extension: no

I noticed that the origin of the PDF coordinate systems is on the left bottom corner, where canvas puts it on the left top corner. 
And I can get x/y from transform[4]/transform[5] in the array items of textContent.items.

But I can not figure out the meaning of x/y coordinates in the array items of textContent.items. Is it the left top point of the array items, or the left bottom point?

```javascript
(async() => {
    const doc = await PDFJS.getDocument({
        data: new Uint8Array(fs.readFileSync(YOUR_PDF_PATH)),
        CMapReaderFactory: NodeCMapReaderFactory,
        cMapUrl: path.join(__dirname, 'node_modules/pdfjs-dist/cmaps/'),
        cMapPacked: true,
    }).promise;

    const page = await doc.getPage(PAGE_NUM);
    const textContent = await page.getTextContent();
    /** array item
    {
        dir:"ltr"
        fontName:"g_d0_f1"
        height:8
        str:"xxxxxxx"
        transform:Array(6) [12, 0, 0, 12, 45, 797]
        width:30.908
    }
    */
})()
```
As the `transform` showed above, coordinate of the item is `x=45, y=797`.
So, is the coordinate the left top point of the item, or the left bottom point?

**Comment by jansensan** [comment]
@johnsmith0209 I believe that it is the bottom left corner. While trying to get the highlighted/underlined content relative to annotations (which is not easy so far), I have been rendering `<div>`s with an outline to see those coordinates, here is what I have so far:

    page.getTextContent().then(
      (textContent) => {
        textContent.items.forEach(item => {

          // get item dimensions and position
          // from transform matrices
          const tx = pdfjsLib.Util.transform(
            viewport.transform,
            item.transform
          );
          const itemX = tx[4];
          const itemY = tx[5] - item.height;

          // display block
          const block = createBlock('text-block');
          block.style.width = `${ item.width }px`;
          block.style.height = `${ item.height }px`;
          block.style.left = `${ itemX }px`;
          block.style.top = `${ itemY }px`;

          block.innerText = item.str;
          block.style.fontSize = `${ item.height }px`;
          block.style.fontFamily = item.fontName;

          document.body.appendChild(block);
        });
      }
    );

Since it's the bottom x position, I subtract the height so this can be positioned in CSS properly.

I am using `"pdfjs-dist": "^2.4.456"` which is why I use `pdfjsLib`. Take that into account, as I see you are using the `PDFJS` object.

**Comment by johnsmith0209** [comment]
@jansensan 
Really appreciated! 
Days ago, I try to place texts & paths to the canvas when assuming the x / y is the left bottom corner of left bottom point. The rendered result is pretty well, but I can not be sure about it.
It can not be more clear without your thorough explanation. Thanks~
