### ISSUE TITLE
Basic import of `pdfjsViewer` with typescript

### ISSUE THREAD

**Issue by coler-j** [mozilla/pdf.js#12030]
How do you do it? Seems like the `@types` are significantly messed up, this library is very difficult to use.

`import * as pdfjsViewer from ' ...............' `?

**Comment by Snuffleupagus** [comment]
This library doesn't have any (official) TypeScript definitions; that's tracked in issue #7909.

**Comment by coler-j** [comment]
Do I need to do something special to be able to use this library?

I installed `pdfjs-dist` from `npm`
I am using `parcel-bundler` to bundle my files

I have an html file like this:

```
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Example</title>

    <link rel="stylesheet" href="../node_modules/pdfjs-dist/web/pdf_viewer.css">

    <script src="../node_modules/pdfjs-dist/build/pdf.js"></script>
    <script src="../node_modules/pdfjs-dist/web/pdf_viewer.js"></script>

  <style>
    * {
      margin: 0;
      padding: 0;
    }
    .page {
      position: relative;
    }
    </style>
  </head>

  <body>
    <div id="pageContainer"></div>
    <script src="./form.js"></script>
  </body>
</html>
```
And a `form.js` like this

```
"use strict";

pdfjsLib.GlobalWorkerOptions.workerSrc =
  "../node_modules/pdfjs-dist/build/pdf.worker.js";

var DEFAULT_URL = '/pdfs/fw4.pdf';
var DEFAULT_SCALE = 1.0;

var container = document.getElementById("pageContainer");

var eventBus = new pdfjsViewer.EventBus();

// Fetch the PDF document from the URL using promises.
var loadingTask = pdfjsLib.getDocument(DEFAULT_URL);
loadingTask.promise.then(function (doc) {
  // Use a promise to fetch and render the next page.
  var promise = Promise.resolve();

  for (var i = 1; i <= doc.numPages; i++) {
    promise = promise.then(
      function (pageNum) {
        return doc.getPage(pageNum).then(function (pdfPage) {
          // Create the page view.
          var pdfPageView = new pdfjsViewer.PDFPageView({
            container: container,
            id: pageNum,
            scale: DEFAULT_SCALE,
            defaultViewport: pdfPage.getViewport({ scale: DEFAULT_SCALE }),
            eventBus: eventBus,
            annotationLayerFactory: new pdfjsViewer.DefaultAnnotationLayerFactory(),
            renderInteractiveForms: true,
          });

          // Associate the actual page with the view and draw it.
          pdfPageView.setPdfPage(pdfPage);
          return pdfPageView.draw();
        });
      }.bind(null, i)
    );
  }
});
```

I just get ` ReferenceError: pdfjsLib is not defined`. It is like `pdfjsLib` is not in global / window scope.
Following some other tickets in the issues here (https://github.com/mozilla/pdf.js/issues/10283), if I `var pdfjsLib = require("pdfjs-dist");` then I get error `pdfjsViewer is not defined`.

But there does not seem to be an accessible import for `pdfjsViewer` nor for the `EventBus` constructor.

**Comment by koogle** [comment]
I think you are looking for 
```
import * as pdfjsViewer from "pdfjs-dist/web/pdf_viewer";
```

**Comment by HoldYourWaffle** [comment]
The above suggestion works at runtime, but TypeScript complains that it "can't find module `pdfjs-dist/web/pdf_viewer` or its corresponding type declarations". As far as I can tell these typings are in `node_modules/pdfjs-dist/types/web/pdf_viewer.d.ts`, but the compiler can't find them for some reason. I've fiddled a bunch with `tsconfig.json` settings, but to no avail...

Has someone gotten this to work?
