### ISSUE TITLE
Warning: Setting up fake worker

### ISSUE THREAD

**Issue by dharmatv** [mozilla/pdf.js#12055]
Configuration:
- Web browser and its version: chrome and 83
- Operating system and its version: ubuntu 18.04
- PDF.js version:  (pdfjs-dist: 2.4.456)
- Is a browser extension: No

Error:
Warning: Setting up a fake worker

Problem:
1. Pdf didn't get a preview
https://snipboard.io/NPh69r.jpg

Whenever I had included the following worker, but pdf won't be loading in local and production (Tested in Security Disable Cross-browser mode and without SDC browser)

import { getDocument } from 'pdfjs-dist'
require("../../../node_modules/pdfjs-dist/build/pdf.worker.js");

And I have tried one more thing is as follows, but pdf won't be loading In local and production (It has worked in, with SDC browser and hasn't worked in SDC browser)

import { getDocument } from 'pdfjs-dist'
import pdfjsLib from "pdfjs-dist/webpack"

At finally I saw issues list here, So tried the following solution :

I have tried each and every solution in the following link, but no use.
[https://github.com/mozilla/pdf.js/issues/12055](https://github.com/mozilla/pdf.js/issues/7612)
[https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/136](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/136)

Could u please suggest any solution

**Comment by Snuffleupagus** [comment]
In https://github.com/mozilla/pdf.js/issues/11990#issuecomment-642502429 it's shown how set the `workerSrc` correctly; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dharmatv** [comment]
Thanks for reply @Snuffleupagus 
but i had tried, but no use

**Comment by Snuffleupagus** [comment]
No one will be able to help you if you won't follow the requests for more information, since without *runnable code* it's simply impossible to tell from a distance what's wrong!
