### ISSUE TITLE
[PDF to SVG, Text/Glyphs] How to have the reel text (remapped) into the exported svg?

### ISSUE THREAD

**Issue by Hideman85** [mozilla/pdf.js#12053]
Hi community, I wanna to have the correct text exported into my svg instead of the private area glyphs.

From what I read (https://github.com/mozilla/pdf.js/issues/10205) this is intended to map the text to a private glyphs area and also related to text selection. In my case I don't need text selection but I prefer to have the correct text into my svg.

I'm using your [example code](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js) that is working well but unfortunately don't remap the text to the correct letters. Do I have a way to get the correct text? maybe by extending the `SVGGraphics` class?

**Comment by Snuffleupagus** [comment]
If you carefully read through issue #10205, you'll see that this is not possible to support without breaking font rendering in *many* cases; note in particular https://github.com/mozilla/pdf.js/issues/10205#issuecomment-435416384 and the referenced PR https://github.com/mozilla/pdf.js/pull/9340 (which fixed *lots* of font bugs).

**Comment by Hideman85** [comment]
I already seen this topic and yes it's speaking about breaking changes and why they have been done I'm just wondering if I can get the old behavior or not? When I go back to the version `pdfjs-dist@2.0.550` it's perfectly working I as wanted to.
