### ISSUE TITLE
How to change language when using PDF.js Viewer?

### ISSUE THREAD

**Issue by rjakshayjain13** [mozilla/pdf.js#12067]
I am using pdf.js viewer.html to display PDFs. PDF.js used to have an option of passing 'locale' as a hash parameter to the viewer, but that has been removed. I went through all the issues, but could not find a proper reason why that was done. Why was 'locale' hash parameter removed?

### Given that 'locale' hash parameter is long gone, how to implement localization for pdf.js viewer?

**Comment by Snuffleupagus** [comment]
>  I went through all the issues, but could not find a proper reason why that was done. Why was 'locale' hash parameter removed?

See #4954.

> Given that 'locale' hash parameter is long gone, how to implement localization for pdf.js viewer?

Assuming that you're referring to the default viewer, i.e. https://github.com/mozilla/pdf.js#online-demo, then you'll need to set the `locale` *before* the viewer has been initialized which can be done with e.g. 
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("locale", "localeCode-here");
});
```

See also https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage, and please keep the following in mind http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by rjakshayjain13** [comment]
Thanks @Snuffleupagus 
I tried to set the locale by adding an event listener as you suggested, but the function inside the listener is never called.
```
document.addEventListener("webviewerloaded", function() {
    PDFViewerApplicationOptions.set("locale", "it");
    console.log("webviewerloaded event listener function called!");
});

var iframeElem = document.getElementById("iframe-el");
iframeElem.src = "http://sample.com/pdfjs/viewer.html?file=sample.pdf#pagemode=none";
```
I debugged the code to make sure that event listener is added before the event is dispatched, and that happens in the right order. Is there something else that needs to be done besides this?

**Comment by timvandermeij** [comment]
> Edit: Also it would be great if the page https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage could be made accessible for anyone from the Wiki section's main page: https://github.com/mozilla/pdf.js/wiki.

This is done now. Thank you for the suggestion.

**Comment by rjakshayjain13** [comment]
Thanks Tim

**Comment by Snuffleupagus** [comment]
Based on https://github.com/mozilla/pdf.js/issues/12067#issuecomment-655791086, this looks like a duplicate of issue #11829 which is fixed in the (current) pre-release; see https://github.com/mozilla/pdf.js/releases

More generally though, when opening an issue please make sure to always provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) upfront to both save time and to get better answers :-)

**Comment by rjakshayjain13** [comment]
Thanks @Snuffleupagus 
I apologize for omitting some important details in my first question. I thought that was insignificant, but do realize now that was not the case. I will take care from next time :)

**Comment by rjakshayjain13** [comment]
I was able to verify that v2.5.207 fixes this issue. 
Do we know (approximately) when this release will be declared stable?

**Comment by blindspeed90** [comment]
For anyone else looking for this answer, maybe the code changed since 2020, but now you have to do:

document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("localeProperties", {lang:"ja"});
});

I tried "lang" and "locale" variants with just "ja", and they don't work.

**Comment by zby909** [comment]
> 对于其他正在寻找此答案的人来说，代码可能自 2020 年以来发生了变化，但现在您必须执行以下操作：
> 
> document.addEventListener("webviewerloaded", function() { PDFViewerApplicationOptions.set("localeProperties", {lang:"ja"}); });
> 
> 我尝试了仅使用“ja”的“lang”和“locale”变体，但它们不起作用。

thank you bro
