### ISSUE TITLE
Some files cannot be displayed as pdf

### ISSUE THREAD

**Issue by akippiko** [mozilla/pdf.js#12062]
Attach (recommended) or Link to PDF file here: 
[binary_hacks_smpl.pdf](https://github.com/mozilla/pdf.js/files/4877088/binary_hacks_smpl.pdf)

Configuration:
- Web browser and its version: Google Chrome 83
- Operating system and its version: Mac OS 10.15.5
- PDF.js version: 1.7.225

Steps to reproduce the problem:
1. If you display the above attachment with pdf.js, it will not be displayed correctly.
Most PDF files can be displayed, but some attached files may not be displayed.
The script is below.

```
            var BASE64_MARKER = ';base64,';

            function convertDataURIToBinary(dataURI) {
                var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
                var base64 = dataURI.substring(base64Index);
                var raw = window.atob(base64);
                var rawLength = raw.length;
                var array = new Uint8Array(new ArrayBuffer(rawLength));

                for (var i = 0; i < rawLength; i++) {
                    array[i] = raw.charCodeAt(i);
                }
                return array;
            }
            var pdfAsDataUri = "{!content}";
            var pdfAsArray = convertDataURIToBinary(pdfAsDataUri);

            var canvasContainer = document.getElementById('content'); // Target Element
            var options = options || {scale: 1};

            function renderPage(page) {
                var viewport = page.getViewport(options.scale);
                var canvas = document.createElement('canvas');
                var ctx = canvas.getContext('2d');
                var renderContext = {
                    canvasContext: ctx,
                    viewport: viewport
                };

                canvas.height = viewport.height;
                canvas.width = viewport.width;
                canvasContainer.appendChild(canvas);

                page.render(renderContext);
            }

            function renderPages(pdfDoc) {
                for (var num = 1; num <= pdfDoc.numPages; num++)
                    pdfDoc.getPage(num).then(renderPage);
            }
            PDFJS.disableWorker = true;
            PDFJS.getDocument(pdfAsArray).then(renderPages);
```
What is the expected behavior? (add screenshot)
![screenshot](https://user-images.githubusercontent.com/2056123/86562332-7f049980-bf9d-11ea-9a0f-317e2799657a.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.7.225

That version is more than *three* years old, and is thus no longer supported. You need to update to the *latest* release, please see https://github.com/mozilla/pdf.js/releases

> The script is below.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Given that your PDF document opens just fine in the default viewer, see https://github.com/mozilla/pdf.js#online-demo, the most likely explanation (besides the really old PDF.js version) is that you didn't set the cMap-parameters when calling `getDocument`; see https://github.com/mozilla/pdf.js/blob/c4255fdbfd76ab3e14b33a546c6348394a857d38/src/display/api.js#L127-L130
