### ISSUE TITLE
Get bookmarks in own viewer

### ISSUE THREAD

**Issue by Nais0ne** [mozilla/pdf.js#12069]
Hi, is there any way to access the bookmarks of a PDF file like i access the text with `page.getTextContent()` ? either the bookmarks of all pages or every single page, doesn't really matter. Building my own UI and couldn't find a way to implement this with looking through the prebuilt-viewer.
If this is the wrong place to ask for help with core features of pdf.js, not related to the prebuilt-viewer, please show me where i should ask instead.

Thanks in advance :)

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/blob/cf8daaf78bf9a2cd0487f5a17116835419db4ec5/src/display/api.js#L691-L710 and https://github.com/mozilla/pdf.js/blob/cf8daaf78bf9a2cd0487f5a17116835419db4ec5/web/pdf_outline_viewer.js
