### ISSUE TITLE
es5

### ISSUE THREAD

**Issue by CHHome** [mozilla/pdf.js#12065]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Why are there Promise in ES5-compatible？  is wrong in IE 9

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Why are there Promise in ES5-compatible?

They are polyfilled with the `core-js` library.

> is wrong in IE 9

As clearly explained in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is the lowest supported version (and has been for a couple of years now).
