### ISSUE TITLE
Release of pdfjs-dist

### ISSUE THREAD

**Issue by optii** [mozilla/pdf.js#12068]
Hi,

we have been following this Merge request: https://github.com/mozilla/pdf.js/pull/11964 that should solve an issue we are having. However we can see it has been merged to https://github.com/mozilla/pdfjs-dist but that there hasn't been a release of that library. Is there a release scheduled ? 

Thanks for your time,

**Comment by timvandermeij** [comment]
You can find all official releases on https://github.com/mozilla/pdf.js/releases. The `pdfjs-dist` library is for the NPM package and that follows the same release scheme. For example, the current pre-release is also available using the `next` tag; see https://www.npmjs.com/package/pdfjs-dist/v/next
