### ISSUE TITLE
Worker crashes on IE 11

### ISSUE THREAD

**Issue by ksocha** [mozilla/pdf.js#12064]
Worker crashes when using version >= 2.3.200 on IE 11. I've tried pdfjs-dist versions 2.5.207, 2.4.456 and 2.3.200 (using es5 when available) with no success.

Everything works with v2.2.228.

**Configuration:**
- Web browser and its version: IE 11
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200 and higher
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Try to open PDF using the above browser

**What is the expected behavior?**
PDF should render

**What went wrong?**
Worker crashes with error visible at the screenshot:
<img width="334" alt="Screenshot 2020-07-06 at 19 25 55" src="https://user-images.githubusercontent.com/25787552/86621953-6311ef80-bfbf-11ea-9f6b-0c00f7a52538.png">

After clicking the source file it points to:
<img width="609" alt="Screenshot 2020-07-06 at 19 26 29" src="https://user-images.githubusercontent.com/25787552/86621999-7329cf00-bfbf-11ea-92ed-d846a8b6cc2e.png">

**Comment by Snuffleupagus** [comment]
https://mozilla.github.io/pdf.js/es5/web/viewer.html works for me in IE11, when running on Windows 7.
Does the latest demo viewer work for you?

> Worker crashes with error visible at the screenshot:

The filename suggests *some* kind of custom implementation, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

However, please note the *very limited* IE 11 support as explained in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by FireFoxRookie** [comment]
The pop-up box for printing 40 files printed by IE browser is hidden automatically. What's the reason?
