### ISSUE TITLE
Unable to use local file: MissingPDFException

### ISSUE THREAD

**Issue by dstrube1** [mozilla/pdf.js#12078]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/4892465/test.pdf)

Configuration:
- Web browser and its version:
Chrome - Version 83.0.4103.116 (Official Build) (64-bit)

- Operating system and its version:
MacOS Catalina Version 10.15.5

- PDF.js version:
Latest (just built yesterday)

- Is a browser extension:
No

Steps to reproduce the problem:

(Note, this only occurs if I run the script locally on my machine. If I run it from a webserver, it works fine.)

1. In the same folder, I have these 4 files: pdf.js, pdf.worker.js, test.html, and test.pdf
2. If I set var url = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf';, then it works fine, displays Hello World
3. If I set var url = 'http://dstrube.oit.gatech.edu/test/test.pdf';, then I get this error:
UnknownErrorException: Failed to fetch
4. If I set var url = 'test.pdf';, then I get this error:
MissingPDFException: Missing PDF "file://[path to file]".

What is the expected behavior? (add screenshot)
The page renders the pdf and an alert pops up with the text from the pdf. (This is how it behaves in the viewer link below.)
<img width="910" alt="Screen Shot 2020-07-08 at 14 24 06" src="https://user-images.githubusercontent.com/7396679/86956756-996a7e80-c127-11ea-950e-53cb9f678144.png">

What went wrong? (add screenshot)
If var url = 'http://dstrube.oit.gatech.edu/test/test.pdf', then I get this error:
UnknownErrorException: Failed to fetch:
<img width="433" alt="Screen Shot 2020-07-08 at 14 15 47" src="https://user-images.githubusercontent.com/7396679/86955436-8f478080-c125-11ea-9101-c28696c2cd0e.png">
If var url = 'test.pdf', then I get this error:
MissingPDFException: Missing PDF "file://[path to file]".:
<img width="442" alt="Screen Shot 2020-07-08 at 14 17 29" src="https://user-images.githubusercontent.com/7396679/86955635-e5b4bf00-c125-11ea-8213-ce20f8c0f04f.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://dstrube.oit.gatech.edu/test/test.html

**Comment by Snuffleupagus** [comment]
> Note, this only occurs if I run the script locally on my machine. If I run it from a webserver, it works fine.

Please see https://github.com/mozilla/pdf.js#getting-the-code, where it's explicitly mentioned that you need to use a web server in order for things to work correctly.
This is a limitation of browsers, rather than the PDF.js library, and as such this issue is INVALID.
