### ISSUE TITLE
http changed to https automatically

### ISSUE THREAD

**Issue by kinmt1234** [mozilla/pdf.js#12079]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Mac OS
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

I am getting the error message says "GET https://www.example.com/sample.pdf net::ERR_CERT_COMMON_NAME_INVALID". However what I am passing is "http://www.example.come/sample.pdf", not 'HTTPS' I am not sure where it was changed to "https" even I passed "http". Please help

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I am getting the error message says "GET https://www.example.com/sample.pdf net::ERR_CERT_COMMON_NAME_INVALID".

That's not actually a valid PDF document, so it's not at all clear that this is a good example.

> However what I am passing is "http://www.example.come/sample.pdf", not 'HTTPS'

The PDF.js library won't change the protocol of a provided URL, hence it has to be e.g. your browser which changes that.

---

All-in-all, given that *most* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is missing this issue unfortunately isn't actionable/valid as-is (and it looks like a *browser* issue anyway). 

Note also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
