### ISSUE TITLE
some Files chinese word lost

### ISSUE THREAD

**Issue by goonwzz** [mozilla/pdf.js#12073]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome 83.X
- Operating system and its version:
- PDF.js version:last version
- Is a browser extension:yes

Steps to reproduce the problem:
1. disply by demo

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by goonwzz** [comment]
should be[normal](https://compeition-skin.oss-cn-beijing.aliyuncs.com/issues/nomo.jpg)
but [abnormal](https://compeition-skin.oss-cn-beijing.aliyuncs.com/issues/20200708103319.jpg)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *required* in order for the issue to be actionable/valid.

> PDF.js version:last version

You need to provide an actual version number, since "last version" could mean any number of things.
