### ISSUE TITLE
Highlighting in viewer.js skips part of the text

### ISSUE THREAD

**Issue by zila661** [mozilla/pdf.js#12074]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 7
- PDF.js version: 2.6.100
- Is a browser extension: No

Steps to reproduce the problem:
1. Download document from this link: https://eur-lex.europa.eu/legal-content/RO/TXT/PDF/?uri=OJ:C:2019:199:FULL&from=NL
2. Open the file on viewer.js hosted by Mozzila latest version, go to page 5 and try selecting entire 3. paragraph
https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)

Should highlight entire paragraph
![Capture2](https://user-images.githubusercontent.com/10809475/86919573-bce1f900-c128-11ea-80ce-1801a068c116.PNG)

What went wrong? 
![Capture1](https://user-images.githubusercontent.com/10809475/86918432-fe71a480-c126-11ea-9e65-dca820a264bd.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ThomasLuyckx** [comment]
I found the same page, but in another document and the situation is worse there: https://eur-lex.europa.eu/legal-content/RO/TXT/PDF/?uri=CELEX:52019XX0614(02)&from=EN

![Capture](https://user-images.githubusercontent.com/31488926/87001489-dda55f80-c1b7-11ea-9fa2-426e8ec1172d.PNG)
