### ISSUE TITLE
Target build ECMAScript modules (pdfjs_dist)

### ISSUE THREAD

**Issue by Betalos** [mozilla/pdf.js#12075]

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you provide *a lot* more information/context than only a (slightly cryptic) title; that way you save everyone's time!

This might be a duplicate of #10317, but that's only a guess given the lack of context.

**Comment by Betalos** [comment]
@Snuffleupagus, I am sorry for not including a description of the issue, the thing is I taught the title was self explanatory.
The pdfjs_dist only includes commonjs/amd distributions.
