### ISSUE TITLE
PDF中编辑文本域

### ISSUE THREAD

**Issue by qiaohailiang** [mozilla/pdf.js#12086]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. PDF打开后自带的文本域消失，不能编辑，但是在浏览器默认打开PDF是可以编辑的

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by qiaohailiang** [comment]
有没有可配置的地方设置成打开效果和浏览器一样，能编辑，然后保存提交到服务器

**Comment by timvandermeij** [comment]
We can only assist in English and with _all_ required issue template details provided.

**Comment by qiaohailiang** [comment]
After PDF is opened, its own text field disappears and cannot be edited. However, PDF can be edited by default in the browser. Is there a solution?
