### ISSUE TITLE
How to Resize PDF when window resizes?

### ISSUE THREAD

**Issue by IIPatternII** [mozilla/pdf.js#12084]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chromium (Electron 9.10)
- Operating system and its version: MacOs 10.15.4
- PDF.js version: 2.4.456
- Is a browser extension:

Steps to reproduce the problem:
1.  Copy the [simplewiewer.js example](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js)
2. click on the edge of the window and resize it.

What is the expected behavior? (add screenshot)
Pdf resizes to fit the viewport size like it does when using the viewer.html
![image](https://user-images.githubusercontent.com/48034748/87213591-70e7ad80-c2fc-11ea-9f25-1bc6c826a3b2.png)
![image](https://user-images.githubusercontent.com/48034748/87213612-7fce6000-c2fc-11ea-80d7-4dc635e9b0f6.png)

What went wrong? (add screenshot)
Pdf maintains it's size
![image](https://user-images.githubusercontent.com/48034748/87213448-6f69b580-c2fb-11ea-9847-8cd349b3f03c.png)
![image](https://user-images.githubusercontent.com/48034748/87213455-814b5880-c2fb-11ea-9879-1a332090d113.png)

**Comment by Snuffleupagus** [comment]
> Copy the [simplewiewer.js example](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js)

That example is *purposely* a simple one, focusing on the basic usage of `PDFViewer` (and related components), without more advanced features. You can look at how e.g. the default viewer implements this:
https://github.com/mozilla/pdf.js/blob/7dabc5ecc8347fbda8ce4a219c182790d9ec9187/web/app.js#L2193-L2208
together with (basically) a `window.addEventListener("resize", webViewerResize);` event-handler.
