### ISSUE TITLE
Bundle pdf.js with Rollup

### ISSUE THREAD

**Issue by mustafa0x** [mozilla/pdf.js#12088]
Reasons:
- https://github.com/Rich-Harris/bundler-comparison#results

An analysis on bundlers:
- https://twitter.com/jaffathecake/status/1277879396074995714

**Comment by Snuffleupagus** [comment]
There doesn't seem to be anywhere near enough context/information provided *here*, to make this an actionable/valid issue for the PDF.js project, considering that replacing the *entire* build system would be a very significant undertaking (and definitely less of a priority compared to e.g. fixing rendering bugs).

All-in-all, the following paragraph from https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md seems relevant:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our Matrix room at https://chat.mozilla.org/#/room/#pdfjs:mozilla.org.

**Comment by timvandermeij** [comment]
I agree. We're open for pull requests, but unless there are major problems with Webpack right now we're not considering doing this.

**Comment by mustafa0x** [comment]
Thanks guys. Apologies, it was just a general suggestion — something to maybe consider for the future. I appreciate that such a big change is likely not a priority.
