### ISSUE TITLE
Add UI to control what optional content is visible

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#12096]
Once #12095 lands, we should add a UI view similar to the other side bar views that controls what optional content layers are visible.

To do this we'll need to:
- add a class similar to PDFOutlineViewer
- wire that class to set the visibility of the groups in the OptionalContentConfig 
- pass in the modified OptionalContentConfig to page.render()
- add a test that changes what groups are visible

**Comment by brendandahl** [comment]
For example acrobats layer panel:
![image](https://user-images.githubusercontent.com/942640/87484060-24e18500-c5ea-11ea-86ff-6aeacb600602.png)

**Comment by Snuffleupagus** [comment]
The implementation is sort-of hacky, and it's some way from being complete (missing e.g. a toolbar icon, proper CSS-styling, a way to reset the visibility to default, and probably more), but it does work quite nicely as-is:
https://github.com/brendandahl/pdf.js/compare/oc...Snuffleupagus:optional-content-viewer

**Comment by Snuffleupagus** [comment]
The following implementation (to my surprise) works quite well, even though it's currently a little rough around the edges:
https://github.com/brendandahl/pdf.js/compare/oc...Snuffleupagus:optional-content-viewer

**Comment by Snuffleupagus** [comment]
The implementation is sort-of hacky, and it's some way from being complete (missing e.g. a toolbar icon, proper CSS-styling, a way to reset the visibility to default, and probably more), but it does work quite nicely as-is:
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:optional-content-viewer

**Comment by Snuffleupagus** [comment]
The following implementation (to my surprise) seems to works quite well, despite it being a little rough around the edges:
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:optional-content-viewer

**Comment by Snuffleupagus** [comment]
The following implementation (to my surprise) seems to work quite well, despite being a bit rough around the edges:
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:optional-content-viewer

**Comment by Snuffleupagus** [comment]
The following implementation (to my surprise) seems to work quite well, despite being a little rough around the edges:
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:optional-content-viewer
