### ISSUE TITLE
All annotations are populating in first page and not considering if any offsets are applied to the page 

### ISSUE THREAD

**Issue by VineelG** [mozilla/pdf.js#12119]
Attach (recommended) or Link to PDF file here: https://web.archive.org/web/20110918100215/http://www.irs.gov/pub/irs-pdf/f1040.pdf

Configuration:
- Web browser and its version: Chrome (84.0.4147.89)
- Operating system and its version: Windows 10
- PDF.js version: 2.6.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Implementing the [acroforms](https://github.com/mozilla/pdf.js/blob/master/examples/acroforms/acroforms.js) example in angular by npm install pdfjs-dist.
2. Able to achieve everything as per the acroforms example, except annotations layer positioning. 

What is the expected behavior? (add screenshot)
![2020-07-24_21-19-37](https://user-images.githubusercontent.com/68660373/88410152-99d76a80-cdf3-11ea-9cc4-942aecd04166.jpg)

What went wrong? (add screenshot)
![2020-07-24_21-25-59](https://user-images.githubusercontent.com/68660373/88410724-5af5e480-cdf4-11ea-8407-14b374667210.jpg)

Could you please explain, what must be causing this issue? What files in pdfjs-dist are responsible for annotations population aligned to the pdfviewer? A similar issue is already reported [#10333](https://github.com/mozilla/pdf.js/issues/10333#issue-387899074), but resolution info is not there. 

Thanks

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by VineelG** [comment]
Thank for the response. I have gone through most of the existing issues, but could able to get any solution for the issue. As requested I have prepared and hosted a [basic application](http://54.146.13.1/basicpdfjs/) and the codebase can be accessed at https://github.com/VineelG/ng-pdfjs-acroforms.

Can you please explain, how this can be resolved or where I can check for the issue.

Thanks

**Comment by Snuffleupagus** [comment]
You're missing crucial CSS rules, which is pretty obvious if you compare your code with the one in https://github.com/mozilla/pdf.js/blob/master/examples/acroforms/acroforms.html; note in particular https://github.com/mozilla/pdf.js/blob/7b0c52fdfed4642366796021093833df63236550/examples/acroforms/acroforms.html#L28-L36

**Comment by VineelG** [comment]
Thank you very much, this helped to solve the issue. Added style to page class in promise after page is drawn, as applying style to .page class in html was not getting applied.
