### ISSUE TITLE
pdfDocument.getOpenAction is not a function

### ISSUE THREAD

**Issue by TheAustinG** [mozilla/pdf.js#12113]
Attach (recommended) or Link to PDF file here: Any PDF file

Configuration:
- Web browser and its version: Microsoft Edge - 84.0.522.40
- Operating system and its version: Windows 10 - Version 10.0.19041 Build 19041
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. Just trying to render a PDF using PDF.js
2.

What is the expected behavior? 
That the PDF is rendered inside the iframe

What went wrong? (add screenshot)
I am able to see the PDF when I run it locally in my dev environment but in production it is logging these errors to the console. The last picture is what the PDF viewer looks like after it's "rendered"

![pdfjs-console](https://user-images.githubusercontent.com/14006557/88309684-46222f80-ccd4-11ea-8479-cac109c731ac.png)

![pdfjs-errors](https://user-images.githubusercontent.com/14006557/88309696-4ae6e380-ccd4-11ea-9952-6afd0c4c77f4.png)

![pdfjs](https://user-images.githubusercontent.com/14006557/88309785-6eaa2980-ccd4-11ea-9e17-3618bd69fada.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I am able to see the PDF when I run it locally in my dev environment but in production it is logging these errors to the console.

That'd suggest a problem in your environment, rather than in the PDF.js default viewer, since otherwise you'd really expect it to be consistently broken everywhere; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
