### ISSUE TITLE
 Error('Invalid PDF binary data: either typed array, ' + 'string or array-like object is expected in the ' + 'data property.'); when key data present, but it empty

### ISSUE THREAD

**Issue by elzone** [mozilla/pdf.js#12117]
Hello.

In some cases source contain data but it's empty and this cause the error show in console log.

![image](https://user-images.githubusercontent.com/2065109/88376078-6837b280-cda5-11ea-96ab-623da27dd534.png)

Maybe you can add additional check for empty data key?

![image](https://user-images.githubusercontent.com/2065109/88376276-bbaa0080-cda5-11ea-916e-e660cb0bd705.png)

![image](https://user-images.githubusercontent.com/2065109/88376142-830a2700-cda5-11ea-958f-aaedc385bac1.png)

thank you.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is there's unfortunately no actionable information provided here!

Also, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is there's unfortunately no actionable information provided here!

Also, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> In some cases source contain data but it's empty and this cause the error show in console log.

If the data you provide is empty, then throwing an Error really is correct behaviour. What would the alternative be, since there's no PDF data to open/display in that case!?

> Maybe you can add additional check for empty data key?

How would that help?

**Comment by elzone** [comment]
sorry, my foult
