### ISSUE TITLE
Fonts are not smooth

### ISSUE THREAD

**Issue by helperman** [mozilla/pdf.js#12116]
Fonts are not smooth in documents.

Configuration:
- Web browser and its version: Firefox 78
- Operating system and its version: win8.1
- PDF.js version: don't know where to see. I just open a link
- Is a browser extension: clean profile

Steps to reproduce the problem:
1. open in Firefox 78: https://mozilla.github.io/pdf.js/web/viewer.html
2. fonts are not smooth. See the screenshot: 
https://i.imgur.com/fDRp3z1.png

What is the expected behavior? (add screenshot)
Fonts are smooth and readable

What went wrong? (add screenshot)
fonts are not smooth.

**Comment by timvandermeij** [comment]
We have seen such issues before and they were all related to graphics driver problems. Please check if there are updates for them or reinstall them.
