### ISSUE TITLE
textlayer misalignment on Chinese document

### ISSUE THREAD

**Issue by PeterW570** [mozilla/pdf.js#12110]
Attach (recommended) or Link to PDF file here:
[chars-此文章包含相關.pdf](https://github.com/mozilla/pdf.js/files/4965103/chars-.pdf)

Configuration:
- Web browser and its version: Google Chrome v84.0.4147.89
- Operating system and its version: macOS Catalina Version 10.15.5
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the attached document

What is the expected behavior? (add screenshot)
textlayer to match up with the pdf text

What went wrong? (add screenshot)
<img width="564" alt="Screenshot 2020-07-23 at 10 56 03" src="https://user-images.githubusercontent.com/7226807/88274135-263e3c00-ccd3-11ea-866b-72485177498d.png">

textlayer spans are in red. The misalignment can be seen particularly badly on the last line in the bottom right.

Had a look for related open issues, perhaps related to: #5558, #9448, #9892, #11756, #12074 but none seemed quite the same as this.

**Comment by zhoujiachang** [comment]
![image](https://user-images.githubusercontent.com/36024462/96100075-89242580-0f06-11eb-85ed-e85aff12efdb.png)

**Comment by timvandermeij** [comment]
Closing since this is fixed by #13257 and possibly other patches.
