### ISSUE TITLE
Horizontal Scrolling as default

### ISSUE THREAD

**Issue by lulibo** [mozilla/pdf.js#12111]
Hi,
Is there a way to set Horizontal Scrolling as default using viewer.html?
I'm using iframe solution in this way:
<iframe height="500px" width="100%"  src="/js/pdfjs/web/viewer.php?file=myfile.pdf#zoom=auto" ></iframe>

I not able to find a config file where to set this as default.

Thank you

**Comment by Snuffleupagus** [comment]
Based on https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage, you can e.g. set the "scrollModeOnLoad" option the following way:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("scrollModeOnLoad", 1);
});
```
where the value `1` corresponds to horizontal scrolling, see https://github.com/mozilla/pdf.js/blob/7b0c52fdfed4642366796021093833df63236550/web/ui_utils.js#L44-L49

**Comment by lulibo** [comment]
Thank you really for your reply.
I added this few lines both in the page containing the iframe and in the viewer.html page, but nothing changed. Do I have to place it somewhere else?

`<script>
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("scrollModeOnLoad", 1);
});
</script>`

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by lulibo** [comment]
Thanks for your suggestion.
I sorted it out changing the function getDefaultPreferences inside viewer.js.
There is the variable scrollModeOnLoad that I set to 1.
Now it works.
Best,
Luca
