### ISSUE TITLE
Missing prominent character in pdf.

### ISSUE THREAD

**Issue by bansan85** [mozilla/pdf.js#12120]
I found other tickets about this kind of issue but I have no idea if it the same problem.

Attach (recommended) or Link to PDF file here: [Planning_1988.pdf](https://github.com/mozilla/pdf.js/files/4973247/Planning_1988.pdf)

Configuration:
- Web browser and its version:

Firefox 78.0.2 (64 bits)

- Operating system and its version:

Windows version 2004 19041.388

- PDF.js version:

2.5.179 and on live : 2.6.138

- Is a browser extension: ??? It's the pdf.js from firefox.

What is the expected behavior? (add screenshot)

From adobe reader :

![adobe](https://user-images.githubusercontent.com/9248729/88415782-596df180-cddf-11ea-88e4-ab436c420124.png)

What went wrong? (add screenshot)

From PDF.js

![pdfjs](https://user-images.githubusercontent.com/9248729/88415857-7e626480-cddf-11ea-8dcc-2e04e48ff88d.png)

Output of the console : null

**Comment by brendandahl** [comment]
I have a fix for this and bug 1057544. I'll hopefully get it up for review soon after all the form support stuff lands.
