### ISSUE TITLE
Persistent "Bad end offset" when deployed to Firebase Cloud Functions

### ISSUE THREAD

**Issue by jiarongkoh** [mozilla/pdf.js#12128]
I am encountering the above issue with text extraction for selected PDF documents. This issue persists when the task is performed by a function deployed on Firebase Cloud Functions.

The function performs a web scraping task, ie goes to multiple websites, extract PDF document's URL, and then extracts the document's plain text. For selected pdfs, it always throw the `Bad end offset` error, and for some reason, these errors are not "catchable".

Firebase Support advised me to check if `pdfjs-dist` maintains a persistent connection with the pdf's URL by following the docs [here](https://firebase.google.com/docs/functions/networking#maintaining_persistent_connections), but I have yet to figure out how to implement such persistent connection via `pdfjs-dist`.

Code:
```
const pdf = require('../pdf/pdf')

function getTextByUrl() {
    let url = "https://www.nea.gov.sg/docs/default-source/our-services/amendments-to-copeh-for-the-removal-of-roof-gutters-for-a-amp-a-or-reconstruction-works-involving-roof-structures.pdf"

    let options = pdf.setupPdfOptions(url)
    return extract(options)
}

function extract(options) {
    return pdf.getPlainBody(options)
    .then(pb => {
        console.log("Text extraction done:", pb)
    })
    .catch(err => {
        console.log("Err:", err)
    })
}
```
At the pdf.js script:
```
const pdfjslib = require('pdfjs-dist/es5/build/pdf.js');

function getPlainBody(options) {
    console.log("1")
    return getDocument(options)
    .then(doc => {
        console.log("4")
        return extractTexts(doc, doc.numPages)
    })
    .catch(err => console.log('Get plainBody err:', err))
}

function getDocument(options) { 
    console.log("2")
    var loadingTask = pdfjslib.getDocument(options)
    return loadingTask.promise
    .then((doc) => {
        console.log("3") //<== Not logged and crashed
        return doc
    })
    .catch(err => console.log("getDocument err:", err)) //<== Didn't catch the "Bad end offset" error
}

function extractTexts(doc, maxNumPages) {
    var promises = []
    for (pageNum = 1; pageNum <= maxNumPages; pageNum++) {
        const promise = getText(pageNum, doc)
        promises.push(promise)
    }

    return Promise.all(promises)
    .then((results) => {
        var pdfString = []
        for (const result of results) {
           pdfString.push(result);
        }

        return pdfString.join('').replace(/\s{2,}/g,' ').trim();
    })
    .catch((err) => {
        console.log('Error extracting text', err)
    })
}

function getText(pageNum, doc) { 
    console.log("5")
    return doc.getPage(pageNum)
    .then((page) => {
        return page.getTextContent()
    })
    .then((content) => {        
        var strings = content.items.map((item) => {
            return item.str
        });
        
        const concatStrings = strings.join('');
        return concatStrings;
    })
    .catch((err) => {
        console.log('Error getting text', err)
        return
    })
}

function setupPdfOptions(url) {
    return {
        url: url,
        httpHeaders: {
            "User-Agent": //My useragent,
        },
    };
}
```

What can I do to eliminate this error? Is this caused by poor connection between `pdfjs` and the pdf's URL? How can I catch this error?

Attach (recommended) or Link to PDF file here:
https://www.nea.gov.sg/docs/default-source/our-services/amendments-to-copeh-for-the-removal-of-roof-gutters-for-a-amp-a-or-reconstruction-works-involving-roof-structures.pdf

Configuration:
- Web browser and its version: Not applicable
- Operating system and its version: Nodejs 10
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. Code as described above.
2. Deploy to Firebase Cloud function
3. Crashes with "Bad end offset", and "Bad end offset" error being uncatchable.

What is the expected behavior? (add screenshot)
Text for the said pdf should be extracted, if pdf is a scanned document, it should return empty string.

What went wrong? (add screenshot)
<img width="987" alt="Screenshot 2020-07-27 at 1 25 42 PM" src="https://user-images.githubusercontent.com/18225065/88507504-26aa4000-d00f-11ea-9067-6aa4833f5743.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
None.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Aside from not being able to help without a running example, it's not clear what `poor connection between pdfjs and the pdf's URL` means. All PDF.js does is request the PDF file using a regular request or range requests if the webserver has support for that. All in all, it looks like the webserver is configured incorrectly.
