### ISSUE TITLE
The file is displayed blank in IE11

### ISSUE THREAD

**Issue by fireWinters** [mozilla/pdf.js#12132]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:IE11.09600.16428 
- Operating system and its version:windows7
- PDF.js version:1.10.100
- Is a browser extension:no

Steps to reproduce the problem:
1. Load the file using the official demo file Viewer. html

What is the expected behavior? (add screenshot)
Show the complete file

What went wrong? (add screenshot)
Page blank

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
  Dear Sir, we have a problem that part of PDF files in IE11.09600.16428 cannot be displayed normally, the actual effect is blank page. We used the same version of PDF. js plug-in to load the same file, which can be displayed in Google Browser and can be displayed normally in Adobe Reader. What is the reason for this? Due to some confidential information, we cannot provide the original file. Looking forward to your reply. Thank you.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *required* in order for the issue to be actionable.

> PDF.js version: 1.10.100

That version is *years* out of date, and is thus no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases

---

Finally, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by fireWinters** [comment]
> > Attach (recommended) or Link to PDF file here:
> 
> This part of the ISSUE_TEMPLATE is _required_ in order for the issue to be actionable.
> 
> > PDF.js version: 1.10.100
> 
> That version is _years_ out of date, and is thus no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases
> 
> Finally, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> 
> > While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which _completely_ prevent the library and/or the default viewer from running will be accepted.

Thank you very much for your reply. I have downloaded the latest version from the official website. Due to network restrictions, the download speed is slow. If there are any other questions, please kindly support me. Thank you very much.

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum, and issues are thus required to contain *all* of the necessary information to be easily actionable/reproducible in order for anyone to help you; unfortunately this issue still contains *no actionable* information.

Finally, as also mentioned, support for IE 11 is *very* limited; hence a rendering issue affecting only that browser won't be fixed.

**Comment by seisdr** [comment]
I have a page that is blank which is this
![Screenshot_2020-07-28-21-09-42](https://user-images.githubusercontent.com/45742462/88704423-b850a500-d116-11ea-95f8-31285484e21d.png)

in pdf.js it reach to this page and never load the next page and nothing else is loaded

**Comment by seisdr** [comment]
"Mozilla/5.0 (PlayStation 4 7.51) AppleWebKit/605.1.15 (KHTML, like Gecko)"

**Comment by seisdr** [comment]
![Uploading Screenshot_2020-07-28-21-32-10.png…]()

**Comment by timvandermeij** [comment]
Without an example PDF file there is nothing we can do to debug this. Moreover, as indicated, IE11 support is limited.

**Comment by seisdr** [comment]
should I open a new issue

**Comment by timvandermeij** [comment]
No, if you have a PDF file that you can attach to the issue we can reopen it.

**Comment by seisdr** [comment]
here's the file

 and here's the image  that didn't uploaded completely
![Screenshot_2020-07-28-21-32-10](https://user-images.githubusercontent.com/45742462/88729493-b4d01480-d13c-11ea-841c-d4b5df3f1a74.png)
the blank page is right on page 35

**Comment by seisdr** [comment]
I'm unable to upload the pdf file 
you can download it from here
https://drive.google.com/file/d/1QI0iIUqN_WD9PDUg4xfl-dd10Od7Zm1Q/view

**Comment by fireWinters** [comment]
> here's the file
> 
> and here's the image that didn't uploaded completely
> ![Screenshot_2020-07-28-21-32-10](https://user-images.githubusercontent.com/45742462/88729493-b4d01480-d13c-11ea-841c-d4b5df3f1a74.png)
> the blank page is right on page 35

Why do you think the empty page in the directory area is an error parsing? Isn't the content displayed here loaded with a mouse wheel event? When you scroll down to the bottom, it loads the entire file. Isn't that how you present it?

**Comment by fireWinters** [comment]
> Please keep in mind that this is first and foremost a _bug tracker_, rather than a support forum, and issues are thus required to contain _all_ of the necessary information to be easily actionable/reproducible in order for anyone to help you; unfortunately this issue still contains _no actionable_ information.
> 
> Finally, as also mentioned, support for IE 11 is _very_ limited; hence a rendering issue affecting only that browser won't be fixed.

![wrong](https://user-images.githubusercontent.com/42629623/88747578-a3f5c200-d181-11ea-8a86-cb0595d1acb2.png)
![right](https://user-images.githubusercontent.com/42629623/88747584-ac4dfd00-d181-11ea-83c7-a066120b7702.png)

**Comment by seisdr** [comment]
no it stop right on this page if I scroll to bottom nothing will loaded I already upload a photo using Android pdf viewer and it loaded

**Comment by seisdr** [comment]
I don't want to load the blank page I want to load the other pages but I couldn't

**Comment by seisdr** [comment]
pdf.js couldn't not me

**Comment by fireWinters** [comment]
> Please keep in mind that this is first and foremost a _bug tracker_, rather than a support forum, and issues are thus required to contain _all_ of the necessary information to be easily actionable/reproducible in order for anyone to help you; unfortunately this issue still contains _no actionable_ information.
> 
> Finally, as also mentioned, support for IE 11 is _very_ limited; hence a rendering issue affecting only that browser won't be fixed.

Just now, I provided the wrong file. Please tell me the possible reason for this bug. Thank you. Looking forward to your reply.

**Comment by fireWinters** [comment]
![image](https://user-images.githubusercontent.com/42629623/88748597-fcc65a00-d183-11ea-8102-fcca965d2a0a.png)
What is the usage scenario difference between the two compression packs? That's what's highlighted in the picture.

**Comment by fireWinters** [comment]
![image](https://user-images.githubusercontent.com/42629623/88748781-778f7500-d184-11ea-9b63-14771a290a6a.png)

**Comment by fireWinters** [comment]
What is the usage scenario difference between the two compression packs? That's what's highlighted in the picture.
![image](https://user-images.githubusercontent.com/42629623/88748827-92fa8000-d184-11ea-98e6-ee9643a70405.png)
