### ISSUE TITLE
在最新版本Firefox上进行打印，最后多出来一张空白页

### ISSUE THREAD

**Issue by infosecliqin** [mozilla/pdf.js#12133]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:     Firefox 78.0.2(64位)
- Operating system and its version:  Windows10
- PDF.js version:  PDF.js 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
1. viewer.html通过iframe嵌套在页面中
2. 选择本地pdf文件打开，点击“打印”按钮，结果最后一页之后，多出来一张空白页

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
We can only help out in English and if _all_ details are provided.
