### ISSUE TITLE
PDF shown with incorrect fonts

### ISSUE THREAD

**Issue by heycam** [mozilla/pdf.js#12155]
Attach (recommended) or Link to PDF file here: https://www.pc.gov.au/research/supporting/jobs-ladder/jobs-ladder.pdf

Configuration:
- Web browser and its version: Firefox Nightly 81
- Operating system and its version: Ubuntu 19.10
- PDF.js version: ?
- Is a browser extension: ?

Steps to reproduce the problem:
1. Open the linked PDF.
2. Look at the third page.

What is the expected behavior?

![Screenshot from 2020-08-02 17-35-09](https://user-images.githubusercontent.com/1484434/89118120-92484d80-d4e6-11ea-98da-f916d2c9bb3c.png)

Entire page (apart from the footer) is rendered with a serif font.  (Screen shot from Gnome Document Viewer.)

What went wrong?

![Screenshot_2020-08-02 Climbing the jobs ladder slower Young people in a weak labour market - jobs-ladder pdf](https://user-images.githubusercontent.com/1484434/89118101-6c22ad80-d4e6-11ea-94f7-aecc30491dc3.png)

It's rendered with a mix of serif and sans serif.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This looks, for all intents and purposes, like a duplicate of #11840.

**Comment by heycam** [comment]
Thanks, yes that looks basically the same.
