### ISSUE TITLE
wrong pdf rendering

### ISSUE THREAD

**Issue by E-lit** [mozilla/pdf.js#12167]
Attach (recommended) or Link to PDF file here:
[document(5).pdf](https://github.com/mozilla/pdf.js/files/5021034/document.5.pdf)

Configuration:
- FireFox 79 and any other version
- macOS 10.15.5 and any other OS supported by Firefox
- PDF.js version - integrated to Firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. open attached file using default Firefox pdf viewer

What is the expected behavior? 
<img width="750" alt="изображение" src="https://user-images.githubusercontent.com/26278477/89272438-d2264680-d646-11ea-9351-aeb019632fe8.png">

What went wrong? (add screenshot)
<img width="816" alt="изображение" src="https://user-images.githubusercontent.com/26278477/89272492-e9fdca80-d646-11ea-8c7a-26808eb92fba.png">

**Comment by dieselart** [comment]
This document includes Adobe Digital Signs. It correctly renders in other viewers, but not here.

**Comment by Snuffleupagus** [comment]
Duplicate of #1076
