### ISSUE TITLE
IE11 PDFjs Print failure at 86% in Print progress bar

### ISSUE THREAD

**Issue by roshanmathew89** [mozilla/pdf.js#12178]
Attach (recommended) or Link to PDF file here: 
N/A
Configuration:
- Web browser and its version: IE11 
- Operating system and its version: Windows 10 pro
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1.  Print is auto triggered
2.  Print service will render all the pages (322 pages) , but always fails at 86% in Print progress bar.

What is the expected behavior? (add screenshot)
 
![PDFfailure](https://user-images.githubusercontent.com/23585184/89463678-e70cf200-d78c-11ea-8a64-75625f9fb710.png)

What went wrong? (add screenshot)

The PDF contains complex tables and diagrams which is leading to IE11 failure at rendering the pages. At times the render fails at 89% also.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by timvandermeij** [comment]
First of all, IE11 support is very limited. From the FAQ:

"While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which completely prevent the library and/or the default viewer from running will be accepted."

322 pages is most likely way too much for IE11 to handle, and given that printing APIs in browsers in general are very inflexible there is nothing we can really do about this. If you have a custom deployment of PDF.js, you can lower the `printResolution` variable, but that will lead to a worse quality print.
