### ISSUE TITLE
Not properly aligned text layer

### ISSUE THREAD

**Issue by TomaIvanovTomov** [mozilla/pdf.js#12184]
Hello, 
this is what happens when I try to use the text layer: [here](https://ibb.co/r3YFM5w)
This is the part of the code where I am implementing it.

`function render(myState) {
    document.getElementById("pdf_renderer").remove();
    var container = document.getElementById("canvas_container");
    var canvas = document.createElement('canvas');
    var canvasStyle = {
    display: '0 auto',
          backgroundColor: '#FFFFFF',

    }
    canvas.id     = "pdf_renderer";
    canvas.style.position = 'relative'
    container.appendChild(canvas);
    canvas.addEventListener("mousemove", (e) => {document.body.style.cursor  = 'auto'}, false);

    var ctx = canvas.getContext('2d');

    myState.pdf.getPage(myState.currentPage).then((page) => {
        console.log(page._pageInfo.ref)
        var viewport = page.getViewport({scale:myState.zoom});
        canvas.width = viewport.width;
        canvas.height = viewport.height;
        page.render({
            canvasContext: ctx,
            viewport: viewport,
        }).promise.then(() => {
            return page.getTextContent();
        }).then((textContent) => {
            const pdf_canvas = document.getElementById("pdf_renderer")
            const canvas_offset_top = pdf_canvas.offsetTop
            const canvas_offset_left = pdf_canvas.offsetLeft
            const canvas_height = pdf_canvas.height 
            const canvas_width = pdf_canvas.width
            document.getElementById("text-layer").setAttribute('style', `z-index: 99999!important; left: ${canvas_offset_left}px; top: ${canvas_offset_top}px; height: ${canvas_height}px; width: ${canvas_width}px`)
            pdfjsLib.renderTextLayer({
                textContent: textContent,
                container: document.getElementById("text-layer"),
                viewport: viewport,
                textDivs: []
            })
        });
    });
}`

I am not a React guru so any advices will be appreciated. This is the repository to reproduce it if you need: [here](https://github.com/TomaIvanovTomov/pdfexample).

**Comment by mmouterde** [comment]
Did you try to add : 
~~~
#text-layer > span {
    position: absolute;
    transform-origin: 0% 0%;
}
~~~

**Comment by Snuffleupagus** [comment]
You probably want to use the *viewer components* examples, as found in https://github.com/mozilla/pdf.js/tree/master/examples/components, since they handle things like text-selection and annotations out-of-the-box.

When using those examples, please remember to always include the CSS files/rules as listed in the relevent `.html` file of the example you're using (otherwise things may not work correctly).
