### ISSUE TITLE
Strange rendering of a PDF LaTeX output

### ISSUE THREAD

**Issue by Rmano** [mozilla/pdf.js#12185]
Attach (recommended) or Link to PDF file here:
[dotclose.pdf](https://github.com/mozilla/pdf.js/files/5041818/dotclose.pdf)

Configuration:
- Web browser and its version: Firefox 79.0 (64-bit)
- Operating system and its version: Linux Ubuntu 18.04 up-to-date on this date
- PDF.js version: I don't know how to check it...
- Is a browser extension: no

Steps to reproduce the problem:
1. open the attached file in Firefox
2. open with other viewers and chrome

What is the expected/wrong behavior?

There is a line join which is drawn differently in PDF.js: 

![ksnip_20200807-155456](https://user-images.githubusercontent.com/6414907/89653785-e75dd800-d8c7-11ea-9479-a48da92e1680.png)

**Comment by timvandermeij** [comment]
Coincidently this exact case was also reported in another issue that got fixed recently. I can't seem to find that issue right now, but if you open the file with https://mozilla.github.io/pdf.js/web/viewer.html it's correct now in the latest `master` version.

**Comment by Rmano** [comment]
I suppose is #12010... Didn't find it before, sorry. Same file and same problem. If you should need it, I can try to generate an uncompressed minimal PDF.

Thanks anyway!

**Comment by timvandermeij** [comment]
Yes, that's the one. The patch in https://github.com/mozilla/pdf.js/pull/12044/files contains a reduced test case, so I think it's all taken care of. Thank you!
