### ISSUE TITLE
Cannot parse pdf correctly

### ISSUE THREAD

**Issue by qhwc2009** [mozilla/pdf.js#12183]
This is the pdf file:
[https://od.lk/d/ODFfNTA2NDY2NDJf/1111111111111.pdf](https://od.lk/d/ODFfNTA2NDY2NDJf/1111111111111.pdf)

After parsing, it is displayed like this
![image](https://user-images.githubusercontent.com/22767477/89640974-4846d980-d8e3-11ea-97e4-5080c5ea3caf.png)

**Comment by timvandermeij** [comment]
The console shows `Warning: JPX: Trying to recover from: JPX error: Out of packets` for debugging this.

**Comment by Snuffleupagus** [comment]
> This is the pdf file:
> https://od.lk/d/ODFfNTA2NDY2NDJf/1111111111111.pdf

Unfortunately the link no longer works (which is why we suggest to *attach* the PDF document here instead); closing as INCOMPLETE for now.
