### ISSUE TITLE
Safari text-only zoom renders overlapping text

### ISSUE THREAD

**Issue by ashbrowning** [mozilla/pdf.js#12196]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Safari Version 13.1.1 (15609.2.9.1.2)
- Operating system and its version: MacOSX 10.15.5 (Catalina)
- PDF.js version: v2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit the demo viewer in Safari (https://mozilla.github.io/pdf.js/web/viewer.html) and load the default PDF
2. Zoom in via the text-only zoom option via Cmd+Alt+Plus
3. Refresh the page
4. Note how the font size increase has taken affect, and each character overlaps with adjacent characters.

What is the expected behavior? (add screenshot)
Expecting rendered text not to increase in size (and definitely not have characters overlap), which is the behaviour in Chrome (attached below) and FireFox.

![Screenshot 2020-08-11 at 08 56 25](https://user-images.githubusercontent.com/701108/89872471-e4593500-dbb0-11ea-8809-b5a06a2591af.png)

What went wrong? (add screenshot)

![Screenshot 2020-08-11 at 08 46 44](https://user-images.githubusercontent.com/701108/89872258-99d7b880-dbb0-11ea-996c-85ac7add445b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Expecting rendered text not to increase in size (and definitely not have characters overlap), which is the behaviour in Chrome (attached below) and FireFox.

Given this, it really does sound like a bug in the Safari browser *itself* rather than in the PDF.js library. Hence it's unfortunately not at all clear what, if anything, can be done about that *here*.

**Comment by timvandermeij** [comment]
I also think this is not a problem in PDF.js, but more likely in the browser (settings) or the display drivers, also given that the icons and input/select boxes have a completely wrong format, so I don't think we can do something about that here unfortunately.
