### ISSUE TITLE
The zoom popup in the viewer shows a weird border at the top and bottom on macOS

### ISSUE THREAD

**Issue by msujaws** [mozilla/pdf.js#12198]
Attach (recommended) or Link to PDF file here:
<img width="303" alt="87592901-e8498280-c6ea-11ea-8f3e-ac8825149edd" src="https://user-images.githubusercontent.com/272055/89949871-8cddb800-dbf6-11ea-9a31-40899dcebafb.png">

Configuration:
- Seen on Firefox Nightly 81.0a1 (2020-08-01)

Steps to reproduce the problem:
1. Use macOS
2. Click on the zoom select at the top of the viewer

**Comment by timvandermeij** [comment]
For reference, this is also tracked in Bugzilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1653382.

**Comment by msujaws** [comment]
Yes, thanks for adding that link to Bugzilla.

**Comment by timvandermeij** [comment]
Closing since the new design should have fixed this (it's also using `background-color` with a non-transparent color now).
