### ISSUE TITLE
How to enable findContoller search in pageviewer example

### ISSUE THREAD

**Issue by TomaIvanovTomov** [mozilla/pdf.js#12190]
Hello, I manage to make the pdf viewer but like the pageviewer example but can't understand how to set up the search functionality. Tried by adding findController but it doesn't work. E.g. the searched word is not wrapped in `<span class='highlight active>rout</span>'`. Posting my code to see what I am talking about. Thank you in advance!
```
myState.pdf.getPage(myState.currentPage).then((page) => {
        
        container.innerHTML = ''

        var eventBus = new pdfjsViewer.EventBus();

        // (Optionally) enable hyperlinks within PDF files.
        var pdfLinkService = new pdfjsViewer.PDFLinkService({
          eventBus: eventBus,
        });

        // (Optionally) enable find controller.
        var pdfFindController = new pdfjsViewer.PDFFindController({
          eventBus: eventBus,
          linkService: pdfLinkService,
        });

        /*if (myState.searchText) {*/
          pdfFindController.executeCommand("find", { query: "rout" });
        /*}*/

        var pdfPageView = new pdfjsViewer.PDFPageView({
          container: container,
          id: myState.currentPage,
          scale: myState.zoom,
          defaultViewport: page.getViewport({ scale: myState.zoom }),
          eventBus: eventBus,
          // We can enable text/annotations layers, if needed
          textLayerFactory: new pdfjsViewer.DefaultTextLayerFactory(),
          //annotationLayerFactory: new pdfjsViewer.DefaultAnnotationLayerFactory(),
          linkService: pdfLinkService,
          findController: pdfFindController
        })

        pdfPageView.setPdfPage(page);
        return pdfPageView.draw();
})
```

**Comment by Snuffleupagus** [comment]
> I manage to make the pdf viewer but like the pageviewer example but can't understand how to set up the search functionality.

You can't, since `PDFFindController` requires access to a complete PDF document in order for things to work as intended.
If you only want to display *a single* page, but still have e.g. searching working, please refer to the `singlepageviewer` example in https://github.com/mozilla/pdf.js/tree/master/examples/components

---

Generally speaking, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (note that answers may vary depending on e.g. what PDF.js version you're using).

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by TomaIvanovTomov** [comment]
Thank you! One last little question. Is it possible to set a particular page to the `PDFSinglePageViewer` ? For example, what to render the 5th page from the pdf document. The example currently always renders the first one.

**Comment by Snuffleupagus** [comment]
> Is it possible to set a particular page to the `PDFSinglePageViewer`?

Generally speaking, the viewer-API can be found in https://github.com/mozilla/pdf.js/blob/master/web/base_viewer.js; in this case see https://github.com/mozilla/pdf.js/blob/7fb01f9f2a4d3d6e2680cf9f6df3c83446d6e763/web/base_viewer.js#L209-L232

**Comment by TomaIvanovTomov** [comment]
I`ve tried to set it to 2 like `pdfSinglePageViewer.currentPageNumber = 2` but `Invalid page number` error was thrown. The document has 100+ pages. Excuse me for my lack of knowledge. Can you give me a really simple few lines example of how I should change the page ?

**Comment by Snuffleupagus** [comment]
> I've tried to set it to 2 like `pdfSinglePageViewer.currentPageNumber = 2` but `Invalid page number` error was thrown.

The error message indicates that you didn't actually provide an *integer*, as required by this getter.

It's unfortunately impossible for anyone to help without access to your *complete* code, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by TomaIvanovTomov** [comment]
```
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf';
import "react-pdf/dist/Page/AnnotationLayer.css";
import { loadStripe } from '@stripe/stripe-js';
import "views/RiggsPDF.pdf";
import * as pdfjsLib from 'pdfjs-dist';
import './pdf.css';
import './pdf_viewer.css';
import  CognitoAuth  from "cognito/index.js";
import * as pdfjsViewer from 'pdfjs-dist/web/pdf_viewer';
import { TextLayerBuilder } from "pdfjs-dist/lib/web/text_layer_builder";
import pdffile from "./test.pdf";

//some functions, that has nothing to do with the pdfjs here

function render(myState) {
    var container = document.getElementById("canvas_container");

    var eventBus = new pdfjsViewer.EventBus();

    // (Optionally) enable hyperlinks within PDF files.
    var pdfLinkService = new pdfjsViewer.PDFLinkService({
      eventBus: eventBus,
    });

    // (Optionally) enable find controller.
    var pdfFindController = new pdfjsViewer.PDFFindController({
      eventBus: eventBus,
      linkService: pdfLinkService,
    });

    var pdfSinglePageViewer = new pdfjsViewer.PDFSinglePageViewer({
      container: container,
      eventBus: eventBus,
      linkService: pdfLinkService,
      findController: pdfFindController,
    });
    pdfLinkService.setViewer(pdfSinglePageViewer);

    eventBus.on("pagesinit", function () {
      // We can use pdfViewer now, e.g. let's change default scale.
      pdfSinglePageViewer.currentScaleValue = "1.5";

      // We can try searching for things.
      if (1==1) {
        pdfFindController.executeCommand("find", { query: "chemi" });
      }
    });

    // Loading document.
    var loadingTask = pdfjsLib.getDocument(pdffile);
    loadingTask.promise.then(function (pdfDocument) {
      pdfSinglePageViewer.setDocument(pdfDocument);
      pdfSinglePageViewer.currentPageNumber = 2

      pdfLinkService.setDocument(pdfDocument, null);
    });
}
```

Maybe it is because I am loading the pdf with `import` and not through url ? Is it possible that to be the problem ?

**Comment by Snuffleupagus** [comment]
It looks like you're trying to change the page *before* the viewer has been fully loaded/initialized, however changing the page here should definitely work: https://github.com/mozilla/pdf.js/blob/7fb01f9f2a4d3d6e2680cf9f6df3c83446d6e763/examples/components/singlepageviewer.js#L59-L60

Again, as clearly mentioned multiple times now: code-snippets are *not* helpful and you'll need to provide runnable code if you're still having problems!
