### ISSUE TITLE
some pdf file cannot render by ios13

### ISSUE THREAD

**Issue by Paul101432** [mozilla/pdf.js#12197]
please like these by iphone: 

http://gzsdkj.top/hrz/#/?demo=ykj

Configuration:
- Safari 
- Iphone11- ios13.6
- pdf.js 2.4.456

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (e.g. the actual PDF file should be attached here, there's no screenshots illustrating the problem, and finally there's just a general lack of information); as-is this issue really isn't actionable.
