### ISSUE TITLE
update the content on the fly

### ISSUE THREAD

**Issue by aloispichler** [mozilla/pdf.js#12195]
Suppose the file filename.PDF, displayed by PDF.js, changes on the disk. Then PDF.js reloads its content and displays the updated content. This is actually an essential feature for LaTeX workshop, e.g.

In doing so, PDF.js
* fist displays the old content,
* then shows a blank screen,
* and finally displays the updated, new content.

The blank screen in between during reloading is distracting. SumatraPDF, for example, does everything on the fly and the user would not even realize the update operation in between.

Can we remove the distracting blank screen in between?
Thank you.

**Comment by Snuffleupagus** [comment]
> Suppose the file filename.PDF, displayed by PDF.js, changes on the disk.

There's no functionality in the PDF.js library that actually detects file change anywhere (neither on disk, nor elsewhere). Furthermore, please note that the PDF.js library usually needs a web-server to even run (unless used in Node.js environments).

> This is actually an essential feature for LaTeX workshop,

That's a *different* project, and while it may utilize the PDF.js library, cannot be supported here. Please contact the authors of "LaTeX workshop" *directly* for support in that case.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
