### ISSUE TITLE
App Size Increased

### ISSUE THREAD

**Issue by abhinavtestbook** [mozilla/pdf.js#12200]
While adding pdf.js library in my android app , it increased the size of my app by 4 MB. 
Is this expected or weird ? since we cant afford increasing the size increase of 4MB.

**Comment by Snuffleupagus** [comment]
You need to keep in mind that the PDF is a big and complex format, with a lot of functionality/features included, hence parsing/rendering PDF documents will require a fair amount of code. There's really no way around that!

The only "solution" here would probably may be to use a minified version of the PDF.js library, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified
