### ISSUE TITLE
[Feature Request] Shortcut to focus "Jump to"

### ISSUE THREAD

**Issue by quangkieu** [mozilla/pdf.js#12205]
Configuration:
- Web browser and its version: Edge Chromium Beta (build 86.0.594.1)
- Operating system and its version: Win 10 Beta Channel (build 19042.450)
- PDF.js version: 2.3.164
- Is a browser extension: [x]

Steps to used feature:
1. User hit shortcut combo, like Ctrl+G
2. Bring focus to "Jump to"/"Go to" box and select all text in box
3. User type new page
4. Jump to that page on "Enter"

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts, where you find:
> <strong>Move focus to the 'go to page' box:</strong> <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>g</kbd>
