### ISSUE TITLE
Edge: Message: Bad (uncompressed) XRef entry: 100R

### ISSUE THREAD

**Issue by yuanfen505** [mozilla/pdf.js#12206]
I have a problem in Edge. In this issue, some pages of the rendered PDF file are missing, and the error message on the console is like a screenshot. The problem occurs occasionally.

Configuration:

Web browser and its version: Microsoft Edge 44.18362.449.0
Operating system and its version: Windows 10
PDF.js version: 2.5.207
Is a browser extension: no

Steps to reproduce the problem:

open pdf URL in Edge 44.17763.771.0
What is the expected behavior? (add screenshot)
Normal PDF

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/29630954/90083940-78a8d080-dd46-11ea-9e58-6253f613b9e5.png)

![image](https://user-images.githubusercontent.com/29630954/90083965-94ac7200-dd46-11ea-97d3-23105aae3b7d.png)

![image](https://user-images.githubusercontent.com/29630954/90084058-e228df00-dd46-11ea-917e-85db7c58e2a4.png)

![image](https://user-images.githubusercontent.com/29630954/90084065-e94fed00-dd46-11ea-9038-cf52efbfdda7.png)

**Comment by Snuffleupagus** [comment]
The `Attach (recommended) or Link to PDF file here:`-part of the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is *required* in order for this, or any, issue to be actionable/valid.
