### ISSUE TITLE
Unable to handle pdf error with try/catch

### ISSUE THREAD

**Issue by nx-n** [mozilla/pdf.js#12214]
Hi,

I stumbled upon a problem using pdfjs-lib while iterating over a folder of pdf files.

The reproduction code is rather simple:

```javascript
const pdfjsLib = require('pdfjs-dist/es5/build/pdf.js');

(async function() {
  try {
    const pdf = await pdfjsLib.getDocument(__dirname).promise;
  } catch (error) {
    console.log('catched...');
  }
})();
```

Instead of catching the error, I get:

```
$ node test.js
(node:92567) UnhandledPromiseRejectionWarning: Error
    at BaseExceptionClosure (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:1790:29)
    at Object.<anonymous> (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:1793:2)
    at __w_pdfjs_require__ (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:52:30)
    at Object.<anonymous> (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:147:13)
    at __w_pdfjs_require__ (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:52:30)
    at Object.<anonymous> (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:129:23)
    at __w_pdfjs_require__ (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:52:30)
    at /Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:116:18
    at /Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:119:10
    at webpackUniversalModuleDefinition (/Users/nscheer/application/stuff/await/node_modules/pdfjs-dist/es5/build/pdf.worker.js:25:20)
(node:92567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92567) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I know this is a somewhat contrived example but has happened like this due to a bug.

Another instance, but very difficult to debug, because the files are on a mounted samba share:

```
(node:1) UnhandledPromiseRejectionWarning: Error: Bad end offset: 2193
    at ChunkedStream.onReceiveData (/usr/src/app/node_modules/pdfjs-dist/es5/build/pdf.worker.js:12255:15)
    at ChunkedStreamManager.onReceiveData (/usr/src/app/node_modules/pdfjs-dist/es5/build/pdf.worker.js:12818:21)
    at /usr/src/app/node_modules/pdfjs-dist/es5/build/pdf.worker.js:12602:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My best guess here is, that the file was not completely written, yet.

Anyways, I'd expect to be able to catch these things using try/catch.

I have basic knowledge about what a UnhandledPromiseRejectionWarning is and that it can be produced by breaking a promise chain.

Is this something that must be handled by adjusting pdfjs? Or am I able to handle/catch these errors myself?

I know I can register a callback for unhandledRejection - but that totally breaks code flow.

My setup is as follows:
- node v12.18.3 / docker node:12-alpine
- MacOS X 10.15.6 / Ubuntu 18.04.3
- PDF.js version: pdfjs-dist@2.4.456

Greetings

Nico

**Comment by Snuffleupagus** [comment]
> The reproduction code is rather simple:
> ```js
> const pdfjsLib = require('pdfjs-dist/es5/build/pdf.js');
> 
> (async function() {
>   try {
>     const pdf = await pdfjsLib.getDocument(__dirname).promise;
>   } catch (error) {
>     console.log('catched...');
>   }
> })();
> ```
> Instead of catching the error, I get:

I've just tested the above snippet, with both the `master` branch and the `2.6.347` release (i.e. the current beta version), and the error was caught just as you'd expect. Hence I can only assume that whatever the problem was, has since been fixed. (I don't have time to try and bisect exactly what fixed it though.)

> Another instance, but very difficult to debug, because the files are on a mounted samba share:

Without an actual test-case, it's unfortunately not really possible to help with this.

---

All-in-all, I think we can close this as fixed now!?
