### ISSUE TITLE
es-module-shims.js file is missing

### ISSUE THREAD

**Issue by JohnAugustineG** [mozilla/pdf.js#12222]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It looks like you didn't run `npm install` then since this is provided by a dependency. Since no other information is provided, this is not actionable.
