### ISSUE TITLE
minified-es5 build is missing in pdfjs-dist

### ISSUE THREAD

**Issue by HugoMuller** [mozilla/pdf.js#12220]
Hi,

this issue could be related to [this one](https://github.com/mozilla/pdf.js/issues/11858).  
It seems that a gulp task [minified-es5](https://github.com/mozilla/pdf.js/pull/11892) has been added, but pdfjs-dist does not include the minified ES5 build.   
I need to support IE and I would like to avoid installing pdfjs and building it myself.

Configuration:
- PDF.js version: 2.4.456 and 2.5.207

Steps to reproduce the problem:
1. npm install pdfjs-dist

What is the expected behavior?

I expect  following files to be present:
- node_modules/pdfjs-dist/es5/build/pdf.min.js
- node_modules/pdfjs-dist/es5/build/pdf.worker.min.js
- node_modules/pdfjs-dist/es5/web/pdf_viewer.min.js

What went wrong?  
Files listed above are missing.

**Comment by Snuffleupagus** [comment]
> I need to support IE and I would like to avoid installing pdfjs and building it myself.

Given that support for Internet Explorer is *very limited*, as mentioned in the FAQ, I'm slightly on the fence regarding whether or not this is something that the `pdfjs-dist` library should support (since `gulp dist` isn't exactly fast as-is).
@timvandermeij What's your opinion here?

Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by timvandermeij** [comment]
I do somewhat agree that it's inconsistent that we provide a minified version for non-ES5 and not for ES5. Unfortunately quite a lot of users cannot use the non-ES5 build yet (I think it's not only IE, but also for other browsers and operating systems), so I'm not opposed to including it to make it consistent between both targets. `gulp dist` isn't run very often, so I'm not too concerned about its speed.

**Comment by HugoMuller** [comment]
Hi,

Thanks for your reactivity. I'll wait for the next release :)
