### ISSUE TITLE
PDF Forms - fill login option should not be displayed in context menu

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12224]
**Affected versions**
* 81.0a1 (2020-08-16)

**Affected platforms**
* Windows 10, macOS 11.0

**Steps to reproduce**
pdfjs.renderInteractiveForms - enabled

1. Launch Firefox;
2. Access a PDF [form with fillable content](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf);
3. Right Click in any text-input field or dropdown menu;

**Expected result**
* expected options are displayed;

**Actual result**
* login - user account data should not be available to pre-fill in such forms;

Additional notes:
* S2/3 as suggested severity due to the potential data secure issues might be caused by users that wouldn't pay attention;
* attached screenshot with the issue;

**Comment by timvandermeij** [comment]
The screenshot appears to be missing, but from what I can find this is a browser setting and can't be disabled by web pages themselves.

**Comment by cfogelSV** [comment]
<img width="438" alt="Screenshot 2020-08-24 at 08 47 54" src="https://user-images.githubusercontent.com/49230899/91008235-939cff80-e5e6-11ea-88e6-3fa1f3eace17.png">
 
Uploaded the image as well.

**Comment by timvandermeij** [comment]
@brendandahl Do you know if this can be disabled programmatically? I couldn't find any resources for that, so I think this is an upstream issue instead?

**Comment by brendandahl** [comment]
I think this will have to be fixed upstream.

**Comment by brendandahl** [comment]
I've created upstream bug for this.
https://bugzilla.mozilla.org/show_bug.cgi?id=1661131

**Comment by cfogelSV** [comment]
[Patch verified](https://bugzilla.mozilla.org/show_bug.cgi?id=1661131#c7). Closing issue.
