### ISSUE TITLE
Parse the `AcroForm` dictionary

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12226]
We don't really use this data now, but it could contain the default appearance for form elements. It seems like the current font code for text widgets is dead as `fontRefName` is never set, so we should parse this dictionary and extract the font information from it.

**Comment by Snuffleupagus** [comment]
> [...] as `fontRefName` is never set,

Also, note that's a slightly misleading name and it really ought to be renamed to `loadedName` (or possibly `fontLoadedName`) as part of fixing this issue.

**Comment by Snuffleupagus** [comment]
> [...] as `fontRefName` is never set,

Also, note that's a slightly misleading name and it really ought to be changed to `loadedName` (or possibly `fontLoadedName`) as part of fixing this issue.

**Comment by calixteman** [comment]
I'm not sure to understand this issue...
Don't we already do that:
https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L815-L824 ?

**Comment by timvandermeij** [comment]
You're right that we not at least use the data for printing in contrast to before where we didn't use it at all. This issue is about using it for non-form rendering, so just as normal annotations. For printing we render the annotation onto the canvas, but for displaying we render an overlay element so e.g., text selection is possible. That code still doesn't work properly; look at https://github.com/mozilla/pdf.js/blob/7df8aa34a5cd4dc41964de5f942376d26ec366b6/src/display/annotation_layer.js#L489-L497 for example and notice that there is no code that actually _sets_ `fontRefName`.

**Comment by timvandermeij** [comment]
Closing since this code is now replaced by working code and we use the default appearance properly.
