### ISSUE TITLE
Form 60 is not converted to acroform 

### ISSUE THREAD

**Issue by Nilanth** [mozilla/pdf.js#12231]
Attach (recommended) or Link to PDF file here:
http://chdtransport.gov.in/Forms/Form60.pdf

Configuration:
- Web browser and its version: chrome latest 
- Operating system and its version: mac
- PDF.js version: latest
- Is a browser extension:

**Comment by timvandermeij** [comment]
This file does not contain an `AcroForm` dictionary, nor does it contain any annotations, so this is not an AcroForm file and is therefore not fillable.

**Comment by Nilanth** [comment]
@timvandermeij 
So we cannot convert any PDF to Form fillable?

**Comment by timvandermeij** [comment]
No, PDF.js is a viewer, not an editor.

**Comment by Nilanth** [comment]
@timvandermeij
How can I get filled data from AcroForm using PDF.js?

**Comment by timvandermeij** [comment]
We have just merged that functionality; it will be part of the next release.

**Comment by Nilanth** [comment]
@timvandermeij
When might be the next release!!

**Comment by timvandermeij** [comment]
Unknown as of now because we're still making changes to it.
