### ISSUE TITLE
Dragged content is displayed way higher then the cursor of the mouse

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12236]
**Affected versions**
* 81.0a1 (2020-08-18)

**Affected platforms**
* Windows 10 64bit
* Ubuntu 18.04 64bit

**Steps to reproduce**
pdfjs.renderInteractiveForms - true

1. Launch Firefox
2. Access a PDF form with fillable content (eg: https://www.irs.gov/pub/irs-pdf/f1040.pdf)
3. Enter a random string in any field
4. Select that string
5. Drag the selected string

**Expected result**
* Selected string is moved with the cursor while dragging

**Actual result**
* Selected string is displayed way higher then the cursor is, and it's hard to see.

**Additional notes**
* S3 as suggested severity, not a major issue since it's only a visual issue but still a noticeable one.
* On macOS 10.15 the selected string is positioned wrong at start but then it is displayed under the cursor.
* Here is a .gif showing the issue:

![Drag string](https://user-images.githubusercontent.com/69848942/90512418-cd918000-e166-11ea-8219-4a5d29369564.gif)

**Comment by cfogelSV** [comment]
Same issue applies for macSO 11.0/10.15.
While it starts from the same offset position, it transitions towards the cursor within 1-2 seconds.

**Comment by Snuffleupagus** [comment]
Given that this is an upstream bug, tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=941356, we probably don't need to keep this issue open since it cannot be fixed *here*.
