### ISSUE TITLE
How use documentProperties?

### ISSUE THREAD

**Issue by Patrik30** [mozilla/pdf.js#12240]
Configuration:
- Web browser and its version: Firefox 79.0 (64-bit)
- Operating system and its version: windows 10
- PDF.js version: 2.4.456

Here is my code:

`var pdfjsLib = window['pdfjs-dist/build/pdf'];
var pdfjsViewer = window['pdfjs-dist/web/pdf_viewer'];

var container = document.getElementById("viewerContainer");
var eventBus = new pdfjsViewer.EventBus();

var pdfSinglePageViewer = new pdfjsViewer.PDFSinglePageViewer({
  container: container,
  eventBus: eventBus,
});

eventBus.on("pagesinit", function () {
  pdfSinglePageViewer.currentScaleValue = "page-width";
});

var loadingTask = pdfjsLib.getDocument({
  url: 'FILE_URL',
});

loadingTask.promise.then(function (pdfDoc) {
    pdfSinglePageViewer.setDocument(pdfDocument);
});`

How can I use documentProperties with PDFSinglePageViewer?

![document](https://user-images.githubusercontent.com/50837787/90545904-9ed8d100-e189-11ea-9910-49b79779ad52.png)

I found:

`function webViewerDocumentProperties() {
  PDFViewerApplication.pdfDocumentProperties.open();
}`

but I don't know how create PDFViewerApplication.

**Comment by timvandermeij** [comment]
You're using the viewer components, in particular the single-page viewer, and it's important to note that those do _not_ contain all functionality that the full-blown default viewer has. Document properties is one of them: the full-blown default viewer has a component to render this diagram in https://github.com/mozilla/pdf.js/blob/master/web/pdf_document_properties.js, so you'll have to implement something similar. It shows you how we implemented it, and it mainly consist of using the `getMetadata` API call to get the required information and rendering it into the dialog.
