### ISSUE TITLE
pdfjs textLayer fontSize conflict with Chrome min fontSize

### ISSUE THREAD

**Issue by xiadd** [mozilla/pdf.js#12243]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome an firefox lastest
- Operating system and its version: Macos
- PDF.js version: latest
- Is a browser extension: no

pdfjs textLayer fontSize conflict with Chrome min fontSize， so textLayer misplaced

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/8351437/90587358-c2dcf680-e20b-11ea-9619-151b40192bd4.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/8351437/90587385-d1c3a900-e20b-11ea-8ff1-4ae730a9fedb.png)

https://github.com/mozilla/pdf.js/blob/1f8b54b1fed38babbe87abc35c7c8bbf2ab0416c/src/display/text_layer.js#L608

**Comment by Snuffleupagus** [comment]
> pdfjs textLayer fontSize conflict with Chrome min fontSize， so textLayer misplaced

Given that there's no information about what "Chrome min fontSize" is, and how/where it's being set, this issue doesn't really seem actionable/valid without much better STR.

**Comment by dverbovyi** [comment]
I managed to fix with `pdfPage.getTextContent({ normalizeWhitespace: true })`
