### ISSUE TITLE
how to enable events like right click event on selected texts

### ISSUE THREAD

**Issue by JohnAugustineG** [mozilla/pdf.js#12252]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since none of the requested details is provided, so it's not actionable. Right-click can be handled with default JavaScript.
