### ISSUE TITLE
Printing/saving issue with chars in textfield which aren't in the default font

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12264]
In order to render these characters we need to have a font to render them.
So the first thing is to find such a font and in order to save the data we need to embed it (with Adobe reader on mac the font is embedded but it isn't with pdfium under linux), it means that we need to get a ttf file or an otf one.
I looked at google font server but in order to get a ttf I need to cheat with the user agent and then I get a cors issue because of that.
Anyway if we can get a ttf file, it seems possible (after reading src/core/fonts.js) to subset it to get only the used glyphs and then it'd avoid to embed the entire ttf file.
If we can't get a font file then for printing we could probably cheat in creating a "fake" font and for saving we could not embed the font (which is a pity).
Any thoughts ?

**Comment by calixteman** [comment]
Now we're embedding Liberation fonts for xfa, I think we should use them to render glyphs which are not in the default font for the field. We should at least be able to cover almost all the european languages but not asian ones for example.

**Comment by marco-c** [comment]
#15587 should fix this.
