### ISSUE TITLE
Tikz image with both transpareny and blend mode looks ugly on Windows but is correct on Linux

### ISSUE THREAD

**Issue by kerkovits** [mozilla/pdf.js#12274]
Attach (recommended) or Link to PDF file here:
http://mercator.elte.hu/~kerkovits/honlap/diasor/koord.pdf

Configuration:
- Web browser and its version: Firefox 79.0
- Operating system and its version: Windows 10
- Using as built-in viewer of the browser

Steps to reproduce the problem:
1. See the top of page 34. The bug is reproducible on Windows but works well on Linux.

What is the expected behavior? (add screenshot)
![kép](https://user-images.githubusercontent.com/22369178/91047237-05db0780-e61a-11ea-8145-db6e15f181dd.png)

What went wrong? (add screenshot)
![kép](https://user-images.githubusercontent.com/22369178/91047146-e6dc7580-e619-11ea-8d38-a4c49692298b.png)

**Comment by Snuffleupagus** [comment]
Related to issue #8019 and/or #8022; hence fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1336572 and/or https://bugzilla.mozilla.org/show_bug.cgi?id=1336591
