### ISSUE TITLE
How to pre fill the acroform fields

### ISSUE THREAD

**Issue by Nilanth** [mozilla/pdf.js#12277]
Configuration:
- Web browser and its version: Chrome 84.0
- Operating system and its version: Catalina 10.15.3
- PDF.js version: 2.4.456
- Is a browser extension: No
I have collected some data from the user using HTML forms and I need to fill those data to acro form fields and need to save the PDF.

**Comment by calixteman** [comment]
You could use:
https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L877

**Comment by Nilanth** [comment]
@calixteman 
in what structure I need to pass the JSON data to saveDocument method? is there any example for this?

**Comment by timvandermeij** [comment]
You indeed need to fill the `annotationStorage` and call `saveDocument`. There is no example for that; you'll have to build it yourself.

**Comment by VineelG** [comment]
Hi, I am trying to pre fill the acroform fields using annotationStorage and by calling saveDocument(annotationStorage). But PDFDocumentProxy will always get empty annotationStorage, even though I add values to annotationStorage . I have tried using promise, but the storage will always be empty. I am trying to saveDocument in side loadingTask promise. Using sample code provided in Acroforms example.

Am I doing anything wrong here, could you please suggest how to achieve pre filling field values in acroforms.

Thanks
![2020-10-14_23-44-47](https://user-images.githubusercontent.com/68660373/96028746-54b55880-0e77-11eb-9bf5-bcd796b7ba86.png)

**Comment by Marc-Hoch** [comment]
Do you find a solution?
