### ISSUE TITLE
Spurious ☒-like characters when printing some PDFs on macOS (see attached PDF)

### ISSUE THREAD

**Issue by barrykn** [mozilla/pdf.js#12282]
Attach (recommended) or Link to PDF file here: I have attached the PDF (edited to remove sensitive information):
[DynamicPDF-redact4.pdf](https://github.com/mozilla/pdf.js/files/5127111/DynamicPDF-redact4.pdf)

Configuration:
- Web browser and its version: Firefox 82.0a1 (2020-08-25) or 81.0b2. Also many earlier versions, going back at least to Firefox 68.11esr (and probably before that).
- Operating system and its version: macOS 10.14.6 (18G6020). Also reproduces on macOS 10.13.6 (17G14019). Issue does not reproduce on Windows.
- PDF.js version: 2.6.302 (extracted from Firefox 82.0a1 2020-08-25 omni.ja to check version number), and many earlier versions also
- Is a browser extension: No, the version that is built into Firefox

Steps to reproduce the problem:
1. Open attached PDF.
2. Print attached PDF. (To see the problem on screen, choose to "Print using the system dialog", then click "PDF" in the lower-left corner and choose "Open in Preview".)

What is the expected behavior? (add screenshot)
Screenshot from doing the STR with Google Chrome 85.0.4183.83 (with Chrome's built-in PDF viewer, not pdf.js):
![Screenshot-GoogleChrome](https://user-images.githubusercontent.com/2141841/91246222-25e6f580-e704-11ea-9327-eff53332c105.png)
(Opening the PDF directly with Apple Preview also shows the expected behavior.)

What went wrong? (add screenshot)
Screenshot from Firefox 82.0a1 (2020-08-25):
![Screenshot-Fx82a1-2020-08-25-pdfjs2 6 302](https://user-images.githubusercontent.com/2141841/91246225-27182280-e704-11ea-9e01-b5b0e92714a3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
No link because I'm using the pdf.js that comes with Firefox

**Comment by marco-c** [comment]
Is this still reproducible?

**Comment by barrykn** [comment]
I've just retested with Firefox 91.4.0esr and Firefox Nightly 97.0a1 (2021-12-08), and neither one reproduces the issue. To make sure the failure to reproduce is not due to any OS change on my system or the like, I also retested with Firefox 82.0.3, and it still reproduces in that version.

Since Firefox no longer appears to have this issue, I'll close it.

**Comment by marco-c** [comment]
It would be great to find out what fixed this using https://mozilla.github.io/mozregression/, if you have time (it shouldn't take that long).

**Comment by barrykn** [comment]
I'll do it when I get a chance, hopefully tomorrow but definitely no later than this weekend.

**Comment by barrykn** [comment]
Actually, I decided to just do it now and get it over with. Here's a screenshot from after the mozregression run.
![Screen Shot 2021-12-09 at 1 41 52 AM](https://user-images.githubusercontent.com/2141841/145372450-28b68935-6d8a-422d-8bf8-0d19ef7a1dec.png)

**Comment by barrykn** [comment]
And here is the last pushlog_url in case it might be helpful:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=d735e197d708d85d9b7e7cb1ea3609bdc4f27bd6&tochange=7387be4b195f3f266410d8faafbaf80f8176e293

**Comment by marco-c** [comment]
Thanks! The range looks reasonable, given that it is a Cairo update.
So this was fixed in Firefox 90.
