### ISSUE TITLE
Firefox Issue: use pdfjs v2.4.456 version,Error:too much recursion

### ISSUE THREAD

**Issue by lpf740024123** [mozilla/pdf.js#12289]
Configuration:
- Web browser and its version: Firefox 80.0(64 bit)
- Operating system and its version:
- PDF.js version: V2.4.456
- Is a browser extension:

Steps to reproduce the problem:
1. git checkout master
2. git checkout v2.4.456 
3. gulp server
4. Refresh the browser a few more times, 
5. F12,   Console, 
Error: too much recursion
  Instantiating http://localhost:8888/node_modules/core-js/modules/es.symbol.js
  Loading http://localhost:8888/node_modules/core-js/es/symbol/index.js
  Loading pdfjs/core/worker.js

**Comment by Snuffleupagus** [comment]
> git checkout v2.4.456

Does it work if you skip the above line?
Please note that in general *all* development happens (or should happen) against the `master` branch, and the version mentioned above is no longer under (active) development.

> gulp server

Furthermore, there's one thing missing *before* this line: an invocation of `npm install`.
It's certainly *possible* that an older PDF.js version doesn't work all that well with the latest dependencies, so the first thing to do when checking out an older commit is to ensure that you test with its *intended* npm packages; note also https://github.com/mozilla/pdf.js#getting-the-code

> Refresh the browser a few more times,
> [...]
> Error: too much recursion

Does this happen for *every* reload, or only intermittently?
If it's the latter, then it's very unlikely to be an issue that we can realistically fix. Besides, as already mentioned, version `v2.4.456` is no longer under development.

**Comment by Snuffleupagus** [comment]
Without additional information, i.e. answers to *all* of the questions above, it's probably not meaningful to keep this issue open.
/cc @timvandermeij
