### ISSUE TITLE
Modified form save data warning dismissed if users chooses to print/save but the action is canceled

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12283]
**Affected versions**
* Firefox 81.0b2
* Latest Nightly 82.0a1

**Affected platforms**
* Windows 10 64bit
* MacOS 10.15.6
* Ubuntu 18.04 64bit

**Steps to reproduce**
1. Open a pdf with form (eg: https://www.irs.gov/pub/irs-pdf/f1040.pdf)
2. Enter some text in a random field
3. Click the print button inside pdf/Hit CTRL+S
4. Cancel the print action/save action
5. Reload/close the tab with the pdf

**Expected result**
* Save notification message is still there since user did not print/save the page.

**Actual result**
* Save notification message is not displayed anymore and the data is lost upon reloading/closing the tab

**Regression range**
* First bad: 79f9ec2f6fece69848aefefb9300fa3d35aa5593
* Last good: 9877228c87db0fe7f1dd353ff8bc5981f52d8622
* Pushlog: https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=9877228c87db0fe7f1dd353ff8bc5981f52d8622&tochange=79f9ec2f6fece69848aefefb9300fa3d35aa5593
* Potential regressor: Bug 1660617 - Update pdf.js to version 2.6.302 / https://github.com/mozilla/pdf.js/pull/12265

**Additional notes**
* Also logged in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1661207

**Suggested severity**
* I my opinion this should have the S2 severity since we are dealing with data loss.

**Comment by Snuffleupagus** [comment]
> Cancel the print action/save action
> [...]
> Save notification message is not displayed anymore and the data is lost upon reloading/closing the tab

That's a known problem, which is even *explicitly* mentioned in https://github.com/mozilla/pdf.js/pull/12265#issue-472003497, and in general it's probably going to very difficult to detect those case.

> Potential regressor: Bug 1660617 - Update pdf.js to version 2.6.302 / #12265

Sorry, but this doesn't really make sense, and as mentioned in that PR the "cancelling of saving"-case already didn't work prior to that.

**Comment by timvandermeij** [comment]
We would be happy to address this, but I don't think there is any way for us to know if printing/saving succeeded in general and across browsers.

**Comment by timvandermeij** [comment]
Closing since I don't know of any way we can know this, especially across browsers. The upstream issue will remain open for any ideas, but for now this is not actionable.
