### ISSUE TITLE
schedule of the next release?

### ISSUE THREAD

**Issue by szaimen** [mozilla/pdf.js#12281]
Hi, sry, I don't want to disturb, but is there already a schedule for the next release?
I am really excited because of the new design, that was merged in #11077 and can't wait to see it in nextcloud/pdf_viewer, which needs a new release of pdf.js to get the design changes, too.

**Comment by Snuffleupagus** [comment]
> [...] but is there already a schedule for the next release?

No, there's currently no time-line for this.

> I am really excited because of the new design, that was merged in #11077 and can't wait to see it in nextcloud/pdf_viewer,

Ideally they should *not* actually be using the viewer as-is, but should rather implement their own UI; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
