### ISSUE TITLE
Include l10n.js file in pdfjs-dist package

### ISSUE THREAD

**Issue by sandanat** [mozilla/pdf.js#12291]
Hello!
I have implemented pdf-viewer for Vuejs like you have in [pdf.js/web/viewer.html](https://github.com/mozilla/pdf.js/blob/master/web/viewer.html). You can see [live demo](https://codepen.io/sandanat/pen/xxVdgYM).
My implementation is based on npm [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) package and doesn't work without file [pdf.js/external/webL10n/l10n.js](https://github.com/mozilla/pdf.js/blob/master/external/webL10n/l10n.js) which is absent in pdfjs-dist.
So I had to manually place this file in [pdfjs-dist/lib/external/webL10n/l10n.js](https://github.com/sandanat/vue-pdf-app/blob/master/src/pdfjs-dist/lib/external/webL10n/l10n.js) to make it work. This file is required in [pdfjs-dist/lib/web/genericl10n.js](https://github.com/mozilla/pdfjs-dist/blob/master/lib/web/genericl10n.js#L29).

Could you include [pdf.js/external/webL10n/l10n.js](https://github.com/mozilla/pdf.js/blob/master/external/webL10n/l10n.js) from your pdf.js repo into `pdfjs-dist/lib/external/webL10n/l10n.js`? 

My [git repo](https://github.com/sandanat/vue-pdf-app)
My [npm](https://www.npmjs.com/package/vue-pdf-app)

Thank you!

**Comment by Snuffleupagus** [comment]
Please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Hence the `pdfjs-dist` library is *purposely* not including the files necessary to build the full default viewer, and this issue is thus WONFIX by design.
