### ISSUE TITLE
Invalid DA for some text annotations which use a font not in DR

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12294]
Attach (recommended) or Link to PDF file here:
https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/joyaku/annai/pdf2/250.pdf

This pdf contains some text annotations with (e.g. "Full name" field on the 1st page):
 - `DA = "/MSGothic 8.5 Tf 0 g"`
 - `DR = << /Font << /KozMinPr6N-Regular 2867 0 R >> >>`

When trying to print/save such a modified textfield then it isn't rendered correctly because the font is not found in DR.
According to the specs it seems that it's an error.
Since `/MSGothic` is present in Acroform::DR, then a way to fix this issue is to use a fallback dict  when a resource is not available.

Do we want to fix this issue with such a workaround (I mean fix the DR: it tryed and it works well) ?
Or do we want to wait for a more general fix to handle chars which are not in the font coming from DA ?
Or anything else ?

**Comment by Snuffleupagus** [comment]
> Since `/MSGothic` is present in Acroform::DR, then a way to fix this issue is to use a fallback dict when a resource is not available.

The correct solution, as mentioned in https://github.com/mozilla/pdf.js/pull/12292#pullrequestreview-476774356, is to first fix issue #12226 and then *correctly* merge the two different `DR` dictionaries.

**Comment by waluyo102** [comment]
Is good

**Comment by timvandermeij** [comment]
Closing since this is fixed by #12361.
