### ISSUE TITLE
When the page's width is big,the content will not be clear.How to deal with it?

### ISSUE THREAD

**Issue by laicelery** [mozilla/pdf.js#12304]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since none of the requested information in the template is provided and the question is not clear at all, so it's not actionable.
