### ISSUE TITLE
PDF - yellow fallback bar doesn't appear below URL bar on some files/links

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12303]
**Affected versions**
* 81.0b3, 81.0b4, 82.0a1 (2020-08-30);

**Affected platforms**
* macOS 11.0, Windows 10, macOS 10.15

**Steps to reproduce**
- pdfjs.renderInteractiveForms - true

1. Launch Firefox;
2. Access links such as: [1](https://royalegroupnyc.com/wp-content/uploads/seating_areas/sample_pdf.pdf), [2](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf);
3. Click inside the page - on any form;

**Expected result**
* yellow fallback bar should appear below URL bar;

**Actual result**
* fallback bar not displayed;

**Regression range**
* First bad: 2020-08-12;
* Last good: 2020-08-13;
* Pushlog: [link](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=74b3be6fcb93aba5e967179e49676f4fb6422851&tochange=f46205a42faecda0e5a73bdcde0a8e1caa0126d9);
* Potential regressor: 1658934

**Additional notes**
* S2 as suggested severity.

**Comment by Snuffleupagus** [comment]
> yellow fallback bar should appear below URL bar;

No it shouldn't, since those forms contain functionality that's now supported; this the *expected* result of PR #12271 (which fixed issue #12217, that you filed :-)

**Comment by cfogelSV** [comment]
Ok on that par. Thanks for the confirmation.

For [irs.gov](https://www.irs.gov/pub/irs-pdf/f1040.pdf) it still appears.
It's a bit unclear, as per notes in the [1661338 uplift](https://bugzilla.mozilla.org/show_bug.cgi?id=1661338) the yellow bar is expected to be displayed.

Is it scripted different or does that form is of a different type? 
If so, what are the key differences that we should look after from this point on?

**Comment by Snuffleupagus** [comment]
> It's a bit unclear, as per notes in the [1661338 uplift](https://bugzilla.mozilla.org/show_bug.cgi?id=1661338) the yellow bar is expected to be displayed.

Are you perhaps referring to https://bugzilla.mozilla.org/show_bug.cgi?id=1661338#c5?
If so, that simply fixed a regression that prevented the "Open With Different Viewer"-button from working *if and only* the fallback bar is displayed, it does *not at all* imply that the fallback bar should be unconditionally displayed for all forms.

> Is it scripted different or does that form is of a different type?

Please refer to https://github.com/mozilla/pdf.js/pull/12271#issue-472172943, and the commit messages in that PR for additional details.
Admittedly this is all pretty technical, and just opening a PDF document isn't usually enough to determine *exactly* what sort of form data it may contain (you really need to look at the actual data-structure of the PDF document itself).

> If so, what are the key differences that we should look after from this point on?

This is what determines if the fallback bar is displayed, when encountering forms:
https://github.com/mozilla/pdf.js/blob/aa27e7fb8d57893fac3810efc56c5d65ce6bd7ec/web/app.js#L1445-L1454

For an individual PDF document, after loading it, executing `PDFViewerApplication.documentInfo` in the web-console shows you the corresponding values here.

**Comment by cfogelSV** [comment]
Thanks again for clearing it out.
