### ISSUE TITLE
All empty pages in pdf file

### ISSUE THREAD

**Issue by uuggene** [mozilla/pdf.js#12306]
Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension: no

Checked on demo website:
https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Upload attached file.
2. All pages are empty.
[document13-08-2020-122237.pdf](https://github.com/mozilla/pdf.js/files/5150027/document13-08-2020-122237.pdf)

Expected:
Acrobat reader can open this document.
![scevkRtfnQ](https://user-images.githubusercontent.com/11631048/91715781-11d54500-eb97-11ea-87d6-1ae9556a964d.png)

**Comment by timvandermeij** [comment]
Strange, there are also no errors/warnings in the console. Thank you for reporting this.

**Comment by THausherr** [comment]
```
0.75 0.0 0.0 -0.75 0.0 842.0 cm
q
  1.33333 0.0 0.0 -1.33333 0.0 1122.6666 cm
  W
  n
  0.75 0.0 0.0 -0.75 0.0 842.0 cm
  q
    794.6667 0.0 0.0 -1122.6666 0.0 1122.6666 cm
    /I1 Do
  Q
Q
```
"W n" applied to non existent path. If the software treats this as an empty path, the result of the clip will be an empty path 😭

**Comment by Snuffleupagus** [comment]
> "W n" applied to non existent path. If the software treats this as an empty path, the result of the clip will be an empty path

I suppose that the question here becomes how to determine that there's no clip-path specified, without having to manually track things since that seems both error-prone (with future code changes) and potentially also slower.

As far as I can tell, there's no property on e.g. the `CanvasRenderingContext2D` that will inform you whether or not a clip-path exists.

**Comment by uuggene** [comment]
I contacted the Telerik PdfProcessing (this library is used to create pdf document) and i've got this answer, maybe it could help.

> The Adobe Acrobat Reader successfully imports the document generated by the PdfProcessing because the default behavior when there is no path construction is to use the entire page size (from the Pdf specification: The initial clipping path includes the entire page) so I can suggest bringing this information to the pdf.js team.

**Comment by skuhnert** [comment]
It seems like there are several libraries, creating these empty path clips. Is it possible, to ignore the "W n" pair?

**Comment by brendandahl** [comment]
Maybe we could create a clip path in beginDrawing that is equal to the bounds of the page?

**Comment by cetinsert** [comment]
By the way, `PDF.js`/`SVG` rendering are *not* blank with both of the files linked so far.
