### ISSUE TITLE
PDF form - yellow fallback bar remains in view when accessing a different page

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12305]
**Affected versions**
* 81.0b4, 82.0a1(2020-08-29);

**Affected platforms**
* macOS 10.15, Windows 10;

**Steps to reproduce**
1. Launch Firefox;
2. Access https://www.irs.gov/pub/irs-pdf/f1040.pdf
3. Click inside the page so the yellow banner appears;
4. Navigate to any other page;

**Expected result**
* banner disappears;

**Actual result**
* banner remains in view;

**Regression range**
* First bad: 2020-08-27;
* Last good: 2020-08-26;
* Pushlog: [URL](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=61ed3192760a3aaef282c089c064fc8dd3890125&tochange=109f3a4de56716d3e1162c2368fe37b8a377f72f);
* Potential regressor: [1661338](https://bugzilla.mozilla.org/show_bug.cgi?id=1661338)

**Additional notes**
* S3 as suggested severity, can be bumped higher since it's affecting the UX side of things;
* .gif with the issue:
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/49230899/91712169-e69b2780-eb8f-11ea-989b-00577fd268de.gif)

**Comment by Snuffleupagus** [comment]
> * Pushlog: [URL](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=61ed3192760a3aaef282c089c064fc8dd3890125&tochange=109f3a4de56716d3e1162c2368fe37b8a377f72f);
> 
> * Potential regressor: [1661338](https://bugzilla.mozilla.org/show_bug.cgi?id=1661338)

Sorry, but I don't think this makes sense here!

Using mozregression I get the following pushlog, which honestly is a lot more reasonable from a technical perspective:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=13ffa1b168d4d981a3bfa2f5150e496e5b9d9780&tochange=0d738afe8203226a708025b6cef8102dabf5b5c2
thus pointing to https://bugzilla.mozilla.org/show_bug.cgi?id=1656494 instead.

**Comment by cfogelSV** [comment]
You are right, the initial regression range is wrong.
Thanks for double checking!

Leaving a note to one more related issue that appeared and should vanish if this one is fixed:

STR - wise:
- open [irs.gov](https://www.irs.gov/pub/irs-pdf/f1040.pdf)
- navigate away or refresh the page;
- navigate back to  [irs.gov](https://www.irs.gov/pub/irs-pdf/f1040.pdf);

The issue is that now there are 2 bars overlaid and you can only close one.

**Comment by msujaws** [comment]
Yes, I will look in to this. Sorry I didn't see the message here since I don't check my GitHub notifications often. Bugzilla is a better place to reach me. I was made aware of this from https://bugzilla.mozilla.org/show_bug.cgi?id=1671504

**Comment by Snuffleupagus** [comment]
> https://bugzilla.mozilla.org/show_bug.cgi?id=1671504

That's now landed, and I can confirm that it's indeed fixed. /cc @timvandermeij

**Comment by timvandermeij** [comment]
Nice work!
