### ISSUE TITLE
Hi, I want to draw a rectangle in the existing pdf with co-ordinates. How to do it

### ISSUE THREAD

**Issue by JohnAugustineG** [mozilla/pdf.js#12316]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
PDF.js is a viewer, not an editor, so drawing is out of scope and you'll have to implement such functionality yourself.
