### ISSUE TITLE
getOperatorList() not recognized as a function.

### ISSUE THREAD

**Issue by BowArrow** [mozilla/pdf.js#12322]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. npm i --save pdfjs-dist
2. write god to load a doc get a page and then attempt to use .getOperatorList on page. It's not recognized as a function

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Without the necessary details, in particular the used `pdfjs-dist` version and a running example to debug this, we cannot provide assistance here. There is an example that uses `pdfjs-dist` and calls `getOperatorList`, so perhaps that could help to find out what's wrong: https://github.com/mozilla/pdf.js/blob/1f7175542e6ea155ddaeb17ded6a66b3c435d9e5/examples/node/pdf2svg.js#L112
