### ISSUE TITLE
How does this plug-in access HTTP PDF files properly?

### ISSUE THREAD

**Issue by Wumei222** [mozilla/pdf.js#12325]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
The error messages:
![09-04_0](https://user-images.githubusercontent.com/49270645/92188879-59f2b100-ee90-11ea-8b59-cedc8b5ba204.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> The error messages:

Based on the screen-shot, this is clearly a browser *limitation* and not related to the PDF.js library as such.
Given this, and also the fact that not a single piece of actionable information was provided, the issue is thus INVALID.
