### ISSUE TITLE
Stable version on NPM not updated after release

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12324]
Updating NPM when making a release stable does not work. I made version 2.5.207 stable today, but NPM still shows version 2.4.456. What did work is updating the `next` tag for pre-release 2.6.347, so it looks like the release script doesn't handle release updates correctly in contrast to release creations. Perhaps the hook is not triggered correctly or an error occurred in the logs?

Please find the cause of this, and for now update the `latest` tag on NPM to version 2.5.207 manually.

/cc @brendandahl

**Comment by timvandermeij** [comment]
Moreover, there was a suggestion to mark the current pre-release as the final one to support IE 11 so we can drop support in the next release. I'm not sure what happens if we edit a pre-release, i.e., are the hooks re-triggered? We don't want multiple pushes to `pdfjs-dist` for example...

**Comment by timvandermeij** [comment]
@brendandahl Gentle ping for this issue :)

**Comment by brendandahl** [comment]
I updated the npm package. It will be a little while until I can look into the bot issue.

**Comment by timvandermeij** [comment]
Great, thanks!

**Comment by timvandermeij** [comment]
@brendandahl I think it would be good to make a new release since the last one was in September. We should probably figure this one out once and for all so we don't run into this issue again during the release. Do you have time to check what goes wrong on the bots here?

**Comment by brendandahl** [comment]
Let's go ahead and do a release and I'll manually fix any issues that come up. I need to do a bunch of work to get my bot test setup working again, and won't get to that for awhile.

**Comment by benbro** [comment]
npm still show v2.5.207. Is it possible to update it to v2.6.347?

**Comment by Snuffleupagus** [comment]
> npm still show v2.5.207. Is it possible to update it to v2.6.347?

But, that's correct since `v2.5.207` is still the current stable version and `v2.6.347` is still the pre-release; see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions and note in particular the `next`-tag.

**Comment by timvandermeij** [comment]
@brendandahl I made a new release today, so we need to fix the stable tag manually again. Could you set the `latest` tag on NPM to version `2.8.335`?

**Comment by timvandermeij** [comment]
@brendandahl Gentle ping for the above so that NPM reflects the correct release state again; thanks!

**Comment by timvandermeij** [comment]
Closing since we decided to only go for stable release now in #14226, which solves this issue since release creations already worked and we don't need to do release updates then anymore.
