### ISSUE TITLE
"Cannot set property 'textContent' of null" when creating PDFViewer

### ISSUE THREAD

**Issue by tigrenok00** [mozilla/pdf.js#12320]
Configuration:
- Web browser and its version: Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- Operating system and its version: Win 10
- PDF.js version: 2.4.456
- Is a browser extension: no

Steps to reproduce the problem:

I used sample code to render all pages from simpleviewer example, however the line 
**this.pdfViewer = new pdfjsViewer.PDFViewer** gives the following error:

```
`core.js:15724 ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'textContent' of null
TypeError: Cannot set property 'textContent' of null
    at PDFViewer._resetView (pdf_viewer.js:5689)
    at new BaseViewer (pdf_viewer.js:5306)
    at new PDFViewer (pdf_viewer.js:6320)

`
```

I am using Angular. When I use **pdfjsViewer.PDFPageView**, everything works fine. But when I try to create pdfjsViewer.PDFViewer there is an error.

My code:

async ngOnInit(): Promise<void> {
    this.container = document.getElementById("viewer");
    this.eventBus = new pdfjsViewer.EventBus();

    this.pdfLinkService = new pdfjsViewer.PDFLinkService({
      eventBus: this.eventBus,
    });

    this.pdfFindController = new pdfjsViewer.PDFFindController({
      eventBus: this.eventBus,
      linkService: this.pdfLinkService,
    });

    this.pdfViewer = new pdfjsViewer.PDFViewer({
      container: this.container,
      eventBus: this.eventBus,
      scale: this.scale,
      textLayerMode: 0,
      linkService: this.pdfLinkService,
      findController: this.pdfFindController,
    });

    console.log("after create");

    this.eventBus.on("pagesinit", function () {
      this.pdfViewer.currentScaleValue = "page-width";
    });

    try {
      await this.showPDF();
    } catch (error) {
      console.log(error);
    }
  }`

Imports:

````

import {
  getDocument,
  PDFPageViewport,
  PDFRenderTask,
  PDFDocumentProxy,
  PDFPageProxy,
  PDFLoadingTask,
  PDFPromise,
  PDFRenderTextLayer,
} from "pdfjs-dist";

import * as pdfjsLib from "pdfjs-dist/build/pdf";
import * as pdfjsViewer from "pdfjs-dist/web/pdf_viewer";

pdfjsLib.GlobalWorkerOptions.workerSrc = "../assets/pdf.worker.js";
```
`

**Comment by Snuffleupagus** [comment]
The error suggests that your "container"-element doesn't actually contain a "viewer"-element, which is required in order for this to work correctly; please note https://github.com/mozilla/pdf.js/blob/84da13b4871f937bdd6d65fe561e301680f28dbb/web/base_viewer.js#L48-L51 and https://github.com/mozilla/pdf.js/blob/84da13b4871f937bdd6d65fe561e301680f28dbb/web/base_viewer.js#L144-L145

---

Hence, please make sure that you follow the `simpleviewer` example in https://github.com/mozilla/pdf.js/tree/master/examples/components *exactly* (see the `simpleviewer.js` *and* `simpleviewer.html` files), note especially https://github.com/mozilla/pdf.js/blob/84da13b4871f937bdd6d65fe561e301680f28dbb/examples/components/simpleviewer.html#L45-L47

**Comment by tigrenok00** [comment]
This is my html for the element:

`   <div id="viewerContainer" tabindex="0">
          <div id="viewer" class="pdfViewer">
          </div>
        </div>`

When I work with pdfjsViewer.PDFPageView with the same container element, everything works fine.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> `<div id="viewerContainer" tabindex="0"> <div id="viewer" class="pdfViewer"> </div> </div>`

In that case the line `this.container = document.getElementById("viewer");` from https://github.com/mozilla/pdf.js/issues/12320#issue-691929644 is trivially wrong, hence please actually follow the examples referenced above; note in particular https://github.com/mozilla/pdf.js/blob/84da13b4871f937bdd6d65fe561e301680f28dbb/examples/components/simpleviewer.js#L35

Finally, see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
