### ISSUE TITLE
GlobalWorkerOptions.workerSrc (vanilla js )

### ISSUE THREAD

**Issue by mohamed-fared** [mozilla/pdf.js#12335]
im trying to setup the pdf,js
and i face this problem  with Deprecated API usage: No "GlobalWorkerOptions.workerSrc" [specified.]
![pdf](https://user-images.githubusercontent.com/38176894/92329569-7d705400-f068-11ea-909e-fb2307fce7b4.jpg)

main.js 

const url = "./pdf.pdf"
let pdfDoc = null , pageNum = 1, pageIsRendering = false , pageNumIsPending = null ;
const scale = 1.5, 
canvas = document.querySelector('#pdf-render'),
ctx = canvas.getContext('2d');
// render the page 
const renderPage = num =>{

}
// get the document 
var x = pdfjsLib.getDocument(url).promise.then(pdfDoc_ =>{
    pdfDoc = pdfDoc_
    console.log(pdfDoc)
}).catch(err =>
    {
        console.log(err)
    })

**Comment by mohamed-fared** [comment]
html code : 

"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
<title>Document</title>
</head>
<body>
<div class="ttop-bar">
<button class="btn" id="prev-page">
<i class ="fas fa-arrow-circle-left"> </i> Prev page
</button>
<button class="btn" id="next-page">
 next page<i class ="fas fa-arrow-circle-right"> </i> 
 </button>
<span class="page-info">
Page <span id="page-num"></span>of <span id="page-count"></span>
</span>
</div>
    <canvas id="pdf-render"></canvas>
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.4.456/build/pdf.min.js"></script>
    <script src="./main.js" ></script>
    
</body>
</html>"

**Comment by timvandermeij** [comment]
You _always_ need to provide a worker path; see https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L24-L25 for example, otherwise PDF.js will not perform well.
