### ISSUE TITLE
Last verison of pdf.js, but can't see any pdf in page

### ISSUE THREAD

**Issue by AliSinaSaemi** [mozilla/pdf.js#12332]
Attach (recommended) or Link to PDF file here:
I used python to make a local server by using (python -m http.server)
after opening it in chrome I get these errors below

Console: 
`
GET http://localhost:9000/build/pdf.js net::ERR_ABORTED 404 (File not found)
pdfjs.js:23 Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (pdfjs.js:23)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (app.js:39)
    at __webpack_require__ (bootstrap:19)
    at Object.<anonymous> (viewer.js:40)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
(anonymous) @ pdfjs.js:23
__webpack_require__ @ bootstrap:19
(anonymous) @ app.js:39
__webpack_require__ @ bootstrap:19
(anonymous) @ viewer.js:40
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
favicon.ico:1 GET http://localhost:9000/favicon.ico 404 (File not found)
 `
Configuration:
- Web browser and its version:  85.0.4183.83 (Official Build) (64-bit)
- Operating system and its version: Windows 10: 1704
- PDF.js version: 2.6.347
- Python version: 3.8.2

Steps to reproduce the problem:
1. Open viewer.html as index.html
2. Open localhost (run server) using python

What is the expected behavior? (add screenshot)
I must see the pdf file showing in the page

What went wrong? (add screenshot)
https://gofile.io/d/iuGGJ8

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The error is pretty clear: the file is not served correctly so it can't be found. You have most likely not built PDF.js, but without more information it's impossible to tell. Instead of using a Python server, you can run `gulp server` which comes with PDF.js to start a development server. You can use `gulp generic` to build PDF.js.
