### ISSUE TITLE
Integration to website

### ISSUE THREAD

**Issue by manolinik** [mozilla/pdf.js#12338]
Hello

I need to integrate this library to a website, in order to count pages submitted pdf files from the front users and assign this variable to a cart(woocomerce). Can someone developer help me with this?

**Comment by rt1301** [comment]
Insert the library via CDN to the HTML document using the script tag.
`<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.min.js" integrity="sha512-Vvbhrrw9oPzjTUUbw+bw/P1mMW9NW2H21DhoajJW69XzOBhICUlI5rywBcy7SI8Y5Dc9v+oIe5lXwQX0PauUCA==" crossorigin="anonymous"></script>`
Then in your JS file, initialize the url for your PDF file
`const url = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf';`
and then initialize the other variables required for the library:
`let pdfDoc = null,
    pdfNum = 1,
    pdfIsRendering = false,
    pageNumIsPending = null;`
`let totalPageNum;`
Finally make a function to Asynchronously download the pdf file and store the pageNum to your totalPageNum variable to access it later
`// Get Document`
`pdfjsLib.getDocument(url).promise.then(pdfDoc_=>{
    pdfDoc = pdfDoc_;
    totalPageNum = pdfDoc.numPages;
});`
then you can access the total page numbers from the totalPageNum variable.

**Comment by manolinik** [comment]
ΟK I am wondering what is the purpose of downvoting?? We are not all  high level developers at the moment.

Thank you for your kindly support rt1301.
But in this particular occasion It's not the js library problem but the php functionality of the website which will use the library

**Comment by timvandermeij** [comment]
This is an issue tracker, _not_ a support forum, hence the downvotes. Closing.

**Comment by manolinik** [comment]
Please read the FAQ of this js library
