### ISSUE TITLE
PDF not rendering correctly

### ISSUE THREAD

**Issue by KuruzuTraputis** [mozilla/pdf.js#12340]
Hello,

I`m rendering document, but got same issue.

Closed issue: https://github.com/mozilla/pdf.js/issues/6648

How to fix this?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this issue will be closed as INCOMPLETE since there's no actionable information provided.

**Comment by suciptoaxel** [comment]
Siippp baguss

**Comment by suciptoaxel** [comment]
Siiipppp bagusss
