### ISSUE TITLE
In IE browser, an error is reported

### ISSUE THREAD

**Issue by tanglinhai** [mozilla/pdf.js#12348]
Configuration:
- Web browser and its version:  ie11
- Operating system and its version:  win10
- PDF.js version:   Official version
- Is a browser extension:

In IE browser, an error is reported:      unable to get undefined or null referenced property "allsettled"
Address:            https://mozilla.github.io/pdf.js/es5/web/viewer.html

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. ***However, this support will be dropped after stable version `2.6.347`.***

**Comment by timvandermeij** [comment]
In addition to the above, `allSettled` is a modern `Promise` extension, so you'll need to use the ES5 version of PDF.js to support IE.
