### ISSUE TITLE
Printing yeilds incorrect size

### ISSUE THREAD

**Issue by YurkoWasHere** [mozilla/pdf.js#12346]
Docusign signed documents, (cant attach due to confidential content). Screen shots attached with content replace by box.

Same PDF document on another computer with same setup (firefox version, software, etc) seem to work fine. Privacy mode in firefox does not seem to change the issue.   Tried to remove all "storage" object in dev tools in firefox without any luck, Not sure what else to do or try.  Im guessing its some sort of client level setting in PDF.JS?

Downloading document and opening it in acrobat yields a good print.
In the past i have also seen some computers generate larger images when printing stretching 1 page onto 4.  Not sure how it got corrected.

Any suggestions for debugging would be appreciated.

Configuration:
- Web browser and its version: 68.12.0esr
- Operating system and its version: win 10
- PDF.js version: PDF2.3.200
- Is a browser extension:  Both embeded PDF and as part of "firefox preview"

Steps to reproduce the problem:
1. Open file
2. Print it

What is the expected behavior? (add screenshot)
Print with size shown in preview
![image](https://user-images.githubusercontent.com/39072689/92516035-93098900-f1e2-11ea-9294-a3bef8b5853d.png)

What went wrong? (add screenshot)
Print is about 2/3 of the size of the paper. (example below is what happens when print to pdf, but same happens on physical printer)
![image](https://user-images.githubusercontent.com/39072689/92516155-c815db80-f1e2-11ea-8292-a54e34ab6f39.png)

**Comment by timvandermeij** [comment]
First of all, without an example file there is not much we can do to help debug this.

> Same PDF document on another computer with same setup (firefox version, software, etc) seem to work fine.

If it works on another computer, this might suggest a broken Firefox profile. You can try to refresh Firefox; see https://support.mozilla.org/en-US/questions/1119815 for how to do that.

**Comment by YurkoWasHere** [comment]
Thanks @timvandermeij refresh firefox did fix the issue thank you.

Still curious what kind of corruption would create such an issue.
