### ISSUE TITLE
pdfViewer.currentPageNumber fails to change page

### ISSUE THREAD

**Issue by ChrisHSandN** [mozilla/pdf.js#12351]
#### Configuration:
- Web browser and its version: Chrome 85
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: No

#### Steps to reproduce the problem:
1.  https://jsfiddle.net/chris_h/eq7fd94z/
2.  Note how the view remains on page 1 even though `currentPageNumber` is called after the `pagesinit` has fired.

#### What is the expected behavior?
After calling `pdfViewer.currentPageNumber = 2` I would expect the view to change to showing page 2.

#### What went wrong?
The view remains on page 1

**Comment by Snuffleupagus** [comment]
The `viewerContainer` needs to be *absolutely* positioned, note https://github.com/mozilla/pdf.js/blob/e51e9d1f33bd6e404bfa795799f1cc035537091e/examples/components/simpleviewer.html#L24-L36

Hence this issue is, for all intents and purposes, a duplicate of #11626.

**Comment by ChrisHSandN** [comment]
Ah, thank you. That does indeed fix the issue, I did not realise that property was required. 👍
