### ISSUE TITLE
Some checkboxes are not ticked inside 3 party apps if saved from Firefox

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12355]
**Affected versions**
* Latest Nightly 82.0a1 that has the fix from https://github.com/mozilla/pdf.js/issues/12319
(https://treeherder.mozilla.org#/jobs?repo=mozilla-central&revision=6cc2266faca2a2301c81f3442d6d893ad3fc9fdf)

**Affected platforms**
* Ubuntu 18.04 64bit
* MacOS 10.15
* Windows 10 64bit

**Steps to reproduce**
1. Open the following https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/joyaku/annai/pdf2/250.pdf
2. Check the checkboxes from top right or scroll down to `Indirect Ownership` column inside the table from 6.
3. Click inside the checkboxes
4. Save the pdf by download button, save as or open with
5. Open the saved pdf in Foxit Reader.

**Expected result**
* Checkboxes are ticked when opening the PDF in Foxit.

**Actual result**
* Checkboxes are empty.

**Regression range**
* Not a regression since this did not work before as well.

**Additional Notes**
* I also saw one of the checkboxes missing from `Indirect Ownership` when opening in Adobe reader as well.

![image(1)](https://user-images.githubusercontent.com/69848942/92620347-3635cd80-f2cb-11ea-8282-8aa0a49ac035.png)
 
**Suggested severity**
* I my opinion this should have the S2 severity since this is data loss related, not sure how many pdfs are affected though.

**Comment by calixteman** [comment]
It's because the names must be escaped when dumped (see 7.3.5)

**Comment by timvandermeij** [comment]
Fixed by the PR above.
