### ISSUE TITLE
Fix or revert PR #12363

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12367]
See https://github.com/mozilla/pdf.js/pull/12363#issuecomment-691488345 for context. If we can easily fix this I'd prefer that, but otherwise we can revert it for now.

/cc @emilio

**Comment by Snuffleupagus** [comment]
I'd suggest reverting the PR *immediately*, since it currently causes (viewer) errors and testing/makeref won't work correctly, and re-landing it later once it's been carefully tested/validated.

**Comment by emilio** [comment]
I have a fix, but I'm happy re-landing after revert if that's preferred.

**Comment by emilio** [comment]
https://github.com/mozilla/pdf.js/pull/12369 is the fix.

**Comment by emilio** [comment]
(And I think the fix is pretty safe, but again, more than happy to revert my original PR, then land the fix, then re-land my original PR).

**Comment by timvandermeij** [comment]
In order to get `master` working again, we have reverted the original PR in #12368 now. For #12369 you can either include the original commit after the fix commit or squash them both into one commit since they are related and one doesn't work without the other.

**Comment by emilio** [comment]
I've done the former, thanks, and sorry for the trouble!

**Comment by timvandermeij** [comment]
No worries!
