### ISSUE TITLE
Side by side text parsed as if on top of each other.

### ISSUE THREAD

**Issue by mckiernantim** [mozilla/pdf.js#12366]
Attach (recommended) or Link to PDF file here:
[PrettyProblems-20.pdf](https://github.com/mozilla/pdf.js/files/5211229/PrettyProblems-20.pdf)
Side by side text being parsed as if on top of one another.

Configuration:
- Web browser and its version: Chrome 85.0.4183.83 
- Operating system and its version: OS Catalina 10.15.6
- PDF.js version: 1.10.100
- Is a browser extension:

Steps to reproduce the problem:
1.  Document is roughly 100 pages with about 12 of these instances.  Happens the same way in each.  The app I'm using recompiles the JSON into a smaller PDF.

What is the expected behavior? (add screenshot)
It was my hope that the PDF text would be parsed left to right, top to bottom, but on these side by side instances, it renders them as if they were on top of each other - 

data at 877 was expected to be the data which is currently at 906

What went wrong? (add screenshot)
Logged Data 
<img width="934" alt="tim_data_pdf-parse" src="https://user-images.githubusercontent.com/38140787/92966480-a1a3aa80-f445-11ea-837d-7cdbb27f8d7f.png">
 PDF recompiled 
<img width="445" alt="Screen Shot 2020-09-11 at 3 00 36 PM" src="https://user-images.githubusercontent.com/38140787/92966760-1aa30200-f446-11ea-82f2-7e26ee88ef35.png">
PDF original

<img width="723" alt="Screen Shot 2020-09-11 at 2 57 41 PM" src="https://user-images.githubusercontent.com/38140787/92966773-2262a680-f446-11ea-9a28-ca67c8badd9a.png">

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.10.100

That version is a couple of years old, and is thus no longer supported. Please find the *latest* releases at https://github.com/mozilla/pdf.js/releases, and note that as of this writing the lowest supported version is `v2.5.207`.

> It was my hope that the PDF text would be parsed left to right, top to bottom, but on these side by side instances, it renders them as if they were on top of each other

Note that the output of `getTextContent`, which I'm guessing that you're looking at, simply follows the order of the text-rendering operators as they appear in the PDF document itself; there's no attempt to re-order the text in the output.
