### ISSUE TITLE
Investigate forward-back-forward test failures

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12371]
In https://github.com/mozilla/pdf.js/commit/6ab3ba95193e7ff287b7d982cc011742603c3c61 we already disabled the `fbf` tests for Chrome, but all of a sudden they also fail for Firefox now in https://github.com/mozilla/pdf.js/pull/12368#issuecomment-691524124. I'd prefer we fix this, but otherwise we'll have to disable them for Firefox too to make `makeref` pass again. This issue tracks the problem for both browsers.

**Comment by baloone** [comment]
Maybe we could allow getting a small differences between the first and the second round ?

**Comment by timvandermeij** [comment]
Yes, perhaps #12165 might address this too.

**Comment by Snuffleupagus** [comment]
Should we perhaps track this in issue #13061 instead now, since the `fbf` failures are also intermittent?

**Comment by timvandermeij** [comment]
Yes, I have updated that issue so we can close this one.
