### ISSUE TITLE
Status of radio buttons not displayed in Firefox after saving the pdf file from Firefox

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12376]
**Affected versions**
* Latest Nightly 82.0a1
* Firefox 81.0b9

**Affected platforms**
* Ubuntu 18.04 64bit
* MacOS 10.15
* Windows 10 64bit

**Steps to reproduce**
1. Open the following https://royalegroupnyc.com/wp-content/uploads/seating_areas/sample_pdf.pdf
2. Click on a radio button (remember it)
3. Save the .pdf locally
4. Open the .pdf inside Firefox

**Expected result**
* Radio buttons previously saved are displayed in Firefox.

**Actual result**
* Radio buttons that were previously saved are not displayed in Firefox.

**Regression range**
* Not a regression since this did not work before as well.
 
**Additional notes**
* The radio button is displayed in Firefox if pdfjs.renderInteractiveForms is set as false.

**Suggested severity**
* Not sure about the severity here, I would say S2-S3, I would say though that it would be bad if the data saved in Firefox won't be displayed in Firefox but all other pdf editors.

**Comment by calixteman** [comment]
The parent of the radio doesn't have any "V" field so we don't get the parent reference and so the parent is not saved.
