### ISSUE TITLE
Not all ticked checkboxes are displayed in Acrobat Reader

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12373]
**Affected versions**
* Latest Nightly 82.0a1

**Affected platforms**
* Ubuntu 18.04 64bit
* MacOS 10.15
* Windows 10 64bit

**Steps to reproduce**
1. Open the following https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/joyaku/annai/pdf2/250.pdf
2. Scroll down to `Indirect Ownership` column inside the table from 6 and tick all checkboxes.
3. Save the pdf by download button, save as or open with
5. Open the saved pdf in Acrobat Reader.

**Expected result**
* Checkboxes are ticked when opening the PDF in Acrobat.

**Actual result**
* Some checkboxes are ticked, some checkboxes are empty, some can be edited/saved some not, some can't be edited anymore.

**Regression range**
* Not a regression since this did not work before as well.
 
**Suggested severity**
* I my opinion this should have the S2 severity since this is data loss related, not sure how many pdfs are affected though.

**Comment by calixteman** [comment]
This file is encrypted and the resulting string after encryption may contain some `\r` and according to the spec (7.3.4.2), this char is interpreted like a `\n` which avoids to decrypt the string.
Few lines after in the specs, it is written that there is no need to escape such char...
I tested the fix with Acrobat on mac and it's ok.
