### ISSUE TITLE
import pdfjs from 'pdfjs-dist' no longer works

### ISSUE THREAD

**Issue by johnwillyn** [mozilla/pdf.js#12389]
I have been using this line in two places in my app; one is the main webpack app, and the other is a rollup based module:

`import pdfjs from 'pdfjs-dist';`

I just got an update to pdfjs-dist v2.5.207 and this no longer works.

I needed to switch over to:

`const pdfjs = require('pdfjs-dist');`

Not a huge issue, but I thought this might help others who encounter this.

**Comment by timvandermeij** [comment]
I don't think we changed anything in this regard in that particular version. As far as I can tell this has already been the case for quite some time; notice the Webpack example at https://github.com/mozilla/pdf.js/blob/50bc4a18e8c564753365d927d5ec6a6d2cce3072/examples/webpack/main.js#L6 for example.

**Comment by francofantini** [comment]
I'm having the same issue, import was working fine on 2.3.200 but not on 2.5.207.

**Comment by arelaxend** [comment]
Not working

**Comment by xitanggg** [comment]
It seems default import doesn't work, but I got it to work with namespace import `import * as pdfjs from 'pdfjs-dist';`.
