### ISSUE TITLE
Contents are randomly displayed mirrored

### ISSUE THREAD

**Issue by stevemarksd** [mozilla/pdf.js#12380]
Might be related to https://github.com/mozilla/pdf.js/issues/10400

I'm using 

```
var viewport = page.getViewport({
                scale: scale
            });
```

I will add more details later when I have the pdf.

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
For now there are no details for us to work with since the template is empty and no PDF file or example code is available. Closing for now, but we can definitely reopen once all information is present.
