### ISSUE TITLE
Status of radio buttons not displayed in Firefox after saving this particular pdf file from Firefox

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12386]
**Affected versions**
* Latest Nightly 82.0a1
* Firefox 81.0b9

**Affected platforms**
* Ubuntu 18.04 64bit
* MacOS 10.15
* Windows 10 64bit

**Steps to reproduce**
1. Open the following https://www.nta.go.jp/taxes/tetsuzuki/shinsei/annai/joyaku/annai/pdf2/250.pdf
2. Click on a radio button (remember it) (eg: Shares (Stocks) or any other)
3. Save the .pdf locally
4. Open the .pdf inside Firefox

**Expected result**
* Radio buttons previously saved are displayed in Firefox.

**Actual result**
* Radio buttons that were previously saved are not displayed in Firefox.

**Regression range**
* Not a regression since this did not work before as well.
 
**Additional notes**
* The radio button is displayed in Firefox if pdfjs.renderInteractiveForms is set as false.

**Suggested severity**
* Not sure about the severity here, I would say S2-S3, I would say though that it would be bad if the data saved in Firefox won't be displayed in Firefox but all other pdf editors.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
