### ISSUE TITLE
I want to draw something on the page

### ISSUE THREAD

**Issue by LiuSandy** [mozilla/pdf.js#12382]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 85.0.4183.102
- Operating system and its version: Mac OS 10.15.6
- PDF.js version: 2.6.347
- Is a browser extension: no

It's not exactly a bug, I want to draw something on the page, My idea is to create a page size `div`.Then I can do anything on this. like draw a box,Record the starting coordinates of the box.Can you help me? Thanks!

**Comment by timvandermeij** [comment]
This is something that is outside of the scope of PDF.js, so we won't be able to provide support for that.
