### ISSUE TITLE
Viewer Constructor blocks remote rendering

### ISSUE THREAD

**Issue by jsg2021** [mozilla/pdf.js#12385]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: all
- Operating system and its version: all
- PDF.js version: 2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
Construct the viewer and give it a div hosted in another frame... when it was working, it now throws 
```
Invalid `container` and/or `viewer` option.
```

This broke it: https://github.com/mozilla/pdf.js/commit/89f6bb0fc6b76009bff922ac5d5c3c4ddbc21ae2

What is the expected behavior?
Allow constructing a viewer that renders to an alternate window.

**Comment by boulderx** [comment]
When will there be a new release including this fix?

**Comment by WolfgangFahl** [comment]
Why is this closed? I get the message in my code on the following line:

```javascript
const pdfViewer = new pdfjsViewer.PDFViewer({
      container,
      eventBus,
      linkService: pdfLinkService,
    });
```

I don't understand what this message is about. Why would a div be an invalid container?

**Comment by twitwi** [comment]
For anyone that would follow the same path as me: I ended up on this issue and found out that the cause/solution is that the element passed as `container` must have a child div for pdfjs to plug into, as in:

```html
    <div class="container">
        <div></div>
    </div>
```
```css
.container {
    position: absolute;
}
```
