### ISSUE TITLE
Some text is not displayed in pdf.js, but display in foxit or chrome viewer

### ISSUE THREAD

**Issue by temka1234** [mozilla/pdf.js#12399]
Some text of specified PDF is not displayed in pdf.js, but display in foxit or chrome embeded viewer.
[display_bug.pdf](https://github.com/mozilla/pdf.js/files/5252466/display_bug.pdf)

Configuration:
- Google chrome 85.0.4183.102
- PDF.js 2.6.347

Steps to reproduce the problem:
1. Open attached PDF in pdf.js [web viewer](https://mozilla.github.io/pdf.js/web/viewer.html)

![comparison](https://user-images.githubusercontent.com/3648995/93720512-3323c280-fb92-11ea-8db4-aab20395d118.PNG)

**Comment by amit777** [comment]
This PDF seems to load fine for me.  see screenshot:
```
const pdfjsVersion = '2.7.90';
const pdfjsBuild = '6728c8fa6';
```

**Comment by amit777** [comment]
![Screen Shot 2020-09-26 at 10 09 07 PM](https://user-images.githubusercontent.com/2703309/94356570-f8fc6a00-0044-11eb-96bd-ce07f56908b5.png)

**Comment by temka1234** [comment]
@amit777 Where i can find `2.7.90` version?

**Comment by temka1234** [comment]
See this version in web viewer source, bug still reproduced.
My operation system: windows 10
