### ISSUE TITLE
The checkboxes have no visual effect while navigating over them using keyboard navigation

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla/pdf.js#12401]
**[Affected Versions]:**
- Firefox RC 81.0 (Build ID: 20200917005511)
- Firefox Nightly 82.0a1 (Build ID: 20200920213416)

**[Affected Platforms]:**
- Windows 10 (x64)
- macOS 10.15
- Ubuntu 18.04 x64

**[Prerequisites]:**
- Have a new profile created.
- Have the “pdfjs.renderInteractiveForms” pref set to “true”.

**[Steps to reproduce]:**
1. Start the Firefox Browser with the profile from prerequisites.
2. Navigate to “https://www.irs.gov/pub/irs-pdf/f1040.pdf”.
3. Navigate through the 2nd page using keyboard navigation and observe the checkboxes.

**[Expected results]:**
- The checkboxes are visibly focused.

**[Actual results]:**
- There is no visible focus effect while navigating through the checkboxes using keyboard navigation.

**[Notes]:**
- The issue is not reproducible if keyboard navigation is used to go through the empty fields.
- Attached a screen recording of the issue.

![2020-09-21_17h35_02](https://user-images.githubusercontent.com/55738964/93782273-083d7b00-fc33-11ea-9b4f-2fe69d10291c.gif)

**Comment by Snuffleupagus** [comment]
Duplicate of #12223

**Comment by Martin-Robert** [comment]
Thank you for marking as duplicate, did not see it beforehand, sorry for that!
