### ISSUE TITLE
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

### ISSUE THREAD

**Issue by jianxiaofei** [mozilla/pdf.js#12408]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:85.0.4183.121
- Operating system and its version:
- PDF.js version:2.5.207
- Is a browser extension:

Steps to reproduce the problem:
1. what's wrong!

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by daviseford** [comment]
Try reverting to an earlier version. My builds broke this morning without warning. 

My error was: `TypeError: Cannot read property 'GlobalWorkerOptions' of undefined`

This fixed it for now.

```diff
-    "pdfjs-dist": "2.5.207",
+    "pdfjs-dist": "2.4.456",
```

**Comment by timvandermeij** [comment]
Unfortunately this is not actionable without a running example to reproduce the issue. It _looks_ like you didn't provide a correct path to the worker, or perhaps #12389 is the case.

**Comment by jianxiaofei** [comment]
Error: The API version "2.4.456" does not match the Worker version "2.3.200
