### ISSUE TITLE
PDF renders incorrectly using SVG

### ISSUE THREAD

**Issue by Roshankg** [mozilla/pdf.js#12404]
Attach (recommended) or Link to PDF file here:
[Helixmith+Selects_20200915153555661.pdf](https://github.com/mozilla/pdf.js/files/5264923/Helixmith%2BSelects_20200915153555661.pdf)

Configuration:
- Web browser and its version: **Google Chrome**
- Operating system and its version: **85.0.4183.102 (Official Build) (64-bit)**
- PDF.js version: 2.3.200
- Is a browser extension: no

Steps to reproduce the problem:
1. I am trying to render the pdf as SVG but it is not correctly rendered.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/18278384/93953599-6ff5e200-fd69-11ea-90c3-9b61817517ea.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/18278384/93953657-97e54580-fd69-11ea-902e-3e30e3caf65e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Not hosted yet

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.3.200

Please note that that version is no longer supported; you can find the latest releases at https://github.com/mozilla/pdf.js/releases

> I am trying to render the pdf as SVG but it is not correctly rendered.

Furthermore, as mentioned in the Wiki only the `canvas`-backend is officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by Roshankg** [comment]
Thanks for your prompt response. 

I have upgraded the pdfjs-dist to latest version ("pdfjs-dist": "2.5.207"). Of-course I know latest release is 2.6.347, but when i install that, it is returning below error. 

**Output:**
Still it is same. Pdf content is not rendering as svg. I can only see title.
![image](https://user-images.githubusercontent.com/18278384/94114249-b466a800-fe65-11ea-91d4-57c1e29ffc98.png)

**Expected output:**
![image](https://user-images.githubusercontent.com/18278384/94114320-d19b7680-fe65-11ea-98ac-14cc1a273ec3.png)

**Comment by Roshankg** [comment]
Jonas, Can i know if you have found some issue related to this case and pdf.

**Comment by Snuffleupagus** [comment]
> Can i know if you have found some issue related to this case and pdf.

As was *clearly* mentioned in https://github.com/mozilla/pdf.js/issues/12404#issuecomment-697199750, with a link to the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends), the SVG-backend is ***not*** officially supported!

The correct solution is to use the default `canvas`-backend.

**Comment by timvandermeij** [comment]
Indeed, the canvas back-end is the only officially supported back-end. This issue remains open to improve the SVG back-end, but as of now it's experimental only.

**Comment by chppatel** [comment]
Hi. Just wanted to see if SVG backend has had any updates on this.
