### ISSUE TITLE
PDF viewer do not highlight text when textLayerMode is set to TextLayerMode.DISABLE

### ISSUE THREAD

**Issue by ChetanGandhi** [mozilla/pdf.js#12400]
Hi,

I am using PDFJS-dist (npm package) into my web application to just render the PDF. I do not want user to download the file or select and copy text (due to privacy concern). I have also added the find bar to allow user to search for text. The find functionality works but the highlight do not when textLayerMode is set to TextLayerMode.DISABLE.

Configuration:
- Web browser and its version: Google Chrome 85.0.4183.102
- Operating system and its version: Windows 10 1909
- PDF.js version: 2.5.207
- Is a browser extension: No

Is text highlighting supported when textLayerMode is set to TextLayerMode.DISABLE ?

Thank you.

**Comment by timvandermeij** [comment]
If the text layer is selected, no highlighting can happen since it operates on the text layer.

> I do not want user to download the file or select and copy text (due to privacy concern)

Please be aware that simply removing the download button does not mean that the file cannot be downloaded. Even removing all download logic from the viewer won't achieve that since the PDF stream must be available to PDF.js and can therefore always be intercepted by advanced users.

**Comment by ChetanGandhi** [comment]
> If the text layer is disabled, no highlighting can happen since it operates on the text layer.

Thanks for confirming this :)

> > I do not want user to download the file or select and copy text (due to privacy concern)
> 
> Please be aware that simply removing the download button does not mean that the file cannot be downloaded. Even removing all download logic from the viewer won't achieve that since the PDF stream must be available to PDF.js and can therefore always be intercepted by advanced users.

In my web application I have the file data been streamed from backend and I pass this data to PDFJS for rendering.
Obviously anyone expert enough can grab the data from the network request.
