### ISSUE TITLE
Builds failing due ot canvas ( again )  v2.5.207 

### ISSUE THREAD

**Issue by EugenMayer** [mozilla/pdf.js#12413]
I'am building pdf.js myself. I'am using `node:12-buster` as a build environment

When running `npm ci` (or `npm install` ) i run into

```
2134 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2135 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2135 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2135 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
2135 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2136 verbose stack Error: canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
2136 verbose stack Exit status 1
2136 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2136 verbose stack     at EventEmitter.emit (events.js:315:20)
2136 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2136 verbose stack     at ChildProcess.emit (events.js:315:20)
2136 verbose stack     at maybeClose (internal/child_process.js:1021:16)
2136 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2137 verbose pkgid canvas@2.6.1
2138 verbose cwd /pdfjs.builder/pdf.js
2139 verbose Linux 5.8.6-1-MANJARO
2140 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2141 verbose node v12.18.4
2142 verbose npm  v6.14.6
2143 error code ELIFECYCLE
2144 error errno 1
2145 error canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
2145 error Exit status 1
2146 error Failed at the canvas@2.6.1 install script.
2146 error This is probably not a problem with npm. There is likely additional logging output above.
```

Looking at the issue queue this seems not the first time. Since i'am using node LTS (12.18.4) and checking the current travis logs https://travis-ci.org/github/mozilla/pdf.js ( which are using 12.18.4 ) i'am actually very suprised the travis builds do work. 

This smells like the reasons those builds work is the build cache - can anybody build ` v2.5.207 ` at all when not using a build cache? 

Thanks!

**Comment by EugenMayer** [comment]
Another interesting point is, that `npm install canvas@2.6.1` seems to work. So doing something like

```
npm install canvas@2.6.1
npm install
```

Will actuall work. Still i guess that is not we are supposed to do :)

**Comment by EugenMayer** [comment]
This is somewhat related to https://github.com/mozilla/pdf.js/issues/11275 (again)

**Comment by daviseford** [comment]
Try reverting to an earlier version. My builds broke this morning without warning. This fixed it for now.

```dif
-    "pdfjs-dist": "2.5.207",
+    "pdfjs-dist": "2.4.456",
```

**Comment by EugenMayer** [comment]
@daviseford 2.4 used cairo 2.6.0 .. pretty sure the reason you face the above is, that the cache you had for 2.6.0 is now no longer working for you, so you have to refetch 2.6.1 and then it fails. 

If you revert the above and try `npm ci` before you build, this would probably reflect if it really works. Sure it can be that 2.6.0 covers your current NAPI "better" .. but the LTS 12.18.4 NAPI is actually covered by canvas prebuilds https://github.com/node-gfx/node-canvas-prebuilt/releases

But i'am actually not sure. running this on my `node:12` container

```
node -e "console.log(process.versions)" | grep v8
  v8: '7.8.279.23-node.39',
```
Means 39 should be used, which is no (longer) build for canvac 2.6.1 but neither has been for 2.6.0 - so maybe that is the wrong indicator? ( `node.39` )

**Comment by arthur-feral** [comment]
Hey there,

I was using `pdfjs-dist@2.4.456` for a web project and after upgrading to `pdfjs-dist@2.6.347`, when I am building the project with webpack, my build fails with the following error. I am thinking it is related to your issue somewhat.

```
resolve 'canvas' in '/app/web/node_modules/pdfjs-dist/build'                
  Parsed request is a module                                                                                         
  using description file: /app/web/node_modules/pdfjs-dist/package.json (relative path: ./build)
    resolve as module   
      looking for modules in /app/web/src      
        using description file: /app/web/package.json (relative path: ./src)
          using description file: /app/web/package.json (relative path: ./src/canvas)
            no extension
              /app/web/src/canvas doesn't exist   
            .js 
              /app/web/src/canvas.js doesn't exist 
            .ts  
              /app/web/src/canvas.ts doesn't exist  
            .tsx        
              /app/web/src/canvas.tsx doesn't exist
            .json                                         
              /app/web/src/canvas.json doesn't exist
            as directory                                  
              /app/web/src/canvas doesn't exist

```

Thing is, this file is actually there:
![Screenshot 2020-09-24 at 16 14 39](https://user-images.githubusercontent.com/1699430/94157089-1aacf400-fe81-11ea-84dc-140c642420e9.png)
required there
![Screenshot 2020-09-24 at 16 15 24](https://user-images.githubusercontent.com/1699430/94157156-2e585a80-fe81-11ea-95f0-09792e817b49.png)

**Comment by EugenMayer** [comment]
> Hey there,
> 
> I was using `pdfjs-dist@2.4.456` for a web project and after upgrading to `pdfjs-dist@2.6.347`, when I am building the project with webpack, my build fails with the following error. I am thinking it is related to your issue somewhat.
> 
> ```
> resolve 'canvas' in '/app/web/node_modules/pdfjs-dist/build'                
>   Parsed request is a module                                                                                         
>   using description file: /app/web/node_modules/pdfjs-dist/package.json (relative path: ./build)
>     resolve as module   
>       looking for modules in /app/web/src      
>         using description file: /app/web/package.json (relative path: ./src)
>           using description file: /app/web/package.json (relative path: ./src/canvas)
>             no extension
>               /app/web/src/canvas doesn't exist   
>             .js 
>               /app/web/src/canvas.js doesn't exist 
>             .ts  
>               /app/web/src/canvas.ts doesn't exist  
>             .tsx        
>               /app/web/src/canvas.tsx doesn't exist
>             .json                                         
>               /app/web/src/canvas.json doesn't exist
>             as directory                                  
>               /app/web/src/canvas doesn't exist
> ```
> 
> Thing is, this file is actually there:
> ![Screenshot 2020-09-24 at 16 14 39](https://user-images.githubusercontent.com/1699430/94157089-1aacf400-fe81-11ea-84dc-140c642420e9.png)
> required there
> ![Screenshot 2020-09-24 at 16 15 24](https://user-images.githubusercontent.com/1699430/94157156-2e585a80-fe81-11ea-95f0-09792e817b49.png)

i think that is a very different issue @arthur-feral -  you should open up a nother ticket ( and run npm ci beforehand :) )

**Comment by Snuffleupagus** [comment]
Is this issue reproducible when testing against the `master` branch of the PDF.js library?

Please keep in mind that development *only* happens against `master`, and generally speaking it's *very* uncommon (in this project) that patches are back-ported to older versions. Especially when the version in question, i.e. `2.5.207`, is the currently stable release version.

**Comment by timvandermeij** [comment]
I have completely rebuilt `node_modules` locally and `canvas` installs just fine. The line `Error: canvas@2.6.1 install: node-pre-gyp install --fallback-to-build` indicates that the `canvas` dependency install script cannot find a binary distribution for your particular platform and falls back to building the library instead, which requires build tools to be present. This is not something we can fix and the issue should therefore be raised upstream at https://github.com/Automattic/node-canvas instead.

**Comment by EugenMayer** [comment]
@timvandermeij you are aware that i use docker, right? You can entirely reproduce this issue yourself and the only reason "it works for you" (which is would say is a fairly weak argument for all of us) is that you probably use a platform ( e.g. macos ) which out of a reason has the prebuild binaries of canvas matching

Please do me a favour and trigger your build in a clean, usual CI environment, e.g.

`node:12` or `node:10` - let as assume those 2 to be the "common ground" of environments

Run this from within your PDF

`docker run -v $(pwd):/src -w /src -it node:12 npm ci`

You should see the issue popping up right away.

If you want to inspect all that, use

`docker run -v $(pwd):/src -w /src -it node:12 bash`

and then
```
npm ci
```

Then inspect what you like.

**Comment by timvandermeij** [comment]
It's not the caching on Travis CI because, as you asked, I just started a build with caching disabled and it still works just fine; see https://travis-ci.org/github/mozilla/pdf.js/builds/732761853 (notice the configuration with `cache: false` if you click "View config" and no lines in the console about fetching the cache that we normally have).

Regardless of whether this worked or not, there is simply nothing we can change about this here since we only use this dependency and don't manage it. If upstream doesn't provide enough prebuilt binaries, that can only be addressed _there_, so this issue is not actionable for us.

**Comment by EugenMayer** [comment]
I see, well i just tested `docker run -v $(pwd):/src -w /src -it node:12 npm ci` myself today to verify and indeed it works - i assume there have been fixes upstream already?

Still `docker run -v $(pwd):/src -w /src -it node:12 npm ci` works on the master HEAD. 

When you use `v2.5.207` as the target commit it will fail.

So if you suggestion is anything then right, this could never been happened, since pdf.js could by no means have fixed this issue in this repo, right?. 

But between `v2.5.207` and `master head` it has been fixed inside pdf.js. 

So being so reluctant that this "cannot be an issue of pdf.js" seems to be the wrong way to go about it, this assumption seems to be proven wrong by this very own repo.

Though your statement that the issue does not exist right now is right - beside that your own current stable release cannot be rebuild by yourself anymore - and that is what i would expect other people to base on (assumingly)
