### ISSUE TITLE
How do I keep hyperlinks when converting pdf to canvas?

### ISSUE THREAD

**Issue by Soniya-Prasad** [mozilla/pdf.js#12410]
I'm using pdf.min.js(version - 2.3.200) to convert large pdf(size -178MB ) pages to canvas. There are lots of internal hyperlinks and external links in each PDF pages. After conversion, in canvas, the same hyperlinked text are highlighted but all the links have been removed.
How do I keep hyperlinks when converting pdf to canvas?

Any suggestions would be greatly appreciated.

**Comment by timvandermeij** [comment]
Canvas is an image format, so there is no concept of hyperlinks there. Hyperlinks in the document are possible because we overlay a layer over the canvas itself.
