### ISSUE TITLE
Rendering problem on Leica PDF repair form

### ISSUE THREAD

**Issue by padenot** [mozilla/pdf.js#12412]
Attach (recommended) or Link to PDF file here:
[FV-G-005+Repair+Form+EN(1).pdf](https://github.com/mozilla/pdf.js/files/5275768/FV-G-005%2BRepair%2BForm%2BEN.1.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 83.0a1 20200923212316
- Operating system and its version: macOS Mojave
- PDF.js version: What is in this Firefox
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open the PDF
2. Look at the personal details form, where the State should be put in

What is the expected behavior?
![Screenshot 2020-09-24 at 13 59 54](https://user-images.githubusercontent.com/270485/94142443-93ef1b80-fe6e-11ea-8670-7cc03c6063e0.png)

What went wrong? (add screenshot)
![Screenshot 2020-09-24 at 14 01 53](https://user-images.githubusercontent.com/270485/94142420-8cc80d80-fe6e-11ea-9238-88239e9ebcef.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): This is when opening the PDF in Firefox.

**Comment by padenot** [comment]
The rendering is correct on (at least) Linux Desktop (same browser version).

**Comment by calixteman** [comment]
WFM on linux too.
The code to display `State` is:
`Tm /TT7 1 Tf [ (St) -155 (a) -40 (t) -155 (e) ] TJ 0 Tc ET BT 8.035176 0 0 8.04 33.11987 572.3597`
The base font is `/YGULQN+Helvetica` and the encoding `/MacRomanEncoding`.
So probably an encoding issue, @brendandahl wdyt ?

**Comment by brendandahl** [comment]
Seems fine on MacOS Catalina w/ Nightly 83.0a1 (2020-10-02). Maybe a mojave only bug?

**Comment by padenot** [comment]
Looks good on Catalina indeed with a current Nightly indeed.

**Comment by Snuffleupagus** [comment]
Given https://github.com/mozilla/pdf.js/issues/12412#issuecomment-702896444 and https://github.com/mozilla/pdf.js/issues/12412#issuecomment-703490543, this sounds possibly like an OS-specific bug.

Is this bug still reproducible, in up-to-date versions of Firefox?

**Comment by padenot** [comment]
This now looks identical on a recent Firefox and any other PDF viewer I have access too on the same machine, thanks!
