### ISSUE TITLE
Mac only: "Command F" vs "Command Shift F"

### ISSUE THREAD

**Issue by zsiegel92** [mozilla/pdf.js#12421]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 85.0.4183.121 (Official Build) (64-bit)
- Operating system and its version: Mac 10.15.4
- PDF.js version: 2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open a PDf
2. Press "Command + Shift + F"

What is the expected behavior? (add screenshot)

Chrome typically uses this shortcut for "Always Show Toolbar in Full Screen".

What went wrong? (add screenshot)

In PDF.js, this shortcut is captured by the extension as "Find". The shortcut "Command + F" is also captured and serves this purpose, so I don't believe "Command + Shift + F" should ALSO be captured for "Find". There is no way to configure the keyboard shortcuts captured by this extension in its options.

I prefer PDF.js to the built-in Chrome PDF viewer (mostly for its ability to open PDF documents to the previous location), but this makes it hard to use.

**Comment by zsiegel92** [comment]
I am hoping this is not a very difficult issue to resolve. Please let me know whether this will be addressed. Thank you!

**Comment by timvandermeij** [comment]
Fixed by the PR above.
