### ISSUE TITLE
Mobile viewer examples fails...

### ISSUE THREAD

**Issue by markhowells** [mozilla/pdf.js#12424]
Using multiple browsers, I cant get the mobile-viewer example to work.

I'm wrapping it in an iframe in my HTML and it fails like this...
`DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/@zxing/library/esm5/core/RGBLuminanceSource.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/popper.js/dist/esm/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack:///node_modules/bootstrap/dist/js/bootstrap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
pdf_history.js:71 Uncaught TypeError: Cannot read property '_on' of undefined
    at new PDFHistory (pdf_history.js:71)
    at Object.pdfViewInitUI [as initUI] (viewer.js:322)
    at HTMLDocument.<anonymous> (viewer.js:376)
PDFHistory @ pdf_history.js:71
pdfViewInitUI @ viewer.js:322
(anonymous) @ viewer.js:376
base_viewer.js:184 Uncaught (in promise) TypeError: Cannot read property 'dispatch' of undefined
    at base_viewer.js:184
(anonymous) @ base_viewer.js:184
Promise.then (async)
BaseViewer @ base_viewer.js:183
PDFViewer @ pdf_viewer.js:19
pdfViewInitUI @ viewer.js:312
(anonymous) @ viewer.js:376
base_viewer.js:455 Uncaught (in promise) TypeError: Cannot read property '_on' of undefined
    at PDFViewer.setDocument (base_viewer.js:455)
    at viewer.js:84
setDocument @ base_viewer.js:455
(anonymous) @ viewer.js:84
Promise.then (async)
open @ viewer.js:81
(anonymous) @ viewer.js:390
Promise.then (async)
(anonymous) @ viewer.js:389`

(I've removed a lot more sourcemap errors)

The first significant error is 

`pdf_history.js:71 Uncaught TypeError: Cannot read property '_on' of undefined
    at new PDFHistory (pdf_history.js:71)
    at Object.pdfViewInitUI [as initUI] (viewer.js:322)
    at HTMLDocument.<anonymous> (viewer.js:376)
PDFHistory @ pdf_history.js:71
pdfViewInitUI @ viewer.js:322
(anonymous) @ viewer.js:376`

Single stepping through the js I can see that my PDF loads (and the pagecount is correct). The error above is because the eventBus var is undefined. The other errors all have the same problem.

This used to work on versions prior to 2.3.200 but failed on 2.3.200 and 2.5.207

I'm at a loss to know what's wrong and any pointers would be appreciated.

**Comment by timvandermeij** [comment]
It's not possible to know for sure since a running example is missing, but from the snippets I can only guess that you're not _explicitly_ providing an event bus instance during initialization. This was deprecated in https://github.com/mozilla/pdf.js/commit/9a437a158f754df875819e55ab689d2bb33598f9 and removed later, so there is no fallback to a global event bus anymore.
