### ISSUE TITLE
Mozilla's pdf.js has Chromium as a dependency

### ISSUE THREAD

**Issue by sixtyfive** [mozilla/pdf.js#12427]
See title.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md

**Comment by timvandermeij** [comment]
Closing since we don't have such a dependency and it's not clear where this claim comes from.

**Comment by sixtyfive** [comment]
As far as I can tell it's an indirect one coming in via one of the npm dependencies.
