### ISSUE TITLE
Slow rendering with lots of math symbols

### ISSUE THREAD

**Issue by jonashaag** [mozilla/pdf.js#12435]
Attach (recommended) or Link to PDF file here:

[mathmode.pdf](https://github.com/mozilla/pdf.js/files/5316996/mathmode.pdf)

Configuration:
- Web browser and its version: Firefox 81, Chrome 85
- Operating system and its version: macOS Catalina
- PDF.js version: The version shipped with Firefox, demo page from today for Chrome
- Is a browser extension: ?

Steps to reproduce the problem:
1. Open https://home.uni-leipzig.de/assmann/teaching/SS15/mathmode.pdf (also attached)

What is the expected behavior?

Renders reasonably quickly

What went wrong?

Rendering time Firefox (integrated PDF.js or PDF.js demo page): ~10s
Rendering time Chrome (PDF.js demo page): ~2s
Rendering time Chrome (native PDF viewer): ~1s

So I guess there are two problems here; one is that PDF.js is slower than the Chrome native PDF viewer, and the other is that Firefox is MUCH slower than Chrome at rendering the file through PDF.js. Shall I report the Firefox performance issue at Firefox Bugzilla?

**Comment by calixteman** [comment]
I just tried with Firefox nightly (83) and Firefox release (81.0.1) under linux (debian) and the rendering is almost instantaneous for both.

**Comment by Snuffleupagus** [comment]
> I just tried with Firefox nightly (83) and Firefox release (81.0.1) under linux (debian) and the rendering is almost instantaneous for both.

I get similar behaviour in Firefox Nightly (83) on Windows, with rendering finishing in well under 500 milliseconds.

**Comment by jonashaag** [comment]
Aha! When I disable WebRender, it's still much slower than Chrome + PDF.js but much faster than with WebRender. That's unfortunate, because I've had performance problems without WebRender elsewhere...

**Comment by timvandermeij** [comment]
This PDF renders within a second for me too on Arch Linux with Firefox 81.0. Given that this may be related to WebRender, it would be better to file this issue upstream in Bugzilla (https://bugzilla.mozilla.org/) so it reaches the WebRender engineers since it doesn't look like something we can address on the PDF.js side. Thanks.
