### ISSUE TITLE
Rendering the page does not show all the page's content. PDF attached.

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#12433]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/5312411/test.pdf)

Configuration:
- Web browser and its version: Chrome Version 85.0.4183.121
- Operating system and its version: Windows 10
- PDF.js version: "2.5.207"
- Is a browser extension: no

Steps to reproduce the problem:

- Go to https://chitgoks.com/test/web/viewer.html?file=../test.pdf
- Open dev console in browser
- Click the minus button (zoom out) button beside the zoom dropdown
- copy the base 64 string returned, open in new tab to see image.
- Notice the bottom part is cut off.

This is the code I used, like in the example. But the bottom part gets cut off.  The PDF.JS viewer does display the pdf right. But using the code below does not. Thoughts? 

```
PDFViewerApplication.pdfDocument.getPage(1).then(function(page) {
        var scale = 1;
        var viewport = page.getViewport({ scale : scale });
        var canvas = document.createElement('canvas');
        canvas.height = viewport.height;
        canvas.width = viewport.width;
        var ctx = canvas.getContext('2d');
        var renderContext = {
            canvasContext: ctx,
            viewport: viewport
        };

       page.render(renderContext).promise.then(function() {
            console.log(canvas.toDataURL());
        });
    });
```

What is the expected behavior? (add screenshot)
Calling canvas.toDataURL() should show all the content in page 1 but at the bottom it gets cut off.

What went wrong? (add screenshot)
![screenshot](https://user-images.githubusercontent.com/3955470/94817825-03957580-0430-11eb-9e55-7a63e4a35a32.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Please see steps above.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by chitgoks** [comment]
will get back with link to site. thank you

**Comment by chitgoks** [comment]
@Snuffleupagus hi, please see updated steps.

**Comment by Snuffleupagus** [comment]
> Go to https://chitgoks.com/test/web/viewer.html?file=../test.pdf

This isn't the sort of example that we ask for, given it's not enough to simply open that URL since lots of *manual* steps are required here; hence please notice the following line:

> **please prepare a short well-documented example that demonstrates the problem and make it accessible online** 

(Personally, I don't have time to help under these circumstances; I simply try to ensure that issues contain enough information to be valid.)

**Comment by chitgoks** [comment]
ok thank you still for checking the comments

**Comment by chitgoks** [comment]
ill close this issue. i tried it in firefox and it works ok once i copy the output of canvas.toDataURL() in dev console using browser context menu item "Copy Object"

This looks like a browser issue. Chrome and Edge has this problem.
