### ISSUE TITLE
Pdf.js v2.5.207 and v2.4.456 doesn't not render on IOS Safari 14.0.1 (Renders white or with errors).

### ISSUE THREAD

**Issue by Brendon-F** [mozilla/pdf.js#12431]
Pdf.js v2.5.207 stable prebuilt (ES5-compatible) version does not render pdf's on iOS safari 14.0.1. The pages are either white or render the following error.

Have now tested 2.4.456-es5-dist with same issues on iOS safari 14.0.1.

Error message:
<img width="693" alt="Screenshot 2020-10-01 at 13 14 38" src="https://user-images.githubusercontent.com/72203963/94807852-22701980-03e8-11eb-81ed-f908fd6c46b1.png">

White page:
<img width="699" alt="Screenshot 2020-10-01 at 17 17 18" src="https://user-images.githubusercontent.com/72203963/94835751-febdcb00-0409-11eb-8261-8213a379f124.png">

The link to a test file can be found here for version 2.4.456:

https://www.designoriginal.co.uk/test/web/viewer.html?file=../pdfs/PRISMA-Core-Datasheet.pdf
https://www.designoriginal.co.uk/test/web/viewer.html?file=../pdfs/VSPP-Datasheet.pdf

To replicate the issue use an apple device with the latest iOS version 14.0.1

Brendon Fear

**Comment by astehlik** [comment]
I'm not sure if this is the cause but some Safari or Samsung Internet versions seems to have a problem with the [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) `??` and [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) `?.`

It seems that those are not transpiled by babel currently, see for example:

https://github.com/mozilla/pdf.js/blob/gh-pages/web/viewer.js#L1142

**Comment by Snuffleupagus** [comment]
> The link to a test file can be found here for version 2.4.456:
> 
> https://www.designoriginal.co.uk/test/web/viewer.html?file=../pdfs/PRISMA-Core-Datasheet.pdf
> https://www.designoriginal.co.uk/test/web/viewer.html?file=../pdfs/VSPP-Datasheet.pdf

Unfortunately none of those links seem to work; however the screen-shots does seem to indicate a bug in the platform/browser *itself*, rather than a bug in the PDF.js library, since otherwise you'd kind of expect it to be consistently broken everywhere. As such there's probably not much we can do here, unfortunately. /cc @timvandermeij
