### ISSUE TITLE
Viewer Stream Truncating Signed URL Query Parameters of PDF file - fetch_stream.js line 59

### ISSUE THREAD

**Issue by drc04** [mozilla/pdf.js#12447]
Accessing a PDF with a time limited signed URL in chrome hosted on GCS CDN. Reader returns error:

PDF.js v2.3.200 (build: 4ae3f9fc)
Message: Unexpected server response (403) while retrieving PDF "https://cdn.example.com/media/20201004062644/test-2.pdf?GoogleAccessId".

CORS is configured and works with unsigned header for PDF files.

In the above message, there should be an '=' and a long string after 'GoogleAccessID' for the correct url. When examining the variable in DevTools, the message url is exactly the url generated on line 59 of fetch_stream.js as the variable. It appears the rest of the url is somehow being truncated at the '='. Looking for help and/or insight into a solution.

Thank you,

**Comment by Snuffleupagus** [comment]
> Accessing a PDF with a time limited signed URL in chrome hosted on GCS CDN.

Without access to a runnable test-case, this issue (or anyone else really) unfortunately isn't actionable/valid.

When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

> PDF.js v2.3.200 (build: [4ae3f9f](https://github.com/mozilla/pdf.js/commit/4ae3f9fcf6735748599b1f436a9d5b94bdf2d393))

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

> In the above message, there should be an '=' and a long string after 'GoogleAccessID' for the correct url.

You probably need to use `encodeURIComponent()`, as mentioned in the FAQ: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

**Comment by drc04** [comment]
Thank you for the tip on encodeURIComponent().
