### ISSUE TITLE
Back action navigates to wrong page after thumbnail is clicked

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#12440]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 87.0.4280.6 (Official Build) canary (64-bit)
- Operating system and its version: Windows 10 Home 10.0.0.18363
- PDF.js version: 2.6.12
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open https://www.ijcai.org/Proceedings/2019/0241.pdf
2. Click on Sidebar icon
3. Click on e.g. last page's thumbnail
4. Click on Back arrow

What is the expected behavior? (add screenshot)
The browser should navigate to 1st page of the document

What went wrong? (add screenshot)
The browser navigates to the page from which the document was opened (e.g., the Home page)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Note: Intrestingly enough, clicking on the Outline works correctly.

**Comment by ashwinpilgaonkar** [comment]
Hi @timvandermeij, can I work on this?

**Comment by Snuffleupagus** [comment]
Assuming that we actually want to support this use-case, when the thumbnail view is used, I'm afraid that it's not really a good beginner bug.

**Comment by Snuffleupagus** [comment]
Assuming that we actually want to support this use-case, when the thumbnail view is used, I'm afraid that it's not really a good beginner bug (based on throwing together a quick patch for this issue).

**Comment by ashwinpilgaonkar** [comment]
> Assuming that we actually want to support this use-case, when the thumbnail view is used, I'm afraid that it's not really a good beginner bug (based on throwing together a quick patch for this issue).

Oh, okay. Is there any other beginner friendly issue that I could work on?
