### ISSUE TITLE
"Invalid PDF structure" for pdf files

### ISSUE THREAD

**Issue by neerajkulk** [mozilla/pdf.js#12443]
Configuration:
- pdfjs-dist: version 2.5.207 (installed from npm)

I'm using pdf.js server-side on node.js and I'm trying to read in a pdf from a url.

Here's a small reproducible example of the bug
```
var pdfjsLib = require("pdfjs-dist/es5/build/pdf.js");
var url = 'https://arxiv.org/pdf/2009.14740.pdf';

var loadingTask = pdfjsLib.getDocument(url);
loadingTask.promise.then(function (pdf) {
    console.log(pdf);
}).catch(function (error) {
    console.log(error)
})
```

Running the code above produces the following error:

```
Warning: getHexString - ignoring invalid character: 33
Warning: getHexString - ignoring invalid character: 79
Warning: getHexString - ignoring invalid character: 84
Warning: getHexString - ignoring invalid character: 89
Warning: getHexString - ignoring invalid character: 80
Warning: getHexString - ignoring additional invalid characters.
Warning: getHexString - ignoring invalid character: 104
Warning: getHexString - ignoring invalid character: 116
Warning: getHexString - ignoring invalid character: 109
Warning: getHexString - ignoring invalid character: 108
Warning: getHexString - ignoring invalid character: 104
Warning: getHexString - ignoring invalid character: 116
Warning: getHexString - ignoring invalid character: 105
Warning: getHexString - ignoring invalid character: 116
Warning: getHexString - ignoring invalid character: 108
Warning: getHexString - ignoring invalid character: 33
Warning: getHexString - ignoring invalid character: 79
Warning: getHexString - ignoring invalid character: 84
Warning: getHexString - ignoring invalid character: 89
Warning: getHexString - ignoring invalid character: 80
Warning: getHexString - ignoring additional invalid characters.
Warning: getHexString - ignoring invalid character: 104
Warning: getHexString - ignoring invalid character: 116
Warning: getHexString - ignoring invalid character: 109
Warning: getHexString - ignoring invalid character: 108
Warning: getHexString - ignoring invalid character: 104
Warning: Indexing all PDF objects
Error
    at BaseExceptionClosure (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:2155:29)
    at Object.<anonymous> (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:2158:2)
    at __w_pdfjs_require__ (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:52:30)
    at Object.<anonymous> (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:389:13)
    at __w_pdfjs_require__ (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:52:30)
    at Object.<anonymous> (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:322:22)
    at __w_pdfjs_require__ (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:52:30)
    at /Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:116:18
    at /Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:119:10
    at webpackUniversalModuleDefinition (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:25:20)
    at Object.<anonymous> (/Users/kulkarniad/side_proj/arxiv_chats/app/node_modules/pdfjs-dist/es5/build/pdf.js:32:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  message: 'Invalid PDF structure.',
  name: 'InvalidPDFException'
}
```

Note that for other url's the code run's just fine. In particular the default pdf provided in the pdf.js example seems to run fine

```
var url = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf'; // this url works
```

I've tried multiple different pdf's and many of them seem to have an "Invalid PDF structure". What is the problem here? Thanks!

**Comment by Snuffleupagus** [comment]
> Here's a small reproducible example of the bug

Code snippets are of limited use, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Note that for other url's the code run's just fine.

That would suggest that it's a *particular* server which returns incorrect (i.e. non-PDF) data, which thus isn't something that can we can fix here. Hence, given the information provided, this unfortunately seems unlikely to be an actionable/valid issue for the PDF.js library.

**Comment by GrumpyDevBear** [comment]
I had the same errors. My pdf was generated via PHP. I checked the console for the pdf response and there were PHP error lines at the top of the generated pdf code like notice undefined variable. So those errors triggered the getHex errors! So if a pdf document gives thes kind of errors then check the sourcecode of the pdf for example by opening it in notepad.

**Comment by huang633** [comment]
May I ask how you can solve it?

**Comment by huang633** [comment]
I encountered this error in the PDF 1.5 document, which is not displayed in the PDF 1.4 document.

**Comment by GrumpyDevBear** [comment]
the answer was in my answer.
    i fixes the php errors
    
    
    Op 19-04-2024 om 04:49 schreef
      huang633:
    
    
      
      May I ask how you can solve it?
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/mozilla/pdf.js/issues/12443#issuecomment-2065656107",
"url": "https://github.com/mozilla/pdf.js/issues/12443#issuecomment-2065656107",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
      
      
       
           Hartelijke groeten,
             
           Arno Leeuwenburgh
            
              
            
            T. 0113 - 700 260 / 0118 - 700 260 
            E. ***@***.***
            
            Bezoekadres: 
            Energieweg 15, Vlissingen
          
          
            
                 
                    The information transmitted is intended only for use
                    by the addressee and may contain confidential and/or
                    privileged material. 
                    Any review, re-transmission, dissemination or other
                    use of it, or the taking of any action in reliance
                    upon this information by persons 
                    and/or entities other than the intended recipient is
                    prohibited. If you received this in error, please
                    inform the sender and/or 
                    addressee immediately and delete the material.
            
          
        
      
    
  

--------------IwNFD6jAc0XuWzOHQIH9XTRF
Content-Type: image/png; name="digiteam.png"
Content-Disposition: inline; filename="digiteam.png"
Content-Id: 
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAAAGMAAAAgCAYAAAAG98ZXAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAO
xAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAABTPSURBVGhD
zVoLlBTVmf7vrarunp7uYQZ5P0REEJgHjwF5ZTVuEoK64YDtOKusjscHGzfRZNVk98RzZHETE2PW
NdlkNQaNJEvcOUMP7BjjI+5RFMRVUV7DQ+U1vBEZYGaY6a6qe/f7b3fV9KiB8cQTuOc0Q9W9dR//
4/u//6+yFy9eTOdyq0ynK0hZlynhXSpIVGqiIVrrKAmRsYj2ahIbtJavKumv2ppKbT+Xz3Kmvdln
GnA2+ksXrbWHVx2og/AX4ndJEXbpk02uUuRrTVrgLlHMEqKPI2WFRWJBu080Ib3iVUXqsU2p1NNn
Y99/7prnnDLGpdOXRifIH0eFNU1B8F1QQJsPSX+swUOI+918n4SColJcSmRdOrGx8TYo7W4o5d0/
V0B/yefPKWWUN6TviljyQUcIuwNCZoH3trFi+Bl4DBVb9uUZUqvL0+k7mlOpJ3s7x9ked84oY3xD
+qGkY9/TCYF2QLDKdcnrOBXKxylJkrAsctvaSHveaeXWhd6olHEo9YlRjz8+cMfChT8824Luzfq9
VkZTfdNoZbuXSqWAGdJrPdW+sq6urp0XaXqkqUgNzVwtSUaktCSQ/fW5qdTW3myAx8Aj7iuBItiy
OSawIooGDqSBM2bkphCSDr32KnUePkxDv/IVKurfjzTg63SNvSpi2ZTds/sBWvLkyR233vyL3u7n
bI3rtTJ86S6MOJF7WAiu5x0uKytrDDbtDnYrHdv5LwHcNi1Dc/Fvr5RR3tAwr8iyFweK4Mfd9nYa
dd3f0uT77jPTaej/95ddTtJxaOoP/pVi/fr3Wl5bH36YIi+v+ili0QawrdW9fvAsDOy1MkjoCX53
IH1t7ty5IYZYkqZJKUnlFNVlU+Tt3pxlZFNTPyGs/2QrZo8IG5Tab/Lk8LK1uZnadu6kATNnfkIR
8CNWV86BCGT3Y+3gW29TLBa1skr/cmZT09TXC/bdmz3+Jcf0ShlLly4tKSlOlIPfg96DVmr1VuEm
taTBUMSefP+GdVvWHZprnOP0LZ71vtfHtgafKIgB7HmRZJLs4mLq2H8ACCXo8JrXyc9myY7HAVev
GRjTMAwrGoWCppOwbShCUMe+fdS6ebPxIJIWYk4HlLiLPFz3i0TGH82438GOztnEqlfKSCQSY3FY
Trby0nXeKRTz/FTqe7jmHy1atEgikTwjEbqmvn7oLsu+Ed6WiYCPukQ22zgHaRb26tv/AQYP5cPj
JIQdHzyYjr79Nr2yGkiD+157B/WfNpVmr1xpFMF+8d5TT9HGnzxM0b5l5ppRsySRIMe2M57n74xL
GnsmAzmb/Z9QRv3S+qHRhH0rTGsaDnNYuNlFkMYYaedgCL8TlnKag03Da4r7xOOX8TWgyqquHs9e
c6jwUBgzpE+8z3wh9RDAyr4TAwb8er9tD0fSlvZ83emQOnq5sKYXSXHVKXhAfMAA6jP2YlJ+Lkgf
W7+evM5OoygH3sFNYVy/KVPMvQCmTmzfTtGyUuNVmJuiHG40LX9O0AfvkurfSTSMlje+CC0dABF5
ad3mjcv+lOE0pdPVWP1KHHkC0KAEi2QBx9tdV69M1aZeKzwfG2BVRdWXca/YIsuWSr45t3bunpUN
DVdAKtUEe0IV4e15NfP+wM81LV3aj+KJOcoSY6Qv20llXphbW7uhhzLS6fT0aMJZblnWUPYC/KWs
UhWS6P0AovB3WyEMJeLxWZbtPGtcgT3HtWcVKgOHuqxPsuR3lhRDkDrD0i1KHvmwei20oqS8SVma
On16fo4gzYmbe/IkjVh4G1V8+9vmvJnjrfT8FVcZWGIvMebOdg+G1beiIi8TYcad3LXbQBfHL6jM
PUD6Z/drPSRG4lsxUF08bXzIPG/ZdZOqqnivtxcKdu3aRfbh/RMexgLfwPkl6zpABCjlKttRd0HI
fzevpmZZ8FxVVdVIqekFlhc318vctzLdOEvazleD9TicrWhI/0CQWkPJ5BLMPMRieTm44zuLIftr
Q2XU19eXRWz7aRxkKAdqjg1ZWB+up8AbJrBX8GIoRqwvtCaL5JScHli66sDJjvbNwSabmpr6wzL/
W0oxyENcMM/jhtD6Fuyt1VbKUVinv6BjjtbTM1iDIam0vDyUT+umTdR15IiJF0HjuGInE1Q6rht1
ODZ0ffihiRfFUFS7Usv+RdPF/Wzrb9hIOH9BpDkExQxCRMkpVdPXYSw/K6Thh/dXft927Dt4v3kk
QPUlZwGBgfpCfhOXoTIspSoheDMeYzwp5L0wrChfB8+ZKQR9B1ZwL8OqIUNc2sEAyCUmPe9HoTKi
0r7FsuwLeBN4MKu1+oYStA5q+znQZ2YwMRbpwZS00FN4Ql4Mhr8JucfJQGgq495iObZRBJ/FV/4P
MU8LNrsYSh7Ic/JCo4Q4gQx6GI+LlJVR6cVjQsEf27g5F7wBPeG8iCnFQ4dS8oILupW2ZSv5gLJo
DOJW/u5HNX1YYsmbICEwbToEQHtqJoTQpNWA/VLeAKt0mBxg3SGYxNDwpvr6i8h27srLgGFyCSD5
567tJuFVj2HPORKjKVboTbrAIDHGhsH9hlzrP0hmBoNILIVs+ucVGUHsStvK/r4n3TFAi19DRXE2
UJIia5TBmDepsuo6tji2Xt9XDfOvSS3hvpXp9DJMNpOFDW0C5igM3suWLYvGo0WVvBBDDCZeF2wS
c1oTK6uuDTwKjy6fn7r6Xu5vXN44EvP9E8/pan2kQgOwhCz2MhkqGzWK4kNYPrl2bEuzgbbCpjCu
5CLILc4KMqZAxzdvMn+j7BXaf30X0QwO4y7WGKD8Z24lcVXMcSozrvvIL7Q+njACggyIEEpyTVlO
XSQScQxFd72Dg4YNuX3GjBnGkhqXL2+G8nIuK8Tuwv1giWq+ztP7dZDdLfn+9Ssb0u9I2/oqywjG
+H5ntuu6BQtS4Cu0fsXy9AN4BrYIyXn0R6OMqvFVF2FflVzfYaEq7TeFiykq5R0by9f6YGt7+3tB
XzKZHOVnvRG8EOwFFmmFlLe6qmqMr8koyniolr/rPoCCE0kzJybdPYKoL8cAZlF94BXs8ty8rk46
+d77iAPgWwVNwcXLKgIow76QFB5H8JaRCKZT1KzpKIxmDq+d0brzC1rswLlmeZ777nbSGVvIUp4O
/e0UcQ6EU2v/DS/rfdcoRusNgSIAZXOwvyuMYSEeCaHDcy5d2pRMFutyAeuGRTE6hMkwjDUSj8aG
BfGWlFixYMECVgQBwtni+gZ9oEZrjTJQwJggLcdYBKzfdVQ0rHYC9SabwMeWn4MhUwIxG+50J1gR
yzznKa8rJsXGsI/oEngZwgLPqU5llRN6DY4zge2Zf3FBe4q1GO5xNILwyioqQ9m079lDpw4cMELu
FhgOjbhQVhBXeEx7y16yI1Ci1ie2Y7OIi33ZuIAn9guSxq0mvQrGkTkpxBdwD2UrYwh729ra9gdz
Iyg/i//zzzQo4a99LW7Gf6/DcGniorFwCqG6LOGOxpihbI6MNr5SYV8sFhuJ2xcZAsAGKfSbwdxu
xq2wLVlm5vSxMymbjTK0sEwQzlv/zjavbTdfGxiKxKoCGILR9cgvyNLhcwLWVzZkSEu30ITpY09D
dr19y5Z1OPRcAs1NIIGsYpxkBcBsPoSaZ/K7Cht4XzZ+XDjF8a3bTWEwUlraPS28IorrwrhyAt6T
OXaM4iUlTA5adpAqc4ShQezUjiusuo/Yd2G5kKipaxlIIWoOLLVb24DmhobrgfV3wBumg9SAHSH0
5xNeCLvNOeWEJAVTTbQgVWN0ym/zTqmQ9iOwV8HIowqCQ/zJIgYzlpqG3U3OoZCpIewf0N7eklMG
6Wo20xxp0BuCDcZiyQtJuyON9lhZ9LHMW8hJgRLxN3RrM6emSaF75hiYoRZIIEdjrcFsSWBPXeVC
ZsFBBruAKK45JUddGMqltXlzSCuDmz7GlYwZTUWDBpud866ObW42EIcXTaDi/p5WLQYH3IvZWhfj
mhnJKEJ2ESeS+LmeH3or94NRDo/a9uOAyTmBoNxsthF7TYDjzjbSgWGt27nuYEGFYWpgdFqL7Vt2
bjkYHkCI6hyJMkLf2dXVtTvogzCmGMTBPgCzzX9VV9dlP9LUVATMHsfCAXzAsrrZkuW5EyVKn3n4
6sJ/QovAxvuiq5z7jJXpbtdlSguWNd54pymf6O5DK5rElsTWCYq472Kt4yj02j6CcmLkCIr1Pa9b
GWBIprRR0HhcnzEXGwocJHtcu+Jrtvojig75QnyRrYEVkdB66SwwK8ikOI7krVPoo2t872VPK9uJ
OmuDqXGeoTHb+SOEji3Ba33/MCl597ya1LLG5emXwiKoph7UHiKbGBpdri8sJ8MXqwOmCSlshJFn
eb0c8YmFzwmVIz72ha57AczGlDq4WOfLbkakbKrujhdiR5vn7Qk2X2QXjUWkGMDXrBCn4DkQ+vEI
ZmVsuHBrDnphDEIWayyJAxA44J6BQgxiobFll40bH4o90/oRte/eZZK4Hg177BvGC0HeqQ46+QEH
+Siv5b9PdAq2NpTt8RRY0/WCDswQ4lvtOGBcij8gJu7oX1PzPz0nNeX2H7Mi8sXQfZhj9tyaeVtB
d89DglgdGB2KkWHwhgIH4blxpmxj2GQ3cnA9L1lcDKKYg0fEizCWJGOxC3H7/CCZBGSZPlt5NBVB
OEhYWp2IE5a+obHpAZPC2BC+cgrITAoSHWDisUyHvy04oKvcyREbczJWaiRaJcmwD5ubAq/BO22i
MhIHEZorkWuYw3QzJKKTOziJO0qyQBmGqyOulBbElfY9LXTq4CGkBxHG4aM7QNuQQBTlIXf3MIWw
FLHj0nXX3eqrZmnZNyQbV3zT89X/XV2TupH3DE8GOFAqn+xiGfXdIBFUMjpZSl1qjBVoB9taH5wT
kFaOuNIn6LMKiA/X84A0AxlxTB5B3fEWrgPClCM+QIguIR1DfGxtiasCN8PfU2AXR80G65vGC1tw
9m1gCPLrga8AtUt4HGMrRLm1tq72SLBJQEK5WZ6tRaljs2fPPsaX6fo0IEoaQsD8rgLUEkHtfGA3
OYkklaIeFbTjW7Ygiesywg8av+GL9e9PJchFwnHbtpmiYQQ1KZys7TgCNtelzPKguOcJkeT4sY/E
KhjB9SVSjuHzeDr7TDAH8hYwPxuB1lQRfMv3wvceANNaO08GINaDTldH4RcokwP4wpkOUBGFtB9B
FsYqcXyTlR/HnGFgxw2DDvws9LSz/5D+BnEYeCGTHK0EtAwEHUuhTrIJedYTqJ9Ec9bAMKhCJpVL
6CoLME/0YFlwyUE8uXFDKc8HO/myL+VHmPMpbCBiMBkbRJ6dAYSVuV1dlDx/BCVGsIHm2jGUwqHp
8Jr/w/GiZORIVGX78ux8HFMyzxUV8sfjdCi/dkRQ5bNKPzHBzW5+lMTYBBTB58HPtz2v4N24HM2G
k2dZtq/tOyGDR3HwKyGDmwKDhDtvnltXdyLYFAJ2KFQ83Yx3PGEf0qawj4M+CoFh8RSSNi9r8tAW
Eh8bwXUHIjqCLSuEbBS8njasATkXbzyfVbaiYLgl2ET1+OrhqPSMDgOXKAjQRguUzTMPXjChhXwB
n9NgahxXKS4ICoTlj4Biv+oUKoUawTBmSHZRviLre3Ri+3s98ws2B8SV0vFBXMkp6vjWbSZJNOZC
NOhCfEyyFxkYrExEhBj4ktB3PkfieLEQwzjA2/wq1sv+dF5tbXgemJu0RK4yxIIHxt+DsXegABoF
EeuCLHIlAK3XBzJYtnZtNE56QjdjlIXGKlF9mBwijqAwZuaJj5F3jvZTGINQ7nUeROT4ms1FPB7A
vNp1X8KiWcdxrsxvcGdtbTcMuTJzSdSOFplEh2HM6V7MaFyK30Pe800VMzenzLruG1j7XZQ9vs4W
4fj+LlGbalYNDXfAVFcMnmZQzzTOGdpbWgh5aHjPBElE/wHTp4X33I52atvFQT5i+Dospxg175Ev
km5wLPtaFB8JNDaBokmCvYj363rZZZ2ZzD93T8wakC/C8O63bdvAChsgZBFF3vAAVP41vFKu5CBM
WddAOLdkS8tY7UQM5Bm48dwQxrmKC4icxH04L2TUTaERZ3DfHpDLOTUTn1CJNurua9IN6RttS9wE
/Ipg0uesiPPvwFGUD9QK2IRAaaHHl3rg89sQmhfCavgFR2d7ZzYM0LzRefg8BtBUBC3UYEmpsu6L
qMk8FI9Gf4ND5bIZ0m/w2E01NStHL/3t/W2r19z3LiqvzOi6Dh8ykJSjr92N48qexkY6+PIrodKy
SAqDcZ0QJErl8x9Q6slf+urhVkGjHa2GeyjaYtUPIPTG+TXXrOwxKS7wfuLNdEMDlzxuhu9eBA/b
i7eZT+Kl2TM4x1ue755HviWkHV1T8Gyr9r2FWV8yF9GeUv8b9DkeUj+yb8tqz4f9CLzZCrN66Tkt
SqqFAF04JHknutpDJZrTpmpSv8Uf/hU29o5PbWAaHP3D0kfhIC464lqAb/PXGOEXGWAsRVDKl4L4
ZPv+88Fz79fdsEg/viRREnHu4lK3zy+R8IauR2MyAEtree758FMd87IJr2iDxrECH71ZfYS47V7S
ewE4ByHcf3yzpianvdO0VE3Ni+jmX4+GEsnKT3sMMYCrDb/6E32c+JlC68cbjB/sm/j3idar165n
Okhh/8TKCU/ACqeuhAUDOt6wHefuzs7OGPj4g4AtkBvkBp63dvSWLcYzgvbBwlvvxne1B1F1/RGw
3uKvRT7R2K0/rqRP2RwX8zpRGnd99W+pzZtfhTI+yxHO2tjPXRngk6MRa8rNyyQhyv2sOweKALJJ
kyDyO2/A3l0Vixd/Qtr4HPMn+KQGAU0+lLCsqQxZ/MIpTGlPIyYOhoAo8yYv66tXMkLfvbUm9U5z
TeqsCfezLvy5KwOCexCKqIfwi0yAsu2hTBvzCc52X+k7UWLo4RWFm8a3Tas+WrZs1pdixXVIGv8e
Qp5SDCGz5sDoTKDOkVpQHCYC6ENYM592QnGrtSUf23TN1eFbuM8qkLM5/nNXRgpBDyWEKm1H5wP9
8U5DoNqhW8DW3jzR1fkq6jN48Xb6dh5q/utzmLtkcjpd2eH5l0HJX0Twr4IiBkHJ/JYOryr0Abw5
24B7r0AnqzamUj2IxJnWOdf6/x8HjGPFN/frwgAAAABJRU5ErkJggg==

--------------IwNFD6jAc0XuWzOHQIH9XTRF--

**Comment by wojtekKrol** [comment]
I have the same problem and I have a feeling that this is related to the font used in pdf, I have no problem to download and open these pdfs locally. @huang633 did you manage to resolve your issue?
