### ISSUE TITLE
How to search only in certain page?

### ISSUE THREAD

**Issue by wonjunkang** [mozilla/pdf.js#12452]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: 2.0
- Is a browser extension: No

Steps to reproduce the problem:

I'm looking to enforce the web viewer to search the input text on specific page we give them. 
So for example, if I give text and a page number, pdfjs should only search within that page and no other pages. 
I'm trying to speed up the search when pdf file has lots of pages. 

Thanks

**Comment by timvandermeij** [comment]
This is not something that PDF.js supports, so you'll have to implement this yourself. What _might_ work (untested) is setting the `pageIdx` as offset.
