### ISSUE TITLE
PDF character randering problem

### ISSUE THREAD

**Issue by ffurkAn** [mozilla/pdf.js#12469]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:"{"http_parser":"2.7.0","node":"7.4.0","v8":"5.6.326.50","uv":"1.10.1","zlib":"1.2.8","ares":"1.10.1-DEV","modules":"53","openssl":"1.0.2j","electron":"1.6.2",**"chrome":"56.0.2924.87"**,"atom-shell":"1.6.2"}"

- Operating system and its version: win10
- PDF.js version: 2.5.207-es5
- Is a browser extension:

Steps to reproduce the problem:
This is happening randomly. Sometimes, after opening viewer again and again, It is displayed correctly.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2103017/95664136-cb87e400-0b4d-11eb-9020-90c935034fce.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2103017/95664144-d5a9e280-0b4d-11eb-903d-d8a16d4a5ae0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is mandatory, in order for this (or any other) issue to be actionable/valid.

> Web browser and its version:"{"http_parser":"2.7.0","node":"7.4.0","v8":"5.6.326.50","uv":"1.10.1","zlib":"1.2.8","ares":"1.10.1-DEV","modules":"53","openssl":"1.0.2j","electron":"1.6.2",**"chrome":"56.0.2924.87"**,"atom-shell":"1.6.2"}"

Huh, that doesn't really look like a browser but rather Node.js!?

---

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
