### ISSUE TITLE
Webpage nested pdfjs to achieve online preview of documents, how to achieve page turning after PDF document full screen.

### ISSUE THREAD

**Issue by kexuebin** [mozilla/pdf.js#12468]
Webpage nested pdfjs to achieve online preview of documents, how to achieve page turning after PDF document full screen.

**Comment by timvandermeij** [comment]
It's not really clear what the question is given that the sentence is hard to interpret. I assume you mean switching the page in presentation mode, which can be done using the arrow keys.
