### ISSUE TITLE
Second request's range overlapping first request's range

### ISSUE THREAD

**Issue by maitreya2954** [mozilla/pdf.js#12463]
Configuration:
- Web browser and its version: Chrome 85.0.4183.121
- Operating system and its version: MacOS 10.13.6
- PDF.js version: 2.1.266
- Is a browser extension: No

Steps to reproduce the problem:
I am using PDFDataRangeTransport (as shown below). 
```
//fetchUsingXhr resolves with data from 0 to 524287
self.fetchUsingXhr(url, 0, 524287).then((data) => {
    let transport = new window.pdfjsLib.PDFDataRangeTransport(data.fileSize, data.response);
    transport.requestDataRange = function (begin, end) {
        self.fetchUsingXhr(url, begin, end).then((data) => {
            transport.onDataProgress(end);
            transport.onDataRange(begin, data.response);
        });
    };
    loadingTask = window.pdfjsLib.getDocument({
        range: transport,
        disableRange: false,
        disableAutoFetch: true,
        disableStream: true,
        cMapPacked: true,
        rangeChunkSize: 524288,
        cMapUrl: cMapUrl
    });
    // setting up pdfviewer
});
```
These are the first few requests made.
<img width="603" alt="Screen Shot 2020-10-09 at 5 29 54 PM" src="https://user-images.githubusercontent.com/23173338/95580747-75d01080-0a55-11eb-9bcc-71181c3b71e7.png">

What is the expected behavior? 
Ideally, When pdf.js is already provided with 525KB (first request in screenshot) of initial data through PDFDataRangeTransport, I expect the next range requests to make requests for data after 525KB. The expected ranges for the first two requests is
1st request:  0-524287
2nd request: 524288-endrange 

What went wrong?
But, the 2nd request which is 525KB is from the 0th byte. 
1st request: 0-524287
2nd request: 0-524287

What am I doing wrong here. How to avoid this overlapping range requests?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.1.266

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by maitreya2954** [comment]
I was able to pin the issue down to the _rangeChunkSize_.

JSBIN: https://jsbin.com/xaralow/24
pdfjs version : 2.10.377

Snippet: 
```
# fetchData(begin, end) - fetches data from server in range [begin, end-1]
fetchData(0, 128 * 1024).then((data) => {
        let transport = new window.pdfjsLib.PDFDataRangeTransport(data.fileSize, data.response),
            initialData = data.response;
        transport.requestDataRange = function (begin, end) {
                fetchData(begin, end).then((data) => {
                    setTimeout(() => {
                        transport.onDataProgress(end);
                        transport.onDataRange(begin, data.response);
                    }, 50);
                });
            // }
        };
      # Setting 'transport' as range option and 512KB chunk size in getDocument and load pdf.
});
```

Here's what I am trying to achieve. Fetch 128KB of pdf data in the first request to ensure that the xref table is available for the pdf.js to parse and subsequently use 512KB requests to load the rest of the data. However, doing so, is triggering a second overlapping request (as shown in jsbin console logs). This overlapping request isn't triggered only if the initial data length is exactly equal to rangeChunkSize. For now, I am just fetching the initial data length equal to chunk size to avoid overlapping request. 

Considering what I am trying to achieve, after the initial data provided to PDFDataRangeTransport, pdfjs will have 128Kb of data and, in theory, shouldn't it just trigger subsequent request from 128KB onwards. Why does it trigger a request from 0 byte offset. Is there any reason for doing so?
