### ISSUE TITLE
RTL Text Contains Strange Characters

### ISSUE THREAD

**Issue by henrywarhurst** [mozilla/pdf.js#12460]
Attach (recommended) or Link to PDF file here: Fiddle: https://jsfiddle.net/47crfxqa/35/

Configuration:
- Web browser and its version: Chrome Version 85.0.4183.121
- Operating system and its version: MacOSX 10.14.6
- PDF.js version: v2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
1. View the extracted text vs actual pdf content in https://jsfiddle.net/47crfxqa/35/
2. **Some of the rtl text has strange punctuation characters in it after parsing by PDFJS.**
3. All the rtl text seems to be backwards (i.e. the raw strings are ltr). I'm not sure if this is expected. The main issue here is point 2. 

The PDF I'm using in that fiddle is 'https://raw.githubusercontent.com/henrywarhurst/pdf-bug/add13fca1d6bc8a167ba95546f64633f2c962f84/rtl.pdf'

**Comment by Snuffleupagus** [comment]
> Some of the rtl text has strange punctuation characters in it after parsing by PDFJS.

Without knowing the languages in question (looks like maybe Hebrew and Arabic), it's slightly difficult to tell what the problem is.

If it is the fact that some characters are copied as numbers, then similar behaviour can be observed in other PDF viewers as well (e.g. Adobe Reader and PDFium in Google Chrome). That is a bug in the PDF document *itself*, which is caused by incomplete/incorrect `/ToUnicode` data in the embedded font, rather than a problem in the PDF.js library.

**Comment by henrywarhurst** [comment]
@Snuffleupagus thanks for the fast response. Ok it appears that if I try to copy the first piece of text from https://raw.githubusercontent.com/henrywarhurst/pdf-bug/add13fca1d6bc8a167ba95546f64633f2c962f84/rtl.pdf in Preview on OSX I also have the dollar sign, so happy to agree that isn't a PDFJS-specific issue.

I do still find it an issue that the RTL text is backwards when selected and copied though. In my app I have to reverse text in RTL languages manually when it comes back from PDFJS's `page.getTextContent()` which seems like a bug to me. For example in https://raw.githubusercontent.com/henrywarhurst/pdf-bug/add13fca1d6bc8a167ba95546f64633f2c962f84/rtl.pdf

`ם ו לש` is returned when `שלומך` is written in the PDF. I confirmed that this behavior is inconsistent with Preview on OSX. In Preview when I select `שלומך` and paste it in a text document, it is correctly pasted as`שלומך`.

**Comment by timvandermeij** [comment]
Reopening to track the RTL issue now that more details have been provided. Thanks.

**Comment by henrywarhurst** [comment]
@Snuffleupagus and @timvandermeij I've had a crack at fixing this in https://github.com/mozilla/pdf.js/pull/12627 if you could please take a look when you get a chance :) :)

**Comment by Snuffleupagus** [comment]
WFM, as far as I can tell not speaking either Hebrew or Arabic, when testing with PDF.js version `2.12.126` (i.e. the built-in PDF Viewer in Firefox Nightly 96); this was most likely fixed be one (or more) of the somewhat recent textLayer patches.
