### ISSUE TITLE
Is it possible to change the scroll speed in the extension?

### ISSUE THREAD

**Issue by joegonzalez722** [mozilla/pdf.js#12467]
wondering if you can change a code to alter the scroll speed and make it faster or slower in pdfs

**Comment by Snuffleupagus** [comment]
No, since that's controlled by the browser.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue isn't really actionable/valid.

**Comment by joegonzalez722** [comment]
ok
