### ISSUE TITLE
Signature display problem

### ISSUE THREAD

**Issue by Lemonxu** [mozilla/pdf.js#12473]
pdf.js View display
![QQ图片20201012182558](https://user-images.githubusercontent.com/15154067/95736156-6ef50800-0cb8-11eb-97dd-ec0c39e6a8d8.png)
chrome view display
![QQ图片20201012182606](https://user-images.githubusercontent.com/15154067/95736175-73212580-0cb8-11eb-949f-b0611cd6936b.png)

**Comment by Snuffleupagus** [comment]
Duplicate of #1076
