### ISSUE TITLE
External calls to the print API ？？

### ISSUE THREAD

**Issue by happilyBoy** [mozilla/pdf.js#12474]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.Does PDf.js provide an external printing function that can call the API
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
No, you'll have to implement this in a custom deployment.
