### ISSUE TITLE
Some urls behind pushbutton are not extracted from the AA dictionary 

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12475]
Steps to reproduce the problem:
1. Open https://www.guidedesimpots.lu/wp-content/uploads/2019/02/160F-2019.pdf
2. The links behind FD, FO, DS, ... are not usable

These annotations correspond to a PushButton because their parent is and the action is in the AA dictionary associated to D (MouseDown).
So once https://github.com/mozilla/pdf.js/pull/12429 is merged we can easily extract url from the action.
Since for security reasons we won't implement `app.launchURL` we must handle that stuff in same way as we do for A dict.

**Comment by calixteman** [comment]
The issue in #9776 is slightly different since the actions in `AA::D` are `/GoTo` and here they're `/JavaScript`.
But finally thanks to your comment, I think I've a way better (and simpler) patch to handle the different cases.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
