### ISSUE TITLE
Populate values in acroform fields using annotationStorage and saveDocument

### ISSUE THREAD

**Issue by VineelG** [mozilla/pdf.js#12480]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 85.0.4183.121
- Operating system and its version: Windows 10
- PDF.js version: 2.7.0
- Is a browser extension: No

Using sample code provided in Acroforms example - I am trying to pre populate the acroform fields with values using annotationStorage and by calling saveDocument(annotationStorage). But couldn't able to acheive this. PDFDocumentProxy will always get empty annotationStorage, even though I add values to annotationStorage . I have tried using promise, but the _storage will always be empty. I am trying to saveDocument in side loadingTask promiseat document level, not sure if this should be done at page level (like annotations). 

Am I doing anything wrong here, could you please suggest how to achieve pre populating field values in acroforms. Attaching screenshot, if this help in better understanding the issue.
![2020-10-14_23-44-47](https://user-images.githubusercontent.com/68660373/96165043-b8a05580-0f39-11eb-9724-bcc33ab888cf.png)

Thanks

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.7.0

Huh, that *exact* version number doesn't actually exist.

> Attaching screenshot, if this help in better understanding the issue.

It does not; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by VineelG** [comment]
Hi @Snuffleupagus , the version I see in pdf.js file is 2.7.0 ( downloaded latest code on 23rd Sept 2020), may be should I see.

I have made the code available at [GitHub](https://github.com/VineelG/ng-pdfjs-acroforms/commits/master). Also I gone through recent code commits and issue discussions related to annotationStorage, still I couldn't able to pre populate values in acroform fields. I tried multiple ways to make this work, but none of them worked.

Can you please let me know how this can be achieved.

**Comment by timvandermeij** [comment]
I think the problem is actually how you set the values at https://github.com/VineelG/ng-pdfjs-acroforms/commit/5f5f7d7b748e0df0be6a2ad8caf4b735f88ee039#diff-884f7f49640e5923f6bcac4c51d90340330a178f662defbe61e5f5aac1c512deR34-R35. There doesn't appear to be a field called `textfield1`/`textfield2` in the `f1040.pdf` file. You need to use the IDs that PDF.js generates for the fields in the annotation layer there instead.

**Comment by VineelG** [comment]
Thanks, I tried with IDs generated by PDF.js, but still values not getting mapped in storage. Are you sure, I have implemented this in correct way? I feel something else as well I missed.

**Comment by kittychengyuenpui** [comment]
Hi, I am also facing similar problem of cannot populate values in acroform fields with `annotationStorage` and `saveDocument(annotationStorage)` even when using the IDs fetched by calling `getAnnotations` of PDFPageProxy.
Is there any update on this?
