### ISSUE TITLE
How to disable mouse wheel scroll

### ISSUE THREAD

**Issue by ePZuz** [mozilla/pdf.js#12499]
I have a problem. I need to disable mouse wheel scrolling in the Viewer. Navigation should only be based on the buttons in the menu. How can I do this?

**Comment by timvandermeij** [comment]
You'd most likely need to disable the `wheel` event; see https://github.com/mozilla/pdf.js/blob/10e76231238e46d6299c0e1d1647cdddd9b8da2c/web/app.js#L1813.
