### ISSUE TITLE
What version is pdf.js supported with Safari on iOS?

### ISSUE THREAD

**Issue by xiangbohua** [mozilla/pdf.js#12490]
Attach (recommended) or Link to PDF file here:

I got an error when I'm trying to display pdf file on iPhone.
The error message was : The browser/environment lacks support for critical functionality used by Pdf.jf library (eg.. `ReadableStream` add/or `Promise.allSettled`); Please use and ES5-compatible build instead.

I have tried iOS 11 iOS11.2 iOS 12 and iOS 13. Test pdf file was display succeed on iOS 13 but other versions of iOS can not be displayed.

So. what is the ES5-compatible build and where can I get that build ?

thank!

Configuration:
- Web browser and its version:Safari on iOS 
- Operating system and its version:iOS version 11   11.2 12
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1.  open an url 
2.

What is the expected behavior? (add screenshot)
remind that the browser lacks native support.
<img width="381" alt="WeCom20201018-115341@2x" src="https://user-images.githubusercontent.com/10529889/96358326-988ab500-1138-11eb-993a-382021fdbb30.png">

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Quoting from the WIKI, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> From version 2.4.456 on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the `-es5-dist.zip` suffix).

Hence see either https://mozilla.github.io/pdf.js/getting_started/#download, or the individual releases listed at https://github.com/mozilla/pdf.js/releases

**Comment by xiangbohua** [comment]
Thanks a lot
