### ISSUE TITLE
Remove the `version-1.10` branch

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#12492]
The `version-1.10` branch, see https://github.com/mozilla/pdf.js/tree/version-1.10, was created when the very *last* `1.x.y`-release was made, see https://github.com/mozilla/pdf.js/releases/tag/v1.10.100.

The purpose of the `version-1.10` branch, as far as I can remember, was to simplify any possible (future) back-porting of patches. However, there hasn't been even a single update to it ever since it was created *and* at this point in time any `1.x.y` release is well and truly *unsupported* (and has been for years).

Hence I'd suggest that we can remove https://github.com/mozilla/pdf.js/tree/version-1.10 now, since it's unnecessary.

**Comment by Yashs911** [comment]
Hi, @Snuffleupagus I would like to work on this issue

**Comment by timvandermeij** [comment]
It's removed now.

@Yashs911 This is only something a maintainer can do.
