### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by jagdishbharucha** [mozilla/pdf.js#12494]
Where can I report security vulnerability found in this library?

Configuration:
- Web browser and its version: Google Chrome Version 86.0.4240.75 and Mozilla Firefox 81.0.2
- Operating system and its version:
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:

What is the expected behavior?

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by brendandahl** [comment]
Please file a [security bug on bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?assigned_to=nobody%40mozilla.org&bug_ignored=0&bug_severity=--&bug_status=NEW&cf_a11y_review_project_flag=---&cf_fission_milestone=---&cf_fx_iteration=---&cf_fx_points=---&cf_root_cause=---&cf_status_firefox81=---&cf_status_firefox82=---&cf_status_firefox83=---&cf_status_firefox84=---&cf_status_firefox_esr78=---&cf_tracking_firefox81=---&cf_tracking_firefox82=---&cf_tracking_firefox83=---&cf_tracking_firefox84=---&cf_tracking_firefox_esr78=---&cf_tracking_firefox_relnote=---&cf_tracking_firefox_sumo=---&cf_webcompat_priority=---&component=PDF%20Viewer&contenttypemethod=list&contenttypeselection=text%2Fplain&defined_groups=1&filed_via=standard_form&flag_type-203=X&flag_type-37=X&flag_type-41=X&flag_type-607=X&flag_type-708=X&flag_type-721=X&flag_type-737=X&flag_type-748=X&flag_type-787=X&flag_type-799=X&flag_type-800=X&flag_type-803=X&flag_type-846=X&flag_type-855=X&flag_type-864=X&flag_type-930=X&flag_type-936=X&flag_type-945=X&form_name=enter_bug&groups=firefox-core-security&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Unspecified&priority=--&product=Firefox&rep_platform=Unspecified&target_milestone=---&version=unspecified)

**Comment by jagdishbharucha** [comment]
Okay I'll do that.
Thanks!
