### ISSUE TITLE
Relative links did not enable by setting the docBaseUrl

### ISSUE THREAD

**Issue by ishanuda** [mozilla/pdf.js#12500]
Hi,

I am new to pdf.js and managed to set up the pdf.js and pdf_viewer.js using the following code.
My intention is to enable internal links and work with PDF files.

```
var DEFAULT_URL = "../learning/test.pdf";
var DOC_BASE_URL = "D:/workspace/repos/github/pdf.js/examples/learning";
```

```
// Loading document.
var loadingTask = pdfjsLib.getDocument({
  url: DEFAULT_URL,
  docBaseUrl: DOC_BASE_URL,
});
```

```
loadingTask.promise.then(function (pdfDocument) {
  pdfViewer.setDocument(pdfDocument);
  pdfLinkService.setDocument(pdfDocument, null);
  debugger;
});
```

The set up was a success. But the problem is, it did not enable the internal links.
Could someone help me to enable the internal links using the docBaseUrl, please?

Also, I went through the following links. But could not get a proper idea about the fix.

[Relative links to pdfs not working with hosted pdf.js and demo viewer](https://github.com/mozilla/pdf.js/issues/8771)
[Hyperlinks not working](https://github.com/mozilla/pdf.js/issues/9637)
[Add support for relative URLs...](https://github.com/mozilla/pdf.js/pull/7689)

**NOTE: I know this is a place to report errors.
I asked the related question in the available chat room at https://chat.mozilla.org/.
But no one answered the question. That is why I am posting the question here.
Please be kind enough.**

Thank you very much.
Shan

**Comment by timvandermeij** [comment]
You'll have to provide a runnable example so we can take a look, because as indicated in the issue template just code snippets don't help to be able to debug this. Moreover, start by checking if the example at https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js works. If so, you can check what the differences are with your code.

**Comment by ishanuda** [comment]
Dear sir,

Thank you very much for your feedback.

I am sorry that I did not have attached the required files.

As you pointed out, that is the exact file I am trying to experiment with the sample pdf files.

Here I have attached the code and sample pdf file for your reference.

[internal-link.zip](https://github.com/mozilla/pdf.js/files/5411451/internal-link.zip)

Thank you very much.
Shan

**Comment by timvandermeij** [comment]
I looked into this and the problem seems to be that `docBaseUrl` needs to get a valid URL, so not a relative path to a local file. There is a unit test that seems to confirm this at: https://github.com/mozilla/pdf.js/blob/02bcc25b9fc6963a7dd90d1669fa816e03111ae0/test/unit/api_spec.js#L1488-L1499
In your example, your `docBaseUrl` is `../learning/sample-files`, which therefore seems to be invalid.

**Comment by ishanuda** [comment]
Dear sir,

Thank you very much for your great explanation.

As you pointed out, I have set up the URL and now the links are enabled.
Thank you very much once again.

However, the related link has a problem as you can see in the attached images.

The docBaseUrl assignment:

![configured-links](https://user-images.githubusercontent.com/8893919/96681358-a3c32800-1366-11eb-9ef1-8907a225c5f8.png)

Output result:

![sample-file-link](https://user-images.githubusercontent.com/8893919/96681405-b8072500-1366-11eb-9dca-1e55124d7333.png)

Folder and file structure:

![sample-files](https://user-images.githubusercontent.com/8893919/96681612-192ef880-1367-11eb-878e-b3a7eaefb6cf.png)

Inside the **folder** has the docBaseUrl target file the **Second-Sample-PDF-FILE2.pdf**

As you can see, the **folder** is duplicated in the URL.
(see the output result image)

Also, the file **Linking to DOC.docx** is in the **sample-files** folder, 
The URL related to the file also has the **folder** name attached 
(see the output result image)

Is something wrong with the **url** assignment or the **docBaseUrl** assignment?


[Download Sample code & related files](https://github.com/mozilla/pdf.js/files/5413706/internal-link.zip)

In addition, I would like to know the following possibilities.

01. If I mention a file related URL in the **docBaseUrl**, Is that the only file navigatable in the file system?

For example, if I have a PDF file with some table of contents (TOC) linking internally to other files,
Assigning this PDF file to the **url** as the parent file and assigning one of the TOC related files in the **docBaseUrl**,
Does this approach link to all the PDF files that are available in the parent PDF file witch is having the TOC?
(NOTE: files can be in the root folder, child folders, or out of the root folder)

02. Can I set the **docBaseUrl** dynamically in case I need to change?

Thank you very much.
Shan

**Comment by timvandermeij** [comment]
The `docBaseUrl` should be to the _root_ of the folder where the PDF file lives, so it should not contain the file name of the PDF file. If you don't want the `folder` part, just remove that from the base URL. The `docBaseUrl` is given when rendering the document, so it can be changed dynamically for each document.

**Comment by ishanuda** [comment]
Dear sir,

Thank you for your explanation.
I think now I clearly understand the way `docBaseUrl `works.

However, I notice that the `docBaseUrl `should end with a forward slash to the root folder in order to resolve the links.

e.g. 
`var DOC_BASE_URL = "http://127.0.0.1:5500/examples/";`

Also, I would like to know, 
How to access the underlying pdfjsLib or any other services to set the `docBaseUrl` or manipulate the PDF document?
e.g. `getJavaScript()` etc when implementing the built-in [web viewer](https://mozilla.github.io/pdf.js/web/viewer.html)

Thank you very much.
Shan
