### ISSUE TITLE
We are using Angular with viewer js and pdf. After annotating in viewer.js, is it possible to call an event in typescript?

### ISSUE THREAD

**Issue by JohnAugustineG** [mozilla/pdf.js#12507]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
None of the required information from the template is provided. You can listen for the `annotationlayerrendered` event to know when the annotation layer is done rendering.
