### ISSUE TITLE
Highlight annotation div can be on top of a textfield

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12504]
Attach (recommended) or Link to PDF file here:
[plop.pdf](https://github.com/mozilla/pdf.js/files/5415411/plop.pdf)

Here the highlight has two rectangles and only `Annotation::Rect` is used when creating the `div` in the annotation layer and so the field is almost unusable.

**Comment by timvandermeij** [comment]
Fixed the PR above.
