### ISSUE TITLE
How to compress the size of PDF file？Because the high definition presentation will cause the  web page to load slowly. 

### ISSUE THREAD

**Issue by fireWinters** [mozilla/pdf.js#12511]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
How to compress the size of PDF file, I mean, when showing a one-page file, this file is relatively large, can you just show it instead of rendering it in HD? Because the high definition presentation will cause the page to load slowly. I am looking forward to your reply. Thank you
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
PDF.js just renders what it's given by the PDF file, so if that needs to be reduced you need to reduce the size of the PDF file itself.
