### ISSUE TITLE
Unexpected Cross line appear in the rectangle.

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#12510]
Attach (recommended) or Link to PDF file here:
[rect.pdf](https://github.com/mozilla/pdf.js/files/5419714/rect.pdf)

Configuration:
- Web browser and its version: Chrome 86.0.4240.80
- Operating system and its version: macOS 10.15.4
- PDF.js version: 2.7.164
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF with pdf.js in Chrome.
2. Found the cross line appear in the rectangle.

What is the expected behavior? (add screenshot)
It displayed correctly in the safari.
![image](https://user-images.githubusercontent.com/18492951/96818340-e7e02680-1453-11eb-805b-d1f7d19f0fc4.png)

What went wrong? (add screenshot)
It displayed wrong in the chrome.
![image](https://user-images.githubusercontent.com/18492951/96818375-fcbcba00-1453-11eb-8536-3a6996942d3d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> It displayed correctly in the safari.

And also in Firefox; hence this would suggest a canvas, hardware acceleration, and/or driver issue specific to Google Chrome, rather than the PDF.js library; as such it's unfortunately very difficult to see that this can be fixed here.
