### ISSUE TITLE
Large characters rendered overlapping on PDF.js in Firefox 82

### ISSUE THREAD

**Issue by blerner** [mozilla/pdf.js#12533]
Example pdf: https://www.mass.gov/doc/covid-19-dashboard-october-25-2020/download -- and most of the previous versions (https://www.mass.gov/info-details/archive-of-covid-19-cases-in-massachusetts) as well

Configuration:
- Web browser and its version: Firefox v82.0
- Operating system and its version: Windows 10
- PDF.js version: whatever's bundled with Firefox
- Is a browser extension: no

Steps to reproduce the problem:
1. View pages 18 or 20 of the PDF for examples

Actual results:
![image](https://user-images.githubusercontent.com/918464/97169604-b1125500-1760-11eb-9793-23aae044dcf9.png)

Expected results (in Chrome):
![image](https://user-images.githubusercontent.com/918464/97169685-d4d59b00-1760-11eb-8a1e-9117987c0f38.png)

**Comment by timvandermeij** [comment]
Fixed by the PR above.

**Comment by blerner** [comment]
Wow, that's an unexpected root cause!  Thanks for the quick fix :)

**Comment by timvandermeij** [comment]
Yes, it's quite surprising, especially since we would expect this to have been reported more often given how long this code already exists. Fortunately it seems to be very rare to trigger in practice, but this PDF file managed to do so. Thank you for reporting it so it could be fixed!
