### ISSUE TITLE
PDF rendering problem. Characters are broken

### ISSUE THREAD

**Issue by ffurkAn** [mozilla/pdf.js#12536]
Attach (recommended) or Link to PDF file here:
[pdf15-2.pdf](https://github.com/mozilla/pdf.js/files/5443804/pdf15-2.pdf)
[pdf13.PDF](https://github.com/mozilla/pdf.js/files/5444114/pdf13.PDF)

Configuration:
I'am using the viewer in electronjs. Versions below:
![image](https://user-images.githubusercontent.com/2103017/97274291-8221df00-1845-11eb-94bf-ff336e20f6b5.png)

- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.5.205-es5
- Is a browser extension:

Steps to reproduce the problem:
Case1 - broken characters is being displayed: If I see characters displayed wrong, I reopen the same file over and over again, I see problem still exists. However, problem dissapeared after I open another pdf file. 

Case2 - nothing seems wrong: I close the electron app, delete caches, open fil and everything seems perfect.

Actually, Problem occurs *randomly* on some specific files. I suspect about fonts and pdf version. But pdf version seems not relative.
 
What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2103017/97274001-150e4980-1845-11eb-989a-e07151652057.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2103017/97274025-20617500-1845-11eb-92d7-5b7d7ac6d041.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I'am using the viewer in electronjs.

Please note that Electron is not an officially supported configuration, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, and also that Node.js environments in general are not the *primary* focus for this library.

Furthermore, it's impossible for anyone to reproduce what you're seeing; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Actually, Problem occurs _randomly_ on some specific files.

This would suggest a bug (and an intermittent one at that) in Electron, rather than the PDF.js library, and as such it unfortunately *very* difficult to see that this is an actionable/valid issue here.

**Comment by ffurkAn** [comment]
There is also a distinction in versions. In electron, I use the -es5- version. however, I use normal version in web app.

**Comment by timvandermeij** [comment]
I agree with https://github.com/mozilla/pdf.js/issues/12536#issuecomment-717101681. Without a runnable example there is nothing we can do here.

**Comment by ffurkAn** [comment]
At least, you should have some ideas, which may help me to get closer the root cause, about what might be the reason for the problem.

**Comment by ffurkAn** [comment]
For the electron side, I did downgrade the version to 1.9.LATEST and it resolved my problem with smaller issues like unexpected italic and bold characters. Reopening the viewer fixes immediately. 

May be you can think of the problem again with these additional informations.
