### ISSUE TITLE
Slow (but kinda awesome) rendering of graphs in single PDF

### ISSUE THREAD

**Issue by occasionallydavid** [mozilla/pdf.js#12535]
Attach (recommended) or Link to PDF file here:

http://www.espenhaug.com/KnowYourWeapon.pdf

Configuration:

- Web browser and its version: Firefox 82
- Operating system and its version: Ubuntu 20.04, Dell XPS 9550 HiDPI 
- PDF.js version: as shipped
- Is a browser extension: no

Steps to reproduce the problem:

1. Observe pleasing progressive rendering effect on all the 3D graphs in the document as they are scrolled into view
2. Recall that PDFs are not intended to be animated and consider it might be worth reporting as a potential bug

What is the expected behavior? (add screenshot)

Graphs render immediately, as in for example in evince using the same PDF.

What went wrong? (add screenshot)

Graphs render pleasingly

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
This is a huge vector graphic. I've seen the effect here but it's not really THAT slow, and in rare cases I've also seen such an effect with Adobe Reader, e.g. with
http://www.math.ubc.ca/~cass/graphics/manual/pdf/ch14.pdf
(see first and last page)

**Comment by occasionallydavid** [comment]
Feel free to close this if it is spurious, I do not have any problem with the performance, it just seemed like maybe the file was exposing some slow algorithm that may not have been worth reporting

**Comment by Snuffleupagus** [comment]
The PDF document in https://github.com/mozilla/pdf.js/issues/12535#issue-729915912 simply contains an absolutely *ridiculous* amount of "normal" rendering operators, i.e. there's no repeated images or similar that could be cached, and as such there's unfortunately not much that we can really do to improve performance here.

Also, when testing this in Firefox 84 on Windows, the *slowest* page takes `< 1.5` seconds to finish loading (which while not great isn't terrible either IMHO).

**Comment by timvandermeij** [comment]
I agree, so let's close this. @occasionallydavid Thank you for reporting it though; reporting and closing after investigation is always better than not reporting it, since it might be something that is indeed wrong/can be optimized.
