### ISSUE TITLE
An error message occurs when printing high resolution file, "Overload resolution failed" 

### ISSUE THREAD

**Issue by winnerys** [mozilla/pdf.js#12547]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome@latest
- Operating system and its version: Windows 10 1809
- PDF.js version: 2.6.347
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the high resolution PDF file with a viewer and click the print icon.
2. The percentage of progress bar does not change from zero percent.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/35720920/97507363-68f16d80-19c0-11eb-84ca-4e37a5d1b99c.png)

I'm not sure there's resolution limitation when printing, I think this is resolution problem.
When the resolution exceeds a certain standard, the error message below appears when printing.
- Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at pdf_print_service.js:201

In my case, the PDF file's resolution is 5,080mm * 3,503mm.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Unfortunately there is nothing we can do without the PDF document itself as requested in the issue template since there is no way for us to debug this. Most likely this is indeed a browser printing limitation.
