### ISSUE TITLE
PDF not rendering properly in android kitkat webview

### ISSUE THREAD

**Issue by shibilyt** [mozilla/pdf.js#12544]
I am trying to display pdf in android webview using pdfjs.

It's working fine in android versions other than kitkat. 

In KitKat, it's displaying with some letters missing from the pdf. For example, the word "parameter" is displayed as "p r meter". Here a is missing from the word. Similarly, many words are missing characters.

pdfjs version is 2.6.37

**Comment by Snuffleupagus** [comment]
According to https://en.wikipedia.org/wiki/Android_version_history#Android_4.4_KitKat_(API_19) the last release from that branch was in 2014, and we simply can't/won't support platforms and/or browsers which are that old.
