### ISSUE TITLE
How to get html span array for pdf file having more than 10 pages at once

### ISSUE THREAD

**Issue by trikdas** [mozilla/pdf.js#12545]
Attach (recommended) or Link to PDF file here:
[ttt.pdf](https://github.com/mozilla/pdf.js/files/5453823/ttt.pdf)

Configuration:
- Web browser and its version: Google Chrome  
Version 86.0.4240.111 (Official Build) (64-bit) 
- Operating system and its version: Windows 10 
- PDF.js version: pdf.js 2.6.401 

Steps to reproduce the problem:
1. Trying to get html span array which is rendered by pdf.js 
2. at a time html span is available for only 10 pages

What is the expected behavior? (add screenshot)
need to get html span for more than 10 pages at once 

What went wrong? (add screenshot)
when moving to page -11, span elements of page-1 is getting removed from html dom. 
is there any way to get this rid of 10 pages restriction?
screenshot shows html element details where page-13 is loaded, we can see page-1 to page-4 does not contain any span tags.
this is because pdf.js loads only 10 pages at a time (page-5 to page14) in our case.
![pdfjs inspect ele](https://user-images.githubusercontent.com/73604779/97474339-04a7bd00-1972-11eb-93d8-7956420a1bcd.png)
 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by viju2008** [comment]
Hello,

Me too facing the same issue. Request Mozilla team to help

**Comment by Snuffleupagus** [comment]
As explained in the Wiki, that's not a good idea and consequently it's not something that will be supported: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by viju2008** [comment]
Hello Team,


We need to render upto 30 pages together . Please tell us where we can change the settings

**Comment by trikdas** [comment]
Team,
It would be of great help if we can change the restriction of 10 pages to 30 pages. pls let us know how to change it

**Comment by viju2008** [comment]
> As explained in the Wiki, that's not a good idea and consequently it's not something that will be supported: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

Hello can we increase the span number of pages to 30 pages
