### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by tonywood** [mozilla/pdf.js#12558]
Attach (recommended) or Link to PDF file here:
mn_ScheduleB_202010261010.pdf
Password: 57JE37iU
https://turnkeygroup.egnyte.com/dl/ohmuxcpkDP

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:
Chrome or Firefox latest versions and latest version of pdf.js

Steps to reproduce the problem:
1. load the file in the viewer
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
see the outline shown around the text in the header part of the pdf report.  When opened in a standard desktop pdf viewer it shows correctly.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by tonywood** [comment]
link to screenshot
screenshot.png
Password: woeGEMRj
https://turnkeygroup.egnyte.com/dl/Na2Dz8OPnU

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> mn_ScheduleB_202010261010.pdf
> Password: 57JE37iU
> https://turnkeygroup.egnyte.com/dl/ohmuxcpkDP

*Generally speaking:* Please attach the PDF file, and screen-shots, *directly* to the issue instead to avoid people having to download if from a third-party source (especially since passwords are required). That way, it's guaranteed that the files remain easily accessible in the future.

Furthermore, it also appears that that website is embedding a *custom*, and many years out-of-date, version of the PDF.js library.

> * Web browser and its version:
> * Operating system and its version:
> * PDF.js version:
> * Is a browser extension:
>   Chrome or Firefox latest versions and latest version of pdf.js

Please actually fill out this part of the ISSUE_TEMPLATE as fully as absolutely possible; note that "latest" can mean any number of things and is essentially not useful.

**Comment by tonywood** [comment]
There seemed to be an error attaching any files which is why I had to put a link. I have tried with the latest version and have asked PDF is express and they report the same thing. What else can I do to help show the problem?


Tony Wood
Managing Director

Turnkey Group

tony.wood@tctl.co.uk<mailto:tony.wood@tctl.co.uk>

COMPLETE COMPUTER SOLUTIONS
        [cid:esiglogo_4287346e-a724-43d3-b161-79f3a619610e.png]

The Turnkey Group Ltd
Thornton Lodge, East Kilbride Road,
Glasgow, G76 9HW, UK
(+44) 141 644 5444<tel:+4401416445444>
www.turnkey-group.com<https://www.turnkey-group.com>    [cid:ipsPartnerLogo_7da9b27f-03d2-4a86-b1b8-2ce0af2a1728.png]

________________________________
This e-mail was sent to you by The Turnkey Group Ltd. Registered in Scotland No: 196063 with registered offices at Thornton Lodge, East Kilbride Road, Glasgow, G76 9HW. This e-mail and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you are not the intended recipient, please delete this e-mail and inform the sender as soon as possible. Copyright in this email and any files transmitted with it is owned by The Turnkey Group Ltd. The opinions, statements and thoughts expressed in this email are those of the individual sender and not necessarily The Turnkey Group Ltd. or any associated personnel. It is the responsibility of the recipient to ensure that this email and any associated files are virus free and The Turnkey Group Ltd. does not accept any responsibility for any loss or damage arising in any way from its use.

________________________________

**Comment by timvandermeij** [comment]
> Furthermore, it also appears that that website is embedding a custom, and many years out-of-date, version of the PDF.js library.

It looks like this, if anything, is the issue here, since the PDF file itself renders exactly like in other PDF viewers for me when opened using https://mozilla.github.io/pdf.js/web/viewer.html (the latest development version of PDF.js).

**Comment by tonywood** [comment]
![image](https://user-images.githubusercontent.com/12101618/97855735-1c28d200-1cf3-11eb-81d1-4c869a527bc6.png)

I have opened the document using the link you mentioned (https://mozilla.github.io/pdf.js/web/viewer.html) and still get the outline in the header text a various zoom sizes as shown in the attached image.
Resolution of screen is 2560 x 1440 
100% Scale.

Let me know if there is any other information I can provide to help resolve this please?

**Comment by timvandermeij** [comment]
I can't reproduce this, but from the screenshot it looks like graphics corruption caused by a graphics driver issue. I'd recommend to update the graphics drivers; historically this has solved quite a few rendering problems.

**Comment by tonywood** [comment]
Its really odd as every other viewer i have tried works fine.  Adobe, Foxit, Nitro all render the header correctly.  I find it can be ok at some zoom levels but not on others.
