### ISSUE TITLE
How to access the current page number of the displayed page

### ISSUE THREAD

**Issue by cedeling** [mozilla/pdf.js#12556]
No problem just a question.  I have pdf.js working well, but have a need for javascript to acess the page number of the currently displayed page of the pdf.  Eg 2 of 17, how can I access the 2?

**Comment by timvandermeij** [comment]
Assuming you're using the default viewer, you can get this from https://github.com/mozilla/pdf.js/blob/6fae381c575061bd31ce20964c77db4c56afabd5/web/base_viewer.js#L237-L242.

**Comment by cedeling** [comment]
Thanks Tim I found  `get currentPageNumber()` that you referred to, but sadly don't know how to call it.  I don't use Node or Jquery just plain old javascript.
My javascript to display a PDF document is:

var pdfjs_url='/pdfjs/web/viewer.html?file=%2Fcp%2Fcasepages%2F'+credentials.case_id+'%2FOfflineDocs%2Fdocs%2F'+p_docnum+'.pdf';
var str='<iframe  width="1000px" height="800px" src="'+ pdfjs_url+'">';
document.getElementById('div4doc').innerHTML=str;

The var pdfjs_url= is all one a single line and I am using the default viewer.  /pdfjs/web/ is as downloaded.

Assume reader scrolls down to page 2 and wants to make a note of something he sees there, my javascript opens a form with inputs and already knows which document is being used, but does not yet know what page the user is looking at.  

What code do I need to write to return the "2" so that it can be saved as part of the user note?  I understand that currentPageNumber() provides that, but dont know how to access it.

I am old and write procedural style code, not object oriented code so dont know how to access the functions in the BaseViewer class

**Comment by cedeling** [comment]
Solved! FOund answer at 
https://stackoverflow.com/questions/35873181/how-can-i-get-the-current-pdf-page-number-from-pdf-js-iframe/35887722#35887722


var iFrame =  document.getElementById('iframe1');
if ( iFrame.contentDocument ) {
	currentPageNum= iFrame.contentDocument.getElementById('pageNumber').value;
}
alert(currentPageNum);

Closing issue, thanks
