### ISSUE TITLE
A high 'scale' value distorts the rendering

### ISSUE THREAD

**Issue by PatrickFromHolland** [mozilla/pdf.js#12550]
used files:
[page42.pdf](https://github.com/mozilla/pdf.js/files/5456649/page42.pdf) (the example pdf-1 page only)

A full example with 1 html file and the pdf: 
[pdfjs.zip](https://github.com/mozilla/pdf.js/files/5456678/pdfjs.zip)   

Configuration:
- Firefox 81.0.2 
- Windows 10:
- PDF.js version: 2.7.215
- Is a browser extension: no

Steps to reproduce the problem:
1. select scale-value 1.5 which renders fine (default). 
2. select scale-value 5.0 (or higher)

What is the expected behavior? all output should render the same (i.e. like below)

<img width="237" alt="correctRender" src="https://user-images.githubusercontent.com/73633801/97536779-f8e1e800-19bd-11eb-8611-f7deb2ab238e.PNG">

What went wrong? The rendered output added extra border-width (or some padding?) that distorts the layout. When selecting an even higher scale all texts disappear behind this border. 

<img width="230" alt="wrongRender" src="https://user-images.githubusercontent.com/73633801/97536841-0c8d4e80-19be-11eb-8ac4-63fb3f1f4389.PNG">

<img width="233" alt="veryWrongRender" src="https://user-images.githubusercontent.com/73633801/97537522-35621380-19bf-11eb-8335-7f4077489549.PNG">

**Comment by Snuffleupagus** [comment]
Fixed by PR #13361.
