### ISSUE TITLE
console.error on webViewerLoad is necessary ?

### ISSUE THREAD

**Issue by RoXuS** [mozilla/pdf.js#12577]
Hey, we have an error when we use your web app inside a iframe served by a different domain.

````
webviewerloaded: SecurityError: Blocked a frame with origin "https://...com" from accessing a cross-origin frame.
````
The error seems to be "normal", but the `console.error` is it necessary? You can't use `console.warn` instead of error?
https://github.com/mozilla/pdf.js/pull/11837/files#diff-987d91686287a25ac2405baaf17b699a5fc1a176a53f8ea347a72ef486001f7bR225

Thx!

**Comment by Snuffleupagus** [comment]
Given that an *actual* error did occurr, and that it only applies to a situation when the event in question cannot be dispatched at the appropriate document, it doesn't seem warranted to change the existing code in my opinion.

Furthermore, you shouldn't be using the default viewer as-is anyway; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by RoXuS** [comment]
Yeah we don't use it "as-is" but we want to keep the most clean as possible in order to follow your updates.

I open this issue because in my opinion it was a strange behavior, but ok, I will delete the `console.error` in our fork, np.

Thx for you response!
