### ISSUE TITLE
Open full width

### ISSUE THREAD

**Issue by Brendon-F** [mozilla/pdf.js#12573]
Hi,

I have no coding experience but would like to open the pdf full width of the viewer. I have used #zoom=page-width at the end of the URL which works fine outside an iframe. Inside a iframe, for some reason, this changed the default open on the last page viewed, to open on the first page. As soon as I take #zoom=page-width off again, it then opens on the last page viewed. I need to keep it opening on the last page viewed so think editing the code inside the viewer.js would be better.

So I would like to find the code and change this inside the viewer.js, I am using the latest version 2.5.207. 

it is just a case of changing var DEFAULT_SCALE_VALUE = 'auto' ; to var DEFAULT_SCALE_VALUE = 'page-width' ; 

Any help would be gratefully received.

**Comment by Snuffleupagus** [comment]
Simply setting the `defaultZoomValue` option (or preference) should do what you want; https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage contains some useful information.
Basically, adding something like the following to the document where the `<iframe>` is located should work:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set("disablePreferences", true); // Ensure that preferences will not override the value set below.

  PDFViewerApplicationOptions.set("defaultZoomValue", "page-fit");
});
```

Please keep in mind that this is first and foremost a bug-tracker, hence if you need additional assistance you'll have to provide *all* of the information as requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and also a runnable example; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
