### ISSUE TITLE
ios rendering pdf long time, about 30 minutes or longer,  pdf use font STSong and MSung, Can anyone help me?

### ISSUE THREAD

**Issue by theMxb** [mozilla/pdf.js#12578]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: ios app webview
- Operating system and its version:
- PDF.js version: 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
1. pdf file use font STSong and MSung 
2. ios app webview rendering pdf base64str long time, about 30 minutes or longer

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

That part of the issue template is *required*, in order for any issue to be actionable/valid.

> Steps to reproduce the problem:
>     1. pdf file use font STSong and MSung
>     2. ios app webview rendering pdf base64str long time, about 30 minutes or longer

Generally speaking, don't use Base64 since it's a very inefficient format (from a memory perspective) and *some* browsers may even truncate long Base64-strings.
Furthermore, this kind of STR isn't enough for an issue to be actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Even ignoring that lack of any actionable information here, this fortunately doesn't seem like a valid PDF.js bug. Rather this sounds entirely like a bug in the platform/browser *itself*, and thus isn't something that we can fix even with additional details provided.

**Comment by theMxb** [comment]
Is it possible that safari cannot download the font bcmap (application/octet-stream), because safari only allows downloading images, and then it has been waiting for the response

**Comment by timvandermeij** [comment]
Not sure, but in that case it would be a platform issue and not a PDF.js one that we can fix.

**Comment by bin674160430** [comment]
I have debugged network requests in Safari, and can normally initiate font requests and responses. As a result, they will always be stuck and show that Safari is currently consuming resources.
**Both the code and the network request are running normally, which is the state Safari has been working on**
Here's the test code: 
```javascript
// CMapReaderFactory
const request = new XMLHttpRequest();
request.responseType = 'arraybuffer';
request.open('GET', 'cmaps/UniGB-UCS2-H.bcmap', true);
request.onreadystatechange = () => {
    if (request.statue === 200 || request.status === 0) {
        let cMapData;
        if (request.response) { // debuger join this
            cMapData = new Unit8Array(request.response); // request.response is ArrayBuffer byteLength: 43366
        } else if (request.responseText) {
            cMapData = (0, _util.stringToBytes)(request.responseText);
        }
    }
}
```

**Comment by theMxb** [comment]
I think after safari gets bcmap, it feels that the thread is blocked for a long time before it reacts. #7423

**Comment by theMxb** [comment]
Fetch bcmap， because some bcmap arraybuffer is very big, safari v8 processing long sequences will block threads！
You can wait patiently for the rendering results and pay attention to the loading and use of fonts.
You can use the following code to view the font.
```javascript
pdfjsLib.getDocument(param).promise.then(pdf => {
            pdf.getPage(1).then(page => {
                var canvas = document.getElementById('canvas');
                var ctx = canvas.getContext('2d');
                var viewport = page.getViewport({scale: 1});
                canvas.width = viewport.width;
                canvas.height = viewport.height;
                canvas.style.width = viewport.width + 'px';
                canvas.style.height = viewport.height + 'px';
                var renderContext = {
                    viewport: viewport,
                    canvasContext: ctx
                };
                page.getTextContent().then(res => console.log(res)); // read item ues font
                page.render(renderContext).promise.then(() => {
                    console.log('over');
                });
            })
        });
```
Solution: modify the problematic font in the pdf file

**Comment by bin674160430** [comment]
> Attach (recommended) or Link to PDF file here:
> 
> Configuration:
> 
> * Web browser and its version: ios app webview
> * Operating system and its version:
> * PDF.js version: 2.3.200
> * Is a browser extension:
> 
> Steps to reproduce the problem:
> 
> 1. pdf file use font STSong and MSung
> 2. ios app webview rendering pdf base64str long time, about 30 minutes or longer
> 
> What is the expected behavior? (add screenshot)
> 
> What went wrong? (add screenshot)
> 
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

look, version is 2.3, please update to 2.5 and above.
e.g: 2.5.207, 2.6.347
### Error when the code is running, e.g.
**1. this.fontLoader.bind(font).catch(...).finally is not a function.
2. Promise.allSettled is not a function**
update you project node_modules/**zone.js** pkg

**Comment by theMxb** [comment]
You can also use the following code to deal with the compatibility of pdf used promises
```javascript
(function() {
	// Get a handle on the global object
	var local;
	if (typeof global !== 'undefined') local = global;
	else if (typeof window !== 'undefined' && window.document) local = window;
	else local = self;

	// It's replaced unconditionally to preserve the expected behavior
	// in programs even if there's ever a native finally.
	local.Promise.prototype['finally'] = function finallyPolyfill(callback) {
		var constructor = this.constructor;

		return this.then(function(value) {
				return constructor.resolve(callback()).then(function() {
					return value;
				});
			}, function(reason) {
				return constructor.resolve(callback()).then(function() {
					throw reason;
				});
			});
    };
    
    local.Promise.prototype['allSettled'] = function allSettledPolyfill(promises) {
        return new Promise(function(resolve, reject) {
            if (!Array.isArray(promises)) {
                return reject(
                    new TypeError("arguments must be an array")
                );
            }
            let resolveCounter = 0;
            const promiseNum = promises.length;
            const resolvedResults = new Array(promiseNum);
            for (let i = 0; i < promiseNum; i++) {
                Promise.resolve(promises[i]).then(
                    function(value) {
                        resolveCounter++;
                        resolvedResults[i] = value;
                        if (resolveCounter == promiseNum) {
                            return resolve(resolvedResults);
                        }
                    },
                    function(reason) {
                        resolveCounter++;
                        resolvedResults[i] = value;
                        if (resolveCounter == promiseNum) {
                            return resolve(resolvedResults);
                        }
                    }
                );
            }
        });
    }
}());
```

**Comment by iysf** [comment]
> I have debugged network requests in Safari, and can normally initiate font requests and responses. As a result, they will always be stuck and show that Safari is currently consuming resources.
> **Both the code and the network request are running normally, which is the state Safari has been working on**
> Here's the test code:
> 
> ```js
> // CMapReaderFactory
> const request = new XMLHttpRequest();
> request.responseType = 'arraybuffer';
> request.open('GET', 'cmaps/UniGB-UCS2-H.bcmap', true);
> request.onreadystatechange = () => {
>     if (request.statue === 200 || request.status === 0) {
>         let cMapData;
>         if (request.response) { // debuger join this
>             cMapData = new Unit8Array(request.response); // request.response is ArrayBuffer byteLength: 43366
>         } else if (request.responseText) {
>             cMapData = (0, _util.stringToBytes)(request.responseText);
>         }
>     }
> }
> ```

new Unit8Array  replace new Uint8Array
