### ISSUE TITLE
Add a basic typescript example

### ISSUE THREAD

**Issue by simhyr** [mozilla/pdf.js#12584]
#12403 

Thanks for the typescript-definitions! 

Could you also provide a basic typescript example? I tried different ways to import the pdfjs-dist library, but the import is typed as 'any' or fails. I tried to import it like this:

```typescript
import * as pdfjsLib from 'pdfjs-dist'; // Error: 'Could not find a declaration file for module pdfjs-dist'
let pdfjsLib = require('pdfjs-dist'); // is typed as 'any'

// this does not work at all - i think that's maybe a pretty old example
import { PDFJSStatic } from 'pdfjs-dist';
const PDFJS: PDFJSStatic = require('pdfjs-dist');
```

PS: I wasn't sure, if its enough to post it in the referenced issue thread, so i also created a new issue.

**Comment by Snuffleupagus** [comment]
Please note that the TypeScript definitions are provided on an "as-is" basis, since PDF.js is a JavaScript-project and the core contributors cannot be assumed to have (detailed) knowledge about TypeScript.

Hence all of the work required to both implement and *importantly* help maintain the TypeScript definitions, will thus have to be done by those who know/use TypeScript themselves :-)

**Comment by simhyr** [comment]
Thanks for your reply! Actually both of the imports work. It was an issue with my Visual Studio Code... Once i have a "real-world"-typescript example, i will create a pull-request :-)

```typescript
import { getDocument } from "pdfjs-dist"; // does work

import * as pdfjs from "pdfjs-dist"; // does work
pdfjs.getDocument(..)
```

**Comment by maclonghorn** [comment]
@simhyr Did you create a PR for the real-world example?  I'm having issues with building with Angular.

**Comment by severinbeauvais** [comment]
The following works.
- pdfjs-dist v3.5.141
- typescript v3.9.10

```
import * as pdfjsLib from 'pdfjs-dist/webpack'

...

    // in this example, data is a Uint8Array
    const pdf = await pdfjsLib.getDocument({ data }).promise
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
      const page = await pdf.getPage(pageNum)
      ...
```

**Comment by vicpara** [comment]
and for nodejs?

**Comment by v29neil** [comment]
Any Node js + typescript integration example please
