### ISSUE TITLE
getTextContent() has invalid characters for Calibri font style

### ISSUE THREAD

**Issue by Veeresh870** [mozilla/pdf.js#12581]
Hi,

Normally, getTextContent() puts strings together into an item of an array. I have a case now for two PDFs where i am getting some characters missing & instead getting invalid characters like '\u0000' character. It is happening when i am using font style of Calibri only. But mean while on browser it is being rendered absolutely fine.
Unfortunately, the PDF has personal financial data of a user so I can't provide it here but below are screenshots, showing the problem.

Configuration:

Web browser and its version: Latest Chrome
Operating system and its version: (tested on ubuntu 18.04)
PDF.js version: "pdfjs-dist": "^2.5.207"

Steps to reproduce the problem:

This is how text is extracted: 
```

const PDFJs = require('pdfjs-dist/es5/build/pdf');

let searchPage = (doc, toc, pageNumber = null) => {
    return new Promise((resolve, reject) => {

        let totalPages = doc.numPages, breakLoop = false, searchResult, isFound = false, text,

            re = new RegExp(Helper.escapeRegExp(toc.text), "gi");

        pageNumber = pageNumber === null ? 4 : pageNumber;

        if (pageNumber > totalPages) {
            return resolve();
        }

        Async.until((searchCallback) => {
            searchCallback(null, breakLoop);
        }, (pageNext) => {
            doc.getPage(pageNumber).then(function (page) {
                return page.getTextContent();
            }).then(function (content) {
                // Search combined text content using regular expression
                text = content.items.map(function (i) {
                    return i.str;
                }).join('');

                searchResult = re.exec(text);

                if ((isFound = searchResult !== null) || pageNumber === totalPages) {
                    breakLoop = true;
                    pageNext();
                } else {
                    pageNumber++;
                    pageNext();
                }
            });
        }, (err) => {
            if (err) {
                return reject(error);
            }

            if (isFound) {
                toc.pageNumber = pageNumber;
            } else {
                Logger.log(Logger.warning('Not Found: ' + toc.text));
            }
            resolve();
        });
    });

```

What is the expected behavior? (add screenshot)

![Screenshot from 2020-11-05 09-25-42](https://user-images.githubusercontent.com/73984293/98209362-c78c8d80-1f64-11eb-992a-1c9e9d006a6e.png)

What went wrong? (add screenshot)

![Screenshot from 2020-11-05 09-24-29](https://user-images.githubusercontent.com/73984293/98209387-d2472280-1f64-11eb-833d-32e613ead5d7.png)

Thanks for any advice!

**Comment by Snuffleupagus** [comment]
> Unfortunately, the PDF has personal financial data of a user so I can't provide it here but below are screenshots, showing the problem.

Access to a test-case is absolutely vital, and a requirement for any issue to be actionable/valid; without a test-case there's no choice but to close this as INCOMPLETE.
Furthermore, unfortunately it's simply *impossible* to do debug a font issue (or anything else really) with only a screen-shot.

> This is how text is extracted:
> [...]

Code-snippets are generally of no use, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Veeresh870** [comment]
[report-pages-3,9 (1).pdf](https://github.com/mozilla/pdf.js/files/5495204/report-pages-3.9.1.pdf)

Please find the above attached pdf..
code snippet :

const PDFJs = require('pdfjs-dist/es5/build/pdf');
let pageNumber = 1;
```
PDFJs.getDocument(data.reportPath).promise.then(async (doc) => { 
       doc.getPage(pageNumber).then(function (page) {
                return page.getTextContent();
            }).then(function (content) {
                // Search combined text content using regular expression
                text = content.items.map(function (i) {
                    return i.str;
                }).join('');
            console.log(text);
            });
});
```

**Comment by Snuffleupagus** [comment]
Unfortunately this is a bug in the PDF document *itself*, rather than in the PDF.js library, since the fonts in question contain incomplete /ToUnicode data and text-selection/copying thus cannot work as you expect. Please note that this is similarly broken in other PDF viewers as well, e.g. Adobe Reader and PDFium/Google Chrome.

Basically, without the PDF document *itself* containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.
