### ISSUE TITLE
Webpack 5 Environment Support

### ISSUE THREAD

**Issue by baylesa-dev** [mozilla/pdf.js#12586]
Attach (recommended) or Link to PDF file here:

Configuration:
- Operating system and its version: macOS Catalina 10.15.7 (19H2)
- PDF.js version: 2.5.207

I'm unable to use pdfjs-dist lib in a Webpack 5 / React environment, when I import pdfjs-dist/webpack.

I got the following errors:
```bash
ERROR in ../../node_modules/jest-worker/build/workers/ChildProcessWorker.js 9:15-39

Module not found: Error: Can't resolve 'child_process' in 'node_modules/jest-worker/build/workers'
...
ERROR in ../../node_modules/jest-worker/build/workers/NodeThreadsWorker.js 29:15-40

Module not found: Error: Can't resolve 'worker_threads' in 'node_modules/jest-worker/build/workers'
...
ERROR in ../../node_modules/worker-loader/dist/index.js 46:27-84

Module not found: Error: Can't resolve 'webpack/lib/web/FetchCompileWasmTemplatePlugin' in 'node_modules/worker-loader/dist'
```

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> I'm unable to use pdfjs-dist lib in a Webpack 5 / React environment,

Please note that we don't really know anything about the React framework here.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
