### ISSUE TITLE
Feature to show Search Results Sidebar

### ISSUE THREAD

**Issue by guilhermefacanha** [mozilla/pdf.js#12587]
### Feature Question
I'm searching for a feature to show search results in a side bar just like in DocketAlarm

Do we have any extension or open source project who address this feature?
![image](https://user-images.githubusercontent.com/1631375/98279602-ff88d600-1f4e-11eb-921e-8703fbe3a6c6.png)

If not whats the best strategy to implement it? We already have thumbnails, layers sidebar.
Where could I start to create my own?

Really appreciate all the help.

**Comment by Snuffleupagus** [comment]
Given that searching, in Firefox, uses the native browser findbar it's somewhat unclear if/how something like this could even be implemented in a generally consistent way. Most likely, this won't be added to the default viewer as far as I can see.

**Comment by timvandermeij** [comment]
I recall having seen a similar issue reported before, but I can't seem to find it. In any case, this functionality does not exist in the default viewer, and most likely won't be added either, but as said I do recall another project based on PDF.js implementing this functionality. It can probably be implemented by adding a new sidebar (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_sidebar.js) and by integrating the results from the find controller (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js).

**Comment by guilhermefacanha** [comment]
> I recall having seen a similar issue reported before, but I can't seem to find it. In any case, this functionality does not exist in the default viewer, and most likely won't be added either, but as said I do recall another project based on PDF.js implementing this functionality. It can probably be implemented by adding a new sidebar (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_sidebar.js) and by integrating the results from the find controller (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js).

Thanks a lot.
That’s already good info on where to start
