### ISSUE TITLE
Strange input field behavior in Safari

### ISSUE THREAD

**Issue by astehlik** [mozilla/pdf.js#12592]
Attach (recommended) or Link to PDF file here: 
[pdf_form_error_test.pdf](https://github.com/mozilla/pdf.js/files/5500961/pdf_form_error_test.pdf)

Configuration:
- Web browser and its version: Safari versions 13.1 and older
- Operating system and its version: Mac Catalina and iOS (tested with 11 to 14)
- PDF.js version: Current Demo version

Steps to reproduce the problem:
1. Open the attached PDF in Safari (or Chrome on iOS)
2. Try entering a value in the right form field

What is the expected behavior?
When clicking the right field it should be activated.

What went wrong?
The left field ist activated. There is no way to enter a value in the right field.

![safari_bug-2020-11-06_12 09 47](https://user-images.githubusercontent.com/956513/98360675-8494ed80-202a-11eb-9713-d54ac3252cd8.gif)

I did some testing with the Console: when I set a value to the right field using JavaScript I can activate the field and edit the value. But then I can not select the left field any more.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html?file=https://www.intera.de/fileadmin/pdftest/pdf_form_error_test.pdf

**Comment by Snuffleupagus** [comment]
WFM, when using either: Firefox Nightly 84.0a1 or Google Chrome 87.0.4280.47, on Windows.

Unfortunately this sounds like a platform/browser bug, rather than a PDF.js one, and as such it's really quite difficult to see that it's something that can be fixed here.

**Comment by astehlik** [comment]
@timvandermeij Thanks for the feedback. I'm also thinking it's a browser bug but IMO before I can report a Safari bug I need to find out what exactly is breaking.

I tried reproducing the behavior by building a static HTML page using exactly the same HTML / CSS that is generated by PDF.js (without the JavaScript). The fields behaved normally.

So my conclusion is that is has to be related to the JavaScript of PDF.js. Can you point me to the JS that is related to the annotation overlay so I can dig a little deeper and hopefully find the Code that is breaking?

Cheers
Alex

**Comment by timvandermeij** [comment]
The fields are text widget annotations, for which the display (rendering) code lives here: https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L462-L575

**Comment by cetinsert** [comment]
> The fields are text widget annotations, for which the display (rendering) code lives here: https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L462-L575

@timvandermeij wow, the way you treat this issue and #13191 is unfortunate. Also please provide permanent links:

- https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L462-L575 ❌ (lines no longer match)
- https://github.com/mozilla/pdf.js/blob/v2.7.570/src/display/annotation_layer.js#LXXX-LXXX ✔ (notice **v2.7.570**)

**Comment by Snuffleupagus** [comment]
> The way you treat this issue and #13191 is unfortunate.

Please keep in mind that this is a project run by Mozilla, and that the *main purpose* of this library existing is to develop the built-in PDF Viewer in Firefox.
Hence other browsers, while we attempt to support them where reasonable/feasible, isn't the main focus of development efforts. (And in this case, it does appear to be a browser-specific bug.)

Furthermore, please also note that we ask that you don't just re-use the demo viewer as-is; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by cetinsert** [comment]
@Snuffleupagus thank you for clarifying the position. I will try to come up with a solution for Safari requiring a minimal set of changes over the weekend myself.

> Furthermore, please also note that we ask that you don't just re-use the demo viewer as-is; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):

I am not using your viewer anywhere &ndash; in fact I find viewers altogether (not just the PDF.js one) too coarse an abstraction.

You are posting this very prominently under every issue. What is the reasoning? You don't want to be associated with the UX of a viewer not maintained directly by Mozilla?

**Comment by Snuffleupagus** [comment]
> I will try to come up with a solution for Safari requiring a minimal set of changes over the weekend myself.

As mentioned elsewhere, to *improve* the chances of getting something like that getting accepted, try limiting the changes to code placed in only [src/shared/compatibility.js](https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js) if possible.

Note also that we always try to use actual feature-detection, and that a solution requiring e.g. checking the userAgent is *very unlikely* to be accepted.

> What is the reasoning? You don't want to be associated with the UX of a viewer not maintained directly by Mozilla?

Exactly; we don't want third-party implementations of the demo-viewer to be easily mistaken for the *built-in* Firefox PDF Viewer.
Some of the reasons for this are:
 - While the Firefox PDF Viewer is updated *regularly*, that probably doesn't apply to most third-party ones. This means that bugs which are fixed, in some cases years ago, are still present in many third-party viewers.
 - It increases user confusion and thus the support burden for the PDF.js project, when people mistake a third-party viewer for the *built-in* Firefox PDF viewer.
