### ISSUE TITLE
Reference Error on Android globalThis is not defined 

### ISSUE THREAD

**Issue by konlikha** [mozilla/pdf.js#12596]
Attach (recommended) or Link to PDF file here:
it
Configuration:
- Web browser and its version: Chrome 62.0.3202 and 70.0.3538
- Operating system and its version: Android 10 & Android 8.1
- PDF.js version: 2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
1. Try to load a file pdfjsLib.getDocument

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

When tried to open a file using select the window gets crashed. I use sentry for my web app and this was the error :

`/ajax/libs/pdf.js/2.6.347/pdf.min.js in Object.getDocument at line 22:28889`
`ReferenceError Object.getDocument(ajax/libs/pdf.js/2.6.347/pdf)
error
globalThis is not defined`

sentry provided the log of Object.getDocument at:

`{snip} leFontFace||!1);void 0===n.ownerDocument&& (n.ownerDocument=globalThis.document);"boolean"!=typeof` n.disableRange&&(n.disableRange=!1);"boole {snip}`

and in script at 

pdfjsLib.getDocument

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
this is my website https://ecutter.web.app try to select a file in

**Comment by Snuffleupagus** [comment]
It sounds like you should be using an ES5-compatible build, since those include polyfills for functionality missing in older browsers (e.g. `globalThis`); see https://mozilla.github.io/pdf.js/getting_started/#download

> this is my website https://ecutter.web.app try to select a file in

Unfortunately that's way too large and complex example to be helpful; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by konlikha** [comment]
@Snuffleupagus Thank you so much for your kind reply. Problem solved.

**Comment by halloayu** [comment]
@konlikha how to resolve this issue?
