### ISSUE TITLE
Error reading PDF "Bits per component missing in image: false" - works on other readers.

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#12597]
Attach (recommended) or Link to PDF file here:

I can't attach the PDF as it's on copyrighted PDF but I could email it to the team privately.

I'm burton _at_ getpolarized dawt eye oh (spam prevention)

Configuration:
- Web browser and its version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
- Operating system and its version: MacOS 10.15.6
- PDF.js version: PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.7.250)
- Is a browser extension: no

Steps to reproduce the problem:
1. just load the PDF

What is the expected behavior? (add screenshot)

it should render the pages properly.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by janpe2** [comment]
I did some tests. Acrobat Reader accepts a missing `BitsPerComponent` entry only in `JPXDecode` (i.e. JPEG-2000) images. Chrome accepts it in `DCTDecode`, `CCITTFaxDecode`, and `JBIG2Decode`.

You mentioned that the PDF works on other viewers. Do you mean also Acrobat Reader?

**Comment by Snuffleupagus** [comment]
Given the lack of a *publicly* available test-case, and that there's apparently not been *any* follow-up to the question asked in https://github.com/mozilla/pdf.js/issues/12597#issuecomment-735796946, I'd suggest closing this issue as INCOMPLETE for now.
