### ISSUE TITLE
Any way to export pdf to separated SVGs?

### ISSUE THREAD

**Issue by fzlee** [mozilla/pdf.js#12603]
Hi team:
 I am working on a project in which we need to export elements on pdf to separated svgs.

say we have a pdf, in which we have a line, a rect and an ellipse. I want to get three svgs.

The following example could export pdf to a single svg, which is not expected:

```
var svgGfx = new pdfjsLib.SVGGraphics(page.commonObjs, page.objs);
          svgGfx.embedFonts = true;
          return svgGfx.getSVG(opList, viewport).then(function (svg) {
            return writeSvgToFile(svg, getFilePathForPage(pageNum)).then(
              function () {
                console.log("Page: " + pageNum);
              },
              function (err) {
                console.log("Error: " + err);
              }
            );
          });
```

**Comment by timvandermeij** [comment]
PDF.js does not have this functionality, nor will it be useful for most people. Moreover, the SVG back-end is experimental and not production-ready yet.
