### ISSUE TITLE
PDF not rending/showing with some mobile browsers (Xiaomi Mi Browser, Samsung Internet Browser, ...)

### ISSUE THREAD

**Issue by CanalComercio** [mozilla/pdf.js#12601]
Attach (recommended) or Link to PDF file here:
https://canalcomercio.es/oferta/contigo/contigo-tenerife-comida-saludable#menu You can see the pdf here. Attached is the pdf.

![image](https://user-images.githubusercontent.com/35999736/98528031-a503b880-2273-11eb-9df9-be91975b1aec.png)

Configuration:
- Web browser and its version:
Happens with two different system that we tested:
-> Xiaomi mix s2 with MIUI 12.0.1 and MI Browser 12.X
-> Samsung S 10 with Samsung Internet Browser

- Operating system and its version: Android 10
- PDF.js version: 2.7.256 (loading from https://mozilla.github.io/pdf.js/build/pdf.js)
- Is a browser extension: NO

Steps to reproduce the problem:
1. Visit the think below with any of the devices listed before (in our tests we use the browser embeded in the QR code reader from the phone, that opens the mobile's browser)

What is the expected behavior? (add screenshot)
The pdf is shown
![image](https://user-images.githubusercontent.com/35999736/98527236-ac769200-2272-11eb-97d7-b8f39fd3e4fa.png)

What went wrong? (add screenshot)
The pdf is not shown
![image](https://user-images.githubusercontent.com/35999736/98529135-30ca1480-2275-11eb-93a1-0be29b4a0c1d.png)

I don't have the browser logs for this or the exact version of the browser, but I'll try to collect the files and posted. This seems to happen to modern in browser mobile.

**Comment by Snuffleupagus** [comment]
> https://canalcomercio.es/oferta/contigo/contigo-tenerife-comida-saludable#menu You can see the pdf here. Attached is the pdf.

That seems to link to an HTML page, rather than *directly* to a PDF file (it's somewhat difficult to navigate that page if you don't speak, what looks like, Spanish). Please make sure that you always attach the actual PDF file *here*.

Also, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Web browser and its version:
>       Happens with two different system that we tested:
>       -> Xiaomi mix s2 with MIUI 12.0.1 and MI Browser 12.X
>       -> Samsung S 10 with Samsung Internet Browser

Did you test with any other, more "standard", browsers such as e.g. Firefox and/or Chrome?

Please note that it's much more likely that this is an issue with the platform/browser *itself*, rather than the PDF.js library, and as such it's unfortunately difficult to see that there's much that can be done about this here.

**Comment by CanalComercio** [comment]
Hi,

Here is the pdf version of the file: https://canalcomercio.es/ServidorDocumentos/0/OFERTAS/2493/20201029083333786CONTIGO2convertido.pdf

This doesn't seems to be related to the PDF itself, it's about the pdf.js and how it's shown and the browser Miui Browser and other mobile

I've tested viewing the code with this phone and used the chrome debugger:
=> https://www.whatsmybrowser.org/b/LLMHZ
=> Miui Browser 71 - V12.4.1-g

Code snippet:
 <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    <script type="text/javascript">

        // Javascript to enable link to tab
        var url = document.location.toString();
        if (url.match('#')) {
            if ($('a[href="#' + url.split('#')[1]).length) {
                $('a[href="#' + url.split('#')[1]).tab('show');
            }
        }
           var loadingTask = pdfjsLib.getDocument($('.url_pdf').text());


            var thePdf = null;

        loadingTask.promise.then(function(pdf) {
            thePdf = pdf;

Failure occurs in the getDocument.

Uncaught SyntaxError: Unexpected token .    pdf.js:2370
Line is pdf.js:2370:
File: <unsaved>
2354:     if (!intentState.displayReadyCapability) {
2355:       intentState.displayReadyCapability = (0, _util.createPromiseCapability)();
2356:       intentState.operatorList = {
2357:         fnArray: [],
2358:         argsArray: [],
2359:         lastChunk: false
2360:       };
2361: 
2362:       if (this._stats) {
2363:         this._stats.time("Page Request");
2364:       }
2365: 
2366:       this._pumpOperatorList({
2367:         pageIndex: this._pageIndex,
2368:         intent: renderingIntent,
2369:         renderInteractiveForms: renderInteractiveForms === true,
2370:         annotationStorage: annotationStorage?.getAll() || null
2371:       });
2372:     }
2373: 
2374:     const complete = error => {
2375:       const i = intentState.renderTasks.indexOf(internalRenderTask);
2376: 
2377:       if (i >= 0) {
2378:         intentState.renderTasks.splice(i, 1);
2379:       }
2380: 
2381:       if (this.cleanupAfterRender || renderingIntent === "print") {
2382:         this.pendingCleanup = true;
2383:       }
2384: 
2385:       this._tryCleanup();

seems to fail to load the document in annotationStorage.  My code loads the documents  perfectly for mozilla/chrome and any other browser (even in phone). Failure is related to Mi UI Browser with the version stated before.

**Comment by timvandermeij** [comment]
> annotationStorage: annotationStorage?.getAll() || null

This line uses optional chaining, and it looks like your browser doesn't support that. This means you're using the non-ES5 version of PDF.js in a ES5-only browser, so you should switch to the ES5 build instead.

> <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>

Never link to this URL directly since it changes on every push to master and may be broken. Either use a CDN (see https://github.com/mozilla/pdf.js#including-via-a-cdn) or host the file yourself.
