### ISSUE TITLE
Question: Can this library not be used from Node.js?

### ISSUE THREAD

**Issue by siddjain** [mozilla/pdf.js#12606]
Hello,

I just have a question. Can this library not be used from Node.js? I get this error when trying to open a PDF file

The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead.

my code:

```
const pdfjsLib = require('pdfjs-dist');
const fs = require('fs');
const pdfPath = 'test.pdf';
const data = fs.readFileSync(pdfPath);
var loadingTask = pdfjsLib.getDocument({data: data});
loadingTask.promise
```

**Comment by timvandermeij** [comment]
It's most definitely possible since we have examples of this in the `examples` folder. The key is that you use the ES5 build as indicated in the error; see

https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js#L17
