### ISSUE TITLE
https://mozilla.github.io/pdf.js/es5/web/viewer.html doesn't work in IE 11

### ISSUE THREAD

**Issue by IanKemp** [mozilla/pdf.js#12602]
I'm aware you plan to nuke IE11 support after 2.6.347 but that version is still in prerelease.

Configuration:
- Web browser and its version: Internet Explorer 11 (11.572.19041.0 / 11.0.210)
- Operating system and its version: Windows 10 2004 (19041.572)
- PDF.js version: whatever version is being used at https://mozilla.github.io/pdf.js/es5/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. Browse to https://mozilla.github.io/pdf.js/es5/web/viewer.html in IE11
2. It doesn't work

What is the expected behavior? (add screenshot): It works

What went wrong? (add screenshot): JavaScript error

SCRIPT1002: Syntax error
pdf.js (33,21)

SCRIPT1002: Syntax error
viewer.js (23,14)

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. ***However, this support will be dropped after stable version `2.6.347`.***

**Comment by IanKemp** [comment]
> Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> 
> > While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. _**However, this support will be dropped after stable version `2.6.347`.**_

Please try reading my report instead of posting canned autoreplies.

**Comment by Snuffleupagus** [comment]
> I'm aware you plan to nuke IE11 support after 2.6.347 but that version is still in prerelease.
> [...]
> Browse to https://mozilla.github.io/pdf.js/es5/web/viewer.html in IE11

That demo, as of this writing, uses PDF.js version `2.7.256` which is a *higher* version number than the last one with IE11 support; hence it's not expected to work unfortunately.

**Comment by IanKemp** [comment]
> > I'm aware you plan to nuke IE11 support after 2.6.347 but that version is still in prerelease.
> > [...]
> > Browse to https://mozilla.github.io/pdf.js/es5/web/viewer.html in IE11
> 
> That demo, as of this writing, uses PDF.js version `2.7.256` which is a _higher_ version number than the last one with IE11 support; hence it's not expected to work unfortunately.

Thank you, that is the information I was looking for.

I suggest that the README be updated to note that the demos are built against the latest version of master (which I assume 2.7.256 is), as opposed to the latest stable version (which was my assumption).
