### ISSUE TITLE
Text selected migration

### ISSUE THREAD

**Issue by liuyuze** [mozilla/pdf.js#12609]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: All browsers
- Operating system and its version: win10
- PDF.js version: v2.6.347
- Is a browser extension:

Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/10252397/98918487-a39eee00-2508-11eb-83ab-3a612f4df62f.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is missing *required* information and will thus be closed as INCOMPLETE.
