### ISSUE TITLE
PDF selected cursor migration

### ISSUE THREAD

**Issue by liuyuze** [mozilla/pdf.js#12615]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome 76.0.3809.100
- Operating system and its version:win10
- PDF.js version:2.5.207
- Is a browser extension:no

Steps to reproduce the problem:
1. downdoad https://pdf.dfcfw.com/pdf/H2_AN202006051382572832_1.pdf
2. open pdf file with https://mozilla.github.io/pdf.js/web/viewer.html
3. Use the mouse to select a text
What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/10252397/99042962-934e4800-25c8-11eb-8f38-5d9e65dbab3f.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/10252397/99042844-68fc8a80-25c8-11eb-8a00-df436c6b286d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):none

I replace 
![image](https://user-images.githubusercontent.com/10252397/99043831-c6dda200-25c9-11eb-9861-70b00f1e057b.png)
text_layer.js
line 83
    if (style.ascent) {
      fontAscent = style.ascent * fontAscent;
    } else if (style.descent) {
      fontAscent = (1 + style.descent) * fontAscent;
    }

with 
![image](https://user-images.githubusercontent.com/10252397/99043869-d4932780-25c9-11eb-8577-d2da2349b65e.png)
    /*********************************/
    var cent = 0;
    if(style.ascent){
        cent+=style.ascent;
    } 
    if (style.descent) {
        cent+=style.descent;
    }
    fontAscent = cent * fontAscent;
    /*********************************/
can fix this bug

Is it right for me to do this？

**Comment by asbaghel** [comment]
I can fix this issue

**Comment by VinGuler** [comment]
@asbaghel 
How?
Or is it that the margins of this page are to thin for the solution?

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.
