### ISSUE TITLE
[Chrome] - Printing pdf with different size pages results in page split 

### ISSUE THREAD

**Issue by cycnos** [mozilla/pdf.js#12611]
Attach (recommended) or Link to PDF file here:
[KO_print.PDF](https://github.com/mozilla/pdf.js/files/5530109/KO_print.PDF)

Configuration:
- Web browser and its version: Chrome 86.0.4240.183
- Operating system and its version: Windows 10 
- PDF.js version: 2.7.262 (current one here: https://mozilla.github.io/pdf.js/web/viewer.html) 
- Is a browser extension: no

Steps to reproduce the problem:
1. open KO_print.PDF 
2. click on print button (you will see that the preview has 4 pages instead of 2) 
3. print as pdf and see the result (it is like the preview but wrong compared to initial pdf) 

What is the expected behavior? (add screenshot)
The printed pdf should looks like KO_print.PDF

What went wrong? (add screenshot)

The printed pdf has 4 pages (the second page is split in three parts which have the same format as the first page) 
You can see the result in 
[KO_print_chrome.PDF.pdf](https://github.com/mozilla/pdf.js/files/5530153/KO_print_chrome.PDF.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by cycnos** [comment]
Hello, 

Is there any updates about this ? Did you manage to reproduce it ? 

Can I help in any way? 

Maybe if you can guide me about the part of the project to look at I can try to help by contributing 

Best regards

**Comment by cycnos** [comment]
Hi, 

issue seems to be solved by #13120. Therefore you can close it :)

**Comment by timvandermeij** [comment]
Thank you for letting us know!
