### ISSUE TITLE
Doc.info in scripting API being currently implemented is not spec-compliant

### ISSUE THREAD

**Issue by AdobeScripter** [mozilla/pdf.js#12619]
Don't get me wrong, it's great that @calixteman wanted to implement that — JS should definitely be supported! I don't want to come off as rude or attacking.

For starters, JS reference specified in the [commit comment](https://github.com/mozilla/pdf.js/commit/8de98079ca05f8f7001ee077771055a57dc0e948) is outdated. It's version 8.1 from 2007… We're more than decade past that now. We should be implementing [Acrobat DC SDK](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/AcrobatDC_js_api_reference.pdf) ([here](https://help.adobe.com/en_US/acrobat/acrobat_dc_sdk/2015/HTMLHelp/#t=Acro12_MasterBook%2FJS_API_AcroJS%2FJavaScript_API.htm) in a nice HTML version).

Other than that, the Doc object now is only implemented with `info` property with standard fields (`Title`, `Author`, `Subject`, `Keywords`, `Creator`, `Producer`, `CreationDate`, `ModDate` and `Trapped`, case insensitive). But [according to the spec](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/AcrobatDC_js_api_reference.pdf#page=243) (even [in that old version](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/js_api_reference.pdf#page=243)), this object can contain other, non-standard properties, that can be set both in Acrobat interface and in JS (which are case-sensitive then).

Acrobat 9.0 introduced another field to that property, `Authors`, containing semicolon-delimited list of authors.

There are probably other problems with that code due to the outdated spec @calixteman was apparently working on.

**Comment by calixteman** [comment]
@AdobeScripter thanks for pointing out the correct specifications to use.
Anyway, we focus on having conformance with Adobe Reader so for now `doc.info` will stay read-only, but feel free to file a bug to ask for this feature.

**Comment by AdobeScripter** [comment]
Even if it is read-only, the non-standard fields should be read from the PDF file and provided in that property. And there is still the `Authors` field that is missing.

**Comment by AdobeScripter** [comment]
I'm sorry to ask here, since it's not completely on the topic, but on the other hand I don't really want to create a new issue just for this question, so I'll just go with it.

When do you plan to release first version (embedded in Firefox) to support JavaScript?

**Comment by timvandermeij** [comment]
The `master` branch is synced periodically with Firefox upstream (every week or so), so it should already be in a Firefox Nightly release, albeit disabled by default with a preference.

**Comment by calixteman** [comment]
It isn't available for now in Firefox: we're still waiting for a review.

**Comment by AdobeScripter** [comment]
I have downloaded Firefox Nightly and enabled scripting support in
about:config, but I haven't managed to get any JS button to work. I suppose
it's a topic for a new issue though.

niedz., 14 lut 2021 o 15:16 mozilla/pdf.js -
reply+arqbek7j5h3nkbirhgknttf6gui4levbnhhcyrfg4u(a)reply.github.com <
ra+evyrnvrtpjhqezclpxvaxarsnnanzulduhgc@simplelogin.co> napisał(a):
