### ISSUE TITLE
Part of the Chinese character cannot be rendered

### ISSUE THREAD

**Issue by YeeJone** [mozilla/pdf.js#12629]
Attach (recommended) or Link to PDF file here:  [pdf link](https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf)

Configuration:
- Web browser and its version: chrome 86.0.4240.193
- Operating system and its version: macOS 10.13.6
- PDF.js version: 2.5.207
- Is a browser extension: -

Steps to reproduce the problem:
1. use the getDocument api to render the pdf
2. getDocument options:   
```
{  
    url: 'https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf' 
    cMapUrl: 'https://unpkg.com/browse/pdfjs-dist@2.6.347/cmaps/',
    cMapPacked: true
}
```

What is the expected behavior? (add screenshot)
 expect render normal

![image](https://user-images.githubusercontent.com/20400822/99236142-c3e4ea80-2831-11eb-8aac-074f3f9bcbfb.png)
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/20400822/99236182-d19a7000-2831-11eb-9422-77c3661d638f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
no

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: [pdf link](https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf)

WFM, using PDF.js 2.7.262 in Firefox Nightly 84.

> getDocument options: `{url: 'https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf' : 'https://unpkg.com/browse/pdfjs-dist@2.6.347/cmaps/',cMapPacked: true} `

Huh, that is definitely not a valid JavaScript object and trying to run that is guaranteed to result in an Error.
More generally though, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by YeeJone** [comment]
```Warning: Unknown type 1 charstring command of "0"```  
As a user, how do I know this situation? I want to set some fallback...

**Comment by YeeJone** [comment]
> > Attach (recommended) or Link to PDF file here: [pdf link](https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf)
> 
> WFM, using PDF.js 2.7.262 in Firefox Nightly 84.
> 
![image](https://user-images.githubusercontent.com/20400822/99248631-bafd1480-2843-11eb-98d3-5e9a42c8af3e.png)
But... it isn't work on my browser(82.0.3)
> > getDocument options: `{url: 'https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf' : 'https://unpkg.com/browse/pdfjs-dist@2.6.347/cmaps/',cMapPacked: true} `
> 
> Huh, that is definitely not a valid JavaScript object and trying to run that is guaranteed to result in an Error.
> More generally though, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
sorry... I have corrected it..  
```Warning: Unknown type 1 charstring command of "0"```
how do I know this situation? I want to set some fallback...
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> But... it isn't work on my browser(82.0.3)

The screen-shot suggests a completely different set of errors, since it appears that invalid PDF data was loaded (possibly a server issue).

> `Warning: Unknown type 1 charstring command of "0"`
> how do I know this situation? I want to set some fallback...

That warning is *not* relevant to the errors you're seeing.

Once more: Without a *runnable* example no additional help can/will be provided here!

**Comment by YeeJone** [comment]
> > But... it isn't work on my browser(82.0.3)
> 
> The screen-shot suggests a completely different set of errors, since it appears that invalid PDF data was loaded (possibly a server issue).
> 
> > `Warning: Unknown type 1 charstring command of "0"`
> > how do I know this situation? I want to set some fallback...
> 
> That warning is _not_ relevant to the errors you're seeing.
> 
> Once more: Without a _runnable_ example no additional help can/will be provided here!  

sorry, we are choosing a plan, so there is not yet an accessible link...  we only tested locally.  
I found a strange phenomenon:  when ```cMapUrl``` is a CDN address, there will be problems, like this:
```
{
      cMapPacked: true,
      cMapUrl: "https://unpkg.com/browse/pdfjs-dist@2.6.347/cmaps/",
      disableAutoFetch: false,
      disableFontFace: false,
      disableRange: false,
      disableStream: false,
      docBaseUrl: "http://localhost:8888/web/viewer.html?file=%2Fweb%2Fac8b5907e1cf5ee7cada8650bbf1082d.pdf",
      fontExtraProperties: false,
      isEvalSupported: true,
      maxImageSize: -1,
      pdfBug: false,
      url: "https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf",
      verbosity: 1
 }
```    
If you use the above options, the console will output this log.
![image](https://user-images.githubusercontent.com/20400822/99268239-d83fdc00-285f-11eb-91a5-43d122f82927.png)


When I replace cMapUrl with the **local address**, it can render normally...
```
{
      cMapPacked: true,
      cMapUrl: "../external/bcmaps/",
      disableAutoFetch: false,
      disableFontFace: false,
      disableRange: false,
      disableStream: false,
      docBaseUrl: "http://localhost:8888/web/viewer.html?file=%2Fweb%2Fac8b5907e1cf5ee7cada8650bbf1082d.pdf",
      fontExtraProperties: false,
      isEvalSupported: true,
      maxImageSize: -1,
      pdfBug: false,
      url: "https://zhihu-live.zhimg.com/pdf/20201112/origin/ac8b5907e1cf5ee7cada8650bbf1082d.pdf",
      verbosity: 1
 }
```  
Thank you for your reply. In my understanding, using CDN address is the same as local address
But the facts are different
so... why🤔

**Comment by Snuffleupagus** [comment]
> I found a strange phenomenon: when `cMapUrl` is a CDN address, there will be problems, like this:

That suggests that the issue could be that the CDN is returning incorrect/malformed data, which we unfortunately cannot do anything about here since the CDN is provided by a third-party.
Another possible explanation could be that you're using a CORS policy which somehow breaks the CMap-requests, and in that case you could maybe try using a *custom* [`CMapReaderFactory`](https://github.com/mozilla/pdf.js/blob/ed27fc6c5224979c5208d8889b954855dd7f47a7/src/display/api.js#L142-L145) to work-around that.

**Comment by YeeJone** [comment]
> > I found a strange phenomenon: when `cMapUrl` is a CDN address, there will be problems, like this:
> 
> That suggests that the issue could be that the CDN is returning incorrect/malformed data, which we unfortunately cannot do anything about here since the CDN is provided by a third-party.
> Another possible explanation could be that you're using a CORS policy which somehow breaks the CMap-requests, and in that case you could maybe try using a _custom_ [`CMapReaderFactory`](https://github.com/mozilla/pdf.js/blob/ed27fc6c5224979c5208d8889b954855dd7f47a7/src/display/api.js#L142-L145) to work-around that.

yep, I noticed that too  
```https://unpkg.com/browse/pdfjs-dist@2.6.347/cmaps/GBK-EUC-H.bcmap```  This url actually returned an HTML, not a ```bCmap``` resource... : )💥

So the solution is to replace cMapUrl with ```https://cdn.jsdelivr.net/npm/pdfjs-dist@2.5.207/cmaps/```
Thank you very much for your help！！😁 😬
