### ISSUE TITLE
How to parse pdf file to html img tag src for preview

### ISSUE THREAD

**Issue by allenpzx** [mozilla/pdf.js#12620]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome or mobile some browser
- Operating system and its version: unknown for client
- PDF.js version: 2.4.456
- Is a browser extension: 

Steps to reproduce the problem:
1. Target is **parse pdf and get data url into the html img tag src attribute** 
2. I got this  =>  `const pdf = await pdfjs.getDocument(pdfFile).promise; `
3. But I don't know how to get the data url to into img src.

What is the expected behavior? (add screenshot)
Target is **parse pdf and get data url into the html img tag src attribute** 

What went wrong? (add screenshot)
I don't know how to get the right data url to into img src.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The PNG example should show you how: https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png
