### ISSUE TITLE
PDF rendering fails with: bad XRef entry

### ISSUE THREAD

**Issue by fireWinters** [mozilla/pdf.js#12628]
When I was using PDF. Js, I encountered an error when Opening a file, and the error was reported as follows, but this file can be displayed normally in other open tools.

 {message: "bad XRef entry", stack: "FormatError↵    at FormatErrorClosure (http://127.…ources/script/commandSorting/pdf.worker.js:24:72)"}
message: "bad XRef entry"
stack: "FormatError↵    at FormatErrorClosure (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:512:27)↵    at Object.<anonymous> (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:516:2)↵    at __w_pdfjs_require__ (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:45:30)↵    at Object.<anonymous> (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:23875:13)↵    at __w_pdfjs_require__ (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:45:30)↵    at Object.<anonymous> (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:40111:23)↵    at __w_pdfjs_require__ (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:45:30)↵    at http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:91:18↵    at http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:94:10↵    at webpackUniversalModuleDefinition (http://127.0.0.1:8088/sofa/acs-commandcenter/resources/script/commandSorting/pdf.worker.js:24:72)"
__proto__:
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
May I ask in which version this problem was fixed? Now we also encounter the same problem. We hope to solve this problem by updating the version we use, which is 1.10.100.
I found that the solution had been given in the problem # 2388（https://github.com/mozilla/pdf.js/issues/2388）. May I ask which version was the earliest to fix this problem.
Due to privacy issues, I am very sorry that I cannot provide the PDF file in question。
Looking forward to your reply。

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information; as-is this will be closed as INCOMPLETE.

> We hope to solve this problem by updating the version we use, which is 1.10.100.

That version is more than *two years* old, and is consequently no longer supported. At this point in time, *no one* should be using a version from the `1`-branch since you're missing out on years of bug fixes, new features, and performance improvements.

The lowest supported PDF.js version, as of this writing, is `2.5.207`; please see https://mozilla.github.io/pdf.js/getting_started/#download and https://github.com/mozilla/pdf.js/releases

**Comment by fireWinters** [comment]
> When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information; as-is this will be closed as INCOMPLETE.
> 
> > We hope to solve this problem by updating the version we use, which is 1.10.100.
> 
> That version is more than _two years_ old, and is consequently no longer supported. At this point in time, _no one_ should be using a version from the `1`-branch since you're missing out on years of bug fixes, new features, and performance improvements.
> 
> The lowest supported PDF.js version, as of this writing, is `2.5.207`; please see https://mozilla.github.io/pdf.js/getting_started/#download and https://github.com/mozilla/pdf.js/releases

OK，I got it.thanks to your replay.
