### ISSUE TITLE
NUGET support?

### ISSUE THREAD

**Issue by jrichview** [mozilla/pdf.js#12640]
Would you please consider providing/maintaining a NUGET package for those of us in the Microsoft stack whose employers prefer that we not reference external CDNs?

**Comment by timvandermeij** [comment]
> [...] prefer that we not reference external CDNs

You can simply self-host a PDF.js build in that case. We won't provide more distributions as of now because the demand for them is very low and it provides additional maintenance burdens for us, especially for these relatively special cases.
