### ISSUE TITLE
Promise from render() resolves prematurely

### ISSUE THREAD

**Issue by ido50** [mozilla/pdf.js#12644]
Cannot attach pdf as it is currently private. This is a text book that also includes a relatively large amount of high resolution images. Current size is 61MB.

**Configuration:**
- Web browser and its version: Firefox 83.0, Chromium 86.0
- Operating system and its version: Arch Linux
- PDF.js version: 2.5.207
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Create a web page that loads a pdf document and displays two pages of it at a time (two canvas elements). Note that the fact that two pages are displayed does not seem to be related to the issue, at least from my tests.
2. For each page, when calling its `render()` method, store the returned promise into a variable or use `await` (I currently render both pages at the same time, but have tried to do that sequentially as well).
3. For each promise, set a resolve callback that does something, doesn't matter what.

**What is the expected behavior?**

Promise should only be resolved once the entire page is visible, including all text and images.

**What went wrong?**

Promise is resolved seconds before rendering is complete. This seems to be mostly noticeable when the page includes images, but that does not mean the promise will be resolved only before the images are rendered, they can also be resolved while the canvas has yet to finish rendering text, with cropped sentences that appear to be stuck for a while until finally being rendered.

Attached are two screenshots. You'll have to forgive me some motion blur, but I left the important parts in focus.

![Screenshot_20201120_213724](https://user-images.githubusercontent.com/80107/99843782-fe1ff600-2b69-11eb-9e6e-7158b4fff937.png)

The first screenshot shows how the pages look once both promises have resolved (notice the code that does this on the right and the actual log messages in the console on the left. In the middle, you'll see just a bit of text has been rendered, and the text is actually cutoff mid-sentence (this is Hebrew, with text going from right to left, so the last line you're seeing is actually the _last_ half of the sentence and the first half is missing).

![Screenshot_20201120_213730](https://user-images.githubusercontent.com/80107/99843791-02e4aa00-2b6a-11eb-857a-97fdb59f2011.png)

The second screenshot shows how the pages look once they actually _have_ finished rendering, which may be several seconds later.

**Other Notes:**

- In Chromium, it appears that the promises get resolved immediately, _way way_ before the pages are actually rendered.

**Comment by timvandermeij** [comment]
Without any running example there is not much we can do here to actually debug this, and it's required according to the issue template for this issue to be actionable. You don't have to use the confidential PDF file for that; perhaps there is another PDF file that can be used and that also shows the problem clearly.

**Comment by Snuffleupagus** [comment]
According to the JSDocs, the `PDFPageProxy.render` method returns a `RenderTask` and *not* regular a promise; see https://github.com/mozilla/pdf.js/blob/c88e8058707895e30abe9b91751c6ed5ffaa499f/src/display/api.js#L1127-L1134 and https://github.com/mozilla/pdf.js/blob/c88e8058707895e30abe9b91751c6ed5ffaa499f/src/display/api.js#L2774-L2806

Hence the *only* way of doing what you want here, i.e. waiting for rendering to finish, is to use `await page.render({...}).promise;` instead; see also the basic examples at https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

**Comment by ido50** [comment]
Thanks @Snuffleupagus, that seems to have solved the issue. Not sure how I missed it when reading the `render` code.
