### ISSUE TITLE
The canvas layer image shows abnormal white stripes

### ISSUE THREAD

**Issue by QM36** [mozilla/pdf.js#12650]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/5583134/-.pdf)

Configuration:
- Web browser and its version: chrome 86.0.4240.198
- Operating system and its version: macOS Catalina 10.15.7
- PDF.js version:  The latest code on the master branch
- Is a browser extension: no

Steps to reproduce the problem:
1. Clone this project and gulp server
2. Upload my pdf
![image](https://user-images.githubusercontent.com/32392850/99965300-a256a680-2dcf-11eb-9093-3f6382a40dc2.png)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/99965334-b13d5900-2dcf-11eb-854f-2acd5aaa4502.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32392850/99965403-c7e3b000-2dcf-11eb-968e-defacfaa9b92.png)

After uploading my pdf to your web demo, white stripes appear in the two rectangles. I guess there is a problem with the canvas layer. How can I solve it?

**Comment by Snuffleupagus** [comment]
WFM, in both Firefox and Google Chrome on Windows.

> Web browser and its version: chrome 86.0.4240.198
> Operating system and its version: macOS Catalina 10.15.7

This is most likely a platform, or possible `<canvas>`-related, bug in Google Chrome on MacOS; as such it's unfortunately difficult to see that this is an actionable/valid issue *here*.
