### ISSUE TITLE
Wrong display and invalid values in AP dictionary of radio button group when filled/saved

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#12654]
Attach (recommended) or Link to PDF file here:
[Subscription-tekMag.pdf](https://github.com/mozilla/pdf.js/files/5591356/Subscription-tekMag.pdf)
[Subscription-tekMag-filled-by-pdfjs.pdf](https://github.com/mozilla/pdf.js/files/5591357/Subscription-tekMag-filled-by-pdfjs.pdf)

Configuration:
- Web browser and its version: FF 83.0
- Operating system and its version: Windows 10 Pro 
- PDF.js version: 2.7.99 / 2.7.295
- Is a browser extension: yes / [no](https://mozilla.github.io/pdf.js/web/viewer.html)

Steps to reproduce the problem:
1. Open document [Subscription-tekMag.pdf](https://github.com/mozilla/pdf.js/files/5591356/Subscription-tekMag.pdf)
2. See the wrong rendered appearances
3. Choose a subscription through the radio button group (Choose your Subscription)
4. Save the document (STRG+S)

What is the expected behavior? 
![grafik](https://user-images.githubusercontent.com/12390057/100124714-4c8c0800-2e7c-11eb-9f17-ac4858032630.png)

What went wrong? 
![grafik](https://user-images.githubusercontent.com/12390057/100124767-5c0b5100-2e7c-11eb-9be8-7b2f1eae17f5.png)

Also when the file is saved the AP dictionary has invalid data and the radio button groups are not useable anymore. E.g.:

    /N << /2#20years,#2024#20issues#20(digital#20download#20only) 162 0 R>>

Looks like the name is not escaped correctly.

(The checkbox at the end has also a strange behavior (always locked when saved) - ping me, if I should open an additional issue for this one)

**Comment by ANIKET502** [comment]
Hi i wanna do work on this issue please assign it to me. Please notice this point that i came first on this issue so please do assign it to me to work.

**Comment by timvandermeij** [comment]
There is already a PR for this (see above).

**Comment by timvandermeij** [comment]
The escaping is fixed by the PR above. Please open a new issue for any remaining issues. Thanks.

**Comment by JanSlabon** [comment]
Looks like the checkbox was fixed by the same PR. I guess that the appearances are not used is an already known/reported issue/known limitation?

**Comment by timvandermeij** [comment]
Ah yes, that would be #12234, so I think everything here is either fixed or tracked in that issue.
