### ISSUE TITLE
Some image chunks not rendering in Chromium browsers

### ISSUE THREAD

**Issue by kbuckinx** [mozilla/pdf.js#12659]
Attach (recommended) or Link to PDF file here:
[Evo Tears HCP 6pp DL 2020.pdf](https://github.com/mozilla/pdf.js/files/5595660/Evo.Tears.HCP.6pp.DL.2020.pdf)

Configuration:
- Web browser and its version: Chrome 87, Edge Chromium 87
- Operating system and its version: tested on Mac OSX 10.15.7, Windows 10
- PDF.js version: 2.0.0
- Is a browser extension: no

Steps to reproduce the problem:
1. open the attached PDF in web/viewer.html
2. notice some parts of the background images are not rendering (including woman's face)

What is the expected behavior? (add screenshot)
![Screenshot 2020-11-24 at 14 50 51](https://user-images.githubusercontent.com/71509781/100208786-66276100-2f09-11eb-8719-ea43f2cf4e98.png)

What went wrong? (add screenshot)
![Screenshot 2020-11-24 at 14 49 38](https://user-images.githubusercontent.com/71509781/100208837-72132300-2f09-11eb-92ee-465e4e2b0c81.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): localhost

**Comment by Snuffleupagus** [comment]
WFM, with PDF.js `2.7.262` in Firefox Nightly 85 on Windows.

> Web browser and its version: Chrome 87, Edge Chromium 87

Most likely this is a browser-specific bug (related to e.g. `canvas` and/or hardware acceleration), rather than a PDF.js one, and as such it's unfortunately difficult to see that there's anything that can be done about it *here*.

> PDF.js version: 2.0.0

For future reference, please note that that version number has *never* existed.

**Comment by timvandermeij** [comment]
Works for me in Firefox. Like the other issue, this one is also most likely related to bugs in Chromium, see https://github.com/mozilla/pdf.js/issues/12462#issuecomment-713878908, and cannot be fixed here unfortunately.
