### ISSUE TITLE
unable to read external pdf from URL getting error ReferenceError: ReadableStream is not defined 

### ISSUE THREAD

**Issue by jatindevaniz** [mozilla/pdf.js#12651]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Without the issue template filled out, this is closed as incomplete. Use the ES5-compatible version if `ReadableStream` is not available.
