### ISSUE TITLE
Korean letters are not shown that exported from Mac Keynote

### ISSUE THREAD

**Issue by gssisaac** [mozilla/pdf.js#12657]
Attach (recommended) or Link to PDF file here:
[korean.pdf](https://github.com/mozilla/pdf.js/files/5594525/korean.pdf)

Configuration:
- Web browser and its version: Chrome 86.0.4240.198 (Official Build) (x86_64)
- Operating system and its version: MacOS Catalina 10.15.6 Beta (19G60d)
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the pdf file and render by the `page.render`.
```
 var renderContext = {
        canvasContext: context,
        viewport: viewport,
      };
      page.render(renderContext);
```

2. When it comes to using this, Korean letters are not shown.
3. But, when open by the viewer `https://mozilla.github.io/pdf.js/web/viewer.html` no problem. 

What is the expected behavior?
But it's not problem in https://mozilla.github.io/pdf.js/web/viewer.html 
<img width="100%" alt="Screen Shot 2020-11-25 at 2 05 45 PM" src="https://user-images.githubusercontent.com/4336264/100185601-8b2acc80-2f27-11eb-9afc-40c05c085875.png">

What went wrong?
But it's problem when rendering pages. I used the example
https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html

<img width="100%" alt="Screen Shot 2020-11-25 at 2 06 38 PM" src="https://user-images.githubusercontent.com/4336264/100185607-8f56ea00-2f27-11eb-881b-65ce228dbda7.png">

My goal is to create images of pages by using `page.render()` and export them.
All of PDFs from Keynotes are broken.

**Comment by gssisaac** [comment]
I wonder what difference between the two examples even though using the same pdf.js engine.

**Comment by Snuffleupagus** [comment]
Most likely the error is caused by the fact that you didn't provide the necessary cMap-parameters, see https://github.com/mozilla/pdf.js/blob/b1d3b6eb12b471af060c40a2d1fe479b1878ceb7/src/display/api.js#L138-L141
Note that there should be warning messages, in the console, informing you about missing/incorrect cMap-parameters.
