### ISSUE TITLE
Support for a pluggable function which generates the <a> tag

### ISSUE THREAD

**Issue by d01010101** [mozilla/pdf.js#12674]
I would like to have a PDF file which just calls some server's API, without loading any page (to generate a chart in another `<div>` for example). This would mean adding `onclick="return false;"` and a dynamic page id to each link.

A pluggable function which allows me to build the `<a>` tags myself would do it all. Would you find it useful if general? If not, I would modify the pdfjs sources just for my needs. My question is, where to search in such a case?

**Comment by timvandermeij** [comment]
This is not something we'd consider for the general viewer since it's a very uncommon use case. I think you're looking for link annotations, which are generated here: https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L327-L409
