### ISSUE TITLE
PDF.js v2.5.207 (build: 0974d6052) Failed to fetch

### ISSUE THREAD

**Issue by sinbadmaster** [mozilla/pdf.js#12670]
Attach (recommended) or Link to PDF file here: [**http://admin.gaokao8.com/dist/api/public/upload/20201118/5f0d1534a05864b62ccc647d3e4d166f.pdf**](http://admin.gaokao8.com/dist/api/public/upload/20201118/5f0d1534a05864b62ccc647d3e4d166f.pdf)

Configuration:
- Web browser and its version:  **Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36**
- Operating system and its version:
- PDF.js version: **PDF.js v2.5.207**
- Is a browser extension: no

Steps to reproduce the problem:
1. use iframe load viewer.html like ``` <iframe class="qeustion" src="./pdfjs/web/viewer.html?file=http%3A%2F%2Fadmin.gaokao8.com%2Fdist%2Fapi%2Fpublic%2Fupload%2F20201118%5C5f0d1534a05864b62ccc647d3e4d166f.pdf"></iframe> ```

What is the expected behavior? (add screenshot)
can load pdf file success
What went wrong? (add screenshot)
![failed_to_fetch](https://user-images.githubusercontent.com/40019023/100702271-5e216280-33dc-11eb-921c-6f58bc2ba9f0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> use iframe load viewer.html like `<iframe class="qeustion" src="./pdfjs/web/viewer.html?file=http%3A%2F%2Fadmin.gaokao8.com%2Fdist%2Fapi%2Fpublic%2Fupload%2F20201118%5C5f0d1534a05864b62ccc647d3e4d166f.pdf"></iframe>`

This honestly doesn't look like a PDF.js issue, but rather a case where the browser for some reason blocks loading of the resource. This could e.g. be related to iframe sandboxing or perhaps suggest a CORS problem (see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr), but as-is we cannot really help with that.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sinbadmaster** [comment]
@Snuffleupagus thanks a lot! your answer gave me a lot help. finally found this issue occured by CORS.

**Comment by chenmommo** [comment]
本地服务配置为http-serrver --cors 可解决报错  PDF.js v2.7.570 (build: f2c7338b0)
信息：Failed to fetch

**Comment by Eyxxxxx** [comment]
it may confilct with your idm extension if you have one, which is my case.

**Comment by WWWzq-01** [comment]
> it may confilct with your idm extension if you have one, which is my case.
So have you solved this problem now? Did you uninstall IDM?

**Comment by WWWzq-01** [comment]
> 本地服务配置为http-serrver --cors 可解决报错 PDF.js v2.7.570 (build: [f2c7338](https://github.com/mozilla/pdf.js/commit/f2c7338b02092db72719dfe106c9688397dc5d90))
> 信息：Failed to fetch

这个本地服务配置是什么意思呀

**Comment by Eyxxxxx** [comment]
> > it may confilct with your idm extension if you have one, which is my case.
> 
> So have you solved this problem now? Did you uninstall IDM?

Shut down the IDM extension in the browser may help to exhibit the pdf with the pdf viewer normally, which is helpful for me.

**Comment by rafiee** [comment]
> > > it may confilct with your idm extension if you have one, which is my case.
> > 
> > 
> > So have you solved this problem now? Did you uninstall IDM?
> 
> Shut down the IDM extension in the browser may help to exhibit the pdf with the pdf viewer normally, which is helpful for me.

It worked for me. Thanks

**Comment by behnam-io** [comment]
> Shut down the IDM extension in the browser may help to exhibit the pdf with the pdf viewer normally, which is helpful for me.

I also faced this issue on Mac. Similarly disabled the Xtreme Downloader plugin (Something like IDM) solved the issue

**Comment by tryhikmawan** [comment]
> > > it may confilct with your idm extension if you have one, which is my case.
> > 
> > 
> > So have you solved this problem now? Did you uninstall IDM?
> 
> Shut down the IDM extension in the browser may help to exhibit the pdf with the pdf viewer normally, which is helpful for me.

Thanks, it worked

**Comment by 0101220069412** [comment]
PDF.js v2.0.943 (build: dc98bf76)
ข้อความ: Failed to fetch

**Comment by 0101220069412** [comment]
PDF.js v2.0.943 (build: dc98bf76)
ข้อความ: Failed to fetch

**Comment by 0101220069412** [comment]
Uploading 2023-08-31-101539036.mp4…
