### ISSUE TITLE
Any way to have download/print/.. display control into preference file?

### ISSUE THREAD

**Issue by sebDK** [mozilla/pdf.js#12672]
Is there any way to control display of download/print/.. button display through default_preferences file?
Now I have to comment out the different code sections inside the different files.
Any better way?

**Comment by Snuffleupagus** [comment]
> Is there any way to control display of download/print/.. button display through default_preferences file?

No, since we want to avoid complicating the default viewer too much; please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by sebDK** [comment]
Thanks @Snuffleupagus
