### ISSUE TITLE
this.linkService.goToDestination is not a function when clicking on an internal link

### ISSUE THREAD

**Issue by d01010101** [mozilla/pdf.js#12683]
Hi, I have replaced `pdf.min.js`, `pdf.worker.min.js`, `pdf_viewer.js` with equivalents from the latest snapshot, not minimized `pdf.js`, `pdf.worker.js`, `pdf_viewer.js`. This made the internal PDF links work no more. If I click on one, the following error shows:

```
uncaught TypeError: this.linkService.goToDestination is not a function
    at HTMLAnchorElement.link.onclick (annotation_layer.js:385)
```
which leads to `this.linkService.goToDestination(destination);`

Otherwise, there are no errors in the console. I use a single page viewer, with the following init/PDF load function, copied from some place:
```
<script src="pdfjs/pdf.js"></script>
<script src="pdfjs/pdf_viewer.js"></script>

...

function loadPdf(id, pdfUrl, searchTerm) {
    const pdfjsLib = window['pdfjs-dist/build/pdf'];
    const pdfjsViewer = window['pdfjs-dist/web/pdf_viewer'];

    pdfjsLib.GlobalWorkerOptions.workerSrc = 'pdfjs/pdf.worker.js';

    const container = document.querySelector(id);

    var DEFAULT_URL = pdfUrl;
    var SEARCH_FOR = searchTerm;

    var eventBus = new pdfjsViewer.EventBus();

    var pdfLinkService = new pdfjsViewer.PDFLinkService({
      eventBus: eventBus,
    });

    var pdfFindController = new pdfjsViewer.PDFFindController({
      eventBus: eventBus,
      linkService: pdfLinkService,
    });

    var pdfSinglePageViewer = new pdfjsViewer.PDFSinglePageViewer({
      container: container,
      eventBus: eventBus,
      linkService: pdfLinkService,
      findController: pdfFindController,
    });
    pdfLinkService.setViewer(pdfSinglePageViewer);

    eventBus.on("pagesinit", function () {
      // We can use pdfSinglePageViewer now, e.g. let's change default scale.
      pdfSinglePageViewer.currentScaleValue = "page-width";
      
      if (SEARCH_FOR) {
        pdfFindController.executeCommand("find", { query: SEARCH_FOR });
      }
    });

    // Loading document.
    var loadingTask = pdfjsLib.getDocument({
      url: DEFAULT_URL,
    });
    loadingTask.promise.then(function (pdfDocument) {
      // Document loaded, specifying document for the viewer and
      // the (optional) linkService.
      pdfSinglePageViewer.setDocument(pdfDocument);
      pdfLinkService.setDocument(pdfDocument, null);
    });
}

```
Where could be the problem?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by d01010101** [comment]
Thanks for info but I don't think that is an issue, just a newbie question in a search for hints. I don't think that it has anything to do with browsers and versions. If it is not a place for newbie questions, close it. Otherwise, I will close it in few days.
