### ISSUE TITLE
Possible typo/error in the `src/scripting_api/field.js` file

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#12684]
The following code looks really strange, since I cannot imagine that using an Array together with a bitwise OR operator (`|`) makes much sense in general!?
Shouldn't these lines simply use a "normal" OR operator (`||`) instead?
https://github.com/mozilla/pdf.js/blob/a618b02e6274c173c414855d8311930c43b99c00/src/scripting_api/field.js#L75-L77

/cc @calixteman

**Comment by calixteman** [comment]
my bad... you're right it should be a `||`.
