### ISSUE TITLE
plus.nativeObj.Bitmap Screen capture

### ISSUE THREAD

**Issue by fuyouping** [mozilla/pdf.js#12692]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Android App（uni-app  vue）
- Operating system and its version: 
- PDF.js version:  Version 2.0
- Is a browser extension:

Steps to reproduce the problem:
1. Normal picture
![image](https://user-images.githubusercontent.com/12540737/101147410-4dc8ec00-3657-11eb-8ce1-60f4b4f8eaba.png)
2.Screen capture
![image](https://user-images.githubusercontent.com/12540737/101147473-61745280-3657-11eb-96e0-ea10ff25589b.png)

The background of the text is different。

How can I set up or use what version to solve this problem？

**Comment by Snuffleupagus** [comment]
> PDF.js version: Version 2.0

That *specific* version number doesn't exist; furthermore there's nowhere near enough information provided to make this issue actionable/valid as-is.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
