### ISSUE TITLE
How do you use pdfjs-dist with Angular for Internet Explorer?

### ISSUE THREAD

**Issue by ericyu049** [mozilla/pdf.js#12691]
Configuration:
- Web browser and its version: Internet Explorer 11
- Operating system and its version: Windows
- PDF.js version: v2.6.347

Steps to reproduce the problem:
1. npm install --save pdfjs-dist
2. import * as pdfjs from 'pdfjs-dist'
3. pdfjs: any
4. use pdfjs functions like getDocument() etc

What is the expected behavior?
PDF should load.

What went wrong? 
This will work perfectly fine for Chrome, but in IE will get errors like "Object action not supported". Which is expected I guess because it's not using the es5 files. In the readme it says "please refer to the es5 folder", but have no documentations on actually how to make the package resolve to es5 folder only.

I tried to modify the pdfjs-dist in the node modules to resolve to the es5 folder by running a script during build to replace contents under /build with /es5/build, or modifying webpack.js to read the es5 folder instead, but at the end when I load my component I got an error saying Weakset undefined or something other weird errors that I have no idea how to debug.

I also tried manually imported the scripts dynamically and append it by using document.createElement('script') and document.getElementsByTagName("head")[0].appendChild(sc). This method will work the best, but performance wise it's very bad because it needs to wait for the scripts to finish loading before you can actually do anything.

What is the proper way to use this package for IE??

**Comment by Snuffleupagus** [comment]
> What is the proper way to use this package for IE??

Please note that as mentioned in the FAQ, IE 11 is now essentially *unsupported*; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. ***However, this support will be dropped after stable version `2.6.347`.***
