### ISSUE TITLE
add cors Header to pdf.js

### ISSUE THREAD

**Issue by Douglas0n** [mozilla/pdf.js#12694]
The solution is described here [stackoverflow](https://stackoverflow.com/questions/24952810/pdf-js-in-mobile-apps-access-control-allow-origin-issue/62953428#62953428)

I'm trying to load a PDF and the request to PDF file on AWS S3 has been blocked by CORS policy. 

    pdfjsLib.GlobalWorkerOptions.workerSrc = workerSrc

    const pdf = await pdfjsLib.getDocument(pdfUrl).promise
    const page = await pdf.getPage(1)
    const viewport = page.getViewport({ scale: 1 })
    const context = pdfCanvasRef.current?.getContext('2d');

    setCanvasHeight(viewport.height)
    setCanvasWidth(viewport.width)

    const renderContext = {
      canvasContext: context,
      viewport: viewport,
    }
    await page.render(renderContext).promise

**Comment by Snuffleupagus** [comment]
Please see the JSDocs for the `getDocument` parameters: https://github.com/mozilla/pdf.js/blob/54ca67d6282e264814bbf91bbe3d4bfb87b5129f/src/display/api.js#L117-L120

**Comment by namlq93** [comment]
> Please see the JSDocs for the `getDocument` parameters:
> 
> https://github.com/mozilla/pdf.js/blob/54ca67d6282e264814bbf91bbe3d4bfb87b5129f/src/display/api.js#L117-L120

Can you give an example? Thank you

**Comment by Douglas0n** [comment]
> Please see the JSDocs for the `getDocument` parameters:
> 
> https://github.com/mozilla/pdf.js/blob/54ca67d6282e264814bbf91bbe3d4bfb87b5129f/src/display/api.js#L117-L120

Can I set the headers like this?:

const pdf = await pdfjsLib.getDocument(pdfUrl, { 'Origin': 'https://www.sign.focvs.cloud' } ).promise();

**Comment by meng7171** [comment]
Hi, @Douglas0n 

TQ for the INFO above. You really save my time for continue attacked by any.
