### ISSUE TITLE
Type3 font is not rendered

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#12705]
Attach (recommended) or Link to PDF file here: [issue.pdf](https://github.com/mozilla/pdf.js/files/5659516/issue.pdf)

Configuration:
- Web browser and its version: Firefox (83.0)
- Operating system and its version: Win 10 Pro
- PDF.js version: 2.7.345

Steps to reproduce the problem:
1. Open attached PDF
2. You see a white page

What is the expected behavior? (add screenshot)
![grafik](https://user-images.githubusercontent.com/12390057/101490189-4d379a80-3962-11eb-94f7-b9a29936ec9f.png)

What went wrong? (add screenshot)
Nothing is rendered but the text layer (selected for demonstration only):
![grafik](https://user-images.githubusercontent.com/12390057/101490311-748e6780-3962-11eb-811b-2c14ec0287e8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
The Type3-glyphs look slightly "weird" as far as I can tell, see one example below (using http://brendandahl.github.io/pdf.js.utils/browser/ to extract the data), since each one sets the fill-color to *white* initially (the `1 1 1 rg` operator) which is then applied at the end  (the `f` operator).
Provided that I'm not misunderstanding the operatorList of each glyph, we thus end up painting it completely white. What I don't see, off the top of my head, is a way to fix this since I can't imagine that just ignoring a white-fill operator for Type3-glyphs is correct in general.

```
iSQP0031 (stream) [id: 27, gen: 0]

    Length = 143
    Filter = /FlateDecode
    <view contents> download

    546 0 110 0 465 730 d1
    0 0 0 RG
    1 1 1 rg
    1 w
    [] 0 d
    465 0 m
    110 0 l
    110 74 l
    242 74 l
    242 562 l
    110 562 l
    110 628 l
    159.87 628 196.62 635.1 220.25 649.32 c
    243.88 663.54 257.17 690.43 260.1 730 c
    336 730 l
    336 74 l
    465 74 l
    h
    f
```

**Comment by JanSlabon** [comment]
It become more hard to decide who's wrong when the Type3 example in PDF 2.0 explicitly uses colors in the glyph description:
![grafik](https://user-images.githubusercontent.com/12390057/101507189-94c82180-3976-11eb-9e38-cc3dee7555ae.png)
[...]
![grafik](https://user-images.githubusercontent.com/12390057/101507241-a5789780-3976-11eb-8e00-1698348a62d9.png)

**Comment by janpe2** [comment]
The spec says:
A glyph description that begins with the `d1` operator should not execute any operators that set the colour (or other colour-related parameters) in the graphics state; any use of such operators shall 
be ignored.

**Comment by JanSlabon** [comment]
@janpe2 you are right! I didn't noticed that when I skim through the specs.

So then it shouldn't be hard to be fixed. For reference this information can be found in "Table 113 – Type 3 font operators" in PDF 32000-1:2008.

**Comment by janpe2** [comment]
The forbidden operators are listed at the end of chapter "8.6.8 Colour Operators".

**Comment by timvandermeij** [comment]
Fixed by the PR above.
