### ISSUE TITLE
Outline items are not opened/closed correctly

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#12704]
Attach (recommended) or Link to PDF file here: [outline.pdf](https://github.com/mozilla/pdf.js/files/5658970/outline.pdf)

Configuration:
- Web browser and its version: Firefox (83.0)
- Operating system and its version: Win 10 Pro
- PDF.js version: 2.7.345
- Is a browser extension: no (but should be independent)

Steps to reproduce the problem:
1. Open the PDF in PDF.js Viewer
2. Open the bookmark outline

What is the expected behavior? 
![grafik](https://user-images.githubusercontent.com/12390057/101478819-8f0c1500-3951-11eb-8693-e59f2924358d.png)

What went wrong? 
![grafik](https://user-images.githubusercontent.com/12390057/101478861-9df2c780-3951-11eb-8d25-87f6d0055dcb.png)
`C.A` should be closed.

For me it looks like an issue which is caused only if the node that should be closed indcludes "open" nodes. This looks like a wrong interpretation of the `/Count` entry in outline items.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
Fixed by the PR above.
