### ISSUE TITLE
How can I preview multiple PDF files simultaneously using the official viewer. html

### ISSUE THREAD

**Issue by mishudaoshui** [mozilla/pdf.js#12715]
Now I have a problem that using canvas to render PDF is too slow and unclear, so I need to display multiple PDF files at the same time, so I choose to use the official viwer.html. At present, I don't know how to use Viwer.html to display multiple PDF files at the same time

**Comment by Snuffleupagus** [comment]
> I don't know how to use Viwer.html to display multiple PDF files at the same time

That's not a supported use-case in the default viewer; nor will it be implemented either since it's too much of an edge-case and would add unnecessary complexity to the code as well.
