### ISSUE TITLE
Problem with worker directory

### ISSUE THREAD

**Issue by clempe** [mozilla/pdf.js#12710]
Attach (recommended) or Link to PDF file here:

Configuration:
- PDF.js version: 2.7.322
- Is a browser extension: no

I tried to upgrade pdf.js from 2.4.456 to 2.7.322

Steps to reproduce the problem:
I have to dynamically load PDF.js using jquery :
``` 
jQuery.getScript('customPath/pdf.js, function () {
            jQuery.getScript('customPath/viewer.js');
});
```
And after that i set the path to for the pdf worker:
```
document.addEventListener("webviewerloaded", function (){
    PDFViewerApplicationOptions.set('workerSrc', 'customPath/pdf.worker.js');
});
```

Upgrading to 2.7.322 now produces the following error:
```
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at: http://.../build/pdf.worker.js".
    at <anonymous>:3158:38
```

It seems like pdf.js tries to access the wrong directory for the worker, because it's not initialized at this point?

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
