### ISSUE TITLE
how fix 'this.annotations is not iterable'?

### ISSUE THREAD

**Issue by songQiuXiao** [mozilla/pdf.js#12714]
[Attach](url) (recommended) or Link to PDF file here:
[b49fe733-63e0-4972-8b47-3a05c2c8e881.pdf](https://github.com/mozilla/pdf.js/files/5669997/b49fe733-63e0-4972-8b47-3a05c2c8e881.pdf)

Configuration:
- Web browser and its version: Google Chrome 86.0.4240.198
- Operating system and its version: MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)big sur 11.0.1

- PDF.js version: 2.5/2.6/2.7
- Is a browser extension:

Steps to reproduce the problem:
1. get the file [b49fe733-63e0-4972-8b47-3a05c2c8e881.pdf](https://github.com/mozilla/pdf.js/files/5669997/b49fe733-63e0-4972-8b47-3a05c2c8e881.pdf)
2. upload into your [demo website](https://mozilla.github.io/pdf.js/web/viewer.html)
3. this bug is absent in version 2.2.228
![image](https://user-images.githubusercontent.com/24636816/101715919-4da57200-3ad7-11eb-9064-c1d196506260.png)

What is the expected behavior? (add screenshot)
see the original pdf file

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/24636816/101715919-4da57200-3ad7-11eb-9064-c1d196506260.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Fixed by the PR above.
