### ISSUE TITLE
TextLayer.render()  problem( (Cannot read property 'dispatch' of undefined     at TextLayerBuilder._finishRendering (pdf_viewer.js?968b:1606))) ,how to use textlayer collectly

### ISSUE THREAD

**Issue by txfyteen** [mozilla/pdf.js#12727]
`Attach` (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:      "pdfjs-dist": "^2.5.207"
- Operating system and its version:  window 10 x64
- PDF.js version:   "pdfjs-dist": "^2.5.207"
- Is a browser extension:  chrome 87.0.4280.11 dev （x64）

Steps to reproduce the problem:
1.  upload pdf file to render pdf , pdf canvas layer is succes
2. add textlayer to render , it is successful to show textlayer in chrome ，meanwhile， console log some problem
3. here is my code
        const viewport = this.pdfPage.getViewport({ scale });
        // Prepare canvas using PDF page dimensions
        const pageDiv = document.createElement("div");
        const canvas = document.createElement("canvas");
        const context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;
        pageDiv.appendChild(canvas);
        pageDiv.setAttribute(
              "style",
              "position: relative;display:flex;justify-content:center;margin-bottom:5px;"
        );
        container.appendChild(pageDiv)
        // Render PDF page into canvas context
        const renderContext = {
          canvasContext: context,
          viewport,
        };
      await this.pdfPage.render(renderContext);
      let textContent = await this.pdfPage.getTextContent();
      // create textlayer div
      const textLayerDiv = document.createElement('div');
      textLayerDiv.setAttribute('class', 'textLayer');
      textLayerDiv.setAttribute('style', `width: ${viewport.width}px; margin: 0 auto;`)
      // add textlayer to div
      pageDiv.appendChild(textLayerDiv);
      // new TextLayerBuilder
      let textLayer = new TextLayerBuilder({
        textLayerDiv: textLayerDiv,
        pageIndex: this.pdfPage._pageIndex,
        viewport: viewport
      });
      textLayer.setTextContent(textContent);
      textLayer.render();

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5924541/101853029-eb617580-3b99-11eb-920f-d37935b52484.png)

What went wrong? (add screenshot)
1、in chrome error
![image](https://user-images.githubusercontent.com/5924541/101853054-f5837400-3b99-11eb-9417-ae7c3b22a05e.png)

2、in firefox error
![image](https://user-images.githubusercontent.com/5924541/101854303-39777880-3b9c-11eb-9f25-af72c1c8accb.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

[https://github.com/mozilla/pdfjs-dist](url)

**Comment by Snuffleupagus** [comment]
It looks like you didn't provide an `eventBus`-instance when initializing the `TextLayerBuilder`, which is required for it to work (and this explains the errors you're seeing).
You may find it easier to use one of the `viewer component` examples, see https://github.com/mozilla/pdf.js/tree/master/examples/components, which handles these kind of things for you.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
