### ISSUE TITLE
korean is broken when specific pdf file is opened to pdfjs

### ISSUE THREAD

**Issue by serile** [mozilla/pdf.js#12729]
Attach (recommended) or Link to PDF file here: https://drive.google.com/file/d/1lrgcVT3mX2wucOXbRHGTSvmjrifyrAwD/view?usp=sharing

Configuration:
- Web browser and its version: chrome, ie11, safari latest version
- Operating system and its version: Windows 7, Windows 10, macOS
- PDF.js version: v2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. open a pdf file I attached to pdfjs

What went wrong? (add screenshot)
Korean appeared in strange letters at document.
I don't know what is going on. there is no problem opening downloaded PDF file with adobe acrobat reader. Korean is fine on  adobe acrobat reader.
Please let me know solution.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://test-data.krx.co.kr:8081/inc/lib/pdfjs/web/viewer.html?file=%2Fcomm%2FfileDn%2Fdownload_att%2Fdownload.cmd%3Fcode%3DLsRMPEMH7qJPS8GBfDwcgEJ4w9xVEA5fHTXJIt%2B%2FJOW9wRqws6IuCFC55QCcJ6tT6RO0B%2BVhrogx1%2BHY6CNtjP98cV%2B73TYdynrYq%2B1vmT6c2fEQDsKWJUZ7Vhzc0ov1kcVggV%2BiA7Z4i0ibozdvaiM%2BKRY9CK0jpR9SM2CT3U8BioQadifaZHrwF9mt0e8oG9zVl2gCt25AMMH5YjI6rg%3D%3D

**Comment by Snuffleupagus** [comment]
This PDF document uses *non-standard* fonts, but doesn't embed them which is incorrect (and thus violates the PDF specification); hence this a bug in the PDF document *itself* rather than the PDF.js library.

> there is no problem opening downloaded PDF file with adobe acrobat reader. Korean is fine on adobe acrobat reader.

That's because you have the fonts in question installed locally on your computer. If you don't have the relevant fonts installed locally, which I don't, then the PDF document does *not* render in Adobe Reader.

**Comment by serile** [comment]
I got it what you said. Thanks to your detail.
Is there any method to install the font for pdf.js that is used to pdf file on my web project?

**Comment by serile** [comment]
> This PDF document uses _non-standard_ fonts, but doesn't embed them which is incorrect (and thus violates the PDF specification); hence this a bug in the PDF document _itself_ rather than the PDF.js library.
> 
> > there is no problem opening downloaded PDF file with adobe acrobat reader. Korean is fine on adobe acrobat reader.
> 
> That's because you have the fonts in question installed locally on your computer. If you don't have the relevant fonts installed locally, which I don't, then the PDF document does _not_ render in Adobe Reader.

I got it what you said. Thanks to your detail.
Is there any method to install the font for pdf.js that is used to pdf file on my web project?

**Comment by timvandermeij** [comment]
You'd have to integrate the font with PDF.js by editing the source code, which is not trivial and not something we can assist with. As said, it's _much_ better to simply embed the font in the PDF file to avoid any problems in any PDF reader.

**Comment by serile** [comment]
Thanks a lot.
