### ISSUE TITLE
PDF with image is not getting rendered in IE 11

### ISSUE THREAD

**Issue by sumitkumar121** [mozilla/pdf.js#12739]
When i try to render a pdf which contain only  image  IE get crashed.

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: windows 10
- PDF.js version: v2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF which only contain Image 

What is the expected behavior? (add screenshot)

it should load the pdf

**Comment by Snuffleupagus** [comment]
> When i try to render a pdf which contain only image IE get crashed.

*Generally speaking:* Without the PDF file in question this issue, or anyone else really, isn't actionable/valid.

> Web browser and its version: IE 11

Furthermore, please note that as mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 will no longer be supported in upcoming PDF.js releases.

> PDF.js version: v2.3.200

Finally, please note that this version is no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases
