### ISSUE TITLE
"Unexpected: The user aborted a request" on changing not fully loaded document

### ISSUE THREAD

**Issue by JustMyst** [mozilla/pdf.js#12735]
Configuration:
- Web browser and its version: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Home x64 1909
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:
1. Load pdf.js to global variable on winfow
2. Init all needed parts of pdf.js - EventBus, LinkService, ViewerContainer
3.  Create PDFViewer instance and link it
```
                this._viewer = new window.pdfjsViewer.PDFViewer({
                    container: this._viewerContainer,
                    eventBus: this._eventBus,
                    linkService: this._linkService,
                    textLayerFactory: new window.pdfjsViewer.DefaultTextLayerFactory(),
                    annotationLayerFactory: new window.pdfjsViewer.DefaultAnnotationLayerFactory()
                });

                this._linkService.setViewer(this._viewer);
```
4. Add Event listener to EventBus, to change scale on `pagesinit`
```
                this._eventBus.on("pagesinit", () => {
                    this._viewer.currentScaleValue = this._scaleValue;
                });
```
5.  Load documents several times
```
            if (this._loadingTask && !this._loadingTask.destroyed)
                await this._loadingTask.destroy();

            this._loadingTask = window.pdfjsLib.getDocument({
                url: this._file.url,
                cMapUrl: "_Public/pdf.js/cmaps/",
                cMapPacked: true,
                disableAutoFetch: true,
                disableStream: true
            });

            try {
                const pdfDocument = await this._loadingTask.promise;

                this._viewer.setDocument(pdfDocument);
                this._linkService.setDocument(pdfDocument, null);
            } catch (ex) {
                if (!ex)
                    throw new UserError(this, "File not found.");

                throw ex;
            }
```
What is the expected behavior? (add screenshot)
Documents should appear on viewer container and change scale on init

What went wrong? (add screenshot)
If document is changed before it's loaded:
1. An error is thrown on `await this._loadingTask.destroy();`
![image](https://user-images.githubusercontent.com/38665029/102050878-e55ed500-3de3-11eb-93b6-4b67ac99bc52.png)
![image](https://user-images.githubusercontent.com/38665029/102050806-c2342580-3de3-11eb-8092-7acf29dc699a.png)
2. Same Error is thrown on `this._viewer.currentScaleValue = this._scaleValue;`
![image](https://user-images.githubusercontent.com/38665029/102051065-3969b980-3de4-11eb-9f76-04a912bf24f3.png)
3. Which results in unexpected `The user aborted a request` error
![image](https://user-images.githubusercontent.com/38665029/102051242-8e0d3480-3de4-11eb-85b6-65d28ed863df.png)

Is there any way to prevent unexpected `The user aborted a request` error (e.g. change event listener to work only on fully loaded documents, or destroy tasks without aborting scale change)? 
Already tried changing eventlistener to `pagesloaded` or `textlayerrendered`.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.,

**Comment by JustMyst** [comment]
Hello @Snuffleupagus and @timvandermeij 

I've forked Your repo and changed `mobile-viewer` example to demonstrate this issue. 
https://github.com/JustMyst/pdf.js

Changes I've made:
- Added button to reload PDF document (Simply does the `open` function)

To reproduce:
1. Get repo from link above
2. run `gulp dist-install` and `gulp server`
3. http://localhost:8888/examples/mobile-viewer/viewer.html
4. In developer tools set `Disable cache` in Network conditions and `Pause on exception` as on image below
![image](https://user-images.githubusercontent.com/38665029/103518349-e54a7600-4e73-11eb-861c-4b8e59be98c0.png)
5. Click on RELOAD button in top left corner several times (fastly or set Network throttling to 3G)

An uncaught error is thrown `pdfPage is not loaded` as on image from point 4.

@timvandermeij Could you reopen this issue?

**Comment by Snuffleupagus** [comment]
> An uncaught error is thrown `pdfPage is not loaded` as on image from point 4.

That honestly doesn't make a lot of sense, since any errors are caught (and only logged) in https://github.com/mozilla/pdf.js/blob/ed3758f84d2a285a19a0fa32baa1b75d990f54ee/web/pdf_rendering_queue.js#L170-L179

**Comment by Snuffleupagus** [comment]
I've just tested this in Google Chrome 89, using the `master`-branch of the PDF.js library with the code modified as outlined in https://github.com/JustMyst/pdf.js/commit/778e4ae5c09f1f2cf88d9d067bd81ba50cae8959?w=1, and I cannot reproduce this issue.

(And as mentioned in https://github.com/mozilla/pdf.js/issues/12735#issuecomment-754580384, the error in question should definitely be caught.)
