### ISSUE TITLE
Path length limitation

### ISSUE THREAD

**Issue by LeoPiresDeSouza** [mozilla/pdf.js#12740]
Hi.
I want to know if there is a limitation to the length of the string that includes the path and the pdf file name.

I have two diferent links shown below. The first one functions perfectly. But the second one gives me the following error message: 
Message: Missing PDF "https://localhost:44371/CertificadoDigital/EscolContabil/eCNPJA1ArquivoEletronico/20201210/Curso_AspnetCore_2_Conteudo.pdf".

It is the same file, just in an shorter path. 

Am I missing something or there really is a limit to the path length?

Thank's.

a href="~/pdf.js-gh-pages/web/viewer.html?file=%2FCertificadoDigital/EscolContabil/eCNPJA1ArquivoEletronico/20201210/Curso_AspnetCore_2_Conteudo.pdf" target="_blank">Open yourpdf.pdf with PDF.js</a>"

a href="~/pdf.js-gh-pages/web/viewer.html?file=%2FCertificadoDigital/Curso_AspnetCore_2_Conteudo.pdf" target="_blank">Open yourpdf.pdf with PDF.js</a>"

![Missing PDF](https://user-images.githubusercontent.com/40829469/102310079-05f46f80-3f49-11eb-91bb-edaf971b4ef1.png)
![PDF shown](https://user-images.githubusercontent.com/40829469/102310102-0d1b7d80-3f49-11eb-8af3-7182b0cf8eaf.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
