### ISSUE TITLE
Travis CI free usage ends Dec 3; mozilla repos should switch to other CI platforms

### ISSUE THREAD

**Issue by hwine** [mozilla/pdf.js#12743]
We're opening this issue because your project has used Travis CI within the last 6 months. If you have already migrated off it, you can close and ignore this issue.

Travis CI is ending free builds on public repositories. travis-ci.com [stopped providing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)them in early November, and travis-ci.org [will stop](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom) after December 31, 2020. To avoid disruptions to your workflows, you must migrate to another CI service.

For production use cases, we recommend switching to [CircleCI](https://circleci.com/). This service is already widely used within Mozilla. There is a guide to migrating from Travis CI to CircleCI available [here](https://circleci.com/docs/2.0/migrating-from-travis/).

For non production use cases, we recommend either CircleCI or [Github Actions](https://github.com/features/actions). There is a guide to migrating from Travis CI to Github Actions available [here](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions). Github Actions usage within Mozilla is new, and you will have to work with our github administrators to enable specific actions following [this process](https://wiki.mozilla.org/GitHub#How_do_I_hook_up_a_new_GitHub_Actions_or_3rd_party_application_to_a_repository_in_the_mozilla_org.3F).

If you have any questions, reach out in `#github-admin:mozilla.org` on [matrix](https://chat.mozilla.org/#/room/#github-admin:mozilla.org).

**Comment by timvandermeij** [comment]
Somewhat related to #11851. I think switching to GitHub Actions is the best way forward here since GitHub is our primary development platform and it (obviously) integrates nicely.

**Comment by timvandermeij** [comment]
Fixed by the pull request above. @hwine Thank you for notifying us!
