### ISSUE TITLE
Copying text from PDF

### ISSUE THREAD

**Issue by hitman4an** [mozilla/pdf.js#12776]
Hello! I have problem with copying text from PDF file. When I try to copy text from file i get text without spaces. Example in attach.
[Доработать в СБИС 2 (1).pdf](https://github.com/mozilla/pdf.js/files/5739391/2.1.pdf)

I have :
Доработатьв СБИС 2.5печать комплектов отчетностив соответствии с пожеланиями клиентов.

I want:
Доработать в СБИС 2.5 печать комплектов отчетности в соответствии с пожеланиями клиентов.

**Comment by tirlochanarora16** [comment]
I tried it but it's working fine for me.

**Comment by hitman4an** [comment]
Here's the video.

https://user-images.githubusercontent.com/23082585/103122003-a0625a80-468f-11eb-9127-48d730edd4c6.mp4

**Comment by tirlochanarora16** [comment]
Try pasting in Microsoft word.

**Comment by hitman4an** [comment]
Same problem
![image](https://user-images.githubusercontent.com/23082585/103125770-39e43900-469d-11eb-8a33-aade0a54a7ab.png)

**Comment by hitman4an** [comment]
If i open this file in Microsoft Edge, text copy is fine.
![image](https://user-images.githubusercontent.com/23082585/103126094-3c935e00-469e-11eb-9012-b51d7cbe4ed6.png)
![image](https://user-images.githubusercontent.com/23082585/103126105-4917b680-469e-11eb-9c16-99e523104f63.png)

**Comment by aastha432** [comment]
![Capture 1](https://user-images.githubusercontent.com/68348006/104048116-c0098f00-5208-11eb-8005-863373814778.PNG)
![Capture 2](https://user-images.githubusercontent.com/68348006/104048121-c3047f80-5208-11eb-9995-61279ba7e8f4.PNG)



It works fine for me....

**Comment by hitman4an** [comment]
Try, please my file
[2.1.pdf](https://github.com/mozilla/pdf.js/files/5963757/2.1.pdf)

**Comment by hitman4an** [comment]
> ![Capture 1](https://user-images.githubusercontent.com/68348006/104048116-c0098f00-5208-11eb-8005-863373814778.PNG)
> ![Capture 2](https://user-images.githubusercontent.com/68348006/104048121-c3047f80-5208-11eb-9995-61279ba7e8f4.PNG)
> 
> It works fine for me....

Show me with my file.

**Comment by timvandermeij** [comment]
Fixed by #13257 and possibly other patches.
