### ISSUE TITLE
Webpack entry point cannot find worker-loader in Yarn 2 repo

### ISSUE THREAD

**Issue by jcamden** [mozilla/pdf.js#12778]
Attach (recommended) or Link to PDF file here:
https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

**Configuration:**
- Web browser and its version: Firefox 84.0
- Operating system and its version: Ubuntu 20.10
- PDF.js version: 2.6.347
- Also note: Webpack 5.11.0 and Yarn 2.3.3 workspaces

**Steps to reproduce the problem:**
To see the manual worker setup resort to fake worker:
1. clone and setup with Yarn 2: https://github.com/jcamden/pdfjs-yarn-2 
2. run the webpack dev server with `yarn start`
3. check browser console log for 'Warning: Setting up fake worker.'

To see the webpack entry point fail:
1. uncomment line 8 of packages/client/App.tsx "// pdfWebpackEntry('./dummy.pdf');"
2. run the webpack dev server with 'yarn start'
3. check terminal for 'Module not found: Error: Can't resolve 'worker-loader'...'

**What is the expected behavior? (add screenshot)**
1. Using the Webpack entry point succeeds, or
2. Manually configuring the worker succeeds, or
3. I make a million dollars.
![millionDollars](https://user-images.githubusercontent.com/5461045/103142795-eba05b80-46d7-11eb-8790-cf83c136a5ec.jpeg)

**What went wrong? (add screenshot)**
1. Manually setting up worker fails:
![Screenshot_2020-12-25_17-24-47](https://user-images.githubusercontent.com/5461045/103142723-22757200-46d6-11eb-99ae-bc5cef9cb383.png)
2. Webpack entry point fails:
![Screenshot_2020-12-25_17-23-30](https://user-images.githubusercontent.com/5461045/103142712-f35f0080-46d5-11eb-8cd9-68a57c936c11.png)
3. Still no million dollars.
![crushingStudentDebt](https://user-images.githubusercontent.com/5461045/103142794-e7743e00-46d7-11eb-9b89-bf29df55242d.jpeg)

**Comment by Snuffleupagus** [comment]
> clone and setup with Yarn 2

Well, I don't think any of the regular PDF.js contributors know "Yarn 2" and consequently it's unfortunately going to be quite difficult for us to provide any meaningful assistance here.

> check terminal for 'Module not found: Error: Can't resolve 'worker-loader'...'

Did you install the `worker-loader` package, since that needs to be done *manually*?

**Comment by jcamden** [comment]
Tyrin' to get some help with this over here: https://github.com/yarnpkg/berry/discussions/2289. I'll update this issue if I make any progress.

**Comment by merceyz** [comment]
> Did you install the worker-loader package, since that needs to be done manually?

@Snuffleupagus The issue is that `pdfjs-dist` lacks an optional(?) peer dependency on `worker-loader` so Yarn PnP (Not Yarn 2) is denying it access

> You guys wouldn't happen to have any leads for me as to why pdfjs-dist seems to be passing "esModule" as worker-loader option, would you? It is indeed true that "esModule" is not one of the options that worker-loader takes. I've tried requiring instead of importing, but seeing the same error. Any guidance, appreciated :)

You're installing `worker-loader@^2` but `esModule` is a `worker-loader@^3` option, if `prdfjs-dist` properly declared its dependencies that would have been avoided

**Comment by jcamden** [comment]
@merceyz , thank you very much! You are awesome!

**Comment by jcamden** [comment]
Just want to clarify a couple of things for posterity:

1. To use pdfjs with Yarn PnP, one must add a package extension for pdfjs-dist to yarnrc.yml since pdfjs-dist does not declare its dependencies. In this case, you want worker-loader as a peer-dep (as @merceyz explained above):
```
packageExtensions:
  'pdfjs-dist@*':
    peerDependencies:
      worker-loader: '^3'
```
2. To use pdfjs _in any case_, note that the global approach (i.e. `import pdfjsLib from 'pdfjs-dist/webpack';`) evinced in the docs and examples (e.g. [here](https://github.com/mozilla/pdf.js/tree/master/examples/webpack#worker-loading)) is now deprecated. It took me some time to sort out why pdfjs was not defined---since my mind was already operating in the realm of worker issues; so I hope to save someone else some time.

I've updated the [repro repo](https://github.com/jcamden/pdfjs-yarn-pnp-webpack-5) with the fixes to serve as an example for anyone trying to integrate pdfjs into a Yarn PnP monorepo with webpack 5. That's the least I can do to pay if forward. Thank you for your awesome contributions.
