### ISSUE TITLE
GlobalWorkerOptions of undefined

### ISSUE THREAD

**Issue by raphael10-collab** [mozilla/pdf.js#12787]
I'm trying to use pdfjs-dist's example: https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js for a Typescript-React-Electron app

    import pdfjsLib from 'pdfjs-dist';

    pdfjsLib.GlobalWorkerOptions.workerSrc = 'src/node_modules/pdfjs-
    dist/build/pdf.worker.js';

I get "GlobalWorkerOptions of undefined".

Based on what I found here: https://github.com/wojtekmaj/react-pdf/blob/master/src/entry.js
in package.json I've put:

    "source": "src/app/components/pdfHandling/entry/entry.js",

where src/app/components/pdfHandling/entry/entry.js : 

    import * as pdfjs from 'pdfjs-dist';

    pdfjs.GlobalWorkerOptions.workerSrc = 'pdf.worker.js';

    export {
     pdfjs,
    };

Any ideas about how to make pdfjs.GlobalWorkerOptions working?

OS: Ubuntu 18.04.4 Desktop
pdfjs-dist installed: 2.5.207
node version:  v14.5.0

**Comment by Snuffleupagus** [comment]
> I'm trying to use pdfjs-dist's example: https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js for a Typescript-React-Electron app

Unfortunately the *core* PDF.js contributors probably don't know much (if anything) about either TypeScript, React and/or Electron hence it's somewhat difficult for us to provide support for those kind of frameworks.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by raphael10-collab** [comment]
@Snuffleupagus  Thank you Jonas for promptly replying to my request of help.

I've searched documented solutions, for example in StackOverflow, but the ones offered, didn't solve the problem.

Here you can find the complete code: https://github.com/raphael10-collab/OnlyPdf

To run the app, once downloaded the code:
- cd OnlyPdf
- yarn
- yarn start

Looking forward to your kind help

**Comment by timvandermeij** [comment]
The standalone examples in our repository work, so this must be some integration issue with React/Electron, for which we cannot provide assistance since we're not familiar with them. I would suggest to ask on StackOverflow or other React/Electron-specific forums instead.
