### ISSUE TITLE
Corona update

### ISSUE THREAD

**Issue by under-score** [mozilla/pdf.js#12784]
What about a 45 deg rotation and not only 90 deg? 
Would be perfect for reading PDFs when ill in bed...

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's no actionable information provided and this issue will be closed as INCOMPLETE.
