### ISSUE TITLE
Autoscroll may cause incorrect changes of document's position

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#12789]
There is a bug where using the autoscroll may cause the document to incorrectly change its position. When the document has been inactive for a while, then left-clicking after autoscrolling will change the position of the document by as much as the position had changed during the autoscroll. For example:

1. There's a pdf document with page 6 active;
2. I switch to another tab;
3. After a longer while, I go back to the document (going back immediately won't work);
4. I use autoscroll to shift the position by 3 pages (page 9 is now active);
5. Now, left-clicking within the area of the document causes the document to jump to page 12.

The worst thing is, this problem does not reproduce 100% reliably. It happens both in Firefox and in the online viewer. There's no particular document that exhibits this bug, I've seen it happen in multiple different documents.

This bug is super-annoying, so if you know of any code locations that are bound to execute when such thing happens, I could add custom code in there to dump the stack/state to provide more insight.

**Comment by Snuffleupagus** [comment]
> There is a bug where using the autoscroll

What is "autoscroll"; a browser feature, addon, or something else entirely?
Without knowing this, I'm having a quite difficult time even understanding the provided STR fully.

**Comment by automatedbugreportingfacility** [comment]
I'm not sure if I picked the right term, it's the circle that appears when you press the middle mouse button: ![autoscroll](https://user-images.githubusercontent.com/3524640/103237816-12b19400-4949-11eb-9566-1e45e6e30de4.png) When it appears, you can move the cursor below or above it to automatically scroll the document.

**Comment by Snuffleupagus** [comment]
> it's the circle that appears when you press the middle mouse button: ![autoscroll](https://user-images.githubusercontent.com/3524640/103237816-12b19400-4949-11eb-9566-1e45e6e30de4.png)

Ah, that definitely helps a lot here!

I'm guessing that you're only seeing this in the PDF.js viewer, and not on any "regular" web-pages?
Regardless, I'd sort of expect that this is a *browser* bug rather than a PDF.js one, but I've got no idea how to debug it off the top of my head (and I've never seen this bug myself).

**Comment by automatedbugreportingfacility** [comment]
Yes, this is specific to PDF.js, and has not ever happened on regular web pages. If PDF.js keeps track of/changes the position of the document somewhere, then there might be a case where autoscroll might disrupt calculations somewhere. I don't know the code well enough to guess where that might be, though, hence a request for aid in debugging.

**Comment by Snuffleupagus** [comment]
Well, there's a scroll-listener added at https://github.com/mozilla/pdf.js/blob/3e34281e3b6e9078ac91dd365393ff15e3a02340/web/base_viewer.js#L210 which (indirectly) calls https://github.com/mozilla/pdf.js/blob/3e34281e3b6e9078ac91dd365393ff15e3a02340/web/base_viewer.js#L1022-L1042 and that one (for the regular `PDFViewer`-case) calls https://github.com/mozilla/pdf.js/blob/3e34281e3b6e9078ac91dd365393ff15e3a02340/web/pdf_viewer.js#L49-L69

However, note that this code simply reads the *current* scroll-state in the viewer but does *not* actually modify it.

**Comment by automatedbugreportingfacility** [comment]
Okay, so I've tried to use "Pause on execution" feature of Firefox debugger to catch any script between the LMB click and the change of the document's position, and unless the debugger is buggy, the jump happens before any script execution. Thus, this looks like a browser bug after all, and something in PDF.js specifically triggers it.

Of interesting things that I noted while looking at scripts executed in PDF.js, the calls to `_tryPushCurrentPosition()` caught my attention. This is a pure guess, but I think the usage of `history.[push/replace]State()` combined with autoscrolling a tab that has recently become active again (i.e. its position is restored) might confuse something in the state kept by the browser.

**Comment by Snuffleupagus** [comment]
> Of interesting things that I noted while looking at scripts executed in PDF.js, the calls to `_tryPushCurrentPosition()` caught my attention.

Please note that that method should *not* be called "in the middle" of scrolling, but rather only from a timeout to ensure that we wait[1] until the viewer is "idle" before calling `_tryPushCurrentPosition()`; note the `_updateViewareaTimeout` property in https://github.com/mozilla/pdf.js/blob/master/web/pdf_history.js

---
[1] Currently set to `1000` milliseconds.
