### ISSUE TITLE
How to set data-loaded attribute to true for all PDF pages?

### ISSUE THREAD

**Issue by alex6liu** [mozilla/pdf.js#12795]
I want to load all the PDF pages at the same time and I find it seems I need to make the data-loaded attribute to true. I wonder if there is anyway to do that.
![image](https://user-images.githubusercontent.com/41029702/103340182-6db8c780-4abe-11eb-9f8c-bd0bfe304133.png)
As you can see in the image, the divs with data-loaded="true" have some real elements in them and others only have ```<div class="loadingIcon"></div>```.
My purpose is the get also the inner elements when PDF loaded. Anyone could give some suggestions? Thank you so much!

**Comment by Snuffleupagus** [comment]
As clearly outlined in the FAQ, that's a really bad idea and it's intentionally *not* supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by alex6liu** [comment]
Hi, @Snuffleupagus. Thanks for your answer. But I really need to do this, anyway to approach that?

**Comment by jsanchezr7** [comment]
Hi, @alex6liu.
¿Did you find the solution? 
I have the same problem.
