### ISSUE TITLE
Minified version of pdf worker doesn't send correct exception

### ISSUE THREAD

**Issue by Wykks** [mozilla/pdf.js#12797]
Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:

Just use any not pdf file to trigger a `InvalidPdfException`

`getDocument().promise.catch((error) => console.log(error);`
`error` is `undefined` when using the _minified_ version of the pdf worker (the one inside **pdfjs-dist/build/pdf.worker.min.js**).

What is the expected behavior?

The error should be `InvalidPDFException {message: "Invalid PDF structure.", name: "InvalidPDFException"}` even when using the minified version of the pdf worker.

What went wrong?

Using pdf.worker.es5.js (should be fine with pdf.worker.js too):
![image](https://user-images.githubusercontent.com/1236069/103357154-c5513600-4ab2-11eb-878b-dd732044351f.png)

Using pdf.worker.min.js:
![image](https://user-images.githubusercontent.com/1236069/103357254-06494a80-4ab3-11eb-9c0d-57b1883b6fd8.png)

And here:
https://github.com/mozilla/pdf.js/blob/6e55326343be543a11a8110e16ceb1c3f0f9f6e6/src/display/api.js#L2332-L2350
`reason` is not going to be defined when `name === 'e'`

**Comment by Snuffleupagus** [comment]
Duplicate of #11941 and #12209.

**Comment by Wykks** [comment]
Oh welp, I really searched before posting.... Sorry!
