### ISSUE TITLE
tapAsync undefined with webpack

### ISSUE THREAD

**Issue by darkomenx** [mozilla/pdf.js#12791]
**Configuration:**
- Web browser and its version: Electron 9
- Operating system and its version: iOS 10.15
- PDF.js version:  "pdfjs-dist": "^2.5.207",
- Is a browser extension: I use Vue.js 2 into Electron.js serve by Webpack

**Steps to reproduce the problem:**
1. yarn add pdfjs-dist
2. import pdfjsLib from 'pdfjs-dist/webpack' (into component vuejs for viewer pdf)

**What is the expected behavior?** 

Perhaps just import run without error...

**What went wrong?** 

```
 error  in ./node_modules/pdfjs-dist/build/pdf.worker.js

Syntax Error: TypeError: Cannot read property 'tapAsync' of undefined

 @ ./node_modules/pdfjs-dist/webpack.js 27:18-64
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/views/modal/ViewerPDF.vue?vue&type=script&lang=js&
 @ ./src/views/modal/ViewerPDF.vue?vue&type=script&lang=js&
 @ ./src/views/modal/ViewerPDF.vue
 @ ./src/router/router.ts
 @ ./src/renderer.js
 @ multi ./node_modules/webpack-dev-server/client?http://192.168.1.15:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/renderer.js
```

It seems that Webpack update change little tricky things about loading. It is not the first time that I have this kind of issue with library that use webpack. Those are my libraries about webpack :  

      "webpack": "^5.5.1",
      "webpack-build-notifier": "^2.1.0"
      "electron-webpack": "^2.8.2",
      "electron-webpack-eslint": "^6.0.0",
      "electron-webpack-ts": "^4.0.1",
      "electron-webpack-vue": "^2.4.0",
      "webpack-cli": "3.3.10",
      "html-webpack-plugin": "^4.5.0",

**Comment by timvandermeij** [comment]
`tapAsync` is not used in our codebase, so it's very likely related to the way you use PDF.js in combination with Electron/Vue, which is unfortunately not something we can provide meaningful assistance for given that we're not familiar with both of them.
