### ISSUE TITLE
default values set in about:config not applied

### ISSUE THREAD

**Issue by nousernameavailableanymore** [mozilla/pdf.js#12803]
I set the default values in about:config for
`pdfjs.defaultZoomValue` to `page-fit` and
`pdfjs.scrollModeOnLoad` to `1`

However, when opening a new pdf, the zoom level still gets set to "Automatic" and the scrolling remains vertical

Configuration:
- Web browser and its version: Firefox 84.0.1 (64-bit)
- Operating system and its version:  Windows 10 1909

Steps to reproduce the problem:
1. set the values in about:config as described above
2. open new pdf

What is the expected behavior? (add screenshot)
Pdf viewer should use the configured default values (page-fit and horizontal scrolling)

What went wrong? (add screenshot)
Pdf viewer ignores values set in about:config and opens pdf via default settings

**Comment by Snuffleupagus** [comment]
WFM, when testing in Firefox Nightly 86 (on Windows) with e.g. https://ctan.uib.no/info/lshort/english/lshort.pdf and https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf

> However, when opening a new pdf,

Please provide the PDF document in question, as asked for in the ISSUE_TEMPLATE.

**Comment by nousernameavailableanymore** [comment]
Found that issue is only related to Nextcloud who seem to have their own implementation of pdf.js in the "PDF viewer" app.

If you, by chance, know how to set the default values with their implementation (I already tried changing default values in /var/www/nextcloud/apps/files_pdfviewer/vendor/pdfjs/web/viewer.js, but no success), that would be great.
Otherwise, this here can be closed.

Thank you.

**Comment by Snuffleupagus** [comment]
> Found that issue is only related to Nextcloud who seem to have their own implementation of pdf.js in the "PDF viewer" app.

We have no idea what "Nextcloud" is here (I'd guess that it's some kind of web-app), but it's in no way related to the built-in Firefox PDF viewer; hence it's (obviously) impossible to use the *Firefox* preferences to change settings in a web-app.

Please direct any further support questions directly to "Nextcloud", since that's not something we support here!
