### ISSUE TITLE
missing callback() in l10n.js

### ISSUE THREAD

**Issue by kjk** [mozilla/pdf.js#12809]
In https://github.com/mozilla/pdf.js/blob/master/external/webL10n/l10n.js#L322 there probably should be `callback()` or else the promise `await this._initializeL10n();` in https://github.com/mozilla/pdf.js/blob/master/web/app.js#L269 is never resolved if this particular code path is taken (happened to me while developing a slightly custom viewer).

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
First of all, when opening an issue, please remember to always provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Secondly, that file originates from the https://github.com/fabi1cazenave/webL10n project, and for all intents and purposes the *upstream* file has the same behaviour as far as I can tell: https://github.com/fabi1cazenave/webL10n/blob/4e33df19d9755d982102c7c70746a42159094a32/l10n.js#L339-L341

**Comment by timvandermeij** [comment]
Yes, if this is in fact a problem it should be addressed upstream, or time should be invested into #10075.
