### ISSUE TITLE
TextLayer rendered too small in PDF's created with PDFProducer

### ISSUE THREAD

**Issue by gertot** [mozilla/pdf.js#12811]
[PdfProducer.pdf](https://github.com/mozilla/pdf.js/files/5763534/PdfProducer.pdf)

Configuration:
- Web browser and its version: Version 87.0.4280.88 (Offizieller Build) (x86_64)
- Operating system and its version: MacOS Big Sur, Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: no we use the library in our own app but the error is also in demo viewer of pdf.js visible

Steps to reproduce the problem:
1. Open the embedded Document in pdf.js demo viewer
2. The text layer is rendered but the spans are too small and have an incorrect scaling. see embedded image
<img width="1792" alt="Bildschirmfoto 2021-01-04 um 08 22 13" src="https://user-images.githubusercontent.com/1286150/103512149-8a5f5180-4e68-11eb-9768-18d91ed39155.png">

What is the expected behavior? the textlayer should be rendered in correct width

What went wrong? textlayer span objects are too small and have an incorrect scaling

**Comment by SushantAA** [comment]
I want to work on this  issue
pls assign me

**Comment by gertot** [comment]
any progress??

**Comment by calixteman** [comment]
I'll have a look on this.

**Comment by calixteman** [comment]
This is fixed by https://github.com/mozilla/pdf.js/pull/13257.

**Comment by timvandermeij** [comment]
Closing since this is now fixed.
