### ISSUE TITLE
 Can I add specific event to pdf?

### ISSUE THREAD

**Issue by chaechae7** [mozilla/pdf.js#12814]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. After converting pdf to html format, I want to generate javascript-type event in the generated <span> tag. Is there a way?
2. The pdf is composed of ifream, and the tag is not accessible.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since not all required information is provided. It's also not at all clear what this means: all PDF.js does is render the PDF to a canvas and overlay layers for text/annotations, and those are simple DOM elements that you can attach events to like all other DOM elements.

**Comment by chaechae7** [comment]
Briefly, I would like to know the order of execution of eventbus.

I want all pdfs to fire a custom event after loading.


In document.addEventListener

1.
	  document.addEventListener('localized', function(e) {
	    console.log('localized');
	    //PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
	  }, true);

2.

	  document.addEventListener('DOMContentLoaded', function(e) {
	    console.log('DOMContentLoaded');
	    //PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
	  }, true);

3.
	  document.addEventListener('webviewerloaded', function(e) {
	    console.log('webviewerloaded');
	    //PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
	  }, true);

4.
	  document.addEventListener('pagesloaded', function(e){
		console.log('pagesloaded');
		//PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true);
	  }, true);

I experimented, and I thought it was the order of 3->2-> 1 or 4.

However, I found a problem where events other than 3 and 2 do not occur.

Also, PDFViewerApplicationOptions.set('eventBusDispatchToDOM', true); The code is not working properly. what's the reason?

The version of pdf.js is the latest version listed on the page.

**Comment by chaechae7** [comment]
@timvandermeij

I got it wrong.
The events (1,4) I added didn't exist.

I just want to fire a custom event after all pdf has been created.

**Comment by chaechae7** [comment]
I solved the problem!
I utilized createEvent / addEventListener.

However, I have one question.
For example,
<span>test</span>
I want to delete the text object in this part.
I tried deleting with js, but there is a problem that text is not deleted in pdf.

Is pdf.js secure?
Or is it my problem?
