### ISSUE TITLE
Rendering Issue in Chrome: Lose some green dots in rendering one PDF exported from AutoCAD

### ISSUE THREAD

**Issue by ahwyX100** [mozilla/pdf.js#12810]
[Attach](url
[Test1.pdf](https://github.com/mozilla/pdf.js/files/5763185/Test1.pdf)
)

Configuration:
- Browser: Chrome 87.0.4280.88
- OS: MacOS 10.15.4
- PDF.js version: 2.5.207

Steps to reproduce the problem:
1. Open the viewer.html in above pdf.js package
2. Open the attached **_Test1.pdf_** in the viewer.html

What is the expected behavior? (add screenshot)
All contents should be rendered properly, just like the attached **_right.png_**
![right](https://user-images.githubusercontent.com/22936768/103504237-ca86fa00-4e91-11eb-9e7a-bb32aad68229.png
)

What went wrong? 
Some green dots in left side are lost, as highlighted in the **_wrong.png_**. And this issue only exists in the Chrome browser, it renders properly in safari and Firefox.
![wrong](https://user-images.githubusercontent.com/22936768/103504252-d8d51600-4e91-11eb-8e49-e59280aab488.png)

**Comment by Snuffleupagus** [comment]
> And this issue only exists in the Chrome browser, it renders properly in safari and Firefox.

That clearly points to a canvas-related bug in Chrome, rather than in the PDF.js library, and as such there's unfortunately nothing that can be done about this *here*.

**Comment by ahwyX100** [comment]
> > And this issue only exists in the Chrome browser, it renders properly in safari and Firefox.
> 
> That clearly points to a canvas-related bug in Chrome, rather than in the PDF.js library, and as such there's unfortunately nothing that can be done about this _here_.

But it works fine [here](https://www.pdftron.com/webviewer/demo/) in Chrome . I opened the same file and by inspecting the element it renders the content in the canvas as well.
