### ISSUE TITLE
Highlighing not happening when page is still processing to show

### ISSUE THREAD

**Issue by vishal151092** [mozilla/pdf.js#12818]
Configuration:
- Web browser and its version: chrome 87.0
- Operating system and its version: Windows 10
- PDF.js version: 2.2.228
- Is a browser extension: no

Steps to reproduce the problem:
1.  I have different pages to show through pdfjs, to which I scroll when different buttons are clicked. Here I highlight the text on pdf.
2. Issue is, when I load pdf page through click for first time. It scrolls to correct page and shows a loading symbol for very small time. 
3. Due to this highlighting does not happen. If the page is already scrolled once before, then this loading symbol doesn't occur, so highlighting works fine.
4. I don't want to hardcode setTimeout for highlighting as page may take few seconds to show.

```
iframe2.PDFViewerApplication.page = myPageNumber;
 //then i write highlighting code after scrolling to page

```

App is in development phase so not hosted it. Please help me by suggesting some way where I can highlight the page once page is visible correctly. 

If all pages can be processed at a time that can also be helpful.
Thanks 
Vishal

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.2.228

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

It's impossible for anyone to follow this, without a *runnable* example; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> I don't want to hardcode setTimeout for highlighting as page may take few seconds to show.

Then you should listen for the one of the custom events, which one depends on *exactly* what you want to chive, and based on https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage that can be done e.g. by something along these lines:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplication.initializedPromise.then(function() {
    // The viewer has now been initialized.

    PDFViewerApplication.eventBus.on("pagechanging", function(event) {
      console.log("The page container is now visible", event.pageNumber);
    });
    PDFViewerApplication.eventBus.on("pagerendered", function(event) {
      console.log("The page is now rendered", event.pageNumber);
    });
    PDFViewerApplication.eventBus.on("textlayerrendered", function(event) {
      console.log("The textLayer is now rendered", event.pageNumber);
    });
  });
});
```

> If all pages can be processed at a time that can also be helpful.

That's a really bad idea in general, which is why the FAQ explicitly advise against it: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by vishal151092** [comment]
Hi, I was reading about **disableAutoFetch**  . Since, in my case pdf will be at max 10 pages, so rendering all pages on load should not impact.  Please let me know how can I set PDFJS.disableAutoFetch to false from my end.

**Comment by timvandermeij** [comment]
You can pass that option when calling `getDocument`; see https://github.com/mozilla/pdf.js/blob/6516ff20b504eae3280c52f67a8277bebceb2537/src/display/api.js#L174-L180.
