### ISSUE TITLE
webpack instructions can't work with last worker-loader versions

### ISSUE THREAD

**Issue by fdaveine** [mozilla/pdf.js#12813]
I followed the recommendations [given here](https://github.com/mozilla/pdf.js/blob/master/examples/webpack/README.md) to use pdf.js `2.6.347` with webpack.

It mention that:
> ...(configuring worker-loader is not necessary; just installing it is sufficient).

It's no longer the case with the last version of `worker-loader` (`v3.0.7`), and since the version [v3.0.0](https://github.com/webpack-contrib/worker-loader/releases/tag/v3.0.0) I believe, due to a breaking change in this package:

![image](https://user-images.githubusercontent.com/12005932/103556603-56a91980-4eb2-11eb-98aa-ad8455e7edba.png)

The `filename` option now [default to [name].worker.js](https://github.com/webpack-contrib/worker-loader#filename), which cause webpack to generate a `pdf.worker.worker.js` file instead of the expected `pdf.worker.js`.

To make webpack generate the proper file, I had to update [a line inside /external/dist/webpack.js](https://github.com/mozilla/pdf.js/blob/master/external/dist/webpack.js#L19) as mention bellow:

```javascript
var PdfjsWorker = require("worker-loader?esModule=false&filename=[name].js!pdfjs-dist/build/pdf.worker.js");
```
(I added `&filename=[name].js` option, for `worker-loader` not to add its new suffix)

**Comment by fdaveine** [comment]
Let me know if it would be helpful that I make a PR for this.

**Comment by timvandermeij** [comment]
A PR for this would be very welcome, most likely together with a small change to the README file to say that at least `worker-loader` version 3.0.0 or higher is required now; thanks!
