### ISSUE TITLE
pdf download

### ISSUE THREAD

**Issue by chaechae7** [mozilla/pdf.js#12821]
I have implemented a pdf viewer with ifream.
I added a custom event to add something like an image to a specific part.
However, the problem is that there was no specific image added to the original pdf when downloading.

Is there any way to export something I've added to the original pdf?

Do you provide this?

**Comment by Snuffleupagus** [comment]
Please see the description of this project in https://github.com/mozilla/pdf.js#pdfjs-, from which I'm quoting:
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.

Futhermore, please see the FAQ: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations

Hence *this* library doesn't allow the kind of editing of existing PDF document that you ask about!
