### ISSUE TITLE
IFrame.contentWindow.postMessage(base64EncodedPdfString) no longer works in pdf.js v2.5.207

### ISSUE THREAD

**Issue by SlavaDonnikov** [mozilla/pdf.js#12833]
### The following way to set up the content of the pdf viewer no longer works in pdf.js v2.5.207:

Markup:
`<iframe id="pdfFrame" aura:id="pdfFrame" src="{! $Resource.pdfjs + '/pdfjs/web/viewer.html'}" onload="{!c.loadPdf}"/>`

JS:
```
loadPdf: function(base64EncodedPdfString) {
    document.getElementById('pdfFrame').contentWindow.postMessage(base64EncodedPdfString, location.origin);
}
```

The following snippets don't work either:
```
document.getElementById('pdfFrame').contentWindow.postMessage(base64EncodedPdfString, '*');
document.getElementsByTagName('pdfFrame')[0].contentWindow.postMessage(base64EncodedPdfString, '*');
component.find('pdfFrame').getElement().contentWindow.postMessage(base64EncodedPdfString,  '*');
```

**Am I missing something important?**

Configuration:
- Web browser and its version: chrome 7.0.4280.141, safari 14.0.1 (15610.2.11.51.10, 15610)
- Operating system and its version: masOS Catalina 10.15.7
- PDF.js version: 2.5.207
- Is a browser extension: no

_The following example integrates the pdf.js library with the **Salesforce Aura Component**._

**Comment by Snuffleupagus** [comment]
> The following way to set up the content of the pdf viewer no longer works in pdf.js v2.5.207

There's no changes in the PDF.js library, and/or its default viewer, which would explain the issues your seeing; hence the assumption that whatever the problem is started with that a particular PDF.js version might be a red herring.

However, if you're convinced that it's a PDF.js regression, you should be able to use `git bisect` to find the offending change; see https://github.com/mozilla/pdf.js/wiki/Bisecting-a-Regression

> The following example integrates the pdf.js library with the **Salesforce Aura Component**.

We know nothing about "Salesforce Aura Component", and thus we (obviously) cannot provide support for that here.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by SlavaDonnikov** [comment]
I'm following [this](https://medium.com/my-journey-with-salesforce1-platform/pdf-viewer-lightning-component-f96e6a5704ab) solution and it does work with the pdf.js library included in the solution's git repo, but not with the latest one.

**Comment by Snuffleupagus** [comment]
> I'm following [this](https://medium.com/my-journey-with-salesforce1-platform/pdf-viewer-lightning-component-f96e6a5704ab) solution and it does work with the pdf.js library included in the solution's git repo, but not with the latest one.

Then please direct further support question *there*, rather than here, since we cannot provide assistance for third-party implementation of the PDF.js library.

**Comment by shanechan517** [comment]
Hi @SlavaDonnikov,

Just wondering if you were able to resolve this issue?
I am actually having similar issue while post data to view.html in LWC with the newest pdf.js version.
Thanks.
