### ISSUE TITLE
Highlighted element is not scrolled into the viewport even if scrollMatches set to true/false

### ISSUE THREAD

**Issue by Sathishsundar07** [mozilla/pdf.js#12832]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Macos
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:
1. execute a find command and check for the hightlighted element
2. if the highlighted text is at end of the page or not in viewport the scrollintoview is not behaving properly.

What is the expected behavior? (add screenshot)
highlighted element should be scrolled into the viewport after a match is found.
What went wrong? (add screenshot)
After executing find command, highlighted element is not scrolled into the viewport even if scrollMatches set to true/false,
as of now it only scrolls to the top of the page.

```
this.pdfFindController.executeCommand("find", {
        query: this.text,
        caseSensitive: false,
        phraseSearch: true,
        highlightAll: false,
        scrollMatches: true,
      });
```
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Sathishsundar07** [comment]
@Snuffleupagus if `scrollMatches` not a valid option, what is the configuration to bring the highlighted text to the viewport?

**Comment by Snuffleupagus** [comment]
> what is the configuration to bring the highlighted text to the viewport?

That happens *by default*, and there's no way to turn if off, which you should've been able to reproduce yourself in the demo-viewer linked above.
Unless you provide a *runnable* example, as asked for, which shows the problem, this issue will be closed as INVALID.
