### ISSUE TITLE
Annotation text does not wrap and overflows popup

### ISSUE THREAD

**Issue by eibens** [mozilla/pdf.js#12847]
I am unable to share the particular PDF at this time. If it is really necessary, I can get a file with an annotation, but I doubt it is a specific problem.

Configuration:
- Web browser and its version: Mozilla Firefox for Ubuntu 84.0.2 (64-bit)
- Operating system and its version: Ubuntu 20.04
- PDF.js version: unknown
- Is a browser extension: no

The text should be contained within the annotation popup like so:

![image](https://user-images.githubusercontent.com/6533896/104124137-4f20bf00-534f-11eb-817d-d9ddb7256779.png)

Instead, it overflows.

![image](https://user-images.githubusercontent.com/6533896/104124112-331d1d80-534f-11eb-994c-e6a2a0b4680b.png)

The problem seems to be caused by the `.pdfViewer.scrollHorizontal, .spread` CSS rule in `resource://pdf.js/web/viewer.css` which specifies `white-space: nowrap;`. At least I am able to fix it by adding `white-space: normal` to the `.annotationLayer .popup` rule in the DOM inspector.

**Comment by timvandermeij** [comment]
I can reproduce this with a sufficiently long annotation text. Thank you for reporting this, I'll work on a fix.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
