### ISSUE TITLE
load pdf error, message: Failed to load font 'g_d0_f4': 

### ISSUE THREAD

**Issue by this-spring** [mozilla/pdf.js#12849]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome and 87.0.4280.88
- Operating system and its version: macos and  10.14.6
- PDF.js version:2.6.347
- Is a browser extension:no

Steps to reproduce the problem:
```
<html>
    <meta charset="utf-8">
    <body>
        <canvas id="the-canvas" width="400px" height="600px"></canvas>
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js" integrity="sha512-Z8CqofpIcnJN80feS2uccz+pXWgZzeKxDsDNMD/dJ6997/LSRY+W4NmEt9acwR+Gt9OHN0kkI1CTianCwoqcjQ==" crossorigin="anonymous"></script>
    <script>
        var loadingTask = pdfjsLib.getDocument('https://klcs01.kaochong.com/courseware/caebe2856d7b48631c7a876c7fa70378/1.pdf');
        loadingTask.promise.then(function(pdf) {
            pdf.getPage(1).then(function(page) {
                var scale = 1.5;
                var viewport = page.getViewport({ scale: scale, });

                var canvas = document.getElementById('the-canvas');
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                var renderContext = {
                canvasContext: context,
                viewport: viewport
                };
                page.render(renderContext);
            });
        });
    </script>
</html>
```
What is the expected behavior? (add screenshot)
no error message 
Warning: Failed to load font 'g_d0_f4': 'SyntaxError: Invalid font data in ArrayBuffer.'.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/58899489/104145108-c4000180-5400-11eb-9beb-5be4ade8cec8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> What is the expected behavior? (add screenshot)
> no error message
> Warning: Failed to load font 'g_d0_f4': 'SyntaxError: Invalid font data in ArrayBuffer.'.

But that's clearly only a *warning* and not an actual breaking error, however the document still renders correctly as far as I can tell (although I don't speak the language used in the document).

Given that there's no actual rendering bug here, this issue can simply be closed.
