### ISSUE TITLE
PDF having font "STSong-Light" is not rendering

### ISSUE THREAD

**Issue by Awadheshpd** [mozilla/pdf.js#12859]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
1. We have PDF with font-family "STSong-Light",
2. Rendering it using SVG methods, its partially loading.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/16066109/104474873-7643ee80-55e4-11eb-8e56-7a2510ebcb9f.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/16066109/104474982-94115380-55e4-11eb-8a97-4f391ca02613.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part is *required* in order for *any* issue to be actionable/valid.

> PDF.js version: 2.3.200

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Rendering it using SVG methods, its partially loading.

As mentioned in the Wiki, the SVG-backend is not officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by Awadheshpd** [comment]
@Snuffleupagus , Thanks for your reply.
With canvas backend also, the behavior is same. Is there any way to make it work for fonts that are not there in pdfjs library.
