### ISSUE TITLE
renderTask.promise resolves too quickly

### ISSUE THREAD

**Issue by kevinbeal** [mozilla/pdf.js#12858]
Attach (recommended) or Link to PDF file here: 
[test.pdf](https://github.com/mozilla/pdf.js/files/5809577/test.pdf) Or just use the Mozilla whitepaper from the demo. They both do it.

Configuration:
- Web browser and its version: Brave 1.14
- Operating system and its version: Ubuntu 20
- PDF.js version: Latest stable release and whatever version the demo viewer uses
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. put a breakpoint at L669 in `pdf_page_view.js`
3. Reload the page and witness that the page has not finished rendering
4. 
![image](https://user-images.githubusercontent.com/855252/104475227-b15a0980-5573-11eb-9ddf-0740a71f2f0d.png)

What is the expected behavior? (add screenshot)
It should be fully rendered when the promise resolves
![image](https://user-images.githubusercontent.com/855252/104475045-7d7ee400-5573-11eb-8c0b-daa28109e433.png)

What went wrong? (add screenshot)
It is not fully rendered. It is only partially rendered.
![image](https://user-images.githubusercontent.com/855252/104475180-a56e4780-5573-11eb-89cf-055f2ffd1b25.png)

**Comment by kevinbeal** [comment]
This an issue for me because I'm trying to implement my own print logic for my own viewer. It looks like the viewer you guys wrote encodes the pdf pages into data urls and then resolving the readiness of the print via the page's img `onload` callback. It makes sense then why your print logic has fully rendered pages prior to showing the print dialog. That's clever.

I may need to do something like that.

**Comment by kevinbeal** [comment]
> It makes sense then why your print logic has fully rendered pages prior to showing the print dialog.

Actually, I just realized it's getting the data-url from the canvas which, in this case, doesn't have all the data when the promise resolves. There must be something else which explains why the page is rendered by the time the print dialog shows.

Is it just a coincidence that the page is fully rendered in time by the time various other asynchronous process complete before showing the dialog?

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Brave 1.14

Testing with Mozilla Firefox Nightly 111.0a1 and it's *built-in* PDF Viewer, which uses PDF.js `3.3.55` [1d683708e], I can't seem to reproduce this issue.
 - Is this still an issue, using the latest PDF.js version? Please fine currently supported versions at https://mozilla.github.io/pdf.js/getting_started/#download
 - Can you reproduce it in other browsers, except Brave (since it may very well be a browser-specific issue)?

**Comment by BryarGH** [comment]
I have the same issue, anyone can help?
