### ISSUE TITLE
Pdf not rendered correctly

### ISSUE THREAD

**Issue by clempe** [mozilla/pdf.js#12856]
Attach (recommended) or Link to PDF file here:
[SEPA-Länder.pdf](https://github.com/mozilla/pdf.js/files/5808018/SEPA-Lander.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 44.18362.449.0 - Microsoft EdgeHTML 18.18363
- Operating system and its version: Windows 10
- PDF.js version: 2.7.425
- Is a browser extension: no

What went wrong? (add screenshot)
Pdf not rendered properly 
![image](https://user-images.githubusercontent.com/491495/104441160-a0b98b80-5593-11eb-98ce-2b8ab6e098bc.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/es5/web/viewer.html
[](url)

**Comment by Snuffleupagus** [comment]
WFM, with PDF.js version `2.7.510` in Firefox Nightly 86 (on Windows).

**Comment by clempe** [comment]
> WFM, with PDF.js version `2.7.510` in Firefox Nightly 86 (on Windows).

Yes works with Chrome, Firefox and Safari... but Edge (non Chromium) does not work. 
I did not have that problem with older PDF.JS version ~2.5

**Comment by Snuffleupagus** [comment]
> Yes works with Chrome, Firefox and Safari... but Edge (non Chromium) does not work.

Please note "Edge (non Chromium)" is explicitly unsupported now, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by clempe** [comment]
> > Yes works with Chrome, Firefox and Safari... but Edge (non Chromium) does not work.
> 
> Please note that "Edge (non Chromium)" is explicitly unsupported now, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
