### ISSUE TITLE
Weird behaviour of an input in a form

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12865]
Attach (recommended) or Link to PDF file here:
https://github.com/mozilla/pdf.js/files/2321540/issue6127.pdf

When entering 13 chars in the 3rd text field (i.e. `NUMERO D’IMMATRICULATION`) the first one appears in the first slot and when the input loses the focus everything looks correct.

With focus:
![image](https://user-images.githubusercontent.com/5641725/104729511-d51a7c80-5738-11eb-8d5e-a9e7818adce8.png)

Without:
![image](https://user-images.githubusercontent.com/5641725/104729632-01ce9400-5739-11eb-9d4d-18c75a152330.png)

The issue is reproductible with firefox nightly and locally on master with firefox and chrome (`gulp server`).

**Comment by somil24** [comment]
Sir I would like to work on this issue and also it would be my first contribution so if you could guide me through.

**Comment by timvandermeij** [comment]
Fixed by #13690.
