### ISSUE TITLE
How to display PDF content with request return type of "content type: application / octet stream"?

### ISSUE THREAD

**Issue by lx4556332** [mozilla/pdf.js#12872]
How to display PDF content with request return type of "content type: application / octet stream"?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this issue will be closed as INVALID since it unfortunately contains no actionable information.
