### ISSUE TITLE
Still contain arrow functions when try to generate es5 built out files

### ISSUE THREAD

**Issue by ahwyX100** [mozilla/pdf.js#12873]
Configuration:
- Operating system and its version: MacOS 10.15.7
- PDF.js version: 2.7.0

Steps to reproduce the problem:
execute `gulp dist` in root folder

What is the expected behavior?
Should generate built out files which are only for es5.

What went wrong?
Still contain arrow functions in built out pdf.js which can not work in IE11, like
```
(() => {
  __w_pdfjs_require__.nmd = (module) => {
    module.paths = [];
    if (!module.children) module.children = [];
      return module;
    };
})();
```

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.7.0

That *exact* version number doesn't exist.

> Still contain arrow functions in built out pdf.js which can not work in IE11,

As mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is no longer supported.
More generally, browsers/environments without arrow function support are simply too old to be supported by PDF.js; see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#browser_compatibility

**Comment by chiptime** [comment]
Hi,
i had same problem.
Versions:
 + pdf: 2.7.667
![image](https://user-images.githubusercontent.com/22093450/106646304-e0213980-658d-11eb-90ef-2ff3a7594ca8.png)
