### ISSUE TITLE
Get all glyphs and their bounding boxes post rendering?

### ISSUE THREAD

**Issue by inf3rnus** [mozilla/pdf.js#12884]
Hi there, been digging into this package for months now :P, (two thumbs up of course!)

I'm wondering if in the API's there is a method available for extracting each glyph and its bounding box with respect to the post-rendered canvas/each glyphs UTF-8 representation. (Forgive me for not being super well versed in the pdf format.)

For example, python has a package called pdfminer which allows one to create an XML doc out of a PDF.

I've run some manual tests using these bounding boxes and they work perfectly.

Here's a sample output:

```
<textline bbox="134.548,535.243,202.881,545.206">
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="134.548,535.243,141.741,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">G</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="141.741,535.243,146.722,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">o</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="146.722,535.243,151.704,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">o</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="151.704,535.243,156.685,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">g</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="156.685,535.243,159.454,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">l</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="159.454,535.243,163.878,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">e</text>
<text> </text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="166.369,535.243,173.014,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">R</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="173.014,535.243,177.437,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">e</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="177.437,535.243,181.312,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">s</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="181.312,535.243,185.736,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">e</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="185.736,535.243,190.159,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">a</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="190.159,535.243,193.477,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">r</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="193.477,535.243,197.900,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">c</text>
<text font="BVZQFF+NimbusRomNo9L-Regu" bbox="197.900,535.243,202.881,545.206" colourspace="DeviceGray" ncolour="0" size="9.963">h</text>
<text>
</text>
</textline>
```

I've explored things related to the text layer, such as getOperatorList(), and getTextContet(), but those are not what I'm looking for... I'm interested in trying to retrieve the actual rendering position of each glyph.

Any help would be greatly appreciated!

Best,
Aaron

**Comment by Snuffleupagus** [comment]
Issue #7996 is possibly (somewhat) relevant here.

However note that since this functionality isn't something that either the rendering or text-extraction parts of the PDF.js library would need, it's unfortunately quite unlikely that this's a feature that would be added to the library. (It'd require extra parsing, and a lot more data being sent between threads, for something that's essentially unused from the general library perspective.)

**Comment by timvandermeij** [comment]
I agree with the above; there is simply not really a point for us to implement this feature if it's practically unused and requires more data parsing. Of course this can be added in a custom deployment, but it's unfortunately not something we can support for now.
