### ISSUE TITLE
Get Search results

### ISSUE THREAD

**Issue by abbassss** [mozilla/pdf.js#12892]
Configuration:

Web browser and its version: Firefox 84.0.2
Operating system and its version: windows 10
PDF.js version: latest version
Is a browser extension: no

What is the expected behavior?  Does pdf.js have any method or way to return found search keys with their Coordinates
in a list or something like that?
i use PDFViewerApplication.findController.executeCommand('find',{}) to search for a key in pdf, but what i need is to get all of the found keys and after that user can jump into their position

**Comment by timvandermeij** [comment]
No, there is no API for that. How it works in the viewer is that the find controller is used to find and highlight the search results, but there is no way to get all search results in a list because that would require parsing all pages, even potentially unloaded once, and we don't use such a list in the viewer.

**Comment by abbassss** [comment]
So if you don't parse pdf pages, then how do you search, find and highlight all found search keys ? this is what happens when we use findbar graphically.
My goal is to be able to jump to its position after finding the key programmatically

**Comment by timvandermeij** [comment]
Yes, my remark about the pages was not entirely correct: in `_extractText` we do loop over all pages, but even though we don't render them we do extract the text content.

In any case, this issue is a duplicate of #7605.

**Comment by abbassss** [comment]
Thanks for your reply

I found a way to get the list of keys found with their page numbers and I will explain about it in the issue you mentioned above

Two more questions:

1- For find a search key you have below method in viewer.js:

```
function webViewerFind(evt) {
  PDFViewerApplication.findController.executeCommand("find" + evt.type, {
    query: evt.query,
    phraseSearch: evt.phraseSearch,
    caseSensitive: evt.caseSensitive,
    entireWord: evt.entireWord,
    highlightAll: evt.highlightAll,
    findPrevious: evt.findPrevious
  });
}
```

How does this "find" works?

```"
find" + evt.type, {
    query: evt.query,
    phraseSearch: evt.phraseSearch,
    caseSensitive: evt.caseSensitive,
    entireWord: evt.entireWord,
    highlightAll: evt.highlightAll,
    findPrevious: evt.findPrevious
  }
```

How can i see "find" implementation? is its body implementation public or private? because i like to read it and do some changes in it and i didn't see any implementation for it in viewer.js

2- What is the properties of "evt" in viewer.js? it seems after you search for a key, you keep the results in "evt" object and use it for "findNext" or "findPrev". is there any way to see what does happen inside of "evt" ?

Thanks.

**Comment by timvandermeij** [comment]
The "find" command is handled here: https://github.com/mozilla/pdf.js/blob/dcd1589b2cfcdc5cab1924ea9d4cda014114e2ab/web/pdf_find_controller.js#L146

**Comment by abbassss** [comment]
Thank you.
