### ISSUE TITLE
Letter Spacing Problem In Reacjs Cavnas Rendering

### ISSUE THREAD

**Issue by alibakhshiilani** [mozilla/pdf.js#12894]
`
import React, { useEffect, useState, useRef, useCallback } from 'react';
import pdfjsLib from "pdfjs-dist/build/pdf";
import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
import PageViewer from './PageViewer';
import { checkValue } from "../../../constant/helper";
import { AnnotationFactory } from "annotpdf";
import BottomSheet from '../../../components/BottomSheet';
import PageNumber from './pageNumber';
import { CheckOutlined } from '@ant-design/icons';

export default function PdfViewer({url,setPdfLoading}){

  pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker;

  const [pdfRef, setPdfRef] = useState();
  const [currentPage, setCurrentPage] = useState(null);
  const [showChatBox, setShowChatBox] = useState(false);
  const [scrollPageNumber, setScrollPageNumber] = useState(1);
  const [pages,setPages] = useState({});

  useEffect(() => {
    setPdfLoading(true)
    loadPdf();
  }, []);

  const getPageData = () => {

    pdfRef.getPage(currentPage).then(function(page) {
     
      if(currentPage < pdfRef.numPages){
        setPages({...pages,[currentPage]:page})
        setCurrentPage(currentPage+1)
      }else{
        setPdfLoading(false)
      }

    });  

  }

  const loadPdf = () => {
    const loadingTask = pdfjsLib.getDocument(url);
    loadingTask.promise.then(loadedPdf => {
        
        setPdfRef(loadedPdf);
        setCurrentPage(1)

    })
  }

  useEffect(() => {
    if(pdfRef){
      getPageData();
    }
  }, [currentPage]);

  return (
    <div style={{paddingTop:"80px"}}>

      <PageNumber 
        scrollPageNumber={scrollPageNumber}
      />

        <div
              className="submit_pdf"
              onClick={(event) => {

              }}
        >
              <CheckOutlined />
        </div>

      {
        Object.keys(pages).map((index) => {
            return (
              <PageViewer page={pages[index]} setShowChatBox={setShowChatBox} url={url}/>
            )
        })
      }

      <BottomSheet
        isOpen={showChatBox}
        classNames="archive-lock-popup"
        viewerClassName="archive-lock-popup-viewer right-text"
        height={3000}
      >
        
      </BottomSheet>

    </div>
    );

}
`

-----
`
import React, { useEffect, useState, useRef, useCallback } from 'react';
import pdfjsLib from "pdfjs-dist";

// import * as PDFJSMain from "pdfjs-dist/build/pdf";
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer"

import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
import { getWindowDimensions,errorMessageHandler } from "../../../constant/helper";
// import { AnnotationFactory } from "annotpdf";
import { findByXY } from '../utils';
import { getAnnotationFilesService } from '../pdfEditor.api';
import { message } from 'antd';
// import pdfjsViewer from "pdfjs-dist/web/pdf_viewer";

export default function PageViewer({page,setShowChatBox}){

  const canvasRef = useRef();

  // const pdfjsViewer = window["pdfjs-dist/web/pdf_viewer"];

  pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker;

  console.log("pdfjsViewer",PDFJSViewer)

  useEffect(async () => {
      
        renderPage()

  }, []);

  async function renderPage () {

        let viewport = page.getViewport(1);
  
        const windowSize = getWindowDimensions();
  
        const scale = windowSize.width / viewport.width;
        viewport = page.getViewport(scale);
  
        const canvas = canvasRef.current;

        canvas.height = viewport.height;
        canvas.width = viewport.width;

        const renderContext = {
          canvasContext: canvas.getContext('2d'),
          viewport: viewport
        };

        const annotations = await page.render(renderContext).promise.then(function () {
        
          return page.getAnnotations();;
          
        });

        console.log('Page annotations',annotations);
  
        canvas.addEventListener("click",async (e)=>{

          annotationClickHandler(e,annotations,scale,canvas)
  
        })

  }

  async function getAnnotationFiles (sessionId,uuid) {

    await getAnnotationFilesService(sessionId,uuid)
          .then((res)=>{
            console.log("res",res)
          })
          .catch((error)=>{
            message.error( errorMessageHandler(error) )
          })
            
  }

  async function annotationClickHandler(e,annotations,scale,canvas){
    // setShowChatBox(true);

    let x = e.pageX - canvas.offsetLeft;
    let y = e.pageY - canvas.offsetTop;

    [x, y] = page.getViewport(scale).convertToPdfPoint(x, y);

    const annotationIndex = findByXY(annotations,x,y)

    if(annotationIndex !== -1){

      const uuid = annotations[annotationIndex].unsafeUrl.replace("ReferenceHash","");

      console.log("uuid",uuid)

      const files = await getAnnotationFiles("6005738129621d76e99e6b20",uuid);
      
    }
  }

  // return <canvas width="100%" ref={canvasRef}></canvas>;
  return <div className="pdf-page-wrapper">
    <canvas width="100%" ref={canvasRef}></canvas>
  </div>;

}

`

https://snipboard.io/nTjZkH.jpg

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this will be closed as INVALID since no actionable information is provided.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
