### ISSUE TITLE
Text layer doesn't use dir property anymore

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12909]
Some characters in:
[hebrew.pdf](https://github.com/mozilla/pdf.js/files/5869562/hebrew.pdf)
are not correct in the text layer (such as question marks).

We get text direction in `evaluator.js` but we don't use it.
It was used in the past, but it seems it has been removed:
https://github.com/mozilla/pdf.js/commit/5bd8a83c9bd7c23003b09e1cfd71422c6b083826#diff-579f2fb8055052aa97906d5fc75aeee84aa7dd9f8efcca24d8a5460d828e1de8L170

**Comment by brendandahl** [comment]
I can't remember why I removed that. I'm guessing I was planning to move it, but forgot.
