### ISSUE TITLE
Should re-render/adjust page contents when switching monitors or screen resolution

### ISSUE THREAD

**Issue by zsiegel92** [mozilla/pdf.js#12918]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Version 88.0.4324.96 (Official Build) (x86_64)
- Operating system and its version: MacOS 11.1
- PDF.js version: PDF Viewer
2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open a pdf (using the extension) in a given window
2. Move the window to another monitor with a different resolution

What is the expected behavior? (add screenshot)
I expected the pdf to re-render the page to adjust for the new resolution. The default Chrome pdf viewer does this when you "interact" with the pdf (e.g. scroll or click) - it is a little disconcerting as it takes a moment, but it is better than continuing to use the page rendered at a different resolution.

Thank you!

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Version 88.0.4324.96 (Official Build) (x86_64)

Huh; there's no actual browser *name* provided here, which makes this part unclear.

Based on the rest of the issue, I'm *guessing* that this is related to the Chromium-extension. /cc @Rob--W

**Comment by zsiegel92** [comment]
Yes, it's Chrome.

**Comment by Rob--W** [comment]
Does this issue also happen with https://mozilla.github.io/pdf.js/web/viewer.html ? The Chrome extension version hasn't been updated for a while (and I need to take a very good look at the changes since the last update before publishing a new one).

If it also happens with the online version, then it's not an extension-specific problem.

**Comment by zsiegel92** [comment]
It works the same with both local files (i.e. Chrome extension) and the page you posted.

I just noticed it DOES re-render when I change zoom or when I scroll more than 2 pages away from where I was. The Chrome built-in viewer re-renders when I scroll at all. I would have reported it as such initially if I had realized. Sorry about that!

**Comment by Snuffleupagus** [comment]
The question here is if there's an event, or some other property, that can be used to check if a browser window has been moved to another screen!?
Some, admittedly very quick, searching seem to suggest that there's no good way of getting the necessary information with Javascript here (and as always we want to avoid adding "hacks").

**Comment by Rob--W** [comment]
I haven't tested (as I'm currently not connected to an external screen), but I guess that the "resize" event may be helpful there?

**Comment by Snuffleupagus** [comment]
> I haven't tested (as I'm currently not connected to an external screen), but I guess that the "resize" event may be helpful there?

Well, we already have a "resize" event listener in the default viewer so apparently that's not enough as-is; note https://github.com/mozilla/pdf.js/blob/2194fb940dac25b3da799474a1e2a9ceb63ab18a/web/app.js#L2698-L2713

**Comment by Snuffleupagus** [comment]
Based on some quick web searches, there doesn't appear to exist any DOM method which can be used to determine (with certainty) if a window is moved from one screen to another; closing as WONTFIX for now.
