### ISSUE TITLE
Version migration error Deprecated API usage: No "GlobalWorkerOptions.workerSrc"

### ISSUE THREAD

**Issue by riosney** [mozilla/pdf.js#12917]
I'm migrating from pdfjs-dist 2.0.391 to 2.4.456.
The project is with AngularJs 1.6.9

Configuration:
- Web browser: Chrome/87.0.4280.141
- Operating system: Windows NT 10
- PDF.js version: 2.0.391

`import pdfjs from 'pdfjs-dist/build/pdf';`

`exclude: [
      path.resolve(nodeModules, 'core-js'),
      path.resolve(nodeModules, 'pdfjs-dist'),
  ],`

`const configurarFactoriesBasicas = (app) => {
    app.factory('pdfjs', () => pdfjs);
};`

erro: Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.

![pdfjs](https://user-images.githubusercontent.com/9463638/105902162-0890bd00-5ffd-11eb-8863-24d9d20c4eba.JPG)

**Comment by timvandermeij** [comment]
You need to set `workerSrc` to the location of the worker file; see https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L22-L26 for example.

**Comment by Snuffleupagus** [comment]
> I'm migrating from pdfjs-dist 2.0.391 to 2.4.456.

Please note that *neither* of those versions are supported any more; the latest releases can be found at https://github.com/mozilla/pdf.js/releases

**Comment by riosney** [comment]
@timvandermeij 
A doubt, for version 2.7.570 it is necessary to do the same thing and it is compatible with AngulaJs 1.6.9?

> You need to set `workerSrc` to the location of the worker file; see https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L22-L26 for example.

**Comment by timvandermeij** [comment]
This is for the library itself; we don't provide Angular integration nor do we officially support it.
