### ISSUE TITLE
In Win7, some numbers and page number cannot be rendered

### ISSUE THREAD

**Issue by YanXinChen1990** [mozilla/pdf.js#12927]
Attach (recommended) or Link to PDF file here:
[1.pdf](https://github.com/mozilla/pdf.js/files/5886165/1.pdf)
[4.pdf](https://github.com/mozilla/pdf.js/files/5886167/4.pdf)

Configuration:
- Web browser and its version: Chrome 88.0.4324.104
- Operating system and its version: Win7
- PDF.js version: 2.8.12
- Is a browser extension: no

Steps to reproduce the problem:
1. In Win7, Open the problematic file in PDF.js

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/47582399/106106205-28042300-6180-11eb-83cf-4a94a9cdc9cc.png)
![image](https://user-images.githubusercontent.com/47582399/106106294-49fda580-6180-11eb-9a83-cbe9f67bca67.png)
![image](https://user-images.githubusercontent.com/47582399/106106440-7f09f800-6180-11eb-8ad9-5844e32d63cf.png)
![image](https://user-images.githubusercontent.com/47582399/106106474-8cbf7d80-6180-11eb-9ec4-157cab1777fd.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [1.pdf](https://data-hz-pds.teambition.net/60126aa8aea5afdc5f2a4158a09a3135eeddab76%2F60126aa88d5fbb4340574995a5225e483e59cca1?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%271.pdf&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1611820737&x-oss-signature=S6kK930StQw1Pq6my%2F9tpquACNd7fHoHQjT53CHjbDs%3D&x-oss-signature-version=OSS2)
> [4.pdf](https://data-hz-pds.teambition.net/60126aac4c6b6d96c4ed4cd2bee3db19d4cfed87%2F60126aacd95345ae710245c89e3c2ac2115a7079?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%274.pdf&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1611820594&x-oss-signature=0KxKXNQo8H3YU0zDak%2FuTXTlCZYZDagD8E23GUYJwik%3D&x-oss-signature-version=OSS2)

Neither of those links work, which is why we ask you to *attach* the files here!

> PDF.js version: latest

Please actually provide an actual number here, since "latest" can mean any number of things and is therefore not useful.

**Comment by YanXinChen1990** [comment]
@Snuffleupagus Hi, I has re-uploaded the files and edited this issue.

**Comment by Snuffleupagus** [comment]
WFM, with Firefox Nightly 87 on Windows.

Hence this is most likely a Chrome-related issue, which means that it's unlikely to be fixable here.
