### ISSUE TITLE
Is it possible to get decrypted file data after the entered password (password-protected pdf)?

### ISSUE THREAD

**Issue by Tatsianacs** [mozilla/pdf.js#12925]
I read different issues here, API doc and I understand that it is possible to detect that the document is password-protected and prompt the user to enter the password (e.g. described here https://github.com/mozilla/pdf.js/issues/9957)/
But is it possible to get decrypted file data after the user entered the password?  (i.e. I do not need to render the document, just need to get file data after decryption when the password is entered).
Could you please explain which API method can help me (if it exists).
Thanks in advance.

**Comment by Snuffleupagus** [comment]
No; since that would require modification of the entire PDF document itself, in order to remove the encryption. 

This isn't something that the PDF.js library supports, or will support, since as mentioned in the README: 
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5:

**Comment by Tatsianacs** [comment]
Thank you for the answer
