### ISSUE TITLE
Printing with wrong default paper size

### ISSUE THREAD

**Issue by JeanMarieMace** [mozilla/pdf.js#12929]
Configuration:
- Web browser and its version: Firefox 83
- Operating system and its version: Win 10
- PDF.js version: builtin Firefox 83

Steps to reproduce the problem:
1. Open any pdf
2. Click Print
3. Click "Preferences" button on Printer popup (native OS window)

What is the expected behavior? US Letter Format instead of A4

What went wrong? A4 selected

But if i use in Firefox main menu File->Print , the default paper format is correctly set to A4 

Any ideas ?

**Comment by zeel-pathak** [comment]
Hey! I would love to work on this issue.

Will surely report soon here with some progress.

**Comment by zeel-pathak** [comment]
@JeanMarieMace  I looked upon the code..And find out that the problem is with Windows os, by default you have selected print preferences, which you can change from control panel...

Because in Ubuntu and Linux derivatives ita working fine...

**Comment by dhufnagel** [comment]
This is really annoying as it keeps resetting almost every time firefox updates. So I think this should be address in firefox itself?

**Comment by Snuffleupagus** [comment]
> So I think this should be address in firefox itself?

That's correct; unfortunately this cannot be fixed *here* and it needs to be reported in Bugzilla instead, since it's not really related to the PDF Viewer functionality as such.
