### ISSUE TITLE
Erro 'pdfjs' is not defined no-undef

### ISSUE THREAD

**Issue by riosney** [mozilla/pdf.js#12921]
I'm migrating from pdfjs-dist 2.0.391 to 2.4.456.

Configuration:
Web browser: Chrome/87.0.4280.141
Operating system: Windows NT 10
PDF.js version: 2.0.391
The project is with AngularJs 1.6.9

Code:
import pdfjs from 'pdfjs-dist/build/pdf';
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';

**Error on that line:** 'pdfjs' is not defined no-undef
pdfj.GlobalWorkerOptions.workerSrc = pdfjsWorker;

const configurarFactoriesBasicas = (app) => {
    app.factory('pdfjs', () => pdfjs);
    app.factory('sprintf', () => sprintf);
};

PS: the system is legacy and I am updating the versions little by little.

**Comment by Snuffleupagus** [comment]
> I'm migrating from pdfjs-dist 2.0.391 to 2.4.456.

As mentioned previously, neither of those versions are supported any more.

> The project is with AngularJs 1.6.9

We know nothing about Angular here, furthermore please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
