### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by thesabirkhalil** [mozilla/pdf.js#12940]
Steps to reproduce the problem:
1.  remort server pdf is not accesing 

throwing error like 
![Capture](https://user-images.githubusercontent.com/31209583/106428500-188e1e00-648f-11eb-85a9-61222bdbf323.PNG)

https://cdn.dotplus.in/Cloud/ELearningPlus/elearning/coverimage/d67bc70f7163.pdf

**Comment by Snuffleupagus** [comment]
When opening an issue, you *must* provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this issue contains no actionable information and will be closed as INVALID.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by wmo123** [comment]
Have you solved the problem yet？I‘ve met too！
