### ISSUE TITLE
toolbar image missing (only mobile browser

### ISSUE THREAD

**Issue by ruji704** [mozilla/pdf.js#12942]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: mobile webbrowser (chrome, safari.. etc)
- Operating system and its version:
- PDF.js version: pdfjs-2.6.347-dist
- Is a browser extension: 

Steps to reproduce the problem:
1.  In Pc webbrowser (chrome)  toolbar image is exposed normally 
2.  In mobile webbrowser (chrome, safari) toolbar image is missing

What is the expected behavior? (add screenshot)

![pdfjs_toolbar](https://user-images.githubusercontent.com/33620980/106542614-7b42f080-6547-11eb-8afc-4f8155ab82a0.PNG)

What went wrong? (add screenshot)
![pdfs_mobile](https://user-images.githubusercontent.com/33620980/106542758-bf35f580-6547-11eb-9e24-b7f74e9602bb.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://3.85.206.182:8080/eform/pdf

**Comment by Snuffleupagus** [comment]
> Web browser and its version: mobile webbrowser (chrome, safari.. etc)

Given that there's no version numbers provided, this information isn't really useful as-is.

> Steps to reproduce the problem:
>  1. In Pc webbrowser (chrome)  toolbar image is exposed normally
>  2. In mobile webbrowser (chrome, safari) toolbar image is missing

This suggests a *platform* issue, rather than a PDF.js one, since otherwise it'd be consistently broken *everywhere*. Furthermore, note that the default viewer was written *primarily* for desktop usage; please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
