### ISSUE TITLE
Range request caching 

### ISSUE THREAD

**Issue by samuelhalff** [mozilla/pdf.js#12953]
We are using range requests on a project so as to stream linearised pdfs.

To do so, we provide pdf.js with our file serving api url.

Yet, by design, pdf.js does not allow the user to customise the serving url. This means the url used for range request will always be the same and will not contain, for instance, range begin/end parameters.

The consequence of this is that you cannot benefit from straightforward http cache control, since the browser does not know which portion was loaded. You could perhaps implement if-range headers, but that did not seem to work out when I looked into it.

any reason why pdf.js does not allow to either customise the pdf url or add range as url parameters rather than data? Range specific urls would entail easy http cache control. We’ve forked pdf.js to add parameters to the pdf url. I would happy to submit a PR for this.

Let me know your thoughts and do of course point out any misconception on my part.

Best,

Sam

**Comment by Snuffleupagus** [comment]
> any reason why pdf.js does not allow to either customise the pdf url or add range as url parameters rather than data?

The PDF.js library already support a *fully custom* data delivery mechanism, please note this `getDocument` parameter https://github.com/mozilla/pdf.js/blob/86a4ba55c56f735e51e29a7aa368bcdcce9d8a23/src/display/api.js#L127-L128 which takes an `PDFDataRangeTransport`-instance (which you create) that then handles the data fetching, see https://github.com/mozilla/pdf.js/blob/86a4ba55c56f735e51e29a7aa368bcdcce9d8a23/src/display/api.js#L549-L625 

(Behind the scenes, this uses https://github.com/mozilla/pdf.js/blob/master/src/display/transport_stream.js)

This method is what the Firefox PDF Viewer uses, and some (admittely basic) usage examples can be found in these unit-tests: https://github.com/mozilla/pdf.js/blob/86a4ba55c56f735e51e29a7aa368bcdcce9d8a23/test/unit/api_spec.js#L2182-L2302

> I would happy to submit a PR for this.

Given the existing `PDFDataRangeTransport` functionality, we don't want to add (from a general library perspective) essentially unused/untested code for a *very specialized* use-case to the multitude of built-in data fetching mechanisms that we support (`fetch_stream.js`/`network.js`/`node_stream.js`).

---

*For future reference:* Please remember to fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.

In cases such as this it's also somewhat difficult to get a *full* picture of the problem with only a text description, hence please keep this in mind https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
