### ISSUE TITLE
File local loading get "Unexpected server response (0)" (Offline - iOS)

### ISSUE THREAD

**Issue by sgabb** [mozilla/pdf.js#12967]
Configuration:
- Web browser and its version: Safari (14.0.3 Mobile)
- Operating system and its version: iOS 14
- PDF.js version: 2.2.171 (build: c8c937c2)
- Is a browser extension: No

Hello, I'm encountering a weird error when trying to load a Blob saved locally (temporary stored in IndexedDB) while **offline (no internet connection)**.

The error is:
**PDF.js v2.2.171 (build: c8c937c2) Unexpected server response (0) while retrieving PDF "blob?:https://[app-domain]/[fileUrl]". undefined**
Where [app-domain] is the same domain where the app frontend is served (no calls to a different origin server are done) and [fileUrl] is an Object URL created from a Blob and PDF.js viewer is loaded into an iframe:

```
const file = getFileFromIndexedDB();
fileUrl = encodeURIComponent(URL.createObjectURL(file));
let viewerUrl = `assets/pdfjs/web/viewer.html`;
viewerUrl += `?file=${fileUrl}`;
this.iframe.nativeElement.src = viewerUrl;
```

This is actually a summary of what the [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/src/ng2-pdfjs-viewer.component.ts#L185) library does.

By looking at the Network tab in the Debug console, it actually seems like a security issue:
- it specify the Initiator is pdf.js:23477, which should be [here](https://github.com/mozilla/pdf.js/blob/d7afb74a6e1980da5041f376e7a7c7caef5f42ea/src/display/network.js#L108)
- the xhr requests fails because "the resource requested is insecure"
- "Failed to load resource" impossible to complete the operation (Error WebKitBlobResource 1)

The point is that I am using Service Worker and cache to serve the app, and the error happens when the network is actually offline (no problem on Android).

Anyone can give me some advice on possible solutions and/or other places where I can ask for suggestions?

Thank you in advance!

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.2.171 (build: [c8c937c](https://github.com/mozilla/pdf.js/commit/c8c937c2579812798fddc13af9d8c1df1e7ce30b))

That version is first of all *not an official* release, as found at https://github.com/mozilla/pdf.js/releases, meaning that support for it was always limited.
Secondly, that version must be from 2019, which means that it's simply way too old in general; please find the supported releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Hello, I'm encountering a weird error when trying to load a Blob saved locally (temporary stored in IndexedDB) while **offline (no internet connection)**.
> 
> The error is:
> **PDF.js v2.2.171 (build: [c8c937c](https://github.com/mozilla/pdf.js/commit/c8c937c2579812798fddc13af9d8c1df1e7ce30b)) Unexpected server response (0) while retrieving PDF "blob?:https://[app-domain]/[fileUrl]". undefined**
> Where [app-domain] is the same domain where the app frontend is served (no calls to a different origin server are done) and [fileUrl] is an Object URL created from a Blob and PDF.js viewer is loaded into an iframe:

This unfortunately sounds like a platform/browser specific bug, rather than a PDF.js one, and as such it's difficult to see that we can do anything much that here. Also, given the information provided, it's basically impossible for anyone to even reproduce this.

> ```
> const file = getFileFromIndexedDB();
> fileUrl = encodeURIComponent(URL.createObjectURL(file));
> let viewerUrl = `assets/pdfjs/web/viewer.html`;
> viewerUrl += `?file=${fileUrl}`;
> this.iframe.nativeElement.src = viewerUrl;
> ```

Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> This is actually a summary of what the [ng2-pdfjs-viewer](https://github.com/intbot/ng2-pdfjs-viewer/blob/master/src/ng2-pdfjs-viewer.component.ts#L185) library does.

Please note that since that's a *different* project, which we know nothing about it *here*, and thus it's unfortunately impossible to provide support for it here. Most likely you'll have better luck getting support directly from that project instead.

**Comment by sgabb** [comment]
@Snuffleupagus thanks for taking time to answer.
I know it is not a PDF.js direct issue, and reproducing it it is quite complicated since it happens **offline and on iOS**.
Mine was more a question than an issue, and I try to write it differently: **_"why there should be this issue with an object url of a file when offline and requesting a url of the same domain?"_**

I was hoping that anyone, which is more expert than me on the xhr call that it's emitted, could give me some insights on a possible solution.

PS I did already created also an issue directly on the mentioned library (https://github.com/intbot/ng2-pdfjs-viewer/issues/129)
