### ISSUE TITLE
Warning: Unimplemented widget field type "null", falling back to base field type.

### ISSUE THREAD

**Issue by evlgromov** [mozilla/pdf.js#12963]
When uploading a pdf file, I get Warning: Unimplemented widget field type "null", falling back to base field type at pdf.worker.js. The file is not loading.
I'm using the chrome browser. All other files are processed fine, but this one is not. Help solve the problem.
[usn2020.pdf](https://github.com/mozilla/pdf.js/files/5936611/usn2020.pdf)

**Comment by calixteman** [comment]
Annotation 19R is equal to its parent so infinite loop.

**Comment by evlgromov** [comment]
> Annotation 19R is equal to its parent so infinite loop.

how can i solve the problem

**Comment by calixteman** [comment]
I don't know.
This file contains a lot of objects which have references to themselves (modulo a chain).
