### ISSUE TITLE
Stop mentioning the `gh-pages` branch in the documentation 

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#12977]
In a few spots in the documentation, see below, we mention the `gh-pages` branch and even advise using it. While that may have made sense at one point in time, that's *really not* recommended anymore (since it changes with every merge) and we *should* simply refer users to the [official releases](https://github.com/mozilla/pdf.js/releases) instead.

 - https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#gh-pages
 - https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#examples

**Comment by timvandermeij** [comment]
Both pages have now been updated to only mention the official releases. Thanks for bringing this up!
