### ISSUE TITLE
PDF rendering problem: Checkboxes have black background

### ISSUE THREAD

**Issue by gibbsnich** [mozilla/pdf.js#13003]
Attach (recommended) or Link to PDF file here:
[Erstattung von Arbeitgeberaufwendungen nach __ 56 Abs. 1 und 57, 58 Infektionsschutzgesetz - Antrag(1).pdf](https://github.com/mozilla/pdf.js/files/6009589/Erstattung.von.Arbeitgeberaufwendungen.nach.__.56.Abs.1.und.57.58.Infektionsschutzgesetz.-.Antrag.1.pdf)

Also available at: [formularserver.bayern.de](https://formularserver.bayern.de/intelliform/forms/stmi+regierungen/rof/b5/55.2/rof_55.2-086/index)

Configuration:
- Web browser and its version: FF 85.0.2 and FF 86.0b9
- Operating system and its version: Win 10
- PDF.js version: 
FF 85.0.2:
const pdfjsVersion = '2.7.345';
const pdfjsBuild = 'b194c820b';

FF 86.0b9:
const pdfjsVersion = '2.7.510';
const pdfjsBuild = '631bada0d';

- Is a browser extension:
no
Steps to reproduce the problem:
1. load pdf document

What is the expected behavior? (add screenshot)
This is with latest Chrome:
![grafik](https://user-images.githubusercontent.com/584660/108499622-e2360880-72ae-11eb-82a7-b181619ff079.png)

What went wrong? (add screenshot)
The checkboxes for e.g. "Geschlecht" are black and you cannot see which one is checked. But this is true for every checkbox in that document.
![grafik](https://user-images.githubusercontent.com/584660/108499753-14e00100-72af-11eb-89d3-1f5ca652e058.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment]
A black square is drawn on the canvas and then because of transparency here:
https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.css#L48
we see it.
@timvandermeij, should we replace the color by an opaque one ?

**Comment by timvandermeij** [comment]
I'm confused about where we actually draw a black square? Looking at https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.css#L48 the color is light blue as intended...

**Comment by Snuffleupagus** [comment]
> In that case I don't see a problem with making this the same color but opaque instead of transparent.

Wouldn't that cause more issues in *general* though, since it will cause anything which is rendered "below" the field to be completely covered up?
For this particular PDF file, such a change would e.g. lead to the bottom of the field descriptions being covered up.

**Comment by timvandermeij** [comment]
Good point. I wonder how/if other PDF files handle this file then, for example Adobe Reader.
