### ISSUE TITLE
Some characters are hidden/deleted on IE11 with pdfjs version pdfjs-2.6.347-es5-dist

### ISSUE THREAD

**Issue by spradhan1990** [mozilla/pdf.js#13012]
Attach (recommended) or Link to PDF file here: 
[DataChanges.PDF](https://github.com/mozilla/pdf.js/files/6034194/DataChanges.PDF)

Configuration:
- Web browser and its version: IE11  
- Operating system and its version: windows 10
- PDF.js version: pdfjs-2.6.347-es5-dist
- Is a browser extension:

Steps to reproduce the problem:
1. Render the pdf using pdf viewer
<div style="width:100%;height:700px;">
	<object id="mediaIframeId"  width="100%" height="100%" data="web/viewer.html?file=DataChanges.PDF"></object>	
</div>

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/79566088/108964532-936ae300-76a1-11eb-96ef-f9339402d8b0.png)

What went wrong? (add screenshot)

you can see  in the left of the screenshot above, the IE is  not showing some characters. (for eg. S, E, i and ....)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As mentioned in the FAQ, IE 11 is no longer supported; note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. ***However, this support will be dropped after stable version `2.6.347`.***

**Comment by spradhan1990** [comment]
Thanks Snuffleupagus. Even it is not supported, i am able to render the pdf on IE11. Problem here is only with the string it is showing.
Is there any way to troubleshot the issue.

**Comment by Snuffleupagus** [comment]
> Is there any way to troubleshot the issue.

Given that IE 11, as mentioned above, is now *explicitly unsupported* we unfortunately cannot provide assistance here (and debugging in IE 11 was always a pain). Furthermore, please note that at this point in time we'll *not* accept any patches for IE 11 specific bugs.
