### ISSUE TITLE
SVG: Missing glyphs

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#13017]
This pdf:
[page-3.pdf](https://github.com/mozilla/pdf.js/files/6037102/page-3.pdf)

The SVG misses quite a few characters.
Steps to reproduce  (pdf.js 2.5 works, pdf.js 2.6+ fails):

````
npm install
node_modules/.bin/gulp dist-install
node examples/node/pdf2svg.js /tmp/page-3.pdf
firefox /tmp/page-3.pdf svgdump/page-3-1.svg
````

**Comment by Snuffleupagus** [comment]
WFM, when opening it with the PDF.js version `2.8.127` default viewer *with SVG-rendering enabled*, i.e. https://mozilla.github.io/pdf.js/web/viewer.html, please see:

![svg](https://user-images.githubusercontent.com/2692120/109026494-1864f500-76c0-11eb-9b0f-198642adeec2.png)

**Comment by doublex** [comment]
This is what I get:
![page-3](https://user-images.githubusercontent.com/274624/109058334-2a0bc400-76e3-11eb-95c0-01d6c2383cfb.jpg)

**Comment by Snuffleupagus** [comment]
I've just tested the `pdf2svg` example, with PDF.js version `2.8.131`, and the resulting SVG file looks good to me when opened in Firefox Nightly 88:

![pdf2svg](https://user-images.githubusercontent.com/2692120/109063795-e49ec500-76e9-11eb-80b0-1ed9c5e2a914.png)

**Comment by timvandermeij** [comment]
It looks like this might be platform specific then. @doublex Could you share the SVG file that you get as output? Perhaps we can see if there are differences in the final output, or if it's another rendering problem.

**Comment by doublex** [comment]
Tested with Centos 7 and Ubuntu 20.04:
[page.zip](https://github.com/mozilla/pdf.js/files/6055391/page.zip)

**Comment by Snuffleupagus** [comment]
> Tested with Centos 7 and Ubuntu 20.04:

 - Which *exact* PDF.js version did you test with, since https://github.com/mozilla/pdf.js/issues/13017#issue-815594803 doesn't mention a full version number?
 - If you haven't already, can you please test with the `master` branch to check if it's still an issue (since we generally don't patch already released versions)?

**Comment by doublex** [comment]
This was the command-line:
````
git clone https://github.com/mozilla/pdf.js.git
cd pdf.js
npm install
node_modules/.bin/gulp dist-install
node examples/node/pdf2svg.js /tmp/page-3.pdf
firefox svgdump/*
````

**Comment by cetinsert** [comment]
2.7.570 has no characters in missing (Win 10, Chrome (both latest stable)) too.

**Comment by doublex** [comment]
Maybe only an issue on linux.
The problem is this commit - @brendandahl
https://github.com/mozilla/pdf.js/commit/f6dff812237d22f8cfc0422238d39e11786f8c9f

**Comment by doublex** [comment]
Issue is gone in current pdf.js
