### ISSUE TITLE
Sidebar outline view is unreadable at window-widths below 840px

### ISSUE THREAD

**Issue by drivasperez** [mozilla/pdf.js#13036]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 86.0 (64-bit)
- Operating system and its version: Windows 10 Enterprise 19042.746
- PDF.js version: Firefox built-in 

Steps to reproduce the problem:
1. Open a document with an outline
2. Change window width to a value less than 840px
3. Open document outline in the sidebar

What is the expected behavior? It should display the document's outline in a visually accessible way.

What went wrong? The background is very dark and translucent, making it extremely hard to read the document's outline.

![image](https://user-images.githubusercontent.com/162802/109527194-4b85fa80-7aab-11eb-9bdb-e13af4623605.png)

It seems like this line is to blame: https://github.com/mozilla/pdf.js/blob/73da90610284bc43f29efc1043247290c5eeb9e7/web/viewer.css#L1793

**Comment by timvandermeij** [comment]
Fixed by the PR above.

**Comment by drivasperez** [comment]
Great, thanks!
