### ISSUE TITLE
PDF.js 2.5.207 shows Security Vulnerability in your dependencies 

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#13043]
<img width="576" alt="detailed security" src="https://user-images.githubusercontent.com/79515387/109686668-7dc95200-7ba8-11eb-90a9-96675df20c49.png">
Attach 
<img width="661" alt="ssecurity vulnerability" src="https://user-images.githubusercontent.com/79515387/109685838-aac93500-7ba7-11eb-8f93-c765b7ec207c.png">
(recommended) or Link to PDF file here:
Integrating PDF.js 2.5.207 results in security vulnerability in highlight.js in Github. Attached is the screenshot showing the vulnerability. Can we just dismiss this?
Configuration:
- Web browser and its version: Chrome, Firefox
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension:

Steps to reproduce the problem:
1. Upgraded from PDF.js 2.1.266 to 2.5.207. 
2. Github shows security vulnerability issue

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Upgraded from PDF.js 2.1.266 to 2.5.207.

First of all, please note that *neither* of those versions are supported any more; please find the current releases at https://mozilla.github.io/pdf.js/getting_started/#download

Furthermore, as can be seen in https://github.com/mozilla/pdf.js/blob/master/package.json, we do *not* have a direct dependency on `highlight.js` (whatever that is).

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus Thank you so much for your quick response. I ll check out where that dependency is induced.
