### ISSUE TITLE
Add a Link with "likely causes" to "The API version X does not match the worker version Y"

### ISSUE THREAD

**Issue by ralfhauser** [mozilla/pdf.js#13040]
![image](https://user-images.githubusercontent.com/1681677/109538848-d6252480-7ac0-11eb-83a7-2558d0fb63e2.png)

For me, the solution mentioned in 
https://github.com/mozilla/pdf.js/issues/10997#issuecomment-724771405
worked.

Suggestion:
1) As this is a frequent error, add a link to this error message where on your site, you can list possible counter-measures.
a) flushing the cache probably being the most likely

More incidents of the same error message:
- https://github.com/mozilla/pdf.js/issues/9997
- https://github.com/mozilla/pdf.js/issues/11994
- ...

**Comment by Snuffleupagus** [comment]
> add a link to this error message where on your site,

Adding a link in the *code* could be problematic[1], however adding a section about this [in the Wiki](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions) would probably be a good idea.

> flushing the cache probably being the most likely

Another situation, and possible more common cause, is for users that load the `pdf.worker.js` file from a CDN (see https://mozilla.github.io/pdf.js/getting_started/#including-via-a-cdn), and thus run into these issues when updating to a new PDF.js release.

---
[1] For example, it would do *nothing* for the already existing releases (and it would also take quite some time before that even hits official releases). Moreover, there's also the risk that a link in the code itself breaks inadvertently, if any future changes are make to e.g. the Wiki (or wherever the link points to), and having a *broken* link seems worse than no link at all.

**Comment by Snuffleupagus** [comment]
An entry has been added to the Wiki, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#version-mismatch
We can obviously always improve/expand upon that later on; however closing this issue as fixed for now.
