### ISSUE TITLE
Unable(Due to lack of knowledge) to insert bar code ttf file in PDF.js

### ISSUE THREAD

**Issue by oliver-bakato** [mozilla/pdf.js#13044]
[document.pdf](https://github.com/mozilla/pdf.js/files/6071355/document.pdf)
![print codigo de barras (1)](https://user-images.githubusercontent.com/54816742/109706807-2b703d00-7b78-11eb-94ed-b07405dd19a3.png)

Configuration:
- Google Chrome: 80.0.3987.122.
- Linux Mint: 19.2
- PDF.js version: 2.8.97

I've had some trouble with the insertion of pdf files with a local brazilian bar code ttf file that obviously ain't embedded in the API. After 4 days searching without many answer due to my lack of experience and more practical documentation online I decided to ask for your help. Could you deliver or produce some documentation regarding the insertion of custom fonts into PDF.js?

**Comment by Snuffleupagus** [comment]
> Could you deliver or produce some documentation regarding the insertion of custom fonts into PDF.js?

The PDF.js library does not support such a use-case, hence you'll simply need to embed the fonts in the PDF document *itself* for this to work as expected.
Also, please keep in mind that the only way to guarantee (in general) that PDF viewers can always display a particular document correctly is if *all* non-standard fonts are embedded in the PDF document itself.

**Comment by oliver-bakato** [comment]
Thank you for your time and attention Snuffleuppagus!
