### ISSUE TITLE
File renders white while looks fine on Chrome

### ISSUE THREAD

**Issue by torakiki** [mozilla/pdf.js#13051]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 86.0 (64 bit)
- Operating system and its version: Linux Mint 20.1
- PDF.js version: 2.7.510

Steps to reproduce the problem:
This file renders completely white while I can see it using Chrome or Xreader
[njp.32101064480005_page_013(2).pdf](https://github.com/mozilla/pdf.js/files/6083044/njp.32101064480005_page_013.2.pdf)

What is the expected behavior? 
![immagine](https://user-images.githubusercontent.com/3884479/109954440-a143e800-7ce1-11eb-85b4-6ed83cb84021.png)

**Comment by Snuffleupagus** [comment]
```
PDF d0b251002ea92fc25f6c12d7709c33e8 [1.5 HathiTrust Image Server / PDF::API2 / HathiTrust] (PDF.js: 2.8.126) viewer.js:1758:13
Warning: Unsupported header type 1970628964 (uuid) pdf.worker.js:1052:13
Warning: JPX: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticallyStripe, predictableTermination). pdf.worker.js:1052:13
Warning: Unable to decode image "img_p0_1": "JpxError: JPX error: JPX error: Out of packets". pdf.worker.js:1052:13
Warning: Dependent image isn't ready yet pdf.js:922:13
```
