### ISSUE TITLE
ie11  open https://mozilla.github.io/pdf.js/legacy/web/viewer.html Show syntax error

### ISSUE THREAD

**Issue by learnerxyf** [mozilla/pdf.js#13065]
![image](https://user-images.githubusercontent.com/41783936/110310459-89e86000-803d-11eb-929f-149a147a2391.png)

**Comment by Snuffleupagus** [comment]
As mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is no longer supported:
> However, this support will be dropped after stable version 2.6.347.

Furthermore, this is *also* mentioned in the release notes (for version `2.7.570`) at https://github.com/mozilla/pdf.js/releases
