### ISSUE TITLE
pdfjs didn't work in IE 11

### ISSUE THREAD

**Issue by GravesDXD** [mozilla/pdf.js#13072]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: win10
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. I copy pdf.js and pdf.worker.js to local
2. create helloworld.html ang then add a blob after import them like learning in example

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)it works well in chrome but IE11 didn't. The error is  'pdfjsLib' is undefined

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is now *explicitly unsupported*.

**Comment by GravesDXD** [comment]
In other word, the version,2.3.200 can work well in IE11, is it right?

**Comment by Snuffleupagus** [comment]
> the version,2.3.200

That version is no longer supported, and consequently it should not be used any more.

> can work well in IE11, is it right?

The PDF.js library never worked all that well in IE 11, since that browser is old, slow, and missing *a lot* of features; please update to a modern browser instead.
