### ISSUE TITLE
Replace spans in text layer by svg:tspan

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13083]
Sometimes the words in text layer are shifted compared to their rendering on the canvas.
It's possible using a `svg:tspan` to specify spaces between glyphs:
```html
<html>
<body>
  <div>
    <svg width="200" height="50" xmlns="http://www.w3.org/2000/svg">
      <text x="10" y="20">
        <tspan dx="0 10 20 30 40" >hello</tspan>
      </text>
    </svg>
  </div>
</body>
</html>
``` 
the text is still selectable (in either Firefox or Chrome).
We'll need to investigate memory consumption and scroll performance but it could be a good thing.

**Comment by Snuffleupagus** [comment]
> We'll need to investigate memory consumption and scroll performance but it could be a good thing.

Any measurements should probably be done on top of PR #12989, since that one is already increasing the number of DOM elements by an order of magnitude (in e.g. the `tracemonkey.pdf` file), given that the *combined* effect may an issue.

**Comment by calixteman** [comment]
I really hope that we'll have almost the same number of tspans than the number of spans we've right now: almost one 1 tspan by line.
So I think the memory consumption should be almost the same (modulo array of shifts for dx attribute) and I'm pretty confident to have similar perf when scrolling.
When I played with talos test, I find out that a lot of time is consumed because of `scaleX` transform and if tspans are ok it should be possible to remove all the `scaleX`. As far as I know removing the `scaleX` should imply that already rasterized glyphs can be reused thanks to the cache and so it should be a way faster.
My idea is to get glyph positions and dimensions in the `evaluator` and then compute the spaces when creating the text layer to make glyph centers coinciding.

**Comment by Snuffleupagus** [comment]
Another thing to keep in mind, if you're trying to make more far-reaching changes to the textLayer, is that highlighting of search results doesn't *accidentally* break in the process; please note the relevant methods in https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js

> My idea is to get glyph positions and dimensions in the `evaluator` and then compute the spaces when creating the text layer to make glyph centers coinciding.

We used to have some code, although it was never actually used, for determining individual glyph positions; please see issue #7996 for details (in case that's helpful to avoid having to re-invent the wheel, so to speak).

**Comment by calixteman** [comment]
I found a solution only based on html so this bug is now useless.
