### ISSUE TITLE
Detecting whether a form field is required or not

### ISSUE THREAD

**Issue by magorismagor** [mozilla/pdf.js#13089]
Hi everyone,

I would like to detect in my javascript code when a form field in a PDF is required but I cannot find the way.  I hope someone can point me in the right direction.

I attach a example PDF with two text fields: one required and another one not required. When I get the annotations of this PDF in my javascript code, for the required form field I get:

alternativeText: ""
annotationFlags: 4
annotationType: 20
borderStyle: {width: 0, style: 1, dashArray: Array(1), horizontalCornerRadius: 0, verticalCornerRadius: 0}
color: Uint8ClampedArray(3) [0, 0, 0]
comb: false
contents: ""
defaultAppearance: "/Helv 8.64 Tf 0 g"
fieldFlags: 2
fieldName: "name"
fieldType: "Tx"
fieldValue: ""
hasAppearance: true
id: "2R"
maxLen: null
modificationDate: null
multiLine: false
readOnly: false
rect: (4) [213.12, 704.38, 457.92, 723.82]
subtype: "Widget"
textAlignment: 0

There are properties for multiLine and readOnly, but there is any for "required". However I can see that the number of fieldFlags is 2, so I guess the way is to get access to this flags, however I don't know how to do this.

[Attach](url
[pdfjsRequiredFieldExample.pdf](https://github.com/mozilla/pdf.js/files/6134335/pdfjsRequiredFieldExample.pdf)
) (recommended) or Link to PDF file here: 

Configuration: 
- Web browser and its version: Chrome Versión 89.0.4389.82 (Build oficial) (64 bits)
- Operating system and its version:  Windows 10  - Version 10.0.18363 compilation 18363
- PDF.js version: 2.6.347
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the PDF attached. 
2. Get the form fields and detect, for each of them, whether is required or not

What is the expected behavior? (add screenshot) I would like to detect in my javascript code whether a form field is required or not. 

What went wrong? (add screenshot) I cannot detect whether a form field is required or not

Thank you so much for your help!

**Comment by Snuffleupagus** [comment]
> There are properties for multiLine and readOnly, but there is any for "required".

Those have been added since the `AnnotationLayer` code needed them, however I doubt that we'd want to *explicitly* add a property for every single flag (if we're not using them anywhere).

> However I can see that the number of fieldFlags is 2, so I guess the way is to get access to this flags, however I don't know how to do this.

Given that you already have access to the `fieldFlags` property, it's trivial to check if the "required" flag is set; simple test `!!(fieldFlags & 2)` and you're done :-)

**Comment by magorismagor** [comment]
Thank you so much for you reply, I have it working perfectly now! I see I misunderstood the meaning of the fieldFlags property.

**Comment by dgkwon** [comment]
Hi,
I am using pdf.js version 3.6.172.
It looks like that the fieldFlags is not available in this version.
Is there any way to detect whether a form field is required or not?
Thanks.
