### ISSUE TITLE
Warning: Invalid absolute docBaseUrl: "data:application/pdf;base64,

### ISSUE THREAD

**Issue by pikooli** [mozilla/pdf.js#13103]
Hello, 

I got this warning in the console when i try to show a base64 encoded pdf.
  
`Warning: Invalid absolute docBaseUrl: "data:application/pdf;base64,`

I don't really know what it mean, but i thing it related to pdf.js . 

I only do this in my html file : 

 `           <embed src="data:application/pdf;base64,{contract.file}#zoom=50" type="application/pdf" width="100%" height="600" id="contract" name="{contract.id}"/>`

I did try to change the tag to iframe or object, but it the same.

Don't know what to do with this, i don't get this error on chrome.

I try to make a basic pdf encode it to base64 and give it to it, it don't show the warning, don't know if it the encodage that was bad or some information missing in the pdf.

I link to a playground where you can test it. 

Thanks all 

[http://jsfiddle.net/yLx2W/1/
](http://jsfiddle.net/yLx2W/1/
)

**Comment by Snuffleupagus** [comment]
> Warning: Invalid absolute docBaseUrl: "data:application/pdf;base64,

Just ignore it, since it's a warning rather than an actual error. (It simply tells you that for a badly created PDF document, relative links won't work.) 

Since there is nothing that's actually wrong here, this issue should just be closed :-)

---

*For future reference:* When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by pikooli** [comment]
Oh ok :o 
So it was the pdf fault, i was thinking the same but wanted to be sure 👍 
Thank you for the reply :)

**Comment by Snuffleupagus** [comment]
> So it was the pdf fault,

Not necessarily; it simply means that the URL (with which the PDF was opened) cannot be used to resolve relative links. It does *not* mean that the PDF document itself is corrupt.
As I said, just ignore the warning since it's (somewhat) technical and aimed primarily at developers :-)

**Comment by pikooli** [comment]
OHHHHHHHH ok, yeah it a base64 encoded so it not a url relative :o.
Thanks you for the explanation

**Comment by Snuffleupagus** [comment]
> it a base64 encoded so it not a url relative

Sorry, but this still isn't entirely correct!
When I mentioned *relative links* above that refers simply to e.g. Annotations within the PDF document *itself*, and not to how you opened your document with the PDF.js library.

**Comment by pikooli** [comment]
ohhhhh ok :D
