### ISSUE TITLE
Attached file isn't rendered properly

### ISSUE THREAD

**Issue by TyDraniu** [mozilla/pdf.js#13107]
Attach (recommended) or Link to PDF file here:
[NAPEN16171380959.pdf](https://github.com/mozilla/pdf.js/files/6143802/NAPEN16171380959.pdf)

Configuration:
- Web browser and its version: Firefox 88 Nightly
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension: No

What went wrong? (add screenshot)
![](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/images/2021-03-15-10-58-27-ce2796.png)

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!
