### ISSUE TITLE
PDF File - Some backgrounds not rendered in PDFJS Demo Viewer

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#13111]
Attach (recommended) or Link to PDF file here:
[Test2.pdf](https://github.com/mozilla/pdf.js/files/6148570/Test2.pdf)

Configuration:
- Web browser and its version: Chrome Version 89.0.4389.90 (Official Build) (64-bit) (and Firefox 86.0.1)
- Operating system and its version: Windows 10
- PDF.js version: ?? Whatever Is Used by the site mozilla.github.io/pdf.js today - I think it is 2.8.240
- Is a browser extension: NO

Steps to reproduce the problem:
1. Open attached file 
2. Goto Page 6 - half the page is white when it should black

What is the expected behavior? (add screenshot)
![Screenshot Chrome Native](https://user-images.githubusercontent.com/947206/111303013-6bc8c400-862a-11eb-8dfa-35d2b95fa22a.png)

What went wrong? (add screenshot)
![Screenshot Demo Viewer](https://user-images.githubusercontent.com/947206/111303051-784d1c80-862a-11eb-9779-9cb0398c56db.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by HAPENLY** [comment]
Check whether it is related to the maximagesize property

**Comment by cetinsert** [comment]
SVG rendering fail for all pages with
```
Error: Invalid SVG dimensions
    at unreachable (pdf.min.js:22)
    at assert (pdf.min.js:22)
    at DOMSVGFactory.create (pdf.min.js:22)
    at SVGGraphics._makeTilingPattern (pdf.min.js:22)
    at SVGGraphics._makeColorN_Pattern (pdf.min.js:22)
    at SVGGraphics.setStrokeColorN (pdf.min.js:22)
    at SVGGraphics.executeOpTree (pdf.min.js:22)
    at SVGGraphics.group (pdf.min.js:22)
    at SVGGraphics.executeOpTree (pdf.min.js:22)
    at SVGGraphics.group (pdf.min.js:22)
```

**Comment by SamyCookie** [comment]
It does not work with with Firefox 88 but seems to fixed now with master.
