### ISSUE TITLE
Please advise which Chrome version above supports pdf.js？thanks！

### ISSUE THREAD

**Issue by ER-Tiylor** [mozilla/pdf.js#13123]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  android browser （chorme57.0）
- Operating system and its version: android 6.0
- PDF.js version:  2.6.347
- Is a browser extension: No

Steps to reproduce the problem:
1. first，this true problem is some characters are missing in mobile browser rendering,
2.For details, I am using PDFJS-dist. In the same mobile phone, the WeChat browser is fine, but the characters are lost in the mobile browser. According to UA, the difference between the two browsers is that the former is Chorme 77, and the latter is Chrome57.So I think it might be a Chrome version problem, which Chrome version is not supported?Sincerely thank you

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

![微信图片_20210320100949_爱奇艺](https://user-images.githubusercontent.com/45189757/111856315-cfbdf600-8964-11eb-933b-b462b0b9fbbd.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that in general, without this information the issue isn't actionable/valid.

Furthermore, the only compatibility information that we provide [is found in the Wiki](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), where it explicitly states (emphasis mine):
> The objective is to support all HTML5 compliant browsers, but since feature support varies per browser/version our support for all PDF features varies as well. In general, the support is below. ***If no version is indicated, then the latest desktop/mobile versions are intended.***

> [...] and the latter is Chrome57.

According to https://en.wikipedia.org/wiki/Google_Chrome_version_history, that version is *four* years old and browsers that old are unsafe and shouldn't be used by anyone.

**Comment by ER-Tiylor** [comment]
OK, thank you, I have noticed in the Wiki and Q&A about the supported version,I would actually like to know the explicit version of Chrome that is not supported in order to prompt users to download the PDF,However, as you said, the version is too old and we will consider dropping it.

**Comment by timvandermeij** [comment]
There is no explicit version that we don't support, but in general: the older the browser, the larger the chance that features could be unsupported. Always use the latest stable browser, currently Chrome 87 according to https://en.wikipedia.org/wiki/Google_Chrome_version_history.

**Comment by ER-Tiylor** [comment]
By installing different versions of Chrome on my smartphone, I've found that it renders missing characters below Chrome70. Hope it helps
