### ISSUE TITLE
Duplicate typescript types and lack of exports

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#13122]
Attach (recommended) or Link to PDF file here:

no PDF

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: latest from git
- Is a browser extension: nope

... this is a bug with the current typescript types so not really a bug with the above.

There are duplicated types in the source code.

For example:

PDFDocumentProxy... 

one is as a class in api.d.ts and the other is in display.d.ts as an interface.

Since the symbols are identical it makes it hard to work with the code and I think right now the types cause more pain.

Could we rename this one IPDFDocumentProxy ?

Right now I need to be able to take PDFDocumentProxy as an argument in my code but that's not possible right now because the types aren't really interchangeable.

**Comment by burtonator** [comment]
Looking at this now, I think 99% of the problems I'm having here can be resolved by:

- making them all exported
- if there's an interface and a class with the same name, prefix one with "I" so that if the class is "Foo" the interface would be IFoo.

The common pattern for typescript developers is to reuse the types provided by the project so:

- not exporting them defeats the purpose of typescript
- duplicating the names just makes it a nightmare

I *really* appreciate you guys doing the work here and we're moving in the right direction but these types seem to make my job harder.

**Comment by timvandermeij** [comment]
The TypeScript types are maintained by the community since this is a vanilla JavaScript project and that therefore has the focus of the core developers, but we are certainly open for reviewing any patches for improving the existing types. The existing types are also the result of community efforts.

**Comment by Snuffleupagus** [comment]
> ... this is a bug with the current typescript types so not really a bug with the above.

Do you mean that you ran `gulp types` to generate the Types, or something else?
Currently, for someone unfamiliar with TypeScript, this issue feels a little "light" on the details and thus difficult to follow...

> one is as a class in api.d.ts and the other is in display.d.ts as an interface.

Looking at https://github.com/mozilla/pdfjs-dist/tree/master/types, or the local output of `gulp types`, there isn't any file called `display.d.ts` which makes this part very hard to understand!?

---

> [...] but we are certainly open for reviewing any patches for improving the existing types.

Although we probably don't want any "ugly hacks" in our JavaScript code, in order to accommodate TypeScript.

**Comment by Snuffleupagus** [comment]
Is this possibly related to https://github.com/mozilla/pdf.js/issues/12384#issuecomment-695143287, and the preceding discussion there?

**Comment by burtonator** [comment]
@timvandermeij Ah... these are still the community types! Gotcha.  I thought these were new typses as I thought I remember some work being done to generate them from the jsdoc.

@Snuffleupagus Sorry for being light on details.  Not my intentions.  I didn't generate with ```gulp types``` but built via ```gulp dist``` but maybe that calls ```gulp types```

Regarding display.d.ts... you're right.  This was due to my error. That was our own internal custom types we maintained from the community types.  

My comment still stands though as I looked at the code and there are duplicate symbol names in duplicate places and not everything is exported.

If you're not opposed to a PR that exports them I'm fine with that.  I'll look at the types when I get the chance.

**Comment by Snuffleupagus** [comment]
> My comment still stands though as I looked at the code and there are duplicate symbol names in duplicate places and not everything is exported.

Please link to the *actual* duplicates that you've found, e.g. in https://github.com/mozilla/pdfjs-dist/tree/master/types, since it's still very difficult to follow *exactly* what you perceive to be wrong here!

> If you're not opposed to a PR that exports them I'm fine with that. I'll look at the types when I get the chance.

Please make sure that you read through #12384 carefully *first*, since as discussed there we'll *not* accept extending the public API of PDF.js just for the TypeScript use-case and that something like https://github.com/mozilla/pdf.js/issues/12384#issuecomment-695143287 might be required for it to be acceptable.

**Comment by timvandermeij** [comment]
> Ah... these are still the community types! Gotcha. I thought these were new typses as I thought I remember some work being done to generate them from the jsdoc.

In addition to the above that I fully agree with, what I meant here is that the types in PDF.js, which are indeed generated from JSDoc comments, are maintained in our repository by the community. I didn't mean any external types such as those from DefinitelyTyped here.

**Comment by Snuffleupagus** [comment]
> Please link to the _actual_ duplicates that you've found, e.g. in https://github.com/mozilla/pdfjs-dist/tree/master/types, since it's still very difficult to follow _exactly_ what you perceive to be wrong here!

Without this information, this issue is unfortunately *still* incomplete and it probably doesn't make sense to keep it open as-is.

Also, as mentioned previously, the "missing" exports is (basically) tracked in https://github.com/mozilla/pdf.js/issues/12384#issuecomment-695143287 already.
