### ISSUE TITLE
Blurry rendering of cad file, starting at 90% zoom

### ISSUE THREAD

**Issue by Oakley1212** [mozilla/pdf.js#13134]
Good afternoon everybody,
I downloaded version 2.7.570 beta and use the provided viewer.html to load a pdf like viewer.html?file={PDF Filename}.
Since this is a cad file the drawing is quite large in format meaning A0 or alike and a good zooming quality is essential.
At 90% the drawing starts to get blurry as you can see in the attached image. Since the file is an Autocad PDF Export the quality should be perfect on any zoom stage. I did not manipulate any of the JS files yet.
Is there any chance to get a better rendering on this?

Best regards

Mirko
![pdf_test](https://user-images.githubusercontent.com/42223137/112310711-2c8f1880-8ca5-11eb-9800-3fb3c1530700.jpg)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since otherwise the issue is unfortunately not actionable/valid.

**Comment by Oakley1212** [comment]
I'm sorry so  here you go:

Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: Chome 89.0.4389.90
Operating system and its version: Windows 10 Pro 20H2
PDF.js version: 2.7.570 beta
Is a browser extension: no
Steps to reproduce the problem: Please check viewer url at the bottom.

What is the expected behavior? Nonblurry rendering over 90% zoom.

What went wrong? Blurry rendering from 90% zoom.

Please check at: http://archive.rinnen-clervaux.com:8082/jsviewer/web/viewer.html?file=testpdf.pdf

**Comment by Snuffleupagus** [comment]
> Please check at: http://archive.rinnen-clervaux.com:8082/jsviewer/web/viewer.html?file=testpdf.pdf

*For future reference:* Directly attaching the PDF document to the issue guarantees that it remains easily available in the future.

Looking at the above confirms the duplicate that I guessed at in https://github.com/mozilla/pdf.js/issues/13134#issuecomment-805795526.
