### ISSUE TITLE
Some PDFs' content is not shown, a message suggesting the usage of Adobe Reader is shown instead

### ISSUE THREAD

**Issue by marco-c** [mozilla/pdf.js#13143]
Attach (recommended) or Link to PDF file here:
[5e70058f-de74-4412-b7ec-0d02124fbd7f.pdf](https://github.com/mozilla/pdf.js/files/6206686/5e70058f-de74-4412-b7ec-0d02124fbd7f.pdf)
[08ba1dad-3244-4854-b0a9-00347e016306.pdf](https://github.com/mozilla/pdf.js/files/6206699/08ba1dad-3244-4854-b0a9-00347e016306.pdf)
Two examples above, I sent a few more to @calixteman.

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Linux
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior?
See the actual contents of the PDF

What went wrong?
A message suggesting the usage of Adobe Reader is shown instead of the actual content

**Comment by Snuffleupagus** [comment]
This looks, for all intents and purposes, like a duplicate of open issues in https://github.com/mozilla/pdf.js/labels/4-form-xfa

**Comment by marco-c** [comment]
> This looks, for all intents and purposes, like a duplicate of open issues in https://github.com/mozilla/pdf.js/labels/4-form-xfa

Could be, we'll test them after some of those issues are fixed, and mark as duplicate if needed.

**Comment by timvandermeij** [comment]
Yes, this should indeed be a duplicate of e.g., #4282. Closing this one and referencing these files from there.

**Comment by marco-c** [comment]
I would have kept this open just to make sure we remember to test these too after the issues from https://github.com/mozilla/pdf.js/labels/4-form-xfa are fixed, but @timvandermeij I trust you will remember.

**Comment by timvandermeij** [comment]
Let's reopen this indeed so we don't forget to also test these.

**Comment by Snuffleupagus** [comment]
> Let's reopen this indeed so we don't forget to also test these.

Well, both of the PDF documents in https://github.com/mozilla/pdf.js/issues/13143#issue-841156024 are now being tracked in *separate* issues, note the linked issues just above; hence I think that we can re-close this one :-)

**Comment by timvandermeij** [comment]
Ah, good point, I didn't see that :-)
