### ISSUE TITLE
Help needed to reproduce pdf decryption in pdf-lib

### ISSUE THREAD

**Issue by Sharcoux** [mozilla/pdf.js#13151]
Does anyone feel able to reproduce [this code for decryption](https://github.com/mozilla/pdf.js/blob/d6e0b2d92e243c56a6ce02be3d6cab92e9df9213/src/core/crypto.js#L1704) into [pdf-lib](https://github.com/Hopding/pdf-lib). I think that a volunteer would probably get a money reward for this, given [the traction on the subject](https://github.com/Hopding/pdf-lib/issues/233).

The current code seems very obscure to me and I don't know enough the pdf format to help much further on this.

**Comment by Snuffleupagus** [comment]
The code in https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js, similar to the rest of the PDF.js project, is licensed under "Apache License 2.0" which means that anyone can use that code *as long as they comply with the license*.

> into [pdf-lib](https://github.com/Hopding/pdf-lib)

That's a completely *different* project, not in any way affiliated with PDF.js, and consequently we know nothing about that here.

> The current code seems very obscure to me and I don't know enough the pdf format to help much further on this.

Well, you'd obviously need to consult the PDF specification, the following should be a good starting point https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G6.2354515, for additional information on that topic.

---

Please keep in mind that this is a *bug tracker* for the PDF.js project, and that this issue doesn't really seem like a actionably/valid bug report here; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md
