### ISSUE TITLE
default page size

### ISSUE THREAD

**Issue by 1rdsk1** [mozilla/pdf.js#13150]
Would it be possible to allow all pdf to be opened at a user set zoom level.  I have a large monitor and view 3 or 4 pages horizontally but if I click on a bookmark it defultas to page width so I have to adjust the zoom each time I use a bookmark which is pain.  The abilty to view multiple pages in chrome means that I use pdf.js as my preferred viewer but this is a constant annoyance.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; given the lack of details the information below will be general (and thus possibly less helpful).

> Would it be possible to allow all pdf to be opened at a user set zoom level.

Yes, just set the "defaultZoomValue" option/preference to the desired value.

> [...] but if I click on a bookmark it defultas to page width so I have to adjust the zoom each time I use a bookmark which is pain.

That behaviour can be disabled, by using the "ignoreDestinationZoom" option/preference.

**Comment by 1rdsk1** [comment]
Thanks.  Please where are these setting in chrome web browser on windows10?

**Comment by 1rdsk1** [comment]
Thanks but there is no option  "ignoreDestinationZoom" option/preference.  I am using Chrome browser on Windows 10.  pfa option popup
![Capture](https://user-images.githubusercontent.com/16118846/112660867-d6a9a480-8e4d-11eb-991f-a4d6e2f14b20.PNG)

**Comment by Snuffleupagus** [comment]
>  I am using Chrome browser on Windows 10. pfa option popup.

That would've been helpful to state upfront :-)

---

Assuming that you're referring to https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm, then it's unfortunately not been updated for quite some time (although that will hopefully change).

> Thanks but there is no option "ignoreDestinationZoom" option/preference.

Yes there is, see https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/preferences_schema.json#L166-L171, but as mentioned it requires updating the Chromium extension first.

> Also when setting the default zoom it would help if a custom level was allowed.

That's a limitation of the UI, not of the option/preference as such. Hence opening a PDF document, and then running the following in the web console should work: `PDFViewerApplication.preferences.set("defaultZoomValue", 90);`

**Comment by 1rdsk1** [comment]
Thanks.  I tried "Hence opening a PDF document, and then running the following in the web console should work: PDFViewerApplication.preferences.set("defaultZoomValue", 90);" but it just says "Promise" without changing the zoom to 90%
![Capture2](https://user-images.githubusercontent.com/16118846/112664163-92200800-8e51-11eb-8f5e-8b4574da9dce.PNG)

**Comment by Snuffleupagus** [comment]
> without changing the zoom to 90%

It applies that next time that you open a PDF document (since the PDF.js options/preferences are only read on load), which is what you asked for in https://github.com/mozilla/pdf.js/issues/13150#issue-842076352 :-)

**Comment by 1rdsk1** [comment]
Thank you very much.  You have made my day!

**Comment by Snuffleupagus** [comment]
> "ignoreDestinationZoom": {
> [...]
> However, I cannot see this option in the popup and my coding level is too low to follow what you mean.

As explicitly mentioned in https://github.com/mozilla/pdf.js/issues/13150#issuecomment-808352078, this requires that the Chromium extension is updated by its maintainer before this can work.

**Comment by timvandermeij** [comment]
Closing since the Chrome extension update is on the radar of @Rob--W.
