### ISSUE TITLE
warning: Attempting to create a Worker from an empty source. This is probably unintentional.

### ISSUE THREAD

**Issue by Ruud68** [mozilla/pdf.js#13167]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox / also Chrome
- Operating system and its version: Ubuntu
- PDF.js version: latest beta and stable (resp. 2.7.570 and 2.6.347)
- Is a browser extension:

Steps to reproduce the problem:
1. installed on localhost: works perfectly
2. install on website: viewer.html throws warning "Attempting to create a Worker from an empty source. This is probably unintentional." and displays empty page.
![image](https://user-images.githubusercontent.com/2733197/113158337-ff5ddf80-923b-11eb-99ab-21467db7662e.png)

3. When clicking download in the pdfjs viewer, the pdf opens correct in FF and external browser. 
![image](https://user-images.githubusercontent.com/2733197/113158949-84e18f80-923c-11eb-9015-e6749221c8f7.png)

What is the expected behavior? (add screenshot)
pdf should display in browser like it does on localhost setup

What went wrong? (add screenshot)
see above, works correct when run from https://localhost but not from 'real' website (tried multiple).
Must be missing something, but cannot find any clue as to what that might be.

Hope somebody can help me with this awesome tool!

**Comment by Snuffleupagus** [comment]
> PDF.js version: latest beta and stable

Please ensure that you always provide actual *numbers*, since "latest" is ambiguous (it changes whenever a new release is made).

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Ruud68** [comment]
Hi @Snuffleupagus ,
thanks for the quick response and you are right, sloopy of me :(
latest versions is both 2.6.347 and 2.7.570
I am using the out-of-the-box web and build directories / files that are in the build zip files.

here I have setup a test article with multiple embedded pdf's, as you can see they do not display but using the embedder can be downloaded correct. The same site on my localhost works okay.

https://och.onlinecommunityhub.nl/en/blog

**Comment by Ruud68** [comment]
Was able to fix this: it turned out that the worker.js files where so big that my build tools 'corrupted' them when creating the installer package.
Closing this one!
Thanks again for this awesome project!
