### ISSUE TITLE
Get error getDocument of undefined and GlobalWorkerOptions of undefined when use Pdf.js v2.6 with Vuejs

### ISSUE THREAD

**Issue by namlq93** [mozilla/pdf.js#13163]
I'm using PDF.js version 2.6 with Vuejs.I've got the error `Cannot read property 'getDocument' of undefined`

- PDF.js version: 2.6.347
- Vue version: 2.6.11

Mycode:

    import pdfjs from "pdfjs-dist";
    pdfjs.getDocument("./sample.pdf").promise.then((pdf) => {
       console.log(pdf._pdfInfo.numPages);
    });

[![getdocument of undifined][1]][1]

I've added the code: 

    import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
    
    pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;

but got error: `Cannot read property 'GlobalWorkerOptions' of undefined`

[![GlobalWorkerOptions of undefined][2]][2]

But when I updown version Pdf.js to `2.0.943`, it's ok:

[![ok][3]][3]

You can see code here: [pdfjs-vue-codesandbox][4]

  [1]: https://i.stack.imgur.com/Y0XiU.png
  [2]: https://i.stack.imgur.com/5FVQr.png
  [3]: https://i.stack.imgur.com/7Rbtb.png
  [4]: https://codesandbox.io/s/sharp-elbakyan-lhzmq?file=/src/App.vue

**Comment by Snuffleupagus** [comment]
> Vue version: 2.6.11

Unfortunately the PDF.js contributors cannot really support various frameworks, such as e.g. Vue.js (since we purposely try to provide generic rather than framework-specific code).

> import pdfjs from "pdfjs-dist";
> [...]
> import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";

That looks wrong, since there's no `pdfjs`/`pdfjsWorker` exports in those files; something like the following is probably more appropriate:
```
import * as pdfjsLib from "pdfjs-dist";
import * as pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
```

**Comment by 3375516913** [comment]
找到一个和我一样的倒霉蛋
