### ISSUE TITLE
Comments Status (Accepted or Rejected)

### ISSUE THREAD

**Issue by bimalgeorge1** [mozilla/pdf.js#13178]
Is there any possibility of shows the status of the comment (Accepted or Rejected )

**Comment by muhammad-fauzan1988** [comment]
https://github.com/muhammad-fauzan1988/vigilant-

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable/valid information and will be closed as INVALID.
