### ISSUE TITLE
pdf.js is overriding the document properties while rendering

### ISSUE THREAD

**Issue by eparirishit** [mozilla/pdf.js#13187]
Attach (recommended) or Link to PDF file here: 
[pdf with print disabled.pdf](https://github.com/mozilla/pdf.js/files/6265180/pdf.with.print.disabled.pdf)

Configuration:
- Web browser and its version: Chrome / 89.0.4389.114
- Operating system and its version: Windows 10 Pro / 20H2
- PDF.js version: 2.6.347 or Latest (2.9.2)
- Is a browser extension: No

I am having a pdf document that has the "print" & "copy" option disabled by default but while viewing this file through the pdf.js viewer these options are getting overridden by the viewer and they are enabled in the UI. If I view the same file in Google chrome with its default pdf renderer these options are disabled. 

Is there any way I can retain these options while rendering the pdf using pdf.js or can I control the context menu options to enable or disable these options?

Steps to reproduce the problem:
1. Navigate to the online demo link - https://mozilla.github.io/pdf.js/web/viewer.html
2. Click on Open File option on the toolbar 
3. Download the pdf from the link above and select the file to be opened in the viewer
4. Right-click on the document anywhere the Print option in the context menu is enabled 

What is the expected behavior? (add screenshot)
![chrome-print-disabled](https://user-images.githubusercontent.com/9528214/113722029-a72c4f00-970d-11eb-8082-6589d8dc76e9.png)

And If I select some text and try to copy (using keyboard shortcut ctrl + c) and paste it on the notepad, it won't be copying the selected text to the clipboard. (can't have this operation in the screenshot)

What went wrong? (add screenshot)
The same behavior is not observed while opening the same file with pdf.js

![chrome-print-enabled](https://user-images.githubusercontent.com/9528214/113722950-8284a700-970e-11eb-8955-f3b9698dd0bb.png)

And when we select some text and click on right-click the copy and print is enabled -

![chrome-copy-enabled](https://user-images.githubusercontent.com/9528214/113723059-9a5c2b00-970e-11eb-8625-b0c9182c9b10.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N.A

**Comment by Snuffleupagus** [comment]
> I am having a pdf document that has the "print" & "copy" option disabled by default but while viewing this file through the pdf.js viewer these options are getting overridden by the viewer and they are enabled in the UI.

By *default* the PDF.js demo viewer will ignore any such restrictions, since those are generally user-hostile, however you can set the `enablePermissions` preference/option to have the viewer respect (some of) those options.

*Please note:* Currently only disabling of copying is supported (see PR #11789), since it's the only thing that's thus far been requested that we support on the Firefox-side; hence if you want to support additional permissions that'd be covered under http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by eparirishit** [comment]
Thanks, @Snuffleupagus enabling that option is now restricting from copying text.

Do we have an option to control the context menu items?

**Comment by Snuffleupagus** [comment]
> Do we have an option to control the context menu items?

The context menu is controlled by the *browser*, and isn't something that a JavaScript application can control.
