### ISSUE TITLE
Unexpected server response while retrieving PDF

### ISSUE THREAD

**Issue by kirk86** [mozilla/pdf.js#13182]
Attach (recommended) or Link to PDF file here:
[PDF Link](http://mfleck.cs.illinois.edu/building-blocks/version-1.3/readings.pdf)

Configuration:
- Web browser and its version: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
- Operating system and its version: macOS Big Sur 11.0.1
- PDF.js version: No idea where to get this info from (probably latest)
- Is a browser extension: Yes, Weava highlighter

Steps to reproduce the problem:
1.  Install weava plugin on chrome and visit pdf link
2. Open pdf link in weava and the error appears, this happens only for certain pdfs and the one in the link is one of those

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2902390/113577542-16c90e00-962a-11eb-9b94-79064c483b35.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/2902390/113577617-35c7a000-962a-11eb-8a4f-8524f793eb68.png)

**Comment by timvandermeij** [comment]
The link works in the regular PDF.js version, so most likely the Weava extension is doing something wrong here. Moreover, PDF.js 1.6.210 as indicated in the screenshot is _4.5 years old_ and therefore _completely_ unsupported. This bug should be reported to Weava instead.

**Comment by Snuffleupagus** [comment]
> Is a browser extension: Yes, Weava highlighter

Also, please note that this refers to https://github.com/mozilla/pdf.js#browser-extensions, since we cannot support third-party extensions here.

**Comment by kirk86** [comment]
Thanks folks!
