### ISSUE TITLE
A word contains characters g or y are separated by the span 

### ISSUE THREAD

**Issue by ShawnYou1** [mozilla/pdf.js#13188]
Attach (recommended) or Link to PDF file here: https://burningvocabulary.com/read/kaoyan/2019/02 

Configuration:
- the pdf.js version is 2.6.347

Steps to reproduce the problem:
1. Open the link https://burningvocabulary.com/read/kaoyan/2019/02 
2. Find a word that contain a character g or y.

What is the expected behavior? (add screenshot)
I expecte a word should be in a span tag and the font size is common.

What went wrong? (add screenshot)
The characters g and y are separated by the span and the font size is different in a word. 
<img width="772" alt="Screenshot 2021-04-07 at 09 08 01" src="https://user-images.githubusercontent.com/44994356/113796098-07100d80-9781-11eb-9106-a37cf9be22f9.png">

![2019年考研英语二___PDF下载](https://user-images.githubusercontent.com/44994356/113796524-ff049d80-9781-11eb-8d38-ddfe21cf8add.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://burningvocabulary.com/read/kaoyan/2019/02

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: https://burningvocabulary.com/read/kaoyan/2019/02

Please just directly *attach* the file, as asked, since that saves everyone's time!

> The characters g and y are separated by the span and the font size is different in a word.

That's caused by the PDF document *itself*, and not the PDF.js library, since the those letters are rendered with a different font than the surrounding text. Hence this is actually a bug in the PDF generator.

**Comment by ShawnYou1** [comment]
x

> > Attach (recommended) or Link to PDF file here: https://burningvocabulary.com/read/kaoyan/2019/02
> 
> Please just directly _attach_ the file, as asked, since that saves everyone's time!
> 
> > The characters g and y are separated by the span and the font size is different in a word.
> 
> That's caused by the PDF document _itself_, and not the PDF.js library, since the those letters are rendered with a different font than the surrounding text. Hence this is actually a bug in the PDF generator.

Thank you for your reply and contribution.
