### ISSUE TITLE
How to block pdfjs extension.

### ISSUE THREAD

**Issue by utkarshbhati07** [mozilla/pdf.js#13185]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
- PDF.js version: pdfjs-2.6.347-es5
- Is a browser extension:Yes Version - 2.3.164

I have written some custom script using pdf.js so that I can hide and unhide the download/print button in pdf viewer.
But when chrome has this pdf viewer extension installed and active then it renders the pdf in that viewer and my custom made viewer code get overwritten.

Is there any way to solve this, so that all pdfs only get rendered in custom written viewer only. Regardless of extension is active or not.

I have attached two screenshot, one when extension is active and second one when it is disable or not installed.

![image](https://user-images.githubusercontent.com/74948236/113666151-6d872400-96cc-11eb-925e-55d9b9425d93.png)

![image](https://user-images.githubusercontent.com/74948236/113666219-93142d80-96cc-11eb-8a92-0cf9afeef1d8.png)

**Comment by Snuffleupagus** [comment]
> I have written some custom script using pdf.js so that I can hide and unhide the download/print button in pdf viewer.
> But when chrome has this pdf viewer extension installed and active then it renders the pdf in that viewer and my custom made viewer code get overwritten.

It should be pretty obvious why, for security reasons, some arbitrary JavaScript code cannot simply overwrite/modify/disable a browser extension. (Different Chrome extensions cannot *generally* communicate directly with each other either, again for security reasons.)

If you want to build a *custom* PDF.js extension, which you can then install into Google Chrome, please follow https://github.com/mozilla/pdf.js#chrome

---

All-in-all, this issue unfortunately doesn't really contain enough information to be actionable/valid as-is.
