### ISSUE TITLE
node packge pdfjs-dist@2.6.347 syntax error

### ISSUE THREAD

**Issue by Even-Lau** [mozilla/pdf.js#13190]
Configuration:
- PDF.js version: 2.6.347

Steps to reproduce the problem:
1. `npm install pdfjs-dist@2.6.347`
2. At `node_modules/pdfjs-dist/build/pdf.js` line 2413 you will get this: `annotationStorage: annotationStorage?.getAll() || null`, and this is definitely a syntax error.
3. However the cdn version works fine, https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.js 

A lot of same errors found at line 2771, line 2817, line 2907, line 2934, line 3488, line 3543, line 3653, line 3744 .etc

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

First of all, that version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download. Hence you'll need to update to either version `2.7.570` or `2.8.335`.

Depending on which of the two versions you pick, please note:
 - https://www.npmjs.com/package/pdfjs-dist/v/2.7.570?activeTab=readme 
   > For usage with older browsers or environments, without support for modern features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and nullish coalescing; please see the `es5` folder.

 - https://www.npmjs.com/package/pdfjs-dist/v/2.8.335?activeTab=readme
   > For usage with older browsers or environments, without support for modern features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and nullish coalescing; please see the `legacy` folder.

**Comment by Even-Lau** [comment]
Sorry to bother you, version 2.7.570 and 2.8.335 get the same error. Please check it again. @Snuffleupagus

**Comment by Snuffleupagus** [comment]
> Sorry to bother you, both version `2.7.570` and `2.8.335` get the same error: `annotationStorage: annotationStorage?.serializable || null`

This clearly suggests that you didn't actually follow *all* of https://github.com/mozilla/pdf.js/issues/13190#issuecomment-814701619, since the quotes (from the relevant READMEs) explain what you need to do here.

**Comment by HelloDreamICome** [comment]
I had the same problem,So ,How to solve it？I just update this package

**Comment by Even-Lau** [comment]
> > Sorry to bother you, both version `2.7.570` and `2.8.335` get the same error: `annotationStorage: annotationStorage?.serializable || null`
> 
> This clearly suggests that you didn't actually read/follow _all_ of [#13190 (comment)](https://github.com/mozilla/pdf.js/issues/13190#issuecomment-814701619), since the quotes (from the relevant READMEs) explain what you need to do here.

I don't think there is anything to do with older browsers or environments. This clearly suggests that you didn't even read the headline. Lots of errors found in your code and you don't even care.

**Comment by tamuratak** [comment]
See:

Optional chaining (?.) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by Snuffleupagus** [comment]
*Once more:* The answer was already provided in https://github.com/mozilla/pdf.js/issues/13190#issuecomment-814701619, and it means that you'll need to import from `node_modules/pdfjs-dist/es5/build/pdf.js`[1] instead.

---
[1] Or `node_modules/pdfjs-dist/legacy/build/pdf.js`, when using PDF.js version `2.8.335` and above.

**Comment by dsilvestregil** [comment]
@Snuffleupagus This import doesn't work for me. Folder 'es5' not exists in node_modules

**Comment by wrxpowered** [comment]
@dsilvestregil  it not exists in version 2.8.335 and above, you can use 2.7.570

**Comment by georgezouq** [comment]
@dsilvestregil  I had the same problem, any solution?
