### ISSUE TITLE
print option on context menu doesn't work as expected for chrome/microsoft edge

### ISSUE THREAD

**Issue by eparirishit** [mozilla/pdf.js#13196]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome / 89.0.4389.114
- Operating system and its version: Windows 10 Pro / 20H2
- PDF.js version: Latest (2.9.2)
- Is a browser extension: No

Steps to reproduce the problem:
1. When we embed the pdf.js viewer within an iframe 
2. Right-click on the document and click on Print

What is the expected behavior? (add screenshot)
The actual pdf file should be initialized for printing as we get on clicking on the Print icon on the toolbar or using the keyboard shortcut (ctrl + P)
![image](https://user-images.githubusercontent.com/9528214/113883931-3869f700-97dc-11eb-92df-bc521a1e4751.png)

What went wrong? (add screenshot)
It is trying to print the web frame
![print-option](https://user-images.githubusercontent.com/9528214/113884310-7ebf5600-97dc-11eb-84e5-fb6ea343ea16.png)

![image](https://user-images.githubusercontent.com/9528214/113884419-94348000-97dc-11eb-8fc9-7e374a5a00c1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://jsfiddle.net/rishit_epari/uopyhe5L/4/

**Comment by Snuffleupagus** [comment]
Given that printing support, as controlled by JavaScript, is very *limited* in browsers these types of problems are unfortunately not something we can fix. Note that the web-platform *itself* simply doesn't have the necessary functionality to provide detailed control over printing (and we're forced to resort to some hacks); hence these types of issues cannot be fixed here.
