### ISSUE TITLE
Question about scaleX (Matrix isn't working rn)

### ISSUE THREAD

**Issue by inf3rnus** [mozilla/pdf.js#13205]
Hey there people! 

Thanks for all of your hard work, and sorry for asking a question in the Issues board, but Matrix's registration seems to be down...

What I'm hoping to know is why scaleX is different when rendering a document on Firefox vs Chrome? 

I can't disclose too many inner details of this, but the problem is that I need to use HTML generated with PDF.js from puppeteer with Firefox, and well, the document is not 1-1 with respect to the text layer (because the scaleX values are different).

There's clearly something involved in calculating scaleX that leads to different values for Chrome and Firefox (and probably other browsers too), and I assume its because of the way both browsers render/compute *something*, I just don't know what that something is.

Any info would be greatly appreciated!

Thanks,
Aaron

**Comment by Snuffleupagus** [comment]
Unfortunately, with *all* of https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md missing this unfortunately doesn't really seem actionable/valid.

**Comment by brendandahl** [comment]
I'm guessing different values are returned when we use the [canvas to measure the text](https://github.com/mozilla/pdf.js/blob/6429ccc0028ecfadca4a4db3a0baf39146325379/src/display/text_layer.js#L666).

**Comment by inf3rnus** [comment]
@brendandahl Dude, thank you! This is a great starting place for me.

Cheers,
Aaron
