### ISSUE TITLE
Implement a warning for unvalidated digital signatures in the generic viewer

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#13215]
In PR #13214 we implemented rendering digital signature annotations, but they are not validated yet. For mozilla-central we display the fallback bar with a clear warning that the signatures are not validated so the user is aware of this, but we have no such mechanism for the generic viewer yet.

I'm thinking we could implement something similar to the fallback bar, which might even be more generally useful for other kinds of messages we now display in the fallback bar. For mozilla-central we'd then use the current browser fallback bar, and for other targets we would display the PDF.js fallback bar instead.

Alternatively we could perhaps add a semi-transparent overlay over the signature.

**Comment by Snuffleupagus** [comment]
> We could implement something similar to the fallback bar

The, by some margin, simplest solution as far as I'm concerned would be to just re-use the existing `errorWrapper`-functionality. While it obviously could look "better", it does the job well enough and requires virtually no "new" code; see https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:generic-signature-warn

**Comment by timvandermeij** [comment]
Yes, that would work for now. It could be made to look better by styling the existing error wrapper a bit nicer, or perhaps allow the existing error wrapper to distinguish between warnings and error (errors in red, warnings in maybe a lighter color).
