### ISSUE TITLE
v2.7-2.8 incorrectly render dashed line in FPDF/FPDI-created files.

### ISSUE THREAD

**Issue by kanuay** [mozilla/pdf.js#13211]
Attach (recommended) or Link to PDF file here:
https://kanuay.com/pdf/report/test.pdf

Configuration:
- Web browser and its version: Firefox Dev 88.0 & Safari iOS 14
- Operating system and its version: Windows 10 Latest & iOS 14
- PDF.js version: 2.7-2.8 (Both self-hosted and Firefox built-in)

Steps to reproduce the problem:
Lot of my file created by FPDF/FPDI
Open these files with PDF.js v2.7 or v2.8
All the fraction lines, radical signs, especially dashed lines are rendered incorrectly.

![PDF js Problem Report 210409](https://user-images.githubusercontent.com/61073462/114229447-0d310480-99a2-11eb-8a70-22ecd052df1d.png)

**Comment by timvandermeij** [comment]
If I recall correctly we did make some changes to the minimum line width code, although I'm not sure it's related to this.

**Comment by Snuffleupagus** [comment]
It seems that this regressed in *two* steps unfortunately, according to `git` bisect:
 1. The rendering of the figure first broke in
    ```
    b3dccd66ab6f895aa4a721082fdac05277c6818b is the first bad commit
    commit b3dccd66ab6f895aa4a721082fdac05277c6818b
    Author: Calixte Denizet <calixte.denizet@gmail.com>
    Date:   Mon Jan 4 14:25:30 2021 +0100

        Enforce line width to be at least 1px after applied transform
         * add a comment to explain how minimal linewidth is computed.
         * when context.linewidth < 1 after transform, firefox and chrome
           don't render in the same way (issue #12810).
         * set lineWidth to 1 after transform and before stroking
           - aims fix issue #12295
           - a pixel can be transformed into a rectangle with both heights < 1.
             A single rescale leads to a rectangle with dim equals to 1 and
             the other to something greater than 1.
         * change the way to render rectangle with null dimensions:
           - right now we rely on the lineWidth set before "re" but
             it can be set after "re" and before "S" and in this case the rendering
             will be wrong.
           - render such rectangles as a single line.

 2. The math symbols then became too bold in
    ```
    9754216c600a571f3cd10f819a88269b98ab2616 is the first bad commit
    commit 9754216c600a571f3cd10f819a88269b98ab2616
    Author: Calixte Denizet <calixte.denizet@gmail.com>
    Date:   Sat Jan 16 14:05:37 2021 +0100

        Fix zoom issue with too thin lines
         - aims to fix issue #12868: apply zoom factor to linewidth after setting it
           to 1.
         - only apply 1px-width when required
         - the sign of getSinglePixelWidth is used to know if 1px-width is required


/cc @calixteman

**Comment by calixteman** [comment]
I wonder if the correct approach would be to play with the transform to get a final correct rectangle (pixel after transform) instead of playing with the linewidth itself.

**Comment by calixteman** [comment]
I tried to fix the transformMatrix instead of fixing the line width and it seems to be the correct way to deal with this issue.
I'll submit a PR asap.
