### ISSUE TITLE
CERFA 12156*05 (pdf with forms) asks to be opened with Adobe reader

### ISSUE THREAD

**Issue by ggramaize** [mozilla/pdf.js#13213]
Attach (recommended) or Link to PDF file here: 
[cerfa_12156-05.pdf](https://github.com/mozilla/pdf.js/files/6290046/cerfa_12156-05.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 89.0a1 (2021-04-03) (64 bits)
- Operating system and its version: Linux 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22)
- PDF.js version: firefox built-in, but reproducible on the [online demo](https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: 

Steps to reproduce the problem:
1. Open cerfa_12156-05.pdf with pdf.js

What is the expected behavior? (add screenshot)
![Capture d’écran du 2021-04-10 16-53-58](https://user-images.githubusercontent.com/5450075/114274150-7013b180-9a1d-11eb-821d-a7c620f7f0f8.png)

What went wrong? (add screenshot)
![Capture d’écran du 2021-04-10 16-54-23](https://user-images.githubusercontent.com/5450075/114274162-7ace4680-9a1d-11eb-99e2-8662bc254dbf.png)

**Comment by calixteman** [comment]
The form is a XFA and we're working to support them.
Anyway it's dup of #2373.
