### ISSUE TITLE
Pdfjs get PDF file from S3 working on Safari, but not working on chrome and firefox with error 404 not found, Missing PDF Exception

### ISSUE THREAD

**Issue by namlq93** [mozilla/pdf.js#13225]
We store the PDF file above AWS S3, and access it through Cloudfront. To access the PDF file, I have to call api: `/api/preview-file/30.json`
But on chrome and firefox I get the error: "MissingPDFException", but on Safari everything works fine, which is confusing.
I have searched but have no answer, looking forward to your help. Thank you!

Configuration:
- Web browser and its version: Chrome Version 89.0.4389.114 (Official Build) (x86_64), Firefox 87.0 (64-bit)
- Operating system and its version: Mac OS High Sierra 10.13.6
- PDF.js version: 2.6.347

What went wrong? (add screenshot)
- Firefox: 
![Screen Shot 2021-04-12 at 14 08 34](https://user-images.githubusercontent.com/41458989/114354648-b6415000-9b98-11eb-8b75-3afe365ab783.png)
- Chrome:
![Screen Shot 2021-04-12 at 14 13 21](https://user-images.githubusercontent.com/41458989/114355124-4aabb280-9b99-11eb-87e0-28e284b36da3.png)

My code: PreviewFile.vue

```
import * as pdfjsLib from 'pdfjs-dist'
import * as pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'

pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker

export default {
    name: 'PreviewFile',
    mounted () {
        // const url = this.$route.query.q
        pdfjsLib.getDocument('/api/preview-file/30.json').promise.then(pdf => {
            const viewer = document.getElementById('pdf-viewer')

            for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
                const canvas = document.createElement('canvas')
                canvas.className = 'pdf-page-canvas'
                viewer.appendChild(canvas)
                pdf.getPage(pageNum).then(page => {
                    const viewport = page.getViewport({ scale: 2 })
                    canvas.height = viewport.height
                    canvas.width = viewport.width
                    page.render({ canvasContext: canvas.getContext('2d'), viewport: viewport })
                })
            }
        })
    }
}


```

Network on firefox: 404

![Screen Shot 2021-04-12 at 14 47 35](https://user-images.githubusercontent.com/41458989/114359385-18e91a80-9b9e-11eb-9a69-282b1c7040cc.png)

Network on safari: OK

![Screen Shot 2021-04-12 at 14 45 52](https://user-images.githubusercontent.com/41458989/114359198-ea6b3f80-9b9d-11eb-8654-ac65d752d50e.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information and will be closed as INVALID.

---

> We store the PDF file above AWS S3, and access it through Cloudfront. To access the PDF file, I have to call api: `/api/preview-file/30.json`
> But on chrome and firefox I get the error: "MissingPDFException", but on Safari everything works fine, which is confusing.
> I have searched but have no answer, looking forward to your help. Thank you!

You've not provided the PDF file in question, which is the very *first* thing we ask for in the ISSUE_TEMPLATE.

Furthermore, this looks for all intents and purposes like a *browser* bug, rather than a PDF.js library one.

Finally, since this is specific to a particular implementation you'll need to provide a *runnable* example; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by namlq93** [comment]
> When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information and will be closed as INVALID.
> 
> > We store the PDF file above AWS S3, and access it through Cloudfront. To access the PDF file, I have to call api: `/api/preview-file/30.json`
> > But on chrome and firefox I get the error: "MissingPDFException", but on Safari everything works fine, which is confusing.
> > I have searched but have no answer, looking forward to your help. Thank you!
> 
> You've not provided the PDF file in question, which is the very _first_ thing we ask for in the ISSUE_TEMPLATE.
> 
> Furthermore, since this is specific to a particular implementation you'll need to provide a _runnable_ example; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
> 
> > PDF.js version: 2.6.347
> 
> That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

My link pdf: `https://swell-cdn.checkit4team.com/132011/91fe7226-9cd9-455b-8cfa-0b4eaf26e785/sample.pdf` It's in my attachment image, but it's stored in s3 and you won't have access to it.  It is difficult to deploy it. Can you review the error?

**Comment by Snuffleupagus** [comment]
> [...] but it's stored in s3 and you won't have access to it.

Again, as already mentioned, without a reduced test-case that we can run/debug this unfortunately isn't actionable!

Please understand that it's *impossible* to do any meaningful debugging from screen-shots alone; and that this is first and foremost a *bug tracker*, rather than a support forum, hence all issues are required to be complete and easily actionable.
