### ISSUE TITLE
offsetParent is not set after iframe show from hidden

### ISSUE THREAD

**Issue by YANGHAOHEHE** [mozilla/pdf.js#13233]
Attach (recommended) or Link to PDF file here:

Configuration:
- Chrome 89.0.4389.114 (arm64):
- operating system: mac os big sur 11.2.3
- PDF.js version:2.6.347
- not a browser extension:

Steps to reproduce the problem:
1.  sorry for my poor english
2.  I am using vue to embed viewer.html as iframe
3. using tabs to show different pdf document
4. when switch from other tag,  one iframe would show and others "hidden" would set to true
5. what I want to do is click an element on one pdf document and jump to the specified pos of another document
6. the steps would be "click the element on iframe pdf1" => "switch tabs"=>" iframe pdf2  would show from hidden"=>" call PDFViewerApplication.pdfViewer._scrollIntoView "
7. but when  iframe pdf2 is  set visible, calling _scrollIntoView immediately would report this error
8. I realized that there might be a reload when pdf2 is show from hidden, because after this error, my following mannal call of _scrollIntoView can work correctly
9.  I wonder if there is really a reload when pdf2 is show? If so, how can I add hook to notice this reload is finished? For example, when open new pdf, I can add hook near "pagesPromise"  to notice my app to do following work

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I am using vue to embed viewer.html as iframe

Sorry, but we cannot provide support for various frameworks here.

---

More generally, this issue unfortunately contains no actionable information. Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum; note also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by YANGHAOHEHE** [comment]
OK. I would close this
