### ISSUE TITLE
Grey background color/text highlight in high contrast mode

### ISSUE THREAD

**Issue by sawanm9000** [mozilla/pdf.js#13230]
Link to PDF file:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Firefox Developer Edition 88.0b9
- Operating system and its version: Windows 10 19042.870
- PDF.js version: Latest version
- Is a browser extension: No

Steps to reproduce the problem:
1. Switch to high contrast mode.
2. Open a PDF file.

What is the expected behavior
- Text and background colors are as defined in the file:
![Screenshot 2021-04-13 112321](https://user-images.githubusercontent.com/25604837/114513249-85f5c200-9c29-11eb-81dd-19049d316021.png)

What went wrong?
- Text has a a highlight/grey background in high contrast mode:
![Screenshot 2021-04-13 112354](https://user-images.githubusercontent.com/25604837/114513988-509da400-9c2a-11eb-848f-f71670548bb9.png)

Possible solution:
- Add the following code after line 32 in pdf_viewer.css

```CSS
.pdfViewer > .page > .textLayer {
    forced-color-adjust: none;
}
```

``forced-color-adjust``, however, is not supported in Firefox.

**Comment by Snuffleupagus** [comment]
> `forced-color-adjust`, however, is not supported in Firefox.

For reference, that's being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1591210

**Comment by marco-c** [comment]
I've reopened the issue since it's still reproducible in Firefox.

**Comment by Snuffleupagus** [comment]
> I've reopened the issue since it's still reproducible in Firefox.

https://bugzilla.mozilla.org/show_bug.cgi?id=1591210 has been fixed, so hopefully this should work now.

**Comment by Snuffleupagus** [comment]
WFM, when testing various high-contrast themes in Windows 11 and Firefox Nightly 115.0a1.
