### ISSUE TITLE
Uncaught syntaxError: Unexpected token error in android chrome browser

### ISSUE THREAD

**Issue by kfyidrig** [mozilla/pdf.js#13245]
When I visited the online demo that url is "https://mozilla.github.io/pdf.js/web/viewer.html" on Android Google browser ,I found some mistakes
![error](https://cdn.ieleven.xyz/temp/error.png)
![debuger](https://cdn.ieleven.xyz/temp%2Fdebuger%20view.png)

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js#online-demo

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's nothing really actionable/valid here.

**Comment by kfyidrig** [comment]
Oh, sorry, there is my configuration:

Web browser and its version: chrome 78.0.3904.96
Operating system and its version: android 10
PDF.js version: 2.9.63
Is a browser extension: no

**Comment by timvandermeij** [comment]
It means that the browser does not support all required features, so for that we have https://mozilla.github.io/pdf.js/legacy/web/viewer.html instead that works in legacy browsers.

**Comment by zzlit** [comment]
@timvandermeij hello，I had the same problem and I don't konw how to solve itI'm use `pdfjs-dist`

**Comment by kfyidrig** [comment]
> @timvandermeij hello，I had the same problem and I don't konw how to solve itI'm use `pdfjs-dist`:
> 
> ```
> Module parse failed: Unexpected token (2413:45)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |         intent: renderingIntent,
> |         renderInteractiveForms: renderInteractiveForms === true,
> >         annotationStorage: annotationStorage?.getAll() || null
> |       });
> |     }
> ```

there are a config problem ,I mean you need to install a loader for webpack ,OR YOU CAN use 
 dist files to solve it .

**Comment by zzlit** [comment]
> > @timvandermeij hello，I had the same problem and I don't konw how to solve itI'm use `pdfjs-dist`:
> > ```
> > Module parse failed: Unexpected token (2413:45)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > |         intent: renderingIntent,
> > |         renderInteractiveForms: renderInteractiveForms === true,
> > >         annotationStorage: annotationStorage?.getAll() || null
> > |       });
> > |     }
> > ```
> 
> there are a config problem ,I mean you need to install a loader for webpack ,OR YOU CAN use
> dist files to solve it .

thanks,I try it
