### ISSUE TITLE
loader support for optional chaining

### ISSUE THREAD

**Issue by rushil-shah87** [mozilla/pdf.js#13248]
I'm running node v14.16.1, npm v7.9.0, react 17.0.2, react-scripts 4.0.3, and pdfjs-dist 2.7.570. I'm getting the following error message when I run `npm start` on my react app:
```
Failed to compile.

./node_modules/pdfjs-dist/build/pdf.js 2407:53
Module parse failed: Unexpected token (2407:53)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                 intent: renderingIntent,
|                 renderInteractiveForms: renderInteractiveForms === true,
>                 annotationStorage: annotationStorage?.getAll() || null
|               });
|             }
```
Not sure what the issue is, or if there should be an additional peer dependency on this dependency

**Comment by Snuffleupagus** [comment]
See e.g. https://github.com/mozilla/pdf.js/issues/13190#issuecomment-814701619, which points to the relevant information.
