### ISSUE TITLE
Disable the Download and Print Button

### ISSUE THREAD

**Issue by Cosmotan01** [mozilla/pdf.js#13251]
Hi,
i will like to disable (hide) the Download and Print Button, can some one provide a simple solution, maybe where to change the source code to achieve this. For future releases it will be nice to have some variables in the viewer.js like : 
DownloadButtonVisible = true;
PrintButtonVisible = true;

Thx for the Help

Cheers

**Comment by Snuffleupagus** [comment]
Please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by Snuffleupagus** [comment]
We *purposely* don't provide support for the sort of customization asked for here, hence you'll have to implement that yourself.

Please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
