### ISSUE TITLE
Open pdf by chrome browser by default with extension

### ISSUE THREAD

**Issue by rulet** [mozilla/pdf.js#13268]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 90.0.4430.72
- Operating system and its version: Windows 10 Pro 20H2
- PDF.js version: 2.3.164
- Is a browser extension: yes

Steps to reproduce the problem:
1. Open pdf with Chrome(not in Chrome by Ctrl+O)
2.

What is the expected behavior? (add screenshot) Opening in PDF.js

What went wrong? (add screenshot) opens in default Chrome pdf viewer

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
It's really not at all clear *exactly* what you're trying to ask/report here, since there's way too little information provided e.g. in the "Steps to reproduce the problem:"-section of the ISSUE_TEMPLATE for this to be actionable/valid.
