### ISSUE TITLE
Text widgets with the same name must share the same value

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13271]
Attach (recommended) or Link to PDF file here:
[multiple.pdf](https://github.com/mozilla/pdf.js/files/6344777/multiple.pdf)

Steps to reproduce the problem:
1. Write something in a field

What is the expected behavior? (add screenshot)
The 3 fields must have the same value

What went wrong? (add screenshot)
The 2 other fields are empty

The three fields share the same name `Text3`.
It works as expected in Adobe and Chrome.

**Comment by calixteman** [comment]
For information, in the pdf in https://github.com/mozilla/pdf.js/issues/13269, there are such text annotations.

**Comment by timvandermeij** [comment]
For future reference, this is the part of the spec that seems to describe this behavior: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=442&zoom=auto,-215,555
