### ISSUE TITLE
Module parse failed: Unexpected token (2413:45)

### ISSUE THREAD

**Issue by Danieliessen** [mozilla/pdf.js#13273]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Vue.js
- Operating system and its version: Windows 10 20H2
- PDF.js version: pdfjs-dist 2.7.570
- Is a browser extension: No

Steps to reproduce the problem:
1.  Create a new vue application
2. npm install pdfjs-dist
3.  Create a component that requests pdfjs-dist 

    import pdfjsLib from "pdfjs-dist/build/pdf";
    import { PDFViewer } from "pdfjs-dist/web/pdf_viewer";
    import "pdfjs-dist/web/pdf_viewer.css";

What is the expected behavior? Well, it works.

What went wrong? 
Error: 

    Module parse failed: Unexpected token (2413:45)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
    https://webpack.js.org/concepts#loaders   
    |         intent: renderingIntent,
    |         renderInteractiveForms: renderInteractiveForms === true,
    >         annotationStorage: annotationStorage?.getAll() || null
    |       });
    |     }

     @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/PDFViewer.vue?vue&type=script&lang=js 3:0-44 6:0-8 30:23-31
     @ ./src/components/PDFViewer.vue?vue&type=script&lang=js
     @ ./src/components/PDFViewer.vue
     @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js
     @ ./src/App.vue?vue&type=script&lang=js
     @ ./src/App.vue
     @ ./src/main.js
     @ multi (webpack)-dev-server/client?http://192.168.1.139:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

     error  in ./node_modules/pdfjs-dist/web/pdf_viewer.js

    Module parse failed: Unexpected token (895:20)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See 
    https://webpack.js.org/concepts#loaders   
    |     this._on(eventName, listener, {
    |       external: true,
    >       once: options?.once
    |     });
    |   }

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): The application does not launch.

**Comment by Snuffleupagus** [comment]
Duplicate of #13200

**Comment by Danieliessen** [comment]
Solved by using 2.3.200 version...

**Comment by thatkidarsene** [comment]
> Solved by using 2.3.200 version...

This worked thanks

**Comment by mt-sizilio** [comment]
@rrrokhtar This lib is wonderful!!! 🥇 
I discovered it recently and it helped me a lot, but unfortunately it stopped working recently. I can't get the URLs anymore.
