### ISSUE TITLE
Limit the display of the PDF pages by specifying the page numbers pdf.js

### ISSUE THREAD

**Issue by Hiro1307** [mozilla/pdf.js#13285]
Hi, I have a requirement which is to restrict certain pages according to the level of access each user have.

For example:
A PDF file have 500 pages
 if user A is an admin, then he can view from page 100 until 400
if user B is normal user, then he can only view from page 20 until 90

![Snag_2590b1c7](https://user-images.githubusercontent.com/43820589/115844691-aa844200-a452-11eb-8f8c-daa3e553dbe6.png)

From my picture, its about something like this where customer can only view first page until page 5. If want to view more need to buy.

Does viewer.js/pdf.js have this kind of function?

All I can do right now is to open specific page

function base64ToUint8Array(base64) {
            var raw = atob(base64);
            var uint8Array = new Uint8Array(raw.length);
            for (var i = 0; i < raw.length; i++) {
                uint8Array[i] = raw.charCodeAt(i);
            }
            return uint8Array;
        }

        var pdfData = base64ToUint8Array(base64);
        var pdfViewerFrame = document.getElementById("pdfFrame");
        pdfViewerFrame.src = "../../pdf.js/web/viewer.html?file=" + "&rand=" + Math.random();
        $(document).ready(function() {
            pdfViewerFrame.onload = function () {
                pdfViewerFrame.contentWindow.PDFViewerApplication.initialBookmark = "page=10";
                pdfViewerFrame.contentWindow.PDFViewerApplication.open(pdfData);

            }
        });

I load the viewer into iframe and used PDFViewerApplication to open pdf byte data from database

Appreciate if anyone can tell if this is possible with current pdf.js build
thanks in advance

**Comment by Snuffleupagus** [comment]
> From my picture, its about something like this where customer can only view first page until page 5. If want to view more need to buy.
> Does viewer.js/pdf.js have this kind of function?

There's no built-in functionality to do something like this, hence you'd have to implement a *custom* viewer where you only fetch the relevant pages. However, please be advised that this will likely *not* prevent a tech-savvy user from accessing other pages manually using e.g. the console and/or debugger in the browser dev-tools.

---

Given that this is first and foremost an open-source *bug tracker*, rather than a support forum, this isn't really something that we can help with; please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
