### ISSUE TITLE
Is there a way to get decrypted bytes provided the password?

### ISSUE THREAD

**Issue by mujahid1005011** [mozilla/pdf.js#13293]
Is there a way to get decrypted bytes provided the password?

**Comment by timvandermeij** [comment]
If the document password is provided then all encrypted bytes are decrypted, so yes, you can get the decrypted content in that case.

**Comment by mujahid1005011** [comment]
@timvandermeij 
getData().then((data) => {console.log(data);}) 
Here this data gives same the bytes which was used as argument in getDocument({data: <bytes>});

**Comment by timvandermeij** [comment]
I don't see the password being passed here; you'll most likely want something like https://github.com/mozilla/pdf.js/blob/c86e70ba08bcde6b2b510bbfd60dc5567ac5285b/test/unit/api_spec.js#L218-L256.

But as clearly requested in the issue template, it's not possible for us to provide more feedback if it's not clear how you're running it, so you'll have to provide a full runnable example (not just code snippets).

**Comment by mujahid1005011** [comment]
> I don't see the password being passed here; you'll most likely want something like:
> https://github.com/mozilla/pdf.js/blob/c86e70ba08bcde6b2b510bbfd60dc5567ac5285b/test/unit/api_spec.js#L218-L256
> 
> But as clearly requested in the issue template, it's not possible for us to provide more feedback if it's not clear how you're running it, so you'll have to provide a full runnable example (not just code snippets).

Thanks very much, you got it right.

**Comment by EmmanuelJego** [comment]
Hi!

I am not able to get the decoded data with the `getData()` function.
Here is my code:
```
const loadingTask = pdfjsLib.getDocument(pdfData)
loadingTask.onPassword = (updatePassword) => {
  updatePassword('qwerty') // 'qwerty' is the correct password for this file
}
const doc = await loadingTask.promise
const decryptedData = doc.getData()
```
The `decryptedData` is the same as the input data, which is obviously not what I expected.

@mujahid1005011 could you tell me how did you manage to make it work? 🙂

Thanks!
