### ISSUE TITLE
PDFPageProxy.render.promise does not return/resolve in XR immersive mode

### ISSUE THREAD

**Issue by itadakimasu** [mozilla/pdf.js#13299]
Attach (recommended) or Link to PDF file here:

Configuration:
- Oculus Quest 2 browser
- Oculus Quest OS
- PDF.js version: pdfjs-dist 2.7.570
- Is a browser extension: NA

Steps to reproduce the problem:
```
const url = "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf";
const pdf = await PDFJS.getDocument(url).promise;
const page = await this.currentPdf.getPage(1);
const context = canvas.getContext("2d") as CanvasRenderingContext2D;
console.log("Before render");
await page.render({ canvasContext: context, viewport: viewport }).promise
console.log("After render");

```
1. Run above in immersive mode on a VR device
2. Observe that "After render" is never printed to the console. As such, the `render()` functionality cannot be used whilst in immersive mode

What is the expected behavior? (add screenshot)
PDGPageProxy.render.promise resolves

What went wrong? (add screenshot)
The promise never resolves and the code awaits infinitely.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Run above in immersive mode on a VR device

First of all, please note that there's no mention in either [the README](https://github.com/mozilla/pdf.js/blob/master/README.md) or [the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions) about the PDF.js library supporting e.g. VR devices.

Secondly, your code-snippet doesn't look like valid JavaScript (e.g. the use of `as` looks strange) and it also cannot be run-as; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by canxerian** [comment]
@Snuffleupagus, the code snippet is written in Typescript.

I understand there isn't support for VR devices at present. Is this on the roadmap?
