### ISSUE TITLE
Ink-Annotations not shown

### ISSUE THREAD

**Issue by SimonErm** [mozilla/pdf.js#13298]
Attach (recommended) or Link to PDF file here:
[output.pdf](https://github.com/mozilla/pdf.js/files/6374987/output.pdf)

Configuration:
- Web browser and its version: Firefox 88.0
- Operating system and its version: macOS Big Sur 11.2.3 (20D91)
- PDF.js version: 2.8.243
- Is a browser extension: no/Firefox built-in

Steps to reproduce the problem:
1.  add Ink-Annotations to a pdf (i use https://github.com/highkite/pdfAnnotate, Annotations with appearance streams are shown correctly)
2. open output file in firefox

What is the expected behavior? 
The annotations should be visible.
![Bildschirmfoto 2021-04-26 um 09 15 48](https://user-images.githubusercontent.com/33630884/116043809-6a020f80-a670-11eb-973c-6f2df3dae532.png)

What went wrong? 
The annotations are added to the dom but invisible.
![Bildschirmfoto 2021-04-26 um 09 18 26](https://user-images.githubusercontent.com/33630884/116043867-7e460c80-a670-11eb-964d-0cc2c6dbfb61.png)

Tested successfull with FoxitReader, AcrobatReader, Chrome and Safari.

**Comment by calixteman** [comment]
The `Ink` annotation doesn't contain an appearance so we should build a default one using the color and the `Inklist`.

**Comment by SimonErm** [comment]
Thanks for the fast reply. 
The Ink annotation is already build, but it's transparent.
If i change the stroke manual from transparent to black it is shown like it should.

**Comment by Snuffleupagus** [comment]
This is (essentially) just another case of issue #6810.

**Comment by calixteman** [comment]
We draw the annotation on the canvas using the `AP` entry and then we use a transparent line in svg to have an object to interact with in the annotation_layer.
Open your pdf here: https://brendandahl.github.io/pdf.js.utils/browser/#root=997,0 
and you'll see that no appearance stream (AP) is there.
But if you open https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-caret-ink.pdf in the pdf browser with `#root=25,0`, you'll see an AP entry with some pdf code to render the line.
