### ISSUE TITLE
API to get current page number

### ISSUE THREAD

**Issue by otseng** [mozilla/pdf.js#13295]
Is there a way to access what is the current page number that is being viewed?

In my app, I want to be able to develop a way to save the current page number and then when the pdf document is loaded next time to jump to that page.

**Comment by timvandermeij** [comment]
There's a property called `currentPageNumber`; see:

https://github.com/mozilla/pdf.js/blob/03c8c89002ec2c1a2223c3a5926560686f8c3917/web/base_viewer.js#L250-L273
