### ISSUE TITLE
Remember previous position after close firefox

### ISSUE THREAD

**Issue by rulet** [mozilla/pdf.js#13308]
How to make pdf.js remember previous position in pdf file when close and open firefox again? Maybe to edit some options in about:config?

**Comment by timvandermeij** [comment]
In general the position is remembered as much as possible, but we have no control over the browser opening/closing. That can most likely only be done upstream, so please open an issue for that in Bugzilla instead.

**Comment by rulet** [comment]
The thing is that when pdf.js is installed in chrome as extension and when it open pdf file it remember previouse position when las time that pdf file was opened. That function available by extension preferences in chrome browser. How to do that in firefox?
