### ISSUE TITLE
Object not masked properly

### ISSUE THREAD

**Issue by cracyc** [mozilla/pdf.js#13315]
Attach (recommended) or Link to PDF file here:
[2021_coursemap_wmhalf5k.pdf](https://github.com/mozilla/pdf.js/files/6399999/2021_coursemap_wmhalf5k.pdf)

Configuration:
- Web browser and its version: Firefox 88
- Operating system and its version: Windows 10 (It looks correct on firefox 88 that ships with fedora 34).
- PDF.js version: 2.8.243
- Is a browser extension: Yes

Steps to reproduce the problem:
1.  Open the file

What is the expected behavior? (add screenshot)
From Edge pdf viewer
![Capture](https://user-images.githubusercontent.com/9255333/116582145-ac2e8980-a8da-11eb-90b8-8cac27697bc2.PNG)
What went wrong? (add screenshot)
![Capture](https://user-images.githubusercontent.com/9255333/116582009-899c7080-a8da-11eb-96ca-146ce94c9636.PNG)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by brendandahl** [comment]
Also looks fine on MacOS.

**Comment by Snuffleupagus** [comment]
Related to issue #8019 and/or #8022; hence fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1336572 and/or https://bugzilla.mozilla.org/show_bug.cgi?id=1336591
