### ISSUE TITLE
import of pdfjs throws an error

### ISSUE THREAD

**Issue by albertdugba** [mozilla/pdf.js#13331]
Hello guys, very new to the pdfjs library, I was installed the `pdfjs-dist` package into my react app, after importing like this: `import pdfjsLib from 'pdfjs-dist/build/pdf'`
`import *as pdfjsLib from 'pdfjs-dist/build/pdf'`

After trying both of these, this was what pI had in my terminal
```
./node_modules/pdfjs-dist/build/pdf.js 2407:53
Module parse failed: Unexpected token (2407:53)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                 intent: renderingIntent,
|                 renderInteractiveForms: renderInteractiveForms === true,
>                 annotationStorage: annotationStorage?.getAll() || null
|               });
|             }
```

Any help will be much appreciated. Thanks

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as this isn't really actionable/valid.

Most likely, the following part of the [`pdfjs-dist` README](https://github.com/mozilla/pdfjs-dist#pdfjs) explains your problem:
> For usage with older browsers or environments, without support for modern features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and nullish coalescing; please see the `legacy` folder.

**Comment by albertdugba** [comment]
@Snuffleupagus  thank you. after reading the  readme, I still cant figure out how I can fix it

**Comment by Snuffleupagus** [comment]
> after reading the readme, I still cant figure out how I can fix it

Try importing from `pdfjs-dist/legacy/build/pdf` instead, which is what the README tells you; but as already mentioned with *all* of the requested information missing this isn't actionable/valid.

**Comment by albertdugba** [comment]
okay

**Comment by Snuffleupagus** [comment]
> Please how do I make sure that I support the modern features

Huh; the README is telling you that *if* you're trying to use the PDF.js library in an environment that lack support for the listed features, you must use the `legacy` build.

---

Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum.
