### ISSUE TITLE
PDF.js inside asp.net project

### ISSUE THREAD

**Issue by RobertoVCamargo** [mozilla/pdf.js#13335]
Dear sirs,

I have a request about showing PDF´s under circumstances, and I have the impression the PDF.js can help me to resolve this.

Starting to use it, I´m using almost 100 % the code off the Hello World example inside my project, adding a new html page.

The problem I´m having is this = 
![image](https://user-images.githubusercontent.com/15171527/117076920-9ae7e180-ad0d-11eb-82a1-8a9e9a4a84d3.png)

Trying to avoid problems, I put my code pointing to the pdf.js site, as here = 
![image](https://user-images.githubusercontent.com/15171527/117077239-1cd80a80-ad0e-11eb-8390-46f3cc353469.png)

I don´t see where I could be making any mistake that can causes this. I´m an VB programmer, with small skills with js (almost none). To me, it looks like the operator "=>" inside pdf.js is causing the problem.

For this problema, I can walk along the code better with IE11, and Chrome and Edge don´t help me a lot.

I thank you in advance for any help you can give me. And beg your pardon for not following all the rules for asking for help.

Roberto Camargo / Rio de Janeiro / Brazil
robertovcamargo@yahoo.com

**Comment by Snuffleupagus** [comment]
First of all, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since those details matter (a lot) when explaining your problem.

> Trying to avoid problems, I put my code pointing to the pdf.js site, as here

You should *never* link directly to that code, since it changes with every merge, and instead use official releases; see https://mozilla.github.io/pdf.js/getting_started/#download

> To me, it looks like the operator "=>" inside pdf.js is causing the problem.

Unfortunately browsers and/or environments without arrow function support is now too old to be supported by the PDF.js library.
All reasonably modern browsers now support arrow functions, please note e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#browser_compatibility

> For this problema, I can walk along the code better with IE11, and Chrome and Edge don´t help me a lot.

As is already mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is no longer supported by the PDF.js library.

---

Finally, please keep in mind that this is first and foremost and open-source *bug tracker*, rather than a support forum.

**Comment by RobertoVCamargo** [comment]
Configuration:

Web browser and its version: IE11 (as previous commented, for allowing me step debugging the code a little better) / Chrome 89.0.4389.72 (Versão oficial) 32 bits / Microsoft Edge Versão 89.0.774.68 (Compilação oficial) (64 bits)
Operating system and its version: Windows 10 Pro
PDF.js version: 2.7.570-es5
Is a browser extension: no
Steps to reproduce the problem: call the helloworld.htm page, inside the Visual Studio 2019 Asp.net project and fall in the problem.
The behavior is the same for the presented page, in all the tree browser. If my comment about the operator was made, this was thanks to IE11, because Chrome and Edge don´t show anything about the error, whilst IE11 shows.

As a only bug tracker, please indicate me where I will get better help about pdf.js usage. 

page code (both local and remote js code - here commented) = 
---------------------------------
<!DOCTYPE html>
<html>
<head>
    
    <script src="pdf.js/pdf.js"></script>
    <title>'Hello, world!' example</title>
</head>
<body>

    
    <script src="pdf.js/pdf.js"></script>

    // <h1>PDF.js 'Hello, world!' example</h1>

    <canvas id="the-canvas"></canvas>

    <script id="script">
        //
        // If absolute URL from the remote server is provided, configure the CORS
        // header on that server.
        //
        var url = '/dje/20081211SEGDJETJRJ_86.pdf';
        //var url = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf';

        //
        // The workerSrc property shall be specified.
        //
        // Loaded via <script> tag, create shortcut to access PDF.js exports.
        var pdfjsLib = window['pdf.js/pdf'];
        //var pdfjsLib = window['//mozilla.github.io/pdf.js/build/pdf'];
        //pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';
        pdfjsLib.GlobalWorkerOptions.workerSrc = 'pdf.js/pdf.worker.js';
        //
        // Asynchronous download PDF
        //
        var loadingTask = pdfjsLib.getDocument(url);
        loadingTask.promise.then(function (pdf) {
            //
            // Fetch the first page
            //
            pdf.getPage(1).then(function (page) {
                console.log('PDF loaded');

                // Fetch the first page
                var pageNumber = 1;
                pdf.getPage(pageNumber).then(function (page) {
                    console.log('Page loaded');

                    var scale = 1.5;
                    var viewport = page.getViewport({ scale: scale, });

                    //
                    // Prepare canvas using PDF page dimensions
                    //
                    var canvas = document.getElementById('the-canvas');
                    var context = canvas.getContext('2d');
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;

                    //
                    // Render PDF page into canvas context
                    //
                    var renderContext = {
                        canvasContext: context,
                        viewport: viewport,
                    };
                    var renderTask = page.render(renderContext);
                    renderTask.promise.then(function () {
                        console.log('Page rendered');
                    });
                });
            }, function (reason) {
                // PDF loading error
                console.error(reason);
            });

        });
    </script>

    <hr>
    <h2>JavaScript code:</h2>
<pre id="code"></pre>
    <script>
        document.getElementById('code').textContent =
            document.getElementById('script').text;
    </script>
</body>
</html>
------------------------------------------
Page view, after loading (with no pdl loaded) = 
![image](https://user-images.githubusercontent.com/15171527/117152903-d8418300-ad90-11eb-8eed-014babbf88bb.png)

**Comment by RobertoVCamargo** [comment]
![image](https://user-images.githubusercontent.com/15171527/117154654-71bd6480-ad92-11eb-94ba-452955a6c5ed.png)

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem: call the helloworld.htm page,

That example *should* work, when run e.g. locally, so it's very difficult to tell what's going wrong.

> Steps to reproduce the problem: call the helloworld.htm page, inside the Visual Studio 2019 Asp.net project and fall in the problem.

Unfortunately we cannot support "Visual Studio 2019 Asp.net project", whatever that is, here.

---

Note that code-snippets are of no use, since it's impossible for anyone else to run your *exact* code; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

All-in-all, this issue unfortunately isn't really actionable/valid.
