### ISSUE TITLE
"commonObj" and "opList" hash difference between Node.js and Chromium environments

### ISSUE THREAD

**Issue by m-majetic** [mozilla/pdf.js#13330]
### The goal:
I'm trying to get the same hash of the `commonObjs` and `opList` objects ( collections ) in both the Chromium and Node.js environment.
These "hashes" I'm trying to get are Sha256 hashes of the JSON stringified `commonObjs` and `opList` objects.

### The issue: 
The issue is that I'm getting a different hash of the `opList` and `commonObjs` objects in the two different environments ( Node.js and the Browser ).
My assumption is that the structure of the objects is different.

I wish that this can be amended by a simple configuration option, but it could be something tied to the environment that can't be helped.

### Configuration:
Web browser: Chromium Version 89.0.4389.114 (Developer Build) built on Debian 10.9, running on Debian 10.9 (64-bit)
OS: Debian 10.9
PDF.js version: 2.7.570
Node.js version: 10.24.1
The gulp configuration used for building the libraries in both environments: `gulp minified-legacy`

### How to reproduce:
Try out the code in this repository: https://github.com/m-majetic/pdfjs-environment-differences

**Comment by Snuffleupagus** [comment]
> I'm trying to get the same hash of the `commonObj` and `opList` objects ( collections ) in both the Chromium and Node.js environment.

It's not really clear what "hash" refers to here, since there's no property with that name in e.g. `commonObjs` (note the correct spelling) or in the data returned by `PDFPageProxy.getOperatorList` (which I'm guessing that "opList" refers to); hence please provide more specific information here!

**Comment by m-majetic** [comment]
Hi !
Thank you for your reply.

I'm sorry for misspelling `commonObjs`.

Did you take a look at the example repository ?
The hashes I have written about are SHA256 of the JSON stringified `commonObjs` and `opList` respectively.

**Comment by Snuffleupagus** [comment]
> Did you take a look at the example repository ?
> The hashes I have written about are SHA256 of the JSON stringified `commonObjs` and `opList` respectively.

I have not yet done that, since it (generally) must be possible to understand what an issue even is about before running someone's custom code. (And, as mentioned, no "hash" property exists in those data-structures.)

**Comment by m-majetic** [comment]
I'm not sure if my intention was clearly carried across by reading your answer.

This is what I'm trying to do with the `opList` and `commonObjs` objects after I extract them from the `page`:
```js
var opListHash = sha256(JSON.stringify(opList))
console.log("This is the opList hash", opListHash);
var commonObjHash = sha256(JSON.stringify(page.commonObjs))
console.log("This is the commonObj hash", commonObjHash);
```

**Comment by Snuffleupagus** [comment]
> The issue is that I'm getting a different hash of the `opList` and `commonObjs` objects in the two different environments ( Node.js and the Browser ).
> [...]
> This is what I'm trying to do with the `opList` and `commonObjs` objects after I extract them from the `page`:
> 
> ```js
> var opListHash = sha256(JSON.stringify(opList))
> console.log("This is the opList hash", opListHash);
> var commonObjHash = sha256(JSON.stringify(page.commonObjs))
> console.log("This is the commonObj hash", commonObjHash);
> ```

Thank you; that's a lot clearer and it also saves me some time (by not having to clone/run your code).

Unfortunately that's not really a use-case that's relevant for e.g. the viewer, and as such we can't/won't guarantee that it behaves *identically* when comparing e.g. browsers and Node.js environments.
Please note that the PDF.js library is/was written primarily for usage in browsers, with support for Node.js essentially tacked on afterwards (which unfortunately shows), and we thus *by default* modify some options to prevent bugs specifically in Node.js environments; see https://github.com/mozilla/pdf.js/blob/master/src/display/api_compatibility.js

Most likely, the differing default options in browsers/Node.js should explain what you're seeing. You can *obviously* set the options manually, when calling `getDocument`, such that you get the same behaviour in all environments.

**Comment by m-majetic** [comment]
Thank you !

I will try out different options and see if they make any difference.

I'd consider this issue closed.
