### ISSUE TITLE
[Regression] Highlighting of search results broken in some cases, after PR 13306 

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#13345]
Attach (recommended) or Link to PDF file here: https://github.com/tesseract-ocr/tesseract/files/947838/2.pdf

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `2.9.223`, or any version after PR #13306 landed.
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open the document above, e.g. with https://mozilla.github.io/pdf.js/web/viewer.html
2. Search for "of the r"

What is the expected behavior? (add screenshot)
Correct highlighting, please see:

![correct](https://user-images.githubusercontent.com/2692120/117328223-b7158b00-ae93-11eb-805c-73718ff569b5.png)

What went wrong? (add screenshot)
Incorrect highlighting, please see:

![incorrect](https://user-images.githubusercontent.com/2692120/117328447-efb56480-ae93-11eb-8506-da9fc0eb9630.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

/cc @brendandahl

**Comment by cetinsert** [comment]
| 2.7.570<br>2.6.347 | difference | 2.8.335 |
| ----- | ----- | ----- |
| ![image](https://user-images.githubusercontent.com/27027/118619870-f0d58280-b7ff-11eb-8513-9cd4856a007f.png) | ![image](https://user-images.githubusercontent.com/27027/118620860-da7bf680-b800-11eb-8907-504ade234ffa.png) | ![image](https://user-images.githubusercontent.com/27027/118620077-237f7b00-b800-11eb-8a9b-1829c5b0a635.png) |

**Comment by Snuffleupagus** [comment]
The screen-shot in https://github.com/mozilla/pdf.js/issues/13345#issuecomment-842980507 has, as far as I can tell, *nothing* to do with this issue which is specifically about a regression regarding highlighting of search results.

> PDF.js version: `2.9.223`, or any version after PR #13306 landed.

Given the above information provided in the OP, that makes https://github.com/mozilla/pdf.js/issues/13345#issuecomment-842980507 even more strange/unrelated.

**Comment by cetinsert** [comment]
@Snuffleupagus – Your comment is very hard to digest. I am trying to be helpful figuring out between which two versions the `.textLayer > span` element positioning regression actually happened. And we now see clearly it happened between `2.7.570` and `2.8.335`. How does that count as strange or unrelated?!

**Comment by cetinsert** [comment]
Ok, I now see that my comment with the image difference is not even part of this issue.
Do you (all devs of PDF.js) think https://github.com/mozilla/pdf.js/issues/13345#issuecomment-842980507 qualifies for its own issue?

**Comment by Snuffleupagus** [comment]
> Do you (all devs of PDF.js) think [#13345 (comment)](https://github.com/mozilla/pdf.js/issues/13345#issuecomment-842980507) qualifies for its own issue?

Probably not, given that this is the result of PR #12896 which is an *overall* improvement for most documents.

---

Note that as mentioned in the *first* paragraph of https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, we try to limit each issue to just one problem since otherwise it becomes very difficult to track issues effectively.

**Comment by cetinsert** [comment]
I did my due diligence and report my findings here https://github.com/mozilla/pdf.js/issues/13396.
No big deal if closed because PR #12896 is an improvement for most other documents.

I do sincerely apologize for temporarily derailing this issue.
