### ISSUE TITLE
Gradient Bleed

### ISSUE THREAD

**Issue by hrvojelabtiva** [mozilla/pdf.js#13348]
[gradient_bleed_issue.pdf](https://github.com/mozilla/pdf.js/files/6440790/gradient_bleed_issue.pdf)

Configuration:
- Chrome (latest)
- Mac OS X Big Sur 11.2.1
- PDF.js version: latest (reproduced on pdf.js demo page)

Steps to reproduce the problem:
1. Open attached pdf in pdf.js demo viewer
2. Notice the gradients spilling over the stop color into solid vertical lines

What is the expected behavior? (add screenshot)
<img width="990" alt="expected" src="https://user-images.githubusercontent.com/9571114/117435991-c269c480-af2e-11eb-8621-bdd4e02bdb35.png">

What went wrong? (add screenshot)
<img width="979" alt="actual" src="https://user-images.githubusercontent.com/9571114/117435941-b251e500-af2e-11eb-8b64-76d0aaa28745.png">

Might be related to:
https://github.com/mozilla/pdf.js/issues/11018

**Comment by Snuffleupagus** [comment]
WFM on Windows; this is likely a MacOS-specific bug.

**Comment by calixteman** [comment]
WFM too on Linux in Firefox nightly.

**Comment by hrvojelabtiva** [comment]
> WFM on Windows; this is likely a MacOS-specific bug.

Yep, I just tried on Win, works fine there.

**Comment by hrvojelabtiva** [comment]
It seems to be specific to Chromium on OS X (Chrome & MS Edge), as Firefox and Safari also work as expected.

**Comment by Snuffleupagus** [comment]
> It seems to be specific to Chromium on OS X (Chrome & MS Edge), as Firefox and Safari also work as expected.

Based on this information, this really does look like a *browser and/or platform* specific bug rather than a PDF.js library one.
Hence it's unfortunately not entirely clear, at least to me, that it's actionable/valid *here*.

**Comment by hrvojelabtiva** [comment]
Seems to be a _browser and/or platform_ specific bug.
