### ISSUE TITLE
Changing text selection / highlight colors

### ISSUE THREAD

**Issue by mgroth0** [mozilla/pdf.js#13353]
Hi, I'm using a slightly modified version of [NightPDF](https://github.com/eleloya/NightPDF) to read PDFs. I read with complete inversion, so white text is displayed on a black background. However, I can hardly see the text highlight colors at all, especially when I use the find feature. I also have a color-deficiency, and this may be part of the problem.

Here are the default colors:

Normal Selection:
![Screen Shot 2021-05-07 at 4 07 11 PM](https://user-images.githubusercontent.com/12831489/117502958-4b442880-af4e-11eb-9399-a55a405dcdaa.png)

Find:

![Screen Shot 2021-05-07 at 4 07 36 PM](https://user-images.githubusercontent.com/12831489/117503002-58f9ae00-af4e-11eb-95d0-accbfacb3c72.png)

I can hardly see these, and would like to make it a strong yellow or blue (FFFF00 or 0000FF).

NightPDF applies a filter that changes colors on the page. This can be seen [in this js file](https://github.com/eleloya/NightPDF/blob/master/app.js) at line 444. I just set inversion to 100% and leave all other settings at 0/default.

In order to try changing the highlight or find color, I tried to add this to the css:
```js
   const highlightStyle = "\n.textLayer .highlight {\n" +
        "        background-color: rgba(0, 0, 0, 1);\n" +
        "      }\n" +
        ".textLayer .highlight.selected {\n" +
        "  background-color: rgba(0, 0, 0, 1);\n" +
        "}" +
        ".textLayer ::selection {\n" +
        "  background: rgba(0, 0, 0, 1);\n" +
        "}"
```
This is then added to the iFrames css. I used [text_layer_builder.css](https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.css) to try to find find the right css. The reason I made the highlights all black was because I was trying to get it to show up as white (just for testing purposes) on the black background. Then, iI would try to ge it to the right color.

So my expectation with the above css was to see a white highlight on the black background. However, the highlight is grey:

Normal highlight:
![Screen Shot 2021-05-07 at 4 40 14 PM](https://user-images.githubusercontent.com/12831489/117506003-e808c500-af52-11eb-8048-d1b46b4cf151.png)

Find:
![Screen Shot 2021-05-07 at 4 40 32 PM](https://user-images.githubusercontent.com/12831489/117506039-f35bf080-af52-11eb-8b2e-b5f6a20c5fff.png)

In addition, I tried turning off the inversion filter in NightPDF (and thus expected a black highlight), but it was still grey:

Normal highlight
![Screen Shot 2021-05-07 at 4 41 26 PM](https://user-images.githubusercontent.com/12831489/117506127-138baf80-af53-11eb-905a-8ffa0d7582fc.png)

Find highlight
![Screen Shot 2021-05-07 at 4 41 43 PM](https://user-images.githubusercontent.com/12831489/117506146-1ededb00-af53-11eb-8e1b-12e79c2c6589.png)

So, my one question here is really **how can I have the direct control over the text selection/highlight/find color**

**Comment by Snuffleupagus** [comment]
> I'm using a slightly modified version of [NightPDF](https://github.com/eleloya/NightPDF) to read PDFs.

Please note that that's a *different* project, which is not connected to the PDF.js project, and as such we unfortunately cannot really provide (much) help/support for that here.

> In addition, I tried turning off the inversion filter in NightPDF (and thus expected a black highlight), but it was still grey:

Perhaps this is what you're looking for?
https://github.com/mozilla/pdf.js/blob/a2652bafd91db17ad30a70bb1be703666efdea49/web/text_layer_builder.css#L23

(Please note that the general problem of inverting document colours is tracked in issue #2071.)

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable/valid.

**Comment by mgroth0** [comment]
Thank you! `opacity` of `.textLayer` completely resolved my original issue.

Apologies of not including this before:

Configuration:

Web browser and its version: Electron
Operating system and its version: MacOS
PDF.js version: Unsure
Is a browser extension: No
Steps to reproduce the problem: 
1. Clone [NightPDF](https://github.com/eleloya/NightPDF)
2. Add code `highlightStyle` code above to the css appended in [this js file](https://github.com/eleloya/NightPDF/blob/master/app.js?rgh-link-date=2021-05-07T20%3A42%3A32Z), line 444
3. Open a PDF and set inversion to 100%
4. Check highlight and "find" colors

What is the expected behavior? - see OP
What went wrong? - see OP

If I may append one small and closely related issue/question here, these changes I have made after changing the opacity have now drowned out the text like so: 

```js
    const highlightStyle = "\n.textLayer{" +
        "opacity: 0.9" +
        "}\n" +
        
        /*find select, gets inverted*/
        ".textLayer .highlight.selected {\n" +
        "  background-color: rgba(100, 100, 0, 1);\n" +
        "}" +

        /*normal select, gets inverted*/
        ".textLayer ::selection {\n" +
        "  background: rgba(0, 0, 255, 1);\n" +
        "}"
```

"Find" selection at top right, normal selection below
![Screen Shot 2021-05-07 at 5 38 34 PM](https://user-images.githubusercontent.com/12831489/117511005-1094bd00-af5b-11eb-8902-b76d25b4131f.png)

Is there a property that controls text color under the highlight? I have skimmed the issue you linked and could not find it.

**Comment by mgroth0** [comment]
Alternatively, can any property move the highlight rectangle behind the text so that the white text is not washed out?

**Comment by mgroth0** [comment]
Understood! Thank you for all the information.

**Comment by noman26636** [comment]
Can I get multiple highlight colors for every annotated text? I mean dynamically generates?

**Comment by andrewdoro** [comment]
new solution for having the color different while keeping the text in view

<img width="735" alt="Image" src="https://github.com/user-attachments/assets/c7016e46-f757-45bb-8c8d-0cc5602c38cb" />


basically you can add any color as the background for selection for .textLayer

``` css
.textLayer ::selection {
  color: transparent;
  
  @apply bg-badgeLightBlue  dark:bg-[#b0c9e9]
}
```

and then where you render your textLayer add `mix-blend-multiply`
``` css
.textLayer {
mix-blend-mode: multiply;
}
```

you can see this in actions on Unriddle (light/dark mode)

https://www.unriddle.ai/
