### ISSUE TITLE
JBIG2 image decoder does not work at all

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#13367]
I am using JPG, JPX and JBIG2 decoders from here: https://github.com/mozilla/pdfjs-dist/tree/master/image_decoders

The JBIG2 decoder does not work at all. I think it is because of the typo that you made: you wrote "Jbig2mage" instead of "Jbig2Image".

https://github.com/mozilla/pdfjs-dist/blob/master/image_decoders/pdf.image_decoders.js#L8603

I found a demo here: https://github.com/mozilla/pdf.js/tree/master/examples/image_decoders , but it parses only a JPG image. Could you add a demo code for parsing JBIG2 and JPX?

**Comment by timvandermeij** [comment]
You're right. Fixed by the PR above. Thank you for reporting this!

**Comment by photopea** [comment]
Thanks a lot for fixing it! BTW. I could not parse these images correctly. The JBig2 returns a wrong output (all pixels white), while the JPX throws an error. Could you add these to the demo?

[images.zip](https://github.com/mozilla/pdf.js/files/6468341/images.zip)
