### ISSUE TITLE
Warning: Unimplemented annotation type "GoldGrid:AddSeal", falling back to base annotation.

### ISSUE THREAD

**Issue by orange-cyp** [mozilla/pdf.js#13370]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by orange-cyp** [comment]
![image](https://user-images.githubusercontent.com/76673376/118098864-0b29ed80-b407-11eb-8f51-43bb8cfd2747.png)

**Comment by orange-cyp** [comment]
the seal becomes smaller

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is missing ever single piece of information required in order to be actionable/valid.
