### ISSUE TITLE
Digital signature text gets corrupted

### ISSUE THREAD

**Issue by LaJu88** [mozilla/pdf.js#13388]
Configuration:
- Web browser and its version: **Chromium 65.0.3325.181 used with CefSharp**
- Operating system and its version: **Microsoft Windows 10 Pro,  10.0.19042 Build 19042**
- PDF.js version: **2.9.296**
- Is a browser extension: yes

Steps to reproduce the problem:
1.  
2.

What is the expected behavior? 
This was displayed in Chrome browser.
![image](https://user-images.githubusercontent.com/77725783/118483989-00c56780-b717-11eb-9c56-c12de3fea47a.png)

What went wrong?
This was displayed with CefSharp/Chromium. I don't see any errors or warnings. 
I only included the date. But it was the same with my name. It appears random characters are missing.
![image](https://user-images.githubusercontent.com/77725783/118484047-120e7400-b717-11eb-8cab-1c5eb43a522f.png)

I've used `gulp generic-legacy` to build from source. 

Does anyone else have problems with older versions of chrome/chromium?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): no link

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE.md is *always required* when opening an issue, since as-is there's no actionable information provided and the issue will thus be closed as INCOMPLETE.

**Comment by LaJu88** [comment]
@Snuffleupagus  Great, thx for the fast reply
