### ISSUE TITLE
Update the Node.js version on the bots

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#13384]
Recently a couple of `npm` packages have started requiring Node.js versions `>= 12`, and that doesn't work on the bots since they apparently use an older Node.js version.

Hence I'd suggest updating the bots to use the latest LTS version of Node.js, so that future `npm` package updates won't be blocked.

/cc @brendandahl

**Comment by brendandahl** [comment]
For some reason the current LTS binary for windows installs the wrong NPM version. I was able to install the latest npm, but that was also broken. I then downgraded to the one that matches the linux bot and that seems to work.

**Comment by brendandahl** [comment]
Both bots should be fine now after fixing #13458.

**Comment by timvandermeij** [comment]
@brendandahl Could you perhaps also update https://github.com/mozilla/pdf.js/wiki/Bots with the new versions/configuration for later reference?

**Comment by Snuffleupagus** [comment]
Thanks a lot for fixing this!
