### ISSUE TITLE
Changing scale and resizing canvas causes text layer misalignment

### ISSUE THREAD

**Issue by naveensaigit** [mozilla/pdf.js#13382]
Some pdf's are being rendered in a slightly lower resolution, so I'm using the suggestion given here  https://github.com/mozilla/pdf.js/issues/10509#issuecomment-517009617
However, when I change the `displayWidth`, the font, top and left properties for the spans of the text layer are too big and are misaligned.

I know there is a PDFViewer option too where the text layer is generated by default. Is there any way to change the resolution for the PDFViewer? I couldn't find it

Attach (recommended) or Link to PDF file here:
https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Chrome v90.0.4430.212
- Operating system and its version: Windows 10
- PDF.js version: 2.9.282
- Is a browser extension: No

Steps to reproduce the problem:

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/56525288/118373013-12512700-b5d2-11eb-9aa0-5ebadc825349.png)
The clarity in the [example](http://mozilla.github.io/pdf.js/web/viewer.html) is very nice, and the text layer is aligned at the same time.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/56525288/118373087-7aa00880-b5d2-11eb-82e7-654d4f48e9a6.png)
The clarity is good (it seems bad in the image, but it is good) when I increase the scale. However, text layer is misaligned.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
See [Codepen](https://codepen.io/naveen_sai/pen/xxqOOgZ?editors=1001)

**Comment by Snuffleupagus** [comment]
> Some pdf's are being rendered in a slightly lower resolution, so I'm using the suggestion given here [#10509 (comment)](https://github.com/mozilla/pdf.js/issues/10509#issuecomment-517009617)

I don't think that's a recommended solution, since it will required that you *manually* handle the textLayer placement correctly (which as you've seen can be difficult).

> I know there is a PDFViewer option too where the text layer is generated by default.

Yes, and that's the *simpler*/*intended* way of doing things; please refer to the "viewer component" examples instead: https://github.com/mozilla/pdf.js/tree/master/examples/components

> Is there any way to change the resolution for the PDFViewer? I couldn't find it

I'm not sure what you mean by "resolution" here, since `PDFViewer` (among other things) will handle e.g. HiDPI-support for you.

If you simply refer to the *scale*, the you can change that using the `currentScale`/`currentScaleValue` setters on a `PDFViewer`-instance; again refer to the "viewer component" examples and the following JSDocs: https://github.com/mozilla/pdf.js/blob/438cf1e438302de470b86f93f2e0a36a377af94d/web/base_viewer.js#L333-L370

**Comment by naveensaigit** [comment]
> I'm not sure what you mean by "resolution" here, since PDFViewer (among other things) will handle e.g. HiDPI-support for you.

By resolution, I meant DPI. Is there any way for me to change the DPI to make the output sharper like what happens in the first case?

> If you simply refer to the scale, then you can change that using the currentScale/currentScaleValue setters on a PDFViewer-instance; again refer to the "viewer component" examples and the following JSDocs:

I will look into it once again, although changing the scale was increasing the size of the page, but had no effect on the clarity

**Comment by Snuffleupagus** [comment]
> Is there any way for me to change the DPI to make the output sharper like what happens in the first case?

No, the "viewer components" simply adapts to the correct DPI (depending on the screen used).

It's not really clear what "the first case" refers to above; however please note that https://github.com/mozilla/pdf.js#online-demo uses the *exact* same underlying components as the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components, and rendering should thus be identical between the two (for the same scale).

**Comment by naveensaigit** [comment]
> It's not really clear what "the first case" refers to here; 

By the first case, I meant changing DPI using https://github.com/mozilla/pdf.js/issues/10509#issuecomment-517009617. 

> however please note that https://github.com/mozilla/pdf.js#online-demo uses the _exact_ same underlying components as the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components, and rendering should thus be identical between the two (for the same scale).

Yeah, which is why I'm surprised! Here are 2 photos (scale is FIT_WIDTH for both of them) -
 
![image](https://user-images.githubusercontent.com/56525288/118384736-36d6ee80-b626-11eb-8dac-ed19f3891e61.png)
Online Demo

![image](https://user-images.githubusercontent.com/56525288/118384760-67b72380-b626-11eb-8803-cf559060cc76.png)
Single Page Viewer from examples

Notice how the single page viewer example is slightly blurred as compared to the online demo (look at the names). I'm not sure what's causing this. Is it because of the version, because I tried the Single Page viewer with 2.4.456, 2.7.570, 2.8.355, but the online demo runs 2.9.282

**Comment by Snuffleupagus** [comment]
> scale is FIT_WIDTH for both of them

Huh, but there's no scale value with that name; did you actually mean "page-width" here?

> Notice how the single page viewer example is slightly blurred as compared to the online demo (look at the names).

This doesn't really make sense, and I cannot reproduce that locally, but with only a screen-shot this issue really isn't actionable/valid.
You'll need to provide a *runnable* example, comparing the demo viewer and the viewer-component example at the *same exact* scale value in order for anyone to debug this further.
