### ISSUE TITLE
Rendering is different with differents zoom levels

### ISSUE THREAD

**Issue by Triton972** [mozilla/pdf.js#13392]
Attach (recommended) or Link to PDF file here:
[nd2295.pdf](https://github.com/mozilla/pdf.js/files/6497213/nd2295.pdf)

Configuration:
- Web browser and its version: PySide2.QWebEngineView
- Operating system and its version: Windows10, Qt for Python version 5.15.0 (PySide 2) et Python 3.7.8
- PDF.js version: 2.7.570
- Is a browser extension:

Steps to reproduce the problem:
1. Run Python App

```
import sys
from PySide2 import QtCore, QtWidgets, QtWebEngineWidgets

class ShowPdf(object):
    def __init__(self):
        super().__init__()

        viewer = "pdfjs-2.7.570-dist/web/viewer.html"
        file = "nd2295.pdf"
        PDFJS = f"file:///{viewer}".replace('\\', '/')
        PDF = f"file:///{file}".replace('\\', '/')
        url = QtCore.QUrl.fromUserInput(f"{PDFJS}?file={PDF}")

        self.view = QtWebEngineWidgets.QWebEngineView()
        self.view.resize(600, 800)
        self.view.load(url)
        self.view.show()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    viewPdf = ShowPdf()
    sys.exit(app.exec_())
```

What is the expected behavior? (add screenshot)
![Capture d’écran 2021-04-28 171225](https://user-images.githubusercontent.com/84353843/118564622-a8a25b80-b73e-11eb-9a1a-d116243a44d4.png)

What went wrong? (add screenshot)
![Capture d’écran 2021-04-28 170918](https://user-images.githubusercontent.com/84353843/118564669-b8ba3b00-b73e-11eb-8a48-e70f51788843.png)
![Capture d’écran 2021-04-28 171014](https://user-images.githubusercontent.com/84353843/118564672-ba83fe80-b73e-11eb-8c67-0253f77e9e52.png)
![Capture d’écran 2021-04-28 171112](https://user-images.githubusercontent.com/84353843/118564686-c243a300-b73e-11eb-9b12-56f08cd47a62.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: PySide2.QWebEngineView
> Operating system and its version: Windows10, Qt for Python version 5.15.0 (PySide 2) et Python 3.7.8

Unfortunately that's not an environment that we can realistically support, since the PDF.js library is written primarily for *browsers*; please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> Steps to reproduce the problem:
>     1. Run Python App

In addition to the above, please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by cetinsert** [comment]
Just tested it in browsers with PDF.js using different scale values. All rendered without flaws.
