### ISSUE TITLE
suboptimal .textLayer > span element positions since 2.8.335

### ISSUE THREAD

**Issue by cetinsert** [mozilla/pdf.js#13396]
Attach (recommended) or Link to PDF file here: https://github.com/tesseract-ocr/tesseract/files/947838/2.pdf

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `2.8.335`, or later
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Render the above document with PDF.js stable and beta
2. Highlight the text layer sub elements

What is the expected behavior? (add screenshot)

See `2.7.570`.

What went wrong? (add screenshot)

See `2.8.335`.

| `2.7.570` ✅ <br> `2.6.347` ✅ | difference | `2.8.335` ❌ |
| ----- | ----- | ----- |
| ![image](https://user-images.githubusercontent.com/27027/118619870-f0d58280-b7ff-11eb-8513-9cd4856a007f.png) | ![image](https://user-images.githubusercontent.com/27027/118620860-da7bf680-b800-11eb-8907-504ade234ffa.png) | ![image](https://user-images.githubusercontent.com/27027/118620077-237f7b00-b800-11eb-8a9b-1829c5b0a635.png) |

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by Snuffleupagus** [comment]
This is the result of PR #12896, which is an *overall* improvement for most documents (and some movement was thus deemed expected/acceptable).

**Comment by cetinsert** [comment]
Only reported here because I thought it related to a different issue. Nothing major for my use of PDF.js. Feel free to close if no one is likely to act on this.

**Comment by timvandermeij** [comment]
Indeed, this should be fine as-is for now, especially since the movement is quite small. Thanks!
