### ISSUE TITLE
Some PDF documents cannot be viewed correctly

### ISSUE THREAD

**Issue by ColcerP** [mozilla/pdf.js#13397]
Attach (recommended) or Link to PDF file here: https://dgfilesanywhere.blob.core.windows.net/public/issues/0085D801.PDF

Configuration:
- Web browser and its version: Google Chrome Version 90.0.4430.212 (Official Build) (64-bit); Microsoft Edge
Version 90.0.818.62 (Official build) (64-bit) **[others as well]**
- Operating system and its version: Windows 10 Pro 64-bit (10.0, Build 18363) **[not only]**
- PDF.js version: pdfjsVersion = '2.1.266'; pdfjsBuild = '81f5835c'; **[does reproduce with the latest version as well]**
- Is a browser extension: No, the pdfjs is integrated in a web application

Steps to reproduce the problem:
1. Open the PDF provided above with the pdf js viewer and you will see a black rectangle over it.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/6659895/118629263-1a79b400-b7d6-11eb-96ac-ff5af26aad83.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6659895/118629182-046bf380-b7d6-11eb-8f89-a7a4fa2b5aad.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): It is not hosted yet. If required, I can host it somewhere.

**Mention: This is not the only file we have that is not displayed correctly. Some of them can be viewed without any issues in Acrobat Reader but not using the pdf js viewer.**

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.9.304` (tested using https://github.com/mozilla/pdf.js#online-demo) in both Firefox Nightly 90 and Google Chrome Beta `91.0.4472.57`.

> PDF.js version: pdfjsVersion = '2.1.266'; pdfjsBuild = '81f5835c'; **[does reproduce with the latest version as well]**

Please note that *only* the versions listed at https://mozilla.github.io/pdf.js/getting_started/#download are supported. Furthermore, it's not clear which *exact* version number "the latest version" refers to above.

**Comment by ColcerP** [comment]
I checked it right now and you're right, this one does work from the online demo link  https://github.com/mozilla/pdf.js#online-demo. I have another PDF file which doens't work in the demo viewer, unfortunatelly I cannot share the document because it contains sensitive data. I've made some print screens and try to blur the sensitive data for you to check the difference
This is the Adobe reader display:
![image](https://user-images.githubusercontent.com/6659895/118643116-d04bff00-b7e4-11eb-90e2-f84d2f5a6cab.png)
And this is the PDF js viewer display:
![image](https://user-images.githubusercontent.com/6659895/118643206-ea85dd00-b7e4-11eb-9346-fb47ec092c0d.png)

**Comment by Snuffleupagus** [comment]
> I have another PDF file which doens't work in the demo viewer, unfortunatelly I cannot share the document because it contains sensitive data. I've made some print screens and try to blur the sensitive data for you to check the difference

Please note that it simply *impossible* to do any meaningful debugging/testing with nothing more than a screen-shot, and that we unfortunately cannot help unless the PDF document is provided.

If you're able to find another document which reproduces the problem, or if you can redact the original document such that it can be shared, please then open a new issue for this problem.
(As mentioned in the *first* paragraph of https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, there should only be one problem reported per issue.)

---

Given that the problem reported https://github.com/mozilla/pdf.js/issues/13397#issue-894187391 has already been fixed, this issue should be closed.
