### ISSUE TITLE
Invalid PDF Structure : is there the way how to use file that has no extension?

### ISSUE THREAD

**Issue by pojjkko** [mozilla/pdf.js#13406]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 
- Operating system and its version: Linux
- PDF.js version: 2.7.570
- Is a browser extension: all browsers

Steps to reproduce the problem:
1. viewer.js accesses the file which has no extension(ex. has extension : file.pdf, no extension : file )
2. when rendering is completed, pdf.js displays error message : Invalid PDF Structure.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Accessing the file without no extension is possible in Windows.
However in Linux, maybe it seems to be not able to recognize the file which has no extension.
I want to use pdfjs in Linux with no extension file, is there the way about that? is there any references? or is it impossible?

**Comment by pojjkko** [comment]
Thank you for your reply.

Attach (recommended) or Link to PDF file here: [file.pdf](https://github.com/mozilla/pdf.js/files/6513984/file.pdf)

When I use this file's name 'file.pdf', it activates normally.
But if I use this file's name 'file'(without the file extension), it occurs error.
![error](https://user-images.githubusercontent.com/68976990/118942944-260fdb00-b98e-11eb-99f1-171a97f412d0.png)

What do I need to give more information about this error?

**Comment by Snuffleupagus** [comment]
> But if I use this file's name 'file'(without the file extension), it occurs error.

I've downloaded the file, and removed the extension, and then opened it (using drag-and-drop) with https://github.com/mozilla/pdf.js#online-demo without any problems whatsoever (on Windows I might add).
Hence it's *not* the PDF.js library that the culprit here, but more likely e.g. your operating system that *somehow* corrupts the file data and that's unfortunately not something that we can debug and/or fix here.

**Comment by calixteman** [comment]
No problem for me too on linux (debian).
Either the file is corrupted or you expect that pdf.js will append a ".pdf" at the end of the filename... Anyway it isn't a pdf.js issue.
Please reopen if you are able to provide better informations.
