### ISSUE TITLE
Annotation layer in shadow DOM

### ISSUE THREAD

**Issue by cetinsert** [mozilla/pdf.js#13405]
Stating something I have encountered in testing. The fixes mentioned at the end do not cover all cases.

---

# 1
The `document.get*` (`document.query*`) methods used in annotation layer radio button selection switch logic work fine in this configuration.
```html
  <html>
    ⋱
      <#light-ancestor>
        ⋱
          <section class="⋯ radioButton" ⋯>
            <input name=a ⋯>
      <#light-ancestor>
        ⋱
          <section class="⋯ radioButton" ⋯>
            <input name=a ⋯>
```

# 2

They do not work if shadow DOM is involved:

```html
  <html>
    ⋱
      #shadow-root
        ⋱
          <#ancestor>
            <section class="⋯ radioButton" ⋯>
              <input name=a ⋯>
            <section class="⋯ radioButton" ⋯>
              <input name=a ⋯>
``` 

For the above case, an incomplete improvement can be gained by scoping down from `document` to `input` (`event.target`) elements' closest not-parent not-section ancestors (`.parentElement.closest(:not(section))`) or grandparents `.parentElement.parentElement` as the end of this comment demonstrates.

# 3

I have not attacked the more involved case demonstrated below. Any suggestions, web standards / MDN references for the below are welcome and the desired output of this issue.

```html
  <html>
    ⋱
      #shadow-root
        ⋱
          <#ancestor>
            <section class="⋯ radioButton" ⋯>
              <input name=a ⋯>
      ⋮
      #shadow-root
        ⋱
          <#ancestor>
            <section class="⋯ radioButton" ⋯>
              <input name=a ⋯>
``` 

I am thinking of replacing `document` with an object that can query across all related (say of the same PDF file) `#shadow-root`s while maintaining API for `document.get*` (`document.query*`) functions. Is there a standard or anything else that I should be aware of for creating/maintaining such a selectively shadow-piercing `document`-like object?

---

The following 3 calls to `document.getElementsByName` effectively caused **all** clicked/tapped **radio buttons** to **stay checked** because finding the ones that are not the target of the current click/tap to clear would fail.

For the 2. case illustrated above, replacing `document.getElementsByName(⋯)` in

https://github.com/mozilla/pdf.js/blob/17e9cfcd2a86bf6b72faf0ac3ac96fe4224731ba/src/display/annotation_layer.js#L976
https://github.com/mozilla/pdf.js/blob/17e9cfcd2a86bf6b72faf0ac3ac96fe4224731ba/src/display/annotation_layer.js#L1050
https://github.com/mozilla/pdf.js/blob/17e9cfcd2a86bf6b72faf0ac3ac96fe4224731ba/src/display/annotation_layer.js#L1064

with
```js
event.target.parentElement.closest(":not(section)").querySelectorAll(`[name="${event.target.name}"]`)
```
helped restore the expected behavior. This is something I maintain patches for targeting specific, frozen-in-time version ranges of `pdf.min.js` from my CDN.

---
---
---

---

not encountered in testing up to `2.8.335`:
https://github.com/mozilla/pdf.js/blob/17e9cfcd2a86bf6b72faf0ac3ac96fe4224731ba/src/display/annotation_layer.js#L676

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

*Unfortunately it's quite difficult to, in its current form, see this as an actionable/valid bug report without a lot more/clearer context.*

Furthermore, please keep in mind that the viewer (and e.g. the AnnotationLayer functionality) was written *primarily* for the Firefox use-case, hence it's not entirely clear how/why shadow DOM is relevant here.
Please also note that it's somewhat unlikely that we'd want to *unnecessarily* complicate the PDF.js code for a use-case (e.g. shadow DOM) that doesn't really matter for the Firefox PDF Viewer.

**Comment by cetinsert** [comment]
@Snuffleupagus - exactly the kind of responses I was expecting : )

I know the code base of PDF.js should be kept simple and the fixes for the 2. case mentioned above do not cover all cases / are not worthy of a pull request.

The reason I report this issue is because PDF.js has a very well thought-out API that does just work even outside the restrictions for which it is primarily designed. Once I have a final suggestion that covers all 3 cases, I would like to report it here and hear the opinions of the other developers. Rest assured it will be surgically minimal to add no bloat for *a case* 1) you guys do not really care at Firefox but 2) that will still broaden the scope of applicability of the library.

**Comment by Snuffleupagus** [comment]
> Rest assured it will be surgically minimal to add no bloat for _a case_

We also want to avoid unnecessary *run-time overhead*, since something like the snippet in https://github.com/mozilla/pdf.js/issues/13405#issue-896209022 requires a lot more parsing (by the browser) to find the relevant elements:

> ```js
> event.target.parentElement.closest(":not(section)").querySelectorAll(`[name="${event.target.name}"]`)
> ```
