### ISSUE TITLE
Importing `es5 build` from Typescript seems to use the "standard" build anyway

### ISSUE THREAD

**Issue by Chrisp1tv** [mozilla/pdf.js#13400]
Hello! Im' facing an issue while trying to require pdfjs-dist from my Node application to parse the text of PDF files.
Does anyone have any suggestion about this? I'm maybe doing something wrong?

### Configuration:
- Web browser and its version: Node 14.17.0 (Electron app - version 11.2.3)
- Operating system and its version: Mac OS X 10.15.17
- PDF.js version: 2.7.570 (pdfjs-dist)
- Is a browser extension: No

Steps to reproduce the problem:
I have the following Typescript code:
```typescript
import { getDocument } from 'pdfjs-dist/es5/build/pdf' // <- note I'm using es5 build as suggested by the error

export async function countInPDF(
  documentPath: string,
  wordsToCount: string[],
): Promise<Record<string, number>> {
  const pdf = await getDocument(documentPath).promise
  // ...
}
```

### What is the expected behavior?
No error when requiring PDFJS, and use the `es5` build instead of the standard one when requiring `es5/build/pdf`

### What went wrong?
When requiring `pdfjs-dist/es5/build/pdf`, it seems that the used version is not the `es5` one, as I'm getting this error:
` The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. ReadableStream); please use an es5-build instead.`

I also tried to set the `workerSrc` this way, but it doesn't have any effect no matter the value I use:
```typescript
GlobalWorkerOptions.workerSrc = '...'
```

While investigating, I noticed that changing the `main` field from the `package.json` of pdfjs from `"main": "build/pdf.js"` to `"main":"es5/build/pdf.js"` "resolves" the issue.  Not a solution nor a viable workaround obviously, but if it can help in the investigations...

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Chrisp1tv** [comment]
Hello, sorry for this.
I created this repository: https://github.com/Chrisp1tv/pdfjs-node-example

- Clone it, run `npm install`, and then `npm start`.
- You'll get the error I mentioned.
