### ISSUE TITLE
Cannot set property 'textContent' 'onclick'

### ISSUE THREAD

**Issue by shaaban112** [mozilla/pdf.js#13407]
Uncaught TypeError
For "onclick" property, it's worked before but after the new addition, not worked anymore

// Get Slider Items | Array.from [ES6 Feature]
var sliderImages = Array.from(document.querySelectorAll('.slider-container img'));

// get Number of Slides
    var slidersCount =sliderImages.length;

// Set Current Slide
    var currentSlide = 1;

//slide Number Element
var slideNumberElement = document.getElementById("slide-number");
//previous And Next Button

    var nextButton = document.getElementById(Next);
    var prevButton = document.getElementById(prev);

    // Handle Click on Previous and Next Buttons
    nextButton.onclick = nextSlide;
    prevButton.onclick = prevSlide;

 
//creat  Main Ul Element
    var paginataionElement = document.createElement('ul');

// set ID ON Created Element
    paginataionElement.setAttribute("id" , "pagination-ul");

// creat List Items Based On Slides Count

for( i =1 ; i<=slidersCount ; i++){

    // creat The LI
    var paginataionItems = document.createElement('li');

    // set custom Attribute
    paginataionElement.setAttribute("data-index" ,i);

    // set item content
    paginataionItems.appendChild(document.createTextNode(i));

    //Append Items to The Main Ul List
    paginataionElement.appendChild(paginataionItems);

}

 // Add The Created Ul Element To The Page

 document.getElementById("indicators").appendChild(paginataionElement);

 // Get The New Created Ul

 var paginationCreatedUL = document.getElementById('pagination-ul');
 
 // Tigger The Checker 
 
 theChecker();

// next slide
 function nextSlide(){
     console.log('Next');
 }
 // previous slide
 function prevSlide(){
     console.log('previous');
 }

// creat The Checker Function

function theChecker () {

    slideNumberElement.textContent = 'Slide #' + (currentSlide) + 'for' + (slidersCount);

    // Set Active Class On Current Slide
    sliderImages[0].classList.add('active');
}

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue isn't actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
