### ISSUE TITLE
Link text does not align correctly in custom rotation (e.g. flipped text, 45 degrees)

### ISSUE THREAD

**Issue by roneytham-ideagen** [mozilla/pdf.js#13414]
Attach (recommended) or Link to PDF file here: [Rotation-test.pdf](https://github.com/mozilla/pdf.js/files/6519949/Rotation-test.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 90.0.4430.212
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:
1. Upload Rotation-test.pdf to demo site: https://mozilla.github.io/pdf.js/web/viewer.html
2. Hover to link texts that are rotated 45 degrees or flipped.
3. Notice that the highlight is not aligned correctly with the link text.

What is the expected behavior? (add screenshot)
The highlight should align correctly on top of the link text

What went wrong? (add screenshot)
The highlight is not aligned as expected
![image](https://user-images.githubusercontent.com/45581023/119080492-c61c4180-ba2c-11eb-80fb-6c3e5d0c533c.png)

**Comment by Snuffleupagus** [comment]
I get the same "broken" behaviour even in Adobe Reader (i.e. the PDF reference implementation) as well, hence this isn't really a bug in the PDF.js library.
Furthermore, in PDFium (in Google Chrome), the rotated LinkAnnotation is also wrong and the flipped LinkAnnotation occupies a much too large area; all-in-all this really doesn't look like the PDF.js library is at fault here. 

> PDF.js version: 2.5.207

Please note that that version is no longer supported, please find the current releases at https://mozilla.github.io/pdf.js/getting_started/#download
