### ISSUE TITLE
Blurred images

### ISSUE THREAD

**Issue by marcusps** [mozilla/pdf.js#1344]
PDF.js displays blurry plots in PDF documents, e.g.

http://arxiv.org/pdf/1202.5344v1.pdf

When viewed in Chrome or Adobe Acrobat all the plots show sharp-edged squares. When viewed in Preview or PDF.js, all the squares show as blurry pixelated blobs.

**Comment by Rob--W** [comment]
Remark: The dots have disappeared in some cases. And while working on something else, I discovered that the Matrix of the tiling pattern has 0 and 0 for the x and y scale, respectively.

![page2](https://cloud.githubusercontent.com/assets/1365071/10263459/06cee8d8-69f0-11e5-9171-f9c59674db68.png)

**Comment by SamyCookie** [comment]
Still blurry plots with Firefox 62 and PDF.js: 2.0.625

**Comment by SamyCookie** [comment]
Still blurry plots with Firefox 66.0.1 and PDF.js: 2.2.107.
However, I have not the `TilingType` log anymore, so maybe it is not a related to a tiling type bug, but more to this kind of issue #7838 ?
