### ISSUE TITLE
Missing PDF Annotations when rendered to PdfJs

### ISSUE THREAD

**Issue by roneytham-ideagen** [mozilla/pdf.js#13447]
Attach (recommended) or Link to PDF file here: 
[A Sample PDF Clean 0 degree with all annotations-original-rotated.pdf](https://github.com/mozilla/pdf.js/files/6551789/A.Sample.PDF.Clean.0.degree.with.all.annotations-original-rotated.pdf)

Configuration:
- Web browser and its version: all browsers, tested with Chrome and Firefox latest versions.
- Operating system and its version: tested in Windows 10
- PDF.js version: current (online version)

Steps to reproduce the problem:
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the file above
3. Notice that several annotations such as arrow, freehand & polyline are missing (compared to Acrobat Reader)
![image](https://user-images.githubusercontent.com/45581023/119781014-11d35d00-befd-11eb-8daa-64f15374cf5b.png)

What is the expected behavior?
- Should display all annotations accordingly to Acrobat Reader

What went wrong? 
- Several annotations are missing such as arrow, freehand & polyline
- Opacity property is not supported and cannot be retrieved via getAnnotations

**Comment by Snuffleupagus** [comment]
This looks, for all intents and purposes, like another duplicate of issue #6810.

**Comment by roneytham-ideagen** [comment]
Alright got it, and we was wondering when will these changes release so that we can update?
https://github.com/mozilla/pdf.js/pull/13301
https://github.com/mozilla/pdf.js/pull/13305
https://github.com/mozilla/pdf.js/pull/13033

**Comment by timvandermeij** [comment]
The pull request above fixed most remaining issues here with the exception of the vertical strikeout annotations and the custom line endings. However, given that all the rest renders like in Adobe Reader, the reference implementation, now that's a minor issue that can be picked up later if need be.

**Comment by roneytham-ideagen** [comment]
@timvandermeij Thanks for the input Tim.

I upgraded to version 2.9.359, everything works well, it just that there are a few missing arrow heads, are those the custom line endings you mentioned above?
![image](https://user-images.githubusercontent.com/45581023/120154326-58d59100-c222-11eb-86f9-416da8136344.png)

Anyhow, thanks for getting these annotations works 👍

**Comment by timvandermeij** [comment]
Indeed, the arrow heads still remain to be fixed here.

**Comment by Snuffleupagus** [comment]
The best, and most correct, solution would be to only add annotations to PDF documents by using *proper* PDF tools that correctly generate an *appearance stream* for all annotations, since that's really the only way to ensure that all PDF viewers will render the annotations as intended.

(I cannot find a link right now, but I seem to recall that in version `2.0` of the PDF specification it'll be explicitly required for all annotations to have an appearance stream.)

**Comment by roneytham-ideagen** [comment]
Thanks for the input guys 👍
