### ISSUE TITLE
Return type signature of getPageIndex is incorrect

### ISSUE THREAD

**Issue by mandel59** [mozilla/pdf.js#13449]
https://github.com/mozilla/pdf.js/blob/0df1a5661958df0c4ed2f73b0f3266d825c5c280/src/display/api.js#L710-L719
The return type signature `@returns {Promise<{num: number, gen: number}>}` is mismatched with its definition. (should be `@returns {Promise<number>}`)

**Comment by shrayan08** [comment]
I am a complete beginner in open source can anyone please guide me to contribute... I know basics of javascript but I want to contribute for Mozilla ... Please someone help me
