### ISSUE TITLE
Using NextJS and get Error: Cannot find module 'webpack/lib/SingleEntryPlugin'

### ISSUE THREAD

**Issue by Braweria** [mozilla/pdf.js#13444]
Attach (recommended) or Link to PDF file here: --

Configuration:
- Web browser and its version: Latest Chrome
- Operating system and its version: Windows 10
- PDF.js version: `^2.7.570`
- Is a browser extension: No

Steps to reproduce the problem:
1. `yarn create next-app`
2. Inside the `index.js` add the following code
```js
import styles from "../styles/Home.module.css";
const pdfjsLib = require("pdfjs-dist");
import "pdfjs-dist/webpack";

const pdfPath = "../lib/Webinar.pdf"; // (any PDF)

export default function Home() {
  pdfjsLib.GlobalWorkerOptions.workerSrc =
    "../../build/webpack/pdf.worker.bundle.js";

  //const loadingTask = pdfjsLib.getDocument(pdfPath);
  //console.log(loadingTask);

  return (
    <div className={styles.container}>
      <h1>PDF Testing</h1>
    </div>
  );
}
```

Get the error that it cannot find the module (error is below). I was following this https://github.com/mozilla/pdf.js/tree/master/examples/webpack example, since NextJS is using Webpack. And inside the `main.js` file I copied the code from: https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js up until that point you see above, and the error happened.  

I installed `worker-loader`. Before installing it, I got the error message `Setting up fake worker`, as it was described the the doc as well.

What is the expected behavior? (add screenshot)
To just work, I am testing the Library, so I expect it to not throw an error there.

What went wrong? (add screenshot)
The error happened, it cannot find `SingleEntryPlugin`.

```
react_devtools_backend.js:2560 ./node_modules/worker-loader/dist/cjs.js?esModule=false&filename=[name].js!./node_modules/pdfjs-dist/build/pdf.worker.js
Error: Cannot find module 'webpack/lib/SingleEntryPlugin'
Require stack:
- C:\Users\XXX\Desktop\pdf-test\node_modules\worker-loader\dist\index.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\worker-loader\dist\cjs.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\compiled\webpack\bundle5.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\compiled\webpack\webpack.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\next-server\server\config-utils-worker.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\next-server\server\config-utils.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\next-server\server\config.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\server\next.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\server\lib\start-server.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\cli\next-dev.js
- C:\Users\XXX\Desktop\pdf-test\node_modules\next\dist\bin\next
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): --

**Comment by Snuffleupagus** [comment]
Unfortunately the PDF.js contributors cannot really provide support for various frameworks/build-tools, such as e.g. "React", "NextJS", and "yarn".

Please note that the example in https://github.com/mozilla/pdf.js/tree/master/examples/webpack *should* work when run as-is, without any other code on top of it.
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
