### ISSUE TITLE
Request: Use available space to separate icons in horizontal menu bar in viewer.html (for touch devices)

### ISSUE THREAD

**Issue by kaytuca** [mozilla/pdf.js#13467]
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: IPad Safari and IPad Chrome 
- Operating system and its version:  iOS 14.5.1
- PDF.js version:  2.8.335
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a pdf in viewer.html on Ipad with only print and download buttons configured to show (rest hidden via css)
2. The download and print buttons are very close together and especially hard to hit exactly with one's fingertip on an iPad given they are set far to the right. Lots of apparent space is available that maybe might allow more separation of the visible icons.

What is the expected behavior? (add screenshot)
![image0](https://user-images.githubusercontent.com/76606355/120125510-fa4edb00-c16d-11eb-9296-b438c4c26b08.jpg)
It would be nice if the space marked with green also could be used, rather than the two visible icons being so close together (and near the edge) as marked in red. Very hard on small devices to target the icon exactly with one's fingertip.

What went wrong? (add screenshot)
Nothing went wrong. Just a suggestion to improve usability on touch devices.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Open a pdf in viewer.html on Ipad with only print and download buttons configured to show (rest hidden via css)
> 
> The download and print buttons are very close together and especially hard to hit exactly with one's fingertip on an iPad given they are set far to the right. Lots of apparent space is available that maybe might allow more separation of the visible icons.

Please keep in mind that the demo viewer was/is not written specifically for touch interfaces, since it's primarily the UI for the built-in PDF Viewer in Firefox; hence closing this issue as WONTFIX.

Please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
