### ISSUE TITLE
Hidden menu icons show in viewer.html as browser window is made narrower & then hide again as made even narrower

### ISSUE THREAD

**Issue by kaytuca** [mozilla/pdf.js#13470]
Two of 3 hidden toolbar Buttons display as the browser window narrows, and then they disappear again as the browser window keeps narrowing. 

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Happens in all browsers I tried: 
      Chrome Version 91.0.4472.77 (Official Build) (64-bit)
      FireFox Version 88.0.1 (64-bit) 
      Edge Version 91.0.864.37 (Official build) (64-bit)

- Operating system and its version:  Win 10 21H1 OS Build 19043.1023
- PDF.js version:  2.8.335 Legacy, using viewer.html
- Is a browser extension: No

Steps to reproduce the problem:

1. Open a pdf in viewer.html where presentationMode, openFile and the bookmark toolbar buttons are hidden via "display: none" in viewer.css : 
.toolbarButton.presentationMode, 
.toolbarButton.openFile,
.toolbarButton.bookmark {
    display: none;
}

2. When the browser is "wider" (normal viewing kind of mode on a monitor in landscape mode), the buttons cannot be seen. 

3. Grab either side of the browser window and drag it to make the browser narrower.   As the browser narrows, two of the 3 hidden toolbar buttons display.

5. As the browser narrows further, the two "appearing" buttons  disappear and do not display again.

What is the expected behavior? (add screenshot)
The expected behavior is that buttons styled not to display won't display.

What went wrong? (add screenshot)

Three screenshots are provided below: 
-- wider (normal landscape viewing width), 
-- narrowing (where buttons appear)
-- even narrower (where buttons disappear again). 
I set a fixed width black background behind the browser window that is narrowing, and each screenshot has this same black background width, so you can get a feel for how much narrower the window has to become for the hidden toolbar buttons to show. 
I underlined in red the buttons on the toolbar on the right hand side that start properly displayed/hidden, hen gain two hidden buttons, and then end properly displayed/hidden again.

Screenshot 1: Wider mode (the hidden buttons do not show).
![wide shot -- normal use mode](https://user-images.githubusercontent.com/76606355/120138004-67706980-c18a-11eb-95d7-20d79a905db3.jpg)

Screenshot 2:  Narrowing: 2 of 3 hidden buttons show as browser window narrows.
![medium narrow shot](https://user-images.githubusercontent.com/76606355/120138014-6b9c8700-c18a-11eb-8fe3-21d867d1dcaa.jpg)

Screenshot 3. Narrows more: the 2 "appearing" buttons hide again as the browser window narrows further.
![narrowest shot](https://user-images.githubusercontent.com/76606355/120138024-71926800-c18a-11eb-9602-c2085ecf9b41.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://kkcomcon.com/libraries/pdfjs/web/viewerkk.html?file=../../../../doc/KPQA.pdf#page=1

**Comment by Snuffleupagus** [comment]
>      .toolbarButton.presentationMode,
>      .toolbarButton.openFile,
>      .toolbarButton.bookmark {
>        display: none;
>      }
> [...]
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> https://kkcomcon.com/libraries/pdfjs/web/viewerkk.html?file=../../../../doc/KPQA.pdf#page=1

Using that link, I cannot re-produce the issue described in this issue.
However, in general, it's possible that the `display: none;` line *could* get overridden by something with a higher specificity and the one guaranteed way of fixing such problems (while generally not recommended) is to append `!important` to that line; see also https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Closing as answered, since this looks like a more general CSS question rather than a PDF.js bug.
