### ISSUE TITLE
help，Some ie11 are shown in white and do not display content.

### ISSUE THREAD

**Issue by ZsxCarl** [mozilla/pdf.js#13483]
Only a part of the computer appears to be blank, and there is no error. So I ask for your help.
![image](https://user-images.githubusercontent.com/84709426/120602423-9550f900-c47d-11eb-8b4f-f3a1860ca275.png)

**Comment by Snuffleupagus** [comment]
As clearly mentioned in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is no longer supported in the PDF.js library.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
