### ISSUE TITLE
Is it possible to hide or obfuscate the source PDF file URL?

### ISSUE THREAD

**Issue by fishfree** [mozilla/pdf.js#13481]
Because I don't want people to download the PDF file by URL directly.

**Comment by Snuffleupagus** [comment]
White that *may* be possible, it will however not stop e.g. a tech-savvy user.
All-in-all, this isn't the sort of thing that we'll support; please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---
*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
