### ISSUE TITLE
Pdf Refreshing in VS Code when GPU is active

### ISSUE THREAD

**Issue by Balrrach** [mozilla/pdf.js#13507]
#### Configuration:
- Web browser and its version: Last one(but it isn't relevant)
- Operating system and its version: Windows 10 [Version 10.0.19042 compilation 19042]
- PDF.js version: Last one available in vscode-pdf and LaTeX workshop
- Is a browser extension: No

#### Steps to reproduce the problem:
1. Download VS Code
2. Launch VS Code
2. Install any of the available pdf viewers on the extensions market
3. Open any pdf in VS Code
4. Open other app in full screen
5. Switch between the two

####  What is the expected behavior? (add screenshot)
Nothing should happen but pdf keeps reloading everytime you switch to VS Code from any other app in fullscreen.

####  What went wrong?
Pdf preview keeps refreshing/flickering when changing(Alt-Tab) from a different app in fullscreen to VS Code. When the app one comes from isn't in fullscreen there is no issue. When VS Code is executed with parameter --disable-gpu there is no problem either. Can't add a screenshot is a visual effect(pdf image flickers)

**Comment by Snuffleupagus** [comment]
> PDF.js version: Last one available in vscode-pdf and LaTeX workshop

While those projects may (perhaps) use the PDF.js library internally, they are *not* actually connected with this project and unfortunately we thus cannot provide support and/or assistance for them *here*. Please contact those projects directly for help instead!

**Comment by Balrrach** [comment]
Ok. Thanks!
