### ISSUE TITLE
how to rotate and stay on the page

### ISSUE THREAD

**Issue by yinhowIdeagen** [mozilla/pdf.js#13519]
It will stay on page 1 after rotate even though at middle of page 1 on pdf demo site(https://mozilla.github.io/pdf.js/web/viewer.html).

May I know how to do it?

Before rotate:
![image](https://user-images.githubusercontent.com/85598498/121286899-193e3180-c913-11eb-8dc7-021921162a1e.png)
After rotate:
![image](https://user-images.githubusercontent.com/85598498/121286940-2bb86b00-c913-11eb-804b-a71f1681d72f.png)

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/blob/ae531e5e23d86ee056f053034853556880c1db4e/web/base_viewer.js#L379-L420 and https://github.com/mozilla/pdf.js/blob/ae531e5e23d86ee056f053034853556880c1db4e/web/app.js#L2650-L2656
