### ISSUE TITLE
Autoprefixer warnings about the partially supported `align-items: start;` CSS rule

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#13518]
After PR #13479 landed, building the PDF.js library now produces warnings from the Autoprefixer package.
For example, with `gulp generic` the following is printed in the console:
```
[21:33:58] gulp-postcss: viewer.css
autoprefixer: C:\Users\Jonas\Git\pdf.js\viewer.css:383:3: start value has mixed support, consider using flex-start instead
autoprefixer: C:\Users\Jonas\Git\pdf.js\viewer.css:393:3: start value has mixed support, consider using flex-start instead
```
with those warnings originating at
 - https://github.com/mozilla/pdf.js/blob/2a6111044e0ad1ee70d6430b073ff39843f7b9d9/web/xfa_layer_builder.css#L121
 - https://github.com/mozilla/pdf.js/blob/2a6111044e0ad1ee70d6430b073ff39843f7b9d9/web/xfa_layer_builder.css#L131

According to MDN, please see https://developer.mozilla.org/en-US/docs/Web/CSS/align-items#browser_compatibility, only Firefox supports `align-items: start;` currently.

@calixteman Can we make the change suggested by Autoprefixer (in which case I'd happily submit a patch), or would that break the layout of XFA documents (in which case I'm guessing this is wontfix)?

Or, could it *possibly* make sense to at least amend the code with the following in those two cases?
```css
align-items: flex-start;
align-items: start;
```

**Comment by calixteman** [comment]
I missed that... Could we add this css lint to `gulp lint` ?
Anyway, after reading the doc, I think replacing `start` by `flex-start` is fine.

**Comment by Snuffleupagus** [comment]
> Could we add this css lint to `gulp lint` ?

Please note this warning only happens during *building*, and the `gulp lint` simply checks the source files as-is (since building as well would be quite a bit slower than it already is).
Furthermore, while there is a PostCSS plugin for [treating warnings as errors](https://github.com/postcss/postcss#treat-warnings-as-errors) it unfortunately (in my testing) doesn't seem to work with the `gulp`-versions of the PostCSS package that we use.

Given the above, I'm just going to fix the issue and defer the linting part for now (this is also the *first* time we've seen such a warning).
