### ISSUE TITLE
Fortify XSS issue

### ISSUE THREAD

**Issue by skana75** [mozilla/pdf.js#13533]
Attach (recommended) or Link to PDF file here:

Configuration:
it is an asp.net, C# web application. Trying to scan security vulnerabilities using fortify.

Steps to reproduce the problem:
This is the issue that fortify scan displayed :
"The method GetDocument() in RendDoc.ashx.cs sends unvalidated data to a web browser on line 160, which can result in the browser executing malicious code."
The below is C# code, it shows issues in 3 lines that are prefixed with **

 public void GetDocument()
        {
            ServiceClient dm = null;
            DocIntService.DocmanServiceSoapClient InternalService = null;

            //Use Internal/External service based on if using Windows Authentication
            if (HttpContext.Current.Request.IsAuthenticated && HttpContext.Current.User.Identity is WindowsIdentity)
                InternalService = new DocIntService.DocmanServiceSoapClient("DocManNetTcpEndpoint");
            else
                dm = new ServiceClient("DocManwsHttpEndpoint");
            //ServiceClient dm = new ServiceClient("DocManwsHttpEndpoint");

            try
            {
                byte[] DocArray;
                //DocArray = dm == null ? InternalService.GetFile(DocId) : dm.GetFile(DocId);
                if (dm == null)
                {
                    //Wrapper for impersonation
                    using (WindowsImpersonationContext cxt = (Thread.CurrentPrincipal.Identity as WindowsIdentity).Impersonate())
                        **DocArray = InternalService.GetFile(DocId);**
                }
                else
                    **DocArray = dm.GetFile(DocId);**

                string fileExt2;
                string strConttenType = null;
                fileExt2 = fileExt;

                strConttenType = GetService.GetContenttype(fileExt2);

                HttpContext.Current.Response.ClearHeaders();
                HttpContext.Current.Response.ClearContent();
                HttpContext.Current.Response.BufferOutput = true;

                HttpContext.Current.Response.ContentType = strConttenType; // "application/msword"; // for PDF type

                HttpContext.Current.Response.AddHeader("Content-Disposition", "inline");
                **HttpContext.Current.Response.BinaryWrite(DocArray);**

                HttpContext.Current.ApplicationInstance.CompleteRequest(); //http://blogs.msdn.com/b/aspnetue/archive/2010/05/25/response-end-response-close-and-how-customer-feedback-helps-us-improve-msdn-documentation.aspx
            }
            catch (FaultException ex)
            {
                ExMgr.Publish(ex);
                dm.Abort();
            }
            catch (Exception ex)
            {
                ExMgr.Publish(ex);
            }
            finally
            {
                if (dm != null)
                {
                    if (dm.State == System.ServiceModel.CommunicationState.Faulted)
                    {
                        dm.Abort();              //Abort() is an ungraceful exit—when called, it immediately aborts all service calls in progress and shuts down the host. Active clients will each get an exception.
                    }
                    else
                    {
                        if (dm.State == CommunicationState.Opened || dm.State == CommunicationState.Opening || dm.State == CommunicationState.Created)
                        {
                            dm.Close();
                        }
                        else
                        {
                            dm.Abort();
                        }
                    }
                }
                if (InternalService != null)
                {
                    if (InternalService.State == System.ServiceModel.CommunicationState.Faulted)
                    {
                        InternalService.Abort();              //Abort() is an ungraceful exit—when called, it immediately aborts all service calls in progress and shuts down the host. Active clients will each get an exception.
                    }
                    else
                    {
                        if (InternalService.State == CommunicationState.Opened || InternalService.State == CommunicationState.Opening || InternalService.State == CommunicationState.Created)
                        {
                            InternalService.Close();
                        }
                        else
                        {
                            InternalService.Abort();
                        }
                    }
                }
            }
        }
2.

PLease let me know solution for removing this issue and code is scanned w/o any issue

**Comment by Snuffleupagus** [comment]
> it is an asp.net, C# web application.

Please note that the PDF.js library is written in *JavaScript*, hence it's quite difficult to understand how your particular case is even relevant *here*.

> Trying to scan security vulnerabilities using fortify.

Note that such tools are known for their many false positives, since the mere presence of a piece of code doesn't automatically imply a vulnerability; note the discussion in old issues such as e.g. #8737 and #9269.

> This is the issue that fortify scan displayed :
> "The method GetDocument() in RendDoc.ashx.cs sends unvalidated data to a web browser on line 160, which can result in the browser executing malicious code."

This sounds exactly like the situation outlined just above, where the tool simply highlights a particular coding-pattern without being "smart" enough to evaluate it properly.
Obviously it must be possible to pass data to the `getDocument` method in the PDF.js API, how else would you actually load/render a PDF document!?

> The below is C# code, it shows issues in 3 lines that are prefixed with **

None of this is code originating in this library, which again is written in JavaScript.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**. isn't actionable/valid.

---

All-in-all, closing as INVALID.
