### ISSUE TITLE
Publish your extension to Microsoft Edge Add-ons website

### ISSUE THREAD

**Issue by sonakshimore** [mozilla/pdf.js#13531]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by Snuffleupagus** [comment]
Please note that as already mentioned in the README, see https://github.com/mozilla/pdf.js#chrome, even the official Chrome extension isn't maintained *directly* in this repository.

Furthermore, please also note that the main development focus is on the Firefox built-in PDF Viewer; hence any *additional* extensions would need to be maintained by a third-party as well.

Closing as WONTFIX.
