### ISSUE TITLE
PDF content is not shown, a message suggesting the usage of Adobe Reader is shown instead

### ISSUE THREAD

**Issue by marco-c** [mozilla/pdf.js#13544]
Attach (recommended) or Link to PDF file here:
First PDF from #13143, [5e70058f-de74-4412-b7ec-0d02124fbd7f.pdf](https://github.com/mozilla/pdf.js/files/6206686/5e70058f-de74-4412-b7ec-0d02124fbd7f.pdf)

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior?
See the actual contents of the PDF

What went wrong?
A message suggesting the usage of Adobe Reader is shown instead of the actual content

**Comment by Snuffleupagus** [comment]
Duplicate of #4282
