### ISSUE TITLE
How to get the base64 images data

### ISSUE THREAD

**Issue by DVGY** [mozilla/pdf.js#13541]
Attach (recommended) or Link to PDF file here:
[PDF](https://pdfhost.io/v/r2Amu6PrF_Microsoft_Word_Document1.pdf)

Configuration:
- Chrome Version 91.0.4472.77 
- OS Name	Microsoft Windows 10 Business
   Version	10.0.19042 Build 19042
- PDF.js version: //mozilla.github.io/pdf.js/build/pdf.js (latest)
- Is a browser extension: No

Steps to reproduce the problem:
1.  I have attached a sample [codesandbox](https://codesandbox.io/s/example-7sjru)
2.  I want to get the image base 64 data so that I later convert to images. But first How to get the base64 data

Note: I know it's not a q n a . I reffered to this thread. Followed this, but this just gives me name of images [stackoverflow thread](https://stackoverflow.com/questions/18680261/extract-images-from-pdf-file-with-javascript#:~:text=onload%20%3D%20function%20webViewerChangeFileReaderOnload(evt),%3D%20files%5B0%5D%3B%20fileReader.)

Can you at least put me in the right direction pls ?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/46158826/121661815-3c5b1380-cac2-11eb-9070-011ddeaee537.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The following unit-test should give you an idea of to access the image data:
https://github.com/mozilla/pdf.js/blob/950dcc7e9fb306c1b5fe621ec79da975f310d7f5/test/unit/api_spec.js#L1615-L1630

**Comment by DVGY** [comment]
@Snuffleupagus Converting `Uint8ClampedArray` to `base64` takes forever. Is there any other method I should look into to convert `Uint8ClampedArray` to image (jpeg) ?
