### ISSUE TITLE
file origin does not match viewer's 

### ISSUE THREAD

**Issue by marufahamed26** [mozilla/pdf.js#13564]
I have 2 foreign URLs to fetch pdf.

1. https://infoabz.com/ebook/uploads/examples.pdf
2. https://ebook.infoabz.com/qazi_anwar/masud_rana/examples.pdf

i am trying by this viewer.html system

`<iframe height="100%" width=100% src='lib/web/viewer.html?file=https://infoabz.com/ebook/uploads/examples.pdf'></iframe>`

`<iframe height="100%" width=100% src='lib/web/viewer.html?file=https://ebook.infoabz.com/qazi_anwar/masud_rana/examples.pdf'></iframe>`

1st one link working perfectly but issues come on 2nd urls.

i added domain on HOSTED_VIEWER_ORIGINS as like this

`HOSTED_VIEWER_ORIGINS = [
"null",
"http://mozilla.github.io", 
"https://mozilla.github.io", 
"http://127.0.0.1:8000", 
"https://infoabz.com", 
"https://ebook.infoabz.com", 
"http://infoabz.com", 
 "http://ebook.infoabz.com"];` 

whats wrong in here

**Comment by Snuffleupagus** [comment]
Please refer to #6916 for additional details; closing as INCOMPLETE since most (if not all) of the information request in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is missing.
