### ISSUE TITLE
Image missing in PDF

### ISSUE THREAD

**Issue by benja-opazo** [mozilla/pdf.js#13561]
Attach (recommended) or Link to PDF file here: [ICEE-B.2017.8192026.pdf](https://github.com/mozilla/pdf.js/files/6651211/ICEE-B.2017.8192026.pdf)

Configuration:
- Web browser and its version:  Firefox 89.0 (64-bit)
- Operating system and its version: Windows 10 Pro Version 21H1
- PDF.js version: I don't know, sorry
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF
2. Figure 1 in page 2 is missing

What is the expected behavior? (add screenshot)
This is how it looks in Edge
![image](https://user-images.githubusercontent.com/40286841/121958287-839b0b80-cd31-11eb-8400-7d9c088d83fa.png)

What went wrong? (add screenshot)
This is how it looks in firefox
![image](https://user-images.githubusercontent.com/40286841/121958359-99a8cc00-cd31-11eb-9d15-b94d5884e03d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by symtalha14** [comment]
Any error logs?

**Comment by benja-opazo** [comment]
I'm sorry, where can I see the error log? I opened the browser console and nothing new appears when I open the PDF

**Comment by brendandahl** [comment]
Yeah, doesn't look like there's any errors in the console. This appears to be yet another issue with how we apply image mask with patterns and how the scaling/transformations interact.
