### ISSUE TITLE
Demo page doesn't work as expected content in IE11

### ISSUE THREAD

**Issue by OlesyaKlochko** [mozilla/pdf.js#13574]
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/22976204/122405902-b71fa500-cf80-11eb-82cb-fbb42d9da2dc.png)

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 10
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  Open https://mozilla.github.io/pdf.js/legacy/web/viewer.html in IE11 

What is the expected behavior? (add screenshot)
Pdf should be available for preview

What went wrong? (add screenshot)
Pdf is not available for preview

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
As clearly mentioned in the FAQ, IE 11 is no longer supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
