### ISSUE TITLE
pdfjsLib not defined, simple question

### ISSUE THREAD

**Issue by travisLilleberg** [mozilla/pdf.js#13578]
Apologies for what might be a simple question, but I've been scouring the docs and the issues and I'm not seeing this very basic issue come up.

I include pdfjs.js as a script in my website:

<img width="843" alt="Screen Shot 2021-06-17 at 12 18 23 PM" src="https://user-images.githubusercontent.com/8809048/122436027-7c107800-cf66-11eb-9dbb-bf24604bff18.png">

But when I try to access pdfjsLib via console, or in a script, it says it's not defined:

<img width="1248" alt="Screen Shot 2021-06-17 at 12 18 36 PM" src="https://user-images.githubusercontent.com/8809048/122436103-8cc0ee00-cf66-11eb-9a92-97cfa51159e8.png">

I tried this line from the examples:
`var pdfjsLib = window['pdfjs-dist/build/pdf'];`

but it didn't do anything.

Am I missing something? I'm not particularly familiar with webpack.

Configuration:
- Chrome, 91.0.4472.101:
- Big Sur 11.1:
- Rails 5.2.6, Sprockets 3.7.2 (though I'm bypassing sprockets currently)

Thank you.

**Comment by Snuffleupagus** [comment]
> I include pdfjs.js as a script in my website:

Please use official releases, see https://mozilla.github.io/pdf.js/getting_started/#download, rather than linking directly to this GitHub repository in your code (since it's not meant to be used as a CDN, and its code changes *very* frequently).

> I tried this line from the examples:
> `var pdfjsLib = window['pdfjs-dist/build/pdf'];`

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
