### ISSUE TITLE
XFA entry allowed for readOnly access fields

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13581]
Attach (recommended) or Link to PDF file here:
[expenseReportDynamic.pdf](https://github.com/mozilla/pdf.js/files/6673403/expenseReportDynamic.pdf)

- Web browser and its version: Firefox 89.0
- Operating system and its version: Windows 10 10.0.19043.1052
- PDF.js version: commit 5d251a3a3e7bfaa8fbfa07f0b7f9901eb3f999d9
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable XFA support
2. Open form

What is the expected behavior? (add screenshot)
Entry (and highlighting) is not allowed
![image](https://user-images.githubusercontent.com/7104454/122484526-c31c5e80-cfa2-11eb-9e88-c5bb7e650ed9.png)

What went wrong? (add screenshot)
Entry into readOnly fields are allowed
![image](https://user-images.githubusercontent.com/7104454/122484720-332ae480-cfa3-11eb-884f-e996da11724d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by marco-c** [comment]
@calixteman did #13595 fix this?

**Comment by marco-c** [comment]
Yes, it's fixed.
