### ISSUE TITLE
XFA Not honoring blank value for choiceList

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13580]
Attach (recommended) or Link to PDF file here:
[expenseReportDynamic.pdf](https://github.com/mozilla/pdf.js/files/6673403/expenseReportDynamic.pdf)

- Web browser and its version: Firefox 89.0
- Operating system and its version: Windows 10 10.0.19043.1052
- PDF.js version: commit 5d251a3a3e7bfaa8fbfa07f0b7f9901eb3f999d9
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable XFA support
2. Open form

What is the expected behavior? (add screenshot)
SmartDoc Client dropdown list (choiceList) should be blank.
![image](https://user-images.githubusercontent.com/7104454/122477162-4c2c9900-cf95-11eb-95f1-0353b08d19fb.png)

What went wrong? (add screenshot)
SmartDoc Client dropdown list (choiceList) defaults to first item/text
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
![image](https://user-images.githubusercontent.com/7104454/122477201-5c447880-cf95-11eb-912c-2e6e0fbd4c0b.png)

**Comment by symtalha14** [comment]
Can you please assign this to me?

**Comment by calixteman** [comment]
Sorry it's already fixed by:
https://github.com/mozilla/pdf.js/commit/1de133a7c90276e9489b2a7756bc7bbbd8fdaeb5

**Comment by symtalha14** [comment]
Ohh, I saw it open

**Comment by calixteman** [comment]
It's because there is bug here too: https://bugzilla.mozilla.org/show_bug.cgi?id=1718241
