### ISSUE TITLE
XFA Geometry exceeds containers

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13584]
Attach (recommended) or Link to PDF file here:
http://education.ohio.gov/getattachment/Topics/Special-Education/Preschool-Special-Education/ETR-Preschool-Planning-Form.pdf.aspx

- Web browser and its version: Firefox 89.0.1
- Operating system and its version: Windows 10 10.0.19043.1052
- PDF.js version: commit 5d251a3a3e7bfaa8fbfa07f0b7f9901eb3f999d9
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable XFA support
2. Open form

What is the expected behavior? (add screenshot)
Shapes stay inside table cells
![image](https://user-images.githubusercontent.com/7104454/122572782-1252a580-d01c-11eb-9d0f-5fed46d6f2fe.png)

What went wrong? (add screenshot)
Shapes fall outside cells (among other issues)
![image](https://user-images.githubusercontent.com/7104454/122572885-2d251a00-d01c-11eb-8863-fa3b9969f0ea.png)

**Comment by calixteman** [comment]
@JDziurlaj, the file isn't accessible: could you attach it to this bug report please ?

**Comment by Snuffleupagus** [comment]
https://web.archive.org/web/20210518165046/http://education.ohio.gov/getattachment/Topics/Special-Education/Preschool-Special-Education/ETR-Preschool-Planning-Form.pdf.aspx

**Comment by calixteman** [comment]
Rectangle dimensions are 100% of the ones from  parent but here the parent has some margins.
So we must take into account the parent margins when generating the svg rectangle.
