### ISSUE TITLE
XFA Only some pages render

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13597]
Attach (recommended) or Link to PDF file here:
http://help.adobe.com/en_US/livecycle/11.0/SampleForms/941/Form.pdf

- Web browser and its version: Firefox 89.0.1
- Operating system and its version: Windows 10 10.0.19043.1052
- PDF.js version: commit bdfcdd6f8326f22c135edfa29a341ea4c558f3d1
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable XFA support
2. Open form

What is the expected behavior? (add screenshot)
Page 3 (of 4) renders
![image](https://user-images.githubusercontent.com/7104454/122686842-622e9980-d1e1-11eb-92ab-86fe488560f2.png)

What went wrong? (add screenshot)
Only 3 pages total render in pdf.js

**Comment by symtalha14** [comment]
Now it is rendering all 4 pages. Close this issue maybe.

**Comment by Snuffleupagus** [comment]
There's overlapping text on the *first* page, possibly related to all of the font warnings:
```
Warning: XFA - Cannot find the font: HelveticaNeueLT Std pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: HelveticaNeueLT Std Blk Cn pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: ITC Franklin Gothic Std Book pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: OCR A Std pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: Times pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: Universal Std News w Comm Pi pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: ITC Zapf Dingbats Std pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: HelveticaNeueLT Std Blk pdf.worker.js:1104:13
Warning: XFA - Cannot find the font: HelveticaNeueLT Std Bold Outln pdf.worker.js:1104:13
```

**Comment by calixteman** [comment]
`config` stream contains a map for font substitution:
```xml
<fontInfo>
  <embed>0</embed> <!-- 0|1 -->
    <!--defaultTypeface>MyriadPro-Regular</defaultTypeface-->
    <map>
      <!-- [0..n] Attributes: from='', to='' [0..n]  -->
      <equate force="0" from="Courier_*_*" to="Courier New_*_*"/>
      <equate force="0" from="CourierNew_*_*" to="Courier New_*_*"/>
      <equate force="0" from="Courier-New_*_*" to="Courier New_*_*"/>
      <equate force="0" from="MyriadPro_*_*" to="Myriad Pro_*_*"/>
      <equate force="0" from="MyriadPro-Regular_*_*" to="Myriad Pro_*_*"/>
      <equate force="0" from="MyriadPro-It_*_*" to="Myriad Pro_*_italic"/>
      <equate force="0" from="MyriadPro-SemiboldSemiCn_*_*" to="Arial Narrow_bold_*"/>
...
```
This pdf doesn't contain any fonts.

**Comment by calixteman** [comment]
We should probably always fallback on the fake myriad when the font isn't available.
