### ISSUE TITLE
worksrc is a cdn link, but it throw a error : Refused to execute script from...because its MIME type ('text/plain') is not executable.

### ISSUE THREAD

**Issue by monjaywang** [mozilla/pdf.js#13607]
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/23545603/122886355-79e95780-d372-11eb-9c43-2c2b4684920b.png)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/23545603/122886518-9f766100-d372-11eb-8bff-1ac3eaa20856.png)

worksrc is a cdn link, but it throw a error 
 blob:https://xen--box-8928--www-zhihu-com.zpres.zhihu.com/ec905a90-c4f1-4bbb-b51e-b837b6de13b9: Refused to execute script from 'https://zhihu-live.zhimg.com/namespace_1001/static/20201115/65eb6ba07d0eb0a435733fde6111ef9d.js' because its MIME type ('text/plain') is not executable.
![image](https://user-images.githubusercontent.com/23545603/122886570-a8ffc900-d372-11eb-8de5-11d851ff3c40.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately not actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
