### ISSUE TITLE
Does not display symbol Ç (Ø)

### ISSUE THREAD

**Issue by Mazuruk** [mozilla/pdf.js#13626]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/6715502/test.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 91.0.4472.114 
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 
- Is a browser extension: yes

Steps to reproduce the problem:
1. download file
2. open file

What is the expected behavior? (add screenshot)
show symbol
![image](https://user-images.githubusercontent.com/50500976/123409847-55ca8800-d5b7-11eb-9e5b-c7f3b33c00e1.png)

What went wrong? (add screenshot)
Does not show symbol
![image](https://user-images.githubusercontent.com/50500976/123409707-274cad00-d5b7-11eb-9a64-b11dcf3cdc3f.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Latest Version Chrome extension

**Comment by calixteman** [comment]
I confirm the bug with firefox nightly on linux (debian).
In the console, I get:
```
downloadable font: hhea: Non-zero caretOffset but head.macStyle italic bit is not set, setting to caretOffset to 0: 5000 (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
```

**Comment by calixteman** [comment]
I just try to set `header[22]=header[23]=0` in `sanitizeMetrics`: it at least removes the error in the console but there's still an issue with the display of `Ø`.

**Comment by calixteman** [comment]
I think we should do the same as in OTS to turn off the error in console:
https://github.com/khaledhosny/ots/blob/main/src/metrics.cc#L52-L57

**Comment by Snuffleupagus** [comment]
I've got a *potential* patch for the glyph-mapping issue (it passes all tests locally), but I still need a little bit of time to really think through the approach since it requires touching `readCmapTable` and any errors there can breaking TrueType fonts quite badly.

**Comment by Mazuruk** [comment]
@Snuffleupagus Thank you for your reply, please let me know when this revision will be completed if possible.
