### ISSUE TITLE
Rendering issue: missing background on PDF

### ISSUE THREAD

**Issue by philip-khor** [mozilla/pdf.js#13629]
Attach (recommended) or Link to PDF file here:
[The-Stories-Algorithms-Tell-CFI-publication-MAR21.pdf](https://github.com/mozilla/pdf.js/files/6720082/The-Stories-Algorithms-Tell-CFI-publication-MAR21.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 91.0a1 (2021-06-26) (64-bit)
- Operating system and its version: Windows_NT 10.0 21390
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Page 2 of this PDF is rendered without background in Firefox. Expected render on right, Firefox pdf.js render on left 

![image](https://user-images.githubusercontent.com/35039795/123512847-5c8ef300-d6bc-11eb-85a1-5590cada7b37.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by philip-khor** [comment]
Seems to be resolved in Nightly 91.0a1 (2021-07-07) (PDF.js: 2.10.263)

**Comment by timvandermeij** [comment]
Works for me too. It's not uncommon for Nightly to have such bugs, so let's close this as fixed upstream for now. Thanks!
