### ISSUE TITLE
Messy Chinese Code Rendered in Wechat PC 's browser 

### ISSUE THREAD

**Issue by wanghai2408** [mozilla/pdf.js#13636]
Attach (recommended) or Link to PDF file here:
Configuration:
- Web browser and its version: CEF(4.0.1326.400)|Chromium(53.0.2785.116)
- Operating system and its version:Windows  10
- PDF.js version:
- Is a browser extension:2.7.570
Steps to reproduce the problem:
1.  Sign In the Wechat App On Winodws 10
2.  load with the PDF file Office Viewer's in Wechat's build-in browser.
3.  The some Chinese text content are missed.

What is the expected behavior? (add screenshot)
![screenshot-mozilla github io-2021 06 27-14_10_12 (1)](https://user-images.githubusercontent.com/4546589/123534744-d9b87780-d751-11eb-9953-b0c34b681ee1.png)

What went wrong? (add screenshot)
![Uploading 粘贴的图片2021_6_27_下午2_26.png…]()
<img width="1755" alt="Windows10" src="https://user-images.githubusercontent.com/4546589/123535084-59474600-d754-11eb-86a9-3322f13791df.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://cdnstyle.woqukaoqin.com/pdfjs/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Web browser and its version: CEF(4.0.1326.400)|Chromium(53.0.2785.116)
> [...]
> load with the PDF file Office Viewer's in Wechat's build-in browser.

The supported browsers are already listed in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, where you'll note that Wechat is first of all *not* listed and secondly that the mentioned Chromium version is too old.
