### ISSUE TITLE
Two pages appear on single page

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13632]
Attach (recommended) or Link to PDF file here:
https://vaccinechoicecanada.com/wp-content/uploads/Daycare-exemption-form.pdf

Configuration:
- Web browser and its version: Firefox Nightly 91.0a1 (2021-06-25) (64-bit)
- Operating system and its version: Windows 10.0.19043.1052
- PDF.js version: N/A

Steps to reproduce the problem:
1. enableXFA in Firefox Nightly
2. Open form

What is the expected behavior? (add screenshot)
First page renders
![image](https://user-images.githubusercontent.com/7104454/123517414-c84a6f00-d66e-11eb-9fa7-22680e45a6da.png)

What went wrong? (add screenshot)
First and second page appear on second page
![image](https://user-images.githubusercontent.com/7104454/123517419-ced8e680-d66e-11eb-8c8c-c38304b2193c.png)

**Comment by Snuffleupagus** [comment]
WFM, in Firefox Nightly 91.0a1 (2021-07-08) using the built-in PDF Viewer (i.e. PDF.js version `2.10.263`).
