### ISSUE TITLE
XFA Form missing some text content

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13631]
Attach (recommended) or Link to PDF file here:
https://www.co.lucas.oh.us/DocumentCenter/View/44843/WIBApplicationForm

Configuration:
- Web browser and its version: Firefox Nightly 91.0a1 (2021-06-25) (64-bit)
- Operating system and its version: Windows 10.0.19043.1052
- PDF.js version: N/A

Steps to reproduce the problem:
1. enableXFA in Firefox Nightly
2. Open form

What is the expected behavior? (add screenshot)
Text renders (pg 2)
![image](https://user-images.githubusercontent.com/7104454/123516584-d39b9b80-d66a-11eb-956f-980c084b14af.png)

What went wrong? (add screenshot)
Text is missing 
![image](https://user-images.githubusercontent.com/7104454/123516599-e615d500-d66a-11eb-89ef-c49818e9b579.png)

**Comment by calixteman** [comment]
The text is rendered in nightly 20210626094654 under Linux, @JDziurlaj can you confirm ?
Anyway the width of the container for "Applicant Contact" on top of page 1 is wrong.

**Comment by JDziurlaj** [comment]
@calixteman Verified OK.
