### ISSUE TITLE
Can not use standardFontDataUrl

### ISSUE THREAD

**Issue by NNSTH** [mozilla/pdf.js#13646]
Attach (recommended) or Link to PDF file here:![thumbnail](https://user-images.githubusercontent.com/36368967/123768885-68073780-d8d1-11eb-94eb-b60b82f898af.png)This is my PDF file: 
[tmp.pdf](https://github.com/mozilla/pdf.js/files/6731946/tmp.pdf)

Configuration:
- (Web Browser:) I'm using pdfjs-dist on Node server
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 2.8.335
- Is a browser extension: No.

Steps to reproduce the problem:
I took the code from examples/node/pdf2png in order to generate thumbnail to my pdf, using node canvas module.
so you can take the code from there and run it externally with latest version of pdfjs-dist.
I get a lot of warnings, like this:
Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Times_path_W.".
And the thumbnail generated is missing some of the text, see this png: 
![output](https://user-images.githubusercontent.com/36368967/123768644-2d9d9a80-d8d1-11eb-8595-25ae3d53d860.png)

What is the expected behavior? The thumbnail has to look like this: 
![thumbnail](https://user-images.githubusercontent.com/36368967/123768885-68073780-d8d1-11eb-94eb-b60b82f898af.png)

What went wrong? see the differences between the 2 images.

While searching within the code of pdfjs-dist in node-modules, it seems like the standardFontDataUrl is not used anywhere,
Is this the correct name? or am I missing something?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.8.335
> [...]
> it seems like the standardFontDataUrl is not used anywhere,

That functionality landed in PR #12726, which is new enough to not *yet* have been included in an official release; hence you'll either need to wait for a future release, or use the development version of the library (see https://github.com/mozilla/pdf.js#getting-the-code).

**Comment by NNSTH** [comment]
Thanks for the quick reply, and estimation for a future release?

**Comment by NNSTH** [comment]
I still get a partially document while trying to generate thumbnail of the pdf, I tried both pdf2png and pdf2svg from the examples, however, the result looks much different than the real pdf source.
e.g.: this is the source doc:
[22-25-34-FINALTASKBCO226SP.pdf](https://github.com/mozilla/pdf.js/files/6738580/22-25-34-FINALTASKBCO226SP.pdf)
and this is the generated png
![output-test](https://user-images.githubusercontent.com/36368967/123914117-b971fe00-d987-11eb-85df-ff6ffcee4cd2.png)
Any idea of how can I use this code to get the desired output?
Thanks!
:
