### ISSUE TITLE
Cannot open a pdf with a large jpx image

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13643]
Attach (recommended) or Link to PDF file here:
[3.pdf](https://github.com/mozilla/pdf.js/files/6725880/3.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Debian testing
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached pdf

What is the expected behavior? (add screenshot)
Display the image

What went wrong? (add screenshot)
Nothing is displayed but an error in console:
```
An error occurred while rendering the page.
PDF.js v2.10.201 (build: 9de0916fd)
Message: 
Stack: putBinaryImageData@resource://pdf.js/build/pdf.js:4873:13
paintInlineImageXObject@resource://pdf.js/build/pdf.js:6445:27
paintImageXObject@resource://pdf.js/build/pdf.js:6393:12
executeOperatorList@resource://pdf.js/build/pdf.js:5128:22
_next@resource://pdf.js/build/pdf.js:3878:39
_scheduleNext/<@resource://pdf.js/build/pdf.js:3866:16
viewer.js:1186:15
    _otherError resource://pdf.js/web/viewer.js:1186
```

I found this pdf in:
https://bugs.chromium.org/p/pdfium/issues/detail?id=1698&q=&can=1

**Comment by ArnoldFabasoft** [comment]
Same problem here with another pdf document (from a customer):
Firefox Version: 94.0
Chrome and Microsoft Edge are working correctly
PDF.JS Version: 
- 2.9.3.59 and 2.11.298

Are there any updates to this issue available?

**Comment by Snuffleupagus** [comment]
Will this issue also be fixed by PR #16077?

**Comment by calixteman** [comment]
Yep it will.

**Comment by calixteman** [comment]
I profiled with the rescaling patch:
https://share.firefox.dev/3J81UKL
Most of the time (~23s) is spent in decoding the image and the resizing stuff takes ~2s.
