### ISSUE TITLE
XFA Text exceeds draw bounds

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13650]
Attach (recommended) or Link to PDF file here:
https://www.fema.gov/sites/default/files/documents/FEMA-form_206-FY-21-112_adjuster-proof-of-loss_2021.pdf

Configuration:

- Web browser and its version: 91.0a1 (2021-07-01) (64-bit)
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. enableXfa = true
2. Open form

What is the expected behavior? (add screenshot)
Text remains in bounds
![image](https://user-images.githubusercontent.com/7104454/124190340-1a84f900-da90-11eb-8de6-52c364b6fb1f.png)

What went wrong? (add screenshot)
Text exceeds draw area (yellow highlight for emphasis)
![image](https://user-images.githubusercontent.com/7104454/124190351-1d7fe980-da90-11eb-9022-13dae036596f.png)

**Comment by JDziurlaj** [comment]
This looks OK in Nightly 89.0.2 (64-bit)

**Comment by marco-c** [comment]
> This looks OK in Nightly 89.0.2 (64-bit)

In 89 there was no XFA support, did you mean latest Nightly?

Anyway, it works in latest Nightly, I've just tested it.

@calixteman do you want to add this PDF to the reftests?

**Comment by JDziurlaj** [comment]
Sorry I meant Nightly.
