### ISSUE TITLE
Not match data sources from method of getOutline() which  different pdf files.

### ISSUE THREAD

**Issue by sdeass** [mozilla/pdf.js#13652]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE11 and Chrome 93.0.4549.4
- Operating system and its version:
- PDF.js version:  "pdfjs-dist": "2.1.266"
- Is a browser extension: yes

Steps to reproduce the problem:
1.  I would like to use book marks to jump the page.
2. I had been get the sources from method of getOutline(), then return the num not the correct the page. seemly A-Z.
     I provided the sources blow.
flies versions:
 right sample version: 1.6  wrong sample:1.5

 

What is the expected behavior? (add screenshot)
Please support what method can I use into Vue.

What went wrong? (add screenshot)

Sources below:
wrong:
[{"dest":[{"num":462,"gen":0},{"name":"XYZ"},0,637,0],"url":null,"title":"home","color":{"0":0,"1":0,"2":0},"bold":false,"italic":false,"items":[]}]
But the page only had 226.

correct:
[{"dest":[{"num":1,"gen":0},{"name":"XYZ"},0,637,0],"url":null,"title":"home","color":{"0":0,"1":0,"2":0},"bold":false,"italic":false,"items":[]}]

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that this part of the issue template is *required* in order for issues to be (generally) actionable!

> PDF.js version:  "pdfjs-dist": "2.1.266"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Please support what method can I use into Vue.

Unfortunately we cannot provide *specific* help/support for various frameworks, e.g. "Vue" in this case.

> I had been get the sources from method of getOutline(), then return the num not the correct the page. seemly A-Z.

This is *very* difficult to understand unfortunately; please provide clearer and more detailed STR here (in addition to also attaching the PDF document in question).

**Comment by Snuffleupagus** [comment]
Also, it probably helps to read the relevant section of the PDF specification to understand the destination format used; see e.g. https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.1696125 which contains the following sentence (emphasis mine):
> In each case, page is an ***indirect reference*** to a page object [...]

**Comment by sdeass** [comment]
Thanks for reminded.
How to distinguishable from sources of "dest: "G1.778581"  when I tried the pdf files which you provided?
Because I should be know which pages inside or how to navigate to the page?
Please provided the least PDFjs Api for me.
Thanks so much.

**Comment by Snuffleupagus** [comment]
> How to distinguishable from sources of "dest: "G1.778581" when I tried the pdf files which you provided?
> Because I should be know which pages inside or how to navigate to the page?

Unfortunately you've still not provided the requested details, and the above questions are not particularly easy to understand!

Perhaps the following is of help, but it's really not possible for anyone to assist without a *clearer* description of your issue:
 - https://github.com/mozilla/pdf.js/blob/d80651e5724686535ac4fbdfac5d5e280a16dbdb/src/display/api.js#L793-L801
 - https://github.com/mozilla/pdf.js/blob/d80651e5724686535ac4fbdfac5d5e280a16dbdb/src/display/api.js#L774-L781

Finally, this is how the viewer uses the various API-methods: https://github.com/mozilla/pdf.js/blob/d80651e5724686535ac4fbdfac5d5e280a16dbdb/web/pdf_link_service.js#L109-L193
