### ISSUE TITLE
Uncaught (in promise)  when embeded as iframe

### ISSUE THREAD

**Issue by jbonlinea** [mozilla/pdf.js#13663]
Attach (recommended) or Link to PDF file here:
The issue do occus with diferent pdf files, that do not cause breaking in others use case

Configuration:
- Web browser and its version:
see below in what happens

- Operating system and its version:
   Static hostname: debian
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 474f4774938047ed92bb158e05fc10e9
           Boot ID: 03815e7e5b094c059efa88beae240304
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.9.0-16-amd64
      Architecture: x86-64

- PDF.js version:
2.8.3.3.5

- Is a browser extension:
eu... I downloaded pdf js from [here](https://mozilla.github.io/pdf.js/getting_started/) and imported it in my project

Steps to reproduce the problem:

take the page with the hello world example
embed it as an iframe in a wordpress post ; display the post --> this is ok the pdf is loaded
embed it as an iframe in a second wordpress post ; display the post --> this is ok the pdf is loaded

then create a wordpress post that contains both previously created post (content) 
go to the page of this latest wordpress post

the pdf are not always displayed, sometimes one of them is, see what went wrong for details

What is the expected behavior? (add screenshot)
load the pdf every time

What went wrong? (add screenshot)

on firefox, when I embed an iframe with my pdfjs project, sometimes i do get this error, sometimes not.
when I embed the iframe thee times on the same page, sometimes i do get this error three times, once for each iframe, some times only twice, and one pdf is ok... it is not always the same one...

On chrome the issue do not seems to occurs

Error on
Firefox firefox 78.11.0esr (64 bits)
```
Uncaught (in promise) 
Exception
​
columnNumber: 0
​
data: null
​
filename: "https://mysite/js/pdfjs-dist/build/pdf.js"
​
lineNumber: 5109
​
message: ""
​
name: "NS_ERROR_FAILURE"
​
result: 2147500037
​
stack: "resetCtxToDefault@https://mysite/js/pdfjs-dist/build/pdf.js:5109:5\nbeginDrawing@https://mysite/js/pdfjs-dist/build/pdf.js:5237:24\ninitializeGraphics@https://mysite/js/pdfjs-dist/build/pdf.js:3739:16\nrender/<@https://mysite/js/pdfjs-dist/build/pdf.js:2266:26\n"
​
<prototype>: ExceptionPrototype
​​
columnNumber: 
​​
data: 
​​
filename: 
​​
lineNumber: 
​​
message: 
​​
name: 
​​
result: 
​​
stack: 
​​
toString: function toString()
​​
Symbol(Symbol.toStringTag): "Exception"
​​
<get columnNumber()>: function columnNumber()
​​
<get data()>: function data()
​​
<get filename()>: function filename()
​​
<get lineNumber()>: function lineNumber()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<get result()>: function result()
​​
<get stack()>: function stack()
​​
<set stack()>: function stack()
​​
<prototype>: Object { … }
canvas.js:787:4


```

I have no clue how to interpret this error message, nor what could cause this.

As this occurs on firefox and not chrome, I assume there is something patially related to broswer, to pdfjs and to wordpress

Hope you may have a clue

Regards

**Comment by Snuffleupagus** [comment]
> then create a wordpress post that contains both previously created post (content)

Unfortunately "WordPress"-integration isn't something that the PDF.js contributors can provide help/support for.

Furthermore, as-is this unfortunately isn't really actionable, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
