### ISSUE TITLE
Complex table not rendering properly

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13667]
Attach (recommended) or Link to PDF file here:
https://www.mfa.gov.lv/data/file/Protocol/pvn_un_an_atmaksas_iesniegums.pdf

Configuration:

- Web browser and its version: 91.0a1 (2021-07-03) (64-bit)
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. enableXfa = true
2. Open form

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/7104454/124388777-539cb380-dcb2-11eb-985d-49fec0bff19b.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/7104454/124388784-5bf4ee80-dcb2-11eb-911d-6c0072a34910.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> https://www.mfa.gov.lv/data/file/Protocol/pvn_un_an_atmaksas_iesniegums.pdf

That link no longer works, and the file cannot be found on the Internet Archive either; hence closing for now.

(*Please note:* This is the reason that we always recommend *attaching* PDF files directly to issue, rather than linking.)
