### ISSUE TITLE
pdfjs-dist doesn't include hash in worker file

### ISSUE THREAD

**Issue by mdrodz** [mozilla/pdf.js#13685]
The current webpack.js file processes the pdf.worker.js file using the worker-loader like so:

`const PdfjsWorker =  require("worker-loader?esModule=false&filename=[name].js!./build/pdf.worker.js");`

This will throw an "API version is different etc..." error because the pdf.js file is processed by my webpack and converted into pdf.[contenthash].js but the pdf.worker.js fle isn't because of this line. This will make the browser fetch the new pdf.js file, since its name changed and is no longer cached but will not do the same for the pdf.worker.js file.

Could this be changed to:

`const PdfjsWorker = require("worker-loader?esModule=false&filename=[name].[contenthash].worker.js!./build/pdf.worker.js");`

This will change the name of the pdf.worker.js every time you upgrade the package, and will stop giving the API version error.

**Comment by timvandermeij** [comment]
I think that should be fine; feel free to make a PR for this. The Webpack support is mainly powered by the community, so improvements are welcome if the existing use case also keeps working.

**Comment by mdrodz** [comment]
The PR: https://github.com/mozilla/pdf.js/pull/13699#issue-686154850

**Comment by timvandermeij** [comment]
Fixed by #13699.
