### ISSUE TITLE
Feature request: Load the same PDF on refresh

### ISSUE THREAD

**Issue by symtalha14** [mozilla/pdf.js#13695]
Attach (recommended) or Link to PDF file here:
No need
Configuration:
- Web browser and its version: All of them 
- Operating system and its version: Windows 10 64 bit
- PDF.js version: latest
- Is a browser extension: No

Steps to reproduce the problem:
Open a PDF in pdf.js and then refresh the page, the pdf disappears and the default pdf is loaded.

What is the expected behavior? (add screenshot)
Ideally,  the PDF which was already loaded should be loaded again on refresh.

What went wrong? (add screenshot)
It is loading the default sample PDF.

I don't know if it's intended to be like that or it is just for testing purposes but if not I think it should be fixed.

**Comment by Snuffleupagus** [comment]
It's not really clear from the description, so I'll have to guess that you're talking about the default viewer here; i.e. https://github.com/mozilla/pdf.js#online-demo

Given that the PDF.js library can load data in a couple of different ways, not just from URLs but also as e.g. TypedArrays[1], it's likely not possible to even implement what you ask for in the general case.
Furthermore, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Closing as answered, or possibly even WONTFIX.

---
[1] Refer to the JSDocs in https://github.com/mozilla/pdf.js/blob/418880d47330e42f867b81c8e4f9035073bf94e3/src/display/api.js#L217-L229
