### ISSUE TITLE
XFA - xfaLayer no more accessible after zooming

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13697]
STR:
  - open a pdf with some XFA
  - click on a text to select it or in an input...: everything is fine
  - zoom
  - try step 2 again and it isn't fine anymore

In looking in devtools, we can see that before zooming we've in page and in this order `canvasLayer`, `textLayer` and `xfaLayer`;
After zooming `textLayer` and `xfaLayer` are swapped, I don't yet if it's the root cause of the issue but it's the only thing I noticed.

**Comment by marco-c** [comment]
On Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1719629.

**Comment by calixteman** [comment]
We must do something similar to:
https://github.com/mozilla/pdf.js/blob/c33bf0b5e8dc09ed010d9c4a1dcdaa98975b6378/web/pdf_page_view.js#L494
