### ISSUE TITLE
Unable to decode images from getOperatorList argsArray

### ISSUE THREAD

**Issue by allandiego** [mozilla/pdf.js#13709]
Attach (recommended) or Link to PDF file here:
[pdf-test.pdf](https://github.com/mozilla/pdf.js/files/6793219/pdf-test.pdf)

Configuration:
- Web browser and its version: Firefox 89.0.2 (64-bits)
- Operating system and its version: Windows 10 64
- PDF.js version: 2.9.359 -  https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.9.359/pdf.min.js

Steps to reproduce the problem:
I'm trying do get images from pdf file and render into html canvas, I noticed that Uint8ClampedArray returned from page.objs.get() contains only RGB chanels so I added a 4th alphachanel to the array like this example:
https://github.com/mozilla/pdf.js/blob/master/examples/image_decoders/jpeg_viewer.js

1. https://codepen.io/allandiego/pen/RwVGbyj
2. select the sample pdf with a image

What is the expected behavior? (add screenshot)
render the imagem from argsArray into html canvas

What went wrong? (add screenshot)
the array appears to be missing pixels data, only some pixels of the image are rendered

**Comment by Snuffleupagus** [comment]
> so I added a 4th alphachanel to the array like this example:
> https://github.com/mozilla/pdf.js/blob/master/examples/image_decoders/jpeg_viewer.js

May I suggest taking one more, and slightly closer, look at the loop found there: https://github.com/mozilla/pdf.js/blob/caaf77375f4a1b1ee2e9402ec5a2f5d25a65e161/examples/image_decoders/jpeg_viewer.js#L74-L79
Here you'll notice that you need to use *different* variables to access the two `Uint8ClampedArray`s, since they (by definition) have different lengths and thus cannot be indexed with a single variable.

**Comment by allandiego** [comment]
@Snuffleupagus thank you very much, that was exactly the problem. Btw It returns 3 chanels array because the image is jpg? if it's a png it would return 4 chanels?

**Comment by Snuffleupagus** [comment]
> Btw It returns 3 chanels array because the image is jpg? if it's a png it would return 4 chanels?

Nope, that's not quite right.
Images sent from the worker-thread in PDF.js will *generally* use the most memory efficient format possible, in the returned `Uint8ClampedArray`, and the exact format can be found in the `kind` property on the image objects (that you get from the `pdfPage.objs`) with the following interpretation: https://github.com/mozilla/pdf.js/blob/2822ba42082b26fae9ecd9494c824d18ef9b44a2/src/shared/util.js#L46-L50
