### ISSUE TITLE
SVG  missing text (maybe the clippath problem)

### ISSUE THREAD

**Issue by samchild** [mozilla/pdf.js#13719]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome  91.0.4472.124 or Microsoft Edge(91.0.864.67 )
- Operating system and its version: window 10
- PDF.js version:  pdfjs-2.9.359-legacy-dist
- Is a browser extension:

Steps to reproduce the problem:
1. download the input.pdf file
2.using pdf2svg.js to generate svgs
3.the first page  svg of the pdf file

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/12930061/125237448-4f0e7580-e318-11eb-8098-6f7a0963c621.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/12930061/125237406-3b630f00-e318-11eb-84cc-cdab4bb4c533.png)
![image](https://user-images.githubusercontent.com/12930061/125237660-a44a8700-e318-11eb-9c9b-494fcbf55521.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

PDF file:

[input.pdf](https://github.com/mozilla/pdf.js/files/6798860/input.pdf)

**Comment by georgezouq** [comment]
@samchild same problem, did you fix this?
