### ISSUE TITLE
XFA Subforms incorrectly colored

### ISSUE THREAD

**Issue by JDziurlaj** [mozilla/pdf.js#13747]
Attach (recommended) or Link to PDF file here:
https://www.nbp.pl/badania/projekty_badawcze/4kbe/formularz_zgloszeniowy_zespolowy.pdf

Configuration:

- Web browser and its version: 92.0a1 (2021-07-17) (64-bit)
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. enableXfa = true
2. Open form

What is the expected behavior? (add screenshot)
Subforms (not including fields) are grey
![image](https://user-images.githubusercontent.com/7104454/126037105-6bbfc327-7387-4edd-aeec-e3f2731125e1.png)

What went wrong? (add screenshot)
Everything is grey (underneath field highlight overlay) 
![image](https://user-images.githubusercontent.com/7104454/126037124-13597d96-a2fb-4643-ac0a-703e4fc610d8.png)

**Comment by calixteman** [comment]
Fixed thanks to:
https://github.com/mozilla/pdf.js/pull/13806
