### ISSUE TITLE
Open url in target iframe

### ISSUE THREAD

**Issue by netrunner7** [mozilla/pdf.js#13755]
Hello,

I would love to use pdf.js on my site, but I have .pdf files with lots of image links. I would like them to open in separate iframe [instead of taking full browser window] is this possible?

Thanks for help.

**Comment by timvandermeij** [comment]
You can set the `externalLinkTarget` app option; see https://github.com/mozilla/pdf.js/blob/f74562b19cc166af126705b04971a7a111e7e2f3/src/display/display_utils.js#L308-L314 for the possible values.

**Comment by leohxj** [comment]
I use `window.PDFViewerApplicationOptions.set('externalLinkTarget', 2);`, but the annotationLater also render this:

```
<a title="http://www.publishing.waldenu.edu/" href="http://www.publishing.waldenu.edu/" target="" rel="noopener noreferrer nofollow"></a>
```

target doesn't has "_blank" value.

**Comment by netrunner7** [comment]
Hello, I managed to target external links to my iframe! (by changing default string value)
The only other problem I have is that most links in my .pdf file are in relevant format like:

folder1/folder2/image.jpg
folder1/folder2/image2.jpg
etc..

and they do not open in pdf.js viewer
I see there are some options with base url, is it possible to automaticaly change such links to:
https://mydomain.com/folder1/folde2/image.jpg

Thanks for help.

**Comment by netrunner7** [comment]
It looks like it doesn't treat relative links as links. Is there a way to fix this? Thanks for help
