### ISSUE TITLE
Relative file links in .pdf - how to enable them?

### ISSUE THREAD

**Issue by netrunner7** [mozilla/pdf.js#13769]
Hello, I have a little problem:
most links in my .doc file are in relevant format like:

/folder1/folder2/image.jpg
/folder1/folder2/image2.jpg
etc..

Which in pdf is converted to file:///folder1/folder2/image.jpg etc.
and they do not open in pdf.js viewer

Is it possible to automatically change such links to:
https://mydomain.com/folder1/folder2/image.jpg

Thanks for help.

**Comment by Snuffleupagus** [comment]
> most links in my .doc file are in relevant format like

Note that the PDF.js library only support `.pdf` files, and not any other file type.

> Is it possible to automatically change such links to:
> https://mydomain.com/folder1/folder2/image.jpg

Yes, if you provide the `docBaseUrl` option when calling `getDocument`; please see https://github.com/mozilla/pdf.js/blob/2cf90cd9adbdc14c175c99e0699f371c1d92fc31/src/display/api.js#L149-L151

---

*For future reference:* When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by netrunner7** [comment]
> > most links in my .doc file are in relevant format like
> 
> Note that the PDF.js library only support `.pdf` files, and not any other file type.
> 
> > Is it possible to automatically change such links to:
> > https://mydomain.com/folder1/folder2/image.jpg
> 
> Yes, if you provide the `docBaseUrl` option when calling `getDocument`; please see
> 
> https://github.com/mozilla/pdf.js/blob/2cf90cd9adbdc14c175c99e0699f371c1d92fc31/src/display/api.js#L149-L151
> 
> _For future reference:_ When opening an issue, please remember to provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Thanks, it works! :D
