### ISSUE TITLE
Website gets displayed instead of PDF

### ISSUE THREAD

**Issue by ekinser** [mozilla/pdf.js#13765]
(https://github.com/mozilla/pdf.js/files/6850315/myPDF.pdf)

Configuration:
- Web browser and its version:
Google Chrome Version 91.0.4472.164
                                                  FireFox Version 90.0.1
                                                  Microsoft Edge Version 91.0.864.70
- Operating system and its version: Windows 10 Build 19043.1081
- PDF.js version: 2.8.335
- Is a browser extension: No

Steps to reproduce the problem:
1. Set up pdfjs as normal

What is the expected behavior? (add screenshot) Expected PDF to be displayed in the container

What went wrong? (add screenshot) [
![Dashboard Screenshot](https://user-images.githubusercontent.com/23428102/126373323-2166a243-dafe-4a32-99c2-2b5c401cafcf.jpg)
](url)

NOTE: I followed this tutorial very closely: https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/#step-1-install-dependencies

**Comment by Snuffleupagus** [comment]
> (https://github.com/mozilla/pdf.js/files/6850315/myPDF.pdf)

That link points *directly* to a PDF file, and not actually to the web-site shown in your screen-shot.

> NOTE: I followed this tutorial very closely: https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/#step-1-install-dependencies

Unfortunately that's *not an official* resource, but rather a third-party example, and it may thus not be correct and/or show best practices.

---

As-is we unfortunately cannot help, since it's impossible to debug something from only a screen-shot. Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by ekinser** [comment]
@Snuffleupagus Apologies. I can't provide a live example of the website as it's currently in development and being run locally. I could not find an official resource related to the third-party one I provided. I've put together the relevant files in to a GitHub repo here: https://github.com/ekinser/pdfjsHELP

Please let me know if that helps at all.

**Comment by timvandermeij** [comment]
The official examples are in https://github.com/mozilla/pdf.js/tree/master/examples. The GitHub repository you linked to is not available for us (404 not found). Without a runnable example, there is unfortunately nothing we can do here. If the PDF doesn't show up, most likely the provided link is incorrect. Check the network tab to see if the PDF file is actually requested.
