### ISSUE TITLE
Option to load the complete pdf

### ISSUE THREAD

**Issue by Balrrach** [mozilla/pdf.js#13785]
The full PDF is never loaded into memory, only the current page and a few more before and after the current page. This causes loading icon when you quickly change to a different page that is far away from the current one. I know this is made in order to reduce memory consumption but I think having the option to load the whole document is good and can be useful for some uses of the pdfViewer like writing LaTex documents using Direct Syntex or when a user needs to move frequenty and quickly through the document.

**Comment by Snuffleupagus** [comment]
> I know this is made in order to reduce memory consumption

It's not only done to reduce memory usage, but to improve *overall* performance as well. Note that the overall UX (e.g. scrolling performance) will suffer considerately in browsers when there's a huge number DOM elements present.

> but I think having the option to load the whole document is good

In generally it's unfortunately a *really bad idea*, e.g. what about a document with a thousand pages, and we don't want to introduce options which are severe performance foot-guns.[1]

Please note that https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages is the official position, which exists for good reason; hence closing this as WONTFIX.

---
[1] We know from experience that many users are unfortunately very likely to enable options that actively hurt performance, e.g. by ignoring documentation advising against it or by simply copy-and-pasting from a (badly written) third-party example.

**Comment by Balrrach** [comment]
I understand. Thanks a lot for the quick answer!
