### ISSUE TITLE
Setting default scale in multipage viewer

### ISSUE THREAD

**Issue by MFoxx** [mozilla/pdf.js#13789]
We've build custom PDF Viewer using PDF.js API. However we can't figure out how to set default scale value on multipage display of PDFs. Because on singlepage you can use this line of code to set scale:

`const viewport = page.getViewport({ scale: 2.5 });`

But on multipage viewport, there is no instance of page, where we could set it up. Our code for initialization of Viewer:

```
const eventBus = new pdfjsViewer.EventBus();

const pdfLinkService = new pdfjsViewer.PDFLinkService({
    eventBus
});

// (Optionally) enable find controller.
const pdfFindController = new pdfjsViewer.PDFFindController({
        eventBus,
        linkService: pdfLinkService
});

const pdfViewerVar = new pdfjsViewer.PDFViewer({
    container: container,
    eventBus: eventBus,
    pdfLinkService,
    pdfFindController,
    useOnlyCssZoom: true,
    textLayerMode: 2
});
```

And setting the PDF:

```
const CMAP_URL = '/node_modules/pdfjs-dist/cmaps/';
const CMAP_PACKED = true;
const loadingTask = pdfjsLib.getDocument({
    url: URL.createObjectURL(scriptFile),
    cMapUrl: CMAP_URL,
    cMapPacked: CMAP_PACKED
});
loadingTask.promise.then(function(pdfDocument) {
     pdfViewer.setDocument(pdfDocument);
}

```
So, my question is, how to change default scale in multipage viewer ?

**Comment by Snuffleupagus** [comment]
Please see (which *appear* to be the example your code is based on): https://github.com/mozilla/pdf.js/blob/bcd6dc416abeb66508cf8c36086cafb0f231f884/examples/components/simpleviewer.js#L74-L76
