### ISSUE TITLE
Chrome 92 Error When Using WinAnsiEncoding: function at() { [native code] } could not be cloned.

### ISSUE THREAD

**Issue by tebueno** [mozilla/pdf.js#13798]
Attach (recommended) or Link to PDF file here:

### Configuration: ###
- Web browser and its version: `92.0.4515.107 (Official Build) (x86_64)`
- Operating system and its version: `MacOs Big Sur version 11.3`
- PDF.js version: `2.4.456`
- Is a browser extension: `false`

Steps to reproduce the problem:
Sorry I don't have a PDF link to reproduce the issue but I can try to explain:

The breaking line of code is here: 

https://github.com/mozilla/pdf.js/blob/51f0a810851c311598748f637fb583b20b7dce03/src/core/evaluator.js#L3637

When using [WinAnsiEncoding](https://github.com/mozilla/pdf.js/blob/5cf116a958548f6596674bf8d5ca0fe64aa2df3c/src/core/encodings.js#L177), which has an "at" value at the 64th index.
For the font Courier (the font that this is failing for), widthsByGlyphName has always been empty for this font. This means that the above line would evaluate to `[]["at"]`, which returned nothing in Chrome 91.

In Chrome 92, however, this actually returns the function / native code because the Array prototype (for that empty array) has an at [method now](https://www.chromestatus.com/feature/6123640410079232). This is causing failures at a later point in the stack. 

**As a result, the overlaying text is not getting displayed to our users.**

**Comment by Snuffleupagus** [comment]
> PDF.js version: `2.4.456`

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
> Sorry I don't have a PDF link to reproduce the issue but I can try to explain:

This was *possibly* fixed by PR #12924, but without a test-case it's simply impossible to tell.

**Comment by tebueno** [comment]
Hi @Snuffleupagus, It was reproducible on version `2.10.377` as well
