### ISSUE TITLE
Unable to use btoa for file in url with pdfjs

### ISSUE THREAD

**Issue by evergreen-shankar** [mozilla/pdf.js#13809]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 
Google Chrome Version 92.0.4515.107
- Operating system and its version: 
Windows 10
- PDF.js version: 
2.10.377
- Is a browser extension:
No

Steps to reproduce the problem:

Actually i don't want to expose file name and its path to end user, so only using btoa for the filepath and its working fine with older version of pdfjs but due to digital signed pdf just updated to latest pdfjs version. 

I am using angular js 1.x and codegniter 3.x. And below is the code i am trying to use.

View Page

`<a ng-click="openViewer()" style="cursor:pointer;">Digitally_signed.pdf</a>`

angular js side

```
$scope.finalurl = btoa(BASE_URL+'/pdf_files/Digitally_signed.pdf');
$scope.openViewer = function() {
    var url = BASE_URL + '/web/pdfviewer.html?file=' + $scope.finalurl;
    window.open(url, 'newwindow', config = 'height=700, width=1000, ' +
        'toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, ' +
        'directories=no, status=no');
}
```
1. Clicking on above view page link it will open Final URL as below in new window of a browser 
http://localhost:9999/mywebapp/web/pdfviewer.html?file=aHR0cDovL2xvY2FsaG9

Above URL throws error **404 with MissingPDFException** But it works fine with older version of pdfjs like 1.5.x 

2. If i make URL like below then it works fine but i don't want to run like below
http://localhost:9999/mywebapp/web/pdfviewer.html?file=http://localhost:9999/mywebapp/pdf_files/Digitally_signed.pdf

What went wrong? (add screenshot)

![missing_pdf](https://user-images.githubusercontent.com/12459663/127284891-55ef14be-53e0-4712-9e0c-74ec8031aab5.png)

What changes do i need so that i should not expose file path, Please suggest. Thanks in advance

**Comment by Snuffleupagus** [comment]
> I am using angular js 1.x and codegniter 3.x.

Unfortunately the PDF.js contributors cannot help with frameworks such as e.g. Angular.

> so only using btoa for the filepath

Please note that the Base64 format often isn't a good idea, in general, since it's (somewhat) inefficient and leads e.g. to increased memory usage (and some browsers may even truncate long Base64 strings).

> Above URL throws error **404 with MissingPDFException** But it works fine with older version of pdfjs like 1.5.x

You can always follow https://github.com/mozilla/pdf.js#getting-the-code, and then run `git bisect` to find out where the problem first occurred. (Although I suppose that with such an ancient PDF.js version, it might not be all that practical.)

---

In order for this issue to become actionable, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by evergreen-shankar** [comment]
@Snuffleupagus Hi, window.open javascript code only used in angular js . Have a requirement like that not to expose file path. As its working fine with older version of pdfjs lib. So i was strange why its not working with latest version of pdfjs. I have downloaded prebuilt version from here https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by Snuffleupagus** [comment]
Sorry, but as explicitly mentioned in https://github.com/mozilla/pdf.js/issues/13809#issuecomment-888107776 we cannot help without a *runnable* test-case!

Closing as INCOMPLETE for now; we can re-open this once *all* of the necessary information has been provided.
