### ISSUE TITLE
Opening Links in a New Window

### ISSUE THREAD

**Issue by Balrrach** [mozilla/pdf.js#13818]
#### Problem Description:
Hello. Hyperlinks to webpages cannot be openned in vs code since the default behaviour of the pdf viewer is to try to open the link in that same tab but this can't be archived in vs code since it doesn't incoporate a web viewer. Is there an option to open a new instance of firefox when clicking on a link instead of this default behabiour.

#### Configuration:
- Web browser and its version: Last one(but it isn't relevant)
- Operating system and its version: Windows 10 [Version 10.0.19042 compilation 19042]
- PDF.js version: Last one available in vscode-pdf and LaTeX workshop
- Is a browser extension: No

#### Steps to reproduce the problem:
1. Download VS Code
2. Launch VS Code
2. Install any of the available pdf viewers on the extensions market
3. Open a pdf with a hyperlink to a webpage in VS Code
5. When clicking on the link nothing happens

####  What is the expected behavior? (add screenshot)
A new instance of firefox would open and load the link

**Comment by Snuffleupagus** [comment]
> PDF.js version: Last one available in vscode-pdf and LaTeX workshop

Sorry, but as mentioned previously (e.g. in issue #13507) we cannot provide support for either of those projects, since they're *not* officially connected with the PDF.js project; please contact those projects *directly* for support instead.

**Comment by Balrrach** [comment]
But they need to know if you provide an option to open an instance of firefox with the link, instead of the default behabiour
