### ISSUE TITLE
PDF Text is rendering multiple times in viewer

### ISSUE THREAD

**Issue by DeepakBabbar** [mozilla/pdf.js#13810]
Hi,

I am exploring this viewer with some test example. Viewer is pop up windows that render base64 string to display inline PDF and there is Cross(X) button that will close the viewer window as seen in attachment.  Problem i have is when i close the viewer window and reopen it duplicates the content and show multiple times every time i click.  I think it might be content string getting concatenated so i tried clearing variable after use but it makes no difference. 
I wonder if anyone have seen this or similar issue before and have solution for me ? Any help will be appreciated.
PS : See attachment.

![PDFViewerError](https://user-images.githubusercontent.com/88086468/127306238-167bff0a-b78d-439e-87b1-23d627754fa3.JPG)

Cheers
Deepak

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information!

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
