### ISSUE TITLE
Legacy build does not support IE 11

### ISSUE THREAD

**Issue by muhammetaltindal** [mozilla/pdf.js#13812]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/legacy/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 10
- PDF.js version: v2.9.359
- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdfjs legacy web demo in IE 11

What is the expected behavior?
<img width="1009" alt="Screen Shot 2021-07-28 at 1 59 33 PM" src="https://user-images.githubusercontent.com/1894101/127318894-92d0803d-6620-4966-8541-d59b5ab3436f.png">

What went wrong?
<img width="1006" alt="Screen Shot 2021-07-28 at 1 48 36 PM" src="https://user-images.githubusercontent.com/1894101/127317368-4a5a920f-6caa-4fa2-94e4-1f37756aa4c9.png">

Link to a viewer:
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Description:

The latest stable release where the PDF.js could initialize and display the demo PDF in IE 11 successfully seems to be pdfjs-[2.6.347-es5](https://github.com/mozilla/pdf.js/releases/download/v2.6.347/pdfjs-2.6.347-es5-dist.zip). From [pdfjs-2.7.570-es5](https://github.com/mozilla/pdf.js/releases/download/v2.7.570/pdfjs-2.7.570-es5-dist.zip) on it does not work anymore in IE 11.

Is the legacy build supposed to work for IE 11?
Or do you have any hint I could apply in order to build PDF.js from the code in order to make it compatible with IE 11?

I've tried to adjust the build script to have core-js polyfills and including a `.browserslistrc` having `ie 11` in it which solved most of the JS runtime errors but there remained still errors during the initial loading.

**Comment by Snuffleupagus** [comment]
As mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is now explicitly unsupported. (There's no simply way to bring back support manually, since we removed all IE-specific compatibility code).
