### ISSUE TITLE
Vs Code Shortcuts Not Working When Focused on the PDF Viewer

### ISSUE THREAD

**Issue by Balrrach** [mozilla/pdf.js#13820]
#### Problem Description:
Hello. In Vs Code, when focused on the PDF Viewer tab Vs Code shortcuts just don't work, instead pdf viewer shortcuts work correctly but Vs Code shortcuts just don't work, not even the ones that are not shadered by pdf viewer ones. Is there a way to fix this? Thanks.

#### Configuration:
- Web browser and its version: Last one(but it isn't relevant)
- Operating system and its version: Windows 10 [Version 10.0.19042 compilation 19042]
- PDF.js version: Last one available in vscode-pdf and LaTeX workshop
- Is a browser extension: No

#### Steps to reproduce the problem:
1. Download VS Code
2. Launch VS Code
2. Install any of the available pdf viewers on the extensions market
3. Open a pdf and click on it
5. Try any Vs Code shortcut(like Ctrl + P to look for a file in the current working directory)

####  What is the expected behavior? (add screenshot)
Not shadered commands should work just fine.

**Comment by Snuffleupagus** [comment]
Sorry, but as mentioned previously (e.g. in issue #13507) we cannot provide support for either of those projects, since they're *not* officially connected with the PDF.js project; please contact those projects *directly* for support instead.
