### ISSUE TITLE
Cannot read property 'getDestination' of null

### ISSUE THREAD

**Issue by Nawarius** [mozilla/pdf.js#13832]
Attach (recommended) or Link to PDF file here:
[lnotes.pdf](https://github.com/mozilla/pdf.js/files/6911955/lnotes.pdf)

Configuration:
- Web browser and its version: Chrome 92
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943/build/pdf.min.js and 2.0.943/web/pdf_viewer.js
- Is a browser extension: No

Steps to reproduce the problem:
The document is loaded and viewed well. But links don't work

`
           
           const eventBus = new window.pdfjsViewer.EventBus()
           const pdfLinkService = new window.pdfjsViewer.PDFLinkService({ eventBus })
            
            const pdfViewer = new window.pdfjsViewer.PDFViewer({
                container,
                eventBus,
                linkService: pdfLinkService
            })

            pdfLinkService.setViewer(pdfViewer)

            window.pdfjsLib.getDocument({ url: openPdf.link}).promise.then(doc => {

                const pdfLinkService = new window.pdfjsViewer.PDFLinkService({ eventBus })

                pdfViewer.setDocument(doc)
                pdfLinkService.setDocument(doc, null)
  
            })
`

What is the expected behavior? (add screenshot)
The ability to click on links inside the pdf and go to the desired place

What went wrong? (add screenshot)
![pdf links](https://user-images.githubusercontent.com/60738027/127755040-216b3b27-62e0-4b36-9c47-225d76ed9f5c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

[https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.943/web/pdf_viewer.js](https://cdn.jsdelivr.net/npm/pdfjs-dist@2.0.943/web/pdf_viewer.js)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.0.943/build/pdf.min.js and 2.0.943/web/pdf_viewer.js

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
> The document is loaded and viewed well. But links don't work

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
