### ISSUE TITLE
Fix intermittent `docId` unit test failure

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#13838]
The `TEST-UNEXPECTED-FAIL | checks that docIds are unique and increasing | in chrome | Expected 9 to be less than 0` unit test failed in a recent test run in https://github.com/mozilla/pdf.js/pull/13837#issuecomment-890511627, but also locally once for me. Perhaps this goes wrong because the test depends on state that might be mutated if the tests are shuffled?

/cc @Snuffleupagus since this unit test was added in https://github.com/mozilla/pdf.js/pull/13813/commits/b18620ac0f196c6fa5a9e54a53fa6b915e19e843

**Comment by timvandermeij** [comment]
Ah, maybe the problem is that the + needs to be _inside_ the paretheses at https://github.com/mozilla/pdf.js/commit/b18620ac0f196c6fa5a9e54a53fa6b915e19e843#diff-bc84ed767f5905bdf8c544c715c08e9b751e7bb1db16c8182d9de515b56bc4b6R400 since otherwise it only matches one digit in case the number is `10` for example?

**Comment by Snuffleupagus** [comment]
Whoops, sorry about this and thanks for pin-pointing the problem in https://github.com/mozilla/pdf.js/issues/13838#issuecomment-890513097.
