### ISSUE TITLE
PDF with Hebrew text is not rendering correctly

### ISSUE THREAD

**Issue by akshay-navali1** [mozilla/pdf.js#13844]
Attach (recommended) or Link to PDF file here:
PDF with Hebrew text is not rendering correctly. If the PDF is opened directly in Chrome/IE/MS Edge , it opens as expected and matches the Adobe native client. However, opening with Firefox shows the issue where the text is not rendered.

Configuration:
- Web browser and its version: Mozilla any version
- Operating system and its version: Any Os, Tested on windows
- PDF.js version: 2.9.359
- Is a browser extension:

Steps to reproduce the problem:

Open the sample document which will be attached shortly in Mozilla. 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* whenever you open an issue, since otherwise this issue unfortunately contains no actionable information (and will be closed as INCOMPLETE).
