### ISSUE TITLE
print white page on IE

### ISSUE THREAD

**Issue by w52524545** [mozilla/pdf.js#13849]
Attach (recommended) or Link to PDF file here:
[4da3d2ed-990a-4c25-b164-ad7400fca11c.pdf](https://github.com/mozilla/pdf.js/files/6923321/4da3d2ed-990a-4c25-b164-ad7400fca11c.pdf)

Configuration:
- Web browser and its version: IE11
- Operating system and its version: windows 10 20H2
- PDF.js version:  1.1.159

I opened this file and print this, But I got 4 pages with 2 white pages. 
And it works on Chrome, How can I get 2 correct pages by using IE?

**Comment by Snuffleupagus** [comment]
> Web browser and its version: IE11

As already mentioned in the FAQ, IE 11 is no longer supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 1.1.159

Please note that the quoted version number is first of all *not an official release*, secondly it must be around *six years old*, and finally only the versions listed at https://mozilla.github.io/pdf.js/getting_started/#download are officially supported.
