### ISSUE TITLE
XFA - Some fields appear to be outside of a page

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13855]
Attach (recommended) or Link to PDF file here:
[imm5710f(1).pdf](https://github.com/mozilla/pdf.js/files/6924738/imm5710f.1.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Debian

Steps to reproduce the problem:
1. Open the pdf on page 3 
2. See the 2 fields after `DÉTAILS DU TRAVAIL PRÉVU AU CANADA`

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/128031365-84b17d62-f805-43d1-9d05-e2b535efa3ef.png)

**Comment by marco-c** [comment]
Is this a regression of a recent change or has it always been there?

**Comment by calixteman** [comment]
It has been always there.
