### ISSUE TITLE
Pdf not displaying after update to the last version

### ISSUE THREAD

**Issue by mmirich** [mozilla/pdf.js#13877]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 92.0.4515.131 
- Operating system and its version: Windows 10 Professionnel 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
- PDF.js version: 2.9.359
- Is a browser extension: No

What is the expected behavior? (add screenshot)
Open the pdf 
What went wrong? (add screenshot)
Pdf Not Opened
![image](https://user-images.githubusercontent.com/63962722/128383551-0701feb8-02a9-447a-a6b2-9692c6ca4a25.png)

after changing the last version, the pdf does not want to display even if I did CTRL + SHIFT + R or CTRL + F5 to clear the cache

**Comment by Snuffleupagus** [comment]
WFM, so most likely there's something *special* about your environment that causes this for you.

Without *very detailed* steps to reproduce the problem, this unfortunately isn't really actionable as-is
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mmirich** [comment]
i update to PDF.js version: 2.9.359 from this version 
[old version.zip](https://github.com/mozilla/pdf.js/files/6940235/old.version.zip)
After updating i use the same link to check pdf and thas not work

**Comment by Snuffleupagus** [comment]
Sorry, but we'll need a *runnable* example and much more detailed information in order for this become actionable.
