### ISSUE TITLE
Pdf not displaying after update to the last version

### ISSUE THREAD

**Issue by mmirich** [mozilla/pdf.js#13876]
after changing the last version, the pdf does not want to display even if I did CTRL + SHIFT + R or CTRL + F5 to clear the cache

![image](https://user-images.githubusercontent.com/63962722/128381845-88a0fa63-bfd6-4ad5-a64f-8ac191ab894f.png)

I am using IIS with application webform

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is it's simply impossible for anyone to help!
