### ISSUE TITLE
Document information is unreadable in high contrast mode

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#13872]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1722984

![image](https://user-images.githubusercontent.com/942640/128253205-86da416c-9f3b-42d9-b1d1-7e0a272b22c1.png)

**Comment by brendandahl** [comment]
@utopianknight since you did the original high contrast stuff would you be interested in fixing this too?

**Comment by Snuffleupagus** [comment]
Is this a more general issue with the overlays, i.e. does it affect the PasswordPrompt as well?

**Comment by utopianknight** [comment]
Everything seems to be working fine with system colors (both white and black themes). I think the problem occurs when Firefox does the color overriding. So this is going to take a while. Unless someone else looks into it.
