### ISSUE TITLE
XFA - Searching a text is broken

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13878]
Since the rendering is done thanks to HTML we should likely use the "normal" firefox search feature (at least for the builtin viewer)

**Comment by Snuffleupagus** [comment]
A few quick observations/questions:
 - How would you then prevent searching from matching strings in the UI (toolbar labels, outline items, and so on), if we simply use the "normal" browser search for XFA documents?
 - How would this work for XFA Foreground documents, which may potentially require both a `textLayer` *and* a `xfaLayer`?

**Comment by brendandahl** [comment]
>     * How would this work for XFA Foreground documents, which may potentially require both a `textLayer` _and_ a `xfaLayer`

Looking at the spec, XFAF documents are are only suppose to use form controls (section `Grammar Excluded from XFAF`), so for this case we would do a regular search with the text layer.
