### ISSUE TITLE
In adobe the links inside the pdf (table of contents for example) has links to other sections of the pdf, but using pdf.js the links are not working

### ISSUE THREAD

**Issue by Prabhakaran1980** [mozilla/pdf.js#13898]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome and Version 92.0.4515.131 (Official Build) (32-bit)
- Operating system and its version: Window 10 pro
- PDF.js version: 2.8.335
- Is a browser extension: No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
Link inside the PDF should navigate to corresponding pages (inside the PDF)
What went wrong? (add screenshot)
Not working as expected
![image](https://user-images.githubusercontent.com/88898064/129386575-2f8596cf-bc04-4b61-ab71-075e5691e0d3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be valid.

> PDF.js version: 2.8.335

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Link inside the PDF should navigate to corresponding pages (inside the PDF)

It's not entirely clear here if you're referring to the outline (in the sidebar), or LinkAnnotations within the document itself.

---

Closing as INCOMPLETE for now; we can re-open this if *all* of the required information is provided.

**Comment by Prabhakaran1980** [comment]
Link Annotations within the document itself
