### ISSUE TITLE
Is it necessary to override window.print()?

### ISSUE THREAD

**Issue by tangdiying** [mozilla/pdf.js#13902]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:2.5.207
- Is a browser extension:chrome

Steps to reproduce the problem:
1. i use window.print()

What is the expected behavior? (add screenshot)
i can use window.print().
What went wrong? (add screenshot)
it overrides window.print(),so i will get error when i use window.print().
that is 'The overlay manager has not yet been initialized'
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by tangdiying** [comment]
![截屏2021-08-18 下午1 52 06](https://user-images.githubusercontent.com/45786464/129844741-36e95913-2640-455f-b6d7-6e56024a2b15.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version:2.5.207

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I use window.print()

WFM, when executing `window.print()` manually in the console at https://mozilla.github.io/pdf.js/web/viewer.html

---

Unfortunately printing isn't well supported across browsers and we're forced to resort to some hacks in order for things to mostly work, this includes overwriting `window.print`.

Please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
