### ISSUE TITLE
Warning: loadFont - translateFont failed: "FormatError: unexpected EOF in bcmap"

### ISSUE THREAD

**Issue by cjq02** [mozilla/pdf.js#13909]
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/16457309/130001731-5a27acae-e493-4cbf-813b-309f480f5556.png)

Configuration:
- Web browser and its version: Chrome 92.0.4515.131
- Operating system and its version: windows10
- PDF.js version: 2.9.359
- Is a browser extension: 

Steps to reproduce the problem:
Open the invoice PDF, the text inside is not shown

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/16457309/130001673-c98d3d84-6f2a-4c18-bd7d-a42de24ac4f8.png)

What went wrong? (add screenshot)
The following error message is displayed on the browser debugging tool console:
![image](https://user-images.githubusercontent.com/16457309/130001865-af5f8195-ce55-4e29-9215-b0645d4f2a66.png)

Reference Link：
https://github.com/mozilla/pdf.js/issues/11833#issue-604618991

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://test.file.jiujiezixun.com/assets/js/framework/lib/pdf.js/web/viewer.html?file=/file/download.json?id%3d3d2048dbe5b04963b76efb193bd8a0eb

**pdf file:**
[invoice.pdf](https://github.com/mozilla/pdf.js/files/7011488/invoice.pdf)

**Comment by cjq02** [comment]
https://github.com/mozilla/pdf.js/issues/13909#issue-974223606

**Comment by Snuffleupagus** [comment]
> **pdf file:**
> [invoice.pdf](https://github.com/mozilla/pdf.js/files/7011488/invoice.pdf)

WFM, when opening that document with https://github.com/mozilla/pdf.js#online-demo
Hence this is likely an issue in your particular implementation, e.g. that you're not providing correct CMap-parameters to the API,  however that's going to be very difficult for anyone else to debug.

> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> http://test.file.jiujiezixun.com/assets/js/framework/lib/pdf.js/web/viewer.html?file=/file/download.json?id%3d3d2048dbe5b04963b76efb193bd8a0eb

When opening that link an "Invalid PDF structure."-error is being thrown, hence it's unfortunately not even possible to reproduce the CMap-errors mentioned above.

Furthermore, please note that a complete viewer is unfortunately way too much code for anyone else to debug. We also have no way of knowing which modification you've made to the code. Finally, please note that we specifically ask for a *reduced test-case* in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by kamalakanthgr** [comment]
Facing the same issue, when using a cmap file in local.
It works fine when used cdn link for cmap file.

**Comment by WangOneOnea** [comment]
i copy  cmap,font file to local  and use local file it works  
 
![image](https://github.com/user-attachments/assets/a2b18371-608e-4df6-808e-e245bcfb169a)
