### ISSUE TITLE
Font Not loading Correctly 

### ISSUE THREAD

**Issue by devfadl** [mozilla/pdf.js#13907]
I'm running into issues that font not loaded correctly .
i use  disableFontFace = false
like below:
 let loadingTask = pdfjsLib.getDocument({
            data: this.pdfBase64string,
            disableFontFace: false
        });
when using disableFontFace = true  the file content not loaded.

Attach (recommended) or Link to PDF file here:

[pdf.pdf](https://github.com/mozilla/pdf.js/files/7010467/pdf.pdf)

Configuration:

Web browser and its version: chrome Version 92.0.4515.131 
Operating system and its version: Windows 10
PDF.js version: 2.9.359
Is a browser extension: no
What is the expected behavior?
my original file looks like that:
![image](https://user-images.githubusercontent.com/2251153/129975739-d6f29955-dfdd-47d0-893c-132681f7a644.png)

What went wrong? 
and here is the file after loading with the library 
![image](https://user-images.githubusercontent.com/2251153/129975838-272ce09b-d95c-49f0-a67c-37fa43b5c415.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Thank you.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately missing every single piece of information required to be actionable/valid.

**Comment by devfadl** [comment]
> When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately missing every single piece of information required to be actionable/valid.

thanks , just update the issue and add missing info

**Comment by Snuffleupagus** [comment]
> thanks , just update the issue and add missing info

No, unfortunately no haven't since the *first and most important* piece is still missing here:
```
Attach (recommended) or Link to PDF file here:
```
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by devfadl** [comment]
> > thanks , just update the issue and add missing info
> 
> No, unfortunately no haven't since the _first and most important_ piece is still missing here:
> 
> ```
> Attach (recommended) or Link to PDF file here:
> ```
> 
> Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Sorry for that , file Uploaded !

**Comment by Snuffleupagus** [comment]
WFM, when testing with PDF.js version `2.11.91` (as built-in to Firefox Nightly 93).

Most likely this was fixed by PR #12726, which was first released in https://github.com/mozilla/pdf.js/releases/tag/v2.10.377

**Comment by devfadl** [comment]
after more investigation , it was issue related to direction of html.
so when using direction rtl the font is not rendered correctly and it was my problem.
so you should use dir : ltr or style: direction:ltr on top of div or canvas.
afte do that the file rendered as same as original file.
