### ISSUE TITLE
Does this library require using a <canvas> tag? Can this library render a set of SVG Elements? 

### ISSUE THREAD

**Issue by joejavacavalier2001** [mozilla/pdf.js#13906]
I'm relatively new to using this library to rending objects in a browser.

Can someone explain to me how this library maps onto HTML5?

Does this library use a <canvas> element?
Can this library use a set of SVG Elements?

If SVG can be used, then I can map event listeners to those events more easily than mapping event listeners to a region of the canvas.

Sorry for being such a newbie.

-Roger

**Comment by benbro** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends
