### ISSUE TITLE
Digital signed pdf throwing error

### ISSUE THREAD

**Issue by evergreen-shankar** [mozilla/pdf.js#13910]
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version:

- Google Chrome Version 92.0.4515.107

Operating system and its version:

- Windows 10

PDF.js version:

- 2.9.359

Is a browser extension:

- No

Steps to reproduce the problem:

I was asked to try using node.js in these linked issue #13809 and below i have tried as suggested the steps.

I have cloned the **latest version** of pdfjs from [github ](https://github.com/mozilla/pdf.js) And setup using **node.js, npm** and **gulp** and run using the url suggested in github `http://localhost:8888/web/viewer.html`, 

but getting the same error.  Please find the attachment for the same.

![image](https://user-images.githubusercontent.com/12459663/129701616-5f38e9d8-2249-46be-b35e-02541244bce3.png)

**Comment by Snuffleupagus** [comment]
Please stop "spamming" the bug tracker with duplicate issues, when none of them contain enough information to be actionable!

> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable; hence why all your previous issues have been closed.

> Steps to reproduce the problem:
> 
> I was asked to try using node.js in these linked issue #13809 and below i have tried as suggested the steps.

No-one asked about Node.js, however you've been repeatedly asked to actually provide sufficient information to make the issue actionable/understandable. With neither the PDF document, nor a runnable test-case, we simply cannot help!

> but getting the same error. Please find the attachment for the same.

Huh; your screen-shot clearly shows *only a warning* and not actually an error!?

**Comment by evergreen-shankar** [comment]
@Snuffleupagus Actually pdf is confidential and can not be shared and runnable test case is just copying pdf under web folder and running the application.

**Comment by Snuffleupagus** [comment]
> Actually pdf is confidential and can not be shared

Sorry, but that means that it's impossible for us to help!

> runnable test case is just copying pdf under web folder and running the application.

No, that's not really helpful without the actual PDF file used.

**Comment by evergreen-shankar** [comment]
@Snuffleupagus Thanks for your reply, Let me recheck about sharing pdf and if gets approved i will share here.
