### ISSUE TITLE
Unload the text layer

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#13912]
I'm not sure if this was by design or not, but it appears we never fully clear out the text layer when a page cleaned up. The text layer seems to also hold on to all the divs, but then re-creates them we render is called again. This probably isn't an issue for most documents, but when scrolling for a very large document this could use a lot of memory.

**Comment by Snuffleupagus** [comment]
> but it appears we never fully clear out the text layer when a page cleaned up.

Doesn't the following code imply that we clean-up the textLayer, or am I missing something obvious here?
https://github.com/mozilla/pdf.js/blob/3c8ee25e057147b9e32ed2aef626576eae9c9d0c/web/pdf_page_view.js#L364-L374

**Comment by brendandahl** [comment]
I had some debug code that was keeping the text layer alive. Nothing to see here...
