### ISSUE TITLE
Error during font loading: unexpected EOF in  bcmap

### ISSUE THREAD

**Issue by Amiedon** [mozilla/pdf.js#13914]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:
![221754_d4fc6d26_1318254](https://user-images.githubusercontent.com/17082966/130186915-0dc80459-8a4e-4147-a1f1-17c555c0e1fe.png)

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information.
