### ISSUE TITLE
Viewer history enable/disable control is broken

### ISSUE THREAD

**Issue by Voileexperiments** [mozilla/pdf.js#13926]
Supposedly it is possible to disable pdfjs viewer restoring viewer state by setting `disableHistory` to false (is this key even documented anywhere?), but it's not working at all.

Adding `#disableHistory` to URL in the viewer does disable the history, but that's caused by a bugged handling: adding any non-empty hash to the URL will cause history to be disabled.

Meanwhile, trying to set  `disableHistory` through `defaultOptions` or `AppOptions` does nothing. The only place where it's used is inside `_initializePdfHistory`, but it isn't doing anything there either since `pdf.history` will be created regardless.

**Comment by Voileexperiments** [comment]
Relevant portion:

https://github.com/mozilla/pdf.js/blob/d02233361872d3758eb23ed394c939c4f510e2cb/web/app.js#L1226-L1242

If history is disabled `PDFViewerApplication.store` should be completely disabled.

**Comment by Snuffleupagus** [comment]
> Supposedly it is possible to disable pdfjs viewer restoring viewer state by setting `disableHistory` to false

That option only controls the *browsing history* implementation, i.e. https://github.com/mozilla/pdf.js/blob/master/web/pdf_history.js, which allows you to use the back button in the browser to navigate to a previous position after e.g. clicking on a LinkAnnotation within a PDF document.

> [...] but it's not working at all.

Yes, it most certainly does exactly what it's supposed to!

> https://github.com/mozilla/pdf.js/blob/d02233361872d3758eb23ed394c939c4f510e2cb/web/app.js#L1226-L1242

Based on the quoted code your question isn't actually about `PDFHistory` but rather about `ViewHistory` (which is a separate thing, that only stores the last position in `localStorage` and nothing else).
That implementation is controlled by the `viewOnLoad` option/preference, with the following currently supported values:
https://github.com/mozilla/pdf.js/blob/d02233361872d3758eb23ed394c939c4f510e2cb/web/app.js#L89-L93

Hence setting `viewOnLoad = 1` is sufficient to discard any view and/or browser history entries and *always* load all documents at the first page (and with default zoom values).

---

*For future reference:* When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Furthermore, this issue required some amount of "reading between the lines" to figure out what you really were asking about; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Voileexperiments** [comment]
Sorry, you did not address the issue.

> Hence setting `viewOnLoad = 1` is sufficient to discard any view and/or browser history entries and *always* load all documents at the first page (and with default zoom values).

Okay, so it is documented anywhere? Most of the viewer options are not documented at all, and it's almost impossible to decipher which option should be used for what purpose.

Also, hashtag disabling view history is still a bug. I can reproduce it like [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html#abc).

**Comment by Snuffleupagus** [comment]
> Sorry, you did not address the issue.

I answered it to the best of my ability, since as mentioned it was somewhat difficult to follow the issue. (Also, down-voting a "correct" answer probably isn't the best way to get people to assist you further...)

> Also, hashtag disabling view history is still a bug.

First of all, note that most hash parameters are *purposely* disabled by default, and shouldn't be used for anything except debugging; see https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js
Secondly, the `disableHistory` hash parameter purposely *only* maps to the AppOption with the same name and will thus *not* affect the `viewOnLoad` option.

**Comment by Voileexperiments** [comment]
I downvoted because while it answers the question, it also dodges the underlying issue of the lack of documentation about viewer configs (what config should I change to achieve anything different from default behaviour?). I am customizing the existing viewer and I find myself often needed to dive into the initialization logic itself just to understand where should I change the code. I don't think this is encouraging to customizing the default viewer.
