### ISSUE TITLE
Cannot Find /web/viewer.html

### ISSUE THREAD

**Issue by conor-f** [mozilla/pdf.js#13928]
Hello all, forgoing the template as there are no real relevant sections in it for this issue.

I am looking at including PDF previews on my site similar to [this](https://mozilla.github.io/pdf.js/web/viewer.html) example. I found I should be able to import [web/viewer.html](https://github.com/mozilla/pdf.js/blob/master/web/viewer.html) and pass it a `GET` variable `?file=https://www.example.com/filename.pdf` to view the file in browser using the above viewer. However, when I tried to import `pdfjs-dist` in my `package.json`, I cannot find nor import the `viewer.html` file.

Can anyone shed some light on this issue for me?

**Comment by Snuffleupagus** [comment]
> However, when I tried to import `pdfjs-dist` in my `package.json`, I cannot find nor import the `viewer.html` file.

That's on purpose, given that the full viewer isn't really intended to be used as-is; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

The `pdfjs-dist` repository includes viewer components in https://github.com/mozilla/pdfjs-dist/tree/master/web, which can be used to build a custom viewer; please refer to the examples in e.g. https://github.com/mozilla/pdf.js/tree/master/examples/components
