### ISSUE TITLE
diplay wrong background color

### ISSUE THREAD

**Issue by startxc** [mozilla/pdf.js#13938]
[test.pdf](https://github.com/mozilla/pdf.js/files/7065053/test.pdf)

Configuration:
- Web browser and its version: Firefox 91.0.2
- Operating system and its version: win10
- PDF.js version: 2.9.359
- Is a browser extension: 

Steps to reproduce the problem:
1. download https://github.com/mozilla/pdf.js/releases/download/v2.9.359/pdfjs-2.9.359-dist.zip
2. modify defalutUrl to my pdf file.  

What is the expected behavior? (add screenshot)
![1](https://user-images.githubusercontent.com/7018023/131091909-68843282-aee3-4677-a5ad-1682fcdf988d.png)

What went wrong? (add screenshot)
![2](https://user-images.githubusercontent.com/7018023/131092004-f747cd3f-b003-4402-b927-b03c4ba5edb8.png)

**Comment by startxc** [comment]
@timvandermeij  Hi, How is it going.

**Comment by janpe2** [comment]
The background is a shading that has an ICCBased color space. PDF.js replaces it with DeviceRGB and gray becomes too dark. Possibly a duplicate of #2856

**Comment by Snuffleupagus** [comment]
Duplicate of #2856
