### ISSUE TITLE
Softhyphen is treating as normal hyphen

### ISSUE THREAD

**Issue by a7vickey** [mozilla/pdf.js#13947]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Version 92.0.4515.159 (Official Build) (64-bit)

- Operating system and its version: Windows windows 8
- PDF.js version: latest version
- Is a browser extension:

Steps to reproduce the problem:
1. Refer the attached image, few soft hyphens are there in the file. When we are copying content using Acrobat professional it is treating them as soft hyphen and text only copying where as while copying trhough pdf.js, it is treating them as normal hyphen and additional hyphen is coming. Could you please check and give the option to avoid soft hyphen. Also confirm that how will you differentiate hard hyphen and soft hyphen?

What is the expected behavior? (add screenshot) 

What went wrong? (add screenshot) ![hyphen](https://user-images.githubusercontent.com/7369163/131340515-c0aa5573-a502-496b-8b4d-4c75feb6ea6d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Without this piece of information, this issue unfortunately isn't actionable.

> PDF.js version: latest version

Please provide the actual version *number*, since "latest" can mean any number of things and isn't really helpful.

> Refer the attached image, few soft hyphens are there in the file. When we are copying content using Acrobat professional it is treating them as soft hyphen and text only copying where as while copying trhough pdf.js, it is treating them as normal hyphen and additional hyphen is coming. Could you please check and give the option to avoid soft hyphen. Also confirm that how will you differentiate hard hyphen and soft hyphen?

This isn't all that easy to understand, and given the overall lack of information we unfortunately cannot help.

**Comment by a7vickey** [comment]
{
  "betaVersion": "2.10.377",
  "stableVersion": "2.9.359",
  "baseVersion": "156762c482a75261e631948168a65a8adb82f21a",
  "versionPrefix": "2.11."
}

**Comment by a7vickey** [comment]
Are can i post new issue ?

**Comment by a7vickey** [comment]
how to avoid hyphen for word break

**Comment by a7vickey** [comment]
Is this answer for this issue?  while copy text from pdf js hyphen copy that was wrong we need to ignore hyphen. how to stop hyphen break words
