### ISSUE TITLE
Restart the bots

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#13958]
The Linux bot appears to be unreachable and the Windows bot is showing weird intermittent rendering changes. It looks like it's best for now to restart both of them and run makeref afterwards (since we merged two PRs with reference image changes, but it doesn't seem useful to run makeref in the current state).

@brendandahl Could you restart them? Hopefully over time this will become less of an issue while we migrate to GitHub Actions.

**Comment by brendandahl** [comment]
We tried upgrading the linux bot to see if it would help with the intermittent, but it doesn't appear to have helped. I also changed the instances to use elastic ips, so the ip hopefully won't change in the future if we change instance types again.
If you have any old runs of tests/previews/etc you can still get them if you update the IP to the new one:
Windows 54.193.163.58
Linux 54.241.84.105
cc @Snuffleupagus
