### ISSUE TITLE
Slow text extraction in large documents due to cross-thread messaging overhead

### ISSUE THREAD

**Issue by robertknight** [mozilla/pdf.js#13962]
While looking into an issue with slow text extraction with a large OCR-ed PDF, I saw in Chrome's profiler that there appeared to be a lot of overhead from calls to `postMessage`.

PDF.js extracts a total of ~500,000 text items from the attached 590-page PDF. When extracting text (eg. using the search function) these text items get sent from the worker thread to the main thread in a series of ~200,000 `postMessage` calls. I checked this by adding a `message` event listener to the `Worker` instance. I then tried modifying `src/core/evaluator.js` to comment out the most frequent `enqueueChunk()` call so that it would flush items in larger batches and thus send the same data with fewer cross-thread messages. It seems to make a substantial difference in Chrome.

I'd be happy to send a PR to fix this, but I'm not sure what the best/cleanest way is to resolve this. The smallest change I can think of would be to modify the `next` callback below so that it invokes `enqueueChunk` only once every N calls. Would that break anything? Should the problem be fixed at a higher level?

## Steps to reproduce

Attach (recommended) or Link to PDF file here: [leviathan.pdf](https://github.com/mozilla/pdf.js/files/7100224/leviathan.pdf)

Configuration:
- Web browser and its version: 95.0.4621.4
- Operating system and its version: macOS 11
- PDF.js version: 0a366dda6a174292e6d109df526f835bfabf87a8
- Is a browser extension: No

Open the attached PDF in PDF.js's development server and search for the phrase "for such truth", which occurs near the very end of the document.

On my 2020 Intel MacBook Pro, testing in Chrome 95, PDF.js takes ~15 seconds to find a match.

Now apply the following diff, then reload the viewer and retry the search:

```diff
diff --git a/src/core/evaluator.js b/src/core/evaluator.js
index 90615b228..85d6325a9 100644
--- a/src/core/evaluator.js
+++ b/src/core/evaluator.js
@@ -2669,7 +2669,8 @@ class PartialEvaluator {
 
     return new Promise(function promiseBody(resolve, reject) {
       const next = function (promise) {
-        enqueueChunk();
+        // TESTING
+        // enqueueChunk();
         Promise.all([promise, sink.ready]).then(function () {
           try {
             promiseBody(resolve, reject);
```

With the above diff applied, the search returns the same result but is much faster (~3-4 seconds).

One quirk I noticed is that initial search speed is much slower (~20 seconds) if Chrome's devtools are open when the search happens. This applies with or without the above diff.

**Comment by Snuffleupagus** [comment]
> Would that break anything?

Perhaps; or at the very least it could slow things down for more "realistic" use-cases. In general it may not be great to optimize for some worst-case scenario, and in this case it *may* have negative consequences for text-extraction performance in all documents.

> On my 2020 Intel MacBook Pro, testing in Chrome 95, PDF.js takes ~15 seconds to find a match.

A more relevant data point, in my opinion, would be what the performance is in *Firefox* since that's the primary development target in this library?

> With the above diff applied, the search returns the same result but is much faster (~3-4 seconds).

*Just a FYI:* Doing that removes *all* benefit of using `ReadableStream`s and essentially reverts to the behaviour from years ago, where it's e.g. not possible to begin building of the `textLayer` on the main-thread until the *entire* page has been parsed.

**Comment by robertknight** [comment]
> A more relevant data point, in my opinion, would be what the performance is in Firefox since that's the primary development target in this library?

In Firefox the overall wall-clock time doesn't seem to vary as much. With or without the above change it subjectively feels like it takes a similar amount of time to Chrome without the patch.

Comparing profiler output from Firefox during the search shows a big difference though. Without the patch much of the time is spent in GC, and browser "Tools" and "Networking" activity triggered by `postMessage` calls:

<img width="1033" alt="pdfjs-unmodified-text-search" src="https://user-images.githubusercontent.com/2458/131889873-d11acf53-2ea4-44ce-8aef-436850099997.png">

With the patch most of the time is spent in "Idle". Subtracting the "Idle" time from the wall clock time gives roughly the same elapsed time as in Chrome with the change (3-4 seconds):

<img width="1025" alt="pdfjs-modified-text-search" src="https://user-images.githubusercontent.com/2458/131889944-56a06fd3-0872-44d1-969c-69d3c89d6099.png">

> Just a FYI: Doing that removes all benefit of using ReadableStreams and essentially reverts to the behaviour from years ago, where it's e.g. not possible to begin building of the textLayer on the main-thread until the entire page has been parsed.

I see. I assumed there was a reason for having the `enqueueChunk()` call in `next`. Maybe there is a workable hybrid between the two extremes.

**Comment by Snuffleupagus** [comment]
Based on some *very quick* testing, it looks feasible to reduce the number of `ReadableStreamDefaultController.enqueue` calls slightly by sending "small" text-chunks together. However, some care will be required to not regress overall performance (time permitting, I'll look into this later during the week).

**Comment by robertknight** [comment]
Thanks for the quick improvement 🙂
