### ISSUE TITLE
text not rendered in 'EssentialC.pdf'...

### ISSUE THREAD

**Issue by pr0gram-er** [mozilla/pdf.js#13965]
Text is not rendered in the [pdf](http://cslibrary.stanford.edu/101/EssentialC.pdf).

Configuration:
- Browser: Firefox(78.13.0esr),
- Host: Debian/Linux 5.10.46-4 (2021-08-03), on amd64,
- 3rd Party installations: Dark_Reader(4.9.34), uBlock_Origin(1.37.2),
- Default browser font: FreeSans.

**Comment by Snuffleupagus** [comment]
WFM, when using the *built-in* PDF Viewer in Firefox Nightly 93.

> Browser: Firefox(78.13.0esr),

Please re-test using the *latest* Firefox version.

**Comment by calixteman** [comment]
WFM too with Firefox 78.12.0esr in debian.

**Comment by pr0gram-er** [comment]
Sorry for wasting your precious time,
The issue was solved by enabling "Allow pages to choose their own fonts, instead of your selections above" in the font preferences.
Thanking you...
