### ISSUE TITLE
Unnecessary ternary operator in api.js

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#13963]
I just stumbled upon these lines:

https://github.com/mozilla/pdf.js/blob/804abb3786e4f09ad084d705ff9b4d770067583d/src/display/api.js#L385
```javascript
    worker = workerParams.port
      ? PDFWorker.fromPort(workerParams)
      : new PDFWorker(workerParams);
```

https://github.com/mozilla/pdf.js/blob/804abb3786e4f09ad084d705ff9b4d770067583d/src/display/api.js#L2267
```javascript
  static fromPort(params) {
    if (!params?.port) {
      throw new Error("PDFWorker.fromPort - invalid method signature.");
    }
    if (this._workerPorts.has(params.port)) {
      return this._workerPorts.get(params.port);
    }
    return new PDFWorker(params);
  }
```

In both cases, `new PDFWorker(params)` is called, so I guess you can simplify the first code snippet.

**Comment by Snuffleupagus** [comment]
Sorry, but I'm having a slightly difficult time following *exactly* what you claim to be wrong and how the code should be changed.

> Unnecessary if statement in api.js
>
> ```js
>    static fromPort(params) {
>       if (!params || !params.port) {
>         throw new Error("PDFWorker.fromPort - invalid method signature.");
>       }
>       if (pdfWorkerPorts.has(params.port)) {
>         return pdfWorkerPorts.get(params.port);
>       }
>       return new PDFWorker(params);
>     }
> ```

Which of these `if` statement do you think is wrong?
(Also, the code that you've included above doesn't actually agree *entirely* with what's present in the latest version of the `src/display/api.js` file.)

**Comment by stephanrauh** [comment]
It's definitely not wrong. I just observed that the ternary operator 
```
worker = workerParams.port
      ? PDFWorker.fromPort(workerParams)
      : new PDFWorker(workerParams);
```
can be simplified to 
```
worker = new PDFWorker(workerParams);`
```

**Comment by stephanrauh** [comment]
You're right, the code I've pasted stems from the 2.10 branch. I've updated the code snippet. The null-safe operators makes our live so much easier, thanks for starting to use it!

**Comment by Snuffleupagus** [comment]
> I just observed that the ternary operator
> [...]
> can be simplified to

No it can't, since you've not considered what happens for *repeated* `getDocument` calls!
Please take a look at the `PDFWorker`-constructor, and you'll see why that doesn't work; closing as INVALID since there's nothing to fix here.

> The null-safe operators

I'm guessing that you mean the "optional chaining"-operator (i.e. `?.`) here. (Sorry for being pedantic, but I find it helps reduce confusion a great deal by using "official" names of language features.)
