### ISSUE TITLE
Warning: JPX: Trying to recover from: "JPX error: Out of packets"，cannot render pdf correctly

### ISSUE THREAD

**Issue by zeayal** [mozilla/pdf.js#13978]
Attach (recommended) or Link to PDF file here:

[Issue File.pdf](https://github.com/mozilla/pdf.js/files/7112957/Issue.File.pdf)

Configuration:
- Web browser and its version: Chrome  Version 92.0.4515.159 (Official Build) (x86_64)
- Operating system and its version: mac OS Catalina 10.15.7  &  Win10
- PDF.js version: pdfjs-2.10.377  &   (PDF.js: 2.9.359)
- Is a browser extension: no

Steps to reproduce the problem:
1. please use pdfjs-2.10.377 to view the issue file
2. you will see the problem

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/28499365/132151931-c6f46c89-4942-435f-8b39-f14027a6ae7b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by zeayal** [comment]
I run master, it's fix this error. When will it be released?

**Comment by linfangrong** [comment]
https://github.com/mozilla/pdf.js/pull/13698 was fixed.
