### ISSUE TITLE
Page with empty OCGs entry rendered blank

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#13971]
Attach (recommended) or Link to PDF file here:
[PDFBOX-5275-p5.pdf](https://github.com/mozilla/pdf.js/files/7109095/PDFBOX-5275-p5.pdf)

Configuration:
- Web browser and its version: FF 91.0.2
- Operating system and its version: Windows 10.0.19043.1165
- PDF.js version: latest (tried with https://mozilla.github.io/pdf.js/web/viewer.html )

Steps to reproduce the problem:
1. open the file
2.

What is the expected behavior? Displays a plant

What went wrong? Displays blank page

See also
https://issues.apache.org/jira/browse/PDFBOX-5275
which had the same problem, the cause was bad handling of an empty OCGs entry

![grafik](https://user-images.githubusercontent.com/6665575/132079956-c48921bf-6dbb-4e89-886e-4301d955ee35.png)

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!
