### ISSUE TITLE
Integration tests failed on a localized environement

### ISSUE THREAD

**Issue by SamyCookie** [mozilla/pdf.js#13987]
Hi,

I try to execute PDF.js `gulp test` target and I got that issue:

```
[...]

### Running integration tests
Server running at http://127.0.0.1:38239/
Started
.TEST-PASSED | must check that first text field has focus
[...]
.TEST-PASSED | must highlight text in the right position
FTEST-UNEXPECTED-FAIL | must search xfa correctly


Failures:
1) find bar highlight all must search xfa correctly
  Message:
    Expected 'Occurrence 1 sur 7' to equal '1 of 7 matches'.
  Stack:
    Error: Expected 'Occurrence 1 sur 7' to equal '1 of 7 matches'.
        at <Jasmine>
        at /home/samuel/src/pdf.js/test/integration/find_spec.js:96:30
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)

31 specs, 1 failure
Finished in 60.326 seconds

Run 31 tests
OHNOES!  Some integration tests failed!
  1 of 31 failed
integration tests runtime was 62.3 seconds
[14:31:34] Finished 'runTest' after 1.6 min
[14:31:34] Finished 'test' after 1.87 min
```
I ran the tests with a french `LANG` environment. If I run tests with a non localized environment (e.g. with command `unset -u LANG gulp test`), all integration tests works.

Request : find a way to disable locale environment before executing the integration tests...
edit:  ... or find a way to compare generated strings with translated strings in integration tests

Have a good day !

**Comment by calixteman** [comment]
I confirm the bug:
https://github.com/mozilla/pdf.js/blob/master/test/integration/find_spec.js#L96
the string here is not localized.

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!
