### ISSUE TITLE
Some text mission in canvas and viewer, but work fine in viewer.html

### ISSUE THREAD

**Issue by georgezouq** [mozilla/pdf.js#13982]
Some text mission in canvas and PDFViewer, but it work in viewer.html.

In my code:

<img width="811" alt="截屏2021-09-07 下午5 54 07" src="https://user-images.githubusercontent.com/5990860/132325360-6a3a8bb3-b4df-4f44-a186-84c80c603915.png">

In official demo: https://mozilla.github.io/pdf.js/web/viewer.html?file=https://img.txqn.huohua.cn/1630639398855teach_guide.pdf

<img width="1500" alt="截屏2021-09-07 下午5 55 41" src="https://user-images.githubusercontent.com/5990860/132325195-585c38d7-d288-4229-95f4-614dc1b75309.png">

I tried two different ways, first use canvas:

```javascript
componentDidMounted() {
    const pdf = await PdfJsLib.getDocument({
      url: fileUrl,
      cMapUrl: 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.2.228/cmaps/',
      cMapPacked: true,
    }).promise

    this.renderPage(pdf, 1)
}
  renderPage = (pdfDoc, num) => {
    pdfDoc.getPage(num).then((page) => {
      let canvasId = 'pdf-viewer-' + num
      const $canvas = document.createElement('canvas')
      $canvas.setAttribute('id', canvasId)

      document.getElementById('viewer').append($canvas)
      // let canvas = document.getElementById(canvasId)
      let ctx = $canvas.getContext('2d')
      let scale = 800 / 595

      let viewport = page.getViewport({ scale: scale })

      $canvas.height = viewport.height
      $canvas.width = viewport.width

      let renderContext = {
        canvasContext: ctx,
        viewport: viewport,
      }
      let renderTask = page.render(renderContext)

      renderTask.promise.then(() => {
        if (num < pdfDoc.numPages) {
          this.renderPage(pdfDoc, num + 1)
        }
      })
    })
  }
```

It did not work, then I try `PDFViewer`, it still did not work. 

```
const pdfViewer = new pdfjsViewer.PDFViewer({
  container,
  viewer,
  eventBus,
  inkService: pdfLinkService,
  findController: pdfFindController,
  scriptingManager: pdfScriptingManager,
  enableScripting: true, // Only necessary in PDF.js version 2.10.377 and below.
})

pdfLinkService.setViewer(pdfViewer)
pdfScriptingManager.setViewer(pdfViewer)
pdfViewer.setDocument(pdf)
```

And I use pdf.js within electron, I don't know if I need to add some configuration?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is unfortunately missing too many of the required details to be actionable.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> And I use pdf.js within electron, I don't know if I need to add some configuration?

Sorry, but we cannot provide support for various frameworks such as e.g. "Electron".

**Comment by georgezouq** [comment]
@Snuffleupagus Thanks for your reply, I think Electron may not the issues. It's just a Chrome browser. In my case, in some pdf files, every text renders just fine, every text in right place. But only some special pdf file mission texts. And I just don't know what's the difference between those files. Any idea about pdf format or configuration issues?

**Comment by Snuffleupagus** [comment]
> Any idea about pdf format or configuration issues?

Without a *runnable* (and reduced) test-case it's simply impossible for anyone to help, hence why we specifically ask for that!

The only suggestion, given the lack of details, is to check that there's no errors or warnings printed in the console.

**Comment by zhanghr897** [comment]
Did you find a solution, I also encountered the same problem

**Comment by zhanghr897** [comment]
Thank you for replying to me soon. I wonder if you have a problem with incomplete text rendering when using the electron framework?
