### ISSUE TITLE
Ultra blurry texts on the Example files on latest Chrome

### ISSUE THREAD

**Issue by handhikadj** [mozilla/pdf.js#13981]
Attach (recommended) or Link to PDF file here: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Chrome 93
- Operating system and its version: Mac M1
- PDF.js version: 2.9.359
- Is a browser extension: nope

Steps to reproduce the problem:
1.  Go to https://jsfiddle.net/pdfjs/wagvs9Lf/
2. compare it with the original PDF file using built-in Chrome PDF viewer: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

What is the expected behavior? (add screenshot)
Texts look perfect
![image](https://user-images.githubusercontent.com/22522638/132319863-b8c317a9-b01f-4ad6-a30b-f5aa1417ccc9.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/22522638/132319702-4affca0d-463a-423c-83e3-b7e5acbc43e4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Added Note:
I have a program which utilizes pdf.js and end up having the same problem

**Comment by Snuffleupagus** [comment]
I'm assuming that you can't reproduce this with the demo viewer, see https://github.com/mozilla/pdf.js#online-demo

> Go to https://jsfiddle.net/pdfjs/wagvs9Lf/

Your code doesn't seem to handle HiDPI screens, which can thus result in blurriness.

You'll either have to implement that *manually*, or a simpler solution would be utilize the "viewer components" which handle HiDPI automatically; please refer to the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components

**Comment by handhikadj** [comment]
any reference how to handle it manually?

**Comment by Snuffleupagus** [comment]
> any reference how to handle it manually?

Looking at how `outputScale` is handled in https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js might be *some* help, however PR #13981 might be slightly easier.
