### ISSUE TITLE
XFA Pdf File unable to load prefilled values

### ISSUE THREAD

**Issue by anshukaira** [mozilla/pdf.js#13994]
Attach (recommended) or Link to PDF file here:
[Form_MGT-14-try-1.pdf](https://github.com/mozilla/pdf.js/files/7138335/Form_MGT-14-try-1.pdf)

Configuration:
- Web browser and its version: Google chrome, Mozilla Nightly
- Operating system and its version: Windows 10
- PDF.js version: 2.11.213 (tested on Demo available on github repo)
- Is a browser extension: -

Steps to reproduce the problem:
1.  Fill the pdf, (try to fill email address) or try to open the attached filled pdf in Demo/pdf.js 

What is the expected behavior? (add screenshot)
Pdf should be filled. (Email address in case of above pdf)
![image](https://user-images.githubusercontent.com/46723211/132728898-a0eb01ff-1334-4da3-891c-55e64b44ed07.png)

What went wrong? (add screenshot)
Unable to see the prefilled values.
![image](https://user-images.githubusercontent.com/46723211/132728865-e7b29617-e0b1-4235-8843-aa4d9ff1642b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
None

--

**Comment by Snuffleupagus** [comment]
> PDF.js version: v 10 (tested on Demo available on github repo)

*For your information:* That version number doesn't exist (or make sense), as of this writing [the demo viewer](https://github.com/mozilla/pdf.js#online-demo) uses version `2.11.213`.

**Comment by anshukaira** [comment]
ok. thanks. updated the version in description
