### ISSUE TITLE
modify PDF Suggestion

### ISSUE THREAD

**Issue by KillerBOSS2019** [mozilla/pdf.js#13990]
Configuration:
- Web browser and its version: MS Edge latest 9/8/2021
- Operating system and its version: Win10 1908
- PDF.js version: http://mozilla.github.io/pdf.js/build/pdf.js
- Is a browser extension: No

Suggestion:
    is it possible to make the viewer to save the changes? like when I rotate the pdf it will save as what it looks like in the viewer. Currently when I rotate the pdf it wont safe to it's file it when and when I download it, It will give me the old PDF that does not have the changes

**Comment by Snuffleupagus** [comment]
> is it possible to make the viewer to save the changes?

Interactive forms that you have filled-in can be saved, but that's it.

> like when I rotate the pdf it will save as what it looks like in the viewer.

That'd require *arbitrary* editing of the PDF data, which this is a use-case that this library is not intended for; as clearly mentioned [at the top of the README](https://github.com/mozilla/pdf.js#pdfjs-) (emphasis mine):
> PDF.js is a Portable Document Format (PDF) *viewer* that is built with HTML5.
