### ISSUE TITLE
Is there anyway to disable the Spread Mode options on the UI?

### ISSUE THREAD

**Issue by quanengineering** [mozilla/pdf.js#14011]
Hi,

I know that we can set the default Spread mode option to be loaded like this:

```
    defaultPreferences = Promise.resolve({
      "cursorToolOnLoad": 0,
      "defaultZoomValue": "",
      "disablePageLabels": false,
      "enablePermissions": false,
      "enablePrintAutoRotate": false,
      "enableWebGL": false,
      "externalLinkTarget": 0,
      "historyUpdateUrl": false,
      "ignoreDestinationZoom": false,
      "pdfBugEnabled": false,
      "renderer": "canvas",
      "renderInteractiveForms": true,
      "sidebarViewOnLoad": -1,
      "scrollModeOnLoad": -1,
      "spreadModeOnLoad": 1,
      "textLayerMode": 1,
      "useOnlyCssZoom": false,
      "viewOnLoad": 0,
      "disableAutoFetch": false,
      "disableFontFace": false,
      "disableRange": false,
      "disableStream": false
    });
```

But I wonder, are there any ways to completely disable or hide the Spread Mode options on the toolbar?

**Comment by Snuffleupagus** [comment]
> But I wonder, are there any ways to completely disable or hide the Spread Mode options on the toolbar?

Not without modifying the HTML (and JavaScript) code; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
