### ISSUE TITLE
Intermittent bug with XFA test on the bots

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14014]
I ran `makeref` on the linux bot using X11 forwarding and I managed to get a [profile](https://share.firefox.dev/3hnn0aM) when Firefox hung. For information, I found nothing neither in the console nor in the terminal nor in network panel which helped me to guess what was wrong.
I  added few `console.log` to try to figure out where the hang happened and it was during `toHTML`:
https://github.com/mozilla/pdf.js/blob/064c21d360dd5a8bd0c9cfc6f16d4c135e7d106c/src/core/xfa/factory.js#L43
and so I finally added a `setTimeout(() => console.log(node.constructor.name), 10000)` + a `clearTimeout` around the call to `toHTML`: https://github.com/mozilla/pdf.js/blob/master/src/core/xfa/xfa_object.js#L370 (and the same around the `toHTML` in template.js file).
And I ran `makeref` in a `while true` during 8 hours and no hang... :(

About the profile, from @gabrielesvelto: "Firefox isn't doing nothing but it's waiting for an event in main event loop".

**Comment by calixteman** [comment]
@Snuffleupagus, @timvandermeij, if you've any idea to try something which could help to figure out what's wrong please propose.

**Comment by Snuffleupagus** [comment]
One thing that I've noticed is different between XFA documents and "regular" documents, is that the XFA documents are parsed all once. As far as I understand the data structure of XFA documents basically force this, however I do wonder if this is *maybe* somehow related to these problems!?

Note how for "regular" documents, during both parsing and rendering (see `src/core/evaluator.js` and `src/display/canvas.js`), we'll divide the parsing/rendering into small chunks and repeatedly defer to the event loop to avoid long running parsing/rendering from hanging the browser.

*Hence my, possibly dumb, idea:* Would it be possible to make the XFA parsing *slightly* asynchronous, for example by deferring to the event loop *after each parsed page*?

**Comment by calixteman** [comment]
@Snuffleupagus, I don't understand why you could be right but it's definitely something I want to try.
So I think it should be possible to do that in using transforming:
https://github.com/mozilla/pdf.js/blob/6a15973a1b26288f981d971fab1f54bb4c98d8be/src/core/xfa/template.js#L5398
into a generator function to yield each page which could allow us to delay the conversion for the next page in using a setTimeout. Having a generator function would help to save and restore the state we were before yielding a page.
