### ISSUE TITLE
Only blank page rendered on Firefox Nightly

### ISSUE THREAD

**Issue by TyDraniu** [mozilla/pdf.js#14029]
Attach (recommended) or Link to PDF file here:  [exemption-letter.pdf](https://github.com/mozilla/pdf.js/files/7171426/exemption-letter.pdf)

Configuration:
- Web browser and its version: Firefox 94 Nightly
- Operating system and its version: Win 10

Steps to reproduce the problem:
1.  Open the attached file. No content has been rendered.

**Comment by Snuffleupagus** [comment]
WFM, using the *latest* Nightly on Windows; hence this is most likely is a duplicate https://bugzilla.mozilla.org/show_bug.cgi?id=1730598 which has already been fixed.

Please make sure that you're actually using the *very latest* Nightly!
