### ISSUE TITLE
Checkbox is not checked when it must be

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14021]
Attach (recommended) or Link to PDF file here:
[docOficialPDF.php.pdf](https://github.com/mozilla/pdf.js/files/7159923/docOficialPDF.php.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: linux debian
- PDF.js version: built-in viewer
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the pdf page 2
2. Checkbox "Alta" in section 2 must be checked

It works fine with evince.

**Comment by marco-c** [comment]
Is this the same as https://bugzilla.mozilla.org/show_bug.cgi?id=1722036?

**Comment by calixteman** [comment]
@marco-c, no.
Here the `N` dictionary is empty and normally it shouldn't:
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=397

So it's easy here to add default `/Off` and `/Yes` but in order to print we need to create a default stream to render the checked checkbox.
