### ISSUE TITLE
Images feature from Acrobat Reader

### ISSUE THREAD

**Issue by hitman4an** [mozilla/pdf.js#14020]
Hello! We need that pdf.js support "change images" feature from Acrobat Reader like at video.
Is it planned in new versions?
[Сувенирка.pdf](https://github.com/mozilla/pdf.js/files/7159360/default.pdf)

https://user-images.githubusercontent.com/23082585/133207571-55995903-a3d5-42c2-a476-85546248d19d.mp4

**Comment by Snuffleupagus** [comment]
> Is it planned in new versions?

No, nothing like that is planned since it seems very much like an edge-case feature; closing as WONTFIX.
