### ISSUE TITLE
setting externalLinkTarget has no effect -> Open link in new Tab does not work anymore

### ISSUE THREAD

**Issue by JanAckermann** [mozilla/pdf.js#14033]
Description:

Since upgrading from v2.5 to v2.9.359 configuration for externalLinkTarget won't be respected anymore.
So I was able to open links in a new tab, which is not possible anymore. 

Attach (recommended) or Link to PDF file here:

[basic-link-1.pdf](https://github.com/mozilla/pdf.js/files/7183594/basic-link-1.pdf)

Configuration:
- Web browser and its version: Chromium Version 91.0.4472.114 (Official Build) for Linux Mint (64-bit)
- Operating system and its version: Linuxmint 20.1 ulyssa
- PDF.js version: v2.9.359
- Is a browser extension: no

Steps to reproduce the problem:
1. Set external link target to 2

Code:
```
document.addEventListener('webviewerloaded', deferredViewerConfig, true);

function deferredViewerConfig() {
pdfjsLib.externalLinkTarget = 2;
//or
PDFViewerApplicationOptions.set('externalLinkTarget', 2);
}
```

What is the expected behavior? (add screenshot)
Target should be `_blank`

What went wrong? (add screenshot)
Link `target` in a tag is `_top`
![image](https://user-images.githubusercontent.com/26169327/133742376-1d451005-079d-48ed-b035-f411201482ac.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by JanAckermann** [comment]
FYI:
this might be prevented due to this line of code:
https://github.com/mozilla/pdf.js/blob/9b42ae9612d3fbd1a88e5fced84bd586fadb936a/web/app.js#L279

The pdfjs is actually running  in an iframe

**Comment by Snuffleupagus** [comment]
> this might be prevented due to this line of code:

No it won't, since that code doesn't run when `externalLinkTarget` has been set to a non-default value:
https://github.com/mozilla/pdf.js/blob/d6a27860e3aee5cb27ef9a1791d61be7a73b84ee/web/app.js#L274-L277

It's much more likely to be the preferences that are overriding the option that you've set. To avoid that, you can disable the reading of all preferences by setting `PDFViewerApplicationOptions.set('disablePreferences', true);` in your "webviewerloaded" event handler.

Closing as answered; if this isn't enough to fix the problem please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by JanAckermann** [comment]
@Snuffleupagus thank you, this did the trick :) 
Note: `PDFViewerApplicationOptions.set('disablePreferences', true);`  won't work with version v2.10 beta

**Comment by Snuffleupagus** [comment]
> Note: `PDFViewerApplicationOptions.set('disablePreferences', true);` won't work with version v2.10 beta

Huh, I *really* don't understand this sentence since the option in question was first introduced all the way back in PDF.js release `2.1.266`.
