### ISSUE TITLE
Setting theme programmatically (Question)

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#14059]
Hi, is it possible to set the theme programmatically?

Configuration:
- Web browser and its version: Chrome Version 93.0.4577.82 
- Operating system and its version: Windows 10 21H1
- PDF.js version: '2.9.359'
- Is a browser extension: No

Steps to reproduce the problem:
How to set theme programmatically. Is this possible? I tried PDFViewerApplicationOptions.set('viewerCssTheme', 1); or value 2 but nothing happens. Or is there something else lacking that needs to be called in order for the theme to take effect?

What is the expected behavior? (add screenshot)
If os has light theme, by using PDFViewerApplicationOptions.set('viewerCssTheme', 2); the PDF.js viewer should be dark themed.

What went wrong? (add screenshot)
If os has light theme, and PDFViewerApplicationOptions.set('viewerCssTheme', 2); is called, it does not set to dark theme.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
None

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
In the browser console setting `viewerCssTheme` does require a reload, but if you set it programmatically it should work if you do it soon enough. As explained above, it's not possible for us to debug this without a running example unfortunately.

**Comment by chitgoks** [comment]
Seems like this has something to do with my other code. 

PDFViewerApplicationOptions.set('viewerCssTheme', 1);, (light mode) works ok.

**Comment by WelterDevelopment** [comment]
For .NET developers who stumble over this issue in order to find out how to change the PDF.js theme e.g. within a WebView2 (WinUI 3) control, here is my workaround:
C#:
``` csharp
private async void PDFjsViewerWebView_CoreWebView2Initialized(WebView2 sender, CoreWebView2InitializedEventArgs args)
{
  sender.CoreWebView2.Settings.AreHostObjectsAllowed = true;
  sender.CoreWebView2.Settings.IsScriptEnabled = true;
  string path = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
  sender.CoreWebView2.SetVirtualHostNameToFolderMapping("pdfjs", path, CoreWebView2HostResourceAccessKind.Deny);
  sender.CoreWebView2.DOMContentLoaded += async (a, b) => { await PDFjsViewerWebView.ExecuteScriptAsync($"setTheme('{ActualTheme.ToString()}')"); };
  sender.Source = new("https://pdfjs/web/viewer.html");
}
```
Code to add at the end of viewer.js:
``` javascript
setTheme = function (theme) {
 if (theme == 'Dark') {
  PDFViewerApplicationOptions.set('viewerCssTheme', 2);
 }
 else {
  PDFViewerApplicationOptions.set('viewerCssTheme', 1);
 }
 PDFViewerApplication._forceCssTheme();
};
```

**Comment by nocin** [comment]
Thanks @WelterDevelopment!

**Comment by soyxan** [comment]
`PDFViewerApplication._forceCssTheme();` gives the following error in version v4.0.269
`Uncaught TypeError: PDFViewerApplication._forceCssTheme is not a function`

**Comment by calixteman** [comment]
You could try with:
`document.documentElement.classList.add("is-light")`
or with `is-dark` in the generic viewer:
https://mozilla.github.io/pdf.js/web/viewer.html

FYI, we removed `_forceCssTheme` because it was a bit broken since we use nested css stuff:
https://github.com/mozilla/pdf.js/pull/17222
But we added back the feature:
https://github.com/mozilla/pdf.js/pull/17293
