### ISSUE TITLE
get HTML in node.js

### ISSUE THREAD

**Issue by CyberShanks** [mozilla/pdf.js#14060]
**Question:** pdf.js render PDF using HTML in the browser, is it possible to do the same in node.js without using anything like puppeteer? I need to get HTML from a PDF(base64) somehow?

**Comment by Snuffleupagus** [comment]
See e.g. https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js, but please note that caveat in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends about the SVG-backend being unsupported/unstable.
