### ISSUE TITLE
Additional Learning Resources docs update

### ISSUE THREAD

**Issue by henrywarhurst** [mozilla/pdf.js#14062]
In the [Additional Learning Resources](https://github.com/mozilla/pdf.js/wiki/Additional-Learning-Resources) Wiki page, the link to `Summary of the PDF file format:` is broken. 

A working link to what appears to be the same page is https://planetpdf.com/navigating-the-internal-structure-of-a-pdf-document/

**Comment by timvandermeij** [comment]
Thank you for reporting this! I have updated the wiki page to point to the correct website now from the Web Archive since the new link you posted above sadly only contains page 1 from 6; it looks like the other ones got lost on that website.
