### ISSUE TITLE
adding form fields to pdf with pdf.js

### ISSUE THREAD

**Issue by dolphinsd** [mozilla/pdf.js#14075]
Do you know of any library that is open source that is integrated with pdf.js to add fields likes text, images, dates to pdf files in viewer? Thanks a lot for a tip or direction.

**Comment by Snuffleupagus** [comment]
> Do you know of any library that is open source that is integrated with pdf.js to add fields likes text, images, dates to pdf files in viewer?

While there's probably a fair number of PDF file *creation* libraries out there, personally I cannot recall having heard of one that integrates directly with the PDF.js library (or its default viewer).

Furthermore, with this being first and foremost a *bug tracker*, please note that we unfortunately cannot provide suggestions or recommendations for other software here.

**Comment by dolphinsd** [comment]
@Snuffleupagus sorry to pollute your threads with question. I could not find any useful forums for pdf.js
