### ISSUE TITLE
Cross origin problem

### ISSUE THREAD

**Issue by valiantboymaksud** [mozilla/pdf.js#14086]
i want to show pdf from drive, but i can't show. I also enable access-control-allow-origin. After that, it show me different error in network tab, "Provisional headers are shown" . How to fix it?

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr, which is the only help we can realistically provide given the complete lack of any actionable information. (And this doesn't really look like a bug in the PDF.js library/viewer.)

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes (easily) actionable.
Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
