### ISSUE TITLE
Provisional header are shown

### ISSUE THREAD

**Issue by valiantboymaksud** [mozilla/pdf.js#14089]
<img width="1020" alt="Screen Shot 2021-09-27 at 10 53 33 PM" src="https://user-images.githubusercontent.com/39328011/135007569-a76d3d74-0186-4edc-afa5-e9f82af4a25b.png">

Using the latest version.

I want to load pdf from google drive, but it fetches failed. I added required headers such as allow-control-access-origin, but the same issue. Please look at the attachment, and please anyone give me a solution.
Thanks.

**Comment by Snuffleupagus** [comment]
Duplicate of #14086

**Comment by valiantboymaksud** [comment]
I am unable to achieve my goal.
