### ISSUE TITLE
`getOutline` of the legacy build can't get the correct outline info for some pdf

### ISSUE THREAD

**Issue by kpkonghk01** [mozilla/pdf.js#14082]
Attach (recommended) or Link to PDF file here:
https://www1.hkexnews.hk/listedco/listconews/sehk/2017/1215/ltn20171215029.pdf

Configuration:
- Web browser and its version: node v14.17.0
- Operating system and its version: ubuntu 20.04
- PDF.js version: pdfjs-dist 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. Download the pdf mentioned above
2. run this script
```
const CMAP_URL = `${__dirname}/node_modules/pdfjs-dist/cmaps/`;
const CMAP_PACKED = true;
const STANDARD_FONT_DATA_URL = `${__dirname}/node_modules/pdfjs-dist/standard_fonts/`;

const pdfjs = require("pdfjs-dist/legacy/build/pdf.js");
const { readFileSync } = require("fs");

const filePath = `./ltn20171215029.pdf`;

let dataBuffer = readFileSync(filePath);

pdfjs
  .getDocument({
    data: dataBuffer,
    cMapUrl: CMAP_URL,
    cMapPacked: CMAP_PACKED,
    standardFontDataUrl: STANDARD_FONT_DATA_URL,
  })
  .promise.then(async (pdf) => {
    const outline = await pdf.getOutline();

    console.log(outline);
  });
```
3. notice that the `dest` property of outline info is malformed

What is the expected behavior? (add screenshot)
Expect getting normal `dest` in the form of something like
```
  dest: [
    [Object: null prototype] { num: 76, gen: 0 },
    [Object: null prototype] { name: 'XYZ' },
    null,
    null,
    null
  ]
 ```

What went wrong? (add screenshot)
The `dest` I got is like
```
    dest: 'þÿ\x00M\x00K\x003\x002',
```
which is not able to pass to the `getPageIndex` method

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by kpkonghk01** [comment]
Also, I don't know if it is an issue:

The example
https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js
is using an option `standardFontDataUrl`, but I can't find the type definition in `pdfjs-dist/types`

**Comment by Snuffleupagus** [comment]
> The `dest` I got is like
> 
> ```
>     dest: 'þÿ\x00M\x00K\x003\x002',
> ```
> 
> which is not able to pass to the `getPageIndex` method

That's not a bug, since it's a *named* destination rather than an explicit one; please refer to https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.1947713
Furthermore, if you open the document with [the demo viewer](https://github.com/mozilla/pdf.js#online-demo) you'll notice that the outline works as intended.

In order convert named destinations into explicit ones; please use https://github.com/mozilla/pdf.js/blob/93ed4bfa119fe82c1fe1fe9cd7d08b1ae719b49e/src/display/api.js#L778-L786
