### ISSUE TITLE
How to get raw data by page?

### ISSUE THREAD

**Issue by nishitaku** [mozilla/pdf.js#14094]
I would like to read a multi page pdf file, and get serveral page raw data.
Instead of `PDFDocumentProxy.getData()` to retrieve the raw data of the whole file.

**Comment by Snuffleupagus** [comment]
That's not something that the PDF.js library supports, nor will support in either.

Please keep in mind that given how PDF documents are structured internally, there's no *simple* way to extract individual pages. Doing so requires a lot of parsing, thus essentially creating one (or more) new PDF document(s) with the required data. Hence that's basically PDF *editing*, which [as explained in the README](https://github.com/mozilla/pdf.js#pdfjs-) isn't what the PDF.js library is intended for:
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.
>
> PDF.js is community-driven and supported by Mozilla. Our goal is to create a general-purpose, web standards-based platform for parsing and rendering PDFs.
