### ISSUE TITLE
GulpUglifyError: unable to minify JavaScript with pdf.js 2.10.377

### ISSUE THREAD

**Issue by quiram** [mozilla/pdf.js#14102]
_Note: I'm actually using [pdfj-dist](https://github.com/mozilla/pdfjs-dist), but that project doesn't have an issues section and it looks like it's just a distribution-ready package of this project, so raising the issue here._

Attach (recommended) or Link to PDF file here:

No PDF file, this is compilation error. I understand that this could be an issue with [gulp-uglify](https://github.com/terinjokes/gulp-uglify) and/or with [uglify-js](https://github.com/mishoo/UglifyJS), but since there was no problem with the previous version (2.9.359) and I haven't changed versions of gulp-uglify nor uglify-js, I thought this should be the first check.

Configuration:
- Web browser and its version:  N/A
- Operating system and its version: macOS Big Sur 11.6 (20G165)
- PDF.js version: 2.10.377
- Is a browser extension: N/A

Steps to reproduce the problem:
1.  Create a JavaScript file that makes use of pdfjs-dist
2. Try to uglify that file using gulp-uglify.

What is the expected behavior? (add screenshot)
minify without errors

What went wrong? (add screenshot)
```
[INFO] [10:34:10] Starting 'pdf-viewer-js'...
[INFO] [10:34:23] 'pdf-viewer-js' errored after 13 s
[INFO] [10:34:23] GulpUglifyError: unable to minify JavaScript
[INFO] Caused by: TypeError: self.name.print is not a function
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by Snuffleupagus** [comment]
First of all, please note that `pdfjs-dist` already provides minified builds; see e.g. https://github.com/mozilla/pdfjs-dist/tree/master/build and look for files whose names end with `.min.js`.
Secondly, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified, the only minifier that we support is Terser (which is used to produce the files mentioned above).

All-in-all, we unfortunately cannot really provide much assistance here; please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by quiram** [comment]
Thanks @Snuffleupagus, and my apologies if raising the issue wasn't the right thing to do; to be honest JavaScript is not my forte and I wasn't entirely sure where to go.

I know you said you cannot provide much assistance but you've actually been very helpful, I really appreciate the pointers.
