### ISSUE TITLE
renderView: "Error: Unknown IR type: p"

### ISSUE THREAD

**Issue by kfyidrig** [mozilla/pdf.js#14113]
Configuration:
- nodejs: v16.4.0
- Operating system and its version: win 19043.1266
- PDF.js version: 2.10.377 ( pdfjs-dist: "^2.10.377")
- Is a browser extension: no

Steps to reproduce the problem:
1. In `examples\node` run `node  pdf2svg.js`
2. The PDF provided in the example will have conversion errors on page 11

What went wrong? 
In nodejs:
```shell
$ node pdf2svg.js
# Document Loaded
Number of Pages: 14

# Page 1
Size: 612x792

Page: 1
# Page 2
Size: 612x792

Page: 2
# Page 3
Size: 612x792

Page: 3
# Page 4
Size: 612x792

Page: 4
# Page 5
Size: 612x792

Page: 5
# Page 6
Size: 612x792

Page: 6
# Page 7
Size: 612x792

Page: 7
# Page 8
Size: 612x792

Page: 8
# Page 9
Size: 612x792

Page: 9
# Page 10
Size: 612x792

Page: 10
# Page 11
Size: 612x792

Error: Error: Unknown IR type: p
```
The PDF file has 14 pages in total, and page 11 cannot be converted successfully.

In browser:

The PDF provided in the example will have conversion errors on page 11 likewise and page 11 is empty.

beside, The words in SVG are garbled.

**Comment by 1Jesper1** [comment]
I also got this error while trying to display a pdf. Only some pages were shown.

```
Error: Unknown IR type: p
    at SVGGraphics._makeShadingPattern
```
