### ISSUE TITLE
Convert examples/components/pageviewer.js to await/async

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#14127]
**Please do not work on this issue unless you have applied to the outreachy project.**

The [pageviewer.js](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js) example currently uses the older style of `promise.then` and callbacks. Convert it to use an `async` function and `await` style.

**Comment by janekotovich** [comment]
Hey guys would love to work on this one! I'm from Outreachy.

**Comment by AnishaSingh0118** [comment]
If it is still open can I take up this issue ?

**Comment by SahilRajpal-hub** [comment]
> If it is still open can I take up this issue ?

@AnishaSingh0118  are you working on this issue ? If not shall I carry forward ?

**Comment by AnishaSingh0118** [comment]
> > If it is still open can I take up this issue ?
> 
> @AnishaSingh0118 are you working on this issue ? If not shall I carry forward ?

Yaa sure .. go ahead..
