### ISSUE TITLE
What does this signify?

### ISSUE THREAD

**Issue by hzj19980803** [mozilla/pdf.js#14157]
![4a7619bbb16ea58b3475c2c696b0a46](https://user-images.githubusercontent.com/45988294/137727558-1fcfe999-d5b0-471a-9c47-895b15630dca.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this isn't actionable/valid.
