### ISSUE TITLE
Minimal stand alone example is missing

### ISSUE THREAD

**Issue by cottrell** [mozilla/pdf.js#14151]
Are there are *purely* stand alone examples? Something that uses cdn, or can be run simply from a single live-server? Current examples have syntax errors.

**Comment by Snuffleupagus** [comment]
This might be helpful: https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

> Current examples have syntax errors.

Please provide more *specific* information here, i.e. which *exact* example(s) aren't working and how are they broken?

When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable/understandable.

**Comment by cottrell** [comment]
Using live-server for example.

```
cd pdf.js/examples/learning
live-server helloworld.html
live-server helloworld64.html
```

None of these work. If there is a special way of running these it should be in a README.md or a makefile or package.json in the same directory. I suspect these are not actually stand alone examples and have been messed with to be embedded in the project docs.

**Comment by Snuffleupagus** [comment]
> Using live-server for example.

Unfortunately "live-server" isn't anything that we know about or can provide support for here.

The only server that we can support here is the one we use for development purposes, which is started using `gulp server`; please refer to https://github.com/mozilla/pdf.js#getting-the-code for more information.

As far as running the examples, please refer to https://github.com/mozilla/pdf.js#learning which contains the following paragraph:
> More examples can be found in the [examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/). Some of them are using the pdfjs-dist package, which can be built and installed in this repo directory via `gulp dist-install` command.

**Comment by timvandermeij** [comment]
Closing since this is answered above.

**Comment by cottrell** [comment]
Yes that is what I mean, no opinion on live-server. Any server on a minimal example should work.

But if you need to do a full build to run the examples it it is not a minimal example.

**Comment by timvandermeij** [comment]
You can of course change them to use a CDN from https://github.com/mozilla/pdf.js#using-pdfjs-in-a-web-application instead of the locally built PDF.js file. The examples are not meant to cover everything, just basic usage. On https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples you can find example usage with an external URL (note: the URL provided there is _not_ a CDN, but can obviously be changed to one).
