### ISSUE TITLE
Pdf converted to picture, text content lost

### ISSUE THREAD

**Issue by lanrenbulan** [mozilla/pdf.js#14163]
Attach (recommended) or Link to PDF file here:

[2.pdf](https://github.com/mozilla/pdf.js/files/7369993/2.pdf)

Configuration:
- all

Steps to reproduce the problem:

What is the expected behavior? (add screenshot)

It can be converted into pictures correctly, which is consistent with the content in PDF

What went wrong? (add screenshot)

text content lost

![image](https://user-images.githubusercontent.com/9604624/137840507-cff2ed83-7c27-451e-8fff-d1d3ad344922.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by lanrenbulan** [comment]
I've added a new configuration description. Please help me see it again.

I need to convert PDF to pictures, but I tried several versions. It can be converted to pictures, but a lot of text is lost after conversion.

**Comment by THausherr** [comment]
Did you create this file? If yes, make sure that the fonts are embedded. If no, then install some Asian fonts on your machine.

**Comment by lanrenbulan** [comment]
> Did you create this file? If yes, make sure that the fonts are embedded. If no, then install some Asian fonts on your machine.

No, this file is generated by a third party, I am looking for the corresponding font and try again.
