### ISSUE TITLE
Annotation borders don't have the correct width

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14203]
Attach (recommended) or Link to PDF file here:
[pdfcomment.pdf](https://github.com/mozilla/pdf.js/files/7428963/pdfcomment.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. Have a look on red lines on page 10
2. They're smaller in Firefox compared to how they're rendered in Acrobat

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/139138056-3b383ea4-b712-4303-832e-fa99af0b7b19.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/139138219-c10f0118-edaf-4c75-a1dd-3cbd1e5b381d.png)

**Comment by HyunjiEllenPak** [comment]
@calixteman 
Hi, I am struggle to utilize the pdf.js module. 
I would like to implement web application where a user could add comment in existing pdf file such as pdfcomment.pdf as you mentioned above.
How could I implement the function using pdf.js?
I'm using React, Javascript.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
