### ISSUE TITLE
PDF files made by iText2.0.8 (by lowagic.com) cannot be displayed in version 1.9.426pdf.js

### ISSUE THREAD

**Issue by fireWinters** [mozilla/pdf.js#14215]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome 
- Operating system and its version:windows7
- PDF.js version:1.9.426
- Is a browser extension:

Steps to reproduce the problem:
1. get the original file,
2.open it in PDFjs,
3.display an exception that cannot be displayed

What is the expected behavior? (add screenshot)

It is expected that files such as iText2.0.8 (by lowagic.com) in the PDF production program can be displayed normally.

What went wrong? (add screenshot)![image](https://user-images.githubusercontent.com/42629623/139612244-2727fd3e-8641-4756-9b86-8b2e98dfd0a6.png)

I look forward to hearing from you very much. Thank you.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable; this is now the fifth time in total that you've opened an issue in the repository without including the necessary information.
Please don't keep wasting our time time by opening completely non-actionable issues!

> PDF.js version: 1.9.426

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download; again we've also mentioned previously that such old releases are unsupported.

> Steps to reproduce the problem:
> [...]
> What went wrong? (add screenshot)

You've not provided *any* information to make this issue actionable, and a screen-shot alone cannot be used to any meaningful debugging.
