### ISSUE TITLE
Types cannot be imported from 'pdfjs-dist/legacy/web/pdf_viewer'

### ISSUE THREAD

**Issue by pinggi** [mozilla/pdf.js#14227]
A custom React component importing a type (for example `PDFViewer`) from `pdfjs-dist/legacy/web/pdf_viewer.d.ts` file ends up with Typescript error saying that the type is not exported from the file. The file cannot be used.

**Type import example**
- Not working
- Typescript error: `Module '"pdfjs-dist/legacy/web/pdf_viewer"' has no exported member 'PDFViewer'.ts(2305)`

_CustomReactComponent.tsx_
```
import { PDFViewer } from 'pdfjs-dist/legacy/web/pdf_viewer';
```
_pdfjs-dist/legacy/web/pdf_viewer.d.ts_
```
export * from "pdfjs-dist/types/web/pdf_viewer.component.d.ts"; <-- this doesn't re-export PDFViewer type from the file
```

The issue probably is that the file name contains `.d.ts` extension. If it's deleted, the typescript error is gone.

**Working type import example**
- Working
- No Typescript error

_CustomReactComponent.tsx_
```
import { PDFViewer } from 'pdfjs-dist/legacy/web/pdf_viewer';
```
_pdfjs-dist/legacy/web/pdf_viewer.d.ts_
```
export * from "pdfjs-dist/types/web/pdf_viewer.component"; <-- correct, this re-exports PDFViewer type now
```

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdfjs-dist/blob/master/legacy/web/pdf_viewer.d.ts looks OK as far as I can tell, with the caveat that I don't really know TypeScript.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by pinggi** [comment]
So it was already fixed.

The issue might be that I used the latest version 2.10.377 as usually and not the next version 2.11.338 you are referring to.
I installed it by `npm install pdfjs-dist` which is the same as `npm install pdfjs-dist@latest` and I needed to use `npm install pdfjs-dist@next`.

[https://www.npmjs.com/package/pdfjs-dist](url) -> 2.10.377

Thanks for the info.
