### ISSUE TITLE
Line 67: Unexpected token =

### ISSUE THREAD

**Issue by rick2909** [mozilla/pdf.js#14236]
Configuration:
- Windows 11
- npm version: 8.1.0
- node version: v16.13.0
- building with gulp-browserify
- pdf.js version: 2.10.377

Steps to reproduce the problem:
1. npm install gulp-browserify
2. npm install pdfjs-dist --save-dev

What went wrong?
when running gulp-browserify i get the following error 
```
Error in plugin 'gulp-browserify'
Parsing file C:\Testing\PdfReader\node_modules\pdfjs-dist\build\pdf.js: Line 67: Unexpected token =
```

**Comment by Snuffleupagus** [comment]
> npm install gulp-browserify

Unfortunately "gulp-browserify" isn't something that we can provide support for here.

> npm install pdfjs-dist --save-dev

Most likely, if you're attempting to use the PDF.js builds in older environments, you'll need to use the files in the `legacy/`-folder; please note the following paragraph from either https://github.com/mozilla/pdfjs-dist#readme or https://www.npmjs.com/package/pdfjs-dist?activeTab=readme:
> For usage with older browsers or environments, without support for modern
features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and
nullish coalescing; please see the `legacy` folder.
