### ISSUE TITLE
Question: Can I pass a PDF URL into viewer.js via JavaScript?

### ISSUE THREAD

**Issue by TwisterMc** [mozilla/pdf.js#14234]
I'm trying to integrate PDFjs in a way that I can pass in the PDF URL to `viewer.js` without having to edit `viewer.js` and without having to send the PDF URL via the address bar or iFrame.

Is there a way to define the PDF URL as a JavaScript variable to `viewer.html` and have that pass down to `viewer.js` and load the PDF?

Thanks

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, in particular:
> The viewer can be started without any PDF loaded by setting the `defaultUrl` app option to an empty string or by using the `?file=` query string without any location specified. Use `PDFViewerApplication.open(file)` to load the PDF file later.
