### ISSUE TITLE
PDF.js does not render my files correctly, Adobe Song Std-light do not work

### ISSUE THREAD

**Issue by lizhengjian1220** [mozilla/pdf.js#14231]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome 93.0.4577.82（official version） （64 - bit）
- Operating system and its version: Windows 10    19042.1288
- PDF.js version:Stable  (v 2.10.377)
- Is a browser extension:No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
The font appears in the table
What went wrong? (add screenshot)
The font not appears 

I've put the Adobe SongStd-light placed inside, still need what operation to make documents show normal.
Added the latest version of the CMAPS font dependency package to the project, but it did not work.
<img width="855" alt="AdobeSongStd-Light" src="https://user-images.githubusercontent.com/53615742/140285984-3c35249d-da9f-4284-bc56-608416214c09.png">
<img width="490" alt="Normal and abnormal" src="https://user-images.githubusercontent.com/53615742/140285990-1782d0e9-8f30-4e0a-9cfc-896a513b1158.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by lizhengjian1220** [comment]
sorry， I forget upload  the format of the PDF file,
<img width="571" alt="Font format of the PDF document" src="https://user-images.githubusercontent.com/53615742/140286943-966f75a9-0879-4c80-9966-fef8b6deb787.png">

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> I've put the Adobe SongStd-light placed inside, still need what operation to make documents show normal.

That's not expected to work either, since the folder shown in your screen-shot is only used for *standard fonts* (and you can't just dump arbitrary fonts there).
Please also note that. according to the PDF specification, all *non-standard* fonts should always be embedded inside the PDF document *itself*.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
