### ISSUE TITLE
Random textLayer inflation in iOS Safari

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#14243]
Attach (recommended) or Link to PDF file here:
*Any PDF with text (used in this demo: [sicp-pocket.pdf](https://github.com/sarabander/sicp-pocket/raw/master/sicp-pocket.pdf))*

Configuration:
- Web browser and its version: *Safari on iOS 14.8*
- Operating system and its version: *iOS 14.8*
- PDF.js version: *2.10.377 (prior versions also)*
- Is a browser extension: *No*

Steps to reproduce the problem:
1. *Open PDF in viewer and **put phone in landscape mode***
2. *Tap anywhere in a page with some text in it*

What is the expected behavior? (add screenshot)

*textLayer should not change. Before tapping:*
![IMG_4862](https://user-images.githubusercontent.com/18247990/140605910-7cd47253-b753-4ab6-957b-9a743ba4ab72.png)

What went wrong? (add screenshot)

*Some text elements beef up. After tapping:*
![IMG_4861](https://user-images.githubusercontent.com/18247990/140605951-afc00ba8-4487-4337-8bc3-7281293ed1d5.png)

*Affects text selection.*
![IMG_4860](https://user-images.githubusercontent.com/18247990/140605961-35fd0614-d69b-443c-b600-1d842b9f9e3f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
*Hosted on localhost.*

---

I don't know if this is a bug with Safari. It happened in previous iOS versions as well.\
Suggestion: this solves the issue:
```css
.textLayer span {
    -webkit-text-size-adjust: none;
}
```

**Comment by shivaprsd** [comment]
Kudos for the quick response and the patch!

#### Off topic:

I discovered the above bug while writing a small add-on for PDF.js (see a little Reader mode icon in the above screenshots?) named *doq*: https://github.com/shivaprsd/doq

It's sort of a hack, code-wise. I wrote it mainly for own use, but it could be useful to people. Is there a chance it could get included in the [Gallery of user projects and modifications](https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications)? Only if the devs find it worthy enough, that is.

\*shameless plug\*🙃 @Snuffleupagus @timvandermeij

**Comment by timvandermeij** [comment]
Certainly, I have just included it in the gallery.

**Comment by shivaprsd** [comment]
Thanks a lot! You guys are awesome. ❤️
