### ISSUE TITLE
How should I use the internal links the way they're formatted?

### ISSUE THREAD

**Issue by smh6** [mozilla/pdf.js#14248]
They're formatted like this `#[{"num":274,"gen":0},{"name":"XYZ"},76.500008,703.5,0]`
clicking on them doesn't go anywhere either, but the external links work correctly
I've set up my annotations like the example components

        page.getAnnotations().then((annotationData) => {

          const eventBus = new pdfjsViewer.EventBus();
          const pdfLinkService = new pdfjsViewer.PDFLinkService({ eventBus });
          let textLayer = document.querySelector(`[data-page="${pageNum}"] .textLayer`);

          pdfjsLib.AnnotationLayer.render({
            annotations: annotationData,
            div: textLayer,
            viewport: viewport.clone({ dontFlip: true }),
            page: page,
            linkService: pdfLinkService,
            enableScripting: true,
            renderInteractiveForms: true
          });
        });

**Comment by Snuffleupagus** [comment]
Please just follow the `simpleviewer` example in https://github.com/mozilla/pdf.js/tree/master/examples/components instead, since that one already supports internal destinations with no additional configuration required.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by smh6** [comment]
But I only need the annotations, the example that you mentioned, needs to independently set the document for the pdfViewer object, which does all the job by itself, I mean it makes the canvas, the text layer, and the annotation layer, but I've implemented the canvas and text layer by myself, and now I only need the annotations, but I don't know how to do it, the one I tried worked correctly with external links but not with the internals, why? those two example components produce the same URL for internal links

**Comment by smh6** [comment]
> Please just follow the `simpleviewer` example in https://github.com/mozilla/pdf.js/tree/master/examples/components instead, since that one already supports internal destinations with no additional configuration required.
> 
> When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

But I only need the annotations, the example that you mentioned, needs to independently set the document for the pdfViewer object, which does all the job by itself, I mean it makes the canvas, the text layer, and the annotation layer, but I've implemented the canvas and text layer by myself, and now I only need the annotations, but I don't know how to do it, the one I tried worked correctly with external links but not with the internals, why? those two example components seem to produce the same URL for internal links, isn't there any way to make them work?
