### ISSUE TITLE
How should I import the PDFLinkService in my js file?

### ISSUE THREAD

**Issue by smh6** [mozilla/pdf.js#14246]
I've downloaded pdf.js version 2.11.338 from https://mozilla.github.io/pdf.js/getting_started/#download
and I tried importing PDFLinkService to my file like this:
`import { PDFLinkService } from '../pdfjs-dist/lib/web/pdf_link_service.js'`
but it throws this error when I try to import it:
`Uncaught SyntaxError: The requested module '../pdfjs-dist/lib/web/pdf_link_service.js' does not provide an export named 'PDFLinkService'`
I literally couldn't find anywhere explaining how to use it properly, I need it for setting up the Annotations in my pdf reader project, what's the proper way of setting up annotations, I've read multiple blogs about it but they're kinda outdated and certain things are changed until now and they don't work correctly, the main issue is with PDFLinkService, I don't know how should I get it to work, I don't know where does it exist at all

**Comment by Snuffleupagus** [comment]
Please note that the README in https://github.com/mozilla/pdfjs-dist/tree/master/lib#readme *explicitly* advises against using its code directly.
The correct file to reference would instead be https://github.com/mozilla/pdfjs-dist/blob/master/web/pdf_viewer.js, where `PDFLinkService` is being exported.

Please refer to the "viewer component" examples, which show how a viewer can be built (with e.g. annotationLayer): https://github.com/mozilla/pdf.js/tree/master/examples/components

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
