### ISSUE TITLE
Invalid pdf structure for a signed file

### ISSUE THREAD

**Issue by luiseufrasio** [mozilla/pdf.js#14269]
Configuration:
- Chrome: 95.0.4638.69 - 64 bits
- Operating system and its version: Windows 10
- PDF.js version: 2.10.377-dist

Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/7529789/test.pdf)

- Is a browser extension: No

Steps to reproduce the problem:
1. run the HELLO WORLD github example passing the attached file: https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html

2. The PDF does NOT load & in Dev tools console we have:
{
    "message": "Invalid PDF structure.",
    "name": "InvalidPDFException"
} 

What is the expected behavior? (add screenshot)
Show the PDF in the browser like this:
![Expected](https://user-images.githubusercontent.com/1511708/141521969-ec9ad9ff-fdd9-4aa3-8268-591045109ae5.png)
[teste_assinado.pdf](https://github.com/mozilla/pdf.js/files/7529848/teste_assinado.pdf)

What went wrong? (add screenshot)
![Error Screen 1](https://user-images.githubusercontent.com/1511708/141521297-95900022-6bc6-44d0-954f-75a3fa285c12.png)
![Error Screen 2](https://user-images.githubusercontent.com/1511708/141521300-1b80d2a5-7773-45ff-ae0d-ba7cb40bbb1e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [test.pdf](https://github.com/mozilla/pdf.js/files/7529789/test.pdf)

That document is damaged enough that it cannot be opened in Adobe Reader either, i.e. the PDF reference implementation, hence this looks for all intents and purposes like a bug in the PDF document *itself* (rather than in the PDF.js library).
