### ISSUE TITLE
selected text color display problem in Chrome

### ISSUE THREAD

**Issue by zjw1111** [mozilla/pdf.js#14274]
Attach (recommended) or Link to PDF file here:
[BAVP Blockchain-Based Access Verification Protoco.pdf](https://github.com/mozilla/pdf.js/files/7535501/Wei.Songjie.-.2018.-.BAVP.Blockchain-Based.Access.Verification.Protoco.pdf)
[BAVP Blockchain-Based Access Verification Protoco(zh-cn).pdf](https://github.com/mozilla/pdf.js/files/7535561/Wei.Songjie.-.2018.-.BAVP.Blockchain-Based.Access.Verification.Protoco.zh.pdf)

Configuration:
- Web browser and its version: Chrome 95.0.4638.69
- Operating system and its version: Win10 10.0.18363.1256
- PDF.js version: 2.10.377
- Is a browser extension: It does not matter. I have tried to use it in the browser extension and on the website https://mozilla.github.io/pdf.js/web/viewer.html, this problem will appear

Steps to reproduce the problem:
1. Select a few lines of text arbitrarily

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/30893610/141714802-099e825a-4268-4e47-8f31-d479c0ca1682.png)

What went wrong? (add screenshot)
- Some text appears light blue
![image](https://user-images.githubusercontent.com/30893610/141714780-c2c9d99f-a047-45b1-932b-b0e3495560de.png)
- And, some text appears dark blue
![image](https://user-images.githubusercontent.com/30893610/141715237-223400f8-8c21-4246-a78e-b64d3cffec0a.png)

**Comment by Snuffleupagus** [comment]
I cannot reproduce this using PDF.js version `2.12.126`, i.e. *built-in* PDF Viewer, in Firefox Nightly 96 on Windows.
Hence this unfortunately looks like a *browser bug*, rather than a PDF.js one (please keep in mind that Firefox is the main development target in this library).
