### ISSUE TITLE
"SyntaxError: Unexpected token '.' " in old Chrome versions.

### ISSUE THREAD

**Issue by filipeRmlh** [mozilla/pdf.js#14288]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 74.0.3729.136 mobile.
- Operating system and its version: Android 9
- PDF.js version: 2.10.377
- Is a browser extension: No

Steps to reproduce the problem:
1. Run the pdfjs in chrome 74 (mobile android).
2. Observe that it can't work due to a "sintax" error.

What is the expected behavior? (add screenshot)
Work without these kind of errors.

What went wrong? (add screenshot)
Line 2437 of builded pdf.js file (or Line 1359 in /display/api.js file):   
sintax error because of `?.` piece of code in old chrome versions.
```js
async getXfa() {
    return this._transport._htmlForXfa?.children[this._pageIndex] || null;
  }
```
Note: this error stopped execution at the mentioned point, meaning that I dont know if there is any other error like this one.

![image](https://user-images.githubusercontent.com/8943674/142437043-4b381274-7aae-4c99-87f7-98a3f4a331b1.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
The bug can be reproduced in mozilla.github.io/pdf.js website.

**Comment by Snuffleupagus** [comment]
When using the PDF.js library in older environments/browsers without e.g. optional chaining support, you'll need to use a `legacy`-build instead; please note the two types of builds listed e.g. at https://mozilla.github.io/pdf.js/getting_started/#download
