### ISSUE TITLE
Pdf.js doesn't fully render the attached PDF page

### ISSUE THREAD

**Issue by gopi-reddy** [mozilla/pdf.js#14297]
Attach (recommended) or Link to PDF file here: [RenderIssue.pdf](https://github.com/mozilla/pdf.js/files/7583657/RenderIssue.pdf)

Configuration:
- Web browser and its version: Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Version 10.0.19042

- PDF.js version: v2.12.201 (If this looks incorrect, please take it from the URL)
- Is a browser extension: No, using https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Drop the attached PDF on to the page - [RenderIssue.pdf](https://github.com/mozilla/pdf.js/files/7583657/RenderIssue.pdf)

What is the expected behavior? It should appear as in Adobe Reader - 
![image](https://user-images.githubusercontent.com/94864394/142921185-1ee7034b-1db9-4b6d-ae08-4a9cb4426d70.png)

What went wrong? Some text is blank - 
![image](https://user-images.githubusercontent.com/94864394/142921086-a5ad3ad7-caac-40d8-92d3-684d59aee1f5.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by Snuffleupagus** [comment]
```
PDF b778a60fa177a7df68a3c50fff65c244 [1.3 - / -] (PDF.js: 2.12.126) viewer.js:1502:13
Warning: No cmap table available. 4 pdf.worker.js:1115:13
```

**Comment by gopi-reddy** [comment]
Hi @Snuffleupagus, 

Not that it matters that much but I get 2.12.201 as the version number in the console for https://mozilla.github.io/pdf.js/web/viewer.html.  Tried clearing the browser cache too.

PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.12.201)

**Comment by sunkangchina** [comment]
not support for now?

**Comment by NeverLuckyLiu** [comment]
> Attach (recommended) or Link to PDF file here: [RenderIssue.pdf](https://github.com/mozilla/pdf.js/files/7583657/RenderIssue.pdf)
> 
> Configuration:
> 
> * Web browser and its version: Chrome Version 96.0.4664.45 (Official Build) (64-bit)
> * Operating system and its version: Windows 10 Version 10.0.19042
> * PDF.js version: v2.12.201 (If this looks incorrect, please take it from the URL)
> * Is a browser extension: No, using https://mozilla.github.io/pdf.js/web/viewer.html
> 
> Steps to reproduce the problem:
> 
> 1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
> 2. Drop the attached PDF on to the page - [RenderIssue.pdf](https://github.com/mozilla/pdf.js/files/7583657/RenderIssue.pdf)
> 
> What is the expected behavior? It should appear as in Adobe Reader - ![image](https://user-images.githubusercontent.com/94864394/142921185-1ee7034b-1db9-4b6d-ae08-4a9cb4426d70.png)
> 
> What went wrong? Some text is blank - ![image](https://user-images.githubusercontent.com/94864394/142921086-a5ad3ad7-caac-40d8-92d3-684d59aee1f5.png)
> 
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

Any update for this? I came across the same problem while displaying a pdf with table

**Comment by NeverLuckyLiu** [comment]
@gopi-reddy  Any update for this? I came across the same problem while displaying a pdf file with table

**Comment by gopi-reddy** [comment]
Hi @NeverLuckyLiu, I haven't seen any progress on this issue.  Looks like it'll take more people to report the issue for momentum.  You might want to submit your sample PDF too.  Pdf.js team?

**Comment by NeverLuckyLiu** [comment]
@gopi-reddy I have solved my problem today by the following code. It seems to be the font issue:

`
  // import pdf.js font
  const CMAP_URL = 'https://unpkg.com/pdfjs-dist@2.6.347/cmaps/'
  
  const initPdf = async (fileUrl) => {
    const loadingTask = pdfjsLib.getDocument({
      url: fileUrl,
      cMapUrl: CMAP_URL,
      cMapPacked: true
    })
    const pdf = await loadingTask.promise
    return pdf
  }
`
