### ISSUE TITLE
PDF Viewer: workerSrc will not be set in Chrome but in FireFox

### ISSUE THREAD

**Issue by ManuelHaas** [mozilla/pdf.js#14309]
I used the current stable version (pdfjs-2.10.377-dist) to build a pdf viewer according to web/viewer.html in an ASP.NET Core App. The viewer works fine in FireFox but does not work in Chrome. I took the viewer.html and adopted the head section to set the workerSrc  property according to the examples because the viewer.html file is not in the same folder as the library files.

```HTML
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="google" content="notranslate">
    <title>PDF.js viewer</title>


    <link rel="stylesheet" href="~/lib/pdfjs/web/viewer.css">

    <!-- This snippet is used in production (included from viewer.html) -->
    <link rel="resource" type="application/l10n" href="~/lib/pdfjs/web/locale/locale.properties">

    <script src="~/lib/pdfjs/build/pdf.js"></script>

    <!-- My addings begin here -->
    <script type="text/javascript">
        // Loaded via <script> tag, create shortcut to access PDF.js exports.
        var pdfjsLib = window["pdfjs-dist/build/pdf"];

        // The workerSrc property shall be specified.
        pdfjsLib.GlobalWorkerOptions.workerSrc = '/lib/pdfjs/build/pdf.worker.js';
    </script>
    <!-- My addings end here -->

    <script src="~/lib/pdfjs/web/viewer.js"></script>

</head>
```

Configuration:
- Web browser and its version: FireFox 94.0.2, Chrome 96.0.4664.45
- Operating system and its version: Windows 10 Pro
- PDF.js version: pdfjs-2.10.377-dist
- Is a browser extension: no

What is the expected behavior?
That it would work in FireFox and Chrome

What went wrong?
It only work in FireFox and NOT in Chrome
Console log of Chrome:
![image](https://user-images.githubusercontent.com/10881695/143427421-dc285609-88a8-403f-959d-9cccbad5fd8f.png)

Screenshot of Viewer in Chrome (with german localization):
![image](https://user-images.githubusercontent.com/10881695/143427918-4bd97597-5e3d-4e51-a5b2-be222ebe3f1e.png)

In FireFox the PDF will be displayed correctly and no error is in console log.

**Comment by Snuffleupagus** [comment]
It almost looks as if you've attempted to *combine* the [viewer components](https://github.com/mozilla/pdf.js/tree/master/examples/components) examples with the [full viewer](https://github.com/mozilla/pdf.js#online-demo), something which is neither intended nor supported unfortunately.

As-is it's almost impossible to provide any further assistance, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by ManuelHaas** [comment]
@Snuffleupagus Thank you for your anwer.
Ok, I understand that it is hard without a reproducible sample. Thought I was missing something simple.
Is a zip of a VS webapplication enough as a sample or would you prefer a web instance?

**Comment by Snuffleupagus** [comment]
> PDF.js version: pdfjs-2.10.377-dist

Oh, the issue is likely that you've attempted to use https://github.com/mozilla/pdfjs-dist/ to implement the "full" viewer. Please note that that's explicitly not intended, and consequently it won't work, and we're purposely not distributing the viewer like that; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine): 
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Hence the only way to implement the "full" viewer is to use a release from https://mozilla.github.io/pdf.js/getting_started/#download, since otherwise things just can't/won't work.

> Is a zip of a VS webapplication enough as a sample or would you prefer a web instance?

In the event that the above isn't already sufficient for you to fix this yourself, then the test-case needs to be a small, simple *and* runnable directly in a web-browser.

**Comment by ManuelHaas** [comment]
Thank you very much for your explanations!
I come to a working solution with your hints.
