### ISSUE TITLE
Content in some text widgets are not visible

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14301]
Attach (recommended) or Link to PDF file here:
[formulairecerfa90nov00-1.pdf](https://github.com/mozilla/pdf.js/files/7594316/formulairecerfa90nov00-1.pdf)
or here: http://mdph.cotesdarmor.fr/pdf/formulaires/formulairecerfa90nov00.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 10 pro

Steps to reproduce the problem:
1.  Go to page 2:
![image](https://user-images.githubusercontent.com/5641725/143210106-47965a75-ad3f-403e-8698-27c679d7b736.png)
Enter a number in each fields (the input is supposed to be a single number)
2. It's impossible to read what it has been entered, so it isn't possible to check that the inputs are correct and consequently the user will very likely use another pdf viewer.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/143210460-22f3c0cb-cc02-4dc2-9f56-bbacef870fbb.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/5641725/143210615-944c73d0-e2aa-4cf8-8867-8ef73e0761ec.png)

**Comment by Snuffleupagus** [comment]
The naive solution would be to just decrease the vertical padding to e.g. `1px` in https://github.com/mozilla/pdf.js/blob/70fc30d97c619de0f2fcb51e67bfdb1a46922725/web/annotation_layer_builder.css#L65
However, without running tests I suppose that could break other things and we may perhaps need to limit that to *only* `input`-elements or even just "short" fields!?

**Comment by calixteman** [comment]
And very likely, at some point, in a particular case, 3px was a good value so setting it to 1px will fix this issue and likely will break another pdf.
For a "normal" text field I don't really see the point to have this padding or maybe it is only useful for comb fields.

**Comment by Snuffleupagus** [comment]
Given that this issue seems to be (somewhat of) a special-case, how about simply using a CSS-class to set the padding to e,g, `padding: 0 1px;` specifically for `textWidgetAnnotation`-inputs where the width is e.g. shorter than `10` pixels?
That should be a very targeted fix, thus reducing the risk of regressing anything else in the process.

**Comment by calixteman** [comment]
@timvandermeij, do you have an idea on what could be a good solution ? and maybe you could remember why you chose this `3`.

**Comment by timvandermeij** [comment]
I see that I introduced the `3px` value in https://github.com/mozilla/pdf.js/commit/e686db250cdb37647f6ba9c05be6b26fc9a07ea6. Back then we didn't have the associated test yet, but I did add that later and I recall having used the same document for the development of this patch, so I'd say if https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-text-widget.pdf still renders correctly (i.e., very similar to Adobe Reader) then changing the `3px` should be fine.
