### ISSUE TITLE
Text size in annotations isn't supoorted correctly

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#14317]
Attach (recommended) or Link to PDF file here: 

[anootation_problem.pdf](https://github.com/mozilla/pdf.js/files/7611701/anootation_problem.pdf)

Configuration:
- Web browser and its version: 98.0.4732.0 (Official Build) canary (64-bit)
- Operating system and its version: Edition Windows 10 Home, Version 20H2, OS build 19042.1348
- PDF.js version: 2.12.211
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open pdf file
2. Scroll to bottom of page and point to annotation of 'loss ft(x) >= 0,' text
3. Compare the displayed text with same in Acrobat Reader

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2311076/143681452-0afa9a98-b16b-4a39-a393-631eb1c8c41f.png)

What went wrong? (add screenshot)
Text size not respected (e.g., in superscripts and subscripts)
![image](https://user-images.githubusercontent.com/2311076/143681575-2a2fe4de-cbad-4625-a6fe-2212fa20b8f1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Looking at the XML-data, in the /RC-entries, it seems that the sub/super-script characters are *only* using `vertical-align` to move them but otherwise have the same font-sizes as the "normal" text.
Hence there doesn't *appear* (at least to me) that we're doing anything technically wrong here, but perhaps we can add a heuristic to reduce the font-size when a non-zero `vertical-align` is used!?

**Comment by calixteman** [comment]
Yes, for example the first `x²` corresponds to the following xml:
```xml
<span dir= "ltr" style= "font-size:10.1pt;text-align:left;color:#000000;font-weight:normal;font-style:italic">x</span>
        <span dir= "ltr" style= "font-size:10.1pt;text-align:left;vertical-align:+5.0pt;color:#000000;font-weight:normal;font-style:normal">2</span>
```
From my pov, it'd be a bit strange to decrease size font  because of vertical align... or I'm missing something somewhere.

**Comment by calixteman** [comment]
In Acrobat, it isn't possible to set the vertical-align but it's possible to add sub/super-script style to some text.
So very likely, vertical-align > 0 is equivalent to superscript and then the font size is decreased (my impress is that the factor is 80%) and when negative it's a subscript.

**Comment by Snuffleupagus** [comment]
Looking at the PDF specification, https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.2097514, it says the following about `vertical-align`:
> An amount by which to adjust the baseline of the enclosed text. A positive value indicates a superscript; a negative value indicates a subscript. The value is of the form <decimal number>pt, optionally preceded by a sign, and followed by “pt”.

Given that sub/super-scripts are usually smaller[1] than the regular text, I suppose that it makes some sense to reduce the font-size in these cases.

---
[1] E.g. Wikipedia, see https://en.wikipedia.org/wiki/Subscript_and_superscript, says the following:
> A subscript or superscript is a character (such as a number or letter) that is set slightly below or above the normal line of type, respectively. It is usually smaller than the rest of the text.

**Comment by Snuffleupagus** [comment]
> my impress is that the factor is 80%

Based on https://en.wikipedia.org/wiki/Subscript_and_superscript#Desktop_publishing, a slightly lower value might be more appropriate!?

**Comment by qwer1304** [comment]
Hi,
Thanx for the quick fix.
The superscript looks great!
However, the subscript seems to be too down below the text:
![image](https://user-images.githubusercontent.com/2311076/143767507-a215dfac-53b0-4e14-81b2-f95617894bea.png)

Compare this to Acrobat Reader output (e.g., the 'e' near the _f_).

**Comment by calixteman** [comment]
The factors are here:
https://github.com/mozilla/pdf.js/blob/a2a5376adff2a608fcf3fa9c08d3e951cf1b91ae/src/core/xfa/xhtml.js#L173-L175
and I got the factors here:
https://en.wikipedia.org/wiki/Subscript_and_superscript#Desktop_publishing
using the Adobe ones.

**Comment by Snuffleupagus** [comment]
> However, the subscript seems to be too down below the text:

I'd say that it's not the subscript position that's wrong, but rather the "f"-characters that are rendered incorrectly (too short).
What you're seeing might be a *browser*-specific problem, since it looks good in Firefox (on Windows):

![popup](https://user-images.githubusercontent.com/2692120/143768845-223264c6-bb4b-499d-b115-cd08be34c6ee.png)

**Comment by qwer1304** [comment]
This is Chrome 98.0.4732.0 (Official Build) canary (64-bit).  It seema as if the issue is with caharcters that do not extend below the line, e.g., 'a', 'c', etc. With a 'g' it looks more resonable.

**Comment by calixteman** [comment]
The font-family is striped out (when existing) from the xml.
Consequently, the rendered html hasn't any font-family set and the web browser is using the default font.
