### ISSUE TITLE
Safari pdf.js load error: [Error] SyntaxError: Unexpected private name #setAnnotationCanvasMap

### ISSUE THREAD

**Issue by jnromero** [mozilla/pdf.js#14327]
When I try to load pdf.js using the following code in Safari Version 14.1 (15611.1.21.161.7, 15611) on Mac OS X Catalina Version 10.15.7 I get the following error: 

[Error] SyntaxError: Unexpected private name #setAnnotationCanvasMap. Cannot parse class method with private name.
	(anonymous function) (pdf.js:11413)

The expected behavior is for the script to load with no errors.  This same error doesn't occur in Chrome.  I have attached a simple jsfiddle to see the bug:

https://jsfiddle.net/fscbpjz1/

**Comment by Snuffleupagus** [comment]
If your browser doesn't support modern, and fully up-to-date, JavaScript then you need to use a `legacy` build of the PDF.js library, please see e.g. https://github.com/mozilla/pdf.js#online-demo and https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by mmarton** [comment]
Releasing a breaking change in a minor version, not mentioning it in the release notes, and then telling people it's their fault for not using up2date browsers... Very professional indeed

**Comment by mmarton** [comment]
@calixteman you are right in most of your points and I shouldn't have ranted.

one thing I would like to emphasize: this lib is also accessible as an npm package. Allowing people to use it in their site as an integrated pdf renderer. Dropping support for older browsers also completely fine. But it is a breaking change that based on semver rules should have be done in a major release instead. So no one accidentally updates to an incompatible version and breaks their site for some of their users
