### ISSUE TITLE
pdf spaces look like character (j)

### ISSUE THREAD

**Issue by CRIS19N** [mozilla/pdf.js#14331]
Configuration:
- Web browser and its version: PHP Desktop Chrome 57 (https://github.com/cztomczak/phpdesktop)
- Operating system and its version: Windows 10
- PDF.js: Prebuilt (for older browsers) v2.10.337:

the problem:
1. some PDFs do not display correctly, for example blanks are filled with a different character.
2.in this pdf the spaces are filled with a "j"
![image](https://user-images.githubusercontent.com/60001912/144165065-7329aaaf-b622-45fb-ae33-d59818651633.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

That part of the ISSUE_TEMPLATE is *always required* in order for any issue to be valid.

> Web browser and its version: PHP Desktop Chrome 57 (https://github.com/cztomczak/phpdesktop)

Unfortunately we cannot support "custom" browsers, and furthermore even the *regular* Google Chrome 57 version is explicitly unsupported; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
