### ISSUE TITLE
pdfjs.history persistent cookie set prior to user consent

### ISSUE THREAD

**Issue by infatum1** [mozilla/pdf.js#14336]
[The page](https://liedaga.liepaja.edu.lv/atbalsts-karjerai/) in question. Not sure whether I'm knocking the right door, but I have tried raising the issue of Wordpress plugin page. Seems, like the plugin is not the issue as any other plugin sets the same persistent cookie. 

Configuration:
- Web browser and its version: regardless of browser
- Operating system and its version: regardless of operating system
- PDF.js version: [EmbedPress ](https://wordpress.org/plugins/embedpress/) or [PDF Viewer for Elementor](https://wordpress.org/plugins/pdf-viewer-for-elementor/)
- Is a browser extension: no. server side plugins

Steps to reproduce the problem:
1. Every page that has an embedded PDF
2.

What is the expected behavior? (add screenshot)
No persistent statistical cookie is set by pdfjs. IS there a way to turn off and never set the cookie?

What went wrong? (add screenshot)
The online service cookiebot.com identifies pdfjs.history as persistent cookie which is not blocked / can't be blocked by consent managers. Presently it violates GDPR law. [Screenshot.](https://photos.app.goo.gl/stJNN2rkF8wRtYrs5)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> [The page](https://liedaga.liepaja.edu.lv/atbalsts-karjerai/) in question.

That web-page is not in any way connected to the PDF.js project, and consequently you'll need to contact its webmaster for issues regarding it.

> PDF.js version: [EmbedPress ](https://wordpress.org/plugins/embedpress/) or [PDF Viewer for Elementor](https://wordpress.org/plugins/pdf-viewer-for-elementor/)

Please note that while it's possible that those projects are *using* the PDF.js library, and its default viewer, they are not affiliated with this library (and we don't know anything about them here). Hence we unfortunately cannot provide any help/support for either of those projects *here*.

> What is the expected behavior? (add screenshot)
> No persistent statistical cookie is set by pdfjs. IS there a way to turn off and never set the cookie?

There's no such functionality, given that the default viewer isn't intended to be used as-is by third-parties; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Hence that'd be an issue (or feature request) you'd need to raise against those projects directly.
