### ISSUE TITLE
PDFJS does not recover from a PDF Worker loading failure

### ISSUE THREAD

**Issue by skrtheboss** [mozilla/pdf.js#14332]
Configuration:
- Web browser and its version: Chrome 96.0.4664.45
- Operating system and its version:  Windows 10.0.19044.1387
- PDF.js version: 2.10.377

Steps to reproduce the problem:
1. Open [this JSFIddle](https://jsfiddle.net/srfeL7kq/13/).
2. Click on `Load Existing`, and it should render the pdf. ( You can click this many times )
3. Click on `Load Missing`, and it should display an error message.
4. Try clicking on `Load Existing`  again, and it should no longer render the pdf, and it should display the error.

What is the expected behavior?

PDFJs should support PDF Worker loading failures, since it could also happen in a situation of bad signal.
It should not be required to reload the whole page.

The problem is caused by those [[1](https://github.com/mozilla/pdf.js/blob/v2.10.377/src/display/api.js#L2234-L2237), [2](https://github.com/mozilla/pdf.js/blob/v2.10.377/src/display/api.js#L2119)] codeblocks.

Currently we have implemented a workaround by overriding the PDFWorker's `_setupFakeWorker`:
```javascript
pdfjs.PDFWorker.prototype._setupFakeWorker = function () {
    this._readyCapability.reject(new Error('Worker could not be loaded!'));
};
```

**Comment by Snuffleupagus** [comment]
Considering that this code has, for all intents and purposes, worked the same way for *many years* I'm thus not entirely convinced that we need to complicate the PDF.js API-implementation in order to handle what must surely be very much an edge-case. (Especially considering that the reload work-around is available.)
As far as I'm concerned, setting the `workerSrc` to the wrong path is basically an implementer error and I don't really understand why you'd want/need to change it essentially *dynamically* like the jsfiddle shows!?

**Comment by skrtheboss** [comment]
Hi @Snuffleupagus,
I have changed the `workerSrc` to a wrong path only to simulate a network outage. Alternatively one could also disable network in the DevTools to reproduce the problem.
I do not think that forcing the users to reload the page is an appropriate thing to do...

**Comment by Snuffleupagus** [comment]
> I have changed the `workerSrc` to a wrong path only to simulate a network outage.

In that case, i.e. a network error, isn't it already very likely that the user will manually reload the page anyway?

My point here is that fixing this *edge-case* would require adding a bunch of code-paths to a part of the code-base which is already somewhat complex and crucial to the (generally) correct working of the PDF.js library. (And none of this applies to e.g. the Firefox PDF Viewer either.)

**Comment by skrtheboss** [comment]
It depends, f.e. in an Angular application ( which is a Singe Page Application ), it is likely that the app is loaded correctly in the past .
Then when you navigate through specific routes/pages where the PDF is rendered, it can occurr that the network is not available for one short moment, but is available again as soon as you switch page again. 
The application should not break only for the short absence of the network.

**Comment by Snuffleupagus** [comment]
There should be a work-around available, which is that you *manually* load the `pdf.worker.js` file and create a Worker first.[1]
Once that's been successfully loaded, assign it to [`GlobalWorkerOptions.workerPort`](https://github.com/mozilla/pdf.js/blob/master/src/display/worker_options.js) *before* calling `pdfjsLib.getDocument`.

As far as I understand, that *should* provide a work-around using existing code and not require us to (further) complicate the worker-loading/initialization code in the API itself.

---
[1] You could e.g. use either `new Worker(/* path to the pdf.worker.js file */)` or manually load the `pdf.worker.js` file and use a blob-URL in the `new Worker(...)` call.
