### ISSUE TITLE
Firefox PDFViewer Allows Editing of Password Protected PDF Form Files!!!

### ISSUE THREAD

**Issue by zorker** [mozilla/pdf.js#14356]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 95.0
- Operating system and its version: Windows 10
- PDF.js version: Whatever is shipped with Firefox 95.0
- Is a browser extension:

Steps to reproduce the problem:
1. Open file in Adobe Acrobat and get message that file is protected. Cannot change anything without password
2. Open file in Firefox 95.0. Allows free editing of form fields and on top the file can be saved.
3. Open the saved file from Firefox with Adobe Acrobat and you still get the password protected message but the values are changed!

Testfile
[testfile.pdf](https://github.com/mozilla/pdf.js/files/7692008/testfile.pdf)

What went wrong?
Firefox allows editing of protected PDF files!!!

**Comment by j-hap** [comment]
I just faced the same issue with FF 108.0.1 on Win10. This is marked closed, but I can still edit protected forms. Chrome and Acrobat don't let me change anything. @zorker did the merge fix you initial issue?

**Comment by Fundraw-123** [comment]
Why Adobe doesn't have a solution? An expensive subscription with Acrobat Pro. With password protection and restrictions options on  sensitive files to prevent from printing and extract, copy the page. These restrictions are not working in Firefox browser. I tried many files. I spoke with tech reps, no solution as of today. I am very hesitant to distribute confidential files. Some people don't about these issues.
