### ISSUE TITLE
 Print preview add watermark

### ISSUE THREAD

**Issue by myJOB1122** [mozilla/pdf.js#14366]
Hi
my problem:
1. How to do Print preview add watermark
2. Please give my a demo
thanks very much!

**Comment by Snuffleupagus** [comment]
That's not a use-case that this library is intended for; note https://github.com/mozilla/pdf.js#pdfjs-
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
