### ISSUE TITLE
PDF appears as white paper with no text

### ISSUE THREAD

**Issue by broy-github** [mozilla/pdf.js#14377]
Hello,

I am using pdf.js in my .Net application. It was working well in many PDFs.
But recently, some PDFs are not rendering.
The entire screen appears just as white paper without any text.
The browser console shows the following messages: 
```
PDF f7bb6400f049c0f34bac34f67ee99934 [1.4 iTextSharp™ 5.5.13 ©2000-2018 iText Group NV (AGPL-version) / -] (PDF.js: 1.9.426)
pdf.worker.js:10 Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 0
```
Please help me.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes actionable.

**Comment by broy-github** [comment]
Here is the attached screenshot:

![image_2021_12_15T12_36_53_179Z](https://user-images.githubusercontent.com/67911901/146188091-4749af15-7483-415e-a211-abe79f088701.png)

**Comment by broy-github** [comment]
Here is the attached screenshot : 

![image_2021_12_15T12_40_41_700Z](https://user-images.githubusercontent.com/67911901/146188486-57223606-b4b0-4791-b2ff-7b98d7d0ae3b.png)

**Comment by calixteman** [comment]
@broy-github we aren't magicians... so please read https://github.com/mozilla/pdf.js/issues/14377#issuecomment-994735460 and provide all the information we need.

**Comment by Snuffleupagus** [comment]
Again, without *all* of the ISSUE_TEMPLATE filled in we really cannot provide any assistance!
Of particular importance is that you include the actual PDF document, since no debugging can be done from a screen-shot alone. Also, you really need to update the PDF.js version *before* asking for help, since the version you're using is over *four years old*.

Closing as INCOMPLETE, since there's unfortunately no actionable information here.

**Comment by broy-github** [comment]
Please find the PDF attached here with : 

[test.pdf](https://github.com/mozilla/pdf.js/files/7719524/test.pdf)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.12.248` in Firefox Nightly 97 on Windows.

*Once more:* You're using a very old and completely unsupported version of the PDF.js library, hence please update to a supported release; see https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by broy-github** [comment]
Is it working in Chrome and Edge browser in Windows 10?
