### ISSUE TITLE
Android(Google Chrome) print preview and print out are empty when printing large PDF (over 25 pages)

### ISSUE THREAD

**Issue by suminda1** [mozilla/pdf.js#14376]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome latest
- Operating system and its version: Android latest
- PDF.js version:2.2.171
- Is a browser extension: NO

Steps to reproduce the problem:
1. View large PDF (over 25 pages)
2. Clicks on the print button 
3. Preview  and print out sometime is empty 

**The solution for the issue is  the following (Open separate windows with the print content for the Android)**

     performPrint: function performPrint() {
        var _this2 = this;

        this.throwIfInactive();
        return new Promise(function (resolve) {
          setTimeout(function () {
            if (!_this2.active) {
              resolve();
              return;
            }
            var printhtml = document.getElementById('printContainer');
            
            if (_this2.isPopPrintEnable && printhtml != null) {

              let popupWin = window.open("", "_blank", "top=0,left=0,height=0,width=auto");
              popupWin.document.open();
              popupWin.document.write(`
                      <html>
                        <head>
                        <style scoped>

                        .no-print {
                          text-align: center;
                          align-items: center;
                          width: 100vw;
                          height:100vh;
                        }

                        .heading-print {
                          font-family: 'Roboto Slab';
                          background-color:#e6e6e6;
                          font-size: 30px;
                          font-weight: bold;
                          color: #20407f;
                        }
                        .display-tbl {
                          border-collapse: collapse;
                          table-layout: fixed;
                          width: 100%;
                          height:100%;
                          .tr {
                            align-items: center;
                            width: 100%;
                            .td {
                              text-align: center;
                              width: 100%;
                            }
                          }
                        }
                       .print{
                          display: none;
                        }
                        @media print {
                            .print {
                              display: block;
                            }
                            .no-print {
                              display: none;
                            }
                        }
                      </style>
                        </head>
                        <body>
                          <div class="no-print heading-print">
                            <table class="display-tbl">
                            <tr>
                               <td><h1 style="text-align: center; color: #20407f;  font-size: 30px; font-weight: bold;">Please tap on the screen go back to application.</h1></td>
                            </tr>
                            </table>
                          </div>
                          <div class="print">
                          ${printhtml.innerHTML}
                          </div>
                          <script defer>
                            function triggerPrint(event) {
                              window.removeEventListener('load', triggerPrint, false);
                              setTimeout(function() {
                                closeWindow(window.print());
                              }, ${1000});
                            }
                            function closeWindow(){
                            //window.onfocus = winclose();
                            }
                            function winclose(){
                              window.close();
                            };
                            window.document.body.addEventListener('click', winclose, true);
                            window.document.body.addEventListener('touchstart', winclose, true);
                            window.document.body.addEventListener('touchmove', winclose, true);
                            window.document.body.addEventListener('touchcancel', winclose, true);
                            window.addEventListener('load', triggerPrint, false);
                          </script>
                        </body>
                      </html>`);
              popupWin.document.close();
              if (activeService) {
                activeService.destroy();
                dispatchEvent('afterprint');
              }
            }
            else {

              print.call(window);
              setTimeout(resolve, 1000);
            }
          }, 0);
        });
      },

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Google Chrome latest
> Operating system and its version: Android latest

Note that "latest" is generally not helpful, which is why you should always provide actual version *numbers*.

> PDF.js version: 2.2.171

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Preview and print out sometime is empty

This unfortunately sounds like a *platform and/or browser* specific bug, rather than a PDF.js library/viewer one, especially since it from the description even sounds like it's intermittent; hence this unfortunately doesn't look like something that we can fix here.

Finally, note that code-snippets are generally not all that helpful; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
