### ISSUE TITLE
The pdf preview is displayed normally, but the DOM text is garbled

### ISSUE THREAD

**Issue by happyByteDance** [mozilla/pdf.js#14378]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/7719229/test.pdf)
Configuration:
- Web browser and its version:Firefox version 95.0 (x64)
- Operating system and its version:macOS version 10.15.7

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/96180924/146184300-3519bc7d-179d-48e2-9b2f-75c9851b8419.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/96180924/146184464-49ff1c60-244d-4a84-bbc6-2c638ae29694.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *always required* in order for any issue to be actionable.

Furthermore, please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue (currently e.g. the PDF.js version number is missing).

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.12.248` in Firefox Nightly 97 on Windows.

Hence I can only assume that this was an issue in *older* versions of the library, however given that you've not stated which PDF.js version(s) you're using (which is *explicitly* asked for in the ISSUE_TEMPLATE) and/or which versions are used in the respective screen-shot, we unfortunately cannot really provide further assistance here!

**Comment by happyByteDance** [comment]
Hello, thank you very much for being able to solve this problem, I think this may be a bug in PDF.js
