### ISSUE TITLE
Large PDF Document cannot be opened with PDF.js Webviewer

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#14382]
Attach (recommended) or Link to PDF file here:
When trying to open the attached customer document which contains large number of pages in PDF.js web viewer, it fails to open .

Configuration:
- Web browser and its version:  chrome latest version
- Operating system and its version: Windows
- PDF.js version: 2.10.377
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached pdf document from the webviewer
2. 

What is the expected behavior? (add screenshot)
The document opens on the webviewer. 
What went wrong? (add screenshot)
The viewer tries to open the file and later becomes unresponsive
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> When trying to open the attached customer document which contains large number of pages in PDF.js web viewer, it fails to open .

As has been mentioned previously, this part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable.

**Comment by venkatabana** [comment]
Large pdf for testing DaejaVirtualViewer

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus We are trying to upload a large PDF which is causing the issue to this ticket but it is not allowing. It shows not in list error. Can you please help us on how can we upload large PDF Documents?

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus We are trying to upload a PDF of size 309MB and 65315 pages but the attach files does not allow us to upload. It says not in list error. Do we have any restriction on the size or number of pages in the PDF which PDF.js viewer allows us to open? Can you please let us know if there is any other way we can upload the PDF in issue?Thanks in advance.
