### ISSUE TITLE
Unnecessary console.log

### ISSUE THREAD

**Issue by pwschaedler** [mozilla/pdf.js#14399]
Attach (recommended) or Link to PDF file here: n/a

Configuration:
- Web browser and its version: Firefox 95.0.2
- Operating system and its version: noticed on both macOS 11.6.2 and Ubuntu 20.04.3 LTS
- PDF.js version: 2.12.313
- Is a browser extension: no

Steps to reproduce the problem:
1. Create a minimal HTML file that loads a PDF, e.g.
```
<embed src="link/to/any/pdf" />
```
2. Open in Firefox and open the developer tools console

What is the expected behavior? (add screenshot)
Not writing to the console.

What went wrong? (add screenshot)
A debug message is written to the console. (Ignore the first two errors in the screenshot, those are a result of such a minimal HTML file.)
<img width="929" alt="Screen Shot 2021-12-23 at 2 11 12 PM" src="https://user-images.githubusercontent.com/8781353/147295791-8447c9bb-4ed3-4286-9c40-be1ebb7532bc.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): The issue is also visible on the official demo page. https://mozilla.github.io/pdf.js/web/viewer.html

The code that produces it is here: https://github.com/mozilla/pdf.js/blob/869b396011b03d00325f2a5d5c01e58841efc312/web/app.js#L1538-L1543

This is an incredibly small issue and the fix is equally small, and I'd be happy to submit a PR for it. Just wanted to check if there's a reason this debug message should come through any time a PDF is ever loaded. As a developer, I'd prefer to not have to see an unnecessary message in the console if possible just because my page loads a PDF.

**Comment by Snuffleupagus** [comment]
That logging can be most helpful when users report bugs, since it provides some basic information about the PDF document and it also contains the PDF.js version number; hence this logging is done on *purpose* and it's existed since "forever".

Please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by pwschaedler** [comment]
@Snuffleupagus I agree and understand that it's helpful information, but in this case I'm not even a user of pdf.js, I'm just... using HTML in Firefox. I just found it a bit misleading since the browser itself is printing console messages that have nothing to do with my own JavaScript. When I first saw the message I thought something in my own code must have been printing it until I realized it was coming from a resource within Firefox itself.

Would it possibly be more effective to have it behind a development flag or some global help information instead, rather than showing to end users by default? Or would you suggest I instead raise this issue with the Firefox team, since this is more a result of Firefox using pdf.js by default to show PDFs?

**Comment by Snuffleupagus** [comment]
> Would it possibly be more effective to have it behind a development flag or some global help information instead, rather than showing to end users by default?

That would make it impossible (or at least much more difficult) for "regular" users to include this information when reporting bugs, which doesn't strike me as a good idea (it could easily lead to more back-and-forth when users report bugs).

> Or would you suggest I instead raise this issue with the Firefox team, since this is more a result of Firefox using pdf.js by default to show PDFs?

Please note that this GitHub repository is where the Firefox PDF Viewer is being developed, and that as mentioned having this debugging information printed in Firefox is overall helpful.
(This is the first time someone has "complained" about this, and while I completely understand that you'd prefer not seeing this message I don't think it's a desirable/necessary change unfortunately.)

**Comment by danvy** [comment]
Can't we just add a flag default to true for no breaking changes so we could remove the the diagnotic console.log output ?
