### ISSUE TITLE
Bookmarks don't work when the /Dest is not well syntaxed

### ISSUE THREAD

**Issue by PamProg** [mozilla/pdf.js#14393]
Attach (recommended) or Link to PDF file here:
Unfortunately I can't share my PDF, but I will paste an extract when opened in a text editor

```
342 0 obj
<</Count 5/First 343 0 R/Last 344 0 R>>
endobj
343 0 obj
<</Dest[4 0 R/XYZ 28.3460006714]/Next 345 0 R/Parent 342 0 R/Title(#Onglet_Onglet 1)>>
endobj
344 0 obj
<</Dest[267 0 R/XYZ 28.3460006714]/Parent 342 0 R/Prev 346 0 R/Title(#Onglet_Onglet 2)>>
endobj
345 0 obj
<</Dest[22 0 R/XYZ 25.5109996796]/Next 347 0 R/Parent 342 0 R/Prev 343 0 R/Title(#Onglet_Onglet 3)>>
endobj
347 0 obj
<</Dest[86 0 R/XYZ 25.5109996796]/Next 346 0 R/Parent 342 0 R/Prev 345 0 R/Title(#Onglet_Onglet 4)>>
endobj
346 0 obj
<</Dest[118 0 R/XYZ 28.3460006714]/Next 344 0 R/Parent 342 0 R/Prev 347 0 R/Title(#Onglet_Onglet 5)>>
endobj
```

Configuration:
- Web browser and its version: Mozilla Firefox 93.0
- Operating system and its version: Windows 10
- PDF.js version: tried on 2.10.377 and 2.11.243
- Is a browser extension: no

Steps to reproduce the problem:
1. Load a PDF with those bad syntaxed /Dest
2. Open the Outlines sidebar and try to click on one of them
3. Nothing happens

What is the expected behavior? (add screenshot)
I'm not sure but on the Chrome PDF viewer, Edge PDF viewer and Acrobat Reader, we navigate to the outline/bookmark as expected.

What went wrong? (add screenshot)
As per the **Destinations** specification : https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.2063217, the /Dest syntax is missing a _top_ and _zoom_ value and this error appear in the console **when I open the document** in the viewer :
![image](https://user-images.githubusercontent.com/29798978/147108449-3e6b3e72-c008-4558-a0a3-caa7e3a7f58d.png)

I tried to add this to my `viewer.js` in the `_bindLink` function :
```
if (!dest[3]) {
  dest[3] = null;
}

if (!dest[4]) {
  dest[4] = null;
}
```
and it seems to work fine (I have another trouble with a container.scrollLeft value when clicking on an outline, but it's for another time).

I'm not sure if we should tried to fix this since the PDF is not well syntaxed, but since other viewers that I tested seems to work, I opened this issue.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> Unfortunately I can't share my PDF, but I will paste an extract when opened in a text editor

Without a test-case, the issue unfortunately isn't actionable; please try to create a *reduced* test-case that demonstrates the problem.

> PDF.js version: tried on 2.10.377 and 2.11.243

Those versions are no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I tried to add this to my `viewer.js` in the `_bindLink` function:

It's unclear what *exact* code you're referring to, since https://github.com/mozilla/pdf.js/blob/master/web/viewer.js doesn't contain the function mentioned above.

> I'm not sure if we should tried to fix this since the PDF is not well syntaxed, but since other viewers that I tested seems to work, I opened this issue.

It most definitely looks like a corrupt PDF document, at least from the description.
Without a test-case that can be used to debug and test this, I'm *very sorry* to say that we cannot really make any "speculative" changes since that always have the potential to break something else.

**Comment by PamProg** [comment]
> Without a test-case, the issue unfortunately isn't actionable; please try to create a reduced test-case that demonstrates the problem.

I understand, I'll try to find that.

> It's unclear what exact code you're referring to, since https://github.com/mozilla/pdf.js/blob/master/web/viewer.js doesn't contain the function mentioned above.

Oh sorry, I meant the `viewer.js` of the Prebuilt version. The code of the `_bindLink` function start at line 9748 in the 2.12.313 legacy version.

> It most definitely looks like a corrupt PDF document, at least from the description.

Yeah, I'm not sure when we can call a PDF corrupted, since mine is still all good while I don't use the outlines/bookmarks sidebar.
But yeah, like you said, I understand that you need the PDF...I'll try to find that ! Thank you

**Comment by Snuffleupagus** [comment]
> * Open the Outlines sidebar and try to click on one of them
> * Nothing happens
>
> [...]
> the /Dest syntax is missing a _top_ and _zoom_ value and this error appear in the console :
> ![image](https://user-images.githubusercontent.com/29798978/147108449-3e6b3e72-c008-4558-a0a3-caa7e3a7f58d.png)

That error looks quite strange, since the outline code does *not* actually invoke the function mentioned in the error; note https://github.com/mozilla/pdf.js/blob/41dab8e7b6c1e2684d4afabb8f02e40a874d8e85/web/pdf_outline_viewer.js#L109-L129

**Comment by PamProg** [comment]
> That error looks quite strange, since the outline code does not actually invoke the function mentioned in the error; 

Sorry again, another clarity mistake. I edit my original post.
The error appear when I open the document in the viewer (or when I open it in Firefox).

I'm still trying to create a basic file where I removed manually the bad syntaxed /Dest to match what I have in my not-shareable PDF.

**Comment by timvandermeij** [comment]
Closing for now since this issue is not actionable as-is. Once you have a PDF document, we can reopen this.
