### ISSUE TITLE
Some of elements are missing on PDF 

### ISSUE THREAD

**Issue by mgifp** [mozilla/pdf.js#14395]
Attach (recommended) or Link to PDF file here:
[WS2810_GiveMoreHoliday_12821_EL.pdf](https://github.com/mozilla/pdf.js/files/7767779/WS2810_GiveMoreHoliday_12821_EL.pdf)

Configuration:
- Web browser and its version: Chrome ver. 96.0.4664.110   64bit
- Operating system and its version - Windows 10 Home 20H2
- PDF.js version - https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension - No

Steps to reproduce the problem:
1. Open the pdf file in https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
![Expected behavior](https://user-images.githubusercontent.com/73522503/147210336-491c182d-f083-4db7-ad1a-459e0656c663.png)

What went wrong? (add screenshot)
![Actual behavior](https://user-images.githubusercontent.com/73522503/147210394-666bc983-7667-4092-9888-4b78a6e0a54a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by quaoaris** [comment]
[WS2810_GiveMoreHoliday_12821_EL_mod2.pdf](https://github.com/mozilla/pdf.js/files/7825000/WS2810_GiveMoreHoliday_12821_EL_mod2.pdf)
This is a simplified testcase with only the pair of scissors (48 kByte)

**Comment by Snuffleupagus** [comment]
According to mozregression this was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1860049, and based on the changelog there my *guess* is that PR #17148 was the one that fixed this.

**Comment by marco-c** [comment]
Do we need to add this PDF to the test cases or are we good with the one added in #17148?
