### ISSUE TITLE
Picture rendering failed

### ISSUE THREAD

**Issue by huhaixiang** [mozilla/pdf.js#14390]
Attach (recommended) or Link to PDF file [here:]
[10.1038nrm.2017.125.pdf](https://github.com/mozilla/pdf.js/files/7743946/10.1038nrm.2017.125.pdf)

Configuration:
- Web browser and its version: Chrome  96.0.4664.55
- Operating system and its version: Mac
- PDF.js version: 2.8.335
- Is a browser extension:

Steps to reproduce the problem:
1. open pdf
2. In the fourth page，Picture rendering failed

What is the expected behavior? (add screenshot)
<img width="536" alt="企业微信截图_18c5312e-7fcf-41ae-8daf-68be064ee2fc" src="https://user-images.githubusercontent.com/16789067/146741038-d9ccdf1d-dd7d-4909-bfaf-82a182b889ff.png">

What went wrong? (add screenshot)

<img width="552" alt="企业微信截图_f9e1f1fd-a2a3-4cbe-98d2-c5d993cd6196" src="https://user-images.githubusercontent.com/16789067/146741271-8d946ba8-d936-4218-8141-0415f90912ba.png">

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.12.248` in Firefox Nightly on Windows.

> PDF.js version: 2.8.335

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
