### ISSUE TITLE
Random pages appear as blank when viewing large pdf document on latest chrome, Firefox and Edge browsers

### ISSUE THREAD

**Issue by springfrolic45** [mozilla/pdf.js#14404]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 96.0.4664.110
- Operating system and its version: Windows 10
- PDF.js version:  1.1.114
- PDFJS.version = '1.1.114';
-PDFJS.build = '3fd44fd';
- Is a browser extension:

Steps to reproduce the problem:
1. Blank pages are displayed when loading large pdf file. Tried with 14 pages
2. Using latest chrome, Firefox, and Edge browser. Same document was rendering properly on older version of browsers
3. Please note that same document loads perfectly fine on IE11 
4. Also same PDF displays absolutely fine when downloaded.  

What is the expected behavior? (add screenshot)
PDF should display correctly.

What went wrong? (add screenshot)
Some pages are appearing as Blank
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

[SamplePDF.pdf](https://github.com/mozilla/pdf.js/files/7780540/SamplePDF.pdf)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.12.248` in Firefox Nightly 97 on Windows.

> PDF.js version:  1.1.114

That version is *over six years old* and consequently no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by springfrolic45** [comment]
Is this issue resolved in latest version?
