### ISSUE TITLE
Highlight went wrong when the text font-size less than the minimum font-size of the browser

### ISSUE THREAD

**Issue by helianthuswhite** [mozilla/pdf.js#14426]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
- Operating system and its version: Intel Mac OS X 10_15_7
- PDF.js version: the latest
- Is a browser extension: no

Steps to reproduce the problem:
1. open the demo in chrome https://mozilla.github.io/pdf.js/web/viewer.html
2. search any word in the pdf, such as 'JavaScript'
3. zoom out the pdf until the minimum font-size less than 12px, and you will see the problem

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/12878076/148487417-63af7e0d-2057-4cd8-8471-5b7e2bb5c6ee.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/12878076/148487329-b5af4efe-00c5-447c-8c2e-80fba1059278.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): 
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by helianthuswhite** [comment]
I have created a pr for this #14427 , thank you for feedback.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

Unfortunately it's not *immediately* clear exactly which browser this actually is; I'm assuming you mean Google Chrome here.

>  PDF.js version: the latest

Sorry, but "the latest" isn't helpful; please always provide an actual version *number*.

> zoom out the pdf until the minimum font-size less than 12px, and you will see the problem

I cannot reproduce this (when testing on Windows) in either Mozilla Firefox Nightly `97.0a1` or Google Chrome Beta `97.0.4692.71` *unless* I manually specify a minimum font-size in the browser settings (that part wasn't entirely clear from the STR).

> I have created a pr for this #14427 , thank you for feedback.

Looking *very* briefly at the patch, it doesn't seem great having to constantly re-compute something that in most browsers won't be set at all. Is there really no way to ensure that these font-properties are always enforced, regardless of browser settings, by using e.g. CSS-rules instead?

**Comment by simpleoo0o** [comment]
I had the same problem with zoom less than 50%
![image](https://user-images.githubusercontent.com/23304206/234205286-2c495a3a-133d-4ed3-8d69-1b1d273d6a97.png)
