### ISSUE TITLE
Pdf cannot be previewed

### ISSUE THREAD

**Issue by 790891601** [mozilla/pdf.js#14422]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome browser 94.0.0
- Operating system and its version: window10
- PDF.js version: 1.10.88
- Is a browser extension: no

Steps to reproduce the problem:
1. Preview PDF

What is the expected behavior? (add screenshot)
Preview PDF should be OK.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/36757025/148351642-37db8340-f6b0-4025-9a24-5a1180c480ec.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): no

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *always required* in order for any issue to actionable and valid.

> PDF.js version: 1.10.88

That version is *over four years old* and (obviously) no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
