### ISSUE TITLE
some code error?

### ISSUE THREAD

**Issue by renzhao1113** [mozilla/pdf.js#14438]
Attach (recommended) or Link to PDF file here:
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/7846269/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: chrome v97.0.4692.7
- Operating system and its version: macOS 10.15.7
- PDF.js version: 2.12.313
- Is a browser extension: no

Steps to reproduce the problem:
1. https://github.com/mozilla/pdf.js/blob/236c8d47864e8ebf593bae21576670b59a7d4988/src/display/base_factory.js#L146-L149
2. https://github.com/mozilla/pdf.js/blob/236c8d47864e8ebf593bae21576670b59a7d4988/src/display/annotation_layer.js#L2073-L2081
3. As in the code above, sometimes 'data.rect' is '[0,0,0,0]', which causes 'this.svgFactory.create' to throw an error, which makes the following for loop stop working. https://github.com/mozilla/pdf.js/blob/236c8d47864e8ebf593bae21576670b59a7d4988/src/display/annotation_layer.js#L2352-L2371

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable.

---

Closing as INCOMPLETE for now, since we unfortunately cannot debug/fix an issue without access to a test-case.

**Comment by renzhao1113** [comment]
> > Attach (recommended) or Link to PDF file here:
> 
> This part of the ISSUE_TEMPLATE is _always required_ in order for any issue to be actionable.
> 
> Closing as INCOMPLETE for now, since we unfortunately cannot debug/fix an issue without access to a test-case.

Sorry, I forgot, I just uploaded the pdf file, is it possible to reopen the iuuse? @Snuffleupagus

**Comment by Snuffleupagus** [comment]
(Also, a more helpful/meaningful issue title wouldn't have hurt here; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#issue)
