### ISSUE TITLE
"Search For Text When I Start Typing" does not work

### ISSUE THREAD

**Issue by maverick74** [mozilla/pdf.js#14436]
Configuration:
- Web browser and its version: Firefox 95
- Operating system and its version: all
- Is a browser extension: no

Steps to reproduce the problem:
1. get the option "Search For Text When I Start Typing" On in Firefox
2. Open a pdf
3. Start typing

What is the expected behavior?
Search bar should come up and start searching in the pdf for the text the user is typing

What went wrong?
Search bar does not come up. User has to hit Ctrl+F everytime

**Comment by calixteman** [comment]
It's a Firefox bug, so I filed one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1749355
