### ISSUE TITLE
Unexpected private name #i. Cannot parse class method with private name.

### ISSUE THREAD

**Issue by danchaseCTS** [mozilla/pdf.js#14431]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web Browser is 
- Operating system and its version: IOS 14.5
- PDF.js version: 2.12.544
- Is a browser extension: No

Steps to reproduce the problem:
1. Ionic Angular App with Capactitor, using package ngx-extended-pdf-viewer. 
2. ionic cap build iOS
3. Run the application in Xcode, and attempt to access the pdf. 

What is the expected behavior? (add screenshot)
Expected behavior is that the PDF Viewer Loads.

What went wrong? (add screenshot)
PDF Toolbar loads, no error messages on the screen, but in the console, pdf.js is not loading.

------ STARTUP JS ERROR ------

⚡️  SyntaxError: Unexpected private name #i. Cannot parse class method with private name.
⚡️  URL: capacitor://localhost/assets/pdf-2.12.544.min.js
⚡️  pdf-2.12.544.min.js:23:0

⚡️  See above for help with debugging blank-screen issues
⚡️  [log] - Done Loading Report

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):n/a

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.12.544

Sorry, but that version number does not correspond to an [official release](https://github.com/mozilla/pdf.js/releases); please find the latest supported releases at https://mozilla.github.io/pdf.js/getting_started/#download

> SyntaxError: Unexpected private name #i. Cannot parse class method with private name.

If you environment/browser doesn't support modern JavaScript, please use a `legacy` build of the PDF.js library. Note that this is mentioned e.g. in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and https://github.com/mozilla/pdfjs-dist/#pdfjs
