### ISSUE TITLE
Include more type definitions in pdfjs-dist

### ISSUE THREAD

**Issue by Majsvaffla** [mozilla/pdf.js#14435]
Hello!

Let me know if i should have opened this issue on the [pdfjs-dist](https://github.com/mozilla/pdfjs-dist) repo but I though here would fit.

I'm using pdfjs-dist and I'm in need of some more types to be exported. I have no idea how the types end up in the dist-repo but would love to open a PR if only someone could point me in the right direction 😃 Since I was using an older version of pdfjs-dist I realize the only type I need that's not in the type defs in the latest release are _PageViewport_ from _[display/display_utils](https://github.com/mozilla/pdf.js/blob/master/src/display/display_utils.js#L153)_.

**Comment by manzarlove** [comment]
Remove my email I have already unsubscribed
