### ISSUE TITLE
The bots are now broken, since the `git://`-protocol is no longer supported

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#14440]
Both of the bots are broken starting today, see the error below, since GitHub has removed support for the `git://`-protocol; please see https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective
```
!!! Error executing command:
git clone git://github.com/mozilla/pdf.js.git .
Cloning into '.'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Based on a cursory look this isn't code originating in https://github.com/mozilla/botio-files-pdfjs, but rather code found in its dependency https://github.com/arturadib/botio

One way to "fix" this would be to implement issue #11851 instead, but given the size/scope of that one we probably need to manually update the bots to allow testing/development to continue working for now.

/cc @brendandahl

**Comment by timvandermeij** [comment]
I don't really understand how, but the build from just now at https://github.com/mozilla/pdf.js/pull/14443#issuecomment-1011356521 worked. Maybe the test command is doing something more?

However, looking at https://github.com/arturadib/botio/blob/9434ca0ede20307f7e1d6efa7e9e559240d72f70/lib/module.js#L88 it may just be a matter of changing Botio's configuration files on the bots, since the repository URL is configurable (given that Botio seems to be a more generic bot framework).

On the slightly longer term we should indeed move towards GitHub Actions, but I need to find some time to actually continue with that (since I think we have most if not all pieces of the puzzle by now)...

**Comment by timvandermeij** [comment]
Good catch! While that does give us some more time to address this, it would already be good to make the (what I assume is a simple) Botio configuration change on both bots to set the repository URL to `http://...` instead of `git://...`.

**Comment by brendandahl** [comment]
The code on the bots is coming from https://github.com/brendandahl/botio.git . Looks like we need to update head_url in a few spots in https://github.com/brendandahl/botio/blob/master/lib/server.js

**Comment by brendandahl** [comment]
I updated the urls in https://github.com/brendandahl/botio/commit/001c01c0053f6f29b484b435c6d8dfbaacba52d9.

**Comment by Snuffleupagus** [comment]
> I updated the urls in [brendandahl/botio@001c01c](https://github.com/brendandahl/botio/commit/001c01c0053f6f29b484b435c6d8dfbaacba52d9).

@brendandahl Were these changes pushed to the bots as well, since it seems that it's now broken again in recent botio runs?

According to https://github.blog/2021-09-01-improving-git-protocol-security-github, support for the `git://`-protocol was removed today.

**Comment by brendandahl** [comment]
Alright, should be working now. There was something weird with the linux bot using a cached version of botio. Wiping out the modules then `npm i` corrected it.

I'm not positive the post merge hook will work as expected. We'll need to check it after the next PR merge and ensure gh-pages is also updated.

**Comment by Snuffleupagus** [comment]
> I'm not positive the post merge hook will work as expected. We'll need to check it after the next PR merge and ensure gh-pages is also updated.

That seems to be working just fine, since the `gh-pages` branch is updating as intended; thanks for fixing this!
