### ISSUE TITLE
base_viewer.js fails with this.linkService._cachedPageNumber in v2.12.313

### ISSUE THREAD

**Issue by schmitch** [mozilla/pdf.js#14442]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Firefox/Chrome, latest version
- Operating system and its version:
Linux,Windows,mac
- PDF.js version:
v2.12.313
- Is a browser extension:
no

Steps to reproduce the problem:
1. create a custom viewer with 
```
async function getViewer() {
const viewer = await import(/* webpackChunkName: 'pdfviewer' */ 'pdfjs-dist/web/pdf_viewer');
const eventBus = new viewer.EventBus();
return viewer.PDFSinglePageViewer({
        container,
        eventBus,
        useOnlyCssZoom: USE_ONLY_CSS_ZOOM,
        // We can enable text/annotations layers, if needed
        textLayerFactory: new viewer.DefaultTextLayerFactory(),
        annotationLayerFactory: new viewer.DefaultAnnotationLayerFactory(),
        // textLayerMode: TextLayerMode.ENABLE,
        // currently the SVG renderer is not supported
        // and it has problems with telekom documents
        // so it will be disabled until it is feature complete
        // renderer: 'svg'
    });
}
```
2. console prints an error:
```
Unable to get page for page view TypeError: this.linkService._cachedPageNumber is not a function
    ensurePdfPageLoaded_fn base_viewer.js:1502
```
    
Looks like the problem is `IPDFLinkService` which is actually using the default one `this.linkService = options.linkService || new SimpleLinkService();` which does not have this function. of course we can use `PDFLinkService` which will probably work.

**Comment by Snuffleupagus** [comment]
> create a custom viewer with

Please note that it's highly recommended to follow https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js instead, which shouldn't be affected by this issue.

**Comment by schmitch** [comment]
btw. we did follow it, but we also followed the "optional" path `// (Optionally) enable hyperlinks within PDF files.` since we do not want to use hyperlinks within the pdf.

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting!
