### ISSUE TITLE
wrong UTF-8 display for PDF-2 document

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#14449]
Attach (recommended) or Link to PDF file here:

[Actually downloaded from <https://github.com/pdf-association/pdf20examples/raw/master/pdf20-utf8-test.pdf>](https://github.com/mozilla/pdf.js/files/7871477/pdf20-utf8-test.pdf)

Configuration:
- Web browser and its version: _Firefox 96_.
- Operating system and its version: _Windows 7_.
- PDF.js version: the one that comes with _Firefox 96_.
- Is a browser extension: I think so.

Steps to reproduce the problem:
1. Open the file metadata, bookmarks and layers are displayed wrong.
2. The explanation on how this works for PDF-2 seems to be https://www.pdfa.org/understanding-utf-8-in-pdf-2-0/. 

What is the expected behavior? (add screenshot)

Right character display.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment]
I've the same bad rendering on Windows in Firefox (nightly), Chrome and Acrobat DC.
But it looks good with Foxit.
