### ISSUE TITLE
Unify bugzilla and github tags/labels

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#14452]
Currently, we have different tags and labels on github and bugzilla which makes find all the bugs related to one label difficult. I propose we have the same tags and do some clean up while we're at it.

In bugzilla we've usually done pdfjs-`c/d/f`-`name` where c=category, d=detail, f=flag. I've never found the category useful. Only the part in the detail or flag has helped me find bugs, so I think we should get rid of the letters and only have the part after d/f. e.g. [pdfjs-d-blend-mode] becomes [pdfjs-blend-mode].

For github, we have the number before the label. Similar to the category on bugzilla, I don't usually find the number helpful (I don't even really remember what all the numbers mean). I propose we drop the numbers and just use more detailed ones that match up with bugzilla.

**Comment by anantraghuvanshi** [comment]
@brendandahl  In such cases, we could use tags/labels which are specific to certain other problems and which depicts some meaning to the reader, like help-wanted, enhancements, bugs, question, or problems. Along with that, if we consider extra precision, then we could add something like difficulty or understanding level required, which could be basic, easy, medium, hard, or expert.

**Comment by brendandahl** [comment]
I went through the labels and compared to bugzilla. It seems most line up pretty well. Most of the clean up will be on the bugzilla side.

For github, I plan to drop the number before the label unless there are any objections.

**Comment by Snuffleupagus** [comment]
> For github, I plan to drop the number before the label unless there are any objections.

That change seems totally fine to me, since I've ever really known what the numbers are/were supposed to represent anyway :-)

**Comment by Snuffleupagus** [comment]
> For github, I plan to drop the number before the label unless there are any objections.

That change seems totally fine to me, since I've never really known what the numbers are/were supposed to represent anyway :-)

**Comment by timvandermeij** [comment]
I agree; the numbers never really made sense to me anyway.

**Comment by brendandahl** [comment]
Alright, numbers removed. Whiteboard tags in https://docs.google.com/spreadsheets/d/1_7foFdAoR4lu64qJQe9k4zODTIUxkGstcrO6LKZ0WqU/edit#gid=0
