### ISSUE TITLE
PDF rendering problem

### ISSUE THREAD

**Issue by suganyaji** [mozilla/pdf.js#14462]
Attach (recommended) or Link to PDF file here:
[test2-3.pdf](https://github.com/mozilla/pdf.js/files/7881930/test2-3.pdf)

Configuration:
- Web browser and its version: Chrome and Version 93.0.4577.63
- Operating system and its version: Ubuntu 20.04.1 LTS
- PDF.js version: v2.12.313
- Is a browser extension: No

What is the expected behavior? 
![Screenshot from 2022-01-17 18-21-02](https://user-images.githubusercontent.com/29357161/149772453-5906d92a-7cf5-458f-8315-695d78aa9674.png)

What went wrong? 
![Screenshot from 2022-01-17 18-20-24](https://user-images.githubusercontent.com/29357161/149772465-07dd71ef-5d41-42c9-8b13-466f8eee116a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by calixteman** [comment]
I can confirm the bug in Firefox nightly on Windows 10.
