### ISSUE TITLE
Odd Font Issue with certain fonts

### ISSUE THREAD

**Issue by jbis9051** [mozilla/pdf.js#14472]
Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1749400

PDF: https://bug1749400.bmoattachments.org/attachment.cgi?id=9258524

**Comment by marco-c** [comment]
No need to open a duplicate issue on GitHub.

**Comment by jbis9051** [comment]
Ah. I apologize, wasn't sure if pdfjs team accessed issues on bugzilla.
