### ISSUE TITLE
Large PDF of size 309 MB and 65000 pages cannot be opened in pdf.js viewer

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#14475]
Attach (recommended) or Link to PDF file here:
I am not able to open a large PDF of 309 MB and 65000 pages in pdf.js viewer. I tried uploading the large pdf to this ticket but it says not in list error. 
Do we have any restriction or maximum size supported by pdf.js viewer? Thanks in advance. 

Configuration:
- Web browser and its version: chrome 
- Operating system and its version: Windows
- PDF.js version:2.12.313
- Is a browser extension:

Steps to reproduce the problem:
1. Open a large PDF of size more than 300 MB and 65000 pages
2. PDF.js viewer becomes unresponsive and does not open the pdf in the viewer. 

What is the expected behavior? (add screenshot)
PDF should be opened
What went wrong? (add screenshot)
Viewer becomes unresponsive and clicking further gives  a Aw Snap error. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I tried uploading the large pdf to this ticket but it says not in list error.

That sounds like a GitHub limitation, so not really something that we can help with here unfortunately.
You'd probably need to upload the file elsewhere (e.g. using a file hosting service), and link to that here.

> * Open a large PDF of size more than 300 MB and 65000 pages
> * PDF.js viewer becomes unresponsive and does not open the pdf in the viewer.

Handling of very large PDF documents was improved *slightly* recently (for the default viewer), however the combination of both the file size and the number of pages may simply be a bit too much to handle comfortably for a PDF parser/viewer implemented in JavaScript.

Closing as INCOMPLETE, given the lack of a test-case. (It might also be WONTFIX, given the document size).

**Comment by rpatnani** [comment]
Jonas, Could you please provide the limitation of the size and number of pages supported by viewer.

**Comment by rpatnani** [comment]
@Snuffleupagus Could you please provide the limitation of the size and number of pages supported by viewer.
