### ISSUE TITLE
Iframe insert page , download lose efficacy

### ISSUE THREAD

**Issue by wmo123** [mozilla/pdf.js#14477]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 97.0.4692.71(正式版本）
- Operating system and its version: Mac OS 10.14.6
- PDF.js version:2.12.313
- Is a browser extension: no

Steps to reproduce the problem:
1. I used pdfjs in my react project，the way is: `<iframe src='generic-legacy/web/viewer.html?file=xx'></frame>`,everything is ok, then,I deployed the project to the server, i get a page url (just name it a.page);
2. in my another react project，i wanna insert a.page in this way: `<iframe src='a.page'></frame>`, then, i can normally preview pdf   as i expected, it can print、zoom in/out....., but, download lose efficacy，then i debug in ‘download-manager.js’ , seems to a.click()  don't trigger,i don't know whether it caused by inserting too much iframe?

What is the expected behavior? (add screenshot)
download be efficacy;
What went wrong? (add screenshot)
<img width="510" alt="131d1a8e72f235099c3bddb6c710453" src="https://user-images.githubusercontent.com/47963460/150488435-e0e40a12-4260-4f8a-bde3-3829c1b73a80.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I used pdfjs in my react project

Unfortunately we know nothing about React, or other frameworks, here and consequently we cannot provide support for that.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by wmo123** [comment]
my fault，i‘ve set sandbox attribute for iframe, so, download doesn't work.
