### ISSUE TITLE
Unit-test "should validate a phone number on a keystroke event" fails after PR 14430

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#14488]
It appears that the unit-tests were never run in PR #14430, since one of the test-cases now fail consistently:
https://github.com/mozilla/pdf.js/blob/88236e11635b103ccff781d69da2ca280c289e87/test/unit/scripting_spec.js#L1096-L1176

Also, looking very briefly at that unit-test I cannot help but wonder if the [updated `GenericScripting.dispatchEventInSandbox`-method](https://github.com/mozilla/pdf.js/blob/88236e11635b103ccff781d69da2ca280c289e87/web/generic_scripting.js#L57-L60) is connected to the regression since it'll now resolve *before* the event has been dispatched?
Should we perhaps do something like the below diff now, or is this perhaps unrelated to the problem?
```diff
@@ -56,7 +56,12 @@ class GenericScripting {

   async dispatchEventInSandbox(event) {
     const sandbox = await this._ready;
-    setTimeout(() => sandbox.dispatchEvent(event), 0);
+    return new Promise(resolve => {
+      setTimeout(() => {
+        sandbox.dispatchEvent(event);
+        resolve();
+      }, 0);
+    });
   }
```

/cc @calixteman

**Comment by calixteman** [comment]
After debugging, it is due to this change:
https://github.com/mozilla/pdf.js/commit/6ac296e48e52a8940f6a869c44f768edb4674a7b#diff-388aefce79f87599ad89abb4759ed56c669e2e53c21ee1889b11f223ff7a524aR154

**Comment by calixteman** [comment]
The issue is in the test itself, I'm fixing.
