### ISSUE TITLE
How to disable rendering acrofield data in getPage() / getDocument() method

### ISSUE THREAD

**Issue by mrszympek** [mozilla/pdf.js#14480]
Problem / Question:
Hi!  Is it possible to NOT render acrofield/acroforms data on pdf? 

Here's sample pdf file I'm using - https://pastebin.com/1V9yPE1B.

What I'm doing 
1. PDFJS.getDocument(url)
2. Map over each page, page.getPage() and create canvases using page.render() method.

Maybe theres some method to remove acrofields data from pdf before rendering it to png/canvas.

What I expect:
Render pdf file without any data.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/23b6fde9fc92b827f054e21978e32ce9c13dab82/src/display/api.js#L1143-L1154, which given the (somewhat limited) information provided is probably the only help we can provide.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mrszympek** [comment]
@Snuffleupagus, thank's for reply. Unfortunately it doesn't work for me.

Here's a code sample.
`    await page.render({
      canvasContext: canvas.getContext('2d'),
      viewport,
      annotationMode: 0
    });`

Here you can see how it renders.
![Screenshot 2022-01-23 at 12 57 16](https://user-images.githubusercontent.com/13149889/150678731-71879615-c82d-4ec0-84c4-37b95fa0f690.png)

I'd like to get those grey areas empty.
