### ISSUE TITLE
Possibility to hide certain page

### ISSUE THREAD

**Issue by minedun6** [mozilla/pdf.js#14484]
I am using the pdfjs viewer.

I have a need to hide certain pages after document load.
Is there any way to achieve such feature ?
Is it already in the api of the viewer, or can you point me in the right direction ?

**Comment by Snuffleupagus** [comment]
No, since this isn't an intended use-case for this library (or the viewer); closing as answered.

**Comment by minedun6** [comment]
Is there any workaround ?
Or can you point me in the right direction ?
