### ISSUE TITLE
Present mode doesn't fullscreen when pdf is embedded

### ISSUE THREAD

**Issue by fwsmit** [mozilla/pdf.js#14499]
First of all, note that I don't think this behaviour is bad currently, I'm just making you aware. I actually rely on this behaviour, so please don't change it before the below mentioned alternative is implemented.

Configuration:

- Web browser and its version: firefox 96.0.2
- Operating system and its version: Arch linux, sway (wayland)
- PDF.js version: Whatever came with the browser
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a web page with an embedded PDF
2. Press the present button on the PDF

What is the expected behavior? (add screenshot)

The more correct and consistent behaviour would be to present the PDF in full screen.

What went wrong? (add screenshot)

It expands the pdf to fill the window (just the way it shows in the demo). Pressing the button again will still not present the pdf in full screen. For now this is to me better than presenting, since I more often want to view the PDF expanded to the whole window. But ideally, when the pdf is embedded, there would be a separate button that would allow you to expand the pdf

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

I cannot link the website, since you have to log in. You'll need to find a website that embeds PDF's, I suppose using an iframe.

**Comment by Snuffleupagus** [comment]
> I cannot link the website, since you have to log in. You'll need to find a website that embeds PDF's, I suppose using an iframe.

Unfortunately that makes it somewhat difficult to follow the provided STR, since using e.g. https://pdfobject.com/static/ I cannot actually reproduce any of this (on Windows).
Please note that e.g. an `<iframe>` can use the `allowfullscreen` attribute to control whether or not the FullScreen API (which is what the PDF.js viewer uses for PresentationMode) is actually allowed to be used. Hence this issue, to me at least, certainly *sounds* like it might actually work as expected!?

**Comment by Snuffleupagus** [comment]
> But ideally, when the pdf is embedded, there would be a separate button that would allow you to expand the pdf

Actually, there already is: Please note the "Current view..." button on the right-hand side of the toolbar, which you can either middle-click or right-click (and then choose e.g. open in new tab) in order to get a full-sized viewer.

**Comment by fwsmit** [comment]
![image](https://user-images.githubusercontent.com/23078054/151152360-d0164cec-eeb7-4d43-b454-6eab035153bc.png)

Hmm, this view is different than any of the views on the website you linked. There's no download or current view button. There's only a download button separate from pdf.js on the page itself. I guess I'm allowed to share the code they use to show the pdf:

```html
<div class="d2l-messagearea d2l_1_36_577" id="d2l_messagearea"></div><div id="ContentView" class="d2l-placeholder d2l-placeholder-live">
        <div id="d2l_le_content_printcontainer">
                <div class="d2l-fileviewer"><div class="d2l-fileviewer-pdf-pdfjs" id="d2l_1_38_266" data-location="/content/some/location" data-title="title.pdf" data-culture="en-us" data-is-always-fully-expanded="0" data-is-download-enabled="1" data-is-fullscreen-button-hidden="0" data-isprintable="True" data-update-pdfjs="1"><div id="id" class="d2l-placeholder d2l-placeholder-live">
                </div>
        </div></div>
        </div>
</div>

...

<div class="d2l-fileviewer-pdf-pdfjs" id="d2l_1_38_266" data-location="/some/location" data-title="title.pdf" data-culture="en-us" data-is-always-fully-expanded="0" data-is-download-enabled="1" data-is-fullscreen-button-hidden="0" data-isprintable="True" data-update-pdfjs="1"><div id="d2l_1_37_708" class="d2l-placeholder d2l-placeholder-live" aria-live="assertive">
							</div>
							<iframe class="d2l-fileviewer-rendered-pdf" scrolling="no" seamless="seamless" style="width: 100%; height: 700px;" src="/some/location" title="title.pdf"></iframe></div>

...

<iframe class="d2l-fileviewer-rendered-pdf" scrolling="no" seamless="seamless" style="width: 100%; height: 700px;" src="/some/location" title="title.pdf"></iframe>

```

I tried copying the relevant parts.

**Comment by Snuffleupagus** [comment]
Thank you for the screen-shot, and the excerpt from the HTML code!
Based on your initial description and this additional information, it actually confirms my suspicion that what you're seeing is a *custom* PDF.js viewer with (some) modified/removed functionality. Unfortunately, this is not something we can help with and you'll need to contact that web-page directly for support; sorry about that.

*Slightly off-topic, but:* This sort of confusion is exactly why we ask those who use the PDF.js viewer, in custom implementations, to change its appearance to not unnecessarily mislead users into thinking it's the Firefox *built-in* PDF Viewer that they're seeing.

**Comment by fwsmit** [comment]
Thank you for your patience and explanation. There seem to be some other buttons missing as well. I have no idea why they would make a custom version just to remove some functionality.

> Slightly off-topic, but: This sort of confusion is exactly why we ask those who embed the PDF.js viewer, in custom implementations, to change its appearance to not unnecessarily mislead users into thinking it's the Firefox built-in PDF Viewer that they're seeing.

Yes I agree. What could also help on your side is adding some version info in the dropdown below document properties and make sure firefox sets their version to something different.

**Comment by Snuffleupagus** [comment]
Note that Firefox will always print the PDF.js version number in the console, when the *built-in* PDF Viewer is being invoked. For example, in Firefox Nightly 98, when opening http://mirrors.ctan.org/info/lshort/english/lshort.pdf the following line is printed (with the version number last):
```
PDF 458436452feb268d340a4b6564fe9133 [1.5 xdvipdfmx (20190824) / LaTeX with hyperref] (PDF.js: 2.13.24)
```

> What could also help on your side is adding some version info in the dropdown below document properties and make sure firefox sets their version to something different.

Unfortunately it'd be impossible to prevent a custom viewer from accidentally, or even deliberately, displaying the same exact version information. Hence this probably wouldn't help all that much, see also issue #5884.

**Comment by fwsmit** [comment]
> Note that Firefox will always print the PDF.js version number in the console, when the _built-in_ PDF Viewer is being invoked. For example, in Firefox Nightly 98, when opening http://mirrors.ctan.org/info/lshort/english/lshort.pdf the following line is printed (with the version number last):

Interesting. When opening that pdf,  I get the string

```
PDF 458436452feb268d340a4b6564fe9133 [1.5 xdvipdfmx (20190824) / LaTeX with hyperref] (PDF.js: 2.12.248)
```

But when opening the page this issue is about I also get a string, namely:

```
PDF 284c6bc89fcf4626d4dd4a60d14d9f90 [1.5 MiKTeX pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.9.0)
```

It seems that non built-in versions of pdf.js also print their version string to console.


> Unfortunately it'd be impossible to prevent a custom viewer from accidentally, or even deliberately, displaying the same exact version information. Hence this probably wouldn't help all that much, see also issue #5884.

True, but it not being the default would probably prevent most cases of that happening. I don't think many vendors will set their string the same on purpose. It seems from the linked issue that it's mostly a case of not thinking it's neccesary.

**Comment by Snuffleupagus** [comment]
> When opening that pdf, I get the string
> ```
> PDF 458436452feb268d340a4b6564fe9133 [1.5 xdvipdfmx (20190824) / LaTeX with hyperref] (PDF.js: 2.12.248)
> ```

That's because you're using Firefox 96, which given that it's older (than the current Nightly) simply contains an older PDF.js version as well.

> ```
> PDF 284c6bc89fcf4626d4dd4a60d14d9f90 [1.5 MiKTeX pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.9.0)
> ```
> It seems that non built-in versions of pdf.js also print their version string to console.

Please note that a non-built version doesn't actually have a version number, and in that case `... (PDF.js: -)` would've been printed instead.
Hence the conclusion is that they've somehow *incorrectly* built the library/viewer, since a version number such as the quoted one has never existed.

> It seems from the linked issue that it's mostly a case of not thinking it's neccesary.

There's also the fact that all code needs to be both implemented *and* then maintained going forward, and it's somewhat questionable if this feature (another dialog box) wouldn't be enough of a special-case to not really be worth it here.
