### ISSUE TITLE
getTextContent Returns wrong text (with spaces removed)

### ISSUE THREAD

**Issue by 1Map** [mozilla/pdf.js#14497]
In the attached image below:
1) **H2** is picked up correctly
2) **17,79** is picked up correctly
3) **256 36 30**  is picked up wrong as 2563630 (without spaces)

Before this used to work.  Now I am having trouble getting the correct text.  I tried setting the parameters below on getTextContent to true or false, but no luck.

- 	normalizeWhitespace
- 	disableCombineTextItems
- 	includeMarkedContent

<img width="296" alt="image" src="https://user-images.githubusercontent.com/1152458/151077931-9dab03bb-b9a3-48e7-b4cc-e58aca62f3ab.png">

The sample is on the attached PDF (Page 2)

<img width="80" alt="image" src="https://user-images.githubusercontent.com/1152458/151080121-7aecdec5-24b4-4431-92c0-3fb779262572.png">

[e335bb3d-9b84-47eb-8238-a903095668af.pdf](https://github.com/mozilla/pdf.js/files/7938019/e335bb3d-9b84-47eb-8238-a903095668af.pdf)

**Comment by Snuffleupagus** [comment]
> Before this used to work.

What versions are you comparing?
Furthermore, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (by actually filling out the template) since as-is most of it is unfortunately missing.

**Comment by 1Map** [comment]
Attach (recommended) or Link to PDF file here:

[e335bb3d-9b84-47eb-8238-a903095668af.pdf](https://github.com/mozilla/pdf.js/files/7940558/e335bb3d-9b84-47eb-8238-a903095668af.pdf)


Configuration:

Web browser and its version: 
Microsoft Edge Version 97.0.1072.69 64bit

Operating system and its version: 
Windows 11 64bit

PDF.js version:
2.12.313 (Not Working)
2.4.456 (Working)

Is a browser extension: 
No

Steps to reproduce the problem: 
1. Use getTextContent with various settings to 
normalizeWhitespace
disableCombineTextItems
includeMarkedContent


What is the expected behavior? (add screenshot)
Certain Text with spaces, when rotated at certain angle, the spaces should not be removed
![image](https://user-images.githubusercontent.com/1152458/151140537-4847448e-71ca-4911-97ea-a47cfdec388a.png)


What went wrong? (add screenshot)
Certain Text with spaces, when rotated at certain angle, the spaces are removed (Screenshot taken as example from page 2 in the attached PDF file)
![image](https://user-images.githubusercontent.com/1152458/151140521-e7928e1b-890b-41a0-957a-cb184f9ff176.png)

**Comment by calixteman** [comment]
Most of the numbers, whitespaces, ... are written using a `Tj` command with each time only one character.
So for a whitespace, we fall in this case:
https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2578
(`isWhitespace===true && i === 0`)
and the whitespace should be added when we compare the position of the 3 with one of the 6.
But the positions of the glyphs are taking into account the textMatrix transformation which can have scale factors but:
 - https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2502
 - https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2309
shows that `negativeSpaceMax` doesn't take into account this scale factor and the whitespace is not detected.
I need to think about that to be sure that my diagnostic is good but it's very likely something around this.

**Comment by 1Map** [comment]
Hi @calixteman 

Thanks,  I have attached a smaller test pdf file with just a couple of text.  Note that I highlighted the ones giving problem in red.  Here the spaces are removed (which should not be).  Funny thing is that some of them are Ok.  You can also see this picture if you open the test pdf in Firefox and select "Select All..." to highlight what is picked up.


<img width="783" alt="image" src="https://user-images.githubusercontent.com/1152458/151165012-9be90a16-a4df-49e0-8dfc-4618ade50c21.png">

Attached PDF: 
[Test.pdf](https://github.com/mozilla/pdf.js/files/7941757/Test.pdf)

**Comment by calixteman** [comment]
In fact I was wrong:
 - we update correctly the scale factor: https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2322
 - and it's correctly cancelled when we compare glyphs positions: https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2496

The real problem is that we don't correctly take into account the rotation from the current transform:
https://github.com/mozilla/pdf.js/blob/5c3b24595854ae8e4fd1490ceb3d712c58143f57/src/core/evaluator.js#L2409

The fix is to unapply the rotation matrix before comparing glyphes positions.

**Comment by 1Map** [comment]
Thanks @calixteman,

Ok, so how do I go about fixing it on my side for now?

**Comment by calixteman** [comment]
I'll push my PR in few minutes.
@1Map, anyway, can I add the file Test.pdf in the test suite ?

**Comment by 1Map** [comment]
@calixteman 

> I'll push my PR in few minutes. @1Map, anyway, can I add the file Test.pdf in the test suite ?

Yes, you may.

**Comment by 1Map** [comment]
Hi @calixteman 

I am not so familiar with Github.  I use the legacy build from pdfjs-dist. How would I go about to include your changes on my side?

**Comment by 1Map** [comment]
Don't worry, I managed to build it with gulp.
