### ISSUE TITLE
Font size is too big when printing pdfs with input text fields

### ISSUE THREAD

**Issue by marlonhort** [mozilla/pdf.js#14502]
Attach (recommended) or Link to PDF file here:
[Pdfjs bug.pdf](https://github.com/mozilla/pdf.js/files/7952983/Pdfjs.bug.pdf)

Configuration:
- Web browser and its version: Firefox 96.0.2 (64-bit)
- Operating system and its version: MacOS Big Sur
- PDF.js version: Latest v2.12.313
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open a pdf that has an input text field, 
2. Add some content to the input field
3. Try to print it, notice that the font size of the content added to the input fields is much bigger on the print preview, in many cases being cut from the printed version.

What is the expected behavior? (add screenshot)
All the content added to the input field should be printed in a very similar way to the one being displayed during the edition.

What went wrong? (add screenshot)
Much bigger font being used during the print preview and final printed version as well, where in many cases the content gets cut.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
![Pdfjs bug - latest Firefox](https://user-images.githubusercontent.com/29414577/151243040-a625d7f1-72f0-49e3-b552-eac0488c460d.gif)

**Comment by marco-c** [comment]
Same root cause as https://bugzilla.mozilla.org/show_bug.cgi?id=1721970 or https://bugzilla.mozilla.org/show_bug.cgi?id=1747071?

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* when opening an issue, since as-is this unfortunately isn't actionable.

**Comment by marlonhort** [comment]
@Snuffleupagus I added the pdf I used there, let me know if you need something else.

**Comment by bozzmedia** [comment]
Still running into this issue, exactly as the OP example demonstrates. Is there a manual font size setting?

FF 119.0 (64-bit), Win10

**Comment by dannyash** [comment]
Issue is still present in 123.0.1 (64-bit) on Win11.

**Comment by RikkiBC** [comment]
Issue still present on v128.0 on Linux (Linux Mint, 64-bit).

**Comment by Shamaoke** [comment]
Has anybody found any solution to that so far?

**Comment by JakenVeina** [comment]
I was able to work around this by going outside of Firefox to Adobe Reader, and adding an empty space at the end of each oversized input. Then that magically quit working.

This issue is not fixed and should be re-opened.

**Comment by rtpt-romankarwacik** [comment]
The issue was apparently not fixed by @calixteman pull request, can this be reopened?
