### ISSUE TITLE
How to make the pdf fit the whole canvas without scaling the page too

### ISSUE THREAD

**Issue by InesBorgesCore** [mozilla/pdf.js#14504]
Configuration:
- Web browser and its version: Chrome latest version
- Operating system and its version: Windows 10
- PDF.js version: latest version CDN
- Is a browser extension:

This is the aspect of the page with the loading of the pdf into the webpage:
![image](https://user-images.githubusercontent.com/86775909/151347639-5ca394dd-3ded-41dd-8094-e2e8a2a0211c.png)

This is the aspect of the page without loading the pdf:
![image](https://user-images.githubusercontent.com/86775909/151347831-660b60c8-88d8-4d07-a802-e31b1ae8c2e6.png)

I want the buttons and the images to **not** scale down when I load the PDF. How can I do that? I want them to stay the same size. But I want the PDF to **fit** the viewport and show all its content like it is doing in the first screenshot.

**Comment by Snuffleupagus** [comment]
> * PDF.js version: latest version CDN

Please provide an actual version *number*, since "latest" unfortunately isn't helpful.

Furthermore, given that this is primarily a *bug tracker*, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by InesBorgesCore** [comment]
Could you please provide me a working example of embedding a PDF into an iframe with pdf.js showing only the first page and using a base64 string as a pdf input?
PS.: I can´t find the version of pdf.js I am using. But is this [cdn](//mozilla.github.io/pdf.js/build/pdf.js)

**Comment by Snuffleupagus** [comment]
Please find the interactive examples in https://mozilla.github.io/pdf.js/examples/ and also additional ones in https://github.com/mozilla/pdf.js/tree/master/examples for basic usage.

> But is this [cdn](//mozilla.github.io/pdf.js/build/pdf.js)

That's *really not* intended to be used as a CDN; please see https://mozilla.github.io/pdf.js/getting_started/#including-via-a-cdn

**Comment by InesBorgesCore** [comment]
I was able to do what I wanted by the means of this piece of code:
`scale = window.innerWidth / (page.view[2] - 10);`

-10 is just to give it some margin so it doesn't stick to the edges of the page
