### ISSUE TITLE
The `normalizeWhitespace = false` option now is being (mostly) ignored

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#14519]
After the changes in PR #14428, the [`normalizeWhitespace` option](https://github.com/mozilla/pdf.js/blob/1087b4dffdf5884ad17669fda54c59dd810667d3/src/display/api.js#L1072-L1073) is now in most (or perhaps even all) cases being ignored and treated as if `normalizeWhitespace = true` is passed to the `PDFPageProxy.{getTextContent, streamTextContent}` methods.[1]

With the changes in PR #14428 we're now handling all whitespaces *consistently* in the `PartialEvaluator.getTextContent` method, which together with other (somewhat) recent improvements have fixed many textLayer issues by handling both coalescing of repeated spaces and proper space insertion between text chunks.
Looking briefly at this code, it seems to me that trying to re-instate "proper" `normalizeWhitespace = false` handling would be quite difficult and would likely hurt readability (assuming it's even at all possible now).
Furthermore, note that in both the viewer and the browser-tests we're only ever using `normalizeWhitespace = true` which means that the other code-path isn't really used all that much.

All-in-all, I'd probably suggest that we simply remove the `normalizeWhitespace` option and make the relevant methods always carry out the normalization since that's what e.g. the viewer uses.

Any thoughts/opinions about this?
/cc @timvandermeij 
/cc @calixteman 

---
[1] One example is the `issue6612.pdf` document in the test-suite, added together with the option, where "regular" spaces are now being returned regardless of the `normalizeWhitespace` value.

**Comment by calixteman** [comment]
I fully agree: most of the spaces are ignored whatever they are so it probably doesn't make sense to keep it anymore.
So +1 to remove it.
If we really want to keep it, then to have a correct behaviour, I think it should be enough to add a  `!normalizeSpace` in the if condition:
https://github.com/mozilla/pdf.js/blob/1087b4dffdf5884ad17669fda54c59dd810667d3/src/core/evaluator.js#L2595-L2602
this way a space is treated as any other character.

**Comment by Snuffleupagus** [comment]
> Do you happen to know why this option was ever introduced in the first place, since I'm wondering why this wasn't already the default in the first place?

It was done simply to not break the old default behaviour of `getTextContent`, but as you say that behaviour doesn't really seem very useful in general (e.g. in the viewer).

While we could perhaps re-introduce a "working" `normalizeWhitespace = false` option, along the lines of https://github.com/mozilla/pdf.js/issues/14519#issuecomment-1025709083, it seems to me doing so *could* lead to multiple consecutive whitespaces being inserted in the output (which "recent" changes have tried hard to avoid).

**Comment by bobsquito** [comment]
Is there any alternative to this?

I use an npm package which uses pdf.js to extract text. I wanted to find why text which was previously coming through with newline characters is now all on one line which really changes the usability of it. It also appears there is a bug somewhere as the newline characters don't seem to come through as replaced with a space and are just removed, but I don't understand enough of this to understand what/where that is occurring.

I can't see an alternative in the pdf.js api to get just get the text as is now that option is removed, or is pdf.js not the right thing to be using to extract text?

**Comment by durlabhjain** [comment]
I've couple of patches for v 3.11 and 4.0. The changes are both similar in pdf.worker.js. In the buildTextContentItem method, we commented out the code block:

```
        /*if (category.isWhitespace) {
          if (!font.vertical) {
            charSpacing += scaledDim + textState.wordSpacing;
            textState.translateTextMatrix(charSpacing * textState.textHScale, 0);
          } else {
            charSpacing += -scaledDim + textState.wordSpacing;
            textState.translateTextMatrix(0, -charSpacing);
          }
          saveLastChar(" ");
          continue;
        }*/
```

and 

```
        /*if (saveLastChar(glyphUnicode)) {
          textChunk.str.push(" ");
        }*/
```

With this, we are getting the desired/ comparable results like earlier behavior. I will try to create a pull request when I get a breather.
[pdfjs-dist+3.11.174.patch](https://github.com/mozilla/pdf.js/files/13490404/pdfjs-dist%2B3.11.174.patch)
[pdfjs-dist+4.0.269.patch](https://github.com/mozilla/pdf.js/files/13490408/pdfjs-dist%2B4.0.269.patch)

I hope it helps

**Comment by Snuffleupagus** [comment]
> I will try to create a pull request when I get a breather.

As you can see from the discussion above this was *purposely* removed, hence we're not going to bring this option back unfortunately.
