### ISSUE TITLE
Dev build broken on chrome 97

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#14512]
Using `gulp server` and loading in Chrome 97 I get the error:

```
es-module-shims.js:769 ReferenceError: require is not defined
    at checkStructuredClone (compatibility.js:114:5)
    at compatibility.js:115:5
```

This appears to be a regression from #14392
@Snuffleupagus

**Comment by Snuffleupagus** [comment]
Also, given that Google Chrome 98 will become the *stable version* in only three days my preference would definitely be that we simply WONTFIX this issue; please see https://chromestatus.com/features/schedule

**Comment by timvandermeij** [comment]
I agree given that Chrome 98 will be stable in two days from now.
