### ISSUE TITLE
Add/Edit/Delete Bookmark in an existing PDF

### ISSUE THREAD

**Issue by soubhikchatterjee** [mozilla/pdf.js#14528]
Is it possible to Add/Edit/Delete Bookmark in an existing PDF and save those changes in the pdf file?

**Comment by Snuffleupagus** [comment]
There's no general editing capabilities (except filling of forms) in the PDF.js library, note also the README at https://github.com/mozilla/pdf.js#pdfjs-:

> [PDF.js](https://mozilla.github.io/pdf.js/) is a Portable Document Format (PDF) viewer that is built with HTML5.

*For future reference:* This issue doesn't really contain enough information/context to be easily understandable/actionable.
