### ISSUE TITLE
feat(web-viewer): link display popover

### ISSUE THREAD

**Issue by ShaMan123** [mozilla/pdf.js#14529]
Hi guys,
Amazing work you've done here. Thanks!
I would like to propose (and willing to PR) that internal links (pointing to place inside the document) will show as popovers on hover.
I was thinking of 2 ways to implement this:
1. `iframe` - need to pass the file down to pdf.js somehow
2. use internals

I'd use some help pointing to the right direction, and a place in the code to get started at
Thanks again

**Comment by Snuffleupagus** [comment]
Duplicate of #5835
