### ISSUE TITLE
How to extract images from PDF files

### ISSUE THREAD

**Issue by yewanji** [mozilla/pdf.js#14542]
I found a problem when I used PDFJS to preview PDF files, sometimes the embedded pictures are very small, I want to realize the function of clicking to enlarge the pictures, may I ask whether the PDFJS class library supports extracting the pictures inside

**Comment by Snuffleupagus** [comment]
*Once again:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this is first and foremost a *bug tracker* and this issue doesn't contain nearly enough information in order to be actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

The following unit-test shows one way of extracting images from a PDF document, however given the various ways in which "images" can be included in PDF documents that's not going to cover everything (also keep in mind that image-extraction isn't the intended/primary use-case for the PDF.js library):
https://github.com/mozilla/pdf.js/blob/acc758c40c55209c05beb9e93e620026b7f72c22/test/unit/api_spec.js#L2264-L2277

**Comment by tienhoangkhmt** [comment]
@timvandermeij,  I still can't get the image in the pdf file, can you take a look at my source code
https://codesandbox.io/s/vibrant-poitras-kdz7hh?file=/src/App.js:822-830

**Comment by d-schneid** [comment]
> The following unit-test shows one way of extracting images from a PDF document, however given the various ways in which "images" can be included in PDF documents that's not going to cover everything (also keep in mind that image-extraction isn't the intended/primary use-case for the PDF.js library):
> 
> https://github.com/mozilla/pdf.js/blob/acc758c40c55209c05beb9e93e620026b7f72c22/test/unit/api_spec.js#L2264-L2277

For me, this code works for `.jpg` images embedded in the `PDF`.
However, for other types of images (i.e. `.png`) it does not work.
I get this error: `Requesting object that isn't resolved yet img_p1_1.`

Any hints how I can solve this?

**Comment by IsraPerez98** [comment]
@d-schneid I was facing the same issue as you getting something like `Requesting object that isn't resolved yet img_p1_1.`

The solution for me is to instead of awaiting pdfPage.objs.get, you should use the callback like:

```
page.objs.get(index (resolved) => {
}
```

Even better, i wrote this small promisified version in TS to fix this

```
async function promisifiedPDFGetObject(page: PDFPageProxy, index: string) {
    return new Promise((resolve, reject) => {
        page.objs.get(index, (resolved: unknown) => {
            if (resolved) {
                resolve(resolved);
            } else {
                reject(new Error('Error getting object'));
            }
        });
    });
}
```

**Comment by fallingleaflun** [comment]
@IsraPerez98  Hello, I tried your snippet, and it looks like this:
```
for (const i of rawImgOperators) {
    const imgIndex = operatorList.argsArray[i][0];
    await new Promise<void>((resolve) => {
        page.objs.get(imgIndex, async (imageRef: any) => {
            const canvas = document.createElement('canvas');
            canvas.width = imageRef.width;
            canvas.height = imageRef.height;
            const context = canvas.getContext('2d');
            if (!context) {
                resolve();
                return;
            }

            const data = new Uint8ClampedArray(imageRef.width * imageRef.height * 4);
            if (imageRef.data.length === imageRef.width * imageRef.height * 3) {
                let k = 0;
                let i = 0;
                while (i < imageRef.data.length) {
                    data[k] = imageRef.data[i]; // r
                    data[k + 1] = imageRef.data[i + 1]; // g
                    data[k + 2] = imageRef.data[i + 2]; // b
                    data[k + 3] = 255; // a
                    i += 3;
                    k += 4;
                }
            } else if (imageRef.data.length === imageRef.width * imageRef.height * 4) {
                data.set(imageRef.data);
            } else {
                console.error('Unsupported image format');
                resolve();
                return;
            }

            const imgData = context.createImageData(imageRef.width, imageRef.height);
            imgData.data.set(data);
            context.putImageData(imgData, 0, 0);

            const imgBlob = await new Promise<Blob | null>((resolveBlob) => canvas.toBlob(resolveBlob));
            if (imgBlob) {
                images.push(imgBlob);
            }
            resolve();
        });
    });
}
```

It works fine when there are only a few images. However, when I repeat the same page and get a PDF that contains many images, I find that after several loops, the breakpoint stops at `await new Promise<void>((resolve) => {`, and then the program pauses. The line `const canvas = document.createElement('canvas');` is never reached.

Could you help me understand why this is happening and how to fix it?

**Comment by fallingleaflun** [comment]
https://github.com/mozilla/pdf.js/discussions/19864#discussioncomment-12944421
