### ISSUE TITLE
metadata.d.ts invalid character #private

### ISSUE THREAD

**Issue by Abrarahmed8** [mozilla/pdf.js#14550]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. npm install pdfjs-dist
2.ng serve

metadata.d.ts invalid character #private

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is most of the necessary details are unfortunately missing.

> Steps to reproduce the problem:
>     1. npm install pdfjs-dist
>     2. ng serve

I'm guessing that "ng serve" is Angular related, but please note that we cannot provide any help/support for various frameworks.
Finally, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mdebeus** [comment]
I too am getting the same error, but when compiling my project when it contains pdfjs-dist. 
The version being compiled into my project is: pdfjs-dist@2.12.313. 
I have the following installed typescript related libraries:
  typescript: 3.43
 @babel/plugin-syntax-typescriptThe compiler error is: 7.3.3
 @babel/plugin-transform-typescript 7.4.0
 @babel/preset-typescript: 7.1.0
 awesome-typescript-loader: 5.2.1
 I am building with webpack version 4.30 and webpack_cli version: 3.3.0 with node version 10.24.1

For me, the error message does not include the invalid character, but I suspect it is the same one:
ERROR in ...\node_modules\pdfjs-dist\types\src\display\metadata.d.ts
[tsl] ERROR in ...\node_modules\pdfjs-dist\types\src\display\metadata.d.ts(10,5)
      TS1127: Invalid character.

**Comment by tanchekwei** [comment]
`npm i @types/pdfjs-dist` fix the issue.

source: https://github.com/VadimDez/ng2-pdf-viewer/issues/877#issuecomment-1138471975
