### ISSUE TITLE
PDF rendering issue with Embedded Subset fonts

### ISSUE THREAD

**Issue by d-amruta** [mozilla/pdf.js#14556]
We are using pdf.js library for PDF viewer module of our web application. The web application is deployed in Tomcat (version:9.0.45) on Linux system (CentOS Linux 7). We noticed that with version 2.0.943, text in PDF is rendered as white boxes or unusual symbols. We also observed the same issue after upgrading to version 2.2.228. The issue is observed when PDF file contains Embedded Subset fonts. We noticed that we get different results with different host environments. When we have our application deployed using Docker container, the PDF seems to render better. 
We would like to understand - 
1. Where pdfjs gets the fonts from when it can't find or load embedded fonts?
2. If someone can tell us a way to at least get some better fonts in the right places then it would be helpful.

Attach (recommended) or Link to PDF file here:
[Test-Font-Rendering.pdf](https://github.com/mozilla/pdf.js/files/8050856/Test-Font-Rendering.pdf)

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.82
- Operating system and its version: CentOS Linux 7 (Core)     Kernel: Linux 3.10.0-1160.15.2.el7.x86_64 
- PDF.js version: 2.0.943 and 2.2.228
- Is a browser extension: No

Steps to reproduce the problem:  
The issue has been observed when we upload and view the attached PDF file in our web application which is deployed using Tomcat

What is the expected behavior? (add screenshot)
The attached PDF file should render fine without any white boxes or unusual symbols.

What went wrong? (add screenshot)
![PDF_Font_Rendering_1](https://user-images.githubusercontent.com/99489253/153648593-407c5851-6d19-4ef9-8b87-3f55abddde34.PNG)
![PDF_Font_Rendering_2](https://user-images.githubusercontent.com/99489253/153648634-9e6d49c7-38ec-4d99-8313-1cf19ba90c4a.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [Test-Font-Rendering.pdf](https://github.com/mozilla/pdf.js/files/8050856/Test-Font-Rendering.pdf)

WFM, using PDF.js version `2.13.93` in Firefox Nightly 99.

> PDF.js version: 2.0.943 and 2.2.228

Neither of those versions are supported any more, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
> The issue has been observed when we upload and view the attached PDF file in our web application which is deployed using Tomcat

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by d-amruta** [comment]
Hello @Snuffleupagus , Thank you for taking a look at this. As suggested, we will try the latest release to see if it helps the issue that we are seeing in our environment. We would still like to understand couple of things that I mentioned above in the issue description. If you could you please share any info for below queries then it would be really helpful.

   1. Where pdfjs gets the fonts from when it can't find or load embedded fonts?
   2. If someone can tell us a way to at least get some better fonts in the right places then it would be helpful.

Thank you.

**Comment by rekhakhatri1212** [comment]
I'm also facing the exact same issue. I'm working on pdfjs upgrade. Current version in my project is 2.0.550 and my goal is to use the latest version available(2.12.313). As soon as I move one version up to 2.0.943, the same PDF is rendering fine in one environment and not working in another. Is there any resolution to this?
I would also like to know the answers to the above questions by @d-amruta.
