### ISSUE TITLE
Nested xform object in tiling pattern not displayed

### ISSUE THREAD

**Issue by jsiefer** [mozilla/pdf.js#14568]
Attach (recommended) or Link to PDF file here: [missing-rect.pdf](https://github.com/mozilla/pdf.js/files/8073442/missing-rect.pdf)

Configuration:
- Web browser and its version: FF 97.0
- Operating system and its version: OSX
- PDF.js version: 2.13.24
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open [missing-rect.pdf](https://github.com/mozilla/pdf.js/files/8073442/missing-rect.pdf)

What is the expected behavior? (add screenshot)

<img width="300" alt="expected" src="https://user-images.githubusercontent.com/6014388/154120761-6185ce18-69f1-44c9-9be1-8ece01a69b02.png">

What went wrong? (add screenshot)

<img width="300" alt="actual" src="https://user-images.githubusercontent.com/6014388/154120949-d5758749-c495-4d60-9608-196df5a1ad8c.png">

**Comment by jsiefer** [comment]
The issue seem to be the negative bounding boxes in the Form XObj that holds the pattern.

**Comment by Snuffleupagus** [comment]
Duplicate of #16038
