### ISSUE TITLE
"Unexpected token '+' " when trying to import pdf.js on Safari

### ISSUE THREAD

**Issue by klonspace** [mozilla/pdf.js#14576]
When trying to use PDF.js in combination with Quasar, I get an unexpected token error in safari. This happens as soon as the library is imported, I don't need to actually execute any functions with it to trigger the error.

Quasar uses webpack under the hood so I am using the webpack version, as well as worker-loader 3.0.8.

Configuration:
- Web browser and its version: Safari 13.1.3
- Operating system and its version: Mac OSX Catalina 10.15.7
- PDF.js version: pdf.js-dist ^2.12.313
- Is a browser extension: no

I can set up a demo if this isn't sufficient information. Looking around online I saw people recommending to use an ES5 build, but I can'd any info regarding this in the docs.

**Comment by Snuffleupagus** [comment]
You want to use a `legacy` build in that case, please see https://github.com/mozilla/pdfjs-dist/tree/master/legacy, which is mentioned e.g. in https://github.com/mozilla/pdfjs-dist#pdfjs
