### ISSUE TITLE
A Functional request for a restful viewer/editor

### ISSUE THREAD

**Issue by keyhan** [mozilla/pdf.js#14574]
PDF.js has recently gotten functionality to fill and save PDF forms. It is a good idea then to let that functionality also sip into the viewer.js and allow it to save the PDF on the same URL it retrieved it from.

I mean if PDFJS do a GET to a open a PDF from a certain URL, it should be possible to do POST to the same URL to save the updated PDF. So instead of or addition to a "download" button there should be a save button.

A bonus point would be also be able to flatten the PDF so it would not be possible to edit it further, but that is not as important.

**Comment by Snuffleupagus** [comment]
> I mean if PDFJS do a GET to a open a PDF from a certain URL, it should be possible to do POST to the same URL to save the updated PDF. So instead of or addition to a "download" button there should be a save button.

That would add a lot of code/complexity for a use-case that doesn't really apply to the Firefox *built-in* PDF Viewer, i.e. the main reason for this library existing in the first place, for something that seems arguable like a very niche use-case.
There's also potentially (quite severe) security problems with allowing e.g. form data to be *easily* sent to a remote server, which is also a reason for the scripting-implementation not supporting any network functionality.

Please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---

> A bonus point would be also be able to flatten the PDF so it would not be possible to edit it further, but that is not as important.

That'd require *arbitrary editing* of PDF documents, which is a use-case that this library isn't really intended for; please note that the README contains the following line (emphasis mine):
> [PDF.js](https://mozilla.github.io/pdf.js/) is a Portable Document Format (PDF) ***viewer*** that is built with HTML5.

**Comment by keyhan** [comment]
The security is also an issue when you retrieve the document. The server could just refrain from accepting a POST if it does not allow it. Again, when you have a functionality like filling a form or annotating a PDF, it is really a natural step to be able to also save it on the server and not just download it.

**Comment by marco-c** [comment]
@keyhan even if we were able to resolve the security concerns, this is not generic enough. 99,9999999% of servers won't do anything with a POST request.
If a website wants to support editing a PDF and saving it to the server, they should bundle pdf.js as a library in their site and support the POST request themselves.

**Comment by keyhan** [comment]
I bet you if you implement it there would be many that actually would and then it would be an incentive to use Firefox :).

**Comment by keyhan** [comment]
And again if you can do a get and retrieve the PDF, it means you accept request from the client. If you implement POST for that endpoint it means you are OK with people posting to it.

**Comment by Snuffleupagus** [comment]
> The security is also an issue when you retrieve the document.

That is in no way even comparable, since downloading a file from a server is a lot safer than *submitting potentially sensitive* user-data (in a PDF form) back to a random (and potentially "evil") server.

**Comment by keyhan** [comment]
OK, I do not undestand random here? You do send to exact same server you retrieved from?

**Comment by keyhan** [comment]
I mean you do GET https://company.com/file.pdf and then you do POST https://company.com/file.pdf if the company is evil why do GET if you are evil why would company accept POST?

**Comment by Snuffleupagus** [comment]
> You do send to exact same server you retrieved from?

That's beside the point, since there's no guarantee that the original server is "safe". All this just seems like a great opportunity to allow an evil actor to more easily carry out a phishing attack, since an "average user" would have a difficult time knowing if the web-site is indeed safe to use (for submitting a PDF form).

> I mean you do GET https : // company.com/file.pdf and then you do POST https: // company.com/file.pdf if the company is evil why do GET if you are evil why would company accept POST?

Just fetching the data doesn't really expose any *potentially sensitive* user-data, whereas submitting a filled-in PDF form back to the server could include *anything* (e.g. social security numbers and similarly sensitive data).

---

This really is WONTFIX, for the reasons already outlined above.

**Comment by keyhan** [comment]
You cannot fix security problems by not allowing client to send data, in that case we should not be able to send these messages to each other.
