### ISSUE TITLE
TypeError: PDFJS.getDocument is not a function

### ISSUE THREAD

**Issue by Jibbolito** [mozilla/pdf.js#14573]
Hello everyone, 

first of all I did read a lot of former posts, just like this: https://github.com/mozilla/pdf.js/issues/9075 . And they all seem to have the same problem, that they are missing "promise". I did include promise and still have the same issue. Here is where I use getDocument() (oriented at https://mozilla.github.io/pdf.js/examples/):

`
PDFJS.getDocument(data).promise.then((pdf) => {
        pdf.getPage(1).then(page => {
            //do sth.
        })
    })
`

I am really unsure what I am doing wrong. A little hint would be very useful. ;) Thanks in advance!

**Comment by Snuffleupagus** [comment]
Please note that the `PDFJS` global was removed *years ago* (the mentioned issue is from 2017), hence that won't work now; you'll need to use `pdfjsLib.getDocument` as shown on https://mozilla.github.io/pdf.js/examples/.

As-is it's unfortunately impossible to provide any further assistance, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
