### ISSUE TITLE
Links which are present in annotation layer are not working(external as well as internal)?

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [mozilla/pdf.js#14586]
Attach (recommended) or Link to PDF file here: http://www.pdfill.com/example/pdf_commenting_new.pdf

Configuration:
- Web browser and its version: Firefox 96.0
- Operating system and its version: Ubuntu 20.04
- PDF.js version: 2.12.313
- Is a browser extension: It is a cordova app

Steps to reproduce the problem:
1. I am trying to create a PDF Viewer page. I implemented text layer but when i add annotation. No links are working either internal or external. Also no popup appears when i hover over an annotation. My implementation using pdfjs is:-

        import $ from 'dom7';
        import DownloadManager from './pdf_js/web/download_manager.js';
        import {PDFLinkService,SimpleLinkService} from './pdf_js/web/pdf_link_service.js';
        import {PDFViewer} from './pdf_js/web/pdf_viewer.js';
	
        let pdfWrapper={
                DownloadManager:new DownloadManager(),
		loadPage:function(lib,pageNum,pdf,canvas,textlayer,annotationlayer){
			/*
				here lib is a reference from pdfjslib
				pdf:- pdf returned from loadingtask
			*/
		     pdf.getPage(pageNum).then(function(page){
	
				textlayer.empty();
	
				var scale=1.5;
				var viewport=page.getViewport({scale:scale});		
				var context = canvas[0].getContext('2d');
				canvas[0].height=viewport.height;
				canvas[0].width=viewport.width;

				var renderContext={
					canvasContext:context,
					viewport:viewport
				};
	
				var renderTask=page.render(renderContext);
				renderTask.promise.then(function(){
					page.getAnnotations().then(function(annotationData){
						pdfWrapper.showAnnotation(annotationlayer,canvas);
						
						lib.externalLinkTarget=lib.LinkTarget.BLANK;
						lib.AnnotationLayer.render({
	        				viewport: viewport.clone({ dontFlip: true }),
	        				div: annotationlayer[0],
	        				annotations: annotationData,
	        				page: page,
	        				downloadManager:DownloadManager,
	        				linkService:new PDFLinkService({
	        					externalLinkTarget:lib.LinkTarget.BLANK
	        				}),
	        				imageResourcesPath: '/static/images/',
	    				});
					});
					
					page.getTextContent().then(function(textcontent){
						pdfWrapper.showText(textlayer,canvas);
	 
						lib.renderTextLayer({
							textContent:textcontent,
							container:textlayer[0],
							viewport:viewport,
							textDivs:[],
							enhanceTextSelection:true
						});
					});
				});
			});
		},
		showText:function(textlayer,canvas){
			var canvas_offset=canvas.offset();
			var canvas_width=canvas[0].width;
			var canvas_height=canvas[0].height;
	
			textlayer.css({
					left: canvas_offset.left + 'px',
				top: canvas_offset.top + 'px',
				height: canvas_height + 'px',
				width: canvas_width + 'px' 
			});
		},
		showAnnotation:function(annotationLayer,canvas){
			var canvas_offset=canvas.offset();
			var canvas_width=canvas[0].width;
			var canvas_height=canvas[0].height;

			annotationLayer.css({
				left: canvas_offset.left + 'px',
				top: canvas_offset.top + 'px',
				height: canvas_height + 'px',
				width: canvas_width + 'px'
			});
		}
	   }
	   export default pdfWrapper;

What is the expected behavior? (add screenshot)
Links should work and popup should we visible when we hover over the annotation.
![When we hover over annotation](https://user-images.githubusercontent.com/37043052/154846190-1640ad66-49e4-4831-a1f2-21516db42158.png)
![the link](https://user-images.githubusercontent.com/37043052/154846216-41375d52-0d95-42e1-8eb2-6bdcb5128738.png)

What went wrong? (add screenshot)
![No popup](https://user-images.githubusercontent.com/37043052/154846327-29779e03-6f4e-4d7d-9166-6bb46b19826c.png)
Neither external or internal links are working.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: http://www.pdfill.com/example/pdf_commenting_new.pdf

WFM, when using the default viewer; see https://github.com/mozilla/pdf.js#online-demo

> I am trying to create a PDF Viewer page. I implemented text layer but when i add annotation. No links are working either internal or external.

Please try using the viewer components examples instead (e.g. the `simpleviewer` one), since they should already support both text-selection and annotations/forms out-of-the box; refer to https://github.com/mozilla/pdf.js/tree/master/examples/components

> My implementation using pdfjs is:

Please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by GAGANsinghmsitece** [comment]
Hi, I tried using the components but i am trying for custom implementation due to following reasons:-
1.  I need to implement find function later on and i did not find any component doing it.
2. I am rendering one page at a time and i think this might be the reason why internal links might not be working but i believe external link must work.
I created a github repository which demonstrate the problem.
https://github.com/GAGANsinghmsitece/Annotation
What i understand is annotation must be firing some event on link click or hover action but i am unable to find documentation relating to the events.

**Comment by Snuffleupagus** [comment]
> 1. I need to implement find function later on and i did not find any component doing it.

Please see https://github.com/mozilla/pdf.js/blob/3635a9a3338feb0049be4f1521d5a5afd173a832/examples/components/simpleviewer.js#L51-L55 and https://github.com/mozilla/pdf.js/blob/3635a9a3338feb0049be4f1521d5a5afd173a832/examples/components/simpleviewer.js#L78-L85

> 2. I am rendering one page at a time

In that case, please use the `singlepageviewer` example instead.
