### ISSUE TITLE
Syntax Error: ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema

### ISSUE THREAD

**Issue by hengshanMWC** [mozilla/pdf.js#14603]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome/98.0.4758.102
- Operating system and its version: Mac OS X 10_15_7
- PDF.js version: 2.6.347
- Is a browser extension: no

Steps to reproduce the problem:
1.  yarn add -D worker-loader
2. use worker-loader
<img width="418" alt="image" src="https://user-images.githubusercontent.com/45714422/155648098-39125e76-1219-4ac9-a440-4f43a3c4965e.png">

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
<img width="929" alt="image" src="https://user-images.githubusercontent.com/45714422/155647560-b5db2589-32bd-4a1c-8d04-ecc5fb80d58d.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. yarn add -D worker-loader
>     2. use worker-loader

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
