### ISSUE TITLE
Text search is not able to identify text, but working with other pdf viewers

### ISSUE THREAD

**Issue by NareshYeddula25** [mozilla/pdf.js#14627]
Attach (recommended)
[Issue_Document.pdf](https://github.com/mozilla/pdf.js/files/8176877/Issue_Document.pdf)
 or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome and Version 98.0.4758.102 
- Operating system and its version: Windows 10
- PDF.js version: Using  "ngx-extended-pdf-viewer": "^12.0.0-alpha.2" which a wrapper around Mozilla's PDF viewer
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached pdf document in 'https://mozilla.github.io/pdf.js/web/viewer.html?'
2. Search for text 'message persists' and 0 results are found
3. Open the attached document with Chrome 
4. Search for text 'message persists' and '1' result is found
5. Open the attached document in Adobe Acrobat Reader
6. Search for text 'message persists' and '1' result is found

What is the expected behavior? (add screenshot) 
Search result for 'message persists' should be 1

> 

**CHROME:**

![image](https://user-images.githubusercontent.com/83689440/156544876-00a04401-68b0-4087-aa4a-330666e44fe6.png)

**ADOBE ACROBAT READER**

![image](https://user-images.githubusercontent.com/83689440/156544978-e95b2e8b-7dcc-4347-a832-dd4f65b7fa36.png)

What went wrong? (add screenshot)
Pdf.js not able to find the text 'message persists'.

**Pdf.js**

![image](https://user-images.githubusercontent.com/83689440/156545187-21ca3752-6754-4c3a-b7ea-c5f3a1e18424.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by marco-c** [comment]
We are not detecting the space between "message" and "persists". If you look for "messagepersists", a result is found.

**Comment by NareshYeddula25** [comment]
> We are not detecting the space between "message" and "persists". If you look for "messagepersists", a result is found.

Yes, but why it is different with other viewers

**Comment by marco-c** [comment]
> Yes, but why it is different with other viewers

It is a bug in pdf.js that we have to fix :)

**Comment by calixteman** [comment]
There is a final whitespace at the end of the Tj for `message`, but it's skipped thanks to:
https://github.com/mozilla/pdf.js/blob/234aa9a50e33599c28877ac3b5fff3542c55cd61/src/core/evaluator.js#L2601
and so it isn't correctly detected when we begin with `persists`.
The text is likely not what it's displayed: the selection in Acrobat looks weird:
![image](https://user-images.githubusercontent.com/5641725/156549752-03b6eb27-82f4-4e51-a09f-87ce25b217f5.png)

**Comment by Snuffleupagus** [comment]
> The text is likely not what it's displayed: the selection in Acrobat looks weird:

The "text" is actually an image, with invisible text (using a zero fill-alpha rather than the invisible text-rendering mode) placed on top for text-selection and searching purposes.
Furthermore, there's a bunch of what appears to be completely unnecessary font-size changes in this "invisible" text, that I assume contribute to the problems we see with guessing where spaces should should be inserted.

**Comment by NareshYeddula25** [comment]
> There is a final whitespace at the end of the Tj for `message`, but it's skipped thanks to:
> 
> https://github.com/mozilla/pdf.js/blob/234aa9a50e33599c28877ac3b5fff3542c55cd61/src/core/evaluator.js#L2601
> 
> 
> and so it isn't correctly detected when we begin with `persists`.
> The text is likely not what it's displayed: the selection in Acrobat looks weird:
> ![image](https://user-images.githubusercontent.com/5641725/156549752-03b6eb27-82f4-4e51-a09f-87ce25b217f5.p

> There is a final whitespace at the end of the Tj for `message`, but it's skipped thanks to:
> 
> https://github.com/mozilla/pdf.js/blob/234aa9a50e33599c28877ac3b5fff3542c55cd61/src/core/evaluator.js#L2601
> 
> 
> and so it isn't correctly detected when we begin with `persists`.
> The text is likely not what it's displayed: the selection in Acrobat looks weird:
> ![image](https://user-images.githubusercontent.com/5641725/156549752-03b6eb27-82f4-4e51-a09f-87ce25b217f5.png)

Page content on this pdf is written using PDFTRON. The original pdf had image in it to which content is written using PDFTRON

**Comment by calixteman** [comment]
We already added an exception to keep whitespaces when they're between two non-whitespaces whatever the extra spacing (negative or not) can be, so I guess we can extend that.
