### ISSUE TITLE
pdfjs demo url doesnt work on Firefox 86

### ISSUE THREAD

**Issue by dhananjay14u** [mozilla/pdf.js#14639]
I am not able to launch demo viewer on Mozilal firefox 86. 

Is there any limitations with an year old browsers. I need to implement latest pdfjs with an application that has support for 
Chrome 86 , Firefox 86, Edge 86. 

As a sanity check - I am not able to load demo viewer on firefox 86.

Demo url : https://mozilla.github.io/pdf.js/web/viewer.html

Please advice. 

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

What is the expected behavior? (add screenshot)
Demo url should launch with sample pdf document when opened in firefox 86

What went wrong? (add screenshot)
Blank screen, buttons like upload document is also not working.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I am not able to launch demo viewer on Mozilal firefox 86.

Please note that that version is even older than the current ESR version (which is currently based on Firefox `91`), and for security reasons it's *never* a good idea to use old and (now) unsupported browsers.

However, for anything except the latest browsers, please note the two different kind of builds provided in https://github.com/mozilla/pdf.js#online-demo and https://mozilla.github.io/pdf.js/getting_started/#download
