### ISSUE TITLE
pdf报错问题

### ISSUE THREAD

**Issue by jackming123l** [mozilla/pdf.js#14643]
vue项目使用"pdfjs-dist": "^2.12.313"版本的报错 
vue脚手架： @vue/cli 4.5.15
vue： ^2.6.11
error  in ./node_modules/pdfjs-dist/build/pdf.js

Module parse failed: Unexpected token (2094:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   async destroy() {
|     this.destroyed = true;
>     await this._transport?.destroy();
|     this._transport = null;
|

**Comment by Snuffleupagus** [comment]
First of all, please note that you need to communicate *only in English* when using this bug tracker!
Secondly, please note that we don't know anything about various frameworks (i.e. Vue in this case) here and cannot really provide support for that.
Finally, please make sure that you read all of https://github.com/mozilla/pdfjs-dist/blob/master/README.md

**Comment by hu19940121** [comment]
我也遇到了这个问题 你觉

> vue项目使用"pdfjs-dist": "^2.12.313"版本的报错 vue脚手架： @vue/cli 4.5.15 vue： ^2.6.11 error in ./node_modules/pdfjs-dist/build/pdf.js
> 
> Module parse failed: Unexpected token (2094:26) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders | async destroy() { | this.destroyed = true;
> 
> > ```
> > await this._transport?.destroy();
> > ```
> 
> | this._transport = null; |

我也遇到了这个问题 你解决了吗

**Comment by dogedogezzz** [comment]
@jackming123l @hu19940121 pdfjs使用了async/await，没有通过babel编译浏览器不认识，在vue.config给他配置一个babel-loader进去就行了，另外～在GitHub上提问还是用英语最好

**Comment by shawbs** [comment]
> @jackming123l @hu19940121 pdfjs使用了async/await，没有通过babel编译，在vue.config给他配置一个babel-loader进去就行了，另外～在GitHub上提问还是用英语最好

不会配置，大佬是怎么弄的？

**Comment by Cv-Engineer123** [comment]
> > @jackming123l @hu19940121 pdfjs使用了async/await，没有通过babel编译，在vue.config给他配置一个babel-loader进去就行了，另外～在GitHub上提问还是用英语最好
> 
> 不会配置，大佬是怎么弄的？

就是你用loader时 额外把.worker.js文件添加到babel编译就行了，一般babel不会对node_modules内的模块编译

**Comment by exhibition315** [comment]
這套件 export 給用戶的是 mjs 檔案，沒有透過 babel 編譯
所以你的錯誤是因為用到了optional chaining 這個 js 的寫法
要解決就必須將 node_modules/pdfjs-dist 做 babel 轉譯
