### ISSUE TITLE
Checkbox not checked when using pdfjs-dist library

### ISSUE THREAD

**Issue by stefandutoit** [mozilla/pdf.js#14657]
Attach (recommended) or Link to PDF file here:
[Certificate 110608.pdf](https://github.com/mozilla/pdf.js/files/8224197/Certificate.110608.pdf)

Configuration:
- Web browser and its version:
   Chrome - Version 99.0.4844.51 (Official Build) (64-bit)
   Edge - Version 99.0.1150.36 (Official build) (64-bit)
   Firefox
- Operating system and its version:
   Windows 10
- PDF.js version: 2.13.216 (Using pdfjs-dist),
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open the PDF in a viewer using the '**pdfjs-dist**' library.
2. On Page 1, checkbox 4.10 (Retail Trade) should be checked. It is not checked.

What is the expected behavior? (add screenshot)
On Page 1, checkbox 4.10 (Retail Trade) should be checked. The screenshot below is using PDF.JS viewer sample at https://mozilla.github.io/pdf.js/web/viewer.html shows the checkbox correctly checked.
![image](https://user-images.githubusercontent.com/60884238/157683988-eb1e5b57-f27e-4082-872b-03fdbf3af02e.png)

What went wrong? (add screenshot)
On Page 1, checkbox 4.10 (Retail Trade) should be checked. It is not checked. The screenshot below is using the **pdfjs-dist** library library from a React project.
![image](https://user-images.githubusercontent.com/60884238/157684094-5a152644-b3a7-410b-ac59-9c62a60819c8.png)

The only possible hint about a problem is the following warnings in the console.

Warning: loadFont - translateFont failed: "TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from undefinedFoxitDingbats.pfb".
pdf.js:479 Warning: Error during font loading: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from undefinedFoxitDingbats.pfb

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> The only possible hint about a problem is the following warnings in the console.
> [,,,]

This suggests that you didn't provide the `standardFontDataUrl` parameter when calling `getDocument`, or possibly that you didn't provide a valid value (it must be a string), please see
https://github.com/mozilla/pdf.js/blob/ee39499a5ab6063fdc5cf58df81ad5b36bd8efed/src/display/api.js#L168-L169

However, without seeing your actual code it's difficult to help more; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by stefandutoit** [comment]
@Snuffleupagus, here is sample code:

https://jsfiddle.net/73vrftuy/2/

**Comment by Snuffleupagus** [comment]
> here is sample code:
> https://jsfiddle.net/73vrftuy/2/

That code appears to be missing the required parameter, as mentioned above in https://github.com/mozilla/pdf.js/issues/14657#issuecomment-1064168705.

**Comment by stefandutoit** [comment]
@Snuffleupagus, are you saying the standardFontDataUrl parameter is missing.  Where should that URL point to?  Thanks for your assistance.

**Comment by Snuffleupagus** [comment]
> are you saying the standardFontDataUrl parameter is missing.

Yes, since in the example code that you provided it's not being set in the `getDocument` call.

> Where should that URL point to?

For *testing* purposes only, I suppose that you can try using `"https://mozilla.github.io/pdf.js/web/standard_fonts/"`.

However, in production you should either host all the PDF.js files yourself (with your application) or load them from a CDN; see https://mozilla.github.io/pdf.js/getting_started/#including-via-a-cdn

**Comment by iamart** [comment]
Why is this a required parameter? It is optional as per types.
