### ISSUE TITLE
PDF rendering is quite slow with some PDFs, compared to other viewers

### ISSUE THREAD

**Issue by soadzoor** [mozilla/pdf.js#14652]
**Attach (recommended) or Link to PDF file here:**
[Floor2.pdf](https://github.com/mozilla/pdf.js/files/8214771/Floor2.pdf)

**Configuration:**
- Web browser and its version: Chrome 99.0.4844.51
- Operating system and its version: macOS monterey 12.2.1 (21D62)
- PDF.js version: newest
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Open the attached PDF with the official viewer: https://mozilla.github.io/pdf.js/web/viewer.html
2. Try zooming in/out, move the PDF around, etc.

**What is the expected behavior? (add screenshot)**
It should be quicker. I tried opening the same PDF with "preview" on mac, and with chrome, and they both render the PDF much-much faster, without any noticable loading/hanging.

**What went wrong? (add screenshot)**
It takes quite a while to load up/render the PDF, and then when I start zooming in and out, it often just turns white, and it hangs for 5-10 seconds before I can see something again.

By the way, I noticed this issue in a complex project, where we use the pdf.js javascript API to render certain parts of the PDF (with a defined viewbox), but it's much easier to reproduce the issue with the official PDF viewer. I sometimes had performance issues before, but in those cases other viewers weren't really any better for those PDFs. With this particular PDF, other viewers/renderers can outperform PDF.js by a lot.

So maybe someone here can find the reason behind it, and even fix it.

**Comment by Snuffleupagus** [comment]
That PDF document contains a *huge* amount of path rendering operators, which likely explains why this is a bit slow since that's something that's not entirely easy to optimize (and it thus looks a tiny bit similar to e.g. issue #10565).

**Comment by soadzoor** [comment]
@Snuffleupagus how do you check the number of paths in a PDF? Also, any idea how to reduce that number, without visually affecting anything? I mean offline solutions, of course, not realtime ones. Although those would be the best, but I believe those are just too complicated, as you mentioned.

**Comment by soadzoor** [comment]
@Snuffleupagus where is `/Contents-streams` ? Is that somehow accessible from the javascript API? I can't find it :(

**Comment by timvandermeij** [comment]
@soadzoor This refers to the built-in structure of the PDF file. You can open the file with a PDF browser, for example https://brendandahl.github.io/pdf.js.utils/browser/, to see the inner structure of the PDF file. In the tree there is also a `/Contents` field.

**Comment by soadzoor** [comment]
@timvandermeij Hm, but on the linked page, I can only see things like
```
Filter = /FlateDecode
Length = 3618135
```

How do I check how many `path rendering operators` are there? In https://github.com/mozilla/pdf.js/issues/10565, someone even left a comment with the exact number of `paths` (7.8 million). If I could retrieve that information, I could warn the users at least, that they're trying to render a complex PDF, so they should expect performance problems.

The question is: how can I retrieve that information?

**Comment by Snuffleupagus** [comment]
> How do I check how many `path rendering operators` are there?

You'd essentially have to *manually* instrument the code, if you want a fully accurate number (w.r.t. the PDF document itself), since no such functionality is provided (there's no general use-case that warrants adding such a feature).

Although, I suppose that it's also possible to use the `getOperatorList`-method and then loop through the operatorList to check for `OPS.constructPath` and using its `args` length to calculate the total number of path operators. Please see https://github.com/mozilla/pdf.js/blob/ee39499a5ab6063fdc5cf58df81ad5b36bd8efed/src/display/api.js#L1537-L1546 and https://github.com/mozilla/pdf.js/blob/ee39499a5ab6063fdc5cf58df81ad5b36bd8efed/src/display/api.js#L1212-L1219

**Comment by soadzoor** [comment]
Thanks! I played around with this, and it seems the PDF file above has `54 127` path rendering operators (I simply filter the `operatorlist.fnArray` for `OPS.constructPath` to get this number).

That doesn't seem like a lot. For example the following PDF has more than 3 times as many path rendering operators (`167 160`), yet it's still faster to render:
[167160.pdf](https://github.com/mozilla/pdf.js/files/8229730/167160.pdf)


Or this one has more than 1.2 million path rendering operators, yet it still seems to be faster to render than the original one in the first post:
[murietta.pdf](https://github.com/mozilla/pdf.js/files/8229752/murietta.pdf)

So I don't think there's a linear correlation between the number of path rendering operators and performance. I think there's more to this 🤔

**Comment by Snuffleupagus** [comment]
> I played around with this, and it seems the PDF file above has `54 127` path rendering operators (I simply filter the `operatorlist.fnArray` for `OPS.constructPath` to get this number).

Note that you've underestimated the actual number by at least one order of magnitude, since only counting `OPS.constructPath` isn't accurate given that each one can contain *lots* of actual path operators.
As mentioned in https://github.com/mozilla/pdf.js/issues/14652#issuecomment-1064328358 you need to count the args (i.e. the contents of the `argsArray`) instead; although I don't think putting time/effort into that really helps fixing this issue :-)

**Comment by luopeihai** [comment]
you can try pdf slice loading, very fast: [Introduces the address](https://medium.com/@ggluopeihai/pdf-slice-loading-full-stack-solution-89c12d92a2a4)

**Comment by THausherr** [comment]
It renders in about 3 seconds on Windows, and one can see that something is happening. My PC is from 2017 but with lots of memory. I don't see this as a performance problem at all. 

> If I could retrieve that information, I could warn the users at least, that they're trying to render a complex PDF, so they should expect performance problems.

 this would take longer than rendering this PDF itself.
