### ISSUE TITLE
Android mobile show error "Cannot read property 'WorkerMessageHandler' of undefined"

### ISSUE THREAD

**Issue by fairyly** [mozilla/pdf.js#14653]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:    Android default browser
- Operating system and its version: Android 8.1.0
- PDF.js version: 2.13.216
- Is a browser extension: no

Steps to reproduce the problem:
1. download  http://mozilla.github.io/pdf.js/getting_started/#download
2. in vue project , vue 2.6.*, vue cli 3.*

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
  PC is ok, but moblie show error "Cannot read property 'WorkerMessageHandler' of undefined"
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> in vue project , vue 2.6._, vue cli 3._

Sorry, but we cannot really provide support for various frameworks (i.e. Vue in this case) here, since we know nothing about them.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
