### ISSUE TITLE
Checkbox not checked

### ISSUE THREAD

**Issue by stefandutoit** [mozilla/pdf.js#14655]
Attach (recommended) or Link to PDF file here:
[Certificate 110608.pdf](https://github.com/mozilla/pdf.js/files/8223331/Certificate.110608.pdf)

Configuration:
- Chrome - Version 99.0.4844.51 (Official Build) (64-bit)
- Edge - Version 99.0.1150.36 (Official build) (64-bit)

- Operating system and its version:
- PDF.js version:  REACT-PDF v5.7.1

Steps to reproduce the problem:
1. Open the PDF in a viewer using the 'react-pdf' library.
2. On Page 1, checkbox 4.10 (Retail Trade) should be checked. It is not checked. 

What is the expected behavior? (add screenshot)
On Page 1, checkbox 4.10 (Retail Trade) should be checked.  The screenshot below is using the Adobe PDF Viewer.
![image](https://user-images.githubusercontent.com/60884238/157661687-43256fb8-c245-418f-80cf-e476364e770f.png)

What went wrong? (add screenshot)
On Page 1, checkbox 4.10 (Retail Trade) should be checked. It is not checked. The screenshot below is using 'react-pdf' library.
![image](https://user-images.githubusercontent.com/60884238/157661809-66b6f5e1-40b0-452f-8df2-bb0f167e64ff.png)

**Comment by Snuffleupagus** [comment]
WFM, when using PDF.js version `2.14.13` as bundled in Mozilla Firefox Nightly 100; please see

![checkbox](https://user-images.githubusercontent.com/2692120/157663857-62ddad76-6b51-4570-a634-321e37bc9eba.png)

> PDF.js version:  REACT-PDF v5.7.1
> Steps to reproduce the problem:
>     1. Open the PDF in a viewer using the 'react-pdf' library.

Sorry, but that's a *different* project which is not affiliated with the PDF.js project and as such we thus cannot provide any help/support for that here. Please contact that project directly for support!
