### ISSUE TITLE
getStructTree returns null

### ISSUE THREAD

**Issue by barsdeveloper** [mozilla/pdf.js#14662]
I'm using Rollup to package a web application that calls pdfjs. My application is module-based and in order to import pdfjs in this context I use commonJS. For some reason I cannot get anything from getStructTree, the method returns null. Did I miss some necessary configuration? The main features of the library like pdf parsing, text/canvas/svg rendering seems to work correctly, everything I've tried so far except this getStructTree.

```JavaScript
import pdfjs from "pdfjs-dist"
import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry"

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker

let pdf = await pdfjs.getDocument("test.pdf").promise
let page = await pdf.getPage(3)
let tree = await page.getStructTree()
// tree is null
```

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable/valid.

> For some reason I cannot get anything from getStructTree, the method returns null.

Please keep in mind that not all PDF documents contain any structure tree data, hence this could be the expected behaviour.

**Comment by barsdeveloper** [comment]
Thanks for the information. I thought it was information that the library was creating based on the page structure and not provided by the page itself.

**Comment by Snuffleupagus** [comment]
> I thought the tree structure was information that the library was creating based on the page structure and not provided by the page itself.

No, that method only provides information found in the PDF document *itself*. Please refer to the PDF specification for more information: https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#M13.9.11242.2Heading.862.Structure.Tree.Root
