### ISSUE TITLE
refuse to ask where to download to

### ISSUE THREAD

**Issue by alexfung888** [mozilla/pdf.js#14681]
Configuration:
- Chrome Version 99.0.4844.74 (Official Build) (64-bit)
- Windows 10 Pro 21H2
- PDF.js version: 2.3.164
- Is a browser extension: yes
- Chrome setting Ask where to save each file before downloading already enabled

Steps to reproduce the problem:
1. display a PDF
2. click download button

What is the expected behavior? (add screenshot)
dialogue to ask path and file name

What went wrong? (add screenshot)
directly download to the default location using server provided name.

**Comment by Snuffleupagus** [comment]
This unfortunately sounds like a *browser* issue, rather than a PDF.js one, and furthermore please note that the Google Chrome addon is effectively unmaintained at this point (since it's not been updated for well over two years).
