### ISSUE TITLE
PDFJS is not able to show prefilled Acroform PDF with data in xfa:dataset

### ISSUE THREAD

**Issue by keyhan** [mozilla/pdf.js#14685]
When Using a PDF which has Type 1 embedded fonts, a prefilled PDF that has been filled with tools like IText or PDFBox cannot be handled as is shown as empty by PDF JS.

If however PDFJS has prefilled the PDF the texts are shown.

Update: After discussion further down, now we know that the PDF is actually a hybrid of Acroform and XFA and PDFJS is not able to prefill Acroform with data in the XFA:dataset, although when saving the PDF, PDFJS actually save them in XFA:dataset also.

Attach (recommended) or Link to PDF file here:
[1647183160545.pdf](https://github.com/mozilla/pdf.js/files/8283456/1647183160545.pdf)
Configuration:
- Web browser and its version: Chrome (99)
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. open the attached file in Acrobat Reader
2. open the attached file in PDFJS

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/1078067/158780711-53842253-e7ca-4d28-a14b-5940f366f2f5.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/1078067/158780891-03c07758-915f-4022-83c2-901619343a67.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[1647183160545.pdf](https://github.com/mozilla/pdf.js/files/8283456/1647183160545.pdf)

**Comment by keyhan** [comment]
After further investigation, it seems like the TYPE1 font is not the issue, we can not find the specific reason.

**Comment by keyhan** [comment]
Thanks for your analysis, Is there any workaround to this problem so we would be able to show the filled values by PDFJS? We use XFA for other PDFs as well and for them PDFJS has no problem of showing the prefilled data. It is with some specific PDFs like this one that we have issues.

**Comment by calixteman** [comment]
I'll fix the bug in a couple of days.

**Comment by keyhan** [comment]
Great to hear. Thanks again for your quick help. appreciate it.
