### ISSUE TITLE
Potential issue with tiling patterns

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#14707]
Tiling patterns call [canvasGraphics.executeOperatorList](https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/src/display/pattern_helper.js#L588), but `executeOperatorList` can potentially [bail out](https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/src/display/canvas.js#L1215) before it has finished if a dependency is not ready yet. This means the tiling pattern could potentially not finish drawing. 

In the normal path of drawing the main operator list with `executeOperatorList`, I rarely see it bail out early (only happens twice while running all the tests locally), but it can happen.

One potential fix is #7294. Alternatively, we could add a way to have async canvas operations, but then any code path that calls `getPattern` would then need to become async since the pattern could potentially be a tiling pattern.

**Comment by Snuffleupagus** [comment]
> In the normal path of drawing the main operator list with `executeOperatorList`, I rarely see it bail out early (only happens twice while running all the tests locally), but it can happen.

I was under the impression that we *should* be avoiding that situation by waiting for all resources to load before rendering of TilingPatterns start, courtesy of this code in the worker-thread:
https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/src/core/evaluator.js#L853-L856

Am I completely misunderstanding that code, or just overlooking something simple here?

**Comment by brendandahl** [comment]
You're right! I had some changes locally that were causing bail outs, but that shouldn't happen for the current code.
