### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by planetsLightningArrester** [mozilla/pdf.js#14729]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
  Actually using Node.JS 16.13.0
- Operating system and its version:
  Windows 10 64 bits
- PDF.js version:
  2.13.216
- Is a browser extension:
  No

Steps to reproduce the problem:
1. Load a PDF using the code below:
``````Javascript
const PDFJS = require('pdfjs-dist');
PDFJS.getDocument({url: "doc.pdf", password: "123"})
``````
2. Run the code using `node`

What is the expected behavior? (add screenshot)
No error should be reported

What went wrong? (add screenshot)
An error is reported
``````Bash
node_modules/pdfjs-dist/build/pdf.js:2180
      data: structuredClone(obj, transfers)
            ^

ReferenceError: structuredClone is not defined
``````

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Notes:
I was using PDF version 2.7.570 and I didn't have this issue. I saw that the polyfill for `structuredClone` [was removed recently](https://github.com/mozilla/pdf.js/pull/13948). I'd like to know if there's any workaround for my case. For now, I'm just downgrading the version that I use. Thank you!

**Comment by Snuffleupagus** [comment]
When using the PDF.js library in Node.js you *must* use a `legacy`-build, since otherwise many things (and not just `structuredClose`) simply won't work unfortunately.
Hence changing your import to instead use `pdfjs-dist/legacy/build/pdf.js` ought to work, note also the examples in https://github.com/mozilla/pdf.js/tree/master/examples/node

> For now, I'm just downgrading the version that I use.

Note that that's never recommended, since anything except the latest version is explicitly unsupported.

**Comment by mmahalwy** [comment]
@Snuffleupagus thoughts on when this would work on non-legacy version?

**Comment by planetsLightningArrester** [comment]
Just FYI, `structuredClone()` is supported from [Node 17 onwards](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility).
I also had issues running tests with Jest, although Node was >17. I'm using the following and it's working perfectly.

Node: 18.9.0
jest: 29.0.3
pdfjs-dist: 2.16.105

```Typescript
import { getDocument, PDFDocumentProxy } from 'pdfjs-dist';

...

let pdf: PDFDocumentProxy | undefined = await getDocument({url: noteFullPath, password: pass}).promise;

```

**Comment by michelem09** [comment]
> Just FYI, `structuredClone()` is supported from [Node 17 onwards](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility). I also had issues running tests with Jest, although Node was >17, so I had to update Jest too.
> 
> I'm using the following versions and now everything is working perfectly.
> 
> Node: 18.9.0 jest: 29.0.3 pdfjs-dist: 2.16.105
> 
> ```ts
> import { getDocument, PDFDocumentProxy } from 'pdfjs-dist';
> 
> ...
> 
> let pdf: PDFDocumentProxy | undefined = await getDocument({url: noteFullPath, password: pass}).promise;
> ```

Importing it from legacy as suggested by @Snuffleupagus works:

`import pdfjsLib from 'pdfjs-dist/legacy/build/pdf.js';`

**Comment by philip-hub** [comment]
> When using the PDF.js library in Node.js you _must_ use a `legacy`-build, since otherwise many things (and not just `structuredClose`) simply won't work unfortunately. Hence changing your import to instead use `pdfjs-dist/legacy/build/pdf.js` ought to work, note also the examples in https://github.com/mozilla/pdf.js/tree/master/examples/node
> 
> > For now, I'm just downgrading the version that I use.
> 
> Note that that's never recommended, since anything except the latest version is explicitly unsupported.

Hello I am unable to find the legacy version. Is it still available?

**Comment by doczoidberg** [comment]
import pdfjsLib from 'pdfjs-dist/legacy/build/pdf.js';

needs canvas which I don't have in node.js 16?
