### ISSUE TITLE
Unneeded Reparsing 

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#1473]
I noticed this while checking out the xref bug. We re-parse certain color spaces and functions every time they are used.  We should really be caching them per page.

See IndexedCS in colorspace.js (had to do str.reset())

See getSampleArray() in function.js (had to do str.reset())

**Comment by timvandermeij** [comment]
Caching has been improved a lot lately, and with all caches now in place (see https://github.com/mozilla/pdf.js/blob/master/src/core/image_utils.js#L203-L208) this should be resolved. If there are specific caching improvements that can still be made, we should make a new issue.
