### ISSUE TITLE
<input> elements for annotations inherit some style from viewer.css

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14736]
STR:
 - open the pdf in https://github.com/mozilla/pdf.js/issues/14685#issue-1172145263
 - open devtools and look at the style for an `<input>`
 - it has `font: message-box` which is defined: https://github.com/mozilla/pdf.js/blob/54d4d345d31abead560e1bc54138af6b9baadd6b/web/viewer.css#L195

According to:
https://developer.mozilla.org/en-US/docs/Web/CSS/font#message-box
this value is for dialog boxes so I think it doesn't make sense to use it for annotation.

**Comment by salmanansari14** [comment]
can u please assign  me this issue !!
