### ISSUE TITLE
Ability to create annotations like Adobe Reader ?

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#14740]
It would be great if pdf.js had the ability to annotate PDF documents like Adobe reader does with a comment toolbar.

What is the expected behavior?
With a comment toolbar with ability to highlight/strikeout text, add text, draw shape and arrow...
[![IMAGE-4](https://user-images.githubusercontent.com/7791600/161339197-99318145-96af-489d-8c76-526364a0058a.jpg)](https://blogs.reed.edu/ed-tech/files/2016/03/IMAGE-4.jpg)

Is this functionality planned ?

This is the only reason I still have to keep Adobe Reader installed.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations

**Comment by THausherr** [comment]
There's a guy who has created such a tool, google "Annotationeer".
