### ISSUE TITLE
Two page spread doesn't work in fullscreen presentation mode

### ISSUE THREAD

**Issue by fivestones** [mozilla/pdf.js#14749]
When using two-page spreads, and then changing to fullscreen presentation mode, it changes back to single pages for the fullscreen mode instead of showing the desired two-page spreads.

I have seen issue #11708, and the response is a claim that presentation mode is meant to be very simple and not have any extra functionality. If this is truly the case it is a poor choice. I think it is more likely that it just hasn't been implemented yet, and so I'm making a new issue here. For presentation mode, anyone using this software would expect to see the same pdf presented as before, but filling the screen, and without the toolbar at the top and without any of the browser chrome surrounding. The answer for issue #11708 says that you should just use the browser's full-screen mode, but this doesn't to my knowledge allow one to show the pdf full-screen without any toolbars visible. If this is more than a bug, and more of a feature request, then please consider it a feature request. Thanks!

Configuration:
- Web browser and its version: Safari 15.1 or Firefox 98.0.1
- Operating system and its version: macOS Monterey 12.0.1
- PDF.js version: Any
- Is a browser extension: No

Steps to reproduce the problem:
1. Open any multi-page pdf
2. Click the double arrow dropdown on the right side of the toolbar
3. Choose "odd spreads" or choose "even spreads". A view will be shown with two pages side by side.
4. Click "Switch to Presentation Mode" on the toolbar.
5. You are switched to fullscreen, but with just one page instead of a two-page spread.

What is the expected behavior? (add screenshot)
When clicking "presentation mode" you should still see the same view of the pdf as you were before entering presentation mode.

What went wrong? (add screenshot)
As above, only one page is shown in presentation mode, regardless of two page spread settings

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a.

**Comment by fdermishin-otus** [comment]
The problem seems to appear again. It reproduces for me on Firefox 110.0 (64-bit), build id 20230214051806, Intel Mac OS Monterey 12.6.2

**Comment by negyvenot** [comment]
Same here, Windows 10, Firefox 112.0.2 (64-bit)

**Comment by fivestones** [comment]
Also for me, Firefox 113.0.1 64 bit, M1 Pro MacOS
