### ISSUE TITLE
Events like 'pagesloaded' and 'pagerendered' are not being triggered

### ISSUE THREAD

**Issue by jsanahuja** [mozilla/pdf.js#14753]
Attach (recommended) or Link to PDF file here: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

Configuration:
- Web browser and its version: Google Chrome 100.0.4896.75 (64 bits)
- Operating system and its version: Windows 10 19041.1415
- PDF.js version: 2.13.216

What is the expected behavior? (add screenshot)
Events to be triggered.

What went wrong? (add screenshot)
We recently updated to 2.13.216 from 2.0.943 and what used to work:
```
window.addEventListener('pagesloaded', function(e) {
    ...
})
```
Is no longer working.

Out workaround:
```
Index: viewer.js
===================================================================
--- viewer.js   (revision 1649)
+++ viewer.js   (working copy)
@@ -3798,6 +3798,14 @@
   dispatch(eventName, data) {
     const eventListeners = this._listeners[eventName];
 
+    var event = document.createEvent('CustomEvent');
+    event.initCustomEvent(eventName, true, true, data);
+    if (data && data.source && data.source.container) {
+      data.source.container.dispatchEvent(event);
+    } else {
+      window.dispatchEvent(event);
+    }
+
     if (!eventListeners || eventListeners.length === 0) {
       return;
     }
```

**Comment by Snuffleupagus** [comment]
We purposely removed global event dispatching, hence you'll need to use the following format instead:
```javascript
PDFViewerApplication.eventBus.on("pagesloaded", evt => {
  ...
});
```
To know when `PDFViewerApplication` and its `eventBus` property is available, please listen for the global "webviewerloaded" event; see also https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage

**Comment by jsanahuja** [comment]
Thanks for answering so quickly and for your explanation.

From my point of view this is a breaking change. Doesn't this repository follow semantic versioning as stated [here](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-is-the-latest-stable-version-of-pdfjs)?
