### ISSUE TITLE
Failed to fetch v2.13.216

### ISSUE THREAD

**Issue by fairyly** [mozilla/pdf.js#14752]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: mobile default browser
- Operating system and its version: android 8.1.0
- PDF.js version:   2.13.216
- Is a browser extension:  no

Steps to reproduce the problem:
1.  download :http://mozilla.github.io/pdf.js/getting_started/#download
2.  use  pdfjs viewer

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/17672815/161888914-072923f5-fbf8-4a1f-a7fe-209b1db0a868.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: mobile default browser

It's not at all clear which *exact* browser this actually means. Furthermore, please find the supported browsers at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> Operating system and its version: android 8.1.0

According to https://en.wikipedia.org/wiki/Android_version_history#Android_8.1_Oreo, that OS was released in 2017 and it's consequently way too old in general. Generally speaking, if you refer to the FAQ mentioned above you'll notice that the oldest browsers that we (currently) attempt to support are *three years old*.

---

Finally, as-is this unfortunately isn't really actionable. Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
