### ISSUE TITLE
Chinese font not displayed

### ISSUE THREAD

**Issue by 123woscc** [mozilla/pdf.js#14759]
Attach (recommended) or Link to PDF file here:
[GM／T 0016-2012 智能密码钥匙密码应用接口规范(1).pdf](https://github.com/mozilla/pdf.js/files/8441278/GM.T.0016-2012.1.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 99.0.1150.39
- Operating system and its version: Windows 10
- PDF.js version: v2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF with pdf.js.
2. Found the text of this PDF disappeared.

What is the expected behavior? (add screenshot)
Open with browser built-in viewer
![image](https://user-images.githubusercontent.com/13806929/162162815-ad7e3b4b-2c41-4a5e-8122-8010eb089e02.png)

What went wrong? (add screenshot)
Open with pdf.js online demo https://mozilla.github.io/pdf.js/web/viewer.html
![image](https://user-images.githubusercontent.com/13806929/162163371-126b8a6a-f42a-4af6-a47f-ab8947796824.png)
![image](https://user-images.githubusercontent.com/13806929/162163896-d1798173-c1ff-4860-8b9f-a11a9dc5b6e5.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
[issue14759_reduced.pdf](https://github.com/mozilla/pdf.js/files/8441462/issue14759_reduced.pdf)

Interestingly it works fine with `disableFontFace = true` set, which suggests that the browser (or possibly OTS) is rejecting the font. However, there are no font-related error messages printed in the console.

**Comment by 123woscc** [comment]
Yes, I've also found that `disableFontFace = true`  to display fine.  but this will cause other files to fail to display. 
![image](https://user-images.githubusercontent.com/13806929/162167949-fe2c5fa8-8763-4b06-99fb-ad4bb8046ce2.png)
Might be easier to handle if it could throw a font-related error.

**Comment by dunduenrzc** [comment]
I also encounter the same problem. Do you have a solution @123woscc

**Comment by syczuan** [comment]
需要设置cMapUrl

`PDFJS.getDocument({
          url: url,
          cMapUrl: "https://unpkg.com/pdfjs-dist/cmaps/",
          cMapPacked: true,
        })`

**Comment by Snuffleupagus** [comment]
Fixed by PR #15900.
