### ISSUE TITLE
Reset pdf / page number when the section is empty

### ISSUE THREAD

**Issue by VictoriaStefanikova** [mozilla/pdf.js#14776]
Hi.  I have a sidebar navigation where each section (navigation item) can contain pdf attachment with 1 or more pages. There can also be section with 0 attachment and in this case, I´m displaying component informing no content for the specific section available. I´m also using page turner component where there is information what page I am currently at and what is the total number of pages for the particular section.

The issue I´m facing, is that whenever I click through these sections and I come from the section that contains multiple page attachment to section that is empty, the number of pages of attachment is preserved. So let´s say I reached 20/20 page on the previous section and got to the empty section, I have to click on the navigate back button 20times to display previous section content.

I need to reset the #pdfFile variable inside my else block, but it is a read only property. Defining empty variable of type PDFDocumentProxy and assigning this value to #pdfFile didn´t help. Do you have any suggestions how to reset this value?

My code:
```
get pdfFile(): PDFDocumentProxy {
    return this.#pdfFile;
  }

  set pdfFile(value: PDFDocumentProxy) {
    this.#pdfFile = value;
  }

#pdfFile: PDFDocumentProxy;
isSectionEmpty = false;

showPdf(attachment: Attachment, pageNum: PageNumber): void {
    // Asynchronous download PDF
    let loadingTask: PDFDocumentLoadingTask;
    if (attachment?.data) {
      loadingTask = pdfjsLib.getDocument({data: atob(attachment.data)});
      this.isSectionEmpty = false;

    } else {
      // the boolean isSectionEmpty determines if the empty section component is visible or not
      this.canvasPdf.getContext('2d').clearRect(0, 0, this.canvasPdf.width, this.canvasPdf.height);
      this.drawService?.canvas?.clear();
      this.isSectionEmpty = true;
    }
    if (loadingTask) {
      loadingTask.promise
        .then((pdfDoc: PDFDocumentProxy) => {
          this.#pdfFile = pdfDoc;
        })
        .finally(() => {
          this.fileDownloading = false;
        });
    }
  }
```

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable (nor particularly easy to follow/understand).

> My code:

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
