### ISSUE TITLE
How can I convert pdfTosvg and then use pdfjs to convert svg to pdf file

### ISSUE THREAD

**Issue by Sincerity7788** [mozilla/pdf.js#14789]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 100.0.4896.60
- Operating system and its version:windows
- PDF.js version:2.5.1
- Is a browser extension: Chrome

Steps to reproduce the problem:
I am looking forward to being able to convert PDFjs into svg and render them on the page. I may add some elements to the svg element, and then I want to use PDFjs again to convert the svg element in the page into a pdf file. I hope the official can provide one Complete implementation. Many thanks to the official PDFjs
What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version:2.5.1

That's first of all not an official release, as found at https://github.com/mozilla/pdf.js/releases
Secondly, that version (assuming it actually existed) is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I am looking forward to being able to convert PDFjs into svg and render them on the page.

As mentioned in the FAQ, the SVG back-end is *not* officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

> and then I want to use PDFjs again to convert the svg element in the page into a pdf file.

As mentioned in both the README and [the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations), the PDF.js library doesn't support *arbitrary* PDF editing (with the exception of saving filled in forms).
