### ISSUE TITLE
Allow the library to be bundled as a single file without seaprate worker js

### ISSUE THREAD

**Issue by Lukenickerson** [mozilla/pdf.js#14781]
**Configuration:**
- Web browser and its version: Any / N/A
- Operating system and its version: Any / N/A
- PDF.js version: v2.13.216
- Is a browser extension: No

**Steps to reproduce the problem:**

1. Attempt to bundle the library in a single, portable js file
    - Do `const pdfjsLib = require('pdfjs-dist/webpack');` followed by some logic inside a `main.js`
    - Bundle `main.js` using webpack
2. Always needs configuration of the worker that points to a separate js file
    - Needs webpack config `"pdf.worker": "pdfjs-dist/build/pdf.worker.entry"` that builds a separate js file
    - Needs a line that points to the exact URL of the worker js file, e.g., `pdfjsLib.GlobalWorkerOptions.workerSrc = './build/pdf.worker.bundle.js';`
    - Both of the above requirements remove many of the benefits of bundling

**What is the desired behavior?**

It would be very useful if the PDF.js library were more portable and could be packaged inside another app. As it currently stands this does not seem to be possible, or is not documented. Following along the documentation at https://github.com/mozilla/pdf.js/tree/master/examples/webpack we see that even though webpack bundles most of the pdfjs library into a single file, there is always a separate worker `.js` file that needs to go along with it, requiring configuration (setting `GlobalWorkerOptions.workerSrc`). The `webpack.js` build does not appear to offer any benefit.

**Comment by Snuffleupagus** [comment]
Please note that using the PDF.js library without Web Workers, i.e. with the `pdf.worker.js` file loaded on the main-thread, will lead to *very poor* overall performance and it'll hurt UI responsiveness which is why it's never been either recommended or even officially supported in browsers.[1]
Note that years ago we had a `SINGLE_FILE` build target, which sounds somewhat like what you're asking for here, however that was *purposely* removed in PR #9385 for the reasons outlined above.

---
[1] The ability to load the `pdf.worker.js` file on the main-thread only exists as a fallback (since older browsers had trouble with workers), for debugging purposes, and finally for Node.js environments.

**Comment by Lukenickerson** [comment]
@Snuffleupagus -- Is it possible to load the js for the worker at build time so that the faster worker functionality can remain intact, but the built js file can contain everything it needs? An implementation could look something like...

```js
// No change in how we import the core functionality
import pdfjsLib from `pdfjs-dist/build/pdf';
// Bring in the worker code (built differently) now rather than at runtime
import pdfjsWorkerFunction from 'pdfjs-dist/build/pdf.worker-function';  // (new build file needed)

// Convert the function into a blob url to use workerSrc
const workerBlob = new Blob(
	[ '(', pdfjsWorkerFunction.toString(), ')()' ],
	{ type: 'application/javascript' },
);
const blobUrl = URL.createObjectURL(blob);
pdfjsLib.GlobalWorkerOptions.workerSrc = blobUrl; // ultimately ends up in new Worker(workerSrc)

// OR (better) just do the above in the library (_initialize method), and just have a new option like:
pdfjsLib.GlobalWorkerOptions.workerFunction = pdfjsWorkerFunction;

// Then continue as normal
```

This way when a webpack build is done, everthing would get bundled up together in a single file with no path-based configuration needed. And (I think) the worker should still work on a separate thread.

Regarding your [1] note: How can someone use the fallback to load the `pdf.worker.js` file on the main thread? I don't recall seeing that in the documentation.
