### ISSUE TITLE
webview 

### ISSUE THREAD

**Issue by StarFishing** [mozilla/pdf.js#14787]
Attach (recommended) or Link to PDF file here:

Configuration:
- UA: Mozilla/5.0 (Linux; Android 6.0.1; OPPO A57 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36
- Operating system and its version: Android 6.0.1
- PDF.js version:2.14.175
- Is a browser extension: NO

Steps to reproduce the problem:
1. Use the same version of webview
2. in webview , open https://mozilla.github.io/pdf.js/legacy/web/viewer.html

What is the expected behavior? (add screenshot) load page success

What went wrong? (add screenshot) can not load pdf

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Android 6 is over six years old now and therefore _far_ out of support.
