### ISSUE TITLE
Source code of the online demo

### ISSUE THREAD

**Issue by AlexVelezLl** [mozilla/pdf.js#14791]
Hi! Where can I find the source code of the [online demo](https://mozilla.github.io/pdf.js/web/viewer.html)? Is this available for everyone? I have searched a lot for its source code without success. There are some features there that I haven't seen in the examples folder, and I want to learn how to reproduce them.

Sorry to ask this question here, I didn't find a discussion section :c

**Comment by Snuffleupagus** [comment]
Refer to https://github.com/mozilla/pdf.js/tree/master/web, however note that it's *purposely not* documented; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
