### ISSUE TITLE
PDF.js v2.13.216 (build: 399a0ec60) Message: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by edsonfeimberg** [mozilla/pdf.js#14805]
And in console:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/storage/manuals/example.pdf (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

The problem is: i have access to the server and i know that it is currently allowing CORS. I have the front-end running at http://127.0.0.1:3000 and the back-end running at http://127.0.0.1:8000. Every type of request to the server currently works perfectly (axios, images etc), only the pdf.js viewer resulting in this problem. In fact, before trying to implement pdf.js, the pdf was displayed perfectly inside the <iframe> as desired.

Also, i already have both http://127.0.0.1:3000 and http://127.0.0.1:8000 in HOSTED_VIEWER_ORIGINS at viewer.js.

Works perfectly without CORS issues:
```
<iframe
      v-if="car.manual"
      :src="'$config.imgsURL + car.manual"
      width="100%"
      height="100%"
      style="border: none"
    >
      >
    </iframe>
```

Doesn't work:
```
<iframe
      v-if="car.manual"
      :src="'/pdf.js/web/viewer.html?file=' + $config.imgsURL + car.manual"
      width="100%"
      height="100%"
      style="border: none"
    >
      >
    </iframe>
```

**Comment by Snuffleupagus** [comment]
> And in console:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/storage/manuals/example.pdf (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr, which is probably the only help that we can realistically provide here.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
