### ISSUE TITLE
download with watermark

### ISSUE THREAD

**Issue by tenyears94** [mozilla/pdf.js#14808]
Watermark is currently implemented in the preview, can click to print or download with a watermark?

**Comment by Snuffleupagus** [comment]
We do *not* support arbitrary PDF editing, which I'm guessing is what you're asking about.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable/valid.
