### ISSUE TITLE
Whole PDF file is downloaded, when sub range download is enabled

### ISSUE THREAD

**Issue by liucan233** [mozilla/pdf.js#14809]
Configuration:
- Web browser and its version: edge 100.0.1185.44
- Operating system and its version: win10
- PDF.js version:  2.13.216
- Is a browser extension: no

Steps to reproduce the problem:

The whole PDF file is downloaded, when sub range download is enabled.
below are my code:
```js
getDocument({
    url: 'http://localhost:3000/demo.pdf',
    disableAutoFetch: true,
    rangeChunkSize: 65530,
    disableRange: false,
})
```

What is the expected behavior? (add screenshot)

Only part of the PDF is loaded when the document is loaded.

What went wrong? (add screenshot)

The entire PDF is downloaded when the document is loaded.
![download](https://user-images.githubusercontent.com/13808186/164202874-1d105022-2c3b-4514-bda9-04efc3e70cda.jpg)

**Comment by Snuffleupagus** [comment]
Please note that the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is *always* required when opening an issue.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
Please note that the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is *always required* when opening an issue, since as-is it's impossible for anyone to reproduce this.

> The whole PDF file is downloaded, when sub range download is enabled. below are my code:
> 
> ```js
> getDocument({
>     url: 'http://localhost:3000/demo.pdf',
>     disableAutoFetch: true,
>     rangeChunkSize: 65530,
>     disableRange: false,
> })
> ```

As mentioned in the API docs, see https://github.com/mozilla/pdf.js/blob/9a8fa3201fbe440ab4b546976f641b04518cca3c/src/display/api.js#L208-L214 you also need to set `disableStream = true` in order for `disableAutoFetch` to work as expected.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
