### ISSUE TITLE
Image fails to render in PDF with warning: Unable to decode image "img_p1_1": "TypeError: dict is undefined".

### ISSUE THREAD

**Issue by nvandermark** [mozilla/pdf.js#14814]
The following PDF document contains an image on the second page, which renders fine in Chrome and Edge, but not in Firefox.

[dummy.png-merged.pdf](https://github.com/mozilla/pdf.js/files/8529750/dummy.png-merged.pdf)

Configuration:
- Web browser and its version: Firefox 99.0.1 (64-bit)
- Operating system and its version: Microsoft Windows 10.0.19044
- PDF.js version: 2.14.13
- Is a browser extension: No, built-in

Steps to reproduce the problem:
1. Download the attached PDF document
2. Open it with Firefox

What is the expected behavior?
![dummy-pdf-preview](https://user-images.githubusercontent.com/98527051/164426628-b653a5a2-50c9-418d-8330-e73dafd1f36e.jpg)

What went wrong?
![dummy-pdf-error](https://user-images.githubusercontent.com/98527051/164426856-908c6519-7e1d-4540-ba96-64a807cda936.jpg)

The console log reports the following:
```
PDF a6a48131e71621bc3b94ef303411a8c1 [1.6 OpenOffice.org 2.1 / Writer] (PDF.js: 2.14.13)
Warning: Unable to decode image "img_p1_1": "TypeError: dict is undefined".
Warning: Dependent image isn't ready yet
```

Additional information:
This PDF document is generated by a software component that we've built in Java, based on a number of open-source libraries. It merges an existing PDF document with a number of supplied images to produce a final PDF document.

**Comment by Snuffleupagus** [comment]
> The following PDF document contains an image on the second page, which renders fine in Chrome and Edge, but not in Firefox.

Please note that is also doesn't render in Adobe Reader, which is the PDF reference implementation.

> This PDF document is generated by a software component that we've built in Java, based on a number of open-source libraries. It merges an existing PDF document with a number of supplied images to produce a final PDF document.

Unfortunately the generated PDF document is actually corrupt, please refer to https://github.com/mozilla/pdf.js/pull/14815#issue-1210816528 for additional details.
Hence please file *also* file a bug report against the PDF generator, such that it starts generating valid documents.

**Comment by nvandermark** [comment]
Thank you for the quick reply, we'll take this back to improve the PDF generation. Cheers!
