### ISSUE TITLE
Latest version of PDF.js cannot see PDF  in iPad

### ISSUE THREAD

**Issue by rahabchung** [mozilla/pdf.js#14820]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Chrome
- Operating system and its version:  iPad
- PDF.js version: v2.13.216  and v2.12.313
- Is a browser extension: No

Steps to reproduce the problem:
1. Using PDF.js version: v2.13.216 (using PDF.js v2.11.338 does not have this issue)
2. using iPad to view, the PDF is blank

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/32052978/164593072-f8ee296b-dc5e-4126-b074-49b1c3c55bb3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
You'll need to use a `legacy`-build, note the two different versions listed at https://github.com/mozilla/pdf.js#online-demo and also the two versions listed at https://mozilla.github.io/pdf.js/getting_started/#download
