### ISSUE TITLE
Missing image in PDF

### ISSUE THREAD

**Issue by dexeonify** [mozilla/pdf.js#14830]
Attach (recommended) or Link to PDF file here: [extracted_page.pdf](https://github.com/mozilla/pdf.js/files/8546955/extracted_page.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 101.0a1
- Operating system and its version: Windows 11 Build 22000.613
- PDF.js version: v2.13.216
- Is a browser extension: No?

Steps to reproduce the problem:
1. Open the PDF with the built-in pdf.js in Firefox
   OR
   Open the PDF at https://mozilla.github.io/pdf.js/web/viewer.html in Edge
2. The trees image is missing.

What is the expected behavior? (add screenshot)
Adobe Acrobat:
![Acrobat](https://user-images.githubusercontent.com/72267349/164895873-53093b23-a2cf-4bb9-b84c-3b1dd38bf723.png)

What went wrong? (add screenshot)
PDF.js in both Firefox and Edge:
![PDF.js](https://user-images.githubusercontent.com/72267349/164895878-67d02586-7409-42eb-933c-a87b3294f58c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by rootsli** [comment]
The same problem was found in my project, especially the scanned images。

**Comment by ChadiHamrouni** [comment]
The problem doesn't seem to have a relationship with the type of the image being rendered since I was able to display different types of images in one file to test it.

**Comment by ASHIK5261** [comment]
is there any solution for this?
