### ISSUE TITLE
PDF JS zoom rendering

### ISSUE THREAD

**Issue by khaledmndev** [mozilla/pdf.js#14837]
Configuration:
- Web browser and its version: Edge Version 100.0.1185.50
- Operating system and its version: Windows 11 (Version 21H2)
- PDF.js version: Version 2.13.216
- Is a browser extension:

here's my problem:
1.  i added an append function inside (.spread>.page), used in viewer.js to load after page is loaded using eventBus.on("pagesloaded", function (){}
2. it will work successfully, but when i click on zoom in or out, or start scrolling the element i appended will disappear.. 

here's my code:
` $(".spread .page").each(function () {
      $(this).append( "<div class='canvasArea'><canvas></canvas></div>");
   });`

**Comment by Snuffleupagus** [comment]
> i added an append function inside (.spread>.page), used in viewer.js to load after page is loaded using eventBus.on("pagesloaded", function (){}

It's somewhat difficult to tell what you're *actually* attempting to achieve by doing this...

> it will work successfully, but when i click on zoom in or out, or start scrolling the element i appended will disappear..

Given that the pages are re-created on zooming, that'd actually be expected. Hence you'd probably have to re-run your code on e.g. every "pagerender" (or maybe "pagerendered") event.

> here's my code:
> ` $(".spread .page").each(function () { $(this).append( "<div class='canvasArea'><canvas></canvas></div>"); });`

That first of looks like JQuery-code, which we don't support here. Secondly, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by khaledmndev** [comment]
is there anyway to disable re-rendering on zoom in and out??
