### ISSUE TITLE
PDF render issue in PDF JS plugin & Mozilla Firefox

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#14841]
[document .pdf](https://github.com/mozilla/pdf.js/files/8561463/document.pdf)

Issue reproducible on FireFix 99.0.1
PDF JS Version: Latest

Steps:
1. Open the PDF in Firefox, it's not rendering
2. Load the PDF in PDFJS it's still not rendering https://mozilla.github.io/pdf.js/web/viewer.html

FYIP:
The same PDF is rendering fine on Chrome without PDF JS plugin

**Comment by ms3534** [comment]
@Snuffleupagus any update in this?

**Comment by Snuffleupagus** [comment]
Duplicate of #13571
