### ISSUE TITLE
Ability to show something where an empty signature annotation is

### ISSUE THREAD

**Issue by pboyd04** [mozilla/pdf.js#14851]
Attach (recommended) or Link to PDF file here: https://secure.burningflipside.com/tickets/_admin/AdultBundle.pdf

Configuration:
- Web browser and its version: Chrome 100.0.4896.88
- Operating system and its version: Windows 11
- PDF.js version: 2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1. Have form with empty signature field
2. Enable annotation layer
3. See nothing on annotation layer for empty signature field

What is the expected behavior? (add screenshot)
I would like to be able to render a button or something where an empty signature annotation is. Is there someway to force the annotation layer to at least render the empty section or something so that I can add a button later? Or some way to override the annotation layer's behavior for certain field types?

**Comment by Snuffleupagus** [comment]
> Have form with empty signature field

It's not entirely clear what "empty" means here. Note that signatures with a `[0 0 0 0]` BBox are not supposed to be rendered at all. If you mean that the signature actually has a meaningful BBox, but contains no appearance data, then we don't have any support for rendering e.g. a field-outline in that case and you'd have to (at least) modify the code in https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js and https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js to achieve that.

However, please note that this isn't really a use-case that we support (and our current signature support is limited to only *displaying* existing ones).

**Comment by pboyd04** [comment]
Empty means without signature present. The bounding box is there. If I put a pull to add an option to display sections for these with no content (i.e. not the default) would you take that pull? Or am I out of luck unless I pay for one of the commercial javascript PDF frameworks?

**Comment by Snuffleupagus** [comment]
> If I put a pull to add an option to display sections for these with no content (i.e. not the default) would you take that pull?

That unfortunately sounds like too much of an edge-case, from the general PDF.js library perspective, to warrant adding a specific option for that (since every option does incur some testing/maintenance overhead).

However, you can can obviously implement this *in your own fork* of the library.
