### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getReader')

### ISSUE THREAD

**Issue by eyvettesou** [mozilla/pdf.js#14850]
Attach (recommended) or Link to PDF file here:

**Configuration:**
- Web browser and its version: Chrome - latest
- Operating system and its version: macOS Monterey 12.0.1
- PDF.js version: 2.13.216
- Is a browser extension: No
- Node version: 14.18.2
- We are NOT using the provided viewer app. We're building out our own viewer via React.

**Steps to reproduce the problem:**
We currently trying to upgrade a lot of our dependencies including our bundler (webpack 4 -> 5).  We upgraded `worker-loader` to 3.0.8, so we decided to upgrade pdfjs to latest as well. Our pdfjs worker version matches the pdfjs version and we're able to successfully call on pdfjs.

```ts
      const loadingTask = pdfjs.getDocument({
        url: props.documentUrl,
        withCredentials: false,
      });
      const downloadedDocument = await loadingTask.promise;
```
However we are now running into an error when trying to resolve the `loadingTask`. 
![Screen Shot 2022-04-27 at 9 31 01 AM](https://user-images.githubusercontent.com/13372311/165568097-98a4cfc6-b6e4-44de-80a5-f3950644e3b6.png)

We are using the provided pdf from the demo ([`compressed.tracemonkey-pldi-09.pdf`](https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf)).

We're not sure what the error means and was hoping to get insight on it.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
It _looks_ like `ReadableStream` support may be missing going by `getReader` being called on an `undefined` object instead of a valid `ReadableStream` (see https://github.com/mozilla/pdf.js/blob/54d4d345d31abead560e1bc54138af6b9baadd6b/test/unit/util_spec.js#L148-L151 for example), but it's impossible to tell for sure without more information as requested above.

**Comment by TrungRueta** [comment]
This issue happend to me in case project implement MirageJs. when setup MirageJs server to mock api, look like MirageJs modified ReadableStream somehow and pdfjs failed when try read document by url. Remove Miragejs server on project make pdfjs work again
