### ISSUE TITLE
Issue: The relations between outline-item and real-page.

### ISSUE THREAD

**Issue by ZUXING** [mozilla/pdf.js#14868]
Attach (recommended) or Link to PDF file here: Any PDF file with OUTLINE, I attached a PDF file with an outline.
[BJC70用户说明书.pdf](https://github.com/mozilla/pdf.js/files/8603466/BJC70.pdf)

Configuration:
- Web browser and its version: Microsoft Edge or Chrome, both are the latest versions.
- Operating system and its version: Windows 10
- PDF.js version: I don't know, I used npm to install it: [ vue-pdf ]
- Is a browser extension:

I need to make a pdf viewer for my vue project, this viewer needs these functions: Outline-List-View. But vue-pdf no outline. I want to put some Element nodes and use them as a outline-list, then click a link, it will scroll to the destination page that I excepted.
Using PDF.js, I could get the Outline list Array or Object, like [num, gen, 'XYZ' 567.89] and some titles. But I can't get the relation between real-page and outline-item or page-number.
I get tons of useless guides or information on Chinese websites, either Baidu or Bing. So I hope someone can help me to solve this problem or tell me the relations between outline-item and real-page. Thanks.
----------------------
英语说的不好，请见谅。以下是中文内容。
通过PDF.js我能获取到大纲的Array，但是我没法把大纲的每一项和真实的页码联系起来。
我想在页面渲染的时候获取页码，这样点击大纲里面的东西就可以跳转到对应的页面。
大纲：Outline、OutlineView。

**Comment by Snuffleupagus** [comment]
> PDF.js version: I don't know, I used npm to install it: [ vue-pdf ]

Sorry, but "vue-pdf" is *not* maintained here and consequently we cannot provide support for that. Please open an issue in the correct repository instead.

Note also that you need to communicate *only* in English when using this bug tracker.

---

Given the limited information provided, the only suggestions is to check the following resources:
 - https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.2063217
 - https://github.com/mozilla/pdf.js/blob/da4f7dfcd04400cb2ce67f04be0d78e43f20dbac/src/display/api.js#L793-L800
 - The viewer-implementation may perhaps be useful as well, see https://github.com/mozilla/pdf.js/blob/da4f7dfcd04400cb2ce67f04be0d78e43f20dbac/web/pdf_link_service.js#L176-L257

**Comment by AaronD1214** [comment]
> Attach (recommended) or Link to PDF file here: Any PDF file with OUTLINE, I attached a PDF file with an outline. [BJC70用户说明书.pdf](https://github.com/mozilla/pdf.js/files/8603466/BJC70.pdf)
> 
> Configuration:
> 
> * Web browser and its version: Microsoft Edge or Chrome, both are the latest versions.
> * Operating system and its version: Windows 10
> * PDF.js version: I don't know, I used npm to install it: [ vue-pdf ]
> * Is a browser extension:
> 
> ## I need to make a pdf viewer for my vue project, this viewer needs these functions: Outline-List-View. But vue-pdf no outline. I want to put some Element nodes and use them as a outline-list, then click a link, it will scroll to the destination page that I excepted.
> Using PDF.js, I could get the Outline list Array or Object, like [num, gen, 'XYZ' 567.89] and some titles. But I can't get the relation between real-page and outline-item or page-number.
> I get tons of useless guides or information on Chinese websites, either Baidu or Bing. So I hope someone can help me to solve this problem or tell me the relations between outline-item and real-page. Thanks.
> 英语说的不好，请见谅。以下是中文内容。 通过PDF.js我能获取到大纲的Array，但是我没法把大纲的每一项和真实的页码联系起来。 我想在页面渲染的时候获取页码，这样点击大纲里面的东西就可以跳转到对应的页面。 大纲：Outline、OutlineView。

请问你租后是如何“实现点击大纲里面的东西就可以跳转到对应的页面"

**Comment by ZUXING** [comment]
------------------ 以下是回复 ------------------


我没有实现这个功能。
最后的解决方案是直接基于mozilla/pdf.js的html-js官方示例，修改CSS和JS实现自己想要的功能，最后放到vue&gt;static目录下。
如果需要访问PDF文件，就要跳出VUE页面。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/pdf.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mozilla/pdf.js] Issue: The relations between outline-item and real-page. (Issue #14868)


……
  
请问你租后是如何“实现点击大纲里面的东西就可以跳转到对应的页面"

**Comment by AaronD1214** [comment]
The reply in Chinese was actually deleted. I solved this problem by upgrading the version. Upgrade to version 2.16.105. "pdfjs-dist": "^2.16.105"
