### ISSUE TITLE
Automatic zoom button is too much visible

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla/pdf.js#14879]
.dropdownToolbarButton > select {
    background-color: var(--dropdown-btn-bg-color);
}
This large button is always dark highlighted, which colloquially in UX practices would signal a permanently pressed button where the mouse has not been released... It is a very poor way of attracting attention or desiring to mean this is the default option (which is wrong since it persists via user optin options too).
The consequence of this needless highlighting (as if my mouse was pressing it) is cognitive load, it is distracting me from the text I am reading.
Sure the design of the old UX was superior since it could afford to use that very innovative concept known as borders to delineate graphics elements

Anyway, a proper fix is to change the CSS selector to:
.dropdownToolbarButton > select {
    background-color: #F9F9FA;
}
which is the toolbar background color, hence this fat select button no longer attracts user attention and cognitive resources by **being more highlighted than the actual content..**

**Comment by Snuffleupagus** [comment]
> Anyway, a proper fix is to change the CSS selector to:
> .dropdownToolbarButton > select {
> background-color: #F9F9FA;
> }

Note that we don't accept hard-coded colors in the CSS nowadays, since for one that doesn't handle light/dark themes correctly.
Furthermore, by effectively removing any kind of "outline" from the zoom-dropdown it becomes more difficult to actually find e.g. its clickable area in the toolbar.

Hence *some* kind of colour difference (by way of a background-color) is probably required here, note also how `<select>`-elements are styled in e.g. the Firefox option pages.
While we could perhaps tweak the existing colours of the zoom-dropdown, it's not really clear how that should actually be done (we'd probably need an updated design spec).

**Comment by LifeIsStrange** [comment]
> Note that we don't accept hard-coded colors in the CSS nowadays
Well then that means you already have defined a CSS variable for the background-color of the toolbar, then you can reuse it there.

I disagree, yes in an ideal world you would have an UX that has no such issues, like the previous PDF.js UX, however given your current borderless style, tradeoffs have to be made (although I would personally advocate for a reversal to the previous UX).
Here the issue you point, that the dropdown being selectable is less clear, is true, it is a bit less obvious, but it is still not hard to understand. The down arrow explicitly exists for showing it's a dropdown arrow, and more importantly the + and - icons allows to change the dropdown values. Add to this it is the central obvious button of the whole interface and therefore the most well discovered and used by end users, so the loss of discoverability is IMHO very low. While the cognitive distraction of it being dark highlighted is IMHO not low at all.

**Comment by Snuffleupagus** [comment]
Further UI improvements/modernizations are already being tracked [bug 1718881](https://bugzilla.mozilla.org/show_bug.cgi?id=1718881), hence I don't believe that we need to keep this specific issue open here (as mentioned, any changes would be simpler with an official design specification to follow).
