### ISSUE TITLE
Text is not rendered

### ISSUE THREAD

**Issue by tobiUP** [mozilla/pdf.js#14881]
Attach (recommended) or Link to PDF file here: [Zu_MR_INF_2223.pdf](https://github.com/mozilla/pdf.js/files/8638426/Zu_MR_INF_2223.pdf)

Configuration:
- Web browser and its version: Firefox 102.0a1 (2022-05-05) (64-bit)
- Operating system and its version: Windows 10 Pro x64 19044.1682
- PDF.js version: 2.14.224
- Is a browser extension: No, the built-in version in Firefox

Steps to reproduce the problem:
1. Open the attached PDF file
2. Go to page 3 and see that all the text is missing.
3. Open the PDF file in Adobe Reader DC and see how it should look like

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/15669647/167091507-601e8dd3-08b7-41f0-bba4-86be327cadf3.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/15669647/167091746-ececddd3-f710-4e9a-a472-9210b127c871.png)

Console log:
Warning: Unknown field name, falling back to empty field name.
PDF 59d44a749e1b8c6b0b32d0ab3dc4eff0 [1.6 Apache FOP Version 2.6 / FOP] (PDF.js: 2.14.224)
Warning: cmap table has unsupported format: 12
downloadable font: OS/2: Adjusting head.macStyle (italic) to match fsSelection (font-family: "g_d0_f7" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!
