### ISSUE TITLE
Extracting attachments from PDF files

### ISSUE THREAD

**Issue by rafagsiqueira** [mozilla/pdf.js#14883]
[PDF with attachments.pdf](https://github.com/mozilla/pdf.js/files/8642099/PDF.with.attachments.pdf)

Configuration:
- Web browser and its version: Chrome (Version 101.0.4951.54 (Official Build) (x86_64)) and Firefox (100.0 (64-bit))
- Operating system and its version: Mac OS X 11.5
- PDF.js version: 2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1) A PDF file is added to the web application using an input object
2) A PDFDocumentProxy is created from the Uint8Array content of the PDF file
3) We try to extract attachments from the PDFDocumentProxy
See snipped below
```
const pdf$ = from(file.arrayBuffer()).pipe(
      map((content: ArrayBuffer) => new Uint8Array(content)),
      switchMap((blob: Uint8Array) => getDocument(blob).promise)
    );
    const attachments$ = pdf$.pipe(
      switchMap((pdf: PDFDocumentProxy) => from(pdf.getAttachments())),
      map((attachments: any) => {
        console.log(attachments);
      })
    )
```

What is the expected behavior? The table with the attachments should be returned.

What went wrong? Attachments table is null.

**Comment by Snuffleupagus** [comment]
> Trying to extract attachments from PDF file using pdf.js.

The `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is required in order for this (or any issue really) to be actionable.

> Steps to reproduce the problem:

Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> What went wrong? Attachments table is null.

Most PDF documents do *not* contain any attachments, are you actually sure that yours does?

**Comment by rafagsiqueira** [comment]
@Snuffleupagus , apologies. I added a test PDF above. When opening it on Firefox I can see the attachments, but I can't extract them using the pdf.js library.

**Comment by Snuffleupagus** [comment]
That's because your document doesn't actually contain any "normal" attachments, however it does have `FileAttachment`-annotations (which are not the same thing).
To access those you'll have to use the [`getAnnotations`-method](https://github.com/mozilla/pdf.js/blob/cfac6fa511945ae5b75d3c27a9356527862a7bf6/src/display/api.js#L1310-L1315) on each page-instance, and loop through the returned array looking for ones with `subtype === "FileAttachment"`.

**Comment by rafagsiqueira** [comment]
Thank you very much @Snuffleupagus !
The PDF is generated by Outlook when exporting emails which have attachment as PDFs. I have no control over that.
