### ISSUE TITLE
"Download" does not respect the browser's settings about the default download directory

### ISSUE THREAD

**Issue by kqwyf** [mozilla/pdf.js#14908]
Configuration:
- Web browser and its version: Firefox 100.0
- Operating system and its version: Manjaro (KDE) latest
- PDF.js version: 2.14.102 (obtained from _pdfjsLib.version in Firefox's debugger)
- Is a browser extension: Firefox builtin

Steps to reproduce the problem:
1. Set a default downloading directory in Firefox's settings (Settings - Files and Applications - Downloads - Save files to).
2. Open an online PDF file in Firefox.
3. Wait until it is loaded, then press "download" button.
4. A "Save As" dialog is shown.

What is the expected behavior?
The PDF file should be directly saved into the default directory without the dialog.

What went wrong?
The "Save As" dialog should not be shown. Instead, the PDF file should be directly saved to the default directory.

Some observations that may be of help:
If you press "download" button before the PDF file is totally loaded, the behavior will be as expected (i.e. automatically start downloading without showing a dialog for choosing the location).
It seems that when the PDF is not loaded, the button may call the browser's downloading API, which respect the default directory set by the browser. While if it is loaded, the button will try to call a "save as ..." function or something, and this does not follow the downloading rules.

Sorry but I am not sure whether this issue should be posted here or in the Firefox's repo. Just considering that since the button is named "download", then it should obey all the rules about downloading, rather than saving-as.

Also, it is understandable if this issue is not easy to be addressed since pdf.js cannot know the settings of the browser (I guess). Then is it possible to either:
- When the file is loaded, pressing the button will "download" it from a local path, so the browser's downloading API could be called.
- Add an option which force the "download" button to re-download the file even if it is loaded.

**Comment by Snuffleupagus** [comment]
> Sorry but I am not sure whether this issue should be posted here or in the Firefox's repo.

Could you please file a bug report in Bugzilla instead, more specifically at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=PDF+Viewer, since this unfortunately cannot be fixed *here* given that the affected ought to be in the Mozilla code-base rather than in this library?

**Comment by kqwyf** [comment]
Thank you @Snuffleupagus !

I found https://bugzilla.mozilla.org/show_bug.cgi?id=1760482 which reports the same problem as I did. Anyone interested in this issue could have a look at it. Basically, the conclusion is that the PDF viewer needs a "save as" functionality rather than "download". However, the button is named as "download" which is misleading.
