### ISSUE TITLE
React failed to compile missing class properties transform

### ISSUE THREAD

**Issue by JeremyMesca** [mozilla/pdf.js#14913]
Hi there! 
I'm trying to use this library, but unfortunately, i can't test anything.
I install it, and import it in one of my components. I start my front and : 

```
Failed to compile.

./node_modules/pdfjs-dist/build/pdf.js
SyntaxError: /Users/SomeGuy/Desktop/SomeProject/node_modules/pdfjs-dist/build/pdf.js: Missing class properties transform.
  3435 |
  3436 | class PixelsPerInch {
> 3437 |   static CSS = 96.0;
       |   ^
  3438 |   static PDF = 72.0;
  3439 |   static PDF_TO_CSS_UNITS = this.CSS / this.PDF;
  3440 | }

```

Configuration : 
- Macbook Pro M1
- React : 16.8.6
- pdfjs-dist : last version (2.13.216)

I have already try many thing, like add configuration to the webpack, try babel thing etc... But all of this solution 

I hope you can help me with this...

Thank's

**Comment by Snuffleupagus** [comment]
Most likely, everything in https://github.com/mozilla/pdf.js/issues/14912#issuecomment-1126064829 applies here as well.

> React : 16.8.6

Please note that the PDF.js developers/contributors cannot provide help/support for various frameworks.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by cjadhav** [comment]
+1
