### ISSUE TITLE
pdfjs-dist throws syntax errors in older browsers

### ISSUE THREAD

**Issue by dmudro** [mozilla/pdf.js#14912]
using pdfjs-dist on not-so-old user agents throws errors when parsing pdf.js; a couple of examples:

_SyntaxError: Invalid character: '#'_
Safari < 14.1 [does not support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#browser_compatibility) private field members; Safari 14.1 was released [in May 2021](https://en.wikipedia.org/wiki/Safari_version_history#Safari_14), which I think is not that long time ago
...here is one of many examples where private field is used in _the final bundle_: https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L3170

_SyntaxError: Unexpected token '||='_
Node.js < 15 [does not suport](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility) logical OR assignment operator; Node 14 is still widely used
...once again the syntax is used throughout the bundle, i. e. https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L1707

would it be possible to set the transpiler to be more backwards compatible? what's the strategy here?

**Comment by Snuffleupagus** [comment]
For anything except the latest browsers, you'll need to use a `legacy`-build of the PDF.js library; note the two different builds provided in https://mozilla.github.io/pdf.js/getting_started/#download or [the README-file in the `pdfjs-dist` library](https://github.com/mozilla/pdfjs-dist/blob/master/README.md) which points to https://github.com/mozilla/pdfjs-dist/tree/master/legacy

See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by cjadhav** [comment]
+1
