### ISSUE TITLE
Some of the chemical formulas are rendered incorrectly during the preview, as shown in the figure

### ISSUE THREAD

**Issue by OnePsycho** [mozilla/pdf.js#14925]
![image](https://user-images.githubusercontent.com/43296632/168713522-a120e549-7cea-4059-b46b-b791122dee6b.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately contains no actionable information.
