### ISSUE TITLE
right click on selected text in pdf viewer doesn't show "search Google" option

### ISSUE THREAD

**Issue by kinjalkishor** [mozilla/pdf.js#14923]
Attach (recommended) or Link to PDF file here:
Any pdf (file or link)
like: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://developer.download.nvidia.com/presentations/2007/gdc/UsingD3D10Now.pdf
Configuration:
- Web browser and its version: Vivaldi	5.2.2623.46 (Stable channel) (64-bit) 
- Operating system and its version: OS	Windows 10 Version 21H2 (Build 19044.1706)
- PDF.js version: 2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. open pdf file
2. select a text word and right click on it

What is the expected behavior? (add screenshot)
![739494f1-a7c2-4ee2-a915-045cab2894ca-image](https://user-images.githubusercontent.com/79158943/168630823-a5ec0068-fa07-4985-8587-eca9562aaa8c.png)

What went wrong? (add screenshot)
right click on selected text in pdf viewer doesn't show "search Google" option, instead shows copy/save image option (pdf are in text format, both opened from file system or opened from web link)
Previously it was working with Vivaldi on this extension. (this works on same extension in Opera/Brave/Google Chrome browser also).
![0633487b-0899-431e-9d9b-acf1f49af3ab-image](https://user-images.githubusercontent.com/79158943/168630873-92e3c469-5f41-4584-a483-97612905c806.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=en

**Comment by Snuffleupagus** [comment]
> Previously it was working with Vivaldi on this extension. (this works on same extension in Opera/Brave/Google Chrome browser also).

That points rather clearly to a *browser-specific* bug, given that it apparently worked before and that it works in e.g. Google Chrome.

Also, as far as I know, there's never been any guarantees about the the PDF.js Chromium-addon working in e.g. the Vivaldi browser. (And the official Chromium-addon has also, most unfortunately, not been updated in over two years.)
