### ISSUE TITLE
Chrome 2D Canvas Acceleration on M1 Macbook Air produces white bars

### ISSUE THREAD

**Issue by agurvich** [mozilla/pdf.js#14938]
Attach (recommended) or Link to PDF file here:
[FPS_test.pdf](https://github.com/mozilla/pdf.js/files/8730653/FPS_test.pdf)

Configuration:
- Web browser and its version: Chrome Version 101.0.4951.64 (Official Build) (arm64)
- Operating system and its version: macOS Monterey, MacBook Air (M1,2020)
- PDF.js version: latest? (reproducible using [y'all's demo](https://mozilla.github.io/pdf.js/web/viewer.html))
- Is a browser extension: no

Steps to reproduce the problem:
1. produce a high resolution (?) pdf. (?) is because it's happened for all kinds of pdfs I've made using different programs. It doesn't happen for *all* pdfs but what seems to be in common is large/high resolution PDFs. 
2. open in the demo

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/7799423/169332374-fe7b8228-8cc3-4e0b-b2fd-f435becb69e8.png)

The above image is produced when 2d canvas acceleration is disabled:
![image](https://user-images.githubusercontent.com/7799423/169332049-6635477f-5170-4491-810a-75e067ce952e.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/7799423/169330571-32e811ac-c7b6-42c6-af9d-ded17de6ce34.png)
This is what happens when that flag is set to Enabled (which is the default in Chrome). I came across the behavior in  Overleaf PDF viewer (which is built with pdf.js, apparently). I regret to inform you that none of my colleagues have been able to reproduce the behavior. However, they do not have M1 Macs and thus I suspect the issue has something to do with that... I also regret to inform you that the PDF *does* render correctly using Chrome's built-in PDF viewer so it does seem like it has to do with pdf.js. Then again, y'all are the experts so maybe it truly is someone else's problem (which for your sake, I hope it is). 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by Snuffleupagus** [comment]
> This is what happens when that flag is set to Enabled (which is the default in Chrome).

The fact that this is connected with hardware acceleration of canvases unfortunately points to a *browser* (or platform) bug, since that shouldn't actually affect rendering in that way. See e.g. issue #14897, which is another recent issue related to hardware acceleration in Google Chrome.

Hence the only way forward here is unfortunately to report this, as bug related to hardware acceleration of canvases, to the Google Chrome project instead.

> I also regret to inform you that the PDF _does_ render correctly using Chrome's built-in PDF viewer so it does seem like it has to do with pdf.js.

Note that the built-in PDF viewer in Google Chrome, also known as PDFium, doesn't use the web-platform for its rendering.
