### ISSUE TITLE
Digital signature not rendered

### ISSUE THREAD

**Issue by angelaki** [mozilla/pdf.js#14943]
Document: [13f622d1-5539-4499-ae6d-91ce2b719b71_1.pdf](https://github.com/mozilla/pdf.js/files/8738431/13f622d1-5539-4499-ae6d-91ce2b719b71_1.pdf)

Configuration:
- Chrome Version 101.0.4951.67 (Official Build) (64-Bit)
- Windows 11
- PDF.js version 2.2.171

The digital signature added at the bottom of the document won't get rendered:

**Should:**
![image](https://user-images.githubusercontent.com/38611461/169504301-a95f9fa7-b75a-4a92-93a2-5dc450141d13.png)

**Is:**
![image](https://user-images.githubusercontent.com/38611461/169504382-b9cadc59-44f3-45d6-98f7-8002ea9d49d8.png)

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/issues/14944#issuecomment-1132748935 applies here as well.

**Comment by angelaki** [comment]
Thank you so much! Sorry for not having checked it, I just expected the npm package to use the latest version.
