### ISSUE TITLE
Font size / paragraphs / new lines rendered wrong

### ISSUE THREAD

**Issue by angelaki** [mozilla/pdf.js#14944]
Document: [caad3efb-5f40-4c38-b2d8-cf0e76ce22a3.pdf](https://github.com/mozilla/pdf.js/files/8738456/caad3efb-5f40-4c38-b2d8-cf0e76ce22a3.pdf)

Configuration:
- Chrome Version 101.0.4951.67 (Official Build) (64-Bit)
- Windows 11
- PDF.js version 2.2.171

Size, new lines and paragraphs of text do completely differ.

**Should:**
![image](https://user-images.githubusercontent.com/38611461/169504810-101fea83-d321-4d37-8151-3768595cc378.png)

**Is:**
![image](https://user-images.githubusercontent.com/38611461/169504834-1ff03d1a-e43c-41b9-bf1a-0a62d18062db.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.14.290` in Firefox Nightly 102.

> PDF.js version 2.2.171

Note that that's first of all not an official release, as found at https://github.com/mozilla/pdf.js/releases
Secondly, that version is a few years old and thus no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by angelaki** [comment]
Thank you so much! Sorry for not having checked it, I just expected the npm package to use the latest version.
