### ISSUE TITLE
 Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by nsht** [mozilla/pdf.js#14956]
Attach (recommended) or Link to PDF file here:
[Broken PDF](https://filetransfer.io/data-package/uTaob7Mo#link)
Configuration:
- Web browser and its version: Chrome Version 100.0.4896.127 (Official Build) (x86_64)
- Operating system and its version: MacOS 12.2.1
- PDF.js version: 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1.  Load the above PDF

What is the expected behavior? (add screenshot)
PDF should render properly, the same PDF works fine in version [2.11.338](https://github.com/mozilla/pdf.js/releases/tag/v2.11.338) 

What went wrong? (add screenshot)
 PDF stops rendering midway with the error  `Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.`
 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/4677967/170052997-dda92de4-b6df-4e0b-b4cf-84915b61b3ce.png">

**Comment by Snuffleupagus** [comment]
WFM, when using https://github.com/mozilla/pdf.js#online-demo in both Firefox Nightly 102 and Google Chrome Beta 102 (on Windows).

Your screen-shot contains a `Deprecated API usage: ...`-warning, suggesting *something* being wrong in your implementation, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
