### ISSUE TITLE
characters not displayed

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#14953]
Attach (recommended) or Link to PDF file here:

http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf

Configuration:
- Web browser and its version: Firefox 100.
- Operating system and its version: Fedora 35.
- PDF.js version: the one that comes with web browser.
- Is a browser extension: yes.

Steps to reproduce the problem:
1. Open http://www.pragma-ade.com/general/manuals/xml-mkiv.pdf.
2. It’s on the first page, no text is displayed.

What is the expected behavior? (add screenshot)

![right-fonts](https://user-images.githubusercontent.com/203767/169893730-5408fdf8-ad34-4c21-85de-a4a7621dfe49.png)

What went wrong? (add screenshot)

![no-fonts](https://user-images.githubusercontent.com/203767/169893726-6f1ce775-5866-4271-86f7-09cc4bfd58f8.png)

**Comment by Snuffleupagus** [comment]
[issue14953_reduced.pdf](https://github.com/mozilla/pdf.js/files/8761060/issue14953_reduced.pdf)
