### ISSUE TITLE
I found compatibility issues

### ISSUE THREAD

**Issue by ww545** [mozilla/pdf.js#14961]
I don't know if anyone else has.
I use a UC browser！
There are three things that need to be addressed in the compiled PDF.js.

1, globalThis

2, padStart ()

3, new RegExp (" ^ (\ \ s) | | (\ \ p {Mn}) (\ \ p {Cf}) $", "u");

Solutions:

1. this.globalThis || (this.globalThis = this)

2. if (!String.prototype.padStart) {
            String.prototype.padStart = function padStart(targetLength, padString) {
              targetLength = targetLength >> 0; //floor if number or convert non-number to 0;
              padString = String(typeof padString !== 'undefined' ? padString : ' ');
              if (this.length > targetLength) {
                return String(this);
              } else {
                targetLength = targetLength - this.length;
                if (targetLength > padString.length) {
                  padString += padString.repeat(targetLength / padString.length); //append to original to ensure we are longer than needed
                }
                return padString.slice(0, targetLength) + String(this);
              }
            };
          }

3.const SpecialCharRegExp = new RegExp("^(\\s)|(\\p{Mn})|(\\p{Cf})$/u");

**Comment by Snuffleupagus** [comment]
The supported browsers are listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

---

*For future reference:* When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by kale365** [comment]
How to use the third solution？
