### ISSUE TITLE
Text selection is inaccurate.

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/pdf.js#14969]
Attach (recommended) or Link to PDF file here:
[Untitled.pdf](https://github.com/mozilla/pdf.js/files/8801004/Untitled.pdf)

Selecting and copying "is" gives "li " instead. Chrome and Preview do not have this problem.

It looks like the cause of this is using a monospace font for the text layer. What's the reason for that?

**Comment by Snuffleupagus** [comment]
One possible way to improve this is tracked in issue #13083, of which this is for all intents and purposes a duplicate.

**Comment by calixteman** [comment]
That said we still need to have a text layer for the screen readers.

**Comment by Mowmowj** [comment]
> That said we still need to have a text layer for the screen readers.

@calixteman  would like to know do you have some suggestion for this Text selection inaccurate issue, i am making a highlight tool it depend on the text selection precision.
