### ISSUE TITLE
Support adding comments/annotations (highlight)

### ISSUE THREAD

**Issue by marco-c** [mozilla/pdf.js#14975]
We are experimenting with basic PDF editing features.
This issue tracks implementing support for highlighting text and adding comments/annotations.

**Comment by Stamo-Gochev** [comment]
@marco-c Can you share more information about when the feature will be available? I see that no milestone has been defined and the issue is in the "to do" section, so I guess it is hard to tell, but I am working on a prototype project that will benefit from the functionality and as specifying a concrete release might not be possible, do you have plans to have this by the end of the year (2022)?

**Comment by marco-c** [comment]
@Stamo-Gochev I hope we will be able to get to this soon, but unfortunately we can't make any promises regarding the timeline.

**Comment by qwer1304** [comment]
How to activate in Chrome? (I built it from sources).
I tried modifying annotationEditorEnabled in pdf.js\extensions\chromium to true and rebuilding, but PDFViewerApplicationOptions.get("annotationEditorEnabled") in console still gives false and there're no new options in viewer.

**Comment by LibertyNLP** [comment]
> 

Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by LibertyNLP** [comment]
Hi , guys, I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by xerz-one** [comment]
Is a preview available with build flags or in another repository? What is the intended UX workflow like?

**Comment by SuperPat45** [comment]
Please add ability to cross out text in addition to the highlight

**Comment by marco-c** [comment]
Highlighting is not available yet, but you can draw or add text on PDFs with the latest version of Firefox.

**Comment by rubenkleiman** [comment]
Hi marco-c. Have you determined by now whether the pdf.js codebase is tractable for implementing annotations? If so, I might help on the coding end. API features I need: (1) highlight a text selection, (2) extract its PDF doc location and the text itself, and (3) edit or delete the highlighted text. The highlighted text has, of course, to be permanently embedded in the PDF. Thanks.

**Comment by marco-c** [comment]
@rubenkleiman this issue is tracking implementing those features. It is feasible, but some work is required.

**Comment by avishaan** [comment]
@rubenkleiman we had a similar issue and solved it by forking pdf highlighter repo which builds on top of this. Check it out here https://github.com/credolabs/react-pdf-highlighter we would love to hear your ideas as well

**Comment by marco-c** [comment]
There is now a meta bug on Bugzilla to track this work: https://bugzilla.mozilla.org/show_bug.cgi?id=1846098.

**Comment by marco-c** [comment]
And https://bugzilla.mozilla.org/show_bug.cgi?id=1863905 about the commenting.

We will close this issue, you can follow along on Bugzilla.

**Comment by shivaprsd** [comment]
As basic annotation features are now available, the [wiki](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations) should be updated.

/cc @timvandermeij
