### ISSUE TITLE
Is it possible render only selected pages of the PDF file in pdf.js?

### ISSUE THREAD

**Issue by Ryannn06** [mozilla/pdf.js#14977]
Is it possible to only show selected pages of the PDF file in the PDF.js? Like only the first 3 pages out of the 10 pages of the PDF file would be rendered in the pdf.js?

**Comment by Snuffleupagus** [comment]
If you're using the API *directly*, you can obviously choose to only fetch and render *some* of the pages in the document.

If you're actually asking about the default viewer, which isn't at all clear from the issue (hence why you should *always* fill out the ISSUE_TEMPLATE properly), then the answer is NO. (This sort of functionality seems like an edge-case and would generally add a lot of undesirable complexity).
