### ISSUE TITLE
Is there a smaller package to use for nodejs if all I want to do is extract content from PDF with getDocument / getTextContent

### ISSUE THREAD

**Issue by GitMurf** [mozilla/pdf.js#14986]
Configuration:
- Web browser and its version: **Electron app (newest version 19)**
- Operating system and its version: **Windows 11**
- PDF.js version: `"pdfjs-dist": "^2.14.305"`
- Is a browser extension: **No**

All I am trying to do is simply extract the plain text from a PDF. I do NOT need to use any of the features to view/show/create PDFs. Below is the extent of the code (simplified) that I need to use from `pdfjs`. Is there a "lite" version / module / script / file I can use that is much smaller in size than having to import the entire 20,000+ lines of code from the `pdf.js` file / `NPM pdfjs-dist node module`  since all I want is a subset of the features that the library offers? It just seems like overkill to have to package the entire library for this subset of the features.

Also am I correct to import from the `pdfjs-dist/legacy/build/pdf.js` location? I am seeing mixed examples and documentation out there for using pdfjs with Electron (nodejs).

```js
import { app, BrowserWindow, ipcMain } from 'electron';
import path from 'path';
const pdfjs = require('pdfjs-dist/legacy/build/pdf');

let mainWindow: BrowserWindow;

app.on('ready', () => {
// Electron code...
});

ipcMain.handle('extract-file', async (event, ...args): Promise<PdfContent> => {
    const fileLocation = "test.pdf";
    const pdfDoc = await pdfjs.getDocument(fileLocation).promise;
    const page = await pdfDoc.getPage(1);
    const pageContent = await page.getTextContent();
    const pageItems = pageContent.items;
    for (const eachItem of pageItems) {
        console.log(eachItem.str);
    }
});
```

**Comment by Snuffleupagus** [comment]
> All I am trying to do is simply extract the plain text from a PDF.

Please keep in mind that note that PDF documents are often much more complex

> Also am I correct to import from the `pdfjs-dist/legacy/build/pdf.js` location? I am seeing mixed examples and documentation out there for using pdfjs with Electron (nodejs).

Yes, in Node.js environments a `legacy/`-build must be used.

**Comment by Snuffleupagus** [comment]
> All I am trying to do is simply extract the plain text from a PDF.

Please keep in mind that PDF documents are often much more complex than they might seem (from the outside), and that it's thus necessary to support a fair amount of the PDF specification (which requires a bunch of code) even if you "only" want to extract text.

> Is there a "lite" version / module / script / file I can use that is much smaller in size than having to import the entire 20,000+ lines of code from the `pdf.js` file / `NPM pdfjs-dist node module` since all I want is a subset of the features that the library offers?

Unfortunately not, since providing many "specialized" builds would increase the maintenance and support burden too much for the few regular PDF.js contributors. 

> Also am I correct to import from the `pdfjs-dist/legacy/build/pdf.js` location? I am seeing mixed examples and documentation out there for using pdfjs with Electron (nodejs).

Yes, in Node.js environments a `legacy/`-build must be used.

**Comment by GitMurf** [comment]
@Snuffleupagus thank you for the quick response!

>Please keep in mind that PDF documents are often much more complex than they might seem (from the outside), and that it's thus necessary to support a fair amount of the PDF specification (which requires a bunch of code) even if you "only" want to extract text.

Totally understand! And I didn't mean to sound like PDF extraction is a "simple" process. More I just wanted to make sure I wasn't missing anything or doing anything wrong with the functionality I am looking for?

So from the sounds of your response, can you confirm the following for me?

1) generally speaking my sample code is the "right way" to use pdfjs in Node and I am targeting the proper import/require with `const pdfjs = require('pdfjs-dist/legacy/build/pdf');`

2) it is expected that I need to be bundling the entire ~25k lines of code with my app (Electron) from the `node_modules\pdfjs-dist\legacy\build\pdf.js` file?

3) I wasn't quite sure about this Node example where it mentions `"Requires single file built version of PDF.js"` and `"please run
// `gulp singlefile` before running the example"`. I am not sure what this `gulp singlefile` does/means and if that is something I should be doing?: https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js

![image](https://user-images.githubusercontent.com/64155612/172024319-387fe403-4eab-4c02-877f-950dea60f0e3.png)

I am simply installing and using `pdfjs` by running `npm i pdfjs-dist` and in my package.json for my Electron app I have as a dependency `"pdfjs-dist": "^2.14.305"`. Is there something else I could/should be doing? Or does it seem like overall I am doing the right thing to get pdfjs working with my Electron app?

Thank you SO much for your quick response and help!!!

**Comment by Snuffleupagus** [comment]
> 1. generally speaking my sample code above is the "right way" to use pdfjs in Node and I am targeting the proper import/require with `const pdfjs = require('pdfjs-dist/legacy/build/pdf');`

Yes, it looks generally reasonable for a Node.js environment.

> 2\. it is expected that I need to be bundling the entire ~25,000 lines of code with my app (Electron) from the `node_modules\pdfjs-dist\legacy\build\pdf.js` file?

Probably, but given that I've never used Electron it's impossible for me to provide any sort of definitive answer.

> 3\. I wasn't quite sure about this Node example where it mentions `"Requires single file built version of PDF.js"` and `"please run "gulp singlefile" before running the example"`. I am not sure what this `gulp singlefile` does/means and if that is something I should be doing?: https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js

Please just ignore that comment, it was *accidentally* left behind and it's been removed now :-)
That example should indeed be directly usable, together with latest version of the `pdfjs-dist`-package.
