### ISSUE TITLE
"Can't find variable: pdfjsLib" in macOS Safari

### ISSUE THREAD

**Issue by mrobe** [mozilla/pdf.js#14981]
The following example works in some browsers, but not Safari:

https://jsfiddle.net/erw47sjo/

"Script error"
"ReferenceError: Can't find variable: pdfjsLib"

Configuration:
- Web browser and its version: Safari 14.1.2
- Operating system and its version: macOS 10.14.6
- PDF.js version: I tried 2.14.305; 2.13.216 in the example.
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the fiddle and click **Run**.
2. Click the **Select PDF** button and choose a PDF file from your local disk.

What is the expected behavior? https://pasteboard.co/1gL3O2un8dhL.png

What went wrong? See above.

**Comment by Snuffleupagus** [comment]
The `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is missing, meaning that it's impossible to reproduce what's shown in the screen-shot.

> PDF.js version: I tried 2.14.305; 2.13.216 in the example.

Note that only version `2.14.305` is currently supported; see e.g. https://mozilla.github.io/pdf.js/getting_started/#download
Also, you may want to try using a `legacy/` version of the PDF.js library since I suspect that Safari may have trouble with the modern build.

---

Furthermore, when using an arbitrary document, your example works in both Firefox Nightly 103 and Google Chrome Beta 103 hence this unfortunately looks like a *browser bug* rather than one in the PDF.js library (since otherwise you'd expect it to be consistently broken).

Also, the example seems to contain lot of unrelated code; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mrobe** [comment]
OK, so I did a little more investigation and found the following. The issue seems to be that Safari <= v14 does not support private name methods. For that, Safari 15 is required. The symptom is an error in the console:

`Cannot parse class method with private name.`

FWIW, the error can be tested with this simple fiddle: https://jsfiddle.net/hjxqrnt3/6/

I have a report that the latest version of pdf.js works on iOS 15.4 Safari on an iPhone 10X device. I haven't yet tried it on desktop macOS. As a workaround, I reverted to use pdf.js 2.11.338, it loads in Safari 14.x without errors.

So, for anyone else who arrives here, the TL;DR; is that due to the use of private name methods in a few places (not sure how many, but possibly < 10), pdf.js can ONLY be used on the newest Apple devices. It looks like anything earlier than 09/2021 won't work.

Upshot: anyone on Apple platforms who hasn't upgraded to macOS Catalina or later cannot use pdf.js.

Personally, I find this disappointing.

**Comment by Snuffleupagus** [comment]
> Upshot: anyone on Apple platforms who hasn't upgraded to macOS Catalina or later cannot use pdf.js.

Yes they can, assuming that a `legacy/`-build of the PDF.js library is being used :-)

Please note that https://github.com/mozilla/pdf.js/issues/14981#issuecomment-1145719841 did already suggest that, see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and https://github.com/mozilla/pdfjs-dist/blob/master/README.md

**Comment by mrobe** [comment]
Thanks for these pointers, though I would say the FAQ is unclear and perhaps misleading, e.g. the text for Safari says:

`Some missing features/defects have been reported, but no problems in general.`

However, even the [basic demo](https://mozilla.github.io/pdf.js/legacy/web/viewer.html) for older browsers has a bunch of broken stuff on the left side of the window.

**Comment by Snuffleupagus** [comment]
> Thanks for these pointers, though I would say the FAQ is unclear and perhaps misleading, e.g. the text for Safari says:

Note that the FAQ section *starts* with the following paragraph, which is intended to cover older browsers in more general terms:
> From version 2.4.456 on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the -legacy-dist.zip suffix).

---

> However, even running the [basic demo](https://mozilla.github.io/pdf.js/legacy/web/viewer.html) for older browsers on Safari 14.x displays a bunch of broken stuff on the left side of the window.

While Safari is *not* the focus of development here, the `legacy`-viewer should work. Given that what's described above sounds unrelated to *this issue*, please open a new issue for that and include clear screen-shots showing the problem.
