### ISSUE TITLE
shading-filled bars in figure 10 of tracemonkey paper don't render on some OS's in firefox

### ISSUE THREAD

**Issue by cgjones** [mozilla/pdf.js#15]
On X11, android, and windows XP systems, the bars will likely not render.  This is because of https://bugzilla.mozilla.org/show_bug.cgi?id=664077 .  Filing this issue to track the Mozilla bug.

**Comment by SamyCookie** [comment]
I do not see this bug anymore on my machines.
* Debian Stretch (testing) 64 bits, firefox 39b1 and "PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.1.185)"
 * Debian Jessie (stable) 64bits, Firefox 38.0.1, and "PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.1.185)"
However, the upstream bug is not marked as corrected.
Anyone else can confirm that ?

**Comment by SamyCookie** [comment]
@timvandermeij Could you test this one too ? I think it's fixed now.

**Comment by timvandermeij** [comment]
I can reproduce this issue on Arch Linux x64.

**Comment by timvandermeij** [comment]
I have confirmed that Firefox 48 fixes this for me on Arch Linux. Closing as fixed, but if someone encounters this issue again after Firefox 48, please let us know and we can reopen this.
