### ISSUE TITLE
TypeError key.split("+")

### ISSUE THREAD

**Issue by devonadam** [mozilla/pdf.js#15007]
There is a new error now in Safari web browser
It wasnt there about a week ago

TypeError: key.split("+").at is not a function. (In 'key.split("+").at(-1)', 'key.split("+").at' is undefined)
tools.js:161

Configuration:
- Web browser and its version: Safari 15.2
- PDF.js version: https://mozilla.github.io/pdf.js/build/pdf.js

**Comment by Snuffleupagus** [comment]
*In general:* For anything except the very latest browsers, you should use a `legacy/`-build of the PDF.js library. Note that we provide two different builds in https://mozilla.github.io/pdf.js/getting_started/#download and also the different versions of the default viewer at https://github.com/mozilla/pdf.js#online-demo
