### ISSUE TITLE
Annotation popup is not displayed

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15012]
Attach (recommended) or Link to PDF file here:
[tracemonkey (9).pdf](https://github.com/mozilla/pdf.js/files/8869933/tracemonkey.9.pdf)

Configuration:
- Web browser and its version: Firefox nightly

A popup has no `Rect` entry, hence it's ignored when it has to be rendered on the annotation layer:
https://github.com/mozilla/pdf.js/commit/08d88a0235e72f7a7e21295faa5c4c9e7c5eccb8#diff-d7b040092cf6be09a276b785ba03c46e79bc8342cf4ae4fb1bc139dea8513425R2342

We could add an exception for the `PopupAnnotation` but it could break something in the SVG factory.
@Snuffleupagus could you have a look please ?

**Comment by Snuffleupagus** [comment]
The question, as far as I'm concerned, is that's "special" about this particular PDF document?
Note that we have code which is supposed to let a PopupAnnotation inherit the /Rect-entry from its parent:
https://github.com/mozilla/pdf.js/blob/a1bc5a8fe27fd6cc580b2c4aeef61da964a873e6/src/core/annotation.js#L2874-L2879

We also have existing test-cases that work fine as-is, see e.g. `annotation-link-text-popup.pdf`.

**Comment by calixteman** [comment]
My bad, the `Rect` entry is required for all the annotations so the pdf here is wrong.
Anyway it has been generated with Edge and Acrobat handles it correctly.
