### ISSUE TITLE
PDF copy /paste lossign format (No space between paragraphs) 

### ISSUE THREAD

**Issue by rajacsharp** [mozilla/pdf.js#15038]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open the sample document  https://mozilla.github.io/pdf.js/web/viewer.html
2.  Copy the text and paste it to Notepad++ or MS word see no space between paragraphs

What is the expected behavior? (add screenshot)
Copy/Paste should retain formatting
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/58780677/173347317-2d7ae70e-a3b9-46dc-ab7b-6119b466e536.png)
![image](https://user-images.githubusercontent.com/58780677/173347432-d4c7fedd-0fed-4454-8275-d8565f453383.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by calixteman** [comment]
I tried in Edge and in Acrobat and there are no space between paragraphs with them.
In Acrobat, the `-\n` are striped out and with Edge they're replaced by `\u0002` (STX).

**Comment by Snuffleupagus** [comment]
Please note that in general there's no concept of e.g. paragraphs in PDF documents[1], and that glyphs are *absolutely positioned* in PDF documents.
Hence I'm not sure that this, again generally, can actually work like you want and it thus seem (to me at least) that this works as intended here and that the issue thus could/should be closed.

---
[1] Possibly with the exception of tagged PDF documents, which doesn't apply to the `tracemonkey.pdf` file.
