### ISSUE TITLE
Problem rendering attached pdf

### ISSUE THREAD

**Issue by bmm6o** [mozilla/pdf.js#15044]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 102
- Operating system and its version: Windows 10
- PDF.js version: 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached PDF
2. Note the text is incorrect compared to Adobe or Foxit.

What is the expected behavior? See screenshot from Adobe. It does require Arial Unicode font to display properly.
![adobe](https://user-images.githubusercontent.com/3179039/173685685-e2ac9df9-8c0e-4a2d-b5cf-6647c06cf1bd.png)

What went wrong? See screenshot. It seems to mess up the character mappings, so that even the ASCII-range characters are mis-represented.
![pdfjs](https://user-images.githubusercontent.com/3179039/173685688-a7616a61-608d-4d07-a523-5af2d72cb28f.png)

**Comment by bmm6o** [comment]
Problematic PDF
[HY0030809983.pdf](https://github.com/mozilla/pdf.js/files/8903822/HY0030809983.pdf)

**Comment by Snuffleupagus** [comment]
> Note the text is incorrect compared to Adobe or Foxit.

Please note that that depends entirely on what fonts you have installed *locally*, since I'm not able to render the document correctly in either Adobe Reader or PDFium (in Google Chrome).

**Comment by bmm6o** [comment]
That's a good point. I did have to find a copy of Arial Unicode in order for Adobe to render it appropriately on my Windows machine.
Thanks for your quick response!
