### ISSUE TITLE
Acrobat JavaScript Bugs related with Forms

### ISSUE THREAD

**Issue by aki2014** [mozilla/pdf.js#15053]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by aki2014** [comment]
[pdfjs_form_demo2.pdf](https://github.com/mozilla/pdf.js/files/8927363/pdfjs_form_demo2.pdf)
PDF.js version: 2.15.125 & Firefox 101.0.1

Steps to reproduce the problem:
1. Click the button labeled "Button1"

What is the expected behavior?
1. The message "This message can be toggled" message will disappear including the textbox border (red border).
2. The Button labeled "This Button can be toggled" will disappear.

What went wrong?
1. The textbox border remains while it should be invisible as well.
2. The button remains visible while it should be invisible.

Notice that both Adobe Reader and Chrome PDF Viewer show no problems for the same PDF.
Thank you in advance.

**Comment by calixteman** [comment]
When clicking on `Button 1` the text field is hidden but we just hide the `input` element and not the `section` which has the border.
And I didn't implement the button JS stuff for now.
