### ISSUE TITLE
[Annotation] Get rid of use of `id` in the annotation layer

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15056]
For example, try to open:
https://www.irs.gov/pub/irs-pdf/f1040.pdf#77R

in the console we have:
`PDFLinkService.goToDestination: "null" is not a valid destination array, for dest="77R".`

now press enter in the address bar and the document is scrolled on page 2.

If a destination is named `77R` we could have a bug.

For reference:
https://github.com/mozilla/pdf.js/pull/15054#discussion_r900210174

As far as I can tell this `id` is only used by JS stuff.

**Comment by Snuffleupagus** [comment]
Instead of an `id` added to elements, should we perhaps add a new *custom* attribute (and if so what to call it) so that we can find them easily using something like the following?
```javascript
document.querySelector(`[data-annotation-id="${id}"] > [data-annot-widget="true"]`);
```

**Comment by Snuffleupagus** [comment]
Instead of an `id` added to elements, should we perhaps "replace" that with a *custom* attribute so that we can find them easily using something like the following?
```javascript
document.querySelector(`[data-element-id="${id}"]`);
```

The only thing that might become a little bit annoying is that we probably need to update lots of integration-tests...
