### ISSUE TITLE
Better User Interface 

### ISSUE THREAD

**Issue by iDCoded** [mozilla/pdf.js#15068]
Here are 2 concepts that I came up with for the UI of [pdf.js](https://github.com/mozilla/pdf.js).
These are nothing too out of the box, the main idea here is having a floating bar that can be moved around according to the user's convenience. 
Additionally, I think the current UI is quite outdated, and most of us will agree with that, it about time to improve the look and feel of this pdf viewer to make it look more modern while maintaining it's minimalism. 

---

![PDFjs (1)](https://user-images.githubusercontent.com/65074550/174543889-390188c3-aa74-41c4-a7ce-7f82f388a746.png)
![PDFjs (2)](https://user-images.githubusercontent.com/65074550/174543893-624549a9-0751-4d32-bac8-a42615e58399.png)

**Comment by Snuffleupagus** [comment]
> These are nothing too out of the box, the main idea here is having a floating bar that can be moved around according to the user's convenience.

Creating a movable toolbar would definitely be non-trivial, furthermore please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
