### ISSUE TITLE
The simplified Chinese content in the PDF is not displayed, but the text is displayed normally after downloading

### ISSUE THREAD

**Issue by qinghuan065** [mozilla/pdf.js#15086]
Attach (recommended) or Link to PDF file [here:]

Configuration:
- Web browser and its version:  Chrome（102.0.5005.115正式版本 ）&&  Microsoft Edge（102.0.1245.44 正式版本) 
- Operating system and its version: Windows 10 专业版
- PDF.js version: ^2.5.207
- Is a browser extension:

Steps to reproduce the problem:
1.   The test PDF is edited by myself (including Chinese text and pictures).
2.   View the PDF after base64 transcoding. 

What is the expected behavior? (add screenshot)
the text is displayed normally whether it's downloaded

What went wrong? (add screenshot)
the Chinese text is not displayed, but the text is displayed normally after downloading

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file [here:]

Without this information, the issue is unfortunately not actionable/valid.

> PDF.js version: ^2.5.207

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by qinghuan065** [comment]
[Uploading 简体中文.pdf…]() 
this is my test pdf and please review my questiuon above. 
There was an error when downloading the latest dependency package, so I used this earlier version with 2.5.207

**Comment by calixteman** [comment]
The link is wrong.

**Comment by qinghuan065** [comment]
![pdfNotShowText1](https://user-images.githubusercontent.com/107908949/175292668-43280123-48fe-4c75-a7be-c156f88f8779.png)
![pdfNotShowText2](https://user-images.githubusercontent.com/107908949/175292692-060bad09-9d47-4c95-9e98-15e4d68d83c8.png)
there are BASE64 decoded PDF without Chinese text，but the text display after download

**Comment by qinghuan065** [comment]
I found this bug only exists in IOS, Android does not have this problem.

**Comment by qinghuan065** [comment]
> WFM, using PDF.js version `2.15.129` in Firefox Nightly 103.
> 
> Most likely you've not set the necessary CMap-parameters when calling `getDocument`, and there's probably warning-message(s) about that printed in the console, please see:
> 
> https://github.com/mozilla/pdf.js/blob/c5dc082da49bdf26e92ceca593451d5b63d48ab4/src/display/api.js#L152-L155
> 
> Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
> 
> Closing, since this seems to work and rather suggests a bug in your implementation.

I have set the necessary CMap-parameters when calling `getDocument`  and there's no warning-message(s) about that printed in the console. I just checked.  I am trying to upgrade this dependency package to the version you mentioned to see if I can solve this problem. thank you.

**Comment by qinghuan065** [comment]
> > I found this bug only exists in IOS, Android does not have this problem.
> 
> That does not, at all, agree with the configuration information you provided in [#15086 (comment)](https://github.com/mozilla/pdf.js/issues/15086#issue-1282081545) making it even more difficult to interpret this issue unfortunately.
> 
> Furthermore, if an issue can only be reproduced in particular platforms/browsers that unfortunately suggests a bug there rather than in the PDF.js library itself.

I found this problem with Chrome and Edge Browser when I first started developing locally，and I just noticed that it doesn't exist on Android but reappears on IOS。
