### ISSUE TITLE
我的 Android 项目使用了 pdf.js ，我手动添加了自动滚动的功能；可是 APK 长时间待机，pdf.js 产生了巨大的缓存，最终导致 APK 崩溃闪退

### ISSUE THREAD

**Issue by warmthsea** [mozilla/pdf.js#15080]
Attach (recommended) or Link to PDF file here:
any pdf file
任何pdf文件

Configuration:
- Web browser and its version: /
- Operating system and its version: Android 7.1 双核 2G 运行内存
- PDF.js version: last version
- Is a browser extension: false

Steps to reproduce the problem:
1. use pdf.js on app，pdf.js load file generates a lot of cache
2. after 1 hour eventually lead to apk flashback

What is the expected behavior? (add screenshot)
How to solve the huge cache generated by pdf.js loading

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/45450994/174985207-efdd4ebe-78e4-4ee3-976a-00304d945981.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://user-images.githubusercontent.com/45450994/174985745-06e4247d-ae8e-4caf-b558-44f69e5beeda.mp4

**Comment by Snuffleupagus** [comment]
First of all, please note that you need to communicate only *in English* when using this bug tracker.
Secondly, the entire ISSUE_TEMPLATE must always be properly filled in (including the `Configuration:`-section).

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
