### ISSUE TITLE
[Chrome] Pdf does not display all contents in a table with 'automatic zoom' 

### ISSUE THREAD

**Issue by cvtoro** [mozilla/pdf.js#15098]
Link to raw pdf file
[20 Pay MK (1).pdf](https://github.com/mozilla/pdf.js/files/8978703/20.Pay.MK.1.pdf)

Configuration:
- Web browser and its version:  Chrome 102.0.5005.115
- Operating system and its version: Windows 10 19044.1466
- PDF.js version: 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1.  View first page of the pdf on **Automatic Zoom**

What is the expected behavior? (add screenshot)
All contents of the table in this pdf should display
![image](https://user-images.githubusercontent.com/8909902/175612415-d9b5c10b-76e9-4a12-afe7-a9ba4aa5e8b0.png)

What went wrong? (add screenshot)
The table is missing elements. Changing the zoom level does cause the element to reappear.
![image](https://user-images.githubusercontent.com/8909902/175612743-158b7ed2-bac6-4439-a70b-f870ff460e82.png)

**Comment by Snuffleupagus** [comment]
Given that it works in Firefox, which is the *primary* development target, this unfortunately looks like a *browser bug* rather than a general PDF.js bug since otherwise you'd expect it to be consistently broken everywhere.

**Comment by ToxicSmurf** [comment]
> Given that it works in Firefox, which is the _primary_ development target, this unfortunately looks like a _browser bug_ rather than a general PDF.js bug since otherwise you'd expect it to be consistently broken everywhere.

By _primary_ development target, do you mean _only_ development target? The chrome extension has been dormant for years.

**Comment by lvmajor** [comment]
I have the exact same problem in chrome, haven't yet tested in Firefox though, I will try that and report later (if I can manage to get Firefox as it's a really controlled environment 😅)

**Comment by teemu6** [comment]
I am having the same issue on latest pdf.js version (2.16.105). The bug appears **only** on chromium based browsers according to my tests (Chrome 105, Edge 105). Safari 15.3 and Firefox 104 works fine.

If the scale is set to 1 (or 1.0, 2, 2.0, 3, 3.0, 4 etc.), some texts are not visible on canvas. Other scale values work fine, such as 0.99, 1.01, 1.99 etc.

So as a workaround, avoid scaling with previously mentioned values and just use values close to it that are practically the same for the scale result.

**Comment by Snuffleupagus** [comment]
The fact that this only affects Chromium-based browsers, and only specific zoom-levels, suggests a `canvas`-related bug in the browser *itself*.
Hence this unfortunately doesn't really look fixable *here*, and note that (in general) we try to avoid introducing browser-specific compatibility hacks in the main code-base. So, please report this (as a `canvas`-bug) to the Chromium developers instead.
