### ISSUE TITLE
Find feature produces some wrong highlightments

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15094]
Attach (recommended) or Link to PDF file here:
[cd.pdf](https://github.com/mozilla/pdf.js/files/8976190/cd.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Search for `e` and `Highlight all`

![image](https://user-images.githubusercontent.com/5641725/175538217-dd660277-4bad-48c1-adbf-1d28030b3f87.png)

Something is wrong around the `B(cb, cs)`.
From the `find_controler`:
`...of the blend function B (c b , cs ) shall be the so...`

and from devtools:
![image](https://user-images.githubusercontent.com/5641725/175539183-ff455f01-59b1-4975-834d-f09983ec30b5.png)

The problem is the space between `c` and `b`: it's either an extra space in the searched string or a missing one in the html.

**Comment by calixteman** [comment]
So in the `TextLayer` case we have forced flush between the `c` and the `b`.
In the other one, we compare the positions of the two glyphs but with different font size and since the `b` is a bit smaller then a white space is guessed.
Having a space between `c` and `b` isn't a big deal, the real problem is that we've different behaviors which lead to something really wrong.
So fixing the extra space is another problem, but I think that in the search case we must flush the text chunk exactly at the same time as in the `TextLayer` case, just have something consistent.

@Snuffleupagus, do you have any thoughts here ?

**Comment by Snuffleupagus** [comment]
> but I think that in the search case we must flush the text chunk exactly at the same time as in the `TextLayer` case, just to have something consistent.

That sounds reasonable, since we obviously must return *consistent* textContent-data regardless of the `includeMarkedContent` value used.

Looking at the surrounding code, I can't help wondering why we don't also "flush" in the following case?
https://github.com/mozilla/pdf.js/blob/cd35b9bfac85c00238cf0fa0f657a780f2a5ead6/src/core/evaluator.js#L3292-L3299
