### ISSUE TITLE
Add a l10n linter

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15128]
When a l10n string is changed, then the id must be changed too.
In m-c we have:
https://searchfox.org/mozilla-central/source/third_party/python/compare_locales/compare_locales/lint/linter.py

**Comment by Snuffleupagus** [comment]
Given that a linter exists in mozilla-central, which should help catch issues at update-time, is it actually worth spending (a lot of) effort on this *here*? Especially since we've not, at least historically, modified existing `l10n`-strings on very many occasions.
