### ISSUE TITLE
I want to display PDF characters that do not exist in the table used for character code mapping processing.

### ISSUE THREAD

**Issue by HirokiTamura1** [mozilla/pdf.js#15139]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome 103
- Operating system and its version:Windows 10
- PDF.js version:react-pdf v5.5.0 and pdfjs-dist v2.13.216
- Is a browser extension:No

Steps to reproduce the problem:
1. Open PDF.
2.Text information in PDF is not displayed.

What is the expected behavior? (add screenshot)
Characters in PDF should be displayed without disappearing.

What went wrong? (add screenshot)
The PDF could not find the table reference used to map the fonts in the PDF.
The wording of the error is "Warning: loadFont --translateFont failed:" XRefEntryException: Bad (uncompressed) XRef entry: 28R ".
pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 28R, Warning: loadFont --translateFont failed: "XRefEntryException: Bad (uncompressed) XRef entry: 31R".
pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 31R ,,,, ".

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Publishing a PDF is difficult because the problem arises from the customer's PDF data used in the project.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always* required when opening an issue, since as-is it's unfortunately not actionable/valid.

> PDF.js version:react-pdf v5.5.0 and pdfjs-dist v2.13.216

Please note that "react-pdf" is a different project, and thus cannot be supported here.
Furthermore, the quoted PDF.js version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> The PDF could not find the table reference used to map the fonts in the PDF.
> The wording of the error is "Warning: loadFont --translateFont failed:" XRefEntryException: Bad (uncompressed) XRef entry: 28R ".
> pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 28R, Warning: loadFont --translateFont failed: "XRefEntryException: Bad (uncompressed) XRef entry: 31R".
> pdf.js: 1895 Warning: Error during font loading: Bad (uncompressed) XRef entry: 31R ,,,, ".

That sounds like a *very* corrupt PDF document...

> Publishing a PDF is difficult because the problem arises from the customer's PDF data used in the project.

Unfortunately this means that we'll have to close the issue as INCOMPLETE. Please try and create a *reduced* test-case, with the sensitive data redacted, to re-open this issue.

**Comment by HirokiTamura1** [comment]
[sample3c.pdf](https://github.com/mozilla/pdf.js/files/9099487/sample3c.pdf)I have created a PDF that can be published by editing customer information, so I will attach it.

The character part is displayed in other PDF viewers, but the character part is not displayed when using the viewer attached to PDF.js.

**Comment by HirokiTamura1** [comment]
We have prepared a shape of 3MB or less
[sample4a.pdf](https://github.com/mozilla/pdf.js/files/9137443/sample4a.pdf)

**Comment by Snuffleupagus** [comment]
> We have prepared a shape of 3MB or less
> [sample4a.pdf](https://github.com/mozilla/pdf.js/files/9137443/sample4a.pdf)

That one *still* contains very large image resources, and the filesize is only marginally smaller at 2.72 MB. Any chance of document *without any images at all*?
