### ISSUE TITLE
Coloured image displaying in black-white

### ISSUE THREAD

**Issue by ashemedai** [mozilla/pdf.js#15141]
Attach (recommended) or Link to PDF file here:
[KNMI_De_staat_van_ons_klimaat_2021_interactief_DEF.pdf](https://github.com/mozilla/pdf.js/files/9061779/KNMI_De_staat_van_ons_klimaat_2021_interactief_DEF.pdf)

Configuration:
- Web browser and its version: Firefox 102.0
- Operating system and its version: Windows 10 (21H1 build 19043)
- PDF.js version: No idea, doesn't seem to be easily accessible within Firefox
- Is a browser extension: yes, built-in

Steps to reproduce the problem:
1. Open PDF
2. Browse to page 9

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/610865/177728808-0573e876-f6bb-47fb-8976-063b6d019778.png)

The working image was taking from the PDF within Edge.

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/610865/177728753-365be161-b207-40a0-a452-4bb2fe5066c4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Additional notes:

Testing the same PDF on Firefox 102.0 on macOS (12.4) does show the correct image.

Edit: Upon further comparison, there seems to be more going on. At first I thought the blue channel was being stripped, but that would still leave red and green channels for some colours. It starts from the very first page, check the KNMI logo, check the interactive bar at the bottom of page 3 and onwards and the index buttons on page 2. They all got reduced to black.

**Comment by ashemedai** [comment]
Thanks @Snuffleupagus - just for the record, after reading that other report: I do not use high contrast mode. I do, however, use dark theme on this Windows system, as well as on the macOS system.

**Comment by THausherr** [comment]
Works for me on W10.0.19043.1766, FF 102.0 and 102.0.1. I don't use a dark theme.

**Comment by hughjonesd** [comment]
I have the same issue on MacOS 11.2 and FF 102.0.1 for this PDF: https://link.springer.com/content/pdf/10.1007/s10519-022-10107-w.pdf. All images are displayed in black and white.

**Comment by calixteman** [comment]
The easiest way to workaround the bug is to set:
 - `pdfjs.pageColorsBackground` to `#FFFFFF`;
 - `pdfjs.pageColorsForeground` to `#000000`;
in `about: config`.

**Comment by cxw-droid** [comment]
> The easiest way to workaround the bug is to set:
> 
> * `pdfjs.pageColorsBackground` to `#FFFFFF`;
> * `pdfjs.pageColorsForeground` to `#000000`;
>   in `about: config`.

The pdf viewer in Firefox works well, but when I tried to set pdf background color to sepia `#FBF0D9` with `pdfjs`, the image in pdf becomes black and white. Any workaround?

**Comment by calixteman** [comment]
It's only for HCM (High Contrast Mode):
https://www.accessibility-developer-guide.com/setup/helper-tools/high-contrast-mode/
Next time, please open a discussion instead of comment an old closed issue, thank you.
