### ISSUE TITLE
Incorrect position when drawing

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15150]
Attach (recommended) or Link to PDF file here:
[forced_colors.pdf](https://github.com/mozilla/pdf.js/files/9070844/forced_colors.pdf)

Configuration:
- Web browser and its version: Firefox
- Operating system and its version: Windows 11

What is the expected behavior? (add screenshot)
The pixel on the top-left corner should be red.
![image](https://user-images.githubusercontent.com/5641725/177964674-337d530d-7eda-4c8b-a1dd-805193c720a5.png)

In chrome:
![image](https://user-images.githubusercontent.com/5641725/177964741-bd66675d-2c03-4929-86fb-1f67321002a9.png)

and in Acrobat (zoom 1000%):
![image](https://user-images.githubusercontent.com/5641725/177964829-b0db5758-4ca3-4089-ae64-2dda61ecd54f.png)

**Comment by Snuffleupagus** [comment]
The PDF document looks *corrupt*, since both /Contents and /Resources try to use the same object reference.
Using http://brendandahl.github.io/pdf.js.utils/browser/ shows:
```
Trailer (dict)
        Size = 5
        Root (dict) [id: 1, gen: 0]
            Type = /Catalog
            Pages (dict) [id: 2, gen: 0]
                Type = /Pages
                Kids (array)
                    0 (dict) [id: 3, gen: 0]
                        Type = /Page
                        Parent (dict) [id: 2, gen: 0]
                        Resources (stream) [id: 4, gen: 0]
                            Length = 12
                            <view contents> [download](data:;base64,MC41IHcgMSAwIDAgUkcgMCA5Ljc1IG0gMC41IDkuNzUgbCBz)

                            0.5 w 1 0 0 RG 0 9.75 m 0.5 9.75 l s

                        MediaBox (array)
                            0 = 0
                            1 = 0
                            2 = 10
                            3 = 10
                        Contents (stream) [id: 4, gen: 0]
                            Length = 12
                            <view contents> [download](data:;base64,MC41IHcgMSAwIDAgUkcgMCA5Ljc1IG0gMC41IDkuNzUgbCBz)

                            0.5 w 1 0 0 RG 0 9.75 m 0.5 9.75 l s

                Count = 1
```

**Comment by calixteman** [comment]
Ah yes (I wrote the pdf myself by hand) and removing the Resources fixes the issue.

**Comment by calixteman** [comment]
Should we consider it is a bug even if the pdf is corrupted since it's ok in either Chrome and Acrobat ?

**Comment by Snuffleupagus** [comment]
> Should we consider it is a bug even if the pdf is corrupted since it's ok in either Chrome and Acrobat ?

Given that it *should*, in this particular case, be quite simple to fix things (with the caveat that I've not run any tests); we can probably try to patch it.
