### ISSUE TITLE
Extracting Acroform details on viewer.js

### ISSUE THREAD

**Issue by AnevMavris** [mozilla/pdf.js#15156]
Hi 

I hope you are all well.
Please assist with the below. I am using pdf.js viewer.html and it's working very well to render acroform pdf.
I would like to find out if there's a way to track acro-form inputs on a pdf through a listener in viewer.html and to find out if I can extract inputs after the pdf form has been filled.

I tried using an answer from StackOverflow as below but it did not work.

<script>
 async getAnnotations() {
    var result = {};                
    var pages = PDFViewerApplication.pdfDocument.numPages;
    for (var i = 1; i <= pages; i++) {
        var page = await PDFViewerApplication.pdfDocument.getPage(i);
        var annotations = await page.getAnnotations();
        for (var j = 0; j < annotations.length; j++) {
            var element = annotations[j];
            // Field Name
            if (result[element.fieldName] == null) {
                result[element.fieldName] = null;
            }
        
                var val = PDFViewerApplication.pdfDocument.annotationStorage.getOrCreateValue(element.id);
                if (element.radioButton) {
                    if (val.value) {
                        result[element.fieldName] = element.buttonValue;
                    }
                } else if (element.checkBox) {
                    result[element.fieldName] = val.value ? "On" : "Off";
                } else {
                    result[element.fieldName] = val.value;
                }                                
        }             
    };  
           console.log(result); 
      return result;
}
</script>

Regards
Sonwabo

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable/valid.

> I would like to find out if there's a way to track acro-form inputs on a pdf through a listener in viewer.html and to find out if I can extract inputs after the pdf form has been filled.

There's no event being dispatched when the `AnnotationStorage` is updated, however there's a callback function:
https://github.com/mozilla/pdf.js/blob/0205597bd09fca95684a8357b275f543d940f66a/web/app.js#L1723-L1729

> I tried using an answer from StackOverflow as below but it did not work.

Sorry, but we cannot provide support for code found elsewhere; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
