### ISSUE TITLE
it doesn't work properly on macbook. 

### ISSUE THREAD

**Issue by cuiyc2000** [mozilla/pdf.js#15160]
Attach (recommended) or Link to PDF file here:
helloworld.pdf exactly in examples.
Configuration:
- Web browser and its version: newest Chrome on Mac
- Operating system and its version: Macbook, M2
- PDF.js version: 2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? 
the project structure of mine, it's a simple html file:
<img width="1476" alt="iShot_2022-07-11_23 27 41" src="https://user-images.githubusercontent.com/68642492/178300963-195db259-b461-4c64-a9bb-f5d3278f6731.png">

What went wrong? 
I don't know if the usage is correct, it behaved like this:
<img width="1471" alt="iShot_2022-07-11_23 27 01" src="https://user-images.githubusercontent.com/68642492/178300991-9352c504-c015-4317-9668-f4c28b5560a8.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
