### ISSUE TITLE
Mobile Safari invalid character '#'

### ISSUE THREAD

**Issue by avanhovedev** [mozilla/pdf.js#15164]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari IOS 15.5
- Operating system and its version: IOS 15.5
- PDF.js version: 2.13.105
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF with PDF.js on safari
2. There is only the loading and nothing is happen

What is the expected behavior? (add screenshot)
The PDF preview

What went wrong? (add screenshot)
There are 2 JS errors on web page loading:
![image](https://user-images.githubusercontent.com/61686963/178538536-0e272702-f617-40cc-94c8-59b471ff8497.png)
![image](https://user-images.githubusercontent.com/61686963/178538567-60626302-fd06-4c8d-aab9-b46d0504102a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.13.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Furthermore, note the two different versions listed there and that [as mentioned in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support) you need to use a `legacy`-version for anything except the latest browsers.
