### ISSUE TITLE
viewer.html is not showing pdf and viewer

### ISSUE THREAD

**Issue by frankmehlhop** [mozilla/pdf.js#15178]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome + Edge current version
- Operating system and its version: Windows 11
- PDF.js version: 2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. download pdfjs
2. start web/viewer.html

What is the expected behavior?
I guess I should see a example pdf inside the viewer.

What went wrong?
I downloaded pdfjs from three different sources.
(mozilla.github.io, jsdelivr.com, one more)
One time viewer.html is not available and two times the presentation looks weird. (see below)

**Why I don't get a pdf viewer by starting viewer.html in a browser?**

Screen shot 1:
I checked the pdf an the path and both is fine.
![viewer01](https://user-images.githubusercontent.com/24494948/179510252-a5e25ef3-6c49-4687-b530-3a448d97ae5a.png)

Screen shot 2:
![viewer02](https://user-images.githubusercontent.com/24494948/179510256-975aba02-9c13-40a0-ae0d-a37686ea0e25.png)

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. download pdfjs
>     2. start web/viewer.html

As outlined in https://github.com/mozilla/pdf.js#getting-the-code, you need to use a server rather than loading the viewer from a `file://` URL.

**Comment by frankmehlhop** [comment]
Thank you!
