### ISSUE TITLE
How can I set the path of the pdf file?

### ISSUE THREAD

**Issue by frankmehlhop** [mozilla/pdf.js#15205]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome current version
- Operating system and its version: Win 11
- PDF.js version: 2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. create Blazor project
2. add <iframe src="pdfjs/web/viewer.html?pdffile=/pdf_collection/00000001.pdf"></iframe>

What is the expected behavior? (add screenshot)
I like to set the pdf file, which is shown at the viewer.html.

What went wrong? (add screenshot)
I don't know how to pas the argument of the pdf path to the viewer.
I tried like src="pdfjs/web/viewer.html?pdffile=/pdf_collection/00000001.pdf", but it does not work. May be wrong path, but I guess wrong way of passing the path.
**How I can set the path of the pdf file?**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file
If that (somehow) doesn't help, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
