### ISSUE TITLE
PDF Text added by Supplier to Template not displaying in iframe

### ISSUE THREAD

**Issue by GreatNeighbours** [mozilla/pdf.js#15207]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version  :  Firefox
- Operating system and its version: Win 10 upto date
- PDF.js version: 0.5.8
- Is a browser extension:

Steps to reproduce the problem:
1.  We use a simple iframe to display PDF, nothing fancy (src = "/ViewerJS/?zoom=page-width#../Uploads/EDocPro/EDT-21072022-163634.pdf"
2.PDF opens and displays what I guess is a template used by the supplier without the Invoice particulars

3.  If I open with Acrobat or Acrobat Reader or the https://mozilla.github.io/pdf.js/web/viewer.html it displays correctly with the full text

As the PDF is not ours but something supplied to us we have no control over the fonts etc (I presume its something like that), how can we force the viewer to display it ?

What is the expected behavior? (add screenshot) - This is what the document actually should be
![image](https://user-images.githubusercontent.com/85852391/180388195-6bbe2e54-4f88-4251-a698-14a234dd133d.png)

What went wrong? (add screenshot) - This is what is displayed in Firefox
![image](https://user-images.githubusercontent.com/85852391/180387718-b28e7838-bec8-4588-ba7a-21284db45620.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[EDT-21072022-163634.pdf](https://github.com/mozilla/pdf.js/files/9165605/EDT-21072022-163634.pdf)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 0.5.8

That's not an official PDF.js release, and even if existed it'd be *almost ten years old*; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> We use a simple iframe to display PDF, nothing fancy (src = "/ViewerJS/?zoom=page-width#../Uploads/EDocPro/EDT-21072022-163634.pdf"
> [...]
> What went wrong? (add screenshot) - This is what is displayed in Firefox

That's clearly *not* the PDF.js default viewer, which is further confirmed by the "ViewerJS" string in your URL.
Hence you unfortunately opened this issue *in the wrong repository*, since the "ViewerJS"-project is *not* being developed here; furthermore I don't believe that project is still developed/maintained now.

**Comment by GreatNeighbours** [comment]
Well that not a particular helpful answer snuffleupagus !!!   Did you think I imagined using viewer for 5 years ??

Whilst I very much appreciate some people live and breathe their own particular technologies when I search for something and come up with : https://viewerjs.org/getit/ and it has a link that says 'latest' version its somewhat hard to assume this is not actually the case !!!!

Now the more polite and educated way of answering my query would have been....

Buddy it looks like you might have a very old version, try downloading the latest version from.....

I will try this now that I have this information and hopefully that will resolve my issue.

**Comment by calixteman** [comment]
Snuffleupagus' answer gave you the exact information you need and about "more polite and educated way...", sorry but it's likely a matter of taste, culture, whatever, .... 
Just as a reminder, some people here are working for free, on their spare time, to provide you a free product, so there is no need to be rude yourself in explaining us how to be polite or educated.

**Comment by GreatNeighbours** [comment]
Thanks but given this is supposed to be a place to get help from like minded individuals/experts there is no need for assumption or unwarranted denegration.

Assuming that I am not doing the same as you in a different field is.....

The first job of giving assistance is to understand the issue, the issue isn't that I have been using a fabulous piece of technology for 5 years without that doesn't exist !

As clearly articulated the fabulous piece of technology we have been using has suddenly presented an issue that we haven't seen before, one that appears to only occur on firefox browsers.  Personally I'd see that as an opportunity worthy of solving, not an opportunity to be rude.

Perhaps you can point me in the direction of installation instructions of the latest version, the VERY OLD version we have been using only needed to be dropped into the website folder for the viewer to function, however this does not appear to be the case with the latest version ?  and the page link provided provides no insight as to further installation.

I apologise for not knowing more about your product or need more than a viewer that works.

**Comment by timvandermeij** [comment]
@Snuffleupagus and @calixteman are completely correct here: "ViewerJS" is _not_ developed or maintained by us, so you opened an issue in the wrong repository. Therefore, as indicated, please open an issue at "ViewerJS" itself at https://github.com/webodf/ViewerJS/issues instead since it's impossible for us to provide support for a project that is not ours.

Locking this issue since the discussion is going nowhere and the response to _correctly_ provided help isn't polite and we want people to be treated respectfully here.
