### ISSUE TITLE
Rendering issue - File content is available but cannot view it

### ISSUE THREAD

**Issue by koyadeek** [mozilla/pdf.js#15203]
Attach (recommended) or Link to PDF file here:
[IRS Form (v.2) (1).pdf](https://github.com/mozilla/pdf.js/files/9159393/IRS.Form.v.2.1.pdf)

Configuration:
- Web browser and its version: Chrome Version 100.0.4896.75 (Official Build) (x86_64)
- Operating system and its version: macOs Big Sur version 11.6 
- PDF.js version: 1.5.188
Note latest version is giving problems with rendering every other file, this version perfectly fits our use case, just this form is an issue
- Is a browser extension:

Steps to reproduce the problem:
1. open this file using pdf js, It shows the content when highlighted but doesn't render

What is the expected behavior? (add screenshot)
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/109739513/180216404-1fc88378-6044-4043-a7d6-8992d7c06ae2.png">

What went wrong? (add screenshot)
<img width="1190" alt="Screen Shot 2022-07-21 at 8 39 19 AM" src="https://user-images.githubusercontent.com/109739513/180216515-9116a13d-ce6c-456f-b291-facf442dd5cb.png">Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.5.188

That version is no longer supported, since it's *over six years old; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Note latest version is giving problems with rendering every other file, this version perfectly fits our use case, just this form is an issue

Sorry, but such a statement unfortunately isn't actionable without any details. (And using software that's many years out of date is never a good idea, since you're missing out on lots of improvements.)

**Comment by koyadeek** [comment]
@Snuffleupagus Is there a way i can make my pdfs static using latest version? I dont want users to be able to edit the pdf in viewer itself

**Comment by Snuffleupagus** [comment]
Given the lack of details, it's somewhat difficult to tell *exactly* what you want to do; hence the following is general advise:
 - https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/src/display/api.js#L1399 and https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/src/display/api.js#L1151-L1162
 - https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/web/base_viewer.js#L241 and https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/web/base_viewer.js#L118-L122
 - https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/web/app_options.js#L71-L75

So assuming that you're using the default viewer, simply setting the `annotationMode` option to `1` might do what you want.

Finally, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by calixteman** [comment]
>     * PDF.js version: 1.5.188
>       Note latest version is giving problems with rendering every other file, this version perfectly fits our use case, just this form is an issue
> 

It'd be a very good idea to file some bugs about the problem you've with "other file".

**Comment by koyadeek** [comment]
I ran and built from source with few changes from previous comment

I changed this to `AnnotationMode.DISABLE`
> * https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/src/display/api.js#L1399

Set annotation value to 1

> * https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/web/app_options.js#L71-L75

I was able to get the annotation-tx*.pdf files to be non-editable. But while using the generic build in my application pdf does not load and is stuck with the default pdf `compressed.tracemonkey-pldi-09.pdf`

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/109739513/180279819-de82c99d-c896-4f13-984c-34e32503ee73.png">


Also, is there a way to disable the blue background for the editable fields?

![annotation-tx2](https://user-images.githubusercontent.com/109739513/180279319-cca7c9ec-bb24-4dc7-8821-90c3add8d473.JPG)
