### ISSUE TITLE
Overlapping texts only in a specific situation

### ISSUE THREAD

**Issue by Vahed-L** [mozilla/pdf.js#15213]
Hi, I'm facing an issue with pdf.js which causes overlapping texts in every different PDF file.
The flow of my code is, for each page in pdf file, there is an canvas object in DOM that page should be rendered on that canvas. but for some reasons texts are overlapping each other just in that enterprise app.
So after reading problems about pdfjs versions, graphic card problems and different operating systems, I come up with an testing approach to write a simple angular app with the exact same configuration, which works totally normal and correct without any overlapping texts.
[pdf sample](https://www.orimi.com/pdf-test.pdf)

I don't know what exactly cause this so I cannot help with reproducing it,
any help would be appreciated, thanks.

Configuration:
- Firefox 102, Chrome 103
- Windows 10
- PDF.js version : 2.14.305

Expected behavior
![Capture2](https://user-images.githubusercontent.com/109841391/180592278-7a9988f2-a983-41d8-b487-ca62a0a6ff2d.PNG)

What went wrong
![Capture](https://user-images.githubusercontent.com/109841391/180592290-12b5afcc-d00c-49a3-8ab0-961d5846e16e.PNG)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `2.15.259` in Firefox Nightly 104.

Most likely there's a bug somewhere in your code, but unfortunately it's simply impossible to help given the limited information provided above; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
