### ISSUE TITLE
pdf.js & Internet Download Manager

### ISSUE THREAD

**Issue by ionbreaker** [mozilla/pdf.js#15212]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 
- Operating system and its version: Windows 10
- PDF.js version: 19+
- Is a browser extension: IDM Version 2022

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 19+

That version does not exist; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Is a browser extension: IDM Version 2022

Note that this question only applies to https://github.com/mozilla/pdf.js#browser-extensions

Furthermore, given that we don't develop/maintain any "Internet Download Manager" here we thus (obviously) can't provide any help/support for that.
