### ISSUE TITLE
Loads all pages automatically without creating cache?

### ISSUE THREAD

**Issue by yuis-ice** [mozilla/pdf.js#15224]
Configuration:
- Web browser and its version: Chrome Version 103.0.5060.134
- Operating system and its version: The Server is on Ubuntu 18.04.5, the client/browser is on Windows 10 10.0.19043.1826
- PDF.js version: v2.14.305 (cloned from github an hour ago)
- Is a browser extension: No

What is the expected behavior?

I have a reason that I wanted to load all the pages, so I changed DEFAULT_CACHE_SIZE to a greater value.
But in order to cache them firstly I need to go through the pages manually pressing the page down key for countless times.

So It's desirable for me if I could load/cache all the pages automatically when I opened a pdf file. 
Is it possible through an option or modifying the source code? Thanks.

**Comment by Snuffleupagus** [comment]
> I have a reason that I wanted to load all the pages, so I changed DEFAULT_CACHE_SIZE to a greater value.

That's really not a good idea, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

> Is it possible through an option or modifying the source code?

Given the above, no such option exists. (Obviously anything is possible with source-code modification, however that's not something that we'll provide support for.)
