### ISSUE TITLE
Native text comment (annotation) is not visible in PDF document

### ISSUE THREAD

**Issue by prmahima** [mozilla/pdf.js#15222]
Attach (recommended) or Link to PDF file here: Attached in the comment section.

Configuration:
- Web browser and its version: 
Google Chrome 103.0.5060.114
Firefox 102.0.1
- Operating system and its version: Windows (Not specific to OS)
- PDF.js version:  '2.15.308'
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF file in https://mozilla.github.io/pdf.js/web/viewer.html
2. Native text comment (annotation) is NOT visible.

What is the expected behavior? (add screenshot)
1. Open the PDF file with Microsoft edge browser (I tried on 103.0.1264.71) Or open the PDF file with Adobe acrobat reader
2. Native text comment (annotation) is visible in blue colour.

What went wrong? (add screenshot)
Native text comment (annotation) is not visible in PDF document with pdf.js viewer where as it can be viewed in other applications.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by prmahima** [comment]
@[Snuffleupagus](https://github.com/Snuffleupagus) Our customer is uploading the document immediately. Please give some 10 mins time.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: Attached in the comment section.
> [...]
> Our customer is uploading the document immediately. Please give some 10 mins time.


*Once more:* Please save everyone's time by actually following the ISSUE_TEMPLATE and *directly attach* the PDF document to the initial post *immediately* when opening an issue.

Please keep in mind that this is an open-source *bug tracker*, frequented by many volunteers, rather than paid tech-support.

**Comment by prmahima** [comment]
@Snuffleupagus Customer is ready to upload the document now. Should I open a new ticket for this issue as this ticket is closed now?

**Comment by calixteman** [comment]
Please add the pdf here and next time just file the bug when you've the pdf.

**Comment by MargitPaul** [comment]
[dc05c650-9cd6-47d7-8790-67852b89cf1e_R0-0_001 (1).pdf](https://github.com/mozilla/pdf.js/files/9179971/dc05c650-9cd6-47d7-8790-67852b89cf1e_R0-0_001.1.pdf)

**Comment by calixteman** [comment]
There is no appearance stream.
The freetext annotation is correctly displayed in Acrobat, Edge, Foxit and Okular, but neither in Firefox nor Chrome.
So when there are no appearance, we must create a default one from the `Contents` entry.

**Comment by Snuffleupagus** [comment]
Duplicate of #6810
