### ISSUE TITLE
Error: JPX images with undefined color components not supported.

### ISSUE THREAD

**Issue by idkwiwtk** [mozilla/pdf.js#15220]
When i try example Previous/Next example at https://mozilla.github.io/pdf.js/examples/ and use [test.pdf](https://github.com/mozilla/pdf.js/files/9177290/test.pdf).

but image not render and error message: Error: JPX images with undefined color components not supported.

**Comment by Snuffleupagus** [comment]
[issue15220_page2.pdf](https://github.com/mozilla/pdf.js/files/9178570/issue15220_page2.pdf)

**Comment by idkwiwtk** [comment]
image rendering is well done.
good.
