### ISSUE TITLE
How can I pass a base64 string so that the viewer opens in the iframe with the pdf from the base64?

### ISSUE THREAD

**Issue by frankmehlhop** [mozilla/pdf.js#15255]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome current version
- Operating system and its version: Windows 11 current version
- PDF.js version:  2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. use a iframe for pdf.js
2. transfer a base64 string to show in Viewer

What is the expected behavior? (add screenshot)
I would like to pass a base64 string instead of a file path.

What went wrong? (add screenshot)
I can't figure out, how I pass the base64 string to show at the pdf.js Viewer.
I know to pass the path and it works.
I tried a lot to pass base64. I tried PDFView.open(myBase64, 0) or URL.createObjectURL(myBase64) in my Blazor C# code, 
but the Classes are unknown and I don't know where there are from.

**How can I pass a base64 string so that the viewer opens in the iframe with the pdf from the base64?**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version:  2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I would like to pass a base64 string instead of a file path.

That's not possible, and you'll need to call `PDFViewerApplication.open` manually with the Base64-data; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

---

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
