### ISSUE TITLE
Viewer issue (broken background) in iOS Safari

### ISSUE THREAD

**Issue by kanuay** [mozilla/pdf.js#15254]
I've also found the broken viewer problem when using PDF.js with iOS Safari. The viewer results varied depending on the combination of PDF.js version & Safari version.

Configuration:
- Web browser version: Safari iOS 12 & 15
- PDF.js version: 2.14-2.15 (also 2.16 online demo)

I download the released version 2.13, 2.14 & today's 2.15 then extract .zip to my localhost IIS website and open viewer.html.

I also test with the online demo (mozilla.github.io/pdf.js/web) which are v2.16.4 now and there are still the same results as v2.15. So if you want to reproduce this problem you may open these links with iOS Safari.

![pdf js-issue-220731](https://user-images.githubusercontent.com/61073462/182035985-990890b3-103e-43f2-93b4-7cac51ce1573.png)

![pdf js-issue-220731b](https://user-images.githubusercontent.com/61073462/182035991-fb0cb81d-b70f-4a1e-9fd2-2e25186282fe.png)

**Comment by Snuffleupagus** [comment]
Given that it apparently works with the `legacy`-version, based on your table, that's consequently the one that you need to use in Safari (since that browser lack support for some modern web-platform features).
