### ISSUE TITLE
Loading blank pages in Internet Explorer 11 browser 

### ISSUE THREAD

**Issue by devusersp** [mozilla/pdf.js#15258]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Window 10
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Add bookmarks and highlighters using Apspose PDF 
2. Load the generated document in IE 11

What is the expected behavior? (add screenshot)
<img width="541" alt="Expected_output" src="https://user-images.githubusercontent.com/110401404/182164792-b0e71028-feb6-4794-af3a-6797b82432ed.PNG">

What went wrong? (add screenshot)
<img width="952" alt="PDF_IE11_BlankPage" src="https://user-images.githubusercontent.com/110401404/182164497-e364d03a-a75c-4e32-a9e9-fe94651d5c28.PNG">
[PDFwithBookmarksAndHighlighterusingAspose.pdf](https://github.com/mozilla/pdf.js/files/9234458/PDFwithBookmarksAndHighlighterusingAspose.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, that browser is no longer supported.

**Comment by cksgh1224** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

The link above says IE/Edge (not Chromium-based). 
As far as I know, Edge is a Chromium based browser. Am I wrong?
