### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by noorqidam** [mozilla/pdf.js#15266]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 103.0.5060.134
- Operating system and its version: Windows 10
- PDF.js version: 2.6.347
- Is a browser extension: No

Steps to reproduce the problem:
1. I am using react version 16.12.0 and webpack version 4
2. when I installed pdfjs-dist:2.6.347 and @react-pdf-viewer/core: 3.6.0, react-pdf-viewer/default-layout 3.6.0

What is the expected behavior? (add screenshot)
![expect](https://user-images.githubusercontent.com/45481403/182585167-4dbbb506-1b67-40d9-8200-8fc2c1bdf4d0.png)

What went wrong? (add screenshot)
![error](https://user-images.githubusercontent.com/45481403/182585231-7333a7df-4dca-4791-a448-e4005925eb45.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> [...] and @react-pdf-viewer/core: 3.6.0, react-pdf-viewer/default-layout 3.6.0

Those are *different projects*, which are not developed/maintained here.

**Comment by noorqidam** [comment]
Hi @Snuffleupagus I've upgraded the pdfjs-dist version to version 215.349 and 214.305 but still getting the same error, I hope you provide a detailed solution.
does it have something to do with the devdependencies I'm using?
![image](https://user-images.githubusercontent.com/45481403/182767039-aa02fb43-6594-4740-9579-939dcee5fb19.png)

**Comment by ariguswahyu** [comment]
i have same issue, its takes a long day not solve yet
