### ISSUE TITLE
Can someone please explain, what is the use of pdf.sandbox.js file?

### ISSUE THREAD

**Issue by kpatne-mdsol** [mozilla/pdf.js#15273]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Not applicable 
- Operating system and its version: Not applicable 
- PDF.js version: 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1. Load pdf file and it shows pdf.sandbox.js not found
2. Though PDF renders correctly, but stillI need to understand what is use of pdf.sandbox.js?
What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

<img width="753" alt="Screen Shot 2022-08-04 at 2 52 43 PM" src="https://user-images.githubusercontent.com/85540218/182812585-6de9f441-7365-4047-a2e3-d08ccbf325b3.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> but stillI need to understand what is use of pdf.sandbox.js?

That's needed to support PDF documents that contain scripting (e.g. things like form validation). Hence the library/viewer still works fine without it, but some (more advanced) features may not be available in the viewer.
