### ISSUE TITLE
Expring URL and disabled autofetch

### ISSUE THREAD

**Issue by dodomorandi** [mozilla/pdf.js#15280]
We are using PDFs exposed through an S3 signed URL with an expiration. We were trying to disable the autofetch in order to reduce the bandwidth usage when reading small parts of the whole document, but once the URL is expired PDF.js cannot get chunks anymore.

The current solution is to cleanup the current `PDFDocumentProxy` and replace it using `getDocument` with a renewed URL, but this would work simply replacing the URL because the resource is exactly the same.

Do you think that it could be possible to expose an API to allow the users to replace the URL of the current resource?

**Comment by Snuffleupagus** [comment]
> Do you think that it could be possible to expose an API to allow the users to replace the URL of the current resource?

Sorry, but this really sounds like way too much of a special-case to warrant the added complexity. Especially considering that we already provide support for *custom* data-delivery; please see e.g. https://github.com/mozilla/pdf.js/issues/12953#issuecomment-772690603 for (some) additional details.
