### ISSUE TITLE
Correct way to use pdf.js with NPM/Yarn and Webpack 5

### ISSUE THREAD

**Issue by PandaBlackAndWhitr** [mozilla/pdf.js#15302]
Hi,
This is a general method question, if it's not relevant/a valid issue feel free to close.

## Problem
I've been trying to figure out the correct way to setup pdf.js with NPM/yarn, as I don't want to use a CDN source. I've been looking at the [official documentation](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website), [this helpful thread](https://github.com/mozilla/pdf.js/issues/12379), and various stackoverflow issues.

My understanding is that:
- pdf.js runs using a web worker
- That web worker must be configured somehow in `GlobalWorkerOptions` (either through a CDN source through a `script` tag or using the `pdfjs-dist` repository)

## Current Solution
Surrounding info outstanding, my solution to implement pdf.js essentially boils down to executing this line on start/boot:
```
GlobalWorkerOptions.workerPort = new Worker(new URL('pdfjs-dist/build/pdf.worker', import.meta.url));
```
_This follows [webpack's documentation](https://webpack.js.org/guides/web-workers/) on how to use web workers_

This solution allows me to import `getDocument` in my main code as normal (since `GlobalWorkerOptions` is statically set):
```
import { getDocument } from 'pdfjs-dist';
```

## Question
This however doesn't follow any of the documentation for pdf.js, which seems to solely use the `workerSrc` option to define the worker.
- Is there any reason why I shouldn't be doing it the way I'm doing it? It seems like such a simple solution, but the fact that no tutorial exists with it leads me to believe there's something I'm missing.
- The solution seems to be even webpack agnostic; according to their [documentation](https://webpack.js.org/guides/web-workers/), this works with native ECMAScript modules as well?

Thanks in advance

**Comment by Snuffleupagus** [comment]
> This however doesn't follow any of the documentation for pdf.js, which seems to solely use the `workerSrc` option to define the worker.

That's probably because it's (often) the easiest solution in most cases, and that our documentation is lacking in places.

> Is there any reason why I shouldn't be doing it the way I'm doing it? It seems like such a simple solution, but the fact that no tutorial exists with it leads me to believe there's something I'm missing.

Nope, it exists to be used in exactly those cases where it makes sense to do so :-)
As long as everything loads correctly and parsing/rendering of PDF documents work[1], then everything should be fine.

---
[1] Just make sure that there's no warnings such as e.g. `Setting up fake worker.` printed in the console.
