### ISSUE TITLE
\node_modules\pdfjs-dist\build\pdf.js: Missing class properties transform.

### ISSUE THREAD

**Issue by bimalstha23** [mozilla/pdf.js#15336]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 104.0.5112.101
- Operating system and its version: windows 11 version 21H2
- PDF.js version: 2.15.349
- Is a browser extension: No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot) 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Unfortunately this is missing too much information in order to be actionable, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
