### ISSUE TITLE
mozCurrentTransformInverse is deprecated

### ISSUE THREAD

**Issue by nagiatzi** [mozilla/pdf.js#15342]
Configuration:
- Firefox Browser Developer 103.0b9
- pdfjs-dist 2.15.349

Steps to reproduce the problem:
1.  The warning appears when trying to display a paginated pdf in Firefox Browsers. 

The exact message is "mozCurrentTransformInverse is deprecated and will be removed in the future. Use CanvasRenderingContext2D.getTransform() or CanvasRenderingContext2D.setTransform() instead."

Are there any plans to a possible upgrade related to this issue?

**Comment by Snuffleupagus** [comment]
*For future reference, when opening an issue:* Please don't forget to fill in the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE.

---

Fixed by PR #15281
