### ISSUE TITLE
Japanese character can't search when there is a new line

### ISSUE THREAD

**Issue by MoriyamaY** [mozilla/pdf.js#15340]
Attach (recommended) or Link to PDF file here:
https://www.meti.go.jp/policy/consumer/seian/denan/file/04_cn/scope/haninokaishaku_211228.pdf

Configuration:
- Web browser and its version: Google Chrome 104.0.5112.81
- Operating system and its version: Windows 10 Pro 21H2 19044.1826
- PDF.js version: v2.15.349
- Is a browser extension: No

Steps to reproduce the problem:
1. Search "検知機構" by Ctrl+F.

What went wrong? (add screenshot):
"検知機構" on page 5 must be hit.
If search "検知機 構"  (add space between 機 and 構), it hits.

<img width="612" alt="キャプチャ" src="https://user-images.githubusercontent.com/110510565/185837991-9c269f62-9a47-4ea2-a4cd-65eda8003cba.PNG">

When this PDF file is opened by Adobe Reader, there is no problem.

**Comment by calixteman** [comment]
My knowledge in Japanese is null, so if I say something wrong, please tell me.
If I understand correctly, here we've some Kanji which are more or less equivalent to some words so it such a case it makes sense to allow some whitespaces after a Kanji but in case of Hiragana or Katakana which are more or less equivalents to some letters or syllables it doesn't.
So if I'm correct, it should be possible to allow whitespaces after a "char" belonging to the [Ideographic](https://www.unicode.org/reports/tr44/#Ideographic) class.

@MoriyamaY, is it ok for you ? or am I wrong ?

**Comment by MoriyamaY** [comment]
@calixteman

I really appreciate your good job.

As well as Kanji, if Hiragana or Katakana are the last character on the line, there is an unnecessary white space.

In addition, v2.3.200 has no this problem.
