### ISSUE TITLE
[Bug] Text rendered incorrectly on Edge (small rectangles on text)

### ISSUE THREAD

**Issue by przem-przem** [mozilla/pdf.js#15353]
Attach (recommended) or Link to PDF file here:
[Sample PDF.pdf](https://github.com/mozilla/pdf.js/files/9432888/Sample.PDF.pdf)

Configuration:
- Web browser and its version: Edge 104.0.1293.63
- Operating system and its version: Windows 10, Windows 11
- PDF.js version: 2.11.338, 2.15.349
- Is a browser extension: No

The text rendered has small rectangles on it, position of rectangles change after each page reload.
The problem occurs only on Edge, but not on every computer, and therefore it cannot be reproduced on any device. 
From what we observed, the problem is not dependent on screen resolution/monitor.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/57131223/186897712-b374dd41-6799-417c-ac15-5855ab18259e.png)

What went wrong?
![image](https://user-images.githubusercontent.com/57131223/186897785-0dc41201-a78c-4d3a-9b94-b2360f913d79.png)
![image](https://user-images.githubusercontent.com/57131223/186897882-36d4a3ea-43bf-44f6-adb5-41e00840a230.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `2.16.86` in both Firefox Nightly 106 and Google Chrome 105 on Windows.

> The problem occurs only on Edge, but not on every computer, and therefore it cannot be reproduced on any device.

That unfortunately suggests that this is a *browser* bug (e.g. `canvas`-related) rather than a PDF.js one, since otherwise you'd really expect it to be consistently broken everywhere. As such this is unfortunately not really actionable/fixable here, and you'll need to report it to the Edge-developers as a `canvas`-related problem. (Please keep in mind that Firefox is the *primary* development target for this library.)

**Comment by StevenStPierre** [comment]
Some users (but not all of them) had a similar issue with Chrome and Edge.
While we investigate to fix it with a more permanent solution, here's a workaround that solved the problem for our users.

**Turn off accelerated 2D canvas rendering in Google Chrome or Edge with the following steps:**

1. In **Google Chrome**, enter **chrome://flags** in the address bar and press enter.
2. In the search bar, type accelerated 2d canvas
3. Change the setting from "Enabled" to "Disabled"
4. Click Relaunch
5. Then, test the PDF again

1. In **Edge**, enter **edge://flags** in the address bar and press enter.
2. In the search bar, type accelerated 2d canvas
3. Change the setting from "Enabled" to "Disabled"
4. Click Relaunch
5. Then, test the PDF again
