### ISSUE TITLE
'SetOCGState' action is not supported

### ISSUE THREAD

**Issue by mnj1004** [mozilla/pdf.js#15372]
Attach (recommended) or Link to PDF file here:
[sample2.pdf](https://github.com/mozilla/pdf.js/files/9460818/sample2.pdf)

Configuration:
- Web browser and its version: Firefox 104.0 (64-bit)
- Operating system and its version: Windows 10 Enterprise 20H2
- PDF.js version: 2.15.303 and 3.0.11
- Is a browser extension: No

Steps to reproduce the problem:
1. Show Layers panel
2. Uncheck 'Layer' to hide a layer
3. Show Document Outline panel
4. Click 'Display Layer' outline and see if the hidden layer appears back

**What is the expected behaviour? (add screenshot)**
![image](https://user-images.githubusercontent.com/34948107/187666631-accc61e4-0e5e-4914-a504-acaa6138edcd.png)
According to PDF Reference, set-OCG-state action should set the state of one or more optional content groups and for this sample pdf, the hidden layer should be back visible.

**What went wrong? (add screenshot)**
The outline performs no action.
When the sample pdf is opened in Adobe Reader, the outline works fine.

On loading the sample pdf, below message is displayed in console.
```console
Warning: parseDestDictionary - unsupported action: "SetOCGState".
```

**Comment by Snuffleupagus** [comment]
*Please note:* This doesn't seem commonly used in real-world PDF documents, since it's the very first time that this feature request has been made. (Even optional-content itself isn't all that common, and most of those documents don't use this specific feature.)
