### ISSUE TITLE
Text in hidden layer is searchable and selectable

### ISSUE THREAD

**Issue by mnj1004** [mozilla/pdf.js#15370]
Attach (recommended) or Link to PDF file here:
[sample2.pdf](https://github.com/mozilla/pdf.js/files/9460108/sample2.pdf)

Configuration:
- Web browser and its version: Firefox 104.0 (64-bit)
- Operating system and its version: Windows 10 Enterprise 20H2
- PDF.js version: 2.15.303
- Is a browser extension: No

Steps to reproduce the problem:
1. Show Layers panel
2. Uncheck 'Layer'
3. Open find bar by pressing `Ctrl + F`
4. Check 'Highlight All' option
5. Type 'e' in text input box and see text in hidden layer is highlighted

**What is the expected behaviour? (add screenshot)**
Only a character 'e' in 'Text' should be highlighted.

**What went wrong? (add screenshot)**
![image](https://user-images.githubusercontent.com/34948107/187642476-08447c84-9877-4731-8869-bdd78755eb51.png)
Character 'e' in 'Layer' which is in a hidden layer is also highlighted.

![image](https://user-images.githubusercontent.com/34948107/187642985-c63f79e3-b638-4390-ab6e-5db5e81c3569.png)
Also, you can drag-select text in the hidden layer.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.15.303

That is *not* an official version; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

This behaviour is *by design*, since having e.g. searching depend upon the currently visible layers are quite unlikely to be helpful to users in the general case. The PDF specification even contains the following, see "NOTE 4" at the bottom of [page 233](https://web.archive.org/web/20220309040754if_/https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=233):
```
[...] A full text search engine, however, may need to process all content in a document, regardless of its current visibility on-screen.
```

**Comment by mnj1004** [comment]
Thank you for your reply.
Is it possible to distinguish text in layer from normal text while rendering text layer using `getTextContent` ?

**Comment by Snuffleupagus** [comment]
> Is it possible to distinguish text in layer from normal text while rendering text layer using `getTextContent` ?

No such functionality exists unfortunately, since the textLayer is independent of the optional-content visibility (for the reasons outlined above).

**Comment by Snuffleupagus** [comment]
> Is it possible to distinguish text in layer from normal text while rendering text layer using `getTextContent` ?

Unfortunately it's not possible to determine the exact "layer"-id a piece of optional-content comes from in the textContent, since that's not functionality that's needed e.g. in the viewer (for the reasons outlined above).
