### ISSUE TITLE
pdf.js not loading pdf file on Chrome

### ISSUE THREAD

**Issue by IcaroAdao** [mozilla/pdf.js#15375]
Configuration:
- Web browser and its version: Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Operating system and its version: Windows 11
- PDF.js version: 2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
1. Choose pdf to be displayed
2. View does not render the pdf file

What is the expected behavior? (add screenshot)
![expected](https://user-images.githubusercontent.com/36521129/187751830-4d431f64-5b09-43d8-83f2-25a349fda024.png)

What went wrong? (add screenshot)
![not expected](https://user-images.githubusercontent.com/36521129/187751085-3488c564-5e4c-4fa3-bf0a-e260ff322c6e.png)

Further context:
I've been trying to use pdf.js in my application, I downloaded the prebuilt directory and pasted it in the public directory within my application. I'm using the viewer in a embedded tag like this:

```
<embed
        title="fileIFrame"
        src={`/PDFViewerJS/web/viewer.html?file=${file.url}`}
        height="100%"
        width="100%"
></embed>
```

The problem is that sometimes the pdf file is corrected loaded, but in another times the error above is being returned in the pdf viewer. The error mainly happens when I try to select other pdf to be displayed in the viewer when there's another one already being displayed.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Google Chrome Version 104.0.5112.102 (Official Build) (64-bit)

Is the problem reproducible in Mozilla Firefox, or only in Google Chrome?

> I've been trying to use pdf.js in my application, I downloaded the prebuilt directory and pasted it in the public directory within my application. I'm using the viewer in a embedded tag like this:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by IcaroAdao** [comment]
The problem is happening only in Chrome. I'll take a look on the second point, thank you!

**Comment by Snuffleupagus** [comment]
> The problem is happening only in Chrome.

In that case it unfortunately sounds like a *browser* problem, rather one a PDF.js library/viewer one (since otherwise you'd expect it to be consistently broken everywhere).

**Comment by IcaroAdao** [comment]
> > The problem is happening only in Chrome.
> 
> In that case it unfortunately sounds like a _browser_ problem, rather one a PDF.js library/viewer one (since otherwise you'd expect it to be consistently broken everywhere).

I've made a quick test on edge and it's also happening in there. Sorry, didn't have test in edge before

**Comment by Snuffleupagus** [comment]
> I've made a quick test on edge and it's also happening in there. Sorry, didn't have test in edge before

Given that Edge is a Chromium-based browser that's probably not too surprising actually; in any case this issue unfortunately isn't actionable as-is.
