### ISSUE TITLE
iOS minimum version needed is 15 using webpack?

### ISSUE THREAD

**Issue by re1709** [mozilla/pdf.js#15380]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 14.6
- Operating system and its version: ios 14.6
- PDF.js version: 2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. Importing pdfjs-dist/webpack and have worker-loader 3.0 installed
2. App crashes on safari ios 14.6 because of private methods, but works on safari iOS 15 because this added private methods

What is the expected behavior?
My understanding was that the distribution builds support iOS 13 and above? Is this no longer true, or are we expected to transpile the distribution if using webpack (feels wrong). We can look at building from source if needed, just wanted to clarify the version of iOS that is supported as minimum with the distribution build (using webpack).

What went wrong? (add screenshot)
App crashes because of private methods and these are not available in iOS 14.6 JavaScript engine.

**Comment by Snuffleupagus** [comment]
For anything except the *very latest* browsers, you'll need to use a `legacy` build of the PDF.js library; please note e.g. the two different builds available at https://mozilla.github.io/pdf.js/getting_started/#download or https://github.com/mozilla/pdfjs-dist/tree/master/legacy (with the latter mentioned in https://github.com/mozilla/pdfjs-dist/blob/master/README.md).

**Comment by re1709** [comment]
Thanks, so the legacy build is not usable with webpack then? (we are importing the webpack.js file) so the worker can be located.

Also that page says safari 13.1 is that including the legacy build as well?

**Comment by Snuffleupagus** [comment]
> Thanks, so the legacy build is not usable with webpack then?

Maybe not directly, but perhaps tweaking the paths in https://github.com/mozilla/pdfjs-dist/blob/master/webpack.js to point to the `legacy`-folder instead works? (Having never used the PDF.js library like that myself, it's somewhat difficult to tell.)

> Also that page says safari 13.1 is that including the legacy build as well?

That lists the minimum supported browsers, which generally means that a `legacy` build will be required. (As mentioned above, only the very latest browsers are supported in the "modern" build.)
