### ISSUE TITLE
Fails on to open pdf (Invalid PDF structure)

### ISSUE THREAD

**Issue by xieyoucai-git** [mozilla/pdf.js#15383]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Google Chrome 版本 102.0.5005.115
- Operating system and its version:
- PDF.js version: PDF.js v2.16.105 (build: 172ccdbe5)
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
PDF.js v2.16.105 (build: 172ccdbe5)
信息：Invalid PDF structure.
What went wrong? (add screenshot)
PDF.js v2.16.105 (build: 172ccdbe5)
信息：Invalid PDF structure.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
PDF.js v2.16.105 (build: 172ccdbe5)
信息：Invalid PDF structure.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required*, since there's no actionable information provided here.

Also, please remember to communicate only *in English* when using this bug tracker.
