### ISSUE TITLE
I get 403 error when I add custom header to httpHeaders.

### ISSUE THREAD

**Issue by nurullah** [mozilla/pdf.js#15399]
Attach (recommended) or Link to PDF file here: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Google Chrome Version 104.0.5112.79 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 16.04
- PDF.js version: 2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. I added an empty object to the httpHeaders option of getDocument. There is no problem.
```javascript
var loadingTask = pdfjsLib.getDocument({
  url: url,
  httpHeaders: {}
});
```
2. I added the custom header parameter in the httpHeaders option, i got an error like the Failed to Fetch. Is there any other parameter that i need to add to httpHeaders?
```javascript
var loadingTask = pdfjsLib.getDocument({
  url: url,
  httpHeaders: {
    "x-ms-version": "2011-08-18"
  }
});
```
![image](https://user-images.githubusercontent.com/10761479/188569713-8725f92c-1883-484c-aa9f-5a1057d1c005.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  https://codepen.io/nsei/pen/ZEoGXbL?editors=1011

**Comment by Snuffleupagus** [comment]
> Is there any other parameter that i need to add to httpHeaders?

That would be a question for the *server administrator*, since we cannot help with that.

> ink to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://codepen.io/nsei/pen/ZEoGXbL?editors=1011

Also, if you look the *browser* console you'll notice something like:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf. (Reason: CORS preflight response did not succeed). Status code: 403.
```
Note also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

**Comment by nurullah** [comment]
> > Is there any other parameter that i need to add to httpHeaders?
> 
> That would be a question for the _server administrator_, since we cannot help with that.
> 
> > Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://codepen.io/nsei/pen/ZEoGXbL?editors=1011
> 
> Also, if you look at the _browser console_ you'll notice something like:
> 
> ```
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf. (Reason: CORS preflight response did not succeed). Status code: 403.
> ```
> 
> See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

Thanks for your help. This helped me to understand the real problem. I need to add `x-ms-version` to `Access-Control-Allow-Headers` on the server. This was the reason why I got the error.
