### ISSUE TITLE
PDF landscape on mobile poor quality

### ISSUE THREAD

**Issue by LukeGarrigan** [mozilla/pdf.js#15405]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google chrome Version 105.0.5195.102 (Official Build) (64-bit)
- Operating system and its version: MS Windows 10 Pro 
- PDF.js version: //mozilla.github.io/pdf.js/build/pdf.js

Steps to reproduce the problem:
1. Go to the [sandbox page](https://codesandbox.io/s/pdf-js-landscape-7fj422?file=/src/index.js) I've setup 
2. Run the application in a new window:
![image](https://user-images.githubusercontent.com/12545967/188713398-ecc2db65-a69d-4ad1-a013-b4d4d06268df.png)
3. Open up the chrome dev tools
4. Choose to use emulate a mobile 
![image](https://user-images.githubusercontent.com/12545967/188714554-7ed2cb4e-a20a-4bde-a97d-74aba046e9c0.png)
5. Pinch use shift + draft
![image](https://user-images.githubusercontent.com/12545967/188714611-0234e4e2-4c4d-4850-817d-7157a5306d44.png)

The quality is awful, is there anything I can do to improve this?

This is the meat of the code for rendering:
```javascript
function renderPage(num) {
  pageRendering = true;
  pdfDoc.getPage(num).then(function (page) {
    const desiredWidth = canvas.width;
    const scaledViewport = getScaledViewport(page, desiredWidth);
    canvas.height = scaledViewport.height;
    canvas.width = scaledViewport.width;
    var renderContext = {
      intent: "print",
      canvasContext: ctx,
      viewport: scaledViewport
    };
    var renderTask = page.render(renderContext);

    // Wait for rendering to finish
    renderTask.promise.then(() => {
      pageRendering = false;
      if (pageNumPending !== null) {
        renderPage(pageNumPending);
        pageNumPending = null;
      }
    });
  });


function getScaledViewport(page, desiredWidth) {
  const viewport = page.getViewport({ scale: 1 });
  if (viewport.width > viewport.height) {
    const scale = desiredWidth / viewport.height;
    return page.getViewport({ scale: scale, rotation: 90 });
  } else {
    const scale = desiredWidth / viewport.width;
    return page.getViewport({ scale: scale });
  }
}
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://codesandbox.io/s/pdf-js-landscape-7fj422

**Comment by Snuffleupagus** [comment]
> Go to the [sandbox page](https://codesandbox.io/s/pdf-js-landscape-7fj422?file=/src/index.js) I've setup

That example fails to run, in both Firefox and Chrome, with the following error:
```
RangeError: Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.
    base64ToBlob index.js:3
    $csb$eval index.js:1
    H sandbox.fb5b9c101.js:4818
    evaluate sandbox.fb5b9c101.js:5649
    evaluateTranspiledModule sandbox.fb5b9c101.js:6249
    c sandbox.fb5b9c101.js:5631
    loadResources index.html:3
    $csb$eval index.html:9
    H sandbox.fb5b9c101.js:4818
    evaluate sandbox.fb5b9c101.js:5649
    evaluateTranspiledModule sandbox.fb5b9c101.js:6249
    evaluateModule sandbox.fb5b9c101.js:6220
    e sandbox.fb5b9c101.js:10268
    c runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 2
index.js:27:25
    e index.js:27
    e sandbox.fb5b9c101.js:2432
    e sandbox.fb5b9c101.js:10270
    c runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 2
```

Looking at the code though, it *appears* that you're not actually re-sizing and re-render the canvas on zooming. Hence that would mostly likely explain the problem, since a canvas (just like an image) cannot just be enlarged without losing quality.

**Comment by LukeGarrigan** [comment]
Can you try [the link again](https://codesandbox.io/s/pdf-js-landscape-7fj422) please?

So the point isn't that _if_ you zoom it has poor quality, I added that just to prove that it's not readable given its current scale. I.e if you were to be using a mobile device then you wouldn't be able to read the pdf document how it currently is.

**Comment by Snuffleupagus** [comment]
> So the point isn't that _if_ you zoom it has poor quality, I added that just to prove that it's not readable given its current scale.

(Well, that wasn't entirely clear from the original description.)

The one thing that's missing from your code seems to be handling of HiDPI screens, see e.g. https://mozilla.github.io/pdf.js/examples/index.html#rendering-the-page

Generally speaking, if you're trying to write your own viewer it's probably simpler to base that upon the "viewer component"-examples instead; see https://github.com/mozilla/pdf.js/tree/master/examples/components which are intended for usage together with https://github.com/mozilla/pdfjs-dist
