### ISSUE TITLE
Edge browser doesn't work properly when the word content contains a few tables inside.

### ISSUE THREAD

**Issue by Hooray0617** [mozilla/pdf.js#15409]
Attach (recommended) or Link to PDF file here:
[测试文件.zip](https://github.com/mozilla/pdf.js/files/9503301/default.zip)

Configuration:

Now I raised this question the second time, last time I was told QQ browser is not supported，then I tried the Edge browser,  and the same problem happens,  which has puzzed me for a long time. Wish to get your reply soon, thank you!
 
Web browser and its version: Edge browser of the latest version(104.0.1293.70) on the mobile phone.
Operating system and its version: Harmony OS 2.0
PDF.js version: pdfjs-2.16.105-legacy-dist  &  pdfjs-2.16.105-dist  both have been tried
Is a browser extension: no
Steps to reproduce the problem:
1. update a word which contains a few tables inside, and then use pdf.js to preview the word.
2. open the system demo in the Edge browser on the mobile phone, then scroll the word file  up and down.
3. it will scroll slower and slower, then even into crash that the UI appears "system no response".
4. when the word doesn't contains any tables, it will work properly, and in the PC, it also work well

What is the expected behavior? (add screenshot)
it can scroll up and down smoothly.
What went wrong? (add screenshot)
it can't scoll well and become slower and slower ,then even into crash that the UI appears "system no response".
[Edge.zip](https://github.com/mozilla/pdf.js/files/9504511/Edge.zip)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [测试文件.zip](https://github.com/mozilla/pdf.js/files/9503301/default.zip)

That archive only contains a `.doc`-file, which makes no sense since the PDF.js library (obviously) only opens PDF documents.
(Also, attaching files directly rather than in archives is a lot simpler to work with.)

> Steps to reproduce the problem:
> 
> update a word which contains a few tables inside, and then use pdf.js to preview the word.
> [...]
> when the word doesn't contains any tables, it will work properly, and in the PC, it also work well

Furthermore, these parts of the STR is really not at all possible to interpret/understand here. Also, if it works in a desktop browser that (again) suggests a bug in the browser/device rather than in the PDF.js library.

For future reference, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

All-in-all, closing as INCOMPLETE given the lack of necessary details.

**Comment by Hooray0617** [comment]
Sorry, I aslo tried the PDF format, the same problem @Snuffleupagus

**Comment by calixteman** [comment]
@Hooray0617, could just attach a pdf file, a screenshot showing what's wrong and another one showing what's expected ?

**Comment by Hooray0617** [comment]
the file is below [testLatest.pdf](https://github.com/mozilla/pdf.js/files/9504641/testLatest.pdf)

the problem is when I use my finger to scroll the pdf up and down , it won’t change pages smoothly and even crash,
![Edge](https://user-images.githubusercontent.com/6283673/188844425-af0639b7-cfcf-42c5-bb69-50a3e0c77c8f.PNG)

What I expected is : When I use my finger to scroll the page up and down, I hope it can change pages smoothly.

@Snuffleupagus

**Comment by Snuffleupagus** [comment]
> the problem is when I use my finger to scroll the pdf up and down , it won’t change pages smoothly and even crash,

As already mentioned, multiple times, that'd indicate a bug in the *browser or OS* and not something that we can fix here.

**Comment by Hooray0617** [comment]
Edge browser has bugs not supported this ?
