### ISSUE TITLE
mobile browser doesn't work properly when the word content contains a few tables inside.

### ISSUE THREAD

**Issue by Hooray0617** [mozilla/pdf.js#15406]
Attach (recommended) or Link to PDF file here:
[测试文件.zip](https://github.com/mozilla/pdf.js/files/9503301/default.zip)

Configuration:
- Web browser and its version: QQ browser of the latest version(13.1.1.1045) on the mobile phone.
- Operating system and its version:  Harmony OS  2.0
- PDF.js version:  pdfjs-2.16.105-legacy-dist
- Is a browser extension: no

Steps to reproduce the problem:
1.  update a word which contains a few tables inside, and then use pdf.js to preview the word.
2. open the system demo in the QQ browser on the mobile phone, then scroll the word up and down.
3. it will scroll slower and slower, then even into crash that the UI appears "system no response".
4. when the word doesn't contains any tables, it will work properly, and in the PC,  it also work well

What is the expected behavior? (add screenshot)
   it can scroll up and down smoothly.
What went wrong? (add screenshot)
  it can't scoll well and become slower and slower ,then even into crash that the UI appears "system no response".
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: QQ browser of the latest version(13.1.1.1045) on the mobile phone.

Sorry, but that browser is *not* supported in the PDF.js project; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> it will scroll slower and slower, then even into crash that the UI appears "system no response".

That also points to a *browser bug*, rather than one found in the PDF.js library.
