### ISSUE TITLE
Firefox Specific - Text highlight not working as expected

### ISSUE THREAD

**Issue by karelee7** [mozilla/pdf.js#15410]
**Attach (recommend or Link to PDF file here):**
[samplepptx.pdf](https://github.com/mozilla/pdf.js/files/9508270/samplepptx.pdf)

**Configuration:**
* Web browser and its version: Firefox, v104.0.2
* Operating system and its version: mac OS Monterey v12.5
* PDF.js version: v2.14.305

**Steps to reproduce the problem:**
Unable to provide steps to reproduce here because it's in a development environment, however below is a detailed explanation of what the problem is:

- When highlighting text and getting the selection via `window.getSelection().toString()`, new line spacing or indentations are missing
- Highlighting the below text results in this incorrect selection (where all the lines are combined into one massive line of text):
`You can print out PPT files as handoutsusing thePRINT >PRINT WHAT > HANDOUTS option`

<img width="543" alt="Screen Shot 2022-08-18 at 5 28 56 PM" src="https://user-images.githubusercontent.com/95440409/188937084-09e27f44-15f0-4494-b429-a14fabe509a4.png">

You can see that the above selection is missing spacing or indentations for where the new line begins. This is causing incorrect outcomes after highlighting text.

**What is the expected behavior?**
The expected behavior is that the selection of text has some kind of indicator of when a new line starts, similar to the spacing that existed in v2.2.228 of PDFjs (i.e. `You can print out PPT files as handouts using the PRINT > PRINT WHAT > HANDOUTS option`)

**What went wrong?** 
In v2.14.305, spacing or indentations for new lines during text selection is missing:

> v2.2.228:

`You can print out PPT files as handouts using the PRINT > PRINT WHAT > HANDOUTS option`

> v2.14.305:

`You can print out PPT files as handoutsusing thePRINT >PRINT WHAT > HANDOUTS option`

**Notes**
This is a newer version of issue https://github.com/mozilla/pdf.js/issues/15331, I added more detail about the problem, included a file, and pinpointed the exact bug that I was seeing. Unfortunately the newest version of PDFjs does not work with our compiler, so I have to use this specific version of PDFjs! 

Is there an alternative to `window.getSelection()` that I need to use? Or is there some other workaround for this issue?

Help is appreciated.

**Comment by Snuffleupagus** [comment]
> PDF.js version: v2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Unable to provide steps to reproduce here because it's in a development environment,

Without a *runnable* example, this isn't really actionable unfortunately.

> When highlighting text and getting the selection via `window.getSelection().toString()`, new line spacing or indentations are missing

WFM, with new-line characters being included in the output, when opening your document with https://mozilla.github.io/pdf.js/web/viewer.html in both Firefox Nightly 106 and Chrome Beta 106.

> Unfortunately the newest version of PDFjs does not work with our compiler, so I have to use this specific version of PDFjs!

Please note that only the very *latest* release is supported, hence you'll have to update to receive help/support.
