### ISSUE TITLE
Error when view file has font .VnArialH

### ISSUE THREAD

**Issue by vienha** [mozilla/pdf.js#15422]
![error_font](https://user-images.githubusercontent.com/41933339/189570148-21168f6f-0576-41ce-86da-f3dcfdc06afa.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since only a screen-shot doesn't make the issue actionable/valid.
