### ISSUE TITLE
Exception when entering in presentation mode in using the keyboard

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15424]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox nightly 
- Operating system and its version: Windows 11 Pro

Steps to reproduce the problem:
1.  Open a pdf
2. hit ctrl+alt+p
3. hit escape
4. hit ctrl+alt+p

I get this output in the console:
```
Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler. [viewer.js:7615:30](resource://pdf.js/web/viewer.js)
switchTool: "null" is an unsupported value. [viewer.js:4280:17](resource://pdf.js/web/viewer.js)
    switchTool resource://pdf.js/web/viewer.js:4280
    addEventListeners resource://pdf.js/web/viewer.js:4314
    dispatch resource://pdf.js/web/viewer.js:4131
    #notifyStateChange resource://pdf.js/web/viewer.js:7682
    request resource://pdf.js/web/viewer.js:7639
    requestPresentationMode resource://pdf.js/web/viewer.js:3000
    webViewerKeyDown resource://pdf.js/web/viewer.js:3816
```

It's likely a matter of focused element when exiting the presentation mode.

**Comment by calixteman** [comment]
When I reload the pdf in using the keyboard (ctrl+shift+r) and then I hit ctrl+alt+p then nothing happen.

**Comment by Snuffleupagus** [comment]
I can't help but wonder if this isn't perhaps a newer browser "feature", where the user cannot activate the Fullscreen API without having first having interacted with the document?

**Comment by calixteman** [comment]
You're very likely right, it's likely a consequence of:
https://hg.mozilla.org/mozilla-central/rev/7dfb03851178
and:
https://developer.mozilla.org/en-US/docs/Glossary/Transient_activation

**Comment by calixteman** [comment]
Since there is no special reason to interact with a pdf document it means that opening a pdf an then directly switching to presentation mode in using the keyboard doesn't work in general.

**Comment by Snuffleupagus** [comment]
Can we do something about this on the PDF Viewer side, and if so do we want to?

Given that extensions can't inject scripts into the built-in PDF Viewer, it *might* perhaps be OK to relax the interaction requirement (assuming that's possible) for code running at `resource://pdf.js/web/viewer.html`!?

**Comment by calixteman** [comment]
Yep it's my idea either. We already have few exceptions for `resource://pdf.js/web/viewer.html` so it'd be one more.

**Comment by calixteman** [comment]
I filed this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1790576
@Snuffleupagus, do you want to fix it ?

**Comment by Snuffleupagus** [comment]
> do you want to fix it ?

Sorry, but I just don't know the platform-code well enough to even tell where to start (and don't have nearly enough time these days to try and figure it out unfortunately).

**Comment by Snuffleupagus** [comment]
Confirmed to be working in the latest Nightly, thank you!
