### ISSUE TITLE
Update `pdfjs-dist/webpack` entrypoint to use `new Worker()` instead of `worker-loader`

### ISSUE THREAD

**Issue by srmagura** [mozilla/pdf.js#15426]
In Webpack 5, the [recommended way](https://webpack.js.org/guides/web-workers/) to create a web worker is

```ts
new Worker(new URL('./worker.js', import.meta.url));
```

Could we update\* the [`pdfjs-dist/webpack` entrypoint](https://github.com/mozilla/pdfjs-dist/blob/master/webpack.js) to use this syntax instead of the legacy `worker-loader`? One of the Webpack contributors told me that `worker-loader` uses "magic" and can cause issues.

\* To maintain compatibility with people still using Webpack 4, we should probably introduce a new entrypoint called `pdfjs-dist/webpack5` (or something like that) rather than changing the existing entrypoint.

Can attempt a PR if you would like.

Closely-related: https://github.com/mozilla/pdf.js/issues/15302

**Comment by Snuffleupagus** [comment]
> To maintain compatibility with people still using Webpack 4, we should probably introduce a new entrypoint called `pdfjs-dist/webpack5` (or something like that) rather than changing the existing entrypoint.

I don't think that we need to worry about older versions, since Webpack 5 was released almost two years ago, and keeping two separate files just increases the maintenance/support burden.
