### ISSUE TITLE
arr.at(i) usage in legacy dist  causing js errors in Safari  v < 15.4

### ISSUE THREAD

**Issue by LucasBourgeois** [mozilla/pdf.js#15437]
Configuration:
- Web browser and its version: Safari version < 15.4
- Operating system and its version: Ios 15
- PDF.js version: Latest
- Ionic App using Safari webkit
- Js code is bundled with Webpack then Babelified.

Steps to reproduce the problem:
1. Import pdf.js (either dist or legacy) and bundle it with webpack. Babel is running on the webpack bundled js file.
2. array.at(-1) are still present as there is no polyfill existing.
3. Js error is thrown : array.at(-1) at is not a function 

What is the expected behavior? (add screenshot)
The package should work in legacy version without experimental / unpolyfilled features. For instance, no ` arr.at(i)` should be present in legacy build

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/18696528/190195779-f5f662c9-b5d2-451a-af8a-0122f7177c7e.png)
![image](https://user-images.githubusercontent.com/18696528/190196257-b75e92ed-4dc5-4481-98d4-a412b196cc95.png)

----

Hi, Im using pdf.js for a Ionic Android & Ios app.
To be able to use es6+ js features, the ios js base code with pdf.js@latest is bundled with webpack & then babelified.
Recently Ive updated pdf.js and find out that `array.at()` is causing js errors. As Safari support `arr.at()` from 15.4 version and as my app is running on older devices. Ive tried to use the legacy build as recommended in the ReadMe for not recent browsers but : 
The legacy build contains `arr.at(i)` and its seems that there is no polyfill in babel for this feature.
I think that `arr.at(-i)` should be replaced with `arr.at(arr.length -1)`.

Thanks

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

Please provide an actual version *number*, since "Latest" isn't really helpful.

> Import pdf.js (either dist or legacy) and bundle it with webpack.

The `legacy`-build of the PDF.js library includes a polyfill for `Array.prototype.at` since version `2.15.349`, hence this should work as-is.

---

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
This also sounds *somewhat* similar to issue #15411, please note https://github.com/mozilla/pdf.js/issues/15411#issuecomment-1240820067 in particular.

**Comment by LucasBourgeois** [comment]
Version is : 2.16.105.
Alright, going to this issue from now

**Comment by Snuffleupagus** [comment]
The point with https://github.com/mozilla/pdf.js/issues/15437#issuecomment-1246990668 was simply to provide additional context (but didn't suggesting commenting there).

Also, screen-shots of code are most useless since they don't provide enough context which is why the following was already referenced above https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

It appears, though it's impossible to tell for sure, that you're trying to use https://github.com/mozilla/pdfjs-dist/tree/master/lib which is *not at all intended* according to the warning in https://github.com/mozilla/pdfjs-dist/blob/master/lib/README.md

Hence, if you actually follow those instructions, you'll be importing from https://github.com/mozilla/pdfjs-dist/tree/master/legacy/build and everything should just work.

**Comment by LucasBourgeois** [comment]
My bad.

Alright :
Im sure that Im using the https://github.com/mozilla/pdfjs-dist/tree/master/legacy/build and not the lib ones as :
I'm importing pdfjs-dist as : `import pdfJs from "pdfjs-dist/legacy/build/pdf.js` (maybe it's where im doing wrong)
Still, idk why, but the legacy build isnt using the array.prototype.at polyfill as i can find occurences of "at(-1)" in the legacy build inside the repo code and inside the bundled file. For exemple : https://github.com/mozilla/pdfjs-dist/blob/cc3d3bf299ae11f8f72ae8d64cbf19b340f9a996/legacy/build/pdf.js#L7871

**Comment by Snuffleupagus** [comment]
> Still, idk why, but the legacy build isnt using the array.prototype.at polyfill as i can find occurences of "at(-1)" in the legacy build inside the repo code and inside the bundled file.

The *entire* point of using a polyfill is to *not* have to replace actual code, but instead provide a fallback implementation when the browser is lacking necessary functionality. Hence the mere existence of `Array.prototype.at` in the code doesn't mean that the polyfill itself isn't working.

For what's now the *third time*, see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by LucasBourgeois** [comment]
@Snuffleupagus Sorry to have annoyed you.
It was in fact an issue about how i was importing the package. I was just importing the pdfJs class and not all the pdf.js file !

My apologies 😄
