### ISSUE TITLE
Wrong apostrophe visualization in pdf

### ISSUE THREAD

**Issue by fousto** [mozilla/pdf.js#15441]
Attach (recommended) or Link to PDF file here:
[document_2013009988776.pdf](https://github.com/mozilla/pdf.js/files/9573225/document_2013009988776.pdf)

Configuration:
- All web browsers
- Windows

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/83006270/190351766-28065667-78c8-4462-ab86-4a9c9255bae8.png)

What went wrong? (add screenshot) - (https://mozilla.github.io/pdf.js/web/viewer.html)
![image](https://user-images.githubusercontent.com/83006270/190351009-8575d767-458e-42c9-b01d-4fec401b2cb6.png)

**Comment by Snuffleupagus** [comment]
> Configuration:
>     * All web browsers
>     * Windows

*For future reference:* Please remember to fill out the "Configuration"-section of the issue template *completely* (e.g. explicitly listing browser names/versions, OS versions, and PDF.js version).

**Comment by stephanrauh** [comment]
Thanks a lot for fixing this bug so quickly! You guys rock!
