### ISSUE TITLE
Broken letters are rendered in text layer

### ISSUE THREAD

**Issue by mnj1004** [mozilla/pdf.js#15448]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Google Chrome v103.0.5060.114 (64-bit)
- Operating system and its version: Windows 10 Enterprise 20H2
- PDF.js version: 3.0.70
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the default sample of pdf.js viewer (compressed.tracemonkey-pldi-09.pdf)
2. Go to page 10 and find Figure 11
3. Drag-select texts in the figure and copy them
4. Paste them to any text editor and see what is copied

What is the expected behavior? (add screenshot)
Texts seen on the pdf viewer should be copied.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/34948107/190625094-3c227eac-503e-49e9-9887-e972316b8cc2.png)

```text
7<>;.?:2/>9<F.A897#3*4$56#
92J25:.-A<#3'4%56#
?>9@AJ.1<?2)'#3%4(56#
?>9@AJ.B<?><#3$4(56#
?>9@AJ.><J/F80-#3$4$56#
?>9@AJ.0A:</C./8-2#3$4%56#
?>9@AJ.D<F@-<>2.@A:0>#3$4,56#
```
Above is copied.

You can also reproduce it on Figure 10 on page 11 and Figure 12 on page 13.

**Comment by calixteman** [comment]
It behaves the same way in Preview, Chrome and Acrobat.
