### ISSUE TITLE
TypeError: attempted to get private field on non-instance

### ISSUE THREAD

**Issue by clinsted** [mozilla/pdf.js#15449]
Attach (recommended) or Link to PDF file here:
(I am using the helloworld pdf from the examples, hard coded in the attached sample)
https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf

Configuration:
- Web browser and its version: Google Chrome, 105.0.5195.102
- Operating system and its version: Windows 10 Enterprise, 21H2
- PDF.js version: Any version after 2.11.338 i.e. it works with 2.11.338 but any of the versions after (version 2.16.105 is the latest @ time of writing).
- Is a browser extension: no

Steps to reproduce the problem: (using the attached sample)
1. npm i
2. npm run serve
3. browse to https://localhost:8080

Note: If the version of pdfjs-dist is down graded to 2.11.338 then no error occurs and the pdf is displayed.

What is the expected behavior? (add screenshot)
Display the pdf without error.

What went wrong? (add screenshot)
the following error occurs: "TypeError: attempted to get private field on non-instance
    at _classExtractFieldDescriptor (index.js:302:1)
    at _classPrivateFieldGet (index.js:302:1)
    at Proxy.getPage (api.js:2924:23)
    at Proxy.getPage (api.js:802:28)
    at App.vue:29:14"

The error is displayed in Google Chrome DevTools Console or VSCode Debug Console.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
na

Attached sample to reproduce the error:
[pdfjs-dist-test.zip](https://github.com/mozilla/pdf.js/files/9583902/pdfjs-dist-test.zip)

The code is contrived and simplistic to demonstrate the error. Referring to the code, App.vue line 27, a copy of the pdf object is created to "simulate" a property passed to a child component. In a real-world vue app the pdf object (and page object) are passed to child components, which causes the error when calling getPage (for example). I do not think this is a bug (in vue or pdfjs) but rather an incompatibility between vue and pdfjs. What I would like is to try get some insight into what has changed after pdfjs-dist version 2.11.338 that causes the error.

**Comment by Snuffleupagus** [comment]
The only suggestion would be to ensure that you're using a `legacy`-build of the PDF.js library, see https://github.com/mozilla/pdfjs-dist/tree/master/legacy if your environment doesn't support the latest JavaScript features.

> I do not think this is a bug (in vue or pdfjs) but rather an incompatibility between vue and pdfjs.

Unfortunately it's simply impossible for us to help with various frameworks, i.e. Vue.js in this case, since we're not actually using them here.

> What I would like is to try get some insight into what has changed after pdfjs-dist version 2.11.338 that causes the error.

Possibly Vue.js doesn't (properly) support some newer JavaScript features, but it's impossible to tell when you've never used the framework in question before.
