### ISSUE TITLE
Pdf streaming not working as expected

### ISSUE THREAD

**Issue by sheikalthaf** [mozilla/pdf.js#15457]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 105.0.5195.125 (Official Build) (arm64)
- Operating system and its version: MacOs latest
- PDF.js version: 2.14
- Is a browser extension: No

Steps to reproduce the problem:
1. Opening linearized pdf with range support in pdfjs viewer
2. You can see that the first request is not within the range

What is the expected behavior? (add screenshot)
I'm using the pdfjs viewer in my application, I wanted the pdf to be stream by 1mb each but the first request is around more than 1mb.

```js
this.pdfLoadingTask = pdfjsLib.getDocument({
      url: url,
      cMapUrl: CMAP_URL,
      cMapPacked: CMAP_PACKED,
      disableStream: false,
      rangeChunkSize: 1024 * 1024
    });
```
What went wrong? (add screenshot)
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/22526247/190921634-8a35b039-263f-461c-9503-3a06df24e524.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> PDF.js version: 2.14

That's not a *complete* version number, and assuming that you actually meant `2.14.305` that version is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I wanted the pdf to be stream by 1mb each but the first request is around more than 1mb.

The `rangeChunkSize` parameter only applies to range-requests (as its name suggests), and doesn't affect streaming which is a slightly different concept. Given that you've left streaming *enabled* it seems that things are probably working as intended here, so you should maybe set `disableStream = true` for your use-case!?

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sheikalthaf** [comment]
@Snuffleupagus updated the comment with attachment and added more details to it.

**Comment by Snuffleupagus** [comment]
As already mentioned in https://github.com/mozilla/pdf.js/issues/15457#issuecomment-1250369604, you're using an *unsupported* version of the PDF.js library.

By default, unless you set `disableStream = true` as also mentioned above, the PDF document will be loaded using *streaming* which means that the entire document is loaded from the initial request (since that will generally lead to the best performance).
It's still possible, depending on the internal "layout" of the PDF document itself (and its size) that some range-requests will be dispatched for data that's not yet been loaded using *streaming*; hence based on the (limited) information provided I'm not entirely sure what the problem is here!?

Also, using a `rangeChunkSize` with a large value (i.e. `1 MB`) will probably hurt rather than help performance in general.

All-in-all, given the information provided, it's again difficult to understand what you perceive to be "wrong" here.
Again, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> But I can see in network tab the first request is downloading more data than the rangeChunkSize.

That behaviour has already been explained, by the second paragraph, in https://github.com/mozilla/pdf.js/issues/15457#issuecomment-1250971554.

> Any way to show pages with minimal downloaded data.

Maybe see https://github.com/mozilla/pdf.js/blob/bf78ccac30e629c3d75d0ba8c1fce65768f7b397/src/display/api.js#L210-L219

---

For everything else, for what's now the *third time*, see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sheikalthaf** [comment]
@Snuffleupagus sorry for the delay response, after `disableStream = true` i can see that the first request not downloading the whole data. But the first page is not visible as soon as some data has been download, for example:

My Pdf file size is 170mb
Pdf is linearized
Server supports range request

When i open the pdf document it is not showing the pdf first after receiving some bytes, It only renders the pdf after it is loading the 165mb. I'm using the pdfjsviewer example [mobile-viewer](https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer)

**Comment by Priestch** [comment]
@sheikalthaf PDF.js tries to avoid requesting too much data when using range request, but some documents send more requests than expected like yours.

 I think it may be related to `await pdfManager.ensureDoc("checkLastPage", [recoveryMode]);` in [loadDocument](https://github.com/mozilla/pdf.js/blob/7404091787440cd67ebd7af4620e3fee438e8ec8/src/core/worker.js#L177).
 
 You can try to comment on that line, there will be fewer requests. But it may not be safe to do that, the code was added to ensure `numPages` is correct as the comment said.
