### ISSUE TITLE
Loading the first page also requires downloading the full pdf file

### ISSUE THREAD

**Issue by anwei-wei** [mozilla/pdf.js#15450]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 105.0.5195.102(64)
- Operating system and its version:Windows 10
- PDF.js version: 3
- Is a browser extension:No

Steps to reproduce the problem:
Steps to reproduce the problem: Normal use, pass the PDF file, just load the first page, also need to download the complete pdf file to render normally,
The strange thing is that there are still 200 206 range download requests when viewing the network request in the browser

![image](https://user-images.githubusercontent.com/70095009/190856790-e8452bc3-b5a9-4547-bd53-965470301a83.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> PDF.js version: 3

Unfortunately that's not a *complete* version number, and thus doesn't really make sense; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem: Normal use, pass the PDF file, just load the first page, also need to download the complete pdf file to render normally,

Depending on the structure of the PDF document, that may *sometimes* be required. However, given the lack of information isn't not really possible to help here.
Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by THausherr** [comment]
@anwei-wei google for "linearized PDF", this explains it. The creator of the PDF is to blame here, not PDF.js.
