### ISSUE TITLE
defect document properties dialog

### ISSUE THREAD

**Issue by TZanke** [mozilla/pdf.js#15475]
Attach (recommended) or Link to PDF file here:
**Any PDF**

Configuration:
- Web browser and its version: ![image](https://user-images.githubusercontent.com/1613368/191247140-8b119e85-970a-4eae-a355-644e881be516.png)
- Operating system and its version: see above
- PDF.js version: 3.0.100 (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: yes?

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. try open document properties

What is the expected behavior? (add screenshot)
**Dialog**

What went wrong? (add screenshot)
**No dialog is opening**
**first click and second:**
![image](https://user-images.githubusercontent.com/1613368/191247023-bb033f25-a107-4552-8aa8-b51e0e5600c4.png)

**Chrome is working**

**Comment by Snuffleupagus** [comment]
> open https://mozilla.github.io/pdf.js/web/viewer.html
> try open document properties

For older browsers you'll need to use a `legacy` build of the PDF.js library, please note the two different links at https://github.com/mozilla/pdf.js#online-demo; hence https://mozilla.github.io/pdf.js/legacy/web/viewer.html should work.

**Comment by TZanke** [comment]
@Snuffleupagus thank you for your quick response. But i am not able to find a documentation when to use the legacy build or not. Firefox 91 felt not old, IE11 does...

https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions

`From version 2.4.456 on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the -legacy-dist.zip suffix).`

I am not able to exactly define `modern` vs. `old`. Should i use the legacy build just to be safe? Who uses the non-legacy version if the customer browser-version is not exactly known? It feels like the default version should never ever be used if client-version is not deployed/administrated by same IT-guy as the pdf.js deployment.

I am a little bit confused and frustrated atm, cause i used the "best choice" available on the download page. Developed a lot of hours, and now i get the information i had to use the `legacy build` for the `newest` LTS / default FF version of Suse 15.3. (https://software.opensuse.org/package/MozillaFirefox)

**Recommendations**

- Add a documentation of the definition of `old` in the context of `pdf.js` (old = not just IE11)
- Add **colored warning** above the downloads, and inform the user: https://mozilla.github.io/pdf.js/getting_started/#download
- _OR:_ Rename the Download. `modern` => `bleeding edge`-browsers and `old` => `default` (most common used browsers)
