### ISSUE TITLE
fetch_stream "fetch" in mobile Safari not work

### ISSUE THREAD

**Issue by cdllqos** [mozilla/pdf.js#15482]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Mobile  Safari
- Operating system and its version: iPhone OS 15_2
- PDF.js version: 2.12.313
- Is a browser extension:

Steps to reproduce the problem:
1. 
```js
PDFFetchStreamReader.getDocument('xxx').promise.then(res => {

})
```
2. throw error
3. 
<img width="692" alt="image" src="https://user-images.githubusercontent.com/25027791/191468272-0399748a-3e68-46ec-9137-b02660f6e002.png">

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
<img width="522" alt="image" src="https://user-images.githubusercontent.com/25027791/191469115-50687ae3-f73c-421d-a3f0-7816baf1d842.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.12.313

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

Unfortunately there's nowhere near enough information provided here to make this an actionable/valid issue, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
