### ISSUE TITLE
why PDFJSDev is undefined? both "gulp generic" and "gulp server"

### ISSUE THREAD

**Issue by CHO-HER** [mozilla/pdf.js#15505]
- PDF.js version: 2.16.105

**Comment by Snuffleupagus** [comment]
Maybe you didn't actually follow https://github.com/mozilla/pdf.js#getting-the-code properly, but it's simply impossible to tell given the complete lack of details here (e.g. there's no steps to reproduce the problem provided).

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
