### ISSUE TITLE
Is it possible to load a pdf document by chunks or one page at a time using pdf.js?

### ISSUE THREAD

**Issue by AGSTRANGER** [mozilla/pdf.js#15506]
I integrated pdf viewer in my app using [pdf.js][1]:  

    import React, { Component } from "react";
    import { connect } from "react-redux";
    import { Container, Row, Col, Button, Input } from "reactstrap";
    import { searchBarStyle } from "../../common/reactSelectStyle";
    
    export class PDFViewer extends Component {
      constructor(props) {
        super(props);
        this.state = {
          pdf: null,
          currentPage: 1,
          zoom: 1,
        };
        this.onZoomInButtonClicked = this.onZoomInButtonClicked.bind(this);
        this.onZoomOutButtonClicked = this.onZoomOutButtonClicked.bind(this);
        this.onPreviousPageButtonClicked =
          this.onPreviousPageButtonClicked.bind(this);
        this.onNextPageButtonClicked = this.onNextPageButtonClicked.bind(this);
        this.onPageNumberEnterPressed = this.onPageNumberEnterPressed.bind(this);
        this.onCurrentPageNumberChanged =
          this.onCurrentPageNumberChanged.bind(this);
      }
      componentDidMount() {
        var pdfjsLib = window["pdfjs-dist/build/pdf"];
        var url = this.props.pdfUrl;
        // var loadingTask = pdfjsLib.getDocument(url);
        var loadingTask = pdfjsLib.getDocument({
          url: url,
          disableAutoFetch: true,
          disableStream: true,
        });
        loadingTask.promise.then((pdf) => {
          this.setState({ pdf });
        });
      }
      onZoomInButtonClicked(e) {
        if (this.state.pdf == null) return;
        this.setState({
          zoom: this.state.zoom + 0.5,
        });
      }
      onZoomOutButtonClicked(e) {
        if (this.state.pdf == null) return;
        this.setState({
          zoom: this.state.zoom - 0.5,
        });
      }
      onPreviousPageButtonClicked(e) {
        if (
          this.state.pdf == null ||
          this.state.currentPage > this.state.pdf._pdfInfo.numPages
        )
          return;
        this.setState({
          currentPage: this.state.currentPage - 1,
        });
      }
      onNextPageButtonClicked(e) {
        if (
          this.state.pdf == null ||
          this.state.currentPage > this.state.pdf._pdfInfo.numPages
        )
          return;
        this.setState({
          currentPage: this.state.currentPage + 1,
        });
      }
      onPageNumberEnterPressed(e) {
        if (this.state.pdf == null) return;
    
        var code = e.keyCode ? e.keyCode : e.which;
    
        if (code == 13) {
          // ON CLICK ENTER GO TO SITE TYPED IN TEXT-BOX
          var desiredPage = document.getElementById("current_page").valueAsNumber;
    
          if (desiredPage >= 1 && desiredPage <= this.state.pdf._pdfInfo.numPages) {
            this.setState({
              currentPage: desiredPage,
            });
          }
        }
      }
      onCurrentPageNumberChanged(e) {
        this.setState({
          currentPage: e.target.value,
        });
      }
      render() {
        if (!!this.state.pdf) {
          this.state.pdf.getPage(this.state.currentPage).then((page) => {
            var canvas = document.getElementById("pdf_renderer");
            var ctx = canvas.getContext("2d");
    
            var viewport = page.getViewport(this.state.zoom);
    
            canvas.width = viewport.width;
            canvas.height = viewport.height;
    
            page.render({
              canvasContext: ctx,
              viewport: viewport,
            });
          });
        }
    
        return (
          <Container>
            <Row>
              <Col>
                <div id="canvas_container" className="canvas-container">
                  <canvas id="pdf_renderer"> </canvas>
                </div>
              </Col>
            </Row>
            <br />
            <Row className="justify-content-center">
              <Col className="text-center">
                <Button
                  className="pdf-toolbar-button btn-round btn btn-outline-default display-inline"
                  id="previous"
                  onClick={this.onPreviousPageButtonClicked}
                >
                  {"<"}
                </Button>
                <Input
                  className="pdf-input display-inline"
                  style={{
                    ...searchBarStyle,
                    maxWidth: "200px",
                  }}
                  id="current_page"
                  value={this.state.currentPage}
                  onChange={this.onCurrentPageNumberChanged}
                  type="number"
                  onKeyPress={this.onPageNumberEnterPressed}
                />
                <Button
                  className="pdf-toolbar-button btn-round btn btn-outline-default display-inline"
                  id="next"
                  onClick={this.onNextPageButtonClicked}
                >
                  {">"}
                </Button>
              </Col>
            </Row>
            <br />
            <Row className="justify-content-center">
              <Col className="text-center">
                <Button
                  className="pdf-toolbar-button btn-round btn btn-outline-default display-inline"
                  id="zoom_out"
                  onClick={this.onZoomOutButtonClicked}
                >
                  -
                </Button>
                <Button
                  className="pdf-toolbar-button btn-round btn btn-outline-default display-inline"
                  id="zoom_in"
                  onClick={this.onZoomInButtonClicked}
                >
                  +
                </Button>
              </Col>
            </Row>
            <br />
          </Container>
        );
      }
    }
    
    const mapStateToProps = (state) => ({});
    
    const mapDispatchToProps = {};
    
    export default connect(mapStateToProps, mapDispatchToProps)(PDFViewer);

This works perfectly fine.  
The problem is that files that are a bit large. Take some time to load.   
So I am wondering if it's possible to load the pdf one chunk at a time, or one page at a time.  
I tried this:

    // var loadingTask = pdfjsLib.getDocument(url);
    var loadingTask = pdfjsLib.getDocument({
      url: url,
      disableAutoFetch: true,
      disableStream: true,
    });

But, it doesn't seem to have any effect.  

  [1]: https://mozilla.github.io/pdf.js/examples/

**Comment by Snuffleupagus** [comment]
> I tried this:
> ```
> // var loadingTask = pdfjsLib.getDocument(url);
> var loadingTask = pdfjsLib.getDocument({
>   url: url,
>   disableAutoFetch: true,
>   disableStream: true,
> });
> ```

That looks generally correct, however in order for that to work the server needs to support range-requests *and* the PDF document itself also needs to be (internally) structured such that it can actually take advantage of this (i.e. it should be linearized).

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable/valid.

Furthermore, we cannot support "React" here (since we don't use it), and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
