### ISSUE TITLE
how delete annotations with a button onclick

### ISSUE THREAD

**Issue by jesesqui** [mozilla/pdf.js#15519]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: safari
- Operating system and its version: iOS 15.5
- PDF.js version: 3.0.66
- Is a browser extension:

Steps to reproduce the problem:

I´m opening the visor in iPad and works well, but I can´t  to delete annotations, so, I would like to add a Button with the  function for delete annotation selected

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.0.66

That version is not an official release, and it's also not the latest `master` version (as of this writing); please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> [...] but I can´t to delete annotations,

It's not at all clear *exactly* what sort of annotation you're referring to here!
 - If you're referring to annotations you've manually added, using the still not officially released annotation-editor of the upcoming PDF.js `3`-release, then using the <kbd>Delete</kbd> button will remove the annotation.
 - If you mean deleting arbitrary, in the PDF document already existing, annotations then that's already tracked in issue #15403.

**Comment by jesesqui** [comment]
_...then using the Delete button will remove the annotation._

with the keyboard works fine, but i would like have a button something like this: 
 <button id="delete" class="toolbarButton"  onClick="delete()">Delete Selected</button>

**Comment by ReturnToTheYouth** [comment]
After reading your comments, I did not see any relevant APIs. May I know which API can delete annotations?

**Comment by unhandyandy** [comment]
Yes, an eraser tool independent of the keyboard is a necessity when using a 2-in-1 in notebook mode.
