### ISSUE TITLE
Text content not visible in PDF document

### ISSUE THREAD

**Issue by gmahesh2022** [mozilla/pdf.js#15513]
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: Mozilla Firefox, v104.0.2
- Operating system and its version: Microsoft Windows 10, 21H2
- PDF.js version: 2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
1. When loaded in the viewer, the viewer does not render any text. 
2. In browser console, an error message "_invalid font name"_ is logged.

What is the expected behavior? (add screenshot): The PDF is rendered completely, with all text and other content.

What went wrong? (add screenshot) Only shapes are visible, no text is rendered. The PDF loads fine in Google Chrome browser and Adobe Acrobat reader.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that this part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.
