### ISSUE TITLE
Formatting and validation not working as expected

### ISSUE THREAD

**Issue by MallRoy** [mozilla/pdf.js#15523]
Link to PDF file here:
[3c4347e5-f117-48af-9349-43e9f72ea811.pdf](https://github.com/mozilla/pdf.js/files/9671936/3c4347e5-f117-48af-9349-43e9f72ea811.pdf)

Configuration:
- Web browser and its version: Chrome 105.0.5195.127 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 3.0.142
- Is a browser extension: No

Steps to reproduce the problem:
1.  Load the pdf and type the ABN value.
2.  formatting and invalid value alert is not thrown

What is the expected behavior?
![image](https://user-images.githubusercontent.com/54269166/192963031-c716ae6f-e41d-43bd-b7e1-f69a3fc42c17.png)

What went wrong?
![image](https://user-images.githubusercontent.com/54269166/192962673-7012bf27-2420-4013-89ed-dfe8eb1bee79.png)
![image](https://user-images.githubusercontent.com/54269166/192962889-3e5ba004-dbe9-4201-b35c-b6b96edf69ea.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by MallRoy** [comment]
In console reference error is thrown from the scripting manager
![image](https://user-images.githubusercontent.com/54269166/192963924-a1a654af-acfb-40e7-b539-0c81726f1ed3.png)

**Comment by calixteman** [comment]
I didn't find any documentation about `AFExactMatch` but if I understand correctly how it's used, it should take 2 arguments: an array of regex and a string. And I guess that if at least one of the regex is exactly matching the string then it returns true else false.

**Comment by Snuffleupagus** [comment]
It's really annoying that Adobe-software is using completely unofficial/undocumented scripting features like this :-(

Searching through GitHub seem to bring up a number of (identical?) implementations that could probably serve as help/inspiration here: https://github.com/search?q=AFExactMatch&type=code

**Comment by MallRoy** [comment]
![image](https://user-images.githubusercontent.com/54269166/193189593-dad2bd30-1f82-4063-ae91-8bd19ba27380.png)
On page 4 if we type two letters in **State/territory it prints undefined**. If the validation is not satisfied.
