### ISSUE TITLE
PDF document outline (table of contents) should be collapsed by default

### ISSUE THREAD

**Issue by sadaaithal** [mozilla/pdf.js#15526]
Attach (recommended) or Link to PDF file here: https://docs.informatica.com/content/dam/source/GUID-5/GUID-57ABF62F-CE24-446C-8BE9-4F23B6940A41/52/en/IN_1052_CommandReference_en.pdf

Configuration:
- Web browser and its version: Firefox, 105.0.1 (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: UNK
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF
2. Check the document outline - it is expanded

What is the expected behavior? (add screenshot)
It is preferrable that the document outline comes collapsed by default. 
Double-click should expand the Table of contents (TOC )

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, since the outline does load with the entries collapsed, in PDF.js `3.0.120` as built-in to Firefox Nightly 107:

![outline](https://user-images.githubusercontent.com/2692120/193151632-6c60ef61-6860-4f9d-921b-26b46d8af7e7.png)
