### ISSUE TITLE
If validation fails, undefined value is printed in the form

### ISSUE THREAD

**Issue by MallRoy** [mozilla/pdf.js#15529]
Link to PDF file here:
[3c4347e5-f117-48af-9349-43e9f72ea811.pdf](https://github.com/mozilla/pdf.js/files/9671936/3c4347e5-f117-48af-9349-43e9f72ea811.pdf)

Configuration:

Web browser and its version: Chrome 105.0.5195.127 (Official Build) (64-bit)
Operating system and its version: Windows 10
PDF.js version: 3.0.142
Is a browser extension: No
Steps to reproduce the problem:
Load the pdf and type the State/territory value with two letters like (WA)
It prints undefined. If the validation is not satisfied.
![image](https://user-images.githubusercontent.com/54269166/193221822-369d1fea-7f9a-428d-a166-59a30f74cfef.png)

What is the expected behavior?
![image](https://user-images.githubusercontent.com/54269166/193221594-be8fdd82-0256-4adc-babc-9dfa740af450.png)

**Comment by calixteman** [comment]
The `undefined` are because `RegExp.$i` aren't implemented in quickjs:
https://github.com/bellard/quickjs/issues/134

It should work correctly in Firefox built-in viewer (once we'll make an update).

**Comment by Snuffleupagus** [comment]
> The `undefined` are because `RegExp.$i` aren't implemented in quickjs: [bellard/quickjs#134](https://github.com/bellard/quickjs/issues/134)
> 
> It should work correctly in Firefox built-in viewer (once we'll make an update).

Given that it now works in the *built-in* Firefox PDF Viewer in Firefox Nightly, which uses PDF.js version `3.0.200`, I don't believe that there's much more that we can do here unfortunately.
