### ISSUE TITLE
Need clarity in Wiki regarding using Viewer options along with file URL

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#15535]
[Wiki](https://github.com/mozilla/pdf.js/wiki/Viewer-options) has example usage of both `#options` and `?file` option. It also says:

> file: the path of the PDF file to use ... Please notice that the path/URL must be encoded using encodeURIComponent

However there is no example of combining both; it seems like the Fragment Identifier should not be URI-encoded when used along with `file=`.
E.g: `/viewer.html?file=%2Fpdf.js%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf#page=2`

I only found this out now. Sorry if was supposed to be obvious, but adding an example can still help.

**Comment by Snuffleupagus** [comment]
> However there is no example of combining both;

But that's just standard URL behaviour, and not really anything unique to the *GENERIC* PDF.js viewer, regarding the combined use of [search](https://developer.mozilla.org/en-US/docs/Web/API/URL/search) and [hash](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash) in a URL.

> it seems like the Fragment Identifier should not be URI-encoded when used along with `file=`.

Given that only the `?file`-section mentions encoding, it could/should thus only be assumed to apply to the search-part of the URL.

**Comment by shivaprsd** [comment]
In my use case, the `file` parameter is itself an absolute URL (using CORS). That is why the confusion arose, whether the hash should belong to the `file` URL or the viewer's URL.
