### ISSUE TITLE
there is wrong position of highlight when scale less than 100%,

### ISSUE THREAD

**Issue by CHO-HER** [mozilla/pdf.js#15531]
Attach (recommended) or Link to PDF file here: [https://mozilla.github.io/pdf.js/web/viewer.html#page=1&zoom=80,-594,801](https://mozilla.github.io/pdf.js/web/viewer.html#page=1&zoom=80,-594,801)

Configuration:
- Web browser and its version: chrome 92.0.4515.107
- Operating system and its version: windows10 LTSC 1809
- PDF.js version: the lastest
- Is a browser extension:

Steps to reproduce the problem:
1. set scaleValue less than 100%
2. find anything

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/44517088/193242115-352932c0-a27b-452a-be44-e5eaf5515dc1.png)
What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/44517088/193242171-fa7ae9b9-6e60-4059-b6b6-f55a2473e879.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using both Firefox Nightly 107 and Google Chrome Beta 107 on Windows.

> Web browser and its version: chrome 92.0.4515.107

Please try this using an up-to-date version of Google Chrome, since your browser is over a year old.
