### ISSUE TITLE
Screen Stopping Error in iOS 16.0.2 Version

### ISSUE THREAD

**Issue by leekiback** [mozilla/pdf.js#15543]
Attach (recommended) or Link to PDF file here:
https://i.imgur.com/TGQreUQ.jpg (Safari )
https://i.imgur.com/y0G6fqH.jpg (Chrome)

Configuration:
- Web browser and its version: Safari 16, Chrome 106.0.5249.92
- Operating system and its version: IOS16.0.2
- PDF.js version: Error in demo version as well
- Is a browser extension: Disable browser extensions

Steps to reproduce the problem:
1. Click the demo URL (https://mozilla.github.io/pdf.js/web/viewer.html)
2. scroll down to scroll down
3. The screen stops intermittently.

What is the expected behavior? (add screenshot)
Isn't there an error in the data rendering process?

What went wrong? (add screenshot)
I'm trying to figure it out.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari 16, Chrome 106.0.5249.92
> Operating system and its version: IOS16.0.2
> [...]
> The screen stops intermittently.

This unfortunately suggests a bug in the OS itself given that it's broken in multiple browser on the same platform (especially since it's apparently intermittent), rather than a bug in the PDF.js library,
Hence this most unfortunately doesn't look fixable here, and please also note that iOS isn't the focus of development.

**Comment by ShawnYou1** [comment]
I have the same problem with iPadOS 16.x or 16.0.x.

**Comment by developerdino** [comment]
Same issue in iOS 16.1.

**Comment by ShawnYou1** [comment]
> This unfortunately suggests a bug in the OS itself given that it's broken in multiple browsers on the same platform (especially since it's apparently intermittent), rather than a bug in the PDF.js library,
> Hence this most unfortunately doesn't look fixable here, and please also note that iOS isn't the focus of development.

Hi, please tell me how did you solve it.

**Comment by ShawnYou1** [comment]
> > Web browser and its version: Safari 16, Chrome 106.0.5249.92
> > Operating system and its version: IOS16.0.2
> > [...]
> > The screen stops intermittently.
> 
> This unfortunately suggests a bug in the OS itself given that it's broken in multiple browsers on the same platform (especially since it's apparently intermittent), rather than a bug in the PDF.js library, Hence this most unfortunately doesn't look fixable here, and please also note that iOS isn't the focus of development.



> > Web browser and its version: Safari 16, Chrome 106.0.5249.92
> > Operating system and its version: IOS16.0.2
> > [...]
> > The screen stops intermittently.
> 
> This unfortunately suggests a bug in the OS itself given that it's broken in multiple browsers on the same platform (especially since it's apparently intermittent), rather than a bug in the PDF.js library, Hence this most unfortunately doesn't look fixable here, and please also note that iOS isn't the focus of development.

Hi, do you know whether the Safari team will fix it?

**Comment by Undyneund** [comment]
Hi, I am also having the same problem, can you share with me your solution.
