### ISSUE TITLE
Zooming does not preserve location when CSS filter is applied

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#15544]
Attach (recommended) or Link to PDF file here: Any

Configuration:
- Web browser and its version: Firefox 105.0.1
- Operating system and its version: macOS 11.6
- PDF.js version: 2.16.105
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open any PDF in the default viewer (built-in / online demo / custom hosted).
2. Apply a CSS filter (e.g. `fliter: invert()`) to the `<div class="pdfViewer">` element via browser dev tools.
3. Zoom in on the document beyond ~110%.

What is the expected behavior? (add screenshot)
The top left corner of current view is preserved while zooming.
![no-filter](https://user-images.githubusercontent.com/18247990/194511016-1065805d-cc6f-45fa-8878-32ab1f1fd154.gif)

What went wrong? (add screenshot)
The top is not preserved, resulting in a jump.
![with-filter](https://user-images.githubusercontent.com/18247990/194511035-bd6c6f1e-92d5-4229-9bff-ff3ed9a43e72.gif)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

This seems a strange issue, and I am not sure whether to post this here, as the unpatched viewer itself works fine. But inverting is a necessary feature of my [custom deployment](https://addons.mozilla.org/addon/doqment), and as it affects any deployment of the generic viewer, I thought better to post it here.

I don't understand why applying a simple CSS filter should affect zooming. Even more strangely, this issue disappears if the filter is applied to the `#viewerContainer` element instead.

P.S. This happens only in Firefox. Could not reproduce in WebKit (Safari 15.4).

**Comment by Snuffleupagus** [comment]
> [...] as the unpatched viewer itself works fine. But inverting is a necessary feature of my [custom deployment](https://addons.mozilla.org/addon/doqment),

We cannot really support *custom* modifications of the viewer, so that means that it's not really an actionable/valid issue here unfortunately.

> Even more strangely, this issue disappears if the filter is applied to the `#viewerContainer` element instead.

That'd also possibly suggest a *browser* issue, rather than a PDF.js one.
