### ISSUE TITLE
LoadingBar indeterminate loadingBar.div replacement?

### ISSUE THREAD

**Issue by KoalaBear84** [mozilla/pdf.js#15540]
Attach (recommended) or Link to PDF file here:
Independent of PDFs

Configuration:
- PDF.js version:
v.2.16.105

Steps to reproduce the problem:
1. We load a webservice generated PDF through the 'official' `web/viewer.html`
2. Because it is webservice generated it doesn't have a Content-Length. The loading does NOT depend on the size of the result PF, but on the generation time. That's why we want to show the indeterminate progress.
3. We add the indeterminate class to show the indeterminate progress, because there is no progress in the meantime

Maybe it's a bit related to https://github.com/mozilla/pdf.js/issues/9446 ?

```html
<iframe class="embed-responsive-item" id="document-viewer-frame" src="" allowfullscreen="true"></iframe>
```

Previous working code
```JavaScript
pdfViewApplication.loadingBar.div.classList.add('indeterminate');
```

But now that loadingBar.div isn't available anymore we need a more complex / clumsy way:

```JavaScript
document.querySelector('#document-viewer-frame').addEventListener('load', (event) => {
	let frameContentWindow = event.target.contentWindow;

	let pdfViewApplication = frameContentWindow.PDFViewerApplication;
	
	// Firefox loads empty iframe on first load
	if (pdfViewApplication) {
		pdfViewApplication.loadingBar.show();
		// This line now works, but it clumsy
		pdfViewApplication.appConfig.toolbar.container.parentElement.querySelector('#loadingBar').classList.add('indeterminate');
	}
});

$('#document-viewer-frame').attr('src', '/pdfjs/web/viewer.html?file=' + encodeURIComponent('webservice-that-is-generating-the-pdf.pdf'));
```

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/5886900/194352024-cd50e93c-1908-4adb-bc72-a309999ed148.png)

What went wrong? (add screenshot)
A good way to show indeterminate when the progress is not yet available. So always show indeterminate automatically when it's generating, and/or when there is no Content-Length.
By default there is no loadingbar when the progress is indeterminate?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
It's internal website. Example code is available above.

**Comment by Snuffleupagus** [comment]
> But now that loadingBar.div isn't available anymore we need a more complex / clumsy way:

The way that the viewer normally triggers the `indeterminate` loadingBar is by doing `PDFViewerApplication.loadingBar.percent = NaN;` so that's possibly what you want here.

However, please keep in mind that *manually* showing/setting the loadingBar isn't really intended and thus not something that's "officially" supported here.

**Comment by KoalaBear84** [comment]
Thank you very much @Snuffleupagus! It is working as intended 👍
