### ISSUE TITLE
recent commit makes some PDF files with forms appear blank

### ISSUE THREAD

**Issue by plorb** [mozilla/pdf.js#15557]
Attach (recommended) or Link to PDF file here:
[checkbox-incomplete-appearance.pdf](https://github.com/mozilla/pdf.js/files/9743656/checkbox-incomplete-appearance.pdf)

Configuration:
- Web browser and its version: Firefox 105.0.1
- Operating system and its version: Windows and Linux
- PDF.js version: all since commit 0c31320c12d6375a914683853eaa29765806ba85

Steps to reproduce the problem:
Open a PDF with a checkbox annotation that doesn't completely specify the appearance.

What is the expected behavior?
Text and other content is visible.  In this example, "Check Box" should be visible.

What went wrong?
The page appears blank except for the form entry boxes.

Commit 0c31320c12d6375a914683853eaa29765806ba85 entered the Firefox release recently and broke an old PDF form.  The form has some checkbox appearance issue that causes appearance .dict vars to not be set and throw an exception when pdf.js tries to use them. I created a smaller file with the same issue.  Previously the PDF displayed properly anyway.   This commit changed the data structure returned by the annotation getOperatorList but missed a null return in a catch block for opListPromises.  The null value isn't tolerated anymore.  This can be fixed by returning the empty list structure instead of null.  Then the PDF works again.

**Comment by marco-c** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1794351 to track the regression on Bugzilla.
