### ISSUE TITLE
PDF rendering error on a page that has been rotated

### ISSUE THREAD

**Issue by Tristan-2i** [mozilla/pdf.js#15560]
Attach (recommended) or Link to PDF file here:
[3-4-5.pdf](https://github.com/mozilla/pdf.js/files/9749518/3-4-5.pdf)

Configuration:
- Web browser and its version: Chrome 106.0.5249.103 (Build officiel) (64 bits)
- Operating system and its version: Windows 10 Famille 21H2
- PDF.js version: 2.3.164
- Is a browser extension:

Steps to reproduce the problem:
1. Rotate a pdf page and save it (edited with foxit)
2. Open the pdf with an other pdf reader, it's ok
3. Open the pdf with PDF viewer (PDF.js), it is rotated and distorted

What is the expected behavior? (add screenshot)
Without browser extension :
![image](https://user-images.githubusercontent.com/78900902/194960337-98ac9c59-f9a5-4796-b3fe-db9218478332.png)

What went wrong? (add screenshot)
With browser extension :
![image](https://user-images.githubusercontent.com/78900902/194960381-2e2702a0-2678-4a56-9b5d-3161f19d95cf.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `3.0.120` in Firefox Nightly 107.

> PDF.js version: 2.3.164

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by Tristan-2i** [comment]
> WFM, using PDF.js version `3.0.120` in Firefox Nightly 107.
> 
> > PDF.js version: 2.3.164
> 
> That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

I have the last version of chrome store
I'm sorry but how to install it on windows ?
Is it only for chromium on linux ?
