### ISSUE TITLE
Strange looking page

### ISSUE THREAD

**Issue by TZanke** [mozilla/pdf.js#15573]
Attach (recommended) or Link to PDF file here:
[EINZELDRUCK (10)-1_1b-000001.pdf](https://github.com/mozilla/pdf.js/files/9783567/EINZELDRUCK.10.-1_1b-000001.pdf)

Configuration:
- Web browser and its version: Chrome 106.0.5249.119 (Offizieller Build) (64-Bit)
- Operating system and its version: openSUSE Leap 15.3
- PDF.js version: PDF.js: 3.0.206 (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: Same issue with integrated pdf.js (Firefox 102.3.0esr (64-Bit))

Steps to reproduce the problem:
1. open attached file
2. have a look at the fonts

What is the expected behavior? (add screenshot)
**(Chrome Viewer)**
![image](https://user-images.githubusercontent.com/1613368/195790499-5706f891-2c78-4f80-b5be-58e34b3b6030.png)

What went wrong? (add screenshot)
**There is a lot of stretched/shrinked Text, glitches everywhere. Also the complete page looks blured.** 
![image](https://user-images.githubusercontent.com/1613368/195790578-5dc8b801-f9a7-4296-8084-62eb57962d37.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by calixteman** [comment]
About the rendering, it's a regression from:
https://github.com/mozilla/pdf.js/pull/14777
There is a cache issue, if I set `cachedImage` to `null`:
https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L1383
then it works.
Maybe there is something wrong with the `mainKey`.

**Comment by marco-c** [comment]
@calixteman could you file a mirror issue on Bugzilla so we can track the regression and set Regressed By?

**Comment by calixteman** [comment]
This pdf is mainly composed of images (the rendering problem is because  an image issue).
Most of them are used with some pattern fill which some performance issues.
