### ISSUE TITLE
Error in console in text_layer.js when opening non-standard pdf

### ISSUE THREAD

**Issue by mihafreenode** [mozilla/pdf.js#15584]
Attach (recommended) or Link to PDF file here:
[22DE80483 (1).pdf](https://github.com/mozilla/pdf.js/files/9800491/22DE80483.1.pdf)

Validator says among other things: "The font is not embedded."

Configuration:
- PDF.js version: 2.9.359

Steps to reproduce the problem:
1. Attached pdf has some validation problem (fonts not embedded)
2. Error in console and don't get text layer rendered event - although pdf is visible in browser.

What is the expected behavior? (add screenshot)
When pdf page is shown, we need event to fire
What went wrong? (add screenshot)
Exception in console and no event, although pdf is visible in browser
![image](https://user-images.githubusercontent.com/10048109/196177542-44370c29-330a-4c33-b8c2-6344f25051fa.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.0.200 [348665934] in Firefox Nightly 107.

> Configuration:

Most of the requested information is missing here.

> PDF.js version: 2.9.359

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by mihafreenode** [comment]
Well could you please open the attached PDF in current version and tell me it is all fixed now? Bots...
![image](https://user-images.githubusercontent.com/10048109/196179584-ae7fed5e-9053-4f71-93e7-43dc6c5ac8ae.png)
