### ISSUE TITLE
Problem with umlauts

### ISSUE THREAD

**Issue by Faelean** [mozilla/pdf.js#15594]
Attach (recommended) or Link to PDF file here:

[z_Beilage zu RE 22055.pdf](https://github.com/mozilla/pdf.js/files/9821160/z_Beilage.zu.RE.22055.pdf)

Configuration:
- Web browser and its version: Firefox Developer Version 107.0b2 (64-Bit)
- Operating system and its version: Windows 10 (21H2)
- PDF.js version: 2.10.377, also tested with the online Demo, 3.0.233 [cc450b405]
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached pdf

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/7944797/196714986-0a08a4ef-5cce-4ad7-b496-d90fd2cbe37a.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/7944797/196715101-d6e5cdb6-d73d-4417-b473-0127d5d33a9c.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.10.377,

*For future reference:* Please note that only the versions listed at https://mozilla.github.io/pdf.js/getting_started/#download are supported.
