### ISSUE TITLE
【Compatibility】it is not work in mobile browsers

### ISSUE THREAD

**Issue by JaneYork** [mozilla/pdf.js#15609]
Attach (recommended) or Link to PDF file here:

it is not work in mobile browsers，but is work in PC browser.

Configuration:
- Web browser and its version:Chrome mobile browser last version，UC mobile browser
- Operating system and its version:Android phone android 12
- PDF.js version:pdfjs-2.16.105-legacy-dist
- Is a browser extension:

Steps to reproduce the problem:
1. Modern browsers: https://mozilla.github.io/pdf.js/web/viewer.html
Older browsers: https://mozilla.github.io/pdf.js/legacy/web/viewer.html。
2. use  pdf.js-legacy version，it not work in chrome mobile brower，use the PDF.js(Modern browsers version) it not work in wechat.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/29787967/197181282-d2099f30-7938-40e8-9e1a-7420f0d09ee7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
