### ISSUE TITLE
Blank page displayed for the pdf document.  FormatError in GetOperatorList()

### ISSUE THREAD

**Issue by rpatnani** [mozilla/pdf.js#15604]
Attach (recommended) or Link to PDF file here: 
File is attached by the customer in the comments section.

Configuration:
- Web browser and its version:
All browsers(latest versions). Some of the browsers which we tried:
Google Chrome Version 106.0.5249.119
Firefox Version 106.0
	
- Operating system and its version:
Windows but not limited to any OS.
	
- PDF.js version: 2.16.105

- Is a browser extension: No

Steps to reproduce the problem:
1.  Open pdf.js viewer.
2. Click "Open File" button and load the sample document

What is the expected behavior? (add screenshot)
Document should be loaded properly with its contents visible.
Open the same pdf document with Chrome or Edge Or Adobe acrobat reader. Document contents are is properly visible.

What went wrong? (add screenshot)
Blank screen is displayed when the pdf document is opened in pdf.js viewer.

Additional Note:
Errors in the browser console says:

```
app.js:1566 PDF 89d7f33e104f0ecc79eaa525e15c34ee [1.4 iTextSharp™ 5.5.1 ©2000-2014 iText Group NV (AGPL-version) / -] (PDF.js: 2.16.105)
util.js:425 Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "FormatError: Invalid number:   (charCode 32)".
util.js:425 Warning: getTextContent - ignoring errors during "GetTextContent: page 0" task: "FormatError: Invalid number:   (charCode 32)".
```

**Comment by dhalale** [comment]
[SP_Page1.pdf](https://github.com/mozilla/pdf.js/files/9832017/SP_Page1.pdf)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> File is attached by the customer in the comments section.

*For future reference:* Please respect peoples time, since this is an open-source project that you're able to use for free (and where many of us are *unpaid* volunteers), by waiting until you've gathered *all* of the required information *before* opening an issue!
