### ISSUE TITLE
Save and print loops in PDF viewer with JS in PDF.

### ISSUE THREAD

**Issue by 1Jesper1** [mozilla/pdf.js#15614]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Versie 106.0.5249.119 (Officiële build) (64-bits)
- Operating system and its version: Windows 11
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1.  Use a pdf with this javascript in it: /JS (app.setInterval('app.execMenuItem("SaveAs")', 1000);)
2.  Use a pdf with this javascript in it: /JS (app.setInterval('print()', 100);)
3.  Use a pdf with this javascript in it:  /JS (app.setInterval('app.alert("123")', 1);)

File 1. [test.pdf](https://github.com/mozilla/pdf.js/files/9852207/test.pdf)
File 2. [test.pdf](https://github.com/mozilla/pdf.js/files/9852212/test.pdf)
File 3. [test.pdf](https://github.com/mozilla/pdf.js/files/9853150/test.pdf)

Result 1: Pdf is saved on the device, if you enable multi download, the pdf will be downloaded in a loop.
Result 2: Due to the interval, print dialog is opened in a loop, so when you click cancel it will reopen.
Result 3: Alert will show in a loop,

**Comment by Snuffleupagus** [comment]
The "Attach (recommended) or Link to PDF file here:"-part of the ISSUE_TEMPLATE is required in order for any issue to be actionable/valid, and please always fill out the ISSUE_TEMPLATE with *all* of the requested information requested.

**Comment by calixteman** [comment]
Those kind of actions (`print`, `alert`, ...) should be triggered only after a user activation.
Adding a check for a user activation will at least help to break the loop and then let the user decide to leave the pdf without being annoyed by a modal.

**Comment by calixteman** [comment]
For the 1st one, you just have to wait few seconds and then cancel the print, to get rid of the print call.
