### ISSUE TITLE
[Feature Request] Any Method to Set Default Scale Mode and Scroll Mode?

### ISSUE THREAD

**Issue by QS0x01** [mozilla/pdf.js#15619]
Configuration:
- Web browser and its version: Firefox Latest
- Operating system and its version: Windows 11 21H2

Steps to reproduce the problem:
Currently, I try to set scale mode and scroll mode of the pdf viewer by a js (It indeed works in console of F12)
```  
scrollHorizontal.click();
scaleSelect.value="page-fit";
scaleSelect.dispatchEvent(new Event('change'));
```
Unfortunately, after experiment and searching I found that TamperMonkey can not work in pdf.js.
[https://bugzilla.mozilla.org/show_bug.cgi?id=1454760](https://bugzilla.mozilla.org/show_bug.cgi?id=1454760)

What is the expected behavior? 
I wish there could be a method to set default view mode so that I do not need to click 4 times each time I open a PDF file in Firefox.
( My work needs to read lots of PDFs.

**Comment by QS0x01** [comment]
I just found a method. Record to help others who may meet the same problem like me.

Step.1. open "about:config" by Firefox address bar.
Step.2. Set "pdfjs.defaultZoomValue" to "page-fit".
Step.3. Set "pdfjs.scrollModeOnLoad" to to "1".
Step.4. Save and restart the browser. Enjoy it!

Refer: https://support.mozilla.org/en-US/questions/1074524

**Comment by Snuffleupagus** [comment]
Closing as solved, since https://github.com/mozilla/pdf.js/issues/15619#issuecomment-1289904557 describes the correct/intended way to do this.
