### ISSUE TITLE
[Bug]Some chars on chrome (windows) are rendered wrong but correct on chrome (mac).

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#15620]
Attach (recommended) or Link to PDF file here:
https://pdf.cdn.readpaper.com/arxivPdf/1206.5141.pdf

Configuration:
- Web browser and its version: 
Chrome Version 106.0.5249.119 (Official Build) (64-bit)
- Operating system and its version: 

版本	Windows 10 家庭中文版
版本号	21H2
安装日期	‎2021/‎5/‎8
操作系统内部版本	19044.2130
体验	Windows Feature Experience Pack 120.2212.4180.0

- PDF.js version:
v2.16.105

- Is a browser extension:
no

Steps to reproduce the problem:
Render the pdf on windows chrome. The char `u` is rendered as `oc` on Page 3.
p.s. Same code and pdf  on the mac chrome are rendered correctly.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/9332442/197676351-324d3bdd-d022-4391-bd69-92062dadc00e.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/9332442/197675963-24b8caff-345e-4b51-8ef3-17361b5e7737.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> 版本 Windows 10 家庭中文版
> 版本号 21H2
> 安装日期 ‎2021/‎5/‎8
> 操作系统内部版本 19044.2130
> 体验 Windows Feature Experience Pack 120.2212.4180.0

You need to use *only* English in this bug-tracker, since otherwise we cannot help you!

---

> Render the pdf on windows chrome. The char `u` is rendered as `oc` on Page 3.

WFM, using PDF.js: 3.0.239 [ba3a0e104] in *both* Firefox Nightly 108 and Google Chrome Beta 107 on Windows.

**Comment by Sara2009** [comment]
@Snuffleupagus My apology to write un-English words. But the issue still exists after using PDF.js 3.0.239.

Operating system and its version:  Windows 10 Home 21H2 (19044.2130).

I fork this repo to https://github.com/Sara2009/pdf.js. I found loading the PDF with pdfjs-dist@3.0.239 in node_modules is not correct. Here is the different:

1. clone my repo https://github.com/Sara2009/pdf.js
2. `npm install --force` I add the pdfjs-dist to dependencies.
3. `npm run dev` I add a script to run `gulp server`.
4. Then open the link1: http://localhost:8888/web/viewer.html?file=%2Fweb%2F1206.5141.pdf
<img width="774" alt="企业微信截图_16675586042082" src="https://user-images.githubusercontent.com/9332442/199954249-6f852c15-cd67-4100-b01a-c0d8865d45f7.png">

5. But open this link2: http://localhost:8888/examples/components/simpleviewer.html
<img width="944" alt="企业微信截图_16675585412563" src="https://user-images.githubusercontent.com/9332442/199954235-7cb675cb-1a3c-4b8e-856f-287fb8fdb181.png">


The link2 loading PDF with builded pdfjs-dist in node_modules.  The link1 loading PDF with source code. They are not same.

**Comment by Snuffleupagus** [comment]
I bet that if you look in the console you'll see a warning suggesting why it doesn't work: You've not specified the path to the standard fonts, see https://github.com/mozilla/pdf.js/blob/eda51d1dcc583120fae8953cb98bf41de6deddf9/src/display/api.js#L172-L173

**Comment by Sara2009** [comment]
> I bet that if you look in the console you'll see a warning suggesting why it doesn't work: You've not specified the path to the standard fonts, see
> 
> https://github.com/mozilla/pdf.js/blob/eda51d1dcc583120fae8953cb98bf41de6deddf9/src/display/api.js#L172-L173

It works. Thank you very very much~~~
