### ISSUE TITLE
TextWidgetAnnotationElement prevents Enter key on Multiline Inputs (rendered as TextArea)

### ISSUE THREAD

**Issue by KBHDEV** [mozilla/pdf.js#15627]
Attach (recommended) or Link to PDF file [here:] Can't see how to attach a pdf here, but it is simple to create. Add a form object textbox to a pdf and make sure the option for "Multiline" is true.

Steps to reproduce the problem:
1.  Open a document with a Textbox that is set to Multiline.
2. Attempt to hit the Enter key to go to a new line.

What is the expected behavior? The cursor goes to a new line.

What went wrong? It does not go to a new line.

Link to a viewer: It can be reproduced on mozilla.github.io/pdf.js

I corrected the issue by altering the pdf.js file like this
element.addEventListener("keydown", event => { 
[...]
--} else if (event.key === "Enter") {
++ } else if (event.key === "Enter" && !this.data.multiLine) {

Our initial testing is coming through clean, and hopefully something like this code can be committed to the project in the future.

**Comment by KBHDEV** [comment]
[Example.pdf](https://github.com/mozilla/pdf.js/files/9870092/Example.pdf)
Figure out how to attach an example form.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.0.252 [987062c30] in Firefox Nightly 108 on Windows.

---

When opening an issue, please remember to fill out the "Configuration:"-section of the ISSUE_TEMPLATE since as-is there's required information missing here.

**Comment by KBHDEV** [comment]
I don't see a "Configuration:" section. What is the information you want?

**Comment by calixteman** [comment]
I can reproduce the issue with but not with Firefox buildin viewer:
https://mozilla.github.io/pdf.js/web/viewer.html

Anyway I think what you proposed makes sense (i.e. adding a check for `!multiLine`):
https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L1194

It doesn't make sense to commit the data when we're just adding a new line.

Could you make a PR please ?

**Comment by Snuffleupagus** [comment]
> I can reproduce the issue with:
> https://mozilla.github.io/pdf.js/web/viewer.html
> but not with Firefox buildin viewer

If there's a difference in behaviour, should we perhaps try and understand *why* that is?

> Anyway I think what you proposed makes sense (i.e. adding a check for `!multiLine`):

Could that potentially lead to data-loss in some weird edge-case scenario, since the data is added to storage later (e.g. during the "blur" event)?

**Comment by KBHDEV** [comment]
If it wasn't apparent enough yet, I'm not much of a github user and had to look up what PR means.... When I tried it, I couldn't get past some validation messages. Probably because I didn't clone the project, I just downloaded it. 

It seems you guys are seeing the issue. If my solution isn't correct, I'll certainly trust your judgement on how to fix it. 

You can close this issue if you want to move to a more correct place. I just wanted to help if I could. Our organization uses this product and I wanted to help fix a bug if I could. Thank you all for everything you do here.
