### ISSUE TITLE
The Firefox browser is incompatible

### ISSUE THREAD

**Issue by iioufogood** [mozilla/pdf.js#15644]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox  106.0.2 (64 位)
- Operating system and its version:  window 11
- PDF.js version: v2.14.305 +
- Is a browser extension: false

As shown below, there is a problem with rendering. Dom overlay misalignment.
![image](https://user-images.githubusercontent.com/31815016/198859838-0f2a96fb-7c4f-4c6e-a3cf-1923dd5e2184.png)

![image](https://user-images.githubusercontent.com/31815016/198859151-47da0335-e0a1-4809-96be-078d34a8fd73.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> PDF.js version: v2.14.305 +

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> As shown below, there is a problem with rendering. Dom overlay misalignment.

As mentioned above, no debugging can be done with screen-shots alone unfortunately.
