### ISSUE TITLE
Tool menu allows horizontal scroll for some languages

### ISSUE THREAD

**Issue by Sterzz** [mozilla/pdf.js#15646]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox Nightly 108.0a1
- Operating system and its version: Debian 11
- PDF.js version: 3.1.2
- Is a browser extension: No

Steps to reproduce the problem:
1. Change the browser language to for example German.
2. Open any pdf.
3. Click on tools.

What is the expected behavior? (add screenshot)
The tools menu should behave like in the English version.
What went wrong? (add screenshot)
It is possible to scroll horizontally.
![2022-10-30_15-17](https://user-images.githubusercontent.com/112873644/198883484-84a86986-05e3-4f04-b3c4-9ea6f6e48d61.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
WFM, in Firefox Nightly 108 on Windows 7.

![secondaryToolbar](https://user-images.githubusercontent.com/2692120/198884021-3dfadab6-78ad-4a85-a18a-6e7e11c26095.png)

**Comment by timvandermeij** [comment]
Let's close this as an upstream (fixed) bug then. Thanks.
