### ISSUE TITLE
`canvas` should not be a dependency if possible

### ISSUE THREAD

**Issue by tamuratak** [mozilla/pdf.js#15652]
`canvas` has been added to the dependency, not devDependency, since v3.0.279. I don't think it is a good idea. Because `node-canvas` prebuilds aren't available for ARM, users with macOS on ARM will request helps from you, which would increase the maintenance burden. We can say the same thing for users with old Linux for which `node-canvas` prebuilds aren't available.

When GitHub actions supports macOS on ARM, the situation would change.

- https://github.com/Automattic/node-canvas/issues/1511

- https://github.com/mozilla/pdfjs-dist/blob/f6eefc659269fe422cc350fe2eef769251eec33d/package.json#L15-L18
```json
  "dependencies": {
    "canvas": "^2.10.1",
    "web-streams-polyfill": "^3.2.1"
  },
```

Configuration:
- PDF.js version: 3.0.279

**Comment by Snuffleupagus** [comment]
What do you actually propose that we do instead, since the `canvas` package is necessary when using the PDF.js library in Node.js environments and we support browsers/Node.js in the same builds?

**Comment by tamuratak** [comment]
One of options would be moving `canvas` into `optionalDependencies` from `dependencies`. Then, `npm i pdfjs-dist` will install `canvas` as a dependency by default, and `npm` will not stop installing `pdfjs-dist` even if installing `canvas` fails. 

Users also can execute`npm i --omit=optional pdfjs-dist` if they want not to install `canvas`.

- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#optionaldependencies

**Comment by Snuffleupagus** [comment]
So by using `optionalDependencies` we basically we change an install-time error into a *potential* run-time error for some (hopefully small number of) Node.js users, while avoiding any issues for browser users?
If so, I suppose that we can try that; please submit a patch.

**Comment by sunknudsen** [comment]
@tamuratak Thanks for raising flag… just hit use case on M1 Mac.

@Snuffleupagus, will #15655 makes it’s way to `pdfjs-dist`?

**Comment by timvandermeij** [comment]
Fixed in release 3.1.81.

**Comment by nikitakot** [comment]
The `npm i --omit=optional pdfjs-dist` doesn't seem to work. The `canvas` dependency is still installed and then `npm i` fails during `node-gyp` step.

**Comment by bn3t** [comment]
For me it worked when doing:

`npm i --omit=optional pdfjs-dist@3.5.141`

Since, my issue was specifically when running unit tests combining vitest and jsdom, I also did:

`npm i --omit=optional jsdom`

**Comment by silverwind** [comment]
`omit` works (best set in `.npmrc`), but it's dangerous because it will omit all optional dependencies from all your dependencies, not just `pdfjs-dist`.

**Comment by bn3t** [comment]
At the end, I have to come back at what I've written in an above comment. --omit=optional didn't work as other dependencies were marked as optional (esbuild-*) but were necessary anyway. I am using another solution which also looks like a hack but seems to work. It comes from this SO answer: https://stackoverflow.com/a/73846274. It consists in adding this to package.json:

```
"overrides": {
    "canvas": "../_EXCLUDED_"
  }
```

Since `canvas`, is an optional dependency, an override to a non existing location is ignored silently.

**Comment by lucasgadams** [comment]
Is there any way to reduce the needed size of the canvas package? when I use pdfjs in a nextjs environment, the canvas package is like 48mb and the limit for Vercel is 50mb! This makes it incredibly difficult to build an app. No other package is even close to this size. Kind of pulling my hair out over this, i currently cant deploy my app. Any ideas?

**Comment by MattyBalaam** [comment]
I found a workaround to stop installing canvas if that might help? We add a new entry to the resolutions object in package.json for `canvas`:

https://github.com/mozilla/pdf.js/issues/16463

**Comment by net** [comment]
I wonder if using [@napi-rs/canvas](https://github.com/Brooooooklyn/canvas) instead would be a good solution for both M1 and Vercel environments.

**Comment by jakepgoldman** [comment]
@net how would you go about replacing the `canvas` dep with the package you listed above?

**Comment by cmahnke** [comment]
Can we please reopen / reconsider this?
By now `cavas` is clearly in a dying state:
For many platforms it's not even installable anymore:
* https://github.com/Automattic/node-canvas/issues/2448
* https://github.com/Automattic/node-canvas/issues/2433

Since this currently impacts pdf.js (currenty forced to use pre-release code to get it to work: https://github.com/mozilla/pdf.js/pull/18922) there should be a documented way to skip this dependency (if it needs be be in there for a transition period)

**Comment by Brooooooklyn** [comment]
Hey everyone, I [received positive feedback from @napi-rs/canvas](https://github.com/Brooooooklyn/canvas/issues/113#issuecomment-2455137298). I’m happy to help with migrating node-canvas to @napi-rs/canvas for PDF.js. Here is the issue tracking the tasks in @napi-rs/canvas: https://github.com/Brooooooklyn/canvas/issues/931.

Anyone who has experience with it, please feel free to contribute or discuss at https://github.com/Brooooooklyn/canvas.

**Comment by timvandermeij** [comment]
In PR #19015 we removed the `canvas` and `path2d` dependencies in favor of `@napi-rs/canvas`. This will be part of the upcoming release and hopefully resolves the installation issues that were experienced with the `canvas` package.
