### ISSUE TITLE
getStructTree do not return struct content 

### ISSUE THREAD

**Issue by lianyzhou** [mozilla/pdf.js#15650]
Attach (recommended) or Link to PDF file here:
[input.pdf](https://github.com/mozilla/pdf.js/files/9898961/input.pdf)

Configuration:
- NodeJs Application: v16.13.1
- Operating system and its version: Win10 Home
- PDF.js version:  2.16.105
- Is a browser extension: No

Reason:
I want to read a pdf file and extract all the heading(h1, h2) items from the pdf，but i can only extract the heading item id ， not the text ， there's no extra api i could fould to achive this goal.

Steps to reproduce the problem:
```

const path = require("path");
const pdfjsLib = require("pdfjs-dist/legacy/build/pdf.js");
const pdfPath = path.resolve(__dirname, "input1.pdf");
const loadingTask = pdfjsLib.getDocument(pdfPath);
loadingTask.promise
  .then(function (pdf) {
    for(var i = 1; i <= pdf.numPages; i++) {
        pdf.getPage(i).then(async function (page) {
          const pTree = await page.getStructTree();


            if (pTree.children) {
              pTree.children.forEach((part) => {
                if (part.children) {
                  part.children.forEach((item) => {
                    if (/^H\d+$/.test(item.role)) {
                      const headingChildren =  item.children;
                      if (headingChildren) {
                        headingChildren.forEach((span) => {
                          console.log(span.children);
                        });
                      }
                    }
                  });
                }
              });
            }
        });
    }
  });
```

What is the expected behavior? (add screenshot)

I want to get h1 element's text content , but now i can only get the id of that element 

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6295633/198956659-c0418076-7ab3-4100-aeee-077a0430bcbf.png)

![image](https://user-images.githubusercontent.com/6295633/198956445-a84ebadf-6e8a-4f65-8add-b48546b859f4.png)

Finally, Thanks a lot to pdf.js, i use it several years and it's fabulous。

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [input.pdf](https://github.com/mozilla/pdf.js/files/9898961/input.pdf)

That document doesn't seem to contain any `structTree` data. (Note that most PDF documents don't actually include such data.)

> PDF.js version:  2.16.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I want to read a pdf file and extract all the heading(h1, h2) items from the pdf，but i can only extract the heading item id ， not the text ， there's no extra api i could fould to achive this goal.

Given that information provided thus far, the above is unfortunately quite difficult to parse/understand.
However, please keep in mind that the *actual text-content* is separate from the `structTree`-data and thus need to be fetched with e.g. `page.getTextContent({ includeMarkedContent: true }` as usual.

> Steps to reproduce the problem:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by CoderMuffin** [comment]
May find this helpful https://github.com/mozilla/pdf.js/discussions/18508
