### ISSUE TITLE
The Firefox browser is incompatible

### ISSUE THREAD

**Issue by iioufogood** [mozilla/pdf.js#15656]
Attach (recommended) or Link to PDF file here:

Configuration:
testfile  [A1.pdf](https://github.com/mozilla/pdf.js/files/9915454/A1.pdf)

- Web browser and its version: Firefox  106.0.2 (64 位)
- Operating system and its version:  window 11
- PDF.js version: v3.0.279
- Is a browser extension: false

As shown below, there is a problem with rendering. Dom overlay misalignment.
![image](https://user-images.githubusercontent.com/31815016/198859838-0f2a96fb-7c4f-4c6e-a3cf-1923dd5e2184.png)

![image](https://user-images.githubusercontent.com/31815016/198859151-47da0335-e0a1-4809-96be-078d34a8fd73.png)

**Comment by NielsInfralogic** [comment]
Related(?) rendering problems in Goggle chrome inside textlayer div


Web browser and its version: Google Chrome v. 107.0.5304.88
Operating system and its version: window 11
PDF.js version: v3.0.279
Is a browser extension: false

![Screenshot 2022-11-02 083420](https://user-images.githubusercontent.com/19637582/199427482-734e2117-3eaf-4258-9cb5-3cdd2624cb19.png)
![Screenshot 2022-11-02 084900](https://user-images.githubusercontent.com/19637582/199430254-b1525c8c-945a-4484-8e4a-2263eece6a9c.png)

![Screenshot 2022-11-02 084508](https://user-images.githubusercontent.com/19637582/199429470-60c9bd17-8c64-4a06-854d-b09e026b0809.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.1.6 [e42e1cde6] in Firefox Nightly 108 on Windows.

![text](https://user-images.githubusercontent.com/2692120/199440634-4e086997-6d8c-4bdc-a023-46f4f54bafc1.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: v3.0.279

Also, your screen-shot doesn't really agree with the quoted version number since it shows an *older* viewer (given the visible toolbar icons).
