### ISSUE TITLE
Font names are different when using getTextContent()

### ISSUE THREAD

**Issue by bmaupin** [mozilla/pdf.js#15651]
Attach (recommended) or Link to PDF file here: 
- [anguish-languish.pdf](https://github.com/mozilla/pdf.js/files/9903280/anguish-languish.pdf)
- [anguish-languish-2.pdf](https://github.com/mozilla/pdf.js/files/9903359/anguish-languish-2.pdf)

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Ubuntu 22.04
- PDF.js version: 2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a PDF using pdf.js
2. Get a page and call `page.getTextContent()`

What is the expected behavior? (add screenshot)

`items` contains a list of text items with a `fontName` attribute. I would expect `fontName` to be the same as the font name used in the PDF, e.g. in the attached file it should be `Helvetica-Bold` and `Times-Roman`.

What went wrong? (add screenshot)

For anguish-languish.pdf (above) instead of the original font names (`Helvetica-Bold` and `Times-Roman`), the font names appear to be truncated to `Helvetica` and `Times`

For anguish-languish-2.pdf, instead of `AAAAAA+LiberationSerif-Bold` and `BAAAAA+LiberationSerif` I see completely different font names: `g_d0_f1` and `g_d0_f2`

According to [this pull request](https://github.com/mozilla/pdf.js/pull/10753) it seems that a different font name is used. Is there a way to get the original font name?

That PR has a couple thumbs up (excluding my own) so it seems there's some interest in this.

Thanks!

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.16.105

Please note that that version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> According to [this pull request](https://github.com/mozilla/pdf.js/pull/10753) it seems that a different font name is used. Is there a way to get the original font name?

No such functionality exists, unfortunately (for the reasons outlined there). Please keep in mind that PDF documents, from a specification perspective, uses slightly different code-paths for rendering and text-extraction.
Hence it's possible that the text-content may contain glyphs not actually present in the font-files themselves, with ligatures being one potential example, which is (part of) the reason that we use different fonts for rendering respectively text-selection.

**Comment by bmaupin** [comment]
@Snuffleupagus What about adding the original font to `TextStyle`? That would use much less memory since it appears only one TextStyle item is created for each font. Would such a PR be accepted?

It seems like it'd be pretty trivial to add: https://github.com/bmaupin/pdf.js/commit/a4fc11d186d6a3148ec46799629459e6d7b36116

Thanks!

**Comment by Snuffleupagus** [comment]
> For anguish-languish.pdf (above) instead of the original font names (`Helvetica-Bold` and `Times-Roman`), the font names appear to be truncated to `Helvetica` and `Times`
> 
> For anguish-languish-2.pdf, instead of `AAAAAA+LiberationSerif-Bold` and `BAAAAA+LiberationSerif` I see completely different font names: `g_d0_f1` and `g_d0_f2`

The difference is non-embedded respectively embedded fonts (this apparently didn't make it into my previous response).

> What about adding the original font to `TextStyle`? That would use much less memory since it appears only one TextStyle item is created for each font. Would such a PR be accepted?

That wouldn't actually work correctly for the non-embedded font case, since e.g. "Arial", "Arial,Bold", "Arial,Italic", and "Arial,BoldItalic" all map to "Helvetica" in the `font.loadedName`; hence the answer is unfortunately no.

**Comment by bmaupin** [comment]
@Snuffleupagus I probably wasn't very clear in my original request either.

What I labeled as the "original font names" (perhaps mistakenly) were actually the values I got from `font.name` (as per the commit I linked above). 

The first file I attached (anguish-languish.pdf) doesn't have embedded fonts. However, the font names from `font.name` are `Helvetica-Bold` and `Times-Roman`, which is still better than `Helvetica` and `Times`.

For the other file, `AAAAAA+LiberationSerif-Bold` is also better than `g_d0_f1`.

Is the issue that "`originalFontName`" isn't an accurate descriptor? Would another property name be better? It would be great to get this information as the current `fontName` property loses some helpful information.

Thanks!

**Comment by Snuffleupagus** [comment]
I wasn't talking about your specific example, but rather about the *general case* where your patch wouldn't do the right thing for a PDF document that contains (all of the) non-embedded fonts named "Arial", "Arial,Bold", "Arial,Italic", respectively "Arial,BoldItalic". As already mentioned they all map to "Helvetica" in the `font.loadedName` property, hence the only generally correct solution would be PR #10753 but as mentioned we're not at all keen on doing that.

> However, the font names from `font.name` are `Helvetica-Bold` and `Times-Roman`, which is still better than `Helvetica` and `Times`.

We can't very well add a feature that only kind of works, as explained above, since that'll only lead to user confusion and support requests. Sorry, but there's unfortunately no great solution here that does the "right thing" without overhead for the default case.

**Comment by bmaupin** [comment]
That makes sense, thanks for your patience in explaining it.

I do have another proposal: `getTextContent` can take parameters; would it be acceptable to keep the current behaviour as-is, but to add a new parameter to add the original font name to the TextItems as per the [referenced PR](https://github.com/mozilla/pdf.js/pull/10753)? That would allow those of us that would like this information to get it without increasing memory usage for those that don't.

Thanks!

**Comment by bmaupin** [comment]
> I wasn't talking about your specific example, but rather about the _general case_ where your patch wouldn't do the right thing for a PDF document that contains (all of the) non-embedded fonts named "Arial", "Arial,Bold", "Arial,Italic", respectively "Arial,BoldItalic". As already mentioned they all map to "Helvetica" in the `font.loadedName` property, hence the only generally correct solution would be PR #10753 but as mentioned we're not at all keen on doing that.

@Snuffleupagus Now that #15659 has made it so that this is no longer the case, would a PR to add the original font name to the `TextStyle` be considered?

Thanks!

**Comment by bmaupin** [comment]
@Snuffleupagus Thanks for your patience in explaining things.

> I wasn't talking about your specific example, but rather about the _general case_ where your patch wouldn't do the right thing for a PDF document that contains (all of the) non-embedded fonts named "Arial", "Arial,Bold", "Arial,Italic", respectively "Arial,BoldItalic". As already mentioned they all map to "Helvetica" in the `font.loadedName` property, hence the only generally correct solution would be PR #10753 but as mentioned we're not at all keen on doing that.

Now that #15659 has made it so that this is no longer the case, would a PR to add the original font name to the `TextStyle` be considered?

Thanks!

**Comment by Snuffleupagus** [comment]
> Now that #15659 has made it so that this is no longer the case, would a PR to add the original font name to the `TextStyle` be considered?

No, since all information should already be (indirectly) available; see e.g. https://github.com/mozilla/pdf.js/pull/15659/files#diff-bc84ed767f5905bdf8c544c715c08e9b751e7bb1db16c8182d9de515b56bc4b6R2269-R2272

**Comment by bmaupin** [comment]
@Snuffleupagus It works! Thanks so much for your help!

```javascript
const { items, styles } = await pdfPage.getTextContent();

await pdfPage.getOperatorList();

for (const fontName in styles) {
  console.log('fontName=', fontName);
  console.log('originalFontName=', page.commonObjs.get(fontName).name);
  console.log();
}
```

```
fontName= g_d0_f6R
originalFontName= Helvetica-Bold

fontName= g_d0_f3R
originalFontName= Times-Roman

fontName= g_d0_f5R
originalFontName= Helvetica
```
