### ISSUE TITLE
l10n: #save and #save_label undefined

### ISSUE THREAD

**Issue by radieter** [mozilla/pdf.js#15653]
looks like the translations for save and save_label are missing
willing to support if you give me a general direction
looks like the variables were renamed from
download_* to save_*
![bug](https://user-images.githubusercontent.com/933949/199322034-744d71e4-09c0-4651-97b2-25ea7de5e78c.PNG)

**Comment by Snuffleupagus** [comment]
This will be fixed with future l10n updates, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md
> Note that the translations for PDF.js in the `l10n` folder are imported from the Nightly channel of Mozilla Firefox, such that we don't have to maintain them ourselves. This means that we will not accept pull requests that add new languages and/or modify existing translations, unless the corresponding changes have been made in Mozilla Firefox first.
