### ISSUE TITLE
How to listen to events from pdf.js

### ISSUE THREAD

**Issue by TechRiddles** [mozilla/pdf.js#15661]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: edge Version 107.0.1418.26
- Operating system and its version: windows 11
- PDF.js version:2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
1. Download and Extract the PDF.js Package
2.Embed the PDF Viewer in Website

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.16.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Assuming that you're talking about the default viewer, the `EventBus` can be accessed via `PDFViewerApplication.eventBus` *after* the viewer has loaded; see https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage
