### ISSUE TITLE
[optimisation]

### ISSUE THREAD

**Issue by BryanCrotaz** [mozilla/pdf.js#15662]
Seeing this console log when running in Chrome on Windows:

```
Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. 
See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

See [https://github.com/fserb/canvas2D/blob/master/spec/will-read-frequently.md](https://github.com/fserb/canvas2D/blob/master/spec/will-read-frequently.md)

Seems like an optimisation target

**Comment by Snuffleupagus** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#parameters that parameter disables hardware acceleration, which could thus very well end up *reducing* performance in some cases (or even overall).
Considering that this issue contains no measurements that show a clear benefit of doing this (within the context of the PDF.js code), especially given the point above, let's close this as WONTFIX for now.

(*For future reference:* As mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#issue, please remember to add a slightly more descriptive title when opening issues.)
