### ISSUE TITLE
Print pdf shows Print preview failed

### ISSUE THREAD

**Issue by akshayb007** [mozilla/pdf.js#15668]
Hii there,

I am facing issue with pdf print preview after rendering my pdf on pdfjs.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this issue is missing every single piece of information required in order to be actionable/valid.
