### ISSUE TITLE
Question about the file parameter

### ISSUE THREAD

**Issue by 1506085843** [mozilla/pdf.js#15660]
I have the following link：
`https://127.0.0.1:8080/trd/pdf/0/viewer.html?title=myPDFtest&file=download/attach/myPDFtest.pdf&tokenStr=N8iSQrfVqmazjQDlyiSd8sNzna0HQ7YWYQHgdj3oq9vHyrS4/8gZOprY/O61m6+yqn4bkpvuNdxd`

The final request will go to this link to get the file：
`https://127.0.0.1:8080/download/attach/myPDFtest.pdf`
but it's not what i want.

I want to make the request go to the link below to get the pdf file：
`https://127.0.0.1:8080/download/attach/myPDFtest.pdf&tokenStr=N8iSQrfVqmazjQDlyiSd8sNzna0HQ7YWYQHgdj3oq9vHyrS4/8gZOprY/O61m6+yqn4bkpvuNdxd`

Simply, I want 
`tokenStr=N8iSQrfVqmazjQDlyiSd8sNzna0HQ7YWYQHgdj3oq9vHyrS4/8gZOprY/O61m6+yqn4bkpvuNdxd `
as part of file .

What should I do?

**Comment by Snuffleupagus** [comment]
Encode the file name, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file
