### ISSUE TITLE
node-canvas issue with Electron: The version of Node.js requires NODE_MODULE_VERSION 109

### ISSUE THREAD

**Issue by GitMurf** [mozilla/pdf.js#15672]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Electron v21.0.1
- Operating system and its version: windows 11
- PDF.js version: 3.0.279
- Is a browser extension: no

Steps to reproduce the problem:
1. Install node.js LTS v18.2.1
2. Install pdfjs with electron
3. Try and run Electron app

What went wrong? (add screenshot)

![A07FBCB7-82BC-4517-A1F9-1E56F3C57585](https://user-images.githubusercontent.com/64155612/200486932-7346eb54-e611-4e27-8818-fa1aa33fd4a8.png)

When running pdfjs with Electron the node-canvas package causes the error in the screenshot: Compiled against a different Node.js version using NODE_MODULE_VERSION 108. The version of Node.js requires NODE_MODULE_VERSION 109

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. Install node.js LTS v18.2.1
>     2. Install pdfjs with electron
>     3. Try and run Electron app

Sorry, but we can't support frameworks such as "Electron" here. Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> What went wrong? (add screenshot)

Given that the error seems to occur inside of https://github.com/Automattic/node-canvas code, this probably needs to be reported in that project instead.

**Comment by GitMurf** [comment]
I understand you cannot support other frameworks but if you introduce a dependency that creates problems, isn’t that something you want to be aware of? Previous versions of pdfjs did not have this problem. I’m not sure if you just introduced node-canvas as a dependency recently or if you updated the version pdfjs uses, but I didn’t have the problem with for example pdfjs v2.16.105.

Any further details you can provide would be much appreciated.

**Comment by GitMurf** [comment]
@Snuffleupagus an alternative that could work for me for now (until Electron gets better support for using a downstream native module like node-canvas) is that I could revert back to an older version of pdfjs that did not require node-canvas in the parts of the code I am using (so i do not get the error above).

But then I would just have to find an alternative to saving images from within a PDF to a PNG file without being able to create/use a Canvas. Basically I would need an alternative to turn the image.data from for example `paintImageXObject` to buffer to be able to then write to a PNG file. Are there alternatives to do this other than using a Canvas? Thanks!

**Comment by GitMurf** [comment]
FYI this has been solved with node-canvas moving to node-addon-api recently!🎉 See PR here: https://github.com/Automattic/node-canvas/pull/2235
