### ISSUE TITLE
How to dispatch events to DOM in pdf.js

### ISSUE THREAD

**Issue by TechRiddles** [mozilla/pdf.js#15676]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: edge Version 107.0.1418.26
- Operating system and its version: windows 11
- PDF.js version:3.9.279
- Is a browser extension:

Steps to reproduce the problem: 
1.Download and Extract the PDF.js Package
2.Embed the PDF Viewer in Website

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
We purposely removed global event dispatching, hence this isn't something that we'll support now.
As previously mentioned, see https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage#initialization-promise, you can add event listeners using e.g. the following format:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplication.initializedPromise.then(function() {
    PDFViewerApplication.eventBus.on("documentinit", () => {
      // A PDF document has now been initialized.
    });
  });
});
```

> PDF.js version:3.9.279

Did you actually mean `3.0.279`, since that's the latest available release!?

> Steps to reproduce the problem:
> 1.Download and Extract the PDF.js Package
> 2.Embed the PDF Viewer in Website

Generally speaking, this really isn't enough context to make an issue actionable/valid; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by TechRiddles** [comment]
Where exactly to add that?

**Comment by TechRiddles** [comment]
> Where exactly to add that?



> 

Where exactly to add this?

**Comment by TechRiddles** [comment]
> We purposely removed global event dispatching, hence this isn't something that we'll support now. As previously mentioned, see https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage#initialization-promise, you can add event listeners using e.g. the following format:
> 
> ```js
> document.addEventListener("webviewerloaded", function() {
>   PDFViewerApplication.initializedPromise.then(function() {
>     PDFViewerApplication.eventBus.on("documentinit", () => {
>       // A PDF document has now been initialized.
>     });
>   });
> });


Where exactly to add this?
