### ISSUE TITLE
PDFs not shown correctly in Chrome based browsers

### ISSUE THREAD

**Issue by NetruN** [mozilla/pdf.js#15673]
Attach (recommended) or Link to PDF file here:
[DB_Abrechnungsbescheinigung_01.pdf](https://github.com/mozilla/pdf.js/files/9959588/DB_Abrechnungsbescheinigung_01.pdf)

Configuration:
- Web browser and its version:
-- Chrome 107.0.5304.91
-- Firefox 106.1.0
-- Edge 107.0.1418.28
- Operating system and its version:
-- Android 13 (incl. October Updates)
- PDF.js version:
-- PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 3.1.20 [7e5008f0f])
-- the one from the demo here: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:
-- no

Steps to reproduce the problem:
1. open attached file in demo pdf.js viewer here: https://mozilla.github.io/pdf.js/web/viewer.html
2. see broken file in Chrome

What is the expected behavior? (add screenshot)
Firefox and Edge show the file correct:
![Firefox](https://user-images.githubusercontent.com/12908284/200526897-ae53c4e3-58b4-4cd7-90ee-cccd6f310dc9.png)
![Edge](https://user-images.githubusercontent.com/12908284/200526909-207d7be5-d301-4ba6-851a-0110b017ca14.png)

**Chrome should do the same.**
I know this could be a Google Chrome problem, but till Google will take care of this there should be a workaround. Chrome is the most used browser on Android.

What went wrong? (add screenshot)
Chrome shows the file broken:
![Chrome](https://user-images.githubusercontent.com/12908284/200526905-d4b2cd9c-1ff7-4448-ab4b-f3db3b05a6fa.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Firefox and Edge show the file correct:
> [...]
> I know this could be a Google Chrome problem, but till Google will take care of this there should be a workaround. Chrome is the most used browser on Android.

WFM, when testing in Google Chrome Beta 108.0.5359.29 on Windows.

Unfortunately this points rather clearly to a bug in the *browser itself*, so please report it to the Chromium developers.
Please also keep in mind that the *primary* development target in this library in the built-in Firefox PDF viewer.
