### ISSUE TITLE
Enable Javascript code to Outlines

### ISSUE THREAD

**Issue by spradhan1990** [mozilla/pdf.js#15681]
Response from the rest call:

![PDFOutlineResponse](https://user-images.githubusercontent.com/79566088/201328998-30c31d54-ebef-4384-910f-c02536319e8b.png)

Issue:
the value for URI is "(javascript:openLinkDoc\('pdf-loc\(7/fith\(7840\)\)'\);)". It is accepting it as unsafe URL.

Questions:
How to make it work.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately missing all of the necessary details needed in order be actionable/valid.

**Comment by spradhan1990** [comment]
Web browser and its version: chrome, 107.0.5304.63
Operating system and its version: Red Hat Enterprise Linux Server, 7.9 (Maipo)
PDF.js version: 3.0.279
Is a browser extension: No
Steps to reproduce the problem: 
1. Open any pdf in chunks of 5 pages with Outline contents and check the response.
![PDFOutlineResponse](https://user-images.githubusercontent.com/79566088/201331585-b2d1472a-5f32-47e9-b35e-18b5dc9c7ca4.png)
2. The value for the URI is javascript code is "(javascript:openLinkDoc('pdf-loc(7/fith(7840))');)". It is accepting it as unsafe URL.

What is the expected behavior?
the Outline href value is blank.

How to make it work. Please help

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As mentioned before, the "Attach (recommended) or Link to PDF file here:"-part of the ISSUE_TEMPLATE is always required.

> The value for the URI is javascript code is "(javascript:openLinkDoc('pdf-loc(7/fith(7840))');)". It is accepting it as unsafe URL.

Furthermore, that's doesn't look like a generally valid URL.
