### ISSUE TITLE
Cannot read properties of undefined (reading 'getDocument')

### ISSUE THREAD

**Issue by DoneDeal0** [mozilla/pdf.js#15685]
Configuration:
- Node 16.13.1
- PDF.js version: 3.0.279

I would like to parse a PDF on a node server, but PDFJS crashes. Here is the process I've followed:

- download the latest official build of PDFJS (3.0.279).
- add the PDFJS folder to the node project (not as a node module, but as proper folder)
- import PDFJS, call `PDFJS.getDocument("pathOfPDF")`
- It crashes with the following error:

> TypeError: Cannot read properties of undefined (reading 'getDocument')

The code is yet simple:
```js
import PDFJS from "./pdfjs-3.0.279-dist/build/pdf.js";

public async parsePDF(pdfPath: string) {
    const doc = await PDFJS.getDocument(pdfPath);
    for (let i = 1; i <= doc.numPages; i++) {
      const page = await doc.getPage(i);
      this.parsePage(page);
    }
    doc.destroy();
    return await this.getParsedPDF();
  }
```

The PDFJS folder looks like this:
 - build
   - pdfj.js
   - pdf.js.map
   - pdf.sandbox.js
   - pdf.sandbox.js.map
   - pdf.worker.js
   - pdf.worker.js.map
 - web (all files also in `web` folder)

How to fix this? Thank you!

EDIT: I've also tried to use the legacy build (`2.16.105-legacy-dist` and `3.0.279-legacy-dist`)

**Comment by Snuffleupagus** [comment]
> download the latest official build of PDFJS (3.0.279).

Do you mean using https://mozilla.github.io/pdf.js/getting_started/#download, or something else?

Please note that we distribute the core package (without e.g. the full viewer) via NPM, see https://www.npmjs.com/package/pdfjs-dist, which might be more appropriate in your use-case.

> The code is yet simple:
> ```js
> import PDFJS from "./pdfjs-3.0.279-dist/build/pdf.js";
> ...
> ```

I'm not sure if that import format works correctly, please refer to the following Node.js usage examples: https://github.com/mozilla/pdf.js/tree/master/examples/node

**Comment by DoneDeal0** [comment]
> Do you mean using https://mozilla.github.io/pdf.js/getting_started/#download, or something else?
Yes.

> https://www.npmjs.com/package/pdfjs-dist, which might be more appropriate in your use-case.
I can't install the package.  I have the error `node-pre-gyp ERR! install response status 503 Egress is over the account limit.` It also says `ERR! find Python You need to install the latest version of Python.`.  Will I need to include Python on my node server to run PDFJS?

**Comment by Snuffleupagus** [comment]
> I can't install the package. I have the error `node-pre-gyp ERR! install response status 503 Egress is over the account limit.` It also says `ERR! find Python You need to install the latest version of Python.`. Will I need to include Python on my node server to run PDFJS?

Those errors seem to be Node.js/NPM related, rather than anything specifically connected to the PDF.js library; hence we unfortunately can't help with that.

---

Also, you definitely need to use a `legacy` build in Node.js since otherwise there's no guarantee that things will work.

Did you try just changing the import format, following the examples linked in https://github.com/mozilla/pdf.js/issues/15685#issuecomment-1312456507, to use `require` instead?
```javascript
const pdfjsLib = require(/* path to the legacy/pdf.js file */);
pdfjsLib.getDocument(...);
...
```

**Comment by DoneDeal0** [comment]
I've downloaded the legacy build `2.16.105` from the release/assets tabs, and imported it as such:

`const PDFJS = require("./pdfjs-2.16.105-legacy-dist/build/pdf.js");`

The server doesn't compile because of the following error:
> Cannot find module 'dommatrix/dist/dommatrix.js'

The folder structure is straightforward:
- pdf
  - pdfjs-2.16.105-legacy-dist
  - index.ts (this file imports `const PDFJS = require("./pdfjs-2.16.105-legacy-dist/build/pdf.js");`)

**Comment by Snuffleupagus** [comment]
Sorry, but in order to use the PDF.js library in Node.js environments it's unfortunately going to be necessary to install it from NPM since that's the only way that the necessary dependency management will work. (In general, using Node.js without being able to access any NPM packages seem quite difficult.)

The only possible work-around would be for you to manually provide polyfills for the following functionality, however doing so without being able to use NPM seem difficult
https://github.com/mozilla/pdf.js/blob/2d1b1e79685bc9c432395c612b6562dc76898486/src/shared/compatibility.js#L41-L57

I realize that this is troublesome in your particular case, however please keep in mind that the PDF.js library is developed primarily for use in *browsers* and the Node.js support thus assume a fully working Node.js/NPM setup unfortunately.

**Comment by elirangoshen** [comment]
I installed the package and still getting this error: 

```
import pdfjsLib from 'pdfjs-dist';







export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const downloadUrl = searchParams.get("downloadUrl");
  try {
  const doc = await pdfjsLib.getDocument(downloadUrl || '').promise;
  const page = await doc.getPage(1);
  const textContent = await page.getTextContent();
  const pageText = textContent.items.map((item) => item.str).join(' ');

  return new Response(downloadUrl);
  
   
  } catch (e) {
    return new Response(JSON.stringify({ error: e.message }))
  }
```

this error im getting : `{"error":"Cannot read properties of undefined (reading 'getDocument')"}`

` "pdfjs-dist": "^3.8.162",`
node -v: v20.4.0

**Comment by Saicharan0662** [comment]
@elirangoshen I am also getting the same error. Did your error get resolved or any other alternatives?
Thanks!

**Comment by KDDeveloper** [comment]
@elirangoshen @Saicharan0662 I am facing the same error in react when trying to use the package pdfjs-dist

**Comment by jvgpinheiro** [comment]
@elirangoshen @Saicharan0662 @KDDeveloper

```javascript
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const downloadUrl = searchParams.get("downloadUrl");
  try {
    const doc = await getDocument(downloadUrl || '').promise;
    const page = await doc.getPage(1);
    const textContent = await page.getTextContent();
    const pageText = textContent.items.map((item) => item.str).join(' ');

    return new Response(downloadUrl);
  } catch (e) {
    return new Response(JSON.stringify({ error: e.message }))
  }
}
```

When importing the function directly this way I stopped getting this error. Didn't test it much further, just stopped getting the error.

**Comment by Th3Mayar** [comment]
Ty @DoneDeal0 ⚡
