### ISSUE TITLE
FindController not supports FULLWIDTH LATIN CAPITAL

### ISSUE THREAD

**Issue by iahu** [mozilla/pdf.js#15690]
Attach (recommended) or Link to PDF file here:
[fullwidth.pdf](https://github.com/mozilla/pdf.js/files/10002370/fullwidth.pdf)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.15.349
- Is a browser extension: no

Steps to reproduce the problem:
1. open this [link](https://mozilla.github.io/pdf.js/web/viewer.html)
2. open the attached `fullwidth.pdf` file
3. toggle find bar, and typing a halfwidth character `O` to see the find result.
4. replace the query string with fullwidth character `Ｏ` and see the result again.

What is the expected behavior? (add screenshot)

convert find bar "query string" and page "textContent" to halfwidth to matches the find results.
or and a option to "ignore fullwidth and/or halfwidth capital case"

<img width="822" alt="截屏2022-11-14 19 27 10" src="https://user-images.githubusercontent.com/1704588/201649090-0408f57f-f5c2-4a86-895a-1fe84963d27e.png">
(↑ matches)

 

What went wrong? (add screenshot)

can't matches fullwidth characters with halfwidth characters.

<img width="985" alt="截屏2022-11-14 19 26 36" src="https://user-images.githubusercontent.com/1704588/201649120-178f4dcc-8aa0-46b6-8b31-3bb8dc616e30.png">
(↑ not match)
 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by iahu** [comment]
I find that FindController use `.normalize('NFD')` to normalize the string, and `NFD` do not convert fullwidth to halfwidth.

I don't know why use `NFD` algorithms, but I notice that `NFKC` can used to convert the fullwidth to halfwidth chars.

**Comment by calixteman** [comment]
`NFKC` is likely a bad idea  in order to find some chars with multiple diacritics.
Maybe we should use `NFKD` which is similar to `NFD` but the the compatibility equivalence would help to change those fullwidth chars in their ascii counterpart.
But it would imply to have some shifts due to, for example, the "fi" ligature.
Interestingly, it works correctly in Chrome and Preview but not in Acrobat and Foxit.
