### ISSUE TITLE
Is it possible to disable the download button?

### ISSUE THREAD

**Issue by kartagis** [mozilla/pdf.js#15697]
This is a support request rather than a bug. We are showing some PDFs on a page, and the client wants us to disable the download button because it's mainly a newspaper and the client doesn't want the PDFs to be downloaded. So, how can I disable the download button?

**Comment by Snuffleupagus** [comment]
> and the client wants us to disable the download button because it's mainly a newspaper and the client doesn't want the PDFs to be downloaded.

It's simply *impossible* to disable all ways of downloading the PDF document, unless you start editing the `pdf.js` and `pdf.worker.js` files to remove all the related functionality.

> So, how can I disable the download button?

The easiest solution would be to just hide the buttons using CSS rules, although that won't prevent e.g. keyboard shortcuts being used (or downloading triggered manually from the web-console, with direct function calls). You'd probably also need to change the `download`/`save` functions, in the viewer, to be no-ops instead; although as mentioned that'd not stop a motivated user.

Finally, please keep in mind that we don't really provide any functionality to easily customize the viewer like this; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by kartagis** [comment]
> The easiest solution would be to just hide the buttons using CSS rules, although that won't prevent e.g. keyboard shortcuts being used (or downloading triggered manually from the web-console, with direct function calls). You'd probably also need to change the download/save functions, in the viewer, to be no-ops instead; although as mentioned that'd not stop a motivated user.

I can hide it using CSS but only in Dev Tools but not in a separate CSS file, so I think something interferes. What do you think that might be?
