### ISSUE TITLE
Multi-line text selection does not work properly on iPadOS/iOS 

### ISSUE THREAD

**Issue by dbalabka** [mozilla/pdf.js#15691]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Safari
- Operating system and its version: iPadOS 15.6, iPadOS 16.1.1 (20B101)
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Use touch to select multiple lines of text 

What is the expected behavior? (add screenshot)
Multiple lines selection should work in the same way as native PDF viewer provides
![4CAE621C-B2D0-466B-B870-391226A5B480](https://user-images.githubusercontent.com/1269372/201650083-6d1876bf-88e4-46c5-aae8-ccc9413bed32.png)

What went wrong? (add screenshot)
The selection became larger and it is not clear what lines are selected 
![862B49D2-853A-4209-9282-EEB81AD713A4](https://user-images.githubusercontent.com/1269372/201649891-1d980cbb-2261-4507-91ab-1531500ac498.jpeg)
![C26080AF-AA19-41A6-AD1B-3CF64AD9A195](https://user-images.githubusercontent.com/1269372/201649899-7b2add9e-85eb-40d1-ab05-54c33634a314.jpeg)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari
> Operating system and its version: iPadOS 15.6, iPadOS 16.1.1 (20B101)

Please keep in mind that the built-in Firefox PDF Viewer is the *primary* development target in this project, hence we're unfortunately quite unlikely to make changes specifically for the configuration listed above.
