### ISSUE TITLE
pdf.js official demo app to test printing on iPad (Safari) issue

### ISSUE THREAD

**Issue by can2000ca** [mozilla/pdf.js#15709]
Hi guys, I have tested the ipad printing and found the printout contains the pdf.js header toolbar, and some contents on the right are missing. Please refer to below attached file. Could anyone have the same experience and how to solve this problem?
Any suggestion is appreciated! Thank you!

![test Ipad priting](https://user-images.githubusercontent.com/118213569/202751395-308c347d-7de8-4899-a82f-81412012febd.JPEG)

**Comment by can2000ca** [comment]
It is easy to duplicate:

1) open this link from iPad Safari:
https://mozilla.github.io/pdf.js/web/viewer.html
2) Open any PDF file
3) Print

**Comment by Snuffleupagus** [comment]
This looks like a *browser* bug, and Safari on iOS is known to have trouble with printing in general; see e.g. issue #7597. (Please keep in mind that Firefox is the *primary* development target in this library.)
