### ISSUE TITLE
Handle null `optionalContentConfig` in `canvas.js`

### ISSUE THREAD

**Issue by kmcclellan** [mozilla/pdf.js#15716]
Attach PDF file here: [layers_tiled.pdf](https://github.com/mozilla/pdf.js/files/10071179/layers_tiled.pdf)

Configuration:

Web browser and its version: FireFox 107.0 (64-bit)
Operating system and its version: Windows 10 Enterprise (10.0.19044 Build 19044)
PDF.js version: v3.0.201 (build: 39160c752)
Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF in FireFox.
2. Open Menu > More tools > Web Developer Tools > Console to see error

What is the expected behavior?

The PDF should render without error. Toggling layers "Black" and "Red" should hide the corresponding sections of the tiled content (see working example of [layered content without tiling pattern](https://github.com/mozilla/pdf.js/files/10071224/layers.pdf)).

What went wrong?

```
An error occurred while rendering the page.

PDF.js v3.0.201 (build: 39160c752)
Message: this.optionalContentConfig is undefined
Stack: beginMarkedContentProps@resource://pdf.js/build/pdf.js:8283:9
executeOperatorList@resource://pdf.js/build/pdf.js:6720:20
createPatternCanvas@resource://pdf.js/build/pdf.js:8916:14
getPattern@resource://pdf.js/build/pdf.js:8991:41
fill@resource://pdf.js/build/pdf.js:7262:33
executeOperatorList@resource://pdf.js/build/pdf.js:6720:20
_next@resource://pdf.js/build/pdf.js:3335:37
__webpack_modules__</_scheduleNext/<@resource://pdf.js/build/pdf.js:3323:14
FrameRequestCallback*_scheduleNext@resource://pdf.js/build/pdf.js:3322:14
renderContinueCallback@resource://pdf.js/web/viewer.js:12483:9
__webpack_modules__</paintOnCanvas/renderTask.onContinue@resource://pdf.js/web/viewer.js:12688:16
_continue@resource://pdf.js/build/pdf.js:3314:17
operatorListChanged@resource://pdf.js/build/pdf.js:3303:10
_renderPageChunk@resource://pdf.js/build/pdf.js:2009:26
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2049:14
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
__webpack_modules__</_pumpOperatorList/pump/<@resource://pdf.js/build/pdf.js:2051:9
promise callback*pump@resource://pdf.js/build/pdf.js:2036:21
_pumpOperatorList@resource://pdf.js/build/pdf.js:2079:5
render@resource://pdf.js/build/pdf.js:1746:12
paintOnCanvas@resource://pdf.js/web/viewer.js:12682:37
draw@resource://pdf.js/web/viewer.js:12521:28
renderView@resource://pdf.js/web/viewer.js:8096:14
__webpack_modules__</forceRendering/<@resource://pdf.js/web/viewer.js:11023:29
promise callback*forceRendering@resource://pdf.js/web/viewer.js:11022:43
renderHighestPriority@resource://pdf.js/web/viewer.js:8003:24
update@resource://pdf.js/web/viewer.js:10849:25
_scrollUpdate@resource://pdf.js/web/viewer.js:10510:10
viewAreaElementScrolled@resource://pdf.js/web/viewer.js:197:15
FrameRequestCallback*debounceScroll@resource://pdf.js/web/viewer.js:179:18
EventListener.handleEvent*watchScroll@resource://pdf.js/web/viewer.js:209:19
PDFViewer@resource://pdf.js/web/viewer.js:9901:45
_initializeViewerComponents@resource://pdf.js/web/viewer.js:1886:22
initialize@resource://pdf.js/web/viewer.js:1691:16
async*run@resource://pdf.js/web/viewer.js:1988:10
webViewerLoad@resource://pdf.js/web/viewer.js:15370:29
EventListener.handleEvent*@resource://pdf.js/web/viewer.js:15378:12
@resource://pdf.js/web/viewer.js:15380:3
@resource://pdf.js/web/viewer.js:15382:12
```

Assessment:
No optional content configuration is passed when [rendering a tiling pattern](https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/canvas.js#L2470-L2475). This causes the exception when rendering tiling pattern content that is part of an "optional content group" layer on this line:

https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/canvas.js#L3140

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this isn't really actionable as-is. At the very least, the `Attach (recommended) or Link to PDF file here:`-part is always required.

**Comment by kmcclellan** [comment]
I've added what more info I can. I'm not licensed to share the PDF document. Handling nulls is definitely actionable, especially when you know why it is null (as I've explained here regarding tiling patterns).

**Comment by Snuffleupagus** [comment]
> PDF.js version: v3.0.201 (build: 39160c752)

Note that that's not an official release, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I'm not licensed to share the PDF document.

In general, please note that we don't want to make changes to code in the `src`-folder without being able to debug the PDF document *and* importantly to include tests in the patch. Otherwise it's just too easy for something to regress again, which could end up wasting time for everyone involved.

> Handling nulls is definitely actionable, especially when you know why it is null (as I've explained here regarding tiling patterns).

Sorry, but it's not clear (at least to me) that this on its own is actually enough to fully address the issue. It might also be necessary to e.g. provide the current `markedContentStack` to ensure that optional content is actually handled correctly, which isn't really possible to tell without a test-case unfortunately.

**Comment by kmcclellan** [comment]
@Snuffleupagus I was able to cook up a test PDF that exhibits this bug (see edited description). FWIW Adobe Reader doesn't appear to handle OC tags within tiled content correctly either (it renders the content, but doesn't toggle visibility). Foxit supports rendering and toggling visibility.
