### ISSUE TITLE
API to use ink tools

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#15712]
Is there an API to use the ink tools? For example a function that let us draw path or text with specific color, font and style.
I don't see ink functions in api.js and ink.js doesn't look like it is supposed to be used publicly.
https://github.com/mozilla/pdf.js/blob/master/src/display/api.js
https://github.com/mozilla/pdf.js/blob/master/src/display/editor/ink.js

**Comment by Snuffleupagus** [comment]
> Is there an API to use the ink tools? For example a function that let us draw path or text with specific color, font and style.

Similar to other pre-existing viewer layers, you'd need to initialize it and then set the necessary parameter like the viewer does. (Note though that the FreeText-editor only supports a default font family/style, so there's no choice there.)

> I don't see ink functions in api.js and ink.js doesn't look like it is supposed to be used publicly.

Please keep in mind that the editor tools are intended to be used as one more layer in the viewer (similar to the existing textLayer, annotationLayer, and xfaLayer), hence none of this functionality is really expected to show up in the core API (as found in the `src/display/api.js file).
To see how this is being initialized/used in the viewer, please see https://github.com/mozilla/pdf.js/blob/master/web/annotation_editor_layer_builder.js and https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js

**Comment by benbro** [comment]
Thank you for the links. The editor let you draw and add text to the pdf. When downloading the document the added annotations are included. I'm interested in the functions that add the path and text to the document and not in the pen and text UI widgets. Where can I find the path and text functions?

**Comment by Snuffleupagus** [comment]
*Please note:* What's described below (at a high level) should probably be regarded as mostly *internal* implementation details, and thus isn't something that you really want to rely too heavily upon since the format may change (if deemed necessary).

All annotations, be it form-data or editor-tools, are stored in the `AnnotationStorage`, see https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/display/api.js#L722-L727 and https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_storage.js

To save a modified document we invoke https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/display/api.js#L967-L973 which serializes the editor-tools with https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/display/editor/editor.js#L422-L431

On the worker-thread this is handled in https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/core/worker.js#L567-L584 which calls https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/core/document.js#L268-L321 and finally https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/src/core/annotation.js#L261-L301

**Comment by benbro** [comment]
Thank you for the information. I'll try to call the function to add an annotation. It will be useful to have such functions as a public stable api (feature request).

**Comment by benbro** [comment]
hi @Snuffleupagus. I'm trying to add annotations and save them with a document without using the viewer UI and editors.
The saveDocument handler in the worker converts the annotations to a plain JSON format. Is it possible to add annotations with this format and save them with the document?
https://github.com/mozilla/pdf.js/blob/3d49459d642e8dfbd11f1acab9a55118bee119f9/src/core/worker.js#L567
Annotation as json:
```json
{
    annotationType: 15,
    color: [0, 0, 0],
    opacity: 1,
    pageIndex: 0.
    paths: [{
        bezier: [...],
        points: [...]
    }],
    rect: [...],
    rotation: 0,
    thickness: 1
}```

**Comment by Snuffleupagus** [comment]
You might want to try something similar to our reference tests (although there's *no guarantees* about long-term stability):
 - https://github.com/mozilla/pdf.js/blob/fa54a587906100eb8198de2e95d6b1e0bfa88846/test/test_manifest.json#L6782-L6817
 - https://github.com/mozilla/pdf.js/blob/fa54a587906100eb8198de2e95d6b1e0bfa88846/test/driver.js#L673-L677

**Comment by benbro** [comment]
It's working thanks!
Will you accept a PR to add a function addAnnotation to api.js?

**Comment by Snuffleupagus** [comment]
> Will you accept a PR to add a function addAnnotation to api.js?

No, as already explained in https://github.com/mozilla/pdf.js/issues/15712#issuecomment-1321079511 this functionality doesn't belong in that file *and* adding official support for this somewhat special use-case doesn't seem great from an overall maintainability/support perspective.

**Comment by ghepardo82** [comment]
hi @benbro , could you post the full working code demonstrating how to programmatically add an annotation (which is then visible on the pdf?)

**Comment by VigneshSonaiya** [comment]
Hi @Snuffleupagus , I have tried the above solution but it seems like this not working as expected for me. Please find the code [here](https://jsfiddle.net/vigneshsv424/8ehn3caz/13/).
```
// atob() is used to convert base64 encoded PDF to binary-like data.
// (See also https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/
// Base64_encoding_and_decoding.)
var pdfData = atob(
  'JVBERi0xLjcKCjEgMCBvYmogICUgZW50cnkgcG9pbnQKPDwKICAvVHlwZSAvQ2F0YWxvZwog' +
  'IC9QYWdlcyAyIDAgUgo+PgplbmRvYmoKCjIgMCBvYmoKPDwKICAvVHlwZSAvUGFnZXMKICAv' +
  'TWVkaWFCb3ggWyAwIDAgMjAwIDIwMCBdCiAgL0NvdW50IDEKICAvS2lkcyBbIDMgMCBSIF0K' +
  'Pj4KZW5kb2JqCgozIDAgb2JqCjw8CiAgL1R5cGUgL1BhZ2UKICAvUGFyZW50IDIgMCBSCiAg' +
  'L1Jlc291cmNlcyA8PAogICAgL0ZvbnQgPDwKICAgICAgL0YxIDQgMCBSIAogICAgPj4KICA+' +
  'PgogIC9Db250ZW50cyA1IDAgUgo+PgplbmRvYmoKCjQgMCBvYmoKPDwKICAvVHlwZSAvRm9u' +
  'dAogIC9TdWJ0eXBlIC9UeXBlMQogIC9CYXNlRm9udCAvVGltZXMtUm9tYW4KPj4KZW5kb2Jq' +
  'Cgo1IDAgb2JqICAlIHBhZ2UgY29udGVudAo8PAogIC9MZW5ndGggNDQKPj4Kc3RyZWFtCkJU' +
  'CjcwIDUwIFRECi9GMSAxMiBUZgooSGVsbG8sIHdvcmxkISkgVGoKRVQKZW5kc3RyZWFtCmVu' +
  'ZG9iagoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDEwIDAwMDAwIG4g' +
  'CjAwMDAwMDAwNzkgMDAwMDAgbiAKMDAwMDAwMDE3MyAwMDAwMCBuIAowMDAwMDAwMzAxIDAw' +
  'MDAwIG4gCjAwMDAwMDAzODAgMDAwMDAgbiAKdHJhaWxlcgo8PAogIC9TaXplIDYKICAvUm9v' +
  'dCAxIDAgUgo+PgpzdGFydHhyZWYKNDkyCiUlRU9G');

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

// Using DocumentInitParameters object to load binary data.
var loadingTask = pdfjsLib.getDocument({data: pdfData});
loadingTask.promise.then(function(pdf) {
  console.log('PDF loaded', pdf);
    pdf.annotationStorage.setValue("edit1",  { 
     "annotationType": 3, 
     "color": [0, 0, 0], 
     "fontSize": 10, 
     "value": "Hello World", 
     "pageIndex": 0, 
     "rect": [67.5, 543, 119, 55.5], 
     "rotation": 0 
   })
		pdf.saveDocument();
  
  // Fetch the first page
  var pageNumber = 1;
  pdf.getPage(pageNumber).then(function(page) {
    console.log('Page loaded', page);
    
    var scale = 1.5;
    var viewport = page.getViewport({scale: scale});

    // Prepare canvas using PDF page dimensions
    var canvas = document.getElementById('the-canvas');
    var context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: context,
      viewport: viewport,
			annotationMode: 3,
    };
    var renderTask = page.render(renderContext);
    renderTask.promise.then(function () {
      console.log('Page rendered');
    });
  });
}, function (reason) {
  // PDF loading error
  console.error(reason);
});
```

**Comment by sinatayebati** [comment]
@VigneshSonaiya @ghepardo82 

If you guys are still seeking a solution to programmatically add annotations to PDFs and use the PDF.js viewer for rendering, I highly recommend checking out this repository: [pdfAnnotate](https://github.com/highkite/pdfAnnotate).

I experienced the same pain when needed to add annotations programmatically on the server side and display them on the client side, and this incredible work saved me.

For me, using the "AnnotationStorage" feature from PDF.js proved to be complex and nearly impossible to achieve. However, after discovering this repository, I found that it provided a straightforward solution. Its integration with PDF.js is seamless, making it incredibly easy to work with. Additionally, it offers a variety of annotation types and is extensively documented, making the entire process smooth and efficient.

**Comment by QuentinAndre11** [comment]
Hi @sinatayebati , I've seen you mentionned this library several times, but reading it I have a few questions if you could answer it: 
- how easy do you think it is to navigate between the annotations ? I have a right pannel with the list of the annotations like in Adobe Reader, I managed to bind the annotations from pdfjs to this panel and make them scroll if I click on the binded annotation or the navigation div, but I fear to do it again if I switch to pdfAnnotate
- the reason I want to switch is to be able to filter the annotations: it seems easier with PDFJS to make the annotations invisible and unprintable
- isn't it a problem that the last commit is from 2 years ago ? is it compatible with the last version of pdfjs ?
- is it suited for rectangle annotations filled with a low opacity ? I've not seen it in the options
Thanks a lot !

**Comment by sinatayebati** [comment]
@QuentinAndre11
Hi there. I just put together a demo in this [repo](https://github.com/sinatayebati/pdfjs-annotation) and tried to document integration of pdfAnnotate and PDFjs; I think you will find it helpful for your questions, so please take a look.

Following your questions, I couldn't quite understand your first question/concern, but bellow are my answers to the rest:
- with pdfAnnotate I was able to programmatically add highlight annotation with "hidden" flag.
- I don't think the last commit is a problem, the package worked perfectly for me and I even tested it in production with dedicated backend. But in case you want to open an issue, you won't probably get an answer from the developer.
- Yes, I have tried various annotation including rectangle with different colors and opacities.
