### ISSUE TITLE
Some PDF with Hebrew content doesnot display correctly

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#15719]
**Note : Sample document will be uploaded in couple of hrs after creating this ticket**
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: Chrome 107, Edge 107, Firefox 106
- Operating system and its version: Windows 11, Mac, 
- PDF.js version: 3.0.279
- Is a browser extension: NA

Steps to reproduce the problem:
1. Open document in pdfjs viewer and verify the content rendered. 
2. Open document in all latest browsers directly (might  be older ones too) and verify the content. 

What is the expected behavior? (add screenshot)
Content is expected to render as viewed in PDF acrobat reader
<img width="1382" alt="original" src="https://user-images.githubusercontent.com/86353329/203269850-5e433ff0-903f-4720-b3d9-6581ce5b158f.png">

What went wrong? (add screenshot)
<img width="946" alt="pdfjsrender" src="https://user-images.githubusercontent.com/86353329/203269885-8bf04478-6b65-4a7a-a01e-b55bf37cb6fb.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Gregory61V** [comment]
[Error 2 Wrong hebrew.pdf](https://github.com/mozilla/pdf.js/files/10075867/Error.2.Wrong.hebrew.pdf)
