### ISSUE TITLE
nextjs 13.0.3 Type error: Could not find a declaration file for module 'pdfjs-dist/build/pdf.worker.entry'. 'frontend_nextjs/node_modules/pdfjs-dist/build/pdf.worker.entry.js' implicitly has an 'any' type.        If the 'pdfjs-dist' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/build/pdf.worker.entry';`

### ISSUE THREAD

**Issue by learncodingforweb** [mozilla/pdf.js#15711]
Created nextjs 13.0.3 app with typescript enabled. installled "pdfjs-dist": "^3.0.279" and added following line of code

import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf'
// import PDFJSWorker from 'pdfjs-dist/legacy/build/pdf.worker.entry'
import PDFJSWorker from 'pdfjs-dist/build/pdf.worker.entry'

pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJSWorker

_typescript gives error_
**Could not find a declaration file for module 'pdfjs-dist/build/pdf.worker.entry'. 'frontend_nextjs/node_modules/pdfjs-dist/build/pdf.worker.entry.js' implicitly has an 'any' type.
  If the 'pdfjs-dist' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/build/pdf.worker.entry';`ts(7016)**

Configuration:
- Web browser and its version:  firefox 107.0 & chrome 107.0.5304.107
- Operating system and its version: windows 10 
- PDF.js version:  2022.003.20263

Steps to reproduce the problem:
1.  not able to build nextjs app using "pdfjs-dist": "^3.0.279",
2. npm run build giving
**Type error: Could not find a declaration file for module 'pdfjs-dist/build/pdf.worker.entry'. frontend_nextjs/node_modules/pdfjs-dist/build/pdf.worker.entry.js' implicitly has an 'any' type.     
  If the 'pdfjs-dist' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/build/pdf.worker.entry';`**

npm run build should generate build output

**Comment by Snuffleupagus** [comment]
> Created nextjs 13.0.3 app with typescript enabled.

Sorry, but we're not really able to provide help/support for the plethora of JS frameworks that exist (since we don't use them here).

In general, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
