### ISSUE TITLE
PDF is not render when multiple canvas instances and rotation is being applied

### ISSUE THREAD

**Issue by fjtrujy** [mozilla/pdf.js#15723]
[element.pdf](https://github.com/mozilla/pdf.js/files/10067049/element.pdf)

Configuration:
- Web browser and its version: `Firefox 107.0 (64-bit)`, `Chrome Version 107.0.5304.110 (Official Build) (arm64)`
- Operating system and its version: `macOS Montery 12.6`
- PDF.js version: `3.0.279`
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a "matrix" using several canvas instances
2. Render the pdf partially in every single canvas
3. Apply rotation to the context before render the pdf item

What is the expected behavior? (add screenshot)
The whole PDF item should be properly rendered with proper rotation being applied.

What went wrong? (add screenshot)
The PDF is not being renderer in some canvases, usually the canvases in the left side
<img width="685" alt="Screenshot 2022-11-22 at 12 54 11" src="https://user-images.githubusercontent.com/10010409/203307677-7ab5147c-1551-468e-af8e-747a17151068.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I have created the next `jsfiddle` where the problem is reproducible:
https://jsfiddle.net/fjtrujy/1b62jLgr/1/

**Comment by Snuffleupagus** [comment]
Sorry, but we don't really support *manually* specifying canvas properties like that.

 - Please note how the `getViewport` method accepts a rotation argument https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/api.js#L1049-L1062 and https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/api.js#L1283-L1294
 - Furthermore, the `render` method also accepts a custom transform argument https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/api.js#L1128-L1172 and https://github.com/mozilla/pdf.js/blob/748be3f70215817ef5e4eeeec412556fef31908c/src/display/api.js#L1344-L1363

**Comment by fjtrujy** [comment]
That was my original approach, however, you're just supporting rotation of `0, 90, 180, 270 or 360`

https://github.com/mozilla/pdf.js/blob/2d1b1e79685bc9c432395c612b6562dc76898486/src/display/display_utils.js#L181-L215

So I can't use the rotation of the GetViewportParameters

**Comment by pedrovgs** [comment]
@Snuffleupagus , is there any workaround we can use in order to get a rotated PDF with 10 degrees for example? We need to render different tiles at the same time and the lack of custom rotation angles doesn't let us implement this feature, but maybe there is a workaround we can use. Thanks!

**Comment by Snuffleupagus** [comment]
> is there any workaround we can use in order to get a rotated PDF with 10 degrees for example?

Sorry, but we unfortunately don't support arbitrary rotation since that's not necessary for the default use-case (i.e. the Firefox PDF Viewer).

**Comment by fjtrujy** [comment]
> > is there any workaround we can use in order to get a rotated PDF with 10 degrees for example?
> 
> Sorry, but we unfortunately don't support arbitrary rotation since that's not necessary for the default use-case (i.e. the Firefox PDF Viewer).

Using the `transform` property, will it ideally work in all the scenarios? even having rotation in that transform?
I have tried doing the next, and still is not working fine
```js
// Render PDF page into canvas context
var renderContext = {
  canvasContext: ctx,
  viewport: viewport,
  background: "#0000FF",
  transform: [3.051900863647461, -1.2326576709747314, 1.2326576709747314, 3.051900863647461, 74.35530853271484, 393.8739929199219]
};
var renderTask = page.render(renderContext);
```

https://jsfiddle.net/fjtrujy/1b62jLgr/5/

**Comment by fjtrujy** [comment]
I have improved the `jsfiddle` that I was using, making sure that we don't do any transform to the canvas before the PDF is render.

```js
function renderPage(id, transform) {
	var canvas = document.getElementById(id);
  var ctx = canvas.getContext('2d');
  
  // Using promise to fetch the first page
  pdfDoc.getPage(1).then(function(page) {
    var viewport = page.getViewport({scale: 1.0});

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: ctx,
      viewport: viewport,
      background: "#0000FF",
      transform: transform
    };
    var renderTask = page.render(renderContext);

    // Wait for rendering to finish
    renderTask.promise.then(function() {
      console.log(`Finished rendering canvas ${canvas.id}`)
    });
  });
}

/**
 * Asynchronously downloads PDF.
 */
pdfjsLib.getDocument(url).promise.then(function(pdfDoc_) {
  pdfDoc = pdfDoc_;
  
  renderPage("DBB0022A-17CD-4544-81D5-CD2A3D2B0EBB", [26.22182, -10.59095, 10.59095, 26.22182, -1408.1418, 1337.1511]);
  renderPage("24F935F6-B043-4A48-ABDB-57C69CE7BEB1", [26.22182, -10.59095, 10.59095, 26.22182, -3455.1418, -709.8489]);
  renderPage("90B922A5-BA8C-4AC4-B554-3B2E00486640", [26.22182, -10.59095, 10.59095, 26.22182, -1408.1418, -709.8489]);
  renderPage("30307787-EE5C-4FDA-BD6A-0A04EE146621", [26.22182, -10.59095, 10.59095, 26.22182, 638.8582, -709.8489]);
  renderPage("B11D9151-99F0-4D34-9D55-01B7FF763613", [26.22182, -10.59095, 10.59095, 26.22182, 638.8582, 1337.1511]);
  renderPage("2AA32085-780B-4BC8-8A84-21F69205AB53", [26.22182, -10.59095, 10.59095, 26.22182, -3455.1418, 1337.1511]);
});
```

And the result is still the same
<img width="748" alt="Screenshot 2022-12-01 at 10 56 06" src="https://user-images.githubusercontent.com/10010409/205022910-0f4a57e0-489d-4f01-8899-16016ad1ab47.png">

@Snuffleupagus, here you have the newer `jsfiddle`, is that still the expected behavior?

https://jsfiddle.net/fjtrujy/1b62jLgr/44/

Cheers
