### ISSUE TITLE
Why does pdf.js convert http headers to lowercase?

### ISSUE THREAD

**Issue by berzi** [mozilla/pdf.js#15726]
Attach (recommended) or Link to PDF file here: [not relevant]

Configuration:
- Web browser and its version: Firefox Dev edition 108.0b4 (64-bit)
- Operating system and its version: Win11
- PDF.js version: pdfjs-dist 2.12.313
- Is a browser extension: no

Steps to reproduce the problem:
1. add the `httpHeaders` parameter with at least one header with a capitalised key (e.g. `Authorization` or `Access-Control-Allow-Origin`)
2. look at what the request actually sends

What is the expected behavior?
The headers should be sent exactly as provided.

What went wrong?
The header keys are lowered.

![image](https://user-images.githubusercontent.com/32619123/203344474-16d95537-6818-43cd-9fb5-89d87e8c334c.png)

Note how the two headers I provided are lowercase, despite me providing them as `Authorization` and `Access-Control-Allow-Origin` respectively, while other headers that were automatically added to the request have the expected casing.

I'm having trouble with CORS headers and I don't know whether this is relevant, but I don't see any possible advantage in changing the case the user provides. In the event the browser or server expects specific case-sensitive keys this breaks the feature without providing the user for any way out, bar finding an alternative library to use.

**Comment by Snuffleupagus** [comment]
> PDF.js version: pdfjs-dist 2.12.313

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Note how the two headers I provided are lowercase, despite me providing them as `Authorization` and `Access-Control-Allow-Origin` respectively, while other headers that were automatically added to the request have the expected casing.

Please note that we *do not* touch the casing at all in the PDF.js code-base, but simply use functionality provided by the web-platform itself to create the headers; see either:
 - https://github.com/mozilla/pdf.js/blob/a0db81723bfcba59d6ba961ff95919660587eb6f/src/display/fetch_stream.js#L45-L55 which uses https://developer.mozilla.org/en-US/docs/Web/API/Headers
 - https://github.com/mozilla/pdf.js/blob/a0db81723bfcba59d6ba961ff95919660587eb6f/src/display/network.js#L83-L89 which uses https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader
