### ISSUE TITLE
Text selection issues

### ISSUE THREAD

**Issue by jeager** [mozilla/pdf.js#15733]
There is a huge problem in text selection that was a bit smoother with `enhanceTextSelection`. Now that it's gone, is there any intention of working on enhancing this? It's clearly problematic to select any text where there are white spaces in the document.

The example I show is a good PDF in the demo provided by the lib itself, other PDFs tend to go even worse behavior.

Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome Version 107.0.5304.87 (Official Build) (x86_64)
- Operating system and its version: MacOS 12.6
- PDF.js version: 3.1.71 (the one provided in the site demo https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1. Try to highlight anything passing through empty areas

What is the expected behavior? (add screenshot)
To not start selecting random portions of text.

What went wrong? (add screenshot)
![Screen Recording 2022-11-23 at 17 11 20](https://user-images.githubusercontent.com/1682249/203638232-c40783b5-e651-4f45-b55c-7d85d95836b6.gif)

**Comment by marcelodlr** [comment]
I noticed the same problem. Is there a workaround for this issue or is there a plan to fix it ?

**Comment by Phero49** [comment]
how did you solve this issue  please help
