### ISSUE TITLE
One PDF that does not render in iOS 16

### ISSUE THREAD

**Issue by garysmith058** [mozilla/pdf.js#15734]
Attach (recommended) or Link to PDF file here:

https://d20u00k0k1e74s.cloudfront.net/test/cv_200605.pdf

Configuration:
- Web browser and its version:

Safari iOS 16

- Operating system and its version:

iOS 16.1.1, iPhone 13

- PDF.js version:

Current version on demo page

- Is a browser extension:

No

Steps to reproduce the problem:

1. Download the above file to iPhone running iOS 16.
2. Open the demo viewer page at https://mozilla.github.io/pdf.js/web/viewer.html in Safari.
3. Open the pdf.
4. Page locks up.

What is the expected behavior? (add screenshot)

PDF renders OK.

What went wrong? (add screenshot)
![IMG_0064](https://user-images.githubusercontent.com/8452207/203667756-4c41b0db-a723-450f-8c47-f3cc64dce95d.PNG)

The page locks up at some stage during rendering. Stops at different places on different loads. Renders correctly on IOS 15, iPad, Android and desktop browsers. Other pdfs load correctly.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by untouch** [comment]
We have the same problem,, but with version 2.
Sometimes the pdf does not render at all.

We will try to update the version to solve the problem

**Comment by Snuffleupagus** [comment]
WFM, using Firefox Nightly 109 on Windows.

> Configuration:
>     Web browser and its version: Safari iOS 16
>     Operating system and its version: iOS 16.1.1, iPhone 13
> [...]
> The page locks up at some stage during rendering. Stops at different places on different loads. Renders correctly on IOS 15, iPad, Android and desktop browsers. Other pdfs load correctly.

This unfortunately suggests a bug in the *browser itself* (and possibly even a regression), rather than a general issue PDF.js issue, since otherwise you'd really expect it to be consistently broken everywhere.
Given that our focus is on developing the Firefox PDF Viewer this unfortunately doesn't look actionable/fixable here, and it'd probably be better to report this to the Safari developers.

**Comment by MattL75** [comment]
@garysmith058 Did you end up reporting it anywhere? We are encountering the same problem with different documents and would be interested in tracking/upvoting any ticket filed

**Comment by garysmith058** [comment]
No, I didn't. Only found one PDF that showed the problem. But if there are
others, it should be reported.
