### ISSUE TITLE
Serach text getting highlighted incorrectly in viewer.html

### ISSUE THREAD

**Issue by Yash7032** [mozilla/pdf.js#15736]
Steps to reproduce:
1. Browse the below link
https://mozilla.github.io/pdf.js/web/viewer.html
2. Search for the text "edu" and it will highlight the text incorrectly. PFB screenshot
<img width="916" alt="image" src="https://user-images.githubusercontent.com/118966146/203728940-5be7847b-c0c3-4732-a337-ce82c633f5b4.png">

**Comment by Snuffleupagus** [comment]
WFM, in Firefox Nightly 109 on Windows.

Given that you've ignored the `Configuration:`-section of the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md), this issue unfortunately isn't actionable.
