### ISSUE TITLE
Lazy load not work.

### ISSUE THREAD

**Issue by GitHubWesley** [mozilla/pdf.js#15737]
One of the pdf I provide doesn't support lazy load, could you please help on that?

Attach (recommended) or Link to PDF file here:

[pdf-not-support-lazy-load.pdf](https://datacapturestagingv2.blob.core.windows.net/daisy-bkssummarizertask-formatter-staging/pdf-not-support-lazy-load.pdf?sv=2020-04-08&st=2022-11-24T08%3A44%3A06Z&se=2023-11-25T08%3A44%3A00Z&sr=b&sp=r&sig=kRL5ZH5Zn%2FL%2FKRqG2nYrS9CCRIAiQ4pA3JfgMJraCAM%3D)

[pdf-support-lazy-load.pdf](https://datacapturestagingv2.blob.core.windows.net/daisy-bkssummarizertask-formatter-staging/pdf-support-lazy-load.pdf?sv=2020-04-08&st=2022-11-24T08%3A44%3A59Z&se=2023-11-25T08%3A44%3A00Z&sr=b&sp=r&sig=hIehrQkiFPW%2BS9OQUKSBt4ctxs8Mg9cUx7lKBS3OciU%3D)

Configuration:
- Web browser and its version: Chrome 107.0.5304.107
- Operating system and its version: Windows 10
- PDF.js version: v3.0.279
- Is a browser extension: No

Steps to reproduce the problem:
1. Load and compare the lazy load behavior

What is the expected behavior? (add screenshot)

Both Pdf could support lazy load.

What went wrong? (add screenshot)

pdf-not-support-lazy-load.pdf doesn't support lazy load.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The difference between the two documents seem to be two-fold:
 - Different location/type of the /XRef tables.
 - Different file layout, of e.g. the /Pages dictionary.

Please keep in mind that the structure of the PDF document itself needs to be such that lazy-loading works, and in some cases we simply can't compensate for a "bad" internal document structure.

**Comment by GitHubWesley** [comment]
> The difference between the two documents seem to be two-fold:
> 
> * Different location/type of the /XRef tables.
> * Different file layout, of e.g. the /Pages dictionary.
> 
> Please keep in mind that the structure of the PDF document itself needs to be such that lazy-loading works, and in some cases we simply can't compensate for a "bad" internal document structure.

@Snuffleupagus Could you please give some advice about what should I do to make the [pdf-not-support-lazy-load.pdf](https://datacapturestagingv2.blob.core.windows.net/daisy-bkssummarizertask-formatter-staging/pdf-not-support-lazy-load.pdf?sv=2020-04-08&st=2022-11-24T08%3A44%3A06Z&se=2023-11-25T08%3A44%3A00Z&sr=b&sp=r&sig=kRL5ZH5Zn%2FL%2FKRqG2nYrS9CCRIAiQ4pA3JfgMJraCAM%3D) could support lazy load? I can try to optimize the PDF which doesn't support lazy load. Really thanks for your support!
