### ISSUE TITLE
Broken fonts

### ISSUE THREAD

**Issue by Fssd1** [mozilla/pdf.js#15738]
Attach (recommended) or Link to PDF file here:
[bug.pdf](https://github.com/mozilla/pdf.js/files/10083159/bug.pdf)

Configuration:
- Web browser and its version: Firefox ESR 102
- Operating system and its version: Windows 10
- PDF.js version: https://mozilla.github.io/pdf.js/legacy/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached PDF
2. On page 3 some fonts are broken.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
> On page 3 some fonts are broken.
> What is the expected behavior? (add screenshot)

This requested screen-shot is unfortunately missing here...

---

WFM, using Firefox Nightly 109 on Windows:

![page3](https://user-images.githubusercontent.com/2692120/203752505-78ba2782-fc19-417e-9c1f-0f8e0e52a04a.png)
