### ISSUE TITLE
Text overlap in W-4 form

### ISSUE THREAD

**Issue by Hello71** [mozilla/pdf.js#1574]
http://www.irs.gov/pub/irs-pdf/fw4.pdf

Don't see any errors in Error Console though.

**Comment by pauldavidson** [comment]
anyone needs to fill out a  <a href="http://www.pdffiller.com/100283892-W-42014pdf-Fillable-Form-W-4-2014-" >IRS form W-4</a>, I found a blank form in this site PDFfiller. This site also has several related tax forms that you might find useful.
