### ISSUE TITLE
Returns the position of the previous ink text when scrolling to the next page

### ISSUE THREAD

**Issue by 123woscc** [mozilla/pdf.js#15744]
Attach (recommended) or Link to PDF file here:

demo pdf: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:
- Web browser and its version: chrome (107.0.5304.107)
- Operating system and its version: windows 10
- PDF.js version: v3.0.279 [Latest](https://github.com/mozilla/pdf.js/releases/latest)

Steps to reproduce the problem:
1. add ink text to the page.
2. scroll to next page.

What is the expected behavior? (add screenshot)
view next page:
![image](https://user-images.githubusercontent.com/13806929/203939711-c9b5a3b8-e9cc-4f26-8e5b-592a0e7d17cd.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/13806929/203942746-106e9d18-f47b-4812-933b-72c808f77b1a.png)
![GIF 2022-11-25 17-04-23](https://user-images.githubusercontent.com/13806929/203942804-bebc1be6-d5f6-4de4-b4d6-e70d1daaaefe.gif)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
@calixteman Any ideas about this one?

**Comment by calixteman** [comment]
I wonder how I missed this bug report...
