### ISSUE TITLE
How to render single page at time with next/previous option using pdfjs-dist/web/pdf_viewer

### ISSUE THREAD

**Issue by rahulgupta-dev** [mozilla/pdf.js#15743]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 107.0.5304.107 
- Operating system and its version: window 11 64bit
- PDF.js version: "pdfjs-dist": "^2.0.943"
- Is a browser extension: No

Steps to reproduce the problem:
1.  Create a pdf render using pdfjs-dist/web/pdf_viewer
2. I am following the [mobile-viewer example](https://github.com/mozilla/pdf.js/blob/master/examples/mobile-viewer/viewer.js)

**What is the expected behavior?**

Expected behavior is to render one page per view then on next render next page, instead of render all page in single view with scroll.

**What went wrong?**

All page is rendered in single view with scroll.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * PDF.js version: "pdfjs-dist": "^2.0.943"

That version is *four years old*, please update to a supported release before reporting a bug or asking for help; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Expected behavior is to render one page per view then on next render next page, instead of render all page in single view with scroll.

See e.g. https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js

**Comment by rahulgupta-dev** [comment]
@Snuffleupagus Thanks for the help, next time will take care to update to latest version. Thanks again.
