### ISSUE TITLE
Still Broken fonts

### ISSUE THREAD

**Issue by Fssd1** [mozilla/pdf.js#15748]
@Sterzz, @Snuffleupagus

Fonts are still broken:
https://github.com/mozilla/pdf.js/files/10083159/bug.pdf

**Comment by Snuffleupagus** [comment]
Duplicate of #15738.

---

Please don't open yet another *incomplete* issue, since you've unfortunately not provided enough information to clearly explain the problem; please note e.g. https://github.com/mozilla/pdf.js/issues/15738#issuecomment-1326208230.
