### ISSUE TITLE
Large file render slowly and confused range request.

### ISSUE THREAD

**Issue by Gakki-f** [mozilla/pdf.js#15754]
Attach (recommended) or Link to PDF file here:
https://drive.google.com/file/d/17K-xn1hCAA1wzoG69DnfXhScfK1XrXr5/view?usp=sharing

Configuration:
- Web browser and its version: Chrome Firefox Safari
- Operating system and its version: mac m1 12.6 
- PDF.js version: 2.2.228

Steps to reproduce the problem:
```javascript
const loadingTask = this.getDocument({
    url,
    disableStream: true,
    disableAutoFetch: true,
})
 loadingTask.promise.then(function (pdf) {
   pdf.getPage(1).then(function (page) {
    // Simple codes draw canvas...
    const context = canvas.getContext('2d')
    const scale = (vm.viewerWidth / 2 /  viewport.width).toFixed(2)
    const scaledViewport = page.getViewport({
      scale: scale * 2
    })
    const renderContext = {
      canvasContext: context,
      viewport: scaledViewport
    }
    const renderTask = page.render(renderContext)
    renderTask.promise.then(function (e) {
        // Here, the end of render is very slow
    }
  }
}
```

What is the expected behavior? 

Render quickly. Or reasonable range request.

What went wrong? 

We are loading the pdf in pages.
As the second page has 37mb, resulting in a very slow loading, also its range request is also very strange, with the default chunkSize: 64kb but it is the last fetch has 37.2mb.
Try to use cdn to introduce pdfjs but the result is the same, in chrome safari Firefox result is also the same fetch is very slow.
What do you suggest? Thanks!
<img width="757" alt="api1" src="https://user-images.githubusercontent.com/52447748/204242096-d2d219f5-c345-45eb-93a9-23ce37804f82.png">

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.2.228

That version is over *three years old* and thus no longer supported, please update to a supported release before reporting a bug or asking for help; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
