### ISSUE TITLE
how to view binary pdf input from api in the viewer

### ISSUE THREAD

**Issue by Starter3** [mozilla/pdf.js#15766]
I built the viewer app and used the generic(build) folder as asset in my Angular project. Embeding the viewer in my angular project works fine, after mimicking the html in the component. I can view a pdf file by passing query string as "file", but how can I feed a pdf file input to the viewer, from an API that responds pdf as binary response.

**Comment by Snuffleupagus** [comment]
*For future reference:* Please always fill out the [ISSUE TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.

Refer to the last two paragraphs in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

Finally, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
