### ISSUE TITLE
Search in newer versions

### ISSUE THREAD

**Issue by raheelqader** [mozilla/pdf.js#15777]
New to pdf.js, I realized that search functionality was working fine in older version using:

```
pdfFindController.executeCommand("find", { query: "my search query", phraseSearch: true, highlightAll: false, entireWord: false, findPrevious: false, caseSensitive: false });
```

however, in the new versions,  `executeCommand` has been deprecated and the suggested method as shown below doesn't work, any ideas?
```
pdfViewer.eventBus.dispatch("find", { type: "", query: "my search query" });
```

Attach (recommended) or Link to PDF file here: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: chrome 106.0.5249.119
- Operating system and its version: ubuntu 20.04
- PDF.js version: 3.1.81

**Comment by Snuffleupagus** [comment]
See e.g. https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js and if that doesn't help please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by ollita7** [comment]
Why this is closed? It is happening exactly the same for me.
