### ISSUE TITLE
When annotaion exceeds 10 pages, print and download are abnormal

### ISSUE THREAD

**Issue by OnlY0226** [mozilla/pdf.js#15780]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:
- Web browser and its version: Google 版本 104.0.5112.79（正式版本） （64 位）
- Operating system and its version: linux
- PDF.js version: v3.0.279
- Is a browser extension:

Steps to reproduce the problem:
1. add annotation on page 1
2. add annotation on page 11
3. print

What is the expected behavior? (add screenshot)
print with annotation
What went wrong? (add screenshot)
report error：
editor.js:298 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'viewportBaseDimensions')
    at InkEditor.getRect (editor.js:298:53)
    at InkEditor.serialize (ink.js:1065:23)
    at get serializable [as serializable] (annotation_storage.js:168:47)
    at new PrintAnnotationStorage (annotation_storage.js:204:49)
    at get print [as print] (annotation_storage.js:153:12)
    at app.js:1683:52
    at async Promise.all (index 1)
![image](https://user-images.githubusercontent.com/55518632/205529553-de262fa9-392c-4c43-8fd9-1edae67b8997.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
Naively, it seems to me that we should probably `serialize` the applicable editors when destroying the layer in https://github.com/mozilla/pdf.js/blob/67e1c37e0fea06951ece8c457c2b39d2ee2a683f/src/display/editor/annotation_editor_layer.js#L513-L530
Similarly, we should probably `deserialize` any applicable editors when re-constructing the layer in https://github.com/mozilla/pdf.js/blob/67e1c37e0fea06951ece8c457c2b39d2ee2a683f/src/display/editor/annotation_editor_layer.js#L64-L82

/cc @calixteman, @marco-c This seems like a pretty serious usability issue, and it's *possible* that this is also the same bug as outlined in https://www.reddit.com/r/firefox/comments/yxlgx3/how_to_actually_save_an_edited_pdf/
