### ISSUE TITLE
How to support SourceHanSans on UOS browser ?

### ISSUE THREAD

**Issue by baofeidyz** [mozilla/pdf.js#15781]
I try to fix the problem that [SourceHanSans](https://github.com/adobe-fonts/source-han-sans) font cannot display some Chinese characters on [UOS Browser](https://home.uniontech.com), I am confused about the version of pdfjs I am using, sorry for not being able to report more details about pdfjs.

I found the [question](https://stackoverflow.com/questions/32764773/what-is-a-pdf-bcmap-file), trying to run "npm run build" to convert the [UniSourceHanSansCN-UTF32-H cmap file](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansCN-UTF32-H) to the bcmap file.
I checked the file path and set PDFJS.cMapPacked to false or true, all failed. I don't get the expected bcmap file.

Actually, I don't know that converting this file will help me solve the problem.So, any help would be great for me, thanks a lot.

**Comment by Snuffleupagus** [comment]
> I am confused about the version of pdfjs I am using, sorry for not being able to report more details about pdfjs.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since the complete lack of details makes it *impossible* for anyone to assist you!

> on [UOS Browser](https://home.uniontech.com)

That's not browser that we support here, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> I found the [question](https://stackoverflow.com/questions/32764773/what-is-a-pdf-bcmap-file), trying to run "npm run build" to convert the [UniSourceHanSansCN-UTF32-H cmap file](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansCN-UTF32-H) to the bcmap file.
> I checked the file path and set PDFJS.cMapPacked to false or true, all failed. I don't get the expected bcmap file.

It's not even clear, given that you didn't actually including the PDF document in question (which is the *first* thing that the ISSUE_TEMPLATE asks for), if this step is necessary/relevant to do here...

> Actually, I don't know that converting this file will help me solve the problem.

And neither does anyone else unfortunately; finally please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by baofeidyz** [comment]
> > I am confused about the version of pdfjs I am using, sorry for not being able to report more details about pdfjs.
> 
> When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since the complete lack of details makes it _impossible_ for anyone to assist you!
> 
> > on [UOS Browser](https://home.uniontech.com)
> 
> That's not a browser that we support here, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
> 
> > I found the [question](https://stackoverflow.com/questions/32764773/what-is-a-pdf-bcmap-file), trying to run "npm run build" to convert the [UniSourceHanSansCN-UTF32-H cmap file](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansCN-UTF32-H) to the bcmap file.
> > I checked the file path and set PDFJS.cMapPacked to false or true, all failed. I don't get the expected bcmap file.
> 
> It's not even clear, given that you didn't actually including the PDF document in question (which is the _first_ thing that the ISSUE_TEMPLATE asks for), if this step is necessary/relevant to do here...
> 
> > Actually, I don't know that converting this file will help me solve the problem.
> 
> And neither does anyone else unfortunately; finally please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> 
> > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

First of all thanks for your reply. I'm sorry about couldn't upload any files and not used ISSUE_TEMPLATE. 

Second, if anyone knows how to convert a cmap file to a bitmap file, it might help me to solve my problem, please reply.

**Comment by baofeidyz** [comment]
# Steps to convert [UniSourceHanSansCN-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansCN-UTF32-H) to bcmap file

Download this repo to your local.

```shell
git clone git@github.com:mozilla/pdf.js.git
cd pdf.js
npm install -g gulp-cli
npm install
```

Then put your cmap file into the CMAP_INPUT folder.

```shell
mkdir -p external/cmaps
mv YOUR_CMAP_FILE external/cmaps
gulp cmaps
```

---
FAQ You may need:
1. no cmap files
```
### Building cmaps error
./external/cmaps has no cmap files, download them from:
  https://github.com/adobe-type-tools/cmap-resources
[10:24:23] 'cmaps' errored after 2.16 ms
[10:24:23] Error: cmap files were not found
    at ....../pdf.js/gulpfile.js:830:11
    at taskWrapper (....../pdf.js/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (....../pdf.js/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

You need to change [gulpfile.js](https://github.com/mozilla/pdf.js/blob/master/gulpfile.js#L827) to set the filename `/UniJIS-UCS2-H` to your setup, or just delete it.

2. How to find the cmap file ?

In this case, just visit this github repo to download:
- [UniSourceHanSansCN-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansCN-UTF32-H)
- [UniSourceHanSansHK-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHK-UTF32-H)
- [UniSourceHanSansHWCN-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHWCN-UTF32-H)
- [UniSourceHanSansHWHK-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHWHK-UTF32-H)
- [UniSourceHanSansHWJP-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHWJP-UTF32-H)
- [UniSourceHanSansHWKR-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHWKR-UTF32-H)
- [UniSourceHanSansHWTW-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansHWTW-UTF32-H)
- [UniSourceHanSansJP-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansJP-UTF32-H)
- [UniSourceHanSansKR-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansKR-UTF32-H)
- [UniSourceHanSansTW-UTF32-H](https://github.com/adobe-fonts/source-han-sans/blob/master/UniSourceHanSansTW-UTF32-H)

Or you can create your own. Cmap file created by adobe, if you need more information, click this [link](https://github.com/adobe-fonts/source-han-sans/issues/40).
