### ISSUE TITLE
Annotations are on Wrong Position after Saving/Downloading

### ISSUE THREAD

**Issue by dki030** [mozilla/pdf.js#15789]
Attach (recommended) or Link to PDF file here: [sample_pdf.pdf](https://github.com/mozilla/pdf.js/files/10175112/sample_pdf.pdf)

Configuration:
- Web browser and its version: Chrome 108 (Firefox too)
- Operating system and its version: Windows
- PDF.js version: 3.1.81
- Is a browser extension: no

Steps to reproduce the problem:
1. open viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached PDF
3. Use ink editor or add annotations
4. Save/Download PDF
5. Open Again

What is the expected behavior? (add screenshot)

After saving (and opening the document again), all annotations should be on the same position as before.

![Before](https://user-images.githubusercontent.com/120009095/206154268-947e7b3d-24bc-46b3-b265-977f6b471fb5.png)

What went wrong? (add screenshot)

![After](https://user-images.githubusercontent.com/120009095/206154300-d18a922b-6e0c-45e3-9c50-bc7a4e454495.png)

**Comment by Snuffleupagus** [comment]
My guess is that it's related to the `/MediaBox [-9, -9, 604.28, 850.89]` entry, so we probably need to take non-zero start coordinates into account in the editor as well (similar to how its done in the annotationLayer).
