### ISSUE TITLE
Text in PDF missing

### ISSUE THREAD

**Issue by Faelean** [mozilla/pdf.js#15784]
Attach (recommended) or Link to PDF file here:
[RE93815363.pdf](https://github.com/mozilla/pdf.js/files/10154659/RE93815363.pdf)

Configuration:
- Web browser and its version: Chrome Version 108.0.5359.95 (Offizieller Build) (64-Bit)
- Operating system and its version: Windows 10 21H2
- PDF.js version: Current nightly (3.2.37 [99cfef882]) and 3.0.279 [d0823066c]
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/7944797/205653925-a7be07fd-0ebd-4838-a400-1e672a1b0fed.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/7944797/205654039-42be0540-77c6-4420-b17c-d074f9836034.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment]
There are some wrong commands 9 in the char strings which are causing this issue.
In replacing them by a 32, it fixes the issue but then we've a number in the middle of the commands which is wrong (but at least the sanitizer doesn't complain that much).
We should probably generate a new char strings data where the wrong commands would have been stripped out (I didn't find any no-op commands in the docs for CFF fonts).
