### ISSUE TITLE
Compressed pdf.worker.min.js works with errors

### ISSUE THREAD

**Issue by idaicu** [mozilla/pdf.js#15790]
Hello,
I've downloaded prebuilt legacy (Stable v3.1.81) from _https://mozilla.github.io/pdf.js/getting_started/_ and integrated in my web app and it works ok. But I'd like to use minified version of JS code.

Configuration:
- Browser Chrome 108
- Windows 10
- PDF.js version 3.1.81

The problem begins when I use _legacy/pdf.worker.min.js_ file instead of _pdf.worker.js_ (downloaded from https://www.jsdelivr.com/package/npm/pdfjs-dist).
Steps to reproduce the problem:
1. Replace pretty code of _build/pdf.worker.js_ with code from https://cdn.jsdelivr.net/npm/pdfjs-dist@3.1.81/legacy/build/pdf.worker.min.js
2. Restart web app
3. Open any PDF file with text

Expected:
![image](https://user-images.githubusercontent.com/14142296/206243913-03b6c4db-94fe-434a-8778-35b157a49fb0.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/14142296/206243198-8efbc51e-8686-4ec9-bd89-dec6ba910dfc.png)
1. Text is unreadable
2. Console warning: OTS parsing error: head: Failed to parse table

Please help to use minified code in my app.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by idaicu** [comment]
Hello,
I've tried to solve the problem by building the source code by gulp (https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified)
But also get the same error very similar to https://github.com/mozilla/pdf.js/issues/8960

Any help is appreciated.
Best regards, Ivan

**Comment by Snuffleupagus** [comment]
I tried to following, in a local clone of the PDF.js library[1]:
 - Run `gulp minified`
 - Run `gulp server`
 - Open http://localhost:8888/build/minified/web/viewer.html in a browser (Firefox Nightly in my case).

That worked just fine, hence this is unfortunately *still* not actionable; hence:
 - Please provide the PDF document that you're testing with (which is the *first thing* that we ask for in the ISSUE_TEMPLATE).
 - Please follow https://github.com/mozilla/pdf.js/issues/15790#issuecomment-1341317016 such that it's possible to test *exactly* the same configuration that you're using.

---
[1] This assumes that you've followed https://github.com/mozilla/pdf.js#getting-the-code first.

**Comment by idaicu** [comment]
Hello,

I've tried everything from your suggestion and it worked **fine**.. until I've deployed it to my **tomcat 9.0.62**.

I found solution by adding [BOM ](https://en.wikipedia.org/wiki/Byte_order_mark) to the **pdf.worker.min.js**.
Any comments?

Best Regards,
Ivan
