### ISSUE TITLE
Example PDF not working

### ISSUE THREAD

**Issue by weary-adventurer** [mozilla/pdf.js#15803]
Attach (recommended) or Link to PDF file here:
- [ocg.pdf](https://github.com/mozilla/pdf.js/files/10200431/ocg.pdf) (from https://pdfium.googlesource.com/pdfium_tests/+/refs/heads/main/fx/layer/ocg.pdf)

Configuration:
- PDF.js version: PDF.js v3.2.62 (build: 9d4aadbf7)
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Drag and drop [ocg.pdf](https://github.com/mozilla/pdf.js/files/10200431/ocg.pdf)

What is the expected behavior? (add screenshot)
- The PDF file opens.

Chrome 101:

![image](https://user-images.githubusercontent.com/30081929/206864610-4fb00a3e-b387-4d12-aaa5-c1320239dfe2.png)

Acrobat Pro DC 2021:

![image](https://user-images.githubusercontent.com/30081929/206864673-78fce2de-b2c2-4ff0-b5ae-8f0d26e6d3bd.png)

What went wrong? (add screenshot)
- The PDF file does not open.

![image](https://user-images.githubusercontent.com/30081929/206864767-7ecf11c9-d365-4e54-8871-dac936c44e4e.png)

**Comment by rizwan-io** [comment]
I would like to take a look at this issue. Can this issue be assigned to me?

**Comment by Snuffleupagus** [comment]
> I would like to take a look at this issue. Can this issue be assigned to me?

Sorry, but this really isn't a good beginner bug without general PDF experience *and* prior PDF.js knowledge.
