### ISSUE TITLE
pdfjs.GlobalWorkerOptions undefined in webpack.js file using 'pdfjs-dist/webpack' import

### ISSUE THREAD

**Issue by 21Kaen** [mozilla/pdf.js#15810]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chromium 79.0.3924.0
- Operating system and its version: Windows 10
- PDF.js version: pdfjs-dist 3.1.81
- Is a browser extension: no

Steps to reproduce the problem:
1. Using Webpack 5.73
2. Using babel-loader with core-js for pdfjs-dist package to fix es6 syntax errors.
3. import * as pdfjsLib from 'pdfjs-dist/webpack'

What is the expected behavior? (add screenshot)
Working pdf.js

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/87319649/207032487-7234db52-9dfc-4d8d-9ac3-fa2f4399d53e.png)

In webpack.js:
![image](https://user-images.githubusercontent.com/87319649/207032563-6a8c3ca2-187d-4a33-abbc-33bf05ff0b87.png)

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. Using Webpack 5.73
>     2. Using babel-loader with core-js for pdfjs-dist package to fix es6 syntax errors.
>     3. import * as pdfjsLib from 'pdfjs-dist/webpack'

You should really use a `legacy`-build, as mentioned in https://github.com/mozilla/pdfjs-dist/blob/master/README.md, rather that attempting to transpile/build it yourself.
Furthermore, as was mentioned in https://github.com/mozilla/pdf.js/issues/15799#issuecomment-1344426764, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
