### ISSUE TITLE
Some Text is not rendering and printing properly!

### ISSUE THREAD

**Issue by OilPrince** [mozilla/pdf.js#15816]
@Snuffleupagus

There is still a problem with the issue you closed, so I register the issue again.
[Some Text is not rendering properly! #15813](https://github.com/mozilla/pdf.js/issues/15813)

As you mentioned, there seems to be no problem if the PDF opens at https://mozilla.github.io/pdf.js/web/viewer.html.

However, when printing the PDF, the texts aren't displayed properly.
The error is made when running pdfTest7.html that I made.
And the console log is the same one!

console log :
pdf.js:4732 OTS parsing error: glyf: Failed to parse table
Warning: Failed to load font 'g_d0_f6': 'SyntaxError: Invalid font data in ArrayBuffer.'.

I think It's not a good idea to say that there's nothing wrong with just opening the PDF on https://mozilla.github.io/pdf.js/web/viewer.html.
Moreover, the error occurred when printing on that URL.

Also, if there is the error opening PDF in the example HTML(pdfTest7.html) (https://mozilla.github.io/pdf.js/examples/), we had better correct the error for PDFJS library.

Please check the issue I asked correctly!

I would appreciate your advice on how to solve it.

**Comment by ltdeta** [comment]
when I load my test file, I get the same error (web viewer)
`PDF 8fad2a9f89022f225e622ab9540b78f8 [1.7 GPL Ghostscript 9.56.1 / -] (PDF.js: 3.1.81 [0766898d5])
util.js:429 Warning: Failed to load font 'g_d0_f4': 'SyntaxError: Invalid font data in ArrayBuffer.'.
`
Unfortunately I can't provide the test file because of privacy.

**Comment by itsmepratikg** [comment]
I am getting the same issue. It seems on some browsers this is working fine but on some, it is not. also, it is not happening on Linux-based Chrome I was only able to replicate it in 2 systems out of 6 systems that I could have access to all windows I tested on 3 systems on Linux but could not replicate the issue for same file.

Browsers that had issue:::
Microsoft Edge
Version 109.0.1518.55 (Official build) (64-bit)

Google Chrome: Version 109.0.5414.74 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/68197133/212884776-49f62d3c-e0ad-4e7e-a262-f8ca10c5e456.png)

The browsers which didn't have issue:::
Firefox: Version 108.0.2
![image](https://user-images.githubusercontent.com/68197133/212885097-5a7a0103-fa8b-432f-b5bf-d565a92b8159.png)
