### ISSUE TITLE
Some Text is not rendering properly!

### ISSUE THREAD

**Issue by OilPrince** [mozilla/pdf.js#15813]
Attach (recommended) or Link to PDF file here:
[aaa.pdf](https://github.com/mozilla/pdf.js/files/10209039/aaa.pdf)

Configuration:
- Web browser and its version: Chrome 108.0.5359.99 (64bit)
- Operating system and its version: Windows 10
- PDF.js version: v3.1.81
- Is a browser extension: N/A

Steps to reproduce the problem:
1. deploy web resources(JS, HTML, PDF) on Tomcat
2. open URL(http://localhost:8080/test/pdfTest7.html) on Chrome
3. check pdf text

What is the expected behavior? (add screenshot)
open PDF on Adobe Reader 
![image](https://user-images.githubusercontent.com/40879690/207073305-01b756f4-8e9b-4265-b099-bd71e4983a8c.png)

What went wrong? (add screenshot)
open my html on Chrome 
![image](https://user-images.githubusercontent.com/40879690/207073794-490aad2c-18b5-4e94-864a-050e787d2b21.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Html file contents is as followd:
pdfTest7.html

```
<!doctype html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<title>PDF Sample</title>
<link rel="shortcut icon" href="data:;base64,iVBORw0KGgo="/>
<style>
#the-canvas {
  border: 1px solid black;
  direction: ltr;
}
</style>
<script src="./pdfjs-3.1.81-dist/build/pdf.js"></script>
</head>

<h1>PDF.js 'Hello, world!' example</h1>

<canvas id="the-canvas"></canvas>

</body>
</html>

<script>
//example URL : https://mozilla.github.io/pdf.js/examples/
var url = '/test/aaa.pdf';

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '/test/pdfjs-3.1.81-dist/build/pdf.worker.js';

// Asynchronous download of PDF
var loadingTask = pdfjsLib.getDocument({
		url
		, cMapUrl: '/test/pdfjs-3.1.81-dist/web/cmaps/'
		, cMapPacked: true
		//, disableFontFace: true
	});
loadingTask.promise.then(function(pdf) {
  console.log('PDF loaded');
  
  // Fetch the first page
  var pageNumber = 1;
  pdf.getPage(pageNumber).then(function(page) {
    console.log('Page loaded');
    
    var scale = 1.5;
    var viewport = page.getViewport({scale: scale});

    // Prepare canvas using PDF page dimensions
    var canvas = document.getElementById('the-canvas');
    var context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;

    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: context,
      viewport: viewport
    };
    var renderTask = page.render(renderContext);
    renderTask.promise.then(function () {
      console.log('Page rendered');
    });
  });
}, function (reason) {
  // PDF loading error
  console.error(reason);
});
</script>
```

console log : 
pdf.js:4732 OTS parsing error: glyf: Failed to parse table
Warning: Failed to load font 'g_d0_f6': 'SyntaxError: Invalid font data in ArrayBuffer.'.

I appreciate it if you could advise me how to display text normally when rendering PDF pages.
I'll wait for other people's guides.

Thanks!

**Comment by Snuffleupagus** [comment]
WFM, without any console errors, when opening your PDF with https://mozilla.github.io/pdf.js/web/viewer.html

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by calixteman** [comment]
I get an error in the console when trying to print:
```
downloadable font: glyf: Bad bounding box values bl=(-21332, 18676), tr=(-2512, 15753) in glyph 16581 (font-family: "g_d0_f6" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: glyf: Failed to parse table (font-family: "g_d0_f6" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f6" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f6" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f6': 'SyntaxError: An invalid or illegal string was specified'.
```
likely because we're rendering the annotations in using their appearance.

**Comment by OilPrince** [comment]
@Snuffleupagus
Why did you close my issue?
The problem I asked has not been solved yet.
I proceeded with the rendering example, but it didn't work properly.
A clear solution to this is needed.
