### ISSUE TITLE
Push Button not rendered on form with JavaScript embedded

### ISSUE THREAD

**Issue by cdm-phm** [mozilla/pdf.js#15821]
Attach (recommended) or Link to PDF file here:
[medforms.20.20.220.10.20.5010_de.pdf](https://github.com/mozilla/pdf.js/files/10220224/medforms.20.20.220.10.20.5010_de.pdf)

Configuration:
- Web browser and its version: Firefox 107.0.1
- Operating system and its version: MacOS Ventura 13.0.1
- PDF.js version: whatever ships with Firefox 107.0.1
- Is a browser extension: integrated in FF

Steps to reproduce the problem:
1. Open any of the PDFs linked/hosted at medforms.ch, e.g. https://medforms.ch/formTemplates/medforms.20.20.220.10.20.5010_de.pdf (see attachment)
2. The "Senden" button will be missing

What is the expected behavior? (add screenshot)
The senden button is visible and executes some JavaScript when clicked
<img width="557" alt="screenshot-acrobat-reader" src="https://user-images.githubusercontent.com/113915113/207396070-74556c45-aced-4f64-bd09-f1c3888a47c3.png">

What went wrong? (add screenshot)
<img width="499" alt="screenshot-pdfjs" src="https://user-images.githubusercontent.com/113915113/207395990-ddcbf51b-f263-4dba-900e-9e4b80d9a5c6.png">
In the console I get a "Warning: Push buttons without action dictionaries are not supported" warning

**Comment by calixteman** [comment]
The pdf contains the form in two formats:
 - one using XFA
 - the other using Acroforms.

In this case we're displaying the Acroform version and the button hast its `F` field set to 6 which means that the button is hidden, which means that the user cannot interact with it. And the button itself has no associated actions which means that even if it was visible, it'd impossible to do something with it.
Looking at the template stream in the XFA entry, we can see that the button has a JS callback but for the moment embedded JS is not executable in the XFA context (and it isn't on our roadmap for the moment).
So as far as I can tell there is nothing we can do right now.

**Comment by cdm-phm** [comment]
Thank you very much for the quick reply and analysis.
I'm fine with having the ticket closed as "won't fix / not planned", but I guess that is not on me to decide.

Sidequestion: Is there any way I can get the code of the XFA JS callback with the pdfjs api? (Probably won't help me much, I'm just interested)

**Comment by cdm-phm** [comment]
> In addition to everything already said in [#15821 (comment)](https://github.com/mozilla/pdf.js/issues/15821#issuecomment-1349762607), looking at the relevant JS code that button seems to be used for sending your entered form-data to a server. If that's correct, it's not clear to me that we'd ever support such a thing for security reasons (even _if_ we'd start supporting XFA embedded JS in the future); see e.g. the discussion in issue #13266.

That is fair and I totally expected that in the end there is a network call which would not work from within pdf.js. I was surprised though that the button wasn't rendered at all and hoped that maybe the validation part of the JavaScript callback would work. But @calixteman explained that very well.

**Comment by calixteman** [comment]
If you want to read the code behind the button, you can open the pdf:
http://brendandahl.github.io/pdf.js.utils/xfa/
and then search for "Senden" and you'll see in some xml  something like:
```xml
<event activity="mouseUp" name="event__mouseUp">
                    <script contentType="application/x-javascript">
                        {	
                        	var languageSwitch = sobHelpers.getFieldValue("formS1Struct.language");	
                        	var validGLN = /^(76|20)[0-9]{11}$/;
                        	var debug = 0;
                        	var hasError = 0;
                        	var logLine = "";
...
```

**Comment by cdm-phm** [comment]
All questions were answered, this is a "won't fix"
