### ISSUE TITLE
Scrolling can be really janky with large pdfs

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15836]
In playing with zooming on the first page of `pdf.pdf` and the Firefox profiler, I discovered that we spend a lot of time in:
```
imgLoader::LoadImage http://localhost:8888/web/images/shadow.png
```
All the blue areas:
![image](https://user-images.githubusercontent.com/5641725/207935170-696ea0d8-a79b-4184-a567-68a816dbe213.png)
are just because of this `shadow.png`.

This image is used:
https://github.com/mozilla/pdf.js/blob/826c358b3aefdddac7914c28462f4db5876ba8ca/web/pdf_viewer.css#L68

If I remove the `var` and just inline the border definition,I get:
![image](https://user-images.githubusercontent.com/5641725/207935659-f610f45c-6611-4c41-a3b9-6ea916f38ae2.png)

I think we could just use a box shadow or something like that in order to avoid this issue.
At least with the dark background, we could just remove the shadow which is useless (or maybe it's just my eyes):
![image](https://user-images.githubusercontent.com/5641725/207936828-4f8d1063-ce11-4ec2-b926-89c17e830f84.png)
and on a white background, maybe a black or box-shadow would be enough.

**Comment by Snuffleupagus** [comment]
> I think we could just use a box shadow or something like that in order to avoid.

Please note that we did use `box-shadow` originally, but that apparently had performance issues on its own (although that may no longer be an issue), please refer to issue #2533 and PR #2874 for context.

**Comment by calixteman** [comment]
I don't see any special value to have this shadow line around pages.
Maybe we could just have a dark line when the background is a light color and nothing with a dark background.
Wdyt ?

**Comment by Snuffleupagus** [comment]
> Maybe we could just have a dark line when the background is a light color and nothing with a dark background.

That inconsistency seems a little annoying to me, and looking at the light/dark themes in Adobe Reader I'm wondering:
Do we need a visible border at all, e.g. could we perhaps just *slightly darken* the `--body-bg-color` value in the light theme (to provide better background/page contrast) and simply use a fully transparent border always?

**Comment by calixteman** [comment]
You're right about the inconsistency.
And I'm not sure either that having a visible border is useful: we just need to have a way to make the difference between the viewer background and a page. It's worth trying the to increase the contrast with the light theme.
