### ISSUE TITLE
Invalid PDF structure with pdfjs but open perfectly with chrome.

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#15833]
Attach (recommended) or Link to PDF file here: [issue15833.pdf](https://github.com/mozilla/pdf.js/files/10236962/issue15833.pdf)

https://pdf.cdn.readpaper.com/userUpload/2022-12-15/1530240274458050305/9562d027b980ea2779dcfb1669f9cf7e.pdf

Configuration:
- Web browser and its version: Google Chrome v108.0.5359.124 (official) arm64
- Operating system and its version: macOS Monterey v12.6
- PDF.js version: v3.2.88 (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1.  open https://mozilla.github.io/pdf.js/web/viewer.html and select PDF. 
<img width="986" alt="image" src="https://user-images.githubusercontent.com/9332442/207831510-0012e89e-5c63-4a9d-9668-b33722b27a0d.png">

What is the expected behavior? (add screenshot)
open with chrome directly.
<img width="1695" alt="image" src="https://user-images.githubusercontent.com/9332442/207832062-9968f9c3-44af-4d07-8fd0-0b19609c85d8.png">

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Even Adobe Reader, i.e. the PDF reference implementation, refuses to open that document hence it's *really* corrupt (and not really our "fault").

**Comment by Snuffleupagus** [comment]
I can see a *potential* solution, with the caveat that I've not run any tests...
