### ISSUE TITLE
Broken dark theme

### ISSUE THREAD

**Issue by Rodrix33333** [mozilla/pdf.js#15840]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:
- Web browser and its version: Android, Samsung Internet 
- Operating system and its version: android latest 
- PDF.js version: latest 
- Is a browser extension: no

Steps to reproduce the problem:
1. Open on Samsung Internet on Android https://mozilla.github.io/pdf.js/legacy/web/viewer.html
2. Enable dark mode on Samsung internet (it's enabled by default!! This make it a critical bug)

What is the expected behavior? (add screenshot)
Icons become white.

What went wrong? (add screenshot)
Icons are black. Black background vs black icons = toolbar not visible. Pdf viewer unusable, customer complains.

Note: works fine on chrome dark mode

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Android, Samsung Internet

That's not one of our supported browsers, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by Rodrix33333** [comment]
Was able to fix it.
Add css for Samsung Browser changing all icons to red.
