### ISSUE TITLE
Printing not working on Safari

### ISSUE THREAD

**Issue by Rodrix33333** [mozilla/pdf.js#15846]
Safari is on the list of supported platforms.

Print is not working.

Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Configuration:

Web browser and its version: iPhone with Safari.
Operating system and its version: iOS
PDF.js version: latest
Is a browser extension: no
Steps to reproduce the problem:

Open this page on Safari iOS
https://mozilla.github.io/pdf.js/legacy/web/viewer.html
Click on print
What is the expected behavior? (add screenshot)
Show print preview of content of book

What went wrong? (add screenshot)
Print preview shows the printing of the browser (including user interface). Does not print book content. It's printing browser window.

It shows page 1/1 instead of 1/24 pages

**Comment by Snuffleupagus** [comment]
> Safari is on the list of supported platforms.

It's only listed as "Mostly" supported...

There's loads of problems with printing on Safari specifically, see e.g. issue #7597, and as previously mentioned the development focus is on the Firefox PDF Viewer.

**Comment by Rodrix33333** [comment]
That's sad... It would be nice to keep the issue open and have the community help make this library better
