### ISSUE TITLE
Doesn't work at all in Safari on ios16.1 - breaks entire page

### ISSUE THREAD

**Issue by dandawson87** [mozilla/pdf.js#15855]
Attach (recommended) or Link to PDF file here:

https://mozilla.github.io/pdf.js/web/viewer.html 

Configuration:
- Web browser and its version: Safari 16.1
- Operating system and its version: iOS16.1
- PDF.js version: 
- Is a browser extension:

Steps to reproduce the problem:
1. Use Safari to open https://mozilla.github.io/pdf.js/web/viewer.html 
2. Note - fails silently, entire page stuck on loading

What is the expected behavior? (add screenshot)

Its supposed to load

What went wrong? (add screenshot)

Failed to load anything

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Attached is a Web Debugger for Safari, looks like it gets stuck loading this

![image](https://user-images.githubusercontent.com/2100446/208607146-9bf9bcb1-fa86-440d-87e5-e6ed85078cdb.png)

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support you need to use a `legacy`-build with Safari, so does https://mozilla.github.io/pdf.js/legacy/web/viewer.html work? If not, are there any error messages printed in the console?

**Comment by dandawson87** [comment]
Neither the legacy or the original work. Any device running the latest iOS and safari has the issue. 

There is no error log - it freezes the browser and stops rendering the page. Very easy to reproduce on iOS atm

**Comment by cksgh1224** [comment]
I tested on "Safari 16.2 (macOS Ventura 13.1)" and it works fine.

**Comment by dandawson87** [comment]
Yes MacOS is fine, the bug is on iOS only. Need an iphone or iPad to reproduce.

**Comment by vlakken** [comment]
We noticed a similar issue in version 2.12.313 in ios15 its fine but in ios16 it freezes for certain files, could it be that in ios16 the canvas memory limit is being hit? The file that fails for us contains large images.

**Comment by dandawson87** [comment]
Can we please change the tag from "info requested" to bug? Its very reproduceable

**Comment by Snuffleupagus** [comment]
> Yes MacOS is fine, the bug is on iOS only.

This means that this bug only affects a particular combination of platform *and* browser...

> in ios15 its fine but in ios16 it freezes for certain files,

... and this even suggests that may be a regression (in the browser/platform).

---

> Can we please change the tag from "info requested" to bug? Its very reproduceable

While it might be easy to reproduce, it unfortunately doesn't seem easy to debug given the complete lack of any error messages.
Most likely this needs to be reported to the Safari developers instead[1], since this unfortunately doesn't really look actionable here (and Firefox is the *primary* development target).

---
[1] Previously we've seen e.g. issue #13726, where a single line of CSS was enough to crash Safari.

**Comment by JohnnyRacket** [comment]
I just wanted to add onto this, that I am seeing this behavior on both safari and chrome for ios16, complete page/tab crash loading pdfs over a page with rich content (full color manual with pictures/videos/etc). Seems like an ios16 specific issue and not a safari issue.

**Comment by vlakken** [comment]
For my cases the issue was caused by the code blocking on the putImageData calls in the following function: https://github.com/showpad/mozilla-pdf.js/blob/master/src/display/canvas.js#L590 Adding ctx.getImageData(0, 0, 1, 1); before each putImageData fixes the issue for me.

**Comment by mszsnn** [comment]
could you show me the code for the **Adding ctx.getImageData(0, 0, 1, 1);**  i have try but not use

**Comment by jiyuan12354** [comment]
still no solution...

**Comment by Zohar727** [comment]
same issue in ios 16.2
