### ISSUE TITLE
Document with examples the proper usage of PDFPageProxy cleanup() and cleanupAfterRender

### ISSUE THREAD

**Issue by robmv** [mozilla/pdf.js#15851]
Developing a custom viewer and opening a large file, then rendering all pages one by one by scrolling, destroying previous non visible canvases to release memory, I still found RAM usage only increased and the garbage collector never freed used RAM.

That happened until I found PDFPageProx's `cleanup()` and `cleanupAfterRender`. After using them and repeating the rendering of the pages, one by one, memory consumption reduced because resources where being freed.

There isn't a single example on mozilla.github.io that shows these should be used.

**Comment by Snuffleupagus** [comment]
We recommend using the viewer components to implement a custom viewer, see the "simpleviewer" example in https://github.com/mozilla/pdf.js/tree/master/examples/components which is intended to be used together with https://github.com/mozilla/pdfjs-dist/

That examples uses the `PDFViewer`-class which, among many other things, handles clean-up of no longer visible/active pages; https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js

> PDFPageProx's `cleanup()` and `cleanupAfterRender`.

Note that `cleanupAfterRender` is *really not* intended to be modified manually, and you should only ever call the `cleanup`-method.

**Comment by robmv** [comment]
Thanks @Snuffleupagus. I need a custom viewer because I need to draw things on top of the pages and that means direct access to the canvas without messing with the supplied viewer internals.

Thanks for letting me now that I shouldn't use `cleanupAfterRender`, maybe it should be removed from the TypeScript types or be prefixed with an underscore.

**Comment by Snuffleupagus** [comment]
> maybe it should be removed from the TypeScript types or be prefixed with an underscore.

First of all, please keep in mind that this is a JavaScript project and that we only provide (best effort) type-definitions since that was a commonly requested feature.[1]
Secondly, as a general rule, unless something is *explicitly documented* in the JSDocs in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js it shouldn't be relied upon.

---
[1] However, even keeping that working has required quite a lot of time/effort.
