### ISSUE TITLE
Download not working on Safari Ios

### ISSUE THREAD

**Issue by rodrix3855** [mozilla/pdf.js#15866]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari (all)
- Operating system and its version: iOS (all)
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Click on download
2. Error is:"refused to load blob because it appears in neither the frame-src directive nor the default-src directive of the contents security policy"

What is the expected behavior? (add screenshot)
Download.

What went wrong? (add screenshot)
Error message: "refused to load blob because it appears in neither the frame-src directive nor the default-src directive of the contents security policy"

**Comment by rodrix3855** [comment]
I got it.

If the viewer is INSIDE an iframe, clicking on the download button triggers this error. It wont download.

**Comment by rodrix3855** [comment]
I tried adding: 		header("Content-Security-Policy: 
default-src *  data: blob: filesystem: about: ws: wss: 'unsafe-inline' 'unsafe-eval' 'unsafe-dynamic'; 
script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; 
connect-src * data: blob: 'unsafe-inline'; 
img-src * data: blob: 'unsafe-inline'; 
frame-src * data: blob: ; 
style-src * data: blob: 'unsafe-inline';
font-src * data: blob: 'unsafe-inline';
frame-ancestors * data: blob: 'unsafe-inline';");
			

But still the same error..

**Comment by Snuffleupagus** [comment]
> Configuration:
>     * Web browser and its version: Safari (all)
>     * Operating system and its version: iOS (all)
>     * PDF.js version: latest
>     * Is a browser extension: no

*Generally speaking:* Please remember to provide meaningful version *numbers*, since "all" and "latest" are quite frankly not helpful/useful to describe your actual environment.

---

Unfortunately I don't believe that the PDF.js contributors can realistically help you with configuration something like CSP to target a specific platform/browser; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
