### ISSUE TITLE
PDF files showing white blank not rendering in Safari

### ISSUE THREAD

**Issue by rajacsharp** [mozilla/pdf.js#15868]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 16.1
- Operating system and its version: Ventura 13.0
- PDF.js version:  2.16.105
- Is a browser extension: No

Looks like the document is loading in pdf.js but not rendering properly, it shows white blank  when we resize the window or use the Zoom +- button document shows correctly 

Steps to reproduce the problem:
1. Open a document pdf.js in IOS 
2.

What is the expected behavior? (add screenshot)
The document should show in PDF.js

What went wrong? (add screenshot)
Document showing white blank
![image](https://user-images.githubusercontent.com/58780677/209624078-05d284ad-9ec7-4679-946f-93accbfad26a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version:  2.16.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. Open a document pdf.js in IOS

If this is specific to just one platform *and* browser, it's unfortunately quite unlikely to be actionable/fixable here; please keep in mind that the *primary* focus of development is on the Firefox PDF Viewer.
