### ISSUE TITLE
In SVG renderer, fill action doesn't end the path properly

### ISSUE THREAD

**Issue by Japhics** [mozilla/pdf.js#15873]
In class SVGGraphics, funciton `fill` calls function `endPath` at the end.In `endPath`, it sets `current.path` to null, but keeps `current.element`.However, `fill` only uses `current.element` to judge whether the path exists and perform the fill action.That means, the next fill action will also be effective,which is not allowed.

**Comment by Snuffleupagus** [comment]
Sorry, but the SVG back-end is no longer maintained/supported; please note https://github.com/mozilla/pdf.js/blob/a575aa13b9e4ce7e671be7794e7a7296406a3087/src/display/svg.js#L468-L472
