### ISSUE TITLE
In IOS 16 version, PDF created with "save as" in MS office with embedded OTF fonts does not open.

### ISSUE THREAD

**Issue by KimDal-hyeong** [mozilla/pdf.js#15881]
Attach (recommended) or Link to PDF file here:
Sample file
[애국가많이폰트.pdf](https://github.com/mozilla/pdf.js/files/10330336/default.pdf)

Configuration:
- Web browser and its version: Mobile Safari 16.1 WebKit 605.1.15
- Operating system and its version: IOS 16.1
- PDF.js version: in PDFjs Demo (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: X

Steps to reproduce the problem:
1. Open the sample file in PDF.js Demo.
2. Loading fails.

What is the expected behavior? (add screenshot)
- The Sample PDF file should display correctly.
**- Screenshot In IOS 15.6.1**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/16788797/210202063-843654a0-636b-409d-aff1-2b782d52f96c.png">

What went wrong? (add screenshot)
- Loading fails.
**- Screenshot In IOS 16.1**
![IMG_7FEF5C0758BD-1](https://user-images.githubusercontent.com/16788797/210202194-a23312bd-9c56-4e0f-aee6-a114baa4508a.jpeg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * The Sample PDF file should display correctly.
>       **- Screenshot In IOS 15.6.1**
> [...]
> * Loading fails.
>       **- Screenshot In IOS 16.1**

This would suggest a regression in the browser *itself*, and as such we'd recommend reporting this to the Safari developers instead.

**Comment by DevSDK** [comment]
FYI:

I filed an issue on [webkit bugzilla](https://bugs.webkit.org/show_bug.cgi?id=250062).
