### ISSUE TITLE
Trying to upgrade to latest from 2.6.146 -> absolute (scroll) problem

### ISSUE THREAD

**Issue by kjartanvalur** [mozilla/pdf.js#15882]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Chrome 108.0.5359.125 (Official Build) (64-bit)
- Operating system and its version: Window 11
- PDF.js version: 3.2.146 from 2.6.347
- Is a browser extension:

Steps to reproduce the problem:
1. Fork https://stackblitz.com/edit/bootstrap-5-3v7wgs?file=src/index.html
2. change version 2.6.347 to 3.2.146 in index.html for three javascript files
3. You will get the error **pdf_viewer.js:254 Uncaught Error: The `container` must be absolutely positioned.**
4. Try set the #viewerContainer style in styles.scss and set the height to a fixed number, e.g. 1000px;
5. The scroll will not be for the main window.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/3437106/210218854-3cf4861c-1ae3-4e7e-a964-1625ada1a86b.png)

I´m having a problem updating from version 2.6.347 to 3.2.146 (latest)

This works fine in version 2.6.347

But when I upgrade to version latest version 3.2.146 I get the following error:
**pdf_viewer.js:254 Uncaught Error: The `container` must be absolutely positioned.**

https://stackblitz.com/edit/bootstrap-5-mpmyoy?file=src/index.html

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/3437106/210218915-2f0ab989-d69a-4636-bca6-e8759d4124c9.png)

When I set the container to absolute the style property height: 100%  then it will not work and I have to set a fixed height which is not what I want. I want to use the main scrollbar of the window to scroll the document.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://stackblitz.com/edit/bootstrap-5-brshqu?file=src/index.html

**Comment by Snuffleupagus** [comment]
This issue is tracked in issue #11626, of which this is effectively a duplicate, since determining the visible pages currently requires that the viewer is absolutely positioned.
Our general recommendation is to place the viewer in an `iframe` to avoid it interfering with the surrounding page.

**Comment by kjartanvalur** [comment]
Hi @Snuffleupagus 
Thanks for the quick response. So there are no plans to fix this or what? 
Can you show me how to fix this with iframe?

**Comment by kjartanvalur** [comment]
But I would rather not use an iframe. This is an angular app and I really want more control over this pdf viewer.

**Comment by kjartanvalur** [comment]
Hi @Snuffleupagus
I´m trying to get the pdf viewer to be 100% height and use the browser window scroll. 
How would you accomplish that?

For example here
https://stackblitz.com/edit/bootstrap-5-brshqu?file=src%2Findex.html
