### ISSUE TITLE
Typescript - "cannot find name OffscreenRenderingContext" error when upgrading to 3.x.x version

### ISSUE THREAD

**Issue by giuseppebrb** [mozilla/pdf.js#15915]
I am developing an Angular 12+ platform. I am currently using PDF.js v2.16.105 but whenever I try to upgrade to 3.x.x (eg. 3.2.146) application doesn't build anymore due an error coming from pdfs dependency itself.
I obtain the following error coming from the file `text_layer.d.ts`: `cannot find name OffscreenRenderingContext`

Configuration:
 PDF.js version: 2.16.105 -> 3.x.x
Angular version: 15.0.4
Typescript version: 4.8.4

It seems to me an issue due the fact since 3.x.x the types are now included within the library but this one cannot be found.

**Comment by tunjayhuseynov** [comment]
Try to upgrade your typescript version.

I faced the same issue, and I've upgraded my typescript version to 4.9.4 and the error was gone

**Comment by giuseppebrb** [comment]
Unfortunately Angular 15 doesn't support TS 4.9.4 yet, a bunch of warning and errors might popup. It makes more sense to me to fix the issue even for those ones not using the latest release of TypeScript.

**Comment by Snuffleupagus** [comment]
If this works simply by updating to the latest TypeScript version, according to https://github.com/mozilla/pdf.js/issues/15915#issuecomment-1380201330, then that's really the preferred/correct solution here.

Please keep in mind that PDF.js is a *JavaScript project*, which only provides type-definitions. Even keeping that working takes a fair amount of effort/time for the (few) core PDF.js contributors, who do not know TypeScript, and thus trying to support *older* TypeScript versions is most unfortunately not really feasible.

(Also, note that Angular isn't something that we use here and thus can't provide support for.)

**Comment by PabbleDabble** [comment]
@giuseppebrb 
I encountered this same thing, still struggling a lot to get this working in my Angular13 repo.  
I also couldn't find anything on https://github.com/microsoft/TypeScript relating to OffscreenRenderingContext 

I added this to my main project's root `src/typings/index.d.ts` which should be then captured by something in your `tsconfig.app.json` (see 'include': [ 'src/**/*.d.ts' ]
```
// some comment about why this exists relating to pdfjs-dist install
interface OffscreenRenderingContext {}
```

It's still not fixing my import issues, but it's a simple way to override the typescript/buld error.
