### ISSUE TITLE
Unable to use pdf file to run Vue Js with composition API with pdf.js using pdfjs-dist package

### ISSUE THREAD

**Issue by sarwangds** [mozilla/pdf.js#15928]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 109.0.5414.75 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Version 22H2 (OS build 19045.2486) 
- PDF.js version: v3.2.146
- Is a browser extension: No

Steps to reproduce the problem:
1. I am using pdfjs-dist in my vue 3 project to read text from the pdf 

``<script setup>
import * as pdfjs from "pdfjs-dist/build/pdf";
import { onMounted } from 'vue'

pdfjs.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.2.146/pdf.worker.min.js';

const getContent = async (src) => {
  const doc = await pdfjs.getDocument(src).promise
  const page = await doc.getPage(1);
  return await page.getTextContent();
}

const getItems = async (src) => {
  const content = await getContent(src);
  const items = content.items.map((item) => {
    console.log(item.str)
  })
  return items;
}

onMounted(()=>{
  getItems("test-pdf.pdf");
})

</script>``

I have this test-pdf in local file, but when I run the project it throws this error
i have test-pdf.pdf file in current directory of vue file.
Also server is running using vite

![image](https://user-images.githubusercontent.com/117128235/212699810-06a6aed3-d393-4981-afe6-62d474486d3f.png)

2.What is the expected behavior? (add screenshot)
it should console.log the text

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/117128235/212700024-15c58098-d681-44e4-8544-fc3e058e5dfd.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I am using pdfjs-dist in my vue 3 project to read text from the pdf

Sorry, but we're not able to provide help/support for the multitude of JS frameworks that exist (i.e. Vue 3 in this case).

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
