### ISSUE TITLE
How do I show the first page as SpreadMode.NONE and the others as SpreadMode.ODD?

### ISSUE THREAD

**Issue by WagnerDavi** [mozilla/pdf.js#15927]
Configuration:
- Web browser and its version: Chrome 108.0.5359.126 (64 bits) / Firefox 108.0.2 (64-bits)
- Operating system and its version: Windows Pro 10 - 19045.2486
- PDF.js version: v3.2.146

I'm trying to create a views where only the first page appears as a sigle page, but the others as double pages, I tried to return "pageNumber" and "_currentPageNumber", but without success, from what I understand it already loads the entire pdf if trying to search for the page number it always returns as 1, I tried to create a method in onclick, but always the first click will return as only one page.
I'm using the pdf.js example for study, does anyone have any idea how I can do it using their own methods.

**Comment by Snuffleupagus** [comment]
It sounds like you're (essentially) describing how the `SpreadMode.EVEN` option works, so maybe try using that one instead!?

(However, given the information provided thus far it's unfortunately difficult to understand exactly what you're asking about here.)

**Comment by WagnerDavi** [comment]
> It sounds like you're (essentially) describing how the `SpreadMode.EVEN` option works, so maybe try using that one instead!?
> 
> (However, given the information provided thus far it's unfortunately difficult to understand exactly what you're asking about here.)

It's exactly that, I didn't pay attention sorry, thanks
