### ISSUE TITLE
Password manager appears on page number input focus

### ISSUE THREAD

**Issue by 4rneorist** [mozilla/pdf.js#15938]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 109
- Operating system and its version: Windows 10
- PDF.js version: 2.2.171
- Is a browser extension:

Steps to reproduce the problem:
1. Click on page number input

What is the expected behavior? 
Password manager doesn't appear

What went wrong? 
Password manager appears
![image](https://user-images.githubusercontent.com/13441265/213185952-af95840e-8348-432a-9850-a27483985662.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.2.171

That version is no longer supported, and it's also not an official release, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by 4rneorist** [comment]
@Snuffleupagus reproduces on your example https://mozilla.github.io/pdf.js/web/viewer.html
![image](https://user-images.githubusercontent.com/13441265/213189179-02bccab2-ee82-4d7e-bea3-b34b78caa537.png)

**Comment by Snuffleupagus** [comment]
> reproduces on your example if add creds to password manager for https://mozilla.github.io https://mozilla.github.io/pdf.js/web/viewer.html

But why would you do that!?

This unfortunately sounds like a bug in your password-manager, rather than in the PDF.js viewer.

**Comment by 4rneorist** [comment]
@Snuffleupagus if I will have saved password in my site and open page with pdf viewer it will reproduce. What about bug in password manager - probably this bug exists on most browsers (tested on latest versions of Chrome, Mozilla, Edge, Opera)

**Comment by calixteman** [comment]
We can't prevent any webextensions to do what they want with the html... so as I already said in [bug 1810940](https://bugzilla.mozilla.org/show_bug.cgi?id=1810940#c1) it isn't a pdf.js bug.
I've myself a password manager and everywhere (e.g. the input on www.google.com) it sees an `<input...>` I've a specific sub-menu.
But of course we can be wrong and if you've a patch to avoid that please make a PR.

**Comment by 4rneorist** [comment]
@Snuffleupagus at least in Chrome autocomplete="off" ignored for now (more details: https://stackoverflow.com/questions/31612867/autocomplete-off-not-working-in-chrome)

**Comment by Snuffleupagus** [comment]
Based on the following resources, this is basically the browser trying to be "helpful" which ends up breaking things; hence this really isn't a bug that we can fix here.
 - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values
 - https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields

**Comment by andreififiita** [comment]
This still happens both on Chrome (114.0.5735.133) and Firefox (114.0.2 ), tested on MacOS Ventura.
![Screenshot 2023-07-06 at 09 23 11](https://github.com/mozilla/pdf.js/assets/9675912/c627dd1c-f63d-4e6b-9bdf-97c73d6e93d3)
![Screenshot 2023-07-06 at 09 22 56](https://github.com/mozilla/pdf.js/assets/9675912/aad9cb44-50b1-44de-bb3a-34cf45a4231a)
