### ISSUE TITLE
Demo viewer, full screen presentation, Keys 'b' and 'w' are conventially used for a full black or white screen.

### ISSUE THREAD

**Issue by axkibe** [mozilla/pdf.js#15932]
Hello, it's quite a common convention during presentations in full screen mode that "b" and "w" keys can be used to completely black or respectively white out the screen (since you want to draw something on the blackboard for example). PDF.js demo viewer doesn't do that. (Yes it's wouldn't be hard to integrate it oneself in integration, but IMO would be nice if the demo would come with this out of the box to put black/white div over everything when said buttons are pressed)

Configuration:
- Web browser and its version: Chrome Version 109.0.5414.74 (Official Build) (64-bit)
- Operating system and its version: Debian 11
- PDF.js version: 3.2.146
- Is a browser extension: No

Steps to reproduce the problem:
1. Start the demo viewer (or integrate it in a website)
2. Start a full screen presentation
3. press "b" (or "w") during the full screen presentation

What is the expected behavior? (add screenshot)
completely black or white screen.

What went wrong? (add screenshot)
nothing happens.

**Comment by Snuffleupagus** [comment]
Sorry, but this sounds like too much of an edge-case to warrant the added complexity related to both implementing and then maintaining something like that.

Please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by axkibe** [comment]
Fair enough, just thought it was a good idea, as most other presentation mode applications respect that convention.

**Comment by axkibe** [comment]
PS: IMO this also makes much sense for the PDF Viewer in Firefox (basically anyone who wants to use the presentation mode for presentations and has learned that keys), so should I make an issue to Firefox then?
