### ISSUE TITLE
The "View URL from Current Page" tooltip text is not clear

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/pdf.js#15967]
This is from #15941.
While I understand the feature, "View URL from Current Page" doesn't seem to explain it well.
Since this is a tooltip, I'd just explain the feature fully, even if it's going to be a long-ish tooltip.

**Comment by itsajay1029** [comment]
Can I work on this @timvandermeij  ?? Please assign this to me if no one is working on it

**Comment by Snuffleupagus** [comment]
Can you please check with the UX-team if we they think that we should tweak this string (again), or if this should be closed as WONTFIX, and if so what (exact) wording to use here? 
/cc @calixteman, @marco-c

**Comment by Snuffleupagus** [comment]
@ItielMaN Given https://github.com/mozilla/pdf.js/issues/15967#issuecomment-1547462757 do you have a *specific* suggestion in mind here?

**Comment by ItielMaN** [comment]
I don't have a better idea other than #16419...

**Comment by itsajay1029** [comment]
Can you properly explain the issue @ItielMaN @marco-c ?

**Comment by timvandermeij** [comment]
Closing for now since the UX team looked into this not too long ago and provided the current wording, and the given suggestions don't make the intent of the functionality much more clear in my opinion as well.
