### ISSUE TITLE
The pdf is not visible on android mobile when it is inside an IFrame

### ISSUE THREAD

**Issue by lamnouar** [mozilla/pdf.js#15969]
Attach (recommended) or Link to PDF file here:

Configuration:
- Samsung S22 GChrome  
- Operating system and its version: Android
- PDF.js version: Can't find it in the file, but it is the latest stable in July 2022
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that this part of the issue template is *always* required.

> Samsung S22 GChrome
> Operating system and its version: Android

Assuming that this means "Google Chrome", then please note that PDF.js is only *built-in* to the Firefox browser and currently its mobile version isn't yet including a PDF Viewer (although that's being worked on currently).

> PDF.js version: Can't find it in the file, but it is the latest stable in July 2022

Given the lack of a version number it's impossible to tell which *exact* version you're using, however any version from "July 2022" is no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Unfortunately this issue doesn't really contain enough details to be actionable as-is, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
