### ISSUE TITLE
Remove title on the secondary toolbar menu items

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#15978]
In the viewer, the secondary toolbar menu buttons have title which are the same as the labels.
So they are unnecessary and can be removed.

**Comment by Snuffleupagus** [comment]
They're not all identical though, see
https://github.com/mozilla/pdf.js/blob/2ebbeb7499f3674ac66b3ab9513ff8a3bf2fc5d0/l10n/en-US/viewer.properties#L47-L78)

**Comment by SuperPat45** [comment]
Better do not show title identical to label
