### ISSUE TITLE
Open PDF links in a new tab instead of the current one

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#15980]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 109
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a PDF with a link
2. Click on the link

What is the expected behavior? (add screenshot)
It is preferable that the link opens in a new tab.

What went wrong? (add screenshot)
The link is opened in the current tab, so the PDF is lost.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The link target is configurable, hence you can achieve this by setting `pdfjs.externalLinkTarget = 2` in `about:config`.

**Comment by SuperPat45** [comment]
I think 2 should be the default value

**Comment by calixteman** [comment]
It's very likely a matter of taste.
PDF.js behaves here like a normal website and you can ctrl+click to open in a new tab.
I'm not sure at all it'd be good idea in general to have different behaviours.
