### ISSUE TITLE
could someone tell me how this windows show in the photos

### ISSUE THREAD

**Issue by baiclamp** [mozilla/pdf.js#15982]
Hi, All
I was very confused that the below photo show that when using pdfviwer to open a pdf file it pop up a printing info window in some mobile phones like iphone10. it could not continue process and sometimes the window and the file info show together.
but not all the phones show like this. I ve tested  iphone 11~13,It will not pop up this window.
Could someone tell me why? thanks!
![photo](https://user-images.githubusercontent.com/78243979/215514707-b812baf9-a72c-4d6e-83c8-f705ee99433a.jpg)
![photo2](https://user-images.githubusercontent.com/78243979/215514719-5386aa22-6270-4014-a31a-45524253de73.jpg)

Configuration:
- wechat embed browser:
- IOS: ios15
- PDF.js version: 2.14.305
- Is a browser extension: no

**Comment by Snuffleupagus** [comment]
> * wechat embed browser:

Sorry, but that's not one of the supported browsers; please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

You might want to use a `legacy`-build, as mentioned in the FAQ linked above, but given the limited information provided it's unfortunately impossible to provide much help.

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
