### ISSUE TITLE
Prevent pdfs downloaded from network request

### ISSUE THREAD

**Issue by natnaeltibebu** [mozilla/pdf.js#15985]
i use PDF.js Previous/Next example but when i see the network request the full file is there, is there any way to only **show the first 3-5 of the whole page**

**Comment by Snuffleupagus** [comment]
Please see the following `getDocument` parameters, which will attempt to load the document on demand:
https://github.com/mozilla/pdf.js/blob/2d87a2eb1ccce55b8099bf2b8fcc7ed51bd6fbc9/src/display/api.js#L221-L230

However, please keep in mind that in order for this to work the PDF document itself must have a suitable internal structure (i.e. it should be linearized) and the server must also support range requests.

**Comment by natnaeltibebu** [comment]
Thanks so much,
Can you please guide me alittle bit how to achieve that.
