### ISSUE TITLE
Multi-Line Annotation highlights an entire block of text

### ISSUE THREAD

**Issue by zzeleznick** [mozilla/pdf.js#15986]
#### Steps to reproduce the problem:
1. Hover over a text area that contains an annotation whose text spans more than one line

#### What is the expected behavior? 
- Link is only highlighted across the text and only hovering over the text causes the highlight

#### What went wrong? 
- Hover on the section causes the entire area to be highlighted instead of the associated link

### Screenshots

| Undesired Behavior | Expected Behavior |
| --- | --- |
 | <img width="1694" alt="Screen Shot 2023-01-31 at 11 26 33 AM" src="https://user-images.githubusercontent.com/5779832/215865133-0292dd1b-40e9-4142-8a1d-f94daeddece3.png"> | <img width="946" alt="Screen Shot 2023-01-31 at 11 36 18 AM" src="https://user-images.githubusercontent.com/5779832/215865131-4e7f9ad0-815d-48db-b55d-81375cabc4c6.png"> |
| `Toxoplasma gondii` link annotation covers more than the text | `genome` link annotation hovered and only covers the text  |

### PDF File
[panda_web_page.pdf](https://github.com/mozilla/pdf.js/files/10550108/panda_web_page.pdf)

#### Configuration
- Web browser and its version: `Chrome 108.0.5359.124` and `Firefox 109.0.1`
- Operating system and its version: `Mac OS Monterey (12.5.1)`
- PDF.js version: `3.3.122`
- Is a browser extension: `No`

#### Link to a viewer
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
The same exact *area* is clickable in both Adobe Reader and PDFium (in Google Chrome) as well, since the PDF document *itself* actually specifies the clickable area too large. (The only difference is that PDF.js highlights the clickable area.)

Hence this is unfortunately a "bug" in the PDF document, and not in the PDF.js library.
