### ISSUE TITLE
Not an issue but is there any plan for pdf js to support reflow of content on zooming pdf

### ISSUE THREAD

**Issue by karthikchakravarthy** [mozilla/pdf.js#16012]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
With nothing more than a (slightly cryptic) title it's virtually impossible to understand *exactly* what you're asking here.

**Comment by karthikchakravarthy** [comment]
I meant to say, On zooming in any pdf to 400% in pdf js presently we need to scroll horizontally to see all the content. Does pdf js support reflow of the content so that the content reflows and there is no requirement of horizontal scroll bar
