### ISSUE TITLE
How to undo and redo the changes done by using text box and pencil editor tools in mobile devices. How can I delete some particular change in mobile devices

### ISSUE THREAD

**Issue by durgamalleswariyeruva** [mozilla/pdf.js#16022]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 3.4.406
- Is a browser extension:

Steps to reproduce the problem:
1. Open pdf in mobile devices(iPhon/android)
2. Add text by using Textbox and pencil drawer tool

What is the expected behavior? (add screenshot)
I need to delete pencil drawer changes and text box changes in mobile devices, when pdf is opened.
What went wrong? (add screenshot)
I am not able to delete pencil drawer changes in pdf .
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by durgamalleswariyeruva** [comment]
@calixteman , Can I get any solution for my issue?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.4.406

Sorry, but that version number doesn't actually exist.

> Steps to reproduce the problem:
>     1. Open pdf in mobile devices(iPhon/android)
>     2. Add text by using Textbox and pencil drawer tool

Assuming that you're referring to https://github.com/mozilla/pdf.js#online-demo, which isn't really clear, then please note that it's intended for desktop browsers in general and the *built-in* Firefox PDF Viewer in particular.

**Comment by jesesqui** [comment]
try this
function personal_Delete(){
	$(".inkEditor.disabled.selectedEditor").remove();
	
	$(".freeTextEditor.selectedEditor").remove();
	
	console.log("jesdeleteCanvas");
}

html

<button id="personal_Delete" onClick="personal_Delete()"  >

**Comment by JImumu** [comment]
![WX20231108-105133@2x](https://github.com/mozilla/pdf.js/assets/25128849/3efda6ab-be17-44cb-9692-cbc767dd2009)
Add closer when AnnotationEditor selected.
