### ISSUE TITLE
Mailto links render an href on top of link text since version 3.1.81

### ISSUE THREAD

**Issue by SuttonKyle** [mozilla/pdf.js#16021]
Attach (recommended) or Link to PDF file here:
[MSD_IRMA_Disclosure_-_trs_update_11-17-14.DRU65gKY7.pdf](https://github.com/mozilla/pdf.js/files/10678322/MSD_IRMA_Disclosure_-_trs_update_11-17-14.DRU65gKY7.pdf)

Configuration:
- Web browser and its version: Chrome 109.0.5414.87 
- Operating system and its version: macOS Monterrey 12.5.1
- PDF.js version: 3.1.81 and above
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached document in the hosted PDF.js viewer at https://mozilla.github.io/pdf.js/web/viewer.html
2. Mailto links for email links render on top of link text.

What is the expected behavior? (add screenshot)
The links should render normally (screenshot from version 3.0.279):
<img width="749" alt="Screen Shot 2023-02-07 at 1 39 27 PM" src="https://user-images.githubusercontent.com/31548831/217336015-ea3e383c-1537-4581-a578-01e088c5c0a0.png">

What went wrong?
The links render in a weird overlapping format (screenshot from versions 3.1.81 and above):
<img width="804" alt="Screen Shot 2023-02-07 at 1 41 03 PM" src="https://user-images.githubusercontent.com/31548831/217336419-e16d6374-a26c-40e9-abed-493ef6b89919.png">

**Comment by calixteman** [comment]
The FreeText annotation has an Opacity (CA entry) equals to 0 it's why we don't see it in other viewers.
In pdf.js we're creating an appearance because there is no appearance but don't take into account the opacity.
