### ISSUE TITLE
inline fonts not shown correctly in pdf.js web-viewer

### ISSUE THREAD

**Issue by Soosfief** [mozilla/pdf.js#16039]
Firefox Version 109.0.1
Windows Server 2018

Steps to reproduce the problem:
1. Download or open a .pdf-file with inline/document fonts 

![grafik](https://user-images.githubusercontent.com/120056302/218033983-95945a75-ded2-4ad6-a932-bfc0ad933d58.png)

![grafik](https://user-images.githubusercontent.com/120056302/218031770-b21d5fda-842a-4c06-be07-b814e7dcb86b.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.
In particular the `Attach (recommended) or Link to PDF file here:`-part is always required.

**Comment by Soosfief** [comment]
[DKA_RE202302602.pdf](https://github.com/mozilla/pdf.js/files/10705644/DKA_RE202302602.pdf)

**Comment by Snuffleupagus** [comment]
Duplicate of #15289 (which is fixed in Firefox 110 and will be released next week).
