### ISSUE TITLE
Upgrade to version 3.3.122 breaks viewer.html in Electron.

### ISSUE THREAD

**Issue by j-pdx** [mozilla/pdf.js#16034]
Configuration:
- Chrome Version 109.0.5414.120 (Official Build) (64-bit)
- Windows 11 22621.1105
- PDF.js version: 3.3.122
- Is a browser extension: No

Steps to reproduce the problem:

We've been using version 2.7.570 in Electron (embedded in an iFrame using the viewer.html URL) with zero issues for a few years.

We just upgraded to version 3.3.122 and now the viewer is throwing errors.

What is the expected behavior? 

Loading the PDF viewer with no exceptions.

What went wrong?

![Screenshot 2023-02-09 083451](https://user-images.githubusercontent.com/1747494/217879780-f5813f60-a982-46d5-bf63-fcf800acc6a5.png)

Any help is appreciated.

**Comment by j-pdx** [comment]
I should also mention this site is being loaded in Electron from an external URL. It is not running in Node.

**Comment by Snuffleupagus** [comment]
For anything except the very latest browsers, as [mentioned in the Wiki](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), you need to use a `legacy` build; please note the two different versions available e.g. at https://mozilla.github.io/pdf.js/getting_started/#download

However, please keep in mind that we've never officially supported frameworks such as e.g. Electron.

**Comment by j-pdx** [comment]
> However, please keep in mind that we've never officially supported frameworks such as e.g. Electron.

Thank you for the quick response.

I understand you don't support Electron as a framework. I guess I thought since it's not a bundled Electron app it shouldn't be an issue, since it's essentially just a shell loading a public web site. My misunderstanding I suppose.

Anyway, I do appreciate the help.

**Comment by zhanghr897** [comment]
Did you find a solution, I also encountered the same problem

**Comment by j-pdx** [comment]
> Did you find a solution, I also encountered the same problem

I used the legacy build as suggested above and that solved our issue.

**Comment by zhanghr897** [comment]
Thank you for replying to me soon. I wonder if you have a problem with incomplete text rendering when using the electron framework?
