### ISSUE TITLE
Some links are not clickable

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#16041]
Attach (recommended) or Link to PDF file here:
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. On the second page there are two clickable links: try to click

What is the expected behavior? (add screenshot)
Open the link

What went wrong? (add screenshot)
Links are not clickable.

It works correctly in Chrome and Acrobat.

**Comment by Snuffleupagus** [comment]
The behaviour is *identical* in Adobe Reader as well, since the /Rect entries are incorrect which causes the "wrong" area to be clickable. This is really a bug in the PDF document *itself*, as far as I'm concerned.

**Comment by calixteman** [comment]
Yes I think you're right, here the links are clickable because they're detected as links (`http://...` pattern).
