### ISSUE TITLE
Can we revert PR 15578 now?

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#16049]
As far as I understand it PR #15578 was intended as a *temporary* solution, until https://bugzilla.mozilla.org/show_bug.cgi?id=1795536 was fixed in Firefox. Given that the upstream bug was fixed in Firefox 108, does that mean that we can revert the PR now?

/cc @calixteman

**Comment by calixteman** [comment]
Unfortunately the bug is still there.

**Comment by Snuffleupagus** [comment]
> Unfortunately the bug is still there.

Then I don't really understand the following comment?
https://github.com/mozilla/pdf.js/blob/fd1c9e34ac63bbe0287c5b218ccaa9cb1f15cf9d/src/display/editor/ink.js#L634-L642

**Comment by calixteman** [comment]
I tested with the test case in the bug I filed and the bug is fixed but unfortunately it didn't fix the bug in pdf.js: we still have the width expressed in `px` instead of `%` but only from times to times.
Anyway you're right on the fact that the comment is inaccurate: I'll fix that.

**Comment by Snuffleupagus** [comment]
> Anyway you're right on the fact that the comment is inaccurate: I'll fix that.

Ping, any chance that you can fix this so that we can close this issue?
