### ISSUE TITLE
Radio buttons do not have values in HTML

### ISSUE THREAD

**Issue by paalg** [mozilla/pdf.js#16044]
The example document used for this issue:
[radio.pdf](https://github.com/mozilla/pdf.js/files/10707775/radio.pdf)

**Configuration:**
- Web browser and its version: Opera 94.0.4606.76
- Operating system and its version: WIndows 10 64 bit
- PDF.js version: 3.2.146
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Load any PDF file with radio buttons in form
2. Enter developement tools and see the rendering av radio buttons

**What is the expected behavior? (add screenshot)**
All HTML form elements in PDF.js have values, except radio button. I am expecting radio buttons to have value too.

**What went wrong? (add screenshot)**
This is the output to screen:
![image](https://user-images.githubusercontent.com/2621435/218101691-5fe77567-a785-4253-9480-81939d8c3c27.png)
No value is added to radio button in HTML. Here is the annotation layer in HTML from the PDF linked to above (I added linefeeds and removed all inline style to make it easier to read):
```
<div class="annotationLayer" data-main-rotation="0">
  <section data-annotation-id="39R" class="buttonWidgetAnnotation radioButton">
    <input data-element-id="39R" aria-required="false" type="radio" name="gender" tabindex="1000" id="pdfjs_internal_id_39R" value="">
  </section>
  <section data-annotation-id="40R" class="buttonWidgetAnnotation radioButton">
    <input data-element-id="40R" aria-required="false" type="radio" name="gender" tabindex="1000" id="pdfjs_internal_id_40R" value="">
  </section>
</div>
```
This is important for me because I extract the data from the form, and don't get values from radio buttons.

**Comment by calixteman** [comment]
Why not using the values from the annotation storage object ?
In the console you can enter `PDFViewerApplication.pdfDocument.annotationStorage.getAll()` and you'll see the values you're expecting.

**Comment by paalg** [comment]
Thanks for the suggestion @calixteman! 

I tried getting values from the annotation storage, and found it returns null if the user has not edited the form yet. Each time a form element has changed, its value is available in the getAll() function, but attribute names are not included. The attributes names are replaced with internal created IDs, which I then need to figure out.

My example with the radio buttons will return this: 
```
{ 
  "R39R": { "value": true }
  "R40R": { "value": false }
}

```
I am aware of though that handling of forms are not a main focus in the project.

**Comment by Snuffleupagus** [comment]
> The attributes names are replaced with internal created IDs, which I then need to figure out.
> 
> My example with the radio buttons will return this:

Assuming that the default viewer is being used, you can get all of the annotation-data for the (first) page using `PDFViewerApplication.pdfViewer.getPageView(0).pdfPage.getAnnotations();`, which returns a Promise that contains lot of details for each individual annotation.
From here you can map the `id`s from the `AnnotationStorage` to the correct annotation and thus lookup (in this case) the `fieldName`/`buttonValue` properties.

**Comment by Snuffleupagus** [comment]
> I am aware of though that handling of forms are not a main focus in the project.

Given this, and that https://github.com/mozilla/pdf.js/issues/16044#issuecomment-1425814323 and https://github.com/mozilla/pdf.js/issues/16044#issuecomment-1427800762 has shown how to access the requested data I don't believe that we need/want to make changes to the PDF,js library here.
Please note that we don't want to add, from the general PDF.js-library perspective, mostly "unused" data to either the DOM or the AnnotationStorage since that increases the maintenance burden (and size) of the code.

**Comment by raryanatkins** [comment]
It seems my use case is really similar to @paalg's so after a couple of days of searching, finding this issue has been incredibly helpful. Is this kind of information on the viewers centrally documented anywhere? Particularly https://github.com/mozilla/pdf.js/issues/16044#issuecomment-1425814323, I don't think I would have found. Specifically, my next step is to find a way to tap into the input event listeners which already exist to create the annotationStorage. Is that possible or should I create my own using the annotation data mentioned above?

**Comment by Talha345** [comment]
This is a valid bug as all radio buttons should have proper values in the HTML. Anybody has a solution in case I am not using the default viewer, how can I get the values for the radio buttons.

**Comment by faiq-shahzad-boolmind** [comment]
> > I am aware of though that handling of forms are not a main focus in the project.
> 
> Given this, and that [#16044 (comment)](https://github.com/mozilla/pdf.js/issues/16044#issuecomment-1425814323) and [#16044 (comment)](https://github.com/mozilla/pdf.js/issues/16044#issuecomment-1427800762) has shown how to access the requested data I don't believe that we need/want to make changes to the PDF,js library here. Please note that we don't want to add, from the general PDF.js-library perspective, mostly "unused" data to either the DOM or the AnnotationStorage since that increases the maintenance burden (and size) of the code.

While I understand that adding or manipulating the code increases the bundle size, I believe radio buttons should always have a valid value. If they don’t, form elements natively default to the value `"on"`.  

Doing something as simple as:  

```js
element.setAttribute("value", storage.getValue(id, {
  value: data.fieldValue || data.buttonValue
}).value);
```  

does, in fact, put the values into the DOM.  

I was wondering if we could add this simple fix or something similar to improve form handling?
