### ISSUE TITLE
viewer.js UMD distribution

### ISSUE THREAD

**Issue by mafar** [mozilla/pdf.js#16043]
I need to use ```web/viewer.js```  with ```require.js``` AMD but it seems its not possible with current dist.
It would be nice if viewer.js is available as UMD so that diff moodules can read this awesome library.
Any workaround for requirejs AMD ?

**Comment by Snuffleupagus** [comment]
Please note that the default viewer, i.e. https://github.com/mozilla/pdf.js#online-demo, was/is not really created to be easily re-used in custom implementations.

Please note that we even ask people to not use it as-is, please see below, hence what's asked for here is unfortunately not something that can support: http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
