### ISSUE TITLE
Chang font-family style in pdf.js

### ISSUE THREAD

**Issue by hathemi** [mozilla/pdf.js#16057]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
here's what i get inside span tag:
`<span role="presentation" dir="ltr" style="left: 144.03px; top: 433.402px; font-size: 12px; font-family: serif; transform: scaleX(1.00423);">Thirty (30) calendar days after written notice of termination to ORGANIZATION </span>`
i want to remove  **font-family: serif;** from style

how can i be able to remove iy from pdf.js or from any other place!?
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> here's what i get inside span tag:
> `<span role="presentation" dir="ltr" style="left: 144.03px; top: 433.402px; font-size: 12px; font-family: serif; transform: scaleX(1.00423);">Thirty (30) calendar days after written notice of termination to ORGANIZATION </span>`
> i want to remove **font-family: serif;** from style

First of all, this is the invisible overlay used to enable text-selection/copying and searching. Hence it's *not* related to the display of the document, and thus modifying it like you suggest doesn't really make sense.
Furthermore, as mentioned [at the top of the README](https://github.com/mozilla/pdf.js#pdfjs-) the PDF.js library is a *viewer* and not a general PDF editor library.
