### ISSUE TITLE
I hope to add the function of directly highlighting the mouse to check the text. The current function can only achieve highlighting similar to a brush

### ISSUE THREAD

**Issue by Zoloft7** [mozilla/pdf.js#16066]
I hope to add the function of directly highlighting the mouse to check the text. The current function can only achieve highlighting similar to a brush

**Comment by Snuffleupagus** [comment]
Duplicate of #14975, note in particular https://github.com/mozilla/pdf.js/issues/14975#issuecomment-1320305071.
