### ISSUE TITLE
PDF.js keyboard shortcuts for editor

### ISSUE THREAD

**Issue by reformedp** [mozilla/pdf.js#16064]
The tools in the toolbar are accessible via keyboard shortcuts. Now that the editor annotation functions are added, I would like to request that they are accessible via keyboard shortcuts as well.

**Comment by Coder-aadarsh** [comment]
They are few already
Ctrl + up arrow key - first page
Ctrl + down arrow key - last page 
etc...

**Comment by marco-c** [comment]
This is now tracked on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1853424. Closing as duplicate.
