### ISSUE TITLE
Separate History

### ISSUE THREAD

**Issue by Dinver** [mozilla/pdf.js#16069]
Hello! I need to implement separate history. I am creating app for learners, who can use the same PC and browser.

I think to implement by the with hash from url, at format:
https://www.example.com/example.pdf?v133-279
Every learner has his own version (?v133-279). Is it possible to generate hash fingerprint at url?

**Comment by Snuffleupagus** [comment]
It's unfortunately not really clear what you mean by "separate history", given the overall lack of details here.
Please keep in mind that the default viewer is created primarily for Firefox, and while it's obviously possible to extend it in various ways we however can't provide detailed help/support for that.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
