### ISSUE TITLE
Multiple Readback Warning Remove

### ISSUE THREAD

**Issue by IshmeetSingh06** [mozilla/pdf.js#16076]
I am facing this issue for the pdfjs "https://github.com/mozilla/pdf.js/issues/15662" I understood the reasoning behind why the willReadFrequently should not be true but is there a way we can disable the warnings that appear for this?, My website revolves around displaying multiple pdf's due to which these warning filling up the console 
![image](https://user-images.githubusercontent.com/76062864/220158141-644423a0-130b-4866-8114-0e48e8ccb235.png)
and this is just with viewing only 2-3 pdf .

**Comment by Snuffleupagus** [comment]
That's a warning printed by the *browser itself*, as such there's really no way for a web-app to disable that.
