### ISSUE TITLE
Navigate to a page in pdfjs

### ISSUE THREAD

**Issue by spradhan1990** [mozilla/pdf.js#16072]
Hi, i don't have any specific query. Just wanted to ask, if i have an url, like 
"rest/media/Element.Media%3A%3AVj0xfnsicklkIjoiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwib3AiOlsiVmVoaWNsZV9JU19Hb2xmQ2FydF9WZWhpY2xlT3JnIiwiSVNfRkdDX1ZlaGljbGVPcmciLCJWZWhpY2xlXzAwMDAwMDAwNTVfVmVoaWNsZU9yZ19lbi1VUyJdLCJubiI6ODgsInRzIjoxNjc2ODc3Mjk4MjY1fQ/files/5.1005.8581.0-Y.PDF?collectionId=Vehicle&contentLang=en-US&persistentId=Vehicle_0000000055_VehicleOrg_en-US&SRCType=PDF&count=-1&pageNumber=5",

what parameter i can set in url to open a pdf with page number 5. 
i mean to say, pdf should be opened with page number 5.

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Viewer-options
