### ISSUE TITLE
Rendering error 

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#16073]
Attach (recommended) or Link to PDF file here:
[bug.pdf](https://github.com/mozilla/pdf.js/files/10784480/bug.pdf)

Configuration:
- Web browser and its version: Firefox 110.0, Chrome 110.0.5481.100
- Operating system and its version: Ubuntu 22.04
- PDF.js version: v3.3.122
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the pdf in the [online viewer](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Check the error in the console

What is the expected behavior? (add screenshot)
![chrome](https://user-images.githubusercontent.com/75841/220115843-41ba971f-1aec-4f00-bcfd-e01b0c917439.png)

What went wrong? (add screenshot)
![firefox](https://user-images.githubusercontent.com/75841/220115048-56072d67-2000-44e5-8715-ae1a485d5d4e.png)
Firefox: Error in console and missing arrows above the letters (vectors).
```
An error occurred while rendering the page.

PDF.js v3.4.112 (build: 534b22aec)
Message: 
Stack: putBinaryImageData@https://mozilla.github.io/pdf.js/build/pdf.js:5393:11
paintInlineImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:6942:25
paintImageXObject@https://mozilla.github.io/pdf.js/build/pdf.js:6902:10
executeOperatorList@https://mozilla.github.io/pdf.js/build/pdf.js:5714:20
_next@https://mozilla.github.io/pdf.js/build/pdf.js:2719:37
__webpack_modules__</_scheduleNext/<@https://mozilla.github.io/pdf.js/build/pdf.js:2709:14
```
Chrome: Rendering is slow. Warning in the console:
```[Violation] 'requestAnimationFrame' handler took 1286ms```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by benbro** [comment]
Issue #6741 is about huge images. Is this the case in this issue? The pdf was generated by exporting a slide with equation to pdf with PowerPoint and I wouldn't expect it to generate a large image.
How can I check the image size in the pdf?
Is there a way to pre-process the pdf and "fix" the image?

**Comment by calixteman** [comment]
The image in this pdf is a bit problematic...
If you open the pdf with the tool mentioned by @Snuffleupagus, you can see that it has dimensions `Width = 34862, Height = 4332`.
Once the image is decompressed, it'll take ~576Mb in RGBA format and it has to be because the original image is in the RGB colorspace.
Canvas dimensions have some limits and here they're reached.
In firefox nightly, it takes around 3.5s to render when it's around 5s in Chrome: as I said in the patch, it isn't crazy but I think it's acceptable. We can probably improve performances here but very likely we won't be able to have something similar to Acrobat or Chrome.

**Comment by benbro** [comment]
@calixteman rendering is still slow even if I ignore huge images with:
```javascript
pdfjsLib.getDocument({ url: url, maxImageSize: 1024*1024 })
```
Could there be another issue besides the huge image?

**Comment by marco-c** [comment]
Maybe the image is decoded anyway, and that takes time.

**Comment by calixteman** [comment]
Here the problem is about a smask which is too large and maxImageSize as no effect on such object.

**Comment by benbro** [comment]
Should maxImageSize also limit smask size? Does the new large image PR handles smasks?
