### ISSUE TITLE
Files with relative path are not displayed in PDF viewer

### ISSUE THREAD

**Issue by Oasan01** [mozilla/pdf.js#16083]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge Versión 110.0.1587.50 (Compilación oficial) (64 bits),  Tested on chrome, mozilla with the same result
- Operating system and its version: Window 10 Pro
- Web Server: IIS 10
- PDF.js version: 3.3.122
- Is a browser extension: No
Steps to reproduce the problem:
1. Login in the application, the records are loaded with their documents
2.The viewer shows a loading error
![image](https://user-images.githubusercontent.com/54637072/221034165-1b934209-770e-4969-98a5-31bfdf431571.png)
3. When inspecting the item
![image](https://user-images.githubusercontent.com/54637072/221034432-b73670f0-30b9-4161-8a6a-dbe9cd6866f3.png)
4.We copy the link in a browser tab
![image](https://user-images.githubusercontent.com/54637072/221034726-03e39071-c5ee-4323-8099-c6c074075844.png)
5.We verify that the file exists
![image](https://user-images.githubusercontent.com/54637072/221035168-51b6172e-1bea-44f7-8e68-2fe6610e360b.png)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/54637072/221036042-57882086-54ec-447c-879c-09175a3f13c0.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/54637072/221035699-e04ffe52-34f8-4ecb-b9ae-71f5d1bcdd4a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web Server: IIS 10

It's certainly possible that this is related to the server, which we unfortunately can't really provide any help/support for here.

More generally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
