### ISSUE TITLE
水印问题

### ISSUE THREAD

**Issue by MickeyLy** [mozilla/pdf.js#16087]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:ios15.6
- PDF.js version: v3.3112
- Is a browser extension:

Steps to reproduce the problem:
1. PDF的水印不见了。
2.ios顶部工具栏可点击，但不显示文字。

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![11](https://user-images.githubusercontent.com/125754603/221169369-4a61cd13-fe2d-49d4-975a-403d1068671a.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please use only English in this bug tracker, since otherwise we can't help you!

Furthermore, please make sure that you *clearly* explain the problem (and note that Firefox is the *primary* development target for this library).
