### ISSUE TITLE
Migration guide missing?

### ISSUE THREAD

**Issue by csicky** [mozilla/pdf.js#16089]
I get this warning:
```
Deprecated API usage: The TextLayerRender `textContent`/`textContentStream`
parameters will be removed in the future, please use `textContentSource` instead.
```
I search in this github here, try to find online some documentation but all is lacking. I can't find the documentation, where I would search for these keywords to find the new way of using them. I was scrolling / searching the release notes but could not find how to migrate to new api.

**Comment by Snuffleupagus** [comment]
What the deprecation message is trying to convey, is that in the `renderTextLayer` call you need to replace the `textContent` (or `textContentStream`) parameter with the new `textContentSource` parameter instead. Basically, if you previously called it like this:
```javascript
renderTextLayer({
  textContent: page.getTextContent(),
  container: document.createElement("div"),
  viewport: page.getViewport(),
});
```
you should now replace that with:
```javascript
renderTextLayer({
  textContentSource: page.getTextContent(),
  container: document.createElement("div"),
  viewport: page.getViewport(),
});
```

Note that for the time being, the old format still works. If you need additional help, please provide a runnable example as mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
