### ISSUE TITLE
File suffix of /locale/locale.properies requires extra configuration on webserver

### ISSUE THREAD

**Issue by teson2000** [mozilla/pdf.js#16088]
The suffix of file /locale/locale.properties has no equivalent mime-type in neither IIS nor Apache.

On IIS, it causes an 404-error unless the suffix is setup. 

Configuration:
IIS7
pdfJS 3.3

Steps to reproduce the problem:
1. Load pdfJS in browser,
2. choose inspect: Failed to load resource: the server responded with a status of 404 (Not Found)

Suggested action:
* Rename .properties files to suffix with known mime-type.

**Comment by Snuffleupagus** [comment]
> The suffix of file /locale/locale.properties has no equivalent mime-type in neither IIS nor Apache.
> [...]
> Rename .properties files to suffix with known mime-type.

Sorry, but we can't support specific web-servers here. Hence such a change isn't something that we'll consider unfortunately.

Please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target for this library, and please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
