### ISSUE TITLE
[Question] Want to find a way to search for a text in pdf with occurrence, or is there a way to programmatically move to the next occurrence of the search until necassary

### ISSUE THREAD

**Issue by joelpeter94** [mozilla/pdf.js#16090]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. NA
2.

What is the expected behavior? (add screenshot)
N/A

What went wrong? (add screenshot)

Currently, `eventBus.dispatch("find", { type: "", query: SEARCH_FOR });` searches for the first occurrence of the text that is to be searched, How do I programmatically navigate to the next occurences? Thanks in advance.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Dispatch a new event, but use `type: "again"` instead.

**Comment by joelpeter94** [comment]
Thank you for the quick response. To try and find out the 10th occurrence, I tried something like this. But it did not work.

`
eventBus.dispatch("find", { type: "", query: SEARCH_FOR });
  for(let i =0;i<10;i++){
    eventBus.dispatch("find", { type: "again", query: SEARCH_FOR });
  }

`

I get the following console error as well
![image](https://user-images.githubusercontent.com/112728478/221351603-413d3a39-4005-4992-96ec-9ad0f29dc355.png)

**Comment by Snuffleupagus** [comment]
> I tried something like this to find out the 10th occurrence. But it did not work.

Like almost everything else in the PDF.js library/viewer, searching is an *asynchronous* operation. Hence you probably need to wait for an "updatefindcontrolstate" event between repeated searches to fix that. (This is basically a duplicate of issue #12014, which is a feature not really needed in the Firefox PDF Viewer.)
