### ISSUE TITLE
3.4.120 fails validation with ES5Strict mode (google closure compiler)

### ISSUE THREAD

**Issue by grammmike** [mozilla/pdf.js#16097]
Attach (recommended) or Link to PDF file here:

Configuration:
- PDF.js version: 3.4.120

commit https://github.com/mozilla/pdf.js/commit/d5c9be341d344a31bf90bccbe9ba5aa37b023d01 by https://github.com/Snuffleupagus fails to validate ES5Strict mode with google closure compiler v20230206 (https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20230206/closure-compiler-v20230206.jar)

Steps to reproduce the problem:
1. extract pdf.js
2. java -jar closure-compiler-v20230206.jar --js build/pdf-debug.js --js_output_file build/pdf.js \
  --output_wrapper="%output%//# sourceMappingURL=pdf.js.map" \
  --create_source_map build/pdf.js.map \
  --compilation_level SIMPLE --warning_level VERBOSE --jscomp_off=es5Strict --strict_mode_input=false \
  --jscomp_off=globalThis --jscomp_off=misplacedTypeAnnotation --jscomp_off=nonStandardJsDocs \
  --jscomp_off=missingProperties --jscomp_off=invalidCasts --jscomp_off=checkTypes --jscomp_warning=visibility \
  --jscomp_warning=unknownDefines --jscomp_warning=undefinedVars --jscomp_warning=strictModuleDepCheck \
  --jscomp_warning=deprecated --jscomp_error=checkVars --jscomp_warning=checkRegExp \
  --jscomp_warning=accessControls --jscomp_off=checkVars

What is the expected behavior?
pdf.js should validate ES5Strict -> widespread compatibility

What went wrong?

Failure:
build/pdf-debug.js:4534:9: ERROR - [JSC_PARSE_ERROR] Parse error. Semi-colon expected
4534|   static #docId = 0;
^^^^^^^^^
1 error(s), 0 warning(s)

**Comment by Snuffleupagus** [comment]
Please note that the only minifier we use[1] in this project is Terser, and consequently we can't provide help/support for others unfortunately; see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified

Furthermore, note that we no longer support ES5 browsers/environments; please find the currently supported browsers in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

---
[1] As-in we provide minified builds in `pdfjs-dist`, see the "min"-files in https://github.com/mozilla/pdfjs-dist/tree/master/build or https://github.com/mozilla/pdfjs-dist/tree/master/legacy/build
