### ISSUE TITLE
Form field with image are not visible

### ISSUE THREAD

**Issue by nofelkad** [mozilla/pdf.js#16099]
Acroform field with image is not visible with pdf.js. Although with adobe reader and I tried few other renderers it is visible.

Update:
This issue is with PDF.js shipped with Mozilla. It worked with pdf.js 3.4.120

PDF Link: [Sample_form_filled.pdf](https://github.com/mozilla/pdf.js/files/10850161/Sample_form_filled.pdf) (archive: [Sample PDF Zip Download](https://github.com/nofelkad/pdf-sample/archive/refs/heads/main.zip))

Configuration:
- Web browser and its version:  Mozilla 110
- Operating system and its version: Windows 10
- PDF.js version:  3.3.56

Steps to reproduce the problem:
1.   Download the zip(Link Above) and unzip the pdf 
2.   Open in latest Mozilla browser or render with sample pdf.js example 

Expected behavior in adobe reader
![image](https://user-images.githubusercontent.com/56793785/221842371-dccc57bb-0885-4176-ab5f-0c93de8874f5.png)

Not visible when opened in Mozilla

![image](https://user-images.githubusercontent.com/56793785/221842551-0740bcf9-bec9-4e5b-8989-edec71b49b77.png)

As you can see, Image is available in PDF 

![image](https://user-images.githubusercontent.com/56793785/221843237-1ef4b4e0-d5df-4e6e-a159-385bf58279c8.png)

Thanks in advance

**Comment by itsajay1029** [comment]
Can you assign this to me... I am willing to work on this

**Comment by calixteman** [comment]
Fixed by #16387.
