### ISSUE TITLE
Unable to preview pdf

### ISSUE THREAD

**Issue by dahai121** [mozilla/pdf.js#16102]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:safari
- Operating system and its version:ios14
- PDF.js version:3.1.4
- Is a browser extension:no

Steps to reproduce the problem:
1. Unable to preview pdf
2.

What is the expected behavior? (add screenshot)
![error](https://user-images.githubusercontent.com/27064521/222392549-f499221b-8866-49ac-8dbd-1e3bd5603747.jpg)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by dahai121** [comment]
version is 3.4.120

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is always required in order for any issue to be actionable/valid.

> Web browser and its version:safari
> Operating system and its version:ios14

Please find the supported browsers at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Possibly you need to use a `legacy`-build of the PDF.js library, note the two different versions at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by dahai121** [comment]
I switched to version 2.5.207-es5-dist and can use it now, thank you!
