### ISSUE TITLE
Invisible text/objects in PDFs after Firefox 109.0->110.0 upgrade

### ISSUE THREAD

**Issue by PaulSD** [mozilla/pdf.js#16113]
Attach (recommended) or Link to PDF file here:
https://dbm.maryland.gov/employees/Documents/MSRP%20Plan%20Highlights%20EZ%20Enroll.pdf
(All PDFs appear to be affected.  This is just one example.)

Configuration:
- Web browser and its version:
  - Broken in Firefox 110.0 (110.0+build3-0ubuntu0.20.04.1) and Firefox 110.0.1 (110.0.1+build2-0ubuntu0.20.04.1)
  - Works in Firefox 109.0.1 ([109.0.1+build1-0ubuntu0.20.04.2](https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/+build/25542957/+files/firefox_109.0.1+build1-0ubuntu0.20.04.2_amd64.deb)) and earlier
- Operating system and its version: Ubuntu 20.04.5
- PDF.js version: 3.3.56 (embedded in Firefox 110.0.1)
- Is a browser extension: Installed with / embedded in Firefox, not installed as a separate add-on or extension

Steps to reproduce the problem:
1. Install Firefox 110.0.1: `apt-get install firefox`
2. Run Firefox with a new profile, or `rm -rf ~/.mozilla` before running
3. Navigate to the PDF link above and observe rendering issues
4. Exit Firefox
5. Downgrade to Firefox 109.0.1: `dpkg -i firefox_109.0.1*.deb`
6. Run Firefox with a new profile, or `rm -rf ~/.mozilla` before running
7. Navigate to the PDF link above and observe correct rendering

What is the expected behavior? (add screenshot)
![Good1](https://user-images.githubusercontent.com/74427/222979715-5767adc5-5467-4737-b72e-9bd7d373a0ed.png)
![Good2](https://user-images.githubusercontent.com/74427/222979717-a506f6cd-ceea-4ae9-83f0-585c2d17b1a3.png)

What went wrong? (add screenshot)
![Bad1](https://user-images.githubusercontent.com/74427/222979729-b203ba6b-1eee-4b98-9051-49031c429ff0.png)
![Bad2](https://user-images.githubusercontent.com/74427/222979730-2fe196b3-41c0-4530-93b2-5fef8a4e8dd3.png)

Thank you!

**Comment by PaulSD** [comment]
After more digging, it looks like this is related to GPU-accelerated Canvas2D in Firefox when using VirGL acceleration in a VM.  Disabling `gfx.canvas.accelerated` in Firefox fixes the problem.

It isn't clear to me yet whether the bug is in Firefox or VirGL, but either way pdf.js is a victim not a culprit.

**Comment by calixteman** [comment]
You can file a bug for Firefox: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Graphics%3A%20Canvas2D.
