### ISSUE TITLE
The photo(e.g. .eddx format to jpeg/png) converted to pdf is obscure when enlarge the pdf

### ISSUE THREAD

**Issue by puresora** [mozilla/pdf.js#16129]
Configuration:
- Web browser and its version: edge 109.0.1518.55 and chrome 110.0.5481.105
- Operating system and its version: windows10
- PDF.js version: 3.4.120
- Is a browser extension: no

Steps to reproduce the problem:
1. as for the complexed eddx file which size is large and figure is also large（e.g. UML and font with color, pattern and so on）converted to pdf，embeding the pdf to html：<embed src="/static/pdfjs/web/viewer.html?file=/docs/pdf/android_camera_frame.pdf" width="100%" height="800" type="application/pdf"></embed>
2. Check the rendering effect on the browser and enlarge the pdf by 50%, 100% and 150%. The result is that the pdf is very blurred and can't be seen clearly

What is the expected behavior? (add screenshot)
having the effect like that The browser's own pdf plugin effect， can be clearly displayed when zoomed in

**Comment by Snuffleupagus** [comment]
The `Attach (recommended) or Link to PDF file here:`-part of the issue template is *always required* in order for any issue to be actionable/valid.
