### ISSUE TITLE
Add viewer to npm packaged library

### ISSUE THREAD

**Issue by evilaliv3** [mozilla/pdf.js#16126]
Hello!

Correct me if i'm wrong, but it seems to me that [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist ), the packaged version of the library published on NPM ,is missing to include the viewer.html file and other files.

For this reason at the moment no one is probably able to install the viewer via NPM and who want to use it is currently fetching the release via github,

This is probably causing reduced adoption of the viewer and making it more risky for users to use it; users in fact to use the library are are time to time manually downloading the new release without any automated possibility if a new library version exist.

For this reason i would find it very useful if you could include the viewer in the NPM package.

**Comment by Snuffleupagus** [comment]
The default viewer is purposely not included in `pdfjs-dist`, since it's never really intended to be used as-is in third-party implementations; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by evilaliv3** [comment]
Thank you very much @Snuffleupagus for your reply and for clarifying.

In the context of [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks/) we recognize the viewer as very valuable and we consider that is a plus to use it as not modified, because using something "official" offer for us significant guarantees of security being a component widely used and tested: 

We recognize the official viewer very valuable for many aspects:
- security
- internationalization
- stability

For this reason we are testing an integration of the client as is (https://github.com/globaleaks/GlobaLeaks/issues/3337) by means of an iframe. Would it be possible to use it that way and if not what would you recommend?

Here is an example of what we are doing:
![Screenshot 2023-03-07 at 23-34-02 GLOBALEAKS - Report](https://user-images.githubusercontent.com/217034/223569687-487fa30e-9e8a-49ea-a626-6a92d5fdd626.png)

**Comment by Priestch** [comment]
@evilaliv3 You can building a custom `pdfjs-dist` based on pdf.js to export what you want.

**Comment by Snuffleupagus** [comment]
The reason that we kindly ask that you *do not* use the default viewer unmodified is to avoid user confusion.
We do not want users to mistake your custom viewer for the *built-in* Firefox PDF Viewer (which has happened more than once), and thus coming here to report bugs that we've already fixed (because your viewer is out-of-date).

**Comment by evilaliv3** [comment]
Thank you for clarifying!

@Priestch: building a custome package and publishing it on npm is not an option that we consider. Would create confusione for mozilla.

For the moment the best option we found is to continously keep an up-to-date copy of the latest github release inside our repository, and eventually apply some minor changes in the style like what requested by @Snuffleupagus.

**Comment by evilaliv3** [comment]
@Snuffleupagus: I just wanted to update you that after your feedback and given your suggestion to not use the official mozilla viewer we have experimented implementing a very basic viewer.

I provide here the link to it in case it would be helpful to anyone.

Our viewer is very minimal and integrated by means of an iframe sandbox; files are accessed by enabling JavaScript execution but enforcing the same origin policy. In this way we are able to open files ensuring to isolate them from the rest of the application.

https://github.com/globaleaks/GlobaLeaks/tree/devel/client/app/viewer

Thank you
