### ISSUE TITLE
Using eval is strongly discouraged

### ISSUE THREAD

**Issue by erkib** [mozilla/pdf.js#16137]
When building a project that has direct or indirect dependency to pdf.js, following message is printed as error and breaks pipelines:
Use of eval in "node_modules/pdfjs-dist/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification.

Configuration:
- PDF.js version: 2.16.105
- Is a browser extension: No

Using it through ReactJS component react-pdf.

**Comment by Snuffleupagus** [comment]
Duplicate of #16061
