### ISSUE TITLE
Cannot find name 'OffscreenRenderingContext'

### ISSUE THREAD

**Issue by eldhotateam** [mozilla/pdf.js#16140]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since nothing more than a (cryptic) title unfortunately isn't enough to make an issue actionable/valid

**Comment by PabbleDabble** [comment]
@eldhotateam This might help as a work around?
https://github.com/mozilla/pdf.js/issues/15915#issuecomment-1496546614
