### ISSUE TITLE
No response when displaying some pdfs on websites using PDF.js from iOS16 WebKit

### ISSUE THREAD

**Issue by Nao-RandD** [mozilla/pdf.js#16149]
Attach (recommended) or Link to PDF file here:
https://www.kitaiku.com/wp-content/uploads/2019/09/f60e89a5a2c92a649cd550661c9954dc.pdf
If the file is more than 10MB or more than 10P pdf, there is a high probability that it will be reproduced.

Configuration:
- Web browser and its version: Safari 16 and corresponding WebKit
- Operating system and its version: iOS 16 or later
- PDF.js version: v3.4.120 (latest as of 2023/3/13)
- Is a browser extension: none

Steps to reproduce the problem:
1. prepare a pdf file that meets one of the following criteria: 10MB or 10P or more
2. access the pdf.js demo page with Safari or an app using WebKit (https://mozilla.github.io/pdf.js/web/viewer.html)
3. click the "Open File" button to open the file selection dialog
4. select the PDF file you prepared in step 1
5. scroll, zoom in/out, etc. on the displayed

What is the expected behavior? (add screenshot)
- PDF can be viewed in response to the operation.

What went wrong? (add screenshot)
- Operation becomes impossible
<img width="240" alt="image" src="https://user-images.githubusercontent.com/72324850/224632941-c241035e-4660-4ab4-9cb2-95a22a04b560.PNG">

Supplemental information
- This does not occur on iOS 14 and 15.
- When WKWebView is frozen, the app itself is running and UIButton and other functions are working.
- The same website cannot be operated even when opened on the Safari app of iOS16.
- In Safari, disabling GPU DOM Rendering in the device settings improves the issue (SFSafariViewController also improves as if the settings are synced).
- (The problem cannot be improved because it cannot be disabled in WKWebView settings.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Operating system and its version: iOS 16 or later
> [...]
> This does not occur on iOS 14 and 15.

Based on the above this really sounds like a regression in the browser/platform itself, rather than a PDF.js issue as such, and consequently it's unfortunately difficult to see that we can realistically address it here (and please keep in mind that Firefox is the primary development target).
Most likely, this needs to be reported to Apple instead.
