### ISSUE TITLE
Question: why is a warning triggered when scripting is wilfully disabled?

### ISSUE THREAD

**Issue by xmo-odoo** [mozilla/pdf.js#16158]
I guess that's a bit of a policy issue, but in the default viewer when scripting has been wilfully disabled (`enableScripting` set to `false`), warnings that javascript support is not enabled are emitted to the console (I assume when scripting is found in the document): https://github.com/mozilla/pdf.js/blob/5e4b3d13ebc6eb2453f0cad12f33964e2d4fc6fc/web/app.js#L1448-L1454

But that's the intent of whoever toggled that setting, the only primary result seems to be that if some sort of error reporting is embedded in the application it gets triggered any time a user tries to view a pdf with scripting (information most of them don't get and may not even be aware of).

The naming in this function also seems a bit odd, as `javaScript` is `true` (/ truthy) if scripting is disabled.

**Comment by Snuffleupagus** [comment]
In many cases disabling of scripting-support will "break" various intended functionality in the PDF document, such as e.g. form-validation, and the warning is consequently intended to help indicate to *the end-user* that certain features may not be working as intended by the creator of the PDF document.

Also, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by lcl45** [comment]
@xmo-odoo did you disabled scripting dinamically? Because I'm trying to do that with no fortune. I'm also using the default viewer opened using an url like http://host/pdf/viewer.html?file=my.pdf, adding the following code in a script tag
```javascript
document.addEventListener('DOMContentLoaded', function () {
    if (window.PDFViewerApplicationOptions) {
          PDFViewerApplicationOptions.set("disablePreferences", true);
          PDFViewerApplicationOptions.set("enableScripting", false);
          PDFViewerApplicationOptions.set("isEvalSupported", false);
          PDFViewerApplication.run();
    }
});
```
This, however, does not trigger the message you are talking about. I saw that log when searching for a solution for my issue.
