### ISSUE TITLE
Display all the pages of a large pdf in nextjs

### ISSUE THREAD

**Issue by ruppo-912116** [mozilla/pdf.js#16161]
package name with version:
  "pdfjs-dist": "^3.4.120",
  "next": "13.2.3" 

I'm trying to load all the pages of a large pdf while utilizing caching behavior i.e. fewer pages are displayed first and other slowly starts rendering. I did implement it on vanilla js using the following code. 

```
window.onload = function () {
    const pdfContainer = document.getElementById('viewerContainer')
    const pdfViewer = new pdfjsViewer.PDFViewer({
        container: pdfContainer,
        eventBus: new pdfjsViewer.EventBus()
    });
    window.pdfViewer = pdfViewer;
}
```
That pdf version was `2.5.207` and now i can't access the pdfViewer in the newer version. How do i implement it now? Can someone help?

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
