### ISSUE TITLE
Duplicate Key Id in PDF. Unable to set value in field.

### ISSUE THREAD

**Issue by Lakhtar-kays** [mozilla/pdf.js#16167]
Hi  Team,

Greeting of the day!! I am facing a typical challenge with XFA forms, nearly close to what you shared. 

IRCC XFA Ref: **https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257b_1.pdf**  

In this XFA form, the **fieldid and dataid** values are duplicates for multiple controls. E.g. <familyname>  

For example:  

`{ 
        "name": "textarea", 
        "attributes": { 
            "dataId": "**field284442**", 
            "fieldId": "**field284442**", 
            "class": [ 
                "xfaTextfield" 
           ], 
            "aria-label": "Question 1 Family name as shown on your passport or travel document", 
            "aria-required": true, 
            "required": true, 
            "tabindex": 5002, 
            "maxLength": 100 
        } 
    } 
] `

  

![image](https://user-images.githubusercontent.com/85861166/225877671-0056d67c-fe63-419d-be60-256697c54cb7.png)
 

![image](https://user-images.githubusercontent.com/85861166/225877799-8c4b6d31-4329-4ff1-8a5a-361446d78c02.png)

Issue: If I want to update the <**field284442**> with value {john}, the code does not work due to duplicate id. 

`pdf.annotationStorage.setValue('field284342', { value: 'John' }); `

Could you help me with: 
1. If there is we can avoid the duplicates; and update the text control to set value?  
2. is there any way so that we can traverse to that particular child node and set value? 

Any sample code, link to a solution or inputs are highly appreciated.  

Thanks in advance.

**Comment by calixteman** [comment]
I don't find id `field284442` in the attached pdf. Could you give us either the correct pdf or the correct id ?
Thank you.

**Comment by Lakhtar-kays** [comment]
Reason behind this is, ID change when we parse it to xfa everytime.
I am using this tool to get XFAHTML

https://steady-dragon-8cfedd.netlify.app/
https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257b_1.pdf

Please put this URL in this tool and you will get the JSON
then you can search the text "dataId" 
then you will find that "dataId" and "field29324" are same for "textarea" and "text" fields.

Another example from that tool is 

![image](https://user-images.githubusercontent.com/85861166/225980937-18cb73be-7591-41ad-8490-ec228ec56025.png)

![image](https://user-images.githubusercontent.com/85861166/225981027-8c76e418-34a5-45fc-8f24-a444a097440b.png)

I hope this will help you to find out the field ID

Thanks in advance

**Comment by Snuffleupagus** [comment]
> I am using this tool to get XFAHTML
> https://steady-dragon-8cfedd.netlify.app/

Please note that the mentioned tool has absolutely *no relation* to the PDF.js library, since it's not developed here, hence we cannot provide any help/support for it.

**Comment by Lakhtar-kays** [comment]
Hi 
I am just giving you reference that from that tool you can get the field otherwise I am using your pdf.js Library to get the XFAHtml and the reference about field id

and to set the value.

But you can parse this pdf and once you will search the dataid you will get duplicate keys 
which create conflict while setting the value in field.

Reference to your code.

![image](https://user-images.githubusercontent.com/85861166/226099466-a3743a61-dece-47bf-ba11-0aaa3b988e06.png)

**Comment by Snuffleupagus** [comment]
Sorry, but this issue is unfortunately very difficult to understand and thus isn't really actionable.
 - When opening an issue, please actually fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with *all* requested information. In this case the `Steps to reproduce the problem:`-part is most important, and should contain a clear and concise list of steps needed to reproduce the problem.
 
 - Furthermore, screen-shots of code is not really helpful; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
   > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

 - Finally, please try to avoid references to any external tools. Part of the confusion here stems from the repeated references to such a tool, since it could just as well be that tool which provides you with inaccurate information.
