### ISSUE TITLE
Getting the current visible page in nextjs

### ISSUE THREAD

**Issue by ruppo-912116** [mozilla/pdf.js#16177]
Configuration:
- PDF.js version: 2.5.207

I'm trying to get the current page number on scrolling pdf page but the scroll event doesn't trigger. Is there a way to get the current visible page from pdfjs directly? Currently, I have loaded pdf.js, pdf.worker and pdf.viewer script inside _document file so it becomes accessible globally via the window object. 

The classnames `pdfViewer` comes from https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/web/pdf_viewer.css.

Problems:
1. scrolling the pdf does not trigger the `handleOnScroll` method.
2. pdfViewer._currentPageNumber only gives output 1 (the first page) when logging inside `window.addEventListener('scroll')`.

Here a code snippet:

```
const [pdfViewer, setPdfViewer] = useState<any>(null);
  useEffect(() => {
    const pdfContainer = document.getElementById('viewerContainer');
    if (typeof window !== 'undefined') {
      setPdfViewer(
        new window.pdfjsViewer.PDFViewer({
          container: pdfContainer,
          eventBus: new window.pdfjsViewer.EventBus(),
        }),
      );
    }
  }, []);

  useEffect(() => {
    if (!pdfViewer || !file.fileObj) return;
    window.pdfjsLib.getDocument(file.fileObj).promise.then((pdf: any) => {
      pdfViewer.setDocument(pdf);
      setPdfObject(pdf);
    });
  }, [file.fileObj, pdfViewer]);

  const handleOnScroll = () => {
    console.log('scrolled');
  };

  return (
    <div id='viewerContainer' style={{ position: 'relative' }}>
      <div id='viewer' className='pdfViewer' onScroll={handleOnScroll}></div>
    </div>
  );

```
How do i get the current visible page number? I used the older version of pdf.js i.e. 2.5.207 because it had exported pdfjsViewer and i didn't need to handle rendering all the pages at once.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.5.207

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Here a code snippet:

As previously mentioned, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

You should probably base your code on an up-to-date version of e.g. the `simpleviewer` instead, see https://github.com/mozilla/pdf.js/tree/master/examples/components
Please keep in mind that we can't support Next.js (or other frameworks here).
