### ISSUE TITLE
Selected text is not highlighted

### ISSUE THREAD

**Issue by Li-Xiang-Ideal** [mozilla/pdf.js#16170]
Attach (recommended) or Link to PDF file here: Any, e.g.
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/11010468/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Edge 112.0.1722.11 (Official Build) beta (64-bit)
- Operating system and its version: Windows 10 Home 22H2 19045.2728
- PDF.js version: latest
- Is a browser extension: It doesn't matter

Steps to reproduce the problem:
1. Open, e.g. https://mozilla.github.io/pdf.js/web/viewer.html
2. Select a piece of text
3. The selected text is not highlighted as before.

What is the expected behavior?
The selected text is highlighted. (It functions as expected in Edge 108.0.1462.76 (Official Build) (64-bit))
![Screenshot 1](https://user-images.githubusercontent.com/54926635/226161026-39255ad2-384c-4785-865a-0fe8022de7b4.jpg)

What went wrong?
The selected text is not highlighted. (Here "Trace-based" is selected, you see the EdgeTranslate Addon popup)
![Screenshot 2](https://user-images.githubusercontent.com/54926635/226161465-0307035f-9543-4ba7-a64d-fdfc2ab22fb8.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
e.g. https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Edge 112.0.1722.11 (Official Build) beta (64-bit)
> [...]
> (It functions as expected in Edge 108.0.1462.76 (Official Build) (64-bit))

That information would suggest a regression in the *browser itself*, rather than a PDF.js library bug. Furthermore, please keep in mind that Firefox is the primary development target for this library.

> (Here "Trace-based" is selected, you see the EdgeTranslate Addon popup)

It's also very possible that the addon, which we know nothing about here, could be the what's breaking things.

**Comment by Li-Xiang-Ideal** [comment]
Thanks for your reply. I've sent a feedback to Microsoft on the same issue. BTW, this problem still occurs after the addon has been uninstalled.
