### ISSUE TITLE
textContent only returns high surrogate 

### ISSUE THREAD

**Issue by t-ashula** [mozilla/pdf.js#16176]
Attach (recommended) or Link to PDF file here:
https://github.com/t-ashula/pdfjs-test/blob/master/20bb7.pdf

Configuration:
- Web browser and its version: node 18
- Operating system and its version: ubuntu 22.04/WSL2
- PDF.js version: 3.4.120
- Is a browser extension: no

Steps to reproduce the problem:
1. git clone https://github.com/t-ashula/pdfjs-test
2. npm i && npx npx ts-node --esm main.ts

What is the expected behavior? (add screenshot)
`{"text":"𠮷"}`

What went wrong? (add screenshot)
`{"text":"\ud842"}`

**Comment by Snuffleupagus** [comment]
Note that it's broken in Adobe Reader, i.e. the PDF reference implementation, as well.
