### ISSUE TITLE
Whether the display layer should be modified to add additional information to the text?

### ISSUE THREAD

**Issue by ssppest** [mozilla/pdf.js#16178]
Hi everyone~
I want to add some additional information to the text, such as a custom id, to make it easier to use the code to find the specific text.
After looking at some source code, I found that I could add custom properties to add additional information when the appendText function of display/text_layer.js generates a span element containing text.
https://github.com/mozilla/pdf.js/blob/33f5d94f23f16073dd35cecebe88065b0d4bc43d/src/display/text_layer.js#L157-L168
Should I do this? There are other, more elegant ways to do this?

**Comment by Snuffleupagus** [comment]
> Should I do this? There are other, more elegant ways to do this?

We cannot decide that for you, and you've also not clearly explained why you need to do this (or what sort of information you intend to add to the DOM).
Generally speaking, there's two arguments against doing that: First of all, any modifications to that part of the code-base could make it more difficult for you to update to new PDF.js versions. Secondly, adding a bunch of additional data to the DOM *might* affect overall performance for large documents with lots of text.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that any issue becomes easily actionable.

**Comment by ssppest** [comment]
> > Should I do this? There are other, more elegant ways to do this?
> 
> We cannot decide that for you, and you've also not clearly explained why you need to do this (or what sort of information you intend to add to the DOM). Generally speaking, there's two arguments against doing that: First of all, any modifications to that part of the code-base could make it more difficult for you to update to new PDF.js versions. Secondly, adding a bunch of additional data to the DOM _might_ affect overall performance for large documents with lots of text.
> 
> _For future reference:_ When opening an issue, please provide _all_ of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that any issue becomes easily actionable.

For example, in a pdf there is a piece of text 

> The trees, the river, everything. Like nothings changed. Not true of course, everything' s changed. If I brought my parents back here now, they probably wouldn't recognize any of it.

In the div of the text layer, it looks like this
![图片](https://user-images.githubusercontent.com/6449253/226297996-629b65a6-1a1f-47e5-864d-92b5c803ff9c.png)
Now I want to be able to find that sentence directly through something like document.getElementById and highlight it
So should I modify text_layer.js to add additional information to span like custom id to locate it? like this?
![图片](https://user-images.githubusercontent.com/6449253/226299274-b727753f-3c6f-49b6-bdec-7d966abf9df0.png)
Or is there another way(method) to identify the text and locate the text?
Thanks for your reply.

---
sorry for issue format
