### ISSUE TITLE
Server Side Save

### ISSUE THREAD

**Issue by azeemiqbalatITS** [mozilla/pdf.js#16174]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: MSEdge,Chrome
- Operating system and its version:Windows 10/11
- PDF.js version:Latest
- Is a browser extension: Not sure

I would like to use the viewer.html application with minimal modifications. The only thing I am lookin for is to have teh save function send the modified pdf back to a server side application page where I can do the storing of the document. My backend application is in Coldfusion.

Thank you for your assistance.

**Comment by Snuffleupagus** [comment]
> I would like to use the viewer.html application with minimal modifications.

Please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

> The only thing I am lookin for is to have teh save function send the modified pdf back to a server side application page where I can do the storing of the document.

Sorry, but we don't provide any such functionality here since that's not relevant to the primary use-case (which is the *built-in* Firefox PDF Viewer).
