### ISSUE TITLE
Transform rectangle coordinates pdfjsLib.OPS.rect

### ISSUE THREAD

**Issue by Ana0112** [mozilla/pdf.js#16184]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Ubuntu
- PDF.js version: "https://mozilla.github.io/pdf.js/build/pdf.js"
- Is a browser extension: using in html/js code

Steps to reproduce the problem:
1. 
 ```
page.getOperatorList().then(opd => {
        return opd;
    })
  .then(opList => {
      for (let i = 0; i < opList.fnArray.length; i++) {
        const fn = opList.fnArray[i];      
        if (fn === pdfjsLib.OPS.constructPath) {
          const args = opList.argsArray[i];
    if (args[0] === pdfjsLib.OPS.rect) {
            console.log(args)
}}}
}) 
})
```

output: args - ```[[19], [3600, 7336.8, 1862.4, 4.80078], [3600, 5462.4, 7336.8, 7341.60078]]```

What is the expected behavior? (add screenshot)
The output args - has two rectangle coordinates. The viewport transform is as follows 
```
{
    "viewBox": [
        0,
        0,
        595.68,
        841.68
    ],
    "scale": 1,
    "rotation": 0,
    "offsetX": 0,
    "offsetY": 0,
    "transform": [1,0,0,-1,0,841.68],
    "width": 595.68,
    "height": 841.68
}

```
What went wrong? (add screenshot)
I want to get the coordinates of the rectangle with respect to pdf. The x-coordinate of rectangle here is 3600; which is meaningless because the width of the pdf itself is `595.68`. So, how should i interpret the rect coordinates, and convert them to something that is wrt the pdf?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that this part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> Steps to reproduce the problem:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Most likely there's a `transform` operator (or even multiple ones) prior to the path-rendering operator in question, but given the overall lack of details (as mentioned above) we can't really provide much help/support here.

**Comment by Ana0112** [comment]
Hi @Snuffleupagus ,
Thank you for responding. Makes sense that I add a working code and the pdf.
Have updated the original post with the [codesandbox link](https://codesandbox.io/s/frosty-fog-sm516x?file=/public/index.html) to the working code.
Thank you

**Comment by Ana0112** [comment]
I couldn't figure out how & when to use the `transform`/`save`/`restore` operator. If you can share an example, that would be of great help. 
I am new to `pdfjsLib`, if not example code, can you point me to something that explains output/workings of `pdfjsLib.OPS.`  in more detail. e.g. why each `args` has 2 rectangles. Are these 2 different coordinate systems? How are these rectangles calculated.

**Comment by Snuffleupagus** [comment]
First of all, you'll need to familiarize yourself with the relevant sections of the PDF specification since our implementation is (mostly) following that. Please note that the file-format itself is unfortunately quite big and complex.

Basically, you'll need to write a parser that handles transform/save/restore operators, such that you're able to compute the "current transformation matrix" (CTM) needed to correctly parse the path-rendering operators.

> e.g. why each `args` has 2 rectangles.

Please just ignore the *second one*, since that's an internal PDF.js implementation details.

**Comment by Ana0112** [comment]
Hey, I need more help.

I tried going through this [issue ticket](https://github.com/mozilla/pdf.js/issues/10535). The x-coordinate of the rect i am getting is way too large so i need to transform the rect coordinates, as you said earlier. 

I have viewport.transform ```["scale": 1, "rotation": 0, "offsetX": 0, "offsetY": 0, "transform": [1,0,0,-1,0,841.68], "width": 595.68, "height": 841.68]``` & the rect coordinates ```[3600, 7336.8, 1862.4, 4.80078]``` in some other coordinate system 

I dont know how to get this transformation matrix.  

Checkout out this [issue](https://github.com/mozilla/pdf.js/issues/5643#issuecomment-69969258), couldn't figure how to do this for my case involving rectangle.

Possible to share some ref. code? 

Thank you

**Comment by Ana0112** [comment]
Hi @Snuffleupagus 

After following this text on [affline transformations](https://math.hws.edu/graphicsbook/c6/s5.html) I did matrix multiplication to get the new coordinates.

```[x y 1] = [3600, 7336.8, 1]```
```[a,b,c,d,e,f] = [1,0,0,-1,595.68,841.68]```


X = ```[x1   x2   1] ```      

A = 
``` a   b   0 ```
``` c   d   0 ```
``` e   f   1 ```

```[x_new   y_new   1] = X * A ```  =    ```[4195   -6495   1]```

The new x,y coordinates are again way off. The width of pdf is ```595.68``` & the height is ```841.68```

**Comment by Snuffleupagus** [comment]
As already mentioned, you need to parse the `transform`, `save`, and `restore` operators to compute the CTM (current transformation matrix) and then use *that one* when computing the values gere; basically something like `pdfjsLib.Util.transform(ctm, /* rect coords here */);`.

**Comment by Ana0112** [comment]
@Snuffleupagus  , thank you for giving direction.

Code: [Codesandbox link](https://codesandbox.io/s/frosty-fog-sm516x?file=/public/index.html)

What i am doing is - 
1. Get the coordinates of first rectangle
2. For that rectangle, initialise the ```ctm = [1,0,0,1,0,0]```
3. Find ```OPS.transform``` , ```OPS.save``` , ```OPS.restore``` operators, and update the ```ctm```
4. Final get the new coords of rect - which are all ```NaN```

What am i doing wrong here?


```
   page.getOperatorList().then(opd => {
        // debugger;
        return opd;
    })
  .then(opList => {
      // Extract lines from the operator list
      const lines = [];
      var stack = [];
      var ctm = [1, 0, 0, 1, 0, 0];
      for (let i = 0; i < opList.fnArray.length; i++) {
        const fn = opList.fnArray[i];
        
        if (fn === pdfjsLib.OPS.transform) {
          const args = opList.argsArray[i];  
          var matrix = args; //[145, 0, 0, 32, 28.346, 774.674]
          ctm = pdfjsLib.Util.transform(
                    ctm,
                    matrix[0],
                    matrix[1],
                    matrix[2],
                    matrix[3],
                    matrix[4],
                    matrix[5]
                  );

          console.log(i);
          debugger;
        } else if (fn === pdfjsLib.OPS.save) {
          // Save the current CTM on the stack
          stack.push(ctm.slice());
          console.log('save',i);
          // debugger;
        } else if (fn === pdfjsLib.OPS.restore) {
          // Restore the CTM from the top of the stack
          ctm = stack.pop();

          console.log('restore', i, ctm);
          // debugger;
        }

        }

        var rect_new = pdfjsLib.Util.transform(ctm, [3600, 7336, 1]);
      })

```

**Comment by Snuffleupagus** [comment]
> const args = opList.argsArray[i];  
>           var matrix = args; //[145, 0, 0, 32, 28.346, 774.674]
>           ctm = pdfjsLib.Util.transform(
>                     ctm,
>                     matrix[0],
>                     matrix[1],
>                     matrix[2],
>                     matrix[3],
>                     matrix[4],
>                     matrix[5]
>                   );

This doesn't look right, since it should be `ctm = pdfjsLib.Util.transform(ctm, args);`; note https://github.com/mozilla/pdf.js/blob/c706c6c34f4c47e75b116027b68987d9a238ca78/src/shared/util.js#L717-L727

**Comment by Ana0112** [comment]
ok, right. Changed. Now getting the original rect as the new rect coordinates. 
CTM eventually is the identity matrix.

Updated full Code: [Codesandbox link](https://codesandbox.io/s/frosty-fog-sm516x?file=/public/index.html)


``` 
if (args[0][0] === pdfjsLib.OPS.rectangle) {
                console.log(args[1]);
                // get the rectangle coords;
                var rect = [args[1][0], args[1][1]];
                var stack = [];
                var ctm = [1, 0, 0, 1, 0, 0];
                for (let i = 0; i < opList.fnArray.length; i++) {
                  const fn = opList.fnArray[i];
                  if (fn === pdfjsLib.OPS.transform) {
                    const args = opList.argsArray[i];
                    var matrix = args; //[145, 0, 0, 32, 28.346, 774.674]
                    ctm = pdfjsLib.Util.transform(ctm, args);

                    console.log("transform", i, ctm);
                    // debugger;
                  } else if (fn === pdfjsLib.OPS.save) {
                    // Save the current CTM on the stack
                    stack.push(ctm.slice());
                    console.log("save", i, ctm);
                    // debugger;
                  } else if (fn === pdfjsLib.OPS.restore) {
                    // Restore the CTM from the top of the stack
                    ctm = stack.pop();

                    console.log("restore", i, ctm);
                  }
                }

                var rect_new = pdfjsLib.Util.applyTransform(rect, ctm);
                console.log("transformed rectangle coordinates", rect_new);
                break;
              }
```

**Comment by Ana0112** [comment]
also i had a thought, since all these operators - ```transform```, ```save```, ```restore``` were applied to the original (coordinates acc. to the pdf) rectangle coordinates, shouldn't i perform _inverse_  operator on the rect coordinate - starting from last operator (save/restore/transform) being applied first?

PS i tried applying operators with last operator being the first, but i still couldnt get a reasonable looking coordinates. Didnt do the inverse transform here.

@Snuffleupagus

**Comment by Snuffleupagus** [comment]
You can't "nest" the parsing like done in https://github.com/mozilla/pdf.js/issues/16184#issuecomment-1483010153, since the operators occur in sequence. Basically you need to do something like the follow sketch:
```javascript
const await opList = getOperatorList();
for (let i = 0, ii = opList.fnArray.length; i < ii; i++) {
  const fn = opList.fnArray[i],
    args = opList.argsArray[i];

  switch (fn) {
    case OPS.save:
      ...
      break;
    case OPS.restore:
      ...
      break;
    case OPS.transform:
      ...
      break;

    case OPS.constructPath:
      // Here you iterate through the path-rendering operators to find a rectangle entry.
      ...
      break;
  }
}
```

**Comment by Ana0112** [comment]
Thanks @Snuffleupagus, I am getting some meaningful values now! 
Need to check if i should subtract the y from height. And generally cross check where are these coordinates of the pdf.

**Comment by peshdnxt** [comment]
@Ana0112 - did you manage to resolve what you needed. I am looking to do the same thing and have been stuck for a while
