### ISSUE TITLE
Simplify our css in using :is or :where 

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#16194]
For reference:
 - https://developer.mozilla.org/en-US/docs/Web/CSS/:is
 - https://developer.mozilla.org/en-US/docs/Web/CSS/:where

**Comment by calixteman** [comment]
For example:
https://github.com/mozilla/pdf.js/blob/f39ff20485014a8782ca71844ed01d72f7c2ac91/web/viewer.css#L330
Probably few others for annotations.

I didn't know either :is or :where before today.

**Comment by tymnec** [comment]
**It's worth noting that :is() and :where() are not supported in all browsers yet**

Assign this issue to me I will simplify *viewer.css*

**Comment by tymnec** [comment]
Assign this issue to me I will simplify *viewer.css*

**Comment by Snuffleupagus** [comment]
Sorry, but this may not be an ideal beginner bug without any prior PDF.js experience (given that any changes require careful manual testing). Furthermore, as outlined in https://github.com/mozilla/pdf.js/issues/16194#issuecomment-1479351592 this potentially applies to all our CSS-files (and not just one).

**Comment by tymnec** [comment]
I understood, Thanks for reply. Can You suggest me some beginner friendly issues I would like to work on PDF.js
