### ISSUE TITLE
pdf.jsv3.4.120  dose not working in mobile

### ISSUE THREAD

**Issue by cff-github** [mozilla/pdf.js#16205]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:v3.4.120
- Is a browser extension:

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html in mobile

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by cff-github** [comment]
![image](https://user-images.githubusercontent.com/69131256/227589515-a81a1da2-743e-4975-9fb8-1db13cb7b428.png)

**Comment by Snuffleupagus** [comment]
> * Web browser and its version:
> * Operating system and its version:

This information is required when opening an issue; please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

---

Most likely you need to use a `legacy`-build, note the two versions at https://github.com/mozilla/pdf.js#online-demo and the two downloads at https://mozilla.github.io/pdf.js/getting_started/#download
