### ISSUE TITLE
Unable to change locale dynamically

### ISSUE THREAD

**Issue by linxianxi** [mozilla/pdf.js#16202]
Steps to reproduce the problem:
1. go https://mozilla.github.io/pdf.js/web/viewer.html
2.  open browser F12
3. input  `document.webL10n.setLanguage("zh-CN")`  or `PDFViewerApplicationOptions.set("locale", "zh-CN")`

What is the expected behavior? (add screenshot)
change locale

What went wrong? (add screenshot)
nothing happend

I searched for other issues, but does not worked

**Comment by linxianxi** [comment]
solved. must run `document.webL10n.transalte()` after set locale

**Comment by Snuffleupagus** [comment]
Please note that this is *not* officially supported, hence the work-around from https://github.com/mozilla/pdf.js/issues/16202#issuecomment-1482194727 is not guaranteed to work correctly in all cases.
