### ISSUE TITLE
Start offset undefined is outside the bounds of the buffer

### ISSUE THREAD

**Issue by zhousisi9900** [mozilla/pdf.js#16215]
Attach (recommended) or Link to PDF file here:
a 1GB file for pdf
Configuration:
- Web browser and its version: chrome 111.0.5563.111
- Operating system and its version: win10 19044.2728
- PDF.js version: v3.4.120
- Is a browser extension:

Steps to reproduce the problem:
1. just open that file

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

PDF.js v3.4.120 (build: af6414988)
Message: Start offset undefined is outside the bounds of the buffer

Uncaught (in promise) UnknownErrorException {message: 'Start offset undefined is outside the bounds of the buffer', name: 'UnknownErrorException', details: 'RangeError: Start offset undefined is outside the bounds of the buffer'}

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> a 1GB file for pdf

Without access to said file, this issue (or any issue really) unfortunately isn't actionable.

**Comment by zhousisi9900** [comment]
> > Attach (recommended) or Link to PDF file here:
> > a 1GB file for pdf
> 
> Without access to said file, this issue (or any issue really) unfortunately isn't actionable.

i can not  upload that file，cause github only allowed 25MB  but the file is larger than 1GB
can you create a pdf over 1GB  and use offical demo to test？
it can recurrent this bug。
