### ISSUE TITLE
pdfjs-dist canvas module parse failed

### ISSUE THREAD

**Issue by JasperAlexander** [mozilla/pdf.js#16214]
I'm trying to use pdfjs-dist (v3.4.120) in my package, but when I test this package in my client-side Next.js frontend, I'm getting the following error. 
```sh
./node_modules/mypackage/node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/mypackage/node_modules/canvas/build/Release/canvas.node
./node_modules/mypackage/node_modules/canvas/lib/bindings.js
./node_modules/mypackage/node_modules/canvas/index.js
./node_modules/mypackage/node_modules/pdfjs-dist/legacy/build/pdf.js
./node_modules/mypackage/dist/index.js
./app/page.tsx
```
I can solve this by using the following webpack config in my Next.js frontend, but I don't want other people that want to use my package to have to set this config. How to solve this problem in my package?
```js
webpack: (config) => {
    config.resolve.alias.canvas = false
    config.resolve.alias.encoding = false
    return config
},
```
I'm using the folllowing imports in my package:
```tsx
import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf'
pdfjsLib.GlobalWorkerOptions.workerSrc = require('pdfjs-dist/build/pdf.worker.entry.js')
```

**Comment by Snuffleupagus** [comment]
> but when I test this package in my client-side Next.js frontend,

Sorry, but that's not a Framework that we use or know anything about here; hence we unfortunately can't provide any help/support for it.

> I'm getting the following error.

Given that the error *seem* to happen in the `canvas` npm-package, which is (optionally) used for Node.js compatibility, this unfortunately doesn't really look actionable here and given the plethora of Frameworks that exist we (again) can't really help.
