### ISSUE TITLE
The `gh-pages` branch is no longer being updated

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#16210]
The `gh-pages` branch, and thus the demo-viewer at https://mozilla.github.io/pdf.js/web/viewer.html, hasn't been updated after the latest couple of merges.
The last update was *after* PR #16196 landed, and given the timing I wonder if the Windows-bot is now running into the following?
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by calixteman** [comment]
I ran `ssh-keygen -R github.com` on the windows bot so it should be fine now.

**Comment by Snuffleupagus** [comment]
Unfortunately that doesn't seem to have fixed the problem, since I merged a simple patch afterwards (see PR #16211) and the `gh-pages` branch didn't update, so the issue must be elsewhere :-(

**Comment by timvandermeij** [comment]
Marking this as a release blocker since I'm not sure how this will affect e.g. pushing to `pdfjs-dist`.

**Comment by calixteman** [comment]
There was a popup asking a question about ssh so I guess it should be fixed now since I answered to them.

**Comment by timvandermeij** [comment]
Closing since this is indeed fixed now; the recent merge did update `gh-pages` again. Thanks!

(It might be prudent though to run the same steps on the Linux bot, just in case.)
