### ISSUE TITLE
Pdf.js canvas not rendering on smartphone rotation

### ISSUE THREAD

**Issue by dwatsp** [mozilla/pdf.js#16219]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 108.0.5359.128
- Operating system and its version: Andriod 12; SM-S908B Build/SP1A.210812.016
- PDF.js version: current preview page
- Is a browser extension:

Steps to reproduce the problem:
1.  Open The demo page with the demo pdf
2. rotate device excessively 

What is the expected behavior? (add screenshot)
 PDF should be rendered completely

What went wrong? (add screenshot)
PDF Canvas is missing or only partially rendered:
![image](https://user-images.githubusercontent.com/128708919/227935756-a7582ce1-8c66-4279-862f-4fb6837c2ad4.png)
![image](https://user-images.githubusercontent.com/128708919/227936056-9a32f463-e1bd-4b46-a9ca-9090dd658542.png)

(Other PDF but I assume it is the same bug)
![image](https://user-images.githubusercontent.com/128708919/227936280-4b2500f9-fb61-4ee6-8762-ceb89eab7f5b.png)

**Comment by Snuffleupagus** [comment]
WFM, using Firefox on Android. This unfortunately looks like a *browser issue*, rather than a bug in the PDF.js library/viewer.
