### ISSUE TITLE
Showing textContent even when pdf is not searchable

### ISSUE THREAD

**Issue by Ana0112** [mozilla/pdf.js#16233]
Attach (recommended) or Link to PDF file here:
[statement.pdf](https://github.com/mozilla/pdf.js/files/11110252/statement.pdf)

Configuration:
Web browser and its version: Chrome
Operating system and its version: Ubuntu
PDF.js version: 3.4.120
Is a browser extension: using in html/js

Steps to reproduce the problem:
1. Pls run this code in [codesandbox](https://codesandbox.io/s/kind-framework-fhtfrq?file=/public/index.html)

What is the expected behavior? (add screenshot)
If you download this pdf, you will see that it is not searchable. So, on doing `getTextContent` I should have gotten an empty array.

What went wrong? (add screenshot)
`PDF.js` is returning texts from this non searchable pdf. Also, all the text lines are not being returned. Only partial text data is being returned.
Is there anyway i can ensure that if the pdf is non searchable the `getTextContent` should return null

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> If you download this pdf, you will see that it is not searchable. So, on doing `getTextContent` I should have gotten an empty array.

Adobe Reader, i.e. the PDF reference implementation, searches that document (mostly) fine. As does the PDF.js default viewer, hence this issue is unfortunately INVALID.

> Also, all the text lines are not being returned. Only partial text data is being returned.

Given that the document looks like is was scanned and then had OCR run on it, that's somewhat expected since that kind of work-flow will never give perfect results.
