### ISSUE TITLE
PDFPageProxy commonObjs always empty

### ISSUE THREAD

**Issue by serbanstef** [mozilla/pdf.js#16236]
Attach (recommended) or Link to PDF file here:
[TagsFonts2.pdf](https://github.com/mozilla/pdf.js/files/11113289/TagsFonts2.pdf)

Configuration:
- Web browser and its version: Chrome Version 111.0.5563.146 (Official Build) (arm64)
- Operating system and its version: macOS Ventura
- PDF.js version: 2.14.305
- Is a browser extension: no

Steps to reproduce the problem:
get a PDFPageProxy with `PDFDocumentProxy.getPage()`

`PDFPageProxy.commonObjs` is always empty, even after calling `getOperatorList()`

What is the expected behavior? 
`PDFPageProxy.commonObjs` should be populated

What went wrong?
`PDFPageProxy.commonObjs` is always empty

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, and please note that we have unit-tests that does would fail if this was generally broken; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
