### ISSUE TITLE
Dots between words

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#16257]
Attach (recommended) or Link to PDF file here: 
[Lentini.pdf](https://github.com/mozilla/pdf.js/files/11171554/Lentini.pdf)
[ss-copy-spec.pdf](https://github.com/mozilla/pdf.js/files/11171557/ss-copy-spec.pdf)

Configuration:
- Web browser and its version: firefox flatpak version 111.0.1
- Operating system and its version: openSUSE Tumbleweed
- PDF.js version: 
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the pdfs
2. See the dots and background changes

What is the expected behavior? (add screenshot)
![Screenshot from 2023-04-06 11-30-09](https://user-images.githubusercontent.com/1039418/230409388-1fde0615-7cfe-444f-87fe-cfb6956a4efa.png)
![Screenshot from 2023-04-06 11-30-55](https://user-images.githubusercontent.com/1039418/230409699-14491062-bd65-4527-a37f-95c5e9142f60.png)

What went wrong? (add screenshot)
![Screenshot from 2023-04-06 11-30-26](https://user-images.githubusercontent.com/1039418/230409482-be31f155-d4ac-4d5d-beac-a6985a516b72.png)
![Screenshot from 2023-04-06 11-30-43](https://user-images.githubusercontent.com/1039418/230409782-b5d2eb02-7bb7-4ff6-9fc4-f61515dc8578.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I tested the pdf.js from Firefox 111.0.1 (flatpak) against Evince (GNOME PDF reader)

**Comment by Snuffleupagus** [comment]
Let's dup this to https://bugzilla.mozilla.org/show_bug.cgi?id=1825293, since the problems look (more or less) identical.
