### ISSUE TITLE
Some Time PDFViewer Not Loaded

### ISSUE THREAD

**Issue by badjiyoon** [mozilla/pdf.js#16253]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: safari 16.2
- Operating system and its version: ios webview
- PDF.js version: 3.4.120
- Is a browser extension: no

Steps to reproduce the problem:
1. pdf document not loaded
   i am using the code
   document.getElementById("pdfFrame").contentWindow.PDFViewerApplication.open(
      pdfData(base64 string),
      password: (password string)
   )
   
   problem : sometime PDFViewer Document not loaded error

   error text :  2594: firstPagePromise not initailize

What is the expected behavior? (add screenshot)
PDF Viewer normal output

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.4.120

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
