### ISSUE TITLE
latest version seems to not be compatible with node 14 anymore

### ISSUE THREAD

**Issue by wollo** [mozilla/pdf.js#16252]
PDFjs does not load in latest version (3.5.141)

Configuration:
- nodejs  v14.21.3
- debian jammy

/config/workspace_docker/node_modules/pdfjs-dist/legacy/build/pdf.js:4907
    (intentState.renderTasks ||= new Set()).add(internalRenderTask);

This old nodejs version seems not recognize ||= operator

**Comment by Snuffleupagus** [comment]
This is expected result of PR #16123 unfortunately; please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for up-to-date information about supported browsers/environments.
