### ISSUE TITLE
TextLayer always logs --scale-factor console.error in chromium browsers

### ISSUE THREAD

**Issue by devalberg** [mozilla/pdf.js#16254]
Attach (recommended) or Link to PDF file here: - 

Configuration:
- Web browser and its version: Chromium Engine Version 111.0.5563.146
- Operating system and its version: Mac OS 13.2.1
- PDF.js version: [v3.5.141](https://github.com/mozilla/pdf.js/releases/tag/v3.5.141)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdf.js demo page: https://mozilla.github.io/pdf.js/web/viewer.html
2. Open browser console
3. See console error message: 
```
 text_layer.js:480 The `--scale-factor` CSS-variable must be set, to the same value as `viewport.scale`, either on the `container`-element itself or higher up in the DOM.
```

What is the expected behavior? (add screenshot)

No error message should be logged since the text layer itself renders correctly:

![image](https://user-images.githubusercontent.com/26262489/230066051-6ff3ad30-ecbe-48d6-871d-35f74f9cca21.png)

What went wrong? (add screenshot)

This code is always triggered on chromium browsers.

```tsx
    const scaleFactor = parseFloat(style.getPropertyValue("--scale-factor"));

    if (
      visibility === "visible" &&
      (!scaleFactor || Math.abs(scaleFactor - viewport.scale) > 1e-15)
    ) {
      console.error(
        "The `--scale-factor` CSS-variable must be set, " +
          "to the same value as `viewport.scale`, " +
          "either on the `container`-element itself or higher up in the DOM."
      );
    }
```
In chromium `style.getPropertyValue("--scale-factor")` always only returns 6 decimal places, therefore `Math.abs(scaleFactor - viewport.scale) > 1e-15` is always `true`.

![image](https://user-images.githubusercontent.com/26262489/230066542-d1ef61c3-3a21-48c5-b5b3-082bcf448076.png)

(also happens if `viewportScale` in the snippet above is string of `"0.123456789"`)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ahmad-qamar** [comment]
Does the text also blur while zooming in or out? I'm facing a similar issue

**Comment by kevinmelo** [comment]
The problem persist...

**Comment by kevinmelo** [comment]
The problem persist... the tweak is not in master branch
