### ISSUE TITLE
[TextLayer] Each line of text in the TextLayer does not overlap with the text positions in the canvas.

### ISSUE THREAD

**Issue by snimstice** [mozilla/pdf.js#16251]
Attach (recommended) or Link to PDF file here: http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

Configuration:
- Web browser and its version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
- Operating system and its version: macOS 12.5 (21G72)
- PDF.js version: 3.4.120 (from npm: pdfjs-dist)
- Is a browser extension: No

Steps to reproduce the problem:
1. import pdfjs-dist and TextLayerBuilder
2. use them normally
I'm not sure what's causing this issue. Is it because of the version or because I'm not using it correctly? I haven't found any effective documentation on how to use it. Here is my code.
![import1](https://user-images.githubusercontent.com/23273812/229713104-2adbb884-923f-44bf-a18e-d773f0e4631f.jpg)
![usage](https://user-images.githubusercontent.com/23273812/229713167-75e4beb7-0138-4e60-972a-866d6d22f2cd.jpg)

What is the expected behavior? (add screenshot)
![truth](https://user-images.githubusercontent.com/23273812/229710901-c6ad09fc-b0cc-4ba1-99c4-e8d9f50b50e4.jpg)
![true2](https://user-images.githubusercontent.com/23273812/229713646-abbd76c9-ab90-4c7f-bf72-aa4e77a084e9.jpg)

What went wrong? (add screenshot)
![false](https://user-images.githubusercontent.com/23273812/229710943-ec44b808-fe0d-4ad3-bf6d-d3b23ef1e547.jpg)
![false2](https://user-images.githubusercontent.com/23273812/229713549-fd858b3b-7177-4342-a749-8d4b7bb0ab06.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
One possible explanation is that you've not loaded the necessary CSS-file, see https://github.com/mozilla/pdfjs-dist/blob/master/web/pdf_viewer.css, or possibly that you've not initialized the `--scale-factor` CSS-variable (see issue #16139).

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
