### ISSUE TITLE
PDF page not rendering at all

### ISSUE THREAD

**Issue by gybadhan** [mozilla/pdf.js#16272]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 
- Operating system and its version: Windows
- PDF.js version: v2.3.200, v2.5.207
- Is a browser extension:  No

Steps to reproduce the problem:
1. Open original PDF in Acrobat Reader
2. Open same PDF in pdfjs sample demo

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/15355958/231144264-f45f38c6-858d-4dc3-a6de-59b8a34720e2.png)
The content on the page is rendering properly.

What went wrong? 

The content on the page is not rendering properly. Same is happening in pdfjs web viewer.
![image](https://user-images.githubusercontent.com/15355958/231145549-a5d95440-cf5d-45d2-b771-268907c30f43.png)

Please refer attached pdf for reference (Page 6)
[March_2023_Navigator_US.pdf](https://github.com/mozilla/pdf.js/files/11199802/March_2023_Navigator_US.pdf)

**Comment by Snuffleupagus** [comment]
WFM, when using the *built-in* Firefox PDF Viewer in Firefox Nightly 114 on Windows 11; which corresponds to PDF.js library version 3.6.9 [184076fe7].

> PDF.js version: v2.3.200, v2.5.207

Those versions are *many years* out-of-date, please make sure that you test with the *latest* version before filing bug reports; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by calixteman** [comment]
I don't have any issues with Firefox (from nightly to ESR) on Windows 11.
But I can confirm the issue with Chrome Dev (114) with https://mozilla.github.io/pdf.js/web/viewer.html.
