### ISSUE TITLE
The pdf file exported by AutoCAD cannot be edited

### ISSUE THREAD

**Issue by 123woscc** [mozilla/pdf.js#16278]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge 111.0.1661.62 
- Operating system and its version: windows 10
- PDF.js version: v3.5.141

Steps to reproduce the problem:
1. open pdf file on Online demo，this pdf file converted by AutoCAD and horizontal by default setting.
[transformed.pdf](https://github.com/mozilla/pdf.js/files/11209121/transformed.pdf)
2. click draw button and start draw
![image](https://user-images.githubusercontent.com/13806929/231405733-c04abcf1-295e-4b06-baee-a6476b9411a0.png)

What is the expected behavior? (add screenshot)
can draw line on the file 
![image](https://user-images.githubusercontent.com/13806929/231406151-64a230e5-42d6-418b-85c5-2c300f95e6d7.png)

What went wrong? (add screenshot)
Wrong drawing area position
![image](https://user-images.githubusercontent.com/13806929/231405953-bdafccf4-44a0-42ae-89cf-e8906006fd05.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
I wonder if this issue is possibly related to [bug 1802895](https://bugzilla.mozilla.org/show_bug.cgi?id=1802895)?

**Comment by calixteman** [comment]
> I wonder if this issue is possibly related to [bug 1802895](https://bugzilla.mozilla.org/show_bug.cgi?id=1802895)?

I'd say it's unrelated: in the bug you mentioned the issue is because of the position of the ghost element and here the initial position of the layer just doesn't take into account the rotation or something like that.
