### ISSUE TITLE
PDF URL metadata saved incorrectly

### ISSUE THREAD

**Issue by f2pHgty8hw** [mozilla/pdf.js#16280]
### Sample PDF
Mozilla privacy agreement: https://static.mozilla.com/moco/en-US/pdf/mozilla_privacypolicy.pdf

### Configuration
- Mozilla Firefox 112.0 (64-bit)
- macOS Ventura 13.3.1 (22E261)
- pdf.js version: built-in PDF viewer

### Reproduce the problem
Open PDF link using pdf.js viewer in browser, and save to computer.

<img width="1505" alt="save_pdf" src="https://user-images.githubusercontent.com/112357858/231724580-679ab6e0-83ce-418e-84ed-0c51c6c9dcce.png">

### Expected behavior and what went wrong
PDF metadata attribute `kMDItemWhereFroms` is incorrect. For comparison, the macOS default viewer, Preview, saves the PDF metadata correctly from Firefox, so I believe the issue is specific to pdf.js.

<img width="1124" alt="metadata_comparison" src="https://user-images.githubusercontent.com/112357858/231738083-8412081a-7980-469a-8385-7dc8d90d2b48.png">

**Comment by shubham-singh-748** [comment]
Hey this looks quite interesting to me,can i work on this issue?

**Comment by calixteman** [comment]
It's a bug in Firefox.
I filed a bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1828249
