### ISSUE TITLE
Image data is null

### ISSUE THREAD

**Issue by gummz** [mozilla/pdf.js#16282]
Attach (recommended) or Link to PDF file here:
[cats.pdf](https://github.com/mozilla/pdf.js/files/11224119/cats.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 112.0.5615.49 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 22.10
- PDF.js version: pdfjs-dist@3.5.141
- Is a browser extension: No

Steps to reproduce the problem:
This is the function I'm using:

```
const extractImagesFromPdf = async (data: Uint8Array): Promise<string[]> => {
    const images: string[] = [];

    const loadingTask = pdfjs.getDocument({ data: data });
    const pdfDocument = await loadingTask.promise;

    const numPages = pdfDocument.numPages;

    for (let pageNum = 1; pageNum <= numPages; pageNum++) {
        const page = await pdfDocument.getPage(pageNum);
        const ops = await page.getOperatorList();

        for (let i = 0; i < ops.fnArray.length; i++) {
            const op = ops.fnArray[i];
            if (op === pdfjs.OPS.paintJpegXObject || op === pdfjs.OPS.paintImageXObject) {
                const imgIndex = ops.argsArray[i][0];

                // Fetch the image object using the callback
                page.objs.get(imgIndex, async (imgRef) => {
                    const bytes = imgRef.data;
                    const base64 = Buffer.from(bytes).toString('base64');
                    images.push(base64);
                });
            }
        }
    }

    return images;
};
```
inspired from [this StackOverflow answer](https://stackoverflow.com/a/39855420/1614466).

The input is an unsigned int array, converted from a ^File` object (uploaded from a simple <input type="file" />) as the following:

```
const arrayBuffer = await readAsArrayBuffer(file);
const data = new Uint8Array(arrayBuffer);
```

What is the expected behavior? (add screenshot)
Output of function should be `images = (base64_str_1, base64_str_2)` where `base64_str_1` and `base64_str_2` are base64 strings of the two images in the pdf file.

What went wrong? (add screenshot)
`imgRef.data` is `null`, so image data cannot be extracted. Other fields are intact, like width, height, bitmap, etc.
![image](https://user-images.githubusercontent.com/8192601/231823024-89886cce-00af-4355-9857-a8822d3403fd.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
You probably need to disable `OffscreenCanvas`-usage in the worker-thread, when calling `getDocument`; please see https://github.com/mozilla/pdf.js/blob/b3932f70edc6dc1f2aab1265079a7f002bb7bc44/src/display/api.js#L205-L208

**Comment by buttercoding** [comment]
This was helpful.  Thanks @Snuffleupagus 

My code had two problems.  First was the need to set `isOffscreenCanvasSupported` to `false`.  Second was the difference between these two...

WORKS:
```typescript
page.objs.get(imgIndex, async (imgRef: any) => {
   const bytes = imgRef.data;
   const base64 = Buffer.from(bytes).toString("base64");
   images.push(base64);
});
```

DOESN'T WORK:
```typescript
const imgRef = await page.objs.get(imgIndex).promise;
const bytes = imgRef.data;
const base64 = Buffer.from(bytes).toString("base64");
images.push(base64);
```

I'm not sure why the second does not work.  I would have thought these two to be equivalent, but apparently not.  I'm not used to using `await` *and* `promise` together.

**Comment by buttercoding** [comment]
Scratch that.  The one above that 'WORKS' does return values that look like they should be an image (`3t7ehoaGf39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f39/f3`...).  But they are not base64 images (as far as I can tell pasting one into an [image converter](https://codebeautify.org/base64-to-image-converter)).  Ultimately, I want to ocr the image using Tesseractjs which accepts a buffer.  But passing `Buffer.from(bytes)` to it also did not work.

ps. happy to open a new case if those reading this would prefer that for tracking.

**Comment by luckymore** [comment]
@buttercoding Where did you see this usage?
```js
page.objs.get(imgIndex).promise
```
