### ISSUE TITLE
TypeScript integration issue due to wrong declarations

### ISSUE THREAD

**Issue by johzie** [mozilla/pdf.js#16307]
Link to TypeScript file here:
https://github.com/mozilla/pdfjs-dist/blob/5f07d5a4159bb99eee2f6143d1297f03b45bba58/types/web/pdf_find_controller.d.ts#L56

Configuration:
- PDF.js version: 3.5.141
- TypeScript version: 5.0.4

The following generated TypeScript declaration prevents calling of PDF.js API.
https://github.com/mozilla/pdfjs-dist/blob/5f07d5a4159bb99eee2f6143d1297f03b45bba58/types/web/pdf_find_controller.d.ts#L56
```
element?: null | undefined;
```
Here the property element is restricted to the types null or undefined.

The **pdf_find_controller.d.ts** declaration file is generated by 
https://github.com/mozilla/pdf.js/blob/3e08eee511b04e127fcd41d2a1d07dd3b5a68a92/gulpfile.js#L1514

A possible fix would be to declare the type like:
```typescript
element?: any;
```
This would be the case when calling TSC without *--strict* option:
https://github.com/mozilla/pdf.js/blob/3e08eee511b04e127fcd41d2a1d07dd3b5a68a92/gulpfile.js#L1507
```javascript
// Remove --strict option and generate type declarations with
gulp types
````

Example snippet which uses the PDF.js TypeScript API:
```typescript
import { EventBus, PDFLinkService, PDFFindController } from "pdfjs-dist/web/pdf_viewer";

const pdfFindController = new PDFFindController({
	eventBus: new EventBus(),
	linkService: new PDFLinkService(),
	updateMatchesCountOnProgress: true
});

// TSC compiles TypeScript code successful
pdfFindController.scrollMatchIntoView({ element: null });
pdfFindController.scrollMatchIntoView({ element: undefined });

// TSC compilation error due to wrong declaration in pdf_find_controller.d.ts
pdfFindController.scrollMatchIntoView({ element: "non null" });
pdfFindController.scrollMatchIntoView({ element: document.getElementById("testId") });
```

API can't be called with a real object and leads to following compilation issues:
```
ERROR in snippet.ts(14,41)
      TS2322: Type 'string' is not assignable to type 'null'.

ERROR in snippet.ts(25,41)
      TS2322: Type 'HTMLElement' is not assignable to type 'null'.
```

Steps to reproduce the problem:
1. Compile above TypeScript snippet with TSC.
2. See compilation issues

What is the expected behavior? (add screenshot)
Calling of PDF.js TypeScript API is possible.

What went wrong? (add screenshot)
Compilaton of TypeScript code with TSC.

**Comment by johzie** [comment]
Thanks for the quick reply and your proposed solution. Would be great if you can expose the API with the appropriate JSDoc.

https://github.com/mozilla/pdf.js/blob/f1b005d7b805e38e731d929b47d78b125765aabe/web/pdf_find_controller.js#L520

**Comment by Snuffleupagus** [comment]
> Would be great if you can expose the API with the appropriate JSDoc.

https://github.com/mozilla/pdf.js/issues/16307#issuecomment-1511694758 should be seen as an invitation for you to help out with fixing this ;-)

---

Please note that the *primary* reason for this library existing is to develop the built-in Firefox PDF Viewer, and the generated type-definitions were added since lots of TypeScript-users repeatedly asked for it.
However, it's unfortunately turned out to be very difficult to get TypeScrupt-users (as a group) to actively help with maintaining this and it usually ends up with contributors (such as myself) having to try and fix the type-definitions without really knowing anything about TypeScript.
