### ISSUE TITLE
Gradient fill not render correctly 

### ISSUE THREAD

**Issue by wb8nbs** [mozilla/pdf.js#16309]
Attach (recommended) or Link to PDF file here:
This bug was reported to Firefox, they recommended to repost here 
https://github.com/webcompat/web-bugs/issues/120617

Configuration:
- Web browser and its version:                  Firefox 112.0
- Operating system and its version:           Ubuntu 20.04
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. https://www.dupagewoodworkers.org/newsletters/news2023/DPWWnews0423.pdf
2. Note several places where fill should be even on both sides is now heavy on right

What is the expected behavior? (add screenshot)
From Chromium:
![chromium](https://user-images.githubusercontent.com/1625588/232544643-5653cab5-bd16-4d82-8211-b85443d6e2a2.png)
From Evince:
![evince](https://user-images.githubusercontent.com/1625588/232546265-7187bc99-fb7a-4eb3-9abc-23890a50a3f7.png)

What went wrong? (add screenshot)
From Firefox
![firefoxrender](https://user-images.githubusercontent.com/1625588/232544899-8f821ed3-90b4-48eb-8579-c48ca949d0b4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.6.35 [342dc760d] in Firefox Nightly 114.0a1 on Windows 11.

![windows](https://user-images.githubusercontent.com/2692120/232547366-50049fd0-4b88-4a9e-9db3-9531f8d65ac5.png)

**Comment by shtstorm** [comment]
I can reproduce the off-center rendered gradient in today's Fenix nightly. ;(
Android 9
Fenix 114.0a1 (Build #2015945635)

**Comment by ryanleesipes** [comment]
I have seen this on all platforms (Windows and MacOS). Happy to share the reference PDF where I can observe this with someone who will work on this, but I can't post it publicly because it is sensitive.

**Comment by marco-c** [comment]
If you can reproduce in Nightly, you can try using [mozregression](https://mozilla.github.io/mozregression/) to find out what caused it exactly.

**Comment by calixteman** [comment]
I can reproduce the bug on my Mac (Pro M1) with `gfx.canvas.accelerated` set to true in Firefox. 
I filed a bug for Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1831414
