### ISSUE TITLE
Accessing Azure Front Door Reference header from response not possible when exception occurs

### ISSUE THREAD

**Issue by pavdev64** [mozilla/pdf.js#16341]
When Pdf.js loads pdf document from Azure cloud and an error occurs, an exception is thrown.
For example `MissingPDFException` when the file is missing.

Azure Front Door returns `X-Azure-Ref` header with a unique reference string value that identifies the request.
For example:
```
X-Azure-Ref: 0zxV+XAAAAABKMMOjBv2NT4TY6SQVjC0zV1NURURHRTA2MTkANDM3YzgyY2QtMzYwYS00YTU0LTk0YzMtNWZmNzA3NjQ3Nzgz
```

It seems it's not possible to read the value and show it to the user for troubleshooting purposes because the error returned to the host app does not contain the response headers.

```js
var loadingTask = pdfjs.getDocument({url});
loadingTask.promise.then(
  (pdf) => {}, 
  (err) => {
    // err.response.headers isn't exposed here
  }
);
```

See: https://github.com/mozilla/pdf.js/blob/e09ad99973b1dcb82a06c001da96d52fc5bcab9d/src/display/fetch_stream.js#L145

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that this doesn't really matter for the *built-in* Firefox PDF Viewer (which is the primary reason for this library existing).
Secondly, please note that we have three different implementations for fetching data and it'd consequently be somewhat difficult to implement something like that *consistently* across all of them:
 - https://github.com/mozilla/pdf.js/blob/master/src/display/fetch_stream.js
 - https://github.com/mozilla/pdf.js/blob/master/src/display/network.js
 - https://github.com/conghoang/pdf.js/blob/master/src/display/node_stream.js
