### ISSUE TITLE
Find-bar error message foreground-color has insufficient contrast in dark mode

### ISSUE THREAD

**Issue by dholbert** [mozilla/pdf.js#16355]
Configuration:
- Web browser and its version: Firefox Nightly 114.0a1 (2023-04-26) (64-bit)
- Operating system and its version: Ubuntu 22.04
- PDF.js version: Unknown; whatever ships with this Firefox Nightly version.
- Is a browser extension: not explicitly; just using the version that ships with Firefox Nightly

Steps to reproduce the problem:
1. Configure your browser to prefer dark color-schemes -- in Firefox preferences, search for "dark" and then choose "Website appearance: Dark"
2. View some PDF **in an iframe** (so that the PDF.js find-in-document UI shows up).  For example, view this data URI:
```
data:text/html,<iframe height=400 width=1200
src="https://manuals.plus/m/5c4b852e59e3baa224c5fe39cde777d5adecd5b2ac5171dfda43cf3ec3f3e979.pdf">
```
3. Click the magnifying glass icon at the top left of the PDF.js UI
4. Type in some gibberish string that won't be found, and look at the "Phrase not found" error-message text.

What is the expected behavior?
The error message should be readable.

What went wrong? (add screenshot)
The error message is hard to read; there isn't sufficient contrast, particularly given that this is small text.
Screenshot:
![image](https://user-images.githubusercontent.com/426803/234677781-90c8b35b-2987-4034-ae5d-a411618c0c5c.png)

The foreground color here is defined as `rgba(251, 0, 0, 1)` here:
https://github.com/mozilla/pdf.js/blob/598408b7af9688e4a85d47fe47227ce32f993017/web/viewer.css#L630-L631
and it's the same color regardless of color-scheme.  (It's quite readable in a light color scheme with a light background, but harder to read with a dark color scheme).

The background color is `--toolbar-bg-color` which is `rgba(56, 56, 61, 1)`

WebAIM contrast analysis for these colors:
https://webaim.org/resources/contrastchecker/?fcolor=FB0000&bcolor=38383D
which rates it as "fail" (insufficiently contrasting) in all categories, with contrast ratio of `2.83:1`.

**Comment by dholbert** [comment]
Note "Phrase not found" is fairly easy to read/recognize.  Here's a screenshot with another error message in the same UI where this is a bit harder to read due to there being more words & longer words:
![image](https://user-images.githubusercontent.com/426803/234679363-e62650a5-6724-4769-8609-08342ac84d76.png)

**Comment by dholbert** [comment]
For comparison, here are screenshots in light mode, where this shade of red is much more readable over the `rgba(249, 249, 250, 1)` background-color:
![image](https://user-images.githubusercontent.com/426803/234679857-ded132d5-cf13-40d7-83e6-4cd121223112.png)
![image](https://user-images.githubusercontent.com/426803/234680448-f79c60ad-ab6f-4fc4-8e97-853104d3e1a8.png)


(As it happens, WebAIM still rates this a "fail" for most categories, but the contrast ratio is substantially higher:
https://webaim.org/resources/contrastchecker/?fcolor=FB0000&bcolor=F9F9FA )

**Comment by Snuffleupagus** [comment]
I wonder if we should just do the same thing as the Firefox findbar, and make that message-text bold instead (and thus remove the red colour)?
