### ISSUE TITLE
Not implemented on purpose?

### ISSUE THREAD

**Issue by memand** [mozilla/pdf.js#16373]
We need this feature, is it left unimplemented on purpose?

https://github.com/mozilla/pdf.js/blob/797f8d3dca5e0770c83788b3b65387884031caa0/src/scripting_api/field.js#L343

**Comment by Snuffleupagus** [comment]
Given that the specification text contains the following sentence, I really cannot see us implementing this unfortunately (and the feature seems very much like an edge-case anyway):
> Imports the appearance of a button from another PDF file. [...]

Refer to https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_jsapiref.pdf#G4.1968883

**Comment by memand** [comment]
> 

Since it's the function that makes it possible to make a picture insertion form field, I can't really understand how I am apparently the only guy on the internet running in to this issue..
