### ISSUE TITLE
Elements misaligned in chrome

### ISSUE THREAD

**Issue by pshp** [mozilla/pdf.js#16389]
Overview: 
- Elements misaligned in chrome
- fixed when hardware acceleration is turned off

Attach (recommended) or Link to PDF file here:
[broken-in-chrome.pdf](https://github.com/mozilla/pdf.js/files/11404640/broken-in-chrome.pdf)

Configuration:
- Web browser and its version: Chrome 113.0.5672.63
- Operating system and its version: MacOS Monterey 12.5.1
- PDF.js version:  newest (mozilla.github.io/pdf.js demo)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open file with mozilla.github.io/pdf.js demo in chrome

What is the expected behavior? (add screenshot)
- Elements to be aligned (see right side of screenshot)

What went wrong? (add screenshot)
- Elements misaligned (see left side of screenshot)

<img width="1435" alt="Screenshot 2023-05-05 at 11 03 16" src="https://user-images.githubusercontent.com/16601198/236417926-780c7aac-7020-4fd7-bbb4-474951fa3cdf.png">

**Comment by Snuffleupagus** [comment]
> * Elements misaligned in chrome
> * fixed when hardware acceleration is turned off

That would unfortunately suggest a bug in the browser *itself*, please report this to the Chromium developers instead since we can't really fix that here.

**Comment by pshp** [comment]
@Snuffleupagus this bug is only present when using pdf.js and not chrome's native pdf viewer. Is this not in the scope of pdf.js?

**Comment by Snuffleupagus** [comment]
This looks like a bug related to `canvas` and hardware-acceleration, which means that *any* JavaScript-application could be affected (if it happens to use a `canvas`-element in a particular way); hence why this suggests a *browser bug* (and please note that Firefox is the *primary* development target here).

**Comment by mniebling** [comment]
I was troubleshooting this recently as well, so just to connect the dots—I am pretty sure that this is the Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1442854

This issue was specific to MacOS and hardware acceleration. It was fixed and I can no longer repro in my case on Chrome `115.0.5790.114 (Official Build) (arm64)` on an M1 Mac running Ventura `13.4.1`.
