### ISSUE TITLE
Display issues in Firefox

### ISSUE THREAD

**Issue by pshp** [mozilla/pdf.js#16386]
Overview:
- Some PDF elements are incorrectly rendered in Firefox
- These display issues sometimes change on refresh, and sometimes disappear altogether
- This seems to be linked to WebGL, as it is fixed when it's disabled (about:config > webgl.disabled = true)

Attach (recommended) or Link to PDF file here: [pdf-with-issues.pdf](https://github.com/mozilla/pdf.js/files/11399489/pdf-with-issues.pdf)

Configuration:
- Web browser and its version: Firefox 112.0.2
- Operating system and its version: MacOS Monterey 12.5.1
- PDF.js version: newest (mozilla.github.io/pdf.js demo)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF with mozilla.github.io/pdf.js demo with recent version of Firefox, and also with another browser
2. Grey boxes obscuring some elements in the PDF in Firefox 
3. Disable WebGL in Firefox (about:config > WebGl.disabled = true) and refresh the PDF
4. Display issues are fixed

What is the expected behavior? (add screenshot)
- All elements correctly rendered in Firefox as with other browsers (see right side of screenshot below)

What went wrong? (add screenshot)
- Grey boxes obscuring some elements in Firefox (see left side of screenshot below)

<img width="1920" alt="Screenshot 2023-05-04 at 18 40 24" src="https://user-images.githubusercontent.com/16601198/236269682-dcbf53d5-b4ec-4103-a919-9f86ee0b5873.png">

**Comment by calixteman** [comment]
It's a bug in Firefox, I filed a bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1831391

**Comment by calixteman** [comment]
Since the bug is not pdf.js specific and will be fixed upstream, this one can be closed.
