### ISSUE TITLE
The display pdf crashes (freezes) in Safari Mobile

### ISSUE THREAD

**Issue by Homand-Cindy** [mozilla/pdf.js#16382]
In Safari on Ipad (IOS 16), I opened a pdf from my client with viewer.html?file=...
I scroll down and at one point, the viewer displays blank pages and then freezes.
This PDF is small (14 pages and 780ko).

I reproduce the problem by opening the demo page (https://mozilla.github.io/pdf.js/legacy/web/viewer.html) but with more difficulty, I need to scroll up or down for 30 seconds and at one point, the viewer displays blank pages and then freezes.

Do you have a solution please?

**Comment by Snuffleupagus** [comment]
> I reproduce the problem by opening the demo page (https://mozilla.github.io/pdf.js/legacy/web/viewer.html) but with more difficulty, I need to scroll up or down for 30 seconds and at one point, the viewer displays blank pages and then freezes.

This would unfortunately suggest a *browser* bug, since otherwise it really ought to be consistently broken everywhere; please report this to the Safari developers instead.
