### ISSUE TITLE
Issue with rendering annotation rectangle on top of the selected text of pdf document

### ISSUE THREAD

**Issue by ruppo-912116** [mozilla/pdf.js#16385]
Attach (recommended) or Link to PDF file here:

## Configuration
- Operating system and its version: Linux
- PDF.js version: 2.5.207

## Description
I am trying to render a new rectangle over the selected text. The rectangle will basically be a new annotation but the rectangle has certain offset and does not render over the selected text. The below code snippet is the logic i tried as far as my knowledge. The method named `renderToViewport` is the main logic for rendering.

```
class AnnotationFactory {

    // get current page annotation container
    getPageIndexOfSelectedText(){
        return parseInt(window.getSelection().getRangeAt(0).commonAncestorContainer.parentElement.parentElement.offsetParent.getAttribute("data-page-number")) - 1;
    }

    getCurrentTransform(pageIndex) {
        return pdfViewer.getPagesOverview()[pageIndex]
    }
    
    renderToViewport() {
        const selectionRect = window.getSelection().getRangeAt(0).getBoundingClientRect();
        const rectangle = document.createElement('section');
        // get the page index of selected text
        const pageIndex = this.getPageIndexOfSelectedText();
        const transformMatrix = pdfViewer.getPageView(pageIndex).viewport.transform;
        rectangle.classList.add('freeTextAnnotation');
        rectangle.setAttribute("data-annotation-id", "-1R")
        rectangle.style.top = `${selectionRect.top}px`;
        rectangle.style.left = `${selectionRect.left}px`;
        rectangle.style.width = `${selectionRect.width}px`;
        rectangle.style.height = `${selectionRect.height}px`;
        rectangle.style.backgroundColor = 'rgba(51, 51, 255, 0.4)';
        rectangle.style.transformOrigin = `-${selectionRect.left}px -${selectionRect.top}px`
        rectangle.style.transform = "matrix(" + transformMatrix.join(",") + ")"
        const annotationLayer = document.getElementsByClassName("annotationLayer")[pageIndex];
        annotationLayer.appendChild(rectangle)
    }
}
```
Can someone please help me with this? I am not quit sure what are the parameters i should be considering to display the rectangle over the top and what am i missing in the above code.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.5.207

That version is no longer supported, since it's almost *three years old*; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> The below code snippet is the logic i tried as far as my knowledge.

Please keep in mind that this is first and foremost a *bug tracker*, and that it's often difficult to provide assistance with custom functionally (even more so with old and outdated PDF.js versions); please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
