### ISSUE TITLE
Pixel 7 pro Chrome. Pdf rendering turns ugly

### ISSUE THREAD

**Issue by pkgitlab** [mozilla/pdf.js#16383]
Chrome 112.0.5615.136
Android 13; Pixel 7 Pro Build/TQ2A.230405.003.E1
![Screenshot_20230503-180635](https://user-images.githubusercontent.com/85375742/236088948-bc73aac0-6770-4462-8c47-510cda16b5a1.png)

the demo link on this GitHub project itself is rendering demo pdf in this manner

**Comment by Snuffleupagus** [comment]
That sort of rendering corruption unfortunately looks like a browser, or possibly graphics driver bug; please report this to the browser developer instead since it unfortunately doesn't look actionable here.

**Comment by pkgitlab** [comment]
Sharing here for the sake of completeness.  The workaround is to got to https://chrome/flags and disable 2D acceleration or going to chrome://flags/#disable-accelerated-2d-canvas

The way I fixed it in pdfjs viewer was to change

web/pdf_page_view.js

`  
 - const ctx = canvas.getContext("2d", { alpha: false });
+ const ctx = canvas.getContext("2d", { alpha: false, willReadFrequently: true });
`
