### ISSUE TITLE
Update the Node.js version on the bots

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#16403]
In PR #16293 we increased the minimum supported Node.js version to `18`, which is the current LTS version.
After that landed I noticed in the logs, see below, that the bots run older Node.js versions and that could become a problem (as we start using modern JS features).

@calixteman Can you please update the bots to Node.js version `18`?

- The Linux-bot now logs (at the start):
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.11.0' }
npm WARN EBADENGINE }
...
```

 - The Windows-bot now logs (at the start):
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.14.0' }
npm WARN EBADENGINE }
...
```

**Comment by calixteman** [comment]
I updated node on the windows bot and it should  be ok.
For the linux one, ubuntu version was too old (16.04), hence I began to upgrade it: so wait and see now.

**Comment by calixteman** [comment]
Both bots are now using node 18.16.
I just triggered some tests:
https://github.com/mozilla/pdf.js/pull/16397#issuecomment-1538263288

Likely we'll have some diffs on the linux bot: all the packages (and especially font ones) have been updated, hence I wouldn't surprised to see some differences.

**Comment by Snuffleupagus** [comment]
Seems to work; thank you!
