### ISSUE TITLE
Orion browser (WebKit) now uses PDF.js

### ISSUE THREAD

**Issue by vprelovac** [mozilla/pdf.js#16402]
Not a bug report, just wanted to report that a WebKit browser (Orion) is now using PDF.js and I want to thank you all for the hard work on the best PDF reader out there.

https://blog.kagi.com/orion-new-features

**Comment by timvandermeij** [comment]
Thank you; I have added it to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications.
