### ISSUE TITLE
PDF.js viewer does not show any fetch calls when disableStream and disableAutofetch is set to true, true for large documents

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#16411]
Attach (recommended) or Link to PDF file here:
[50kpageslinear.pdf](https://github.com/mozilla/pdf.js/files/11451322/50kpageslinear.pdf)

Configuration:
- Web browser and its version: chrome, firefox
- Operating system and its version:
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
1. Change the disableAutofetch and disableStream values to true, true
2. Open the above document as default document.
3. We will see that the viewer is switched to single page view mode. No scroll bars will be available.
4. When scrolling to any page like 10000, 20000, .. , it does not show any xhr fetch calls in the network. 

What is the expected behavior? (add screenshot)
xhr fetch call for the respective page should be seen in the network tab. 

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Given how the /Pages-tree looks, with only a single level, we need to fetch the *entire* PDF document to be able to successfully load/render it (regardless of API-options used). Hence the entire document will be loaded upfront, and there's consequently no additional data-fetching needed as the user browses through the PDF document.

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus But since these API options(disableStream and disableAutofetch ) would be more useful for large PDF documents, which can fetch the required pages as we go to that page rather than waiting and fetching the entire document - Is there any specific reason for this design?

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus Can you please clarify on the above question?I understand above 15000 PDF.js switches to single page mode. So PDF documents above 15000 pages cannot use the disableStream and disableAutofetch to true parameters? The entire document must be fetched before rendering?
