### ISSUE TITLE
Number of blank pages after reload depends on zoom level, while actullay none should be blank

### ISSUE THREAD

**Issue by xania** [mozilla/pdf.js#16423]
Attach (recommended) or Link to PDF file here:
[sample.pdf](https://github.com/mozilla/pdf.js/files/11472950/sample.pdf)

Configuration:
- Web browser and its version: **CHROME**
- Operating system and its version: **Windows**
- PDF.js version: **3.6.172**
- Is a browser extension: **NOPE**

Steps to reproduce the problem:
1. structure of the HTML container for the viewer
```jsx
    <div class="absolute h-full">
      <div class="pdfViewer"></div>
    </div>
```

2. Initialization of the viewer once we have access to the DOM
 
```typescript

   async attachTo(container: HTMLDivElement) {
      // Initialization of the viewer once we have access to the DOM
      const pdfDocument = await PDFJS.getDocument(props.path).promise;
      const eventBus = new EventBus();
      const linkService = new PDFLinkService({
        eventBus,
      });

      const pdfViewer = new PDFViewer({
        container,
        eventBus,
        linkService,
        l10n: NullL10n,
        textLayerMode: TEXT_LAYER_MODE,
      });

      linkService.setViewer(pdfViewer);
      linkService.setDocument(pdfDocument, null);
      pdfViewer.setDocument(pdfDocument);
    },
```

3. Complete code sample
https://github.com/xania/xania.nl/blob/b1af9765d358214baca8b2f24ef9615123a8690e/src/components/documents/index.tsx

What is the expected behavior? (add screenshot)
Lazy loading pages on scroll 

What went wrong? (add screenshot)
Blank pages are shown on scroll. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://www.xania.nl/documents

**Comment by xania** [comment]
If I remove the `h-full` class from the container element then all pages loaded, but not lazily

**Comment by Snuffleupagus** [comment]
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> https://www.xania.nl/documents

There is a `Warning: Setting up fake worker.` message logged in the web-console, which suggests that the `GlobalWorkerOptions.workerSrc`-option hasn't been set. While that's not relevant to *this issue*, using the PDF.js library without workers will lead to subpar performance and isn't really recommended nor supported.

> If I remove the `h-full` class from the container element then all pages load correctly, but not lazily.

Most likely the DOM structure, or CSS `position` rules, of the surrounding page is interfering with our `getVisibleElements`-function that's used to determine the visibility of pages.
Our general advice is to simply place the viewer in an `<iframe>`-element to fully "isolate" it from the rest of the page.
