### ISSUE TITLE
Disable stroke smoothing

### ISSUE THREAD

**Issue by anewuser** [mozilla/pdf.js#16436]
Hello. Is there a way to disable the smoothing effect that is applied to lines made using the Draw feature?

Firefox 113.0.1
Windows 10

**Comment by Snuffleupagus** [comment]
No, please also see https://github.com/mozilla/pdf.js/blob/46bbabbd5df2682a3498ff5a89f227eb1f7e79b3/src/display/editor/ink.js#L434-L437

**Comment by ldez** [comment]
Hello,

as it's not possible to disable the smoothing, is it possible to reduce the effect by increasing the number of points used to compute the curve?

The underlying problem is that when you try to sign a PDF document, the signature is really distorted.

**Comment by calixteman** [comment]
We changed the way to smooth few days ago:
https://github.com/mozilla/pdf.js/pull/16445
You can test in either [Firefox nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly) or at https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by ldez** [comment]
Thank you for your quick answer.

I tested the new Ink tool and it's exactly what I wanted.
Good job and thank you for this improvement.
