### ISSUE TITLE
Black blocks after pdf.js update

### ISSUE THREAD

**Issue by NikeByNike** [mozilla/pdf.js#16441]
Attach (recommended) or Link to PDF file here:
[css.pdf](https://github.com/mozilla/pdf.js/files/11511509/css.pdf)

Configuration:
- Web browser and its version: Google Chrome 108.0.5359.124
- Operating system and its version: Ubuntu 20.04.5 LTS
- PDF.js version: 3.6.172 (v 2.12.313 did not have this problem)
- Is a browser extension: no, I use incognito

Steps to reproduce the problem:
This problem not reproduces on hellowworld or viewer examples. But I cant figure it out. What can broke only parts of rendering?

What is the expected behavior? (add screenshot)
v 2.12.313
![image](https://github.com/mozilla/pdf.js/assets/40059850/20e68768-8237-424e-9edf-ab1bd0f7b32e)

What went wrong? (add screenshot)
v 3.6.172
![image](https://github.com/mozilla/pdf.js/assets/40059850/769081ce-d8bc-44b6-8172-2da840cc209b)

**Comment by Snuffleupagus** [comment]
WFM, when opening your document (using e.g. drag-and-drop) in the demo-viewer; see https://mozilla.github.io/pdf.js/web/viewer.html
That's using PDF.js version 3.7.64 [3be66f59d] on Windows 11, in both Firefox Nightly 115.0a1 *and* Chrome Beta 114.0.5735.35, hence this unfortunately looks like a bug that's specific to a particular combination of e.g. platform, gfx-drivers, and/or browser.

**Comment by NikeByNike** [comment]
But why this problem not appears on https://mozilla.github.io/pdf.js/web/viewer.html, but I use same "platform, gfx-drivers, and/or browser"?

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by calixteman** [comment]
I'm not able to reproduce your issue on Mac 13.3.1 (M1) with either Firefox or with Chrome, so as mentioned it's likely related to your setup.
But the rendering of the two fishes on the first page is wrong in pdf.js (see a screenshot from Preview):
<img width="889" alt="image" src="https://github.com/mozilla/pdf.js/assets/5641725/4a2aba40-e6e4-4877-9c13-2e0dfcd31a95">

**Comment by NikeByNike** [comment]
I cant reproduce it too, on viewer or helloworld pages. Clean pet projects works fine too, but when i use it on our site it has those kind of problems. On Safari problem is more serious. The render is not works at all.
And I cant find what kind of code can effect on render.
Witch part of librery responsible for render? Worker? Or the main chank of librery?
