### ISSUE TITLE
Pdf renders with artifacts on chrome 113 + Android 13 + Samsung

### ISSUE THREAD

**Issue by LueNC** [mozilla/pdf.js#16459]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Chrome 113.0.5672.134
- Operating system and its version: Samsung, Android 13
- PDF.js version: N/A, persists on the demo 
- Is a browser extension: No

Steps to reproduce the problem:
1.  Go to the preview (linked above) using one of the devices

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/109590814/f292def3-9757-4eb3-bd03-79466dfc75a2)
I do not have an actual image from the preview but the same issues as above appear in it. some pages are blank, a lot of things are black. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
-

We have tried on the following devices without issue:
Nokia G21 - Android 13 - Chrome 113.0.5672.134
Samsung S9 - Android 10 - Chrome 113.0.5672.134
iPhones in general

The following devices had the issue:
Samsung Galaxy S21 Ultra - Android 13 - chrome 113.0.5672.134
Samsung Galaxy S20 - Android 13 - chrome 113.0.5672.134

The issue was first shown in our system. We then discovered it on the pdf preview on github which shows that its an issue with pdf.js and chrome.

**Comment by Snuffleupagus** [comment]
*This is slightly confusing, since the PDF document from the screen-shot doesn't actually appear to be included anywhere in this issue.*

However, if you actually mean that even https://mozilla.github.io/pdf.js/web/viewer.html (with its default `tracemonkey`) is broken then that most unfortunately suggests a problem related to e.g. the platform, browser, and/or graphics-driver rather than a bug in the PDF.js library/viewer itself.

**Comment by LueNC** [comment]
@Snuffleupagus Here's an image from the preview: 
![image](https://github.com/mozilla/pdf.js/assets/109590814/42c0e8ca-8f91-4387-976c-212b82c73310)

**Comment by calixteman** [comment]
As said by @Snuffleupagus, it's very likely a chrome issue, so file a bug in the chrome bug tracker:
https://bugs.chromium.org/p/chromium/issues/list
You can try to open https://mozilla.github.io/pdf.js/web/viewer.html in [Fenix](https://play.google.com/store/search?q=firefox&c=apps) and see if the rendering is wrong or not: if it's please file a bug in Firefox bug tracker:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix&component=General
