### ISSUE TITLE
Get coordinates for each word

### ISSUE THREAD

**Issue by Ana0112** [mozilla/pdf.js#16455]
Attach (recommended) or Link to PDF file here:
[statement.pdf](https://github.com/mozilla/pdf.js/files/11110252/statement.pdf)

Configuration:
Web browser and its version: Chrome
Operating system and its version: Ubuntu
PDF.js version: 3.4.120
Is a browser extension: using in html/js

Steps to reproduce the problem:

Pls run this code in [codesandbox](https://codesandbox.io/s/kind-framework-fhtfrq?file=/public/index.html)
What is the expected behavior? (add screenshot)
This is expected behaviour. ```PDF.js``` combines words that it calculates should form a single sentence. I want to get bounding box for each word in the pdf file. In the attached code, the output `{str: "Account Balance Summary", dir: "ltr", width: 131.99873730057004, height: 10.9999, transform: Array(6)…}` shows item containing a group of words, and then the coordinates represent width, x, y coordinates of that item. I want to get exact coordinates for each of the words in that item. Is it possible in `PDF.js`. How do you get the coordinates for each word?

What went wrong? (add screenshot)
Nothing wrong. `PDF.js` is returning a group of words. Is there anyway I can make it to return each word as a separate item?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please note that *in general* there's no concept of "words" in most PDF documents, since glyphs are usually absolutely positioned, hence there's really no (easy) way to access the information you want unfortunately.
