### ISSUE TITLE
How could I get the pdf.js version of without nodejs modules after gulp compilation

### ISSUE THREAD

**Issue by xujiujiu** [mozilla/pdf.js#16456]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Chrome
- Operating system and its version:  113.0.5672.127
- PDF.js version: 2.12.313
- Is a browser extension: Yes

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
When I compile it through rollup, the following error occurs, but my compiled product is only used in the browser
![image](https://github.com/mozilla/pdf.js/assets/25719101/d92a3e00-ff12-41e2-a75e-089b5c2118bd)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.12.313

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> When I compile it through rollup, the following error occurs, but my compiled product is only used in the browser

Sorry, but we don't know anything about "rollup" here and consequently we cannot provide any help/assistance with that.

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Priestch** [comment]
@xujiujiu Does rollup successfully compile? If it does, then you can ignore such message.
I see same message when using webpack, set `resolve.fallback` to ignore, you can check whether rollup has similar config.

```javascript
module.exports = {
  //...
  resolve: {
    fallback: {
      https: false, // do not include a polyfill for https
    },
  },
};
```
You can see more from [resolvefallback](https://webpack.js.org/configuration/resolve/#resolvefallback)
