### ISSUE TITLE
 TypeError: (0 , _pdfjsLib.createPromiseCapability) is not a function

### ISSUE THREAD

**Issue by RadioMalibu** [mozilla/pdf.js#16468]
Hi, 
Since recently I am getting the following error (chrome devTools) and no pdf is shown anymore. It has been working without a problem before.

pdfjs-dist: "^2.5.207",
npm: "^6.14.5"

pdf_viewer.js:3140 Uncaught (in promise) TypeError: (0 , _pdfjsLib.createPromiseCapability) is not a function
    at PDFFindController._reset (pdf_viewer.js:3140:1)
    at new PDFFindController (pdf_viewer.js:2995:1)
    at _callee$ (sllDocViewerMob.js:56:37)
    at tryCatch (sllDocViewerMob.js:2:1)
    at Generator.<anonymous> (sllDocViewerMob.js:2:1)
    at Generator.next (sllDocViewerMob.js:2:1)
    at asyncGeneratorStep (sllDocViewerMob.js:2:1)
    at _next (sllDocViewerMob.js:2:1)

I have tried updating pdfjs-dist to a later version, but from version 2.7.570 and above I run into building issues and issues with loaders. We are close to release, so I need a quick fix for now. So my question is, what is the issue here, and how do I fix it? Alternative, what is the correct loader if I would upgrade to a later version of pdfjs?
Thanks!

**Comment by Snuffleupagus** [comment]
> pdfjs-dist: "^2.5.207"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I have tried updating pdfjs-dist to a later version, but from version 2.7.570 and above I run into building issues and issues with loaders.

Sorry, but please note that only the *latest* version is supported here. (Since this is an open-source project where support is generally handled by unpaid volunteers.)

> So my question is, what is the issue here, and how do I fix it?

Besides the "ancient" version, it's simply impossible to tell unfortunately; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
