### ISSUE TITLE
pdfjs-dist: Jest failures with optional dependency canvas for ARM macs

### ISSUE THREAD

**Issue by MattyBalaam** [mozilla/pdf.js#16463]
Configuration:
- ARM MacBook
- Ventura
- pdfjs-dist v3.6.172

Steps to reproduce the problem:
1. Install pdfs-dist, notice a build failure on `canvas` dependency (there are no prebuilt binaries), but notice the install continues
2. Run any pre-existing browser `jest` tests which use `jest-environment-jsdom`. (no need to include `pdfjs-dist` anywhere)
3. See Jest errors relating to a missing Build folder in canvas.
 
<img width="756" alt="Screenshot 2023-05-23 at 17 44 59" src="https://github.com/mozilla/pdf.js/assets/1246923/e4434925-af36-476b-9976-c90716cebac4">

This really feels like probably a `jsdom` and `canvas` issue, but in the absence of the `canvas` maintainer providing ARM binaries, is there a possible workaround anyone can suggest to stop this chain?

I have wondered if there is any way of uninstalling `canvas` programatically after install for example? Or perhaps there should be a browser-only fork of pdfjs-dist. The other option is quite drastic and would involve copying over the compiled build files.

**Comment by MattyBalaam** [comment]
@Snuffleupagus I understand you have attempted to use the optionalDependencies object, unfortunately the package is still installed into node_modules, but the build folder is empty.

I'll poke the jsdom maintainers instead, perhaps they can make a more robust check.

**Comment by MattyBalaam** [comment]
In case anyone else comes across the same issue, I have a horrible little workaround which works in my case. Note that this will mean that if you need to use a canvas in a node environment this will not help you.

We are using `yarn` so we were able to add a new entry to the resolutions object `"canvas": "./__BLOCKED_MODULE"` where `__BLOCKED_MODULE` is a local folder just with a basic `package.json` file. This means that `node-canvas` does not get pulled and therefore `jsdom` does not fail when trying to import/require expected files.

**Comment by blackbing** [comment]
@MattyBalaam's solution is horrible but work.

**Comment by MattyBalaam** [comment]
> @MattyBalaam's solution is horrible but work.

Yep, it certainly is!

**Comment by msileo** [comment]
Came across this as well after installing pdfjs-dist
The solution works but for now just keeping it stashed for when running jest unit tests instead of committing as it is kind of gross :/
