### ISSUE TITLE
getDocument gets invalid text

### ISSUE THREAD

**Issue by wangzhiming1999** [mozilla/pdf.js#16477]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome
- Operating system and its version:
- PDF.js version:3.6.172
- Is a browser extension:

Steps to reproduce the problem:
1. getDocument and getTextContent get content differently than display
2.
![image](https://github.com/mozilla/pdf.js/assets/48944224/f12a093c-73ae-419a-b789-98c64642a1ef)
![image](https://github.com/mozilla/pdf.js/assets/48944224/fa7b4d29-7e38-434d-b09c-7c8c763fa8c4)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> getDocument and getTextContent get content differently than display

Usually that because the PDF document doesn't contain proper /ToUnicode data, but given the lack of details we cannot provide further assistance unfortunately.

**Comment by wangzhiming1999** [comment]
file=https://core.ac.uk/download/pdf/41446564.pdf

**Comment by Snuffleupagus** [comment]
> file=https://core.ac.uk/download/pdf/41446564.pdf

WFM, with the caveat that I don't speak Chinese, when using PDF.js 3.7.67 [38287d943] in Firefox Nightly 115.0a1 on Windows. This is how the textLayer renders in the viewer:

![textlayer](https://github.com/mozilla/pdf.js/assets/2692120/0aa958e0-4f0b-4f7a-bd5d-ecdea84bac8f)

---

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
