### ISSUE TITLE
how to use the highlight functionality of pdf.worker.js

### ISSUE THREAD

**Issue by Gomathispaosta** [mozilla/pdf.js#16486]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Nothing more than a *slightly cryptic* title isn't enough to make an issue actionable/valid unfortunately.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily understandable.
