### ISSUE TITLE
can't not resolve 'canvas' in ......./pdf.js

### ISSUE THREAD

**Issue by Jmelon66** [mozilla/pdf.js#16496]
Attach (recommended) or Link to PDF file here:

Configuration:
- PDF.js version:3.7
- vue version:2.6

Steps to reproduce the problem:
1. download pdf.min.js
2.'import pdfjs from 'pdf.min.js'' in a specific file of vue project
3.throw a error 'dependency not found ' in vscode terminal ,and browser throw module not found
ps: in other project doesn.t require this dependency

What is the expected behavior? (add screenshot)
normally import

**Comment by Snuffleupagus** [comment]
> PDF.js version:3.7

Note that that's not a *complete* version number, did you actually mean `3.7.107`!?

> vue version:2.6

Sorry, but we unfortunately cannot provide help/support for the myriad of JS frameworks that exists.

Generally, please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
