### ISSUE TITLE
Strange font rendering: no space between characters.

### ISSUE THREAD

**Issue by j-morano** [mozilla/pdf.js#16509]
Attach (recommended) or Link to PDF file here: <https://mozilla.github.io/pdf.js/web/viewer.html>

Configuration:
- Web browser and its version: Mozilla Firefox 113.0.1
- Operating system and its version: Fedora Linux 38 (Sway) x86_64
- PDF.js version: PDF.js: 3.8.10 [32964db6e]
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to <https://mozilla.github.io/pdf.js/web/viewer.html>

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/48717183/d8c41df2-542f-4a28-b09b-677281467f9a)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/48717183/b506fb01-dc43-41c1-932f-3718bf358093)

The font is correctly rendered when I download the PDF and open it in Firefox (see 1st screenshot), but it is poorly rendered when the PDF is accessed using the provided link.

In browser's console, I only get the following:
```
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 3.8.10 [32964db6e])
```

**Comment by timvandermeij** [comment]
This works fine for me on Arch Linux. It sounds like an issue where the browser is not allowed to access the font data and therefore falls back to a default font. It might be an extension that is blocking things here while allowing it for local files? You can try starting Firefox in safe mode (disabling any extensions) to check. In any case, this is a browser-specific issue and nothing we can fix on the PDF.js side unless more information is presented to indicate otherwise.

**Comment by calixteman** [comment]
Could you share the output of `about:support` (you can use the button `Copy text to clipboard` and paste in just keeping the section `Important Modified Preferences`) ?

**Comment by j-morano** [comment]
```
Important Modified Preferences
------------------------------
accessibility.typeaheadfind.flashBar: 0
browser.contentblocking.category: standard
browser.download.useDownloadDir: false
browser.search.region: AT
browser.sessionstore.upgradeBackup.latestBuildID: 20230524092640
browser.startup.homepage: about:home
browser.startup.homepage_override.buildID: 20230524092640
browser.startup.homepage_override.mstone: 113.0.1
browser.tabs.firefox-view.ui-state.tab-pickup.open: true
browser.tabs.inTitlebar: 1
browser.tabs.warnOnClose: true
browser.urlbar.placeholderName: Google
browser.urlbar.placeholderName.private: Google
browser.urlbar.quicksuggest.migrationVersion: 2
browser.urlbar.quicksuggest.scenario: history
browser.urlbar.tipShownCount.searchTip_onboard: 4
browser.urlbar.tipShownCount.searchTip_redirect: 4
browser.zoom.full: false
doh-rollout.doneFirstRun: true
doh-rollout.home-region: AT
extensions.lastAppVersion: 113.0.1
idle.lastDailyNotification: 1685728952
media.eme.enabled: true
media.gmp-manager.buildID: 20230524092640
media.gmp-manager.lastCheck: 1685874195
media.gmp-manager.lastEmptyCheck: 1685874195
media.gmp-widevinecdm.abi: x86_64-gcc3
media.gmp-widevinecdm.hashValue: 55a7e4b379d5826f01b1a36abd872f411b0ba3cd2edec0c799e82def02f171df1e33365f58d91d2527f1dcaf3644b0ba9f5c4a31e712bee42bc786a5
media.gmp-widevinecdm.lastDownload: 1684021144
media.gmp-widevinecdm.lastInstallStart: 1684021143
media.gmp-widevinecdm.lastUpdate: 1684021144
media.gmp-widevinecdm.version: 4.10.2557.0
media.gmp.storage.version.observed: 1
media.videocontrols.picture-in-picture.video-toggle.first-seen-secs: 1684081539
media.videocontrols.picture-in-picture.video-toggle.has-used: true
network.dns.disablePrefetch: true
network.http.speculative-parallel-limit: 0
network.predictor.enabled: false
network.prefetch-next: false
places.database.lastMaintenance: 1685476055
privacy.purge_trackers.date_in_cookie_database: 0
privacy.purge_trackers.last_purge: 1685728952998
privacy.sanitize.pending: [{"id":"newtab-container","itemsToClear":[],"options":{}}]
security.sandbox.content.tempDirSuffix: 164a4258-7500-4022-93c1-8ecc85a42491
services.sync.declinedEngines:
services.sync.engine.creditcards: true
services.sync.engine.prefs.modified: false
services.sync.lastPing: 1685824685
services.sync.lastSync: Sun Jun 04 2023 12:25:52 GMT+0200 (Central European Summer Time)
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1684002398
```

**Comment by j-morano** [comment]
Thanks for the quick response.

> It might be an extension that is blocking things here while allowing it for local files? You can try starting Firefox in safe mode (disabling any extensions) to check.

I tried running `firefox --safe-mode`, and the issue persists.
