### ISSUE TITLE
Documentation for pdf viewer with functions?

### ISSUE THREAD

**Issue by 28development** [mozilla/pdf.js#16506]
Not an issue, but is there an actual source code of building something like that using pdf.js:

https://mozilla.github.io/pdf.js/web/viewer.html

In my case I am using react with Typescript and have done this so far:

```
import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";*/
import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry";
import { getDocument, GlobalWorkerOptions } from "pdfjs-dist/legacy/build/pdf";
import React, { useCallback, useEffect, useRef, useState } from "react";

interface PdfViewerProps {
    url: string;
}

GlobalWorkerOptions.workerSrc = pdfjsWorker;

const PdfViewer = ({ url }: PdfViewerProps) => {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    GlobalWorkerOptions.workerSrc = pdfjsWorker;

    const [pdfRef, setPdfRef] = useState<any>();
    const [currentPage, setCurrentPage] = useState(1);

    const renderPage = useCallback(
        (pageNum, pdf = pdfRef) => {
            pdf &&
                pdf.getPage(pageNum).then((page: any) => {
                    const viewport = page.getViewport({ scale: 1.5 });

                    if (!canvasRef.current) return console.error("canvasRef is not set");

                    const canvas: HTMLCanvasElement = canvasRef.current;

                    canvas.height = viewport.height;
                    canvas.width = viewport.width;

                    const renderContext = {
                        canvasContext: canvas.getContext("2d"),
                        viewport: viewport
                    };
                    page.render(renderContext);
                });
        },
        [pdfRef]
    );

    useEffect(() => {
        renderPage(currentPage, pdfRef);
    }, [pdfRef, currentPage, renderPage]);

    useEffect(() => {
        const loadingTask = getDocument(url);
        loadingTask.promise.then(
            (loadedPdf: any) => {
                setPdfRef(loadedPdf);
            },
            function (reason: any) {
                console.error(reason);
            }
        );
    }, [url]);

    const nextPage = () =>
        pdfRef && currentPage < pdfRef.numPages && setCurrentPage(currentPage + 1);

    const prevPage = () => currentPage > 1 && setCurrentPage(currentPage - 1);

    return <canvas ref={canvasRef} />;
};

export { PdfViewer };
```

I am using React with TypeScript. Not sure how I would need to implement a sidebar or search function and the rest of the functions this page contains:

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
Please refer to https://github.com/mozilla/pdf.js/tree/master/examples/components to see how a (basic) viewer can be created, using the same components that powers the "full" viewer.

> https://mozilla.github.io/pdf.js/web/viewer.html

There's not really any documentation for that one unfortunately, since it's never been intended for direct third-party usage; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
