### ISSUE TITLE
Documentation - Invalid links on GitHub wiki

### ISSUE THREAD

**Issue by pomali** [mozilla/pdf.js#16532]
On https://github.com/mozilla/pdf.js/wiki/ are links that compose into `.../wiki/wiki/...` for example https://github.com/mozilla/pdf.js/wiki/wiki/Frequently-Asked-Questions , but that link is invalid so you can't access the wiki content. Correct link is https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions .

**Comment by techmannih** [comment]
I'll handle it

**Comment by timvandermeij** [comment]
I have fixed the links now; thank you for reporting this!
