### ISSUE TITLE
Error: ReferenceError: pdfjsLib is not defined

### ISSUE THREAD

**Issue by DevanshiParmar** [mozilla/pdf.js#16536]
I'm saving all files of src directory including pdf.js and pdf.worker.js in the same directory as my html and passing the script file paths in my html too. 

But I'm getting -
Error: ReferenceError: pdfjsLib is not defined

This is my function in script.js :

```
function extractPDFText(pdfData) {
    return new Promise((resolve, reject) => {
        // Use a PDF parsing library to extract the text content
        // Here's an example using PDF.js
        pdfjsLib.getDocument(pdfData).promise
            .then(pdf => {
                const numPages = pdf.numPages;
                const pagePromises = [];
                for (let pageNum = 1; pageNum <= numPages; pageNum++) {
                    pagePromises.push(pdf.getPage(pageNum));
                }
                Promise.all(pagePromises)
                    .then(pages => {
                        const extractedText = [];
                        for (let i = 0; i < pages.length; i++) {
                            const page = pages[i];
                            page.getTextContent()
                                .then(textContent => {
                                    const pageText = textContent.items.map(item => item.str).join(' ');
                                    extractedText.push(pageText);
                                    if (extractedText.length === numPages) {
                                        const fullText = extractedText.join('\n');
                                        resolve(fullText);
                                    }
                                });
                        }
                    })
                    .catch(error => {
                        reject(error);
                    });
            })
            .catch(error => {
                reject(error);
            });
    });
} 
```

What is the issue and how to modify?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
