### ISSUE TITLE
How to implement PDFFindBar

### ISSUE THREAD

**Issue by cgiontrading** [mozilla/pdf.js#16530]
Hello there,

I am working on a web-application and in my project I have implemented a very simple PDF viewer using the `pdfjs-dist` library. The viewer currently just need to have zoom and search functionality, more to be added later.

I was able to implement the zoom functionality but for search I need to look around.
As per the documentation and in reference to this PR https://github.com/mozilla/pdf.js/pull/16350, it was advised that we should not use files from `pdfjs-dist/lib` folder. And same was removed from latest build.

Can you please point me to the documentation or sample which I can refer and implement the find bar.
It will be great if the inbuilt `PDFFindBar` class is exposed to web, that way developers need not have to worry about the internal working of find bar and find bar controller.

Thanks.

**Comment by Snuffleupagus** [comment]
> It will be great if the inbuilt `PDFFindBar` class is exposed to web,

That class is created *specifically* for the default viewer, i.e. https://github.com/mozilla/pdf.js#online-demo, and thus won't really be directly usable elsewhere; hence why it's not included in `pdfjs-dist`.
Hence you'll need to create your own custom find-bar, using e.g. the `PDFFindBar` class as inspiration.

However, the [actual find-implementation](https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js) is available through [`pdfjs-dist`](https://github.com/mozilla/pdfjs-dist/blob/master/web/pdf_viewer.js) and that file can be used to build a simple viewer (e.g. with searching included); please refer to the "viewer component" examples in https://github.com/mozilla/pdf.js/tree/master/examples/components

**Comment by cgiontrading** [comment]
Thanks @Snuffleupagus.
