### ISSUE TITLE
PDF with empty background is not rendering background property set on RenderParameters object

### ISSUE THREAD

**Issue by khelben5** [mozilla/pdf.js#16545]
Attach (recommended) or Link to PDF file here:

https://raw.githubusercontent.com/fjtrujy/wasm-max-ram/2759042b9834b3cd1395924f5ef76c4634a9275a/trickyPdf.pdf

Configuration:
- Web browser and its version: Google Chrome Version 114.0.5735.106 (Official Build) (arm64)
- Operating system and its version: MacOS 13.4 (22F66)
- PDF.js version: v3.7.107
- Is a browser extension: no

Steps to reproduce the problem:
1. Please, check out the [following example](https://jsfiddle.net/khelben/9x0t28ub/61/).

What is the expected behaviour? (add screenshot)

Blue should cover the hole red square.

What went wrong? (add screenshot)

<img width="263" alt="CleanShot 2023-06-12 at 12 54 17@2x" src="https://github.com/mozilla/pdf.js/assets/2377749/2063a52b-7d0a-460d-8bdd-a15c49efa399">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

https://jsfiddle.net/khelben/9x0t28ub/61/

**Comment by Snuffleupagus** [comment]
Most likely you're using a hiHPI-screen, however your code doesn't appear to take that into account; please see https://mozilla.github.io/pdf.js/examples/#rendering-the-page
