### ISSUE TITLE
PDF with huge pages (118 x 157 inches) gets part of a page rendered incorrectly (missing color or layer)

### ISSUE THREAD

**Issue by ondrej-tesar-digital** [mozilla/pdf.js#16560]
Attach (recommended) or Link to PDF file here:

[kalas.pdf](https://github.com/mozilla/pdf.js/files/11767672/kalas.pdf)

Configuration:
- Web browser and its version: Chrome, Firefox, Safari (any?)
- Operating system and its version: Windows, Mac (any?)
- PDF.js version: 3.7.107 and 2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF in Firefox or in Pdf.js demo [legacy demo](https://mozilla.github.io/pdf.js/legacy/web/viewer.html), [modern demo](https://mozilla.github.io/pdf.js/web/viewer.html)
2. The dress should be all blue, but one sleeve is white
3. Compare it either in Acrobat Reader or Chrome, both show it correctly

What is the expected behavior? (add screenshot)

![image](https://github.com/mozilla/pdf.js/assets/105774515/1700c18c-ef77-4e5e-a683-662c940bd26f)
![image](https://github.com/mozilla/pdf.js/assets/105774515/316c7270-897b-45a7-a283-f29e8d4406a9)
![image](https://github.com/mozilla/pdf.js/assets/105774515/57561393-15a4-4e7a-bf3c-44b064de3b01)

What went wrong? (add screenshot)

![image](https://github.com/mozilla/pdf.js/assets/105774515/0b5edd16-6213-4a7d-9872-6540aff5d9cd)
![image](https://github.com/mozilla/pdf.js/assets/105774515/2df2e7c5-d049-45f9-ac4d-cdb23371bc8c)
![image](https://github.com/mozilla/pdf.js/assets/105774515/6c06e6cf-e005-4528-9bed-e5e0f93ac961)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ondrej-tesar-digital** [comment]
It works on version 2.5.207

**Comment by calixteman** [comment]
It's a regression from #14175.
Here's a reduced test case.
[issue16560.pdf](https://github.com/mozilla/pdf.js/files/11815933/issue16560.pdf)

**Comment by Snuffleupagus** [comment]
Fixed by #17067.
