### ISSUE TITLE
Does pdf.js support form-filling then saving the resulting 'filled' PDF?

### ISSUE THREAD

**Issue by marke-apexit** [mozilla/pdf.js#16571]
I would like to understand if pdf.js support my use case of embedded form filling and also saving the resulting 'filled' PDF either to the file system or via an HTTP POST.

Sample code as part of the examples would be fantastic!

**Comment by Snuffleupagus** [comment]
Yes, once a form has been filled in (using e.g. the viewer) the "new" PDF file can be obtained with the `PDFDocumentProxy.saveDocument` method; please see https://github.com/mozilla/pdf.js/blob/fc487c8aa99f5910315ad55dcb413c3fc0cf243e/src/display/api.js#L1025-L1031

---

When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
