### ISSUE TITLE
In Android10, the pdf cannot be loaded out, but is empty

### ISSUE THREAD

**Issue by wangzhaoshuai** [mozilla/pdf.js#16575]
In Android10, the pdf cannot be loaded out, but is empty

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since nothing more than a cryptic title isn't nearly enough information to make any issue actionable/valid.
