### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '.' on PDFjs version 3.6.172

### ISSUE THREAD

**Issue by karelee7** [mozilla/pdf.js#16584]
Configuration:
- PDF.js version: 3.6.172
- Running E2E tests with Cypress

When running our E2E tests, this error message pops up for multiple tests in the console:

```
Uncaught SyntaxError: Unexpected token '.'

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

In the screenshot from Cypress tests, I also see the error message `Cannot read property 'GlobalWorkerOptions' of undefined`. The last time that I encountered this error, it was because we were missing a minified file in our setup. But I believe we have all the necessary files here:

<img width="189" alt="Screenshot 2023-06-21 at 11 20 24 AM" src="https://github.com/mozilla/pdf.js/assets/95440409/562142ce-de07-46f2-bd7d-dfd2bf093dee">

Are we missing something in our setup that's causing this error? (we manually downloaded the files from here: https://cdnjs.com/libraries/pdf.js/3.6.172)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.6.172

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Running E2E tests with Cypress

Unfortunately we have no idea what either of those are, since it's not something that we use in the PDF.js project.

Perhaps you need to use a `legacy`-build, but given the lack of details it's really impossible to tell; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by karelee7** [comment]
@Snuffleupagus I see, hm. By any chance, do you know if `window.pdfjsLib` is still valid for this version of PDFjs? We can't seem to find the pdfjsLib property on the window object anymore in our e2e tests; I think this is what's causing the errors that we're seeing
