### ISSUE TITLE
pdfjs-3.7.107-legacy-dist What is the lowest version of Firefox and Internet Explorer supported

### ISSUE THREAD

**Issue by lvruixia** [mozilla/pdf.js#16609]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:fireFox 56.0
- Operating system and its version:win10
- PDF.js version:pdfjs-3.7.107-legacy-dist

What went wrong? (add screenshot)
[
![image](https://github.com/mozilla/pdf.js/assets/44104432/b5769614-98be-442c-8f84-5878cb410fc3)
](url)

SyntaxError: illegal character[详细了解] pdf.js:816:2
SyntaxError: expected expression, got '?'[详细了解] viewer.js:837:86

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
