### ISSUE TITLE
Chinese characters font encoding is wrong 

### ISSUE THREAD

**Issue by hbghlyj** [mozilla/pdf.js#16606]
# Attach (recommended) or Link to PDF file here:
[CloudFlare link](https://cloudflare-ipfs.com/ipfs/bafykbzacednf4ordx5zro4fftiyqcvcotheedsmstrbgwaszvlbdl3cimod7e?filename=%E5%86%AF%E6%A2%A6%E9%BE%99%20-%20%E8%AD%A6%E4%B8%96%E9%80%9A%E8%A8%80.pdf)

# Configuration:
- Web browser and its version: Firefox Version 114.0.2(64-bit)
- Operating system and its version: Windows 11
- PDF.js version: 3.6.126
- Is a browser extension: No

# Steps to reproduce the problem:
1. Open [CloudFlare link](https://cloudflare-ipfs.com/ipfs/bafykbzacednf4ordx5zro4fftiyqcvcotheedsmstrbgwaszvlbdl3cimod7e?filename=%E5%86%AF%E6%A2%A6%E9%BE%99%20-%20%E8%AD%A6%E4%B8%96%E9%80%9A%E8%A8%80.pdf)
2. See garbled text

# What went wrong? (add screenshot)
*The displayed encoding is corrupted, but the bookmarks has correct encoding:*
![image](https://github.com/mozilla/pdf.js/assets/53823634/cb5d3191-f0c3-4be3-83f5-b73e62a4ac84)

# What is the expected behavior? (add screenshot)
*After saving the file, opened in local PDF reader (SumutraPDF)*
![image](https://github.com/mozilla/pdf.js/assets/53823634/06125788-55d4-44ac-95bd-7ecb11105a47)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.6.126

Please note that that's *not* an official release, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> See garbled text

Unfortunately your PDF document is *corrupt*, since it uses non-standard fonts but doesn't embed any of them.
Please note that other PDF Viewer also cannot render your document correctly, unless you've got the necessary fonts installed locally; this is how your document renders on my computer:
 - Adobe Reader
   ![adobe_reader](https://github.com/mozilla/pdf.js/assets/2692120/93d64687-f05e-49a3-ab63-d0f4a9cd51ca)
   
 - PDFium (i.e. the Google Chrome PDF Viewer)
   ![pdfium](https://github.com/mozilla/pdf.js/assets/2692120/67343c5b-56d6-4801-816c-a0d0377940b0)

**Comment by hbghlyj** [comment]
> Unfortunately your PDF document is _corrupt_, since it uses non-standard fonts but doesn't embed any of them. Please note that other PDF Viewers also cannot render your document correctly, unless you've got the necessary fonts installed locally; this is how your document renders on my computer:
> 
>     * Adobe Reader
>       ![adobe_reader](https://user-images.githubusercontent.com/2692120/248854597-93d64687-f05e-49a3-ab63-d0f4a9cd51ca.png)
> 
>     * PDFium (i.e. the Google Chrome PDF Viewer)
>       ![pdfium](https://user-images.githubusercontent.com/2692120/248854734-67343c5b-56d6-4801-816c-a0d0377940b0.png)
The encoding is **WinAnsiEncoding**. The font dictionary of this PDF doesn't contain a `ToUnicode CMap`
Excerpt from [VeryPDF doc](https://www.verypdf.com/document/pdf-format-reference/pg_0470.htm):
> 5.9.1 Mapping Character Codes to Unicode Values
> A consumer application can use the following methods, in the priority given, to
> map a character code to a Unicode value. Tagged PDF documents, in particular,
> must provide at least one of these methods (see “[Unicode Mapping in Tagged
> PDF](https://www.verypdf.com/document/pdf-format-reference/pg_0892.htm)” on page 892):
> * If the font dictionary contains a ToUnicode CMap (see Section 5.9.2,
> “[ToUnicode CMaps](https://www.verypdf.com/document/pdf-format-reference/pg_0472.htm)”), use that CMap to convert the character code to Unicode.
> * If the font is a simple font that uses one of the predefined encodings
> **MacRomanEncoding**, **MacExpertEncoding**, or **WinAnsiEncoding**, or that has an encoding whose
> **Differences** array includes only character names taken from
> the Adobe standard Latin character set and the set of named characters in the
> Symbol font (see Appendix D):
> 1. Map the character code to a character name according to Table D.1 on
> [page 996](https://www.verypdf.com/document/pdf-format-reference/pg_0996.htm) and the font’s **Differences** array.
> 2. Look up the character name in the *Adobe Glyph List* (see the Bibliography) to obtain the corresponding Unicode value.

I run both tests of `SumutraPDF` and `PDF.js` on the same computer, and `SumutraPDF`

**Comment by Priestch** [comment]
@hbghlyj Chrome is a native desktop app, it can safely use system fonts.

There's no way to use system fonts for PDF.js as a web PDF viewer unless use the [Local Font API](https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API).

**Comment by hbghlyj** [comment]
I see. Thanks.

**Comment by hbghlyj** [comment]
Hello, the broken font can be fixed by [](https://github.com/sumatrapdfreader/sumatrapdf/blob/9a2183db3c3db5cbf242ac9d8f8576750f581096/mupdf/docs/examples/fix-s22pdf.js#L12)
After running `mutool run fix-s22pdf.js input.pdf output.pdf` the PDF can be shown in PDF.js correctly:
![image](https://github.com/mozilla/pdf.js/assets/53823634/74308f8c-93d8-4193-9464-e2e6bd4643fa)
