### ISSUE TITLE
Clicking on chapters in the outline incorrectly aligns the page horizontally

### ISSUE THREAD

**Issue by robotman2412** [mozilla/pdf.js#16603]
Attach (recommended) or Link to PDF file here:
https://www.espressif.com/sites/default/files/documentation/esp32-c6_technical_reference_manual_en.pdf

Configuration:
- Web browser and its version: Firefox 114.0.1
- Operating system and its version: Ubuntu 22.04.2 LTS (x86_64)
- PDF.js version: Latest as of the time of posting this issue
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF with both landscape and portrait pages (e.g. [esp32-c6 TRM](https://www.espressif.com/sites/default/files/documentation/esp32-c6_technical_reference_manual_en.pdf))
2. Open the document outline
3. Click on one of the chapters in the outline
4. If your browser window is too narrow, the pages will not be centered

*Note: If you had manually adjusted the horizontal scroll before performing step 3, it would be overridden.*

What is the expected behavior? (add screenshot)
The pages should be horizontally centered (scroll X == 0):
![image](https://github.com/mozilla/pdf.js/assets/25562445/36d3aaba-05ce-46e0-ad27-61f046f698cd)
![image](https://github.com/mozilla/pdf.js/assets/25562445/7f1debac-b5f3-42cf-aaa5-aa6a0cc26562)

What went wrong? (add screenshot)
The pages are not horizontally centered (scroll X != 0):
![image](https://github.com/mozilla/pdf.js/assets/25562445/4b974983-82a7-4048-804a-167decdb45bb)
![image](https://github.com/mozilla/pdf.js/assets/25562445/6a106451-80fa-4b9c-a85f-82fa279f2aaf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Built-in from Firefox 114.0.1; also affects the viewer on `mozilla.github.io/pdf.js`.

I believe that this behaviour might be a result of the X position of the headers in the PDF file. As you can see in the screenshots, the horizontal scroll is set such that the origin of aforementioned text items is aligned to the left of the frame.

Suggested solution:
Either add an option to, or by default, do not change horizontal scroll position when clicking on chapters in the outline.

**Comment by Snuffleupagus** [comment]
> I believe that this behaviour might be a result of the X position of the headers in the PDF file.

Correct, the destinations used in the PDF document *itself* specifies this behaviour; hence this actually works as expected.
Please note that similar behaviour can also reproduced in Adobe Reader as well (i.e. the PDF reference implementation).

> Either add an option to, or by default, do not change horizontal scroll position when clicking on chapters in the outline.

Not respecting the horizontal destination-position could easily "break" destinations in some PDF documents and/or at larger zoom-levels, which would thus result in the bug-reports which is essentially the *inverse* of this one.
Given that all options have a maintenance/support overhead, and given the edge-case nature of this case, I'm unfortunately not entirely convinced that we want to add an options specifically for this.
