### ISSUE TITLE
Prevent render of annotation highlights

### ISSUE THREAD

**Issue by lsmenicucci** [mozilla/pdf.js#16618]
PDF viewers are able to add annotations together with a highlight marker. I would like to know if it is possible to prevent the rendering of such colored highlights, so I can handle them myself.

**Comment by Snuffleupagus** [comment]
You can disable all annotation-rendering by setting `annotationMode = 0` when calling `PDFPageProxy.render`, please see
 - https://github.com/mozilla/pdf.js/blob/88c7c8b5bfae61a20d7cb5fb27b3749b98a48d02/src/display/api.js#L1186-L1230
 - https://github.com/mozilla/pdf.js/blob/88c7c8b5bfae61a20d7cb5fb27b3749b98a48d02/src/display/api.js#L1408-L1426

Unfortunately it's somewhat difficult to interpret the *exact* context of your question, without more/clearer information.
Please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

**Comment by lsmenicucci** [comment]
Sorry, I've couldn't attach an image before to avoid the ambiguity. I'm not referring to the annotation itself but the highlight that viewers make while annotating text. Here's a screenshot of an annotation made with Okular:

[https://imgur.com/a/4Gv7P3I](https://imgur.com/a/4Gv7P3I) 

Any way to filter those out? Either by correlation with the annotation quads or other methods?

**Comment by lsmenicucci** [comment]
The `annotationMode = 0` worked perfectly! Just had to update the lib  to a newer version (was using 2.7) and annotations are now filtered as expected.

Thanks a lot!
