### ISSUE TITLE
Artifacts when rendering mitered paths

### ISSUE THREAD

**Issue by alexneufeld** [mozilla/pdf.js#16619]
Attach (recommended) or Link to PDF file here:
[test_miter.pdf](https://github.com/mozilla/pdf.js/files/11902400/test_miter.pdf)

Configuration:
- PDF.js version: 3.6.126 [3f89a99a5]
- Browser & version: Firefox 114.0.1
- Operating system: Manjaro Linux
- Is a browser extension: No

Steps to reproduce the problem:
1. view a pdf containing a path with many short connected segments. The path should have its ["stroke-linejoin"](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin) property set to "miter"

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/37948669/96b144fb-82db-458d-95d8-1c0c8faa00b9)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/37948669/5ce59f52-3341-4ed0-a771-ea1e903d1d73)

**Comment by Snuffleupagus** [comment]
> Configuration:
> PDF.js version: 3.6.126 [3f89a99a5]

What about the rest of the `Configuration:`-section, since you've left out details about *both* the browser and OS used?

---

WFM, using PDF.js version `3.8.107` [03059e1f8] in Firefox Nightly 116.0a1 on Windows 11.

![path](https://github.com/mozilla/pdf.js/assets/2692120/8ac3480e-7e2b-4ea9-b1d7-525a76f47a72)

**Comment by alexneufeld** [comment]
> What about the rest of the `Configuration:`-section

fixed

**Comment by Enivex** [comment]
I can confirm that this issue also occurs in the latest Firefox nightly on Android.

**Comment by calixteman** [comment]
I can reproduce the bug with Firefox on mac with the pref `gfx.canvas.accelerated` set to true.
I filed this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1841020
