### ISSUE TITLE
Existing Text Annotations change position while editing

### ISSUE THREAD

**Issue by dki030** [mozilla/pdf.js#16633]
Attach (recommended) or Link to PDF file here: [sample.pdf](https://github.com/mozilla/pdf.js/files/11933959/sample.pdf)

Configuration:
- Web browser and its version: Chrome 114 (Firefox 113 too)
- Operating system and its version: Windows
- PDF.js version: 3.8.162
- Is a browser extension: no

Steps to reproduce the problem:
1. open viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached PDF
3. Press Button to edit text annotations
4. Annotation are on a slightly different position:

Screenshot 1
![image](https://github.com/mozilla/pdf.js/assets/120009095/04a5dff5-2213-4080-acbf-f7d125ab1911)

Screenshot 2
![image](https://github.com/mozilla/pdf.js/assets/120009095/16796043-9a8c-41b9-8fa1-d733ccfa67fa)

What is the expected behavior? (add screenshot)
Same as Screenshot 1, position has to be the same when editing Text annotations.

What went wrong? (add screenshot)

It looks like Screenshot 2, the annotation is moved a little bit in the lower left corner.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
It seems that changing https://github.com/mozilla/pdf.js/blob/8b50836d76bbfd33f203887f4ea431e23f0344e4/src/display/editor/freetext.js#L488-L489 into
```javascript
 const [tx, ty] = this.getInitialTranslation(); 
 this.setAt(baseX * parentWidth, baseY * parentHeight, tx, ty); 
```
might fix the *vertical* positioning, however the horizontal position would still be off slightly.

**Comment by calixteman** [comment]
My feeling is that we need to get the coordinates of the first glyph in the annotation and then adapt the translation accordingly.
