### ISSUE TITLE
The 1.4 version of pdf uses that version of the pdfjs-dist library, the current project encountered a problem, when displaying the pdf1.4 version of the text can not be rendered.

### ISSUE THREAD

**Issue by tongsuoxun** [mozilla/pdf.js#16639]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:google114.0.5735.134
- Operating system and its version:win11
- PDF.js version:3.8.162
- Is a browser extension:

Steps to reproduce the problem:
1. The pdf1.4 version is displayed blank
2.But there are display tables

What is the expected behavior? (add screenshot)
Show the pdf1.4 version
![image](https://github.com/mozilla/pdf.js/assets/68542496/65ac51be-0525-4989-abbd-48adb1e75c35)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/68542496/9c08632f-ff01-489f-852a-b8af4554d9d0)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
no link

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This is part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

**Comment by tongsuoxun** [comment]
[test.pdf](https://github.com/mozilla/pdf.js/files/11955243/test.pdf)

**Comment by Snuffleupagus** [comment]
> test.pdf

First of all, that document looks *nothing* like the screen-shots in https://github.com/mozilla/pdf.js/issues/16639#issue-1788958751; please provide consistent information when opening an issue.

Secondly, that document works for me using PDF.js version 3.8.107 [03059e1f8] in Firefox Nightly 117.0a1 on Windows 11.

**Comment by tongsuoxun** [comment]
[bcfdsbvjh21121410074879614.pdf](https://github.com/mozilla/pdf.js/files/11955367/bcfdsbvjh21121410074879614.pdf)
again

**Comment by Snuffleupagus** [comment]
> [bcfdsbvjh21121410074879614.pdf](https://github.com/mozilla/pdf.js/files/11955367/bcfdsbvjh21121410074879614.pdf)

That also WFM, please see 
![working](https://github.com/mozilla/pdf.js/assets/2692120/7cae52db-e105-4229-9d3e-005806382ae2)

If anything your PDF document *itself* is broken since uses non-standard fonts but doesn't embed them, as evident from the console:
```
PDF 9aa1bff42642c0079d2aa530b7515e98 [1.4 iText® 5.5.12 ©2000-2017 iText Group NV (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version) (AGPL-version); modified using iText® 5.5.0 ©2000-2013 iText Group NV (AGPL-version) / -] (PDF.js: 3.8.107 [03059e1f8]) [viewer.js:1491:13](resource://pdf.js/web/viewer.js)
Warning: Unimplemented annotation type "Screen", falling back to base annotation. [pdf.worker.js:985:13](resource://pdf.js/build/pdf.worker.js)
Warning: Cannot load system font: STSong-Light, installing it could help to improve PDF rendering. [pdf.js:393:13](resource://pdf.js/build/pdf.js)
```

**Comment by tongsuoxun** [comment]
Solved, thank you
