### ISSUE TITLE
PDFjs Viewer accumulates memory usage when paging/scrolling some PDF files.

### ISSUE THREAD

**Issue by TrilokJaladi** [mozilla/pdf.js#16632]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: 
- PDF.js version: 3.8.162
- Is a browser extension:

Steps to reproduce the problem:
1. Open the pdf in pdfjs viewer. Click on pagedown arrow button continuously.
2. Check the memory usage in the task manager.

What is the expected behavior? (add screenshot) Memory should not increase drastically.

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site othe
[DI-c036090-09-00-44.364.pdf](https://github.com/mozilla/pdf.js/files/11933872/DI-c036090-09-00-44.364.pdf)
r than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please note that your PDF document contains very large images (one per page), hence this is unfortunately unavoidable.
However, please note that as pages go out of view (and are evicted from the cache) memory will be released again.
