### ISSUE TITLE
The 1.4 version of pdf uses that version of the pdfjs-dist library, the current project encountered a problem, when displaying the pdf1.4 version of the text can not be rendered.

### ISSUE THREAD

**Issue by tongsuoxun** [mozilla/pdf.js#16638]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since nothing more than a title unfortunately isn't enough to make any issue actionable/valid.
