### ISSUE TITLE
PDF is constantly flickering with load image beside page number

### ISSUE THREAD

**Issue by neelimar97477** [mozilla/pdf.js#16653]
Configuration:
- Web browser and its version: Chrome - 114.0.5735.199
- Operating system and its version: Windows Server 2016 - 64-bit version OS, x64-based processor
- PDF.js version: 1.4.20
- Is a browser extension: No

PDF file is constantly flickering while viewing using the PDF.js of version 1.4.20. 
Providing the below console log error 'Uncaught (in promise) Error: An error occurred while loading the PDF.
    at getDocumentError '
It holds an inner exception saying 'Worker was destroyed' from the function 'setupFakeWorkerGlobal'

The same PDF can be viewed with same PDF js file version on Windows 10 OS.

Here are the few more PDF details captured in the log.
'PDF a31cbd6dbbc18f313ddb74634316c7d9 [1.5 Aspose.Words for .NET 16.4.0.0 / -] (PDF.js: 1.4.20)'

Open, close and load functions and constantly called while debugging the PDF.js file on Windows Server 2016 version which are not being called on Windows 10.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.4.20

That version is no longer supported, since it *over seven years* old; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
