### ISSUE TITLE
Console exception is coming on changing the currentScale of viewer.js in the latest version

### ISSUE THREAD

**Issue by hiteshk764** [mozilla/pdf.js#16657]
Attach (recommended) or Link to PDF file here:

Steps to reproduce the problem:
1.  Inside pdf_viewer.js inside function scrollPageIntoView. Sometimes this._pages are not present i.e. length is 0 so in that case it 
     throws exception.  Previous version (3.7.107) this exception was not coming 
     const pageView = Number.isInteger(pageNumber) && this._pages[pageNumber - 1];

What is the expected behavior? Exception should not come

![image](https://github.com/mozilla/pdf.js/assets/25202384/1258db2d-b104-4811-9e42-1088833d665c)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
>  Previous version (3.7.107) this exception was not coming

Considering that the affected code [was last changed two years ago](https://github.com/mozilla/pdf.js/blame/eb2527e9d72a78cb037a4b7caab670c21bdf1ca5/web/pdf_viewer.js#L1412-L1419), that sounds strange.

--- 

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md 
Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
