### ISSUE TITLE
TextLayer is empty for watermarked files (present in v3.8.162 of PDFjs)

### ISSUE THREAD

**Issue by karelee7** [mozilla/pdf.js#16676]
Attach (recommended) or Link to PDF file here: Link not available, but screenshots are below.
* File with an overlay:
<img width="1680" alt="Screenshot 2023-07-11 at 2 41 02 PM" src="https://github.com/mozilla/pdf.js/assets/95440409/86d017e3-b942-44f6-825d-f5c9fd08830f">

* File without an overlay: 
<img width="1680" alt="Screenshot 2023-07-11 at 2 41 33 PM" src="https://github.com/mozilla/pdf.js/assets/95440409/dfe1a29d-d27f-4df9-a911-83fbc479e89e">

Configuration:
- Web browser and its version: Chrome, Version 114.0.5735.198
- Operating system and its version: OSX
- PDF.js version: 3.6.172 (has been an issue since v2.15.349 of PDFjs - was not present in 2.14.305; **is also an issue in 3.8.162**)
- Is a browser extension: No

Steps to reproduce the problem:
1. Observe how the `textLayer` has content in the file without an overlay and is missing all content in the file with an overlay.

What is the expected behavior? (add screenshot) 
The file with the overlay should still have content in the `textLayer` - as is it does in older versions of PDFjs (specifically noticed that the issue first began appearing after 2.14.305)

What went wrong? (add screenshot)
The `textLayer` in the file with an overlay is present, but empty.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

Relevant code:
Below is how we're initializing the PDF viewer for the file.
```
     /**
     * Initialize the pdf.js viewer.
     *
     * @protected
     * @return {pdfjsViewer.PDFViewer} PDF viewer type
     */
    initPdfViewer() {
        return this.initPdfViewerClass(this.pdfjsViewer.PDFViewer);
    }

    /**
     * Initialize the inner pdf.js viewer class.
     *
     * @protected
     * @param {Function} PdfViewerClass - the pdf viewer class (PDFViewer, PDFSinglePageViewer, etc.) to initailize
     * @returns {*}
     */
    initPdfViewerClass(PdfViewerClass) {
        const { file, location } = this.options;
        const { AnnotationMode: PDFAnnotationMode = {} } = this.pdfjsLib;
        const assetUrlCreator = createAssetUrlCreator(location);
        const hasDownload = checkPermission(file, PERMISSION_DOWNLOAD);
        const hasTextLayer = hasDownload && !this.getViewerOption('disableTextLayer');
        const textLayerMode = this.isMobile ? PDFJS_TEXT_LAYER_MODE.ENABLE : PDFJS_TEXT_LAYER_MODE.ENABLE_ENHANCE;

        return new PdfViewerClass({
            annotationMode: PDFAnnotationMode.ENABLE, // Show annotations, but not forms
            container: this.docEl,
            eventBus: this.pdfEventBus,
            findController: this.pdfFindController,
            imageResourcesPath: assetUrlCreator(IMAGES),
            linkService: this.pdfLinkService,
            maxCanvasPixels: this.isMobile ? MOBILE_MAX_CANVAS_SIZE : -1,
            renderInteractiveForms: false, // Enabling prevents unverified signatures from being displayed
            textLayerMode: hasTextLayer ? textLayerMode : PDFJS_TEXT_LAYER_MODE.DISABLE,
        });
    }
```

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: Link not available, but screenshots are below.

No meaningful debugging can be done with screen-shots alone, hence you *need* to provide the PDF document in order for any issue to be actionable/valid. (This isn't the first time that you open an issue, so you ought to know this by now.)

> Relevant code:
> Below is how we're initializing the PDF viewer for the file.

This code cannot be run as-is; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by karelee7** [comment]
@Snuffleupagus Ah yes, sorry about that! I found a way to get the actual files, please see the revised description above

**Comment by karelee7** [comment]
From the many debuggers that I dropped in, it seems like for the watermarked file, it never calls `_layoutText` when `await this.textLayerRenderTask.promise;` is executed in the `TextLayerBuilder` class. It looks like for the non-watermarked file, `_layoutText` is performed when `await this.textLayerRenderTask.promise;` runs. Not sure if that could be why..
