### ISSUE TITLE
 Uncaught TypeError: PDFJS.getDocument is not a function

### ISSUE THREAD

**Issue by anudhuri23** [mozilla/pdf.js#16700]
Attach (recommended) or Link to PDF file here:

**Note**

**_It's not duplicate I have already went through similar issues like https://github.com/mozilla/pdf.js/issues/11960 and tried the solutions provided but it does not work_** 

We are currently using pdfjs version pdfjs-1.6.210, which has xss issues. To esolve that I am trying to upgrade to pdfjs-3.8.162.
As per doc https://github.com/mozilla/pdf.js, I took the  pdfjs-3.8.162-dist.zip  from https://github.com/mozilla/pdf.js/releases/tag/v3.8.162 and updated pdf.js as mention in the doumentation

**This will generate pdf.js and pdf.worker.js in the build/generic/build/ directory (respectively build/generic-legacy/build/). Both scripts are needed but only pdf.js needs to be included since pdf.worker.js will be loaded by pdf.js. The PDF.js files are large and should be minified for production.** I am not building the pdf js at my local machine.

_I am getting **Uncaught TypeError: PDFJS.getDocument is not a function**. It seems pdf.worker.js is not loading._

`console.log("Url match.");
var pdfjsSrc = dojo.config.baseUrl;
PDFJS.workerSrc = pdfjsSrc.replace(/dojo\/$/i, 'pdfjs\/pdf.worker.js');`

`      open: function pdfViewOpen(file, callback) {
    this.close();

    var parameters = {};
    if (typeof file === 'string') {
      parameters.url = file;
    } else if (file && 'byteLength' in file) { // ArrayBuffer
      parameters.data = file;
    } else if (file.url && file.originalUrl) {
      parameters.url = file.url;
    }
    
    var self = this;
    self.loading = true;
    self.downloadComplete = false;

    var loadingTask = PDFJS.getDocument(parameters);
	loadingTask.promise.then(function(pdf) {
		console.log("******************")
    });
  },`

Our current pdf version is '1.6.210';

Configuration:
- Web browser and its version: 115.0.2 (64-bit)
- Operating system and its version: windows 10
- PDF.js version: pdfjs-3.8.162
- Is a browser extension: no

Steps to reproduce the problem:
1. update the new pdf.js 
2. try to view in viewer

What is the expected behavior? (add screenshot) Pdf should be loaded

What went wrong? (add screenshot)
Throwing and exception ** Uncaught TypeError: PDFJS.getDocument is not a function**
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> It's not duplicate I have already went through similar issues like #11960 and tried the solutions provided but it does not work

Well, if you read through all of that issue you'll see that the correct thing to use is `pdfjsLib.getDocument(...)` in modern versions of the PDF.js library.

> I am getting **Uncaught TypeError: PDFJS.getDocument is not a function**. It seems pdf.worker.js is not loading.

Note that the `PDFJS`-global was removed already in PDF.js version `2`, hence the problem isn't the worker but again the fact that you're not call `pdfjsLib.getDocument(...)`.
Also, you really should consider updating the PDF.js library a little more frequently since version `1.6.210` was released in 2016.

---

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
