### ISSUE TITLE
Annotation: Chinese font rendering failed in other browsers (Google, Edge)

### ISSUE THREAD

**Issue by Elwin0204** [mozilla/pdf.js#16712]
Version 3.8.162: Using text annotations and brush functions, saved PDF files cannot be rendered when opened in Google Chrome, especially for Chinese fonts

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately contains no actionable information.
