### ISSUE TITLE
Uncaught (in promise) Error: startCleanup: Page 1 is currently rendering. 

### ISSUE THREAD

**Issue by anudhuri23** [mozilla/pdf.js#16727]
Attach (recommended) or Link to PDF file here:

_**We are currently using pdfjs version pdfjs-1.6.210, which has xss issues. To esolve that I am trying to upgrade to pdfjs-3.8.162.
As per doc https://github.com/mozilla/pdf.js, I took the pdfjs-3.8.162-dist.zip from https://github.com/mozilla/pdf.js/releases/tag/v3.8.162 and updated pdf.js as mention in the doumentation**_

Configuration:
-Web browser and its version: 115.0.2 (64-bit)
-Operating system and its version: windows 10
-PDF.js version: pdfjs-3.8.162
-Is a browser extension: no

Steps to reproduce the problem:
-update the new pdf.js
-try to view in viewer

What is the expected behavior? (add screenshot)
PDF should be rendered

What went wrong? (add screenshot)
![pdf-viewer-issue](https://github.com/mozilla/pdf.js/assets/139737155/abf4cfe7-abcb-4b98-a5de-0462a2ffd67e)

At first time, PDF is rendering, But when I scroll down and scroll up again first few pages are not rendering and throwing

**VM7991:2477 Uncaught (in promise) Error: startCleanup: Page 1 is currently rendering.
    at WorkerTransport.startCleanup (eval at <anonymous> (eval at <anonymous> (dojo.js:1:1)), <anonymous>:2477:15)**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is completely impossible to debug using nothing but a screen-shot, which also appears to be from a *custom viewer*; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by anudhuri23** [comment]
@Snuffleupagus I checked this https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/645 issue and it seems it is fixed. But still I am getting this. Atleast tell me workaround to fix the issue before closing the ticket

**Comment by Snuffleupagus** [comment]
> I checked this [stephanrauh/ngx-extended-pdf-viewer#645](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/645) issue and it seems it is fixed.

Sorry, but that's a *different* project that we cannot provide help/support for here.

> Atleast tell me workaround to fix the issue before closing the ticket.

Given that this doesn't happen in the default viewer, see https://github.com/mozilla/pdf.js#online-demo, as already mentioned in https://github.com/mozilla/pdf.js/issues/16727#issuecomment-1646626615 it's simply *impossible* for anyone to provide assistance without being able to reproduce the issue; hence why a *runnable example* is needed here.

**Comment by anudhuri23** [comment]
That's okay but what's the work around here, The pdf isn't loading because of this.

**Comment by anudhuri23** [comment]
@Snuffleupagus the above issue is appearing only for latest version. I tried https://github.com/mozilla/pdf.js/releases/tag/v3.7.107, and there is no issue.
