### ISSUE TITLE
Allow user to jump to the first page with 0

### ISSUE THREAD

**Issue by itsdevdeepak** [mozilla/pdf.js#16734]
Not sure about other but i personally find it weird to not able to go the first page with 0, idk why it naturally occur to me to use 0 for first.

**Comment by Snuffleupagus** [comment]
Sorry, but this just feels like way too much of a special-case to warrant doing (and it could also complicate the page-label implementation unnecessarily). Please keep in mind that all code needs to be tested/maintained/supported, potentially for years.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by calixteman** [comment]
FYI, I had a quick look in Chrome, Edge and Acrobat and none of them have this feature.
The usual shortcuts in a browser for reaching start or end of the document is to use Home and End keys on your keyboard.

**Comment by itsdevdeepak** [comment]
ahh ok understandable
