### ISSUE TITLE
header is not visible

### ISSUE THREAD

**Issue by prmanik** [mozilla/pdf.js#16747]
Attach (recommended) or Link to PDF file here:
We are using prebuilt pdf.js library, For a specific document, headers are not visible.
Configuration:
- PDF.js version: 3.7.107

Steps to reproduce the problem:
1. Please open the pdf file with prebuilt code
[val-ven-rpt-0533 (1).pdf](https://github.com/mozilla/pdf.js/files/12172783/val-ven-rpt-0533.1.pdf)

2. Headers are not visible as mentioned in the screenshot

What is the expected behavior? (add screenshot)
![image-2023-06-28-18-01-01-877](https://github.com/mozilla/pdf.js/assets/140620152/a565eed8-1947-4cf3-ab9c-9ae0eefdc7f4)

What went wrong? (add screenshot)
![image-2023-06-28-18-00-47-193](https://github.com/mozilla/pdf.js/assets/140620152/49626403-e716-4dd3-b3a9-62aadc0ade29)

**Comment by Snuffleupagus** [comment]
> Configuration:

Most of the necessary details are missing from this section.

> PDF.js version: 3.7.107

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Headers are not visible as mentioned in the screenshot

WFM, using PDF.js 3.9.130 [71f113bf8] in Firefox Nightly 117.0a1 on Windows 11.

![header](https://github.com/mozilla/pdf.js/assets/2692120/d1e2ec7f-ae60-48dd-b70d-77bef1240e1f)

---

Given that your screen-shot appears to be from a *custom* viewer, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
