### ISSUE TITLE
Dialog to open file not opening

### ISSUE THREAD

**Issue by paulmenzel** [mozilla/pdf.js#16751]
Following the [Wiki page *Bisecting a Regression*](https://github.com/mozilla/pdf.js/wiki/Bisecting-a-Regression) After

    $ git clone https://github.com/mozilla/pdf.js/
    $ cd pdf.js

and then

    $ python3 -m http.server
    Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/viewer.html HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/viewer.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] code 404, message File not found
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /node_modules/es-module-shims/dist/es-module-shims.js HTTP/1.1" 404 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/pdf_viewer.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/text_layer_builder.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/annotation_layer_builder.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/xfa_layer_builder.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/annotation_editor_layer_builder.css HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-viewThumbnail.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-viewOutline.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-viewAttachments.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-viewLayers.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-sidebarToggle.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-search.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-pageUp.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-pageDown.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-openFile.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-print.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-download.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-editorFreeText.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-secondaryToolbarToggle.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-editorInk.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-zoomOut.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-zoomIn.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /web/images/toolbarButton-menuArrow.svg HTTP/1.1" 200 -
    127.0.0.1 - - [27/Jul/2023 08:29:38] code 404, message File not found
    127.0.0.1 - - [27/Jul/2023 08:29:38] "GET /favicon.ico HTTP/1.1" 404 -

and Mozilla Firefox/Nightly shows

> Laden fehlgeschlagen für das <script> mit der Quelle "http://localhost:8000/node_modules/es-module-shims/dist/es-module-shims.js". viewer.html:55:80

and the dialog to open a file does not work.

Do I need to build something first?

**Comment by Snuffleupagus** [comment]
You need to follow all steps listed in https://github.com/mozilla/pdf.js#getting-the-code in order install the necessary dependencies.

**Comment by paulmenzel** [comment]
It would be nice, if the Wiki page could be updated accordingly. Currently, it reads to me like, that no additional steps are needed.
