### ISSUE TITLE
Regression between Firefox 109.0.1 and 115.0.2 - document used to render, now does not

### ISSUE THREAD

**Issue by jl6** [mozilla/pdf.js#16759]
Link to PDF file here: [issue16759.pdf](https://github.com/mozilla/pdf.js/files/12185373/issue16759.pdf) (from [https://lab6.com/1](https://lab6.com/1))

Configuration:
- Web browser and its version: Firefox 115.0.2 (64-bit)
- Operating system and its version: Ubuntu 22.04
- PDF.js version: Version built into Firefox 115.0.2

Steps to reproduce the problem:
1. Try to load the above URL
2. Document does not render. The following error message can be found in the console:

```
Invalid or corrupted PDF file.

PDF.js v3.7.96 (build: 23958ffc5)
Message: Invalid PDF structure.
```

This document used to render in Firefox 109.0.1 (possibly later versions too, but that's the old version I have to hand). It renders in Chrome and Okular, and also passes PDF validators (https://www.pdfen.com/pdf-a-validator and VeraPDF).

N.B. This is a polyglot PDF/MP3 file that does not rely on parser bugs. I believe it to be fully conformant to the PDF spec, but it may push the boundaries of what a PDF processor expects, or I may be wrong about it being fully conformant.

**Comment by Snuffleupagus** [comment]
> I believe it to be fully conformant to the PDF spec, but it may push the boundaries of what a PDF processor expects, or I may be wrong about it being fully conformant.

Unfortunately your PDF document is *corrupt*, as indicated by the "Indexing all PDF objects"-part of the complete console-log:
```
Partitioned cookie or storage access was provided to “https://lab6.com/1” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Warning: Indexing all PDF objects pdf.worker.js:973:13
Warning: indexObjects: Found "trailer" inside of another "obj", caused by missing "endobj" -- trying to recover. pdf.worker.js:973:13
Invalid or corrupted PDF file.

PDF.js v3.9.146 (build: 48cc67f17)
Message: Invalid PDF structure. viewer.js:1280:13
Uncaught (in promise) 
Object { message: "Invalid PDF structure.", name: "InvalidPDFException", stack: "BaseExceptionClosure@resource://pdf.js/build/pdf.js:446:29\n__webpack_modules__<@resource://pdf.js/build/pdf.js:449:2\n__w_pdfjs_require__@resource://pdf.js/build/pdf.js:14213:41\n@resource://pdf.js/build/pdf.js:14481:32\n@resource://pdf.js/build/pdf.js:14492:3\n@resource://pdf.js/build/pdf.js:14495:12\nwebpackUniversalModuleDefinition@resource://pdf.js/build/pdf.js:31:50\n@resource://pdf.js/build/pdf.js:32:3\n" }
```

**Comment by calixteman** [comment]
In using [mozregression](https://mozilla.github.io/mozregression/), I found:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=837b1f1e4939ef2b5240519606c195f33f97d32a&tochange=ccaec9f3c11a1eb01e207a78df4096fea00fafb6
And it seems that #15854 could be the cause of this regression.

**Comment by calixteman** [comment]
In order to track the regression, I filed a mirror bug on bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1845762

**Comment by jl6** [comment]
Is there a way of getting PDF.js to emit the offset at which it thinks it has detected corruption?

**Comment by Snuffleupagus** [comment]
> Is there a way of getting PDF.js to emit the offset at which it thinks it has detected corruption?

Unfortunately not.

> So scanning through the stream and finding "trailer" before "endobj" does not necessarily indicate corruption.

Please note that the decision that the PDF document is *corrupt* is made a lot earlier, since a "normal" PDF document won't even enter the `XRef.indexObjects` method in the first place. The issue here seem, based on a very cursory look, to be related to the `xref`-entries found within the document.
