### ISSUE TITLE
Additional Blank page in pdf at the end for Printing

### ISSUE THREAD

**Issue by AndrewWebDev** [mozilla/pdf.js#16763]
Attached link to PDF file here:
[PDF.js.pdf](https://github.com/mozilla/pdf.js/files/12193114/PDF.js.pdf)

**Configuration:**
- Web browser: **Chrome**, Version **115.0.5790.110** (Official Build) (64-bit):
- Operating system and its version: **Windows 10** Enterprise, 22H2, **19045.3208**
- PDF.js version: pdfjs-**3.8.162**
- Is a browser extension: NO

**Steps to reproduce the problem:**
1. Open online demo by link: https://mozilla.github.io/pdf.js/web/viewer.html
2. Download the file from the attachments ([PDF.js.pdf](https://github.com/mozilla/pdf.js/files/12193114/PDF.js.pdf)) and open it using the PDF viewer
3. Click the Print icon-button

**What is the expected behavior?** (added a screenshot for printing from a native browser pdf viewer)
PDF contains only one page **so print contains only 1 page:**

![image](https://github.com/mozilla/pdf.js/assets/130077789/52ab98e6-0d06-4cd2-99f1-a65199e34047)

**What went wrong?** (added a screenshot for printing from a pdfjs-**3.8.162**)
PDF contains only one page but **on Print sends two pages where the last page is blank:**

![image](https://github.com/mozilla/pdf.js/assets/130077789/a864d1b9-f19f-4c07-81e9-b8d8f553c5a7)

**Additional notes:**
In the browser Microsoft Edge, Version 115.0.1901.188 (Official build) (64-bit)
all works fine

![image](https://github.com/mozilla/pdf.js/assets/130077789/1efc9708-ba56-47a0-94c0-1ca48c10cc68)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js PDF.js: 3.9.146 [48cc67f17] as *built-in* to Firefox Nightly 117.0a1 on Windows 11.

Also WFM, using PDF.js 3.9.169 [cfd179f23] (i.e. the demo viewer) in Google Chrome Beta 116.0.5845.49 on Windows 11.

> In the browser Microsoft Edge, Version 115.0.1901.188 (Official build) (64-bit)
> all works fine

Given that this apparently works in another Chromium-based browser, the fact that *detailed control* over printing output is still difficult to achieve in general (and with good cross-browser support), and finally that Firefox is the *primary* development target for this library; this most unfortunately doesn't really look easily actionable/fixable here.
