### ISSUE TITLE
pdf_viewer broken in 3.9.179 when using Webpack

### ISSUE THREAD

**Issue by code-elf** [mozilla/pdf.js#16778]
Attach (recommended) or Link to PDF file here: No PDF needed; the viewer does not load properly.

Configuration:
- Web browser and its version: Chrome 114.0.5735.198
- Operating system and its version: Linux (Nobara 38)
- PDF.js version: 3.9.179
- Is a browser extension: No

It seems that https://github.com/mozilla/pdf.js/commit/bad4bfffdf4bfc15c66039eb1b8731d86f154dfa broke `pdf_viewer`'s importing of `pdfjsLib` when using Webpack. That commit message states that "the *built* `pdf.js` file has always exposed the API-contents globally," however the `pdf.js` file has the following header:
```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("pdfjs-dist/build/pdf", [], factory);
	else if(typeof exports === 'object')
		exports["pdfjs-dist/build/pdf"] = factory();
	else
		root["pdfjs-dist/build/pdf"] = root.pdfjsLib = factory();
})(globalThis, ...
```
This means that when using a bundler with module support, the API will _not_ be added to the global scope, which breaks the `pdf_viewer`.

Please let me know if I'm missing anything, but I believe this is a regression in the library, as the only way I can now see to make `pdf_viewer` work is to manually add the API to `globalThis`.

**Comment by camsong** [comment]
Got the same error, please fix this, thanks.
