### ISSUE TITLE
Error: fetch Built In CMap: failed to fetch file "../web/cmap/UniKS-UTF16-H.cmap" with "Not Found"

### ISSUE THREAD

**Issue by prmanik** [mozilla/pdf.js#16783]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 115.0.5790.110 (Official Build) (64-bit)
- Operating system and its version: Windows version 10 enterprise
- PDF.js version: 3.7.107
- Is a browser extension: No

Steps to reproduce the problem:
I was able to load document header with below change

var loadingTask = pdfjsLib.getDocument({
url: parameters.url,
cMapUrl: 'https://unpkg.com/pdfjs-dist@3.7.107/cmaps/',
cMapPacked: true
});

But when I tried to use local files like below, it is showing me error as "Error: fetch Built In CMap: failed to fetch file "../web/cmap/UniKS-UTF16-H.cmap" with "Not Found".".

var loadingTask = pdfjsLib.getDocument({
url: parameters.url,
cMapUrl: '../web/cmaps/',
cMapPacked: true
});
Could you please let me know why it is not working with local files. Any configuration that we need to do in order make it right?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.7.107

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> var loadingTask = pdfjsLib.getDocument({ url: parameters.url, cMapUrl: 'https://unpkg.com/pdfjs-dist@3.7.107/cmaps/', cMapPacked: true });
> 
> But when I tried to use local files like below, it is showing me error as "Error: fetch Built In CMap: failed to fetch file "../web/cmap/UniKS-UTF16-H.cmap" with "Not Found".".

Unfortunately that error message doesn't make sense with the mentioned API options, furthermore it's simply impossible for anyone to reproduce this without a lot more information.
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by prmanik** [comment]
Can you please suggest the example to how use the local files?
