### ISSUE TITLE
Fetch Document outline aka. Table of Contents aka. Bookmarks

### ISSUE THREAD

**Issue by yoganandaness** [mozilla/pdf.js#16785]
Can this Package be used for backend Nodejs? 

I have a requirement, where i want to read the Document Outline(aka. Table of Contents aka. Bookmarks) of a PDF in the backend. 
Is this package a suitable candidate for the job?

**Comment by Snuffleupagus** [comment]
> Can this Package be used for backend Nodejs?

Yes.

> I have a requirement, where i want to read the Document Outline

Please see https://github.com/mozilla/pdf.js/blob/0725b6299f122632a7d5b97f82fe584ae1584c5d/src/display/api.js#L951-L972

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
