### ISSUE TITLE
getOutline - How to get the page number of each item

### ISSUE THREAD

**Issue by yoganandaness** [mozilla/pdf.js#16789]
Attach (recommended) or Link to PDF file here: 
[LearnJava (1).pdf](https://github.com/mozilla/pdf.js/files/12249504/LearnJava.1.pdf)

Configuration:
- Web browser and its version: Using Backend Node Js
- Operating system and its version: Mac M2
- PDF.js version: 3.9.179
- Is a browser extension: No

Steps to reproduce the problem:
1. Run the project. https://codesandbox.io/p/sandbox/heuristic-dawn-64r7nk?file=%2Findex.js%3A16%2C1

I am able to get the Outline items, but i would like to have the Page Number, it is being linked to. Please help me get the information. 

The field dest is confusing. Help me understand the dest and how to derive the page number out of it. 

![Screenshot 2023-08-03 at 12 09 22](https://github.com/mozilla/pdf.js/assets/132274772/492cf885-acdf-412e-87f6-fa1424a28f6e)

**Comment by Snuffleupagus** [comment]
Please refer to https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G11.1696125
Hence the pageIndex can be obtained by passing *the first* element in the `dest` array to https://github.com/mozilla/pdf.js/blob/2747928a5498daac37dcf7a15d7eca8f7139dd72/src/display/api.js#L860-L867

---

In case the `dest` entry is a string, note https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G11.1947713 and the explicit destination can be obtained via https://github.com/mozilla/pdf.js/blob/2747928a5498daac37dcf7a15d7eca8f7139dd72/src/display/api.js#L879-L887

**Comment by yoganandaness** [comment]
@Snuffleupagus That works like Charm. Thanks a lot for quick response.
