### ISSUE TITLE
JPX Image with transparency shows inversed colors

### ISSUE THREAD

**Issue by pubpub-zz** [mozilla/pdf.js#16782]
with the following PDF:
[tt1.pdf](https://github.com/mozilla/pdf.js/files/12244643/tt1.pdf)

we are expecting this image:(available in AcrobatReader, Chrome, Sumatra,...)
![image](https://github.com/mozilla/pdf.js/assets/4083478/26412267-e77a-4fd3-b888-28790f9d8215)

but in pdf.js (windows 11 / firefox 115.02 + PDF.js: 3.7.96 [23958ffc5] the colors are inverted:
![2023-08-02 23-00-07](https://github.com/mozilla/pdf.js/assets/4083478/1535f815-4efb-4ad3-88ce-56afc26658f7)

**Comment by NextThread** [comment]
hey can I work on this issue

**Comment by pubpub-zz** [comment]
@NextThread any update of your analysis?

**Comment by pubpub-zz** [comment]
Is anyone interested in having a look in my issue ?

**Comment by pubpub-zz** [comment]
@Snuffleupagus  
I don't think the issue is a duplicate of #17416 where the channels seems to be puzzled whereas in here the image is color reversed.
For me still active
