### ISSUE TITLE
Facing issue on integrating pdf.js with Backend NodeJs

### ISSUE THREAD

**Issue by yoganandaness** [mozilla/pdf.js#16788]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Using Backend Node.Js
- Operating system and its version: Mac
- PDF.js version: Latest
- Is a browser extension: NO

Steps to reproduce the problem:
1. Create an Express Js App
2. Install `pdfjs-dist`
3. import the `pdfjs-dist`, as done in https://github.com/mozilla/pdf.js/blob/0725b6299f122632a7d5b97f82fe584ae1584c5d/examples/node/getinfo.js
4. Run `npm run dev`

What is the expected behavior? (add screenshot)
Import the `pdfjs-dist` and start using the APIs. I want to fetch the Document Outline of the PDF and found an api `getOutline()` as given in https://github.com/mozilla/pdf.js/blob/0725b6299f122632a7d5b97f82fe584ae1584c5d/src/display/api.js#L951-L972. 

What went wrong? (add screenshot)
`npm run dev` throws error. TypeError: Cannot read properties of undefined (reading 'prototype')
![Screenshot 2023-08-03 at 11 05 06](https://github.com/mozilla/pdf.js/assets/132274772/73b04d41-15e5-4688-80f4-c42a363235a0)

Here is the code
app.js
![Screenshot 2023-08-03 at 11 07 01](https://github.com/mozilla/pdf.js/assets/132274772/3351075e-03a8-431c-a9b1-0c11e9d24af1)
package.json
![Screenshot 2023-08-03 at 11 07 21](https://github.com/mozilla/pdf.js/assets/132274772/5b86593b-f2bf-4d1a-8085-f07f600cb60c)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

Please remember to provide a version *number*, since "latest" isn't really helpful.

> Here is the code

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
