### ISSUE TITLE
A newly added stamp annotation shows a resizing image

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#16797]
Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: mac OS Ventura 13.5

Steps to reproduce the problem:
1. Open a pdf
2. Add an image

What went wrong?
The image is resizing itself without any user interaction

It's a regression from #16794.

@Snuffleupagus, could you have a look please ?

**Comment by Snuffleupagus** [comment]
I was having a difficult time reproducing this issue at first, and I needed to change the zoom-level in the viewer (after adding the stamp-annotation) in order to reproduce this.
