### ISSUE TITLE
Setting up fake worker failed: "Cannot load script at: http://localhost:82/facilitator/node_modules/pdfjs-dist/build/pdf.worker.js

### ISSUE THREAD

**Issue by sohailahmad07** [mozilla/pdf.js#16791]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: firefox developer latest 
- Operating system and its version: Linux ubuntu 22.04
- PDF.js version: 3.9.179
- Is a browser extension: no

Steps to reproduce the problem:
1. install laravel with jetstream with livewire
2. install pdf.js through npm `npm i pdfjs-dist` 
3. import pdf.js in bootstrape.js like so 
4. add the code to render pdf 

step 3 code
```
import * as pdfjsLib from "pdfjs-dist";
window.pdfjsLib = pdfjsLib;
pdfjsLib.GlobalWorkerOptions.workerSrc = "../../node_modules/pdfjs-dist/build/pdf.worker.js";
```

step 4 code
```
 <p x-data='' @click='pdfjsLib.getDocument("path to the pdf").promise.then(pdf => {
            pdf.getPage(1).then(page => {
                console.log(page);
            });

        });'>Click Me</p>
```

What is the expected behavior? (add screenshot)
i should not throw any errors 

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/58299055/6125ab53-bba1-418e-a1ce-49d477f4d832)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): no

**Comment by Snuffleupagus** [comment]
> install laravel with jetstream with livewire

Sorry, but that's unfortunately not a configuration that we can provide help/support for.

> add the code to render pdf

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> What went wrong? (add screenshot)

Please keep in mind that error messages should always be provided *as text*, since that's much easier to work with than images. Furthermore you seem to have MIME type warnings, which might suggest an issue with your server, so that's probably the first place that you should start looking for the problem.
