### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read from private field

### ISSUE THREAD

**Issue by sohailahmad07** [mozilla/pdf.js#16792]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: firefox latest
- Operating system and its version: ubuntu 22.04
- PDF.js version:^3.9.179
- Is a browser extension:no

hi i am using pdfjs to should pdf in a modal and i am using alpine js for that

pdf is multiple file and i want to display nav button on the top of the pdf so user can navigate

but i get this error :Uncaught (in promise) TypeError: Cannot read from private field

i am open to ideas

thanks in advance

here my code

pdfInstance: false,

   createPdf() {
        PDFJS.getDocument(option.url).promise.then(pdf => {
            this.pdfInstance = pdf;
            this.renderPage(1);
        });
    },
    
    renderPage(page) {

        this.pdfInstance.getPage(page).then(page => {

               console.log(page)
        })

    }

i was expecting to see the pdf but i get this error one more this if i dont assign the pdf to pdfInstance it work fine but then i want to render other page i will create the document every single time and i dont know if i such a good idea

this code works but i dont think i good cuse i will create the document every thime i render new page

 createPdf(page) {

        PDFJS.getDocument(option.url).promise.then(pdf => {
          
             pdf.getPage(page).then(page => {

               console.log(page)
             })
           
            this.renderPage(1);
        });
    },
    

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/58299055/76f34db3-b5f1-4b13-938e-4ddfaad0cf83)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by wang-zao** [comment]
Got same error. Tried legacy version and not working. using version 3.9.179

**Comment by bijinfeng** [comment]
I have encountered the same problem, which is my solution:

```js
createPdf(page) {
  this.pdfPromiseInstance = PDFJS.getDocument(option.url).promise;
}

renderPage(page) {
    this.pdfPromiseInstance.then(pdf=> {
         pdf.getPage(page).then(page => {
           console.log(page)
         })
    })
}
```
