### ISSUE TITLE
Get filled forms

### ISSUE THREAD

**Issue by jamshidwizard** [mozilla/pdf.js#16817]
Attach (recommended) or Link to PDF file here:

Configuration:
- last version chrome
- windows10:
- last version:
- Is a browser extension:

Steps to reproduce the problem:
1. i change forms value, but annontationStorage is null
2. how can i get changed form's value and download filled form

i used to cdn links

**Comment by Snuffleupagus** [comment]
> Configuration:
>     * last version chrome
>     * windows10:
>     * last version:
>     * Is a browser extension:

When opening an issue, please remember to fill out the "Configuration" section completely and also include all relevant version numbers.

> Steps to reproduce the problem:
> [...]

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
