### ISSUE TITLE
browser translate pdf

### ISSUE THREAD

**Issue by Pantyhose-X** [mozilla/pdf.js#16827]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chromium 115
- Operating system and its version:win10
- PDF.js version:3.9.179
- Is a browser extension:

Steps to reproduce the problem:
1. I want to use chromium translate to translate pdf
2. I can't translated contents 

What is the expected behavior? (add screenshot)
Use the browser's own translation function to translate pdf
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I want to use chromium translate to translate pdf

Sorry, but this is not a feature that the PDF.js library/viewer supports. (Given how PDF documents "work" it's also generally not possible to just replace a piece of text and expect that it'll render correctly.)
