### ISSUE TITLE
Inserted images do not appear in the downloaded PDF (encrypted)

### ISSUE THREAD

**Issue by bstarchuk** [mozilla/pdf.js#16821]
Attach (recommended) or Link to PDF file here:
[i-9-paper-version.pdf](https://github.com/mozilla/pdf.js/files/12312627/i-9-paper-version.pdf)

Configuration:
- Web browser and its version:  Chrome Version 115.0.5790.171 (Official Build) (64-bit)
- Operating system and its version: Windows 11 Education 22H2
- PDF.js version: 3.9.179
- Is a browser extension: no

Steps to reproduce the problem:
1. Open [attached PDF file](https://github.com/mozilla/pdf.js/files/12312627/i-9-paper-version.pdf) with PDFViewer
2. Try insert an image into a PDF
3. Download file

What is the expected behavior?
The inserted image should appear in the downloaded PDF
![image](https://github.com/mozilla/pdf.js/assets/70882822/d531550e-fd61-4cdb-9e33-aa06123be388)

What went wrong?
When you open the downloaded PDF, the inserted image is not there
![image](https://github.com/mozilla/pdf.js/assets/70882822/a0d4a1c5-6878-4778-8175-8c7e4f3e7d67)

**Comment by bstarchuk** [comment]
@calixteman How can I check?

**Comment by calixteman** [comment]
> @calixteman How can I check?

Open your pdf at https://mozilla.github.io/pdf.js/web/viewer.html and edit it.

**Comment by bstarchuk** [comment]
> > @calixteman How can I check?
> 
> Open your pdf at https://mozilla.github.io/pdf.js/web/viewer.html and edit it.

Thanks!
