### ISSUE TITLE
How can you download a pdf from any website using pdf.js which does not have a print button?

### ISSUE THREAD

**Issue by raj2577** [mozilla/pdf.js#16832]
[`Attach`](
![Screenshot 2023-08-13 181609](https://github.com/mozilla/pdf.js/assets/112565295/6ccf651a-e606-460e-9137-752f61487930)
) (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: All
- Operating system and its version: Windows
- PDF.js version: dk
- Is a browser extension: no

**Comment by Snuffleupagus** [comment]
Given the title, how does the lack of a *print*-button affect the ability to download the document!?

Using the debugger, in the browser devtools, you ought to be able to find a reference to the current `PDFDocument`-instance and then you can call its `getData`-method to get the bytes of the PDF:
https://github.com/mozilla/pdf.js/blob/8cf2f6d3527b70353599a77f26d2bce1362d47a1/src/display/api.js#L1030-L1036
which you can then download e.g. by using a Blob-URL.

---

Closing as answered, given the overall lack of actionable details (and note that this is first and foremost a *bug tracker*).
