### ISSUE TITLE
Windows 10: PDF is not rendered correctly

### ISSUE THREAD

**Issue by mikhailbartashevich** [mozilla/pdf.js#16839]
Attach (recommended) or Link to PDF file here:
[250125_010823.pdf](https://github.com/mozilla/pdf.js/files/12356264/250125_010823.pdf)

Configuration:
- Web browser and its version:
   Chrome/Firefox
- Operating system and its version:
   Windows 10
- PDF.js version:
  Actually used react-pdf, so tested 3.6 and demo version
- Is a browser extension:
  No

Steps to reproduce the problem:
1. Upload the file to https://mozilla.github.io/pdf.js/web/viewer.html using Windows 10
2. PDF is rendered partially

What is the expected behavior? (add screenshot)
<img width="1147" alt="Screenshot 2023-08-16 at 08 25 42" src="https://github.com/mozilla/pdf.js/assets/576339/13f324c0-250b-40ed-86c5-6e85e895200a">

What went wrong? (add screenshot)
![250125_010823 (1) pdf 2023-08-16 08-26-52](https://github.com/mozilla/pdf.js/assets/576339/5c96868b-9252-4a4e-81b2-9a0bcdea8e02)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
There seems to be *something* wrong with the `F0 (dict) [id: 4, gen: 0]` font, given the console log:
```
PDF 335087d4e029494fb286566728537342 [1.5 FastReport.NET / FastReport] (PDF.js: 3.10.80 [690b87389]) [viewer.js:1518:13](resource://pdf.js/web/viewer.js)
Warning: TT: more functions defined than expected [pdf.worker.js:970:13](resource://pdf.js/build/pdf.worker.js)
```

Here both `maxFunctionDefs` and `maxSizeOfInstructions` become zero, which might be related to problems:
https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/core/fonts.js#L2696-L2711

---

> Configuration:
>     * Web browser and its version:
>     * Operating system and its version:
>     * PDF.js version:
>     * Is a browser extension:

Please actually fill out this part of the ISSUE_TEMPLATE when reporting an issue!

**Comment by calixteman** [comment]
I can't reproduce the issue on mac with either Firefox or Chrome.

**Comment by griZZZly8** [comment]
Same for me. Provided pdf is not rendered correctly on Win 10. Any updated regarding this issue?

**Comment by Lyumih** [comment]
This is still relevant. Please fix it, we also faced the same problem

**Comment by calixteman** [comment]
The maxp table for the non-rendered font has a version number equals to 0x100 which is very likely wrong:
https://learn.microsoft.com/en-us/typography/opentype/spec/maxp
There is no issue on Mac or Linux.
