### ISSUE TITLE
URL parameter truncation bug causing parameter loss

### ISSUE THREAD

**Issue by signLee** [mozilla/pdf.js#16841]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:115.0.5790.110
- Operating system and its version:window 10
- PDF.js version:3.9.179
- Is a browser extension:NO

Steps to reproduce the problem:
1. When I pass the PDF address to the viewer. html page through a URL, but the PDF access address has multiple parameters, there will be parameter loss imagination.
2.  For example, do I want to open  www.xxx.com/viewer.html?file=www.xxx.com/file/demo. pdf? Key=123&from=web This PDF, but the actual access is www.xxx.com/viewer.html?file=www.xxx. com/file/demo. pdf? Key=123, all other parameters are missing.
3.I found the problem here
app.js:
const queryString = document.location.search.substring(1);
const params = parseQueryString(queryString);
file = params.get("file") ?? AppOptions.get("defaultUrl");
This should be：
 file = queryString.substring(5) ?? _app_options.AppOptions.get("defaultUrl");

What went wrong? (add screenshot)
parameters are missing

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Encode the URL, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

**Comment by rudolphi** [comment]
When updating from version 5.3.31 to 5.4.54, parameters within the properly encoded file parameter stopped working. This URL does work
https://sciflection.com/applet/pdfjs-5.3.31/web/viewer.html?file=%2FgetBindata.jsp%3Ftable%3DAnaData%26pk%3D11444%26field%3DanaDataBlob%26autoWrap%3Dtrue%26filePattern%3D*.pdf%26filename%3DMai20.pdf
while this one no longer does:
https://sciflection.com/applet/pdfjs-5.4.54/web/viewer.html?file=%2FgetBindata.jsp%3Ftable%3DAnaData%26pk%3D11444%26field%3DanaDataBlob%26autoWrap%3Dtrue%26filePattern%3D*.pdf%26filename%3DMai20.pdf
