### ISSUE TITLE
Misaligned text layer

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#16843]
Attach (recommended) or Link to PDF file here:
[16_2020-044.pdf](https://github.com/mozilla/pdf.js/files/12366234/16_2020-044.pdf)

Configuration:
- Web browser and its version: Chrome, Safari, Firefox
- Operating system and its version: macOS 13.4
- PDF.js version:  3.10.86
- Is a browser extension: no

What went wrong? (add screenshot)
<img width="949" alt="Screenshot 2023-08-17 at 08 37 52" src="https://github.com/mozilla/pdf.js/assets/6362989/87bdf83c-a1ac-449a-8cfa-82aff4e880f7">

**Comment by PritamSarbajna** [comment]
Hey @mrtcode, I'm not seeing any text layers. I think you should confirm this issue after updating your firefox version.
