### ISSUE TITLE
how to get fresh annotations when I click customized button?

### ISSUE THREAD

**Issue by Benjaminbai** [mozilla/pdf.js#16849]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 3.9.179
- Is a browser extension:

Steps to reproduce the problem:
1. create a new button to get annotations
2. listen the event, but can't get fresh annotations, just existed annotations

What is the expected behavior? (add screenshot)
I want to get fresh annotations, when I click the button 

What went wrong? (add screenshot)
but just existed annotations will output in console

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. create a new button to get annotations
>     2. listen the event, but can't get fresh annotations, just existed annotations
>
> What is the expected behavior? (add screenshot)
> I want to get fresh annotations, when I click the button
> 
> What went wrong? (add screenshot)
> but just existed annotations will output in console

Sorry, but this is nowhere near enough information/context to make this an actionable/valid issue unfortunately.

Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
