### ISSUE TITLE
PDF.js/Mozilla browser checks all checkboxes if a script enables other checkbox

### ISSUE THREAD

**Issue by peopledrivemecrazy** [mozilla/pdf.js#16863]
Attach (recommended) or Link to PDF file here: [4422-84.pdf](https://github.com/mozilla/pdf.js/files/12422360/4422-84.pdf) (https://forms.mgcs.gov.on.ca/en/dataset/014-4422-84)

Configuration:
- Web browser and its version: Chrome Version 116.0.5845.96 (Official Build) (arm64)
- Operating system and its version: Mac OS 13.5 (22G74)
- PDF.js version: latest
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Select any of the fields from hepatitis 
2. It selects several other checkboxes
<img width="823" alt="image" src="https://github.com/mozilla/pdf.js/assets/3922469/61e6034d-da13-4d33-b868-cd022a3edf53">

What is the expected behavior? (add screenshot)
1.  Check as per its restrictions
2. Works natively in chrome; safari seems to ignore restrictions

What went wrong? (add screenshot)
Checks all checkboxes
<img width="751" alt="image" src="https://github.com/mozilla/pdf.js/assets/3922469/64c722c6-33f6-4af7-a6fc-c99b49bf5540">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
I took a very quick look, and it seems to be a `resetForm`-issue because we accidentally ignore Array-arguments since `typeof [] === "object"`. Furthermore, it seems that we're not applying the `readonly`-changes correctly to the DOM-elements.
Even with that fixed though, we're *still* incorrectly changing the values in the "Hepatitis ..." sub-checkboxes.

```diff
diff --git a/src/display/annotation_layer.js b/src/display/annotation_layer.js
index 306b74c8d..a4407b008 100644
--- a/src/display/annotation_layer.js
+++ b/src/display/annotation_layer.js
@@ -373,11 +373,7 @@ class AnnotationElement {
         event.target.title = event.detail.userName;
       },
       readonly: event => {
-        if (event.detail.readonly) {
-          event.target.setAttribute("readonly", "");
-        } else {
-          event.target.removeAttribute("readonly");
-        }
+        event.target.disabled = event.detail.readonly;
       },
       required: event => {
         this._setRequired(event.target, event.detail.required);
diff --git a/src/scripting_api/doc.js b/src/scripting_api/doc.js
index 86da32249..bbc4c4d9f 100644
--- a/src/scripting_api/doc.js
+++ b/src/scripting_api/doc.js
@@ -1185,7 +1185,7 @@ class Doc extends PDFObject {

   resetForm(aFields = null) {
     // Handle the case resetForm({ aFields: ... })
-    if (aFields && typeof aFields === "object") {
+    if (aFields && typeof aFields === "object" && !Array.isArray(aFields)) {
       aFields = aFields.aFields;
     }
```

**Comment by peopledrivemecrazy** [comment]
Thank you for the quick response. Hopefully, there is PR addressing this issue.

**Comment by calixteman** [comment]
@Snuffleupagus, you almost steal my patch !! :)

**Comment by Snuffleupagus** [comment]
> you almost steal my patch !! :)

Sorry, not on purpose! (I just figured leaving a couple of quick observations wouldn't hurt, however the diff is both incomplete and untested.)

**Comment by calixteman** [comment]
Don't worry, I found that funny to have almost the same patch (and sometimes the "almost" is in your favor, I mean you point some useful things I overlooked)... as we said "team work".
