### ISSUE TITLE
Issue rendering thumbnails outside of iFrame containing the viewer

### ISSUE THREAD

**Issue by lethallynx** [mozilla/pdf.js#16861]
I am trying to reuse the already loaded pdfjsLib that is inside the iFrame to render some thumbnails in canvas's that exist on the parent page.
When I use a rasterized PDF everything is fine.
When I use a vector based PDF it has issues that can be seen below.
I have been tinkering with it for the past few days but I can't seem to figure out what is going on.
Can anyone point me in the right direction?

Attach (recommended) or Link to PDF file here: 
https://juz.me/pdfjs-test/web/helloworld-vector.pdf

Configuration:
- Web browser and its version: Chrome/Firefox
- Operating system and its version: Windows 11
- PDF.js version: 3.9.179
- Is a browser extension: No

Steps to reproduce the problem:
1. Launch sample-vector.html: (https://juz.me/pdfjs-test/web/sample-vector.html)
2. Click Render Thumbnails
3. Look at the 3 canvas elements down the bottom.

What is the expected behavior? (add screenshot)
That the three thumbnails generate correctly.
![image](https://github.com/mozilla/pdf.js/assets/963869/6afff482-e635-4abf-8945-0faf86f7b67c)

What went wrong? (add screenshot)
The generated canvas's contain an empty box in chrome and a unicode character in firefox:
![image](https://github.com/mozilla/pdf.js/assets/963869/41500db0-6359-4111-bb4a-93045c8957a3)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Broken: https://juz.me/pdfjs-test/web/sample-vector.html
Working: https://juz.me/pdfjs-test/web/sample-raster.html

Here is a zip of a fresh test against the latest release:
[pdfjs-test.zip](https://github.com/mozilla/pdf.js/files/12420347/pdfjs-test.zip)

**Comment by Snuffleupagus** [comment]
> I am trying to reuse the already loaded pdfjsLib that is inside the iFrame to render some thumbnails in canvas's that exist on the parent page.

In that case you're still loading *fonts* (and other resources) into the `iframe`-document, which makes them inaccessible in the scope where the thumbnails are being rendered. Hence adding something like `ownerDocument: globalThis.document,` to the `getDocument`-call ought to work; please note https://github.com/mozilla/pdf.js/blob/a7d829155b54ad82f6575d970689a076168f4962/src/display/api.js#L200-L202

> When I use a vector based PDF it has issues that can be seen below.

Note that this PDF document simply uses *fonts*, rather than images.

**Comment by lethallynx** [comment]
Yep that worked a treat! Thanks for the link and explanation @Snuffleupagus
