### ISSUE TITLE
Remove the "I'm developing a custom solution based on PDF.js core library. Can you help me?" section from the FAQ

### ISSUE THREAD

**Issue by connwork** [mozilla/pdf.js#16868]
Configuration:
- Web browser and its version: Firefox 116.0.3
- Operating system and its version: Windows 11, version 22H2
- PDF.js version: v3.9.179
- Is a browser extension: No

Steps to reproduce the problem:
1. Post an issue on this github page requesting any form of help that is currently unsupported by pdf.js
2. View immediate response by devs declining requested help. 

What is the expected behavior?
Good faith attempt at help as described in the "I'm developing a custom solution based on PDF.js core library. Can you help me?" section from the FAQ. 

What went wrong?
Devs do not provide good faith attempt at help as described in the "I'm developing a custom solution based on PDF.js core library. Can you help me?" section from the FAQ.

**Comment by marco-c** [comment]
We're trying to help users as much as we can, sorry to hear you feel like we aren't.

**Comment by connwork** [comment]
I know by looking at opened issues for the past several years that you likely will not respond to this, and by that same method, I know that you have canned responses for anything outside of current pdfjs functionality.

Why put this in the faq when a cursory glance at github issues shows that you do not support anything outside of current pdfjs functionality?

**Comment by marco-c** [comment]
Maybe your cursory glance was too cursory. Our job is literally to add support for additional functionality requested by users. You can take a look at many of the issues in https://github.com/mozilla/pdf.js/issues?page=1&q=is%3Aissue+is%3Aclosed+sort%3Acomments-desc+label%3Afeature or bugs on Bugzilla or ideas on Mozilla Connect.

**Comment by connwork** [comment]
Please read the issue. I'm not talking about adding functionality requested by users. I am specifically referring to custom solutions based on the PDF.js core library, as specified in the FAQ. Apologies for not being clear, I should have specifically referenced custom solutions instead of "current pdfjs functionality". 

Clearly there is a scope disconnect between the roles of requesting additional functionality within PDF.js and requesting assistance for custom solutions based on the PDF.js core library. This wouldn't be an issue if there was adequate documentation.
