### ISSUE TITLE
Wrong Font Selected for DFKai-SB 

### ISSUE THREAD

**Issue by kelibox** [mozilla/pdf.js#16870]
Attach (recommended) or Link to PDF file here:
[DFKai_Sample.pdf](https://github.com/mozilla/pdf.js/files/12430424/DFKai_Sample.pdf)

Configuration:
- Web browser and its version: Fiefox 116
- Operating system and its version: Win 10
- PDF.js version: 3.8.110
- Is a browser extension: No

Steps to reproduce the problem:
1.  Upload the Sample to Pdf.js site
2.  The char is not correct on Pdf.js
3.  Drop the Sample to Microsoft Edge 
4.  The char is correct on Edge

What is the expected behavior? (add screenshot)
I hope the char correct as next:
![edge_normal](https://github.com/mozilla/pdf.js/assets/24959130/817f27a2-a9b4-4ac6-a104-501c2dedd150)

What went wrong? (add screenshot)
I get the wrong char as :
![firefox_abnormal](https://github.com/mozilla/pdf.js/assets/24959130/205355b2-eb41-4014-8a7e-362cf7558483)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[link](https://mozilla.github.io/pdf.js/web/viewer.html?file=https://github.com/mozilla/pdf.js/files/12430424/DFKai_Sample.pdf)

**Comment by calixteman** [comment]
The console shows this message:
`Warning: Cannot load system font: DFKai-SB, installing it could help to improve PDF rendering.`
I opened the pdf in Preview, Chrome and Acrobat on mac and none of them render the pdf correctly: the missing font should really be embedded in the pdf.

**Comment by kelibox** [comment]
> The console shows this message: `Warning: Cannot load system font: DFKai-SB, installing it could help to improve PDF rendering.` I opened the pdf in Preview, Chrome and Acrobat on mac and none of them render the pdf correctly: the missing font should really be embedded in the pdf.

My platform is Windows 10

**Comment by kelibox** [comment]
https://learn.microsoft.com/zh-hk/typography/font-list/dfkai-sb
