### ISSUE TITLE
Android 端集成后，加载发票pdf文件，内容显示不全

### ISSUE THREAD

**Issue by dyzgihthub** [mozilla/pdf.js#16874]
这个是我的发票地址https://inv.jss.com.cn/fp2/sNa_ll4bnOuiYpOFk1YacuckEqPnMmzaJgVFWgAmKrtHwZiJbrbJUkJLiOy4lkWg6cjYrr2muse1aJM2DlHwsg.pdf

**Comment by Snuffleupagus** [comment]
You need to use *only* English in this bug tracker, besides you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when reporting an issue.
