### ISSUE TITLE
[Regression] Editor selection broken in some cases

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#16872]
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `master`, likely regressed by PR #16811
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Load https://mozilla.github.io/pdf.js/web/viewer.html#page=1
2. Enable e.g. Ink-editing, however all editors are similarly affected.
3. Draw something on the first page.
4. Press the <kbd>End</kbd> key to go to the last page.
5. Draw something on the last page.
6. Go back to the first page, one page at a time, by repeatedly pressing the <kbd>P</kbd> key. (To ensure that the first page is evicted from the `PDFPageViewBuffer`.)
7. Try to select the drawing on the first page, by clicking on it.

What is the expected behavior? (add screenshot)
The editor on the first page is successfully selected.

What went wrong? (add screenshot)
The editor isn't selected, and Errors such as the following are thrown:
```
Uncaught TypeError: can't access property "pageIndex", editor.parent is null
    setUpDragSession tools.js:1578
    #setUpDragSession editor.js:802
    pointerdown editor.js:793
tools.js:1578:8
```
One possible explanation here might be that we're not "properly" committing the editor to the AnnotationStorage when the page is destroyed, however it seems that we're currently accessing the `editor.parent` property in a couple of spots in the dragging-code without always checking that it's available.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

/cc @calixteman

**Comment by Snuffleupagus** [comment]
@calixteman Gentle ping, do you have time to look into this?

**Comment by calixteman** [comment]
Yep, I wrote a patch 2 weeks ago on my laptop and I didn't have time to write a test.
I'm writing a test.
