### ISSUE TITLE
Add a new url parameter for disabling warnings in the case of possible data loss

### ISSUE THREAD

**Issue by aki2014** [mozilla/pdf.js#16882]
Steps to reproduce the problem:
1. Because of the following enhancement:
https://github.com/mozilla/pdf.js/issues/12257
when leaving a page, we see a waning. But in some cases we don't want to show warnings to users.

I would like to request you to add a new url parameter for disable warning in the case of possible data loss.

2. The blow is not my post but the same issue as I described here.
https://stackoverflow.com/questions/74865020/remove-warning-when-navigating-away-from-changed-form-in-pdf-js-viewer

**Comment by Snuffleupagus** [comment]
Please note that controlling API- and/or viewer-features using hash parameters was *purposely* disabled, see issue #4954 for additional information, hence we will unfortunately *not* be adding any new ones to customize/configure the default viewer.

Also, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
