### ISSUE TITLE
Support editing already existing ink-/stamp-annotations

### ISSUE THREAD

**Issue by DDHSchmidt** [mozilla/pdf.js#16883]
Disclaimer: This is more or less a clone of issue #15403 with an expanded scope

Attach (recommended) or Link to PDF file here:
[dummy.pdf](https://github.com/mozilla/pdf.js/files/9497274/dummy.pdf)

Configuration:
- Web browser and its version: Firefox 116.0.3
- Operating system and its version: Windows 10 (22H2)
- PDF.js version: 3.8.110
- Is a browser extension: No

Steps to reproduce the problem:
1. Add an ink or stamp annotation 
2. Save the pdf under a different name
3. Reload the saved pdf
4. The added ink-/stamp-annotations are "burnt in" and can't be edited anymore

What is the expected behavior? (add screenshot)
I would have expected to be able to edit/remove the added annotations.

What went wrong? (add screenshot)
The annotations are "burnt in" after saving. Subsequent reloads of the pdf won't let me edit or remove them

**Comment by atrinker** [comment]
Are there any plans to move on this issue in an upcoming release?

**Comment by marco-c** [comment]
Yes, we are planning to work on this soon. However, if you're up for it, we'd happily accept contributions to make it happen faster.

**Comment by marco-c** [comment]
#18834 did this for stamp annotations.
#18972 is the first step to do this for ink annotations too.

**Comment by grifball** [comment]
Hi, how do you access this feature? AFAIK, ink annotations are impossible to edit after leaving annotation mode. You can still select ink annotations, but the only option is to delete them.
