### ISSUE TITLE
Add support for `Blur` and `Focus` actions

### ISSUE THREAD

**Issue by ryg-git** [mozilla/pdf.js#16887]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox, Chrome
- Operating system and its version: Windows 11, Ubuntu,
- PDF.js version: 
- Is a browser extension: Tested on extension and also generic build

Steps to reproduce the problem:
1. Open PDF file which has `Blur` and/or `Focus` action(s) for annotations.
2. Nothing happens on `onblur` or `onfocus`

What is the expected behavior? (add screenshot)

The mouse cursor should change on elements which have these actions, also `Blur` action and `Focus` action should be bound to `onblur` and `onfocus`.

What went wrong? (add screenshot)

* annotation layer is not generated for elements which have `Blur` and `Focus` actions.
* `Blur` and `Focus` actions are not bound to relevent JavaScript methods `onblur` and `onfocus`.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ryg-git** [comment]
I would like to work on this issue

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

**Comment by ryg-git** [comment]
> This part of the ISSUE_TEMPLATE is always required in order for any issue to be actionable/valid.

Unfortunately I cannot share the PDF as it is confidential.

But for what it's worth, I can share the flow,

* There is button (`PushButtonWidgetAnnotationElement`) in PDF which has `Action` or JS action `onclick`
* On this `Action` the PDF should  jump to another `AnnotationElement` but it doesn't,
* because relevant anchor tag with the relevant `data-element-id` is not generated. 
* This relevant `data-element-id` is not generated because it has PDF actions  `Focus` or JS action `onfocus` and `Blur` or js action `onblur`.
* And `pdf.js` only supports PDF actions `Action`, `Mouse Up` and `Mouse Down`.
* but I have checked that the `sandbox` ( `pdf.sandbox.js`) supports `Blur` and `Focus` actions.

Therefore I think support for `Blur` and `Focus` actions should also be added.

> Unfortunately this might not be a good beginner bug.

I have locally made changes to the library and now it is working as expected therefore I would like to add these changes here also.

Therefore please consider assigning this issue to me.

Thank you!

**Comment by Snuffleupagus** [comment]
> Unfortunately I cannot share the PDF as it is confidential.
> 
> But for what it's worth, I can share the flow,

Sorry, but that unfortunately makes this issue (or any issue really) non-actionable. Please try to create a *reduced* test-case without any sensitive data, and we can re-open this issue.

> I have locally made changes to the library and now it is working as expected therefore I would like to add these changes here also.

Sorry, but a patch that cannot be (easily) tested and verified makes reviewing quite difficult and also means that it's all too easy for it to regress in the future. Furthermore, please note that all patches *ideally* should include tests, which is this case would likely be an `integration`-test (meaning that a PDF document is needed).
