### ISSUE TITLE
Property 'str' does not exist on type 'TextItem | TextMarkedContent'.

### ISSUE THREAD

**Issue by jippy89** [mozilla/pdf.js#16909]
Attach (recommended) or Link to PDF file here:
[helloworld.pdf](https://github.com/mozilla/pdf.js/files/12540011/helloworld.pdf)

Configuration:
- Web browser and its version: Not used
- Operating system and its version: Windows 10 Home Single Language version 22H2
- PDF.js version: 3.10.111
- Is a browser extension: Nope

Steps to reproduce the problem:
Please check the following [GitHub Repository](https://github.com/jippy89/pdfjs-typescript-linter-error)

What is the expected behavior? (add screenshot)
I am able to use the `str` property in `text` which is instance of either `TextItem` or `TextMarkedContent`.

What went wrong? (add screenshot)
It's error on line 27. But basically the `text.str` results in the following error.
![error-pict-pdfjs](https://github.com/mozilla/pdf.js/assets/33748953/8ca53764-c480-43ca-a9e8-48032bce0c27)

**Comment by jippy89** [comment]
For anyone looking, the workaround is of course to use `any` type in the function and depends on [Mozilla's api.js documentation](https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib.html). But you lose all the benefits of TypeScript of course.

I tried calling the class or interface but apparently, it's not exported. So I'm stuck with this solution.

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. Install `pdfjs-dist` in a typescript project
>     2. Add the following code.

Unless you know TypeScript (which I don't), this isn't really actionable unfortunately; please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> What is the expected behavior? (add screenshot)
> I am able to use the `str` property in `text` which is instance of either `TextItem` or `TextMarkedContent`.

Looking at the JSDocs, the `TextItem` typedef *does* have a `str`-property:
https://github.com/mozilla/pdf.js/blob/cf5a1d60a61e13108afffbb1046521b5bb46f918/src/display/api.js#L1156-L1168

Hence, as a non-TypeScript user, it's not really clear to me what the problem is here.

**Comment by jippy89** [comment]
Thanks for the quick reply! Sorry for the lack of repro code. I will create a mini repro so you can see what my problem is.

> Looking at the JSDocs, the TextItem typedef does have a str-property:

Yes, I'm aware of this that's the reason I created the ticket. However, the VS Code Popup clearly tells you that `Property 'str' does not exist on type 'TextItem | TextMarkedContent'.` which means it simply doesn't exist. **When it is!** Elaborated in my second comment. Basically, what I'm trying to say is. The released code and the declaration class (which is a support for TypeScript linter) are different.

**Comment by jippy89** [comment]
Thanks for the quick reply! Sorry for the lack of repro code. I will create a mini repro so you can see what my problem is.

> Looking at the JSDocs, the TextItem typedef does have a str-property:

Yes, I'm aware of this that's the reason I created the ticket. However, the VS Code Popup clearly tells you that `Property 'str' does not exist on type 'TextItem | TextMarkedContent'.` which means it simply doesn't exist. **When it is!** Which is why I give workaround solution in my second comment. Basically, what I'm trying to say is. The released code and the declaration class (which is a support for TypeScript linter) are different.

**Comment by jippy89** [comment]
Ah nevermind, turns out I just needed to add a safe guard. Silly me, been a while since I used TypeScript.
Thanks for the support!
