### ISSUE TITLE
Cant make search working

### ISSUE THREAD

**Issue by ollita7** [mozilla/pdf.js#16908]
Currently I cannot do a search using the new approach.

Im currently using the dispatch approach but nothing happens.

```js
if (search_param) {
    eventBus.dispatch("find", { type: "", query: search_param });
}
```

This issue is related to the closed one **https://github.com/mozilla/pdf.js/issues/15777**

**Comment by ollita7** [comment]
Are kidding me? Can you give us an example of the eventBus find working? What you suggest and what you have on your repository sample is not working.

**Comment by Snuffleupagus** [comment]
When I test this locally, following the steps below, searching works just fine:
 - Complete *all* steps listed in https://github.com/mozilla/pdf.js#getting-the-code
 - Run `gulp dist-install`
 - Change https://github.com/mozilla/pdf.js/blob/cf5a1d60a61e13108afffbb1046521b5bb46f918/examples/components/simpleviewer.js#L38 into e.g. `const SEARCH_FOR = "Mozilla";`
 - Open http://localhost:8888/examples/components/simpleviewer.html in a browser.
