### ISSUE TITLE
ScrollMode and SpredMode are not working

### ISSUE THREAD

**Issue by RZ-Jyothsna** [mozilla/pdf.js#16918]
I am using
node version: 18.0.0
pdfjs-dist: ^3.10.111
framework: react18
browser: chrome(Version 116.0.5845.140 (Official Build) (64-bit))

I am using PDFViewer and i tried to set scrollMode to 1 (Horizontal)."scrollmodechanged" event got listened and
PDFViewer object data also got updated. But I could not see changes in the broswer. The same thing happend with spearMode.
Kindly help me to resolve this.

**Comment by Snuffleupagus** [comment]
> Kindly help me to resolve this.

That's unfortunately *impossible* without a runnable example, since only a text description of the problem does not really help.

Please don't keep reporting completely non-actionable issues, see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
