### ISSUE TITLE
pdfViewer.scrollPageIntoView() is not working.

### ISSUE THREAD

**Issue by RZ-Jyothsna** [mozilla/pdf.js#16913]
I am using
node version: 18.0.0
pdfjs-dist: "3.9.179"
framework: react18
browser: chrome(Version 116.0.5845.140 (Official Build) (64-bit))

I got "is not a valid page number" as error message when trying to use "scrollPageIntoView" in PDFViewer. I guess _pages[pageNumber - 1] has not returned page data.
for "pdfViewer.pagesCount", "0" is displayed in console.

How to fix this.

**Comment by Snuffleupagus** [comment]
> pdfjs-dist: "3.9.179"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> framework: react18

Unfortunately it's very difficult for the (few) PDF.js contributors to provide help/support for the myriad of JS frameworks that exist.

> I got "is not a valid page number" as error message when trying to use "scrollPageIntoView" in PDFViewer. I guess _pages[pageNumber - 1] has not returned page data.
> for "pdfViewer.pagesCount", "0" is displayed in console.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by RZ-Jyothsna** [comment]
I have upgraded the pdfjs-dist to "^3.10.111". 
I am using PDFViewer and i tried to set scrollMode to 1 (Horizontal)."scrollmodechanged" event got listened and
PDFViewer object data also got updated. But I could not see changes in the broswer.  The same thing happend with spearMode.
Kindly help me to resolve this.
