### ISSUE TITLE
The big "{" shows small when export to pdf

### ISSUE THREAD

**Issue by Applauzzz** [mozilla/pdf.js#16919]
The .md and preview.
![ed498cce1f1a7960e83164ceffcbd57](https://github.com/mozilla/pdf.js/assets/88478579/fc1d910a-b933-4854-970b-a594bfc60659)
The exported pdf
![91be3e0bd47b0616378b2095e9de3a8](https://github.com/mozilla/pdf.js/assets/88478579/d9fa6254-9971-43b6-bebb-06812e6163e4)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (rather than just removing the template) since this issue is unfortunately missing every necessary detail in order to be actionable.
