### ISSUE TITLE
update babel dependency to 7.22.17

### ISSUE THREAD

**Issue by yardenac** [mozilla/pdf.js#16922]
Older versions of babel are broken with Node 20.6, see https://github.com/babel/babel/issues/15927

**Comment by Snuffleupagus** [comment]
Given that we're using the Node.js LTS version in CI, both for testing and building the library, I don't think that we're affected by that issue right now.

Furthermore, please note that we're already doing regular (biweekly) updates of npm packages hence this will be handled as part of our normal development work.

**Comment by yardenac** [comment]
So you don't support git builds on any other platform? I'm maintaining the AUR package for this which won't build until you bump babel https://aur.archlinux.org/packages/chromium-pdfjs-git
