### ISSUE TITLE
Auto-Print Function Fails in Firefox Silent Mode Post PDF-to-Canvas Rendering

### ISSUE THREAD

**Issue by BryarGH** [mozilla/pdf.js#16924]
I'm not sure what could be possible wrong here but will give you all the details as long as I can. 

Configuration:
- Web browser and its version: Firefox 117
- Operating system and its version: Windows 10
- PDF.js version: 3.10.111
- Is a browser extension: No

**Steps to Reproduce the Problem:**

1. **Setup & Configuration**
    - We use the NexoPOS system for our point-of-sale operations.
    - NexoPOS offers two distinct methods to print receipts.
    - Due to our unique design requirements, we opted to use TCPDF for designing our PDF receipts.
    - To facilitate printing, this PDF is then converted into a canvas format.

2. **Implementation Process**
    - The browser is directed to access the `pdfGenerator` page.
    - The primary function of this page is to generate the PDF version of the receipt.
    - Upon successful generation, it provides a URL for `pdf.js` to fetch and process.
    - `pdf.js` takes the responsibility to convert this PDF into a canvas, prepping it for the printing process.

3. **Silent Mode Operations**
    - When the silent mode is activated within NexoPOS, it discreetly accesses the designated printing page. This ensures that the user remains unaware of the underlying processes.
    - Immediately after, the auto-print function is triggered.

4. **Issue with Firefox in Silent Mode**
    - The challenge arises exclusively when using Firefox in silent mode.
    - Despite the successful generation and conversion of the PDF to canvas using `pdf.js`, the rendering process inexplicably halts.
    - This interruption occurs immediately post the `renderTask` phase. Consequently, the subsequent function, i.e., `renderTask.onFinish()` or its associated promise, fails to execute. This means the auto-print function remains dormant and doesn't initiate.

**Comment by Snuffleupagus** [comment]
> The challenge arises exclusively when using Firefox in silent mode.

I'm not entirely sure what "silent mode" means here, please provide more context/information.
Anyway, could that not potentially suggest a *browser issue* rather than a PDF.js library one?

> Despite the successful generation and conversion of the PDF to canvas using `pdf.js`, the rendering process inexplicably halts.
> This interruption occurs immediately post the `renderTask` phase.

So, to clarify, you're saying that the `renderTask.promise` resolves as expected here? (Given your next statement this isn't totally clear, at least to me.)
Note that `renderTask.promise` won't resolve until rendering is fully complete.

> Consequently, the subsequent function, i.e., `renderTask.onFinish()` or its associated promise, fails to execute.

Please note that no such method actually exists, which makes this a bit difficult to understand; see https://github.com/mozilla/pdf.js/blob/18a661b6a09fc3b7f4bfaaf4205d760aed61ab3b/src/display/api.js#L3223-L3275

If the problem is actually that `renderTask.promise` never resolves, then my only *guess* would be that it might be related to `requestAnimationFrame` (which is used during rendering) since that may perhaps not fire as expected in "silent mode".
The way around that would be to set `intent: "print"` in the `PDFPageProxy.render` call, which seems appropriate in this case anyway since you're indeed generating output for printing; see https://github.com/mozilla/pdf.js/blob/18a661b6a09fc3b7f4bfaaf4205d760aed61ab3b/src/display/api.js#L1199-L1243 and https://github.com/mozilla/pdf.js/blob/18a661b6a09fc3b7f4bfaaf4205d760aed61ab3b/src/display/api.js#L1421-L1439

In any case, with only a text description of the problem it's unfortunately going to be *really* difficult (or even impossible) for anyone to help; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by BryarGH** [comment]
This is my code by the way.. Also, attaching a video of both browsers..

```
pdfjsLib.getDocument(pdfFileUrl).promise.then(function(pdfDoc_) {
                        pdfDoc = pdfDoc_;
                        var pageNumber = 1;
                        pdfDoc.getPage(pageNumber).then(function(page) {
                            var viewport = page.getViewport({ scale: 1.5 });
                            pdfCanvas.height = viewport.height;
                            pdfCanvas.width = viewport.width;
                            var renderContext = {
                                canvasContext: context,
                                viewport: viewport
                            };
                            var renderTask = page.render(renderContext);
                            console.log("Testing 1");
                            // Chain another then to the renderTask.promise
                            renderTask.promise.then(function() {
                                console.log("Testing")
                                @includeWhen( request()->query( 'autoprint' ) === 'true', '/pages/dashboard/orders/templates/_customautoprint' );
                                // Send a POST request to delete the temp file after rendering
                                fetch('http://localhost/EpsonPrinter/deleteTempFile.php', {
                                    method: 'POST',
                                    headers: {
                                        'Content-Type': 'application/json'
                                    },
                                    body: JSON.stringify({ pdfFileUrl: pdfFileUrl })
                                })
                                .then(response => response.json())
                                .then(data => {
                                    if (data.success) {
                                        console.log("Temp file deleted successfully.");
                                    } else {
                                        console.error("Error deleting temp file:", data.message);
                                    }
                                })
                                .catch(error => console.error('Error:', error));
                            });
                        });
                    });
```

This is a short video
[POS — NexoPOS 4.x - [InPrivate] - Microsoft​ Edge 2023-09-09 16-43-16.zip](https://github.com/mozilla/pdf.js/files/12565935/POS.NexoPOS.4.x.-.InPrivate.-.Microsoft.Edge.2023-09-09.16-43-16.zip)

**Comment by BryarGH** [comment]
About silent mode, active mod is when the user browse this page:
/dashboard/orders/receipt/{id}

Here they can click on a button and print which works fine but silent mode:
/dashboard/orders/receipt/{id}?dash-visibility=disabled&autoprint=true

Is where the use doesn't see the screen and printing will be auto.. This is when the problem arise with Firefox

**Comment by BryarGH** [comment]
IF you have any more questions please let me know.

**Comment by Snuffleupagus** [comment]
> IF you have any more questions please let me know.

Unfortunately you've not really answered *any* of the questions asked in https://github.com/mozilla/pdf.js/issues/16924#issuecomment-1712513634, and there's also no indication that you actually tested the suggestion made there (regarding using `intent: "print"` for rendering).
Furthermore, as was also mentioned above you'll need to provide a *runnable example* in order for anyone to have any chance of assisting you here.

**Comment by BryarGH** [comment]
> > IF you have any more questions please let me know.
> 
> Unfortunately you've not really answered _any_ of the questions asked in [#16924 (comment)](https://github.com/mozilla/pdf.js/issues/16924#issuecomment-1712513634), and there's also no indication that you actually tested the suggestion made there (regarding using `intent: "print"` for rendering). Furthermore, as was also mentioned above you'll need to provide a _runnable example_ in order for anyone to have any chance of assisting you here.

I can not provide an active link because this is a local Laravel Vue project, which has thousands of files but let me answer your questions or at least I will try... 

I think I have already answered what was the silent mode of printing. I have also attached a video to this process. 

`renderTask.onFinish()` this was a mistake so please ignore it. 

Everything works fine in silent mode and active mode but :
```renderTask.promise.then(function() {
                                console.log("Testing")
                                @includeWhen( request()->query( 'autoprint' ) === 'true', '/pages/dashboard/orders/templates/_customautoprint' );
                                // Send a POST request to delete the temp file after rendering
                                fetch('http://localhost/EpsonPrinter/deleteTempFile.php', {
                                    method: 'POST',
                                    headers: {
                                        'Content-Type': 'application/json'
                                    },
                                    body: JSON.stringify({ pdfFileUrl: pdfFileUrl })
                                })
                                .then(response => response.json())
                                .then(data => {
                                    if (data.success) {
                                        console.log("Temp file deleted successfully.");
                                    } else {
                                        console.error("Error deleting temp file:", data.message);
                                    }
                                })
                                .catch(error => console.error('Error:', error));
                            });
 ```
                            
This code or what is inside the promise doesn't work or get activated that is the issue am going through and only happens in Firefox. 

We have two ways to load the same page either loading through the browser via URL which works fine on Firefox/Chrome or in background when the user want to print this without seeing the generated document or page. 

Vue and Laravel in background will process loading the same url, get the generatet canva and send a message box to print it with the API or normal prinitng box windows.print(). This message box is inside this promise `@includeWhen( request()->query( 'autoprint' ) === 'true', '/pages/dashboard/orders/templates/_customautoprint' );` Here exactly. 

The promise or render should be done then this will be executed , the problem is here on Firefox it doesn't so most likely is keep rendering? but on Chrome everything is fine .

I didn't really get what did you mean by this:
`intent: "print"`

**Comment by Snuffleupagus** [comment]
> I can not provide an active link because this is a local Laravel Vue project,

Without being able to easily reproduce the problem, it's simply *impossible* for anyone to help you unfortunately.

> I think I have already answered what was the silent mode of printing. I have also attached a video to this process.

Unfortunately I don't think so, and it's not possible to debug anything from a video alone.

> Vue and Laravel

Please keep in mind that the PDF.js contributors cannot provide help with the plethora of JS frameworks that exists.

> I didn't really get what did you mean by this:
> `intent: "print"`

Use `intent: "print"` when rendering the page, note that https://github.com/mozilla/pdf.js/issues/16924#issuecomment-1712513634 already linked to both the JSDocs and the method-signature in question. Hence you'd change this part of your code-snippet:
```javascript
var renderContext = {
  canvasContext: context,
  viewport: viewport,
};
```
into the following instead:
```javascript
var renderContext = {
  canvasContext: context,
  viewport: viewport,
  intent: "print",
};
```

**Comment by BryarGH** [comment]
You understood this or not but this fixed it: `intent: "print"` 

Thanks for your help :)
