### ISSUE TITLE
Arabic text issue on Mac using Chrome

### ISSUE THREAD

**Issue by moataseme** [mozilla/pdf.js#16933]
[Screenshot](https://imgur.com/a/yCGQpql)

Example document:
https://easyupload.io/iclwni

Configuration:
- Web browser and its version: Google Chrome latest version
- Operating system and its version: Mac
- PDF.js version: Latest version
- Is a browser extension:
- 

Code:

`
<div id="pdf"></div>

<script>
        window.onload = function(){
            var thePdf = null,
                scale = 2.5,
                base64pdf = atob('{{ $pdf }}');

            pdfjsLib.disableWorker = true;
            
            pdfjsLib.getDocument({data: base64pdf}).promise.then(function(pdf) {
                thePdf = pdf;
                viewer = document.getElementById('pdf');
                
                for(page = 1; page <= pdf.numPages; page++) {
                    canvas = document.createElement("canvas");    
                    canvas.className = 'pdf-page-canvas';         
                    viewer.appendChild(canvas);            
                    renderPage(page, canvas);
                }
            });
    
            function renderPage(pageNumber, canvas) {
                thePdf.getPage(pageNumber).then(function(page) {
                    viewport = page.getViewport({ scale: scale });
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;          
                    page.render({canvasContext: canvas.getContext('2d'), viewport: viewport});
                });
            }
        }
</script>
`

Is there a method to change the font or convert pages to images?

**Comment by timvandermeij** [comment]
You can convert pages to images using e.g. the PNG export example at https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png. Furthermore PDF.js renders purely what is in the document, so changing fonts is not possible.
