### ISSUE TITLE
Text is not rendering in iOS/macOS Lockdown Mode

### ISSUE THREAD

**Issue by pajowu** [mozilla/pdf.js#16945]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html 

Configuration:
- Web browser and its version: Mobile Safari 16.6, Safari 16.6
- Operating system and its version: iOS 16.6, macOS 13.5.2
- PDF.js version: tested on 2.9.359, 3.11.52, 3.11.111
- Is a browser extension: No

Steps to reproduce the problem:
1. [Enable Lockdown Mode](https://support.apple.com/en-gb/HT212650) on an iOS Device or macOS Device
2. Open the [pdfjs demo page](https://mozilla.github.io/pdf.js/web/viewer.html)
3. Navigate to page 12

What is the expected behavior? (add screenshot)

The pdf, including the text, is rendered

![Screenshot 2023-09-13 at 12 00 20](https://github.com/mozilla/pdf.js/assets/6545097/4f4664c8-fd76-45ef-87ad-7714e6916f85)

What went wrong? (add screenshot)

The text on the page is not rendered, only the graphics. The loading spinner is shown indefinitely

![IMG_12F087AE4192-1](https://github.com/mozilla/pdf.js/assets/6545097/7583800f-9cd1-488f-8612-2b25bfd1fc1b)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by pajowu** [comment]
No errors are shown in the developer console

**Comment by Snuffleupagus** [comment]
Please note that Safari is only listed as "mostly" supported, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, and that the *built-in* Firefox PDF Viewer is the primary development target for this library.

Hence I'm sorry to say that "Lockdown Mode" in Safari isn't really something that we do (or intended to) support unfortunately.

**Comment by pajowu** [comment]
Ok, thanks for the quick response. Would you be willing to merge a PR that fixes this if I (or someone else) finds a solution for that?

**Comment by pajowu** [comment]
The underlaying bug seems to be in WebKit, I opened a [bug in the WebKit bugzilla](https://bugs.webkit.org/show_bug.cgi?id=261508) for that now.

The attached patch would fix this on pdf.jss side as well. If you say this is an acceptable patch to include in pdf.js, I would open a PR.

[261508.patch](https://github.com/mozilla/pdf.js/files/12598201/261508.patch)

**Comment by calixteman** [comment]
@nt1m, maybe you could help here.

**Comment by pajowu** [comment]
Yes, this almost certainly is a webkit bug, with them not following the w3c spec properly. That's why I opened the bug report with webkit.

However the workaround for this in pdfjs is relatively small (1 LOC) and should have no side-effects (see the patch in https://github.com/mozilla/pdf.js/issues/16945#issuecomment-1717679447). That's the reason for my question whether I should open a PR with this workaround?

**Comment by Snuffleupagus** [comment]
> Yes, this almost certainly is a webkit bug, with them not following the w3c spec properly. That's why I opened the bug report with webkit.

Thank you, it indeed seems to be a *browser* bug.

> However the workaround for this in pdfjs is relatively small (1 LOC) and should have no side-effects (see the patch in [#16945 (comment)](https://github.com/mozilla/pdf.js/issues/16945#issuecomment-1717679447)). That's the reason for my question whether I should open a PR with this workaround?

To be honest, I don't think it's really our "responsibility" to work-around a *browser* bug here. (While it maybe won't have side-effects, who would "guarantee" that?)

**Comment by pajowu** [comment]
> (While it maybe won't have side-effects, who would "guarantee" that?)

The same standard that guarantees that we don't need this call:

> For fonts constructed from binary data [...] it does nothing.
> -- https://www.w3.org/TR/css-font-loading/#font-face-load

So the tradeoff would be between a known browser bug and potential unknown browser bugs (that tbh seem very unlikely)
