### ISSUE TITLE
Is XFA layer and Text layer mutually exclusive? 

### ISSUE THREAD

**Issue by SushmaRaghu** [mozilla/pdf.js#16942]
Hi,
I am trying to render xfa support to our product using pdf.js. I have a few clarifications. 
Currently I am using the below code to render xfa : 
 
                   `if(page.isPureXfa)`
                        {
                         page.getXfa().then(function(xfaHtml){
                        var pdfJSGlobal = @com.daeja.viewone.ajax.client.renderer.PDFNativeBridge::pdfJSGlobal;
                        var xfaDiv = document.createElement("div");
                        var parameters = {
                        viewport: viewport.clone({ dontFlip: true }),
                           div: xfaDiv,
                           xfaHtml:xfaHtml,
                           annotationStorage: pdfJSGlobal.annotationStorage,
                           linkService: pdfJSGlobal.linkService,
                           intent:"display",
                           };
                        pdfJSGlobal.XfaLayer.render(parameters);
                        imageCallback.onCompleted(xfaDiv, imgSrc, cappedScale,null);
                 });
            }
           else  //Render text layer

 If I try to render xfaDiv also along with textDiv, I get errors.  So I am assuming, xfa layer is different from a text layer. 
I want to know if xfa layer and text layer are mutually exclusive ? Should we use isPureXfa to render XFA Forms separately and handle text forms in the else block ? 
 
Thanks
Sushma Raghupathi

**Comment by Snuffleupagus** [comment]
> I want to know if xfa layer and text layer are mutually exclusive?

Yes, XFA documents don't use a separate textLayer since they are different (in lots of ways) from "normal" PDF documents

> Should we use isPureXfa to render XFA Forms separately and handle text forms in the else block?

There's not really a question of should, you *need* to handle XFA documents separately.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md rather than ignoring the template.

Also, note that code snippets are not really useful; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
