### ISSUE TITLE
Some characters are not rendered or not correct.

### ISSUE THREAD

**Issue by binle** [mozilla/pdf.js#16971]
Attach (recommended) or Link to PDF file here: [V01.SSC.N.20230908.2023090801-40010201.pdf](https://github.com/mozilla/pdf.js/files/12644541/V01.SSC.N.20230908.2023090801-40010201.pdf)

Configuration:
- Web browser and its version: Chrome version 116.0.5845.188
- Operating system and its version: window 11 .   Version	10.0.22621 Build 22621
- PDF.js version: 3.9.54, (It also occur in https://mozilla.github.io/pdf.js/web/viewer.html)

Steps to reproduce the problem:
 -  use the attached pdf file 

What went wrong? (add screenshot)
the result: some text in header are not rendered or not correct
![image](https://github.com/mozilla/pdf.js/assets/13077778/ca31c32d-783f-4f2f-a2fe-eb3f2f6d8967)

It should be like this:
![image](https://github.com/mozilla/pdf.js/assets/13077778/e3bd5245-b36e-4ff8-8140-9100f516e9c5)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.11.42 [cf7efdb04] in Firefox Nightly 119.0a1 on Windows 11. (Please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target for this library.)

![firefox](https://github.com/mozilla/pdf.js/assets/2692120/2bd14ba7-91ea-45cb-9a6c-4fd0cf8a2131)
