### ISSUE TITLE
Could you please explain why the default full viewer cannot be directly used??????

### ISSUE THREAD

**Issue by lliendo** [mozilla/pdf.js#16997]
Hi,

I'm going to be polite. This non-sense is baffling: [Setup-pdf.js](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website)

And from an older issue: [Issue 9210](https://github.com/mozilla/pdf.js/issues/9210#issuecomment-347834276) Quote: **"Hence we don't want to make it too simple to use it directly."** Honestly, what is that????

What I'm supposed to do? Go through the ~2000 LOC of `PDFViewerApplication` from `web/viewer.js` to just make the full viewer work? Now I think I understand **why** it wasn't added under `examples`. Can you please explain what's the whole point of this crap?

Maybe you can learn a bit from Leaflet, simply adding proper attribution should be enough provided you want credit. Please make things simpler and easier, and not harder as quoted. No one wants to waste time.

**Comment by marco-c** [comment]
This behavior is not tolerated here.
