### ISSUE TITLE
How i can create a mouse move in a PDF preview

### ISSUE THREAD

**Issue by Marcelin97** [mozilla/pdf.js#17008]
Configuration:
- Web browser and its version: chrome
- Operating system and its version: Ubuntu 20.04.6 LTS
- PDF.js version: "pdfjs-dist": "3.4",

**Comment by Snuffleupagus** [comment]
> PDF.js version: "pdfjs-dist": "3.4",

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

As-is this issue unfortunately contains nowhere near enough information to understand *exactly* what you're asking about, and please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
