### ISSUE TITLE
The watermark display is abnormal, and the text of the watermark covers the main text

### ISSUE THREAD

**Issue by seayao** [mozilla/pdf.js#17025]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:google chrome 116.0.5845.140(arm64)
- Operating system and its version:macos 13.4
- PDF.js version:  v2.0.489, the latest version(v3.11.174) has the same issue 
- Is a browser extension:no

Steps to reproduce the problem:
1. The watermark display is abnormal, and the text of the watermark covers the main text

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/29435027/b174e533-192b-4114-80f9-a4f3a87adfe8)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/29435027/24a62c00-8d21-4dc2-b2ef-e8a4749bd88d)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Here is the original PDF file：
[水印异常文件测试.pdf](https://github.com/mozilla/pdf.js/files/12711860/default.pdf)

**Comment by Snuffleupagus** [comment]
We're matching the rendering in Adobe Reader, i.e. the PDF reference implementation, hence there's unfortunately *something* wrong with the PDF document *itself* if different PDF Viewers don't agree here; see

![adobe](https://github.com/mozilla/pdf.js/assets/2692120/6ba7ece4-cf19-4162-bb94-f9bae46675c6)
