### ISSUE TITLE
Broken CSS Build in pdfjs-dist (v3.11.174) 

### ISSUE THREAD

**Issue by andrewlistopadov** [mozilla/pdf.js#17044]
Configuration:
- PDF.js version: v3.11.174

What went wrong? (add screenshot)
There seems to be new images import in `pdfjs-dist/web/pdf_viewer.css`
```
  --alt-text-add-image: url(images/altText_add.svg);
  --alt-text-done-image: url(images/altText_done.svg);
```

But there are no such files there. Build is failed due to this reason.

`pdfjs-dist/web/pdf_viewer.css:835:29: Can't resolve 'images/altText_add.svg' in '.../node_modules/pdfjs-dist/web'`
`pdfjs-dist/web/pdf_viewer.css:836:30: Can't resolve 'images/altText_done.svg' in '.../node_modules/pdfjs-dist/web'`

**Comment by yu-nakagawa** [comment]
I faced the same problem. I demand immediate improvement.

**Comment by timvandermeij** [comment]
@calixteman This seems related to the new alt text dialog; could you perhaps take a look at this?

**Comment by Snuffleupagus** [comment]
This should be pretty trivial to fix, simply [by extending this list](https://github.com/mozilla/pdf.js/blob/71bffcc7a94a74eff4fbd9728d1b5ad14476c1c1/gulpfile.mjs#L1071-L1074) to include the new images, however after seeing the https://github.com/mozilla/pdf.js/issues/17044#issuecomment-1740451511 (which comes across as rude and entitled) I simply didn't feel like spending by spare time writing a patch for this.
