### ISSUE TITLE
Error in console in demo viewer

### ISSUE THREAD

**Issue by user100582** [mozilla/pdf.js#17047]
Attach (recommended) or Link to PDF file here: 
[document_signature.pdf](https://github.com/mozilla/pdf.js/files/12751818/document_signature.pdf)

Configuration:
- Web browser and its version: Chrome 117.0.5938.63 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 3.11.186
- Is a browser extension: no

Steps to reproduce the problem:
1. go to https://mozilla.github.io/pdf.js/web/viewer.html
2. click on Open File button
3. choose attached pdf

What is the expected behavior? (add screenshot)
document is rendered in viewer and we do not see error in console tab
What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/127196044/6b96a9ce-9639-4c60-80d8-49a5c9b2370d)
error in console tab appears when you open uploaded document (currentPageNumber: "4" is not a valid page.
set currentPageNumber	@	pdf_viewer.js:390)
although document is displayed
![image](https://github.com/mozilla/pdf.js/assets/127196044/5cdfa95f-ff0f-4d04-9081-b6fd98d5f6e6)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
I cannot reproduce with, as of this writing, PDF.js version `3.11.200` [52862893f].

Besides, this is only a log message and not an actual Error hence it can be safely ignored; please note: https://github.com/mozilla/pdf.js/blob/52862893f5bef7ff6c7b8f816154d8fec00f49e7/web/pdf_viewer.js#L391
