### ISSUE TITLE
Wrong value when loading field values from annotationStorage

### ISSUE THREAD

**Issue by jsanahuja** [mozilla/pdf.js#17046]
Attach (recommended) or Link to PDF file here:
[test_form.pdf](https://github.com/mozilla/pdf.js/files/12750286/test_form.pdf)

Configuration:
- Web browser and its version: Google Chrome 117.0.5938.92
- Operating system and its version: Windows 10 Business 10.0.19045 19045
- PDF.js version: 3.9.179
- Is a browser extension: No

Steps to reproduce the problem:
1. Edit `viewer.html` and add the following code to set values in `annotationStorage` before rendering.
```js
<script>
  (function(){
    var customValues = {
      '12R': true,
      '13R': 'Test',
      '15R': true,
      '16R': false,
      '17R': false,
      '19R': 'Item4L',
      '21R': 'Item2'
    };
    document.addEventListener("webviewerloaded", () => {
      PDFViewerApplication.initializedPromise.then(() => {
        PDFViewerApplication.eventBus.on('pagesloaded', (e) => {
          for (let key in customValues) {
            PDFViewerApplication.pdfDocument.annotationStorage.setValue(key, { value: customValues[key] });
          }
        });
      });
    });
  })();
</script>
```
2. Open viewer and see all fields have the loaded value but text field.

What is the expected behavior? (add screenshot)
**(Ignore field background colors, that was set for testing)**
Set the value from annotationStorage 
![image](https://github.com/mozilla/pdf.js/assets/16489902/ab87f081-303c-4dd4-a5c9-a66404b835b8)

What went wrong? (add screenshot) 
**(Ignore field background colors, that was set for testing)**
Text field does not load correctly annotationStorage value:
![image](https://github.com/mozilla/pdf.js/assets/16489902/c8ecd0c5-655c-4891-972d-b4d6a2c08b16)
On `focus` it does set the correct value but if I do not change it, sets back the default value on `blur`
![image](https://github.com/mozilla/pdf.js/assets/16489902/875965a2-75a0-43ce-b6ac-0b82f795cb22)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.9.179

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by calixteman** [comment]
A text field has 2 values: the one entered by the user, e.g. 123 (userValue or value), and the one displayed when the field is unfocused, e.g. 123,00€ (formattedValue).

**Comment by jsanahuja** [comment]
> formattedValue



> A text field has 2 values: the one entered by the user, e.g. 123 (userValue or value), and the one displayed when the field is unfocused, e.g. 123,00€ (formattedValue).
Shouldn't then `annotationStorage.getValue(id, {})` include `formattedValue`?

**Comment by calixteman** [comment]
Yes maybe... `formattedValue === null` just means that nothing set it (usually an embedded js code can format the string). So it's up to you to guess that in such a case the formatted value is the value or maybe you could do something else with this information... I don't know.
That said, if you don't have a real bug in the Firefox pdf viewer or  at https://mozilla.github.io/pdf.js/web/viewer.html, we won't fix anything (except of course if something is obviously completely wrong). Here I've the impress it's just a detail and likely a matter of taste.

**Comment by jsanahuja** [comment]
> Yes maybe... `formattedValue === null` just means that nothing set it (usually an embedded js code can format the string). So it's up to you to guess that in such a case the formatted value is the value or maybe you could do something else with this information... I don't know.

Then I would say `value` should have more "priority" than default value. That is:
https://github.com/mozilla/pdf.js/blob/3072efa064cf92dabd5191e5be4ffef02102df0d/src/display/annotation_layer.js#L1201-L1202 Should be:
```js
let fieldFormattedValues =
        storedData.formattedValue || storedData.value || this.data.textContent?.join("\n") || null;
```
And these both https://github.com/mozilla/pdf.js/blob/3072efa064cf92dabd5191e5be4ffef02102df0d/src/display/annotation_layer.js#L1217 https://github.com/mozilla/pdf.js/blob/3072efa064cf92dabd5191e5be4ffef02102df0d/src/display/annotation_layer.js#L1224 simply use `fieldFormattedValues `

**Comment by calixteman** [comment]
`this.data.textContent` is built from the appearance stream (the one you've when you print a form for example) so it's a formatted value and has the precedence over value.

**Comment by jsanahuja** [comment]
I believe that default values (formatted or not) shouldn't take precedence over `annotationStorage` values. It would be more intuitive if they behaved like user input values.

For example, on user input:
https://github.com/mozilla/pdf.js/blob/3072efa064cf92dabd5191e5be4ffef02102df0d/src/display/annotation_layer.js#L1245-L1254  `elementData.formattedValue` is set to `null` to prevent exactly this (in case formattedValue is not updated by the PDF)

Anyway, I will go with setting `formattedValue` myself but thank you for your prompt responses and the clarification!
