### ISSUE TITLE
Setting theme programmatically does not seem to work

### ISSUE THREAD

**Issue by jsanahuja** [mozilla/pdf.js#17057]
Attach (recommended) or Link to PDF file here:
(not related to PDF)

Configuration:
- Web browser and its version: Google Chrome 117.0.5938.132 64 bits
- Operating system and its version: Windows 10 Business 22H2 19045.3448
- PDF.js version: 3.11.174
- Is a browser extension: No

Steps to reproduce the problem:
1. Edit `viewer.html` and set dark theme.
```html
<script>
  (function(){
    document.addEventListener("webviewerloaded", () => {
        appOptions.set('disablePreferences', true);
        appOptions.set('viewerCssTheme', 2); // 0-Automatic, 1-Light, 2-Dark
    });
  })();
</script>
```
2. Open PDFViewer

What is the expected behavior? (add screenshot)
Show `DARK` theme:
![image](https://github.com/mozilla/pdf.js/assets/16489902/765c2262-40ae-426f-aec6-a02338ba45e3)

What went wrong? (add screenshot)
Shows `AUTOMATIC` theme:
![image](https://github.com/mozilla/pdf.js/assets/16489902/03f1f0a9-19a1-499d-833c-3f27133af643)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**More info**
This did not happen in `3.9.179`. I have investigated a bit and seen now there are 3 media rules for dark theme. Folder `old_pdfviewer` is `3.9.179` and `pdfviewer` is `3.11.174`:
![image](https://github.com/mozilla/pdf.js/assets/16489902/c570a2d2-e447-4354-b4d2-80ed252dd060)
But the method [_forceCssTheme](https://github.com/mozilla/pdf.js/blob/f5367f01ca33bbdfb9165850776f7b9de0a65f55/web/app.js#L408C3-L408C17) only affects the first media rule (returning after the first match)
![image](https://github.com/mozilla/pdf.js/assets/16489902/c70ef30c-d1dd-4396-ac9e-170ac17e3b69)

**Comment by jsanahuja** [comment]
Since the three rules are in different files, I understand that they belong to different components. Therefore, perhaps the simplest solution would be to implement the following change:
```diff
diff --git a/app.js b/app.js
--- a/app.js
+++ b/app.js
@@ -424,8 +424,7 @@ const PDFViewerApplication = {
         ) {
           if (cssTheme === ViewerCssTheme.LIGHT) {
             styleSheet.deleteRule(i);
-            return;
-          }
+          } else {
             // cssTheme === ViewerCssTheme.DARK
             const darkRules =
                 /^@media \(prefers-color-scheme: dark\) {\n\s*([\w\s-.,:;/\\{}()]+)\n}$/.exec(
@@ -435,7 +434,7 @@ const PDFViewerApplication = {
                 styleSheet.deleteRule(i);
                 styleSheet.insertRule(darkRules[1], i);
             }
-          return;
+          }
         }
       }
     } catch (reason) {
```

**Comment by Snuffleupagus** [comment]
> Therefore, perhaps the simplest solution would be to implement the following change:

Unfortunately I don't believe that it's this simple, since that still won't catch *all* `@media (prefers-color-scheme: dark) { ... }` instances which means that *part* of the UI won't look correct (e.g. the new alt-text dialog).

Please note that the `_forceCssTheme`-functionality was always a best effort solution, and most likely the CSS-rules that we've started using recently are sufficiently complex that it's difficult to find *all* relevant cases (without a bunch of complicated code).

**Comment by jsanahuja** [comment]
I have tested and the change seems just fine for me. This condition catches exactly the 3 dark media rules: https://github.com/mozilla/pdf.js/blob/f5367f01ca33bbdfb9165850776f7b9de0a65f55/web/app.js#L421-L424
Added `console.log('test', darkRules, rule.cssText);` right after condition:
![image](https://github.com/mozilla/pdf.js/assets/16489902/0fbe3f34-9828-4b59-997d-065b13b759b4)
