### ISSUE TITLE
Read only form field not rendered when AnnotationMode = 1 (ENABLED)

### ISSUE THREAD

**Issue by pavdev64** [mozilla/pdf.js#17064]
`Pdf.js` displays AcroForm text field in all states except one - when the form field is `read-only` and `Pdf.js` `AnnotationMode` is set to `1 (ENABLED)`.

![image](https://github.com/mozilla/pdf.js/assets/131694949/54553cab-f079-47e7-bbe8-9939b6ef126d)

The default `AnnotationMode` is `2 (ENABLED_FORMS)`, so when a pdf with a readonly text field is displayed in Firefox, everything looks ok. However when `AnnotationMode` is set to `1 (ENABLED)`, the text form field is not displayed.

The form field might not be displayed because `isRenderable`  is `false` in `TextWidgetAnnotationElement`.
See: https://github.com/mozilla/pdf.js/blob/59d94b549ff487895f96f1ab0f151ce550e06175/src/display/annotation_layer.js#L1162

`parameters.renderForms` is `false` because `AnnotationMode = 1 (ENABLED)`
`parameters.data.hasAppearance` is `true`
`parameters.data.fieldValue` is `"Foo"`

Because `renderForms` is `false`, the `hasAppearance` property controls whether the widget is renderable.
Why the widget is only renderable if it has a value and not an appearance - is that right?
The widget with the value is rendered if `isRenderable` variable is set to `true`. 

Steps to reproduce:

1. Set AnnotationMode to 1 (ENABLED)
2. Display [simple-form-readonly.pdf](https://github.com/mozilla/pdf.js/files/12793820/simple-form-readonly.pdf)
3. You will see the text field is not rendered. This is not OK.
4. Display [simple-form.pdf](https://github.com/mozilla/pdf.js/files/12793820/simple-form.pdf)
5. You will see the text field is rendered. This is OK.

BTW: see the checkbox tick symbol - why does it look different in both modes?

Configuration:

pdfjs-dist: 3.10.111 build e142baecb

Used forms:

[simple-form.pdf](https://github.com/mozilla/pdf.js/files/12793819/simple-form.pdf)
[simple-form-readonly.pdf](https://github.com/mozilla/pdf.js/files/12793820/simple-form-readonly.pdf)

**Comment by calixteman** [comment]
If I remember correctly, for form elements it makes sense to disable hasOwnCanvas.
For other elements, in the case of FreeText, we use a canvas in order to be able to hide it in case it's edited.
That said I'm fine to disable all the own canvas thing depending on renderForms: I suppose in such case people just want to render an image.
