### ISSUE TITLE
Elements not displayed in demo viewer

### ISSUE THREAD

**Issue by user100582** [mozilla/pdf.js#17069]
Attach (recommended) or Link to PDF file here:
[Testdoc.pdf](https://github.com/mozilla/pdf.js/files/12802422/Testdoc.pdf)

Configuration:
- Web browser and its version: Chrome 117.0.5938.63 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 4.0.10 & 3.11.174
- Is a browser extension: no

Steps to reproduce the problem:
1. go to https://mozilla.github.io/pdf.js/web/viewer.html
2. click on Open File button
3. choose attached pdf

What is the expected behavior? (add screenshot)
comment and sticky note are rendered in viewer 
please note this is working in 2.5.207 PDF.js version:
![image](https://github.com/mozilla/pdf.js/assets/127196044/8bb6f9f9-0508-4335-95de-3bf78dcc4a6e)

What went wrong? (add screenshot)
comment and sticky note are not rendered in viewer
![image](https://github.com/mozilla/pdf.js/assets/127196044/1e9623f1-6657-4bf8-a78a-6ee0a43736fe)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment]
I can reproduce in Firefox nightly.
We aren't rendering some annotations which must be:
https://github.com/mozilla/pdf.js/blob/c377f2d48860ce7c9aba9dbf1f6f4835762c7d77/src/display/annotation_layer.js#L2968

**Comment by user100582** [comment]
Hi @calixteman,

Thank you for resolving this problem! I have tested on Demo site and sticky note appears correctly. 
Comment also appears but is missing component on hover. Here is how it is displayed in 2.5.207 PDF.js version:
![image](https://github.com/mozilla/pdf.js/assets/127196044/57553b3b-3dd1-4c75-b627-b0ebc59d10be)
Any chance you could resolve this or I need to open another issue?
