### ISSUE TITLE
Pattern: applying a transform breaks the pattern

### ISSUE THREAD

**Issue by Dherse** [mozilla/pdf.js#17065]
Attach (recommended) or Link to PDF file here: [test.pdf](https://github.com/mozilla/pdf.js/files/12795741/test.pdf)

Configuration:
- Web browser and its version: Firefox 118.0.1 (64-bit)
- Operating system and its version: Windows 10 22H2 19045.3448
- PDF.js version: 3.10.86 [c72cb5436]
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF in Firefox
2. Compare with a version in Chrome/mupdf

What is the expected behavior? (add screenshot)
It should show four distorted rectangles each with a single contiguous color gradient from red to blue to green to purple (the red part is clipped). The file has been tested in the following viewers: Acrobat, mupdf, evince, XPDF, Chrome, SummatraPDF, and the Apple one and works in all of them.

![image](https://github.com/mozilla/pdf.js/assets/9665250/302d73d0-964d-4fe6-a120-88aad562022d)

What went wrong? (add screenshot)
For the two rectangles on which a skew & rotation is applied, the pattern does not appear:
![image](https://github.com/mozilla/pdf.js/assets/9665250/c7fa5bf8-9f92-4e55-957e-036f26936cdf)

Hope this is complete, thanks in advance,

Dherse :)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

It appears, as far as I can tell, that you forgot to attach the PDF document to this issue.

**Comment by Dherse** [comment]
> It appears, as far as I can tell, that you forgot to attach the PDF document to this issue.

Very sorry, it's there now.

**Comment by Snuffleupagus** [comment]
@calixteman Any ideas what could be wrong here?

**Comment by calixteman** [comment]
Yes, it was a bit uneasy to find out what the issue is, but I found out:
https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L517-L524
We can't only consider the two opposite points to compute the bounding box.

**Comment by Dherse** [comment]
Wow @calixteman I am blown away, thank you so much!
