### ISSUE TITLE
Cannot use the keyboard to "click" on the toolbar buttons when Page Fit is used

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#17071]
This bug is so weird that I wonder if I'm doing something wrong...
That said  here's a STR:
 - open a pdf and set `Page Fit`;
 - with the keyboard, move the focus on a toolbar button, e.g. the freetext one;
 - press Enter key

nothing is happening.
If I change to `Automatic Zoom` then everything is ok.

**Comment by calixteman** [comment]
We should add a specific case when Enter is pressed and the activeElement is a button, link, ...
https://github.com/mozilla/pdf.js/blob/40d6b0e1bf306ef16b4cdcdc093df7cedc2dddad/web/app.js#L2960

**Comment by Snuffleupagus** [comment]
I've not tested it, but it seems that changing
https://github.com/mozilla/pdf.js/blob/40d6b0e1bf306ef16b4cdcdc093df7cedc2dddad/web/app.js#L3254
into something like the following could work
```javascript
((evt.keyCode === 13 || evt.keyCode === 32) && curElementTagName !== "BUTTON")
