### ISSUE TITLE
When the page scaling ratio is less than 100%, there is a problem with the width of the renderText after the text is selected

### ISSUE THREAD

**Issue by yangyusha177** [mozilla/pdf.js#17103]
![img_v2_b59efbb1-125c-4c60-8464-7bcff75704fg](https://github.com/mozilla/pdf.js/assets/40791574/33ae43f8-f6b0-416f-9080-1538f874e2fd)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since nothing more than a screen-shot unfortunately isn't enough to make an issue actionable/valid.

**Comment by yangyusha177** [comment]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- PDF.js version: Many versions，demo link in README
Steps to reproduce the problem:
1. open the [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Adjust the top zoom to below 100%
3. Select a piece of text with your mouse，select area beyond text

What is the expected behavior? (add screenshot)
![img_v2_fc0b2025-3f64-4e92-95cd-795abd85b5dg](https://github.com/mozilla/pdf.js/assets/40791574/1127d081-7b3b-4ec4-b0b5-32e728473724)


What went wrong? (add screenshot)
![img_v2_3e646be1-1c90-4ea6-8929-35ab492df88g](https://github.com/mozilla/pdf.js/assets/40791574/1a4e9eab-8f82-456a-991b-a09ab369c785)
