### ISSUE TITLE
When the page scaling ratio is less than 100%, there is a problem with the width of the renderText after the text is selected

### ISSUE THREAD

**Issue by yangyusha177** [mozilla/pdf.js#17104]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome
- PDF.js version: Many versions，demo link in README
Steps to reproduce the problem:
1. open the [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Adjust the top zoom to below 100%
3. Select a piece of text with your mouse，select area beyond text

What is the expected behavior? (add screenshot)
![img_v2_fc0b2025-3f64-4e92-95cd-795abd85b5dg](https://github.com/mozilla/pdf.js/assets/40791574/1127d081-7b3b-4ec4-b0b5-32e728473724)

What went wrong? (add screenshot)
![img_v2_b59efbb1-125c-4c60-8464-7bcff75704fg](https://github.com/mozilla/pdf.js/assets/40791574/33ae43f8-f6b0-416f-9080-1538f874e2fd)

**Comment by Snuffleupagus** [comment]
> Configuration:
> Web browser and its version: chrome
> PDF.js version: Many versions，demo link in README

You haven't stated which Google Chrome *version* you use, despite that being asked, and you've also not included the `Operating system and its version:`-part of the ISSUE_TEMPLATE.

---

WFM, when testing https://mozilla.github.io/pdf.js/web/viewer.html in both Firefox Nightly 120.0a1 *and* Google Chrome Beta 119.0.6045.9 on Windows 11; see screen-shots below.
Most likely there's *something* strange about your environment that triggers this, e.g. related to installed fonts, however given that this doesn't reproduce for all users it seems difficult to address here. Furthermore, please note that the *built-in* Firefox PDF Viewer is the primary development target for this library.

 
 - Firefox
   ![firefox](https://github.com/mozilla/pdf.js/assets/2692120/454034b9-91a4-42ac-a99a-4a4d9c44a889)

 - Chrome
   ![chrome](https://github.com/mozilla/pdf.js/assets/2692120/bbb9c1fc-1608-4605-bc3a-ce4f7fee0717)

**Comment by yangyusha177** [comment]
chrome has this problem with version 117.0.5938.150
