### ISSUE TITLE
PDF files are garbled when using Firefox built-in PDF viewer

### ISSUE THREAD

**Issue by ArnieO** [mozilla/pdf.js#17109]
This problem seems to have appeared in one of the latest Firefox versions, it started a few days ago.

Attach (recommended) or Link to PDF file here: https://s1.q4cdn.com/806093406/files/doc_downloads/test.pdf

Configuration:
- Web browser and its version:
![image](https://github.com/mozilla/pdf.js/assets/10295178/68d248c9-6248-4024-bc1e-83a10cfad218)
- Operating system and its version: **Windows 11**
- PDF.js version: **No idea, I'm using the built-in PDF viewer**
- Is a browser extension: **No**

Steps to reproduce the problem:
1. Download the test file linked above
2. Open in Firefox

What is the expected behavior?
It should look like this (opened in Adobe Acrobat):
![image](https://github.com/mozilla/pdf.js/assets/10295178/2277a0d7-e41d-40d6-859e-d7df5d691502)

What went wrong? (add screenshot)
It looks like this in Firefox:
![image](https://github.com/mozilla/pdf.js/assets/10295178/7aa6de61-136f-4cb4-ba80-24d85eb06442)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is, most likely, a duplicate of [bug 1854090](https://bugzilla.mozilla.org/show_bug.cgi?id=1854090) and/or [bug 1857015](https://bugzilla.mozilla.org/show_bug.cgi?id=1857015).

**Comment by ArnieO** [comment]
Yes, it is the same.
