### ISSUE TITLE
Fix new code scanning alerts

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#17118]
The following new code scanning alerts showed up recently:

- https://github.com/mozilla/pdf.js/security/code-scanning/402
- https://github.com/mozilla/pdf.js/security/code-scanning/401
- https://github.com/mozilla/pdf.js/security/code-scanning/400
- https://github.com/mozilla/pdf.js/security/code-scanning/399
- https://github.com/mozilla/pdf.js/security/code-scanning/398

There is a note in there that this is debugging code code, and it's indeed not called from anywhere. It has also mostly been changed 12 years ago.

@Snuffleupagus What do you think? Should we get rid of it, or is this something you have used or think is useful to keep? In the latter case we can just silence the alert.

**Comment by Snuffleupagus** [comment]
Personally I've never once used either https://github.com/mozilla/pdf.js/blob/master/src/shared/cffStandardStrings.js or https://github.com/mozilla/pdf.js/blob/master/src/shared/fonts_utils.js
Given that none of them import/export things properly, and rely on everything being *global*, this code also wouldn't run without a bunch of re-writing first; hence it's probably safe to assume that those files haven't been used for many years. Also, looking at the [`writeToFile` function](https://github.com/mozilla/pdf.js/blob/23b8dbb7308ffdb46d3ff5602eaf8b178b8bdd58/src/shared/fonts_utils.js#L402-L429) it seems to rely on access to platform code (in Firefox itself) that might not even exist anymore.

So, in closing, we can probably just remove those two old files and get rid of the alerts that way.

**Comment by timvandermeij** [comment]
Thanks for the feedback; I'll prepare a PR soon then.
