### ISSUE TITLE
Help: Max serverless function size of 50 MB compressed or 250 MB uncompressed reached

### ISSUE THREAD

**Issue by meness** [mozilla/pdf.js#17111]
Configuration:
- PDF.js version: 3.11.174

What is the expected behavior?
I used `getDocument`, `isPdfFile`, and `TextItem` only from `pdfjs-dist`.

What went wrong?
I get this warning on Vercel. The solution is to lazy load it, but I don't know how to lazy load functions. I use pdf.js to extract content from PDF only.
```
Warning: Max serverless function size of 50 MB compressed or 250 MB uncompressed reached
--
Serverless Function's page: 404.js
Large Dependencies              Uncompressed size  Compressed size
node_modules/canvas/build               178.98 MB         45.74 MB
node_modules/next/dist                    9.02 MB          2.55 MB
node_modules/pdfjs-dist/build             2.43 MB        476.76 KB
```

**Comment by timvandermeij** [comment]
We don't know about Vercel, nor can we provide support for it. Most of the size doesn't come from PDF.js itself but rather from the `canvas` library which is even an optional dependency for PDF.js; see https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs#L2126-L2127.
