### ISSUE TITLE
How to search multiple phrases simultaneously?

### ISSUE THREAD

**Issue by noki98** [mozilla/pdf.js#17129]
As I see issue #16247 fixes searching for multiple phrases. How do i search for multiple phrases? Through URL?

**Comment by Snuffleupagus** [comment]
> How do i search for multiple phrases?

By providing a `query`-parameter containing an Array of strings, e.g. `["Lorem ipsum", "foo bar"]`.

> Through URL?

That's not supported.

**Comment by noki98** [comment]
And where can I provide such query?
