### ISSUE TITLE
The document bytes are not retrieved properly after upgrading the pdf.js to 

### ISSUE THREAD

**Issue by deepika134** [mozilla/pdf.js#17158]
Attach (recommended) or Link to PDF file here:
Attached the PDF file in sample and the issue replicated from this PDF.js version 3.3.122.

Configuration:
- Web browser and its version:  Chrome- Version 118.0.5993.89 
- Operating system and its version: Windows 11 Enterprise - 22H2
- PDF.js version: 3.11.174

Steps to reproduce the problem:
1. Please run the attached sample in a web browser.
2. Click on the button in the output screen.
3. In the console, you may notice that the byte length is not being retrieved properly.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/87310214/8a826cb0-a611-49bf-b921-3ddb1f9fe675)
What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/87310214/701a1f5d-8caf-4272-b876-622ca082abba)
[flutter_pdf_app.zip](https://github.com/mozilla/pdf.js/files/13070030/flutter_pdf_app.zip)

**Comment by Snuffleupagus** [comment]
> Please run the attached sample in a web browser.

How?
Unless you're previously familiar with "Flutter", this unfortunately isn't really easily actionable.

Please note that we specifically ask for *a link to a directly runnable code*, since nothing more than an archive with a bunch of source-code (using some framework) makes it really difficult to help; note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by deepika134** [comment]
Hi @Snuffleupagus ,

Thanks for the quick response .

We are experiencing an issue while using PDF.js with Flutter.
