### ISSUE TITLE
Support for Displaying Image Stamps in Signed PDFs

### ISSUE THREAD

**Issue by akippiko** [mozilla/pdf.js#17169]
## Attach (recommended) or Link to PDF file here:
[stamp-signature.pdf](https://github.com/mozilla/pdf.js/files/13161366/stamp-signature.pdf)

## Configuration:
- Web browser and its version: Chrome 19.0.0
- Operating system and its version: Windows10
- PDF.js version: 3.4.120
- Is a browser extension:

## Steps to reproduce the problem:
1. Open the attached/linked PDF file using PDF.js.
2. Navigate to the page with the electronic stamp.

## What is the expected behavior? (add screenshot)

The electronic stamp should be displayed correctly on the signed PDF document.

## What went wrong? (add screenshot)

The electronic stamp is not rendering/displaying correctly.

## Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): 

Cannot provide

**Comment by calixteman** [comment]
The signature annotations have the flag INVISIBLE (0x1) and according to the specs:
```
If set, do not display the annotation if it does not belong to one of the
standard annotation types and no annotation handler is available. If
clear, display such an unknown annotation using an appearance
stream specified by its appearance dictionary, if any (see 12.5.5,
“Appearance Streams”).
```
so we should make them visible since they belong to one of the standard annotation type.
