### ISSUE TITLE
Split single page into multiple objects

### ISSUE THREAD

**Issue by nuthinking** [mozilla/pdf.js#17160]
I would need to spit a single page pdf in as many "layers" as possible. The problem is that the pdfs I need to split don't seem to have any optional content, if I drag them into the [viewer](https://mozilla.github.io/pdf.js/web/viewer.html) the layers tab is disabled. Is there a way to access the list of rendered objects and, for instance, remove one before the rendering? An example could be to separate text from a background picture. Thanks! 🙏

**Comment by Snuffleupagus** [comment]
It sounds like you're basically asking for *arbitrary* PDF editing, which is not really what the PDF.js library is created/intended for; hence this is unfortunately not supported here.
Please note that the first sentence [of the README](https://github.com/mozilla/pdf.js#pdfjs-) states: `PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.`

> Is there a way to access the list of rendered objects and, for instance, remove one before the rendering?

You might be able to hack the `operatorList` into skipping certain operators, see e.g. https://github.com/mozilla/pdf.js/blob/377af6892b6c9e22a5fc545dfd454ad73f411990/src/display/api.js#L1769-L1789 however this isn't something that we can officially support.
