### ISSUE TITLE
PDF Page numbers in wrong order

### ISSUE THREAD

**Issue by catabozan** [mozilla/pdf.js#17162]
Attach (recommended) or Link to PDF file here: 
[1-Electrostatique.pdf](https://github.com/mozilla/pdf.js/files/13114193/1-Electrostatique.pdf)

Configuration:
- Web browser and its version: Firefox 118.0.2 (64-bit)
- Operating system and its version: 
- PDF.js version: Firefox Builtin PDF viewer
- Is a browser extension: no

(https://drive.google.com/file/d/1DDaa6x4MFxBwwDtxh_F3ZBtgmiDyxFYQ/view?usp=sharing)
Steps to reproduce the problem:
1.  Open a PDF with Firefox built-in viewer that has some pages with numbers, and other pages that do not have a set page number.
2. Scroll between pages that have a number set and other that do not have it.

What is the expected behavior? (add screenshot)
Displayed page number in the top left corner should be in ascending order while scrolling: page 1, 2, 3, ... 43, 44, ...
![image](https://github.com/mozilla/pdf.js/assets/43291246/1a198809-825d-4446-8c4b-6a11e9fabd0f)

What went wrong? (add screenshot)
The pages are not counted correctly. If a page has a set page number, that number is shown. If another page does not have a set number, the order of the pages is thrown off.
When a page number is set:
![image](https://github.com/mozilla/pdf.js/assets/43291246/2ec7cbeb-d1ba-414d-8ff7-30863baf2144)

When a page number is not set(page after the one showed above):
![image](https://github.com/mozilla/pdf.js/assets/43291246/008aa44b-77f1-4d7c-820f-9de12d34e2d2)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is a bug in the /PageLabels dictionary of the PDF document *itself*, and the same behaviour can be observed in e.g. Adobe Reader (i.e. the PDF reference implementation) as well.

**Comment by catabozan** [comment]
Ok, thank you for the response!
