### ISSUE TITLE
Something I missed?

### ISSUE THREAD

**Issue by MrZhongzq** [mozilla/pdf.js#17179]
Attach (recommended) or Link to PDF file here: Sorry, private files. but it is good file with 200 status.
<img width="608" alt="image" src="https://github.com/mozilla/pdf.js/assets/108169409/233024f0-72cd-48be-8fab-e56f46f3df34">

Configuration:
- Web browser and its version: Google chrome 118.0.5993.117
- Operating system and its version: pdf.js on ubuntu 22.04, visit it on Mac 13.4.1
- PDF.js version:3.11.174
- Is a browser extension:

Steps to reproduce the problem:
1. visit my website with ?file=xxxx
2.done, nothing happened

What is the expected behavior? (add screenshot)
    load the pdf
What went wrong? (add screenshot)
   pdf doesn't show
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):https://pdf.zzqhmbb.eu.org/web/viewer.html

**Comment by MrZhongzq** [comment]
Overall, I can't load any file on it now. I am using the release package.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: Sorry, private files. but it is good file with 200 status.

If you don't provide a *full* example, including the PDF document in question, it's unfortunately not possible to help you.

> visit my website with ?file=xxxx

Again, you'll need to provide the *full URL* here in order for anyone to be able to assist.

---

The only *guess* would be that you're either running into the following checks, in which case you'll need to extend the `HOSTED_VIEWER_ORIGINS` list, https://github.com/mozilla/pdf.js/blob/fbfacf8828eddd0c458a330f162c5a3f7f5dc948/web/app.js#L2204-L2233 or it could possible a CORS issue https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr
