### ISSUE TITLE
Some characters are not rendered

### ISSUE THREAD

**Issue by yxc666** [mozilla/pdf.js#17182]
Attach (recommended) or Link to PDF file here: Can be reproduced on the demo page:
https://mozilla.github.io/pdf.js/web/viewer.html
[record.pdf](https://github.com/mozilla/pdf.js/files/13175024/record2.pdf)
Configuration:
- Web browser and its version: chrome 118.0.5993.89
- Operating system and its version: win11 22000.556
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached pdf on the demo page

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/29443555/d7b90566-733a-4361-ae6b-d80203d785f9)
What went wrong? (add screenshot)
Some text is not displayed：
![image](https://github.com/mozilla/pdf.js/assets/29443555/f7f1a65c-5977-4076-b37c-5c314b7b4396)

**Comment by Snuffleupagus** [comment]
This is similarly broken in Adobe Reader (i.e. the PDF reference implementation) as well, and there's even a warning message about a broken font, hence this is clearly an issue with the PDF document *itself*.

![image](https://github.com/mozilla/pdf.js/assets/2692120/546b6645-7d7e-4e3e-a7ce-a0845f0e7d7f)
