### ISSUE TITLE
Highlight the text in the pdf is not working

### ISSUE THREAD

**Issue by ChandraBahavathi** [mozilla/pdf.js#17183]
Attach (recommended) or Link to PDF file here:
[0a83d06d-27b1-4800-afb3-a108f302a0c3_processed.pdf](https://github.com/mozilla/pdf.js/files/13175442/0a83d06d-27b1-4800-afb3-a108f302a0c3_processed.pdf)

Configuration:
- Web browser and its version:Chrome
- Operating system and its version:Windows 10
- PDF.js version:V3.11.174
- Is a browser extension:No

Steps to reproduce the problem:
1. Go to pdf.js viewer https://mozilla.github.io/pdf.js/web/viewer.html
2.Open the attached file 

What is the expected behavior? (add screenshot)
I want too search the text and highlighted it in the pdf 
What went wrong? (add screenshot)
![Screenshot (127)](https://github.com/mozilla/pdf.js/assets/111121349/bfdd80d5-0b95-4052-8de0-6cd9f35c3f4c)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
No

**Comment by Snuffleupagus** [comment]
> I want too search the text and highlighted it in the pdf

That works fine when opening your PDF document with https://mozilla.github.io/pdf.js/web/viewer.html

> What went wrong? (add screenshot)

Your screen-shot shows some kind of custom solution, that we know nothing about.
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
