### ISSUE TITLE
PDFJS renders a blank canvas in node environment, if scale >= 9.49

### ISSUE THREAD

**Issue by soadzoor** [mozilla/pdf.js#17188]
Attach (recommended) or Link to PDF file here:
[c53a656b-551d-4c24-bfb6-f994ef3a6d4b.pdf](https://github.com/mozilla/pdf.js/files/13179307/c53a656b-551d-4c24-bfb6-f994ef3a6d4b.pdf)

Configuration:
- Web browser and its version: It works fine in web-browser environments
- Operating system and its version: Ubuntu 22.04.2 LTS, node v18.15.0
- PDF.js version: 3.11.174
- Is a browser extension: no

Steps to reproduce the problem:
1. I've made a minimalistic repo to replicate the problem. Clone this https://github.com/soadzoor/node-pdfjs
2. `npm install`
3. `node index.js`
4. Note that a PNG is getting generated with a section from the PDF (`FloorplanSection.png`)
5. Now modify the viewport within `index.js` (replace the `scale` value with a number above `9.49`, or simply uncomment the section from line 31 to 36)
6. **Note that the generated PNG (`FloorplanSection.png`) is blank now, it contains only white pixels, but it shouldn't.**
7. If I run the same exact code (meaning, same PDF, same viewportsettings, etc., only the rendering method is different, because node.js doesn't have a built-in renderer and/or canvas) in a web-browser environment, the PDF section gets rendered properly. Here's the web-browser version: https://jsfiddle.net/rwdysagu/ , scroll down to the bottom for the code, the base64 data is kind of huge.

What is the expected behavior? (add screenshot)
PDF.js should work the same within node.js, and a web-browser

What went wrong? (add screenshot)
On the node.js version, PDF.js renders a blank image, while the web-browser renders a visible section from the PDF.
They both use the same PDF, and the same exact settings, viewport, etc:
![Screenshot 2023-10-26 172204](https://github.com/mozilla/pdf.js/assets/10392261/0a323c2a-acf1-42ee-8ada-d1df8361a52f)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Render is blank if run from node.js: https://github.com/soadzoor/node-pdfjs
Same thing works fine within a web-browser: https://jsfiddle.net/rwdysagu/

Note, that it works as expected until you change the scale on the node.js version to be above 9.49. Any value lower than that gives you the same exact image as the web-browser version (if everything else is the same, of course).

**Comment by Snuffleupagus** [comment]
In Node.js we rely on the `node-canvas` package for rendering, see https://github.com/Automattic/node-canvas
Hence if this is limited to Node.js that sounds like a bug in that package, rather than in the PDF.js library. (Note also that Firefox is the *primary* development target here.)

**Comment by soadzoor** [comment]
For the record:
Since `node-canvas` was replaced with `@napi-rs/canvas`, this problem seems to be solved!

Also, for the record, there are some minor differences in rendering output between the 2 canvas implementations. Here's an example:
`node-canvas`:
![node-canvas_FloorplanSection](https://github.com/user-attachments/assets/5666e93f-d3b2-4ffe-8957-e26a1a657ff2)
`@napi-rs/canvas`:
![napi-rs-canvas_FloorplanSection](https://github.com/user-attachments/assets/c1cfec9d-29f6-4fc7-b38e-93cd8eac564b)


You can see the slight differences if you open up both of these in a new tabs, and switch between the tabs.

I couldn't see which one is _"better"_, but they're a bit different for sure.
