### ISSUE TITLE
Cannot find name 'WeakKey'.

### ISSUE THREAD

**Issue by joutvhu** [mozilla/pdf.js#17197]
```log
Error: node_modules/pdfjs-dist/types/web/text_layer_builder.d.ts:41:32 - error TS2304: Cannot find name 'WeakKey'.
41     textDivProperties: WeakMap<WeakKey, any>;
```

Configuration:
- Package: pdfjs-dist
- PDF.js version: 3.11.174

**Comment by Snuffleupagus** [comment]
Given that overall lack of actionable details, with e.g. no runnable example code provided, my guess is that this is simply caused by an old (and outdated) version of TypeScript.

**Comment by ineiti** [comment]
@joutvhu please provide a minimal example that shows the failure.

**Comment by shamoon** [comment]
FWIW, I have the same issue, not so simple to create a minimal example because for me its in the context of an angular app, which because of angular's requirements is stuck on Typescript < 5.2.0 (so Im not certain if upgrading beyond that fixes it).

At this point I'd be happy with a workaround, if possible.

**Comment by ineiti** [comment]
@shamoon can you try if a simple example with your typescript version also fails in the same way?

**Comment by shamoon** [comment]
Yes, in my case as soon as I add any import from 'pdfjs-dist/web/pdf_viewer' I get this.

Sorry for not saying before, but for reference, I'm using:
- typescript: 5.1.6
- @angular/cli: 16.2.9
- pdfjs-dist: 3.11.174

I'm a little ashamed to even post it here (no judgements! 😜), but this nasty hack does allow the build to succeed:
```ts
declare global {
  interface WeakKeyTypes {
    symbol: Object
  }

  type WeakKey = WeakKeyTypes[keyof WeakKeyTypes]
}
```

**Comment by shamoon** [comment]
Edit: I think its the import of EventBus, if thats relevant

**Comment by rbalet** [comment]
@shamoon I do get `Duplicate identifier 'WeakKey' when I try to use your workaround.

Did you did something special ?

**Comment by shamoon** [comment]
Sorry I cant help more, Im no longer using that workaround
