### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype') var DOMExceptionPrototype = $DOMException.prototype = NativeDOMException.prototype (node_modules/pdfjs-dist/legacy/build/pdf.js:5863))

### ISSUE THREAD

**Issue by AnoopFranc** [mozilla/pdf.js#17207]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: No web browser it's an express app
- Operating system and its version: macOS version 14.0
- PDF.js version:    "pdfjs-dist": "^3.11.174"
- Is a browser extension: No

What is the expected behavior? (add screenshot)
I was trying to create a pdf to image function in my express app using canvas and pdfjs based on the example provided : https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.mjs
but when I start the server it throws, 

/Users/anoop/code/demo-solutions/document-sign/docu-sign-server-sol/node_modules/pdfjs-dist/legacy/build/pdf.js:5863
var DOMExceptionPrototype = $DOMException.prototype = NativeDOMException.prototype;
                                                                         ^

here is the code that is supposed to create a pdf to image for me

```js
const PDFJS = require('pdfjs-dist/legacy/build/pdf.js');
const { fromBuffer } = require('pdf2pic');
const { uploadFIle } = require('./file_storage');
const NodeCanvasFactory = require("./canvas_factory_service");
PROCESS_DOC_CONFIG = {
    format: 'png',
};

const CMAP_URL = "../../../node_modules/pdfjs-dist/cmaps/";
const CMAP_PACKED = true;

// Where the standard fonts are located.
const STANDARD_FONT_DATA_URL =
    "../../../node_modules/pdfjs-dist/standard_fonts/";

module.exports.createPdfPreviewFromFile = async (attachment, filePath) => {
    // Get the number of pages in the PDF.
    const pdf = await PDFDocument.load(attachment);
    const canvasFactory = new NodeCanvasFactory();
    const _pdf = PDFJS.getDocument({
        data: bufferToUint8Array(attachment), cMapUrl: CMAP_URL,
        cMapPacked: CMAP_PACKED,
        standardFontDataUrl: STANDARD_FONT_DATA_URL, canvasFactory
    });
    const pdfDocument = await _pdf.promise;
    const numberOfPages = pdf.getPageCount();
    const previewImages = []
    // Generate preview images for up to MAX_NUMBER_OF_PAGES_PROCESSED pages
    for (let pageNumber = 0; pageNumber < numberOfPages; pageNumber++) {
        // Create a Vips image object from the PDF page

        // const pdfPage = pdf.getPage(pageNumber);
        const _pdfPage = await pdfDocument.getPage(pageNumber + 1);
        // Render the page on a Node canvas with 100% scale.
        const viewport = _pdfPage.getViewport({ scale: 1.0 });
        const ctx = canvasFactory.create(viewport.width, viewport.height);
        const renderTask = _pdfPage.render({ canvasContext: ctx.context, viewport });
        await renderTask.promise;
        // Convert the canvas to an image buffer.
        const image = ctx.canvas.toBuffer();
        // const page = await sharp(pageOutput.buffer, { density: PROCESS_DOC_CONFIG.DPI });

        // // Resize the image
        // const image_metadata = await page.metadata();
        // page.resize(PROCESS_DOC_CONFIG.MAX_WIDTH / image_metadata.width || PROCESS_DOC_CONFIG.MAX_WIDTH);

        // // Resize the image
        // const buffer = await page.toBuffer();
        const pageFilePath = `${filePath}/${pageNumber}.png`;
        await uploadFIle(image, pageFilePath);
        previewImages.push(pageFilePath);
        canvasFactory.destroy(ctx.context);
    }
    return previewImages;
}

function bufferToUint8Array(buffer) {
    const arrayBuffer = new ArrayBuffer(buffer.length);
    const uint8Array = new Uint8Array(arrayBuffer);
    buffer.copy(uint8Array);
    return uint8Array;
}
```

What went wrong? (add screenshot)

<img width="1080" alt="Screenshot 2023-10-31 at 7 04 01 AM" src="https://github.com/mozilla/pdf.js/assets/52399978/c8c41f82-3232-475a-80f1-f6c8c243e796">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by AnoopFranc** [comment]
It seems like it was a node version issue
node v18.16.0 issue solved it

**Comment by Snuffleupagus** [comment]
> Web browser and its version: No web browser it's an express app

Please note that that's not a configuration that we know anything about, and that we simply cannot support the myriad of frameworks that exist.

> I was using node v16.20.0 but changing it to node v18.16.0 issue solved it

Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
