### ISSUE TITLE
PDF first page is displaying as blank in Safari browser

### ISSUE THREAD

**Issue by rajacsharp** [mozilla/pdf.js#17210]
PDF first page is displaying as blank in Safari **browser**

PDF first page is displaying as blank in Safari browser.
Configuration:
- Web browser and its version: Safari Browser version : Safari Browser version 16.1
- Operating system and its version: Apple macOS 10.14 (
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. Open any PDF or PDF.js Demo in safari browser 
2.First page is displayed as blank

What is the expected behavior? (add screenshot)
First page should display the content 
What went wrong? (add screenshot)
 
![image](https://github.com/mozilla/pdf.js/assets/58780677/cdcf10f1-0a52-4bbe-9082-f3c44f597bcb)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version:

The part of the ISSUE_TEMPLATE must always be provided.

> Steps to reproduce the problem:
>    1. Open any PDF or PDF.js Demo in safari browser
>    2. First page is displayed as blank

If this is specific to just *one browser*, that unfortunately suggest a browser-specific bug (since otherwise you'd expect it to be consistently broken everywhere); please report this to the Safari-developers instead.
