### ISSUE TITLE
Error during font loading: Font Helv is not available

### ISSUE THREAD

**Issue by ValerioMarsala** [mozilla/pdf.js#17211]
Configuration:
- Web browser and its version:  Chrome 118.0.5993.118
- Operating system and its version: Windows 10
- PDF.js version: "pdfjs-dist": "2.7.570"
- Is a browser extension: no

Steps to reproduce the problem:
1.  Upload the pdf
2. Render it with pdf.js library in a more or less 80% scaled window.

What is the expected behavior? We expect a clear and readable render of the fonts in the pdf, without graphic glitches.

What went wrong? The fonts are blurry and not very readable. 
On console we receive the following error: `Warning: Error during font loading: Font Helv is not available`.
The pdf has some fonts that are not embedded, so we came at the conclusion that this could be the problem.

Can a version update or any known workaround fix this problem?

Thanks

**Comment by Snuffleupagus** [comment]
> PDF.js version: "pdfjs-dist": "2.7.570"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Upload the pdf

Unfortunately you've left out the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE, which is the single most important piece of information that you always need to provide when opening an issue.

> Can a version update or any known workaround fix this problem?

Maybe, but given the lack of information (see above) we cannot really provide any assistance here.
