### ISSUE TITLE
pdf_viewer broken in 4.0.189 when using Webpack

### ISSUE THREAD

**Issue by code-elf** [mozilla/pdf.js#17228]
Attach (recommended) or Link to PDF file here: No PDF needed; the viewer does not load properly.

Configuration:
- Web browser and its version: Chrome 119.0.6045.105
- Operating system and its version: Linux (Nobara 38)
- PDF.js version: 4.0.189
- Is a browser extension: No

It seems that https://github.com/mozilla/pdf.js/commit/927e50f5d48a67e76f2a51c112ea5a98867822fe broke `pdf_viewer`'s usage of `pdfjsLib` when using Webpack. Previously, it was possible to use it like this:
```js
import * as pdfjs from "pdfjs-dist/legacy/build/pdf";
import { EventBus, PDFLinkService, PDFSinglePageViewer } from "pdfjs-dist/legacy/web/pdf_viewer";
```
However, this now breaks as `pdf.mjs` now contains `__webpack_exports__ = globalThis.pdfjsLib = await __webpack_exports__;`. This means that when the `pdf_viewer` code executes, `pdfjsLib` is not set yet.

Please let me know if I'm missing anything, but I believe this is a regression in the library, as I wasn't able to find a way to use `pdf_viewer` with Webpack now.

**Comment by ENDsoft233** [comment]
`import * as pdfjs` means setting a alias for imported dependencies, so whether pdfjsLibs exported, whatever your alias set, it won't making any error. So, any error logs provided?

**Comment by mashirozx** [comment]
same issue, we are using the old cjs module, and mjs results in errors in our projects!

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mashirozx** [comment]
This is the latest npm package (v4):
<img width="825" alt="image" src="https://github.com/mozilla/pdf.js/assets/16148054/83a1be68-9cf1-4eb3-8a79-6d1466577fdc">
And this is the last version (v3):
<img width="816" alt="image" src="https://github.com/mozilla/pdf.js/assets/16148054/50c45363-3795-414f-a7d2-8ff3d27210ff">
we can see that v4 only provide mjs build, and this will not be compatible with a lot of old project, that's all the information i think

**Comment by mashirozx** [comment]
This is the latest npm package (v4):
<img width="825" alt="image" src="https://github.com/mozilla/pdf.js/assets/16148054/83a1be68-9cf1-4eb3-8a79-6d1466577fdc">
And this is the last version (v3):
<img width="816" alt="image" src="https://github.com/mozilla/pdf.js/assets/16148054/50c45363-3795-414f-a7d2-8ff3d27210ff">
we can see that v4 only provide mjs build, and this will not be compatible with a lot of old projects and old browsers! we need to use the lib's CDN resources, which was stated in the documentation:
<img width="1571" alt="image" src="https://github.com/mozilla/pdf.js/assets/16148054/96badd06-2923-41f7-9707-3bfa456fe86e">

**Comment by mashirozx** [comment]
interesting, is this a place to discuss and feedback? why was my detailed description deleted?

**Comment by mashirozx** [comment]
funny, are you a bot? so interesting

**Comment by ghenry** [comment]
Just trying out v4 in a new project and getting:

```
[watch] build started (change: "js/pdf_preview/index.js")
✘ [ERROR] Top-level await is currently not supported with the "iife" output format

    node_modules/pdfjs-dist/build/pdf.mjs:16837:53:
      16837 │ ...ck_exports__ = globalThis.pdfjsLib = await __webpack_exports__;
            ╵                                         ~~~~~
```

See https://elixirforum.com/t/importing-pdf-mjs-into-app-js/59578

**Comment by Snuffleupagus** [comment]
Please keep in mind that *this issue* is specifically about the problem outlined in https://github.com/mozilla/pdf.js/issues/17228#issue-1980128178, rather than a general discussion for any and all problems related to PDF.js version `4.0`.

Please refer *other problems* with PDF. js `4.0` to their own discussions or issues, such that we avoid a situation where different things are covered in the same issue (since that makes tracking much more difficult).

**Comment by code-elf** [comment]
> Would it work if you do e.g. const pdfjs = await import("pdfjs-dist/legacy/build/pdf"); instead?

Yes, that seems to work in our case. I think that this is still an issue in some cases as it breaks bundling and I assume not everyone will be able to use the async import syntax, so will keep this open for the moment. Still, thank you!

**Comment by timvandermeij** [comment]
Could you perhaps test the possible fix in https://github.com/mozilla/pdf.js/pull/17255 to see if it solves the issue here?

**Comment by jameshalsall** [comment]
@timvandermeij this is should be kept open, this doesn't really work unless you import inside of an async function...

**Comment by Snuffleupagus** [comment]
> this should be kept open, this doesn't really work unless you import inside of an async function...

A patch landed in PR #17255, and it's unfortunately not entirely clear what more/else we can really do here; hence re-opening this issue doesn't seem meaningful as-is.
Furthermore, you should be able to import at the top level (outside of any function) since all browsers/environments that we currently support have implemented top level await.

**Comment by jameshalsall** [comment]
Appreciate that 👍🏻  although I'm seeing Jest at least **not** working when importing `pdfjs-dist` - it could be a problem there rather than anything wrong with what you've done, apologies.

**Comment by pavdev64** [comment]
I'm seeing that as well. Jest fails on:
```
SyntaxError: await is only valid in async functions and the top level bodies of modules
```
and the await in the top level body requires ES2022 - the newest mobile phone browsers.

**Comment by pavdev64** [comment]
With the last version of pdf.js 4.0.269, is it still needed to use the top level await or the intention was to eliminate the await?
```
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf';
const { PDFViewer } = await import('pdfjs-dist/legacy/web/pdf_viewer');
```
because I tried  
```
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf';
import { PDFViewer } from 'pdfjs-dist/legacy/web/pdf_viewer';
```

and it fails on undefined [globalThis.pdfjsLib](https://github.com/mozilla/pdf.js/blob/9ac1ac6ed3be13183746c465d9183df1181eabb7/web/pdfjs.js#L71).

This line is preceded by [await globalThis.pdfjsLibPromise](https://github.com/mozilla/pdf.js/blob/9ac1ac6ed3be13183746c465d9183df1181eabb7/web/pdfjs.js#L22), which I think should wait for pdfjsLib to load, but [globalThis.pdfjsLib](https://github.com/mozilla/pdf.js/blob/9ac1ac6ed3be13183746c465d9183df1181eabb7/web/pdfjs.js#L71) remains undefined.

**Comment by wojtekmaj** [comment]
I would also like to chime in and share my concern with top-level await being used here. This for a bizzare reason makes PDF.js non-functional in Vite, which I consider a blocker for upgrading PDF.js in React-PDF.

**Comment by kofifus** [comment]
Had a lot of drama with this, ended up adding `window.pdfjsLib = globalThis.pdfjsLib` to the botom of `pdf.mjs`
