### ISSUE TITLE
how to extract the catalogue？

### ISSUE THREAD

**Issue by LMchensir** [mozilla/pdf.js#17230]
I want to extract catalogue, not outline，I know there is a function that can extract the outline, but I couldn't find the function to extract the catalogue。

**Comment by Snuffleupagus** [comment]
What do you actually mean by "catalogue"? A link to the relevant section of the PDF specification would be helpful here, since this issue is a bit too light on actionable details.

If you're referring to the /Catalog object in a PDF document then that's a lower-level object that we cannot expose directly, given its contents and that all parsing is done in a worker-thread.

**Comment by LMchensir** [comment]
> What do you actually mean by "catalogue"? A link to the relevant section of the PDF specification would be helpful here, since this issue is a bit too light on actionable details.
> 
> If you're referring to the /Catalog object in a PDF document then that's a lower-level structure that we cannot expose directly, given its contents and that all parsing is done in a worker-thread.

I'm very sorry that I didn't clarify my question clearly in my first inquiry.

I made a simple GIF to illustrate my problem.

![pdf](https://github.com/mozilla/pdf.js/assets/51938074/9b17110b-e50d-4196-bf94-ceebf4a2b66b)

What I mean is this kind of directory. I'm not sure if you provide an API function to obtain such a directory and implement the functionality to navigate to the corresponding location upon clicking?

Could you please let me know if you have the corresponding API function? Ideally, I apologize for my poor English.

**Comment by Snuffleupagus** [comment]
*Even looking at your GIF, it's unfortunately not entirely clear __exactly__ what you mean.*

If you're referring to a "table of contents" found within the pages of a specific PDF document, that's just a a bunch of text with *separate* LinkAnnotations and not actually a data-structure defined in the PDF specification.
Exactly how this is implemented in an individual PDF document usually varies a fair bit, and there's consequently no way to (easily) access such data unfortunately.
