### ISSUE TITLE
Form annotation not shown because of UnknownErrorException

### ISSUE THREAD

**Issue by MasterATM** [mozilla/pdf.js#17232]
Hello,
When I upload the pdf in attachment, it fails to show the form annotation.
Could you please help?

Additional info: the original files comes from https://www.overzeesesocialezekerheid.be/nl/documenten/aanvraag-beeindiging-aansluiting.pdf
I have opened the original pdf with the default pdf tool (Preview) in MacOS, selected and deleted the signature field.
Thanks!

Attach (recommended) or Link to PDF file here:
This is the file where the signature field has been deleted.
[aanvraag-beeindiging-aansluiting.pdf](https://github.com/mozilla/pdf.js/files/13280636/aanvraag-beeindiging-aansluiting.pdf)

Configuration:
- Web browser and its version: Chrome Version 118.0.5993.118 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise 21H2
- PDF.js version: 4.0.191 [72338ce05]
- Is a browser extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the file in attachment.

What is the expected behavior? 
If we open the pdf in Foxit or Adobe Reader, the first field shows "my own name"
![2023-11-07_14h52_45](https://github.com/mozilla/pdf.js/assets/13003523/7054445d-617d-4014-90cb-eab4f0bc0af4)

What went wrong? 
![2023-11-07_14h54_27](https://github.com/mozilla/pdf.js/assets/13003523/4b7052b1-fa9f-4096-840c-783e354c08f0)

The file is shown but there are no annotation in the form. Moreover, an exception is thrown in the console.

**Comment by calixteman** [comment]
The `Fields` array in the `Acroform` dictionary contains a reference to a nonexistent field and then we throw:
https://github.com/mozilla/pdf.js/blob/72338ce05df18f77746ab256efb71c310db9f45e/src/core/document.js#L1716
when we try to access to the field property.
