### ISSUE TITLE
Cant open single page PDFs with size bigger than 1.5mb

### ISSUE THREAD

**Issue by JordanWilting** [mozilla/pdf.js#17246]
Im trying to implement a custom pdf editor for tablets and ran into the following problem on my iPad.
It is not possible to render single page PDFs with a size bigger than 1.5mb. 
When i try to open such a pdf it only displays a white page without displaying anything.

Is there a way to fix this problem without changing the resolution of the displayed pdf?

The app is html based and im using a pdf container (canvas) to render to PDF onto the page. 

This is how i am rendering the pdf onto the given canvas.

HTML snippet: 

```

    <div ref="pdfViewerBox" class="pdf-viewer">
        <div
            class="pdf-viewer-box"
            :class="{ empty: !base64Item || base64Item == '' }">
            <!-- canvas to show the pdf page  -->
            <canvas ref="pdfContainer"></canvas>
             .....
             ....
         </div>
    </div>
```
Typscript snippet: 

```
    const pdfState: PdfCanvasInterface = reactive({
        scale: 1.25,
        rotation: 0,
        countPdfPages: 0,
        pageNumber: 1,
        pageIsRendering: false,
        pageNumberPending: null,
        pdfCanvas: null,
        pdfDocument: null,
    });
    const pdfDocumentWithNoAnnotations = shallowRef<PDFDocumentProxy>();

async function renderPage(): Promise<void> {
        pdfState.pageIsRendering = true;
        // Using promise to fetch the page

        const page = await pdfDocumentWithNoAnnotations.value?.getPage(
            Number(pdfState.pageNumber)
        );

        const viewport = page.getViewport({
            scale: pdfState.scale,
            rotation: pdfState.rotation,
        });
        pdfState.pdfCanvas.height = viewport.height;
        pdfState.pdfCanvas.width = viewport.width;
        const parentContainer = pdfState.pdfCanvas.parentElement;
        parentContainer.style.minWidth = `${viewport.width + 16}px`;
        parentContainer.style.minHeight = `${viewport.height + 16}px`;
        // Render PDF page into canvas context
        const renderTask = page.render({
            canvasContext: pdfState.pdfCanvas.getContext('2d'),
            viewport: viewport,
        });
        try {
            await renderTask.promise;
            if (pdfState.pageNumberPending !== null) {
                // New page rendering is pending
                pdfState.pageNumber = pdfState.pageNumberPending;
                renderPage();
                pdfState.pageNumberPending = null;
            }
        } catch (e) {
            console.error('fehlerhafte Seite' + e);
        }
        pdfState.pageIsRendering = false;

        // Wait for rendering to finish

        //move to the top of the page
        const pdfViewerBox = pdfState.pdfCanvas?.parentElement?.parentElement;
        if (pdfViewerBox) {
            pdfViewerBox.scrollTop = 0;
        }
    }
```

**Comment by Snuffleupagus** [comment]
> Im trying to implement a custom pdf editor for tablets and ran into the following problem on my iPad.
> It is not possible to render single page PDFs with a size bigger than 1.5mb.
> When i try to open such a pdf it only displays a white page without displaying anything.

This unfortunately sounds like you're running into platform/browser limitations of the iPad, and we've seen similar reports previously, since iOS apparently limits e.g. the allowed canvas-size.
There's not a lot that we can do about this generally, and please keep in mind that the Firefox *built-in* PDF Viewer is the primary development target here.

---

*For future reference:* Please remember to fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue and also that code-snippets unfortunately are of limited use (hence why we ask for complete runnable examples).

**Comment by isPaker** [comment]
I encountered the same issue. When loading PDF files with more than 50 pages in iOS Webkit using pdfjs-dist 2.16.105, the pages are forcibly refreshed. Is there a solution to this
