### ISSUE TITLE
Interactive example "previous / next" broken on Safari (macOS)

### ISSUE THREAD

**Issue by xeraa** [mozilla/pdf.js#17249]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 17.1
- Operating system and its version: macOS 13.6.1
- PDF.js version: latest (`//mozilla.github.io/pdf.js/build/pdf.worker.mjs`)
- Is a browser extension: no

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples
2. Go to "Result" of "PDF.js Previous/Next example"
3. JS error in the console `TypeError: undefined is not an object (evaluating 'pdfjsLib.GlobalWorkerOptions')`

What is the expected behavior? (add screenshot)

Vivaldi or Firefox:
<img width="1132" alt="Screenshot 2023-11-09 at 22 21 50" src="https://github.com/mozilla/pdf.js/assets/432211/affd9352-9f42-44e2-a40d-0e2cd547cdbf">

What went wrong? (add screenshot)

Safari:
<img width="1257" alt="Screenshot 2023-11-09 at 22 15 57" src="https://github.com/mozilla/pdf.js/assets/432211/9b6bb0fa-98a4-4734-a091-072065cbb71b">

I only noticed this when starting do dig around when it broke in a similar way on my own site after upgrading to the 4 release. I can also provide that example if needed but your own demo is probably the best starting point?

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari 17.1

The example works just fine in both Firefox Nightly 121.0a1 and Google Chrome Beta 120.0.6099.18, when testing on Windows 11, hence this unfortunately suggests a bug in Safari *itself* since otherwise you'd expect it to be consistently broken everywhere.

**Comment by Lyumih** [comment]
![image](https://github.com/mozilla/pdf.js/assets/32732179/be34068e-1bd9-41f2-b758-44d06cfa6d1c)
In local develop on mac os + google chrome i have broken icons

**Comment by xeraa** [comment]
I tried digging a bit around but I'm at a loss here: In about 80% of the cases `globalThis` is undefined though I'm using Safari 17.1 where it should exist. And if I step in with a debugger and set a breakpoint, it's available. Also a polyfill for older versions doesn't fix the problem. Or using `window` instead of `globalThis`.

And in 20% of the cases approximately it works as it should — I just need to keep refreshing the page. But I'd still love to find a solution since this makes the current version barely usable.

**Comment by xeraa** [comment]
If anyone has the same problem, I've "fixed" it through an act of desperation: Added a polyfill for older browsers and if everything else fails I keep reloading the page. At least for me it seems to work but it is abhorrent.

```js
var { pdfjsLib } = globalThis;
if(pdfjsLib === undefined){ // Fallback for older browsers and a Safari bug
  (function() {
    if (typeof globalThis === 'object') return;
    Object.defineProperty(Object.prototype, '__magic__', {
      get: function() {
        return this;
      },
      configurable: true
    });
    __magic__.globalThis = __magic__;
    delete Object.prototype.__magic__;
  }());
  var { pdfjsLib } = globalThis;
  if(pdfjsLib === undefined){
    var { pdfjsLib } = window;
    if(pdfjsLib === undefined){
      window.location.reload(); // This is an act of desperation
    }
  }
}
```

**Comment by Snuffleupagus** [comment]
> And in 20% of the cases approximately it works as it should — I just need to keep refreshing the page. But I'd still love to find a solution since this makes the current version barely usable.

This unfortunately sounds like a bug that needs to be reported to the Safari developers instead, given that other browsers seems to be unaffected, especially since by the description above it seems to be *intermittent* as well.
