### ISSUE TITLE
Legacy: Type declarations are broken in 4.0

### ISSUE THREAD

**Issue by lanwin** [mozilla/pdf.js#17241]
Ive tested 4.0.189 from NPM and noticed that the type declaration file is broken for legacy with this version. 

> Error:
> Could not find a declaration file for module 'pdfjs-dist/legacy/build/pdf.mjs'

The fix is simple. `pdfjs-dist/legacy/build/pdf.d.ts` should be renamed to `pdfjs-dist/legacy/build/pdf.mjs.d.ts`.

**Comment by tamuratak** [comment]
The file name should be  `pdf.d.mts`, not `pdf.mjs.d.ts`. 

See https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md

> A .d.mts file represents a .mjs file which is always an ES module; a .d.cts file represents a .cjs file which is always a CommonJS module; a .d.ts file represents a .js file whose module format is determined by the nearest package.json.
