### ISSUE TITLE
How to import pdfjs version 4 in a NodeJS project?

### ISSUE THREAD

**Issue by RedShift1** [mozilla/pdf.js#17248]
In version 3 to use pdfjs in NodeJS, the following line is needed:

```javascript
import pdfjs from 'pdfjs-dist/legacy/build/pdf.js';
```

What is the correct import for version 4?

**Comment by Snuffleupagus** [comment]
Please take a look at the Node.js examples: https://github.com/mozilla/pdf.js/tree/master/examples/node

Hence you either import only the needed functionality using e.g.
```javascript
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
```
or you import the entire library using e.g.
```javascript
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
```

**Comment by jameshalsall** [comment]
Doing the former breaks TS types, so not sure that is the solution here 🤔. 

> TS7016: Could not find a declaration file for module  pdfjs-dist/legacy/build/pdf.mjs .
/path/to/project/node_modules/pdfjs-dist/legacy/build/pdf.mjs
implicitly has an  any  type.
If the  pdfjs-dist  package actually exposes this module, try adding a new declaration (.d.ts) file containing
declare module 'pdfjs-dist/legacy/build/pdf.mjs';
