### ISSUE TITLE
Possible Typo in web/pdf_page_view

### ISSUE THREAD

**Issue by pyramid-johng** [mozilla/pdf.js#17254]
https://github.com/mozilla/pdf.js/blob/1b88aad0db542d7bc04babffa137c4662c6b971a/web/pdf_page_view.js#L287

I was poking around and noticed this line might be incorrect and should read `--hcm-highlight-filter` but the `t` is missing?

**Comment by Executioner769** [comment]
attempt to fix typo: #17254
