### ISSUE TITLE
Console error: Failed to load module script

### ISSUE THREAD

**Issue by jamesgurung** [mozilla/pdf.js#17259]
When running PDF.js v4.0.189 in the browser, there is a console error in Chrome 119:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

For instance, this occurs when running the example page at https://mozilla.github.io/pdf.js/examples

Under "Interactive examples > Hello World" click "Result" to run the script. Everything works correctly, but there is a console error:

![image](https://github.com/mozilla/pdf.js/assets/1919846/3c6dd407-42f7-470d-9f44-78f7ceb731ff)

The blob source causing the error is:

```js
await import("https://mozilla.github.io/pdf.js/build/pdf.worker.mjs");
```

The same console error also occurs on my own website when accessing the worker from a CDN, so it's not specific to the example page:

![image](https://github.com/mozilla/pdf.js/assets/1919846/803750d1-87fd-4545-a964-2ef83e05c225)

```js
await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.0.189/pdf.worker.min.mjs");
```

**Comment by Snuffleupagus** [comment]
It works fine in Firefox Nightly 121.0a1, running on Windows 11.

**Comment by jamesgurung** [comment]
I'm getting the error on Google Chrome 119.0.6045.124 (Official Build) (64-bit) and Microsoft Edge 119.0.2151.58 (Official build) (64-bit), which are the latest stable versions. Both on Windows 11, in guest mode with no extensions.

**Comment by Zhouyashi** [comment]
v4.0.189 the same error, v3.11.174 can work
