### ISSUE TITLE
针对中文文献，出现多余空格，导致搜索不准、复制出现多余空格问题

### ISSUE THREAD

**Issue by charliegogh** [mozilla/pdf.js#17251]
![V0KNWYD6 N~LX11G`D}S1)A](https://github.com/mozilla/pdf.js/assets/44202644/37371b25-0c1d-4fb7-a638-6dde7bd46f99)

针对中文文献，出现多余空格问题，导致搜索不准、复制出现多余空格问题

**Comment by Snuffleupagus** [comment]
You must use English in this bug tracker, and you must fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) completely/correctly when opening an issue.
