### ISSUE TITLE
`/GoToR` not working

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#17278]
Attach (recommended) or Link to PDF file here:
[Document with `/GoToR`](https://github.com/mozilla/pdf.js/files/13354256/a.pdf)
[Document with named destinations](https://github.com/mozilla/pdf.js/files/13354258/whatever.pdf)

Configuration:
- Web browser and its version: firefox-119.0-5
- Operating system and its version: Fedora 37
- PDF.js version: 3.11.183 [d37cd65c5]
- Is a browser extension: the one that comes with the browser.

Steps to reproduce the problem:
1. Open the file `a.pdf` with Firefox.
2. Click on any link (they don’t work).

What is the expected behavior? (add screenshot)

Given that `a.pdf` contains some objects such as:

```
3 0 obj
<<
  /D (1)
  /F (whatever.pdf)
  /S /GoToR
>>
endobj
```

and `whatever.pdf` is on the same directory as `a.pdf`, links should be followed (and they should reach its destination in the external document).
 
What went wrong? (add screenshot)

`/GoToR` actions are not working.

I don’t know whether this behavior is intended.

If disabling the links is intentional, I think links in local documents to documents on the same directory (or subdirectories) may be exempted from this.

Many thanks for your help.

**Comment by Snuffleupagus** [comment]
Please note that it does work in the development viewer, hence this kind of /GoToR destination *can* work...

> I think links in local documents to documents on the same directory (or subdirectories) may be exempted from this.

This is unfortunately a *browser limitation*, related to how the Firefox PDF Viewer works, please see #12415 and [bug 1678914](https://bugzilla.mozilla.org/show_bug.cgi?id=1678914).
