### ISSUE TITLE
PDF.js doesn't render large images in PDF that other renderers do

### ISSUE THREAD

**Issue by thiagohp** [mozilla/pdf.js#17289]
Link to PDF file: [example.pdf](https://github.com/mozilla/pdf.js/files/13391396/example.pdf)

- Firefox 119.0.1 (64-bit), Chromium 119.0.6045.159 (Official Build) snap (64-bit)
- Ubuntu Linux 23.04.
- PDF.js version: 4.0.189 [50f52b43a]
- Is a browser extension: no.

Steps to reproduce the problem:
1. Just open the PDF on PDF.js

What is the expected behavior?
Notice the scanned book page image gets rendered:
![image](https://github.com/mozilla/pdf.js/assets/163011/859e9d01-22cb-44cf-98bc-f0f77759b54c)
Screenshot take from Atril Document Viewer.

What went wrong?
Notice the scanned book page does not get rendered here:
![image](https://github.com/mozilla/pdf.js/assets/163011/90bb7ab0-a7a5-43ad-8c5a-2cc4f1cf0066)

Console log:
PDF 247b3d402477644b1b7b61c8c1311da0 [1.6 PDF24 / PDF24] (PDF.js: 4.0.189 [50f52b43a]) [viewer.mjs:12052:13]
Warning: Unsupported header type 1970628964 (uuid). 2 [pdf.worker.mjs:339:13]
Warning: JPX: Unsupported COD options (terminationOnEachCodingPass, verticallyStripe, predictableTermination). 08:55:09.017 Warning: Unable to decode image "img_p0_1": "JpxError: JPX error: JPX error: Invalid tag tree".
Warning: Dependent image isn't ready yet

Last three lines repeat for every scanned page image.

**Comment by zzj0402** [comment]
Same issue with my use case on a scanned book.

**Comment by calixteman** [comment]
> Same issue with my use case on a scanned book.

Please file a new issue and attach a pdf: this kind of comment in a closed issue is useless.
