### ISSUE TITLE
Building Generic version no longer allows viewer to open PDF files

### ISSUE THREAD

**Issue by intrepidOlivia** [mozilla/pdf.js#17292]
**Configuration:**
- PDF.js version: ffbfd680e

**Steps to reproduce the problem:**
1.  Pull the repo
2. Install with `npm install` and `npm install -g gulp-cli`
3. Build the viewer with `gulp generic`
4. Serve the files located in `build/generic` and navigate to `web/viewer.html`

**What is the expected behavior?** (add screenshot)
There should be an Open button available for the generic PDF viewer
![image](https://github.com/mozilla/pdf.js/assets/3474569/d252b7fb-b46f-4504-a302-13e00f3d4146)

**What went wrong?** (add screenshot)
There is no Open button available
![image](https://github.com/mozilla/pdf.js/assets/3474569/3a5af2d4-1281-4847-a166-9472f3903601)

**Additional Notes**
This seems to be a fairly recent development, because I still had the Open button from last time I built from the repo at commit 77475ac61.

If this is intentional behavior for the Generic viewer, is there someone who can explain to me how to properly configure my build so that button is available?

**Comment by intrepidOlivia** [comment]
Never mind.. I see that removing this button was the entire purpose of bf01674. I don't understand why this one button complicates CSS rules when there are other buttons on the toolbar already. But okay.

**Comment by Snuffleupagus** [comment]
The "Open file"-button was permanently moved, see PR #17244, into the secondaryToolbar.
