### ISSUE TITLE
Alt-text and delete buttons may overlap

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17298]
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: 4.0.242 [3459615ec]
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Open the demo viewer, https://mozilla.github.io/pdf.js/web/viewer.html#locale=en-US 
2. Add a StampAnnotation, e.g. `firefox_logo.svg` from the test-suite.
3. Rotate the document once. *Edit:* It also reproduces without rotating, simply by making the Annotation small enough.

What is the expected behavior? (add screenshot)
That both the alt-text *and* delete buttons are visible and clickable.

What went wrong? (add screenshot)
The buttons overlap, see 

![overlap](https://github.com/mozilla/pdf.js/assets/2692120/eb3cf8bb-85c3-47a8-b213-173aa2c12666)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by Snuffleupagus** [comment]
@calixteman Can you please check with UX how we should handle this situation?

**Comment by calixteman** [comment]
Yep I asked the question yesterday and they were thinking about moving the alt-text button in the new editor toolbar.
That said, it's Thanksgiving in US, so I guess we'll have nothing before next week.
