### ISSUE TITLE
Getting 'MIME type' errors which prevent PDF display

### ISSUE THREAD

**Issue by jamminjames** [mozilla/pdf.js#17296]
I am getting these MIME type errors which prevent my test file pageviewer.html from displaying the pdf:

For /node_modules/pdfjs-dist/build/pdf.mjs:
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

For /node_modules/pdfjs-dist/web/pdf_viewer.mjs: 
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

For pageviewer.js: 
Uncaught ReferenceError: pdfjsLib is not defined

How can I fix these? I'm also not sure how to reference what pdf file to display. I'm trying to use the pageviewer.html example from the examples folder here.

I have the latest npm and nodejs installed.

Any help is appreciated!

Configuration:
- Web browser and its version: Chrome Version 109.0.5414.120 (Official Build) (32-bit)
- Operating system and its version: Windows 7
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. installed pdf.js and set up pageviewer.html as per example
2. not working

What is the expected behavior? (add screenshot) 
To display the pdf

What went wrong? (add screenshot)
Completely blank web page, with the above errors in the Developer Tools Console.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://subs.humortimes.com/pageviewer.html

**Comment by Snuffleupagus** [comment]
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

This error message says that your *web-server* isn't correctly configured, since it returns an incorrect MIME type for `*.mjs` files. Hence you'll need to update the server configuration to return `text/javascript` for such files. (Exactly how that's done might vary depending on the server used, and isn't really something that we can help you with here.)

> PDF.js version: latest

*For future reference:* Please remember to provide a version *number*, since what "latest" is (obviously) changes over time.

**Comment by jamminjames** [comment]
Ah, of course. We're using nginx, and that is configured in /etc/nginx/mime.types in our case. Thank you.

**Comment by eobeans** [comment]
> Ah, of course. We're using nginx, and that is configured in /etc/nginx/mime.types in our case. Thank you.

hi, how you configured nginx to success deal it ? thx

**Comment by eobeans** [comment]
thx, we deal it.  use
 http {
    include       mime.types;
    types {
       application/javascript js mjs;
    }
    default_type  application/octet-stream;

.....

**Comment by frankzhu0925** [comment]
![image](https://github.com/mozilla/pdf.js/assets/145976678/90fdcdff-1748-4130-8bcb-69d2f1c4668d)
Same problem, solved by this conf

**Comment by frankzhu0925** [comment]
> thx, we deal it. use http { include mime.types; types { application/javascript js mjs; } default_type application/octet-stream;
> 
> .....

![image](https://github.com/mozilla/pdf.js/assets/145976678/622832b7-f317-42a6-b015-dde88fcf8997)
Same problem, solved by this conf

**Comment by arlomedia** [comment]
For the sake of better search results, the error I was getting in Safari was:

TypeError: text/plain is not a valid JavaScript MIME type

I use Apache, so I edited /etc/mime.types and added mjs after js on the same line as the existing text/javascript entry. I didn't need to restart Apache but did need to clear my browser cache.

**Comment by palalor01** [comment]
thx, i did the same and it works perfectly

`http {
    ## use mime types
    include /etc/nginx/mime.types;
    types {
        application/javascript js mjs;
    }
    default_type application/octet-stream;`

**Comment by beit-dp** [comment]
If you use Apache, you can set it by updating the .htaccess file:

`<IfModule mod_mime.c>
  AddType text/javascript mjs
</IfModule>`

**Comment by alekswebnet** [comment]
This nginx config works perfectly for me:

```bash
server {
    # ...

    location / {
        root   /usr/share/nginx/html;
        index  index.html;

        location ~* \.mjs$ {# target only *.mjs files
            # now we can safely override types since we are only
            # targeting a single file extension.
            types {
                text/javascript mjs;
            }
        }
    }
}
```

Thanks to the author! https://stackoverflow.com/a/19630564/12674896

**Comment by shivangi-2001** [comment]
@alekswebnet  hi there,

I used to your code but doesn't help, can you guide me:

<img width="537" alt="Screenshot 2024-09-06 at 5 34 16 PM" src="https://github.com/user-attachments/assets/00fea108-5585-41fc-89b5-9780f51015b0">
<img width="634" alt="Screenshot 2024-09-06 at 5 34 04 PM" src="https://github.com/user-attachments/assets/3fa6083b-68d1-41be-8397-86baa8d76773">

**Comment by calixteman** [comment]
@shivangi-2001, sorry but this issue has been closed a while back and is unrelated to pdf.js itself (see https://github.com/mozilla/pdf.js/issues/17296#issuecomment-1818335844). So please don't use this issue tracker as a chat room. Thank you.

**Comment by susanforme** [comment]
You can downgrade to version 3.11.174 ,then use the file pdfjs-dist/build/pdf.worker.min.js

**Comment by yuroyami** [comment]
@susanforme I saw this a bit late after editing NGINX. But i do confirm that version 3.x works as a workaround

**Comment by Laurent1991-LAW** [comment]
Another solution is to require worker js file from unpkg.com, not from our own web-server, hence no need to config Nginx anything.
The way to do it is simply replace 'new URL().toString()' block like below:

```javascript
import { pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
```

**Comment by jimmygu2024** [comment]
> Another solution is to require worker js file from unpkg.com, not from our own web-server, hence no need to config Nginx anything. The way to do it is simply replace 'new URL().toString()' block like below:
> 
> import { pdfjs } from 'react-pdf';
> 
> pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
it's not work for me.

**Comment by jimmygu2024** [comment]
@Laurent1991-LAW  it's not work for me,  could you give me a exmaple please ?

**Comment by Laurent1991-LAW** [comment]
> [@Laurent1991-LAW](https://github.com/Laurent1991-LAW) it's not work for me, could you give me a exmaple please ? if I don't want to change Nginx

Could you share your error massage ? i.e. Anything on the browser console.
Getting from `unpkg.com` requires access to open Internet, if your web server's located in intranet, then it's probably not working.

**Comment by niemyjski** [comment]
It makes no sense why we are distributing this with this in 2025 with a mjs file extension. Please distribute it with a .js file extension.

**Comment by calixteman** [comment]
@niemyjski do you have a pointer explaining what the common sense "web-standards-based" is ?
Modules are around for few years now:
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#see_also

If you're unhappy with our way to do, please feel free to fork and change whatever makes you happy, if you don't know how to do, you can pay someone to do it.
We've to make some choices every day and whatever we choose some people will be unhappy.
FYI, our main focus is to write the Firefox pdf viewer and few years ago we move most of the Firefox js code into modules.

**Comment by niemyjski** [comment]
My apologies, I'm grateful for this library and team. I was just frustrated that we are in an esm world yet still struggling with conventions due to cjs and that a js lib upgrade would require infra changes.

Yes, use common file extensions like `.js`. The article you linked even calls it out that some tooling will never support it, most web servers don't serve it right, script type attribute (type="module") already defines it's a module. Finally, if you google pdf.js/mjs and mime you'll see tons of end users struggling with this. It's not always easy to configure a server e.g., cloudfront serving it up from s3, requires you to upload the mjs files with an attribute. Let alone dx locally is completely different once you deploy it. Browsers and tooling will do the correct things, there are way more upsides of just using .js instead of .mjs.
