### ISSUE TITLE
TypeError: this.info.toSource is not a function

### ISSUE THREAD

**Issue by prmanik** [mozilla/pdf.js#17308]
Configuration: 
Web browser and its version: Chrome Version 119.0.6045.160 (Official Build) (64-bit)
Operating system and its version: Windows version 11 enterprise
PDF.js version: [v4.0.189]
Is a browser extension: No

Steps to reproduce the problem:
1. Open any Published MasterControl documents
2. and will get an error - TypeError: this.info.toSource is not a function and in text layer stating that "Published MasterControl documents frequently use JavaScript. If you are seeing this message, your viewer either does not support JavaScript or it is disabled. If you are using Adobe Acrobat, please enable JavaScript. If you are using another viewer, you will need to configure your browser to view PDF files externally in Adobe Acrobat."

What is the expected behavior? (add screenshot)
<img width="580" alt="image" src="https://github.com/mozilla/pdf.js/assets/140620152/deb39ddf-879a-4063-a097-4ee03fd94b7a">

What went wrong? (add screenshot)
<img width="952" alt="image" src="https://github.com/mozilla/pdf.js/assets/140620152/fcef2d4d-8628-4685-983f-c0f9365a342e">

Could you please let us know, how to resolve the issue?

**Comment by Snuffleupagus** [comment]
The `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is always required in order for any issue to be actionable/valid.

> Open any Published MasterControl documents

We have no idea what that is, and consequently it's not something that we can provide help/support for here.

---

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
