### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'samplesPerLine')

### ISSUE THREAD

**Issue by manunio** [mozilla/pdf.js#17302]
While [Fuzzing](https://en.wikipedia.org/wiki/Fuzzing) locally using [jazzer.js](https://github.com/CodeIntelligenceTesting/jazzer.js) `JpegImage().parse` threw `TypeError: Cannot read properties of undefined (reading 'samplesPerLine')` at
https://github.com/mozilla/pdf.js/blob/d8424a43baf4c18dd19c77f466bbfff2b15cd8f4/src/core/jpg.js#L1076

Configuration:
- Operating system and its version:  Ubuntu 20.04.6 LTS
- PDF.js version: v4.0.189

Steps to reproduce the problem:

```js
❯ cat test.js
import { JpegImage } from "./src/core/jpg.js";
new JpegImage().parse(Buffer.from('ffd8', 'hex'));
```
```js
❯ node test.js
Warning: JpegImage.parse - reached the end of the image data without finding an EOI marker (0xFFD9).
file:///home/maxx/dev/security/oss-fuzz-projects/pdf.js/src/core/jpg.js:1076
    this.width = frame.samplesPerLine;
                       ^

TypeError: Cannot read properties of undefined (reading 'samplesPerLine')
    at JpegImage.parse (file:///home/maxx/dev/security/oss-fuzz-projects/pdf.js/src/core/jpg.js:1076:24)
    at file:///home/maxx/dev/security/oss-fuzz-projects/pdf.js/test.js:3:17
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v21.1.0

```

What is the expected behavior? 
 - Should not throw exception.

**Comment by Snuffleupagus** [comment]
> would be interested in fuzzing pdf.js at [oss-fuzz](https://google.github.io/oss-fuzz/) ? It's a free service by google for continuously fuzzing important open source projects.

Thanks for the offer!
For me personally, the utility of that would depend a fair bit on the number and "quality" of issues it'd report.

For example: A lot of the worker-thread code, which is where the parsing happens, will be called with data that's already been validated elsewhere; hence I'd be slightly worried about us potentially "drowning" in unrelated/non-actionable reports.[1]

/cc @calixteman, @marco-c What's your opinion on this?

---
[1] Note that the patch for this issue simply "replaced" an implicit Error with an explicit one, see the discussion starting at https://github.com/mozilla/pdf.js/pull/17303#pullrequestreview-1740370681.

**Comment by pyoor** [comment]
@Snuffleupagus can you point me to where in the worker-thread code this validation occurs?  Assuming that that code is exported, the fuzzer implementation could pass data through that validation routing before then passing it to the individual parsers (which I definitely think is a worthwhile fuzzing target).

**Comment by Snuffleupagus** [comment]
> can you point me to where in the worker-thread code this validation occurs?

There's no "point" where that happens, since we have lots of validation all over the place (which you need given how real-world PDF document often look).
My comment was simply intended to illustrate that getting *loads of reports* similar to this one, which as discussed in https://github.com/mozilla/pdf.js/pull/17303#pullrequestreview-1740370681 wasn't clear that we actually "must" to fix, could end up taking a lot of triaging resources.

**Comment by tysmith** [comment]
> could end up taking a lot of triaging resources.

That is a valid concern but it's better to see what bugs are found and triage as time allows. Invalid issues can always be marked as `wontfix`.

**Comment by Snuffleupagus** [comment]
> The reason for selecting ImageDecoders was, as it being listed as an example and it seems its also being released separately as pdfjs-dist.

Note that when the image decoders are used "normally", i.e. during parsing of a PDF document, any errors thrown during image decoding will be caught and thus cannot break general parsing of a PDF page.

> Should we start with decoders for now to see how it goes, i can submit a pr as an initial step.

We should probably wait for feedback from @calixteman and @marco-c *first*, before doing something that might add a lot of maintenance/triaging work.

**Comment by marco-c** [comment]
I think before adding ourselves to OSS-Fuzz we should first try a bit manually, otherwise we will be overwhelmed by automatically filed issues.

**Comment by marco-c** [comment]
Let's go ahead then, you can add my email (mcastelluccio@mozilla.com).
