### ISSUE TITLE
No delete button appears

### ISSUE THREAD

**Issue by lapopm** [mozilla/pdf.js#17321]
Attach (recommended) or Link to PDF file here:
**the demo template file**

Configuration:
- Web browser and its version: **Chrome 119**
- Operating system and its version: **Windows 11**
- PDF.js version: **4.0.189**
- Is a browser extension: **No**

Steps to reproduce the problem:
**1. download prebuild version
2. I used the demo site to test the delete button after drawing, and it works
3. the delete button doesn't show when I put the prebuilt version into a folder in my project**

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/83830521/052da215-1ecd-4efc-9a8b-7694e0088b20)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/83830521/fb578f32-c1bc-49c7-9f0f-ff671e4f9760)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please compare the release date of https://github.com/mozilla/pdf.js/releases/tag/v4.0.189 with the merge date of https://github.com/mozilla/pdf.js/pull/17243#event-10926845252, and you should be able to answer this yourself :-)

Hence you'll simply have to wait for the next release, but please remember http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by lapopm** [comment]
你好，我是77，我已收到你的邮件。
