### ISSUE TITLE
Draweditor makes weird jumps when creating multiple annotations on different pages

### ISSUE THREAD

**Issue by PatrickZimmerer** [mozilla/pdf.js#17327]
Page to reproduce: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Chrome version 118, also on Safari
- MacOS 14.1.1 
- PDF.js version: whatever runs on this demo page of yours: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. Draw an Ink Editor Annotation (just a circle on page 1)
2. Scroll to page 2 and draw another Annotation

Expected behavior:
There should be two circles:
1. draw a circle
2. closed the toolbar for the draw editor
3. scrolled to page 2
4. opened the draw editor 
5. draw another circle
Outcome: 
![Bildschirmfoto 2023-11-24 um 10 20 57](https://github.com/mozilla/pdf.js/assets/96255548/486d0b99-db12-41a1-a08b-0a59081de117)

What went wrong:
There is a weird jump the draw editor makes so the second circle has a weird line in it:
1. draw a circle
2. scrolled to page 2
3. draw another circle
Outcome: 
![Bildschirmfoto 2023-11-24 um 10 18 16](https://github.com/mozilla/pdf.js/assets/96255548/3bd590b9-23f4-4036-85e1-85ecee5a4aa3)

**Comment by Snuffleupagus** [comment]
WFM, in Firefox Nightly 122.0a1 on Windows 11.

**Comment by PatrickZimmerer** [comment]
Yes, the error also exists on Edge, any Idea on how to fix the error on other browsers?

**Comment by gregahren** [comment]
This issue is reintroduced in the Dec 31st version. Please check.

**Comment by avdoseferovic** [comment]
The same issue is now present in v4.10.38. On firefox it works properly.
