### ISSUE TITLE
Signature is missing in Signed PDFs

### ISSUE THREAD

**Issue by 15369411343** [mozilla/pdf.js#17332]
Attach (recommended) or Link to PDF file here:
[test(1).pdf](https://github.com/mozilla/pdf.js/files/13463186/test.1.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 119.0.2151.72
- Operating system and its version: Windows10
- PDF.js version: 4.0.189
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached/linked PDF file using PDF.js.
2. Navigate to the page with the electronic stamp.

What is the expected behavior? (add screenshot)
The electronic stamp should be displayed correctly on the signed PDF document.

What went wrong? (add screenshot)
The electronic stamp is not rendering/displaying.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
According to the console log, there's something wrong with the /FlateDecode-streams of the Annotations:
```
PDF 4c3c7124243ed749ad2627a65bd58811 [1.7 Microsoft® Word 2019 / Microsoft® Word 2019] (PDF.js: 4.0.246 [086a5921d]) [viewer.mjs:10503:13](resource://pdf.js/web/viewer.mjs)
Warning: TT: undefined function: 32 [pdf.worker.mjs:339:13](resource://pdf.js/build/pdf.worker.mjs)
Warning: TT: undefined function: 3 [pdf.worker.mjs:339:13](resource://pdf.js/build/pdf.worker.mjs)
Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "FormatError: Bad block header in flate stream". 2 [pdf.worker.mjs:339:13](resource://pdf.js/build/pdf.worker.mjs)
```

**Comment by 15369411343** [comment]
But it can be displayed in MuPDF.
![20231126101645](https://github.com/mozilla/pdf.js/assets/50473179/ad2d6d00-bb80-4070-a64e-7684b4d99bff)

**Comment by calixteman** [comment]
The pdf is correctly rendered in Chrome, in Acrobat and in Preview.
