### ISSUE TITLE
Error on this wiki page: https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website

### ISSUE THREAD

**Issue by Leask** [mozilla/pdf.js#17357]
In page https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website .
Please fix the link https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js to https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.mjs .
Thaanks!

**Comment by timvandermeij** [comment]
Done. Thank you for reporting this!

**Comment by Leask** [comment]
👍 Cool! I hope GitHub will release a feature that enables us to file a pull request to wiki pages. :)
