### ISSUE TITLE
[Generic viewer] Firefox automatically opens the PDF upon download

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#17365]
Attach (recommended) or Link to PDF file here: Any

Configuration:
- Web browser and its version: Firefox 120.0.1
- Operating system and its version: macOS 11.7.10
- PDF.js version: 4.0.296
- Is a browser extension: No

Steps to reproduce the problem:
1. Set Firefox to open PDF files by default
2. Open the online demo viewer in Firefox
3. Click the save/download button

What is the expected behavior? (add screenshot)
File should get downloaded to disk.

What went wrong? (add screenshot)
Firefox opens the downloaded PDF in the built-in viewer in a new tab.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

This does not happen when the action for PDF is set to `Always Ask` or `Save File`. This happens only for the generic viewer; with the integrated viewer Firefox opens the prompt asking what to do with the file.

**Comment by Snuffleupagus** [comment]
Please keep in mind that the GENERIC viewer simply triggers downloading, and exactly how that's handled is then up to *the browser itself* and thus not really in our control (as far as I can tell).
It sounds like the browser does exactly what's it configured to do in this case, i.e. display PDF documents, hence it's unfortunately not clear what you expect the PDF.js viewer to do differently here!?

**Comment by shivaprsd** [comment]
I was wondering if this behaviour could be related to the *specific way* the Generic viewer triggers downloading (programmatically creating and clicking a temporary `<a>` element), and hence, if it could be controlled.

If I click a regular link to a PDF it opens in the Default viewer. If I secondary click and choose `Save as` it downloads. This same behaviour applies to other media types also. Only in this particular case, FF downloads the file and also opens the (*local*) file in a new tab (i.e. served from a `file:///` url).

This simply felt... weird. Even FF simply opening the linked file in the Default viewer without downloading was understandable. This was indeed the behaviour a few versions ago. I think it changed because now all downloads are done as blob downloads?
