### ISSUE TITLE
Can we increase the value of the `maxCanvasPixels` viewer-option?

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17371]
The current `maxCanvasPixels` viewer-option value is 16 mega-pixels, introduced in PR #4834 which was almost *a decade* ago; see https://github.com/mozilla/pdf.js/blob/5111b6d37169822e18a9bf27f298c8612724df01/web/app_options.js#L179-L183

In Firefox the maximum allowed canvas-size (in bytes) is currently *a lot* larger; see https://searchfox.org/mozilla-central/rev/68b1b0041a78abd06f19202558ccc4922e5ba759/modules/libpref/init/StaticPrefList.yaml#6169-6173
Note that we're actually using this value as the maximum canvas-size when resizing huge images in the *worker thread* with `OffscreenCanvas`, which should correspond to a maximum of 512 mega-pixels; i.e. `(0x7FFFFFFF >> 2) / 1024 ** 2` given https://github.com/mozilla/pdf.js/blob/5111b6d37169822e18a9bf27f298c8612724df01/src/core/image_resizer.js#L112-L117

Since the current `maxCanvasPixels` value is *well over* an order of magnitude smaller than the upper browser-limit, I thus wonder if we could perhaps increase this now (e.g. doubling it to 32 mega-pixels)?
This would *obviously not* "fix" the issues we have with huge canvases, but would at least improve things a little bit by enabling users to zoom-in further before we fallback to CSS-only zooming.[1]

/cc @calixteman Any opinions/thoughts?

---
[1] This sort of change could perhaps *complement* canvas tiling, since it'd help reduce the number of separate canvases necessary.

**Comment by Snuffleupagus** [comment]
> Would it be easy to make the number of pages in the cache depending on the page size and the zoom level ?

Probably not all that difficult, assuming I didn't make a mistake somewhere: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:pdf.js:viewer-totalCanvasPixels

**Comment by calixteman** [comment]
Could you make a PR with the patch above ? at first glance it looks good.
