### ISSUE TITLE
The problem of "No gulpfile found"

### ISSUE THREAD

**Issue by laishuliang** [mozilla/pdf.js#17383]
The gule-cli does not support gulp.mjs format until version 2.3.0. However, the package-lock.json file locks version 2.2.0, causing the following error "No gulpfile found" when gulp server is executed after npm install.

package-lock.json -- line 8439,

```json
"node_modules/gulp/node_modules/gulp-cli": {
      "version": "2.2.0",
      "resolved": "https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.2.0.tgz",
      "integrity": "sha512-rGs3bVYHdyJpLqR0TUBnlcZ1O5O++Zs4bA0ajm+zr3WFCfiSLjGwoCBqFs18wzN+ZxahT9DkOK5nDf26iDsWjA==",
      "dev": true,
      "dependencies": {
        "ansi-colors": "^1.0.1",
        ... ....
```

The gulp-cli module version 2.3.0 of package-lock.json should be regenerated and submitted.

**Comment by Snuffleupagus** [comment]
This shouldn't be a problem if you actually follow https://github.com/mozilla/pdf.js#getting-the-code, since it explicitly tells you to run `$ npm install -g gulp-cli` *before* running `$ npm install`.
