### ISSUE TITLE
Can't print PDF from <object> / <iframe> / <embed>

### ISSUE THREAD

**Issue by nikita11044** [mozilla/pdf.js#17390]
Configuration:
- Firefox 120.0.1;
- macOS Sonoma 14.0;
- PDF.js is not a browser extension.

I have the following React component. It receives a link to a PDF document and renders PDF browser-specific viewer.

```
export type PDFViewerChildrenProps = {
  dataUrl: string;
};
 
const PDFViewerChildren = (props: PDFViewerChildrenProps) => {
  const { dataUrl } = props;
 
  if (!dataUrl) {
	return null;
  }
 
  return (
	<object
  	  type="application/pdf"
  	  aria-label="View PDF"
  	  data={dataUrl}
	/>
  );
};
 
export default PDFViewerChildren;
```

It works as intended in all browsers except Firefox. Firefox for some reason fails to print the document. Each time a “Print” button on viewer’s toolbar is clicked, an NS_ERROR_FAILURE error appears in the console (see screenshot).

![image](https://github.com/mozilla/pdf.js/assets/62565112/c997f998-2165-4e7a-b001-983cd273b188)

<img width="452" alt="image" src="https://github.com/mozilla/pdf.js/assets/62565112/fb32e4fb-ad05-4171-9bf5-b7f2611e351d">

Other buttons work as intended. The PDF itself is rendered correctly. The only issue is printing in Firefox.

The same error appears in Firefox even if object is replaced with iframe or embed.

Tried rewriting component with different tags, adjusting Firefox setting - nothing worked

**Comment by Snuffleupagus** [comment]
> I have the following React component. It receives a link to a PDF document and renders PDF browser-specific viewer.

Unfortunately this cannot be run as-is; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by trott13** [comment]
Same for me using ExtJS. When the PDF is rendered in <iframe>/<object>/<embed> the Error occurs and the PDF isn't printable. Having trouble with this issue "for ages" essentially switching to Chrome to solve it.
Just verified again on Firefox 130/MacOS
