### ISSUE TITLE
Single point ink annotation doesn't show on Chrome pdf viewer

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#17418]
Configuration:
- Web browser and its version: Firefox 115.5.0esr  / Chrome 120.0.6099.71
- Operating system and its version: Ubuntu 22.04
- PDF.js version: 4.0.347
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the [viewer](https://mozilla.github.io/pdf.js/web/viewer.html).
2. Draw a single point annotation (not a line) with the ink tool.
3. Save the pdf.
4. Open the pdf in a Chrome tab.

What is the expected behavior?
The point ink annotation should be visible

What went wrong?
The point ink annotation doesn't show on Chrome.

Is it a bug in the Chrome pdf viewer? Is there a way to draw a circle annotation instead of a single point line?

**Comment by calixteman** [comment]
Why do you think it's a bug in pdf.js ?
I opened the created pdf in Acrobat and it's rendered correctly.
That said we can likely improve things, but really this a bug in Chrome.

**Comment by benbro** [comment]
I've tried adding support for circle and polygon annotations to [saveNewAnnotations](https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L324):
```javascript
case AnnotationEditorType.CIRCLE:
          promises.push(
            CircleAnnotation.createNewAnnotation(xref, annotation, dependencies)
          );
          break;
case AnnotationEditorType.POLYGON:
          promises.push(
            PolygonAnnotation.createNewAnnotation(xref, annotation, dependencies)
          );
          break;
```

But I wasn't able to find the equivalent syntax to pdf.annotationStorage.setValue(key, value) with annotationType 6 for circle and 7 for (polygon). Is it possible to add it if it's only few lines of code?
```javascript
let key = "pdfjs_internal_editor_1";
let value = {
  "annotationType": 15,
  "color": [255, 0, 0],
  "thickness": 3,
  "opacity": 1,
  "paths": [{
      "bezier": [
        73, 560.2277710847244, 74.30408044851005, 561.5318515332344,
        76.89681158113368, 557.7555609512324, 77.5, 557.2277710847244,
        81.95407020558315, 553.3304596548392, 87.4811839685984, 550.8645311043504,
        92.5, 547.7277710847244, 97.38795894206055, 544.6727967459365,
        109.48854351637208, 540.2392275683522, 113.5, 536.2277710847244
      ],
      "points": [
        73, 560.2277710847244, 76.7257911988625, 558.1025687477292,
        75.5128345111164, 559.4147224528562, 77.5, 557.2277710847244,
        92.5, 547.7277710847244, 109.21378602219673, 539.2873735223628,
        103.32868842191223, 542.3364518890394, 113.5, 536.2277710847244
      ]
  }],
  "pageIndex": 0,
  "rect": [71.5, 534.5, 115, 562],
  "rotation": 0
}
pdf.annotationStorage.setValue(key, value);
```
