### ISSUE TITLE
To add OCR function in pdf.js

### ISSUE THREAD

**Issue by Ekans111** [mozilla/pdf.js#17425]
## It's awesome, wonderful and perfect module in PDF viewer.
I want to add some function in it such as OCR, draw rectangle, circle and blabla...
It's common functions in local PDF viewer like **Acrobat**, **Foxit Reader**...
Buy why don't we make it yet?
I suggest the way to realize my dream.
Thank you for your kindness.

**Comment by timvandermeij** [comment]
OCR is already tracked in #15843 and annotation editing is already tracked in https://github.com/mozilla/pdf.js/projects/9 and present for some types already.

**Comment by akmalabaa99** [comment]
any updates of this? i open the provided link, i can't find anything with the "ocr" keyword. Sry if i dont understand.
