### ISSUE TITLE
pdf version 2.4.456 gulp error

### ISSUE THREAD

**Issue by parksuhyun9321** [mozilla/pdf.js#17426]
Configuration:
- PDF.js version: 2.4.456

Steps to reproduce the problem: Error running "gulf generic"
1. https://github.com/mozilla/pdf.js/assets/59465364/08e20e6a-d465-4018-9adc-7820f847cb6d 
2. https://github.com/mozilla/pdf.js/assets/59465364/1e94c4aa-c797-4425-96b1-87dd80f36882

What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/e1543b28-1b86-424d-9b05-cf8cf3fb02bf

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/b9a7373f-2a58-41e6-a300-f70ad8811637
https://github.com/mozilla/pdf.js/assets/59465364/82e2a886-4ba6-4959-b1a5-00d30d384d19
https://github.com/mozilla/pdf.js/assets/59465364/f0444da7-3fd3-40a3-9c2b-30b5e6fd5583 (Error executing 'npm update')

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.4.456

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
