### ISSUE TITLE
Unable to obtain matrix information for image

### ISSUE THREAD

**Issue by Oumae-Kumiko** [mozilla/pdf.js#17422]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Chrome/108.0.5359.215
- Operating system and its version:  win10
- PDF.js version:   "pdfjs-dist": "^4.0.269"
- Is a browser extension:

Steps to reproduce the problem:
1. 
const image = page.objs.get(imageName);
const bmp = image.bitmap;
console.log(bmp)
2. 

What is the expected behavior? (add screenshot)

Hope to obtain matrix information of image deformation and correct width/height
![QQ截图20231214140348](https://github.com/mozilla/pdf.js/assets/36727052/c485a3d3-c4ed-48ce-9f5d-fbaafa024d50)

What went wrong? (add screenshot)

Unable to obtain matrix information and correct width/height for image deformation
![QQ截图20231214140614](https://github.com/mozilla/pdf.js/assets/36727052/fed40b2d-e862-4c68-a7f0-5c0e118bba01)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> Steps to reproduce the problem:
> [...]

Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
