### ISSUE TITLE
webpack helper missing typescript types

### ISSUE THREAD

**Issue by Lazyshot** [mozilla/pdf.js#17433]
Configuration:
- Web browser and its version: Chrome Version 120.0.6099.109 (Official Build) (arm64)
- Operating system and its version: Mac 13.4.1
- PDF.js version: 4.0.269
- Is a browser extension: No

Steps to reproduce the problem:
1. Utilize `import * as pdfjsLib from 'pdfjs-dist/webpack';`
2. View typescript errors

What is the expected behavior? (add screenshot)
No typescript errors and pass through of types

What went wrong? (add screenshot)
Typescript error: `Could not find a declaration file for module 'pdfjs-dist/webpack.mjs'` ts(7016)

**Comment by airmanx86** [comment]
Sorry to dig up a closed issue. However, this is making consuming this library in typescript & webpack environment more challenging than required. With version `4.7.76` I have a work around as follow:

1. Make a folder called `pdfjs`
2. Add `index.d.ts` in it with content `export * from 'pdfjs-dist/types/src/pdf';`
3. Add `index.js` in it with content `export * from 'pdfjs-dist/webpack.mjs';`
4. In the `ts` file import the module (folder) like this `import * as pdfjs from './pdfjs';`

This would load the `pdfjs` with the type definition

**Comment by itsiiromiuy** [comment]
that's awesome solution!! save my life @airmanx86
