### ISSUE TITLE
Bad line height on multiline text in read only

### ISSUE THREAD

**Issue by mbohovic** [mozilla/pdf.js#17447]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Brave [Version 1.61.104 Chromium: 120.0.6099.115 ]
- Operating system and its version: mac OS
- PDF.js version: 
pdfjs dist 4.0.269 https://www.npmjs.com/package/pdfjs-dist/v/4.0.269 
pdf lib: 1.17.1
- Is a browser extension:

Steps to reproduce the problem:
1. in edit mode, the multiline input text is ok
2. in read only mode, the text is displayed using the canvas and has a bad line layout, the text itself goes outside the canvas

What is the expected behavior? (add screenshot)
to display multiline text in read only mode as in edit mode

What went wrong? (add screenshot)
<img width="154" alt="edit-mode" src="https://github.com/mozilla/pdf.js/assets/5237193/76f02c26-9faf-463b-b59b-bf8e6872f319">
edit mode

<img width="246" alt="read-only-mode" src="https://github.com/mozilla/pdf.js/assets/5237193/3fa5d997-16f9-458d-ae1d-6b288f3ea618">
read only mode

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> in read only mode, the text is displayed using the canvas and has a bad line layout, the text itself goes outside the canvas

What does "read only mode" actually mean here?
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by mbohovic** [comment]
hello, I sent a file with a description to the matrix room
​

**Comment by Snuffleupagus** [comment]
> hello, I sent a file with a description to the matrix room

Please just attach the PDF document *directly* here at GitHub, and please provide all additional information here!

**Comment by mbohovic** [comment]
I am writing about this ticket. https://github.com/mozilla/pdf.js/issues/17447
I am attaching a file where you can see that the canvas with this text is rendered poorly, the text is full in the textarea with hidden attr text is entered as "aaa\nbbb\nccc"
[Uploading file.pdf…]()

**Comment by mbohovic** [comment]
I am attaching a file where you can see that the canvas with this text is rendered poorly, the text is full in the textarea with hidden attr text is entered as "aaa\nbbb\nccc"
[Uploading file.pdf…]()

**Comment by Snuffleupagus** [comment]
> Uploading file2.pdf…

Unfortunately that's not a working link, however looking through the editing-history of https://github.com/mozilla/pdf.js/issues/17447#issuecomment-1864452239 it seems to contain one actual PDF document: https://github.com/mozilla/pdf.js/files/13727952/file.pdf

However, quickly checking that PDF document the following "problems" are noticed:
 - It doesn't actually look anything like the screen-shot attached in https://github.com/mozilla/pdf.js/issues/17447#issue-2050182829, which makes this issue slightly difficult to understand.
 - It looks *basically* identical in both Adobe Reader (i.e. the PDF reference implementation) and PDF.js 4.0.347 [76e3e5202] built-in to Firefox Nightly 123.0a1 on Windows 11.
   
   ![adobe](https://github.com/mozilla/pdf.js/assets/2692120/a6a3a22d-5157-4275-89fd-e449b07a2ca1)
   
   ![pdfjs](https://github.com/mozilla/pdf.js/assets/2692120/a1e533be-3620-490c-8eba-c22a4ce11257)

**Comment by calixteman** [comment]
The text field containing `aaa\nbbb\nccc` is read-only and the code to render it has been generated by the software used to save the data. 
So there's no bug here with pdf.js but very likely there's one with the software used to save.
Just fyi, here's the rendering when saved with pdf.js:
<img width="242" alt="image" src="https://github.com/mozilla/pdf.js/assets/5641725/4119a0ee-3e82-409b-a6ec-a79ec21a3cf6">
