### ISSUE TITLE
[Question] Generate to JS

### ISSUE THREAD

**Issue by catmans1** [mozilla/pdf.js#17450]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. I use `gulp generic`
2. The prebuild is mjs files

My question: Can I generate it to js file?

What is the expected behavior? (add screenshot)
Generate to js
What went wrong? (add screenshot)
Generate to mjs
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ifcwlme** [comment]
I think just change the file extension to .js will work.

**Comment by Snuffleupagus** [comment]
We only support outputting of JavaScript modules nowadays, since that's supported in all modern browsers/environments.
