### ISSUE TITLE
PDF turns Firefox into black screen

### ISSUE THREAD

**Issue by janseris** [mozilla/pdf.js#17478]
Attach (recommended) or Link to PDF file here:
https://proboos.cz/wp-content/uploads/2021/12/rsd-prezentace-D1-Kyvalka-Holubice-28_7_2021-002.pdf

Configuration:
- Web browser and its version: Firefox 121.0 (64 bit)
- Operating system and its version: 
  - OS Name:                   Microsoft Windows 11 Pro
  - OS Version:                10.0.22621 N/A Build 22621
- PDF.js version: PDF.js: 4.0.240 [ffbfd680e]
- Is a browser extension: no

Steps to reproduce the problem:
1.  Open the PDF
2. Scroll to page 3 (different paper size (that's the trigger of the bug))
3. The whole Firefox window including titlebar etc turns black but is responsive

![obrazek](https://github.com/mozilla/pdf.js/assets/64279914/f81ac64f-ee1d-4469-843f-fd598f1aa0b0)

What is the expected behavior? (add screenshot)
PDF can be normally viewed such as in Adobe Acrobat or in MS Edge
![obrazek](https://github.com/mozilla/pdf.js/assets/64279914/23ce84c2-27cd-47bb-a2a6-f16fbdf3241d)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla

[rsd-prezentace-D1-Kyvalka-Holubice-28_7_2021-002.pdf](https://github.com/mozilla/pdf.js/files/13833707/rsd-prezentace-D1-Kyvalka-Holubice-28_7_2021-002.pdf)
.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
This PDF file works fine for me with Firefox on Linux, and given that the whole browser is affected this doesn't seem like something we can fix here: it looks like a browser or graphics driver issue. I would recommend to update the graphics drivers, and if that does not solve it to file a bug report upstream at Bugzilla.

**Comment by TiraelSedai** [comment]
@janseris did you manage to figure out what's wrong? I have the same issue

**Comment by FlohEinstein** [comment]
Happens to me with almost all PDFs. e.g. the Swiss Civil Code https://fedlex.data.admin.ch/filestore/fedlex.data.admin.ch/eli/cc/24/233_245_233/20250101/de/pdf-a/fedlex-data-admin-ch-eli-cc-24-233_245_233-20250101-de-pdf-a-2.pdf or the Swiss Code of Obligations https://www.fedlex.admin.ch/eli/cc/27/317_321_377/en . Everything goes to black in black.

![Image](https://github.com/user-attachments/assets/788f3766-0b35-4fe6-aef4-38773626cb93)

In my case though, it only happens inside the pdf.js part of the window. Other tabs, menus etc. are unaffected. Funny enough you can mark text, so is suspect that its simply a problem that the background of PDF pages is displayed black.

At least in that regard, it's not like @janseris's problem, and I'd appreciate if this could be reopened and investigated, and although this is not nice, I hope other people have the same issue - and maybe a solution?

**Comment by THausherr** [comment]
It works for me with FF 134.0.2 on Windows 10.0.19045.5440, Radeon RX 460, its driver is 31.0.21921.1000

**Comment by DuchGhast** [comment]
I had the same problem and clean reinstall of graphic drivers solved the issue.
