### ISSUE TITLE
Unexpected server response (0) while retrieving PDF

### ISSUE THREAD

**Issue by malgee012** [mozilla/pdf.js#17472]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:  cordova android
- PDF.js version:  v4.0.269
- Is a browser extension:  no extension

PDF.js v4.0.269 (build: f4b396f6c)
Message: Unexpected server response (0) while retrieving PDF ""

**Comment by Snuffleupagus** [comment]
Unfortunately this issue doesn't contain nearly enough information to be actionable/valid; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
