### ISSUE TITLE
Unable to fetch pdf from wp content link

### ISSUE THREAD

**Issue by lyqht** [mozilla/pdf.js#17486]
Attach (recommended) or Link to PDF file here: 
https://ausometraining.com/wp-content/uploads/2023/11/AUSOME-Exploring-Being-Autistic-with-My-Child.pdf?fbclid=IwAR3wTlfpAmXrvVzNzyAjfTK-qs3g6s9xlYoyQ6mCyQaqa460Dr2B5LreTQw_aem_AUEPJPsIRkIDMltxzsSAGBGmSEEmtN1yG7NtN1QgslJ5XtmQwsxEKX-PTePUAxPtAXY

> I don't own this document. I have a user that wanted to view this pdf.

Configuration:
- Web browser and its version: Arc (Chromium)
- Operating system and its version: MacOS
- PDF.js version: v4.0.269
- Is a browser extension: no

Steps to reproduce the problem:
1. Visit the [official pdfjs demo link](https://jsfiddle.net/pdfjs/9engc9mw/)
2. Replace the URL with the one above. You will see the failed to fetch error.

What is the expected behavior? (add screenshot)

Can see PDF

What went wrong? (add screenshot)

<img width="3008" alt="image" src="https://github.com/mozilla/pdf.js/assets/35736525/4a83beab-eddf-4d68-9a0c-47bcd5aeb939">

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr
