### ISSUE TITLE
text select have deviation

### ISSUE THREAD

**Issue by Mowmowj** [mozilla/pdf.js#17493]
Attach (recommended) or Link to PDF file here:
my pdf: 
[my_pdf.pdf](https://github.com/mozilla/pdf.js/files/13897306/compressed.tracemonkey-pldi-09.3.pdf)

Configuration:
- Web browser and its version:  chrome(Version 120.0.6099.199 (Official Build) (arm64))
- Operating system and its version: macos 14.0
- PDF.js version: 4.0.379
- Is a browser extension: no

Steps to reproduce the problem:
1.  open this online demo address : https://mozilla.github.io/pdf.js/web/viewer.html 
2. open my provide pdf
3. copy first row text this phrase: "no responsibility"
4. paste any other place the copy text is "e no responsibili"

What is the expected behavior? (add screenshot)
copy what i am really selected text
What went wrong? (add screenshot)
<img width="1915" alt="image" src="https://github.com/mozilla/pdf.js/assets/24759562/c7369ef1-a422-4992-9333-82ce598ca626">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html 

Additional Info:
I find the offset between canvas and test layer is worse in newest version(4.0.379) than pdfjs 2.11 version.

pdf render with pdfjs 2.11.338 like this with small offset:
notes: red text are textlayer, black is canvas
<img width="798" alt="image" src="https://github.com/mozilla/pdf.js/assets/24759562/921aa3ec-2fdf-485c-8948-381345a5dd0a">

pdf render with pdfjs 4.0.379 like this with huge offset:
notes: red text are textlayer, black is canvas
<img width="798" alt="image" src="https://github.com/mozilla/pdf.js/assets/24759562/621811e9-e762-4405-8a14-dc92ff8b38c6">

I know it's a tough issue to fix perfectly, if could not improve, could you tell me the root reason of this issue?

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 4.0.396 [903af4ee0] in Firefox Nightly 123.0a1 on Windows 11.

![firefox](https://github.com/mozilla/pdf.js/assets/2692120/013105d2-a006-4d35-98d0-d4ae2c3ce777)

**Comment by Mowmowj** [comment]
> WFM, using PDF.js 4.0.396 [[903af4e](https://github.com/mozilla/pdf.js/commit/903af4ee0009afbb5e42f5866b966fdefe4185b7)] in Firefox Nightly 123.0a1 on Windows 11.
> 
> ![firefox](https://private-user-images.githubusercontent.com/2692120/295847916-013105d2-a006-4d35-98d0-d4ae2c3ce777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjY5ODcsIm5iZiI6MTcwNDk2NjY4NywicGF0aCI6Ii8yNjkyMTIwLzI5NTg0NzkxNi0wMTMxMDVkMi1hMDA2LTRkMzUtOThkMC1kNGFlMmMzY2U3NzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDk1MTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQ5MzI0ZWYyZTBkNGIxNThkNzA2N2RhMDNiZTcwYWUxY2Q0MTZjZGM5OTdiNjk2YmUyN2Q5ZDlhYmRkYTZiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mlsT6CJm3PSADzZ9mKz9GvqdPQBDlJaD2kdBpjATeMo)

Thanks for your response. after testing my friends' macos version 13 works good as same as you, others macos version 14 not work as same as me. So will pdfjs do the adapting work for macos 14? or it might be a macos bugs.
