### ISSUE TITLE
Text Annotation Extraction Doesn't Supports Breaking lines in Copy and Paste

### ISSUE THREAD

**Issue by Ztong55** [mozilla/pdf.js#17495]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome Version 120.0.6099.216 (Official Build) (64-bit)
- PDF.js version: v4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a text annotation.
2. Copy and paste a long paragraph with line breaks.
3. Save the document.

What is the expected behavior? (add screenshot)
]
![Screenshot 2024-01-11 163558](https://github.com/mozilla/pdf.js/assets/149151442/4c218818-f2eb-470f-b6c4-7206c65b0ddc)

What went wrong? (add screenshot)

![Screenshot 2024-01-11 163643](https://github.com/mozilla/pdf.js/assets/149151442/ffc6b3a4-468f-4c60-bd7e-71bf758a519d)

Provide some details about this:

The extracting method of text annotation in **src/display/editor/freetext.js** is not so good:
```
  #extractText() {
    const divs = this.editorDiv.getElementsByTagName("div");
    if (divs.length === 0) {
      return this.editorDiv.innerText;
    }
    const buffer = [];
    for (const div of divs) {
      buffer.push(div.innerText.replace(/\r\n?|\n/, ""));
    }
    return buffer.join("\n");
  }
```
This will not only lead to the losing first line bug in other browsers, but also make only text input using keyboard available. Maybe here you can add some formatting based on the width of the text annotation. On pasting, making it only paste text content but no fonts and other styles is also a good idea.
By the way, please add flattening function to make it possible to add annotations to the PDF as text content.

**Comment by Ztong55** [comment]
This function from pdf-lib(https://github.com/Hopding/pdf-lib/) may fit this problem:
```
const layoutMultilineText = (
  text: string,
  { alignment, fontSize, font, bounds }: LayoutTextOptions,
): MultilineTextLayout => {
  const lines = lineSplit(cleanText(text));

  if (fontSize === undefined || fontSize === 0) {
    fontSize = computeFontSize(lines, font, bounds, true);
  }
  const height = font.heightAtSize(fontSize);
  const lineHeight = height + height * 0.2;

  const textLines: TextPosition[] = [];

  let minX = bounds.x;
  let minY = bounds.y;
  let maxX = bounds.x + bounds.width;
  let maxY = bounds.y + bounds.height;

  let y = bounds.y + bounds.height;
  for (let idx = 0, len = lines.length; idx < len; idx++) {
    let prevRemainder: string | undefined = lines[idx];
    while (prevRemainder !== undefined) {
      const { line, encoded, width, remainder } = splitOutLines(
        prevRemainder,
        bounds.width,
        font,
        fontSize,
      );

      // prettier-ignore
      const x = (
          alignment === TextAlignment.Left   ? bounds.x
        : alignment === TextAlignment.Center ? bounds.x + (bounds.width / 2) - (width / 2)
        : alignment === TextAlignment.Right  ? bounds.x + bounds.width - width
        : bounds.x
      );

      y -= lineHeight;

      if (x < minX) minX = x;
      if (y < minY) minY = y;
      if (x + width > maxX) maxX = x + width;
      if (y + height > maxY) maxY = y + height;

      textLines.push({ text: line, encoded, width, height, x, y });

      // Only trim lines that we had to split ourselves. So we won't trim lines
      // that the user provided themselves with whitespace.
      prevRemainder = remainder?.trim();
    }
  }
```
Dependence:
`const lineSplit = (text: string) => text.split(/[\n\f\r\u000B]/);`
and
```
const splitOutLines = (
  input: string,
  maxWidth: number,
  font: PDFFont,
  fontSize: number,
) => {
  let lastWhitespaceIdx = input.length;
  while (lastWhitespaceIdx > 0) {
    const line = input.substring(0, lastWhitespaceIdx);
    const encoded = font.encodeText(line);
    const width = font.widthOfTextAtSize(line, fontSize);
    if (width < maxWidth) {
      const remainder = input.substring(lastWhitespaceIdx) || undefined;
      return { line, encoded, width, remainder };
    }
    lastWhitespaceIdx = lastIndexOfWhitespace(line) ?? 0;
  }
```

**Comment by Ztong55** [comment]
> > Steps to reproduce the problem:
> > 1. Create a text annotation.
> > 2. Copy and paste a long paragraph with line breaks.
> > 3. Save the document.
> 
> WFM, when testing in both Firefox Nightly 123.0a1 and Chrome Beta 121.0.6167.57 on Windows 11 and pasting the following text into a new FreeText-annotation:
> 
> ```
> Lorem ipsum dolor sit amet,
> consectetur adipiscing elit,
> sed do eiusmod tempor incididunt
> ut labore et dolore magna aliqua.
> ```
> 
> Since you only included a screen-shot, but not the _actual text_ that you tried to paste, this issue is unfortunately lacking crucial information needed for it to be actionable/valid.

Sorry for that.
If you copy these text from my issue here to make a text annotation, this will happen in Chrome.
![image](https://github.com/mozilla/pdf.js/assets/149151442/68254239-b6e1-4415-b611-91544eccfbe8)
The reason why your text is not affected is that it is manually broken into lines.
Like this code:
```
#extractText() {
    const divs = this.editorDiv.getElementsByTagName("div");
    if (divs.length === 0) {
      return this.editorDiv.innerText;
    }
    const buffer = [];
    for (const div of divs) {
      buffer.push(div.innerText.replace(/\r\n?|\n/, ""));
    }
    return buffer.join("\n");
  }
```
![image](https://github.com/mozilla/pdf.js/assets/149151442/dd6bdb39-7e0b-4cb3-a7f2-e1b00006753b)

The divs.length  === 0 is true and it will return the inner text which has line breaks when there is a '\\'. But at least when I am using window 11 system and Chrome browser, copying something in the webpage and pasting will lead to the inner HTML and inner text to be like this:
![image](https://github.com/mozilla/pdf.js/assets/149151442/a1bff9d8-1127-4b54-80bc-629ed4cec5d1)

The line break happens only because of the span has the text-wrap of 'warp' in its style. And when it is serialized to be rendered on the pdf, the code only extracts it's inner text because it has no inner div.

**Comment by Ztong55** [comment]
> Maybe here you can add some formatting based on the width of the text annotation. On pasting, making it only paste text content but no fonts and other styles is also a good idea.

This is what I think can be done to fix this. Also you can consider that not manually doing line breaks is the user's fault and this is not a bug of the text annotations.

**Comment by Snuffleupagus** [comment]
> Also you can consider that not manually doing line breaks is the user's fault and this is not a bug of the text annotations.

As far as I'm concerned, this seems like a reasonable conclusion.
