### ISSUE TITLE
[Feature request]: Touch scrolling (page swiping with a finger)

### ISSUE THREAD

**Issue by marek-lach** [mozilla/pdf.js#17515]
Attach (recommended) or Link to PDF file here:
https://www.mediaactionresearch.org/wp-content/uploads/2016/10/Understanding_Alternative_Media_Power_Ma.pdf

Configuration:
- Web browser and its version: Firefox 121.01
- Operating system and its version: Linux
- PDF.js version: 4.0.240
- Is a browser extension: No (built-in)

Steps to reproduce the problem:
1. Open up any PDF in Firefox on a tablet, or laptop with a touch-enabled screen.
2. Try to scroll pages with a finger swipe, up, or down, the pages won't move.

What is the expected behavior?
Make the pdf.js viewer scrollable with a finger-touch swipe up /down and left/right gesture.

**Comment by calixteman** [comment]
I just tried with Firefox 121 and 123 (nightly) on Fedora with Wayland and a lenovo laptop with a touch screen and it WFM but with X11 it doesn't work. That said maybe there is something to configure either in Firefox or in your system (or both) to enable the touch screen stuff with Firefox.
So as far as I can tell there's no problem on the pdf.js side.

**Comment by marek-lach** [comment]
> I just tried with Firefox 121 and 123 (nightly) on Fedora with Wayland and a lenovo laptop with a touch screen and it WFM but with X11 it doesn't work. That said maybe there is something to configure either in Firefox or in your system (or both) to enable the touch screen stuff with Firefox. So as far as I can tell there's no problem on the pdf.js side.

Just tested it under Wayland and yes, this seems to be only an x11 issue.
