### ISSUE TITLE
Type import error

### ISSUE THREAD

**Issue by vwkd** [mozilla/pdf.js#17535]
Importing types in Deno throws an error.

It seems the `/types/src/pdf.d.ts` file contains imports from a file `./shared/util.js` which doesn't exist.

### Configuration:
- Web browser and its version: deno 1.39.2
- Operating system and its version: macOS 14.2.1
- PDF.js version: 4.0.379
- Is a browser extension: no

### Steps to reproduce the problem:
1. Open REPL

```sh
deno repl -A
```

2. Import types

```ts
import * as Pdfjs from "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/types/src/pdf.d.ts";
```

### What is the expected behavior?

Types should import.

### What went wrong?

Throws an error

```txt
Uncaught TypeError: Module not found "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/types/src/shared/util.js".
    at https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/types/src/pdf.d.ts:8:32
    at async <anonymous>:1:36
```

**Comment by Snuffleupagus** [comment]
> Importing types in Deno throws an error.

Unfortunately that's not an environment that the PDF.js library supports; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
