### ISSUE TITLE
V4.0.379 throws a segmentation in AWS Lambda Node 18.x

### ISSUE THREAD

**Issue by dominicfarr** [mozilla/pdf.js#17538]
I'm attempting to use this package in an lambda but hitting some issues, most notably a segmentation error during initialisation.  

PDF.js version: 4.0.379
RTE: AWS Lambda Node 18.x

****LOG****

INIT_START Runtime Version: nodejs:18.v19	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:5
--
2024-01-19T11:04:02.792Z	undefined	INFO	Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
2024-01-19T11:04:02.805Z	undefined	INFO	Warning: Cannot polyfill `Path2D`, rendering may be broken.
INIT_REPORT Init Duration: 897.65 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
2024-01-19T11:05:10.066Z	undefined	INFO	Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
2024-01-19T11:05:10.067Z	undefined	INFO	Warning: Cannot polyfill `Path2D`, rendering may be broken.
INIT_REPORT Init Duration: 1244.42 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: signal: segmentation faultRuntime.ExitError
END 

****Usage****
package.json
``` json
  "dependencies": {
    "@aws-sdk/client-s3": "^3.188.0",
    "@aws-sdk/util-stream-node": "^3.188.0",,
    "pdfjs-dist": "^4.0.379"
  },
```
import
```JavaScript
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs'
```

It is the import statement that caused the errors, no library code is ever reached. 

Am I doing something wrong with the "strange" import? Or perhaps I can't use this library in node?

**Comment by Snuffleupagus** [comment]
> Or perhaps I can't use this library in node?

The PDF.js library can be used in Node.js, provided that *all* of the necessary NPM dependencies are correctly installed; please note https://www.npmjs.com/package/pdfjs-dist?activeTab=dependencies

Most likely "AWS Lambda" isn't automatically installing the dependencies, which we unfortunately cannot really help with; please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dominicfarr** [comment]
Just to say, I did try adding those dependencies, but still wasn't able to fix the seg fault. 

I have found a workaround
Dropped directly using pdfjs-dist 4.x and moving to pdf-text-reader.  
pdf-text-reader 4.0.1 depends on pdfjs-dist@3.9.179

I haven't tried directly using pdfjs-dist@3.9.179 [yet]
