### ISSUE TITLE
Need to restore the last PDF file page previously viewed when the Web page is opened. Is there a way to do this? Each time the Webpage containing the PDF.js container is opened, the PDF file is set back to the first page.

### ISSUE THREAD

**Issue by guitarmadness** [mozilla/pdf.js#17549]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
That should be the default behaviour, however given the *complete lack* of any details this is unfortunately not actionable.

---

*For future reference:* When opening an issue you need to actually fill out the ISSUE_TEMPLATE *properly* with all of the requested information in order for the issue to be actionable/valid.
Note also that the title should contain a *good summary* of the issue, however it's not really helpful to try and state your entire problem in the title.
