### ISSUE TITLE
JavaScript form function toFixed only displaying one digit in some cases

### ISSUE THREAD

**Issue by rtpt-romankarwacik** [mozilla/pdf.js#17540]
Attach (recommended) or Link to PDF file here:
[test.pdf](https://github.com/mozilla/pdf.js/files/13990875/test.pdf)

Configuration:
- Web browser and its version: Firefox 121.0.1
- Operating system and its version: Fedora 39
- PDF.js version: PDF.js: 4.0.240 [ffbfd680e]
- Is a browser extension: Yes? pdf.js it integrated into Firefox

Steps to reproduce the problem:
1. Open the attached PDF file
2. Type a number into the textfield

What is the expected behavior?
For example in Chromium or Okular the resulting Numbers have a fixed number of decimal digits (3):
![image](https://github.com/mozilla/pdf.js/assets/108284286/dc48fcf8-e940-48f1-9f6c-3a192c8e0fa8)

What went wrong?
In Firefox, only one decimal digit is shown for one value, while the other is properly displayed:
![image](https://github.com/mozilla/pdf.js/assets/108284286/f545ba26-c4c6-4061-b9d5-391211f287cb)

The underlying latex code used to produce the PDF:
```
\documentclass{article}
\usepackage{hyperref}

\begin{document}
\begin{Form}
\TextField[name=f1]{\null} $\cdot 0.3 =$
\TextField[calculate={
event.value = (parseInt(this.getField('f1').value) * 0.3).toFixed(3);
},readonly=true,name=f1calc]{\null}
\TextField[calculate={
this.getField('f1').value;
event.value = (0.33333).toFixed(3);
},readonly=true,name=f2calc]{\null}
\end{Form}
\end{document}
```

**Comment by Snuffleupagus** [comment]
The formatting seems to be clobbered at the following line, however I don't know what (if any) effect simply keeping all existing decimal places would have in the general case?
https://github.com/mozilla/pdf.js/blob/f8e3c79cb55daa0326da5b23e933fb92da5f95eb/src/scripting_api/field.js#L261

**Comment by calixteman** [comment]
Yep it's because we're using the `value` field which should be a number when it's a "number" in the `Calculate` process:
https://github.com/mozilla/pdf.js/blob/f8e3c79cb55daa0326da5b23e933fb92da5f95eb/src/scripting_api/event.js#L315
