### ISSUE TITLE
Cannot read properties of undefined (reading '_on')

### ISSUE THREAD

**Issue by farisshomali** [mozilla/pdf.js#17552]
Attach (recommended) or Link to PDF file here:

Configuration:

- PDF.js version: 4.0.379

Steps to reproduce the problem:
1.  Combining PDFjs with PdfAnnotate
2. Creating a pdfContainer causes the problem with event bus

What is the expected behavior? Creating the pdfContainer successfully 

What went wrong? 

![Screen Shot 2024-01-21 at 5 53 51 PM](https://github.com/mozilla/pdf.js/assets/61110881/853c8468-3184-4158-be9e-29dc0a9f09e5)
![Screen Shot 2024-01-21 at 5 54 18 PM](https://github.com/mozilla/pdf.js/assets/61110881/b76845fc-5b1b-4a25-8a3c-1e521d307265)

`function loadViewer() {
      let pdfContainer = document.getElementById('viewerContainer');

      pdfViewer = new pdfjsViewer.PDFViewer({
        container: pdfContainer,
      });

      pdfjsLib.getDocument('src/assets/pdfSample.pdf').promise.then((generatedDocument) => {
        pdfDoc = generatedDocument;
        const viewer = document.getElementById('pdf-viewer');
        for (let page = 1; page <= generatedDocument.numPages; page++) {
          let canvas = document.createElement("canvas");
          canvas.className = 'pdf-page-canvas';
          viewer.appendChild(canvas);
          renderPage(page, canvas);
        }

        generatedDocument.getData().then((data) => {
          pdfFactory = new AnnotationFactory(data);
        });
        pdfViewer.setDocument(generatedDocument)
        setTimeout(() => {
          pdfViewer.currentScaleValue = 'page-width';
        }, 1500)
      });

    }`

error occurs at this line  

  pdfViewer = new pdfjsViewer.PDFViewer({
        container: pdfContainer,
      });

**Comment by timvandermeij** [comment]
You need to pass an event bus instance; please see the example at https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.mjs#L66. Moreover, quoting from https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md:

> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, please prepare a short well-documented example that demonstrates the problem and make it accessible online on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- keep in mind that just code snippets won't help us troubleshoot the problem.
