### ISSUE TITLE
Obsolete repository link in the npm package metadata

### ISSUE THREAD

**Issue by msgx** [mozilla/pdf.js#17557]
### Problem overview

npm package metadata should be updated to reflect the current GitHub repository as a package source:

![obsolete-repo-link](https://github.com/mozilla/pdf.js/assets/7853057/be5ae02f-4a9e-44d1-adad-e846e955bc60)

### Steps to reproduce

1. Open the [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) package page at NPM Registry.
2. Review the **Repository** field.

### Expected behavior

The link should point to this repository.

**Comment by Snuffleupagus** [comment]
This is correct, since the NPM package contains the same exact code as found at https://github.com/mozilla/pdfjs-dist.

(Currently that repository isn't updating correctly, which is a *known* issue; refer to #17524.)
