### ISSUE TITLE
Javascript object default properties like `toString` are considered "valid" PDF operators

### ISSUE THREAD

**Issue by ThomasRinsma** [mozilla/pdf.js#17554]
Test case: [hello.pdf](https://github.com/mozilla/pdf.js/files/14002259/hello.pdf)

Configuration:
- Web browser and its version: **Firefox 122.0b5 (Ubuntu snap)**
- Operating system and its version: **Ubuntu 23.04**
- PDF.js version: **PDF.js: 4.0.347 [76e3e5202]**
- Is a browser extension: **no**

Steps to reproduce the problem:

1. Construct a PDF with a stream containing the token `toString` (see example linked above, line 35)

What is the expected behavior?

- Being an invalid operator, it should be ignored.

What went wrong?

![screenshot](https://github.com/mozilla/pdf.js/assets/3109710/dc075c73-1a16-4dd1-99ff-8fa29cb84356)

Potential operator tokens are used as an index into a map (i.e. a standard Javascript object), where certain properties like `id` and `numArgs` are stored. The presence of an element in this map is checked as follows:

https://github.com/mozilla/pdf.js/blob/fce822cde0fb6bab1d976ffcad5623482e18d446/src/core/parser.js#L1289-L1292

(maybe also in other places, I am not super familiar with the codebase)

The problem is that `possibleCommands` (which seems to equal the result of [`opMap`](https://github.com/mozilla/pdf.js/blob/fce822cde0fb6bab1d976ffcad5623482e18d446/src/core/evaluator.js#L4778)) is a regular Javascript object with the `Object` prototype. This means that it has properties like `toString` and `__proto__`. Hence, in these cases `knownCommands[possibleCommand]` will not equal `undefined`, and the operator is assumed to be valid. This then results in an exception later on when further logic attempts to access this operator's properties.

Variants of such a bug could lead to security problems, but this specific one is pretty harmless. Nevertheless it is good to make use of null-prototype objects for cases like this, and/or use a different way of checking operator validity.

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this issue!

Out of curiosity, how was this found? Did you use a fuzzer, or manual code inspection, or something else?

**Comment by ThomasRinsma** [comment]
Great, happy to help!

It was actually found manually/blackbox. When I come across enum-looking things being parsed by Javascript I like to try this trick :)
