### ISSUE TITLE
PDF file when reopened goes to the 1st page instead of returning to the previously viewed page.

### ISSUE THREAD

**Issue by guitarmadness** [mozilla/pdf.js#17559]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 120.0.6099.225
- Operating system and its version: MS Windows 10 pro 10.0.19045 Build 19045
- PDF.js version: 2.1.8
- Is a browser extension:
I'm developing the Website with WordPress and have installed the PDF.js plugin on the webpage shown below.
Steps to reproduce the problem:
1. Go to the guitarmadnessmethod.com/pdfjs test page and page down the PDF file to any page
2. Close the page, go back to the same website as above and notice the PDF file is set back to the first page

What is the expected behavior? (add screenshot)
PDF file would display the last viewed page
What went wrong? (add screenshot)
The PDF file displays the first page of the file
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
guitarmadnessmethod.com/pdfjs test

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.1.8

That's not an official release and furthermore that version must be many years old; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I'm developing the Website with WordPress and have installed the PDF.js plugin on the webpage shown below.

Note that we have never developed any "WordPress plugin" in the PDF.js project, hence that must be third-party code that we unfortunately cannot provide any help/support for (since we know nothing about it).

Please contact the "WordPress plugin"-author for help/support instead.

> Go to the guitarmadnessmethod.com/pdfjs test page and page down the PDF file to any page

In the web-console that page logs the following, which is *another* PDF.js version number than you stated above (but still many years out-of-date and thus unsupported).
```
PDF b9e1b4a01eb82d4e8ef3152f64b252b4 [1.6 Adobe PDF Library 23.8.246 / Acrobat PDFMaker 23 for Word] (PDF.js: 2.6.347)
```

Even ignore the "WordPress plugin"-part, an entire viewer cannot be meaningfully debugged; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, note that you're not supposed to the default viewer as-is without modification; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by guitarmadness** [comment]
Hi Jonas,
Below is the description  of the PDF.js Viewer from the WordPress site:
https://wordpress.com/plugins/pdfjs-viewer-shortcode

   - Is this a different group and product than what you are associa
   <https://wordpress.com/plugins/>ted with?

[image: plugin-icon]
PDF.js Viewer
By Ben Lawson, Thomas McMahon
<https://wordpress.com/plugins/?s=developer:%22Ben%20Lawson,%20Thomas%20McMahon%22>
·
embed
<https://wordpress.com/plugins/browse/embed/>
pdf
<https://wordpress.com/plugins/browse/pdf/>
pdf.js
<https://wordpress.com/plugins/browse/pdf-js/>
Embed a beautiful PDF viewer into pages.
Ratings
4.4
Last updated
January 10, 2023
Version
2.1.8
Active installations
20K
This plugin hasn’t been tested with the latest 3 major releases of WordPress.
It may no longer be maintained or supported and may have compatibility
issues when used with more recent versions of WordPress. Try searching
<https://wordpress.com/plugins/> for a similar plugin.

   - Description
   - Installation
   - Changelog

[image: PDF.js Viewer]

Incorporate Mozilla’s PDF.js
<https://github.com/mozilla/pdf.js/?referrer=wordpress.com> viewer into
your pages and posts via a Gutenberg block or a simple shortcode. PDF.js is
a javascript library for displaying pdf pages within browsers.

Features:

   - Gutenberg Block and Shortcode
   - Elegant Theme that adapts to dark and light mode (if browser supports
   dynamic CSS)
   - Customizable buttons
   - Page navigation drawer
   - Search functionality
   - Protected PDF password entry
   - Loading bar & displays partially loaded PDF (great for huge PDFs!)
   - Document outline
   - Zoom settings
   - Classic Editor: Easy to use editor media button that generates the
   shortcode for you
   - Support for mobile devices


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
