### ISSUE TITLE
embedPdf returns the PDF sections

### ISSUE THREAD

**Issue by RGerhardt-Pressmind** [mozilla/pdf.js#17551]
I wanted to merge 2 PDF files into one PDF file for my project. The challenge was to place the two PDF files next to each other.

In doing so, embedPdf with drawPage caught my eye. I noticed that embedPdf returns the PDF with the bleed hidden and in A4. It cuts something off the top and right of the PDF to display the bleed at the bottom and left.

My question is whether you can hide the bleed again or whether you can at least say, give me the whole PDF back and don't cut it to A4, then I can fix it later with drawPage:

```typescript
const [rightPage] = await mergePdf.embedPdf(pdfDoc, [0]);

newPage.drawPage(rightPage, {
  x: widthSites,
  y: 0,
  width: widthSites,
  height: heightSites,
});
```

Error pdf by merge with the function embedPdf
![error_pdf](https://github.com/mozilla/pdf.js/assets/69625642/842fbf97-d638-4932-8854-2adae085e6eb)

Normal A4 PDF without cuts
![normal_pdf](https://github.com/mozilla/pdf.js/assets/69625642/48fac5ea-50b9-48b6-a439-33a5d960a6aa)

**Comment by Snuffleupagus** [comment]
It seems that you accidentally opened this issue against the wrong project, since we don't support arbitrary PDF editing and the code mentioned above include functions that don't exist in the PDF.js code-base.

*For future reference:* Please don't ignore the ISSUE_TEMPLATE when opening an issue.
