### ISSUE TITLE
Rendering issues at certain scales

### ISSUE THREAD

**Issue by PSPvZ** [mozilla/pdf.js#17566]
Attach (recommended) or Link to PDF file here:

[BGWW - Factuur Termijn Spec (WS) (ac11704).pdf](https://github.com/mozilla/pdf.js/files/14022641/BGWW.-.Factuur.Termijn.Spec.WS.ac11704.pdf)

Configuration:
- Web browser and its version:
  - Microsoft Edge v120.0.2210.144
  - Google Chrome v120.0.6099.225
- Operating system and its version:
  - Windows 10.0.19045 Build 19045
- PDF.js version:
  - PDF.js v4.0.379
- Is a browser extension:
  - No

Steps to reproduce the problem:
1. Open the supplied PDF in the PDF.js viewer on an Edge/Chrome browser (possibly any Chromium-based browser)
2. Set the zoom to "Automatic Zoom"
3. Resize the browser so that the displayed PDF changes in size

What is the expected behavior? (add screenshot)

![expected](https://github.com/mozilla/pdf.js/assets/3479722/ceb44db7-da9b-4a7e-8366-8bad6c8b242a)

What went wrong? (add screenshot)

At certain scales, different parts of the text will disappear and reappear.

![comparison](https://github.com/mozilla/pdf.js/assets/3479722/e44a9e41-3fb2-47a7-8dd2-f649f356579b)

**Comment by Snuffleupagus** [comment]
This unfortunately suggests a *browser bug*, hence you'll need to report this to the Chromium developers instead.

It *may* be another case where Hardware Acceleration of canvas rendering breaks things, you can try disabling that in about:flags and see if it helps (that might be relevant information when reporting this to the Chromium devs).

**Comment by PSPvZ** [comment]
I had already feared as much, but I couldn't be certain. I submitted the report here as you might be able to easily determine whether it was an underlying problem in the chromium engine or a bug in PDF.js.

I have filed a bug-report with Chromium: [https://bugs.chromium.org/p/chromium/issues/detail?id=1520835](https://bugs.chromium.org/p/chromium/issues/detail?id=1520835)

**Comment by PSPvZ** [comment]
We have received some additional information. The supplied PDF uses the "Forma DJR Text Light 10" font. If we generate the same PDF but with "Arial", there are no issues. Could this affect the status of this report? Or is it likely still a browser bug?

Also, do you know of any workarounds that we could implement that can prevent this issue? Even if they fixed it in Chromium, it would still be a few months before that change would propagate to our software.
