### ISSUE TITLE
Some PDF documents filling out checkboxes regardless of whether it is actually checked or not.

### ISSUE THREAD

**Issue by adarshmathumal** [mozilla/pdf.js#17579]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox(121.0.1 )
- Operating system and its version: windows 11
- PDF.js version: v4.0.379
- Is a browser extension: 

Steps to reproduce the problem:
Open the sample document with pdf.js .  For page numbers 3 and 4, all checkboxes are filled regardless of whether it is actually checked or not.

What is the expected behavior? (add screenshot) :
Only selected checkboxes should be filled when opened.

What went wrong? (add screenshot) :
All checkboxes are filled regardless of whether it is actually checked or not.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that this part of the ISSUE_TEMPLATE is *always necessary* in order for an issue to be actionable/valid.
