### ISSUE TITLE
Default page labels are displayed for PDF files that specify empty string page labels for all pages

### ISSUE THREAD

**Issue by ed0d2b2ce19451f2** [mozilla/pdf.js#17573]
Attach (recommended) or Link to PDF file here:
[1.pdf](https://github.com/mozilla/pdf.js/files/14042349/1.pdf)

Configuration:
- Web browser and its version:  Firefox 121.0.1
- Operating system and its version:  Windows 10
- PDF.js version:  The version included with browser.  Maybe 4.0.240?
- Is a browser extension:  No?

What is the problem?
Default page labels are displayed for PDF files that specify empty string page labels for all pages.

Steps to reproduce the problem:
1. Open the attached PDF file which specifies empty string page labels for all pages.

What is the expected behavior?
Page input field in the PDF.js toolbar is blank for all pages.  Text to the right of the page input field is `(1 of 2)` for the first page and `(2 of 2)` for the second page.

What went wrong?
Page input field in the PDF.js toolbar contains `1` for the first page and `2` for the second page.  Text to the right of the page input field is `of 2`.

**Comment by Snuffleupagus** [comment]
This is done *on purpose*, since having the page-number input be completely blank doesn't seem particularly helpful; please note https://github.com/mozilla/pdf.js/blob/ae627870801eb758180e1db0c51b5a778c61af7a/web/app.js#L1590-L1607
