### ISSUE TITLE
pdf not rendering please see attachment for error

### ISSUE THREAD

**Issue by vikaskumarsdlv** [mozilla/pdf.js#17584]
i download zip code from github and extract zip file in my htdocs folder and path of my server http://128.0.0.67/pdf.js-master/web/viewer.html
then no pdf file is rendered. please see attachement. 
![pdfjs](https://github.com/mozilla/pdf.js/assets/80539085/32272345-aef2-4d20-9c4c-c48756e4b60c)

**Comment by Snuffleupagus** [comment]
Duplicate of #17575
