### ISSUE TITLE
Getting TypeError: Cannot read properties of null (reading 'getDocument') when using pdfjsdist from CDN in supabase edge function (deno)

### ISSUE THREAD

**Issue by shivamsaboo17** [mozilla/pdf.js#17595]
Steps to reproduce the problem:
My code looks like this which will be deployed as edge function in supabase

```
// Follow this setup guide to integrate the Deno language server with your editor:
// https://deno.land/manual/getting_started/setup_your_environment
// This enables autocomplete, go to definition, etc.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import pdfjsDist from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/+esm'
import { readerFromStreamReader } from "https://deno.land/std@0.93.0/io/mod.ts";

Deno.serve(async (req: Request) => {

  const payload = await req.json();
  console.log(JSON.stringify(payload, null, 2));

  const pdfUrl = payload.record.cv_link

  const pdfBuffer = await (await fetch(pdfUrl)).arrayBuffer();
  
  console.log(pdfBuffer)

  var myData = new Uint8Array(pdfBuffer); //put it in a Uint8Array

  console.log("converted to uint array")
  
  const doc = await pdfjsDist.getDocument(myData).promise

  console.log("got document")

  const page = await doc.getPage(1)

  console.log("page read")

  const text = await page.getTextContent()

  console.log("got text")

  console.log(text)

  return new Response(JSON.stringify({ payload }), {
    headers: { 'Content-Type': 'application/json' },
    status: 200,
  })

})
```

The error I get is
```
TypeError: Cannot read properties of null (reading 'getDocument'
```

My use case is rather simple, just need to get text from pdf from a url

**Comment by nicolo-ribaudo** [comment]
Use `import * as pdfjs`

**Comment by Snuffleupagus** [comment]
Please note that "Deno" is not a supported environment, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and note also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by lewisdonovan** [comment]
Considering the proliferation of Supabase, and the fact that their Edge Functions all run on Deno and you can't eject out of it, do you think this might be worth another look @Snuffleupagus?
