### ISSUE TITLE
Exception with GenericL10n fallback

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#17609]
STR:
 - run `gulp server`
 - open http://localhost:8888/web/viewer.html?file=/test/pdfs/tracemonkey.pdf

There's an exception:
```js
Uncaught (in promise) Error: Not Found
    fetchData http://localhost:8888/src/display/display_utils.js:414
    #createBundleFallback http://localhost:8888/web/genericl10n.js:115
    #generateBundles http://localhost:8888/web/genericl10n.js:79
    touchNext http://localhost:8888/node_modules/cached-iterable/src/cached_async_iterable.mjs:63
    onChange http://localhost:8888/node_modules/@fluent/dom/esm/localization.js:164
    onChange http://localhost:8888/node_modules/@fluent/dom/esm/dom_localization.js:40
    Localization http://localhost:8888/node_modules/@fluent/dom/esm/localization.js:21
    DOMLocalization http://localhost:8888/node_modules/@fluent/dom/esm/dom_localization.js:22
    GenericL10n http://localhost:8888/web/genericl10n.js:50
    createL10n http://localhost:8888/web/genericcom.js:42
    initialize http://localhost:8888/web/app.js:213
    run http://localhost:8888/web/app.js:588
    webViewerLoad http://localhost:8888/web/viewer.js:209
    <anonymous> http://localhost:8888/web/viewer.js:220
display_utils.js:414:13
```

the URL:
https://github.com/mozilla/pdf.js/blob/master/web/genericl10n.js#L116
is wrong: there's no `en-us` (but there's `en-US`) under the `locale` directory.

@Snuffleupagus could you have a look please ?

**Comment by Snuffleupagus** [comment]
> There's an exception:
> [...]

In my testing the viewer still *loads*, despite errors during L10n-init; can you confirm that?

> https://github.com/mozilla/pdf.js/blob/master/web/genericl10n.js#L116
> is wrong: there's no `en-us` (but there's `en-US`) under the `locale` directory.

The only way that we should be able to reach that line is if the `web/locale` folder is empty/missing, in which case there's no locale-data to load anyway.
Given that this only concerns a fallback code-path in *development mode*, perhaps we should just hard-code to URL to point at https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/viewer.ftl instead?

**Comment by calixteman** [comment]
> In my testing the viewer still loads, despite errors during L10n-init; can you confirm that?

Yep everything is loading correctly.

> Given that this only concerns a fallback code-path in development mode, perhaps we should just hard-code to URL to point at https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/viewer.ftl instead?

I'm fine with this solution.
Another possibility would be to lowercase everything (when generating the directories). Do you know if it's possible to have different locales but with the same lowercase names ?

**Comment by Snuffleupagus** [comment]
> Do you know if it's possible to have different locales but with the same lowercase names ?

While I don't believe so, I'm not sure. Hence it's difficult for me to tell if anything could "break" if we change this.

Although, please keep in mind that we're simply importing those folders (and files) as-is from mozilla-central and we *might* thus run into trouble if the default locale directory is named `en-us` in the GitHub repo but `en-US` in the mozilla-central repo?
