### ISSUE TITLE
How to read PDF files and get images, text or other data inside PDF files?

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [mozilla/pdf.js#17612]
I haven't looked at the source code, I'm making suggestions as a user.

Configuration:
- Web browser and its version: Google Chrome 121.0.6167.86
- Operating system and its version: Windows10 x64
- PDF.js version: 4.0.379
- Is a browser extension: No, it's Github Page.

How to extract text, images or other data inside a PDF file, I don't want to use Canvas rendering, I want to use html5 tags to render it out, I don't want to use Web Viewer.

--- deepl translator.

**Comment by Snuffleupagus** [comment]
> I want to use html5 tags to render it out,

Sorry, but that's not supported.
