### ISSUE TITLE
监听不到webviewerloaded事件

### ISSUE THREAD

**Issue by lianluoo** [mozilla/pdf.js#17616]
你好 我尝试改变pdfjs工具栏的显示语言，但是怎么都监听不到webviewerloaded事件。
Configuration:
- Web browser and its version: chrome版本 121.0.6167.140（正式版本） （64 位）
- Operating system and its version: Windows 10 企业版 LTSC 21H2
- PDF.js version: pdfjs-4.0.379 
 
Steps to reproduce the problem:
1. 在web/viewer.html中添加script标签
```javascript

<script>

      document.addEventListener("webviewerloaded", function() {
        console.log('webviewerloaded')
        PDFViewerApplicationOptions.set("locale", "en-US")
      });
    
</script>

```
 控制台中并未输出‘webviewerloaded’

**Comment by lianluoo** [comment]
使用parent.document.addEventListener就可以
```javascript
    <script>

      parent.document.addEventListener("webviewerloaded", function() {
        console.log('webviewerloaded')
        PDFViewerApplicationOptions.set("locale", "en-US")
      });
    
    </script>
```

**Comment by Snuffleupagus** [comment]
Please note that you need to communicate *only* in English when using this bug tracker.
