### ISSUE TITLE
Punctuation gets copied apart from text. Some text gets copied in gibberish

### ISSUE THREAD

**Issue by Drugoy** [mozilla/pdf.js#1762]
Well, actually I've already reported this issue to Bugzilla: as <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=758901">bug 758901</a>.
Copy-paste from there:
Example pdf file

Here is an example file: http://www.nbuv.gov.ua/portal/soc_gum/Uproz/2011_1/u1101nik.pdf

1. Just try to open it using pdf.js and Adobe Reader for comparison.
2. Hit CTRL+A, CTRL+C and then CTRL+V it to notepad.
3. Compare the output for pdf.js and Adobe Reader.

Actual results:
pdf.js copies the text like this:
<pre>Перед планированием рекламной кампании одной из самых важных задач является
опре
-
деление
    ,   " "  .      ,   
целевой аудитории написание портрета потребителя Любая фирма осознает что ее
 
            .         
товары не могут нравиться сразу всем покупателям Каждая компания должна выявить наиболее
 
    ,            .   
привлекательные сегментырынка которыеонавсостоянииэффективнообслужить Продавцыне
 
      .              :
всегдапридерживалисьэтойпрактики Взглядынаданнуюпроблемупрошлитриэтапа</pre>

Expected results:
pdf.js should copy the text like Adobe Reader does, like this:
<pre>Перед планированием рекламной кампании одной из самых важных задач является опре-
деление целевой аудитории, написание "портрета" потребителя. Любая фирма осознает, что ее
товары не могут нравиться сразу всем покупателям. Каждая компания должна выявить наиболее
привлекательные сегменты рынка, которые она в состоянии эффективно обслужить. Продавцы не
всегда придерживались этой практики. Взгляды на данную проблему прошли три этапа:</pre>

Also, take a look at the bottom of any page in that file: there is written the following (in bold different font):
<pre>"Управління розвитком"</pre>
in pdf.js it gets copied in gibberish:
<pre>"
Oi?aae?iiy ?icaeoeii
"</pre>

**Comment by timvandermeij** [comment]
@Drugoy The link appears to be dead. Do you have a new one?

**Comment by Drugoy** [comment]
@timvandermeij 
The current link redirects me to <a href="http://www.irbis-nbuv.gov.ua/cgi-bin/irbis_nbuv/cgiirbis_64.exe?C21COM=F&I21DBN=UJRN&P21DBN=UJRN&S21CNR=20&Z21ID=soc_gum/Uproz/2011_1/u1101nik.pdf">this page</a>.
Ctrl+u there and then Ctrl+f for any ".pdf" and you'll get some results like <a href="http://nbuv.gov.ua/sites/default/files/basicpage_files/201401_basicpage_files_mat/mon1111.pdf">this</a> and <a href="http://nbuv.gov.ua/sites/default/files/basicpage_files/201503_basicpage_files_mat/journal_memory.pdf">that</a>.
