### ISSUE TITLE
PDF Viewer is not localized in Firefox for Android

### ISSUE THREAD

**Issue by flodolo** [mozilla/pdf.js#17623]
Tested on a current Nightly in Italian, and the button at the top are displayed in English.

We should be already packaging the translations, since this is part of toolkit, so this might be a problem with the code loading the translations.

**Comment by flodolo** [comment]
On second thoughts, are we not including the Fluent file `toolkit/pdfviewer/viewer.ftl` in GeckoView?
https://searchfox.org/mozilla-central/source/mobile/android/locales/jar.mn#35-55

CC @eemeli

**Comment by eemeli** [comment]
Agreed, I'm pretty sure this should be a bugzilla bug.

**Comment by flodolo** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1878572
