### ISSUE TITLE
Some PDF documents filling out checkboxes regardless of whether it is actually checked or not.

### ISSUE THREAD

**Issue by adarshmathumal** [mozilla/pdf.js#17631]
Attach (recommended) or Link to PDF file here:
[5._without_signature_rendering.pdf](https://github.com/mozilla/pdf.js/files/14179036/5._without_signature_rendering.pdf)

Configuration:
- Web browser and its version: Firefox(121.0.1 )
- Operating system and its version: windows 11
- PDF.js version: v4.0.379
- Is a browser extension:

Steps to reproduce the problem:
Open the sample document with pdf.js . For page numbers 3 and 4, all checkboxes are filled regardless of whether it is actually checked or not.

What is the expected behavior? (add screenshot)

Only selected checkboxes should be filled when opened in viewer.

![Screenshot 2024-01-25 at 5 37 17 PM](https://github.com/mozilla/pdf.js/assets/157715551/4de7db35-1c1a-4431-a356-e5f313ffbd81)

What went wrong? (add screenshot)

All checkboxes are filled regardless of whether it is actually checked or not.

![Screenshot 2024-01-25 at 5 36 52 PM](https://github.com/mozilla/pdf.js/assets/157715551/c81d374e-f213-4b06-b6bd-f0fb35ad4c67)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Below is a screen-shot from Adobe Reader, i.e the PDF reference implementation (after manually enabling editing since it's a `PDF/A` document). Hence this looks like a bug in the PDF document *itself* and not in the PDF.js library.

![adobe](https://github.com/mozilla/pdf.js/assets/2692120/5a52755c-0ef9-41fb-8bd0-b668332ec957)
