### ISSUE TITLE
Some characters are not displayed / rendered.

### ISSUE THREAD

**Issue by Docota-GmbH** [mozilla/pdf.js#17671]
When we create simple and complex pdfs with Oracle Outside in Technology, we get pdfs as a result where some characters will not be displayed in pdf.js. But rendering / displaying these pdfs in Adobe Acrobat Reader and other web pdf viewer works fine.

Attached you will find a simple Excel converted to pdf with the text: Das ist ein Test
The t is missing , but text layer is working.

[Mappe123.pdf](https://github.com/mozilla/pdf.js/files/14277861/Mappe123.pdf)

Configuration:
- Web browser and its version:
Microsoft Edge (Chromium) Windows Version 121.0.2277.112, Chrome (Mac OS) Version 121.0.6167.160

- Operating system and its version:
Windows 11, MacOS 14.2.1

- PDF.js version:
PDF.js: 4.1.181 and PDF.js: 4.0.379

- Is a browser extension:
no

Steps to reproduce the problem:
1. open attached pdf in pdf.js
2. compare displaying result with adobe acrobat reader (and other)

What is the expected behavior? (add screenshot)
![expecteddisplay](https://github.com/mozilla/pdf.js/assets/113769563/a51dd847-2321-40c3-95e5-1fb8a3f177b3)

What went wrong? (add screenshot)
![result](https://github.com/mozilla/pdf.js/assets/113769563/0c9e0fc4-b82c-4389-b8c0-cc02614acb02)

**Comment by calixteman** [comment]
`ttx` is unhappy with the font:
```
ERROR: An exception occurred during the decompilation of the 'glyf' table
Traceback (most recent call last):
  File "/home/calixte/.local/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 470, in _readTable
    table.decompile(data, self)
  File "/home/calixte/.local/lib/python3.8/site-packages/fontTools/ttLib/tables/_g_l_y_f.py", line 109, in decompile
    raise ttLib.TTLibError("not enough 'glyf' table data")
fontTools.ttLib.TTLibError: not enough 'glyf' table data
```
and in trying to open the font in `fontforge` I get an error for glyph 9 (`its data length is negative`) and the glyph maps to the missing `t`.
