### ISSUE TITLE
When editor in iframe changes style of parent/body

### ISSUE THREAD

**Issue by Osiris-Team** [mozilla/pdf.js#17683]
![image](https://github.com/mozilla/pdf.js/assets/59899645/f6e64cc5-2c0f-43ca-93b3-91bbbd04087d)

It shouldn't affect the style of the parent. Code:
```html
<iframe src="https://mozilla.github.io/pdf.js/web/viewer.html" sandbox="allow-same-origin allow-scripts allow-forms allow-popups allow-modals allow-orientation-lock allow-pointer-lock allow-presentation"
                ></iframe>
```

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this unfortunately lacks the necessary details in order to be actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by Osiris-Team** [comment]
Thanks for the info. I didnt think this was such a complex problem that it required filling out all that info of the issue template.

**Comment by Snuffleupagus** [comment]
> I didnt think this was such a complex problem that it required filling out all that stuff in the issue template.

Unfortunately you've not really explained, in sufficient detail, what the problem actually is...

**Comment by Osiris-Team** [comment]
I thought that the styles in an iframe were completely separate from the ones in the parent element. Guess I was wrong, since when adding the pdf editor via an iframe it also changes the background color of the parent for example.
