### ISSUE TITLE
pdf显示报错‘Invalid PDF structure’

### ISSUE THREAD

**Issue by smile-hh123** [mozilla/pdf.js#17699]
Attach (recommended) or Link to PDF file here:
[RJM8L003D6P6.pdf](https://github.com/mozilla/pdf.js/files/14340487/RJM8L003D6P6.pdf)

Configuration:
- Web browser and its version:谷歌浏览器
- Operating system and its version: vue2项目, node:v16.20.2
- PDF.js version: 2.2.228
- Is a browser extension:

Steps to reproduce the problem:
1. 获取pdf地址
2.加载pdf文件进行显示

What is the expected behavior? (add screenshot)
pdf正确显示，没有报错信息

What went wrong? (add screenshot)
个别pdf显示报错
![image](https://github.com/mozilla/pdf.js/assets/160576470/5d6764ec-a0e0-4b72-820b-155429ae1021)
报asyncToGenerator.js:12 Uncaught (in promise) InvalidPDFException {name: 'InvalidPDFException', message: 'Invalid PDF structure', stack: 'Error\n    at InvalidPDFExceptionClosure (webpack:/…./node_modules/pdfjs-dist/build/pdf.js?:24618:30)'

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by smile-hh123** [comment]
相同的pdf用浏览器可以直接打开显示,使用库显示报Invalid PDF structure

**Comment by Snuffleupagus** [comment]
*Please note that you need to communicate __in English__ when using this bug tracker!*

> Attach (recommended) or Link to PDF file here:
> [RJM8L003D6P6.pdf](https://github.com/mozilla/pdf.js/files/14340487/RJM8L003D6P6.pdf)

WFM, when using an up-to-date version of the PDF.js library.

> Operating system and its version: vue2项目, node:v16.20.2

Neither of those are an operating system, and furthermore your Node.js version is too old: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 2.2.228

The version is almost *four years old*, and (obviously) no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
