### ISSUE TITLE
Pinch-zoom glitches on Safari iOS

### ISSUE THREAD

**Issue by extremegf** [mozilla/pdf.js#17713]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 16.7.4?
- Operating system and its version: iOS 16.7.4
- PDF.js version: v4.0.379
- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdfjs standard demo: [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Slowly zoom-in by pinching. See video.

https://github.com/mozilla/pdf.js/assets/1788593/f6693b0a-95f4-438f-833a-2557ea777491

**Comment by nicolo-ribaudo** [comment]
@extremegf If you are embedding pdf.js and thus you can add custom CSS, you can find a workaround in the description of https://github.com/mozilla/pdf.js/pull/17571.

**Comment by extremegf** [comment]
> Duplicate of #16155

Good catch. I should've search for this among the issues...

> @extremegf If you are embedding pdf.js and thus you can add custom CSS, you can find a workaround in the description of #17571.

Thank you so much! I really needed a solution.
