### ISSUE TITLE
[web/app.js] Remove the remaining `zoomDisabledTimeout` usage?

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17727]
With the primary use-case for the `zoomDisabledTimeout` functionality being removed in PR #17724, I wonder if we could get rid of the rest of this code now?
The remaining code was added in PR #10351 to work-around [bug 1503412](https://bugzilla.mozilla.org/show_bug.cgi?id=1503412), but without access to a Mac I cannot tell if we still need that and if so whether it's possible to refactor it to remove the `setTimeout`-based hack?

/cc @calixteman The following patch simply removes the affected code, would you be able to test it on Mac?
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:pdf.js:rm-setZoomDisabledTimeout

**Comment by calixteman** [comment]
Unfortunately, the bug is still there.
This is a Firefox issue and I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1882168.
