### ISSUE TITLE
Time/Date validation error message is confusing and has some broken formatting

### ISSUE THREAD

**Issue by dholbert** [mozilla/pdf.js#17721]
Attach (recommended) or Link to PDF file here:
[dsmv450.pdf](https://github.com/mozilla/pdf.js/files/14389404/dsmv450.pdf)
(Downloaded from https://www.dmv.nh.gov/sites/g/files/ehbemt416/files/inline-documents/dsmv450.pdf )

Configuration:
- Web browser and its version: Firefox 125.0a1 (2024-02-23) (64-bit)
- Operating system and its version: Ubuntu 22.04
- PDF.js version: whatever ships with current Firefox Nightly
- Is a browser extension: Yes (the one built-in to Nightly)

Steps to reproduce the problem:
1. Type `a` (or any non-date value) into the "Date of Expiration" field (near top-right) or "DATE" field (near bottom-right)
2. Press Tab to move focus out of that field.

What is the expected behavior?
A validation dialog should appear clearly explaining the problem.  Here's how this looks in Chrome's built-in PDF viewer, for reference:
![image](https://github.com/mozilla/pdf.js/assets/426803/404140f3-3203-433f-baab-e32cd32a9b1c)

What went wrong? (add screenshot)
The validation dialog that appears has several problems. Here's a screenshot, using the "Date of Expiration" field:
![image](https://github.com/mozilla/pdf.js/assets/426803/a78c4647-a2b4-4883-b8f0-f3b8e0f6b69b)
The popup says:
```
Invalid date / time: please ensure that the date / time exists.Field [ 
undefined_4 ] should match format mm/dd/yy
```
Problems:
- The initial part saying "please ensure that the date / time **exists**" is confusing for what is really a formatting problem rather than an existence problem.
- We're missing a space after the first sentence's period (so `exists.Field` looks quite broken/weird)
- The `Field [ undefined_4 ]` section is confusing/arcane (both due to the bracket usage and the "undefined" as part of the name -- I'm not sure if this is the field's actual label, vs. if it's just a label-with-an-increment that we apply to unlabeled fields, vs. something else).  Maybe in some cases it's useful to include the label, but it's not really helpful here.
- Maybe the message should end with a period? (if we can make it clear that the period isn't part of the mm/dd/yy syntax)

**Comment by Snuffleupagus** [comment]
Please note that we seem to be matching Adobe Reader, i.e. the PDF reference implementation:

![adobe](https://github.com/mozilla/pdf.js/assets/2692120/c3d2a93c-85c8-4e76-ad13-027462eeff9a)

**Comment by calixteman** [comment]
Yes when dumping `this.IDS_INVALID_DATE` in Acrobat console, I get: `Invalid date/time: please ensure that the date/time exists. Field`.
And the field name is really `undefined_4`:
<img width="277" alt="image" src="https://github.com/mozilla/pdf.js/assets/5641725/33a5d233-80b6-4251-8cbf-44c912d36b12">
That said we can at least fix the space after the dot.

**Comment by dholbert** [comment]
> Please note that we seem to be matching Adobe Reader, i.e. the PDF reference implementation:

That's interesting! I'd view this as a bug there as well, then. :)  It feels like we could stand to make the text more helpful than theirs here (and closer to Chrome's simpler message); but I suppose fixing the space is at least a step in the right direction -- thanks for doing that!
