### ISSUE TITLE
PDF doesn't display anything, complains about my pdf viewer

### ISSUE THREAD

**Issue by samth** [mozilla/pdf.js#1773]
This PDF http://www.northeastern.edu/hrm/pdfs/resources/benefits/MBTA-pretax-form-July2012.pdf produces the following error message as the contents of the pdf:

```
Please wait... 

If this message is not eventually replaced by the proper contents of the document, your PDF 
viewer may not be able to display this type of document. 

You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by 
visiting  http://www.adobe.com/products/acrobat/readstep2.html. 

For more assistance with Adobe Reader visit  http://www.adobe.com/support/products/
acrreader.html.
```

Neither Evince nor OS X Preview works either.

**Comment by DuncanGEMcMillan** [comment]
Solved!! I updated my Adobe Reader to the latest and greatest version using Chrome and getting the same message. 
I used Internet Explorer instead of Chrome and it opened up right away.

**Comment by Andsbf** [comment]
Apparently Adobe found a way to screw the nice standard "PDF". :(

**Comment by dbrisinda** [comment]
After upgrading to latest, which presumably would install the necessary plugins, these horrid XFA pdfs still don't load in Safari. My heartfelt wishes for a fast and painful death to Adobe.

**Comment by SegersIan** [comment]
The reason is simple. You need to launch this in the original Acrobat Adobe Reader, not 'in-browser'. 'In-browser' pdf reading is often a plugin or is 3th party rendering and does not support interactive elements. So the simple fix is, download locally the pdf and open it with the actual Acrobat Adobe Reader and not in browser or with another reader than the Adobe's one.

**Comment by emilianbold** [comment]
Sadly these XFA form PDFs can only be opened and printed from Adobe Reader.

My workaround is to use this printer driver on macOS https://github.com/emilianbold/PDFwriter and get Adobe to print to it. This produces a normal PDF that pdf.js / Preview can open.

**Comment by marco-c** [comment]
The forms appear to be working well now. @calixteman do you want to add them to reftests?
