### ISSUE TITLE
Use non-module version of pdfjs

### ISSUE THREAD

**Issue by jbutcher13930** [mozilla/pdf.js#17734]
I have a legacy application which cannot use modules

In Version  3.11.174 it is possible to use e.g. /pdfjs-dist/build/pdf.min.js

In version 4.0.379 also in legacy folder there are only .mjs file available e.g. /pdfjs-dist/legacy/build/pdf.min.mjs

Is this expected? Is it mandatory to use <script> with type="module" ? How could we use version 4 in this legacy application?

**Comment by Snuffleupagus** [comment]
> Is this expected? Is it mandatory to use <script> with type="module" ?

Yes, on both counts.

> How could we use version 4 in this legacy application?

Unfortunately you can't, unless you manually transpile the PDF.js code to older JavaScript.

---

Please note that JavaScript modules should be available in all browsers/environments that we support, see:
 - https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#legacy-build
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#browser_compatibility

**Comment by alaksandarjesus** [comment]
I am running on xampp for development and running on cpanel for production. I have the same issue and totally struck.

**xampp output**
![image](https://github.com/mozilla/pdf.js/assets/4712552/d03b83b3-f2fe-4efd-9ee3-7da02c009f64)

**cpanel output**

![image](https://github.com/mozilla/pdf.js/assets/4712552/93b578bf-d9c2-4e40-a570-045f16284ca1)
