### ISSUE TITLE
unable to decode Khmer language text

### ISSUE THREAD

**Issue by Ana0112** [mozilla/pdf.js#17731]
Attach (recommended) or Link to PDF file here:
[x1.pdf](https://github.com/mozilla/pdf.js/files/14406513/x1.pdf)

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Mac
- PDF.js version: "https://mozilla.github.io/pdf.js/build/pdf.js"
- Is a browser extension: using in html/js code

Steps to reproduce the problem:

```
const pdfDoc =  await pdfjsLib.getDocument(pdfPath).promise;
const page = await pdfDoc.getPage(1);
var texts = await page.getTextContent();
let w = texts.items;
let s = w[0].str;
console.log(s);

```

What is the expected behavior? (add screenshot)
<img width="230" alt="Screenshot 2024-02-26 at 8 54 02 PM" src="https://github.com/mozilla/pdf.js/assets/111160059/ceec91b1-952e-4314-a4a6-14ce3de41d55">

I was expecting `s` to contain text in the khmer language. How should I decode it, so that it should match with the output of `console.log(s)` . Currently, whenever I decode `s`, when I write `console.log(s)` in console it gives the correct khmer output. But when I write 's' only, it gives the encoded output as shown in the screenshot above.

**Comment by Snuffleupagus** [comment]
That's just how the string-representation works in JavaScript, for certain glyphs that cannot be displayed; this is *not* related to the PDF.js library.

**Comment by calixteman** [comment]
The ToUnicode dictionary of the font used to render the text is buggy.
For example the first word in the pdf starts with the following drawing instructions:
```
0 -64 Td <0001> Tj
8 0 Td <0002> Tj
22 0 Td <0003> Tj
0 0 Td <0004> Tj
...
```

and the ToUnicode map contains:
```
<0000> <0000> <0000>
<0001> <0001> <179A>
<0004> <0004> <1799>
```
so the first string starts with "\u179A\x02\x03\u1799".
There's exactly the same issue with Acrobat except they use `\u10002\u10003`, so unfortunately we can't help you.

**Comment by Ana0112** [comment]
ok, i dont understand this ..

but a noob question, how has `console.log` been able to decode it

**Comment by calixteman** [comment]
The console just uses some white spaces for `\x02`, `\x03` and `\x05`.

**Comment by Ana0112** [comment]
ah ok
 
I tried just simply replacing `\x02` etc with space in the console, but still got the encoded string

```
let q = s.replace(/\\x([0-9A-Fa-f]{2})/g, '') 
q
```

output i got
`'រ\x02\x03យ\x05\x03រណ៍គណនី'`
