### ISSUE TITLE
Why is it much more difficult to select vertical annotations in mechanical drawings from top to bottom than from bottom to top, and it is even impossible to select all of them at all?

### ISSUE THREAD

**Issue by ouleioulei** [mozilla/pdf.js#17741]
I don’t know the version of pdf.js. I just remember that it was in the compressed file downloaded at https://github.com/mozilla/pdf.js on October 23, 2023. I ran pdf.js-master/web /viewer.html, and then open my pdf file. However, when selecting (as shown in the screenshot), I encountered the problem that "for vertical annotations in mechanical drawings, it is much more difficult to select from top to bottom than from bottom to top, and you cannot select all of them at all." This is very useful for It is not very user-friendly (a truly friendly interaction should be that it should be equally easy to select content no matter which direction you look at), so I would like to ask if anyone has any way to solve this problem?
![20240228185507](https://github.com/mozilla/pdf.js/assets/34880715/db6e2b65-4c66-4bc9-9a19-cf82e9a1d40b)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is missing too much of the necessary information in order to be actionable/valid.
