### ISSUE TITLE
'minified' and 'minified-legacy' builds don't include web/cmaps anymore

### ISSUE THREAD

**Issue by mnj1004** [mozilla/pdf.js#17749]
Configuration:
- PDF.js version: v4.0.379

Steps to reproduce the problem:
1. Clone git repo and checkout a branch 'tags/v4.0.379'
2. Build `minified` or `minified-legacy`

What is the expected behaviour?
web/cmaps folder exists in the build

What went wrong?
web/cmaps folder is missing

Individuals or organizations may choose to build pdf.js from its source code for security or other specific reasons. However, there is an issue with the `minified` version: it lacks the necessary ‘cmaps’. As a result, our application cannot properly display multibyte characters for our customers. We kindly request that you address this by restoring the ‘cmaps’.

**Comment by Snuffleupagus** [comment]
> What went wrong?
> web/cmaps folder is missing

That's the expected behaviour, given that we don't build a minified viewer anymore.

If you need the CMap files (or the standard font files), those can be still be built as part of e.g. `gulp generic` and thus obtained from the `build/generic/web/cmaps` directory.
