### ISSUE TITLE
Helvetica font on windows machine mapping issue

### ISSUE THREAD

**Issue by TangMichael** [mozilla/pdf.js#17751]
Configuration:
- Web browser and its version: chrome 120
- Operating system and its version: windows 10
- PDF.js version: pdfjs-dist 3.6.172

Steps to reproduce the problem:
1. Loading document on windows machine

What is the expected behavior? (add screenshot)

font should be displayed properly

What went wrong? (add screenshot)

This is the pdf on adobe

![Screenshot 2024-02-28 at 5 54 05 PM](https://github.com/mozilla/pdf.js/assets/25641760/a154f215-9a33-4113-b24c-7558ac826b44)

This is the result when I upload the pdf on my app with react-pdf
![Screenshot 2024-02-28 at 5 53 50 PM](https://github.com/mozilla/pdf.js/assets/25641760/0783cda7-f448-4fc5-9494-0af3e992f046)

font property
![Screenshot 2024-02-28 at 5 54 27 PM](https://github.com/mozilla/pdf.js/assets/25641760/bc63bf1c-e70d-493a-926b-21e15e7e0db6)

font mapping seems weird. Is this a computer issue or is there some mapping between fonts not working properly on specific machine with windows.

This only happens for certain users on windows 10. I was not able to reproduce personally. I've asked on the [react-pdf github](https://github.com/wojtekmaj/react-pdf/issues/1684) too but could not get any answer. Perhaps somebody here would understand why this is happening?

**Comment by Snuffleupagus** [comment]
Unfortunately this issue isn't actionable in its current form, please keep in mind that the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is always required when opening an issue.

> PDF.js version: pdfjs-dist 3.6.172

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> This is the result when I upload the pdf on my app with react-pdf

Please keep in mind that "react-pdf" is not developed here, and while it may use the PDF.js library it's not something that we can provide help/support for.

**Comment by sergiubologa** [comment]
@TangMichael this looks to me like the same issue explained here: https://github.com/wojtekmaj/react-pdf/issues/1684#issuecomment-2175632912
