### ISSUE TITLE
A single page pdf is taking 4 min to render

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#17779]
Attach (recommended) or Link to PDF file here:
[p95.pdf](https://github.com/mozilla/pdf.js/files/14522359/p95.pdf)

Configuration:
- Web browser and its version: Firefox nightly
- Operating system and its version: Windows 11

Steps to reproduce the problem:
1. Open the pdf 
2. and wait...

It seems that the pdf contains a lot of paths outside the clip box and for each of them we call with a `null` argument:
https://github.com/mozilla/pdf.js/blob/6bb6ce6a5d133c5aa318e2fff9d1df5326a1ea96/src/display/canvas.js#L1788

which itself calls at some point:
https://github.com/mozilla/pdf.js/blob/6bb6ce6a5d133c5aa318e2fff9d1df5326a1ea96/src/display/canvas.js#L838

That said, the overall rendering is incorrect: the lines for the borders and some grayed countries are not rendered at all.

**Comment by Snuffleupagus** [comment]
Is the underlying issue here perhaps (partially) related to the fact that SMask handling is inefficient, given the use of `getImageData`/`putImageData` calls?
This is reminding me of https://github.com/mozilla/pdf.js/issues/14982#issuecomment-1466141810, which talks about possible alternatives.

**Comment by calixteman** [comment]
> Is the underlying issue here perhaps (partially) related to the fact that SMask handling is inefficient, given the use of `getImageData`/`putImageData` calls? This is reminding me of [#14982 (comment)](https://github.com/mozilla/pdf.js/issues/14982#issuecomment-1466141810), which talks about possible alternatives.

Yep, it's on my long todo list.

**Comment by marco-c** [comment]
Should we close this now that #18029 was merged?
