### ISSUE TITLE
Node-pakcage pdfjs-dist: DOMMatrix is not defined

### ISSUE THREAD

**Issue by z1glr** [mozilla/pdf.js#17789]
Attach (recommended) or Link to PDF file here: 
[issue_dommatrix.pdf](https://github.com/mozilla/pdf.js/files/14559750/issue_dommatrix.pdf)

Configuration:
- Web browser and its version: No browser, used through the node-package "pdfjs-dist" together with "node-canvas"
- Operating system and its version: Windows 10 Version 22H2 (Build 19045.4123)
- PDF.js version: 4.0.379
- Is a browser extension: no

Steps to reproduce the problem:
1. load the PDF through pdfjs.getDocument
2. create a Canvas
3. render with page.render

What is the expected behavior? PDF-page should render and be available as an image buffer for further processing. (Works with other PowerPoint-generated PDFS without tables)

What went wrong? Uncaught ReferenceError ReferenceError: DOMMatrix is not defined at getPattern (node_modules\pdfjs-dist\build\pdf.mjs:4805:25)

Additional information / ideas:
When I add `import { DOMMatrix } from "canvas";` at the top of `pdf.mjs`, it is working. (Of course this isn't a viable fix, but hopefully a hint)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Implementation is here: [johncg/src/server/SequenceItems/PDF.ts](https://github.com/johannesbuehl/johncg/blob/71f5876d93c20159b9c884cfc8f808eeb1a2a8aa/src/server/SequenceItems/PDF.ts) (starting at line 34, error appears at line 51)

**Comment by Snuffleupagus** [comment]
You need to import from the `legacy`-folder in Node.js environments; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
