### ISSUE TITLE
Checkbox selection missing after loading PDF

### ISSUE THREAD

**Issue by artstalker** [mozilla/pdf.js#17782]
Link to PDF file here: 
[Check box issue.pdf](https://github.com/mozilla/pdf.js/files/14534221/Check.box.issue.pdf)

It is reproducible in https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:

Web browser and its version: Firefox 123.0.1 (64-bit)
Operating system and its version: Windows 11 Pro 10.0.22631
PDF.js version: Latest (https://mozilla.github.io/pdf.js/web/viewer.html)
Is a browser extension: No
Steps to reproduce the problem:

1. Load PDF file
Actual result:
The checkboxes are selected
![image](https://github.com/mozilla/pdf.js/assets/2846956/85457de5-ba9a-45fc-b417-2272555fe974)

Expected results:
If you open PDF in any other PDF viewer, the No checkboxes are selected
![image](https://github.com/mozilla/pdf.js/assets/2846956/49f83647-073d-46be-94c1-a667070a8952)

**Comment by calixteman** [comment]
Weird, it wfm in Firefox 123.0.1 with either the built-in viewer or https://mozilla.github.io/pdf.js/web/viewer.html. 
Normally it has been fixed a while back:
https://github.com/mozilla/pdf.js/pull/17159
You can try in [Firefox nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#desktop-nightly-download).

**Comment by THausherr** [comment]
Also works for me, both FF 123.01 on Windows 10 and with viewer.html link.

**Comment by Snuffleupagus** [comment]
>     1. Load PDF file
>        Actual result:
>        The checkboxes are selected
>        ![image](https://private-user-images.githubusercontent.com/2846956/311140042-85457de5-ba9a-45fc-b417-2272555fe974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ1OTEsIm5iZiI6MTcwOTg5NDI5MSwicGF0aCI6Ii8yODQ2OTU2LzMxMTE0MDA0Mi04NTQ1N2RlNS1iYTlhLTQ1ZmMtYjQxNy0yMjcyNTU1ZmU5NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMTAzODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFkY2JjMTI3NDkxYzIyZTVlOGQ1MjRlZTExZDhkODNjMDdiNmI5MjRkYmI0MTVlZTJkZTU3NzlmYWM4ZTAwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-Fi7XqcWZ6D_yih748Cy9GJgW7k7R0gSfa-KI67PuII)

Is this image *actually* from the demo viewer, i.e. https://mozilla.github.io/pdf.js/web/viewer.html, since there's a border-shadow visible to the right of the page (something that the demo viewer doesn't have)?

**Comment by artstalker** [comment]
You are right; I am sorry for the confusion.

This issue is reproducible in Angular wrapper implementation https://pdfviewer.net/extended-pdf-viewer/forms
not in pdf.js itself.
