### ISSUE TITLE
PDF Document does not display text correctly when rendered in pdf.js

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#17808]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Mozilla any version
- Operating system and its version: Any Os, Tested on windows
- PDF.js version: 4.0.379
- Is a browser extension:

Steps to reproduce the problem:
1. Open the Attached PDF in https://mozilla.github.io/pdf.js/web/viewer.html
2. We see broken text in rendered document

What is the expected behavior? (add screenshot)
Text should be displayed correctly 
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by gstakhov** [comment]
[Document1.pdf](https://github.com/mozilla/pdf.js/files/14653301/Document1.pdf)

**Comment by calixteman** [comment]
It's a regression from #12259.
The font (which is symbolic) used to render the data has 3 cmap tables: 0,3; 1,0 and 3,1.
We don't select the correct table (i.e. 3,1) but selecting the 0,3 one is fine.

**Comment by mirnalinikarthik** [comment]
@calixteman Thank you for your quick response. We will wait for the issue to be fixed.
