### ISSUE TITLE
Structure Tree 

### ISSUE THREAD

**Issue by siddhesh8k** [mozilla/pdf.js#17804]
Hi All,
not able to get pdf structure tree for every page. 

Need to get structure tree for every pdf page. 

mostly observed that document created indesign etc , have problems. Works good if word file is converted to pdf.

Please provide the valid solution.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please note that *most* PDF documents don't include any structTree-data.

Also, if you ignore the entire ISSUE_TEMPLATE we cannot provide any help.
