### ISSUE TITLE
Lost data of annotationStorage using saveDocument function on xfa forms

### ISSUE THREAD

**Issue by NicoBaigorria** [mozilla/pdf.js#17815]
Attach (recommended) or Link to PDF file here: https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm1294e.pdf

Configuration:
- Web browser and its version: Nodejs
- Operating system and its version: Windows 10
- PDF.js version: 4.0.379
- Is a browser extension: 

Steps to reproduce the problem:
1. With xml form like the document linked try to populate any field using annotationStorage.setValue
2. Save the changes using saveDocument method
3. Without change the code any times the data is saved correctly and others not

What is the expected behavior? (add screenshot)

![image](https://github.com/mozilla/pdf.js/assets/56775102/b8883780-7099-4a53-bfb7-3ec38cc7e38c)

What went wrong? (add screenshot)

![image](https://github.com/mozilla/pdf.js/assets/56775102/5e2dd3f0-d277-406e-8e81-4d18515bd683)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

[imm1294e.pdf](https://github.com/mozilla/pdf.js/files/14668528/imm1294e.pdf)

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem: 
>     1. With xml form like the document linked try to populate any field using annotationStorage.setValue
>     2. Save the changes using saveDocument method
>     3. Without change the code any times the data is saved correctly and others not

It sounds from the above like you're not using the viewer, but some kind of *custom* code!?

Furthermore it's unfortunately not specified *exactly* what data, and how, you're attempting to add to the `annotationStorage`; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by NicoBaigorria** [comment]
Here is an example of the code, it simply does not save the changes or return an error approximately 49 out of 50 times

```
import fs from "fs";
import * as pdfjs from "pdfjs-dist/build/pdf.min.mjs";

async function readAndEditXFAWithAnnotations(pdfInputPath, outputPath, newData) {
    try {
        const pdf = await pdfjs.getDocument({ url: pdfInputPath, enableXfa: true });
        const pdfData = await pdf.promise;
        

        // Modify the data or annotations as needed
        // For example, update field values with newData
        for (const fieldName in newData) {
            console.log(fieldName, newData[fieldName])
            await pdfData.annotationStorage.setValue(fieldName, { value: newData[fieldName] });
        }

        // Save the modified PDF document
        const modifiedPdfBytes = await pdfData.saveDocument();
        await saveModifiedPdf(outputPath, modifiedPdfBytes);

        console.log("PDF saved successfully with updated XFA data and annotations.");
    } catch (error) {
        console.error("Error reading or editing PDF:", error);
    }
}

async function saveModifiedPdf(outputPath, modifiedPdfBytes) {
    try {
        const arrayBuffer = new Uint8Array(modifiedPdfBytes).buffer;
        await fs.promises.writeFile(outputPath, Buffer.from(arrayBuffer));
    } catch (error) {
        console.error("Error saving modified PDF:", error);
    }
}

// Usage example:
const pdfInputPath = "./src/InputFiles/imm1294e.pdf";
const outputPath = "./imm1294e.pdf";
const newData = {
    "Sex240558": "M Male",
    "FamilyName240550": "Tomas",
    // Add more field data as needed
};

readAndEditXFAWithAnnotations(pdfInputPath, outputPath, `newData);`
```

**Comment by calixteman** [comment]
The problem is that there is no element with data-id equals to `Sex240558` or `FamilyName240550`.
Those ids aren't public:
https://github.com/mozilla/pdf.js/blob/master/src/display/xfa_layer.js#L125-L129
that said if you want to know them you can just add something like:
```js
case "dataId":
  ...
  html.setAttribute("data-id", value);
```
