### ISSUE TITLE
Detect security (protection) options from PDF

### ISSUE THREAD

**Issue by croraf** [mozilla/pdf.js#17812]
[dummy_rafa (1).pdf](https://github.com/mozilla/pdf.js/files/14664385/dummy_rafa.1.pdf)

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: all
- PDF.js version: 4.0.379
- Is a browser extension: -

The attached document is protected (secured) to prevent copying. There are other protection options like prevent printing or prevent modification that can be imposed on a document.

pdfjs should allow detection of such options through its API.

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/blob/3718d0a9b477eb56f18f5af19b9c179a165af959/src/display/api.js#L986-L993 and https://github.com/mozilla/pdf.js/blob/3718d0a9b477eb56f18f5af19b9c179a165af959/src/shared/util.js#L96-L106
