### ISSUE TITLE
Pdf pages are trimmed (by width and by height)

### ISSUE THREAD

**Issue by croraf** [mozilla/pdf.js#17820]
I think any size are trimmed, but here I provide one custom page size
[pdf_size_test2.pdf](https://github.com/mozilla/pdf.js/files/14705392/pdf_size_test2.pdf)

Configuration:
- Web browser and its version: Chrome 122 and Firefox 123
- Operating system and its version: Linux Ubuntu 22
- PDF.js version:  4.0.379 
- Is a browser extension: - 

What is the expected behavior? (rendered in Chrome's built in viewer)
![image](https://github.com/mozilla/pdf.js/assets/19698636/e6f5863c-f9b1-4542-a0f8-bc55e46c4560)

What went wrong? (pdfjs render)
![image](https://github.com/mozilla/pdf.js/assets/19698636/840e800a-a08c-4cb0-93ff-fcef44705cf0)

It renders 560px width and 377.33px height, instead of 583.00px width and 393.00px height.

pdfjs inspect (scale factor 1.3333333333): (560px width and 377.33px height)
![image](https://github.com/mozilla/pdf.js/assets/19698636/c43f4747-9b99-4d53-a3a8-e9b5951b16ac)

Document properties from Chrome: (583.00px width and 393.00px)
![image](https://github.com/mozilla/pdf.js/assets/19698636/91e59649-b563-4643-87a6-39fff1f747b7)

**Comment by Snuffleupagus** [comment]
WFM, using the [demo viewer](https://github.com/mozilla/pdf.js#online-demo) in Firefox Nightly 126 on Windows 11:

![demo](https://github.com/mozilla/pdf.js/assets/2692120/f4bd4171-1246-4c3d-b756-288d9a782034)

> PDF.js version:  4.0.379
> What went wrong? (pdfjs render)

Your screen-shot shows a *much older* viewer, that's not consistent with the stated version number unfortunately.

---

First of all, please make sure that you use a supported version; see https://mozilla.github.io/pdf.js/getting_started/#download
Secondly, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by croraf** [comment]
PDF.js version is 4.0.379, but I'm using a custom implementation and I had some global css applied, namely `box-sizing: border-box`. 

I should have tested on your implementation, sorry about that.
