### ISSUE TITLE
Smaller package for nodejs by only including the legacy folder (and its dependencies) from pdfjs-dst

### ISSUE THREAD

**Issue by jcelmeta14** [mozilla/pdf.js#17822]
Configuration:
- Web browser and its version: Node.js 16 (running in the backend)
- Operating system and its version: AWS Lambad, probably Amazon Linux 2023 
- PDF.js version: 2.16.105
- Is a browser extension: No

First of all, thank you for this amazing package! 

I had a question about potentially making the package manually part before my app is deployed to AWS Lambda. Since I am using the legacy version, I had the idea of excluding some unused files manually. The reason is that AWS Lambda has a maximum size.

Using Dependency Cruiser, I tried to find the dependencies of the legacy. I get the following graph:

![image](https://github.com/mozilla/pdf.js/assets/22294784/1800fa4b-6be3-4020-996a-1ed514dc9275)

It looks like nothing from the `lib` folder is being imported/required in the files from the `legacy` folder.  I was hoping to exclude the entire `lib` folder, and some source map files. I think the problem that I have right now is that the files are not being correctly ignored by a plugin that I use for building my serverless functions (serverless-webpack)

Thank you!

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.16.105

That version is no longer supported, and the current version is `4.0.379` where this issue no longer exists; see https://www.npmjs.com/package/pdfjs-dist

*For future reference:* Please make sure that you always test with the *latest version* before opening an issue.
