### ISSUE TITLE
Error with 0 width / height shaders

### ISSUE THREAD

**Issue by rossj** [mozilla/pdf.js#17848]
I've come across some PDFs where pages are partially rendered in PDF.js but display fully in Acrobat & Chrome. These files appear to be CAD drawings converted to PDF format. The PDFs have a `Creator` value of `AcroPlot Pro (Build 2018-01-24) - www.cadzation.com` and a `Producer` of `PDF-XChange (xcpro40.dll v4.0.0316.0001) (Windows)`.

I've tracked the issue down to some problematic shaders in the page's `/Shading` resource dictionary. Specifically, there are some shaders that seem to have 0 width and/or 0 height, which causes a rendering error in PDF.js.

The relevant shader handling code is around here: https://github.com/mozilla/pdf.js/blob/841d57df462a19a4db8acfaa18ebe85269fb0c03/src/display/pattern_helper.js#L342

With these problematic shaders, any of boundsWidth / boundsHeight / width / height may be 0, and scaleX / scaleY can end up as `NaN`, with the eventual thrown error coming from `createImageData()`. Perhaps such shaders need to be detected & ignored during rendering.

Attach (recommended) or Link to PDF file here:
I've hand written a sample file that uses one of these problematic shaders:
[minimal - shader issue.pdf](https://github.com/mozilla/pdf.js/files/14765362/minimal.-.shader.issue.pdf)

Configuration:
- Web browser and its version: Chrome 123, Firefox 124
- Operating system and its version: Windows 11
- PDF.js version: 4.1, 4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the sample PDF
2. Notice error in browser console and lack of page content

What is the expected behavior? (add screenshot)
The document should show "Hello World"
![image](https://github.com/mozilla/pdf.js/assets/735679/f39e1c26-7552-4b6c-bedf-1c6323693bc9)

What went wrong? (add screenshot)
PDF.js shows a blank page with error in console
![image](https://github.com/mozilla/pdf.js/assets/735679/ac515fca-3d63-4d4f-bc83-e7734aa309d8)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by verma** [comment]
Thank you @rossj and @Snuffleupagus for raising and taking care of this issue. 🙏🏽 

I was wondering if it was possible to cut a release with this fix in?
