### ISSUE TITLE
Dispatching 'find' when clicking a button doesn't scroll the next occurrence into view.

### ISSUE THREAD

**Issue by raulsebastianmihaila** [mozilla/pdf.js#17853]
Configuration:
- Web browser and its version: Chrome 123.0.6312.58
- Operating system and its version: Ubuntu 22.04.4 LTS
- PDF.js version: 4.0.379
- Is a browser extension: no

I'm currently having an issue with the find operation, when clicking a button, in that if I want to find the next occurrence of the searched text, it is found, but the UI doesn't scroll to that new occurrence into view.

I'm using the pdf viewer form the pdfjs-dist npm package. I saw the presentation of the different layers on the Getting Started page (https://mozilla.github.io/pdf.js/getting_started/). If I understood correctly:
- the Display layer in the npm package is /build/pdf.mjs
- the Core layer in the npm package is /build/pdf.worker.mjs
- the Viewer layer in the npm package is /web/pdf_viewer.mjs + /web/pdf_viewer.css
However, on the Getting Started page it says that the Viewer layer is the UI for the PDF viewer in Firefox, meaning https://mozilla.github.io/pdf.js/web/viewer.html. I also looked at the prebuilt version, as presented on the Getting Started page, and it seems that the Viewer layer (in terms of html, css and js) is /web/viewer.html + /web/viewer.css + /web/viewer.js. However, the /web/viewer.js and /web/viewer.css files from the prebuilt version are different from the /web/pdf_viewer.mjs and /web/pdf_viewer.css files from the npm package. The Viewer files from the demo page seem to be https://github.com/mozilla/pdf.js/blob/master/web/viewer.js and https://github.com/mozilla/pdf.js/blob/master/web/viewer.css (in terms of js and css), and these seem to include the files from the /web dir from the npm package, but they also have extra code.

I see that the finding next occurrence operation works well in the demo website. I'm wondering if there is something that I'm doing wrong or if the operation depends on the part of the code that is only included in the demo version. I managed to display the PDF and the text is selectable. I'm using the PDFViewer class and I'm trying the find operation using `pdfViewer.eventBus.dispatch('find', {type: 'again', <query>})`. Another thing I noticed is that in my implementation, when the document is displayed, the container element (the one that I pass when I instantiate PDFViewer) has a scrollTop of 10px, which is equal to the top margin + top border of the page element of the first PDF page (the div with class 'page'), meaning the top edge of my container is aligned with the top of the white content area of the PDF page, while on the demo page, I see that the container element doesn't have any top scroll.

Please note I saw https://github.com/mozilla/pdf.js/issues/16090, but I'm doing the search (dispatching the 'find' operation) when clicking on a 'Find' button, so I don't get any error. The search works, meaning it finds the next occurrence every time, it's just that it doesn't scroll the new occurrence into view. It does scroll the page of that occurrence into view, but if the occurrence is outside of the viewport (my container is smaller than a page's height), the occurrence is not visible until manually scrolling to it. So does this work only on the demo page (prebuilt version), or is it supposed to work well with the npm package code too?

Thanks!

**Comment by Snuffleupagus** [comment]
Most likely you're running into issue #11626, and the easiest work-around is probably to place your custom PDF Viewer inside an `iframe`-element.

**Comment by raulsebastianmihaila** [comment]
@Snuffleupagus please note I do set position absolute and overflow auto on the container, so the issue you linked doesn't seem related. I tried multiple setups, including showing only the container on the page (and its children of course), as I have full control over the content. So this would be equivalent to using an iframe I suppose. And I still reproduce the issue. Can you please consider reopening the issue? Thanks!

**Comment by Snuffleupagus** [comment]
Searching *and* scrolling matches into viewer works correctly for me when testing the `simpleviewer` example locally; see https://github.com/mozilla/pdf.js/tree/master/examples/components

To reproduce that, follow *all* of the steps in https://github.com/mozilla/pdf.js?tab=readme-ov-file#getting-the-code and then edit (the local file) as suggested in the comment:
https://github.com/mozilla/pdf.js/blob/55db43966eaf99b1292ae913fe2ae3eae7d0e8ad/examples/components/simpleviewer.mjs#L36
and finally open http://localhost:8888/examples/components/simpleviewer.html in a browser.

Hence the conclusion is *unfortunately* that there's a bug in your code. Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
