### ISSUE TITLE
dead link on wiki

### ISSUE THREAD

**Issue by nico** [mozilla/pdf.js#17881]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-is-the-latest-stable-version-of-pdfjs says "The [generic viewer](http://mzl.la/pdf-js) always contains the latest PDF.js build and is available for testing." liking to `https://mozilla.github.com/pdf.js/web/viewer.html`. That's a 404, it should link to `https://mozilla.github.io/pdf.js/web/viewer.html` instead I'm guessing.

As far as I can tell, I don't have permissions to edit the wiki myself, so I'm filing this issue instead. Sorry for the overhead.

**Comment by timvandermeij** [comment]
Thank you for informing us about this. I have just amended the wiki page.
