### ISSUE TITLE
Feature Request Accept Another Link tag resource for localization

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#17899]
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: Chrome 123.0.6312.105
Operating system and its version: Mac OSX Sonoma 14.3.1
PDF.js version: 4.0.379'
Is a browser extension: No

This is a feature request. in viewer.js, only 1 linkn tag is retrieved with this code.

```
static async #getPaths() {
    const {
      href
    } = document.querySelector(`link[type="application/l10n"]`);
    const paths = await (0,pdfjs_lib__WEBPACK_IMPORTED_MODULE_2__.fetchData)(href, "json");
    return {
      baseURL: href.replace(/[^/]*$/, "") || "./",
      paths
    };
  }
  
```
  maybe something like this, if i add a second one so it does not get ignored.

  
```
const links = document.querySelectorAll('link[type="application/l10n"]');
const hrefs = Array.from(links).map(link => link.href);
```

i want to add my own translations independent of files of pdf.js. I did this with webL10n and it worked ok but currently, it does not with the fluent lib since only 1 link tag is processed.

Steps to reproduce the problem:
1. Add a second link tag resource for localization pointing to a different locale.json and folder as well as the language files.
2. In dev console, call PDFViewerApplication.l10n.get('key') to see if it gets loaded.

What is the expected behavior? (add screenshot)
If feature is added, other translation files will also be loaded.

**Comment by Snuffleupagus** [comment]
This seems to be essentially covered by http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
