### ISSUE TITLE
Colors in outline viewer

### ISSUE THREAD

**Issue by Niccori250k** [mozilla/pdf.js#17892]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox Nightly 126.0a1
- Operating system and its version: Windows 11 (Build 26090)

- PDF.js version: The latest of master branch (5adad89eb36b7600258270864b1f9a35454b4586)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a document with colored outline items
2. See outlines

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/54626227/e8e69f02-8187-42c0-b33a-c67d96554f6c)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/54626227/74e13fc2-782d-449e-8b8d-aaa655b0e713)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Note:
The screenshot of the expected behavior was produced by adding
```js
element.style.color = "rgb(" + item.color.toString() + ")";
```
just after [the line 226 in pdf_outline_viewer.js](https://github.com/mozilla/pdf.js/blob/master/web/pdf_outline_viewer.js#L226).

**Comment by Snuffleupagus** [comment]
Given that we support both light *and* dark themes in the viewer, this cannot be implemented without negatively affecting visibility of many custom colour-values. This is a known/accepted limitation, please note the discussion in PR #6943.
