### ISSUE TITLE
wrong line dash pattern rendering behavior when dash array is empty

### ISSUE THREAD

**Issue by ex37** [mozilla/pdf.js#17904]
Link to PDF file here:
[dash_array_example.pdf](https://github.com/mozilla/pdf.js/files/14905707/dash_array_example.pdf)

Configuration:
- Web browser and its version: chrome 123 (not important)
- PDF.js version: 4.1.367

Steps to reproduce the problem:
1. open inside pdf.js viewer any pdf file which has an annotation with an empty array as a dash pattern

What is the expected behavior?
from PDF spec, page 218:
<img width="511" alt="Screenshot 2024-04-08 at 5 04 00 PM" src="https://github.com/mozilla/pdf.js/assets/1114629/8ff14887-466c-47e3-9fe6-b52280d476b8">
it's completely valid having empty dash array, and in Acrobat line is rendered with proper width:

![dash_array_acrobat](https://github.com/mozilla/pdf.js/assets/1114629/d560fc08-6bc0-4134-808d-68115ef97a5a)

What went wrong?
cause of the following line:
https://github.com/mozilla/pdf.js/blob/5adad89eb36b7600258270864b1f9a35454b4586/src/core/annotation.js#L1503
annotation width is set to 0, when dash array is empty.
<img width="1435" alt="dash_array_pdfjs" src="https://github.com/mozilla/pdf.js/assets/1114629/c3770dd8-5a01-49cb-85f6-4ffc58993016">

A solution could be changing the else if statement to smth like this:
`else if (!Array.isArray(dashArray))`

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this and providing a good analysis to reproduce the issue!

**Comment by ex37** [comment]
thanks for the quick fix
