### ISSUE TITLE
Upgrade `gulp` to version 5.0.0

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#17922]
We should upgrade to Gulp 5 now that it's officially released. The changelog, including the breaking changes that mostly don't seem to affect us, can be found at https://github.com/gulpjs/gulp/releases/tag/v5.0.0.

I have already quickly tried the upgrade locally to see if it would be easy or not, and found that the main blocker appears to be the `merge-stream` package. It doesn't seem to work anymore with Gulp 5, causing tracebacks for most tasks (because of most of them directly or indirectly rely on `merge` calls).

The last commit for `merge-stream`, see https://github.com/grncdr/merge-stream, was 5 years ago, so this probably isn't very surprising. However, I played around with removing the `merge` calls altogether and didn't immediately find something that was obviously broken, so I'm mainly wondering what the use case of it is or was at the time of introduction (maybe it's obsolete nowadays, or something breaks when removing it that I just haven't noticed yet...). Sadly I haven't been able to find out more from e.g. Git commit messages.

We should investigate if `merge-stream` can be fixed, replaced or removed. Once that is addressed Gulp 5 _should_ work, but note that we still need to carefully test _all_ commands.

**Comment by Snuffleupagus** [comment]
Could https://github.com/sindresorhus/merge-streams be a possible replacement?

**Comment by Snuffleupagus** [comment]
> However, I played around with removing the `merge` calls altogether and didn't immediately find something that was obviously broken, so I'm mainly wondering what the use case of it is or was at the time of introduction (maybe it's obsolete nowadays, or something breaks when removing it that I just haven't noticed yet...).

Without some `merge`-like functionality I believe that we'll not correctly wait for everything to complete, which could possibly lead to intermittent bugs later on if we just remove it.

However, it seems that others have run into similar/same problems and according to https://github.com/gulpjs/gulp/issues/2802#issuecomment-2094130656 there's an "official" gulp-helper available; see https://www.npmjs.com/package/ordered-read-streams

**Comment by timvandermeij** [comment]
Nice find; thanks! I have made the PR above to replace `merge-stream`, after which the Gulp 5 upgrade _should_ be unblocked (provided that we don't find further defects while testing all Gulp targets carefully).
