### ISSUE TITLE
Upgrade `eslint` to version 9.0.0

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#17928]
We should upgrade to ESLint 9 now that it's officially released. The changelog, including the breaking changes that should be audited, can be found at https://github.com/eslint/eslint/releases/tag/v9.0.0. Note that this upgrade is currently blocked on the ESLint plugins that we use indicating support for ESLint 9 in their `package.json` ranges first, so this is mostly a tracking issue at the moment.

**Comment by wojtekmaj** [comment]
Let's make it a tracking issue then :D

### Plugins

| Plugin name | Current status | Issue | Comments
|---|---|---|---|
| [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) | Probably planned | https://github.com/import-js/eslint-plugin-import/issues/2948 | |
| [eslint-plugin-json](https://github.com/azeemba/eslint-plugin-json) | Kinda-supported? | https://github.com/azeemba/eslint-plugin-json/issues/80 | No update in 3 years, I'd be worries about this plugin health |
| [eslint-plugin-mozilla](https://searchfox.org/mozilla-central/source/tools/lint/eslint/eslint-plugin-mozilla) | Probably planned | https://bugzilla.mozilla.org/show_bug.cgi?id=1881696 | |
| [eslint-plugin-no-unsanitized](https://github.com/mozilla/eslint-plugin-no-unsanitized) | Probably planned | https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/234 | |
| [eslint-plugin-sort-exports](https://github.com/jrdrg/eslint-plugin-sort-exports) | Unknown | n/a | |
| [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) | Implemented, to be released | https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2250 | Likely to be released as v53 |

**Comment by timvandermeij** [comment]
In commit d7f2bc044aaa25376d68ec35696561497d0aa50e `eslint-plugin-unicorn` got upgraded to version 53.0.0 which contains support for ESLint 9, so we can cross that one off the list.

**Comment by nicolo-ribaudo** [comment]
If you haven't already seen https://eslint.org/blog/2024/05/eslint-compatibility-utilities/, it might be useful for this. It provides wrappers to run ESLint 8 plugins in ESLint 9.

**Comment by mozfreddyb** [comment]
I can comment for eslint-plugin-no-unsanitized: It's planned but blocked on dependencies (heh)
 https://github.com/mozilla/eslint-plugin-no-unsanitized/issues/241

**Comment by timvandermeij** [comment]
`eslint-plugin-json` 4.0.0 is now released and contains ESLint 9 support (see https://github.com/azeemba/eslint-plugin-json/commit/0ff302cadbd6a995089be756c5f8660001e45f29), but sadly we can't update to it yet because `eslint-plugin-mozilla` has not indicated support for version 4.0.0 in `package.json` yet which we'll have to await first:

```
npm error While resolving: eslint-plugin-mozilla@3.7.4
npm error Found: eslint-plugin-json@4.0.0
npm error node_modules/eslint-plugin-json
npm error   dev eslint-plugin-json@"^4.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint-plugin-json@"^3.1.0" from eslint-plugin-mozilla@3.7.4
npm error node_modules/eslint-plugin-mozilla
npm error   dev eslint-plugin-mozilla@"^3.7.4" from the root project
npm error
npm error Conflicting peer dependency: eslint-plugin-json@3.1.0
npm error node_modules/eslint-plugin-json
npm error   peer eslint-plugin-json@"^3.1.0" from eslint-plugin-mozilla@3.7.4
npm error   node_modules/eslint-plugin-mozilla
npm error     dev eslint-plugin-mozilla@"^3.7.4" from the root project
```

**Comment by timvandermeij** [comment]
In commit c77dbe04966111b8b80383e8befa8d4f9438a346 `eslint-plugin-jasmine` got updated to version 4.2.0 which contains support for ESLint 9, so we also can cross that one off the list.

**Comment by timvandermeij** [comment]
In PR #18571 the idea came up of trying to remove `eslint-plugin-mozilla` given that we only used three rules from it and after that PR we are down to two: one at https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/.eslintrc#L19 and one at https://github.com/mozilla/pdf.js/blob/master/.eslintrc#L47. The latter might already be covered by an existing `unicorn` rule, and the former may be removed in favor of documenting the remaining globals we have left explicitly (since it's only five nowadays judging by a quick `npx gulp lint` run with the rule removed).

We should investigate if this is possible/worthwhile since it could unblock the `eslint-plugin-json` update and that combined with the removal of `eslint-plugin-mozilla` would bring us two steps closer to ESLint 9.

**Comment by timvandermeij** [comment]
In commit https://github.com/mozilla/pdf.js/commit/be93d530deab4a1d9a4ad795ee0c80b7fa9ae119 `eslint-plugin-mozilla` got removed, so we also can cross that one off the list.

**Comment by mozfreddyb** [comment]
`no-unsanitized` now supports eslint 9. We just released a new version earlier in the week.

**Comment by timvandermeij** [comment]
In commit https://github.com/mozilla/pdf.js/pull/18708/commits/ae13b4a01571c73c6d451cb36bc66b21f6d996d2 `eslint-plugin-no-unsanitized` got updated to version 4.1.0 which contains support for ESLint 9, so we can cross that one off the list.

**Comment by timvandermeij** [comment]
In commit https://github.com/timvandermeij/pdf.js/commit/78bf5287d17311e61bbeae23d281dbaf4da1925a `eslint-plugin-import` got updated to version 2.31.0 which contains support for ESLint 9, so we can cross that one off the list.

**Comment by timvandermeij** [comment]
In the PRs above we removed obsolete plugins and replaced `eslint-plugin-sort-exports`, which _should_ have removed the final blocker for the upgrade here.

**Comment by nicolo-ribaudo** [comment]
It _seems_ like now just bumping the version in package.json works, but I haven't had time to test deeply.
