### ISSUE TITLE
Encountering an issue with pdf.js truncating outline item titles when their text length exceeds 256 characters.

### ISSUE THREAD

**Issue by RajendraDogne-RWS** [mozilla/pdf.js#17920]
Encountering an issue with pdf.js truncating outline item titles when their text length exceeds 256 characters.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this contains no actionable information.
