### ISSUE TITLE
OpenJPEG warnings don't respect the PDF.js `verbosity` levels

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17980]
Currently any OpenJPEG warnings are logged *directly* using `console.warn`, which seems a bit unfortunate; note https://github.com/mozilla/pdf.js.openjpeg/blob/8efbbf110984561b1cbd6118544a04f316ed91e6/src/myjs.js#L17-L20

Would it be feasible/possible to e.g. change either of these call-sites to also include the PDF.js `warn`-function, and then use that for reporting the OpenJPEG warnings? https://github.com/mozilla/pdf.js/blob/5ad42c13adb90fd030dcc7b60451eb6f9824581f/src/core/jpx.js#L29-L30
 
/cc @calixteman

**Comment by calixteman** [comment]
Do you have a pdf where some warnings are generated ?

**Comment by Snuffleupagus** [comment]
> Do you have a pdf where some warnings are generated ?

http://www.braidense.it/rd/03595.pdf (taken from an old issue).
