### ISSUE TITLE
v4.1.392 breaks loading pdfjs in Safari (16.6)

### ISSUE THREAD

**Issue by cgi-0** [mozilla/pdf.js#17992]
We noticed a problem with the recent v4.1.392 release and Safari (16.6). I'm not sure what is officially supported (reading https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support it seems Safari is supported just with the legacy release?), but I think 16.6 might still be used and it did work before with v4.0.379. Losing Safari support would be a bit unfortunate. 

Just go to the default demo page with Safari using the default document. 

Thanks for having a look.

**Configuration:**
- Web browser and its version: Safari 16.6 
- Operating system and its version: Ventura 13.6
- PDF.js version: v4.1.392
- Is a browser extension: no

**Steps to reproduce the problem:**
1.  go to https://mozilla.github.io/pdf.js/web/viewer.html

**What is the expected behavior?**
Pdf should be rendered in Safari like with v4.0.379. Chrome and Firefox works fine with v4.1.392.

**What went wrong?**
Just the toolbar is rendered, no pdf content is shown/rendered. Some functions in the toolbar are unresponsive.

**Comment by Snuffleupagus** [comment]
As outlined in the FAQ, using a `legacy`-build *is necessary* for Safari compatibility (which has been the case *for years*); hence https://mozilla.github.io/pdf.js/legacy/web/viewer.html ought to work.

**Comment by calixteman** [comment]
Yep, I can confirm that it works with the legacy build in testing with 16.6 at https://www.browserstack.com/test-on-safari-browser (it's possible to free test but only for 1 or 2 minutes).

**Comment by Snuffleupagus** [comment]
> * Do I understand it correctly, that _legacy_ is just a "translated/polyfilled build" of the same source code that is used for the _modern_ build (I guess" translated" means transpiled to a older ES version) ?

Yes, the same function is being used to build the code with Webpack; see https://github.com/mozilla/pdf.js/blob/90d4b9c2c0df7cadbd5c2388431b208f08da1ed6/gulpfile.mjs#L264-L390
The only difference is that the `legacy`-version *also* uses Babel to transpile/polyfill the code, with the following configuration: https://github.com/mozilla/pdf.js/blob/90d4b9c2c0df7cadbd5c2388431b208f08da1ed6/gulpfile.mjs#L83-L106

> * Are you aware of any functional or performance differences between the _legacy_ and _modern_ build? In other words, do you see any advantages to use the _modern_ build in a deployment?

There shouldn't be any functional differences, provided that the polyfills (which are mostly `core-js` based) work correctly. A polyfill may (obviously) be slower than native code, but that's probably not much of an issue in practice.

It all depends on what you need/want to support in your application, if that includes anything that's not that current Firefox/Chrome releases than you'll *need* to use a `legacy`-build.
