### ISSUE TITLE
TypeError: Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by gopi-chand-reddy** [mozilla/pdf.js#18006]
_This error has nothing to do with the PDF file._

**Configuration:**
- node.js V21.7.3
- Operating system and its version: Ubuntu 22.04.1 LTS
- PDF.js version: "pdfjs-dist": "^4.1.392"
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Run this code: `node index.js`
```
import fs from "fs";
// import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { getDocument } from "pdfjs-dist";

async function pageCount(pdfPath) {
    try {
        const data = new Uint8Array(fs.readFileSync(pdfPath));
        const pdf = await getDocument({ data }).promise;

        return pdf.numPages;
    } catch (reason) {
        console.log(reason);
    }
}

const pcount = await pageCount(process.argv[2] || "./sigs.pdf");
console.log(pcount);
```

**What is the expected behavior?** Print the page count (as done by the legacy module)

**What went wrong?** Getting the following error:
`TypeError: Promise.withResolvers is not a function`

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  Using "npm i pdfjs-dist" in a simple node.js app.

**Comment by gopi-chand-reddy** [comment]
It appears node (as of v21) doesn't include the feature by default.  When enabled through a flag as in `node --js-promise-withresolvers index.js`, it works as expected. You might want to close the issue.

**Comment by Snuffleupagus** [comment]
As mentioned in the FAQ, using a `legacy`-build *is required* in Node.js environments; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by F8-Tortoise** [comment]
没看懂 能简单明了的说一下吗？要怎么搞呢

**Comment by alphabetaxz** [comment]
Manually adding a polyfill for Promise.withResolvers(), not sure what side effects this might have, but it currently solves my problem.
```
if (!Promise.withResolvers) {
  Promise.withResolvers = function () {
    let resolve, reject;
    const promise = new Promise((res, rej) => {
      resolve = res;
      reject = rej;
    });
    return { promise, resolve, reject };
  };
}
```
