### ISSUE TITLE
Slow rendering of PDF

### ISSUE THREAD

**Issue by TyDraniu** [mozilla/pdf.js#18002]
Attach (recommended) or Link to PDF file here:
[real estate Website Template_w.pdf](https://github.com/mozilla/pdf.js/files/15106258/real.estate.Website.Template_w.pdf)

Configuration:
- Web browser and its version: Firefox Nightly 127
- Operating system and its version: Windows 11

It takes more than 30 seconds to render this file. It's quite long, keeping in mind that this file has only 5MB.

In Edge it opens within 5 seconds.

Could the situation be improved?

**Comment by jscher2000** [comment]
The PDF displays quickly in the Google Drive previewer, in case that provides any clues: https://drive.google.com/file/d/1sbQdmfhHGOVb5l2ja_NwcVkx8D1Fwenn/view (link shared in https://support.mozilla.org/en-US/questions/1445689#answer-1649333)
