### ISSUE TITLE
[3.11.174]Unable to render pages on offscreencanvas ?

### ISSUE THREAD

**Issue by minedun6** [mozilla/pdf.js#18010]
PDFJS version : 3.11.174

Descripton : 
I'm trying to generate pages using the offscreencanvas, I'm trying to process the document pages in a webworker.

`const pdf = await pdfjs.getDocument({data).promise;

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);

    const viewport = page.getViewport({ scale: 0.5 });
    const canvas = new OffscreenCanvas(viewport.width, viewport.height);
    const context = canvas.getContext("2d");

    page
      .render({
        canvasContext: context,
        viewport: viewport,
      })
      .promise.then(() => {
          // send it back to main thread
      });
  }`

and this is the error I'm getting
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createElement')
    at DOMCanvasFactory._createCanvas`

I thought I gone around the need to create a canvas by making an Offscreencanvas :rofl: 

Is there any workaround to making this work ?

**Comment by Snuffleupagus** [comment]
> PDFJS version : 3.11.174

Note that this version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I'm trying to generate pages using the offscreencanvas, I'm trying to process the document pages in a webworker.

Sorry, but *rendering* the PDF document in a Worker is not supported.
