### ISSUE TITLE
Not able to Edit the text annotation on top of a Form field when PDF Documents has link annotations and native annotations on it

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#18025]
Attach (recommended) or Link to PDF file here:
[test4filled.pdf](https://github.com/mozilla/pdf.js/files/15153748/test4filled.pdf)

Configuration:
- Web browser and its version: Any browser
- Operating system and its version: Windows
- PDF.js version: After pdf.js2.8 till latest We see this issue. this issue was not seen in pdf.js 2.5.207 and 2.8.
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached document in mozilla.
2. Try Adding annotation text exactly on top of the form field. 
3. Then try to edit the annotation

What is the expected behavior? (add screenshot)
We should be able to edit the text annotation on top of the form field. 
![image](https://github.com/mozilla/pdf.js/assets/79515387/82f05457-6a45-4a27-9fd3-78536b94cae2)

What went wrong? (add screenshot)
We are not able to select the Text annotation as the form field annotation layer is rendered on top. 
![image](https://github.com/mozilla/pdf.js/assets/79515387/4e47c655-172b-4a6c-b9a0-0c4e13847afd)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by mirnalinikarthik** [comment]
I understand that clicking the Text mode button brings the Text annotation layer to the top. Just wanted to know if there is a flag which can be enabled to bring the text annotation layer to the top always.

**Comment by Snuffleupagus** [comment]
> I understand that clicking the Text mode button brings the Text annotation layer to the top.

Yes, it's necessary to enable an edit-tool *first* in order to change a previously added annotation; hence this is working as intended here.

> Just wanted to know if there is a flag which can be enabled to bring the text annotation layer to the top always.

No, there's not.
