### ISSUE TITLE
Broken firefox ESR support since 4.1.392

### ISSUE THREAD

**Issue by PhiR42** [mozilla/pdf.js#18027]
### Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox ESR 115
- Operating system and its version: windows 11 64bits
- PDF.js version: 4.1.392 and 4.2.67

Console gives the following error:
```
Uncaught TypeError: Promise.withResolvers is not a function
    1621 app.js:101
    a async module:49
    1621 viewer.mjs:1983
    Webpack 6
```
The interface is loaded but the pdf not displayed.

**Comment by nicolo-ribaudo** [comment]
Looking at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#legacy-build, it seems like for Firefox ESR you need to use the _legacy_ build (which includes a `Promise.withResolvers` polyfill).

**Comment by PhiR42** [comment]
Ok my bad. For the record is there any drawbacks to using the legacy build for all browsers ?

**Comment by nicolo-ribaudo** [comment]
It is a larger file because it includes polyfills, but except for that there should be no difference.
