### ISSUE TITLE
Serbian cyrillic and latin localization

### ISSUE THREAD

**Issue by snofear** [mozilla/pdf.js#18020]
Configuration:
- Chrome version 123.0.6312.107.
- Windows 11
- PDF.js version: 3.10.111.

I want to change pdfjs localization to serbian latin language but there is just serbian cyrillic language available. Is it possible to add latin option also?

**Comment by timvandermeij** [comment]
The localizations are not managed here, but in the upstream Mozilla repositories instead; we only import them (see https://hg.mozilla.org/l10n-central/). Hence this request should be reported upstream, for example refer to https://pontoon.mozilla.org/.

**Comment by Snuffleupagus** [comment]
As outlined in https://github.com/mozilla/pdf.js/blob/master/l10n/README.md we don't maintain the locale-files in this repository, hence you'd need to ask for a new Firefox localization.

> PDF.js version: 3.10.111

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by snofear** [comment]
Thank you for quick answer
