### ISSUE TITLE
Structure Tree does not provides ColSpan and RowSpan

### ISSUE THREAD

**Issue by siddhesh8k** [mozilla/pdf.js#18039]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Upload the any tagged PDF and observe
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Structure Tree doesn't provide colSpan and rowSpan.
Please provide solution on this
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
**Please fill out the ISSUE_TEMPLATE correctly and completely, as mentioned previously, when opening an issue.**

**Comment by siddhesh8k** [comment]
> Attach (recommended) or Link to PDF file here:
> 
> Configuration:
> 
> * Web browser and its version:
> * Operating system and its version:
> * PDF.js version:
> * Is a browser extension:
> 
> Steps to reproduce the problem:
>1) Open the attached pdf file in pdfjs viewer and observe the structure tree.
![image](https://github.com/mozilla/pdf.js/assets/22116188/88069d30-f009-4f9a-a45d-99eca558db91)
In above image, the pdf file has tagged table with colspan as 2. 

2)Issue:-
![image](https://github.com/mozilla/pdf.js/assets/22116188/cf782c2f-3e2d-4430-a60f-a0b54845e3cf)
In above image, we can see in pdfjs viewer structure tree does not maintain the colspan. 
> 
> What is the expected behavior? (add screenshot)
> So can be there any provision by which we can retain the colspan or row span. Please provide solution on this 
[table.pdf](https://github.com/mozilla/pdf.js/files/15308667/table.pdf)

> What went wrong? (add screenshot) Structure Tree doesn't provide colSpan and rowSpan. Please provide solution on this Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
