### ISSUE TITLE
Uncomfortable textselection in iOS

### ISSUE THREAD

**Issue by levram** [mozilla/pdf.js#1803]
### The problem

We tried a couple of pdfs in iOS and text selection is sometimes uncomfortable: it switches to block selection mode from character selection mode inproperly. 
Usually you can only select one line in character selection mode **at most**, and it switches to block selection mode if the selection contains a line break (more precisely one div ends and an other one starts). We also observed this behaviour when the selection contains any font style changes (because this also means a div end and a div start).

Usual use case is that a user wants to select an exact whole sentence, and because of this phenomena the user simply can't (the selection contains excess/unneeded words at the beginning and at the end).

Do you have any solution for our situtation?
If not, this is what we came up with.
### A possible solution

We would write a paragraph recognizer algorithm which gathers visually related texts into one div (or a p tag) with proper inner and outer positioning (linebreaking, etc)
#### This will have two advantages:
- selection will work as intended within a paragraph
- this might increase performance because of the less DOM elements

We would like your advice in this matter before we proceed any further.

Thanks in advance,
Viktor

**Comment by twigbranch** [comment]
Is this issue being addressed?

Whenever I try to select text on an iPhone, I am able to select a word by long pressing on it, but when I try to expand the select area by dragging the iOS handles, the select area suddenly shifts to large blocks and I can no longer select by individual words.

**Comment by timvandermeij** [comment]
Closing since this is a very old issue and many text selection improvements have been made in the meantime, including combining tags where possible.
