### ISSUE TITLE
What is the latest version of worker available?

### ISSUE THREAD

**Issue by matveychuk** [mozilla/pdf.js#18040]
The latest version of the library 'pdfjs-dist' is 4.2.67. But I can't upgrade my current version to it because I use the 
`workerUrl="https://unpkg.com/pdfjs-dist@3.11.174/build/pdf.worker.min.js"` and the latest version of the worker as I see is 3.11.174. 
How is it supposed the new versions work with worker?
Thank you!

**Comment by timvandermeij** [comment]
Version 4.2.67 is available at https://unpkg.com/pdfjs-dist@4.2.67/build/pdf.worker.min.mjs. Note that the CDNs simply mirror our releases and we don't control how that process is done, so any support questions should be directed to the CDN in question.
