### ISSUE TITLE
Safari bug, cannot import pdfjs: `SyntaxError: Unexpected private name #setRectEdited`

### ISSUE THREAD

**Issue by acoyfellow** [mozilla/pdf.js#18045]
Attach (recommended) or Link to PDF file here: (any PDF file)
![image](https://github.com/mozilla/pdf.js/assets/1666099/d7955aa6-f6cf-4198-ae4c-0ad0789f69c9)
![image](https://github.com/mozilla/pdf.js/assets/1666099/6cb6e951-91a9-4d8c-bb52-9eb3477dc956)

Configuration:
- Web browser and its version: Safari 14.1.2
- Operating system and its version: MacOS Big Sur 11.5.2
- PDF.js version: 4.2.67
- Is a browser extension: No

Steps to reproduce the problem:
1.  Import pdfjs-lib when on Safari.
* The same exact code runs fine on Chrome / Safari

What is the expected behavior? To load.

What went wrong? Will not load, error in console:
```
[Error] SyntaxError: Unexpected private name #setRectEdited. Cannot parse class method with private name.
```

![image](https://github.com/mozilla/pdf.js/assets/1666099/166bed7c-0a98-4fdb-9bb3-517386246d25)

**Comment by acoyfellow** [comment]
Digging a bit deeper, it looks like Safari 14.1.2 just does not like using `#` 

I can reproduce the error with simply:

```html
<!DOCTYPE html>
<html>

<script>
  console.log('Test');
  class Test {
    #setRectEdited() { };
  };
</script>

</html>
```

```
SyntaxError: Unexpected private name #setRectEdited. Cannot parse class method with private name.
```

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari 14.1.2

Unfortunately that's too old to be supported here; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
