### ISSUE TITLE
Update Wiki documentation

### ISSUE THREAD

**Issue by carlinmack** [mozilla/pdf.js#18056]
The [docs](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file) state:

> Use PDFViewerApplication.open(file) to load the PDF file later.

However doing so results in:

> The `PDFViewerApplication.open` signature was updated, please use an object instead.

So I believe it should instead be:

> Use PDFViewerApplication.open({"url": file}) to load the PDF file later.

**Comment by SeanAverS** [comment]
Hello. Can I work on this issue?

**Comment by timvandermeij** [comment]
Thank you for reporting this. The wiki has just been updated.
