### ISSUE TITLE
Update the Babel plugin to remove empty `class` constructors

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#18057]
To avoid useless `class` constructors we utilize the ESLint `no-useless-constructor` rule, which works well in *most* cases.
The exception is when a constructor includes pre-processor statements that make it conditionally empty, note e.g. how the following source code:
https://github.com/mozilla/pdf.js/blob/b6765403a1b08aa80a21cb0809741875a925ab4d/src/display/editor/tools.js#L61-L67
is transformed into (in that case for the `MOZCENTRAL` build):
https://searchfox.org/mozilla-central/rev/dbd654fa899a56a6a2e92f325c4608020e80afae/toolkit/components/pdfjs/content/build/pdf.mjs#1829

Hence it seems like a good idea to extend the Babel plugin to remove `class` constructors that become empty during building.

/cc @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
I can work on this

**Comment by Snuffleupagus** [comment]
> I can work on this.

Thank you!

> Do we have cases in which we also need to remove subclass constructors like the following?
> ```js
> class A extends B {
>   constructor(...args) { super(...args) }
> }
> ```

That *exact* pattern should already be caught by `no-useless-constructor`, at least I think so.
