### ISSUE TITLE
The seal image in the PDF file is displayed missing

### ISSUE THREAD

**Issue by 280668993** [mozilla/pdf.js#18058]
Attach (recommended) or Link to PDF file here:  
[file.pdf](https://github.com/mozilla/pdf.js/files/15269193/file.pdf)

Configuration:
- Web browser and its version:Microsoft Edge  124.0.2478.80
- Operating system and its version: window11   22631.3527
- PDF.js version:  4.2.67
- Is a browser extension:

Steps to reproduce the problem:
1. open the pdf

What is the expected behavior? (add screenshot)
![1](https://github.com/mozilla/pdf.js/assets/51706054/1f1cfd81-70bd-4b0c-ba96-ea7306023918)

What went wrong? (add screenshot)
![2](https://github.com/mozilla/pdf.js/assets/51706054/bcc03eb2-dd28-4b7d-823f-65cea125e794)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ArthurJam** [comment]
+1
