### ISSUE TITLE
Fields not rendered after saving and opening Dutch tax form

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18072]
Attach (recommended) or Link to PDF file here:

- Direct link: https://download.belastingdienst.nl/belastingdienst/docs/model_opgaaf_gegevens_loonheffingen_lh0082z11fol.pdf
- Web Archive link: https://web.archive.org/web/20240309103139/https://download.belastingdienst.nl/belastingdienst/docs/model_opgaaf_gegevens_loonheffingen_lh0082z11fol.pdf

Configuration:
- Web browser and its version: Firefox 125.0.3
- Operating system and its version: Arch Linux
- PDF.js version: 4.1.342 embedded in Firefox and 4.3.21 from https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF file (Dutch tax form).
2. Click the first radio button on the second page. Notice that extra fields appear behind it.
3. Enter a date: 12-05-2024
4. Save the PDF file to disk.
5. Open the saved PDF file. Notice that the first radio button on the second page is checked, but the extra fields behind it are no longer visible. This makes it _seem_ as if data loss occurred, even though that's not the case.
6. Click the second radio button below it and click the first radio button again. Notice that the extra fields behind the first radio button are now correctly visible, including the entered date.

What is the expected behavior? (add screenshot)
![Expected](https://github.com/mozilla/pdf.js/assets/1993262/721ede30-1f5b-4dc9-bef1-58bba2c58cda)

What went wrong? (add screenshot)
![Actual](https://github.com/mozilla/pdf.js/assets/1993262/a9bbdcec-a4b0-4a20-9fef-bb400c81189e)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by calixteman** [comment]
I suppose the action under the `A` entry must be triggered even when there's no user action.
In the [specs](https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf#page=422&zoom=108,-133,650), we can read that:
```
The optional A entry in the annotation or outline item dictionary (see Tables 168 and 153) specifies an
action performed when the annotation or outline item is activated;...
```
I wonder when we should trigger the action: either when rendering the annotation for the first time or when all the annotations data are loaded in the sandbox (and before or after DcumentOpen/PageOpen...).

**Comment by timvandermeij** [comment]
Today I found out that if I save the form with the PDF editor in Microsoft Edge and then open the PDF file with Firefox that it _does_ render correctly, so that makes me think that the rendering part in PDF.js might work correctly but that it's rather a problem with saving the PDF file from PDF.js...

**Comment by calixteman** [comment]
When the user clicks on the radio button, the visibility of the associated text fields is changed and must be saved.

**Comment by timvandermeij** [comment]
Thank you for fixing this, @calixteman! I have tested this again and it works like a charm now.
