### ISSUE TITLE
[performance]: The putBinaryImageData function takes too long and blocks page interaction.

### ISSUE THREAD

**Issue by lu606** [mozilla/pdf.js#18088]
Attach (recommended) or Link to PDF file here:
[example.pdf](
https://github.com/mozilla/pdf.js/files/15305498/example.pdf)

Configuration:
- Web browser and its version: chrome version: 124.0.6367.208
- Operating system and its version: win 11
- PDF.js version: 3.4.120

Steps to reproduce the problem:
1. Render a 30+ page PDF document in a 200 × 200 container
2. After calling the pdfPage rendering function, the page becomes unresponsive.

What is the expected behavior? 
Render normally without blocking user behavior

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/59679502/0ef9ef6a-a67a-4417-84d3-0d425ceafb17)
![image](https://github.com/mozilla/pdf.js/assets/59679502/024b5e3c-0036-4e80-a597-c5202b89ce95)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.4.120

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by calixteman** [comment]
I can reproduce the issue with Firefox nightly and I think I've a fix.

**Comment by lu606** [comment]
> I can reproduce the issue with Firefox nightly and I think I've a fix.

This sounds like good news, which version should I upgrade to and give it a try?
