### ISSUE TITLE
Enabling Context highlight in PDF

### ISSUE THREAD

**Issue by Aruldevan** [mozilla/pdf.js#18083]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome and Version 124.0.6367.201 (Official Build) (64-bit)
- Operating system and its version: Windows  and 23H2
- PDF.js version: pdfjs-4.0.379-dist
- Is a browser extension: No

Steps to reproduce the problem:
1. Give **phrase** as 'true' and give value of  **search** attribute one line from pdf which is rendered using pdfjs-viewer-element. It is working fine.
2. Now give two lines from pdf it is not working.

What is the expected behavior? (add screenshot)
![m](https://github.com/mozilla/pdf.js/assets/91751623/4bf37cc5-3f49-4a04-a71e-614f4c59360a)

What went wrong? (add screenshot)
![n](https://github.com/mozilla/pdf.js/assets/91751623/04cb2470-4f5a-4395-87c3-e2e3de01db1a)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part is *always* necessary when reporting an issue; as-is this would be closed as INCOMPLETE.

> PDF.js version: pdfjs-4.0.379-dist

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. Give **phrase** as 'true' and give value of  **search** attribute one line from pdf which is rendered using pdfjs-viewer-element. It is working fine.
>     2. Now give two lines from pdf it is not working.

Unfortunately this is nowhere clear enough, also given the overall lack of information. Please provide *detailed* step-by-step instructions needed to reproduce the problem.
