### ISSUE TITLE
cleanup hiddenCanvasElement when using renderTextLayer

### ISSUE THREAD

**Issue by elitastic** [mozilla/pdf.js#18086]
I am using the text layer rendering like:

```
const pdf = await pdfJs.getDocument('xy').promise;
const page = await this.pdf.getPage(0);
await  page.render({...});
const textContent = await page.getTextContent();
await pdfJs.renderTextLayer({...}).promise;
```

Due to the following [commit](https://github.com/mozilla/pdf.js/commit/f84f48b5d0f8d82a0f5ac344c6e9cdb4f13b0097), a canvas element is always used instead of OffscreenCanvas like before. This is fine for me. But, after `renderTextLayer()` is called, I would like to cleanup the canvas element lying around in document body.

My current workaround is:

```
document.querySelectorAll('.hiddenCanvasElement').forEach(e => e.remove())
```

Is there a better way to prevent the canvas element lying around in document body?

**Comment by Snuffleupagus** [comment]
> Is there a better way to prevent the canvas element lying around in document body?

It'll be removed when you destroy the PDF document, which you should be doing anyway once you're done with it. Hence, based on your code, you'd add `await pdf.destroy();` at the end; note https://github.com/mozilla/pdf.js/blob/0347e59b99cfcdcc5d755434a8ce5d0ca34f299d/src/display/api.js#L1072-L1077

**Comment by elitastic** [comment]
Thanks for your help!
