### ISSUE TITLE
Chrome fails to draw content in pdf.js when switching between tabs

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#18100]
Attach (recommended) or Link to PDF file here: https://arxiv.org/pdf/2212.09034.pdf

Configuration:
- Web browser and its version: Chrome 126.0.6463.0 (Official Build) canary (64-bit) (cohort: Clang-64) 
- Operating system and its version: Windows 10 Version 22H2 (Build 19045.4291)
- PDF.js version: 3.9.49, 4.3.21
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open the file FIVE times in different tabs
2. Switch back to the first Tab

What is the expected behavior? (add screenshot)
![Chrome_good](https://github.com/mozilla/pdf.js/assets/2311076/b3abbfb3-bc84-47fd-b25a-b1fa297fb980)

What went wrong? (add screenshot)
![Chrome_bad](https://github.com/mozilla/pdf.js/assets/2311076/309e6584-83ae-4125-acd7-1fed91e87723)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

This is Chrome regression from 126.0.6462.0.
I opened a [bug report](https://issues.chromium.org/issues/339654395) for Chrome.
So far, they were able to reproduce the issue (on Mac), but haven't been able to bisect it.

**Comment by Snuffleupagus** [comment]
Thanks for the information.
Given that this is apparently *a browser* regression, and not a PDF.js one, I'm not sure that it's necessary for us to keep this issue open here.

Generally speaking, we're quite unlikely to attempt to hack-around browser bugs *unless* they affect Firefox (which is the primary development target here).
