### ISSUE TITLE
pdfjs-dist's legacy build has newer syntax

### ISSUE THREAD

**Issue by mitchellsimoens** [mozilla/pdf.js#18120]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 125.0.6422.61
- Operating system and its version: MacOS 14.4.1
- PDF.js version: 4.2.67
- Is a browser extension: No

Steps to reproduce the problem:
1. `npm i --save-dev pdfjs-dist`
2. Look at node_modules/pdfjs-dist/legacy/build/pdf.mjs

What is the expected behavior?

Expect to not have non-legacy browser desired syntax. For example, AnnotationElement has private class member syntax (e.g. `#updates = null;` and `this.#setRectEdited(rect);`).

What went wrong?

Legacy browsers or tooling that do not support some newer syntax will error out when it gets to the code with newer syntax.

We are using Ionic [Stencil.js](https://stenciljs.com/) that uses Rollup to build their components into web components. When I build my project, I get this error:

<img width="686" alt="Screenshot 2024-05-20 at 1 24 11 PM" src="https://github.com/mozilla/pdf.js/assets/325473/ad5dbc38-b51e-437a-925b-2acf7f5b9cee">

We import using:

```typescript
import pdfjsLib, { PDFDocumentProxy } from 'pdfjs-dist/legacy/build/pdf.mjs';

import worker from 'pdfjs-dist/legacy/build/pdf.worker.mjs';

pdfjsLib.GlobalWorkerOptions.workerSrc = worker;
```

iirc, ES2022 brought private properties which wouldn't be very "legacy".

**Comment by mwrouse** [comment]
I am also noticing that doing the legacy build appears to still be generating modules entirely. The final line of the files is an `export` line.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
