### ISSUE TITLE
Don't render the attached file

### ISSUE THREAD

**Issue by pankajgupta2410** [mozilla/pdf.js#18144]
Attach (recommended) or Link to PDF file here:

Configuration:
[test3.pdf](https://github.com/mozilla/pdf.js/files/15401665/test3.pdf)

- Web browser and its version: Chrome, V124.0.X
- Operating system and its version: macOS, 14.4.1 (23E224)
- PDF.js version: 4.1.392
- Is a browser extension: no

Steps to reproduce the problem:
1.  load above attached file

What is the expected behavior? (add screenshot) File should be loaded successfully

What went wrong? (add screenshot): Looks like fails to load locale data

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Default webviewer used

**Comment by Snuffleupagus** [comment]
That PDF document is unfortunately corrupt enough that neither Adobe Reader (i.e. the PDF reference implementation) or PDFium (i.e. the Google Chrome PDF Viewer) is able to open it, and they both display error messages.
