### ISSUE TITLE
Hyperlinks in PDF Rendered by vue-pdf Misaligned on Small Screens

### ISSUE THREAD

**Issue by JoyZ-nineteen** [mozilla/pdf.js#18149]
Attach (recommended) or Link to PDF file here:
https://tcstore1.17usoft.com/tcoa-bucket/30778699df3d48a4b61d6fe335352e56.pdf

Configuration:
- Web browser and its version: Google
- Operating system and its version: win10
- PDF.js version: vue-pdf 4.2.0 and 4.3.0

Steps to reproduce the problem:
1. yarn add vue-pdf
2. <template>
  <div>
    <pdf src="https://tcstore1.17usoft.com/tcoa-bucket/30778699df3d48a4b61d6fe335352e56.pdf"></pdf>

  </div>
</template>

<script>
import pdf from 'vue-pdf'

export default {
  name: 'abcd',
  components: {
    pdf,
  },
}
</script>

What is the expected behavior? (add screenshot)
<img width="475" alt="1" src="https://github.com/mozilla/pdf.js/assets/45134895/1bef4112-e0d4-408f-8af6-d4edf772028b">

What went wrong? (add screenshot)
<img width="862" alt="2" src="https://github.com/mozilla/pdf.js/assets/45134895/e9c60459-5f43-4793-bde2-1a7194a97dbb">

**Comment by nicolo-ribaudo** [comment]
Can you reproduce this opening that PDF at https://mozilla.github.io/pdf.js/web/viewer.html? If not, you should this to vue-pdf.
