### ISSUE TITLE
Cascading PDF selection?

### ISSUE THREAD

**Issue by zyd-n** [mozilla/pdf.js#18172]
I'm not sure how to describe this bug, hence the rather poor title, please see screen recording attached.

PDF:
[document.pdf](https://github.com/mozilla/pdf.js/files/15448332/document.pdf)

Configuration:
- Web browser and its version: Firefox 126.0 (64-bit)
- Operating system and its version: `Linux/Fedora 40`
- PDF.js version: `4.1.379`
- Is a browser extension: no

Steps to reproduce the problem:
1. Open attached PDF
2. Select some text

What is the expected behavior? (add screenshot)
- Normal selection

What went wrong? (add screenshot)
- Selection

See screen recording: 
[pdf-gone-wrong.webm](https://github.com/mozilla/pdf.js/assets/169315939/077d8e50-25ae-41a3-b8ff-f0976cdb3c4b)

For reference, poppler backed pdf readers (e.g `pdf-tools` in emacs, or `Evince`) handle the selection of this pdf just fine.

**Comment by Snuffleupagus** [comment]
This is effectively a combination of issue #17561 and #6011.
