### ISSUE TITLE
Special character € does not appear

### ISSUE THREAD

**Issue by bizdocs-rodolfo-orlandini** [mozilla/pdf.js#18208]
Attach (recommended) or Link to PDF file here: 
[d403d5d5-f3e1-411d-b289-9b497069b80e.pdf](https://github.com/user-attachments/files/15587595/d403d5d5-f3e1-411d-b289-9b497069b80e.pdf)

Configuration:
- Web browser and its version: 
    - Chromium-based: 125.0.6422.147
    - Mozilla Firefox 126.0.1
- Operating system and its version:
    - Windows Pro 11 Version: 10.0.22631 Build: 22631
- PDF.js version:
    - 4.4.14 -> [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
    - 3.11.174
- Is a browser extension: No

Steps to reproduce the problem:
- Open attach document in pdf.js viewer

What is the expected behavior? (add screenshot)
- Open the document containing all special characters

![image](https://github.com/mozilla/pdf.js/assets/146735311/b09decd2-2dd3-413c-84ff-f68c6351dd58)

What went wrong? (add screenshot)
- The special character ﻿`€` does not appear

![image](https://github.com/mozilla/pdf.js/assets/146735311/84f0ee43-a037-4714-bbc3-16b1cd47350d)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
- [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by lokeshsingh3721** [comment]
can i work on this issue ?

**Comment by marco-c** [comment]
Sure thing, feel free to work on it!

**Comment by lokeshsingh3721** [comment]
can you please tell me what can be the possible file should i look for ? otherwise, i have to navigate through all the files. 
Thanks.
