### ISSUE TITLE
Font and glyph spacing on Android differ from desktop

### ISSUE THREAD

**Issue by leoheitmannruiz** [mozilla/pdf.js#18210]
https://github.com/pmetzger/ShellTutorial/releases/download/20131218/ShellTutorial.pdf
https://doc.cat-v.org/plan_9/9.intro.pdf

(both seem to have been created using troff)

Configuration:
- Web browser and its version: Vanadium 125.0.6422.147 (also DuckDuckGo 5.194.0 and Fennec F-Droid 125.3.0)
- Operating system and its version: GrapheneOS 2024053100
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

Steps to reproduce the problem:
1. View one of the two PDFs using https://mozilla.github.io/pdf.js/web/viewer.html on Android
2. See the glyph spacing and font looking weird and differing from desktop

What is the expected behavior?

Firefox on desktop:
![pdf-desktop](https://github.com/mozilla/pdf.js/assets/148111793/6934594c-451d-4317-a1c8-313472bd166e)

What went wrong?

Vanadium on GrapheneOS:
![pdf-android](https://github.com/mozilla/pdf.js/assets/148111793/5b37b002-9376-48ee-acf1-0c97ee880341)

**Comment by calixteman** [comment]
The pdfs don't embed their fonts and pdf.js is falling back on the system ones. For example for the shell tuto, the missing fonts are Times-*** and very likely, whatever your desktop OS is, there's a good substitution for them. On mobile, usually, there are only few fonts which have been designed to be used on mobile... so we're falling back on a font with very different char widths.
We recently fixed a similar issue for Fenix: https://bugzilla.mozilla.org/show_bug.cgi?id=1882613.

**Comment by ArmaandeepSingh** [comment]
@leoheitmannruiz There was a similar issue related to the fonts which was fixed earlier by one of the contributors for bug 1882613. So this is already fixed!
