### ISSUE TITLE
PDF freezes when opened with Firefox with HW Acceleration ON despite very powerful PC specs

### ISSUE THREAD

**Issue by Minibus93** [mozilla/pdf.js#18241]
Attach (recommended) or Link to PDF file here: 
[31) Statistica Inferenziale 6 + Prove d'ipotesi.pdf](https://github.com/user-attachments/files/15816166/31.Statistica.Inferenziale.6.%2B.Prove.d.ipotesi.pdf)

Configuration:
- Web browser and its version: FF 127 stable branch 64 bit
- Operating system and its version: Windows 11 Pro 23h2 (22631.3737) - Ryzen 7800x3d - 4070ti S - 32gb DDR5 6000mhz - 2TB nvme SSD
- PDF.js version: Don't know, whatever comes by default with FF127
- Is a browser extension: I've disabled them all

Steps to reproduce the problem:
1. open the pdf I sent with HW acceleration ON (you probably need to have same cpu/gpu, can't say for sure)
2. scroll down till the bottom
3. see it freeze like in my video 

What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/73554423/72143257-c0d3-43d0-bc66-bf22bb5ab225

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/73554423/2e01810f-865f-43fb-bebf-76bcfef37ba2

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by marco-c** [comment]
We are planning to disable HW acceleration for pdf.js, see https://bugzilla.mozilla.org/show_bug.cgi?id=1902012.

**Comment by Minibus93** [comment]
Sorry to re-open this, but in FF129 the issue is still present.

Is the merged pull request not added yet in the stable release?

No hurry at all, just trying to understand if the issue is still present or if another one appeared :)

**Comment by marco-c** [comment]
@Minibus93 could you try again in the latest Firefox Nightly?
