### ISSUE TITLE
Deactivate High Contrast Mode on pdfs only

### ISSUE THREAD

**Issue by fermofran** [mozilla/pdf.js#18285]
Configuration:
- Web browser and its version: Firefox 127.0
- Operating system and its version: Windows 11

Hello, 
I have installed a custom high contrast mode for Windows 11 and I've been really liking it. I thought I would run into a bunch of issued like not finding buttons or things like that but this works remarkably well. But there's one problem.
On Firefox the pdfs also get affected by this high contrast mode and end up in a weird low-bit monochrome version. 
I don't like that and I want to deactivate it but If I do so it deactivates the hcm for all firefox when I only want it turned off for pdf reading. 

I leave an image with how the pdf looks on firefox compared to Edge, I would like firefox to display it as edge does without deactivating my High Contrast Mode.

Is it possible??

![Uploading Screenshot 2024-06-18 171827.png…]()

**Comment by calixteman** [comment]
In Firefox, with the builtin viewer, you can remove the hcm filter used when rendering the pdf, in setting `pdfjs.pageColorsBackground` or `pdfjs.pageColorsForeground` to an empty string.

![image](https://github.com/mozilla/pdf.js/assets/5641725/7b3011e7-23cb-4501-add0-9c763c30f9b4)

**Comment by fermofran** [comment]
thank you so much!! that solved it
