### ISSUE TITLE
PDF Text is rendered as transparent

### ISSUE THREAD

**Issue by tclain-pillar** [mozilla/pdf.js#18298]
Attach (recommended) or Link to PDF file here: 
[example-malformed.pdf](https://github.com/user-attachments/files/15908428/example-malformed.pdf)

Configuration:
- Web browser and its version: Chrome
- Operating system and its version:  MacOS Ventura 3.0 (22A380)
- PDF.js version: used the viewer (https://mozilla.github.io/pdf.js/web/viewer.html) : PDF.js: 4.4.97
- Is a browser extension: no

Steps to reproduce the problem:
1. open the pdf with https://mozilla.github.io/pdf.js/web/viewer.html
2. most of the text will be transparent

What is the expected behavior? (add screenshot)

<img width="839" alt="image" src="https://github.com/mozilla/pdf.js/assets/99363042/7b8cb893-2968-455f-a842-94fc86ef6fdf">

What went wrong? (add screenshot)

<img width="1071" alt="image" src="https://github.com/mozilla/pdf.js/assets/99363042/8d1dab75-da8f-4b9e-87e2-19c5f02e799d">

The following warnings are displayed in the js console:

```
Warning: getOperatorList - ignoring XObject: "FormatError: Bad encoding in flate stream".
VM31 jam-console-devtools.js:1 Warning: Knockout groups not supported.
util.js:373 Warning: getTextContent - ignoring XObject: "FormatError: Bad encoding in flate stream".
util.js:373 Warning: getOperatorList - ignoring XObject: "FormatError: Bad encoding in flate stream".
VM31 jam-console-devtools.js:1 Warning: Knockout groups not supported.
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by tclain-pillar** [comment]
Thanks for the prompt fix.

I am not used by the release process of pdf.js,

What's the usual timeline for a fix to drip down in the npm package ?

Thanks again :-)

**Comment by timvandermeij** [comment]
We usually make a release at the end of every month, unless release blockers are identified before that time.
