### ISSUE TITLE
Data in formfields with same id (duplicates) are not saved when saving PDF

### ISSUE THREAD

**Issue by martinjo** [mozilla/pdf.js#18291]
Attach (recommended) or Link to PDF file here:
[Test.pdf](https://github.com/user-attachments/files/15898419/Test.pdf)

Configuration:
- Web browser and its version: Firefox v127.0 (64-bit)
- Operating system and its version: MacOS 14.5 (23F79)
- PDF.js version: Not sure. The one included in Firefox
- Is a browser extension: No

Steps to reproduce the problem:
1. Open Test.pdf and fill in one of the date fields.
2. The other date field will also update the entered value (the date fields have the "field id", this is intentional).
3. Download the pdf with the date field filled in.
4. Open the downloaded PDF.
5. The value entered in the date field is not saved.

What is the expected behavior?
I was expecting that the value I entered in the field would be saved when I download the PDF. All other fields (that does not share id with another field) are saved.

**Comment by ArmaandeepSingh** [comment]
Hi @martinjo, Would you be able to share a video of this issue as an attachment if that sounds feasible to you?

**Comment by calixteman** [comment]
I suppose the date fields are the two ones called `dagens_datum`, correct ? I only see one field with a date inside (the one called `personnummer`).
So if I'm correct, I don't manage to reproduce your issue either with Firefox nightly or with Firefox 127.0 on Windows 11.

**Comment by ArmaandeepSingh** [comment]
Yes @calixteman, I could also not reproduce it on my local. However I think he is mentioning the fields in the right with the text Dagens datum.
