### ISSUE TITLE
`pdfjsLib` is not exposed in the minified legacy build

### ISSUE THREAD

**Issue by sergiubologa** [mozilla/pdf.js#18290]
Configuration:
- Web browser and its version: Chrome 126.0.6478.62
- Operating system and its version: Windows
- PDF.js version: 4.3.136
- Is a browser extension: no

Steps to reproduce the problem:
1. Install the version 4.3.136
2. Search in the `node_modules\pdfjs-dist\legacy\build\pdf.min.mjs` file for `pdfjsLib` string.

What is the expected behavior? (add screenshot)
It should be found and exposed on the window object when loaded in the browser.

What went wrong? (add screenshot)
The `pdfjsLib` is not exposed anymore. It is exposed instead on all other build options:
- `node_modules\pdfjs-dist\legacy\build\pdf.mjs`
- `node_modules\pdfjs-dist\build\pdf.min.mjs`
- `node_modules\pdfjs-dist\build\pdf.mjs`

I [can see](https://github.com/mozilla/pdf.js/blob/9dbe4c246b1bbb08c423f3a98b7b25ce1e2c240f/gulpfile.mjs#L463) that the `tweakWebpackOutput` function in the gulpfile expects the string `",__webpack_exports__={};"` to exist in the minified file. But looking at the published minified file it looks like this `var __webpack_exports__={};`. Is this a webpack issue?

**Comment by sergiubologa** [comment]
@timvandermeij when will this be released?

**Comment by timvandermeij** [comment]
We normally create a new release at the end of every month, unless release blockers are identified before that time.
