### ISSUE TITLE
Error occurred in rendering the page while previewing certain PDFs

### ISSUE THREAD

**Issue by ly269nva** [mozilla/pdf.js#18309]
Attach (recommended) or Link to PDF file here: 
[test.pdf](https://github.com/user-attachments/files/15921995/big0.pdf)

Configuration:
- Web browser and its version:  Microsoft Edge 版本 126.0.2592.61 (正式版本) (64 位)
                                                   双核浏览器   版本 6.1.1.12（64 位）内核版本: Chromium 101.0.4951.64
- Operating system and its version:  win11
- PDF.js version: PDF.js v1.9.426 (build: 2558a58d)
- Is a browser extension: no

Steps to reproduce the problem:
1.  start tomcat
2.  visit viewer.html with 

What is the expected behavior? (add screenshot)
show content of pdf

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/31555480/4d44abc4-d773-4178-80f0-9ca127125d05)
PDF.js v1.9.426 (build: 2558a58d)
信息：Cannot read properties of null (reading 'get')
堆栈：TypeError: Cannot read properties of null (reading 'get')
    at PartialEvaluator_hasBlendModes [as hasBlendModes] (http://localhost:8180/test/pdf/build/pdf.worker.js:16885:35)
    at http://localhost:8180/test/pdf/build/pdf.worker.js:29289:42
    at async Promise.all (index 0)
![image](https://github.com/mozilla/pdf.js/assets/31555480/fbc8a887-8ba3-491b-afd3-2a05cb87d6b5)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
![image](https://github.com/mozilla/pdf.js/assets/31555480/9b7cc788-dbf3-4757-bc7e-725c391a3b45)

**Comment by ly269nva** [comment]
the graphicState is null

**Comment by Snuffleupagus** [comment]
> PDF.js version: PDF.js v1.9.426 (build: [2558a58](https://github.com/mozilla/pdf.js/commit/2558a58dbb8f367470afe648647d9480c63048ef))

That version is ***seven years old*** and thus obviously no longer supported, please make sure that you use an up-to-date version *before* reporting a bug or asking for help!
Please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
