### ISSUE TITLE
[Feature]: add signature panel in pdf.js viewer to view signature information like Certificate/PEM

### ISSUE THREAD

**Issue by insinfo** [mozilla/pdf.js#18327]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

add signature panel in pdf.js viewer to view signature information like Certificate/PEM

![image](https://github.com/mozilla/pdf.js/assets/12227024/d8951231-3266-4b1e-bd05-e747eafb6799)

### Other PDF viewers

![image](https://github.com/mozilla/pdf.js/assets/12227024/c0605f2f-a53a-4874-a546-6d2d687815ae)

**Comment by Snuffleupagus** [comment]
Without issue #13351 implemented this really doesn't seem meaningful to consider doing; should we WONTFIX this for now?

**Comment by timvandermeij** [comment]
Yes, and I image such a panel could be part of the validation work so users can easily see which signatures are present and if they are verified or not. Let's track it in that issue indeed.
