### ISSUE TITLE
[Bug]: pdf background rendering as transparent, makes documents unreadable

### ISSUE THREAD

**Issue by ebardie** [mozilla/pdf.js#18347]
### Attach (recommended) or Link to PDF file

[From Punched Cards To Flat Screens: A Technical Autobiography by Philip Haze](https://github.com/user-attachments/files/16041217/CIHK.pdf)

### Web browser and its version

Firefox 126

### Operating system and its version

NixOS 

### PDF.js version

Whatever version is built in to the Firefox releases above

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Load any PDF.  That's it.

I'm running X.org on NVidia and Linux, and have Picom as a compositor. 

[lshw.txt](https://github.com/user-attachments/files/16041401/lshw.txt)

Before recent FF releases this problem wasn't happening.

### What is the expected behavior?

The PDF attahed to this issue should look like it's rendering on Google Drive:
 
![Google Drive rendering](https://github.com/mozilla/pdf.js/assets/724661/7ac8e91c-8f01-480b-95ec-b5907c4e6e95)

### What went wrong?

But what happens with all PDFs for the past couple of releases of FF is that I can see my desktop rendered in place of the PDF's background:

![Firefox rendering](https://github.com/mozilla/pdf.js/assets/724661/91945ddc-96ef-42c1-a25e-1a5b9ee6d2a2)

The clouds and checker board pattern is my desktop image, but as you can see the PDF page text is still rendered.

### Additional context

PDFs render properly with the latest version of the extension loaded in Chrome Stable, so this looks like a FF related issue?

Mine is not the only instance of this happening.  I came here via  https://www.reddit.com/r/firefox/comments/1dkih34/pdf_rendering_error/  which has a comment recommending leaving a report here.

**Comment by ebardie** [comment]
I thought I was already running FF127, but when I went to get the "More troubleshooting information" from the "Help" menu, I wasn't.

So rather than retype all this info, I submitted the Issue, restarted FF since I had installed FF 127, and lo, the problem is fixed \o/

**Comment by calixteman** [comment]
It's very likely a dup of https://bugzilla.mozilla.org/show_bug.cgi?id=1904707.
