### ISSUE TITLE
[bug]: newer versions of PDF.js (the underlying PDF viewer used by Zotero and Firefox) force page-by-page scrolling mode

### ISSUE THREAD

**Issue by MoYuXianR** [mozilla/pdf.js#18364]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

More than 10,000 pages of pdfs will force a locked scrolling

**Comment by Snuffleupagus** [comment]
This is done on purpose, to make all pages of very long documents accessible; please see PRs #18189 and #14324.

**Comment by MoYuXianR** [comment]
In previous versions it could be good to see whether the
Is it possible to give the user an option to lift the restriction for high performance computers

**Comment by MoYuXianR** [comment]
I was thinking that you can achieve dynamic loading rendering, for large pdf documents, do not need to load a one-time loading, each time to load a little bit for the performance of a little bit of the configuration of the use of the user can be liberalized restrictions
