### ISSUE TITLE
[Bug]: node 16 install 3.6.172 broken by path2d-polyfill@^2.0.1 (which now mathed 2.1.1 with node 18 limit)

### ISSUE THREAD

**Issue by zhaojjiang** [mozilla/pdf.js#18392]
### Attach (recommended) or Link to PDF file

not pdf code bug

### Web browser and its version

any

### Operating system and its version

any

### PDF.js version

3.6.172

### Is the bug present in the latest PDF.js version?

No

### Is a browser extension

No

### Steps to reproduce the problem

`yarn add pdfjs-dist@~3.6.172`

### What is the expected behavior?

successfully installed

### What went wrong?

install broken by path2d-polyfill engine limit

### Additional context

pdfjs-dist@~3.6.172 is the latest version for node 16, but broken by its dependency path2d-polyfill@^2.0.1,
now path2d-polyfill@^2.0.1 mathes its version 2.1.1, which not compatible with node 16

**Comment by Snuffleupagus** [comment]
> ### PDF.js version
> 
> 3.6.172

That version is no longer supported and will not receive any updates/fixes, please update to the latest PDF.js release.

> ### Additional context
> 
> pdfjs-dist@~3.6.172 is the latest version for node 16,

Node.js 16 has been unmaintained since 2023-09-11, which means that it may contain security vulnerabilities.
