### ISSUE TITLE
Fix unit test "caches image resources at the document/page level as expected (issue 11878)"

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18403]
This unit test failed most recently in http://54.193.163.58:8877/0936bcbf5dcdb06/output.txt on Windows, but has failed a couple of times before on Linux too. The log line is:

```
TEST-UNEXPECTED-FAIL | caches image resources at the document/page level as expected (issue 11878) | in firefox | Expected 893 to be less than 832.5. 
```

We should investigate why this happens sometimes because as far as I have seen this is the only intermittent we have left in the unit tests.

**Comment by Snuffleupagus** [comment]
This unit-test was already tweaked once in PR #17663, maybe we should try changing the divisor to `3` instead?
Obviously comparing parsing/rendering times like this isn't great, but I don't know how we'd test this otherwise.

**Comment by timvandermeij** [comment]
Yes, I also don't have a better suggestion than that. I found that in https://github.com/mozilla/pdf.js/blob/bb3e3164e6dae3c0d7470603278b5262bce7c3fc/test/unit/api_spec.js#L4210-L4212 we use a divisor of 2 and I don't recall having seen that one fail, so I have made the PR above to go use that divisor for this test too for consistency.
