### ISSUE TITLE
[Bug]: Browsers marked as supported do not implement Promise.withResolvers

### ISSUE THREAD

**Issue by c-oreills** [mozilla/pdf.js#18446]
### Attach (recommended) or Link to PDF file

N/A

### Web browser and its version

Chrome 98

### Operating system and its version

MacOS

### PDF.js version

4.3.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open a PDF with Chrome 98 (nominally supported). It should error with

```
Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)
```

because Chrome 98 does not implement `Promise.withResolvers`.

### What is the expected behavior?

The list in `gulpfile.mjs` [ENV_TARGETS](https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs#L83) should only specify [Browser versions that support `Promise.withResolvers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility).

Alternatively a polyfill for `Promise.withResolvers` should be included.

### What went wrong?

The list is outdated and many browser versions in it do not support `Promise.withResolvers`. No polyfill is provided.

**Comment by Snuffleupagus** [comment]
> Alternatively a polyfill for `Promise.withResolvers` should be included.

A polyfill is included in the `legacy` builds, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by c-oreills** [comment]
Thank you!
