### ISSUE TITLE
Upgrade `streamqueue` to version 2.0.0

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18474]
This dependency got updated after almost seven years, but likely because of that large timespan it also contains large changes. The changelog can be found at https://github.com/nfroidure/streamqueue/blob/main/CHANGELOG.md, but at this point in time it's blocked because it only supports Node >= 20 and currently we still support Node 18 LTS. This issue therefore tracks upgrading this dependency later once we dropped Node 18 support.

**Comment by Snuffleupagus** [comment]
At the risk of asking a stupid question, but could we perhaps replace this dependency with https://github.com/gulpjs/ordered-read-streams instead?

**Comment by timvandermeij** [comment]
I'm not sure because I don't know too much about what `streamqueue` does exactly, but it's definitely something we should check out first because that might avoid having to do this (and also reduce the number of dependencies which can't hurt either).

**Comment by Snuffleupagus** [comment]
The reason that I hope that the existing `ordered-read-streams` package could be a drop-in replacement are the following observations.

 - Note this helper function for creating something from a string: https://github.com/mozilla/pdf.js/blob/98e772727e70dcad6433b5f02e027d6724b912f4/gulpfile.mjs#L172-L184

 - In at least one spot we're using that helper function as input to the `ordered`-function: https://github.com/mozilla/pdf.js/blob/98e772727e70dcad6433b5f02e027d6724b912f4/gulpfile.mjs#L925-L928

 - Now note how similar the `createStringSource` and `createTestSource` helper functions look: https://github.com/mozilla/pdf.js/blob/98e772727e70dcad6433b5f02e027d6724b912f4/gulpfile.mjs#L666-L725
 
 - Finally, note one example of how `createTestSource` is being using in: https://github.com/mozilla/pdf.js/blob/98e772727e70dcad6433b5f02e027d6724b912f4/gulpfile.mjs#L1709-L1714

**Comment by timvandermeij** [comment]
Nice find! It'd require careful testing, but this does make sense and hopefully we can just replace the dependency then.

**Comment by timvandermeij** [comment]
Unfortunately a replacement with `ordered-read-streams` doesn't work after trying this. While both return the output of the streams in order, the key difference between them turns out to be that `streamqueue` processes the readable streams one by one whereas `ordered-read-streams` processes all of them at once (thereby in our case triggering _all_ test processes at once) and reorders the output internally to ensure an ordered return value. In other words, `ordered-read-streams` runs the input streams in parallel whereas `streamqueue` does so in series.

However, I think I have an alternative solution that would also get rid of `streamqueue`, while still running everything in series, that I'm trying out now.
