### ISSUE TITLE
[Feature]: Simple API for custom search for PDF.js embedders

### ISSUE THREAD

**Issue by nicolo-ribaudo** [mozilla/pdf.js#18482]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

PDF.js offers good search support out of the box that closely matches Firefox's search functionality. However, websites/apps embedding PDF.js might want to use their own search logic to match how it works in the rest of their website/app.

Examples of similar features request in the past:
- https://github.com/mozilla/pdf.js/pull/17988
- https://github.com/mozilla/pdf.js/pull/16285
- https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/304 (this is in an Angular wrapper for pdf.js)

The current way of doing so is to copy&paste the `PDFFindController` class, and writing the custom logic in the `#calculateMatch` function. This makes it way more complex than what it could be: most of the logic in `PDFFindController` is not specific to the matching algorithm but to how PDF.js renders the DOM.

It would be very helpful for consumers of the library if `PDFFindController` exposed a way to use a different matching algorithm. To minimize the maintenance burden on PDF.js itself, this hypothetical API should:
- only expose the minimum necessary information to implement search, and not any internal logic. This makes it easy to refactor `PDFFindController` avoiding breaking changes for consumers
- be actually used in the "main path", and not be some code that is not actually used by PDF.js itself. This avoid having duplicate untested logic.

I would like to propose the following API:
```js
new PDFFindController({
  ...existing options...,
  matcher(query, pageContent, pageIndex) {
    return [
      { index: <match start>, length: <match length> },
    ];
  }
});
```
with the default implementation of `matcher` being what PDF.js currently does.

I have a wip implementation that I'd be happy to show.

**Comment by Snuffleupagus** [comment]
Personally I'm not entirely convinced that we want to support even a simple API for this, since doing "nothing" here is guaranteed to not cause any future work for the core contributors.
On the other hand, even a simple API will lead to work upfront and then also cause a non-zero amount of maintenance/support burden later. Given that keeping the general PDF.js library running outside of Firefox is already a significant amount of work, adding even more to that feels not great (especially since no one is sponsoring general maintenance of the library).

**Comment by marco-c** [comment]
Agreed, OK to accept something like this as long as it really doesn't increase the maintenance burden too much and as long as we can count on you for some maintenance related to this in the future.
