### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by AxBTe** [mozilla/pdf.js#18489]
Hello, I've been led here by a kind user on reddit who told me to post my issue here since it my also help. He told me to report my specific problem.
I was using firefox for reading and highlighting a PDF, one I had downloaded for studying purposes. I wanted to save the PDF in the same folder it came from, but as a default it went to another one. It was only a slight inconvenience at first, just wanting to make sure i wouldn't lose the marks. But when I closed it on accident and went to open it again I found my settings were altered. I never use PDFs, I like to print, but since asking a friend for a nice PDF reader and him telling me it was firefox and me being a firefox user I thought of giving it a go. Now, picture me opening the PDF with some of the viewing settings altered to a preferred viewing style I just found, to find them all reverted.
That's the issue, I just think that maybe making the browser remember where the PDF comes from and it's settings would be nice. I detailed everything just in case it's something to do with my laptop. Thanks in advance.

**Comment by timvandermeij** [comment]
> i wouldn't lose the marks

To me this suggests that highlight annotations are not saved as expected...

> viewing settings altered to a preferred viewing style

but this makes it sound like it's not related to highlight annotations but rather to the viewer state itself?

In any case, it sounds like a bug, so please file it as such using the "Bug report" option on https://github.com/mozilla/pdf.js/issues/new/choose which gives a simple form that provides us with all the required details to debug the issue. At the very least we'll need the exact steps to reproduce the issue and the PDF file for which the issue happens. Thanks.

**Comment by AxBTe** [comment]
First, sorry if I was misleading I'm new to this and may have been too formal. The thing itself was that I toyed with the settings, then saved, and closed on accident. The things I had highlighted didn't save and the setting that I had established for the document (I changed how I was seeing the document and the way the pages were shown, or something like that) weren't saved

**Comment by timvandermeij** [comment]
Can you reproduce the issue with https://mozilla.github.io/pdf.js/web/viewer.html which is the most recent version of PDF.js? The viewer should, and in my testing at least does, persist changes to e.g. the page scroll and spread modes, and the place in the particular document where you left off reading, so I'm not really sure which kind of settings you mean that weren't saved. It would help to have steps to reproduce the issue in the following way:

1. Open https://mozilla.github.io/pdf.js/web/viewer.html.
2. Open PDF file <link to PDF file>.
3. Click on button X.
4. Notice effect Y. I had expected effect Z to happen instead.
