### ISSUE TITLE
[Feature]: Loading indicator that appears before PDF has started transferring

### ISSUE THREAD

**Issue by catmanjan** [mozilla/pdf.js#18522]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

PDF.js has a loading indicator which appears after the first GET request has begun, however if the URL to the PDF has to load before transferring (e.g. Content-Length is not known ahead of time so nothing can be done to notify PDF.js how long to wait) there is nothing to indicate anything is happening.

Some sort of indeterminate loading indicator should appear in this interval.

**Comment by Snuffleupagus** [comment]
The default viewer already has an indeterminate loadingBar for cases where the size of the PDF document isn't known, see https://github.com/mozilla/pdf.js/blob/f6b356eff753358bf3263d174dc0cf4852800edd/web/ui_utils.js#L716-L726 which uses the following CSS https://github.com/mozilla/pdf.js/blob/f6b356eff753358bf3263d174dc0cf4852800edd/web/viewer.css#L408-L439

Opening e.g. https://www.uni-muenster.de/imperia/md/content/ziv/pdf/printpay_flyer.pdf in Firefox Nightly 130, with its built-in PDF Viewer, triggers the indeterminate loadingBar for me.
