### ISSUE TITLE
[Bug]: Form Field Calculation Triggering Unexpectedly or not getting trigger at all.

### ISSUE THREAD

**Issue by paritosh-mahale** [mozilla/pdf.js#18532]
### Attach (recommended) or Link to PDF file

**Description:**

I am using the pdf.js library to rendering PDFs that contain form fields with embedded formulas. When I open the PDF in any pdf reader and enter values, the formula in the specific field is triggered, and the result is calculated correctly for that field only.

However, when using pdf.js, entering a value in one field causes the formulas in all fields to be calculated, not just the one being edited.

![image](https://github.com/user-attachments/assets/1f32da25-949e-4ee8-8368-2af9f54beda2)

In another pdf when I am entering any value it is suppose to do an calculation like this

![image](https://github.com/user-attachments/assets/4dc42d6c-9dc9-41ab-9210-12e507862085)

but is not at all getting triggered

![image](https://github.com/user-attachments/assets/c1e86cea-881b-43b1-8d4d-d8ec2aadf542)

**Expected Behavior:**
Entering a value in a specific form field should trigger the formula and calculate the result for that field only.

I have been struggling with this issue for the past 2-3 days and would greatly appreciate any assistance or guidance. Thank you in advance for your help.

### Web browser and its version

firefox 127.0

### Operating system and its version

Linux 

### PDF.js version

pdfjs-dist: 3.11.174

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open any pdf which is having formulas in it.

### What is the expected behavior?

Entering a value in a specific form field should trigger the formula and calculate the result for that field only.

### What went wrong?

Either not triggering the calculation or triggering calculation for the filed which is not expected.

**Comment by calixteman** [comment]
We need to have the pdf to debug the potential issue: without it, it's impossible to guess what's wrong exactly.

**Comment by rahulrajpal2911** [comment]
Hi @calixteman 
Thank you for your prompt reply. Here I have attached a PDF for your reference. @paritosh-mahale  and I are working on this and found this issue.

![image](https://github.com/user-attachments/assets/b584a615-9623-420e-ad68-0b06f33b4695)

**Comment by calixteman** [comment]
An empty product should be 0 and not 1:
https://github.com/mozilla/pdf.js/blob/63371eaed8326f1ba4d4cdf6a1360a9333bd0bcf/src/scripting_api/aform.js#L524

**Comment by rahulrajpal2911** [comment]
@calixteman Will this check resolve the other issue as well? In the PDF snapshot shared by @paritosh-mahale, you can see that the amount is being calculated from the rate by default when we enter the quantity in any row. This is affecting the solution we created using pdf.js.

**Comment by calixteman** [comment]
I don't know, you didn't provide the pdf for the other issue...
It'd be a way easier for everybody and make a good use of our time to provide the required information when you file the bug:
![image](https://github.com/user-attachments/assets/2da772e3-664e-439f-b49f-e4017a449adc)
Isn't it (I mean the sentence `Attach (recommended) or Link to PDF file`) clear enough ?

**Comment by Snuffleupagus** [comment]
In addition to everything said in https://github.com/mozilla/pdf.js/issues/18532#issuecomment-2262355425, please also note that it's not really "allowed" to report multiple different problems in one issue (since that makes tracking things much more difficult).

**Comment by rahulrajpal2911** [comment]
@calixteman  and @Snuffleupagus I understand you said and I am aligned with that. Your time is valuable, and since this is an open-source library, the support we are receiving from you is a significant help for us. The other PDF is restricted and cannot be shared in a public forum. If possible, could we share it via email? This is the last piece pending in our solution, and we are a bit worried about it.

Thank you for providing us with this wonderful library. Cheers!

**Comment by rahulrajpal2911** [comment]
@calixteman / @Snuffleupagus  Here is the attached PDF. We recreated it without restrictions.

[calculation-issue.pdf](https://github.com/user-attachments/files/16454414/calculation-issue.pdf)
