### ISSUE TITLE
pdfjs How to display the digital signature?

### ISSUE THREAD

**Issue by zengjingxw** [mozilla/pdf.js#18557]
### Discussed in https://github.com/mozilla/pdf.js/discussions/18556

<div type='discussions-op-text'>

<sup>Originally posted by **zengjingxw** August  5, 2024</sup>
Unable to display signature field information in pdfjs.
![image](https://github.com/user-attachments/assets/b9a6cc89-df07-4334-b3db-c297342ee667)
In the pdf viewer tool can show.
![image](https://github.com/user-attachments/assets/d8e6ab10-8ebd-4f2a-b81e-bc0863469872)

[demonstration Files](https://github.com/user-attachments/files/16490409/test111.pdf)
</div>

**Comment by Snuffleupagus** [comment]
You must fill out *all fields* of the issue template properly when reporting a bug; please see https://github.com/mozilla/pdf.js/issues/new?assignees=&labels=&projects=&template=bug.yml&title=%5BBug%5D%3A+
