### ISSUE TITLE
[Bug]: 在移动端ios系统苹果手机上预览时显示白屏，也不报错，在安卓手机上是正常显示的

### ISSUE THREAD

**Issue by baiyajin** [mozilla/pdf.js#18553]
### Attach (recommended) or Link to PDF file

在移动端ios系统苹果手机上预览时显示白屏，也不报错，在安卓手机上是正常显示的

### Web browser and its version

使用的是 uniapp 中的 web-view 组件来预览

### Operating system and its version

华为跟苹果

### PDF.js version

4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

Yes

### Steps to reproduce the problem

开发的uniapp使用web-view预览，运行到苹果手机就白屏，安卓跟h5正常

### What is the expected behavior?

能在苹果手机上显示

### What went wrong?

不兼容苹果

**Comment by timvandermeij** [comment]
Closing since we can't help if the bug report is not in English and not all details have been provided (mainly the PDF file).

**Comment by sunny-wanghaiqing** [comment]
> ### Attach (recommended) or Link to PDF file
> 在移动端ios系统苹果手机上预览时显示白屏，也不报错，在安卓手机上是正常显示的
> 
> ### Web browser and its version
> 使用的是 uniapp 中的 web-view 组件来预览
> 
> ### Operating system and its version
> 华为跟苹果
> 
> ### PDF.js version
> 4.5.136
> 
> ### Is the bug present in the latest PDF.js version?
> Yes
> 
> ### Is a browser extension
> Yes
> 
> ### Steps to reproduce the problem
> 开发的uniapp使用web-view预览，运行到苹果手机就白屏，安卓跟h5正常
> 
> ### What is the expected behavior?
> 能在苹果手机上显示
> 
> ### What went wrong?
> 不兼容苹果
> 
> ### Link to a viewer
> _No response_
> 
> ### Additional context
> _No response_

解决了不
