### ISSUE TITLE
Update the Babel plugin to remove empty static initialization blocks

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#18559]
We have [static initialization blocks](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks) that include pre-processor statements which make them conditionally empty, note e.g. how the following source code:
https://github.com/mozilla/pdf.js/blob/c60c0d1c6df3a4e93da9d9ad4186eb07e837e024/src/display/api.js#L2016-L2054
is transformed into (in that case for the MOZCENTRAL build):
https://searchfox.org/mozilla-central/rev/b6671f4c3afdb2b36e63c9d176f98a5959907259/toolkit/components/pdfjs/content/build/pdf.mjs#10434

Hence it seems like a good idea to, if possible, extend the Babel plugin to remove static initialization blocks that become empty during building.

**Comment by nicolo-ribaudo** [comment]
I'll take a look
