### ISSUE TITLE
[Feature]: Host it on npm for best accessibility

### ISSUE THREAD

**Issue by kqvanity** [mozilla/pdf.js#18565]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

I currently have to clone and install other packages locally to spin up the viewer. I was wondering if you could easily provide this package on npm to be used as some kind of global CLI tool to load [local pdf](https://support.mozilla.org/en-US/questions/1221277) in the browser right away.

**Comment by timvandermeij** [comment]
The library is published to NPM as `pdfjs-dist`; please see https://www.npmjs.com/package/pdfjs-dist. The viewer is deliberately not distributed separately to not create confusion with the default viewer in Firefox; it can be used, but from https://mozilla.github.io/pdf.js/getting_started/#introduction:

> It can be a good starting point for building your own viewer. However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.
