### ISSUE TITLE
[Bug]: PDF.js not Performing Calculations on Interactive PDF Forms

### ISSUE THREAD

**Issue by paritosh-mahale** [mozilla/pdf.js#18561]
### Attach (recommended) or Link to PDF file

[Lowes Measure sheet (2).pdf](https://github.com/user-attachments/files/16494500/Lowes.Measure.sheet.2.pdf)

### Web browser and its version

Mozilla

### Operating system and its version

Linux

### PDF.js version

v4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached PDF document in Adobe Reader.
2. Enter values in the input fields.
3. Observe that the total is automatically calculated using the hidden per-unit price field.
4. Open the same PDF document using PDF.js.
5. Enter values in the input fields.
6. Notice that the total is not calculated.

### What is the expected behavior?

PDF.js should perform the same calculations as Adobe Reader when values are entered into the input fields.

![image](https://github.com/user-attachments/assets/e9bde406-5420-48bf-b1a0-839987b7cc78)

### What went wrong?

PDF.js does not perform the calculations, and the total remains unchanged when values are entered into the input fields.

![image](https://github.com/user-attachments/assets/2ebecda2-0e13-4201-bfda-79c6d2d264fc)

### Additional context

I am experiencing an issue with PDF.js when it comes to interactive PDF forms that involve calculations. I have a PDF document containing input fields for user data entry and hidden fields that perform calculations based on the input values. Specifically, when I open the document in Adobe Reader, entering values in the input fields automatically retrieves a per-unit price from a hidden field and calculates the total by multiplying the per-unit price by the quantity entered. However, this calculation is not happening when I open the same document using PDF.js.

**Comment by Snuffleupagus** [comment]
> I am experiencing an issue with PDF.js when it comes to interactive PDF forms that involve calculations. I have a PDF document containing input fields for user data entry and hidden fields that perform calculations based on the input values. Specifically, when I open the document in Adobe Reader, entering values in the input fields automatically retrieves a per-unit price from a hidden field and calculates the total by multiplying the per-unit price by the quantity entered. However, this calculation is not happening when I open the same document using PDF.js.
> 
> Expected result : ![image](https://private-user-images.githubusercontent.com/8596818/355069476-e9bde406-5420-48bf-b1a0-839987b7cc78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQxNDcsIm5iZiI6MTcyMjg1Mzg0NywicGF0aCI6Ii84NTk2ODE4LzM1NTA2OTQ3Ni1lOWJkZTQwNi01NDIwLTQ4YmYtYjFhMC04Mzk5ODdiN2NjNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTAzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4ZmY4N2I2OGVlYmJiNDU5Y2ZiMjM5MzRhNzI1YmExYjc5MDk5ODEyNzM3MTA0MzllZTZmNjhkZDg0MWY1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.feWL86ScWOHw0xEETj-nabeyu0beqjjBG-uvA2LZ7Qk)
> 
> actual result: ![image](https://private-user-images.githubusercontent.com/8596818/355069535-2ebecda2-0e13-4201-bfda-79c6d2d264fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQxNDcsIm5iZiI6MTcyMjg1Mzg0NywicGF0aCI6Ii84NTk2ODE4LzM1NTA2OTUzNS0yZWJlY2RhMi0wZTEzLTQyMDEtYmZkYS03OWM2ZDJkMjY0ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTAzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YyNzEyNjlmNjhjMDI4ZTQyYzI1NmM0NjFkYTI4OTQ5ZGEzN2I2OWRjMDhkYzNlZDUzZDUxNGU0M2FmNDE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1oewZHskpXbgbEwYxCsz6mj9HdW6wfHOE1rusV8QXE8)

Please place such content and screen-shots under the *appropriate* headings below, rather than dumping it at the top of the issue!

**Comment by paritosh-mahale** [comment]
> > I am experiencing an issue with PDF.js when it comes to interactive PDF forms that involve calculations. I have a PDF document containing input fields for user data entry and hidden fields that perform calculations based on the input values. Specifically, when I open the document in Adobe Reader, entering values in the input fields automatically retrieves a per-unit price from a hidden field and calculates the total by multiplying the per-unit price by the quantity entered. However, this calculation is not happening when I open the same document using PDF.js.
> > Expected result : ![image](https://private-user-images.githubusercontent.com/8596818/355069476-e9bde406-5420-48bf-b1a0-839987b7cc78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQxNDcsIm5iZiI6MTcyMjg1Mzg0NywicGF0aCI6Ii84NTk2ODE4LzM1NTA2OTQ3Ni1lOWJkZTQwNi01NDIwLTQ4YmYtYjFhMC04Mzk5ODdiN2NjNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTAzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI4ZmY4N2I2OGVlYmJiNDU5Y2ZiMjM5MzRhNzI1YmExYjc5MDk5ODEyNzM3MTA0MzllZTZmNjhkZDg0MWY1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.feWL86ScWOHw0xEETj-nabeyu0beqjjBG-uvA2LZ7Qk)
> > actual result: ![image](https://private-user-images.githubusercontent.com/8596818/355069535-2ebecda2-0e13-4201-bfda-79c6d2d264fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQxNDcsIm5iZiI6MTcyMjg1Mzg0NywicGF0aCI6Ii84NTk2ODE4LzM1NTA2OTUzNS0yZWJlY2RhMi0wZTEzLTQyMDEtYmZkYS03OWM2ZDJkMjY0ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMTAzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YyNzEyNjlmNjhjMDI4ZTQyYzI1NmM0NjFkYTI4OTQ5ZGEzN2I2OWRjMDhkYzNlZDUzZDUxNGU0M2FmNDE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1oewZHskpXbgbEwYxCsz6mj9HdW6wfHOE1rusV8QXE8)
> 
> Please place such content and screen-shots under the _appropriate_ headings below, rather than dumping it at the top of the issue!

Hi @Snuffleupagus  Updated as you mention, Thank you for highlighting this.

**Comment by calixteman** [comment]
If I enter a rate for Aluminum, then there's an error with either pdf.js or Acrobat, you should fix it and provide us a correct file.
If possible you should provide us a basic test case instead of a big file (it makes the debugging more complex).

**Comment by paritosh-mahale** [comment]
there is not issue in Acrobat, we have given you a same file that we received and it's breaking in pdf.js only. in acrobat is working fine.

Test case is : Whenever we add quantity, Rate get calculated with the help of hidden filed and whenever rate updates the total also get updated immediately.

**Comment by calixteman** [comment]
Please don't tell me there's no issue...
https://github.com/user-attachments/assets/f954b476-c632-4826-816b-c6ac396e86a6

**Comment by paritosh-mahale** [comment]
Please refer this recording, it's chrome browser and pdf.js
[Uploading screen-capture (1).webm…]()

**Comment by paritosh-mahale** [comment]
Please refer this recording, it's chrome browser and pdf.js
[screen-capture (1).webm](https://github.com/user-attachments/assets/f312d760-50aa-410d-a91e-07d0e6ad6519)

**Comment by calixteman** [comment]
It'd be nice to provide a clear STR instead of saying fuzzy things like "Enter values in the input fields.".
Really providing us a basic file with only 2,3 fields in order to clearly show what the problem is would be a way more helpful than a big pdf and fuzzy instructions to reproduce the issue.
See my answer in https://github.com/mozilla/pdf.js/issues/18561#issuecomment-2268840656, you answered me "there is not issue in Acrobat", I wrote something clear and if you test what I wrote in this comment in either Chrome, Acrobat or Firefox then it doesn't work correctly because of a wrong field name.
So again, please make a good use of our time in filing clear bug reports.

**Comment by calixteman** [comment]
The embedded JS code used to calculate fields value is either using unexisting fields or has some invalid JS code !! so when we evaluate the `C` callback, there are some exceptions we don't catch when our competitors does.

**Comment by rahulrajpal2911** [comment]
Hi @calixteman 
We understand that not all PDFs are causing trouble, but only this one. When we save it using any PDF viewer or editor, even some basic row-level multiplication is not happening. These PDFs are coming from a different source, and therefore, we are not allowed to edit them. We hope you understand our limitations. Also, with our limited expertise, we are not sure if this PDF is causing trouble.

**Comment by calixteman** [comment]
It isn't a problem to not have a basic test case if you aren't able to produce one, but the minimal thing you can do is to provide a clear STR, for example:
 - on page 2, click in the field Qty for the line Aluminum and add 123
 - click on the field below
 
 Expected results:
 - in the field Rate, we should have 12300
 - in the field Total (on the bottom of the page) we should have 12300
 
 Actual results:
 In both fields, Rate and Total, we've 0.

+ screenshots as you did.

**Comment by paritosh-mahale** [comment]
Hi @calixteman 
Please find below details:

Steps to reproduce:
1) Open PDF document and go to page no 2.
2) In "customer labor" table ( middle table) add Qty as 10 for Aluminum and click on next row in Qty column.

Expected behavior:
- Rate for Aluminum should get calculated automatically by multiplying  Qty by 10, so rate should become 100.
- Also the Total ( In red, below table) should also be get calculated as 100 ( it's an total of rate)

Screenshot of expected result (from Adobe Reader) 
![image](https://github.com/user-attachments/assets/97fad718-b9ba-46a4-b62c-70054f33c13d)



Actual behavior:
- The calculation is not getting trigger to calculate the rate and total based on Qty provided.

Screenshot of actual result (from pdf.js) 
![image](https://github.com/user-attachments/assets/8d6d0457-7ca5-47d1-b769-395983d819c1)
