### ISSUE TITLE
[Bug]: Can't display signature fields that are not digitally signed?

### ISSUE THREAD

**Issue by zengjingxw** [mozilla/pdf.js#18564]
### Attach (recommended) or Link to PDF file

[test111.pdf](https://github.com/user-attachments/files/16499042/test111.pdf)

### Web browser and its version

Google Chrome 127.0.6533.89

### Operating system and its version

Windows 11 Version 23H2

### PDF.js version

4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. https://mozilla.github.io/pdf.js/web/viewer.html upload the file
2. Can't display signature fields that are not digitally signed?
![image](https://github.com/user-attachments/assets/f98d6764-281b-445e-a2be-5aeadb6d5509)
3. In the pdf viewer tool can show.
![image](https://github.com/user-attachments/assets/65733800-a0b3-4adc-bf2f-2f5457886dd8)

### What is the expected behavior?

Signature fields in the pdf that are not signed can be displayed

### What went wrong?

Unable to show unsigned signature fields in pdfs

**Comment by timvandermeij** [comment]
This document contains two signature annotations, but both have an empty appearance stream (`% DSBlank` content in the AP -> N entry) so there isn't anything to actually draw visibly. The signature validation part is known and already tracked in #13351.

**Comment by zengjingxw** [comment]
> This document contains two signature annotations, but both have an empty appearance stream (`% DSBlank` content in the AP -> N entry) so there isn't anything to actually draw visibly. The signature validation part is known and already tracked in #13351.

Do signature annotations support on-page manipulation? Or is it just displaying it now without any manipulation?

**Comment by zengjingxw** [comment]
@timvandermeij 
Do signature annotations support on-page manipulation? Or is it just displaying it now without any manipulation?

**Comment by timvandermeij** [comment]
We only render signature annotations, so they cannot be verified or modified.
