### ISSUE TITLE
[Feature]: Add a generic interface or API for external implementations of AnnotationEditorLayer

### ISSUE THREAD

**Issue by TaTo30** [mozilla/pdf.js#18625]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

Hi Mozilla team.

I have been looking to implement AnnotationEditorLayer using the node package `pdfjs-dist` and searching on the source code I've noticed that is mandatory to use an _uiManager_ class to handle viewer events, user interactions and editors properties but this design is too difficult to brings up on custom solutions where the only features needed are adding, removing and saving annotations. Just for comparing `AnnotationLayer` and `TextLayer` are easy to implement with the current API.

I am well aware that your main focus is Firefox Viewer but could you consider add a generic API or interface on the medium/large term to allows dependents projects implement the editor layer with the most basic features: add/remove, save, drag/resize, without caring about keyboard events, multi-page dragging, toolbar options, etc.

**Comment by Snuffleupagus** [comment]
This unfortunately sounds like something that could/would add way too much code, complexity, and maintenance burden all for a feature that's unused (and untested) within the project itself.
Please also note that the Editor is still under very active development, which means that we need to be able to make changes as needed without worrying about maintaining an API-surface.
