### ISSUE TITLE
[Bug]: TypeError: Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)

### ISSUE THREAD

**Issue by YaoZhouZ** [mozilla/pdf.js#18631]
### Attach (recommended) or Link to PDF file

![cfeb79b96cbfea589bbbfb8e29a3fa7089a767499ea04eea46dc46e1b5c252feL1VzZXJzL2VkeS9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMzAxMjQxNjUyOF92Mi9JbWFnZUZpbGVzLzE3MjQxNTAxNDA1NDNfRDU5MjY1MEUtNTlBMy00ODYwLTk1MEItRDRDM0IzMkM5MDI3LnBuZw==](https://github.com/user-attachments/assets/ccd0baae-dcb6-4960-99da-dfc53e9b762e)

### Web browser and its version

safari17.3.1

### Operating system and its version

mac14.3.1 

### PDF.js version

4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.Unable to display PDF file and an error occurs when using the preview feature provided by pdf.js official.
2.Error occurs when opening PDF preview using Safari on macOS.

### What is the expected behavior?

TypeError: Promise.withResolvers is not a function. (In 'Promise.withResolvers()', 'Promise.withResolvers' is undefined)

### What went wrong?

![cfeb79b96cbfea589bbbfb8e29a3fa7089a767499ea04eea46dc46e1b5c252feL1VzZXJzL2VkeS9MaWJyYXJ5L0FwcGxpY2F0aW9uIFN1cHBvcnQvRGluZ1RhbGtNYWMvMzAxMjQxNjUyOF92Mi9JbWFnZUZpbGVzLzE3MjQxNTAxNDA1NDNfRDU5MjY1MEUtNTlBMy00ODYwLTk1MEItRDRDM0IzMkM5MDI3LnBuZw==](https://github.com/user-attachments/assets/09589cce-2e8a-4e82-9808-975054b11fd5)

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> [...]

Sorry, but a screen-shot makes no sense under that heading.

> ### Steps to reproduce the problem
> 
> 1.Unable to display PDF file and an error occurs when using the preview feature provided by pdf.js official.
> 2.Error occurs when opening PDF preview using Safari on macOS.

You need to use a `legacy`-build, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by No54** [comment]
chrome 117, same bug...
