### ISSUE TITLE
[Bug]: Safari renders transparency as solid colour

### ISSUE THREAD

**Issue by hubgit** [mozilla/pdf.js#18634]
With PDF.js v4, Safari is rendering solid colour where a PDF contains transparent images.

Firefox and Chrome both render the transparency correctly with PDF.js v4, and all browsers render the transparency correctly with PDF.js v2.

### Web browser and its version

Safari 17.6

### Operating system and its version

macOS 14.6.1

### PDF.js version

v4.5.136

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the attached PDF in [the demo viewer](https://mozilla.github.io/pdf.js/legacy/web/viewer.html).

[drop-shadow.pdf](https://github.com/user-attachments/files/16680089/drop-shadow.pdf)

### What is the expected behavior?

The drop shadow is rendered as partially transparent.

Chrome:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/f33b9c52-e95b-4b2c-b609-3fb38bba86a0">

Firefox:

<img width="548" alt="image" src="https://github.com/user-attachments/assets/867ae6dd-06ab-4332-9a76-f75426abd4e2">

### What went wrong?

The drop shadow is rendered as a solid block of colour.

Safari:

<img width="553" alt="image" src="https://github.com/user-attachments/assets/058558d1-a6e5-4d35-bfc9-0b99dd129664">

### Link to a viewer

https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by Snuffleupagus** [comment]
> With PDF.js v4, Safari is rendering solid colour where a PDF contains transparent images.
> 
> Firefox and Chrome both render the transparency correctly with PDF.js v4,

Given that it works in both Firefox and Chrome this unfortunately points to either a bug or a missing feature in the Safari browser *itself*, rather than an issue in the PDF.js library, hence this probably needs to be reported the Safari developers instead.

Please also note that we only list Safari as "mostly" supported in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> and all browsers render the transparency correctly with PDF.js v2.

The SoftMask handling in PDF.js has been re-factored in more times, to improve performance, so it's likely that we're now using functionality that Safari doesn't support properly.

**Comment by aeaton-overleaf** [comment]
I suspect it might be the issue described in [this StackOverflow post](https://stackoverflow.com/questions/64076018/globalalpha-not-working-with-globalcompositeoperation-on-safari), where the `globalAlpha` setting is not being recognised in combination with `globalCompositeOperation`. In fact, each of Chrome, Firefox and Safari render that example differently.

The closest WebKit bug I can find is [202459](https://bugs.webkit.org/show_bug.cgi?id=202459).

**Comment by hubgit** [comment]
I suspect it might be the issue described in [this StackOverflow post](https://stackoverflow.com/questions/64076018/globalalpha-not-working-with-globalcompositeoperation-on-safari), where the `globalAlpha` setting is not being recognised in combination with `globalCompositeOperation`.

Here's a very minimal reproduction which shows Safari not rendering the opacity when `globalCompositeOperation` is set to `destination-atop` (or `source-out`, but most other values for `globalCompositeOperation` seem fine):

```js
const canvas = document.querySelector("canvas");
const ctx = canvas.getContext("2d");
ctx.globalCompositeOperation = "destination-atop";
ctx.globalAlpha = 0.2;
ctx.beginPath();
ctx.rect(0, 0, 800, 800);
ctx.closePath();
ctx.fill();
```

The closest WebKit bug I can find is [202459](https://bugs.webkit.org/show_bug.cgi?id=202459).

**Comment by hubgit** [comment]
Reported upstream to WebKit: https://bugs.webkit.org/show_bug.cgi?id=278454

**Comment by mlevans0** [comment]
Another instance of this reported https://app.frontapp.com/open/cnv_cdzi5fl?key=PoLfZs4reYIsidQhLZDtDa6CTzoh337T

**Comment by calixteman** [comment]
@mlevans0 why are you commenting on a closed bug, which isn't finally related to pdf.js, and to share a non-public URL ?
