### ISSUE TITLE
[Feature]: distribute viewer to pdf-dist in npm

### ISSUE THREAD

**Issue by liudongmiao** [mozilla/pdf.js#18751]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

Currently, there are two distributions:
- releases via https://github.com/mozilla/pdf.js/releases
  - and online demo in https://mozilla.github.io/pdf.js/web/viewer.html and legacy version
- pdfjs-dist in npm

However, there is no viewer in pdfjs-dist, no `locale`, no `viewer.css`, `viewer.html`, and missing some images.

**Comment by Snuffleupagus** [comment]
> However, there is no viewer in pdfjs-dist, no `locale`, no `viewer.css`, `viewer.html`, and missing some images.

Sorry, but this is done on purpose since the viewer isn't intended to be used as-is; please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by liudongmiao** [comment]
@Snuffleupagus My question is like this, there are two **different** distributions.
If the releases doesn't include the viewer, then it's ok too.
However, the releases include the viewer, while the npm doesn't.

**Comment by liudongmiao** [comment]
duplicate as https://github.com/mozilla/pdf.js/issues/5609  https://github.com/mozilla/pdf.js/issues/5709 https://github.com/mozilla/pdf.js/issues/6545 https://github.com/mozilla/pdf.js/issues/7780 https://github.com/mozilla/pdf.js/issues/9127 https://github.com/mozilla/pdf.js/issues/9144 https://github.com/mozilla/pdf.js/issues/9210
