### ISSUE TITLE
[Bug]: Type4 shading isn't correctly rendered

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#18750]
### Attach (recommended) or Link to PDF file

The pdf has been found in the [PDFBox bug tracker](https://issues.apache.org/jira/projects/PDFBOX/issues/PDFBOX-5852?filter=allopenissues).
[minimal.pdf](https://github.com/user-attachments/files/17012258/minimal.pdf)

### Web browser and its version

Firefox nightly

### Operating system and its version

Windows 11

### PDF.js version

last one

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the pdf.

### What is the expected behavior?

In Chrome:
![image](https://github.com/user-attachments/assets/97ef4797-b180-4b1a-ad76-e7d5366d855a)
In Acrobat:
![image](https://github.com/user-attachments/assets/e6d8e6dd-5f40-494e-b75c-570e61905fda)

### What went wrong?

It depends of the zoom level: if it's to high nothing is drawn but if it's small enough we can see for example:
![image](https://github.com/user-attachments/assets/2a0de309-44a3-4696-874d-dac97df3dfd8)

**Comment by Snuffleupagus** [comment]
Could this be another duplicate of #16038, perhaps?

**Comment by calixteman** [comment]
Do you think that the wrong blue thing has the same cause as in #16038 ?

**Comment by Snuffleupagus** [comment]
Given that this seems to be using a *tiling* pattern with a /BBox that contains negative values, it *might* thus be related?

**Comment by calixteman** [comment]
I confirm it's a dupe of #16038.
