### ISSUE TITLE
[Bug]: "Find in Document" Feature Throws an Error and Spins Indefinitely

### ISSUE THREAD

**Issue by Austin-Berry-se** [mozilla/pdf.js#18767]
### Attach (recommended) or Link to PDF file

[PDF w Bookmarks.pdf](https://github.com/user-attachments/files/17066629/PDF.w.Bookmarks.pdf)

### Web browser and its version

Chrome Version 129.0.6668.59

### Operating system and its version

Windows 10

### PDF.js version

v4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Pull the latest version of the PDF viewer into a React solution.
2. Render a PDF and search for a word that exists in the document.

### What is the expected behavior?

The "Find in Document" feature should successfully search and highlight search terms within the document. This feature worked without error on v4.5.136.

### What went wrong?

A console error is thrown, and the feature spins indefinitely without completing the search.

![image](https://github.com/user-attachments/assets/47202ebb-e354-4548-89fb-1adc66751cc5)
![image](https://github.com/user-attachments/assets/be3c395f-cd2c-4d55-9c2a-0abc89dd5de4)

**Comment by Snuffleupagus** [comment]
WFM, when opening your document in https://mozilla.github.io/pdf.js/web/viewer.html and searching for various words (e.g. "the", "and", "all").

> ### Steps to reproduce the problem
>   1. Pull the latest version of the PDF viewer into a React solution.
>   2. Render a PDF and search for a word that exists in the document.

Sorry, but we cannot really provide support for various frameworks such as "React" since we're not using those.

> ### What went wrong?
> A console error is thrown, and the feature spins indefinitely without completing the search.

First of all, please note that log/error messages should always be provided *as text* rather than images.

Secondly, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Austin-Berry-se** [comment]
We identified that renaming the folder from "pdfjs-4.6.82-dist" to "PDFviewer" caused the issue. This problem is now resolved.
