### ISSUE TITLE
Fix the "Select text with the pointer hovering an existing highlight must check that an existing highlight is ignored on hovering" integration test

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18775]
This integration test fails consistently on _only_ the Windows bot with the following traceback (see http://54.193.163.58:8877/662f7dec318944a/output.txt):

```
Failures:
1) Highlight Editor Select text with the pointer hovering an existing highlight must check that an existing highlight is ignored on hovering
  Message:
[31m    In chrome: Expected 1 to equal 0.[0m
  Stack:
        at <Jasmine>
        at file:///C:/pdfjs/botio-files-pdfjs/private/662f7dec318944a/test/integration/highlight_editor_spec.mjs:1880:58
        at async Promise.all (index 1)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/662f7dec318944a/test/integration/highlight_editor_spec.mjs:1834:7)
```

The earliest occurrence I could find of this test failure is https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2336406803, so perhaps that patch introduced a regression (other than https://github.com/mozilla/pdf.js/pull/18716). We could try to check if it still fails without that patch, and if so we might have a better idea about what changed.

PR #18721 attempts to debug/resolve this issue.

**Comment by timvandermeij** [comment]
I have confirmed in PR #18859 that reverting commit 68332ec23670c020c8aade17d24256b86ccd8a6d indeed fixes the issue. This issue is quite similar to https://github.com/mozilla/pdf.js/issues/18774#issuecomment-2395426167 in that it originates from the same commit and it only happens on a specific browser/OS combination (sadly in this case that makes it hard to debug because it only occurs on the Windows bot here).

**Comment by calixteman** [comment]
I tried to reproduce it yesterday on Windows and I didn't manage to.
That said, maybe I've an idea to fix it (but I still don't know why it happens).
