### ISSUE TITLE
[Bug]: Incorrect rendering of texts in a PDF 

### ISSUE THREAD

**Issue by mathumal07** [mozilla/pdf.js#18778]
### Attach (recommended) or Link to PDF file

Will be uploading in comments

### Web browser and its version

Mozilla Firefox : any version

### Operating system and its version

Any OS

### PDF.js version

Latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the sample file provided in pdf.js viewer, we can see the text replaced with some other characters.

### What is the expected behavior?

PDF text fields should be displayed with correct text
![image](https://github.com/user-attachments/assets/209b17b7-bf8f-4a94-88e6-f02a97b3db49)

### What went wrong?

Texts in PDF is replaced with some different characters.
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/f6f15fb6-787e-4be4-80cd-116a3c2986db">

**Comment by lbadri** [comment]
[Personal Financial Statement (1).pdf](https://github.com/user-attachments/files/17098080/Personal.Financial.Statement.1.pdf)
[i-129.pdf](https://github.com/user-attachments/files/17098081/i-129.pdf)

**Comment by lbadri** [comment]
Problem pdf forms uploaded.

**Comment by calixteman** [comment]
The pdf doesn't correspond to what we've on the screenshot: I mean there is no `SECTION 1: APPLICANT INFORMATION`.

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> Will be uploading in comments

Sorry, but that's not appropriate. Please wait until you have the document *before* opening an issue.

> ### PDF.js version
> 
> Latest

That's not a version *number*, please fill out the template properly.

---

> [Personal Financial Statement (1).pdf](https://github.com/user-attachments/files/17098080/Personal.Financial.Statement.1.pdf)
> [i-129.pdf](https://github.com/user-attachments/files/17098081/i-129.pdf)

Please do *not* report multiple different problems in the same issue.

---

Finally, the screen-shots don't actually match any of the PDF documents provided above.

Please take more care to report actionable/valid issues, by providing consistent and correct information.
