### ISSUE TITLE
[Bug]: "Warning: Invalid absolute docBaseUrl" when using blob: URLs

### ISSUE THREAD

**Issue by robmv** [mozilla/pdf.js#18780]
### Attach (recommended) or Link to PDF file

Not specific to a single PDF file. 

### Web browser and its version

Firefox

### Operating system and its version

Linux (Fedora 40)

### PDF.js version

v4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open a PDF stored on a Blob, example bellow using a file control as the source of the Blob.
2. Press the 'Open in Tab' button

```html
<html>
<head>
  <script>
function pdfSelected(elem) {
  document.getElementById("button").disabled = false;
}

function openPdf() {
  const input = document.getElementById("input");
  const url = URL.createObjectURL(input.files[0]);
  window.open(url, '_blank');
  URL.revokeObjectURL(url);
}
  </script>
</head>
<body>
  <input id="input" type="file" onchange="pdfSelected()">
  <br>
  <button id="button" type="button" disabled onclick="openPdf()">
    Open in Tab
  </button>
</body>
```

### What is the expected behavior?

The PDF opens in a new tab with no waning.

### What went wrong?

On the tab where the PDF is being shown, PDF.js prints on the console:

    Warning: Invalid absolute docBaseUrl: "blob:null/....".

PDF.js should take into account blob URLs

**Comment by Snuffleupagus** [comment]
That warning is associated with the following API option, and since a Blob-URL cannot be meaningfully used to create a *fallback* absolute URL for incorrectly specified LinkAnnotations (among other things) the warning seems appropriate.
https://github.com/mozilla/pdf.js/blob/b65b7747b6a2e1d150e2bccb89d77d165e298273/src/display/api.js#L140-L142

**Comment by robmv** [comment]
Maybe the warning should be displayed on these cases instead of any file loaded from a Blob.
