### ISSUE TITLE
[Bug]: commonObjs empty on NodeJs

### ISSUE THREAD

**Issue by sschoeb** [mozilla/pdf.js#18797]
### Attach (recommended) or Link to PDF file

You can use any PDF object you have. We are not able to fill it.

### Web browser and its version

Node 20.12.1

### Operating system and its version

Windows 11

### PDF.js version

Latest (4.6.82)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Given the following example code:
```
const pdfJsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');
const document = pdfJsLib.getDocument({data: inputBuffer});
 for (let pageIndex = 1; pageIndex <= document.numPages; pageIndex++) {
            const page = await document.getPage(pageIndex);
            await page.getOperatorList();

            // commonObjs is always an empty object
            console.log(page.commonObjs);
}
```
For some reason, in the latest version of PdfJs, commonObjs is always an empty object. 

I do have an old version of pdfjs (where I unfortunately do not know the exact version, any hint how I could figure that out?), which does work perfectly well. I've uploaded the old version as zip here: https://we.tl/t-9MyjlHlfXe

So if I do load the old version like this:
```
const pdfjsLib = require('./externallibs/pdfjs/pdf.js');
```
And then execute the code above, it works perfectly fine.

So my questions would be:

1. Does the newest version still support NodeJs?
2. How can I figure out the version of a lib
3. Is there anything I have to do differently in the latest versions to load the commonObjs object?
4. Is there any possibility to get som additional logs how I could maybe figure out a problem?

### What is the expected behavior?

It should return a filled commonObj after calling getOperatorList

### What went wrong?

The commonObj object is an empty object

**Comment by Snuffleupagus** [comment]
> For some reason, in the latest version of PdfJs, commonObjs is always an empty object.

Note that we have multiple unit-tests, that run in Node.js (via GitHub Actions), which access that field successfully; please see one such example here: https://github.com/mozilla/pdf.js/blob/9735a840ad9e8b6f87d24279504400f6da13acfe/test/unit/api_spec.js#L3349-L3352

> 1. Does the newest version still support NodeJs?

Yes, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> 2. How can I figure out the version of a lib

Unless you're using a minified version of the code, searching for `pdfjsVersion` in e.g. the `pdf.mjs` file should allow you to find the version number.

> 3. Is there anything I have to do differently in the latest versions to load the commonObjs object?

It should be available, so without additional information it's unfortunately somewhat difficult to help.

> 4. Is there any possibility to get som additional logs how I could maybe figure out a problem?

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sschoeb** [comment]
Thank you very much @Snuffleupagus for your response. 

As the old version is minified, I guess that is going to be a hard task then. But anyway, as I don't want to use the old version it doesn't matter too much. I was just wondering if there was something in the upgrade path, that I've missed.

I've uploaded here a runnable example that demonstrates the problem in the smallest possible way:
https://github.com/sschoeb/pdfjs-commonobj-node

There is also an example PDF-included in the repo. About the code in there:

```
async function parsePdf(): Promise<void> {
    const data = fs.readFileSync('./dummy.pdf');
    const pdfJsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');
    const document = await pdfJsLib.getDocument({
        data: data.buffer, verbosity: 0
    }).promise;

    for (let pageIndex = 1; pageIndex <= document.numPages; pageIndex++) {
        const page = await document.getPage(pageIndex);
        await page.getOperatorList();

        console.log('Loaded commonObjs')
        console.log(page.commonObjs);
    }
}
```

We load the pdf using the legacy build of pdfjs. Getting the document, the pages works perfectly fine. But after calling the "getOperatorList()"-method on the page, somehow the commonObjs is not populated. 

Maybe about the task we want to archive:
We need a list of fonts with all the properties from the document. And we think this commonObj-thing is the way to go for this. Please let me know if we are wrong about this.

I hope I could provide all the information needed, otherwise I'm happy to work further on this. Thanks for your help.

**Comment by sschoeb** [comment]
Thank you very much @Snuffleupagus. That solved the problem.

For anyone migrating from an old world to the new one:
In old versions the "private" field was not "private" but just named "_objs". Therefore it was possible to access these values to get all the fonts (which was a hack, I agree :-)). In the newer version, pdfJs uses real private fields, making the "objs" field invisible to the outside. 

Thanks again.
