### ISSUE TITLE
Print button does'nt work when a pdf file is rendered in <object>,<embed> or <iframe>

### ISSUE THREAD

**Issue by trott13** [mozilla/pdf.js#18809]
Same for me using ExtJS. When the PDF is rendered in <iframe , <object , <embed  the Error occurs and the PDF isn't printable. Having trouble with this issue "for ages" - essentially switching to Chrome as a work around.
Just verified again on Firefox 130/MacOS

_Originally posted by @trott13 in https://github.com/mozilla/pdf.js/issues/17390#issuecomment-2379068722_

**Comment by nicolo-ribaudo** [comment]
Please re-open the issue following the template at https://github.com/mozilla/pdf.js/issues/new?assignees=&labels=&projects=&template=bug.yml&title=%5BBug%5D%3A+
