### ISSUE TITLE
[Bug]: 在使用TextLayerBuilder时导致的bug报错

### ISSUE THREAD

**Issue by Shi-haoD** [mozilla/pdf.js#18808]
### Attach (recommended) or Link to PDF file

任何pdf文件

### Web browser and its version

chrome

### Operating system and its version

win10

### PDF.js version

2.6.347

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

在使用TextLayerBuilder的render时候，显示的是eventbus事件总线没有这两个方法导致页面报错，试了很多个版本

### What is the expected behavior?

引入
import {
	TextLayerBuilder,
} from 'pdfjs-dist/web/pdf_viewer';
import * as pdfjsLib from 'pdfjs-dist/build/pdf'; //pdfjs
pdfjsLib.GlobalWorkerOptions.workerSrc = `/js/pdf.worker.js`;
执行方法：
}			
this.pdfurl = data.data.ulr;
			this.fileName = data.data.filename;
			document.title = data.data.filename;
			console.log(data.data);
			const loadingTask = getDocument(data.data.ulr);
			const pdf = await loadingTask.promise;
			const viewer = this.$refs.pdfViewer;
			viewer.innerHTML = ''; // 清空现有内容

			// 渲染所有页面
			for (let i = 1; i <= pdf.numPages; i++) {
				const page = await pdf.getPage(i);
				const viewport = page.getViewport({ scale: 1 });

				const canvas = document.createElement('canvas');
				const context = canvas.getContext('2d');
				canvas.height = viewport.height;
				this.allHeight = viewport.height * pdf.numPages;
				canvas.width = viewport.width;

				// // 渲染 PDF 页面到 Canvas
				await page.render({
					canvasContext: context,
					viewport: viewport,
				});

				// 创建文本层
				const textLayerDiv = document.createElement('div');
				textLayerDiv.className = 'textLayer';
				viewer.appendChild(textLayerDiv);
				viewer.appendChild(canvas);
				//提取文本并创建文本层
				const textContent = await page.getTextContent();
				const textLayer = new TextLayerBuilder({
					textLayerDiv: textLayerDiv,
					pageIndex: i - 1,
					viewport: viewport,
				});
				textLayer.setTextContent(textContent);
				textLayer.render();
			}

### What went wrong?

![1727431206105](https://github.com/user-attachments/assets/67936ffe-7637-4897-9704-c79974bbe622)

**Comment by Snuffleupagus** [comment]
Please use English in this bug tracker, otherwise no help can/will be provided.

> ### PDF.js version
> 
> 2.6.347

That version is no longer supported, since it's over four years old, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
