### ISSUE TITLE
[Bug]: Glitchy text when opening pdf

### ISSUE THREAD

**Issue by cdkw2** [mozilla/pdf.js#18806]
### Attach (recommended) or Link to PDF file

[0007_overview.pdf](https://github.com/user-attachments/files/17166253/0007_overview.pdf) (PDF link: https://projecteuler.net/overview=0007)

### Web browser and its version

Firefox 130.0.1 (64-bit)

### Operating system and its version

archlinux

### PDF.js version

firefox inbuilt

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open PDF

### What is the expected behavior?

Non glitchy text

### What went wrong?

Glitchy text

![image](https://github.com/user-attachments/assets/a43e63d4-831c-41fb-ab20-cc2590f81c63)

**Comment by Snuffleupagus** [comment]
> PDF link:
> https://projecteuler.net/overview=0007

Unfortunately that doesn't seem to point to an actual PDF file for me, with both Firefox and Chrome instead landing on https://projecteuler.net/about (which is an HTML file).

**Comment by cdkw2** [comment]
> > PDF link:
> > https://projecteuler.net/overview=0007
> 
> Unfortunately that doesn't seem to point to an actual PDF file for me, with both Firefox and Chrome instead landing on https://projecteuler.net/about (which is an HTML file).

oh maybe its because you have not solved the problem, I'll just post the pdf here

**Comment by cdkw2** [comment]
[0007_overview.pdf](https://github.com/user-attachments/files/17166092/0007_overview.pdf)

**Comment by calixteman** [comment]
No problem for me too on windows.
Basically, your issue is because the Aria font isn't embedded in the pdf and so we're using a substitute font on your system.

@cdkw2 could you follow the steps described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1854090#c23 ?
For me, the font used for the title is called `g_d0_sf4` (in the pdf debugger in right sidebar) and the real font used is Aria Bold (from the devtools panel called `Fonts`).
That said you've likely a weird substitution for Aria. In a terminal, could you run the command `fc-list "Aria"` and provide the output ?

**Comment by cdkw2** [comment]
> No problem for me too on windows. Basically, your issue is because the Aria font isn't embedded in the pdf and so we're using a substitute font on your system.
> 
> @cdkw2 could you follow the steps described here: https://bugzilla.mozilla.org/show_bug.cgi?id=1854090#c23 ? For me, the font used for the title is called `g_d0_sf4` (in the pdf debugger in right sidebar) and the real font used is Aria Bold (from the devtools panel called `Fonts`). That said you've likely a weird substitution for Aria. In a terminal, could you run the command `fc-list "Aria"` and provide the output ?

well fc-list "aria" yeilded no result but fc-list shows this:

[fonts.txt](https://github.com/user-attachments/files/17167748/fonts.txt)


also heres a ss from those steps:

![image](https://github.com/user-attachments/assets/3f8f102b-56a0-4273-a021-081a3723ee3d)

**Comment by calixteman** [comment]
Could you please show the same only for `Find the...`  in the title ?
![image](https://github.com/user-attachments/assets/cc032b1c-16c3-48f1-be1e-5e1292d163b4)
Take care to select the correct span on the DOM view.

**Comment by cdkw2** [comment]
> Could you please show the same only for `Find the...` in the title ? ![image](https://private-user-images.githubusercontent.com/5641725/371630794-cc032b1c-16c3-48f1-be1e-5e1292d163b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjI1NDcsIm5iZiI6MTcyNzQ2MjI0NywicGF0aCI6Ii81NjQxNzI1LzM3MTYzMDc5NC1jYzAzMmIxYy0xNmMzLTQ4ZjEtYmUxZS01ZTEyOTJkMTYzYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTgzNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcwMWJjNTkxMjc3NmU5ZmEwNWIxODU5OWZiMmNjNzVlYjNlZWFlOWM0ZWE4ZmI2NjY4YmJjYmEwYjkxNmMyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zG_UTVE7EZ2vNA_xvCTxebFxFli3EVN2gzRmzYYwROs) Take care to select the correct span on the DOM view.

sure thing:

![image](https://github.com/user-attachments/assets/52e67c21-4e21-460f-bd59-4b4b1fbaf15c)
 Sorry for the delay

**Comment by cdkw2** [comment]
> Could you please show the same only for `Find the...` in the title ? ![image](https://private-user-images.githubusercontent.com/5641725/371630794-cc032b1c-16c3-48f1-be1e-5e1292d163b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjI1NDcsIm5iZiI6MTcyNzQ2MjI0NywicGF0aCI6Ii81NjQxNzI1LzM3MTYzMDc5NC1jYzAzMmIxYy0xNmMzLTQ4ZjEtYmUxZS01ZTEyOTJkMTYzYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTgzNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTcwMWJjNTkxMjc3NmU5ZmEwNWIxODU5OWZiMmNjNzVlYjNlZWFlOWM0ZWE4ZmI2NjY4YmJjYmEwYjkxNmMyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zG_UTVE7EZ2vNA_xvCTxebFxFli3EVN2gzRmzYYwROs) Take care to select the correct span on the DOM view.

sure thing:

![image](https://github.com/user-attachments/assets/52e67c21-4e21-460f-bd59-4b4b1fbaf15c)
 Sorry for the delay

**Comment by calixteman** [comment]
What are the output of `fc-list "Arial"` (I made a typo it was Arial and not Aria) and the output of `fc-list "Helvetica"` ?
Normally, these two fonts have the same metrics, but it seems that the Helvetica (or its substitution) you've has different ones.
Installing a better font (like Liberation Sans) and set it as a substitution for Arial and Helvetica could help (see https://wiki.archlinux.org/title/Metric-compatible_fonts#List_of_metric-compatible_fonts).

**Comment by cdkw2** [comment]
> What are the output of `fc-list "Arial"` (I made a typo it was Arial and not Aria) and the output of `fc-list "Helvetica"` ? Normally, these two fonts have the same metrics, but it seems that the Helvetica (or its substitution) you've has different ones. Installing a better font (like Liberation Sans) and set it as a substitution for Arial and Helvetica could help (see https://wiki.archlinux.org/title/Metric-compatible_fonts#List_of_metric-compatible_fonts).

[cdkw2@cdkw2 ~]$ fc-list "Arial"
[cdkw2@cdkw2 ~]$ fc-list "Helvetica"
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox3hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox1hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox4hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox5hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox3hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox4hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox2hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox1hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox6hb.otb: Helvetica:style=Bold
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox2hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox3ho.otb: Helvetica:style=Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox2ho.otb: Helvetica:style=Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox1ho.otb: Helvetica:style=Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox3h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox1h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox2h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox5h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox6h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox4h.otb: Helvetica:style=Regular
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox5hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox6ho.otb: Helvetica:style=Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox5ho.otb: Helvetica:style=Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox6hbo.otb: Helvetica:style=Bold Oblique
/home/cdkw2/.fonts/bitmap/cronyx-cyrillic/crox4ho.otb: Helvetica:style=Oblique
[cdkw2@cdkw2 ~]$

**Comment by cdkw2** [comment]
And as for installing ttf-liberation I already have it installed

**Comment by calixteman** [comment]
So the font used for Helvetica is crox which isn't metrics compatible with Helvetica.
We cannot do anything on the pdf.js side: in the first place, the pdf should have embedded its fonts and in a second one you must fix your font configuration (search for something like `fontconfig substitution`).

**Comment by cdkw2** [comment]
ok thanks!
