### ISSUE TITLE
[Feature]: Add "Ask GPT" Feature for PDF Contextual Queries

### ISSUE THREAD

**Issue by 003-kalki** [mozilla/pdf.js#18818]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

-> Context
With the increasing demand for AI-assisted tools in document reading, I propose adding an "Ask GPT" feature to PDF.js. This would allow users to interact with the content of their PDFs in real-time, similar to how VSCode integrates ChatGPT.

->  Feature Proposal
The idea is to integrate an AI chatbot that enables users to ask questions about the content while reading. This feature could provide definitions, explanations, or summaries directly from the document.

->  Use Cases
- Users could inquire about specific terms or concepts found within the PDF.
- The AI could summarize sections or provide contextual information based on user queries.

->  Steps to Implement
1. Integration with OpenAI API : Utilize the OpenAI API to handle user queries and return relevant information.
2.  User Interface : Implement a chat window within the PDF.js viewer for users to type their questions.

->  Benefits
- Enhances accessibility for users struggling with complex documents.
- Promotes interactive engagement with content, leading to better understanding and retention.

->  Additional Information
There are existing tools that offer similar functionalities; integrating such a feature could significantly enhance user experience with PDF.js.

### Other PDF viewers

No.

**Comment by Snuffleupagus** [comment]
There's absolutely no way that we'll implement a feature that sends potentially sensitive user information to an unknown/untrusted third-party service!

**Comment by soham203** [comment]
we can use llama 3.2 which is open source AI model

**Comment by marco-c** [comment]
Building ML-based features in PDF.js is not completely out of the question. Indeed, we've already been doing it with automatically generating alt text for added images. We are planning to build more, whenever possible it will be with local models we are training openly like we are doing for alt text and for translations.

> Users could inquire about specific terms or concepts found within the PDF.

Selecting text, right clicking and "search" should already mostly cover this.

> The AI could summarize sections or provide contextual information based on user queries.

We could potentially support summarization with local models.
