### ISSUE TITLE
[Feature]: Optional Content Radio Button Groups

### ISSUE THREAD

**Issue by agrahn** [mozilla/pdf.js#18823]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

The PDF spec defines the **`/RBGroups`** entry in the optional content configuration dictionary. It allows OCGs to be to added to groups of OCGs that follow the radio-button paradigm:  From all OCGs within a Radio Button Group only one can be enabled at a time. Enabling an OCG, e. g. in the Layers tab of the PDF viewer, automatically hides the previously visible OCG in that group. An OCG can be a member of multiple Radio Button Groups. The attached example PDF has two radio button groups, where one OCG, "3", belongs to both radio-button groups. If that one is enabled, any currently visible OCG belonging to the rb groups is hidden. There is also one OCG, "7", which is unrelated to the rb groups.

### Other PDF viewers

The attached PDF opened in **KDE Okular** which correctly implements OC radio button groups:

[radioBtnGrp.pdf](https://github.com/user-attachments/files/17193421/radioBtnGrp.pdf)

![rbgrpsEx](https://github.com/user-attachments/assets/2736df34-4f44-4995-a7f9-9de153a14f16)

**Comment by calixteman** [comment]
@agrahn I think you've a patch ready for this feature, if it's correct, would you mind to make a PR please ?
It'd nice to have an integration test if it's possible.

**Comment by agrahn** [comment]
> @agrahn It'd nice to have an integration test if it's possible.

I am trying to figure out how to do an integration test. I followed the instructions on [testing](https://github.com/mozilla/pdf.js/wiki/Contributing) applied on the `master` branch first, just to get familiar with the procedure, but already `npx gulp makeref` in the master branch ends with errors. What do I have to do?

**Comment by calixteman** [comment]
You can create a file `optional_content_spec.mjs` similar to https://github.com/mozilla/pdf.js/blob/master/test/integration/annotation_spec.mjs, with a test testing doing something like:
 - click on the sidebar button
 - click on the layers button
 - click on the buttons in the pdf
 - check that the radio buttons in the sidebar have the correct state.
something like that...
