### ISSUE TITLE
Selected text which appears to be normal has spaces occasionally missing.

### ISSUE THREAD

**Issue by dwhly** [mozilla/pdf.js#1883]
Using the following PDF as reference....

http://www.nature.com/nature/journal/v486/n7402/pdf/nature11234.pdf

Selecting the abstract text and doing a copy paste into a text editor results in a string with spaces occasionally missing on whole lines...  for example:

"Studies of the human microbiome have revealed that even healthy individuals differ remarkably in the microbes that
occupy habitats such as the gut, skin and vagina. Much of this diversity remains unexplained, although diet,
environment, host genetics and early microbial exposure have all been implicated. Accordingly, to characterize the
ecology of human-associated microbial communities, the Human Microbiome Project has analysed the largest cohort
and set of distinct, clinically relevant body habitats so far. We found the diversity and abundance of each habitat’s
signaturemicrobestovarywidelyevenamonghealthysubjects,withstrongnichespecializationbothwithinandamong
individuals. The project encountered an estimated 81–99% of the genera, enzyme families and community
configurations occupied by the healthy Western microbiome. Metagenomic carriage of metabolic pathways was
stable among individuals despite variation in community structure, and ethnic/racial background proved to be one of
the strongest associations of both pathways and microbes with clinical metadata. These results thus delineate the range
ofstructuralandfunctionalconfigurationsnormalinthemicrobialcommunitiesofahealthypopulation,enablingfuture
characterization of the epidemiology, ecology and translational applications of the human microbiome

**Comment by speedplane** [comment]
PR #5783 should fix this.

**Comment by timvandermeij** [comment]
Fixed after recent text selection patches.
