### ISSUE TITLE
[Bug]: Deleting and restoring an edited Stamp-annotation is broken

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#18849]
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-stamp.pdf

### Web browser and its version

N/A

### Operating system and its version

N/A

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load https://mozilla.github.io/pdf.js/web/viewer.html
2. Open the `annotation-stamp.pdf` file.
3. Double-click on the "APPROVED"-image to enable Stamp-editing.
4. Delete the editor, either with <kbd>Del</kbd> or the editing-toolbar button.
5. Restore the editor, with <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

### What is the expected behavior?

That the editor is restored.

### What went wrong?

The editor is *not* restored, and the following is printed in the console:
```
TypeError: can't access property "type", image is undefined
    #get tools.js:138
    getFromUrl tools.js:183
    getFromId tools.js:200
    #getBitmap stamp.js:226
    rebuild stamp.js:334
    addOrRebuild annotation_editor_layer.js:585
    #addEditorToLayer tools.js:1873
    undo tools.js:2057
    undo tools.js:354
    undo tools.js:1993
    exec tools.js:478
    keydown tools.js:1444
    #addKeyboardManager tools.js:1263
    AnnotationEditorUIManager tools.js:817
    setDocument pdf_viewer.js:893
    promise callback*setDocument pdf_viewer.js:866
    load app.js:1264
    open app.js:1070
    promise callback*open app.js:1068
    onFileInputChange app.js:2250
    dispatch event_utils.js:115
    run app.js:730
    run app.js:724
    webViewerLoad viewer.js:255
    <anonymous> viewer.js:266
tools.js:167:14
```

**Comment by calixteman** [comment]
When the annotation is deleted then the bitmap is removed:
https://github.com/mozilla/pdf.js/blob/e5b6144bfa1a61a1dfe79c67e74e5eb08930fdab/src/display/editor/tools.js#L242-L243
but we've no way to recreate the image when undoing the deletion (i.e. no file, no url, ...).
So we must keep some data in order to be able to recreate it.
