### ISSUE TITLE
[Feature]: Please make it possible to access the raw image data (e.g. JPEG)

### ISSUE THREAD

**Issue by mitya57** [mozilla/pdf.js#18840]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

In our project we need some interactivity for images in PDF: in place of some images, we need to display a button (pressing this button reveals the image), and in place of other images we need to display inputs. This behavior is controlled by images metadata (EXIF).

Currently we are using pdf.js v2.4, but in a newer version this is no longer possible: since `case "JpegStream"` block was removed in 0351852d746b2b7bf1b555989978fad8d2432edf, there is no longer `new Image` object (aka `<img>` element), the only thing we have access to is an object with already decoded image pixels. Because of this, we cannot access EXIF metadata.

It would help us a lot if there was an option to access the original JPEG bytes somehow. Either by adding our callback somewhere which is called with these bytes as an argument, or by having it in the `getPage(num)` output.

### Other PDF viewers

pdfimages(1) from Poppler allows you to get the list of original images. However there is no way to use that from JS code.

**Comment by Snuffleupagus** [comment]
Sorry, but (large) features that are completely unused within the PDF.js project itself are generally difficult for us to add.

Please keep in mind that every piece of functionality not only has to be implemented, but will increase complexity of the code-base, and finally needs to be tested, maintained, and supported for (potentially) many years.
