### ISSUE TITLE
[Bug]: icons are not being displayed

### ISSUE THREAD

**Issue by ToratEmetInWord** [mozilla/pdf.js#18861]
### Attach (recommended) or Link to PDF file

i have downloaded the latest release and opened the viewer.html however the icons are not being displayed;
![image](https://github.com/user-attachments/assets/128c9812-5272-4c16-8d5e-f05a2ce2070a)

### Web browser and its version

all browsers

### Operating system and its version

windows 10

### PDF.js version

latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. download latest release
2. open the viewer.html

### What is the expected behavior?

the icons should be visible

### What went wrong?

the icons are not visible

**Comment by calixteman** [comment]
@Snuffleupagus would it be possible to display a message in the console or in a span in the viewer to explain what's wrong ?

**Comment by Snuffleupagus** [comment]
> would it be possible to display a message in the console or in a span in the viewer to explain what's wrong ?

I don't think so, since the problem isn't so much the images but rather that JavaScript is being blocked (by CORS) when a `file://`-URL is used to load the viewer.
