### ISSUE TITLE
[Bug]: Poor font rendering, disappearing strokes in certain characters

### ISSUE THREAD

**Issue by kittybwained** [mozilla/pdf.js#18886]
### Attach (recommended) or Link to PDF file

[HPO6TEST.pdf](https://github.com/user-attachments/files/17345694/HPO6TEST.pdf)

### Web browser and its version

Firefox 131.0.2

### Operating system and its version

Windows 10 Enterprise N LTSC 21H2

### PDF.js version

4.6.60 [10a846417]

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open linked PDF
2. Observe the capital T and D

### What is the expected behavior?

I expected the top of the capital letters T and D to be rendered properly, like they are in Chromium.
For reference, here is a screenshot of the PDF in Chromium, rendered at 160% zoom:
![chrome_PFxPEVT5S0](https://github.com/user-attachments/assets/d54086c2-47ad-4b8c-90fc-fd2d0ebe9968)

### What went wrong?

The capital letters T and D are rendered very poorly, the top of the letters are disappearing.
A screenshot of the PDF in Firefox, also at 160% zoom:
![firefox_5WU2eDVzSn](https://github.com/user-attachments/assets/a983c7d7-11d7-47f9-ac42-993d63d27bf8)
There's also what looks like a gap in the top of the 8 and the 0. The bottom of the D gets a bit too thin too.

### Additional context

The font in the PDF in question is Palatino, specifically the URW Base 35 P052 version, in Type 1 format. The PDF was created by Ghostscript 10.0.0, on Debian 12, from a PostScript file (ps2pdf). Said PostScript file was generated by SCRIPT/VS 4.0.0, running on VM/ESA 2.4, using metrics for Palatino made by Adobe. GhostScript uses a translation rule to replace Palatino-Roman with P052-Roman, but AFAIK they're metrically compatible, so it should be okay.

I've noticed similar issues with other fonts, but none this egregious, usually just the top of a lowercase S or an 8 having a slight gap, or fonts just looking too thin in general. Fonts in PDFs rendered by Chromium always look much nicer, the fonts look more bold, and don't have these weird disappearing strokes. The boldness is probably just personal preference, but the disappearing strokes in Firefox/PDF.js are clearly an error.

I've tried messing with some gfx.font_rendering.cleartype_params preferences, namely the enhanced contrast, the pixel structure, and the rendering mode. Unfortunately, I couldn't find any configuration that fixed this issue.

I wasn't sure how to answer the question "Is the bug present in the latest PDF.js version?" (referring to the online demo), as the PDF uses different fonts, where the specific issue with the T and D don't crop up. In the interest of this issue not getting auto-closed with "already fixed", I've answered yes, as it's untested.

In case this is an issue in Firefox's font renderer, as opposed to something in PDF.js, I apologize, I will open an issue there instead if necessary.

**Comment by kittybwained** [comment]
Note: I've just checked and noticed that I accidentally had `gfx.font_rendering.cleartype_params.rendering_mode` still set to 5 in Firefox when I took the screenshots (some random advice online suggested this). Unfortunately, returning it to it's default value of -1 doesn't fix the issue.

**Comment by calixteman** [comment]
I opened the pdf in Acrobat Reader and the rendering is the same as in Firefox and I agree that it looks better in Chrome with pdfium but the rendering is the same as in Firefox with https://mozilla.github.io/pdf.js/web/viewer.html.
@jfkthame, would you know if there's something we can do to improve this ?

**Comment by kittybwained** [comment]
For a test, I installed the PDF.js extension in Chromium, and viewed the PDF with that. It produces the same errors as native Firefox does, which to me suggests that it's an issue in PDF.js as opposed to Firefox's font rendering.

**Comment by jfkthame** [comment]
It sounds to me like the font embedded in the pdf isn't working very well with DirectWrite rasterization; factors that could contribute to that include poor hinting and/or incorrect path directions in the glyphs. Chrome's pdfium rendering may use a different rasterizer (freetype?) that happens to handle this font better.

Unless pdf.js is actually modifying the glyph data or hinting in the font resource in the process of extracting it and packaging it up to load in the browser, I don't think we can blame it for the rendering here.

(One way to check further would be to extract the "original" embedded font resource, install it directly in Windows, and see how it renders in DirectWrite-using Windows applications. If it shows similarly poor results, then pdf.js isn't the problem.)

**Comment by kittybwained** [comment]
I extracted the font using an online tool, and installed it to my system. What programs should I try it with? I tried it in the font installer preview and notepad, it looks fine. It's more thin than how Chromium would render it, but it never has the weird disappearing line on the top of the T for example.

> It sounds to me like the font embedded in the pdf isn't working very well with DirectWrite rasterization; factors that could contribute to that include poor hinting and/or incorrect path directions in the glyphs. Chrome's pdfium rendering may use a different rasterizer (freetype?) that happens to handle this font better.
> 
> Unless pdf.js is actually modifying the glyph data or hinting in the font resource in the process of extracting it and packaging it up to load in the browser, I don't think we can blame it for the rendering here.
> 
> (One way to check further would be to extract the "original" embedded font resource, install it directly in Windows, and see how it renders in DirectWrite-using Windows applications. If it shows similarly poor results, then pdf.js isn't the problem.)

**Comment by calixteman** [comment]
@kittybwained, I extraceted the font and use it in MS Word and here's the result:
![image](https://github.com/user-attachments/assets/43348e8a-a239-4dd3-a432-0813b59a9bad)
You can see that there's the same problem with D and T.

So unfortunately, we won't be able to fix this problem because there is nothing obvious we could workaround.

**Comment by kittybwained** [comment]
> @kittybwained, I extraceted the font and use it in MS Word and here's the result:
> ![image](https://github.com/user-attachments/assets/43348e8a-a239-4dd3-a432-0813b59a9bad)
> You can see that there's the same problem with D and T.
> 
> So unfortunately, we won't be able to fix this problem because there is nothing obvious we could workaround.

I see. It's a shame, but I understand. Thanks for taking the time to review it though!
