### ISSUE TITLE
[Bug]: pdf2png blank page

### ISSUE THREAD

**Issue by kchzhang** [mozilla/pdf.js#18897]
### Attach (recommended) or Link to PDF file

[1.pdf](https://github.com/user-attachments/files/17359921/1.pdf)

### Web browser and its version

Chrome 129

### Operating system and its version

Windows 10

### PDF.js version

4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Transform the given PDF as PNG using https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png
![image](https://github.com/user-attachments/assets/a33b4c58-c7dc-4676-a353-c51d3119c929)

### What is the expected behavior?

png
![image](https://github.com/user-attachments/assets/1f405f8a-2ac2-4100-a4ac-52bec2217334)

### What went wrong?

Transform the given PDF as PNG using https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png
![image](https://github.com/user-attachments/assets/a33b4c58-c7dc-4676-a353-c51d3119c929)

**Comment by Snuffleupagus** [comment]
WFM, when testing against the PDF.js `master` branch (after running `gulp dist-install`) with Node.js v20.16.0 on Windows 11.

![output](https://github.com/user-attachments/assets/9267bea2-d17a-48f4-a43d-fe49f5e8b64e)

---

Given that the PDF document is a very simple one, the explanation may be that you've not installed all the needed dependencies. However that's impossible to tell given the provided information, and you've not even stated what Node.js version you're using!

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
