### ISSUE TITLE
Linux + old version of puppeteer fails to render pdf

### ISSUE THREAD

**Issue by MatanYemini** [mozilla/pdf.js#18901]
Hi! 👋 
      
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `pdfjs-dist@4.4.168` for the project I'm working on.

I had a puppeteer running on one of my old linux machines (running old version of puppeteer) and it failed to work there because of non existing function error.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.mjs b/node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.mjs
index 7906d1a..2b07de5 100644
--- a/node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.mjs
+++ b/node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.mjs
@@ -2132,6 +2132,9 @@ class KeyboardManager {
     for (const [keys, callback, options = {}] of callbacks) {
       for (const key of keys) {
         const isMacKey = key.startsWith("mac+");
+        if (!key.split || !key.slice || typeof key.split !== "function" || typeof key.slice !== "function" || !key.split("+").at || typeof key.split("+").at !== "function") {
+          continue; // See line 4213 -> linux (puppeteer) doesn't have the those keys
+        }
         if (isMac && isMacKey) {
           this.callbacks.set(key.slice(4), {
             callback,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

I don't think it's urgent, but just an FYI.

I can make a PR if you think it's relevant.

**Comment by Snuffleupagus** [comment]
Please note that any browser/environment without support for e.g. `Array.prototype.at()` is no longer supported by the PDF.js project, compare the following:
 - https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

*For future reference:* Please remember to follow https://github.com/mozilla/pdf.js/issues/new/choose when reporting an issue.
