### ISSUE TITLE
[Bug]: Library takes forever to render a document

### ISSUE THREAD

**Issue by ievgennaida** [mozilla/pdf.js#18909]
### Attach (recommended) or Link to PDF file

This document example that instantly works for the iframe and takes almost forewer to load using pdf.js
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ:L_202401624

### Web browser and its version

Chrome

### Operating system and its version

Win

### PDF.js version

v4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Run library just with the given url

### What is the expected behavior?

Fast as iframe

### What went wrong?

Long rendering time, no lazy loading.

**Comment by Snuffleupagus** [comment]
WFM, with all pages rendering "instantly" with PDF.js 4.7.78 [81cf42df4] in Firefox Nightly 133.0a1 on Windows 11.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
