### ISSUE TITLE
[Bug]: PDF.js not working in Microsoft Edge for all our users

### ISSUE THREAD

**Issue by btwillca5** [mozilla/pdf.js#18935]
### Attach (recommended) or Link to PDF file

This morning they try to open PDFs but they are presented with blank screen.  The PDF never loads.  I have attached a screenshot of what it looks like.  The extension appears to load but it never puts in the PDF.    If you go to PDF.JS Extension Options it is also blank, except for Restore Defaults

The Chrome version works fine, it is just with Microsoft Edge.  

![2024-10-21_09-47-06-PDFjsExtensionOpts](https://github.com/user-attachments/assets/6fe4fcf4-f45b-42b9-9e11-038cafa657ee)
![2024-10-21_09-41-51-Edge](https://github.com/user-attachments/assets/0158d3b0-3d1d-4574-a9dd-3a91f30dadd6)

### Web browser and its version

Edge 130.0.2849.46

### Operating system and its version

Windows 11 and Windows 10

### PDF.js version

4.6.129

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

Yes

### Steps to reproduce the problem

Open PDF with viewer and it does not show anything 

### What is the expected behavior?

PDF will display and extensions options will display

### What went wrong?

PDF fails to display as well as extension options do not display

**Comment by Snuffleupagus** [comment]
> The Chrome version works fine, it is just with Microsoft Edge.

Is that not a bug in Microsoft Edge then?

*For future reference:* Please don't place "unrelated" information under the `Attach (recommended) or Link to PDF file` heading, since that context belongs further down in the issue template instead.

**Comment by GitHubRulesOK** [comment]
Just a comment the current Edge is 
About Microsoft Edge Version 130.0.2849.**56** 
and the extension is working perfectly for me in this latest Edge
![image](https://github.com/user-attachments/assets/c23fdbd9-addf-4878-8530-f794d0cc90a4)

**Comment by Snuffleupagus** [comment]
Given https://github.com/mozilla/pdf.js/issues/18935#issuecomment-2443975898 it's apparently not broken everywhere, and considering the current state of this issue it most unfortunately doesn't clearly point to a bug *here*.
