### ISSUE TITLE
[Bug]: Vulnerability: inflight@1.0.6 - Missing Release of Resource after Effective Lifetime (Introduced by pdfjs-dist dependencies)

### ISSUE THREAD

**Issue by BrunoElias98** [mozilla/pdf.js#18938]
### Attach (recommended) or Link to PDF file

Hello,

I am currently using pdfjs-dist@4.7.76 in my project, and during a security scan using Snyk, I encountered a medium severity vulnerability related to the inflight@1.0.6 package. This vulnerability is categorized as "Missing Release of Resource after Effective Lifetime" and appears to be introduced via a chain of dependencies in pdfjs-dist.

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/7ddcf117-d54d-406d-aaa8-c288edb7afcd">

### Web browser and its version

chrome

### Operating system and its version

MACOS Ventura (13.6.6)

### PDF.js version

4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Perform a Snyk security scan on a project using pdfjs-dist@4.7.76.
The scan results identify a vulnerability related to inflight@1.0.6, categorized as "Missing Release of Resource after Effective Lifetime".
This vulnerability is introduced via the dependency chain: pdfjs-dist@4.7.76 > canvas@2.11.2 > @mapbox/node-pre-gyp@1.0.11 > rimraf@3.0.2 > glob@7.2.3 > inflight@1.0.6.

### What is the expected behavior?

The project should not have vulnerabilities related to resource management in any of its dependencies. Ideally, the pdfjs-dist package would update or remove dependencies introducing these types of vulnerabilities, such as inflight@1.0.6.

### What went wrong?

The Snyk scan reports a medium severity vulnerability caused by the outdated inflight@1.0.6 package. As there is no direct upgrade or patch available for inflight, it is necessary to update the dependency chain in pdfjs-dist to use a more secure version or replace the vulnerable package.

### Additional context

I am requesting that the maintainers of pdfjs-dist update the dependency chain to remove or update inflight@1.0.6, which currently has a known vulnerability with no patch or upgrade available. This issue can potentially affect applications using pdfjs-dist by not properly releasing resources after their effective lifetime.

**Comment by Snuffleupagus** [comment]
Effectively a duplicate of #18934.

---

> ### Attach (recommended) or Link to PDF file
> 
> Hello,
> 
> I am currently using pdfjs-dist@4.7.76 in my project, and during a security scan using Snyk, I encountered a medium severity vulnerability related to the inflight@1.0.6 package. This vulnerability is categorized as "Missing Release of Resource after Effective Lifetime" and appears to be introduced via a chain of dependencies in pdfjs-dist.
> <img alt="image" width="1093" src="https://private-user-images.githubusercontent.com/42720352/378564264-7ddcf117-d54d-406d-aaa8-c288edb7afcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODExNTAsIm5iZiI6MTcyOTU4MDg1MCwicGF0aCI6Ii80MjcyMDM1Mi8zNzg1NjQyNjQtN2RkY2YxMTctZDU0ZC00MDZkLWFhYTgtYzI4OGVkYjdhZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZmE3MGUyOTU3OGI5NzEzOTU1MWY1MjllNTY1MjZkNmVkNzUxOTUxNWFmNTRkNTczMGE0ZmUyMzNjMDFkYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FZZaTVxTsB4UaSehbXE62Tvy4_46c-GPgsb_Kdjs7B0">

*For future reference:* None of that makes sense under a heading called `Attach (recommended) or Link to PDF file`, and should have been placed elsewhere, please take care to fill out the issue template correctly.
