### ISSUE TITLE
[Bug]: rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported, npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported. gauge@3.0.2: This package is no longer supported.

### ISSUE THREAD

**Issue by omoghaoghenemano** [mozilla/pdf.js#18934]
### Attach (recommended) or Link to PDF file

rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
├─┬ pdfjs-dist@4.7.76
│ └─┬ canvas@2.11.2
│   └─┬ @mapbox/node-pre-gyp@1.0.11
│     └── rimraf@3.0.2

### Web browser and its version

Chrome, Edge

### Operating system and its version

Windows

### PDF.js version

pdfjs-dist@4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

Yes

### Steps to reproduce the problem

npm install

### What is the expected behavior?

I would appreciate it if this library could be updated.

### What went wrong?

-

**Comment by Snuffleupagus** [comment]
> rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported

We have no such *direct* dependency, as can be seen in https://github.com/mozilla/pdf.js/blob/master/package.json

> canvas@2.11.2

That dependency has already been updated (will be included in the upcoming release), see https://github.com/mozilla/pdf.js/blob/d37e4b08e4006b382b14b1596c5f70df7e93fbd9/package.json#L16
