### ISSUE TITLE
[Feature]: OCR Support for Non-Selectable Text in PDF Documents

### ISSUE THREAD

**Issue by rossanodr** [mozilla/pdf.js#18949]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

I couldn't find a current implementation or any updates on OCR (Optical Character Recognition) support for documents with non-selectable text in pdf.js. I came across some old issues discussing the topic, but there hasn't been a clear follow-up.

Could you provide an update on whether there are plans to include OCR support for scanned documents or image-based PDFs in pdf.js? This feature would be highly valuable for making non-selectable text searchable and accessible.

Thank you!

**Comment by Snuffleupagus** [comment]
Duplicate of #15843
