### ISSUE TITLE
[Feature]: Add more printing option

### ISSUE THREAD

**Issue by Tarek-Hasan** [mozilla/pdf.js#18950]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

Currently, pages per sheet supports 1, 2, 4, 6, 9 and 16. You're out of luck if you want to make 8 or 10 pages per sheet, etc. Add option to custom page per sheet that will solve the problem

Also, it lacks an option to change page orientation from portrait to landscape.

### Other PDF viewers

[pdfmake](https://github.com/bpampuch/pdfmake) library supports changing page orientation.

**Comment by Snuffleupagus** [comment]
This sort of fine-grained control over printing output isn't really possible from JavaScript.

> [pdfmake](https://github.com/bpampuch/pdfmake) library supports changing page orientation.

It's somewhat difficult to understand how a PDF *creation* library is relevant to this issue.
