### ISSUE TITLE
[Bug]: Rendering Bug

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#18956]
### Attach (recommended) or Link to PDF file

[PDF_-_correct.pdf](https://github.com/user-attachments/files/17522721/PDF_-_correct.pdf)

### Web browser and its version

Firefox 131.03

### Operating system and its version

WIndows 11

### PDF.js version

4.7.76 actually used https://mozilla.github.io/pdf.js/web/viewer.html today

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the PDF, on all the panels the white text should display directly on the background texture but there is some colored area between the text and the background texture. 

The most obvious areas are highlighted 

FYI the same PDF renders correctly using the native Chrome PDF viewer.

### What is the expected behavior?

Should render correctly

### What went wrong?

Not rendered correctly

**Comment by calixteman** [comment]
Here's a simplified test case:
[issue18956.pdf](https://github.com/user-attachments/files/17523239/issue18956.pdf)
