### ISSUE TITLE
Update the list of "required" GitHub Actions workflows

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#18996]
- For the `CI / Test (18)` workflow, *remove* the "required" label to unblock PR [18959](https://github.com/mozilla/pdf.js/pull/18959).
 
 - For the `Lint / Lint` workflow, *add* the "required" label.

/cc @calixteman, @marco-c Can either of you please help out with this?

**Comment by marco-c** [comment]
Done!

**Comment by marco-c** [comment]
Note: I added `Lint (lts/*)` because `Lint` is not running on PRs.

**Comment by Snuffleupagus** [comment]
Thank you!
