### ISSUE TITLE
[Feature]: mobile-viewer enable pinch zoom

### ISSUE THREAD

**Issue by kosuke-zhang** [mozilla/pdf.js#19004]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

PDFJS have support pinch zoom, but why mobile-viewer cannot use this feature? how to enable or this is a bug?

**Comment by Snuffleupagus** [comment]
It's not really clear given the very limited information provided, but if you're talking about https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer that's merely *an example* and consequently it won't include all the features/functionality of the default viewer.

**Comment by kosuke-zhang** [comment]
> https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer

YES!!! it is https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer.

But how to enable pinch zoom? I didn't find the relevant documents to open pinchzoom feature. Could you help me?
