### ISSUE TITLE
[Bug]: Firefox on iOS doesn't display the PDFs properly.  

### ISSUE THREAD

**Issue by rgelb** [mozilla/pdf.js#19008]
### Attach (recommended) or Link to PDF file

N/A

### Web browser and its version

Firefox 132.0 

### Operating system and its version

iOS 18
iOS 17 (with iPad 5th gen)

### PDF.js version

4.8.89

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Start Firefox on the iPhone
2. Go to https://mozilla.github.io/pdf.js/web/viewer.html

### What is the expected behavior?

Toolbar is legible

### What went wrong?

Toolbar is illegible
![IMG_4315](https://github.com/user-attachments/assets/0dff9d3b-bdb4-4af7-89e6-2a1efca8f231)

### Additional context

As you can see from the screenshot, the toolbar is completely mangled.  This behavior is also present in Firefox for iPad as well.

**Comment by ceramist** [comment]
I also encountered the same problem, so it is not clear whether it is not compatible with mobile devices.
