### ISSUE TITLE
[Feature]:  Add Text Search and Highlighting for PDF.js Viewer

### ISSUE THREAD

**Issue by moh123adan** [mozilla/pdf.js#19017]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

I would like to add a text search and highlighting feature to PDF.js. This feature would allow users to search for specific words or phrases within a PDF document and have the matches highlighted in real-time. This functionality would improve the user experience by enabling users to locate important information quickly without manually scanning the entire document.

For example, when a user enters a term into a search bar, PDF.js could scroll to the first occurrence and highlight all matches within the document, making it easy to navigate through results.

### Other PDF viewers

Text search and highlighting are standard features in many PDF viewers, including Adobe Acrobat, Google Chrome’s PDF viewer, and Microsoft Edge’s built-in PDF viewer. Adding this feature to PDF.js would bring it closer in functionality to these popular viewers, enhancing its usefulness for researchers, students, and professionals who frequently work with large PDF files.

**Comment by Snuffleupagus** [comment]
This functionality has existed *for years*, see https://mozilla.github.io/pdf.js/web/viewer.html; please remember to test things *before* filing a feature request.

**Comment by calixteman** [comment]
![image](https://github.com/user-attachments/assets/ab4d6a03-d86f-4f08-8cdc-e3f46652269e)

**Comment by moh123adan** [comment]
Thank you for the clarification! I apologize for the oversight and appreciate the link to the existing functionality. I’ll make sure to explore the current features in more depth before suggesting any further improvements. Thanks again for the quick response!
