### ISSUE TITLE
[Feature]:  Add Annotation Support for PDF.js Viewer

### ISSUE THREAD

**Issue by moh123adan** [mozilla/pdf.js#19016]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

I'd like to see an annotation feature in PDF.js that allows users to highlight, underline, or add notes to text within PDFs. This would be useful for people reviewing or studying documents directly in the viewer. Currently, users must use external tools to annotate PDFs after viewing them, which is not convenient.

### Other PDF viewers

Many other PDF viewers, like Adobe Acrobat and Foxit Reader, support annotation features. Adding this functionality to PDF.js would enhance its usability and make it more competitive with other PDF viewing tools.

**Comment by Snuffleupagus** [comment]
Editing functionality is already implemented, and there's existing issues about extending it further, see https://mozilla.github.io/pdf.js/web/viewer.html; please remember to test things (and search existing issues) *before* filing a feature request.
