### ISSUE TITLE
Investigate if the performance of `issue18896.pdf` can be improved in Chrome

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#19032]
In https://github.com/mozilla/pdf.js/pull/19024 we had to disable the test case because it caused frequent errors on the Linux bot, as can be seen for example at https://github.com/mozilla/pdf.js/pull/19023#issuecomment-2468450381. The test case was introduced as part of the fix for https://github.com/mozilla/pdf.js/issues/18896 in https://github.com/mozilla/pdf.js/pull/18899.

It would be nice if we could eventually enable the test case again on Chrome too. Perhaps we can reduce the PDF file or find/create a different file that also reproduces the original issue and that isn't as resource-intensive to render.

**Comment by Snuffleupagus** [comment]
Let's (forward) duplicate this to issue #19138, since that one tracks timeouts in Google Chrome (on the bots) generally.
