### ISSUE TITLE
[Feature]: pdf-dist的工具栏是否可以自由控制其显示与否？

### ISSUE THREAD

**Issue by zbr826858040** [mozilla/pdf.js#19037]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

我的项目是vue3技术栈的工程化项目，我使用了pdf-dist viewer.html ，并且使用iframe预览。效果很棒！
但是，当我想要隐藏工具栏的部分按钮，或者将右侧展开中的演示模式按钮挪出来至保存按钮的旁边，并且如果可以的话我希望更改按钮的图标，用我自定义的图标。
一个小的功能请求，期望回复。

**Comment by Snuffleupagus** [comment]
Please use *only* English in this bug tracker.

**Comment by zbr826858040** [comment]
OK
