### ISSUE TITLE
[Bug]: display `/UF` from `/Filespec` when hovering `GoToE` links

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#19063]
### Attach (recommended) or Link to PDF file

[Already uncompressed file](https://github.com/mozilla/pdf.js/files/15167371/attachment-desc.pdf) with `/GoToE` link.

### Web browser and its version

`firefox-132.0.1-1.fc40.x86_64`

### Operating system and its version

Fedora 40

### PDF.js version

PDF.js: 4.7.18 [9735a840a]

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the [attached PDF document](https://github.com/mozilla/pdf.js/files/15167371/attachment-desc.pdf).
2. Hover the link.

### What is the expected behavior?

> [This is a follow-up from #18030.]

When hovering the `/GoToE` link `/UF` from `/Filespec` (instead of `/Desc`) should be displayed.

The attachment itself displays `/Desc` (as per https://github.com/mozilla/pdf.js/pull/18031) and this is perfectly fine.

### What went wrong?

![screenshot](https://github.com/user-attachments/assets/7c9637c4-0eb8-4835-a306-dc5145ed3e2a)

**Comment by Snuffleupagus** [comment]
This was implemented that way on purpose, so that FileAttachments behave *consistently* regardless of where in the viewer they're used/displayed; hence I don't really consider this a bug.

**Comment by Snuffleupagus** [comment]
> I’m afraid this forces links to be considered as embedded files themselves (which they cannot be).

Those are not really "normal" hyper-links, since clicking them simply runs *JavaScript* that trigger saving of the embedded file.

> Sorry if I’m missing your point here, but do you really think it is reasonable to display any other information when hovering an `<a>` element with other than its `href` value?

Those never displayed a "meaningful" title for FileAttachments, since as already mentioned above the links trigger JavaScript and thus don't (and can't) contain any useful `href`-value.

> It might end up being a security issue.

Sorry, but how? These "links" only trigger saving of things already present in the PDF itself.
