### ISSUE TITLE
[Bug]: Warnings from Vite for dynamic imports when using in Angular 18 app

### ISSUE THREAD

**Issue by mitiyoana** [mozilla/pdf.js#19077]
### Attach (recommended) or Link to PDF file

![Screenshot 2024-11-20 103307](https://github.com/user-attachments/assets/1d6a3ac3-f5a5-4479-8d6a-f0665a4bba6f)

### Web browser and its version

Edge 131.0.2903.48

### Operating system and its version

Windows 11

### PDF.js version

"pdfjs-dist": "^4.8.69"

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Create an Angular 18 application
2. Install pdfjs-dist
3. Start the application
4. Observe the server logs 
5. See the warning: 

12036|        const worker = yield import(
12037|          /*webpackIgnore: true*/
12038|          this.workerSrc
   |          ^^^^^^^^^^^^^^
12039|        );
12040|        return worker.WorkerMessageHandler;
The above dynamic import cannot be analyzed by Vite.

### What is the expected behavior?

There shouldn't be any warnings and the app should start smoothly. 

### What went wrong?

The dynamic import of the worker couldn't be analyzed by vite. I see that there is already a webpackIgnore comment already so it would be nice to have the same with viteIgnore.

**Comment by Snuffleupagus** [comment]
Please see PR #18395, which never landed since there was no real demand.
