### ISSUE TITLE
[Bug]: Failing to parse special characters

### ISSUE THREAD

**Issue by yaroshchuk8** [mozilla/pdf.js#19097]
### Attach (recommended) or Link to PDF file

[MLE-137.pdf](https://github.com/user-attachments/files/17892649/MLE-137.pdf)

### Web browser and its version

Google Chrome Version 131.0.6778.86 (Official Build) (64-bit)

### Operating system and its version

Windows 11 Pro 24H2

### PDF.js version

v4.8.69

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

I am trying to parse a pdf file using pdf.js library.

Here is a code snippet:
```
import * as pdfjsDist from 'pdfjs-dist';
const { getDocument } = pdfjsDist;

async function parsePdf(pdfPath){
    const pdfDocument = await getDocument(pdfPath).promise;
    const page = await pdfDocument.getPage(1);
    const textContent = await page.getTextContent();
}

const path = "D:\\Storage\\Work\\MLE-137.pdf";
parsePdf(path);
```

### What is the expected behavior?

I need to parse the special characters too if possible.

### What went wrong?

The problematic characters to parse are in the line "To do so, the letter conversion process needs to handle many character types, including: ß, ...".
I am debugging the script in my IDE and some of the special characters are missing (not parsed incorrectly, just missing).

As you can see in the screenshot below, some characters are parsed (ß, n, ², ±, i, u, í), while others are not.
![Screenshot](https://github.com/user-attachments/assets/8e87d809-5c5c-4b05-8115-7c33a5a54dfa)

Can you explain what could be the problem and is there any way to fix it?

### Additional context

I've noticed that I can't copy the problematic characters from the pdf file directly (ctrl + c) and if I upload the pdf file to google drive and open it in google docs editor, those characters are missing too.

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, since the font doesn't contain any /ToUnicode data which is necessary to enable copying to work correctly in general.

**Comment by yaroshchuk8** [comment]
@Snuffleupagus What software did you use to see that the font doesn't contain the necessary data? Is there any way to fix the PDF file so I can parse it correctly?
