### ISSUE TITLE
[Feature]: Pick up where you left off

### ISSUE THREAD

**Issue by Abdelaziz18003** [mozilla/pdf.js#19094]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

As someone who uses Firefox (which uses PDF.js under the hood) as the default PDF viewer on my daily taks, I am missing the feature of picking up where I left off, where the PDF file opens on the page I closed it on last time. This will be a really usefull feature when reading long books inside Firefox and other products using this library.

I don't know if there are any relevant workarounds for now, but I was thinking of creating an extension that saves the current scroll value in localstorage and automatically scrolls to it in the next time the same file is opened.

### Other PDF viewers

Edge has this feature by default, if you open a PDF, scroll down and closed it, then re-open it, you will land on the same page you left off.

I am new to this project. However, I have experience with Javascript and I am open to contribution if given some guidance.

Regards

**Comment by Snuffleupagus** [comment]
The GENERIC viewer already supports this, through the use of `localStorage`.
However, the Firefox PDF Viewer purposely uses `sessionStorage`; please refer to PR #4559.

**Comment by Abdelaziz18003** [comment]
Got it, thanks @Snuffleupagus for the quick reply
