### ISSUE TITLE
[Bug]: Two addresses provided on the official website cannot be opened in iOS 16

### ISSUE THREAD

**Issue by pengfeir** [mozilla/pdf.js#19101]
### Attach (recommended) or Link to PDF file

https://mozilla.github.io/pdf.js/legacy/web/viewer.html
 https://mozilla.github.io/pdf.js/web/viewer.html

### Web browser and its version

latest

### Operating system and its version

ios 15.5

### PDF.js version

15.5

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1.open  https://mozilla.github.io/pdf.js/legacy/web/viewer.html
2. ![image](https://github.com/user-attachments/assets/c15663bf-876f-427e-9dd6-38545d171b02)

### What is the expected behavior?

Can open correctly.

### What went wrong?

![image](https://github.com/user-attachments/assets/e0bdf89d-5969-44ef-8eba-7cac58f12591)

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, which the issue template explicitly asks you to check *before* reporting a bug.
