### ISSUE TITLE
[Bug]: Text selection is different with what we see

### ISSUE THREAD

**Issue by IKKEM-Lin** [mozilla/pdf.js#19103]
### Attach (recommended) or Link to PDF file

[PDF file](https://github.com/IKKEM-Lin/pdfjs-test/blob/main/web/10.1038_ncomms13869.pdf)

### Web browser and its version

Chrome 130.0.6723.117

### Operating system and its version

Windows 11 22631.4460

### PDF.js version

v4.8.69

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open https://stackblitz.com/~/github.com/IKKEM-Lin/pdfjs-test
2. Select "**the catholyte and anolyte**" as follow image and copy text
![image](https://github.com/user-attachments/assets/f9ade324-d41e-482c-8fb5-1b3dd0bbde3c)

### What is the expected behavior?

The paste result should be "**the catholyte and anolyte**" as text selection. 
BTW: the behavior of pdf viewer embed in google chrome is work as expected.

### What went wrong?

The paste result is "**he catholyte and anolyt**".

### Link to a viewer

https://stackblitz.com/~/github.com/IKKEM-Lin/pdfjs-test

**Comment by bkonic** [comment]
@Snuffleupagus I have the exact same issue running Firefox v 133 on Ubuntu. I also have the same issue with my PDFs.  Please help me understand how this bug is closed if it only works on a Beta or Nightly version of the current browsers. Can you please elaborate? Thank you.
