### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by thejupitergroup** [mozilla/pdf.js#19119]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

Make it so users can use a URL parameter (i.e., file=) to automatically load PDF documents in the example viewer and make it easier to embed them.

**Comment by Snuffleupagus** [comment]
First of all, please remember to provide a title when opening an issue.

Secondly, [as outline in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file) this is already supported, however it may also be subject [to CORS restrictions](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr).
