### ISSUE TITLE
[Bug]: find highlight matches wrong index with normalization for compound word with a line break after the hyphen.

### ISSUE THREAD

**Issue by Mario185** [mozilla/pdf.js#19120]
### Attach (recommended) or Link to PDF file

[compound_word_with_line_break_after_hyphen.pdf](https://github.com/user-attachments/files/17944819/compound_word_with_line_break_after_hyphen.pdf)

### Web browser and its version

Firefox 133

### Operating system and its version

Windows 10

### PDF.js version

v4.8.69 

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached file "compound_word_with_line_break_after_hyphen.pdf"
2. Search for the letter "o"

### What is the expected behavior?

The letter "o" should be highlighted

### What went wrong?

Because of the normalization the index is off by 1 and the letter "n" is highlighted
![image](https://github.com/user-attachments/assets/f1db1071-8291-4729-999a-40054a8c49f0)
The span for the highlight contains only the letter "n" instead of "o"
![image](https://github.com/user-attachments/assets/2c00ea82-af38-4014-903a-670a11033e66)

### Additional context

It seems that during normalization in pdf_find_controller.js the position calculated for the case "Compound word with a line break after the hyphen." is wrong.

**Comment by Snuffleupagus** [comment]
Is this perhaps a regression from PR #18730, since https://github.com/mozilla/pdf.js/issues/18693#issuecomment-2336789821 mentions that fixing that one could lead to other issues?
