### ISSUE TITLE
Idea: Create font to match PDF font's width

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#1914]
**Problem**: Right now, the text layer doesn't use the same font as the font we use for rendering the actual text. To make sure the text selection goes more or less the right way, we make sure the width of the total text in the div layer matches the width of the text that is rendered to the canvas. However, as the fonts use different spaces for characters, there is some miss-alignment for selection in the middle of the font.

**Idea**: If I understood it right, the font width is specified in the font-table somewhere. Could we use some open-source font, load it and replace the default font-width table by exactly the same widths used for the font that is printed.

The problem here might be, that there are multiple glyphs for a single character. In this case, we might want to use the average of the two glyphs widths for the corresponding character in the text-div font.

Also, the text-div font is never visible. Therefore, it could be a "very simple font", that has only a single line for each character. This makes the overhead to load an extra font for each font loaded in the PDF maybe not that much dramatic. Also, we wouldn't have to adjust the div layer anymore in the case we recognize that the glyphs used only have a direct mapping between glyph <-> character. If there are two glyphs mapping to the same character, the width might still need to be adjusted.

What do you think?

**Comment by Snuffleupagus** [comment]
Given that no work has happened on this for almost nine years, let's close it as WONTFIX for now.
