### ISSUE TITLE
[Bug]: Cannot load "@napi-rs/canvas" package: "Error: Cannot find module '@napi-rs/canvas'

### ISSUE THREAD

**Issue by soadzoor** [mozilla/pdf.js#19145]
### Attach (recommended) or Link to PDF file

https://github.com/mozilla/pdf.js/files/13179307/c53a656b-551d-4c24-bfb6-f994ef3a6d4b.pdf

But I believe it has nothing to do with the PDF file itself.

### Web browser and its version

Node.js v22.11.0

### Operating system and its version

Ubuntu 22.04.2 LTS (but I tried with newest MacOS as well, same issue...)

### PDF.js version

4.9.124

### Is the bug present in the latest PDF.js version?

No

### Is a browser extension

No

### Steps to reproduce the problem

1. Clone this repo: https://github.com/soadzoor/node-pdfjs
2. Run `npm install`
3. Run `node index.js`

### What is the expected behavior?

It should generate a PNG file

### What went wrong?

It generates a runtime error when running `node index.js`:
Unfortunately, it gives me a runtime error:
node index.js 
Warning: Cannot load "@napi-rs/canvas" package: "Error: Cannot find module '@napi-rs/canvas'
Require stack:
- /home/runner/work/pdf.js/pdf.js/src/display/node_utils.js".
Warning: Cannot polyfill `DOMMatrix`, rendering may be broken.
Warning: Cannot polyfill `ImageData`, rendering may be broken.
Warning: Cannot polyfill `Path2D`, rendering may be broken.
PDF loaded
Page loaded
node:internal/modules/cjs/loader:1249
  const err = new Error(message);
              ^

Error: Cannot find module '@napi-rs/canvas'
Require stack:
- /home/runner/work/pdf.js/pdf.js/src/display/node_utils.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at NodeCanvasFactory._createCanvas (file:///home/soadzoor/works/node-pdfjs/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10769:20)
    at NodeCanvasFactory.create (file:///home/soadzoor/works/node-pdfjs/node_modules/pdfjs-dist/legacy/build/pdf.mjs:10241:25)
    at file:///home/soadzoor/works/node-pdfjs/index.js:37:46 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/pdf.js/pdf.js/src/display/node_utils.js' ]
}

Node.js v22.11.0

### Additional context

I was happy to learn that pdfjs replaced `node-canvas` with a new canvas implementation (`@napi-rs/canvas`) which has much less dependencies. This fact also gave me hope that the [bug I reported a long time ago](https://github.com/mozilla/pdf.js/issues/17188) might be fixed now, so I gave it a shot.

First I created the canvas context like this:
```
import {createCanvas} from "@napi-rs/canvas";

var canvas = createCanvas(2048, 2048);
var context = canvas.getContext('2d');
```

Then I checked the official examples, and based on those, I replaced those with these lines below, and removed the `@napi-rs/canvas` dependency from my `package.json`, deleted `node_modules` and ran `npm install` again:
```
const canvasFactory = pdf.canvasFactory;
const canvasAndContext = canvasFactory.create(2048, 2048);
```

Unfortunately, I still have the same issue.

What am I doing wrong?

**Comment by nicolo-ribaudo** [comment]
This is indeed a bug in how `pdfjs-dist` gets bundled before publishing it `pdfjs-dist/legacy/build/pdf.mjs` contains a hard-coded path from where it gets published from:

```js
class NodeCanvasFactory extends BaseCanvasFactory {
  _createCanvas(width, height) {
    const require = process.getBuiltinModule("module").createRequire("file:///home/runner/work/pdf.js/pdf.js/src/display/node_utils.js");
    const canvas = require("@napi-rs/canvas");
    return canvas.createCanvas(width, height);
  }
}
```

**Comment by soadzoor** [comment]
> This is indeed a bug in how `pdfjs-dist` gets bundled before publishing it `pdfjs-dist/legacy/build/pdf.mjs` contains a hard-coded path from where it gets published from:
> 
> ```js
> class NodeCanvasFactory extends BaseCanvasFactory {
>   _createCanvas(width, height) {
>     const require = process.getBuiltinModule("module").createRequire("file:///home/runner/work/pdf.js/pdf.js/src/display/node_utils.js");
>     const canvas = require("@napi-rs/canvas");
>     return canvas.createCanvas(width, height);
>   }
> }
> ```

How does anyone use pdfjs in nodejs with this bug?

**Comment by nicolo-ribaudo** [comment]
One uses an older version 😅 

It'd be great if you could open a PR to fix this regression. There are two usages of `import.meta.url` in https://github.com/mozilla/pdf.js/blob/d4489531668b172a5ffd4ac6a29c3eb856af79a6/src/display/node_utils.js#L38, and Webpack is replacing it while it should leave it as-is. I'm not good enough at Webpack to quickly tell how to fix it, but the webpack config is defined in https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs.

**Comment by soadzoor** [comment]
> One uses an older version 😅
> 
> It'd be great if you could open a PR to fix this regression. There are two usages of `import.meta.url` in
> 
> https://github.com/mozilla/pdf.js/blob/d4489531668b172a5ffd4ac6a29c3eb856af79a6/src/display/node_utils.js#L38
> 
> , and Webpack is replacing it while it should leave it as-is. I'm not good enough at Webpack to quickly tell how to fix it, but the webpack config is defined in https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs.

I've tried [4.7.76](https://github.com/mozilla/pdf.js/releases/tag/v4.7.76) and `[v4.8.69](https://github.com/mozilla/pdf.js/releases/tag/v4.8.69)` , they dsn't work either, I have the following runtime error there:
![image](https://github.com/user-attachments/assets/0b209d3a-1a6a-40d8-99fd-b5e5651cca5f)

Anyway, I can see that @Snuffleupagus already submitted a PR for this, thanks!

**Comment by cponcsak** [comment]
Hi everyone. Is there a planned hot fix release for this or will it be held until the next scheduled release?

**Comment by soadzoor** [comment]
> Hi everyone. Is there a planned hot fix release for this or will it be held until the next scheduled release?

It's not my call, but if it's not too much trouble, I'd vote for a hotfix, because we can't use pdf.js in node.js with the last 3 versions because of this, it seems. I'm surprised I was the first one to report this.

**Comment by timvandermeij** [comment]
The fix for this issue is now released as part of PDF.js version 4.9.155.

**Comment by GreenFlag31** [comment]
Still have the issue : 
![image](https://github.com/user-attachments/assets/cd2d57dc-dc08-4b45-81f0-15d3a1c54acc)

Reproduction: 
1. const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs');
2. this.pdfDocument = await pdf.getDocument(docParams).promise; (got the warnings at this line, see pictures. This is a regression, I didn't get warning before)
3.  Then creating a canvas with node-canvas (installed locally, same issue with napi/rs canvas)
4. Have the issue

NB: even the build-in canvas method in pdfjs-dist is wrongly typed, there is no `createCanvas `method on it:
![image](https://github.com/user-attachments/assets/c2fb1300-dedd-4f5b-8b51-3d582bc43dde)
since this is a basic Object.

Everything was working fine with "pdfjs-dist": "4.7.76" version.

**Comment by soadzoor** [comment]
> Still have the issue : ![image](https://private-user-images.githubusercontent.com/84795623/393545280-cd2d57dc-dc08-4b45-81f0-15d3a1c54acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDU5NDAsIm5iZiI6MTczMzYwNTY0MCwicGF0aCI6Ii84NDc5NTYyMy8zOTM1NDUyODAtY2QyZDU3ZGMtZGMwOC00YjQ1LTgxZjAtMTVkM2ExYzU0YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDIxMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNjdhMWFmMzE2N2YwZTRlMDM5YjdiOTE3ZjBjNGNjNTFjMWRlMDJmYmYxYTE4ZDkxYmE2ZDhmMWNiY2QzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qifb9hSZksO-sMviXaEyVMmMM8zvjf43U2AHuMT4V8E)
> 
> Reproduction:
> 
> 1. const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs');
> 2. this.pdfDocument = await pdf.getDocument(docParams).promise; (got the warnings at this line, see pictures. This is a regression, I didn't get warning before)
> 3. Then creating a canvas with node-canvas (installed locally, same issue with napi/rs canvas)
> 4. Have the issue
> 
> NB: even the build-in canvas method in pdfjs-dist is wrongly typed, there is no `createCanvas `method on it: ![image](https://private-user-images.githubusercontent.com/84795623/393545373-c2fb1300-dedd-4f5b-8b51-3d582bc43dde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDU5NDAsIm5iZiI6MTczMzYwNTY0MCwicGF0aCI6Ii84NDc5NTYyMy8zOTM1NDUzNzMtYzJmYjEzMDAtZGVkZC00ZjViLThiNTEtM2Q1ODJiYzQzZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDIxMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmN2JhNTFmN2I2YjNmMzQ3MzJiMjFkMzFjNTQ4NzFhZDNmN2UyMjRmZmZlZDc5Yjc1OTBhMzZmMjlhNjcwOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WeNmtC6M75QA3aA4BcGHQiiHpuxzyGNDxOC3OGqn-KQ) since this is a basic Object.
> 
> Everything was working fine with "pdfjs-dist": "4.7.76" version.

I think you should upgrade your node version to at least v20, but it's better to use v22 lts.

Then probably you won't be able to use ts-node anymore, so you should replace that with vite-node. At least it worked for me that way.

**Comment by GreenFlag31** [comment]
I'm using Node v20.

**Comment by DarraghOFlaherty** [comment]
Experiencing this again in "4.10.38"

**Comment by klesun** [comment]
Experiencing still in 5.3.31
Downgrading to `4.7.76` solved the issue for me.

**Comment by raggeju** [comment]
Experiencing this still in 5.4.54.
Reverting to 4.7.76 solved the issue for me.

**Comment by ddauer** [comment]
same issue in 5.4.149 - revert solved the issue. I cannot reopen... node.js v24
