### ISSUE TITLE
[Feature]: Add Support to open a url directly

### ISSUE THREAD

**Issue by luckymore** [mozilla/pdf.js#19141]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

When I have a link but don't want to download it, for example:
https://arxiv.org/pdf/2404.07143

```[tasklist]
### Tasks
```

**Comment by Snuffleupagus** [comment]
Unfortunately it's really not clear, from this very short feature request, what you're actually asking for; please take more care to provide detailed and clear information.

Besides, the PDF.js library can already load a PDF file from a URL, note the following JSDocs for the `getDocument` function: https://github.com/mozilla/pdf.js/blob/d4489531668b172a5ffd4ac6a29c3eb856af79a6/src/display/api.js#L112-L116

**Comment by luckymore** [comment]
@Snuffleupagus What I mean is to add an input field for the pdf url, here or somewhere. Then, we can open a pdf by the url directly.
![image](https://github.com/user-attachments/assets/54d71986-3b25-45d9-bcfb-da522daab219)
