### ISSUE TITLE
[Feature]: New enhancement for PDF

### ISSUE THREAD

**Issue by Rm88-88** [mozilla/pdf.js#19162]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

There is no page number under the page images in the sidebar, which makes it very difficult with large files.

**Comment by Snuffleupagus** [comment]
Note that the thumbnails have tooltips that contain the page numbers (or page labels), which helps avoid wasting vertical space which displaying page numbers in the thumbnailView would lead to.
