### ISSUE TITLE
[Bug]: No content alert displayed when opening copy protected file

### ISSUE THREAD

**Issue by mayconghizoni** [mozilla/pdf.js#19171]
### Attach (recommended) or Link to PDF file

Hello!

When I open a copy-protected file, an alert with no content is displayed in my browser. From what I could identify, the problem is in the `pdf.sandbox.external.js` file on line 130.

I currently use the lib as a dependency and not creating a fork just to remove this is not worth it for me.

Is this really a planned feature or really a bug? In versions 3.9 the problem did not occur.

Thank you for your attention.

### Web browser and its version

Google Chrome version 131.0.6778.85 

### Operating system and its version

Ubuntu 24.04.1 LTS

### PDF.js version

4.8.69

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open Pdfjs in your browser
2. Attach a copy-protected pdf file

### What is the expected behavior?

That the alert is not displayed or that it contains some information

### What went wrong?

An alert is being displayed without information

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> Hello!
> 
> When I open a copy-protected file, an alert with no content is displayed in my browser. From what I could identify, the problem is in the `pdf.sandbox.external.js` file on line 130.
> 
> I currently use the lib as a dependency and not creating a fork just to remove this is not worth it for me.
> 
> Is this really a planned feature or really a bug? In versions 3.9 the problem did not occur.
> 
> Thank you for your attention.

Unfortunately none of the above is relevant under that heading, as the issue template tells you, and that information belongs *further down* in the issue template instead.
Furthermore, you didn't actually include the PDF file here which means that this issue isn't actionable/valid as-is.

> ### PDF.js version
> 
> 4.8.69

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by calixteman** [comment]
The embedded script is checking for `global.numero_serie` and I didn't find anything about it.
I created a pdf form from scratch and checked for it and nothing...
That said, it's pretty useless to display an empty alert since it doesn't bring any useful information for the user, so let's avoid to display it.
