### ISSUE TITLE
[Bug]: Blob URL Error in PDF.js v4.7.76 and Above

### ISSUE THREAD

**Issue by katzura1** [mozilla/pdf.js#19205]
### Attach (recommended) or Link to PDF file

I am experiencing an error when trying to read a PDF using a Blob URL with PDF.js version 4.7.76 and above. The error message is as follows:

network.js:276 Uncaught TypeError: Failed to construct 'Headers': Invalid name
    at PDFNetworkStreamFullRequestReader._onHeadersReceived (network.js:276:29)
    at NetworkManager.onStateChange (network.js:119:22)

here is the error i got in version 4.7.76 and latest
![image](https://github.com/user-attachments/assets/cb8e10a1-98fc-4ad7-b758-e74060e3f1fd)

when i using below version its work normally

![image](https://github.com/user-attachments/assets/63c5dffa-6138-4e96-9a95-1c3ccf8c8e3e)

### Web browser and its version

Google Chrome

### Operating system and its version

Windows 11

### PDF.js version

4.7.76 above

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load a PDF file using a Blob URL with the following code:

`const blob = new Blob([/* PDF data */], { type: 'application/pdf' });
const url = URL.createObjectURL(blob);
pdfjsLib.getDocument(url).promise.then(function(pdf) {
    // Handle PDF loading
});`

2. Observe the console for errors.

### What is the expected behavior?

The PDF should load successfully without any errors.

### What went wrong?

The error message appears in the console, preventing the PDF from loading.

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> I am experiencing an error when trying to read a PDF using a Blob URL with PDF.js version 4.7.76 and above. The error message is as follows:
> 
> network.js:276 Uncaught TypeError: Failed to construct 'Headers': Invalid name at PDFNetworkStreamFullRequestReader._onHeadersReceived (network.js:276:29) at NetworkManager.onStateChange (network.js:119:22)
> 
> here is the error i got in version 4.7.76 and latest ![image](https://private-user-images.githubusercontent.com/13588143/394156122-cb8e10a1-98fc-4ad7-b758-e74060e3f1fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjA0MTYsIm5iZiI6MTczMzgyMDExNiwicGF0aCI6Ii8xMzU4ODE0My8zOTQxNTYxMjItY2I4ZTEwYTEtOThmYy00YWQ3LWI3NTgtZTc0MDYwZTNmMWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4NDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MTEwY2JmYjdkNmNlZjI5ZjkxNGVjOGJiMzk5YWViMWIxOGIyZDYyMWU4OGQ4ZWM0NDgxZjRiMmUxNjY0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S_KuENeNs4714z7dfSUBIi-Bmbxul-nQRqZkUtJ-TWQ)
> 
> when i using below version its work normally
> 
> ![image](https://private-user-images.githubusercontent.com/13588143/394156292-63c5dffa-6138-4e96-9a95-1c3ccf8c8e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjA0MTYsIm5iZiI6MTczMzgyMDExNiwicGF0aCI6Ii8xMzU4ODE0My8zOTQxNTYyOTItNjNjNWRmZmEtNjEzOC00ZTk2LTlhOTUtMWMzY2NmOGM4ZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA4NDE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZTc5YjcxNzUxYWViNjZiZGRkYjY3YzgyZjcxZWNjNGRjYTBiZmI3M2NiMTVlMzk3YTU2OGJmYmFiMjcwOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0IeqVD2ntR2fpoDxKSyyKC0__WuFAtncxdrvsvPHQSU)

First of all, please note that none of this information belongs under a heading called `Attach (recommended) or Link to PDF file` and should rather be placed further down in the issue template.

> ### Steps to reproduce the problem
> 
>   1. Load a PDF file using a Blob URL with the following code:
> 
>  `const blob = new Blob([/* PDF data */], { type: 'application/pdf' }); const url = URL.createObjectURL(blob); pdfjsLib.getDocument(url).promise.then(function(pdf) { // Handle PDF loading });`
> 
>   2. Observe the console for errors.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by katzura1** [comment]
Thank you for your response. Below is additional information regarding the issue I encountered:

### Steps to Reproduce the Problem

1. I download a ZIP file using fetch, extract its content using a library, and then pass the extracted PDF file as a file parameter to viewer.html.
2. Here is the relevant code snippet: 
```javascript
// Download ZIP file
const response = await fetch("/brochure.zip");
if (!response.ok) {
  return null;
}

const contentLength = response.headers.get("content-length");
const totalSize = parseInt(contentLength, 10);
let downloadedSize = 0;
const reader = response.body.getReader();
const fileData = [];

while (true) {
  const { done, value } = await reader.read();

  if (done) {
    break;
  }

  fileData.push(value);
  downloadedSize += value.length;

  const progress = (downloadedSize / totalSize) * 100;
  console.log(progress);
}

// Create blob from ZIP downloaded
const fileBlob = new Blob(fileData);
console.log(fileBlob);

// Retrieve entries from ZIP file
const entries = await model.getEntries(fileBlob, {});

// Loop through entries
for await (const item of entries) {
  // Get file name
  const filename = item.filename.toString().toLowerCase();
  if (filename.includes(".pdf")) {
    // Get URL of PDF file
    const url = await model.getURL(item, {});
    console.log(url);
    document.getElementById("pdfjs46").src =
      "/pdfjs-4.6.8.2/web/viewer.html?file=" + url;
    document.getElementById("pdfjs49").src =
      "/pdfjs-4.9.1.5.5/web/viewer.html?file=" + url;
    break;
  }
}

``` 
3. The issue arises when using the Blob URL with PDF.js versions 4.7.76 and later. Specifically, the error occurs in the console:
```
network.js:276 Uncaught TypeError: Failed to construct 'Headers': Invalid name
    at PDFNetworkStreamFullRequestReader._onHeadersReceived (network.js:276:29)
    at NetworkManager.onStateChange (network.js:119:22)

``` 
4. The same code works perfectly with earlier versions, such as 4.6.x.

### Repository Example
To help reproduce the issue, I’ve created a sample repository with the code and ZIP file:
[https://github.com/katzura1/pdf-js-blob](https://github.com/katzura1/pdf-js-blob)

ZIP File
The ZIP file used in the example is included in the repository.

Thank you for your assistance. Please let me know if additional details are required or if there’s anything else I can do to help resolve the issue.

**Comment by Snuffleupagus** [comment]
> To help reproduce the issue, I’ve created a sample repository with the code and ZIP file:
> https://github.com/katzura1/pdf-js-blob

I've downloaded that code and ran it using the PDF.js development server, and it works for me without any errors when testing in Firefox Nightly 135.0a1.
(However I needed to tweak a couple of paths in the `index.html` file to actually get the code to run at all.)

**Comment by thuoanh-95** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> I am experiencing an error when trying to read a PDF using a Blob URL with PDF.js version 4.7.76 and above. The error message is as follows:
> 
> 
> 
> network.js:276 Uncaught TypeError: Failed to construct 'Headers': Invalid name
> 
>     at PDFNetworkStreamFullRequestReader._onHeadersReceived (network.js:276:29)
> 
>     at NetworkManager.onStateChange (network.js:119:22)
> 
> 
> 
> here is the error i got in version 4.7.76 and latest
> 
> ![image](https://github.com/user-attachments/assets/cb8e10a1-98fc-4ad7-b758-e74060e3f1fd)
> 
> 
> 
> when i using below version its work normally
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/63c5dffa-6138-4e96-9a95-1c3ccf8c8e3e)
> 
> 
> 
> ### Web browser and its version
> 
> Google Chrome
> 
> ### Operating system and its version
> 
> Windows 11
> 
> ### PDF.js version
> 
> 4.7.76 above
> 
> ### Is the bug present in the latest PDF.js version?
> 
> Yes
> 
> ### Is a browser extension
> 
> No
> 
> ### Steps to reproduce the problem
> 
> 1. Load a PDF file using a Blob URL with the following code:
> 
> 
> 
> `const blob = new Blob([/* PDF data */], { type: 'application/pdf' });
> 
> const url = URL.createObjectURL(blob);
> 
> pdfjsLib.getDocument(url).promise.then(function(pdf) {
> 
>     // Handle PDF loading
> 
> });`
> 
> 
> 
> 2. Observe the console for errors.
> 
> ### What is the expected behavior?
> 
> The PDF should load successfully without any errors.
> 
> ### What went wrong?
> 
> The error message appears in the console, preventing the PDF from loading.
> 
> ### Link to a viewer
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
