### ISSUE TITLE
Detect (from JavaScript) if Firefox plugin installed

### ISSUE THREAD

**Issue by malchmalch** [mozilla/pdf.js#1921]
I have a web site that uses PDF's extensively.

As users enter the site I check to see if they appear to have a PDF plugin. In the case of Firefox and Chrome that's done via navigator.plugins[]. If no plugin is found, I can display a page with advice on what software to install and where to get it.

Plugins are a real hassle and I'm very excited about pdf.js. The Firefox addin seems to be in great shape on multiple platforms and I am hoping this will be the answer to my prayers.

How can I detect (using JavaScript) whether the user has already installed the Firefox addin so I can display a helpful message if they don't yet have it.

**Comment by timvandermeij** [comment]
Closing since this is not relevant for the library. Moreover, the Firefox extension is no longer developed since it doesn't work in version 57 and higher and it's default now in Firefox.
