### ISSUE TITLE
[Bug]: Incorrect number of pages while opening XFA-PDF document in pdf.js viewer

### ISSUE THREAD

**Issue by mathumal07** [mozilla/pdf.js#19223]
### Attach (recommended) or Link to PDF file

[on00314e.pdf](https://github.com/user-attachments/files/18127291/on00314e.pdf)

### Web browser and its version

Firefox 133.0.3 

### Operating system and its version

Mac 14.6.1  , Windows 10

### PDF.js version

v4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the sample file in Firefox/pdf.js in any browser, it opens as 18 page pdf

### What is the expected behavior?

In adobe, the sample opens as 1 page

### What went wrong?

The sample pdf opens as 18 pages

**Comment by Snuffleupagus** [comment]
The same behaviour can be reproduced in Adobe Reader as well, if scripting is disabled.

Given that we currently don't support any scripting in XFA documents, for which there's multiple existing issues in https://github.com/mozilla/pdf.js/labels/form-xfa-js already, let's close this one as a duplicate.
