### ISSUE TITLE
[Bug]: Extracted text is in a wrong encoding

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#19231]
### Attach (recommended) or Link to PDF file

[tractor-16.pdf](https://github.com/user-attachments/files/18150400/tractor-16.pdf)

### Web browser and its version

Chrome latest

### Operating system and its version

Windows 10

### PDF.js version

4.10.4

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached PDF in the viewer https://mozilla.github.io/pdf.js/web/viewer.html
2. Select all and copy
3. Insert in any text document

### What is the expected behavior?

All text should be displayed in the right readable encoding

### What went wrong?

MASSEY FERGUSON / PERKINS ENGINES
- 4 -
01/2017 (V2.4)
Premium Quality Parts
w w w. a t s i n t e r n a t i o n a l . c o m
OEM & other company part numbers are shown for reference purposes only.
Our parts are not original or manufactured by these companies.
SHORT ENGINES ΓέϳλϗΔϧϛϣ
MOTORES PARCIALES YARIM MOTOR
MOTORES PARCIAIS έϭΗϭϣϡϳϧ
BLOC EMBIELLE
3.6($76 2OG5HI6(*$76
Parts Included
Part Description ATS REF. OEM REF.
Cylinder Block Assy.( Includes Liner) ZZ50255-ATS ==
Pistons 68301-ATS GOLD 0
Ring kits 41158041-ATS GOLD-100 05.
Connecting Rod ZZ90009-ATS ==00000%-
Crankshaft ZZ90082-ATS-000 ==0
Engine bearing U5MK0265-ATS 80.0
Thrust Washer 31137551/61-ATS ; ;
Core Plug 0650577-ATS 
Cam Bush 31134165-ATS 0
Details
Engine 
Model 0)
Bore 98.48mm
1R2I5LQJV 59
Chamber Type Bath Tub
Parts Included
Part Description ATS REF. OEM REF.
Cylinder Block Assy.( Includes Liner) ZZ50256-ATS ==
Pistons U5LP0009-ATS GOLD 8/3033
Ring kits 41158022-ATS GOLD-100 05
Connecting Rod ZZ90009-ATS ==00000%-
Crankshaft ZZ90082-ATS-000 ==0
Engine bearing U5MK0265-ATS 80.0
Thrust Washer 31137551/61-ATS ; ;
Core Plug 0650577-ATS 
Cam Bush 31134165-ATS 0
PKSE440-ATS, 2OG5HI6(*$76
Details
Engine 4.248
Model 0)
Bore PP
1R2I5LQJV 59
Chamber Type Bath Tub
Piston Type
Piston Type
06/2024 (V 3.1)
OE Quality PartsOE Quality Parts
![screen](https://github.com/user-attachments/assets/66981c18-3050-497d-a686-4c1da36879f1)

### Link to a viewer

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
Please note that it's equally broken in Adobe Reader (i.e. the PDF reference implementation) and PDFium (i.e. the Google Chrome PDF viewer), since this is a bug in the PDF document *itself*.
Given that none of the fonts contain /ToUnicode data, it's unfortunately impossible for text-extraction to work "correctly".
