### ISSUE TITLE
[Bug]: Conic gradients in PDF render as pink fallback (Unsupported shading type)

### ISSUE THREAD

**Issue by Shantanu-Bokey** [mozilla/pdf.js#19233]
### Attach (recommended) or Link to PDF file

[Akash_PadamPall_1733891260642.pdf](https://github.com/user-attachments/files/18164274/Akash_PadamPall_1733891260642.pdf)

### Web browser and its version

Mozilla Firefox Version 133.0.3 (64-bit)

### Operating system and its version

Windows 11

### PDF.js version

pdfjs-dist@4.4.168

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Generate a PDF using Puppeteer (or any HTML-to-PDF library) where an element uses a conic-gradient() in CSS (for example, a ring or radial chart).
Open the generated PDF in Chrome’s built-in viewer → The conic gradient displays properly.
Open the same PDF in PDF.js (Firefox built-in viewer or [React PDF Viewer](https://www.npmjs.com/package/@react-pdf-viewer/core) which uses PDF.js). The conic gradient appears pink instead of the intended gradient.

### What is the expected behavior?

The PDF viewer should show the same conic gradient as Chrome’s PDF viewer (or at least a comparable gradient rendering) instead of a pink fallback.
![image](https://github.com/user-attachments/assets/ea8d1ea2-e628-43b3-8159-c26456c0d0f1)

### What went wrong?

In PDF.js, the conic gradient is replaced by a pink fallback color, and the console often shows “Unsupported ShadingType: 1” warnings.
This indicates PDF.js cannot interpret the embedded conic shading pattern created by Puppeteer.
![image](https://github.com/user-attachments/assets/7095c057-9ead-4238-a2b4-ed60f8b94e39)
![Screenshot 2024-12-17 162359](https://github.com/user-attachments/assets/2ebf259e-36d9-4b41-b34e-68af77f80c71)

### Additional context

Conic gradients aren’t part of the official PDF spec, which only includes axial (type 2) and radial (type 3) shading.
Chrome’s PDF renderer apparently supports conic gradients as a vendor-specific shading extension.
We’d like PDF.js to either gracefully approximate or allow conic gradients, or at least provide clearer documentation/fallbacks.

**Comment by Snuffleupagus** [comment]
Duplicate of #5046

> ### PDF.js version
> 
> pdfjs-dist@4.4.168

This version is no longer supported.

**Comment by dario-antonio-lassoni** [comment]
The issue persists with PDFs generated via Gotenberg when opened in the latest version of Firefox (PDF.js: 5.4.445), specifically with conic-gradient() backgrounds. Is a fix planned for this in the near future?
