### ISSUE TITLE
[Bug]: Document pages rendered as black and white instead of colored

### ISSUE THREAD

**Issue by alexkonst** [mozilla/pdf.js#19242]
### Attach (recommended) or Link to PDF file

[example-b:w-page.pdf](https://github.com/user-attachments/files/18202726/example-b.w-page.pdf)

### Web browser and its version

Chrome 131

### Operating system and its version

MacOS

### PDF.js version

v4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open pdf in viewer https://mozilla.github.io/pdf.js/web/viewer.html

### What is the expected behavior?

Images on page are colored

### What went wrong?

Images on page are black and white

### Additional context

Release version v4.4.168 renders document correctly.
All release versions above (including latest v4.9.155) renders document incorrectly.
Interesting that all of them logs in browser console such warning message.
```
// v4.4.168
Warning: parseColorSpace - ignoring ColorSpace: "FormatError: Unrecognized ColorSpace: C1".

// v4.9.155
Warning: Unrecognized ColorSpace: C1
```

**Comment by alexkonst** [comment]
I've read release notes for [v4.5.136](https://github.com/mozilla/pdf.js/releases/tag/v4.5.136) and found this
>Fallback on DeviceGray when a colorspace cannot be parsed by @calixteman in https://github.com/mozilla/pdf.js/pull/18468

Seems that current behavior is fallback, but something wrong with colorspace C1 (according to warning logs).

**Comment by Snuffleupagus** [comment]
This is clearly a *corrupt* PDF document, since it doesn't render in Adobe Reader (i.e. the PDF reference implementation) and there's even a warning message displayed.

![adobe](https://github.com/user-attachments/assets/01e66837-f99f-4ae9-bc61-aa0f054c305c)

**Comment by alexkonst** [comment]
@Snuffleupagus Thanks for your help. I will try to figure out how this corrupted document was created.

**Comment by THausherr** [comment]
In the form XObject `Root/Pages/Kids/[0]/Resources/XObject/X1` the colorspace C1 is missing. It is defined in the parent resources but that's not enough.
