### ISSUE TITLE
[Bug]: Image in FormXObject with SMask is not rendered correctly

### ISSUE THREAD

**Issue by SehoAhn** [mozilla/pdf.js#19240]
### Attach (recommended) or Link to PDF file

[test.pdf](https://github.com/user-attachments/files/18193476/test.pdf)

### Web browser and its version

Firefox 133.0.3

### Operating system and its version

Windows 11

### PDF.js version

Firefox built-in, pdfjs-dist@4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the PDF in Firefox

### What is the expected behavior?

The PDF file has 4 pages.
Each page has a QR code image on top right corner.
When opened in Adobe Acrobat or Google Chrome, it appears well like:
![image](https://github.com/user-attachments/assets/01b6df84-ee6a-4c16-8d2a-240caadd6d7b)

### What went wrong?

When opened with Firefox, it looks like:
(only page 1 and 2 have the issue)
![image](https://github.com/user-attachments/assets/130233b1-aae0-4c78-bbef-e494fecf0c22)

**Comment by SehoAhn** [comment]
I found that 2 soft masks are now applying to that QR image:
_Root/Pages/Kids[0]/Resources/XObject/Fm0/Resources/XObject/Im0/SMask_
_Root/Pages/Kids[0]/Resources/XObject/Fm0/Resources/ExtGState/GS0/SMask_

But also I found PDF1.7 Specification(ISO 32000-1:2008 11.6.4.3 Mask Shape and Opacity) is saying:

> An image XObject may contain its own soft-mask image in the form of a subsidiary image XObject in the SMask entry of the image dictionary. This mask, if present, shall override any explicit or colour key mask specified by the image dictionary's Mask entry. Either form of mask in the image dictionary shall override the current soft mask in the graphics state.

which probably means the second soft mask should've ignored and only the first soft mask have applied?

Might it be the clue for the problem?

**Comment by Snuffleupagus** [comment]
This *might* be the same problem as issues #7992 and #11666.
