### ISSUE TITLE
[Feature]: Consider adding "scripts" field to package.json for common actions

### ISSUE THREAD

**Issue by FKLC** [mozilla/pdf.js#19267]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

Many JS protects define "scripts" field in package.json for common actions like building, watching, etc. Editors such as VSCode also show them under NPM Scripts for easier execution too. I think pdf.js would also benefit from this too.

**Comment by Snuffleupagus** [comment]
Marking this as WONTFIX, as outlined in https://github.com/mozilla/pdf.js/pull/19268#issuecomment-2564800585.
