### ISSUE TITLE
[Bug]: PDF document bytes are getting disposed after creating PDFJsDocument

### ISSUE THREAD

**Issue by pikumar98** [mozilla/pdf.js#19261]
### Attach (recommended) or Link to PDF file

Any PDF document

### Web browser and its version

All

### Operating system and its version

All

### PDF.js version

>=3.3.122

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Create a new html file.
2. Copy the below code and run the html in any browser
3. From the website -> https://cdnjs.com/libraries/pdf.js, copy the link to the pdf.min.js or pdf.min.js and paste the link in the text box in the running html page.
4. Click 'Load PDF.js' button.
5. Choose any PDF document and click 'Load PDF' button
6. Observe the bytes information before and after initializing the PDF document.
Note: Try with different version of the pdf.min.js links. Before testing with another link, kindly refresh the web page.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Byte Information</title>
</head>
<body>
    <h1>PDF Byte Information</h1>
    <input type="file" id="filePicker" accept=".pdf">
    <button onclick="pickFile()">Load PDF</button>
    <br/>
    <label for="scriptSrc">PDF.js Script URL:</label>
    <input type="text" id="scriptSrc" style="width: 300px;">
    <br/>
    <button onclick="loadPdfJs()">Load PDF.js</button>
    <p id="beforeBytes">Bytes before initializing PDF Document: </p>
    <p id="afterBytes">Bytes after initializing PDF Document: </p>
    <canvas id="pdfCanvas"></canvas>
    <script>
        let pdfDocument = null;

        function pickFile() {
            const fileInput = document.getElementById('filePicker');
            const file = fileInput.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(event) {
                    const bytes = event.target.result;
                    document.getElementById('beforeBytes').textContent = 'Bytes before initializing PDF Document: ' + bytes.byteLength;
                    const loadingTask = pdfjsLib.getDocument(bytes);
                    loadingTask.promise.then(pdfDoc => {
                        pdfDocument = pdfDoc;
                        console.log('PDF loaded');
                        console.log('Number of pages:', pdfDocument.numPages);
                        document.getElementById('afterBytes').textContent = 'Bytes after initializing PDF Document: ' + bytes.byteLength;
                }).catch(error => {
                        console.error('Error loading PDF:', error);
                });
                };
                reader.readAsArrayBuffer(file);
            } else {
                alert('Please select a PDF file.');
            }
        }

        function loadPdfJs() {
            if (!document.getElementById('pdfjsScript')) {
                const script = document.createElement('script');
                script.id = 'pdfjsScript';
                script.src = document.getElementById('scriptSrc').value;
                if (script.src.endsWith('.mjs')) {
                    script.type = 'module';
                }
                document.head.appendChild(script);
                script.onload = () => {
                    console.log('PDF.js script loaded');
                    if (pdfjsLib) {
                        const workerSrc = script.src.replace('.min.', '.worker.min.');
                        pdfjsLib.GlobalWorkerOptions.workerSrc = workerSrc;
                    }
                };
            } else {
                console.log('PDF.js already loaded');
            }
        }
    </script>
</body>
</html>
``` 

### What is the expected behavior?

The bytes should not become zero.

### What went wrong?

In version <= 3.2146, the bytes before and after initializing the PDF document remains same.
But, after 3.3.122, after initializing the PDF document, the bytes count becomes zero

### Additional context

I would like to know what cause/commit this behavior

**Comment by Snuffleupagus** [comment]
> ### PDF.js version
> 
> > =3.3.122

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> ### Steps to reproduce the problem

You need to provide a link to a directly runnable test-case, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> ### What went wrong?
> 
> In version <= 3.2146, the bytes before and after initializing the PDF document remains same. But, after 3.3.122, after initializing the PDF document, the bytes count becomes zero

That's the expected *and* documented behaviour, to reduce memory usage: https://github.com/mozilla/pdf.js/blob/4547f230bac8103ebfcc038a649861bae939e81c/src/display/api.js#L116-L123
