### ISSUE TITLE
huffman is not supported

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#2073]
While I've tried to upload a PDF/A document which contains a compressed image, I got the following error:

PDF.JS Build: b0d8d56
Message: JBIG2 error: huffman is not supported

**Comment by yurydelendik** [comment]
Another book https://library.sciencemadness.org/library/books/ignition.pdf (Chrome has issue with it as)

**Comment by danlester** [comment]
Another example is here:
[Ignition-JohnClark.pdf](https://github.com/mozilla/pdf.js/files/1077190/Ignition-JohnClark.pdf)

Thank you!
