### ISSUE TITLE
Text selection partly overlapping and extraction not correct

### ISSUE THREAD

**Issue by afuerlinger** [mozilla/pdf.js#2097]
If you select text out of this PDF the marked text seems to be overlapping partly. Copying the text is not working correctly:

 http://www.content-select.com/fileadmin/pdfjs_test/pdfjs_test_9783407224279_12.pdf

**Comment by Snuffleupagus** [comment]
The PDF file is no longer available, but given that we have [numerous open issue regarding text-selection](https://github.com/mozilla/pdf.js/labels/4-text-selection), I'm closing this one.
