### ISSUE TITLE
pdf.js does not support rendering some PDFs

### ISSUE THREAD

**Issue by malaterre** [mozilla/pdf.js#2133]
It looks like pdf.js does not render properly the following file:

http://bugs.debian.org/cgi-bin/bugreport.cgi?msg=5;filename=test5.pdf;att=1;bug=687379

The image should render as:

https://issues.apache.org/bugzilla/attachment.cgi?id=29364

thanks !

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #8168.
