### ISSUE TITLE
Text line should be one text line when select/copy

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#2140]
If a line is made up of multiple divs, selecting, copy and past will result in multiple lines.

That the content of the divs ends up in multiple lines seems to be the case as we use absolute positioned divs.

**Comment by aaronshaf** [comment]
If positioned span's were used instead of div's, I think this would be easier.

**Comment by luiscastro193** [comment]
I am trying to use a regex with the text of a PDF and I encountered this issue. Any known solution?

**Comment by timvandermeij** [comment]
Fixed by #10197 since we're now using `span` element instead of `div` elements.
