### ISSUE TITLE
Can't display N-400 form

### ISSUE THREAD

**Issue by cbiesinger** [mozilla/pdf.js#2348]
http://www.uscis.gov/files/form/n-400.pdf

This is with the pdf.js from Firefox Nightly 19.0a1 (2012-11-02). I just get a "Please wait..." message:

> If this message is not eventually replaced by the proper contents of the document, your PDF
> viewer may not be able to display this type of document

**Comment by marco-c** [comment]
The PDF is no longer available, and we landed support for XFA recently anyway.

**Comment by cbiesinger** [comment]
Looks like the form is now at https://www.uscis.gov/sites/default/files/document/forms/n-400.pdf but I don't know if it still uses XFA. Glad to hear you support XFA now!
