### ISSUE TITLE
Support XML Forms Architecture (XFA) forms

### ISSUE THREAD

**Issue by abevoelker** [mozilla/pdf.js#2373]
[XFA](http://en.wikipedia.org/wiki/XFA) forms are XML-based forms created by Adobe's LiveCycle Designer tool.  They offer enhanced features over the old AcroForms method of creating fillable PDF forms with things like growable text fields (which can overflow across page boundaries) and "Rich Text," which is a subset of XHTML and CSS for stylizing text.  There is also support for running JavaScript and FormCalc (a proprietary scripting language) scripts for manipulating data using a 
"Scripting Object Model" (SOM - looks sort of like XPath).  Other features include network interaction with servers (e.g. form submission) using HTTP or WSDL/SOAP.  I believe you can also embed regular PDF documents inside XFA.

I don't pretend to understand XFA ([the standard](http://partners.adobe.com/public/developer/xml/index_arch.html) is here), but I have had to deal with it recently as it seems to be the direction that Adobe is pushing towards as until very recently (with the latest version of iText), the only reliable way of manipulating these forms were with Adobe's LiveCycle Server product (epic $).  And so far, the only renderer that I've used that can even display them is Adobe Acrobat.

I see XFA has been mentioned on the [Mozilla wiki](https://wiki.mozilla.org/PDF.js#Big_project:_XFA_or_AcroForms) and [on the mailing list](https://groups.google.com/forum/?fromgroups=#!searchin/mozilla.dev.pdf-js/XFA/mozilla.dev.pdf-js/SJSLYoYxCes/uQInaNB0wLQJ) and it looks like there is some trepidation in supporting it as it is still a proprietary standard.  If this is still the case, does that mean that pull requests would also not be accepted relating to XFA?

I can totally understand why you would not want to support a proprietary and complicated standard, but thought I would bring it up anyway as it's frustrating being locked into Adobe Reader and LiveCycle Server products.  Thanks!

**Comment by brendensoares** [comment]
I would be interested in working on an extension to support this. It seems [pdf2jspn](https://github.com/modesty/pdf2json) already has written an extension for pdf.js. Any comments on this?

**Comment by fbender** [comment]
This should be revisited. Even if XFA is not a de-jure standard, it unfortunately is a de-facto standard (along AcroForms) with great distribution and (medium) renderer support. Since browsers are deprecating NPAPI plugins, it will (for a lot of existing content and content still generated today) no longer be possible to fill out PDFs with forms within the browser, leading to users being annoyed and/or websites force-downloading PDF files to be opened with another PDF reader. Supporting forms in PDF (both XFA and AcroForms) is a unique feature that has the potential to influence the market. Issue #1459 contains [further reasoning](https://github.com/mozilla/pdf.js/issues/1459#issuecomment-156979898).

**Comment by wanghaisheng** [comment]
any update?

**Comment by timvandermeij** [comment]
Currently we're working on AcroForm support (in #7613). XFA support is not planned, but I think the AcroForms work should definitely help to simplify the implementation for XFA support.

**Comment by Vinmj** [comment]
Any updates on supporting LiveCycle PDF Documents?

**Comment by nekohayo** [comment]
In case this might somehow be useful, perhaps you could use PDFium's XFA implementation code as inspiration for an implementation in pdfjs? I have no idea if it actually works, in any case it's probably better than nothing: https://github.com/chromium/pdfium/tree/master/xfa

**Comment by ludakhris** [comment]
I hate to keep asking about this but has there been any progress on this???

**Comment by timvandermeij** [comment]
XFA support is being developed and experimental, but is progressing.

**Comment by ludakhris** [comment]
Thanks so much @timvandermeij is there a timeframe or a pull request that interested parties can follow?

**Comment by timvandermeij** [comment]
The list of merged PRs is https://github.com/mozilla/pdf.js/pulls?q=is%3Apr+xfa+is%3Aclosed.

**Comment by marco-c** [comment]
I think we can now close this, as the main XFA-related work has landed.

**Comment by garyvdm** [comment]
Thank for all the hard work that went into this!

In what version of Firefox is this expected to land?

**Comment by marco-c** [comment]
Firefox 91

**Comment by marco-c** [comment]
You can already test it in Firefox Nightly, by setting the `pdfjs.enableXfa` preference to true.

**Comment by garyvdm** [comment]
Got it working. Thanks!

**Comment by crich04** [comment]
Is the Demo online the latest version of pdf.js? The reason I ask is this:
In the demo, I open/upload a local PDF. This PDF is a static PDF created by LiveCycle Designer. It has one field - super easy.
It displays fine.
I type some data into the field and click Export. It opens on my desktop using Acrobat.
There is no data in the form.

If I use the demo PDF with text fields, it works as expected - contains the data I typed.

I need the export of the PDF to contain data . . . this is super ideal.

**Comment by keyhan** [comment]
Is is possible now to save the filled input in separate XFA-file or is it merged into the PDF? Or is it not saved at all like in Acrobat Reader?

**Comment by marco-c** [comment]
@keyhan the filled data should be saved as part of the PDF.
