### ISSUE TITLE
Rendering is inaccurate due to font substitution

### ISSUE THREAD

**Issue by yurivict** [mozilla/pdf.js#2403]
Consider this document:
http://www.threeplus.com.au/_dbase_upl/Baulderstone%20_%20PCH%20progressreport_9FEB12.pdf

Letters look like they are misplaced. Some letter combinations like "st", "Br" and "Wi" touch each other.
In acroread this document shows without such artifacts.

Obviously rendering is wrong. I think the issue is that pdfjs substituted the font which makes rendering wrong.

**Comment by timvandermeij** [comment]
Closing since this no longer happens, most likely after recent font fixes. The second PDF file now renders fine, the first one is no longer available (also not in the Web Archive).
