### ISSUE TITLE
Huge PDF renders slow

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#2541]
The PDF at

  http://www.vrr.de/imperia/md/content/fahrten/stadtlinienplaene/wuppertal_2012.pdf

is 5.4 MB in size and contains only one page. It's a very detailed map with a lot of shapes. No wonder this is rendered slowly using PDF.JS but it might be worth sharing for some performance benchmarking.

**Comment by RasmusDK** [comment]
Is there any news regarding this issue? I can see that it still takes a long time when I try with documents that contains complex drawings.
Comparing with Adobe Reader it takes almost 3 times longer in pdf.js to open the same file. 
I will also welcome advices on settings etc. that can help make it faster?

**Comment by RasmusDK** [comment]
Has this issue just been dropped? or are there any news?
In my latests test I see chromes native pdf viewer opening a complex document 3-4 times faster than pdf.js. It doesn't draw anything until the end, I don't know if that makes a difference to the performance (adobe draws the same way as pdf.js, just faster).

As mentioned before, any advice on how to make load of this type of document faster, is also very welcome.

**Comment by timvandermeij** [comment]
Performance improvements landed in Firefox a while ago for the canvas drawing operations to make these kinds of PDFs render faster, but I think there is also work to do about this on the PDF.js side. We need to find out where the delay is coming from exactly to see if we can optimize that part of the codebase.

**Comment by Snuffleupagus** [comment]
> We need to find out where the delay is coming from exactly to see if we can optimize that part of the codebase.

With maps like these, there's an *absolutely huge* amount of rendering operations needed to draw them, which is probably the main reason for the slowness (given that canvas rendering is sequential).
Perhaps canvas tiling (see issue #6419) could help somewhat here, provided that it enabled us to draw different sections of a page in parallel.

**Comment by brendandahl** [comment]
The PDF is no longer there. Anyone have it and want to upload?

**Comment by Snuffleupagus** [comment]
> The PDF is no longer there. Anyone have it and want to upload?

[wuppertal_2012.pdf](https://github.com/mozilla/pdf.js/files/1522715/wuppertal_2012.pdf)

**Comment by RasmusDK** [comment]
> The PDF is no longer there. Anyone have it and want to upload?

these two are still there. I am not sure how they behave in PDF.js currently though.
http://carto.metro.free.fr/documents/CartoMetroParis.v3.6.pdf
http://carto.metro.free.fr/documents/CartoMetroParis.v3.6.simple.pdf

**Comment by SamyCookie** [comment]
The log
```
[11:50:01.324] Warning: TODO: TilingType: 1
```
has disappeared, so maybe this ticket is not related to a tiling type bug anymore ?

**Comment by caffeinum** [comment]
I have a similar issue: our PDF are lecture slides for kids with vector animals. They are exported from Apple Keynote. 

When you switch slides, new pages render sequentially in layers: first the background, then the foreground. That makes it "jump" on slow computers, where characters appear after the background is drawn.

Currently we overcome this by rasterizing: we export slides into bunch of PNG's which are then grouped into one big PDF. This works much better, but vector images look nicer.

**Comment by THausherr** [comment]
This one (copied from https://www.vrr.de/fileadmin/user_upload/pdf/service/downloads/tarifinformationen/verbundraum_2019.pdf ) is surprisingly slow in PDF.js
[verbundraum_2019.pdf](https://github.com/mozilla/pdf.js/files/3473845/verbundraum_2019.pdf)

**Comment by timvandermeij** [comment]
@THausherr That PDF file renders in about 2 seconds for me, which I don't really find slow. Do you have details about your configuration (OS, browser, PDF.js version)?

**Comment by Snuffleupagus** [comment]
One PDF file per issue please, otherwise tracking becomes a mess :-)

**Comment by THausherr** [comment]
FF 68.0.1, Windows 10, PDF.js latest version ( https://mozilla.github.io/pdf.js/web/viewer.html ). I chose this file because it is also from Wuppertal transportation. It took about 30 seconds.

**Comment by timvandermeij** [comment]
Closing since the rendering of these files is now acceptable and has improved a lot since this issue was opened thanks to multiple optimizations. For example the Wuppertal one renders in around three seconds now.
