### ISSUE TITLE
Need button to open in external viewer

### ISSUE THREAD

**Issue by benbucksch** [mozilla/pdf.js#2553]
I see a "Download" button, but when I click on it, I get a "Save As..."-Dialog immediately.

In older Firefox versions I used to get - and I still do for other filetypes -, an option to either open in an external application or save. I don't get this with the Download button in pdfjs. Now, that dialog was always annoying, it's 2 extra clicks.

Please just make 2 buttons in pdfjs: Download and Open in external viewer. The latter maybe with dropdown to select one of the viewers (and of course remembering the last choice, which will be used when I click directly on the button).

As much as I appreciate pdfjs as a quick preview and for security reasons, still external PDF viewers are needed for serious reading, work, and certain features. As-is, pdfjs makes it _a lot_ harder to get there, making life harder overall instead of improving it. A single additional button would fix that.

**Comment by grahamperrin** [comment]
### Open With Different Viewer

This button appears when a PDF _might not be displayed correctly_, for example with the current edition of <https://staff.brighton.ac.uk/is/Published%20Documents/UoB%20IT%20Regulations.pdf>: 

![image](https://user-images.githubusercontent.com/192271/65373246-cde17c80-dc72-11e9-8c74-b9f49b4e3b96.png)

As a slightly ugley workaround to this issue #2553, I wonder … might the viewer be 'tricked' into always presenting the banner that contains the button?

**Comment by JiPa2022** [comment]
Yes please implement this button alongside the download button, related to #15326
Very much needed

**Comment by Snuffleupagus** [comment]
@marco-c, @calixteman Do we want to implement this for the default viewer (since something similar was done for GeckoView), or should we close this old issue as WONTFIX?

**Comment by marco-c** [comment]
I think we should close this, it doesn't make a lot of sense in the default viewer.
