### ISSUE TITLE
Slow rendering with libreoffice impress template

### ISSUE THREAD

**Issue by ofirdev** [mozilla/pdf.js#2616]
A PDF created using a libreoffice impress template takes much longer to render than other documents.

Please see the attached odp and pdf files:
https://docs.google.com/file/d/0B0odzw1WMqkGakk3Tklfbm0yYk0/edit
https://docs.google.com/file/d/0B0odzw1WMqkGV3RXWTlGY0hkRG8/edit

**Comment by timvandermeij** [comment]
IE9 is not supported anymore in PDF.js 2.0, so I'm closing this issue as won't fix.
