### ISSUE TITLE
Feature request for the future: PDF layers

### ISSUE THREAD

**Issue by Richard-Mlynarik** [mozilla/pdf.js#269]
That is all.

The code looks really promising!

**Comment by wizkids** [comment]
I'm also interested in knowing when layers will be supported (specifically showing/hiding them).

**Comment by timvandermeij** [comment]
There is no implementation for this yet and as far as I know no-one is working on this. If someone wants to work on this, feel free to create a pull request.

**Comment by THausherr** [comment]
Files with OCGs:
http://ims.er.usgs.gov/images/USTopo/
(not all, only the huge ones)

**Comment by boundaryfree** [comment]
Also expect this feature. Get layers info/showing layer/hiding layer.

**Comment by boundaryfree** [comment]
Hi, also expect OCGs (layer) supports. Any schedule?

**Comment by timvandermeij** [comment]
Currently this feature is not planned to be implemented. If someone wants to work on this, please let us know. If you can attach more example PDF files here, that would help to get people started and verify their work.

**Comment by THausherr** [comment]
Here's a simple one:
[PDFBOX-4103-OCG.pdf](https://github.com/mozilla/pdf.js/files/2940627/PDFBOX-4103-OCG.pdf)

**Comment by gitspeare** [comment]
an old example with transparency and ocgs, it'd be nice if the ocgs were selectable from within a browser/ page
[_myChessboardv1.2_mockup_ImageArray_beta0.7 - public.pdf](https://github.com/mozilla/pdf.js/files/2940821/_myChessboardv1.2_mockup_ImageArray_beta0.7.-.public.pdf)

**Comment by 2Owy** [comment]
I'm trying to identify some content from PDF.
I understand that I can't use the layers because they are not supported. 
Is that corect ?
And is there another way ?

**Comment by mkubdev** [comment]
Hi, i'm trying to identify too OCG content from PDF inside pdf.js. As i searched, OCGs Layers can't be rendered on the viewer ?
Do you think there is a way to play with layer from Illustrator/AutoCAD/etc... ?

**Comment by mkubdev** [comment]
I'm working on this feature actually. I'm trying to identify where and when pdf.js read the document, parse it, then exclude the OCGs (https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf page 222), i think it's on stream.js

What i found, is that [evaluator.js#L606 ](https://github.com/mozilla/pdf.js/blob/1421b2f2056ae6dac564469374ff43342a3fb891/src/core/evaluator.js#L606) got a switch, and i think i need to work on the case 'D'... Nobody worked on OCGs?

**Comment by mkubdev** [comment]
Also expect this feature. Get layers info/showing layer/hiding layer.

**Comment by ConradJChan** [comment]
Hi, I realize this issue is 8 years old, but would just like to add to the case that this would be a very useful feature to have. Perhaps things have changed in 2 years?

**Comment by developerashu** [comment]
Please update the status if someone have worked on this issue and resolved it.

Thankyou

**Comment by pnocera** [comment]
+1

**Comment by nuthinking** [comment]
+1

**Comment by timvandermeij** [comment]
Please don't post individual "+1" comments, but give the original comment (https://github.com/mozilla/pdf.js/issues/269#issue-1238154) a thumbs up using GitHub's reaction mechanism. This prevents needless bumps on this issue and allows us to filter based on priority from the community.

**Comment by Jonani92** [comment]
Hallo, is there any update of the priority of this future request? :)
It seems like a lot of duplicated posts referencing the same issue, which might not be explained and shown in a good example in this post?

**Comment by timvandermeij** [comment]
Nobody is currently working on this. If anyone wants to contribute, we're always happy to review pull requests.

**Comment by Snuffleupagus** [comment]
The reason that this isn't implemented yet is most likely because it happens to be a fairly complicated subject, given the way that all of this is described in the PDF specification.
Ignoring *a lot* of the other specifics surrounding OCGs, section ["8.11.3.1 General"](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.3987734) of the specification states (note the *second* point):

> When a piece of optional content in a PDF file is determined that it shall be hidden, the following occurs:
> - The content shall not be drawn.
> - Graphics state operations, such as setting the colour, transformation matrix, and clipping, shall still be applied. In addition, graphics state side effects that arise from drawing operators shall be applied; in particular, the current text position shall be updated even for text wrapped in optional content. In other words, graphics state parameters that persist past the end of a marked-content section shall be the same whether the optional content is visible or not.
```

**Comment by ma-rf** [comment]
Hey there, I've been trying to find a solution for this issue during the last week and was hoping someone can point me in the right direction.
For my use-case, it would not be necessary to toggle additional layers, I would simply need to hide them in my viewer.

So far I was able to identify the "hidden" layers inside document.js like this:

`const hiddenLayers = this.catalog.xref.root._map.OCProperties._map.D.get("OFF");`

But I could draw the connection between the layers and the actual content that is rendered by pdf.js. So if anyone could give me a hint how to figure out which data is supposed to be hidden, I'd rellay love to put it to use.

**Comment by nuthinking** [comment]
@brendandahl how does the new API works? What is "Optional Content"? Can't we simply scan existing layers and hide them? Thanks!

**Comment by Snuffleupagus** [comment]
>  What is "Optional Content"?

See https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.3858031

> Can't we simply scan existing layers and hide them?

Unfortunately it's really quite difficult to understand what you're asking here.
*Note:* This functionality has not yet been integrated into the default viewer, however that'll be addressed in #12170.

**Comment by nuthinking** [comment]
Sorry, I meant detecting them and having the option to manipulate them (hide, remove, etc...)

**Comment by THausherr** [comment]
I tried the feature and it works as expected, which is that instead of displaying all layers, it only displays the ones for viewing.

**Comment by brendandahl** [comment]
> @brendandahl how does the new API works? What is "Optional Content"? Can't we simply scan existing layers and hide them? Thanks!

The full API still needs a bit more work, but you can `pdfDoc.getOptionalContentConfig` then iterate over the various `optionalContentConfig.groups` and set which ones you want to hide/show (`optionalContentGroup.visible`). Then pass that config into your call to `render` a page.

Useful links:
https://github.com/mozilla/pdf.js/blob/63e33a5895bb730ce0e6a65e4d0de12ed043b649/src/display/api.js#L779

https://github.com/mozilla/pdf.js/blob/63e33a5895bb730ce0e6a65e4d0de12ed043b649/src/display/optional_content_config.js#L25

https://github.com/mozilla/pdf.js/blob/63e33a5895bb730ce0e6a65e4d0de12ed043b649/src/display/api.js#L958

**Comment by nuthinking** [comment]
@brendandahl oh, this looks very interesting! I will give it a go. Thanks!

**Comment by nuthinking** [comment]
@brendandahl a pdf like [this](https://assets.codepen.io/4628065/canva.pdf) doesn't seem to have any `optionalContentGroup`. How could I split the different elements into multiple renderings? I can see there is a SVG exporter. I wonder if parsing an SVG tree would be easier.

**Comment by Mauriciocr207** [comment]
Does this PR include support for OCGs in the future?
