### ISSUE TITLE
Viewer does not indicate that a document is copy-protected

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#2699]
Adobe has a "lock" sidebar item that appears when a document is copy-protected, and then indicates inside that sidebar item what you **can't** do with the document. PDF.js has nothing of the sort, so until you open the PDF in a viewer that _does_ tell you the permissions, it (possibly) could be a bug in PDF.js. And more likely than not, you will get some reports from people that _do_ think it is a bug in PDF.js.

Adobe sidebar (example):

> This document has an open password or a modify password.
> 
> You cannot edit or copy this document.
>   [Permission Details](about:blank)

The final link goes to a dialog box that says (something like) the following:
![Untitled](https://f.cloud.github.com/assets/2175324/140419/ce42b7a8-721f-11e2-8144-6c616d65be78.png)

**Comment by agharbeia** [comment]
What's the purpose of enforcing this when someone else can write a tool, or indeed modify this one, to not enforce it!
In other words, what's the point in enforcing this at all!

**Comment by Snuffleupagus** [comment]
The current state of things, given the existing code:
 - None of these document permissions are enabled/enforced by default in the PDF.js viewer, which thus includes the built-in Firefox PDF Viewer.
 - When the `pdfjs.enablePermissions` preference is set (in Firefox), currently *only copying* is disabled and the text-selection cursor is then replaced with the "not-allowed" cursor (to indicate that text-selection/copying is prevented); see also PR #11789.
 - The rest of the document permissions are currently *not* implemented.

All-in-all, given that the only supported document permission is indicated (via the cursor), closing this old issue as WORKSFORME for now.
