### ISSUE TITLE
Transparent gradient not displayed correctly

### ISSUE THREAD

**Issue by pamelafox** [mozilla/pdf.js#2730]
When opening this PDF (https://dl.dropbox.com/u/10998095/get_certificate.pdf), the coursera logo does not display correctly, the gradient on the C is rendered as white.

In PDFJS:
http://dl.dropbox.com/u/10998095/Screenshots/moz-d4np~60n.png

In Adobe PDF viewer in Chrome:
http://dl.dropbox.com/u/10998095/Screenshots/63ojqql3gwkq.png

We would like to use PDFJS to render our PDFs on our certificates page, but would feel more comfortable doing that if we knew everything would be rendered correctly.

Thanks!

**Comment by THausherr** [comment]
That is a shading type 2.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6684.
