### ISSUE TITLE
TilingType

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#2765]
http://pubs.usgs.gov/sim/3067/pdf/sim3067sheet-2.pdf does not have black lines where it should in pdf.js. This is probably because of the warning in the console:

> Warning: TODO: TilingType: 3

... that gets printed 125 times in a row.

Since enough other PDFs want this, perhaps it's finally time to attempt a _complete_ implementation?

**Comment by Rob--W** [comment]
Is this bug report still relevant? I don't see any issues with the provided PDFs and descriptions.

**Comment by timvandermeij** [comment]
I'm going to keep only the performance label here as both PDFs are not very performant (especially the first one). The image issues appear to be resolved as far as I can tell.
