### ISSUE TITLE
Printing is slow and generates huge amount of output

### ISSUE THREAD

**Issue by musiphil** [mozilla/pdf.js#2771]
I have a PDF document called short-math-guide.pdf, which has 17 pages and takes 531 KB on disk. It's all text (with symbols), has no images, and was generated by pdfTeX-0.14h (according to Adobe Reader).

When I print this document from Adobe Reader, printing is done in a few seconds and I see **1.35 MB** is sent to the printer. However, when I print it from the builtin PDF reader of Firefox 19, it takes about 40 seconds and **381 MB** is sent — **282 times** 1.35 MB.

![PDF js-printqueue](https://f.cloud.github.com/assets/3655356/182163/e5619f70-7c66-11e2-9598-ab46c09906c4.png)

This is not an acceptable performance, and together with the printing quality problem, makes me wonder why I would use the builtin PDF reader when I can just download the Adobe plugin for free and use it (as I have always done).

**Comment by timvandermeij** [comment]
Since this issue has been opened, various optimizations have improved this a lot. When I now print this to a file using the latest version of PDF.js, the resulting file size is 21 MB. Still large, but much better than 381 MB.

**Comment by timvandermeij** [comment]
Closing as fixed after recent printing PRs.
