### ISSUE TITLE
Errors downloading test pdfs

### ISSUE THREAD

**Issue by divergentdave** [mozilla/pdf.js#2774]
I'm getting my development environment set up, following the instructions under [Contributing](https://github.com/mozilla/pdf.js/wiki/Contributing#wiki-ref-images). I had some trouble getting my reference images set up because three test PDFs couldn't be downloaded from their original servers. I got a 404 for hmm.pdf, a 403 for wdsg_fitc.pdf, and a 404 for issue1055.pdf.

I was able to get hmm.pdf via archive.org. I could download wdsg_fitc.pdf manually with Firefox without any issues. (Perhaps the original host of this file doesn't appreciate the extra traffic) It looks like @mcpherrinm used to host issue1055.pdf on his server, and it doesn't show up in archive.org, so I'm stuck with that one.

Everything else downloaded without visible errors, although the following PDFs don't have the right MD5 sums: intelisa.pdf, german-umlaut.pdf, f1040.pdf, ibwa-bad.pdf

FWIW, I'm building under Cygwin.

**Comment by Snuffleupagus** [comment]
I'm closing this, since the general issue of unavailable test files is tracked #5091.
