### ISSUE TITLE
Inconsistent whitespace

### ISSUE THREAD

**Issue by arski** [mozilla/pdf.js#2775]
Hi there, I'm imagining this is somewhat related to https://github.com/mozilla/pdf.js/pull/2167 but I'll open a new issue just in case as that one has been closed for a while.

In this document here http://www.who.int/immunization_delivery/new_vaccines/5.Coreinformation_Hib.pdf if you go to the bottom and check out the references - you'll see that almost every letter has its own div and also many of the spaces are not represented as real spaces, but as divs being positioned absolute-ly

I suppose a similar but less dramatic case is http://www.nice.org.uk/nicemedia/live/12018/41363/41363.pdf - go to the bottom and checkout out reference 199 - it, as most places in this doc, has spaces being represented as spaces most of the time, but you'll see just before "2007" the space is again not a real space, but two divs positioned to create a visual space.

Is there something that could be done about this?

Cheers

**Comment by SamyCookie** [comment]
Hi, both PDF file have disappered but I have reupload them: [5.Coreinformation_Hib.pdf](https://github.com/mozilla/pdf.js/files/2372855/5.Coreinformation_Hib.pdf) and [41363.pdf](https://github.com/mozilla/pdf.js/files/2372856/41363.pdf).

It seems that the situation you describe (a too much use of div) is a lot better today than before.
If the situation is now OK, maybe this issue can be closed ?

**Comment by timvandermeij** [comment]
Closing since this is now fixed.
