### ISSUE TITLE
Character with umlauts are treated as 2 chars in search/selection

### ISSUE THREAD

**Issue by xavier114fch** [mozilla/pdf.js#2807]
Also observe this with the default tracemonkey paper.
1. Use the Find tool and enter "na" in the search box. Check the "Highlight all" box.
2. Scroll down to page 2 of the paper, and see the 3rd paragraph. It highlights "naive". Point your mouse and highlight the whole word, you can see the letter i with umlaut is highlighted twice.
3. Right click on the word "naive" and you can see the Search Google text becomes "na ̈ ıve".
4. Copy the text and paste elsewhere. The result is also "na ̈ ıve", where the umlaut and letter i are treated as 2 characters.

**Comment by Snuffleupagus** [comment]
Given that https://github.com/mozilla/pdf.js/issues/2807#issuecomment-32075437 still applies, I'd suggest WONTFIX here since it doesn't seem meaningful to keep this issue open.
