### ISSUE TITLE
printing not correct for landscape

### ISSUE THREAD

**Issue by ce03** [mozilla/pdf.js#2851]
This pdf file is landscape, and is displayed as such in the browser.  When I print it, it appears as half of a portrait page. If I use Print Preview I can change to landscape but I don't want to have to remember to do this.

Sample file - http://services.land.vic.goc.au/pdfjs/map1.pdf
Screen grab - http://services.land.vic.goc.au/pdfjs/map1.jpg

**Comment by silentsakky** [comment]
Does anyone have any fix for this issue?

**Comment by ousia** [comment]
_Acrobat_ has an orientation parameter in the printing  dialog that can be set to auto, such as in:

![not this](https://helpx.adobe.com/acrobat/kb/print-mixed-page-sizes-acrobat/_jcr_content/main-pars/procedure_0/proc_par/step_2/step_par/img_0.img.png/mixed_win_step3.png)

Image linked from _Adobe_ and it has another property selected.

Maybe it would be helpful that PDF.js implements page auto-orientation as default.

**Comment by jscher2000** [comment]
Could something like this help in adapting to the unknown orientation the browser will use:

````
@media print and (orientation: portrait) {
  /* Rotate page if it is landscape */
}
@media print and (orientation: landscape) {
  /* Rotate page if it is portrait */
}
````

**Comment by stbear** [comment]
I've changed the following lines of code:
`return pagesOverview.map(function (size) {
        if (isFirstPagePortrait === (0, _ui_utils.isPortraitOrientation)(size)) {
          return size;
        }`
to
`return pagesOverview.map(function (size, index) {
        if ((index == 0 && isFirstPagePortrait || index > 0 && (0, _ui_utils.isPortraitOrientation)(size))) {
          return size;
        }`
and it works fine for me. Didn't test it much, since our app with embedded PDF.js will be deployed to end users in fall.

**Comment by timvandermeij** [comment]
Closing since this is fixed by the PR above.
