### ISSUE TITLE
print pdf file as it is - not as a browser page

### ISSUE THREAD

**Issue by ce03** [mozilla/pdf.js#2852]
This map is designed to fill an A4 page, and Acrobat prints it as that - the file has "Actual size" set as a preference so the scale bar prints as the correct length. The map can also be created as A3 and Acrobat also honours the "Choose paper source by PDF page size" preference and correctly prints the A3 page without any intervention.
I don't want to use Page Setup and remove margins, headings, etc, and set scale to 100% every time I want to print such a file.
Perhaps a second print button is needed to allow printing of the file as Acrobat does,

Sample map - http://services.land.vic.gov.au/pdfjs/map1.pdf

**Comment by yurydelendik** [comment]
Fixed by #7677
