### ISSUE TITLE
Add way to customize viewer toolbar

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#2871]
There is some functionality on the context menu (and hopefully soon in a special panel once #2792 lands) that I would love to access from the toolbar. These actions might not be useful for everyone and therefore don't make sense to put them in the toolbar by default. However, it would be nice if the user could customize the toolbar her-/himself.

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and that there's no current plans to implement something like this, let's just duplicate it to https://bugzilla.mozilla.org/show_bug.cgi?id=1740425
