### ISSUE TITLE
Interactive PDF doesn't work

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/pdf.js#2896]
How to reproduce this problem:
* Open http://www.jasnapaka.com/temp/INteractivePDF.pdf.
* There are some blue points (cities) and hover over these points should open bubbles with images. Try in Adobe Reader. With pdf.js are these images showed by default.

**Comment by fbender** [comment]
See #1459 for tracking the forms issue

**Comment by timvandermeij** [comment]
@JasnaPaka The link is dead. Do you have a new one?

**Comment by timvandermeij** [comment]
Closing for now until a new link is provided.

**Comment by Hyangyong** [comment]
People can take a good sample about interactive PDF on web in case anybody go to the site named www.smarttest.kr. Have a nice day.
