### ISSUE TITLE
Support for Rich Text annotations

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [mozilla/pdf.js#2966]
In PDF annotations an HTML code can be used. Such annotations are not processed correctly in PDF.js (nothing is displayed).

**Comment by qwer1304** [comment]
The situation is better in version 2.12.211 - some formatting is supported (e.g., bold, italics).
However, it seems that text size isn't respected as the following images show:
First from Acrobat Reader:
![image](https://user-images.githubusercontent.com/2311076/143679464-7d51ebaf-11a6-43a1-9d39-581f9b988653.png)

Then from pdf.js:
![image](https://user-images.githubusercontent.com/2311076/143679508-f7133fe1-76c7-439c-bc00-61edec86467c.png)

Notice how the superscript and subscript sizes is screwed up.

**Comment by calixteman** [comment]
@qwer1304, please open a new issue with the pdf containing those annotations.
