### ISSUE TITLE
Search highlight in wrong position

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#2980]
Hi guys,

in this pdf: http://www.ics.com/files/docs/kd/KDChart1refman.pdf

There is wrong highlight position in page 22.

This is a know issue?

I'm using Nightly, pdf.js development and Ubuntu 12.04
![Captura de tela de 2013-03-22 10:12:44](https://f.cloud.github.com/assets/1039418/290806/5f0db72c-92f2-11e2-968d-55c11b2bbeac.png)

**Comment by marcosps** [comment]
@SamiChoudhury I tested using current Nightly in Flatpak, and it seems this is solved. As I cannot reproduce the issue anymore, I'm closing the bug. If you can still reproduce, please reopen the bug.

**Comment by sneps85** [comment]
The bug seems not to be fixed for Android WebView. May you have a look? It works fine in desktop browsers, mobile browser and ios WKWebview, but not in Android WebView.

**Comment by KnIfER** [comment]
same large offset for android webview, 
![screencap (1)](https://user-images.githubusercontent.com/11593903/194766222-db78775a-3b20-4ef3-b125-b012ad5617de.png)

**Comment by KnIfER** [comment]
> The bug seems not to be fixed for Android WebView. May you have a look? It works fine in desktop browsers, mobile browser and ios WKWebview, but not in Android WebView.

Try `wv.getSettings().setTextZoom(100)`

**Comment by KnIfER** [comment]
another problem —— the browser  has a **minimal supported font-size** for an expample it is 13px right now on my laptop.

anything smaller is "invalid",  to fix that, the css transfromation value of the text layer spans should be smaller : 

![image (1)](https://user-images.githubusercontent.com/11593903/202833303-f496127d-5f42-4c8f-97f0-c39b0673f81e.jpg)

"fix"ed:

![image](https://user-images.githubusercontent.com/11593903/202833324-4dbca4c1-15cc-4500-8417-f89ae54755d7.jpg)
