### ISSUE TITLE
Bug 810636 - Poor copy & paste behavior with pdf.js

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#2989]
See also Bug 810636 on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=810636 for reference.

**Basic problem**: The textLayer is build up from multiple `<span>` elements. If the user selects text across multiple spans and copies the text, there is a newline insert between each span. However, it makes more sense (in most cases) to just insert a whitespace. Firefox has now support to change the clipboardData during the copy/cut event (background: https://bugzilla.mozilla.org/show_bug.cgi?id=407983). 

**Implementation idea**:
1. Add an `onCopy` and `onCut` event listener to PDF.JS
2. If the event is fired, look at the current selected text in the textLayer
3. For each selected text in the span, take that text and concat it with a whitespace
4. Put the resulting string on the clipboarData object by using 

This shouldn't be hard to implement and I have a plan for it bug lack the time to do it myself and make sure it lands properly.

Let me know if someone is interested in fixing this.

**Comment by timvandermeij** [comment]
Closing since we now use `span` elements. For any remaining issues, please check if we already have an open issue. If not, please open a new one since this one has become too general to be actionable.
