### ISSUE TITLE
sans serif font problem

### ISSUE THREAD

**Issue by beingalink** [mozilla/pdf.js#2996]
File exposing the issue: http://www.gesis.org/fileadmin/upload/forschung/publikationen/zeitschriften/isi/isi-29.pdf

Text using sans serif font looks broken (Headings,etc.).

Platform: Mac OS X 10.8.3, Firefox Nightly 22.0a1 (2013-03-26)

**Comment by timvandermeij** [comment]
Closing since this no longer happens, most likely after recent font fixes.
