### ISSUE TITLE
performance problems, rendering problems in keynote-generated PDF

### ISSUE THREAD

**Issue by samth** [mozilla/pdf.js#3001]
PDF here: http://www.ccs.neu.edu/home/dvanhorn/talks/umd-trustworthy-2013.pdf

A sampling of the problems:
* Very slow performance, for example on pages 130-140.
* Flickering images on page 5 the first time it's rendered
* Errors in rendering, as on page 18 (missing "g" in "predicting").

**Comment by samth** [comment]
The flickering seems to no longer happen. The other problems are still here (FF nightly, built-in pdf.js).

**Comment by timvandermeij** [comment]
The PR mentioned above might be the fix for the missing "g" character, which would leave the performance issue after it is merged. Thanks for the update.

**Comment by Snuffleupagus** [comment]
The font issues are fixed by PR #6724.

**Comment by timvandermeij** [comment]
The performance of this file is also fine now after the latest patches. Closing as fixed.
