### ISSUE TITLE
Weird rendering of first page

### ISSUE THREAD

**Issue by davidascher** [mozilla/pdf.js#3070]
Of this illustrious document:

  http://former.vancouver.ca/ctyclerk/cclerk/20130409/documents/rr2.pdf

character positioning on first page is, I hope, not correct.

Using firefox nightly 23.0a1 (2013-04-05)

**Comment by timvandermeij** [comment]
Closing since this no longer happens, most likely after recent font fixes. The character spacing is now much better given the fact that the fonts are not embedded.
