### ISSUE TITLE
Progress bar display when changing PDFs

### ISSUE THREAD

**Issue by derekrosien** [mozilla/pdf.js#3090]
Have a really nice integration with PDF.js, working well.

Do have a few questions though:

Is there a way to display the loading progress bar when switching PDFs?

We are loading large PDFs into the tool, initially the loading progress bar is displayed for the first PDF, which works great. However when you switch to a different PDF using the PDFView.open() method, it just sits there loading the new PDF in the background, then when it is done loading, it displays it.

Being that we are loading very large PDFs this makes the page appear broken... Would love to display the loading bar overtop of the first PDF while the second one is loading.

Is this possible?

Or is there a "loaded" and/or "loading progress" event(s) or something that we can listen for and just display a loading message ourselves.

Thanks

**Comment by cemerick** [comment]
I hit this too, and thought I'd submit a patch, but I don't yet grok the `disableAutoFetch` option and related bits well enough to feel confident in that.

As a workaround, adding this just prior to every `PDFViewerApplication.open()` call works great:

```js
PDFViewerApplication.loadingBar.show();
PDFViewerApplication.loadingBar.percent = 0;
```

In short, the `loadingBar` is never reset after the first document is opened, so just resetting its state works just fine. AFAICT, this could be the entirety of the patch, maybe right after `downloadComplete` is reset to `0`; I can submit that, if it seems reasonable.

**Comment by Snuffleupagus** [comment]
In the default viewer opening a new PDF file usually means a *local* one (either through the "Open File"-button or via drag-and-drop), in which case displaying the `loadingBar` isn't very meaningful.

Should this simply be closing as WONTFIX, given the specialized use-case described here?
