### ISSUE TITLE
Some Chinese characters not displayed from PDF generated by Inkscape

### ISSUE THREAD

**Issue by xavier114fch** [mozilla/pdf.js#3117]
You can get the file here:
https://www.dropbox.com/s/09eg9pj6pf4g0ir/hk-2020.pdf

There are some Chinese characters failed to display on the map:
* In the legend box to the upper right, you can see holes that fill up the character "觀塘" next to the green line, and "灣" just next to the red line.
* On the red line, the station names are missing the character "灣" for "荃灣" and "長沙灣".
* On the green line, the station names are missing the characters "塘" for "九龍塘" (light blue/green lines interchange) and "油塘" (purple/green lines interchange), "灣" for "九龍灣" and "觀塘" is completely missing.
* On the blue line, the station names are missing the character "灣" for "灣仔", "銅鑼灣", "西灣河", "筲箕灣" and "柴灣".
* On the brown line, the station names are missing the character "灣" for "土瓜灣".

In general, the characters missing are "灣", "塘" and "觀塘". If you highlight the text you can see the bounding box of the characters. If you select them and right click, you can see the proper text shown up in the Search Google for item.

Testing in Nightly and latest pdf.js (0.8.55). This happens both on Windows 8 (with hardware acceleration on) and Arch Linux (with latest update installed). The PDF file is generated from Inkscape 0.48.4 on Windows from an SVG file, using File > Save a Copy. The PDF setting are:

* Restrict to PDF version: 1.5
* Rasterize filter effects: checked
* Resolution for rasterization: 90 dpi
* Other options are left unchecked

The Chinese font used in the SVG is Adobe Fan Heiti Std (Adobe繁黑體 in Chinese) and it came from an Adobe CS6 Suite install.

The Web Console does not display any useful information.

[12:21:32.214] "PDF 27d234c2487072caf713a2b425f7128 [1.5 cairo 1.11.2 (http://cairographics.org) / cairo 1.11.2 (http://cairographics.org)]"
[12:21:32.385] "Warning: Not enough parameters for rcurveline; actual: 0, expected: 8"
[12:21:32.385] "Warning: Not enough parameters for callsubr; actual: 0, expected: 1"
[12:21:32.409] "Warning: Not enough parameters for rcurveline; actual: 7, expected: 8"

**Comment by brendandahl** [comment]
@xavier114fch Can you post a new link? The above does not work for me anymore. Or if anyone else has the pdf still.

**Comment by Snuffleupagus** [comment]
[issue3117.pdf](https://github.com/mozilla/pdf.js/files/52492/issue3117.pdf)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6724.
