### ISSUE TITLE
API support for page labels

### ISSUE THREAD

**Issue by jlegewie** [mozilla/pdf.js#3165]
Hi,
it would be great to have API support for logical page numbers and integrate them in the viewer. A lot of pdf's from academic databases (eg. JSTOR) use "logical page numbers". As far as I know, they are included in the "page label dictionary". This is discussed in section 12.4.2 [PDF 1.7 spec](http://www.adobe.com/devnet/pdf/pdf_reference.html) (document on bottom).

Best!

**Comment by as-com** [comment]
I absolutely need this feature to be implemented. Otherwise, I'm going to hack the viewer into using my own page number -> label map. That won't be pleasant.

**Comment by SamyCookie** [comment]
This feature seems to be added in #6803. Close ?

**Comment by timvandermeij** [comment]
Correct. We have #6902 to track the inclusion in the viewer.
