### ISSUE TITLE
Text is incorrectly kerned/joint in PDF

### ISSUE THREAD

**Issue by gcp** [mozilla/pdf.js#3185]
http://labsdownload.adobe.com/pub/labs/flashruntimes/shared/air3-7_flashplayer11-7_releasenotes.pdf

Note the first sentence with "Thisprerelease" and "Thisdocument". Official Adobe PDF reader renders it correctly. Rest of the PDF seems to be fine.

**Comment by Snuffleupagus** [comment]
I can no longer reproduced this issue, using: PDF.js 1.0.1118, Windows 7 (64-bit), and Firefox Nightly 38 (buildID: 20150126030202) with HWA on.
Closing as worksforme.

**Comment by timvandermeij** [comment]
Confirmed to be fixed.
