### ISSUE TITLE
Highlighting selects wrong things when moving to non-text spaces

### ISSUE THREAD

**Issue by rstanyan** [mozilla/pdf.js#3200]
I notice when I highlight text if I move to a space between lines the highlight changes to only cover all the text prior to the start point.

**Comment by Snuffleupagus** [comment]
Since this issue contains no specific test-case, meaning that it will be difficult to know if/when it's actually fixed, I'm closing this as duplicate of [many existing text selection issues](https://github.com/mozilla/pdf.js/labels/4-text-selection).
