### ISSUE TITLE
This file is not rendered correctly by Firefox (black and white areas left sometimes).

### ISSUE THREAD

**Issue by aleksejrs** [mozilla/pdf.js#3208]
https://bug767299.bugzilla.mozilla.org/attachment.cgi?id=745378

2013-05-06-03-09-25-mozilla-central-firefox-23.0a1.ru.linux-x86_64

**Comment by Snuffleupagus** [comment]
> I can also reproduce this using Arch Linux, Firefox 26.0 and the latest PDF.js development version.

@timvandermeij Can you still reproduce this (old) issue?

**Comment by timvandermeij** [comment]
No, all files mentioned here and on Bugzilla now work, so we can close this.
