### ISSUE TITLE
Colour in pdf not rendered

### ISSUE THREAD

**Issue by githubuser2012** [mozilla/pdf.js#3226]
Fig. 1 in http://arxiv.org/pdf/0705.4298.pdf is not displayed properly in PDF Viewer 0.8.1

**Comment by Rob--W** [comment]
Note: "not displayed properly" = the image on the first page has no colors.

![invalid-pic](https://cloud.githubusercontent.com/assets/1365071/10263516/8541e318-69f1-11e5-9f90-ed74f28fed07.png)
