### ISSUE TITLE
firefox freezes and must be killed externally

### ISSUE THREAD

**Issue by Blargher** [mozilla/pdf.js#3234]
Visit www.maths.nuigalway.ie/~destrade/publications/destrade_c11.pdf
Firefox will freeze, but it won't recognize that it's frozen.

**Comment by fkaelberer** [comment]
Works for me under Windows 7 in Firefox 37, Chrome 41, and IE11 (even though Yury's test case in [bug 870640](https://bugzilla.mozilla.org/show_bug.cgi?id=870640) still crashes IE11, but not the other browsers).

**Comment by timvandermeij** [comment]
Yes, this has indeed been fixed in Firefox 37. I cannot reproduce this anymore. Closing as resolved.
