### ISSUE TITLE
3d PDF support

### ISSUE THREAD

**Issue by johnyf** [mozilla/pdf.js#3254]
It would be nice to have 3d interactive object support in this viewer:
http://www.3dpdfconsortium.org/

As of now incorporating this feature would make it (apparently) the first open source PDF viewer to render 3d pdf graphics.
Currently only Adobe Acrobat and some proprietary viewers only support 3d viewing capabilities, which severely limits use of 3d content (coupled with the relatively involved ways of incorporating 3d content via non-proprietary methods).

Moreover, if pdf.js provided this capability, it would allow standalone websites (i.e., irrespective of browser/system) to display 3d PDF content, platfrom-independently.

Some related links may be of interest:
http://vcg.isti.cnr.it/~cignoni/newvcglib/html/
http://threejs.org/

**Comment by jimbowatusi** [comment]
I was excited to see this as an open issue.  Has there been any movement on it?

**Comment by timvandermeij** [comment]
Not yet. This is a very complicated and not frequently used feature, so I doubt it will be implemented soon. However, anyone willing to work on this is invited to submit a PR.

**Comment by Huespal** [comment]
More than year has passed. News about this? I'm waiting for this to be a reality on the web. Big cloud companies are not rendering 3D PDF's in browsers and I can not understand why.

**Comment by yurydelendik** [comment]
> I can not understand why.

I mentioned above 3D part is not part of PDF32000 specification, but defined in different specification http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-363%204th%20Edition.pdf . The market is small for this feature, but we will be glad to consider integrating a plugin or some external library that will render U3D (that PDF.js can extract from a PDF) into generic demo viewer.

**Comment by yurydelendik** [comment]
Somebody want's to try https://github.com/Lorti/webgl-3d-model-viewer-using-three.js ?

**Comment by stealth1024** [comment]
> Somebody want's to try https://github.com/Lorti/webgl-3d-model-viewer-using-three.js ?
It is very different but NOT an answer to this issue. I have used three.js, it is based on the latest WebGL technology and good for .obj/.stl files, but the 3D model here is embedded into a pdf file and the format is no opened.

**Comment by Lang-Zh** [comment]
渴望实现3d渲染

**Comment by Snuffleupagus** [comment]
As mentioned above, see e.g. https://github.com/mozilla/pdf.js/issues/3254#issuecomment-330267767, this isn't actually part of the PDF specification and it also seems to be a somewhat of a niche feature still; all-in-all this seems unlikely to be implemented in PDF.js and thus WONTFIX is probably appropriate here.

**Comment by johnyf** [comment]
In case it is decided at a future time to implement this functionality, then this issue could be reopened.

**Comment by hybridherbst** [comment]
It seems there has been some movement in the 3D PDF space lately; ISO/TS 32007:2024 (https://www.iso.org/standard/45880.html) added glTF support in late 2024, which seems to be supported by Foxit Reader but not yet by Acrobat Reader. 

glTF is a much more web-friendly format than U3D or PRC (with many implementations available, e.g. three.js).
I was not able to find an example PDF with embedded glTF content though so far.
