### ISSUE TITLE
Missing char on IE9/10 on Windows 7/8

### ISSUE THREAD

**Issue by ofirdev** [mozilla/pdf.js#3270]
The symbol marked in red is missing in IE9 and IE10 on Windows 7 and Windows 8 with pdf.js HEAD.
On FF 21 it works fine.

File:
https://docs.google.com/file/d/0B0odzw1WMqkGSkVFRFBsaGstT1k/edit?usp=sharing

Good:
![good](https://f.cloud.github.com/assets/2394904/519109/47155588-bf0e-11e2-8fd2-882ec30422ec.png)

Bad:
![bad](https://f.cloud.github.com/assets/2394904/519110/4bfc5056-bf0e-11e2-9372-560304219912.png)

**Comment by timvandermeij** [comment]
Closing since IE9 and IE10 are no longer supported since PDF.js 2.0.
