### ISSUE TITLE
No text selection possible and sporadically blank (especially on first page)

### ISSUE THREAD

**Issue by ole1986** [mozilla/pdf.js#3400]
Hi,

I found this PDF which makes troubles in reading the font properly to provide text selection.

Also it sometime shows me a blank canvas.

Here is the pdf: http://ge.tt/4uce8Ok/v/0?c

EDIT: I tried it with different devices and browers:

- Safari on iPhone 6.X show blank page, no text selection
- Chrome on Android 4.2 shows blank (but the image is partly display) on al pages
- Native Browser on Android 4,2 works just fine, but no selection of text
- Chrome on iPhone 6.X show blank page(s) and text selection failed

- Chrome on a Desktop computer works just fine, but not selection
- Internet Explorer 10 on Desktop computer failed with blank pages

**Comment by timvandermeij** [comment]
Text selection is now working for me (perhaps after #3360 has been fixed, but maybe it was unrelated) and I don't get any blank pages. Closing as fixed.
