### ISSUE TITLE
Differences between the viewer and the printed file.

### ISSUE THREAD

**Issue by MajinOwy** [mozilla/pdf.js#3418]
Hello.
My name is Ovidiu , I'm a web developer and I'm working on an application that open pdf files in firefox viewer and I found this problem.
In viewer the document looks perfect but if I try to print that file the bottom of the document is cut, it does not print the all document. And that is available for every pdf document that is print with firefox viewer. 
( The view of the document is perfect but the printing version is not.  I added two photos with the problem.)
Are you aware of this problem ? Is something that I can do or is a viewer problem ?
Thank you.
![printing_document](https://f.cloud.github.com/assets/2499453/727262/c740f1cc-e182-11e2-9cbd-33646c2ece06.png)
![firefox_pdf_viewer](https://f.cloud.github.com/assets/2499453/727261/c7425936-e182-11e2-8fa1-dc535c5b6398.png)

**Comment by yurydelendik** [comment]
The workaround is sufficient for most of the users. There is nothing a web page can do to control or query information about printed page size. Closing as won't fix for now.
