### ISSUE TITLE
Warning: fontRes not available

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#3452]
https://401k.fidelity.com/static/dcl/shared/documents/WPS_PublicSite/Documents/403b_DistributionForm_441802.pdf

Firefox 22 (HWA on), Windows 7 x64, pdf.js development

This is also a testcase for AcroForms/JavaScript problems.

**Comment by fbender** [comment]
The mentioned issue was fixed by #4716. The warning in the mentioned PDF still persists, though.

**Comment by timvandermeij** [comment]
I'm not sure if it's a bad thing or not. Maybe @yurydelendik, @brendandahl or @Snuffleupagus can say more about this. I do not know much about the font stuff myself unfortunately.

**Comment by brendandahl** [comment]
The pdf uses some fonts that aren't embedded, which is bad on the  PDF's side.

**Comment by fbender** [comment]
Would it be a good idea to display a message to the user saying the PDF may be broken?

**Comment by timvandermeij** [comment]
Closing since the warning is only an indicator of non-embedded fonts, which is something we cannot do anything about.
