### ISSUE TITLE
Security: Ignores protection from Copy

### ISSUE THREAD

**Issue by mkasson** [mozilla/pdf.js#3471]
Documents generated with FPDF with security (namely protection against copy - I haven't check print, password or other protections) not working.

Here is a script from the FPDF website which containts a link to its output.
http://www.fpdf.org/en/script/script37.php

The protection works on Acrobat Reader 8.\* in Win Vista

I am using FF 22.

Thanks

**Comment by Snuffleupagus** [comment]
Fixed by PR #11789.
