### ISSUE TITLE
Unable to cancel a transfer

### ISSUE THREAD

**Issue by RyanEdwardHall** [mozilla/pdf.js#3485]
Currently the PDFJS.getDocument function does not expose a way to cancel the transfer. Trying to reject the promise results in an error message: Warning: Unhandled rejection: (error message).

**Comment by Kureev** [comment]
**up**. What about to merge #5629, @yurydelendik ?

**Comment by rauchg** [comment]
@domenic another datapoint for the cancellation of async work discussion

**Comment by domenic** [comment]
Work is ongoing!

**Comment by rauchg** [comment]
😍

**Comment by Kureev** [comment]
Awesome! Do you have any ETA, @domenic ?

**Comment by domenic** [comment]
We'd really like to do this soon ... I'd measure it in not-too-many-more Chrome releases.

**Comment by Kureev** [comment]
@domenic Thank you for your feedback! Looking forward for it!

**Comment by yurydelendik** [comment]
#6546 introduces `PDFDocumentLoadingTask.destroy()` which terminates worker and all I/O operations. Closing as fixed.

**Comment by JurisTechsys** [comment]
> This won't work in my case because the PDFDocumentProxy object is returned after the getDocument promise is resolved, and the promise only resolves after the transfer finishes:
> 
> ```js
> PDFJS.getDocument(url).then(function getDocumentCallback(pdfDoc) {
>         //transfer already complete
>         pdfDoc.destroy() //this would be happening too late
>         renderPage(page);
>     })
> ```
> 
> It would be nice if we could do something like:
> 
> ```js
> PDFJS.abortAllTransfers();
> ```

its works
