### ISSUE TITLE
Check if b2g viewer can use shared l10n.js

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#3518]
Started as https://bugzilla.mozilla.org/show_bug.cgi?id=898408 "[Next] and [Previous] button cannot work on PDF Viewer". The fix requires disabling optimization for PDF viewer: https://github.com/mozilla-b2g/gaia/pull/11201

```
<kaze> https://bugzilla.mozilla.org/show_bug.cgi?id=853933
<firebot> Bug 853933 nor, --, ---, kaze, RESO FIXED, Don't inline all locales as JSON in the HTML
<yury> so it's not using .properties files?
<kaze> .properties files are compiled to JSON and inlined in the HTML document, yes
<kaze> the point is to avoid XHR calls
```

**Comment by timvandermeij** [comment]
Closing as the B2G viewer is no longer used. It will be moved to the examples where it will serve as a basic (not feature-complete) example, so the complexity of L10n is not wished anymore compared to when it was used as an actual extension.
