### ISSUE TITLE
Reader shows Polish fonts but doesn't print them.

### ISSUE THREAD

**Issue by rafcio21** [mozilla/pdf.js#3531]
My example:
http://nawra.wysylaj.net/kartapdf2.php?page=karta&szczegoly=sprzedaz&rynek=wtorny&gdzie=poznan&cena=&wybrane=&ktora=2&ileofe=12&id=1888&print=true

When I click print then it print it without polish ąężź etc.

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs.
