### ISSUE TITLE
PDF.js not working on IE10

### ISSUE THREAD

**Issue by eloivis** [mozilla/pdf.js#3638]
The PDF's text is broken on IE10.
I have used a meta tag - &lt;meta http-equiv="X-UA-Compatible" content="IE=edge" /&gt;.

Those are fine on Chrome, Firefox, and Safari.

http://cosmopolitan.joins.com/e-Magazine/Campus/Web/viewer.html

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.
