### ISSUE TITLE
Cascaded image

### ISSUE THREAD

**Issue by kkujala** [mozilla/pdf.js#3679]
This is interesting. pdf: https://github.com/mozilla/pdf.js/blob/master/test/pdfs/issue3458.pdf

Before the #3506 fix the image is upside-down and somehow cascaded, see http://postimg.org/image/ns507atmh/
With the fix the image is the correct side up but differently cascaded, see http://postimg.org/image/hbobh5dml/
Reference with Adobe, see http://postimg.org/image/ixornpfmt/

I have Windows 7, hwa on, Aurora 25.0a2.

Apparently on OSX it looks fine.

**Comment by timvandermeij** [comment]
Closing as fixed as this renders as it should now.
