### ISSUE TITLE
Scanned page is blank on Chrome when zooming

### ISSUE THREAD

**Issue by ofirdev** [mozilla/pdf.js#3681]
When I'm using 90% zoom and above in the viewer on Chrome, the page turns blank.
On FF and IE it works fine.
https://docs.google.com/file/d/0B0odzw1WMqkGRjVtc2RUWTBLQ2s/edit?usp=sharing

Skia, has a limit on the number of pixels in a canvas but I don't think that's the issue: https://code.google.com/p/chromium/issues/detail?id=253788&q=canvas%20wide&sort=-modified&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

Tested with
commit 4f243b39b4f998db396eb83ad6a386e4c99cb61c
Chrome 29.0.1547.66 m
Windows 7
FF 23.0.1

**Comment by timvandermeij** [comment]
Closing since we've had no more reports for this and the Chrome version reported is now unsupported.
