### ISSUE TITLE
UI of localized (non-English) viewer looks partially broken

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#3683]
When I open a small viewer with a Dutch locale (nl), the zoom controls partially collide with the page number, because "Pagina X van Y" is wider than "Page X of Y" (the UI is designed for the latter). For example, shrink your window and visit http://107.22.172.223:8877/1c358b0bbaf719b/web/viewer.html#locale=nl (this version of the viewer is based on #3671, which fixed the layout issue for the default locale, en-US):

![overlap](https://f.cloud.github.com/assets/1365071/1138259/1b44f97e-1c72-11e3-86a0-560c1dafa2e4.png)

The positions should not be hard-coded, to solve the problem.

I guess that the secondary toolbar is also affected by this issue (it has a hard-coded max-width of 200px).

**Comment by timvandermeij** [comment]
I just found out that there is also https://people.mozilla.org/~shorlander/files/PDFjs-ui-prototype/pdfjs-ui-demo-i01.html which has the [X] / Y view we talked about here.

**Comment by timvandermeij** [comment]
As seen in #6262, this can also happen if the number of pages is large. In fact, I think all of these issues can be resolved at once if we tweak the current responsiveness as described in https://github.com/mozilla/pdf.js/issues/6191#issuecomment-124248289.

**Comment by yurydelendik** [comment]
Still an issue?

**Comment by Rob--W** [comment]
Yes it is. Set the language to Dutch (`LANG=nl_NL.UTF8`) and resize the viewer. Then the minus button will overlap the page number as shown in the screenshot.

**Comment by timvandermeij** [comment]
I can confirm that this is still an issue, at least with the Dutch locale but most likely also with other languages.

**Comment by timvandermeij** [comment]
Pull request #6945 improved this a bit and makes it easier to make the viewer more responsive. However, we're not quite there yet, so this issue remains open to track the remaining issues.
