### ISSUE TITLE
Missing font glyphs

### ISSUE THREAD

**Issue by rauchg** [mozilla/pdf.js#3694]
Got:

![image](https://f.cloud.github.com/assets/13041/1143990/07737e42-1d68-11e3-9a39-69a16203ebc7.png)

Expected:

![image](https://f.cloud.github.com/assets/13041/1143991/10aef00e-1d68-11e3-9c71-cd3b5ffd5da3.png)

Chrome Version 29.0.1547.65
File: https://i.cloudup.com/oG1S4DIPAa.pdf

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6724.
