### ISSUE TITLE
Support touch events

### ISSUE THREAD

**Issue by vyv03354** [mozilla/pdf.js#3765]
Currently pdf.js is disabled on Metrofox due to the lack of the touch support.
https://bugzilla.mozilla.org/show_bug.cgi?id=859579

**Comment by MickL** [comment]
Any news on this? Especially pinch to zoom? (The PR is closed btw)

**Comment by Snuffleupagus** [comment]
> Currently pdf.js is disabled on Metrofox due to the lack of the touch support.

Given that "Metrofox" is no longer a thing, and that touch-zooming is already tracked elsewhere; let's close this as a duplicate of issue #2582 instead.
