### ISSUE TITLE
Text segments position around special symbols is not correct

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#3773]
Text segments position around special symbols (like integral symbols, sum symbols, and big parenthesis, etc.) is not correct. It seems like symbols are drawn below what PDF.js sees as position of symbols. See
![attached image](https://f.cloud.github.com/assets/585279/1274497/677e6ab2-2da9-11e3-8464-c15ecbc6b10d.png)

Example PDF (best seen on the second page): http://arxiv.org/pdf/0704.0006v1.pdf

You can just try to use text selection and you will see where divs are.

**Comment by timvandermeij** [comment]
This is rendering even better than Adobe Reader does for me now, so I'm closing this as fixed.
