### ISSUE TITLE
PDF.js is not compatible with LibreJS

### ISSUE THREAD

**Issue by hpr** [mozilla/pdf.js#3775]
Being that pdf.js is free software, it would be in the best interests of the pdf.js team to tag the licenses of all Javascript files part of the project in a way that computers can read and confirm that users are in fact allowed to change the code. A practical implication of this is that pdf.js will no longer be blocked by the LibreJS browser addon.

For an example of how this has been done in a similar web application, see https://github.com/ether/etherpad-lite/pull/1066. For instructions by the LibreJS team, see http://www.gnu.org/software/librejs/free-your-javascript.html.

**Comment by meShakti** [comment]
Hi I am new to the project and would like to contribute to it .Please guide me as to which method to use javascript web labels or by other methods like 
http://www.gnu.org/software/librejs/free-your-javascript.html#magnet-link-license

**Comment by yurydelendik** [comment]
Use `/* */`.

Please notice that this tags shall be present only in built pdf.js libraries, since source code from src/ and web/ is preprocessed and shall not be distributed as is. See https://github.com/mozilla/pdfjs-dist

**Comment by axxonn** [comment]
Is anyone still working on this?

**Comment by timvandermeij** [comment]
No, anyone who is willing to work on this can do so.

**Comment by yurydelendik** [comment]
Most of the files in the src/ and web/ does not need to be changed since they are combined into bigger files (in the build/* folders), so only the files that are main files need to be changed:

  - src/pdf.js
  - web/pdf_page_view.js
  - web/compatibility.js
  - web/viewer.js (?)
  - external/l10n.js (?)
  - TDB

Also since we remove licenses from the middle of the file, we need to add third-party licenses to these "main" files of the files they include. (see make.js's stripCommentHeaders)

**Comment by prometheansacrifice** [comment]
@yurydelendik The following can collect all third party license headers during the build

```
function collect3rdPartyLicenses(content, filename) {
  var thirdPartyLicenses = [];
  var notEndOfComment = '(?:[^*]|\\*(?!/))+';
  var reg = new RegExp(
      '(\n*/\\* Copyright .... (?!Mozilla Foundation)' +
          notEndOfComment + '\\*/\\s*)' +
          '', 'g');
  thirdPartyLicenses = content.match(reg);
  return thirdPartyLicenses;
}
```

**Comment by timvandermeij** [comment]
It's not entirely clear yet what the best way is to implement this. Feel free to join us on #pdfjs on irc.mozilla.org so we can discuss this.

**Comment by himanish-star** [comment]
@timvandermeij , Has this issue already been resolved or is someone working on this? If no one is working on this then I would surely like to work on this

**Comment by timvandermeij** [comment]
It's yours! Feel free to contact us on IRC if you have questions.

**Comment by himanish-star** [comment]
@timvandermeij , the link [irc.mozilla.org](irc.mozilla.org) doesn't open. I searched for list of mozilla irc channels in [https://wiki.mozilla.org/IRC](https://wiki.mozilla.org/IRC) but there are a number of irc channels. So which one should i join to ask my doubts on pdf.js

**Comment by timvandermeij** [comment]
You should use a client like HexChat or Quassel to connect to `irc.mozilla.org`. Once connected, you can join `#pdfjs`.

**Comment by himanish-star** [comment]
Thanks for helping @timvandermeij
