### ISSUE TITLE
Ctrl + P results in two print dialogs in IE11+

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#3784]
We intercept <kbd>Ctrl</kbd> + <kbd>P</kbd> in order to render all pages before sending a print job. All modern browsers (Firefox, Chrome, Safari and Opera) respect `event.preventDefault();`, and do not show the print dialog.

Internet Explorer, on the other hand, just continues to show the print dialog regardless of whether `event.preventDefault();` was called. With `attachEvent`, it was possible to cancel the event anyway (see https://github.com/mozilla/pdf.js/blob/1731c0fb/web/mozPrintCallback_polyfill.js#L120-L128), but IE11 has dropped support for `attachEvent`.

As far as I know, there is no other way to prevent the default behavior of Ctrl + P in Internet Explorer from happening, so we have the issue that the print dialog is triggered **twice** in Internet Explorer 11 (once for Ctrl + P, once when all pages have finished rendering).

I've created this ticket to track this issue, in case someone discovers a viable work-around.

**Comment by loueradun** [comment]
This was unacceptable behavior so I had to do something to resolve this problem.  I found 3 solutions, none of which are ideal, but wanted to include my findings in case it helps someone or can provide some insight as to how this issue can be resolved.

All 3 solutions require inserting the code after the window.print in the keydown function for Ctrl+P

Solution 1:
```
var ie11fixwindow = window.open('_blank', 'test', 'toolbar=no,status=no,width=1,height=1');
ie11fixwindow.close();
```

Solution 2:

`window.alert('Printing Initiated');`

Solution 3:
```
while (new Date().getTime() < now + 4000) {
	var progressContainer = document.getElementById('mozPrintCallback-shim');
	progressContainer.removeAttribute('hidden');
}
```

All of these have their own issues, but I ended up going with the window.open fix.  This really needs to get fixed, it has been almost 3 years.  I think it could be resolved by building the canvas before returning from the keydown method, but that is a huge re-write of the printing code.

**Comment by timvandermeij** [comment]
I think this should be reported upstream as we do not wish to include such hacks, especially if it is only for IE.

**Comment by loueradun** [comment]
While I agree all these hacks are not good candidates to be included in a release, it is useful to note that the way IE11 works in cancelling the Ctrl+P event varies based on the time taken to complete the keydown event or if the browser window loses focus momentarily.

If printing in IE11 is an absolute must for your implementation of pdf.js, something like the alert or window.open hack may be a viable option for you.

@timvandermeij Is there somewhere else I should report my findings upstream?  I thought that was what I was doing here.

**Comment by yurydelendik** [comment]
> Is there somewhere else I should report my findings upstream? 

Opening this issue is enough to report the findings. Also, opening an issue at http://connect.microsoft.com/IE is preferable since it only affects IE.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
