### ISSUE TITLE
Annotations incorrectly flipped

### ISSUE THREAD

**Issue by mahelious** [mozilla/pdf.js#3826]
[original pdf file](https://dl.dropboxusercontent.com/u/62819916/Poll%20of%20the%20Day%20-%20How%20do%20you%20feel%20when%20a%20game%20you%27re%20anxiously%20waiting%20for%20gets%20delayed_%20-%20GameFAQs.pdf)
[annotated pdf file](https://dl.dropboxusercontent.com/u/62819916/Mole_Man_Exhibit_15.pdf)

After saving a web page to PDF in Chrome (v30.0.1599.101 m), any annotations made show up as "flipped" in pdfjs.  However they appear correctly in Foxit and Adobe Reader XI.  I have included both the original document as Chrome produced it, as well as the version after saving annotations in Foxit, and screenshots of the annotations as they appear in Reader and pdfjs.  Note that annotations saved by Foxit to PDF files generally render correctly in pdfjs, only pdf files produced by Chrome seem to exhibit this behavior.

Annotated document rendered in Reader
![reader_correct_80](https://f.cloud.github.com/assets/4097440/1356722/721fd0da-377e-11e3-89a5-7804cb4c7c20.png)
Annotated document rendered in Reader (zoomed)
![reader_correct_100](https://f.cloud.github.com/assets/4097440/1356723/722231f4-377e-11e3-86d0-dccad7e88c9f.png)
Annotated document rendered in pdf.js
![pdfjs_incorrect_60](https://f.cloud.github.com/assets/4097440/1356720/72134dd8-377e-11e3-90a2-aea9236e6a4c.png)
Annotated document rendered in pdf.js (zoomed)
![pdfjs_incorrect_100](https://f.cloud.github.com/assets/4097440/1356721/7214e102-377e-11e3-959e-b33dc724ff43.png)

**Comment by hjalet** [comment]
Hi,

We are experiencing the same issue with rotated annotations. Any chance this issue will be fixed or does any work around exist?

**Comment by THausherr** [comment]
Possibly related to #5946.
