### ISSUE TITLE
Various musical symbols get cut off when hardware acceleration is off

### ISSUE THREAD

**Issue by mikemorr** [mozilla/pdf.js#3876]
When hardware acceleration is off, sheet music dynamic markings (e.g. p and f for piano and forte) have part of their descenders cut off. Example here: http://mikemorr.com/dynamics.pdf

Screenshot from http://mozilla.github.io/pdf.js/web/viewer.html showing the problem:
![dynamics-incorrect](https://f.cloud.github.com/assets/2184268/829734/48eb939e-f0fb-11e2-931d-50e0b808c482.PNG)
Screenshot from SumatraPDF showing correct appearance:
![dynamics-correct](https://f.cloud.github.com/assets/2184268/829735/4f0db464-f0fb-11e2-98b9-58f66a84bc9c.PNG)
See #3349 for my configuration (HWA is off).

**Comment by mikemorr** [comment]
Another example, showing that the dots and wings on repeat barlines are also cut off: http://mikemorr.com/Repeats.pdf
Screenshots from SumatraPDF and http://mozilla.github.io/pdf.js/web/viewer.html (with cut-off parts outlined in red by me):
![sumatrarepeats](https://cloud.githubusercontent.com/assets/2184268/6201051/c62373f0-b462-11e4-9781-d40b1437e3f0.PNG)
![pdfjsrepeats](https://cloud.githubusercontent.com/assets/2184268/6201052/c86154c0-b462-11e4-998e-5cb2efbabc77.PNG)

**Comment by Snuffleupagus** [comment]
WFM, when testing[1] in Firefox Nightly 91.0a1 (2021-06-27) (64-bit) running on Windows 7.

---
[1] By toggling the "Use hardware acceleration when available" checkbox to *off* and restarting the browser.
