### ISSUE TITLE
Pdf doesn't render appropriately

### ISSUE THREAD

**Issue by SunilAgrawal** [mozilla/pdf.js#3946]
I am using the latest PDF.js available along with Firefox 26 and it fails to render the PDF located at https://drive.google.com/file/d/0B0crLpIS-8COTUl1SUc0M2RlT28/edit?usp=sharing appropriately.

The colors are missing.

**Comment by timvandermeij** [comment]
The link to the PDF file is dead. Please provide a new link to reopen the issue.

**Comment by Snuffleupagus** [comment]
It actually looks like this was fixed by PR #6684.
