### ISSUE TITLE
incorrect rendering / no "rendering is incorrect" warning

### ISSUE THREAD

**Issue by kunom** [mozilla/pdf.js#3988]
http://stadtmusik-sursee.ch/phocadownload/2013_Chlausmaeaert/2013_Chlausmaert_A5.pdf

web console output (FF 26 Beta 8):

Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:58
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:73
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:81
12:33:58.724 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:89
12:33:58.725 Unknown property 'box-sizing'.  Declaration dropped. viewer.css:822
12:33:58.725 Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:1225
12:33:59.157 "PDF cc0a252e7914bab8c28dce9e963f31 1.6 Adobe PDF Library 10.0.1 / Adobe InDesign CC (Macintosh) (PDF.js: 0.8.751)"

**Comment by Snuffleupagus** [comment]
Probably the same issue as #6130.

**Comment by Snuffleupagus** [comment]
> http://stadtmusik-sursee.ch/phocadownload/2013_Chlausmaeaert/2013_Chlausmaert_A5.pdf

Since the link appears to be dead now, I'm attaching the file here: [issue3988.pdf](https://github.com/mozilla/pdf.js/files/1431954/issue3988.pdf).
