### ISSUE TITLE
Image rendering & font rendering issue's at print time

### ISSUE THREAD

**Issue by jonwilks** [mozilla/pdf.js#3992]
Road to the issue...

1. Issue #3969 is created
2. Pull request #3978 is then triggered (fixing #3969 )
3. This issue is created  

//Problem
During a regression test of my production PDF's following #3978 I noticed image rendering issues on the printed medium. The rendered preview looks fine. My print sequence is triggered by javascript auto-print sequence, which PDF.js parses and issues its own command. I have attached a PDF via dropbox named "Image_Font_Issue_Printed_Scans.pdf" that contains for printed scans. Each of which contains a description of the problem at the bottom of the page in Red. 

I was able to create a new test pdf for the purposes of reproduction of the problem. This is more similar to my production PDF. It is named "pdfjs_test_label.pdf"

//Artifacts located here:
https://www.dropbox.com/sh/m845ygimsbgelfz/D_Bl6eYkzC

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs.
