### ISSUE TITLE
Text layer slightly broken

### ISSUE THREAD

**Issue by piotrex** [mozilla/pdf.js#4002]
Go to page 3 in https://dl.dropboxusercontent.com/s/i23vgfe4bdevern/Lab_el_tranzystory.pdf 
It doesn't seem that the pdf is broken though.

Console messages:

12:58:21.482 "PDF fa5c2c847f6dc574f118482c939bec3f [1.3 Acrobat Distiller 5.0 (Windows) / PScript5.dll Version 5.2.2] (PDF.js: 0.8.759)" viewer.js:2601
12:58:28.574 "Warning: TT: complementing a missing function tail" pdf.js:198

Win7 64-bit, last pdf.js development version

**Comment by timvandermeij** [comment]
Closing as fixed in the latest development version of PDF.js. Text selection is now equivalent to that of other PDF readers.
