### ISSUE TITLE
SVG Pattern not loaded in PDF Viewer: it shows a spinner

### ISSUE THREAD

**Issue by mirelvt** [mozilla/pdf.js#4063]
I created an html file with an svg that contains a pattern, and use PrinceXML to generate the PDF. The svg is displayed correct in other PDF viewers, except in Firefox PDF Viewer. There, it shows a spinner instead.

Example code:

    <defs>
        <pattern id="grid" width="600" height="25" 
                patternUnits="userSpaceOnUse" x="0" y="204">
            <line x1="0" y1="0"  x2="600" y2="0" class="grid-lines" />
        </pattern>
    </defs>

    <svg width="600" height="204" viewBox="0 0 600 204">
        <rect class="background-grid" x="55" y="0" width="545" height="204" fill="url(#grid)" /> 
    </svg>

The grid lines are defined in the css.

You can download the complete example from https://github.com/mirelvt/pdf-issue

**Comment by Snuffleupagus** [comment]
> I don't know which grid pattern I'm supposed to see, but PDF.js and Adobe Reader only show grid lines. Those lines are more clear in Adobe Reader and are indeed barely visible in PDF.js.

Fixed by PR #4615, closing as worksforme (using PDF.js version 1.0.1143).
