### ISSUE TITLE
JPEG error: marker was not found

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#4090]
https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

```
"PDF d0331af6364b4637a61316757c264737 [1.6 PDFlib Personalization Server 7.0.0p3 (C++/Win32) / Rampage PDF PageAssembly] (PDF.js: 0.8.827)" viewer.js:2897
"Error: JPEG error: marker was not found" pdf.worker.js:216
"JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:32948\nDecodeStream_getBytes@resource://pdf.js/build/pdf.worker.js:32246\nPDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:28437\nPDFImage_fillRgbaBuffer@resource://pdf.js/build/pdf.worker.js:28369\nPDFImage_getImageData@resource://pdf.js/build/pdf.worker.js:28432\nPartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:14618\nPDFImage_buildImage/<@resource://pdf.js/build/pdf.worker.js:28085\n" pdf.worker.js:218
"Warning: Unsupported feature \"unknown\""
```

**Comment by joopeed** [comment]
Similar bug on version 52.0.2 not solved yet:
Warning: Unable to decode image: Error: JPEG error: marker was not found  pdf.worker.js:2965:6
Warning: Dependent image isn't ready yet  pdf.js:265:6
Error: JPEG error: marker was not found  pdf.worker.js:2973:6
decodeScan@resource://pdf.js/build/pdf.worker.js:13800:8
parse@resource://pdf.js/build/pdf.worker.js:14162:25
JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:23708:6

**Comment by yurydelendik** [comment]
@joopeed can you confirm that https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf produces the error you mentioned above?

**Comment by joopeed** [comment]
No, this PDF doesn't produce this error. The PDF which procuces this error contains sensetive information.

**Comment by yurydelendik** [comment]
> The PDF which produces this error contains sensetive information.

@joopeed  We cannot address the issue and we cannot reproduce it. Please stop spamming unrelated issues. I recommend to create your issue and to attempt to created PDF without sensitive information.

**Comment by doront99** [comment]
Hi,
I have the same problem. I have noticed that this problem occures mainly on pdf produced from Samsung printers.

here is a link to a file:
https://drive.google.com/open?id=0By6fVX-F2s1xbGEyeG4xNldKbkNDQ1l1UHFkcXdQZFZ2MXM0

if you need more files, please ask.

Can we re-open the bug?

Thanks,
Doron

**Comment by doront99** [comment]
Thanks,
I havn't notice.
It does work with the latest version.

Doron

**Comment by theinhtunthein** [comment]
myanmar

**Comment by Uruselfei** [comment]
Hi,
I still have this error in IE. Tried both latest stable and beta versions - IE shows all, except embedded image. Chrome shows everything correctly.
I could send my PDF sample to somebody for investigation. Publishing for all - net very good idea, since it contains some sensitive information.
