### ISSUE TITLE
Pdf Stamp not visible

### ISSUE THREAD

**Issue by tiarossi** [mozilla/pdf.js#4123]
In some situations the stamp attached to the pdf document is not shown by pdfjs as expected.

This happens with the following file: https://drive.google.com/file/d/0B4lYWKfSQThlMGJOUjZKLVl1aWc/edit?usp=sharing

The file is displayed normally by adobe.

![image](https://f.cloud.github.com/assets/477378/1912390/6d6c5f3a-7d39-11e3-82cb-97efbc50cf0d.png)

**Comment by timvandermeij** [comment]
Closing as fixed by #6814.
