### ISSUE TITLE
Crashing Chrome and stalling Netscape with large (200MB) image-heavy PDF

### ISSUE THREAD

**Issue by mjoblin** [mozilla/pdf.js#4155]
I'm experiencing problems loading large image-heavy PDFs.  Chrome tabs will crash ("Aw, Snap!"); and Netscape tabs will stall (refusing to load the new PDF, and unviewed pages in the previously-viewed PDF get stuck on the spinning loading icon).  I'm experiencing this in the current web viewer (PDF.js 0.8.909):

 http://mozilla.github.io/pdf.js/web/viewer.html

Given the size of the PDFs (over 200MB) it's probably no surprise there can be some memory problems.

The reference PDF I'm using is this one:

 http://paintingaportraitbydelaszlo.files.wordpress.com/2014/01/paintingaportrait.pdf

The process to reproduce the problem can be a little contrived (especially on OSX), but it's actually not uncommon behaviour in the context in which I'm using PDF.js (browsing lots of large image-heavy PDFs).  It's definitely worse on Windows 7 (in a VM) than OSX.  I haven't been able to test it on an actual non-VM'd Windows 7 machine.

To reproduce the problem I:
1. Create two copies of the above PDF.
2. Go to the web viewer.
3. Load the first copy of the PDF into the viewer.
4. Immediately load the second copy of the PDF into the viewer.
5. Repeat steps 3 & 4 until the crash/stall happens.

Here's what I've noticed in different environments:

Windows 7 VirtualBox VM (4GB), running under OSX:
- Chrome 32.0.1700.76 m: "Aw, Snap!" after first load.
- Firefox 26: Displays OK first time; stalls on second or third load.

OSX 10.9.1, 8GB:
- Chrome 32.0.1700.77: "Aw, Snap!" after rapidly cycling through steps 3 & 4 above about 20 times.
- Firefox 26: Cannot reproduce (RAM peaks at around 2.5GB).
- Safari 7.0.1: Cannot reproduce (RAM peaks around 2GB).

When the Firefox tab stalls I see the following in the console:

uncaught exception: out of memory
TypeError: this.pdfDocument is null
   return this.pdfDocument.getPage(n);

In Chrome the tab crashes without anything being displayed in the console.

Given that it appears to be an out of memory problem I don't know if there's anything that can be done, but I wanted to mention it just in case.

Thanks!

**Comment by timvandermeij** [comment]
Closing since this works fine for me now. Note that there have been many performance improvements since this issue was filed (for example fetch API usage and drawing optimizations).
