### ISSUE TITLE
PDF doesn't render

### ISSUE THREAD

**Issue by anjiro** [mozilla/pdf.js#4174]
pdf.js version 0.8.1

http://www-personal.umich.edu/~pvbuelow/publication/pdf/vonBuelow07_SDPS.pdf

JS Console:

10:39:05.550 Error: Missing endstream pdf.js:763
10:39:05.540 "Warning: Indexing all PDF objects" pdf.js:743

**Comment by Rob--W** [comment]
This PDF is corrupted (beyond repair?). In Adobe Reader DC (2015.007.20033), page 2 is missing. In Chrome, half of page 2 is rendered. Most images in the PDF are rendered in an obviously incorrect way.

When I ignore all errors (`error = function(msg){ console.error('Would-be fatal error: ' + msg); }`)

A quick investigation: I've decompressed the stream in the PDF file that describes page 2 (object 3 0). The decompressed data looks ok until "clic manner" (shown below, starting from byte 5858). This should have been followed by a `)]TJ`, but it is not. The remaining part of the stream contains seemingly structured (PDF) data, but the text is intelligible. I guess that the compressed data became corrupted, and lead to corruption of the data. This hypothesis is supported by the fact that `zlib-flate` and `gzip` report errors when I pipe the compressed data through them.

```
[(from this pool of solutions called )-5.5(a population. One ge)]TJ
22.2404 0 TD
0.0004 Tc
0.0392 Tw
[(neration follows the nex)-7.8(t)-0.5( in a )-5.5(cy)-7.8(clic manner
20.1913 0 TD
0.000tp)66/6h(s)s \(6f solu)-7.5(tions il ea e<94>)-3.9and point resulting in a <93>bes(<94> solution is)]TJ
21.5191 0 TD
[(lces (definde. The populati)]TJ
20.7943 0 TD
0.0008 Tc
0.0497 Tw
[ionsdon co vegen in ths)7.5( )]TJ
```

Screenshot of the viewer and the console when errors are ignored:

![issue4174-page2-ignore-errors](https://cloud.githubusercontent.com/assets/1365071/8640450/6588011c-28f9-11e5-8c1b-e5b929706026.png)

Should we offer a way to ignore errors?

**Comment by timvandermeij** [comment]
No, I don't think we should. If even Adobe Reader cannot render it properly (and Adobe Reader can handle a lot without failing miserably) and there is no reasonable way to render this properly, then I think we should close this as won't-fix (or can't-fix, really).

**Comment by timvandermeij** [comment]
Closing as won't-fix. Everything we could do has been done and it renders just like Adobe Reader now (page 2 missing and images partly broken). There is nothing we can do about the remaining defects because the data is corrupted.
