### ISSUE TITLE
Image position in appendImage is not correct

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#4182]
In this PDF, image positions given in appendImage are not correct:

http://arxiv.org/abs/1204.3516

Vertically they have some strange offsets.

**Comment by ldenoue** [comment]
I found a bug in canvas.js:
https://github.com/mozilla/pdf.js/blob/30b8f4100325f3f6a55de0722e7dadf239b2cc0e/src/display/canvas.js#L1895

It should be:
var position = this.getCanvasPosition(0, -h);

Laurent.

**Comment by SamyCookie** [comment]
Thanks @ldenoue for your find. Could you open a 'pull request' for that ?

**Comment by ldenoue** [comment]
there's more to it than just passing -h.
looks like the position gets negative sometimes too.
