### ISSUE TITLE
Prints incorrectly, except when first scrolling through document in viewer OR using disableFontFace hint

### ISSUE THREAD

**Issue by fredrikhh** [mozilla/pdf.js#4215]
We use PDFs which print incorrectly in Firefox 26 (using the pdf.js based default PDF viewer) under "normal" circumstances, but print correctly when:
- user first scrolls through entire document in the viewer before printing
- we provide the #disableFontFace=true "hint" to pdf.js

This is a failed printout (unfortunately we don't have any published documents that I can link to):
![pdf_print_example](https://f.cloud.github.com/assets/4683306/2028317/4aaf2e5c-88cc-11e3-84d4-a82647221128.PNG)

I don't see any special error message in the Console when printing, though I did see the following when viewing the document:
11:02:59.919 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:56
11:02:59.919 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:71
11:02:59.919 Unknown pseudo-class or pseudo-element 'fullscreen'.  Ruleset ignored due to bad selector. viewer.css:79
11:02:59.920 Unknown property 'box-sizing'.  Declaration dropped. viewer.css:789
11:02:59.921 Unknown pseudo-class or pseudo-element 'selection'.  Ruleset ignored due to bad selector. viewer.css:1178
11:03:00.461 "PDF 177b6feba9d21ee8f77cec7e39887 [1.3 iText 4.2.0 by 1T3XT / Unknown] (PDF.js: 0.8.505)" viewer.js:2180

My own assumption is that it's a font/embedding issue in the PDFs we use manifested by a bug in pdf.js (since it's working under special circumstances, but not always). I'm just not sure how to correct the issue in the PDFs themselves (i.e. what to tell the agency that produces them).

When I look at the PDFs in Acrobat Pro, I can see that "problem pages" fail the following font-related preflight checks:
- "Glyph in subset font missing"
- "Text cannot be mapped to Unicode"
but again I'm not sure if that's related to the printing issue (or if it's related to these PDFs containing form-fields that we will with data and which prints correctly all the time). I'm also still confused by the fact that PDFs look correct in the viewer AND print correctly if you scroll through the entire document first, but fail to print correctly if you print without scrolling first.

I have tried looking for similar issues in tickets, wiki and/or find advice on producing PDFs that are compliant with pdf.js, but without much result. Any help would be appreciated.

Best regards,
Fredrik

**Comment by timvandermeij** [comment]
Closing as fixed by #7694 and other printing PRs.
