### ISSUE TITLE
Words looks weird when zoom is 100% 

### ISSUE THREAD

**Issue by AnthonyAtencio-zz** [mozilla/pdf.js#4238]
Only when using more or less than 100% zoom, letters look normal.

Link to PDF: http://iesbarriodebilbao.es/blogs/pcpi/files/2009/03/usodelacoma.pdf
[100% Zoom]
![coma](https://f.cloud.github.com/assets/6562958/2058414/c6852a3a-8b70-11e3-9426-bcd07c8bd34b.png)

[130% Zoom]
![coma130](https://f.cloud.github.com/assets/6562958/2058422/4aeaf818-8b71-11e3-92ca-0be5dd81ec1c.png)

More info:
Ubuntu 13.10 64bits
Firefox 26.0
PDF Viewer 0.8.649

**Comment by Snuffleupagus** [comment]
> The PDF does not contain embedded fonts. So documents might look different on different computers since widths of characters might not match.

Given this, I'm not sure that it's meaningful to keep this old issue open.
