### ISSUE TITLE
Gradation visualisation

### ISSUE THREAD

**Issue by romaina** [mozilla/pdf.js#4249]
PDF with graduate color display are not display properly. 

![image](https://f.cloud.github.com/assets/6012492/2087668/097a735c-8e70-11e3-9cf8-0e93b34320d7.png)

github doesn't allow to upload PDF but I can off course provide the PDF if necessary

**Comment by Snuffleupagus** [comment]
> https://ob-eu.br-docs.brother.com/share/8ec0b2a74d1da9b8e0e398d620317a4b
>
> Here is an new one : https://testing.preprod.br-docs.brother.com/share/b30a4216b7f87e9293fcf2f903d7cc84

Unfortunately none of those links work any more, and the Internet Archive doesn't have either of those file cached; given the age of this issue closing as INCOMPLETE for now.
