### ISSUE TITLE
Failure to do subpixel anti-aliasing

### ISSUE THREAD

**Issue by gcp** [mozilla/pdf.js#4252]
Continuation of https://github.com/mozilla/pdf.js/issues/2349

https://www.schneier.com/paper-twofish-paper.pdf

On Windows 8.1, current Nightly (but note original report was on Windows 7), this PDF does not get subpixel/ClearType antialiasing, only greyscale antialiasing. This makes the PDF significantly harder to read with pdf.js compared to Adobe Reader.

Adobe vs pdf.js
https://dl.dropboxusercontent.com/u/32496746/pdfbadhint.png

Zoomed in view showing lack of subpixel AA:
https://dl.dropboxusercontent.com/u/32496746/pdfbadhint2.png

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6551.
