### ISSUE TITLE
OCR Text visible because Image layer can't be loaded 

### ISSUE THREAD

**Issue by schroederp** [mozilla/pdf.js#4254]
There had been a similar issue two years ago.
In this case the image which should be shown in foreground is monochrome TIFF (TIFF G4 or CCITTFaxDecode).

http://digipool.bib-bvb.de/bvb/info/OCR_with_TIFFG4.pdf

The background OCR Text is loaded, but the image layer not. Instead I see just the small "loading ..." icon. 
See screenshot attached.
Left handside Firefox 27 and right handside IE with Adobe Plugin.
Moreover FF  keeps the CPU busy without stopping and takes about 130 MB more of user memory permanently as long as the tab with pdf is open. 
![ocr_with_tiffg4](https://f.cloud.github.com/assets/6605297/2099251/f292b62a-8f39-11e3-83e5-c8e4414df46c.jpg)

**Comment by Snuffleupagus** [comment]
Closing as WORKSFORME, using: Windows 7 (64-bit), Firefox Nightly 40 (buildID: 20150404030218) with HWA on, and PDF.js 1.1.45.
