### ISSUE TITLE
PDF file freezing Firefox

### ISSUE THREAD

**Issue by QuLogic** [mozilla/pdf.js#4265]
You probably have a lot of these, but hopefully one more test case won't hurt. The file [located here](http://comjnl.oxfordjournals.org/content/27/3/276.full.pdf) is a 2-page PDF, and appears to be comprised of one scanned image per page, with some short "downloaded from" text on the side.

When opening it in PDF.js on Firefox 27 (Fedora 20), it absolutely cripples my laptop with "only" 4G of RAM. In a controlled test, the RAM usage rose to about 50% before I decided to kill it, though it was still rising. For comparison, evince manages to get away with ~1.3% RAM usage. If I get a chance to try it on my desktop with lots more RAM, I may test it to see how high it tops out.

**Comment by QuLogic** [comment]
This seems to be working pretty alright in current Firefox; is it not fine for you?

**Comment by timvandermeij** [comment]
Yes, this was an upstream Firefox bug that has been fixed. Closing as resolved.
