### ISSUE TITLE
Add Help / Improve discoverability of shortcuts

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#4279]
Wouldn't it make sense to add the shortcut to the tooltips in the UI, or at the very least a help box within PDF.js? (triggered via <kbd>F1</kbd> and/or <kbd>?</kbd>)?

**Comment by Snuffleupagus** [comment]
Do we still actually want to attempt to add keyboard shortcuts in the tooltips? /cc @timvandermeij 

Looking at the PR above, this *most unfortunately* doesn't look like a very good beginner bug without prior experience with the viewer-code. The following is a basic patch that attempts to handle tooltips dynamically, and with platform-specific shortcuts: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:pdf.js:tooltip-shortcuts

**Comment by timvandermeij** [comment]
I don't have a particularly strong opinion on this. I think the basic implementation looks good, but on the other hand this request hasn't come up in over 8 years, so I'm not really sure if it's worth the extra complexity...

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and the lack of any duplicates, let's just close this as WONTFIX for now.
