### ISSUE TITLE
PDF document should be without first empty page

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/pdf.js#4281]
We received report about one PDF document which contains first empty page. When I open this document in Adobe Reader there is no first empty page. 

**PDF document**: http://jasnapaka.com/bugs/201401118288024775776630217.pdf
**pdf.js**: Firefox 30.0a1 (2014-02-10), HWA enabled
**OS**: Windows 7 64 bit

**Web Console**:
"Error: Invalid XRef stream header" pdf.worker.js:205
"XRef_readXRef@resource://pdf.js/build/pdf.worker.js:5519
XRef_parse@resource://pdf.js/build/pdf.worker.js:5129
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:4495
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:4379
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4031
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
BasePdfManager_ensureModel@resource://pdf.js/build/pdf.worker.js:3892
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:34894
" pdf.worker.js:207
"Warning: Unsupported feature "unknown"" pdf.worker.js:190
"Warning: Unsupported feature "unknown"" pdf.js:190
"XRefParseExceptionClosure@resource://pdf.js/build/pdf.worker.js:399
pdfjsWrapper@resource://pdf.js/build/pdf.worker.js:394
@resource://pdf.js/build/pdf.worker.js:40035
" pdf.worker.js:4038
"Warning: Indexing all PDF objects" pdf.worker.js:190
"PDF cf64a0acbfb8274a0e4ea604dd17450 [1.7 Oracle PDF driver; modified using iText 2.1.7 by 1T3XT / Oracle11gR1 AS Reports Services](PDF.js: 0.8.990)" viewer.js:3178
"Warning: AcroForm/XFA is not supported" viewer.js:3193
"Error: Bad FCHECK in flate stream: 120, 239" pdf.worker.js:205
"FlateStream@resource://pdf.js/build/pdf.worker.js:32886
Parser_makeFilter@resource://pdf.js/build/pdf.worker.js:31849
Parser_filter@resource://pdf.js/build/pdf.worker.js:31822
Parser_makeStream@resource://pdf.js/build/pdf.worker.js:31814
Parser_getObj@resource://pdf.js/build/pdf.worker.js:31650
XRef_fetch@resource://pdf.js/build/pdf.worker.js:5611
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:5557
Dict_get@resource://pdf.js/build/pdf.worker.js:4618
getDefaultAppearance@resource://pdf.js/build/pdf.worker.js:2723
Annotation@resource://pdf.js/build/pdf.worker.js:2791
WidgetAnnotation@resource://pdf.js/build/pdf.worker.js:2996
Annotation_fromRef@resource://pdf.js/build/pdf.worker.js:2953
PageClosure/Page.prototype.annotations@resource://pdf.js/build/pdf.worker.js:4306
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4029
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
Page_getOperatorList@resource://pdf.js/build/pdf.worker.js:4234
wphSetupRenderPage/<@resource://pdf.js/build/pdf.worker.js:35160
" pdf.worker.js:207
"Warning: Unsupported feature "unknown"" pdf.worker.js:190
"error@resource://pdf.js/build/pdf.worker.js:209
FlateStream@resource://pdf.js/build/pdf.worker.js:32886
Parser_makeFilter@resource://pdf.js/build/pdf.worker.js:31849
Parser_filter@resource://pdf.js/build/pdf.worker.js:31822
Parser_makeStream@resource://pdf.js/build/pdf.worker.js:31814
Parser_getObj@resource://pdf.js/build/pdf.worker.js:31650
XRef_fetch@resource://pdf.js/build/pdf.worker.js:5611
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:5557
Dict_get@resource://pdf.js/build/pdf.worker.js:4618
getDefaultAppearance@resource://pdf.js/build/pdf.worker.js:2723
Annotation@resource://pdf.js/build/pdf.worker.js:2791
WidgetAnnotation@resource://pdf.js/build/pdf.worker.js:2996
Annotation_fromRef@resource://pdf.js/build/pdf.worker.js:2953
PageClosure/Page.prototype.annotations@resource://pdf.js/build/pdf.worker.js:4306
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4029
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
Page_getOperatorList@resource://pdf.js/build/pdf.worker.js:4234
wphSetupRenderPage/<@resource://pdf.js/build/pdf.worker.js:35160
" pdf.worker.js:4038
"Warning: Unsupported feature "unknown"" pdf.js:190
"Error: Bad FCHECK in flate stream: 120, 239" pdf.worker.js:205
"FlateStream@resource://pdf.js/build/pdf.worker.js:32886
Parser_makeFilter@resource://pdf.js/build/pdf.worker.js:31849
Parser_filter@resource://pdf.js/build/pdf.worker.js:31822
Parser_makeStream@resource://pdf.js/build/pdf.worker.js:31814
Parser_getObj@resource://pdf.js/build/pdf.worker.js:31650
XRef_fetch@resource://pdf.js/build/pdf.worker.js:5611
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:5557
Dict_get@resource://pdf.js/build/pdf.worker.js:4618
getDefaultAppearance@resource://pdf.js/build/pdf.worker.js:2723
Annotation@resource://pdf.js/build/pdf.worker.js:2791
WidgetAnnotation@resource://pdf.js/build/pdf.worker.js:2996
Annotation_fromRef@resource://pdf.js/build/pdf.worker.js:2953
PageClosure/Page.prototype.annotations@resource://pdf.js/build/pdf.worker.js:4306
Page_getAnnotationsData@resource://pdf.js/build/pdf.worker.js:4293
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4031
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
wphSetupGetAnnotations/<@resource://pdf.js/build/pdf.worker.js:35143
" pdf.worker.js:207
"Warning: Unsupported feature "unknown"" pdf.worker.js:190
"error@resource://pdf.js/build/pdf.worker.js:209
FlateStream@resource://pdf.js/build/pdf.worker.js:32886
Parser_makeFilter@resource://pdf.js/build/pdf.worker.js:31849
Parser_filter@resource://pdf.js/build/pdf.worker.js:31822
Parser_makeStream@resource://pdf.js/build/pdf.worker.js:31814
Parser_getObj@resource://pdf.js/build/pdf.worker.js:31650
XRef_fetch@resource://pdf.js/build/pdf.worker.js:5611
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:5557
Dict_get@resource://pdf.js/build/pdf.worker.js:4618
getDefaultAppearance@resource://pdf.js/build/pdf.worker.js:2723
Annotation@resource://pdf.js/build/pdf.worker.js:2791
WidgetAnnotation@resource://pdf.js/build/pdf.worker.js:2996
Annotation_fromRef@resource://pdf.js/build/pdf.worker.js:2953
PageClosure/Page.prototype.annotations@resource://pdf.js/build/pdf.worker.js:4306
Page_getAnnotationsData@resource://pdf.js/build/pdf.worker.js:4293
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4031
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
wphSetupGetAnnotations/<@resource://pdf.js/build/pdf.worker.js:35143
" pdf.worker.js:4038
"Warning: Unsupported feature "unknown"" pdf.js:190
"Při vykreslování stránky nastala chyba.
PDF.js v0.8.990 (sestavení: 54f6291)
Zpráva: Bad FCHECK in flate stream: 120, 239
Zásobník: error@resource://pdf.js/build/pdf.worker.js:209
FlateStream@resource://pdf.js/build/pdf.worker.js:32886
Parser_makeFilter@resource://pdf.js/build/pdf.worker.js:31849
Parser_filter@resource://pdf.js/build/pdf.worker.js:31822
Parser_makeStream@resource://pdf.js/build/pdf.worker.js:31814
Parser_getObj@resource://pdf.js/build/pdf.worker.js:31650
XRef_fetch@resource://pdf.js/build/pdf.worker.js:5611
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:5557
Dict_get@resource://pdf.js/build/pdf.worker.js:4618
getDefaultAppearance@resource://pdf.js/build/pdf.worker.js:2723
Annotation@resource://pdf.js/build/pdf.worker.js:2791
WidgetAnnotation@resource://pdf.js/build/pdf.worker.js:2996
Annotation_fromRef@resource://pdf.js/build/pdf.worker.js:2953
PageClosure/Page.prototype.annotations@resource://pdf.js/build/pdf.worker.js:4306
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4029
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4021
Page_getOperatorList@resource://pdf.js/build/pdf.worker.js:4234
wphSetupRenderPage/<@resource://pdf.js/build/pdf.worker.js:35160

**Comment by timvandermeij** [comment]
There is also this warning now:

`Error: Bad FCHECK in flate stream: 120, 239`

**Comment by timvandermeij** [comment]
Closing since this file is now fixed.
