### ISSUE TITLE
Mis-scaled rendering on iPad

### ISSUE THREAD

**Issue by drowouw** [mozilla/pdf.js#4310]
Viewing pdf files with images on iPad shows them distorted and mis-scaled.
If you need I can add a screen shot.

**Comment by reggersusa** [comment]
I have the same issue. I found the pages mis-scaled only on iOS 6 and 7.1 using Safari 6 and 7 respectively. The problem does not exist on iOS 8 with Safari 8. Here is my full report:

Description: Pages are squeezed vertically
Link to the PDF: https://www.dropbox.com/s/p8o6mdjgcafe32x/ContentServer.pdf?dl=0
Location in PDF: all pages
Screen shot: https://www.dropbox.com/s/2drseoesqtdpq2p/IMG_0036.png?dl=0
Browser version: Safari 6 & 7
Operating System: iOS 6 & 7.1
Note: Works fine on Safari 8 on iOS 8.1
PDFJS version: 1.0.907
Console messages/warnings:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (locale.properties, line 0)
[Warning] http://lpmc_reggers/~reggers/PDFJS/web/locale/locale.properties not found. (l10n.js, line 315)
[Warning] #page_of is undefined. (l10n.js, line 794)
[Log] PDF e8b9fb7aa835db4a8a8723cb849de412 [1.6 iTextSharp 4.1.6 by 1T3XT / -] (PDF.js: -) (viewer.js, line 1017)
[Warning] #thumb_page_title is undefined. (l10n.js, line 794, x7)
[Warning] #thumb_page_canvas is undefined. (l10n.js, line 794, x2)

**Comment by yurydelendik** [comment]
Closing as won't fix for iOS6 and 7. Work for IOS8+
