### ISSUE TITLE
A document ended up with "Error: Invalid XRef table: unexpected first object"

### ISSUE THREAD

**Issue by deepj** [mozilla/pdf.js#4419]
**PDF document**: http://www.ai.wu.ac.at/~kaiser/birgit/Reflections_TheoryU.pdf
**Versions**: Firefox 28 beta, pdf.js 0.8.1136
**OS**: Mac OS X 10.9.2

**Console output**:

```
"Error: Invalid XRef table: unexpected first object" pdf.js:1259
"XRef_readXRefTable@resource://pdf.js/build/pdf.worker.js:5695
XRef_processXRefTable@resource://pdf.js/build/pdf.worker.js:5591
XRef_readXRef@resource://pdf.js/build/pdf.worker.js:5928
XRef_parse@resource://pdf.js/build/pdf.worker.js:5558
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:4913
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:4797
NetworkPdfManager_ensureHelper@resource://pdf.js/build/pdf.worker.js:4446
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:4436
BasePdfManager_ensureModel@resource://pdf.js/build/pdf.worker.js:4310
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:35435
runHandlers@resource://pdf.js/build/pdf.worker.js:955
" pdf.js:1259
"Warning: Unsupported feature "unknown"" pdf.js:1259
"Warning: Unsupported feature "unknown"" pdf.js:197
"XRefParseExceptionClosure@resource://pdf.js/build/pdf.worker.js:414
pdfjsWrapper@resource://pdf.js/build/pdf.worker.js:409
@resource://pdf.js/build/pdf.worker.js:40711
" pdf.js:1259
"Warning: Indexing all PDF objects" pdf.js:1259
"PDF 397920423de0d51a9fd2c5ea3ca818 [1.3 Mac OS X 10.4.10 Quartz PDFContext / Adobe InDesign CS2 (4.0.5)] (PDF.js: 0.8.1136)"
```

**Comment by deepj** [comment]
Any progress on this? I think if it doesn't cause any problem the bug in the pdf files could be ignored. The message is more than confusion for ordinary users in this context.

**Comment by Snuffleupagus** [comment]
I'm closing this issue as WFM, since the PDF file renders correctly and given that we no longer show the fallback bar for (recoverable) XRef errors.

Note that there's still a message in the browser console about the XRef error, however given that the PDF file actually is corrupt that's appropriate here (and this message isn't visible to regular users anyway).

**Comment by Bytesmiths** [comment]
I find that the Mac utility "Lightweight PDF" gets rid of the infamous "Invalid xref table" error, and also makes the PDF smaller.
