### ISSUE TITLE
iPad: Document loaded, blank Page.

### ISSUE THREAD

**Issue by dvorpahl** [mozilla/pdf.js#4432]
Hi,

i'm using _PDFJS v0.8.1145_ (build ad623ff). i used it to create hybrid pdf-reader for desktop and mobile web.applications.

on desktop everything works fine.

on mobile (ipad) device the document was loaded also well as:
- CreationDate: "D:20140217162941+01'00'"
- IsAcroFormPresent: false
- IsXFAPresent: false
- ModDate: "D:20140217162941+01'00'"
- PDFFormatVersion: "1.4"
- Producer: "PDFlib 7.0.4 (C++/Win32)"

but the canvas will be blank (white). pagenumbers and meta information are correct.

i've no idea why.

**Comment by kejsiStruga** [comment]
Hi, can you use the download button on iPad ?
Thank you

**Comment by timvandermeij** [comment]
@kejsiStruga Please don't post unrelated comments on issues.

**Comment by pedropcruz** [comment]
well, on my case, i cant really show the pdf:

Here:

![pdf_idp_error](https://user-images.githubusercontent.com/6757946/36605853-e396f2b8-18b9-11e8-963a-afcc5fa5c340.png)

**Comment by dvorpahl** [comment]
hi @yurydelendik.
any news to this -device performance issue- ?? maybe a _precalc-1/2-resolution_ or something like that?

**Comment by Snuffleupagus** [comment]
Given the old age of this issue, the fact that none of the links in https://github.com/mozilla/pdf.js/issues/4432#issuecomment-37191259 work any more, that there's other issues open about performance problems in iOS devices, and finally that the main focus of development is the Firefox built-in PDF Viewer; closing as INCOMPLETE for now.
