### ISSUE TITLE
Add document loading life cycle events

### ISSUE THREAD

**Issue by datsis** [mozilla/pdf.js#4448]
There is need for life cycle events in case if PDFJS is used to review multiple documents.

Here is scenario:
1) User makes search and finds several documents with some keywords
2) When user click on document PDFJS is loaded document with open(url) function
3) When document is loaded and rendered it is necessary to highlight keywords

For now there is no way how to catch a moment when document has been rendered.

**Comment by Snuffleupagus** [comment]
> For now there is no way how to catch a moment when document has been rendered.

There's the `documentinit` event, which signals that the document is ready for user-interaction; this issue can probably be closed now.
