### ISSUE TITLE
Need to check for tooComplexToFollowFunctions in ENDF?

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#4450]
I think that ENDF should have the same logic as FDEF.
I didn't see a problem with a doc but noticed this while working on a bug.

https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L3643

Instead of:

``` javascript
} else if (op === 0x2D) { // ENDF - end of function
```

Should be?

``` javascript
} else if (op === 0x2D && !tooComplexToFollowFunctions) { // ENDF - end of function
```

**Comment by Snuffleupagus** [comment]
Given that we don't have an example of a PDF document (with TrueType fonts) that's currently broken without the proposed changes, let's WONTFIX this for now since making changes without test-cases always carry a regression risk (even though it may be small).
