### ISSUE TITLE
pdf.js worst case: openclassrooms pdfs

### ISSUE THREAD

**Issue by NawfelBgh** [mozilla/pdf.js#4487]
Download a pdf file from this website:
[http://fr.openclassrooms.com/](http://fr.openclassrooms.com/)

Pdf.js performs poorly. horrible performance!! My native pdf reader shows them without problems

Edit:
I retried again with the latest [dev version](http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi). Performance is better but it is still SLOW. when i scroll, Firefox freezes completely.

My OS: Fedora 20
Firefox Ver: 27.0.1
Hardware: Memory: 3.7 GiB, Processor: Intel® Core™ i3 CPU M 370 @ 2.40GHz × 4, OS type: 64-bit, Graphics: Intel® Ironlake Mobile)
JavaScript console warning: Just few l10n warnings "[l10n] #document_properties_producer missing for [chrome://global/locale/intl.properties]"

I had the same problem with older versions of firefox and in an other linux (Mint 13)

Here is [a PDF file i downloaded](https://drive.google.com/file/d/0B9nStCiu3GXxc2lSOHdESTZPb00/edit?usp=sharing) from that site.
The table of content (pages 2, 3) is shown line by line in pdf.js whereas the whole page is rendered instantly in Evince (My native pdf reader). At first, scrolling is unresponsive, then firefox freezes until i switch to an other tab.

**Comment by timvandermeij** [comment]
This has most likely been fixed by #6590, causing much less DOM elements to be created, hence I'm closing this issue as resolved.
