### ISSUE TITLE
Question mark ('?') comes up where it shouldn't

### ISSUE THREAD

**Issue by YSYoon** [mozilla/pdf.js#4498]
Hi,

PDFJS.version = '0.8.1277';
PDFJS.build = 'cebf783';

page 2 of this PDF file (50MB) shows question marks.
https://www.dropbox.com/s/gka4pvgc2w8xaf0/testMat2.pdf

**Comment by brendandahl** [comment]
Is this pdf still available? Also, are there still isues?

**Comment by YSYoon** [comment]
Hello, I'm not using pdf.js for my project any more so I can't test it myself.
Please try this link and let me know the result. Thank you!
https://www.dropbox.com/s/gka4pvgc2w8xaf0/testMat2.pdf?dl=0

**Comment by brendandahl** [comment]
@YSYoon  "Access to this link has been disabled. Please ask the owner of the shared link to send a new link to access the file or the folder."

**Comment by YSYoon** [comment]
@brendandahl sorry, I thought clicking on share would reenable it, but I guess I was wrong.
new link: https://www.dropbox.com/s/hnaso4vgyl2901i/testMat2.pdf?dl=0

**Comment by brendandahl** [comment]
Looks fine for me on chrome 49 and safari 9.

**Comment by YSYoon** [comment]
I've deleted link to the file due to copyright issue
