### ISSUE TITLE
PDF missing background color, appears blank

### ISSUE THREAD

**Issue by samth** [mozilla/pdf.js#4499]
This pdf: http://www.cse.chalmers.se/edu/course/pfp/lectures/lecture2/Marlow14.pdf has a blue background and white text, but the background doesn't appear in pdf.js (I think v0.8.649), and so all the text is invisible.  It also doesn't present the usual "This PDF doesn't work right" warning.

**Comment by timvandermeij** [comment]
I can no longer reproduce this on Arch Linux with Firefox 42. Closing as fixed.
