### ISSUE TITLE
Printing problems: Landscape to Portrait

### ISSUE THREAD

**Issue by alexandrevicenzi** [mozilla/pdf.js#4514]
When I have a Landscape PDF and use Print button on pdf.js the PDF is printed in Portrait mode and in a lower size, not 100% for pages that are Portrait.

Tested on current on-line version, and 0.8.649. I'm using Firefox Nightly.

PDF file to try to simulate: http://bit.ly/1eFc4in

**Comment by timvandermeij** [comment]
The automatic landscape printer selection is tracked in #2851. The other problem mentioned here, automatic page rotation for printing, has been fixed in #8043.
