### ISSUE TITLE
Page Number field not triggering in IE11

### ISSUE THREAD

**Issue by osuritz** [mozilla/pdf.js#4551]
This issue seems specific to IE11.
#### Steps to reproduce
- After a document is open, click the pageNumber field and enter a (valid) page number.
- Press ENTER
#### Observation

Nothing happens
#### Expected behavior

Viewer jumps to correct page (which it does with the ENTER key in all other browsers)

_Note:_ the event seem to be properly triggered if you click outside the pageNumber textbox (seems to properly trigger the onChange event).

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
