### ISSUE TITLE
Presentation Mode not working in Safari

### ISSUE THREAD

**Issue by osuritz** [mozilla/pdf.js#4561]
Hello,

Just me again... your friendly-neighborhood bug reporter ;)
It appears that Presentation Mode (aka Fullscreen mode) isn't working in Safari (at least not on MacOS).

I found this SO issue and it seems to apply: http://stackoverflow.com/questions/8427413/webkitrequestfullscreen-fails-when-passing-element-allow-keyboard-input-in-safar

Basically, if you drop `Element.ALLOW_KEYBOARD_INPUT` from the call to `webkitRequestFullScreen` it sort of works. E.g.

    //this.container.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
    this.container.webkitRequestFullScreen();  // probably breaks Chrome, through.

I doesn't render well though… e.g. if the developer bar was open at the bottom when `webkitRequestFullScreen` is called, then there's a gap in the fullscreen view where the dev bar was.

Could we maybe hide the Presentation Mode in Safari until it can be rendered correctly?

**Comment by abioneperhobby** [comment]
Hi,

Safari on ipad 8.4.1 doesn't show fullscreen button on the demo page (https://mozilla.github.io/pdf.js/web/viewer.html) . 

Is this problem solver or not?

**Comment by timvandermeij** [comment]
If the button is not showing, then we have detected that presentation mode is not working and we have disabled it to avoid problems with browsers that do not (fully) support the Fullscreen API.

**Comment by sunil4infobeans** [comment]
HI,
Facing same issue as mentioned by @abioneperhobby 
Doesn't show fullscreen button on iPad and iPhone devices.
Same issue with https://github.com/kogmbh/ViewerJS. 

Is there any possible solution for this issue?

**Comment by nikna** [comment]
This is not working (anymore) on newest Safari and iOS version. The button is not shown, and if I disable the check to show it there is nothing happening after I click on it.
