### ISSUE TITLE
Improve text layer tests.

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#4576]
It would be useful to improve the text layer tests by taking a snapshot of the actual rendering of a the pdf on canvas during the test. This would allow us to better check the alignment of the text layer with the actual pdf rendering.

For text layer tests, we'd need to add a third radio button to the reftest analyzer that would show the real canvas rendering of the pdf.

**Comment by timvandermeij** [comment]
Fixed by #6619.
