### ISSUE TITLE
Slow performance: Chinese PDF

### ISSUE THREAD

**Issue by bthorben** [mozilla/pdf.js#4580]
PDF.js is unusably slow when viewing this pdf:
http://www.grapes-trams.org.cn/UploadFile/files/%E5%88%A9%E7%94%A8%E4%B8%80%E4%B8%AA%E6%B5%B7%E6%B0%94%E8%80%A6%E5%90%88%E6%A8%A1%E5%BC%8F%E5%AF%B9%E5%8F%B0%E9%A3%8EKrovanh%E7%9A%84%E6%A8%A1%E6%8B%9F.pdf

**Comment by timvandermeij** [comment]
Closing as fixed by #6590.
