### ISSUE TITLE
IE11 font issue

### ISSUE THREAD

**Issue by marcelodesouza** [mozilla/pdf.js#4619]
Hi 

Please check the font problem on IE11. 
http://www.simpleone.com/contracts/546?token=411e26955f24112e64cb

See screenshot 
![pdfjs-ie11 fw](https://cloud.githubusercontent.com/assets/1896685/2696714/b89fb144-c3e5-11e3-91aa-fe215b3e09ca.png)

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
