### ISSUE TITLE
Blank page on iOS safari only.

### ISSUE THREAD

**Issue by HerbJiang** [mozilla/pdf.js#4620]
This pdf cannot be rendered correctly on iOS safari. It shows blank page only, but it rendered correctly on PC / MAC or Android. 
https://www.dropbox.com/s/qnva96o2jlmodbh/04-01-test-on-ios.pdf  
I use web inspector to debug and there is no error in the console.

**Comment by Snuffleupagus** [comment]
Given that age of this issue, and the fact that it's platform/browser specific; is it really meaningful to keep it open still?
