### ISSUE TITLE
Pdf viewer shows black pages

### ISSUE THREAD

**Issue by gentilitedeschi** [mozilla/pdf.js#4648]
Some pdf files are shown as black pages with the internal pdf viewer; see http://www.braidense.it/rd/03595.pdf; if using any acrobat viewer or saved, pages appear correctly

**Comment by quaoaris** [comment]
This bug might be related to the 4 BitsPerComponent, which is not handled correctly. See https://bugzilla.mozilla.org/show_bug.cgi?id=1659412

**Comment by THausherr** [comment]
IrfanView claims that the image inside the PDF from the bugzilla issue has 12 bits per pixel?!
