### ISSUE TITLE
TextLayer and Canvas Layer of pdf.js is not aligned for few pdf's

### ISSUE THREAD

**Issue by anushashetty** [mozilla/pdf.js#4665]
For many of the pdf's , the text layer and canvas layer are not aligned properly. 
We can see that the text layer has been misplaced. 
Because of this issue, search doesn't work properly for all these. Please check the screenshot attached :  I have searched for text "reading this" but it has highlighted some other text.
![screenshot](https://cloud.githubusercontent.com/assets/697216/2776930/9e7f358e-cadc-11e3-9c84-441b8649158b.png)

Please find one of the document which has issue here:
https://docs.google.com/file/d/0B4ByjzSjRWSfX0xYQllacFpFaW8/edit?pli=1

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6601.
