### ISSUE TITLE
Missing glyf and loca errors prevent invisible font from showing

### ISSUE THREAD

**Issue by cforcey** [mozilla/pdf.js#4684]
PDF.js shows a search button and accurately searches and allows selection of text for many types of PDFs.  For the PDF files created by our tools below (the vast majority of our large collection), however, we see no search box and are unable to select text.  Opening these same PDFs is Adobe Reader, Apple Preview, and Foxit Reader. None of those readers show error messages or any other signs that the PDF is malformed.

Our theory is that the relatively antique and simpe invisible font we are using for our text layer is missing some TrueType elements (glyf and loca tables) that the OpenType font sanitizer wants to see.  When it does not see them, it drops the font which in our case renders the PDF unsearchable becuase everything from the HDOC processing by Tesseract has been rendered in this one font.

Any advice or help you can provide would be great.  Thanks so much for this work on PDF.js -- it is a beautiful reader!

Error Message:

In Firefox console (debug turned on) we see:

"Warning: Error during font loading: Required "glyf" or "loca" tables are not found"

FontInspector on Firefox native PDF.js shows no fonts in the sidebar.

Document samples: 

http://pucdocket.s3.amazonaws.com/MA/12-42/121912dpuaprv_ocr.pdf
http://pucdocket.s3.amazonaws.com/MA/11-07/123112dpugrmt_ocr.pdf

Tools Used for PDF Creation:

Font: http://www.angelfire.com/pr/pgpf/if.html
ReportLab: https://bitbucket.org/rptlab/reportlab/overview
PyPDF2: https://github.com/mstamy2/PyPDF2

Possibly Related Issues:

https://github.com/mozilla/pdf.js/issues/3483
https://github.com/mozilla/pdf.js/pull/495
https://github.com/mozilla/pdf.js/issues/3522
![screen_shot_2014-04-25_at_10 58 38_am](https://cloud.githubusercontent.com/assets/38297/2802398/e63afb8a-cc8d-11e3-9a12-3583728d43f3.png)

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!
