### ISSUE TITLE
Strange characters in PDF

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#4691]
Hi people,

http://linux-training.be/files/books/LinuxFun.pdf

Look at the image
![captura_de_tela](https://cloud.githubusercontent.com/assets/1039418/2809356/7aac062a-cd69-11e3-9934-86c3e124468a.png)

Evince shows the pdf correctly, without this strange characters

I'm using Fedora 20, pdf.js 1.0.87 and Firefox 28.

**Comment by ousia** [comment]
@marcosps, I think the issue is solved (I’m on Fedora 25 using Firefox 55.0.1):

![solved-issue](https://user-images.githubusercontent.com/203767/29753195-52bef284-8b6c-11e7-88da-fa8eb1434353.png)

Could you check it at http://linux-training.be/files/books/LinuxFun.pdf#page=14?

**Comment by marcosps** [comment]
@ousia indeed, it now works, thanks!
