### ISSUE TITLE
Part of document text not displaying

### ISSUE THREAD

**Issue by joepie91** [mozilla/pdf.js#4694]
pdf.js is failing to correctly display the document at http://pdf.cryto.net/document/PfYTDiZa1TuYHHTk. While the colored text is visible, the 'default-styled' document text is not.

A screenshot of the problem:
![original_owely20140427-18987-14m3vjf](https://cloud.githubusercontent.com/assets/1663259/2812010/5ca15eb2-ce3d-11e3-90f2-3539040da54d.png)

The document is *meant* to display black text, per the following thumbnail that was generated server-side using ImageMagick:

![pfytdiza1tuyhhtk](https://cloud.githubusercontent.com/assets/1663259/2812018/f1beccbe-ce3d-11e3-9cf5-6f4234e4a26a.png)

The original PDF can be downloaded at http://pdf.cryto.net/document/PfYTDiZa1TuYHHTk/download.

I am using the standard viewer that is shipped with pdf.js, with some minor UI modifications (such as the toolbar being auto-collapsed), that should not directly affect the document. The issue occurs regardless of whether the viewer is in an iframe or not (see also http://pdf.cryto.net/document/PfYTDiZa1TuYHHTk/embed).

The console log does not display any anomalies. The following debug information is output:

    PDF 719cc7d684314735832e2e9aa889de8 [1.4 Adobe PDF Library 9.9 / Adobe InDesign CS5 (7.0)] (PDF.js: 1.0.21) 

Platform: openSUSE 12.3 x64, Google Chrome 34.0.1847.116, pdf.js 1.0.21 (build f954cde)

**Comment by yurydelendik** [comment]
Works for me on Chrome for Mac now -- closing.
