### ISSUE TITLE
API for getting parts of the PDF file loaded

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#4703]
Currently API allows only getting whole file through `getData` API call. If I understand correctly, this means that whole file is copied in memory to be passed to the caller. Would it be possible to have an API call which would allow reading file in chunks? We are trying to post-process PDF file additionally after it has been loaded and would like to prevent duplicate downloading to the client or having multiple copies of it in the browser's memory.

**Comment by Snuffleupagus** [comment]
Based on https://github.com/mozilla/pdf.js/issues/4703#issuecomment-46509406 it seems unlikely that this feature is desirable in the general PDF.js library; should this just be closed as WONTFIX?

**Comment by timvandermeij** [comment]
Yes, I also don't really see a general use case for such a feature.
