### ISSUE TITLE
Blurry/fuzzy embedded images

### ISSUE THREAD

**Issue by rustyx** [mozilla/pdf.js#4706]
A fix for this was attempted many times, but still the issue exists.
FF 29.0.

Test PDF: http://rustyx.org/temp/fuzzy-test.pdf

![Results](http://rustyx.org/temp/blurry-images-pdfjs.png)

**Comment by jonwilks** [comment]
Just poking this issue - very interested in this.

**Comment by jlukic** [comment]
:+1:

**Comment by ssaras** [comment]
Any update on this? I'm having similar issues with blurry images. 

In Adobe Acrobat Reader 2017 Release | Version 2017.012.20098

![adobe](https://user-images.githubusercontent.com/17534571/29826804-47b39e5e-8ca6-11e7-8c6a-ae3d4ae74ce9.PNG)

In Chrome 60.0.3112.113 (Official Build) (64-bit), Firefox 54.0.1 (32-bit) and Edge 40.15063.0.0 using pdf.js version 1.4.20

![browser](https://user-images.githubusercontent.com/17534571/29827214-5419659c-8ca7-11e7-908f-30bd7de2b0b1.PNG)

**Comment by Vorador666** [comment]
Hello world,

I have the same issue with Firefox 56.0.2 (32 bits) & PDF.js v1.8.618 VS Adobe Reader XI (v11.0.1).
It's just nightmarish for the eyes :)
Any fix planned ?

Best regards
![ar1101](https://user-images.githubusercontent.com/38276616/38602286-9b3cba22-3d6a-11e8-84fd-7a6095797437.PNG)
![ff5602](https://user-images.githubusercontent.com/38276616/38602287-9b6b5f9e-3d6a-11e8-83dc-cf3504606256.PNG)

**Comment by asmith3006** [comment]
I have the same issues with Firefox 64.0

Is there any chance of this being resolved? I'm going to have to switch my staff to use Chrome instead of Firefox as a result of this sadly.

**Comment by kno10** [comment]
Here is a small test file (7.6k) that renders fine in all my PDF viewers except pdf.js:
[optics-multiple-plot.pdf](https://github.com/mozilla/pdf.js/files/4843080/optics-multiple-plot.pdf)

**Comment by THausherr** [comment]
The image in that PDF has /Interpolate sent to false, but the PDF is rendered like this:
![grafik](https://user-images.githubusercontent.com/6665575/86012511-5c630580-ba1e-11ea-9e20-9907e9f1aad7.png)

**Comment by THausherr** [comment]
When /Interpolate isn't set, interpolation should be done only when scaling down, not when scaling up
