### ISSUE TITLE
Only first page can be seen in presentation mode under IE11

### ISSUE THREAD

**Issue by srees** [mozilla/pdf.js#4711]
IE11 successfully renders PDF inside iframe, but when presentation mode is selected only the first page can be seen. Can't seem to find a way to get to the next page.

**Comment by djivko** [comment]
Most probably this defect is related to this one:
https://connect.microsoft.com/IE/feedback/details/838286/ie-11-incorrectly-reports-dom-element-sizes-in-fullscreen-mode-when-fullscreened-element-is-within-an-iframe
