### ISSUE TITLE
Can't search across lines in some PDFs (like the demo PDF)

### ISSUE THREAD

**Issue by ncanen** [mozilla/pdf.js#4742]
pdf.js is not able to search for text across lines in some PDFs (like the demo PDF). For example if you search for the phrase "code that can handle" the find dialog states "Phrase not found"; however, this phrase does exist in the 1st paragraph (3rd line) wrapping to the next line.

**Comment by speedplane** [comment]
Note that PR #5783 will fix this.

**Comment by walenzack** [comment]
+1 It would be really really nice to have that PR merged to solve this (along a number of other open issues, btw).

**Comment by timvandermeij** [comment]
Pull request #5783 was never completely finished, but it can be used as a baseline for fixing this.

**Comment by calixteman** [comment]
It should be fixed by https://github.com/mozilla/pdf.js/pull/13261.
