### ISSUE TITLE
Document outline will not load

### ISSUE THREAD

**Issue by nturcot** [mozilla/pdf.js#4749]
When trying to open the document below, nothing is displayed after the progressbar has finished loading: only the gray background of the reader is visible.

http://bourse.lesechos.fr/complements/2014/04/30/968815_1398865921_page-30.pdf

Reproduced with Firefox 29 on windows XP, Seven and Ubuntu Linux.

This issue was reported on the French support forums: http://forums.mozfr.org/viewtopic.php?f=5&t=118245

**Comment by timvandermeij** [comment]
Closing since the outline is now available as well.
