### ISSUE TITLE
Pixelation/Quality issues of vectors graphics in Chrome. 

### ISSUE THREAD

**Issue by Salmizar** [mozilla/pdf.js#4760]
In Chrome in particular, vector graphics are showing up noticeably different than IE and FF. Some are pixelated and lower quality.

I created this basic file to showcase the problem.
http://www.salmizar.com/files/ford/ford.pdf

Here is a screenshot of what it looks like in FF:

http://www.salmizar.com/files/ford/ff.png

Here is a screenshot of what it looks like in Chrome.

http://www.salmizar.com/files/ford/chrome.png

Side Note:

Also, Interestingly, file PDF above, fails to load properly in the online demo in FF. Console message as follows: 

PDF 11dd61fd574441b1ab5ff38782ff [1.4 pdfeTeX-1.21a / TeX](PDF.js: 1.0.162)
viewer.js (line 3426)
Warning: Unsupported feature "unknown"

Works properly in my local dev (versio:0.8.1334, build:b97127a) copy though.

Thanks,
Chris

**Comment by esamo** [comment]
And confirmed using Chrome 50.0.2661.37 beta-m 64-bit.

**Comment by esamo** [comment]
Beta version of pdfjs-1.4.20-dist makes no difference.

**Comment by timvandermeij** [comment]
This appears to be some upstream Chrome bug. Maybe @Rob--W has an idea?

**Comment by Rob--W** [comment]
@esamo Could you share the PDF file?
@timvandermeij I'm not aware of any related bugs in Chrome. Maybe this has something to do with how we draw patterns (#6606)? (I didn't check whether the image is drawn using tiling patterns, I could be completely off).

**Comment by esamo** [comment]
@Rob--W Yeah, the file is loaded here: http://www.pbspolska.eu/test-przegladarka-katalogu-pdf (20 MB PDF). Most graphics looks like there would be no antialias at all.

**Comment by medialwerk** [comment]
I have also an issue with pixelation. I have attached a pdf which shows a circle. In Chrome the circle seems to not be antialiased and a warning appears:

```
# Chrome Version 50.0.2661.94 (64-bit) / pdfjs-dist: 1.5.258
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
```

[bug.pdf](https://github.com/mozilla/pdf.js/files/272123/bug.pdf)

**Comment by Snuffleupagus** [comment]
> I created this basic file to showcase the problem.
> http://www.salmizar.com/files/ford/ford.pdf

Unfortunately that link is no longer available...

> the file is loaded here: http://www.pbspolska.eu/test-przegladarka-katalogu-pdf (20 MB PDF).

... and neither is that one.

> I have attached a pdf which shows a circle. In Chrome the circle seems to not b
> bug.pdf

That one WFM, when testing with PDF.js version `2.9.350`, in Google Chrome Beta version `91.0.4472.77` on Windows.

---

All-in-all, closing this old issue as WFM since nothing seems broken any more.

(If there's still problems, please open a *new* issue for each broken PDF document.)
