### ISSUE TITLE
Popup menu on the top right not behaving like usual GUI elements

### ISSUE THREAD

**Issue by rocketsound** [mozilla/pdf.js#4810]
With most if not all (popup) menus across all popular platforms like Windows, OS X, ... it is possible to open a menu by pressing the left mouse button. While keeping the left mouse button pressed you hover over the menu item you want to select and then release the button. This behavior isn't working for me with the "»" menu in the top right of the PDF viewer. Instead nothing happens when I try using it like described above.

I'm using version 1.0.219.

**Comment by timvandermeij** [comment]
Closing as won't-fix as per discussion in #4813. It is a very minor feature which required quite some code to get working properly, and it is not clear how many people actually use this.
