### ISSUE TITLE
"Real" full-screen

### ISSUE THREAD

**Issue by joepie91** [mozilla/pdf.js#4816]
For my PDF hosting service, which provides an embed code for documents, I was looking to have a "real" full-screen mode - that is, displaying the regular viewer in full-screen, rather than a slimmed-down fit-to-page "presentation mode" (as this makes text-dense documents hard to read). Finding no such functionality in the default viewer, I decided to [implement it myself](https://github.com/joepie91/pdfy/commit/14571567a58c03fbf809d71e14dc81ad1ee4bca1)...

While implementing this, I found that there are some problems with the way presentation mode works - most notably the assumption that "if I'm in full-screen, I must be in presentation mode" - that break 'regular' full-screen. I've more or less hacked around this in my implementation by setting a class on the `<body>` and a variable in the `PresentationMode` object when in presentation mode, but this is far from an ideal solution.

My suggestion would be to either implement a "real" full-screen mode, or to at least modify the behaviour of PresentationMode so that it doesn't assume that 'full screen' and 'presentation mode' are the same thing (making it easier for developers to implement their own variants of full-screen without breaking presentation mode).

Somewhat related to #3828.

EDIT: For completeness' sake, tthe implementation of full-screen I mean can be seen [here](http://pdf.yt/d/LbakZXpRDswUzRwe) (the right-most icon in the collapsed toolbar).

**Comment by groe** [comment]
I have just encountered the same problem. Solved it by requesting full screen for the outer document (i.e. not the PDF.js iframe) and resizing the iframe to 100% width and height while full screen is activated.

Not an ideal solution though. Would be nice if pdf.js provided an option or even 2 buttons to choose from: One for presentation mode (no toolbars, no UI) and one for "reading mode" (fullscreen with regular controls).

I agree with @joepie91 that it would be reasonable to assume that landscape usually needs presentation mode and portraits are usually better to be displayed in reading mode.

**Comment by Snuffleupagus** [comment]
> [...] In its current state, it's hard to implement anything to do with full-screen, without first having to dig through a large amount of PresentationMode code, having to actually change the PresentationMode code to not interfere.

This should have been addressed as part of PR #5699, since the `PDFPresentationMode` implementation won't unconditionally attach `fullscreenchange` event listeners any more.

Hence this issue should be closed, since it's been stated repeatedly (see the issues referenced above) that a general fullscreen mode won't be implemented in the default PDF.js viewer. /cc @timvandermeij
