### ISSUE TITLE
Incorrectly rendered 't' at 125% zoom level

### ISSUE THREAD

**Issue by joepie91** [mozilla/pdf.js#4820]
I was looking at [this document](http://pdf.yt/d/nZEw14APprsJbkeF), and noticed that `t` characters are being misrendered for me at 125% zoom level. I cannot reproduce this problem in either Google Chrome's internal PDF reader, nor in Evince; it appears to be a problem specific to pdf.js.

Screenshot of the problem:

![image](https://cloud.githubusercontent.com/assets/1663259/3029877/1aa797ec-e03a-11e3-98f0-29a661cb27ee.png)

Correct display in Evince:

![image](https://cloud.githubusercontent.com/assets/1663259/3029894/3a07ac1c-e03a-11e3-90a4-bf8b388f405d.png)

---

pdf.js 1.0.21 build f954cde, openSUSE 12.3, Google Chrome 34.0.1847.137

PDF log line: PDF cdfe75313a18bb6350687b3fb8a5923b [1.6 Acrobat Distiller 7.0 (Windows) / PScript5.dll Version 5.2.2] (PDF.js: 1.0.21)

**Comment by timvandermeij** [comment]
@joepie91 Does this still happen for you with the latest version of PDF.js at https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by timvandermeij** [comment]
No response. Closing also because I cannot reproduce this on Arch Linux.
