### ISSUE TITLE
Embedded viewer does not download documents

### ISSUE THREAD

**Issue by joepie91** [mozilla/pdf.js#4822]
After sending a URL to an article that embeds pdf.js (via my PDF hosting service) to a friend of mine, he informed me that while the viewer page itself loaded, the document was not loaded.

Brief problem description: when embedded under particular conditions, the PDF document is not loaded.

Upon further research, we've made the following observations:
- In the testcase at http://jsbin.com/doneyogo/1, I can view both documents. For my friend, neither of the documents will display. One iframe has `allowfullscreen` while the other does not, so that is evidently not a cause of problems.
- The document is literally never downloaded. No HTTP request for the document is made. The document URL in the source is correct, so it is the actual downloading (or triggering a download) that fails.
- The download button in the pdf.js viewer toolbar (which relies on pdf.js) does _not_ work. The "download original" link at the bottom of the embed (which does not rely on pdf.js) _does_ work. It seems like pdf.js is either never executed, or it somehow isn't triggered to download the file (and thus doesn't have a 'file' to download).
- My friend can view the document at http://pdf.yt/d/vdYp-3KipQ6xHOps. This embeds the viewer in the same way that the JSBin embed does, _however_ the parent page and embedded viewer run on the same domain. This suggests there might be a problem with cross-domain document loading or script execution.
- However, my friend _does_ get an alert(0) when he opens the testcase at http://jsbin.com/doneyogo/2, which indicates that "script execution in iframes" is not blocked wholesale.
- He also gets an alert(0) when opening the testcase at http://jsbin.com/doneyogo/3, which does the same thing as version 2, but cross-domain. This indicates that cross-domain script execution also functions.
- There is no output from pdf.js in his console whatsoever, not even the line that normally logs the application that the PDF was created in (along with the pdf.js version).
- He can reproduce the problem consistently. It always breaks in the same way. It also happens regardless of which document is being embedded.
- I cannot reproduce his problem at all (although my environment is different).

Environment of said friend:
- Ubuntu 13.10 x86
- Chromium 34.0.1847.116 (Developer Build 260972) x86
- pdf.js 1.0.21 build f954cde

My (non-reproducible) environment:
- openSUSE 12.3 x64
- Google Chrome 35.0.1916.114
- pdf.js 1.0.21 build f954cde

For completeness' sake: the build of pdf.js I am using has some customizations. None of these (fairly minor) customizations is related to document loading.

Looks like a pretty tricky corner case to me :)

**Comment by timvandermeij** [comment]
I agree. Let's close this for now.
