### ISSUE TITLE
Strange characters show instead of space characters in IE11

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#4836]
http://www.gender.go.jp/about_danjo/whitepaper/h25/gaiyou/pdf/h25_gaiyou.pdf

Please see the first page.

IE11 shws starange characters instead of space characters as I attched.
![ie11_space](https://cloud.githubusercontent.com/assets/3334552/3076009/ab3d01fa-e3a7-11e3-82fc-b88fd550b609.jpg)

**Comment by Snuffleupagus** [comment]
@takahiroyoshi Can you please confirm if PR #7427 fixed this issue?

**Comment by timvandermeij** [comment]
No response, so I'm closing this as fixed as the PR corresponds to the suggested fix of the issue's author.
