### ISSUE TITLE
Document shows ÿ instead of bullets

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#4837]
Using Firefox 29.0.1, Fedora 20 and pdf.js 1.0.248

In pdf.js:
![captura de tela de 2014-05-25 16 32 24](https://cloud.githubusercontent.com/assets/1039418/3077796/a1996e30-e443-11e3-9c77-60cab6b47996.png)

In evince:
![captura de tela de 2014-05-25 16 32 38](https://cloud.githubusercontent.com/assets/1039418/3077797/a6e1c374-e443-11e3-879e-5f28dd1ee84b.png)

File can be tested here:
http://www.nayuan.com.cn/ProductDocument/633862071587600000.pdf

**Comment by retrazil** [comment]
pdf.js(2.2.71) shows misplaced arrows but Evince(3.18.2) still shows y with two dots on the top. 

pdf.js
![RDA5807SP_datasheet_v1 1 doc   633862071587600000 pdf](https://user-images.githubusercontent.com/24795309/60383056-d702e900-9a89-11e9-81bb-a5af301051ee.png)

Evince
![Screenshot from 2019-06-29 16-20-03](https://user-images.githubusercontent.com/24795309/60383062-e1bd7e00-9a89-11e9-84be-fde14b4a6dd7.png)

**Comment by marcosps** [comment]
@retrazil well, I tested here using Nightly with Flatpak, and indeed, I think that showing an arrow fixes the issue. So I'm closing this issue, thanks for the pdf.js team!
