### ISSUE TITLE
Option to hide icon in omnibox

### ISSUE THREAD

**Issue by cmens** [mozilla/pdf.js#4842]
![Icon in omnibox](https://cloud.githubusercontent.com/assets/201669/3084180/84e895a6-e4f0-11e3-9680-2affd6485f32.png)

In the above picture you see the pdf icon displayed in the omnibox, I would be nice if there is an option the hide this.

**Comment by Snuffleupagus** [comment]
Is this issue still relevant, given that Chrome (since some time) appears to have moved extension icons from the omnibox to the toolbar?

**Comment by Rob--W** [comment]
This issue is not relevant any more. Now we have a different problem, namely that the button is either always visible, or always hidden: https://crbug.com/597657
