### ISSUE TITLE
Only some specific characters are thicker than others in the same sentence.

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#4848]
http://www.eaccess.net/technique_info/pdf/mobile.pdf

Open the page 6.
In pdf.js only some specific characters are thicker than others in the same sentence. Or most of characters are not Gothic while they should be.

![font_gothic](https://cloud.githubusercontent.com/assets/3334552/3092246/fdbcc810-e5a6-11e3-9992-974f5ba9b360.jpg)

**Comment by timvandermeij** [comment]
Closing since this is fixed in the latest version.
