### ISSUE TITLE
Ligatures in Linux Libertine are displayed incorrectly

### ISSUE THREAD

**Issue by capnrefsmmat** [mozilla/pdf.js#4853]
I have the following document created in LuaTeX using the [Linux Libertine](http://www.linuxlibertine.org/index.php?id=1&L=1) OpenType font:

http://refsmmat.com/files/microcosmographia.pdf

In Firefox 29.0.1 on Mac OS 10.9.3, some of the ligatures are displayed corrupted (both in-browser and in the [online viewer](https://mozilla.github.io/pdf.js/web/viewer.html)). For example, from the first page of that document:

![screen shot 2014-05-27 at 9 34 46 pm](https://cloud.githubusercontent.com/assets/711629/3099877/4f46c90e-e608-11e3-89a4-c3db9d23c50b.png)

and

![screen shot 2014-05-27 at 9 34 55 pm](https://cloud.githubusercontent.com/assets/711629/3099878/533b08ea-e608-11e3-896a-169789af5aac.png)

Curiously, the "fi" ligature in the second image is fine, but the "ft" ligature is not.

The document displays fine in Preview and Adobe Reader. I tried switching to the Apple-supplied Times font and ligatures appear fine. But Libertine has an abundance of unusual ligatures.

**Comment by capnrefsmmat** [comment]
I've just tried the web viewer again (Firefox 39, OS X 10.10.4) and the ligatures work correctly. The pdf.js version shipped with Firefox 39 still has the bug. Some recent change must have fixed it. I assume the fix will land in Firefox fairly soon?

**Comment by timvandermeij** [comment]
@capnrefsmmat Yes, probably within one or two versions.
