### ISSUE TITLE
IE9: out of memory on image-based PDF's without security

### ISSUE THREAD

**Issue by Wortany** [mozilla/pdf.js#4855]
Large image-based PDF's without encryption seem to balloon the memory consumption of IE9-only. With some cases going beyond 1.7GB causing an out-of-memory exception.

Once an owner password is set, the document is viewable with a memory usage of around 300MB which is atleast doable.

I can send some test-pdf's (around 40MB) but they are content-sensitive, so if you could provide an email-adress to which I could send it, that would be great.

This was tested on:
Pdf.js version 1.0.21 and 1.0.68.
Internet Explorer 9.0.8112.16421

**Comment by timvandermeij** [comment]
IE9 is not supported anymore in PDF.js 2.0, so I'm closing this issue as won't fix.
