### ISSUE TITLE
letter pdf gets printed as continuous image on a4

### ISSUE THREAD

**Issue by DarkoVeberic** [mozilla/pdf.js#4874]
when printing a letter formatted pdf via pdf.js on a a4 printer, the output looks like the pages are concatenated into a very long continuous image which then gets broken up at the a4-size boundaries, ie there is no new-page issued between the original letter pages.

**Comment by yurydelendik** [comment]
Is it still an issue after #7677? Please specify correct configuration OS, browser and PDF.js versions. Thanks.

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs. If the problem remains after the *latest*  `master` branch commits, let us know and we'll reopen. We now render than canvases based on the paper information provided by the PDF file.
