### ISSUE TITLE
release zips should contain minified files

### ISSUE THREAD

**Issue by mgol** [mozilla/pdf.js#4884]
Apart from unminified source files, release zips at http://mozilla.github.io/pdf.js/getting_started/#download should contain minified files as well, preferably in a format `file.js -> file.min.js`. Most frontend packages work that way; it also makes it easier to develop with unminified files & put minified ones into production.

IMO minified files should have verbosity seriously decreased by default as well. This shouldn't affect the Firefox module since it's unminified but log noise on a page where pdf.js is only one of the components is ususally unwelcome, especially in production.

**Comment by Snuffleupagus** [comment]
Given that minified versions of the built `pdf.js`/`pdf.worker.js` files are available through https://github.com/mozilla/pdfjs-dist, this issue probably ought to be closed as fixed now.
