### ISSUE TITLE
1mb - 2mb large single-page engineering plan pdf's consistently crash chrome window when loading

### ISSUE THREAD

**Issue by enunciat** [mozilla/pdf.js#4905]
i see it's been mentioned somewhere in the docs that page size & resolution have an effect on processing time, so this isn't a huge surprise (80cm x 60cm, 600dpi). Just thought I'd mention it. I can't upload the pdf for privacy reasons, unfortunately (and acrobat pro's redaction seems to do funny things to the file). But I'll try again if it would be helpful. 

using chrome 35.0.1916.114 on osx and the pdf.js demo linked to from the github page.

**Comment by timvandermeij** [comment]
Closing since the PDF file is no longer available and many optimizations have been implemented since. There are also other issues that already track large image tiling.
