### ISSUE TITLE
PDF displays as plain white - works in other readers

### ISSUE THREAD

**Issue by jordan-thoms** [mozilla/pdf.js#4913]
Hi, 

I came across this PDF ( https://www.dropbox.com/s/8tpneuaw8xguuyi/hc1tradpdf.pdf ) which is displaying in PDF.js as plain white (but the text layer does contain the text from the document). Apple preview displays it OK.

Any idea what is going on?

**Comment by timvandermeij** [comment]
@CodingFabian @jordan-thoms Is this still an issue with the latest version of Chrome and PDF.js?

**Comment by jordan-thoms** [comment]
This seems to be working fine now.
