### ISSUE TITLE
Rendering bug: line is partly invisible at certain zoom levels (Firefox)

### ISSUE THREAD

**Issue by Lekensteyn** [mozilla/pdf.js#4918]
In at least Firefox 29.0.1 and 30.0, [this PDF][1] is rendered incorrectly.

This picture was taken at zoom level 80%:
![pdf in Firefox](https://cloud.githubusercontent.com/assets/164530/3247263/aed57b60-f182-11e3-99f9-4a3c790753c1.png)

The empty space is supposed to be a straight line. The same bug occurs at other levels including, but not limited to, 25%, 80%, 90%, 150%, 170% and 200%. The bug does not occur at 60%, 100%, 110% and 130% (and others).

 [1]: https://lekensteyn.nl/junk/test.pdf

Affected browser versions: Mozilla Firefox 29.0.1, 30.0
Affected PDF.js versions: 6d330250dadcca8a7a97bafffc7b2650fbd05f2d (the one published in CWS), the one included with above FF and master: bf92ed9c22c9665abc4f04b9d7f9de0578757f93, possibly others.
Not affected: Chromium 35.0.1916.114
Distribution: Arch Linux x86_64

**Comment by timvandermeij** [comment]
@Lekensteyn The link appears to be dead. Do you have a new one, and does the problem still occur with the latest version of PDF.js at https://mozilla.github.io/pdf.js/web/viewer.html and the latest graphics drivers?

**Comment by timvandermeij** [comment]
No response, closing (it's also tracked upstream).
