### ISSUE TITLE
Implement Deflate64 compression

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#4975]
http://arxiv.org/pdf/0704.0739v2.pdf

Last page shows a black square because we do not support Deflate64.

**Comment by Snuffleupagus** [comment]
> http://arxiv.org/pdf/0704.0739v2.pdf

The last page of that document also doesn't render successfully in either Adobe Reader or PDFium (in Google Chrome).

> Last page shows a black square because we do not support Deflate64.

Given that the Deflate64 compression format doesn't seem to be in widespread use (this is the only issue/bug I'm aware of), and that it's a [proprietary format](https://en.wikipedia.org/wiki/DEFLATE#Deflate64/Enhanced_Deflate) where no official specification seem to exist and with generally limit support in various projects, is it meaningful to keep this issue open?

**Comment by timvandermeij** [comment]
Not really. I thought we would see more of it, but I also haven't.
