### ISSUE TITLE
Printing looks different after cleanup

### ISSUE THREAD

**Issue by CodingFabian** [mozilla/pdf.js#5006]
can be at least reproduced with several PDFs on FF 32a on my Mac .

Load the PDF, print (to pdf) - the PDF will look good quite identical.

Reload
Load the same PDF, wait 45 seconds, print (to pdf) - the PDF will look different. In most cases fonts which were bold are no longer bold.

one example: http://www.postgis.us/downloads/postgis21_cheatsheet.pdf

**Comment by SailorMax** [comment]
Evidence: built-in Firefox viewer (looks like modified) has no this problem.
Tested on Firefox 46.0.1 (with built-in viewer 1.3.231)

**Comment by timvandermeij** [comment]
Closing as (most likely) fixed by #7694.
