### ISSUE TITLE
PDF.js viewer does not honor "open to page" settings in PDF

### ISSUE THREAD

**Issue by nibblesnbits** [mozilla/pdf.js#5009]
Many of the documents I would like to display with the PDF.js in my project, when opened in Adobe Reader or other readers, will open directly to a specific page when opened for the first time.  The PDF.js viewer does not seem to honor this.  If someone can give me some direction on where to get started on fixing this, I can do what I can to help.

**Comment by THausherr** [comment]
The link no longer works; here's a PDF (with fake extension) that should open at 75% on page 2.


![zoom-page2 pdf](https://cloud.githubusercontent.com/assets/6665575/18593727/13aad822-7c3d-11e6-9b9d-a07973919461.png)

**Comment by Snuffleupagus** [comment]
Fixed by PR #10334; the feature is currently off by default, set the preference `viewOnLoad = -1` to enable.
