### ISSUE TITLE
Character spacing is too small

### ISSUE THREAD

**Issue by schwartzmike** [mozilla/pdf.js#5027]
Characters are all bunched together throughout this file:
https://d5me67xtse2u5.cloudfront.net/documents/1962.35/OutgoingWireRequest.pdf

Bug posted and screenshot taken using OSX Firefox 30. Looks exactly the same via https://mozilla.github.io/pdf.js/web/viewer.html

Looks fine in Adobe Reader and Chrome Viewer. Looks even worse in OSX Preview (completely garbled characters).

Firefox (ignore the spinner in the middle I think, it was a one time issue):
![pdfjs-rendering](https://cloud.githubusercontent.com/assets/2592353/3469919/f1e7f34a-02b4-11e4-847c-c9a92582ac77.png)

Adobe Reader:
![adobereader-rendering](https://cloud.githubusercontent.com/assets/2592353/3469920/f1e9b77a-02b4-11e4-9cb3-156afddbf403.png)

OSX Preview:
![preview-rendering](https://cloud.githubusercontent.com/assets/2592353/3469921/f1e9da0c-02b4-11e4-884d-ddbdbe2ad2e0.png)

Firebug console output:
PDF d7112575b73945963bab53a586be0 [1.5 - / -] (PDF.js: 0.8.1181)
Warning: AcroForm/XFA is not supported

Note also that upon initial viewing (and when I took the screenshot) I did not get the "Does not support forms, open in another viewer" prompt. That prompt only appeared when I did a reload in order to get the firebug console output. And regardless, other PDFs which have forms at least display properly even if you can't fill them out.

**Comment by timvandermeij** [comment]
Perhaps related to #5084?

**Comment by timvandermeij** [comment]
From the console:

<pre>
downloadable font: head: Bad y dimension in the font bounding box (32767, -32768) (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKwOByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzctUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzctUmVndWxhckdlbmVyaWM3QWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: head: failed to parse table (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKwOByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzctUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzctUmVndWxhckdlbmVyaWM3QWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: rejected by sanitizer (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKwOByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzctUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzctUmVndWxhckdlbmVyaWM3QWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: font load failed (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKwOByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzctUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzctUmVndWxhckdlbmVyaWM3QWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: head: Bad y dimension in the font bounding box (32767, -32768) (font-family: "g_font_3" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKUAByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzAtUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzAtUmVndWxhckdlbmVyaWMwQWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: head: failed to parse table (font-family: "g_font_3" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKUAByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzAtUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzAtUmVndWxhckdlbmVyaWMwQWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: rejected by sanitizer (font-family: "g_font_3" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKUAByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzAtUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzAtUmVndWxhckdlbmVyaWMwQWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
downloadable font: font load failed (font-family: "g_font_3" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKUAByIAAACcAAAA5U9TLzL+4Wd+AAABhAAAAGBjbWFwAAvgNAAAAeQAAAAsaGVhZKsnUVMAAAIQAAAANmhoZWGAAoJ4AAACSAAAACRobXR4AdAAAAAAAmwAAAAIbWF4cAACUAAAAAJ0AAAABm5hbWWHjTmaAAACfAAAAihwb3N0AAMAAAAABKQAAAAgAQAEBAABAQERR2VuZXJpYzAtUmVndWxhcgABAQFBHgoABIgoH4uLHgoABIgoH4uLDAcdBfXg/x0F9eD/HfoKHwEd+gofAQUdAAAAjg8dAAAAkxEdAAAAMx0AAACxEgAEAQERGR4mR2VuZXJpYzAtUmVndWxhckdlbmVyaWMwQWRvYmVJZGVudGl0eQAAAAIAAQAAAAIBAQ0Z/wZmZmaPjxWPjwUO/wHPWRaPjxWPjwUOe5v4PJn3bpmRm7mTBvuIi/iMkfcaiwd7m/g0l/dul52bs5UI+4aL+IaS9xeLCa8K9xwLAAAAAAADAiQB9AAFAAACigK7AAAAjAKKArsAAAHfADEBAgAAAAAGAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAqMjEqAADgAOABHwEfAQBkHwHg/wAAAAAAAAAAAdgCeAAA4AAAAwAAAAEAAwABAAAADAAEACAAAAAEAAQAAQAA4AH//wAA4AD//yAAAAEAAAAAAAEAAAAAEAAAAAAAXw889QAACAAAAAAAngt+JwAAAACeC34nAAB//w//gAAAAAARAAAAAAAAAAAAAQAAgAB//wAA//8AAAAAAAACeAAAAAAAAAAAAAAAAAAAAAIAAAAAAdAAAAAAUAAAAgAAAAAAFAD2AAEAAAAAAAAAEAAAAAEAAAAAAAEAEwAQAAEAAAAAAAIABwAjAAEAAAAAAAMACAAqAAEAAAAAAAQAEwAyAAEAAAAAAAUADABFAAEAAAAAAAYAAABRAAEAAAAAAAcABwBRAAEAAAAAAAgABwBYAAEAAAAAAAkABwBfAAMAAQQJAAAAIABmAAMAAQQJAAEAJgCGAAMAAQQJAAIADgCsAAMAAQQJAAMAEAC6AAMAAQQJAAQAJgDKAAMAAQQJAAUAGADwAAMAAQQJAAYAAAEIAAMAAQQJAAcADgEIAAMAAQQJAAgADgEWAAMAAQQJAAkADgEkT3JpZ2luYWwgbGljZW5jZUJJRERYUStDYWxpYnJpLEJvbGRVbmtub3dudW5pcXVlSURCSUREWFErQ2FsaWJyaSxCb2xkVmVyc2lvbiAwLjExVW5rbm93blVua25vd25Vbmtub3duAE8AcgBpAGcAaQBuAGEAbAAgAGwAaQBjAGUAbgBjAGUAQgBJAEQARABYAFEAKwBDAGEAbABpAGIAcgBpACwAQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABCAEkARABEAFgAUQArAEMAYQBsAGkAYgByAGkALABCAG8AbABkAFYAZQByAHMAaQBvAG4AIAAwAC4AMQAxAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= OutgoingWireRequest.pdf
</pre>

These sanitizer errors might indicate the problem.
