### ISSUE TITLE
Over stretched font when the zoom level is 100%

### ISSUE THREAD

**Issue by rathinivethan** [mozilla/pdf.js#5028]
PDFJS Verison - 0.8.0
I have a PDF in which font looks good in all zoom levels except when zoom level is 100%.
The letters 'n' and 'u' looks like stretched out.

Note: This issue occurs only with 100% zoom

http://jmp.sh/Bc0PVes
http://jmp.sh/pT1Erlm

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue, and secondly the fact that it seems specific to a *particular* platform/browser (and possibly even graphics driver), it's probably not meaningful to keep this open since it unfortunately doesn't look like an actionable PDF.js issue.
