### ISSUE TITLE
Background color is not appearing on Chrome Version 35.0.1916.153 m roatate clock wise 

### ISSUE THREAD

**Issue by miltonpereira** [mozilla/pdf.js#5043]
ON google chrome file is not showing background on pdf.js

![2014-07-14_2354_001](https://cloud.githubusercontent.com/assets/8161117/3575013/2f698ecc-0b84-11e4-9d2d-35ac9e9fbfc5.png) chrome version with blank pdf screen

![2014-07-14_2354](https://cloud.githubusercontent.com/assets/8161117/3575014/2f70e596-0b84-11e4-94e5-c6212ed148b0.png) ie 11 version proper pdf screen

it works fine when rotate counterclockwise on chrome Version 35.0.1916.153 m
![2014-07-15_0005](https://cloud.githubusercontent.com/assets/8161117/3575149/a9761e3c-0b85-11e4-9003-0b735af6ca3b.png)

**Comment by TrashbinPornoDolske** [comment]
Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by miltonpereira** [comment]
Hi @Rob--W and @timvandermeij  can you please confirm if following bug is related to this ticket?
Page # 2 appears yellow with blank images
http://screencast.com/t/tLwv45FAE05 

Here is the file:
https://s3.amazonaws.com/uploads.hipchat.com/23322/806699/FObJrdOttNFZeQQ/1142324.pdf

**Comment by timvandermeij** [comment]
Closing since the upstream bug is fixed.
