### ISSUE TITLE
PDF rendering issue (incorrect in FF30; correct in FF24)

### ISSUE THREAD

**Issue by hochhaus** [mozilla/pdf.js#5044]
I have an example PDF which renders correctly in FF24, but incorrectly in FF30.

http://hochhaus.us/HeadBodyFoot.pdf (attached [HeadBodyFoot.pdf](https://github.com/mozilla/pdf.js/files/52162/HeadBodyFoot.pdf) )

This PDF contains three logical entities (a header, a body and a footer). When rendered in Adobe Reader, Chrome's built in reader, PDF.js in FF24 and Apple Preview all three entities are visible. For example:

![correct](https://cloud.githubusercontent.com/assets/5508784/3576785/c32c2eb0-0b95-11e4-92be-87eb091d4fa5.png)

However, when rendered from PDF.js in FF30 only the footer is visible. For example:

![incorrect](https://cloud.githubusercontent.com/assets/5508784/3576876/e9c66e36-0b96-11e4-9a94-59c4fcaac77a.png)

Without knowing anything about PDF.js my guess would be that this has something to do with how different "regions" of the PDF are cropped. Is this the type of issue that the PDF.js team is interested in resolving? If so, what can I do to provide more helpful debugging information?

**Comment by yurydelendik** [comment]
@hochhaus are you the author of the HeadBodyFoot.pdf and can we use it in our test suite?

**Comment by hochhaus** [comment]
@yurydelendik Yes, I am the author. Yes, you can use it in the test suite. Thanks for your work on this issue.
