### ISSUE TITLE
Large PDF is causing rendering problems on various browsers

### ISSUE THREAD

**Issue by xadhatter** [mozilla/pdf.js#5067]
I have fairly large PDF with many embedded images that is causing problems on various browsers:

    Chrome, tab crashes because of too much memory use
    IE, DOM7000 errors occur and rendering stops
    Firefox, NS_ERROR_NOT_AVAILABLE errors occur and rendering stops

Here is the PDF causing the issues:
https://www.dropbox.com/s/hg2evr59bvuo2va/LargeManual.pdf

**Comment by timvandermeij** [comment]
The performance of this PDF file is fine with the latest PDF.js version after the recent fixes, so I'm closing this as fixed.
