### ISSUE TITLE
PDF not rendering the overlay in ios only

### ISSUE THREAD

**Issue by completeajay** [mozilla/pdf.js#5094]
I have this issue for so long that a few PDF's i have do not show up correctly in ios (iphone , ipad or ios browsers)  and it works fine in android and IE and chrome. We do have overlay in these PDFs .

Can someone please help me onto it.

Attached is the PDF to take a look at.

Ajay

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue, and second of all that none of the links work any more, and finally the general lack of details provided; is it still meaningful to keep this issue open?
