### ISSUE TITLE
Unable to select and copy text

### ISSUE THREAD

**Issue by jbrown0180** [mozilla/pdf.js#5098]
Hello,

I am unable to select part of a PDF document.  Please find the download link:

http://www.files.com/set/53d7b88365ba0

Environment:

PDF.js - 1.0.68
Browser: Chrome (latest) and Firefox version 30

I have checked with the latest version of PDF.js (1.0.277) and beta version (1.0.473) and the problem persists.  Here is the screen shot showing the problem:

![pdfselection](https://cloud.githubusercontent.com/assets/8300548/3736960/6a7f1478-1732-11e4-9456-0ef79a242f7f.png)

The DIV positions when seen in Chrome's browser inspector, shows there is an overlap in the positions of the generated DIVs.

This issue is affecting copy/paste of the text from the PDF file as well.

Thanks.

**Comment by timvandermeij** [comment]
Closing as fixed in the latest development version.
