### ISSUE TITLE
Multiple PDF documents in one HTML page

### ISSUE THREAD

**Issue by tmarrinan** [mozilla/pdf.js#5148]
I try to render multiple PDF documents in one HTML page, but the last loaded document seems to interfere with the others. The fonts / encodings of previously loaded documents all change when they re-render (next page, resize document, etc.).

**Comment by danlester** [comment]
@tmarrinan Thanks for the suggestion. Were you able to submit it to the main pdf.js project as a pull request in the end? I'd love to borrow your solution rather than making my own fork and then submitting it myself. Thank you!

**Comment by tmarrinan** [comment]
I just applied the patch to a newly forked version of pdf.js, and submitted the pull request. Hopefully this gets accepted and merged into the main project. Otherwise, you can check it out at https://github.com/tmarrinan/pdf.js

**Comment by danlester** [comment]
@tmarrinan Thank you. I think it's an important issue for the project especially if it seems to be the only problem preventing multiple PDF views on the same page.

**Comment by timvandermeij** [comment]
Fixed by #6571.

**Comment by lakuri** [comment]
> I've put a live demo up at http://tmarrinan.bitbucket.org/pdfjs-test/original.html
> 
> Example to cause render error:
> 
> 1. Load PDF 1 --> can change pages with no error
> 2. Load PDF 2 --> can change pages with no error
> 3. Change page on PDF 1 --> render error!
> 4. Reload PDF 1 --> renders correctly again (and can change pages with no error)
> 5. Change page on PDF 2 --> render error!
> 
> Whichever PDF document is last loaded is the one that renders correctly as you go to previous or next page. All others (in this example only one other PDF) will have strange font or text encoding.

@tmarrinan Do you still have the demo code? The bitbucket doesn't seem to exist.
