### ISSUE TITLE
PDF.js on Chrome with Win 7 Fails to do Subpixel Anti-Aliasing

### ISSUE THREAD

**Issue by speedplane** [mozilla/pdf.js#5196]
Continued from #4252.

Subpixel font rendering does not work in Chrome for the tracemonkey document example.  In the image below, pdf.js in Chrome renders the document on top and adobe renders it directly below.  Notice that there are tiny artifacts in the pdf.js around the fonts (it's hard to tell because of image compression in the screenshot).  This becomes more obvious when you zoom in (see image further down).

<img src=http://i.imgur.com/jSDL6LM.png>

**Zoomed In (pdf.js on top, adobe reader on bottom):**

Notice how the image in adobe reader is not just black and white, but is also red and blue.  That's the subpixel antialiasing, which makes documents much easier to read.

<img src=http://i.imgur.com/MOuqVbB.png>

**Comment by timvandermeij** [comment]
Is this still an issue with the latest version of Chrome for you? https://code.google.com/p/chromium/issues/detail?id=7508#c83 indicates that it _might_ work.

**Comment by timvandermeij** [comment]
@speedplane Is this still an issue with the latest version of Chrome for you? https://code.google.com/p/chromium/issues/detail?id=7508#c83 indicates that it _might_ work.

**Comment by speedplane** [comment]
Yup it works now, feel free to close.

Michael Sander
michael.sander@gmail.com
607-227-9859
