### ISSUE TITLE
PDF.js on IE9 with Win 7 Fails to do Subpixel Anti-Aliasing

### ISSUE THREAD

**Issue by speedplane** [mozilla/pdf.js#5197]
Continued from #4252 (see also #5196 for Chrome issue).

Subpixel font rendering does not work in IE 9 for the tracemonkey document example. In the image below, pdf.js in IE9 renders the document with no subpixel antialiasing. If there were sub-pixel anti-aliasing, you would see pixels rendered in blue and red around the edges of the font.

<img src=http://i.imgur.com/663TTH3.png>

**Comment by timvandermeij** [comment]
IE9 is not supported anymore in PDF.js 2.0, so I'm closing this issue as won't fix.
