### ISSUE TITLE
Ability to highlight multiple phrases simultaniously

### ISSUE THREAD

**Issue by mainseq** [mozilla/pdf.js#5220]
When our customers search documents we need the ability to show each search term highlighted. I could not find a way to do that using the current viewer. I modified viewer.js to accomplish this. Not super familiar with all the ins and outs of the code and was wondering if someone wanted to clean up my changes. The goal would be to pass the search terms through the URL as a single parameter.

Basically pull an array containing each search term/phrase to highlight.

Link to modified script:
http://office.pcrecruiter.com/viewer.js

**Comment by ananyaojha** [comment]
Does your code search multiple phrases too?

**Comment by HKWhyIP** [comment]
I tried mainseq's PDF.js (https://github.com/mainseq/pdf.js) and have "pdfjs/web/viewer.html?wl=trace%20time" in the URL but cannot see the highlights.  Did I do something wrong?

**Comment by timvandermeij** [comment]
Closing as fixed by #5579. I will open a separate issue to track a UI for this.
