### ISSUE TITLE
[Android] It's not possible to hide Firefox's address bar

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#5222]
Firefox for Android has the great ability to hide its address bar when the document contents are scrolled down. However, this does not work in pdf.js: When flipping the document with the finger, then only the pdf contents move, but not the entire view area, so Firefox does not recognize to hide the address bar.
On a screen so small, only 67% of its height remain for reading, so this can be quite annoying.

Screenshot on Samsung Galaxy S II:
![screenshot_2014-08-21-09-47-06](https://cloud.githubusercontent.com/assets/4624768/3993259/15ebdede-290a-11e4-89ec-3a738ebce568.png)

**Comment by Snuffleupagus** [comment]
Given that, as mentioned in https://github.com/mozilla/pdf.js/issues/5222#issuecomment-52913345, the demo viewer was/is created *primarily* for desktop environments (since it's used for the built-in Firefox PDF Viewer); closing as WONTFIX for now.
