### ISSUE TITLE
[Android] Wrong entry in the list of zoom values

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#5223]
On the desktop Firefox, there's a horizontal line between "Seitenbreite" (page width) and the smallest numerical zoom value ("50%"). On android, however, a float number is shown instead. Upon selecting it, nothing happens.

![screenshot_2014-08-21-09-51-54](https://cloud.githubusercontent.com/assets/4624768/3993414/5d48923e-290c-11e4-8352-6412667f9d57.png)

**Comment by timvandermeij** [comment]
I just tested this again. Closing as fixed, most likely by #7792.

**Comment by Snuffleupagus** [comment]
> Closing as fixed, most likely by #7792.

... or perhaps PR #7242.
