### ISSUE TITLE
[Android] Text layer font is visible during text selection

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#5225]
The text layer is not hidden and aligns badly under android.

![screenshot_2014-08-21-11-19-08](https://cloud.githubusercontent.com/assets/4624768/3994046/ad5bae70-2914-11e4-87ab-d470bfe014f0.png)

**Comment by timvandermeij** [comment]
This is working as expected now using Android 6.0.1 on a Nexus 6 with Firefox 46.0.1. The text layer is not visible anymore during text selection, probably due to recent text selection fixes. Closing as fixed.
