### ISSUE TITLE
PDF.js displays penguins where there should not be any

### ISSUE THREAD

**Issue by mfiedler** [mozilla/pdf.js#5256]
Viewing [1] with PDF.js results in a lot of penguins where there really shouldn't be any :) ‒ see the following screenshot PDF.js vs. Evince:

![screenshot from 2014-09-02 12 05 36](https://cloud.githubusercontent.com/assets/116578/4126124/4d8ff748-32e8-11e4-9b45-ff89bc4a60cd.png)

  [1] http://www.schaeffer-ag.de/fileadmin/user_upload/Downloads/Handbuecher_Datenblaetter/PDFs/Housingassemblymanual.pdf on page 4

PDF.js 1.0.277 (also reproducible with http://mozilla.github.io/pdf.js/web/viewer.html)
Debian 7.6 Wheezy
Iceweasel 24.7.0

**Comment by chisophugis** [comment]
I've been running into this a lot lately with Texas Instruments literature. Page 62 of http://www.ti.com/lit/ug/slau131j/slau131j.pdf is particularly full of them, but it seems that diagrams/figures in a lot of TI literature end up with these (but not the main text).

Is there any possibility for fixing this besides changes to system fonts?

**Comment by Rob--W** [comment]
When I extract the relevant font from @chisophugis's PDF (https://robwu.nl/pdfjs/issue5256/g_font_3.otf) and open it with FontForge, I observe that the space is replaced with `.notdef`, which in turn does not map to any glyph. When I look at the PDF in the original report, I see the same situation.

![fonttable](https://cloud.githubusercontent.com/assets/1365071/6541070/a30047d8-c4be-11e4-95b8-6b62aec0b428.png)

@yurydelendik Is "fixing" this bug by ignoring a space->notdef mapping when notdef is not defined acceptable?

**Comment by timvandermeij** [comment]
@Rob--W Are you still able to reproduce this? I just tested this again on Arch Linux and while I used to see weird characters before, they are now gone and the rendering looks exactly like Evince for me.

**Comment by Rob--W** [comment]
The boxes started disappearing from the PDF (i.e. rendering as expected) in Chrome 38. I did a bisect and ended in the following range:
https://chromium.googlesource.com/chromium/src/+log/acc18a83656e79649ad74ed44cb9d6e9a7df0049..70ff25dc41a6a3c06e1b18ead3af394a23861b95
There is a Blink roll in this range: https://chromium.googlesource.com/chromium/src/+log/58e3a54618690d0b722e33596c7e381c10e3bcf2..7adbf75bf35e1e62ae1986d88c8d6f1a053c1ffc

The original reporter used Firefox (Iceweasel), so I can't comment on that (since we never managed to reproduce the issue in Firefox).

**Comment by SamyCookie** [comment]
I don't see any weird glyph with Iceweasel 44, PDF.js 1.1.551 and Debian Strech (testing) 64bits.

**Comment by mfiedler** [comment]
I can still reproduce this with Iceweasel 38.5.0, current PDF.js from http://mozilla.github.io/pdf.js/web/viewer.html and Debian 8.3 Jessie x86, seeing no penguins any more but other glyphs that should not be there. I currently do not have access to another Linux box with more recent software for additional testing.

**Comment by mfiedler** [comment]
Also reproducible using Google Chrome 48.0.2564.82, current PDF.js from http://mozilla.github.io/pdf.js/web/viewer.html and Debian 8.3 Jessie x86.

**Comment by SamyCookie** [comment]
I cannot reproduce that issue with Debian Jessie 64bits, pdf.js 1.4.91 version with both Iceweasel 44 and Chromium 48.
It does not seem to be related to the browser or the pdf.js version. I think it related to the system, maybe to graphic drivers.

**Comment by yurydelendik** [comment]
... or version of FreeType installed on the system

**Comment by SamyCookie** [comment]
2.5.2-3+deb8u1 version for FreeType on my Debian Jessie 64 computer (and no issue visible).
@mfiedler What is yours ?

**Comment by mfiedler** [comment]
Same here:
`$ apt-cache show libfreetype6`
`Version: 2.5.2-3+deb8u1`
