### ISSUE TITLE
Rendering flipped / upside down on Chrome dev build

### ISSUE THREAD

**Issue by rauchg** [mozilla/pdf.js#5273]
Rendering flipped and scaling problems
![](https://cldup.com/OKm6FDr10K.png)

![image](https://cloud.githubusercontent.com/assets/13041/4175152/b9246972-35c1-11e4-80e5-c808bee6de41.png)

**Comment by biomorgoth** [comment]
This issue is still happening, as @deweydb says, it happens when reloading the PDF (i think he meant re-rendering the page) while it was already loading. In my case it also happens with an window.onresize event, which will fire several times quickly (e.g. switching fullscreen). One piece of information that i found was that the issue seems to dissapear if the intent parameter on page.render() is set to "print".

**Comment by timvandermeij** [comment]
I'm not sure if there is anything we can do here, but let's reopen.

**Comment by expede** [comment]
Hi everyone :smile: My team is seeing this issue consistently when we try to render multiple pages in succession. We see it on Chrome, Firefox and Safari (haven't tried the IEs). All but the last page become flipped in both the horizontal and vertical dimensions (like in the description screenshot). If we add another page afterwards, the rendering corrects itself.

**Comment by yurydelendik** [comment]
> My team is seeing this issue consistently when we try to render multiple pages in succession. 

@expede it's not related to the subject, your custom project shall not utilize the same canvas to run multiple rendering at the same time and/or wait for rendering to complete before next rendering is started. See also https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html example to avoid that.

**Comment by timvandermeij** [comment]
@rauchg @yurydelendik Is this still an issue with the most recent Chrome build?

**Comment by yurydelendik** [comment]
not for me

**Comment by yurydelendik** [comment]
let's close it as wfm.

**Comment by reinerluke** [comment]
Can confirm

> @expede it's not related to the subject, your custom project shall not utilize the same canvas to run multiple rendering at the same time and/or shall wait for rendering to complete before next rendering is started. See also https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html example to avoid that.

It happened to me because somehow my function which renders the PDF into the canvas triggered twice. 
After I fixed it, it sloved the problem too.

**Comment by right4mat** [comment]
displaying pages quickly in succession messes with the rendering

**Comment by foghorn88** [comment]
We experienced this upside down / inverted text with some multi page documents. I was able to fix it by setting the viewers renderer property from "svg" to "canvas". I don't know why this worked but it did.

**Comment by right4mat** [comment]
Cheers! Will try that now

**Comment by bundsol** [comment]
Everybody seems to have a different reason why they were getting inverted renderings, but in my case the retrieved viewport had `NaN` in both `width` and `height`, so I had to do the following,

    var viewport = page.getViewport(   options  );    
    const width= viewport.viewBox[2];    
    const height= viewport.viewBox[3];    
    viewport.width = width ;
    viewport.height = height ;

**Comment by diogocanelas** [comment]
It's happening to me with the current version. Pdf.js rotates my pdf both vertically and horizontally. I tried all the possible solutions above but none worked. Any idea how to solve this problem? It's been happening for years but there's still no efficient solution...

**Comment by AYGTX** [comment]
let scale = (canvas.width / page.view[2]);
        **--> viewport = page.getViewport({scale: scale});**
        var ctx = canvas.getContext('2d');
adding this line before renderContext seems to solve the issue for me
