### ISSUE TITLE
Many symbols in the printed PDF look different from the viewed PDF

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#5279]
The symbols (math symbols and list item images) in the following page are rendered correctly in Firefox and the print preview, but incorrectly on a printed page (e.g. look at the items in the list at "Notation"). Further, the kerning is completely off (some letters are almost glued to each other).

https://robwu.nl/pdfjs/multi-precision-arithmetic.pdf

In the screenshot below, I've shown three pages. The top-right corner shows how the PDF is supposed to look like. Below that page, there are two bad prints (left = Windows 7; right = Linux).

![print3x-good win7 linux](https://cloud.githubusercontent.com/assets/1365071/4187303/b8985eac-3768-11e4-89cb-ee45c8fdc5a8.jpg)

**Comment by amirkdv** [comment]
I have been consistently hitting the same issue (effects are identical to what @Rob--W posted). Is it still reproducible by others or should I collect more debug info?

p.s: is this somehow related to #5006? I can reproduce the example there on Linux (FF 45.0.2). I also took a file that would print improperly on Windows (as in this issue) and reproduced the same (in fact, worse) problems on Linux (by procedure as in #5006).

**Comment by timvandermeij** [comment]
Yes, those issues are related, but unfortunately there is still no real indication of why this is happening. I can also reproduce it 100% of the time on Arch Linux, even with the default Tracemonkey paper.

**Comment by timvandermeij** [comment]
Closing as fixed by #7694.
