### ISSUE TITLE
PDF has no text in Chrome

### ISSUE THREAD

**Issue by smber1** [mozilla/pdf.js#5297]
This document does not show the text in Chrome..

Works fine in Firefox and Safari.

Goto http://mozilla.github.io/pdf.js/web/viewer.html

Open the following PDF... (removed)

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue (from 2014), and secondly that it's apparently limited to a particular platform/browser, it's probably not meaningful to keep this issue open.
