### ISSUE TITLE
PDF not rendered correct in FF and not rendered in Chrome at all

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#5298]
If you open this PDF file directly in FF (with the FF PDF plugin) the file is not correct rendered..

http://docdroid.net/hmn6

The yellow markup is either on top of the text or the text is not rendered at all

If the PDF is rendered on a webpage with pdf.js the preview looks the same and if the file is rendered in Chrome no preveiw is rendered at all

**Comment by timvandermeij** [comment]
Closing since the file is no longer available and lots of font/annotation fixes have been applied that may have solved the issue.
