### ISSUE TITLE
Should worker_loader.js also load compatibility.js?

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#5316]
I discovered that with new version of PhantomJS and when I am running PDF.js tests inside it, Worker support is detected and it tries to use it, but then it fails because of the lack of `Function.prototype.bind`. If I set `PDFJS.disableWorker` explicitly, then everything works because I load `compatibility.js` in the main thread before PDF.js. So I would suggest that `compatibility.js` should be added to the list of fails loaded by `worker_loader.js`.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #8102.
