### ISSUE TITLE
Implement streaming using responseType=stream (Streams API)

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#5319]
We should use the Streams API instead of range requests when it becomes available. A Firefox-specific patch to support the Streams API was added here https://github.com/mozilla/pdf.js/pull/5263.

When a concrete implementation of the Streams API appears in other browsers (e.g. Chrome), then we should support that too. Here are some relevant bugs on Chromium's issue tracker:
- https://crbug.com/401396 Add a response type for ReadableStream to XMLHttpRequest
- https://crbug.com/240603 Streams API

**Comment by timvandermeij** [comment]
Is this still relevant? I think we have streams API support now, at least through a polyfill if I'm not mistaken.

**Comment by Rob--W** [comment]
Fixed by #8768.
