### ISSUE TITLE
PDF rendering exception in IOS 8 safari

### ISSUE THREAD

**Issue by spolitakis** [mozilla/pdf.js#5341]
Some pages are missing graphics and never remove the spinner.

Here is a doc that throws the exception, I have others too. 

http://pandexio.s3.amazonaws.com/widgets-1.1.3/viewer/sample/transforming-collaboration-with-social-tools.pdf

Page 12 will blow up, I've tracked it down to line 957 in canvas.js
`this.current.activeSMask = null;`
The exception is "TypeError: Attempted to assign to readonly property."

I'm using an iphone 5 with IOS 8, PDFJS Build 1.0.712 

the good news is that there is a vast speed improvement in pdf rendering over IOS 7

**Comment by jacksonrayhamilton** [comment]
We encountered this issue recently. Running the PDF.js codebase through [webkit-assign](https://github.com/StoryCloud/webkit-assign) fixed it for us.

**Comment by yurydelendik** [comment]
> Running the PDF.js codebase through webkit-assign fixed it for us.

Interesting... so people know that it's the issue with the browser and the vendor does not want to fix it? How slow the execution of the PDF.js with webkit-assign code hacks?

Marking as beginners bug to add a workaround to replace Object.create with the [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FObject%2Fcreate#Polyfill) for affected versions of webkit.

**Comment by jacksonrayhamilton** [comment]
There is [a claim](https://bugs.webkit.org/show_bug.cgi?id=138038#c21) that it's been fixed in iOS 9. I haven't benchmarked the performance difference yet.

**Comment by jacksonrayhamilton** [comment]
In our application, I measured the time from calling `PDFJS.getDocument()` to its `.then()` callback (on a local network with a ~7MB PDF), and furthermore the time elapsed from that call to `PDFJS.getDocument()` and the call to the `onAfterDraw` event on an instance of `PDFJS.PDFViewer`. The PDF has a lot of images in it. I tested with and without webkit-assign applied to all components of PDF.js v1.1.469, 5 times each. Here are the results:

Test harness (the rest of the code is proprietary):

```js
const time = Date.now();
PDFJS.getDocument({
    url: url
})
    .then(function (pdfDocument) {
        console.log('loaded document', Date.now() - time);
        return pdfViewer.setDocument(pdfDocument);
    })
    .then(function () {
        addPageHook(pdfViewer, 'onAfterDraw', function () {
            console.log('onAfterDraw', Date.now() - time);
        });
    });
```

Results:

```
iPod touch model no. MGG32LL/A

Mozilla/5.0 (iPod touch; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4

pdfViewer.currentScale = 0.3496168582375479

with webkit-assign

loaded document 6303
onAfterDraw 29838
loaded document 5090
onAfterDraw 23751
loaded document 4776
onAfterDraw 18141
loaded document 4191
onAfterDraw 22724
loaded document 4088
onAfterDraw 21335

without webkit-assign

loaded document 2640
onAfterDraw 20145
loaded document 5138
onAfterDraw 20468
loaded document 3284
onAfterDraw 19717
loaded document 2566
onAfterDraw 20325
loaded document 3535
onAfterDraw 20270
```

From this simple benchmark, there is not consistently a large difference in load time.

**Comment by yurydelendik** [comment]
I think we can safely closing this one as won't fix. IOS8 is below than 3% (per https://developer.apple.com/support/app-store/)
