### ISSUE TITLE
Safari and Chrome run out of memory when quickly scrolling through large PDFs

### ISSUE THREAD

**Issue by nibblesnbits** [mozilla/pdf.js#5342]
When quickly scrolling through large PDFs (over 100 pages of text), both Safari and Chrome are quitting from a an excessive memory warning.  I've captured the crash reports, which are obviously rather lengthy.  Should I post them here or is there somewhere I should send it?

**Comment by samarpanB** [comment]
Hello guys,
We are also having the same issue on iOS (iphone 5, iphone 6, etc.). The app crashes while reading through a pdf rendered using pdfjs. It happens more frequently with big pdfs, in terms of file size or page numbers both. Also while zooming or direct to a specific page navigation.
Our app is using ionic framework. It works just fine on android. We can see memory shooting up while profiling on android through chrome debugger. But it doesn't crash there. However, it crashes on iOS intermittently.
I don't see any update to above issue, so I am just curious was it ever resolved ?
Any help will be really appreciated.

**Comment by yurydelendik** [comment]
@samarpanB try to use mobile-viewer from the examples and see if the same issue exists.

**Comment by drblmb** [comment]
I am seeing this same exact issue on my ipad - ios 9.3.5.  Using inAppBrowser, scrolling quickly, out of memory errors.  anyone else still seeing this?  Is there an update?

**Comment by Band-Aid** [comment]
OOM also happening when you pinch-in pinch-out on files in landscape mode

**Comment by drblmb** [comment]
The same issue exists in IOS 10.0.2 GM and 10.1 Beta.  This needs to be fixed!

**Comment by Band-Aid** [comment]
Hello folks, Any updates?

**Comment by drblmb** [comment]
Same problem still exists.  Just have to live with it until Apple fixes the problem.  I created a 30-page plain-text PDF with "This is a text PDF" line over and over.  Even this PDF will crash if you scroll up and down quickly.

**Comment by saleo** [comment]
the same problem reported from my iphone users, not sure whats exactly the iOS version but maybe more than one iOS version since several user reported.

**Comment by Band-Aid** [comment]
im not sure if this is a problem we need to wait for Apple to fix. Other libraries that render pdf to html don't crash (not saying they are better or have any plans to use them) 
Just saying There's got to be a way to improve how pdf.js handles cached memory :)

**Comment by disist** [comment]
Hi guys, 
We also have the same problem, especially when we scrolling and rotate device in that time

**Comment by varunmaker** [comment]
At least until this issue gets fixed, is their any recommendation on how to know when the app is about to run out of memory and kill the viewer, so at least the app doesn't crash?

**Comment by timvandermeij** [comment]
Closing since this should be fixed by #11106 and other performance optimizations that were merged since this issue was opened.
