### ISSUE TITLE
Strongly pixelated pages in PDF

### ISSUE THREAD

**Issue by deepj** [mozilla/pdf.js#5354]
**PDF document**: http://apple.servispardubice.cz/images/quadro_srpen2014.pdf
**Versions**: Firefox 33 beta, pdf.js 1.0.837
**OS**: Mac OS X 10.9.5

**Console output**:

None

**Comment by automatedbugreportingfacility** [comment]
> Here's another one (page 20 for example): https://www.ideals.illinois.edu/bitstream/handle/2142/25816/ellison-rosu-2011-tr-b.pdf?sequence=4. This seems to be a regression as this wasn't the case before.

This is actually a different issue, regressed by #4834 -- you may want to open a separate ticket for it. In this bug, drawnHeight is around 9000. Bumping MAX_GROUP_SIZE to 16384 makes it look okay, but I have no idea if it's a desired fix.

**Comment by deepj** [comment]
Hello, any progress in this issue?
