### ISSUE TITLE
Text layer moves up during search

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#5355]
1. Visit the following PDF (http://movelex.hu/fenyoapa/tori_6_tk_webre.pdf_150.pdf) with the text layer enabled, e.g. using the URL parameter:`http://movelex.hu/fenyoapa/tori_6_tk_webre.pdf_150.pdf#textLayer=visible`
2. Look at the text below the top-left image (looks all right).  
 ![pdfjs-textlayer](https://cloud.githubusercontent.com/assets/1365071/4435261/1f2740e2-473c-11e4-8df9-c310e84dfd31.png)
3. Use the search box and search for "pesti".
4. Look at the text below the top-left image, and observe that the text layer has shifted up.  
  ![pdfjs-textlayer-search](https://cloud.githubusercontent.com/assets/1365071/4435264/2a40db96-473c-11e4-85ff-4103564edda8.png)

I've found this bug and PDF at https://stackoverflow.com/questions/25922247/how-to-fix-pdf-js-find-highlight-error-or-what-causes-it.

**Comment by Hengjie** [comment]
Perhaps we should prevent an element to be added if they exist outside of the textLayer's dimensions.
