### ISSUE TITLE
Type 6 shadings with edge connections are not displayed correctly

### ISSUE THREAD

**Issue by ben9ml** [mozilla/pdf.js#5357]
Type 6 shadings with edge connections do not render properly.

The poppler bug reported here includes a PDF attachment which illustrates the problem:
https://bugs.freedesktop.org/show_bug.cgi?id=84465

The first and second pages should appear identical, but the shared edge flags used in the object on the second page cause the shading to be incorrectly displayed.

**Comment by automatedbugreportingfacility** [comment]
There are minor discrepancies comparing to Acrobat Adobe Reader, but the first and second pages are displayed identically in the latest version, so this issue can be closed.

**Comment by timvandermeij** [comment]
This is indeed fixed. Luckily I don't even see any discrepancies at all comparing to Adobe Acrobat DC 2015. Thanks for letting us know that this is fixed.
