### ISSUE TITLE
Text layer displaced

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#5358]
Sample: http://movelex.hu/fenyoapa/tori_6_tk_webre.pdf_150.pdf

Visualization of text layer (without canvas):  
![pdfjs-snippet-textlayer](https://cloud.githubusercontent.com/assets/1365071/4448764/88f8b1d8-4816-11e4-9d75-ec00ee3a4c58.png)

With canvas:  
![pdfjs-snippet-both](https://cloud.githubusercontent.com/assets/1365071/4448797/bfe4e270-4816-11e4-88a3-2b252dabaf39.png)

Note that there is a line in the middle of the screenshots (=the bottom-right corner of the PDF) that is incorrectly shifted to the right.

**Comment by timvandermeij** [comment]
@Rob--W This appears to have been fixed in the meantime. Could you recheck? The text shifted to the right is not visible for me anymore.

**Comment by Rob--W** [comment]
It's no longer at the right, but at the left:
![pdfjspink](https://cloud.githubusercontent.com/assets/1365071/10984059/222d7252-8417-11e5-8254-0cf62c3ad1f2.png)

(to get this picture, add `visibility:hidden` to `.canvasWrapper` and `color:red` to `.textLayer > div`.)

**Comment by yurydelendik** [comment]
wfm (on Mac OSX)

@Rob--W can you also specify on which platform you see these results?

**Comment by Rob--W** [comment]
Actually, it is fine now. I was testing on an old branch.

This bug is fixed by fa46b73c47a84823056492c33124e3e8b5c31f86.
