### ISSUE TITLE
FF 31+ is not able to select/copy text in some pdfs

### ISSUE THREAD

**Issue by mavink** [mozilla/pdf.js#5370]
Thanks very much for the quick reply. I am creating a new issue because I cannot reopen an issue closed by a moderator (http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github).

This is a follow up to issue https://github.com/mozilla/pdf.js/issues/5345

After a lot of sweat I have been able to create a sample document, free of personal information, which exhibits the problem. 

I have uploaded the file to https://nfil.es/SEjH5o/ and http://wikisend.com/download/885274/2.pdf (Couldn't upload to github as it allows only images). It contains the following text only - "a 80.04". If you want me to upload it elsewhere please let me know.

In the file in FF30 and below one can select any text (Tested on Firefox portable 29, 30 and 31 from firefox-usb.com). However in FF31+ one can select only the letter 'a'. The number cannot be selected or copied. 

Would be glad to be of further assistance. Hopefully this issue gets resolved at the earliest. And sorry for confusing it with protection being implemented in pdf.js!

**Comment by Snuffleupagus** [comment]
Given that this is an issue with the PDF file itself and *not* with PDF.js, as outlined in https://github.com/mozilla/pdf.js/issues/5370#issuecomment-64707701, I'm closing this issue as invalid.
