### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by xerofdv** [mozilla/pdf.js#5392]
in firefox 32.0.3 with PDf.js 1.0.277

pictures are rendered but text is transparent (existent but not appearing), I can select and paste it elsewhere but i cannot view it within the viewer in the browser

**Comment by yurydelendik** [comment]
Multiple ATI graphics driver bugs were fixed (e.g. #5986). It shall be fixed after graphics driver and Firefox update.

Please provide more details including screenshot and link to the PDF to re-open the issue.
