### ISSUE TITLE
Extension is not built correctly when git is missing from PATH

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#5403]
As I was building extensions (Windows 7, "node make firefox") to bisect #5400, I noticed that when "git" is not an environmental variable, a broken extension is generated due to following code in pdf.js and pdf.worker.js:

> PDFJS.build = ''git' is not recognized as an internal or external command,
> operable program or batch file.
> ';

With this string fixed, the extension worked alright. Would it be possible to fall back to some valid string for "PDFJS.build" if git is missing from PATH?

**Comment by Snuffleupagus** [comment]
Given that the Firefox addon was removed in PR #9566, this issue can probably be closed now.
