### ISSUE TITLE
layered images are all displaying incorrectly

### ISSUE THREAD

**Issue by pleasantBailey** [mozilla/pdf.js#5410]
I've created a series of brochures for my company, which includes a large number of images, often layered over each other for visual interest. In every other browser, and in Acrobat Reader, these images are displaying perfectly well, but in Firefox, the following issues arise:
- images display as if they have been set as multiply transparency (that is, the closer to white a colour is, the more transparent it is, with black being perfectly opaque)
- outline effects applied are showing as red instead of the black/dark grey they are set as
- a white drop-shadow is applied to the outlines

I am using inDesign CS6 to create these files, and cannot find any settings from my end to make a more uniform experience for any of our users.

A link to one of the brochures to view live is http://files.pleasantsolutions.com/Home/Download/58724246-0f20-4204-97af-a3c400cd3c1c

![browsercompare](https://cloud.githubusercontent.com/assets/9219363/4634658/58080c78-53d2-11e4-9735-4a6d2482ab77.jpg)

**Comment by pleasantBailey** [comment]
I just checked this issue in the latest version of Firefox, a year later, and the issue is still occurring. Bumping this to hopefully at least get it triaged and assigned to someone to review.

**Comment by THausherr** [comment]
The page mentioned in the first message (4) looks pretty good to me. Maybe the problem has been fixed?

**Comment by timvandermeij** [comment]
Yes, it's fixed for me as well. Most likely it was a regression in Firefox that has been resolved. Closing as fixed.
