### ISSUE TITLE
Text Layer accented chars

### ISSUE THREAD

**Issue by Moistly** [mozilla/pdf.js#5423]
The accented characters in the following PDF are not correct within the Text Layer (fine in the visible canvas layer)

https://dl.dropboxusercontent.com/u/20922503/AQA-3651-RF-W-QP-JUN09%20-%20French.6.pdf

à > ‡
é > È

Tested on Win7 (FF and Chrome)

Thanks

**Comment by timvandermeij** [comment]
Closing since the file is no longer available. If this is still an issue with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html, please provide the file again to reopen. Thanks.
