### ISSUE TITLE
 transfer-encoding: chunked vs content-length

### ISSUE THREAD

**Issue by laurawu** [mozilla/pdf.js#5424]
https://github.com/mozilla/pdf.js/pull/2719 implemented chunk loading, it requests the server to return response with content-length. while for tomcat apache server, which uses the http 1.1 and use transfrer-encoding in place of content-length. 

Is there a special setting to support transfer-encoding "chunked"? or is there a other way to implement partial content loading for large pdf document?

**Comment by yurydelendik** [comment]
PDF.js uses HTTP range requests to "ask" server for data need to display particular page. And it does not matter if transfer-encoding is used -- the received data is handled by browser's XHR so it shall not be an issue. However it is PDF.js must know the total length if the file to accurately estimate size of the document. If server does not support range requests. PDF.js will try to load data progressively, but that's currently supported by Firefox's XHR only (moz-chunked-arraybuffer responseType). See #5319 for details.

There are not many PDFs that are linearized (web optimized) -- non-linerized PDFs contain important data at the end of the file, so just using streaming/loading progressively will not help. Closing as answered.
