### ISSUE TITLE
Compatibility.js XHR Polyfill conflict with angular-route.js in IE9

### ISSUE THREAD

**Issue by TylerYang** [mozilla/pdf.js#5429]
Hey guys, I just use the pdf.js to render pdf in ie9. And here is what I just found:
When I use angular-route.js to switch between different views.It will call a XHR request to load html file from my server. 

In compatibility.js, it has the code to set response for IE9:

    function responseGetter() {
        var text = this.responseText;
        var i, n = text.length;
        var result = new Uint8Array(n);
        for (i = 0; i < n; ++i) {
          result[i] = text.charCodeAt(i) & 0xFF;
        }
        return result.buffer;
      }
      Object.defineProperty(xhrPrototype, 'response', { get: responseGetter });

However, angular.js use this code to get the responseText from xhr:

    if (xhr && xhr.readyState == 4) {
        var responseHeaders = null,
              response = null;

        if(status !== ABORTED) {
            responseHeaders = xhr.getAllResponseHeaders();
            // responseText is the old-school way of retrieving response (supported by IE8 & 9)
            // response/responseType properties were introduced in XHR Level2 spec (supported by IE10)
            response = ('response' in xhr) ? xhr.response : xhr.responseText;   //Here to get the response from xhr. which conflict with compatibility.js 
          }
          completeRequest(callback,
              status || xhr.status,
              response,
              responseHeaders,
              xhr.statusText || '');
    }

I know in angular.js we can use other things like: template  to avoid by sending a xhr request to load html file. 

I think maybe we'd better create some private ajax function to avoid changing prototype? Cuz' I think this will make a lot of conflicts with the other plugin which depend on checking  xhr.response||xhr.rexponseText. 

P.S compatibility.js(pdf.js) version is : v 1.0.822
       angular-route.js/angular.js : v1.2.18 (The same api with angular.js 1.2.26)

Thx for your help. :）

**Comment by shershen08** [comment]
Have the same issue. At first I wasn't sure what was triggering such a weird behaviour.
Described it here - http://stackoverflow.com/questions/28188629/ie9-receives-json-response-as-a-line-of-charcodes-in-restangular

**Comment by yurydelendik** [comment]
@shershen08 Is that already fixed by https://github.com/mozilla/pdf.js/commit/a265861ba65fb9441328245d94d8559872b8d945 ?

https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js#L185

**Comment by timvandermeij** [comment]
No reponse. Closing as fixed for now until we have more information about this.

**Comment by TylerYang** [comment]
@yurydelendik @timvandermeij  Sorry for the late response. This should fix my angularjs app issue. Thx.
