### ISSUE TITLE
Layered object (transparent layer) not rendering properly in PDF.JS

### ISSUE THREAD

**Issue by Salmizar** [mozilla/pdf.js#5434]
This is what it looks like in Acrobat

![acrobat](https://cloud.githubusercontent.com/assets/6550271/4738661/b211c592-59fe-11e4-95d0-aa086fdff01b.png)

This is what the PDF looks like in PDF.JS

![pdfjs](https://cloud.githubusercontent.com/assets/6550271/4738644/9636fae0-59fe-11e4-8bc3-2d12c32691b1.png)

You can see that behind the ALWAYS OPEN letters, there is a missing transparant layer.

Here is a copy of the PDF

http://www.salmizar.com/files/pdfJSTransparancyIssue.pdf

I have confirmed the issue on v1.0.921

**Comment by Snuffleupagus** [comment]
Fixed by PR #13361
