### ISSUE TITLE
Blended color is drawed wrong with this PDF example

### ISSUE THREAD

**Issue by jokx** [mozilla/pdf.js#5436]
Hello,

I juste discover that pdf.js didn't draw rightly the blended color of this PDF :
http://www.iut-nimes.fr/sites/default/files/documents/pages/sg/IUT%20de%20Nimes%20-%20Organigramme%20-%2010.2014.pdf

Thanks for your attention and your great job.
JM.

**Comment by THausherr** [comment]
please add the shading label to this one (shading type 2)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6684.
