### ISSUE TITLE
Move to use Path2D canvas API

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#5451]
New canvas API provide also `Path2D`. Would that improve performance?

There is also a [polyfill](https://github.com/google/canvas-5-polyfill).

**Comment by Snuffleupagus** [comment]
Note that we have *some* `Path2D`-usage in the https://github.com/mozilla/pdf.js/blob/master/src/display/pattern_helper.js file.
If it'd be helpful in more places, *individual issues* should be opened for those specific cases; hence closing this old issue.
