### ISSUE TITLE
When using the hand tool, sometimes the secondary tool bar will go behind the document

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#5452]
Win7 64b ( tried using pdfjs 1.0.473 and 1.0.712 )

To reproduce I simply use the hand tool and scroll pages with it for a bit, and then click on the button to open the secondary menu.  Sometimes when I do this it gets stuck behind the document.  When this happens a page refresh is required to fix it.  This doesn't happen every time so reproducing it is somewhat awkward.  IE11 reproduces with a higher frequency, although I was also able to reproduce in FF32 as well:

![handtoolissue](https://cloud.githubusercontent.com/assets/9434387/4810896/b6d15cca-5eb6-11e4-9c68-3a4c49e46ee3.png)

**Comment by Snuffleupagus** [comment]
Is this still an issue?

**Comment by Rob--W** [comment]
I can still reproduce using the STR from https://github.com/mozilla/pdf.js/issues/5452#issuecomment-60913444 in Chromium 80.0.3987.132. The menu goes behind the canvas, but doesn't completely disappear though.
