### ISSUE TITLE
Not all layers of PDF are shown when in Chrome

### ISSUE THREAD

**Issue by dm-d2l** [mozilla/pdf.js#5453]
This particular PDF is too big to attach, but is available here ( http://www.grt.ca/en/routesSchedules/resources/2015transitmapKW_website.pdf )

In IE and FF it looks fine, but within Chrome it doesn't show some of the layers.

Chrome:

![pdfjs_chrome](https://cloud.githubusercontent.com/assets/9434387/4811479/8bec29aa-5eba-11e4-9454-12ed708fdcc1.JPG)

IE and FF:
![pdfjs_ie_ff](https://cloud.githubusercontent.com/assets/9434387/4811480/8bf9f79c-5eba-11e4-92fc-fcfef108e711.jpg)

**Comment by timvandermeij** [comment]
Closing since this issue is fixed upstream.
