### ISSUE TITLE
Remove Canvas try/catch

### ISSUE THREAD

**Issue by CodingFabian** [mozilla/pdf.js#5458]
There are two places in canvas:

            try {
              ctx.clip('evenodd');
            } catch (ex) {
              // shouldn't really happen, but browsers might think differently
              ctx.clip();
            }

          try {
            ctx.fill('evenodd');
          } catch (ex) {
            // shouldn't really happen, but browsers might think differently
            ctx.fill();
          }

Which use try catch in often invoked methods.
This makes these methods unnecessarily slow. (http://ryanmorr.com/reinventing-the-try-catch-block/)
The comment unfortunately does not mention which browsers the unhappy ones are.

Does anybody know which were causing the problem? would it be possible to polyfill it? or any other idea how to avoid the try catch?
![screen shot 2014-10-29 at 21 57 33](https://cloud.githubusercontent.com/assets/176132/4834492/414ff616-5fae-11e4-90c8-2bf33180c173.png)

**Comment by Rob--W** [comment]
Tested in the following browsers (using Browserstack), and `.fill('evenodd')` did not throw. I think that the `try`-catch can safely be removed without breaking functionality:

Desktop:

- IE9, IE11
- Chrome 14, 46
- Opera 11.6, 12
- Firefox 4, 41
- Safari 5.0, 9

Mobile (stock browsers):

- Android 2.2, 2.3, 4, 5
- iOS 3, 8

**Comment by yurydelendik** [comment]
> Is this try-catch syntax really necessary?

Not really. I just played it save. We can remove it.
