### ISSUE TITLE
Memory consumption - Special Use case

### ISSUE THREAD

**Issue by DavidVentura** [mozilla/pdf.js#5469]
I made the following example: http://jsfiddle.net/zkq19spu/2/
This represents my use case: Drawing a page of a PDF to a canvas, doing something to the canvas, then saving the image, drawing the next page to the canvas [..]

This seems to be an edge case, because the memory usage shoots to over 900MB with a 22MB pdf.
Could you help me to modify the source to:
*Disable the cache or shrink it to the minimum size
*Delete the canvas on render finish

With my use case I don't need to go back to the previous pages, and after the rendering is finished I don't need it anymore.

**Comment by fbender** [comment]
Is this still an issue with the latest version? @DavidVentura

**Comment by timvandermeij** [comment]
No response, closing for now.
