### ISSUE TITLE
Source Han Sans not displaying correctly at specific weight

### ISSUE THREAD

**Issue by Fanolian** [mozilla/pdf.js#5476]
OS: Win 8.1 64bit, all updates installed
Browser: Nightly 2014-11-05 build
pdf.js version: unknown

In the document "Developing & Deploying The World’s First Open Source Pan-CJK Typeface Family" (https://blogs.adobe.com/CCJKType/files/2014/11/iuc38-lunde-s1t3.pdf#page=21), Source Han Sans does not display correctly at a specific weight.
However in a very similar page from another document "Building Source Han Sans & Noto Sans CJK" (https://blogs.adobe.com/CCJKType/files/2014/11/iuc38-lunde-s8t1.pdf#page=50), this is displaying correctly.

There is displaying issue on page 20 in the first document (See screenshot) but I don't know if it's related.
p.s. I have both fonts Source Han Sans & Noto Sans CJK installed if it matters.

Screenshots:
pdf.js issue in Nightly
![pdf js](https://cloud.githubusercontent.com/assets/771216/4936552/cefdbe32-65ba-11e4-9694-08029d2488c5.PNG)

Expected result in adobe reader 11.0.09
![adobe reader](https://cloud.githubusercontent.com/assets/771216/4936584/2842a408-65bb-11e4-850e-07f79492185f.PNG)

No issue in another document
![pdf js2](https://cloud.githubusercontent.com/assets/771216/4936602/6015a524-65bb-11e4-86c9-f474d3dd8640.PNG)

**Comment by timvandermeij** [comment]
Likely to be related to #5377.

**Comment by timvandermeij** [comment]
Fixed by #9340.
