### ISSUE TITLE
Publish minified files to pdfjs-dist npm package

### ISSUE THREAD

**Issue by mgol** [mozilla/pdf.js#5487]
The npm `pdfjs-dist` package should containt minified file as well. Most front-end projects publishing on npm does it.

**Comment by thejdeep** [comment]
This looks like done ?

**Comment by mzgol** [comment]
> This looks like done ?

What do you mean by done? The latest version of the package doesn't contain the minified files.

**Comment by timvandermeij** [comment]
There is a PR for this (#5593), but indeed it's not done yet.

**Comment by yurydelendik** [comment]
#5593 is on right track, except it does not publish the same pdfjs-dist as minified output.

**Comment by adhikasp** [comment]
Hi, i think this issue could be closed. The commit e403f5272232c87581b0471e04c5e94c60aca91d is creating minify file with uglify-js.  Also [the latest comment in PR #6682](https://github.com/mozilla/pdf.js/pull/6682#issuecomment-249621359) is mentioned that it's closed because of the uglify-js.

**Comment by timvandermeij** [comment]
I don't think so. The `minified` target exists, but is not called when bundling `pdfjs-dist`. The files at https://github.com/mozilla/pdfjs-dist do not appear to be minified.
