### ISSUE TITLE
Low performance when decoding jbig2.

### ISSUE THREAD

**Issue by tau0** [mozilla/pdf.js#5493]
There is a shared dictionary in JBIG2 format, which is used usually in all pages. And decoding algorithm in PDF.js decodes the shared dictionary again and again on every page . 

The issue is described here (section 3.2): https://www.imperialviolet.org/binary/google-books-pdf.pdf

We've achieved minus 2 sec (on the sample book encoded via jbig2enc) on every page except the first using this hack: http://pastebin.com/fRRHqbA3. 

So the new time of rendering page is about 200ms (2400ms before hack)

But it isn't a good solution for production. It's better to make shared dictionary really _shared_, so on the next pages you can reuse already rendered symbols.

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and that neither of the links in https://github.com/mozilla/pdf.js/issues/5493#issuecomment-63500448 work any more, let's just close this as INCOMPLETE.

---

For e.g. other JBIG2-problems, please open a new issue (one per PDF document) with all of the information from the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) included.
