### ISSUE TITLE
Image content in pattern objects don't print or are incorrectly scaled when printing in chrome

### ISSUE THREAD

**Issue by jebramwell** [mozilla/pdf.js#5505]
I have found that PDFs generated by win2PDF (a print to PDF driver for windows) are not printing correctly from PDFjs in chrome.

I have tested a few versions of PDFjs 
* 1.0.277
* 1.0.712
* 1.0.907

in several versions of chrome: 
* chromium 37
* chrome 40.0.2214.10
* chromium 41.0.2226.0

all with the same result.

I have found that I can "correct" the problem by undoing a "hack" put in place to improve print quality under firefox.

in viewer.js
```javascript
 this.beforePrint = function pageViewBeforePrint() {
    var pdfPage = this.pdfPage;
    console.log("PDF before print");
    var viewport = pdfPage.getViewport(1);
    // Use the same hack we use for high dpi displays for printing to get better
    // output until bug 811002 is fixed in FF.
    var PRINT_OUTPUT_SCALE = 1;
```
I changed the line
```javascript
       var PRINT_OUTPUT_SCALE = 2;
```
to
```javascript
       var PRINT_OUTPUT_SCALE = 1;
```

and the printing issue goes away, however print quality does suffer.

I suspected this has to do with pattern object because I generated a PDF from the same content/application using CutePDF and the resulting PDF doesn't have the same problem.  Comparing the two PDFs I found that Win2PDF is putting the images inside of pattern objects. 

Win2PDF version with issue printing in chrome:
[PDFTest1.Win2PDF.pdf](https://pdf.yt/d/veavWBjq64E6ITKJ)

This is what the print preview looks like:
![image](https://cloud.githubusercontent.com/assets/6652852/5160527/a2db62e6-735c-11e4-982d-c3773e672219.png)
Here is the PDF generated if I have chrome create a PDF of the incorrect render
[PDFTest1.Win2PDF.printpreview.pdf](https://pdf.yt/d/ogMiCAYiJCSgBgN_)

CutePDF version that displays and prints fine:
[PDFTest1.cutePDF.pdf](https://pdf.yt/d/F5HZpqF7MStQfGV8)

I think what win2PDF is doing is silly, but it is an issue I have to deal with and it does suggest there is some general issue with how PDFjs is rendering patterns in chrome.

I found a simple example of using patterns for tiling an image from [this site](http://www.readytext.co.uk/).
I then viewed the PDF with PRINT_OUTPUT_SCALE set to 1, 2, and 3 and "printed" the result as a PDF.  
Original: [patternfill.pdf](https://pdf.yt/d/TGAOAnw3am-z7NJX)
print 1x scale: [patternfill.1x.pdf](https://pdf.yt/d/ToywBeEKXS0GpoOr)
print 2x scale: [patternfill.2x.pdf](https://pdf.yt/d/2tBWN1ZfNUPoK1Jm)
print 3x scale: [patternfill.3x.pdf](https://pdf.yt/d/fNp8VZK4ZYfsL_28)

I couldn't see a scaling issue in the preview window, but that may be because the tiled area is so small. The resulting PDFs clearly show the effect of PRINT_OUTPUT_SCALE on both the quality of the result and the mis-scaling of the tiled pattern.  So I guess if the intent of PRINT_OUTPUT_SCALE  is to improve detail in the printed output while not actually impacting relative scales then we might need to apply PRINT_OUTPUT_SCALE to pattern rendering in some way in chrome.  Or perhaps there is a bug in chrome.

I repeated this test in firefox and I didn't see the same issue with the pattern repeating more often at higher PRINT_OUTPUT_SCALE values.

**Comment by Webcascade** [comment]
Thanks for this! Fixed my issue with IE10.
