### ISSUE TITLE
Chrome 39 seems to incorrectly cache RangeResponses

### ISSUE THREAD

**Issue by CodingFabian** [mozilla/pdf.js#5512]
Message: Unexpected server response (206) while retrieving PDF.

It looks like either PDF.js does something strange, or there is a regression in Chrome 39 (Version 39.0.2171.65 (64-bit)).
Sometimes I am getting a partial response for the first request. If I have dev-tools with the cache override open, this does not happen at all.
If I allow caching then chrome seems to mix up the responses sometimes.

Might be a regression of the streaming implementation?
Right now I need to add Chrome 39 to checkRangeRequests() in Compatibility.js

**Comment by timvandermeij** [comment]
Fixed by #5598.
