### ISSUE TITLE
Internet Explorer (any version) getClientRects

### ISSUE THREAD

**Issue by MathewBerg** [mozilla/pdf.js#5513]
In our app we're using getClientRects to get the bounding boxes of the current text selection. We're using this and telling the server where they are. The issue is that pdf.js positions elements absolutely and this seems to break internet explorers ability to have getClientRects function correctly. The solution that I was able to find was to have all elements float left with negative margins and then position them via margin-left/top. I created a stackoverflow question with an example as well as the solution I was able to find here: http://stackoverflow.com/questions/27132674/internet-explorer-getclientrects-absolute-positioned-elements

**Comment by chitgoks** [comment]
I can confirm your solution works! Thank you!

**Comment by Snuffleupagus** [comment]
> The issue is that pdf.js positions elements absolutely and this seems to break internet explorers ability to have getClientRects function correctly.

We won't be making changes to the PDF.js library to specifically cater to old browsers, such as e.g. Internet Explorer; hence closing the issue as out-of-scope.

**Comment by NogsMPLS** [comment]
@Snuffleupagus Just FYI, this is potentially also an issue in Edge and not just old IE browsers:

https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects

> IE and Edge return a (ClientRectList with) MSDN: ClientRect objects (which do not contain x and y properties) instead of DOMRect objects

**Comment by chitgoks** [comment]
@NogsMPLS  I figure this may need to be reopened. This does not work with Edge 44 anymore.

**Comment by mariuszpala** [comment]
This is related with this Edge bug I think: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15068329/

**Comment by chitgoks** [comment]
@MathewBerg  perhaps you can reopen this issue? maybe someone else may be able to provide a fix.

**Comment by MathewBerg** [comment]
It seems I cannot, as this was specifically related to older versions of IE and not Edge I suggest you create a new issue and reference this one.

**Comment by chitgoks** [comment]
i saw an issue created regarding the new versions. ill reference this one then. thank you

**Comment by chitgoks** [comment]
#5513
