### ISSUE TITLE
Arial Font Rendering broken without disableFontFace

### ISSUE THREAD

**Issue by CodingFabian** [mozilla/pdf.js#5514]
The PDF available here is using an Arial font.

https://public.centerdevice.de/59622df7-38f2-4035-b36e-06f440c56d23

Most obvious is the text at the top:
"Verarbeitungsanweisungenselbstverriegelnd, auswärts öffn. TürensysteQ-Schlosssysteme - Vollmotorische Mehrfachverriegelun"

![brokenpng](https://cloud.githubusercontent.com/assets/176132/5219811/63ee1af8-765c-11e4-9423-bb458671e74f.png)

**Comment by timvandermeij** [comment]
@CodingFabian The link to the PDF appears to be dead. Could you post a new one?

**Comment by CodingFabian** [comment]
that one was customer provided. Looks they deleted it from our system. i will request a new one / this one again.

**Comment by CodingFabian** [comment]
Updated the Link in the description. the error still reproduces.

**Comment by Snuffleupagus** [comment]
Closing as fixed by #6715.
