### ISSUE TITLE
Only prefetch text not images (e.g for OCR'd files)

### ISSUE THREAD

**Issue by PXLRic** [mozilla/pdf.js#5520]
When using the search function the entire file is downloaded even with auto fetch disabled. This causes a problem with large OCR'd files. It would be great to be able to just download the text for searching, and the page images are grabbed only when required to view.

**Comment by Snuffleupagus** [comment]
> It would be great to be able to just download the text for searching, and the page images are grabbed only when required to view.

Unfortunately ignoring images would lead to missing content when extracting text!

Images, or rather `XObjects` as they are called, can come in various subtypes. Specifically in the case of the `Form` subtype, the `XObject` may contain (almost) arbitrary PDF content, please see the PDF specification[1]. Hence if we ignored images when extracting text, then text-selection and searching would be partially broken for many existing PDF files.

Closing as wontfix.

---
[1] http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G7.1852124
