### ISSUE TITLE
Image not rendering correctly

### ISSUE THREAD

**Issue by cazgp** [mozilla/pdf.js#5526]
The pdf can be found at http://wikisend.com/download/775042/page11.pdf.

With this code:

    var viewer = document.getElementById('viewer');

    var handle_page = function(page) {
      // This gives us the page's dimensions at full scale
      var viewport = page.getViewport(1);

      // This change the viewport so the pdf uses the full page width
      viewport = page.getViewport( viewer.offsetWidth / viewport.width );

      // We'll create a canvas for each page to draw it on
      var canvas = document.createElement( "canvas" );
      canvas.style.display = "block";
      var context = canvas.getContext('2d');
      canvas.height = viewport.height;
      canvas.width = viewport.width;

      // Draw it on the canvas
      page.render({canvasContext: context, viewport: viewport});

      //Add it to the web page
      viewer.appendChild( canvas );
    };

    PDFJS.getDocument(name)
      .then(function(pdf) {
        pdf.getPage(11).then(handle_page);
    });

the image output is 
![screenshot from 2014-12-04 19 41 49](https://cloud.githubusercontent.com/assets/658873/5304759/b5e96bb4-7bed-11e4-8589-88fcf392b255.png)

This is true with a variety of worker options, including disabled and not. Tried a combination of different pdf.js as well, including the latest, the one from the examples gallery, and some random ones on the internet. Other images in the same document that's taken from do render correctly.

This is true in both Chrome 38 and Firefox 33.0 on Ubuntu 12.04.

**Comment by timvandermeij** [comment]
@cazgp The link is dead. Could you put up a new one (perhaps Google Drive, Dropbox or something else that is less likely to expire)?

**Comment by timvandermeij** [comment]
The original link is dead, but I have found the same PDF file online: https://www.overleaf.com/articles/building-new-topological-spaces-through-canonical-maps/dzrpwmqjbnhv/viewer.pdf

**Comment by timvandermeij** [comment]
Closing as fixed, probably by a patch regarding applying base transforms.

**Comment by Snuffleupagus** [comment]
> Closing as fixed, probably by a patch regarding applying base transforms.

Bisecting actually points to commit https://github.com/mozilla/pdf.js/commit/194994a2898a6d01c434d6d3270357799f3ac820, i.e. PR #6551.
