### ISSUE TITLE
Send as an email attachment

### ISSUE THREAD

**Issue by Krastanov** [mozilla/pdf.js#5527]
Can the addition of "send pdf as an email attachement" option be considered?

My workflow includes opening a pdf article in firefox, saving it to a temporary location and then opening gmail to send the newly downloaded file to my kindle or to a coleague.

More generally, what would be the appropriate way to create an http request containing the entire pdf file object?

**Comment by cirosantilli** [comment]
+1

**Comment by mano-mykingdom** [comment]
+1

**Comment by AlexDubstone** [comment]
+1

**Comment by brianmcbride** [comment]
+1

**Comment by iamgururaj** [comment]
+1

**Comment by timvandermeij** [comment]
I would like to ask everyone not to add +1 comment anymore. Use GitHub's reaction button on the original (top) comment instead. This avoids mail/notification spam and allows us to prioritize issues by sorting on the number of +1 reactions given. Thanks.

**Comment by alicat3** [comment]
+1

**Comment by Snuffleupagus** [comment]
The web platform doesn't generally, for obvious security reasons, support adding attachments to `mailto:` links and this issue is thus probably not possible to solve. @timvandermeij Should this issue simply be closed as wontfix (or even cantfix)?

**Comment by timvandermeij** [comment]
Yes, I don't see this happening any time soon.
