### ISSUE TITLE
about rendering pdf file from shared location

### ISSUE THREAD

**Issue by jkella** [mozilla/pdf.js#5530]
HI I am new to PDF.js and i want to load pdf file from shared location instead of from local application context . Please suggest me approach to load pdf file from shared location in linux like /opt/temp

**Comment by Snuffleupagus** [comment]
Based on the very limited information provided, it doesn't sound like this is actually a PDF.js specific issue, but rather a more general question regarding file handling in web applications.

Closing as invalid/incomplete.
