### ISSUE TITLE
text selection , copy and paste problem for RTL languages

### ISSUE THREAD

**Issue by sshbio** [mozilla/pdf.js#5533]
selecting rtl languages cause many problems , copy the selected text is in reverse order without spacing ,
select is not possible in some cases because of div positions and order of them.
is there any solution to fix the problem?

![out](https://cloud.githubusercontent.com/assets/478063/5353875/ae10e4a8-7f94-11e4-94f5-72949ed6fdfa.gif)

language in above pdf is farsi (fa)
but as I tested, the problem affect all rtl languages.

**Comment by kfir91** [comment]
@shSina  Hi, can you give example please?

**Comment by Snuffleupagus** [comment]
Given that this issue contains no PDF file or runnable test-case (and is very old), I'd suggest closing it as INCOMPLETE since it's not really actionable in its current form.
