### ISSUE TITLE
Text does not render on Mac OS X  Chrome/Safari (Includes Reproduction)

### ISSUE THREAD

**Issue by nathan-muir** [mozilla/pdf.js#5535]
File: https://drive.google.com/file/d/0BxMxKr-U2w6MS2x1ekEyVFpRWFU/view?usp=sharing

PDF.js: Latest viewer at http://mozilla.github.io/pdf.js/web/viewer.html

Displays Correctly On:
- PDF.js, Fedora 20; Firefox
- PDF.js, Fedora 20; Google Chrome
- PDF.js, Mac OS X 10.10; Firefox
- Okular, Fedora 20
- Adobe Reader 9, Fedora 20

![image](https://cloud.githubusercontent.com/assets/3112329/5371530/191bf9aa-8084-11e4-8c1f-07682a9cbb7b.png)

Doesn't display text:
- PDF.js, Mac OS X 10.10; Google Chrome
- PDF.js, Mac OS X 10.10; Safari

![image](https://cloud.githubusercontent.com/assets/3112329/5371632/1b0b683e-8086-11e4-9630-078856ee14ca.png)

---

Aside;

Took a while to be able to make a minimal reproduction!

I'm a bit of a novice debugging these things, but it seemed quite weird when generating a minimal test case with [maker](http://brendandahl.github.io/pdf.js.utils/maker/) I had to insert null bytes before each character, eg

```
BT
10 20 TD
/F1 20 Tf
(\u0000h\u0000e\u0000l\u0000l\u0000o\u0000 \u0000w\u0000o\u0000r\u0000l\u0000d) Tj
ET
```

Otherwise the output would be blank on all readers / display weird UTF-8 characters

**Comment by timvandermeij** [comment]
@nathan-muir Are you still able to reproduce this with the latest viewer at http://mozilla.github.io/pdf.js/web/viewer.html? The have been many font fixes since this issue was opened, including a largely Mac-specific one just a day ago.

**Comment by nathan-muir** [comment]
@timvandermeij I've just tested it now on the current web viewer on _Mac OS X_.

  *  **does not** work on Google Chrome (Currently Version 43.0.2357.130 (64-bit)),
  *  **does** work on Firefox (Currently 39.0)

**Comment by nathan-muir** [comment]
Just tested again.

It **does** work on Google Chrome 48.0.2564.116
it **does not** work on Safari 9.0.3 (11601.4.4)

**Comment by hansent** [comment]
Can confirm that loading the file  https://drive.google.com/file/d/0BxMxKr-U2w6MS2x1ekEyVFpRWFU/view?usp=sharing in Safari 9.1 using http://mozilla.github.io/pdf.js/web/viewer.html  not display text.

I am running into the simmilar issue on Safari 9.1 on a webapp lots of text not displaying on page load.  As soon as I resize the page, or there is another event that causes a repaint (?!) it seems to correct itself.  I am also seeing this behaviour on  http://mozilla.github.io/pdf.js/web/viewer.html  on the above file.

tempted to call it a safari bug...but no luck finding any open issue or much about how to work around yet.

**Comment by Snuffleupagus** [comment]
This issue is very old, and is relevant for browsers and PDF.js versions which are no longer supported.
Furthermore there's also e.g. PR #9340, which should help avoid browsers (potentially) interfering with and breaking font rendering; is it still meaningful to keep this issue open?
