### ISSUE TITLE
double-gamma incorrectly displayed

### ISSUE THREAD

**Issue by maw** [mozilla/pdf.js#5540]
In http://www.brill.com/sites/default/files/ftp/downloads/34732_Preview.pdf on the 16th page (in the document itself the page is labelled 10) the double-gamma in ἄγγελος (and many other words in the first column of text) is misrendered.

**What I expected to see**: two gammas -- γγ

**What I saw instead**: it's difficult to describe but I'd say that it looks kind of like kettle (see screenshot)
![kettlegamma](https://cloud.githubusercontent.com/assets/17752/5429262/74053d9e-83aa-11e4-9dab-fccf41979369.png)

Versions tested: pdf.js as shipped with ff 33.1 and master (20bf84ac5).

**Other notes**:

* Single gammas render fine, for instance ἆγε in the second column. The double-gammas are rendered fine in Preview and in the renderer that Chrome uses.

* In Greek gamma is equivalent to g in English and is this character: γ. In Greek double gammas are pronounced differently. I notice that in Preview and in Chrome when I select text, I can't select individual gammas when they're paired up -- either both or neither.

**Comment by timvandermeij** [comment]
@CodingFabian Is this still broken using the latest versions of Firefox and PDF.js?

**Comment by CodingFabian** [comment]
yes still broken in latest nightly (41.0a1 (2015-06-09)) and latest pdf.js (fda6c186447c6eeea5850613888ce67c4dc4f502)

**Comment by Snuffleupagus** [comment]
Reduced test-case: https://www.dropbox.com/s/yxcacixy2gfyblp/issue5540_reduced.pdf?dl=0.
*Note:* I don't have access to a Mac, so I'm hoping that it accurately captures the issue.

**Comment by CodingFabian** [comment]
it does:
![screen shot 2015-06-11 at 13 10 27](https://cloud.githubusercontent.com/assets/176132/8105657/5071c0e6-103b-11e5-9ebc-18e02f67fb54.png)

**Comment by CodingFabian** [comment]
fixed by #6171 confirmed on my mac using preview version for that PR.
@Snuffleupagus please close, thanks.
