### ISSUE TITLE
Load PDF from blob using  PDFJS.getDocument()

### ISSUE THREAD

**Issue by telliott22** [mozilla/pdf.js#5544]
I'm using the hello world example to load a PDF stored in my database as a Blob, but can't get it to work. I'm using docInitParams to get the data from a servlet that queries the DB. Is there something that I'm missing out?

I'm getting a list of error messages in the console window listing invalid characters, like : 
Warning: Ignoring invalid character "33" in hex string util.js:204 

Here is the code i'm using:

            var docInitParams = {
            url: "/secure/pdf",
            withCredentials: true
            };

           PDFJS.getDocument(docInitParams).then(function(pdf) {
           .....

Thanks in advance.

**Comment by timvandermeij** [comment]
Closing as incomplete for now. Please provide more information to reopen if the problem still exists.
