### ISSUE TITLE
Fill pattern not rotated

### ISSUE THREAD

**Issue by bergk** [mozilla/pdf.js#5547]
When /Rotate is used on a page fill patterns are not rotated and become invisible.
The pdf sample: https://wftp.stuertz.de/public.php?service=files&t=1bb02d8ec2c90ffe05f7928b2b685659
If you look at the pdf with Adobe Reader you see a pipe filled with an orange pattern.
But with PDF.JS the pipe is not filled (using Windows 7, FireFox 33.0.1, demo viewer http://mozilla.github.io/pdf.js/web/viewer.html). The page uses /Rotate 90.
![rendered-with-acrobat](https://cloud.githubusercontent.com/assets/10218175/5469560/6069ac7c-85dd-11e4-8c26-c04f4075f54b.png)
![rendered-with-pdf js](https://cloud.githubusercontent.com/assets/10218175/5469562/64f9be08-85dd-11e4-8090-6c4a46a32138.png)
The Javascript console shows just 1 line:
"PDF 528485bbf3c61ed69e52b6a1c5895e61 [1.6 GPL Ghostscript 9.04 / FreePDF 4.06 - http://shbox.de] (PDF.js: 1.0.993)" viewer.js:5418

**Comment by Snuffleupagus** [comment]
@bergk Is this still an issue in the latest version of PDF.js?
If so, can you please provide a new link to the PDF file, since the existing one has expired?

**Comment by timvandermeij** [comment]
Closing until a new link is provided.
