### ISSUE TITLE
Toggling the "Highlight all" search feature should not change the view position

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#5561]
When the _Highlight all_ search feature (checkbox in the [demo](http://mozilla.github.io/pdf.js/web/viewer.html), button in the extension) is toggled, then the view position seems to focus the first hit on the current page.
In my opinion, the toggle shouldn't move the view at all, especially if the user turns _Highlight all_ off. Changing the focus is also contrary to Firefox's built-in highlight behavior (I haven't tested other browsers).

(FF34, Windows 7, current Demo version: 1.0.1011)

**Comment by jazzy-em** [comment]
+1
I completely agree.
