### ISSUE TITLE
Highlighting not displaying on Android 4.2.2

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#5575]
Hello!
I tested the demo example (http://mozilla.github.io/pdf.js/web/viewer.html) on Samsung Galaxy Tab 3 (GT-P5210, Android 4.2.2). When I try to search for something, highlighting is not displayed. Navigating the search results is working correctly, but the results are not highlighted.

**Comment by timvandermeij** [comment]
This is working as expected on Android 6.0.1 using Firefox 46.0.1 on a Nexus 6. Android 4.2.2 is outdated and I'm going to assume this issue was with the stock Android browser, which is no longer supported since Android 4.4, so there is not much more we can do here.
