### ISSUE TITLE
Some characters аrе not displaying on Android 4.2.2

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#5576]
Hello!
I tested the demo example (http://mozilla.github.io/pdf.js/web/viewer.html) on Samsung Galaxy Tab 3 (GT-P5210, Android 4.2.2). Some characters аrе not displaying ('C' in '6.1 Calling Compiled Traces'):
![pdfjsbug](https://cloud.githubusercontent.com/assets/10258064/5534749/5f052322-8a8b-11e4-8cbc-43ae687c39bd.jpg)

**Comment by timvandermeij** [comment]
This is working as expected on Android 6.0.1 using Firefox 46.0.1 on a Nexus 6. Android 4.2.2 is outdated and I'm going to assume this issue was with the stock Android browser, which is no longer supported since Android 4.4, so there is not much more we can do here.
