### ISSUE TITLE
PDF renders incorrectly

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5583]
The PDF at the below URL renders incorrectly.  The background fading graphic appears on top of the text.  In Adobe Reader it appears as a background and the text is readable.

http://drugnatural.com/mm5/DrugNatural_Library/Nutrition_Article_Archive/IMJune_July2004_LeakyGut.pdf

**Comment by Rob--W** [comment]
Upstream Chrome bug has been fixed (verified in Chrome 41.0.2265.0)

![pdfjs-chrome-41 0 2265 0](https://cloud.githubusercontent.com/assets/1365071/5600001/c48add42-92d1-11e4-82fe-4296be820e40.png)
