### ISSUE TITLE
Support for partial region decode of Jpeg2000

### ISSUE THREAD

**Issue by MaMazav** [mozilla/pdf.js#5607]
I've developed a support in partial region decoding of jpeg2000 codestreams, the changes can be reviewed here:

https://github.com/MaMazav/pdf.js/commit/65f0736f57381bbba77bea7b7558dce879ecb423
(Link editted).

If it can help pdf.js in any way I'll open a PR to contribute it so you can merge it into main pdf.js repo, otherwise you can close this issue.

**Comment by timvandermeij** [comment]
/cc @yurydelendik 

What is your opinion on this?

**Comment by Snuffleupagus** [comment]
Given the lack of a PDF file that can be used to test this, since a reference-test would be a requirement for accepting a patch, does it actually make sense to keep this issue open?
