### ISSUE TITLE
Thumbnail images are broken for large zoom values

### ISSUE THREAD

**Issue by fkaelberer** [mozilla/pdf.js#5611]
STR: open the [viewer#zoom=500](http://mozilla.github.io/pdf.js/web/viewer.html#zoom=500), wait for the first page to render completely, then open the thumbnail bar.

![broken](https://cloud.githubusercontent.com/assets/4624768/5597420/409cf99a-92a2-11e4-826f-a488b8f9fbaf.png)

Windows & Linux, FF34 & 37.

**Comment by Snuffleupagus** [comment]
This is a regression from PR #4834.

/cc @dferer
