### ISSUE TITLE
if the file name is chinese.pdf.js can not find it,what can i do

### ISSUE THREAD

**Issue by qiannianhappy** [mozilla/pdf.js#5613]

**Comment by yurydelendik** [comment]
No description is provided.

**Comment by qiannianhappy** [comment]
the pdf.js demo support pdf name is “compressed.tracemonkey-pldi-09.pdf” ,if the name change to chinese,such as "文档.pdf", pdf.js can not find it

**Comment by yurydelendik** [comment]
works for me:

![screen shot 2015-01-07 at 9 17 52 am](https://cloud.githubusercontent.com/assets/1523410/5647714/28612004-964e-11e4-9a7f-defd4c0b47a2.png)

please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md to provide more details
