### ISSUE TITLE
PDF Extension for Chrome in Public Sessoin

### ISSUE THREAD

**Issue by Kwklos** [mozilla/pdf.js#5614]
Can you please enable the Extension to work in Public Sessions.  At this point it is the only way I can print certain PDFs.

**Comment by Rob--W** [comment]
What prevents you from installing the PDF Viewer in a public session?
Have you tried to pre-install the extension? https://support.google.com/chrome/a/answer/1375694

**Comment by Rob--W** [comment]
To me it is not clear what issue you're having right now. Please state what is preventing you from using PDF.js's Chrome extension in "public sessions". If you don't know how to write it down, share a video that highlights your problem.

**Comment by timvandermeij** [comment]
Closing as incomplete for now. Please provide more information as requested above to reopen.
