### ISSUE TITLE
Significant rendering errors

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5625]
Significant rendering errors throughout file.  It renders correctly in Adobe Acrobat.  (See Screen shots).  Using Windows 8.1 x64. Chrome 39.0.2171.95

File:  https://pdf.yt/d/_9N23mLX9_XzEhEQ

pdf.js screenshot

![image](https://cloud.githubusercontent.com/assets/10129039/5655229/726a5100-96c3-11e4-9c8c-04834fe35365.png)

![image](https://cloud.githubusercontent.com/assets/10129039/5655253/c159b95e-96c3-11e4-9d73-07611d1aeeee.png)

Adobe Acrobat

![image](https://cloud.githubusercontent.com/assets/10129039/5655240/9c418214-96c3-11e4-9298-5c67d6fe7b35.png)

![image](https://cloud.githubusercontent.com/assets/10129039/5655248/b38a20ca-96c3-11e4-9ad9-a98258b382ec.png)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #5308.
