### ISSUE TITLE
pdf.js doesn't randering some character. 

### ISSUE THREAD

**Issue by vivacewith** [mozilla/pdf.js#5626]
![temp](https://cloud.githubusercontent.com/assets/10443206/5659932/63121662-975d-11e4-8b40-3088ece7a588.JPG)

**Comment by vivacewith** [comment]
blue box is missing character

**Comment by Snuffleupagus** [comment]
@vivacewith When reporting an issue: please make sure you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, paying special attention to the *first* paragraph!
At the *very* least you need to provide a link to the PDF file, and preferable also other information about your configuration (as outlined in the link above).

**Comment by timvandermeij** [comment]
Closing as incomplete. Please provide the information requested above to reopen this issue.
