### ISSUE TITLE
Sharp ('#') symbols missing in music transcription of "Like Spinning Plates"

### ISSUE THREAD

**Issue by nnethercote** [mozilla/pdf.js#5635]
The music transcription at http://vigna.di.unimi.it/music/likespinningplates.pdf is missing all the sharp ('#') signs. There should be four at the start of each stave and some of the notes in the treble stave should also have them.

I reproduced this problem with the current pdf.js tip.

**Comment by timvandermeij** [comment]
I cannot reproduce this using Windows 7 x64 and Firefox 34.0.5. What is your configuration?

**Comment by nnethercote** [comment]
It reproduces for me on Mac with Firefox 35.0, and also on Linux 64 (Ubuntu 14.10) with a trunk build of Firefox.

It renders correctly in Preview on Mac and in evince on Linux.

**Comment by nnethercote** [comment]
The sharps are also missing for me in Firefox 33 running on Windows 8.1 (in a VM).

**Comment by timvandermeij** [comment]
Are there any messages in the console for you?

**Comment by nnethercote** [comment]
Nothing in the console.

**Comment by nnethercote** [comment]
Sample output from pdf.js:
![plates](https://cloud.githubusercontent.com/assets/1940286/5697225/c8caa2e0-99a0-11e4-9db6-2e6cc2dee176.png)

**Comment by nnethercote** [comment]
Sample output from evince:
![plates2](https://cloud.githubusercontent.com/assets/1940286/5697230/f05d27d8-99a0-11e4-8bd4-482d84992f5f.png)

**Comment by timvandermeij** [comment]
This is what it looks like for me (sample from PDF.js tip on Windows 7 x64 and using Firefox 34.0.5):

![naamloos](https://cloud.githubusercontent.com/assets/1993262/5697290/8a6a9b1c-99ec-11e4-8b24-f6b14849ac46.png)

Maybe it's a font issue that does not affect Windows. Marking as triage needed.

**Comment by nnethercote** [comment]
I mentioned above that the problem still occurs for me on my Windows 8.1 installation. So saying "Windows only" is an oversimplification.

**Comment by CodingFabian** [comment]
ok for me on mac with chrome and ff nightly

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by brendandahl** [comment]
@nnethercote Still an issue? I can't reproduce on MacOS or Windows w/ FF58.

**Comment by nnethercote** [comment]
It's now working correctly for me on Linux and Mac with Firefox 58. Thank you for the update.
