### ISSUE TITLE
Thumbnail size and rendering regressions

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#5637]
Steps to reproduce:

1. Open http://kennemerlyceum.nl/attachments/article/4/Gymnasiumfolder.pdf
2. Open the sidebar with the thumbnail view
3. Notice that the second thumbnail is stretched in height and the third thumbnail has rendering issues (white background is missing for example).

Commits that caused this:

- [x] Stretch caused by https://github.com/mozilla/pdf.js/commit/fe4ac8678198937aca49c02fb7d2e83de183cd0e (fixed by #5638).
- [ ] Rendering issues caused by https://github.com/mozilla/pdf.js/commit/ec311f303b40ed6457278ec157d49fb761144f36, i.e. PR #3009.

**Comment by Snuffleupagus** [comment]
The referenced commit for the rendering issue is likely a red herring, further bisecting/triaging is needed.
