### ISSUE TITLE
Wrong characters

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#5642]
The following pdf show bad characters instead of numbers and math symbols.
Tested with Firefox 34.0 and PDF.js: 1.0.1080 on Windows 7.

https://drive.google.com/file/d/0B12AhxvnYHrANlJucE43YXFWTGM/view?usp=sharing

Thanks

**Comment by Snuffleupagus** [comment]
This is a regression from commit https://github.com/mozilla/pdf.js/commit/b5b94a4af389ef387570cf22662d9fc6bd41417a, i.e. PR #4259.

**Comment by benbro** [comment]
Maybe fixed by?
https://github.com/mozilla/pdf.js/pull/5651#issuecomment-71811234

**Comment by Snuffleupagus** [comment]
> Maybe fixed by? #5651

No, unfortunately not, since that one only fixes regressions from PR #5017.
@benbro You can confirm this yourself by using the the preview [available here](https://github.com/mozilla/pdf.js/pull/5651#issuecomment-70094891).

**Comment by timvandermeij** [comment]
Direct download link: https://drive.google.com/uc?export=download&id=0B12AhxvnYHrANlJucE43YXFWTGM

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7023.
