### ISSUE TITLE
Unable to render PDF with many pictures

### ISSUE THREAD

**Issue by sanel** [mozilla/pdf.js#5644]
Hi,

I'm using latest Firefox (35.0) with PDF.js (1.0.907) and seems it is not able to show pdf with many images and drawings. The same behavior is with older PDF.js versions. Here is the sample: http://repository.readscheme.org/ftp/papers/sw2010/06-barland.pdf

This pdf is rendered in Xpdf and Chrome without problems.

**Comment by CodingFabian** [comment]
confirmed, looks like the pdf is broken.
" Page index 0 not found. viewer.js:934 rejected"

**Comment by Snuffleupagus** [comment]
This is a regression from PR #3848.
