### ISSUE TITLE
Uncompatible

### ISSUE THREAD

**Issue by MartinFirefox** [mozilla/pdf.js#5645]
PDF viewer is not compatible with latest firefox version (35.0) in Windows XP SP 3.

**Comment by yurydelendik** [comment]
Please explain

**Comment by yurydelendik** [comment]
My guess it is about https://addons.mozilla.org/en-US/firefox/addon/pdfjs/:

```
Note: PDF.js is part of the Firefox since version 19. The extension is mostly used to bring newer version of the PDF.js library to the older Firefox version. It will be marked as incompatible starting from the Firefox version 35.
```

Please uninstall the addon. If you previously disabled in the Options->Application or in about:config, please enabled it (and restart FF)

**Comment by timvandermeij** [comment]
That must be it. Closing as answered.
