### ISSUE TITLE
Search Function doesn't update on same page

### ISSUE THREAD

**Issue by AdamBes** [mozilla/pdf.js#5652]
When searching for something, if the hit is on a new page, it will load the new page and focus on that text, but subsequent hits on the page will not update page positioning, will only update the searched phrase location.

**Comment by Rob--W** [comment]
That's normal. Search should only scroll jump to a section of a page if that section was previously not visible. If the search result is already visible, then there is no point in changing the page position.

**Comment by timvandermeij** [comment]
True. Closing as answered for now. Please provide more details and steps to reproduce (example PDF) if you mean something else.
