### ISSUE TITLE
Is it possible to run pdf.js with out a web-server?

### ISSUE THREAD

**Issue by kirangsa** [mozilla/pdf.js#5653]

**Comment by yurydelendik** [comment]
Yes, it is. It runs without web server when browser allows to request PDF from local system, e.g. Firefox allows to perform file XMLHttpRequest, however Chrome does not. For browser that does not support local file system XHR use other means to transfer data to PDF.js library -- getDocument() allow opening PDFs from Uint8Array. Closing as answered (see also [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request))

**Comment by kirangsa** [comment]
thanks for replay
i am developing website that works on ie9 to ie11
i need to run the pdf.js without a server also.

Is it possible? if possible can you please share some tutorial for the same.

Thanks in Advance!

**Comment by yurydelendik** [comment]
In the past, I used http://msdn.microsoft.com/en-us/library/system.windows.forms.webbrowser.objectforscripting%28v=vs.110%29.aspx to communicate data between Window Application and HTML page for other project. Hope it will help to pass data between PDF.js and local file system/database. This issue is getting Microsoft platform specific, therefore it's out of scope of this project. You may find more help at a discussion list or the IRC channel.

**Comment by hendrawidjaja** [comment]
i am trying to understand and follow exactly the prevnext example, including changing the url path and filename. I am working local (offline) but I didn't see any pdf on my screen. Did I make a mistake somewhere?

**Comment by hltdev8642** [comment]
I have gotten this to work, if you write over the viewer.js file every time, appending the url of the pdf  plus the "file:///" prefix at the start . 

You can write the file by splitting it at the  "DEFAULT_URL=" line (somewhere around the 5000th line Lol), and then adding the url, and then the rest of the file. You also could use a regex, or other method to replace the variable.

An example url would look like this (this is in javascript pseudocodeish writing...)
 
var urlInsert = 'file://' + urlToPdfOnDeviceHere (/C:/Users/username/folder/filename.pdf)
var file = ''
file += [code from viewer.js untill "DEFAULT_URL="]
file += urlInsert 
file += \n
file += [remaining code in viewer.js file]

write the file ---> 'viewer.js' 
(with the string saved above in "file" variable)

If you want more info let me know , I could provide you a demo but it is dependent on an android app called Droidscript, so it runs on android only at the moment. But it works :) 

email me  @ hltdev8642@gmail.com if you want help , or are interested in figuring out how to do this id be happy to help 😄

**Comment by hltdev8642** [comment]
Oh yeah i forgot, and then you simply load the main html file in the pdf.js directory (as you would normally). The file url you appended to the viewer.js should result in whatever pdf file you set the file name to , to load. 

Basically it overwrites it everytime, which was the only way I could find to get around the incompatibility with usage of the "file:///" prefix (as pdf.js is supposed to access a relative path on a server, so I suppose it makes sense the support for the file:/// prefix is minimal to nonexistant if I am not mistaken)
