### ISSUE TITLE
Buttons and zoom do not work when using from local machine (file://) in Internet Explorer

### ISSUE THREAD

**Issue by chuliomartinez** [mozilla/pdf.js#5662]
IE does not allow file:// using the native window.XMLHttpRequest. Using window.ActiveXObject("Microsoft.XMLHTTP") works ok. 

The problem is in l10n.js xhrLoadText() method.

The "bug" causes buttons and zoom-bar to be unresponsive, however the PDF is loaded correctly,

jQuery has workaround code for exactly this situation.

**Comment by Snuffleupagus** [comment]
As described in the [README](https://github.com/mozilla/pdf.js#getting-the-code), this is a limitation of some browsers. Please use a web server instead.
Closing as won't fix.
