### ISSUE TITLE
Search text is highlighting to the right throughout the document, even though manually selected text is correct

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5667]
https://pdf.yt/d/mGEUewV6eh0UDnOc

Open this pdf and search for the word 'pyogenes'.  Throughout the document it is highlighting significantly to the right.

However, if I manually select the word pyogenes, it works correctly and copies correctly to the clipboard.

Using Chrome 39, Windows 8.1 x64 and pdf.js 1.0.1061

(Interestingly, works better on the version of pdf.js on pdf.yt - suggests something may have broken this feature)

![image](https://cloud.githubusercontent.com/assets/10129039/5860534/d7a581a6-a259-11e4-8eda-7278f7c8d7b3.png)

**Comment by timvandermeij** [comment]
Closing as duplicate. We have many issues open for this problem, for example #2980.
