### ISSUE TITLE
Search feature is highlighting wrong text

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5668]
https://pdf.yt/d/BeioWriXAn-DkFcO

When searching the above pdf for the phrase 'acute' the second hit hightlights the nearby word ' especi'.  Almost certainly this is the same issue that I raised in #5667 

However, when examining the generated html you can see that the highlighted text is incorrect - it contains the text ' especi' and not the search term 'acute' - it is not a positioning issue.  (see screenshot).

I am using Chrome 39, windows 8.1 x64 and pdf.js 1.0.1093

![image](https://cloud.githubusercontent.com/assets/10129039/5864096/f2d665a4-a276-11e4-91fa-af6eb36f0cde.png)

**Comment by timvandermeij** [comment]
Hm, this is an interesting one. I can reproduce this using the latest PDF.js development version on Windows 7 x64 too (Firefox 35.0).

**Comment by jespersh** [comment]
It seems to be the textlayer itself is placed incorrectly.

![textlayer wrongly placed](http://i.imgur.com/6Mys1ti.png)
