### ISSUE TITLE
PDF.js Issue

### ISSUE THREAD

**Issue by mohd450** [mozilla/pdf.js#5670]
Hello

I have this issue, I'm trying to build a book App through PhoneGap using PDF.js, the project I'm trying to convert to a mob app is in the following link:

http://mozilla.github.io/pdf.js/getting_started/

the problem is that when I convert it to an app, the viewer opens, but the pdf document does not appear.

Will be appreciated if you kindly help me solving this issue.

Regards,
Moh'd

**Comment by timvandermeij** [comment]
Are there any erros in the console? Could you share more information about the environment the app runs on?

**Comment by timvandermeij** [comment]
Closing as incomplete. Please provide the information mentioned above to reopen.
