### ISSUE TITLE
Arabic glyphs missed in PDF Viewer

### ISSUE THREAD

**Issue by Qutbiddin** [mozilla/pdf.js#5677]
Hello.
Arabic glyphs are missed in PDF Viewer.
Original text:
.عذراً
ماذا؟
...أحتاج
السّيّدة
See example.
http://www.pdf-archive.com/2015/01/27/arabicmissedglyphs/arabicmissedglyphs.pdf 

This example works fine on Adobe Acrobat and Google Chrome
Best regards
Qutbiddin.

**Comment by Snuffleupagus** [comment]
This is a regression from commit https://github.com/mozilla/pdf.js/commit/b5b94a4af389ef387570cf22662d9fc6bd41417a, i.e. PR #4259.

**Comment by slothmike** [comment]
This issue effects us as well.
