### ISSUE TITLE
Printing on iOS Chrome and Apple policy?

### ISSUE THREAD

**Issue by aledoroshenko** [mozilla/pdf.js#5685]
Can't figure out how it's done in pdf.js viewer. As i see on [Stackoverflow](http://stackoverflow.com/questions/24947993/window-print-method-is-not-working-in-ipad-chrome-browser):

> it's currently not possible to print in Chrome for iOS due to Apple's policy on using alternative browser engines.

> It's a chrome bug/feature. window.print is available, it works and do nothing.

But in pdf.js demo page printing in iPhone 5S Chrome is actually works - it fires browser print dialog! Can somebody clarify, how it's done? Or maybe i misunderstood something.

**Comment by yurydelendik** [comment]
Does it actually print or just doing "page layout"?

**Comment by aledoroshenko** [comment]
Well, i don't have a printer to test actual printing, but when i hit print on test page, i have this dialog after page prepared:

![image](https://cloud.githubusercontent.com/assets/981275/5958541/8f00e7c4-a7d6-11e4-82a4-8cd6e03153f0.png)

So i suppose `window.print()` actually worked there? Then i was able to click on virtual Google printer from there, and get option to save resulting pdf to Google Disk, but it was just two blank pages.

**Comment by timvandermeij** [comment]
If Apple accepts `window.print()` like normal browsers do, then it should work just fine. Otherwise there does not seem to be much we can do. Recently a few patches landed to fix up printing with Chrome, so it should be working fine now. If not, please open a follow-up issue with steps to reproduce and a test PDF file. Closing as answered.

**Comment by sangyi7** [comment]
I have the same symptoms if I change the print.
