### ISSUE TITLE
Question regarding Pdf.js

### ISSUE THREAD

**Issue by anantwaykar** [mozilla/pdf.js#5689]
Hello friends,

Using pdf.js is it possible to track pdf page views, open or not. for eg suppose pdf has 10 pages then I want to track out of 10 pages which is most readable and least readable page from the marketing point of view.
If yes what is the process of trackng.

Thanks.

**Comment by yurydelendik** [comment]
The current PDF Viewer does not collect such information. However your custom solution may track the visible pages, e.g. during scrolling or with specific interval. Currently we don't finalize API, but you can see  getVisiblePages usage at https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L551 to draw only visiblepage.

Closing as answered.
