### ISSUE TITLE
downloadable font: cmap: failed to parse table (font-family: "g_font_5"

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#5690]
With Firefox 35.01 on Windows 8.1( HWA is on)
https://cdn.gonitro.com/img/primo/PrimoPDF_V5_User_Guide.pdf
shows error in console

"PDF 3267576565f948b08dba0521895c7b8e [1.4 Acrobat Distiller 8.1.0 (Windows) / Acrobat PDFMaker 8.1 for Word] (PDF.js: 1.0.1132)" viewer.js:6212
downloadable font: cmap: Range glyph reference too high (2 > 1) (font-family: "g_font_5" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKbjKy4AAACcAAAC+k9TLzJEMyxhAAADmAAAAGBjbWFwySkrQQAAA/gAAACkaGVhZKsnUAUAAAScAAAANmhoZWEDxgHQAAAE1AAAACRobXR4APoAAAAABPgAAAAIbWF4cAACUAAAAAUAAAAABm5hbWVMQvvqAAAFCAAAAlhwb3N0AAMAAAAAB2AAAAAgAQAEAgABAQEcUEhOQ0RNK0F2ZW5pck5leHRMVFByby1Cb2xkAAEBASz4GwH4FAQdAAZOkw37VvuOHAS6+lcFHQAAAlsRHQAAAB8dAAAC2hL4HAwWAAICAAEB6AH8Q29weXJpZ2h0IKkgMjAwNCAtIDIwMDYgTGlub3R5cGUgR21iSCwgd3d3Lmxpbm90eXBlLmNvbS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4gVGhpcyBmb250IHNvZnR3YXJlIG1heSBub3QgYmUgcmVwcm9kdWNlZCwgbW9kaWZpZWQsIGRpc2Nsb3NlZCBvciB0cmFuc2ZlcnJlZCB3aXRob3V0IHRoZSBleHByZXNzIHdyaXR0ZW4gYXBwcm92YWwgb2YgTGlub3R5cGUgR21iSC4gQXZlbmlyIGlzIGEgdHJhZGVtYXJrIG9mIEhlaWRlbGJlcmdlciBEcnVja21hc2NoaW5lbiBBRywgZXhjbHVzaXZlbHkgbGljZW5zZWQgdGhyb3VnaCBMaW5vdHlwZSBHbWJILCBhbmQgbWF5IGJlIHJlZ2lzdGVyZWQgaW4gY2VydGFpbiBqdXJpc2RpY3Rpb25zLiBUaGlzIHR5cGVmYWNlIGlzIG9yaWdpbmFsIGFydHdvcmsgb2YgQWRyaWFuIEZydXRpZ2VyIGFuZCBBa2lyYSBLb2JheWFzaGkuIFRoZSBkZXNpZ24gbWF5IGJlIHByb3RlY3RlZCBpbiBjZXJ0YWluIGp1cmlzZGljdGlvbnMuIEF2ZW5pck5leHRMVFByby1Cb2xkAAAAAAIBAXd6+JS9zs69+AvFAb3V95faA/dy9wkVzsNIB1b3CRWJnAWwj6aUnB6UnJqfoaEItrSSnKQau2iwYmJqcEeDHlmTBeqUwbXTG9LAVzxgf21YXB9ydX16h34Ih36Jc2ga91P7TBX4/fww/P0H+GL5MBX9YvyU+WIHDveODnie+Iab91aeBvuEiwceCgOWPwwJ9w4K9zsL9w6hDAwAAAAAAwIkAfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAABgAAAAAAAAAAAAADEAAAAAAAAAAAAAAAKjIxKgAAACDgAAPD/wYAZAPDAPoAAAAAAAAAAAH1AskAAAAgAAMAAAABAAMAAQAAAAwABACYAAAAIgAgAAQAAgB+AKwArwC0AL0AvwDIAMsA0ADhAOMA6wDxAPUA++AA//8AAAAgAKEArgCxALYAvwDBAMoAzQDhAOMA6ADxAPUA+OAA////4f+//7//vv+9/7z/u/+6/7n/qf+o/6T/n/+c/5ogbAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAF8PPPUAAAPoAAAAAJ4LficAAAAAngt+JwAA/wYP/wPDAAAAEQAAAAAAAAAAAAEAAAPD/wYAAP//AAAAAAAAAskAAAAAAAAAAAAAAAAAAAACAAAAAAD6AAAAAFAAAAIAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABABsAEAABAAAAAAACAAcAKwABAAAAAAADAAgAMgABAAAAAAAEABsAOgABAAAAAAAFAAwAVQABAAAAAAAGAAAAYQABAAAAAAAHAAcAYQABAAAAAAAIAAcAaAABAAAAAAAJAAcAbwADAAEECQAAACAAdgADAAEECQABADYAlgADAAEECQACAA4AzAADAAEECQADABAA2gADAAEECQAEADYA6gADAAEECQAFABgBIAADAAEECQAGAAABOAADAAEECQAHAA4BOAADAAEECQAIAA4BRgADAAEECQAJAA4BVE9yaWdpbmFsIGxpY2VuY2VQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRVbmtub3dudW5pcXVlSURQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA viewer.html
downloadable font: cmap: failed to parse table (font-family: "g_font_5" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKbjKy4AAACcAAAC+k9TLzJEMyxhAAADmAAAAGBjbWFwySkrQQAAA/gAAACkaGVhZKsnUAUAAAScAAAANmhoZWEDxgHQAAAE1AAAACRobXR4APoAAAAABPgAAAAIbWF4cAACUAAAAAUAAAAABm5hbWVMQvvqAAAFCAAAAlhwb3N0AAMAAAAAB2AAAAAgAQAEAgABAQEcUEhOQ0RNK0F2ZW5pck5leHRMVFByby1Cb2xkAAEBASz4GwH4FAQdAAZOkw37VvuOHAS6+lcFHQAAAlsRHQAAAB8dAAAC2hL4HAwWAAICAAEB6AH8Q29weXJpZ2h0IKkgMjAwNCAtIDIwMDYgTGlub3R5cGUgR21iSCwgd3d3Lmxpbm90eXBlLmNvbS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4gVGhpcyBmb250IHNvZnR3YXJlIG1heSBub3QgYmUgcmVwcm9kdWNlZCwgbW9kaWZpZWQsIGRpc2Nsb3NlZCBvciB0cmFuc2ZlcnJlZCB3aXRob3V0IHRoZSBleHByZXNzIHdyaXR0ZW4gYXBwcm92YWwgb2YgTGlub3R5cGUgR21iSC4gQXZlbmlyIGlzIGEgdHJhZGVtYXJrIG9mIEhlaWRlbGJlcmdlciBEcnVja21hc2NoaW5lbiBBRywgZXhjbHVzaXZlbHkgbGljZW5zZWQgdGhyb3VnaCBMaW5vdHlwZSBHbWJILCBhbmQgbWF5IGJlIHJlZ2lzdGVyZWQgaW4gY2VydGFpbiBqdXJpc2RpY3Rpb25zLiBUaGlzIHR5cGVmYWNlIGlzIG9yaWdpbmFsIGFydHdvcmsgb2YgQWRyaWFuIEZydXRpZ2VyIGFuZCBBa2lyYSBLb2JheWFzaGkuIFRoZSBkZXNpZ24gbWF5IGJlIHByb3RlY3RlZCBpbiBjZXJ0YWluIGp1cmlzZGljdGlvbnMuIEF2ZW5pck5leHRMVFByby1Cb2xkAAAAAAIBAXd6+JS9zs69+AvFAb3V95faA/dy9wkVzsNIB1b3CRWJnAWwj6aUnB6UnJqfoaEItrSSnKQau2iwYmJqcEeDHlmTBeqUwbXTG9LAVzxgf21YXB9ydX16h34Ih36Jc2ga91P7TBX4/fww/P0H+GL5MBX9YvyU+WIHDveODnie+Iab91aeBvuEiwceCgOWPwwJ9w4K9zsL9w6hDAwAAAAAAwIkAfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAABgAAAAAAAAAAAAADEAAAAAAAAAAAAAAAKjIxKgAAACDgAAPD/wYAZAPDAPoAAAAAAAAAAAH1AskAAAAgAAMAAAABAAMAAQAAAAwABACYAAAAIgAgAAQAAgB+AKwArwC0AL0AvwDIAMsA0ADhAOMA6wDxAPUA++AA//8AAAAgAKEArgCxALYAvwDBAMoAzQDhAOMA6ADxAPUA+OAA////4f+//7//vv+9/7z/u/+6/7n/qf+o/6T/n/+c/5ogbAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAF8PPPUAAAPoAAAAAJ4LficAAAAAngt+JwAA/wYP/wPDAAAAEQAAAAAAAAAAAAEAAAPD/wYAAP//AAAAAAAAAskAAAAAAAAAAAAAAAAAAAACAAAAAAD6AAAAAFAAAAIAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABABsAEAABAAAAAAACAAcAKwABAAAAAAADAAgAMgABAAAAAAAEABsAOgABAAAAAAAFAAwAVQABAAAAAAAGAAAAYQABAAAAAAAHAAcAYQABAAAAAAAIAAcAaAABAAAAAAAJAAcAbwADAAEECQAAACAAdgADAAEECQABADYAlgADAAEECQACAA4AzAADAAEECQADABAA2gADAAEECQAEADYA6gADAAEECQAFABgBIAADAAEECQAGAAABOAADAAEECQAHAA4BOAADAAEECQAIAA4BRgADAAEECQAJAA4BVE9yaWdpbmFsIGxpY2VuY2VQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRVbmtub3dudW5pcXVlSURQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA viewer.html
downloadable font: rejected by sanitizer (font-family: "g_font_5" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKbjKy4AAACcAAAC+k9TLzJEMyxhAAADmAAAAGBjbWFwySkrQQAAA/gAAACkaGVhZKsnUAUAAAScAAAANmhoZWEDxgHQAAAE1AAAACRobXR4APoAAAAABPgAAAAIbWF4cAACUAAAAAUAAAAABm5hbWVMQvvqAAAFCAAAAlhwb3N0AAMAAAAAB2AAAAAgAQAEAgABAQEcUEhOQ0RNK0F2ZW5pck5leHRMVFByby1Cb2xkAAEBASz4GwH4FAQdAAZOkw37VvuOHAS6+lcFHQAAAlsRHQAAAB8dAAAC2hL4HAwWAAICAAEB6AH8Q29weXJpZ2h0IKkgMjAwNCAtIDIwMDYgTGlub3R5cGUgR21iSCwgd3d3Lmxpbm90eXBlLmNvbS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4gVGhpcyBmb250IHNvZnR3YXJlIG1heSBub3QgYmUgcmVwcm9kdWNlZCwgbW9kaWZpZWQsIGRpc2Nsb3NlZCBvciB0cmFuc2ZlcnJlZCB3aXRob3V0IHRoZSBleHByZXNzIHdyaXR0ZW4gYXBwcm92YWwgb2YgTGlub3R5cGUgR21iSC4gQXZlbmlyIGlzIGEgdHJhZGVtYXJrIG9mIEhlaWRlbGJlcmdlciBEcnVja21hc2NoaW5lbiBBRywgZXhjbHVzaXZlbHkgbGljZW5zZWQgdGhyb3VnaCBMaW5vdHlwZSBHbWJILCBhbmQgbWF5IGJlIHJlZ2lzdGVyZWQgaW4gY2VydGFpbiBqdXJpc2RpY3Rpb25zLiBUaGlzIHR5cGVmYWNlIGlzIG9yaWdpbmFsIGFydHdvcmsgb2YgQWRyaWFuIEZydXRpZ2VyIGFuZCBBa2lyYSBLb2JheWFzaGkuIFRoZSBkZXNpZ24gbWF5IGJlIHByb3RlY3RlZCBpbiBjZXJ0YWluIGp1cmlzZGljdGlvbnMuIEF2ZW5pck5leHRMVFByby1Cb2xkAAAAAAIBAXd6+JS9zs69+AvFAb3V95faA/dy9wkVzsNIB1b3CRWJnAWwj6aUnB6UnJqfoaEItrSSnKQau2iwYmJqcEeDHlmTBeqUwbXTG9LAVzxgf21YXB9ydX16h34Ih36Jc2ga91P7TBX4/fww/P0H+GL5MBX9YvyU+WIHDveODnie+Iab91aeBvuEiwceCgOWPwwJ9w4K9zsL9w6hDAwAAAAAAwIkAfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAABgAAAAAAAAAAAAADEAAAAAAAAAAAAAAAKjIxKgAAACDgAAPD/wYAZAPDAPoAAAAAAAAAAAH1AskAAAAgAAMAAAABAAMAAQAAAAwABACYAAAAIgAgAAQAAgB+AKwArwC0AL0AvwDIAMsA0ADhAOMA6wDxAPUA++AA//8AAAAgAKEArgCxALYAvwDBAMoAzQDhAOMA6ADxAPUA+OAA////4f+//7//vv+9/7z/u/+6/7n/qf+o/6T/n/+c/5ogbAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAF8PPPUAAAPoAAAAAJ4LficAAAAAngt+JwAA/wYP/wPDAAAAEQAAAAAAAAAAAAEAAAPD/wYAAP//AAAAAAAAAskAAAAAAAAAAAAAAAAAAAACAAAAAAD6AAAAAFAAAAIAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABABsAEAABAAAAAAACAAcAKwABAAAAAAADAAgAMgABAAAAAAAEABsAOgABAAAAAAAFAAwAVQABAAAAAAAGAAAAYQABAAAAAAAHAAcAYQABAAAAAAAIAAcAaAABAAAAAAAJAAcAbwADAAEECQAAACAAdgADAAEECQABADYAlgADAAEECQACAA4AzAADAAEECQADABAA2gADAAEECQAEADYA6gADAAEECQAFABgBIAADAAEECQAGAAABOAADAAEECQAHAA4BOAADAAEECQAIAA4BRgADAAEECQAJAA4BVE9yaWdpbmFsIGxpY2VuY2VQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRVbmtub3dudW5pcXVlSURQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA viewer.html
downloadable font: font load failed (font-family: "g_font_5" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIKbjKy4AAACcAAAC+k9TLzJEMyxhAAADmAAAAGBjbWFwySkrQQAAA/gAAACkaGVhZKsnUAUAAAScAAAANmhoZWEDxgHQAAAE1AAAACRobXR4APoAAAAABPgAAAAIbWF4cAACUAAAAAUAAAAABm5hbWVMQvvqAAAFCAAAAlhwb3N0AAMAAAAAB2AAAAAgAQAEAgABAQEcUEhOQ0RNK0F2ZW5pck5leHRMVFByby1Cb2xkAAEBASz4GwH4FAQdAAZOkw37VvuOHAS6+lcFHQAAAlsRHQAAAB8dAAAC2hL4HAwWAAICAAEB6AH8Q29weXJpZ2h0IKkgMjAwNCAtIDIwMDYgTGlub3R5cGUgR21iSCwgd3d3Lmxpbm90eXBlLmNvbS4gQWxsIHJpZ2h0cyByZXNlcnZlZC4gVGhpcyBmb250IHNvZnR3YXJlIG1heSBub3QgYmUgcmVwcm9kdWNlZCwgbW9kaWZpZWQsIGRpc2Nsb3NlZCBvciB0cmFuc2ZlcnJlZCB3aXRob3V0IHRoZSBleHByZXNzIHdyaXR0ZW4gYXBwcm92YWwgb2YgTGlub3R5cGUgR21iSC4gQXZlbmlyIGlzIGEgdHJhZGVtYXJrIG9mIEhlaWRlbGJlcmdlciBEcnVja21hc2NoaW5lbiBBRywgZXhjbHVzaXZlbHkgbGljZW5zZWQgdGhyb3VnaCBMaW5vdHlwZSBHbWJILCBhbmQgbWF5IGJlIHJlZ2lzdGVyZWQgaW4gY2VydGFpbiBqdXJpc2RpY3Rpb25zLiBUaGlzIHR5cGVmYWNlIGlzIG9yaWdpbmFsIGFydHdvcmsgb2YgQWRyaWFuIEZydXRpZ2VyIGFuZCBBa2lyYSBLb2JheWFzaGkuIFRoZSBkZXNpZ24gbWF5IGJlIHByb3RlY3RlZCBpbiBjZXJ0YWluIGp1cmlzZGljdGlvbnMuIEF2ZW5pck5leHRMVFByby1Cb2xkAAAAAAIBAXd6+JS9zs69+AvFAb3V95faA/dy9wkVzsNIB1b3CRWJnAWwj6aUnB6UnJqfoaEItrSSnKQau2iwYmJqcEeDHlmTBeqUwbXTG9LAVzxgf21YXB9ydX16h34Ih36Jc2ga91P7TBX4/fww/P0H+GL5MBX9YvyU+WIHDveODnie+Iab91aeBvuEiwceCgOWPwwJ9w4K9zsL9w6hDAwAAAAAAwIkAfQABQAAAooCuwAAAIwCigK7AAAB3wAxAQIAAAAABgAAAAAAAAAAAAADEAAAAAAAAAAAAAAAKjIxKgAAACDgAAPD/wYAZAPDAPoAAAAAAAAAAAH1AskAAAAgAAMAAAABAAMAAQAAAAwABACYAAAAIgAgAAQAAgB+AKwArwC0AL0AvwDIAMsA0ADhAOMA6wDxAPUA++AA//8AAAAgAKEArgCxALYAvwDBAMoAzQDhAOMA6ADxAPUA+OAA////4f+//7//vv+9/7z/u/+6/7n/qf+o/6T/n/+c/5ogbAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAAAF8PPPUAAAPoAAAAAJ4LficAAAAAngt+JwAA/wYP/wPDAAAAEQAAAAAAAAAAAAEAAAPD/wYAAP//AAAAAAAAAskAAAAAAAAAAAAAAAAAAAACAAAAAAD6AAAAAFAAAAIAAAAAABQA9gABAAAAAAAAABAAAAABAAAAAAABABsAEAABAAAAAAACAAcAKwABAAAAAAADAAgAMgABAAAAAAAEABsAOgABAAAAAAAFAAwAVQABAAAAAAAGAAAAYQABAAAAAAAHAAcAYQABAAAAAAAIAAcAaAABAAAAAAAJAAcAbwADAAEECQAAACAAdgADAAEECQABADYAlgADAAEECQACAA4AzAADAAEECQADABAA2gADAAEECQAEADYA6gADAAEECQAFABgBIAADAAEECQAGAAABOAADAAEECQAHAA4BOAADAAEECQAIAA4BRgADAAEECQAJAA4BVE9yaWdpbmFsIGxpY2VuY2VQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRVbmtub3dudW5pcXVlSURQSE5DRE0rQXZlbmlyTmV4dExUUHJvLUJvbGRWZXJzaW9uIDAuMTFVbmtub3duVW5rbm93blVua25vd24ATwByAGkAZwBpAG4AYQBsACAAbABpAGMAZQBuAGMAZQBQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABVAG4AawBuAG8AdwBuAHUAbgBpAHEAdQBlAEkARABQAEgATgBDAEQATQArAEEAdgBlAG4AaQByAE4AZQB4AHQATABUAFAAcgBvAC0AQgBvAGwAZABWAGUAcgBzAGkAbwBuACAAMAAuADEAMQBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AVQBuAGsAbgBvAHcAbgADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA viewer.html

But on another machine (Firefox 35.01 on Windows 7, HWA is off), there is no error in the console.

**Comment by timvandermeij** [comment]
Closing as fixed by #6715.
