### ISSUE TITLE
Hyperlink displays incorrectly

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5694]
http://www.karger.com/Article/Pdf/368404

The above PDF displays the hyperlink at the top incorrectly.

Using Chrome 39, Windows 8.1 x64 and PDF.js 1.0.1132 (latest)

PDF.js
![image](https://cloud.githubusercontent.com/assets/10129039/6009031/0161e530-ab1e-11e4-89f9-101949c6a0cc.png)

Adobe Acrobat
![image](https://cloud.githubusercontent.com/assets/10129039/6009038/12b7fee6-ab1e-11e4-9d1b-6f479cefe38e.png)

**Comment by timvandermeij** [comment]
That particular annotation has a `/U` (underline) border style, which PDF.js currently does not support. However, #5585 will add support for this and fix this issue largely (only the spacing of the border is not entirely correct with that patch).
