### ISSUE TITLE
singlefile build "Setting up fake worker"

### ISSUE THREAD

**Issue by robrez** [mozilla/pdf.js#5695]
Sorry if this has been answered elsewhere.

I'm trying to make a vulcanized polymer component the imports pdf.combined.js.

I get a console warning -- pdf.combined.js:235  "Warning: Setting up fake worker."

Please help.  Is there a way to specify a worker outside of pointing to a src file?  For example, if i've imported pdf.js and pdf.worker.js... can I just say "PDFJS.worker = new Worker()" instead of "PDFJS.workerSrc = '/path/to/worker.js'"

**Comment by yurydelendik** [comment]
>  Is there a way to specify a worker outside of pointing to a src file? For example, if i've imported pdf.js and pdf.worker.js... can I just say "PDFJS.worker = new Worker()" instead of "PDFJS.workerSrc = '/path/to/worker.js'"

Don't use pdf.combined.js file it you are planing to use a worker, use pdf.js/pdf.worker.js files.  pdf.combined.js is designed to disable any local usage and to be a single file.

You can certainly do that. But PDF.js designed to test capabilities of a worker  of different platforms and fallback to the standard script loading.

Could you explain in details why you think "PDFJS.worker = new Worker()"  feature will be something web developers will be using?

**Comment by robrez** [comment]
Thanks for the speedy response. I've only just started tinkering w/ pdf.js and I may not clearly understand the nature of "workerSrc" / .worker.js.

Maybe my particular use-case can provide more insight...

I'm trying to create a Polymer PDF component.  To cut down on network requests, the component is "vulcanized" to _inline_ include pdf.js as well as pdf.worker.js.  Since pdf.worker.js has already been inlined, my thought is that PDFJS shouldn't need to have a path to that script. My train of thought is that I ought to be able to directly instantiate a new worker, instead.

**Comment by yurydelendik** [comment]
I don't really following "to directly instantiate a new worker" thought. To instantiate a web worker you need to provide a path to the javascript file. (if you will use pdf.combined.js twice, you will just waste lots of CPU on main and worker thread to parse useless javascript code)

**Comment by yurydelendik** [comment]
Closing as answered for now. See https://html.spec.whatwg.org/multipage/workers.html#dom-worker for documentation about Web Workers.

**Comment by robrez** [comment]
Sorry for my ignorance -- I didn't realize that worker was part of the html standard / thought it was proprietary to pdfjs.

Thanks
