### ISSUE TITLE
Checkboxes filled in black

### ISSUE THREAD

**Issue by asinner** [mozilla/pdf.js#5696]
I'm using PDF.js to render some PDFs and I've encountered this problem - all checkbox inputs have been filled in black. I've read issues regarding:

1. Images turning black
2. Checkboxes converted to numbers...

But not checkboxes turned black. 

This issue occurs in Chrome 40, 
This is not in an issue in FF 35, Safari 8.

**FF & Safari**

![screenshot 2015-02-03 17 27 11](https://cloud.githubusercontent.com/assets/1994042/6033531/baa95be2-abcb-11e4-8bc7-8a1ef812e9cf.png)

**Chrome**

![screenshot 2015-02-03 17 24 55](https://cloud.githubusercontent.com/assets/1994042/6033532/baaa2450-abcb-11e4-9abd-1638cf56e26f.png)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read (especially the first paragraph) https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. I'm also quoting the most relevant part:
> [...] provide more details about the issue: **link to the PDF**, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages.

**Comment by asinner** [comment]
I cannot link to the PDF in question as that would violate the FERPA law governing the document in question. Other details I can provide:

- Location in PDF all pages
- Screenshots included in original comments
- Browser versions included in original comment
- Console messages:
PDF 6eec7551c2b48bd34b8bf48e9d2a5 [1.6 Mac OS X 10.9.5 Quartz PDFContext / FileMaker Pro] (PDF.js: 1.0.712)

**Comment by timvandermeij** [comment]
If you render the PDFs yourself, can't you create one with dummy content so we can use that as a test? Otherwise there is not much we can do about this issue I'm afraid...

**Comment by asinner** [comment]
Here is a heavily redacted version of the original file. All meta-data has been kept, and the sections containing the offending checkboxes have been kept.

https://www.dropbox.com/s/euwvi3jrxl03ctf/pdf-js-issue-redacted-2.pdf?dl=0

**Comment by Rob--W** [comment]
@asinner That PDF is just a set of images (bitmaps), and useless for debugging.

Could you share the tool that was used to create this PDF or find/create a similar PDF?

An alternative way to help is to debug the issue yourself (about 20 - 60 minutes, depending on whether you follow through to the last step):

1. Enable the debugging tools: https://github.com/mozilla/pdf.js/wiki/Debugging-PDF.js (set pdfBugEnabled to true, and append `#pdfBug=all` to the URL, then press Enter, focus the URL and press Enter again (or perhaps `#pdfBug=all&disableWorker=true` to make sure that the whole application is single-threaded).
2. When the stepper shows up, try to find the operator range that paints the checkbox. A binary search is quite effective.
3. After identifying the operator list, try to match the operator with code in PDF.js, e.g. by searching for the operator name in `src/`. Once you've found the relevant area, put JavaScript breakpoints (via Chrome's developer tools), and check whether the logic in PDF.js looks fine.
4. If PDF.js seems to be ok, this might be a bug in Chrome (canvas). Try to create a minimal test case and report the bug at https://crbug.com/new. See https://github.com/mozilla/pdf.js/issues/5043#issuecomment-48972506 for instructions on debugging canvas.

If you don't want to debug yourself and cannot share any PDF, send me a mail to see how we can proceed further (e.g. a remote debugging session).

**Comment by Snuffleupagus** [comment]
Since this issue appears to be identical to #5932, and given that the "test-case" provided here is just an image of the problematic PDF file (compared to #5932, which has working test-case), I'm closing this issue as a duplicate.
