### ISSUE TITLE
Searching by whole word

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#5697]
Hello!
I want to make the possibility of a whole word search.
For example, if I search for 'up', I want to see in the search results just a 'up', not  'startUP' or 'sUPports'.
I understand that it is contrary to Firefox's built-in highlight behavior, but it is necessary for my application.
The main problem that I faced is the inability to determine a line break in the text extracted from the page (on viewer layer).
In PDFFindController_extractText() function we get text from PDF document to pageContents variable, but all lines on page are glued.
Tell me, please, can I some way to split a strings in extracted text on viewer layer?
Or need to change core layer? If yes, where is the best place in code for this changes?

**Comment by jazzy-em** [comment]
May be line break can be detected in 'case OPS.moveText:' (core/evaluator.js, PartialEvaluator_getTextContent(...))? Or is this the wrong way?

**Comment by ananyaojha** [comment]
I want to call a function once the pdf finished loading. May I know which line is the exact place? N which file too.

**Comment by timvandermeij** [comment]
@ananyaojha Please do not post unrelated questions in issues. Use the mailing list for your question instead: https://groups.google.com/forum/#!forum/mozilla.dev.pdf-js

**Comment by chitgoks** [comment]
im curious with this feature. is there a plan to add this? 

if so, would love to find the link for progress. would love to track this.

**Comment by Snuffleupagus** [comment]
> For example, if I search for 'up', I want to see in the search results just a 'up', not 'startUP' or 'sUPports'.

@timvandermeij This issue could probably be closed now, since the feature described above was implemented by PR #10028.

**Comment by timvandermeij** [comment]
Closing since this is indeed fixed by the PR above.
