### ISSUE TITLE
Image element display problem in PDF.js

### ISSUE THREAD

**Issue by sambose** [mozilla/pdf.js#5698]
Dear All,

PDF.js doesn't display an image on my pdf file, this element is in header of my file. I couldn't find the same problem that i have.

![2](https://cloud.githubusercontent.com/assets/3242937/6039587/aac2245e-ac7d-11e4-8b56-e84e2b5461d1.png)

my sample will be found in [here](http://www.asidesigner.com/R.pdf) 

Regards,
Sambose

**Comment by timvandermeij** [comment]
The images show up for a brief second for me and then disappear all of a sudden (Windows 7 x64 and the latest PDF.js development version).

**Comment by Snuffleupagus** [comment]
> The images show up for a brief second for me and then disappear all of a sudden

I believe that this may be a red herring, since the image (the red/white one) in the top left corner *does not* show up even briefly. That one isn't actually a "standard" image, but rather a `TilingPattern`.

**Comment by sambose** [comment]
but it show up in the adobe acrobat reader.
