### ISSUE TITLE
Problems with rendering Myriad Pro font, fallbacks to other one damaging UTF-8 characters

### ISSUE THREAD

**Issue by radzikod** [mozilla/pdf.js#5702]
Hi,

I've encountered a problem with viewing a PDF file generated from my application. It works on any other viewer I tried, but when using FF with PDF.js the browser seems to have problems with rendering Myriad Pro font and it fallbacks to other one (I guess), in which UTF-8 characters are damaged:

![scr](https://cloud.githubusercontent.com/assets/5390129/6061597/5c1a2690-ad49-11e4-9ad4-a3f3f608d128.png)

What I got in console window is:

<code>"[l10n] #page_scale_percent missing for [pl]" l10n.js:16</code>

<code>"PDF 5209b7f2956bc33e5a7e9903242ecbf1 1.5 iText 2.1.7 by 1T3XT / BIRT Report Engine <i>(...)</i> using iText <i>(...)</i> (PDF.js: 1.0.1135)" viewer.js:6115</code>

<code>downloadable font: cmap: Range glyph reference too high (848 > 847) (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIEBk/N4AAACcAABBIk9TLzJEfarGAABBwAAAAGBjbWFweH2+LwAAQiAAAAPwaGVhZKsnT/oAAEYQAAAANmhoZWEDuwT3AABGSAAAACRobXR4ARgAAAAARmwAAA1AbWF4cANQUAAAAFOsAAAABm5hbWWylmFIAABTtAAAAohwb3N0AAMAAAAAVjwAAAAgAQAEAgABAQESTXlyaWFkUHJvLVJlZ3VsYXIAAQEBRfqJ+oqLDB76hgD6hwH6iAL6iAP4GAT7MfuO+vr6TAUdAAAmug8dAAAmvxEdAAAAAB0AAAAAEh0AADcvDCUdAAA3NwwkAnECAAEABwAKAA4AEgAZAB8AIgAmADIAPQBBAEgASgBNAFIAVwBcAF8AYgBlAGcAcQB1AH8AiACVAKEArQC7AMgA1QDhAO8A/QEKARoBJQEvATkBRQFQAVsBZQFxAX0BiAGYAagBtwHGAdcB5wH3AgYCFwIoAjgCSgJaAmoCfAKQAp8CtQLCAs4C2gLoAvUDAgMOAxwDKgM3A0YDVANjA3ADfwORA6QDsQO9A8kD1wPkA/ED/QQLBBkEJgQ1BEMEUgRfBG4EgASTBKEErgS7BMoE2ATmBPMFAgURBR8FLwU+BU4FXAVsBX8FkwWjBbIFwQXSBeIF8gYBBhIGIwYzBkUGVgZoBngGigafBrUGuwbFBs8G3QbuBwAHEQcjBy0HPQdKB1gHZwd3B4QHkgekB60HuQfEB8wH1AfbB+MH7gf1B/wIBQgKCA8IEQgbCCEIKAgvCDQIOghACEsIVQhbCGEIZwhxCH file.pdf</code>

<code>downloadable font: cmap: failed to parse table (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,<i>(...base64 content...)</i> file.pdf</code>

<code>downloadable font: rejected by sanitizer (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,<i>(...base64 content...)</i> file.pdf</code>

<code>downloadable font: font load failed (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0)
source: data:font/opentype;base64,<i>(...base64 content...)</i> file.pdf</code>

What is wrong with Myriad Pro and how to handle it? Why the other font damages UTF-8 characters?

<a href="https://www.dropbox.com/s/aqlabg9l78bjh8v/file.pdf?dl=0">File can be downloaded here.</a>

**Comment by Snuffleupagus** [comment]
Closing as fixed by #6715.
