### ISSUE TITLE
Ø (LATIN CAPITAL LETTER O WITH STROKE) doesn't appear

### ISSUE THREAD

**Issue by mikemorr** [mozilla/pdf.js#5704]
In this PDF: http://www.jazzbooks.com/mm5/download/FREE-nomenclature.pdf
the character Ø (U+00D8, LATIN CAPITAL LETTER O WITH STROKE) doesn't appear. Issue occurs on both Windows and Mac. Screenshots from http://mozilla.github.io/pdf.js/web/viewer.html and Adobe Reader:
![pdfjs](https://cloud.githubusercontent.com/assets/2184268/6082595/97430140-adf0-11e4-962d-311fa3bed203.png)
![adobereader](https://cloud.githubusercontent.com/assets/2184268/6082597/9aaf0ab8-adf0-11e4-9ca9-cf04827587dc.png)

**Comment by Snuffleupagus** [comment]
This is a regression from PR #4259.
