### ISSUE TITLE
PDF's headline is distorted in Ubuntu and in Android

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#5706]
The PDF is:
http://www.iip.or.jp/summary/pdf/detail02j/14_01.pdf

The headline of the first page is distorted like:
![sangyo-pdfjs](https://cloud.githubusercontent.com/assets/3334552/6078597/db051a10-ae3d-11e4-8e07-fbb72e013271.jpg)

I tested it with Firefox on Ubuntu 14.04 and some Android machines. This error did not occur on either Windows or on Mac.

**Comment by timvandermeij** [comment]
Looks good to me on Arch Linux with Firefox 37.0.1.

@takahiroyoshi Could you download the file and open it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar)? That is to see if your PDF.js version is perhaps old. If it works there, this bug is resolved.

**Comment by timvandermeij** [comment]
Closing as fixed (there have been a lot font fixes since the creation date of this issue). Please provide the request information to reopen if there are still problems.
