### ISSUE TITLE
PDF is rendering almost all black

### ISSUE THREAD

**Issue by nevosegal** [mozilla/pdf.js#5712]
I'm trying to display a pdf and it gets rendered weirdly. In some locations it looks like it renders the inverse colours and in other cases it renders pitch black. You can find a link to it on http://nevosegal.github.io/pdfjs_issue/test.pdf.

This is happening on Mac OSX v10.10.2 using both Firefox v35.0.1 and Chrome v40.0.2214.111 and pdf.js v1.0.907.

A screenshot of the issue:
![screen shot 2015-02-09 at 13 19 42](https://cloud.githubusercontent.com/assets/3370167/6107006/63bc769c-b05e-11e4-850c-5c2fd67958ae.png)

A screenshot of the original:
![screen shot 2015-02-09 at 13 10 29](https://cloud.githubusercontent.com/assets/3370167/6106849/140121a8-b05d-11e4-802e-0d12c0cb4081.png)

This was found by @jakubfiala and myself.

**Comment by Snuffleupagus** [comment]
[Edited the original issue with a direct link to the PDF file.]

**Comment by Snuffleupagus** [comment]
This worked better before PR #4161, so apparently we're not handling the SMask correctly.
