### ISSUE TITLE
ETA for next stable release?

### ISSUE THREAD

**Issue by jqnatividad** [mozilla/pdf.js#5716]
Per https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#version, are you close to marking a new stable release?

Just curious as we intend to create a CKAN extension to enable PDF viewing using pdf.js (https://github.com/ckan/ckanext-pdfview).  

CKAN is the platform that runs the largest data portals in the world like data.gov and data.gov.uk, and this extension will be a must-install for any CKAN implementation, and we'd rather embed something that's recent yet stable.

**Comment by timvandermeij** [comment]
We were planning to release 1.1, but there are some PRs that should/need to be merged before we can do so (especially font fixes). Maybe @yurydelendik knows more about this?

**Comment by timvandermeij** [comment]
The most recent stable version has been released at https://mozilla.github.io/pdf.js/getting_started/#download. Future releases will also be published there, so please keep an eye on that page. Closing as answered.
