### ISSUE TITLE
pdf.js very slow while loading the 6 pages content in IOS7

### ISSUE THREAD

**Issue by thangamani2015** [mozilla/pdf.js#5719]
I am using IOS7.1.1 pdf.js is opening very slow . Even i tried the sample too. Its getting loaded finally but it take time. Can you let me know why it is happening. This is happening the especially in IOS7. But its works well in IOS8 and Ipads.

Eventhough i have minified the pdf.js and pdf.worker.js, but is its same issue.

Please suggest how to fix this?

**Comment by yurydelendik** [comment]
> But its works well in IOS8 and Ipads.

Closing as won't fix for IOS7
