### ISSUE TITLE
caching of rendered content?

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5720]
Whenever I load a PDF that I've loaded before, the actual PDF data is cached from the browser. It seems that the rendered images (PNG?) are rendered every time anew. Is there a way to cache those, too?

**Comment by Rob--W** [comment]
Could you share a PDF file that clearly shows the issue that you've described?

**Comment by nschloe** [comment]
This already happens in the most simple example [1]: On a page reload, the PDF chunks are properly fetched from cache, and the pages are rendered anew. It occurs to me that the rendered page images could also be cached since verifyably we're rendering the same PDF.

[1] http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Rob--W** [comment]
Which images? When I look at the network traffic in the developer tools, the only images I see are those that are a part of the viewer UI.

Or are you referring to the fact that images are progressively rendered? That's not a caching issue. Rendering performance does not only depend on network performance, but also memory and computing power (parsing the PDF, parsing the image, painting the image).

**Comment by nschloe** [comment]
> Which images?

I'm assuming the PDF pages are rendered into images for display. Is that correct at all?

**Comment by Rob--W** [comment]
Each page in a PDF file is just a set of drawing commands. What you see is the result of evaluating each command, which can be anything ranging from displaying some text and painting an image. The result is painted on a `<canvas>` element. The text is also added to an invisible text layer in the DOM, which allows users to select (and copy) text.

If the drawing instructions are expensive (i.e. memory/time-consuming), then saving the painted result as an image (caching) *could* improve the time-to-display, at the cost of storage space (and engineering efforts to develop it). This could be an interesting experiment, but I reckon that most (web-optimized) PDFs can already be parsed and rendered relatively quickly.

What lead you to create this feature request, by the way? Did you observe any terrible performance that could be improved by this suggestion?

**Comment by nschloe** [comment]
> The result is painted on a <canvas> element.

Ah okay, I previously thought an image is created that is then displayed.

> If the drawing instructions are expensive (i.e. memory/time-consuming), then saving the painted 
> result as an image (caching) could improve the time-to-display, at the cost of storage space

That's what I had in mind.


> This could be an interesting experiment, but I reckon that most (web-optimized) PDFs can already be 
> parsed and rendered relatively quickly.

What are "web-optimized PDFs"? How can I optimize my PDFs for faster rendering?

> Did you observe any terrible performance that could be improved by this suggestion?

Not terrible, but notable [1] to a degree where I thought that the display of cached PNGs would be faster.

[1] http://win.ua.ac.be/~nschloe/other/pph.webm

**Comment by Rob--W** [comment]
By "web-optimized PDFs", I mean linearized PDFs, i.e. PDFs where the bits that describe a page are close to each other (so that the PDF engine can start parsing and rendering the page as soon as it has been loaded). If a PDF is not linearized, the time-to-render *is* heavily affected by network speed: parsing & rendering the PDF can only start when the necessary chunks of a PDF are available.

> Not terrible, but notable [1] to a degree where I thought that the display of cached PNGs would be faster
> [1] http://win.ua.ac.be/~nschloe/other/pph.webm

The page is rendered within a split second, looks fast enough to me, not?

**Comment by nschloe** [comment]
> By "web-optimized PDFs", I mean linearized PDFs, i.e. PDFs where the bits that describe a page are > close to each other

Thanks for the explanation. This actually led me to looking through my PDFs, noticing that many of them can be reduced by a great deal when applying some basic (GhostScript) optimizations.

> The page is rendered within a split second, looks fast enough to me, not?

It is fast indeed, but you do notice the build-up  and the flickering can get somewhat annoying when switching tabs. I assume you wouldn't see if the canvases were cached as images.

**Comment by Rob--W** [comment]
That flickering (Chrome, I presume?) is not something caused by PDF.js, but by the browser.

**Comment by nschloe** [comment]
> That flickering (Chrome, I presume?) is not something caused by PDF.js, but by the browser.

Well, yes, the browser re-renders the PDF on the canvas every time the tabs are switched, so technically, the build-up sequence is caused by the browser. Now, I'm interested in how to make it easier for the browser to render the canvas. Would you think that capturing the output in an image and caching that could help here? (The full-blown rendering process seems particularly wasteful for the thumbnails.)

**Comment by Rob--W** [comment]
Could you show a screencast where this problem is apparent? I don't recall having seen a significant latency in canvas rendering in Chromium.

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by damlatien** [comment]
I have a similar problem with FF39.
I have set up a local vhost with a (42Mb) pdf file to see if it was a problem with networking, and I am observing a long latency (4 to 5 seconds) everytime when I jump from the 1st pages to the last one (the index) with and without using the vhost. For big files such as big articles/books/etc... , it would be very useful to enable caching of already rendered pages, at least as an option for the user.

**Comment by Rob--W** [comment]
Caching the final rendering of a heavy page sounds like a good usability improvement to me.

Something along the lines of "if the page takes more than X milliseconds to render, store a PNG snapshot of the canvas in a LRU cache". The amount of disk space used by PDF.js is currently minimal, implementing this feature request would require a change in this characteristic.

**Comment by Zykino** [comment]
I would like this feature, even as an option disabled by default.

I cannot provide a PDF but some pages are taking more than 10 seconds to render.
I know that the problem is the same on any PDF reader on **Linux** (not PDF.js specific) for the same PDF.
It occur when a I have a lot of images on the same pages and most of all images rendered by PDF.js.
The images are printed part by part (each polygone individually it seems).

For now I'm trying to manually cache every pages I load.

**Comment by redstoneleo** [comment]
It happens frequently that we need to open a pdf file a second time to finish reading it, in order to make pdf.js load pdf fast when loading the same pdf file a second time, I suggest pdf.js to save those common tasks such as parsing or conversion of last time for next time’s usage.

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX, since this is an old issue and the particular use-case looks somewhat specialized.
Hence it's not clear, at least to me, that the time/effort needed to both implement *and* then maintain/test this kind of functionality is worth it overall.
