### ISSUE TITLE
Text lost in IE9

### ISSUE THREAD

**Issue by liushenf** [mozilla/pdf.js#5722]
Please help to check this PDF: https://drive.google.com/file/d/0B5sTqArpFYNmY2tTM3BxQUo3RUU/view?usp=sharing
All the text lost in IE9. But it works fine in IE10 or FireFox.
![ie9_screenshot](https://cloud.githubusercontent.com/assets/10972551/6163499/31864a00-b2ce-11e4-8e33-c491c06b5d7e.png)

Thanks!

**Comment by liushenf** [comment]
Snuffleupagus, do we have plan to fix this IE9 issue? My application is in IE9 compatible mode, so it is really an issue for us. Thanks1

**Comment by timvandermeij** [comment]
IE9 is not supported anymore in PDF.js 2.0, so I'm closing this issue as won't fix.
