### ISSUE TITLE
Problem when printing a PDF generated file from website provider. Blank page rendered.

### ISSUE THREAD

**Issue by hermannedem** [mozilla/pdf.js#5724]
Hello. i've a serious problem. i'm a developper in Togo (west africa). Our official language is French, so i wish i could explain myself well in English to be understood.
​i have built a website in which i generate pdf files. it worked well but since last week, the generation of the file only is working in Google chrome but is not working in Mozilla Firefox or Internet Explorer.
I searched for a long and i didn't found a solution. 
- Browser : Firefox 35.0.1
- OS : Windows 8
- JavaScript console warning/error messages : "Une erreur s'est produite lors du chargement du fichier PDF. PDF.js v1.0.907 (identifiant de compilation : e9072ac) Message : invalid array length"
- Image : 
![capture_problem_pdf](https://cloud.githubusercontent.com/assets/10979891/6175481/1135e410-b2ef-11e4-823b-09b85563aad3.JPG)

Please help me.

**Comment by Snuffleupagus** [comment]
First of all, is this issue still present in the *latest* version (as of this writing `1.0.1143`) of PDF.js?
You can test this easily by opening the file in the demo viewer (click on the "Open File" button on the right-hand side of the toolbar): http://mozilla.github.io/pdf.js/web/viewer.html.

If the issue still exists in the latest version of PDF.js, then you *need* to provide a link to a PDF file that can be used to reproduce this issue (as outlined [in the first paragraph here](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md)).

**Comment by timvandermeij** [comment]
Closing as incomplete. Please provide the information mentioned above to reopen.
