### ISSUE TITLE
JPX.js fails to render J2K files

### ISSUE THREAD

**Issue by louismullie** [mozilla/pdf.js#5725]
From what I understand, JPEG 2000 (.jp2, .j2k) is a subset of JPEG 2000 Extended (.jpx, .jpf) - therefore JPX.js should be able to render J2K files.

However, working with JPEG2000 data extracted from the [Enterix data set](http://www.osirix-viewer.com/datasets/DATA/ENTERIX.zip), I get unexpected results with JPX.js as compared with openjpeg.js (and the openjpeg command line tool).

Result with jpk.js

![image](https://cloud.githubusercontent.com/assets/681636/6178149/5add7c64-b2da-11e4-8426-579e47b4c2cf.png)

Result with openjpeg.js

![image](https://cloud.githubusercontent.com/assets/681636/6178152/5d4dc260-b2da-11e4-95db-c402d312235d.png)

Here is the code I am using: https://gist.githubusercontent.com/louismullie/dca8a3fa351cc955b38f/raw/199dbfc000088b125dffa2235308d2baf73d0464/jpx-j2k-bug.html

Anybody have ideas as to what explains this kind of behaviour? Is JPX.js built to support J2K as a subset of JPX?

**Comment by louismullie** [comment]
Incidentally, JPX.js is much faster than openjpeg.js and could be incredibly useful as a standalone library for JPEG2000 reading in Javascript (one key application would be for use in DICOM web viewers). Are any of @ivmartel, @chafey and @mi-kas interested in contributing from this point of view?

The sheer [number of issues related to JPX.js](https://github.com/mozilla/pdf.js/issues?page=1&q=jpx) on this repository would be another argument in favour of making this a separate repo.

**Comment by Snuffleupagus** [comment]
@louismullie Could you please create a *PDF* file with that image, and provide a link to it here?
That would make testing this a a lot easier for us!

**Comment by jpambrun** [comment]
@louismullie look at my last comment in PR https://github.com/mozilla/pdf.js/pull/5727.

**Comment by louismullie** [comment]
Merci @jpambrun, the PR #5727 fixes this issue. Closing!
