### ISSUE TITLE
viewer.html#locale= not working on pdfjs-1.0.907

### ISSUE THREAD

**Issue by jesteves** [mozilla/pdf.js#5730]
Hello,

No much additional to say.  See, for example:  http://mozilla.github.io/pdf.js/web/viewer.html#locale=es

Thanks in advance,

Julián

**Comment by yurydelendik** [comment]
There is no default culture for 'es'; 'es-MX' or 'es-ES' shall be used. PDF.js project is not managing localization files, but borrowing then from the Firefox. If you have a custom solution, you are welcome to copy es-MX/-ES  into the es folder. Closing as won't fix.

**Comment by jesteves** [comment]
Sure, I get that.

(Being a Mexican myself I guess I can live perfectly with that ;-))

But (did you at least tried?) the same applies to es-MX, es-ES, fr-FR and, I'm pretty sure, anything but en-US.

See attached image.

I'm on Chrome 40.0.2214.111 / OS X 10.10.2

![compressed_tracemonkey-pldi-09_pdf_y_acta_90_2013_pdf_y_papelera](https://cloud.githubusercontent.com/assets/8601921/6197112/0095bf24-b3a6-11e4-9450-65181f9b8818.png)

**Comment by jesteves** [comment]
For sake of completeness:

*  Same behavior on Firefox 35.0.1
*  Same behavior on Opera 27.0
*  On Safari 8.0.3 seems to automatically use Spanish and then no other language can be selected via `locale#`

All my four browsers are on Spanish.

![compressed_tracemonkey-pldi-09_pdf_y_compressed_tracemonkey-pldi-09_pdf_y_viewer_html_locale__not_working_on_pdfjs-1_0_907_ _issue__5730_ _mozilla_pdf_js](https://cloud.githubusercontent.com/assets/8601921/6197416/6acc1574-b3aa-11e4-98a1-2a4aca8a8106.png)

**Comment by yurydelendik** [comment]
Please notice that you have to ("hard" on Chrome) refresh the page after you change stuff in URL bar, 'es-MX' works for me:

![screen shot 2015-02-13 at 6 39 03 pm](https://cloud.githubusercontent.com/assets/1523410/6197702/c0739c68-b3af-11e4-82cf-47d14174bec6.png)

**Comment by yurydelendik** [comment]
Also notice that we disabled this feature for production mode, see https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L1432 . Changing viewer UI via URL is not what end-user will expect, and we don't want publishers to create content with such "features".

If you are using the viewer on your web site, please add the code to get/pass locale preference some other way than hash.

**Comment by jesteves** [comment]
Than final comment explains it.

I don't understand this part "[...] we don't want publishers to create content with such "features" [...]", but never mind.

We'll look for a workaround for our case (where actually a change in the UI is *exactly* what the user expects...)

Thanks.
