### ISSUE TITLE
Chrome does not render graphical circles, Firefox and IE do

### ISSUE THREAD

**Issue by Kurdakov** [mozilla/pdf.js#5732]
I have a sample page where the problem is visible

http://www.sim-ai.org/ErrorPage.pdf

( tested with either http://mozilla.github.io/pdf.js/web/viewer.html  or fresh git )

on top of this page there are small circles which are rendered in Firefox and IE but not in Chrome/Opera

**Comment by yurydelendik** [comment]
Looks good on Mac OSX. Can you add a screenshot?

It can be related to https://bugzilla.mozilla.org/show_bug.cgi?id=858128

**Comment by yurydelendik** [comment]
Sorry, misunderstood the problem. The PDF looks the same as in the Mac OS X Preview application:

![screen shot 2015-02-13 at 5 45 24 pm](https://cloud.githubusercontent.com/assets/1523410/6197262/33c63c32-b3a8-11e4-8513-d316216d01cc.png)

**Comment by Snuffleupagus** [comment]
Works for me, using: Windows 7 (64-bit), Firefox Nightly 38 (buildID: 20150213030456) with HWA on, and PDF.js 1.0.1143.

**Comment by yurydelendik** [comment]
Sorry, misunderstood again :) I see it in Chrome on Mac OS X:

![screen shot 2015-02-13 at 5 49 04 pm](https://cloud.githubusercontent.com/assets/1523410/6197289/a8939384-b3a8-11e4-9ccd-df46c133068c.png)

**Comment by yurydelendik** [comment]
Okay, minimal test case:

```
ctx.strokeStyle = 'rgb(111,113, 117)';

ctx.lineWidth = 3;
ctx.miterLimit = 4;
ctx.lineJoin = 'round';
ctx.lineCap = 'round';
ctx.setLineDash([0, 6.035]); // Chrome does not like 0, which draws circles.
ctx.lineDashOffset = 0;

ctx.moveTo(10, 10);
ctx.lineTo(90, 10);
ctx.stroke();
```

**Comment by yurydelendik** [comment]
Issues in Chrome opened on Oct 23, 2012 at https://code.google.com/p/chromium/issues/detail?id=157347

**Comment by halcanary3** [comment]
To work around this, try: `ctx.setLineDash([0.0003, 6.035]);`

https://gist.github.com/halcanary3/d684151c63114f1c90bb

**Comment by yurydelendik** [comment]
> To work around this, try: ctx.setLineDash([0.0003, 6.035]);

@halcanary3 I don't understand that. Do you recommend to change the PDF to have the operators that produce that commands for PDF.js?

**Comment by NekR** [comment]
> @halcanary3 I don't understand that. Do you recommend to change the PDF to have the operators that produce that commands for PDF.js?

I believe he meant this:
```javascript
var val = ...;

if (val === 0 && isChrome) {
  val = 0.0003;
}

ctx.setLineDash([val, 6.035]);
```

Or maybe without ```isChrome``` check.

**Comment by yurydelendik** [comment]
@NekR we are trying to keep code base free from workarounds of browsers' deficiencies. In most of the cases such workarounds affect the performance at start up (polyfill and monkey-patching) or at the runtime (like the solution above). That does not mean a custom solution shall not include those fixes.

Please notice that you recommended not a complete solution: the current transform might set higher or lower scaling, so 0.0003 value might not have effect or introduce a visual defect. 

After reading the canvas 2d spec I'm not convinced that's a right behavior on a Chrome side. Most of web developers that use canvas expect right behavior on all browsers, don't they?

**Comment by yurydelendik** [comment]
Closing as WFM. See also closed upsteam bug https://code.google.com/p/chromium/issues/detail?id=157347
