### ISSUE TITLE
Zoom setting increases when using the back button 

### ISSUE THREAD

**Issue by aleth** [mozilla/pdf.js#5735]
STR
Use '+' to zoom in
Click on an internal link in the PDF
Use the back button to return
Result: The zoom amount increases further.

**Comment by Snuffleupagus** [comment]
I cannot reproduce this, using http://mirrors.ctan.org/info/lshort/english/lshort.pdf.

@aleth Please provide *more* detailed steps to reproduce this, e.g. a link the PDF file where this is happening and which internal link you click on. See also [the first paragraph here](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md).

**Comment by aleth** [comment]
I apologize for the poor bug report, which was from memory.
Closing this issue and refiling with a more correct description.
