### ISSUE TITLE
Most letters are invisible.

### ISSUE THREAD

**Issue by azhang66** [mozilla/pdf.js#5737]
Link to the PDF: http://www.hamilton.edu/writing/sins/SDSPosters8.5x11-1.pdf
Location in the PDF: The entire text area
Screenshot:
![screenshot2](https://cloud.githubusercontent.com/assets/10838574/6215353/56415908-b5c5-11e4-852b-87a329540570.png)
OS: Linux (Kubuntu 14.10)
Browser: Firefox 35.0.1 (Mozilla Firefox for Ubuntu canonical - 1.0)
PDF.js Version: 1.0.907
JS Warnings: None

This is the same pdf rendered in chrome:
![screenshot3](https://cloud.githubusercontent.com/assets/10838574/6215405/ed9c2454-b5c5-11e4-92e0-86ef4c50f447.png)

**Comment by Snuffleupagus** [comment]
Works for me, using: Windows 7 (64-bit), Firefox Nightly 38 (buildID: 20150216030222) with HWA on, and PDF.js 1.0.1143.

@azhang66 Is this issue present in the *latest* version of PDF.js?
To check this, please download the file and open it with the demo viewer (click on the "Open File" button on the right-hand side of the toolbar): http://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by azhang66** [comment]
Yes, the issue is still present in the latest version of PDF.js
Here's what it looks like:
![screenshot4](https://cloud.githubusercontent.com/assets/10838574/6215957/d786009a-b5ca-11e4-9691-da3c67acc99f.png)

Interesting enough, i can select the text, but i cannot see it:
![screenshot5](https://cloud.githubusercontent.com/assets/10838574/6215974/06f0e7dc-b5cb-11e4-80bc-2cd25692bc2d.png)

I believe this is due to a rendering issue, maybe broken fonts or something? (I really don't know)

However, the preview sidebar shows the correct preview:
![screenshot6](https://cloud.githubusercontent.com/assets/10838574/6215996/45cbe560-b5cb-11e4-84c5-6417ea8cc343.png)

Thank you,
AZhang

**Comment by Rob--W** [comment]
FYI looks good to me in PDF.js in Chrome 40.0.2214.91 on Linux.

**Comment by timvandermeij** [comment]
Possibly related to #5392.

**Comment by azhang66** [comment]
@timvandermeij My drivers are current

**Comment by azhang66** [comment]
@timvandermeij The issue appears to have resolved itself. I'm guessing this was a Firefox bug that got fixed recently.
