### ISSUE TITLE
Synchronous loading of L10n data: Chrome warning

### ISSUE THREAD

**Issue by AllSeeingEye** [mozilla/pdf.js#5739]
l10n.js, line 227:

    // import another *.properties file
    function loadImport(url) {
       xhrLoadText(url, function(content) {
          parseRawLines(content, false); // don't allow recursive imports
     }, null, false); // load synchronously

in turn causes the warning (l10n.js, line 108):

    Synchronous XMLHttpRequest on the main thread is deprecated because
    of its detrimental effects to the end user's experience.

If I change false to true on line 231, l10n data just fails to load.

Probably a low-priority issue, but something to keep an eye on.
L10n code needs restructuring?

**Comment by yurydelendik** [comment]
Yeah, we need to look if l10n.js project changed the way it is loading the content and/or modify our stuff to load files using async XHR.

**Comment by Rob--W** [comment]
This part needs to be changed: https://github.com/mozilla/pdf.js/blob/e2c001c19d92c2c867ad6fc71627f99366bf9a3f/external/webL10n/l10n.js#L188-L266

I'll work on it once https://github.com/mozilla/pdf.js/pull/5692 has been merged (which touches code in the same area).

**Comment by Rob--W** [comment]
I've submitted a patch upstream: https://github.com/fabi1cazenave/webL10n/pull/52
