### ISSUE TITLE
I Have issue with showing content via url on the same domain on iPad

### ISSUE THREAD

**Issue by vitaly-ndaw** [mozilla/pdf.js#5740]
Hi . I Have issue with showing content via url on the same domain on iPad. So it seems the PDF is loaded and showed the correct number of pages but the pages are empty. But when I load the PDF from the same directory for example put file next to viewer.html  - all fine. I added CORS using web.config to the directory with the viewer.html like

<?xml version="1.0" encoding="utf-8"?>
< configuration>
  < system.webServer>
    < httpProtocol>
      < customHeaders>
        < add name="Access-Control-Allow-Origin" value="*" />
        < add name="Access-Control-Allow-Methods" value="GET" />
        < add name="Access-Control-Allow-Headers" value="range" />
        < add name="Access-Control-Expose-Headers" value="content-range, content-length, accept-ranges" />
      < /customHeaders>
    < /httpProtocol>
  < /system.webServer>
< /configuration>

but no effect

**Comment by timvandermeij** [comment]
It could also be that there is something wrong with the PDF file. Please post a sample PDF file here and state more information about your configuration (browser, OS, etc.).

**Comment by vitaly-ndaw** [comment]
iPad with retina display
iOS 8.1
Safari

PDF is ok, because it works in every desktop browser. And I can't show the url since there is needed authorization.

Do you have any idea what's wrong ?

**Comment by vitaly-ndaw** [comment]
CHecked with another PDF file of the same version and for some reason it showed the content but the file I mentioned - doesn't. So you are right something with the PDF file, but what it is - I don't know.

**Comment by timvandermeij** [comment]
Since we have no PDF file to verify the issue, I'm closing it as incomplete for now as there is no way for us to tell what is going wrong with the file.
