### ISSUE TITLE
Multiple warnings while loading in IE9 with disabled worker (Unhandled rejection: TypeError)

### ISSUE THREAD

**Issue by shershen08** [mozilla/pdf.js#5741]
I have rendering app, which works OK in all browsers (IE10 and IE11 too) except IE9.
 - PDFJS version - "1.0.233", build - "d39af0a"
 - compatibitity.js is included;
 - PDFJS.disableWorker = is set to true for IE9;
 - correct line is uncommented in PDFJS in loadFakeWorkerFiles function;

Further, depending on a file I try to load - get in console
```javascript
LOG: Warning: Setting up fake worker. 
LOG: Warning: Unhandled rejection: TypeError: Object doesn't support property or method 'catch' 
LOG: Warning: Unhandled rejection: TypeError: Object doesn't support property or method 'requestAnimationFrame' 
```
or
```javascript
LOG: Warning: Setting up fake worker. 
LOG: Warning: Unhandled rejection: TypeError: Object doesn't support property or method 'catch' 
LOG: Warning: Could not find a preferred cmap table. 
LOG: Warning: Unsupported feature "font" 
LOG: Warning: Error during font loading: Unable to get value of the property 'length': object is null or undefined 
```
Files are really basic, just A4 with 2 words, so problem is not in complex files, seems that smth is not loaded correctly.

**Comment by timvandermeij** [comment]
Interesting. We have some other issues open for IE9 specifically. Perhaps they are related to the type errors.

**Comment by shershen08** [comment]
Problem was solved by: 1) adding alternative polyfil for requestAnimationFrame method ; 2) polyfil for promises; 3) eliminating promise.catch( statements in code
