### ISSUE TITLE
Second page of pdf not shwoing

### ISSUE THREAD

**Issue by flik** [mozilla/pdf.js#5746]
I was checking helloword example and I replaced pdf file with multple pages pdf. 
It was showing first page of pdf file and not showing other pages of pdf file.

**Comment by Snuffleupagus** [comment]
As you can see [here](http://mozilla.github.io/pdf.js/examples/learning/helloworld.html), the "Hello world" example only shows *one* page. For a basic examples with a multi-page PDF file, see e.g. http://mozilla.github.io/pdf.js/examples/learning/prevnext.html. The code for both of these examples are placed in https://github.com/mozilla/pdf.js/tree/master/examples/learning.

There are also examples using the new, and still under development, viewer components. Please see the "Simple viewer" example in https://github.com/mozilla/pdf.js/tree/master/examples/components.

Closing as answered.
