### ISSUE TITLE
Error with PDF containing CCITTFaxStream Image

### ISSUE THREAD

**Issue by Harti79** [mozilla/pdf.js#5747]
I've a problem to view a PDF which contains a CCITTFaxStream image.

I get an error in pdf.worker.js in method ColorSpace.parseToIR at: 
switch(mode) {
..
  case 'CalGray':
          params = cs[1].getAll();  <-- undefined is no function
          return ['CalGrayCS', params];
}

Error message of pdf.worker.js:
Warning: Unable to decode image: TypeError: undefined is not a function
Warning: Dependent image isn't ready yet

pdf to test: https://drive.google.com/file/d/0BzOCthVk1FvqMmc4WUVjdkI0N1U/view?usp=sharing

**Comment by Snuffleupagus** [comment]
@Harti79 Did you create the PDF file yourself? If so, would if be OK for us to include it in our test suite?

**Comment by Harti79** [comment]
@Snuffleupagus i'ts no problem, you can add this PDF to your testsuite.
