### ISSUE TITLE
Unable to render PDF on drawing document (blank result)

### ISSUE THREAD

**Issue by azizikhoirulhaq** [mozilla/pdf.js#5755]
https://drive.google.com/file/d/0B3OU3WoaKy-XclZYblpjV08xVjQ/view?pli=1
Perfectly rendered on MacOS and Ubuntu Linux OS.
![normal_on_acrobat](https://cloud.githubusercontent.com/assets/8193125/6327181/9802e5e8-bb8b-11e4-8366-3deed05e775c.png)
 

but problem found on Windows.
![error_page](https://cloud.githubusercontent.com/assets/8193125/6327188/a52f907c-bb8b-11e4-93ac-de9ecba55cca.png)

Detail:
OS: Windows 7 32 bit
Processor: Pentium Dual Core T4300 2.10 GHz
Memory: 2GB
Browser: Mozilla Firefox 35.0.1

Please help me.. Thanks..

**Comment by yurydelendik** [comment]
Contains picture  7192x11154 -- windows graphics backend (dx?) has known to have problems with loading picture with size more than 8192.

**Comment by Snuffleupagus** [comment]
Interestingly this issue seem to be fixed upstream, since I can reproduce with Firefox 36, but *not* with Firefox&nbsp;37. (Tested with the latest version, `1.0.1149`, of PDF.js in both browsers.)

**Comment by azizikhoirulhaq** [comment]
Thanks for your help, Mr. yurydelendik, Snuffleupagus, timvandermeij..

**Comment by timvandermeij** [comment]
Works for me too now. Closing as fixed upstream.
