### ISSUE TITLE
Long delay and rendering problems in IE9/IE11 

### ISSUE THREAD

**Issue by holloway** [mozilla/pdf.js#5762]
The following one-page PDF...

  http://www.well.ucr.edu/docs/party_enforcement.pdf

...takes 40 seconds to display in IE11, and is rendered correctly. Desktop PDF viewers (E.g. Evince) take 2-3 seconds.

In IE9 it takes the same amount of time and then is rendered as this,

![screenshot from 2015-02-27 10 35 41](https://cloud.githubusercontent.com/assets/620580/6402454/9bcf6b5e-be6c-11e4-8f19-b6bc97aa1037.png)

Note that this reproducible in Microsoft's provided testing VMs from http://modern.ie/

This delay is present in PDF.js beta 1.0.1040 (stable), 1.0.907, as well as the [demo page](http://mozilla.github.io/pdf.js/web/viewer.html) running 1.0.1149.

**Comment by meteormatt** [comment]
I download this PDF and see blank page in IE.
While it is OK in Firefox.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
