### ISSUE TITLE
'Only print' watermark is shown ( incorrectly ) when viewed in browser 

### ISSUE THREAD

**Issue by Kurdakov** [mozilla/pdf.js#5764]
If to add a watermark to pdf file with Acrobat with 'Show when printing' (advanced option) enabled but 'Show when displaying on screen' option unchecked, then desktop pdf viewers view and print file correctly (show no watermarks, but print watermarks ), 

pdf.js will show watermark in both cases ( will not hide it when displaying on screen )

edit: example file http://www.sim-ai.org/errPage2.pdf

edit  I'm sorry to confuse bookmark with watermark - now text is correct ( but example is clear what the problem is - if to open file in desktop pdf viewer no across text is visible, but is incorrectly shown in pdf.js viewer )

**Comment by Kurdakov** [comment]
looks like it is related to https://bugzilla.mozilla.org/show_bug.cgi?id=845650 and https://github.com/mozilla/pdf.js/issues/269

**Comment by calixteman** [comment]
The link to the pdf in comment#0 is dead and bug 845650 has been closed so I close this one.
@Kurdakov, if you're still able to reproduce your bug and if you can attach the pdf to this issue, then feel free to re-open.
