### ISSUE TITLE
Add data attribute to DOM element-container to identify the page index

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#5766]
Per https://github.com/hypothesis/h/blob/document-pdfjs/docs/internals/pdfjs.rst#getting-the-root-dom-node-for-the-text-layer-of-a-page, add a 'data-' attribute to allow query selector operation and for identifying which page element-container belongs to. 'data-page-id' will work.

/cc @csillag

**Comment by csillag** [comment]
I can confirm that this would make integration between PDF.js and other projects (like Hypothes.is) easier.

**Comment by mbbaig** [comment]
So I made the change that is required in pdf_page_view.js to add the attributes. Take a look at the following commit: https://github.com/mbbaig/pdf.js/commit/f8c25ba257ff51f415388fd828cdd6941b764ad8

Here is a screen shot to illustrate the result:
![page-attribute-highlight](https://cloud.githubusercontent.com/assets/1588537/6818543/031e7820-d288-11e4-8e8f-1267b975ae86.png)

This was the intent right?

**Comment by yurydelendik** [comment]
yes, it is. To not confuse people, we probably need to change"data-page-id" to "data-page-index" for 0..n-1 numbers or to "data-page-number" for 1..n numbers. The latter seams to be more logical.

**Comment by mbbaig** [comment]
updated the code to reflect requirements. https://github.com/mbbaig/pdf.js/commit/7682d0cb80839a6c0a207d100f58adf0debb95e2

**Comment by timvandermeij** [comment]
Fixed in #5881.
