### ISSUE TITLE
Error: Invalid XRef stream header

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#5768]
http://www.clizio.com/S3/documenti/Miscellanea/OpenSSLcrypto.pod.pdf

Firefox 35.0.1, pdf.js 1.0.1165

**Comment by Snuffleupagus** [comment]
Nothing appears to be visibly broken, however Adobe Reader prompts you to re-save the file on exit, suggesting that it's corrupt. From the console:
```
"Error: Invalid XRef stream header" pdf.worker.js:250:4
"XRef_readXRef@resource://pdf.js/build/pdf.worker.js:3693:13
XRef_parse@resource://pdf.js/build/pdf.worker.js:3289:23
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:2484:7
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:2371:7
ensureHelper@resource://pdf.js/build/pdf.worker.js:2000:22
NetworkPdfManager_ensure/<@resource://pdf.js/build/pdf.worker.js:2014:7
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:1994:1
BasePdfManager_ensureDoc@resource://pdf.js/build/pdf.worker.js:1861:14
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:33208:11
" pdf.worker.js:252:0
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:4
"Warning: Unsupported feature "unknown"" pdf.js:235:4
"Warning: Indexing all PDF objects" pdf.worker.js:235:4
"PDF 7e19469dc763f25237641abc510ef31a [1.2 pod2pdf / -] (PDF.js: 1.0.1149 [WebGL])" viewer.js:6115:0

**Comment by naterkane** [comment]
Using pdf.js as part of an Angular app, nothing is loading, however console throws the same error. 

```

pdf.worker.js:250 Error: Invalid XRef stream header
pdf.worker.js:252     at error (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:252:15)
    at Object.XRef_readXRef [as readXRef] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:4235:13)
    at Object.XRef_parse [as parse] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:3831:28)
    at Object.PDFDocument_setup [as setup] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:3027:17)
    at Object.PDFDocument_parse [as parse] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:2914:12)
    at LocalPdfManager.ensure (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:2478:26)
    at LocalPdfManager_ensure [as ensure] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:2473:12)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:2405:19)
    at http://localhost:1235/lib/pdfjs-dist/build/pdf.worker.js:33746:22
pdf.worker.js:235 Warning: Unsupported feature "unknown"
pdf.worker.js:235 Warning: Indexing all PDF objects
```

I do not have the ability to re-generate or re-export the PDFs that I have to render as they are artifacts on a .gov website.

this is the file [60000972414.pdf | uploaded via ZenHub](https://files.zenhub.io/5504f669a564ab7a3147b4d1)

**Comment by CrewBoss** [comment]
I get the same error in the Safari debugger when I pass PDFJS.getDocument a PDF stream retrieved from our server. (I had to put the data into a uint8Array to even get it into the stream).

**Comment by quikchan** [comment]
Same here, and I'm using the example code.

**Comment by Rawwood** [comment]
I get this problem on PDFJS.getDocument on a PDF that i know is broken. But can i somehow catch this error and tell the user that the PDF is probably broken?

**Comment by borsch** [comment]
Hello.
I get this error whet pass UInt8Array. it's start from [37, 80, 68, 70, 45..] and it's equals to %PDF-
I don't know what is wrong. can somebody help me?

**Comment by Rob--W** [comment]
- http://www.clizio.com/S3/documenti/Miscellanea/OpenSSLcrypto.pod.pdf triggers "Invalid XRef stream header", because the specified xref offset (the number between "startxref" and "%%EOF" at the end of the PDF file) does not point to a xref table in the PDF (but the middle of some other stream). Because the xref table cannot be found, PDF.js falls back to indexing all objects to construct a xref table. In most cases, the PDF can be displayed just fine.

- https://files.zenhub.io/5504f669a564ab7a3147b4d1 opens without any errors.

Closing for now since I don't see any bug with PDF.js here. If you still think that there's a bug, please share a link to the PDF file + description of what happens and what you expected instead.
