### ISSUE TITLE
we should be able to "ANNOTATE" the rendered pdf and then save it

### ISSUE THREAD

**Issue by zaxebo1** [mozilla/pdf.js#5775]
we should be able to "ANNOTATE" the rendered pdf and then save/download it.
That is , fully support "annotation" adding/deleting/editing, esp the comments adding

**Comment by timvandermeij** [comment]
The README (https://github.com/mozilla/pdf.js/blob/master/README.md) file clearly states that PDF.js is only a PDF renderer. Editing PDFs is outside of the scope of this project. There are however forks of PDF.js that aim to provide such functionality.

Closing as won't-fix.
