### ISSUE TITLE
Additional resources > GNUpdf - Introduction to PDF is non english

### ISSUE THREAD

**Issue by totty90** [mozilla/pdf.js#5779]
You should add some english docs or at least warn that is non english.

**Comment by yurydelendik** [comment]
I guess you are talking about a comment from https://github.com/mozilla/pdf.js/blob/master/examples/helloworld/README.md:

"The file helloworld.pdf is from the GNUpdf project (see Introduction to PDF at GNUpdf), and contains a simple and human-readable PDF."

I don't think it says anything about documentation -- it's just a link to the place where the PDF was take from.

The issue does not specify steps to reproduce the problem. Closing as invalid for now. Please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md to provide more details to reopen the issue.
