### ISSUE TITLE
Where is the API located?

### ISSUE THREAD

**Issue by totty90** [mozilla/pdf.js#5780]
I've read multiple times your readme page and FAQ but no link to the API. Examples are a not enough to understand the API.

I would like to know the methods of `PDFJS`, `page.render` .. where can I find them?

I have this and I can't figure out how to render in a way to make text selectable:

      var renderContext = {
        canvasContext: context,
        viewport: viewport
      };
      page.render(renderContext);

**Comment by Snuffleupagus** [comment]
For API docs, please refer to the documentation at http://mozilla.github.io/pdf.js/api/draft/index.html and the comments in the actual file https://github.com/mozilla/pdf.js/blob/master/src/display/api.js (these links are also available from http://mozilla.github.io/pdf.js/api/).

Support for text selection isn't actually part of the API, but rather part of the viewer. See e.g. the examples using the new viewer components, available here: https://github.com/mozilla/pdf.js/tree/master/examples/components (these depend on [`PDFViewer`](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js)).

Closing as answered.

**Comment by totty90** [comment]
Thanks, I've looked into https://github.com/mozilla/pdf.js/blob/master/docs/contents/index.md and it didn't worked. Maybe add a link from the main readme to http://mozilla.github.io/pdf.js/api/draft/index.html ?
