### ISSUE TITLE
The converted HTML can able to store into a single variable 

### ISSUE THREAD

**Issue by sureshopensoft** [mozilla/pdf.js#5788]
Hi,
    Its very nice library .I have one issue that is the pdf to html conversion as to be done in very nice manner in your library .can i able to store the total html into a single variable that should be possible or not..possible means how to do that please share me...Thank you...

**Comment by timvandermeij** [comment]
It should be possible, but the pages are rendered by default only when they are coming into view. Since this is not an issue in PDF.js, but really a custom implementation question, I'm closing this as invalid. Please use the mailing list or IRC for such questions.

**Comment by sureshopensoft** [comment]
Ok thank you I will catch in mail .....

On Fri, Mar 6, 2015 at 12:53 AM, Tim van der Meij <notifications@github.com>
wrote:

> It should be possible, but the pages are rendered by default only when
> they are coming into view. Since this is not an issue in PDF.js, but really
> a custom implementation question, I'm closing this as invalid. Please use
> the mailing list or IRC for such questions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/pdf.js/issues/5788#issuecomment-77432466>.
>



-- 
Suresh.C
Software Engineer Trainee,
Open Soft

I'm Not Prefect But I want Become a Perfect......

**Comment by sureshopensoft** [comment]
Hello,
send your mail id....

On Fri, Mar 6, 2015 at 9:27 AM, Suresh C <sureshopensoft@gmail.com> wrote:

> Ok thank you I will catch in mail .....
>
> On Fri, Mar 6, 2015 at 12:53 AM, Tim van der Meij <
> notifications@github.com> wrote:
>
>> It should be possible, but the pages are rendered by default only when
>> they are coming into view. Since this is not an issue in PDF.js, but really
>> a custom implementation question, I'm closing this as invalid. Please use
>> the mailing list or IRC for such questions.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/pdf.js/issues/5788#issuecomment-77432466>.
>>
>
>
>
> --
> Suresh.C
> Software Engineer Trainee,
> Open Soft
>
> I'm Not Prefect But I want Become a Perfect......
>



-- 
Suresh.C
Software Engineer Trainee,
Open Soft

I'm Not Prefect But I want Become a Perfect......

**Comment by timvandermeij** [comment]
Please use the mailing list at dev-pdf-js@lists.mozilla.org or https://groups.google.com/group/mozilla.dev.pdf-js/topics.
