### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Kup3a** [mozilla/pdf.js#5789]
Hi!
I'm going use your product in my uni project, but i can't find the documentation about it! I need tutorial or smth like this. For example, how should i remember and store the last page of document, which was opened by user? I want store it in DB and open his document on right page at his next visit.
Help me, please!

**Comment by timvandermeij** [comment]
The wiki with all sorts of documentation can be found here: https://github.com/mozilla/pdf.js/wiki
The API is documented in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js

We are working on better API documentation, but that's not ready yet.

Closing as answered. Questions regarding custom implementations should be asked on the mailing list or IRC as this is purely a bug tracker.
