### ISSUE TITLE
Chinese type 1 font does not render: Warning: Unknown type 1 charstring command of "0"

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5790]
No characters on the page render. Reproducible on all browsers.
link to the PDF: https://www.dropbox.com/s/5vu5whodghu3tcm/7df6568c_Contents1.pdf?dl=0
location in the PDF: page 1
screenshot: none
browser version: Chrome 40.0.2214.111, Safari 8
operating system: Mac OSX 10.10.2, iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF 7db13e99f91a1692295d9c85c99248 [1.4 pdfFactory Pro 4.50 (Windows XP Professional x86 Chinese) / pdfFactory Pro www.fineprint.cn] (PDF.js: -)
util.js:204 Warning: Unknown type 1 charstring command of "0"

**Comment by timvandermeij** [comment]
For me some characters render, but I also get the warning in the console.

**Comment by timvandermeij** [comment]
This now renders the same as Adobe Acrobat for me, so I'm closing this as fixed.

**Comment by wojtekmaj** [comment]
A user provided me with another PDF that has this warning, not sure if that helps with anything, but just a heads up: https://github.com/wojtekmaj/react-pdf/issues/312#issuecomment-443563605
