### ISSUE TITLE
Chinese type 1 font does not render: Warning: Unsupported header type 1785750376 (jpch)

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5791]
link to the PDF: https://www.dropbox.com/s/fom2wylgjj3q0gx/4641a3fb_Title.pdf?dl=0
location in the PDF: first page
screenshot: none
browser version: Chrome 40.0.2214.111, Safari 8 
operating system: Mac OSX 10.10.2, iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF 342a53e926d7d11d9894bdab575343 [1.4 pdfFactory Pro 4.50 (Windows XP Professional x86 Chinese) / pdfFactory Pro www.fineprint.cn] (PDF.js: -)
util.js:204 Warning: Unknown type 1 charstring command of "0"
		(v 1.0.1175): Warning: Unknown type 1 charstring command of “0”, Warning: Unsupported header type 1785750376 (jpch)

**Comment by brendandahl** [comment]
It looks fine to me. Is there anything visually wrong with the PDF?

**Comment by timvandermeij** [comment]
This renders the same as Adobe Acrobat on Windows now, so I'm closing this as fixed. If there are defects remaining, please provide a screenshot that indicates these defects.
