### ISSUE TITLE
iOS 8. Renders blank page, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5792]
link to the PDF: https://www.dropbox.com/s/amdp638zcummd9n/343fd29b_5.pdf?dl=0
location in the PDF: first page
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
iOS 8: 
PDF f1644086626a8aed130c013f190a9282 [1.4 Adobe Acrobat Pro 11.0.2 Paper Capture Plug-in / A-PDF Deskew](PDF.js: -)
Chrome 40.0.2214.111 (although it renders ok):
PDF f1644086626a8aed130c013f190a9282 [1.4 Adobe Acrobat Pro 11.0.2 Paper Capture Plug-in / A-PDF Deskew](PDF.js: -)
viewer.html:1 Unhandled promise rejection Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: DOMException: Invalid font data in ArrayBuffer.}

**Comment by indystar-jamesearlywine** [comment]
Is anyone working to fix this?  I've got the same problem:

http://bookshelfb.indystardev.com/#/app/publication/view/228

I get these errors in Chrome console:

Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.fontLoaderBind @ pdf.js:6372transportObj @ pdf.js:2737messageHandlerComObjOnMessage @ pdf.js:1525
pdf.js:6372 Uncaught (in promise) DOMException: Invalid font data in ArrayBuffer.

These are the fonts in the document (embedded subsets):

FrutigerLTPro-Roman okay
AgilitaLTPro-MediumCond--Identity-H bad
AgilitaLTPro-Heavy--Identity-H bad
AgilitaLTPro-Regular--Identity-H bad
ZapfDingbatsStd okay
GlyphaLTStd-Black--Identity-H bad
AgilitaLTPro-BoldItalic--Identity-H bad
AgilitaLTPro-Light--Identity-H bad
AgilitaLTPro-Bold--Identity-H bad
AlbertinaMTStd-Regular--Identity-H okay
AgilitaLTPro-LightItalic--Identity-H bad
AgilitaLTPro-BoldCond--Identity-H bad
AgilitaLTPro-BoldCond okay
AgilitaLTPro-Medium--Identity-H bad
NotecLTPro--Identity-H bad
AgilitaLTPro-Condensed--Identity-H bad
GigiStd--Identity-H okay


The ones marked "bad" are the ones that throw the error.

**Comment by yurydelendik** [comment]
Closing as incomplete
