### ISSUE TITLE
iOS 8, Chinese vertical characters fail to render, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5793]
link to the PDF: https://www.dropbox.com/s/j2cibde0c4q2evp/8a94106f_A1.pdf?dl=0
location in the PDF: first page
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF 2d4bc6d8fad151a0c5e5283de5f14505 [1.4 Antenna House PDF Tool API V2.6 / Antenna House PDF Outliner　V2.0](PDF.js: -)

**Comment by yurydelendik** [comment]
Closing as incomplete
