### ISSUE TITLE
iOS 8, First page fails to render, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5795]
link to the PDF: https://www.dropbox.com/s/p8o6mdjgcafe32x/ContentServer.pdf?dl=0
location in the PDF: first page (2nd page renders fine)
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF 2af3038b5388a149ad34478e981aada7 [1.4 - / -](PDF.js: -)

**Comment by yurydelendik** [comment]
Closing as incomplete
