### ISSUE TITLE
iOS 8, Only last page renders, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5796]
link to the PDF: https://www.dropbox.com/s/i0wmcc944pr0x76/ContentServer%20%281%29.pdf?dl=0
location in the PDF: pages 1-4 (page 5 renders ok)
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
[Log] PDF fd8633b8c01e354e9151adaeee6469c9 [1.6 PDFsharp 0.9.653 (www.pdfsharp.com) / PDFsharp 0.9.653 (www.pdfsharp.com)](PDF.js: -) (viewer.js, line 1015)

**Comment by yurydelendik** [comment]
Closing as incomplete
