### ISSUE TITLE
iOS 8: Book cover image does not display, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5797]
link to the PDF: https://www.dropbox.com/s/l2ngmf9tq4cp3jo/63b18d95_Cover.pdf?dl=0
location in the PDF: page 1
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF c3618d13dd7224abca970ce6367065b8 [1.4 Acrobat Distiller 11.0 (Windows) / Adobe InDesign CS6 (Macintosh)](PDF.js: -)

**Comment by yurydelendik** [comment]
Closing as incomplete
