### ISSUE TITLE
iOS8: Background images don't render on book cover pages, no warnings

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5799]
link to the PDF: https://www.dropbox.com/s/x6yvg0a3bh985pl/ContentServer%20%284%29.pdf?dl=0
location in the PDF: pages 1 and 2
screenshot: none
browser version: Safari 8 
operating system: iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
PDF ae4e8dc08978f748a36a5a154c6772c0 [1.6 iTextSharp 4.1.6 by 1T3XT / -](PDF.js: -)

**Comment by yurydelendik** [comment]
Closing as incomplete
