### ISSUE TITLE
When printing files watermarked with itext, watermarks are duplicated when printing

### ISSUE THREAD

**Issue by dankirberger** [mozilla/pdf.js#5800]
We have a java app that watermarks pdfs on the server then feeds them to pdf.js

It views just fine, but when printing (or during print preview), the watermarks are duplicated. It views and prints fine in acrobat.

We are using the watermarking method outlined at the beginning of this answer:
http://stackoverflow.com/a/20361261/287609

Files found in this zip:
http://www.files.com/shared/54f8b53413692/Duplicated%20watermarks.zip
Source file, watermarked file, "print to pdf" from acrobat, "print to pdf" from Chrome with pdf.js

![comparison](https://cloud.githubusercontent.com/assets/1018378/6513341/e6ee245e-c33f-11e4-8ee0-09123f092384.png)

I'll work on getting a sharable version of our actual watermarking code, but I'm more curious if there is an underlying issue in the watermarked PDF that could help identify this, and if it is something more appropriately addressed in pdf.js directly (as it appears/prints fine in Acrobat).

**Comment by dankirberger** [comment]
Turns out this was due to me using the itext "PdfPatternPainter", which appears to cause the pattern to be reapplied multiple times on the page in certain situations. I have fixed it in my pdf generation code, but it might still be considered an issue in the print rendering of pdf.js?

**Comment by dankirberger** [comment]
This is a dupe of:
https://github.com/mozilla/pdf.js/issues/5505 it appears.

Though it does appear to be affecting us in IE and chrome at least. It is the same "pattern" based object layout issue.

**Comment by timvandermeij** [comment]
Perhaps #5828 will solve this then?

**Comment by timvandermeij** [comment]
Fixed by #5828.
