### ISSUE TITLE
Font decoding issues

### ISSUE THREAD

**Issue by pawelbialaszczyk** [mozilla/pdf.js#5801]
I'm experiencing some font-related issues. National (polish) characters are not being rendered correctly in the linked file.

Link to the PDF: http://www.planywb.po.opole.pl/index2.php?f=g9451.pdf
Location in the PDF: Whole file
Screenshot: ![Screenshot](http://i.imgur.com/8xm9olM.jpg)
Browser version: Firefox 36.0.1
Operating system: Windows 8.1 64-bit
PDF.js version: 1.0.1149
JavaScript console warning/error messages: none

**Comment by Snuffleupagus** [comment]
The majority of this issue has been addressed by PR #5809; the remaining issues with (some) incorrect characters are described in https://github.com/mozilla/pdf.js/pull/5809#issue-60202881.

**Comment by Snuffleupagus** [comment]
The following screen-shot is a comparison of the rendering in Adobe Reader and PDF.js, **on Windows**, of `issue5801.pdf` from our test-suite.
I'd be happy to try and address the few remaining incorrect characters, as outlined in https://github.com/mozilla/pdf.js/pull/5809#issue-60202881, but before doing that we've to establish that these issues aren't platform (or configuration) specific. 

![issue5801](https://cloud.githubusercontent.com/assets/2692120/8251920/09462b70-1681-11e5-8b7b-7159ff712764.png)
