### ISSUE TITLE
Printing multiple documents at once

### ISSUE THREAD

**Issue by mikewil** [mozilla/pdf.js#5807]
I need to place multiple PDFs on a page determined by an AJAX response, and when all documents and pages have rendered, call window.print.

The pages (canvases) of each document are being added to a div with class 'pdfdoc' to keep the pages in order by document.

I'm new to Promises, and I'm having trouble determining when to call window.print because of the async nature. Sometimes it is being called before all the pages are available even though I'm checking for the last page of the last document in the render promise before calling it. Here's the code:

``` javascript
// Called on each iteration of coredatalist
var getDoc = function(count) {
    PDFJS.getDocument(srcUrl).then(function(pdf) {
        var currentPage = 1;
        $('<div class="pdfdoc" id="doc' + count + '"></div>').appendTo('body');
        getPage(pdf, currentPage, count);
    });
};

// Called for each page in PDF
var getPage = function(pdf, currentPage, count) {
    pdf.getPage(currentPage).then(function(page) {
        var scale = 2,
            viewport = page.getViewport(scale),
            canvas = document.createElement('canvas'),
            context = canvas.getContext('2d'),
            renderContext = {
                canvasContext: context,
                viewport: viewport,
                intent: 'print'
            };

        // Prepare canvas using PDF page dimensions

        canvas.setAttribute('class', 'canvaspdf');
        canvas.id = 'canvas' + currentPage;
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        // Render PDF page into canvas context

        page.render(renderContext).then(function(page) {
            $('#doc' + count).append(canvas);
            if (currentPage < pdf.numPages) {
                currentPage++;
                getPage(pdf, currentPage, count);
            } else {
                if (parseInt(count) === coredatalist.length - 1) {
                    window.print();
                }
            }
        });
    });
};

// Iterate through JSON object from AJAX request
for (var j in coredatalist) {
    if (coredatalist.hasOwnProperty(j)) {
        srcUrl = coredatalist[j].props.downloaduri
        getDoc(j);
    }
}
```

Is what I'm describing possible?

**Comment by sime** [comment]
I'm interested in this. What does you markup look like to make this work?

**Comment by Snuffleupagus** [comment]
Given the sort of hoops that we have to jump through in order for printing to even work (somewhat acceptably) in e.g. the [demo viewer](https://github.com/mozilla/pdf.js#online-demo), please refer to https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js, this issue is probably not something that we can/will directly provide support for.
