### ISSUE TITLE
Require for link support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla/pdf.js#5812]
The sample of font features for Doulos SIL 5.000 have some links.
http://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=DoulosSIL-features5.000.pdf&filename=DoulosSIL-features5.000.pdf
I have tested this file in Sumatra PDF, these links can be open by click, but when I open file in Firefox, only select the link and right click can open these links.

Window 8.1 Chinese edition, auto-updates enabled
Firefox 36.0.1

**Comment by Snuffleupagus** [comment]
The PDF file doesn't actually contain any links, just text that *looks* like standard hyperlinks.

Those links can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).

The is tracked in #3172, hence I'm closing this issue.
