### ISSUE TITLE
Can I Use pdf.js to edit the pdf by uploading a pdf form on a website ?

### ISSUE THREAD

**Issue by ynagarjuna1995** [mozilla/pdf.js#5817]
I want the similar functionality like dochub.com where I can upload my PDF file which I want to edit and I can share with some one to edit the same pdf file

**Comment by timvandermeij** [comment]
PDF.js is only a PDF renderer and viewer, not an editor. Of couse it can be extended with editing capabilities, but that it out of scope for the PDF.js library. IIRC there are custom forks attempting to provide such functionality.

Closing as answered and out of scope.
