### ISSUE TITLE
Usage from node

### ISSUE THREAD

**Issue by blacksonic** [mozilla/pdf.js#5822]
I installed pdf.js to my node application, but it's version was only 0.1 but the current is 0.8 in the repository. Maybe it only needs an npm publish?
The problem that with version 0.1 the package.json requires cofeescript with the latest version, but the latest version doesnt auto register.
```
require('coffee-script');
module.exports = require('./lib/document');
```
Even after calling ```register``` here the code dies and complains for ```has no method 'getDocument'```

**Comment by Rob--W** [comment]
The `pdf.js` package on NPM has nothing to do with this project.
If you want to install PDF.js, use `npm install pdfjs-dist`, see #5777.

**Comment by blacksonic** [comment]
Am i right then it could not be used from Node.js just from the browser?

**Comment by yurydelendik** [comment]
It's not trivial to setup, but it's possible to use it from the node.js. See https://github.com/mozilla/pdf.js/tree/master/examples/node

We asked node.js community about API they want to see and what use cases they have in mind. No feedback was provided yet.

**Comment by LinusU** [comment]
@yurydelendik is there an open discussion about that? I can't seem to find it.

I would be very happy to provide feedback on how one would want to use Pdf.js from node.
