### ISSUE TITLE
Printing images on chrome are scaled by 50%

### ISSUE THREAD

**Issue by Hallelujahh** [mozilla/pdf.js#5827]
When printing a document containing images in chrome, the images get scaled down by 50%.

https://github.com/mumble-voip/mumble/blob/master/doc/mumble-protocol.pdf
(TeX src: https://github.com/mumble-voip/mumble/blob/master/doc/mumble-protocol.tex)

Print preview:
![pdf-scale](https://cloud.githubusercontent.com/assets/5173343/6599422/f8f2f7c8-c809-11e4-81d6-3ebf5a5f6d8a.png)

Expected (viewed in pdf.js):
![pdf-scale-expected](https://cloud.githubusercontent.com/assets/5173343/6599448/22330448-c80a-11e4-9974-7bde61cec0af.png)

**Comment by Rob--W** [comment]
Confirmed bug in Chromium 41.0.2272.77 on Linux. Looks fine in Firefox 36.0

**Comment by Rob--W** [comment]
Root cause found. It has something to do with an incomplete `mozCurrentTransform` polyfill. Investigating further...
