### ISSUE TITLE
Search: Hebrew character highlighting is completely wrong

### ISSUE THREAD

**Issue by xZero707** [mozilla/pdf.js#5833]
![hebrew-charsearch-issue](https://cloud.githubusercontent.com/assets/3281104/6614710/37362436-c89d-11e4-89d0-d5e1340aa337.png)
> Neither any of check boxes matter, result is always same

If we search for this Hebrew character: א for example in this line (pretend line):
aslkd klasjd ljsalkj asdlkj dsalkj laslaslkdja a a jsklfd א slkdjfslksdjflksfjs
So א is over towards the right.
The search engine will find it ... but the highlight will appear over to the left
aslkd klasjd ljs[here somewhere] dsalkj laslaslkdja a a jsklfd א slkdjfslksdjflksfjs

So distance from right margin becomes distance from left margin, so highlighted area is completely wrong, but it succeeds finding the search phrase.

UPDATE: Also, sometimes, search for those times out.

**Comment by xZero707** [comment]
Anything new regarding this issue?

**Comment by xZero707** [comment]
It's long time ago since I submitted this issue, and didn't get any update. Is it fixed?

**Comment by Snuffleupagus** [comment]
@xZero707 Could you please provide a link to a PDF fie that can be used to reproduce this issue, without that there's very little anyone can do to help.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.

**Comment by xZero707** [comment]
I must obtain permission for sharing above file as it belongs to another foundation.

**Comment by timvandermeij** [comment]
That's okay, we will reopen this when a test file is provided. Thank you.

**Comment by ItielMaN** [comment]
@timvandermeij Please take a look at [bug 1508345](https://bugzilla.mozilla.org/show_bug.cgi?id=1508345).
Link to an actual test case for this bug:
https://mushlam.clalit.co.il/SiteCollectionDocuments/platinum.pdf

Can this issue be re-opened?

**Comment by Snuffleupagus** [comment]
> Please take a look at [bug 1508345](https://bugzilla.mozilla.org/show_bug.cgi?id=1508345).

There's no reason to track the same issue in both GitHub and Bugzilla, hence this should just remain closed here and tracked in Bugzilla instead.
