### ISSUE TITLE
PdfJS rendering image picture COLOR wrongly

### ISSUE THREAD

**Issue by nguyenxuantuong** [mozilla/pdf.js#5836]
I just tested pdfJS using the code inside example folder (examples/learning/prevnext.html). Below is picture of the pdf (which is rendered to canvas) and the actual pdf image. As it can be seen, the color which originally  purple has turned become bright yellow colour. It also happen with some of other pdf pages (which turn light brown into red color). Is there any solution to avoid this?

Here is original pdf file which i used to test: https://danesrti8sy2q.cloudfront.net/public/issues/6492/pages/844aa31ba77b830038f5b556f2fdf48862023cfb/background.pdf

![screen shot 2015-03-13 at 3 16 09 pm](https://cloud.githubusercontent.com/assets/4355115/6634414/1788b99a-c993-11e4-829d-25c8252c42c2.png)
![screen shot 2015-03-13 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/4355115/6634415/178bfbdc-c993-11e4-9530-604febcc1eb4.png)

One more question, the file is stored in cloudfront, but the code will throw to error: Refused to get unsafe header "Accept-Ranges". I try to add some headers like Accept-Ranges, Content-Encoding, etc.. to the S3 bucket policy, but it doesn't help. Would appreciate if someone can help me figure out what need to be changed. A sample S3 bucket policy would be very helpful. Thanks.

**Comment by timvandermeij** [comment]
It seems all three issues are related. I have found that the problem is in line https://github.com/mozilla/pdf.js/blob/master/src/core/colorspace.js#L398. The values produced there do not comply with the DeviceRGB colorspace, whereas the spec says that they should. Not sure what it causing that though.
