### ISSUE TITLE
Not able to load the `pdf` file from server using the `localhost`

### ISSUE THREAD

**Issue by 3gwebtrain** [mozilla/pdf.js#5837]
Using `pdf.js` i a trying to load a `pdf` file from server. But i am getting bunch of errors. In case if i load the `pdf` file from nested folder it works well.

I don't any any idea to fix this issue. can any one help me to sort this please?

my code in `viewer.js` :

    'use strict';
    
    var DEFAULT_URL = ''http://localhost/PdfDemo/web/viewer.html?file=https://dl.dropboxusercontent.com/u/6257603/pdfs/pdf01.pdf'; //setting here..
    var DEFAULT_SCALE_DELTA = 1.1;
    var MIN_SCALE = 0.25;
    var MAX_SCALE = 10.0;
    var VIEW_HISTORY_MEMORY = 20;
    var SCALE_SELECT_CONTAINER_PADDING = 8;
    var SCALE_SELECT_PADDING = 22;
    var PAGE_NUMBER_LOADING_INDICATOR = 'visiblePageIsLoading';
    var DISABLE_AUTO_FETCH_LOADING_BAR_TIMEOUT = 5000;
    
    PDFJS.imageResourcesPath = './images/';
      PDFJS.workerSrc = '../build/pdf.worker.js';
      PDFJS.cMapUrl = '../web/cmaps/';
      PDFJS.cMapPacked = true;

My url path in location bar is : 

    http://localhost/PdfDemo/web/viewer.html#page=112&zoom=250,-2,842

is the default_url which i am setting is wrong?...

here is the error:

    l10n.js:127 GET http://localhost/PdfDemo/web/locale/locale.properties 404 (Not Found)
    l10n.js:127 XHR finished loading: GET "http://localhost/PdfDemo/web/locale/locale.properties".
    l10n.js:315 http://localhost/PdfDemo/web/locale/locale.properties not found.
    ?file=https://dl.dropboxusercontent.com/u/6257603/pdfs/pdf01.pdf:1 GET http://localhost/PdfDemo/web/?file=https://dl.dropboxusercontent.com/u/6257603/pdfs/pdf01.pdf 403 (Forbidden)
    XHR finished loading: GET "http://localhost/PdfDemo/web/?file=https://dl.dropboxusercontent.com/u/6257603/pdfs/pdf01.pdf".
    l10n.js:794 #loading_error is undefined.
    l10n.js:794 #unexpected_response_error is undefined.
    l10n.js:794 #error_version_info is undefined.
    l10n.js:794 #error_message is undefined.

Additionally, 
Whenever the user licks on `next` or `previous` button (customized in html not pdf viewer) i would like to load the appropriate `pdf` file. ( need to update the pdf file ) how can i do that?

Thanks in advace.

**Comment by yurydelendik** [comment]
Your browser protects you from cross-domain request (via CORS policies). You shall not request data from the remote domain by default. See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

Closing as answered

**Comment by 3gwebtrain** [comment]
I agree. can you show me a sample to load `pdf` file by dynamically. actually it is required to write by myself or is there some method?
In case of my self can i do like this ok?

    var i = 0;
    var DEFAULT_URL ="currentPdf"; 
    button.increase.on('click', function () {
    	i++;
    	DEFAULT_URL = "currentPdf"+i; //will it update?
    });

**Comment by yurydelendik** [comment]
just opening "http://localhost/PdfDemo/web/viewer.html?file=" and calling `PDFViewerApplication.open('/mypdf.pdf');` shall work

**Comment by 3gwebtrain** [comment]
sorry for the disturbance.  I am calling like this : but not working

    var DEFAULT_URL = 'http://localhost/PdfDemo/web/viewer.html?file='+ PDFViewerApplication.open('https://dl.dropboxusercontent.com/u/6257603/pdfs/pdf01.pdf');

**Comment by sreedaar** [comment]
I am using the below url in my application
**<iframe id="myFrame" src = "/js/pdfJS/web/viewer.html?file=#/base/docViewerAction?docid=12&parid=a" width='100%' height='800' allowfullscreen webkitallowfullscreen></iframe>**

**/base/docViewerAction?docid=12&parid=a** actually cooks a pdf file in a server context's temp directory and returns the actual path to the called method.

Either I dont get any error nor the pdf gets loaded. 

I am using pdfjs version 1.1.114.

Can anyone help?\

- Sridhar
