### ISSUE TITLE
Error rendering a page due to InvalideStateError of CanvasContext is not reported

### ISSUE THREAD

**Issue by TacB0sS** [mozilla/pdf.js#5839]
It would be difficult to setup a sample project, as I'm doing this on android and call the api from Java code.

The problem I'm seen is related to rendering while parsing other pages, these need to be pages with content and not some empty pages with a word in it.

So for example if I try to render 20 pages, then I iterate on the indices:

    renderPageCallBack = funciton (pdfPage){
    	logD("Page #" + pageIndex + " - Parsed");
    ...
    ...
    	pdfPage.render(renderContext).then(function pdfPageRenderSuccess() {    
    		logD("Page #" + pageIndex + " - Completed");
    	}, function pdfPageRenderError(error) {
    		logD("Page #" + pageIndex + " - Error: " + error);
    	});
    }
    
    doc.getPage(index).then(renderPageCallBack)

All the pages are logged as Parsed, most pages are rendered correctly, but only few (which most of the time are the first ones to be rendered) fail with the following log and no callback to 'pdfPageRenderError':

    "Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable.", source: content://com.nu.art.software.android.pdf.sdk/pdf.js/web/core/pdf.js (5023)

I'm not really sure why this is happening, but if I'll get the error I could consider rendering that page again, otherwise I'm stuck in limbo...

**I've also made another attempt**, to parse all the pages before calling any rendering, and everything seemed to be just fine!

**Comment by timvandermeij** [comment]
Which version of PDF.js are you using? Are you using our master branch or one of the stable/beta releases?

**Comment by TacB0sS** [comment]
master...

**Comment by timvandermeij** [comment]
Could you add some timeout inbetween the page requests just to see if that is the issue?

**Comment by TacB0sS** [comment]
If iterate manually... via clicking a button and calling the api everything is working fine.

**Comment by TacB0sS** [comment]
Also if I depends on the amount of pages I iterate on... for example, on some pdfs it doesn't matter if I iterate on 30 pages and on some even iterating on 3 causes this.

**Comment by timvandermeij** [comment]
Hm, the fact that the issue is intermittent makes it hard to find the cause. I'm marking this issue as triage-needed since we would need to look into this some more.

**Comment by TacB0sS** [comment]
What I can suggest to reproduce it is to parse page 1, call render on it and break the execution before rendering starts call parse on two or more other pages, destroy the canvas of page 1 manually (not really sure how to do that) and let the code run... 

I believe this would trigger the bug and not report to the error callback.

Thanks for your help.

**Comment by yurydelendik** [comment]
Is it still an issue?

**Comment by yurydelendik** [comment]
No response. Closing as incomplete.
