### ISSUE TITLE
uncaught exception: Page index 0 not found.

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#5840]
With Firefox 36(Windows 8.1) and Google Chrome 41
http://repository.readscheme.org/ftp/papers/sw2010/06-barland.pdf
does not load with the error:
uncaught exception: Page index 0 not found.
pdf.js's version is 1.0.1207.

Adobe Reader and Chrome PDF Viewer display it as expected.

**Comment by Snuffleupagus** [comment]
Closing as duplicate of issue #5644.
