### ISSUE TITLE
text extraction without rendering

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5846]
I would like to extract the text of PDFs on the server, i.e., without explicitly rendering the PDF. I'm wondering if pdf.js is fit to the task. So far I couldn't install pdf.js cleanly with node.js, nor was I able to extract the text without rendering the PDF.
Anyone with a little more insight here?

**Comment by Snuffleupagus** [comment]
I would suggest checking out these node examples: https://github.com/mozilla/pdf.js/tree/master/examples/node, especially `getinfo.js`  (note that it requires PDF.js to be built using `node make singlefile`).

The `getinfo.js` example uses the `getTextContent` method of the API, please see [api.js#L831-L839](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L831-L839).

**Comment by timvandermeij** [comment]
Now that the example has been fixed and instructions have been provided, I'm closing this as answered.
