### ISSUE TITLE
How to prevent the default pdf from loading.

### ISSUE THREAD

**Issue by 3gwebtrain** [mozilla/pdf.js#5850]
In my app, I don't require to load a file by default. when user click on the button, i like to generate the container, in which i would like to show the pdf.

What i required is, `how to disable` the defaut option, at present I using this approach
```javascript
var DEFAULT_URL = null;
````

is this correct? or is there any in-build approach?

**Comment by timvandermeij** [comment]
As far as I know, the default PDF.js library will always attempt to load a file. The best way is to only load PDF.js if you actually want to load a PDF file. Otherwise you would have to implement this yourself.

Closing as answered.

**Comment by yurydelendik** [comment]
You can also use empty "file" parameter: http://mozilla.github.io/pdf.js/web/viewer.html?file=
