### ISSUE TITLE
pdfjs-dist ships 1.1.1 as 1.1.3

### ISSUE THREAD

**Issue by andrenarchy** [mozilla/pdf.js#5852]
The [bower and npm packages](https://github.com/mozilla/pdfjs-dist) ship the current version 1.1.1 as 1.1.3. I think these are automatically generated, so maybe there's a bug in the build script?

**Comment by timvandermeij** [comment]
This is expected. The current add-on version is also at version 1.1.3. It happened because in #5851 the first commit introduced 1.1.1 and the next two commits increased the version to 1.1.3.
