### ISSUE TITLE
Link to gnupdf.org is broken/spammy

### ISSUE THREAD

**Issue by sg-s** [mozilla/pdf.js#5854]
The link at the bottom of [this page](https://github.com/mozilla/pdf.js/tree/master/examples/helloworld) is broken?

edit: this [link](http://www.gnupdf.org/?Introduction_to_PDF)

**Comment by timvandermeij** [comment]
Hm, it seems that GNUpdf disappeared recently. Thank you for reporting this. I will prepare a patch to clean it up.
