### ISSUE TITLE
How to remove `window re-size` event?

### ISSUE THREAD

**Issue by 3gwebtrain** [mozilla/pdf.js#5858]
In my app, i am using the stable width and height dimension to show the rendered pdf file. some time, when i open the `console` panel that triggers the windows resize event.

because of that, my form, which i show over the text layer, resets itself. even some of background this resets in the textlayer, what i set.

so, how can i disable the `window resize` event from `viever.js or pdf.js`

any one help me?

**Comment by Snuffleupagus** [comment]
The `resize` event is fired by the browser, see https://developer.mozilla.org/en-US/docs/Web/Events/resize, so it is not possible to prevent it from firing.
You can of course remove the event handling code from [viewer.js#L1817](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L1817) in your implementation, but please note that doing so would prevent certain functions of the viewer from working.

Closing as answered (and out of scope for the default viewer).

**Comment by 3gwebtrain** [comment]
Yes, it works. can you tell me a way to disable or remove the `toolbar` and `thumb` at the left as well... I am doing using `css`. it that correct?

**Comment by Snuffleupagus** [comment]
It sounds like your implementation doesn't actually need most of the features of the default viewer. Hence I would suggest that you look into using the viewer components instead, see https://github.com/mozilla/pdf.js/tree/master/examples/components.
In response to your second question, I suggest searching the code for the `pagerendered` and `textlayerrendered` events.

**Comment by 3gwebtrain** [comment]
Thanks for your great advice. What I exactly required is, I would like to show the pdf, in which user can `select the text` once that done, i would like to `hightlight` the selected area wrapping the text in `span` element say : `<span class="highlighted">Some selected text</span>, so i can filter the areas whatever the user selected and send to back-end. 

In case user require to delete the selected text, i will keep delete button, which can re-wrap the `span` element.
Can you tell me extactly which `components` require to use this please?
Onload let me show them `pdf1` on click on next and previous button let me update the pdfs. for to show the selected text again to user  i am `storing the textlayer` in javascript object to replace when the user come back from `pdf2` to `pdf1`. 

Thanks in advance. If i get any suitable answer for this questions, it mean you have saved me a week time..!
