### ISSUE TITLE
Larger PDF files are causing memory issues with ipad (again)

### ISSUE THREAD

**Issue by eikkaj** [mozilla/pdf.js#5862]
It seems that this was a previous issue but I am experiencing it again across browsers on ios8.

Chrome://crashes
Crash ID 351cf94098951d3a

iOS Logs:
CrashReporter Key:   465575774f69fc01a0e830a21ac4ebeb32389cf2
Hardware Model:      iPad2,1
Process:             Chrome [174]
Path:                /private/var/mobile/Containers/Bundle/Application/7B5C4EB0-9B65-4251-812C-D848891E1885/stable.app/Chrome
Identifier:          com.google.chrome.ios
Version:             41.0.2272.56 (41.2272.56)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2015-03-16 14:34:23.437 -0400
Launch Time:         2015-03-16 14:28:57.988 -0400
OS Version:          iOS 8.1.2 (12B440)
Report Version:      105

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0xb04b1b39
Triggered by Thread:  17

.
.
.

Thread 17 name:  WebThread
Thread 17 Crashed:
0   WebCore                       	0x2e66a87e 0x2e65c000 + 59518
1   WebCore                       	0x2e66a744 0x2e65c000 + 59204
2   WebCore                       	0x2e87fc50 0x2e65c000 + 2243664
3   WebCore                       	0x2e8c692a 0x2e65c000 + 2533674
4   WebCore                       	0x2e8c54a8 0x2e65c000 + 2528424
5   WebCore                       	0x2e879334 0x2e65c000 + 2216756
6   WebCore                       	0x2e71ebf8 0x2e65c000 + 797688
7   CFNetwork                     	0x22c74eec 0x22c51000 + 147180
8   CFNetwork                     	0x22d1176a 0x22c51000 + 788330
9   CFNetwork                     	0x22c65d6e 0x22c51000 + 85358
10  CoreFoundation                	0x2311859e 0x230ff000 + 103838
11  CFNetwork                     	0x22c65c26 0x22c51000 + 85030
12  CFNetwork                     	0x22c65aee 0x22c51000 + 84718
13  CFNetwork                     	0x22c65988 0x22c51000 + 84360
14  CoreFoundation                	0x231cdfd4 0x230ff000 + 847828
15  CoreFoundation                	0x231cd3e6 0x230ff000 + 844774
16  CoreFoundation                	0x231cba64 0x230ff000 + 838244
17  CoreFoundation                	0x23118b2c 0x230ff000 + 105260
18  CoreFoundation                	0x2311893e 0x230ff000 + 104766
19  WebCore                       	0x2e6dec7c 0x2e65c000 + 535676
20  libsystem_pthread.dylib       	0x3139be64 0x31399000 + 11876
21  libsystem_pthread.dylib       	0x3139bdd6 0x31399000 + 11734
22  libsystem_pthread.dylib       	0x31399b80 0x31399000 + 2944
.
.
.
Thread 17 crashed with ARM Thread State (32-bit):
    r0: 0xb04b1b39    r1: 0x00000003      r2: 0x00000002      r3: 0xfffffffe
    r4: 0x00000000    r5: 0x05258d54      r6: 0x084a1264      r7: 0x05258db4
    r8: 0x087dc300    r9: 0x05124828     r10: 0x00000000     r11: 0x00000000
    ip: 0x00000000    sp: 0x05258d0c      lr: 0x2e66a749      pc: 0x2e66a87e
  cpsr: 0xa4001c30

**Comment by eikkaj** [comment]
I'm not sure if this is actually caused by a file that is too large or a file with too many pages perhaps? The form(s) I am testing with also have form fields.  A smaller version of the pdf doesn't seem to cause any problems with > 100 tests across browsers. I have a larger form with double the number of pages (5 vs 11, so still not all that big) and it fails pretty consistently. I've troubleshooted by removing the form fields, cutting the pages, tripling them, and it watching the memory usage in ios. It seems that the memory is maxed out consistently.

**Comment by timvandermeij** [comment]
We will need a link to the problematic file so a developer can try to reproduce the issue. Could you post one?

**Comment by eikkaj** [comment]
https://www.dropbox.com/s/fegpzwrdl33pkxc/IHVSC_2014-10-03_a25.pdf?dl=0

**Comment by anaholzbach** [comment]
Hi, I am working with eikkaj on this project. Would you have an update on this issue? Were you able to load the file? Thanks for your help.

**Comment by eikkaj** [comment]
Could anyone provide any advice for tweaking the performance perhaps?

**Comment by timvandermeij** [comment]
I'm not sure what the cause of the problem is. It is not using more than 200-250 MB memory on desktop, which is lower than usual for PDFs (as is it mostly text instead of images). Someone would have to debug this on the device, but since I don't use iOS I wouldn't know where to look for the issue unfortunately.

**Comment by eikkaj** [comment]
Thanks for the info. I'll be moving away from pdf.js due to memory issues on iPads. I'll close the bug since it appears this isn't supported.
