### ISSUE TITLE
PDF.js is part of Firefox 14 and up, not 19 and up

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/pdf.js#5864]
From https://en.wikipedia.org/wiki/PDF.js: "A version of PDF.js (not the extension) is included in Mozilla Firefox since version 14,[2][3] and is enabled by default since version 19.[4][5]"

Most references I've seen refer that PDF.js was introduced in Firefox 14:
* http://www.ghacks.net/2012/03/23/firefox-14-gets-built-in-pdf-reader-pdf-js/
* http://www.itechmag.com/pdf-js-built-in-pdf-reader-for-firefox-14/
* http://browserfame.com/569/pdfjs-firefox14-pdf-reader
* http://newsblog.wti.com/index.php/2012/03/firefox-14-gets-built-in-pdf-reader-pdf-js/

Can you please change text in https://addons.mozilla.org/en-US/firefox/addon/pdfjs/

From: "Note: PDF.js is part of the Firefox since version 19."

To: "Note: PDF.js is part of the Firefox since version 14 (or 15?), and enabled since version 19."

Can you do that?

**Comment by davidhedlund** [comment]
Most references state PDF.js was introduced already in Firefox 14.

**Comment by Snuffleupagus** [comment]
As explained in https://github.com/mozilla/pdf.js/issues/5865#issuecomment-83960820, we're trying to deprecate the AMO addon.

Closing as invalid.
