### ISSUE TITLE
Arabic Characters not display properly in IE and un selectable with Firefox and Chrome

### ISSUE THREAD

**Issue by 3gwebtrain** [mozilla/pdf.js#5872]
My PDF has the arabic characters,  It is showing with Firefox and Chrome as like image. I am not able to select the text at all...

In case of  `ie 11`, the characters not at all visible it displaying nothing.

1) How to fix the `ie` arabic character issue...
2) How to make text are select-able?

Do i required to installed the `arabic` fonts with me or any other workaround need to do here?

 Here is the screen shot,
###### `ie 11` display :-1:

![arabicin-ie11](https://cloud.githubusercontent.com/assets/6211826/6773579/39d7edd8-d139-11e4-8975-4c165f8596f5.JPG)

---
###### Firefox / chrome display:-

![arabicin-chromeandfirefox](https://cloud.githubusercontent.com/assets/6211826/6773584/4aed2778-d139-11e4-9508-3826764224ad.JPG)

Please help me to sort this.

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read: https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.
At the very least, you must provide a link to a PDF file that can be used to reproduce this issue.

**Comment by 3gwebtrain** [comment]
I am sorry, here is the link for pdf file. https://dl.dropboxusercontent.com/u/6257603/aspire2.pdf

**Comment by Snuffleupagus** [comment]
The file renders identical to Adobe Reader for me, in both Firefox 39 and IE 11, using PDF.js `1.1.11`.

Please note that the Arabic "text" isn't actually text, but rather a series of images. This thus explain why text selection isn't possible *even* in Adobe Reader.

**Comment by 3gwebtrain** [comment]
I am using the version of "PDFJS.version = '1.0.1149';" , I am using `pdf.js` simpleviewer from the components. just a couple of day before I integrated using `node`. in case if I required to update my version of `pdf.js` can you give me the link of latest please?

**Comment by 3gwebtrain** [comment]
Yes, I agree all this Arabic text are series of images. since i am getting from server i am not realized this page. but still the images is not shows the correct result like other browser do. Is there a way to fix this? or avoiding series of images to "select-able" text may work out?

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
