### ISSUE TITLE
IE9 Font rendering issue (Out of memory)

### ISSUE THREAD

**Issue by dankirberger** [mozilla/pdf.js#5873]
Having issue loading the Chinese characters in the following document in IE9:
http://www.files.com/shared/55104cd334391/IE9%20Chinese%20Font%20Out%20of%20Memory.pdf

The chinese characters do not load, but everything else does.
![image](https://cloud.githubusercontent.com/assets/1018378/6786089/0da51b68-d158-11e4-86ad-9abbec38c176.png)

IE10, chrome, firefox all are fine. This is very specific to IE9. If this could be fixed short term via certain PDF processing I would be interested in hearing that as well, as that could help us (we are embedding pdf.js into our site but process the documents ourselves).

_IE9 Log:_
LOG: Warning: Setting up fake worker. 
LOG: PDF 8eb8d4511109ea94e7e0d16f0c150cff [1.5 Acrobat Distiller 6.0 (Windows) / Acrobat PDFMaker 6.0 Word 版](PDF.js: 1.0.1040) 
LOG: Warning: Unsupported feature "font" 
LOG: Warning: Error during font loading: Out of memory

**Comment by mathiaslin** [comment]
I have the same issues with a PDF of 70 pages, which renders fast within Chrome, but throws Out Of Memory errors in IE10.

**Comment by Thunderforge** [comment]
No issues for me with IE 11, so this is definitely with older versions.

**Comment by timvandermeij** [comment]
Closing since IE9 and IE10 are no longer supported since PDF.js 2.0.
