### ISSUE TITLE
Urdu Font (Jameel Noori Nastaleeq) not being rendered correctly

### ISSUE THREAD

**Issue by Bob45** [mozilla/pdf.js#5874]
Link to example PDF (other files which I tried don't work either): https://drive.google.com/file/d/0B9loCyDBc62ZM2hMeXphb3JVYTA/view?usp=sharing (google viewer renders it correctly)
Location in the PDF: Whole file
Screenshot: 
![pdf_bad](https://cloud.githubusercontent.com/assets/11624423/6795869/9e10f0da-d209-11e4-8714-597247abface.JPG)
Browser version: Firefox 36.0.4
Operating system: Ubuntu 14.04 LTS 64-bit, also tested on Windows 7, 32-bit
PDF.js version: 1.0.1040, 1.1.1 (see below for explanation)
JavaScript console warning/error messages: "Use of getPreventDefault() is deprecated.  Use defaultPrevented instead." (I don't think this actually relates, though)

I'm trying to render pdf files with Urdu text on my site, but pdf.js 1.0.1040 only renders weird letters. However, I did try it in 1.1.1 too, and it rendered decently:
![pdf_decent](https://cloud.githubusercontent.com/assets/11624423/6795891/1f9d6ade-d20a-11e4-9fb5-b241a79f67b9.png)
There are still some defects though, such as boxes around letters and (in some other documents) missing text. If this is a known issue which is being worked on I apologize, I just wanted to notify anyone of it.

**Comment by Snuffleupagus** [comment]
@Bob45 Did you create the PDF file yourself? If so, would if be OK for us to include it in our test suite?

**Comment by Bob45** [comment]
Sure, I don't mind if you include the PDF in you test suite.

**Comment by Snuffleupagus** [comment]
@Bob45 Thank you! I've submitted a patch that should address the issue; if you want to test it, please use the preview available in https://github.com/mozilla/pdf.js/pull/5990#issuecomment-100242449.

**Comment by Bob45** [comment]
Thanks for all the help! The PDF is now rendered correctly, so I'm closing this issue. However, in some other PDF files, there are small problems which I outlined here: https://github.com/mozilla/pdf.js/issues/5994 (Sorry for all the trouble).
