### ISSUE TITLE
devanagari getting extra intraword whitespace 

### ISSUE THREAD

**Issue by Shreeshrii** [mozilla/pdf.js#5876]
Please see http://sanskritdocuments.org/pdfjs/web/viewer.html?file=http://sanskritdocuments.org/doc_z_misc_shankara/aatmasha.pdf#zoom=auto&pagemode=thumbs

and compare to the pdf 
http://sanskritdocuments.org/doc_z_misc_shankara/aatmasha.pdf

the display in pdf.js viewer is adding whitespace breaking a word into multiple fragments

**Comment by Shreeshrii** [comment]
![image](https://cloud.githubusercontent.com/assets/5095331/6805416/d2898da4-d268-11e4-9313-1eeccd989ada.png)

This is in 
In Chrome 41.0 on Windows8

**Comment by Shreeshrii** [comment]
The problem seems to be font related, as http://sanskritdocuments.org/pdfjs/web/viewer.html?file=http://sanskritdocuments.org/doc_z_otherlang_hindi/stuti.pdf#zoom=auto&pagemode=thumbs displays correctly.

**Comment by brendandahl** [comment]
These look fine for me (osx preview on the left, pdf.js on the right) https://www.dropbox.com/s/oilch1hqz19agxd/Screenshot%202015-12-15%2011.27.27.png?dl=0

Is this still an issue?

**Comment by timvandermeij** [comment]
Yes, this looks fine for me on Windows too. Closing as fixed. If there are remaining problems, please open a new issue with the defects clearly outlined.
