### ISSUE TITLE
Error pops up when using pdfjs to retrieve a Chinese named file with IE explorer

### ISSUE THREAD

**Issue by rainerwang** [mozilla/pdf.js#5883]
I have met an error when trying to use pdfjs for retrieving a Chinese named file via IE explorer. 
The error info is "Message: Unexpected server response (403) while retrieving PDF". It's ok when I use chrome and ff explorer. My IE version is 9. 
Could someone please show me a light about this? Thank you.

**Comment by timvandermeij** [comment]
We will need more information to look into this, specially the PDF file. Could you post that?

**Comment by Snuffleupagus** [comment]
> It's ok when I use chrome and ff explorer. My IE version is 9.

This would suggest that it's not actually a PDF.js issue, but rather a browser issue.
You probably need to encode the URL, using e.g. `encodeURI`, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI.

Closing as answered.
