### ISSUE TITLE
Big base64 pdf

### ISSUE THREAD

**Issue by phillamarmotte** [mozilla/pdf.js#5885]
when i print a small pdf from base64 data i have no problem but when i try to do it with a big one (5 MO) i've got the error "InvalidPDFException: Invalid PDF structure". I can print this pdf from the pdf file only. Is there any max arraybuffer size ?

**Comment by yurydelendik** [comment]
> Is there any max arraybuffer size ?

There is no limit in the PDF.js. Looks like it's limitation of the browser rather than PDF.js. Closing as invalid.
