### ISSUE TITLE
Better error message for zero-sized file

### ISSUE THREAD

**Issue by tob2** [mozilla/pdf.js#5887]
EDIT: It turns out that the file is really broken: It is a size-zero file! I think there should be a better message if the file is zero or doesn't start with the "%PDF" marker. The current mesage implies that PDF.js has an issue - while the file has the issue.

That's with PDF.js as shipping with Firefox 36 under Linux.

The PDF file under http://www.bundesnetzagentur.de/cae/servlet/contentblob/38252/publicationFile/2591/Mitteilung902005VerzeichniId1323pdf.pdf doesn't render at all - only the dark background and is shown. The web console shows:

"Error: stream must have data" pdf.worker.js:250:4
"assert@resource://pdf.js/build/pdf.worker.js:267:5
init@resource://pdf.js/build/pdf.worker.js:2312:5
PDFDocument@resource://pdf.js/build/pdf.worker.js:2303:7
NetworkPdfManager@resource://pdf.js/build/pdf.worker.js:1975:24
getPdfManager@resource://pdf.js/build/pdf.worker.js:32962:24
wphSetupDoc@resource://pdf.js/build/pdf.worker.js:33157:7
messageHandlerComObjOnMessage@resource://pdf.js/build/pdf.worker.js:1219:9
" pdf.worker.js:252:0
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:4
"Warning: Unsupported feature "unknown"" pdf.js:235:4

PDF.js Version 1.0.937 (build: 308646d)

**Comment by mbbaig** [comment]
I would like to work on this bug. Can someone point me into the right direction? How would the devs like this implemented?

**Comment by timvandermeij** [comment]
Marking this as a feature since it does not concern a PDF file here and the message itself ("stream must have data") is correct, but might be made more explicit in that case. Not a high priority though.
