### ISSUE TITLE
wrong recognition for non-BMP Unicode characters

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#5890]
I’m afraid that pdf.js suffers from the bug described at sumatrapdfreader/sumatrapdf/issues/150.

http://www.unicode.org/charts/PDF/U20000.pdf#page=46 contains character U+20A3B 𠨻 which is recognized as character U+0A3B ਻.

As far as I know, glyph is displayed fine. It affects to search and copy.

**Comment by Snuffleupagus** [comment]
Duplicate of #10529.
