### ISSUE TITLE
Index Size Error while displaying pdf

### ISSUE THREAD

**Issue by kamrapooja** [mozilla/pdf.js#5891]
Hi,
We are facing index size error issue while displaying images in pdf.js.
The version of Pdf.js, we are using is : 1.0.712.
Please suggest for the resolution of same. It would be great help for us.

Regards,
Pooja Kamra

**Comment by Snuffleupagus** [comment]
When reporting as issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. Especially the *first* paragraph, which I'm also quoting:
> The issues are used to track both bugs filed by users and specific work items for developers. Try to file one issue per problem observed. Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: **link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages.** Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by timvandermeij** [comment]
Closing as incomplete for now. Please provide the information requested above to reopen.
