### ISSUE TITLE
Assign Annotations to users

### ISSUE THREAD

**Issue by KidLogic** [mozilla/pdf.js#5894]
Feature Request:
Enable users to create annotations and assign them to users via "@[email_address]".
This would be incredibly useful for design documents in creative and engineering disciplines.

I am a noob at programming but would love to help contribute to this feature... It will just take me a loonnnggg time.  Any help would be appreciated!

**Comment by timvandermeij** [comment]
PDF.js is only a PDF renderer and viewer, not an editor. While I can imagine that this feature is useful to you, most general users will not need this and therefore this should be implemented in a custom fork. Closing as out-of-scope for this project.
