### ISSUE TITLE
Heading is rendered with "=" sign in it

### ISSUE THREAD

**Issue by mrpandya007** [mozilla/pdf.js#5900]
![heading](https://cloud.githubusercontent.com/assets/11521993/6964645/d07356f6-d968-11e4-9008-d986343ba492.PNG)

I am getting this output when i have data in it, and without Data Heading was OK.
Its working fine with chrome and in adobe but not rendering well in pdf.js
Sorry I can't provide you the pdf as its confidential .

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read: https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md; especially the first paragraph which I'm also quoting below:
> The issues are used to track both bugs filed by users and specific work items for developers. Try to file one issue per problem observed. Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: **link to the PDF,** location in the PDF, screenshot, **browser version, operating system, PDF.js version and JavaScript console warning/error messages.** Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by Snuffleupagus** [comment]
Without access to a test-case, there is unfortunately nothing anyone will be able to do about this!
I would suggest that you try to create a reduced test-case, without any sensitive/private data, and make that available to us.

Closing as incomplete for now.
