### ISSUE TITLE
Hindi characters are not appearing correctly

### ISSUE THREAD

**Issue by varunwadhwa** [mozilla/pdf.js#5904]
Hi,
Hindi characters are not appearing correctly in the viewer. I am attaching the input pdf . I checked it at : https://mozilla.github.io/pdf.js/web/viewer.html and it does not render the characters correctly. I have generated the PDF using a command line tool named wkhtmltopdf. I can view the generated PDF in all major pdf readers and even online PDF readers but on pdf.js I see this error on chrome dev console - 
at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:244:17)
    at Object.Font_checkAndRepair [as checkAndRepair](https://mozilla.github.io/pdf.js/build/pdf.worker.js:18078:11)
    at Object.Font (https://mozilla.github.io/pdf.js/build/pdf.worker.js:16682:21)
    at Object.PartialEvaluator_translateFont [as translateFont](https://mozilla.github.io/pdf.js/build/pdf.worker.js:12258:14)
    at Object.PartialEvaluator_loadFont [as loadFont](https://mozilla.github.io/pdf.js/build/pdf.worker.js:11055:16)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont](https://mozilla.github.io/pdf.js/build/pdf.worker.js:10827:19)
    at next (https://mozilla.github.io/pdf.js/build/pdf.worker.js:11216:27)
    at https://mozilla.github.io/pdf.js/build/pdf.worker.js:11369:19

Thanks for pdf.js . It is an amazing viewer but I am really stuck on this. I searched for the solutions but I found the corresponding issues as either closed or not supported. Can anything be done for this ?
Thanks again for the viewer.

[input.pdf | uploaded via ZenHub](https://files.zenhub.io/551e73a925485a902b1a0c22)

**Comment by Snuffleupagus** [comment]
Despite the console messages about the font issues, PDF.js actually seem to render all characters the same way as Adobe Reader for me (disclaimer: I don't speek Hindi):
![comparison](https://cloud.githubusercontent.com/assets/2692120/6981877/9bf29288-da09-11e4-8dda-db596e5967fd.png)

My configuration: Windows 7 (64-bit), Firefox Nightly 40 (buildID: 20150402115824) with HWA on, and PDF.js 1.1.36.

@varunwadhwa As outlined in the *first* paragraph here: https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, please provide more information about your configuration:
> The issues are used to track both bugs filed by users and specific work items for developers. Try to file one issue per problem observed. Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: link to the PDF, **location in the PDF, screenshot, browser version, operating system, PDF.js version** and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.

___
Complete console log:
```
"PDF 16994a3a836fce4deb7fb55acc21d962 [1.4 Qt 4.8.6 / wkhtmltopdf 0.12.2.1] (PDF.js: 1.1.36 [WebGL])" viewer.js:6216:1
downloadable font: OS/2: adjusting Mac style (regular) (font-family: "g_font_1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <unknown>
"Error: Required "glyf" or "loca" tables are not found" pdf.worker.js:243:5
"Font_checkAndRepair@resource://pdf.js/build/pdf.worker.js:17787:11
Font@resource://pdf.js/build/pdf.worker.js:16391:16
PartialEvaluator_translateFont@resource://pdf.js/build/pdf.worker.js:11967:14
PartialEvaluator_loadFont@resource://pdf.js/build/pdf.worker.js:10764:1
PartialEvaluator_handleSetFont@resource://pdf.js/build/pdf.worker.js:10536:14
next@resource://pdf.js/build/pdf.worker.js:10925:22
next/<@resource://pdf.js/build/pdf.worker.js:11078:19
Promise*PartialEvaluator_setGState@resource://pdf.js/build/pdf.worker.js:10666:1
next@resource://pdf.js/build/pdf.worker.js:11076:22
next/<@resource://pdf.js/build/pdf.worker.js:10930:19
Promise*PartialEvaluator_handleSetFont@resource://pdf.js/build/pdf.worker.js:10536:1
next@resource://pdf.js/build/pdf.worker.js:10925:22
next/<@resource://pdf.js/build/pdf.worker.js:11078:19
Promise*PartialEvaluator_setGState@resource://pdf.js/build/pdf.worker.js:10666:1
next@resource://pdf.js/build/pdf.worker.js:11076:22
next/<@resource://pdf.js/build/pdf.worker.js:11078:19
Promise*PartialEvaluator_setGState@resource://pdf.js/build/pdf.worker.js:10666:1
next@resource://pdf.js/build/pdf.worker.js:11076:22
next/<@resource://pdf.js/build/pdf.worker.js:11078:19
Promise*PartialEvaluator_setGState@resource://pdf.js/build/pdf.worker.js:10666:1
next@resource://pdf.js/build/pdf.worker.js:11076:22
next/<@resource://pdf.js/build/pdf.worker.js:11078:19
Promise*PartialEvaluator_setGState@resource://pdf.js/build/pdf.worker.js:10666:1
next@resource://pdf.js/build/pdf.worker.js:11076:22
PartialEvaluator_getOperatorList@resource://pdf.js/build/pdf.worker.js:10862:1
Page_getOperatorList/pageListPromise<@resource://pdf.js/build/pdf.worker.js:2461:16
Promise*Page_getOperatorList@resource://pdf.js/build/pdf.worker.js:2451:26
wphSetupRenderPage/<@resource://pdf.js/build/pdf.worker.js:33787:9
Promise*Catalog_getPage@resource://pdf.js/build/pdf.worker.js:3363:1
PDFDocument_getPage@resource://pdf.js/build/pdf.worker.js:2794:14
BasePdfManager_pagePage@resource://pdf.js/build/pdf.worker.js:2119:14
wphSetupGetPage@resource://pdf.js/build/pdf.worker.js:33699:14
messageHandlerComObjOnMessage/<@resource://pdf.js/build/pdf.worker.js:1456:18
Promise*messageHandlerComObjOnMessage@resource://pdf.js/build/pdf.worker.js:1455:9
" pdf.worker.js:244:1
"Warning: Unsupported feature "unknown"" pdf.worker.js:235:5
"Warning: Unsupported feature "unknown"" pdf.js:235:5
"Warning: Unsupported feature "font"" pdf.worker.js:235:5
"Warning: Unsupported feature "font"" pdf.js:235:5
"Warning: Error during font loading: Required "glyf" or "loca" tables are not found" pdf.js:235:5
```

**Comment by varunwadhwa** [comment]
@Snuffleupagus : Thanks for the immediate response and sorry for not providing complete
![pdf-js](https://cloud.githubusercontent.com/assets/7371719/6982436/601fe442-da2f-11e4-94dc-c8d6b69431f4.png)
![pdf-js](https://cloud.githubusercontent.com/assets/7371719/6982443/79fcf56c-da2f-11e4-8754-fba728439330.png)

 details. As you mentioned , I checked it on two machines : ubuntu and windows and following are the details:-

Windows 7
chrome version :-  41 : not working
mozilla version :- 35 : working. 

Ubuntu 14.04 
chrome version :- 41 : not working
mozilla version :- 37 : working.

I am attaching a screenshot which shows the working and non working output on both the machines. The application that I am building is mainly used on chrome so it would be really helpful if I can get a way around on chrome for this. Sorry again to not mention these details before.
Thanks.
![pdf-js](https://cloud.githubusercontent.com/assets/7371719/6982448/9295dce2-da2f-11e4-8f54-cf220bd51b3a.png)

**Comment by varunwadhwa** [comment]
Hi,
any plans for solving this. It is kind of a blocker issue for me and it would be of great help if this can be fixed. Even if I can get a lead as to how to solve this , I can try to do it myself.

**Comment by Snuffleupagus** [comment]
This issue is really old, and it seems to be relevant for a *specific* browser (and/or version thereof); is it still meaningful to keep this open?
