### ISSUE TITLE
Handle some cases where two PDFs were concatenated together.

### ISSUE THREAD

**Issue by jordan-thoms** [mozilla/pdf.js#5909]
Hi!

We've had a report with a PDF file which PDF.js could not open, but other PDF readers (e.g. Preview, Adobe Reader), could open without issues.

In investigating this, it turns out the PDF file is actually two different PDFs which were concatenated one after the other into a single file. Obviously not a valid PDF, but given that other PDF readers will show one of the PDFs in this case, we probably should too (*sigh*).

There was some previous discussion of this on issue #5255.

I've found the issue preventing us from showing one of the PDFs - it's because in the XRef indexObjects method in obj.js, we don't stop reading when we hit a %%EOF marker, and we will happily overwrite things in the entries array. 

Stopping at %%EOF has the side effect of breaking reading linearized PDFs that have a broken startxref value (because they contain one at the beginning too), so as an alternative fix I have implemented a check where we don't write into the entries array if a value is already present. I'll be pushing up a PR with that shortly.

I've uploaded the file here: https://www.dropbox.com/s/pvcuea8fmg1nc3c/21063565.pdf?dl=0

Thanks
Jordan

**Comment by timvandermeij** [comment]
Fixed by #5910.
