### ISSUE TITLE
Masked content renders visible

### ISSUE THREAD

**Issue by jsundn** [mozilla/pdf.js#5919]
Hi!

Part of a text layer that should be hidden renders visible with pdf.js, as you can see here:
https://s3-eu-west-1.amazonaws.com/epaper-dev/pdfjs/dn_dagens-nyheter_page_2015-04-07_b.pdf.

It should look like this:
http://postimg.org/image/5b506gh15.

Tested in browser versions:
Safari: 8.0.4 (10600.4.10.7)
Firefox: 36.0.4
Chrome: 41.0.2272.118 (64-bit)

Operatingsystem:
OSX Yosemite 10.10.2 (14C109)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6723.
