### ISSUE TITLE
Warning with large PDF

### ISSUE THREAD

**Issue by bostonou** [mozilla/pdf.js#5924]
When trying to display a large but simple pdf, we get the following warnings:

Windows 7, Chrome:

```
Warning: Unable to decode image: RangeError: Invalid array buffer length
Warning: Dependent image isn't ready yet
```

Windows 7, Firefox:

```
Warning: Unable to decode image: out of memory
Warning: Dependent image isn't ready yet
```

[Sample PDF](https://www.dropbox.com/s/dvh59tud2k71jcg/test-rectangle.pdf?dl=0)

**Comment by timvandermeij** [comment]
Renders perfectly fine for me and even faster than Adobe Acrobat. Perhaps you are using an older version of PDF.js. To verify, please open the PDF file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem is then resolved.

**Comment by bostonou** [comment]
@timvandermeij It works fine on my mac. However, I saw those errors on my Windows 7 VM using the viewer you linked to.

**Comment by timvandermeij** [comment]
Memory usage peaks at 980 MB, which is indeed (too) high. I think you only see it in the VM since that is likely to have less memory allocated. Labeling as a performance issue now.

**Comment by bostonou** [comment]
@timvandermeij I thought that might be the problem so I gave the VM 4GB of memory. Not enough I guess.

Is it possible that this issue could cause Chrome to crash? A more complicated PDF with the same dimensions is causing Chrome to crash on a PC. Unfortunately I can't share that specific PDF.

**Comment by timvandermeij** [comment]
Hm, 4 GB of memory should be more than enough. The image appears to be pretty large (12000 x 9000 if I remember correctly looking at the internal structure of the PDF) and perhaps we could we handling it more efficiently. I'm currently trying to find out what causes the high memory usage. It is possible that the browser crashes if it cannot allocate enough memory.

**Comment by bostonou** [comment]
With a more complicated PDF, I'm hitting [a known memory issue with Chrome on Windows 7](https://code.google.com/p/chromium/issues/detail?id=352204). Chrome on Windows 7 crashes if it can't allocate memory. In this case, the 12000x9000 canvas is the culprit.

Firefox and IE handle it with no issue, so it'd be nice if Chrome at least failed gracefully.

I'm still not clear on why Chrome crashes with the complicated PDF and with the simpler PDF (but same dimensions) it gives the warning mentioned above.

**Comment by Snuffleupagus** [comment]
WFM, without warnings and/or huge memory usage, when testing with PDF.js version `2.9.142` in Firefox Nightly 90.
Given the age of this issue, I wonder if it still makes sense to keep this open!?
