### ISSUE TITLE
Stabilize Viewer API

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#5925]
This is a meta issue to track feedback and things we want to change for PDF.js viewer API. Hopefully in Q2 2015 this will be stabilized and we'll start following the semantic versioning for it.

**Comment by meltuhamy** [comment]
Hi, any updates with this? It would be great to have a stable API for the viewer application for integrations

**Comment by timvandermeij** [comment]
@brendandahl Are there are any concrete developments required to close this issue? If so, what are they?

**Comment by timvandermeij** [comment]
Closing since we now have the viewer components and there is nothing more actionable in this issue.
