### ISSUE TITLE
Viewer doesn't remember last rotation angle

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#5927]
The viewer does remember last scroll position but not rotation angle. After reload the viewer will restore the last scroll position but because the rotation angle is not restored, the page position may be wrong.

**Comment by mbbaig** [comment]
I'd like to get started working on this. Any suggestions on the devs want to go about doing this?

**Comment by timvandermeij** [comment]
I would think that we can do this the same way as we store the last scroll position. I think the relevant part is located here: https://github.com/mozilla/pdf.js/blob/e4e9a2adea1b19f962dcebaca7c8144104549173/web/viewer.js#L897

**Comment by TZanke** [comment]
In relation to #8743 , will this be merged in master / new version anytime?

**Comment by soubhikchatterjee** [comment]
The rotation works fine in the web view, but the original file remains unchanged in the disk. Is there anyway we can save the changes to the original file on the disk?
