### ISSUE TITLE
Text rendered wrongly in Chrome

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#5928]
File: https://drive.google.com/file/d/0B6YhVF9p-y2AWU5XeVZlYzhyVU0/view?usp=sharing

Google Chrome	41.0.2272.118 (Official Build) 
![screen shot 2015-04-10 at 4 56 46 pm](https://cloud.githubusercontent.com/assets/1201310/7082140/a1cc8dd2-dfa2-11e4-9c51-d7ac5150ea0d.png)

Safari Version 8.0.4 (10600.4.10.7)
![screen shot 2015-04-10 at 4 56 54 pm](https://cloud.githubusercontent.com/assets/1201310/7082141/a32f79fa-dfa2-11e4-827d-124d978cdf0e.png)

Using the demo viewer

**Comment by Snuffleupagus** [comment]
I cannot reproduce this, using: Windows 7 (64-bit), Firefox Nightly 40 (buildID: Mozilla/5.0 (20150409030206) with HWA on, and PDF.js 1.1.52.

@xlc Please provide information about your Operating System.

**Comment by xlc** [comment]
Just tried with Windows 8.1 chrome which works. 

Still doesn't work on OSX 10.10.3 (14D87h) Chrome 41.0.2272.118

**Comment by Hengjie** [comment]
I'm on Chrome v43 on OS X 10.10.3 and can reproduce this issue.

**Comment by timvandermeij** [comment]
@xlc @Hengjie Are you still able to reproduce this using the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html? A largely Mac-specific font patch landed a day ago, which might fix this.

**Comment by Hengjie** [comment]
The problem still exists on 10.10.4, see screenshot below on the latest viewer:

<img width="1402" alt="a" src="https://cloud.githubusercontent.com/assets/261870/8553371/d88718b2-2497-11e5-9cd0-bd53a9c89201.png">

**Comment by timvandermeij** [comment]
@Hengjie Thank you for confirming this (as I do not have access to Mac myself)! We'll leave this open for further triage.

**Comment by timvandermeij** [comment]
Is this still an issue with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html and up-to-date OSX and Chrome? Many font-related patches landed since the last comment.

**Comment by xlc** [comment]
Works for me on Chrome 50 and latest pdf.js
