### ISSUE TITLE
Prevent Priting

### ISSUE THREAD

**Issue by mausclaffani** [mozilla/pdf.js#5930]
I would like to know that is possible disable the printing function.
I downloaded the demo, and would like to prevent the shortcut "Ctrl + P" of browser.

Is it Possible ?!?
Anyone help me?

Regards

**Comment by timvandermeij** [comment]
Sure, just remove the print button at https://github.com/mozilla/pdf.js/blob/master/web/viewer.html#L158 and the code that handles printing: https://github.com/mozilla/pdf.js/blob/master/web/secondary_toolbar.js#L84

Closing as answered.

**Comment by mausclaffani** [comment]
Tim,
I already removed the print button, but i need prevent the "Ctrl + P".
I would like something that not allow the "Ctrl + P".
Regards

**Comment by timvandermeij** [comment]
You cannot prevent the user from printing the document completely. See also http://stackoverflow.com/questions/18843936/how-to-disable-the-ctrlp-using-javascript-or-jquery, but that is out of scope for this project.

**Comment by annayarotska** [comment]
This was the fix for me: returning false for this property in app.js

`get supportsPrinting() {
    return false
  }`
