### ISSUE TITLE
FAQ: Supported IE Versions

### ISSUE THREAD

**Issue by ax3l** [mozilla/pdf.js#5931]
Hi,

is there any news about support/functionality in more recent versions of IE/Spartan and Safari?
The [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported) entry is still pointing out IE8 (no) and IE9 (limited) only.

**Comment by Rob--W** [comment]
To see whether the required features are supported, just open http://mozilla.github.io/pdf.js/features/.

**Comment by ax3l** [comment]
thank you for the list!
now we just have to find a list honestly stating what is implemented and working on non-mozilla browsers ^^

**Comment by Rob--W** [comment]
@ax3l You can generate the list yourself by opening that page I linked in e.g. IE11. The page detects and shows whether the required features are present (and if not, if they could be emulated).

**Comment by ax3l** [comment]
oh, I did not realize that! I was just happily staring at my all-green FF results and thought it's an static/automated list from a CI :)

thank you!

**Comment by ax3l** [comment]
Seems like IE11 and Spartan support all but `Canvas supports extended blend mode` (thx @BenjaminW3)
