### ISSUE TITLE
Checkboxes not rendering correctly

### ISSUE THREAD

**Issue by wamatt** [mozilla/pdf.js#5932]
The following PDF renders checkbox as solid black boxes, in latest version of pdf.js

http://www.chinaconsulatesf.org/chn/qianzhen/zgqz/P020130828366275572026.pdf

![image](https://cloud.githubusercontent.com/assets/1271434/7106925/3e70eb5a-e107-11e4-8caf-15a36574153a.png)

By comparison

Chrome
![image](https://cloud.githubusercontent.com/assets/1271434/7106928/5acab218-e107-11e4-9142-ffedd6a3b3df.png)

Apple Preview
![image](https://cloud.githubusercontent.com/assets/1271434/7106931/68eff650-e107-11e4-8171-980ea3ceadde.png)

Adobe Acrobat
![image](https://cloud.githubusercontent.com/assets/1271434/7106936/80e4fdaa-e107-11e4-8445-a627a41c25dc.png)

**Comment by Snuffleupagus** [comment]
Possible related to issue #5696.

**Comment by Snuffleupagus** [comment]
Given the age of this issue and the fact that it's specific to a *particular* platform/browser, it's probably not meaningful to keep this open since it's unfortunately very unlikely to be fixable *here*.
