### ISSUE TITLE
Potential problem when encountering encrypted file streams

### ISSUE THREAD

**Issue by gettalong** [mozilla/pdf.js#5935]
The fallback at https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js#L1970 should not be `this.strf` but `this.stmf` according to the PDF1.7 spec section 7.6.1 page 57 (EFF key description).

**Comment by timvandermeij** [comment]
Thank you for reporting this. Could you make a pull request to address this?

**Comment by gettalong** [comment]
See pull request #5937 .
