### ISSUE TITLE
pdf.js and pdfworker.js are not working after build my whole project (all the js concatenated in one file)  

### ISSUE THREAD

**Issue by aboelnaga** [mozilla/pdf.js#5938]
i removed the pdf.js and pdfworker.js from concatenation and added them separately and it worked. how can i make them work while concatenated ?

**Comment by timvandermeij** [comment]
Did you use `node make singlefile`?

**Comment by aboelnaga** [comment]
yes i use node i use angular cg-generator and its grunt file for building

**Comment by timvandermeij** [comment]
It seems like there may be a problem with that particular generator then. Can you also reproduce it with the regular Makefile commands from this repository (as we do not use Grunt)?

**Comment by timvandermeij** [comment]
This appears to work just fine for me using the regular Makefile. It is recommended to use that with `node make generic`. There is also `node make singlefile` to produce one file is that is really needed. Angular CG generator and its Grunt Makefile are out of scope for this project: if there are any problems with that, please report them at their repository.

Closing as invalid. If there is really an issue in PDF.js (i.e., with our Makefile), then please provide more details to reopen.
