### ISSUE TITLE
Some text renders with incorrect colours

### ISSUE THREAD

**Issue by Elusive138** [mozilla/pdf.js#5939]
This file: https://www.usenix.org/system/files/login/articles/login_apr15_02_grosvenor_041315.pdf

    "PDF dccdf906ffde4b5a97d5ef7478b37c46 [1.6 Adobe PDF Library 11.0 / Adobe InDesign CC 2014 (Macintosh)] (PDF.js: 1.0.1040)"

Firefox 37.0

Incorrect in PDF.js:
![15-04-2015 4-20-34 am](https://cloud.githubusercontent.com/assets/1674237/7144146/d568e3e8-e326-11e4-9940-366c30bd4003.png)

Correct in Adobe Acrobat XI:
![15-04-2015 4-21-17 am](https://cloud.githubusercontent.com/assets/1674237/7144152/e0f43014-e326-11e4-97ad-a0d58044dd35.png)

Also works correctly in Chrome 41's built-in viewer.

**Comment by timvandermeij** [comment]
Possibly related to #5836.
