### ISSUE TITLE
PDF.js renders old report

### ISSUE THREAD

**Issue by Cora-san** [mozilla/pdf.js#5940]
Hi Team,

I am using PDF.js to render my PDF reports in my mobile web app for iOS. The PDF.js reads the PDF file "SalesData.pdf" from "Reports" folder. My Problem is that, If I update the pdf file with new data, PDF.js continues to display the same old report data.  Please help me on this issue. what can I do to tackle this problem.

Note: 'I am using your github source files for my application. I give the file name to "viewer.html" for rendering.'

Regards,

Cora-san.

**Comment by timvandermeij** [comment]
This must be some caching on the device, because this works fine locally and PDF.js just loads the most recent file from the source unless some caching is occurring. Since that is a custom implementation issue, I'm closing this as invalid for now.

**Comment by Cora-san** [comment]
There is no cache implementation in my app.
