### ISSUE TITLE
Fonts look blurry even with same zoom as in Adobe reader

### ISSUE THREAD

**Issue by nidhihooda** [mozilla/pdf.js#5941]
Hi,

The file looks blurred in pdf viewer as compared to that in adobe reader even when the zoom level is same in both. Please check the attached picture. The boldness of text seems to faint.

![image](https://cloud.githubusercontent.com/assets/11960653/7157931/dbb89ab6-e391-11e4-9b9c-865056e58876.png)

**Comment by CodingFabian** [comment]
What is blurry according to your interpretation?
I see on that second set of screenshots that the logo and line next to it are bad quality, but they are bad quality in adobe as well, In my opinion pdf.js does even a better job of displaying this thing at this zoom level.
Besides that the zoom level seems to be slightly different.

**Comment by CodingFabian** [comment]
Also please provide a PDF which exposes the problem, so we can fix it.

**Comment by nidhihooda** [comment]
Hi,

I agree that pdf did a better job in displaying the logo but the fonts in the images are thin when seen in pdf viewer. They are bold in pdf but somehow became normal in pdf viewer. Black color of fonts is  becoming lighter in pdf. I want the font as it is in the pdf viewer. This becomes more visible as the zoom level of pdf decreases. Please find the attached file for reference.
50% zoom
![image](https://cloud.githubusercontent.com/assets/11960653/7201923/b15d9592-e52a-11e4-9ffc-1de86c91b1af.png)
75% Zoom
![image](https://cloud.githubusercontent.com/assets/11960653/7201928/c2e09918-e52a-11e4-91d5-a47f08aaf0d5.png)

Zoom level are same as you can see in the pics. I tried adding the pdf here but it says- Unfortunately, we don't support that file type. Please suggest how to upload PDF.

**Comment by CodingFabian** [comment]
I see what you mean, but I assume thats due to different anti aliasing of the rendered font. Even might be related to your windows clear type setting. Its really hard to define whats the right rendering for this, especially on non 100% zoom. With regards to the PDF Upload, please upload it to a file upload site of your choice and provide the link.

**Comment by nidhihooda** [comment]
Hi,
I have uploaded the pdf. Please check. 
I have tried this on other machines and same problem is occurring there as well. Its a problem as mostly I will be using pdf viewer in 50-75% zoom.

**Comment by nidhihooda** [comment]
Hi,

Please use this pdf for checking this issue- https://drive.google.com/file/d/0ByHEu7dln2u6VjRVNjFUM2NfNkU/view?usp=sharing
Fonts get blurred as we reduce the Zoom of the PDF even though i am using image based PDF.

**Comment by kauran** [comment]
Hi,

Leaving this  comment on behalf of nidhihooda. Did someone get a chance to check the issue with the PDF in the previous comment (https://drive.google.com/file/d/0ByHEu7dln2u6VjRVNjFUM2NfNkU/view?pref=2&pli=1)?

Thanks in advance!

**Comment by yurydelendik** [comment]
@kauran they look the same to me:

<img width="994" alt="screen shot 2015-12-22 at 4 04 38 pm" src="https://cloud.githubusercontent.com/assets/1523410/11967087/cbde8142-a8c5-11e5-8624-c11f8428767f.png">

**Comment by yurydelendik** [comment]
50% zoom in reader is not 50% percent zoom in pdf.js (try ~60%)

Same as in original PDF:

<img width="971" alt="screen shot 2015-12-22 at 4 10 53 pm" src="https://cloud.githubusercontent.com/assets/1523410/11967226/ac487b16-a8c6-11e5-88d9-36fd634ec1fc.png">

Closing as works for me.

Please provide more detailed information to reopen an issue.
