### ISSUE TITLE
Not rendering PNG image in IE11

### ISSUE THREAD

**Issue by ryanpf** [mozilla/pdf.js#5942]
File:
https://drive.google.com/file/d/0B6xJdPUaaUwZUEtINUdwZVFhME0/view?usp=sharing

Using version (1.0.1040).
Renders correctly in Chrome. Repeated the test with a JPG and it renders correctly in IE and Chrome

This pdf was created by saving a web page as PDF in Chrome, creating a PDF (using FPDF) overlay including the text "BARNS, DAVID" and the "Meow" signature image, then using pdftk to merge the two.

**Comment by timvandermeij** [comment]
This renders perfectly fine in all browsers for me, also IE 11, using the latest version of PDF.js (1.1.63). It is rendering exactly the same as Adobe Acrobat and does not complain about anything in the console.

Closing as fixed. If you still experience rendering issues, please open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to test with the latest PDF.js. version. Also include a screenshot of the part that is not rendering.

**Comment by ryanpf** [comment]
Here are screenshots from the viewer.

IE
![image](https://cloud.githubusercontent.com/assets/2955908/7211170/f5f96684-e51d-11e4-936c-dd817ce14d0e.png)

Chrome
![image](https://cloud.githubusercontent.com/assets/2955908/7211181/160eb406-e51e-11e4-8586-d083b74948e5.png)

**Comment by timvandermeij** [comment]
Hm, that's really strange, because I do see the signature in IE11. Reopening with label 'triage-needed'.

**Comment by CodingFabian** [comment]
works in my IE as well

**Comment by timvandermeij** [comment]
Sounds like a driver issue then. @ryanpf Could you make sure that you have the latest graphics drivers installed?

**Comment by ryanpf** [comment]
You are right, it was an outdated display driver. Thank you so much for following up on this!

**Comment by timvandermeij** [comment]
You are welcome, and good to hear :)
