### ISSUE TITLE
When used with embed get load, progress & end events

### ISSUE THREAD

**Issue by aslamsayyed** [mozilla/pdf.js#5943]
Events thrown could be as defined in HTML5 embed/object element spec. e.g.
<embed src="my.pdf" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html"
onloadstart="myloadstart" onloadeddata="myoncomplete" onloadedmetadata onprogress onshow>

**Comment by timvandermeij** [comment]
We already have events built in and there is #5915 to add more of them. I don't see why they would also need to be added to any `embed` tag, but if there is anything that we should change, please clarify or submit a PR.
