### ISSUE TITLE
Rendering error, some text flipped across page

### ISSUE THREAD

**Issue by jethrogb** [mozilla/pdf.js#5946]
In Firefox 36.0.1 / Ubuntu 14.04:
![screen shot 2015-04-17 at 14 17 22](https://cloud.githubusercontent.com/assets/1132307/7211147/da7336bc-e50c-11e4-9f16-9267b40c21e3.png)

The header text "Advising Review Checklist" is flipped and on the bottom of the page. Same issue using Firefox 37.0.1 / Mac OS X Mavericks

Compare Adobe Reader 9.5.5 / Ubuntu 14.04:
![screenshot from 2015-04-17 14 19 17](https://cloud.githubusercontent.com/assets/1132307/7211150/dca4e264-e50c-11e4-96e5-0da3ff368edb.png)

Source file: https://jbeekman.nl/github-mozilla-pdf.js-issue-5946.pdf

**Comment by dacsy** [comment]
Is there any information about this yes ?
I am having this issues also

**Comment by jethrogb** [comment]
I have yet to see a PDF.js bug I reported fixed.

**Comment by dacsy** [comment]
Which version are you talking about ? I got the latest version: 1.2.109 and I still get the problem

**Comment by THausherr** [comment]
Another:
https://issues.apache.org/jira/secure/attachment/12636888/D.1_signiert.pdf (signature missing)

**Comment by THausherr** [comment]
A possible hint... there's a bug in the PDF specification: 12.5.5 Appearance Streams. Text is "Matrix shall be concatenated with A to form a matrix AA" should be "Matrix shall be concatenated to A to form a matrix AA" and the formula below must be changed too. This has been confirmed to be by somebody who has the PDF 2.0 specification.

**Comment by THausherr** [comment]
I believe I found the cause and it is not related to my remark above. I enclosed the page content stream in q...Q, i.e. so that after rendering the page content, the graphics attributes would be reset to their original values, and now this file and the one from #4743 (with the code change mentioned by @Osukaru) are properly displayed.

So a code change would be needed that resets something before rendering annotations.

**Comment by THausherr** [comment]
This code in core.js:
```
      return Promise.all([pageListPromise, annotationsPromise]).then(
          function(datas) {
        var pageOpList = datas[0];
        var annotations = datas[1];

        if (annotations.length === 0) {
          pageOpList.flush(true);
          return pageOpList;
        }

        var annotationsReadyPromise = Annotation.appendToOperatorList(
          annotations, pageOpList, partialEvaluator, task, intent);
        return annotationsReadyPromise.then(function () {
          pageOpList.flush(true);
          return pageOpList;
        });
      });
    },
```
if I've understood this correctly, you are creating a big list of operators with their parameters from the page content stream(s) and the content streams of the annotations. So if the page content stream(s) end with a flipped CTM (here: 1 0 0 -1 0 792 cm), the annotations will "inherit" that.

**Comment by timvandermeij** [comment]
I'm a bit confused about this issue. We have https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L1839-L1846 which *should* take care of resetting the state already. I also tried adding explicit `save` and `restore` operators around `beginAnnotations` and `endAnnotations` at https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L396-L400, but also no luck. While @THausherr's explanation is very plausible, I'm unsure why these changes have no effect at all. The issue does appear to be not properly resetting the state before drawing annotations, but I don't know of anything more we have for canvas drawing to do that.

@yurydelendik @Snuffleupagus Do you perhaps have an idea for the above? It is affecting multiple PDFs in open issues, so it would really be nice to have this resolved.

**Comment by THausherr** [comment]
What I meant is to save and restore before and after the main content stream. It is the main content stream that is the problem, i.e. if the main content stream doesn't reset all changes it has done.

I don't know enough about javascript, I remember you have some list of all operators with their parameters, ideally OPS.save should be inserted before everything, and OPS.restore at the end of the list, all that before you add the annotation content streams.

**Comment by Snuffleupagus** [comment]
@jethrogb Are you the creator of the PDF file (https://jbeekman.nl/github-mozilla-pdf.js-issue-5946.pdf), and if so may we include it in the test-suite?

**Comment by jethrogb** [comment]
I'm not, and I don't know. I can try to get permission, but it'd be easier if you could recreate the test case.

**Comment by reinh** [comment]
Why was this issue closed?

**Comment by Mirich2** [comment]
> I believe I found the cause and it is not related to my remark above. I modified the first file and enclosed the page content stream within q...Q, i.e. so that after rendering the page content, the graphics attributes would be reset to their original settings, and now this file and the one from #4743 (with the code change mentioned by @Osukaru) are properly displayed.
> 
> So a code change would be needed that resets something before rendering annotations.
> 
> The modified files: http://www.filedropper.com/pdfjs-5946unc http://www.filedropper.com/test-signatureunc

hey i have the same problem as stated above my electronic signature when viewed is seen upside down im in need of the modificatios you posted since the links are down if possible thank you
