### ISSUE TITLE
Track last viewed page using pdf.js

### ISSUE THREAD

**Issue by pyprism** [mozilla/pdf.js#5948]
I want to track my last viewed page of my pdf. Is there any way using pdf.js   ?

**Comment by timvandermeij** [comment]
If you open the PDF again, you will see that PDF.js will continue on the last viewed page of the PDF (that is, if the `showPreviousViewOnLoad` preference is not disabled). The code that handles that is here: https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L897-L909. `pageNum` there appears to be what you are looking for.
