### ISSUE TITLE
inexplicable error on xhr

### ISSUE THREAD

**Issue by laudeon** [mozilla/pdf.js#5950]
Hello,

I have an error when I try to use pdf.js. In console, I have this error ":  :". It trigger the line 1672 in pdf.worker.js.

What I'm did wrong ? It will be difficult to debug with this error message.

Thanks,
laudeon

**Comment by timvandermeij** [comment]
Could you set up the example on jsFiddle or jsBin so we can take a look?

**Comment by laudeon** [comment]
It could be quite complicate, but i'll check what can i do tomorow --> I don't have source code on my pc.

**Comment by laudeon** [comment]
So, I can't set up a jsFiddle. Too much things are related to local server side. Thanks anyway !

**Comment by timvandermeij** [comment]
What is the content of line 1672 in your `pdf.worker.js`? Without more information we cannot resolve this I'm afraid.

**Comment by laudeon** [comment]
I have this on line 1672 :
```javascript
xhr.open('GET', this.url);
```
