### ISSUE TITLE
Find (aka Ctrl-F) inside pdf.js does't work for this case

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#5955]
In pdf.js development version 1.1.73 and using Nightly 40.0a1

If I try to search "show sel", this doesn't work, but when trying "showsel" it works. The first form works in evince, so it seems to be a problem in pdf.js.

![captura de tela de 2015-04-21 14 25 00](https://cloud.githubusercontent.com/assets/1039418/7265177/1e08e824-e86c-11e4-8c26-0f240341bd3d.png)
![captura de tela de 2015-04-21 14 25 06](https://cloud.githubusercontent.com/assets/1039418/7265179/1e126f70-e86c-11e4-9a21-6d19934cf94f.png)
![captura de tela de 2015-04-21 14 25 14](https://cloud.githubusercontent.com/assets/1039418/7265178/1e107d14-e86c-11e4-8b33-c821b2ece3a9.png)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md; especially the *first* paragraph.
You need to provide a link to the PDF file in order for the issue to be valid.

**Comment by marcosps** [comment]
Ops, my fault. Here is the pdf URL:
http://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/cli/config/guide/2-1/b_UCSM_CLI_Configuration_Guide_2_1.pdf

**Comment by fbender** [comment]
Can reproduce on Fx 42 (release)

**Comment by fbender** [comment]
May be fixed by #5783

**Comment by timvandermeij** [comment]
Closing as fixed by a recent text selection PR. Note that the text can now also be copied correctly.
