### ISSUE TITLE
Issue with examples/learning/helloworldbase64.html

### ISSUE THREAD

**Issue by pudgeball** [mozilla/pdf.js#5956]
Hey there,

I was playing around with the examples and I was really interested in the example that uses a base64 encoded string to create a PDF.  However when I open the example page it errors out with the error: "Error: stream must have data".

Any thoughts as to why that might be?

Thanks!

**Comment by timvandermeij** [comment]
Works for me. Are you serving the file with a web server? You can run `node make server` in the PDF.js root folder and then visit http://localhost:8888/examples/learning/helloworld64.html in the browser. Make sure you run `node make generic` first have the built version available.

**Comment by pudgeball** [comment]
I tried this again using the beta build and it worked fine.  I used an older build and it didn't.  I'm sorry about that.  Thanks for the help.
