### ISSUE TITLE
Some PDF's incorrectly shown when printing

### ISSUE THREAD

**Issue by Ewout-Spitaels** [mozilla/pdf.js#5958]
I've reported problems with Chrome before where printing would result in 50% of size showing on the page. 
I have tested further and find that this only happens with certain pdf's.
The PDF that is provided in the examples of PDFjs works fine, but the next PDF can't not get decently scaled when printing:

![correct](https://cloud.githubusercontent.com/assets/1496578/7297077/c2c2f724-e9c5-11e4-8e60-17c29579429c.PNG)
![incorrect](https://cloud.githubusercontent.com/assets/1496578/7297078/c2c3016a-e9c5-11e4-9e60-86b85a361672.PNG)

The second (wrongly shown) PDF is available at this URL:
http://graduator.be/res/items/documents_hint/pre-2015/1420724404-2048-hint.pdf

**Comment by Hengjie** [comment]
This was fixed in https://github.com/mozilla/pdf.js/pull/5857

**Comment by timvandermeij** [comment]
Fixed by #5857.
