### ISSUE TITLE
Visual indicator to show that there are embedded files

### ISSUE THREAD

**Issue by jqnatividad** [mozilla/pdf.js#5961]
Would be nice if there's a visual hint in the UI

**Comment by timvandermeij** [comment]
Do you mean attachments? If so, do you have an example of how other PDF viewers do that?

**Comment by jqnatividad** [comment]
Yes. I meant attachments. 

I don't have an example, but one I can think of is showing the same paper clip icon already used in the sidebar next to the "Toggle Sidebar" icon when attachments are present.

Clicking on the "paper clip" would then go automatically to the "Attachments" tab.

**Comment by jqnatividad** [comment]
An opendata proposal: PDF + Data = PDDF
http://blog.civicdashboards.com/2015/08/opendata-proposal-pdf-data-pddf/

Would love to get your thoughts...

**Comment by fbender** [comment]
As proposed in #6644, I'd prefer a notification bar (similar to info when a PDF contains e.g. forms) with a button that opens the sidebar with the attachments view. This is obvious to the user and does not require new UX design or handling new items in the toolbar.

**Comment by jqnatividad** [comment]
Hi @fbender ,
If by notification bar, you mean this:

![pdf_form_example](https://cloud.githubusercontent.com/assets/1980690/11188553/68aa62cc-8c59-11e5-8c2d-c9304146e9e9.jpg)

then I agree that it is a more obvious way to show it to the reader. +1

**Comment by fbender** [comment]
Yes indeed. Could also be used similarly for when forms are supported by PDF.js
