### ISSUE TITLE
When I print the pdf file within the  viewer.html, there're always blank pages!

### ISSUE THREAD

**Issue by iKeepWalking** [mozilla/pdf.js#5967]
![image](https://cloud.githubusercontent.com/assets/869695/7337299/ea623fe4-ec57-11e4-8cd9-3e398719a986.png)

**Comment by iKeepWalking** [comment]
But actually there are no these blank pages if I open the pdf file with adobe reader.
![image](https://cloud.githubusercontent.com/assets/869695/7337220/ad34791e-ec54-11e4-90c5-109fe74b7fc4.png)

**Comment by timvandermeij** [comment]
Cloising as duplicate of #5718 and others regarding added blank pages.

**Comment by iKeepWalking** [comment]
thanks :-)

**Comment by iKeepWalking** [comment]
It's ok in Chrome  40.0.2214.111 .
But the issue is still there in node-webkit 0.12.1( Chromium 41.0.2272.76)
;-(
