### ISSUE TITLE
CORS + APACHE + PHP

### ISSUE THREAD

**Issue by fabi0w** [mozilla/pdf.js#5968]
Congratulations on the project. But someone has a concrete example that works with CORS? apache + php + win7? I found this example http://colonelpanic.net/2014/08/using-pdf-js-web-worker-cross-domain-cors/ but was unable appears error: XMLHttpRequest can not load http://www.education. gov.yk.ca/pdf/pdf-test.pdf. In the 'Access-Control-Allow-Origin "header is present on the requested resource. Origin 'http: // localhost: 8080' is not allowed Therefore access.

TKS

**Comment by Snuffleupagus** [comment]
Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr. As outlined there, this is out of scope of the PDF.js project.
