### ISSUE TITLE
Workaround for hardware accelerated rendering errors

### ISSUE THREAD

**Issue by tass01024** [mozilla/pdf.js#5969]
Steps:
1) On laptop with integrated intel graphics (like HD 4400) with Windows7/64bit
2) Use Internet Explorer 11 with Hardware acceleration on (HWA on) 
3) use/load a PDF with small fonts

Seen:
Some text are rendered with defects, especially final letters in sentences

Workarounds:
- Turn off HWA in IE settings
- change code to use a higher output scale, like high DPI devices, causing higher memory usage
- fix Intel graphics 64bit windows driver!

**Comment by timvandermeij** [comment]
Thank you. There have been fixes for HWA-related issues before and the rest of them are in currently open issues. We cannot do anything about the driver, but the other two options do fix the issues sometimes, although both are not ideal. Closing this issue as there is no concrete problem (which is what this issue tracker is for), but the tips here might be useful for some users that experience problems with this.
