### ISSUE TITLE
Android 4.3 Cordova PDF doesn't load

### ISSUE THREAD

**Issue by cdennington** [mozilla/pdf.js#5973]
I can't get a PDF to load on Android 4.3, in the app I have created using cordova, the screen loads blank, and I get the same issue if I use the default Samsung browser. However, loading the app and site on newer versions of Android the PDF loads fine.

I've tried to debug using the promises set up in your plugin, but I only get the following message in console, which is less than helpful
![screenshot_2015-04-28-16-42-49](https://cloud.githubusercontent.com/assets/1114197/7364238/a5fff3f2-edc7-11e4-8097-30f05c574db0.jpg)

I'm using the latest files: 
pdf.js
pdf.worker.js
compatibility.js

Below is the code I'm using to call pdf.js, I call it in a angular controller:
```
window.pdfDoc = PDFJS.getDocument(url);
        console.log(
            "URL: " + url + '\n' +
            "PDFJS: " + PDFJS + '\n' +
            "PDFElement: " + JSON.stringify(window.pdfDoc)
        );
        window.pdfDoc.then(function (pdfDoc_) {
            console.log("SUCCESS: " + pdfDoc_);
            pdfDoc = pdfDoc_;
            document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
        }, function(error) {
            console.log("ERROR: " + JSON.stringify(error));
        });
```

The site shows no errors, but the status of the promise stays at 0, which means it never resolves. We have searched the tickets here but found no one else having this issue.

Thanks

**Comment by yurydelendik** [comment]
Solved at http://stackoverflow.com/a/34027997/1765767 . Closing as answered.
