### ISSUE TITLE
Annotations appear misplaced

### ISSUE THREAD

**Issue by mabkenar** [mozilla/pdf.js#5974]
I have a PDF file (in grayscale) which is annotated (in red) using the Adobe PDF software. Opening it using Evince or Adobe Reader shows the annotations in the correct position (middle right of the page).

Opening the same file using pdf.js shows the annotations 
(a) much smaller, and
(b) in the wrong place, bottom left of the page.

Here is the PDF file:
https://iffcloud.fz-juelich.de/index.php/s/PxmixAyXdPyg252

Firefox version: 37.0.2
Also tested in ownCloud: version 8.0.2 (stable)

**Comment by mcorb** [comment]
The annotations appear in the correct place with current PDF.js from git.

**Comment by mcorb** [comment]
The integration process used by owncloud seems unsatisfactory:

  https://github.com/owncloud/files_pdfviewer

It looks like they're bundling a partial build of the PDF.js sources without indicating which version is in use, which makes it difficult to diagnose problems here.

They should really use npm, bower or git submodules to handle dependencies so PDF issues can be addressed by the correct developers in the community. (I see a trail of PDF.js bug reports in their bug tracker that's mostly redundant duplication of effort.)

**Comment by mabkenar** [comment]
I suppose the version of pdf.js shipped with Firefox is up-to-date. Now I want to test my PDF using the Firefox version of pdf.js from my local file. 
When I open my local PDF file (Ctrl+O) from inside Firefox, I see a Firefox dialog asking whether I want to save the file or to open it using an external viewer. How can I force Firefox to open the file internally using pdf.js?

**Comment by timvandermeij** [comment]
It does not seem to work for me yet, even with the latest PDF.js build. You can always work with the latest PDF.js build (Git master) on https://mozilla.github.io/pdf.js/web/viewer.html. Use the Open File button in the toolbar to open a PDF file.

**Comment by mabkenar** [comment]
@timvandermeij thanks for your help. For me it is also the same. Even the Git master branch shows the annotations wrong (very small and in the bottom left). The Evince 3.10.3 viewer on my Ubuntu 14.04 LTS works fine, showing the annotations in the middle right and much bigger (as it was intended when edited by my colleague using Adobe Reader).
@mcorb Can you confirm this?

**Comment by mcorb** [comment]
@mabkenar My mistake. A local copy of the PDF was auto-saved by the Preview PDF viewer, and that appears to have made it work.

I can now confirm the misplaced annotations are still a problem with the original file and the current development PDF.js.

**Comment by timvandermeij** [comment]
Closing as fixed by #6814.
