### ISSUE TITLE
PDF Blank in Chrome

### ISSUE THREAD

**Issue by cvaught** [mozilla/pdf.js#5975]
PDF LInk: https://dl.dropboxusercontent.com/u/2541471/72050.pdf

Tested in chrome version 42.0.2311.90 (64-bit), and the PDF is blank. In Firefox it is displayed but performance is poor.

**Comment by timvandermeij** [comment]
It is blank for me in Firefox too. Marking as triage needed.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by arielcarrera** [comment]
It's blank for me in Chrome too.

**Comment by timvandermeij** [comment]
This PDF file contains a 18000 x 24000 pixel image. So this is again an issue where tiling the canvas would probably help.

**Comment by Snuffleupagus** [comment]
Closing, since the PDF file is no longer available.
(We can re-opened the issue if the problematic PDF file is *attached* here.)
