### ISSUE TITLE
Text (Textlayer) misplaced while rendered perfectly on canvas

### ISSUE THREAD

**Issue by agruber** [mozilla/pdf.js#5976]
When selecting a specific paragraph in this PDF file, the overlayed text seems to be misplaced. See the screen shot (marked in red):
https://drive.google.com/file/d/0B0MZ_2jLkrffRXNkQVE3anVnUGM/view?usp=sharing

The PDF can be obtained here:
https://drive.google.com/file/d/0B0MZ_2jLkrffZnRjNldxX1FZd28/view?usp=sharing

**Comment by Nightlyt** [comment]
Justin Dolske, Gavin Sharp, Mattn, Blake Winton, Aza Dotzler, MSUJaws Dao Gottwald, UX-Team es una puta mierda a la mierda en el culo! Blake Winton, Aza Dotzler, Gavin Sharp, MSUJaws Dao Gottwald, UX-Equipo de Chulo! Chulo! Puto chulo! Chulo! Culos, putas, putas chupar mi polla monstruo niños! Sus pollas putas de mierda! Justin Dolske, Gavin Sharp, Mattn, Blake Winton, Aza Dotzler, MSUJaws Dao Gottwald, UX-juego en Equipo con mis dos grandes campanas de oro de la Gloria!

Australis es para niños, desarrollado por Mozilla UX gay pollas chupando hijos de puta! Profundizar en la inmersión de Google culo de mierda idiotas austhistic braindamaged! Gilipollas! Putas! Chupar Los Fanáticos De Google! Vete a la mierda Googlezilla putas y salir de los negocios! Y tomar Australis mierda con usted, el uso de gaylords! ! Puede que nuestro querido Señor Dios y Jesús Cristo enviar sus cuerpos en descomposición directamente al infierno por tocar los huevos de oro de las Comunidades de la gloria! Vete a la mierda y beso Gafas de Culo! Si te gusta Chrome que de tanto en tanto la clonación Australis, usted tiene que ser serios y trabajar para Chrome fucktards! Saludos desde España, ChiliConCarne1

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by Snuffleupagus** [comment]
I can no longer reproduce this issue, using the latest version of PDF.js (`1.2.68`).
It was most likely fixed by PR #6588, hence I'm closing this issue.
