### ISSUE TITLE
PDF.js full screen mode on Android mobile browser appears corrupted

### ISSUE THREAD

**Issue by rajeevk27** [mozilla/pdf.js#5981]
Observed following issues rendering on mobile devices:
1. full screen mode randomly kept on flickring
2. Navigation (back / forward etc) not working
3. full screen mode on mobile occupied only half the available view port of the device
4. Device back button closes the browser instead of the full screen view

**Comment by timvandermeij** [comment]
I cannot reproduce 1 and 4 on my Nexus 6 with Firefox for Android. 2 and 3 are indeed not completely functional yet.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by timvandermeij** [comment]
The closed issue above also mentions "At the first time I saw the toolbar at the top, behind the page".

**Comment by timvandermeij** [comment]
Closing since this is a very old issue and many improvements have been made in the meantime.
