### ISSUE TITLE
Truncated images

### ISSUE THREAD

**Issue by SamyCookie** [mozilla/pdf.js#5986]
Hi,

This PDF renders badly on firefox 37.0.2 with PDF.js 1.1.114 (and also trunk web version).
Some images are truncated.
No errors in console logs.

Computer: Win 7 64bits

http://www.virginmobile.fr/media/virgin/offres/pdf/fis-forfaits-se-avec-ou-sans-option-mobile.pdf

Good luck !

**Comment by SamyCookie** [comment]
Hum, no error detected with Firefox 37.0.2 and Chromium 42.0.2311.135 on Linux Debian.
Seems to be Windows specific error, I will test with chrome on Windows earlier.

**Comment by SamyCookie** [comment]
No errors either with Chrome 42.0.2311.135 on Win 64.

**Comment by yurydelendik** [comment]
@SamyCookie Can you post the "Graphics" section from the about:support? Also, can you check if drivers on the Windows up-to-date?

**Comment by SamyCookie** [comment]
Of course, here they are:

Date du pilote	11-20-2014
Description de la carte	AMD Radeon HD 7800 Series
Direct2D activé	true
DirectWrite activé	true (6.2.9200.16571)
Fenêtres avec accélération graphique	1/1 Direct3D 11 (OMTC)
GPU 2 actif	false
ID du périphérique	0x6819
ID du sous-système	201c1787
ID du vendeur	0x1002
Pilotes de la carte	aticfx64 aticfx64 aticfx64 aticfx32 aticfx32 aticfx32 atiumd64 atidxx64 atidxx64 atiumdag atidxx32 atidxx32 atiumdva atiumd6a atitmm64
RAM de la carte	2048
Rendu WebGL	Google Inc. -- ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Version du pilote	14.501.1003.0
windowLayerManagerRemote	true
AzureCanvasBackend	direct2d 1.1
AzureContentBackend	direct2d 1.1
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0

Drivers are indeed up to date according to AMD update software

**Comment by SamyCookie** [comment]
I have installed bêta graphic driver that is more up to date, but bug is still here.

Date du pilote	3-31-2015
Description de la carte	AMD Radeon HD 7800 Series
Direct2D activé	true
DirectWrite activé	true (6.2.9200.16571)
Fenêtres avec accélération graphique	1/1 Direct3D 11 (OMTC)
GPU 2 actif	false
ID du périphérique	0x6819
ID du sous-système	201c1787
ID du vendeur	0x1002
Pilotes de la carte	aticfx64 aticfx64 aticfx64 aticfx32 aticfx32 aticfx32 atiumd64 atidxx64 atidxx64 atiumdag atidxx32 atidxx32 atiumdva atiumd6a atitmm64
RAM de la carte	2048
Rendu WebGL	Google Inc. -- ANGLE (AMD Radeon HD 7800 Series Direct3D11 vs_5_0 ps_5_0)
Version du pilote	14.502.1014.0
windowLayerManagerRemote	true
AzureCanvasBackend	direct2d 1.1
AzureContentBackend	direct2d 1.1
AzureFallbackCanvasBackend	cairo
AzureSkiaAccelerated	0

**Comment by SamyCookie** [comment]
Bug is gone with HWA off.

To resume, it's a specific Windows bug with Firefox and HWA on. So it means that the problem is due to graphic drivers ?

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by yurydelendik** [comment]
Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1168189 -- marking as upstream bug

**Comment by SamyCookie** [comment]
I confirm that both https://bugzilla.mozilla.org/show_bug.cgi?id=1168189 and https://bugzilla.mozilla.org/show_bug.cgi?id=1170739 are visually corrupted on my computer.

**Comment by SamyCookie** [comment]
I also confirm that http://output.jsbin.com/gufozi/1/ failed with HWA enabled and works when disabled.

**Comment by SamyCookie** [comment]
upstream bug fixed, it seems it will be effective for Firefox 42.
I'll close this bug when I will be able to confirm this.

**Comment by timvandermeij** [comment]
@SamyCookie Thank you for that. The patch is probably already in a Nightly build of Firefox, so maybe that will help you verify the fix.

**Comment by SamyCookie** [comment]
Upstream bugfix was backported to bêta channel.
I have installed Firefox 40b2 in 64bits and all is working correctly on my computer.

Closing as fixed, thanks all !!!
