### ISSUE TITLE
In Firefox  the pdf is displayed but its taking more time to display

### ISSUE THREAD

**Issue by karunakarkarna** [mozilla/pdf.js#5987]
I Tested in Firefox latest version(64-bit) with windows 7  the PDF is displayed but its taking more time to display the pdf  and in the same os  with chrome browser it loaded fastly,
and in Ubuntu also displayed correctly and loaded also good.
i need to show in Firefox latest version with windows 7.
and the sample pdf is http://www.pdf995.com/samples/pdf.pdf i need to display this pdf in Firefox windows7 with good performance.

please check it once and  tell me the solution for this as soon as possible

**Comment by timvandermeij** [comment]
Displays instantly for me using Windows 7 x64, Firefox 37.0.2 and the latest PDF.js development version. Please try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if that resolves the issue.

**Comment by CodingFabian** [comment]
doublechecked, renders instantly also with built in pdf.js on Windows 7 x64, Firefox 37.0.2.

**Comment by timvandermeij** [comment]
Closing as incomplete/working for now.
