### ISSUE TITLE
Unable to revert permanent deny for fullscreen in pdf.js

### ISSUE THREAD

**Issue by AllanDaemon** [mozilla/pdf.js#5988]
After opening a pdf file in pdf.js and gone fullscreen, I clicked in the check box to remember my decision, and by **mistaken I click in `deny` instead of `allow`**. Now I **can't go fullscreen** with it: clicking in fullscreen button in pdf.js toolbar does nothing. I also **can't find any way to undo** this.

Even if I click in the globe icon before the url, go in `More Information` > `Permissions` > `Enter fullscreen` > `Allow`, it won't work. It also doesn't work if I try to go full screen in another PDF in another sites (domain).
I suppose it's showing the permission to the site I'm viewing, and the permission denied was for the pdf.js, as it was what was named in the fullscreen confirmation popup.

Here is the part of the dump of the permissions.sqlite dump of my profile. The last one ('www.facom.ufu.br') was made by me trying to white list the site for full screen as descried earlier.

```sql
$ sqlite3 permissions.sqlite .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE moz_hosts ( id INTEGER PRIMARY KEY,host TEXT,type TEXT,permission INTEGER,expireType INTEGER,expireTime INTEGER,modificationTime INTEGER,appId INTEGER,isInBrowserElement INTEGER);
(...)
INSERT INTO "moz_hosts" VALUES(12,'pdf.js','fullscreen',2,0,0,1430997732127,0,0);
INSERT INTO "moz_hosts" VALUES(14,'www.facom.ufu.br','fullscreen',1,0,0,1430997870757,0,0);
COMMIT;
```

I can of course edit the permissions file by myself, but this is not reasonable for a normal user.

Version: Firefox 37.0.2
Mozilla Firefox for Ubuntu
canonical - 1.0

It's the Firefox that came with Ubuntu 14.04 (Trusty) 64bit, fully updated.

![firefox pdf js screenshot](https://cloud.githubusercontent.com/assets/607994/7515281/0c6aabe8-f49c-11e4-9f14-f665e02ca620.png)

**Comment by timvandermeij** [comment]
I think this is not an issue with PDF.js, but rather with how the full screen functionality is handled in Firefox. Please file this issue at https://bugzilla.mozilla.org for Firefox instead as this is not something that can be resolved on the PDF.js side. We would need something to undo that, but Firefox should provide that, not PDF.js.

**Comment by Snuffleupagus** [comment]
It should be possible to revert that setting; even though I agree that it isn't too discoverable.
Try the following steps:
 1. Open `about:permissions` (enter it in the URL bar).
 2. In the "Search Sites" box, enter `pdf.js` and click on the result.
 3. Reset the "Fullscreen" setting. (If that doesn't work, try clicking on the "Forget About This Site" button.)

___
![deny_fullscreen](https://cloud.githubusercontent.com/assets/2692120/7524895/6007649e-f505-11e4-87f3-c51a7d577bba.png)
