### ISSUE TITLE
Chrome: OPTIONS preflight request gives empty response from CloudFront

### ISSUE THREAD

**Issue by bernljung** [mozilla/pdf.js#6003]
I have created an AWS support ticket for this but I thought I'd check here as well to see if anyone experienced the same thing.

Some of our Chrome users are unable to get requested content in chunks. The browser's preflight OPTIONS request simply fails with an empty response from CloudFront. From what we've seen the problem occurs for about 10% of the users. Note that we have only seen this behaviour with PDF.js + CloudFront.

For instance, a certain user is able to access the demo application and see the PDF.
http://mozilla.github.io/pdf.js/web/viewer.html

We then uploaded the same PDF to our S3/CloudFront and pointed the demo application to this url instead. This time the user is unable to see the PDF at all, the OPTIONS request gives an empty response: 
http://mozilla.github.io/pdf.js/web/viewer.html?file=http://cdn-stage.im-epaper.se/compressed.tracemonkey-pldi-09.pdf

The CORS configuration we use on the S3 bucket looks like this:
```
    <CORSRule>
        <AllowedOrigin>http://mozilla.github.io</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>Accept-Ranges</ExposeHeader>
        <ExposeHeader>Content-Encoding</ExposeHeader>
        <ExposeHeader>Content-Length </ExposeHeader>
        <ExposeHeader>Content-Range</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
```

Have anyone else seen this behaviour before?

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
