### ISSUE TITLE
Chrome Bug for large pdfs (pages out of order)

### ISSUE THREAD

**Issue by acmisiti** [mozilla/pdf.js#6005]
In chrome & firefox, for some large PDFS they pages are rendered out of order. I noticed that the issue does not happen in safari. Some of the pages in the middle of the document contain alot of graphics and I noticed that they were the last onces to be appended to the end of the PDF. It does not seem to be a coincidence that the pages rendered last had heavy graphics.

**Comment by timvandermeij** [comment]
We really need an example PDF file and more information about your configuration in order to investigate this. Could you post that?

**Comment by acmisiti** [comment]
The PDF i found the issue with is confidential so I will have to find another one and then post it.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by timvandermeij** [comment]
Closing until we have a PDF file to verify the issue, because until then there is nothing we can do about this. Make sure that you also use the latest browser versions and open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to verify if the issue exists in the latest version of PDF.js.
