### ISSUE TITLE
Radial gradient

### ISSUE THREAD

**Issue by ofirdev** [mozilla/pdf.js#6006]
The radial gradient in this PDF appears as a small dot.
Maybe the radius is wrong?
https://drive.google.com/file/d/0B0odzw1WMqkGTkFyZGFKamdaNUU/view

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
