### ISSUE TITLE
AAATA bus schedule rendering image with black background on Chrome

### ISSUE THREAD

**Issue by vielmetti** [mozilla/pdf.js#6008]
This might be multiple issues, and I'm tracking detail on https://github.com/a2civictech/a2civictech/issues/134 .

The AAATA (Ann Arbor Area Transporation Authority) produces a bus schedule in PDF which renders variously on various devices using PDF.js (under ViewerJS). Versions are

PDFJS.version = '1.0.1040';
PDFJS.build = '997096f';

Test page up at http://vielmetti.typepad.com/vacuum/2015/05/summer-2015-route-5-to-ann-arbor-schedule-as-embedded-with-viewerjs.html which renders this original schedule http://www.theride.org/Portals/0/Documents/1SchedulesMapsAndTools/RtMaps/Current/5toAA.pdf

**Comment by Snuffleupagus** [comment]
Renders identical to Adobe Reader for me, using: Windows 7 (64-bit), Firefox Nightly 41 (buildID: 20150512030215) with HWA on, and PDF.js 1.1.124.

**Comment by yurydelendik** [comment]
@vielmetti looks like it's just a version that is used by ViewerJS. If not, can you provide more information and a criteria for closing this issue?

**Comment by vielmetti** [comment]
@yurydelendik -

I'm hoping to bisect the releases so that I can determine which release and platform things work on, and which don't. To do that I need to sort out a few config operations in ViewerJS which doesn't yet make it easy to specify an arbitrary release, and make sure that the ViewerJS project moves forward to the latest PDF.js release for testing. The issue to track that is at  https://github.com/kogmbh/ViewerJS/issues/144 .

My environments are 
- Mac OS X 10.9.5 (Mavericks) + Chrome 42.0.2311.152 (build environment)
- Windows Phone 8.1 + IE (my phone)
- Android + Chrome (my son's phone)
- iPhone + Safari (user report)

Based on @Snuffleupagus results, if this page renders identically on the Mac OS X 10.9.5 + Chrome 42.latest + PDF.js 1.1.124 then I'm happy to close this, and to that end I'll test that combo next. (Whatever other issues would be platform specific and could get separate issues, once I'm up to the latest rev of PDF.js in my build environment.)

**Comment by yurydelendik** [comment]
Okay, that is a Chrome issue. Reduced test case at http://jsbin.com/zinige/1/, reported at https://code.google.com/p/chromium/issues/detail?id=488103

**Comment by yurydelendik** [comment]
@vielmetti fyi, we don't accept meta issues or issues without criteria to close it (see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md)

I'm renaming the current issue to the one related to the Chrome displaying image with black background. The issues with Windows Phone 8.1 or iPhone shall be filled separately. And as you said you already tracking that on your side, so you can refer only PDF.js issues from yours.

**Comment by vielmetti** [comment]
Thanks @yurydelendik for identifying (and reducing!) the Chrome issue. I'll narrow down the other ones separately and open up separate issues once I have the test environment to reproduce them.

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by yurydelendik** [comment]
Upstream bug is fixed. Closing
