### ISSUE TITLE
Disabling cache?

### ISSUE THREAD

**Issue by bibos** [mozilla/pdf.js#6009]
Hi everyone,

When I open a PDF file with the viewer, then destroy the file on the server, and refresh the viewer... The PDF file still can be oppened.

How can I disable this? With disabling the cache I assume, but how ?

Thanks for any help.

Bruno

**Comment by yurydelendik** [comment]
PDF.js does not store any files and relies on browser to provide the data. In most cases it's either browsers cache (erase browser's cache) or your hosting aggressive caching (disable that or just wait couple of days). Closing as answered.

**Comment by bibos** [comment]
I'm using pdf.js to have an overview of a PDF file while creating it online... So I must have an overview refreshing everytime... Do I have to rename the file everytime with a random name?

**Comment by yurydelendik** [comment]
> Do I have to rename the file everytime with a random name?

Too little information is provided about a problem. If the issue with the hosting site, please consult with them to provide more efficient solution.

**Comment by bibos** [comment]
I asumed it was an issue with the viewer and not the host since if I open the PDF file directly in the browser (with Chrome for example), it is correctly refreshed.

**Comment by bhmb2000** [comment]
You can disable cache by making changes in pdf.js file under defaultPreferences 
Open  your pdf.js file and update as follow -
Set showPreviousViewOnLoad = false,

`defaultPreferences = Promise.resolve({
      "showPreviousViewOnLoad": false,
       ....
`
