### ISSUE TITLE
Can't open encrypted PDFs with R = 6 and password containing multibyte characters

### ISSUE THREAD

**Issue by wizkids** [mozilla/pdf.js#6010]
Test PDFs:
Password "abc": https://docs.google.com/file/d/0B6UCteMctzGBeWFPWVNjaURuQk0/edit
Password "æøå": https://docs.google.com/file/d/0B6UCteMctzGBYWh2ZzQtbW1USmc/edit

Both PDFs have been created with CPDF command line tool using the AES256ISO encryption (which has R = 6) with the password being the only difference.

Encryption using R = 6 is specified in ISO 32000-2: http://www.pdfa.org/wp-content/uploads/2014/09/ISO-32000-2_DIS-1_REVIEW_ONLY.pdf (still under development, but check section 7.6 and section 7.6.3.2). Despite this several libraries support encrypting using this R value.

Seems like the default encoding of passwords has been changed from ISO-8859-1 to UTF-8 for R = 6, so most readers are not capable of opening encrypted PDFs with password using multibyte characters. At time of testing only Acrobat Reader is capable of opening both PDFs.

Test across a couple of viewers: https://docs.google.com/spreadsheets/d/1Bg3eSe5cGSZJy-4k4j2KV_3hS0uhNtx6Xz3OV3JcncA/edit

**Comment by yurydelendik** [comment]
Looks like we need to change how we treat password only for revision 6 only(?). Somewhere around https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js#L1921

**Comment by yurydelendik** [comment]
(`unescape(encodeURIComponent('æøå'))` shall do the job)

**Comment by Snuffleupagus** [comment]
I haven't got time to test it right now, but this seems to work fine: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-6010.

**Comment by yurydelendik** [comment]
> I haven't got time to test it right now, but this seems to work fine:

Based on the spreadsheet above that shall happen only for R=6.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!
