### ISSUE TITLE
Image is drawn as black "placeholder"

### ISSUE THREAD

**Issue by tkoski** [mozilla/pdf.js#6034]
Version: pdf.js 1.1.155

Problem:
The image on the right hand side is drawn as a black placeholder.

Image drawn OK on this pdf: http://62.210.181.5/ok.pdf
Not OK (image drawn black) on this pdf: http://62.210.181.5/nok.pdf

Expected output of nok.pdf:
![should_look_like](https://cloud.githubusercontent.com/assets/829168/7703176/d1e9a760-fe3e-11e4-93fb-0d4fc202e08d.jpg)

Console log: none

Opening the nok.pdf for example with Chromium Version 41.0.2272.76 Ubuntu 14.04 works fine.

**Comment by Snuffleupagus** [comment]
The file `nok.pdf` appears to be corrupt. Even Adobe Reader fails to render the graphics, and warns that the file might not display correctly (sorry about the Swedish language in the prompt):

![nok](https://cloud.githubusercontent.com/assets/2692120/7707453/258313fa-fe50-11e4-9c6d-b52b8a6be051.png)

**Comment by tkoski** [comment]
@Snuffleupagus you are right. There is something wrong with the pdf file since some other viewers do not show it correctly either.

How ever some do show it correctly (like the one in Chrome) so I do not know if pdf.js -team wants to still try to get this "fixed".

But from my behalf this issue can be closed.

**Comment by timvandermeij** [comment]
Closing since the files are no longer available and we now have more logic in place for recovery of broken content in PDF files.
