### ISSUE TITLE
Reduce memory footprint of thumbnails

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6035]
We have discussed on IRC that it might be helpful to package rendered thumbnails as PNG to reduce their memory consumption. This should be done when the viewer is idle, i.e., not when the user is scrolling.

**Comment by vineetpurswani** [comment]
I want to work for it. Can you tell me what exactly needs to be done?

**Comment by timvandermeij** [comment]
Probably all code you need is in https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_view.js. At https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_view.js#L242-L261 we render the page onto a thumbnail canvas.

The idea is that when thumbnails are created, they are drawn on a separate canvas. We have to keep these canvases in memory such that the thumbnail viewer can be used at all times. The goal of this issue is to package the rendered thumbnails as PNG instead of keeping them as canvases in order to reduce the memory we need for them (canvas is essentially a plain pixel map and PNG is more compressed). Maybe we can just use `canvas.toDataURL("image/png");`, otherwise we have a "convert image data to PNG" function at https://github.com/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/src/display/svg.js#L29-L219. If we must use that here, we should extract it into a separate component and apply that to the thumbnails.

For more details I hereby ping @yurydelendik, but he is currently on vacation, so it might take some time before he responds here.

For starters it would be nice to have a benchmark of how much memory the thumbnails use in the current implementation. Take the PDF reference for example with 1310 pages: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf. Theoretically, here (http://logs.glob.uno/?c=mozilla%23pdfjs&s=19+May+2015&e=19+May+2015&h=package#c34123) is the size of one thumbnail, so multiplying that by 1310 *should* give an upper bound for the memory usage of the thumbnails, but we do not know if that theoretical bound is also true in practice. Once we have an idea of the current memory usage, you can create this PNG patch and see if it indeed helps to reduce memory usage.

**Comment by zinking** [comment]
as for the benchmarks of how memory have been saved, is there any similar test in the existing pdf.js tests?

**Comment by timvandermeij** [comment]
@zinking No, that should be done manually by measuring memory consumption of the process.
