### ISSUE TITLE
Extra blank page ejected when printing all pages in a PDF in Firerfox

### ISSUE THREAD

**Issue by pal1000** [mozilla/pdf.js#6038]
This includes documents that only have 1 page.
Both Firefox built-in version and dev extension are affected. Current version of extension as of writing this, is v1.1.159-g 82536f8f
This is reproducible with any PDF including the example one. Doesn't happen if I try to print a specific page or a range of pages.

**Comment by timvandermeij** [comment]
Closing as duplicate of #4041.
