### ISSUE TITLE
Sharp symbol (#) in 'file' url parameter

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#6039]
Hello!
I try to open PDF file which contains '#' symbol in filename - Act#1.pdf (`https://mozilla.github.io/pdf.js/web/viewer.html?file=http://localhost/Act%231.pdf`).
PDF.js decoded all url parameters via decodeURIComponent() and unsuccessful attempted to open http://localhost/Act#1.pdf.
Opening file directly:
![1](https://cloud.githubusercontent.com/assets/10258064/7765219/c80d7c66-0074-11e5-81e3-865d6e8d2a43.png)
Opening file via PDF.js:
![3](https://cloud.githubusercontent.com/assets/10258064/7765232/ec0a030a-0074-11e5-8b66-c88bd626cb69.png)

Maybe needed a special way to handle 'file' parameter?

**Comment by yurydelendik** [comment]
I think there two problems: CORS does not let you fetch file cross domain (see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request about that) and you are not escaping '%' in parameters (shall be .../web/viewer.html?file=http://localhost/Act%25231.pdf). Closing as answered.

**Comment by jazzy-em** [comment]
Thanks
