### ISSUE TITLE
render the position of text error

### ISSUE THREAD

**Issue by luowei-D** [mozilla/pdf.js#6040]
Hi i use PDF.js to render some pdf files in Chinese, but after transform pdf to svg,the position of some text is not right, just like the picture show.
![Image of error position of text](http://112.124.12.145:8082/error-font-position.png)
And in the browser console, there some Waring:
`
pdf.worker.js:14077 GET http://xxxx.com/nullAdobe-GB1-UCS2 404 (Not Found)createBuiltInCMap @ pdf.worker.js:14077CMapFactory.create @ pdf.worker.js:14090Font_buildToUnicode @ pdf.worker.js:18623Font @ pdf.worker.js:16524PartialEvaluator_translateFont @ pdf.worker.js:12262PartialEvaluator_loadFont @ pdf.worker.js:11062PartialEvaluator_handleSetFont @ pdf.worker.js:10834next @ pdf.worker.js:11223(anonymous function) @ pdf.worker.js:11228
pdf.js:7 Warning: Unimplemented method setFlatness
pdf.js:7 Warning: Unimplemented method dependency
pdf.js:7 Warning: Unimplemented method setRenderingIntent
pdf.js:7 Warning: Unimplemented method dependency
pdf.js:7 Warning: Unimplemented method setFlatness
pdf.js:7 Warning: Unimplemented method dependency
pdf.js:7 Warning: Unimplemented method setFlatness
pdf.js:7 Warning: Unimplemented method dependency
pdf.js:7 Warning: Unimplemented method beginGroup
pdf.js:7 Warning: Unimplemented method setFlatness
pdf.js:7 Warning: Unimplemented method endGroup
`

I know the http://xxxx.com/nullAdobe-GB1-UCS2 404 is because of missing the configuration of PDFJS.cMapUrl，I try to configure PDFJS.cMapUrl, but after that all the text disappear.

Please help me to solve the problem, Thanks.

**Comment by timvandermeij** [comment]
We need an example PDF to verify the issue and more information on your configuration. I must also mention that the SVG back-end is not complete yet and not officially in use.

**Comment by barlowluo** [comment]
You can download the example PDF here : http://112.124.12.145:8082/chinese-example.pdf  . Thanks.

**Comment by timvandermeij** [comment]
The link to the PDF file is dead. Since the creation of this issue many font conversion and SVG back-end issues have been fixed. Closing for now; if the issue remains, please re-upload the PDF file to GitHub/Dropbox/another service where the link does not expire quickly.
