### ISSUE TITLE
PDF.JS Upgrade questions

### ISSUE THREAD

**Issue by eoctavien** [mozilla/pdf.js#6042]
I just downloaded the newest version of pdf.js on my local machine (I used to have version 1.0.1040). What is new in this latest version? I also noticed that the printer icon from this one is gone, was it taken out? Thanks.

**Comment by eoctavien** [comment]
Also I noticed that in the demo version (http://mozilla.github.io/pdf.js/web/viewer.html) it seems to have  fullscreen capabilities. Is there any way I can include that in my version?

**Comment by yurydelendik** [comment]
> I also noticed that the printer icon from this one is gone
> I noticed that in the demo version (http://mozilla.github.io/pdf.js/web/viewer.html) it seems to have fullscreen capabilities

Downloaded from http://mozilla.github.io/pdf.js/getting_started/#download viewer shall have all capabilities of http://mozilla.github.io/pdf.js/web/viewer.html. See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions .

Printing and presentation mode capabilities functions are tested against a web browser capabilities (e.g. mozPrintCallback or fullscreenEnabled), so they may be disabled if deployed not as http://mozilla.github.io/pdf.js/web/viewer.html or different browser used.

Closing as answered.

**Comment by eoctavien** [comment]
OK thank you, but do you recommend the stable or beta version?

**Comment by timvandermeij** [comment]
For production we always recommend the stable version. The beta version is usually for testing purposes. For development of PDF.js you can use the master branch on GitHub.
