### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by eoctavien** [mozilla/pdf.js#6043]
I have been having some performance issues when running pdfjs from my server. When I try to run it locally, it seems to work well however when I publish from the server, often times my pdfs load slowly and in some cases freeze. Is there any way I can optimize performance? Is it just my server is too slow. I would like to have it load as fast as the demo does (http://mozilla.github.io/pdf.js/web/viewer.html). Also I feel as I should mention I do not have the latest version (I have 1.0.1040). Would upgrading improve (or impede) perforance?

**Comment by yurydelendik** [comment]
@eoctavien provide public URL to the viewer on your sever to help to troubleshot the issue.

**Comment by timvandermeij** [comment]
Closing as invalid for now. Please provide the information mentioned above to reopen.
