### ISSUE TITLE
PDF rendered upside down. 

### ISSUE THREAD

**Issue by gladsonrobinson** [mozilla/pdf.js#6053]
I am rendering the pdf from base-64 encoded data.  I am showing the pages as a slider way in a popup. 
For every 5 sec the page will be changing automatically. It works fine. But the problem is when I select any other tabs in a browser  and coming back to our page the data is show as upside down  or as a mirror image for that particular page and when the page changes it shows as a regular one. 

Any help please...

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you read: https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. In this case, the *fourth* paragraph seem especially relevant.

**Comment by timvandermeij** [comment]
Closing as incomplete for now. Please provide the information mentioned above to reopen.
