### ISSUE TITLE
Text Missing / Colors Displayed Incorrectly

### ISSUE THREAD

**Issue by jwhammond** [mozilla/pdf.js#6055]
In the following PDF, http://aualum.org/pdfs/magazine/mediakit2015.pdf , text colored #10233e is being displayed as #ff0000. Text with the color #f27f3c is not displayed at all. How the PDF should appear and how it is being displayed are shown in the two screenshots below.

In Chrome:
![screen shot 2015-05-27 at 9 10 30 am](https://cloud.githubusercontent.com/assets/6800333/7838121/cc77bdcc-0450-11e5-84da-23f0394c4b29.png)

In Firefox:
![screen shot 2015-05-27 at 9 10 45 am](https://cloud.githubusercontent.com/assets/6800333/7838126/cf011390-0450-11e5-8e14-c4243fb0614b.png)

**Comment by timvandermeij** [comment]
Confirmed using Windows 7 x64, Firefox 38.0.1 and the latest PDF.js development version. We have seen more of such issues lately, so perhaps it's a duplicate. We need to investigate this more to be sure.

**Comment by SamyCookie** [comment]
Confirmed also in Debian Linux testing x64, Firefox 38.0.1 and the latest PDF.js development version.

**Comment by timvandermeij** [comment]
Possibly related to #5836.
