### ISSUE TITLE
extract validor from pdf.js

### ISSUE THREAD

**Issue by gr2m** [mozilla/pdf.js#6057]
I'm creating a new JavaScript library to generate PDFs right now. I know there are existing ones, but I want to build one anyway, please bear with me.

I'd love to be able to easily validate generated PDFs using pdf.js. It's not really made for that purpose, and I wonder if it would be possible to somehow extract a `pdf-validator` module out of `pdf.js` that could be used on it's own. For example, https://github.com/devongovett/pdfkit/  has not a single test right now, and adding tests by generating PDFs and making sure they are valid would already be worth a lot.

I've asked @jviereck for help, he has send me hear because you're all so nice <3

You can find my current work in progress here: https://github.com/gr2m/node-pdf

```
git clone git@github.com:gr2m/node-pdf.git
cd node-pdf
npm install
npm test
# you'll see an error that PDF.js throws
```

I wonder if we can extract all the validation bits out of PDF.js, as I don't need all the display bits, just the validation :)

**Comment by timvandermeij** [comment]
I'm not quite sure what you are looking for exactly. There is font validation for example, but that it not done in a central place. PDF structure validation is not done centrally either. Validation of annotations is mainly done in https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js. In short, it would be a lot of work to gather everything as there is no such thing as a validation component in PDF.js, but rather bits of the PDF are validated at different stages in the rendering process. The main reason for this is to be able to render as much as possible in case of, for example, a corrupted PDF. I guess you would be able to extract those bits, but it is **a lot** of work and *really* out of scope for the PDF.js project itself unfortunately. I can give you some hints on where to find some validation bits, but it's most likely not everything there is. Your best option would be to ask on the mailing list or IRC if you need more information, as the issue tracker should only be used for bugs in PDF.js.

- Annotations: https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js
- Fonts: https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js
- PDF structure: https://github.com/mozilla/pdf.js/blob/master/src/core/evaluator.js

**Comment by yurydelendik** [comment]
You probably just need src/core/* files (and their dependencies) -- reading and parsing is done there. We are not doing any strict validation since lots of PDFs on web have some issues. As a start you can read how [unit tests](https://github.com/mozilla/pdf.js/tree/master/test/unit) are using classes in the core directory

**Comment by gr2m** [comment]
Bummer, but thanks. Are you maybe aware of another CLI tool that exists for validating PDFs?

**Comment by timvandermeij** [comment]
Personally I'm not aware of any, sorry.
