### ISSUE TITLE
Eliminate CSS "preprocessor"

### ISSUE THREAD

**Issue by mcorb** [mozilla/pdf.js#6058]
Is there any reason why builder.js attempts to remove vendor-prefixed CSS extensions?

The code is deeply flawed and seems to be built on trial-and-error with disregard towards the CSS specification's parsing rules, and it only really removes lines of no-op text.

Firefox will already ignore vendor-prefixed directives so the preprocessor appears to be a redundant diversion of engineering resources that can be avoided.

Limitations in this set of regular expressions are blocking ongoing compatibility work such as #6049

**Comment by Snuffleupagus** [comment]
> Is there any reason why builder.js attempts to remove vendor-prefixed CSS extensions?

Yes, there is. Since the *primary* use case for PDF.js is the PDF viewer included by default in Firefox, we want to be able to remove unnecessary code from the CSS (and also the JavaScript). Apart from avoiding unneeded code in mozilla-central, this also helps us reduce the file size of e.g. `viewer.css` quite a bit.

If, according to the title, the only purpose of this issue is to "remove" the CSS preprocessor, then this issue will most likely be closed as WONTFIX or INVALID.

**Comment by existentialism** [comment]
Howabout using [autoprefixer](https://github.com/postcss/autoprefixer) inside the specific build targets?

**Comment by Snuffleupagus** [comment]
> Howabout using autoprefixer inside the specific build targets?

This was suggested, and rejected, around the time when the current CSS preprocessor was added. Reasons for this was that it would make the development version (i.e. `node make server`) more difficult to use, and also that such preprocessors gives us less control over the resulting output.

**Comment by timvandermeij** [comment]
I think this issue contains a valid point, actually. How about this: we move the vendor-prefixed rules and other compability CSS rules to a new file named `compatibility.css` (just like we already have `compatibility.js`) and include that file in the required builds. Then we should be able to remove the CSS preprocessor. Would there be any problems with that approach?

/cc @yurydelendik because he is the author of the CSS preprocessor.

**Comment by yurydelendik** [comment]
See also #3404

At the moment when decision was made there was no generator that would fit our needed -- probably now there is one. Notice that we preprocess not only for Firefox but for Chromium as well.

Also we chose preprocessor vs generator for development convenience. @timvandermeij so sounds like this issue more than swapping out what's in build step, but changing entire way how development tools are used (e.g. contributors have to build pdf.js before debugging it). Personally I'm fine with that with exception that it shall not be done half-way; now who is willing to update entire infra to remove preprocessors (css, html and js) and replace them with (e.g. autoprefixer and uglfier)? :

**Comment by Snuffleupagus** [comment]
> Would there be any problems with that approach?

Yes; given that different build needs different CSS rules (one example is `fullscreen` rules), having just *one* compatibility CSS file wouldn't work. We would need one for *each* build type, and trying to keep all of that in sync is going to be an absolute nightmare while doing reviews!

**Comment by Snuffleupagus** [comment]
> e.g. contributors have to build pdf.js before debugging it

@yurydelendik Wouldn't that mean that something like e.g. bisecting would become *a lot* more cumbersome (since you'd need to build at each step)? Because that is *one* very important use-case, which the current development process makes very easy.

**Comment by yurydelendik** [comment]
> Wouldn't that mean that something like e.g. bisecting would become a lot more cumbersome (since you'd need to build at each step)?

Correct, every usage of new code will require a build.

**Comment by yurydelendik** [comment]
I guess original question of this issue is answered. Shall we close it as "answered"?

Making decision on preprocessor vs generator might take awhile and out-of-scope of issue tracking. However adding easy fix to #6049 for the preprocessor shall not that much effort as the reporter claimed.

**Comment by mcorb** [comment]
Splitting out compatibility rules to a separate would be even more burdensome than fixing the regex preprocessor, so let's skip that and give @yurydelendik's approach a shot. Thanks for the constructive discussion.

I'll drop by on IRC to discuss another possibility for the CSS at some point, that we've been evaluating for our viewer and which might also work for upstream. I'll file a specific bug report on the preprocessor and close this one.
