### ISSUE TITLE
PDF Search Handling of White Spaces Inconsistent With Adobe Acrobat

### ISSUE THREAD

**Issue by goodnowt** [mozilla/pdf.js#6061]
At Lafayette College's Digital Scholarship Services, we use pdf.js to display various collections in-browser, that our user base then heavily uses to search those PDFs.  Unfortunately, we have found that our OCR has line breaks and carriage returns inserted in cases where there should be spaces, and pdf.js does not know how to compensate for these, and it results in search errors.

However, when we open those same issues in Adobe Acrobat, the in-PDF search offered that actually appears to have an algorithm on the back-end that is able to compensate for these erroneous line breaks and carriage returns generated in the OCR text, and we get a much more streamlined search function out-of-the-box.

Is this is a known issue with pdf.js, and has there been any work done to resolve it?

**Comment by Snuffleupagus** [comment]
@goodnowt As outlined in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, could you please provide access to a PDF file with this behaviour?

**Comment by goodnowt** [comment]
Sure thing, here are two items which both failed on internal searches on the phrase "Neil McElroy":

http://digital.lafayette.edu/collections/alumninewspubs/lafalummag-19980400
http://digital.lafayette.edu/collections/newspaper/19900907

I believe another of the librarians I work with actually managed to put in place a workaround to get these two particular cases working within our site, so it would be best if they are downloaded from those pages for testing purposes.

**Comment by timvandermeij** [comment]
Text selection and search has improved a lot for these PDFs after recent patches. The phrase "Neil McElroy" can now be found in the first PDF. Not in the second PDF, but that is because an additional space is inserted, which is tracked in many other issues about too few/much spaces in the text layer.

Closing as fixed.
