### ISSUE TITLE
font bluring when click on print icon in chrome browser

### ISSUE THREAD

**Issue by ramesh9987** [mozilla/pdf.js#6064]
Hi all,
In below html pdf url. I have got one issue in chrome.
https://github.com/mozilla/pdf.js

i.e : when i downloaded the pdf & given print page then i got perfect font.
When I click on print icon in open pdf url then print page generating with font bluring.
you can test this by using above url.
How can i fix this print icon issue? Please can anyone suggest me the best print pdf choices

**Comment by timvandermeij** [comment]
Which PDF file do you mean exactly? Is it the default Tracemonkey PDF?

**Comment by timvandermeij** [comment]
Closing as incomplete until more information is provided.
