### ISSUE TITLE
Decode 16 bit JPEG 2000 image data from DICOM

### ISSUE THREAD

**Issue by drsganesh** [mozilla/pdf.js#6067]
I am a medical professional & a hobbyist coder.
I recently wrote a very simple DICOM viewer in pure javascript / HTML5, which works entirely on javascript ( chrome 43).

I want to parse a DICOM file with pixelData in 16 bit JPEG 2000 format.
I managed to get the pixelData into arraybuffer. Now want to convert the data into raw RGB (typed array) .

I tried jpx.js without success

Can you help? { parse pixeldata in 16 bit JPEG 2000 format as arraybuffer - In very simple codes}

**Comment by timvandermeij** [comment]
Since this issue is not directly related to PDF.js, I'm closing it as invalid. You could try asking on the mailing list though.

**Comment by yurydelendik** [comment]
Try jpgjs library at https://github.com/notmasteryet/jpgjs - it uses jpx.js file from pdf.js
