### ISSUE TITLE
PDF doesn't render at all (bad XRef entry)

### ISSUE THREAD

**Issue by andrewthecoder** [mozilla/pdf.js#6069]
As I can see from other tickets, this means the PDF is technically "corrupt", but it's generated by TCPDF (http://www.tcpdf.org/) and unfortunately the codebase which generates it can't easily be changed now as it's legacy code.
As such the end result to our users is just that our product (which includes showing reports to the user in PDF format) works great in Chrome and Internet Explorer but is broken in Firefox. Here "broken" means displaying a grey screen and an optional link to download the file, but the user then gets confused as it is saved as "doc.pdf" etc.

Either way if somebody could figure out why this particular one is crashing pdf.js I'd appreciate it - if I'm given specific help I could probably fix it myself and submit a PR, but I don't really know where to start with the PDF spec.

Here's the console log:
```
Error: Invalid XRef stream
pdf.worker.js (line 250)
<System>

XRef_readXRef@resource://pdf.js/build/pdf.worker.js:3683:15
XRef_parse@resource://pdf.js/build/pdf.worker.js:3289:23
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:2484:7
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:2371:7
ensureHelper@resource://pdf.js/build/pdf.worker.js:2000:22
NetworkPdfManager_ensure/<@resource://pdf.js/build/pdf.worker.js:2014:7
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:1994:1
BasePdfManager_ensureDoc@resource://pdf.js/build/pdf.worker.js:1861:14
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:33208:11

pdf.worker.js (line 252)
<System>
Warning: Unsupported feature "unknown"
pdf.worker.js (line 235)
<System>
Warning: Unsupported feature "unknown"
Warning: Indexing all PDF objects
pdf.worker.js (line 235)
<System>
Error: bad XRef entry
pdf.worker.js (line 250)
<System>

XRef_fetchUncompressed@resource://pdf.js/build/pdf.worker.js:3782:9
XRef_fetch@resource://pdf.js/build/pdf.worker.js:3754:21
XRef_fetchIfRef@resource://pdf.js/build/pdf.worker.js:3735:14
Dict_get@resource://pdf.js/build/pdf.worker.js:2639:23
XRef_parse@resource://pdf.js/build/pdf.worker.js:3305:25
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:2484:7
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:2371:7
ensureHelper@resource://pdf.js/build/pdf.worker.js:2000:22
NetworkPdfManager_ensure/<@resource://pdf.js/build/pdf.worker.js:2014:7
NetworkPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:1994:1
BasePdfManager_ensureDoc@resource://pdf.js/build/pdf.worker.js:1861:14
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:33208:11

pdf.worker.js (line 252)
<System>
Warning: Unsupported feature "unknown"
pdf.worker.js (line 235)
<System>
Warning: Unsupported feature "unknown"
An error occurred while loading the PDF.
PDF.js v1.0.1149 (build: bc7a110)
Message: bad XRef entry
```

Thanks in advance.

**Comment by timvandermeij** [comment]
I agree, we need to look into what is causing this as there are multiple open issues for this. Thank you for reporting it!

**Comment by jmiserez** [comment]
@andrewthecoder Just FYI, `mutool` ([project page](http://mupdf.com/), [manpage](http://manpages.ubuntu.com/manpages/trusty/man1/mutool.1.html)) seems to be able to fix your broken PDFs (without printing them). Run `mutool clean doc.pdf output.pdf`, the resulting file renders fine in pdf.js. Of course this is not a permanent solution, and there might be data loss. I'd keep the originals if I were you.

mutool output:
```
$ mutool clean doc.pdf output.pdf
error: cannot recognize version marker
warning: trying to repair broken xref
```

**Comment by andrewthecoder** [comment]
Thanks for the heads-up about a potential workaround @jmiserez, I'll give it a try and see what the output is like.
However we'll still need to make PDF.js work around this particular bad XRef entry, as we can't realistically run every generated PDF through mutool server-side before serving it to the client (well, we might be able to but it would create substantial complications).
However I'm interested in looking into the mutool source to see how they are "fixing" this particular issue and if that may help a fix for PDF.js...

**Comment by websirnik** [comment]
Didn't want to open another issue. I stumbled upon another PDF uploaded by one of our users which shows "bad XRef entry" error:
http://www.dataxu.com/wp-content/uploads/Forrester-Wave-Report-Q4_2011.pdf
I don't know which tool was used to generate the PDF.
