### ISSUE TITLE
All content in White color is rendered in black color and the content in black color is rendered as white color.

### ISSUE THREAD

**Issue by vijith2712** [mozilla/pdf.js#6071]
When I am trying to view a document using PDFJS the content in white color is rendered in black color and the content in black color is rendered as white color.
![using_pdfjs](https://cloud.githubusercontent.com/assets/12690991/7910310/32d77dd6-0871-11e5-965a-db197ee9c0de.png)

![using_other](https://cloud.githubusercontent.com/assets/12690991/7910285/fc319b7c-0870-11e5-91b1-7cd6a14608a5.jpg)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, paying special attention to the *first* paragraph. At the *very least*, you must provide a link to a PDF file that can be used to reproduce this issue!

**Comment by Snuffleupagus** [comment]
Closing as incomplete for now; please provide the information requested above to re-open.

**Comment by vijith2712** [comment]
Jonas,
I have mailed the document to your mail id mentioned, as there is no provision to upload document here.

**Comment by Snuffleupagus** [comment]
https://www.dropbox.com/s/w5cb3li354rtgcb/issue6071.pdf?dl=0
___
@vijith2712 *For future reference, when reporting issues:*
If possible, please upload the PDF file to a file sharing service (e.g. Dropbox, Google Drive, Microsoft OneDrive or similar), and paste a link to the file in the issue, instead of sending it by email to individual contributors/developers.

Sending a PDF file by email should only be considered as last resort for PDF files containing sensitive data, where making the PDF file available through a file sharing service would pose a problem.

**Comment by vijith2712** [comment]
Jonas, 
Any updates on why this issue is happening.

**Comment by timvandermeij** [comment]
The PDF contains a `DeviceGray` image with `DecodeParams`. Perhaps we do not handle those decode parameters correctly? It seems like a color inversion issue.

**Comment by vijith2712** [comment]
Can we expect a fix for this issue in the next release? Can you please provide ETA for this issue?

**Comment by vijith2712** [comment]
Any Update on fix for this issue?

**Comment by timvandermeij** [comment]
When there are updates, we will provide them here. Currently there is no news.

**Comment by THausherr** [comment]
> The PDF contains a DeviceGray image with DecodeParams. Perhaps we do not handle those decode parameters correctly?

I think it's related to the predictor 2. This is related to issue #6289 but different bit size.

**Comment by Snuffleupagus** [comment]
Interestingly enough, if you skip the `bits === 1` code-path in `readBlockTiff`, see [src/core/stream.js#L740-L749](https://github.com/mozilla/pdf.js/blob/6c263c19946af23b723f148d9f05118971e18b36/src/core/stream.js#L740-L749), and instead fallback to default one, see [src/core/stream.js#L758-L783](https://github.com/mozilla/pdf.js/blob/6c263c19946af23b723f148d9f05118971e18b36/src/core/stream.js#L758-L783), the PDF file appears to render correctly. Hence it certainly seems plausible that the code for the `bits === 1` case could be wrong in some edge-cases.

**Comment by mukulmishra18** [comment]
> if you skip the bits === 1 code-path in readBlockTiff, see src/core/stream.js#L740-L749, and instead fallback to the default one, see src/core/stream.js#L758-L783, the PDF file appears to render correctly

@Snuffleupagus, i also reproduced the condition mentioned above, but i am unable to understand what is going on in the code, can you please guide me how can i understand what code does.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7869.
