### ISSUE TITLE
Make it possible to handle links with different URL protocols

### ISSUE THREAD

**Issue by trevordixon** [mozilla/pdf.js#6072]
I've got PDFs with links like "textedit:///tmp/input.ly:4:2:17". This fails the [`isValidUrl` check](https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L290-L311), and the link is ignored. It would be nice to make it possible to do something useful with such strange links.

**Comment by TimothyGu** [comment]
Or at least add an option to disable the valid URL check.

**Comment by timvandermeij** [comment]
Forks can edit or even remove the `isValidUrl` check if need be, but for the main PDF.js library it is needed for security and validation. `textedit` is not a valid protocol and is not handled by PDF.js, so if your forks want to work with that you will have to edit the `isValidUrl` check.

Closing as invalid.
