### ISSUE TITLE
Getting errors compressing pdf.js

### ISSUE THREAD

**Issue by eoctavien** [mozilla/pdf.js#6074]
When trying to minify the pdf.js file with the google closure compiler I get 15 errors (when just removing the white space) and 4 warnings when I choose the simple optimization. This is what it gave me:

Number of errors: 15
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 1925 character 0
    get promise() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2037 character 0
    get numPages() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2044 character 0
    get fingerprint() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2238 character 0
    get pageNumber() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2244 character 0
    get rotate() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2251 character 0
    get ref() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 2258 character 0
    get view() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 3089 character 0
    get promise() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 4616 character 0
    get isFontSubpixelAAEnabled() {
^
JSC_PARSE_ERROR: Parse error. String continuations are not supported in this language mode. at line 5503 character 30
  var smaskVertexShaderCode = '\
                              ^
JSC_PARSE_ERROR: Parse error. String continuations are not supported in this language mode. at line 5518 character 32
  var smaskFragmentShaderCode = '\
                                ^
JSC_PARSE_ERROR: Parse error. String continuations are not supported in this language mode. at line 5652 character 32
  var figuresVertexShaderCode = '\
                                ^
JSC_PARSE_ERROR: Parse error. String continuations are not supported in this language mode. at line 5670 character 34
  var figuresFragmentShaderCode = '\
                                  ^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 5846 character 0
    get isEnabled() {
^
JSC_PARSE_ERROR: Parse error. getters are not supported in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option. at line 6296 character 0
  get loadTestFont() {
^

I tried using this because I thought this was a supported minifier. Is it because I simply copied and pasted or do I have to use the command, if it is the command issue, how to I do this in ASP.NET Webforms? Thank you.

**Comment by yurydelendik** [comment]
`CLOSURE_COMPILER=~/closure-compiler/closure.jar node make minified` works for me. (cc version: v20140625)

Closing as works for me. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md to reopen issue.

**Comment by eoctavien** [comment]
Where do I run that command, inside that script file?
