### ISSUE TITLE
Greyscale scanned pdf not working on safari, pdf.js 1.1.114-dist

### ISSUE THREAD

**Issue by priyesh875** [mozilla/pdf.js#6077]
I scanned same document 2 times, color and greyscale. i upload both files and color document is larger in size still its working properly but same greyscale document is not working its displayed as blank pages. i have both files but i am not able to upload pdf files here.

**Comment by timvandermeij** [comment]
Without the PDF files and more information (errors/warnings in the console, details about your configuration, et cetera), there is unfortunately nothing we can do about this. Please make sure to read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md before submitting an issue. Closing as invalid until more information is provided. You could try making other PDF files without sensitive data.

**Comment by priyesh875** [comment]
By this reply i don't think so you guys want to resolve this issue. I have
windows server from GoDaddy. You can find my both pdf files in attachment.
I scan same document 2 times in canan scanner, one is as colored and one as
greyscale. You can check both files working great firefox or IE but if you
open this in IPad Safari you can see that color document is working but
greyscale is not.

**Comment by timvandermeij** [comment]
We are willing to resolve the issue, but we are not able to if not enough information is provided. Unfortunately GitHub does not support adding attachments via e-mail, so you will have to upload them to a file sharing service like Dropbox or Google Drive.

**Comment by priyesh875** [comment]
You can find both files on below links. let me know if you need any other information. 
IPad, iOs 8.3 
GreyScale : https://www.dropbox.com/s/z55jm9dv7t5w92c/greyscale.PDF?dl=0
Colored : https://www.dropbox.com/s/rrgsgon3anogiqa/color.PDF?dl=0

**Comment by timvandermeij** [comment]
@priyesh875 Are you using the latest version of PDF.js? You can verify by opening both files with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem persists.

**Comment by priyesh875** [comment]
yes, i am using pdf.js 1.1.183 latest version. it still doesn't work.

**Comment by Jesspu** [comment]
I am having the same issue, we have pdf's that are all grayscale except for a blue line at the bottom. The blue line of text is rendered but the rest of the document is not. This is on ios in a angular app using pdf.js the latest stable version. I have also included compatibility.js.

**Comment by priyesh875** [comment]
right now for solution we convert over pdf at uploading time with ImageMagick, its open source converter. We are using this command "convert -density 175 -compress jpeg -quality 20 abc.pdf abc_result.pdf" to convert over pdfs and its working nice but its not proper solution. i am also waiting for reply from pdf.js developers.

**Comment by Jesspu** [comment]
thanks for the info.

**Comment by timvandermeij** [comment]
I have looked a bit more into the shared PDF files. The grayscale version contains an image that is almost two times larger than the color version. It is known that resource-constrained devices currently have issues rendering these large images. For web usage, it is better to reduce the size of those images. Marking as performance issue.

**Comment by cetinsert** [comment]
Does anyone still have the files here? None of the links work.

**Comment by timvandermeij** [comment]
Aside from the links not working anymore, this is also a very old issue that might well be resolved in the latest version already due to all performance improvements in the meantime. Closing for now; please attach the PDF on GitHub if there are still issues (to avoid the file getting lost).
