### ISSUE TITLE
Font rendered error

### ISSUE THREAD

**Issue by futurist** [mozilla/pdf.js#6092]
I have a test PDF file, as below:

http://1111hui.com/pdf/font.pdf

But font rendered error on Windows XP and Windows 2003, please see:
http://1111hui.com/pdf/web/viewer.html?file=../font.pdf

![font pdf](https://cloud.githubusercontent.com/assets/159167/8028406/96a138a2-0ddf-11e5-9a4b-8f4810b4a049.png)

Like line height too small to display. Also I have CMaps of Chinese fonts installed.

In Mac OS X I've tested with no problem.

**Comment by timvandermeij** [comment]
Works for me on Windows too. Are you using the latest version of PDF.js? Try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem persists. If so, it is most likely a driver issue, so you could try updating those too.

**Comment by futurist** [comment]
![2015-06-08 9 54 38](https://cloud.githubusercontent.com/assets/159167/8036242/2e897b5e-0e29-11e5-8f4f-6f3907a90e5c.png)

Same problem, in Windows + Chrome, using open button from lastest version.

**Comment by brianincd** [comment]
Hi, have you sovled this issue？

**Comment by timvandermeij** [comment]
The PDF file is no longer available, both here and in the Internet Archive. Moreover, this is most likely a driver issue, so if this still happens please make sure to update all graphics drivers (moreover, Windows XP and Windows Server 2003 *really* shouldn't be used anymore and we do not support that).
