### ISSUE TITLE
Black squares instead of letters on Firefox for Android

### ISSUE THREAD

**Issue by cis-oip** [mozilla/pdf.js#6094]
PDF.js version 1.1.3 (stable)
Firefox version 38.0.5 (for Android)
Hardware: Huawei MediaPad 10 Link, Android 4.0.4

When I try to open pdf file with external PDF.js viewer I see black squares instead of letters.
Screenshot: http://higgs.rghost.ru/89wVw98bT/image.png

But in Chrome, Opera and other browsers it works perfect. It works perfect with Firefox on Desktop PC.

Is it problem with Firefox or PDF.js? How to avoid that bug and make Firefox to render text normally?

**Comment by timvandermeij** [comment]
Almost sounds like an upstream issue to me. This has to be triaged.

**Comment by timvandermeij** [comment]
The screenshot is gone and no document has been provided for reproducing the issue. I have seen no such problems on Android before. Closing as incomplete until more information is provided.
