### ISSUE TITLE
Rendering error, text not visible

### ISSUE THREAD

**Issue by jethrogb** [mozilla/pdf.js#6096]
http://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf

Firefox 38.0 on Ubuntu 14.04:

![firefox](https://cloud.githubusercontent.com/assets/1132307/8043286/ccca9c30-0dd9-11e5-9a79-5bd9250cbe1a.png)

Adobe Reader 9.5.5 on Ubuntu 14.04:

![adobe](https://cloud.githubusercontent.com/assets/1132307/8043288/cf113288-0dd9-11e5-8179-7ed855a4ea9a.png)

**Comment by timvandermeij** [comment]
Confirmed on Arch Linux with Firefox 38.0.5 and the latest development version of PDF.js.

**Comment by timvandermeij** [comment]
Closing as fixed (works now on Arch Linux with Firefox 42).

**Comment by SamyCookie** [comment]
Fixed for me too with iceweasel 42 on Debian testing 64 (stretch)
