### ISSUE TITLE
Printing doesn't work on Ubuntu & Chrome 

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6097]
Using demo viewer and the default pdf file, when print, most of the pages are blank (only page 2, 11 and 13 are not blank). Also happens for other pdf files.

OS: Ubuntu 14.04.2 LTS
Browser:  Chrome 43.0.2357.81 (64-bit)

Firefox works fine. Chrome on OS X also working.

The only thing installed is Chrome.

**Comment by timvandermeij** [comment]
Are you using the latest version of PDF.js? Please try with https://mozilla.github.io/pdf.js/web/viewer.html and see if the problem remains.

**Comment by xlc** [comment]
@timvandermeij Yes. Just tried again and it still doesn't work.

**Comment by Rob--W** [comment]
This is a known bug in Chrome, and the latest version of Chrome (43.0.2357.124) contains the fix. See #6084 and https://github.com/mozilla/pdf.js/issues/6084#issuecomment-109565842 for more information.
