### ISSUE TITLE
table format in pdf is not rendered properly in browser

### ISSUE THREAD

**Issue by selva1980** [mozilla/pdf.js#6100]
We tried to render a pdf using pdf.js library latest version. This pdf contains some tables with rows and columns. The partition lines of rows and columns did not appear as smooth as the native pdf reader. I have attached the screenshots for your reference
![pdf-rendering-issues-with-tablesformat](https://cloud.githubusercontent.com/assets/12811884/8057563/f9fb627e-0ecf-11e5-9b67-527dedb0441c.jpg)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, paying special attention to the *first* paragraph. I'm quoting the relevant section:
> [...] and provide more details about the issue: **link to the PDF, [...], browser version, operating system, PDF.js version and JavaScript console warning/error messages**. Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by timvandermeij** [comment]
Closing as incomplete. Please provide the information requested above to reopen.
