### ISSUE TITLE
Page Orientaion will not print as in actual pdf file using chrome browser

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6107]
i have a pdf wich contains scaned documents with different page size and orientation and i want to print it as it is. But the chrome or any browser does not support it. They print pdf as default setting in chrome preview or default Printer.

**Comment by ArjunPatil** [comment]
if i open a pdf file in Chrome directly and takes it print. then chrome prints it correcly as same as in actual pdf with mixed orientation(landscape or portrait ) or page size (hand bill, A4, letter pad, visiting card size)


![snapcrab_noname_2015-6-12_10-42-42_no-00](https://cloud.githubusercontent.com/assets/12855547/8123951/55dcfb26-10f0-11e5-8b29-b91b12a56432.png)

**Comment by timvandermeij** [comment]
Probably #6103 will help.

**Comment by ArjunPatil** [comment]
My pdf file having both landscape and portrait scanned pages in it. 
in that case all the pages are printed on A4 portrait pages and Landscape pages get streached verticaly and get compressed horizontally to map Portrait page.

but when i print same file from chrome or adobe reader all the pages printed as per their orintation.

**Comment by ArjunPatil** [comment]
Hi timvandermeij 

thanks for helping me to resolve this issue.
