### ISSUE TITLE
I use the pdf.js plugin in the project, it will clear my website cookie information, how I want to operate

### ISSUE THREAD

**Issue by kugouming** [mozilla/pdf.js#6118]
When I use the pdf.js plugin in the project, it will clear the cookie information from my website, and how do I do it?
Users at the site of the original login, then refresh the page, is out of the state, how should I do?

**Comment by timvandermeij** [comment]
This is not caused by PDF.js as PDF.js does not clear or overwrite cookies. It's most likely a problem with your own implementation. Closing as invalid unless a working example demonstrating the problem can be put online.
