### ISSUE TITLE
getAll is not a function Lab ColorSpace

### ISSUE THREAD

**Issue by jcbvm** [mozilla/pdf.js#6124]
I recently have issue with some PDF's with version 1.1.3. I'm getting an `Object doesn't support property or method 'getAll'`. It is coming from the function `ColorSpace.parseToIR` in `pdf.worker.js`. I see a similar issue #5747, only this issue is with CalGray mode, my error is coming from the Lab mode.

If I look into the fix of issue #5747, I see the following change:
     
     - params = cs[1].getAll();
     + params = xref.fetchIfRef(cs[1]).getAll();

For the Lab mode params is still defined by just doing `getAll`. If I change that part to the part shown above, everything is working fine.

**Comment by Snuffleupagus** [comment]
Thanks for the report; however this was fixed (two days ago) by PR #6112, hence I'm closing this issue.
