### ISSUE TITLE
How to resize the pdf chunk fetch size from 64KB to  200KB in pdf.js

### ISSUE THREAD

**Issue by itsursujit** [mozilla/pdf.js#6133]
Sir,
How can I change the chunk fetch size, default its 64KB. And How can I check if the PDF has been loaded or not? Is there any minified version of pdf.js, pdf.worker.js and viewer.js with progressive loading enabled?

**Comment by Snuffleupagus** [comment]
> How can I change the chunk fetch size, default its 64KB.

You'll have to edit https://github.com/mozilla/pdf.js/blob/master/src/core/pdf_manager.js#L23, and then rebuild PDF.js yourself.

> And How can I check if the PDF has been loaded or not?

*This question is difficult to answer without more information, but the following is some general advise:*
If you're using the default viewer you could e.g. listen for the `documentload` event, which is fired when the entire PDF file has been loaded, see https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L789.
You could also listen for e.g. the `pagesinit` event, which is fired as soon as the first page of the document has been loaded, see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L310.

> Is there any minified version of pdf.js, pdf.worker.js and viewer.js with progressive loading enabled?

There's an experimental `node make minified` command available, see https://github.com/mozilla/pdf.js/blob/master/make.js#L626. However there's no official support for it yet, nor are there any minified builds available (from us) at this time.

Closing as answered.
