### ISSUE TITLE
Support for Fenix :) 

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla/pdf.js#6136]
Can you add support of pdf.js for Android ? Now we are obligated to use proprietary software instead :(
I'm very sorry for my very bad english. 
Thanks =]

**Comment by timvandermeij** [comment]
We are indeed planning to make PDF.js work on Firefox for Android too, with a modified viewer that will be easier to use on mobile devices. There is also https://bugzilla.mozilla.org/show_bug.cgi?id=938235 containing work for this.

**Comment by LifeIsStrange** [comment]
Oh I'm sorry for not having informed before, there is an extension that implements pdf.js for Android (https://addons.mozilla.org/fr/android/addon/pdfjs/?src=search) but it's expérimental and not working with my oneplus one (cyanogenmod 12S)  on all m'y Firefox (38.0.5, 39,40 and 41) But it is not urgent ! 

Also, it's m'y first time with github  :m, I must close the issue ? (I don't know how the issue system work, I'm very sorry for take your precious time !)

**Comment by timvandermeij** [comment]
We can leave this open for tracking purposes; thanks!

**Comment by M-Reimer** [comment]
FYI: https://addons.mozilla.org/de/android/addon/android-pdf-js/
This is actually a port of the Chrome extension back to Firefox.
I've hosted my version in a separate GIT repo:
https://github.com/M-Reimer/android-pdf-js/
It has some problems but it's actually better than nothing.

**Comment by 532910** [comment]
Thank you!

**Comment by KrasnayaPloshchad** [comment]
Yeah, so is it possible to add this project into [wiki page](https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications)?

**Comment by 532910** [comment]
Fennec development is stopped due to Fenix.  This issue should be renamed or closed and a new one opened.

**Comment by Snuffleupagus** [comment]
Given that this is now being tracked in the Fenix repository, let's close this one for now since it's likely to e.g. require a special viewer that would (quite probably) live in the Fenix code-base rather than directly in the PDF.js library.
