### ISSUE TITLE
Printing in IE11 not working

### ISSUE THREAD

**Issue by chrisdde** [mozilla/pdf.js#6152]
Hi,

we are using PDF.js and the printing seems not to work in IE11. Instead of the PDF the whole HTML page is printed. Do you have an suggestion how to fix this?

Thanks and Regards,
Chris

**Comment by FesterCluck** [comment]
This is a duplicate being addressed in https://github.com/mozilla/pdf.js/issues/3983

**Comment by chrisdde** [comment]
I solved my issue. Intead of embed i use an iframe. then it works better. But I now have the same issued like in #3983

**Comment by timvandermeij** [comment]
Closing this as fixed and moving further tracking to #3983.
