### ISSUE TITLE
Overlapped characters

### ISSUE THREAD

**Issue by marcosps** [mozilla/pdf.js#6156]
Firefox 38.0.5, pdf.js 1.1.228, Fedora 22

This is the pdf
http://ftp.blackbox.com/manuals/L/ls1001a-ls1048a%20v214%20ACS.pdf

Evinces shows correctly, just pdf.js shows some titles overlapped.

Evince:
![captura de tela de 2015-06-30 13-05-16](https://cloud.githubusercontent.com/assets/1039418/8435628/d21b3892-1f28-11e5-922f-0c5bc254c5af.png)

pdf.js:
![captura de tela de 2015-06-30 13-05-06](https://cloud.githubusercontent.com/assets/1039418/8435649/e68ac61c-1f28-11e5-8cba-36f96add1eaa.png)

**Comment by brendandahl** [comment]
Looks okay for me in PDF.js: 1.3.78. Are you still having issues?
https://www.dropbox.com/s/zvw3olj7z5yzjv6/Screenshot%202015-12-15%2011.40.38.png?dl=0

**Comment by timvandermeij** [comment]
Looks good for me too on Windows 10 x64 with the latest PDF.js development version and Firefox 42.0.

**Comment by marcosps** [comment]
The problem still existis for me with Firefox 42.0 and pdf.js 1.3.88, on Fedora 23

**Comment by timvandermeij** [comment]
Thank you, labeling this as Linux-only for now.

**Comment by SamyCookie** [comment]
Confirmed that issue too on my Linux Debian 64 stretch testing with Firefox 42 and embedded pdf.js version.

**Comment by SamyCookie** [comment]
Still here with Linux Debian 64 stretch testing with Firefox 48.0 and embedded pdf.js version.

**Comment by timvandermeij** [comment]
Fixed in the most recent version. This now renders exactly the same as Evince for me using Arch Linux and Firefox 61.0.2.
