### ISSUE TITLE
Progress bar 

### ISSUE THREAD

**Issue by Darex1991** [mozilla/pdf.js#6164]
Hello, I search, but I don't found example.. How implement progress bar loading pdf. We use pdf like this:
```
.pdf-viewer
  .pdf-viewer__canvas
    canvas#pdf-canvas data-url = "#{detail.asset.url}"

  .pdf-viewer__navigation
    button.btn--primary--border.btn--sm#prev= t('education.groups.show.previous_page')

    .pdf-viewer__pages
      .pdf-viewer__page-num#page_num
      .pdf-viewer__separator
        |/
      .pdf-viewer__page-count#page_count

    button.btn--primary--border.btn--sm#next= t('education.groups.show.next_page')

script src = '/assets/pdf.js'
script src = '/assets/pdf.worker.js'

coffee:
  $(document).on 'ready', ->
    if $('canvas#pdf-canavas')
      window.renderPdf()
```
I try this solution:
https://groups.google.com/forum/#!topic/mozilla.dev.pdf-js/kRYEDyC2wmA
And when i past 
```
PDFJS.getDocument(doc,null,null,function(obj){
  var pc = (obj.loaded/obj.total).toFixed(2); // sets the percentage of progress
  console.log(pc); // example of a function that updates and renders a progress bar
});
```
in pdf.js, after code of this plugin.
But i got error in console log "doc is not defined". What I doing wrong..?

**Comment by timvandermeij** [comment]
Just do what the `viewer.js` code is doing to. For instance, we have https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L382-L386

This issue tracker is intended for bugs in PDF.js. For custom solutions, please use the mailing list. Closing as answered.

**Comment by Darex1991** [comment]
Tnx for respond. I need include viewer.js or i only need lines with 'loadingBar'?
Ie. 
https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L382-L386
https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L692-L719
https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L731-L734
https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L774
