### ISSUE TITLE
Bad render of sec-guide-to-proxy-brochures

### ISSUE THREAD

**Issue by wfaulk** [mozilla/pdf.js#6165]
https://www.sec.gov/investor/pubs/sec-guide-to-proxy-brochures.pdf

The first page shows _only_ a blue rectangle at the top, the image in the center, and the footer.  The rest of the pages seem to render fine.  Here's a screenshot:

![screen shot 2015-07-01 at 11 36 41 am](https://cloud.githubusercontent.com/assets/205470/8458548/b66f6f7e-1fe5-11e5-958a-8dc0cda0bcdd.png)

I see the same results whether using the version of pdf.js that is included in Firefox 38.0.5 or version 1.1.233 installed as an add-on.

**Comment by griffinmyers** [comment]
Well say! Not the first time an SEC form as had trouble.... https://github.com/mozilla/pdf.js/issues/6151

**Comment by Snuffleupagus** [comment]
This is a regression from PR #4161.

**Comment by Snuffleupagus** [comment]
This issue could possibly be related to https://bugzilla.mozilla.org/show_bug.cgi?id=852992.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7176.
