### ISSUE TITLE
Warning: Unhandled rejection: Error: Access is denied

### ISSUE THREAD

**Issue by cdesewell** [mozilla/pdf.js#6168]
I receive this error when trying to view the following: http://www.publishers.org.uk/_resources/assets/attachment/full/0/2091.pdf
in IE9, I have pdf.compatibility.js loaded so I don't believe that it's related to type arrays. 
Has anybody encountered this before/understand why it occurs?

Edit: I'm using the following version
PDFJS.version = '1.0.1040';
PDFJS.build = '997096f';
Thanks

**Comment by timvandermeij** [comment]
It renders fine for me with https://mozilla.github.io/pdf.js/web/viewer.html. Could you try upgrading to the latest release?

**Comment by cdesewell** [comment]
Thanks for your reply timvandermeij, this error occurs because:
"You cannot load PDF files from another domain (cross-origin) in Internet Explorer, because the PDF is fetched using XMLHttpRequest and Internet Explorer 9 does not support CORS (Cross-Origin Resource Sharing). CORS was introduced in Internet Explorer 10.

You could work around this issue by loading the PDF from the same origin. Download the file to your own server first by using a back-end proxy on your server, then load the PDF from there." - Blaise

To solve this I now proxy my pdf files through my web server.
