### ISSUE TITLE
PDF is missing background & has extra artefacts

### ISSUE THREAD

**Issue by websirnik** [mozilla/pdf.js#6183]
I have a PDF doc(not created by us) that has a major rendering issues.
Here is the link to the doc:
http://files.shareholder.com/downloads/AMDA-MMXS5/0x0x827039/370849E8-1114-474D-963D-74CE277CA3B6/TRIP_1Q15_Investor_Presentation_v3.pdf

Tested:
- Chrome 45.0.2448.0 canary (64-bit)
- Firefox 39.0.0
- PDFJS.version = '1.1.266';
- PDFJS.build = 'eb2ad11';

![screen shot 2015-07-07 at 11 39 54](https://cloud.githubusercontent.com/assets/282871/8544402/ee681776-249c-11e5-8a02-400fb4407beb.png)

**Comment by THausherr** [comment]
This is a shading type 4 (Gouraud shading), see #6283.

**Comment by timvandermeij** [comment]
Renderig has improved slightly with the green shadding pattern now largely visible. There are still performance issues though and the shading does not extend to the full page yet.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.9.142` in Firefox Nightly 90 (tested with a local copy of the document, since the link above is dead).
