### ISSUE TITLE
Remove PDF cache history in PDF.JS

### ISSUE THREAD

**Issue by itsursujit** [mozilla/pdf.js#6185]
Sir,
We are working on e-library where pdf.js is used to load the PDF files chunk by chunk. The file size of PDF is normally 16MB. AT first load of PDF.JS(disabling cache on browser), the pdf is downloaded in chunk. But as I refresh the page(withour disabling chache on browser), the PDF.Js downloads whole PDF instead of chunk. 
For reference,
Browsing pdf with (cache disable):
![working snap](https://cloud.githubusercontent.com/assets/4959215/8565368/0cc19cb4-2575-11e5-9d85-a347aaa6823f.png)

But when the same PDF is stopped in the middle and reloaded again then, whole pdf is downloaded as:
![not working snap](https://cloud.githubusercontent.com/assets/4959215/8565441/b084e09a-2575-11e5-927b-59ca45e502d0.png)

How can I make PDF.JS load the PDF file downloading chunk-by chunk even if I refresh the page multiple times?

**Comment by itsursujit** [comment]
Is there any server-side configuration required to resolve this issue? It would be helpful enough if one could provide the necessary configurations on: SERVER or CLIENT so that the PDF would be loaded same as like as mozilla hosted PDF.JS( Every request is made with 206 Partial Content).

**Comment by yurydelendik** [comment]
> Is there any server-side configuration required to resolve this issue?

Yes, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ for solution. PDF.js is using browser's XHR and has no direct control over request caching. Closing as answered.

**Comment by ctnitchie** [comment]
One way to disable caching client-side is to add a random or timestamp-based parameter to the end of the URL, e.g. `viewer.html?file=some.pdf&_=someRandomNumberOrCurrentDatetime`. This will cause the browser's cache to be bypassed, because the URL is always different.
