### ISSUE TITLE
Highlighting obscures text in IE11

### ISSUE THREAD

**Issue by ryanpf** [mozilla/pdf.js#6202]
The highlighted text is being covered by the yellow highlighting. Works as expected in chrome, tested in v1.1.288 and v1.1.3. (https://mozilla.github.io/pdf.js/web/viewer.html)

File: (https://drive.google.com/file/d/0B6xJdPUaaUwZaXBONExUbExKcUE/view?usp=sharing)

![image](https://cloud.githubusercontent.com/assets/2955908/8654381/89ce0052-294f-11e5-986f-3818d5ee0bd2.png)

**Comment by Snuffleupagus** [comment]
This might be a duplicate of issue #5264.

**Comment by Snuffleupagus** [comment]
Closing as duplicate of issue #5264.
