### ISSUE TITLE
Image doesn't draw correctly and hangs page rendering on ARM IE11

### ISSUE THREAD

**Issue by bdares** [mozilla/pdf.js#6203]
Sample PDF: https://s3.amazonaws.com/uploads.hipchat.com/105189/1330840/XyW0rDHFCOyK0hp/broken_image_win_arm_ie11.pdf

There is an image in the attached file that isn't drawing correctly in **IE11** on a **Surface RT (Windows ARM) device** running **Windows RT 8.1** when running the PDFjs demo (https://mozilla.github.io/pdf.js/web/viewer.html).  This image includes the string attaching the boy's toe to the pencil, as well as the lines on the paper that the boy is writing on.

When opened in the demo reader, the page is partially drawn, with a spinner overlaid forever.

The same PDF renders correctly in IE11 on a Surface Pro 2 device.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
