### ISSUE TITLE
Internal hyperlinks don't work in 2011 IRS 1040 tax form

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6204]
The 2011 version of the [IRS 1040 tax form pdf](http://www.irs.gov/pub/irs-prior/i1040gi--2011.pdf) has an index on the second to last page (page 99). Each page number on the index is an internal link that jumps to the relevant page on the PDF. When viewed in Adobe Reader and the default Chrome PDF reader, those internal links work properly. In PDF.js (and in Firefox), those internal hyperlinks do not work.

The only unusual thing I see about the PDF was that the PDF Producer is set to "Adobe PDF Library 5.0.2", which was released 10 years before  in 2001 (that's the speed of government for you).

**Comment by timvandermeij** [comment]
There is probably an issue with parsing the named destinations. I don't think this is related to the LinkAnnotation.
