### ISSUE TITLE
Funky font rendering when rendering multiple different PDFs

### ISSUE THREAD

**Issue by throwaway713** [mozilla/pdf.js#6205]
### Description
PDF.js renders font inconsistently and incorrectly when rendering multiple PDFs. Issue does not always appear, and never seems to appear when only one PDF document is being rendered. Issue does not appear to be tied to any specific browser or operating system (see browsers tested below).

### Screenshots (Expected and Actual)
![Expected Result](https://cloud.githubusercontent.com/assets/13324662/8664964/02d38dc0-2a11-11e5-83e2-019fa611aab9.png)
![Actual Result](https://cloud.githubusercontent.com/assets/13324662/8664901/4d8d7d68-2a10-11e5-9bd7-301dcdc7d461.png)

![Expected Result](https://cloud.githubusercontent.com/assets/13324662/8664965/02d69768-2a11-11e5-878e-037796762eb6.png)
![Actual Result](https://cloud.githubusercontent.com/assets/13324662/8664900/4d875df2-2a10-11e5-8064-2aa659c7eabb.png)

![Expected Result](https://cloud.githubusercontent.com/assets/13324662/8664966/02da5ace-2a11-11e5-985e-12792e1a75dc.png)
![Actual Result](https://cloud.githubusercontent.com/assets/13324662/8664902/4d916ae0-2a10-11e5-8086-481a0df1de29.png)

### PDF.js Version
Both stable (v1.1.114) and beta (1.1.125) from https://mozilla.github.io/pdf.js/getting_started/#download

### Browsers Tested
* Firefox 35.0.1 on Ubuntu 14.04 LTS
* Firefox Dev Ed 41.0a2 (2015-07-12) on Ubuntu 14.04 LTS
* Chrome 43.0.2357.81 (64-bit) on Ubuntu 14.04 LTS
* IE 11.0.9600.17843 on Windows 7 Build 7601

### Code Used
    <body>
    <script src="pdf.js"></script>
    <script>

      function tryPDF(filename) {
        return PDFJS.getDocument(filename)
          .then(function(pdf) { return pdf.getPage(1); })
          .then(function(page) {
            var c = document.createElement('canvas');
            var v = page.getViewport(1.2);
            c.width = v.width;
            c.height = v.height;
            document.body.appendChild(c);
            return page.render({
              canvasContext: c.getContext('2d'),
              viewport: v,
            });
          });
      }

      Promise.all([
        tryPDF('compressed.tracemonkey-pldi-09.pdf'),
        tryPDF('pdf.pdf'),
        tryPDF('random.pdf'),
      ])
        .then(function() { console.log('done'); })
        .catch(console.error.bind(console));

    </script>
    </body>

### PDFs used
http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf
http://www.pdf995.com/samples/pdf.pdf
https://www.mathworks.com/moler/random.pdf

**Comment by Rob--W** [comment]
Thanks for the detailed report. I've reproduced the issue and created a unit test. I'll follow up later with a fix.

**Comment by Snuffleupagus** [comment]
Is this issue perhaps related to e.g. #5148, #5984, and #5992?

**Comment by throwaway713** [comment]
Ah yes, it does seem to be the same bug as #5148. Applying the fix (using random numbers) does indeed solve the issue, although not ideal. I hope a better fix could be integrated in future versions. Thank you.
