### ISSUE TITLE
Embedding into webpage

### ISSUE THREAD

**Issue by frederikbosch** [mozilla/pdf.js#6212]
Because I want to control how a pdf open in a specific webpage, I am using pdf.js (pdf.js dist combined version 1.1.299). However, I have troubles opening some files. For those files I have the same log messages.

For Firefox it says.
`"Warning: Unsupported feature "font""`
`"Warning: Error during font loading: glyphName is undefined"`

Whereas Chrome says.
`Refused to get unsafe header "Accept-Ranges"`
`Warning: Unsupported feature "font"`
`Warning: Error during font loading: Cannot read property '0' of undefined`

Since all the documents are client documents, I cannot link/upload them. But my general feeling that my setup of PDF JS is incorrectly. The pdf is rendering correctly when I access the PDF normally with the Firefox (which uses PDF JS natively, right?). So it must be in my setup on the library. Please find some code below (it is an [EmberJS](http://emberjs.com/) component).

```js
App.PdfViewerComponent = Ember.Component.extend({

  classNames: ['overlay', 'pdf'],

  disableWorker : function () {
    PDFJS.disableWorker = true;
  }.on('init'),

  renderPdf : function () {
    var href = settings.host + '/stream/pdf?url=' + encodeURIComponent(this.get('href'));
    var $container = this.$();
    var $canvas = this.$('canvas');
    var canvas = $canvas.get(0);

    $container.append($canvas);
    $container.addClass('loading');

    var self = this;
    PDFJS.getDocument(href).then(function (pdfDoc) {
      self.set('document', pdfDoc);
      self.set('page', 1);
      self.renderPdfPage(canvas);
    });
  }.on('didInsertElement'),

  renderPdfPage : function (canvas) {
    var $container = this.$();
    var pdfDoc = this.get('document');
    var page = this.get('page');

    $container.addClass('loading');

    pdfDoc.getPage(page).then(function (page) {
      var viewport = page.getViewport(1.5);
      var context = canvas.getContext('2d');

      canvas.height = viewport.height;
      canvas.width = viewport.width;

      $container.removeClass('loading');

      page.render({
        canvasContext: context,
        viewport: viewport
      });
    });
  }

});
```

**Comment by timvandermeij** [comment]
If you can open the files correctly with https://mozilla.github.io/pdf.js/web/viewer.html (using the Open File button in the toolbar), then the PDFs are fine and it is indeed your setup. Are you using the latest version of PDF.js (master branch here or https://github.com/mozilla/pdfjs-dist)?

**Comment by timvandermeij** [comment]
(By the way, you might also want to use the web components at https://github.com/mozilla/pdf.js/tree/master/examples/components for your implementation. It allows you to set up a minimal viewer with just a few files of code.)

**Comment by frederikbosch** [comment]
@timvandermeij I am using the latest version of PDF JS (1.1.299, [combined file](https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.combined.js)). Yes, opening in the [demo viewer](https://mozilla.github.io/pdf.js/web/viewer.html) is successful.

The problem is: some files are opened correctly, some are not. Could it be the response from the server then?

**Comment by timvandermeij** [comment]
Does it only happen with the client PDF files or with any other PDF file too? It's hard to tell what is going on without a working example unfortunately. Perhaps you can set up your implementation on a site that you can share with us so we can test with it?

**Comment by frederikbosch** [comment]
@timvandermeij Maybe I wrongly assumed that pdf.combined.js is all I needed. Because, that is what I have now: pdf.combined.js + my ember component. I did not include compatiblity.js, which is inserted in [the component example](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.html) you sent me.

In the same example there is also something with [textLayerFactory and annotationsLayerFactory](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js). Both are not in my Ember component.

**Comment by frederikbosch** [comment]
@timvandermeij I have it across multiple documents (not only the client one), but not all documents. It is all text related though, as the errors are also telling me.

**Comment by timvandermeij** [comment]
`compatibility.js` only provides polyfills for missing features in browsers like IE, so it is not a mandatory component. The text layer factory takes care of rendering the text layer, which is needed for text selection in the viewer. The annotation layer factory provides a component such that annotations can be rendered in the viewer (such as links or a text dialog that can be opened on click). For basic rendering of the page, though, none of those are mandatory.

I would advise testing the components example as provided (without EmberJS) to see if that does work or if the errors are there too. If that is working, integrate that into the EmbedJS component and see if it keeps working.

Maybe others here have more ideas?

**Comment by frederikbosch** [comment]
@timvandermeij So text layer factory only facilitates accessibility of the page? The basic components do not seems the work either, same errors, in my example. But I did not test it in isolation (without Ember JS). I will do that first, and then come back here.

**Comment by frederikbosch** [comment]
@timvandermeij In isolation it works. What could be wrong here? I will find out! Will let you know.

**Comment by frederikbosch** [comment]
@timvandermeij It is very specifically related to EmberJS. I have no clue why these to libraries fail to cooperatie. Eventually I managed to let the component use an iframe, which on its turn is a isolated pdf.js page. I will close this issue, because an iframe is a valid workaround. Maybe that I will have a deeper look in the future, and find out why it fails. Thanks for your help!

**Comment by timvandermeij** [comment]
@frederikbosch You're welcome, and if there is anything that needs to be done on the PDF.js side to make working with libraries like EmberJS easier, feel free to let us know.

**Comment by frederikbosch** [comment]
@timvandermeij Actually, implementation was great. Too bad that something goes wrong for some documents.
