### ISSUE TITLE
Can't display plugin with node-webkit

### ISSUE THREAD

**Issue by CyberianIce** [mozilla/pdf.js#6213]
PDF.js wont display PDF content when used with node-webkit (nw.js), only interface is shown.

**Comment by timvandermeij** [comment]
We really need more information here. Which version of PDF.js is used? Are there errors or warnings in the console? Is it specific for a PDF file or does it happen with any PDF file? Could you share a minimal example or a PDF file that is failing?

**Comment by CyberianIce** [comment]
In my projects, I am using PDF.js version 0.8.0 and nw.js version 0.12.2, but other PDF.js versions also won't work when viewed with nw.js. I thought problem was in nw.js but other PDF/document viewers works without problem (i.e viewer.js). There is no errors in console log, just toolbar and empty space, no even loading slider animation, preview panel button is unresponsive. There is no problem with specific PDF document as such. Afterwards I tried newest nw.js (0.13.0 alpha) and finally made everything works, which may indicate that problem was in nw.js after all. You may close this thread now and I will investigate further, maybe even consult candy-pdf package maintainer for help.

**Comment by timvandermeij** [comment]
Yes, if it does work with the most recent nw.js and PDF.js, then it is likely either a problem with older versions of nw.js. Closing as fixed as this does not seem to be a problem with PDF.js.
