### ISSUE TITLE
centralizing my footer, how do i do it?

### ISSUE THREAD

**Issue by shaunstanislaus** [mozilla/pdf.js#6225]
below is a screenshot of the footer appearing to be marginLeft, how do i centralize it?
```javascript
  // add footer
  if (invoice.invoice_footer) {
      doc.setFontType('normal');
      doc.setFontSize('8');
      SetPdfColor(invoice.invoice_design_id == 2 || invoice.invoice_design_id == 3 ? 'White' : 'Black', doc);
      var top = doc.internal.pageSize.height - layout.marginLeft;
      if (!invoice.is_pro) top -= 25;
      var footer = doc.splitTextToSize(processVariables(invoice.invoice_footer), 500);
      var numLines = footer.length - 1;
      doc.text(layout.marginLeft, top - (numLines * 8), footer);
  }

  return doc;
  }

```
<img width="1440" alt="screen-shot-2015-07-17-13-29-09" src="https://cloud.githubusercontent.com/assets/1703530/8741569/a7202f9a-2c8d-11e5-8ba3-c11a7bd3d575.png">

**Comment by Rob--W** [comment]
As I said on IRC, what you're using is not this PDF.js library (which is a PDF viewer, not a PDF creator). The API of your snippet looks like jsPDF, see https://github.com/MrRio/jsPDF.
