### ISSUE TITLE
Reserved word 'char' is used as variable in processBinaryCMap() in cmap.js

### ISSUE THREAD

**Issue by 13xforever** [mozilla/pdf.js#6228]
This is an error in strict mode, and so [this variable](/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/src/core/cmap.js#L551) should be renamed.

**Comment by timvandermeij** [comment]
Since `node make lint` covers the entire `src` directory as far as I know, why does lint not complain about this? Anyway, I'm fine with changing the name, I'm just wondering why lint is not complaining about this.

**Comment by timvandermeij** [comment]
Probably lint is not influenced by strict mode. If someone is willing to make a PR to rename this variable, I'm fine with it.

**Comment by Snuffleupagus** [comment]
Isn't this identical to issue #4547, which we closed as WONTFIX.

**Comment by timvandermeij** [comment]
You are right. In fact, that issue contains some valid arguments about why this should not be a problem and most tools have been fixed to address that bug / comply to the new standard. Since the developers explicitly closed that issue as won't-fix, I'm doing the same here.
