### ISSUE TITLE
Default System Menu Font

### ISSUE THREAD

**Issue by kilgor270** [mozilla/pdf.js#6229]
Hello,
Newbie here:)
How do I select the system font used for the PDF.js menus? I have it running on two different Mac OS. Maverick and Yosemite. On Maverick system I get a serif font like Times Roman for the menus and on the Yosemite system, I get a san serif like ariel or helvetica.
I'm trying to force PDF.js to use a san serif font.

Any help would be appreciated.

Thanks

**Comment by timvandermeij** [comment]
It should be enough to add your desired `font-family` in https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L18-L21. The viewer uses `font: message-box` by default, see also the CSS file for that. Since this is just CSS work and no bug in PDF.js, I'm closing this as answered.
