### ISSUE TITLE
The color of some texts is wrong.

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#6234]
I uploaded the sample file:
http://www.broadband-xp.com/test/pdfjs/english_title2.pdf

When I load the above PDF in
https://mozilla.github.io/pdf.js/web/viewer.html
with Firefox 39.0, the color of texts is wrong.
With Adobe Reader it is blue or something, but with pdf.js it is white.
No error in console.

**Comment by timvandermeij** [comment]
This appears to be another pattern/shading problem.

**Comment by THausherr** [comment]
Here are simpler files with the same problem (using a shading pattern for text rendering): 
https://issues.apache.org/jira/secure/attachment/12652022/PDFBOX-2159.pdf
https://issues.apache.org/jira/secure/attachment/12650283/000004_ShadingPatternTextPDF.pdf
The first one is also available as postscript here:
https://issues.apache.org/jira/browse/PDFBOX-2159

**Comment by Snuffleupagus** [comment]
This could *potentially* be related to issues: #3988, #5432 and #6130.

**Comment by timvandermeij** [comment]
This PDF now renders exactly the same as in Adobe Reader/Acrobat, so I'm closing this as fixed. The other PDF files in this issue are indeed related to the other mentioned issues, and not to this issue.

**Comment by Snuffleupagus** [comment]
@THausherr Can we include the PDF files mentioned in https://github.com/mozilla/pdf.js/issues/6234#issuecomment-126369593 in the test-suite?
I've got a patch (locally), which fixes *one part* of the issues with those files.

**Comment by THausherr** [comment]
Only the PDFBOX-2159.pdf file, because I created that one. The other one was provided by Petr Slaby ( slaby at kwsoft.de ) but I don't know if he's the author.
