### ISSUE TITLE
Find bar locates correct text, but highlights incorrect text

### ISSUE THREAD

**Issue by Thunderforge** [mozilla/pdf.js#6237]
I have discovered a situation where PDF.js is finding the correct phrase in a PDF, but is highlighting letters that are not part of the phrase. To reproduce:

<ol start="1">
  <li>Open https://www.sec.gov/investor/seniors/seniorsguide.pdf with the default PDF.js viewer (or Firefox)</li>
  <li>Open the find bar and search for the following: www.sec.gov/investor</li>
  <li>Notice that the first match correctly highlights the phrase</li>
</ol>

![correct highlighting](https://cloud.githubusercontent.com/assets/6200170/8781328/eea8d694-2ed3-11e5-980f-1309ca87edc0.png)

<ol start="4">
  <li>Click the button to go to the next match</li>
  <li>Note that although it did find another instance of the phrase, the viewer is  instead is highlighting the letters "ens: www.sec.gov/inv", and part of the following letter "e"</li>
</ol>

![incorrect highlighting](https://cloud.githubusercontent.com/assets/6200170/8781302/d3e1a502-2ed3-11e5-804e-e33216d9fcb5.png)

This is reproducible in both Chrome and Firefox. It does not occur in Adobe Reader.

**Comment by Snuffleupagus** [comment]
I can no longer reproduce this issue, using the latest version of PDF.js (`1.2.68`).
It was most likely fixed by PR #6588, hence I'm closing this issue.
