### ISSUE TITLE
Images rendered as negatives.

### ISSUE THREAD

**Issue by lightonflux** [mozilla/pdf.js#6238]
When i view [this pdf](http://fqa.9front.org/dash1.kaptnblaubar.pdf) with pdf.js in Firefox 39 (Linux) all the images (except the pdf cover) are inverted. In my regular pdf viewer (evince) everything looks normal.

![bildschirmfoto vom 2015-07-20 20 31 36](https://cloud.githubusercontent.com/assets/1377943/8783794/593a7144-2f1e-11e5-9fb2-ecc5d54f8ef2.png)
.

**Comment by timvandermeij** [comment]
Hm, that's a strange one. We will have to triage this. Thank you for reporting this!

**Comment by timvandermeij** [comment]
All images have `BitsPerComponent = 8` and `Decode` array {1, 0, 1, 0, 1, 0}. We are probably not handling that well.

**Comment by Thunderforge** [comment]
Chrome, IE 11, and Adobe Reader all properly render this PDF properly.
