### ISSUE TITLE
Print quality between browers.

### ISSUE THREAD

**Issue by tucker87** [mozilla/pdf.js#6241]
Print quality in Chrome is much lower than in Firefox. 

In the example I loaded the demo and clicked the pdf.js print button then output the document to "Save as PDF." The blurriness is present when sent a printer as well.

I couldn't find a bug specific to print quality differences.

![pdf js print quality](https://cloud.githubusercontent.com/assets/6833267/8792566/0f5f5814-2f37-11e5-8cbe-6fd3faafb26a.jpg)

**Comment by timvandermeij** [comment]
Closing since this is expected based on https://github.com/mozilla/pdf.js/issues/6719#issuecomment-325987006. Only Firefox provides `mozPrintCallback` to avoid rasterizing the output, the other browsers don't. General quality improvements are tracked in #2750 instead.
