### ISSUE TITLE
Watermark displays over text or not at all when images or urls are on a PDF page.

### ISSUE THREAD

**Issue by andyjgibbs** [mozilla/pdf.js#6245]
I used stamptk and pdktk to add watermarks to PDFs.  They display correctly in desktop based PDF viewers.

The watermark appears over the text when images are included in the page.

The watermark doesn't appear at all if urls are included on the PDF page.

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, paying special attention to the *first* paragraph. I'm also quoting the relevant section:
> [...] and provide more details about the issue: link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages.

At the very least, you must provide a link to a PDF file that can be used to reproduce this issue.
If the PDF file isn't available online, please upload it to a file sharing service (e.g. Dropbox, Google Drive, Microsoft OneDrive or similar), and paste a link to the file here.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided. We need at least a PDF file to reproduce the issue.
