### ISSUE TITLE
Text annotations not rendered 

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6246]
File: https://drive.google.com/open?id=0B6YhVF9p-y2Ad3VsWDRHRkRxY2c

Using latest demo viewer with Chrome, Safari, Firefox on OS X 10.10.4

No text annotations were rendered by PDF.js.

This is how it look like in OS X Preview
<img width="464" alt="screen shot 2015-07-22 at 6 12 40 pm" src="https://cloud.githubusercontent.com/assets/1201310/8819114/4380c5da-309d-11e5-99c7-eab2125121ef.png">

And OS X Adobe Acrobat Reader DC 

![screen shot 2015-07-22 at 6 13 43 pm](https://cloud.githubusercontent.com/assets/1201310/8819145/6c1cfd74-309d-11e5-8bfd-6b1cd46b5fc7.png)

**Comment by Snuffleupagus** [comment]
```
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a; modified using iText® 5.5.6 ©2000-2015 iText Group NV (AGPL-version) / TeX] (PDF.js: 1.1.326 [WebGL])
```
According to http://brendandahl.github.io/pdf.js.utils/browser/, all annotations have `Subtype = /FreeText`.

**Comment by timvandermeij** [comment]
`/FreeText` is not completely implemented yet. https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L285 seems to indicate it is not implemented at all, but I have seen some examples that do render.

**Comment by timvandermeij** [comment]
This is now tracked in #6810.

**Comment by Lalala-YD** [comment]
Has the problem been solved? I ran into the same problem. I used iText5.5 to add annotations to PDF that Google Browser can`t see
