### ISSUE TITLE
Print Page-Break and Blurry font issue with Safari

### ISSUE THREAD

**Issue by CRajiv** [mozilla/pdf.js#6248]
If i print a PDF with safari browser print is blurry and shows wrong page breaks.  I have verified and confirmed that safari not taking @page CSS rules.

CSS

      @page{
         size: A4 portrait;
         margin: 0mm;
        }

We couldn't see this issues in chrome and FF.

**Comment by timvandermeij** [comment]
Do you have an example PDF file? What version of Safari are you using?

**Comment by CRajiv** [comment]
Browser: Safari 5.1.7. 
OS : Windows 8
![safari_issue](https://cloud.githubusercontent.com/assets/13448382/8869476/c1dcdb2a-3201-11e5-991e-34aec7085411.png)

**Comment by muthu07** [comment]
I am also facing same issue on this @timvandermeij. In the issue number#6654

**Comment by CRajiv** [comment]
Still we are facing this issue. Do you have any update regarding this issue?

**Comment by yurydelendik** [comment]
#7677 improves printing for Safari too. Closing as WFM. Quality of printing maybe further improved by #7077
