### ISSUE TITLE
after display pdf in canvas, problem converting it to image

### ISSUE THREAD

**Issue by loverdrive** [mozilla/pdf.js#6249]
Hi. I want to convert, client-side, a pdf into a img. I show pdf into a canvas with pdf.js  Then, i convert canvas into image, with

```javascript
var myimage = new Image();
myimage.src = canvas.toDataURL("img/png");
window.open(myimage.src);
```

but it creates only a full-white page. Don't write the canvas content.

But if i use same code to convert into a image a canvas not created by pdf.js  it works. So, i think the problem is related to canvas created by pdf.js

Have you any idea?
Thank you

**Comment by Rob--W** [comment]
`img/png` is not a valid MIME-type, try `image/png` instead. Also, how are you using PDF.js, in which browser, and using which PDF file?

**Comment by timvandermeij** [comment]
Closing as incomplete. Adjust the MIME type first and then check whether you convert the canvas to an image strictly *after* it has been rendered, otherwise the canvas will be white. Since this does not appear to be a problem with PDF.js, but rather with a custom implementation, please use the mailing list for these types of issues instead unless you are certain that it is a problem in the PDF.js library.

**Comment by allenpzx** [comment]
> Hi. I want to convert, client-side, a pdf into a img. I show pdf into a canvas with pdf.js Then, i convert canvas into image, with
> 
> ```js
> var myimage = new Image();
> myimage.src = canvas.toDataURL("img/png");
> window.open(myimage.src);
> ```
> 
> but it creates only a full-white page. Don't write the canvas content.
> 
> But if i use same code to convert into a image a canvas not created by pdf.js it works. So, i think the problem is related to canvas created by pdf.js
> 
> Have you any idea?
> Thank you

Hi bro, I got this requirement too, did you do it well?, I want to get the pdf into img src, so How can i get the data url,
or does the page.render has hooks to detect when to finished render?

**Comment by allenpzx** [comment]
> Closing as incomplete. Adjust the MIME type first and then check whether you convert the canvas to an image strictly _after_ it has been rendered, otherwise the canvas will be white. Since this does not appear to be a problem with PDF.js, but rather with a custom implementation, please use the mailing list for these types of issues instead unless you are certain that it is a problem in the PDF.js library.

Hi bro, is there any way to direct get the pdf data url into img src to render?
Until now, I can get the page, if render canvas to dataURL is unnecessary to me, 
How can i get the data url
`    const pdf = await pdfjs.getDocument(pdfFile).promise;
    const page = await pdf.getPage(1);`
