### ISSUE TITLE
Can be used to create a new PDF document Splited by Quantiy of pages?

### ISSUE THREAD

**Issue by marveen** [mozilla/pdf.js#6251]
The issue is this: 

I had a scanned  pdf document with (10) pages , i need to open this document and split on 5 documents, each one  with 2 pages , that´s because the main document contains 5 distincts docs i  need to reclassify this. 

can someone give me a idea to do this...

**Comment by timvandermeij** [comment]
PDF.js is a PDF parsing and rendering library. It is not a PDF producer, so you should find another tool to write PDF files for you.
