### ISSUE TITLE
Replace PNG assets with SVG assets

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6252]
After discussion on #6242 we found that it might be a good idea to move away from PNG assets towards SVG assets. That way we do not need two files for each image (regular and @2x) and the icons always look good on any screen and configuration. This would require that the UX team recreates all icons in SVG format, or just provide them if they are already designed in vector format, which we have to discuss with them.

**Comment by yurydelendik** [comment]
We had the icons in SVG format first. But on low-res displays they looked bad due to "uncontrolled" rasterizing by the web browser. With new design we adapted PNG assets.

Closing as won't fix for now.

**Comment by jancborchardt** [comment]
@yurydelendik would it be possible to add the SVG files to the repo as they are the source files? I want to do a light & simple theme and it would be great to have the source SVGs for that. (But also in general it would be cool to have the image sources as well since it’s, well, open source. ;)

**Comment by yurydelendik** [comment]
@jancborchardt New PNG resources were created without SVG source, PNG files are source files that were contributed under Apache license afaik. There is another issue opened (#3528) for themes. Current viewer's HTML is not easy to modify, however appearance modification is possible by just adding extra CSS.

**Comment by jancborchardt** [comment]
@yurydelendik thanks a lot! :) And yep, I’m currently toying around just with the CSS, using invert filters.
