### ISSUE TITLE
PDF Viewer [FIREFOX]: Ctrl + scroll wheel maximizes/minimizes the scale

### ISSUE THREAD

**Issue by arni2033** [mozilla/pdf.js#6263]
I wrote the full description on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1171659

Please read this, especially the "32768" part:
https://developer.mozilla.org/en-US/docs/Web/Events/DOMMouseScroll#detail

That makes your function basically useless because in this case it maximizes/minimizes the scale:
https://github.com/mozilla/pdf.js/blob/45810e0866e4d2047e71501b03ff92051cb1b2ad/web/viewer.js#L1786

SOLUTION:
I don't know if your decision about zooming up/down is good for those people who decides to scroll by 1-3 lines using mouse wheel, BUT I strongly suggest you to make ticks = 1 for those who scroll by 1 page (such as myself).

P.S. I am experiencing this issue on Firefox for several years now.
[my email is on bugzilla in case of PM]

**Comment by timvandermeij** [comment]
Similar as #6317, closing for now. If necessary, this can be revisited later on.
