### ISSUE TITLE
Loading valid file results in Invalid PDF structure

### ISSUE THREAD

**Issue by Hengjie** [mozilla/pdf.js#6275]
Loading http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.294.2304&rep=rep1&type=pdf from Chrome Extension results in `Message: Invalid PDF structure` being thrown. But if I download the file manually (say, with `wget`) and open it in PDF.js, it'll render fine.

**Comment by Rob--W** [comment]
Refreshing the page seems to work. This problem does not seem to be a problem with PDF.js per se, but some weird restriction with the website.

```
GET /viewdoc/download?doi=10.1.1.294.2304&rep=rep1&type=pdf HTTP/1.1
Host: citeseerx.ist.psu.edu
Connection: keep-alive
CSP: active
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
Accept: */*
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,nl;q=0.6,en-GB;q=0.4
Cookie: JSESSIONID=069C46E2663358C9ADDED860E5DBA302
```

```
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
Location: http://citeseerx.ist.psu.edu/messages/downloadsexceeded.html
Content-Length: 0
Date: Wed, 29 Jul 2015 08:34:13 GMT
```

**Comment by Hengjie** [comment]
Gotcha, this can probably be closed. Though, the UX here should probably be, if redirected, we follow the redirects in the browser and if it turns out the end result isn't a valid PDF doc, we can render it in the  browser.
