### ISSUE TITLE
Embedded Files in PDF not working - kind of !?

### ISSUE THREAD

**Issue by 4F2E4A2E** [mozilla/pdf.js#6276]
Hello Guys!

Thank you for this great project and Community, as already discussed today in the IRC-Chat we are having a hard time reading Embedded Files from a PDF [6].

The topic is not an easy one but some guys [1] have already explained and done the ground work for a discussion about this. 

### Working Case:
Open up the PDF-JS Viewer [3] with the file [2] mentioned in the article [1], click the attachments tab and download the embedded file. Great it works!

### No so working case:
Create an empty PDF and add an attachment to it [4] or use this test file [5], open up the PDF-JS Viewer [3] with one of the mentioned files and click on the attachments tab, it does not work.

### Why?
We think that there are more ways how to embed files into a pdf since newer versions of pdf acrobat readers appeared and the other ways have most probably not been implemented yet. Therefore a file embedded with Acrobat Reader higher version - like 11, will be not found and not displayed by pdf.js at all.

1: http://openpreservation.org/blog/2013/01/09/what-do-we-mean-embedded-files-pdf/
2: http://opf-labs.org/format-corpus/pdfCabinetOfHorrors/fileAttachment.pdf
3: http://mozilla.github.io/pdf.js/web/viewer.html
4: http://help.adobe.com/en_US/acrobat/X/standard/using/WS58a04a822e3e50102bd615109794195ff-7e4e.w.html
5: https://onedrive.live.com/view.aspx?resid=A2E6EDB5D81A9B36!7890&ithint=file%2cpdf&app=WordPdf&authkey=!AKx_9e-1AJjlAEE
6: http://blogs.adobe.com/insidepdf/2010/11/pdf-file-attachments.html

**Comment by VladBlue** [comment]
We have uploaded the not working attachments here:

https://onedrive.live.com/view.aspx?resid=A2E6EDB5D81A9B36!7890&ithint=file%2cpdf&app=WordPdf&authkey=!AKx_9e-1AJjlAEE

Please let us know your thoughts!

**Comment by 4F2E4A2E** [comment]
Maybe the PDF must be linearized before trying to read it: https://gist.github.com/hubgit/6078384#qpdf

**Comment by timvandermeij** [comment]
The reason for this issue is that the attachments are added as `FileAttachment` annotations, which are not supported by PDF.js yet. Previously this was not clear, but with the refactored annotation code this is now visible in the console:

`Warning: Unimplemented annotation type "FileAttachment", falling back to base annotation`
