### ISSUE TITLE
Print Preview is not in proper format , in Chrome Browser.

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#6279]
Hi , I think this issue may be fixed long time ago but still i am getting this issue . I am using PDF Js Stable 1.1.1 version. Please help me any code to be added or any version of css to be used ??
I could not get any info by seeing the existing issues

![capture](https://cloud.githubusercontent.com/assets/12858790/8976996/0e9879ba-36b2-11e5-859a-a3908d5dab79.PNG)

**Comment by timvandermeij** [comment]
You should update to the latest release 1.1.215 and try that as it includes #5857 (which likely has fixed this). Otherwise try the current master branch. Closing as answered; if there are still issues with the current master, feel free to let us know to reopen this.
