### ISSUE TITLE
Type 4 shading (Gouraud shading) not or no longer supported

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6283]
See these files:
https://issues.apache.org/jira/secure/attachment/12647115/PDFBOX-2100-gouraud-RGB-function.pdf
https://issues.apache.org/jira/secure/attachment/12647112/PDFBOX-2100-gouraud-CMYK-function.pdf

Apparently type 4 shading was implemented some time ago, but no longer works...

You can find the Postscript here:
https://issues.apache.org/jira/browse/PDFBOX-2100

Very useful help on how to color a triangle, almost no math skills needed:
http://classes.soe.ucsc.edu/cmps160/Fall10/resources/barycentricInterpolation.pdf

Whoever did types 6 and 7 for you should be able to do types 4 and 5.

The files I created myself (with postscript) are usually apache licensed, except for those that mention an "inspiration" in the PS source. Many such files are also in PDFBOX-1915.

**Comment by timvandermeij** [comment]
Closing as fixed by the PR that fixed the shading type regressions. These now render again. The artefacts (additional lines) are tracked in #6284 where we have more examples.
