### ISSUE TITLE
Shadings rendered with additional lines

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6284]
Coons shading without function works: 
https://issues.apache.org/jira/secure/attachment/12647101/coons-nofunction-RGB.pdf

but Coons shading with function doesn't:
https://issues.apache.org/jira/secure/attachment/12647093/coons-function.pdf

You can find the Postscript here:
https://issues.apache.org/jira/browse/PDFBOX-1915

**Comment by timvandermeij** [comment]
Possibly related: https://issues.apache.org/jira/secure/attachment/12658600/LATTICE2.pdf (same extra lines)

**Comment by timvandermeij** [comment]
More PDFs that render fine, but with additional lines:

https://issues.apache.org/jira/secure/attachment/12647115/PDFBOX-2100-gouraud-RGB-function.pdf
https://issues.apache.org/jira/secure/attachment/12647112/PDFBOX-2100-gouraud-CMYK-function.pdf

**Comment by timvandermeij** [comment]
Since all the PDF files in this issue now render correctly except from having some additional artefacts (lines to the end of the page), I'm renaming this issue to reflect that.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7184.
