### ISSUE TITLE
Japanese character(酸) not displaying properly

### ISSUE THREAD

**Issue by jcarterdev** [mozilla/pdf.js#6286]
I have linked a pdf with examples. 
https://www.dropbox.com/s/hyjqelspujhcf8g/error_sample1.pdf?dl=1

font 1: no problem.
font 2, which is an embedded font, the character appears to be missing. The missing character can however be copied to the clipboard for what thats worth.

I've also included an image showing the problem.
![missingcharacter_firefox](https://cloud.githubusercontent.com/assets/8525397/8991890/67cae038-36c9-11e5-8eac-572d826156aa.png)

**Comment by timvandermeij** [comment]
Thank you for the minimial test case! The console lists:

<pre>
"Warning: Not enough parameters for rcurveline; actual: 0, expected: 8" pdf.worker.js:224:5
"Warning: Not enough parameters for hmoveto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for hstemhm; actual: 0, expected: 2" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
"Warning: Not enough parameters for hstem; actual: 0, expected: 2" pdf.worker.js:224:5
"Warning: Not enough parameters for rcurveline; actual: 0, expected: 8" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
"Warning: Not enough parameters for rmoveto; actual: 1, expected: 2" pdf.worker.js:224:5
"Warning: Not enough parameters for callsubr; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for rcurveline; actual: 0, expected: 8" pdf.worker.js:224:5
"Warning: Not enough parameters for hmoveto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
"Warning: Not enough parameters for callsubr; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
"Warning: Not enough parameters for rmoveto; actual: 0, expected: 2" pdf.worker.js:224:5
"Warning: Not enough parameters for vvcurveto; actual: 0, expected: 4" pdf.worker.js:224:5
"Warning: Not enough parameters for rcurveline; actual: 1, expected: 8" pdf.worker.js:224:5
"Warning: Not enough parameters for vmoveto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for callsubr; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for vmoveto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for vlineto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for rcurveline; actual: 0, expected: 8" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
"Warning: Not enough parameters for hstem; actual: 0, expected: 2" pdf.worker.js:224:5
"Warning: Not enough parameters for vmoveto; actual: 0, expected: 1" pdf.worker.js:224:5
"Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6" pdf.worker.js:224:5
...
</pre>

which might make this related to #5929.

**Comment by pillaiabhilash** [comment]
Hi There,

We got a Japanese document, attached here:

[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/54127/compressed.tracemonkey-pldi-09.pdf)

It has problem when rendered using PDF.js (attached images show how the original is & how does it look with PDF.js..

![original document - view](https://cloud.githubusercontent.com/assets/12607134/11631038/38b865ae-9d26-11e5-8540-87379a88f8cf.png)
![document using this tool - view](https://cloud.githubusercontent.com/assets/12607134/11631037/38b6f5e8-9d26-11e5-9b69-a025024e4e31.png)

Any thoughts?

Thanks
Abhi

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6724.
