### ISSUE TITLE
Some reference images of GWG test files not rendered correctly

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6288]
Two reference images in 2 test files from the Ghent Workgroup ( http://www.gwg.org/ ) 
https://issues.apache.org/jira/secure/attachment/12626558/GWG060_Shading_x1a.pdf
https://issues.apache.org/jira/secure/attachment/12626560/GWG061_Shading_x1a.pdf
are not rendered correctly (the shadings are OK).

The "problem" images are all DCT encoded, but the two that are rendered incorrectly have a Separation colorspace.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6366.

**Comment by timvandermeij** [comment]
Confirmed, thanks for noticing this!
