### ISSUE TITLE
16bit image with TIFF predictor not displayed

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6289]
16bit image with TIFF predictor in test file from the Ghent Workgroup ( http://www.gwg.org/ ) is not displayed:
https://issues.apache.org/jira/secure/attachment/12685775/GWG181_16Bit_CMYK_X4.pdf

(This is probably lowest priority, as this is not a file "from the wild")

**Comment by timvandermeij** [comment]
Fixed by pull request #8921.
