### ISSUE TITLE
Render some pages filled in black

### ISSUE THREAD

**Issue by khanghuynh92** [mozilla/pdf.js#6290]
Im using PDF.js to render some PDFs and I've encountered this problem pdfjs filled some pages filled in black

orginal page: 
![1](https://cloud.githubusercontent.com/assets/10219168/8999979/9f836a8e-376b-11e5-9eec-f0ee5fff6272.png)

and the pdf.js render like that
![2](https://cloud.githubusercontent.com/assets/10219168/8999990/acdec41c-376b-11e5-9039-e01835de1296.png)

Im using the lastest pdf.js and Chrome 45.0.(64-bit)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. The first paragraph is especially relevant here, and I'm quoting part of it below:

> [...] and provide more details about the issue: **link to the PDF,** location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by yurydelendik** [comment]
http://www.researchgate.net/profile/Chia-Wen_Lin2/publication/224751274_Error-resilient_transcoding_using_adaptive_intra_refresh_for_video_streaming/links/02bfe50ec2a6f96d9d000000.pdf

**Comment by yurydelendik** [comment]
Looks good on Mac OSX:

**Comment by SamyCookie** [comment]
No display error either in Debian Stretch (testing) 64bits with:
- default PDF.js viewer (1.0.1149) in iceweasel 38.1.0
- PDF.js 1.1.132 in chromium 44.0.2403.107

**Comment by timvandermeij** [comment]
Looks good on Windows 10 Pro x64 with Firefox 39.0 and the latest PDF.js development version too. As none of us can reproduce the problem and no additional information has been provided (OS, link to the PDF, configuration details), I'm closing this as invalid until the information requested above has been provided.
