### ISSUE TITLE
Barcode is not rendered in private network

### ISSUE THREAD

**Issue by bharat-S** [mozilla/pdf.js#6291]
Hi,
   At our on-premise private network, in pdf viewer barcode is not getting rendered.

Html is ::
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
"http://www.w3.org/TR/html4/loose.dtd">
<html><style type='text/css'>
	@font-face {font-family: 'IDAutomationHC39M'; src: url(data:font/truetype;charset=utf-8;base64,AAEAAAARAQAABAAQTFRTSI2KMfcAAJB......(large text)......3AAA=)format('truetype');}</style><body><div style="margin-bottom: 5px; height: 190px">
	<div style="font-size:10.8pt; z-index: 9999; position: absolute;top:26px; right:3.5%; display:block">
		<font id="barcodeDataValue" face="IDAutomationHC39M">*ABC1000001222*</font>
	</div>	
</div><body><html>

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. The *first* paragraph is especially relevant here, and I'm quoting part of it below:
> and provide more details about the issue: link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by timvandermeij** [comment]
Closing as incomplete as no information we can possibly work with has been provided. Please provide the information request above to reopen.
