### ISSUE TITLE
Axial and Radial shading pattern displayed as one color

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6293]
https://issues.apache.org/jira/secure/attachment/12610815/axial-input.pdf
red ball

https://issues.apache.org/jira/secure/attachment/12610820/radial-input.pdf
blue ball

This is not related to the recent regression.

**Comment by timvandermeij** [comment]
Possibly related: https://issues.apache.org/jira/secure/attachment/12652009/pattern-shading-2-4-idMatrix.pdf

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6684.
