### ISSUE TITLE
Extra stuff in type 5 shading (Gouraud mesh)

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6294]
tested with
http://107.21.233.14:8877/2d43c75f950d82e/web/viewer.html

The file
https://issues.apache.org/jira/secure/attachment/12658599/LATTICE1.pdf

has some "extra stuff" at the bottom left, near the number 1.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7184.
