### ISSUE TITLE
Radial shading (type 3) too small

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6296]
http://asymptote.sourceforge.net/gallery/shade.pdf
the radial shading (type 3) is there, but it is too small. (Maybe related to the issue where somebody complained that a radial shading was a single dot)

**Comment by timvandermeij** [comment]
Possibly related to #6006.

**Comment by THausherr** [comment]
Similar effect in
http://asymptote.sourceforge.net/gallery/shadestroke.pdf

**Comment by timvandermeij** [comment]
I think the issue that that the `Extend` array is ignored in PDF.js.

**Comment by dsprenkels** [comment]
I suspect PDF.js applies the transformation `q 0.1 0 0 0.1 0 0 cm` and draws the gradient in the rectangle, while the PDF reference says the following:
> A pattern’s appearance is described with respect to its own internal coordinate system. Every pattern as a pattern matrix, a transformation matrix that maps the pattern’s internal coordinate system to the default coordinate system of the pattern’s **parent content stream (the content stream in which the pattern is defined as a resource)**. The concatenation of the pattern matrix with that of the parent content stream establishes the pattern coordinate space, within which all graphics objects in the pattern are interpreted.

So the transformation should only be applied to the rectangle, not to the gradient.

**Comment by THausherr** [comment]
Why was this closed? @dsprenkels wrote "Note that this commit does not fix #6296". I tested the two files with http://107.21.233.14:8877/449aed77d8383fb/web/viewer.html and they still don't render correctly.

**Comment by yurydelendik** [comment]
> Why was this closed?

github assumed that "Note that this commit does not fix #6296." is a command to close this issue

**Comment by dsprenkels** [comment]
Would it be a suitable fix to concatenate the invert of the "current tranformation matrix" to the transformation described in [`RadialAxial_getIR`](https://github.com/mozilla/pdf.js/blob/2f1a626d6a0df3d74fff0d779c5a11d0d17fdf7d/src/core/pattern.js#L182)?

**Comment by timvandermeij** [comment]
Fixed by #6684.
