### ISSUE TITLE
Axial shading (type 2) too small

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6298]
https://issues.apache.org/jira/secure/attachment/12690132/Shading2Function2text.pdf

The vertical size is too small.

**Comment by Snuffleupagus** [comment]
This is *almost* fixed PR #6684.

**Comment by dsprenkels** [comment]
The error of the small _color-to-transparent_ gradients top and bottom are due to `Shadings.SMALL_NUMBER` being too large. #6796 should fix this.
