### ISSUE TITLE
Node.js headless extraction of PDF's innards

### ISSUE THREAD

**Issue by shobhitg** [mozilla/pdf.js#6302]
Hi,

I would like to convert a PDF file into json via node.js

There is another project on github [modesty/pdf2json](https://github.com/modesty/pdf2json) which uses 2 year old version of PDF.js, and from what I understand, it tricks pdf.js into using its own in memory canvas to draw everything. And from that point onwards, it extracts out data.

The issue is that the project is using quite old pdf.js code.

I would like a solution that remains current on an ongoing basis.

I am a bit confused, some of the demos of pdf.js that I have seen uses canvas, while other does actual DOM.

If we have demos that draws PDF contents in actual DOM, then there must be an intermediate layer where I can tap into and get JSON data ?

I will be happy to use phantomjs, if that means I could get pdf's content data in JSON format with all its metadata.
So it boils down to "do we have a way to get JSON data (even within browser) ? "

Thanks for any discussions / solutions?

**Comment by timvandermeij** [comment]
Check out https://github.com/brendandahl/pdf.js.utils. The PDF browser (see https://brendandahl.github.io/pdf.js.utils/browser for the live version) extracts data from the PDF file without rendering it at all. You can inspect its source code at https://github.com/brendandahl/pdf.js.utils/blob/master/browser/browser.js to see how it gathers the data. Converting that to JSON should be easy then.

Closing as answered. For more information please use the mailing list as this issue tracker is primarily used for tracking bugs in PDF.js.
