### ISSUE TITLE
Search and highlight programmatically without displaying toolbar

### ISSUE THREAD

**Issue by rahulpandya** [mozilla/pdf.js#6307]
Is there a way to implement the search and highlight functionality programmatically? Ideally, we render the page without displaying the toolbar and can use javascript to pass in a piece of text/phrase and highlight all occurrences. I see the search code in PDFFindController. I'm just not quite sure how to trigger it. I've also been trying to add code to examples/components/pageviewer.js because this was an established example without the toolbar, but it uses the PDFPageView object and I'm not sure if that's an issue at all.

**Comment by timvandermeij** [comment]
This request is already tracked in #1875. To work without the toolbar you should indeed use the components example.

**Comment by yurydelendik** [comment]
PDFFindController now does not require find bar to function, see also https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L57
