### ISSUE TITLE
Character rendering incorrectly

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#6312]
Using latest version: 1.1.357
On Chrome 44.0.2403.125 m
PDF file:  http://seth.redirectme.net/med/pdf/55a3e76831f73.pdf

Renders correctly in adobe acrobat, but displays '!' symbol instead of '<' in pdf.js (see images)

Interestingly, when I copy the character to the clipboard from adobe acrobat it pastes as '!'.

![image](https://cloud.githubusercontent.com/assets/10129039/9071543/be155e50-3aed-11e5-8da4-575fdef30b60.png)

![image](https://cloud.githubusercontent.com/assets/10129039/9071588/eef25f3c-3aed-11e5-8a3a-8a10b9da921a.png)

**Comment by timvandermeij** [comment]
I can confirm this using Windows 10 Pro x64, Firefox 39.0 and the latest PDF.js development version.

**Comment by timvandermeij** [comment]
Closing as fixed by #6715.
