### ISSUE TITLE
Download PDF dialog shows "from:blob"

### ISSUE THREAD

**Issue by disha87** [mozilla/pdf.js#6313]
<img width="1434" alt="screen shot 2015-08-04 at 1 37 02 pm" src="https://cloud.githubusercontent.com/assets/5131487/9072097/17392c4a-3aae-11e5-85e2-fe3c8841e4bb.png">

**Comment by timvandermeij** [comment]
More information: occurs on https://mozilla.github.io/pdf.js/web/viewer.html in Firefox. Minor issue in my opinion, so I'm marking the correction of this as a feature for now.

**Comment by disha87** [comment]
When is this expected to be fixed? Is there a work around in the mean time which we can implement?

**Comment by Snuffleupagus** [comment]
It seems that fixing this is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1053327.

**Comment by Snuffleupagus** [comment]
*Follow-up to https://github.com/mozilla/pdf.js/issues/6313#issuecomment-255361077:* Is it meaningful to keep this issue open, when it's blocked on an upstream bug (which is approaching *five* years of age)?

**Comment by timvandermeij** [comment]
No, let's track this upstream.
