### ISSUE TITLE
Is it possible show side panel by default in pdf JS?

### ISSUE THREAD

**Issue by ananyaojha** [mozilla/pdf.js#6319]

**Comment by timvandermeij** [comment]
Yes, see https://github.com/mozilla/pdf.js/wiki/Viewer-options. Currently there appears to be a regression there, but a fix is already available in #6314 and will probably land soon. Closing as answered.

**Comment by ananyaojha** [comment]
let me see... thank you

**Comment by timvandermeij** [comment]
There is also the https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.js#L26 preference.

**Comment by ananyaojha** [comment]
Thank you.. Can you tell me how to show default page fit in pdfjs?
