### ISSUE TITLE
can we set page fit as default view in pdfjs?

### ISSUE THREAD

**Issue by ananyaojha** [mozilla/pdf.js#6320]

**Comment by ananyaojha** [comment]
I have set

**Comment by timvandermeij** [comment]
This is also a preference: https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.js#L25

The GitHub issue tracker is mainly intended for tracking bugs in PDF.js. Support questions should be asked either on IRC or on the mailing list. Thanks.

**Comment by ananyaojha** [comment]
Thank you :)  I did the same yesterday itself... Anyways thanks for helping

**Comment by choosenvictim** [comment]
@ananyaojha 
Setting DEFAULT_SCALE = 'page-fit'; works for me
Thanks

**Comment by gurjeet** [comment]
For anyone looking at this issue in the future, the variable that affects this is now (as of v2.4.456) is named `DEFAULT_SCALE_VALUE`. So change the code in `web/ui_utils.js` from

```
const DEFAULT_SCALE_VALUE = "auto";
```
to 
```
const DEFAULT_SCALE_VALUE = "page-fit";
```
