### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by closdesignUIUX** [mozilla/pdf.js#6322]
Was pinch to zoom ever implemented?  I saw a thread from 2013 about it. (https://github.com/mozilla/pdf.js/issues/2582) 
Was this ever implemented?  I don't see it in the latest version unless I am missing something.

**Comment by timvandermeij** [comment]
No, it has not been implemented yet. We could not get it to work reliably. We are tracking this feature in #2582.

**Comment by sirius2013** [comment]
This feature is done? I want zoom feature on ios cordova app.
