### ISSUE TITLE
Localize / translate all strings

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6333]
Some parts of the UI in Chrome (extension and non-extension) are not translated.

it would be nice to translate the strings. Here are two examples, there are probably more instances if you search for it:
- https://github.com/mozilla/pdf.js/blob/26b9205c7e7d8d7507b26f56221bab13c0ef4001/web/viewer-snippet-mozPrintCallback-polyfill.html#L70
- #6233 (see discussion as well).

**Comment by timvandermeij** [comment]
The first one is fixed by #7697.

**Comment by Rob--W** [comment]
@Snuffleupagus Sounds good to me.
