### ISSUE TITLE
PDF does not display when hosted on IIS

### ISSUE THREAD

**Issue by aliweb** [mozilla/pdf.js#6335]
I downloaded PDF.js and double clicked on viewer.html file. It displayed the default PDF without any issues. I am using FF 35.

Then I uploaded whole folder on Windows 2003 machine and double clicked on viewer.html but it didn't display PDF. It only displayed the container like buttons, page number etc.

Then I hosted it on IIS on same machine (Windows 2003) and tried to view it in browser as follows but it didn't display the PDF. It only displayed the container like buttons, page number etc.

http://myserver/viewer.html?file=http://myserver/test.pdf

On this machine I am using Chrome 32.0.1700.76.

How to fix this issue?

EDIT
I tested it on another machine on IE10 and same issue.

**Comment by Rob--W** [comment]
Please provide error messages, etc. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by aliweb** [comment]
There is not error. Please see attached screenshot. This is how it looks like. It doesn't load default PDF document. Even if I provide "file" parameter it doesn't display anything.

![pdfjs](https://cloud.githubusercontent.com/assets/2186719/9154378/ffe7704e-3e93-11e5-938c-073708420de4.PNG)

**Comment by Rob--W** [comment]
Open the JavaScript console (Ctrl + Shift + J) and look for error messages over there.

**Comment by aliweb** [comment]
I am getting error in **viewer.js** on line **5925**.

**Uncaught TypeError: Object #<Object> has no method 'shadow'**

**Comment by Rob--W** [comment]
Your PDF.js build is incorrectly set up. Which instructions did you follow to set up PDF.js?

**Comment by aliweb** [comment]
I am using generic build of PDF.js from this page.
https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by aliweb** [comment]
Ok this is fixed now. I was using some other PDF.js not the generic one. Replacing it with generic PDF.js fixed the problem.
