### ISSUE TITLE
Extremely slow rendering in Safari sometimes due to shadow/Object.createProperty not overriding isFontSubpixelAAEnabled getter

### ISSUE THREAD

**Issue by nicksellen** [mozilla/pdf.js#6338]
I noticed that rendering a pdf on the second or third time it would be _extremely_ slow, like 10 seconds, instead of 0.5 seconds on the first render.

The `shadow` function is used to override the `isFontSubpixelAAEnabled` getter so it doesn't get called each time. This stops working though - I added a counter to record how many times `isFontSubpixelAAEnabled` is called:

![slow](https://cloud.githubusercontent.com/assets/31616/9156118/d03bacde-3ecf-11e5-9041-16bcc7822228.png)

When I modify the `shadow` function to also do `delete obj[prop]`, the issue is resolved:

``` javascript
function shadow(obj, prop, value) {
  delete obj[prop]; // just this line added
  Object.defineProperty(obj, prop, { value: value,
                                     enumerable: true,
                                     configurable: true,
                                     writable: false });
  return value;
}
```

Now it's only ever called once or twice:
![fast](https://cloud.githubusercontent.com/assets/31616/9156123/e78b4368-3ecf-11e5-9e81-fcef4bedd4c3.png)

You can (try and) recreate the problem - I put my files used here https://github.com/nicksellen/pdfjs-slow.
The PDF I used for it is available at http://www.ubersmith.com/kbase/index.php?_m=downloads&_a=downloadfile&downloaditemid=9 (I copied the file so I'd have two copies of the PDF so the fileinput triggers the change event still).

I also observe the slow rendering with http://mozilla.github.io/pdf.js/web/viewer.html.

I'm using PDFJS from https://github.com/mozilla/pdf.js/releases/download/v1.1.215/pdfjs-1.1.215-dist.zip

```
PDFJS.version = '1.1.215';
PDFJS.build = 'c9a7498';
```

And Safari version is:
![safari-version](https://cloud.githubusercontent.com/assets/31616/9156094/3e5e84ee-3ecf-11e5-8d5a-9519c1f50ddb.png)

**Comment by nicksellen** [comment]
(and I guess this is more suggesting a bug in Safari... but so long as this change doesn't introduce any other negative side effects, it solves a big problem for me)

**Comment by nicksellen** [comment]
Just two points I forgot to add:
- when it is slow almost all the time is during `showText` action (and `isFontSubpixelAAEnabled` within that, as suggested above)
- it doesn't happen with all PDFs, I was originally noticed it with an invoice generated using Ubersmith, but as I can't make that publically, I wondered if it also affected Ubersmith documentation PDF... and it does :) So, it's perhaps related to how they're generating them...

**Comment by yurydelendik** [comment]
@nicksellen was it reported to the safari's vendor? sounds like it's only their JIT affected by it

**Comment by nicksellen** [comment]
Ah, I just filed a bug report with Safari :)

**Comment by yurydelendik** [comment]
We shall probably add this test to the web/capability.js if possible. In fact we have similar test at https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js#L119 by in that case Object.defineProperty was throwing.

**Comment by timvandermeij** [comment]
Closing since Safari 8 is no longer supported in PDF.js 2.0.
