### ISSUE TITLE
PDF.js Truck Factor

### ISSUE THREAD

**Issue by gavelino** [mozilla/pdf.js#6341]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **PDF.js** and obtained a value of **3**.

The developers responsible for this TF are:

Yury Delendik - author of 44% of the files
Brendan Dahl - author of 26% of the files
Rob Wu - author of 13% of the files

To validate our results, we would like to ask **PDF.js** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **PDF.js**?

(b) Do you agree that **PDF.js** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **PDF.js** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by yurydelendik** [comment]
Closing this bug as a irrelevant one for the project. Please contact @brendandahl, @wfwalker or me over e-mail for the subject.

Personally, I'm answering "no" to a) until I see the data that backs up this statement, which makes b) and c) irrelevant.
