### ISSUE TITLE
Upper half of document is cut white

### ISSUE THREAD

**Issue by informatorius** [mozilla/pdf.js#6346]
I opened this document and its upper half is cut white.
http://www.mainconcept.com/fileadmin/user_upload/download/product_sheets/ATI_Speed_Results.pdf
It is working correctly in Adobe Reader.

**Comment by timvandermeij** [comment]
Renders just like Adobe Acrobat/Reader for me. Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the problem remains? That is the latest version of PDF.js. If the problem remains, please provide a screenshot and more information about your configuration (OS name/version, browser name/version, graphics driver data, et cetera).

**Comment by informatorius** [comment]
I use Firefox 39.0.3 on Windows 7 64 SP1 with AMD driver 15.7.1
(It is working in Internet Explorer 11, I will test with fresh Firefox profile... )
![viewer shows problem](https://cloud.githubusercontent.com/assets/6989214/9233500/b4968416-4133-11e5-89f8-a3866bde40e9.PNG)
![adobe reader is fine](https://cloud.githubusercontent.com/assets/6989214/9233504/b93d590e-4133-11e5-8779-30b24e38b9ef.PNG)

**Comment by timvandermeij** [comment]
Could you check if there are graphic driver updates available? This really appears to be a graphics card/driver issue.

**Comment by informatorius** [comment]
It is latest Windows driver version 29.07.2015.
If I am the only one seeing this issue then it doesn't matter.
But if someone else can reproduce it then maybe it is worth investigation.

**Comment by fkaelberer** [comment]
I cannot reproduce the problem, even though I also use Firefox 39.0.3 on Windows 7 64 SP1 with AMD driver 15.7.1 (all in german)

**Comment by yurydelendik** [comment]
@informatorius check #5986 and https://bugzilla.mozilla.org/show_bug.cgi?id=1168189

**Comment by informatorius** [comment]
I just updated to Firefox 40 and problem is solved.
So this is duplicate of #5986 and I can close it.
Thank you!
