### ISSUE TITLE
Separate pdf parser into its own module

### ISSUE THREAD

**Issue by ebdrup** [mozilla/pdf.js#6351]
I would love to be able to just use the pdf parser to check if a PDF file is corrupt or not. And I guess the parser alone could be used for a lot of other cool things by others.

**Comment by bubenshchykov** [comment]
:+1:

**Comment by yurydelendik** [comment]
For now, you have to include set of the JS files (like we do in unit tests, https://github.com/mozilla/pdf.js/blob/master/test/unit/unit_test.html#L13) and access parser code this way. You don't have to use web worker via display/api.js in this case. Main question is: will this API look like we have now internally or shall we repackage it in something more usable (e.g. in node.js)?

**Comment by ebdrup** [comment]
The ultimate node.js implementation would be a streaming parser.

**Comment by sandstrom** [comment]
pdf.js is a joy to use! But being able to run it on node.js would make it even better!

I've found this project[1] which has built some sort of wrapper to run pdf.js on the server. But having pdf.js packaged with more consideration to server-environments would be great. :boat: 

[1] https://github.com/peerlibrary/meteor-pdf.js/blob/master/package.js#L26

**Comment by bjrmatos** [comment]
@yurydelendik the API looks great, except for the configuration parts.. currently PDFJS relies on properties attached to global `PDFJS` for configuration.. in node.js this won't work so well.

i think you can export the parser to something like this:

```js
var pdfParser = require('pdf-parser')({ /*...options..*/ });
```

in other words.. i think the best way to do this is repackage the parser into something more usable that could be re-used for node.js and the browser (`pdf.js`)

**Comment by timvandermeij** [comment]
#6683 might be a solution for this.

**Comment by bjrmatos** [comment]
thnks! i'll follow the discussion there

**Comment by timvandermeij** [comment]
Is this still an issue now that we have UMD headers everywhere (see the PR mentioned above)?

**Comment by sandstrom** [comment]
I think this issue can be closed, since it was mainly concerned with modularisation.

But there are a few more things that could be done to facilitate server-side use of pdf.js, for example this one: https://github.com/mozilla/pdf.js/issues/7798

**Comment by timvandermeij** [comment]
Closing as fixed.
