### ISSUE TITLE
Refactor CMap factory to be async

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#6352]
Currently the [CMapFactory.create](https://github.com/mozilla/pdf.js/blob/master/src/core/cmap.js#L969) method is synchronous. We are using XMLHttpRequest e.g. at https://github.com/mozilla/pdf.js/blob/master/src/core/cmap.js#L396 in the CMap code. The XHR is becoming more asynchronous (see also Fetch API) and we need to refactor font loading code to make this method asynchronous.

(#4815 did refactoring to make translateFont/loadFont asynchronous)

**Comment by timvandermeij** [comment]
Should we also add the performance label here?

**Comment by timvandermeij** [comment]
Fixed by #7039.
