### ISSUE TITLE
Top of each page missing in Windows

### ISSUE THREAD

**Issue by deannag3** [mozilla/pdf.js#6356]
If I go to http://mozilla.github.io/pdf.js/web/viewer.html and open a multiple page PDF file that has a full page image per page, the top 1/3 of the image on each page is cut off so the top 1/3 of the page is empty. 
OS: Windows 7 Professional, Service Pack 1
FF: 39.0
Accessing it from Chrome Version 44.0.2403.125m on this same OS, it displays correctly.

If I try viewing the same exact PDF file via http://mozilla.github.io/pdf.js/web/viewer.html on my Mac, it displays correctly.
OS: OS X Yosemite Version 10.10.4
FF: 39.0.3

**Comment by yurydelendik** [comment]
Could you paste the Graphics section from about:support? (See also #6346 -- can be related)

**Comment by timvandermeij** [comment]
Indeed, also try updating to Firefox 40 as that has previously resolved a similar issue (#6346).

**Comment by deannag3** [comment]
Upgrading to Firefox 40.0.2 fixed the problem. Thank you!

Please let me know if you would still like me to post the Graphics section from about:support and I can do that.

**Comment by timvandermeij** [comment]
@deannag3 Thank you for confirming the fix. In that case there is no need to post any additional information.
