### ISSUE TITLE
Error in passing base64 / Uint8Array

### ISSUE THREAD

**Issue by RobbieLensen** [mozilla/pdf.js#6359]
Hi all,

I am having some trouble in finding the correct way to pass a base64 / Uint8Array to the default viewer that works on all browsers / platforms.

I have done the following tests:

SOLUTION 1
Here, I convert a base64 string coming from an XLMhttpRequest to an Uint8Array

//Converts a base64 string into a Uint8Array
function base64ToUint8Array(base64) {
    var raw = atob(base64); //This is a native function that decodes a base64-encoded string.
    var uint8Array = new Uint8Array(new ArrayBuffer(raw.length));
    for(var i = 0; i < raw.length; i++) {
        uint8Array[i] = raw.charCodeAt(i);
    }
    return uint8Array;
}

//Get the document 
var xmlhttp=new XMLHttpRequest();
xmlhttp.open("GET","../../documents/get_document.php",false);
xmlhttp.send();

var pdf_document = xmlhttp.responseText;

var DEFAULT_URL = base64ToUint8Array(pdf_document);

RESULTS:
FF 40.0.2 
1.0.473 --> OK
1.1.215 --> viewer window OK but pdf not loading/showing (without error message)
1.1.366 --> viewer window OK but pdf not loading/showing (without error message)

Chrome  44.0.2403.155 & Chrome on iOS
1.0.473 --> OK
1.1.215 --> viewer window OK but pdf not loading/showing (without error message)
1.1.366 --> viewer window OK but pdf not loading/showing (without error message)

Safari 8.0.6 (10600.6.3) & Mobile Safari
1.0.473 --> OK
1.1.215 --> viewer window OK but pdf not loading/showing (without error message)
1.1.366 --> viewer window OK but pdf not loading/showing (without error message)

SOLUTION 2
Passing the base64 data directly 

//Get the document 
var xmlhttp=new XMLHttpRequest();
xmlhttp.open("GET","../../documents/get_document.php",false);
xmlhttp.send();

var pdf_document = xmlhttp.responseText;

var DEFAULT_URL = 'data:application/pdf;base64,' + pdf_document;

RESULTS:
FF 40.0.2 
1.0.473 --> OK
1.1.215 --> OK
1.1.366 --> OK

Chrome  44.0.2403.155
1.0.473 --> OK
1.1.215 --> OK
1.1.366 --> OK

Chrome on iOS
1.0.473 --> OK
1.1.215 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......
1.1.366 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......

Safari 8.0.6 (10600.6.3)
1.0.473 --> OK
1.1.215 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......
1.1.366 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......

Mobile Safari on iOS
1.0.473 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......
1.1.215 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......
1.1.366 --> ERROR: unexpected server response (0) while retrieving PDF data:application/pdf;base64,JVBERi0xLjc......

From the the example at http://107.22.172.223:8877/c48a5fd7a46a111/examples/learning/helloworld64.html
I understood that there should be a way of just passing the atob(base64) string, but I haven't figured out how to do this in the default viewer.js (= setting it as DEFAULT_URL).

Thanks a lot in advance for your support!

**Comment by yurydelendik** [comment]
You cannot use responseText to handle binary (in this case PDF) data. Please use responseType and response properties to properly receive the data. Closing as answered.

See also https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data

**Comment by RobbieLensen** [comment]
Hi Yury,

Thanks a lot for your reply.
However, I do not understand why my methods seem to work without any problem in PDF.JS 1.0.473 but not in the newer versions..
If the different versions are getting exactly the same input but react differently, then there must be some kind of regression going on there, no?

Also, correct me if I am wrong, but setting the responseType is only possible for asynchronous request. And since my goal is to feed the result of the XHR to the DEFAULT_URL, I have no other choice but to execute the XHR synchronously (because the data has to be there before we can continue the logic of viewer.js)

I really hope we can get this sorted out. I love using PDF.JS I'm dying to get the latest version up an running in my tool :-)

**Comment by yurydelendik** [comment]
> setting the responseType is only possible for asynchronous requests.

Yes, that is a limitation of the web platform. Please use asynchronous request.

Set DEFAULT_URL to empty string (`var DEFAULT_URL = '';`) and in XHR `onload` callback open PDF the `PDFViewerApplication.open` method. Don't convert Uint8Array to the data URI -- it increases memory usage and does not work in legacy browsers. You can set `xhr.resposeType = 'arraybuffer';` for async request.

If you want to find out the exact reason why your solution does not work with new versions: 1) bisect  and find the exact commit when it breaks; 2) and/or provide all information requested in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md including published code for your snippets above.

**Comment by RobbieLensen** [comment]
Hi Yuri,

I have changed the logic as you suggested by leaving the DEFAULT_URL blank in the viewer.js and to change the viewer.html in such a way that an asynchronous arraybuffer request gets the document and feeds it into the PDFViewerApplication.open method and..... it works like a charm on all platforms and browsers!!! :-)

Awesome support! Thanks a million!! 
I'm really pleased that I'll be ably to update the plug-in to the latest version in my tool now :-D
