### ISSUE TITLE
All British government company check pdf files do not work with Firefox

### ISSUE THREAD

**Issue by cal-kostoff** [mozilla/pdf.js#6360]
Here is an example url, all or most of the many thousands of documents on this website do not work with Firefox pdf.js

https://beta.companieshouse.gov.uk/company/07853397/filing-history

**Comment by brendandahl** [comment]
I looked at this awhile ago. The startxref points to a bad location in the file. The file does appear to have an intact xref table, but it appears also be corrupted. To fix we'll probably need to look into our recovery mode.
