### ISSUE TITLE
viewer.js: disableAutoFetch doesn't work on latest Firefox (39,40).

### ISSUE THREAD

**Issue by axln** [mozilla/pdf.js#6361]
I use disableAutoFetch=true to load pdf files on deman. But it doesn't work in Firefox again. Tried both with disableStream set to true and false, both versions: stable (v1.1.215) and beta (v1.1.366).

I already read [#3811] (https://github.com/mozilla/pdf.js/issues/3811), the problem was solved by setting disableStream to true. But such workaround didn't work anymore.

In Chrome it works regardless of the disableStream value.

**Comment by Snuffleupagus** [comment]
How are you actually specifying/setting those parameters?
If you're attempting to supply them as hash parameters, please read https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js.

**Comment by axln** [comment]
No, I specify them in the viewer.js file:

	var DEFAULT_PREFERENCES = {
		showPreviousViewOnLoad: true,
		defaultZoomValue: '',
		sidebarViewOnLoad: 0,
		enableHandToolOnLoad: false,
		enableWebGL: false,
		pdfBugEnabled: false,
		disableRange: false,
		disableStream: true,
		disableAutoFetch: true,
		disableFontFace: false,
		disableTextLayer: false,
		useOnlyCssZoom: false
	};

**Comment by axln** [comment]
Snuffleupagus,

Thank you very much! Applied your fix and it works now.
