### ISSUE TITLE
PDF.js not showing the color image in the PDF

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6364]
Hi,

Attached PDF has a color image which is not displaying properly in PDF.js (in mozilla)
When i download the PDF i can see the color image in Page 1

Please let me know which property of the PDF/Image causing this issue

**Comment by Snuffleupagus** [comment]
Unfortunately GitHub doesn't support attaching PDF files, can you please provide a like to the file?

**Comment by Snuffleupagus** [comment]
Unfortunately GitHub doesn't support attaching PDF files, can you please provide a link to the file?

**Comment by kvk123456** [comment]
here is the URL http://www.rightprospectus.com/documents/Osterweis/SEMI_Osterweis.pdf

**Comment by yurydelendik** [comment]
It's interesting that Preview is not showing this image at all. 
<img width="992" alt="Firefox/PDF.js, Reader, Preview, Chrome" src="https://cloud.githubusercontent.com/assets/1523410/9336818/33d31cc8-45a1-11e5-83c1-4f73628f695a.png">

JPEG with CMYK colorspace

**Comment by Snuffleupagus** [comment]
This is a regression from commit https://github.com/mozilla/pdf.js/commit/e8f0700bfaa875817f3f460b64435c5b80943e0d, i.e. PR #4528.

**Comment by kvk123456** [comment]
Currently we are using the stable version V1.1.215
Can we do some change in the code and fix this issue ourself?

**Comment by timvandermeij** [comment]
You can use the patch from #6366 and apply it manually if waiting for the next release it not an option.

**Comment by kvk123456** [comment]
Not able to access this Patch

**Comment by kvk123456** [comment]
Could you please provide the patch that we can apply to Version V1.1.215 and fix this issue

**Comment by SamyCookie** [comment]
To get the current patch:
git fetch
git diff 3fa5f6cc3b30bb4808ea6c7fa86d702501e9af53^! -- src/core/image.js

**Comment by kvk123456** [comment]
Could you please tell me, when I can expect the next stable release of PDF.js with this issue fixed

**Comment by timvandermeij** [comment]
IIRC we will release a new version on September 21.

**Comment by kvk123456** [comment]
Thanks timvandermeij,
Can you please provide the link where i can download the latest stable version on September 21

**Comment by timvandermeij** [comment]
All releases are tracked here: https://github.com/mozilla/pdf.js/releases

**Comment by kvk123456** [comment]
Sorry for keep asking more details here. The next stable release coming on Sep 21 is V1.1.366
Could you please tell me which is the change set number, which has the fix for issue 6364?
