### ISSUE TITLE
Pages rendered partially

### ISSUE THREAD

**Issue by jpfleury** [mozilla/pdf.js#6365]
A lot of pages in the following PDF file are not fully rendered:

http://imslp.nl/imglnks/usimg/f/fd/IMSLP63317-PMLP02344-Chopin-Op28edDebussy.pdf

For example, here's how I see the page 4 with Firefox 40.0 in safe mode on Xubuntu 15.04:

![capture d ecran_2015-08-18_14-34-14](https://cloud.githubusercontent.com/assets/687082/9339106/42611eec-45b6-11e5-979d-5e37bbd00c3d.png)

and here's how it's rendered with Evince 3.14.2:

![capture d ecran_2015-08-18_14-35-53](https://cloud.githubusercontent.com/assets/687082/9339143/75f99838-45b6-11e5-9a94-77f6087733e4.png)

**Comment by Snuffleupagus** [comment]
From the console:
```
PDF e1cff38dc9b64afa8ea4b3b93c306b22 [1.6 - / -] (PDF.js: 1.1.387 [WebGL]) viewer.js:6645:1
Warning: Unable to decode image: Error: JPX Error: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticalyStripe, predictableTermination) pdf.worker.js:224:5
Warning: Dependent image isn't ready yet pdf.js:224:5
Warning: Unable to decode image: Error: JPX Error: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticalyStripe, predictableTermination) pdf.worker.js:224:5
Warning: Dependent image isn't ready yet pdf.js:224:5
[...]
```

**Comment by mate-user** [comment]
http://imslp.nl/imglnks/usimg/f/fd/IMSLP63317-PMLP02344-Chopin-Op28edDebussy.pdf doesn't open any more, and it's not on Web Archive either.
I found a copy here:
http://conquest.imslp.info/files/imglnks/usimg/f/fd/IMSLP63317-PMLP02344-Chopin-Op28edDebussy.pdf

**Comment by naveensaigit** [comment]
The link in the OP does not work. The same PDF can now be found [here](http://waltercosand.com/CosandScores/Composers%20A-D/Chopin,%20Frederic/Find_by_Category/Preludes/Preludes-Op28-edDebussy.pdf). The issue still exists.

![image](https://user-images.githubusercontent.com/56525288/118027721-e3437700-b37f-11eb-96a3-cfdb85bae325.png)

Console Log:
``` javascript
Warning: Unable to decode image: s: JPX error: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticallyStripe, predictableTermination) pdf.worker.min.js:22
Warning: Unable to decode image: s: JPX error: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticallyStripe, predictableTermination) VM482 pdf.js:707
Warning: Dependent image isn't ready yet pdf.worker.min.js:22
Warning: Unable to decode image: s: JPX error: Unsupported COD options (resetContextProbabilities, terminationOnEachCodingPass, verticallyStripe, predictableTermination...
```

**Comment by NigelCunningham** [comment]
https://github.com/ivmartel/dwv/issues/400 records that one user replaced the library in pdfJS and had previously broken images start working. Perhaps it would help here?

**Comment by nico** [comment]
(Both links above don't work for me; looks like http://conquest.imslp.info/files/imglnks/usimg/f/fd/IMSLP63317-PMLP02344-Chopin-Op28edDebussy.pdf is another copy. Page 4 does indeed render correctly now.)
