### ISSUE TITLE
Local PDFs can't be opened in Firefox

### ISSUE THREAD

**Issue by Fironet** [mozilla/pdf.js#6367]
Each local PDF opened in Firefox (v42.0a2) launches the Open/Save dialog box. However online PDFs open normally.

Mentioned in [another issue](https://github.com/mozilla/pdf.js/issues/6339) but as per guidelines decided to create a separate issue.

**Comment by yurydelendik** [comment]
Can you check if PDF type association was corrupted in mimeTypes.rdf? (via about:support open Profile Folder) There you shall have a section similar to:

```
  <RDF:Description RDF:about="urn:mimetype:application/pdf"
                   NC:value="application/pdf"
                   NC:fileExtensions="pdf">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:application/pdf"/>
  </RDF:Description>
```

**Comment by Fironet** [comment]
Here are the entries in mimeTypes.rdf in order of appearance:

```
<RDF:Description RDF:about="urn:mimetype:handler:application/pdf"
                   NC:handleInternal="true"
                   NC:alwaysAsk="false" />

<RDF:Description RDF:about="urn:mimetype:application/pdf"
                   NC:value="application/pdf">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:application/pdf"/>
</RDF:Description>

<RDF:Description RDF:about="urn:mimetype:application/oct-stream"
                   NC:fileExtensions="pdf"
                   NC:description=""
                   NC:value="application/oct-stream"
                   NC:editable="true">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:application/oct-stream"/>
</RDF:Description>

<RDF:Seq RDF:about="urn:mimetypes:root">
    <RDF:li RDF:resource="urn:mimetype:application/pdf"/>
...
</RDF:Seq>
```

Do I need that entry you posted listed verbatim in the file?

**Comment by yurydelendik** [comment]
Notice entry that has `NC:fileExtensions="pdf"` -- looks like it says your '.pdf' has 'application/oct-stream' mime type. Remove this entry and modify one above to have NC:fileExtensions.

**Comment by Fironet** [comment]
Ah, thanks so much. Works as expected now. Marked as closed.
