### ISSUE TITLE
Links in pdf files are not working with the builtin pdf viewer.

### ISSUE THREAD

**Issue by krats** [mozilla/pdf.js#6373]
I am using latest stable firefox version 40.0.2.

The links are showing up as "resource://pdf.js/web/" and are not clickable.

**Comment by Snuffleupagus** [comment]
As outlined in the first paragraph of https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, please provide a link to a PDF file that can be used to reproduce this issue.

**Comment by krats** [comment]
Closing the issue as the links in the pdf were not proper. And they are working fine now. Sorry for the inconvenience caused.
