### ISSUE TITLE
Analytics/Tracking feature in pdf.js

### ISSUE THREAD

**Issue by evivz** [mozilla/pdf.js#6378]
What is the best way to track user interaction with pdf's served via pdf.js?
I want to track time spent on each slides by each user.

**Comment by Rob--W** [comment]
You could detect page changes via the `pagechange` event.

It is triggered here: https://github.com/mozilla/pdf.js/blob/63ed6816eb5701c263d89ca604d17968c7db39c4/web/pdf_viewer.js#L131-L151

Example of where it is used: 
https://github.com/mozilla/pdf.js/blob/63ed6816eb5701c263d89ca604d17968c7db39c4/web/viewer.js#L1792-L1815

**Comment by bangank36** [comment]
You can use this library 
https://github.com/hueper/PDF-Analytics
