### ISSUE TITLE
View document with several customised parameters

### ISSUE THREAD

**Issue by Alplob** [mozilla/pdf.js#6379]
Hello,

I am trying to view pdf documents that requires several parameters in the URL (separated with & - ampersand). It seems that pdf.js viewer ignore them. Example, if I input the following address in my web browser (two customised parameters type and line):

    https://myserver.com/plugins/pdfjs/web/viewer.html?file=https://myserver.com/files/index.php&type=document&line=157

I get the error message 
    Message: Unexpected server response (0) while retrieving PDF "https://myserver.com/files/index.php".

(remark I can see my document when I put the address https://myserver.com/files/index.php&type=document&line=157 directly in y web browser).

Is there any way to view pdf with these additional parameters?

Thanks!

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, especially this part:

>    [...] In the latter case, the PDF path/URL must be encoded using `encodeURIComponent()`.

Closing as answered.
