### ISSUE TITLE
Highlights created by qpdfview is not rendered

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6382]
File: https://drive.google.com/file/d/0B6YhVF9p-y2AU0RlYjRKakFQRjQ/view?usp=sharing
Using latest demo viewer

The highlight added by qpdfview is not rendered.

Screenshot from Adobe Acrobat Reader DC:
![screen shot 2015-08-24 at 1 50 34 pm](https://cloud.githubusercontent.com/assets/1201310/9431520/34333df4-4a67-11e5-9018-6bbc7ee8c401.png)

I have checked the pdf file, it has a /Highlight annotation without appearance stream (`/AP`) so PDF.js doesn't render it. 
<img width="523" alt="screen shot 2015-08-24 at 1 53 59 pm" src="https://cloud.githubusercontent.com/assets/1201310/9431546/9a5fff36-4a67-11e5-98a5-988716832208.png">

PDF.js should use `/QuadPoints` and `/C` to draw the highlight rectangle

**Comment by timvandermeij** [comment]
This is now tracked in #6810.
