### ISSUE TITLE
Kernings and trackings of vertical texts are incorrect

### ISSUE THREAD

**Issue by hakatashi** [mozilla/pdf.js#6387]
From my observation, kernings and trackings of vertical texts (in Japanese) are incorrect.

Test PDF: [pdfjs-issue.pdf](https://www.dropbox.com/s/xcmsffaeld2ru3x/pdfjs-issue.pdf)
(Generated by Adobe Illustrator CC [pdfjs-issue.ai](https://www.dropbox.com/s/32dzcwsfv9cd87s/pdfjs-issue.ai))

Adobe Acrobat Pro DC 2015.008.20082:
![2015-08-27 15_21_43-pdfjs-issue pdf - adobe acrobat pro dc](https://cloud.githubusercontent.com/assets/3126484/9513990/eb3b192a-4cd0-11e5-9e84-bc3fc034cae7.png)

PDF.JS (of Firefox 40.0 Stable):
![2015-08-27 15_22_14-pdfjs-issue - pdfjs-issue pdf](https://cloud.githubusercontent.com/assets/3126484/9514006/040a1cc6-4cd1-11e5-840c-b9b0d5614842.png)

Preceding screenshots are taken in Windows 10 Japanese. OS X may have the same error.

**Comment by CodingFabian** [comment]
Thank you @hakatashi  - I found the reason and have written a fix. can we use your pdf as regression test?

**Comment by hakatashi** [comment]
Absolutely no problem, if you don't mind the embedded Noto Fonts, which are licensed under Apache license 2.0.
Anyway, thank you for your quick reply and fix!

**Comment by Snuffleupagus** [comment]
This issue is a regression from PR #4832.

**Comment by CodingFabian** [comment]
I tried to fix that, it also applies to the text layer size (which i noticed is offset in this document as well)

the fix is to use the vertical info to change the multiplication sign.

PS: Am I the only one who thinks the spec doesnt make sense? why will a positive value make the text narrow on horizontal, but wider on vertical?
