### ISSUE TITLE
Does Translation Work ?

### ISSUE THREAD

**Issue by abdulawal39** [mozilla/pdf.js#6389]
It seems translation feature is not working currently. I am talking about #locale 

Can anyone check it please ?

Thanks

**Comment by Rob--W** [comment]
`#locale=` can only be used in debugging mode, see #5730, https://github.com/mozilla/pdf.js/blob/50b15b8c10e5e56678c61d72029f95fac4b613d6/web/viewer.js#L1265-L1317 and https://github.com/mozilla/pdf.js/wiki/Debugging-PDF.js.

**Comment by abdulawal39** [comment]
ok. can you tell me an way about how I can use the translation feature on live version then ?

Thanks

**Comment by Rob--W** [comment]
@abdulawal39 To force the language to Dutch (nl) set `PDFJS.locale` to `nl` after `pdf.js` is loaded. E.g. at the top of `viewer.js`, add `PDFJS.locale = 'nl';`

**Comment by abdulawal39** [comment]
Thank You!
