### ISSUE TITLE
Shaded/Transparent graphics not displaying correctly.

### ISSUE THREAD

**Issue by dankirberger** [mozilla/pdf.js#6392]
This PDF comes from a powerpoint presentation converted to PDF with Powerpoint itself. I _do not_ have the original powerpoint, only the PDF. 

You'll see the "Heading" areas do not display correctly in the viewer. The first two disappear entirely, the last 2 become a light grey even tone.

PDF: http://www.files.com/shared/55e060d5acef1/stripped%20-%20missing%20elements.pdf
Acrobat rendering: http://i.imgur.com/9w9ytwG.png
PDFJS result (from demo site, and also our older stable version we're running):http://i.imgur.com/5IEVaz0.png

**Comment by Snuffleupagus** [comment]
This is *almost* fixed by PR #6684.

**Comment by timvandermeij** [comment]
Closing since the file is not available anymore and quite a bit of shading pattern fixes have been made in the meantime. If this is still a problem, please upload the file to GitHub and we'll reopen.
