### ISSUE TITLE
Destinations

### ISSUE THREAD

**Issue by bbrique** [mozilla/pdf.js#6393]
there is issue with destinations.
In a PDF document  with several destination  some of them does not open on right page

Exemple : 
First url with  “BA” destination : 
http://geojura.geosphere.fr/reglement/39/206/39206_rapport_20140623.pdf#nameddest=BA 
>pdf.js  opens to the right page

Second url with “03” destination :
http://geojura.geosphere.fr/reglement/39/206/39206_rapport_20140623.pdf#nameddest=03
>pdf.js opens with one page gap. 116 instead of 117

**Comment by Snuffleupagus** [comment]
This will be fixed if/once PR #6318 is merged.

**Comment by rmondesilva** [comment]
Is this issue fixed already? I tried accessing the bookmark like this:

http://localhost/assets/js/pdf.js/web/viewer.html#nameddest=section2

But did not work.
