### ISSUE TITLE
PDFs rendering incorrectly

### ISSUE THREAD

**Issue by wpdavis** [mozilla/pdf.js#6394]
We've been using pdf.js through the PDF Viewer Chrome plugin on Chromebooks. It works very well 90 percent of the time, but we've run into several instances where the PDF will render incorrectly, if at all.

Almost all of these PDFs are generated out of Adobe Illustrator.

For example, this PDF renders fine in all PDF viewers except pdf.js, where it renders as a grey box: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/08/WildersJewelry_SO138134_B1.pdf

This PDF renders to a black background with a glass of iced tea: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/07/Jerrys_SO133799_B2.pdf

In this PDF, the color of the block text should be white, but it renders as grey: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/07/StephenNightingale_SO134099_m-01.pdf

Often, the PDF will flash on the screen for a second, showing that it has rendered correctly, before settling on the final, incorrect rendering.

**Comment by fkaelberer** [comment]
Which OS and browser are you using? Have you tried the latest version of PDF.js (i.e., the [online viewer](http://mozilla.github.io/pdf.js/web/viewer.html))?

The first and second document render fine for me using Firefox 43.0a1 on Windows or Firefox 41.0b on Android and the latest version of pdf.js.

Concerning the third document:
> In this PDF, the color of the block text should be white, but it renders as grey

The block text is made up of thin white lines on black background. If you zoom in, then all pdf renderers that I have tried (Acrobat, Sumatra, and pdf.js) show the white lines similarly, but the appearance differs if you zoom out. Acrobat shows white letters (so the thin white lines hide the black background), Sumatra shows gray letters, and pdf.js shows white or gray letters, depending on the zoom level. So I wouldn't call the block gray letters an issue, it's just that pdf renderers draw thin are lines differently at sub-pixel scales.

**Comment by wpdavis** [comment]
The original report was from the latest version of Chrome OS, running Chrome 43.0.2357.81.

I just tested the first two PDFs on a Mac running Chrome 44.0.2403.157 using the latest version of pdf.js and had the same result as on the Chromebook (incorrect render). The third PDF rendered correctly.

All three rendered correctly in Safari 8.0.8 on a Mac using the latest version of pdf.js, so it looks to be a Chrome-specific issue.

Will

**Comment by wpdavis** [comment]
Video example: https://youtu.be/4UduKaYtC70

**Comment by fkaelberer** [comment]
I can confirm the behavior shown in the video using Chrome 44.0.2403.157 on Windows 7, but only if hardware acceleration is turned ON.

**Comment by wpdavis** [comment]
Yes, I can confirm if hardware acceleration is turned off the PDFs render correctly.

**Comment by wpdavis** [comment]
Also, you can turn enable `Disable accelerated 2D canvas` in `chrome://flags` for the same result.

**Comment by abioneperhobby** [comment]
I have a rendering problem too.
This pdf https://mega.nz/#!NEx3FZLR!6SCLomb_Wdaw9By10MGBuMorjoL2qO2G84XVoZqEGNM has a yellow shadow if opened with acrobat reader, sumatra pdf, foxit , chrome , windows edge, but if you try to upload this pdf on the pdf.js demo area you will not see the yellow shadow, with every browser. 

on chrome i tried to disable acceleration but nothing changed.

please, take a look to the screenshot 
![screenshot](https://cloud.githubusercontent.com/assets/2149815/9765596/55bca36a-5715-11e5-990b-2b516f8228ab.JPG)

**Comment by wpdavis** [comment]
@abioneperhobby Can you please provide a link to the PDF?

**Comment by abioneperhobby** [comment]
https://www.dropbox.com/s/urz6c211a9mdmqb/original_content.pdf?dl=1

or

https://mega.nz/#!NEx3FZLR!6SCLomb_Wdaw9By10MGBuMorjoL2qO2G84XVoZqEGNM

**Comment by amsantoki** [comment]
I am also having incorrect rendering issue with http://www.courts.state.va.us/forms/district/dc412.pdf.

In other pdf viewer works fine but when rendering it with pdf.js with enabling inetractiveForm support, all texts shown fine in annotation layer, except text boxes, in  which when i enter text it appears to be entered in vertical direction like https://screenshots.firefox.com/G6UyGvjIBSKojevl/s.comoe.com

This seems to only occur when pdf is in landscape mode

**Comment by retrazil** [comment]
@amsantoki , can you please provide more details ? What version of Firefox are you using ? What operating system are you using ? 

I opened the link you provided (on Firefox 66.0.3) but I cannot input anything.

**Comment by amsantoki** [comment]
@retrazil Thank you for your reply,

I am using firefox vrsion 66.0.3, OS- Window 10. I have enabled inetractiveForm (true) as i have mentioned earlier in question.

**Comment by Snuffleupagus** [comment]
> For example, this PDF renders fine in all PDF viewers except pdf.js, where it renders as a grey box: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/08/WildersJewelry_SO138134_B1.pdf
> 
> This PDF renders to a black background with a glass of iced tea: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/07/Jerrys_SO133799_B2.pdf
> 
> In this PDF, the color of the block text should be white, but it renders as grey: http://newsroom.bangordailynews.com/creative/wp-content/uploads/sites/4/2015/07/StephenNightingale_SO134099_m-01.pdf

Unfortunately non of those links, from https://github.com/mozilla/pdf.js/issues/6394#issue-103727693, work any more; hence closing this as INCOMPLETE for now.

(The other PDF documents mentioned above are either not available and/or seem to be completely unrelated to the issue as filed.)

---

If there's still problems here, please open a *new* issue per PDF document (providing *all* of the information requested in the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).)
