### ISSUE TITLE
How to specify no of pages to be loaded first? 

### ISSUE THREAD

**Issue by evivz** [mozilla/pdf.js#6400]
Say I have 200mb pdf with 2000 pages. Now when user open the browser till whole pdf is not downloaded he will not be able to view the pdf. 

Is there any way I can mention say download 5 pages at a time. So say user opens the browser, he will get to see the pdf directly as it will not take much time to download first 5 pages. Now when he reaches on pages to page 6 will be downloaded. So on.

Can this be done with PDF JS?
If yes how?

**Comment by yurydelendik** [comment]
There are two options: `disableStream` -- which disables progressive file loading, and `disableAutoFetch` -- which disables fetching entire file using range requests. The HTTP range requests will fetch only needed portions of a PDF. Options can be changed at web/default_preferences.js (or about:config). Closing as answered.

**Comment by evivz** [comment]
I tried above thing here: http://docstub.com/doc but still same issue. Any way to fix it?

**Comment by evivz** [comment]
Basically I want to implement progressive rendering. My backend is on laravel and is hosted on digital ocean.
