### ISSUE TITLE
Font render shifted (displacement)

### ISSUE THREAD

**Issue by futurist** [mozilla/pdf.js#6406]
See below url:

http://mozilla.github.io/pdf.js/web/viewer.html?file=http://7xkeim.com1.z0.glb.clouddn.com/20150827143655-166.pdf

Platform: Windows XP SP3(32Bit) + Chrome 44.0.2403.125 m

Problem:

![image](https://cloud.githubusercontent.com/assets/159167/9597690/f523e7d4-50b6-11e5-92bc-50a1d6c9f917.png)

The highlighted line contains text: 13486356700 when pasted to notepad, but the highlight area shifted to left.

**Comment by brendandahl** [comment]
Seems to be better now, but still not perfect.
https://www.dropbox.com/s/a6j7mdq1r6otytq/Screenshot%202015-12-15%2011.31.37.png?dl=0

**Comment by timvandermeij** [comment]
Closing since the file is no longer available and text layer fixes were made in the meantime.
