### ISSUE TITLE
Mangled text rendering (embedded TrueType font, WinAnsi encoding)

### ISSUE THREAD

**Issue by pteichman** [mozilla/pdf.js#6410]
I'm generating PDFs that render correctly in OSX Preview and Chrome and display with incorrect characters in pdf.js. Copy & paste from pdf.js yields the expected text.

You can find an example file here:
https://dl.dropboxusercontent.com/u/4565469/tmp/pdfjs-font-embed.pdf

The pdffonts output for this broken file shows:
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                            Type 1            WinAnsi          no  no  no       3  0
PFDinTextPro-Thin                    TrueType          WinAnsi          yes no  no       4  0
DINEngschriftStd,Bold                TrueType          WinAnsi          yes no  no       5  0
PFDinTextPro-Thin,Bold               TrueType          WinAnsi          yes no  no       6  0
PFDinTextPro-Regular,Bold            TrueType          WinAnsi          yes no  no       7  0
TRLucidaHandwritingItalic            TrueType          WinAnsi          yes no  no       8  0
```

After tweaking our PDF generation code, I've gotten a working render. pdffonts on the working file shows:
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                            Type 1            WinAnsi          no  no  no       3  0
PFDinTextPro-Thin                    CID TrueType      Identity-H       yes no  yes      4  0
DINEngschriftStd,Bold                CID TrueType      Identity-H       yes no  yes      5  0
PFDinTextPro-Thin,Bold               CID TrueType      Identity-H       yes no  yes      6  0
PFDinTextPro-Regular,Bold            CID TrueType      Identity-H       yes no  yes      7  0
TRLucidaHandwritingItalic            CID TrueType      Identity-H       yes no  yes      8  0
```

I've attached broken and expected output images for reference.
![pdf-broken](https://cloud.githubusercontent.com/assets/69112/9619119/7d03bea4-50c1-11e5-86a5-98ce9957f38c.png)
![pdf-expected](https://cloud.githubusercontent.com/assets/69112/9619121/7fd9a0a8-50c1-11e5-97d6-b18aaac55135.png)

**Comment by Snuffleupagus** [comment]
This is a regression from commit https://github.com/mozilla/pdf.js/commit/b5b94a4af389ef387570cf22662d9fc6bd41417a, i.e. PR #4259.

**Comment by Snuffleupagus** [comment]
@pteichman Are you the creator of the PDF file, and if so can we include it in our test suite?

**Comment by pteichman** [comment]
@Snuffleupagus I created this PDF and you're welcome to add it to the test suite. Thanks, and let me know if any more information would be helpful.
