### ISSUE TITLE
Link in PDF page shown with a border

### ISSUE THREAD

**Issue by alexxavier84** [mozilla/pdf.js#6412]
URL link in PDF page while opening in PDF.js is surrounded by a border. Where as the same document opened in Acrobat reader is just having an underline. Can we have it implemented the way its rendered in Acrobat Reader

PDF URL: http://hosted.rightprospectus.com/documents/schwab/intleft_ann.pdf
![capture](https://cloud.githubusercontent.com/assets/12302674/9657279/3d6edbdc-525d-11e5-972a-8cb513090ff8.JPG)
![capture_pdf](https://cloud.githubusercontent.com/assets/12302674/9657282/48c29320-525d-11e5-9207-b3ffbd69cfb8.JPG)

**Comment by Snuffleupagus** [comment]
This has already been fixed by PR #5585, please update to latest version of PDF.js.
*Note:* this is fixed in PDF.js versions `1.1.366` and above, see https://github.com/mozilla/pdf.js/releases.
