### ISSUE TITLE
Special Characters are visible in IE for bookmarks

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6416]
We are using pdf js 1.1.215 (the latest version ) , we are able to see special characters in bookmarks and this is critical issue for us.
Please suggest any solution or code changes for the same. 

pdf url :   http://www.rightprospectus.com/documents/PacificLi/SUM_PLLimitedDurationHighIncome.pdf

![pdf-js-bookmarks](https://cloud.githubusercontent.com/assets/13853369/9682653/67dc6ec4-5326-11e5-9900-8412765166c0.png)

**Comment by timvandermeij** [comment]
The link to the PDF file appears to be dead.

**Comment by kvk123456** [comment]
http://www.rightprospectus.com/documents/PacificLife/SUM_PLLimitedDurationHighIncome.pdf

**Comment by kvk123456** [comment]
Sorry http://www.rightprospectus.com/documents/PacificLife/SAI_Combined.pdf is the correct URL

**Comment by timvandermeij** [comment]
Looks perfectly fine for me. Please try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the issue remains. It might be the case that the website in your screenshot has embedded an old version of PDF.js.

**Comment by kvk123456** [comment]
I Still see the error in Internet Explorer with the URL you provided
![ie10](https://cloud.githubusercontent.com/assets/13853369/9772788/76dd9d28-570c-11e5-96c9-0e6384dc1b34.jpg)

**Comment by yurydelendik** [comment]
There are null (\x00) characters that are visible in the inspector (and PDF browser). I wonder if we shall just replace those with spaces or truncate when building outline.

<img width="731" alt="screen shot 2015-09-09 at 3 54 37 pm" src="https://cloud.githubusercontent.com/assets/1523410/9773976/44e0e718-570b-11e5-8f45-f5fca6db1172.png">

**Comment by Snuffleupagus** [comment]
> I wonder if we shall just replace those with spaces or truncate when building outline.

Since we might run into this kind of issue for attachments as well, and given that both the outline and attachments are using `stringToPDFString`, I'm wondering if it would make sense to add a parameter to `stringToPDFString` that allows skipping of `\x00`?

**Comment by yurydelendik** [comment]
.. or tweak that on UI

**Comment by kvk123456** [comment]
Can i expect this issue fix in next available stable version V1.1.366? 
Hope the release date is 9/21/2015
