### ISSUE TITLE
Wrong direction used for the collapsed outlineItem icon in RTL locales?

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#6422]
Looking at the outline, after PR #6242, I'm wondering if the collapsed outlineItem icon has the wrong direction in RTL locales? See the following screen-shot: 

![outline-collapsed_rtl](https://cloud.githubusercontent.com/assets/2692120/9704165/ee5ed83e-549c-11e5-9b75-778441640278.png)

---
Either this was intentional, or @shorlander simply forgot to provide a RTL version in https://github.com/mozilla/pdf.js/pull/6242#issuecomment-133462395. If this was not intended, then I think that we should fix this. We basically have three options:

1. Ask Stephen Horlander for the RTL asset. (This would seem like the "correct" solution to me, since he should have a vector original for the asset.)
2. Flip the asset using CSS, e.g. using `transform: scaleX(-1)` or similar.
3. Creating the asset ourselves, based on the the existing one. (Since this would basically mean re-saving a PNG file, I'm not sure if that would be using such a great idea.)

Given that we're getting close to the next uplift, [see dates here](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates), we probably need to make a decision, and if necessary fix this very soon (e.g. within the upcoming week, if we want to avoid shipping the current state in Firefox).

/cc @Rob--W, @timvandermeij What are your opinions on this?

**Comment by Rob--W** [comment]
How does the inspect element panel of the devtools look like in RTL Firefox?

**Comment by timvandermeij** [comment]
If we should flip it, I'm personally fine with having CSS handle that or creating the asset ourself. Re-saving a PNG file should not be a problem as it is (practically) lossless as far as I know.

**Comment by timvandermeij** [comment]
By the way, I also think that this icon should be flipped. I'm happy with the approach in #6423. @Snuffleupagus Could you also review that one and merge it if you like it too?

**Comment by Snuffleupagus** [comment]
> What does the inspect element panel of the devtools look like in RTL Firefox? (there are also triangles over there)

It actually uses LTR in part of the devtools, please see the screen-shot below. That was changed (as far as I can tell) in https://bugzilla.mozilla.org/show_bug.cgi?id=704017, since it was argued that HTML/CSS/JavaScript is always read left to right.
In our case, since we're dealing with "real" text it does seem to make sense to flip the icon (as your submitted PR does).

![rtl_devtools](https://cloud.githubusercontent.com/assets/2692120/9713954/025c4a2a-5555-11e5-9c25-d4340c3d2e36.png)
