### ISSUE TITLE
Texts in PDF are broken

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6429]
Texts in PDF is broken and looks weird in IE 10
![ie10](https://cloud.githubusercontent.com/assets/13853369/9747710/579b0dfc-564d-11e5-8f46-e094a1b76e37.jpg)

http://hosted.rightprospectus.com/Equinox/Fund.aspx?cu=35907Y733&dt=P

**Comment by timvandermeij** [comment]
This site seems to embed an old version of PDF.js. Could you try downloading the file and opening it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the issue remains with the most recent version?

**Comment by kvk123456** [comment]
I tried the PDF with the URL you have given and see same issue in IE 10
![equinox](https://cloud.githubusercontent.com/assets/13853369/9774377/1956d2a0-5716-11e5-9a76-cecf9f52eb1b.jpg)

**Comment by kvk123456** [comment]
When is the next stable release we can expect with all these fixes?

**Comment by yurydelendik** [comment]
> When is the next stable release we can expect with all these fixes?

This issue is not addressed yet. And it looks good in IE11 for me -- it's either defect in the browser (which was fixed by the vendor already) or video card driver. Can you try updating drivers or disabling hardware acceleration in IE?

**Comment by kvk123456** [comment]
Thanks yurydelendik,

I tried disabling hardware acceleration in IE. This fixed the issue. 
Could you please suggest, is there any way we can do this programmatically using javascript in client machine?

**Comment by timvandermeij** [comment]
Hardware acceleration cannot be disabled from JavaScript. It has to be done manually by the user. Really the only feasible fix for now is to upgrade to IE11 or higher (Edge). I'm not sure if there is anything at all we can do about this on the PDF.js side, @yurydelendik ?

**Comment by yurydelendik** [comment]
We have an options to disable usage of @font-face as a workaround. Nothing else we can do on the PDF.js side.

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.
