### ISSUE TITLE
Logo not showing while loading in IE 10

### ISSUE THREAD

**Issue by alexxavier84** [mozilla/pdf.js#6430]
For the PDF (link provided) file we noticed that the logo is not rendering properly on few IE 10 browser instance. Attached is screenshot on the behavior while not rendering right.

http://www.rightprospectus.com/documents/Invesco/VK-VIMCG-SAR-1.pdf

![untitled](https://cloud.githubusercontent.com/assets/12302674/9759980/ca1bdca0-570e-11e5-9493-d4fea162885d.jpg)

**Comment by timvandermeij** [comment]
Is it only the case using IE 10? If it is on a few instances only, it might also be a driver issue. Please try downloading the file and opening it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the issue remains with the most recent version of PDF.js.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
