### ISSUE TITLE
PDF document with Open Sans font is missrendered.

### ISSUE THREAD

**Issue by alankis** [mozilla/pdf.js#6432]
I have invoice created in .PDF using embedded Open Sans font, which is missrendered when preview it with default Firefox preview. You can see screenshoot at http://imgur.com/5t8d1vE

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, paying special attention to the *first* paragraph. I'm quoting the relevant section:
> [...] and provide more details about the issue: **link to the PDF**, location in the PDF, screenshot, **browser version**, **operating system**, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.

**Comment by art-solopov** [comment]
Same issue here.
[PDF](https://dl.dropboxusercontent.com/u/6226401/testproject-243395.pdf) (generated by Redmine)
[Screenshot](http://i.imgur.com/4u6QizN.png)

Ubuntu 14.04, Firefox 44.

**Comment by yurydelendik** [comment]
@art-solopov the Adobe Reader produces the same result (in Mac OSX Preview it is good though)

<img width="527" alt="screen shot 2016-02-24 at 8 38 14 am" src="https://cloud.githubusercontent.com/assets/1523410/13288566/1e40a814-dad2-11e5-9306-6425d326d060.png">

Reopening for investigation. Marking as corrupted PDF.

**Comment by art-solopov** [comment]
@yurydelendik Evince and Chromium view display it okay though. Just FYI.

**Comment by art-solopov** [comment]
I actually get this result for several TrueType fonts, including Liberation Mono and PT Sans (all downloaded from [FontSquirrel](http://www.fontsquirrel.com/)).

**Comment by yurydelendik** [comment]
@art-solopov I don't think it's related to the Open Sans font problem (and screenshot in the original issue description does not much yours). I'll close this as incomplete. Please open new issue will details related to your case. It looks like your PDF generator produces corrupted PDFs (at least based on Adobe Reader error message)
