### ISSUE TITLE
addHtml function of a div does not render the div completely

### ISSUE THREAD

**Issue by ppasi07** [mozilla/pdf.js#6436]
Hi 

  I am trying to convert a html div content, which is in a modal dialog.  I am using addHtml and the page does not render completely in the pdf document. Instead, I can see only partial content which I can see on the screen. The remaining content which is scrollable is not seen. 

Any help how to display the entire div. Thanks in advance

**Comment by timvandermeij** [comment]
Please provide an example PDF file that does not render correctly (using e.g. Dropbox, Google Drive or another file sharing service), otherwise we cannot do much about this.

**Comment by timvandermeij** [comment]
Based on your preview issue, I think you are confusing this library with the jsPDF library, which is indeed a PDF generator, so I'm closing this as invalid unless there is a real PDF.js issue here.
