### ISSUE TITLE
byteArray of pdf content generated from pdf js

### ISSUE THREAD

**Issue by ppasi07** [mozilla/pdf.js#6437]
Hello

 I want to know if I can get byteArray out of the pdf document created from pdf js. We are using iText on the backend. I am trying to make a report from html using pdf js and send the pdf byteArray to backend, which directly saves the doc in our repository.

**Comment by timvandermeij** [comment]
PDF.js is not a generator, so it will not create documents, just render existing ones. You can capture the rendered canvases, but that's probably as far as you will get.
