### ISSUE TITLE
Uncaught TypeError: Cannot read property 'div' of undefined

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6438]
Chrome 46 with demo viewer 

Press <kbd>r</kbd> key when no file is loaded will throw follow exception.
You can "unload" the file in demo viewer by open a non-pdf file.

```
Uncaught TypeError: Cannot read property 'div' of undefined
PDFViewer_scrollPageIntoView @ viewer.js:5033
pdfViewRotatePages @ viewer.js:7048
keydown @ viewer.js:7808
```

We should ignore most of the keyboard events when there is no file loaded.

**Comment by Snuffleupagus** [comment]
Since this issue specifically mentions the <kbd>R</kbd> key, and given that the approach in the referenced PR has unwanted side-effects, I'd suggest to just modify `{PDFViewer, PDFThumbnailViewer}.pagesRotation` instead.
