### ISSUE TITLE
Custom barcode font doesn't render on PDF document

### ISSUE THREAD

**Issue by brzu** [mozilla/pdf.js#6448]
Problem: barcode font doesn't render properly in pdf.js, as shown below:
![pdf_js_barcode_bug](https://cloud.githubusercontent.com/assets/14274688/9849509/fda3ccb4-5aeb-11e5-8bb8-cb3a023c8ab2.png)
As you can see, Adobe Reader displays this font properly.

System details:
PDF.js 1.1.366
Firefox 40.0.3
Chrome 45.0.2454.85 m
IE 11.0.9600.17937
Windows 8.1 Update

**To reproduce the bug:**

Barcode Font:
https://www.dropbox.com/s/0gdnwlzlg7vs77d/EskBarCode128_1.ttf?dl=0

PDF Document:
https://www.dropbox.com/s/r6zlnavu8mvrru8/odrec1a.pdf?dl=0

**Comment by Snuffleupagus** [comment]
@brzu The PDF file that you linked to (https://www.dropbox.com/s/r6zlnavu8mvrru8/odrec1a.pdf?dl=0) does not actually embed *any* font files, hence it renders identical in PDF.js and Adobe Reader for me!
Can you please provide a link to a PDF file that actually includes the the font that you referenced above?

**Comment by brzu** [comment]
@Snuffleupagus That's true - PDF file I posted does not embed any fonts and it's intended.

The font (I posted it too https://www.dropbox.com/s/0gdnwlzlg7vs77d/EskBarCode128_1.ttf?dl=0) is installed in the system. Adobe Reader makes use of it and PDF.js does not.

**Comment by yurydelendik** [comment]
Based on the screenshots you are creating the custom solution. If the intent to redistribute font to end users, you have to specify your custom fonts in the PDF.js page styles, e.g.

```
<style>@font-face { font-family: 'EskBarCode128'; src: url('/myfonts/EskBarCode128_1.ttf'); }"</style>
```

and this will work

<img width="646" alt="screen shot 2015-09-14 at 11 07 53 am" src="https://cloud.githubusercontent.com/assets/1523410/9854913/e2bbb224-5ad0-11e5-90e1-9532d1c88c48.png">

**Comment by yurydelendik** [comment]
(Also, I think `_1` in the font name, if there is a possibility, try to create a font without `_`, `-` or space in the font name)

**Comment by timvandermeij** [comment]
I'm actually a bit confused why you would intentionally want to not embed the font. Adobe recommends embedding fonts for consistent rendering on all systems. If a system does not have your font installed, rendering issues will occur because of font substitution. So unless you have a really good reason not to (font licenses for example), I would definitely recommend embedding the font (which can also be a subset so you do not have to embed the entire font) to avoid issues altogether.

**Comment by timvandermeij** [comment]
Closing since there is nothing more we can do on the PDF.js side. It's recommended to always embed fonts to prevents issues like this.
