### ISSUE TITLE
Dynamially generated black text color looks in red color.

### ISSUE THREAD

**Issue by kishorkhadake** [mozilla/pdf.js#6451]
I am using editable pdf and some text is generated at runtime and filled into pdf. Text has Tahoma font and color as blck, but after rendering text is shown in red color on firefox 38.0.5.

**Comment by Rob--W** [comment]
Please include the PDF file, screenshot of expected result and screenshot of actual result.
See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above has been provided.
