### ISSUE TITLE
Improve PDF quality

### ISSUE THREAD

**Issue by Champ116** [mozilla/pdf.js#6453]
I would like to increase the quality of the text and images.
After loading the PDF inside the canvas, the text is getting blurred.
How can I improve the quality of the PDF?

**Comment by yurydelendik** [comment]
@Champ116 could you provide more information? The PDF.js is using OS/browsers font rendering engine to display PDF. So your environment can affect the quality. Also, the way canvas if used can affect the usage, e.g. scaling is done using CSS or HiDPI parameters is not taken in account (the standard viewer is optimized to take that in account).

See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md for needed information

**Comment by edwardmeng** [comment]
I have encountered the same problem, and my environment as following:
OS: Windows 10 Professional
Browser: firefox 40.0.3
No scaling, any font

**Comment by timvandermeij** [comment]
We really need more information here: screenshots, graphics driver information, PDF files that display the problem and other information that might help debugging this. Without that, there is nothing we can do about this and then this issue will be closed as incomplete.

**Comment by timvandermeij** [comment]
Closing as invalid until the requested information is provided.
