### ISSUE TITLE
Add largestHeight and largestWidth to pdf object

### ISSUE THREAD

**Issue by DaleMatthews** [mozilla/pdf.js#6454]
Implementing fit-to-width and fit-to-height in a custom viewer (where all pages are in a scrolling div) is very challenging right now due to mixed-orientation or mixed-size PDFs. You cannot know what width to use for fit-to-width without first getting all of the pages. That means that during the initial render of the PDF document, you have to get every page before rendering the first page. This gives unwanted user-experience. The easiest solution would be a largestHeight and largestWidth property on the pdf object. I don't know if this is actually possible, so I apologize if it is not.

My current solution keeps a running maxWidth and maxHeight and renders as it gets pages. Therefore, if it encounters a new maxWidth and the setting is fit-to-width, the pages above that page are set to the wrong scale. Same with maxHeight/fit-to-height. I don't re-render because content-heavy pages take too long to load.

Sorry but I can't find a public pdf file as an example.

**Comment by brendandahl** [comment]
As far as I know the actual PDF data does not contain the maxwidth/maxheight, so if we implemented this in the API it would have to do the exact same thing you would have to do by getting all the pages and finding the maxes. If you don't care about having all the pages scaled the same it's easy to do fit-to-width.

**Comment by Snuffleupagus** [comment]
As outlined in https://github.com/mozilla/pdf.js/issues/6454#issuecomment-140907858 there's no concept of maxWidth/maxHeight in the PDF specification, and adding an API method that would essentially force the *entire* file to load seems really unfortunate; hence WONTFIX is probably an appropriate resolution here.
