### ISSUE TITLE
Text misplaced when browser zoom level is not set to 100% in FF

### ISSUE THREAD

**Issue by agruber** [mozilla/pdf.js#6456]
Text (Textlayer) does not perfectly overlap with the text canvas when the browser zoom level is not set to 100% in Firefox. Works perfectly in Chrome.

**Comment by timvandermeij** [comment]
Please post an example PDF so we are able to reproduce the issue.

**Comment by agruber** [comment]
Seems to happen with any PDF. I just tried it with the tracemonkey.pdf, see the screen shot below. Top - zoom level 100%, bottom - zoom level 200%. 

![misaligned](https://cloud.githubusercontent.com/assets/64104/9933155/2e4f87ea-5d49-11e5-9795-ca7b0681ef83.png)

**Comment by timvandermeij** [comment]
Closing as fixed, most likely by recent text layer PRs.
