### ISSUE TITLE
Filled in Form Fields not displaying

### ISSUE THREAD

**Issue by akozmic** [mozilla/pdf.js#6457]
Have a simple form in a pdf.  Text fields are not displaying their values

Adobe: 

<img width="678" alt="adobe" src="https://cloud.githubusercontent.com/assets/534131/9937719/8246e680-5d27-11e5-84c1-234be062ceef.png">

pdf.js version:

<img width="975" alt="pdfjs" src="https://cloud.githubusercontent.com/assets/534131/9937720/8248a060-5d27-11e5-9602-8aa3548b613f.png">

Here's a link to the pdf
https://www.dropbox.com/s/d09mau8dyb0fi0n/Test%20Form%20Fields.pdf?dl=0

**Comment by timvandermeij** [comment]
Works fine for me using the latest PDF.js version at https://mozilla.github.io/pdf.js/web/viewer.html. Could you try opening the file (Open File button in the toolbar) using that URL?

**Comment by akozmic** [comment]
@timvandermeij 

It looks like the demo is using version 1.1.474.   I was using stable 1.1.366.   It looks like the issue is addressed.  I apologize for the dupe.   Thanks.

**Comment by timvandermeij** [comment]
No worries! Closing as resolved.
