### ISSUE TITLE
Pdf.js not work in Iphone

### ISSUE THREAD

**Issue by agoronik** [mozilla/pdf.js#6458]
Hello, please help, why this page http://mozilla.github.io/pdf.js/web/viewer.html#page=2 not work in iphone 4 5 or 6 versions? but in android good work. Please help. Big Thank!

**Comment by timvandermeij** [comment]
We really need more information here. What does not work? Is it not rendering at all or are there rendering artefacts? Are there errors mentioned in the console? Please be as precise as possible to explain the problem.

**Comment by yurydelendik** [comment]
fwiw, tested on iphone 4s and few configurations in the emulator -- works for me.

**Comment by agoronik** [comment]
link to project http://adebiportal.kz/pdf-js-master/web/viewer.html?lang=ru&book=/upload/iblock/9cc/9cc88932e09a0b2278c9f3fafb7b8139.pdf work in android, but not work iphone 4,5,6 ... in console has errors http://adebiportal.kz/pdf-js-master/web/locale/locale.properties not found. File is exists. Please help with this problem.

**Comment by timvandermeij** [comment]
I also see `TypeError: document.getElementById(...) is null` because you removed the download button without removing the calling JS code (wait a few seconds after opening the page to see that in the console). This really seems like a custom implementation issue rather than a bug in PDF.js though...

**Comment by agoronik** [comment]
ok. I dont see this error, but we remowed all  js code that calling downloa button. Nothing happens. We testng viewer at http://www.mobilephoneemulator.com/ and we see that kind of error http://joxi.ru/aD2Pgw0HLbw0m3 I think it's because of access. How can I test it right without iphone?
Mobile phone emulator that enables you to test the display of any website in many cell phones.

**Comment by timvandermeij** [comment]
This is a CORS issue. See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request for more information. Basically you cannot load a PDF from another server by default: you have to configure the server to allow that.

Closing as answered as there appears to be no PDF.js bug here, but rather a custom implementation bug. For more help, please use the IRC channel.
