### ISSUE TITLE
Generate "pagerendered" (?) event when CSS zoom is used

### ISSUE THREAD

**Issue by kimgronqvist** [mozilla/pdf.js#6463]
I'm creating a custom annotations layer and using convertToPdfPoint to store the position of the annotation, and then draw it by calling convertToViewportPoint (or rectangle if appropriate). This works flawlessy until I zoom beyond 400%, at which point the annotation gets incorrectly positioned. 
I've also noticed that this happens at an lower zoom level if the actual browser is zoomed in.

I would appreciate any pointers to figure out why this is happening. 

I'm using the latest pdf.js and I see this is an all browsers I've tested (IE11, Chrome, Firefox).

**Comment by yurydelendik** [comment]
Depends on how CSS is used in created annotations, but you may take in account #4834. Basically you may use page or viewer scale for convertToPdfPoint/convertToViewportPoint depending on where the custom annotation layer is located. It's hard to suggest a particular solution with information provided. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by kimgronqvist** [comment]
Setting `PDFJS.maxCanvasPixels` to -1 does fix my issue, but there seems to be some perfomance implications with that.

I draw all annotations on a seperate canvas above the text layer and page canvas.

```html
<div id="pageContainer1" class="page" data-page-number="1" data-loaded="true" style="width: 426px; height: 602px;">
  <div class="canvasWrapper" style="width: 426px; height: 602px;">
    <canvas id="page1" width="468" height="662" style="width: 426px; height: 602px;"></canvas> 
  </div>
  <div class="textLayer" style="width: 426px; height: 602px;"></div>
   <div class="customAnnotationsLayer" style="width: 426px; height: 602px; pointer-events: none;">
     <canvas width="468" height="662" style="width: 426px; height: 602px;"></canvas>
  </div>
</div> 
```

One type of annotation is a highlight. It is a rectangle drawn over a specific point on the document. Given a data object with page number, a x- and y-coordinate I store it like so:

```javascript
var page = PDFViewerApplication.pdfViewer._pages[data.page - 1];

var x = data.x * page.scale,
      y = data.y * page.scale,
      width = data.width * page.scale,
      height = data.height * page.scale,
      x2 = x + width,
      y2 = y + height;

this.annotations.push({
      type: 'Highlight',
      x: x,
      y: y,
      width: width,
      height: height,
      page: data.page,
      pagePoint: page.viewport.convertToPdfPoint(x, y)
            .concat(page.viewport.convertToPdfPoint(x2, y2))
});
```

Drawing a highlight:
```javascript
var page = PDFViewerApplication.pdfViewer._pages[annotation.page - 1];

var rect = page.viewport.convertToViewportRectangle(annotation.pagePoint);

ctx.drawRect(rect[0], rect[1], rect[2] - rect[0], rect[3] - rect[1]);
```

To highlight "Trace-" in the example document I can do this:
```javascript
this.createHighlight({
        x: 100,
        y: 100,
        page: 1,
        width: 75,
        height: 30
});
```

100% zoom
![image](https://cloud.githubusercontent.com/assets/3421067/10047610/3e4bb7e8-620f-11e5-9b41-a8cd11cc688d.png)

400% zoom
![image](https://cloud.githubusercontent.com/assets/3421067/10047687/90dbb166-620f-11e5-9445-c2e2af8998d9.png)

440% zoom 
![image](https://cloud.githubusercontent.com/assets/3421067/10047717/b9c372da-620f-11e5-849f-c20ea82c9b43.png)

(And as I said, settting `PDFJS.maxCanvasPixels` to -1 fixes the highlight for zoom levels beyond 400%).

Thanks for taking a look, and please let me know if you need more information to make sense of this.

**Comment by yurydelendik** [comment]
In your case, it's better to use DOM (svg or styled divs) for annotations -- canvas takes width * height *4 bytes of memory. (Like we use text selection)

**Comment by yurydelendik** [comment]
Could you publish the example you described in https://github.com/mozilla/pdf.js/issues/6463#issuecomment-142618740 online?

**Comment by yurydelendik** [comment]
Closing as incomplete.

**Comment by kimgronqvist** [comment]
I've create a full example:

https://github.com/kimgronqvist/pdfjs-annotation-example
http://kimgronqvist.github.io/pdfjs-annotation-example/

Zoom first to 400%, then 490% to see the issue.

I'll try the svg approach soon.

**Comment by yurydelendik** [comment]
We don't generate any events when CSS only zoom used. Proposing generate "pagerendered" with cssTransform property set to true.

**Comment by kimgronqvist** [comment]
Great! Thanks for looking into this.

**Comment by chitgoks** [comment]
what i did was to calculate and store the position and dimension at 100% zoom if the user is at whatever zoom value.

this way, if the user zooms at 500%, using that original dimension and a little formula, the position will still correctly place itself regardless of zoom level.

just wondering, did your implementation slow down? even pdf.js at 400% zoom is slow at my end. adding a canvas layer for annotations (which i also did) made it slower.

maybe my ideas can help you. i placed a small guide here 

http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/

**Comment by kimgronqvist** [comment]
@chitgoks Your blog post got me started with this. Thanks a lot :)

We did notice substantial slowness with the canvas implementation. As previously stated, it's a real memory hog. Currently we use a SVG implementation that works very well.

**Comment by chitgoks** [comment]
@kimgronqvist you're welcome. i have also encountered this issue when i zoom in. when i create a new annotation the created x,y is out of place. setting PDFJS.maxCanvasPixels = -1 does the trick but you're right about the performance.

if you found a workaround, please let us know. thank you

**Comment by ManuelMadeira98** [comment]
> http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/

Do you still have this guide available somewhere? Would really appreciate it.

**Comment by ManuelMadeira98** [comment]
> what i did was to calculate and store the position and dimension at 100% zoom if the user is at whatever zoom value.
> 
> this way, if the user zooms at 500%, using that original dimension and a little formula, the position will still correctly place itself regardless of zoom level.
> 
> just wondering, did your implementation slow down? even pdf.js at 400% zoom is slow at my end. adding a canvas layer for annotations (which i also did) made it slower.
> 
> maybe my ideas can help you. i placed a small guide here
> 
> http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/

Do you still have this guide available somewhere? Would really appreciate it.

**Comment by ManuelMadeira98** [comment]
> what i did was to calculate and store the position and dimension at 100% zoom if the user is at whatever zoom value.
> 
> this way, if the user zooms at 500%, using that original dimension and a little formula, the position will still correctly place itself regardless of zoom level.
> 
> just wondering, did your implementation slow down? even pdf.js at 400% zoom is slow at my end. adding a canvas layer for annotations (which i also did) made it slower.
> 
> maybe my ideas can help you. i placed a small guide here
> 
> http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/

@chitgoks Do you still have this guide available somewhere? Would really appreciate it.

**Comment by chitgoks** [comment]
> > what i did was to calculate and store the position and dimension at 100% zoom if the user is at whatever zoom value.
> > this way, if the user zooms at 500%, using that original dimension and a little formula, the position will still correctly place itself regardless of zoom level.
> > just wondering, did your implementation slow down? even pdf.js at 400% zoom is slow at my end. adding a canvas layer for annotations (which i also did) made it slower.
> > maybe my ideas can help you. i placed a small guide here
> > http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/
> 
> @chitgoks Do you still have this guide available somewhere? Would really appreciate it.

no sorry. i gave up my hosting during covid and removed the guide prior to that. but the video is here

https://youtu.be/g2YAn-Yvlss
