### ISSUE TITLE
PDF.js throws error when trying to Open PDF file generated from a GIF file

### ISSUE THREAD

**Issue by davidfekke** [mozilla/pdf.js#6470]
We get an error when we try to open certain PDF files that are created from iText with a GIF image in the file. We are using version 1.1.469 of PDF.js. I can provide a copy of the PDF file in question if needed to duplicate the test.

If you go to line 3840 of the function putBinaryImageData, the library throws an error because the 'dest' object does not have a 'set' method. The 'dest' object just looks like a byte array, and it does not appear to have a set method.

**Comment by Rob--W** [comment]
Please include the PDF. browser version, etc. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md for instructions on creating bug reports.

This sounds like a non-modern browser. Did you include compatibility.js to fill the gaps?

**Comment by davidfekke** [comment]
Thanks for your Rob. 

Here is a link to that PDF file;
https://github.com/davidfekke/SamplePDFsForPDFjs/blob/master/somecrummyGIFConvertedTo.pdf

I will try adding the compatibility.js to my project. We are only having this issue with IE.

**Comment by davidfekke** [comment]
I added the compatibility.js file to my bundle, and it is rendering the PDF file correctly now. Thanks for your help.
