### ISSUE TITLE
convertToPdfPoint() function showing different co-ordinate

### ISSUE THREAD

**Issue by eaxle** [mozilla/pdf.js#6471]
function showCoordinate(event){
   var x=event.clientX;
    var y=event.clientY;
    var pageIndex = window.PDFViewerApplication.pdfViewer.currentPageNumber - 1;
    var page = window.PDFViewerApplication.pdfViewer._pages[pageIndex];
    var viewport = page.viewport;
    var selected=viewport.convertToPdfPoint(x,y)
   console.log(JSON.stringify(selected))
}

this is the function i use, to convert the mouse position to pdf point.The function is called when mouse is clicked.The problem is that it shows different point when i click the same postion in pdf for different zoom level.

**Comment by timvandermeij** [comment]
Related to #6463?

**Comment by eaxle** [comment]
The console shows different values for normal zoom for example it shows different values when zoomed from 100 to 150%

**Comment by yurydelendik** [comment]
clientX/clientY does not show right mouse position in relation to page div/canvas. Closing as answered. 

Please provide a concrete example online with steps to reproduce the issue. I was testing using the following -- it worked fine:

```
function showCoordinate(){
var pageIndex = window.PDFViewerApplication.pdfViewer.currentPageNumber - 1;
var page = window.PDFViewerApplication.pdfViewer._pages[pageIndex];
var x= 100 * window.PDFViewerApplication.pdfViewer.currentScaleValue;
var y= 100 * window.PDFViewerApplication.pdfViewer.currentScaleValue;
var viewport = page.viewport;
var selected=viewport.convertToPdfPoint(x,y)
console.log(JSON.stringify(selected))
}

setInterval(showCoordinate, 1000);
```

**Comment by emtiajium** [comment]
@yurydelendik How did you get 100? How to get x, y's values?

**Comment by m00dy** [comment]
> @yurydelendik How did you get 100? How to get x, y's values?

a very good question  🗡

**Comment by rahimnagori** [comment]
Can anyone please provide a working example?
