### ISSUE TITLE
Auto-print PDF in pop-up window in Firefox causes printer error dialog and js warning.

### ISSUE THREAD

**Issue by mikeclark** [mozilla/pdf.js#6472]
Seems like when a generated pdf with auto-print built into the pdf (using javascript in this case) is displayed through a pop-up window it causes a printer error(see screenshot) in Firefox using the default Firefox pdf viewer. 

This only happens if the pdf is displayed in a popup generated from javascript, going to the file without popping up a new window seems to work just fine.  Works as expected if pdf reader in Firefox is set to use Adobe Reader.

Code to generate popup:
https://gist.github.com/mikeclark/cdb8f51395f8b878ee68

Running Windows 7, Firefox 41.0, PDF.js: 1.1.215

Related issue (where I got the test pdf from): https://github.com/mozilla/pdf.js/issues/5086

Screenshot:
![pdf_firefox_issue](https://cloud.githubusercontent.com/assets/956742/10078824/ba25bbac-62b4-11e5-9a3a-e5db89364472.png)

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs.
