### ISSUE TITLE
zoom with ctrl-scrollwheel zooms from top left, instead of about mouse cursor

### ISSUE THREAD

**Issue by mrpgruber** [mozilla/pdf.js#6474]
When zooming in or out using ctrl - scroll wheel, it is much more elegant to zoom around the point of interest, which is naturally defined as where the mouse cursor is pointing.  Zooming in from the top left feels counter-intuitive, as the place the eyes are focused on moves down, left and quickly offscreen.

Inkscape, Gimp & Excel handle zoom this way. Sadly, Chrome and Firefox don't, but that needn't stop this product from doing so

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6170.
