### ISSUE TITLE
Rendering multiple pages at the same time sometimes does not work correctly

### ISSUE THREAD

**Issue by jonathan-roy** [mozilla/pdf.js#6477]
Loading a multi-pages PDF and rendering all of the pages at the same time does not seem to work correctly with some PDFs (while it's working well with some others)

I've created a live demo at http://r0y.fr/pdfjs/index.html

On OS X Yosemite, Firefox 41.0 only renders some of the pages and logs *"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"* error messages for pages that are not rendered. The pages that are shown are not correctly rendered, some elements on the background are missing, some are mis-positioned.
On Chrome 45.0.2454.99 there isn't any error but the pages are often not correctly rendered.

The same problem also appears when loading multiple PDFs at the same time.

From the console if you set *PDFView.allowSimultaneousRendering* to *false* then the problem disappears.

**Comment by yurydelendik** [comment]
Can be related (or blocked) by #5148.

The error points on using cached canvases during smask/groups compositing (see global object CanvasCache at https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L164). The CanvasCache.getCanvas accepts id as a parameter which makes this id collide for the same document and page rendering.

**Comment by LeninJeyaraj** [comment]
i used pdfmake to make pdf pages. its very usefull (https://github.com/bpampuch/pdfmake).
but how can i append multiple pages in one pdf ?
i.e i want to append multiple pages into one pdf instead of multiple pdf pages.

if any replies appreciated, thankyou.

**Comment by Snuffleupagus** [comment]
> "InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"

Closing, since this error should be fixed by PR #6551.

---

@LeninJeyaraj Your question does not seem to be related to PDF.js.
Since it even links to `pdfmake`, I'd suggest that you ask your question there instead.
