### ISSUE TITLE
PDF.js Search not working correctly

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6478]
Search functionality locating wrong place for some of the PDFs

![pdf js search issue](https://cloud.githubusercontent.com/assets/13853369/10105851/0b7ea750-637f-11e5-834e-510cfda4d0b3.jpg)

**Comment by kvk123456** [comment]
Here is the PDF url http://hosted.rightprospectus.com/documents/WilliamBlair/PRO_Combined.pdf

**Comment by timvandermeij** [comment]
The problem is that the text layer is not aligned properly.

**Comment by kvk123456** [comment]
is there any fix available for this from PDF.js?

**Comment by timvandermeij** [comment]
Not that I am aware of. Someone has to look into the cause of the misalignment.

**Comment by timvandermeij** [comment]
Closing as fixed in the latest development version of PDF.js.
