### ISSUE TITLE
Page Up / Down not working

### ISSUE THREAD

**Issue by mydoghasworms** [mozilla/pdf.js#6479]
I am using Firefox 40.0.3 on Linux (Mint 17).

When viewing a PDF document (e.g. https://mozilla.github.io/pdf.js/web/viewer.html or any other document), Page Up and Page Down does not work:

Hitting Page Down the first time scrolls halfway down the page. Hitting it a second time scrolls back to the top of the page, and from there it alternates: halfway down the page, back to the top, etc.

Hitting Page Up scrolls more than a page upwards.

**Comment by timvandermeij** [comment]
I cannot reproduce this on Windows, so either it's Linux-specific or there is an issue with your configuration. Labeling as triage-needed for now.

**Comment by mydoghasworms** [comment]
I am now unable to recreate the issue as well; must have been due to some other variables. Thanks for checking.

**Comment by fkaelberer** [comment]
I can reproduce this behavior on one of my computers too, using Firefox 41 on Windows 7.

![cursor](https://cloud.githubusercontent.com/assets/4624768/10311971/60a2b80c-6c49-11e5-9e30-e01121d02b3e.png)
I also noticed a blinking cursor that sometimes appears in the top left of a page. Maybe it's the cursor that is moving the view into focus.

**Comment by Snuffleupagus** [comment]
If Caret mode is enabled, this issue is most likely a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1210070.

**Comment by fkaelberer** [comment]
@Snuffleupagus confirmed. Toggling Caret mode resolves the issue.

**Comment by mydoghasworms** [comment]
Thanks for the info and confirming @fkaelberer  and @Snuffleupagus.
