### ISSUE TITLE
Add new fonts

### ISSUE THREAD

**Issue by maherelgamil** [mozilla/pdf.js#6483]
I need to add new fonts , how can i do this  ?

**Comment by timvandermeij** [comment]
You should embed the necessary fonts in the PDF files, but otherwise you can use CSS's `@font-face`. Closing as answered.

**Comment by maherelgamil** [comment]
thanks for you @timvandermeij :)

**Comment by arelaxend** [comment]
How to incorporate a font in the rendered page using CSS's @font-face T_T ? I am rendering a canvas with pdfjs, i have done some tests and it does not work.
