### ISSUE TITLE
Search is not working for some PDF files

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6484]
Search is not finding any text for below URL

http://www.rightprospectus.com/documents/Fidelity/PRO_VIPContrafund.pdf
![search](https://cloud.githubusercontent.com/assets/13853369/10136119/b9745ab0-65c0-11e5-91f8-2f5a94c71fa8.jpg)

**Comment by Snuffleupagus** [comment]
Searching doesn't return any results in Adobe Reader either, and trying to copy the text just returns gibberish. Since this is a case of a corrupt font data (bad/missing `toUnicode` data), and given that the PDF file is similarily broken in Adobe Reader too, I'm closing this issue as invalid.
