### ISSUE TITLE
Background not showing up

### ISSUE THREAD

**Issue by francoisprunier** [mozilla/pdf.js#6486]
Hi,

First, thanks for the great work.

I was trying to read this presentation: https://spark-summit.org/2014/wp-content/uploads/2014/06/Testing-Spark-Best-Practices-Anupama-Shetty-Neil-Marshall.pdf. It has a dark background (an image or a gradient I'm not sure) with white text. With no background, the text is white on white and thus is illegible. 

There's no error in the browser console, I'm using the firefox 41 on kubuntu 15.04.

**Comment by francoisprunier** [comment]
Adding screenshots.

In firefox:
![firefox](https://cloud.githubusercontent.com/assets/8289560/10161823/f8f324b4-66a6-11e5-9462-cabb968c2a98.png)

In okular (kde's pdf viewer):
![okular](https://cloud.githubusercontent.com/assets/8289560/10161833/0d830732-66a7-11e5-9650-9ebbe59a8dd5.png)

**Comment by timvandermeij** [comment]
The rendering of this PDF has improved a bit after recent patches. The black background is now rendered, but the shading is still not visible.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6684.
