### ISSUE TITLE
XREF issue. Using IONIC platform

### ISSUE THREAD

**Issue by TheVedhaGuy** [mozilla/pdf.js#6487]
Hey, 

I'm still new to this so sorry if this is repetetive. Anyways, I am trying to genereate a PDF file by using jsPDF.
My goal is to convert a html document (things inside a div tag) to a PDF. I receive a datauri string which I store inside a pdfValue then convert that to Binary and call upon your PDFJS.getDOcument(withBinaryStringValue) function.

I only included two files in my project, pdf.js and pdf.worker.js. I obtained these files by following the instructions.
When i check the logs in logcat, I get the following issues:

D/CordovaLog(12117): : Line 0 : The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
I/chromium(12117): [INFO:CONSOLE(0)] "The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.", source:  (0)
D/CordovaLog(12117): file:///android_asset/www/app/toPDF/pdf.worker.js: Line 232 : Error: Invalid XRef stream
I/chromium(12117): [INFO:CONSOLE(232)] "Error: Invalid XRef stream", source: file:///android_asset/www/app/toPDF/pdf.worker.js (232)
D/CordovaLog(12117): file:///android_asset/www/app/toPDF/pdf.worker.js: Line 233 :     at error (file:///android_asset/www/app/toPDF/pdf.worker.js:233:17)
D/CordovaLog(12117):     at Object.XRef_readXRef [as readXRef] (file:///android_asset/www/app/toPDF/pdf.worker.js:4307:15)
D/CordovaLog(12117):     at Object.XRef_parse [as parse] (file:///android_asset/www/app/toPDF/pdf.worker.js:3905:28)
D/CordovaLog(12117):     at Object.PDFDocument_setup [as setup] (file:///android_asset/www/app/toPDF/pdf.worker.js:3062:17)
D/CordovaLog(12117):     at Object.PDFDocument_parse [as parse] (file:///android_asset/www/app/toPDF/pdf.worker.js:2943:12)
D/CordovaLog(12117):     at file:///android_asset/www/app/toPDF/pdf.worker.js:2498:26
D/CordovaLog(12117):     at LocalPdfManager_ensure [as ensure] (file:///android_asset/www/app/toPDF/pdf.worker.js:2493:12)
D/CordovaLog(12117):     at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (file:///android_asset/www/app/toPDF/pdf.worker.js:2425:19)
D/CordovaLog(12117):     at file:///android_asset/www/app/toPDF/pdf.worker.js:34209:22
I/chromium(12117): [INFO:CONSOLE(233)] "    at error (file:///android_asset/www/app/toPDF/pdf.worker.js:233:17)
I/chromium(12117):     at Object.XRef_readXRef [as readXRef] (file:///android_asset/www/app/toPDF/pdf.worker.js:4307:15)
I/chromium(12117):     at Object.XRef_parse [as parse] (file:///android_asset/www/app/toPDF/pdf.worker.js:3905:28)
I/chromium(12117):     at Object.PDFDocument_setup [as setup] (file:///android_asset/www/app/toPDF/pdf.worker.js:3062:17)
I/chromium(12117):     at Object.PDFDocument_parse [as parse] (file:///android_asset/www/app/toPDF/pdf.worker.js:2943:12)
I/chromium(12117):     at file:///android_asset/www/app/toPDF/pdf.worker.js:2498:26
I/chromium(12117):     at LocalPdfManager_ensure [as ensure] (file:///android_asset/www/app/toPDF/pdf.worker.js:2493:12)
I/chromium(12117):     at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (file:///android_asset/www/app/toPDF/pdf.worker.js:2425:19)
I/chromium(12117):     at file:///android_asset/www/app/toPDF/pdf.worker.js:34209:22", source: file:///android_asset/www/app/toPDF/pdf.worker.js (233)
D/CordovaLog(12117): file:///android_asset/www/app/toPDF/pdf.worker.js: Line 224 : Warning: Unsupported feature "unknown"
I/chromium(12117): [INFO:CONSOLE(224)] "Warning: Unsupported feature "unknown"", source: file:///android_asset/www/app/toPDF/pdf.worker.js (224)
D/CordovaLog(12117): file:///android_asset/www/app/toPDF/pdf.js: Line 224 : Warning: Unsupported feature "unknown"
I/chromium(12117): [INFO:CONSOLE(224)] "Warning: Unsupported feature "unknown"", source: file:///android_asset/www/app/toPDF/pdf.js (224)
D/CordovaLog(12117): file:///android_asset/www/app/toPDF/pdf.worker.js: Line 224 : Warning: Indexing all PDF objects
I/chromium(12117): [INFO:CONSOLE(224)] "Warning: Indexing all PDF objects", source: file:///android_asset/www/app/toPDF/pdf.worker.js (224)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. At the very least, you need to provide the PDF file for us to debug; either as a link, or [uploaded to GitHub](https://github.com/blog/2061-attach-files-to-comments).

**Comment by timvandermeij** [comment]
I'm also a bit confused here. You say that you are using jsPDF (which is a *different project* than PDF.js), so how exactly does PDF.js come into play here?

**Comment by yurydelendik** [comment]
> PDFJS.getDOcument(withBinaryStringValue)

See also https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L223, and make sure you are not passing binary string instead of URL. Are you sure the above is not  `PDFJS.getDocument({data: withBinaryStringValue})`?

**Comment by TheVedhaGuy** [comment]
@Snuffleupagus do you mean the PDf.js file itself? Or the actual PDF that is generated (because it doesn't generate anything).
@timvandermeij Well i needed jsPDF to get the datauri output by using jspdfObject.output('datauri')

then i used PDFJS.get(jspdfObject.output('datauri')) to display the document.

@yurydelendik Correct me if i am wrong, but isn't datauri a base64 encoded string? Unless that is the same as a binary string.

Thanks for your patience and help guys,

**Comment by yurydelendik** [comment]
> Correct me if i am wrong, but isn't datauri a base64 encoded string? Unless that is the same as a binary string.

If withBinaryStringValue is a datauri with base64 encoded string (the variable name is misleading), then XHR on legacy WebKit and IE browsers don't support reading from the data URI scheme. Feed decoded binary data (typed array, js array or string) to the getDocument using the syntax I proposed in the comment above.

**Comment by TheVedhaGuy** [comment]
Alright, so I found a method that converts base64 to a binary string. After converting, I pass that array into getDocument. The file generates on the PC but not on android. Also, some methods for PDFJS are showing as "unresolved'. Is that because i am lacking libraries?  I only included pdf.js and pdf.worker.js after building these files. To give you a better idea of whats going on, i'll post the cose here
$scope.toPDF = function(){

                    var doc = new jsPDF();
                    var source = $('#test').html();
                    doc.fromHTML(source, 15, 15, {
                        'width': 170
                    });
                    var PAGE_TO_VIEW = 1;
                    var SCALE = 1.0;
                    var pdfValue = doc.output('datauri');
                    var pdfAsArray = convertDataURIToBinary(pdfValue);
                    window.open(pdfValue);
                   // window.open("app/recent_transactions/recent_transactions.html");
            //PDFJS.getDocument('recent_transactions.html');
                    PDFJS.getDocument(pdfAsArray).then(function(pdfDocument){
                        return pdfDocument.getPage(PAGE_TO_VIEW).then(function (pdfPage) {
                            // Creating the page view with default parameters.
*****PDFPageView is unresolved type**********
                            var pdfPageView = new PDFJS.PDFPageView({
                                id: PAGE_TO_VIEW,
                                scale: SCALE,
                                defaultViewport: pdfPage.getViewport(SCALE)
                                // We can enable text/annotations layers, if needed
                                //textLayerFactory: new PDFJS.DefaultTextLayerFactory(),
                                //annotationsLayerFactory: new PDFJS.DefaultAnnotationsLayerFactory()
                            });
                            // Associates the actual page with the view, and drawing it
**setPdfPage is also an unresolved type.
                            pdfPageView.setPdfPage(pdfPage);
                            return pdfPageView.draw();
                        });
                    });
        };
        var BASE64_MARKER = ';base64,';

        function convertDataURIToBinary(dataURI) {
            var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
            var base64 = dataURI.substring(base64Index);
            var raw = window.atob(base64);
            var rawLength = raw.length;
           var array = new Uint8Array(new ArrayBuffer(rawLength));

            for(var i = 0; i < rawLength; i++) {
               array[i] = raw.charCodeAt(i);
            }
            return array;
        };


**Just a note**
i found the code following getDocument online. It pretty much filled the contents of a blank pdf page that was generated before I added that section of code.

**Comment by yurydelendik** [comment]
To deal with legacy browsers you need to include web/compatibility.js

**Comment by TheVedhaGuy** [comment]
I tried adding the compatibility but nothing changes. I ended up displaying the PDF in a canvas on the HTML page but it would be optimal if I can get a separate window to open.

**Comment by yurydelendik** [comment]
Actually, since it's custom solution, please provide link to the complete code and OS and browser versions. I'll close as incomplete for now. Please provide all information requested at https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md to reopen.
