### ISSUE TITLE
Cannot read property 'parentElement' of undefined

### ISSUE THREAD

**Issue by eaxle** [mozilla/pdf.js#6490]
Hi,
I have used your highlight functions (getHightlightCoords and showHighlight) for annotation in pdf.js.The function works well.I have called the same Highlight function for every saved coordiantes and page number. 
When I highlight a selected part and zoom in and scroll down for sometime and call the function with the saved data, it sometimes shows 
"Cannot read property 'parentElement' of undefined" message in the console, page(canvas gets undefined.)and it doesn't highlight

**Comment by eaxle** [comment]
also when i highlight the initial page of pdf and scroll down to the last, the highlight disappears

**Comment by timvandermeij** [comment]
Which version of PDF.js do you use? Could you setup a minimal example (on jsFiddle or jsBin for example) that demonstrates the problem?

**Comment by timvandermeij** [comment]
Closing as incomplete as there is not enough information here to work with. On top of that `getHightlightCoords` and `showHighlight` do not seem to exist in the codebase. This issue can be reopened if the information requested above is provided.
