### ISSUE TITLE
PDFJS render CCITTFaxStream slowly.

### ISSUE THREAD

**Issue by hhstkh** [mozilla/pdf.js#6493]
I have used PDFJS to render PDF file but it rendered slowly. This pdf contains a CCITTFaxStream.
Here is time log to render this page.
Info: Bad two dim code
pdf.worker.js:217 Info: page=1 - getOperatorList: time=4783ms, len=0

Could we improve performance of pdf.js in this case?

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md; paying special attention to the *first* paragraph.
At the very least, you need to provide the PDF file for us to debug; either as a link, or [uploaded to GitHub](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by yurydelendik** [comment]
Based on given information. The getOperatorList timing does not reflect the true numbers for the performance since it includes data transfer time (especially for large pdfs), are you testing it locally or requesting from a remote server (the browser you are using will matter too). It does not clear what does improve performance mean in this case (network transfer speed or data parsing). Notice that native PDF reader e.g. OSX Preview and Adobe Reader might take time to render huge images, e.g. 10208x13200 bitmap (1200DPI) is too big to be hosted on the web and really hard to any reader (you can notice that during zooming operations). 

Closing as incomplete, it can be reopened with PDF attached and system details.

See also:
- https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js
- http://brendandahl.github.io/pdf.js.utils/browser/
- https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster
- https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by hhstkh** [comment]
This is pdf file to test: https://drive.google.com/open?id=0BzoKdQwBinAnXzVJcmdVZjBmbkE.
This file has only one page but it has high DPI. I am testing it locally.
Could you suggest me how to improve performance for rendering it?

**Comment by timvandermeij** [comment]
Renders within a second for me on Windows 10 x64. Make sure you use the latest version of PDF.js.

**Comment by hhstkh** [comment]
I have downloaded the latest version of pdf js **(v1.1.469)**. I used IIS Manager to run it on localhost.
I set the starting time at:
```javascript
PDFJS.getDocument = function getDocument(src,
                                         pdfDataRangeTransport,
                                         passwordCallback,
                                         progressCallback) {
  PDFJS.startTime = Date.now();
  var task = new PDFDocumentLoadingTask();
  ...
}
```
 and the ending time  at:
```javascript
endDrawing: function CanvasGraphics_endDrawing() {
      this.ctx.restore();
      CachedCanvases.clear();
      WebGLUtils.clear();

      if (this.imageLayer) {
        this.imageLayer.endLayout();
      }

      info('endDrawing time = ' +
               (Date.now() - PDFJS.startTime) + 'ms');
 }
```
 Total time for rendering this file is about 5s. My computer's hardware: Window 7x 64, RAM: 12 GB, Processors: Intel Core i5. Your rendering time is only **a second**. So could you suggest me about this problem?

**Comment by yurydelendik** [comment]
What is you browser and its version? The getDocument starts loading PDF from your localhost -- looks like you are measuring time to download PDF from localhost in addition to rendering. (See if https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L648 will be more useful)

There is nothing we can do without more specific deployment / example, see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by hhstkh** [comment]
I use **Chrome browser** and its version is **45.0.2454.101 m**. I have showed logging time at **render** function:

```javascript
 render: function PDFPageProxy_render(params) {
      var stats = this.stats;
      stats.time('Overall');
      ....
    function complete(error) {
       ...
        stats.timeEnd('Rendering');
        stats.timeEnd('Overall');

        console.log(stats.toString());
      }
}
```
**This is logging time**:
Page Request 20ms
Rendering    3284ms
Overall      3304ms

Could you suggest me how to improve performance in this case? 
Thanks.

**Comment by hhstkh** [comment]
In order to follow this issue. I summarise as follows:
I used the latest version of pdf js **(v1.1.469)**. I deloyed it to IIS Manager and tested it on **localhost** but pdf.js renders slowly.

Here is detail information:
- File for testing: https://drive.google.com/open?id=0BzoKdQwBinAnXzVJcmdVZjBmbkE
- System detail: my computer's hardware: **Window 7x 64, RAM: 12 GB, Processors: Intel Core i5. I use Chrome browser and its version is 45.0.2454.101 m**


I have logged time at render function of PDF.JS as follows:
```javascript
 render: function PDFPageProxy_render(params) {
      var stats = this.stats;
      stats.time('Overall');
      ....
    function complete(error) {
       ...
        stats.timeEnd('Rendering');
        stats.timeEnd('Overall');

        console.log(stats.toString());
      }
}
```

This is logging time:
Page Request: 20ms
Rendering: 3284ms
=> Overall: 3304ms

Could you possibly review this again and suggest me how to improve performance in this case? Thanks

**Comment by yurydelendik** [comment]
> Could you possibly review this again and suggest me how to improve performance in this case?

As suggested above, reduce DPI of the scanned images to reasonable size (e.g. 300 DPI, but for the web 150DPI as enough). For comparison your document is scanned at 1200DPI.

See also https://acrobatusers.com/tutorials/how-optimize-your-pdf-file and https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster .

**Comment by s2ramana** [comment]
Yury,

With this same PDF, other PDF viewers such as Adobe Reader, Edge's PDF Viewer, and Chrome's PDF viewer scale down the BMP i.e. 25% automatically in order to render it quickly. It would be more robust if PDF.js could do this as well.

Regards,
Siva
