### ISSUE TITLE
not marked as incompatible with Firefox version 35 or greater

### ISSUE THREAD

**Issue by lsloan** [mozilla/pdf.js#6495]
The version of the extension I have installed (v1.0.277.1-signed) has the following text in its description:

"Note: PDF.js is part of the Firefox since version 19. The extension is mostly used to bring newer version of the PDF.js library to the older Firefox version. It will be marked as incompatible starting from the Firefox version 35."

However, my Firefox version 41.0.1 doesn't recognize the extension as incompatible.  I've gone through several updates of Firefox since version 35 and not one of them warned me that the extension is incompatible.  I've had updates warn me about other extensions, but not this one.  I don't use Firefox regularly, but I've noticed recently that it couldn't display PDFs any longer.  On a whim, I disabled this extension and now I can view PDFs in Firefox again.  

**Either Firefox or the extension should have warned me about the incompatibility.**

FYI, I'm using Firefox version 41.0.1 with OS X 10.8.5.

**Comment by yurydelendik** [comment]
Please uninstall the extension (restart might be required). Firefox 19 and up has embedded PDF viewer, which is based on up-to-date PDF.js. If you disabled the embed PDF viewer using shumway.disabled configuration option or set different viewer in Options->Applications, enable Firefox to view PDFs. You can also check mimeTypes.rdf file, for correct mime type bindings if files from file system is not handled correctly. (If nothing helps try creating a new Firefox profile using profile manager). Closing as answered.

**Comment by yurydelendik** [comment]
Changed https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-extensions
