### ISSUE TITLE
Blurry PDF tiling patterns with huge xstep/ystep

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6496]
Most of the text is blurry in [GNK Studie in Cijfers 2015.pdf](https://github.com/mozilla/pdf.js/files/6870/GNK.Studie.in.Cijfers.2015.pdf) (source: http://www.uu.nl/bachelors/sites/default/files/editor/gnk/documenten/GNK%20Studie%20in%20Cijfers%202015.pdf).

The text is drawn using a tiling pattern ([PDF spec, 8.7.3 Tiling patterns](https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdfPDF8.7.3)) with cells of size 99999x99999... PDF.js [shrinks that to 3000x3000](https://github.com/mozilla/pdf.js/blob/82f73dfed51fd39df7b9df5cd422173d30ad427d/src/display/pattern_helper.js#L339-L347), which results in the blurred text.

```
14 0 obj
<< /Type /Pattern /PatternType 1 /PaintType 1 /TilingType 2
/Resources 13 0 R
/BBox [0 0 748.734 682.715]
/XStep 99999
/YStep 99999
/Matrix [1 0 0 -1 0.000 688.819]
```

Expected (viewed using PDFium):
![pdfium](https://cloud.githubusercontent.com/assets/1365071/10250948/1252384e-692e-11e5-9442-a2ca206ef3bc.png)
PDF.js:
![max-pattern-size-3k](https://cloud.githubusercontent.com/assets/1365071/10250955/174f9b7a-692e-11e5-93a8-138dc3436c57.png)
If I set [`MAX_PATTERN_SIZE = 16000;`](https://github.com/mozilla/pdf.js/blob/82f73dfed51fd39df7b9df5cd422173d30ad427d/src/display/pattern_helper.js#L291), then it's less blurry but still illegible:
![max-pattern-size-16k](https://cloud.githubusercontent.com/assets/1365071/10250965/1e37487a-692e-11e5-9afe-67a61bf14d36.png)

If I set `MAX_PATTERN_SIZE` to 99999 (or even lower 20000), then the gradient is not painted at all... Obviously we cannot create a full canvas of 100k x 100k, but we should still be able to draw this somehow.

**Comment by yurydelendik** [comment]
I see a clip operation above the tiling pattern -- we probably shall optimize this case (rectangle clip + tiling pattern fill)

**Comment by Rob--W** [comment]
Fyi, I already have a patch for this issue (which solves the issue by
constraining the scale if the xstep/ystep exceeds the limit).

This caused a regression in another file, but I didn't find the time to
investigate that yet.
