### ISSUE TITLE
Text block in PDF-to-text conversion being broken up into multiple lines

### ISSUE THREAD

**Issue by sid-thakur** [mozilla/pdf.js#6504]
Hi, 
I am trying to recover text from reference section from a pdf article, but the text block sometimes break up into multiple lines. A somewhat related issue might be #4629 

Incorrect text splitting: 
![pdfjs_text_splitting_issue](https://cloud.githubusercontent.com/assets/5922613/10287751/e7bb0066-6b62-11e5-8f41-7bf13c3f0c82.png)

Correct text splitting:
![pdfjs_correct_text_splitting](https://cloud.githubusercontent.com/assets/5922613/10287785/205b542a-6b63-11e5-8b87-f561a0ce22d6.png)

I would like to recover text without extra line delimiters. Below is code I use to get text from pdf:

```
// PDFJS.version = '1.0.85';
// PDFJS.build = '094d0e2';

context.getPDFText = function pico_getPDFText() {

	// Variable to hold PDF text data
	var pdfTextContent = '';

  	// pdfObj: global reference to PDF file object
  
	// Get each page and extract text content of the page
	for (var p = 1; p <= context.pdfObj.numPages; p++) {

		// Asynchronous processing
		context.pdfObj.getPage(p).then(function(res) {

			var content = res.getTextContent().then(function(textContent) {
				var promise = new Promise(function(resolve, reject) {

					for (var i = 0; i < textContent.items.length; i++) {
						var line = textContent.items[i].str.trim().toLowerCase();

						if ((line.indexOf('reference') > -1 || line.indexOf('bibliograph') > -1) &&
							(line === 'references' || line === 'bibliography')) {
                          	// print references / bibliographic citations
							console.log(line);
						}
					}

				});

			});
		});
	}
}
``` 
Thank you.
Sid

**Comment by Snuffleupagus** [comment]
Closing as incomplete, please provide a link to the PDF file (or attach it to the issue, since GitHub now supports that) in order to re-open the issue.
