### ISSUE TITLE
Pdf.js : Barcode not rendering in chrome v44 with windows xp

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6511]
I embedded PDF.js  in my Web Application. Now issue is when I view the PDF document in Windows XP barcode is not getting rendered in barcode format but in text format. 

The same is working fine in Windows 7. I have attached both windows XP and windows 7 screenshots for your reference. I have downloaded pdfjs-1.0.1040-dist. I have copying the code in css file for your reference

@font-face {
  font-family: '3of9Barcode';
  src: url("fonts/3OF9NEW.TTF") format("truetype"); 
}
@font-face {
  font-family: '3 of 9 Barcode';
  src: url("fonts/3OF9NEW.TTF") format("truetype"); 
}

So How Can i fix this barcode rendering issue on Windows XP. Please revert back.

![untitled2](https://cloud.githubusercontent.com/assets/12855547/10335674/1244eb18-6d10-11e5-95ca-490685c9c3c0.png)
![untitled](https://cloud.githubusercontent.com/assets/12855547/10335675/124e02f2-6d10-11e5-8715-5518f7cbe839.png)

**Comment by timvandermeij** [comment]
Might be a duplicate of #6340 and #6448. Try using the latest version of PDF.js to see if that makes a difference (1.1.513 as of writing, see https://github.com/mozilla/pdfjs-dist).

**Comment by ArjunPatil** [comment]
I tried this on 1.1.513 version    but it wont work on xp with chrome browser.

**Comment by ArjunPatil** [comment]
There is Warning occured while loading the PDF file. 

![dms_2015-10-9_10-9-23_no-00](https://cloud.githubusercontent.com/assets/12855547/10386891/cf1452f0-6e79-11e5-9e39-4ed3e7ff2077.jpg)
![dms_2015-10-9_10-6-44_no-00](https://cloud.githubusercontent.com/assets/12855547/10386892/cf1b20ee-6e79-11e5-9372-f483da70c792.jpg)

**Comment by yurydelendik** [comment]
To understand the conversation above: the Chrome fails to load a custom font provided by you, is it correct? If so, please provide a font that does not fail to load on Chrome.

**Comment by ArjunPatil** [comment]
Issue resolved ...

just put embeded css in Viewer.html Body tag as follow:

style="font-family: arial,times,sans-serif,courier,'3 of 9 Barcode';"
