### ISSUE TITLE
table borders are not in thick format and broken in between lines

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6512]
I embedded PDF.js in my Web Application. The image quality is poor, table borders are not thick enough and broken in between lines.

I have downloaded pdfjs-1.0.1040-dist. I am attaching the relevant code for your reference.

var viewport = pdfPage.getViewport(2);
				// Use the same hack we use for high dpi displays for printing to get
				// better output until bug 811002 is fixed in FF.
				console.log('vp: wt='+viewport.width+' ht='+viewport.height);
				var PRINT_OUTPUT_SCALE =2;
				var canvas = document.createElement('canvas');
				canvas.width = Math.floor(viewport.width) * PRINT_OUTPUT_SCALE;
				canvas.height = Math.floor(viewport.height)* PRINT_OUTPUT_SCALE;
				 // The rendered size of the canvas, relative to the size of canvasWrapper.
				//canvas.style.width = (PRINT_OUTPUT_SCALE * Math.floor(viewport.width)) + 'px';
				//canvas.style.height = (PRINT_OUTPUT_SCALE * Math.floor(viewport.height)) + 'px';
				canvas.style.width = (PRINT_OUTPUT_SCALE * 100)+'%';
				canvas.style.height = (PRINT_OUTPUT_SCALE * 100)+'%';
		
				
			var cssScale = 'scale(' + (1 / PRINT_OUTPUT_SCALE) + ', ' +	(1 / PRINT_OUTPUT_SCALE) + ')';
			//var cssScale = 'scale(' + (1) + ', ' +	(1) + ')';
									//width				//height	
			CustomStyle.setProp('transform' , canvas, cssScale);
			CustomStyle.setProp('transformOrigin' , canvas, '0% 0%');

				var printContainer = document.getElementById('printContainer');
				var canvasWrapper = document.createElement('div');
				canvasWrapper.style.width = (viewport.width/PRINT_OUTPUT_SCALE) + 'pt';
				canvasWrapper.style.height = (viewport.height/PRINT_OUTPUT_SCALE) + 'pt';
				
				canvasWrapper.style.pageBreakAfter = 'always';
				canvasWrapper.appendChild(canvas);
			
				printContainer.appendChild(canvasWrapper);

				canvas.mozPrintCallback = function(obj) {
					var ctx = obj.context;

					ctx.save();
					ctx.fillStyle = 'rgb(255, 255, 255)';
					ctx.fillRect(0, 0, canvas.width, canvas.height);
					ctx.restore();
					ctx.scale(PRINT_OUTPUT_SCALE, PRINT_OUTPUT_SCALE);

					var renderContext = {
							canvasContext: ctx,
							viewport: viewport,
							intent: 'print'
					};

					pdfPage.render(renderContext).promise.then(function() {
						// Tell the printEngine that rendering this canvas/page has finished.
						obj.done();
					},

![dms_2015-10-7_16-55-19_no-00](https://cloud.githubusercontent.com/assets/12855547/10336142/38ccddc8-6d14-11e5-8622-64afc161b2e2.jpg)

**Comment by timvandermeij** [comment]
We need the PDF file to reproduce the issue. It might be an image decoding problem.

**Comment by ArjunPatil** [comment]
you can check the 2 files attached for reference.

**Comment by ArjunPatil** [comment]
Hello Van.Attaching the PDF file you requested.PFA.

​Thanks and Regards,
Arjun Patil


 

On Wed, 10/07/2015 10:35 PM, Tim van der Meij &lt;notifications@github.com&gt; wrote:
> We need the PDF file to reproduce the issue. It might be an image decoding problem.


—
> Reply to this email directly or view it on GitHub.



  
 *

**Comment by timvandermeij** [comment]
@ArjunPatil You cannot attach files by e-mail. You have to upload the file on GitHub.

**Comment by ArjunPatil** [comment]
@timvandermeij, can you share your other email id with me so i can send PDF file.I'm unable to upload PDF on GitHub.

**Comment by timvandermeij** [comment]
You can just drag-and-drop a PDF file into the box where you type your message. Alternatively we ask users to upload a PDF file on Dropbox, Google Drive or another file sharing service and post the link here.

**Comment by ArjunPatil** [comment]
@timvandermeij  please find the documents on following link
https://www.dropbox.com/sh/pdu40fzl5ti8hhv/AACefuSmP7e2aZMd6asWYgAfa?dl=0

**Comment by timvandermeij** [comment]
This renders *exactly* in PDF.js as it does in Adobe Acrobat, so I don't see any issues here. The PDF itself just contains a poor quality image: nothing we can do about that. Closing as invalid.
