### ISSUE TITLE
print quality different on two workstations

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6513]
we are getting one poor image quality and one good image quality on two workstations when they are printing the same document using pdfviewer.js

I am attaching the code for your reference.

var viewport = pdfPage.getViewport(2);
// Use the same hack we use for high dpi displays for printing to get
// better output until bug 811002 is fixed in FF.
console.log('vp: wt='+viewport.width+' ht='+viewport.height);
var PRINT_OUTPUT_SCALE =2;
var canvas = document.createElement('canvas');
canvas.width = Math.floor(viewport.width) * PRINT_OUTPUT_SCALE;
canvas.height = Math.floor(viewport.height)* PRINT_OUTPUT_SCALE;
// The rendered size of the canvas, relative to the size of canvasWrapper.
//canvas.style.width = (PRINT_OUTPUT_SCALE * Math.floor(viewport.width)) + 'px';
//canvas.style.height = (PRINT_OUTPUT_SCALE * Math.floor(viewport.height)) + 'px';
canvas.style.width = (PRINT_OUTPUT_SCALE * 100)+'%';
canvas.style.height = (PRINT_OUTPUT_SCALE * 100)+'%';

        var cssScale = 'scale(' + (1 / PRINT_OUTPUT_SCALE) + ', ' + (1 / PRINT_OUTPUT_SCALE) + ')';
        //var cssScale = 'scale(' + (1) + ', ' +    (1) + ')';
                                //width             //height    
        CustomStyle.setProp('transform' , canvas, cssScale);
        CustomStyle.setProp('transformOrigin' , canvas, '0% 0%');

            var printContainer = document.getElementById('printContainer');
            var canvasWrapper = document.createElement('div');
            canvasWrapper.style.width = (viewport.width/PRINT_OUTPUT_SCALE) + 'pt';
            canvasWrapper.style.height = (viewport.height/PRINT_OUTPUT_SCALE) + 'pt';

            canvasWrapper.style.pageBreakAfter = 'always';
            canvasWrapper.appendChild(canvas);

            printContainer.appendChild(canvasWrapper);

            canvas.mozPrintCallback = function(obj) {
                var ctx = obj.context;

                ctx.save();
                ctx.fillStyle = 'rgb(255, 255, 255)';
                ctx.fillRect(0, 0, canvas.width, canvas.height);
                ctx.restore();
                ctx.scale(PRINT_OUTPUT_SCALE, PRINT_OUTPUT_SCALE);

                var renderContext = {
                        canvasContext: ctx,
                        viewport: viewport,
                        intent: 'print'
                };

                pdfPage.render(renderContext).promise.then(function() {
                    // Tell the printEngine that rendering this canvas/page has finished.
                    obj.done();
                },

these are printouts taken on different machines...

![dms_2015-10-7_17-34-48_no-00](https://cloud.githubusercontent.com/assets/12855547/10336918/c13f62fc-6d19-11e5-9003-f54ffcf75e01.jpg)
![dms_2015-10-7_17-34-20_no-00](https://cloud.githubusercontent.com/assets/12855547/10336917/c0fc9332-6d19-11e5-97a7-724a1d02d99a.jpg)

**Comment by timvandermeij** [comment]
We really need the PDF file to reproduce this. It might be a driver issue.

**Comment by timvandermeij** [comment]
Closing as incomplete until the file request above is posted.
