### ISSUE TITLE
PDFJS render CCITTFaxStream slowly

### ISSUE THREAD

**Issue by hhstkh** [mozilla/pdf.js#6514]
I have used PDFJS to render PDF file but it rendered slowly. This pdf contains a CCITTFaxStream.
Here is log timining to render this page.
Info: Bad two dim code
pdf.worker.js:217 Info: page=1 - getOperatorList: time=4783ms, len=0
This is pdf file to test: https://drive.google.com/open?id=0BzoKdQwBinAnXzVJcmdVZjBmbkE.
This file has only one page but it has high DPI. I am testing it locally.
Could you suggest me how to improve performance for rendering it?

**Comment by timvandermeij** [comment]
As mentioned in the other issue where you posted the same question, this renders within a second for me on Windows 10 x64. Make sure that you are using the latest PDF.js version. To improve performance, do not use 10000x13000 pixel images, but reduce the size of those images for web.
