### ISSUE TITLE
PDFDataRangeTransport appears to require 65536-byte chunks

### ISSUE THREAD

**Issue by adammw** [mozilla/pdf.js#6517]
I'm attempting to provide a custom transport which internally uses the fetch() api to grab the data from the PDF and therefore returns variable-sized chunks when reading. This doesn't seem to be documented anywhere, I just hitting [this](https://github.com/mozilla/pdf.js/blob/367794f0c73a10abf0b8452f58012f593153eae6/src/core/chunked_stream.js#L66) assertion, and I don't quite see how I can get this from PDFDataRangeTransport as it's used internally within the worker (or at least as far as I can tell). I can see a lot of issues from @bh213 about chunking/streaming PDFs, but that was back in 2014 so I'm not sure what the state of pdf.js is at the moment. Since PDF.js already has code to handle putting chunks together, it'd really help if the consumer of the API didn't have to do this, and PDF.js could just handle variable-sized chunks.

**Comment by timvandermeij** [comment]
I'm not sure if this will help you, but recently #6568 landed, allowing custom solutions to provide a range chunk size of their wish. Now that that is an API setting, it should make life easier for custom solutions, however since you want to have variable-sized chunks I'm not sure if it we be of much use for you.

**Comment by Snuffleupagus** [comment]
> I'm attempting to provide a custom transport which internally uses the fetch() api to grab the data from the PDF and therefore returns variable-sized chunks when reading.

Note that the Fetch API has been officially supported for a couple of years now.
Furthermore, given https://github.com/mozilla/pdf.js/issues/6517#issuecomment-152830106 and the age of this issue, should this be closed now?
