### ISSUE TITLE
Add Line Number Attribute to Every Div Rendered from pdf.js

### ISSUE THREAD

**Issue by pdfjsexplorer** [mozilla/pdf.js#6525]
Hello All, 
Can Anybody plz guide how can we mark the line number of every line while rendering the pdf in coordination with that of Original pdf lines.

To elaborate, [<div data-canvas-width="439.021448245499" ] is given by pdf.js, i want to get the similar attribute for each line for ex.[<div data-canvas-LINE_NUMBER=1] and so on in the continued manner.

**Comment by timvandermeij** [comment]
You will have to modify the text layer builder component (https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js) and keep line counts yourself, however that is not a trivial task as PDFs do not contain line numbers as far as I know, so you would have to determine where the end of a line is (for example by checking the drawing coordinates). Closing as out of scope for the PDF.js library itself though: for assistance with this, please use IRC or the mailing list, as this issue tracker is only used for tracking bugs in PDF.js.

**Comment by pdfjsexplorer** [comment]
Thanks for the reply, 
Actually Basic issue which i am facing is, while rendering the pdf in different screen resolutions, the top Style of every div changes, as it is based on pixel based, can it be changed on percentage basis, or can we render the pdf in some default screen resolution. ex.1440*900, Plz let   me  know if there is any alternative solution.

**Comment by timvandermeij** [comment]
Everything is done in pixels, so switching to percentages will be hard. However, there is https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L181-L182 you might need for your change.

**Comment by pdfjsexplorer** [comment]
Hi, Thanks again for reply, will look into this line of code in-depth.
i want also to restrict the search (ctrl+F) [find bar] functionality to single page. or else provide page number while searching. any suggestion will be welcome.

Thanks in advance.

**Comment by timvandermeij** [comment]
There is https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js. Please look into the `/web` folder as most code you will need is there. Since we're getting off-topic here, please use IRC or the mailing list for new questions.
