### ISSUE TITLE
Safari loads a lot of base64 fonts when rendering, slows down page load

### ISSUE THREAD

**Issue by jakubfiala** [mozilla/pdf.js#6529]
Hey everyone,

I have the weirdest problem on Safari:

Unlike Chrome/FF, when loading any PDF via pdf.js, Safari seems to load a *ludicrous* amount of base64-encoded fonts. Many of them are identical to each other, as seen in the screenshot from Viewer/Safari dev tools below – e.g. the ones that are 1.09kB.

![screen shot 2015-10-15 at 11 35 30](https://cloud.githubusercontent.com/assets/5719805/10511459/2c75c8dc-7331-11e5-8c80-15b9a9aeb1a5.png)

Now, Viewer seems OK with this, but I'm working on a web app with some more complex fonts, which seem to take insane amounts of time to load, thus blocking other stuff that needs to load after the PDF renders.

Is the base64 font loading a Safari-only feature or a bug? Also, why are the fonts getting loaded multiple times?

*Note: I'm using Safari 9.0 | Chrome 45 | FF 40 on OS X 10.11.*

Thanks!

**Comment by brendandahl** [comment]
The first and second page use 14 fonts combined. Safari doesn't currently support the font loading api so we use a trick that loads an empty fake font for each of the above 14 fonts to figure out when the font is really loaded, so this puts us at 28 fonts. See https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js for more.
