### ISSUE TITLE
Question: What kind of promise library is used? looking for finally()

### ISSUE THREAD

**Issue by dman777** [mozilla/pdf.js#6534]
What kind of promise library is used? looking for finally() or a similar method.

**Comment by Snuffleupagus** [comment]
PDF.js attempts to use the native Promise implementation available in modern browsers. If a browser doesn't support Promises, we use our own polyfill based on the Promises/A+ specification; please see https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L1089-L1407.

As far as I can tell, `finally` is *not* part of either the [Promise specification](https://promisesaplus.com/) or the [ECMAScript specification](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-objects), but rather an extension used in some libraries. Based on a cursory look at some libraries that implement `finally`, I'd image that you can achieve the same result by doing e.g.
```javascript
function onFinally(data) {
  // Code to be executed when a promise is either resolved,
  // or rejected.
}
promise.then(onFinally, onFinally);
```
Closing as answered.
