### ISSUE TITLE
Not working in a chrome app

### ISSUE THREAD

**Issue by mug3n** [mozilla/pdf.js#6537]
The methods of the PDFJS object do not get initialized in a chrome app, the only attribute it has is workerSrc: 
Object {workerSrc: "chrome-extension://obmbcjpnenmhndledcghbbiicnfbcpmh/scripts/pdfjs/src/pdf.worker.js"}.
I've tried declaring the worker variable, leaving it undefined, moved the include script up and down the document, nothing seems to work. The result is obviously that PDFJS.getDocument is not a function.

**Comment by Rob--W** [comment]
Can you describe how you're trying to use PDF.js in a Chrome app? E.g. by sharing a zip file with your app.

**Comment by mug3n** [comment]
As per the tutorial I found on the web:
downloaded the whole package, included the pdf.js script into my app.

**Comment by Rob--W** [comment]
@mug3n It's difficult to debug without seeing your project, so please share all necessary details for debugging the issue.

**Comment by mug3n** [comment]
window.html:
<html>
<head>
...
</head>
<body>
....
<script src="scripts/pdfjs/src/pdf.js"></script>
<script src="scripts/app.js"></script>
</body>
</html>

and either in app.js or from the console, when I check the PDFJS object, it has no methods at all: Object {workerSrc: "chrome-extension://obmbcjpnenmhndledcghbbiicnfbcpmh/scripts/pdfjs/src/pdf.worker.js"} so naturally calling PDFJS.getDocument(...) errors with PDFJS.getDocument is not a function.
It might be that I'm not using the lib correctly.

**Comment by mug3n** [comment]
The app is polymer, so it's say 50 mb of data in files, you sure you want me to upload it here? If I'm even able to.

**Comment by Rob--W** [comment]
> The app is polymer, so it's say 50 mb of data in files, you sure you want me to upload it here? If I'm even able to.

50MB is quite a lot.. Try removing the unnecessary bits. If you are not able to do that, then go ahead and share all of it.

**Comment by mug3n** [comment]
It's the polymer elements I'm using, so it won't work without them. I'm not home at the moment, is it okay if I upload it when I get home from work or tonight?

**Comment by mug3n** [comment]
The ironic part is, it works in a webview natively and it's the same pdf.js that does it. That's how I managed to dodge the problem for now. But I'd prefer using the lib myself.

**Comment by Rob--W** [comment]
Closing issue since I haven't received anything. If you still have a problem with integrating PDF.js in your Chrome app, share a link to an example that shows your problem.
