### ISSUE TITLE
PDF.js script hosted on different domain

### ISSUE THREAD

**Issue by Znack** [mozilla/pdf.js#6538]
When I load script from the same domain as webpage 
```
<script type="text/javascript" src="../js/pdf.js"></script>
```
everything works great, but when I use AWS S3 as CDN pdf.js doesn't even load pdf files (maybe there is no rights to send cross domain request?
```
<script type="text/javascript" src="http://my-bucket.s3.amazonaws.com/js/pdf.js"></script>
```

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr.
Closing as answered.

**Comment by Znack** [comment]
@Snuffleupagus my question was not about PDF file on different domain, but about pdf.js script, my AWS S3 server support CORS headers. My question more about: if we will use CDN for pdf.js script it stop working

**Comment by yurydelendik** [comment]
It is still about CORS and PDF located on different server. But now you have three places to look at: viewer app, CDN server and PDF host. Please provide an exact test case, so we can troubleshoot it.

**Comment by Znack** [comment]
My main goal is allow my clients to embed my PDF files to their websites. So I have AWS S3 storage where located my PDF files and all scripts (my custom js-script which initialize pdf.js and pdf.js itself) and then I give my clients snippet something like this:
```
<script type="text/javascript" src="http://my-bucket.s3.amazonaws.com/js/my-custom.js"></script>
<script type="text/javascript" src="http://my-bucket.s3.amazonaws.com/js/pdf.js"></script>

// this should be located whenever client wants to display my PDF file
<script type="text/javascript">
    new window.MyCustomConstructor(params);
</script>
```
Then in MyCustomConstructor I call pdf.js code:
```
PDFJS.getDocument('http://my-bucket.s3.amazonaws.com/FILENAME.pdf').then(function handlePdfDocument(pdf) { 
 // this callback never fired
});
```

**Comment by yurydelendik** [comment]
@Znack I'm not familiar with AWS S3 storage API to retrive. Can you load PDF as binary data and pass it to the getDocument as Uint8Array?

**Comment by Znack** [comment]
@yurydelendik AWS S3 isn't something specific, it is just hosting where I upload my pdf file, so when I do something like `PDFJS.getDocument('http://my-bucket.s3.amazonaws.com/FILENAME.pdf')` PDFJS should get only pdf without any specific info. Please, notice when I load pdf.js script from localhost (like `<script type="text/javascript" src="../js/pdf.js"></script>`) everything is fine, but when I load it from remote origin (like `<script type="text/javascript" src="http://my-bucket.s3.amazonaws.com/js/pdf.js"></script>`) pdf.js stop working, it just doesn't resolve main promise 
```
PDFJS.getDocument(pdfAsArray).then(function (pdf) {
    // Oops, I will never execute
});
```


Anyway I tried your advice, but it doesn't work anyway, PDFJS.getDocument() still never resolve
```
    var BASE64_MARKER = ';base64,';
    function convertDataURIToBinary(dataURI) {
      var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
      var base64 = dataURI.substring(base64Index);
      var raw = window.btoa(unescape(encodeURIComponent(base64)));
      var rawLength = raw.length;
      var array = new Uint8Array(new ArrayBuffer(rawLength));

      for(var i = 0; i < rawLength; i++) {
        array[i] = raw.charCodeAt(i);
      }
      return array;
    }

var xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://my-bucket.s3.amazonaws.com/FILENAME.pdf', true);
    xhr.onload = function (e) {
        var response = e.target.response;
        var pdfAsArray = convertDataURIToBinary("data:application/pdf;base64, " + response);
        var pdfDocument;

        PDFJS.getDocument(pdfAsArray).then(function (pdf) {
            // this callback will never fired
            pdf.getPage(1).then(function handlePdfPage(page) {
            });
        })
    };
    xhr.send();
```

**Comment by Znack** [comment]
@yurydelendik I have checked the CORS headers, both pdf.js script and pdf file itself have it:
```
Access-Control-Allow-Methods:GET
Access-Control-Allow-Origin:*
Access-Control-Max-Age:8000
```

But still when I use remote storage for loading pdf.js it doesn't work :(

**Comment by ravi0999** [comment]
I have found the solution in asp.net c-sharp first convert cross domain pdf file into base64 string and then bind it into iframe.

here is the solution : https://www.dontnetcodes.com/2021/03/How-to-Bind-a-cross-domain-pdf-file-into-pdf.js-viewer-pdf.viewer-issue-solution-in-asp.net-using-csharp.html
