### ISSUE TITLE
Generated PDFs

### ISSUE THREAD

**Issue by xxcrystalcat** [mozilla/pdf.js#6539]
Hi there, 

this is more of a question than an issue, my question is, if I'm generating PDFs on the fly, how do I incorporate this into pdf.js?

**Comment by yurydelendik** [comment]
See [PDFJS.getDocument]() function https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L231 -- it's possible to load PDF as an array of bytes. Closing as answered.

**Comment by xxcrystalcat** [comment]
Thanks! :) +1:
