### ISSUE TITLE
After compatibility.js is imported. "this" becomes undefined in globally invoked functions

### ISSUE THREAD

**Issue by liuzhen2008** [mozilla/pdf.js#6542]
I loaded the compatibility.js

After that, i notice
```javascript
(function() {
    if (this === undefined) // this line becomes true.
})()
```

Does anybody know if this is the intended behavior?

Am I suppose to manually add window to all the functions that are invoked this way?

**Comment by yurydelendik** [comment]
PDF.js runs in strict mode. Using ECMAScript 5's "use strict" will do that. See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

Closing as answered.

**Comment by liuzhen2008** [comment]
@yurydelendik  I see. I didn't realize it is a thing!
