### ISSUE TITLE
The getDocument promise does not resolve when setting PDFJS.disableWorker = true

### ISSUE THREAD

**Issue by liuzhen2008** [mozilla/pdf.js#6544]
I built the pdf.js and pdf.worker.js according to the "build generic" instructions.

When I type these code into chrome console
```javascript
PDFJS.disableWorkder = true;
PDFJS.getDocument("https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf")
.then(function(resp) {
    console.log(resp);
});
```
I don't get any console logs. What am I missing here?

Judging by the network console, I don't think any HTTP requests are being sent. Is there something else I need to do other than getDocument()?

**Comment by yurydelendik** [comment]
Does the promise fail? Try:

```
PDFJS.disableWorker = true;
PDFJS.getDocument("https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf")
.then(function(resp) {
    console.log(resp);
}, function (reason) {
   console.error(reason);
});
```

Looks like you are loading from different server. See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request

**Comment by liuzhen2008** [comment]
```javascript
PDFJS.disableWorker = true;
PDFJS.getDocument("https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf")
.then(function(pdf) {
    console.log("happy");
}, function(e) {
    console.log("sad");
)};
```

This is what i have. I don't see the "sad".

**Comment by yurydelendik** [comment]
Provide the complete test online with information requested at https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by liuzhen2008** [comment]
Closing issue.

The issue is no longer reproducible. Must be something wrong on my own code. Thank you for your time.
