### ISSUE TITLE
Print quality on remote terminal

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6548]
I have a remote terminal server where in VMWare image for Windows Server 2008 has been installed. Windows server 2008 uses default SVGA graphics driver of VMWare. Now to this thick client many thin clients get connected and they are trying to print a document using pdfviewer. The print quality is coming poor both on thin client as well as the server(thick client). Now our issue is we were trying to update SVGA Graphics drivers of VMWare to improve print quality but were unable to do so. Is there a way out to improve the print quality in this scenario.

By poor quality we mean blur images or light image. 
VMWare version: 5.0

Let us know if u need any more inputs

**Comment by timvandermeij** [comment]
Please post an example PDF that comes out blurry or light. It might just be the PDF that is causing issues.

**Comment by ArjunPatil** [comment]
tim it is not just about one pdf. I can attach the pdf but the issue is coming on all pdf's. the print quality is so bad that it is barely readable. we were able to resolve the issue in windows 7 and windows XP. is there any remote terminal based settings we need to add in our code for better print quality

**Comment by timvandermeij** [comment]
There are no special settings for remote terminals in the codebase. I don't think there is anything you or we can do from the PDF.js side, it has to be fixed on the remote terminal itself. This is not anything that we can debug though, so you might need to get support from e.g. VMWare or Microsoft in this case. Closing as invalid for PDF.js though.

**Comment by ArjunPatil** [comment]
@timvandermeij 

We got good print quality on chrome 39 version on thin client terminal. is there any prerequisite for using pdf.js on thin client ? if yes please share this ASAP.
Our debug steps as of now are:
1. Windows 7 with chrome 44 and above seem to be working fine and
2. Windows Server 2008 with chrome 39 seem to be working fine

Windows Server 2008 is a thick client hosted as VMWare and terminals(thin clients - Windows Server 2008) use pdf.js for printing pdf's.

**Comment by timvandermeij** [comment]
There are no special prerequisites other than having up-to-date graphics drivers and PDF.js/browser versions. AFAIK no-one here has experience with Windows Server 2008, so since this does not appear to be a bug in PDF.js but rather a configuration issue on the client/server side, you should ask your question on Windows Server support forums or other people who know more about that environment.
