### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.

### ISSUE THREAD

**Issue by oVuHoangMinhNhat** [mozilla/pdf.js#6549]
I have received an error when i load the pdf file via http://mozilla.github.io/pdf.js/web/viewer.html in browser Google Chrome Version 46.0.2490.71 m
Actual in viewer: Page 2 and page 3 didn't render
(The PDF file is mentioned at https://drive.google.com/file/d/0B-7b1tfXVpRpenVuQS1ZXzJjMms/view?pli=1)

    Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': An object could not be cloned.
    at Error (native)
    at Object.MessageHandler.postMessage (http://mozilla.github.io/pdf.js/build/pdf.worker.js:1625:19)
    at Object.messageHandlerSend [as send] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:1590:10)
    at Object.OperatorList.flush (http://mozilla.github.io/pdf.js/build/pdf.worker.js:12747:27)
    at Object.OperatorList.addOp (http://mozilla.github.io/pdf.js/build/pdf.worker.js:12704:16)
    at next (http://mozilla.github.io/pdf.js/build/pdf.worker.js:11668:24)
    at http://mozilla.github.io/pdf.js/build/pdf.worker.js:11672:13

**Comment by timvandermeij** [comment]
I can confirm that pages 2 and 3 do not render.

**Comment by Rob--W** [comment]
To pinpoint the issue, I used the debugger as follows:

```javascript
// debugger in MessageHandler.prototype.postMessage
var port = new MessageChannel().port1;
port.postMessage(message); // error
port.postMessage(message.data.operatorList); // error
port.postMessage(message.data.operatorList.fnArray); // No error
port.postMessage(message.data.operatorList.argsArray); // error

var arr = message.data.operatorList.argsArray;
for (var i = 0; i < arr.length; ++i) try {
  port.postMessage(arr[i]);
} catch(e) { console.log(i, arr[i]); }
// prints 295, 512, 602, and for each index [Name, {MeshObj:[ ... ]}]
```

All Name objects are of type `AIMesh`, so I guess that the cause of the error is identical for all items. Using the technique that I described above, I tried to identify the cause of the serialization error:

```javascript
var arr = message.data.operatorList.argsArray[295][1].MeshObj;
// for+try-catch as above: prints index 5,7,9,11,13,15 which are arrays of Name and Dict/Array.
// The names are Node, Segment, Vertex
var arr = message.data.operatorList.argsArray[295][1].MeshObj[5];
// for+try-catch as above: prints index 1,5,9,13 which are Dict objects
```

Dict objects are intentionally not serializable, so we have to figure out why they are being posted in the first place...

```javascript
message.data.operatorList.fnArray[295]; // === 70 (which is OPS.beginMarkedContentProps)
```

We don't support marked content yet (I worked on it in #6269, but it's far from finished). If I look at `PartialEvaluator_getOperatorList`, I see that arguments for unrecognized operations are blindly passed through... I will submit a PR to ignore these operations to resolve the error.
