### ISSUE TITLE
SVG displays renders a huge scroll bar on IE

### ISSUE THREAD

**Issue by liuzhen2008** [mozilla/pdf.js#6559]
Demo: http://liuzhen2008.github.io/PDFJS-SVG-bug-demo/

This is the pdf I tested with.

https://github.com/liuzhen2008/PDFJS-SVG-bug-demo/blob/master/2_Behaviour%20Change.pdf

All the code can be seen here https://github.com/liuzhen2008/PDFJS-SVG-bug-demo

The code is exactly from examples/svgviewer.

On the console however i see these logs. (firefox)
Error in parsing value for 'stroke-miterlimit'.  Declaration dropped.
Error in parsing value for 'stroke-linecap'.  Declaration dropped.
Error in parsing value for 'stroke-linejoin'.  Declaration dropped.
Error in parsing value for 'stroke-dasharray'.  Declaration dropped.

Warning: Unimplemented method dependency
Warning: Unimplemented method beginMarkedContentProps
Warning: Unimplemented method endMarkedContent
Warning: Unimplemented method beginGroup
Warning: Unimplemented method endGroup

It also renders a huge scroll bar on IE.

**Comment by fbender** [comment]
This renders fine for me in Fx 42. May you please re-check? @liuzhen2008

**Comment by liuzhen2008** [comment]
This is interesting. Firefox at my workplace is unable to display the pdf at all. But firefox at my home can.

Still on IE 11, the pdf causes the browser to render a huge scroll bar. Should I change the issue to IE only instead?

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
