### ISSUE TITLE
Would like to fix bug https://github.com/mozilla/pdf.js/issues/6549 in version PDF.js 1.1.366 or  1.1.469

### ISSUE THREAD

**Issue by oVuHoangMinhNhat** [mozilla/pdf.js#6561]
I understand that the bug https://github.com/mozilla/pdf.js/issues/6549 is fixed in current version 1.2.30 via http://mozilla.github.io/pdf.js/web/viewer.html when load pdf file (https://drive.google.com/file/d/0B-7b1tfXVpRpenVuQS1ZXzJjMms/view?pli=1).

Could you please share solution to fix it in the stable version 1.1.366 or  1.1.469?

**Comment by timvandermeij** [comment]
You would have to make a patch from #6546 and apply it to that version, although there might be merge conflicts. However, it might be better to use https://github.com/mozilla/pdfjs-dist as that is always the most recent version of the PDF.js library and already contains this fix.

Closing as answered.
