### ISSUE TITLE
SVG display on firefox 41.0.2 text rendering problem

### ISSUE THREAD

**Issue by liuzhen2008** [mozilla/pdf.js#6563]
Demo:

http://liuzhen2008.github.io/PDFJS-SVG-bug-demo/index.html?file=test1.pdf

The pdf has been modified to remove all unnecessary distractions. Looks like the font is not rendered properly on firefox. Changing the font-family of the SVG text node will fix the rendering problem.

PDF: 
https://github.com/liuzhen2008/PDFJS-SVG-bug-demo/blob/gh-pages/test1.pdf

**Comment by fbender** [comment]
> Changing the font-family of the SVG text node will fix the rendering problem.

To which value did you change it?

**Comment by liuzhen2008** [comment]
I remove the font-family attribute of the text node completely. The texts are no longer scrambled after that. But obviously the font isn't correct.

**Comment by yurydelendik** [comment]
As I remember this problem affects only certain browser/platform. Please provide more information when reporting an issue.

**Comment by liuzhen2008** [comment]
@yurydelendik  The title says firefox 41.0.2 =)

This is the text node of the svg element generated from the pdf. The font family attribute seems to cause firefox to render the text incorrectly.
``` html
<tspan x="148.548 169.17985 195.01865 215.53305 226.96455 251.94205 275.19695 295.47645 306.0478 327.73725" y="-559.765" font-size="39.15px" font-family="g_font_1">THE BASICS</tspan>
```

**Comment by yurydelendik** [comment]
>  The title says firefox 41.0.2 =)

Firefox on Mac OSX, Windows or Linux?

**Comment by liuzhen2008** [comment]
@yurydelendik  On windows 7

**Comment by yurydelendik** [comment]
Upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1023929

**Comment by pleswi** [comment]
Same problem on Win 10Pro 64bit v1703 with FF 54.0.1 (32 bit)

**Comment by janpe2** [comment]
Pull request #8627 has fixed this issue. There are no longer glyphs that have zero width. They caused the problem in Firefox.

**Comment by yurydelendik** [comment]
Thanks. We can close it here due to workaround.
