### ISSUE TITLE
Umlaut missing

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6565]
See here:
https://dl.dropboxusercontent.com/u/133997/2015/Div/Krautreporter%20Genossenschaft%20Beitritt%20190615.pdf

On first page, display is "Wir gr nden eine Genossenschaft" but should be "Wir gründen eine Genossenschaft", i.e. "ü" is missing.

part of content stream is

  q
    1 0 0 -1 0.1377869 841.9449 cm
    BT
      10 0 0 -10 223.2601 235 Tm
      /Tc1 1 Tf
      (Wir gr\237nden eine Genossenscha) Tj
    ET
  Q

**Comment by Snuffleupagus** [comment]
From the console:
```
PDF 9ba2950e90f6e3af8c7a9fa3d03f8054 [1.4 Mac OS X 10.10.1 Quartz PDFContext / Combine PDFs] (PDF.js: 1.2.32 [WebGL]) viewer.js:6846:1
Warning: Not enough parameters for rmoveto; actual: 1, expected: 2 pdf.worker.js:224:5
Warning: Not enough parameters for rrcurveto; actual: 0, expected: 6 pdf.worker.js:224:5
```
Hence it would require that #5929 is implemented, in order for this issue to be fixed.
