### ISSUE TITLE
document_colors_disabled shouldn't escape quotes (compare-locales warning)

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/pdf.js#6569]
This in viewer.properties is an unnecessary escape.
document_colors_disabled=PDF documents are not allowed to use their own colors: \'Allow pages to choose their own colors\' is deactivated in the browser.
The localization validator compare-locales of Mozilla warns about that:
unknown escape sequence, \' at line 167, column 96 for document_colors_disabled
unknown escape sequence, \' at line 167, column 146 for document_colors_disabled

**Comment by fbender** [comment]
@Archaeopteryx The commit 5c66a23 seems to be lost in history. Would you mind creating a new PR (with `fixes #6569` or `fix #6569` in the title so the issue is auto-closed on landing)?
