### ISSUE TITLE
PDF with non-JFIF image is not rendered correctly

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6574]
File:
https://drive.google.com/file/d/0B6YhVF9p-y2AeERST1NKQmdVcnM/view?usp=sharing

Using demo viewer Chrome 47.0.2526.27 beta (64-bit) OSX 10.10.4 (14E46)

PDFJS:
<img width="399" alt="screen shot 2015-10-29 at 3 37 16 pm" src="https://cloud.githubusercontent.com/assets/1201310/10808666/f3708112-7e52-11e5-967d-3f3dbe8daa1f.png">

Chrome's buildin viewer:
<img width="307" alt="screen shot 2015-10-29 at 3 38 32 pm" src="https://cloud.githubusercontent.com/assets/1201310/10808696/26dded00-7e53-11e5-8329-956f0fd371dd.png">

Message from console:

>Warning: Unsupported header type 1885564018 (pclr)
pdf.worker.js:224 Warning: Unsupported header type 1668112752 (cmap)
pdf.worker.js:224 Warning: Unsupported header type 1885564018 (pclr)
pdf.worker.js:224 Warning: Unsupported header type 1668112752 (cmap)
pdf.worker.js:224 Warning: Unsupported header type 1885564018 (pclr)
pdf.worker.js:224 Warning: Unsupported header type 1668112752 (cmap)
pdf.worker.js:224 Warning: Unsupported header type 1885564018 (pclr)
pdf.worker.js:224 Warning: Unsupported header type 1668112752 (cmap)
pdf.worker.js:224 Warning: Unsupported header type 1885564018 (pclr)
pdf.worker.js:224 Warning: Unsupported header type 1668112752 (cmap)

**Comment by yurydelendik** [comment]
fwiw, Mac OSX Preview displays this PDF the same way as PDF.js.

**Comment by yurydelendik** [comment]
It's not a JPX image, it's JPEG. Browser is using it's internal decoder to display it:

<img width="597" alt="screen shot 2015-10-29 at 8 25 46 am" src="https://cloud.githubusercontent.com/assets/1523410/10819592/e8ecf9f0-7e16-11e5-93b4-de6ec7bea9a2.png">

**Comment by yurydelendik** [comment]
Okay, this JPEG image is not JPEG File Interchange Format (JFIF): "... requirement is the mandatory presence of the APP0 marker right after the SOI marker" This image has no such data.

[PDF32000](http://localhost:8888/web/viewer.html?file=/files~/PDF32000_2008.pdf#page=42&zoom=100,-62,457) briefly describes property of the ColorTransform attribute, which means no transform (including YUV one). Standard JFIF formats requires YUV transform.

Possible resolution is to check ColorTransform=0 and fallback to PDF.js JPEG decoding without conversion.
