### ISSUE TITLE
Error on `PDFDocumentLoadingTask.destroy`: Cannot read property 'objs' of undefined

### ISSUE THREAD

**Issue by Kureev** [mozilla/pdf.js#6577]
![image](https://cloud.githubusercontent.com/assets/2273613/10819416/33cfe050-7e48-11e5-8f00-02a945567936.png)
Version 1.2.38
Occurs when I try to cancel existing transfer.

Seems `messageHandler` keeps receiving 'obj' messages even after `destroy()`. But `pageCache` object has been flushed already, so line 2915 `if (pageProxy.objs.hasData(id)) {` throws an error above.

cc @yurydelendik

**Comment by yurydelendik** [comment]
@Kureev can you provide a test case?

**Comment by yurydelendik** [comment]
Also see if #6571 fixes the issue

**Comment by Kureev** [comment]
@yurydelendik I'm using it for a single document, so seems #6571 can't help me with it. What kind of a test case do you want?

**Comment by yurydelendik** [comment]
> What kind of a test case do you want?

A test case that demonstrate the issue. You already have a code, so it will save the project contributors time to narrow down the issue.

**Comment by Kureev** [comment]
@yurydelendik Unfortunately, I don't have a permission to share this code with anybody, but I'll try to compose a sandbox to demonstrate it

**Comment by Kureev** [comment]
@yurydelendik https://github.com/Kureev/pdfjs-example

**Comment by yurydelendik** [comment]
Okay, it looks like the similar issue as in #6560, but at different timing. Used PDF document is also matters. (You can reproduce with high rate if you will add `pdf.destroy();` just after the render method call).

**Comment by Kureev** [comment]
This works :heart: !
