### ISSUE TITLE
Uncaught (in promise) cancelled

### ISSUE THREAD

**Issue by Kureev** [mozilla/pdf.js#6579]
![image](https://cloud.githubusercontent.com/assets/2273613/10845106/714336ea-7f05-11e5-8a7c-ce302bdfc894.png)
Seems if I destroy a worker after scheduling a `render` task, something in rendering promise triggers a `cancelled` error which I can't catch. (I've tried to intercept `render(...).promise.catch`, so I get `cancelled`, but error still occurs). 

cc @yurydelendik

**Comment by yurydelendik** [comment]
Can you provide a test case? I'm thinking it's possible to reproduce that with just calling cancel on the render task object.

**Comment by Kureev** [comment]
I think you can still use my [previous example](https://github.com/Kureev/pdfjs-example), I've updated it to throw this error (added `.then()` to `render` function). Take a big PDF and wait pdf.js to start processing it, then cancel.

**Comment by yurydelendik** [comment]
Hmm, I was not able to reproduce that so far -- probably I'm using wrong PDF or timing is bad. (Ability to be able to reproduce will help quickly to fix the issue)

**Comment by Kureev** [comment]
You can use this one: http://www.nasa.gov/pdf/750614main_NASA_FY_2014_Budget_Estimates-508.pdf to reproduce the issue. Right after you select it, press cancel and check developer console

**Comment by Kureev** [comment]
I've sent you a PDF in the email, @yurydelendik

**Comment by Kureev** [comment]
Just tested PDF I've sent you in FF, got this:
![image](https://cloud.githubusercontent.com/assets/2273613/10847507/34bb309e-7f17-11e5-8ced-e392a4293522.png)
In FF I have this error message with a few seconds timeout

**Comment by yurydelendik** [comment]
I see that when using your document, but it's expected. The render promise must be resolved to something (and it shall not be a success)

To avoid breaking in the debugger tools or console message, please use catch e.g.:

```
       page.render({
          canvasContext: canvas.getContext('2d'),
          viewport: page.getViewport(scale),
        }).promise.then(function() {
          console.log('finished');
        }, function (reason) {
          console.log('stopped ' + reason);
        });
```

or

```
       page.render({
          canvasContext: canvas.getContext('2d'),
          viewport: page.getViewport(scale),
        }).promise.catch(function (reason) {
          console.log('stopped ' + reason);
        });
```

I hope this helps.

**Comment by Kureev** [comment]
Thanks a lot!
