### ISSUE TITLE
Issue with smaller image divs shrinking inside a larger container div (Divception)

### ISSUE THREAD

**Issue by invizon104** [mozilla/pdf.js#6584]
I have a div that holds a number of smaller divs. These smaller divs are used for displaying pictures... Not sure what the best way of explaining it is, so I'll add a couple of images

![template_design](https://cloud.githubusercontent.com/assets/15470154/10857591/f40fb0d2-7f1c-11e5-9e22-84cf29b48c18.png)

Anyways, in the design view, I have the divs looking perfectly, or at least near perfectly like the example above. Everything is lined up so it looks even with whatever element. However...

![template_print](https://cloud.githubusercontent.com/assets/15470154/10857601/0f3b0cb2-7f1d-11e5-9f29-ba4c69c909de.png)

When I go to Print view, the pictures divs shrink in size. A lot of the time it isn't by much, almost barely noticable, but its enough to throw the layout off. I have tried this on both Chrome and Firefox, and I have downloaded it an opened it in Adobe; every time it comes out the same way. I've thrown everything I can think of at this but haven't been able to figure out why its happening.

**Comment by yurydelendik** [comment]
How it's related to PDF.js project?

**Comment by timvandermeij** [comment]
I'm also really confused and I think this is filed in the wrong repository. This does not look like PDF.js at all and it does not even appear to deal with PDF files, but rather image divs. Closing as invalid until more information is provided (example PDF file or link, used PDF.js version and browser/OS versions).
