### ISSUE TITLE
Is not default pdf viewer for chrome

### ISSUE THREAD

**Issue by tmorrow-hyphensolutions** [mozilla/pdf.js#6589]
pdf.js is not my default pdf viewer in chrome browser. I went to chrome://plugins and disabled the default viewer.

It's the default viewer for http urls, but not for file urls. I have enabled allow file urls in the extensions page.

Thanks!

**Comment by Rob--W** [comment]
Try restarting Chrome.

There is a bug in Chrome that when an extension updates, it can no longer access file:-URLs (https://crbug.com/365107).

**Comment by tmorrow-hyphensolutions** [comment]
Yes thank you.
Close the issue.
Sorry for taking your time.

-Todd
