### ISSUE TITLE
Default behavior for setting workerSrc is brittle; assumes that last script is pdf.js

### ISSUE THREAD

**Issue by Arwid** [mozilla/pdf.js#6593]
The following code assumes that pdf.js is the last included script in head. If it's not, workerSrc will be set incorrectly (e.g. if last script src is app.js, pdfjsSrc is set to app.worker.js).

```javascript
 if (!PDFJS.workerSrc && typeof document !== 'undefined') {
  // workerSrc is not set -- using last script url to define default location
  PDFJS.workerSrc = (function () {
    'use strict';
    var scriptTagContainer = document.body ||
                             document.getElementsByTagName('head')[0];
    var pdfjsSrc = scriptTagContainer.lastChild.src;
    return pdfjsSrc && pdfjsSrc.replace(/\.js$/i, '.worker.js');
  })();
}
```
source: https://github.com/mozilla/pdf.js/blob/master/src/pdf.js#L41

**Comment by yurydelendik** [comment]
@Arwid yes, you have to always set PDFJS.workerSrc (as examples recommend)

What is your expected behavior for the issue?

**Comment by Rob--W** [comment]
[`document.currentScript`](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) is more robust than taking the last element, but it is not universally supported (IE).

**Comment by yurydelendik** [comment]
No information provided, closing as incomplete.
