### ISSUE TITLE
Search Function doesn't scroll to invisible string

### ISSUE THREAD

**Issue by seanlis** [mozilla/pdf.js#6596]
The search only jumps to the page that contains the string, but doesn't scroll to the string if it's invisible.

For example, if I search javascript in the [demo](https://mozilla.github.io/pdf.js/web/viewer.html), the 3rd match is invisible in this window, but pdf.js doesn't update position to show it.

This is what it looked like.

![image](https://cloud.githubusercontent.com/assets/7328445/10995070/4004b56c-84b5-11e5-9aed-7ee16a21e3d7.png)

I had to manually scroll down to see the matched string(rendered green).
![image](https://cloud.githubusercontent.com/assets/7328445/10995297/aa1e39ea-84b6-11e5-9637-f8e45966b40d.png)

**Comment by Snuffleupagus** [comment]
This seem to be a regression from PR #6552.
