### ISSUE TITLE
very high marking of type 3 font glyphs with 0 0 0 0 BBox

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6605]
Text marking with this file
https://issues.apache.org/jira/secure/attachment/12769999/type3%20zero%20font%20size.pdf
has a giant size.

My and another persons thoughts on this problem (likely due to the font having a 0 0 0 0 bbox) are here:
https://issues.apache.org/jira/browse/PDFBOX-3076

**Comment by yurydelendik** [comment]
fwiw, mac osx preview app has the same issue

<img width="689" alt="screen shot 2015-11-10 at 5 21 47 pm" src="https://cloud.githubusercontent.com/assets/1523410/11079123/968453da-87cf-11e5-9436-e437e205feb6.png">
