### ISSUE TITLE
Do not hardcode ports in test.js

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6609]
Currently test.js defaults to port 8000 if a port is not given.

But if I have something else running at port 8000, then I cannot use `node make test` because there is no way to change the port.

Can we set the port to `0`, so that Node.js automatically chooses a free port? Then we can also run multiple tests next to each other (in theory).

**Comment by yurydelendik** [comment]
There is not problem in moving test server to a different port, e.g. 5-digit number (auto-choosing a free port might introduce many unless code)

**Comment by Rob--W** [comment]
@yurydelendik Choosing a random port a la https://xkcd.com/221/ is not going to fly. I'll let the system choose a port (see PR #6620).
