### ISSUE TITLE
Wrong Text Layer rendering for some PDFs

### ISSUE THREAD

**Issue by mpankov** [mozilla/pdf.js#6612]
Here is a sample PDF: https://github.com/mpankov/pdfjs_selection_issue/raw/master/test_document.pdf
Text Layer words position doesn't correspond to canvas.
Search highlight is outside of text:
![wrong_selection_position](https://cloud.githubusercontent.com/assets/5310577/11037136/4cd2ffe2-870d-11e5-97a0-e4c56408230f.png)

As I can see PDF.js renders "tab" symbols in Text Layer (instead of spaces) and that makes text longer...

**Comment by yurydelendik** [comment]
Not finding "tab" symbols, but I see glyph advance is used after each character:

```
[<0001>-20.385<0002>-20.385<0003>-20.385<0004>-20.385<0005>-20.385<0006>-20.385...
```

Looks like this affects the div size. (Not sure why generator chose the use that instead of character spacing or just using monospace font metric).

**Comment by yurydelendik** [comment]
You are right, there are tabs in the div layer though. I wonder if we can just replace them with spaces.

**Comment by mpankov** [comment]
Hi Yury,
Thank you for the analysis.
Is there a way I could help to fix this issue or speed up the process somehow?
I'm not very familiar with PDF.js code, but if you could point me to a potential place to replace tabs with spaces, I will try to fix it.
Thanks!

**Comment by yurydelendik** [comment]
> Is there a way I could help to fix this issue or speed up the process somehow?

Sure, you can submit a pull request e.g. with CSS fix that changes tab size to 1.

**Comment by mpankov** [comment]
Ok, I have created a pull request with the fix you suggested.
BTW, this change looks like a workaround, I thought we have to do something with the Text Layer rendering... But I checked this fix on a sample PDF with real tab symbols, and it works fine. So looks like this is an acceptable solution.

**Comment by mpankov** [comment]
I have found that phrase search does not work with that approach (because of tab, but not space, between words).
So cancelling the PR... I think we need to replace "tab" symbols during the Text Layer rendering.
