### ISSUE TITLE
Use of document.currentScript breaks phantomJS and IE

### ISSUE THREAD

**Issue by andrenarchy** [mozilla/pdf.js#6613]
PR #6595 introduced `document.currentScript` which breaks phantomJS (and probably IE as indicated [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript)):
```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  TypeError: 'undefined' is not an object (evaluating 'document.currentScript.src')
  at [...]
```
It was also mentioned in #6593 that `document.currentScript` is not universally supported. Maybe this was overlooked. There should be a fallback for browsers not supporting it.

**Comment by yurydelendik** [comment]
> There should be a fallback for browsers not supporting it.

There is a fallback, see compatibility.js file.

**Comment by yurydelendik** [comment]
Closing as not an issue: for legacy browser include web/compatibility.js file. (Or upgrade PhantomJS to more up-to-date version 2)

**Comment by andrenarchy** [comment]
The problem was that we loaded `compatibility.js` after `pdf.js`. Thanks for your quick and very helpful response!
