### ISSUE TITLE
Vertical positioning of text layer off (for some documents)

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#6614]
For some documents, the vertical positioning of the text layer is off. Examples include

 * http://arxiv.org/pdf/1208.0264.pdf and
 * http://arxiv.org/pdf/1405.2785v3.pdf

The outcome is

![area](https://cloud.githubusercontent.com/assets/181628/11046350/36dc72ca-872d-11e5-98d7-dcb47a9c1004.png)

Pull request #5545 does fix this, but is much larger in scope.

This is on Ubuntu 14.10 with Chrome 46.0.2490.80 (64-bit) and pdfjs 1.2.83.

**Comment by yurydelendik** [comment]
Can you also mention OS and browser you are using? I see it as

<img width="795" alt="screen shot 2015-11-09 at 3 04 02 pm" src="https://cloud.githubusercontent.com/assets/1523410/11046459/3824c798-86f3-11e5-9c89-65d440e7db84.png">

**Comment by nschloe** [comment]
@yurydelendik Extended the description.

**Comment by yurydelendik** [comment]
> You can reproduce this on https://dev.paperhive.org/frontend/deps/articles/563be788b6639fea3abc3e9a. 

I can see the defect there. (But not on http://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by nschloe** [comment]
Got it. The reason we're seeing the additional offset is that we're using bootstrap for the rest of the site, and bootstrap sets the `lineheight` to
```
body {
    // ...
    line-height: 1.42857143;
    // ...
}
```
see https://github.com/twbs/bootstrap/blob/master/less/variables.less#L63. Setting it back to `1.0` on the text layer fixes this. Perhaps this is something worth setting in pdfjs?

**Comment by yurydelendik** [comment]
> Setting it back to 1.0 on the text layer fixes this. Perhaps this is something worth setting in pdfjs?

Yeah, we need to include those default parameters at text_layer_builder.css.
