### ISSUE TITLE
Page continuous without separating the pdf-pages and showing the body/html of the viewer between pages.

### ISSUE THREAD

**Issue by m-ichael** [mozilla/pdf.js#6618]
How to set the viewer to show a continuous page if the pdf has more then one page, instead of the default, a pages-scroll that shows intermittent space where background shows through between pages. Skim and Adobe allow for this setting when submitting my same test page, this setting is most usefull when showing a multipage pdf in a browser. It's 'seamlessness' no-seams takes pdf closer to the web, part of the idea behind pdf.js. 
What file to edit, probably viewer.js? viewer.css?

**Comment by timvandermeij** [comment]
Is this related to #1385?

**Comment by m-ichael** [comment]
It is not, let me be more precise: in default view, the viewer will show a multi-page pdf, upon scrolling down/up wards there is a gap of a few points between pages.
The question is as follows, how/where to reformat the viewer to glue subsequent pages into one continuous (not page) show of individual pages glued together. Both skim and adobe-viewer allow for this, it would be miming a regular html concept of an uninterupted flow of content.
So this boils down to a formatting the viewer(viewer.js?, viewer.css?) question. Since one of the design goals of pdf.js is 'integrating pdf into the workflow' 'offering all of the existing functionality of the browser' that would justify tweaking the code for me.
If the pdf is produced without header and footer, and no margin top or bottom, the pdf pages become a continuous content, very appropriately mimicking the html/browser of regular.

**Comment by yurydelendik** [comment]
If it's just removing styling/page borders, then it can be done by editing css and js files (see pdf_viewer.css/.js first -- it will be compiled into viewer.js during the build). There was something extra requested at #2288. (Reformatting of a text on the PDF page is not possible)

**Comment by m-ichael** [comment]
Solved, thanks to your tip, there is a 9pt transparent border around every page, removing it, setting it to 0 gives the desired effect. 
Removing the main toolbar 'Toolbarviewer' 'ToolbarContainer' ?? gives me trouble though... Should i remove a complete division in the viewer.html?

**Comment by yurydelendik** [comment]
See if it will easier for you to start from the simpleviewer example at https://github.com/mozilla/pdf.js/tree/master/examples/components (it uses only pdf_viewer.js)

**Comment by m-ichael** [comment]
Done and thanks, the viewer.css holds consequently all of the formatting. Will post an example of 'my style' later. The viewer contains no toolbar(not needed, a browser has a search function, the toolbar on top takes away vertical screen estate) as the only particular differing from the default.
