### ISSUE TITLE
Issue with png image rendering

### ISSUE THREAD

**Issue by ryanp0422** [mozilla/pdf.js#6621]
The png logo shows up in other pdf readers but not in pdf.js  

[933efe83-fd36-4c0e-9e2e-88e6cc6e07c4.pdf](https://github.com/mozilla/pdf.js/files/31286/933efe83-fd36-4c0e-9e2e-88e6cc6e07c4.pdf)

**Comment by yurydelendik** [comment]
fwiw, it does not show in Mac OSX Preview.

<img width="1072" alt="screen shot 2015-11-10 at 4 21 44 pm" src="https://cloud.githubusercontent.com/assets/1523410/11077730/37a87cf4-87c7-11e5-9072-0042a0eb0266.png">

**Comment by ryanp0422** [comment]
You think it could be an issue with the image?

**Comment by yurydelendik** [comment]
Looks like mask is not decoded properly -- I see it inverted. Probably it's connected with how we decode DeviceGray colorspace 1 bit-per-component data.

**Comment by ryanp0422** [comment]
Is that something I can look for in an upcoming release, or show we try getting a new image?

**Comment by yurydelendik** [comment]
> Is that something I can look for in an upcoming release

depends if somebody will submit a patch to fix the issue

**Comment by ryanp0422** [comment]
Ok thanks.

**Comment by yurydelendik** [comment]
@ryanp0422 can you create a sample/smaller file that will demonstrate the issue and we can redistribute it as a reference test?

**Comment by ryanp0422** [comment]
I was able to compress it a bit, but I cannot generate a new file

[e-file.compressed.pdf](https://github.com/mozilla/pdf.js/files/31377/e-file.compressed.pdf)

**Comment by Rob--W** [comment]
Here is a minimal test case:

[issue6621.pdf](https://github.com/mozilla/pdf.js/files/31812/issue6621.pdf)

**Comment by THausherr** [comment]
PDFBox and GS 9.14 also don't display the seal.

**Comment by THausherr** [comment]
The file is broken.

I get the "bad" effect in Acrobat Reader if I insert "/ImageMask true" in the mask. If I set it to false then the rendering is good. This leads me to the conclusion that this part of the spec is to be taken literally: "However, if the image dictionary’s ImageMask entry is true, the sample data shall be interpreted as a stencil mask for applying the graphics state’s nonstroking colour parameters (see 8.9.6.2, "Stencil Masking")." i.e. that if /ImageMask isn't there or is false, the mask is to be ignored.

This can be confirmed by a trick: at the beginning of the content stream, change "1 1 1 rg" (white) to "1 0 1 rg" (pink). Display with Adobe Reader, the white square is there. If masking bad been working, only the seal would be seen without a white square.

If your eyes are good, you can see the dirt below the seal, which can also be seen in the unedited PDF. If the masking had been working, the dirt wouldn't be seen.

So for PDFBox, I'll simply change to apply the mask only if /ImageMask true

@ryanp0422: if you created the file, a solution would be to remove /ColorSpace /DeviceGray, set /ImageMask true and /Decode to [1 0] (I tested this!). Or just remove /ColorSpace /DeviceGray, set /ImageMask true and reverse the mask bits.

Btw, unrelated to all this: your file claims to be PDF/A but it isn't. I checked it with PDFBox preflight and with PDF-Tools. http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx

3.1.11 : Invalid Font definition, DEVEXP+TimesNewRoman: The CIDSet entry is missing for the Composite Subset
3.1.11 : Invalid Font definition, DEVEXP+TimesNewRoman,Bold: The CIDSet entry is missing for the Composite Subset
7.1 : Error on MetaData, Expecting namespace 'adobe:ns:meta/' and found 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'

**Comment by yurydelendik** [comment]
@THausherr  really good info. Any ideas what will be a right workaround on PDF.js side so we will have same effect as in Adobe Reader? Is it if /ImageMask true we have to ignore /ColorSpace ?

**Comment by yurydelendik** [comment]
Probably, the same as with PDFBox, "change to apply the mask only if /ImageMask true"

**Comment by THausherr** [comment]
I did look into the pdf.js code, but this will need another beginner than me :-)

**Comment by THausherr** [comment]
https://issues.apache.org/jira/browse/PDFBOX-3105
contains the "pink file".
