### ISSUE TITLE
radio buttons should have same field names

### ISSUE THREAD

**Issue by si458** [mozilla/pdf.js#6623]
Hi,
I have been bashing my head against wall for days now and ive finally found an issue

im using this sample to create online PDF forms for filling in - http://www.codeproject.com/Articles/466362/Blend-PDF-with-HTML (i have updated the pdf.js engine to latest version, tweaked a few files and seemed ok)

however when I create a pdf with radio buttons using adobe and make sure the radio buttons are in the same group, it appears the radio buttons are showing the fieldName as  
`Group1`0`   `Group1`1` 
(noticed the extra bit after the Group1)

however they need to be displayed the same fieldName for the radio buttons to work correctly

ive managed to find the line in Annotation.js(535) and pdf.worker.js(5416) - fieldName.unshift('`' + j);

this resolves the issue with text fields, buttons, etc, but not radio buttons!

is it possible to check if type if a radio button if so then dont add it ?

EDIT: simple code i made and seems ok - if (data.fieldFlags & 32768) { }else{ fieldName.unshift('`' + j); }

currently ive just commented out the line and it works

Simon

**Comment by yurydelendik** [comment]
AcroForms are not supported yet (see #1459 and #6172). If you think that make sense, please submit a pull request. Notice there is a comment about this line https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L522 . My question is: why there is no name for the radio button?
