### ISSUE TITLE
Symbols displayed as rectangles only on Linux

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6624]
This was found in #6610 after the following reftest: http://107.21.233.14:8877/95b107ace06ecf3/reftest-analyzer.html#web=eq.log

The test case from that PR works fine on Windows, but displays rectangles on Linux. It appears to be Linux-only.

**Comment by SamyCookie** [comment]
Not an issue on my Debian testing (stretch) 64bits computer with Firefox 42.

**Comment by timvandermeij** [comment]
Maybe it's just the Linux bot. We need to look into this further, but thank you for confirming that it is not an issue for all Linux distributions.

**Comment by Rob--W** [comment]
Looks fine for me in Chromium 46 on ArchLinux.

**Comment by timvandermeij** [comment]
@yurydelendik @brendandahl Could it be that the Linux bot is not up to date?

**Comment by timvandermeij** [comment]
This seems to happen on the Linux bot with a lot of files now: http://107.21.233.14:8877/d0892aecbf4ec50/reftest-analyzer.html, around firefox-issue2829-page4.

**Comment by timvandermeij** [comment]
This turned out to be caused by missing CJK fonts on the Linux bot. Not only are the CJK characters rendered properly now, the overall font rendering has improved in such a way that there is barely any difference with the Windows bot, making comparisons easier. New reference images have been generated, so I'm closing this as fixed.

(We now also have documentation for the bots with the packages that we installed. See https://github.com/mozilla/pdf.js/wiki/Bots for more information.)
