### ISSUE TITLE
Why pdfjs View remote file only on FullScreen?

### ISSUE THREAD

**Issue by dmitrirussu** [mozilla/pdf.js#6632]
Hi I have installed your lib on my server, I try to call a pdf file from the server public storage. The remote access is enabled etc. After PDFJS download the file. I see he display Number of pages, but no Thumbnails, no pages viewed, Only on full screen  it display the pdf file. 

PDF file which I use id the demo file from the you repository. 

I was tested on Firefox 42.0, Chrome 46.0.2490.80

Please help me to solve the problem

Thanks

**Comment by dmitrirussu** [comment]
I see the canvas is empty

**Comment by yurydelendik** [comment]
Could you provide a link to your application/server?

**Comment by dmitrirussu** [comment]
Hi, you can see here 
http://app.hypetutor.com/CampaignBuilder/Viewer 

version is v1.1.366

**Comment by dmitrirussu** [comment]
Hi, again I was taking directly the files from the demo view (http://mozilla.github.io/pdf.js/web/viewer.html) and replaced on the repository 1.1.366 /build directory, and now it display ok the pdf document.

**Comment by yurydelendik** [comment]
Your changes in HTML are causing the pages to be hidden:

```
< <body tabindex="1" class="loadingInProgress"><div>
---
>   </head>
> 
>   <body tabindex="1" class="loadingInProgress">
24a51
> 
390,391c417,419
< 	</div>
< </div></body>
---
> </div>
> 
>   </body>
```

Notice you added extra div-wrapper. That broke CSS, but if you use the inspector you can see that PDF pages/canvases are rendered.

Closing as invalid.

**Comment by dmitrirussu** [comment]
thanks
