### ISSUE TITLE
In Browserify environment, PDFJS.workerSrc does not work when using the "require" method

### ISSUE THREAD

**Issue by mykone** [mozilla/pdf.js#6634]
I am using Browserify to require my modules, and test PDFJS. I followed the Setup guide at: https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website. When I use the "require()" method, I get no errors but the Promise is stuck in "pending", and neither onFulfilled, nor onRejected gets called. However, if I copy the same pdf.worker.js to the root directory and specify the workerSrc path as a string, everything works.

Please note, I am not using WebPack.
 
See sample code below:

```javascript

  require('pdfjs-dist/build/pdf');
  
  canvas = document.getElementById('the-canvas');

  ctx = canvas.getContext('2d');

  url = './test.pdf';

  //This does not work, even though "pdf.worker.js" is in the same path.
  //Neither "onFullFilled" nor "onRejected" gets called.
  //PDFJS.workerSrc = require('pdfjs-dist/build/pdf.worker.js');

  //This works if I copy the same file to the root directory. 
  //onFulfilled gets called and the PDF is rendered properly
  PDFJS.workerSrc = "/pdf.worker.js";

  console.log("PDFJS:%o", PDFJS);

  _self = this;

  onFulfilled = function(pdf) {
    var pdfDoc;
    console.log("PDF Loaded successfully. Number of pages:%o", pdf.numPages);
    pdfDoc = pdf;
    document.getElementById('page_count').textContent = pdfDoc.numPages;
    _self.renderPage(pageNum);
  };

  onRejected = function(reason) {
    console.log("PDFJS.getDocument(url) FAILED!, Reason:%o", reason);
  };

  PDFJS.getDocument(url).then(onFulfilled, onRejected);
```

**Comment by timvandermeij** [comment]
As far as I know, you *need* to specify the worker source as a string (#6595), but I might be wrong. Maybe @yurydelendik can say more about this.

**Comment by mykone** [comment]
Thanks for your quick repy @timvandermeij . As I mentioned, I followed the Setup guide. Please see the code I use below:

```javascript
// in index.js
require('pdfjs-dist/build/pdf');
require('pdfjs-dist/web/pdf_viewer'); // Only if you need `PDFJS.PDFViewer`
// Webpack returns a string to the url because we configured the url-loader.
PDFJS.workerSrc = require('pdfjs-dist/build/pdf.worker.js');
var url = require('assets/books/my book.pdf'); 
PDFJS.getDocument(url).then(function(pdf) {/* Continue the normal tutorial from the README.*/})
```

**Comment by yurydelendik** [comment]
`PDFJS.workerSrc` is a string parameter, so PDFJS.workerSrc = '/absolute-path-to-pdfjs-dist/build/pdf.worker.js'; shall work. If '/absolute-path-to-pdfjs-dist' can change, calculate it based on html page URL. Closing as anwered.

**Comment by NawfelBgh** [comment]
I had the same problem when using PDFJS with browserify.

My solution was 

* src/pdf.js

```js
require('pdfjs-dist')
```

* src/pdf.worker.js

```js
require('pdfjs-dist/build/pdf.worker.js');
```

* src/index.js: My code which uses PDFJS without using require since it's exported in window.PDFJS which smells.

* package.json

```json
"scripts": {
    "build:pdfjs": "browserify src/pdf.js -o public/pdf.js && browserify src/pdf.worker.js -o public/pdf.worker.js",
```
