### ISSUE TITLE
Chinese characters clipped on the left

### ISSUE THREAD

**Issue by mjlyons** [mozilla/pdf.js#6635]
PDF.js Daily screenshot:
https://www.dropbox.com/s/p2axyt6nizy3oq5/Screenshot%202015-11-13%2019.11.50.png?dl=0

Preview.app:
https://www.dropbox.com/s/nbxvw9mmjlwkqsu/Screenshot%202015-11-13%2019.12.09.png?dl=0

PDF:
https://www.dropbox.com/s/t7c49mkis290ehz/chinese-bad.pdf?dl=0

Note the 2nd and 8th characters (and others) are clipped a bit on the left side in the PDF.js screenshot, but not in Preview.app.

This document was generating by exporting a PDF from MS Word. I've noticed this in several Chinese documents.

**Comment by timvandermeij** [comment]
I can't reproduce this on Windows 10 Pro x64 with Firefox and the latest PDF.js development version. Perhaps it's OS X-only?

**Comment by mjlyons** [comment]
Looks like it's OS X only. Repros on Firefox and Chrome, but not Safari.

**Comment by timvandermeij** [comment]
Does this still happen with the latest PDF.js version at https://mozilla.github.io/pdf.js/web/viewer.html (use the Open File button in the toolbar to ope the PDF file)?

**Comment by Snuffleupagus** [comment]
Given that this is likely to be a platform/browser issue, rather than a PDF.js one, is it meaningful to keep this issue open when it cannot be fixed *here*?
