### ISSUE TITLE
Display info bar when PDF contains attachments

### ISSUE THREAD

**Issue by fbender** [mozilla/pdf.js#6644]
When a PDF contains attachments, no indication is given that there are attachments available. Users have to manually toggle the sidebar and switch to the attachments tab. Instead, a notification bar should be shown to indicate that attachments are available, and maybe a button that opens the sidebar in attachment view.

PDF document: http://www.jasnapaka.com/bugs/aaa.pdf
OS: Windows 7 64 bit
pdf.js: Firefox 42 (32bit, release), PDF.js: ?

**Comment by Snuffleupagus** [comment]
Given that this issue is basically about the same thing as #5961, I don't think that it's necessary to keep both of them open; hence I'm closing this one as a duplicate.
