### ISSUE TITLE
Death Valley map symbols rendered as black squares

### ISSUE THREAD

**Issue by nth10sd** [mozilla/pdf.js#6652]
link to the PDF: http://www.nps.gov/deva/planyourvisit/loader.cfm?csModule=security/getfile&pageid=112771
location in the PDF: Map symbols rendered as black squares
screenshot: ![pdfscreenshot](https://cloud.githubusercontent.com/assets/488630/11225188/a818c834-8d2d-11e5-967f-621c3b21b649.png)
browser version: 43.0b4
operating system: Mac OS X 10.11.1 El Capitan

PDF.js version:
PDFJS.version = '1.1.469'; PDFJS.build = 'f06aa6a';

JavaScript console warning/error messages: 
PDF c00243375b7720a8de78ba83c0cf116d [1.4 Adobe PDF library 5.00 / Adobe Illustrator 10.0.3](PDF.js: 1.1.469) viewer.js:6746:1
Warning: globalCompositeOperation "compatible" is not supported pdf.js:224:5

El Capitan's Preview.app 8.1 (877) renders it as: ![previewappscreenshot](https://cloud.githubusercontent.com/assets/488630/11225310/61e3d02e-8d2e-11e5-8837-2885f8c46b53.png)

**Comment by timvandermeij** [comment]
Thank you for the detailed bug report. I can reproduce this on Windows 10 x64 with Firefox 42 and the latest PDF.js development version. I'm also labeling this as a performance issue as it takes forever to render the map.
