### ISSUE TITLE
When copying non-horizontally text line breaks are added

### ISSUE THREAD

**Issue by rugk** [mozilla/pdf.js#6659]
example: https://www.ietf.org/proceedings/82/slides/rtcweb-13.pdf

When you copy a text which is displayed non-horizontally like the HTTPS (ROAP?) on site 6 you get many line breaks:

```
HTTPS
(R
OA
P?)
```

Tested with Firefox 42

**Comment by yurydelendik** [comment]
Text is question painted using following commands:

```
BT
/R8 10 Tf
0.808736 -0.588172 0.588172 0.808736 220.414 175.061 Tm
(HTTPS)Tj
-3.23 -12 Td
(\(R)Tj
-0.35 Tc
9.59986 0 Td
(OA)Tj
0 Tc
14.09 0 Td
(P?\))Tj
```

**Comment by timvandermeij** [comment]
This improved slightly after a recent fix. It now copies as:

```
HTTPS
(ROA
P?)
```

**Comment by rugk** [comment]
Well… still broken😁

**Comment by timvandermeij** [comment]
Oh, I agree, I just mentioned it to update the issue with the current state so that when we go through the issues we know it's still relevant.

**Comment by Snuffleupagus** [comment]
WFM, since the unnecessary line-break was removed already by PR #10197 and then PR #13257 improved the situation further.

**Comment by rugk** [comment]
I can confirm with Firefox 88 the mentioned example now copies as: 
> HTTPS(ROAP?)

Which, IMHO, is okay. (A space could be useful, but I guess pdf.js cannot know this.)
