### ISSUE TITLE
all pages remain blank because the canvas remains hidden

### ISSUE THREAD

**Issue by cvlmtg** [mozilla/pdf.js#6661]
Hi, I upgraded pdf.js from 1.2.58 to 1.2.133 and suddenly all pdf pages remain blank. Comparing the two releases I discovered that now the canvas is hidden before the rendering starts and that the problem is that it remains hidden when the rendering finishes.

Looking at ```web/pdf_viewer.js``` I see that the canvas is shown again if this.renderingQueue is not falsy, however I've never used or setup any queue and I can't find any documentation on it, so I've no idea how to set it up and if it is really mandatory.

Currently our rendering code (taken from the old version of this example: https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js) is like this:

```coffee
view = new PDFJS.PDFPageView
  textLayerFactory: new PDFJS.DefaultTextLayerFactory()
  defaultViewport: task.cache.viewport
  id: task.container.id
  container: task.container
  scale: task.scale

view.setPdfPage task.cache.pdf
view.draw().then ->
  # do other things...
```

Any help? Thanks in advance!

**Comment by cvlmtg** [comment]
just a little addendum:

isCanvasHidden is set to true at line ```1238``` of pdfjs-dist/web/pdf_viewer.js, while at line ```1366``` there's the code that display the canvas again. This code is executed only if ```this.renderingQueue```is not falsy (line ```1356```)

**Comment by Snuffleupagus** [comment]
This is a regression from PR #6551.

**Comment by cvlmtg** [comment]
thanks!
