### ISSUE TITLE
Unwanted grey lines appear in PDF

### ISSUE THREAD

**Issue by SupratimChandra** [mozilla/pdf.js#6664]
There are unwanted grey horizontal lines appear in specific PDFs while opening in Mozilla browser and using PDF.js plugin. These lines are not observed in any other PDF viewer including Chrome and IE browser.

**Comment by yurydelendik** [comment]
Can you provide link to the one of the "specific PDF" or reduces test case?

**Comment by timvandermeij** [comment]
Closing as incomplete until more information is provided.
