### ISSUE TITLE
font blur(fuzzy) issue while rendering page on chrome latest version(ex:46.0.2490.86 m and above) , 

### ISSUE THREAD

**Issue by muthu07** [mozilla/pdf.js#6667]
Hi Team,
I am facing fuzzy font issue while rendering and printing on chrome 46.0.2490.86 m and above  versions., But its working fine on chrome 45., I work around on windows 7 environment with 64 bit.
Please find below screen shot., Kindly help on this issue.,

I founded issues on.chrome 43,46,47 browsers with windows7 64bit.

![screenshot_2](https://cloud.githubusercontent.com/assets/5626299/11296018/714ca282-8f3d-11e5-8ae5-bb474612a9ba.jpg)

**Comment by timvandermeij** [comment]
This is covered by #6668, so I'm closing this one.

**Comment by muthu07** [comment]
Hi @timvandermeij,

 #6668 issue is sharpness issue that's appearing in all browsers printed page out put only.

This issues getting while rendering the page on chrome 46,47 windows 7 64 bit. Is that graphics issue of machine or browsers. But i am getting good page while taking XPS format save. But issue on getting pdf format. 

One more info, from local machine its all good but mainly in remote machine only we are facing issue. is any different between local and remote machine.
