### ISSUE TITLE
Font sharpness issue on printed page from pdf.js with all the browsers compare to Adobe reader printed page.

### ISSUE THREAD

**Issue by muthu07** [mozilla/pdf.js#6668]
I am facing text sharpness problem, while print the page from all the browsers compare to Adobe reader  printed page. Is this default one for pdf.js?

Safari, IE, Chrome, Firefox     vs    Adobe reader

**Comment by timvandermeij** [comment]
Everything is sharp over here, so it must be some configuration/driver issue. Please post the Graphics section of `about:support` from Firefox.

**Comment by timvandermeij** [comment]
Closing as incomplete until the requested information is provided. Without this there is really nothing we can do.
