### ISSUE TITLE
Rendering the first page sooner

### ISSUE THREAD

**Issue by DavidVentura** [mozilla/pdf.js#6670]
Hi
I have some "big" PDFs (~130-180pag, 5-70MB), that do not start rendering until the file is completely downloaded or almost completely. This means that the first page renders (on a fast computer with a 50mb downlink) after 10-30 seconds. The viewer does ~30 requests, most are exactly 64kb in size
![requests](https://cloud.githubusercontent.com/assets/3650670/11309465/c7a71076-8fa2-11e5-9b9e-58cb12d37dd0.png)

It'd be lovely if pdf.js could be able to render the pages upon arrival. Maybe I'm doing something wrong on my end?
Currently using PDFJS.version = '1.1.469';

Edit: The timings don't change if I "linearize" the pdf with pdfopt.

**Comment by yurydelendik** [comment]
Please provide PDF that correspond to the figure above. Also browser kind and its version.

It normal to really "fragmented" and non optimized for web PDF to have multiple range request: for header, tralier and xref, and for page and its resources. Based on the figure above it only means either the PDF document is too framented (all the needed data located in different parts of file) or PDF is corrupted and PDF.js is trying to recover it.

**Comment by DavidVentura** [comment]
Sure. This is the file https://curso.especificosba.com.ar/pdfs/Clase8.pdf
I'm accessing the file through the viewer: https://curso.especificosba.com.ar/js/ViewerJS/#../../pdfs/1448045373_Clase8.pdf

On Firefox 43, Linux

**Comment by bmarkovic** [comment]
If I may add a bit. This PDF file really is weird. It doesn't display in the viewer on the given link, and when opened in Chrome PDF viewer it also took ages to render.  It took longer than anything I ever opened in Foxit Reader on Windows too.

**Comment by DavidVentura** [comment]
It does display, after 98 requests and 28s. On mupdf/okular on linux, the file displays immediately

**Comment by yurydelendik** [comment]
> On mupdf/okular on linux, the file displays immediately

Assuming that you are comparing loading locally downloaded file with network hosted one, could you also post how long it take to open using pdf.js if file is located locally?

**Comment by DavidVentura** [comment]
Hosting it locally with SimpleHTTPServer takes about 6-7 seconds to render. Even after refreshing (the request shows the pdf is cached already)

**Comment by yurydelendik** [comment]
Hosting matters. It looks like your hosting (using nginx?) delays every request by 300-900 ms! I tried to host the same file at my remote server:

<img width="1046" alt="screen shot 2015-12-14 at 10 16 43 am" src="https://cloud.githubusercontent.com/assets/1523410/11786390/05c5eb82-a24c-11e5-865c-16889e8f84b4.png">

I'm receiving response within seconds. Check your deployment on different servers. Keeping this issue opened just to see if we can reduce amount of requests or abandon range requests for badly deployed solutions.

**Comment by yurydelendik** [comment]
> with SimpleHTTPServer takes about 6-7 seconds to render.

SimpleHTTPServer cannot not handle range requests and cannot handle resource requests in parallel.

**Comment by DavidVentura** [comment]
I'll see if I can modify the behavior of nginx, it might be because the server is 10 thousand kilometers away (latency is always ~200ms)

**Comment by DavidVentura** [comment]
>SimpleHTTPServer cannot not handle range requests and cannot handle resource requests in parallel.

nginx locally, completing all requests takes 2.5s and rendering takes 7s after that. This is on a Core 2 Duo at 2.4ghz

**Comment by yurydelendik** [comment]
How much time it takes to render if you open your file using "Open File" button at http://mozilla.github.io/pdf.js/web/viewer.html ?

**Comment by DavidVentura** [comment]
It's instant. In my tests I'm using ViewerJS (that uses pdf.js)

**Comment by yurydelendik** [comment]
> In my tests I'm using ViewerJS

Older version of PDF.js (1.1.469) is used there. However I suspect that nginx cannot handle range requests (for big files?). Can you try different web server?

**Comment by yurydelendik** [comment]
@DavidVentura also, not sure if ViewerJS start displaying after it gets first page or it waits for all pages to be loaded. But that's question for the ViewerJS vendor.

**Comment by DavidVentura** [comment]
nginx supports  byte ranges: http://nginx.org/en/docs/http/ngx_http_core_module.html#max_ranges
I can't install another webserver atm. I'll use pdf.js and comment the results here

**Comment by DavidVentura** [comment]
Ok.. I just cloned the website you linked and works instantly on localhost. I'll upload it to the server and close the issue if it was ViewerJS all along

**Comment by DavidVentura** [comment]
Ok..
https://curso.especificosba.com.ar/js/pdfjs/web/viewer.html?file=../../../pdfs/1448045373_Clase8.pdf

Renders within 2-3 seconds, makes the same amount of requests and takes the same time to download the entire file( which was what I expected, even if I think >100 requests to download a 7mb file is a lot) , but there's almost instant rendering of the first page. Excellent!
