### ISSUE TITLE
Regression tests do not display annotations

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6673]
In the annotation flags refactoring PR, @Snuffleupagus noticed that our regression testing framework does not actually display the annotations and therefore they are not compared in the snapshots. This means that a file like `annotation-border-styles.pdf` is tested without rendered annotations, which defeats the purpose of that test case.

The cause is probably that some parts of the annotation code are placed in the viewer, which the regression testing framework does not take into account. We might need to do something similar to PR #6619 to fix this.

**Comment by Snuffleupagus** [comment]
Annotations that are appended to the `OperatorList` does not seem to be affected by this, but rather only those annotations which are handled in `web/annotations_layer_builder.js`.

**Comment by brendandahl** [comment]
We could do something similar to the new text layer tests where we render using SVG.
