### ISSUE TITLE
double click in text in pdf not working properly in chrome browser

### ISSUE THREAD

**Issue by eaxle** [mozilla/pdf.js#6678]
![untitled](https://cloud.githubusercontent.com/assets/11533842/11335558/4b594e34-9205-11e5-9ee6-750a109e0396.png)
If you double click in the text it selects other text as well.In above example,I double click the languages and it selects dynamic and andreas as well.It happens in chrome but not in firefox.
google chrome Version 46.0.2490.86 
os windows 10
pdf.js version PDF.js: 1.1.366
demo http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by fdstevex** [comment]
Happens in Safari (9.1) as well.  Not in Firefox.

**Comment by Jozomby** [comment]
I'm also seeing this problem, in Chrome (64.0) with pdf.js version v1.10.88.

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
