### ISSUE TITLE
Refactor annotation data passing

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6680]
Currently we do not expose the entire annotation object to viewer/third-party code, but only the data in `this.data`. Keeping `this.data` up-to-date not only requires more code, but it's also a bit error-prone as #6677 shows. I'm therefore proposing to expose the entire object instead as that will make the code easier and also give viewers/third-party code more flexibility (and more data to work with). Does this idea seem fine or are there issues with this approach that I have missed so far?

This would imply an API change as any external code relying on the fields in `this.data` must be converted to use the actual annotation object instead.

**Comment by Snuffleupagus** [comment]
> Does this idea seem fine or are there issues with this approach that I have missed so far?

One complication is that `annotation.js` is executed on the worker side, and the annotation `data` is then parsed on the main thread. Hence trying to return the `Annotation` "class" as is might not work correctly, since it's quite possible that there could be issues with cloning such an object.
(But please note that I haven't tested any of it, that's just what comes to mind immediately.)

**Comment by timvandermeij** [comment]
Good point. I just recall looking into that problem for #5218. What I remember that happened was that the methods were no longer accessible, but the attributes were, so one can no longer use `annotation.hasFlag(flag)` for example, but one can access `annotation.flags`. I think that is fine for our purposes though as viewer/third-party code does not need access to the setters or other methods, but only access to the properties of the object. But indeed this is something that needs to be tested to see if it really works this way.

**Comment by xlc** [comment]
It will be nice if some methods for Annotation class can be shared between worker and UI e.g. `hasFlag`, `viewable` and `printable`.
A possible solution is to create an `AnnotationHelper` class in `src/shared` folder so that helper methods can be shared.

      // src/shared/annotation_helper.js
      var AnnotationHelper = (function AnnotationHelperClosure() {
        function AnnotationHelper(data) {
          this.data = data;
        }

        AnnotationHelper.create = function(data) {
          return new AnnotationHelper(data)
        }

        AnnotationHelper.prototype = {
          // methods;
        };

        return AnnotationHelper;
      })();

-----

    // src/display/api.js
    getAnnotations: function PDFPageProxy_getAnnotations() {
      if (!this.annotationsPromise) {
        this.annotationsPromise = this.transport.getAnnotations(this.pageIndex)
        .then(function(annotations) {
          return annotations.map(AnnotationHelper.create)
        });
      }
      return this.annotationsPromise;
    },

-----
    
    // src/core/annotation.js
    Util.inherit(Annotation, AnnotationHelper);

**Comment by timvandermeij** [comment]
I did some more testing for this and it turns out that indeed the methods are lost when the object is cloned. While I like @Snuffleupagus' idea to bring back the `getData()` method that returns and object with the data to be exposed (since that prevents the double bookkeeping of the `this.data` object that we have to do now), after some more thinking I don't think that resolves this issue because when we clone the object we would still lose the `getData()` method.

We might need to some something along the lines of @xlc's comment, but personally I'm not a big fan of extracting the methods of the class only because the worker is not able to clone the object properly. It seems like all that extra code should not be necessary.

Do you have other suggestions to tackle this problem? If it turns out that passing the entire object is simply not possible, then I propose to remove the `this.data` object altogether as all properties are already in the cloned object (such as `this.rectangle` and `this.flags`).

**Comment by Snuffleupagus** [comment]
> [...] idea to bring back the getData() method that returns and object with the data to be exposed

That suggestion was made in the context of #6699, and without thinking too much about *this* specific issue. So in the current context I don't thing that `getData()` would bring us much, if any, value.

> [...] but personally I'm not a big fan of extracting the methods of the class only because the worker is not able to clone the object properly. It seems like all that extra code should not be necessary.

Agreed. Also, the `Annotation` "class" contains a number of methods that doesn't make sense to expose on the main thread either.

Since we're currently *only* exposing various properties, but not any methods, I suppose the question is how necessary it really is to have methods available too. (Note how e.g. PR #6675 added functionality that enables fetching of `viewable`/`printable` annotations through the API).

One thing that might explain why `this.data` was introduced in the first place, is that when workers are disabled, you'd get the entire `Annotation` object through the API (complete with methods and everything). So that case is probably worth considering here as well.

**Comment by timvandermeij** [comment]
I think you are right. We do not need to expose the entire object as third-party/viewer code does not really need the methods, only the properties. Since disabling workers is discouraged because of the performance impact, I don't think we need to worry too much about that case. In all cases though, third-party/viewer code can make use of the available properties of the annotation object without having `this.data` (e.g., `this.data.rect` would just become `this.rectangle`), so I'm in favor of removing it.

**Comment by yurydelendik** [comment]
Please notice that usage at the core and display modules of the annotations are different -- any future designs shall keep that in mind. The core part shall only perform parsing and providing an IR of the annotations (the different classes/methods can be used for operator list conversion). The display part shall operate with IR only to generate non-operator list representation. There might be some code duplication, but I'm afraid it will not be a big concern.

**Comment by Snuffleupagus** [comment]
To address the `this.<propertyName>` vs `this.data.<propertyName>` duplication, a possible solution could be something along these lines: https://gist.github.com/Snuffleupagus/62d3e1816db883c0af1a.

**Comment by yurydelendik** [comment]
IMHO just explicitly assigning properties from data/IR object to the target object will be as efficient. (My worry is that for-each loop might construct different object shape and that will prevent JIT from some optimizations).

**Comment by timvandermeij** [comment]
I don't think there is much more we can do about this at this point. The structure improved a lot since the last patches and the assignments to `this.data` are now more clear and grouped where possible (for example https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L170-L176). Other suggestions are either hard/impossible or inefficient, so I'm closing this for now. We can always decide to change this later if we want to, but for now the situation has improved a lot to keep it like this.
