### ISSUE TITLE
Full screen mode WITH toolbar badly needed

### ISSUE THREAD

**Issue by creynders** [mozilla/pdf.js#6688]
As @drjjw describes in #5993 there _is_ a use case for a full screen mode with toolbar. For instance I have multiple pdf viewers on a single HTML page and I'd like to offer the possibility to view each of them full screen separately, _with_ a toolbar. F11 is no solution since it'll simply put the entire browser window in full screen mode. And this is not for presentation purposes either, i.e. presentation mode won't do.

**Comment by Rob--W** [comment]
"Full screen mode with toolbar", sounds exactly like F11. How should full screen mode without opening a full screen browser window look like according to you?

**Comment by yurydelendik** [comment]
> For instance I have multiple pdf viewers on a single HTML page and I'd like to offer the possibility to view each of them full screen separately

@creynders I guess this is a use case for "Bookmark" button/link, you can open this link into new tab.

**Comment by creynders** [comment]
@Rob--W exactly, that's what it should be. But it's not. pdf.js only provides a "presentation mode" button, which sets the browser and pdf full screen, but hides the (pdf)toolbar. What we need is a button to set the browser and pdf full screen _with_ (pdf)tool bar. Or allowing to configure the presentation mode with/without toolbar.

@yurydelendik yeah, there's a number of workarounds, but all of them horrible UX-wise. IMO this is definitely a missing feature. One people will come back asking for.

**Comment by Rob--W** [comment]
I just press F11. Personally I never use the presentation mode except for square presentations, but the majority of the PDFs that I open are not like that.

Could we add an option to use "F11 full-screen" mode instead of presentation mode when the button is clicked when the PDF has a portrait orientation? Then Ctrl + Shift + P and F11 will still behave like today, but the fullscreen button gets a more useful default button.

Perhaps a tri-state

1. Ctrl + Shift + P
2. F11
3. 1 or 2, depending on the page orientation

WDYT @yurydelendik ?

**Comment by yurydelendik** [comment]
The main reason we did not want is add confusion between "Presentation Mode", browser's "Fullscreen Mode" and (whatever we can call it) "Extend into Fullscreen"-thing. There is no UX analysis presented yet for this request, so it's hard to introduce and support a feature that is used by small number of people. However I would be willing to review a functionality that adds it to the secondary menu (under similar to Ctrl + Shift + P or F11 shortcut with additional/different modifiers)

**Comment by yurydelendik** [comment]
(The site authors can modify UI to bring that to the front of the toolbar instead of "Presentation Mode" icon)

**Comment by creynders** [comment]
@yurydelendik Yeah, I understand. It's only really a problem with embedded pdf's. But I think allowing site authors to configure presentation mode with a toolbar is pretty useful in any case, no? I mean, there's plenty of situations where having a toolbar in presentation mode is useful too.

**Comment by yurydelendik** [comment]
> there's plenty of situations where having a toolbar in presentation mode is useful too. 

We are trying to place all needed commands in the context menu (it works only on FF atm)

**Comment by timvandermeij** [comment]
As far as I can tell this exact issue is tracked in #4816, where the author has made such functionality for https://pdf.yt, thus I'm closing this one as a duplicate for now.
