### ISSUE TITLE
pdf.js loads forever on a certain page of this PDF

### ISSUE THREAD

**Issue by pabloff9** [mozilla/pdf.js#6692]
pdf.js loads forever while trying to load page 11 of this PDF: http://www.inf.ufg.br/~hugoribeiro/OSPs/osp-im.pdf

I also noted that my Kindle Paperwhite has problems rendering the same page (especifically, the monospaced text part), while Evince loads it just fine.

**Comment by timvandermeij** [comment]
Thank you for reporting this. At first sight I do not see any immediate problems with that particular page. I was expecting to see a huge image that might take time to render, but it appears to be just text. We need to triage this.

**Comment by yurydelendik** [comment]
Based on proposed #6695 solution, marking PDF as corrupted.

The bigger question here to resolve, why the rendering promise is not getting resolved?

**Comment by timvandermeij** [comment]
With #6697 the infinite rendering issues for all pages are resolved. Now only the monospaced font is not displayed, which should also be resolved when #6695 is merged.

**Comment by pabloff9** [comment]
Awesome. Thanks. :)
