### ISSUE TITLE
Servo compatibility ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla/pdf.js#6702]
https://github.com/servo/servo

**Comment by timvandermeij** [comment]
We have no idea. Someone will have to try it out. Marking as a good beginner bug.

**Comment by LifeIsStrange** [comment]
Oh sorry this issue already exist https://github.com/servo/servo/issues/6098

**Comment by timvandermeij** [comment]
Let's track this over at the Servo repository then as there is not much we can do about this support on the PDF.js side (as the Servo support seems very minimal from a look at the issue).
