### ISSUE TITLE
Blank page and transparency not rendered

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#6707]
This PDF is blank when opended in Firefox (pdf.js)

https://secure.dynaccount.com/data/voucher/30000/400/30452_93e074c4c8b2301a24b33176331c49e5755e02fa.pdf

**Comment by yurydelendik** [comment]
Error message from console:

```
PDF 56cc7201a626829804b29f8c18284ef8 [1.4 GPL Ghostscript 9.16 / Faktura: 479608] (PDF.js: 1.3.44) viewer.js:6859:1
Error: unrecognized colorspace PANTONE 467 U 1 pdf.worker.js:248:5
ColorSpace_parseToIR@resource://pdf.js/build/pdf.worker.js:6763:11
ColorSpace_parseToIR@resource://pdf.js/build/pdf.worker.js:6833:17
ColorSpace_parse@resource://pdf.js/build/pdf.worker.js:6674:14
next@resource://pdf.js/build/pdf.worker.js:11327:17
```

**Comment by yurydelendik** [comment]
Adobe Reader has issues with this PDF as well. We need to fix error propagation in the evaluator to complete rendering.

**Comment by clarkk** [comment]
Thats right.. Adobe can't read the file either.. But Google Chrome can read the most of the file, but not the parts with transarency

The PDF file is optimized with Ghostscript
