### ISSUE TITLE
Dashed borders in link annotations not dashed

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6708]
http://www.ghostscript.com/doc/examples/annots.pdf

6 of the borders on page 1 should be dashed, see 4th element of /Border attribute, which is a dash array.

**Comment by Snuffleupagus** [comment]
Thanks for the report, but since this is already tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1219400, I'm closing this one as duplicate.
