### ISSUE TITLE
Zoom in/out with mouse wheel.

### ISSUE THREAD

**Issue by theoryshaw** [mozilla/pdf.js#6713]
Possible to include a preference where you can just use the mouse wheel to zoom in and out?  

In additon to ctrl + Mouse wheel, that is.

**Comment by dasilvacontin** [comment]
How do you intend to scroll the pages then?

**Comment by theoryshaw** [comment]
perhaps something like this?...

![2016-11-11_07-11-51](https://cloud.githubusercontent.com/assets/507113/20216110/50976454-a7de-11e6-8191-4055ac015695.gif)

Bluebeam Precedent

**Comment by dasilvacontin** [comment]
@theoryshaw Ah, you are clicking and dragging to scroll, or?

**Comment by theoryshaw** [comment]
using mouse wheel to zoom.

It zooms to center of where the cursor is placed. 

also, holding down middle mouse button (which is the scroll button too), it pans.

**Comment by Snuffleupagus** [comment]
This seems like enough of a special case to not warrant the added complexity it would add to the default viewer; closing as WONTFIX?

**Comment by gakudva** [comment]
Zooming with mouse wheel + CTRL is a common use case and PDF viewer.  Chrome PDF viewer supports this very well.  In pdf.js, zoom results in entire page including pdf.js control bar zooming out.

**Comment by timvandermeij** [comment]
Zooming everything instead of only the page is a bug that is in the progress of being fixed; see the recently merged #10652 and the corresponding upstream bug for Firefox.
