### ISSUE TITLE
Italic fonts printed slightly rotated

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#6719]
This happened at work with a "big" HP printer/scanner, but not at home with a cheap HP printer, with
https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf (page 2 and others)

(Both on Windows 7 with firefox)

The italic titles were printed slightly rotated, i.e. each glyph was rotated (not skewed):

![20151203_182340](https://cloud.githubusercontent.com/assets/6665575/11568252/68cae2c8-99eb-11e5-986e-2c00dfb60baf.png)

**Comment by ousia** [comment]
@THausherr, it is really hard to check what is happening there without having access to that page (_Adobe_ may be changing its policy requiring to register before accessing the document).

My guess is that the italic font isn’t embedded, but that the regular font is skewed in the PDF document. And PDF.js may be rotating the glyphs instead of skewing them.

**Comment by THausherr** [comment]
@ousia this is new. When I created the issue it was freely available. Luckly there's the internet archive:
https://web.archive.org/web/*/https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf
e.g.
https://web.archive.org/web/20150319074038/https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf

We no longer have the HP machine, now we have one from Xerox, and the problem happens there too.

Yes, it is not a italic font. It is helvetica bold and yes it is skewed:
```
  /F5 1 Tf
  13 0 2.763 13 222 698 Tm
  -0.006 Tc
  (Copyright) Tj
```
But why does it work properly when displaying in the browser and not when printing?

**Comment by THausherr** [comment]
Here's a reduced PDF:
[PDFJS-6719-badprint-reduced.pdf](https://github.com/mozilla/pdf.js/files/1256705/PDFJS-6719-badprint-reduced.pdf)
Now the content stream has only this:

```
0 g
BT
/F5 1 Tf
50 0 10 50 20 700 Tm
(Copyright)Tj
ET
```

**Comment by yurydelendik** [comment]
> But why does it work properly when displaying in the browser and not when printing?

Notice that Firefox is trying to print non-rasterized canvas content directly to the printer (see info/bugs around mozPrintCallback). Probably there is an issue with doing that on Windows.

**Comment by THausherr** [comment]
When I print from the current viewer ( https://mozilla.github.io/pdf.js/web/viewer.html ) it is fine. When I print from a viewer URL from April (e.g. from PR #8352) it is fine too. The effect happens only when using the built-in viewer in FF (55.0.3, 32 bit). Maybe I didn't take care to use the viewer URL when I created this issue.

**Comment by yurydelendik** [comment]
@THausherr Please notice that embedded in Firefox PDF.js uses mozPrintCallback (to generate vector output). Generic/demo viewer (for all browsers) rasterizes the output.

**Comment by Snuffleupagus** [comment]
Is this still an issue, with the built-in PDF Viewer in the latest version of Firefox?

**Comment by timvandermeij** [comment]
Closing since this is either fixed already or a problem with `mozPrintCallback` specifically, which cannot be fixed here and should be reported upstream in Bugzilla instead.
