### ISSUE TITLE
OCR highlighted Pdf is having issue while displaying in browser using pdf js

### ISSUE THREAD

**Issue by manishac91** [mozilla/pdf.js#6722]
In our application using c# we are highlighting the byte content of an prime OCR pdf.Where in pdf, the area can be selected.But when we are using pdf js to render the OCR pdf in browser the highlighted content is not getting.We are getting the pdf without highlight.

For general highlighted pdf(without OCR) is rendering properly using pdf js.

I have attached one pdf which is not working.

[HighlightPdf.pdf](https://github.com/mozilla/pdf.js/files/51844/HighlightPdf.pdf)

Is there any solution which can be used to render the highlighted OCR pdf in browser using pdf js.?

Thanks In Advance.
:)

**Comment by yurydelendik** [comment]
So it is "Hightlight" annotation support.
