### ISSUE TITLE
botio-linux hangs with slow script dialog box on issue6032.pdf test

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#6726]
This started happening after [dec-5 firefox aurora](http://ftp.mozilla.org/pub/firefox/nightly/2015/12/2015-12-05-00-40-05-mozilla-aurora/firefox-44.0a2.en-US.linux-x86_64.tar.bz2) update (https://hg.mozilla.org/releases/mozilla-aurora/rev/eeaa77b2a1e0e2c8f34f2342b2a254e1025f9f4d), last [good firefox aurora](http://ftp.mozilla.org/pub/firefox/nightly/2015/12/2015-12-04-00-40-06-mozilla-aurora/firefox-44.0a2.en-US.linux-x86_64.tar.bz2) (https://hg.mozilla.org/releases/mozilla-aurora/rev/858b1b930b16a5c46634e3dad2650c517e150cb0)

See https://github.com/mozilla/pdf.js/pull/4352#issuecomment-162230504

**Comment by timvandermeij** [comment]
Should this be reported upstream or should we replace the test file? I recall we have another test file from the Bugzilla issue.

**Comment by yurydelendik** [comment]
https://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=fd72ac533a5d91e8ba8341b78a4b0ed11332c904&tochange=695a52aa5554b191bd6d533f6842edf5ad228e8e

We shall probably replace the test
