### ISSUE TITLE
Can I integrate pdf.js as a search-in-pdf plugin

### ISSUE THREAD

**Issue by feldrim** [mozilla/pdf.js#6728]
Is it possible to call find tool of pdf.js outside the documents, so that we can search in pdf files on our blog and show the result highlighted in pdf.js window?

**Comment by timvandermeij** [comment]
It think it could be done. See https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js and https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_bar.js for how the current find code works. The code works with some events and you might be able to use the class in your own code, but it might be a difficult extension to reach it from outside PDF.js, and it is something we do not support here. Closing as out of scope.
