### ISSUE TITLE
pdf.js API

### ISSUE THREAD

**Issue by VovkVV** [mozilla/pdf.js#6730]
Is there any possibility to communicate with pdf.js from another (chrome) extension? More pricesely, I need such functionality as: 1. obtaining full amount of pages; 2. obtaining text of certain page; 3. obtaining page number and line number from and to user see on his screen now; 4. obtaining selected text.

**Comment by yurydelendik** [comment]
Not a chrome extension expert, but you can communicate with PDF.js generic viewer via window.PDFViewerApplication object. There is no API yet, so things might change. The pdfDocument is created by getDocument - you can find docs at src/display/api.js

Does this answer the question?

**Comment by VovkVV** [comment]
I think things are more complicated but thanks.
Extensions could exchange with messages as it described here: https://developer.chrome.com/extensions/messaging#external.

I modified pdf.js (I've added chrome.runtime.onMessageExternal.addListener) and send messages from background page of another extension (chrome.runtime.sendMessage). And I can send current page number to my another extension (PDFViewerApplication.page). It works.

But the problem is to obtain the text of current page. Is there a way to get a context of certain page (or, maybe, only current?) as text?

**Comment by VovkVV** [comment]
I found my task could be resolve if I first try to search something. Then PDFViewerApplication.findController fills array pageContents and it is possible to get text from this array. But I hesitate if is it the best way?

**Comment by yurydelendik** [comment]
To get the text from a page: use pdfDocument, retrieve the page using getPage and call its getTextContent.

**Comment by timvandermeij** [comment]
Yes, the method described above is the right way to obtain a page's text content. I'm closing this issue as answered. If you need more help, please contact us on IRC.
