### ISSUE TITLE
Problem with some letters when zoom value is 100% in IE

### ISSUE THREAD

**Issue by haql** [mozilla/pdf.js#6732]
Dear brothers,

I am using pdf.js at link http://mozilla.github.io/pdf.js/web/viewer.html to open the PDF file and I have a problem that the letter 'i' and 'r' were upper case(or higher) when the zoom value of pdfjs is between 96% to 103% and the zoom value of browser is 100% on IE. I am using IE version 11.0.9600.17031.

Please see the attachments for more informations.

Thanks!
![100-percent](https://cloud.githubusercontent.com/assets/16188652/11625310/9c4b5172-9d0c-11e5-9ddb-cfdd833edda1.PNG)
![110-percent](https://cloud.githubusercontent.com/assets/16188652/11625313/a353e452-9d0c-11e5-8062-66702ebac3d7.PNG)
[PRB-DataOverview-2012.pdf](https://github.com/mozilla/pdf.js/files/53823/PRB-DataOverview-2012.pdf)

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
