### ISSUE TITLE
Title of the document is not visible with proper color 

### ISSUE THREAD

**Issue by SanvidManiyar** [mozilla/pdf.js#6737]
Hi All,

we are using PDF.js and observed that following types of documents are not rendering correctly in IE11, Chrome and FF. it lost its color and header tittle.
[Florida Industrial MarketView Q3 2015.pdf](https://github.com/mozilla/pdf.js/files/55597/Florida.Industrial.MarketView.Q3.2015.pdf)

I have open the document from the link http://mozilla.github.io/pdf.js/web/viewer.html and it gives me the same result. find the attached screen.

![image](https://cloud.githubusercontent.com/assets/6779439/11658632/9ed870c2-9de9-11e5-9107-c3bd353268ba.png)

is there any solution for this issue  ?

Regards,
Sanvid

**Comment by Snuffleupagus** [comment]
It seems that PR #6606 would improve this quite a bit.

**Comment by SanvidManiyar** [comment]
Hi All,

We have tried replacing files "pattern_helper.js" with the latest version but it gives javascript error while loading a document. 

Is there any other approach to get rid of this problem ?

Regards,
Sanvid

**Comment by SanvidManiyar** [comment]
Hi All,

Could you let us know that which JS is responsible to render the header content is it "pattern_helper.js"  ? So, that I can also try to improve at our my end.

Regards
Sanvid

**Comment by timvandermeij** [comment]
I don't think just updating `pattern_helper.js` is enough. You will need to update all files.

**Comment by SanvidManiyar** [comment]
Hi,

Thanks For your reply. I have also change the other files mentioned with the latest version of PDF.js but it seems that the base version which is used to develop a solution of #6606 is different from the latest version. 

Replacing other mentioned files with pattern_helper.js gives an error while loading the document.

Is it possible to merge this change with the latest version ? so that we can have this improvement in latest version of DDF.js.

Regards,
Sanvid

**Comment by timvandermeij** [comment]
Yes, the #6606 has merge conflicts, so the original file has changed since that patch. Because that PR has not been merged and is not ready yet, it is not recommended to use it yet, but if you really need it you can apply the changes from https://github.com/mozilla/pdf.js/pull/6606/files manually.

**Comment by SanvidManiyar** [comment]
Hi,

Thanks you for your reply.

With a view to apply the changes, Could you suggest which version should I take as base version as the latest one is not supporting change files ?

Regards,
Sanvid
