### ISSUE TITLE
This document does not print correctly with firefox

### ISSUE THREAD

**Issue by bigfatbird** [mozilla/pdf.js#6738]
https://www.dropbox.com/s/d2j81j6fbblcx2u/Hausaufgaben_6.pdf?dl=0

The Document here won’t print properly with firefox... If I print this with preview for example it works well.

Not sure if this is a bug, but i wanted to let you know this. 

Might be a problem with LaTeX and I had this more than once with pdfs containing LaTeX.

**Comment by timvandermeij** [comment]
Could you provide a bit more details? It is a font problem, are there blank pages, is the print blurry? What is you OS name/version and browser name/version?

**Comment by bigfatbird** [comment]
My OS is OS X 10.11.1 and I’m printing with the default driver for my Canon Pixma MP 610.

The pdfs look blurry, and are rendered incorrectly. 
Preview.app prints them just fine, firefox (42) prints them incorrect.

**Comment by timvandermeij** [comment]
If you could provide screenshots, then that would be very helpful. Anything you can provide to make the issue clear might speed up its resolution. Thanks.

**Comment by bigfatbird** [comment]
Differences between prints expected and final results. Another example document
In both softwares it looks fine, but being printed out... just no! 


https://www.dropbox.com/s/2gqlafq05mju8nn/Hausaufgaben_2-1.pdf?dl=0

![img_0567](https://cloud.githubusercontent.com/assets/1159341/11671884/95bf8ada-9e0b-11e5-9ba2-d1039cf4d937.jpg)
![img_0568](https://cloud.githubusercontent.com/assets/1159341/11671886/95c11c42-9e0b-11e5-9eaa-39f3bc526819.jpg)
![screen shot 2015-12-09 at 00 17 49](https://cloud.githubusercontent.com/assets/1159341/11671882/95bde5ae-9e0b-11e5-9f75-148374df6987.png)
![screen shot 2015-12-09 at 00 18 20](https://cloud.githubusercontent.com/assets/1159341/11671883/95be3946-9e0b-11e5-92b5-e45fd538b15a.png)
![screen shot 2015-12-09 at 00 18 49](https://cloud.githubusercontent.com/assets/1159341/11671887/961780f0-9e0b-11e5-9b88-eab2766086f5.png)
![screen shot 2015-12-09 at 00 19 40](https://cloud.githubusercontent.com/assets/1159341/11671885/95c1253e-9e0b-11e5-9e82-8d4be4bb45c3.png)

**Comment by timvandermeij** [comment]
Judging by the images, this might be related to #6498 where we lose the font when printing, causing this kind of rendering.

**Comment by bigfatbird** [comment]
I don’t know 😅

**Comment by timvandermeij** [comment]
Closing as fixed by #7694.
