### ISSUE TITLE
Cannot mark a single line in one in one document

### ISSUE THREAD

**Issue by rugk** [mozilla/pdf.js#6744]
Have a look here: https://letsencrypt.org/documents/LE-PITRA-Results-Sept-8-2015.pdf
![marksingleline](https://cloud.githubusercontent.com/assets/11966684/11756138/220e33da-a058-11e5-8e6f-698a843242e6.PNG)

Firefox 42

**Comment by rugk** [comment]
Okay, just tested this with another PDF reader and I see the same result.

Feel free to close this issue if you think it is invalid.

**Comment by timvandermeij** [comment]
This is also the behavior of Adobe Acrobat/Reader and it has to do with the way the PDF draws its text fragments. Therefore I'm closing this.
