### ISSUE TITLE
Highlighting all matches causes the page to jump while scrolling

### ISSUE THREAD

**Issue by Quicksaver** [mozilla/pdf.js#6746]
STR:
1 - open http://arxiv.org/pdf/1509.03893v1.pdf (tested only in Nigthly with e10s enabled, but I've had users report this to me in other setups);
2 - make sure "Page Fit" is selected as view, it's easier to reproduce like this but I've managed to reproduce it with other zoom/view factors applied;
3 - search (Ctrl+F) for "alice" and click the "Highlight all" button;
4 - press F3 three times so that again the first of three instances of "alice" is active (it does not occur when the first instance of "alice" is active for the first time!);
5 - click in the document to focus it and press "home" key to jump back to the beginning;
6 - scroll down with "page down" button until you are at around page 7 or 8 and it should jump ahead to page 10 where the first instance of "alice" appears.

I've found this is because [TextLayerBuilder.renderMatches scrolls the match into view indiscriminately](https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js#L213-L216) every time a page is (re)rendered, even while just scrolling (close) to it.

Here's how I've fixed it in my add-on FindBar Tweak: https://github.com/Quicksaver/FindBar-Tweak/commit/c48dc2d5efa480e163064d15e5ca3e3e2bd08c82
- PDFFindController.nextMatch sets a flag to show the current match;
- PDFFindController.updateMatchPosition only actually scrolls to the match when this flag is set, and resets it immediately after scrolling.

**Comment by timvandermeij** [comment]
I can indeed reproduce this issue using the mentioned steps. Would you be interested in creating a pull request to fix this in the PDF.js codebase too?

**Comment by Snuffleupagus** [comment]
Given that this isn't the only existing problem related to "Highlight all", it would perhaps be a good idea to try and fix issue #5561 as part of this too.

**Comment by Quicksaver** [comment]
Done and done. :)
