### ISSUE TITLE
Mobile phone display abnormal

### ISSUE THREAD

**Issue by HawkLu** [mozilla/pdf.js#6750]
My object need online pdf,used this plug-in,opend pdf the page number is right，but no content,there is a picture of my pdf files.

**Comment by timvandermeij** [comment]
There is not nearly as much information as required for us to look into this issue. Please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md carefully and provide the mentioned information (OS name/version, console warnings, details about the hardware, et cetera). Closing as incomplete for now.
