### ISSUE TITLE
Presentation mode does not work on Fennec

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6752]
Platform: Android
Browser version: Firefox Mobile 43.0b4
Screen orientation: Portrait

1. Visit https://mozilla.github.io/pdf.js/web/viewer.html in Firefox Mobile (Fennec)
2. Tap on the presentation mode button.

Observed bugs:

- At the first time I saw the toolbar at the top, behind the page.
- There is no way to navigate to a different page.

**Comment by timvandermeij** [comment]
Possibly a duplicate of #5981.

**Comment by timvandermeij** [comment]
Closing as duplicate of #5981.
