### ISSUE TITLE
Chunked requests question

### ISSUE THREAD

**Issue by meltuhamy** [mozilla/pdf.js#6756]
When chunked requests are made, I noticed there's an initial GET for the pdf, which comes back with the accepted ranges header that tells pdfjs to request chunks.

My question is, once this is done, that request is allowed to proceed, and at the same time, chunked requests for the file are made. Is this necessary? Can't we abort the original request once we know we can ask for chunks, so it doesn't load the same data twice?

**Comment by yurydelendik** [comment]
Right now only FF don't interrupt initial request and only when streaming is not disabled. That will allow reduce amount of range requests. (we have plans to implement in all browsers when Streams API will be spec'ed.) Range requests are typically slower than loading entire file. We aware that some portions of the data can be loaded twice, however that is a trade off to make appearance of the first pages faster. Real win is be when PDF is linearized (web optimized). See also #5263.

Closing as answered.
