### ISSUE TITLE
Add overflow assertions to the various string<int> functions

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#6759]
https://github.com/mozilla/pdf.js/issues/6397#issuecomment-164954332 Would have been a lot easier to find had there been an assertion checking that string16 didn't go out of bounds of the 16bit number.

**Comment by yurydelendik** [comment]
we can add `//#if PRODUCTION` with asserts to not affect the performance, once advanced compilation is in working order we can use e.g. "release" constant and introduce debug assert which we will remove in production.
