### ISSUE TITLE
pdfjs-dist 1.3.94 throwing error

### ISSUE THREAD

**Issue by viz** [mozilla/pdf.js#6760]
using react-pdfjs 1.0.1 which has pdfjs-dist as a dependency.

In the last hour pdfjs 1.3.94 was released and I'm now getting:

Uncaught TypeError: Cannot read property 'PDFJS' of undefined

**Comment by yurydelendik** [comment]
@viz Could you post link to the complete example?

**Comment by viz** [comment]
With irrelevant stuff removed...

```
import React from 'react';
import { Button, Modal } from 'react-bootstrap';
import PDF from 'react-pdfjs';

const MyLargeModal = React.createClass({
  render() {
    return (
      <Modal {...this.props} aria-labelledby="contained-modal-title-lg">
        <Modal.Header closeButton>
          <Modal.Title id="contained-modal-title-lg">{this.props.title}</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <PDF file={this.props.sampleUrl} />
        </Modal.Body>
        <Modal.Footer>
          <Button onClick={this.props.onHide}>Close</Button>
        </Modal.Footer>
      </Modal>
    );
  }
});
```

**Comment by viz** [comment]
![http___localhost_8888_product-list_is_not_available](https://cloud.githubusercontent.com/assets/12402/11831356/0ac90cec-a402-11e5-983d-06b803437708.png)

**Comment by viz** [comment]
whoops - accidentally closed the issue

**Comment by viz** [comment]
Worked previously when pdfjs was at version 1.3.78. Only started to see this problem when we re-installed node modules.

**Comment by yurydelendik** [comment]
Looks like it's a problem with webpack, and we don't support webpack atm. The snippets above are not really helpful. Can you create a sample project with react-pdfjs 1.0.1 and document steps to reproduce the issue including build steps? This can speed up the issue resolution.

**Comment by yurydelendik** [comment]
I think the simple way will be to remove UMD headers from the inside of the pdf.js and pdf.xxx.js files.

**Comment by viz** [comment]
I'll have a look - will try to create a small sample project showing the issue

**Comment by rlucha** [comment]
Last working version for us was 1.3.90.

The only hint I've found is in https://github.com/mozilla/pdfjs-dist/blame/07affac44670de2ec4886d6ffd3f0641c0556f62/build/pdf.js#L38
