### ISSUE TITLE
PDF.js Not Working in Ipad

### ISSUE THREAD

**Issue by madhav1985** [mozilla/pdf.js#6761]
I am getting the following error i tried to load the sample pdf in ipad (Apple Webkit 534.46) version/5.1 mobile/9B206 Safari/7534.48.3

Error:-
      TypeError:Undefined is not a function {near..} bind(this) Reject(TI..).

When  i tried to open pdf.js in ipad with safari browser from webapplication i am getting the following error.
   Waring: Unhandleded rejection: TypeError :null is not an object

**Comment by madhav1985** [comment]
I tried adding the new Compactabilty.js but still not working.
If any one provides me some fast solution it would be great

**Comment by madhav1985** [comment]
![safaribrowserissue](https://cloud.githubusercontent.com/assets/16306738/11838174/42e0ae06-a40b-11e5-8c42-a5f200023013.jpg)

**Comment by ralphjasonXDD** [comment]
@madhav1985 are you using ios7?

**Comment by yurydelendik** [comment]
Closing as incomplete
