### ISSUE TITLE
Chrome Crash (Ow snap)

### ISSUE THREAD

**Issue by ralphjasonXDD** [mozilla/pdf.js#6763]
The following file produces error (Ow Snap error in page 2 of this document) in Google Chrome Version 47.0.2526.106 m, Windows 8

I'm using this version of pdf.js
pdf.js 1.3.94
pdf.worker.js 1.3.94

**Comment by ralphjasonXDD** [comment]
I also tried it in the demo page, it also snaps.

**Comment by timvandermeij** [comment]
Firefox does not crash, but there are performance issues and page 2 takes forever to load. This definitely needs improvement.

**Comment by timvandermeij** [comment]
The file link is no longer available. Closing until a new one is provided.
