### ISSUE TITLE
Filename with '&', '#' and '=' not opening in pdf js

### ISSUE THREAD

**Issue by lakshajit** [mozilla/pdf.js#6768]
Hi, 

I recently noticed that pdf filename with '&', '#' and '=' was not opening in pdf js. Its showing "

PDF.js v? (build: ?)
Message: Missing PDF
"file:///storage/emulated/0/JS_"

and the actual filename is "JS_&_sample.pdf"

Can anyone please help me to understand this issue?

**Comment by Snuffleupagus** [comment]
As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, you need to use `encodeURIComponent()` for the URL. Closing as answered.

**Comment by lakshajit** [comment]
Hey @Snuffleupagus, Thanks for quick response..:)
