### ISSUE TITLE
Transform to resource transform when stroking pattern

### ISSUE THREAD

**Issue by dsprenkels** [mozilla/pdf.js#6769]
Alternate title: _Applying #6684-similar fix to stroke_
#6684 makes sure the "current" transformation, at the moment of filling radial gradients is the `baseTransform` (that of the rescource (page), as it says in the specs). However, this should also be fixed in [`CanvasGraphics_stroke`](https://github.com/dsprenkels/pdf.js/blob/a9081653fc565eb72c3eb5142c17088cb162e7ce/src/display/canvas.js#L1052).

**Comment by timvandermeij** [comment]
Are there testcases available that are currently broken because of this?

**Comment by dsprenkels** [comment]
Currently, not. But it is not hard to write one.
[issue6769.pdf](https://github.com/mozilla/pdf.js/files/65427/issue6769.pdf)

Screenshots:

PDF.js (f93a220):
![pdfjs](https://cloud.githubusercontent.com/assets/439973/11871161/ea74e5de-a4cd-11e5-9229-cd023dac18a0.png)

Reference (evince):
![evince](https://cloud.githubusercontent.com/assets/439973/11871184/2771e464-a4ce-11e5-8702-3b69fc18b071.png)

**Comment by dsprenkels** [comment]
Btw. I do not mind to fix this. But you may also label this as a good beginner bug, because a new developer can use the changed in #6684 as a lead for a fix.

**Comment by timvandermeij** [comment]
Thank you for the update. If you are willing to fix this, feel free to make a pull request so we can review it.

**Comment by dsprenkels** [comment]
I've been screwing around with this for some minutes. This complex is, because of the stroke width, a bit harder than expected. It will be necessary to fix the matrix transformation of the pattern itself, when dealing with pdf files like the one below.

I guess you can yet remove the `5-good-beginner-bug` label; sorry.

[issue6769.pdf](https://github.com/mozilla/pdf.js/files/65511/issue6769.pdf)
![screenshot from 2015-12-17 15 58 15](https://cloud.githubusercontent.com/assets/439973/11872699/06035282-a4d7-11e5-8d1b-691ea63c7cd6.png)

**Comment by timvandermeij** [comment]
Done. No worries, take as much time as you need, it's already great that you are willing to look into it! You can find us on IRC if you need any help with this.
