### ISSUE TITLE
Refactor PDFJS global var usage and move it initialization into single file

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#6779]
for v1.x we are going to keep supporting accessing PDFJS.xxxx members, however for future (e.g. v2.0) we shall probably rely only on module exports keeping that single file as compatibility feature.

TODO:
- [x] move all preferences from api.js into parameter object for related methods (e.g. disableRange is parameter for getDocument, and externalLinkTarget for AnnotationLayer.render)
- [x] refactor global PDFJS usage/assignments from all core/, shared/ and display/ , keep them in the single file e.g. src/display/globals.js

**Comment by shikhar-scs** [comment]
Is this issue still up @yurydelendik ?

**Comment by timvandermeij** [comment]
You're right, both tasks should be done already when the last pull request above is merged.

**Comment by shikhar-scs** [comment]
Thanks @timvandermeij for confirming. I'll look up for something else :+1:

**Comment by Snuffleupagus** [comment]
Closing, since the remaining TODO was fixed by PR #9493.
