### ISSUE TITLE
fakeWorkerFilesLoadedCapability promise is resolved too early

### ISSUE THREAD

**Issue by bjrmatos** [mozilla/pdf.js#6783]
hi! [as i mentioned in a comment](https://github.com/mozilla/pdf.js/commit/b084dc09eea7da13987ba5cda7055e21cddafd38), i'm working in a node.js application that works with pdf files, i'm using the pdfjs parser (`getDocument` method) to get page count from pdf.

i have noticed that the `fakeWorkerFilesLoadedCapability` promise is resolved too early, causing my node.js app never respond..

showcase: 

![showcase](https://cloud.githubusercontent.com/assets/4262050/11915859/2f88ddb4-a687-11e5-98cb-15ff1c8b3d8d.gif)

as you can see, in my first test my app never respond (timeout is reached), but in my second test if i resolve the `fakeWorkerFilesLoadedCapability` promise in the next tick (with `setTimeout`) everything works normally.

to make pdf.js work in node.js i am using this code with latest `pdfjs-dist`@1.3.114:

```js
// from https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js
var DOMParserMock = require('./domparsermock.js').DOMParserMock;

// HACK few hacks to let PDF.js be loaded not as a module in global space.
global.window = global;
global.navigator = { userAgent: 'node' };

global.PDFJS = {
  workerSrc: true // value to make it work inside iron-node and electron
};

global.DOMParser = DOMParserMock;

require('pdfjs-dist/build/pdf.combined.js');

module.exports = function parsePDF(pdfBuf, cb) {
  var pdfData;

  try {
    pdfData = new Uint8Array(pdfBuf);

    global.PDFJS.getDocument(pdfData).then(function(doc) {
      cb(null, doc);
    }).catch(function(err) {
      cb(err);
    });
  } catch (uncaughtErr) {
    cb(uncaughtErr);
  }
};

```

**Comment by bjrmatos** [comment]
i'm using node.js 0.10.41 on iisnode, but executing pdf.js from [electron](http://electron.atom.io/) (a weird combination, i know..).

strangely, pdf.js works normally in a normal node.js app (without iisnode or electron), but if i put my app on iisnode the `fakeWorkerFilesLoadedCapability` never gets resolved

**Comment by yurydelendik** [comment]
I don't this it's related to the commit you commented on -- you are wrapping different line in your movie.

Since it works fine in the node.js, I would assume it's a problem with your environment. Right Promise resolution shall let you bind then latter in the calling code. Looks like there is a defect in Promise implementation you are using then.

**Comment by bjrmatos** [comment]
you're right the problem is not related to the commit i have commented, but it is related to set up of the fake worker.

the part that interacts with PDF.js lies in [electron](http://electron.atom.io/), which ships with node.js v4.x.x. and its Promise implementation.

i will test with node v4 to see if this problem occur..

**Comment by bjrmatos** [comment]
i'm closing this because it works on node.js 4, i will check if there is some dependency in my app that override the Promise object. thanks anyway
