### ISSUE TITLE
Then install v1.3.114 in to SeaMonkey 2.39 user can't see some addon's propitiates

### ISSUE THREAD

**Issue by VictorVG** [mozilla/pdf.js#6784]
Then install v1.3.114 in to SeaMonkey 2.39 user can't see some addon's propitiates - home page URL and rating URL: 

Please, see screenshot's:

v1.3.100 - all fields is visible:

![1 3 100](https://cloud.githubusercontent.com/assets/906886/11916445/3af97544-a6e8-11e5-9dd5-10ae17231a28.png)

v1.3.114 - only some fields is visible:

![1 3 114](https://cloud.githubusercontent.com/assets/906886/11916448/6be90b6a-a6e8-11e5-95c8-8985dd705e38.png)

I use home page URL (added in to bookmark, but :)) for goto addon's home page and search update...

**Comment by timvandermeij** [comment]
This also happens in Firefox after the add-on signing update. @yurydelendik Do you have any idea what causes this? Maybe the change of add-on ID?

**Comment by VictorVG** [comment]
Personally, I did not change year - just put on your page, but in principle the idea of the change of ID seems reasonable. Let's try. True other signed additions withdraw their description and the full URL, but you never know until God is asleep :)

**Comment by yurydelendik** [comment]
The addon is not maintained at the AMO (looks like the text was taken from the https://addons.mozilla.org/en-US/firefox/addon/pdfjs/)

Is there a way to specify this text for unlisted addons? We can automatically sign only this kind.

**Comment by VictorVG** [comment]
So they have built it into a fox, so the sense in it in a separate module no. Let's leave vyod the same text that would blloko 1.3.100 - a description, URL, and instead Talkback I would have made a note that the module is integrated into the FF, because in the list of add-ons not updated.

Personally, I do not really need a description, but easy to quickly navigate through URL - this is a useful item. Now I have to get through bookmarks Git-and there is the benefit of a number of projects that are interesting to me, and my sources I rarely invest because of the fans - the kindergarten suddenly accumulates to get into the conversation of adults. :)

**Comment by yurydelendik** [comment]
I tried to change properties for unlisted addon. For some reason we are missing some fields:

<img width="743" alt="screen shot 2015-12-21 at 8 02 37 am" src="https://cloud.githubusercontent.com/assets/1523410/11932235/7bc0fde6-a7b9-11e5-8733-12c8567436b7.png">

I can see name and description at https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/metadata.inc -- are we missing summary?

@VictorVG can you check if screenshot is visible now on SeaMonkey?

**Comment by VictorVG** [comment]
That now looks like a property page add-on (locale ru-Ru). Have a look at the portable profile to the working copy as not to spoil the other machine (Now let down to its network).

PDF.js:

![screen-2015-12-21_19-25-08](https://cloud.githubusercontent.com/assets/906886/11935481/1552ab1c-a819-11e5-9851-5fef3cf36fb6.png)

ReminderFox:

![screen-2015-12-21_19-26-53](https://cloud.githubusercontent.com/assets/906886/11935492/22a4cdc2-a819-11e5-9531-9cb926864b23.png)

**Comment by yurydelendik** [comment]
ReminderFox is listed addon on AMO, developer version of PDF viewer is not. (We still have discontinued version of PDF viewer, but that's not related to the latter).

PDF.js are not gaining anything by fixing Firefox ability to get info for unlisted addons: users that install our addon are beta users and testers (or users who used https://github.com/mozilla/pdf.js to install it, which says it's "Development Version").

Closing as won't fix.

**Comment by yurydelendik** [comment]
> new versions after v1.3.114 not replaced record and not removed old version

See also https://github.com/mozilla/pdf.js/pull/6773 and https://github.com/mozilla/pdf.js/issues/6137
