### ISSUE TITLE
HTTP request for PDF file is missong Cookie header

### ISSUE THREAD

**Issue by ntoniazzi** [mozilla/pdf.js#6790]
Hello,
we are using pdf.js (v1.0.1040 997096f) in a production application. All traffic is in HTTPS, and the user needs to be identified to access the documents. pdf.js is loaded in an iframe.

Yesterday, I upgraded firefox to 45 and could not load any document anymore : all requests to the PDF files are redirected to a login page (302). When requesting the PDF file, the cookie header is not sent anymore.
I'm not sure it's a pdf.js issue, could be firefox.
Thanks.

**Comment by timvandermeij** [comment]
There is not much we can do if we cannot inspect your environment. Could you set up a demo location somewhere that we can access?

**Comment by yurydelendik** [comment]
> we are using pdf.js (v1.0.1040 997096f)

Do you have the same issue with newer version of PDF.js?

> I'm not sure it's a pdf.js issue, could be firefox.

Use mozregression (see http://harthur.github.io/mozregression/) for find a range when Firefox stopped working for your solution. And report this information at https://bugzilla.mozilla.org/

**Comment by ntoniazzi** [comment]
@timvandermeij You can see the problem [here](https://www.bdu-irp.fr/test/pdfjs.php). 

`pdfjs.php` initiate the session and put a value inside. `reader.php` tries to get it : 
```php
<?php

session_start();

if (!isset($_SESSION['user'])) {
    header('HTTP/1.0 204 No Content');

    exit;
}

readfile('annuaire.pdf');
```
I tried to put the demo on a server without HTTPS and it works. I tried another server with HTTPS and it worked too. Could be something with the HTTP headers.

**Comment by yurydelendik** [comment]
@ntoniazzi The link above does not work for FF43 as well

**Comment by timvandermeij** [comment]
For me the cookie header contains "PHPSESSID=m3q7g72cbtojk83rjflah4pu01" and the PDF is shown. This is with Firefox 43.0.1 on Windows 10 x64.

I'm not sure how/if PDF.js can cause this behavior.

**Comment by ntoniazzi** [comment]
@yurydelendik You tried the link with FF43 but the demo was broken, sorry. Shouldn't work anymore ;)

@timvandermeij It's working fine with chrome too. I have little time now but I'll try to play with mozregression. I suspect a combination of server configuration and browser behaviour.

Thanks.

**Comment by timvandermeij** [comment]
Closing for now until it is more certain that this is in fact a PDF.js issue. I really suspect it to be a server/browser issue as you also point out. We can reopen this when more information is provided about why PDF.js would be at fault here. Thanks.

**Comment by ntoniazzi** [comment]
Hello,
I figured out the origin of the problem : there is a Firefox preference named [`network.cookie.cookieBehavior`](http://kb.mozillazine.org/Network.cookie.cookieBehavior). I had it set to `1`, which means than only cookies from the originating server are allowed. When I set it back to the default value of `0`, all cookies are accepted and everything works fine.
This doesn't explain everything, though : I'm only using one server.

Thanks anyway.

**Comment by gpilot24** [comment]
I have the exact same issue with FF 45.0 developer edition, 2015-12-11 build.  Requesting a pdf file (hosted on my server via Owncloud) in firefox 28.0 (Waterfox) opens an instance of the firefox pdf viewer and displays the file. (Soapbox ON..,I hate Astralis and the trend to hide everything; apps and web pages have become so simple they are becoming useless..Soap OFF) .  Going to the exact same site, same file, same server attempting to open the on FF45 developer ed:  The pdf viewer opens, then error "PDF.js v1.0.712 (build: 6969ed4)
Message: InvalidPDFException" is shown in a red box and the pdf does not load.

Toggling the user pref network.cookie.cookieBehavior;0 (which I do not want) allows the pdf viewer to function.  Toggling back to "1" repeats the same error.

Common items:  Owncloud 8.2.2. on Ubuntu linux server
Same PC: Win7 x64
Same file reguested on server, error happens with any pdf, actually downloading the file works fine,
this is a viewer issue

Only difference is the browser (FF 28 vs FF 45).  
FF45 has Classic theme restorer, works like a charm.

**Comment by MohandSadakah** [comment]
`<!DOCTYPE html>
<script>
"use strict";

// At javascript.info, we use Google Analytics for statistics,
// so there should be some cookies
alert( document.cookie ); // cookie1=value1; cookie2=value2;...
</script>`
