### ISSUE TITLE
forms

### ISSUE THREAD

**Issue by dantart** [mozilla/pdf.js#6797]
is it possible to insert input forms ?

I'm not looking for a fillable PDF, but insert HTML input forms in specific coordinates of PDF, fillables, zoomables (as the rest of the document) ...

**Comment by timvandermeij** [comment]
If you mean AcroForms, the closest working version we have is https://github.com/mozilla/pdf.js/tree/master/examples/acroforms. It's not in the core of the library yet, but there is #6172 to do that partially. Closing as answered.
