### ISSUE TITLE
IE11 - strange rendering of text

### ISSUE THREAD

**Issue by Uffman** [mozilla/pdf.js#6798]
We have problem with text rendering on IE 11. This problem only occurs on specific Windows 7 computer. Viewer works fine in Chrome. On other computers in company this problem does not occur. 
All security and internet settings are the same as on other computers. 
There are no javascript errors in console.

![3](https://cloud.githubusercontent.com/assets/1281907/11993809/95799e72-aa35-11e5-975a-57825fa59df8.png)

![4](https://cloud.githubusercontent.com/assets/1281907/11993805/95772fde-aa35-11e5-9ad0-8b62b366bb29.png)

![5](https://cloud.githubusercontent.com/assets/1281907/11993807/95776990-aa35-11e5-9ebc-c04aebc35775.png)

![ieversion](https://cloud.githubusercontent.com/assets/1281907/11993804/9576f62c-aa35-11e5-95b7-f500f3fb68e2.png)
![1](https://cloud.githubusercontent.com/assets/1281907/11993808/9578d096-aa35-11e5-86e5-71947b722ff5.png)

![2](https://cloud.githubusercontent.com/assets/1281907/11993806/95772fde-aa35-11e5-8fc1-b4d9284327d7.png)

**Comment by timvandermeij** [comment]
First of all, there is not much we can do without a test PDF document, so please provide one. Secondly, this viewer looks modified and I'm not sure if it is using the latest version of PDF.js, so please try opening your file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar). If it is only on a specific computer, it might also be a graphics driver problem. Please update the graphics driver.

**Comment by timvandermeij** [comment]
Closing for now until more information (mentioned above) is provided.

**Comment by Uffman** [comment]
Thank you for your reply and help. We tried the problem pdfs with your online demo viewer and it was the same problem on the same computer. In the end it was the graphics drive problem.

Thanks a lot for your help
