### ISSUE TITLE
PDFs loading differently between development and production server while using pdf.js - please help.

### ISSUE THREAD

**Issue by ardnirum** [mozilla/pdf.js#6799]
Hi

We are using pdf.js in our application to display thousands of PDFs. 

In the development server (running on CentOS), when we access PDFs, the viewer shows the first page, while the rest of the pages load/download.

Whereas, in the staging & production servers(RedHat OS), the viewer waits for all the pages to download before showing the first page.

What could be the reason?  I am not able to believe that it would be OS based.

Please help.

Thanks
Gopal

**Comment by timvandermeij** [comment]
You have to enable range requests on your server to get chunked rendering. If range requests are disabled, then all contents will be downloaded before the first page shows. Closing as answered.

**Comment by ardnirum** [comment]
Thanks for answering Tim.  I am not aware that the range requests can be done at the server end. Will have to find out how to do that.  Will look for that.  If you have come across any literature/website, which explains the way to do, please suggest.  Thanks again for the response.

Regards
Gopal

**Comment by kp6abhu** [comment]
Hi Tim,
We are also facing the same problem. 
You mentioned that enable range request.
we cant able to find out. how to enable range request in Apache server configuration. 
We are using RHEL server so please explain in detail.

Thanks & Regards
Prabhu.K
