### ISSUE TITLE
Chrome extension bug: Page 2 landscape stretched to page 1 portrait mode on print

### ISSUE THREAD

**Issue by LarryLACa** [mozilla/pdf.js#6800]
For this PDF (Induction record), page 1 is portrait, page 2 is landscape.  When printed from Chrome with the PDJ.js (PDF viewer) extension, page 2 is stretched vertically and squeezed horizontally to fit the page 2 landscape content to the portrait layout used by page 1.  The stretch is visible in print preview and prints the same.

The source PDF is generated by scanning a hand-stamped master document into a PDF.  The scan edges are visible, with slight mis-alignment.   Source and stretched print output are attached.

I'm a Chrome community volunteer working Akshay's help request.  I'm posting the problem here as I've been able to reproduce it with Akshay's source document.  Akshay may have additional comments.  See links below.

Chrome & OS:  47.0.2526.106 (stable 12/15/15) XP;  48.0.2564.48 (beta 12/16/15) Win8.1 
PDF.js: 1.1.527

Problem orginally reported by Akshay Shah on Chrome help forum 11/25/15
 https://productforums.google.com/forum/?#!topic/chrome/TLVMuM9dQSg
See for full discussion and original scanned doc (12/9 post).  
Problem isolated (by me) to PDF.js.

Reported as Chrome bug 563890 11/30/15 by Akshay
  https://code.google.com/p/chromium/issues/detail?id=563890
Status 12/24/15: Unconfirmed. Will probably be deferred as External.

Original scanned PDF: pg1 portrait, pg2 landscape.
[Akshay-Induction Record-fc09.pdf](https://github.com/mozilla/pdf.js/files/71883/Akshay-Induction.Record-fc09.pdf)

Stretched print, created from Chrome 47..106, XP and print to PDF; 
  paper print looks the same.
[Akshay-Induction Record-fc09-XP-Print-PDF.js.pdf](https://github.com/mozilla/pdf.js/files/71885/Akshay-Induction.Record-fc09-XP-Print-PDF.js.pdf)

**Comment by timvandermeij** [comment]
I believe that this is related to #6103, i.e., support for determining the page orientation on a per-page basis. Note that this is a general PDF.js issue, not just for the Chrome extension.

**Comment by LarryLACa** [comment]
@timvandermeij - agreed, same issue as 6103.  This bug notice should be merged/relegated there.

I'm the new kid on the block.  I assume Rob--W (PDF.js owner) will fold this in.  Or can I do that?

thanks, Larry

**Comment by timvandermeij** [comment]
PR #6103 is under review, but it is assumed that a slightly different solution is needed to avoid issues with almost square pages being rotated too. @Rob--W probably knows more about this specific PR than I do. In any case, this issue is now linked with the PR.

**Comment by LarryLACa** [comment]
@timvandermeij  - The fc09 test pdf is a slightly different test case.  Visually inspecting the fc09 PDF, it looks like page 2 is landscape.  The print setup should have rotated pg2 to match the paper stock (or left it to the print device), and then applied a fit-to-page  transform, if requested.  I.e. there are interactions between F2P and autoRotate.

**Comment by Rob--W** [comment]
Thanks @LarryLACa for your detailed bug reports and efforts to help others!

I've pinged the author of the linked PR in case they've forgotten about it.

FYI: There is no difference between printing in PDF.js on a website, or the PDF Viewer Chrome extension. If there is a bug in the Chrome extension's printing behavior, then it also applies to the PDF.js for websites and vice versa.

**Comment by timvandermeij** [comment]
Closing since this is now implemented as a viewer preference thanks to #8043.
