### ISSUE TITLE
500MB+ PDF crashes PDF.js in Chrome

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#6802]
Feedback from the Chrome web store:

> https://hdl.handle.net/10462/eadarc/1525 If you try to load the PDF at the above location by clicking the PDF icon next to "View Options" it loads most of the way and then comes back with "Aww, Snap!" The built in Chrome PDF plugin handles it fine, but it can't search inside the PDF when it's in its own frame whereas your extension can. Do you have any ideas?

I debugged it a little bit. That particular PDF file (http://bishop.slq.qld.gov.au/webclient/StreamGate?folder_id=0&dvs=1450995369427~57) has 568484947 bytes of data (542 MB). Chrome kills the tab around 512 MB due to a memory allocation failure (only for XMLHttpRequest with type `arraybuffer`, with a size that exceeds 512MB). It seems that `resonseType = 'blob'` doesn't cause a crash.

Maybe it's time to add a special path for big PDF files? E.g.:
- fetch (with streaming response bodies) #6126 
- For requests that cannot be streamed at once, use XHR with responseType `blob`, and then use FileReader to read arraybuffers in chunks.

(fetch seems ideal, but it has some disadvantages as I explained in https://github.com/mozilla/pdf.js/issues/6126#issuecomment-130572300)

**Comment by timvandermeij** [comment]
Closing since the fetch API is implemented now and the file is no longer available.
