### ISSUE TITLE
Popup annotations reserve space even when they are hidden

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#6806]
**STR:** Open http://www.nyc.gov/html/dcp/pdf/zone/map8c.pdf.

**ER:** No horizontal scrollbar, since the Popup annotation is hidden by default.

**AR:** The horizontal scrollbar *is* displayed, since the Popup annotation isn't hidden correctly. See screen-shot below.

This is a regression from PR #6792.
/cc @timvandermeij 

---
![popup](https://cloud.githubusercontent.com/assets/2692120/12010143/ca5afb24-ac9a-11e5-9e07-785213664aae.png)

**Comment by timvandermeij** [comment]
The issue here is that the `hidden` attribute is applied on the popup div and not on the entire container. I have an idea how to fix this.
