### ISSUE TITLE
Verify correctness of the `pagechange` event

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6809]
*This issue originites from the discussion at PR #6801.*

The question is whether or not the `pagechange` event should be fired when the page does not change, i.e., when one pressed the right arrow while being on the last page. Now it appears to fire and state that `previousPageNumber` is the last page number plus one. We need to determine what the expected behavior is here in order to not confuse users of the event.

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/pull/6801#issuecomment-167396469:
> The purpose of sending the event with `event.previousPageNumber = val;` in the current code, is to ensure that we update the UI if the user had tried to specify an invalid pageNumber.

**Comment by MattWeiler** [comment]
Would it cause an issue to set both the event.previousPageNumber and event.pageNumber to both be this._currentPageNumber?
This way the UI could still be updated as we'd still fire the event but the event.previousPageNumber would not be out-of-range.

I'm not familiar with the rest of the code-base so I can't say for sure what else in the code registers for this same event and may be affected.

**Comment by timvandermeij** [comment]
Closing as fixed by #6809. The event no longer fires when the pages doesn't change and `previousPageNumber` has been removed because of this.

**Comment by diwakar1911** [comment]
set "eventBusDispatchToDOM": true in viewer.js why isn't anyone telling this!
