### ISSUE TITLE
Support quad points for annotations

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6811]
The PDF reference states that Link and text markup annotations can specify quad points. https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=634&zoom=auto,-246,530 explains this principle. Right now we create one container per annotation, but when quad points are defined, we need to create multiple containers with rectangles defined by a group of eight quad points. Below are known files that will benefit from quad points support, which are files where an annotation takes up multiple lines (which is not too common, fortunately):
- https://blogs.adobe.com/acrolaw/files/acrolaw/comment_print_button.pdf
- https://github.com/mozilla/pdf.js/files/37756/compressed.tracemonkey-pldi-09.pdf (from #6655)

It is also possible that the annotation's rectangle is not valid at all when quad points are specified, in which case we need to use the (at least first eight) quad points to determine the rectangle for the container. Known files are:
- http://linorg.usp.br/CTAN/macros/latex/contrib/pdfcomment/doc/pdfcomment.pdf (page 11)
- http://www.plpdf.com/examples/PLPDF-SDK/Simple_Examples/37_Markup_annotation/markup.pdf

**Comment by THausherr** [comment]
https://issues.apache.org/jira/secure/attachment/12906841/PDFBOX-4074-011922-p5-Annotations.pdf

**Comment by timvandermeij** [comment]
Notes to self for implementing this:

- https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=403&zoom=auto,-215,540
- https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=411&zoom=auto,-215,71
- https://jsfiddle.net/6eLqahpn

**Comment by timvandermeij** [comment]
Quad points are now supported in the core and the API, so this issue is only about the viewer support now.
