### ISSUE TITLE
[Question] Generate a PDF from HTML in the browser?

### ISSUE THREAD

**Issue by Industrial** [mozilla/pdf.js#6816]
Hi.

I'm looking all over the interwebs for a solution to getting a PDF document from a HTML page. In my case I have a form with resume data and I'd like to get a PDF output of the form data. Right now, I don't care so much about the actual format of the output as long as it's readable and presentable :-).

My best bet so far is using [html2canvas](https://html2canvas.hertzen.com/documentation.html) for making a canvas representation of HTML and then using `canvas.toDataURL()` to get a data URL out of that and then I can hopefully stick it in a https://parall.ax/products/jspdf document to generate the PDF. This means I get no hyperlinks in the PDF, since it's just one big image ..

Does pdf.js have any means of generating a PDF from HTML?

**Comment by timvandermeij** [comment]
No, PDF.js is just a renderer and viewer, not a generator. You will need something like jspdf or another generator for this purpose.
