### ISSUE TITLE
Printing all the pages of the PDF

### ISSUE THREAD

**Issue by sohitri** [mozilla/pdf.js#6817]
Based on the latest code on Github, I want to print all the pages of the PDF document (having 14 pages) using window.print(). But what i am getting a 2 or 3 initial pages. If i scroll down to the bottom of the document, then i get 10 pages. Where is the render function for getting all the pages from DOM? Also each page has a blank area in the bottom, but the the size should be ideally of a A4 page. 

I am following the link below
[PDF link] (http://173.10.27.85/pdfjs/web/viewer.html)

but cant find the "processing for printing" portion where all the pages are rendered and showed for printing.

**Comment by timvandermeij** [comment]
You have to do what the viewer does, which is render all pages before calling the print command. See the `beforePrint` method in `web/viewer.js` (specifically https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L1239-L1241).

**Comment by sohitri** [comment]
@timvandermeij  Thanks for your reply. Now I am getting all the pages, but they are all blank. Any idea why this is happening?
