### ISSUE TITLE
Please build the library and components using node make generic components

### ISSUE THREAD

**Issue by shaunc869** [mozilla/pdf.js#6831]
I know I am just being dense here, but I followed the build instructions and built using:

    node make generic components

I then copied the build folder into my project and included the pdf.js file:

    <script src="/backend/newdesign/assets/js/pdfjs/build/pdf.js"></script>

This is for version:

    PDFJS.version = '1.3.148';
    PDFJS.build = '4e9ea35';

And then I get the pop-up saying:

Please build the library and components using node make generic components
![screen shot 2016-01-04 at 10 20 25 am](https://cloud.githubusercontent.com/assets/6071090/12096907/7a639c6e-b2cd-11e5-87e4-286d390da34f.png)

Can you kindly let me know what I am doing wrong? Thanks!

**Comment by yurydelendik** [comment]
If you are using PDFViewer or PDFPageView, you also need to add "/backend/newdesign/assets/js/pdfjs/build/components/pdf_viewer.js". For better results, use pdf.js, pdf.worker.js and pdf_viewer.js included in the [pdfjs-dist](https://github.com/mozilla/pdfjs-dist)

Closing as answered.

**Comment by shaunc869** [comment]
That worked great, thank you!
