### ISSUE TITLE
Hyperlinks won't open from within PDF in Firefox 43.0.3

### ISSUE THREAD

**Issue by jimuntershine** [mozilla/pdf.js#6832]
PDF files created from MS Word Acrobat PDFmaker 10.1 will not open hyperlinks when viewed with Firefox 43.03 default PDF viewer (the hyperlinks work fine in IE8).

The hyperlinks in the Firefox PDF viewer have a special ascii character appended to the address. 
A sample of the problem and screenshot can be viewed at http://www.gndzerosrv.com/test/pdfjs-homepage.htm which presents the PDF in an iframe which provides a link to another PDF.

**Comment by jimuntershine** [comment]
@Snuffleupagus 
Is this is an issue that is still to be resolved?
Or is something I must do on my end somehow?

**Comment by yurydelendik** [comment]
@jimuntershine yes, we need to review/test it. But, if you can, you may experiment on your end with the patch provided at #6834.

**Comment by jimuntershine** [comment]
Thanks you guys for the quick response. :)
