### ISSUE TITLE
PDF find text mis-aligned

### ISSUE THREAD

**Issue by shaunc869** [mozilla/pdf.js#6833]
Hi!

I have a sample PDF I am opening and then running a find on it like this:

![screen shot 2016-01-04 at 12 31 12 pm](https://cloud.githubusercontent.com/assets/6071090/12099729/2a1324c0-b2df-11e5-9911-f19c465d88bf.png)

As you can see the find text looks like off center, I am using bootstrap as well so I wonder if this is causing the issue?

Here are the Chrome debug tools for this element:

![screen shot 2016-01-04 at 12 33 05 pm](https://cloud.githubusercontent.com/assets/6071090/12099771/692b54ca-b2df-11e5-9740-e03a2f524cb2.png)

I can also confirm it's the same for Firefox. Thanks for the help!

**Comment by yurydelendik** [comment]
Can you publish a minimal example online with the issue above? In the past there was issues with bootstap overriding some styles (e.g. #6614). Also is it PDF specific?

**Comment by shaunc869** [comment]
Here you go:

https://pythonversion-dot-promptappointment.appspot.com/backend/pdftest/pdftest.html

Thanks again!

**Comment by yurydelendik** [comment]
You did not add "pdfViewer" class name to the pages container, e.g. `<div id="pdfContainer" class="pdf-content pdfViewer">` mostly it's `position: relative`. We probably shall add e.g. ".pdfViewerPage" to the https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.css#L22.

**Comment by shaunc869** [comment]
Wow that worked great, it's still a little off, is this is the line height issue? How do I fix that?

<img width="342" alt="screen shot 2016-01-04 at 3 11 53 pm" src="https://cloud.githubusercontent.com/assets/6071090/12103258/a21ba24c-b2f5-11e5-9a9c-847fe1c9f66c.png">

I've also updated the link: https://pythonversion-dot-promptappointment.appspot.com/backend/pdftest/pdftest.html

Thanks a lot!

**Comment by yurydelendik** [comment]
> is this is the line height issue? 

Not really. The text selection layer may not match canvas's display perfectly -- it depends on fonts and kerning used in by the PDF generator. What you see is probably okay result.

**Comment by timvandermeij** [comment]
Closing as resolved.
