### ISSUE TITLE
Turnjs/flipbook integration with pdf.js viewer

### ISSUE THREAD

**Issue by smokeyjohnson** [mozilla/pdf.js#6836]
We've started looking at implementing pdf.js with turn.js. We've written a very quick article on this as well as an example viewer. Very crude example just to get things working but it works if someone with more time and effort can get this implemented in a more effective way then that would move things forward greatly! We've hijacked the presentation mode in the standard viewer to use for the turnjs book. Perhaps another "flipbook mode" could be used to host a viewer for the turnjs or any other flip book implementation. 

Hopefully this can help move others forwards. The combination of PDF.js and turn.js could be pretty amazing.

http://www.link-infotec.co.uk/articles/pdfjs-and-turnjs-reader/

**Comment by timvandermeij** [comment]
Cool application! Since there is no PDF.js issue here, I'm going to close this, but feel free to add your project to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications once it is finished. Thanks.

**Comment by iamdeadman** [comment]
Hi, great work. I instantly found so many applications for this in my mind. I was looking on more info on how can I integrate it with angularjs as well. I think there are a couple of wrappers for turn.js in angularjs but I am not able to figure out the integration part that you have done here with the pdf.js to create embedded viewers. can you probably share a reference document or some info on how can I get it working with pdf.js and angular.js

**Comment by yurydelendik** [comment]
> can you probably share a reference document or some info on how can I get it working with pdf.js and angular.js

@iamdeadman As not angular.js experts, we rely on people that knows the subject to create a documentation. If you think that you are comfortable with angular.js, I'll be glad to chat with you on '#pdfjs' IRC channel on the subject. I guess you just do via including pdf.js script tag and providing workerSrc to the pdf.worker.js file as you would do with normal JS app.
