### ISSUE TITLE
How to roll tomcat 8.0 logs daily specifically localhost log file

### ISSUE THREAD

**Issue by ArjunPatil** [mozilla/pdf.js#6844]
As written in title i want Daily rolling file appender for localhost log file.

I tried some configuration in logging.properties file as follow:

added following statement but it wont work.

2localhost.org.apache.juli.AsyncFileHandler.limit = 102400 2localhost.org.apache.juli.AsyncFileHandler.count = 5

**Comment by Snuffleupagus** [comment]
Closing as invalid, since this does not appear to be related to PDF.js (questions about server configurations should be directed to the provider of the server software).
