### ISSUE TITLE
Border line, seprator are not coming properly on Chrome browser

### ISSUE THREAD

**Issue by samit2015** [mozilla/pdf.js#6845]
On Chrome browser, pdf is missing lines, dividers, separators etc...any idea what needs to be done

**Comment by timvandermeij** [comment]
There is not enough information here for us to look into the issue. Please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md carefully and provide the details requested there, with a link to the PDF file being a minimal requirement.

**Comment by samit2015** [comment]
its sensitive data else I wld have given...anyways , I will figure it out by own.
