### ISSUE TITLE
Passing file_name.pdf raw data to pdfJS instead of url?

### ISSUE THREAD

**Issue by YarinSl** [mozilla/pdf.js#6850]
I'm trying to load document using pdfJS and passing data instead of url. The data is the response of $http.get(PATH_TO_PDF_FILE) and its look like that -

pdfFileFromAjaxResponse = 
"
%PDF-1.3 1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj 2 0 obj << /Type /Pages /Kids [3 0 R 7 0 R 11 0 R 15 0 R 19 0 R 23 0 R 27 0 R 31 0 R 35 0 R 39 0 R 43 0 R 47 0 R 51 0 R 55 0 R 59 0 R 63 0 R 67 0 R 71 0 R 75 0 R 79 0 R 83 0 R 87 0 R 91 0 R 95 0 R ] /Count 24

endobj 3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [ 0 0 599 842] /Resources << /XObject << /Im1 4 0 R /ProcSet [ /PDF /ImageC ] /Contents 5 0 R endobj 4 0 obj << /Type /XObject /Subtype /Image /Filter /CCITTFaxDecode /DecodeParms << /K -1 /Columns 2080>> /Width 2080 /Height 2923 /BitsPerComponent 1 /ColorSpace /DeviceGray /Length 46622 stream ;*§; ðòß¹2"MËH%¦¶@UË£àÐlàJÖÀÔ7ØØ-ÒHÃ*2CVF·[ÖsH:RÊEÎÕü>ì©¶ü?ùUîýá¡þÁøò©Ë!{¸È"¯!°·ÿX}aKy áÂ!°±$ä4«È(+xUÜ;Õ))Ú ©ýHl[»øP°ïå0KÔaÃÂ½Ö¼áû¿
      ¡ä6÷_°]õX?!7ÎÁÞAu%dò]kòÁVúÂ¼µð~C8.ÃÿyrÛZWRÛUôØ"#+Ù@ÂØ¦
      Ü°)l¥Gdò86°wD.Ó@ÈñtpUb$Ar&¤3Ã»gQHà^CâöÂÄ4½È5ØuÙ;Ì}Î9srGFÂwnC ì6AØ1 VØÈ ÿÅ°â ÷a rC°Èg,Ûl1K»a Þpí²Ç d7UP¡¶,4F9§ÝÃìá°H À&Û ÝÆÎ9: áÁhDqÃD· WÁÃP" .Q¿Ëe(m±!zÁx¶,cÖ7@ÉDw,¸\ Bäq!áD3ìHÈ*dA\q Ò9::9TxÈj:qlR@¹VÄ[épì B$+¤A¹°² cä)ÃexXîä3»!¦=Úò:`ë Ó8bPáH$c9cÝSÛ ±Ðb#³ @ÁBîÈHãÎÞ ªðØqÂ]8Wl6Æ$ú·Â $íé Ó á3È¸0\D~ÜB0JC
...
"

When trying to use:

var arrayBufferOfPdfData = pdfFileFromAjaxResponse;

var myData = new Uint8Array(arrayBufferOfPdfData); //put it in a Uint8Array

var docInitParams = {data: myData};
PDFJS.getDocument(docInitParams).then(function(pdf){
    //render a page here
});
I get the error and warnning:

"
Error: stream must have data
Warning: Unsupported feature "unknown"
"

anyone knows how to load it or what am i doing wrong?

Thanks!

**Comment by yurydelendik** [comment]
You cannot just pass string into Uint8Array constructor. However you can pass string to the getDocument via object in the data field `PDFJS.getDocument({data: arrayBufferOfPdfData})`. Closing as answered.

In most of the cases ajax() function corrupts PDF data, so it's not recommended to use it. Use XHR with responseType = 'arraybuffer' or overrideMimeType with charset that does not corrupts PDF data, see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Handling_binary_data

**Comment by ithillel-aminev** [comment]
@yurydelendik your answer doesn't solve the problem. It's not about data type, string or object. It's about raw pdf content like " %PDF-1.3 1 0 obj ... ". So that if this content is set in the data property of an object passed to getDocument, result pdf will not be rendered.

**Comment by yurydelendik** [comment]
> So that if this content is set in the data property of an object passed to getDocument, result pdf will not be rendered.

See working example at https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html . There is nothing PDF.js can do if PDF data (string or bytes) was corrupted during ajax transmission or decoding.

**Comment by idevtech** [comment]
@yurydelendik the example in your comment link does not have the input string format " %PDF-1.3 1 0 obj ... " mentioned above. It is some kind of other format. Will the format mentioned above by @YarinSl work if passed to setDocument()?

**Comment by stephanrauh** [comment]
Just in case someone else stumbles over the same problem: the example does have the requested input string format. After decoding the cryptic string with `atob()` (which is  done at https://github.com/mozilla/pdf.js/blob/91a8027acd2df0686351b4ebf9844d8193871f63/examples/learning/helloworld64.html#L19) the resulting string starts with `%PDF-1.7`.
