### ISSUE TITLE
Horizontal lines displayed on certain pages of a PDF

### ISSUE THREAD

**Issue by scottschluer** [mozilla/pdf.js#6851]
I can only reproduce this with a single PDF (which I can't attach due to HIPAA regulations). The first three or so pages of the PDF look like they were merged from an existing PDF document and render just fine, but the remaining pages were all scanned in. All of those pages display in the PDF.js viewer with horizontal lines across them (see screenshot).

If I view the source PDF in Adobe Acrobat, there are no horizontal lines. I'm using v1.2.107.

![screenshot](https://cloud.githubusercontent.com/assets/1582014/12242631/113390b4-b84f-11e5-80a6-7e7b5f3acf60.jpg)

**Comment by timvandermeij** [comment]
Does it still occur with the latest version of PDF.js. Try opening the PDF with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar). Without an example PDF, there is unfortunately not much we can do...

**Comment by scottschluer** [comment]
Yes, it does. I downloaded the latest version during my troubleshooting a couple of days ago. I realize it's not very helpful without the PDF but I figured I'd log it anyways.

**Comment by timvandermeij** [comment]
All I can think of is that it might be a CCITTFaxStream issue, but there is really no way to tell unless there is an example PDF. Is it also not possible to create a reduced test case (for instance only one of the pages, with any sensitive information removed)?

**Comment by scottschluer** [comment]
I'll see what I can do. I'll grab a page but I need to get approval to upload it here so it may be a day or two. Stay tuned...

**Comment by timvandermeij** [comment]
I'm going to close this issue for now, but we will reopen it when a test file becomes available. Without it there appears to be nothing we can do about this.
