### ISSUE TITLE
A webpage using pdf.js viewer does not open in iOS UIWebView.

### ISSUE THREAD

**Issue by neelamc23** [mozilla/pdf.js#6852]
A webpage using pdf.js viewer works perfectly fine on all browsers on desktop and even in iOS Safari. But when that same http link is simply loaded in a UIWebView, I get the error seen in attached screenshot. 

Is there any special handling that is required on either sides (web development and iOS development)?

Thanks.
P.S.: Even the Online Demo link http://mozilla.github.io/pdf.js/web/viewer.html is not loaded (blank screen) in UIWebView but looks perfect in Safari. Please advice.

![img_0117](https://cloud.githubusercontent.com/assets/3431397/12242902/b1f6b20c-b8c1-11e5-9584-ff004d925b01.PNG)

**Comment by timvandermeij** [comment]
I would suggest to file a bug upstream about this as no special actions should be needed for this. Either it's a bug in UIWebView or in your custom application, but it does not seem to be directly related to PDF.js at this point.

**Comment by Tulakshana** [comment]
This is happening to me as well.
