### ISSUE TITLE
Misaligned text selection due to overriding font metrics from dummy invisible font file (used when OCRing)

### ISSUE THREAD

**Issue by rossj** [mozilla/pdf.js#6863]
Whilst upgrading PDF.js, I noticed a potential regression where text selection / highlighting of hidden text in OCRd documents appears vertically offset from the text in the background image.

I tracked the issue down to pull request #6601 (merged in commit bb29e13307a813226e08db6db412b505ab9dc781), which adds the overriding of PDF FontDescriptor metrics with metrics from the header of the embedded font file. Below is a link to a test file that displays the issue, along with screenshots using commit 9a830a7b624679ace8fcae5b91ad80d70d91ed1f and the previous commit 9a830a7b624679ace8fcae5b91ad80d70d91ed1f.

[ocr-highlight.pdf](https://github.com/mozilla/pdf.js/files/88510/ocr-highlight.pdf)

Commit bb29e13307a813226e08db6db412b505ab9dc781
![Commit bb29e13307a813226e08db6db412b505ab9dc781](https://cloud.githubusercontent.com/assets/735679/12287585/4c1bfbcc-b993-11e5-8cdd-dba6fe0b0e11.png)

Commit 9a830a7b624679ace8fcae5b91ad80d70d91ed1f
![Commit 9a830a7b624679ace8fcae5b91ad80d70d91ed1f](https://cloud.githubusercontent.com/assets/735679/12287957/230b5428-b996-11e5-9ce6-f792521ad059.png)

It seems that in order to create the overlaid invisible text, some OCR software uses a dummy TTF file with dummy metric information and a single glyph, and the PDF FontDescriptor information is expected to be used instead. Tesseract OCR uses this technique. You can see a discussion of the method in their code [here](https://github.com/tesseract-ocr/tesseract/blob/7cc7c6f9c282c81be10b4224883eb2bf9e51a3f1/api/pdfrenderer.cpp#L19).

It doesn't seem that Tesseract is changing the PDF FontDescriptor information based on the font that is being OCRd, so it does seem reasonable for them to update the dummy .ttf file to contain the same metrics that are used in the FontDescriptor, which I believe would fix the issue for new PDFs generated by Tesseract. However, this won't help PDFs that are already out in the wild with this descrepancy.

Perhaps it would be possible to detect these dummy fonts and then trust the FontDescriptor information?

**Comment by timvandermeij** [comment]
This might be related to #6509.

/cc @yurydelendik

**Comment by jbreiden** [comment]
@rossj Can you help me determine exactly which font metrics disagree? I am the right person to make an update with respect to Tesseract. Here's the current situation.

[font-metrics.ttx.txt](https://github.com/mozilla/pdf.js/files/128897/font-metrics.ttx.txt)
[simple-1.pdf](https://github.com/mozilla/pdf.js/files/128901/simple-1.pdf)
[pdf-metrics.txt](https://github.com/mozilla/pdf.js/files/128903/pdf-metrics.txt)
![screenshot](https://cloud.githubusercontent.com/assets/4961958/13024493/4e5fc6b4-d1aa-11e5-9531-d158d2f8997a.png)

**Comment by rlucha** [comment]
We have the same problem with our CRD'ed pdf's with tesseract. Is there any plan so fix this in the future?

If we can help in any way to test the issue please ask.

**Comment by rossj** [comment]
Sorry for the delayed response @jbreiden; I missed your reply notification.

I believe the discrepancy is in the `ascent` and `descent` values. In the PDF metrics, `ascent` = 500 / 1000 = 0.5 "text space" units and `descent` = -1 / 1000 = -0.001 text space units. However, pdf.js [overrides](https://github.com/mozilla/pdf.js/blob/9c95d089dea692f2ab4cd4c8b188555d2550b27f/src/core/fonts.js#L2237) these values with those from the TTF font metrics, where `ascent` = 1 / 2048 =  0.00048 text space units and `descent` = -1 / 2048 = -0.00048 text space units.

I believe setting `ascent` in the TTF font metrics to be 1024 should fix the discrepancy. In both cases the descent value is essentially 0 (and is probably only not 0 because the PDF spec says it must be negative).

As a potentially separate but related issue, I believe Tesseract's PDF generator is intended to create half-hight highlights (see this [comment](https://github.com/tesseract-ocr/tesseract/blob/a3ba11b030345d32829b1e8355afea5419978d82/api/pdfrenderer.cpp#L622)). I think setting the PDF font metric ascent to be 1000 (and setting the corresponding `ascent` value in the TTF metrics to 2048) might produce better full-height highlights.

**Comment by jbreiden** [comment]
@rossj Thank you, I raised ascent to 1024 in the TTF and tested in Firefox version 46.0.1. Although there are significant improvements, we're not quite there yet. Any thoughts?

![control](https://cloud.githubusercontent.com/assets/4961958/15878804/d1f36f84-2cd2-11e6-8b70-752590827fd9.png)

![experiment](https://cloud.githubusercontent.com/assets/4961958/15878813/f09eac14-2cd2-11e6-913c-8a85b04085d7.png)

**Comment by jbreiden** [comment]
Actually, I think I can get correct results on Firefox with additional fiddling of the various yMax numbers in the font. Will pick something that looks good and do some wider compatibility testing.

**Comment by jbreiden** [comment]
[align.pdf](https://github.com/mozilla/pdf.js/files/309730/align.pdf)

**Comment by bryanph** [comment]
Any progress on this?

**Comment by jbreiden** [comment]
I just tested against Firefox 52.8.1. Looks even worse, especially copy-paste performance. Would love to discuss with a pdf.js programmer.

**Comment by timvandermeij** [comment]
Closing since most of these files are fixed now, and this issue contains lots of different files with different problems, making it less actionable. The Tesseract problem is still tracked in another issue. If there are remaining issues, please open a new issue per problem.
