### ISSUE TITLE
ChromeApp: integrate pdf.js in Chrome Dev Editor

### ISSUE THREAD

**Issue by jitsingh89** [mozilla/pdf.js#6868]
How can I integrate pdf.js in Chrome Dev Editor for rendering and parsing pdf. I am following this link https://github.com/mozilla/pdf.js.First I have created git clone. then I am opening in Chrome web editor.

**Comment by yurydelendik** [comment]
This question if out of scope of this project. Please contact Chrome Dev Editor vendor to find out a right way to embed an extension to their extension.
