### ISSUE TITLE
Issue: highlight text found in document is wrong position when searching vertical text

### ISSUE THREAD

**Issue by oVuHoangMinhNhat** [mozilla/pdf.js#6874]
I've reported the issue: Highlight text found in document is wrong position when searching vertical text

Could you tell me know about this issue? What is root cause?

Steps to reproduce:
- Access http://mozilla.github.io/pdf.js/web/viewer.html
- Open pdf file (http://web.archive.org/web/20150805202858/http://blogs.adobe.com/CCJKType/files/2012/07/TaroUTR50SortedList112.pdf) has contained vertical text.
- Searching key word: "私の誕生日"

Expected result: The highlight at text "私の誕生日" is right position text.
Actual result: The highlight at text "私の誕生日" is wrong position text.

![search_text_vertical](https://cloud.githubusercontent.com/assets/15086937/12370326/b64128de-bc3f-11e5-8327-1420943d3e48.PNG)

**Comment by oVuHoangMinhNhat** [comment]
Thank you for your understand about scope this issue "4-text-selection". I've added image to make it clearly

**Comment by oVuHoangMinhNhat** [comment]
Dear Tim van der Meij,

I still wait your answer. Could you please share information about this issue?

**Comment by timvandermeij** [comment]
We did not yet look into this issue. When more information is available, it will be posted here.

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.
