### ISSUE TITLE
Progressive loading with non leanerized pdfs

### ISSUE THREAD

**Issue by evivz** [mozilla/pdf.js#6890]
How to enable progressive loading on pdfs which are non leaner? 
I tried to leanerize the files but that increase file size 4 to 5 times if the file has images in it.

Is there any way to handle this?

One of solution I feel is dividing the pdf into multiple pdf each of single page. And then load them one by one in viewer. Is that possible?

Can we play multiple file as single set in single viewer?

**Comment by evivz** [comment]
@timvandermeij  anyone here who can reply this?

**Comment by timvandermeij** [comment]
Linearization is definitely better. I don't really understand why linearization would make the file so much larger; perhaps you need to try another tool for that that does not increase the file size that much.

If linearization is not an option after all, only enabling range requests on the server might help to use progressive loading.

You cannot view multiple files at the same time in one viewer, and for performance that's also not recommended.

Closing as answered. If you have more questions, please contact us on IRC.

**Comment by yurydelendik** [comment]
@evivz the PDF.js is doing it by default when HTTP range requests are enabled on the servers and a browser supports it: the PDF.js is fetching first data needed to display first visible page, then rest of the file. It's doing that for linearized or non-linearized files.

Splitting files into one page documents will increase size of the PDF multiple times.

**Comment by evivz** [comment]
But still is there a way I can try once using multiple pdf files? I tried what you are saying performance is not upto the mark.

**Comment by yurydelendik** [comment]
@evivz it's not clear what you are asking from the PDF.js project contributors, but you can certainly experiment and publish findings and performance results of loading one pdf vs multiple pdfs. Please notice that the environment matters: browsers and hosting my affect your results.
