### ISSUE TITLE
Can not see PDF content on tablet device

### ISSUE THREAD

**Issue by kinjal111** [mozilla/pdf.js#6892]
Hello,
pdf.js is not working on tablet. can see num of pages of pdf but content will be blank page. can you please help me regarding this?
Thanks kinjal.

**Comment by timvandermeij** [comment]
Please read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md carefully before submitting an issue. We need more information to be able to look into this, most importantly the name of the tablet, the OS name and version that runs on it and any console output that you can get.

**Comment by kinjal111** [comment]
Hello, below is my device details

Lenova Tablet
--------------------
- PDf location is at app storage folder of device. path like  'data\201601215822215\201601215846407\201601215923739.pdf'
-browser version 4.1.2
-android version 4.1.2
-pdf.js version - 1.3.88

Another device is
- xolo Q600
- Android version 4.2.1
-pdf.js version - 1.3.88
-browser version 4.1.2

i tested on above both device. its not worked on those device.

its worked on below device
Asus Android Phone

-Android Version - 5.0.2
-pdf.js version - 1.3.88
-browser version 4.1.2


![screenshot_2016-01-18-18-08-20](https://cloud.githubusercontent.com/assets/13674937/12391844/a8e595d0-be10-11e5-953d-7c420d0dcb9c.png)

**Comment by kinjal111** [comment]
Hello, 
 any update??

**Comment by timvandermeij** [comment]
It's most likely the PDF file that is causing issues. Since this has not been provided, there is nothing we can do at this point. Moreover, there have been many fixes in the meantime, so please use the most recent PDF.js version. Closing as incomplete until more information is provided.
