### ISSUE TITLE
Print issue in embedded PDF viewer Cordova / Phonegap

### ISSUE THREAD

**Issue by Rjjp** [mozilla/pdf.js#6897]
Hi all!

I'm using the viewer embedded in a Cordova app. I've embeded it like that:

```
var htmlContent = '<object type="text/html" width="100%" height="100%" data="pdfjs/web/viewer.html?' + paramFile + paramSearch + '"></object>';
	
	if(DEVICE_WINDOWS) {
		MSApp.execUnsafeLocalFunction(function() {
			document.getElementById("rightSection").innerHTML = htmlContent;
		});
```

When printing, the preview (and the printed document) are like a screen capture instead of the whole pdf document. See it here:

![print](https://cloud.githubusercontent.com/assets/6089141/12426773/c5711834-bedb-11e5-9911-e6e54f1626e4.png)

I think is something related with the rendering using window since window corresponds to innerHTML instead of to the whole page. I've tried to change somewhere window by window.parent but still doesn't works. Any idea ?

Thank you in advance !

**Comment by timvandermeij** [comment]
You might need to select the `canvas` elements manually then, but since nobody here is a Cordova developer it might be better to ask the question on a website or IRC channel for Cordova developers.
