### ISSUE TITLE
missing ligatures in this PDF

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#6901]
in page 1, search for "nal labeling". There's a "fi" before, but PDF.js does not report it in its text layer.
It is displayed well though.
[icvgip14_table.pdf](https://github.com/mozilla/pdf.js/files/97600/icvgip14_table.pdf)

**Comment by yurydelendik** [comment]
Adobe Reader has the same issue, Mac OSX Preview has not.

**Comment by ldenoue** [comment]
Chrome PDF viewer (Pdfium) works.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7550.
