### ISSUE TITLE
Demo not rendering properly with Firefox ESR 10.0.12 win32 build, corporate deploy.

### ISSUE THREAD

**Issue by sperlab** [mozilla/pdf.js#6908]
Hi there.

Pdf.js demo page (https://mozilla.github.io/pdf.js/web/viewer.html) never renders correctly within Firefox ESR 10.0.12 win32 build.

This is really kind of strange since it renders perfectly on Firefox ESR 10.0.12 MacOs build as well as Linux amd64 build.

Target operating system is win7 x64 but tests have been carried out on winxp x32 and win10 x64 as well with same results.

All builds come from https://ftp.mozilla.org/pub/firefox/releases/10.0.12esr/

All tests have been done with a fresh install and freshly created user profile.

Corporate build upgrade is not an option right now as soon as it might take months to complete full testing.

Thanks in advance for your attention on this issue.

**Comment by timvandermeij** [comment]
PDF.js was not included in Firefox 10, so I therefore assume you are using the (development) add-on. Firefox 10 is *severely outdated* and should not be used anymore. Support for that version has stopped and compatibility code might have been removed in the mean time. I don't think there is anything we can do about this at this moment, perhaps unless we see some console output or error logs to identify the problem. See also https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by sperlab** [comment]
Thank you Tim for this prompt answer.
Sad to hear that.
This hurts especially as we deploy Mozilla software on every computer in the company !
 
May i just point out that 10.0.12 ESR branch just came up as Firefox 17 release branch. (based on https://wiki.mozilla.org/RapidRelease/Calendar).

So it is not as "severely outdated" as Firefox 10 release branch.

**Comment by yurydelendik** [comment]
> This is really kind of strange since it renders perfectly on Firefox ESR 10.0.12 MacOs build as well as Linux amd64 build.

This suggests that you might have some bad configuration. Please update your graphics drivers and see about:support graphics section information. Also you did not provide any additional information in terms of what "never renders correctly" mean.

**Comment by yurydelendik** [comment]
> May i just point out that 10.0.12 ESR branch just came up as Firefox 17 release branch. 
> This hurts especially as we deploy Mozilla software on every computer in the company !

It's good to hear, but looking at https://www.mozilla.org/en-US/firefox/organizations/faq/ "The ESR will also have a two cycle (12 week)", means your organization shall consider deploying 38ESR and soon start testing 45ESR.

**Comment by sperlab** [comment]
I cannot agree more Yury !

But we are still dependant on the bloody "netscape.security.PrivilegeManager" that stuck us to this build.

Please note that we managed to get good rendering on the win32 build with the 0.8.1334 pdf.js release for general purpose pdf files.

But unfortunately our pdf product data sheets (for which we want to generalize pdf.js as default viewer) seems too complex (overlays, font embedding, ...) and fails to render.

Anyway, thanks for the tips and thanks to you all for the good job.

**Comment by yurydelendik** [comment]
You can always bisect PDF.js and Firefox and find out when particular feature was added/fixed/broken. `git bisect` on the repository for PDF.js and `mozregression` for Firefox. Attaching screenshots and PDFs of samples of your pdf product data sheets might help to give you ideas how to address the issue - probably disabling some feature for some configuration will help you. But 0.8.1334 version is really old and not suitable for production anymore.

**Comment by sperlab** [comment]
Hi Yury. One of my dev team member is now dedicated to test the internal stuff against latest ESR.
You talked about ESR 45. Where could we found a win32 build for that one, even a nightly one ?
