### ISSUE TITLE
Cannot get Annotations working.

### ISSUE THREAD

**Issue by Thomsos** [mozilla/pdf.js#6910]
Hey everyone,
I am following the  [Simple reader with prev/next page controls](http://mozilla.github.io/pdf.js/examples/learning/prevnext.html) example, but I cannot get annotations on any of the PDFs I try. I require the latest pdf.js version through npm.

Help would be appreciated, thank you.

**Comment by yurydelendik** [comment]
See examples at https://github.com/mozilla/pdf.js/tree/master/examples/components . Closing as answered.

**Comment by yurydelendik** [comment]
> I require the latest pdf.js version through npm.

But this you mean `npm install pdfjs-dist` ?

**Comment by Thomsos** [comment]
I was able to get the annotations to appear, however they seem to be off center. my canvas in placed in the center of the page, but the textLayer and annotationLayer elements are in the top right corner.

And yes, i am using npm install pdfjs-dist
