### ISSUE TITLE
Adding copyright watermark to every page 

### ISSUE THREAD

**Issue by melashkov** [mozilla/pdf.js#6911]
Hi am am working on one feature, to add watermark/copyright text to every page when document is being print with pdf.js. I do not need to save file after, just printing with watermark text on the top of the document.
I have find the way to do it, just when page is being rendered in the beforePrint event ```               pdfPage.render(renderContext).promise.then(function() {```
I add this
```javascript
obj.context.fillStyle = 'rgba(66, 66, 66, 0.5)';
obj.context.font = "bold 16px Arial";
obj.context.fillText("This document is generated for Denys Melashkov (c)", 10, 15);
```
The question is I am looking for the guidance or best practice how I can implement this feature in more robust way and also contribute this feature to PDF.js

Appreciate

**Comment by yurydelendik** [comment]
The solution above is one of the ways how to do that, and it's as good as any other. I'm afraid this feature is out of scope of this project and will not be maintained properly in the future. It shall be part of the specific developer customization and shall be maintained by this developer.

**Comment by timvandermeij** [comment]
I agree. I see no use case for this in the general PDF.js library, even though it might be useful for custom solutions. Closing for now.
