### ISSUE TITLE
The latest stable release (v1.3.90) is broken, because it's missing PR 6873

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#6920]
Unfortunately the [latest stable release (v1.3.90)](https://github.com/mozilla/pdf.js/releases/tag/v1.3.90) is broken, since it implicitly includes PR #6846 (which is a requirement for PR #6916).

However, PR #6873 *also* needs to be included, since in its current form the release is unusable.

Given that the release is already out, and is being advertised (e.g. on the mailing list), we should probably try to address this quickly. (I'm not submitting a patch, since I'm not sure if the correct way to address this is to just update the existing release, or to replace it with new a one.)

/cc @brendandahl, @yurydelendik

**Comment by Snuffleupagus** [comment]
`v1.3.91` has been released, fixing this issue.

**Comment by yurydelendik** [comment]
See also 051a0746e17d6769e58b53d0ff2044189bf520fb
