### ISSUE TITLE
JS errors when opening Japanese PDF in IE10

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#6925]
Document tested: http://www.guidetojapanese.org/grammar_guide.pdf

Test method: Going to http://mozilla.github.io/pdf.js/web/viewer.html in IE10 and uploading downloaded PDF with the 'Upload' icon

Errors seen: SCRIPT5007: Unable to get property 'pdfOpenParams' of undefined or null reference 
viewer.js, line 7519 character 3

I also see these errors while scrolling up and down the document: https://gist.github.com/tonyjin/ca739de21aefce587f2a

**Comment by timvandermeij** [comment]
Does this only occur in IE10 or also in other versions/browsers?

**Comment by tonyjin** [comment]
Seems fine in IE11, Chrome, Firefox

**Comment by timvandermeij** [comment]
In that case it's probably some unsupported feature in IE10 that might need a polyfill.

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.
