### ISSUE TITLE
Images don't load with some foreign PDFs in IE10

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#6926]
Documents tested: https://cloud.box.com/s/xiz8vrg198fi0t942e39mzrtjiycphqh and https://cloud.box.com/s/rjsecoc0nzpba3hh173llruuvfzorqb4

Test method: Going to http://mozilla.github.io/pdf.js/web/viewer.html in IE10 and uploading downloaded PDFs with the 'Upload' icon

Errors seen: https://gist.github.com/tonyjin/b3c3bab712317e132177

Screenshot: http://screencast.com/t/HG7NbcqirxTN

**Comment by tonyjin** [comment]
Seems fine in IE11, Chrome, Firefox

**Comment by timvandermeij** [comment]
Sounds like an unsupported feature in IE10 that needs a polyfill.

**Comment by Zen33** [comment]
I had the same problem that only happened in ie10, do you solve that?@tonyjin, thanks.

**Comment by tonyjin** [comment]
Don't have a solution right now @Zen33

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.
