### ISSUE TITLE
PDF.js and Generic Demo Viewer broken on MSEdge

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#6927]
Repro steps: Visit https://mozilla.github.io/pdf.js/web/viewer.html on MSEdge (I used the modern.ie VM found here - https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/)

Screenshot: http://screencast.com/t/CAbhhD5TGIs

Issue seems to be specific to MSEdge.

**Comment by priyajeet** [comment]
Issue in PDF.js
http://i.imgur.com/tQlxvGI.png

'origin' in URL.protoype
