### ISSUE TITLE
Image displayed without color (Red changed to Black)

### ISSUE THREAD

**Issue by WalterYongtaoWang** [mozilla/pdf.js#6931]
[test.pdf](https://github.com/mozilla/pdf.js/files/107056/test.pdf)

Open the attachment. The logo and company name on top right is in black, but it should be in red.

**Comment by THausherr** [comment]
File is correctly displayed with gs. File is incorrectly displayed with PDFBox and two other java products. PDFBox complains about a bad icc profile and uses the RGB colorspace instead.

**Comment by WalterYongtaoWang** [comment]
Chrome display this in blue (should be red). I also reported a bug to them:
https://code.google.com/p/chromium/issues/detail?id=581742

Acrobat Reader and SumatraPDF (MuPDF) can display this correctly in my test.

**Comment by Snuffleupagus** [comment]
I've briefly looked at this PDF file, using http://brendandahl.github.io/pdf.js.utils/browser/.
I'm not sure if it's relevant to the issue at hand, but I noticed that just prior to painting the image (with `/R80 Do`), the Graphics State is set (through `/R79 gs`).
That particular GState includes a transfer function, or an array of four transfer functions to be exact. Hence I'm wondering if we would need to parse those transfer functions, and then apply them when painting the image (in `canvas.js`, similar to how the transfer functions are handled for SMasks).

**Comment by yurydelendik** [comment]
@Snuffleupagus  we can always replace functions by [LUT](https://en.wikipedia.org/wiki/Lookup_table) if we cannot perform color transforms on the the core side. See also #6723 and https://github.com/mozilla/pdf.js/issues/5046#issuecomment-169167290 .

**Comment by yurydelendik** [comment]
Mac OSX Preview displays the same way as us (see screenshots of PDF.js, Chrome, Preview, Adobe Reader):

<img width="1201" alt="screen shot 2016-01-29 at 10 13 21 am" src="https://cloud.githubusercontent.com/assets/1523410/12680779/3ae5dcd4-c671-11e5-940f-6f4de576114f.png">

**Comment by Snuffleupagus** [comment]
@WalterYongtaoWang Are you the author of the PDF file, and if so may we include it in our test-suite?

**Comment by THausherr** [comment]
Here's a document that has both: page 4 has an array, page 11 and 12 have a single function for all colorants. This is a NASA document (I googled "Planetary Systems Branch") , thus not copyrighted.
https://issues.apache.org/jira/secure/attachment/12785801/PDFBOX-3221-023321.pdf

**Comment by WalterYongtaoWang** [comment]
@Snuffleupagus  I'm really sorry, this is from our customer and they don't want to include this PDF file into the test suites.

**Comment by timvandermeij** [comment]
@WalterYongtaoWang Is there any way you could generate a minimal test case, i.e., a PDF file with only the logo in it and no other data? If that's also not possible, we might need to look into creating a reduced test case from this PDF, which will be hard I'm afraid :(

**Comment by WalterYongtaoWang** [comment]
[pdfbug.pdf](https://github.com/mozilla/pdf.js/files/114765/pdfbug.pdf)

I made some changes. Please included this one in your test suites. Thanks.

**Comment by timvandermeij** [comment]
@WalterYongtaoWang Awesome, thank you for providing this file!

**Comment by Snuffleupagus** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1149713 contains another example of a PDF file where some images utilise transfer functions.
