### ISSUE TITLE
electron and web workers

### ISSUE THREAD

**Issue by cvlmtg** [mozilla/pdf.js#6932]
Hi, we are developing an app which runs in the browser and as an electron app. There's been a release that has introduced this code:

```js
if (typeof module !== 'undefined' && module.require) {
   // node.js - disable worker and set require.ensure.
   PDFJS.disableWorker = true;
   ...
```

The problem is that `module.require` exists in electron too, so web workers are disabled even if they should not. I patched pdf.js this way:

```js
if (typeof window === 'undefined' && typeof module !== 'undefined' && module.require) {
   // node.js - disable worker and set require.ensure.
   PDFJS.disableWorker = true;
   ...
```

and it seems to work. I think this patch should not cause other unwanted troubles, so could it be possibile to add it to pdf.js?

**Comment by yurydelendik** [comment]
We cannot introduce `typeof window === 'undefined'` -- the stubs for window object can be added to global. Can we rely on something else, e.g. process?

**Comment by cvlmtg** [comment]
I think it should be ok, I'll check it tomorrow. I was thinking about __filename too, but it doesn't exists in node repl, just when evaluated in a script.

**Comment by cvlmtg** [comment]
ok i checked. "process" can't be used because it exists too in electron. we need to find something else.

**Comment by cvlmtg** [comment]
ok I think this might do:

*node*
```
 ~ node
> process.versions.electron
undefined
```

*electron*
```
process.versions.electron
"0.36.5"
````

I'll do some tests with this code:

```js
if (typeof process.versions.electron === 'undefined' && typeof module !== 'undefined' && module.require) {
```

**Comment by Rob--W** [comment]
What about ditching duck-typing of the environment and using `typeof Worker !== 'function'` instead?

**Comment by cvlmtg** [comment]
I think that should be ok too

**Comment by yurydelendik** [comment]
Fix our dependence on stub for worker, so `typeof worker === 'undefined'` check shall work now. See #7126 and it shall fix this issue.

**Comment by cvlmtg** [comment]
thanks, we'll try it soon!
