### ISSUE TITLE
Somehow store whether the contents/thumbnail sidebar is open

### ISSUE THREAD

**Issue by sknorr** [mozilla/pdf.js#6935]
Proposal for a small UX enhancement:

I just had the experience that I:

1. opened a PDF file
1. opened the contents sidebar
1. navigated away from the PDF by clicking a link in it
1. navigated back to the PDF by clicking the browser's Back button

Result: the contents sidebar is not open anymore.

I think this issue might be solved relatively easily by adding `#sidebar-content`/`#sidebar-thumbs` to the URL when the sidebar is open. (And then of course changing the UI depending on that.)

But there might be better ways.

**Comment by timvandermeij** [comment]
Might be fixed in a similar way as #5949.

**Comment by thepulkitagarwal** [comment]
#5949 is not working now - you can try doing it in the [demo link](https://mozilla.github.io/pdf.js/web/viewer.html). After reload, the viewer does restore the last scroll position, but not the rotation angle. (This is the same issue as #5927)

That may be because almost all changes made in #5949 have been removed. 
I redid those changes, and it started working.

**Comment by ankitaggarwal011** [comment]
Anyone working on this? If no, I would like to try to fix this issue. Thanks!

**Comment by brendandahl** [comment]
> Anyone working on this?

Not that I know of, feel free to take it on!

**Comment by ankitaggarwal011** [comment]
@brendandahl, since the user moves away from the PDF in this issue, would it be good idea to store the state of sidebar in the local-storage of the browser and initialize ```sidebarOpen``` variable in viewer.js from local-storage if available. What do you think? Please let me know.

**Comment by brendandahl** [comment]
We have code already built to persistently store preferences. As Tim suggested above, this will be very similar to the fix in #6980 and I'd suggest looking at that.

**Comment by ankitaggarwal011** [comment]
Thanks. I will have a look and try to make changes locally and test them.
