### ISSUE TITLE
Gradient at wrong angle

### ISSUE THREAD

**Issue by sknorr** [mozilla/pdf.js#6936]
Take a look at this document: [test.pdf](https://github.com/mozilla/pdf.js/files/109718/test.pdf)

There are (subtle) gradients in the border of the "key" images (i.e. Alt and F1) and those seem to have the wrong angle in PDF.js (tested in Firefox 43/Linux, with the [web viewer](https://mozilla.github.io/pdf.js/web/viewer.html)).

In Evince, where things look correct, the gradient angle is about -45deg, whereas in PDF.js, the angle seems like it is around -70deg.

_Edit_ Tim is correct, the gradient is only over the border.

**Comment by timvandermeij** [comment]
I had to zoom to 400% to finally see it, but you're right. It's best seen in the gray border around the keys.

**Comment by Snuffleupagus** [comment]
Fixed by PR #13361.
