### ISSUE TITLE
How scrollPageIntoView() works?

### ISSUE THREAD

**Issue by antonmoiseev** [mozilla/pdf.js#6947]
I'm trying to use `scrollPageIntoView()` to scroll to a specific point on the page:
```js
pdfViewer.scrollPageIntoView(1, [null, {name: 'XYZ'}, 0, 790]);
```
AFAIU `scrollPageIntoView()` expects coordinates in the original document scale and internally transforms the coordinate applying various transformations such as zoom level, rotation, pixels density (?). However it almost never reveals the point I specify as the target.

**Example:**

1. Open the [demo page](http://mozilla.github.io/pdf.js/web/viewer.html).
2. Set the zoom level to 200%
3. In the browser's console execute following code: `PDFViewerApplication.pdfViewer.scrollPageIntoView(1, [null, {name: 'XYZ'}, 0, 790])`

**Expected:** since the height of the original PDF document is 792 px I would expect the last line of the document to be visible.

**Result:** the view scrolls only several pixels down, the bottom part of the document is not visible.

**Details:**

* OS: OS X 10.11.3
* Screen resolution: 3360x2100 (retina display)
* Browser: Google Chrome 48.0.2564.97 (64-bit)

**Comment by yurydelendik** [comment]
Don't forget that PDF coordinates has flipped Y, i.e. (0,0) is located at the left bottom corner of the page.

**Comment by antonmoiseev** [comment]
I didn't know that, thank you!

**Comment by hoclun-rigsep** [comment]
I still don't understand how to use this method...

**Comment by hoclun-rigsep** [comment]
Finally got it to do something:

```js
pdf_viewer_obj.scrollPageIntoView({pageNumber: 4, destArray: [1, {name:"Fit"}]})
```

**Comment by luqmanrom** [comment]
Get it to work in console using this:


```
PDFViewerApplication.pdfViewer.scrollPageIntoView({ pageNumber: 4, destArray: [null, {name: 'XYZ'}, 0, 790]})
```
