### ISSUE TITLE
Kerning on embedded font is incorrect

### ISSUE THREAD

**Issue by jFransham** [mozilla/pdf.js#6950]
The kerning on the text in the attached file is incorrect. The embedded font is `twcenmt`. I have not found another PDF viewer that displays this issue. The PDF was generated using TCPDF, I am not sure if this is relevant but it might be related to how the fonts are embedded.

[Certificate.pdf](https://github.com/mozilla/pdf.js/files/113856/Certificate.pdf)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #6736.
