### ISSUE TITLE
Need some things:

### ISSUE THREAD

**Issue by Manuelbarrios99** [mozilla/pdf.js#6952]
This app needs improve the interface.

It could work better as a chrome app than a complement, for can choose if open a file with this app or open with Pdf viewer of Google chrome.

It will be great:
when I can choose colors and fonts of letters.

But this is a great start.

**Comment by Rob--W** [comment]
Is "this app" referring to the PDF Viewer Chrome extension (https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm)?

It is currently an extension for technical reasons (apps cannot be displayed in tabs, and there are some other things).

**Comment by timvandermeij** [comment]
It's unclear what is actually requested here. I think Rob's answer is the best possible answer to this issue, so I'm closing this for now.
