### ISSUE TITLE
Issue with rendering pages wrongly  in safari

### ISSUE THREAD

**Issue by ramanathan92** [mozilla/pdf.js#6955]
I am facing issue while pages rendering in safari...total -72 pages but loading 64 and in-between it is loading another left out pages in safari,but working fine in chrome and firefox ..any one faced this same issue b4?

**Comment by timvandermeij** [comment]
Please provide the data as requested in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md when opening a new issue. Without an example PDF file there is not much we can do.

**Comment by ramanathan92** [comment]
[The OAuth 2.pdf](https://github.com/mozilla/pdf.js/files/117937/The.OAuth.2.pdf)
I have attached the pdf file and it is working fine for me in chrome -48.0.2564.97  - os X 10.11.3,firefox - 43.0.4 
and error for safari Version 9.0.3 (11601.4.4).pages rendering wrongly like 1 to 16 and then 64 -76 and 17 - 63


   $scope.renderPDF = function (url, canvasContainer) {

        var options = {scale: 3};

        $scope.renderPage = function (page) {
            var viewport = page.getViewport(options.scale);
            var canvas = document.createElement("canvas");
            canvas.setAttribute("id", "canvas" + $scope.count);
            canvas.setAttribute("class", "canvas-content");
            var ctx = canvas.getContext('2d');
            var renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };

            canvas.height = viewport.height;
            canvas.width = viewport.width;
            canvasContainer.appendChild(canvas);

            page.render(renderContext);
            $scope.count++;
        };

        $scope.renderPages = function (pdfDoc) {
            $scope.pdfTotalPages = pdfDoc.numPages;
            $scope.pdfPageLoaded = true;
            $loading.finish('pdfPageLoaded');
            for (var num = 1; num <= pdfDoc.numPages; num++) {
                pdfDoc.getPage(num).then($scope.renderPage);
            }

        };

        $scope.errorHandling = function () {
        };

         //PDFJS.workerSrc = 'scripts/pdf.js';
        PDFJS.disableWorker = true;
        PDFJS.getDocument(url).then($scope.renderPages, $scope.errorHandling);

    };

    $scope.renderPDF($stateParams.downloadUrl, document.getElementById('pdf-page'));

**Comment by timvandermeij** [comment]
Does this also render incorrectly for you when you use https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) instead of your own custom solution?

**Comment by ramanathan92** [comment]
Safari version - 9.0.3 and yes it is working fine https://mozilla.github.io/pdf.js/web/viewer.html here.only prob is with my custom solution

**Comment by ramanathan92** [comment]
I have found out the reason why pages rendering wrongly,
Its because ofthe  asynchronous call 
 for (var num = 1; num <= pdfDoc.numPages; num++) {
            pdfDoc.getPage(num).then($scope.renderPage);
        }

I did it wrongly, so i have changed my code like this

$scope.renderPDF = function (url, canvasContainer) {

        var options = {scale: 2};

        $scope.renderPage = function (page) {
            var viewport = page.getViewport(options.scale);
            var canvas = document.createElement("canvas");
            canvas.setAttribute("id", "canvas" + $scope.count);
            canvas.setAttribute("class", "tpam-canvas-content");
            var ctx = canvas.getContext('2d');
            var renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };

            canvas.height = viewport.height;
            canvas.width = viewport.width;
            canvasContainer.appendChild(canvas);

            page.render(renderContext);
            $scope.count++;
            if($scope.count <= $scope.pdfDocObj.numPages){
                $scope.pdfDocObj.getPage($scope.count).then($scope.renderPage);
            }
            $loading.finish('pdfPageLoaded');
        };

        $scope.renderPages = function (pdfDoc) {
            $scope.pdfDocObj = pdfDoc;
            $scope.pdfTotalPages = pdfDoc.numPages;
            $scope.pdfPageLoaded = true;
            pdfDoc.getPage($scope.count).then($scope.renderPage);

        };

        //PDFJS.getDocument("scripts/OAUTH2.pdf").then($scope.renderPages, $scope.errorHandling);
        //PDFJS.workerSrc = 'bower_components/pdfjs-dist/build/pdf.worker.js';
        PDFJS.workerSrc = 'scripts/pdf.js';
        PDFJS.getDocument(url).then($scope.renderPages, $scope.errorHandling);

    };

And it is working now after making it a synchronous one.So,you can close this issue.Thanks
