### ISSUE TITLE
Glyph are shifted upward and cropped.

### ISSUE THREAD

**Issue by nbp** [mozilla/pdf.js#6956]
Version: Firefox 43.0.4
pdf: http://www.academie-francaise.fr/sites/academie-francaise.fr/files/rectifications_1990.pdf
Console:
```
14:29:55.599 PDF 5cb3d0c260c4e0535858a854b996b625 [1.4 Acrobat Distiller 5.0 for Macintosh / Microsoft Word: AdobePS 8.7.2 (104)] (PDF.js: 1.1.469)1        viewer.js:6746:1
```

Seen:
![](https://people.mozilla.org/~npierron/pdfjs-issue/pdfjs-firefox-43.png)
Expected (xpdf):
![](https://people.mozilla.org/~npierron/pdfjs-issue/xpdf.png)

The baseline of character on the same line is randomly shifted upward, and the top of the characters are cropped.

**Comment by timvandermeij** [comment]
I cannot reproduce this using Windows 10 x64, Firefox 44 and the latest PDF.js development version. Could you open the PDF file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the problem remains? If so, please also state the operating system you use.

**Comment by richerm** [comment]
Tested fine for me on the viewer using Windows 7 x64, 
Chrome - 48.0.2564.97 m
FireFox - 43.0.4
IE - 11.0.9600.18163

**Comment by yurydelendik** [comment]
Is it Linux only issue?

**Comment by SamyCookie** [comment]
I do not have this bug on Debian Stretch (Fx 44).

**Comment by yurydelendik** [comment]
Is it related to https://bugs.freedesktop.org/show_bug.cgi?id=91829 ?

**Comment by timvandermeij** [comment]
Closing due to no response and no-one here can reproduce this so far. Please provide more information as requested above to reopen.

**Comment by nbp** [comment]
@timvandermeij 

Sorry for the late reply, github is a bit spammy and I missed this conversation.

> Could you open the PDF file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the problem remains?

The problem remains, and I can also see the same issue on the pdf about the tracing jit.

> If so, please also state the operating system you use.

I am running NixOS.

How can I find the fonts which are being loaded by firefox, and the fonts which are being loaded by xpdf?

**Comment by timvandermeij** [comment]
Thank you for your reply! I'm reopening the issue for you as you're still experiencing it.

I tested this again on Arch Linux x64 with the latest PDF.js development version and I cannot reproduce this problem myself.

I'm not sure how to see which fonts are loaded, but if there is an issue with loading the font it will trigger a warning or error in the browser console. If it is empty, most likely everything went well (or something went wrong and it was not logged, which is unlikely). From your screenshot however it looks like the graphics driver is causing issues here.

Could you make sure you have the most recent graphics drivers and, if that does not fix it, post the contents of the Graphics section of `about:support` (just enter that in the URL bar) here?

**Comment by nbp** [comment]
> if there is an issue with loading the font it will trigger a warning or error in the browser console

I do not see any error in the console, only these 2 lines after browsing the kink, and loading the other pdf.
```
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.4.143) viewer.js:7256:1
PDF 5cb3d0c260c4e0535858a854b996b625 [1.4 Acrobat Distiller 5.0 for Macintosh / Microsoft Word: AdobePS 8.7.2 (104)] (PDF.js: 1.4.143) viewer.js:7256:1
```

I will check for driver updates later, in the mean time here is the content of the Graphics section of `about:support`:
```
Adapter Description	Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Mobile
Asynchronous Pan/Zoom	none
Device ID	Mesa DRI Intel(R) Haswell Mobile
Driver Version	3.0 Mesa 10.6.9
GPU Accelerated Windows	0/1 Basic (OMTC)
Supports Hardware H264 Decoding	No; Failed to create H264 decoder
Vendor ID	Intel Open Source Technology Center
WebGL Renderer	Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Mobile
windowLayerManagerRemote	true
AzureCanvasBackend	skia
AzureContentBackend	cairo
AzureFallbackCanvasBackend	none
AzureSkiaAccelerated	0
CairoUseXRender	1
(#0) Error	Failed to allocate a surface due to invalid size Size(1824,0)
(#3391) Error	Failed to allocate a surface due to invalid size Size(1824,0)
(#3392) Error	Failed to allocate a surface due to invalid size Size(1875,0)
(#3393) Error	Failed to allocate a surface due to invalid size Size(1824,0)
(#3394) Error	Failed to allocate a surface due to invalid size Size(1824,0)
(#3395) Error	Failed to allocate a surface due to invalid size Size(1824,0)
```

I asked @nical and he asked me to double check `gfx.canvas.azure.backends` in `about:config`.  
Apparently, when this preference is set to `skia` instead of `cairo` we see the bug that I am reporting.

**Comment by nbp** [comment]
To be more clear, I switched the preference back to `cairo`, instead of `skia`, and the problem went away after restarting firefox.

So I guess we can close this issue, and open one on bugzilla.

**Comment by timvandermeij** [comment]
Correct, in that case there is nothing we can do about this on the PDF.js side. If you could open an issue with the information above at https://bugzilla.mozilla.org that would help to get the problem at the right place. Thank you!
