### ISSUE TITLE
Pages printed 1/4 size

### ISSUE THREAD

**Issue by patricktokeeffe** [mozilla/pdf.js#6958]
Printing with pdf.js (on my Canon PIXMA MG5220) produces documents at 1/4 size.

1. Started by messing with the printer preferences.... still 1/4 size.
2. Next, deleted my driver (Windows7) and reset the device's settings.... still 1/4 size.
3. Tried reprogramming my preferences (duplex, fast) and verified the document wasn't scaled... still 1/4 size.
4. Open PDF using SumatraPDF instead, then print.... works as advertised.

I verified tab-by-tab that the printer preferences used by pdf.js are precisely identical to SumatraPDF. What I didn't find was a "reset pdf.js options" lever.

**Comment by yurydelendik** [comment]
Could you also mention the OS (assumed Windows 8?) and the browser?

**Comment by timvandermeij** [comment]
Additionally, please provide a link to the document you are testing with for us to reproduce the issue.

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.

**Comment by patricktokeeffe** [comment]
fwiw I haven't encountered this since reporting. :)
