### ISSUE TITLE
Password and encryption.

### ISSUE THREAD

**Issue by ATouhou** [mozilla/pdf.js#6959]
Hello.
How do I set up decryption / opening of a password protected pdf?

**Comment by timvandermeij** [comment]
PDF.js already supports opening password-protected PDF files. If you open a PDF file with https://mozilla.github.io/pdf.js/web/viewer.html, a password prompt will be shown. If you need to implement this in your own custom viewer, just take a look at https://github.com/mozilla/pdf.js/blob/master/web/password_prompt.js and where it is used to see how the regular viewer handles this. Closing as answered.

**Comment by ATouhou** [comment]
How can I open a password protect PDF, without prompting the user to input password ?  Like storing password in some variable, html or the like

**Comment by timvandermeij** [comment]
Well, technically you could, but that's rather unsafe as it allows the user to find out the password. In that case you might as well remove the password, but if you still want to do this, then take a look at how it's done in the unit tests for example: https://github.com/mozilla/pdf.js/blob/4c59712606e67bd66bb982dbb465117a3d349afb/test/unit/api_spec.js#L169
