### ISSUE TITLE
Not responding when clicking the print button in android firefox

### ISSUE THREAD

**Issue by vinothr** [mozilla/pdf.js#6964]
In android for the firefox, when click the print button it doestn't respond. The same thing will work on chrome by opening the google drive.

**Comment by timvandermeij** [comment]
Is there any information in the console? Which version of PDF.js do you use? Did you try with https://mozilla.github.io/pdf.js/web/viewer.html? Which version of Android do you use?

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.
