### ISSUE TITLE
Image in PDF doesn't load

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#6967]
Tested in both Chrome and Firefox. Image in page 10 of the attached PDF (labeled page 8 in the document) doesn't load.

The Chrome native viewer and Adobe Reader both load the image properly.

[temp_portfolio658660046914130129 (1).pdf](https://github.com/mozilla/pdf.js/files/124118/temp_portfolio658660046914130129.1.pdf)

**Comment by timvandermeij** [comment]
I can confirm this using Windows 10 x64, Firefox 44.0 and the latest PDF.js development version. It's unfortunate that there are no console messages about this.

**Comment by SamyCookie** [comment]
Same behaviour on Linux Debian stretch (testing) and trunk pdf.js version. No console logs.

**Comment by brendandahl** [comment]
The images are decoded fine. You can observe this by doing the following in paintInlineImageXObject() in canvas.js

```
--- a/src/display/canvas.js
+++ b/src/display/canvas.js
@@ -2067,6 +2067,13 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
         var tmpCtx = tmpCanvas.context;
         putBinaryImageData(tmpCtx, imgData);
         imgToPaint = tmpCanvas.canvas;
+
+        var div = document.createElement('div');
+        var imgData = tmpCtx.canvas.toDataURL();
+        var img = document.createElement('img');
+        img.src = imgData;
+        div.appendChild(img)
+        document.querySelector('#viewerContainer').appendChild(div);
       }
```

Seems to be an issue with how they're drawn. Quick look seems like the coordinates are messed up, but I'll have to look into it more later.

**Comment by Snuffleupagus** [comment]
Skipping the `SMask` case in `CanvasGraphics_setGState` "fixes" this all the missing images in this PDF file, hence this issue is unfortunately yet another regression from PR #4161.

**Comment by yurydelendik** [comment]
Looks like we are not handling AIS=false state properly. Switching mask off for this case helps the case.

**Comment by groovy21** [comment]
Can someone please fix this issue in pdf js. This issue has ruined our experience in an application that is in production. If we dont get a fix we will have to abandon pdf.js and move to a different product. I dont want to do that as I find pdf.js really simple in its UI and dependencies.

**Comment by SamyCookie** [comment]
For reference, some images at page 6-8-10-14 are still missing.

**Comment by tony-pond** [comment]
I am not sure if it can help debug, 
This book doesn't show images, and the front cover is an example of the image not rendering.

https://github.com/tony-pond/books-bug-6967/blob/main/indian_basket_weaving_1903.pdf

**Comment by THausherr** [comment]
The original PDF is an SMask problem, this PDF doesn't have them. I suspect a problem with the JPX decoder. Page 1 has a JPX image, most of the other pages have JBIG2 images which show. Page 11 and 15 have both types, and the JPX image doesn't show. I suggest you create a new issue with your file.
