### ISSUE TITLE
Print button doesn't respond in ipad firefox

### ISSUE THREAD

**Issue by vinothr** [mozilla/pdf.js#6969]
In iPad firefox, when I click print button, loader is visible(Preparing the document for print) after 100% completion, doesn't prompt any print dialog or print app to print the PDF file for the url (https://mozilla.github.io/pdf.js/web/viewer.html)
Firefox version: 1.2
iOS version: 9.2

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and that it looks like a platform/browser bug (rather than a PDF.js one), is it really meaningful to keep this open now?
