### ISSUE TITLE
embedded fonts not rendering in IE 11 in latest PDF.js, don't print properly in previous versions

### ISSUE THREAD

**Issue by davedenis** [mozilla/pdf.js#6974]
I just upgraded (and then downgraded) a site using pdf.js 1.1 because it wasn't printing this PDF with the proper font https://dl.dropboxusercontent.com/u/1057787/pti-embedded-font.pdf although it was displaying it properly (printing issue in all browsers). After upgrading to 1.3 it will no longer even display the font in IE 11, although it works fine in Chrome. I'm assuming the font bad somehow but am unsure how to troubleshoot further.

**Comment by timvandermeij** [comment]
Is there any information in the browser's console? Could you post a screenshot of which parts are missing?

**Comment by davedenis** [comment]
I'll have to get access to IE 11 again. I had to use someone's computer to see that it didn't work.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
