### ISSUE TITLE
Chrome throwing warning while rendering pdf and file is not rendering(page is blank)

### ISSUE THREAD

**Issue by ramanathan92** [mozilla/pdf.js#6976]
[jax_rs-1_1-mrel-spec.pdf](https://github.com/mozilla/pdf.js/files/127549/jax_rs-1_1-mrel-spec.pdf)

I have attached the file and tested in chrome - Version 48.0.2564.97 m -  in windows 10 and it is working,
even i tested with mozilla viewer and working fine in chrome http://mozilla.github.io/pdf.js/web/viewer.html,

but when i tried to test same thing in chrome -Version 48.0.2564.109 (64-bit) OS X - 10.11.3,it is not rendering the page and throwing warning ,page is blank. (I have attached screenshot of it)

<img width="944" alt="screen shot 2016-02-12 at 11 29 21 am" src="https://cloud.githubusercontent.com/assets/7633145/13000078/ecadba3a-d17b-11e5-8220-dc0e8ab8ab7b.png">

<img width="1429" alt="screen shot 2016-02-12 at 11 24 39 am" src="https://cloud.githubusercontent.com/assets/7633145/12999994/40a04924-d17b-11e5-8840-ab0e9ddfbbb0.png">.

My code is 

$scope.renderPDF = function (url, canvasContainer) {

        var options = {scale: 2};

        $scope.renderPage = function (page) {
            var viewport = page.getViewport(options.scale);
            var canvas = document.createElement("canvas");
            canvas.setAttribute("id", "canvas" + $scope.count);
            canvas.setAttribute("class", "tpam-canvas-content");
            var ctx = canvas.getContext('2d');
            var renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };

            canvas.height = viewport.height;
            canvas.width = viewport.width;
            canvasContainer.appendChild(canvas);

            page.render(renderContext);
            $scope.count++;
            if($scope.count <= $scope.pdfDocObj.numPages){
                $scope.pdfDocObj.getPage($scope.count).then($scope.renderPage);
            }
            $loading.finish('pdfPageLoaded');
        };

        $scope.renderPages = function (pdfDoc) {
            $scope.pdfDocObj = pdfDoc;
            $scope.pdfTotalPages = pdfDoc.numPages;
            $scope.pdfPageLoaded = true;
            pdfDoc.getPage($scope.count).then($scope.renderPage);
};
        //PDFJS.getDocument("scripts/OAUTH2.pdf").then($scope.renderPages, $scope.errorHandling);
        //PDFJS.workerSrc = 'bower_components/pdfjs-dist/build/pdf.worker.js';
        PDFJS.workerSrc = 'scripts/pdf.js';
        PDFJS.getDocument(url).then($scope.renderPages, $scope.errorHandling);

    };

**Comment by timvandermeij** [comment]
Could you setup a demo online somewhere? It's difficult to find the issue from a code fragment.

**Comment by timvandermeij** [comment]
No response, closing. I can only imagine that it's not liking that `renderPage` does not actually render one page, but multiple, leading to a large call stack it's complaining about.
