### ISSUE TITLE
pdf.js Key bindings will not go away

### ISSUE THREAD

**Issue by adamczyrek** [mozilla/pdf.js#6989]
Hello, in the project I am testing we use pdf.js inside an Angular web app to view PDFs.

After a pdf is viewed, and the user navigates to another view in the app which does not have pdfjs embedded, all key bindings seem to be still going to pdfjs even though it is not visible. For example, arrow keys and backspace do nothing in rich text (trix) input fields, but they do work in regular input fields.

Can someone please help me understand what we have done wrong here?  How can we correctly disable pdf.js' key binding events when the view containing it is not visible?

Any help is greatly appreciated.

**Comment by timvandermeij** [comment]
This is for the default viewer, but perhaps you are using it too/something similar: see https://github.com/mozilla/pdf.js/blob/059e826e20518a00e4bdcb72a6b7a37bb849a5bb/web/viewer.js#L2016. PDF.js adds the key bindings to `window`, which might explain why you can use them in another view if you do not refresh the page. You can decide to remove the key bindings when you change views, or refresh the page when you change views, or rewrite the key binding code a bit to not attach them to the `window` object. Closing as answered.

**Comment by adamczyrek** [comment]
Thank you very much for your assistance @timvandermeij .
