### ISSUE TITLE
Problem with missing image in IE 10 & IE 11

### ISSUE THREAD

**Issue by Zen33** [mozilla/pdf.js#6991]
I have posted an issue demo: [http://zen33.github.io/chakra/pdf/web/](url), it works well in Chrome and Firefox. But the image is missing in IE 10 and IE 11.

![sc2](https://cloud.githubusercontent.com/assets/3705744/13040482/a30bd70e-d3e7-11e5-91e6-2cd6e3dab9e5.PNG)

My pdf file is: [http://zen33.github.io/chakra/pdf/web/test.pdf](url), it should display as below:

![sc3](https://cloud.githubusercontent.com/assets/3705744/13040541/4117a2fc-d3e8-11e5-8e02-3a68b56c2475.png)

**Comment by TammyHe19900522** [comment]
is there any solution until now?

**Comment by Zen33** [comment]
not yet. @TammyHe19900522

**Comment by brendandahl** [comment]
The links above are broken.

**Comment by timvandermeij** [comment]
Closing as duplicate of #6957.
