### ISSUE TITLE
fieldValue always empty

### ISSUE THREAD

**Issue by ezsper** [mozilla/pdf.js#6995]
When getting form fields with `getAnnotation`, `fieldValue` is always empty for checkboxes and radios. Look at the console screenshot, the correct value should be `Male` for the named radio field of gender.

![fieldvalueempty](https://cloud.githubusercontent.com/assets/798804/13056635/ae8c13f8-d3fd-11e5-847d-89ad7d669e6b.PNG)

**Comment by timvandermeij** [comment]
We are not handling all widget annotation types yet, so this might be a consequence of that.

**Comment by ezsper** [comment]
I know that annotations are not fully supported, but this seems to be an issue of the beta version, 1.3 get the value just fine, I was using it previously.

**Comment by xlc** [comment]
I don't see any issue here. The fieldValue is the `FT` field and you are looking at sub dictionary of `AP` (appearance dictionary) field.

**Comment by ezsper** [comment]
No, it's not. At least not for radios and checkboxes, or at least not in this version of pdf.js. I just know for sure that the field has the specified value `Male`, the the pdf form being parsed I created my self. In the pdf.js 1.3 it came the correct value for the field, but in the 1.4 beta, it came as empty.

**Comment by ezsper** [comment]
This doesn't work for buttons either.

What I'm doing is injecting in `core/annotation.js` close to line 572 something like this:

    var fieldValue = Util.getInheritableProperty(dict, 'V');

    if(fieldType == 'Btn')
      if(fieldFlags & 65536) {
        //buttons
        try{
          fieldValue = dict.get('MK').get('CA');
        } catch(e) {}
      } else {
        //radios and checkboxes
        try{
        fieldValue = Object.keys(dict.get('AP').get('N').map)[values.length-1]||'';
        } catch(e) {}
      }
    }

    data.fieldValue = stringToPDFString(fieldValue || ''); 


Probably not the best approach, but is doing the trick at least.

**Comment by brendandahl** [comment]
Can you post an example pdf?

**Comment by ezsper** [comment]
http://208.109.168.78/pdf/web/viewer.html?file=/pdf/test.pdf
http://208.109.168.78/pdf/test.pdf

**Comment by timvandermeij** [comment]
Closing as fixed by #7898. Pushbuttons are tracked in #7613.

**Comment by drakar4ik** [comment]
now if radio's parent has no value (all radios unchecked), radio's buttonValue ("on" value) is null.
