### ISSUE TITLE
Document browserify build procedure

### ISSUE THREAD

**Issue by bsitruk** [mozilla/pdf.js#7000]
Hello,

I'm using browserify with grunt on my project.
I've followed the [Setup PDF.js in a website guide](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website).
When I trigger a build, the browserify task throws an error:

> Error: Cannot find module 'entry?name=[hash]-worker.js!./pdf.worker.js'

It looks like, the following condition is evaluated as true on runtime (pdf.js line 8309):

```javascript
if (typeof __webpack_require__ !== 'undefined') {
    // Webpack - get/bundle pdf.worker.js as additional file.
    PDFJS.workerSrc = require('entry?name=[hash]-worker.js!./pdf.worker.js');
    useRequireEnsure = true;
}
```

But I'm not using webpack at all.

Any idea ?

Thanks !

**Comment by yurydelendik** [comment]
@bsitruk we don't support browserify atm. I was planning to setup a basic example/docs how to configure build for it. All you need to do is ignore 'entry?name=[hash]-worker.js!./pdf.worker.js' and 'node-ensure' during build, and build pdf.worker.js as a separate file. (Sorry I don't experience with browserify). If you will be able to create a minimal example (e.g. like https://github.com/mozilla/pdf.js/tree/master/examples/webpack), I will be glad to review and commit that into main repo.

**Comment by bsitruk** [comment]
Thank you for the fast answer. I'll check it !

**Comment by bsitruk** [comment]
@yurydelendik What do you mean by "build pdf.worker.js as a separate file" ?
Is there a way to separate pdf.js from pdf.worker.js, so pdf.js doesn't try to load pdf.worker.js ?
I think that's my current issue. I would like to load PDFJS and PDFWorker separately, and then set PDFJS.PDFWorker, without using PDFJS.workerSrc.

Any idea ?

**Comment by yurydelendik** [comment]
@bsitruk pdf.js creates Web Worker (which is pdf.worker.js) and communicates with it via postMessage. (The former controls display, the latter parsing and loading of the PDF.) pdf.js has classes to instantiate the worker, so have to load this file first. And currently you need to set path to the pdf.worker.js at PDF.workerSrc (in the future it will change, e.g. to pass in to the PDF.PDFWorker constructor). And yes, you can instantiate PDF.PDFWorker one time and pass to the getDocument as a parameter. I think I saw somewhere, browserify can provide future path for the bundle you will build from pdf.worker.js -- assign that to PDFJS.workerSrc.

**Comment by bsitruk** [comment]
I've finally found a solution that works for me.

I wrote a node script that generate a pdf.worker.proxy file.
This file simply encapsulate the pdf.worker code into a Blob Object, and export the URL representing the Blob as so: [web-workers-without-a-separate-javascript-file](http://stackoverflow.com/questions/5408406/web-workers-without-a-separate-javascript-file).

I'm not sure it's a very reliable solution, so I did not wrote example.
If you think it would be useful just tell me.

Thanks for your help @yurydelendik.

**Comment by yurydelendik** [comment]
The solution above increases library size and will not work on legacy systems.

**Comment by bsitruk** [comment]
Haven't found any other solution.
If you have any other idea, that would really help me.

**Comment by yurydelendik** [comment]
The right solution (as I mentioned above) is to build separate bundles: one for you app (which will include pdf.js, however browserify needs to ignore some libraries I listed above) and another one for pdf.worker.js. PDFJS.workerSrc shall be used to specify path to the latter.

**Comment by yurydelendik** [comment]
See https://github.com/substack/browserify-handbook#external-bundles

**Comment by bsitruk** [comment]
Nothing here :p

**Comment by bsitruk** [comment]
But yeah, I undestand the solution you are suggesting.
Actually, it seems that it would be a bit complicated to deliver several bundle through our architecture.
I'll check if there is any compatibility issue in the project scope with the current solution. 
Otherwise, we will probably make the necessary changes to use another bundle.

**Comment by mciparelli** [comment]
@bsitruk I'd love to see an example of how you're loading pdf.worker.js as a Blob and getting the URL out of it.

**Comment by yurydelendik** [comment]
@mciparelli the PDF.js is already doing it for cross-origin loading, see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L1248

**Comment by mciparelli** [comment]
Thank you. After I asked I found this as well: https://github.com/shama/workerify . Have anyone sorted out the `__webpack_require__` error you get using browserify already? Seems like if that's sorted out browserify support could no longer be an issue.

**Comment by mciparelli** [comment]
oh I just saw your suggestion about ignoring that file. I'll see if I get this running and make some time soon to submit a PR for _docs on how to build with browserify_

**Comment by yurydelendik** [comment]
Docs updated at https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website#with-browserify
