### ISSUE TITLE
Broken link [missing anchor] in Contributing page Wiki

### ISSUE THREAD

**Issue by ankitaggarwal011** [mozilla/pdf.js#7003]
After Prerequisites, the following text has a broken link [missing anchor] with "Generating reference images":

> Before you make any changes to the code you will probably want jump down to [Generating reference images](https://github.com/mozilla/pdf.js/wiki/Contributing#ref-images) to create the reference snapshot images so you can run the test framework and check for regressions.

This section is available in the same wiki after a few paragraphs, but it doesn't have a valid anchor for the above link to work correctly.

Adding the element id as "ref-images" for relevant section would solve the issue. Since, the wiki cannot be edited with a PR, I assume this has to be resolved by admin. Thanks!

**Comment by timvandermeij** [comment]
I have edited the wiki page to remove those broken links. GitHub wikis do not seem to support anchor links (anymore). Thank you for reporting this!
