### ISSUE TITLE
SVGGraphics clips extra objects when rendering images

### ISSUE THREAD

**Issue by serggusak** [mozilla/pdf.js#7004]
After SVGGraphics_paintInlineImageXObject is called, all following objects are clipped as well. I guess save/restore should be used somewhere in that method. Consider attached PDF. It does not render properly to SVG.
[A702.pdf](https://github.com/mozilla/pdf.js/files/135543/A702.pdf)

Also, restore does not restore clipping, so after adding save/restore, the above still does not work. I re-wrote restore as:

restore: function SVGGraphics_restore() {
      var prevCurrent = this.current;

      this.transformMatrix = this.transformStack.pop();
      this.current = this.extraStack.pop();

      this.tgrp = document.createElementNS(NS, 'svg:g');
      this.tgrp.setAttributeNS(null, 'transform', pm(this.transformMatrix));

      if (this.current.pendingClip) {
          if (!prevCurrent.pendingClip || prevCurrent.clipId !== this.current.clipId) {
              this.cgrp = document.createElementNS(NS, 'svg:g');
              this.cgrp.setAttributeNS(null, 'clip-path',
                                   'url(#' + this.current.clipId + ')');
              this.pgrp.appendChild(this.cgrp);
          }

          this.cgrp.appendChild(this.tgrp);
      }
      else {
        this.pgrp.appendChild(this.tgrp);
      }
    },

Seems like there was some provision for that (current.clipId that was not really used).

**Comment by timvandermeij** [comment]
Fixed by #7732.
