### ISSUE TITLE
Use display layer

### ISSUE THREAD

**Issue by Lordful** [mozilla/pdf.js#7008]
Hello,

I try to find an information about using the display layer like we can use to core layer to browse a PDF. I want to do the same thing but with the display layer because this layer seems to be better for manipulate a PDF.

It seems to me that we can have a object PDF very easily with the display layer, with this object, I could have access to a specific page and see his content easily. Better than by using the core layer.

Is this possible ? Because the documentation about this layer is very poor and I can't find any exemple.

Thanks for the help of my issue.

**Comment by yurydelendik** [comment]
The issue does not meet guidelines described at https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md . Closing as invalid. Also we are constantly working on improving the API documentation and providing examples, so this issue will be/was addressed somewhere else.

**Comment by yurydelendik** [comment]
>  I can't find any exemple.

Please find examples at the [./examples](https://github.com/mozilla/pdf.js/tree/master/examples) folder.

**Comment by Lordful** [comment]
Ok sorry for the bad guidelines and thanks for your help anyway.
