### ISSUE TITLE
Inject pdf.js viewer in existing page

### ISSUE THREAD

**Issue by IrvinDominin** [mozilla/pdf.js#7018]
Hi,

thanks fot this great library!

I'm trying to inject the pdf.js viewer in an existing div in a page, for doing so I'm injecting pdf js script in the head tag like:
```
    var jsInclude = [{ url: 'PdfViewer/compatibility.js', type: 'js' },
    { url: 'PdfViewer/l10n.js', type: 'js' },
    { url: 'PdfViewer/pdf.js', type: 'js' },
    { url: 'PdfViewer/debugger.js', type: 'js' },
    { url: 'PdfViewer/viewer.js', type: 'js' }];
```

and than I'm setting PDFJS and load the file as Uint8Array using:
```
    PDFJS.workerSrc = 'PdfViewer/pdf.worker.js';
    PDFJS.disableWorker = true;
    var pdfData = base64ToUint8Array(PdfView.base64Data);
    PDFViewerApplication.open(pdfData)
```

but I'm facing this error:

>     Uncaught (in promise) TypeError: Cannot read property 'reset' of undefined(…)

I'm going crazy, the same using a simple page, without the script injection is working fine.

Kind regards,
Irvin Dominin

**Comment by yurydelendik** [comment]
Not enough details provided to investigate the issue. Provide public link to your example (see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md)  The PDF.js demo viewer is complex enough and it's may deserve a separate IFRAME in the case your are mixing different libraries.

**Comment by IrvinDominin** [comment]
Hi Yury, I'll post a demo asap; yep it's a pretty complex integration, but sadly I can't follow the iframe path because my framework (for offline site usage) doesn't support it.

**Comment by IrvinDominin** [comment]
Hi @yurydelendik here is a sample link: http://79.99.8.89/sviluppo/testpdf.html

Currently I'm:

1. injecting pdf.js and viewer needed scripts

2. getting the pdf as blob and converting it into an Uint8Array 

3. refreshing the PdfViewer using PDFViewerApplication.open

**Comment by yurydelendik** [comment]
There is 404 on catalogo.pdf

**Comment by IrvinDominin** [comment]
@yurydelendik I'm really sorry...example fixed

**Comment by yurydelendik** [comment]
The generic viewer initialization is called before or after yours (depending on timing):  1) viewer.js cannot find any HTML element it needs to control, 2) or, workerSrc got overridden. Modify viewer.js to control initialization sequence to be in sync with your WaitForPDFJS method. Closing as answered.

**Comment by IrvinDominin** [comment]
@yurydelendik just an add, to handle the issue I managed it:
 - using require.js to inject the script in order and with depencies
 - triggering DOMContentLoaded to start viewer.js correctly
