### ISSUE TITLE
Could you map j/k to scroll the pages like arrow keys' doing?

### ISSUE THREAD

**Issue by petronny** [mozilla/pdf.js#7019]
Hi,
  Thank you for present us this awesome viewer.
  Although there are many keyboard shortcuts to switch to the next/previous page, I have to use up/down to scroll the pages. So I wander that could you map j/k to scroll the pages, and J/K to go to the next/previous page?

**Comment by moore3071** [comment]
@petronny, this sounds pretty Vim-like. If this gets closed as "won't fix", perhaps consider seeing if the Firefox plugin Vimperator has this ability, and if not making an issue there as they're more likely to implement this (or you could bind it yourself in your vimperatorrc).

**Comment by petronny** [comment]
@moore3071 Thank you for your advice.
But I forgot to mention that I'm using chromium now. 
There is a plugin called Vimium like Vimperator for Firefox.
I can use Vimium to scroll the pages without any pdf plugin enabled, but the problem is I can not find a way to set the default zoom level to fill the width of my screen.
Once the document is opened by pdf.js, it will fill the width by default. But its URL goes to "chrome-extension://.....". Vimium doesn't handle this kind of URL.

**Comment by dragon788** [comment]
I'd love to see this as well. j/k do swap pages, but I'd prefer they acted more like the arrow keys and only scrolled a portion of the screen. In vimium u/d perform the more "page up/page down" like scrolling, so allowing that behavior in pdf.js would be awesome as well, even if it's behind a config flag.

**Comment by mackdata** [comment]
I think that many PDF.js users are also on Vimium. So harmonizing the keyboard shortcut behavior between the two would make sense.

**Comment by KVohra95** [comment]
I have found a solution, you have to use vimium++ which is a fork of vimium and use my fork of pdf.js chrome extension as shown here: https://chrome.google.com/webstore/detail/pdf-viewer/lcopgfbpbmionefhhgbamgmejggljpbb. I have also added a few vimium related keybindings such as h and l to go forward back a page and / for searching within the document

**Comment by mackdata** [comment]
Woooow! Impressive work Kvohra95. This is working perfectly!!!! 😄 Thanks for taking the time to upload the Chrome extension and sharing it with everyone.!!

**Comment by KVohra95** [comment]
no worries :)

**Comment by astier** [comment]
Please make j/k behave like the arrow-keys. This would be godsend. Vim-plugins do not work in pdfjs-tabs.

**Comment by astier** [comment]
Or make vim-plugins work with pdf-js.

**Comment by astier** [comment]
I would like to add that to navigate between pages there are already the keys n/p. My proposal would be to use j/k as arrow keys and h/l to navigate pages additionally to n/p.

**Comment by Snuffleupagus** [comment]
Fixing this would, as far as I can tell, require that you'd *simulate* the behaviour of e.g. the regular arrow keys. This is never going to work as well as just letting the browser handle scrolling natively, and at least one previous attempt at doing something like that was rejected[1].

All in all, it seems that WONTFIX might be an appropriate resolution here; please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---
[1] In that case it was related broken scrolling when using the <kbd>Spacebar</kbd> in Firefox, however that's since been fixed in the browser *itself*.
