### ISSUE TITLE
Certain embedded fonts not rendering properly in web viewer in Firefox

### ISSUE THREAD

**Issue by SaranrajR** [mozilla/pdf.js#7020]
When I go to the pdf.js web viewer (pdfjs-1.2.109-dist) and open this PDF using IE 11, it views fine. However, when I go to the same URL and open the same document using either the latest version of Firefox (v44.0.2) the font does not appear to render and there are appear encrypted font for only normal weight font type text. (The PDF loads and displays as expected when using a stand-alone PDF view, such as Adobe Acrobat Reader.)

Here is a screenshot of that console error in Firefox (v44.0.2):

![font_3](https://cloud.githubusercontent.com/assets/17423938/13278111/d1bb7cea-daf3-11e5-8ec2-a53b65ca1430.png)

![rendering_error](https://cloud.githubusercontent.com/assets/17423938/13385826/6a1c91ce-decb-11e5-97bf-3c47e7bd6661.png)

[pdf.zip](https://github.com/mozilla/pdf.js/files/150324/pdf.zip)

**Comment by Snuffleupagus** [comment]
As far as I can tell, the problematic PDF file is not included anywhere in the issue (the `.zip` file only contains a `.js` file).
As outlined https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, please provide the PDF file itself in order for this issue to be valid.

**Comment by SaranrajR** [comment]
Here, i have attached the PDF.
[PDF_File.zip](https://github.com/mozilla/pdf.js/files/152156/PDF_File.zip)

**Comment by Snuffleupagus** [comment]
Reduced test-case, *without* password, available here: [issue7020_reduced.pdf](https://github.com/mozilla/pdf.js/files/152749/issue7020_reduced.pdf).
From the console:
```
PDF b81d91f1677947719abd15ea0fd835cf [1.7 - / -] (PDF.js: 1.4.107 [WebGL]) viewer.js:7135:7
downloadable font: name: Faile to write name entry (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <unknown>
downloadable font: name: failed to serialize table (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <unknown>
downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <unknown>
downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: (invalid URI) <unknown>
Warning: Failed to load font ""g_d0_f1"": SyntaxError: An invalid or illegal string was specified pdf.js:368:5
```
