### ISSUE TITLE
Images displaying as blackboxes

### ISSUE THREAD

**Issue by moore3071** [mozilla/pdf.js#7024]
Using Firefox 44.0.2 on Arch Linux, Figure 1 and figure 2 from the pdf [here](http://web.mit.edu/3.064/www/slides/Ko_spider_silk.pdf) are displayed as black boxes, whereas Chromium's default pdf viewer renders these images fine.

**Comment by timvandermeij** [comment]
This happens for me too on Arch Linux. Thank you for reporting this.

**Comment by timvandermeij** [comment]
This is fixed for me on Arch Linux (while I did experience this some time ago). This also applies to the referenced issue above: also fixed for me on Arch Linux.

@moore3071 Do you still experience this issue with the latest version of PDF.js, Firefox and Arch Linux?

**Comment by yurydelendik** [comment]
Fixed in FF46, see https://bugzilla.mozilla.org/show_bug.cgi?id=976322

**Comment by moore3071** [comment]
This is fixed for me also when running Firefox 46.0. Thanks guys!
