### ISSUE TITLE
Add files from FileAttachment annotations to the attachments tab in the sidebar

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7025]
#6988 implemented support for FileAttachment annotations. Some PDF readers like Adobe Reader or Foxit Reader show the attachements from FileAttachment annotations in the attachments tab in the sidebar too, which we might also want to do if possible.

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/pull/6988#issuecomment-188424375, I've got a patch series that implements this[1], but the question is if we want to implement this functionality!?

---
[1] See https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:PDFSidebar

**Comment by timvandermeij** [comment]
I'm a bit on the fence about this. I'm not sure if there is much use if not all attachments can be shown in the attachment viewer at document load. Sure, if a page is loaded we can display the attachment in the attachment sidebar, but we will not get the attachments from pages that have not been loaded yet.
