### ISSUE TITLE
Hidden Text Layer Not in correct y-position as text on pdf page

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7027]
Hi, im depending on the text layer coordinates to get the selected text and create an underline or strike-through

however, the y position of the hidden text layer can sometimes be positioned a little lower or above the original text in the pdf page

take for example the monkey pdf in the viewer. the hidden text layer's y position is positioned a little lower than the text in the pdf page. on some pdf pages, its y-position starts above the printed text.

is this a fixed behavior or will there be changes for a possible fix in the future? i could not find any existing issues in the repository that talked about this so i thought i'd open this up.

**Comment by Snuffleupagus** [comment]
If the difference is small, this may be expected, see e.g. the explanation in https://github.com/mozilla/pdf.js/issues/6833#issuecomment-168846561.
(There's been previous issues about this, mostly with custom deployments, e.g. #5558 and #6614.)

If there are specific PDF files where the textLayer is way off, please open separate issues for those, including the PDF file (or a link to it). Please also see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

Closing as answered.
