### ISSUE TITLE
Copying a text line from PDFJS into word breaks separated lines

### ISSUE THREAD

**Issue by hhstkh** [mozilla/pdf.js#7028]
When I copy a text line from PDFJS into word, this content breaks into separated lines
Example:
THANK 
YOU
 VERY 
MUCH 
FOR 
THIS 
REFERRAL

File to test: https://drive.google.com/open?id=0BzoKdQwBinAncW1Od0VXOF80N28
PDFJS version: 1.3.91
Google Chrome version 48.0.2564.116 m

Please advise.

**Comment by hfhchan** [comment]
I'm also seeing this issue with nearly every single export file from Word 2013.

I'm using Firefox 49.0.2 with built-in pdf.js.

**Comment by timvandermeij** [comment]
Closing since the file is no longer available. Moreover, we have many other issues tracking the same problem (#9984 for example).
