### ISSUE TITLE
Display Custom Error Authorization Message

### ISSUE THREAD

**Issue by samit2015** [mozilla/pdf.js#7032]
My requirement is to display that Custom Error message on pdf viewer that user is not authorized to see doc. But In pdf.js its going inside function UnexpectedResponseExceptionClosure and in pdf.worker.js at onError: function onError(status) ELSE part Status is coming as 500 and exception as UnexpectedResponseException: Unexpected server response (500) while retrieving PDF ....

I want to know where uts getting converted and how can I show exact error message which I am getting after hitting repositories?

Thanks in advance

**Comment by timvandermeij** [comment]
I think you mean this: https://github.com/mozilla/pdf.js/blob/58329f7f92f9c9f5dd8a7e42caf6ba3afdd6911d/src/core/worker.js#L319

It's not really clear from the description what you want to do though, but that is the location where this exception is raised. I think you can replace that with your custom message.

Closing as answered.
