### ISSUE TITLE
page re-numbering

### ISSUE THREAD

**Issue by lovasoa** [mozilla/pdf.js#7037]
Often, articles and digitized books have their own page numbering that
doesn't match the one of the PDF. That is, the first page of the book is
not at the first page of the PDF, but after. [Exemple PDF](http://www.orie.cornell.edu/orie/academics/master/resources/upload/HandbookF15-July2015-3.pdf)

The PDF file format allows to specify custom page numbers. Unfortunately few PDF
generating softwares use this feature. But it is supported in pdf.js (thanks to #6945 ), and that will allow us to fix this problem without writing much new code.

I wrote [this commit](https://github.com/lovasoa/pdf.js/commit/40f3ddc3306d6cc2bcae792b51a792bebe4c621d), adding a feature that allows easier navigation in such PDFs.

The user should go to the first page of the book inside the PDF, and
click "Mark this page as page №1" (in the secondary menu bar). pdf.js
will then renumber all the pages in the pdf, so that pages before the
current page have a page label indicationg "intro-n" and pages starting
from the current one will have numbers corresponding to their real
position inside the book.

I do not submit it as a pull request, because this commit is based on #6945 that hasn't been merged yet. But I would like to have your opinion about this feature is general and my implementation in particular.

If you don't want to pull and compile my repo, I set up an [online demo](http://ophir.alwaysdata.net/pdf.js/web/viewer.html).

![capture du 2016-02-27 01-18-03](https://cloud.githubusercontent.com/assets/552629/13367046/64e1b824-dcf0-11e5-87be-52b1c15cc522.png)

**Comment by timvandermeij** [comment]
Could you elaborate a bit on why this is useful (i.e., what the use-cases are for this feature)? Do other PDF viewer support such functionality?

**Comment by Snuffleupagus** [comment]
I understand that this feature might be useful in a custom implementation of PDF.js, but too me this seems like too much of a special case to warrant adding to the default viewer.

**Comment by lovasoa** [comment]
It's useful to people who read books or article of research in pdf.js. They almost never contain page labels (at least I have never seen one who does), and the content often refers to page number in the book. For instance, many books or article contains sentences like "see reference at page n". But entering n as a page number in pdf.js doesn't lead you to the nth page of the book.

**Comment by lovasoa** [comment]
Google books references [hundreds of such books](https://www.google.com/search?tbm=bks&q=see+at+page#q=%22see+page%22&tbm=bks&start=80), the reading of which would benefit from this patch.

**Comment by Snuffleupagus** [comment]
As previously stated, this feature seem like way too much of a special case to warrant the added code/buttons that would be necessary to make this work properly; let's close this as WONTFIX.
