### ISSUE TITLE
Help Me Please : Problems with print pdf file in pdf js iframe on ie 11.

### ISSUE THREAD

**Issue by pool13433** [mozilla/pdf.js#7042]
Print PDF in an iframe in IE 11 has undesirable with a PDF attachment.
After viewing the results, print on paper and then have the unwanted messages attached.

**Comment by Rob--W** [comment]
Please provide all necessary details to reproduce the bug. See https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md

**Comment by timvandermeij** [comment]
Closing as incomplete until the information as requested above is provided.
