### ISSUE TITLE
Text copied into word generates more characters.

### ISSUE THREAD

**Issue by hhstkh** [mozilla/pdf.js#7045]
When I copy a selected text from PDFJS into word, this content is added extra characters.
Example, copy "SANCHEZ , VIVANA" into word with option Keep Text Only. It displays as "SAANNCCHHEEZZ,,VVIIVVIIAANNAA"

File to test: https://drive.google.com/open?id=0BzoKdQwBinAneXpZbEE0QnU3SFU
PDFJS version: 1.3.91
Google Chrome version 48.0.2564.116 m

Please advise.

**Comment by brendandahl** [comment]
I'm kind of surprised other viewers handle this well.
The PDF draws each character twice to give a shadow affect. Simplified example of the drawing operations:

```
Tr 2 (set text rendering mode to fill then stroke text)
Tj S (draw an 'S')
TD <move back to where 'S' was>
Tr 0 (set text rendering mode to fill text)
Tj S (draw an 'S')
```

**Comment by Snuffleupagus** [comment]
> File to test: https://drive.google.com/open?id=0BzoKdQwBinAneXpZbEE0QnU3SFU

Given that the file is no longer available, let's close this as a (forward) duplicate of issue #12521. /cc @timvandermeij
