### ISSUE TITLE
Add option to display 1 page regardless of zoom

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7051]
I am not sure if this feature is available but considering the number of keywords i used to search for it, i could not find any related article if there exists such a feature.

It would be nice for pdf.js to have an option for 1 page display regardless if the user scrolls up or down,  zooms in or out, only 1 page gets displayed.

this can greatly help in memory consumption because i thought about resetting all the pages if they are not visible, then have the page recreate itself if it is visible.

**Comment by Snuffleupagus** [comment]
> this can greatly help in memory consumption because i thought about resetting all the pages if they are not visible, then have the page recreate itself if it is visible.

Note that it's possible to reduce the number of pages that are cached, by changing `DEFAULT_CACHE_SIZE` in the source code, see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L352.

**Comment by chitgoks** [comment]
@Snuffleupagus  thank you for this. this can help. but if user zooms out too the pages visible will not be reset.

this is a feature request though so i hope someoen can tag this as 2-features? the 1 page display will ensure that all pages are not cached except the one visible even if the scale is zoomed out too much

**Comment by Snuffleupagus** [comment]
This can now be achieved, in a custom viewer implementation, simply by making use `PDFSinglePageViewer` instead of the "default" `PDFViewer`.

**Comment by chitgoks** [comment]
this is great news!

i hope this cN be an optiom in default viewer since many users use the default aS is.
