### ISSUE TITLE
PDFJS Low Quality When Print in IE 11

### ISSUE THREAD

**Issue by pool13433** [mozilla/pdf.js#7055]
![pdfjs_blur](https://cloud.githubusercontent.com/assets/8747366/13489883/083c2648-e15c-11e5-8c88-e7157313bd78.png)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you provide all the necessary information, see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.
