### ISSUE TITLE
PDF file does not load is too large. (> 100M)

### ISSUE THREAD

**Issue by Dustfate** [mozilla/pdf.js#7056]
PDF file does not load is too large(> 100M).You can limit what is displayed?For example the first one to display the contents on page 10.

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you provide all the necessary information, see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.
