### ISSUE TITLE
Loading pdf from uint8array is much slower then from url on IE11

### ISSUE THREAD

**Issue by pdorrestijn** [mozilla/pdf.js#7059]
Hi,

First of all: great work on PDF.js!
I do encounter an issue using version 1.3.91.
I'm trying to display the supplied tracemonkey pdf using the supplied viewer.html (viewer.js DEFAULT_URL='') PDFViewerApplication.open(rawPDFinUint8Array).
This works all fine in chrome and firefox.
However when using IE11 (and IE10), this variant takes awefully long (about 10 minutes), one core of the cpu is very busy and memory is high.
When I load the same pdf from url (DEFAULT_URL in viewer.js) with IE, the speed is ok (few seconds).
When I use open file to load the same pdf, the speed is ok (few seconds).
When I try to use PDFJS.getDocument(rawPDFinUint8array), I get nothing (Chrome, Firefox, IE).
When I try to use PDFJS.getDocument({data:rawPDFinUint8array}), I get nothing (Chrome, Firefox, IE).
What is different with PDFViewerApplication.open and IE that it takes 10 minutes?
Should I load the raw pdf data differently in PDF.js?

**Comment by yurydelendik** [comment]
It all depends on size of the document, how PDF document(s) is created, in which mode IE in (it can be in IE9 mode). There is no special code path for IE11 in terms of PDF loaded as Uint8Array. There might be issues with how Uint8Array, e.g. object created in different window/frame might be slower than created in same window. Please provide more information (see https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md) such as link to your solution including PDF documents and steps to reproduce the problem on different computer.

**Comment by pdorrestijn** [comment]
Thanx for the reply, unfortunately my stuff is not online thus I can not share.
I can provide information on how to reproduce this:
IE is run in standard mode (11).
The document used is compressed.tracemonkey-pldi-09.pdf as supplied in the distribution 1.3.91.
I have converted this pdf using http://www.webutils.pl/index.php?idx=base64 and stored the content in a javascript variable called base64pdf which will be converted (see below) and supplied to PDFViewerApplication.open(base64pdf) once the viewer.html (also supplied in the distribution) is loaded (meaning PDFViewerApplication is defined).

I decode the base64 encoded pdf using:
`function convert(base64string) {
  var raw = atob(base64string);
  var data = new Uint8Array(raw.length);
  for(var i=0; i<raw.length;i++) { data[i] = raw.charCodeAt(i); }
  return data;
`
The pages are hosted in a static resource folder of a tomcat 8 instance. 
This all works as a charm when using chrome and/or firefox.
When using IE11 (mode=standard), the conversion function does not take long but for PDFViewerApplication.open to display this particular PDF takes approx 3 minutes (one CPU core to the max and memory increases linear from 50MB to 144MB) before the pdf is shown.
When I do the same actions in Chrome, the pdf is displayed within 1 second without a notable CPU usage nor increase of memory...

**Comment by yurydelendik** [comment]
It will save more time for contributors if they could just click a link to see the issue, hence speed up the issue resolution.

Also you can try to diagnose it by opening IE profiler https://msdn.microsoft.com/en-us/library/dn255005(v=vs.85).aspx and check which function takes more time and compare that with Chrome/Firefox profile results. Try the same with PDFJS.disableWorker to true as well.

**Comment by pdorrestijn** [comment]
Ok, I've ran one diagnostic while the worker was disabled (confirmed by warning that a fake worker was setup).
pdfViewOpen used a total of 2 msec (exclusive), and getDocument a total of 926 msec (exclusive).
So this looks good.
Most interesting things that I've seen in de report when sorted on start time:
after some style calculations and paint actions in the first 15 seconds,
some timer (UI-thread) goes off after 15 seconds and nothing happens for about 30 seconds
then again some style calculations and paint actions within 50msec ending in paint(1920x960)
No actions for 30 seconds until a style calculation (<1msec).
Then the garbage collector kicks in (<1 ms).
Another 280 seconds of nothing
Then an insert before starts superceeded with a ton of fast paint/timer/dom actions after which the pdf is shown.
I only have my own page opened (previously referred to as 'oarent' window) and the child window.
There is a setTimeout in my 'parent' window to wait for PDFViewerApplication to become defined.
I will try to put the stuff in jsfiddle, see if I can share my solution and link it with the online demo.

**Comment by pdorrestijn** [comment]
Interesting fact afterwards, once the pdf is shown and some browser idle time (and I guess another garbage collector run) the memory dropped from 150MB back to 50MB.

**Comment by yurydelendik** [comment]
As a recommendation to decrease memory usage: it's preferable to not use base64 encoding decoding since you are increasing memory use several times i.e. one for base64 encoding, one for atob result and one for original data and one will be encoded and send to the worker, so in single moment of time you will have 4.75x  - 6.50x memory used for the same PDF data (strings often take 2x size since they are stored as utf16). At very least don't perform atob conversion (see https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_rewrite_the_DOMs_atob()_and_btoa()_using_JavaScript%27s_TypedArrays_and_UTF-8) and "zero" original base64 store as soon as possible.

**Comment by pdorrestijn** [comment]
Not decoding is good advice.
I've tried doing without, but there's not much difference.
The diagnostic tooling of IE makes me suspect that the parent and child windows get mingled in IE (where a proper browser like firefox doesn't). Also when I run the memory diagnostics, I do not see where those 100's of MB's are allocated.
Let me share my javascript here, maybe someone understands why IE gets meshed up.
This script can be executed either by:
new PDFViewer(<relative path to viewer.html from the distribution>).show(base64encodedPdf); or
new PDFViewer(<relative path to viewer.html from the distribution>).load(rawPdf);

`PDFViewer = function(viewerUrl) {
	'use strict';
	var _path = typeof viewerUrl !== 'undefined' ? viewerUrl : 'web/viewer.html';
	var _window = window;
	var _view = null;
	var _data;
	var _expires;
	/*
	 * Converteer een base64 encoded string naar een unsigned array of shorts.
	 * Deze functie kan nog worden geoptimaliseerd door atob niet te gebruiken en direct de uint te berekenen van de hex codering
	 */
	function _convert(base64string) {
	  var raw = atob(base64string);
	  var data = new Uint8Array(raw.length);
	  for (var i=0; i<raw.length; i++) {
		data[i] = raw.charCodeAt(i);
	  }
	  return data;
	}
	/*
	 * Laad de pdf in de viewer
	 */
	function _laad() {
		if (typeof _view === 'undefined') {
			throw "No PDFViewer";
		} else if (Date.now()>_expires) {
			throw "Could not load PDFViewer";
		} else if (typeof _view.PDFViewerApplication === 'undefined') {
			setTimeout( function() { _laad() },100);
		} else {
			_view.PDFViewerApplication.open(_data,0);
		}
	}
	
	function _close() {
		_data = null;
		_view = null;
	}
	/*
	 * Open de viewer
	 */ 
	this.open = function() {
		if (typeof _view === 'undefined' || _view == null) {
			_view = _window.open(_path);
			_view.window.onbeforeunload = function () {
				_close();
			}
		} else {
			_view.window.focus();
		}
	}
	/**
	 * Sluit de viewer
	 */ 
	this.close = function() {
		if (typeof _view !== 'undefined' && _view != null) {
			_view.window.close();
		}
	}
	/*
	 * Toon de base64 encoded PDF in de viewer
	 */
	this.show = function(base64encodedPDF) {
		this.open();
		_expires = Date.now() + 10000;
		_data = _convert(base64encodedPDF);
		_laad();
	}
	/*
	 * Toon de base64 encoded PDF in de viewer
	 */
	this.load = function(raw) {
		this.open();
		_expires = Date.now() + 10000;
		_data = raw;
		_laad();
	}
}
`

**Comment by pdorrestijn** [comment]
thanx, issue was detected with IE10 & 11 being slow. Edge could not compute.

**Comment by pdorrestijn** [comment]
Also tried the easy way but the onload is not working

> 			_view = _window.open(_path);
			_view.window._data = _data;
			
			_view.window.onload = function () {
				this.PDFViewerApplication.open(this._data, 0);
				//PDFViewerApplication.open(_data,0);
			}
			_view.window.onbeforeunload = function () {
				_close();
			}

**Comment by yurydelendik** [comment]
try to decode base64 string into uint8array in the web/viewer.js file

**Comment by pdorrestijn** [comment]
Hi Yury,
I've tried PDFViewerApplication.open from viewer.html/js in a single window and there everything works like a charm in IE.
Thanx for that tip, it makes me conclude that the actual cause on this issue is IE and the way IE handles the window object and the security around it (at one point I even had a BOD!).
Now that I know the problem, I will try some different approaches to see what IE can and can't do.
PDF.js remains a gem, I will close this issue.

**Comment by pdorrestijn** [comment]
Problem solved by letting the parent window put a key in de sessionStorage of the child window.
The child window has a timer to check for new keys in it's sessionStorage.
When found, it will fetch the pdf data from the parent using the provided key.
