### ISSUE TITLE
JS error when loading fonts in IE10/11

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#7064]
Issue: Some documents are not properly loading in IE 10/11. Test file: https://isotropic.org/papers/chicken.pdf. I could not reproduce on the generic viewer, but could when using a separate app built on PDF.js.

Seems to be caused by:
https://github.com/mozilla/pdf.js/blob/8402c791711a1dd0a66021cc02e97e455194d8b1/src/core/fonts.js#L234

the "for (var charCode in this._map)" is not checking for hasOwnProperty when iterating. Debugging in IE10 / IE11 shows an attempt to check this.map["find"].charCodeAt(0).

**Comment by tonyjin** [comment]
Doesn't look like the ToUnicodeMap code changed recently - maybe the contents or type of the map it's iterating over changed and the "for...in" no longer performs expected behavior.

**Comment by tonyjin** [comment]
Found the issue - we are polyfilling Array.prototype.find. I'll submit a pull request to add a hasOwnProperty check which seems like a good idea regardless.

**Comment by yurydelendik** [comment]
`find` shall not be enumerable on the Array objects. Are you using some library that make this property enumerable?

(Adding hasOwnProperty check will not be acceptable due to amount of item ToUnicodeMap has to deal with)

**Comment by Snuffleupagus** [comment]
> I'll submit a pull request to add a hasOwnProperty check which seems like a good idea regardless.

That was rejected previously, for performance reasons, please see https://github.com/mozilla/pdf.js/pull/5411#issuecomment-59098223.

**Comment by yurydelendik** [comment]
>  we are polyfilling Array.prototype.find

When you are polyfilling, use `Object.defineProperty(Array.prototype, "find", { value: ..., enumeratable: false, configurable: true });` instead of `Array.prototype.find = ...`

**Comment by tonyjin** [comment]
Ah, thanks for the tip. I'll close this. We were using this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill
