### ISSUE TITLE
[Wiki] Update "Optimize a PDF" hyperlink

### ISSUE THREAD

**Issue by websirnik** [mozilla/pdf.js#7071]
"Optimize a PDF" hyperlink here https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster needs to be updated to https://helpx.adobe.com/acrobat/using/optimizing-pdfs-acrobat-pro.html

**Comment by timvandermeij** [comment]
Done. Thank you for reporting this!
