### ISSUE TITLE
How to render text layer

### ISSUE THREAD

**Issue by mzabriskie** [mozilla/pdf.js#7072]
I am trying to render the text content of a PDF as is done [here](http://mozilla.github.io/pdf.js/web/viewer.html). I wasn't able to find an exposed API that would support this, event though #858 makes reference to `page.renderTextLayer`. Digging through the source I was able to find `page.getTextContent` and was able to get `PDFJS.renderTextLayer` by including `src/display/text_layer.js` in my source. Even then the text layer doesn't render as expected.

Two questions:

1. Why does the PDF text layer render incorrectly ([example](http://mzabriskie.github.io/pdf-textlayer-example/) | [source](https://github.com/mzabriskie/pdf-textlayer-example/blob/master/index.js))?
2. Why isn't `renderTextLayer` exposed on either the `page` or `PDFJS` objects?

**Comment by brendandahl** [comment]
1) You need some more css. Checkout our main viewer for examples.
But overall add a .textLayer class to your wrapping div and make it relative or absolute and

```(css)
.textLayer > div { 
   position: absolute;
}
```

2) Not positive what the above is asking, but it is exposed on PDFJS just not documented. We should probably move it to api.js and add some docs there.

**Comment by Snuffleupagus** [comment]
I'd suggest looking into using the viewer components, see https://github.com/mozilla/pdf.js/tree/master/examples/components, which are intended to simplify building a custom viewer.

**Comment by mzabriskie** [comment]
@brendandahl thanks for your response. I could have sworn that I already tried that, but sure enough it did the trick :facepalm:

Aso for `PDFJS.renderTextLayer` it doesn't exist unless I include `src/display/text_layer.js` in my project. I am getting `PDFJS` from `pdfjs-dist/build/pdf.js` using the [pdfjs-dist](http://npm.im/pdfjs-dist) npm module.

**Comment by yurydelendik** [comment]
> Aso for PDFJS.renderTextLayer it doesn't exist unless I include src/display/text_layer.js in my project. I am getting PDFJS from pdfjs-dist/build/pdf.js using the pdfjs-dist npm module.

@mzabriskie it shall be included in pdfjs-dist's pdf.js, see https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L5373

**Comment by yurydelendik** [comment]
Also find all needed CSS at https://github.com/mozilla/pdfjs-dist/blob/master/web/pdf_viewer.css

**Comment by mzabriskie** [comment]
You're correct `PDFJS.renderTextLayer` exists in the current version. I was apparently using an older version. Updating to latest version solves my problem.

**Comment by nurtureJamesTan** [comment]
why is this function not in page element?

**Comment by pangguoming** [comment]
Hello，guys，i know how to do that.
1、incllude CSS file in your page
<link rel="stylesheet" href="../../node_modules/pdfjs-dist/web/pdf_viewer.css">
2、create a text layer div with the following code 
<div id="textlayer"></div>
3、replace js code:  page.render(renderContext);  to the following code
page.render(renderContext).then(() => {
          return page.getTextContent();
        }).then((textContent) => {
          // 创建文本图层div
          const textLayerDiv = document.getElementById('textlayer');
          textLayerDiv.setAttribute('class', 'textLayer');
          // 创建新的TextLayerBuilder实例
          var textLayer =  pdfjsLib.renderTextLayer({
            textContent: textContent,
            container: textLayerDiv,
            viewport: viewport
          });
          textLayer._render();
          //textLayer.setTextContent(textContent);
          //textLayer.render();
        });

**Comment by dxc-jbeck** [comment]
https://usefulangle.com/post/90/javascript-pdfjs-enable-text-layer

**Comment by technicaltitch** [comment]
Any tips on how to run `renderTextLayer` in node?

```javascript
return page.getTextContent().then(textContent => {
  const div = document.createElement("div");
  pdfjsLib.renderTextLayer({
    textContent,
    container: div,
    viewport,
    textDivs: [],
  });
});
```

Raises `TypeError: canvas.getContext is not a function`

My plan was to extract SVG and media, render server-side then deliver, but mobile browsers still struggle, eg, to zoom. So I'm now trying to super-impose a text layer over an image. I want to extract the text layer exactly as it is rendered as spans in a div, I'm not worried about updating for zoom level, etc.

My full script is below, attempt at text extraction on line 242:

[scrape2.js.zip](https://github.com/mozilla/pdf.js/files/4553327/scrape2.js.zip)
