### ISSUE TITLE
Build Pdf.js Faild

### ISSUE THREAD

**Issue by wadehehe** [mozilla/pdf.js#7073]
When I execute "gulp generic"  ,there is no build folder created.
Only Show below info
![generic](https://cloud.githubusercontent.com/assets/6838063/13625319/76915b38-e5f1-11e5-8328-677037a670f7.png)

I did not change anything only by cloning the code and install npm module then execute "gulp generic".

Can anyone help me ?

**Comment by timvandermeij** [comment]
Works fine for me. Do you have Git configured properly? Git needs to be installed and in your PATH variable. The fact that it seems to stop at the first step "Getting extension build number" makes it really possible that Git cannot be found, which is a prerequisite for PDF.js.

**Comment by wadehehe** [comment]
Thanks man, it works fine now.
