### ISSUE TITLE
How to use in angularsJS web app ?

### ISSUE THREAD

**Issue by vincentcialdella** [mozilla/pdf.js#7075]
Hi,

I've seen libraries wrapping pdf.js for angularjs:

- [ng-pdfviewer](https://github.com/akrennmair/ng-pdfviewer)

- [angularjs-pdf](https://github.com/sayanee/angularjs-pdf)

- [angular-pdf-viewer](https://github.com/winkerVSbecks/angular-pdf-viewer)

but none exposes "print" and " download" functionalities.

I would like to have many of the functionalities of the viewer here : [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

I thought I could use pdf.js directly without any wrapper but I have seen in the code that print was : `window.print();` but what I would like to print is not all the content of the window, just the content of an element. 

Any suggestions ?

Thanks

**Comment by yurydelendik** [comment]
> Any suggestions ?

Browsers can print only what's visible (when corresponding CSS rules applied) -- there is no web API to create a print job.  Your main page shall do what PDF.js generic viewer does (notice that it will not work as iframe):
  - hide all main content using CSS @media print directive
  - unhide/show all page divs/canvas
  - handle mozPrintCallback or use its polyfill to print canvases

Closing as answered.
