### ISSUE TITLE
Open local files with pdf.js viewer and electron.

### ISSUE THREAD

**Issue by Aelkeris** [mozilla/pdf.js#7076]
So the issue i have here, is that i am using electron framework to develop desktop apps in html and js. And i need to show pdf documents, and for that i am using the pdf.js library. Now, what i want to do, is open a new window in electron, which is fairly simple, i do this by saying : 
window.open("../../../pdf.js/web/viewer.html", "View");

However, what i want is to give user the freedom to select a pdf file on his machine. Now, i have tried passing the pdf file using the "?file=", but it is still not working. When my user selects a file using a file picker, the file picker returns me the entire file path, so, i have almost everything to make it work, but im missing that final piece. Is even possible to open files like that with viewer.html ?

**Comment by bhanuc** [comment]
Don't use viewer.html as a base in electron, it's bulky(not an issue actually) and depends on require.js which is not supported in electron and causes conflicts when you try to import anything else. 
 Go for a minimal reader if possible where you can use PDFJS.getDocument(url) to load the document. 
Doing something similar is also possible with viewer.html . 
I am writing a Book reader using electron and pdf.js and I started with viewer.html but decided against it.

**Comment by yurydelendik** [comment]
>  Is even possible to open files like that with viewer.html ? 

An electron application is a node.js application. So you can use e.g. `process.args[2]` in the main script to get to command line parameter and concat with "web/viewer.html?file=" and open it as your main window. WFM.

Closing the issue as answered. See also related issue #7135.
