### ISSUE TITLE
Text low resolution when printing

### ISSUE THREAD

**Issue by TupaNegreiros** [mozilla/pdf.js#7077]
I am using PDF Viewer (Chrome extension), so I am no sure if this is a issue of pdf.js or the chrome extension.

I am trying to print this PDF: http://biosystem.link/Atendimento/Teste (BTW it has a javascript to print after loading)
If I use built in Chrome viewer, the resolution is fine, but it doesn't support javascript.
If I enable PDF Viewer, the text resolution becomes low when printing. You don't need to print, even zooming in print preview is possible to see the resolution difference from zooming in the viewer.

This PDF is generated using PdfSharp. I've tried to embed fonts or not in the file, the results are the same. Maybe there is some adjustment to do when PdfSharp generates the PDF, but I don't have a clue.

I used Chrome 48 x64, PDF Viewer 1.4.55, Windows 10.

Thanks a lot.

**Comment by timvandermeij** [comment]
Closing as fixed. Remaining quality issues are tracked in #6241.
