### ISSUE TITLE
Is there an API from pdf.js that can be used to edit pdf ? 

### ISSUE THREAD

**Issue by Aelkeris** [mozilla/pdf.js#7079]
I am using pdf.js to view pdf files, however, i will have to edit them. Is there any way, they can be edited by using the API from pdf.js? 

For example something similar to  :  
http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/js_api_reference.pdf

I apologise if the question is a bit inconclusive.

**Comment by timvandermeij** [comment]
We do not provide such functionality. PDF.js is only a renderer and viewer. Editing PDFs is out of scope for this project.
