### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by raineroviir** [mozilla/pdf.js#7080]
I'm getting this error when trying to load my PDF.  
`Error: ReferenceError: XMLHttpRequest is not defined`

**Comment by yurydelendik** [comment]
Please provide more information as requested at https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md . As is the issue will be closed as incomplete.

**Comment by raineroviir** [comment]
I solved the problem looking at the node.js example: the `getDocument()` API needs a Uint8Array stream not the local file path.
