### ISSUE TITLE
hindi fonts loading issue with some pdf

### ISSUE THREAD

**Issue by gooddayjitendra** [mozilla/pdf.js#7081]
hi,
    
     i am trying to load pdf with hindi fonts. In some pdf  i am getting wrong characters. With some pdf it is working fine but with some it's not loading correctly........

![pdfjs](https://cloud.githubusercontent.com/assets/8165047/13722749/7e8bec50-e875-11e5-83f9-25e1456952ac.jpeg)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.

**Comment by Snuffleupagus** [comment]
Unfortunately even with the edit made to the initial post, this issue is still missing all the necessary details!
I'm quoting from the *first* paragraph of https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, with emphasis on the required information: 

> The issues are used to track both bugs filed by users and specific work items for developers. Try to file one issue per problem observed. Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: **link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.**

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
