### ISSUE TITLE
History not functional in presentation mode

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#7082]
PDF.js version: latest (c6d2b7f9d9c8fdf75b0b73b5c6bb1b7b7ebcf91d)
Tested with: Firefox 44, Chrome 49.
Example: https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf

Steps to reproduce:
1. Open the above PDF.
2. Enter presentation mode.
3. Click on the link below "Example of a link to internal destination" on the first page. Now the second page will be displayed.
4. Try to go back in history using Alt + Arrow left (or a mouse button if supported).

Expected result:
PDF.js should show the first page again.

Actual result:
PDF.js stays at page 2. If I repeat step 4 again, then I get to the page before the PDF viewer opened (=PDF.js does not store or detect the page position before navigating via an internal link).

**Comment by Snuffleupagus** [comment]
This should be fixed by PR #6272, I just need to find a way (and the time) to split those patches into more testable/reviewable chunks (as asked in for in https://github.com/mozilla/pdf.js/pull/6272#issuecomment-189018446).

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #8775.
