### ISSUE TITLE
Can't create mozcentral package anymore

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#7083]
I'm trying to update the mozilla-central pdf.js import and am running into bustage.

ryanvm@ubuntu:~/repos/pdfjs$ BASELINE=51f6aba gulp mozcentralbaseline mozcentraldiff
[16:45:20] Using gulpfile ~/repos/pdfjs/gulpfile.js
[16:45:20] Starting 'mozcentralbaseline'...

### Creating baseline environment
Cloning into 'baseline'...
done.
Note: checking out '51f6aba'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 51f6aba... Merge pull request #7054 from timvandermeij/fix-typo

### Creating mozcentral baseline environment
[16:45:21] Working directory changed to ~/repos/pdfjs
[16:45:21] Using gulpfile ~/repos/pdfjs/gulpfile.js
[16:45:21] Starting 'mozcentral'...

### Getting extension build number
Extension build number: 135

### Bundling files into build/pdf.js
[16:45:22] Finished 'mozcentral' after 675 ms
cp: no such file or directory: build/baseline/build/mozcentral/*

**Comment by Snuffleupagus** [comment]
This seems to be a regression from PR #7063, and [this line in particular](https://github.com/mozilla/pdf.js/pull/7063/files#diff-da55c948ab565ebe30a2027fe5b721abR1360), since `gulp` is async and the code below is executed *before*  `make mozcentral` has a change to complete.

The simple solution is probably to temporarily revert that change, since the proper solution could be more involved. @timvandermeij Can you look into this?

**Comment by Rob--W** [comment]
@Snuffleupagus `gulp` is called via `exec`, which blocks until the spawned process has exited. Are you sure that this has to do with gulp?

**Comment by Snuffleupagus** [comment]
> Are you sure that this has something to do with gulp?

Considering that reverting that line to `exec('node make mozcentral');` I'm assuming that it's related!

**Comment by timvandermeij** [comment]
This is indeed a really strange regression. Node.js 0.12 provides `execSync`, which leads me to believe that `exec` itself is not completely synchronous. I'll look into this today.

**Comment by timvandermeij** [comment]
@rvandermeulen The issue should be fixed, so https://bugzilla.mozilla.org/show_bug.cgi?id=1256037 can be updated I think.
