### ISSUE TITLE
Printing ONLY blank pages on IE9

### ISSUE THREAD

**Issue by wkeilholz** [mozilla/pdf.js#7086]
The current demo ( https://mozilla.github.io/pdf.js/web/viewer.html ) prints ONLY blank pages (except for the header and footer) on IE9 (the preview works fine).

There is already an IE specific ticket (3983) about pdf.js printing extra blank pages / too small canvas, but this looks like a new/different problem to me. It works fine on IE 10 (contrary to what is reported in ticket 3983).

**Comment by yurydelendik** [comment]
Is it still an issue?

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs. If the problem remains with the *latest* `master` branch commits, let us know and we'll reopen.
