### ISSUE TITLE
Fonts not printed correctly (some special characters - RO), but correctly rendered on screen

### ISSUE THREAD

**Issue by marianrabagel** [mozilla/pdf.js#7092]
OS: Windows Server 2012
Browser: Firefox 44.0.2
Pdf.js version:  1.3.91
I am opening the pdf in the attachment , it is rendered correctly on screen, but when I print it the result has some unknown characters in it (I provided a screenshot of it).
If I try to print the same pdf using the build-in pdf.js from Firefox is working. When I am using the build I took from https://github.com/mozilla/pdf.js/releases it is not.
I think it is related to #6498 .
I have tried to disable layout.css.font-loading-api, but there was no difference.
Any idea if this is a bug or just something that I have done wrong?

Thanks.

![specialcharacters](https://cloud.githubusercontent.com/assets/12893535/14009971/9ab886e0-f199-11e5-81d2-413e34b230aa.png)

[specialChars.pdf](https://github.com/mozilla/pdf.js/files/179664/specialChars.pdf)

**Comment by Zylann** [comment]
I have a similar issue with the pdf.js viewer that is shipped with Firefox 46.0.1 on Windows 10.
First time it printed fine, but all subsequent pages had garbled text (things like % !   '5%   ! and lots of squares), even if I restard the printing for the same document. Same with the XPS writer.

**Comment by timvandermeij** [comment]
Closing as fixed by #7694.
