### ISSUE TITLE
Capturing file path with pdf js

### ISSUE THREAD

**Issue by Aelkeris** [mozilla/pdf.js#7099]
Hello good people of pdf.js, i have a question. Can i somehow capture opening of a pdf file, that is done in viewer.html, and then use the path of the file captured. Or if i cannot do that, can someone tell me, where is the functionality that handles the file opening ? 

Because i have multiple ways of opening a file, and i would like the file openings to be compatible. So for example, if i do a drag and drop on my div, i would like the viewer.html to show the dropped file, and vice versa, if i open file using pdf.js's open file, that my div would change colour, or whatnot.

**Comment by timvandermeij** [comment]
It depens on if you have a custom viewer or use the default PDF.js viewer. For custom viewers there is the `api.getDocument` call (see for example https://github.com/mozilla/pdf.js/blob/master/examples/helloworld/hello.js#L10). In the default PDF.js viewer we have https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L1526-L1548. More specifically, https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L576 handles opening a file.

Cloising as answered.
