### ISSUE TITLE
PDF file with "É" char : 

### ISSUE THREAD

**Issue by kriska360** [mozilla/pdf.js#7101]
Attached file can not be loaded.
Uncaught Error: Requesting object that isn't resolved yet g_font_2_path_E
[EBug.pdf](https://github.com/mozilla/pdf.js/files/184631/EBug.pdf)

**Comment by yurydelendik** [comment]
Please provide versions of OS, browser and PDF.js. Works for me.

**Comment by kriska360** [comment]
Attached file can not be loaded if PDFJS.disableFontFace = true

PDF.js : 1.4.20
OS : WINDOWS 10  PRO 64 bits French
Browser : Chrome 47.0.2526.111
