### ISSUE TITLE
PDF Pages as Images

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7103]
This is more of a feature request.

Are there plans to have like an option to have PDF.JS output pages as images instead of HTML?

Yes, this would mean search functionality and text selection are disabled.

**Comment by Rob--W** [comment]
PDF.js outputs on `<canvas>` elements, which is more like an image than HTML.

What is the issue that you're trying to solve by this feature request?

**Comment by yurydelendik** [comment]
See http://mozilla.github.io/pdf.js/examples/ . Closing the issue because the PDF.js is doing that already.

**Comment by chitgoks** [comment]
@yurydelendik  thanks

@Rob--W yes i am aware of that. i was under the assumption that storing full blown images in a canvas is more resource expensive than an <img> tag.
