### ISSUE TITLE
Font not found -> Use a default font

### ISSUE THREAD

**Issue by Graphfx** [mozilla/pdf.js#7109]
Hi,

I’m currently developing a cross-platform desktop application with Electron that allows the user to read any of his PDFs using PDFJS. However, with some PDFs, the fonts are not found and only the images are displayed. The following error message is displayed:

`Failed file:///…/assets/libs/pdfjs/null<FontName> to load resource: net::ERR_FILE_NOT_FOUND` 

To be more specific, it's `null<FontName>` such as `nullAdobe-CNS1-UCS2` for example.

How to solve this issue ? Is it possible to set a default font to use when a font is not found?

Thank you for your help. 

**To reproduce the issue**:
```
git clone https://github.com/Graphfx/PDFJS-Font-Not-Found.git
cd PDFJS-Font-Not-Found
npm install && npm start
```

[Here is the repository to reproduce the issue
](https://github.com/Graphfx/PDFJS-Font-Not-Found)

**Comment by timvandermeij** [comment]
I wonder where `nullFontName` is coming from. It does not look like something PDF.js generates, but I might be wrong here...

**Comment by yurydelendik** [comment]
Not enough information provided to reproduce the issue. Please file the issue template and provide link to the repo with source code for the custom solution.

**Comment by Graphfx** [comment]
@timvandermeij Sorry, I would mean `null<Name of the font>` (such as `nullAdobe-CNS1-UCS2` for example). 

@yurydelendik To reproduce the issue:
`
git clone https://github.com/Graphfx/PDFJS-Font-Not-Found.git
cd PDFJS-Font-Not-Found
npm install && npm start
`

**Comment by Snuffleupagus** [comment]
> I would mean null<Name of the font> (such as nullAdobe-CNS1-UCS2 for example).

This would suggest that the problem here is that the Adobe CMaps are not included, or that the path to them isn't set correctly (see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L84-L95).

**Comment by Graphfx** [comment]
@Snuffleupagus In fact, the CMaps was not included correctly... I didn't knew about that but it works now.

Sorry for the inconvenience and thank you!
