### ISSUE TITLE
Following a in-document link changes zoom

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7110]
Link to PDF file (or attach file here): http://link.springer.com/content/pdf/10.1007%2Fs11682-015-9412-6.pdf

Configuration:
- Web browser and its version: Chrome Version 51.0.2690.0 canary (64-bit)
- Operating system and its version: Win 10 64b
- PDF.js version: 1.4.55
- Is an extension: Yes

Steps to reproduce the problem:
1. Open the link
2. Click any of the reference links

What is the expected behavior? (add screenshot)
Browser should jump to reference AND zoom should be kept

What went wrong? (add screenshot)
Browser jumps to reference BUT zoom changes

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The PDF file you linked to does *not* appear to be accessible without a login!

Also, please compare the behaviour of the links in PDF.js with Adobe Reader.
Most likely, the PDF file is using destinations that *intentionally* alter the zoom level.

**Comment by qwer1304** [comment]
My bad - Adobe Reader modifies the zoom too. Sorry.
