### ISSUE TITLE
Invalid annotation coordinates

### ISSUE THREAD

**Issue by atrebbi** [mozilla/pdf.js#7115]
annotation coordinates ( item.rect ) , instead of being an array of 4 numbers, is an array of 4 objects, each with 2 fields : gen ( always 0 ) and num ( a progressive index )

the function :

var rect = PDFJS.Util.normalizeRect(
      viewport.convertToViewportRectangle(item.rect));

converts these 4 objects in NaN ( invalid numbers )

**Comment by Snuffleupagus** [comment]
Unfortunately this issue does not contain enough information to reproduce it.
As the *first* line of the issue template says, please provide a PDF file that demonstrates the issue!

**Comment by Snuffleupagus** [comment]
I have a theory about the cause of this issue, and have a tentative patch for it, but you need to provide the PDF file in question in order for me to test that theory.

**Comment by atrebbi** [comment]
I have a problem, the pdf has logo of customer and i can't publish it, may i send it privately ?

**Comment by Snuffleupagus** [comment]
> I have a problem, the pdf has logo of customer and i can't publish it, may i send it privately ?

Sure, there's an email address in my GitHub profile.

**Comment by yurydelendik** [comment]
Let's keep 4-information-requested attached to follow up -- the project contributors cannot address issue as it's stated.

**Comment by timvandermeij** [comment]
Okay, but in the PR above we already have a minimal testcase because the file was sent privately.
