### ISSUE TITLE
Current version of viewer.js does not work with IE 11

### ISSUE THREAD

**Issue by JohnEwen** [mozilla/pdf.js#7119]
The version of viewer.js that comes with PDF.js version 1.3.91 does not work with IE 11 but works with Chrome, FireFox and Edge - all under Windows. The version that comes with PDF.js version 1.1.114 (the one provided with ViewerJS) **does** work with IE 11. The error message is generated by pdf.js - not viewer.js.

The problem is solved by replacing this line in the code block at the end of pdf.js:

    var pdfJsSrc = document.currentScript.src;

with the corresponding code from the earlier version of pdf.js

    var scriptTagContainer = document.body ||
                             document.getElementsByTagName('head')[0];
    var pdfjsSrc = scriptTagContainer.lastChild.src;

This seems to be the only change required.

**Comment by Snuffleupagus** [comment]
As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-browsers-are-supported, in order to support browsers such as IE you need to use https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js.

Closing as answered.
