### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by PremTester** [mozilla/pdf.js#7123]
![404](https://cloud.githubusercontent.com/assets/6542369/14085795/1fee3976-f54c-11e5-9b2e-baa044a8fe56.png)
![html](https://cloud.githubusercontent.com/assets/6542369/14085796/1ff40b4e-f54c-11e5-9e40-7a431eeddf65.png)

I'm did the following step from https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website
When i click on the link to view pdf is display 404 not found i have no idea what wrong with it.

**Comment by yurydelendik** [comment]
A web server does not point for the PDF.js root or not properly handles PDF.js files as static resource. Not information provided about which application server is used and how it's configured. Closing as incomplete. 

Provide link to the repo with complete code and steps to reproduce the issue on different computer to reopen the issue.
