### ISSUE TITLE
PDFViewerApplication.open memory usage

### ISSUE THREAD

**Issue by IrvinDominin** [mozilla/pdf.js#7127]
Link to PDF file (or attach file here): https://www.dropbox.com/s/f1yt19l3rcwftxt/catalogo.pdf?dl=0

Configuration:
- Web browser and its version: iOS 9.2.1 webview
- Operating system and its version: iPad 2 with iOS 9.2.1
- PDF.js version: 1.3.91

I'm loading the viewer https://github.com/mozilla/pdf.js/issues/7018 so I:
- Get the pdf saved locally
- convert it to base64 using btoa
- convert it in Uint8Array using the function:
```
		function base64ToUint8Array(base64) {
			var raw = atob(base64);
			var uint8Array = new Uint8Array(raw.length);
			for (var i = 0; i < raw.length; i++) {
			  uint8Array[i] = raw.charCodeAt(i);
			}
			return uint8Array;
		}
```
- load it into viewer using:
```
			var DOMContentLoaded_event = document.createEvent('Event');
			DOMContentLoaded_event.initEvent('DOMContentLoaded', true, true);
			window.document.dispatchEvent(DOMContentLoaded_event);
			PDFViewerApplication.open(pdfData);
```

The issue is that the memory and processor usage goes to top, and often the app crash...

Tha app crash by scrolling the pdf too, debugging on iOS I see:

> Message from debugger: Terminated due to memory issue

I think is a memory leak, GC or something related, how can I handle this?

I track the growth, and the app memory goes from ~112Mb to ~242Mb at the end of the opening and goes to ~350Mb if I open the thumnail panel.

I set to null each var involved in the opening of the pdf in the **open** promise then callback:
- the base64Data transformed document
- the file reader
- the Uint8Array

Alternatively, is there a better way to load a local file into the viewer? By local I mean that the file can be offline and is saved locally inside a shell app.

I tried using the Base64 encoding and decoding suggestion 2 from mdn:

> Solution #2 – rewrite the DOMs atob() and btoa() using JavaScript's TypedArrays and UTF-8
> 
> Use a TextEncoder polyfill such as TextEncoding (also includes legacy windows, mac, and ISO encodings), TextEncoderLite, or Buffer and a Base64 polyfill such as base64-js.
> 
> The simplest, most light-weight solution would be to use TextEncoderLite and base64-js.

but without any improvment.

How can I destroy a viewer instance in order to free memory?

Kind regards,
Irvin Dominin

**Comment by yurydelendik** [comment]
( See discussion about base64 at https://github.com/mozilla/pdf.js/issues/7059#issuecomment-191878493 ) And with you using base64 encoding, JS might allocate somewhat 50 MB just for pdf data. Simple answer if use Uint8Array and free it as soon as worker loaded the document.

Try to reduce/limit PDFJS.maxCanvasPixels if you are using generic/desktop viewer -- the canvases take lots of memory on the iPads.

> Alternatively, is there a better way to load a local file into the viewer?

Not sure what kind of I/O operations you can use within an app. But you can implement [PDFDataRangeTransport](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L550) to fetch data in chunks.

Closing as anwsered.

**Comment by IrvinDominin** [comment]
I have implemented both point 1 and 2, and the memory usage goes down; now I want to:

> Not sure what kind of I/O operations you can use within an app. But you can implement PDFDataRangeTransport to fetch data in chunks.

Thanks @yurydelendik; currently I have to display a file saved locally, I get it with an xhr, load it in a FileReader using `readAsArrayBuffer` and then opening it in the viewer using:
```
			var DOMContentLoaded_event = document.createEvent('Event');
			DOMContentLoaded_event.initEvent('DOMContentLoaded', true, true);
			window.document.dispatchEvent(DOMContentLoaded_event);
			
			PDFViewerApplication.open(pdfData).then(function(){
				pdfData=null;
				reader=null;
			});
```
How do I, if possibile, add PDFDataRangeTransport for chunk reading and display?

**Comment by yurydelendik** [comment]
> PDFDataRangeTransport for chunk reading and display

There is no example but you can looks at implementations in [unit test](https://github.com/mozilla/pdf.js/blob/master/test/unit/api_spec.js#L890) and [Firefox extension](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L453). I'm not sure iOS webview let's read data in chunks, but try slicing the file (see example at https://www.w3.org/TR/FileAPI/#slice-method-algo)
