### ISSUE TITLE
PDF Links not working

### ISSUE THREAD

**Issue by laurenw92** [mozilla/pdf.js#7137]
Link to PDF file :http://beta.wetlandhealth.org/the-ramsar-wetland-disease-manual/practices/

Using pdf.js latest version.

On clicking 3.1.1 it displays the pdf but does not allow the links to be clicked. The pdf contains links and the links work in adobe acrobat with automatic creation turned off

Creating these dynamically on the page using jquery and javascript.

**Comment by Snuffleupagus** [comment]
That page is using a custom PDF.js implementation to display those PDF files, so this is unfortunately not something that we can help with. I'd suggest that you report the issue directly to the website instead.

Closing as invalid.

**Comment by laurenw92** [comment]
Hello,
Can you please explain how this is using a custom PDF.js implementation? 

We have changed to using the example here https://mozilla.github.io/pdf.js/examples/ however the links are still not working?

**Comment by yurydelendik** [comment]
> Can you please explain how this is using a custom PDF.js implementation?

> We have changed to using the example here https://mozilla.github.io/pdf.js/examples/ however the links are still not working?

@laurenw92 The above is exactly what we meant: you took our example and changed it for you needs. Looks like you have to add annotation layer handling to your solution: we have annotation layer and you just need to handle navigation to the needed destination.

**Comment by yurydelendik** [comment]
Perhaps examples at https://github.com/mozilla/pdf.js/tree/master/examples/components will be more useful -- please notice link service is used there and you may extend it.

**Comment by laurenw92** [comment]
@yurydelendik Thanks for the examples, unfortunately they don't work. The functions mentioned don't exist in build/pdf.js
