### ISSUE TITLE
All page text missing in IE 11, but not in chrome

### ISSUE THREAD

**Issue by calioptrix** [mozilla/pdf.js#7141]
Link to PDF file (or attach file here):
[blankinvoice.PDF](https://github.com/mozilla/pdf.js/files/198961/blankinvoice.PDF)

Configuration:
- Web browser and its version:IE 11.0.9600.18230, update versions 11.0.29.  The "install new versions" automatically box is checked. All windows updates applied as of March 31, 2016
- Operating system and its version: Windows 7 Pro x64
- PDF.js version:1.2.109 and 1.3.91 have the same issue
- Is an extension:no

Steps to reproduce the problem:
1. Use pdf.js to render the attached blankinvoice.pdf
2.

What is the expected behavior? (add screenshot)
![proper pdf rendering](https://cloud.githubusercontent.com/assets/11166069/14197423/33b4a0f6-f79c-11e5-9f36-15e55b4d4e66.PNG)

What went wrong? (add screenshot)
In IE the lines and background colors are displayed, but there is no text. In chrome, the document renders correctly.

In the developer tools in IE, I receive this error on every pdf (even those that render correctly):
Unable to get property 'src' of undefined or null reference
File: pdf.js, Line: 9529, Column: 5

![pdf with no text](https://cloud.githubusercontent.com/assets/11166069/14197465/ab0a7194-f79c-11e5-9658-9e1e3d6e765e.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
A link wouldn't do any good. You would need an account to sign in to the system. The company would not let me provide you an account.

**Comment by Rob--W** [comment]
I downloaded the PDF and opened it in the online viewer (https://mozilla.github.io/pdf.js/web/viewer.html) on Browserstack (Windows 7, IE 11.0.9600.17420), and it looks fine.

Are you using the default viewer or a modified version?

**Comment by yurydelendik** [comment]
> In the developer tools in IE, I receive this error on every pdf (even those that render correctly):
Unable to get property 'src' of undefined or null reference
File: pdf.js, Line: 9529, Column: 5

> You would need an account to sign in to the system. The company would not let me provide you an account.

The company developers forgot to include 'web/compatibility.js' library to the custom solution they created. See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Closing as answered. Please provide public access to minimal example with steps to reproduce to reopen the issue.
