### ISSUE TITLE
Working when connected through RDP, not working when physically logged in

### ISSUE THREAD

**Issue by ilistes** [mozilla/pdf.js#7142]
Any PDF.
IE11 latest version, Windows 7, latest stable version of PDF.js.

So basically, if I login physically, the preview is not working. I see no errors in the console, and I have tried debugging it to the best of my capabilities (using built in debug tools).

However, if I RDP to the same computer, and use identical steps, everything works as expected. Same PDF file, same browser, everything is absolutely the same - except for the method of how I login into that computer.

I have zero ideas as how to approach this issue, and any help is appreciated.

**Comment by Rob--W** [comment]
This bug report does not contain enough details for us to act upon. Please provide a more accurate description of the environment and the exact problem you're facing. Add screenshots and/or links if it helps with clarifying the report.

**Comment by ilistes** [comment]
The preview only displays a blank page.
The PDF itself is a valid document and can be opened with some other software. The only scenario in which it does not work is the above scenario.

http://s000.tinyupload.com/index.php?file_id=95915584557367527050

**Comment by yurydelendik** [comment]
Please file https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md . You can attach files and screenshot to the issue.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information as requested above is provided.
