### ISSUE TITLE
Some images are not rendered correctly/at all

### ISSUE THREAD

**Issue by JanSlabon** [mozilla/pdf.js#7143]
Link to PDF file:
[programme.pdf](https://github.com/mozilla/pdf.js/files/199308/programme.pdf)

Configuration:
- Web browser and its version: 45.0.1
- Operating system and its version: Windows 10
- PDF.js version: 1.4.181
- Is an extension: no

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html
2. Load the PDF file

What is the expected behavior?
All images should be visible.

What went wrong?
Some images are not shown:
- left side on page number 2:
![shot](https://cloud.githubusercontent.com/assets/12390057/14203089/26263f34-f7fc-11e5-96ad-498d37065fe1.PNG)
- left side on page number 4:
![shot2](https://cloud.githubusercontent.com/assets/12390057/14203208/e5c8048a-f7fc-11e5-8a1b-91da5aa86ee2.PNG)

Link to a viewer: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
This is a regression from PR https://github.com/mozilla/pdf.js/pull/4161 (and it looks similar to the other open SMask regressions).

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7176.
