### ISSUE TITLE
PDF JS don't show the letters correctly in comb fields

### ISSUE THREAD

**Issue by rmmto** [mozilla/pdf.js#7151]
I'm using the PDF JS as PDF Viewer.
When I open a PDF document with comb fields the letters aren't correctly inserted on the squares. The text is showed like normal text instead of each letter be inside on his own square.

If you can at least point me in the right direction I'd really appreciate it.

Thanks.

**Comment by yurydelendik** [comment]
Closing as incomplete -- not enough information provided to reproduce the issue.
