### ISSUE TITLE
Trying to get viewer.html working in iframe

### ISSUE THREAD

**Issue by AndrewStipdonk** [mozilla/pdf.js#7152]
I am trying to implement PDF.js into an <iframe>.  When I use a link it works fine but when I use an iFrame I get javascipt errors in compatibility.js / debugger.js / viewer.js and the document does not show.  I have the link in one line of code and the iframe in the other.  both reference the same file through the same path.  Is there anyplace or anyone that can tell me what may be going wrong (I am presuming on my side).

Configuration:
Visual Studio 2013
IE 11
PDF.js v1.3.91

Pertinent Code:
																	<a href="http://myapp/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf" runat="server">View</a>
																	<iframe src="http://myapp/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf" height="800px" id="fraViewDocumentsPDFViewer" runat="server" width="800px"></iframe>

Thank you.

**Comment by yurydelendik** [comment]
Works for me at http://output.jsbin.com/zihixufubi/ . Provide all information as requested at https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and link to your web site.

**Comment by yurydelendik** [comment]
I don't think PDF.js matters much, however mode in which IE11 runs can break iframe display.

**Comment by AndrewStipdonk** [comment]
I see.  The mode was set to 7.  Once I set it to 10 or above it works fine.  Thank you for the info :)
