### ISSUE TITLE
error to load pdf on foreign url with pdf.js

### ISSUE THREAD

**Issue by gildassamuel** [mozilla/pdf.js#7153]
Hello,
I have this error when i want to load pdf from foreign url

Error: file origin does not match viewer's
throw new Error('file origin does not match viewer\'s');

please help!

**Comment by yurydelendik** [comment]
It's done on purpose, see #6916. Modify viewer.js to include your hosts origins in the HOSTED_VIEWER_ORIGINS list. Closing as answered.

**Comment by gildassamuel** [comment]
Thanks @yurydelendik 
But I don't know how this answer help me

**Comment by yurydelendik** [comment]
> But I don't know how this answer help me

>> Modify viewer.js to include your hosts origins in the HOSTED_VIEWER_ORIGINS list.

**Comment by gildassamuel** [comment]
I did it but I do not know how to call my remote pdf file

**Comment by yurydelendik** [comment]
> I did it but I do not know how to call my remote pdf file

Please explain. Also can you provide the following  information:
- what is URL for the viewer including the file parameter?
- what was changed in the viewer.js code?
- how was configured CORS headers on the server that host PDF?

**Comment by gildassamuel** [comment]
My pdf file is on cloudinary .
And when I put the access in DEFAULT_URL variable , I got error
Error : file viewer 's origin Does not match
throw new Error ( 'file viewer origin Does not match \' s ');

**Comment by gildassamuel** [comment]
exemple of my url pdf http://res.cloudinary.com/image/upload/v1459791656/my_file.pdf

**Comment by gildassamuel** [comment]
I resolve to comment this lines in viewer.js

if (fileOrigin !== viewerOrigin) {
    throw new Error('file origin does not match viewer\'s');
    }

**Comment by rrecurse** [comment]
Don't comment out logic. Use console.log() to see if your fileOrigin and viewerOrigin match. Make sure at least one entry in your HOSTED_VIEWER_ORIGINS object matches the viewerOrigin and the "_File origin does not match viewer_" error will disapper.

Add this:

`
console.log('fileOrigin', fileOrigin);
`
`
console.log('viewerOrigin', viewerOrigin);
`

... right above:

`
if (fileOrigin !== viewerOrigin) {
`
`
throw new Error('file origin does not match viewer\'s');
`
`
}
`

I'd bet a nickel you're missing (or have) an added slash at the end of your URL like I did (discovered when console logging those two vars). 

Hope this helps someone.

**Comment by yaliashkevich** [comment]
It would be nice to be able to configure HOSTED_VIEWER_ORIGINS array with regex/wildchars.

**Comment by AndrewRayCode** [comment]
In order to allow for non-hard-coded Mozilla domains, I have to modify the source code of a 10k line built file called viewer.js?????

**Comment by james4388** [comment]
The proper fix is open viewer.js and append your file's host to HOSTED_VIEWER_ORIGINS
`var HOSTED_VIEWER_ORIGINS = ['null', '.....'];`

**Comment by abrasat** [comment]
I have the same issue (file origin does not match viewer's) on UWP with local pdf file. What entry exactly must be added to HOSTED_VIEWER_ORIGINS for a local path ?

**Comment by cunnpole** [comment]
For anyone else using this within an app I had to add 'file://' to allow local paths to work. 

   var HOSTED_VIEWER_ORIGINS = [
    'null',
    'http://mozilla.github.io',
    'https://mozilla.github.io',
    'file://' //local viewer in app
   ];

**Comment by GustavoDomingueti** [comment]
I had the same problem  and I resolved:

var HOSTED_VIEWER_ORIGINS = [
       'null',
       'http://mozilla.github.io',
       'https://mozilla.github.io',
       'http://localhost:5000'
];

But *don`t remove the checking code*:

```
if (fileOrigin !== viewerOrigin) {
       throw new Error('file origin does not match viewer\'s');
}
```

**Comment by AlexanderGalas** [comment]
I think adding these 2 lines will be a good solution. Your local ip will detect automatically (wherever you start your application)

```
  var LOCAL_AUTO_DETECT_ORIGIN = window.location.origin;

  var HOSTED_VIEWER_ORIGINS = ['null', 'http://mozilla.github.io', 'https://mozilla.github.io'];

  HOSTED_VIEWER_ORIGINS.push(LOCAL_AUTO_DETECT_ORIGIN);
```

**Comment by yarostbaklajana** [comment]
> It's done on purpose, see #6916. Modify viewer.js to include your hosts origins in the HOSTED_VIEWER_ORIGINS list. Closing as answered.

helped me

**Comment by mdtaslimkhan** [comment]
it a very bad problem, any how hant solved yet

**Comment by lk77** [comment]
Hello,

is there a reason for this ?

it's the browser responsability to care about cors policy, not pdfjs
i think this check should be removed.

**Comment by ErAz7** [comment]
as @IK77 mentioned, can you please provide a reason for this ?

**Comment by ErAz7** [comment]
well, I found this : https://github.com/mozilla/pdf.js/pull/6916
@IK77

**Comment by peterzhanghui** [comment]
> 在我的情况下，我在本地编码，遇到了同样的问题，我通过添加**本地地址来解决**：
> 
> ```
> var HOSTED_VIEWER_ORIGINS = [
>        'null',
>        'http://mozilla.github.io',
>        'https://mozilla.github.io',
>        'http://localhost:5000'
> ];
> ```
> 
> 但是**不要删除检查代码**：
> 
> ```
> if (fileOrigin !== viewerOrigin) {
>        throw new Error('file origin does not match viewer\'s');
> }
> ```

This is the correct answer to help me solve the problem, thank you.
