### ISSUE TITLE
PDF Viewer links move to incorrect page

### ISSUE THREAD

**Issue by jamiemjones79** [mozilla/pdf.js#7154]
Link to PDF file (or attach file here): (attached)

Configuration:
- Web browser and its version: Chrome 49.0.2623.87 m
- Operating system and its version: Windows 10
- PDF.js version: 1.3.91
- Is an extension:

Steps to reproduce the problem:
1. Load viewer with attached PDF
2. Click on Links

What is the expected behavior? (add screenshot)
It is expected that clicking the links will move to the correct page in the PDF, however the pages seem to be offset by 1 page

The PDF file was created in Powerpoint.

Opening the PDF in Adobe reader shows the links working correctly

This looks similar in nature to #2401 which has been marked as fixed

[PDFLinkTest.pdf](https://github.com/mozilla/pdf.js/files/204166/PDFLinkTest.pdf)

**Comment by Snuffleupagus** [comment]
> Opening the PDF in Adobe reader shows the links working correctly

It actually depends on the *how* the document is viewed in Adobe Reader. If the PDF document is shown in continuous pages mode (in Adobe Reader), the behaviour of the links is *identical* in both Adobe Reader and PDF.js.
This is really an issue with the PDF itself, which specifies the destinations in an incorrect manner (actually setting the destinations to the bottom left corner of the pages, instead of the top).

**Comment by jamiemjones79** [comment]
Have tested this and can confirm this is correct.

This may not be the forum for this but is there a way of forcing the pdf.js viewer in to single page mode?

**Comment by yurydelendik** [comment]
> This may not be the forum for this but is there a way of forcing the pdf.js viewer in to single page mode?

There is no such mode. Close to what you are looking for is presentation mode or view in "page fit" scale.

**Comment by timvandermeij** [comment]
Closing since we now have a single page viewer (refer to https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js) which you can use for your use case and the PDF file itself describes this behavior.

**Comment by TomaIvanovTomov** [comment]
@timvandermeij  How to set certain page for singlepageviewer ? It always shows me the first page of the document.
