### ISSUE TITLE
Incompatibility pdf.js with google chrome

### ISSUE THREAD

**Issue by gildassamuel** [mozilla/pdf.js#7155]
Hello, 
I use pdf.js to display pdf in my web site.
It work well in Mozilla, But I don't view pdf in google chrome.
Please help.

**Comment by yurydelendik** [comment]
Thank you for reporting the indecent. However there not enough information is provided (see https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md what information is need to properly file an issue) to reproduce it on different computer. Closing as incomplete.
