### ISSUE TITLE
Shortcuts also work in rich text editors

### ISSUE THREAD

**Issue by jurmatix** [mozilla/pdf.js#7156]
Configuration:
- Web browser and its version: Chrome latest
- Operating system and its version: Win10
- PDF.js version: there is no version number in viewer.js :(
- Is an extension: Yes. I've added an rich text editor to make annotations to the PDF

Steps to reproduce the problem:
1. Adding RTE to viewer.html
2. Pressing 'r', 'k', 'p', 'j', 'n' or any other shortcut without Shift or Control in RTE.

What is the expected behavior?
The pressed key should be only inserted in to the RTE.

What went wrong?
The shortcut will be also performed in pdf.js (rotating page while pressing 'r' ...).
So far this is the correct behaviour. But there is already code for exeptions starting in line 7823 in viewer.js. I.e. for input, textarea and select fields. But this won't work with div based rich text editors.
Would it make sense to check also "Element.attributes.contenteditable" so that the shortcuts won't get handled if the focus is in an editable element?

**Comment by yurydelendik** [comment]
> Would it make sense to check also "Element.attributes.contenteditable" so that the shortcuts won't get handled if the focus is in an editable element?

We do something similar at https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L2016 -- extend it to recognize other custom elements.

**Comment by Rob--W** [comment]
Add `|| curElement.isContentEditable` to the block that yury referenced.

**Comment by chitgoks** [comment]
Will this option be included in the next pdf.js release? This will be useful for any element having contenteditable not to be affected by those shortcuts

**Comment by angularPublic** [comment]
Adding the bold line below in **pdf.js** fixed the issue with textAngular key events.

Thanks Rob.

...
var curElement = document.activeElement || document.querySelector(':focus');

> if(curElement.isContentEditable) return;

 var curElementTagName = curElement && curElement.tagName.toUpperCase();
 if (curElementTagName === 'INPUT' || curElementTagName === 'TEXTAREA' || curElementTagName === 'SELECT') {
  if (evt.keyCode !== 27) {
   return;
  }
 }
....

**Comment by Snuffleupagus** [comment]
Rather than leaving this open indefinitely, I'd suggest doing one of two things here:
 - Preferably closing the issue as WONTFIX, since this doesn't affect the default viewer as such (but rather only a custom implementation of it).
 - Given the simplicity of the suggestion in https://github.com/mozilla/pdf.js/issues/7156#issuecomment-206357229, accept a patch to fix this (probably qualifies for the `5-good-beginner-bug` label).

**Comment by timvandermeij** [comment]
Sure, please do!
