### ISSUE TITLE
Any PDF not rendering in Android WebView

### ISSUE THREAD

**Issue by srgibbs99** [mozilla/pdf.js#7157]
Link to PDF file (or attach file here):  I've used the sample PDF that comes in the pre-built PDF.js package.  I've also tried other PDF files, from different sources.  The results are the same.

Configuration:
- Web browser and its version: **Android WebView (Appcelerator)**
- Operating system and its version: **Android Marshmallow**
- PDF.js version: **v1.3.91**
- Is an extension: **No**

Steps to reproduce the problem:
1. I used the pre-built viewer to see if it would work in the Android WebView Control in our Hybrid Mobile app
2. I am just loading the sample PDF that comes with the pre-built PDF.js

What is the expected behavior? (add screenshot)

This is how it looks in Chrome on Android, **it looks perfect**:

![pdf-js-chrome](https://cloud.githubusercontent.com/assets/4959116/14303410/ae0c21fc-fb67-11e5-865a-b1fd632ed143.PNG)

What went wrong? (add screenshot)

This is how it looks inside of the Android WebView.  The PDF does download, I can see the "Document Properties" and I can see it in Full Screen mode, but it does not render in normal mode.

![pdf-js-webview](https://cloud.githubusercontent.com/assets/4959116/14303786/59ca726c-fb6a-11e5-8df1-0713e6d7874b.PNG)

![pdf-js-webview-props](https://cloud.githubusercontent.com/assets/4959116/14303866/46487ef4-fb6b-11e5-92e8-0eed0c5b4fb6.PNG)

Both the logs from Chrome and the Android WebView look the same:

![pdf-js-chrome-logs](https://cloud.githubusercontent.com/assets/4959116/14303492/761c0298-fb68-11e5-88af-98735382ffc9.PNG)

I understand that this is likely something to do with the Appcelerator WebView control, however I am wondering if there is some other way I can troubleshoot or find a workaround.  Is there more logging that can be enabled, or some other steps I could try to find the problem?

Thanks.

**Comment by yurydelendik** [comment]
>  some other steps I could try to find the problem?

Since loading is working, try to log some page painting info e.g. if PDFPageView draws anything or page divs are created.

**Comment by srgibbs99** [comment]
> P.S. possible reason that viewer div is not visible, hidden or too small.

Yes!!  You are a genius.  I used the Chrome debugger to inspect the HTML content and indeed, the "height" of the `html`. `body`, and `div#outerContainer` tags are set to "%100". Each has a "Calculated" height of 0px.  So, the `div#viewerContainer` element renders at 0px high as well. Once I add some explicit/actual height to any of those containers, the PDF shows up just fine.

`<div id="viewerContainer" tabindex="0">` <-- This, and all parent elements, render at 0px high

Another oddity is that, once its visible, the PDF is rendered very large.  Its being rendered at over 800px wide even though my screen only has 360 px across.  I'm thinking these two things are related.

Any ideas why the CSS wouldn't be calculating the height of the `html `or `body `tags correctly?  Feels like a media query gone wrong maybe?  Due to something quirky with the Appcelerator WebView?

**Comment by paolocaminiti** [comment]
Same problem with android api 23/reactnative/webview.

As said it's quickly fixed by `document.body.style.height = window.innerHeight + 'px'` although one should take care of dynamic resizing if any.

The rendering to wrong size seems to only affect the emulator, but I tested only on one android 5 device by now.

**Comment by MaluNoPeleke** [comment]
Why is there no integrated PDF.js viewer in Firefox for Android?
Everytime I click on a PDF with my mobile phone (Android Marshmallow, Firefox Beta 48) it gets downloaded instead of displayed inside of the browser.
The extension is deprecated: https://addons.mozilla.org/de/android/addon/pdfjs/

**Comment by AngelVB** [comment]
@srgibbs99 I have the same height problem in a Samsung s6 6.0.1 Could you fix this? Thank you

**Comment by JimVanG** [comment]
@paolocaminiti 
>As said it's quickly fixed by document.body.style.height = window.innerHeight + 'px'

Where do you put that line of code? I'm having issues rending my PDFs inside my webview, they only render about a third of the size...

**Comment by xcarpentier** [comment]
Hi,

I’m working on a solution using pdfjs via react-pdf into react-native and expo app.
https://github.com/xcarpentier/rn-pdf-reader-js
That may helps someone...

**Comment by Snuffleupagus** [comment]
Given the age of this issue, and that it looks platform and/or browser specific (rather than PDF.js related as such), is it actually meaningful to keep it open?
