### ISSUE TITLE
Can't open External PDF URL

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [mozilla/pdf.js#7159]
Link to PDF file (or attach file here):
http://vrinsoft.com/terratrove/upload/chapter/PDF1459862116.pdf

Configuration:
- Web browser and its version: I am using for Phonegap Application(Android/iOS)
- Operating system and its version:
- PDF.js version:
- Is an extension: no

Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html from my Application
2. Load External URL of PDF

What is the expected behavior? (add screenshot)
PDF should be visible and also enable pinch zoom

What went wrong? (add screenshot)
I can't open
![screen shot 2016-04-07 at 11 38 44 am](https://cloud.githubusercontent.com/assets/14848491/14342161/527afe72-fcb5-11e5-8d3d-1101caafe475.png)
 PDF

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by rkaartikeyan** [comment]
@Krishna25Vrinsoft Hi bro did you got the solution to open external URL in this pdf viewer?

**Comment by timvandermeij** [comment]
Do you get errors/warnings in the console? Most likely you're trying to request a file from storage that the app does not have access to, but without any logs this is impossible to tell from the description alone.
