### ISSUE TITLE
API for user actions?

### ISSUE THREAD

**Issue by Asoul** [mozilla/pdf.js#7162]
I want to record user actions for pdf.js.
Is there some API to know what is the current page and total pages? Thanks!

**Comment by timvandermeij** [comment]
There is https://github.com/mozilla/pdf.js/blob/122d4732398ca67381cc469dc2f49696b824c98d/web/pdf_viewer.js#L120 for the total number of pages and https://github.com/mozilla/pdf.js/blob/122d4732398ca67381cc469dc2f49696b824c98d/web/pdf_viewer.js#L128 for the current page number. Most things you'll need can be found in that file.
