### ISSUE TITLE
How to use postmessage in pdf.worker with IE8/9?

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7166]
I'm using postmessage inside of pdf.worker.js to send the pdf-data, line 2469 (function LocalPdfManager)

```
globalScope.postMessage({
          action: 'setPdfData',
          data: data
      });
```

And catching it up in pdf.js to save it into a global variable, line 1492 (function MessageHandler):
```
ah['setPdfData'] = [function ahWriteVariable(data) {
    PDFJS.pdfData = data;
  }];
```

Which is working fine so far. But IE8/9 is not loading the PDF and showing the error: "Message: Argument not optional".

Hope someone may help me out...

**Comment by yurydelendik** [comment]
It hard to tell what is the issue you are trying to solve. IE8 is not supported configuration and IE9 support is limited due to absence of typed array. If you would like some assistance, please publish example online (MCVE) and provide more information.

**Comment by Snuffleupagus** [comment]
Closing, based on https://github.com/mozilla/pdf.js/issues/7168#issuecomment-207029411.
