### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by InteractM** [mozilla/pdf.js#7167]
Are those examples should to work out of the box on Firefox and Chrome (resources located on a local computer)? As far I'm not able to get anything to work and get it to work in a way described here: http://stackoverflow.com/questions/5586717/inline-pdf-viewer

Thanks

**Comment by yurydelendik** [comment]
The examples might not work from local file system, but they will work via local web server (e.g. Chrome disables access of XHR to the file system). See http://mozilla.github.io/pdf.js/examples/learning/helloworld.html which is exact copy of one at https://github.com/mozilla/pdf.js/tree/master/examples/learning . Closing as answered

**Comment by InteractM** [comment]
When I have move 'examples' folder to a web server it came up that I have missing 'build' folder. Did I skipped something?

**Comment by yurydelendik** [comment]
> When I have move 'examples' folder to a web server it came up that I have missing 'build' folder. 

See https://github.com/mozilla/pdf.js#getting-the-code for beginner instructions.
