### ISSUE TITLE
Get PDF Blob inside of pdf.js or pdf-view.js

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7168]
Is it possible to get the PDF Blob somewhere inside of pdf.js or pdf-view.js? Is there any line where it is available so i can save it into a global variable?

I found it within pdf.worker.js but i'm not able to send it to pdf.js in IE9 using postMessage.

**Comment by yurydelendik** [comment]
> Is it possible to get the PDF Blob somewhere inside of pdf.js 

Downloaded via XHR PDF data is accessible via documents getData() method (see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L737) Closing as answered.

**Comment by yurydelendik** [comment]
Try running in IE9 devtools when http://mozilla.github.io/pdf.js/web/viewer.html opened:

```
PDFViewerApplication.pdfDocument.getData().then(function (d) { window.pdfData = d; })
```

**Comment by MickL** [comment]
Yes this function is working fine. Now I don't need the worker anymore(other issue). Thanks for your fast answer(s)!
