### ISSUE TITLE
Replace global JS unit tests file with UMD modules

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#7179]
(continuation of #6905, #7178 and #7172)

The unit tests (in Jasmine) can be loaded via RequireJS. We need to make them as AMD modules. Suggested naming is 'pdfjs-test/unit/file_name'.

Why UMD? I'm thinking we can reuse the same tests and run portion of them on Travis CI via node. Also we can use the same infra to validate the UMD headers.

**Comment by sriranganathan** [comment]
@yurydelendik  Would like to give this a try if it's still open.

**Comment by timvandermeij** [comment]
Feel free to work on this! If you need help, you can contact us on IRC.

**Comment by incorrectusername** [comment]
can i work on this?

**Comment by timvandermeij** [comment]
I'm not sure if @sriranganathan is still working on this. If not, feel free to work on it!

**Comment by incorrectusername** [comment]
@timvandermeij Sir can you tell me how do i proceed? This is my first time.

**Comment by yurydelendik** [comment]
Currently #7934 is opened by@porlan1
