### ISSUE TITLE
spaces missing in uppercase italic font

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7180]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Version 50.0.2661.26 beta (64-bit)
- Operating system and its version: OS X EL CAPITAN 10.11.3 (15D21)
- PDF.js version: main demo (April 11 2016) https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension:

Steps to reproduce the problem:
1. upload this PDF
2.caption of Figure 1 missing spaces in "Figure 1. A page from Jepson’sAFLORAOFCALIFORNIA"

What is the expected behavior? (add screenshot)
Caption of Figure 1 should have spaces "Figure 1. A page from Jepson’s A FLORA OF CALIFORNIA"

What went wrong? (add screenshot)
No spaces

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html
[papertopda.pdf](https://github.com/mozilla/pdf.js/files/213030/papertopda.pdf)

**Comment by yurydelendik** [comment]
The display looks file, it's copy and paste does not insert spaces:

<img width="654" alt="screen shot 2016-04-11 at 8 42 58 am" src="https://cloud.githubusercontent.com/assets/1523410/14429079/883b1ce0-ffc1-11e5-8c09-8f66578ad8c0.png">

Is it correct?

**Comment by ldenoue** [comment]
correct
