### ISSUE TITLE
wrong characters selected

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7182]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Version 50.0.2661.26 beta (64-bit)
- Operating system and its version: OSX El Capitan 10.11.3 (15D21)
- PDF.js version: online
- Is an extension:

Steps to reproduce the problem:
1. upload attached PDF
[topic2vec.pdf](https://github.com/mozilla/pdf.js/files/213508/topic2vec.pdf)

2. caption of Figure 1 replaces , with ; when selecting "(wt−2, wt−1, wt+1, wt+2) "
Also, equation (2) "p(wj |wi) =" replaces | with j
There are more errors throughout the document involving text selections.

What is the expected behavior? (add screenshot)
Expected=selecting right character, not ; instead of , and not j instead of |
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7550.
