### ISSUE TITLE
Remove `combineUrl` from the test files

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7183]
Take a look at https://github.com/mozilla/pdf.js/search?utf8=%E2%9C%93&q=combineUrl for where it is still used. We should replace it with the URL constructor as done in https://github.com/mozilla/pdf.js/pull/7178/files.

**Comment by yurydelendik** [comment]
We still need to test the combineUrl function or remove that from our code.

**Comment by timvandermeij** [comment]
Good point. Now that I come to think of it, couldn't we remove it entirely since we have a polyfill for it (at https://github.com/mozilla/pdf.js/blob/68e8f5fff51f2ee7f845a4217b9419b8676df866/src/shared/util.js#L1692)?

**Comment by yurydelendik** [comment]
@brendandahl already wanted to remove that. Please notice that we shall properly handle `if (!url) {` case when it is needed.

**Comment by prakashpalanisamy** [comment]
Hi, This will be my first contribution, is it okay if I take this issue up and work on it?

**Comment by yurydelendik** [comment]
> Hi, This will be my first contribution, is it okay

Sure, please read https://github.com/mozilla/pdf.js/wiki/Contributing

**Comment by prakashpalanisamy** [comment]
Thank you..

**Comment by prakashpalanisamy** [comment]
there is a source file having reference to combineUrl - api.js in display. Should I replace that refernece too? Or only the test file references?
If src refernces are to be replaced, Should the function also be removed from util.js? - assuming that it will not be used in the future.

**Comment by yurydelendik** [comment]
> there is a source file having reference to combineUrl - api.js in display. Should I replace that refernece too? 

Yes, you can replace that, remove tests and from util.js.
