### ISSUE TITLE
Can't display any pdf in anything other than firefox

### ISSUE THREAD

**Issue by woody1987** [mozilla/pdf.js#7186]
Configuration:
- Web browser and its version: 
       Firefox 44.0.2 (works)
       Chrome 49 (doesnt work)
       IE 11 (doesnt work)
       Edge 20 (doesnt work)
- Operating system and its version: Windows 10 64bit
- PDF.js version: 1.3.91
- Is an extension: no

Steps to reproduce the problem:
1. Download pdf.js from https://mozilla.github.io/pdf.js/
2. extract and open viewer.html

What is the expected behavior?

default pdf compressed.tracemonkey-pldi-09.pdf to be dsiplayed (show in firefox below)
![ff](https://cloud.githubusercontent.com/assets/5889597/14456176/7c3cd53e-009b-11e6-9f6c-094a701108ca.png)

What went wrong? 

Nothing displayed in Chrome, IE or edge

Edge displays an error:
![edge](https://cloud.githubusercontent.com/assets/5889597/14456915/50d30c0c-009f-11e6-9a43-98ef04066c1b.png)

Navigating to http://mozilla.github.io/pdf.js/web/viewer.html does show the pdf in those browsers but I need to be able to display pdfs locally.

Within chrome I can use the open file dialog to display a local file but this doesnt work on IE or edge

**Comment by Snuffleupagus** [comment]
As explained in the [README](https://github.com/mozilla/pdf.js/blob/master/README.md), some browsers don't allow using `file://` URLs like this, so you'll need to use a local server instead. Please see https://github.com/mozilla/pdf.js#getting-the-code.

Closing as answered.
