### ISSUE TITLE
No way to detect if viewer is in hand tool grab-pan mode

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7187]
Manually setting it to presentation mode, i call HandTool.enterPresentationMode();

i looked at the viewer.js and i cannot find any way to detect if the viewer is in presentation mode or not.

is there such function currently?

**Comment by Snuffleupagus** [comment]
There is `isInPresentationMode` in `PDFViewer`, see https://github.com/mozilla/pdf.js/blob/1c253e6e1d44237e12ed165d03c50576f732dcf4/web/pdf_viewer.js#L660, which could be accessed (in the default viewer) using `PDFViewerApplication.pdfViewer.isInPresentationMode`.

Closing as answered.

**Comment by chitgoks** [comment]
hi . snuffleupagus. apologies. it's not the presentation mode but when i click the hand tool mode and activate grab to pan. is there such variable to identify that it is in this mode?

currently im checking if the viewerContainer element has the class grab-pan-... but having a variable to detect that would be better.

**Comment by Snuffleupagus** [comment]
In that case, try using `HandTool.handTool.active`.

Closing as answered.

**Comment by timvandermeij** [comment]
Now that #7207 landed there is `PDFViewerApplication.handTool.isActive` for this.
