### ISSUE TITLE
Thin line is rendered too thick

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#7188]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: ff 45.0.1
- Operating system and its version: W7 64
- PDF.js version: newest
- Is an extension: ?

Steps to reproduce the problem:
1. https://mozilla.github.io/pdf.js/web/viewer.html
2. open the file from https://issues.apache.org/jira/secure/attachment/12652090/CIB-coons-vs-tensormesh.pdf

What is the expected behavior? (add screenshot)
![scr1](https://cloud.githubusercontent.com/assets/6665575/14466424/11fbc950-00d7-11e6-806a-675b84ffe901.jpg)

What went wrong? (add screenshot)
![scr2](https://cloud.githubusercontent.com/assets/6665575/14466432/1926376a-00d7-11e6-80f8-6f96e4f5a0c8.jpg)

I thought this is a regression from todays fix (thanks!) but it is also in the pre-fix version that it in my browser.

**Comment by yurydelendik** [comment]
It is intermittent for me (on Mac OS X).

**Comment by Snuffleupagus** [comment]
I can reproduce this at *some* zoom levels, but *not* at others, which seems very strange.
Interestingly enough, if I use the `Stepper` to render the file one operation at a time, it always works correctly *regardless* of zoom level. Furthermore, if I force the use of the `mozCurrentTransform` polyfill, https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L92-L93, it also works regardless of zoom level.

All this suggests, to me, that `this.ctx.{mozCurrentTransform,mozCurrentTransformInverse}` intermittently returns incorrect values (perhaps the previous ones?).
So one solution, that I've seen mentioned on IRC as a solution for the general transformation mess in `canvas.js`, might be that we track the transforms ourselves, to avoid these (apparent) platform issues.

However, in the meantime, I've found a possible workaround:
```diff
diff --git a/src/display/canvas.js b/src/display/canvas.js
index e9b3563..97a4c5c 100644
--- a/src/display/canvas.js
+++ b/src/display/canvas.js
@@ -2298,7 +2298,9 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
     },
     getSinglePixelWidth: function CanvasGraphics_getSinglePixelWidth(scale) {
       if (this.cachedGetSinglePixelWidth === null) {
+        this.ctx.save();
         var inverse = this.ctx.mozCurrentTransformInverse;
+        this.ctx.restore();
         // max of the current horizontal and vertical scale
         this.cachedGetSinglePixelWidth = Math.sqrt(Math.max(
           (inverse[0] * inverse[0] + inverse[1] * inverse[1]),
```
@yurydelendik Would the code above be an acceptable workaround? If so, I'll happily submit a PR!
