### ISSUE TITLE
PDFView.open() is done?

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7193]
Using `PDFView.open()`, how do i know when pdf or first page is loaded?

**Comment by yurydelendik** [comment]
PDFView is obsolete and was replaced by PDFViewerApplication. PDFViewerApplication.open returns promise that indicates when pdfDocument is ready to be used. Closing as answered.

**Comment by yurydelendik** [comment]
https://github.com/mozilla/pdf.js/blob/master/web/app.js#L621

**Comment by MickL** [comment]
Is this new? I get `Cannot read property 'then' of undefined`

```
PDFViewerApplication.open('myURL').then(function() {
           console.log('DONE');
})
```

P.S. Thanks alot for your blazing fast answer(s)!

**Comment by yurydelendik** [comment]
The version of PDF.js was not provided in the question. So it's assumed the new version of PDF.js was meant.

**Comment by MickL** [comment]
I'm using 1.1.1

**Comment by yurydelendik** [comment]
It's there since v1.2.109 (Nov, 2015) and now currently 1.3 release and 1.4 in beta.
