### ISSUE TITLE
Display only PDF file in file browser

### ISSUE THREAD

**Issue by vanduc1102** [mozilla/pdf.js#7195]
When I click open to open a PDF file. The file browser is open with all file type. What I want is just the file browser display only PDF files.
Like when we did with accept attribute 
`<input type="file" name="pic" id="pic" accept="image/gif, image/jpeg" />`

**Comment by yurydelendik** [comment]
Not all computers are configured to associate ".pdf" with "application/pdf" mime type. Our usage of input element is only in the demo viewer, so it's not critical for us. However supporting request like "why my local PDF is not showing in your demo viewer?" is not desired. 

You can modify your own version of demo viewer at https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1335 if you are sure your user have the mime type configured. Closing as won't fix for us.
