### ISSUE TITLE
Strange characters in preview

### ISSUE THREAD

**Issue by ilistes** [mozilla/pdf.js#7198]
Configuration:
- Firefox
- Windows 7
- Latest stable/latest beta, does not matter

When I try the online demo though, everything appears to work.
That version is a bit ahead of what's available to downoad, maybe that's the cause (1.4.237 comparared t0 1.4.20)?

[example.zip](https://github.com/mozilla/pdf.js/files/220522/example.zip)
![example_capture](https://cloud.githubusercontent.com/assets/3984654/14554576/2b32db2a-02ee-11e6-994c-88dc4a34b8d4.JPG)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #7023, which will be included in future PDF.js releases.

For information about obtaining the *latest* version of PDF.js, please refer to either https://github.com/mozilla/pdf.js#getting-the-code or https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#gh-pages.
