### ISSUE TITLE
What is the maximum size of pdf that can be opened with pdf viewer?? Is the size browser specific?

### ISSUE THREAD

**Issue by sanjivani2208** [mozilla/pdf.js#7199]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Maximum size of PDF is specific to what particular browser can support.
