### ISSUE TITLE
PDF page contents with a null value in its DecodeParms are rendered blank

### ISSUE THREAD

**Issue by eljolge** [mozilla/pdf.js#7200]
PDF file: [Dokument_ohneOCR.pdf](https://github.com/mozilla/pdf.js/files/220724/Dokument_ohneOCR.pdf)

Configuration:
- Web browser and its version: 
  - Chrome 49.0.2623.112
  - Firefox 45.0.2
- Operating system and its version: Mac os X 10.11.3 (15D21)
- PDF.js version: 1.3.91
- Is an extension: No

Steps to reproduce the problem:
1. Open the PDF with the viewer
2. A blank page is displayed. The console shows this message: 'Warning: Invalid stream: "TypeError: params.get is not a function'
![screen shot 2016-04-15 at 13 09 50](https://cloud.githubusercontent.com/assets/3442509/14559754/5f94cdf2-030b-11e6-99bd-813ca1a89385.png)

What is the expected behavior?
- The viewer must display the text of the page (a Lorem ipsum text)
![screen shot 2016-04-15 at 13 07 30](https://cloud.githubusercontent.com/assets/3442509/14559732/2863f2d6-030b-11e6-98ce-b75b888fb563.png)

What went wrong?
The attached pdf file contains a null value in the DecodeParms array of the /Contents of the /Page.
![screen shot 2016-04-15 at 13 29 41](https://cloud.githubusercontent.com/assets/3442509/14560192/4c383250-030e-11e6-832e-99204319674b.png)
The following lines are the source PDF objects
```
9 0 obj
<</Type/Page/Parent 3 0 R/MediaBox[0 0 595.275591 841.889764]/Contents 10 0 R/Resources 12 0 R>>
endobj
10 0 obj
<</Filter/FlateDecode/Length 165/DecodeParms[null]>>stream
x�u�1AE{N�D`�a�71�Syc��լ��'�l�4��X������=��DZZ3Jͬ�Y��yI���n��|3
��nт�5��%�0X���e���B�4���F�\�M8"�`ҨTQ�����<�VȱZk16�T)e��������L������7�*�9�
endstream
endobj
```
The warning message is thrown because the PredictorStream function from stream.js starts with the following line:
```javascript
    var predictor = this.predictor = params.get('Predictor') || 1;
```
The previous code fails if params is an array containing a null value. The rest of the PredictorStream logic is not executed, so no stream is returned.

I have been able to render the document property by enclosing that line in a try/catch block:
```javascript
    try {
      var predictor = this.predictor = params.get('Predictor') || 1;
    } catch (e) {
      predictor = this.predictor = 1;
    }
```
Maybe it's not the best solution, but it works (The last time I did something serious with JS was with Netscape :-P).

Just a little bit of additional information: Mac OS X Preview behaves exactly like PDF.js whereas the file is rendered properly by Adobe Acrobat Reader DC.

[Link to a viewer](https://mozilla.github.io/pdf.js/web/viewer.html?file=https://dl.dropboxusercontent.com/u/7466413/Dokument_ohneOCR.pdf).

**Comment by Snuffleupagus** [comment]
@eljolge Thanks for the *very* thorough bug report!
Are you the creator of the PDF file, and if so can we include it in our test-suite?

**Comment by eljolge** [comment]
No, I am not -directly- the creator, but you can include it in your test-suite. No problem.

**Comment by Snuffleupagus** [comment]
> No, I am not -directly- the creator, but you can include it in your test-suite. No problem.

Thank you! The fix for this issue has now landed.
