### ISSUE TITLE
pdfjs-dist repository does not contain every file generated by 'gulp generic'

### ISSUE THREAD

**Issue by keabard** [mozilla/pdf.js#7203]
In pdfjs-dist repository (https://github.com/mozilla/pdfjs-dist), there are many files missing:

- `viewer.html`
- `viewer.js`
- `l10n.js`
- `debugger.js`
- locale files
- etc...

The resulting repository is therefore unusable, even with a custom viewer.html.

Is there something missing in `make.js` or am I totally missing the point ?

The guy from PDFObject uses `viewer.html` from pdf.js repository, along with other missing files, to build his example with pdf.js fallback (http://pdfobject.com/examples/pdfjs.html).

How can I do the same without the missing files ?

**Comment by yurydelendik** [comment]
We are not redistributing viewer.html to avoid (visual?) confusion of third party deployments with Firefox and Chrome extensions UI, as well as our demo viewer. There is no easy way to customize viewer.html/viewer.js, so it's not in a library yet. However there is set of components that will let you build customized viewer, see pdfjs-dist/web/pdf_viewer.js file and examples at https://github.com/mozilla/pdf.js/tree/master/examples/components. Once we will confident that our viewer can be easy customized (we are slowing working towards that) and not mistaken for the extensions, we will may include the listed files in some form. Closing as answered.

**Comment by yurydelendik** [comment]
See also http://mozilla.github.io/pdf.js/getting_started/
