### ISSUE TITLE
Unify the primary toolbar in a module

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7205]
Currently it's scattered througout `web/app.js`, which isn't ideal. If we have a separate entity for this, it will be good to create an event based structure to let the primary and secondary toolbar send events to the viewer to remove the dependencies that are currently there, such as #7204 shows.

**Comment by yurydelendik** [comment]
#7209 might help a little

**Comment by timvandermeij** [comment]
#7458 also helped with this.
