### ISSUE TITLE
If browser can not support view pdf,can auto turn download (such as IE7,IE8)

### ISSUE THREAD

**Issue by wslpeter** [mozilla/pdf.js#7214]

**Comment by yurydelendik** [comment]
IE8 and below are not supported. Closing as invalid. 

You can add [a server side solution](http://blogs.microsoft.co.il/egoldin/2009/07/29/detecting-ie8-on-server-side/) to detect older browsers or add additional script before compatibility.js and pdf.js that checks for old IE and redirects to PDF link. Both of them out of scope of the project.

**Comment by wslpeter** [comment]
Thank you very much
