### ISSUE TITLE
Doesnt work in IE11

### ISSUE THREAD

**Issue by Xurma2** [mozilla/pdf.js#7216]
![screenshot_2](https://cloud.githubusercontent.com/assets/5157416/14603057/4a52bd76-0574-11e6-8bad-f25f3015d67d.png)

If i change it
`    var pdfJsSrc = document.currentScript.src;`

at it
```
var pdfJsSrc = (function() {
      var scripts = document.getElementsByTagName('script');
      return scripts[scripts.length - 1].src;
})();
```

All works fine in ie11

Both file pdf.js and pdf.worker.js

**Comment by yurydelendik** [comment]
Add web/compatibility.js to your page to avoid the above. Also it was already fixed in newer version of PDF.js (https://github.com/mozilla/pdf.js/blob/master/src/pdf.js#L34). Closing as invalid.
