### ISSUE TITLE
PDF.js throws error in Visual Studio 2013 Asp.Net MVC Project

### ISSUE THREAD

**Issue by DevQueen** [mozilla/pdf.js#7218]
I receive the following error when I run my project:
Unhandled exception at line 9529, column 5 in http://localhost/SSQV4/SSQV5/Scripts/pdf.js

0x800a138f - JavaScript runtime error: Unable to get property 'src' of undefined or null reference

and it stops at the following line in the pdf.js file:

 var pdfJsSrc = document.currentScript.src;

Nuget would not add pdf.js in VS 2013 so I had to add pdf.js and the worker files manually.

**Comment by yurydelendik** [comment]
For IE, add web/compatibility.js or use new version. Closing as dup of #7216

**Comment by DevQueen** [comment]
I have compatibility.js, but I still get that error.  Am I missing something else?

**Comment by yurydelendik** [comment]
You did not provide enough information to reproduce the issue on the computer other than yours. Please provide all information requested by https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md . See also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md .

**Comment by DevQueen** [comment]
Browers: IE 11
Operating System: Windows 7 Ultimate
Pdf,js version 1.3.31
Steps to Reproduce:
I add pdf.js.. pdf.worker.js and compatability.js to my project.  I added script tags to pdf.js and compatability.js to my layout page.  I ran the project in debug mode, and the error happens.  It does NOT happened in Chrome, only IE.

**Comment by timvandermeij** [comment]
Could you provide a link to your project (e.g., on JSBin or a custom server for example) so we can try to reproduce the issue?

**Comment by DevQueen** [comment]
I copied the source file that you have on Git Hub now as I noticed it was different from the one that downloads in your zip file.  The error is no longer occurring.  Thank you for your help!

**Comment by yurydelendik** [comment]
> I copied the source file that you have on Git Hub now as I noticed it was different from the one that downloads in your zip file.

Please explain: which zip and js files you are referring too?

**Comment by DevQueen** [comment]
I clicked Download.Zip on the Code page and I received an older version of pdf.js.  I received version 1.3.91.  It is not the same as what shows in the src folder here.

**Comment by yurydelendik** [comment]
I see. You cannot use non-built source code of PDF.js in the production. As a user, you shall only download code listed in the released.
