### ISSUE TITLE
PDFJS lines smaller than 0.75px not appearing consistently

### ISSUE THREAD

**Issue by vivek6** [mozilla/pdf.js#7223]
[Sample_Lines.pdf](https://github.com/mozilla/pdf.js/files/226823/Sample_Lines.pdf)

Configuration:
- Chrome 49.0.2623.75
- Windows 7
- PDF.js version: 1.1.215

Steps to reproduce the problem:
1. Open the attached pdf in pdfjs viewer.
2. lines drawn with 0.25 or 0.5 px is not appearing consistently.

What is the expected behavior? All lines should be visible

What went wrong? lines drawn with 0.25 or 0.5 px is not appearing consistently. If I add a <BR> before the 0.25px or 0.5px lines, the lines magically appears. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): We have viewer integrated with Application. But this problem exists in Chrome Extension too.

**Comment by yurydelendik** [comment]
Could you show what do you mean? Looks fine on FF and Chrome for me (on Mac OS):

<img width="586" alt="screen shot 2016-04-19 at 4 11 11 pm" src="https://cloud.githubusercontent.com/assets/1523410/14655766/7c04b6b4-0649-11e6-978c-56fcbed81a90.png">

<img width="651" alt="screen shot 2016-04-19 at 4 12 44 pm" src="https://cloud.githubusercontent.com/assets/1523410/14655789/9a49508a-0649-11e6-9f15-118d300a788d.png">

Also looks like you are using out-of-date PDF.js. Did you try the same file at http://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by vivek6** [comment]
![image](https://cloud.githubusercontent.com/assets/18561428/14655990/aab12136-064a-11e6-982d-2bb122083023.png)

I Just tried in pdfjs chrome extension (on windows 7). I dont see the 0.25px line at all in section 1 and section 2. And in Section 3, I dont see 0.5 px line.

**Comment by yurydelendik** [comment]
The issue depends on OS and/or browser. Looks like other PDF Viewers (e.g. Mac OSX Preview) has similar issue.

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue, secondly the fact that it looks very much platform/browser-specific, and finally that recently a number of improvements have been made to the handling minimum line sizes; does it still make sense to keep this issue open?
