### ISSUE TITLE
Printing PDF without text

### ISSUE THREAD

**Issue by sanzmiguel** [mozilla/pdf.js#7225]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Google Chrome 49.0.2623.112 m
- Operating system and its version: Windows 10
- PDF.js version: 1.3.91

Steps to reproduce the problem:

I am doing my first code with the PDF.js, but I´m having one problem. When I try to show the PDF file in a canvas tag, the canvas shows the PDF without the text. I show you down the code that I wrote, the PDF file and what the canvas is showing. What is wrong? Am I forgiving anything??

Thank you.

```
function convertPDF(){
	var url = 'doc/ficha.pdf';
	var canvas = document.getElementById('canvas');
	var ctx = canvas.getContext('2d');
	 PDFJS.getDocument(url).then(function (pdfDoc_) {
		pdfDoc = pdfDoc_;
		var num_paginas = pdfDoc.numPages;
		pdfDoc.getPage(1).then(function(page) {
			var viewport = page.getViewport(scale);
			canvas.height = viewport.height;
			canvas.width = viewport.width;

			// Render PDF page into canvas context
			var renderContext = {
				canvasContext: ctx,
				viewport: viewport
			};
			var renderTask = page.render(renderContext);
		});
	});
}

```
What is the expected behavior? 

![pdf](https://cloud.githubusercontent.com/assets/18249386/14668086/abd90806-06e2-11e6-836c-f9c4c6d99250.JPG)

What went wrong? (add screenshot)

![sintexto](https://cloud.githubusercontent.com/assets/18249386/14668090/b4e2c4dc-06e2-11e6-8d93-4ecae0e80135.JPG)

**Comment by Snuffleupagus** [comment]
Please read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, since this issue currently does not contain enough information be valid.

First of all, if this issue is limited to a *particular* PDF file, please provide the file either via a link or attached to this issue.
Also, since this seems to be an issue with a custom PDF.js implementation, please provide access to a *working* example online, since just code snippets are not particularly helpful.

**Comment by sanzmiguel** [comment]
I send you the pdf file. I checked with other pdf file and I have the same problem. I only call the function since index.html and put it on a canvas tag.

I have one warning in the console of Javascript:

(pdf.worker.js:2317 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.)

Also, I have one error in the console of Javascript:

(pdf.worker.js:274 Uncaught Error: Unknown action from worker: configure)

Thank you.




[ficha.pdf](https://github.com/mozilla/pdf.js/files/227792/ficha.pdf)

**Comment by Snuffleupagus** [comment]
WFM, when I open the PDF file with the latest version (`1.4.258`) of PDF.js: http://mozilla.github.io/pdf.js/web/viewer.html.

> I checked with other pdf file and I have the same problem.

This would indicate that it's an issue with your custom implementation of PDF.js, so as mentioned in https://github.com/mozilla/pdf.js/issues/7225#issuecomment-212373874, the only way for anyone to be able to provide help here is if you follow this piece of advice:

> Also, since this seems to be an issue with a custom PDF.js implementation, please provide access to a working example online, since just code snippets are not particularly helpful.

**Comment by sanzmiguel** [comment]
I provide you a link to a GitHub repository:
https://github.com/sanzmiguel/pdfConverter

However, I tried to print this canvas tag with a thermal printer and the text is correctly printed. The text only isn´t printed in the browser. I checked it in Google Chrome and Mozilla Firefox.

Thank you.

**Comment by sanzmiguel** [comment]
The problem is solved. Just, I changed the stable version for the beta version and it´s working now.

Thank you for your help.

**Comment by SamyCookie** [comment]
@sanzmiguel Good to know. If this is OK for you, don't forget to close the issue ;)
