### ISSUE TITLE
Textlayer is not correctly on top

### ISSUE THREAD

**Issue by mangei** [mozilla/pdf.js#7226]
## Link to PDF file (or attach file here):

[testdocument.pdf](https://github.com/mozilla/pdf.js/files/227533/testdocument.pdf)
## Configuration:
- Web browser and its version: Firefox 45.0.2, Chrome  49.0.2623
- Operating system and its version: Microsoft Windows 10
- PDF.js version: 1.4.175
- Is an extension: usage as a library in a web application or normal viewer in Firefox
## Steps to reproduce the problem:
1. Open Document (see attached testdocument.pdf)
2. Select a paragraph
## What is the expected behavior? (add screenshot)

The text should be correctly on top, such that e.g. selecting works fine.

**Adobe Acrobat Reader DC**
![2016-04-20 103451](https://cloud.githubusercontent.com/assets/1218033/14668660/ae737170-06e5-11e6-9b14-412fcbc2b723.png)
## What went wrong? (add screenshot)

The text overlay is not correctly positioned and scaled.

**PDF.js in Firefox**
![2016-04-20 103326](https://cloud.githubusercontent.com/assets/1218033/14668671/bc64d710-06e5-11e6-8dc3-0eb1601274ed.png)

**Web application**
![2016-04-20 104803](https://cloud.githubusercontent.com/assets/1218033/14668658/aa95abcc-06e5-11e6-9e58-66576630c4c5.png)

**Comment by mangei** [comment]
related to #5558, #5387, #3713

**Comment by timvandermeij** [comment]
The text layer alignment got fixed by #12896 and other work, but the lines are still too short.

**Comment by timvandermeij** [comment]
Fixed by #13257.
