### ISSUE TITLE
messy code with Chinese pdf file

### ISSUE THREAD

**Issue by fisher030712** [mozilla/pdf.js#7228]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 47, IE 11
- Operating system and its version: win7 64, zh_CN
- PDF.js version:ch 1.3.91
- Is an extension:

Steps to reproduce the problem:
1. open the pdf file.
I can't upload the pdf file, can you send me a email, and i will reply and send you the pdf file.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by fisher030712** [comment]
my email: fisher030712@hotmail.com

**Comment by yurydelendik** [comment]
Closing as incomplete

**Comment by fisher030712** [comment]
Hi, this is a Chinese PDF file, when i open it with pdf.js 1.3.91, it's messy code.


Thank you very much, if any suggestion, please let me know.


________________________________
发件人: Yury Delendik <notifications@github.com>
发送时间: 2016年4月21日 19:28
收件人: mozilla/pdf.js
抄送: fisher030712; Author
主题: Re: [mozilla/pdf.js] messy code with Chinese pdf file (#7228)


Closing as incomplete

―

**Comment by timvandermeij** [comment]
You cannot attach PDF files via GitHub's e-mail system. You should instead login on GitHub and upload the PDF using the comment field.
