### ISSUE TITLE
PDF rendering error: bad XRef entry

### ISSUE THREAD

**Issue by hanky** [mozilla/pdf.js#7229]
Hello,

I have problems with rendering of the attached PDF file. When I open it using the official viewer at http://mozilla.github.io/pdf.js/web/viewer.html I get the following error:

```
PDF.js v1.4.258 (build: 990150c)
Message: bad XRef entry
```

I know that there were lots of similar issues with bad xref entry, and they were mostly caused by corrupted PDFs, but my pdf still can be opened using other applications. So, I hope somebody will adderss this issue.

P.S. Thank you for a great tool.

[bad_xref.pdf](https://github.com/mozilla/pdf.js/files/229487/bad_xref.pdf)

**Comment by Snuffleupagus** [comment]
@hanky Are you the creator of the PDF file, and if so may we include it in the test-suite?

**Comment by hanky** [comment]
Yes, you may include it.

**Comment by HeggyChan** [comment]
@hanky how did you resovle it? i upgrade the latest one from offical web, which is v2.9.359, the problem still exist
