### ISSUE TITLE
searching is selecting the context next to the exact word

### ISSUE THREAD

**Issue by SaranrajR** [mozilla/pdf.js#7230]
Here, i have attached the PDF, that PDF document contains "Nudi" as an embedded font. When i searching the particular word (that in Nudi font), the search result selecting the word that context next to the exact word.

Link to PDF file (or attach file here):
[sample_pdf.zip](https://github.com/mozilla/pdf.js/files/229582/sample_pdf.zip)

Configuration:
- Web browser and its version: Mozilla 45.0.2
- Operating system and its version: Windows 7
- PDF.js version: 1.4.20-disc

What is the expected behavior? (add screenshot)
![find_01](https://cloud.githubusercontent.com/assets/17423938/14704922/c2e67f2c-07d4-11e6-9320-9aed2578d377.png)

**Comment by Snuffleupagus** [comment]
Fixed by #12855
