### ISSUE TITLE
Weird for loop in bidi.js

### ISSUE THREAD

**Issue by xiemaisi** [mozilla/pdf.js#7231]
[This](https://github.com/mozilla/pdf.js/blob/990150ce615d76257d4bcbc5a1d7f853ef3fd0da/src/core/bidi.js#L255) looks wrong:

```javascript
for (j = i + 1; j < strLength; --j) {
  ...
}
```

Note that the loop counter is decremented, but checked with `<`. I assume it should be incremented instead?

**Comment by timvandermeij** [comment]
You're right, this looks wrong. I wonder if this causes any text selection bugs. Thank you for reporting this, we'll look into it!

**Comment by Snuffleupagus** [comment]
That looks very much like a copy-and-paste error, and interestingly it has looked the same way ever since PR #1218 which first introduced the code.
Unfortunately I don't think we have very good, if any, test coverage for that particular part of `bidi.js`.

**Comment by timvandermeij** [comment]
It would be nice if we can come up with a test PDF (either create one or find one) that causes this `for` loop to be used.

**Comment by yurydelendik** [comment]
@xiemaisi just to get some background, was the issue found using some analyzer or by just studying the code. If the former, does this tool evolve and using PDF.js as the test case periodically? We might need to mark those issue by special label then.

**Comment by xiemaisi** [comment]
@yurydelendik this issue (as well as #7232 and #5227) were indeed found by our analyzer, which is currently still in stealth mode (in fact it's so stealthy it doesn't even have an official name yet ;-). We're hoping to go live at the end of June, at which point we'd be happy to tag these issues. In the meantime, if you feel they are useful we can keep filing issues we find as we're improving our analysis.

**Comment by yurydelendik** [comment]
Thanks. They are useful and keep then coming. We can mark them somehow, just inform that they were found via static analysis.

If the tool running periodically I'm not that concern in unit tests to cover for single typo, unit tests better if they cover entire unit functionality (in this case bidi)

**Comment by yurydelendik** [comment]
Closed in favor of #7261
