### ISSUE TITLE
Change the scale factor when clicking on the + button?

### ISSUE THREAD

**Issue by Manmade** [mozilla/pdf.js#7238]
How do I change how much the pdf is scaled up when you zoom in with the + button?
Thanks a lot!

**Comment by Snuffleupagus** [comment]
You will need to modify `DEFAULT_SCALE_DELTA`, see https://github.com/mozilla/pdf.js/blob/4aac324558829e26020c0fa4d56efb37b8599ad5/web/app.js#L102 and https://github.com/mozilla/pdf.js/blob/4aac324558829e26020c0fa4d56efb37b8599ad5/web/app.js#L343-L351.

Closing as answered.

**Comment by Manmade** [comment]
Ok, great. Thanks a lot Jonas!
  ----- Original Message -----
