### ISSUE TITLE
PDF Viewer links off by one page in PDF js

### ISSUE THREAD

**Issue by santhoshcd** [mozilla/pdf.js#7243]
Hi 
I am using Object tag of html to display the PDF file in HTML page.
When i clicks on Page number link it is displaying the incorrect page of pdf file in PDF.js. It is expected that clicking the links will move to the correct page in the PDF, however the pages seem to be offset by 1 page.

Which is working fine when i open same pdf file in firefox with pdf.js(sample.pdf#page=3 or sample.pdf#page=4) by changing page number manually.
Even in Adobe reader(chrome) also working fine.

I checked [3076](https://github.com/mozilla/pdf.js/pull/3193) issue but i did not get any solution. They are telling there is a problem in PDF file, if there is a problem then how Same pdf file is working fine in Abode reader and firefox with PDF.js(sample.pdf#page=3 or sample.pdf#page=4).

Please give me solution for this.

Configuration:
- FIreFox:
- PDF.js

**Comment by Snuffleupagus** [comment]
Closing as incomplete, please provide the necessary information to re-open.
Please read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, and make sure to follow https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when filing an issue.
