### ISSUE TITLE
current pdf.js development version fails to load on SeaMonkey 2.40 and Firefox ESR 38.8.0

### ISSUE THREAD

**Issue by JohnDDuncanIII** [mozilla/pdf.js#7245]
Link to PDF file (or attach file here): http://harpers.org/wp-content/uploads/2008/09/HarpersMagazine-1996-01-0007859.pdf

Configuration:
- Web browser and its version: SeaMonkey 2.40
- Operating system and its version: OS X 10.11.3
- PDF.js version: 1.5.201
- Is an extension: Yes

When attempting to load any pdf file, the page will stop loading (it is just blank). The error console shows: 
```Error: NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN: Cannot modify properties of a WrappedNative
Source File: jar:file:///Users/John/Library/Application%20Support/SeaMonkey/Profiles/SeaMonkey.default/extensions/viewer@pdf.js.xpi!/content/PdfStreamConverter.jsm
Line: 1069```
every time.

Steps to reproduce the problem:
1. Install the [current pdf.js development version in SeaMonkey 2.40](http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi) 
2. try to open a pdf file
the page will fail to load and give the above error

What is the expected behavior? (add screenshot)
display the pdf

What went wrong? (add screenshot)
it failed
![screen shot 2016-04-24 at 9 35 19 pm](https://cloud.githubusercontent.com/assets/9257785/14771869/76ffaf6a-0a64-11e6-9d0f-268891b22228.png)


Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

note: all other development versions of this add-on have worked for me so far. I decided to try to update it tonight and it immediately stopped working after the update.

**Comment by JohnDDuncanIII** [comment]
I cannot find old .xpi's of the development version (and don't want to install node stuff on this computer for builds), so I have [simply reverted back to pdf.js 1.4.124](http://web.archive.org/web/20160304190638/http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi) which works fine on SM 2.40.

**Comment by yurydelendik** [comment]
Can you bisect and find the exact commit that caused the issue?

**Comment by JohnDDuncanIII** [comment]
I am not absolutely positive, but I believe the most recent commit that modifies this file is the culprit: https://github.com/mozilla/pdf.js/commit/867a5ea1b00f1bc5f58a1b5edc29f87ebe348527

**Comment by JohnDDuncanIII** [comment]
update: I am forced to use Firefox ESR 38.8.0 at my FFRDC (so no pdf.js built in). I am running into the exact same issue as previously reported with the most current dev build:
(NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN: Cannot modify properties of a WrappedNative PdfStreamConverter.jsm:1069:0). 

The older development version (from web.archive.org, as I linked above) works fine. It seems as if the commit I mentioned in my previous post is the problem (a pretty large problem imo). In the mean time, I am just using an older version. Thanks.

**Comment by ljb279** [comment]
Are you sure about Firefox? I have the same pdf.js problem as you on Seamonkey-2.40, but my Firefox ESR-38.8.0 does include built-in PDF viewing, and it does work. I'm using Slackware Linux, which includes both the Seamonkey and Firefox packages.

**Comment by JohnDDuncanIII** [comment]
Perhaps it's something that was disabled at compile-time by our sysadmins, but I can confirm that installing the current dev version as an add-on in ESR-38.8.0 leads to the same issue as on SM 2.40.
