### ISSUE TITLE
How updatable is PDF.js using a custom viewer?

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7248]
Using a totally customized Viewer, how updatable is the Core and Display Layer over the next years?

Will it still work in the future when replacing all files, except for viewer.js? Or may function names and logic change?

(This may also a good FAQ)

**Comment by yurydelendik** [comment]
> Using a totally customized Viewer, how updatable is the Core and Display Layer over the next years?

We are trying to keep every API we create compatible with 1.0, or at least we are not trying to break or remove on purpose. We will trying to fix regression if needed. (With 2.0 we are planning to remove global `PDFJS` support -- no timeline on this.) See also http://semver.org/ -- we did not explicitly said we are doing it, but that's what we do.

> Will it still work in the future when replacing all files, except for viewer.js? 

We had reports that people replaced pdf.js/pdf.worker.js files for older viewer with success. But we always recommend to update core library and viewer.

> Or may function names and logic change?

For 1.x we are not planning to remove/change names. Logic is can be altered if some global variable dependency is used (trying to remove dependency on global state).

Closing as answered.

**Comment by yurydelendik** [comment]
Updated https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#version

**Comment by yurydelendik** [comment]
> We had reports that people replaced pdf.js/pdf.worker.js files for older viewer with success. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1247266

> But we always recommend to update core library and viewer.

Here is the case why #6916
