### ISSUE TITLE
pdfjs Viewer - hiding a page

### ISSUE THREAD

**Issue by fryaniv** [mozilla/pdf.js#7252]
Hi,

Is there an API way to hide a page or several pages within a pdf document using pdfjs viewer? For example, suppose Iv'e loaded in the pdfjs Viewer a 15 pages pdf document - is there a command to hide pages 2,3 and 6 of this document?

Trying to hide page 4 for example in http://mozilla.github.io/pdf.js/web/viewer.html by using document.getElementById("pageContainer4").style.display = "none" seems to be buggy as when I scroll fast down and up - page 3 is only white and stuck with the spinner.

Thanks,
Yaniv

**Comment by yurydelendik** [comment]
No, there is no an API with such functionality. The viewer can be modified, and it looks like you are doing the right thing. The use case you are mentioning in out of scope of this project, so there is no plans to add it to the demo viewer. Closing issue as answered.

**Comment by yurydelendik** [comment]
> using document.getElementById("pageContainer4").style.display = "none" seems to be buggy as when I scroll fast down and up - page 3 is only white and stuck with the spinner.

WFM
