### ISSUE TITLE
upper and bottom part of each "code" line is missing

### ISSUE THREAD

**Issue by SR-gh** [mozilla/pdf.js#7253]
Link to PDF file (or attach file here):
https://www.qtdeveloperdays.com/sites/default/files/BogdanVatra_Extending_Qt_Android_Apps_with_JNI.pdf

Configuration:
- Web browser and its version: Firefox 45.0.2
- Operating system and its version: Windows 7 SP 1
- PDF.js version:
- Is an extension: no

Steps to reproduce the problem:
1. Open the link to the PDF in Firefox
2. Go to page 7
3. Observe that the code text is not correctly rendered : upper and bottom part of each line is missing.
![codemalformed-leftpdf js-rightadobeacrobatreader](https://cloud.githubusercontent.com/assets/15922893/14826691/52e85cfe-0bdf-11e6-8dce-d1ff564c53e9.png)

What is the expected behavior? (add screenshot)
What went wrong? (add screenshot)
The attached screen shows the rendered file through PDF.js on the left and Acrobat Reader on the right.
The right one is easy to read. The left one is hard to read because it is not correctly rendered.

Remarks :
-colours are not the same (green banner for instance). I don't know if it's a bug, I report no issue about it.
-distance between the green banner and the top of the page is different between the two renderers. I don't know if it's a bug, I report no issue about it.

**Comment by yurydelendik** [comment]
Looks good on Mac OS:

<img width="1296" alt="screen shot 2016-04-26 at 12 50 52 pm" src="https://cloud.githubusercontent.com/assets/1523410/14828687/ab10ea9a-0bad-11e6-9ab8-44c5f9292a76.png">

Maybe differences in OS font engines.

**Comment by timvandermeij** [comment]
Looks good on Arch Linux too.

**Comment by SR-gh** [comment]
For completeness sake, after creating pdfjs.verbosity_levels=info through about:config :
PDF 6579a1a668ec734bb41757759e3e755d [1.4 Qt 5.3.2 / -] (PDF.js: 1.3.76) viewer.js:6862:1
downloadable font: OS/2: adjusting Mac style (regular) (font-family: "g_d0_f3" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64, <snipped data>
downloadable font: OS/2: adjusting Mac style (regular) (font-family: "g_d0_f4" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64, <snipped data>

**Comment by timvandermeij** [comment]
I'm getting this in the console too. I'm guessing Windows cannot handle this as well as Linux/OS X. Marking as Windows-specific for now.

**Comment by timvandermeij** [comment]
Closing since the file is no longer available and recently similar issues have been marked as resolved.
