### ISSUE TITLE
Android webView find word

### ISSUE THREAD

**Issue by jamesvanhallen** [mozilla/pdf.js#7257]
Link to PDF file (or attach file here
[pdf.pdf](https://github.com/mozilla/pdf.js/files/238348/pdf.pdf)
):

Configuration:
- Web browser and its version: Android crosswalk (alternative webView)
- Operating system and its version: Android 4+
- PDF.js version: PDFJS.version = '1.0.277';
- Is an extension:

Steps to reproduce the problem:
1. html: http://pastebin.com/
2. js function in customview.js: http://pastebin.com/LahFUmTe
3. call searchPDF from java code: webView.load("javascript:searchPDF(\"" + query + "\")", null);

What is the expected behavior? (add screenshot)
 find and highlight search text
What went wrong? (add screenshot)
 "Uncaught ReferenceError: PDFView is not defined", source: file:///android_asset/pdf/pdfviewer/customview.js (104)

Can you show tutorial for searching in pdf file with pdf.js?

**Comment by timvandermeij** [comment]
You are using a very old version of PDF.js. We recently updated our examples and code to make the find controller available for other viewers: see https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js. You will need to use the latest master code for that though, so it's recommended to use the NPM or Bower package.

Closing as answered.

**Comment by jamesvanhallen** [comment]
`  PDFJS.getDocument(url).then(function (pdfDoc_) {
             pdfDoc = pdfDoc_;
           // document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
    });`
Error: "Uncaught TypeError: undefined is not a function"
With latest pdf.js
