### ISSUE TITLE
Can we pass the parameters in request body instead of request URL?

### ISSUE THREAD

**Issue by priyankac90** [mozilla/pdf.js#7259]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. We are passing document name in the $scope.pdfUrl . This is causing a security issue as it is visible in URL.
2. Security issue states that sensitive information passed in URL
3. We also have changed the request to POST method 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
We don't have `$scope.pdfUrl` anywhere is our code base. The issue you are reporting is unrelated to the PDF.js. Closing as invalid.

If you are sure you are reporting the issue with PDF.js, please prepare complete example online and provide as link. Also provide all information (about browser, OS, etc) in the form above
