### ISSUE TITLE
Add smoke tests for all core/ files

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#7261]
(Based on #7231) and blocked by #7179

We have some files (in the core/) without any unit tests. It will be nice to add some elementary tests to check if we are not breaking anything:
- [x] bidi.js
- [ ] colorspace.js
- [x] unicode.js
- [x] murmurhash3.js
- [x] cff_parser.js
- [x] type1_parser.js

**Comment by pablofiumara** [comment]
@yurydelendik Do the check mark on the left of file names means the unit test for that file have already been written?

**Comment by timvandermeij** [comment]
Yes, only the ones without a checkmark still require tests.

**Comment by pablofiumara** [comment]
@timvandermeij  Thanks for answering. Could you confirm that murmurhash2.js was renamed to murmurhash3.js and that murmurhash3.js needs unit tests to be written, please?

**Comment by yurydelendik** [comment]
" murmurhash2.js " was typo -- fixed
