### ISSUE TITLE
emoji appear in rendered pdf, but not cached file, reload of the same pdf removes the emoji

### ISSUE THREAD

**Issue by jfspencer** [mozilla/pdf.js#7264]
Link to PDF file (or attach file here):
[F3AADD7D-D9F2-411A-8077-F290AC069FE2.pdf](https://github.com/mozilla/pdf.js/files/240609/F3AADD7D-D9F2-411A-8077-F290AC069FE2.pdf)

Configuration:
- Web browser and its version: iOS 9 Safari Webview, Ionic Framework
- Operating system and its version: iOS 9
- PDF.js version: 1.4.20
- Is an extension: no

Steps to reproduce the problem:
1. load the pdf
2. once loaded emoji appear in various places in the pdf, see "What went wrong"
3. zooming in or out or reloading the pdf removes the emoji, see "What is expected"

What is the expected behavior? (add screenshot)
![screen shot 2016-04-28 at 7 51 54 am](https://cloud.githubusercontent.com/assets/6029517/14888171/2d42c60a-0d16-11e6-9c5d-870919d04d56.png)

What went wrong? (add screenshot)
![screen shot 2016-04-28 at 7 49 04 am](https://cloud.githubusercontent.com/assets/6029517/14888139/0c317a9c-0d16-11e6-8814-6beb2b61b617.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
none

**Comment by lamaslam** [comment]
Same problem here. on iOS 9

**Comment by Snuffleupagus** [comment]
Given that this issue is very old, and that everything points to it being a platform/browser bug (rather than a general PDF.js one), is it actually meaningful to keep this open?
