### ISSUE TITLE
Search jumps the page in IE

### ISSUE THREAD

**Issue by sharanmunyal** [mozilla/pdf.js#7269]
Link to PDF file (or attach file here):
http://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 7
- PDF.js version: 1.5.214
- Is an extension: No

Steps to reproduce the problem:
1. Search for 'the' in the link provided above. 
2. Do next repeatedly and you should see the page jumping up before it shows the highligted result

What is the expected behavior? (add screenshot)
It should not jump like other browsers (Chrome, Firefox and Safari)

What went wrong? (add screenshot)
Page jumps when you scroll

**Comment by Snuffleupagus** [comment]
> What is the expected behavior? (add screenshot)
> It should not jump like other browsers (Chrome, Firefox and Safari)
> 
> What went wrong? (add screenshot)
> Page jumps when you scroll

This effect is actually, technically, present in *all* browsers, it's just that with the usual exception of IE 11 every other browser is fast enough that it's completely imperceivable. The explanation is that the current page is *always* being re-scrolled into view, when a match has been found, regardless if it's necessary or not; see https://github.com/mozilla/pdf.js/blob/81f5835cd7024827e0671ccd66525df98fb15703/web/pdf_find_controller.js#L473-L478

Most likely this issue could be somewhat easily fixed, perhaps [along these lines](https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:less-scrolling-updatePage), but I'm just not sure if you want to bother with it!?

**Comment by timvandermeij** [comment]
I would say we close this as won't-fix since it's not really a problem in modern browsers.
