### ISSUE TITLE
Failed to load resource: cancelled

### ISSUE THREAD

**Issue by nazarhussain** [mozilla/pdf.js#7271]
Configuration:
- Safari Version 9.1 (11601.5.17.1)
- Mac OSX 10.11.4 (15E65)
- v1.5.188 

Steps to reproduce the problem:
1. Open up a protected page which have pdf js viewer.html loading in iframe
2. The iframe had a parameter viewer.html?file=FILE_URL
3. The FILE_URL is actually a protected URL which make a 302 redirect to a S3 bucket object 
4. Loading would failed (cancelled) from the client side

What is the expected behavior? (add screenshot)
It must open the pdf page for which url came after redirect. 

It is working fine on Chrome, Firefox only the Safari on Mac and iOS is effecting with this problem.

**Comment by yurydelendik** [comment]
Most likely it's a bug in Safari, but it's hard to tell without reproducing it. The PDF.js is using browser's XHR to get the data, so there is a way to reduce it to the simple test case without PDF.js logic. Would you like to publish small example to reproduce the issue on different computer (or close it as incomplete)?

**Comment by nazarhussain** [comment]
I had figured out the first issue of cancelation but came across another. 

```
https://api.caremerge.us/pdfViewer/web/viewer.html?file=https://api.caremerge.us/social/editors/download/pdf-sample.pdf
```
Please check the link above, it works pretty fine in Chrome and Firefox. But in Safari it shows Error.

```
Failed to load resource: Cannot make any requests from null.
```

Please suggest what could be wrong?

**Comment by yurydelendik** [comment]
This is not related to the PDF.js functionality: try to execute the following in the https://api.caremerge.us/pdfViewer/web/viewer.html?file=https://api.caremerge.us/social/editors/download/pdf-sample.pdf
 context:

```
var xhr = new XMLHttpRequest(); 
xhr.open('GET', 'https://api.caremerge.us/social/editors/download/pdf-sample.pdf'); 
xhr.responseType = 'arraybuffer'; 
xhr.onload = function () { alert(xhr.status); }; 
xhr.onerror = function () { alert('Error!'); };
xhr.send();
```

Only Safari fails:

<img width="932" alt="screen shot 2016-05-02 at 12 57 27 pm" src="https://cloud.githubusercontent.com/assets/1523410/14962653/8c35363c-1065-11e6-945a-90f868731a32.png">

PDF.js is using browser's XHR and there is nothing we can do to bypass the browser's restrictions. Please contact the vendor of the browser to troubleshot the issue with your S3 bucket and Safari.

**Comment by yurydelendik** [comment]
The workaround will be to get binary directly from S3 bucket (via its APIs) and pass it to the PDF.js as Uint8Array to open. In this case memory consumption might increase and you may loose progressive loading of the PDF data (so it's better limit that to the Safari only). Closing as answered.

**Comment by nazarhussain** [comment]
@yurydelendik Thanks for the workaround. That would be an immediate solution at the moment.
