### ISSUE TITLE
"TypeError: pageView is undefined" during pdf.js tests

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#7274]
Noticed when looking at Treeherder logs.
http://archive.mozilla.org/pub/firefox/try-builds/ryanvm@gmail.com-bfecb53c1626b14dab001068ddfe3fd686854802/try-linux64/try_ubuntu64_vm_test-mochitest-e10s-browser-chrome-1-bm54-tests1-linux64-build223.txt.gz

INFO -  JavaScript error: resource://pdf.js/web/viewer.js, line 8148: TypeError: pageView is undefined

**Comment by yurydelendik** [comment]
Points to https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1589 in the webViewerTextLayerRendered. I suspect that we destroy viewer but still continue rendering of the text layers.

**Comment by yurydelendik** [comment]
Indeed that is the case. We shall discontinue this event and other renderings if viewer is closed.
