### ISSUE TITLE
pdf.js Bug?

### ISSUE THREAD

**Issue by oranger** [mozilla/pdf.js#7283]
Lin[k to PDF file (or attach file here):]
[1237-W-15th-1-2-Street289025.pdf](https://github.com/mozilla/pdf.js/files/246241/1237-W-15th-1-2-Street289025.pdf)

This pdf display in pdf.js is wrong, also in firefox browser.

**Comment by Snuffleupagus** [comment]
The PDF file uses layers, which we currently don't support.
Closing as duplicate of issue #269 (and others).
