### ISSUE TITLE
HandTool mode of Viewer inside iFrame Does not work correctly

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7284]
I tried to load pdf.js inside an iFrame and there is an issue when enabling hand tool mode.

When I drag it and the mouseup ends up outside the iFrame, and when i move the mouse cursor back inside the iFrame, it ends up being in dragged mode.

Is there a way to programmatically set the hand tool drag event as finished when the mouse cursor ends up outside the iFrame.

**Comment by Rob--W** [comment]
Thanks for the report, I created a new ticket at https://github.com/Rob--W/grab-to-pan.js/issues/4
