### ISSUE TITLE
pagechange event fires two times when user changes page

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#7288]
Link to PDF file (or attach file here):
Base file at https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome 50
- Operating system and its version: Mac OSX 10.10.5
- PDF.js version: 1.5.230
- Is an extension: No

Steps to reproduce the problem:
1. Open devtools and add a breakpoint in viewer.js (currently line 2741):
```
eventBus.on('pagechange', function (e) {
  var event = document.createEvent('UIEvents'); // <-- Add breakpoint here
  event.initUIEvent('pagechange', true, true, window, 0);
  event.updateInProgress = e.updateInProgress;
  event.pageNumber = e.pageNumber;
  event.previousPageNumber = e.previousPageNumber;
  e.source.container.dispatchEvent(event);
});
```

2. Change page number using toolbar, say to page 2 of 14.
3. See that breakpoint is triggered twice

What is the expected behavior? (add screenshot)
'pagechange' event should be fired only once

What went wrong? (add screenshot)
'pagechange' event is fired twice, once from the setting of currentPageNumber, and another when the screen updates.
1st time: http://screencast.com/t/kdjojgK0cC
2nd time: http://screencast.com/t/9ssbszRNQ

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by yurydelendik** [comment]
@tonyjin, looks like it's not a regression, right?

**Comment by tonyjin** [comment]
Agreed, looks like this has been happening for a while.

**Comment by yurydelendik** [comment]
I think we can safely assume that people don't want previousPageNumber==pageNumber event. Can we break this behavior for everyone?

**Comment by brendandahl** [comment]
> I think we can safely assume that people don't want previousPageNumber==pageNumber event. Can we break this behavior for everyone?

SGTM

**Comment by G1King** [comment]
PDF 32b8b4b630401348e21c91fb96935fb3 [1.7 secPdfProducer / Scan Assistant] (PDF.js: 2.0.950)
Use the viewer's page   Outside calls   PDFViewerApplication.page = 3
and  pagechange handler two times 
![image](https://user-images.githubusercontent.com/21077737/200462856-4cdada22-8dcb-4d2b-baf9-d92922a155e1.png)

**Comment by G1King** [comment]
iframe element src ： /generic/web/viewer.html?file='xxxx'#page=1#zoom=100
   Call to order  PDFViewerApplication.page and  url params 
   I'm not going to call back twice when I remove the argument（#page） to the url
   I look forward to your reply. Thank you
