### ISSUE TITLE
Is it possible to use it for online pdf's

### ISSUE THREAD

**Issue by rajagopal231** [mozilla/pdf.js#7293]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Android WebView
- Operating system and its version: Any android
- PDF.js version:latest
- Is an extension:no

Steps to reproduce the problem:
1. I want to use PDF.JS for viewing the online PDF files as android does not support directly opening the pdf in the browser.
2.I am able to open the local PDF document using the viewer, but i wanted to know how to use this to view online pdf documents.
3. please provide me a way to do this.

What is the expected behavior? (add screenshot)
should open online PDF documents.
What went wrong? (add screenshot)
nothing wrong
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
There is no viewer for Android, but since it's tracked in #6136, I'm closing this issue as a duplicate.
