### ISSUE TITLE
PDFs with Chinese characters not displaying correctly with PDF.js while displaying OK in Acrobat Reader, Chrome and IE

### ISSUE THREAD

**Issue by PSWMartin** [mozilla/pdf.js#7308]
Link to PDF file (or attach file here):
[ZGTA198001028.pdf](https://github.com/mozilla/pdf.js/files/256692/ZGTA198001028.pdf)

Configuration:
- Web browser and its version:
  Firefox 46.0.1
- Operating system and its version:
  Windows 7 Ultimate (Service Pack 1)
- PDF.js version:
  Not sure, built-in to my version of Firefox

Steps to reproduce the problem:
1. Open the file in the PDF.js viewer: The file does not open (the loading icon is perpetually displayed)

What is the expected behavior? 
PDF in Chrome
![pdfinchrome](https://cloud.githubusercontent.com/assets/19281948/15140203/541a0dbe-169a-11e6-8e52-ac10df667c52.PNG)

What went wrong? (add screenshot)
PDF in Firefox
![pdfinfirefox](https://cloud.githubusercontent.com/assets/19281948/15140214/5edfa484-169a-11e6-9ea8-bbd87dce10b9.PNG)

**Comment by timvandermeij** [comment]
The JBIG2 decoder gets into a huge loop at https://github.com/mozilla/pdf.js/blob/master/src/core/jbig2.js#L374, where it gets the number 1499701222 as height. It gets this number from https://github.com/mozilla/pdf.js/blob/master/src/core/jbig2.js#L548, so I suspect we're not in the correct part of the stream when we attempt to read this integer.
