### ISSUE TITLE
Add phone-home to Chrome extension

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#7312]
In order to clean up the extension code without breaking functionality of users who aren't using the latest version of Chrome/Chromium, I need to know which versions they are using. So I will submit a PR with an opt-out phone-home feature.

The following anonymous data will be logged:

- User agent string (browser version, OS)
- Server time.
- Some randomly generated string that is created on the first run - used to deduplicate events.

To-do:

- [x] Create privacy policy that explains that the above data is collected.
- [x] Logging backend (can be as simple as access log)
- [x] Add phone-home to extension.
- [x] Add preference to disable phone-home.

**Comment by timvandermeij** [comment]
I'm wondering if the variance in version numbers will be large or not. As far as I know Chrome has a pretty strict update policy, so unless you're using an ESR version, I would assume that most users are using the latest version or some version really close to that. Do you have reasons to believe that people are still using over one year old Chrome versions (like 35 for instance)?

I think you're referring to https://github.com/mozilla/pdf.js/blob/master/extensions/chromium/feature-detect.js that you would like to remove. Both features were implemented in Chrome 35, so now that we are at version 50, I would say that it's safe to remove those feature tests, unless you are concerned that a lot of people may still be using it, of course.

**Comment by Rob--W** [comment]
@timvandermeij I expect the majority of the users to be at the latest version, and running ancient versions of Chrome is very stupid (because of security vulnerabilities). However, given the lot of users, I expect that it is not unlikely to have at least a few thousand users who are still using an old Chrome version.

My immediate need is indeed determining whether it's safe to drop support for Chrome 35, but the statistics can also be useful in determining whether it's safe to use newer Chrome APIs that are backwards-incompatible. For instance, the [declarativeWebRequest API](https://developer.chrome.com/extensions/declarativeWebRequest) allows for a more efficient use of system resources. Currently it is only available on non-stable Chrome releases. If it becomes available for stable, then I can use [event pages](https://developer.chrome.com/extensions/event_pages) instead of background pages. But event pages cannot be used with the [webRequest API](https://developer.chrome.com/extensions/webRequest), so I cannot switch until I know that it won't affect users.

In either way, there are too many users that depend on the extension, so I want to make informed decisions (based on real data) instead of an unfounded estimate.

**Comment by timvandermeij** [comment]
Sounds good to me! Thank you for the additional information.

**Comment by timvandermeij** [comment]
Fixed by #7370.
