### ISSUE TITLE
Text layer overlays not exactly

### ISSUE THREAD

**Issue by hypergod** [mozilla/pdf.js#7320]
Link to PDF file (or attach file here):
[page3.pdf](https://github.com/mozilla/pdf.js/files/260845/page3.pdf)

Configuration:
- Web browser and its version: IE 11, Chrome 50
- Operating system and its version: Windows 7
- PDF.js version: 1.5
- Is an extension: No

Steps to reproduce the problem:
1. Open page3.pdf with viewer.html
2. Select text: "application mainly"

What is the expected behavior? (add screenshot)
Text layer matches exactly with rendered text.

What went wrong? (add screenshot)
![text_layer_missmatch](https://cloud.githubusercontent.com/assets/1008864/15208326/3332deae-182b-11e6-8bd7-2dca39a3955d.png)

Text layer overlays not exactly. A little bit too far up and too far ahead in the middle of text line.

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.
