### ISSUE TITLE
Ability to support tags just like in Acrobat

### ISSUE THREAD

**Issue by weboracle** [mozilla/pdf.js#7321]
Link to PDF file (or attach file here):
https://storage.googleapis.com/pdf-test/test.pdf

Configuration:
- Web browser and its version: Firefox 45.0.2
- Operating system and its version: Windows 7
- PDF.js version: latest built into the Firefox 45.0.2
- Is an extension: part of default firefox install

Steps to reproduce the problem:
Open the following url
https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-2

in 
Internet Explorer 9/10/11 (Environment: Adobe Acrobat installed + Window 7; if you don't have this configuration you can obtain the VM here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/

What is the expected behavior? (add screenshot)
This URL 
https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-2
should bring you to 
page 2  and highlight the word 'adipiscing'

![expected-pdf-page-2](https://cloud.githubusercontent.com/assets/4527785/15216009/2df7fa26-1823-11e6-9ba5-34ade8a0e208.jpg)

Additional Tags in this document
Tag-1 => page 1 (475,512,690,681) 'morbi'

https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-1

Tag-2 => page 2 (430,472,685,672) 'adipiscing'

https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-2

Tag-3 => page 3 (475,472,690,679) 'commodo'

https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-3

Tag-4 => page 4 (475,543,678,668) 'viverra' 

https://storage.googleapis.com/pdf-test/test.pdf?calcrtid=Tag-4

What went wrong? (add screenshot)

user sees page 1 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Additional information:

Also here is the content of the (simplified) OpenAction script:

this.disclosed = true;
this.syncAnnotScan();
var u = this.URL;
var args = u.split('calcrtid=');
var tags;
if ( args.length > 1 ) {
    tags = args[1].split('&');
    this.gotoNamedDest(tags[0]);
    var a = this.getAnnot( this.pageNum, tags[0] );
    var hilite = ( u.indexOf( 'hilite=true' ) == -1 ) ? 0 : 1;
    if ( hilite ) {
        var selected = '';
        if ( a != null ) {
            selected = a.name;
        }
        var list = this.getAnnots();
        for ( var ix = 0; ix < list.length; ++ix ) {
            var ann = list[ ix ];
            if ( ann.type == 'Highlight' ) {
                var nm = ann.name;
                ann.hidden = false;
                if ( nm == selected ) {
                    ann.contents = nm + ' (SELECTED)';
                } else {
                    ann.contents = nm;
                }
            }
        }
    }
    if ( a != null ) {
        a.hidden = false;
        var rect = a.rect;
        if ( rect != null ) {
            this.scroll( rect[ 2 ] + 100, rect[ 3 ] + 100 );
        }
    }
    this.closeDoc(true);
 }

This functionality is very important for many users in my case more than 250,000+.  Thank you

**Comment by yurydelendik** [comment]
None this work for any other PDF viewers (Chrome, Safari, Preview) except probably Adobe Reader. Marking as a feature to support embedded scripts. 

P.S. Personally I disable any JavaScript in the Reader for security reasons.

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here):
> https://storage.googleapis.com/pdf-test/test.pdf

The file is no longer available (nor on the Internet Archive), hence it's probably not meaningful to keep this issue open.

(Also, the PDF.js library now supports embedded scripts, which based on https://github.com/mozilla/pdf.js/issues/7321#issuecomment-218762122 *should* mean that this is fixed now.)
