### ISSUE TITLE
getStrings with key "thumbs" returns undefined as the result the browser shows error 

### ISSUE THREAD

**Issue by vitaly-ndaw** [mozilla/pdf.js#7323]
Hi

Firefox (46.0.1) show this error
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

And Chrome (49.0.2623.112 m) shows this:
Uncaught SyntaxError: Unexpected token u

PDF.js version:
1.5.254

I used pdf js 1.0.907 and now I'm migrating to the new one and so I have replaced all files I used for 1.0 version and now I have this error with translation I believe.

As the result the pdf file is not showing on the viewer. How can I fix this? Thanks

**Comment by yurydelendik** [comment]
> I have replaced all files I used for 1.0 version and now I have this error with translation I believe.

It's not possible to reproduce the issue locally. Please provide link to your viewer. Standard viewer works for me for different cultures.

**Comment by vitaly-ndaw** [comment]
I don't have link to the viewer the changes are local. I can add that I'm using the latest dev version

**Comment by yurydelendik** [comment]
> I don't have link to the viewer the changes are local.

I'm sorry but it's not possible to address the issue without this information. Please commit all your change to github and provide a link?

**Comment by vitaly-ndaw** [comment]
just extract the project from here
http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi
try to open viewer.html and you will get the same error

**Comment by vitaly-ndaw** [comment]
Fixed. The server was not correctly configured!
