### ISSUE TITLE
PDFs looking strange.

### ISSUE THREAD

**Issue by MrOutput** [mozilla/pdf.js#7324]
PDFs looking strange in viewer. The issue happens when I switch from looking at one pdf to another. The first view always looks correct...the second one seems to have traces of the previous one. I am thinking it is a rendering issue or a memory leak.

Configuration:
(tested on chromium and FF and edge)
(tested on windows, and linux)

What is the expected behavior? (add screenshot)
![1463072836](https://cloud.githubusercontent.com/assets/8491687/15221623/d9b5240c-1831-11e6-8e0a-91e2b6a8f764.png)

What went wrong? (add screenshot)
![1463072710](https://cloud.githubusercontent.com/assets/8491687/15221599/bb12245a-1831-11e6-933b-752a9314431b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Version 1.1.366

**Comment by yurydelendik** [comment]
> Version 1.1.366

Is really old and your issue is probably fixed in new version. Closing as fixed?

Please provide more details to properly triage the issue: link to PDF or attach it. (you can test if it fixed at http://mozilla.github.io/pdf.js/web/viewer.html, but we still need the PDF to troubleshoot the problem).

**Comment by MrOutput** [comment]
I should have specified that I DID build the latest repo and STILL had the issue. I ended up rolling back to the old version.

**Comment by yurydelendik** [comment]
> I ended up rolling back to the old version.

As understand this is a workaround for the issue. 

Closing as incomplete. We will reopen once more information is provided.

**Comment by MrOutput** [comment]
**TEST PDF**

[test.pdf](https://github.com/mozilla/pdf.js/files/261857/test.pdf)

**Comment by yurydelendik** [comment]
Looks good on my computer. I don't think you are attaching the file that shows the issue.

**Comment by yurydelendik** [comment]
See
<img width="529" alt="screen shot 2016-05-12 at 12 05 26 pm" src="https://cloud.githubusercontent.com/assets/1523410/15223400/da05d976-1839-11e6-97a2-da1274f98f19.png">

**Comment by MrOutput** [comment]
it looks fine on mine too. The issue occurs when two pdfs are involved. By switching the pdfs w/o reloading causes the issue.

**Comment by yurydelendik** [comment]
> The issue occurs when two pdfs are involved. By switching the pdfs w/o reloading causes the issue.

Provide exact steps to reproduce the issue.
