### ISSUE TITLE
PDF object not getting loaded in android chrome browser

### ISSUE THREAD

**Issue by nisha-kajale** [mozilla/pdf.js#7329]
Hi,

I am trying to load pdf from a different domain in android but it is giving me error saying "This browser does not support inline pdf. Please download pdf to view it."

But when i access https://pdfobject.com/examples/pdfjs-forced.html from my android tablet i am able to view the pdf.

Can you please explain how should i code so that i can force chrome browser to view my pdf which is located at different domain as it is done in https://pdfobject.com/examples/pdfjs-forced.html.

I also tried by loading a pdf file from same domain to check if cross domain is an issue. But still it did not work for me.

Thanks,
Nisha

**Comment by Snuffleupagus** [comment]
This is the issue tracker for the *PDF.js* project, which has nothing to do with *PDFObject*. (They may be utilizing PDF.js in their examples, but we don't really know anything about that integration here.)
Issues regarding the usage of PDFObject are probably better suited here: https://github.com/pipwerks/PDFObject.

Closing as invalid
