### ISSUE TITLE
Browser fails to load 'g_font_1' font and instead of showing warning it throws an exception

### ISSUE THREAD

**Issue by acc15** [mozilla/pdf.js#7331]
Link to PDF file:
[operdayinfo.pdf](https://github.com/mozilla/pdf.js/files/266051/operdayinfo.pdf)

Configuration:
- Chrome 35.0.1916.153 m
- Windows 7 SP 2
- tested on 1.2.109 and 1.5.188

Steps to reproduce the problem:

    PDFJS.getDocument('pdf.pdf').then(function(pdf) {
        pdf.getPage(num).then(function(page) {
            page.render({
                canvasContext: canvas.getContext("2d"),
                viewport: viewport
            }).promise.then(function() {
                //
            }, function(err) {
                //
            });
        });
    });

What is the expected behavior?
PDF is rendered correctly

What went wrong?
  
Stacktrace from 1.2.109
 
    Uncaught TypeError: Cannot read property 'catch' of undefined pdf.js:6566
    getNativeFontPromise pdf.js:6566
    fontLoaderBind pdf.js:6583
    transportObj pdf.js:2902
    messageHandlerComObjOnMessage pdf.js:1568

This error occurs in a very rare cases. Browser fails to load 'g_font_1' font and instead of showing warning it throws that exception

**Comment by acc15** [comment]
Following changes fixes problem
However i'm not sure about it correctness

        ...
        var getNativeFontPromise = function(nativeFontFace) {
            // Return a promise that is always fulfilled, even when the font fails to
            // load.
    +       if (!nativeFontFace.loaded) {
    +           warn('Failed to load font "' + nativeFontFace.family + '": ' + e);
    +           return nativeFontFace;
    +       }
            return nativeFontFace.loaded.catch(function(e) {
                warn('Failed to load font "' + nativeFontFace.family + '": ' + e);     
            });
        };
        for (var i = 0, ii = fonts.length; i < ii; i++) {
            var font = fonts[i];
        ...

**Comment by Snuffleupagus** [comment]
> Chrome 35.0.1916.153 m

That version of Chrome is almost two years old. Is this issue still present in a latest version, which currently seem to be version `50`?
It's possible that there were bugs in the Font Loading API in older Chrome versions, which I suppose could explain the errors, especially considering that you describe the issue as intermittent:
> This error occurs in a very rare cases. Browser fails to load 'g_font_1' font and instead of showing warning it throws that exception

**Comment by acc15** [comment]
Upgrading to Chrome 50 solves problem
