### ISSUE TITLE
pdf.js loads a new copy of pdf.worker.js every time I call PDFJS.getDocument

### ISSUE THREAD

**Issue by gaye** [mozilla/pdf.js#7333]
I would like (for performance) to reuse the same worker. Could this be exposed in some configuration? This prevents the browser from needing to parse the worker js over and over again if I'm calling getDocument frequently.

Configuration:
- Web browser and its version: Chromium 49
- Operating system and its version: Ubuntu 15.10
- PDF.js version: 1.3.76
- Is an extension: No

Steps to reproduce the problem:
1. Call PDFJS.getDocument twice.

What is the expected behavior? (add screenshot)

Only one worker is spawned and is renders both documents.

What went wrong? (add screenshot)

A worker is spawned on every call to PDFJS.getDocument

![screenshot from 2016-05-16 13-02-33](https://cloud.githubusercontent.com/assets/535859/15302189/83b34074-1b66-11e6-94c9-63069b8b2389.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by gaye** [comment]
Ah I see that it's at least intended that consumers can pass a worker to `getDocument` via `getDocument({worker: someWorker})` https://github.com/gaye/pdf.js/blob/master/src/display/api.js#L219

**Comment by yurydelendik** [comment]
The issue was fixed in #6571 and part of the 1.3.91. Closing as answered.

**Comment by gaye** [comment]
Thanks @yurydelendik!
