### ISSUE TITLE
Ionic2 project

### ISSUE THREAD

**Issue by Vurk** [mozilla/pdf.js#7334]
Hi, I´m trying to add PDF.js to my Ionic 2 project as a pdf viewer with the particularity that I don´t load a .pdf but an array with the data created on the fly.

I generate a uint8Array array from a content variable with all the information. Then I blob the data into an url (this step can be omitted and only pass the array with the data). After that, I call my page with this code in the javascript:

"pdfUrl is the variable with the blob url"
let pdfUrl = navParams.get('pdfUrl'); 
PDFJS.workerSrc = '../../lib/pdfjs-dist/pdf.worker.js';    
    // Loading document.
    PDFJS.getDocument(pdfUrl).then((pdfDocument) => {
      pdfDocument.getPage(1).then((page) => {
        let scale = 1;
        let viewport = page.getViewport(scale);
        // Prepare canvas using PDF page dimensions.
        let canvas = document.getElementById('the-canvas');
        let context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;
        // Render PDF page into canvas context.
        let renderContext = {
          canvasContext: context,
          viewport: viewport
        };
        page.render(renderContext);
      });
    });

In the html file I have set the canvas: <canvas id="the-canvas" style="border: 1px solid black"></canvas>
 
When I test the code in the browser (Chrome version 50.0.2661.102 m) all works fine. But in a mobile with android 5.1.1, the pdf is not display. I only see the border of the canvas.

Anyone have an idea about what I have to do?

Thanks in advance.

**Comment by yurydelendik** [comment]
> Anyone have an idea about what I have to do?

It's hard to tell without life demo. (Can you provide a link to one?) But old androids may need web/combatibility.js and/or propert width/height set on the container div.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided. Make sure to use the provided issue template to provide us with all required information to debug this.
