### ISSUE TITLE
Embeded font problem. When display on screen it renders correctly, but when print out it use incorrect fonts. Also, the prinout loses the original resolution.

### ISSUE THREAD

**Issue by tanes73** [mozilla/pdf.js#7335]
Link to PDF file (or attach file here):
https://drive.google.com/file/d/0B-kWP0B0PGWLVFVTQnotLV85dlU/view?usp=sharing

Configuration:
- Web browser and its version: 
Firefox 46.0
- Operating system and its version:
Ubuntu 14.04
- PDF.js version:
Stable (1.4.20) and Current
- Is an extension:

Steps to reproduce the problem:

1. Use PDF.js to view.  
2. Then, print it out (click on printer button)

What is the expected behavior? (add screenshot)

Output on screen and print out should be the same.

What went wrong? (add screenshot)

Printout is not the same as on screen. It is noticeable easily since the character mapping is not correct. So, the font print on the printout is not the same font rendering (correctly) on screen.
 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
We need to disable font loading api usage for Firefox as workaround.

**Comment by timvandermeij** [comment]
Closing as fixed by #7694.
