### ISSUE TITLE
Pdf toolbar is missing when pdf is opened inside dynamic div container

### ISSUE THREAD

**Issue by eswarpdf** [mozilla/pdf.js#7338]
Link to PDF file (or attach file here):

Configuration: 
- Web browser and its version: Firefox 38.0.1
- Operating system and its version: Windows 
- PDF.js version: 1.5.188
- Is an extension:

Steps to reproduce the problem:
- This is not the issue with PDF.js

What is the expected behavior? 

Using PDF.js latest version. My requirement is to open pdf file in dynamic tab which is created as below.

```
var myUrl = "viewer.html?file=encodeURIComponent(blob)";

var newTab = '<div id="tab1"><iframe id="tab1-iFrame" src="'+myUrl+'" class="tab_content" style="width:100%; height:750px;" frameborder="0"></iframe></div>'; 

$('#dynamicContent').append(newTab);
$('#dynamicContent').show();

```
The pdf file is opening successfully in the div(tab1) but toolbar is missing. expected toolbar
![pdf-toolbar](https://cloud.githubusercontent.com/assets/18658733/15366154/a0e4ae04-1d40-11e6-95db-cbb87fce3afd.JPG)

I have 2 problems here.

   1. Open the pdf file inside div dynamically.?
   2. Toolbar should be visible in the opened pdf?

I've no clue where did I go wrong or is it the right way to open pdf inside dynamic tab(not a browser tab)?

**Comment by timvandermeij** [comment]
There is not much we can do if you do not have a working demo online somewhere for us to test/debug with. Please prepare one and post the link here.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
