### ISSUE TITLE
Color bar produced by PGFPlots does not render correctly

### ISSUE THREAD

**Issue by danieljohansson** [mozilla/pdf.js#7339]
Link to PDF file (or attach file here):
- [output.pdf](https://github.com/mozilla/pdf.js/files/271335/output.pdf)
- [PGFPlots manual](http://pgfplots.sourceforge.net/pgfplots.pdf) (See e.g. section 4.7.6 Color Maps)

Configuration:
- Web browser and its version: Firefox 46.0, Nightly 49.0a1, Chrome 50.0
- Operating system and its version: Windows 7 64-bit
- PDF.js version: 
  - Version built into Firefox 46.0, Nightly 49.0a1
  - Version at https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem: Open attached PDF.

What went wrong/expected behavior: 
![screenshot](https://cloud.githubusercontent.com/assets/1746843/15373999/8de2fd26-1d48-11e6-8eb1-5c35eb5691a6.png)

**Comment by THausherr** [comment]
Reduced file from #10874 … this is just one type 2 (radial) shading, but with a complex type 3 (stitching) function.
[PDFJS-10874-reduced.pdf](https://github.com/mozilla/pdf.js/files/3240081/PDFJS-10874-reduced.pdf)
