### ISSUE TITLE
IE11 Performance Issues

### ISSUE THREAD

**Issue by mawaru29** [mozilla/pdf.js#7350]
[Sample PDF -120 pages.pdf](https://github.com/mozilla/pdf.js/files/278481/Sample.PDF.-120.pages.pdf)
File attached. 

Configuration:
- IE: Version 11.0.9600.18314
- Chrome: Version 50.0.2661.102 m
- Operating system and its version: Windows 7 
- PDF.js version: 1.4.20
- Is an extension: No

Steps to reproduce the problem:
1. Load the PDF using PDF.js in both Chrome and IE11
2. Search for "the"
3. Search results take much longer in IE11 vs. Chrome.
4. Use the scrollbar to page through the document. IE11 displays the loading icon whereas, Chrome quickly loads the pages.

Is there a reason for the difference? Thanks!

**Comment by Snuffleupagus** [comment]
> Is there a reason for the difference?

Yes, for one the JavaScript performance in Internet Explorer is much worse than in e.g. Firefox or Chrome. Also, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE doesn't support all the features that PDF.js relies on. The missing ones have to be emulated, which is slower than using native JavaScript functions.

Closing as answered.

**Comment by mawaru29** [comment]
Thanks for the explanation!
