### ISSUE TITLE
chrome V51 timesout in the middle of the test suite

### ISSUE THREAD

**Issue by seth4618** [mozilla/pdf.js#7363]
Configuration:
- Web browser and its version: Chrome 51.0.2704.63 unknown (64-bit)
- Operating system and its version: Ubuntu 14.04.1
- PDF.js version: 0.8.0  (forked on github on 5/26, commit: 41f978c)
- Is an extension:no

Steps to reproduce the problem:

```
git clone git@github.com:seth4618/pdf.js.git
cd pdf.js
git submodule init
git submodule update
npm install
git remote add upstream git://github.com/mozilla/pdf.js.git
gulp lint
cp test/resources/browser_manifests/browser_manifest.json.example test/resources/browser_manifests/browser_manifest.json
<edit to put in paths for both firefox and chrome>
cd test
node test.js -m --browserManifestFile=resources/browser_manifests/browser_manifest.json
```

Expected all tests to pass, but only passes for firefox.  Chrome timesout in the middle of testing.  And the test output includes:

```
TEST-UNEXPECTED-FAIL | test failed Chrome has not responded in 120s
[Chrome] Going to wait until the browser process has exited.
[Chrome] Browser process exited with status 0
[Chrome] Clean-up finished. Going to call callback...
```

The first time chrome timed out during "rotation" the second time during "issue6019-text"

**Comment by oekonomi** [comment]
Can you confirm this is still an issue?

**Comment by timvandermeij** [comment]
Closing since we have not seen this happening anymore and we have had no more reports of this. Chrome 51 is out of date now.
