### ISSUE TITLE
Ionic CORS

### ISSUE THREAD

**Issue by starkemc** [mozilla/pdf.js#7366]
What is the best way to implement PDF.js in a cordova app like Ionic since CORS is not supported?

**Comment by Rob--W** [comment]
Not tried myself, but it seems that you can get Cordova to request data from sources other than file: https://github.com/apache/cordova-plugin-whitelist

**Comment by Snuffleupagus** [comment]
I don't think that any of the PDF.js developers/contributors are experts in that particular framework, so we'll not be able to provide much assistance here. It'd probably be better to ask for help from the Ionic community.

Closing, since this isn't an issue with PDF.js.
