### ISSUE TITLE
Implement a UI for multiple phrase search

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7368]
PR #5579 implemented multiple phrase search, but as of now this is only accessible through the `#search=` URL parameter. It would be nice have a UI for this. We need to adapt our current find bar to add a checkbox for phrase search, but this also involves integration for the Firefox add-on.

**Comment by ribeaud** [comment]
See #7870 for corresponding pull request.

**Comment by Snuffleupagus** [comment]
Given that this, as outlined in https://github.com/mozilla/pdf.js/issues/7368#issuecomment-425377443, is basically blocked on similar functionality existing for regular searching in Firefox *itself*, is it really meaningful to keep this issue open indefinitely?
