### ISSUE TITLE
i want to show TextLayer, which  js file  i must integrate?  thk

### ISSUE THREAD

**Issue by zhagener** [mozilla/pdf.js#7376]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
The viewer components examples, see https://github.com/mozilla/pdf.js/tree/master/examples/components, provides text-selection by default and should be the simplest way to build a custom viewer.
Closing as answered.
