### ISSUE TITLE
PDF comes up empty (with suggestion to use different viewer)

### ISSUE THREAD

**Issue by tobp** [mozilla/pdf.js#7379]
http://bermudarace.com/wp-content/uploads/2016/04/Newport-Bermuda-2016-v1-PDF-for-Web.pdf

Configuration:
- Web browser and its version: FIREFOX 47.0b9
- Operating system and its version: Window 7 (32bit)
- PDF.js version: internal version within Firefox

Steps to reproduce the problem:
1. Open File
2. Shows up blank - not even the page frame is shown, just the suggestion to open it in a different viewer.

**Comment by timvandermeij** [comment]
Are you able to reproduce this when you download the PDF file and open it with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar)? That is the most recent version of PDF.js. Your link does work fine for me on Arch Linux using Firefox 46.0.1 and the latest PDF.js development version.

**Comment by brendandahl** [comment]
Also works fine for me on FF48 and OSX.

**Comment by tobp** [comment]
CLOSE. Today, it works again - seems as if Firefox just wanted to be re-startet? At least, nothing else has changed.
