### ISSUE TITLE
disable referrer by default

### ISSUE THREAD

**Issue by devd** [mozilla/pdf.js#7380]
With stuff like https://blog.mozilla.org/security/2015/01/21/meta-referrer/ now widely available, I think PDF.JS should set the policy to origin to limit leakage of potentially sensitive PDF URIs via links clicks in the PDF.

**Comment by Snuffleupagus** [comment]
By default all external links already use `rel = noreferrer`, please see https://github.com/mozilla/pdf.js/blob/7c7d2399956c25491aa7d2548c9c784cc2b3cea8/src/display/global.js#L230-L236.

Closing as answered, since it doesn't seem like there is anything more we'd need to do here.

**Comment by devd** [comment]
ohh! thanks! sorry I missed it.
