### ISSUE TITLE
Browserified PDFJS should be exported like other cjs modules

### ISSUE THREAD

**Issue by gaye** [mozilla/pdf.js#7381]
Currently it makes itself globally available as `PDFJS`

**Comment by gaye** [comment]
Currently it makes itself globally available as `PDFJS`

**Comment by yurydelendik** [comment]
pdf.js and pdf.worker.js are wrapped with UMD header, so it can be used as cjs module. Global PDFJS is only for legacy support and planned to be removed in v2 or later. 

Based on information and examples provided in the example, I'll close the issue as answered.
