### ISSUE TITLE
In session-restored tabs in Firefox, the wrong page is displayed

### ISSUE THREAD

**Issue by aleth** [mozilla/pdf.js#7385]
Configuration:
- Web browser and its version: Firefox 48
- Operating system and its version: OSX 10.11
- PDF.js version: builtin
- Is an extension: no

Steps to reproduce the problem:
1. Open a large PDF file, go to e.g. page 150, switch to a different tab and restart Firefox
2. After the restart, switch back to that tab (at which point it gets reloaded)

What is the expected behavior? (add screenshot)
Correct scroll position restored

What went wrong? (add screenshot)
The correct page number appears in the page number box in the toolbar, but the displayed page is page 1.
Probably a race condition somewhere?

**Comment by Snuffleupagus** [comment]
I believe that this issue will be possible to work-around as part of the `PDFHistory` rewrite being done in PR #6272. (That work is currently blocked by PR #7341, and then on finding a reviewer willing to review the rather large changes in #6272.)

**Comment by Snuffleupagus** [comment]
> I believe that this issue will be possible to work-around as part of the PDFHistory rewrite being done

A work-around landed as part of the re-factoring in PR #8775, which is included in Firefox 57.
