### ISSUE TITLE
Add upstream fix for Bug 1242730

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#7386]
https://bugzilla.mozilla.org/show_bug.cgi?id=1242730 is landing but there is no fix for it in our repo. We need to detect if newer API is available and fallback on old way if not available.

**Comment by Snuffleupagus** [comment]
Before we attempt to upstream that patch, I think that it would really help if we made a decision about the *minimum* Firefox version that we intend to support with the development addon.

Currently we've got quite a bit of fallback code for fairly old Firefox versions in `PdfStreamConverter.jsm` (and `PdfjsChromeUtils.jsm`), and given the lack of testing, I wouldn't be surprised if the development addon is already semi-broken in older Firefox versions.

My suggestion is thus that we should limit support for the development addon to the *currently shipping* ESR version, which as of this writing is `45`. This would considerably reduce the amount of necessary fallback code, and greatly simplify testing.

/cc @brendandahl, @yurydelendik What are your thoughts on this?

**Comment by yurydelendik** [comment]
In addition to ESR let's check what latest Linux distributions include, plus I think we have some SeaMonkey users and they want to use the extension as well.

**Comment by yurydelendik** [comment]
Here is list of daily usages summed for period of one year from our legacy addon stats. Not sure why people still using it :/

```
App	Total
FF 40	3050155
FF 39	2805922
FF 44	2589532
FF 41	2544491
FF 45	2207403
FF 47	1565187
FF 42	1478297
FF 46	1216450
FF 43	666152
FF 24	333915
FF 31	304256
FF 15	300091
FF 37	261152
FA 35	254973
FF 26	231364
FA 34	214289
FA 39	210397
FA 45	197221
FF 25	189924
FA 42	188915
FA 40	188471
FF 12	173516
FA 41	170845
FF 34	168639
FF 35	167576
FF 36	158247
FA 43	152549
FA 44	137043
FF 32	135483
FF 17	134114
FF 30	133216
FA 46	128728
SM 2.33	125355
FF 28	113655
FF 38	103015
FF 33	83857
FF 29	79209
FF 20	76495
FF 27	75348
FF 22	74283
FA 38	53706
FF 14	47220
FF 16	38816
```
