### ISSUE TITLE
pdf.js is making the pdf wind smaller and un expandable .

### ISSUE THREAD

**Issue by Darknight2403** [mozilla/pdf.js#7392]
I am facing a starnge issue from 4th of june'16. The pdf.js is making the pdf viewing window very small . I can not even expand it . It is making the viewing experiance very uncomfortable .
![pdf issue](https://cloud.githubusercontent.com/assets/19814029/15885553/981cdd06-2d75-11e6-9e1a-168d9d4c97de.JPG)For agreement issue , I can not show you the pdf content but the the problem in the screenshot is recognizable I hope .

I need to use this extention to show the pdf . Other extentions are not very helpfull .This issue is relatively new , I suspect this is occurring due to a recent update you have given to this extention.

Please let us know once you have pin pointed the issue . Hope you guys will fix this in no time ..

**Comment by Snuffleupagus** [comment]
As outlined in the *fourth* paragraph of [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), you must provide access to a working example in order for the issue to be valid:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, please prepare a short well-documented example that demonstrates the problem and make it accessible online on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- keep in mind that just code snippets won't help us troubleshoot the problem.

**Comment by timvandermeij** [comment]
As mentioned above there is not enough information here for us to work with. Closing as incomplete until the information requested in the issue template is provided.
