### ISSUE TITLE
Get text based on bounding box

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7396]
I would like to ask if it is possible in PDF.js wherein i have a bounding box rectangle and i would like to get the text that belong to that area.

I used 

var rect = viewport.convertToPdfPoint

and

viewport.convertToViewportRectangle(rect);

in order to get the bounds (left, top, width, height).

**Comment by timvandermeij** [comment]
As far as I know there is no such functionality in the API. You can get the text content of a page, but not of such a specific region. This is not something that is useful for the PDF.js library itself, but rather for a custom implementation only, so I'm closing this here.

**Comment by Sposito** [comment]
Actually iTextSharp pdf library for C# does exactly that, and it is really usefull for getting spatial context from the text. I would really appreciate if u could reconsider opening this again @timvandermeij

**Comment by chitgoks** [comment]
hi sposito, i managed to do this without pdf.js

add a Span tag for each character because doing this you will be able to get the offset x,y coordinates as well as the width and height and use these details to see if it intersects within the annotation shape’s bound.

it may not look pretty but it gets the job done

**Comment by greddyatpt** [comment]
I was looking for this feature too.  I'd consider it a basic feature in a document library.  Geometry, fonts and font sizes would be extremely useful.  How would a custom implementation get this info?

**Comment by mNeevetha** [comment]
> I would like to ask if it is possible in PDF.js wherein i have a bounding box rectangle and i would like to get the text that belong to that area.
> 
> I used
> 
> var rect = viewport.convertToPdfPoint
> 
> and
> 
> viewport.convertToViewportRectangle(rect);
> 
> in order to get the bounds (left, top, width, height).


@chitgoks Can I know how did you implement that functionality?

**Comment by gggauravgandhi** [comment]
This feature can be very useful, currently i am going through transform value of all text contents to find text fitting specific bounding box.

**Comment by Wanderish** [comment]
@gggauravgandhi I'm stuck doing that with nowhere to go. 
Were you able to pull it off? Any suggestions?

**Comment by gggauravgandhi** [comment]
No, I dropped that project so didn't spend much for the solution.

**Comment by Wanderish** [comment]
@gggauravgandhi Oh, okay. Thanks, anyway!

**Comment by RaviKumarNatrajan** [comment]
> I would like to ask if it is possible in PDF.js wherein i have a bounding box rectangle and i would like to get the text that belong to that area.
> 
> I used
> 
> var rect = viewport.convertToPdfPoint
> 
> and
> 
> viewport.convertToViewportRectangle(rect);
> 
> in order to get the bounds (left, top, width, height).

How did you implement Rectangle bounding box because when I draw a bounding box inner rect filling with white color bg
