### ISSUE TITLE
Use PdfJs in Electron app

### ISSUE THREAD

**Issue by BesatZardosht** [mozilla/pdf.js#7397]
How can I use pdfjs in Electron app?
Is there a good tutorial?

**Comment by timvandermeij** [comment]
This issue tracker is only used to track problems in PDF.js. We do not provide support for using PDF.js with other frameworks/libraries. You can ask for this on the IRC channel or the mailing list. See also previous issues about Electron: https://github.com/mozilla/pdf.js/search?q=electron&type=Issues&utf8=%E2%9C%93. Closing as answered.

**Comment by yurydelendik** [comment]
> How can I use pdfjs in Electron app?

Yes, you can use generic viewer with Electon without any change

> Is there a good tutorial?

https://github.com/electron/electron-quick-start, copy generic viewer and replace index.html address to web/viewer.html
