### ISSUE TITLE
pdfviewer will not show online pdfs... even with CORS correctly configured

### ISSUE THREAD

**Issue by leinaD-natipaC** [mozilla/pdf.js#7399]
Link to PDF file (or attach file here): https://github.com/mozilla/pdf.js/blob/gh-pages/web/viewer.js#L8366

Configuration:
- Web browser and its version: firefox
- Operating system and its version: ubuntu
- PDF.js version: PDF.js version 1.5.292 (latest commit of gh-pages as of today- bc5e00a)
- Is an extension: no

Steps to reproduce the problem:
1. Set up a page for the viewer. 
2. Set up a server to serve pdfs with the access-control-allow-origin configured correctly
3. Go to the viewer with the file argument set to one of the pdfs from step 2 (as in "example.com/web/viewer.html?file=http://website.org/pdf.pdf")

What is the expected behavior? (add screenshot)
For the viewer to show the pdf normally.

What went wrong? (add screenshot)
Exception thrown by the viewer: "file origin does not match viewer's"

NOTICE: When I removed the throw exception from line 8366 (if (fileOrigin !== viewerOrigin) then throw the exception), the viewer worked JUST FINE with my project. So this check should be substituted for one that doesn't prevent something that should work from working, or removed (IMO).

**Comment by yurydelendik** [comment]
It's disabled on purpose. See #6916 for details. We also mentioned that at [FAQs](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr). Closing

**Comment by rohitcoder** [comment]
This was little bit tough, but here a solution https://stackoverflow.com/a/62953428/6110557 if anyone want to get it solved you can follow this same lnk :) https://stackoverflow.com/a/62953428/6110557
