### ISSUE TITLE
Text glyphs are scrambled

### ISSUE THREAD

**Issue by BHSPitMonkey** [mozilla/pdf.js#7403]
### Link to PDF file (or attach file here): 
[garbled78910.pdf](https://github.com/mozilla/pdf.js/files/309967/garbled78910.pdf)

### Configuration:
- Web browser and its version: **Firefox 47.0**
- Operating system and its version: **Ubuntu 16.04**
- PDF.js version: **1.4.121**
- Is an extension: **no**

### Steps to reproduce the problem:
1. Open the PDF
2. Scroll to page 3, 4, or 5

### What is the expected behavior?

![screenshot from 2016-06-10 16-16-20](https://cloud.githubusercontent.com/assets/33672/15981169/d1b57a5c-2f26-11e6-9dbd-6cc1bde8fec1.png)

### What went wrong?

![screenshot from 2016-06-10 16-16-44](https://cloud.githubusercontent.com/assets/33672/15981178/dd60defa-2f26-11e6-9239-a82226f692e5.png)

(Text is corrupt all over the last three pages; the screenshots only compare one section.)

**Comment by Snuffleupagus** [comment]
@BHSPitMonkey Are you the author of the PDF file, and if so may we include it in our test-suite?

**Comment by BHSPitMonkey** [comment]
@Snuffleupagus - I'm not, though the document is a derived version of a standard tax form (from https://www.gov.uk/). That being said, I wouldn't say I have the authority to say it can be included (from a licensing perspective).
