### ISSUE TITLE
Images not rendering due to quantizationTables missing at rendering phase

### ISSUE THREAD

**Issue by flexpaper** [mozilla/pdf.js#7406]
Link to PDF file (or attach file here):

Configuration:
[broken-image.pdf](https://github.com/mozilla/pdf.js/files/311002/broken-image.pdf)

- Web browser and its version:Chrome 51
- Operating system and its version:OSX 10.10.5
- PDF.js version:1.5.294
- Is an extension:No

Steps to reproduce the problem:
1. Open PDF
2. Observe no images appearing

What is the expected behavior? (add screenshot)
Images appearing (they are appearing in OSX Preview, Adobe Acrobat, Chrome PDFium)

What went wrong? (add screenshot)
This seems related to reading the quantizationTables in the parse function of JpegImage. It looks like the quantizationTables are parsed after they are used which is causing them to be empty. Could this be a matter of rendering order for these tables?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
@flexpaper Are you the creator of the PDF file, and if so may we include it in the test-suite?

*Please note:* I've submitted a tentative patch, but we really need to be able to include a test-case with the patch in order to land it.

**Comment by flexpaper** [comment]
I am not the author of this particular pdf so I can't give that permission unfortunately :( 
I'll try to create a new sample for you that you can use for your suite

**Comment by timvandermeij** [comment]
I think we'll have to try to make a reduced test case out of the posted PDF somehow.
