### ISSUE TITLE
TextItem width way off

### ISSUE THREAD

**Issue by richkniles** [mozilla/pdf.js#7411]
Link to PDF file (or attach file here):
[text_item_widths_off.pdf](https://github.com/mozilla/pdf.js/files/314774/text_item_widths_off.pdf)

View this file in the viewer.  Search for the word 'designated'.  The highlighting of the search hit on line 5 is way off to the right of where the word is rendered on the canvas.  This is caused by the width of TextItem[10](Returned in the promise from getTextContent%28%29) having a width that is about 50% too high.

This pdf file was generated by MS Word, from a document using New Times Roman font. The issue is corrected if I use MS Word's default 'Calibri' font.

I've created my own viewer with a search function, and I'd like the search hits to match more closely to the rendered text on the canvas.  I've looked at quite a few pdfs in my viewer, and most of them have fairly close matching between search highlighting and the rendered text.  But documents created in word with most fonts other than the default "Calibri" seem to have similar problems.

Any advise?

**Comment by timvandermeij** [comment]
Closing as fixed, most likely by #7879. This now aligns perfectly.
