### ISSUE TITLE
A0 sized pdfs are extremely slow

### ISSUE THREAD

**Issue by chrisdunne** [mozilla/pdf.js#7415]
A0 sized pdfs are extremely slow to display above 110% zoom on the viewer.

Configuration:
- Web browser and its version: Chrome/51.0.2704.84
- Operating system and its version: windows 10 pro
- PDF.js version: 1.4.20

Steps to reproduce the problem:
1. upload @ viewer
2. zoom 130% +

What is the expected behavior? Slow rendering

What went wrong? Slow rendering

PDF:
[HDR-Ashill-Land-Ltd-PDA-05-Matter-4.pdf](https://github.com/mozilla/pdf.js/files/316368/HDR-Ashill-Land-Ltd-PDA-05-Matter-4.pdf)

Above file grabbed from online @ https://www.sevenoaks.gov.uk/__data/assets/pdf_file/0005/128651/HDR-Ashill-Land-Ltd-PDA-05-Matter-4.pdf initial problem found using my own pdfs locally, was recreated using the viewer and externally sources pdf.

**Comment by chrisdunne** [comment]
Update:

Also noticed occasionally when you zoom in beyond 130% and zoom back out, the image flips/mirror images. I've noticed this has been mentioned previously, with no solution, but "it works for me". I'd assume the two issues are connected via the zoom functionality.

**Comment by timvandermeij** [comment]
Closing since this file renders almost instantly now after optimizations from the last few years.
