### ISSUE TITLE
Boxed X symbol shown instead of Japanese multibyte space (but not always) only on IE

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#7416]
Link to PDF file (or attach file here):
[boxed_x_symbol.pdf](https://github.com/mozilla/pdf.js/files/317616/boxed_x_symbol.pdf)

Configuration:
- Web browser and its version: **IE only** (Firefox/Chrome are OK)
- Operating system and its version: Windows 7
- PDF.js version: any version up to 1.5.188
- Is an extension:

Steps to reproduce the problem:
1. Open the attached PDF on IE.
2. You will see boxed X symbol as attached screen shot below. (I indicated) The problematic location is Japanese multi-byte space character exist, but the boxed X symbol doesn't always show with the multi-byte space character, in many cases showing properly.
Below screen shots are my own tool implemented on local web server, so that it's not accessible in internet, but the tool is just a collection of several versions of PDF.js. (nothing changed)

What is the expected behavior? (add screenshot)
![boxed_x_symbol_firefox](https://cloud.githubusercontent.com/assets/7111820/16104557/7b727316-33bd-11e6-8c75-b3ff2b24b968.jpg)

What went wrong? (add screenshot)
![boxed_x_symbol_ie11](https://cloud.githubusercontent.com/assets/7111820/16104489/d195fd4a-33bc-11e6-8ebb-07924fc83788.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Please look into and investigate it.
Thanks in advance,
Best Regards

Futoshi Tanuma

**Comment by brendandahl** [comment]
@Snuffleupagus I'm guessing this another case where we need to not map to the character. Do you have a version of IE11 to test with?

**Comment by takahiroyoshi** [comment]
@futot1 
see:
https://github.com/mozilla/pdf.js/issues/4836
https://github.com/mozilla/pdf.js/issues/7033
を見てください。

**Comment by futot1** [comment]
@takahiroyoshi san, Thanks for your reply.
Yes, the issue must be the same and your fix code in #4836 worked fine for me, too.
Thanks for your letting me know.
Have you pushed the fix code to repository??

**Comment by takahiroyoshi** [comment]
@futot1 
Not yet. I do not know(understand) how to push the code to repository.
Could you do it for us Japanese?

**Comment by futot1** [comment]
@takahiroyoshi san
Hmm, I have briefly reviewed contribution guideline document, but it seems not easy.
https://github.com/mozilla/pdf.js/wiki/Contributing

**Comment by brendandahl** [comment]
@futot1 Can you verify the fix by using the preview of the above pull request? http://107.21.233.14:8877/f92ec0b01764b9b/web/viewer.html

**Comment by futot1** [comment]
@brendandahl san, Thanks for your message, but could you please let me know how I can do pull request?
I think I don't have the problematic PDF file on 107.21.233.14 server so that I need to test it on my end, but even though I have obtained whole pdf.js code from #7427 but when I run it, it shows JavaScript error in viewer.js, possibly the way I did was wrong...

**Comment by Snuffleupagus** [comment]
> [...] but could you please let me know how I can do pull request?

A PR has already been submitted, see #7427. What Brendan asked was that you help verify that it works correctly, so please follow these steps and report back if it worked:
1. Open http://107.21.233.14:8877/f92ec0b01764b9b/web/viewer.html in Internet Explorer.
2. Click on the "Open file" button on the right-hand side of the toolbar.
3. In the dialog, browse to the location of `boxed_x_symbol.pdf` on your local hard drive, and open it.

**Comment by futot1** [comment]
Thanks @Snuffleupagus san for letting me know.
I didn't know the button for opening local PDF. :-)
Yes, http://107.21.233.14:8877/f92ec0b01764b9b/web/viewer.html does fix the problem of this issue.
Thank you for people doing this!
But I think @takahiroyoshi san may need to confirm his issues on this, since I guess there're slightly more lines in his fix than #7427 fix.

**Comment by takahiroyoshi** [comment]
Yes,
http://107.21.233.14:8877/f92ec0b01764b9b/web/viewer.html shows no problem for PDFs I have.
Thank you.
