### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7422]
Link to PDF file (or attach file here): http://arxiv.org/pdf/1604.00289.pdf

Configuration:

Web browser and its version: Chrome Version 53.0.2770.0 canary (64-bit)
Operating system and its version: Win 10, 1511, 64b, Build 10586.420
PDF.js version: 1.5.294
Is an extension: Yes
Steps to reproduce the problem:
1. Click the link
2. Scroll (go to) page 9

What is the expected behavior? (add screenshot)
Page is displayed

What went wrong? (add screenshot)
Crash (Aw, snap!)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

BTW, I tried to reduce the Zoom Factor, but it didn't help.
And it does NOT crash in Chrome Version 53.0.2767.4 dev-m (64-bit)

**Comment by Rob--W** [comment]
Can't reproduce on Linux (x64), 53.0.2770.0 or  53.0.2771.0; Memory usage appears normal (around 100MB while scrolling through the pages).

Canary builds of Chrome are full of bugs, so I would not be surprised if this problem goes away within a few updates. Is this bug consistently reproducible? Do you have a crash ID, chrome://crashes?

**Comment by qwer1304** [comment]
It reproduces, also on Version 53.0.2771.0 canary (64-bit).
Crash IDs: 
6750a1a600000000 (911f1611-5464-4a2c-9c40-281aac31c27c)
5c7a21a600000000 (ef842ec0-2f87-4b31-9cd3-f612bc218c51)

**Comment by timvandermeij** [comment]
Works fine for me on Arch Linux x64 and Firefox 47.0. The PDF itself does not seem to have any strange properties, such as huge images for example. Does it also happen with non-Canary builds of Chrome, i.e., the current release version?

**Comment by Rob--W** [comment]
I've opened a bug report at https://crbug.com/621297.

If you're adventurous, then you can also help by generating a crash dump and extract a stack trace: https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug#TOC-Windows

**Comment by qwer1304** [comment]
I managed to fix the issue by creating a new user directory.
Note that creating a new profile did NOT fix the issue.
