### ISSUE TITLE
Text missing from some PDFs rendered in Chrome on Mac OS

### ISSUE THREAD

**Issue by bergr01** [mozilla/pdf.js#7423]
[ShimanoXTR-BrakesHoseFitting.pdf](https://github.com/mozilla/pdf.js/files/322621/ShimanoXTR-BrakesHoseFitting.pdf)
[41631689AO.PDF](https://github.com/mozilla/pdf.js/files/322622/41631689AO.PDF)

Chrome 51.0.2704.103 (64 bit)
Operating system: OS X Yosemite - 10.10.5
PDF.js version "pdfjs-dist": "^1.5.262",

**Comment by Snuffleupagus** [comment]
As requested in the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, please provide screenshots of the rendering issues. Also, are there any warnings/errors printed in the console?

**Comment by bergr01** [comment]
Didn't see any warnings/errors, will upload screenshots tomorrow when I get access to the Mac book again.

**Comment by bergr01** [comment]
![screen shot 2016-06-22 at 6 43 40 am](https://cloud.githubusercontent.com/assets/4503791/16245727/86a16986-3845-11e6-9b1b-50ccf8529568.png)
![screen shot 2016-06-22 at 6 44 38 am](https://cloud.githubusercontent.com/assets/4503791/16245740/8f95eb48-3845-11e6-869d-b7530006bfba.png)
![screen shot 2016-06-22 at 6 47 26 am](https://cloud.githubusercontent.com/assets/4503791/16245747/97be7cfe-3845-11e6-8b59-fee6e67207e4.png)
![screen shot 2016-06-22 at 6 48 25 am](https://cloud.githubusercontent.com/assets/4503791/16245755/9e48cd2c-3845-11e6-9487-68cedf2c9382.png)

First two screenshots are from Chrome browser and demonstrate the problematic rendering, the next two are from Firefox on the same Mac OS machine and show what the document is meant to look like (although you can probably see that by just opening the originally attached PDFs in Adobe Reader, etc). Let me know if you need anything else from me

**Comment by NguyenPhiCuong** [comment]
I got the same issue when I minify source code of pdfviewer component to develop to environment production. 

Error message; "Error during font loading: Maximum call stack size exceeded"

**Comment by bergr01** [comment]
Nguyen - are you saying the 'text not rendering correctly in Chrome' for the above-mentioned PDFs does not happen if one uses non-minified pdfviewer source? Didn't quite understand whether that's what you were trying to say, especially with your p/s.

**Comment by bergr01** [comment]
Hi, do you need me to provide any more information on this issue or do you have enough to go on with?

**Comment by pascalboucher** [comment]
I have the same issue, they say that they implemented a workaround in https://github.com/mozilla/pdf.js/blob/be6754a1a05b59668677154cedb3ec43d0f96169/make.js#L709

but it's not working for me.

**Comment by theMxb** [comment]
After safari gets the bcmap, it feels that the thread is blocked for a long time before responding, please help me.....

**Comment by Snuffleupagus** [comment]
Is it really meaningful to keep this (very) old issue open, when everything points to a platform/browser bug (rather than a PDF.js one), since this doesn't seem like something that can be fixed *here*?
