### ISSUE TITLE
PDF.js Viewer.html Presentation mode Problem

### ISSUE THREAD

**Issue by coer123** [mozilla/pdf.js#7429]
I have embedded in some html files to display PDFs the:

http://mozilla.github.io/pdf.js/

Now that html files are exported from an application to make courses. And in this way is used the viewer.html with pdf.js inside that html files when I look the code:

`<IFRAME scrolling=no src=\'pdf/web/viewer.html?file=test.pdf#page=1&zoom=75,-8,797\'></IFRAME>`

Now the problem is that the presentation mode icon or presentation mode element from the right side menu is not displayed when is called from that html files exported from the application to make courses. However if I call directly without any embedding in any of that html files produced by that course creator  in this form http://xxx.xxx.xxx.xxx/web/viewer.html?file=test.pdf works perfect just when I call via an iframe code like I pasted before from that html files courses generated is not shown the presentation mode icon or right menu element.

Anyone has an idea of why the presentation mode icon or presentation mode menu element in the right side are not shown? Just us the presentation mode.

Thank you

**Comment by Snuffleupagus** [comment]
You need to set the `allowfullscreen` attribute on the `<iframe>` in order for this to work, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe. Closing as answered.

**Comment by coer123** [comment]
it works thank you
