### ISSUE TITLE
Pdf with Chinese characters renders really slow in Safari

### ISSUE THREAD

**Issue by guoxing** [mozilla/pdf.js#7431]
Link to PDF file (or attach file here):
https://www.dropbox.com/s/l7deqa82azeapg9/safari.pdf?dl=0

Configuration:
- Web browser and its version: Safari Version 9.1.1 (11601.6.17)
- Operating system and its version: OS X 10.11.5
- PDF.js version: 1.4.20
- Is an extension: No

Problem:
Some pdfs with Chinese characters that require specific cmaps (UniGB-UTF16-H and Adobe-GB1-UCS2) to load render really slow in Safari. It takes about 20-30s for a 2-page pdf to finish rendering. And during rendering time it takes the whole CPU power all the time. It works fine on Chrome/Firefox though.

**Comment by daveydee33** [comment]
This is also very slow in IE11.  Roughly 10x slower in IE11 vs Chrome and Firefox.

**Comment by AugustePop** [comment]
the postMessage from worker takes a lot of time for the font. no idea why. disableWorker somehow alleviate the problem.

**Comment by Snuffleupagus** [comment]
Given first of all the age of the issue, and secondly the fact that it looks to a platform/browser-specific bug; @timvandermeij does it really make make sense to keep this issue open?
