### ISSUE TITLE
Localization | PDF.js language

### ISSUE THREAD

**Issue by webdrifter** [mozilla/pdf.js#7432]
Hi!

Using PDF file viewer link and assets as per documentation
`<a href="assets/js/pdf.js/web/viewer.html?file=../../../files/invoice.pdf">Arve</a>`
and everything works. 

1) Wanted to change pdf.js viewer toolbar language. 
`<a href="assets/js/pdf.js/web/viewer.html#locale=et?file=../../../files/invoice.pdf">Arvel</a>`

Did not work. Wasn't able to find any documentation regarding localization. Found other people having the same issue:

- https://github.com/mozilla/pdf.js/issues/3761 (Issue closed, but doesn't seem to work). Example: http://mozilla.github.io/pdf.js/web/viewer.html#locale=he
- http://stackoverflow.com/questions/29407188/how-to-localize-pdf-js-toolbar

**Please:**
- Include localization in the documentation and provide a working example
- Consider assigning toolbar language using html lang attribute from html document. `<html lang="et">` for example. Or provide a solution to do it. It would be very easy to use on multilingual pages. Its not only English out there.

**Comment by Snuffleupagus** [comment]
For security reasons, some of the hash parameters (e.g. `locale`) are disabled by default, please see https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js.

If you want to force a particular locale, you should set the `PDFJS.locale` variable in your code, please see https://github.com/mozilla/pdf.js/blob/2d8ed7ba187ad3e3a550e49534c57c0500bc9667/web/ui_utils.js#L84-L88.

Closing as answered.

**Comment by webdrifter** [comment]
Still not clear where to change and what?!

**Comment by yurydelendik** [comment]
> Still not clear where to change and what?!

Comment at https://github.com/mozilla/pdf.js/issues/7432#issuecomment-228314648 has a solution, e.g. set `PDFJS.locale = 'et';` in a script inside viewer.html or viewer.js -- similar to what you asked in the issue description.

**Comment by webdrifter** [comment]
Thank you @yurydelendik. This fixed it. Wasn't able to understand @Snuffleupagus example. Wasn't sure I should change lines in core js file 
(e.g `PDFJS.locale = (PDFJS.locale === undefined ? navigator.language : PDFJS.locale`);

How about using `<html lang="">` attribute (website language) to define interface language - if webpage uses another language - change the language in the interface. If html lang is not set use navigator navigator.userLanguage? I mean if we are going to have 5 different languages we need to overwrite the PDFJS.locale every time?

What do you think?

**Comment by yurydelendik** [comment]
> html lang is not set use navigator navigator.userLanguage

That's what viewer is doing, no?

**Comment by webdrifter** [comment]
No, I don't think so. I think it would be a great improvement.

**Comment by yurydelendik** [comment]
Localization and user language detection WFM

<img width="916" alt="2016-06-24 3 59 01 pm" src="https://cloud.githubusercontent.com/assets/1523410/16350533/d4ee3fd4-3a24-11e6-89f0-a98eba4d7911.png">

**Comment by webdrifter** [comment]
Currently user language detection uses browser settings - not html code lang attribute. I mean if I have Estonian page and I'm using browser with English language the viewer is in English indeed. But if I want Estonian language I need to change the PDFJS.locale variable.

It would be reasonable PDF.js to use html lang attribute value to change the interface language. I mean if I code web page in Estonian, Russian, Swedish etc the viewer takes language values from the HTML code. If you view current issue page HTML source code you see <html lang="en">

**Comment by balmydrizzle** [comment]
I modify pdf.js code to force localization. It's feasible. Whereas, setting pdfjs.locale doesn't work sometimes.

**Comment by softwareonair** [comment]
in web/ui_utils.js, changing getLanguage(){ return "yourlocale" } and build does the job.

**Comment by kfir91** [comment]
> in web/ui_utils.js, changing getLanguage(){ return "yourlocale" } and build does the job.

not worked for me

**Comment by rjakshayjain13** [comment]
What is the suggested way to change locale as of the v2.2.228? I am only using viewer.html to render the pdf.
