### ISSUE TITLE
PDF JS displaying blank page on windows 7x ie 11

### ISSUE THREAD

**Issue by mffunes** [mozilla/pdf.js#7433]
Link to PDF file (or attach file here):
I can´t post a link since it contains sensitive information from our clients. But is a pdf with images scanned.
Configuration:
- IE 11
- Windows 7 32bits with Intel graphics card
 The driver versions are:
              T440: Intel 9.18.10.3272
              M83: 9.18.10.3220
              780: 8.15.10.2057
- PDF.js version: 1.4.20 / 1.5.188
- Is an extension: No, using default viewer

Steps to reproduce the problem:
1. On IE 11 advanced settings verify the option Use software rendering instead of GPU rendering is not checked
2.open the pdf js demo site and load a pdf with scanned images and text

What is the expected behavior? (add screenshot)
See the document
What went wrong? (add screenshot)
The document displays blank pages

Now if i check the option to use software rendering the document is displayed normally.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): default viewer

**Comment by Rob--W** [comment]
Please provide a PDF file that shows the problem. This bug report is not actionable in its current form.

**Comment by Snuffleupagus** [comment]
> On IE 11 advanced settings verify the option Use software rendering instead of GPU rendering is not checked

This sounds exactly like #5031, which is a browser/driver specific problem, and thus unfortunately not something that we'll be fix on the PDF.js side.

**Comment by mffunes** [comment]
I will close it for now to check the drivers and try to find a pdf i can share
