### ISSUE TITLE
Failed while loading the pdf 

### ISSUE THREAD

**Issue by puneet1301** [mozilla/pdf.js#7435]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: IE 11 
- Operating system and its version:in WIN 2012 and WIN 7
- PDF.js version:var pdfjsVersion = '1.4.20';
                          var pdfjsBuild = 'b15f335';
- Is an extension: pdf.worker and compatibility.js

Steps to reproduce the problem:
1. Load the html page and it fails with following exception:
Access denied in xhr.open line of the pdf.worke
unable to open the pdf file.
What is the expected behavior? Load the pdf

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by puneet1301** [comment]
![error](https://cloud.githubusercontent.com/assets/20128525/16339553/fb137938-3a40-11e6-8516-0e6d872e5d85.png)
Uploaded the file

**Comment by puneet1301** [comment]
Renamed the caller html file to txt and uploaded. kindly help
[adminguide.txt](https://github.com/mozilla/pdf.js/files/331837/adminguide.txt)

**Comment by timvandermeij** [comment]
I think the error is pretty clear: access denied, so it cannot access your file. Make sure that the PDF is exactly at the path where you say it is and use the developer tools' network tab to check why the file cannot be loaded. It could be anything, for example permissions. If you are loading a PDF file from another server, you need additional server configuration: see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request.

Closing for now.
