### ISSUE TITLE
PDF.js as MODAL

### ISSUE THREAD

**Issue by webdrifter** [mozilla/pdf.js#7436]
Open PDF file in Gmail. It does not replace the page and acts as a full width modal. User can still see the background and get back to the page. It looks really nice and:
1) Closes when you click on the close button on the top right
2) Closes when you press Esc key.
3) Closes when you click on the background

Is there a way to make pdf.js display the same way? Currently pdf.js only way to get back to the page is use "Back" - either browser back or Backspace. Not sure user understands he is still on the website.

**Comment by yurydelendik** [comment]
The browsing experience in the browsers (with pdf.js extension) is consistent with browsers without pdf.js -- it opens pdf as regular web page. Gmail is a custom app that provides overlay with pdf images. You easily implement the same effect with iframe and demo viewer in your app. Closing as won't fix.
