### ISSUE TITLE
PDF.JS Firefox extension unsigned again (stuck on June 15 at v1.5.296)

### ISSUE THREAD

**Issue by pal1000** [mozilla/pdf.js#7449]
Link to PDF file (or attach file here): N/A
Configuration:
- Web browser and its version: Firefox 47.0 Relese channel x64
- Operating system and its version: Windows 10.0.10586 Home x64
- PDF.js version: 1.5.296
- Is an extension: Yes

Steps to reproduce the problem:
-Attempting to update the extension results on extension not being verified error, subsequent attempts result in extension considered up-to-date. 
-Manual upgrade shows the same extension not verified error .

What is the expected behavior? (add screenshot)
Extension should upgrade successfully.

**Comment by timvandermeij** [comment]
/cc @yurydelendik 

Might that have something to do with the botio issue we had recently?

**Comment by yurydelendik** [comment]
Interesting that on the AMO it got signed without issue. Checking more, could be a timeout.

**Comment by Snuffleupagus** [comment]
Would it perhaps help if we increased [this `timeout`](https://github.com/mozilla/botio-files-pdfjs/blob/12db806dff1adaa5bdc679ea0a18a0b41991ae5c/signxpi.js#L113) to e.g. ten minutes instead?

**Comment by yurydelendik** [comment]
Regression from #7437, fixed by https://github.com/mozilla/pdf.js/commit/3cba2cb2584028c7a1f18a33a62898a80fe74608.

For future, https://addons.mozilla.org/en-US/firefox/pages/appversions/ shall be used as a reference.

**Comment by Snuffleupagus** [comment]
Sorry about breaking this, and thanks for fixing it!
