### ISSUE TITLE
Inconsistent naming: Fit Page/Full Width vs Page Fit/Page Width

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#7452]
Review from the Chrome Web Store (but this bug applies to all builds):

> First of all, THANK YOU SO MUCH! This extension is freaking awesome! Anyway, I discovered a naming inconsistency in the extension. In the Options menu, you have the "Default zoom level" option. One of the options is "Full Width." But when you actually open a PDF, the zoom level that corresponds to that is called "Page Width." You may wish to consider calling both of these the same thing to prevent confusion. I would actually recommend changing both to say "Fit Width" instead, so it uses the same terminology as Adobe.

"Page Fit" and "Page Width" was renamed to "Fit Page" and "Full Width" in 3d435768385e567c908b201fd9d894b85b07c275, in viewer.html. However, the translations never changed. When I created `options.html`, I based the strings on viewer.html, hence the inconsistency spotted by a very sharp user.

There are two options here:
- Update l10n files to use "Fit Page" and "Full Width".
- Update web/viewer.html and `extensions/chromium/options/options.html` to use "Page Fit" and "Page Width".

**Comment by Rob--W** [comment]
I think that we should do this:

> * Update `web/viewer.html` and `extensions/chromium/options/options.html` to use "Page Fit" and "Page Width".

So, in both files:

- Replace the "Fit Page" string with "Page Fit"
- Replace the "Full Width" string with "Page Width"

**Comment by nish17** [comment]
May I work on this? will you please assign it to me?

**Comment by Rob--W** [comment]
@nish17 It's all yours.
