### ISSUE TITLE
PDF.js v1.4.237 (build: e9dbb23) Unexpected server response (204)

### ISSUE THREAD

**Issue by yudipras** [mozilla/pdf.js#7456]
PDF.js v1.4.237 (build: e9dbb23)
Message: Unexpected server response (204) while retrieving PDF

pdf can not be loaded, while I am retrieving pdf from my own server.

It can't work on mozilla firefox 47.0.1 but it work well on chrome  51.0.2704.103

it become autodownload by idm when I am using mozilla.

Any suggestion?
help please :'D

**Comment by timvandermeij** [comment]
Make sure you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md to know what you must provide before opening an issue. At the very least a link to a working example (if it is a custom solution) is required for us to debug the issue. Closing until this is provided.

**Comment by xpf7622** [comment]
I also meet the problem,: "Message: Unexpected server response (204) while retrieving PDF"

**Comment by Abdulmanan0315** [comment]
Was about to post the same issue with the v2.0.943 (build: dc98bf76) and read the comment of @ravibpatel  and finally it solved.
To solve this issue one should disable File manager or **refrain them from capturing download links from web players** .

**Comment by faridsh69** [comment]
When you are using this package in local hold ALT key on keyboard, then IDM will not download that link.

**Comment by makantr17** [comment]
I had the same issue but to fix it, I make sure that the path to the pdf is correct, and I disabled the IDM file as suggested above.

**Comment by makantr17** [comment]
I had the same issue but to fix it, I make sure that the path to the pdf is correct, and I disabled the IDM as suggested above.

**Comment by LukeM-97** [comment]
Thank you, this fixed my issue too
