### ISSUE TITLE
Extract embedded Xml file from PDF using javascript

### ISSUE THREAD

**Issue by anantapl** [mozilla/pdf.js#7459]
I Have a pdf which has an embedded xml file.

I want to Extract and read the data from xml file which is embedded with PDF using javascript. 
Please help me to do so. and I want to know that can it be done using pdf.js.

**Comment by timvandermeij** [comment]
PDF.js is able to parse the PDF file, so you could probably write something to extract that. If it is an attachment then there is already support for that, otherwise you have to write it youself. Closing as answered.

**Comment by anantapl** [comment]
I dont want to extract PDF file, i want to extract XML file which is embedded or attached with the PDF and I have the PDF, Can i extract the data from xml file @timvandermeij ?

**Comment by timvandermeij** [comment]
Yes, that's what I said. PDF.js parses the PDF file and is able to give you the data of the XML file, probably as a `FileSpec` dictionary.

**Comment by anantapl** [comment]
Thanks Can you please share code for extracting embedded xml file in php using pdf.js

**Comment by timvandermeij** [comment]
PDF.js is written in JavaScript, so PHP will not be of much use here. There is already support for attachments, but you will have to write other code yourself as we do not provide support for writing custom solutions.

**Comment by anantapl** [comment]
Ok thanks.
