### ISSUE TITLE
Is there any onPageChanged action listener?

### ISSUE THREAD

**Issue by EvgenyKislyy** [mozilla/pdf.js#7461]
Hello. 
I want to track page selection and do something in my code when it happens. 
Is there any eventListener, something like onPageChanged(callbackFunction)?

**Comment by yurydelendik** [comment]
PDFViewerApplication has eventBus and it has "pagechange" (it's new API). In old viewer, there was document DOM event with the same name (see https://github.com/mozilla/pdf.js/blob/master/web/dom_events.js#L52). Closing as answered.
