### ISSUE TITLE
Question: render partial pdf file instead of the whole pdf?

### ISSUE THREAD

**Issue by chunyenHuang** [mozilla/pdf.js#7464]
Link to PDF file (or attach file here):
[test center.pdf](https://github.com/mozilla/pdf.js/files/344030/test.center.pdf)

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: OS X 10.10.5
- PDF.js version: pdfjs-dist@^1.5.296
- Is an extension: No

Hello pdf.js team,
Thank you for your amazing work! I just start to use pdf.js from last month, it is truly incredible.

I wonder if there is any way to render partial pdf without scanning through the whole pdf. 

I want to only render the center box from original pdf file
<img width="648" alt="screen shot 2016-07-01 at 12 10 00 pm" src="https://cloud.githubusercontent.com/assets/12788155/16532140/d246a84c-3f84-11e6-86c1-9087ade89792.png">
Will be rendered like this:
<img width="315" alt="screen shot 2016-07-01 at 12 10 08 pm" src="https://cloud.githubusercontent.com/assets/12788155/16532134/cc7974b2-3f84-11e6-8743-627bd29689d7.png">
_The case is I try to render the Commendation PDF files without showing the borders._

**I can now achieve this by modifying the PageViewport(constructor) and Canvas Size.** 
However, some pdfs are rasterized with big sizes. Even I only render very center(1/10 width and height),  the total rendering time is almost the same as I render the whole pdf. 
Is there any way to just select a field in the pdf and render it?( or it is actually how pdf.js works =~=).
I browsed the issues and couldn't find enough information. If it is possible, please give me some hint, so I can keep digging!

Thanks for reading my question, I appreciate so much!

This is the code where I calculate the rendering time.
`````
    render: function PDFPageProxy_render(params) {
      var start = window.performance.now();
      .....
      .....
      var end = window.performance.now();
      var time = (end - start);
      console.log('%c rendering time: ' + time.toFixed(4) + 'ms', 'background: #9c0000; color: #fffdc7');
      }
      return renderTask;
    },
`````

**Comment by timvandermeij** [comment]
Cropping a PDF file is not supported by PDF.js. As you indicated, you could implement this yourself, but it will not speed up the rendering time of the PDF file. Even with range requests, you need a certain amount of data to be loaded to render a part of the PDF file. Unless you know where the parts of the PDF file you are interested in are in the file, you will not be able to render only a part of a page efficiently as far as I know.

**Comment by chunyenHuang** [comment]
Thanks for answering!

**Comment by yurydelendik** [comment]
Can be connected with tracked item "provide boundary to getOperatorList and discard objects/text from the list that are not in the boundary" at https://github.com/mozilla/pdf.js/issues/6419#issuecomment-191423489

**Comment by harshajayaweeraXHJ** [comment]
> Link to PDF file (or attach file here):
> [test center.pdf](https://github.com/mozilla/pdf.js/files/344030/test.center.pdf)
> 
> Configuration:
> 
> * Web browser and its version: Chrome
> * Operating system and its version: OS X 10.10.5
> * PDF.js version: pdfjs-dist@^1.5.296
> * Is an extension: No
> 
> Hello pdf.js team,
> Thank you for your amazing work! I just start to use pdf.js from last month, it is truly incredible.
> 
> I wonder if there is any way to render partial pdf without scanning through the whole pdf.
> 
> I want to only render the center box from original pdf file
> <img alt="screen shot 2016-07-01 at 12 10 00 pm" width="648" src="https://cloud.githubusercontent.com/assets/12788155/16532140/d246a84c-3f84-11e6-86c1-9087ade89792.png">
> Will be rendered like this:
> <img alt="screen shot 2016-07-01 at 12 10 08 pm" width="315" src="https://cloud.githubusercontent.com/assets/12788155/16532134/cc7974b2-3f84-11e6-8743-627bd29689d7.png">
> _The case is I try to render the Commendation PDF files without showing the borders._
> 
> **I can now achieve this by modifying the PageViewport(constructor) and Canvas Size.**
> However, some pdfs are rasterized with big sizes. Even I only render very center(1/10 width and height), the total rendering time is almost the same as I render the whole pdf.
> Is there any way to just select a field in the pdf and render it?( or it is actually how pdf.js works =~=).
> I browsed the issues and couldn't find enough information. If it is possible, please give me some hint, so I can keep digging!
> 
> Thanks for reading my question, I appreciate so much!
> 
> This is the code where I calculate the rendering time.
> 
> ```
>     render: function PDFPageProxy_render(params) {
>       var start = window.performance.now();
>       .....
>       .....
>       var end = window.performance.now();
>       var time = (end - start);
>       console.log('%c rendering time: ' + time.toFixed(4) + 'ms', 'background: #9c0000; color: #fffdc7');
>       }
>       return renderTask;
>     },
> ```

Can you provide a code sample how you did it?
