### ISSUE TITLE
when on full screen, header and footer of the site is visible on Chrome

### ISSUE THREAD

**Issue by kushvarma** [mozilla/pdf.js#7470]
Configuration:
Chrome latest version
- OS X latest, Windows 7,8,10
- PDF.js version: 1.4.20

Steps to reproduce the problem:
1. When I go in presentation mode in Chrome browser it shows header and footer of the site on the full screen mode. 

What is the expected behavior? (add screenshot)
It should not show any header or footer. It works fine on IE, firefox.

I cannot share the link where I am getting this issue. But is this a known issue?

**Comment by timvandermeij** [comment]
PDF.js makes use of the fullscreen API that the browser exposes, so if there is an issue with this it should be reported at the issue tracker for Chrome. I have not heard about this before, though, and there are no screenshots to see what you mean.
