### ISSUE TITLE
PDFJS fails to print on Awesomium

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#7472]
I'm trying to print a PDF file on Awesomium 1.7.5 on Windows 7 x64 using PDFJS (stable version 1.4.20).

I'm using WPF to launch the browser and PDFJS is loaded as an internal resource (.pak file) via an "asset://" protocol (defined by Awesomium)

Any PDF file is rendered properly by using method PDFViewerApplication.open(bytearray) since the PDF is obtained through an array of bytes. Nevertheless, when I print executing Javascript function "window.print()" blank pages are printed.

**Comment by Snuffleupagus** [comment]
> I'm using WPF to launch the browser and PDFJS is loaded as an internal resource (.pak file) via an "asset://" protocol (defined by Awesomium)

This particular setup appears "special" enough to warrant pointing to https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Furthermore, it seems unlikely that this is really a PDF.js bug; closing as INCOMPLETE/INVALID?
