### ISSUE TITLE
How do I include compatibility.js?

### ISSUE THREAD

**Issue by yamizukin** [mozilla/pdf.js#7476]
Using base64 encoded content as a PDF file.

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 7
- PDF.js version: 1.5.314

Steps to reproduce the problem:
1. Read FAQ; read "include compatibility.js" to solve IE errors
2. Assume it means "include as dependency in module," use an "import" statement, or include as 
`<script` src="compatibility.js">` (condensed); run out of ideas.

What is the expected behavior?
My goal is to get this working in IE and Chrome via a webpack application. I inherited the code from someone else; strangely, it works in Chrome without including it as a dependency anywhere in the code.
![image](https://cloud.githubusercontent.com/assets/3587911/16625371/d73d100a-4369-11e6-9edb-a22cf14f5271.png)
Importing compatibility.js as an import statement ("import 'compatibility.js'" in our directive) doesn't affect it.

What went wrong?
In IE 11, it appears to render the canvas but nothing is inside it.
![image](https://cloud.githubusercontent.com/assets/3587911/16625494/7cdb1bec-436a-11e6-9cf9-128028c36cc4.png)
There are no errors in the console.

Including compatibility.js through `<script src="compatibility.js">` causes this error, in both browsers:
![image](https://cloud.githubusercontent.com/assets/3587911/16625434/308f7738-436a-11e6-8f15-faf74291145d.png)
Thsi prevents the canvas from loading at all; the page is blank.

Given all the FAQs state to include compatibility.js to solve IE issues and I'm the only person having IE issues, getting the import correct would fix all my problems... in theory. What is the right way to include compatibility.js?

The only other thing I can imagine is that there are issues with base64 content and IE11, as I'm unable to download this PDF through a different module. I've read both that it's (nearly) impossible to download a normal PDF in base64 in IE due to its size, and it also seems others got this to work without issues. I'll keep trying things, but please help me find the right direction.

**Comment by yamizukin** [comment]
Put more concisely: I downloaded the example from here and tried the webpack version. With or without any inclusion of compatibility.js (using "require" instead of "import" in this case), Chrome has no issues, after disabling web security. IE renders a blank page with no errors in both cases.

**Comment by yurydelendik** [comment]
Based on your comments you are introducing invalid HTML markup `<script src="compatibility.js">` vs `<script src="compatibility.js"></script>`, but it's hard to tell without entire example.

We cannot solve the issue without concrete example(s) online. Closing as incomplete.
