### ISSUE TITLE
How to display 2 pdf file on 1 html view page?

### ISSUE THREAD

**Issue by jstft** [mozilla/pdf.js#7477]
Dear sires/madams

I would like to have 2 pdf file opening on 1 web view page w/ pdf.js, is there a method in pdf.js to resolve this issue?

Currently, the first pdf file got cancelled in runtime as the sec pdf starts loading, and console log display:

1st PDF file -- stopped cancelled

2nd PDF file -- finished loading

How do I manually halt the sec pdf after 1st finished loading the renderPage(). I have searched for several days and only seen few post example relating to display all pages of 1 pdf file. 

Please provide a detail example of displaying multiple pdf files w/ pdf.js.

Thanx

**Comment by timvandermeij** [comment]
You cannot render multiple PDF files on one canvas. The only way to render multiple PDF files is to use multiple canvases and render each PDF on its own canvas using the example code in the `/examples` folder.

**Comment by dinamiqo** [comment]
Hello, timvandermeij! excuse me, but You will  could share the link to the example that mentions?

**Comment by timvandermeij** [comment]
The examples are located at https://github.com/mozilla/pdf.js/tree/master/examples. Take for instance the `helloworld` example.

**Comment by dinamiqo** [comment]
Ok, thanks. I try modify it to my necessities :)

**Comment by afuentes90** [comment]
Has anyone been able to display two pdf files with two viewers toolbars in one page?
