### ISSUE TITLE
UIWebview crash in ios with PDFJS

### ISSUE THREAD

**Issue by sravankumarp** [mozilla/pdf.js#7484]
I have loaded a pdf in a UIWebView using PDFJS in an iOS Applcation

All loading is fine, but the app crashes, when the user scrolls very fastly and when zoom. Up on debugging, I noticed that App received memory warning and crashed. 

Anyone faced this issue, how do we handle this scenario, so that app will not crash due to memory?

**Comment by yurydelendik** [comment]
As stated, duplicate of #5342
