### ISSUE TITLE
Callbacks to SelectText Events

### ISSUE THREAD

**Issue by nartz** [mozilla/pdf.js#7491]
I am embedding a pdf in a split pane window (pdf in one side, 'comments') in another - is there a way to register callbacks so that when users interact with the PDF (i.e. highlighting text) that I can register to this event? Does PDF js expose these types of event callbacks?

**Comment by timvandermeij** [comment]
PDF.js does not expose these callbacks as there generally people do not use such events, so you should implement it yourself for a custom solution. You could fire an event when `mouseup` or `mousedown` is detected for the text layer divs.
