### ISSUE TITLE
pdf.js watermark issue??

### ISSUE THREAD

**Issue by musicholic80** [mozilla/pdf.js#7503]
Steps to reproduce the problem:
**1. pdf.js**
![image](https://cloud.githubusercontent.com/assets/20637533/17094787/4cc1e586-528c-11e6-9cb6-0ee4cb2c6ee9.png)

**2.org file** 
![image](https://cloud.githubusercontent.com/assets/20637533/17094714/f8db48f4-528b-11e6-9b20-f8d26a71f47c.png)

**font or color issue??**

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, *especially* a PDF file that can be used to reproduce the problem!
As is, this issue will be closed as incomplete; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md.

**Comment by musicholic80** [comment]
download url : https://github.com/mozilla/pdf.js/archive/gh-pages.zip
watermark no display

**Comment by Snuffleupagus** [comment]
> download url : https://github.com/mozilla/pdf.js/archive/gh-pages.zip
> watermark no display

I'm sorry, but the above does not provide us with the necessary information!
Again, you need to provide the *actual PDF file*, i.e. a file with the `.pdf` extension, that corresponds to the screenshots you posted above. (And preferably also provide information about your configuration, as requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by musicholic80** [comment]
Web browser and its version: chrome, ie10
Operating system and its version: windows 8.1, windows server 2008
PDF.js version: 1.5.351

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/20637533/17120872/4f69eef4-530a-11e6-9dcf-f29ed4421311.png)

**Comment by timvandermeij** [comment]
The browser prevents using `file://` URIs. You'll have to serve the files using a web server (try `gulp server`) as indicated in https://github.com/mozilla/pdf.js#getting-the-code. Closing as solved based on the given information as the PDF file has not been provided.
