### ISSUE TITLE
Some of the Devnagri Fonts not being rendered properly

### ISSUE THREAD

**Issue by subbame** [mozilla/pdf.js#7507]
Link to PDF file:  [2007-01-SB_CMYK.pdf](https://github.com/mozilla/pdf.js/files/382169/2007-01-SB_CMYK.pdf)

**Configuration:**
- Web browser and its version: Chrome (Version 51.0.2704.103 m) and Mozilla Firefox 47.0
- Operating system and its version: Windows 10 Pro
- PDF.js version: 1.5.355
- Is an extension: N/A

**Steps to reproduce the problem:**
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the attached PDF (2007-01-SB_CMYK.pdf) file to reproduce the error.

**What is the expected behavior?**
I have attached correct display of the PDF file below which is showing up the text without any issue before being rendered by pdf.js
![before-being-rendered](https://cloud.githubusercontent.com/assets/14233772/17112353/62ba72f4-52c3-11e6-8070-abba1d135d9c.png)

**What went wrong?**
Some of the text are not being rendered properly. We are using SHREE-DEV Devnagri Fonts which are freely available at http://www.abstractfonts.com/search/shree-dev-0714%20download for download. I have included the screenshot of the PDF file which is being rendered incorrectly.
![fonts-issue-01](https://cloud.githubusercontent.com/assets/14233772/17112293/1bcd78a0-52c3-11e6-8080-435683b64376.png)

**Chrome Error Console Output:**

```
Warning: Failed to load font "g_d0_f2": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f4": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f6": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f10": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
Warning: Failed to load font "g_d0_f11": SyntaxError: Invalid font data in ArrayBuffer. pdf.js:277
```

**Comment by Snuffleupagus** [comment]
A more complete error message, from the Firefox console:
```
PDF 94eb7faf31644e43a33f25c9d8e3b37b [1.7 Adobe PDF Library 10.0.1 / Adobe InDesign CS6 (Windows)] (PDF.js: 1.5.355)viewer.js:7880:7
downloadable font: glyf: Bytecode length too high 135 (font-family: "g_d0_f2" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: glyf: Failed to parse glyph 19 (font-family: "g_d0_f2" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: rejected by sanitizer (font-family: "g_d0_f2" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: font load failed (font-family: "g_d0_f2" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
Warning: Failed to load font ""g_d0_f2"": SyntaxError: An invalid or illegal string was specifiedpdf.js:277:5
downloadable font: glyf: Bytecode length too high 166 (font-family: "g_d0_f4" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: glyf: Failed to parse glyph 36 (font-family: "g_d0_f4" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: rejected by sanitizer (font-family: "g_d0_f4" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: font load failed (font-family: "g_d0_f4" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
Warning: Failed to load font ""g_d0_f4"": SyntaxError: An invalid or illegal string was specifiedpdf.js:277:5
downloadable font: glyf: Bytecode length too high 158 (font-family: "g_d0_f6" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: glyf: Failed to parse glyph 36 (font-family: "g_d0_f6" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: rejected by sanitizer (font-family: "g_d0_f6" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: font load failed (font-family: "g_d0_f6" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
Warning: Failed to load font ""g_d0_f6"": SyntaxError: An invalid or illegal string was specifiedpdf.js:277:5
downloadable font: glyf: Bytecode length too high 123 (font-family: "g_d0_f10" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: glyf: Failed to parse glyph 20 (font-family: "g_d0_f10" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: rejected by sanitizer (font-family: "g_d0_f10" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: font load failed (font-family: "g_d0_f10" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
Warning: Failed to load font ""g_d0_f10"": SyntaxError: An invalid or illegal string was specifiedpdf.js:277:5
downloadable font: glyf: Bytecode length too high 182 (font-family: "g_d0_f11" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: glyf: Failed to parse glyph 45 (font-family: "g_d0_f11" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: rejected by sanitizer (font-family: "g_d0_f11" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
downloadable font: font load failed (font-family: "g_d0_f11" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)(unknown)
Warning: Failed to load font ""g_d0_f11"": SyntaxError: An invalid or illegal string was specifiedpdf.js:277:5
```

The errors thus point to the `glyf` data validation in OTS, in particular [src/glyf.cc#L101-L108](https://github.com/khaledhosny/ots/blob/56b9be8baddeb52ef15ec742bfcbf8e8df2ab681/src/glyf.cc#L101-L108).

Interestingly, if we called `sanitizeGlyphLocations` with `hintsValid = false`, see [src/core/fonts.js#L1644-L1646](https://github.com/mozilla/pdf.js/blob/336b26a39dc304fc589d0cfb85c52e7d4ee85112/src/core/fonts.js#L1644-L1646), this would just fix things.
I'm wondering if `sanitizeTTPrograms`, see [src/core/fonts.js#L2084](https://github.com/mozilla/pdf.js/blob/336b26a39dc304fc589d0cfb85c52e7d4ee85112/src/core/fonts.js#L2084), is somehow failing to detect that the fonts aren't well formed!?

**Comment by ash-recommind** [comment]
I get a very similar warning/error when loading the attached PDF
[TheBlueLights_chapter1_DIE_ZWEITE_UND_LÄNGERE_VERSION.PDF](https://github.com/mozilla/pdf.js/files/1323725/TheBlueLights_chapter1_DIE_ZWEITE_UND_LANGERE_VERSION.PDF)
into the viewer.
As a result the PDF is rendered using a different (probably some kind of default) font.

Chrome (Version 60.0.3112.113 (Official Build) (64-bit)) console output :
`Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.`

Firefox (55.0.3 (32-bit)) console output:
```
downloadable font: rejected by sanitizer (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

downloadable font: font load failed (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

In IE10 and IE11 the PDF seems to be loading without any font loading issue - at least there are no font-related warnings/errors in the JS console and in turn the PDF is rendered similar to if you open it in e.g. Adobe Reader.

Used OS: Windows Server 2012 and Windows 10

This is reproducible with the latest pdf.js demo pages: https://mozilla.github.io/pdf.js/web/viewer.html

What's causing this kind of font loading error and is there a chance that this gets fixed any time soon?

**Comment by brendandahl** [comment]
@ash-recommind please open a new issue, yours is probably different.

**Comment by ash-recommind** [comment]
@brendandahl, I asked to reopen #8623, see [this comment](https://github.com/mozilla/pdf.js/issues/8623#issuecomment-331142687)

But @timvandermeij pointed out that there are already open tickets for my issue.
Hence I picked this ticket and added my information, because to me it seemed to match.

Now you're saying that I should open a new ticket.
What do you think about reopening #8623

**Comment by SamyCookie** [comment]
@ash-recommind Since #8955 has been merged now, could you now test your file with current dev PDF.js https://mozilla.github.io/pdf.js/web/viewer.html.
If your issue is still present, it's another one than the current issue ticket, so open a new issue ticket please.

**Comment by brendandahl** [comment]
@ash-recommind let's just open a new issue with your PDF. While the error is similar to other issues, it is likely a very different problem. I'd rather not re-open #8623 since it is an incomplete report.

**Comment by ash-recommind** [comment]
Done: Created ticket #8960
