### ISSUE TITLE
Rendering error in italian pdf if font is missing (IE9-11)

### ISSUE THREAD

**Issue by gitarossrac** [mozilla/pdf.js#7508]
Link to PDF file (or attach file here):
[_Informazioni sulle perfomance del team.pdf](https://github.com/mozilla/pdf.js/files/383628/_Informazioni.sulle.perfomance.del.team.pdf)

Configuration:
- Web browser and its version: IE9-11
- Operating system and its version: Windows 10
- PDF.js version: 1.4.20
- Is an extension: no

Steps to reproduce the problem:
1. Not sure. Try to open the pdf when you don't have the font. (embeding it didn't help)
2.

What is the expected behavior? Renders correctly.

What went wrong? see screenshot
![brokenpdf](https://cloud.githubusercontent.com/assets/11339199/17135267/b8a90f3c-5326-11e6-8596-652c51ba95b2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Renders correctly for me with Arch Linux, but I have manually installed Arial fonts before. According to Okular the TrueType Arial fonts are not embedded.

**Comment by Snuffleupagus** [comment]
*Updating the labels, since Arial isn't really a non-standard font ;-)*

> Operating system and its version: Windows 10

It seems kind of weird that the latest version of Windows wouldn't include standard fonts such as e.g. Arial.

**Comment by gitarossrac** [comment]
It works on most Windows 10 and Windows 7 machines with all types of IE and Edge.
I'm assuming font problem because of the Italian special characters. And also because changing the font to Times New Roman solved the issue.

**Comment by gitarossrac** [comment]
Hi Gentle people,
Could you make some investigation on this one?
Please let me know if you need any info about it.

**Comment by ArthurZhan** [comment]
I am using Window 7 + IE11  show the pdf is well

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
