### ISSUE TITLE
update pdf.js from 1.1.3 to 1.5.355, PDFJS.AnnotationUtils is undefined'

### ISSUE THREAD

**Issue by FahadQurashi49** [mozilla/pdf.js#7509]
I have updated pdf.js from 1.1.3 to 1.5.355, it gives me error 'PDFJS.AnnotationUtils is undefined', I have been searching all over to what use instead of this, I was using this property to get html of annotations: 

`page.getAnnotations().then(function (annotationsData) {
...
for (var i = 0; i < annotationsData.length; i++) {
                        var data = annotationsData[i];
                        var element = PDFJS.AnnotationUtils.getHtmlElement(data);
... // use element in my code
}
}`

kindly help

**Comment by yurydelendik** [comment]
Undocument PDFJS.AnnotationUtils was refactored to create public API for PDFJS.AnnotationLayer (see #6714). Your description does not provide complete example, so it's hard to if it's a good replacement for you. Closing for now as answered.
