### ISSUE TITLE
Zoom should be centered

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7512]
Currently when zooming the page-scroll stays the same.
The expected behavior should be a centered zoom to the middle of the viewport. (Example: Google Maps)

A scrolling, according to viewport, needs to be added.

Initial situation:
<img width="1127" alt="bildschirmfoto 2016-07-28 um 16 59 48" src="https://cloud.githubusercontent.com/assets/5103210/17217559/07710556-54e5-11e6-9b8b-561d9b72739f.png">

Current behavior:
<img width="1125" alt="bildschirmfoto 2016-07-28 um 17 01 03" src="https://cloud.githubusercontent.com/assets/5103210/17217563/09c95420-54e5-11e6-86ce-553ad66652ca.png">

Expected behavior:
<img width="1124" alt="bildschirmfoto 2016-07-28 um 17 03 59" src="https://cloud.githubusercontent.com/assets/5103210/17217634/4d3ad67a-54e5-11e6-85d1-61c756993323.png">

**Comment by Snuffleupagus** [comment]
The behaviour you describe is used when zooming is done with a mouse or trackpad (using
<kbd>Ctrl</kbd>+`scroll wheel`/`trackpad`).

> A scrolling, according to viewport, needs to be added.

However, I do *not* agree that *all* zooming (e.g. with the toolbar buttons) should behave that way.
Compare with with desktop PDF viewers such as e.g. Adobe Reader, which handles zooming similar to PDF.js. In my opinion, this issue is won't fix.

**Comment by MickL** [comment]
To zoom to something specific the user has to do: zoom, scroll, zoom, scroll, ... which is very unhandy.

Similar "big" software that zooms into center on zoom-in-button click:

- Google Maps
- Apple Preview

**Comment by dasilvacontin** [comment]
I'm having this problem as well. Also, looking forward to adding mobile-zoom via pinch, it's necessary that pdf.js can zoom using any point as the zoom's center.

**Comment by Snuffleupagus** [comment]
> Also, looking forward to adding mobile-zoom via pinch,

That's already tracked in issue #2582.

---

Closing as WONTFIX, given the points mentioned in https://github.com/mozilla/pdf.js/issues/7512#issuecomment-235929489.
