### ISSUE TITLE
The printed document is pixelated  

### ISSUE THREAD

**Issue by IonicaBizau** [mozilla/pdf.js#7517]
Link to PDF file (or attach file here): http://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chromium 51.0.2704.79 Ubuntu 16.04 (64-bit), Firefox 47.0 
- Operating system and its version: I've tested on Ubuntu 16.04, Ubuntu Server 16.04
- PDF.js version: latest
- Is an extension: no

Steps to reproduce the problem:
1. Open http://mozilla.github.io/pdf.js/web/viewer.html
2. Click the print button.
3. Print the document

What is the expected behavior? (add screenshot)

To get the clear document text, like opening the pdf natively on Chrome:

![image](https://cloud.githubusercontent.com/assets/2864371/17341449/519406ee-58fd-11e6-8327-e3de7b920fc5.png)
 

What went wrong? (add screenshot)

The print preview and the printed document using a physical printer are pixelated.

![image](https://cloud.githubusercontent.com/assets/2864371/17341471/75dd233c-58fd-11e6-8600-03ee65ac4f46.png)

---

I **did see** that there are lots of related issues, but is there a simple solution/workaround?

**Comment by Snuffleupagus** [comment]
> I did see that there are lots of related issues, but is there a simple solution/workaround?

The only simple workaround would be increase [`PRINT_OUTPUT_SCALE`](https://github.com/mozilla/pdf.js/blob/39412e5acec1edcf97954029b20154788eccdb18/web/pdf_page_view.js#L541). (Note that doing so will increase the memory consumption quite a lot during printing, which is why the default is what it is.)
Since there's a number of already existing open issues regarding print quality, I'm closing this one as answered.

**Comment by IonicaBizau** [comment]
@Snuffleupagus I did try that and there was no change, except it was slower.

**Comment by timvandermeij** [comment]
Try making the canvas twice as large. At https://github.com/mozilla/pdf.js/blob/39412e5acec1edcf97954029b20154788eccdb18/web/pdf_page_view.js#L538 change `1` to `2`. AFAIK the print output scale is nothing but a resize, which could make the canvas look blurry.
