### ISSUE TITLE
View PDF pages quickly before whole source PDF file downloaded

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7518]
It seems the whole source PDF MUST be downloaded before render.
When source PDF is too big and bandwidth not enough, it'll wait for a long time.
Is there any way to view PDF as input stream OR just get a part of source PDF data and quickly render?

**Comment by timvandermeij** [comment]
This is default in PDF.js and is called chunked rendering. The server must enable range requests. If it does and the PDF is created properly, pages can be loaded before the entire document is downloaded. Closing as answered.
