### ISSUE TITLE
how to ajust the toolbar Button icon size 

### ISSUE THREAD

**Issue by kevin3566** [mozilla/pdf.js#7524]
Configuration:

    Web browser and its version: Chromium 51.0.2704.79 , Firefox 47.0,
    Operating system and its version:Windows7
    PDF.js version:latest
    Is an extension:no

What is the expected behavior? (add screenshot)

the toolbar Button icons  seem too small for mobile device viewer
i wanna make them larger for better viewing experience
may i have any advice on this?

**Comment by timvandermeij** [comment]
You may use the `@2x` images that are larger (for example https://github.com/mozilla/pdf.js/blob/master/web/images/toolbarButton-print%402x.png). You'll need to adjust the CSS to use those instead and increase the size of the buttons there. Closing as answered.
