### ISSUE TITLE
Progressive loading not working while loading pdf from another domain.

### ISSUE THREAD

**Issue by kishanj918** [mozilla/pdf.js#7531]
When i load pdf within my domain, progressive loading is working. But when i load pdf from another domain i am getting **Refused to get unsafe header "Accept-Ranges"** error.
![screen shot 2016-08-08 at 10 23 50 am](https://cloud.githubusercontent.com/assets/3994657/17469615/5c574fd8-5d52-11e6-96fb-02192ce50401.png)

**Comment by Snuffleupagus** [comment]
This sounds like a CORS issue, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr. Closing as answered.

**Comment by kishanj918** [comment]
@Snuffleupagus  i have added cors config in my subdomain(media.docstub.com),still progressive loading is not working. My configs are as follow. and link to webpage is [https://www.docstub.com/doc/212/lic-model-paper-ii](url).  Can you help? thanks!

```
location / {
                try_files $uri $uri/ =404;
                add_header 'Access-Control-Allow-Origin' 'https://www.docstub.com';
                add_header 'Access-Control-Allow-Methods' 'GET';
                add_header 'Accept-Ranges' 'bytes';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Headers' 'Range';
                add_header 'Access-Control-Expose-Headers' 'content-range, content-length, accept-ranges';

        }
```

**Comment by pravid** [comment]
Is there any solution yet?
I'm loading PDF from different domain. It is loading the PDF fine but not in chunks. It loads full PDF at one go.

**Comment by zsybupt** [comment]
I have the same problem? any solutions?

**Comment by zsybupt** [comment]
It loads full pdf instead of loading chunk by chunk when do cors request

**Comment by zsybupt** [comment]
@pravid  see #3150 , I solved this by add ExposedHeaders

**Comment by pravid** [comment]
@zsybupt Thanks for informing. I tried adding expose header to my file but it is not working. I'm using rackspace cloud. Below are the headers I have set,

> Content-Type: application/pdf
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Range
> Access-Control-Allow-Methods: POST, GET, OPTIONS
> Access-Control-Allow-Origin: *

What do I'm missing?
