### ISSUE TITLE
Missed locales translation for "Page Width" button on hovering?

### ISSUE THREAD

**Issue by Kateryna-Baranovska** [mozilla/pdf.js#7535]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Firefox 47.0.1 (Chrome 52.0)
- Operating system and its version: Windows 7
- PDF.js version: 1.4.20
- Is an extension: No, used as inner plugin in web-site

Steps to reproduce the problem (actually, I can provide exactly steps, but will describe the whole situation):
In my web-site I have ability to add different content and display it on the UI. For example, I add some pdf file and open it using en-US locale - everything is working fine. But if I change the locale, for example on Spanish (or Arabian or Germany) and hover on the button "Page Width" - the translation doesn't appear and I still see english translation instead of chosen one. 
I looked into the inner code of each viewer.properties in locale folder and found out that field "page_scale.title={..translation..}" everywhere was missed (shown on the screenshot), but in previous our version of pdf (1.0.473) it existed.
Could you please tell me - is this an issue or it just my locally problem?

What is the expected behavior? (add screenshot)
On hovering to the "Page Width" button translation should be the same as the locale.

What went wrong? (add screenshot)
On the screenshot I opened two versions (old: 1.0.473 and new: 1.4.20) in Total Commander and compared its content and here is deleted line:
![comparison](https://cloud.githubusercontent.com/assets/10024414/17554870/b307273a-5f15-11e6-920d-5c71fd4948a3.png)

Thank you in advance.

**Comment by yurydelendik** [comment]
There is no "Page Width" button in the demo viewer. The select control has the "zoom" localization id (so "zoom.title" will have control's tooltip localization). We did not provide the title attributes for the select options. Also there is no control with "page_scale" localization id. Closing as answered.
