### ISSUE TITLE
Print IE - Mozilla very slow on this pdf

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#7536]
We are facing an issue when printing this doc on IE 11 or Mozilla. In chrome no problem.
On print preparation the temp file has a huge size.
There are also some AcroForms in this doc. I know that this library doesn't really manage AcroForms but I don't know if it is the problem. 
If you have any idea of how to solve this problem, i attach the PDF : 
Link to PDF file (or attach file here):
[doct_ref_2010_0.pdf](https://github.com/mozilla/pdf.js/files/411273/doct_ref_2010_0.pdf)

Configuration:
- Web browser and its version: IE 11 or Mozilla
- Operating system and its version: Windows - Ubuntu
- PDF.js version: 1.4.20
- Is an extension: no

Steps to reproduce the problem:
1. Open this file on these browsers
2. Print

What is the expected behavior? (add screenshot)
Preparation and size normal when printing like other docs 

What went wrong? (add screenshot)
The preparation is very slow (8% in 6 minutes)
![pdfjs](https://cloud.githubusercontent.com/assets/18471608/17557130/0ebc7eb8-5ee4-11e6-8c40-0f0ded41c72c.png)
the size of the temp PDF becomes huge

**Comment by Snuffleupagus** [comment]
First of all, at this point in time support for IE 11 is *very* limited.
Second of all, given the *limited* printing support in browsers, trying to print a PDF document with *many hundreds* of pages is unfortunately not going to work well in general. Hence I wonder if keeping this old issue open is meaningful? /cc @timvandermeij
