### ISSUE TITLE
Is there any better way to remove some top buttons? 

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7537]
Under some circumstances, we need to remove some top buttons, is there any better way to do it? e.g. configure it?

**Comment by timvandermeij** [comment]
Not really, since they are in the HTML at https://github.com/mozilla/pdf.js/blob/master/web/viewer.html. In a custom viewer, you either need to hide them when you are not using them or add them on demand, but both is out of scope for the regular viewer that we ship. Closing as answered.

**Comment by Snuffleupagus** [comment]
As a followup to https://github.com/mozilla/pdf.js/issues/7537#issuecomment-239422832, note that if you want to completely remove certain buttons from `viewer.html`, you should be able to do so by replacing the elements in question with a hidden dummy element in [`getViewerConfiguration`](https://github.com/mozilla/pdf.js/blob/94089960c04d7f59eb637d6dc63944115bbc539d/web/viewer.js#L53).

Also, as mentioned in e.g. http://mozilla.github.io/pdf.js/getting_started/ and https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#from-examples, the default viewer isn't intended to be used as is in custom deployments:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer.
*However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

**Comment by venkataraog** [comment]
Can I use this source for custom modifications like for example, I do modifications in viewer.html and viewer.js to disable Download and Print buttons then rebuild and use. I feel this is what custom means. 
Is this correct approach? Please guide me how to do in this case?

**Comment by shivanikoko** [comment]
> Can I use this source for custom modifications like for example, I do modifications in viewer.html and viewer.js to disable Download and Print buttons then rebuild and use. I feel this is what custom means.
> Is this correct approach? Please guide me how to do in this case?

@venkataraog  have you tried that approach did it work for you?

**Comment by faydanube** [comment]
> Can I use this source for custom modifications like for example, I do modifications in viewer.html and viewer.js to disable Download and Print buttons then rebuild and use. I feel this is what custom means.
> Is this correct approach? Please guide me how to do in this case?

pdfjs-2.7.570-dist, doesn't work~~~
