### ISSUE TITLE
Intermittent test failures after updating to Firefox 50

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#7542]
As can be seen in https://github.com/mozilla/pdf.js/pull/3891#issuecomment-238831677 and below, Firefox 50 causes intermittent test failures both when run locally *and* on the bots.
Especially the `tracemonkey-fbf` test is problematic, since it prevents `makeref` from completing successfully.

This appears to be a regression from [bug 1289380](https://bugzilla.mozilla.org/show_bug.cgi?id=1289380), according to https://github.com/mozilla/pdf.js/pull/3891#issuecomment-239390828:
>As mentioned on IRC, running [mozregression](http://mozilla.github.io/mozregression/) (on Windows) gave me the following range: https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=950a962b75eae61cb9f0c5638b6b362427f7ebe6&tochange=fc5b4f286716bf47199435415f945695c1c20d0b.
Given the commit message and the actual code this seems like a fairly reasonable regression range, but I'd be great if someone else could confirm that it's accurate.

/cc @brendandahl, @yurydelendik

**Comment by Snuffleupagus** [comment]
What we need to do here is:
 - [ ] Confirm that the regression range found above is correct.
 - [ ] Create a standalone, and preferably reduced, test-case in order to report the issue upstream.

**Comment by Snuffleupagus** [comment]
One a hunch I re-tested PR #7330, rebased to `master`, locally on Windows. That PR tries to address a Firefox specific intermittent issue outline in https://github.com/mozilla/pdf.js/issues/7188#issuecomment-211012375.

Interestingly enough, locally that patch actually prevents *all* the intermittent test failures that I'm seeing!
Since PR #7330 fixes an actual rendering issue, and that it seems to also help with this issue, I'd really like to get that landed to see if it helps on the bots as well.

/cc @brendandahl, @yurydelendik

**Comment by timvandermeij** [comment]
The patch is merged, so the intermittents should be resolved. I guess you want to keep this open for reporting it upstream?

**Comment by Snuffleupagus** [comment]
> The patch is merged, so the intermittents should be resolved.

Most of them are, but we still need https://bugzilla.mozilla.org/show_bug.cgi?id=1292870 as well.

**Comment by timvandermeij** [comment]
The upstream bug has been fixed and uplifted as well a few days ago, and after making new reference images today the tests do not fail intermittently anymore, so let's close this as fixed.
