### ISSUE TITLE
Area control problems

### ISSUE THREAD

**Issue by kimkwanho** [mozilla/pdf.js#7545]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:  explorer 10 / crome 52.0.2743.116 m (64-bit)
- Operating system and its version:
- PDF.js version:
PDFJS.version = '1.3.91';
PDFJS.build = 'd1e83b5';
- Is an extension: .pdf file

Steps to reproduce the problem:
1. I want to see the form of the horizontal.
2. I want to divide the region. 2 page by page.

What is the expected behavior? (add screenshot)
left, right button slide
![1](https://cloud.githubusercontent.com/assets/20715794/17690360/f1dc2174-63c8-11e6-9d91-87f711c7bbb9.png)

What went wrong? (add screenshot)
![2](https://cloud.githubusercontent.com/assets/20715794/17690374/15f041e4-63c9-11e6-9476-e49ef6520ac0.png)
Not the desired area.
How do I adjust the default settings of zoom?

pdf.js or viewer.js or viewer.css.
I do not know what to work on any part of yourself ...
This is desperately needed help and advice.

Thank you in advance.

**Comment by timvandermeij** [comment]
There is https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L471 for setting the zoom factor. Other than that, two-page views are hard because of varying page sizes. Since no demo is provided, we cannot do more here. Closing as answered.
