### ISSUE TITLE
Chrome: Invoking 'print()' during microtask execution is deprecated

### ISSUE THREAD

**Issue by yorl1n** [mozilla/pdf.js#7547]
This message :

> Invoking 'print()' during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

appears in console of Google Chrome (my Version 52.0.2743.116 m) trying to print pdf.
Just open example(http://mozilla.github.io/pdf.js/web/viewer.html ) page in Chrome and try to print it.

Unfortunately I didn't find anything regarding this issue in issues list. I'm afraid the print functionality will be broken after removing of deprecated functionality from chromium.

**Comment by timvandermeij** [comment]
/cc @Rob--W 

Do you know more about this Chrome change and what it will affect?

**Comment by yorl1n** [comment]
Unfortunately no. But I will try to contact feature owner.

**Comment by yorl1n** [comment]
Going to provided link there is a link to discussion (click FireFox icon in Consensus & standardization) https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/uMPT8II-G_c/CHFdj8unAgAJ
There are a little bit detailed discussion.

**Comment by timvandermeij** [comment]
Fixed in #7548.
