### ISSUE TITLE
The table borders are not visible

### ISSUE THREAD

**Issue by dhirugalaxy** [mozilla/pdf.js#7551]
Link to PDF file (or attach file here): PFA Chrome_Vector.pdf 
[Chrome_Vector.pdf](https://github.com/mozilla/pdf.js/files/424230/Chrome_Vector.pdf)

Configuration:
- Web browser and its version: Google Chrome Version : 52.0.2743.82
- Operating system and its version: Windows 8.1 Pro 64 bit
- PDF.js version: 1.5.385
- Is an extension: NA

Steps to reproduce the problem:
(1) Open https://mozilla.github.io/pdf.js/web/viewer.html
(2) Click on Open File button to open new PDF to view.
(3) Open the attachment file “Chrome_Vector.pdf”
(4) The table border is not displayed. This issue occurs only in google chrome 

Please find full issue description with screenshots in attached document "  Issue Description.docx 
[Issue Description.docx](https://github.com/mozilla/pdf.js/files/424239/Issue.Description.docx)
"

**Comment by dhirugalaxy** [comment]
This bug is also registered with Chrome issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=630964

They actually need some PDF.js knowledge of the part which is triggering this bug, If you could please collaborate and help, it would be great.

**Comment by yurydelendik** [comment]
Based on stepper info:
<img width="309" alt="screen shot 2016-08-29 at 7 53 06 am" src="https://cloud.githubusercontent.com/assets/1523410/18052028/afbf28be-6dbd-11e6-9c35-fbcef3b9b981.png">

It tries to paint line with 0.5 width, can this affect the painting on Chrome for Windows?

**Comment by dhirugalaxy** [comment]
can you please point out some snippet of just a few lines of PDF.js that demonstrates the bug. since we are stuck and not able to move forward.

**Comment by Snuffleupagus** [comment]
> can you please point out some snippet of just a few lines of PDF.js that demonstrates the bug. since we are stuck and not able to move forward.

I'd suggest that you try to extract the canvas drawing operations from PDF.js, by using a tool such as e.g. https://github.com/Rob--W/canvas-interceptor.

**Comment by timvandermeij** [comment]
Closing as fixed upstream.
