### ISSUE TITLE
Is possible to show the signature information and validation?

### ISSUE THREAD

**Issue by Gibran-16** [mozilla/pdf.js#7552]
Hello mates, I want to know if is possible to show information about each sign when clicking it or validate it?
I mean like in adobe reader when I click the signature shows the information and validation status.
The signature is visible.

Thanks.

**Comment by timvandermeij** [comment]
Closing as duplicate of multiple issues in https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-digital-signature.
