### ISSUE TITLE
outline sidebar and current position in sync

### ISSUE THREAD

**Issue by aleprovencio** [mozilla/pdf.js#7557]
What I mean is a visual indication on the outline sidebar of where you're currently browsing the document.  I find this very useful information and its a common behavior among other pdf viewers.

**Comment by reyou** [comment]
This is what I was looking for, it would be great following features to have:

1. Track following section on the side bar (where if I change the page, and go into new chapter, section, side bar will focus to that section with bold text)
2. Search in the side bar
3. Enable/Disable auto sidebar tracking. So if enabled it will auto focus on the sidebar, if disabled only if we hit "highlight on the sidebar" button will focus on current section on the sidebar.
4. API support for these :)

**Comment by TianTXie** [comment]
Yep, I need this feature too.

**Comment by devnoname120** [comment]
@timvandermeij Is this on the roadmap? I think that this feature would be a very nice thing to have.

**Comment by timvandermeij** [comment]
No, but anyone is welcome to work on this and submit pull requests for us to review.

**Comment by Snuffleupagus** [comment]
> No, but anyone is welcome to work on this and submit pull requests for us to review.

However, please keep in mind that implementing this in a way that won't perform badly (e.g. in larger documents) could be slightly challenging in general.
Hence I'm thinking that a *simpler* implementation, similar to what current versions of Adobe Reader does, is probably the way to go here (most of what https://github.com/mozilla/pdf.js/issues/7557#issuecomment-564618261 ask for is unlikely to be desirable).
