### ISSUE TITLE
How can I get a feedback after click printButton or cancelButton?

### ISSUE THREAD

**Issue by xingxiaoyiyio** [mozilla/pdf.js#7558]
Web browser:  Chrome 

I click printButton on `viwer.html`, then it triggers the browser method of `window.print()`,
it open a preview page.

Here is the problem: 
How can I get a feedback after click printButton or cancelButton on this preview page see blow?
because I need to execute a callback function after print success but not cancel printing.

![pages](https://cloud.githubusercontent.com/assets/17907566/17879726/d41d19d2-6926-11e6-8545-a41f7e3e53f5.png)

**Comment by Snuffleupagus** [comment]
You should be able to listen for the `afterprint` event (see https://developer.mozilla.org/en-US/docs/Web/Events/afterprint and https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint), which is the event that the viewer uses to cleanup after printing (in https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2312-L2314 and https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1167-L1180).

Closing as answered.

**Comment by xingxiaoyiyio** [comment]
thanks for your kindly reply, I have tried to listen for the afterprint event but that is not I really want, since afterprint event is fired when the printing dialog closed no matter I click print button or cancel print button at last on the open window of printing dialog.  

what make me puzzled is that the event window.print() has no any return value to let me know whether it print successful or cancel or stop printing. 

so how I can confirm my printing task really success but not be cancel at last?

**Comment by aqlu** [comment]
@xingxiaoyiyio Did you find a solution?
