### ISSUE TITLE
How to know when PDF rendering has partially failed

### ISSUE THREAD

**Issue by perttumyry** [mozilla/pdf.js#7562]
Is there a way to catch a case in which PDF rendering has partially failed? I can catch exceptions, but in some cases PDF.js only logs warnings into console and even those cases can be quite fatal for end user experience.

For example, we have one invoice PDF which gives the following warning in console.
`Warning: Failed to load font "g_d0_f2": SyntaxError: Invalid font data in ArrayBuffer.`

A screenshot of the outcome rendered in PDF.js version 1.5.188 in Chrome 52.0.2743.116 (64-bit) on Ubuntu 14.04 looks like this:
http://public.humap.com/images/pdf-font-loading-failed.png

Clearly the PDF is somewhat flawed. Still, some viewers can show the PDF properly (such as Chrome built-in PDF viewer and Ubuntu Document Viewer).

Instead of showing the flawed PDF in browser I would like to show an error message to user and provide just a link to download the PDF file. So how could I do that?

The original PDF file contains secure information, but I can deliver it to developers in case someone wants to take a look at this particular file.

**Comment by timvandermeij** [comment]
https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L254 is used to log the warning to the console. You might be able to throw a custom exception there and catch is elsewhere to abort rendering and display a message for the user.

However, this particular problem should not raise a warning IMO. Could you share the file here so we can take a look at what is causing the issue? If the invoice PDF contains sensitive data, would you be able to create a PDF file with the same issue but without the data in it?

**Comment by perttumyry** [comment]
I tested opening the file with latest viewer and fonts are messed there as well.

I tried to edit the PDF, but with every attempt to remove the sensitive data the new PDF file got broken so that it was messed up in every PDF viewer I tested. So unfortunately I was not able to create a version which doesn't contain the sensitive data.

In case someone wants to take a look at the original pdf, please drop me a message at perttu.myry@gmail.com and I can send you the file for testing purposes.

Tested and verified the problem with
- Browser: Chrome 52.0.2743.116 (64-bit)
- OS: Ubuntu 14.04 LTS (64-bit)
- PDF.js: 1.5.188

**Comment by perttumyry** [comment]
@THausherr kindly helped me and created a reduced version of the invoice PDF which doesn't contain any confidental information.

You can find the test pdf file at http://public.humap.com/pdf/PDFJS-7562-reduced.pdf

It only has word "Summa" in it which displays correctly when viewed with Ubuntu Document Viewer, but in PDF.js the content is scrambled.

**Comment by THausherr** [comment]
The font is indeed broken (the first 4 bytes are "true" instead of 0x00010000, and there's probably more); but I'm able to display the file with Adobe Reader, PDFBox, PDFRenderer, GSWin, IcePDF and JPedal.

**Comment by timvandermeij** [comment]
Interesting. Thank you @THausherr for helping out here!

**Comment by Snuffleupagus** [comment]
> The font is indeed broken (the first 4 bytes are "true" instead of 0x00010000, and there's probably more); [...]

Just based on this information you *cannot* conclude that the font is broken, since either `0x00010000` or `true` are actually valid TrueType font identifiers; please see https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html#ScalerTypeNote for additional information.
