### ISSUE TITLE
Print PDF on jQuery dialog

### ISSUE THREAD

**Issue by charlesen** [mozilla/pdf.js#7564]
Link to PDF file (or attach file here):

Configuration:
- Latest Chrome Version:
- Ubuntu 16.04.1 LTS:

I'm using PDF.js for loading document in a jQuery Dialog; but when I try to print document, I take the whole page. While I just want to focus on my document.

Do someone have an idea to solve this problem

Thanks for answers and (Sorry for my very poor english...From France with love :-) )

Charles

**Comment by timvandermeij** [comment]
As outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, we need a running demo to be able to look into the issue. Could you set it up somewhere (own server, JSBin, et cetera)?

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
