### ISSUE TITLE
Invalid annotation id: `[object Object]` in PDF exported from Google Drive

### ISSUE THREAD

**Issue by eXtreme** [mozilla/pdf.js#7569]
I encountered this problem while writing my custom pdf viewer with annotation support but the same issue is with PDF.js viewer html so my implementation is irrelevant. 

![bug0](https://cloud.githubusercontent.com/assets/197671/18005540/e3f403fe-6b9a-11e6-8f5a-4e65755fc31d.PNG)

Link to PDF file: [pdfbug.pdf](https://github.com/mozilla/pdf.js/files/439240/pdfbug.1.pdf)

The PDF file was created from Google Drive Presentation. There are 4 shapes with links (shapes are irrelevant). IDs for this annotations become `[object Object]` with PDF.js.

I have no knowledge of how PDF.js works internally but problematic ids are generated with this line: https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L188 where ref is converted to string, but it is an object so JS' `[object Object]` is produced. By setting a breakpoint there and printing `params.ref` we get this:
![bug1](https://cloud.githubusercontent.com/assets/197671/18005215/d8f6baa2-6b98-11e6-8b38-04c11de3aaf5.PNG)
While there should be a `Ref` object (from what I understand...).

I don't know any specialized PDF debugging tools, I tried PDFGears to browse objects and it looks like this:

(left: buggy pdf, right: normal pdf)
![bug2](https://cloud.githubusercontent.com/assets/197671/18005711/f9362bce-6b9b-11e6-9230-ab7492e9e16a.PNG)
I guess, the ID sits in square brackets, so obviously Google Drive Presentation PDF Exporter is broken here. But PDF.js should generate "some" id for such annotations, not `[object Object]`, right?

The example PDF can be minified (I guess), that was just a test file for my viewer, we can make it smaller and probably just use one shape/link.

Happens with latest chrome, firefox, Windows OS and macOS. Opening with Firefox' internal PDF viewer, the annotation id is just "undefined". PDF.js version? Latest, well the same as here: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
According to the PDF specification[1], the entries in an `Annots` dictionary should be indirect objects, and unfortunately this PDF file violates that.

---
[1] http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=86

**Comment by timvandermeij** [comment]
Thank you for reporting this and providing a detailed explanation of the issue, @eXtreme!

**Comment by timvandermeij** [comment]
This is fixed in PR #7570. @eXtreme If you have time, you might want to report this issue to Google too. The PDF file that you attached is obviously corrupt, so it would be good to notify Google too to prevent the creation of corrupt PDFs in the future. Also, the attached PDF file consistently makes Okular (on Linux) crash.

**Comment by eXtreme** [comment]
@timvandermeij @Snuffleupagus thanks, looks like it works now. :+1: Reported to Google as well.
