### ISSUE TITLE
Reset container to load a new one

### ISSUE THREAD

**Issue by marsuaga44** [mozilla/pdf.js#7571]
Hi! I am working on a project based on your mobile viewer example. The difference I made is that I load the pdf dynamically inside a jquery dialog when a user selects the file they want displayed. My problem is that if I click on a second file, seems like the data from the first loaded file is still there. Is there a way in which I can reset all data when I close the dialog?

**Comment by timvandermeij** [comment]
Destruction is done at https://github.com/mozilla/pdf.js/blob/master/web/app.js#L521 in the viewer. Destroying the loading task and resetting `pdfDocument` should be what you need.

**Comment by timvandermeij** [comment]
To make opening and closing documents easier, PR #7573 introduced a `close` method, which is asynchronous, just like `open` is now. Use `open`/`close` to correctly construct and destruct documents.

**Comment by redfox05** [comment]
@timvandermeij the line 521 now points to a totally different piece of code. Could you mention the function that is used? I will have a look at the close method in the meantime. I'm trying to clear out everything to allow the loading of a second document after the rendering of the first.
