### ISSUE TITLE
PDF renders correctly in Firefox but text is unreadable in Chrome 

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#7576]
Link to PDF file (or attach file here):
[Boards and Bees Company 8-5x11Trifold Inside pog copy.pdf](https://github.com/mozilla/pdf.js/files/443438/Boards.and.Bees.Company.8-5x11Trifold.Inside.pog.copy.pdf)

Configuration:
- Web browser and its version:
  Chrome 52 vs Firefox 48
- Operating system and its version:
  Windows 10
- PDF.js version:
  using https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension:

Steps to reproduce the problem:
1. load pdf in Chrome
2. load pdf in Firefox

What is the expected behavior? (add screenshot)
They should look the same

What went wrong? (add screenshot)
Text is unreadable in Chrome

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
I haven't see the rendering in chrome but here's a hopefully correct explanation: The glyphs are not created with the text operators but by clipping out shapes from a black image, **with no anti-aliasing**. GSWin, PDFBox, IcePDF and JPedal also render the file poorly.

Another file that uses this technique (in a different way) is this one (at the bottom, near the circled "1"):
https://issues.apache.org/jira/secure/attachment/12735315/PDFBOX-2814.pdf

Also:
https://issues.apache.org/jira/secure/attachment/12640944/experienced_java_developer.pdf
https://issues.apache.org/jira/secure/attachment/12533959/40376536.PDF

**Comment by paulodetarso** [comment]
And just to complement, here are some images that ilustrate the problem. When we are viewing a PDF with "pdf.js", ok, normal (step-1.jpg). After open some file on new tab (step-2.jpg), when we back, we can see these black blocks (step-3.jpg)
![step-1](https://cloud.githubusercontent.com/assets/4804498/18141832/7ae06fec-6f91-11e6-8b4c-51c85d141ca3.jpg)
![step-2](https://cloud.githubusercontent.com/assets/4804498/18141835/7b1908c0-6f91-11e6-8edd-b70ed8db73b5.jpg)
![step-3](https://cloud.githubusercontent.com/assets/4804498/18141834/7b140a96-6f91-11e6-90c5-3502755c894b.jpg)


.

**Comment by blackmambahk** [comment]
Don't disagree that in the pdf it's a glyph rather than actual text, I think the original source is probably photoshop but issue is why does it work in Firefox and not in Chrome.

Also just to note it displays fine in Chrome own native pdf viewer.

**Comment by Snuffleupagus** [comment]
Given that this issue is *very* old, and that it's apparently specific to a *particular* platform/browser, it's probably not meaningful to keep this open now since it's unfortunately difficult to see that it can be fixed here.
