### ISSUE TITLE
Getting exception Worker is destroyed

### ISSUE THREAD

**Issue by mourice** [mozilla/pdf.js#7581]
I am using pdfjs viewer inside my ionic2 application I am loading the bytearray pdf successfully inside iframe.
When i go back from the viewer using navigation back button. And again come back to view pdf its throwing exception Worker is destroyed
Please help thanks

**Comment by timvandermeij** [comment]
There is not much we can do without a working demo online that illustrates the issue. Always be sure to provide the data from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

**Comment by timvandermeij** [comment]
Closing until the requested information is provided.
