### ISSUE TITLE
Slow PDF download

### ISSUE THREAD

**Issue by smanov** [mozilla/pdf.js#7582]
Happens for every PDF file test mainly in chrome but assuming it is reproducible in all browsers. The problem is that getDocument is downloading a file for 20ms and then the inside benchmark shows it took to the library 300ms to finish the download.  The code is as simple as this:
PerformanceCounter.getLogger("OpenDocumentViewer").tick("Start PDF file loading", DW.Diagnostics.TickTypes.Client);
                PDFJS.getDocument(url)
                    .then(function (pdf) {
                        PerformanceCounter.getLogger("OpenDocumentViewer").tick("PDF file loaded", DW.Diagnostics.TickTypes.Server);

So the question is - is it normal that Fiddler shows 20ms for the download and the inside performance counter is showing 300ms dilay? In general readying the PDF header should be a fast operation I guess so explaining this with some "pre-rendering" will be off topic. 

What I expect to happen here is a number comparable to the fiddlers response time but averaging 12 times more should be happening for a reason.

**Comment by timvandermeij** [comment]
Could you setup a demo on JSBin or such a site so we can take a look? From the description it's not really clear what the problem could be.

**Comment by yurydelendik** [comment]
> So the question is - is it normal that Fiddler shows 20ms for the download and the inside performance counter is showing 300ms dilay?

PDF.js is using browser's XHR to load the data, this mean if data is in the browser's cache it will try to use this data. Also if server reports, that it can handle range request, PDF.js aborts initial request and issues new to get the "tail" of the pdf, which is enough to finish getDocument() request (PDF.js will issue additional range requests to get the data only applicable to display of the particular page).

> Happens for every PDF file test mainly in chrome but assuming it is reproducible in all browsers.

Please provide exact steps and link to reproduce the issue. The snippet above cannot be executed as is.

**Comment by smanov** [comment]
Maybe I am not explaining myself right. You can use any example regarding PDF.js in JSBin e.g. http://jsbin.com/tovafeyobu/2/edit?html,console,output 
and just put something like this in it (before and after the getDocument): 
var startTime = new Date();
PDFJS.getDocument(url)
 .then(function (pdf) {
var stopTime = new Date();
console.log(stopTime - startTime);

The snippet I have provided was with my own counter but you don't need it obviously.

**Comment by yurydelendik** [comment]
> is downloading a file for 20ms 

It's not clear where this number is coming from. Is it total from all (initial and range) XHR requests?

**Comment by smanov** [comment]
The service I am using for the PDFs is not supporting range requests.

**Comment by smanov** [comment]
It is just a single download request and I am using the "overall elapsed" time provided by fiddler

**Comment by yurydelendik** [comment]
The link you provided above does not load PDF. Can you use browser's profile to find out where all time in the script is spend?

**Comment by smanov** [comment]
The profiling doesn't show much... everything seems fine. It seems it takes about 200ms to load and initialize the woker itself every time and this is what causes the "delays" I experience.

**Comment by yurydelendik** [comment]
Based on your example you are using disableWorker. Can you not do that?

**Comment by yurydelendik** [comment]
>  is it normal that Fiddler shows 20ms for the download and the inside performance counter is showing 300ms dilay?

>  It seems it takes about 200ms to load and initialize the woker itself every time and this is what causes the "delays" I experience.

I guess you answered your question. Closing as anwsered.

We are not loading core PDF.js in the main thread to avoid long running script warnings and locking of UI. With getDocument we are loading worker with PDF.js code, however the worker can be loader upfront and re-used accross getDocument calls (see PDFJS.PDFWorker). The CPU time will stay the same (for PDFWorker or disableWorker/pdf.combined.js options) though.
