### ISSUE TITLE
Script5022 error when trying to view pdf with scanned image in ie11

### ISSUE THREAD

**Issue by adam-knights** [mozilla/pdf.js#7587]
Pdf: 
[2_birds.pdf](https://github.com/mozilla/pdf.js/files/452246/2_birds.pdf)

Configuration:
- Web browser and its version: ie11
- Operating system and its version: window 7 64 bit
- PDF.js version: pdfjs-dist v1.5.415
- Is an extension:

Steps to reproduce the problem:
```
let pdfData = this.base64ToPdfData(encodedDoc);

            window.document.write('<canvas id="af-canvas"></canvas>');
            PDFJS.workerSrc = '../assets/pdf.worker.js';
            PDFJS.getDocument(pdfData).then(function(pdf) {
              pdf.getPage(1).then(function(page) {
                var scale = 1.5;
                var viewport = page.getViewport(scale);

                var canvas = window.document.getElementById('af-canvas');
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                var renderContext = {
                  canvasContext: context,
                  viewport: viewport
                };
                page.render(renderContext);
              });
            });

  base64ToPdfData(base64) {
    var raw = atob(base64);
    var uint8Array = new Uint8Array(raw.length);
    for (var i = 0; i < raw.length; i++) {
      uint8Array[i] = raw.charCodeAt(i);
    }
    return uint8Array;
  },
```

The pdf comes down in base64 encoded data, thus the above. I'm hoping this reproduces in a more basic sense for someone.

What is the expected behavior? Display the pdf - see pdf in chrome for it working

What went wrong? It doesnt render at all in ie11 and shows script5022 error in the debugger. It seems to fail at the line ``` this.ctx.drawImage(groupCtx.canvas, 0, 0);``` in the ```endGroup: function```.

**Comment by yurydelendik** [comment]
Since there is complete example online to test your, the problem can be with mode HTML in e.g. non-HTML5. Check <!DOCTYPE definition and check if web/compatibility.js is included. Closing as incomplete.

**Comment by adam-knights** [comment]
@yurydelendik where is the complete example online to test this?. I have both doctype and web compatibility setup.

I managed to get more detail on the exception - drawImage is throwing a typeMismatchError.

**Comment by adam-knights** [comment]
Nevermind - although the original page has <!DOCTYPE - this was opening into a new window, if I open onto the same page it works. The new window doesnt have <!DOCTYPE, so could well be it, ill see if i can add that to the new window.
