### ISSUE TITLE
Prepare a new release

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7589]
It has been a while since the last release, so we should prepare a new one. I suggest to do this after #7586 and #7588 land to ensure that the new release contains improved text selection enhancement code.

**Comment by Snuffleupagus** [comment]
#7407 is another quite small PR (with a reduced test-case), that would be really nice to get landed and included in the release.

**Comment by timvandermeij** [comment]
The pull requests have been merged, so we are ready to create the release.

**Comment by timvandermeij** [comment]
This has been completed yesterday, so I'm closing this as resolved.
