### ISSUE TITLE
Double-click highlighting broken with enhanced text selection turned on.

### ISSUE THREAD

**Issue by jeremypress** [mozilla/pdf.js#7590]
Link to PDF file (or attach file here): 
[tracemonkey.pdf](https://github.com/mozilla/pdf.js/files/452993/tracemonkey.pdf)

Configuration:
- Web browser and its version: Chrome 53, Safari 9.1.2
- Operating system and its version: Mac OS X
- PDF.js version: 

Steps to reproduce the problem:
1. turn on enhanceTextSelection
2. try to double click text, especially if the text is in two columns

What is the expected behavior? (add screenshot)
The word that is being double clicked should be selected

What went wrong? (add screenshot)
A word a few words back was selected

Video demonstrating the problem:
[example.zip](https://github.com/mozilla/pdf.js/files/452999/example.zip)

**Comment by jeremypress** [comment]
I think adding a delay on firing the event to shrink the div after a mouse up could solve this problem.

**Comment by Snuffleupagus** [comment]
WFM, using Firefox Nightly 51 on Windows (`ID:20160902030222 CSet: d5f20820c80514476f596090292a5d77c4b41e3b`).

**Comment by jeremypress** [comment]
@Snuffleupagus updated  impacted browsers
