### ISSUE TITLE
iPad Safari prints blank pages

### ISSUE THREAD

**Issue by slimjim181** [mozilla/pdf.js#7597]
As an iPad user
I want to be able to print my pdf documents from PDF.js
So I can have a hard copy

PDF file is not applicable but screenshots were taken from the example pdf https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration**
- iPad Air 2
- iOS 9.3.5 (latest)
- Safari 9 (latest)
- PDF.js 0.8.0 (latest)

**Steps to reproduce**
- Click the print button on a document.
- Note the 'preparing for document printing' dialog comes up

**Expected Behaviour**
- The print dialog box opens up with the document present (as the screenshot in the workaround shows)
- And when I actually print the document to a printer the document is printed not just a blank page

**Actual Behaviour**
- The print dialog box comes up with blank page.
  ![ipad-print-3](https://cloud.githubusercontent.com/assets/20076864/18258212/835520da-7425-11e6-9075-29e372f75861.jpg)
- And when you actually print the document to the printer the page is blank

**A workaround**
- Download the pdf document to the iPad by clicking the download button.
- Open in iBooks (app preinstalled by default)
- Click the share button
- Click print. 
- The print dialog box opens with the document visible in its frame
  ![ipad-print-4](https://cloud.githubusercontent.com/assets/20076864/18258150/b8cb6a18-7424-11e6-9067-9de61d3b69bd.jpg)
  This screenshot ^ show the expected behaviour I would expect the print button to perform in PDF.js

**Comment by slimjim181** [comment]
Related issue: https://github.com/mozilla/pdf.js/issues/4582

**Comment by adiq** [comment]
I discovered, that in some cases `window.close()` after `print()` can cause iOS Safari not to work properly. The only solution which I found is to add second timeout statement.

```javascript
setTimeout(() => {
    window.print();
    setTimeout(() => {
        window.close();
    }, 1000);
}, 1000);
```

I don't know if that's the issue in this case, but I leave this information for others having similar problem.

**Comment by tlcoder** [comment]
I am seeing the same issue.

**Comment by sangyi7** [comment]
I have the same symptoms if I change the print.

**Comment by AnsonWooBizCloud** [comment]
I have the same issue

**Comment by kejsiStruga** [comment]
How do you get the download to work on iPad???

**Comment by jordanhenderson** [comment]
Same issue. The fix above from @SyntaxUnknown allows PDF previews to be displayed, however upon printing I receive a blank page. I'll investigate this further and report back, does anyone have a solution?

**Comment by jordanhenderson** [comment]
Will try the solution from @adiq shortly.

**Comment by jordanhenderson** [comment]
Using the following performPrint function fixed the issue on iOS Safari for me:
`performPrint: function () {
     this.throwIfInactive();
     return new Promise(function (resolve) {
      setTimeout(function () {
       if (!this.active) {
        resolve();
        return;
       }
       print.call(window);
       var printEvent = window.matchMedia('print');
       printEvent.addListener(function(printEnd) {
         if (!printEnd.matches) {
           resolve();
         };
       });
      }.bind(this), 0);
     }.bind(this));
    }`

**Comment by jordanhenderson** [comment]
Apparently there are still issues with the above solution on > iOS 9.3.5.

**Comment by pedropcruz** [comment]
Well, i tried on several issues, maybe i had luck on this...

I am testing on my ipad, ios 9.3.5, on safari and no resulst of showing pdf:

The supost result, seeing on desktop, google chrome:

![image](https://user-images.githubusercontent.com/6757946/36841554-87152772-1d40-11e8-9252-a46f3b6e20fd.png)

and when tested on ipad:

![pdf_idp_error](https://user-images.githubusercontent.com/6757946/36841579-a91e7b8e-1d40-11e8-9109-b7fea4b8fba7.png)

Any idea what it can be ?

thanks

**Comment by pedrojrivera** [comment]
Here is what I found:

To get printing to work on  iPad iOS > 9.3.5 I had to comment out the resolve() method. The only issue is that the dialog box that shows the percent print completed remains open. 

For now I am going to change the cancel button to "Done" once printing is completed so that the user can close the dialog box manually. At leas the printing will work as expected.

**Comment by vigorem** [comment]
@pedrojrivera I agree, this is unfortunately the only solution which worked for me (iOS11 - iPad Pro - Safari). 

On Chrome I can't even make it work

**Comment by farshadmohajeri** [comment]
@pedrojrivera 
I added below code to renderProgress() function, so "Cancel" becomes "Done" when progress is full!.

```
 if (progress == 100) {
  	document.getElementById('printCancel').innerHTML = 'Done';
}
  
```

**Comment by pgtaboada** [comment]
2018, ios12 and still an open issue?

**Comment by gobinathm** [comment]
Yes Still a problem.

**Comment by ArchFolken** [comment]
This bug is very old now and still not fixed. Anyone has a valid solution ? Or another lib to use to display and print a pdf on ipad plz ?

**Comment by MuhammadAziz** [comment]
This code works for me. This also resolve issue when you click cancel button on print dialog and print for second time. Tested on iOS 11.0.1
```js
document.addEventListener("DOMContentLoaded", function(){
  var printQuery = window.matchMedia('print');
  PDFViewerApplication.beforePrint = function(method){
    return function(){
      method.apply(this, arguments);
      if(this.printService){
        this.printService.performPrint = function(print){
          return function(){
            var that = this;
            return new Promise(function(resolve){
              function printListener(){
                setTimeout(function(){
                  printQuery.removeListener(printListener);
                  resolve();
                }, 1000);
              }
              printQuery.addListener(printListener);
              print.call(that);
            });
          }
        }(this.printService.performPrint)
      }
    }
  }(PDFViewerApplication.beforePrint);
})
```

**Comment by oneclickwebstudio** [comment]
> 2018, ios12 and still an open issue?

2021, Mac OS Big Sur, Safari Technology Preview and still the same shit)

**Comment by nikhil123k** [comment]
This issue is still happening in iPad and i am using pdfjsVersion = '1.4.137'. Do we have any solution for this issue?
With the below solution, first time it is showing in ipad, if we close print window and opens again it is showing blank page. Also in iPad Safari, if we cancel the print window and opens again it is showing "This website has been blocked from automatically printing" 

setTimeout(resolve, 1000); // Tidy-up.

**Comment by kaytuca** [comment]
@MuhammadAziz  
Two questions: 
1. Where exactly do you put this code? 
2. Is it just a matter of inserting the code, or are you replacing other code?  And if replacing, what are you replacing?
Thanks!

I have the same experience as others:
1. I had the same printing problem on my iPad iOS 14.5.1 using PDF.js viewer 2.7.570 (es5 compatible) with large pdf files not rendering in print preview (two pages would render and that's it)
2. Changing  setTimeout(resolve,20)   to  setTimeout(resolve, 1000)   also got the iPad to render the pdf in its entirety.
3. The "cancel" button created problems for me as for everyone else. 
Hence my interest in the "larger solution" and the block of code that might solve the entire problem for all of us.  

Thanks for anyone's help!

Thanks

**Comment by samreaves** [comment]
> 

I added @MuhammadAziz 's code in the webViewerLoad function, as that is called on DOMContentLoaded. Works for me now.

`function webViewerLoad() {
  const config = getViewerConfiguration();
  const event = document.createEvent("CustomEvent");
  event.initCustomEvent("webviewerloaded", true, true, {
    source: window
  });

  try {
    parent.document.dispatchEvent(event);
  } catch (ex) {
    console.error(`webviewerloaded: ${ex}`);
    document.dispatchEvent(event);
  }

  _app.PDFViewerApplication.run(config);

  /* Custom script to help printing on iOS */
  var printQuery = window.matchMedia('print');
  PDFViewerApplication.beforePrint = function(method){
    return function(){
      method.apply(this, arguments);
      if(this.printService){
        this.printService.performPrint = function(print){
          return function(){
            var that = this;
            return new Promise(function(resolve){
              function printListener(){
                setTimeout(function(){
                  printQuery.removeListener(printListener);
                  resolve();
                }, 1000);
              }
              printQuery.addListener(printListener);
              print.call(that);
            });
          }
        }(this.printService.performPrint)
      }
    }
  }(PDFViewerApplication.beforePrint);
}`

**Comment by Snuffleupagus** [comment]
Let's close this as WONTFIX, given that:
 - Firefox, and particularly its built-in PDF Viewer, is the *primary* development target in this library.
 - This seem to be browser/platform-specific, rather than a more general bug.
 - We always try to avoid adding browser-specific compatibility hacks in the code-base, for reasons of readability/maintainability/performance.
 - The work-arounds mentioned above seem to rely on using a *somewhat arbitrary* time-out, which isn't really something that we'd consider here (in addition to the previous point).
