### ISSUE TITLE
Cannot print on Android 4.4.2

### ISSUE THREAD

**Issue by slimjim181** [mozilla/pdf.js#7599]
As an Android user
I want to be able to print my pdf documents from PDF.js
So I can have a hard copy

PDF file is not applicable but screenshots were taken from the example pdf https://mozilla.github.io/pdf.js/web/viewer.html

**Configuration**
- Samsung Galaxy Ace 3
- Android 4.2.2 (latest version the Ace 3 can get)
- Chrome 52
- PDF.js 0.8.0 (latest)

**Steps to reproduce**
- Click the print button on a document.
  ![screenshot_2016-09-06-15-31-50](https://cloud.githubusercontent.com/assets/20076864/18261758/befff342-744f-11e6-95b1-74918f893240.png)
- Note the 'preparing for document printing' dialog comes up
  ![screenshot_2016-09-06-15-31-36](https://cloud.githubusercontent.com/assets/20076864/18261752/b858186c-744f-11e6-92a6-ad9eac02787e.png)

**Expected Behaviour**
- After the 'preparing for document printing' dialog gets to 100%
- The print dialog box opens up with the document present
- And I can print the document

**Actual Behaviour**
- Nothing happens. no print dialog box comes up at all.
- Therefore I cannot print the document

**Comment by slimjim181** [comment]
I can see various similar issues have been raised about this but were closed due to lack of detail.

**Comment by Snuffleupagus** [comment]
Closing, since Android 4 is explicitly unsupported in PDF.js `2.0`.
