### ISSUE TITLE
Print/preview from pdf.js component getting some fields added. Help us to remove

### ISSUE THREAD

**Issue by shenbagaraj** [mozilla/pdf.js#7604]
On clicking the print button from the pdfviewer component could see four fields added in the pdf. Please find below the screen shot Highlighted in yellow.
Kindly help me to remove the four fields from the print option. 
1) Date
2) pdf.js viewer(title text)
3) url 
4) Date

![image](https://cloud.githubusercontent.com/assets/21241471/18302292/a71f33a0-74f4-11e6-9a83-fe25fc3ca11a.png)

Browser **chrome**, pdf.js version **pdfjs-1.5.188-dist**

Kindly help me to remove the four fields from the print option.

**Comment by timvandermeij** [comment]
This cannot be done through code as browsers do not expose this functionality. It has to be disabled in the print dialog of the browser itself. Closing as answered.
