### ISSUE TITLE
Feature request: Displaying a list of search results

### ISSUE THREAD

**Issue by ausiuming** [mozilla/pdf.js#7605]
Now the search function is similar to the normal search in Adobe Reader.

Is it possible to implement an advanced search function similar to the one in Adobe Reader that can display a list of clickable search results ?

Currently is there any API to grab the search results ?

**Comment by pravid** [comment]
I have written basic functions to show search result list. 
The thing I'm stuck with is that, I'm not able to highlight the selected text on page change.
Here is the gist link - https://gist.github.com/pravid/f99f4d9857a3a042918c1bba9676bfe8

**Comment by abbassss** [comment]
I found a solution on stackOverFlow and with a little bit of change, I got the found key with 20 characters before and after that and the page numbers.
check this link: https://github.com/abbassss/PdfJs-search-result

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX for now.
