### ISSUE TITLE
Range Request small

### ISSUE THREAD

**Issue by Seebiscuit** [mozilla/pdf.js#7606]
Link to PDF file (or attach file here):

Configuration:
- Browser: Chrome Version 52.0.2743.116 m
- OS: Win 7
- PDF.js version: 1.4.20
- Is an extension: No

Steps to reproduce the problem:
1. Request any PDF doc
2. Observe byte range request header

Issue:
Range request bytes are always "small". I've only noticed the range to be pretty much exactly `64KB`. 

We're serving PDF docs via a controller that implements a stream write and handles byte range requests. Negotiating with the controller directly meets our security policy requirements, but is very costly.

Is it possible to tweak the range request size? Maybe something to the order of `0.5MB`? Are there are pitfalls to consider?

**Comment by timvandermeij** [comment]
Yes, you can change https://github.com/mozilla/pdf.js/blob/b26af7ee2471305a39239ceed2e171986a8115a6/src/display/api.js#L66. The main pitfall I can imagine is that initial rendering may take longer, especially on slow connections, as 0.5 MB has to be transferred instead of 64 KB to begin rendering.

**Comment by Snuffleupagus** [comment]
> Are there are pitfalls to consider?

One issue is that setting the `DEFAULT_RANGE_CHUNK_SIZE` to something as large as `0.5 MB` will basically disable range requests for a very large percentage of PDF files.[1]
As can been seen in [`src/core/network.js`](https://github.com/mozilla/pdf.js/blob/8dbb5a7c4a63782e24382f9773386d9facbfc557/src/core/network.js#L425-L430), we don't use range requests for PDF files that are smaller than `2 * DEFAULT_RANGE_CHUNK_SIZE`.

---
[1] Note that the [Firefox telemetry data](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-08-23&keys=__none__!__none__!__none__&max_channel_version=release%252F48&measure=PDF_VIEWER_DOCUMENT_SIZE_KB&min_channel_version=release%252F47&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2016-07-26&table=0&trim=1&use_submission_date=0) suggests that a majority of PDF files found in the wild are smaller than `1 MB`.
