### ISSUE TITLE
Is there any callback method triggered by rending done event?

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7607]
I need to do something after PDF rendering finished, is there any callback method to use?

**Comment by timvandermeij** [comment]
There is only the "pagerendered" event. Refer to https://github.com/mozilla/pdf.js/issues/4448#issuecomment-37523898 as to why.

**Comment by yurydelendik** [comment]
Also `RenderTask` (https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L1870) returned by the render method contains a promise that is resolved when the rendering is done.
