### ISSUE TITLE
Set rangeChunkSize dynamically

### ISSUE THREAD

**Issue by Seebiscuit** [mozilla/pdf.js#7610]
Trying to dynamically set `rangeChunkSize`.

Found this (https://github.com/mozilla/pdf.js/blob/b26af7ee2471305a39239ceed2e171986a8115a6/src/display/api.js#L216):
```
params.rangeChunkSize = params.rangeChunkSize || DEFAULT_RANGE_CHUNK_SIZE;
```

And I tried supplying it as a `#` view option:
```
http://...#rangeChunkSize=524288
```

But it didn't get picked up. Any ideas how it can set `params.rangeChunkSize`?

**Comment by timvandermeij** [comment]
Hash parameters are not used for this (or practically anything else in general as most are only for development purposes). You can set `rangeChunkSize` by providing it to the object passed as `src` to `getDocument`. Look at the code at https://github.com/mozilla/pdf.js/blob/b26af7ee2471305a39239ceed2e171986a8115a6/src/display/api.js#L139 to see how it is processed.
