### ISSUE TITLE
pdf.js partially fails to render text - bad x_height

### ISSUE THREAD

**Issue by jeremypress** [mozilla/pdf.js#7617]
Link to PDF file: 
[ud.pdf](https://github.com/mozilla/pdf.js/files/462534/ud.pdf)

Configuration:
- Web browser and its version: all
- Operating system and its version: Mac OS X 10.11.6
- PDF.js version: most recent master

Steps to reproduce the problem:
1. Load PDF
2. Compare text areas on pages 9, 11 to preview or chrome's built in pdf viewer

What is the expected behavior? (add screenshot)sc
<img width="822" alt="screen shot 2016-09-08 at 12 49 12 pm" src="https://cloud.githubusercontent.com/assets/2474027/18364337/d97f7e26-75c2-11e6-8c4b-9436a7da527f.png">
<img width="839" alt="screen shot 2016-09-08 at 12 49 18 pm" src="https://cloud.githubusercontent.com/assets/2474027/18364343/dba71d12-75c2-11e6-91fe-9042bbd833a4.png">

What went wrong? (add screenshot)
<img width="919" alt="screen shot 2016-09-08 at 12 49 43 pm" src="https://cloud.githubusercontent.com/assets/2474027/18364352/df5b0c0c-75c2-11e6-909f-d10def443161.png">
<img width="906" alt="screen shot 2016-09-08 at 12 49 50 pm" src="https://cloud.githubusercontent.com/assets/2474027/18364353/df6ff16c-75c2-11e6-9ecf-8c1243dec09e.png">

Getting this error multiple times: `downloadable font: OS/2: bad x_height: -485 (font-family: "g_d0_f22" style:normal weight:normal stretch:normal src index:0)`

**Comment by timvandermeij** [comment]
It seems like the font cannot be sanitized properly, so I'm labeling it as such for now.

**Comment by Snuffleupagus** [comment]
Works for me, despite the `downloadable font: ...` warnings being present in the console, using PDF.js version `1.5.437` on Windows 7. Could this be worse on MacOS?

**Comment by jeremypress** [comment]
@Snuffleupagus I didn't expect that but it appears to be true. It renders much better on Windows Chrome, Firefox, and IE.

**Comment by timvandermeij** [comment]
Closing since this now renders fine. The sanitizer warnings are gone.
