### ISSUE TITLE
Reset page number and zoom setting at each loading

### ISSUE THREAD

**Issue by ctessier** [mozilla/pdf.js#7627]
Link to PDF file (or attach file here):

Configuration:

Web browser and its version: chrome, latest
Operating system and its version: Windows 7
PDF.js version: latest
Is an extension: 
Steps to reproduce the problem:

Hi,

Is there a way to reset local storage at each loading of the viewer so the PDF doesn't keep the previous page number and zoom setting I had?

Thanks for your help
Regards

**Comment by Snuffleupagus** [comment]
> Is there a way to reset local storage at each loading of the viewer so the PDF doesn't keep the previous page number and zoom setting I had?

Assuming that you're using the default viewer, then setting the `showPreviousViewOnLoad` to `true` should make sure that PDF files always load with the default page/zoom.

Closing as answered.

**Comment by VictoriaStefanikova** [comment]
As this is deprecated solution, would you recommend some workaround?
