### ISSUE TITLE
font rendering blurry with custom scaling level in windows

### ISSUE THREAD

**Issue by karyon** [mozilla/pdf.js#7630]
Link to PDF file (or attach file here): https://people.mpi-inf.mpg.de/~ritschel/PreconvolvedRadianceCaching/PreconvolvedRadianceCaching.pdf

Configuration:
- Web browser and its version: Firefox 50.0a2 (2016-09-12)
- Operating system and its version: Windows 10 10586
- PDF.js version: '1.5.365', build '19105f0'
- Is an extension: no

Steps to reproduce the problem:
1. change windows' scaling level to 115%: type "display" in start menu, click the control panel thing that comes up, click "choose a custom scaling level", set to 115%
2. open the pdf

What is the expected behavior? (add screenshot)
it shouldn't look worse than in 100%:

![100small](https://cloud.githubusercontent.com/assets/1891915/18474964/e37cfa74-79c4-11e6-80ef-56ac48281a63.png)
or 125%:
![125small](https://cloud.githubusercontent.com/assets/1891915/18474965/e381d986-79c4-11e6-9773-2215cbe7e235.png)

What went wrong? (add screenshot)
it looks pretty blurry.

![115small](https://cloud.githubusercontent.com/assets/1891915/18474963/e37b69c0-79c4-11e6-9169-09b749420d84.png)

make sure you have these displayed unscaled. the difference is quite noticeable; if it's not noticeable for you, maybe your browser or OS are scaling it wrong ;) everything else in firefox looks just fine for me.

let me know if i can help with this.

**Comment by timvandermeij** [comment]
It looks like Windows is articifically scaling up the canvases, somewhat like CSS zooming. I think you do not have this when the Windows zoom is 100% and the PDF.js zoom is 125% because we actually re-render the canvas. Since this is something Windows is doing, I don't think there is anything we can do about that...

**Comment by karyon** [comment]
to make sure there is no misunderstanding: the 125% screenshot is made with the windows scaling set to 125%, not the pdf.js scaling. in all three screenshots i set the scaling of pdf.js to some value so the resulting width was roughly the same, not necessarily to 100% (i don't know exactly). I don't remember exactly but i'd say the perceived blurriness between different pdf.js scaling levels was the same for a given windows scaling level.

**Comment by yurydelendik** [comment]
The reported `devicePixelRatio` is 1.1538461446762085 which probably is hard to round for our physical pixel snapping at `approximateFraction`, which rounds that to 8/7 = 1.142857142857143. I did not check, but increasing limit to 16 might help.

**Comment by yurydelendik** [comment]
Setting as good beginner bug to investigate (and if results will be positive submit PR). Otherwise we probably close this bug in favor of upstream bug with canvas or won't fix.

**Comment by yurydelendik** [comment]
Related bug at #6552

**Comment by karyon** [comment]
i experimented a bit and 116% did not change anything. in fact, it did not even change the `devicePixelRatio` of 1.1538461446762085. i don't know whether windows or firefox is at fault for that. 117% to 119% gave 1.1764706373214722, which is approximated with 7/6 = 1,1666666 and gives blurry text. 120% gives a `devicePixelRatio` of 1.200000, which is approximated with 6/5, and all looks good.

a limit of 16 resulted in `devicePixelRatio` = 1.1538461446762085 -> 15 / 13 = 1,153846153, exact match.
however, for `devicePixelRatio` = 1.1764706373214722 the result was 13 / 11 = 1,18181818, and indeed the text was blurry again.
but, raising the limit to 32 it resulted in 20/17 = 1,176470588 which is a exact match again.

could it be that the devicePixelRatio is rounded with that limit set to 32 somewhere upstream? i don't know where to look for that, and have no idea whether that's intended or not.

**Comment by karyon** [comment]
i searched mozilla-central and could find neither "farey" or "approximateFraction" anywhere else.

**Comment by yurydelendik** [comment]
@karyon the function can be found at https://dxr.mozilla.org/mozilla-central/source/browser/extensions/pdfjs/content/web/viewer.js#2201 , but the change has to be posted here first to be landed to m-c.

**Comment by karyon** [comment]
@yurydelendik i found that one, but the question was where the rounding of the `devicePixelRatio` happens :)

**Comment by yurydelendik** [comment]
> where the rounding of the devicePixelRatio happens

I'm sorry, I don't understand what are you asking then. It can be reported by OS in this manner or some precision lost during float/int of graphics layer operations. Browsers' internals is out of topic, but you are welcome to investigate this and provide feedback on what can be done at PDF.js level.

**Comment by karyon** [comment]
when setting windows' scaling level to 115 or 116%, the `devicePixelRatio` is actually 1.15384, although 115 and 116 can be exactly represented by 32-bit floats. but, since that 1.15384 matches 15 / 13 exactly (as far as that is possible with floats), this made me suspect that the `devicePixelRatio` is already a fractional approximation.

my question was where that approximation for `devicePixelRatio` is done, whether that is pdf.js, firefox or even windows. then i could look how the approximation is done there and maybe refer to that place in a comment instead of reverse-engineering it and setting some arbitrary limit in that algorithm.

the easy solution would be setting the limit to 32 as I know the font rendering works fine with that limit and for scaling levels of 115% to 120%, but that's not a satisfying solution :)

**Comment by yurydelendik** [comment]
What do other browsers report for devicePixelRatio (e.g. chrome, ie)?

**Comment by karyon** [comment]
chrome doesn't care and reports 1, edge says 1.5999 for 116%, so it doesn't approximate.

i opened https://bugzilla.mozilla.org/show_bug.cgi?id=1302789 for the `devicePixelRatio` approximation, but i guess that's not worth fixing.

but most of all it's not pdf.js' fault.

should i create a PR that raises that limit to 32? it doesn't seem like a satisfying solution to me, but i know basically nothing about canvas rendering and how all that scaling stuff is supposed to work, so i don't have any better suggestion.

**Comment by yurydelendik** [comment]
> know basically nothing about canvas rendering and how all that scaling stuff is supposed to work

it's simple: we create a canvas with the size that will fit into physical pixels. HTML/CSS's 1px does not match a physical pixel but devicePixelRatio gives how to scale it. We approximate ratio between CSS and physical pixel, so during composition canvas pixels with match physical one (e.g. if devicePixelRatio=1.25, we want that every canvas 5x5 rect will be painted in 4x4 px CSS). Since sizes maybe non-divisible by ratio number, in worst case we will have empty pixels to the right or bottom (and we are trying to hide them).

**Comment by karyon** [comment]
that sucks. that also means that raising the limit might result in more empty pixels, right?

but, why bother with css pixels at all? why is it not enough to get the canvas size in physical pixels and render to that size, since it will end up with that exact size on screen? i tried to do exactly that (measuring how large it will be rendered on screen, and then setting canvas.width and height accordingly) and it was still blurry, why?

please let me know if i'm asking too many questions, but i'm genuinely curious.

as an aside, this here http://www.html5rocks.com/en/tutorials/canvas/hidpi/ sounds like one could get the physical size with that `backingStorePixelRatio`, but that has never seen widespread implementation. that being said, the code from there retreiving `backingStorePixelRatio` is still in pdf.js but i guess it does nothing in most browsers :)

**Comment by karyon** [comment]
setting the canvas size to measured size plus four resulted in a sharp output. is there a 2px border anywhere or something like that?

i'm getting confused and am going to bed. any comment to help me understand this would be appreciated. again, please let me know if i'm taking too much of your time.

**Comment by yurydelendik** [comment]
> that also means that raising the limit might result in more empty pixels, right?

Right, it will insignificant in comparison with canvas size.

>  why is it not enough to get the canvas size in physical pixels and render to that size, since it will end up with that exact size on screen?

It does not. All explanations can be found at http://www.html5rocks.com/en/tutorials/canvas/hidpi/ . By doing 200% scale on windows, you are making what is called "retina" display on mac, just pixels are not dense enough :)

**Comment by karyon** [comment]
unfortunately, that exact part is not explained there. it says "In case you're wondering why you can't use the devicePixelRatio to determine the backing store size, the answer is that they aren't guaranteed to match" but does not give any further details. further, it is quide outdated, since `webkitBackingStorePixelRatio` does not exist anymore in chrome.

btw chrome does report a devicePixelRatio, but not for 125% and below where it's just set to one.

any idea why i have to set the canvas size to physical size + 4 to get a sharp result?

**Comment by yurydelendik** [comment]
> any idea why i have to set the canvas size to physical size + 4 to get a sharp result?

nope, but it's something related to rounding.

**Comment by Snuffleupagus** [comment]
Closing this for now, since based on the entire discussion above it's not clear that this is first of all a PDF.js library/viewer bug and secondly if/how it could be worked-around (satisfactory) in the PDF.js code-base.
