### ISSUE TITLE
comments on PDF files in landscape orientation are rotated and in wrong position

### ISSUE THREAD

**Issue by yaofeng365** [mozilla/pdf.js#7631]
There is a problem in pdf.js when displaying comments on documents in landscape orientation.  The comment icon and popup text are shown as rotated 90 degree.  Documents in portrait orientation don't have this problem.

Link to PDF file (or attach file here):
Please see the attached pdf_landscape_adobe.pdf
[pdf_landscape_adobe.pdf](https://github.com/mozilla/pdf.js/files/470518/pdf_landscape_adobe.pdf)

Configuration:
- Web browser and its version:  Google Chrome Version 52.0.2743.116 m
- Operating system and its version:  Windows 7 Professional Service Pack 1
- PDF.js version: 1.4.20
- Is an extension: No.

Steps to reproduce the problem:
1. Create a pdf document in landscape orientation
2. Added a comment and an annotation (for comparation purpose) with Adobe Reader.  Both comment and annotation look good in Adobe Reader.  See the attached pdf_landscape_adobe.pdf.
3. Go to pdf.js demo site http://mozilla.github.io/pdf.js/web/viewer.html and open the above pdf file.  
4. You can see the annotation is displayed correctly, but the comment has problems.
- The icon is rotated 90 degree.
- The popup text (once you click on the icon) is rotated 90 degree.
- The popup text is not in the right position.

What is the expected behavior? (add screenshot)
The comment should be displayed correctly as annotation.  See screenshot 
![pdf_landscape_expected](https://cloud.githubusercontent.com/assets/22178781/18486730/26b5f0f2-79a7-11e6-8ac4-acbd6562f541.png)
![pdf_landscape_bug](https://cloud.githubusercontent.com/assets/22178781/18486742/332d3f70-79a7-11e6-9230-864c229259b5.png)

pdf_landscape_expected.png. 

What went wrong? (add screenshot)
The following problems were observed.  See screenshot pdf_landscape_bug.png.
- The icon is rotated 90 degree.
- The popup text (once you click on the icon) is rotated 90 degree.
- The popup text is not in the right position.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
Closing as incomplete because the requested information is not provided.

**Comment by yaofeng365** [comment]
Sorry for not providing requested information when I created this issue - I hit the wrong button.  Anyway, I updated the issue with all the required information.  Can you please take a look?  Thanks.

**Comment by THausherr** [comment]
The annotation has the NoRotate flag set.

**Comment by timvandermeij** [comment]
I wonder why it's even rotated as the page itself is not rotated. Even if we would respect the `NoRotate` flag, how come it's rotated in the first page?

**Comment by THausherr** [comment]
The page is rotated:

![pdfdebugger-screenshot](https://cloud.githubusercontent.com/assets/6665575/18617336/83f050da-7dcd-11e6-9d65-ab94d190c35e.png)

**Comment by timvandermeij** [comment]
That probably explains the issue. Thanks for looking into this. This issue is about supporting the `NoRotate` flag then.

**Comment by yaofeng365** [comment]
Thanks for looking into it.  Please let me know if you need anything from me.

**Comment by JanSlabon** [comment]
We also run into that issue. Attached an additional [example file](https://github.com/mozilla/pdf.js/files/1148045/-90.pdf).

I guess it shouldn't be that hard to fix, because a simple matrix calculation depending on the rotation and NoRotate flag should be all. All you have to do is to rotate on the upper left corner.

I'm sorry for not offering a pull request but I simply have no deep knowledge in pdf.js.

**Comment by Mucaccino** [comment]
+1

**Comment by THausherr** [comment]
Another test file, I created it myself:
[PDFBOX-4447-Annotations-NoRotate.pdf](https://github.com/mozilla/pdf.js/files/2809615/PDFBOX-4447-Annotations-NoRotate.pdf)

**Comment by JosNun** [comment]
Are there any known workarounds for this?
