### ISSUE TITLE
How to get x coordinate from right side instead of left side?

### ISSUE THREAD

**Issue by bhavu002** [mozilla/pdf.js#7638]
Hi, I am using below function for getting X and Y coordinate from PDF:
As per current coding we are getting X coordinate from left side and Y coordinate from bottom.

 Util.applyTransform = function Util_applyTransform(p, m) {
    var xt = p[0] \* m[0] + p[1] \* m[2] + m[4];
    var yt = p[0] \* m[1] + p[1] \* m[3] + m[5];
    return [xt, yt];
  };

  Util.applyInverseTransform = function Util_applyInverseTransform(p, m) {
    var d = m[0] \* m[3] - m[1] \* m[2];
    var xt = (p[0] \* m[3] - p[1] \* m[2] + m[2] \* m[5] - m[4] \* m[3]) / d;
    var yt = (-p[0] \* m[1] + p[1] \* m[0] + m[4] \* m[1] - m[5] \* m[0]) / d;
    return [xt, yt];
  };

**Comment by Snuffleupagus** [comment]
Closing as INCOMPLETE, since there's unfortunately nowhere near enough information provided to make this actionable/valid; please note https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
