### ISSUE TITLE
TextWidgetAnnotations rendered in *both* the core and display layer after PR 7596

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#7643]
After PR #7596, the rendering of the following PDF files regressed (both taken from issue #3419, and could/should be used as new reference tests):
http://www.broadband-xp.com/test/pdfjs/annotation-tx2.pdf
http://www.broadband-xp.com/test/pdfjs/annotation-tx3.pdf

Note how the content is rendered *twice*, once in the `core` and once in the `display` layer:

![double_rendering](https://cloud.githubusercontent.com/assets/2692120/18613720/7fde6182-7d80-11e6-9c92-cb41a9d6ad63.png)

**Please note:** The screen-shots were obviously taken *without* the (experimental) form support enabled, so they represent what a regular PDF.js user would currently see!

I believe that this is a direct result of https://github.com/mozilla/pdf.js/pull/7596#issuecomment-244819605, and it's *very* unfortunate that we didn't have tests that covered this.

Finally, note that when this is fixed, the patch will have to be uplifted to Firefox 51 since PR #7596 was included in https://bugzilla.mozilla.org/show_bug.cgi?id=1301577.

**Edit:** Note that even the newly added test file `annotation-text-widget.pdf` has the same problem.
(But the files linked above still makes *very* good test-cases, since they illustrate quite clearly why we cannot just skip the `Appearance` stream when rendering forms in the `display` layer.)

**Comment by Snuffleupagus** [comment]
For now it might be easiest to simply replace the previous condition, but with a slight tweak, e.g.
```javascript
var isRenderable = (!parameters.data.hasAppearance &&
                    !!parameters.data.fieldValue) || parameters.renderInteractiveForms;
AnnotationElement.call(this, parameters, isRenderable);
```
instead of https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L404.

**Comment by timvandermeij** [comment]
This has been fixed, so could you contact the required people upstream for uplifting this to Firefox 51?

**Comment by Snuffleupagus** [comment]
> This has been fixed, so could you contact the required people upstream for uplifting this to Firefox 51?

It's probably best to wait until the next PDF.js update in mozilla-central.
Those are usually done by RyanVM once a week, at Thursdays or Fridays, so I figured that I'd wait for the next one and then submit an Aurora patch (containing *only* the change for the `annotation.js` file) and try to convince the release managers that they want it :-)

**Comment by timvandermeij** [comment]
Perfect. Indeed only the change in `annotation.js` is needed for the uplift, so hopefully that's doable. Thank you for helping out with this!

**Comment by Snuffleupagus** [comment]
I didn't ask for an extra PDF.js update, but it seems that RyanVM did one anyway! 🎉
This is fantastic news, since https://bugzilla.mozilla.org/show_bug.cgi?id=1303651 has just landed on mozilla-central, hence no further action should be required here :-)

**Comment by timvandermeij** [comment]
Awesome!
