### ISSUE TITLE
TextLayer placed wrong on canvas

### ISSUE THREAD

**Issue by kaarebs** [mozilla/pdf.js#7651]
https://s3.eu-central-1.amazonaws.com/lix-production-public-storage/262.pdf

Configuration:
- Version 46.0.2490.86 (64-bit)
- Ubuntu (x86_64)
  pdfjsVersion = '1.5.477'
  pdfjsBuild = '9e927de'

Steps to reproduce the problem:
1. Just loaded the pdf attached in the viewed.

What is the expected behavior?
- I expected the text to be placed correctly.

What went wrong?
- Text is not placed the right way.
- Also "exponent -" is parsed as the number 2.
- Se this link https://s3.eu-central-1.amazonaws.com/lix-production-public-storage/Screenshot_from_2016-09-21_11%3A13%3A16.png

The text is colored red everywhere and I have marked the word "value" -> here it is very wrong.

**Comment by timvandermeij** [comment]
The "value" part is fixed by recent patches. The "exponent" issue remains.

**Comment by timvandermeij** [comment]
Closing since the file is no longer available.
