### ISSUE TITLE
Is there any way to support IE8? even NOT look so well.

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7655]
Is there any way to support IE8? even NOT look so well.

**Comment by timvandermeij** [comment]
IE 8 is missing too many features to be supported. You may include `web/compatibility.js` that includes polyfills for missing functionality in older IE versions, but we provide no support for IE 8 whatsoever.

**Comment by godwin668** [comment]
I found compatibility.js it already included, but does NOT work. I tried include respond.js that includes polyfills but still does NOT work.
