### ISSUE TITLE
How to only load a few pages needed, but NOT load all pages.

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7657]
Is there any way only load pages of current page and near pages and do NOT load other pages silently?
When I scroll page, also only load current page and near pages.

**Comment by Snuffleupagus** [comment]
Yes, setting `PDFJS.disableAutoFetch = true;` will attempt to only load the necessary data to render the currently active page(s). Note that this requires that the server supports range requests, for more information please refer to: https://github.com/mozilla/pdf.js/blob/6c263c19946af23b723f148d9f05118971e18b36/src/display/global.js#L178-L188.

Closing as answered.
