### ISSUE TITLE
Best way to config params. e.g. PDFJS.disableAutoFetch=false

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7658]
I need to config params like PDFJS.disableAutoFetch, is there any separate config file or I need to search all files and set all occurrence of PDFJS.disableAutoFetch?

**Comment by timvandermeij** [comment]
You can do it like in the examples: https://github.com/mozilla/pdf.js/blob/master/examples/mobile-viewer/viewer.js#L25

Just set it once (perhaps in a separate configuration file) for the entire environment.
