### ISSUE TITLE
Error loading PDF from DataURL in Safari

### ISSUE THREAD

**Issue by chadjaros** [mozilla/pdf.js#7662]
Link to PDF file (or attach file here):
All Files - Example: http://www.bombmanual.com/manual/1/pdf/Bomb-Defusal-Manual_1.pdf

Configuration:
- Web browser and its version: Safari 9.1.3
- Operating system and its version: OSX 10.11.6
- PDF.js version: 1.5.485 (pdfjs-dist installed via bower)
- Is an extension: no

Steps to reproduce the problem:
1. Choose a file from the local file system via an `<input type="file"></input>` tag
2. Capture the selected file, and convert it to a DataURL (via `FileReader.readAsDataURL`)
3. Call `PDFJS.getDocument` with the DataURL

What is the expected behavior? (add screenshot)
- The returned promise should resolve successfully with a PDFDocumentProxy. The above process works well on Chrome and Firefox.

What went wrong? (add screenshot)
- Safari Error

> XMLHttpRequest cannot load data:application/pdf;base64, [data]. Cross origin requests are only supported for HTTP.
- Thrown Error:

> Error: Unexpected server response (0) while retrieving PDF "data:application/pdf;base64, [data]".
> UnexpectedResponseExceptionClosure@http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:463:52
> http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:467:3
> http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:46:12
> pdfjsWrapper@http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:48:2
> http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:11485:10
> http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:25:8
> global code@http://localhost:8080/bower_components/pdfjs-dist/build/pdf.js:27:2

**Comment by Snuffleupagus** [comment]
> The returned promise should resolve successfully with a PDFDocumentProxy. The above process works well on Chrome and Firefox.

Since it's apparently a browser specific problem, this doesn't really seem like an issue in the PDF.js library; should this be closed as INVALID then?

**Comment by chadjaros** [comment]
At the very least the documentation should be modified to indicate this functionality does not work on Safari

**Comment by Snuffleupagus** [comment]
Safari isn't listed as fully supported at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and generally speaking it's not really feasibly to list *every* browser specific limitation that may exist.
