### ISSUE TITLE
JBIG2 throws errors and displays blank pages in PDF

### ISSUE THREAD

**Issue by julieknoll** [mozilla/pdf.js#7663]
https://fraser.stlouisfed.org/docs/publications/employment/1970s/1970-1974/empl_081971.pdf

Configuration:
- Web browser and its version: Firefox 49.0
- Operating system and its version: OSX 10.11.3 
- PDF.js version: 1.5.281
- Is an extension:

Steps to reproduce the problem:
1. View the file at https://fraser.stlouisfed.org/docs/publications/employment/1970s/1970-1974/empl_081971.pdf
2. Scroll to page 6. 

What is the expected behavior? (add screenshot) Expected to see images in the PDF file
![pdf](https://cloud.githubusercontent.com/assets/1264064/18754273/b43629e4-80ad-11e6-9407-11fa2090f89a.png)

What went wrong? (add screenshot) The page displays blank, but you can highlight the embedded OCR text. There are errors about the JBIG2 pattern dictionary thrown in the javascript console.
![jbig2error](https://cloud.githubusercontent.com/assets/1264064/18754200/7517b41c-80ad-11e6-8114-ba76b027c6fb.png)

**Comment by DoomTay** [comment]
Here are some more examples with that same issue, as natively implemented in Firefox 54.0.1 on Windows 10, PDF.js: 1.7.348

http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1991-03.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1991-01.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-08.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-11.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-05.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-04.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-03.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-02.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1989-09.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1989-10.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1989-11.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1989-12.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-01.pdf
http://www.americanradiohistory.com/Archive-Modern-Electronics/Modern-Electronics-1990-03.pdf
