### ISSUE TITLE
Disable Shortcuts

### ISSUE THREAD

**Issue by sarankup** [mozilla/pdf.js#7669]
Hi,

I want to disable the PDF.JS shortscuts. Please advise how to achieve it.

Thanks in advance.

**Comment by timvandermeij** [comment]
You can update https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2064.

**Comment by TaoChinLau** [comment]
> You can update https://github.com/mozilla/pdf.js/blob/master/web/app.js#L2064.

I am using vue-pdf-app, which based on pdf.js. How can I disable the shortcust? Thanks a lot.
