### ISSUE TITLE
Some Japanese characters overlap

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#7687]
Link to PDF file (or attach file here):
[610510_p37.pdf](https://github.com/mozilla/pdf.js/files/507848/610510_p37.pdf)

Configuration:
- Web browser and its version: Firefox
- Operating system and its version: Windows 7
- PDF.js version: Current
- Is an extension:

Steps to reproduce the problem:
1. I accessed http://mozilla.github.io/pdf.js/web/viewer.html
2. Opened attached PDF

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![pdf_error](https://cloud.githubusercontent.com/assets/7111820/19065750/3f8cb246-8a50-11e6-879d-dba35461b6ea.png)
Some characters overlapping as indicated.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Fixed by #11540.
