### ISSUE TITLE
PDF download problem in Safari 10.00

### ISSUE THREAD

**Issue by cloud1991** [mozilla/pdf.js#7688]
Using the official demo: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Safari 10.0 (12602.1.50.0.10)
- Operating system and its version: macOS Sierra 10.12 (16A323)
- PDF.js version: Latest
- Is an extension: No

Steps to reproduce the problem:
1. Open link of demo: https://mozilla.github.io/pdf.js/web/viewer.html
2. Wait for viewer to complete loading of PDF
3. Press download button of the pdf.js viewer
![bugpdf_1](https://cloud.githubusercontent.com/assets/9305709/19066487/d3280550-8a19-11e6-8c5b-f36ed8fc7b72.png)
1. Safari opens the PDF in his viewer showing in URL bar something like: "blob:https://mozilla.github.io/7978885a-c1ef-43d3-ac3b-39d22736c7bf"

What is the expected behavior? (add screenshot)
Pressing the download button of the Safari PDF viewer should start PDF download. In a similar way, by pressing the "Open in preview" button the PDF should be opened in Preview or Adobe Reader.
![bugpdf_2](https://cloud.githubusercontent.com/assets/9305709/19066495/da8ca97c-8a19-11e6-9ec3-ded54659e8ce.png)

What went wrong? (add screenshot)
The two buttons in the screenshot above don't work. They simply do nothing.

**Comment by timvandermeij** [comment]
Works fine in Firefox, so I'm marking this as Safari-specific for now. There is no "Open in preview" button, its an "Open file" button for opening a local file with PDF.js.

**Comment by cloud1991** [comment]
"Open in preview" is the third button of the last screenshot (after the two magnifing lenses). Is a button of the Safari Pdf viewer.

**Comment by Rob--W** [comment]
Safari (including 10!) does not support `<a download>`. See https://bugs.webkit.org/show_bug.cgi?id=156056 and https://github.com/eligrey/FileSaver.js/issues/12, which suggest that it may be fixed in the future.

**Comment by timvandermeij** [comment]
Closing as fixed upstream.
