### ISSUE TITLE
Example to use multiple PDF.js viewer in same page

### ISSUE THREAD

**Issue by himani-chaudhary** [mozilla/pdf.js#7693]
Hi Team,

I am facing an issue to add multiple PDF.js viewers in single page. First of all, I don't know how to start, as in the example page i.e. 
https://mozilla.github.io/pdf.js/web/viewer.html

Here, the whole structure uses IDs, i.e. outerContainer, mainContainer, viewerContainer, viewer. 

How to add similar structure to show other PDF in the same page. Please provide any example page, which I can refer.

Thanks

**Comment by yurydelendik** [comment]
Demo viewer is not designed to be used/instantiated multiple times on the same page. However we performed multiple steps toward making it work in such manner (e.g. #7209 or #6571).

> I am facing an issue to add multiple PDF.js viewers in single page.

Hosting multiple iframes gives the same effect, so there is no real benefits for the project to have and support such functionality. Closing as won't fix for now.

**Comment by gaupoit** [comment]
Dear team,

Thanks for creating the wonderful library. We are also facing these problems, have we supported this feature now?

**Comment by timvandermeij** [comment]
Improvements have been made to make the viewer much more stand-alone and less dependent on global attributes. However, the iFrame approach is still the recommended way for now, but we're always open for contributions to improve the situation. Thanks.
