### ISSUE TITLE
Pdf.js can copy from encrypted file without password?

### ISSUE THREAD

**Issue by Just-CJ** [mozilla/pdf.js#7699]
Link to PDF file (or attach file here):
https://github.com/itext/itext7-samples/raw/master/samples/src/test/resources/sandbox/security/cmp_encrypt_pdf_without_user_password.pdf

Configuration:
- Web browser and its version: Google Chrome 53.0.2785.143 (64-bit) 
- Operating system and its version: OS X 10.11.6
- PDF.js version: v1.6.210
- Is an extension: no

I have a encrypted pdf that is set unethical reading and decrypt on purpose (use itextpdf). 
That means when I open this file, I can read the content, but when I try to copy the content, it will show a dialog to input password.
However, when I open it in pdf.js viewer, I can easily copy then content without the password.

Steps to reproduce the problem:
1. Download the file above.
2. Open it with local application, try to copy something and you will be prompted to input password which is 'World'
3. Open it with pdf.js viewer like https://mozilla.github.io/pdf.js/web/viewer.html. You can easily copy anything without password.

**Comment by timvandermeij** [comment]
Closing as duplicate of #2699.
