### ISSUE TITLE
will the pdf.js download the file that mount?

### ISSUE THREAD

**Issue by LXMin** [mozilla/pdf.js#7704]
after the pdf.js open the file that set in the DEFAULT_URL , will it store the file in the local folder?
if that ? how can i find the storage file?
or if not that? how the pdf.js load the pdf file and open it ?just transform the pdf file to some buffer ?

**Comment by timvandermeij** [comment]
PDF.js does not store the file elsewhere or copy it. It just loads the file and handles it internally. If you reload the viewer, the file is reloaded as well.

**Comment by LXMin** [comment]
thank u
