### ISSUE TITLE
Printing from subframe does not work in Chrome 54

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#7706]
Steps to reproduce: https://bugs.chromium.org/p/chromium/issues/detail?id=650952

Chrome 54 is going to be released next week, so this should be fixed soonish.

Once #7697 lands, I plan to submit a PR that collects all images and sends them to the main frame for printing.

**Comment by timvandermeij** [comment]
Closing as fixed upstream. It should be in time for a new Chrome release, so I'm hopeful that we won't need a workaround. If things change, we can reopen this/the PR. Thanks.

**Comment by Rob--W** [comment]
FYI: The fix landed in Chrome 56.
