### ISSUE TITLE
Add support for biometric signatures

### ISSUE THREAD

**Issue by lexcorp** [mozilla/pdf.js#7707]
**Add support for biometric signatures**

If you do not already know, the signature captured from the signature pad is **not just an image** of a signature, but it constitutes as a behavioural biometrics. The biometric signature from sign pad is able to provides data, capable to identify a person based on his characteristics displayed when he signs his signature. It is different from physiological biometrics, such as fingerprint and retina, which cannot be changed, and can be easily duplicated.

Though a signature captured from the signature pad, is rendered just like a normal signature signed by a normal
pen like this:
 
https://s16.postimg.org/bmc5lb32d/Biometric_Signature.jpg

But in actual fact, the computer only captures the points within the signature, at a rate of 200 points per second, as you can see in the following image.
 
https://s16.postimg.org/6oyl07139/Biometric_Signature_Points.jpg

The complete lines you see are rendered based on the coordinates of these points, and the thickness of the lines is based on the pen pressure.

Each point contains not just the XY coordinates, but also other information –including the sequence, pressure, pen tilt, contact with pad. 

Yes, the movement of the pen is captured even when it is not in contact with the pad, so that you can tell if a fraudster is hovering his/her pen in midair deciding how to make his/her next stroke.

When you know the sample rate of the signature pad, you can also calculate the speed. And the sequence number of each point can give you the direction of the strokes. So there is a whole lot of information in just a plain signature.

**Mockups**
**Biometric signatures process and steps**
https://s16.postimg.org/5b6y4w1tx/Biometric_Signature.png

1.- Include icons to signatures on pdf.js ToolBar
https://s9.postimg.org/9ywfx66zz/Barra_Iconos.png

2.- Draw rectangle to locate signature
https://s9.postimg.org/ks3y5ooa7/locatesignature.png

3.- Signature capture popup open and detect device to sign (sign pad, pen, etc)
https://s9.postimg.org/j7ym7afvz/detect_devices.png

4.- Draw signature with sign pad, pen, etc.
https://s9.postimg.org/66cxhfrhr/drawsignature.png

5.- Embed signature on pdf
https://s9.postimg.org/3qb43l9f3/embed_signature.png

6.- Ability to perform Dinamyc_Signature_Verification
https://s9.postimg.org/5fk7bnp4f/Dinamyc_Signature_Verification.png

**Dinamyc Signature Verification**

Use the Dynamic Signature Verification to analyse signatures captured in your applications. You
can use DSV to compare a new signature with a trusted signature and modify your application workflow accordingly. For example, if a signature is not recognised your application can choose to request additional personal identification.

Dynamic signature verification uses biometric information to determine the level of similarity between signatures. Two diferent signatures cannot be absolutely identical but a number of features can be compared and given a score in the verification process. The features include the pen stroke sequence, direction, speed and pressure and these define the dynamic signature verification process. The following illustrates information available to the dynamic verification process which cannot be seen in a static image; in this case the path of the pen between strokes can be used in the verification process.

**How Graphometric Signature and Verification is performed**

When the user perform a Graphometric Signature the following information are captured:

1.	The image of the signature,
2.	The position and direction
3.	The pressure (1024 levels)
4.	The time
5.	The curvature
6.	The acceleration
 
http://www.andxor.com/images/Obama%20Signature%20biometric.jpg

During a Graphometric Signature the important element is not the graphical mage (like during 2D normal ink signature) but the biometric characteristics of the image. Including the time and the pressure, the x,y position the velocity and direction we can have spatial dynamic information not available during a normal ink signature.
 
http://www.andxor.com/images/Graphometrical%20Signature%20Points%20and%20Velocity.jpg

In the next picture you can see a normal ink signature in a 2Dimensional space and the same signature in a 3Dimensional space including the time.
 
http://www.andxor.com/images/Graphometrical%20signature%20Spatial%20dynamic.jpg

In fact "ONLY the biometric information without the image of the signature" are stored and are useful for matching a future signature. This allow more security and dynamic verification 
This is the typical verification process.
 
http://www.andxor.com/images/Graphometric%20Verification.jpg

All these information will be included in the digital signature creating and Advanced Electronic Signature.

Once the Advanced Electronic Signature using Biometrical information is bonded with the document via a Digital Signature the final final receive the Persistent Security to allow legal verification of authenticity, presence in time and Integrity as well as non repudiation.
 
**International standards**

ISO/IEC 19794-7:2014 Information technology -- Biometric data interchange formats -- Part 7: Signature/sign time series data

ISO/IEC 19794-11:2013 Information technology — Biometric data interchange formats — Part 11: Signature/sign processed dynamic data

**More info:**

http://www.andxor.com/supported-signatures.html

http://www.andxor.com/help.html

**Comment by timvandermeij** [comment]
PDF.js is a viewer, not an editor, so adding signatures is not something PDF.js should support. This can be implemented in a custom viewer though, it's just something that is not of value for the default viewer as shipped in Firefox and other extensions.

**Comment by lexcorp** [comment]
Thanks for the clarification tim...
