### ISSUE TITLE
If the pdf.js open the pdffile safely?

### ISSUE THREAD

**Issue by LXMin** [mozilla/pdf.js#7708]
I have a requirement that the pdf file is confidential ，
so i want to know if the pdf.js has a model of encryption，
in other words , i just want to see , if the pdf.js open the file safely ？
is there any possible that will leak the content of the file that will be opened by the pdf.js ?
thank u

**Comment by timvandermeij** [comment]
If the PDF file is encrypted with a password, then PDF.js will not show the file unless the correct password is specified. However, otherwise the PDF will be rendered and that means that its contents are visible and may be downloaded/captured. This is the case for any viewer, really.
