### ISSUE TITLE
how to regenerate a pdf file without embedding fonts

### ISSUE THREAD

**Issue by wanghaisheng** [mozilla/pdf.js#7710]
i am using https://github.com/modesty/pdf2json which based on pdf.js.
can anyone tell me how to regenerate a pdf file without embedding fonts?

**Comment by yurydelendik** [comment]
It's out of scope of this project. See https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md for more information. Closing as invalid.

**Comment by wanghaisheng** [comment]
@yurydelendik   what about how to use pdf.js to generate pdf files without embedding fonts? every character use one of the 5 standard font families(Times, Helvetica, Courier,Symbol and ZapfDingbats.)

**Comment by timvandermeij** [comment]
Embedding fonts is mandatory to ensure proper display across PDF viewers and systems. Not embedding fonts is a deprecated practice and we highly discourage that and do not provide support for that. You'll have to take care of providing the required font files in your custom application.

**Comment by wanghaisheng** [comment]
thx for you ,it seem my problem is not caused by  the embeeding fonts 
https://github.com/mozilla/pdf.js/issues/7712
pdf files what  i got elsewhere is not complete,without  character encoding  as yurydelendik commented
