### ISSUE TITLE
PDF with acrobat javascript print, in iframe, will print the outside page instead of pdf content

### ISSUE THREAD

**Issue by fancycarp** [mozilla/pdf.js#7711]
I have a PDF file [http://pdfjs.eu5.org/TestIFrame/ShowPrintDialog.pdf](http://pdfjs.eu5.org/TestIFrame/ShowPrintDialog.pdf)
with acrobat javascript : this.print(true);

I want to press button and load file in iframe and display print dialog immediately, like this
[http://pdfjs.eu5.org/TestIFrame/Test.html](http://pdfjs.eu5.org/TestIFrame/Test.html)

The print dialog shows up fine, and when I print out, the result from Chrome is fine but from IE is incorrect. It should be the PDF content, not the content of outside page.
![2016-10-12_11h38_27](https://cloud.githubusercontent.com/assets/15316793/19297566/6f9f00ee-9070-11e6-9bde-a25b19f276b1.png)

Environment
PDFJS : 1.5.188
Browser : IE 10.0.9200.16899
OS : Windows 8 Pro x64

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.

**Comment by CXVVMVII** [comment]
> Closing since IE10 is no longer supported since PDF.js 2.0.

Hey , but can this be done via any other browser ,
if yes , please how ??!

and thanks
