### ISSUE TITLE
Chrome extension: Add option/Default to collapse all items in outline

### ISSUE THREAD

**Issue by jeenuv** [mozilla/pdf.js#7713]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome, 53.0
- Operating system and its version: Linux
- PDF.js version: 1.5.294
- Is an extension: Yes

Steps to reproduce the problem:
1. Open any PDF with table of contents, and the outline is displayed with everything expanded. For a file with large TOC, it takes a lot of scrolling to find/jump to the right item. This is exacerbated by the fact that outline width isn't adjustable, which means that the content wraps around, resulting in longer scrolls.

What is the expected behavior? (add screenshot)

Please add an option to, or make it the default behaviour that items in the outline start collapsed upon page load. In a stricter sense, only this will give an outline of the document! Users can later expand them as required.

To see how frustrating an expanded TOC is, try the ARM Architecture Manual for ARMv8 (login required) - it's 5000+ pages long, with a rather long and deep TOC.

**Comment by jeenu-arm** [comment]
Another alternative that comes to my mind is to offer a button to recursively expand/collapse a selected item in the TOC. When operated on top-level item thus expands/collapses the entire tree.

**Comment by Snuffleupagus** [comment]
It currently is *very* poorly (or not at all even) surfaced in the UI, but please note that as [mentioned in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#outline-sidebar), you can double-click on the "Show document outline" button to expand/collapse *all* outline items.
Furthermore, again please see the FAQ, by pressing the <kbd>Shift</kbd> key while clicking on the triangles you can expand/collapse all items under the selected item

**Comment by jeenuv** [comment]
Ha! That was basically what I was after. I'd rather have that displayed on the tool tips. Let me see if I can get a patch through.

(My previous comment was left from an account that I use at work)

**Comment by timvandermeij** [comment]
Fixed by #7717.
