### ISSUE TITLE
How to wait for page rendered?

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#7718]
Hey,

how to check if pdf.js is currently rendering or finished rendering? 

Im using the viewer example as a foundation. In my external code I zoom and want to wait for pdf.js finished rendering before executing more of my code.

Thanks for any answers!

**Comment by timvandermeij** [comment]
You can listen for the `pagerendered` event. In general there is no way to know that the entire document is rendered because it may load incrementally (for example, based on range requests or in the viewer when you scroll a page into view).

**Comment by MickL** [comment]
Problem is that this is too general. It gets called a few times (for every page rendered?). But i don't know when the viewer is actually rendering. Perfect would be a flag `var rendering:boolean` that i can access.

**Comment by yurydelendik** [comment]
@MickL. As it was said, the demo viewer never renders all pages (only visible) and re-renders some pages when zoom changes. Looks like you have to write specialized viewer that will render all pages, so you can run your code. See how to wait on page to be rendered with RenderTask.promise at https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html

**Comment by MickL** [comment]
Sorry if it wasnt clear. I know it only renders the visible pages. But i need to know when it finished this rendering so i can continue. When "pagerendered" is called twice, how do i know the second is the final one? It would be perfect if there is some variable or event like "pdf js is currently working".

**Comment by yurydelendik** [comment]
It hard to tell without seeing the example: 1) "pagerendered" could be called for different pages (e.g. after rendering page 2 then after page 1 -- they both are visible but page 2 had less content); 2) zoom/scale parameter changed e.g. due to window.resize; 3) bug in the viewer.

**Comment by MickL** [comment]
Is there any startrendering event?
I could catch every start and every end so i would know when there is no rendering active.

**Comment by yurydelendik** [comment]
Also see if https://github.com/mozilla/pdf.js/blob/master/web/dom_events.js#L37 and https://github.com/mozilla/pdf.js/blob/8c5b9255471d7c2f472e477592fca4a50f2a5962/web/pdf_page_view.js#L433

**Comment by MickL** [comment]
To clearify: I just want to know if the pdf.js is currently rendering. If yes i would wait. If no I can continue.

**Comment by yurydelendik** [comment]
There is `renderingState` for every page view, see https://github.com/mozilla/pdf.js/blob/8c5b9255471d7c2f472e477592fca4a50f2a5962/web/pdf_page_view.js#L96 . You can query state for every page view in the document?

**Comment by MickL** [comment]
Ok thanks this is kind of what i was looking for. It may not be a good idea to check every page when having a 200 page document. But the surrounding 2 may be fine.

It may look something like this:

```
if(PDFViewerApplication.pdfViewer._pages[currentPage] == 3) {
    // continue
} else {
   // setTimeout iteration
}
```

Not the best solution but i would work. A variable or promise from pdf.js saying "hey im currently doing some hard work" and "im currently doing nothing" would be more nicely :)

**Comment by jerry-sunny** [comment]
> There is `renderingState` for every page view, see
> 
> https://github.com/mozilla/pdf.js/blob/8c5b9255471d7c2f472e477592fca4a50f2a5962/web/pdf_page_view.js#L96
> 
> . You can query state for every page view in the document?



> There is `renderingState` for every page view, see
> 
> https://github.com/mozilla/pdf.js/blob/8c5b9255471d7c2f472e477592fca4a50f2a5962/web/pdf_page_view.js#L96
> 
> . You can query state for every page view in the document?

thanks for mentioning renderingStates property , it really solved the hurdle 
```
var RenderingStates = {
  INITIAL: 0,
  RUNNING: 1,
  PAUSED: 2,
  FINISHED: 3
};
```

**Comment by navidshey** [comment]
In this sample (https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html), you can see that we have a promise that will run after the pdf is loaded:

```
  // Wait for rendering to finish
      renderTask.promise.then(function () {
        pageRendering = false;
        if (pageNumPending !== null) {
          // New page rendering is pending
          renderPage(pageNumPending);
          pageNumPending = null;
        }
      });
```
