### ISSUE TITLE
Missing some images in converted canvas

### ISSUE THREAD

**Issue by SergioV85** [mozilla/pdf.js#7724]
https://manuals.info.apple.com/MANUALS/1000/MA1595/en_US/ipad_user_guide.pdf
http://kindle.s3.amazonaws.com/Kindle_User%27s_Guide_English.pdf

Configuration:
- Chrome 53.0.2785.143 m (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 1.6.234
- Is an extension:

I use PDF.js for converting pdf files to simple images. And, for some PDF files converting is not very good: many images are missing, and sometimes whole pages are blank

I using next code for converting pdf

``` javascript
public ConvertPDFtoImage(pdf: PDFDocumentProxy) {
    const promiseDocumentArray: Array<PDFPromise<PDFPageProxy>> = [];
    for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
        promiseDocumentArray.push(pdf.getPage(pageNum));
    }   
    this.getPagesFromDocument(promiseDocumentArray);
}
private getPagesFromDocument(documentPromisesArray) {
    const promisePageArray = [];
    Promise.all(documentPromisesArray)
        .then(
            (pages) => {
                $.each(pages, (i, page: PDFPageProxy) => {
                    promisePageArray.push(this.renderPDFpageToCanvas(page));
                });
                this.getCanvasesFromPages(promisePageArray);
            }
        );
}
private getCanvasesFromPages(promisePageArray) {
    Promise.all(promisePageArray)
        .then(
            (canvases) => {
                $.each(canvases, (idx, canvas: HTMLCanvasElement) => {
                    this.editor.Screenshot.canvas = canvas;
                    this.editor.LoadImageFromPDF();
                });
            })
        .catch(
            (error) => {
                console.log(error);
        });
);
private renderPDFpageToCanvas(page: PDFPageProxy): JQueryPromise<HTMLCanvasElement> {
    const renderedCanvas = $.Deferred();
    const scale = 1.5;
    const viewport = page.getViewport(scale);
    const canvas = <HTMLCanvasElement> document.createElement('canvas');
    const context = canvas.getContext('2d');
    canvas.height = viewport.height;
    canvas.width = viewport.width;
    const renderContext = {
        canvasContext: context,
        viewport
    };
    page.render(renderContext)
        .then(
            (result) => {
                renderedCanvas.resolve(canvas);
            }
        );
        return renderedCanvas.promise();
}
```

this.editor.LoadImageFromPDF(); - this function just append canvas inside DOM

What is the expected behavior? 
So, this are images from PDF Acrobat, Chrome and Mozilla viewers
iPad Manual
![ipad-01](https://cloud.githubusercontent.com/assets/8452421/19391788/57b7c67c-922e-11e6-9f32-3dae92a22b67.png)
iPad Manual
![ipad-02](https://cloud.githubusercontent.com/assets/8452421/19391789/57b9aee2-922e-11e6-8895-17b2ff482209.png)
Kindle Manual Title
![kindle-01](https://cloud.githubusercontent.com/assets/8452421/19391791/57be7670-922e-11e6-9adb-5f8d911a3993.png)
Kindle Manual
![kindle-02](https://cloud.githubusercontent.com/assets/8452421/19391790/57bbdb40-922e-11e6-868b-6623bc59b06d.png)

What went wrong? 
And this is converted images
iPad Manual
![ipad-01-br](https://cloud.githubusercontent.com/assets/8452421/19391947/f9ddd8a6-922e-11e6-8f4a-8866cfb56111.png)
iPad Manual
![ipad-02-br](https://cloud.githubusercontent.com/assets/8452421/19391946/f9d61d32-922e-11e6-8f87-9c23995757fe.png)
Kindle Manual Title
![kindle-01-br](https://cloud.githubusercontent.com/assets/8452421/19391945/f9cf88b4-922e-11e6-99f6-5410ee8da883.png)
Kindle Manual
![kindle-02-br](https://cloud.githubusercontent.com/assets/8452421/19391948/f9e0c2aa-922e-11e6-865f-79a5e0ea04c8.png)

As you see, some images are broken or missed.

**Comment by yurydelendik** [comment]
@SergioV85, Can you provide link to the complete example (that can be used to reproduce the issue, not a snippet)? Does this issue present in demo viewer?

**Comment by SergioV85** [comment]
Hi!
I've attached zip-archive [app.zip](https://github.com/mozilla/pdf.js/files/532819/app.zip) with Chrome extension. Please, install it to Chrome and try with any opened PDF. Some of them will be converting to image without loosing images (like this [one](http://martin.von-gagern.net/publications/2008-diploma/Diplomarbeit.pdf)), but manuals, mentioned above will loose some schemes and images

In preview (I use this [one](https://mozilla.github.io/pdf.js/web/viewer.html)) manual opened normally

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue and secondly that it looks like platform/browser-specific bug, rather than a general PDF.js one, is it actually meaningful to keep this open?
