### ISSUE TITLE
PDF image displayed blurred on Firefox

### ISSUE THREAD

**Issue by alexpahomi** [mozilla/pdf.js#7731]
Link to PDF file (or attach file here):
http://stud.usv.ro/~apahomi/paco.pdf

Configuration:
- Web browser and its version: Firefox 47.0.1
- Operating system and its version: Windows 10 Pro 64 bits
- PDF.js version:
- Is an extension: No, it's firefox default build in pdf viewer

Steps to reproduce the problem:
1.  Access the provided link

What is the expected behavior? (add screenshot)
Open the link in chrome and see the pdf or change the default pdf viewer to another pdf app in firefox or simply just save the pdf(even the one with image blured)

What went wrong? (add screenshot)
The main image is displayed blurred on Firefox but is displayed as it should be on other browsers. Even in firefox if I choose to save the pdf displayed blurred and open it later from my local machine with other app, the pdf looks as it should be.

**Comment by timvandermeij** [comment]
I can confirm this issue using Arch Linux x64, Firefox 49.0.1 and the latest PDF.js development version.

**Comment by Snuffleupagus** [comment]
It seems that PR #6606 would fix this, so it'd be really nice if we could get that landed!

**Comment by THausherr** [comment]
Same problem:
https://issues.apache.org/jira/secure/attachment/12821417/PDFBOX-3447-Step-99999.pdf

**Comment by ssaras** [comment]
I'm having similar issues. [https://github.com/mozilla/pdf.js/issues/4706#issuecomment-325689432](https://github.com/mozilla/pdf.js/issues/4706#issuecomment-325689432)

**Comment by LubomirKurpel** [comment]
Having the same problem still...

**Comment by Rob--W** [comment]
The PDF from the bug report is 404. I'm assuming that https://github.com/mozilla/pdf.js/issues/7731#issuecomment-274865111 is an alternative test case for this bug. The referenced PR seems to fix the blurriness in the given test case.
