### ISSUE TITLE
Transparent PDFs have white background

### ISSUE THREAD

**Issue by Clawiste** [mozilla/pdf.js#7734]
Rendering PDF with transparent background doesn't work, instead of transparency it has white background. In the example below are two PDFs, one as a base and other one overlaying the base one which has transparent background but is rendered with a white one.

(on left side is how it should look like, on right side is how PDF.js renders it)
![example](https://cloud.githubusercontent.com/assets/5333075/19477391/2f6c04a4-953e-11e6-8877-ca1b9e1aed8d.jpg)

example website:
http://casopis.headliner.cz/pdfjs-transparency/

example pdfs:
http://casopis.headliner.cz/pdfjs-transparency/pdf/base.pdf
http://casopis.headliner.cz/pdfjs-transparency/pdf/overlay.pdf

source itself is available here:
http://casopis.headliner.cz/pdfjs-transparency/source.zip

**Configuration:**
Web browser and its version: Chrome 49, Safari 6, Firefox 48 (and probably even other versions, these are only ones that I have available)
Operating system and its version: OS X 10.8.3
PDF.js version: 1.6.230

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you provide *all the information* requested in the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md), and please also read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).
Without the requested information, this issue will be closed as incomplete.

**Comment by yurydelendik** [comment]
Closing as invalid: combining/composing two pdf pages (from different document) without background applied is out-of-scope of the project.
