### ISSUE TITLE
How to Add custom text(water mark) on each page of pdf file uisng pdf.js

### ISSUE THREAD

**Issue by altafkhokhar** [mozilla/pdf.js#7737]
Hi,

We are using pdf.js to display pdf file(s) in browser.
We came across requirement to display stamp(text like watermark in word) on each page.

Is it possible to add custom text like watermark on each page using pdf.js programatically ?
While user print the pdf file those watermark(s) should be there in print out.

Appreciate any ideas/inputs/solutions for same.

Version: 1.1.114

**Comment by timvandermeij** [comment]
You can overlay text `div`s over each page and render them onto the canvas for printing, but this is out of scope for the PDF.js project. Closing as answered.

**Comment by altafkhokhar** [comment]
Thank you very much.

I appreciate if you share any reference(s) which allow to render annotation(water mark) using pdf.js.

Thanks.
