### ISSUE TITLE
Generating HTML files and saving in the backend.

### ISSUE THREAD

**Issue by mysticmode** [mozilla/pdf.js#7741]
I'm building a browser based ebook reader with pdf support. Instead of rendering pdf to html when every time the user opens, I'm planning to show the html content directly to the client if it is possible to fetch it from pdfjs in the backend through headless browser like phantomjs.

I'm thinking about browser compatibility issues with the html that is coming from phantomjs. Could you give me some info on this?

Thanks!

**Comment by yurydelendik** [comment]
There is no issues stated. Closing as invalid.
