### ISSUE TITLE
Way to clear or reset the viewer?

### ISSUE THREAD

**Issue by JasonColeyNZ** [mozilla/pdf.js#7744]
Is there a way to reset or clear the viewer?

I use the .open(data) method to render the pdf using data retrieved via a web service controller.

I'd like to reset the view if possible to have it back to what it would be on first load.

**Comment by timvandermeij** [comment]
You have to do something similar to the `close` method in `web/app.js`: https://github.com/mozilla/pdf.js/blob/master/web/app.js#L550

This closes the document and resets all views.
