### ISSUE TITLE
ERROR: Unexpected server response (206) while retrieving PDF...

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7752]
I encounter error when view PDF under Webchat(微信) app in IOS(iPhone):
PDF.js v1.5.337 (build: 11381cd)
信息：Unexpected server response (206) while retrieving PDF...

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

Closing as incomplete for now, since it's impossible for anyone to help with the information given.
