### ISSUE TITLE
PDFJS.getDocument fails silently on nodejs

### ISSUE THREAD

**Issue by q4w56** [mozilla/pdf.js#7762]
Configuration:
- Web browser and its version:  nodejs v6.3.1 
- PDF.js version: 1.6.274

Steps to reproduce the problem:
1. `npm install pdfjs-dist`
2. 
```
var PDFJS = require('pdfjs-dist')
PDFJS.getDocument('nonsense_input').then( () => {})
```
What is the expected behavior? 
It should throw.

What went wrong? (add screenshot)
It didn't throw.

**Comment by yurydelendik** [comment]
> What is the expected behavior?
> It should throw.

It shoundn't throw, since JS Promises are used. Closing as invalid.

**Comment by q4w56** [comment]
Indeed I am wrong about the throw. 

But  I cannot catch the error.

```
PDFJS.getDocument('nonsense_input')
    .then( () => {})
    .catch( e => { console.log(e) })
// no stdout
```
