### ISSUE TITLE
PDFJS.getDocument fails silently on nodejs

### ISSUE THREAD

**Issue by q4w56** [mozilla/pdf.js#7763]
Configuration:
- Web browser and its version:  nodejs v6.3.1 
- PDF.js version: 1.6.274

Steps to reproduce the problem:
1. `npm install pdfjs-dist`
2. 

```
var PDFJS = require('pdfjs-dist')
PDFJS.getDocument('nonsense_input').then( () => {} ).catch( e => {console.log(e)} )
// no stdout
```

What is the expected behavior? 
Error should be caught.

What went wrong? (add screenshot)
No error is caught.

**Comment by Snuffleupagus** [comment]
> PDFJS.getDocument('nonsense_input').then( () => {} ).catch( e => {console.log(e)} )

According to the API docs, `getDocument` returns a `PDFDocumentLoadingTask`, please see https://github.com/mozilla/pdf.js/blob/d0d7046129f69f2c933115919a516876b1d50882/src/display/api.js#L175-L178

The [`PDFDocumentLoadingTask`](https://github.com/mozilla/pdf.js/blob/d0d7046129f69f2c933115919a516876b1d50882/src/display/api.js#L368-L373), for backwards compatibility, contains a `then` method but *not* a `catch` one: https://github.com/mozilla/pdf.js/blob/d0d7046129f69f2c933115919a516876b1d50882/src/display/api.js#L443-L451

Hence the intended way to handle the situation described above is to use the `PDFDocumentLoadingTask.promise` instead:
https://github.com/mozilla/pdf.js/blob/d0d7046129f69f2c933115919a516876b1d50882/src/display/api.js#L417-L422

Hence, the solution to this issue would be to do e.g. the following:
```javascript
let loadingTask = PDFJS.getDocument('nonsense_input');
loadingTask.promise.then(() => {}).catch(e => { console.log(e); });
```

Closing as answered.
