### ISSUE TITLE
PDF to SVG opacity

### ISSUE THREAD

**Issue by alafr** [mozilla/pdf.js#7764]
**Attach file here:**  [file.pdf](https://github.com/mozilla/pdf.js/files/559611/file.pdf)
**Web browser and its version:** all
**PDF.js version:** 1.6.274, https://mozilla.github.io/pdf.js/build/pdf.js

**What went wrong?**
All paths and shapes with opacity < 1 are rendered opaque
I get in the console the message: `Warning: Unimplemented graphic state ca (and CA)`

I can see there is no use of "fill-opacity", "stroke-opacity" or "opacity" attributes in the `src/display/svg.js` source code. Will this be implemented?

**Comment by doublex** [comment]
+1

**Comment by timvandermeij** [comment]
This pull request fixes the opacity issues tracked in this issue. Note that the only difference with the canvas rendering is then the stroke width, which is tracked in #7767.
