### ISSUE TITLE
font rendering blurry bad anti-aliasing

### ISSUE THREAD

**Issue by bikb** [mozilla/pdf.js#7765]
Link to PDF file (or attach file here):
http://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: firefox 48 android; safari ipad 
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. Open the demo and zoom into the sample pdf file
2.

What is the expected behavior? (add screenshot)
Why is the font rendering not as sharp as on desktop pc. How can it be tuned?
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Most likely CSS zooming is used, leading to a more blurry zoom. It's necessary on small devices because they generally lack the performance/memory required to render a large canvas.

**Comment by bikb** [comment]
In my post I told you clearly the following link:
http://mozilla.github.io/pdf.js/web/viewer.html
I think you can imagine which pdf version is used in the demo! 

Of course I can make some screenshots if needed. 
But I also think most github users have a smartphone and can test it. Please open the demo and zoom a little bit more into the font!

Perhaps we can investigate the problem a little bit more. 
In my opinion a Apple Ipad has a good software optimization with not so powerful CPU. But I only guess it. So whats with tuning a little bit and testing the options. I have a real device to do it.
What about hardware acceleration. Please can anyone tell how to test?


So please don't close the problem so fast as nobody can help!

**Comment by bikb** [comment]
Thank you for the comment. 
I have tested a little bit on android and there occured rendering performance issues.
Please can someone comment the code:
var maxScale = Math.sqrt(pdfjsLib.PDFJS.maxCanvasPixels / pixelsInViewport);
and the consequenses?
