### ISSUE TITLE
PDF to SVG stroke properties

### ISSUE THREAD

**Issue by alafr** [mozilla/pdf.js#7767]
- Attach file here: [bug-stroke.pdf](https://github.com/mozilla/pdf.js/files/560532/bug-stroke-uncompressed.pdf)
- Web browser and its version: probably all - I use chrome 54.0.2840.71 m (64-bit)
- PDF.js version: 1.6.274 from https://mozilla.github.io/pdf.js/build/pdf.js

What went wrong?
The width, dasharray, linejoin, linecap of the paths and lines are not rendered in the SVG.
I added breakpoints in the javascript debugger and I could see that the missing styling is correctly understood by the [`executeOpTree()`](https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js#L523-L543) function but is not yet defined when needed by [`constructPath()`](https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js#L884-L892) function. Maybe these lines should be moved in the [`stroke()`](https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js#L992) function ?

**Comment by timvandermeij** [comment]
Interesting. Thank you for trying out the experimental SVG back-end and providing detailed feedback!
