### ISSUE TITLE
Unit tests fail due to strict mode error

### ISSUE THREAD

**Issue by divergentdave** [mozilla/pdf.js#7768]
Link to PDF file (or attach file here):
N/A

Configuration:
- Web browser and its version: Firefox 45.4.0
- Operating system and its version: Debian Jessie
- PDF.js version: Latest from git
- Is an extension: No

Steps to reproduce the problem:
1. Run `gulp unittest`

What is the expected behavior? (add screenshot)
Tests run to completion

What went wrong? (add screenshot)
The Jasmine test runner does not load properly in Firefox, and the following error shows up in the browser console.

`SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function` `worker.js:93:9`

(this line is `function IPDFStream() {}`, which is inside `if (typeof PDFJSDev === 'undefined' || !PDFJSDev.test('PRODUCTION')) {...}`)

This regression was introduced in 0576c9c, from #7322. The error is similar to #2172.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by timvandermeij** [comment]
The unit tests run fine on the Windows/Linux bots that we use. Could you test with the most recent version of Firefox?

**Comment by divergentdave** [comment]
Yes, the problem went away with a newer Firefox. I had used 45.4.0 ESR at first since it's the default for Debian.

**Comment by timvandermeij** [comment]
Closing as fixed by upstream in that case.
