### ISSUE TITLE
Strange box characters in PDF

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#7769]
I see a problem with a particular PDF when viewed on the latest version of pdf.js, e.g. through your viewer here:

https://mozilla.github.io/pdf.js/web/viewer.html

This is the PDF displayed using Preview on a Mac:

![screen shot 2016-10-31 at 14 18 01](https://cloud.githubusercontent.com/assets/786238/19857251/ebdbf172-9f74-11e6-85d2-ee05555d358f.png)

But this is what I see in all browsers I've tried:

![screen shot 2016-10-31 at 14 15 36](https://cloud.githubusercontent.com/assets/786238/19857290/112a095a-9f75-11e6-9cfd-3df9226a61db.png)

Unfortunately I'm not sure what software is used to create the PDF.

The PDF is here:

[Parish-Bulletin-10-22.1 (1).pdf](https://github.com/mozilla/pdf.js/files/561923/Parish-Bulletin-10-22.1.1.pdf)

I hope this helps. Thank you!

Dan

**Comment by timvandermeij** [comment]
I can reproduce this issue using Arch Linux, Firefox 49.0.1 and the latest PDF.js development version. Thank you for reporting this! The fonts in the PDF cannot be sanitized according to the console output, leading to this broken rendering. The PDF generator is iText 5.5.8.

**Comment by rhazor** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/22996586/20013880/7d364e38-a2bd-11e6-9728-bf19649f4203.jpg)

**Comment by yurydelendik** [comment]
@rhazor your comment above looks unrelated to original issue. See https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md

**Comment by THausherr** [comment]
The problem is that type 1 font specification doesn't tell (or I didn't find it) what should be used and what not. Most fonts use only a tiny subset of postscript so one doesn't need to understand postscript but this one is more tricky:

```
%!FontType1-1.0:  
13 dict begin
/FontInfo 2 dict dup begin
/GlyphNames2HostCode <<
>> def
/GlyphNames2Unicode <<
>> def
end readonly def
/Ascent 0 def
/Descent 0 def
/Encoding 256 array
0 1 255 {1 index exch /.notdef put} for
dup 2 /vineleafboldnw put
dup 3 /space put
readonly def
/FontBBox {0 0 0 0} readonly def
/FontMatrix [0.00048828 0 0 0.00048828 0 0] readonly def
/FontName /TT1Eo00 def
/FontType 1 def
/PaintType 0 def
currentdict end
currentfile eexec
```


The two dictionaries ("<<"...">>") are unusual.
