### ISSUE TITLE
Compile custom changes 

### ISSUE THREAD

**Issue by Gibran-16** [mozilla/pdf.js#7770]
Hello,

I created a drag and drop box that I need, I added a .js file where I validate some actions the I do with the box, also I included a css file, I use bootstrap to show a modal and I modified viewer.htmt where I added a button and modal source. 

I added my .js to app.js file (define, requiere, root. etc.)
When I run the application using 'gulp server', all work very well, all is Ok, but when I compile the source using 'node make generic', it doesn't include my custom .js into viewer.js that is generated into 'build/generic/web/viewer.js', I saw this file that contains the source of other .js files.

My question is, how could I add o where could I add my custom .js to be compiled into viewer.js?

Let me know if you need moor information.

**Comment by timvandermeij** [comment]
Where did you place the JS file? You might need to place it in the `/web` folder to be used in the bundle process, but I'm not entirely sure. Maybe others can also help out here?

**Comment by Gibran-16** [comment]
Hi, thanks for your answer. Yes, it is in /web, precisely where the other .js files.

**Comment by yurydelendik** [comment]
Hard to tell without seeing the modification.

**Comment by Gibran-16** [comment]
Hi,

This is my .js file, it has more lines about some validations, drag and drop etc.

![11_modified](https://cloud.githubusercontent.com/assets/11055909/19893821/2b2e29bc-a010-11e6-9492-50ddbebfc23f.png)

This files is app.js where I added some things to integrate my .js.

![22_modified](https://cloud.githubusercontent.com/assets/11055909/19893844/47464b20-a010-11e6-89f2-29cd02735adf.png)

The problem is when I compile, it does not add my pdf_signature_box.js to viewer.js. I don't know how to do it. If I run gulp server all that I did works fine.

Thanks

**Comment by yurydelendik** [comment]
Several things:
- I see pdf_signature_box has some require() for jquery -- they will not be packaged by our packager -- add them to the viewer.html
- Change pdfjsWebPDFsignature_boxMode to e.g. pdfjsWebPDFSignatureBox -- you will see warning when running `gulp lint`

**Comment by Gibran-16** [comment]
> _I see pdf_signature_box has some require() for jquery -- they will not be packaged by our packager -- add them to the viewer.html_

Yes I use jquery, I installed jquery using npm install, t works and it is in the viewer.html. 
I compiled and all changes that I did in app.js were added to viewer.js, but not pdf_signature_box.
For example I see that pdf_presentation_mode.js is added to viewer.js, How is this added?

Thanks

**Comment by yurydelendik** [comment]
It is added automatically by our packager. Looks like you are doing everything right except two things I mentioned above at https://github.com/mozilla/pdf.js/issues/7770#issuecomment-257591086

**Comment by timvandermeij** [comment]
Closing as answered.
