### ISSUE TITLE
pdf.js doesn't work in IE9, it look like a 'cross domain request' problem

### ISSUE THREAD

**Issue by hdfeng265** [mozilla/pdf.js#7772]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:IE9
- Operating system and its version:WIN8
- PDF.js version:pdfjs-1.5.188-dist
- Is an extension:i don't know 

Steps to reproduce the problem:
1. my code:
```
PDFJS.getDocument('another domain').then(function(pdf) {
    		debugger;
    		pdf.getPage(1).then(function(page) {
    			debugger;
   			});
    	});
```
2.run in IE9

What went wrong? (add screenshot)
the code work well in Chrome,IE10,even the url is different origin.
but it didn't work in IE9 when the url is different origin.
pdf.js went wrong before it go to fetch the pdf in the url.
the error message is : 

> Warning: Unhandled rejection: Error: 拒绝访问。
 
拒绝访问 means 'refuse to access'.

**Comment by timvandermeij** [comment]
Your browser may prevent you from doing this due to security reasons. Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr on how to do this instead.
