### ISSUE TITLE
View is not updating on the file change 

### ISSUE THREAD

**Issue by ayushjamsaria** [mozilla/pdf.js#7776]
Link to PDF file (or attach file here): 

Configuration:
- Web browser and its version: Google Chrome
- Operating system and its version: Windows 10
- PDF.js version: Stable (v1.5.188)

Steps to reproduce the problem:
1. Open viewer.html in a iframe on other page. 
2. PDF File gets changed (suppose i removed a page from the file) for this i'm deleting the existing file and putting a new file with some less pages but with the same name. File name remains same 

What is the expected behavior? (add screenshot)
If i refresh the page It should show the content of the updated file or new file. 

What went wrong? (add screenshot)
If i refresh the page it is showing the previous file content. It should show the content of the updated file or new file. Because of cache this problem is there? 

Using the same viewer.js and viewer.html downloaded from github

**Comment by timvandermeij** [comment]
Yes, this is a caching problem, either on the browser side or the server side. From the posted information there appears to be nothing that can be done about it on the PDF.js side.
