### ISSUE TITLE
Is there any other way to load pdf without url or file path?

### ISSUE THREAD

**Issue by nikhilreddy93** [mozilla/pdf.js#7777]
In the below code i have used url to load the pdf,
var url = 'http:localhost:8080/file.pdf';
PDFJS.getDocument(url)
	    .then(function(pdf) {
}

 but is there any other way to load the pdf other than the above method like 
for example : 

PDFJS.getDocument(data)
	    .then(function(pdf) {
}

**Comment by yurydelendik** [comment]
`PDFJS.getDocument(data)` will work, as well as `PDFJS.getDocument({data: data})` See https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L146

**Comment by nikhilreddy93** [comment]
Here is my code
Path pdfPath = Paths.get("D:/project/file.pdf");
	byte[] pdf = Files.readAllBytes(pdfPath);
	String pdfString = new String(pdf);

var array = convertDataURIToBinary('<%=pdfString%>');
			console.log('byteArray = ' + array);
			var BASE64_MARKER = ';base64,';
			function convertDataURIToBinary(dataURI) {
				  var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
				  var base64 = dataURI.substring(base64Index);
				  var raw = window.atob(base64);
				  var rawLength = raw.length;
				  var array = new Uint8Array(new ArrayBuffer(rawLength));

				  for(i = 0; i < rawLength; i++) {
				    array[i] = raw.charCodeAt(i);
				  }
				  return array;
				}

PDFJS.getDocument(array,null,null,progressCallback)
	    .then(function(pdf) {
}

I'm getting this error  "Uncaught SyntaxError: Invalid or unexpected token" below is the screen shot

![error](https://cloud.githubusercontent.com/assets/12526688/19957957/120060ba-a1c1-11e6-901a-8a666aafa3c3.PNG)

**Comment by nikhilreddy93** [comment]
@yurydelendik  Got it. Thanks.
