### ISSUE TITLE
Enabling to add watermarks on pdf.js pages

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7783]
This would be a nice additional feature:

Enabling to add watermarks on pdf.js pages especially printing.

Or perhaps is there a variable where we can get references to all the canvas pages that will be printed? so we can add our own watermarks?

**Comment by timvandermeij** [comment]
This is out-of-scope for the PDF.js library itself, but may indeed be useful for custom solutions. Recently the printing code has been refactored, so you should be able to adapt the `printService` to add any watermarks to printed canvases.

**Comment by chitgoks** [comment]
thank you for this tim. i have one tiny question. i am using the stable version of pdf.js yet when i search through the code, there is no string of printservice that can be found.

is this not found in viewer.js?

**Comment by timvandermeij** [comment]
It's introduced in #7697, so it's not in the stable version yet. In the stabl version I think there is `beforePrint`.

**Comment by chitgoks** [comment]
hi tim. thank you. i have checked beforePrint before but i am not quite familiar since it returns a PDFPageView but when beforePrint() is called, it does not seem to return anything looking at the current codebase.

i am planning to also listen to the beforeprint event, is it possible to have it return that pdfpageView object in the next version? i think adding canvas with the watermark inside every canvasWrapper can do the trick.

please advise.

**Comment by chitgoks** [comment]
hi tim. question, is there a function that gets called when all the rendering is finished before the print preview pane displays them all?

that is where i plan to re-draw the canvas and add the watermarks. please advise.

there are only beforeprint and afterprint events and modifying the canvases inside beforeprint still will not work since it seems the promise is the one that notifies that the rendering on the canvas is finished. unless i am mistaken.

**Comment by chitgoks** [comment]
hi tim. i have a question. i have managed to add watermarks to the pages during print preview and have verified during printing as well. but this is in chrome.

when i used firefox and IE  that do not have print preview panes, beforePrint does not get called nor is there any beforeprint event that gets fired. for this scenario, where should i look at in order to add watermarks to the pages?

please advise

**Comment by timvandermeij** [comment]
Strange, because `beforePrint` should always be called to prepare the pages for printing. If not, the pages cannot be printed properly. I have done testing in Firefox/IE before and `beforePrint` was always called, most notably because changes in `beforePrint` (e.g., https://github.com/mozilla/pdf.js/commit/29947b5a570e07ca2ea2c2f14d5a3c7bcb838d4c) caused different printing in IE. If it's not called, probably something else is wrong, but it's not possible from the presented information to say for sure.

You could try using the current master branch with refactored printing code and see if that improves things. There is also https://github.com/mozilla/pdfjs-dist, a generic build of PDF.js that gets updated everytime we push a commit to the master branch, which you may consider.

**Comment by chitgoks** [comment]
in your end, does firefox and ie show no print preview pane as well? and beforeprint is still dispatched? 

i just did it like this

window.addEventListener('beforeprint', function() {
   console.log('beforeprint');
});

works in chrome, print preview pane shows up. but both firefox and ie shows the print popup window directly, no print preview.

**Comment by timvandermeij** [comment]
Firefox uses `mozPrintCallback`, so that is a difference compared to Chrome/IE. Recently this has been changed to use `mozPrintCallback` only for the Firefox add-on and not for the regular viewer in Firefox anymore, because of problems with `mozPrintCallback`. If you have not applied #7697, `mozPrintCallback` will also be used for the regular viewer in Firefox, so you can try to see if that is used. I'm not too familiar with `mozPrintCallback`, unfortunately, and the new patch reduced its usage to make it more uniform for all browsers.

**Comment by chitgoks** [comment]
hi tim. thank you. i'll check that out and give an update after getting some findings.

**Comment by chitgoks** [comment]
hi tim. apologies, firefox does call beforeprint. not used to using firefox all the time so i was looking at the wrong tab window in dev console. instead of logging, i was looking at JS. tsk.

case closed. thank you again.

**Comment by chitgoks** [comment]
hi tim. got another question regarding this. does firefox work differently compared to IE and chrome because of the mozPrintCallback? What I did was to get hold of the canvas inside the printContainer and place my watermarks there.

It works in Chrome and IE (no print preview but i confirmed it works when i printed it). But in firefox, it does not include my watermarks. 

Also, I noticed in Edge browser it does not print preview the pdf pages correctly. Sometimes it works, sometimes it does not. is this an ongoing issue yet? please advise

**Comment by timvandermeij** [comment]
Yes, Firefox may behave differently because of `mozPrintCallback`. Recently we fixed a lot of printing issues (including IE/Edge problems) and made the printing code more the same in all browsers. Now, only the Firefox *add-on* uses `mozPrintCallback`, whereas the regular viewer does not anymore, to make it more in line with other browsers. I would recommend you to use the latest PDF.js master branch or, better yet, `pdfjs-dist` to get all these fixes. The current release version does not contain them yet.

**Comment by chitgoks** [comment]
is there be a plan to streamline all browsers to use the same including firefox? i figure i don't need to add code specifically for firefox if this is the plan going forward.

and also because i still could not figure out when to add the watermarks in all the canvas of printContainer in Firefox. the beforeprint does show that printContainer has all canvas inside but i believe it has not yet been rendered so my function to display watermarks gets wiped out when pdf.js renders the pages.

**Comment by timvandermeij** [comment]
Everything is already streamlined, except for the Firefox add-on version, but you'll probably not use that when developing a custom solution (the add-on is only intended for inclusion in Firefox itself).

For `mozPrintCallback`, I think you can check https://github.com/mozilla/pdf.js/blob/master/web/firefox_print_service.js#L70, but, as said, this should now only be for the add-on version which is probably not relevant for a custom solution.

**Comment by chitgoks** [comment]
ok. guess ill just disable the print button for firefox.

before i tried the ads.on, i tried printing it and i got no watermarks unlike ie and chrome.

thank you.

**Comment by GJ2511** [comment]
Hi @chitgoks Have you find any workaround for enabling watermark?

**Comment by chitgoks** [comment]
@GJ2511 yes. i have my own solution.

**Comment by GJ2511** [comment]
COuld you please provide some reference for help, 
As per my understanding mozPrintCallback doesn't get fired beforeprint( as Firefox don't provide print preview ).

**Comment by chitgoks** [comment]
you can install the print preview plugin in firefox so you will be able see your print preview in firefox.

what i did is get hold of the canvas of pdf.js and draw my watermarks there.

**Comment by GJ2511** [comment]
At what place you did that?

This is what I did so far (it's working for IE and Chrome)

```
function applyWatermarkToPrintedDocument(event) {
        //Remove listener so that the function will not cause problems when mozilla
        //attempts to use the real mozPrintCallback
        window.removeEventListener('beforeprint', this);

        var canvases = document.querySelectorAll('canvas');
        for (var count = 0; count < canvases.length; count++) {
            if (canvases[count].mozPrintCallback && !canvases[count].renderedWatermark) {
                //Override the default moz callback with new one.
                canvases[count].mozPrintCallback = mozCallbackOverride(canvases[count].mozPrintCallback);
                canvases[count].renderedWatermark = true;
            }
        }
    }
window.addEventListener('beforeprint', applyWatermarkToPrintedDocument, false);

function mozCallbackOverride(defaultMozPolyfillCallback) {
        var originalCallback = defaultMozPolyfillCallback;

        function newCallback(obj) {
            //Override the done callback to we are able to determine when rendering is complete. Use closure to retain
            //reference.
            obj.done = (function() {
                //grab the done object, for later calling
                //grab the contextObj
                var contextObj = obj;
                contextObj.done1 = obj.done;
                return function() {
                    isPrinting = true;

                    //Render watermark onto printing canvas
                    var watermarkSizes = calculateWatermarkSizes(contextObj.context.canvas);
                    watermarkSizes.canvas.context.save();
                    layoutRegion(watermarkSizes.canvas.context, watermarkSizes.top);//Here I am adding watermark
                    layoutRegion(watermarkSizes.canvas.context, watermarkSizes.middle);
                    layoutRegion(watermarkSizes.canvas.context, watermarkSizes.bottom);
                    watermarkSizes.canvas.context.restore();
                    isPrinting = false;

                    //Callback done object
                    contextObj.done1();
                };
            })();

            //fire original callback with new overridden object.
            originalCallback(obj);
        }

        return newCallback;
    }

```

**Comment by chitgoks** [comment]
i dont know how to override those functions in pdf.js since i dont understand their code. the only way that i did was to modify and add code in viewer.js. this would mean manually adding the changes for every new version of pdf.js

look at renderPage in viewer.js. it returns the canvas context. use that to draw your watermarks.

listening to beforeprint and afterprint didnt work out for me.

**Comment by GJ2511** [comment]
Oh ok, thanks for your help man :)

**Comment by chitgoks** [comment]
@GJ2511 can you email me at gmail. username is same. i wish to ask you something.

**Comment by chitgoks** [comment]
@GJ2511 did you manage to make it work in firefox?

**Comment by andreadd** [comment]
Hello, could you explain me how to add watermarks? I am using last version of pdf.js
Thank you!
