### ISSUE TITLE
Bad render of PDF file with images

### ISSUE THREAD

**Issue by dmitrirussu** [mozilla/pdf.js#7785]
Link to PDF file (or attach file here):

Configuration:
- any
- any
- v1.6.210               
- no

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. download file [https://drive.google.com/file/d/0B9izTHWJQ7xlSDJDbkN0TVhPZ1U/view](url)
3 upload PDF JS viewr demo Viewer 
4. Compair the preview
See all document, you will see crapped chars on image, strange behavior
thanks

**Comment by Snuffleupagus** [comment]
> download file [https://drive.google.com/file/d/0B9izTHWJQ7xlSDJDbkN0TVhPZ1U/view](url)

That link is unfortunately no longer available, closing as INCOMPLETE for now.
