### ISSUE TITLE
Artefacts

### ISSUE THREAD

**Issue by rhazor** [mozilla/pdf.js#7787]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Latest Firefox, Latest Chrome
- Operating system and its version: Windows 7,8,10 (tested on multiple machines)
- PDF.js version: latest stable 1.5.188 from https://mozilla.github.io/pdf.js/getting_started/
- Is an extension: Drupal module https://www.drupal.org/project/pdf

Steps to reproduce the problem:
1. Visit http://209.240.154.13/emc/pdf/new-patient-information-form

What is the expected behavior? expect to look clean

What went wrong? artefacts/squares
![untitled-1](https://cloud.githubusercontent.com/assets/22996586/20014475/cd88d002-a2bf-11e6-9f44-b23ceb6e5c68.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://www.drupal.org/project/pdf
http://209.240.154.13/emc/sites/all/libraries/pdf.js/build/pdf.js

No artefacts if downloaded to desktop via Firefox and opened in Adobe Acrobat.
Contains artefacts if printed directly from Firefox viewer.

**Comment by timvandermeij** [comment]
Direct link to the PDF file: http://209.240.154.13/emc/sites/default/files/pdf/hipaa-pt-info-w-design-website-9-13.pdf

**Comment by brendandahl** [comment]
@rhazor Do you have an updated link to the PDF?

**Comment by rhazor** [comment]
what year is this

**Comment by Snuffleupagus** [comment]
> Do you have an updated link to the PDF?

[issue7787.pdf](https://github.com/mozilla/pdf.js/files/1397867/issue7787.pdf)

Also, this issue *may* be similar to e.g. issue #8680.

**Comment by timvandermeij** [comment]
Fixed by #9340.
