### ISSUE TITLE
fontRef Error when drawing string with ReportLab

### ISSUE THREAD

**Issue by rkni9ht** [mozilla/pdf.js#7788]
Link to PDF file (or attach file here):
[font-bug.pdf](https://github.com/mozilla/pdf.js/files/575695/font-bug.pdf)
Tried with multiple files, writing number in bottom right corner with reportlab in python using following code:
```
c.setFillColorRGB(255, 0, 0)
c.setFont("Helvetica", 12)
c.drawString(width - 50, 10, text)
```

Configuration:
- Web browser and its version: Firefox 49.0.2

Steps to reproduce the problem:
1. open the pdf file in the browser

What is the expected behavior? (add screenshot)
Expected to see bates number in bottom right. 
![capture](https://cloud.githubusercontent.com/assets/15227621/20062765/d40345b8-a4fc-11e6-98d5-0fcdff919d1d.JPG)

What went wrong? (add screenshot)
It doesn't load the text and prints to console:
```
Warning: fontRef not availablepdf.worker.js:2298:5
Warning: Error during font loading: Font F1 is not availablepdf.js:277:5
Warning: fontRef not available
```

**Comment by timvandermeij** [comment]
Closing since this one is fixed now.
