### ISSUE TITLE
Problem in rtl fonts

### ISSUE THREAD

**Issue by aminmk** [mozilla/pdf.js#7795]
Hi
Thank you for your great library. 
I have an issue in one of my pdf files. The rtl (Persian) font isn't rendered properly. The right format and the wrong one are shown below, respectively. I have tested my code with both Chrome and Firefox browsers and the code is simply copied from the "hello world" example. I must also mention that the code works properly for my other rtl pdf files but this one.
![true](https://cloud.githubusercontent.com/assets/19909067/20131354/2c15af68-a672-11e6-801a-d35b8eeb518a.jpg)
![wrong](https://cloud.githubusercontent.com/assets/19909067/20131355/2c1b0e86-a672-11e6-8bb2-0a7f22b6e238.jpg)
Thanks a lot

**Comment by Snuffleupagus** [comment]
As is, this issue will be closed as incomplete.
Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, without e.g. the PDF file in question there's nothing that can be done here.

**Comment by Snuffleupagus** [comment]
Closing as incomplete; please provide *all* the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) to re-open.
