### ISSUE TITLE
fix bug in evaluator js cause text extractor to break with exception

### ISSUE THREAD

**Issue by ereuven** [mozilla/pdf.js#7804]
File: src/core/evaluator.js

Bug:
Line 1421: args.length = 0;
Sometimes args is null and running exits with exception.

Fix: 
Add before this line:
if (args === null) {args = [];}

**Comment by Snuffleupagus** [comment]
Please provide all the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; especially important here is a PDF fie that can be used to reproduce the issue.

**Comment by ereuven** [comment]
I created a pull request with full details.

**Comment by timvandermeij** [comment]
Closing as fixed by #7819.
