### ISSUE TITLE
View PDF with Open File Dialog

### ISSUE THREAD

**Issue by ParthBDesai** [mozilla/pdf.js#7814]
Hello,

Can anyone help me ...In Viewing PDF File from my local PC using Open File Dialog with the help of PDFjs ?

**Comment by yurydelendik** [comment]
See demo viewer at http://mozilla.github.com/web/viewer.html (and the open file button). Closing as answered.

**Comment by ParthBDesai** [comment]
Page Not Found on that Link

**Comment by timvandermeij** [comment]
This one works: https://mozilla.github.io/pdf.js/web/viewer.html
