### ISSUE TITLE
IOS webview APP error: Unexpected server response (206) while retrieving PDF...

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7815]
Link to PDF file (or attach file here):
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version:微信WeChat 6.3.27
- Operating system and its version:IOS 10.0.3
- PDF.js version:1.6.319

Steps to reproduce the problem:
1. Open 微信WeChat
2. view: https://mozilla.github.io/pdf.js/web/viewer.html

What went wrong? (add screenshot)

![pdfjs](https://cloud.githubusercontent.com/assets/2181421/20309225/244afce2-ab82-11e6-8126-01f60e727489.jpg)

**Comment by yurydelendik** [comment]
Looks like WeChat (the browser we don't support) has no "Safari" in it's user agent string (?). I cannot find any specific documentation on what user agent string shall be, probably something along "MicroMessenger/6.3.27" lines. We don't know market share of WeChat + PDF.js users, so I don't think we shall rush into adding that to the compatibility.js.

**Comment by godwin668** [comment]
Until March, 2016, there are 0.927 billion active WeChat users in China. So it is very important to solve this PDF.js bug on WeChat. @yurydelendik

**Comment by yurydelendik** [comment]
>  0.927 billion active WeChat users in China

- how many of them use PDF.js?
- how many of them use iOS 10?

**Comment by yurydelendik** [comment]
> So it is very important to solve this PDF.js bug on WeChat.

@godwin668 we gave it a try with #7800, but it did not work for you. Can you help us with proposing a solution?

**Comment by godwin668** [comment]
@yurydelendik I do NOT know exact number but I do know two professional online preview provider is using PDF.js in China.

I'm NOT specialty in PDF.js, but I will try.

**Comment by godwin668** [comment]
@yurydelendik I tried and succeeded.
