### ISSUE TITLE
Integrating pdf.js in a angular 1.x app.

### ISSUE THREAD

**Issue by TomVanHaver** [mozilla/pdf.js#7820]
Hi,

We want to show pdf's in our angular 1.5.x application with a (slightly) different layout then in the viewer.html.

There are 2 scenario's possible (we are now going for scenario B, since we believe we can easily update the pdf.js lib this way)

# **scenario A** 
Host a fully functional viewer (like the gh-pages package) at for example AWS  and just call the viewer.html with a ?file= parameter.

**QUESTION**: 
1. the pdf.js version used in gh-pages package is the latest (unstable?) version, is there a stable package that we can host (and adapt the viewer to our liking)?

# **scenario B** 
integrate the viewer in our solution.

We have a working solution now, but have a few questions.
SETUP:

> We have taken files from the pdfjs-dist npm package AND have copied files from the /web folder in the gh-pages zip to our app/studio/assets/pdf-js/web folder in the solution:

A. we have a gulp task that (tries) to minify the pdf.worker.js file from pdfjs-dist:

```
gulp.task('minify-pdf-worker', () => {
    gulp.src('node_modules/pdfjs-dist/build/pdf.worker.js')
        .pipe(minify({
            ext: {
                src: '.js',
                min: '.min.js',
            },
            noSource: false, // SEE QUESTION 3 BELOW
            // mangle: false,
        }))
        .pipe(gulp.dest('target/app/bundle'));
});
```

B. webpack build:

we have the following in our webpack.config :

entry 
```
pdfViewer: [
                './node_modules/pdfjs-dist/web/compatibility.js', 
                './app/studio/assets/pdf-js/web/pdf.js.entry.js', 	// SEE BELOW FOR CONTENTS
                './app/studio/assets/pdf-js/web/l10n.js',
                './app/studio/assets/pdf-js/web/change_viewer_locale.js', // SEE BELOW FOR CONTENTS
            ],
```
and 

  ```
  new HtmlWebpackPlugin({
                filename: '../studio/assets/pdf-js/web/viewer.html',
                template: './app/studio/assets/pdf-js/web/viewer_modified_template.html', // SEE BELOW FOR CONTENTS
                minify: {
                    removeComments: true,
                },
            }),
```
pdf.js.entry.js :
```
const w = (typeof window !== 'undefined' ? window : {});
w.pdfjsDistBuildPdf = require('pdfjs-dist/build/pdf.js');
```

change_viewer_locale.js :
```
/*eslint-disable */
PDFJS.locale = 'nl';
```

C. files in our solution (copied from the gh-pages zip):

```
app\studio\assets\pdf-js\web\
\cmaps // EXACT COPY
\images // EXACT COPY
\locale // EXACT COPY
l10n.js // EXACT COPY
viewer.css // ADAPTED TO OUR LIKING
viewer_modified.js 	// SEE BELOW FOR MODIFICATIONS
viewer_modified_template.html // SEE BELOW FOR MODIFICATIONS
```

viewer_modified_template.html :
copy from gh-pages with following change:
```

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="google" content="notranslate">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PDF.js viewer</title>
    <link rel="stylesheet" href="viewer.css">

    <!-- This snippet is used in production (included from viewer.html) -->
    <link rel="resource" type="application/l10n" href="locale/locale.properties">

    <!--WEBPACK - DO NOT CHANGE SEQUENCE-->
    <script src="{%=o.htmlWebpackPlugin.files.chunks.common.entry%}"></script>
    <script src="{%=o.htmlWebpackPlugin.files.chunks.pdfViewer.entry%}"></script>

    <script src="viewer_modified.js"></script>
</head>
```

viewer_modified.js :
copy from gh-pages with following change:

 ```
function configure(PDFJS) {
    PDFJS.imageResourcesPath = './images/';
    PDFJS.workerSrc = '../../../../bundle/pdf.worker.js'; <==== point to the worker.js file from the minify-pdf-worker gulp task above.
    PDFJS.cMapUrl = '../web/cmaps/';
    PDFJS.cMapPacked = true;
   }
```

**Questions:**

1. is there some improvement possible in our setup? Now the files are taken from here and there which feels brittle.
2. in our webpack entry, we load the compatibility.js BEFORE the pdf.js, i read that this is necessary?
3. when we try to minify the worker.js (see gulp task above) AND the chrome devTools are active, chrome crashes.
4. is it possible to move the "copied" files/scripts out of the pdf-js/web/ folder directly under the pdf-js/ folder?
5. how can debugging be enabled ? i tried adding the query param, but no result.
6. can the locale be set in another way then via the change_viewer_locale.js (see above)
7. the pdfjs-dist is the latest version, can we depend on a stable version?

Thank you very much for taken the time to help us.
Tom.

**Comment by yurydelendik** [comment]
> the pdf.js version used in gh-pages package is the latest (unstable?) version, is there a stable package that we can host (and adapt the viewer to our liking)?

Yes, check https://github.com/mozilla/pdf.js/releases for list of release/pre-release viewer packages.

> 1. is there some improvement possible in our setup? Now the files are taken from here and there which feels brittle.

If it's possible try to use only files from pdfjs-dist -- gh-pages' viewer.*  files might change. Best way is to rely on pdfjs-dist files and implement toolbars/UI yourself.

> 2. in our webpack entry, we load the compatibility.js BEFORE the pdf.js, i read that this is necessary?

It's needed for legacy browsers. If your users only use modern browsers without defects you may ignore this file.

> 3.  when we try to minify the worker.js (see gulp task above) AND the chrome devTools are active, chrome crashes.

No PDF.js problem. Report the issue to the Chrome DevTools team.

> 4. is it possible to move the "copied" files/scripts out of the pdf-js/web/ folder directly under the pdf-js/ folder?

Yes. In custom deployment you can choose any location.

> 5. how can debugging be enabled ? i tried adding the query param, but no result.

See https://github.com/mozilla/pdf.js/wiki/Debugging-PDF.js but it looks like the debugger integration is broken by the custom deployment. Also it's part of the demo viewer from troubleshooting PDFs. I don't think you will need it as a part custom deployment -- you can always use demo viewer to do that.

> 6. can the locale be set in another way then via the change_viewer_locale.js (see above)

Yes, you don't have to use demo viewer way to localize -- remove mozL10n/webL10n library is use your own.

> 7. the pdfjs-dist is the latest version, can we depend on a stable version?

Yes

Closing as answered.
