### ISSUE TITLE
selecting thumbnails via ctrl+click

### ISSUE THREAD

**Issue by Godrules500** [mozilla/pdf.js#7823]
Mine is more of a question. I want to ctrl + click the thumbnails so that I can print out specific ones. Is there a way to do this with pdf.js?

**Comment by timvandermeij** [comment]
No, you would have to implement this yourself. You can get the page number of the thumbnail on Ctrl+click (by parsing its ID or by adding a `data` attribute) and edit the printing code to pass the selected page numbers and print only those. Closing as answered.
