### ISSUE TITLE
main.worker.js?

### ISSUE THREAD

**Issue by mark-norgate** [mozilla/pdf.js#7827]
I have built `pdf.js` in accordance with [these instructions](https://github.com/mozilla/pdf.js/#building-pdfjs). The code generated includes this line:

```
var worker = new Worker(workerSrc);
```

Chrome is complaining that it cannot find the file `GET http://localhost:8100/build/main.worker.js`.

Now then, I have not come across web workers before, so I'm not sure what this error means or where to find, or build, this file. I notice that the build process also yields a file called `pdf.worker.js`, and I have strong suspicions that this might be the file it's after, although renaming it to `main.worker.js` had no effect.

I'm sure this is a very simple problem if you are in the know. What am I missing?

<hr></hr>

Ok, after a little more digging, I found [this](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website) which pertains more to my situation. I am using Ionic 2 and I don't know how to generate the file referenced in this line:
```
pdfjsLib.PDFJS.workerSrc = '../../build/webpack/pdf.worker.bundle.js';
```
Can anyone illuminate my dark mind?

**Comment by agilgur5** [comment]
@mark-norgate you'd probably find the information [issue I previously filed](https://github.com/mozilla/pdf.js/issues/7612) helpful. See also #7683

**Comment by distante** [comment]
@mark-norgate did you manage to fix this? I have the exact same problem.

**Comment by yurydelendik** [comment]
> What am I missing?

You need to specify PDFJS.workerSrc or PDFJS.workerPort. Using 'pdfjs-dist/webpack' with provide workerPort automatically (see #8107). Closing as answered.
