### ISSUE TITLE
IE10 callback/promise issue in  setupFakeWorkerGlobal function  

### ISSUE THREAD

**Issue by NileshkumarPrajapati** [mozilla/pdf.js#7831]
Hi, 

I am facing issue to return promise of worker setup function in IE10. in other browser like IE9, IE11 & chrome it's working fine but in IE10 pdf is not rendering in HTML canvas and XHR service call not going to read pdf file.

I have already added compatibility.js

PDF.js / Line no 9581
---------------------------------------------------------------------------------------------
 function setupFakeWorkerGlobal() {
           var WorkerMessageHandler;
                   if (!fakeWorkerFilesLoadedCapability) {
                        fakeWorkerFilesLoadedCapability = createPromiseCapability();                     
                        var loader = fakeWorkerFilesLoader || function (callback) {
                            Util.loadScript(getWorkerSrc(), function () {
    **Note: In IE10 callback called before return promise.**
                                callback(window.pdfjsDistBuildPdfWorker.WorkerMessageHandler);
                            });
                        };
                        loader(fakeWorkerFilesLoadedCapability.resolve);
                    }
                    return fakeWorkerFilesLoadedCapability.promise;
                }

-------------------------------------------------------------------------------------
 _setupFakeWorker: function PDFWorker_setupFakeWorker() {
               
                        setupFakeWorkerGlobal().then(function (WorkerMessageHandler) {
***** _inside then Code not calling in IE10._ **
                              if (this.destroyed) {
                                this._readyCapability.reject(new Error('Worker was destroyed'));
                                return;
                            }
*****_So service call not going to read pdf file._**
                        }.bind(this));
                    },

Thanks You...

**Comment by timvandermeij** [comment]
This issue will be closed as incomplete in its current form. Please provide *all* information requested in the issue template (https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and make sure that you provide a runnable example for us to test with. We cannot debug the issue with just code snippets.

**Comment by NileshkumarPrajapati** [comment]
No in IE10 console not giving any error or warning.

**Configuration:**
Web browser and its version:   64 bit IE V.10
Operating system and its version: Windows 7 Enterprise  64-bit
PDF.js version:    var pdfjsVersion = '1.5.188';
Is an extension:   No

**Steps to reproduce the problem:** 
step 1.
in getDocument() function creating new worker instance. (line # 8766)
step 2.
During PDFWorker initialize  _setupFakeWorker function called (line # 9748)
step 3. 
in setup fake worker, SetupFakeWorkerGlobal() function called with promise.(line # 9757)
step 4.
Code between SetupFakeWorkerGlobal(),then({}) not executed in IE10 as loader(fakeWorkerFilesLoadedCapability.resolve) returns before return promise (line# 9590)

**What is the expected behavior? (add screenshot)**
First promise must return from SetupFakeWorkerGlobal() & then call back function called once Util.loadscript() function load worker script. (line # 9595)

**What went wrong? (add screenshot)**
pdf.worker.js file load from server but after that XHR service call not going to Read/Load PDF file. Problem is in IE 10 only. might be loader function create issue ? 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by NileshkumarPrajapati** [comment]
Hi Tim,
During Analysis i found that there was one existing library in my project having code for promise/polyfill which was creating issue in our promise in IE10. after removing that code currently its working fine in all browser which we are currently supported.

Thank you so mush for your kind support & such good library which helps a lot.
