### ISSUE TITLE
Select box support & save pdf

### ISSUE THREAD

**Issue by guruganesh26** [mozilla/pdf.js#7843]
Hi,

I started using pdf.js, it is amazing and great work from you guys. i need to know two things from that,

1) In the example acroforms, it says select box is not supported, but i checked some of the code merges regarding select boxes, please share how to do the select box in pdf to html conversion.

2) How to save to pdf after html conversion, my case using pdf.js i converted the pdf (which contains form) and displayed as html, now the user can fill that. but i don't know how save back to pdf(filled html) again. 

Your suggestion will help us lot.

Thanks

**Comment by timvandermeij** [comment]
You can enable the **experimental** `renderInteractiveForms` flag at https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L17, but do note that this is not ready yet and its functionality may change in the future.

Saving back to PDF is not implemented and it's not sure if we ever will. Maybe we'll only support printing the filled in PDF, not re-saving it. There is a different issue for AcroForms support where we're tracking this, so I'm closing this one.
