### ISSUE TITLE
ios10的版本问题

### ISSUE THREAD

**Issue by shidfdfdf** [mozilla/pdf.js#7848]
![99366dcf2aeeb2c18e6d1e75d47be4bb](https://cloud.githubusercontent.com/assets/23722812/20601510/fc0d32c2-b293-11e6-86d1-e0e252efdd32.png)
![2d095b63254d398a2975b08fde9d04e9](https://cloud.githubusercontent.com/assets/23722812/20601531/0f1f8702-b294-11e6-96cc-5c9248341cbe.png)
![2d095b63254d398a2975b08fde9d04e9](https://cloud.githubusercontent.com/assets/23722812/20601533/13ce0fc6-b294-11e6-8137-7793f66b39ab.png)

ios手机app里引用的pdf.js，从手机app里打开的效果和手机浏览器上不一样，从手机app里打开，最下面的那行地址怎么去掉？点击下载后，不能分享，不能保存到其他地方，只能查看，点击打印无反应，这是最新的版本1.6.   这是什么原因呢？

**Comment by Snuffleupagus** [comment]
Closing as invalid; please use English when reporting bugs (or asking questions), since we'll not be able to help otherwise.
