### ISSUE TITLE
All pages are loaded with the completion event, I want to perform the print operation.

### ISSUE THREAD

**Issue by acivan** [mozilla/pdf.js#7851]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. In viewer.js,All pages (canvas) are loaded with the completion event. I want to perform the print operation.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by acivan** [comment]
listener textlayerrendered event solved my problem

**Comment by JimmyBoh** [comment]
Does anybody have a snippet of a way to get this working with the viewer? I see the `renderedPromise` in the source but I can't seem to find that promise.
