### ISSUE TITLE
PDFViewerApplication.findController.executeCommand deprecated?

### ISSUE THREAD

**Issue by zett-sail** [mozilla/pdf.js#7854]
I've been using this function in my viewer, I updated my pdf.js build to the latest last night and this function is no longer available. I'm a little confused - can someone advise what the replacement function looks like? 

In my code I'm using it in this context:

`  iframe.contentWindow.PDFViewerApplication.findController.executeCommand('find', {query: term});`

**Comment by timvandermeij** [comment]
It's still there: https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js#L286. Closing as answered since no more information is provided.
