### ISSUE TITLE
About a pdf file display problem with png files

### ISSUE THREAD

**Issue by ArthurZhan** [mozilla/pdf.js#7860]
Hello, I am using PDF.js in my development project as an online PDF viewer.

But I found one thing is that when my PDF file with PNG format transparent image as a watermark

This PDF file in the Acrobat software is normal to see the watermark

But can not be seen in pdf.js.

But if the jpg format files can be converted to normal display.

However, because the jpg file does not transparent background function will cover the contents of the original file, so in fact still must
To use the png format image as a PDF file in the watermark.

Some people know how to solve this problem?

Thank you!

**Comment by timvandermeij** [comment]
Closing as incomplete. This should work properly unless the PDF file is malformed or there is a bug in PDF.js. However, it's impossible to tell because the information from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md has not been provided.

**Comment by ArthurZhan** [comment]
Hello :

I can not use the New Issue feature in GitHub can be Attache File function.

Because I use the pdf.js website is open on the Internet, it can not use the url link
Provide a pdf file for your reference.

Can you please tell me how to add the file up?

Thank you!

**Comment by ArthurZhan** [comment]
Hello , I found the way to upload files
Thank you.

**Comment by THausherr** [comment]
But nothing is attached.

**Comment by timvandermeij** [comment]
Another issue has been opened that contains the information.
