### ISSUE TITLE
On IE11 can not be normal PDF.JS display PDF transparent image watermark problem

### ISSUE THREAD

**Issue by ArthurZhan** [mozilla/pdf.js#7864]
**Link to PDF file (or attach file here):**

[WithGif.pdf](https://github.com/mozilla/pdf.js/files/626303/WithGif.pdf)
[WithPng.pdf](https://github.com/mozilla/pdf.js/files/626304/WithPng.pdf)

**Configuration:
- Web browser and its version:**
  (1) These Web Browser is show the watermark well :
            Google Chrome 54.0.2840.99 m (64-bit) 
            Mozilla Firefox 50.0.2
            Opera 41.0.2353.69

  (2) Microsoft Internet Explorer 11 show watermark wrong

**- Operating system and its version:** Microsoft Windows 7 64bit
**- PDF.js version:** v1.5.188
**- Is an extension:**

**Steps to reproduce the problem:**

Hello, I found that if the PDF file to insert PNG format or GIF format transparent background image file as a watermark,
Use pdf.js in Microsoft Internet Explorer 11 to view this pdf file
This watermark can not be displayed.

At present, only the watermark can not be displayed, the other content is normal.

IE 11 browser can not be displayed in the top left corner of each page, such as the following contains the text of the watermark:

![watermark_productiondoc](https://cloud.githubusercontent.com/assets/24282861/20821874/38c517be-b881-11e6-9f75-216461496209.png)

But in Google Chrome 54.0.2840.99 m (64-bit), Mozilla Firefox 50.0.2, Opera 41.0.2353.69
These three browsers can be normal display.

I think this should be pfg.js and IE 11 browser with a transparent picture of the PDF file support a problem.

Because in practice, floating watermark should be transparent to the background of the file, so as not to cover the background content of the file.

Whether I use the v1.5.188 version downloaded on GitHub: https://mozilla.github.io/pdf.js/getting_started/#download
Or I can use the GitHub online pdf.js browser: https://mozilla.github.io/pdf.js/web/viewer.html

Have this problem.

**What is the expected behavior? (add screenshot)**
![right](https://cloud.githubusercontent.com/assets/24282861/20821849/154f059c-b881-11e6-895c-edcb7ead5c4a.png)

**What went wrong? (add screenshot)**
![error](https://cloud.githubusercontent.com/assets/24282861/20821852/191d3298-b881-11e6-8dbf-73ae47ef99be.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by StepanMelnik** [comment]
We have the same problem with pdf background in IE11 in some specific versions
![ie_11__invisible_pdf_background](https://cloud.githubusercontent.com/assets/3713877/21101584/2642d3a0-c07a-11e6-9afb-d52c436bd978.png)
![ie_11__visible_pdf_background](https://cloud.githubusercontent.com/assets/3713877/21101585/2645ef36-c07a-11e6-95bc-e52135dceb3a.png)

 only

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
