### ISSUE TITLE
Wrong rendering of text layer

### ISSUE THREAD

**Issue by sanketbajoria** [mozilla/pdf.js#7865]
Please, help me with this, Not able to point out the issue. 

Link to PDF file (or attach file here):
[GROUPING_JobMarch2RUCHI.1.pdf](https://github.com/mozilla/pdf.js/files/627799/GROUPING_JobMarch2RUCHI.1.pdf)

Configuration:
- Web browser and its version: Chrome 54.0.28
- Operating system and its version: Window 7
- PDF.js version: PDF.JS 0.8.0
- Is an extension: No

Steps to reproduce the problem:
1. Just upload the attached pdf. 
2. And render the text layer

What is the expected behavior? (add screenshot)
Text layer should align properly. 
What went wrong? (add screenshot)
All Text items get aligned, other than 2 words, Account Number. Attached the screenshot of the same, 
In screenshot, the light red color is text layer, and black color is actual content.
For wrong placement, I have marked it with border blue color.
![bug2](https://cloud.githubusercontent.com/assets/2969587/20844010/d141a428-b8e3-11e6-9a08-18b943e01853.png)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It looks like this is still a problem with the current development viewer, so we should keep tracking this.

**Comment by timvandermeij** [comment]
Closing since this is now fixed.
