### ISSUE TITLE
force web viewer to render all pages

### ISSUE THREAD

**Issue by rpedela** [mozilla/pdf.js#7867]
Is there a way to force the web viewer to render all pages? Is there a setting? If not, can you give a pointer to the section of code I need to change?

**Use Case**
I want to show all search matches in the scrollbar after the PDF loads similar to how Chrome's CTRL-F works. Right now I use JQuery to find all the matches by CSS class, get positions within document, and translate the positions to the scrollbar. I draw a custom scrollbar too.

**Problem**
```pdf.js``` only renders a few pages after the initial load so I cannot get the position of all matches. The user would need to scroll to the bottom in order to render all pages.

**Comment by timvandermeij** [comment]
You would have to do something similar as in the SVG viewer: https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer/viewer.js#L13.

**Comment by rpedela** [comment]
@timvandermeij Okay thanks. Is it possible to render the text layer only for all pages? That would be a good middle ground, but will the text line up with the view layer correctly? In other words, are the two layers completely independent?

**Comment by timvandermeij** [comment]
I believe that at the moment you have to render the page along with the text layer. You may be able to render only the text layer, but that's out of scope for the PDF.js project and you would have to implement that yourself. For example, use the text extraction example at https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L49 to obtain just the text layer.

**Comment by F2000-FR** [comment]
Maybe it can help : http://stackoverflow.com/questions/31185785/pdf-js-render-pdf-with-scrollbar/41851102#41851102
