### ISSUE TITLE
How to enable zooming by pinch gesture on mobile devices in presentation mode?

### ISSUE THREAD

**Issue by bevalorous** [mozilla/pdf.js#7875]
There are a lot of issues related to these topics. I'm a little bit confused with them, and after reading them all I still don't know if the solution of my problem exists.

Pdf.js viewer in presentation mode on mobile devices doesn't react to any gestures: press, swipe, pinch/zoom. But if PDF has big format (A4, for example), it's impossible to read it without zooming, because the document fits to screen and font is too small in presentation mode.

I've hacked viewer.js file and switched on the zooming in presentation mode for desktop browser (for example, if you click Ctrl + "+" in Chrome, the doc is zoomed in, and if you click Ctrl + "-", it is zoomed out). But PDF viewer doesn't react to zoom/pinch gesture on mobile phone touchscreen. 

I've tried to attach Hammer.JS to html element with id="viewer". I haven't got an error, but my handler of "pinch" event wasn't fired too.

Is there any possibility to use zoom/pinch gestures on mobile devices in presentation mode?

**Comment by Snuffleupagus** [comment]
Zooming was purposely disabled in Presentation Mode, please refer to the discussion in issue #5336; this is thus out-of-scope for the default PDF.js viewer.
Closing as answered.

**Comment by ibaritakis** [comment]
Hello bevalorous,

Can you please tell me how you have  hacked viewer.js file and switched on the zooming in presentation mode for desktop browser (for example, if you click Ctrl + "+" in Chrome, the doc is zoomed in, and if you click Ctrl + "-", it is zoomed out)?

Thanks

**Comment by bevalorous** [comment]
Hello @ibaritakis,

Just open `web/viewer.js` file and find out these pieces of code:
```
if (!isViewerInPresentationMode) {
    PDFViewerApplication.zoomIn();
}
```
and
```
if (!isViewerInPresentationMode) {
    PDFViewerApplication.zoomOut();
}
```
You should change conditions in these if-statements to something that always evaluated to true, for example, `if (true || !isViewerInPresentationMode) {`. 

That was my dirty trick ;-)

**Comment by ibaritakis** [comment]
Thanks @bevalorous!

I also did

` 
enableHandToolOnLoad: true,

enterPresentationMode: function handToolEnterPresentationMode() {
    if (this.handTool.active) {
      this.wasActive = true;
      //this.handTool.deactivate();
    }
  },

  exitPresentationMode: function handToolExitPresentationMode() {
    if (this.wasActive) {
      //this.wasActive = null;
      //this.handTool.activate();
    }
  }`

for enabling hand tool so you can move around when zoomed in

**Comment by bevalorous** [comment]
Thanks @ibaritakis !

**Comment by anubhavbansal727** [comment]
Hi @ibaritakis 
where did you add this code? can you please mention the file names to be more clear.
Thanks
