### ISSUE TITLE
Detecting download completed in pdf.js

### ISSUE THREAD

**Issue by timyounes** [mozilla/pdf.js#7882]
I am using pdf.js to my project I need to detect if pdf file is finished downloading.. Because I want to save logs in my database like date and time finished download.. 

Thanks in advanced

**Comment by timvandermeij** [comment]
There is https://github.com/mozilla/pdf.js/blob/fb4c4ffb97069cfb51a5162116b1bbc16f4fd055/web/app.js#L873 that becomes `true` when the download is complete. Closing as answered.

**Comment by timyounes** [comment]
How can I call this to my javasript function?

**Comment by timvandermeij** [comment]
You can monitor this member variable and add a database entry when it changes. How to include this in your custom solution is out of scope for the PDF.js project, so you'll have to implement that yourself.

**Comment by timyounes** [comment]
I am using viewer.js not api.js and I can't call the functions inside how can I monitor that member variable?
