### ISSUE TITLE
caching pdf files in pdf js

### ISSUE THREAD

**Issue by NiveditaKapil** [mozilla/pdf.js#7883]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since there's nowhere near enough information provided to understand what the problem might be here.
