### ISSUE TITLE
Load one page at time

### ISSUE THREAD

**Issue by Paulohrflores** [mozilla/pdf.js#7889]
Hi folks, I'm new here and I don't know if is allowed to post doubts here. I'm currently implement a simple web application, and I got pdf.js implemented. To my  application's success is crucial that is loaded (not just rendered) on page at time, cause my users doesn't relies on good internet connection, so retriving the full document is heavy for their connection and devices. I'm wondering if their a way of loading just the previous, current e next pages.

Thanks,

**Comment by yurydelendik** [comment]
Resources for one page are spread across entire PDF file (e.g. fonts or images), so in most of the cases you need to load entire file. If server provides HTTP range requests (and browser has no bugs in XHR) PDF.js tries to load only data needs for current page display and automatically download rest of the content later (the latter can be disabled via `disableAutoFetch`). Closing the issue as answered.

**Comment by Paulohrflores** [comment]
I've been thinking about split the file and then mask the page number. Of course scrolling will not be possible and there will be some delay to load the next page, but this will solve the overload of user's network.

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/issues/7889#issuecomment-266570630, provided that the server supports range requests, setting `PDFJS.disableAutoFetch = true;` before the `PDFJS.getDocument(...)` call will attempt to only load the data necessary for the current page; please refer to [src/display/global.js#L178-L188](https://github.com/mozilla/pdf.js/blob/00a006e466014439dd43813e5cd2d7ec86b79a9b/src/display/global.js#L178-L188).

**Comment by yurydelendik** [comment]
>  but this will solve the overload of user's network.

Not at all, every PDF-page will have fonts embedded which will increase total size of the transmitted data, as well as adding CPU overhead on parsing PDF header/footer/xref for each of the "page".

> Some advice?

In the past, most of the users suggested the similar solution, but nobody came back with measurements/benchmarks. So it's hard to tell if dividing PDFs into pages is any better than PDF.js's way of handing.

**Comment by Paulohrflores** [comment]
Thanks, I'll try the suggestion.
