### ISSUE TITLE
Is it possible to rotate single pdf page in pdfjs viewer?

### ISSUE THREAD

**Issue by nikhilreddy93** [mozilla/pdf.js#7892]
In my application I've embedded the pdfjs viewer, i'm able to rotate all the pages but i didn't find option to rotate a single page. How can i do that?

**Comment by timvandermeij** [comment]
You cannot do that at the moment. Right now https://github.com/mozilla/pdf.js/blob/fb4c4ffb97069cfb51a5162116b1bbc16f4fd055/web/app.js#L1226 takes care of the rotation of pages. You would have to modify that in your custom application to adjust the rotation of only one page. Closing as answered.

**Comment by powolnymarcel** [comment]
Still not possible in 2021 ?

**Comment by timvandermeij** [comment]
No, and we won't likely support this since there is no use case for that right now in the default viewer.

**Comment by ClaraPaiva** [comment]
Still not possible in 2024?

**Comment by zadeviggers** [comment]
This comes up quite often for me.

Often a document was scanned or photographed, and one page out of 10 is upside down. Additionally, appendices for portrait reports often include tables or figures formatted as landscape pages, so must be rotated to be read. This creates a frustrating experience when working across reference tables and body sections above.

I encourage the developers to include a control to rotate only the current page. It would be helpful to be exposed as a UI element, but even including a modifier to the existing keyboard shortcuts would resolve this frustration.
