### ISSUE TITLE
Safari Browser on Windows 10

### ISSUE THREAD

**Issue by smajid25** [mozilla/pdf.js#7902]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Safari Browser
- Operating system and its version: Windows 10

Steps to reproduce the problem:
1. Open the following link below in Safari within Windows 10 Operating System 
2. https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
Blank Screen
What went wrong? (add screenshot)
![safari issue](https://cloud.githubusercontent.com/assets/14893571/21316551/3bb30b7e-c5cf-11e6-86aa-c4db426069e7.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by smajid25** [comment]
Not sure what's going on, works in all the other browsers and operating systems that I have tried. Any help or understanding about the issue will be much appreciated.
Regards,
Sibghat Majid

**Comment by yurydelendik** [comment]
`SyntaxError: Cannot declare a parameter named 'href'  in strict mode` at line with `set href(href)` in the shared/util.js

**Comment by smajid25** [comment]
Can you explain what means?

**Comment by yurydelendik** [comment]
> Can you explain what means?

Looks like legacy Safari version has a bug in the JavaScript interpreter that falsely decides that naming parameter `href` is wrong since setter name is `href` as well.

**Comment by smajid25** [comment]
Looks like Safari dropped support for Windows years ago. Latest version I could get for Windows 10 was the legacy 5.1.7,  hence why this JS interpreter is not working properly. This issue is resolved now, thanks for the help.
