### ISSUE TITLE
Mac OSX WebView throws 206 error when render certain pdf files

### ISSUE THREAD

**Issue by lucozhao** [mozilla/pdf.js#7906]
Link to PDF file (or attach file here):
[1330.pdf](https://github.com/mozilla/pdf.js/files/665149/1330.pdf)

Configuration:
- Web browser and its version:  Mac WebView
- Operating system and its version:  Mac OSX 10.12.1 (16B2555)
- PDF.js version: 
var pdfjsVersion = '1.5.188';
var pdfjsBuild = '0e2d50f';
- Is an extension: No

Steps to reproduce the problem:
1. Open the pdf file
2. 

What is the expected behavior? (add screenshot)
Expect to render this as normal browser (Chrome/Firefox).

What went wrong? (add screenshot)
WebView cannot render it and shows below error:
PDF.js v1.5.188 (build: 0e2d50f)
Message: Unexpected server response (206) while retrieving PDF 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://www.moxtra.com/versions/3.0/vendor/pdfjs/web/viewer.html?file=xxx

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Mac WebView
> Operating system and its version: Mac OSX 10.12.1 (16B2555)

Safari based browsers have issues with range requests, which should explain this happens. Note that to prevent these kind of issues, [web/compatibility.js](https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js) should be setting `PDFJS.disableRange = true;` for Safari (and other problematic browsers).

I'd suggest checking to ensure that you've included `compatibility.js` in your custom viewer (as recommended in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support).

**Comment by lucozhao** [comment]
Thanks for the info. Latest compatibility.js changed the isSafari detect logic, looks like disableRange is true now for safari browser. However, Mac OSX WebView looks like to return userAgent without Safari wording, which looks like **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko)**,  not sure if pdfjs can optimize to include this embeded browser?

**Comment by yurydelendik** [comment]
> not sure if pdfjs can optimize to include this embeded browser?

If your viewer will be Mac OSX specific, just set disableRange.  For newer Safari we have only this issue, so you may not even include entire compatibity.js AFIAK.  It's hard to feature-detect this particular bug with XHR on our side. Closing as answered.

**Comment by yurydelendik** [comment]
@lucozhao if you feel confident that `AppleWebKit`-check will do the job (to fix your problem and not break other configurations), please submit a pull request to improve compatibility.js logic.
