### ISSUE TITLE
it's is difficult to render pdf in mobile browser with chinese language 

### ISSUE THREAD

**Issue by ideagay** [mozilla/pdf.js#7907]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:iphone6s safari
- Operating system and its version:
- PDF.js version:the latest version
- Is an extension:

Steps to reproduce the problem:
1. when i open the pdf in the mobile browser, it's ok for compressed.tracemonkey-pldi-09.pdf,but i want to open my own pdf that were in Chinese with 13 pages,the page always at loading state,it seems difficult to render the pdf? but it's ok for one page pdf that were in Chinese too.
what's the reason?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

![Uploading IMG_0089.PNG…]()

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Closing as incomplete.
