### ISSUE TITLE
Visualisation problems

### ISSUE THREAD

**Issue by amatsumiro** [mozilla/pdf.js#7908]
Link to PDF file (or attach file here): http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/111/95/491-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/112/96/493-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/113/97/494-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/115/98/495-1

Configuration:
- Web browser and its version: All, it happens more in google chrome and in opera,  happens less frequently in internet explorer and firefox.
- Operating system and its version: Windows and Linux
- PDF.js version:   1.0.907
- Is an extension: Yes

Steps to reproduce the problem:
1. Click the link in different Browsers and OS.
If visualization is weird:
2. Click fullscreen button
3. Press Esc

What is the expected behavior?
PDF should be showed well formated. 
![3](https://cloud.githubusercontent.com/assets/6704243/21390052/f250c1d0-c76b-11e6-907d-c28f166a832a.png)

What went wrong?
Some fonts problems.
![1](https://cloud.githubusercontent.com/assets/6704243/21390060/fd7d3d2c-c76b-11e6-9e3c-c062b10c59c1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/111/95/491-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/112/96/493-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/113/97/494-1
http://www.livrosabertos.sibi.usp.br/portaldelivrosUSP/catalog/view/115/98/495-1

**Comment by yurydelendik** [comment]
WFM on Mac OSX. Please provide exact versions of the Linux (and Windows) as well as browsers.

Can you reproduce this with the viewer at http://mozilla.github.io/pdf.js (files can be opened via the open file button)?

**Comment by amatsumiro** [comment]
Hi,


With viewer at http://mozilla.github.io/pdf.js I can't reproduce the error.

Let's starting getting just one OS and Browser.

OS: Windows 10 x64

Browser chrome: Versão 55.0.2883.87 m

Please open all the four links.
It does not happen every time.
I think it's cache-related.
After displaying the PDF correctly it does not show weird for a while.
After half an hour, weird reappears.


Regards.

_____________
Tarcisio Pereira


________________________________
De: Yury Delendik <notifications@github.com>
Enviado: quarta-feira, 21 de dezembro de 2016 11:46
Para: mozilla/pdf.js
Cc: Tarcisio; Author
Assunto: Re: [mozilla/pdf.js] Visualisation problems (#7908)


WFM on Mac OSX. Please provide exact versions of the Linux (and Windows) as well as browsers.

Can you reproduce this with the viewer at http://mozilla.github.io/pdf.js (files can be opened via the open file button)?

Pdf.js: PDF Reader in JavaScript - mozilla.github.io<http://mozilla.github.io/pdf.js>
mozilla.github.io
©Mozilla and individual contributors. PDF.js is licensed under Apache, documentation is licensed under CC BY-SA 2.5



-

**Comment by yurydelendik** [comment]
> PDF.js version: 1.0.907

> With viewer at http://mozilla.github.io/pdf.js I can't reproduce the error.

The viewer deployed at www.livrosabertos.sibi.usp.br is old version. We cannon upgrade third-party deployment. Please notify the admins of this site about the issue. Closing as fixed.

**Comment by amatsumiro** [comment]
Hi @yurydelendik 

Viewer deployed at www.livrosabertos.sibi.usp.br is now updated.
Now, this problem is less frequent.
From what I've noticed is only happening in chrome and never when I use the open button.
It's very strange.

Regards,
Tarcisio Pereira

**Comment by yurydelendik** [comment]
Sounds like #7136, but it's hard to guess or suggest anything without being able to reproduce the issue on different computer.
