### ISSUE TITLE
Extracting fonts from PDF?

### ISSUE THREAD

**Issue by matt-curtis** [mozilla/pdf.js#7914]
How does one go about accessing and extracting fonts from the PDF? It appears that pdf.js's font loading capabilities have been disabled, and instead it uses monospace and serif/sans-serif system fonts. I'd like to be able to extract fonts, whether for display/text selection or otherwise, if possible.

Additional question: How is getTextContent().styles.fontName derived? It doesn't seem to correlate with the font name in the actual page dictionary. In the case of the PDF 1.7 Reference, I see `g_d0_f1` and `g_d0_f2`. How would one derive the actual font name from this identifier, or at least the index in the Font dictionary being referred to? I've found [where the identifier seems to be generated](https://github.com/mozilla/pdf.js/blob/3b3a179486e9e9f5979d574ec6ec8c86e2d1a877/src/core/evaluator.js#L744), and the identifier looks to be generated based on a number of factors.

Final question: why is it that PDF.js doesn't (seem to) utilize the character widths or the actual fonts themselves defined in the PDF for text selection?

**Comment by matt-curtis** [comment]
Additional question: How is getTextContent().styles.fontName derived? It doesn't seem to correlate with the font name in the actual page dictionary.

**Comment by matt-curtis** [comment]
Answer to the 2nd question seems to be `page.commonObjs`. Took awhile to find that one!

**Comment by yurydelendik** [comment]
The getTextContent() results does not contain text (in `str` property) to be displayed via specified font. `fontName` is provided just for informational purpose, so an attempt to use `page.commonObjs` font in getTextContent-context might fail due to the getOperatorList and getTextContent logic (two different algorithms per specification). 

> I see g_d0_f1 and g_d0_f2. How would one derive the actual font name from this identifier, or at least the index in the Font dictionary being referred to?

Font ID is used to match fonts during getOperatorList processing.

> why is it that PDF.js doesn't (seem to) utilize the character widths or the actual fonts themselves defined in the PDF for text selection?

There are several width attributes defined for fonts: one in the PDF dictionary and one in the font. PDF.js defines map based on these two. Produced "embedable" font contains only data from the font data (and not from PDF, if defined), that's why we cannot rely just on font information. Also in most of the cases glyph are precisely positioned, so glyph widths are useless for fillText/strokeText canvas operators or DOM layout.

Closing as answered.

**Comment by matt-curtis** [comment]
> Produced "embedable" font contains only data from the font data (and not from PDF, if defined), that's why we cannot rely just on font information.

So, in order to get accurate glyph positioning and size, you would need to use the actually 'font program' (as it is referred to in the spec)? If the font metadata as given in the PDF is not sufficient to accurately achieve text selection, why isn't the font program extracted and added to the page? I'm probably not understanding something, but it seems like it would provide more accurate selection than the current implementation.

> Also in most of the cases glyph are precisely positioned, so glyph widths are useless for fillText/strokeText canvas operators or DOM layout.

How much do fillText/strokeText affect glyph width? It seems like you could still achieve more accurate glyph widths than the current selection implementation provides, though fill/stroke would be needed for drawing.

**Comment by yurydelendik** [comment]
I don't understand how the questions above related to the OP.

> How much do fillText/strokeText affect glyph width?

See "TJ" operator (www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=259) -- in most of the cases it is used and in most of the cases it is used as described in `[ (A) 120 (W) 120 (A) 95 (Y again) ] TJ` example -- fillText produces non-acceptable output in this case.

> I'm probably not understanding something, but it seems like it would provide more accurate selection than the current implementation.

We made trade-off for performance and better browser search/selection integration by accepting somewhat not-quite-precise text layer. You are welcome to provide complete solution to improve the viewer text selected, however the github issue is not good tools for discussion (see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md)
