### ISSUE TITLE
Use embed if available

### ISSUE THREAD

**Issue by xakzona** [mozilla/pdf.js#7917]
Hello guys,
I want to use pdfJS only if embed tag can't be used (not supported by the browser), else using native embed tag.
Can I implement it?

**Comment by matt-curtis** [comment]
PDFObject does this: https://pdfobject.com/

**Comment by timvandermeij** [comment]
Indeed you'll need to do a feature detection like PDFObject does and load PDF.js only if the feature is not supported. It can be done that way, but since that's out of scope for the PDF.js project itself, I'm closing this as answered.
