### ISSUE TITLE
Edge Referer 

### ISSUE THREAD

**Issue by itlizhi** [mozilla/pdf.js#7918]
- Web browser and its version: **Edge**
- Operating system and its version: win10
- PDF.js version: 1.6.416
- Is an extension: false

**Use referer to check the source**

in chrome  and firefox is ok
![image](https://cloud.githubusercontent.com/assets/10509513/21518777/9606c696-cd23-11e6-9f01-01a678a569eb.png)

but edge don't request referer header
![image](https://cloud.githubusercontent.com/assets/10509513/21518789/b3c70da8-cd23-11e6-8606-b0993671cf83.png)

**Comment by timvandermeij** [comment]
PDF.js does not appear to do anything specific for referer headers (see https://github.com/mozilla/pdf.js/search?q=referer&type=Code&utf8=%E2%9C%93), so this looks more like a bug in Edge. Closing as invalid for now.
