### ISSUE TITLE
Radial shading not clipped

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#7921]
Link to PDF file (or attach file here):
https://issues.apache.org/jira/secure/attachment/12844801/PDFBOX-3640.pdf

Configuration:
- Web browser and its version: FF 50.1.0
- Operating system and its version: W7
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: ?

Steps to reproduce the problem:
1. open the file

What is the expected behavior? (add screenshot)
![clipboard01](https://cloud.githubusercontent.com/assets/6665575/21521441/46f8a5c2-ccfd-11e6-828d-57809ed2f660.png)

What went wrong? (add screenshot)
![clipboard02](https://cloud.githubusercontent.com/assets/6665575/21521445/4b7f1522-ccfd-11e6-8adc-e061c6be8cd1.png)

**Comment by Snuffleupagus** [comment]
In my testing, it seems that this issue may be either intermittent, and/or dependent on the zoom level.

**Comment by THausherr** [comment]
I tried changing the zoom level and yes indeed, it happens sometimes and sometimes not.

**Comment by brendandahl** [comment]
I'm not able to reproduce the issue. The recent pattern changes may have fixed it. @THausherr or @Snuffleupagus can you still reproduce with master?

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version 2.9.142 in Firefox Nightly 90.

**Comment by THausherr** [comment]
Works for me on W10 at different zoom levels with FF 88.0.1, both with 
https://mozilla.github.io/pdf.js/web/viewer.html
and with the built-in viewer. However the later one is much faster.
