### ISSUE TITLE
Unknown property ‘appearance’

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#7923]
While landing [Bug 1326340](https://bugzilla.mozilla.org/show_bug.cgi?id=1326340), we had:

```
TEST-UNEXPECTED-FAIL | browser/base/content/test/general/browser_parsable_css.js | Got error message for jar:file:///builds/slave/test/build/application/firefox/browser/omni.ja!/chrome/pdfjs/content/web/viewer.css: Unknown property ‘appearance’. Declaration dropped. 
```

See https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&fromchange=67286eb47060e44a7d3d311e44618691a679bab5&selectedJob=65424931

(My best guess is due #7898)

Problems to solve here:
- why browser_parsable_css.js fails us
- how to fix
- can we use browser_parsable_css.js?

**Comment by yurydelendik** [comment]
I think just removing the following for the annotation_text_layer.css shall help:

```diff
+  -ms-appearance: none;
+  appearance: none;
```

**Comment by timvandermeij** [comment]
I'm concerned that that will break rendering of the wigets in other browsers. They are all required to make the rendering look good.

**Comment by timvandermeij** [comment]
I think an exception should be added at https://github.com/mozilla/gecko-dev/blob/master/browser/base/content/test/general/browser_parsable_css.js#L20.

**Comment by rvandermeulen** [comment]
I can try adding it to the whitelist, thanks.

**Comment by yurydelendik** [comment]
> You mean in https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.css?

Yes, thanks

**Comment by rvandermeulen** [comment]
Here's a Try push for the whitelisting patch. If it's green, I'll attach it to bug 1326340 and get review from a browser peer before folding it into the main patch and re-landing the pdf.js update.
https://treeherder.mozilla.org/#/jobs?repo=try&revision=79d9f0c81c98117cbd93acdea1a7910db3d2a447&group_state=expanded

**Comment by rvandermeulen** [comment]
Try push was good and the change got r+. I've relanded the pdf.js update with that fix incorporated, so I think we can close this out now.

**Comment by yurydelendik** [comment]
> Try push was good and the change got r+... so I think we can close this out now.

Thank you, closing.
