### ISSUE TITLE
who can tell me the role that folders named cmaps and locale play in the progress,what will happened if I delete these,beacause the project is so big that can not be used in mobile  items

### ISSUE THREAD

**Issue by RainingBlack** [mozilla/pdf.js#7927]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by mukulmishra18** [comment]
I think [this](https://mozilla.github.io/pdf.js/getting_started/) might help.

The cmaps/ folder contains certain files with extension .bcmap, you can find similar question asked on [stackoverflow](http://stackoverflow.com/questions/32764773/what-is-a-pdf-bcmap-file) and why it is required.

The local/ folder contains translation files, i think it is for localization of viewer(i.e converting the viewer to local language).

**Comment by yurydelendik** [comment]
@mukulmishra18 thanks. Closing as answered.

**Comment by RainingBlack** [comment]
@mukulmishra18 @yurydelendik  thanks for your answer,but I want to know what will happen if I delete the local/ folder or when I can delete these folders?Thanks again!
