### ISSUE TITLE
Migrate code to es6 or to Typescript

### ISSUE THREAD

**Issue by luisvt** [mozilla/pdf.js#7931]
Code will have better readability if it is migrated to es6 or to Typescript.

**Comment by yurydelendik** [comment]
Closing as duplicate of https://github.com/mozilla/pdf.js/projects/3

**Comment by luisvt** [comment]
what would you prefer to use: es6 or Typescript?

**Comment by yurydelendik** [comment]
> what would you prefer to use: es6 or Typescript?

This is an opinion based question and shall not be part of this issue (see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md about non-technical problems). ES6 was chosen as evolutionary step of the same programming language and moving entire project to be modular.

**Comment by luisvt** [comment]
ok, I'll begin doing migrations to es6 then
