### ISSUE TITLE
Safari iPad iOS 10.2 - PDF not loading

### ISSUE THREAD

**Issue by egodsk** [mozilla/pdf.js#7936]
Configuration:
- Web browser and its version: Safari - iOS 10.2
- Operating system and its version: iOS 10.2
- PDF.js version: 1.5.188

When i load up PDF.js on Safari iPad iOS 10.2, no pdf is displayed. The PDF.js framework displays, but a pdf never loads. I can fix this by going in and setting: disableRange: to true in viewer.js. I have tried including the compatibility.js file, but it still does only work is disableRange is set to true.

Works perfectly well in Chrome on Windows with the disableRange set to false.

**Comment by Snuffleupagus** [comment]
I believe that this should have been fixed by PR #7841, which (among other things) disables range requests on iOS devices.

> PDF.js version: 1.5.188

If you use the *latest* version of `compatibility.js`, as found at https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js, does that resolve the issue?

**Comment by Snuffleupagus** [comment]
Closing as answered, since the advice in https://github.com/mozilla/pdf.js/issues/7936#issuecomment-271258344 should be enough to fix this issue.

**Comment by pedropcruz** [comment]
@Snuffleupagus i cant understand how you include compatibility, when you get worker and document. I can show the code here:

first, i'm using require:

```javascript
 var pdfjsLib = require('pdfjs-dist/build/pdf');

``` 

```javascript

 pdfjsLib.PDFJS.workerSrc = require('pdfjs-dist/build/pdf.worker');

        pdfjsLib.PDFJS.getDocument(this._pdfPath).then(function(pdfDoc_){
            pdfDoc = pdfDoc_;
            renderPage(pageNum, 1);
        });

```

**Comment by rashnk** [comment]
Crashed chrome on iPad while rendering pdf with 70 pages, 
[https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js](@Snuffleupagus  this link does not exist, https://github.com/mozilla/pdf.js/blob/master/web/compatibility.js)

**Comment by marcoiai** [comment]
Can't seem to make it work on ios too! compatibility.js is gone from the repo!
