### ISSUE TITLE
pdf.js showing wrong portion of images

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#7946]
Link to PDF file (or attach file here): https://cloud.box.com/s/3idigur8fepcqxto007ykhjca3w0x68i (after following step 1 below)

Configuration:
- Web browser and its version: Chrome 55
- Operating system and its version: Mac OSX El Capitan
- PDF.js version: 1.6.334
- Is an extension: No

Steps to reproduce the problem:
1. Turn on pdf.js viewer by visiting https://cloud.box.com/on/beta
2. Visit https://cloud.box.com/s/3idigur8fepcqxto007ykhjca3w0x68i - the page should look like https://www.screencast.com/t/lYCWRzAsix
3. Go to page 6
4. Note image in bottom right is cropped/positioned at the wrong place compared to when file is downloaded and viewed through Chrome or Adobe Reader, which show the landscape and not just the bottom portion of the chair

What is the expected behavior? (add screenshot)
page 6 - http://www.screencast.com/t/kfdy2ftjIF
page 15 - http://www.screencast.com/t/nk6k6fLz4XI

What went wrong? (add screenshot)
page 6 - http://www.screencast.com/t/N9Pd9Hgha
page 15 - http://www.screencast.com/t/JndDKRYO8

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://cloud.box.com/s/3idigur8fepcqxto007ykhjca3w0x68i (after following step 1 above)

**Comment by timvandermeij** [comment]
I don't even see the top images on pages 6, 9 and 15 and both images on page 12 on Arch Linux, just blue squares. This may therefore also depend on the OS/browser version being used.

**Comment by tonyjin** [comment]
Oops, sorry forgot to add a step. If you don't do this step, you see the old viewer, which isn't on pdf.js.

1. Visit https://cloud.box.com/on/beta before any other URL

**Comment by timvandermeij** [comment]
You're right, that resolves the mentioned issues for me. I do see only the cropping/positioning issue now.

**Comment by tonyjin** [comment]
Another example: https://privportfolio.app.box.com/s/lrtjiu6bpma0pvz2xmhnrmremcpi2i2k

Expected page 5 behavior (Chrome): https://www.screencast.com/t/XbU3f9St
Incorrect page 5 behavior (pdf.js): https://www.screencast.com/t/s6yy6TnZsy

**Comment by Rob--W** [comment]
Attached original PDF for posterity: [3203.pdf](https://github.com/mozilla/pdf.js/files/3014568/3203.pdf)

This bug appears to be fixed by #6606.
