### ISSUE TITLE
Shrinked pdf page when we try to print it is becoming blur and not redable

### ISSUE THREAD

**Issue by madhav1985** [mozilla/pdf.js#7955]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: All web browser
- Operating system and its version: Windows 10
- PDF.js version:pdfjs-1.5.188-dist
- Is an extension:

Steps to reproduce the problem:
1. We have the input .msg file for c++ and c++ converts it to pdf. But the converted pdf cuts the content in the right side of the page.
2. To overcome this issue we shrinked the page in c++ and we are getting the full content in the pdf but the content size is smaller that the orginal one.
While printing the pdf with shrinked content using pdf.js it is more blur than the orginal file and not readable.

What is the expected behavior? (add screenshot)
Need to increase the quality of printing for shrinked contents.
What went wrong? (add screenshot)
Print is becoming blur in all browsers after the content is shriked.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by madhav1985** [comment]
In chrome it is coming fully blur compared to mozilla firefox

**Comment by timvandermeij** [comment]
Closing as invalid. No PDF file has been provided to reproduce the issue. Moreover, fairly recently quite a lot of printing bugs were fixed and these changes are not yet in version 1.5.188.
