### ISSUE TITLE
Missing filled shapes after applying the mask

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [mozilla/pdf.js#7958]
Link to PDF file (or attach file here):
http://drifted.in/other/batik/horologium-batik-reduced.pdf

Configuration:
- Web browser and its version: Firefox beta 51.0b13
- Operating system and its version: Windows 10
- PDF.js version: n/a
- Is an extension: no

What is the expected behavior?
Ring with filled shapes, see the result in Acrobat or Chrome

What went wrong?
Nothing is displayed

The original SVG file is converted into PDF using Batik transcoder. If there is non-standard code, let me know, I'll pass this to Batik developers to fix this also on their side.

**Comment by timvandermeij** [comment]
This PDF file renders exactly the same as Okular does for me using the latest version of PDF.js. Please try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if the issue is still there.

**Comment by jan-tosovsky-cz** [comment]
In that viewer opened in Firefox I can see the same problem. However, when that viewer is opened in Chrome, I see the correct result. It is really weird. In Edge it takes ages (progress circle for more than 5 minutes), so I had to stop it. In all browser there is same version stamp in the console (PDF.js: 1.6.458),

**Comment by jan-tosovsky-cz** [comment]
In Edge I overlooked the error in the console 'IndexSizeError' - pdf.js (7457,8). Should I file a new bug?

**Comment by jan-tosovsky-cz** [comment]
There should be rather 'firefox-specific' label. It works in Chrome, but not in FF.

**Comment by mattmcardle** [comment]
Is there any update on this? I have similar issue with users reporting "IndexSizeError" appearing in IE11.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.13.133` in Firefox Nightly 99 (on Windows).

Can anyone still reproduce this, since the issue is quite old? (If so, it's most likely a browser/graphics-driver bug rather than a PDF.js one.)

**Comment by jan-tosovsky-cz** [comment]
I can confirm it works fine now in FF (on pdf.js 2.13.24)
