### ISSUE TITLE
How to disable navigation keyboard shortcuts

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7961]
Is there such an option?

**Comment by timvandermeij** [comment]
No, you would have to remove the key bindings for the viewer yourself.

**Comment by allefeld** [comment]
> No, you would have to remove the key bindings for the viewer yourself.

I'm trying to do that for ^P (print) ^O (open).

As far as I can tell, ^P is implemented in line 15627 ff. of `web/viewer.js':
```
window.addEventListener('keydown', function (event) {
  if (event.keyCode === 80 && (event.ctrlKey || event.metaKey) &&   // 'p'
      !event.altKey && (!event.shiftKey || window.chrome || window.opera)) {
    window.print();
```
Commenting out `window.print()` had no effect.

For ^O I can't even find the corresponding code.

**Comment by fishfree** [comment]
@chitgoks I also disable keyboard shortcuts, even all. Please re-open this issue.

**Comment by chitgoks** [comment]
reopening on @fishfree  's request. i have no use for this anymore

**Comment by fishfree** [comment]
@allefeld I find we should also comment out 
` window.addEventListener("click", webViewerClick);
    //window.addEventListener("keydown", webViewerKeyDown);
    window.addEventListener("keyup", webViewerKeyUp);
`

**Comment by allefeld** [comment]
@fishfree, in my application I ended up with a solution that does not involve changing the code of the viewer.

I use the viewer for a pdf-display pane in atom: <https://github.com/allefeld/atom-pdfjs-viewer>.
The viewer is in an `iframe`, and I have code outside which controls which keypresses make it to the viewer in the first place.

See: https://github.com/allefeld/atom-pdfjs-viewer/blob/453706f884835031a43a829304914b9c1eafb1be/lib/pdfjs-viewer-view.js#L101
