### ISSUE TITLE
Bug 1331081 - omit addEventListener/removeEventListener's third parameter when it's false

### ISSUE THREAD

**Issue by fqueze** [mozilla/pdf.js#7962]
Just a friendly heads up that a mass-change I pushed to mozilla-inbound contains the 2 following changes touching pdf.js files:

https://hg.mozilla.org/integration/mozilla-inbound/diff/7b434711753b/browser/extensions/pdfjs/content/web/debugger.js

https://hg.mozilla.org/integration/mozilla-inbound/diff/7b434711753b/browser/extensions/pdfjs/content/web/viewer.js

**Comment by timvandermeij** [comment]
Thank you for reporting this. The changes have now been merged here as well.
