### ISSUE TITLE
Open pdf with password

### ISSUE THREAD

**Issue by medbio951094** [mozilla/pdf.js#7967]
How to open pdf with password in pdf.js?

**Comment by medbio951094** [comment]
How to open pdf with password in pdf.js?

**Comment by Snuffleupagus** [comment]
One option is to provide the `password` parameter when calling `PDFJS.getDocument`, please see https://github.com/mozilla/pdf.js/blob/a917443ae6733e77ec0011097ddfb23fa0e740fc/src/display/api.js#L120.

Another option is to attach a `onPassword` callback to the `PDFDocumentLoadingTask`, which is returned by `PDFJS.getDocument`, please see https://github.com/mozilla/pdf.js/blob/a917443ae6733e77ec0011097ddfb23fa0e740fc/src/display/api.js#L342-L346.

For an example of how the above methods work in practice, refer to e.g. the relevant unit-tests: https://github.com/mozilla/pdf.js/blob/a917443ae6733e77ec0011097ddfb23fa0e740fc/test/unit/api_spec.js#L174-L261.

Closing as answered.
