### ISSUE TITLE
Set Noopener (maybe even nofollow) by default on external links

### ISSUE THREAD

**Issue by devd** [mozilla/pdf.js#7986]
In https://github.com/mozilla/pdf.js/blob/master/src/display/global.js#L230-L236

pdf.js currently sets the referrer policy for external links to noreferrer. For further safety, can we set rel attribute to noopener, noreferrer, nofollow? See https://mathiasbynens.github.io/rel-noopener/

**Comment by yurydelendik** [comment]
> can we set rel attribute to noopener, noreferrer, nofollow

@devd did you mean to the "noopener noreferrer nofollow" value?

@tonyjin can you check if this will be a breaking API change for you guys? (based on #6767)

**Comment by devd** [comment]
yes. Sorry .. the english rules overrode the HTML rules for a moment :)
