### ISSUE TITLE
Image not shown in some pages on MANGA contents

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#7992]
Link to PDF file (or attach file here):
[AN_1000126_p100.pdf](https://github.com/mozilla/pdf.js/files/728428/AN_1000126_p100.pdf)

Configuration:
- Web browser and its version: doesn't seem browser specific
- Operating system and its version: any
- PDF.js version: current
- Is an extension:

Steps to reproduce the problem:
1.  Open the attached PDF
2.

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/7111820/22274836/19c1d04c-e2ec-11e6-95d3-ccef39219a4b.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/7111820/22274840/26da2af4-e2ec-11e6-8384-c08c7c9d88f9.png)
Even it's MANGA contents, images aren't shown.
(Most pages are OK, but it happens with this page only.)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
After PR #14175, the images are now *very faintly* visible.
