### ISSUE TITLE
printing with correct fonts  and fast

### ISSUE THREAD

**Issue by otorite** [mozilla/pdf.js#7994]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:           45.6
- Operating system and its version:    Debian 8.6
- PDF.js version:                                   1.1.209
- Is an extension:                                  yes

Steps to reproduce the problem:
1. original pdf have multiple pages landscape and portrait 
[Bimer.pdf](https://github.com/mozilla/pdf.js/files/729080/Bimer.pdf)
2. when printed with pdf.js, original font was changed 
![scanned-1](https://cloud.githubusercontent.com/assets/25297789/22284597/0eec0f04-e2f9-11e6-9da0-7734acc9e30a.jpg)

What is the expected behavior? (add screenshot)
fonts must be kept like the original pdf 
What went wrong? (add screenshot)
font was changed and printing is too slow

Regards,

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You're using a really old version of PDF.js. This has been fixed recently, so try either the latest release or the current master.
