### ISSUE TITLE
Calculating the position of individual glyphs in `getTextContent`

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#7996]
In PR #4570, code was added for calculating the position of individual glyphs in `getTextContent`.
However, as can be seen from both the PR and also the current version of [src/core/evaluator.js](https://github.com/mozilla/pdf.js/blob/e0a92a7f4853adb4145145920f2c85078d1695ff/src/core/evaluator.js#L1326-L1336), that code has always been commented out and was thus never actually used.

In PR #7972 this code is being removed since it's completely unused, however this issue exists so as to maintain a record of the code.

---
The individual glyph positions are calculated as outlined in commit https://github.com/mozilla/pdf.js/commit/3a1cffa7984e2731f4bc9e5c1b930531c8eecb4f#diff-0b94c2e77a5259f7a728122fdbf9f46aR785,  see also the excerpt below.
```JavaScript
// The following will calculate the x and y of the individual glyphs.
if (font.vertical) {
  tsm[4] -= vMetricX * Math.abs(textState.fontSize) *
            textState.fontMatrix[0];
  tsm[5] -= vMetricY * textState.fontSize *
            textState.fontMatrix[0];
}
var trm = Util.transform(textState.textMatrix, tsm);
var pt = Util.applyTransform([trm[4], trm[5]], textState.ctm);
var x = pt[0];
var y = pt[1];
```
Where the `vMetricX`/`vMetricY` variables are calculated in a loop above, please refer to commit https://github.com/mozilla/pdf.js/commit/3a1cffa7984e2731f4bc9e5c1b930531c8eecb4f#diff-0b94c2e77a5259f7a728122fdbf9f46aR765 or the excerpt below.
```JavaScript
var glyphs = font.charsToGlyphs(chars);
var defaultVMetrics = font.defaultVMetrics;
for (var i = 0; i < glyphs.length; i++) {
  var glyph = glyphs[i];
  if (!glyph) { // Previous glyph was a space.
    continue;
  }
  var vMetricX = null;
  var vMetricY = null;
  var glyphWidth = null;
  if (font.vertical) {
    if (glyph.vmetric) {
      glyphWidth = glyph.vmetric[0];
      vMetricX = glyph.vmetric[1];
      vMetricY = glyph.vmetric[2];
    } else {
      glyphWidth = glyph.width;
      vMetricX = glyph.width * 0.5;
      vMetricY = defaultVMetrics[2];
    }
  } else {
    glyphWidth = glyph.width;
  }
```

**Comment by cheapsteak** [comment]
Could I confirm if `vMetricX` should be null if `font.vertical` is false? I guess `null * x` will be `0`
