### ISSUE TITLE
Can my custom annotation layer be passed to pdf.js' annotationlayer for printing?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7997]
hi, i looked at AnnotationLayerBuilder and i wonder if it is possible since i have my own canvas layer to draw annotations, be passed to pdf.js AnnotationLayerBuilder so it can be included in print preview?

i tried to pass it off to the printContainer canvas.drawImage(annotationCanvas ... ) but it looks like there is some transformation that occurs for every pdf.js page because my annotations in the canvas are out of place and too big so i wonder if the canvas layer can be passed to the AnnotationLayerBuilder would save me the trouble?

also it ends up being blurred.

if so, how? please advise
![print_preview](https://cloud.githubusercontent.com/assets/3955470/22320469/9a2c3f02-e3c7-11e6-862a-799299d69f63.jpg)

**Comment by chitgoks** [comment]
hi. i managed to make it work. however, i made it work inside viewer.js

im looking at making it work outside pdf.js and the key here is the context rendered by the page in beforePrint. is there any way to get the context object?

**Comment by hobbydevs** [comment]
How did you solve it ?
