### ISSUE TITLE
Bug 1331599 - Avoid removeEventListener calls when {once: true} can be used instead

### ISSUE THREAD

**Issue by fqueze** [mozilla/pdf.js#7999]
This file was changed on mozilla-central:
https://hg.mozilla.org/integration/mozilla-inbound/diff/ec0f3678bb31/browser/extensions/pdfjs/test/browser_pdfjs_navigation.js

**Comment by Snuffleupagus** [comment]
Please note that tests residing in http://searchfox.org/mozilla-central/source/browser/extensions/pdfjs/test are actually *not* present here in the GitHub repo, so in this case we don't need to make any changes here.

Closing, since there's nothing to do here.
