### ISSUE TITLE
Out of memory issue while printing

### ISSUE THREAD

**Issue by tudoragaf** [mozilla/pdf.js#8007]
The issue is reproducible while printing big documents. Memory usage goes up gradually and if the machine has not enough RAM, the browser crashes.

Link to PDF file: http://prawnpdf.org/manual.pdf

Test 1  
Configuration:
- Web browser and its version: Google Chrome v55.0.2883.87 
- Operating system and its version: Windows 7 Professional
- PDF.js version: 1.7.231

![chrome-pdf_n](https://cloud.githubusercontent.com/assets/16950929/22417590/4f468aa4-e6d5-11e6-9748-7d7bbec9de9f.PNG)

Test 2
Configuration:
- Web browser and its version: Internet Explorer v11.0.9600.18537
- Operating system and its version: Windows 7 Professional
- PDF.js version: 1.7.231

![ie-pdf_n](https://cloud.githubusercontent.com/assets/16950929/22417605/65bcb7e0-e6d5-11e6-87fb-7c5f1dfb44a6.PNG)

Test 3
Configuration:
- Web browser and its version: Mozilla Firefox v50.1.0
- Operating system and its version: Windows 7 Professional
- PDF.js version: 1.7.231

![firefox-pdf_n](https://cloud.githubusercontent.com/assets/16950929/22417614/71b530a4-e6d5-11e6-8502-645e0c1ce26b.PNG)

**Comment by Rob--W** [comment]
This is unfortunately a consequence of the fact that all browsers (except for Firefox) require the document to print to be fully rendered before the result is sent off to a printer. In Firefox, PDF.js prints one page at a time, whereas in other browsers all pages are rendered at once and then printed.

To avoid this, we can either delegate the print rendering to the browser and let it handle the print (e.g. as done in #6190), or try to get the browsers to support asynchronous printing. The latter is a long shot (e.g. Chromium is not interested in implementing something like this - https://crbug.com/131279), while the former depends on a non-JavaScript component that is not always bundled with Chromium (and naturally unavailable to non-Chromium browsers).

**Comment by FireFoxRookie** [comment]
In IE 11, less than 20 files are printed and the memory occupied has reached 1 g. ie crashes directly. Is there a solution to this problem? @timvandermeij

**Comment by Rob--W** [comment]
@FireFoxRookie Can you share the PDF file where this happens? In any case it is unlikely for the problem to be solved, except possibly work-arounds such as reducing the quality of the printed results.

**Comment by Snuffleupagus** [comment]
> In IE 11, less than 20 files are printed and the memory occupied has reached 1 g. ie crashes directly. Is there a solution to this problem?

Note also that as clearly outlined in the Wiki, IE 11 is *virtually unsupported* at this point in time; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.

**Comment by Snuffleupagus** [comment]
Given that IE 11 is now *explicitly* unsupported, and that memory usage is "reasonable" in other browser (given that it's a 100+ page document), is it actually meaningful to keep this issue open?
