### ISSUE TITLE
Unreferenced files

### ISSUE THREAD

**Issue by fqueze** [mozilla/pdf.js#8014]
The tests I wrote in https://bugzilla.mozilla.org/show_bug.cgi?id=1316187 flag the following pdf.js files as shipped in Firefox builds but not referenced by any code:

resource://pdf.js/web/debugger.js
resource://pdf.js/web/images/annotation-check.svg
resource://pdf.js/web/images/annotation-comment.svg
resource://pdf.js/web/images/annotation-help.svg
resource://pdf.js/web/images/annotation-insert.svg
resource://pdf.js/web/images/annotation-key.svg
resource://pdf.js/web/images/annotation-newparagraph.svg
resource://pdf.js/web/images/annotation-noicon.svg
resource://pdf.js/web/images/annotation-note.svg
resource://pdf.js/web/images/annotation-paragraph.svg

Could someone please check if these files were false positives, or are actually unreferenced and if so should be removed?

**Comment by yurydelendik** [comment]
> The tests I wrote in https://bugzilla.mozilla.org/show_bug.cgi?id=1316187 flag the following pdf.js > files as shipped in Firefox builds but not referenced by any code:

> resource://pdf.js/web/debugger.js

Referenced from https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1375

> resource://pdf.js/web/images/annotation-check.svg
> resource://pdf.js/web/images/annotation-comment.svg
...

Referenced from https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L390

All of those referenced at runtime (but not at m-c tests). Closing as answered.
