### ISSUE TITLE
Bot warnings not showing in logs

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#8015]
Just noticed over in #8012 that the MD5 warnings are not showing up, but I see them in the console on the bot.

```
WARNING: MD5 of file "pdfs/issue215.pdf" does not match file. Expected "31f3dc60ecf008987d970edfd2b1df61" computed "7fe95dcea2820e9bfaf71e125e704265"
```

**Comment by timvandermeij** [comment]
It looks like a problem on the new bot, because the current bot used to report this. Furthermore, `md5sum issue215.pdf` gives me the expected value locally, so I think the file on the bot is incorrect. Are you sure that this happens on the current bot as well?

**Comment by brendandahl** [comment]
This should be resolved. We were running an botio with a new version of shelljs that has been changed. I reverted the version.
