### ISSUE TITLE
Windows bot does not provide correct preview links

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8017]
The links provided by the new Windows bot when creating a preview do not actually link to the generated preview, but result in a 404. Example: https://github.com/mozilla/pdf.js/pull/8012#issuecomment-276801814

**Comment by brendandahl** [comment]
Looks like zip is missing on the bot. I'll try to figure it out tomorrow and why the error didn't show up in the log.

**Comment by brendandahl** [comment]
Should be fixed now.
