### ISSUE TITLE
Remove `parseJbig2` function in `src/core/jbig2.js`

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8018]
It looks like this function (https://github.com/mozilla/pdf.js/blob/master/src/core/jbig2.js#L924) is unused, and has been since its introduction in https://github.com/mozilla/pdf.js/commit/95bc99f6980051618a093dff54288253143a23cc, so I think we can safely remove this dead code.

Thoughts about this, @Snuffleupagus?

**Comment by Snuffleupagus** [comment]
As far as I'm concerned we can remove that code. However, if we decide to do so, then I think that we ought to open a tracking issue (similar to #7996) to maintain a record of the code.

@yurydelendik Since you added the code in question, are you OK with removing it?

**Comment by shikhar-scs** [comment]
If this issue is still up can I take it please ?

**Comment by shikhar-scs** [comment]
@Snuffleupagus @yurydelendik @timvandermeij ?

**Comment by timvandermeij** [comment]
Yes, feel free to work on this.

**Comment by shikhar-scs** [comment]
Thankyou @timvandermeij. I've filed a PR related to the same :+1: please review it

**Comment by timvandermeij** [comment]
Fixed in #9386.
