### ISSUE TITLE
Add-on is unverified

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8034]
Even after the `amo.json` fix, the add-on is still unverified. Presumably the error logs will help to determine the cause of this.

**Comment by brendandahl** [comment]
Our bot was missing a dependency on jsonwebtoken. Should be fixed, I'll leave open until we verify.

**Comment by timvandermeij** [comment]
Closing as fixed. The add-on is signed again. Thank you for fixing this!
