### ISSUE TITLE
PDFjs not laying out fields in right loctaion

### ISSUE THREAD

**Issue by rmhrisk** [mozilla/pdf.js#8048]
Link to PDF file (or attach file here):
[AcroForm.pdf](https://github.com/mozilla/pdf.js/files/762493/AcroForm.pdf)

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: OSX
- PDF.js version: Latest
- Is an extension: No

Steps to reproduce the problem:
1. Open this PDF
2. Notice AcroFields in wrong location

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/1619279/22767186/9bd252e4-ee2e-11e6-9052-4bad89632837.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/1619279/22767173/8f6b25d0-ee2e-11e6-9b3a-00326d7b0412.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by THausherr** [comment]
Works fine on FF 51.0.1.

**Comment by timvandermeij** [comment]
This works for as well using the latest Firefox and PDF.js versions (https://mozilla.github.io/pdf.js/web/viewer.html) and there have been annotation layer fixes lately, so I'm closing this as fixed.
