### ISSUE TITLE
IE11 print margins in iFrame

### ISSUE THREAD

**Issue by uvolpato** [mozilla/pdf.js#8052]
Outside to iFrame, and with outher browsers it's all ok!
Into IE11 iframe not.

`<iframe src="http://mozilla.github.io/pdf.js/web/viewer.html"></iframe>`

Configuration:
- Web browser and its version: IE11
- Operating system and its version: WIN 10
- PDF.js version: 1.7.225
- Is an extension: -

Steps to reproduce the problem:
1. Open the official demo page in a iframe with IE11
2. Print

Print outside iframe:
![image](https://cloud.githubusercontent.com/assets/4378596/22818491/c3013cb4-ef6d-11e6-86af-9e4f0a56d3f9.png)

Print into iframe:
![image](https://cloud.githubusercontent.com/assets/4378596/22818516/e9a49014-ef6d-11e6-99a6-3890701b0852.png)

Wrong:
![image](https://cloud.githubusercontent.com/assets/4378596/22818804/679e00da-ef6f-11e6-9eed-315b238bd1ea.png)

Could you help me? thanks!

**Comment by kimgronqvist** [comment]
While I'm not entirely sure why, IE11 (and older version of IE) has issues with using `window.print` in an iframe. Using `window.document.execCommand('print', false, null);` seems to get the desired results, but is not supported in Firefox.

If you are building pdf.js from source, you can change `print.call(window)` in `pdf_print_service.js` to this:
```js
if (document.queryCommandSupported('print')) {
  window.document.execCommand('print', false, null);
} else {
  print.call(window);
}
```

For a more complete solution, you might also want to check if you are in an iframe.

**Comment by uvolpato** [comment]
Great! Print space is ok now, but I have one more issue ... Print doesn't take the correct page orientation. Below an example of landscape page, but printed with portrait orientation ... (always with IE11 and iFrame) ... 

Thanks!!

![image](https://cloud.githubusercontent.com/assets/4378596/23660325/594fdfc4-0349-11e7-8a36-5653716e2f98.png)

**Comment by ngramprabhu** [comment]
solution by kimgronqvist worked for margin issue.  But it created a new issue for me.

I had a custom event listener for "afterprint" event like below.
```
someiframe.contentWindow.addEventListener("afterprint", function() {
    window.close();
});
```
This event doesn't trigger in IE after the margin fix. Fine in chrome.... Any ideas?

**Comment by wareor** [comment]
Same here.
The way of @kimgronqvist works, but now print all in the page, even the custom buttons.
Another way is changing IE Printing Page Setup from this:
![image](https://user-images.githubusercontent.com/27779514/34064021-e53d0cd8-e1aa-11e7-87b6-c78c91bcdf97.png)
To this:
![image](https://user-images.githubusercontent.com/27779514/34064034-016b6512-e1ab-11e7-985d-22f96d063b5a.png)
And printing is fine.
But is in the browser of the client.
Anyone finded a solution for this?

**Comment by jvalst** [comment]
Same issue here, can this be fixed inside the package?

**Comment by EthianWong** [comment]
Try setTimeout like:
```javascript
someiframe.contentWindow.addEventListener("afterprint", function() {
   setTimeout(function(){
       window.close();
   }, 1000) 
});
```
In Internet Explorer，the JavaScript thread will be blocked when the print dialog appears. So try to use setTimeout to make it execute when the thread resumes (close the print dialog)

**Comment by jennybean** [comment]
I am also experiencing this in IE, but @kimgronqvist's solution did not fix it. Is there an official solution to this issue?

**Comment by ilnur-slv** [comment]
I face with same problem. @kimgronqvist's solutions work from time to time.
Will this issue be fixed in official package?

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
