### ISSUE TITLE
Downloading File In Safari

### ISSUE THREAD

**Issue by frankangelone** [mozilla/pdf.js#8059]
Based on issue #7688, I am unable to download files in Safari using the "download" button.  My steps to reproduce are the same as the previously referenced issue.  I had noticed that others had noted that this issue was an issue with WebKit, but had previously been corrected.  Unfortunately, I'm still running into problems.  Any suggestions? I saw that @timvandermeij closed the last issue, so I wanted to open a new thread in case anyone has insight on this. @cloud1991 - were you able to get this functionality working on your end?  

Configuration:

Web browser and its version: Safari 10.0.3 (11602.4.8.0.1)
Operating system and its version: Mac OS X El Capitan 10.11.6 (15G1217)
PDF.js version: Latest
Is an extension: No

**Comment by timvandermeij** [comment]
This has been fixed upstream in WebKit, but that was two months ago. Safari 10 does not yet have this version and consequently does not support it. There is nothing we can do about this; you'll just have to wait until a new Safari version is released, unfortunately.
