### ISSUE TITLE
Error loop in worker crashes browsers

### ISSUE THREAD

**Issue by LeonMelis** [mozilla/pdf.js#8061]
Link to PDF file (or attach file here): https://storage-download.googleapis.com/pdfjs_bug/test.pdf

Configuration:
- Web browser and its version: Chrome 56.0.2924.87 (64 bit), Firefox 51.0.1 (64-bit)
- Operating system and its version: MacOS 'Sierra' 10.12.3
- PDF.js version: 1.7.278, github.io CDN version
- Is an extension: No

Steps to reproduce the problem:
1. See this fiddle: https://jsfiddle.net/5ky7jy0m/1/
2. Run the fiddle (might crash browser tab!)
3. Observe developer console output, and how CPU usage maxes out
4. Notice that the page.render.then exception handler is never called

What is the expected behaviour? (add screenshot)
I'd expect the renderTask (`page.render()`) promise to reject, so I can catch and display the error.

What went wrong? (add screenshot)
Catch() is never called, PDFJS worker enters an error loop, printing the same error over and over, causing the browser tab to consume 100% of available resources, it becomes impossible to close the tab in chrome. (use `Window > Task Manager` to kill tab)
The exception handler in `page.render.then` is never called.

````
Warning: Invalid cMap data: Error: Illegal character: 41
Error: Illegal character: 41
    pdf.worker.js:340     at error (http://mozilla.github.io/pdf.js/build/pdf.worker.js:340:15)
    at Lexer_getObj [as getObj] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:13075:5)
    at parseCMap (http://mozilla.github.io/pdf.js/build/pdf.worker.js:38700:22)
    at Object.create (http://mozilla.github.io/pdf.js/build/pdf.worker.js:38817:12)
    at PartialEvaluator_readToUnicode [as readToUnicode] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:27809:24)
    at PartialEvaluator_extractDataStructures [as extractDataStructures] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:27637:44)
    at PartialEvaluator.<anonymous> (http://mozilla.github.io/pdf.js/build/pdf.worker.js:28175:17)

[error repeats infinitely]
````

![screen shot 2017-02-11 at 15 20 15](https://cloud.githubusercontent.com/assets/2332995/22854559/857fe836-f071-11e6-9698-6cd38cc4fc0e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://jsfiddle.net/5ky7jy0m/1/

**Comment by timvandermeij** [comment]
Thank you for reporting this bug and thanks @Snuffleupagus for fixing this so quickly!

**Comment by LeonMelis** [comment]
I can confirm that the PDF now renders correctly, thanks @Snuffleupagus for the quick action!
