### ISSUE TITLE
How to load a PDF from  a folder in root (outside public_html) ?

### ISSUE THREAD

**Issue by drswing** [mozilla/pdf.js#8074]
My pdfs are in the foder "data" located outside the public_html folder.

To access the files in this folder form a php script the path is :  ../../data/file.pdf

When I try to use that path with pdf.js, it paste my domain name before the path and I get the error message : Message : Missing PDF "http://mydomain.com/data/file.pdf".

Where can I change that?

Thank you for your help

**Comment by yurydelendik** [comment]
Relative path is not preferred way, but it can work when demo viewer is used. Please specify path in absolute form -- it shall not be an issue to build full path using `document.location`. Closing as answered.

**Comment by yurydelendik** [comment]
There is no way to access a non-web exposed files from the browser, if you mean by 'outside public_html' by that.
