### ISSUE TITLE
File with many repeated patterns sortof freezes browser

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#8078]
Link to PDF file (or attach file here):
https://bugs.ghostscript.com/attachment.cgi?id=7455

Configuration:
- Web browser and its version:
FF 51.0.1 32bit

- Operating system and its version:
W7

- PDF.js version:
https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. click on link

What is the expected behavior?
that it be displayed

What went wrong?
Only a part is drawn and then firefox freezes / gets very slow, the "wait" animation is there. Sometimes it is possible to close the tab, but FF is still slow, so I close and restart it.

Thoughts about this file (which is a real world file, but kindof extreme):
https://bugs.ghostscript.com/show_bug.cgi?id=692158
https://issues.apache.org/jira/browse/PDFBOX-3688

I also tried with MSIE. It first popped up a scary dialog box about a "32/64bit thumbnail bridge" which I denied. Then the effect was the same than with FF.

**Comment by Snuffleupagus** [comment]
This particular PDF document is quite slow to render *even* in Adobe Reader, hence I'm think that we can call this issue fixed after the following patches:
 - PR #12016, which improved overall performance quite a bit.
 - PR #13361, which made the light-blue pattern visible.
