### ISSUE TITLE
Basic object initialization isn't working in Webpack with v1.7.308

### ISSUE THREAD

**Issue by dschissler** [mozilla/pdf.js#8084]
Link to PDF file (or attach file here):

**Configuration:**
- Firefox 51:
- Ubuntu 16.04 VM, Webpack 2.2.1:
- `pdfjs-dist` NPM package version `1.7.308`

**Steps to reproduce the problem:**
1. Create a Webpack 2 entry with only:
```
import pdflib from 'pdfjs-dist'
import 'pdfjs-dist/web/pdf_viewer'
```
2. Build with Webpack
3. In the browser load the page or simple Webpack magic file and see `pdfjsLib is undefined`.

**Expected Behavior:**

`pdflib` or `window.PDFJS` should have all of the extra properties added from `pdf_viewer`.

This works correctly with version `1.6.486`

**Opinion**

It seems like an error but if something fundamental was changed in v1.7 then the documentation should be updated.

**Comment by yurydelendik** [comment]
There was no changes in API. Can you provide a complete example? I checked API at "examples/components" and it works okay. Also http://jsbin.com/sukuga/edit?html,js,output

**Comment by brendandahl** [comment]
@dschissler Does the above pull request fix it for you?

**Comment by dschissler** [comment]
No it didn't.  I will be able to look at this again in about a week.

**Comment by dschissler** [comment]
Sorry I was in an airport and didn't read it correctly.  I will try it later to give comment.

**Comment by sjoyal** [comment]
I'm having the same issue today when using `1.7.331`:
```
        require.ensure(['pdfjs-dist/web/pdf_viewer', 'pdfjs-dist/web/compatibility'], require => {
            require('pdfjs-dist/web/pdf_viewer');
            require('pdfjs-dist/web/compatibility');

            window.PDFJS.workerSrc = 'root/vendor/pdf.worker.module.js';

            this.pdfViewer = new PDFJS.PDFViewer({
                container: this._documentContainer,
            });
            // doing some more stuff here
        }, 'pdfviewer');
```
The above worked in `1.6.414`.

However now I receive a `TypeError: Cannot read property 'PDFJS' of undefined` when attempting to require the chunks, and the main pdfjsLib object is undefined in pdf_viewer.

If i update to just `require('pdfjs-dist')`, I do not receive an error when requiring, but the PDFViewer constructor is not available on the PDFJS object?

**Comment by yurydelendik** [comment]
@sjoyal can you try again? (s3 was down yesterday to publish new version of pdfjs-dist).

(and it's not related to this problem, but adding require.ensure includes entire pdf.js + pdf.worker.js into main bundle which it wrong)

**Comment by sjoyal** [comment]
@yurydelendik `1.7.337` appears to fix the issue. Thanks!

**Comment by dschissler** [comment]
`1.7.361` works for me.  I didn't try an earlier build.

Thanks everyone.
