### ISSUE TITLE
Certain watermarks are not getting rendered properly.

### ISSUE THREAD

**Issue by aradhya1982** [mozilla/pdf.js#8085]
Link to PDF file (or attach file here): [Office 2007_009_pAGELAYOUT_Pagebackground(Watermark,Pagecolor,Pageborder).pdf](https://github.com/mozilla/pdf.js/files/786986/Office.2007_009_pAGELAYOUT_Pagebackground.Watermark.Pagecolor.Pageborder.pdf)

Configuration:
- Web browser and its version: All browsers
- Operating system and its version: Windows
- PDF.js version: 1.6.486
- Is an extension: No

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Click on open file and open the attached file.
3. Also open the attached file in acrobat reader.
4. There is a substantial difference between the 2.

What is the expected behavior? (add screenshot)
![watermark acrobat](https://cloud.githubusercontent.com/assets/2163241/23118605/c66784c0-f77a-11e6-9817-b5bb8e9e22f2.png)

What went wrong? (add screenshot)
![watermark pdfjs](https://cloud.githubusercontent.com/assets/2163241/23118662/f30a57be-f77a-11e6-8435-4b439b642333.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
That is a type 2 (axial) shading with a type 0 function (uses a table of sample values to define the function).
Here's another file with these that has a similar problem.
[Shading2Function0.pdf](https://github.com/mozilla/pdf.js/files/794323/Shading2Function0.pdf)
