### ISSUE TITLE
CLX-6220 scanned pdf renders as a blank page in pdf.js viewer

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#8090]
Link to PDF file (or attach file here): since its a client pdf, we can't share it.

Configuration:
- Web browser and its version: IE, Chrome, Firefox (all latest)
- Operating system and its version: Latest OS's
- PDF.js version: 1.6.461
- Is an extension: No

Steps to reproduce the problem:
open a a CLX-6220 scanned pdf through this pdf.js viewer.
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here): since its a client pdf, we can't share it.

Unfortunately we cannot do anything here without access to a test-case!
If possible, please try to create a reduced test-case by scanning/processing a non-sensitive document using the same hardware/software and upload that here.
Closing as incomplete for now, since there's currently no actionable information provided.

**Comment by venusakthiv** [comment]
thanks. we will try the same and provide you soon

**Comment by venusakthiv** [comment]
please find the below console log on this:

PDF e74c347b0665e24889a8151aefb7f921 [1.6 CLX-6220 Series; modified using iTextSharp™ 5.5.0 ©2000-2013 iText Group NV (AGPL-version) / CLX-6220 Series] (PDF.js: 1.6.461)  SterlingViewer.js:6295:25
Error: JPEG error: marker was not found  pdf.worker.js:2973:6
decodeScan@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:14621:8
parse@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:14983:25
JpegStream_ensureBuffer@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:24534:6
JpegStream_getBytes@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:24541:6
PDFImage_getImageBytes@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:42709:14
PDFImage_createImageData@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:42622:20
PartialEvaluator_buildPaintImageXObject/<@https://vdr.sterlingdatarooms.com/Sterlingvdr/build/pdf.worker.js:45299:22
  pdf.worker.js:2974:6
Warning: Unable to decode image: Error: JPEG error: marker was not found
