### ISSUE TITLE
Radial shading rendered incorrectly

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#8093]
Link to PDF file (or attach file here):
https://issues.apache.org/jira/secure/attachment/12618826/shading_pattern.pdf

Configuration:
- Web browser and its version: FF 51.0.1 32bit
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem: open file

What is the expected behavior? (add screenshot)
![screenshot-ar](https://cloud.githubusercontent.com/assets/6665575/23225070/e45d59b6-f930-11e6-9d6d-681d5a4c2c1a.png)

What went wrong? (add screenshot)
![screenshot-pdfjs](https://cloud.githubusercontent.com/assets/6665575/23225083/ecfbe6b4-f930-11e6-895d-18f1669e20e6.png)

**Comment by THausherr** [comment]
Also
https://issues.apache.org/jira/secure/attachment/12630566/pslib-shading.pdf
page 2, 4th shading.

**Comment by Snuffleupagus** [comment]
Duplicate of #257
