### ISSUE TITLE
options.length returns 0 when pdf contains multiple combo box with the same name

### ISSUE THREAD

**Issue by ClaudeMartel** [mozilla/pdf.js#8094]
Link to PDF file (or attach file here):
[ComboBox.pdf](https://github.com/mozilla/pdf.js/files/794376/ComboBox.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 38.14393.0.0 | Google Chrome 56.0.2924.87 (64-bit)
- Operating system and its version: Windows 10 Pro
- PDF.js version: 1.7.225
- Is an extension:

Steps to reproduce the problem:
1. The attached PDF file has two instances of the same combo box. Problem will not occur if PDF only contains one combo box.
2. Open the following html page
[ComboBox.txt](https://github.com/mozilla/pdf.js/files/794413/ComboBox.txt)

What is the expected behavior? Console should return the following paragraph twice:

DropDown1
Ch
Value2
3
Description1
Value1
Description2
Value2
Description3
Value3

What went wrong? Console returns:

DropDown1
Ch
Value2
0
DropDown1
Ch
Value2
0

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Thank you for reporting this. The pull request above fixes the issue. Note that other readers (at least Okular) have the same issue.
