### ISSUE TITLE
Missing property: exportValue of checkboxes AcroForms

### ISSUE THREAD

**Issue by ClaudeMartel** [mozilla/pdf.js#8095]
Link to PDF file (or attach file here):
[CheckBox.pdf](https://github.com/mozilla/pdf.js/files/794534/CheckBox.pdf)

Configuration:
- PDF.js version: 1.7.225

Acrobat allows multiple checkboxes to share the same name, making them act as radio buttons. While designing the document, every checkbox has an «Export Value». The attached sample pdf has two checkboxes named "Choice", one having "Yes" as export value and the other having "No".

Unfortunately, the «Export Value» of a checkbox is not available among all properties of a «Btn» control. Still, I am able to get it by adding the following line to the function «WidgetAnnotation» of «pdf.worker.js»: 

data.customAppearance = dict.get('AP');

and then, having the appearance of the checkbox, the following code displays then name and export value of every checkbox of a pdf document:

[script.txt](https://github.com/mozilla/pdf.js/files/794535/script.txt)

I simply wish that checkboxes have an exportValue property set.

**Comment by artem-alek** [comment]
Any update if PDF.js working with checkboxs/radio selected value without needed a script? I am working attempting to extra all pdf data and last thing missing is the values of check/unchecked.

**Comment by timvandermeij** [comment]
Closing since this is fixed by the pull request above.
