### ISSUE TITLE
Incompatible or broken font

### ISSUE THREAD

**Issue by jasonjensen** [mozilla/pdf.js#8097]
The fonts in the attached PDF are not loading correctly. Qpdf found no errors, but that is of course not a guarantee. The first error comes from the font "AdvTT7b515deb", but I think there are more.

Link to PDF file (or attach file here): [brokenFont.pdf](https://github.com/mozilla/pdf.js/files/795201/brokenFont.pdf)

Configuration:
- Web browser and its version: Chrome Version 56.0.2924.87 (64-bit)
- Operating system and its version: macOS version 10.12.2 (16C68)
- PDF.js version: Current demo viewer
- Is an extension: no.

Steps to reproduce the problem:
1. Open the attached PDF in the demo viewer

What is the expected behavior? (add screenshot)
This is what (part of) the first page looks like in Acrobat Reader:
![brokenfontadobe](https://cloud.githubusercontent.com/assets/7598563/23239537/e71d25e6-f935-11e6-9f42-2623f6f37ddf.png)

What went wrong? (add screenshot)
This is how it loads in pdf.js:
![brokenfontpdfjs](https://cloud.githubusercontent.com/assets/7598563/23239548/f39c2c86-f935-11e6-89b5-396f520b1e43.png)

**Comment by Snuffleupagus** [comment]
This regressed in PR #6724, however please note that there's actually bugs in the font files *themselves* as well.

Console log *after* PR #6724:
```
PDF 499356774a91da55dce73a8a7da2bafe [1.3 Acrobat Distiller 9.0.0 (Windows) / Co-Action Publishing] (PDF.js: -)  app.js:1084:7
Warning: Error during font loading: data is undefined  util.js:284:5
Warning: Out of bounds subrIndex for callgsubr  util.js:284:5
Warning: Out of bounds subrIndex for callgsubr  util.js:284:5
Warning: Error during font loading: data is undefined  util.js:284:5
Warning: Error during font loading: data is undefined  util.js:284:5
```
Console log *before* PR #6724:
```
PDF 499356774a91da55dce73a8a7da2bafe [1.3 Acrobat Distiller 9.0.0 (Windows) / Co-Action Publishing] (PDF.js: -)  viewer.js:1000:7
Warning: Not enough parameters for vhcurveto; actual: 2, expected: 4  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for callgsubr; actual: 0, expected: 1  util.js:245:5
Warning: Not enough parameters for hstem; actual: 0, expected: 2  util.js:245:5
```
/cc @brendandahl

**Comment by jasonjensen** [comment]
Thank you for the reply and explanation. I believe the pull request above will fix this particular problem.
