### ISSUE TITLE
Accented characters and search / highlight

### ISSUE THREAD

**Issue by devanonyme** [mozilla/pdf.js#8101]
Hello,

I have noticed that PDF.js is not doing a match ignoring accentuation (contrary to Acrobat and Chrome native renderer).

By exemple, "Montréal" will not find and occurance if "Montreal" is used in the text (and vice versa).

I guess this behavior is out of specs (and would likely slow down search?) but is this something that was considered to fix in the future?

Thanks!

**Comment by timvandermeij** [comment]
Yes, this is by design. No normalization is done as it would mean that matches may be found that are not actually matches. For instance, just searching "é", I would expect "Montréal" to be matched, but not all other words with a normal "e" in them. Aside from the expectation, it's also more expensive to normalize all text.

Closing as answered.

**Comment by rjpedrosa** [comment]
Hi. Is there any way to enable this?, so e.g. search for "montreal" would both match "montreal" and "montréal"? Thanks.

**Comment by CesarUCIGIT** [comment]
@eric-gagnon can you please give a straight answer on how to do this? The example you share is not source code is only working website.

**Comment by eric-gagnon** [comment]
You can see the hacked file here : https://collections.banq.qc.ca/biblio/js/pdfjs/pdfjs-1.6.210-dist_banq_20200615/web/viewer.js, have a look at PDFFindController_calcFindWordMatch and stopwords by exemple (compare with a diff tool with the unchanged file from 1.6.210, there are likely other changes (identified by "Fix BAnQ Numerique" for our needs and some that can be ignored for this feature).

I was not involved much in that particular hack / patch so I cannot say more than this.

This was done using 1.6.210. I think I remember having notice some important rework in more recent implementation but it should be possible to find the function that does the transformation.

**Comment by CesarUCIGIT** [comment]
Thank you very much @eric-gagnon, I share here a version of viewer file for latest lib with the mod that allows searching special characters too. https://drive.google.com/file/d/1tWOW_P6-O8ATiQc9cOVt2LAToRB-niHc/view?usp=sharing

**Comment by eric-gagnon** [comment]
Glad you where able to work something out of the exemple.

Eric
