### ISSUE TITLE
Error: JPEG error: marker was not found pdf.worker.js:2973:6 ......... ................... Warning: Unable to decode image: Error: JPEG error: marker was not found

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#8104]
Link to PDF file (or attach file here): since its a client pdf, we can't share it.

Configuration:

Web browser and its version: IE, Chrome, Firefox (all latest)
Operating system and its version: Latest OS's
PDF.js version: 1.6.461
Is an extension: No
Steps to reproduce the problem:
1.open a a CLX-6220 scanned pdf through this pdf.js viewer.

**please find the below console log on this:

PDF e74c347b0665e24889a8151aefb7f921 [1.6 CLX-6220 Series; modified using iTextSharp™ 5.5.0 ©2000-2013 iText Group NV (AGPL-version) / CLX-6220 Series] (PDF.js: 1.6.461) Viewer.js:6295:25
Error: JPEG error: marker was not found pdf.worker.js:2973:6
decodeScan@https:///pdf.worker.js:14621:8
parse@https://pdf.worker.js:14983:25
JpegStream_ensureBuffer@https:///pdf.worker.js:24534:6
JpegStream_getBytes@https:///pdf.worker.js:24541:6
PDFImage_getImageBytes@https://build/pdf.worker.js:42709:14
PDFImage_createImageData@https:///pdf.worker.js:42622:20
PartialEvaluator_buildPaintImageXObject/<@https:///build/pdf.worker.js:45299:22
pdf.worker.js:2974:6
Warning: Unable to decode image: Error: JPEG error: marker was not found**

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here): since its a client pdf, we can't share it.

Closing as incomplete, since it's not possible to debug an issue with a just a copy of the console log.

As I explained in https://github.com/mozilla/pdf.js/issues/8090#issuecomment-281347842, we *need* the PDF file *itself* to be able to help here.

**Comment by venusakthiv** [comment]
OKay.. thanks!!
