### ISSUE TITLE
incorrect shading of text 

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#8111]
Link to PDF file (or attach file here):
https://issues.apache.org/jira/secure/attachment/12650283/000004_ShadingPatternTextPDF.pdf

Configuration:
- Web browser and its version: FF 51.0.1 32bit
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem:
display file

What is the expected behavior? (add screenshot)
![ok](https://cloud.githubusercontent.com/assets/6665575/23339534/5ff2de9c-fc25-11e6-837e-0fdaf81b4ca9.png)

What went wrong? (add screenshot)
![nok](https://cloud.githubusercontent.com/assets/6665575/23339536/63f7a37e-fc25-11e6-813c-cc218cc4def3.png)

possibly similar problem:
https://www.pdflib.com/fileadmin/pdflib/Cookbook/pdf/color_gradient.pdf (shaded text completely missing)
https://issues.apache.org/jira/secure/attachment/12630566/pslib-shading.pdf (page 4, part of text missing)
https://issues.apache.org/jira/secure/attachment/12652009/pattern-shading-2-4-idMatrix.pdf (some text missing)
https://issues.apache.org/jira/secure/attachment/12652010/pattern-shading-2-4-noMatrix.pdf (some text missing)

**Comment by mate-user** [comment]
Uploaded copies of these PDFs in case they disappear from the source.

https://issues.apache.org/jira/secure/attachment/12650283/000004_ShadingPatternTextPDF.pdf
[000004_ShadingPatternTextPDF.pdf](https://github.com/mozilla/pdf.js/files/2822338/000004_ShadingPatternTextPDF.pdf)

https://issues.apache.org/jira/secure/attachment/12630566/pslib-shading.pdf
[pslib-shading.pdf](https://github.com/mozilla/pdf.js/files/2822356/pslib-shading.pdf)

https://issues.apache.org/jira/secure/attachment/12652009/pattern-shading-2-4-idMatrix.pdf
[pattern-shading-2-4-idMatrix.pdf](https://github.com/mozilla/pdf.js/files/2822364/pattern-shading-2-4-idMatrix.pdf)

https://issues.apache.org/jira/secure/attachment/12652010/pattern-shading-2-4-noMatrix.pdf
[pattern-shading-2-4-noMatrix.pdf](https://github.com/mozilla/pdf.js/files/2822370/pattern-shading-2-4-noMatrix.pdf)
