### ISSUE TITLE
Bar charts are not rendered properly 

### ISSUE THREAD

**Issue by ramoh** [mozilla/pdf.js#8117]
[Test.pdf](https://github.com/mozilla/pdf.js/files/806780/Test.pdf)

Configuration:
- Web browser and its version: Chrome Version 56.0.2924.87 (64-bit)
- Operating system and its version: Windows 7 
- PDF.js version: Version which is hosted here https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension:

Steps to reproduce the problem:
1.  Upload the attached pdf  at the following URL https://mozilla.github.io/pdf.js/web/viewer.html
2.  You can see that bar charts are not being rendered properly 

Bar chart is not being rendered properly .See the screen shot below 
![image](https://cloud.githubusercontent.com/assets/2700577/23405418/24f7282c-fde0-11e6-8a0f-dc49a6826a7c.png)

It should look like this.
![image](https://cloud.githubusercontent.com/assets/2700577/23405516/9559a068-fde0-11e6-8dd7-0da25f86c0b8.png)

**Comment by ramoh** [comment]
Is there a workaround  to get around this fix ?

**Comment by THausherr** [comment]
The bbox of the patterns is a bit... unusual, it is [0 8 8 0]. Change it to [0 0 8 8] and the file is rendered properly. I.e. in this case, the 2nd and 4th value must be switched.

**Comment by Snuffleupagus** [comment]
@THausherr Very nice debugging!
Based on this, a naive solution could perhaps be to use `Util.normalizeRect` at https://github.com/mozilla/pdf.js/blob/d0d9843a0e62b8abdfcd293f7e6acce0b9ce7f6d/src/display/pattern_helper.js#L321.
(However, I've not actually run any tests/nor checked if that makes sense from a spec point of view here.)

**Comment by THausherr** [comment]
Yes, this is similar to what we do in PDFBox:
https://svn.apache.org/viewvc/pdfbox/trunk/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/common/PDRectangle.java?revision=1750159&view=markup#l129
I've often seen such weird rectangles in BBox arrays.
