### ISSUE TITLE
Html to pdf.

### ISSUE THREAD

**Issue by kaflanTech** [mozilla/pdf.js#8118]
How to use this library to build extinction, html to pdf.
User push in plugin button, program build pdf file and send to my server. Can this library do it?

**Comment by Snuffleupagus** [comment]
As explained in the README, PDF.js is a PDF *viewer* and not a PDF creator.
Hence what you're asking isn't possible, and you may have confused this project with e.g. https://github.com/MrRio/jsPDF/.

Closing as answered.
