### ISSUE TITLE
Browsing history disabled when pdf displayed in an iframe

### ISSUE THREAD

**Issue by kgopdev** [mozilla/pdf.js#8121]
My application displays the pdf in an iframe. I want to provide the capability for the user to go back/forward when user clicks on hyperlinks to content on the same pdf. I see that this functionality is already implemented but is disabled if the pdf is embedded in an iframe. I was hoping to know why it is disabled and what are the drawbacks of enabling it when the pdf is embedded. I did not run into any issues when I enabled the browsing history and tested it for an embedded pdf. 
The relevant code from pdf.js/web/app.js below -
```
if (!pdfjsLib.PDFJS.disableHistory && !self.isViewerEmbedded) {
  // The browsing history is only enabled when the viewer is standalone,
  // i.e. not when it is embedded in a web page.
  if (!self.viewerPrefs['showPreviousViewOnLoad']) {
    self.pdfHistory.clearHistoryState();
  }
  self.pdfHistory.initialize(self.documentFingerprint);
  if (self.pdfHistory.initialDestination) {
    self.initialDestination = self.pdfHistory.initialDestination;
  } else if (self.pdfHistory.initialBookmark) {
  self.initialBookmark = self.pdfHistory.initialBookmark;
  }
}
```

**Comment by Snuffleupagus** [comment]
> I was hoping to know why it is disabled and what are the drawbacks of enabling it when the pdf is embedded.

Because modifying the browser history in an `<iframe>` will affect/overwrite the browser history of the *top level* document, which given the sort of history manipulation that the PDF.js viewer does could very well have unintended and unwanted side-effects.

Given that this should be an edge-case, I'd suggest closing this issue as WONTFIX.

**Comment by wideweide** [comment]
@kgopdev 
it seems not disabled in an frame even set disableHistory=true 
https://github.com/mozilla/pdf.js/issues/12208

and where is the self.pdfHistory.clearHistoryState();?
