### ISSUE TITLE
Search is not working correctly in viewer.html

### ISSUE THREAD

**Issue by lzqwang** [mozilla/pdf.js#8123]
Source PDF
[Book1.pdf](https://github.com/mozilla/pdf.js/files/815557/Book1.pdf)

Configuration:
- Web browser and its version: IE 11/ chrome ...
- Operating system and its version: windows7
- PDF.js version: latest version

Steps to reproduce the problem:
1.  View a pdf file(the file is converted from word or excel)
2. Search a special text

What is the expected behavior? (add screenshot)
Highlighted matched text only
What went wrong? (add screenshot)
![searcherror](https://cloud.githubusercontent.com/assets/19404763/23534888/bc8cc432-fff5-11e6-8f60-3eebe08c1231.png)

I did a little debug, the pagecontents return from the pdf.js remove all the spaces between the separeted words, then the indexof function will mismatch the query.
Could anyone help on this issue?
Thanks a lot.

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
