### ISSUE TITLE
PDF displays under unexpected 180 degree rotation

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8125]
Link to PDF file (or attach file here):

[activity-calendar (1).pdf](https://github.com/mozilla/pdf.js/files/816480/activity-calendar.1.pdf)

Configuration:
- Tried in Chrome, Firefox, Safari on Mac
- PDF.js version: Latest through https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. Upload the file to the web viewer
2. It will appear rotated by 180 degrees!

What is the expected behavior? (add screenshot)

Under other viewers (e.g. Mac Preview):

![screen shot 2017-03-03 at 10 21 58](https://cloud.githubusercontent.com/assets/786238/23547519/546e1ff8-fffb-11e6-96b7-68704bbf86e9.png)

What went wrong? (add screenshot)

![screen shot 2017-03-03 at 10 19 51](https://cloud.githubusercontent.com/assets/786238/23547531/5d837d9a-fffb-11e6-860b-8755c91d53c8.png)

Thanks,

Dan

**Comment by viral-w3nuts** [comment]
Did you get any solution for this ? I am having same issue.
Any help or suggestion appreciated thanks.
