### ISSUE TITLE
print pdf will add the pdf filename & url addr at the top & end of the page

### ISSUE THREAD

**Issue by TianYu-hpu** [mozilla/pdf.js#8137]
Link to PDF file (or attach file here):
[test.pdf](https://github.com/mozilla/pdf.js/files/826924/test.pdf)

Configuration:
- Web browser and its version: IE 9 * Chrome
- Operating system and its version: Windows7
- PDF.js version: 1.6.210
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
dont add the url addr & filename & date on the printed page
expected is this
![normal](https://cloud.githubusercontent.com/assets/6236078/23694489/24b9467a-0415-11e7-8975-67f1c803e5dd.jpg)

What went wrong? (add screenshot)
![unnormal01](https://cloud.githubusercontent.com/assets/6236078/23694495/2c958a70-0415-11e7-9fc8-f7bc69c0f0e4.jpg)
![unnormal02](https://cloud.githubusercontent.com/assets/6236078/23694502/31ab317c-0415-11e7-8ecd-3b4c70b2775d.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://pdfjs.zenmaster.com.cn/plugins/pdfjs/web/viewer.html?file=/test.pdf

**Comment by timvandermeij** [comment]
Closing since we can't fix this. You have to manually disable this in your browser's print settings. There is no way for us to do that via JavaScript, unfortunately.
