### ISSUE TITLE
how can i display stamp?

### ISSUE THREAD

**Issue by kiner-tang** [mozilla/pdf.js#8147]
Why can not the stamp be displayed in pdf?

It can be normal to show in my mac in chrome browser！

- This picture is chrome directly open pdf
![image](https://cloud.githubusercontent.com/assets/10286961/23786664/545559ce-05a9-11e7-9db8-9f29c550b328.png)

- This picture is the effect of using pdfjs
![image](https://cloud.githubusercontent.com/assets/10286961/23786683/678efbc6-05a9-11e7-8cd1-f8f1ed25d4ef.png)

**Comment by Snuffleupagus** [comment]
Closing as incomplete for now; please provide *all* the of information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) in order to re-open the issue (note that access to the PDF file in question is crucial here).
