### ISSUE TITLE
WebkitBlobRessource error 1 when reloading blob on IOS

### ISSUE THREAD

**Issue by eric-gagnon** [mozilla/pdf.js#8152]
The problem occur when using file download on IOS and using reload on the window displaying the blob.

Configuration:
Nothing special. PDFjs viewer.

Web browser and its version:
Operating system and its version: IOS 10.2
PDF.js version: 1.6.210.
Is an extension:
Steps to reproduce the problem: 1. 2.
- Using PDFViewer, after displaying a PDF, use the download file button.
- A new tab open that show the pdf in native pdf renderer of Safari.
- Use "reload" of the page : the page display an error instead of displaying the pdf again (in native pdf renderer of Safari)

What is the expected behavior? (add screenshot)
Best case : Display the pdf again (at least if the tab containing pdf.js displaying the pdf is still open)
Acceptable : empty page or user friendly message.

What went wrong? (add screenshot)
I get an error page like (approximatively translated from french) : 
Safari cannot open this page.
Error: The operation cannot complete  (WebkitBlobRessource error 1).

I get an error like (approximatively translated from french) : 
Safari cannot open this page.
Error: The operation cannot complete  (WebkitBlobRessource error 1).

Just reporting for documentation as I dont think there is a solution to this problem. The ressource have very likely been released from memory, maybe Webkit / Safari could display a more user friendly message ( I did a quick search on webkit but base but found no related issue).

**Comment by Snuffleupagus** [comment]
PR #8081 might help here, since it should disable `blob` usage in Chrome on iOS.
What version of PDF.js are you using?

(For future reference, please provide as much of the information in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md as possible when opening an issue.)

**Comment by devanonyme** [comment]
Yes, sorry for skipping details.

I use 1.6.210. I will get the check version of IOS but I think it's version 10.

Thanks for reference to #8081, I will read it.

**Comment by Snuffleupagus** [comment]
Given everything mentioned in https://github.com/mozilla/pdf.js/issues/8152#issue-213375356, this really seems like a browser-specific bug rather than a PDF.js one; should this be closed since there doesn't appear to be anything we can do here?

**Comment by eric-gagnon** [comment]
Yes, I will close, thanks.
