### ISSUE TITLE
This hand written pdf file has no text on the page; but should show "Hello, world."

### ISSUE THREAD

**Issue by myrkraverk** [mozilla/pdf.js#8153]
Link to PDF file (or attach file here):
[new.pdf](https://github.com/mozilla/pdf.js/files/835689/new.pdf)

Configuration:
- Web browser and its version: SeaMonkey 2.46
- Operating system and its version: OS X 10.10.5
- PDF.js version: Today, from http://mzl.la/pdf-xpi
- Is an extension: yes

Steps to reproduce the problem:
1. View the attache pdf file.
2. The page is blank, but should show "Hello, world." on the center of the page.  It does in the OS X Preview tool.

What is the expected behavior? (add screenshot)
![screen shot 2017-03-11 at 7 05 20 pm](https://cloud.githubusercontent.com/assets/1880957/23822731/b73c90ea-068d-11e7-83cf-188a7ada6c14.png)

What went wrong? (add screenshot)
![screen shot 2017-03-11 at 7 04 15 pm](https://cloud.githubusercontent.com/assets/1880957/23822725/a4978724-068d-11e7-8576-f57d3d9fbeb4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
Assuming you created this file yourself - it is incorrect, here's why:
```
4 0 obj
<<
	/Type /Font
	/Subtype /Type1
	/BaseFont /Times-Roman
>>
5 0 obj

```
The "endobj" is missing. And there's more that is wrong: the offsets in the table are incorrect, and the comment line below %PDF is missing (must have bytes > 128, e.g. "%âãÏÓ").

**Comment by myrkraverk** [comment]
Yes, I made the file and did some beginner mistakes.  The point here is that that pdf.js is the only PDF viewer I tried which _fails silently_; not even in the error console.

I have no recommendation; whether you choose to give the user a message that the file is corrupt, or fix it silently like all the other viewers I tried; only that you don't fail silently.

**Comment by Snuffleupagus** [comment]
> The point here is that that pdf.js is the only PDF viewer I tried which fails silently; not even showing anything in the error console.

That's not entirely true, the following is a copy from the browser console when loading the attached PDF file:
```
Error: Invalid XRef stream header  pdf.worker.js:345:3
XRef_readXRef@resource://pdf.js/build/pdf.worker.js:30801:7
XRef_parse@resource://pdf.js/build/pdf.worker.js:30447:19
PDFDocument_setup@resource://pdf.js/build/pdf.worker.js:37848:4
PDFDocument_parse@resource://pdf.js/build/pdf.worker.js:37744:4
LocalPdfManager_ensure/<@resource://pdf.js/build/pdf.worker.js:48291:16
LocalPdfManager_ensure@resource://pdf.js/build/pdf.worker.js:48286:11
BasePdfManager_ensureDoc@resource://pdf.js/build/pdf.worker.js:48238:11
loadDocument/</<@resource://pdf.js/build/pdf.worker.js:34239:6
promise callback*loadDocument/<@resource://pdf.js/build/pdf.worker.js:34238:5
promise callback*loadDocument@resource://pdf.js/build/pdf.worker.js:34237:4
promise callback*setupDoc@resource://pdf.js/build/pdf.worker.js:34400:4
wphReady@resource://pdf.js/build/pdf.worker.js:34563:4
messageHandlerComObjOnMessage@resource://pdf.js/build/pdf.worker.js:1326:5
EventListener.handleEvent*MessageHandler@resource://pdf.js/build/pdf.worker.js:1332:2
wphCreateDocumentHandler@resource://pdf.js/build/pdf.worker.js:34200:17
wphSetupDoc@resource://pdf.js/build/pdf.worker.js:34189:11
messageHandlerComObjOnMessage/<@resource://pdf.js/build/pdf.worker.js:1304:13
promise callback*messageHandlerComObjOnMessage@resource://pdf.js/build/pdf.worker.js:1303:5
EventListener.handleEvent*MessageHandler@resource://pdf.js/build/pdf.worker.js:1332:2
initializeWorker@resource://pdf.js/build/pdf.worker.js:34570:16
@resource://pdf.js/build/pdf.worker.js:34575:2
__w_pdfjs_require__@resource://pdf.js/build/pdf.worker.js:45:12
@resource://pdf.js/build/pdf.worker.js:49137:23
__w_pdfjs_require__@resource://pdf.js/build/pdf.worker.js:45:12
@resource://pdf.js/build/pdf.worker.js:91:18
@resource://pdf.js/build/pdf.worker.js:26:18
webpackUniversalModuleDefinition@resource://pdf.js/build/pdf.worker.js:24:72
@resource://pdf.js/build/pdf.worker.js:16:11  pdf.worker.js:346:3
Warning: Indexing all PDF objects  pdf.worker.js:337:3
PDF 000be5cf1d034166d66671ee35ff187f [1.3 - / -] (PDF.js: 1.7.365)  viewer.js:1484:4
```

> Yes, I made the file and did some beginner mistakes.

I'd say that this issue is a good example of why it's generally not a great idea to manually edit PDF files, since it's just too easy to make mistakes (I'm speaking from personal experience here).
My advice would be to always run hand-edited PDF files through some PDF creation tool[1] to clean them up, in order to avoid problems like these.

> [...] or fix it silently like all the other viewers I tried;

Please note that PDF.js is able to recover from the corrupt XRef table, otherwise the file wouldn't load at all. The reason that certain parts of the file isn't rendered is because of the missing `endobj` command, as described in https://github.com/mozilla/pdf.js/issues/8153#issuecomment-285934302, which means that we're not finding all objects.
While that is probably possible to fix, it would most likely make the `XRef.indexObjects` method even more complicated. Given how rare this issue seem to be, since no actual PDF software seems to produce files that are broken in this way, I'm just not certain if fixing this will be a priority.

---
[1] Examples of such PDF tools: https://www.pdflabs.com/tools/pdftk-server/ and http://qpdf.sourceforge.net/

**Comment by myrkraverk** [comment]
>That's not entirely true, the following is a copy from the browser console when loading the attached PDF file:

SeaMonkey has both an _error console_ and a _browser console_.  The former shows nothing, and I didn't check the latter.

> Given how rare this issue seem to be, since no actual PDF software seems to produce files that are broken in this way, I'm just not certain if fixing this will be a priority.

Fair enough; I still think giving the user (without checking some obscure log) a fair warning that the PDF is invalid is the right thing to do.

I'm closing the issue; thanks for looking into it.
