### ISSUE TITLE
Command Token Too Long when parsing Base64 string

### ISSUE THREAD

**Issue by TylerDev6** [mozilla/pdf.js#8163]
Ok, my setup is a bit rough, but here's what I'm doing:

1. Angular-CLI includes PDFJS and the worker in an inline bundle, so I grab a reference to the PDFJS global and set the workerSrc to the bundled js file. Not sure if this is working but I am getting a fake worker warning.

2. I am retrieving base64 encoded versions of PDFs from my server and passing them in as data to be rendered. I've tried loading the PDF in question into your viewer as a PDF and it works fine. I have also tried taking the base64 string and running it through a decoder and it converts back to PDF fine as well.

3. When I do this, I get "Error: Command token is too long: 128" as well as "Invalid PDF Structure". 

Using latest Chrome and latest PDFJS dist.

**Comment by TylerDev6** [comment]
forgot to use ATOB. Closing now.

**Comment by wi-ski** [comment]
What is ATOB?

**Comment by timvandermeij** [comment]
https://github.com/mozilla/pdf.js/blob/99060e2485cacb8513e7bc50d88b70101069b1c9/examples/learning/helloworld64.html#L16
