### ISSUE TITLE
How to set `Cache-Control` header in request via `getDocument` method ?

### ISSUE THREAD

**Issue by vsymguysung** [mozilla/pdf.js#8175]
I am wondering if there is a way of setting `Cache-Control': 'max-age=1000'` via `getDocument` method.   Thanks much in advance.

**Comment by Snuffleupagus** [comment]
There's a `httpHeaders` parameter on `getDocument`, please refer to https://github.com/mozilla/pdf.js/blob/3ff872b7968c299f1c4743193056b4eabfe29489/src/display/api.js#L123.
That parameter is then used in https://github.com/mozilla/pdf.js/blob/3ff872b7968c299f1c4743193056b4eabfe29489/src/core/network.js#L112-L118.

Closing as answered.

**Comment by SongJie123** [comment]
Could you please tell me how to add http-headers in the getDocument? I'm a little bit confused and don't know how to do it. Thank you very much.

**Comment by chenwuchi** [comment]
The following code works for me.
```
// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window["pdfjs-dist/build/pdf"];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc =
      "//mozilla.github.io/pdf.js/build/pdf.worker.js";

// Asynchronous download of PDF
var loadingTask = pdfjsLib.getDocument({
    url: <external pdf link>,
    httpHeaders: {
      "Cache-Control": <cache control content>,
    },
});
```
