### ISSUE TITLE
Add watermark to a page for viewing & printing

### ISSUE THREAD

**Issue by rajegannathan** [mozilla/pdf.js#8178]
\Hi,

I am working on a project where I want to add watermark to a pdf document that is loaded.  The watermark has to persist even when the document gets printed.  Is there any documentation on where we should look into for doing this?  If not, can someone point me to the right direction for doing this?

There is an AnnotationType.WATERMARK = 24 in shared/util.js.  But I couldn't find its usage anywhere in the code.  Also, debugging a page which already has a watermark ends up eating a lot of time without much productive results.  I would really appreciate if someone can point me in the right direction for this.

Thank you,

**Comment by timvandermeij** [comment]
Watermarking is out of scope for the PDF.js project as the library only renders PDF files and does not edit them. You could render a text overlay over each rendered canvas, or render the text onto the canvas. Refer to previously closed issues (https://github.com/mozilla/pdf.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20watermark) for more insights.

**Comment by DrWebDeveloper** [comment]
You can design/generate a free script from [protectweb.site](https://protectweb.site) to watermark your webpages in one click, super-easy way to add a watermark to webpages.
