### ISSUE TITLE
[Print deviation]  When pdf file has vertical page  and horizontial page at same time...

### ISSUE THREAD

**Issue by shen341** [mozilla/pdf.js#8181]
Link to PDF file (or attach file here):
[Muli-size.pdf](https://github.com/mozilla/pdf.js/files/859951/Muli-size.pdf)

Configuration:
- Web browser and its version: Chrome 56.0.2924.87
- Operating system and its version: window 7
- PDF.js version: pdfjs V1.7.225
- Is an extension:

Steps to reproduce the problem:
1. Open file in online website
![image](https://cloud.githubusercontent.com/assets/18575119/24175978/b0ab9b70-0edc-11e7-8ca1-15ea7a8e5d4d.png)

2.Click print button to preview , deviation is happened
![image](https://cloud.githubusercontent.com/assets/18575119/24176079/3a1dd508-0edd-11e7-9a5a-cd08ee3682da.png)

What is the expected behavior? (add screenshot)
When preview/print multiple size pages in a pdf file, want normal display/ print.
 ->pdfjs v1.6.210 has not same problem...

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by shen341** [comment]
Use another server  method already Solved it…
I am weak in javascript programming...but really hope pdf.js can clear it!
■server  method:
############################################
1.Add new print button overlay originally  print button 
2.when click print button,kick off  a ajax communication with server 
 for check  this pdf file  have  vertical  and horizontal page 
3.if not have,trigger originally  print event
4.if have,use server process(like Java/PHP...etc) to split pdffile to two files
    (※one is all vertical  pages,another is all horizontal  pages )
5.popup new small window with pdf.js  to load splited file and auto print it
############################################

**Comment by Snuffleupagus** [comment]
Fixed by PR #13120.
