### ISSUE TITLE
3 Of 9 barcode is not generated properly

### ISSUE THREAD

**Issue by lenfocus** [mozilla/pdf.js#8187]
Link to PDF file (or attach file here):
**PDF file display**
![capture_item1](https://cloud.githubusercontent.com/assets/8380626/24237862/175956f8-0fe3-11e7-97fb-e1f74d3435fb.JPG)

**PDF preview view PDF.js**
![capture_item2](https://cloud.githubusercontent.com/assets/8380626/24237901/4e141796-0fe3-11e7-8adf-740f4fcb6ec4.JPG)

Configuration:
- Web browser and its version:  Chrome 50.0.2661.94 m
- Operating system and its version: windows 7
- PDF.js version: v1.6.210
- Is an extension: No

Steps to reproduce the problem:
1. The PDF converts to base64 string 
2. Use the base64 string to generate preview

What is the expected behavior? (add screenshot)
![capture_item1](https://cloud.githubusercontent.com/assets/8380626/24237862/175956f8-0fe3-11e7-97fb-e1f74d3435fb.JPG)

What went wrong? (add screenshot)
3 Of 9 barcode is generated with extra space in the middle

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Can you provide sample PDF? It's hard to tell what's causing it. My bet it's a low quality image in the PDF.

**Comment by lenfocus** [comment]
Thanks Yury. I have sent PDF files and the source code to your mailbox for recommendation.

**Comment by yurydelendik** [comment]
Reduced test case

[case1.pdf](https://github.com/mozilla/pdf.js/files/869253/case1.pdf)

**Comment by lenfocus** [comment]
Hi Yury,

I have tried again with the reduced test case. The situation is screendump for your information.
![image](https://cloud.githubusercontent.com/assets/8380626/24338087/40154ac6-12d5-11e7-9d8f-abb4caed14b6.png)

**Test project**
[TestPDFJS.txt](https://github.com/mozilla/pdf.js/files/871297/TestPDFJS.txt)

Change the '.txt' to '.zip' and unzip

**Comment by bntconan** [comment]
Hi, may i know if there is any update? I have encountered the same issue too.
