### ISSUE TITLE
Error: JPEG error: marker was not found. Scanned from Samsung MFP.

### ISSUE THREAD

**Issue by akeno379** [mozilla/pdf.js#8189]
Link to PDF file (or attach file here): [scan.pdf](https://github.com/mozilla/pdf.js/files/865245/scan.pdf)

Configuration:
- Web browser and its version: Chrome 56.0.2924.87 (64-bit) and Firefox 52.0.1 (64-bit)
- Operating system and its version: Windows 10 64 bit and Ubuntu 16.10
- PDF.js version: Stable 1.6.210 and Beta 1.7.225
- Is an extension: No

Steps to reproduce the problem:
1. Upload the pdf to the Online demo site https://mozilla.github.io/pdf.js/web/viewer.html
2. All pages are blank

What is the expected behavior? PDF will be rendered properly 
![expected](https://cloud.githubusercontent.com/assets/4175765/24256036/1babfc80-1022-11e7-9ca1-ef7d1a68aa10.PNG)

What went wrong? There are pages but no content.  In the developer console of the browser this is the logs:
`PDF a650df87b150696f9e4415aeeaece60c [1.4 CLX-8380 Series / 300] (PDF.js: 1.7.378)
pdf.worker.js:345 Error: JPEG error: marker was not found
/pdf.js/build/pdf.worker.js:345 Error: JPEG error: marker was not found
pdf.worker.js:346     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:346:15)
    at decodeScan (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44260:5)
    at JpegImage.parse (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44637:22)
    at JpegStream_ensureBuffer [as ensureBuffer] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3087:13)
    at JpegStream_getBytes [as getBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3094:8)
    at PDFImage_getImageBytes [as getImageBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42687:22)
    at PDFImage_createImageData [as createImageData] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42619:26)
    at https://mozilla.github.io/pdf.js/build/pdf.worker.js:25799:28
/pdf.js/build/pdf.worker.js:346     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:346:15)
    at decodeScan (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44260:5)
    at JpegImage.parse (https://mozilla.github.io/pdf.js/build/pdf.worker.js:44637:22)
    at JpegStream_ensureBuffer [as ensureBuffer] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3087:13)
    at JpegStream_getBytes [as getBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3094:8)
    at PDFImage_getImageBytes [as getImageBytes] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42687:22)
    at PDFImage_createImageData [as createImageData] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:42619:26)
    at https://mozilla.github.io/pdf.js/build/pdf.worker.js:25799:28
`
![actual](https://cloud.githubusercontent.com/assets/4175765/24256164/59f7429c-1022-11e7-862b-5236468aa597.PNG)

I think this is also related with #8090 and #8104

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Tested using mozilla.github.io/pdf.js

**Comment by joopeed** [comment]
Similar bug on version 52.0.2 not solved yet:
Warning: Unable to decode image: Error: JPEG error: marker was not found pdf.worker.js:2965:6
Warning: Dependent image isn't ready yet pdf.js:265:6
Error: JPEG error: marker was not found pdf.worker.js:2973:6
decodeScan@resource://pdf.js/build/pdf.worker.js:13800:8
parse@resource://pdf.js/build/pdf.worker.js:14162:25
JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:23708:6

**Comment by yurydelendik** [comment]
@joopeed can you confirm that the scan.pdf attached in OP produces the error you mentioned above?

**Comment by joopeed** [comment]
Yes, I'm using version 52.0.2 of firefox, and the scan.pdf produces the error:
Error: JPEG error: marker was not found  pdf.worker.js:3841:11
decodeScan@resource://pdf.js/build/pdf.worker.js:14246:15
parse@resource://pdf.js/build/pdf.worker.js:14668:33
JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:24613:11
JpegStream_getBytes@resource://pdf.js/build/pdf.worker.js:24620:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:44455:20
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:44378:32
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:47300:29
  pdf.worker.js:3842:11
Warning: Unable to decode image: Error: JPEG error: marker was not found  pdf.worker.js:3830:11
Warning: Dependent image isn't ready yet  pdf.js:273:11
Error: JPEG error: marker was not found  pdf.worker.js:3841:11
decodeScan@resource://pdf.js/build/pdf.worker.js:14246:15
parse@resource://pdf.js/build/pdf.worker.js:14668:33
JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:24613:11
JpegStream_getBytes@resource://pdf.js/build/pdf.worker.js:24620:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:44455:20
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:44378:32
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:47300:29
  pdf.worker.js:3842:11
Warning: Unable to decode image: Error: JPEG error: marker was not found

**Comment by yurydelendik** [comment]
This issue is fixed in ff55 -- see https://bugzilla.mozilla.org/show_bug.cgi?id=1352276
