### ISSUE TITLE
How to draw some simple graphics on the PDF?

### ISSUE THREAD

**Issue by violin84** [mozilla/pdf.js#8191]
My project isn't just open a pdf in the web, I need to add a function which can draw draw some simple graphics on such as: line, rect, circle. Can you tell me which js and which function I should deal with?
![20170324165250](https://cloud.githubusercontent.com/assets/26641545/24287423/a1441caa-10b4-11e7-9da4-37c74b65ab10.jpg)

**Comment by timvandermeij** [comment]
You can draw anything you want onto the rendered canvas. Taking https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html for example, you can just draw onto the canvas after PDF.js rendered it.

**Comment by violin84** [comment]
Yes, what you said is right. But I need to remember which page I have drawn. For example, I draw a line in page 1, then I draw a rect in page 2, and I draw a circle in page 10. When I drag the slider or pagesButtons, it's should show me what had drawn in those pages, while nothing graphics in others.

I don't know which js and which function I should deal with.

**Comment by violin84** [comment]
1.  I just download the master branch, it dosen't contian build/pdf.js and build/pdf.worker.js, then I search them in internet and add them myself, but the web tell me that:  ReferenceError: PDFJS is not defined --- helloworld.html:33:3

2.  The page just too easy, no any buttons?

3.   I need to remember which page I have drawn. For example, I draw a line in page 1, then I draw a rect in page 2, and I draw a circle in page 10. When I drag the slider or pagesButtons, it's should show me what had drawn in those pages, while nothing graphics in others. Beside,  the accurate x, y coordinates should be following when I dragging the slider.

I don't know which js and which function I should deal with. I think you can tell me.

**Comment by Snuffleupagus** [comment]
> I don't know which js and which function I should deal with. I think you can tell me.

As explained in the FAQ, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, adding annotations to PDF files is currently out-of-scope for the PDF.js project.
