### ISSUE TITLE
Is it possible to add some simple annotations to a PDF?

### ISSUE THREAD

**Issue by DongWJ** [mozilla/pdf.js#8200]
I select some text and then click the right mouse button will pop up a menu, the menu which has a mark option, when click on the mark options will have a pop-up box, enter the contents and save.when the pdf file display , do not show the text of the comment.Just add a background above the text color, when mouse over, there will be floating box prompt.

**Comment by Snuffleupagus** [comment]
As explained in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, adding annotations is not supported. Closing as answered.
