### ISSUE TITLE
No PDFJS.workerSrc specified error on using pdfjs-dist package from npm 

### ISSUE THREAD

**Issue by the-fallen** [mozilla/pdf.js#8204]
![test](https://cloud.githubusercontent.com/assets/11062448/24399416/4f1b9b38-13ca-11e7-8802-4e7316c69cb2.jpg)

```
function usage(blob) {
    console.log('usage called!');
    var fileReader = new FileReader();
    fileReader.onload = function (blob) {
        require('pdfjs-dist');
        var fs = require('fs');
        PDFJS.getDocument(blob.target.result).then(function (pdfDocument) {
        console.log('Number of pages: ' + pdfDocument.numPages);
        });
    }
    fileReader.readAsArrayBuffer(blob);
}
```

implemented as shown in the example for node, but throws error for not specifying workingSrc. 
I'm using content scripts for a chrome extension which disallow document.currentscript as fcfort commented in [this](https://github.com/mozilla/pdf.js/issues/5344) issue

**Comment by the-fallen** [comment]
As fcfort commented, it works when i use

`PDFJS.workerSrc = chrome.extension.getURL("libs/pdf.worker.js");
`
before calling PDFJS.document and put my pdf.worker.js in root folder(root-directory/libs/pdf.worker.js).
But this isn't a clean solution. I hope there's a fix for this.

**Comment by Arsh-kalsi** [comment]
Go to pdf.js 

search function getWorkerSrc()

replace this lines

pdfjsFilePath = "YOUR_PATH_TO_JS_FILE/pdf.worker.js";
    if (pdfjsFilePath) {
      return pdfjsFilePath;
    }

**Comment by Snuffleupagus** [comment]
> But this isn't a clean solution. I hope there's a fix for this.

That's not a work-around, but actually the *correct* solution!
You should *always* set the `workerSrc` option before calling `getDocument`, which is even [mentioned in the docs](https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/src/display/worker_options.js#L30-L31), to ensure that the worker file will be loaded correctly.

Please keep in mind that even though we attempt to [obtain a fallback path](https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/src/display/api.js#L1304-L1311), there's no simply no guarantee that it will be successful if the `workerSrc` option wasn't explicitly set by the user.

Closing as answered.

**Comment by luistak** [comment]
You should try this:



      const pdfjs = await import('pdfjs-dist/build/pdf');
      const pdfjsWorker = await import('pdfjs-dist/build/pdf.worker.entry');

      pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;

      ...

**Comment by TroyWolf** [comment]
> > But this isn't a clean solution. I hope there's a fix for this.
> 
> That's not a work-around, but actually the _correct_ solution!
> You should _always_ set the `workerSrc` option before calling `getDocument`, which is even [mentioned in the docs](https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/src/display/worker_options.js#L30-L31), to ensure that the worker file will be loaded correctly.
> 

Regarding that documentation. I'm trying to follow it. I'm not God's gift to programming, but I'm not always the dumbest guy in the room either. I am having a difficult time making heads or tails of this paragraph in the documentation:

RE: https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website

> To use the library in your project add require('pdfjs-dist') to your file requires and build your project normally. The worker shall be built into a separate bundle: take the file "./node_modules/pdfjs-dist/build/pdf.worker.entry.js" or built a separate file that uses require('pdfjs-dist/build/pdf.worker'). PDFJS.workerSrc shall be set to point to this file. You can use the pdfjs-dist/webpack module for PDF.js autoconfiguration.

It seems to have a typo at least, but even if that is fixed, this is not very clear to me. It might reduce some frustration and wasted time answering questions if more explanation can be put around this bit.

Thanks! :coffee:

**Comment by danielmcq** [comment]
> You should try this:
> 
> ```
>   const pdfjs = await import('pdfjs-dist/build/pdf');
>   const pdfjsWorker = await import('pdfjs-dist/build/pdf.worker.entry');
> 
>   pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
> 
>   ...
> ```

This absolutely worked for me, expect I'm using native `import`.

```
import pdfjs from 'pdfjs-dist';
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
```

**Comment by luistak** [comment]
> > You should try this:
> > ```
> >   const pdfjs = await import('pdfjs-dist/build/pdf');
> >   const pdfjsWorker = await import('pdfjs-dist/build/pdf.worker.entry');
> > 
> >   pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
> > 
> >   ...
> > ```
> 
> This absolutely worked for me, except I'm using native `import`.
> 
> ```
> import pdfjs from 'pdfjs-dist';
> import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry';
> 
> pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
> ```

i have preferred import with an await to split the bundle, this lib is kinda heavy

**Comment by danielmcq** [comment]
Yeah. Either way. The concept is the same. I'm just glad I found your comment because it helped me resolve this problem rather quickly. :)

**Comment by luistak** [comment]
I added a simple create-react-app example on this PR

https://github.com/mozilla/pdf.js/pull/11220

**Comment by charlesfries** [comment]
Is it possible to add a TypeScript type definition to this package for the `pdfjs-dist/build/pdf.worker.entry` import?
