### ISSUE TITLE
Blank page Error: JPEG error: unknown marker

### ISSUE THREAD

**Issue by Zurd** [mozilla/pdf.js#8206]
Firefox open a blank PDF file which was scanned by a printer Ricoh Aficio SP C232SF. Happens everytime. However, Adobe Acrobat, Google Chrome and Edge can open the PDF file correctly.

Firefox's Browser Console reports:
```
PDF 9c8164cf8b91c459432f3db80b06aea3 [1.3 RICOH Aficio SP C232SF (095ec0) / -] (PDF.js: 1.6.315)  viewer.js:7205:13
Error: JPEG error: unknown marker ec3b  pdf.worker.js:3841:11
parse@resource://pdf.js/build/pdf.worker.js:14685:17
JpegStream_ensureBuffer@resource://pdf.js/build/pdf.worker.js:24613:11
JpegStream_getBytes@resource://pdf.js/build/pdf.worker.js:24620:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:44455:20
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:44353:28
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:47300:29
  pdf.worker.js:3842:11
Warning: Unable to decode image: Error: JPEG error: unknown marker ec3b  pdf.worker.js:3830:11
Warning: Dependent image isn't ready yet  pdf.js:273:11
```

**Link to PDF file (or attach file here):**
[170328113002.pdf](https://github.com/mozilla/pdf.js/files/876171/170328113002.pdf)

**Configuration:**
- Web browser and its version: Firefox 52.0.1 (64-bit)
- Operating system and its version: Happens in Linux, Windows 7 and Windows 10
- PDF.js version: var pdfjsVersion = '1.6.315'; var pdfjsBuild = 'a139c75';
- Is an extension: No

**Steps to reproduce the problem:**
1. Open the PDF with Firefox

**What is the expected behavior?**
Should display an image
![screenshot at 2017-03-28 11-28-51](https://cloud.githubusercontent.com/assets/2153082/24413560/ce249f4a-13a9-11e7-9dd7-633485e4de50.png)

**What went wrong?**
Display a blank page
![screenshot at 2017-03-28 11-30-54](https://cloud.githubusercontent.com/assets/2153082/24413687/338f32d2-13aa-11e7-8205-f7a83b1e6ae5.png)

**Comment by yurydelendik** [comment]
Looks okay in 1.7.395

**Comment by Zurd** [comment]
I have the latest Firefox but do not have 1.7.395.

Shouldn't Firefox also update PDF.js ?

**Comment by yurydelendik** [comment]
Once it's pass testing (couple of month) if it will appear in production version of Firefox. It's normal process. The issue does not contain any additional information to bypass normal release process and fix the issue earlier.

**Comment by Zurd** [comment]
I see. So we just wait until Firefox update PDF.js.

Thanks for the information. Closing this issue.

**Comment by yurydelendik** [comment]
@Zurd can you test your pdf at http://mozilla.github.io/pdf.js/web/viewer.html (there is an open button to do so)?

**Comment by Zurd** [comment]
14 pages of texts, diagrams, photos, tables. Seems like I see everything in Firefox.
