### ISSUE TITLE
FireFox - "offsetParent is not set -- cannot scroll  viewer.js:125:3"

### ISSUE THREAD

**Issue by k0st1x** [mozilla/pdf.js#8208]
Link to website with sample PDF file:
https://codecentral.devexpress.com/T227361/?Print=true

Configuration:
- Web browser and its version:
FireFox v.54.0a2
- Operating system and its version:
Win10 x64 [Version 10.0.14393]
- PDF.js version:
(PDF.js: 1.7.348)
- Is an extension:
No (default pdf.js viewer in the firefox)

Steps to reproduce the problem:
1. open site https://codecentral.devexpress.com/T227361/
2. press the "Print" button
direct preview of pdf file is working normally.
but if pdf file opened from the web page - there will be js error and no pfd.js viewer opened.

What is the expected behavior? (add screenshot)
The PDF.js viewer is not opened.

What went wrong? (add screenshot)
console output:
> offsetParent is not set -- cannot scroll  viewer.js:125:3
> PDF 0a60e3235e22da40aa53a4e284cde0a4 [1.4 Developer Express Inc. DXperience (tm) v16.2.3 / -] (PDF.js: 1.7.348)

**Comment by borys-kupar** [comment]
Is there any workaround for this issue?

**Comment by brendandahl** [comment]
Instead of using "display:none" on the iframe you can hide it off screen. e.g. style="position:absolute; left: -10000px; top: -10000px;

**Comment by apoorva-shah** [comment]
So here i have a code pdf_slider_block is in a bootstrap modal. I first bootstrap modal then get pdf via ajax and remove class "hide-it-off-screen", so i can see pdfs. But number enter text box not working i always went to 1st page. Please help.
```
<div id="pdf_slider_block" class="hide-it-off-screen" style="height: 400px;">
    <a id="catalogue_slider_prev" class="hidden next-prev"><i class="fa fa-chevron-left"></i></a>
    {% include 'templates/pdf/viewer.html.twig' %}
    <a id="catalogue_slider_next" class="hidden next-prev"><i class="fa fa-chevron-right"></i></a>
</div>
```

```
style.css

.hide-it-off-screen {
    position: absolute;
    left: -10000px;
    top: -10000px;
}

```

**Comment by stonstad** [comment]
Why was this closed?  I'm still seeing this behavior.  The workaround may not be applicable for scenarios which hide the iframe while transparent loading occurs.
