### ISSUE TITLE
In pdf viewer, an error occurs when zooming

### ISSUE THREAD

**Issue by ilnur-slv** [mozilla/pdf.js#8209]
Hello!

In pdf viewer, an error occurs when zooming.

Configuration:
- Web browser: Chrome, Firefox, IE, Edge
- Operating system: Win 10
- PDF.js version: 1.7.343

Steps to reproduce:
1) open the document
2) zoom in/out
3) wait a couple of minutes
4) zoom in/out

Error in console:
```
Uncaught TypeError: Cannot read property 'rotation' of undefined
    at PDFPageView_transform [as cssTransform] (VM9875 pdf.viewer.js:16517)
    at PDFPageView_update [as update] (VM9875 pdf.viewer.js:16481)
    at PDFViewer.pdfViewer_setScaleUpdatePages [as _setScaleUpdatePages] (VM14856 pdf.viewer.js:18718)
    at PDFViewer_setScale [as _setScale] (VM14856 pdf.viewer.js:18743)
    at PDFViewer.set currentScaleValue [as currentScaleValue] (VM14856 pdf.viewer.js:18517)
    at Object.pdfViewZoomIn [as zoomIn] (VM9875 pdf.viewer.js:12173)
    at webViewerWheel (VM9875 pdf.viewer.js:13277)
```
	
This happens in the cssTransform function [https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js#L281-L282](https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js#L281-L282)

this.paintedViewportMap.get (target) is 'undefined', since this.paintedViewportMap.delete(this.canvas) is called after a few minutes.

The error appeared after the pull request [https://github.com/mozilla/pdf.js/pull/7977/files](https://github.com/mozilla/pdf.js/pull/7977/files)

**Comment by Snuffleupagus** [comment]
@ilnur-slv Can you please check if the preview available in https://github.com/mozilla/pdf.js/pull/8210#issuecomment-290115602 fixes this issue?

**Comment by ilnur-slv** [comment]
@Snuffleupagus Works well!

**Comment by ilnur-slv** [comment]
@Snuffleupagus Thank you so much!

**Comment by sid-thakur** [comment]
I am experiencing the original problem mentioned at the beginning of this thread.

Configuration
* Electron React App
* OS: Windows 10
* pdfjs-dist version: 2.6.347

Steps to reproduce: zoom in/out, after some zoom in/out more, error occurs

```
TypeError: Cannot read property 'rotation' of undefined
PDFPageView.cssTransform
C:/Users/sidth/project/libs/react-pdf-highlighter/node_modules/pdfjs-dist/web/pdf_viewer.js:4721
  4718 | const div = this.div;
  4719 | target.style.width = target.parentNode.style.width = div.style.width = Math.floor(width) + "px";
  4720 | target.style.height = target.parentNode.style.height = div.style.height = Math.floor(height) + "px";
> 4721 | const relativeRotation = this.viewport.rotation - this.paintedViewportMap.get(target).rotation;
       | ^  4722 | const absRotation = Math.abs(relativeRotation);
  4723 | let scaleX = 1,
  4724 |     scaleY = 1;
View compiled
PDFPageView.update
C:/Users/sidth/project/libs/react-pdf-highlighter/node_modules/pdfjs-dist/web/pdf_viewer.js:4690
  4687 | }
  4688 | 
  4689 | if (this.zoomLayer) {
> 4690 |   this.cssTransform(this.zoomLayer.firstChild);
       | ^  4691 | }
  4692 | 
  4693 | this.reset(true, true);
:
:
```

Thanks!

**Comment by Akaban** [comment]
Hello !

Same here, if I zoom in I don't have the error but while zooming out I get it.

React 16 here

If someone knows something would be greatly appreciated !

**Comment by pizzooid** [comment]
I fixed it by passing `useOnlyCssZoom: true` to PdfViewer :-)
