### ISSUE TITLE
PDF Js edge browser problem in print

### ISSUE THREAD

**Issue by pushparaj100** [mozilla/pdf.js#8211]
Link to PDF file (or attach file here):
![pdfjsdemo_print_edge_issues](https://cloud.githubusercontent.com/assets/8383864/24461800/efde7b08-14bf-11e7-90dc-1390167b827f.jpg)

Configuration:
- Web browser and its version: windows 10 edge browser 
- Operating system and its version: windows 10
- PDF.js version: I don't know exactly i have tested your demo url https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
I have expected to print that pdfjs demo iframe content only 
What went wrong? (add screenshot)
but it print entire page refer above image
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
My demo url is http://113.193.25.20/pushparajowctest/pdfjsdemo/

is there any solution to solve this edge browser problem?

**Comment by rstorres** [comment]
Hi all,

I am experiencing exactly the same problem.
The pdfjs version that I am using is **Beta (v1.7.225)**


Do you know when this will be fixed? Do you know some workaround?

Regards

**Comment by rstorres** [comment]
Hello,

I have update my Windows 10 and now I am able to print correctly.

Honestly, I don't know if that Windows 10 update includes some update on Edge ... probably yes!

Find below my currently Edge version:
![image](https://cloud.githubusercontent.com/assets/18192556/24700850/5d5c869a-19f0-11e7-84a4-cfd7701267ef.png)

Regards

**Comment by timvandermeij** [comment]
Closing since this looks like it is an upstream Edge issue that has been fixed in the most recent version.
