### ISSUE TITLE
CA sign can't be seen in pdf.js

### ISSUE THREAD

**Issue by kenwhale** [mozilla/pdf.js#8214]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome  57.0.2987.110
- Operating system and its version: Win7
- PDF.js version: online demo
- Is an extension:

Steps to reproduce the problem:
1.  open the attached pdf file 
2.  the ca sign can't be shown on the right-bottom corner

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> open the attached pdf file

Unfortunately, this issue isn't complete as-is, since there's no PDF file attached.

> the ca sign can't be shown on the right-bottom corner

Support for signatures in PDF.js is already tracked in issue #1076, hence I'm closing this as a duplicate based on the information provided.
