### ISSUE TITLE
IE 11 Problem

### ISSUE THREAD

**Issue by kalinowcyk** [mozilla/pdf.js#8216]
Link to PDF file (or attach file here): Not important

Configuration:
- Web browser and its version: Internet Explorer 11.839.10586
- Operating system and its version: Windows 10 64bit
- PDF.js version: 
`var pdfjsVersion = '1.6.210';`
- Is an extension: I'm using PDF.JS inside other application

Steps to reproduce the problem:
1. I'm loading PDF.JS in Iframe in application. 
2. Next I'm closing this iframe. 
3. Repeating steps 1-2 multiple times (about 20). 
4. In one of next loading PDF is not loading. It's stuck on this line: 

```
return loadingTask.promise.then(
      function getDocumentCallback(pdfDocument) {
        self.load(pdfDocument, scale);
      },
      function getDocumentError(exception) {
        var message = exception && exception.message;
        var loadingErrorMessage = mozL10n.get('loading_error', null,
          'An error occurred while loading the PDF.');

        if (exception instanceof pdfjsLib.InvalidPDFException) {
          // change error message also for other builds
          loadingErrorMessage = mozL10n.get('invalid_file_error', null,
                                            'Invalid or corrupted PDF file.');
        } else if (exception instanceof pdfjsLib.MissingPDFException) {
          // special message for missing PDF's
          loadingErrorMessage = mozL10n.get('missing_file_error', null,
                                            'Missing PDF file.');
        } else if (exception instanceof pdfjsLib.UnexpectedResponseException) {
          loadingErrorMessage = mozL10n.get('unexpected_response_error', null,
                                            'Unexpected server response.');
        }

        var moreInfo = {
          message: message
        };
        self.error(loadingErrorMessage, moreInfo);

        throw new Error(loadingErrorMessage);
      }
    );
```

What is the expected behavior? (add screenshot) Load PDF. 

What went wrong? (add screenshot) PDF not loaded. Look at screenshot above. On pdfjs3 screen I uploaded shot of 
`console.log(loadingTask.promise);`

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Not possible. 
![pdfjs3](https://cloud.githubusercontent.com/assets/26790621/24500082/5eb55c16-1544-11e7-95fc-37354201e96b.png)
![pdfjs2](https://cloud.githubusercontent.com/assets/26790621/24500081/5eb4c1b6-1544-11e7-8055-1c43476b21c5.png)
![pdfjs](https://cloud.githubusercontent.com/assets/26790621/24500080/5eb46748-1544-11e7-9c35-bd5eda83b34d.png)

**Comment by timvandermeij** [comment]
You should provide a link to a working example that demonstrates the issue. It is hard to reproduce if no example is given. Without it, this issue will be closed as incomplete. Thanks.

**Comment by kalinowcyk** [comment]
I'll try to make some demo version of this bug, but I need some time.

**Comment by kalinowcyk** [comment]
Hi. When I was trying to make a demo of a bug, I found an error in my application. So, You can close this issue, it's not a bug of pdf.js. 
Thanks for inspiration ;)
