### ISSUE TITLE
Getting white blank page without any content on iPad. #8212

### ISSUE THREAD

**Issue by Pawan9977** [mozilla/pdf.js#8219]
Configuration:

Web browser and its version: latest version of chrome for ipad
Operating system and its version: IOS 9.2.1
PDF.js version: 1.6.210
Is an extension: NO

Steps to reproduce the problem:

1. Pass base64 encoded data to the pdf.js( PDFJS.getDocument() method)
2. Try to open pdf in chrome browser for ipad using PDF.js library.

What is the expected behavior? (add screenshot)
It should always render a pdf with content.

What went wrong? (add screenshot)
It shows white blank page without any content. This is a random behavior. It does not happen all times but its inconsistent behavior.

Please find the below code to render the pdf:
var PDFRenderModule = (function() {

var renderPDFWithResponseBody = function(content, containerId) {

        var myData = convertDataURIToBinary(content); //put it in a Uint8Array

	PDFJS.getDocument(myData).then(function(pdf) {

		// Get div#container and cache it for later use
		var container = document.getElementById(containerId);

		// Loop from 1 to total_number_of_pages in PDF document
		for (var i = 1; i <= pdf.numPages; i++) {

			// Get desired page
			pdf.getPage(i).then(function(page) {

				var scale = 3;
				var viewport = page.getViewport(scale);
				var div = document.createElement("div");

				// Set id attribute with page-#{pdf_page_number} format
				div.setAttribute("id", "page-" + (page.pageIndex + 1));

				// This will keep positions of child elements as per our needs
				div.setAttribute("style", "position: relative");

				div.setAttribute("style", "height: 100%");

				// Append div within div#container
				container.appendChild(div);

				if (i > 1)
					container.appendChild(document.createElement("br"));

				// Create a new Canvas element
				var canvas = document.createElement("canvas");

				canvas.setAttribute("style", "height: 100%");

				// Append Canvas within div#page-#{pdf_page_number}
				div.appendChild(canvas);

				var context = canvas.getContext('2d');
				canvas.height = viewport.height;
				canvas.width = viewport.width;

				var renderContext = {
					canvasContext: context,
					viewport: viewport
				};

				var renderTask = page.render(renderContext);

				renderTask.then(function () {

					console.log('Page rendered :: ' + containerId);
				 
				});
			});
		}
	});
};

// convert base64 data to binary data
var convertDataURIToBinary = function(dataURI) {

	var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
	var base64 = dataURI.substring(base64Index);
	var raw = window.atob(base64);
	var rawLength = raw.length;
	var array = new Uint8Array(new ArrayBuffer(rawLength));

	for (var i = 0; i < rawLength; i++) {
		array[i] = raw.charCodeAt(i);
	}

	return array;
};

return {
	renderPDFWithResponseBody: renderPDFWithResponseBody
}
});

Where containerId is the id of the div container to hold document.

I have to render multiple pdf in single page with multiple tabs. It works fine in web browsers for desktop/laptop. But getting inconsistent behavior for iPad.

**Comment by Pawan9977** [comment]
Hi, 
does anyone have faced the same issue with pdf.js

**Comment by pedropcruz** [comment]
Hello,

Anyone can solve this? I cant get any page from my PDF using pdf.js

**Comment by Snuffleupagus** [comment]
This looks like a platform/browser bug (perhaps `canvas`-related), rather than a general PDF.js one, hence this unfortunately doesn't seem like something that can be fixed *here*.
