### ISSUE TITLE
Aligning rendered pages by code

### ISSUE THREAD

**Issue by ekambarrao** [mozilla/pdf.js#8226]
Say the pdf has 2 or 3 pages and I am able to render all of them to canvas but I could not control the display format as they are coming side by side. How to control placement of the pages in code, example, one below another?

**Comment by timvandermeij** [comment]
The default viewer (https://mozilla.github.io/pdf.js/web/viewer.html) displays the pages below each other. You can control the display of the pages using regular CSS if you have the canvases. Just set them to e.g., `display: inline-block` to display them next to each other.
