### ISSUE TITLE
Convert the Firefox add-on to a WebExtension

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8227]
It looks like the current Firefox add-on will not be supported anymore in Firefox 57. Instead, only WebExtensions will be supported. We should investigate how to convert the Firefox add-on to a WebExtension.

I think the Chrome add-on manifest gives us a clue about which APIs we need. We need to check if they are already supported by Firefox, and how much we can reuse from the existing Chrome extension. Hopefully we will be able to merge the Chrome and Firefox extensions with this effort (perhaps with some preprocessor statements for browser-specific code such as telemetry for Firefox).

**Comment by Snuffleupagus** [comment]
Please note that this is already tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1271476, which mentions a number of (mostly likely still) missing features that the add-on currently depends on.

**Comment by timvandermeij** [comment]
Closing since this is now tracked in a new issue with more actionable points.
