### ISSUE TITLE
[Edge, IE] blank white stripes are shown at the top and bottom of the zoom values list

### ISSUE THREAD

**Issue by ilnur-slv** [mozilla/pdf.js#8230]
In IE and Edge browsers blank white stripes are shown at the top and bottom of the zoom values list.

Configuration:

Web browser: Edge, IE
Operating system: Win 10
PDF.js version: 1.7.343

Edge:
![aa994d4eb41d240514e8a34365b773bced5ca0f3220a06e64e pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/1205974/24605144/59a3a942-1870-11e7-89ec-9a05a3c24fc6.png)

IE:
![capture333](https://cloud.githubusercontent.com/assets/1205974/24605148/60cae500-1870-11e7-8456-86de76b12d10.PNG)

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
