### ISSUE TITLE
Letter ä not showing in pdf

### ISSUE THREAD

**Issue by pchtri** [mozilla/pdf.js#8234]
Link to PDF file (or attach file here):
[FF52_CR_ä_missing.pdf](https://github.com/mozilla/pdf.js/files/892611/FF52_CR_a_missing.pdf)

Configuration:
- Web browser and its version: FireFox 52.0.1
- Operating system and its version: Windows 7 and 10
- PDF.js version: 1.7.406
- Is an extension:

Steps to reproduce the problem:
1. Open the attached file in https://mozilla.github.io/pdf.js/web/viewer.html or in FireFox 52.0.1
2.

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/26895763/24650700/a73256a4-1933-11e7-853c-529ebf4f31c3.png)
The same pdf works fine in Acrobat Reader, Chrome and all other viewers I've tested.

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/26895763/24650791/09272272-1934-11e7-9d0f-f4d83b6e36bb.png)
The small letter ä is shown in the same color as the background (white). If you select the text and paste it to notepad ä is there, but it doesnt show in the pdf.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by THausherr** [comment]
[PDFJS-8234_reduced.pdf](https://github.com/mozilla/pdf.js/files/900112/PDFJS-8234_reduced.pdf)
Reduced version of the file. The font does not have does not have a glyph name for code 32, but it has a ToUnicode entry (ä) and a glyph (ä). Likely a bug in the subsetter of the library that produced this file.

**Comment by timvandermeij** [comment]
Fixed by #9340.
