### ISSUE TITLE
Skipped pages show up in reftests

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#8241]
I noticed a number of blank pages in http://107.21.233.14:8877/aec1bf6261c835c/reftest-analyzer.html for chrome-issue1658, turns out 1-10 are skipped pages. Not sure why they're showing up in the tests.

**Comment by Snuffleupagus** [comment]
It looks like we actually create 1x1 sized canvases when skipping pages, according to https://github.com/mozilla/pdf.js/blob/c380d2540772be2d996c6c1b932593c57a42da63/test/driver.js#L447-L462, I'm not sure why that is though.
