### ISSUE TITLE
PDF Displaying not displaying properly

### ISSUE THREAD

**Issue by aidlo** [mozilla/pdf.js#8245]
Link to PDF file (or attach file here):
[document.pdf](https://github.com/mozilla/pdf.js/files/902878/document.pdf)

Configuration:
    Web browser and its version: Firefox 52.0.2 (32-bit)
    Operating system and its version: Windows 10
    PDF.js version: Using version bundled with Firefox

Steps to reproduce the problem:
1. View Attached PDF with PDF.js in Firefox
 Similar Issue #8083 

What is the expected behavior? (add screenshot)
Adobe Reader correctly shows the image and isn't blurry. PDF.js does not. See screenshots for comparison.

![screenshot correct](https://cloud.githubusercontent.com/assets/26969366/24759503/93f39d2c-1add-11e7-9f75-e95418668e3e.gif)

What went wrong? (add screenshot)
![screenshot](https://cloud.githubusercontent.com/assets/26969366/24759417/41e79cc2-1add-11e7-92bf-290fb8064b25.gif)

The image in the PDF is an Indexed xobject. not sure if this is the issue.

**Comment by THausherr** [comment]
This is not related to #8083, that one was about patterns with giant steps. Here there's no pattern, only a very small image that is extremely blown up.

**Comment by aidlo** [comment]
This was a small image (10x10 pixel) for a quick example. It happens with bigger more complicated images also.
Have had similar problems when working with other image code where dithering was used instead of the indexed palette.

**Comment by THausherr** [comment]
Here's another. That one has inline images with 1 bit /DeviceGray.
[inline.pdf](https://github.com/mozilla/pdf.js/files/909417/inline.pdf)
The file is created by the PDFBox build tests and thus Apache licensed.

**Comment by aidlo** [comment]
Sample open as intended in Goggle Chrome.
Bug may just be in the Firefox implentation.

**Comment by THausherr** [comment]
I have it blurry on chrome when using https://mozilla.github.io/pdf.js/web/viewer.html .

**Comment by aidlo** [comment]
It is down to the imageSmoothingEnabled property being enabled by default [.](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled) 
Turning off smoothing for the canvas and everything looks correct.
`mozImageSmoothingEnabled = false;
 webkitImageSmoothingEnabled = false;
 msImageSmoothingEnabled = false;
imageSmoothingEnabled = false;`

**Comment by aidlo** [comment]
Create a JSFiddle to demostrate [Demo](https://jsfiddle.net/y4zd4955/)

**Comment by SamyCookie** [comment]
Maybe it is related to #3331 (blurry lines), I have deduced the same conclusion on that bug.

**Comment by aidlo** [comment]
How can this I get this fixed?
