### ISSUE TITLE
Error: Cannot resolve callback 1 when opening multiple pdfs

### ISSUE THREAD

**Issue by gdaolewe** [mozilla/pdf.js#8246]
Link to PDF file (or attach file here):

[pdf-sample.pdf](https://github.com/mozilla/pdf.js/files/903097/pdf-sample.pdf)
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/903096/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Chrome 56.0.2924.87
- Operating system and its version: OSX 10.11.6
- PDF.js version: pdfjs-dist 1.7.414
- Is an extension: No

Using following React component:

```jsx
import React, { Component } from 'react';
import PDFJS from 'pdfjs-dist/webpack';

class App extends Component {
  constructor() {
    super();
    this.state = {pdfs: []};
    this.handleInputChange = this.handleInputChange.bind(this);
  }

  handleInputChange(event) {
    const file = event.target.files[0];
    const reader = new FileReader();
    const self = this;
    reader.onload = function() {
      const typedArray = new Uint8Array(this.result);
      PDFJS.getDocument(typedArray).then(pdf => {
        self.setState({pdfs: self.state.pdfs.concat(pdf)});
      });
    };
    reader.readAsArrayBuffer(file);
  }

  render() {
    return (
      <div>
        <input type="file" onChange={this.handleInputChange}/>
        <ul>
          {this.state.pdfs.map((pdf, i) => <li key={i}>{pdf.numPages}</li>)}
        </ul>
      </div>
    );
  }
}
```

Steps to reproduce the problem:
1. Upload first attached PDF
2. Upload second attached PDF

What is the expected behavior? Both PDFs' page counts are printed:

![image](https://cloud.githubusercontent.com/assets/2925407/24762453/7262401c-1abc-11e7-95fc-e0c020b85afb.png)

What went wrong? The expected behavior occurs, but PDF.js throws the following error when a second PDF is opened, and will throw the error again whenever a new PDF is opened:

```
Error: Cannot resolve callback 1
pdf.js:340     at error (http://localhost:3000/static/js/bundle.js:33026:18)
    at MessageHandler.messageHandlerComObjOnMessage (http://localhost:3000/static/js/bundle.js:33732:10)
```

(specifically, from line https://github.com/mozilla/pdf.js/blob/59392fd5442d819879dc7ec0a0a8ce9a2fbd2f71/src/shared/util.js#L1291)

This appears unrelated to the contents of the PDFs, this occurs with any sequence of multiple PDFs I've tried other than opening the same file twice.

If I call `pdf.destroy()` on the already-open PDF before opening another, this does not occur.

**Comment by gdaolewe** [comment]
If I modify the example code above to allow picking multiple PDFs at once:

```jsx
import React, { Component } from 'react';
import PDFJS from 'pdfjs-dist/webpack';

class App extends Component {
  constructor() {
    super();
    this.state = {pdfs: []};
    this.handleInputChange = this.handleInputChange.bind(this);
  }

  handleInputChange(event) {
    const self = this;
    for (const file of event.target.files) {
      const reader = new FileReader();
      reader.onload = function() {
        const typedArray = new Uint8Array(this.result);
        PDFJS.getDocument(typedArray).then(pdf => {
          self.setState({pdfs: self.state.pdfs.concat(pdf)});
        });
      };
      reader.readAsArrayBuffer(file);
    }
  }

  render() {
    return (
      <div>
        <input type="file" multiple onChange={this.handleInputChange}/>
        <ul>
          {this.state.pdfs.map((pdf, i) => <li key={i}>{pdf.numPages}</li>)}
        </ul>
      </div>
    );
  }
}

export default App;
```
then when I do pick multiple PDFs at once, in addition to the error above, I also receive the error:

```
Uncaught TypeError: Cannot read property 'disableCreateObjectURL' of null
    at setupDoc (pdf.worker.js:11104)
    at wphReady (pdf.worker.js:11264)
    at MessageHandler.messageHandlerComObjOnMessage (pdf.worker.js:1076)
```

and only the first 2 PDFs picked will actually be parsed and have their page counts rendered.

This does not occur if I import `pdfjs-dist` instead of `pdfjs-dist/webpack` and use the fake worker.

**Comment by rvinay88** [comment]
I ran into the same issue. I was implementing multiple templates (through a series of GET requests) and replacing the pdf on the page (also a react application). Calling pdf instance's destroy method helped resolve the problem. Thanks!

**Comment by mattnetto** [comment]
+1

**Comment by yurydelendik** [comment]
@rvinay88 @mattnetto can you publish complete project (instead of snippets of code)?

**Comment by gdaolewe** [comment]
@yurydelendik I published a complete minimal project here: https://github.com/gdaolewe/webpack-pdfjs-repro
