### ISSUE TITLE
UNC Path

### ISSUE THREAD

**Issue by gshaver** [mozilla/pdf.js#8252]
We store the PDFs for our application on a different file server from the web server.  Is there a way to show PDFs from a UNC path on a different server?  The only way I've seen in the examples is to pass it with a URL.  We don't want to expose the PDFs to the web through IIS and everything I've tried has been unsuccessful.  

For example I want to pass a path like \\server2\folder\file.pdf to the viewer.html page.

**Comment by timvandermeij** [comment]
Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr for more information on this topic.
