### ISSUE TITLE
v1.6.380+ Regression: Glyphs’ migration to PUA can fail, get missed when rendered

### ISSUE THREAD

**Issue by evadne** [mozilla/pdf.js#8255]
Link to PDF file (or attach file here): ~confidential but can send over secure channel~ reduced test case available, see comment

Configuration: Any
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: Any version more recent than 1.6.380
- Is an extension: No

Explanation:

Starting from build 1.6.380, presumably with commit 8d036faf403fb71fd106f7f605251268feb6a658, symbolic fonts are having their glyphs moved entirely to the Private Use Area in order to work around a canvas rendition problem.

I have seen this cause an issue with one of my documents where Hangul glyphs using Arial Unicode MS do not render properly in PDF.js on or after said release (1.6.380). I have traced the problem through the codebase and think I know what the problem is.

The problem is that there are three Private Use Areas…

1. Basic Multilingual Plane, U+E000 - U+F8FF, 6400 glyphs
2. Plane 15, U+F0000 - U+FFFFD, 65534 glyphs
3. Plane 16, U+100000 - U+10FFFD, 65534 glyphs

…and PDF.js only moves glyphs into the first area which supposedly gives it capacity for 6400 glyphs, but I have a document that triggers a problem where certain glyphs do not render, because it is using a font marked as Symbolic and has more than that amount of glyphs, with some of them already in the U+E000 - U+F8FF range. In practice, this causes certain documents to render without all glyphs being seen and is reproducible both in Firefox Developer Edition and a custom viewer I built by pulling components from `pdfjs-dist`.

I have currently worked around this issue in my own system by setting that font as not symbolic, and left the following comments for your reflection —

> This is probably because that the Private Use Area in question, while explicitly left undefined by the Unicode Consortium, has already been filled by vendors like Apple (which uses the last glyph 0xF8FF as an Apple icon) and Microsoft (in various Core Fonts, even Arial Unicode MS, whose version 1.01 contains 43 characters in the Private Use Area).
> Therefore at this time the most immediate solution is to work around this issue by ensuring that if Arial Unicode MS is marked as Symbolic by whatever application producing a PDF, it is unmarked as Symbolic here within $Service.

It would be nice if we can either patch `PRIVATE_USE_OFFSET_START` and `PRIVATE_USE_OFFSET_END` (in `src/core/fonts.js`) or make PDF.js use all three Private Use Areas and ensure that it does not touch any glyph already in these areas.

I may be able to contribute that patch given enough guidance.

**Comment by brendandahl** [comment]
To use all three we'd need to modify the code that [moves the glyphs to the private use area](https://github.com/mozilla/pdf.js/blob/c5199d0814720a767b5cc4b83053ddc134ff3b13/src/core/fonts.js#L862). It shouldn't be too hard to add support for all three. Alternatively, we could always use Plane 15. I seem to remember we had an issue using Plane 15 and 16, but I can remember what.

**Comment by brendandahl** [comment]
Also, do you have a PDF you can share that triggers this issue?

**Comment by evadne** [comment]
@brendandahl I can send the problematic page to you indeed. I have your email address embedded in the commit?

**Comment by evadne** [comment]
I managed to make a very small page which shows the problem. Please see attachment.
[pdf-missing-embedded-glyphs.pdf](https://github.com/mozilla/pdf.js/files/907165/pdf-missing-embedded-glyphs.pdf)

**Comment by Snuffleupagus** [comment]
@evadne Thank you for the test-case!
However, since you remarked above that the PDF file contains sensitive information, are you aware that the file you attached still contains a lot more information than what's easily visible?
If one removes the `/Cropbox` entry from your PDF file, it's actually possible to recover the *entire* page since the information is still present in the file even though it's not *visible* by default.

If this is a problem, privacy wise, I'd suggest that you remove the like to the file!
And in case you want/need to remove your file, I'm attaching a reduced PDF file which contains *only* the text visible in your file and *nothing* more: [issue8255_reduced.pdf](https://github.com/mozilla/pdf.js/files/907372/issue8255_reduced.pdf).

**Comment by evadne** [comment]
@Snuffleupagus thanks for the trim 😃

**Comment by evadne** [comment]
I have a Pull Request up ☝️ but not sure if that change makes sense?
