### ISSUE TITLE
Images not showing in PDF

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8264]
Link to PDF file (or attach file here):

[FVD1.pdf](https://github.com/mozilla/pdf.js/files/910730/FVD1.pdf)

On all browsers that we've tried (e.g. Chrome for Mac latest) the three images towards the top right of the first page do not appear.

I have tried with the standard viewer:
https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)

![screen shot 2017-04-10 at 17 21 41](https://cloud.githubusercontent.com/assets/786238/24871731/8812838c-1e12-11e7-9dc2-69273a41a629.png)

What went wrong? (add screenshot)

![screen shot 2017-04-10 at 17 21 30](https://cloud.githubusercontent.com/assets/786238/24871722/806f10a0-1e12-11e7-92e1-8699ba4115a8.png)

**Comment by Snuffleupagus** [comment]
From a cursory look, this seems to be another issue that would be fixed by PR #6606.

**Comment by thoussem** [comment]
I have the same problem
