### ISSUE TITLE
PDF Viewer will not allow Print option on Macbook Air

### ISSUE THREAD

**Issue by laurenday5** [mozilla/pdf.js#8268]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by brendandahl** [comment]
We need more information, please fill out the issue template. Closing for now.
