### ISSUE TITLE
cannot print pdf with right size

### ISSUE THREAD

**Issue by gggllm** [mozilla/pdf.js#8274]
Link to PDF file (or attach file here):
[document.pdf](https://github.com/mozilla/pdf.js/files/916015/document.pdf)
Configuration:

- Web browser and its version:
FF52.0.2
- Operating system and its version:win7 X64
- PDF.js version: browser provided
- Is an extension: no

Steps to reproduce the problem:
1. open it with ff
2.print it to a5

What is the expected behavior? (add screenshot)
print it correctly
What went wrong? (add screenshot)
During the first few times of trying it was printed exactly 100% bigger than the pdf file and can only print 1/4 of its left up part of the pdf file.
After a while the size just changed to about 5% bigger than the original pdf file. I don't know what happend here.
The test was conducted both on a virtual pdf printer and a real printer.
Change the settings of the virtual pdf printer can change the size of printing results however ,this didn't work on the real printer. and no matter what I do , the printing results on the real printer cannot be controlled and is sometimes 100% bigger and now

 is 5% bigger with content loss

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
I cannot reproduce this issue, using Firefox Nightly 89 (which includes PDF.js `2.9.44`).
Given the recent round of printing patches, this issue should now have been fixed.
