### ISSUE TITLE
What does pdf.worker.js do?

### ISSUE THREAD

**Issue by hipkiss91** [mozilla/pdf.js#8279]
How is it different from pdf.js?
Can I get rid of pdf.js and just use the worker in my package?

**Comment by yurydelendik** [comment]
> How is it different from pdf.js?

See http://mozilla.github.io/pdf.js/getting_started/ :

│   ├── pdf.js                             - display layer
│   └── pdf.worker.js                      - core layer

>Can I get rid of pdf.js and just use the worker in my package?

It depends on what you are trying to do. You may just start using files/modules from src/core folder.

Closing as answered.
