### ISSUE TITLE
'Invalid XRef stream' only on PDF via XHR

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [mozilla/pdf.js#8282]
Hello,

My application is under Angular2/webpack. My final objective is to use ng2-pdf-viewer but, for now, I tried something more simple.

I try to open this PDF https://files.zenhub.io/5504f669a564ab7a3147b4d1 found in an other issue on this github which seems to be correct.

When I try to open it directly like this:
```
PDFJS.getDocument('/assets/pdf-test.pdf').then(function (pdfDocument) {
	console.log('Number of pages: ' + pdfDocument.numPages);
	debugger;
});
```

Everything is OK, no warning

But When I try to open with data getted from XHR request (which is the final objective) like this:

```
jQuery.ajax("http://localhost:3000/assets/pdf-test.pdf").success((pdf) => {
    PDFJS.getDocument({data: pdf}).then(function (pdfDocument) {
 	console.log('Number of pages: ' + pdfDocument.numPages);
 	debugger;
    });
});
```

I get:

> Error: Invalid XRef stream
> pdf.combined.js:340     at error (http://localhost:3000/main.bundle.js:89643:17)
>     at Object.XRef_readXRef [as readXRef] (http://localhost:3000/main.bundle.js:113108:15)
> ...
> pdf.combined.js:331 Warning: Indexing all PDF objects
> visualisation.document.component.ts:126 Number of pages: 3

I did not found any related answer so... have you got some input to help me?

Regards,

**Comment by yurydelendik** [comment]
jQuery.ajax shall return arrayBuffer and not a string. Closing as won't fix due to https://bugs.jquery.com/ticket/11461. Use XHR or fetch() instead.
