### ISSUE TITLE
No More Access To DEFAULT_URL

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8301]
DEFAULT_URL is now not a global variable. I believe since 1.7 inside the viewer.js it is now placed within a function() { }() so it becomes a local variable.

I used to just override this variable from a different Javascript and PDF.JS will load the document based on that variable.

What is the correct way to override the default url variable from a different javascript file instead of in viewer.js?

**Comment by Snuffleupagus** [comment]
Does https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file answer your question?

**Comment by chitgoks** [comment]
hi snuffle. no.

i dont like the query string alternative. but well, if there is no other way now, then no choice. 

but if it is possible, i would prefer overriding the default_url variable.

**Comment by chitgoks** [comment]
looks like there is no other way to do this now except the query string option

**Comment by timvandermeij** [comment]
I think the query string option is the preferred way. If you want to do it via JavaScript, you should still be able to override https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L19 (as far as I can tell it's still a global variable, but keep in mind that that may change later on, hence the recommendation to use the query string).

**Comment by chitgoks** [comment]
hi @timvandermeij based on that code yes it may be a global variable but the one i got version 1.8 is not.

ill follow your suggestion

**Comment by prohtex** [comment]
I need to be able to define the default url via a php script. My script is based on viewer.html, but it gets a filename from a database with an ID, and defines that in the header:

`echo "var DEFAULT_URL = '".$file."'";

This doesn't seem to be working for me in 2.0 - how would I go about defining the default url now? Exposing the location of the pdf file in the URL is simply not an option for me.
