### ISSUE TITLE
PDF is missing parts in IE 11

### ISSUE THREAD

**Issue by JCalabretta-MaxetaTech** [mozilla/pdf.js#8304]
When viewing this pdf using helloworld.html ([here](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html)) the heading in the top left corner and the lines are missing. It also doesn't display correctly when using my own application.

This only happens in IE. In Chrome and Firefox it works fine.

Original
[MainLibraryFloorplan.pdf](https://github.com/mozilla/pdf.js/files/926075/MainLibraryFloorplan.pdf)

Screenshot from Chrome
![chromescreenshot](https://cloud.githubusercontent.com/assets/22794988/25096276/8c38cde4-236d-11e7-92a3-43f510993a82.PNG)

Screenshot from IE 11
![screenshot](https://cloud.githubusercontent.com/assets/22794988/25095957/f88f81f6-236b-11e7-9793-de9dbea7dd8f.PNG)

I was wondering if someone could confirm that this is a pdf.js issue.
I also tried including compatibility.js but that did not fix the issue.

Thanks!

**Comment by evadne** [comment]
A wild guess, but I wonder if you have some non-RGB stuff that IE does not like, essentially making this a colour management problem. According to Illustrator the bits that are not showing are greyscale bitmaps.

<img width="638" alt="screen shot 2017-04-30 at 23 35 11" src="https://cloud.githubusercontent.com/assets/104086/25568570/c11320e2-2dfd-11e7-9e96-13437234df2c.png">

According to some other tooling I can see that images are specified with an `Intent` of `RelativeColorimetric` and that could also be problematic, I have had a case where Firefox itself refuses to draw a particular RGB image that was marked as `Perceptual`; I’ve had to work around that problem by essentially rewriting the relevant stream.

<img width="290" alt="screen shot 2017-04-30 at 23 38 51" src="https://cloud.githubusercontent.com/assets/104086/25568604/4c87f1fc-2dfe-11e7-942e-b3b63daafc70.png">

If you have access to Acrobat try treating the file using Preflight and converting everything to sRGB with no embedded profile. My suspicion is that it will cure your problem at hand.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
