### ISSUE TITLE
What should be the value for `workerSrc`?

### ISSUE THREAD

**Issue by yinso** [mozilla/pdf.js#8305]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 57.0.2987.133
- Operating system and its version: OSX 10.11.6
- PDF.js version: 1.7.365
- Is an extension: bundled via webpack 2.2.1

I tried to follow [the documentation for webpack](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#with-webpack) but it's not working (keep getting setting up fake worker), probably due to me not understanding what exactly should go into `workerSrc`.

Is `workerSrc`:

* a URL that'll get resolved by the browser? e.g. `PDFJS.workerSrc = '/pdf.worker.js';`
* a Node require spec that'll get resolved and bundled into the same file via webpack & node?
   e.g. `PDFJS.workerSrc = 'pdfjs-dist/build/pdf.worker.js';`
* a relative path that'll get resolved and bundled into the same file via webpack & node?
  e.g. `PDFJS.workerSrc = '../../node_modules/pdfjs-dist/build/pdf.worker.js';`
* something else?

Thanks for any pointers.

**Comment by evadne** [comment]
@yinso should be something the browser can hit. You may not want to use a relative path since it may break if anything else in your stack makes asset digests. It is best if you render that from your web framework.

**Comment by timvandermeij** [comment]
Moreover, you can refer to the Webpack example at https://github.com/mozilla/pdf.js/tree/master/examples/webpack. Closing as answered.

**Comment by yinso** [comment]
Thanks guys for the help - appreciated.

**Comment by luistak** [comment]
Try this:



      const pdfjs = await import('pdfjs-dist/build/pdf');
      const pdfjsWorker = await import('pdfjs-dist/build/pdf.worker.entry');

      pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;

      ...

**Comment by llamamoray** [comment]
I think @luistak solution should be added to the documentation. It's the cleanest way to load the worker in using webpack/create-react-app

**Comment by Mageenz** [comment]
It's the cleanest way to load the worker in using webpack/create-react-app

**Comment by gremo** [comment]
@luistak solution is good but still getting the error in console: **Warning: Setting up fake worker.**

Any help?

**Comment by luistak** [comment]
> @luistak solution is good but still getting the error in console: **Warning: Setting up fake worker.**
> 
> Any help?

This was reported [here](https://github.com/mozilla/pdf.js/issues/11729) and I don't really know much about pdf.js to fix 😞  
 I'm sorry

**Comment by Nataliasem** [comment]
I use Pdfjs v2.8.335 with legacy supporting in this way:

import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf'
import PDFJSWorker from 'pdfjs-dist/legacy/build/pdf.worker.entry'

pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJSWorker

**Comment by matheus-brisance** [comment]
I use Pdfjs v2.9.359 with legacy supporting in this way:

`
import * as PDFJS from 'pdfjs-dist/legacy/build/pdf';
import PDFJSWorker from 'worker-loader?esModule=false&filename=[name].[contenthash].js!pdfjs-dist/legacy/build/pdf.worker';

PDFJS.GlobalWorkerOptions.workerPort = new PDFJSWorker();

export default PDFJS;
`

**Comment by iamrmin** [comment]
has anyone faced error `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` when using 

```
import { pdfjs } from 'react-pdf'
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker
```

`react-scripts build` and `react-scripts start` just crashes when error mentioned above. most importantly it only occur when i enable source map.

**Comment by Johnnybar** [comment]
Having the same issue as @iamrmin. The solution looks straightforward but crash follows...

**Comment by iamrmin** [comment]
@Johnnybar Yes, I fixed it the same way 🤝

**Comment by Johnnybar** [comment]
Hi @iamrmin and whoever runs into this problem in the future. I managed to solve this issue by creating an .env file in the project's root where I deactivated building sourcemaps.
Here are links to 3 possible solutions:
https://stackoverflow.com/a/63745434
https://github.com/wojtekmaj/react-pdf/issues/97#issuecomment-940069915

**Comment by rajkp1997** [comment]
> pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker
has anyone faced error FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory when using

import { pdfjs } from 'react-pdf'
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker
react-scripts build and react-scripts start just crashes when error mentioned above. most importantly it only occur when i enable source map.

**Comment by lamnouar** [comment]
You have the issue because you already have an instance for the pdfWorker created, I hade the same issue and I fixed it by adding this globalThis.pdfjsWorker = null; just before setting the workerSrc
Like this you will be able to create a new instance with your local file

**Comment by ar2pi** [comment]
If anyone reaches this point and uses this library in Node.js with Typescript, Serverless Framework and `serverless-plugin-optimize` here's what worked for me.

In your `serverless.yml` file:
```yaml
provider:
  optimize:
    external:
      - pdfjs-dist/legacy/build/pdf.worker.js
```

In your code:
```ts
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf';

pdfjs.GlobalWorkerOptions.workerSrc = 'pdfjs-dist/legacy/build/pdf.worker';
```

**Comment by zhaoxu-lingoace** [comment]
Adding this to the entry file is automatically set `workerSrc`

```
import 'pdfjs-dist/webpack';
```

**Comment by isacvale** [comment]
We're not allowed to rely on cloudfare's cdn, so we needed another approach.
I got this from [react-pdf's README](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#legacy-pdfjs-worker) , and it worked ok. 

```
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/legacy/build/pdf.worker.min.js',
  import.meta.url,
).toString();
```

**Comment by chtmiley** [comment]
> Adding this to the entry file is automatically set `workerSrc`
> 
> ```
> import 'pdfjs-dist/webpack';
> ```
> 
> > [Official documentation](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#webpack)

This worked for me using webpack. I did it following the instructions on worker loading in this example: https://github.com/mozilla/pdf.js/tree/master/examples/webpack

***Worker loading

If you are getting the Setting up fake worker warning, make sure you are importing **pdfjs-dist/webpack.mjs** which is the zero-configuration method for Webpack users. Installing worker-loader is no longer necessary.

    import * as pdfjsLib from 'pdfjs-dist/webpack.mjs';

**Comment by ahmedelhaw** [comment]
> ```
> import 'pdfjs-dist/webpack';
> ```
> 
> 
>     
>   
> 
> >

fantastic

**Comment by jigmeloday** [comment]
> //cdnjs.cloudflare.com/ajax/libs/pdf.js/{installed_npm_version}/pdf.worker.js

pdf.mjs:12095 
 GET https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.js net::ERR_ABORTED 404 (Not Found)

app-index.js:33 Warning: Error: Setting up fake worker failed: "Failed to fetch dynamically imported module: http://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.6.82/pdf.worker.js".
﻿

**Comment by jigmeloday** [comment]
> We're not allowed to rely on cloudfare's cdn, so we needed another approach. I got this from [react-pdf's README](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#legacy-pdfjs-worker) , and it worked ok.
> 
> ```
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>   'pdfjs-dist/legacy/build/pdf.worker.min.js',
>   import.meta.url,
> ).toString();
> ```

getting 403

**Comment by techie014** [comment]
> > We're not allowed to rely on cloudfare's cdn, so we needed another approach. I got this from [react-pdf's README](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#legacy-pdfjs-worker) , and it worked ok.
> > ```
> > pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> >   'pdfjs-dist/legacy/build/pdf.worker.min.js',
> >   import.meta.url,
> > ).toString();
> > ```
> 
> getting 403

@jigmeloday  Could you please try this?
```
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  "pdfjs-dist/build/pdf.worker.min.mjs",
  import.meta.url
).toString();
```

**Comment by OkanShr** [comment]
I haven't checked why yet but changing react-pdf version to: `"react-pdf": "^8.0.2"` fixed the 404 error that i previously had.
And im just using `pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;`
Works fine

**Comment by anton-x-t** [comment]
This worked for me (React/Vite):
```
import { pdfjs } from "react-pdf";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?worker";
pdfjs.GlobalWorkerOptions.workerPort = new pdfWorker();
```

Sources:
What should be the value for workerSrc? 8305,
thank you Leung Yau Ming,
https://github.com/mozilla/pdf.js/issues/8305#issuecomment-1674973556

Importing Script as a Worker, vite.dev,
thank you helloworld3200 et al,  
https://vite.dev/guide/assets.html#importing-script-as-a-worker

**Comment by edulapakberkah** [comment]
> > > We're not allowed to rely on cloudfare's cdn, so we needed another approach. I got this from [react-pdf's README](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#legacy-pdfjs-worker) , and it worked ok.
> > > ```
> > > pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> > >   'pdfjs-dist/legacy/build/pdf.worker.min.js',
> > >   import.meta.url,
> > > ).toString();
> > > ```
> > 
> > 
> > getting 403
> 
> [@jigmeloday](https://github.com/jigmeloday) Could you please try this?
> 
> ```
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>   "pdfjs-dist/build/pdf.worker.min.mjs",
>   import.meta.url
> ).toString();
> ```

this is the solution since all file name extension .js has been changed to .mjs

**Comment by eternal-bug** [comment]
Now version is 5.4.449. According to [isacvale](https://github.com/isacvale)'s answer. `workerSrc` can set as:
```html
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/legacy/build/pdf.worker.min.mjs',
  import.meta.url,
).toString();
```
