### ISSUE TITLE
the problem about loading PDF file

### ISSUE THREAD

**Issue by FancyKong** [mozilla/pdf.js#8314]
I know that we can use pdf.js to show pdf file in browser.

But I found that the browser will download the whole pdf file before showing the pdf when I use pdf.js.

I think it is not good.

If the pdf file is too big, users will have to download the whole pdf file in order to view the pdf.

So I want to know is it any solution to solve this problem?

It is possible that users view the pdf without download the whole pdf file?

**Comment by yurydelendik** [comment]
> It is possible that users view the pdf without download the whole pdf file?

If a server properly configured to support HTTP range requests and PDF is valid, PDF.js will download PDF by portions. Closing as answered.

**Comment by rajegannathan** [comment]
Is there anyway to do this without using range requests?  What exactly does disableStream option do and how to use that to view huge pdf files?

**Comment by yurydelendik** [comment]
> Is there anyway to do this without using range requests?

Most of PDFs contain important data at the end of the file. Last I checked, it's not possible to get data from random position of HTTP resource with range requests. Majority servers on the web support that, so it shall not be a problem.

**Comment by yurydelendik** [comment]
> What exactly does disableStream option do and how to use that to view huge pdf files?

If XHR supports reading chunks of bytes, PDF.js will use this capability to allow faster rendering of e.g. linearized PDFs, `disableStream` will disable this functionality.

**Comment by rajegannathan** [comment]
Thank you.  Just to clarify, I can have a server that doesn't support range requests but supports byte streaming and pdfjs will automatically start showing the document without loading it completely if my client supports reading chunks of bytes?
