### ISSUE TITLE
How to disable loading icon for pdf?

### ISSUE THREAD

**Issue by ppimple** [mozilla/pdf.js#8316]
I wanted to add my own loading icon/bars for pdf loading, By default pdfjs providing us loading icon(spinner), Instead of default loading icon i wanted to show my new loading icon/bars only
![loading](https://cloud.githubusercontent.com/assets/27769305/25182564/a0ae4aee-2532-11e7-976f-fb128e94d0ba.png)

**Comment by yurydelendik** [comment]
The issue looks unrelated to pdf.js. Closing as invalid.
