### ISSUE TITLE
Images missing in specific version of Safari

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8317]
Here is the PDF: 
[AXALIGHT-Cloud-Drive-banner.pdf](https://github.com/mozilla/pdf.js/files/935338/AXALIGHT-Cloud-Drive-banner.pdf)

I have been trying using the latest pdf.js viewer here:
https://mozilla.github.io/pdf.js/web/viewer.html

Everything looks fine in most browsers, e.g. Chrome, and in some versions of Safari.
But in one version of Safari there are some images missing as follows:

![missing image](https://cloud.githubusercontent.com/assets/786238/25186624/9e5a8b32-2518-11e7-852b-bf524ba03d5e.png)

The correct appearance is:

![correct display](https://cloud.githubusercontent.com/assets/786238/25186633/a8ba1cb4-2518-11e7-8b07-c4abe9cc26b2.png)

The OS and browser details for the BROKEN display are:
Safari Version: 10.1 (12603.1.30.0.34)
System Version:	macOS 10.12.4 (16E195)
Kernel Version:	Darwin 16.5.0

The OS and browser details for the CORRECT display are:
Safari Version: 10.1 (10603.1.30.0.34)
System Version:	OS X 10.10.5 (14F2315)
Kernel Version:	Darwin 14.5.0

Thank you!

**Comment by danlester** [comment]
Hello - just wondered if this is a duplicate of another ticket, or if you are having issues reproducing? It seemed to be specific to a particular Safari version, and I may be able to get any tests run in that particular environment if needed.

Thanks,

Dan

**Comment by Snuffleupagus** [comment]
> The OS and browser details for the BROKEN display are:
> Safari Version: 10.1 (12603.1.30.0.34)
> System Version: macOS 10.12.4 (16E195)
> Kernel Version: Darwin 16.5.0
> 
> The OS and browser details for the CORRECT display are:
> Safari Version: 10.1 (10603.1.30.0.34)
> System Version: OS X 10.10.5 (14F2315)
> Kernel Version: Darwin 14.5.0

Given that this points quite strongly to a bug in a *specific* browser version, it seems unlikely that this is something that can/should be fixed in the PDF.js library; closing as WONTFIX?
