### ISSUE TITLE
English and Arabic words on one PDF

### ISSUE THREAD

**Issue by denislagoda** [mozilla/pdf.js#8318]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 57.0.2987.133
- Operating system and its version: Windows 7
- PDF.js version: 1.8.233
- Is an extension: mozilla/pdfjs-dist

Steps to reproduce the problem:
1.  have a correct PDF with both English and Arabic words generated from HTML with Direction=RTL
2. open in PDF.JS using canvas

What is the expected behavior? (add screenshot) http://image.prntscr.com/image/abd035980a694418b848be2ce2028efa.png
this is a screenshot of PDF in common viewer

What went wrong? (add screenshot)
http://image.prntscr.com/image/bae1072bfba14f21a8c514c41b92de12.png
this is a screenshot of PDF at page using PDFJS
English text is distorted

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Link to PDF file (or attach file here):
https://www.dropbox.com/s/6upv4t1n50913s6/test_application_19042017184451673.pdf?dl=0

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here):

Please provide the PDF file here, since it's impossible to help otherwise.

**Comment by denislagoda** [comment]
Link to PDF file (or attach file here):
https://www.dropbox.com/s/6upv4t1n50913s6/test_application_19042017184451673.pdf?dl=0

**Comment by Snuffleupagus** [comment]
Even though the rendering in PDF.js isn't as smooth as in e.g. Adobe Reader, I cannot reproduce any real errors, compare the screen-shots from Adobe Reader and PDF.js below (taken on Windows 7).

Hence I'm not convinced that it's a font conversion issue, since it seems more likely to be an issue related to font rendering quality on `canvas` on some platforms (e.g. Windows).

---

![comparison](https://cloud.githubusercontent.com/assets/2692120/25203300/003e3a0c-2559-11e7-9107-2d399c67ca32.png)

**Comment by timvandermeij** [comment]
@denislagoda Are you using the latest graphics drivers? Issues like these have come up before and usually upgrading the graphics drivers fixes a lot of issues.

**Comment by denislagoda** [comment]
timvandermeij>> This happens on all computers in our team: Windows 7 , 8. 10, MAC (OS X El Capitan). So I would not suspect drivers.
El Capitan screenshot (not the same file but the same report from the same aplication):
https://www.dropbox.com/s/o158k97251j9h9y/%5E4841A458E6EB3F2BF5FF5B316BBB57AF0099E6706FE07F5139%5Epimgpsh_fullsize_distr.jpg?dl=0

**Comment by denislagoda** [comment]
This is simplified code of our Angular directive that produces this issue
`.directive('pdfPreviewerMono', [

    '$window',
    'securityService',

    function ($window, securityService) {

        return {
            restrict: 'E',
            scope: {
                pdfList: "=" //list of pdf files
            },
            templateUrl: '../common/components/pdfPreviewerMono/pdfPreviewerMono.tpl.html',
            link: function (scope, element, attrs) {

                var PDFJS = $window.PDFJS;
                PDFJS.disableWorker = true;
                var pdfRenderTask;

                var canvasPdfPreviewer = element.find('.pdf-previewer')[0];
                var canvasContext = canvasPdfPreviewer.getContext('2d');

                var tokenData = securityService.getTokenData();
                var config = {};

                if (tokenData) {
                    config.httpHeaders = {};
                    config.httpHeaders.authorization = tokenData.token_type + ' ' + tokenData.access_token;
                }

                //loading pdf
                scope.getPdfDocumentMono = function (pdfObject) {
                    config.url = pdfObject.pdfUrl;
                    var pdfLoaderTask = PDFJS.getDocument(config, null, null);
                    pdfLoaderTask
                        .then(function (pdfDoc) {
                                    scope.$apply(function () {
                                        pdfObject.pdfDocument = pdfDoc;
                                        scope.curentDocument = pdfObject.pdfDocument;
                                        scope.renderPage();
                                    });
                            }
                        );
                };

                scope.renderPage = function () {
                        scope.curentDocument.getPage(1)
                            .then(function (page) {
                                    var viewport = page.getViewport(1.5);
                                    scope.setCanvasDimensions(viewport.width, viewport.height);
                                    var renderContext = {
                                        canvasContext: canvasContext,
                                        viewport: viewport
                                    };
                                    pdfRenderTask = page.render(renderContext);
                            });
                };

                scope.setCanvasDimensions = function (w, h) {
                    canvasPdfPreviewer.width = w;
                    canvasPdfPreviewer.height =h;
                    canvasPdfPreviewer.style.width = Math.floor(w) + 'px';
                    canvasPdfPreviewer.style.height = Math.floor(h) + 'px';
                    canvasContext.setTransform(1, 0, 0, 1, 0, 0);
                };

                scope.getPdfDocumentMono(scope.pdfList[0]);

            }
        };
    }
]);`

**Comment by denislagoda** [comment]
Issue is resolved:

**Comment by mryassera** [comment]
> 
> 
> Issue is resolved:
> Because the whole page was under direction=rtl.
> Just changed a container with canvas to direction=ltr

Is worked for me
Thank you for save my time
