### ISSUE TITLE
Problems accessing the file path

### ISSUE THREAD

**Issue by kevinavira** [mozilla/pdf.js#8319]
Hello yurydelendik I have a problem I am trying to access a pdf file in the glassfish server I try to get the route but do not bring it to me, what can be the problem
![captura](https://cloud.githubusercontent.com/assets/19599668/25190171/0abb0694-24f1-11e7-9b9f-509cb3457295.PNG)
?

**Comment by yurydelendik** [comment]
The client reports that this file is missing. Supporting glassfish server is out of scope of this project. Closing as answered.
