### ISSUE TITLE
Creating delay between page change event

### ISSUE THREAD

**Issue by prachinema** [mozilla/pdf.js#8325]
Configuration:
- Web browser and its version: Chrome 57.0.2987.133
- Operating system and its version: Windows 8.1 Enterprise
- PDF.js version: 1.8.170

I'm using PDF.js for rendering my PDFs. I need to create a delay of 10 seconds between each page change event. I have tried adding below event listener on my page, but this triggers after the default page change listener.

        document.addEventListener("pagechange", function (e) {
                       //my code
        });

But this event is triggered after the default 'pagechange' event. So it doesn't prevent the page from changing.
	
I need the user to stay on the same page for atleast 10 seconds and to prevent changing the page

**Comment by yurydelendik** [comment]
> So it doesn't prevent the page from changing.
> I need the user to stay on the same page for atleast 10 seconds and to prevent changing the page

You cannot prevent HTML page from scroll, unless you will start overriding scroll position. You have to write a specialized viewer yourself -- demo viewer will be hard for you to adapt and snippet above is wrong place/way to do it. See e.g. https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html or https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js

Closing as answered.
