### ISSUE TITLE
PDFDocumentProxy or PDFPageProxy to serializable object

### ISSUE THREAD

**Issue by Liestambeur** [mozilla/pdf.js#8326]
Hey!

I would like to use Pdf.js to render offline pdf's.
I tested on different pdf's and the method getDocument always takes a long time. Is it possible to overcome this time to store the PDFPageProxy or PDFDocumentProxy? The solutions I found (local storage like localforage) need a serializable object. Is there a way to adapt the PDFPageProxy to make this serializable? Or another way to save this object or to reduce the time it takes for the getDocument method?

**Comment by yurydelendik** [comment]
Proxy objects do not contain any data and merely represent data on the worker side, which refer entire arraybuffer with PDF data. So at the end you will store array of bytes. Closing as won't fix.
