### ISSUE TITLE
Question: is there any better way to implement zoom in

### ISSUE THREAD

**Issue by Olgagr** [mozilla/pdf.js#8327]
We're rendering PDF with pdf.js (we are not using viewer). I wonder if there is any better way to implement zoom in/out than re-rendering every time the zoom scale changes. Our current implementation looks like this:

```
viewerWrapper.classList.add('hidden', 'hidden');

const context = canvas.getContext('2d');
const viewport = pdf.getViewport(zoom);

canvas.height = viewport.height;
canvas.width = viewport.width;
const renderContext = {
    canvasContext: context,
    viewport,
};

const renderTask = pdf.render(renderContext);
renderTask.then(() => {
    viewerWrapper.classList.remove('hidden', 'hidden');
});
```
The problem with this approach is that we have to hide/show viewerWrapper which causes flashing effect, there no smooth transition between zoom levels. I checked viewer implementation and there is renderTask.onContinue function in which canvas is shown but in my case it changes nothing.

**Comment by yurydelendik** [comment]
PDFPageView implements gradual canvas change for zoom in/out (but re-paint is need for better text display), see https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js example and add `pdfPageView.update(newScale)`. Closing as answered.

You can experiment with SVG backend, that is yet to be implemented; or use PDFJS.useOnlyCssZoom, which is bad for text quality.
