### ISSUE TITLE
Word searched in a PDF document was found, but not highlighted properly (mis-aligned with the searched word).

### ISSUE THREAD

**Issue by kpton** [mozilla/pdf.js#8333]
Link to PDF file (or attach file here):
[ICN-ROLLSROYCE-STDP-700000-R-K0680-CHP70-A-004-01.pdf](https://github.com/mozilla/pdf.js/files/956993/ICN-ROLLSROYCE-STDP-700000-R-K0680-CHP70-A-004-01.pdf)

Configuration:
- Web browser and its version:   Google Chrome version 57.0.2987.133
- Operating system and its version:   Windows 7 Professional SP1 64-bit
- PDF.js version:  v1.6.210
- Is an extension:  No

Steps to reproduce the problem:
1.   Open the selected PDF file in pdf.js viewer
2.   Search a word (e.g.  'subject'  or 'number').
3.   Navigate through hit list (using Find Next/Find Previous buttons in Find toolbar) 
4.  Several hits in the PDF document are not properly aligned with the searched word. 

What is the expected behavior? (add screenshot)
- All searched words (hits) should be properly highlighted.
What went wrong? (add screenshot):
![screenshot-1](https://cloud.githubusercontent.com/assets/28031104/25415502/dc07c584-29ec-11e7-8a39-2602267456b6.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/28031104/25415508/e69e387a-29ec-11e7-9587-a9e82119090b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by m-abdulsamad-confiz** [comment]
I investigated this issue, and to me it seems there is a problem while highlighting the text but the 'find' functionality is fine. Can anyone shed some light on it :)

**Comment by timvandermeij** [comment]
Closing since this is fixed after recent text layer fixes.
