### ISSUE TITLE
Certain `forms` reference tests, containing text fields, are failing in Firefox on both bots

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#8334]
As can be seen in https://github.com/mozilla/pdf.js/pull/3891#issuecomment-297307522 and https://github.com/mozilla/pdf.js/pull/3891#issuecomment-297311016, certain `forms` test-cases that contain text fields have started failing in Firefox on *both* of the bots. *Note:* this is with tests run against the current `master`.

This is really strange, since first of all the number of test failures on the Linux/Windows bots are *not* identical. Second of all, when testing locally using the latest Nightly (i.e. Firefox 55), or the latest Aurora (i.e. Firefox 54), on Windows I cannot reproduce this.

*Edit:* Also, opening those test-cases with the default viewer in Firefox 54/55 with `renderInteractiveForms = true` set, I'm not able to reproduce any issues either.

**Comment by timvandermeij** [comment]
It could be that this is an issue in the rasterization code for the tests. I suspect #8005 is the same issue as this one actually.

**Comment by timvandermeij** [comment]
The Linux bot renders `f1040-forms` correctly again.

**Comment by timvandermeij** [comment]
Firefox 55 on the Linux bot regressed the rendering of `f1040-forms` again (see http://54.67.70.0:8877/28a03e33e0c3cf3/reftest-analyzer.html).

**Comment by timvandermeij** [comment]
The Linux bot is completely fixed after the Firefox 57 update. This issue now only tracks the Windows bot.

**Comment by brendandahl** [comment]
The form tests also intermittently work for me locally on MacOS in both FF and Chrome.

**Comment by timvandermeij** [comment]
The Windows bot is now also fixed after the Firefox 57 update. Closing since this issue is fixed. If intermittent issues remain after updating to Firefox 57, a new ticket should be opened to track that.
