### ISSUE TITLE
Error: Cannot resolve callback 1 in v1.8.254

### ISSUE THREAD

**Issue by omkadiri** [mozilla/pdf.js#8336]
This was said to have been fix in https://github.com/mozilla/pdf.js/issues/5344 but i can still see the console error

I just install pdfjs-dist 1.8.25, Am getting the console error in both chrome and mozilla firefox. eg from https://github.com/mozilla/pdf.js/issues/5344:

![image](https://cloud.githubusercontent.com/assets/10691627/25451088/037dbb30-2a8f-11e7-88cd-b6d7a8655404.png)
Error: cannot resolve callback 1

**Comment by yurydelendik** [comment]
WFM http://jsbin.com/wudabu/edit?html,js,output

Closing.
