### ISSUE TITLE
Is it possible to run the PDFJS without the data-uri?

### ISSUE THREAD

**Issue by suthanbala** [mozilla/pdf.js#8360]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Windows Cordova App (t doesn't support loading of data-uri)
- Operating system and its version: Windows 10
- PDF.js version: 1.7.225

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/4681651/25622856/e05534fa-2f23-11e7-8a81-c929ab39c79a.png)

What went wrong? (add screenshot)
It loads pretty slow, I believe it's retrying to load the font again and again for a certain amount of times for the document.
![image](https://cloud.githubusercontent.com/assets/4681651/25622998/264cc716-2f24-11e7-9cfc-9b06b0783956.png)

Sorry no live link. Since Windows app doesn't support `data-uri` loading for local context, is it possible to run it using other option than `data-uri` for embedding the fonts and other necessary styles?

**Comment by yurydelendik** [comment]
There is low quality font rendering available via disableFontFace (it's also slower). It's your trade-off for window app restrictions. It better to make it work with font loading API or via data/blob mechanism if available. Closing as answered.
