### ISSUE TITLE
Missing dots in certain PDF file

### ISSUE THREAD

**Issue by iamCristYe** [mozilla/pdf.js#8373]
Link to PDF file (or attach file here):
[Nat Struct Mol Biol 2008 Zenklusen.pdf](https://github.com/mozilla/pdf.js/files/975293/Nat.Struct.Mol.Biol.2008.Zenklusen.pdf)

Configuration:
- Web browser and its version: Chrome 58.0.3029.96
- Operating system and its version: Windows 15063.250
- PDF.js version: 1.7.225
- Is an extension: No

Steps to reproduce the problem:
Have a look at the top right pic on page 6

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/25691977/410ce348-3054-11e7-8516-4466dd64db30.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/12642018/25691987/4795e142-3054-11e7-8f79-b4ad3e468c27.png)

**Comment by THausherr** [comment]
The two dot images are in patterns, which have 32767 X- and Y-steps. Maybe related to #7731. Here's a reduced version.
[PDFJS-8373-reduced.pdf](https://github.com/mozilla/pdf.js/files/978867/PDFJS-8373-reduced.pdf)
