### ISSUE TITLE
Safari - zoom and slow re-drawing

### ISSUE THREAD

**Issue by Olgagr** [mozilla/pdf.js#8374]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Safari 10.1
- Operating system and its version: OS X El Capitan (10.11.6) 
- PDF.js version: 1.8.254
- Is an extension: no

Steps to reproduce the problem:
1. I implemented zoom in/out using PDFPageView:
```
const pdfPageView = new PDFJS.PDFPageView({
   container: pdfPage,
   id: 1,
   scale: zoom,
   defaultViewport: pdf.getViewport(zoom),
});

pdfPageView.setPdfPage(pdf);
pdfPageView.draw();

// when zoom level changes
pdfPageView.update(zoom);
pdfPageView.draw();
```

2. In Chrome and FF everything works nicely. The problem is in Safari. When I'm zooming in/out, I see some portion of pdf moved (I suspect these areas has images). It disappears after ~ one second, I guess after re-drawing.

I wonder is there any way to make it faster.

What is the expected behavior?

![le_telegramme](https://cloud.githubusercontent.com/assets/1297219/25694390/b5cd3048-30ae-11e7-9fd9-c890287e50a3.png)

What went wrong? 

![le_telegramme](https://cloud.githubusercontent.com/assets/1297219/25694325/67902e76-30ae-11e7-964a-061e944c9bde.png)

**Comment by Snuffleupagus** [comment]
> In Chrome and FF everything works nicely. The problem is in Safari. When I'm zooming in/out, I see some portion of pdf moved (I suspect these areas has images). It disappears after ~ one second, I guess after re-drawing.

That would indicate that the problem is with the Safari browser, rather than in the PDF.js library; hence it's not clear that keeping the issue open is meaningful.

Furthermore, given that neither the PDF file in question or a runnable example were provided, this issue isn't actionable anyway; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Olgagr** [comment]
Ok, I'm closing the issue.
