### ISSUE TITLE
scrolling event to calculate how much scrolling is done for pdf.

### ISSUE THREAD

**Issue by kiranmahale** [mozilla/pdf.js#8379]
Hello,
Currently, there is no event from which we can get the percentage of scrolling is done for pdf. Can you please provide a solution about how can I get scrolling percentage?

**Comment by timvandermeij** [comment]
You can do something like https://stackoverflow.com/questions/2387136/cross-browser-method-to-determine-vertical-scroll-percentage-in-javascript. Closing as answered.
