### ISSUE TITLE
Horrible performance with a pdf document

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#8380]
https://www.mbank.pl/download/firma/Dyspozycja-zmiany-typu-rachunku-biecego.pdf?noredir -- this pdf takes over 25 seconds to display.

Configuration:
- Web browser and its version: Nightly 55.0a1 (2017-05-05) (32-bit)
- Operating system and its version: Windows 7 SP1
- PDF.js version: 1.8.320
- Is an extension: yes

**Comment by yurydelendik** [comment]
Looks like doPDF (?) is doing "good" job in producing content, I see lots of tiny image painted:

```
	1422	save	[]
	1423	save	[]
	1424	transform	[1,0,0,1,209.76,652.32]
	1425	transform	[0.96,0,0,0.48,0,0]
	1426	dependency	["img_p0_71"]
	1427	paintJpegXObject	["img_p0_71",4,2]
	1428	restore	[]
	1429	restore	[]
	1430	save	[]
	1431	save	[]
	1432	transform	[1,0,0,1,210.72,652.32]
	1433	transform	[0.96,0,0,0.48,0,0]
	1434	dependency	["img_p0_72"]
	1435	paintJpegXObject	["img_p0_72",4,2]
	1436	restore	[]
	1437	restore	[]
	1438	save	[]
	1439	save	[]
	1440	transform	[1,0,0,1,211.68,652.32]
	1441	transform	[0.96,0,0,0.48,0,0]
	1442	dependency	["img_p0_73"]
	1443	paintJpegXObject	["img_p0_73",4,2]
	1444	restore	[]
	1445	restore	[]
	1446	save	[]
```

**Comment by timvandermeij** [comment]
This PDF file renders in two seconds for me (Arch Linux 64-bit, Firefox 53.0, PDF.js development version). Not too performant, but much better than the 25 seconds reported. You can see the images being drawn, so probably an optimization is possible to recognize this bad pattern and replace it.

**Comment by automatedbugreportingfacility** [comment]
Hi Tim,

Thank you. I tested a little further, and it seems that disabling Adblock Plus v2.8.2.4245-beta reduces time taken to render the document from over 25 seconds to 2 seconds that you mention. With Adblock enabled, there's a high CPU usage in the browser process while the document is being rendered.

**Comment by thestinger** [comment]
Try uBlock Origin instead of ABP. ABP is known to be very inefficient by injecting enormous CSS style sheets.
