### ISSUE TITLE
Cannot (do not know how to) leave page number box using keyboard?

### ISSUE THREAD

**Issue by adavidzh** [mozilla/pdf.js#8389]
It is very common to want to skip to a certain slide and then come back to <kbd>←</kbd> <kbd>→</kbd> browsing.

Steps to reproduce the problem:
1. Go to page number box using <kbd>Ctrl/⌘</kbd>+<kbd>Alt</kbd>+<kbd>G</kbd>.
2. Cannot leave using keyboard, namely using <kbd>Esc</kbd>.

What is the expected behavior?
I would expect that pressing <kbd>Esc</kbd> would bring focus back to the pages.

**Comment by sahil56** [comment]
Pressing <kbd>Tab</kbd> brings focus back to pages.

**Comment by adavidzh** [comment]
Sort of: pressing <kbd>Tab</kbd> definitely allows to use <kbd>←</kbd> and <kbd>→</kbd> to change page, but focus is definitely on the zoom out button.
