### ISSUE TITLE
print Arabic wrong

### ISSUE THREAD

**Issue by Smiler94** [mozilla/pdf.js#8392]
Link to PDF file (or attach file [here):]
[31039855943.pdf](https://github.com/mozilla/pdf.js/files/983151/31039855943.pdf)

Configuration:
- Web browser and its version:Firefox 53.0.2 32bit
- Operating system and its version:Windows 7
- PDF.js version:latest
- Is an extension:no

Steps to reproduce the problem:
1. I use pdf.js to show the pdf file which contain Arabic contents
2.when I print it, the Arabic contents were replaced with []

What is the expected behavior? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/9924085/25800134/9b8ae080-341a-11e7-8403-582e2b36a444.png)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/9924085/25800165/bbc1ce9a-341a-11e7-9589-2674ac487237.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is an upstream bug, and the solution will require patching of Firefox; please refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1524640#c1.

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
