### ISSUE TITLE
PDF which CFF hdrSize is 17 isnot displayed correctly

### ISSUE THREAD

**Issue by yoshinori99** [mozilla/pdf.js#8404]
Configuration:
IE11,Windows10,PDF.js(ver1.4.2)

The pdf file which contains the CFF is not displayed correctly.

Please,see the attach file.
![attachfile](https://cloud.githubusercontent.com/assets/28625432/25977415/6c0edbde-36f6-11e7-84bc-4bbe400c1f17.png)

CFF header size is 17byte and "header.hdrSize" is also 17.
Following code① at pdfworker.js is seems like assumed 4byte.
So I tried changed code② as a test then pdf is displayed collectly.

Is the way of like code② correct?

<code①>
compileHeader: function CFFCompiler_compileHeader(header){
return [
header.major,
header.minor,
header.hdrSize,
header.offSize
];
},

<code②>
compileHeader: function CFFCompiler_compileHeader(header) {
var headerArray = [];
for (var i = 0 ; i < header.hdrSize; i++)
{
headerArray.push(0);
}
headerArray[0] = header.major;
headerArray[1] = header.minor;
headerArray[2] = header.hdrSize;
headerArray[3] = header.offSize;

return headerArray;
},

I am looking forward to your reply.

**Comment by Snuffleupagus** [comment]
> The pdf file which contains the CFF is not displayed correctly.

As outlined in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), you'll need to provide a link (or attach) the problematic PDF file here in order for this issue to be valid!

**Comment by yoshinori99** [comment]
Thank you for replying.
I'm sorry.
Its difficult to provide the problematic PDF file Immediately.
Because the PDF file is confidential.
After creating a sample PDF file,I'll provide.

**Comment by timvandermeij** [comment]
Closing since this is incomplete for now, but we can reopen this once a sample is provided. Thanks.
