### ISSUE TITLE
Link Annotation - error trapping - not a bug per se

### ISSUE THREAD

**Issue by alQemist** [mozilla/pdf.js#8407]

**Comment by timvandermeij** [comment]
Personally I'm not sure I understand the issue here. Is PDF.js supposed to do something, or is it intended that this does not work at the moment? I don't see what you want PDF.js to do here exactly.

**Comment by alQemist** [comment]
Sorry I wrote that report early this morning before the caffeine had time to kick in.
I want to use link annotations to trigger another custom function whenever they contain a particular string , which is not a valid url. By default they fail silently which is nice but I need to know where the link click event is being handled. Basically I want to know where I can add new logic to trap for a specific URI  to put it more simply.

**Comment by timvandermeij** [comment]
Thank you for the clarification. In that case, you'll want to look at https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L273. That class handles `Link` annotations. More specifically, https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L317 is the event handler.

**Comment by alQemist** [comment]
Perfect ! thank you so much !
