### ISSUE TITLE
What happened to DEFAULT_CACHE_SIZE

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8410]
hi. i noticed DEFAULT_CACHE_SIZE is not a global variable anymore.

is there a new variable now for this? how to access this now?

**Comment by yurydelendik** [comment]
> hi. i noticed DEFAULT_CACHE_SIZE is not a global variable anymore.
> is there a new variable now for this? how to access this now?

No, there is not. It's not a configurable property of the demo viewer. You have to maintain and support you custom version of the code for that. Closing as answered.
