### ISSUE TITLE
Errors during running makeref

### ISSUE THREAD

**Issue by cgreening** [mozilla/pdf.js#8412]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: NA
- Operating system and its version: MacOS X 
- PDF.js version: master
- Is an extension: no

Steps to reproduce the problem:
1. Follow the contributing instructions
2. Run makeref

What is the expected behavior? (add screenshot)

All pdfs are downloaded successfully?

What went wrong? (add screenshot)

```
WARNING: File was not downloaded. See "pdfs/issue3999.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/hmm.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/wdsg_fitc.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/geothermal.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/issue5752.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/issue6117.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/issue2442.pdf.error" file.
WARNING: File was not downloaded. See "pdfs/bug887152.pdf.error" file.
```

**Comment by timvandermeij** [comment]
If the files are not in the repository (e.g., due to licensing issues), they are downloaded from the Web Archive. It happened before that the Web Archive website is temporarily slow or unresponsive, so I'd suggest to try again later. Please let us know if that works.

**Comment by cgreening** [comment]
http://web.archive.org/web/20151016185606/http://www.nber.org/papers/w4332.pdf

Blocked by a robots.txt file on http://nber.org/robots.txt.

http://web.archive.org/web/20150212141833/http://geothermal.inel.gov/publications/future_of_geothermal_energy.pdf

This URL has been excluded from the Wayback Machine.

http://web.archive.org/web/20140925155348/http://www.nature.com/news/2010/100721/pdf/466432a.pdf

Blocked by robots.txt on http://www.nature.com/robots.txt

**Comment by timvandermeij** [comment]
Right, that's something we need to fix. Labeling this issue as such, thanks.
