### ISSUE TITLE
[Request] New example

### ISSUE THREAD

**Issue by johnnyasantoss** [mozilla/pdf.js#8414]
Hello!
Just wanted to thank you guys for making this awesome lib and ask a few questions.

I did a nice (I think at least) example of using PDF.js for generating images, and I think that it could be useful for people that are looking for a tool to create images of a pdf or just learning how to use PDF.js.

[Here][jsfiddle] it is.

It could be added [here][examples]

That's it!
Thanks!

 [jsfiddle]: https://jsfiddle.net/johnnyasantoss/vuqr8tfh/
 [examples]: https://mozilla.github.io/pdf.js/examples/

**Comment by timvandermeij** [comment]
Thank you for your feedback! In the `examples` folder in the repository, we already have such an example with instructions: https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png. However, you're always free to add your example to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications if you like.
