### ISSUE TITLE
Terminated due to memory issue on iPad

### ISSUE THREAD

**Issue by buptlilu** [mozilla/pdf.js#8418]
I use the pdf.js to render pdf files on iPhone and iPad. I find that when I load a pdf file which is about 400 pages if I scroll the view quickly, my app will be Terminated. And Xcode shows  "Message from debugger: Terminated due to memory issue". My question is : how can I clear the cache when I use pdf.js to load a pdf file ? I don't know if there is a function to release memory when the memory is large ?

**Comment by yurydelendik** [comment]
Hard to tell without requested information. Closing as incomplete. I'm guessing it is a custom solution that is trying to display 400 canvases at once -- see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages .
