### ISSUE TITLE
TypeError: Cannot set property 'compatibilityChecked' of undefined when running Mocha Tests

### ISSUE THREAD

**Issue by ryanCchen** [mozilla/pdf.js#8423]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Mocha Test Runner
- Operating system and its version: macOS Sierra 10.12.4
- PDF.js version: 1.8.359
- mocha, chai, enzyme

Steps to reproduce the problem:
1. `import PDFjs from 'pdfjs-dist' ` into component on React
2. run mocha tests

What is the expected behavior? (add screenshot)
![screen shot 2017-05-18 at 10 25 01 am](https://cloud.githubusercontent.com/assets/17462600/26215239/7632563c-3bb4-11e7-86af-f8dabf64f92d.png)

What went wrong? (add screenshot)
![screen shot 2017-05-18 at 10 25 28 am](https://cloud.githubusercontent.com/assets/17462600/26215991/57258ad6-3bb7-11e7-8027-1c0800d4fa68.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

opinion:
![screen shot 2017-05-18 at 10 50 16 am](https://cloud.githubusercontent.com/assets/17462600/26216135/d8bbb57a-3bb7-11e7-9b3c-7deafd2a824e.png)
I believe the issue is stemming from here as there seems to be an issue with `PDFJS` being undefined at this point and for some reason `globalScope.PDFJS` is not properly initializing the object.

**Comment by yurydelendik** [comment]
a small project to reproduce the problem is needed.

**Comment by ryanCchen** [comment]
@yurydelendik here is the link to the project. Let me know if you need anything else. Thanks!

https://github.com/ryanCchen/mocha-pdfjs

**Comment by yurydelendik** [comment]
"test/dom" adds `window`, which is not global we need better way to detect globalScope

**Comment by ryanCchen** [comment]
@yurydelendik thanks for the response

My current workaround is to add `globalScope.PDFJS.compatibilityChecked = true;` in the 
` ../node_modules/pdfjs-dist/build/pdf.js` file which is related to `compatibility.js` will this lead to any complications when using different browsers?

**Comment by brendandahl** [comment]
Could do the old `(1, eval)('this');`

**Comment by yurydelendik** [comment]
> Could do the old (1, eval)('this');

eval can be disabled by CSP

**Comment by yurydelendik** [comment]
Something like https://github.com/zloirock/core-js/blob/master/modules/_global.js ?
