### ISSUE TITLE
compatibility runHandlers RUN_TIMEOUT setting and performance

### ISSUE THREAD

**Issue by clausreinke** [mozilla/pdf.js#8427]
Link to PDF file (or attach file here): any large PDF file (300 pages show the effect nicely)

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 7
- PDF.js version: 1.8.188
- Is an extension:

Steps to reproduce the problem:
1. open the file
2. wait until first page is rendered, scroll to page 2
3. now wait until page 2 appears

What is the expected behavior? should take no more than a couple of seconds

What went wrong? takes very long

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
local install, local file system

I'm having performance issues rendering large documents in IE11 (these issues do not appear in Chrome).

After staring at the f12 tools profiles for a while, I started wondering about all those `Timer(runHandlers)` invocations, none of these seem to take much time, but there are just so many of them that it fills the seconds.

So I tried changing the `RUN_TIMEOUT` in `runHandlers` (I think this is from compatibility.js) and noticed drastic improvements in the waiting time. Are there any disadvantages when setting the value from `1` to `5`? Doesn't seem long enough to cause blocking in the UI.

**Comment by yurydelendik** [comment]
https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js#L928

It is from Promise polyfill. Modern browsers don't use that anymore -- they have native support for promises.

> Are there any disadvantages when setting the value from 1 to 5?

We can increase RUN_TIMEOUT value. It will not affect most of the browsers we support, only legacy browsers. A pull request is welcome.

**Comment by amitsin6h** [comment]
I would like to work on this bug am ready with my dev env

**Comment by timvandermeij** [comment]
Feel free to work on this. Thanks!

**Comment by Snuffleupagus** [comment]
PR #9054 switched PDF.js to use the https://github.com/zloirock/core-js#ecmascript-6-promise polyfill, in order to avoid having to maintain a Promise polyfill ourselves.
Hence I'm closing this issue, since there's no longer anything to address on the PDF.js side.
