### ISSUE TITLE
use ajax to get viewer.html,content isn't show

### ISSUE THREAD

**Issue by moahmn** [mozilla/pdf.js#8440]
Link to PDF file (or attach file here):

Configuration:
- any browser
- win7 64
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. i want to embed pdf to my pop-up layer and this my code:
	<div id="b"></div>
	<script type="text/javascript" src="jquery-1.12.2.min.js"></script>
	<script type="text/javascript">
	$.get('../web/viewer.html',function(data){
		$('#b').append(data);
	})
	</script>

and i find the context isn't show.why?
 

What is the expected behavior? (add screenshot)

just like open your example https://mozilla.github.io/pdf.js/web/viewer.html

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Works for me. Closing
