### ISSUE TITLE
pdfjs-dist/webpack.js and IE9 support

### ISSUE THREAD

**Issue by FranckFreiburger** [mozilla/pdf.js#8451]
I successfully tested [pdfjs-dist/webpack.js](https://github.com/mozilla/pdfjs-dist/blob/master/webpack.js) for bundling the pdf worker properly.
Everything works fine except for IE9 (used with compatibility.js).
Since IE9 has no Worker class, [worker-loader](https://github.com/webpack-contrib/worker-loader/blob/5225c54e56e77e5ba50f2d983a5bf725d91137bf/index.js#L15) cannot be used properly.
Is it possible to set `PDFJS.workerPort` according to the `Worker` class availability ? 
eg.
```
if ( typeof window !== 'undefined' && 'Worker' in window ) {

	pdfjs.PDFJS.workerPort = new PdfjsWorker();
}
```

**Comment by yurydelendik** [comment]
There is a little we can do for IE9. Please don't use pdfjs-dist/webpack in this case and continue using setting of PDFJS.workerSrc method. Closing as won't fix.

**Comment by yurydelendik** [comment]
How is the worker-loader is used with IE9 anyway?

**Comment by FranckFreiburger** [comment]
I think that worker-loader don't care about browsers that do not have the `Worker` class, it just generates the sting `new Worker(${workerPublicPath})`.

**Comment by yurydelendik** [comment]
> I think that worker-loader don't care about browsers that do not have the Worker class,

Correct. We always promoted PDFJS.workerSrc method since it has proper non-Worker fallback.  pdfjs-dist/webpack is added to people who use worker-loader.

**Comment by FranckFreiburger** [comment]
Since I already use webpack for my project, I would prefer to also use worker-loader, but except for IE9.
The current setup works fine:
```
var PDFJS = require('pdfjs-dist');

var PdfjsWorker = require('worker-loader!pdfjs-dist/build/pdf.worker.js');
if ( typeof window !== 'undefined' && 'Worker' in window )
	PDFJS.PDFJS.workerPort = new PdfjsWorker();
```

On IE9 console, I get `Warning: Setting up fake worker.` (what is expected), and on other browsers, no fake worker and pdf are loading properly.

**Comment by yurydelendik** [comment]
This might work. Add else branch with `PDFJS.PDFJS.disableWorker=true;` and submit as a PR.

**Comment by FranckFreiburger** [comment]
ok, I will create the PR.
However I cannot figure out if only one "copy" of the worker will be included in the final bundle, since the `pdf.worker.js` file The file could be loaded elsewhere (I am quite new to webpack)

**Comment by yurydelendik** [comment]
>  I cannot figure out if only one "copy" of the worker will be included in the final bundle

There shall be two copies of the "worker": one for Web Worker, another one for its disableWorker fake. However only one of them will be loaded into a page.

**Comment by FranckFreiburger** [comment]
ok, I hope it is acceptable since the worker is around 600 KB
