### ISSUE TITLE
Disappeared backspace  between word and word after copying and selecting

### ISSUE THREAD

**Issue by Echocruise** [mozilla/pdf.js#8453]
Link to PDF file (or attach file here):
[1994--2016考研英语翻译（英语一）.pdf](https://github.com/mozilla/pdf.js/files/1033305/1994--2016.pdf)

Configuration:
- Web browser and its version:   Google Chrome 57.0.2987.98 (64-bit)
- Operating system and its version: Win10 64bit 14393
- PDF.js version: pdfjs-1.7.225-dist
- Is an extension: not a extension

Steps to reproduce the problem:
1.  use PDF.JS to read a PDF documents
2. copy some texts in the documents 
3. find the backspace between word and word is disappear

What is the expected behavior? (add screenshot)
![disappeared backspace](https://cloud.githubusercontent.com/assets/13390670/26517996/25cb8d6e-42d8-11e7-9d16-40eb5272ada4.png)

what  I expected is  the backspace still exists after copying

What went wrong? (add screenshot)
![disappeared backspace](https://cloud.githubusercontent.com/assets/13390670/26517996/25cb8d6e-42d8-11e7-9d16-40eb5272ada4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since this is fixed now.
