### ISSUE TITLE
please remove PDF Viewer(discontinued) from android add-ons website

### ISSUE THREAD

**Issue by krihsna** [mozilla/pdf.js#8456]
the add-on at https://addons.mozilla.org/en-US/android/addon/pdfjs/ states that " It will be marked as incompatible starting from the Firefox version 35."

if this is not compatible with latest versions of fennec, please remove from Mozilla addons website.

**Comment by timvandermeij** [comment]
I don't know if we can actually do that, in terms of if we have the correct rights to remove it and if that has any side-effects.

/cc @yurydelendik @brendandahl Do you know more about this?

**Comment by Snuffleupagus** [comment]
Closing, since it appears that the addon has now been removed (https://addons.mozilla.org/en-US/firefox/addon/pdfjs/ displays "This add-on has been removed by its author.").
