### ISSUE TITLE
Slow first range loading (http 206)

### ISSUE THREAD

**Issue by chatelain** [mozilla/pdf.js#8457]
Hi,

I have made a custom viewer for PDF.JS that users can include on their own website with CORS request.

I give a webservice url to the getDocument function, that set the correct headers and serve the PDF file progressively with HttpResponse::setFile($location) and HttpResponse::send() [from apache]

The first time the pdf loads, it is very fast, but when I refresh the page many times, it takes always one minute before the first range request give an answer. (screenshot below)

The problem doesn't appear when I give the direct link to the PDF.
Do you have an idea where to look for ?

Thank you, best regards

![capture d ecran 2017-05-30 a 15 00 28](https://cloud.githubusercontent.com/assets/3294486/26584609/afd4002c-4549-11e7-9b9d-0be8f61b36b0.png)

![capture d ecran 2017-05-30 a 15 01 03](https://cloud.githubusercontent.com/assets/3294486/26584617/b57225a4-4549-11e7-8917-6bab01274bbc.png)

Configuration:
- Web browser and its version: Chrome 58
- Operating system and its version: MAC OS X El Captain
- PDF.js version: 1.7.225

**Comment by yurydelendik** [comment]
Looks like it's a PHP side is holding response. Not sure it's a problem on PDF.js side, but would be much clear with complete and worker example (including PHP code was provided). Please provide short PHP project that reproduces the issue.

**Comment by chatelain** [comment]
Hi,

thank you for the answer.
I have tried to empty my webservice and just let the HttpResponse method for serving the files and I noted that the slow loading was caused by the session_start() in my webservice.

I cannot explain why but now the problem of slowness has disappeared.

Thank you very much !

Best regards
