### ISSUE TITLE
Firefox bullet point rendering bug (F0B7 unicode character)

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#8460]
Link to PDF file (or attach file here): https://cloud.box.com/s/bs6708c0hwpoxuew4br2yx16eunhg2zu

Configuration:
- Web browser and its version: Firefox 53.0.3
- Operating system and its version: Mac OSX El Capitan
- PDF.js version: Latest on https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: No

Steps to reproduce the problem:
1. Download PDF from https://cloud.box.com/s/bs6708c0hwpoxuew4br2yx16eunhg2zu
2. Go to https://mozilla.github.io/pdf.js/web/viewer.html on Firefox
3. Open downloaded PDF
4. Go to third page, highlight a bullet point
5. Notice that 'F0B7' unicode character shows up over the bullet point, even though it's supposed to be transparent. This shows up as a square character in Chrome that is hidden, regardless of text selection.

What is the expected behavior? (add screenshot)
No unicode character shows up after text selection:
![2017-05-30_11-24-43](https://cloud.githubusercontent.com/assets/689351/26598615/a896e280-452a-11e7-9491-44be4811593b.png)

What went wrong? (add screenshot)
Unicode character shows up after text selection:
![2017-05-30_11-24-07](https://cloud.githubusercontent.com/assets/689351/26598572/899dc9d4-452a-11e7-95e4-75c06bc0d4b5.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by tonyjin** [comment]
Not sure if this is a text selection or rendering issue in Firefox - in the sample pdf.js viewer, the F0B7 character only shows up after a text selection, but using a custom build (we're on 1.8.323) on Firefox, the character shows up before text selection as well.

To view for yourself:
- Use Firefox 53.0.3
- Visit https://darth.app.box.com/on/beta
- Visit https://darth.box.com/s/ujwqqtlqst73ts3a6yof3866phiqtli6
- Go to page 2, notice the character is visible before any sort of text selection

**Comment by timvandermeij** [comment]
Closing since this no longer happens. This might have been a bug in Firefox.
