### ISSUE TITLE
Image and font issues in Safari (only some versions)

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#8471]
Here is the PDF:

[SLDT140 - SKYLINE DUOTEK 140 data-sheet.pdf](https://github.com/mozilla/pdf.js/files/1044724/SLDT140.-.SKYLINE.DUOTEK.140.data-sheet.pdf)

Using the latest pdf.js viewer at https://mozilla.github.io/pdf.js/web/viewer.html

Everything OK in most browsers, including some versions of Safari.
But in one version of Safari there are some images missing and fonts incorrect as follows - Safari on the left, correct appearance on right:

![screen shot 2017-05-31 at 16 47 16](https://cloud.githubusercontent.com/assets/786238/26679861/c6eef100-46ce-11e7-9a80-fcff811a347d.png)

The OS and browser details for the BROKEN display are:
Safari Version: 10.1 (12603.1.30.0.34)
System Version:	macOS 10.12.4 (16E195)
Kernel Version:	Darwin 16.5.0

Another BROKEN version:
Safari Version 10.1.1 (12603.2.4)
System Version:	macOS 10.12.5 (16F73)
Kernel Version:	Darwin 16.6.0

Thank you!

**Comment by Snuffleupagus** [comment]
Closing as duplicate; since the font issues appear to be tracked in #8231, and the image issues in #8317.
