### ISSUE TITLE
French latin characters with accents like é à ô ï don't print well with Canon printers on firefox

### ISSUE THREAD

**Issue by CdRom1** [mozilla/pdf.js#8481]
The Canon printer driver replaces all french accent characters by a rectangle. Firefox works fine when printing a webpage but doesn't work when printing a PDF. So I think the problem comes from pdf.js . I tested it with several printers and it looks like only canon printers have this problem. Tested it on Windows 7 and 10 with France/French language pack.

**Comment by Snuffleupagus** [comment]
As is, this issue is currently missing virtually all the required information in order to be actionable.

Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by timvandermeij** [comment]
Closing since this is not actionable right now and looks like a Canon-specific problem. Please provide more information to reopen.

**Comment by CdRom1** [comment]
Web Browser : Firefox 53.0.3 (and previous versions, I think)
Operating system : Windows 10 (64 bits), Windows 8 (64 bits), Windows 7 (64 bits)
pdf.js version: 1.6.467 (according to the console output)
is an extension : [I didn't understand the question. I'm using firefox to display PDFs.]
printer : Canon iP2800 series (driver version 2.75)
steps to reproduce the problem:
-print a pdf containing french accentuated characters like é à with mozilla firefox
It only does this with firefox when printing a pdf but webpages and other softwares work well.
examples : i've attached a pdf containing those characters and a scan of the print.
