### ISSUE TITLE
Display newline characters as `\n`?

### ISSUE THREAD

**Issue by th-m** [mozilla/pdf.js#8487]
Guess this is more of a question than an issue... I didn't have anywhere else to ask. 

I want to display newline characters as `\n` when converting pdf to text. I have looked everywhere and couldn't find anything about this. 

Configuration:
- Web browser and its version:
    Chrome
- Operating system and its version:
    Mac Sierra

Steps to reproduce the problem:
1. There are never any newline characters

**Comment by Snuffleupagus** [comment]
*Cross-posted in https://stackoverflow.com/q/44376415/5317012.*

There's no concept of line breaks in the PDF specification, please refer to the answer provided in https://stackoverflow.com/a/44380710/5317012; closing as answered.
