### ISSUE TITLE
examples/node/pdf2png example fails when using any other file other than the helloworld.pdf example file

### ISSUE THREAD

**Issue by nicholaswmin** [mozilla/pdf.js#8489]
### Configuration:
- Node.js v7.6.0
- OSX Sierra
- pdf.js v1.8.188

### Steps to reproduce the problem:

1. Add attached `gal-trace.pdf` file in `examples/helloworld/` folder
2. Change `pdfURL` in `examples/node/pdf2png/pdf2png` to point to `examples/helloworld/gal-trace.pdf`
2. Run the `pdf2png.js` example

### What is the expected behavior? 

- It creates 14 images - one image for each page in `gal-trace.pdf`

### What went wrong? (add screenshot)

- No images are created
- Terminal logs the following error:

```
# PDF document loaded.
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: document is not defined
(node:16114) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): ReferenceError: document is not defined
(node:16114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): ReferenceError: document is not defined

```

**Comment by ua1905** [comment]
**Same problem for me**

**Comment by jlfabi** [comment]
I am having a similar issue. Does the PDF need be generated by GNUpdf only?

**Comment by taxilian** [comment]
The issue appears to be related in some way to the fontLoader; I would guess it's in some way connected to having a custom embedded font in the PDF, but I'm still investigating. The actual location of the exception is:

```
Unhandled rejection ReferenceError: document is not defined
    at Object.fontLoaderInsertRule [as insertRule] (/Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/display/font_loader.js:36:42)
    at Object.fontLoaderBind [as bind] (/Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/display/font_loader.js:136:16)
    at Object.transportObj (/Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/display/api.js:1727:29)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/shared/util.js:1300:19)
    at LoopbackPort.<anonymous> (/Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/display/api.js:1177:18)
    at Array.forEach (native)
    at /Users/richard/code/gc/gcformservice/node_modules/pdfjs-dist/build/webpack:/src/display/api.js:1176:23
```

You can find this yourself by using Bluebird, setting `globals.Promise = require("bluebird");`.  Unlike native Promise bluebird logs unhandled rejections with a stack trace by default, which helps in this case.

**Comment by lafeuil** [comment]
I find a workaround in #7929 : 
try using `PDFJS.disableFontFace=true;`

> It's not fixing issue, it just using lines to draw letters instead of fonts and fillText.

**Comment by raliste** [comment]
What about documents with images?

```
Unhandled rejection ReferenceError: HTMLElement is not defined
    at CanvasGraphics_paintInlineImageXObject [as paintInlineImageXObject] (/Users/raliste/Work-Unsafe/preview/node_modules/pdfjs-dist/build/pdf.js:15331:30)
    at CanvasGraphics_paintImageMaskXObject [as paintImageMaskXObject] (/Users/raliste/Work-Unsafe/preview/node_modules/pdfjs-dist/build/pdf.js:15242:12)
```

**Comment by noauthoritybuturself** [comment]
any idea how to solve it for documents with images?

**Comment by cemerick** [comment]
I'm seeing the same error as @nicholaswmin with a different (very simple/small) document. A couple of data points:

1. I'm only calling `.getOperatorList()`; that's where my interactions with pdf.js end (not using its rasterization/display stuff in this context).
1. `PDFJS.disableFontFace=true` also is effective at eliminating the error as mentioned by @lafeuil. I haven't dug into how that setting will or won't affect what I'm doing, so I don't know if it's actually a workaround (yet).

**Comment by swftvsn** [comment]
So I chased these problems a bit today, and here's what I've found so far:

First of all, you don't need Bluebird to get the full stack of unhandled exceptions, just add this at the top of your script: 

`process.on('unhandledRejection', r => console.log(r))`

The examples are written in typescript andI drive this in Google Cloud Functions, so I require

```ts
import { PDFJSStatic, PDFDocumentProxy, PDFSource, PDFPageProxy } from 'pdfjs-dist'
const Canvas = require('canvas-prebuilt')
const pdfjs = require('pdfjs-dist') as PDFJSStatic
```

OK, let's start..

1. `disableFontFace=true;` works to combat the font loader issue. Please do note, that it must be fed as a parameter to pdfjs.getDocument today instead of global setting like this:

```ts
const source = {
  data: pdfBuffer,
  nativeImageDecoderSupport: 'none',
  disableFontFace: true
} as PDFSource
pdfjs.getDocument(source).then(result => {
```

2. `nativeImageDecoderSupport` must be set to `'none'` as shown in 1. to fix the "Image is not defined" issue explained in #9373 

3. To fix "Unhandled rejection ReferenceError: HTMLElement is not defined" in PDF's that contain images, one must introduce a global as follows:

`global.HTMLElement = class {}`

The stub can be empty, as the only point where it is used is this instance of: (the comment even states that this does not work in node..)
https://github.com/mozilla/pdf.js/blob/25bbff46927cb91cb72f62cbd681a20535d914f6/src/display/canvas.js#L2115-L2116

This could actually be fixed quite easily just by checking if `HTMLElement` exists like this:
```javascript
 // typeof check is needed in node.js, see issue #8489
 if ((typeof HTMLElement === 'function' && imgData instanceof HTMLElement) || !imgData.data) {
```

**Comment by swftvsn** [comment]
Opened PR to address the HTMLElement issue, see #9588
