### ISSUE TITLE
Error displaying font

### ISSUE THREAD

**Issue by RoyStobbelaar** [mozilla/pdf.js#8495]
[04-01-2017 APRIL.pdf](https://github.com/mozilla/pdf.js/files/1057899/04-01-2017.APRIL.pdf)
Hey there,

While using your library to show different PDF's, i've noticed that a particular PDF would not show correctly, the text simply was not displayed. The console was showing the following error 'Warning: Error during font loading: this._map[charCode].charCodeAt is not a function.'

After digging through the library files i've found the line where the error occurred; 
line 31141 in pdf.combined.js. 

After removing the .charCodeAt(0) function and simply using this._map[charCode] i noticed that the problem was solved, and that the font was loaded correctly. cMaps are used btw.

Here is a link to the PDF i used; https://www.scribd.com/document/350620291/04-01-2017-APRIL

Configuration used:
Chrome v58.0.3029.110 (64-bit)
MAC OS Sierra v10.12.5
PDF.JS version; v1.8.188

Steps to reproduce the problem:
1. Simply display the PDF using the library

I have supplied some screenshots;
Bugged version without font; http://imgur.com/t80tjCR
Version without .charCodeAt(0); http://imgur.com/a/i5f5M

I hope you guys can solve this problem,

Cheers!

**Comment by Snuffleupagus** [comment]
> Here is a link to the PDF i used; https://www.scribd.com/document/350620291/04-01-2017-APRIL

That link seem to require that you sign up to be able to download the file. Can you please attach the file directly to this issue instead?

**Comment by RoyStobbelaar** [comment]
Ah, i apologize. I have attached the PDF now.

**Comment by Snuffleupagus** [comment]
I cannot reproduce this issue, using PDF.js version `1.8.428` (which is the latest version as of this writing).

@RoyStobbelaar If you open your PDF file with the demo viewer (by clicking on the "Open File" button on the right-hand side of the toolbar), available at https://mozilla.github.io/pdf.js/web/viewer.html, does your file display correctly there?

If the demo viewer displays the file correctly, then it may be an issue with your custom implementation of PDF.js. In that case, you'll need to provide access to a working example in order for us to assist further.

**Comment by Snuffleupagus** [comment]
If I were to guess, since this appears to be an issue with a custom deployment of PDF.js, the problem might be that you're using a JavaScript Library/Framework that adds custom properties/methods to Arrays in such a way that they become `enumerable` (which is *not* correct).
That would explain the problem here, and it's something that we've seen reported from time to time, please refer to the discussion in issues such as #7064 and #7318.

**Comment by RoyStobbelaar** [comment]
Thanks for the support guys. Apparently the issue is solved by manually downloading the package rather then installing it using npm.

**Comment by rodmario193** [comment]
On my case I was implementing pdf.js on a propietary Javascript framework. After some debugging I found out that this framework was setting up aditional char codes on the **this._map** object that were not numbers at all. My solution was the to update my local copy of **pdf.worker.js**, from this:

`forEach: function forEach(callback) {`
  `     for (var charCode in this._map) {`
`          callback(charCode, this._map[charCode].charCodeAt(0));`
`      }`
`    }`

to this:

`forEach: function forEach(callback) {`
`      for (var charCode in this._map) {`
`        if ( !isNaN(charCode) )  callback(charCode, this._map[charCode].charCodeAt(0));`
`      }`
`    }`
