### ISSUE TITLE
SVG example generates svg holding lots of small black boxes -> the DOM looks weird.

### ISSUE THREAD

**Issue by kaarebs** [mozilla/pdf.js#8496]
Link to PDF file (or attach file here):
[error_prone_file.pdf](https://github.com/mozilla/pdf.js/files/1057922/error_prone_file.pdf)
It also happens in other pages of the pdf file, but I have only provided one page to reproduce the problem.

Configuration:
- Chrome - 58.0.3029.110 (64-bit)
- macOS Sierra - 10.12.5
- PDF.js version: "betaVersion": "1.8.188"

Steps to reproduce the problem:
- Just try the added pdf file with pdf.js's own provided svgviewer example

What is the expected behavior?
https://www.dropbox.com/s/c2gknbtlo6vchua/Screenshot%202017-06-07%2014.34.57.png?dl=0

What went wrong?
https://www.dropbox.com/s/082uf4z73v19zrs/Screenshot%202017-06-07%2014.35.26.png?dl=0

--
I the earlier versions of pdf.js this problem was occurring in many of my pdf's -> many have been fixed over time, but it still seems to occur sometimes.

--
kaarebs

**Comment by Rob--W** [comment]
With the current master version I also see grey boxes when I open the generated SVG file in Chrome and Firefox.

With PR 8542, the grey boxes disappear (the black boxes are still around though).

Before #8542:
![error_prone_file-old](https://user-images.githubusercontent.com/1365071/27286278-cc982164-54ff-11e7-8134-7a88f836a886.png)

After #8542:
![error_prone_file-with-pr8542](https://user-images.githubusercontent.com/1365071/27286279-cc983424-54ff-11e7-8b43-51c5cdd070b2.png)
