### ISSUE TITLE
Do I need to bind extra libraries when using pfd-dist in Webpack Ionic2/Ionic3?

### ISSUE THREAD

**Issue by distante** [mozilla/pdf.js#8502]
Configuration:
- Operating system and its version: MAC OS El Capitan
- PDF.js version: 1.8.428

I am trying to implement PDF.js into an Ionic 3 App, I installed [pdfjs-dist](https://www.npmjs.com/package/pdfjs-dist) and the typings from dt.

I can correctly import and call the library functions but It does work when I load the PDF into an HTML5's canvas element:

```
       loadPDFIntoCanvas() {
        console.log("Run loadPDF, loading pdf into canvas");

        pdfjsLib.getDocument(this.pdfPath)
            .then((pdf) => {
                this.pdfDocument = pdf;
                console.log("PDF File loaded");
                console.dir(this.pdfDocument);

                return this.pdfDocument.getPage(1);
            })
            .then((pdfPage) => {
                console.log("the pdfPage");
                console.dir(pdfPage);
                var scale = 1;
                var viewport = pdfPage.getViewport(scale);

                var canvas: HTMLCanvasElement = document.getElementById('the-canvas') as HTMLCanvasElement;
                console.log("the canvas");
                console.dir(canvas);
                var context = canvas.getContext('2d');

                canvas.width = window.outerWidth;
                canvas.height = window.outerHeight;
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };
                return pdfPage.render(renderContext);
            })
            .catch((e) => {
                console.warn(e);
            });

    }
```

But It completely breaks when I try to add it to a page container like the  [Page Viewer Component example](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js).

```
    loadPDFToPageContainer() {
        var DEFAULT_URL = this.pdfDefaultPath;
        var PAGE_TO_VIEW = 1;
        var SCALE = 1.0;
        var container = document.getElementById('pageContainer');

        // Loading document.
        PDFJS.getDocument(DEFAULT_URL).
            then( (pdfDocument)=> {
                this.pdfDocument = pdfDocument;
                // Document loaded, retrieving the page.
                return this.pdfDocument.getPage(PAGE_TO_VIEW);
             })
            .then( (pdfPage)=> {
                // Creating the page view with default parameters.
                var pdfPageView = new pdfjsLib.PDFPageView({
                    container: container,
                    id: PAGE_TO_VIEW,
                    scale: SCALE,
                    //defaultViewport: pdfPage.getViewport(SCALE),
                    // We can enable text/annotations layers, if needed
                    //textLayerFactory: new pdfjsLib.DefaultTextLayerFactory(),
                    //annotationLayerFactory: new pdfjsLib.DefaultAnnotationLayerFactory()
                });
                // Associates the actual page with the view, and drawing it
                pdfPageView.setPdfPage(pdfPage);
                return pdfPageView.draw();
            });
    }
```
The error says:

> ERROR Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_2_pdfjs_dist__.PDFPageView is not a constructor
TypeError: __WEBPACK_IMPORTED_MODULE_2_pdfjs_dist__.PDFPageView is not a constructor

The same is not a constructor error happens when I uncomment `textLayerFactory: new pdfjsLib.DefaultTextLayerFactory()` and `annotationLayerFactory: new pdfjsLib.DefaultAnnotationLayerFactory()`.

Since in the [pageviewer.html](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.html) file there is a ` <script src="../../build/dist/web/pdf_viewer.js"></script>` line I think I am missing some parts in my dist-build but I do not know what/where/how to add those.

I tried to add manually `pdf_viewer.js` but (as expected) It does not found the `pdf.js` file.

Do I need to add an extra Javascript file ?

**Comment by yurydelendik** [comment]
It's hard to tell without having the complete example. Here is [how to use getDocument](https://github.com/yurydelendik/pdfjs-react/blob/master/src/App.js) or [how to use PDFViewer](https://github.com/yurydelendik/pdfjs-react/blob/master/src/Viewer.js) in context of webpack - I hope this will help. Closing this issue as incomplete,

**Comment by distante** [comment]
Actually that is all the code. There is nothing more than the default ionic 3 Imports and the declarations of the `this.X` variables

```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import * as pdfjsLib from 'pdfjs-dist'; 
import * as $ from "jquery";
```

What I see as different from your how to use PDFViewer link is that I am importing `pdfjs-dist` and in the example is `pdfjs-dist/web/pdf_viewer.js`

**Comment by yurydelendik** [comment]
> Actually that is all the code.

Problem that contributors cannot run this code to troubleshot it. If there was a complete example and it would make world of difference to quickly run and observe the problem.

> default ionic 3 Imports

What's ionic 3?

**Comment by distante** [comment]
> What's ionic 3?
[Ionic Framework](http://blog.ionic.io/ionic-3-0-has-arrived/) a wrapper for Cordova, mobile apps with html.

I am importing from `web/pdf_viewer.js` now and it works better. I need to check out the example correctly because I get a blurry canvas but that is other problem. Thanks
