### ISSUE TITLE
IE not working

### ISSUE THREAD

**Issue by JoseDRojasA** [mozilla/pdf.js#8505]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: IE 11.296.15063.0
- Operating system and its version: Windows 10
- PDF.js version: Current in 2017/06/08

Steps to reproduce the problem:
1. Try to open a pdf in IE. 

![issue](https://user-images.githubusercontent.com/25036583/26951647-8f22cb04-4c67-11e7-98f1-bf1c9929d8a1.png)

I modified viewer.js to display a base64 file.

[PDF2.zip](https://github.com/mozilla/pdf.js/files/1062473/PDF2.zip)

**Comment by yurydelendik** [comment]
Access denied. Based on the screen you are trying to run a web application from local drive -- and that is impossible to do for some browsers. There is nothing we can do on PDF.js side about that. Closing as won't fix.
