### ISSUE TITLE
Remove error() and re-inspect assert() calls.

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#8506]
There is lots of confusion how error() is used. It also may mislead people when reading source code -- error() hides `throw new Error()`, so it's not easy to see control flow for human and JS analyzers cannot complain about dead code.

The same issue can be found with assert(). Normally assert() is used to define precondition for the following code, means that code shall never have its check `false`. (In other languages it's usually defined as hard stop for the program). By hiding checks and throw inside assert(), we also potentially removing JIT ability to make some assumptions.

- [x] Introduce InvalidPDFError() to raise when PDF is malformed instead of generic Error()
- [x] We need to review code and change `error(_)` => `throw new Error(_)`
- [ ] We need to review code and change `assert(_,?)` => `if (!_) throw new Error(_)` for non-assert-like calls (test for it is: it's impossible to remove this check/assert without changing logic of the program and affect the testing)

**Comment by brendandahl** [comment]
> We need to review code and change assert(_,?)

Just to clarify on this one, do you mean keep assert() for proper uses, but change other assert's to throw?

**Comment by yurydelendik** [comment]
> Just to clarify on this one, do you mean keep assert() for proper uses, but change other assert's to throw?

Correct. We will keep assert() for proper uses.

Also since we cannot just simply abort the app, let's keep throwing inside assert() for now. However it will be nice to see `process.exit(1)`, `worker.terminate()` or at least `while(1);` :)

**Comment by Snuffleupagus** [comment]
> Introduce InvalidPDFError() to raise when PDF is malformed instead of generic Error()

We already have a similarly named `InvalidPDFException`, as defined in [src/shared/util.js#L425](https://github.com/mozilla/pdf.js/blob/93420545024b1879b8d92cd9d3741c1727bc090d/src/shared/util.js#L425), which is currently thrown if we're unable to recover a valid XRef table; please see [src/core/obj.js#L1130](https://github.com/mozilla/pdf.js/blob/93420545024b1879b8d92cd9d3741c1727bc090d/src/core/obj.js#L1130).

> There is lots of confusion how error() is used.

Unless your intention to reuse the existing `InvalidPDFException`, we probably ought use a name that's not too similar to avoid real confusion here :-P

**Comment by yurydelendik** [comment]
> We already have a similarly named InvalidPDFException

InvalidPDFException wfm

**Comment by yurydelendik** [comment]
adding `unreachable(msg)`, which is just a shortcut for `assert(true, msg)`
