### ISSUE TITLE
Question about output of PDF

### ISSUE THREAD

**Issue by hirokiAoyama** [mozilla/pdf.js#8514]
Dear all,

I am Hiroki, working at software house in Tokyo, Japan.

I would appreciate it if you could give me advice on
how to apply "PDF.js" to the program source 
using ServletOutputStream for client response.

But please note that this system is not acceptable to
GET command on HTTP for the security reason.

I would like to hear the answer until July 15.

Best regards,

Hiroki

**Comment by yurydelendik** [comment]
See SO answers on how deliver PDF data using ServletOutputStream (e.g. https://stackoverflow.com/questions/24702258/how-to-display-pdf-in-web-browser-using-servletoutputstream) and also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr . Closing as answered.
