### ISSUE TITLE
Lib weight

### ISSUE THREAD

**Issue by julienR2** [mozilla/pdf.js#8518]
Hi !

Sorry for not following the guidelines, but I don't think it applies here since is more of a lib issue itself.

After running a webpack build with prod and aot enabled, I inspected the bundle with source-map-explorer and realize the lib weight 800kb (in my case 25% of the bundle) increasing my bundle size from 1.2 Mb to 2Mb.

So I was wondering what could cause this lib to be some heavy ? It's probably not a problem for desktop user, but can quickly be a trouble for mobile users..

Any though or idea about getting the lib lighter ?

Thanks for your help and for this lib !

**Comment by yurydelendik** [comment]
> Any though or idea about getting the lib lighter ?

PDF is not simple format -- spec is over 750 pages and it includes more other similar formats. If you use subset of PDFs and you know which features of PDF spec is used, you can disable and remove that from the lib. For example, if your PDF generator does not produce JBIG2, JPX or does not use CFF fonts, you can remove code that supports that. If your code needs to work only on new browsers, remove portion of compatibility.js. If you don't need SVG rendering, you can remove that too.

> , I inspected the bundle with source-map-explorer and realize the lib weight 800kb (in my case 25% of the bundle) increasing my bundle size from 1.2 Mb to 2Mb.

PDF.js split into two parts: core and display layers. The display layer is smaller part of the library and about 227K minified, this part is required to be on main page, and page start up time shall not be affected by it. There is the core part (~689K)  that is loaded by demand just before getDocument call into a web worker. The webpack can efficiently split core/display code between several file (see examples/webpack). Please notice that using pdf.combined.js is not efficient solution and we don't recommend it.

> It's probably not a problem for desktop user, but can quickly be a trouble for mobile users..

PDF.js was used for Firefox OS and is used for mobile devices as well -- the known issues on mobile device is canvas size and absence of natural zooming and not the PDF.js size.

Closing as answered.

**Comment by julienR2** [comment]
Thanks for you answer !
Yes I understand PDF is a quite complex format. I'll try to work with it.
Thanks for these information 👍

**Comment by GauravThakur03** [comment]
Try Adobe Embed APIs: https://www.adobe.com/devnet-docs/dcsdk_io/viewSDK/index.html
- Much smaller
- Easy to integrate
- Much better PDF View quality
- Lots of PDF features
