### ISSUE TITLE
Samsung Galaxy S7: Can not download pdf file

### ISSUE THREAD

**Issue by dlyahov** [mozilla/pdf.js#8521]
Link to PDF file (https://mozilla.github.io/pdf.js/web/viewer.html):

Configuration:
- Web browser and its version: Chrome v58.0.3029.83
- Operating system and its version: Samsung Galaxy S7, Android 7.0
- PDF.js version: 1.8.444
- Is an extension: Download manager

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Click on 'Download'

What is the expected behavior? (add screenshot)
Pdf file is downloaded

What went wrong? (add screenshot)
Downloaded failed due
![screenshot_20170613-132100](https://user-images.githubusercontent.com/8529665/27078287-ce42c1e0-503b-11e7-894a-ef439c4d65f7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by dlyahov** [comment]
Are there any updates on this issue?

**Comment by Snuffleupagus** [comment]
Given that this issue seem to be specific to a *particular* browser/platform, it's not at all clear that this is actually a valid bug for the PDF.js library/viewer.

> Is an extension: Download manager

It's not clear what this means, but there's been other issues about various "Download Mananger"-software interfering with and breaking PDF.js; that cannot be fixed here and the issue thus appear to be INVALID.
