### ISSUE TITLE
how to implement edit ?

### ISSUE THREAD

**Issue by rotencode** [mozilla/pdf.js#8523]
hi, thanks for your great works. 
I'm trying to implement simple edit operations for the sample viewer.html.

I try to insert a DOM into textlayer,but don't showed up. any suggestions? 

thanks.

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#is-it-possible-to-add-annotations-to-a-pdf

**Comment by timvandermeij** [comment]
Closing since PDF.js does not offer edit capabilities. You could make it work, but it's out of scope for us to work on.
