### ISSUE TITLE
DOM events called multiple times for each occurrence of PDFJS.webViewerLoad()

### ISSUE THREAD

**Issue by curiosity26** [mozilla/pdf.js#8524]
Link to PDF file (or attach file here):
Any PDF causes this issue

Configuration:
- Web browser and its version: Chrome 58
- Operating system and its version: Mac OS X 10.12.5
- PDF.js version: 1.8.448
- Is an extension: No

Steps to reproduce the problem:
1. Configure PDF.js in a single page app
2. Configure a way to generate a DOM element to render the PDF.js viewer by calling `PDFJS.webViewerLoad(url)`
3. Configure a way to destroy the the DOM element
4. Toggle on the Element
5. Click Download - 1 document should download
6. Toggle the element off and on again
7. Click Download - 2 documents download
8. Repeat Steps 6 and 7, another document downloads with each call of `PDFJS.webViewerLoad(url)`

What is the expected behavior? (add screenshot)
Only one PDF should download each time

What went wrong? (add screenshot)
Multiple PDF's downloaded

**Comment by yurydelendik** [comment]
What's PDFJS.webViewerLoad? We are exposing PDFViewerApplication which has open() method to accomplish the same.

**Comment by curiosity26** [comment]
I apologize, I was looking at an angular script that wraps the PDFJS library.

The call is actually: `PDFViewerApplication.run(config)`

**Comment by yurydelendik** [comment]
This issue looks out of scope of this project. I'll close it. (PR #8525 sounds like a good idea, but require more work) I'm thinking this issue similar to #8402, so this one can be addressed but fixing it.
