### ISSUE TITLE
How I can load all contents When I used this plug In web app just once? 

### ISSUE THREAD

**Issue by huangche007** [mozilla/pdf.js#8526]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since the lack of *any* details makes it impossible to understand what's being asked here. (Please fill out the issue template with all the relevant information when opening an issue.)
