### ISSUE TITLE
How to disable pdf file download by pressing ctrl + s

### ISSUE THREAD

**Issue by recived** [mozilla/pdf.js#8530]
How to disable the download of files by pressing ctrl + s in the standard pdf viewer or replace it with the download of the html page? Thanks. 
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by yurydelendik** [comment]
There is no useful data on the html page, so it's not worth to saving it. Closing as won't fix.

**Comment by sapq** [comment]
use css 

    display: none;

<button id="download" style="display: none;">
</button>

**Comment by recived** [comment]
Can close. Commented the line downloadManager.download (blob, url, filename) in app.js, and now you can not load it with ctrl + s.

**Comment by ILMLOYS** [comment]
@recived Thanks
