### ISSUE TITLE
loadingBar progress and  glimmer

### ISSUE THREAD

**Issue by sapq** [mozilla/pdf.js#8532]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: chrome , Firefox
- Operating system and its version: windows 7
- PDF.js version: last one
- Is an extension:

Steps to reproduce the problem:
1.  loadingBar progress and  glimmer
2. i want show loadingBar progress  not glimmer 
how  i make pdf.js show loadingBar progress 

What is the expected behavior? (add screenshot)

![prossbar](https://user-images.githubusercontent.com/8040862/27193903-408823de-5209-11e7-942a-55b16427f5b8.jpg)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Not enough information is provided. http://mozilla.github.io/pdf.js/web/viewer.html works for me. Looks like PDF.js demo viewer is embedded in some web site (probably some custom version). Closing as incomplete.

**Comment by sapq** [comment]
The information is clear why you close my topic ????

this is not fair

**Comment by yurydelendik** [comment]
> The information is clear why you close my topic ????

Please provide link to the web site you having problem with (for HTTP header diagnostics).

> this is not fair

The contributors need all information and more to troubleshot the issue. Holding details of the problems is not fair to them.

**Comment by sapq** [comment]
ok this my website : http://www.hululkitab.com/1784-2/

**Comment by sapq** [comment]
how i fix this problem ?? 

i want show loadingBar progress

**Comment by yurydelendik** [comment]
If you open network monitor you will see that Content-Length is missing for PDF xhr:

<img width="1144" alt="screen shot 2017-06-15 at 12 43 51 pm" src="https://user-images.githubusercontent.com/1523410/27194520-751713e4-51c8-11e7-9cd5-63b12f75a6e6.png">

Make sure that your HTTP server returns Content-Length HTTP header.

Also you may want to disable gzip encoding to enable range requests.

**Comment by sapq** [comment]
ok thank you
