### ISSUE TITLE
Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#8538]
Why do I get this in the console: `Deprecated API usage: getDocument is called with pdfDataRangeTransport, passwordCallback or progressCallback argument`

```
PDFJS.getDocument(pdf_url, null, null, transfer_progress).then(function(pdf){
	// load pdf
});

function transfer_progress(progress){
	var percent = parseInt(progress.loaded / progress.total * 100);
	$('#'+transfer_id).css('width', percent+'%');
}
```

If I only pass `pdf_url` to `getDocument` the message disappears

```
PDFJS.getDocument(pdf_url).then(function(pdf){
	// load pdf
});
```

**Comment by timvandermeij** [comment]
The `getDocument` API call has been simplified in the sense that less parameters need to be passed. If you want to have progress information, you can set `onProgress` on the loading task. This change is introduced in https://github.com/mozilla/pdf.js/commit/5135aa9becc15a79a565ddf33452e2351196bd5b and https://github.com/mozilla/pdf.js/commit/5135aa9becc15a79a565ddf33452e2351196bd5b#diff-dd42e9b2d2a652b8e312efa567698aa6 shows how it should be used now (and how it's used in the current default viewer).

**Comment by clarkk** [comment]
could you please show in my example how to use it?

**Comment by timvandermeij** [comment]
Note that this is untested, but I think it would be:

```javascript
let loadingTask = PDFJS.getDocument(pdf_url);
loadingTask.onProgress = function transfer_progress(progress) {
  var percent = parseInt(progress.loaded / progress.total * 100);
  $('#'+transfer_id).css('width', percent+'%');
}
loadingTask.promise.then(function(pdf) {
  // load pdf
});
