### ISSUE TITLE
pdfview not working in safari

### ISSUE THREAD

**Issue by thiyagarajanvss** [mozilla/pdf.js#8541]
Link to PDF file (or attach file here):
![safari-issue](https://user-images.githubusercontent.com/13113636/27281389-4be250bc-5509-11e7-85d6-d92c3c5d6856.png)

Configuration:
- safari 5.1.7():
https://mozilla.github.io/pdf.js/web/viewer.html   - pdefview not working in safari

**Comment by Rob--W** [comment]
The console shows the following error: "cannot declare a parameter href in strict mode".

Looks like a bug in Safari.

**Comment by thiyagarajanvss** [comment]
what i have to  do to solve this isssue

**Comment by Rob--W** [comment]
I submitted a patch at #8544. I confirmed that the viewer works again in Safari 5.1 with that patch.

**Comment by thiyagarajanvss** [comment]
![safari-issue](https://user-images.githubusercontent.com/13113636/27285999-42c0b844-551c-11e7-8253-793fe2357c6a.png)
