### ISSUE TITLE
Render whole textLayer without scrolling

### ISSUE THREAD

**Issue by stefanos113** [mozilla/pdf.js#8545]
Hello!

How do I configure the [pdf,js standard viewer](https://mozilla.github.io/pdf.js/web/viewer.html) to render all pages without waiting for the user to scroll down to the different pages so that pdf.js renders the pages? I know about the possibility to extract the text from the pdf, but I really need the textLayer.

My use case:
I need the whole 'textLayer' for all pages, because I analyze the words given in the layer and highlight some of them (the ones which satisfy my defined rules) by putting them in a span: `<span class="highlight selected">word</span>`.

Thank you in advance!

**Comment by yurydelendik** [comment]
> I need the whole 'textLayer' for all pages,

See e.g. https://stackoverflow.com/a/40662025/1765767

> by putting them in a span: <span class="highlight selected">word</span>.

It's a small project by itself -- you need to modify viewer to modify text layer out to add these spans. There is no easy answer here and you need start looking at the https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js and/or https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js to modify that. Good luck.

Closing as answered.

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages about rendering all pages in the demo viewer.

**Comment by kuiran** [comment]
i also want to know it,if you know how to solve it,please tell me

**Comment by MikeBeaton** [comment]
I also want to highlight selected words. I got that working on a different document viewer by trapping the jQuery `html` function ([following this SO answer](https://stackoverflow.com/a/10742069/795690)) so that I could redo the highlighting after any changes to the DOM. I don't think that can apply here. Still, it should be possible to get a callback each time a new page is loaded. If anyone can drop a quick line how to do that, great; if I find out how to I'll happily edit this.

**Comment by stefanos113** [comment]
Just listen for the textlayersrendered event. What I do is iterating over the pages and saving the text content by reading out the textlayers. Then I have all the text with position (page number and div id where the text is located). An algorithm chooses then which words should be highlighted. I save that Information and each time when the textlayersrendered event fires, I annotate the desired words by putting spans inside the corresponding divs wehre the word is located.

**Comment by MikeBeaton** [comment]
Thanks @stefanos113. Here's some working simple example code:
``` javascript
  document.addEventListener('textlayerrendered', function (event) {
    // This generates an event for each text layer once when it is added.
    // You can highlight directly here, e.g. using jquery-highlight library:
    $(event.target).highlight("information");
  });
```
Perhaps worth pointing out that the approach suggest by the original question and our comments ignores the [highlighting which pdf.js already provides for searches](https://mozilla.github.io/pdf.js/web/viewer.html#search=information%20code%20runtime%20collaboration%20false%20value), so there might be a much more official way to do this!?
