### ISSUE TITLE
SVG: arabic codepoints lost

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#8546]
After creating SVG pages from an arabic PDF the glyphs are not related to arabic codepoints.
If I copy/paste the text from the SVG - the result are mojibake.

Steps to reproduce:
PDF: [r2l.pdf](https://github.com/mozilla/pdf.js/files/1085907/r2l.pdf)

````
npm install
gulp dist-install
node examples/node/pdf2svg.js /tmp/r2l.pdf
````
Open the svgdump/*.svg files and copy/paste the text to an editor.

**Comment by Rob--W** [comment]
I guess that this requires us to transform all characters to the unicode point as defined in the unicode map, and recreate the embedded font data such that the glyph correspond to the new unicode points.

Especially the latter probably takes some effort.

**Comment by doublex** [comment]
The "html" backend works perfectly: Copy+Paste are arabic codepoints.

**Comment by yurydelendik** [comment]
the generated .svg does not contain text layer and pdf2svg has no capabilities to generate text layer html for .svg. marking as a feature request.

**Comment by doublex** [comment]
$ 250 bounty:
https://www.bountysource.com/issues/46379893-svg-arabic-codepoints-lost

**Comment by denim2x** [comment]
Hi - guess I should be able to integrate some third-party code that's better at *pdf->svg*

**Comment by brendandahl** [comment]
> I guess that this requires us to transform all characters to the unicode point as defined in the unicode map, and recreate the embedded font data such that the glyph correspond to the new unicode points.

We should be doing this already https://github.com/mozilla/pdf.js/blob/ad74f6e7410420dc6ae27edc863a2ef906d77b57/src/core/fonts.js#L731, but it can fail in certain cases.

**Comment by doublex** [comment]
@brendandahl 
The "html output" works perfectly.

**Comment by yurydelendik** [comment]
@doublex just to be clear, PDF.js does not perform any SVG text conversion, it builds image, that means there is no guarantee glyph code match. As PDF spec suggests, and uses different algorithm for it, use text layer (same as html output uses) to extract text.

**Comment by yurydelendik** [comment]
I'll close this issue since it's getting to be confusing, based on comments from @brendandahl and @denim2x . I think OP did not provided enough information, e.g. to specify a expected/actual result. Closing as incomplete.

**Comment by doublex** [comment]
I would pay $500 for a patch.
Is there anything I can do?
