### ISSUE TITLE
pdf.js and the sha1 algorithm

### ISSUE THREAD

**Issue by hdruppert** [mozilla/pdf.js#8548]
I think pdf.js dosn't support the sha1 algorithm.
I have only the question: is it ever used and if yes since what version is it removed?

**Comment by Snuffleupagus** [comment]
Since an identical question was asked in https://stackoverflow.com/q/44629914/5317012, closing as answered by [https://stackoverflow.com/a/44632308/5317012](https://stackoverflow.com/a/44632308/5317012).[1]

---
[1] Note that the person who wrote that answer is one of the PDF.js devs.
