### ISSUE TITLE
Blank page at end

### ISSUE THREAD

**Issue by Sterbina** [mozilla/pdf.js#8550]
Link to PDF file (or attach file here):
https://www.dropbox.com/s/6dj7ew27dseo7bn/Test_Test_20_06_2017.pdf?dl=0

Configuration:
- Web browser and its version: Integrated in Electron App and tested on Chrome Version 59.0.3071.104
- Operating system and its version: Windows 10 ver. 1703
- PDF.js version: 1.7.225 (Stable), tried even Beta (1.8.188) or built latest repo
- Is an extension: No

Steps to reproduce the problem:
1. Clicked on Print Icon
2. Selected Microsoft Print to PDF or normally printed

What is the expected behavior? 
Expected behavior would be to print this document without blank page at the end

What went wrong? 

![screenshot 2017-06-20 14 42 00](https://user-images.githubusercontent.com/26405202/27333600-b3911208-55c6-11e7-8851-979ee24e1841.png)

When I try to print a document I get what you can see on screenshot.

I don't know why it's happening. I tried change print styles, resolution, explored issues here, even modified PDF but nothing helped. Interesting is that one of my PDFs prints as it is so I don't get what's happening.

**Comment by Sterbina** [comment]
Please, can anyone comment this issue, is it in solving or is it problem specific on our side?

**Comment by ousia** [comment]
@Sterbina, I’m not a developer, but I have two guesses (on what happens) and a request.

The request is: please, attach the PDF document to the issue ([your url](https://www.dropbox.com/s/6dj7ew27dseo7bn/Test_Test_20_06_2017.pdf?dl=0) gives a warning about a non-existing resource).

Your image shows that the page isn’t a pure blank page, but it has a minimal dark green line on its top border. The unintended extra page has contents. My guesses are:

* It might be that the PDF document defines an the bottom green frame with some part outside the page boundaries.

* PDF.js may be printing the part outside the page margins in the next page.

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here):
> https://www.dropbox.com/s/6dj7ew27dseo7bn/Test_Test_20_06_2017.pdf?dl=0

That link is no longer available, and given that there's already similar issues tagged with `4-printing` I'd suggest closing this one as INCOMPLETE.
