### ISSUE TITLE
Remove stick on the top for toolbar

### ISSUE THREAD

**Issue by paloir** [mozilla/pdf.js#8551]
Hello, 

Is it possible to rmeove the stick for the toolbar ?

Example on my website : https://catalogue.gkip.fr/test/lecteur.html?file=pdf/aigostar.pdf

I've menu on the top, but it's invisible. 

Thx !

**Comment by yurydelendik** [comment]
> Is it possible to rmeove the stick for the toolbar ?

Add "display: none" for the stick HTML element CSS property.

Closing as answered.

**Comment by paloir** [comment]
Thank you but I want to see my menu when the load page.

With firefox, it's good : 
https://catalogue.gkip.fr/test/ok.PNG
Buit with chrome : 
https://catalogue.gkip.fr/test/notok.PNG

Thanks
