### ISSUE TITLE
Viewer.html does not work in IE11

### ISSUE THREAD

**Issue by jeffreywyp** [mozilla/pdf.js#8553]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:IE 11
- Operating system and its version:Win 7
- PDF.js version: latest version
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
I got JS error message "Promise is undefined" when i open the viewer.html in download package.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Looks like you are trying to use github repo source code as it without building the code. Use http://mozilla.github.io/pdf.js/getting_started/#download package. Non-built version for developers is not supported on very old platforms. Closing as answered.
