### ISSUE TITLE
Incorporating forms into web viewer

### ISSUE THREAD

**Issue by LubenZA** [mozilla/pdf.js#8554]
Hi,

I am using the default viewer but some of my PDF's contain and need to display dropdowns/textbox/etc. I was hoping someone could guide me on how to enable the form elements  in the main default viewer. 

I am using this fork to display the form elements:
https://github.com/mainegreen/pdf.js/tree/master/examples/forms
My question is how do I combine this in the main viewer?

Thanks.

**Comment by yurydelendik** [comment]
Forms are not fully implemented yet, please follow https://github.com/mozilla/pdf.js/projects/1 . There is the [renderInteractiveForms](https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L18) preference to turn on forms support in the demo viewer, you can use that. Closing as answered.

**Comment by LubenZA** [comment]
Perfect thank you Yury!
