### ISSUE TITLE
node svg example double-encodes element attributes

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#8558]
https://github.com/mozilla/pdf.js/blob/9bed695ebde488b49d39290087f72ba224bd1078/examples/node/domstubs.js#L84-L87
```javascript
  setAttributeNS: function DOMElement_setAttributeNS(NS, name, value) {
    value = value || '';
    value = xmlEncode(value);
    this.attributes[name] = value;
```

https://github.com/mozilla/pdf.js/blob/9bed695ebde488b49d39290087f72ba224bd1078/examples/node/domstubs.js#L105

```javascript
      buf.push(' ' + i + '="' + xmlEncode(this.attributes[i]) + '"');
```

One of the two should be removed. Most likely the first one, because `getAttributeNS`'s implementation just returns `this.attributes[i]`, and that should not be encoded.

**Comment by yurydelendik** [comment]
Can we replace our stubs with [jsdom](https://www.npmjs.com/package/jsdom) / [jsdom-global](https://www.npmjs.com/package/jsdom-global)?

**Comment by Rob--W** [comment]
I think that it's better to not do that. We use a very limited subset of the DOM, so it is relatively easy to implement and optimize the stubs for our use case; jsdom seems overkill for us. Also, our example currently does not have any external module dependencies, which simplifies testing (though this is a very minor point).
