### ISSUE TITLE
Improve PNG encoder in display/svg.js to generate smaller PNG files 

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#8560]
One of the reasons for the out-of-memory crash at #8434 is that PDF.js generates very large data-URLs.
The 2MB PDF file (https://github.com/mozilla/pdf.js/files/1021334/invalidstringlength.pdfhttps://github.com/mozilla/pdf.js/files/1021334/invalidstringlength.pdf) results in a 265MB SVG file (after applying #8557 to even be able to generate the file).

I extracted the first data-URL. It is an almost fully transparent image, with the light-colored text "DIE MESSE DER KIRCHE", which appears at the center of the PDF file. The PNG file (after base64-decoding) is 28MB. When I use pngcrush to compress it, I am able to get a file size that is about a thousand times smaller (32KB).

So surely there must be opportunity to improve our (naive?) PNG generation method at https://github.com/mozilla/pdf.js/blob/9bed695ebde488b49d39290087f72ba224bd1078/src/display/svg.js#L34-L224

I digged up the following specs, which are probably relevant:

- http://www.libpng.org/pub/png/spec/1.2/PNG-Contents.html
- http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
- http://www.libpng.org/pub/png/spec/1.2/PNG-Compression.html
- https://tools.ietf.org/html/rfc1950.html
- https://tools.ietf.org/html/rfc1951.html

**Comment by yurydelendik** [comment]
There is no easy way to implement an encoder for PNG (except in a browser we can use canvas and toDataURL).

I wonder if we can use some simple module such as 'zlb' for node.js and extend code at https://github.com/mozilla/pdf.js/blob/9bed695ebde488b49d39290087f72ba224bd1078/src/display/svg.js#L171-L195 , so if DEFLATE compression present on platform use it.

**Comment by doublex** [comment]
Another testcase (`node` was killed by the kernel):
http://doppelbauer.name/oom-killed.pdf

Console:
````
# PDF "/tmp/1.pdf", 575 pages
# Load page 1, 293x454
Warning: Unimplemented operator setTextRenderingMode
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
# Save page: "/tmp/svg/000000001.svg"

[...snip...]

# Load page 221, 293x454
Warning: Unimplemented operator setTextRenderingMode
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Warning: Unimplemented operator dependency
Killed

dmesg:
[1199004.806807] Out of memory: Kill process 14310 (node) score 608 or sacrifice child
[1199004.806820] Killed process 14310 (node) total-vm:8279704kB, anon-rss:4273868kB, file-rss:0kB
````

**Comment by timvandermeij** [comment]
The problem should be fixed for Node.js now, but we're keeping this open to track inclusion of `pako` to hopefully solve this for both Node.js and browsers. Note that the latter should also help in terms of performance for the SVG project at https://github.com/mozilla/pdf.js/projects to potentially use the SVG back-end for printing.
