### ISSUE TITLE
Pdf.js Annotations

### ISSUE THREAD

**Issue by kbaranovska** [mozilla/pdf.js#8562]
Hi, maybe it isn't proper channel to ask - but I am interested in implementing Pdf.js Annotations for pdf.js viewer, but can't find examples how to do it correct. I saw some implementations and supporting several types of annotation in the github repo. Are there any description how to integrate annotations in viewer?

Thank you.

**Comment by timvandermeij** [comment]
Take a look at the example at https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L50. It activates the annotation layer when drawing the canvases. If you use the default viewer as a base, there is https://github.com/mozilla/pdf.js/blob/master/web/annotation_layer_builder.js.
