### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by waeladaming** [mozilla/pdf.js#8563]
http://www.projets-en-cours.com/wwwokok/fr-FR/FR_YR_ACT_BEAUTIFUL.pdf

Configuration:
- Web browser and its version: safari on Ipad and Safari on Iphone
- Operating system and its version:
- PDF.js version: 1.8
- Is an extension: 
Error
Uncaught (in promise) Error: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
  Loading pdfjs-web/app.js
t @ system.js:14
(anonymous) @ system.js:1415

**Comment by yurydelendik** [comment]
Similar to #8553. The developers (non-built) version of the demo viewer might not work on certain legacy browsers. Use pre-built version to deploy on ipad/iphone. Closing as answered (and won't fix)
