### ISSUE TITLE
scale is not working as expected

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#8568]
I want to calculate the scale so my canvas will have a specific height of `400px`, but the scale is not working as expected

I calculate the height like this

```
var canvas_height = 400;
var scale = canvas_height / page.getViewport(1).height;
```

Then I pass `scale` to pdfjs but the canvas ends up with `height:534px` ?

**Comment by alafr** [comment]
Maybe because the page height is in PDF points and the canvas is in pixels?
`1px = 0.75pt` and  `1pt = 1.33333px`

**Comment by yurydelendik** [comment]
> var scale = canvas_height / page.getViewport(1).height;
@clarkk what about canvas_width? try `var scale = Math.min(canvas_width / page.getViewport(1).width, canvas_height / page.getViewport(1).height);` (See also https://stackoverflow.com/questions/44547585/generating-thumbnail-of-a-pdf-using-pdf-js/44548566#44548566)

**Comment by yurydelendik** [comment]
eh, var scale =  page.getViewport(1).height / canvas_height;

Closing as answered.

**Comment by clarkk** [comment]
@yurydelendik 

What is the answer? 

This gives a scale larger than 1.. I want it must be smaller than 1 (downscale)

```
var scale = page.getViewport(1).height / canvas_height;
```

**Comment by yurydelendik** [comment]
> This gives a scale larger than 1.. I want it must be smaller than 1 (downscale)

>> var scale = page.getViewport(1).height / canvas_height;

Agree, updated snippets.

The working example was provided at https://stackoverflow.com/questions/44547585/generating-thumbnail-of-a-pdf-using-pdf-js/44548566#44548566 -- if your custom solution still has issue see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md

**Comment by clarkk** [comment]
ok.. `1px = 0.75pts` :)
