### ISSUE TITLE
.pdfViewer .page .loadingIcon does not disappear

### ISSUE THREAD

**Issue by leolux** [mozilla/pdf.js#8569]
Link to PDF file (or attach file here):
http://cdn.mozilla.net/pdfjs/tracemonkey.pdf

Configuration:
- Web browser and its version: Chrome Version 59.0.3071.109
- Operating system and its version: Windows 10
- PDF.js version: [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 1.8.476)
- Is an extension: no

Steps to reproduce the problem:
1. Use the code from the example "mobile-viewer"
2. Open viewer.js and change the DEFAULT_URL to http://cdn.mozilla.net/pdfjs/tracemonkey.pdf

What is the expected behavior?
Not only the loadingBar gets hidden after loading, but also the loadingIcon.

What went wrong? (add screenshot)
The loadingIcon (a spinner in this example) keeps displaying although the loadingTask has finished loading the PDF and all pages are visible.
BTW: This example produces the following error message: pdf.worker.js:24497 Refused to get unsafe header "Accept-Ranges".
I thing this issue is cause by missing headers on the server http://cdn.mozilla.net when following https://github.com/mozilla/pdf.js/issues/8566

Does the issue with the loadingIcon depend on the issue with range requests?

**Comment by Snuffleupagus** [comment]
> Not only the loadingBar gets hidden after loading, but also the loadingIcon.

I cannot reproduce this, and furthermore the `.loadingIcon` CSS class is toggled from within the `PDFPageView` code[1]. Hence if this was generally broken the default viewer would be affected as well, and there hasn't been any other similar reports (as far as I can tell).

Given the above, and the age of the issue itself, should this issue simply be closed now?
/cc @timvandermeij 

---
See https://github.com/mozilla/pdf.js/blob/d614cabfa099841b89646932a907102759fdaea6/web/pdf_page_view.js#L200-L202 and https://github.com/mozilla/pdf.js/blob/d614cabfa099841b89646932a907102759fdaea6/web/pdf_page_view.js#L450-L453
