### ISSUE TITLE
Some Japanese characters do not render

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#8570]
Link to PDF file (or attach file here): 
[boxViewerで平仮名カタカナ句読点が抜けるPDF_Chrome印刷でPDF (1).pdf](https://github.com/mozilla/pdf.js/files/1098673/boxViewer.PDF_Chrome.PDF.1.pdf)

Configuration:
- Web browser and its version: Chrome Version 59.0.3071.104 
- Operating system and its version: Mac OS Sierra 10.12.5
- PDF.js version: Latest (in viewer.html demo)
- Is an extension: No

Steps to reproduce the problem:
1. Go to pdf.js web viewer demo (https://mozilla.github.io/pdf.js/web/viewer.html)
2. View attached PDF

What is the expected behavior? (add screenshot)
Should look like printed version of website: https://www.konicaminolta.jp/about/research/future/3dlr/

What went wrong? (add screenshot)
Only Chinese characters show
![2017-06-23_11-27-23](https://user-images.githubusercontent.com/689351/27495491-eb019a72-5806-11e7-9517-b122af5f30b3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

Additional notes:
Re-printing the web page as PDF seems to work in some situations in pdf.js, but the attached file does render properly in Mac Preview & Chrome's PDF viewer - is there a missing cmap or something?

**Comment by tonyjin** [comment]
Confirmed fix on my end. Thanks @brendandahl @Snuffleupagus!

**Comment by DILEEPKUMAREBIX** [comment]
Japanese characters are not loading in IE browser with latest **pdfjs-2.6.347-es5-dist**.

Where as same PDF displaying good in all other browser including EDGE.

Getting below warning message in console.

PDF 9a16c1e2adbc4e44af1ed7dedb359d9d [1.4 Adobe PDF Library 10.0 / Acrobat PDFMaker 10.1 for Word] (PDF.js: 2.6.347)
Warning: Load test font never loaded.
Warning: Load test font never loaded.

**Comment by THausherr** [comment]
You're posting to a closed issue. Please open a new one and include your PDF.
