### ISSUE TITLE
Units and translation

### ISSUE THREAD

**Issue by SPlatten** [mozilla/pdf.js#8573]
I am trying to work out what units the PDF is using, I want to translate the information into mm.

I'm using a module called pdf2json which as far as I can tell is based on PDF.js, I think this node module is no longer supported as there doesn't seem to be any feed back from the author in recent months....here is my post which I hope will mean something to people here and hopefully someone can help me....please?

https://github.com/modesty/pdf2json/issues/133

**Comment by yurydelendik** [comment]
Support of pdf2json is out of scope of this project. But based on https://stackoverflow.com/questions/42494394/pdf2json-page-unit-what-is-it, it's about 24px. Converting px to mm is device specific and purely subjective. Closing as answered.
