### ISSUE TITLE
[renderTextLayer] Decouple computation and DOM operations

### ISSUE THREAD

**Issue by ghetolay** [mozilla/pdf.js#8575]
Currently `renderTextLayer` will **compute** the different properties (left, top, font-style, scale...) **using `canvas.measureText()`** and **build** the result view using vanilla DOM operations.

I'm working on an Angular PDF viewer based on pdf.js engine and not just a dummy wrapper. 
I would like to know if it possible to either : 
  1) abstract those DOM operations inside `renderTextLayer`
  2) to extract the computation part so we could build our own `renderTextLayer`. 

`1)` would most certainly result in an API break, while `2)` could be contained on internal stuff and new API.

I can see at least 2 benefits : 
  - We could avoid the DOM rebuild and just update the style of existing nodes on certain cases (when we zoom on the page for example).
 - We *should** be able to make this work with server side rendering. (* still not sure about how to handle `measureText()` on node).

I will propose one or several implementation if you approve the idea.

**Comment by yurydelendik** [comment]
> I will propose one or several implementation if you approve the idea.

@ghetolay it is a good idea, but keep in mind the issue measureText is solving. It is giving exact width of text for the mapped standard browser fonts, and here is why it is done this way:

1. in PDF format, extracted text and glyph display algorithms are using different paths, so glyphs will have different metrics than extracted text (example glyphs `ﬁle` is not the same as extracted `file` -- the former is using ligature)
2. browser font metrics are hard to extract to be using off main thread (e.g. in the worker or node)
3. or, providing know fonts cost memory/storage.

There is no specific criteria for closing this issue. Please refine issue to include plan to specify that and concrete plan for closing this issue.

**Comment by yurydelendik** [comment]
> We could avoid the DOM rebuild and just update the style of existing nodes on certain cases (when we zoom on the page for example).

It's possible to do and can be done unrelated to this issue.

**Comment by ghetolay** [comment]
I know `measureText` will be challenging but I hope I could manage something at least for my use case which is specific.
I'll look more deeply on the code and try to find a way to abstract those without significant perf impact and breaking change. So even if we can't compute text size otherwise it shouldn't matter much.

> We could avoid the DOM rebuild and just update the style of existing nodes on certain cases (when we zoom on the page for example).
It's possible to do and can be done unrelated to this issue.

Yeah totally but I was thinking angular, if I can get angular manage the DOM it'll do it for me.
If this is not too much challenging I'll look into that.

Not sure I'll have much time soon but I'll do it sooner or later :)

**Comment by ghetolay** [comment]
So here is how I plan to do it, I would remove `container` and `textDivs` parameters and add :
- `textMesurer` a class to get the text width, with a dom implementation using a canvas.
- `renderTextCallback` a callback called for each text node with a dom implementation that creates a div and set it's style. (need probably better naming).

I choose a callback that get called for each text rather than a callback that would get called once with an array of text because we can either have a sync text content or a text content stream. This solution seems to works well with both case. 
We could also return a stream instead of using a callback input, that's how I would do it in a personal project using observables, but I don't know the status of streams in this project. Looks like it's only used when web workers are involved.

Here is the types of theses new parameters : 
```js
/** Text Mesurer
 * @typedef {Object} TextMesurer 
 * @method 
 *   @name TextMesurer#getWidth
 *   @param {string} text
 *   @param {string} fontFamily
 *   @param {number} fontSize
 *   @returns {number} width of the rendered text
 */

/**
 * Text layer render parameters.
 *
 * @typedef {Object} TextLayerRenderParameters
 * @property {TextContent} textContent - (optional) Text content to render
 *   (the object is returned by the page's getTextContent() method).
 * @property {ReadableStream} textContentStream - (optional) Text content
 *   stream to render (the stream is returned by the page's
 *   streamTextContent() method).
 * @property {PageViewport} viewport - The target viewport to properly
 *   layout the text runs.
 * @property {Array} textContentItemsStr - (optional) Strings that correspond
 *   the `str` property of the text items of textContent input. This is output
 *   and shall be initially be set to empty array.
 * @property {number} timeout - (optional) Delay in milliseconds before
 *   rendering of the text  runs occurs.
 * @property {boolean} enhanceTextSelection - (optional) Whether to turn on the
 *   text selection enhancement.

// new stuff here //
 * @property {TextMesurer} textMesurer - An object responsible of 
 *   rendered text measurement
 * @property {callback} renderTextCallback - A callback used to render text 
 *   (called for each text node)
// params may evolve //
 *   @param {string} text
 *   @param {object} textProperties (exact properties to be defined)
 *   
 */

/**
 * Starts rendering of the text layer.
 *
 * @param {TextLayerRenderParameters} renderParameters
 * @returns {TextLayerRenderTask}
 */
function renderTextLayer(renderParameters) { }
```

For now we'll still rebuild the divs every time, I'll do the optimization in a separate PR. But I can already see that I'll probably take advantage of the callback and submit a different one depending on the situation (rebuild / update).

Since this is already a breaking change I think we could also rename `renderTextLayer` as it's not really rendering anymore but delegating it to the callback.

**Comment by ghetolay** [comment]
Should I just start the PR ?

**Comment by FabianTe** [comment]
@ghetolay Very interesting conversation right here! 👍 
I am researching on how to use the text layer computation of PDF.js since it performs better that other solutions like Apache PDFBox IMO. I actually only what the coordinates and dimensions of the text of the PDF.

How have you proceeded with this topic, is there something you could share? 😉

**Comment by Snuffleupagus** [comment]
I really don't think that we want to complicate and/or possibly slow down the general textLayer building by introducing e.g. a callback function, provided from the outside, for handling text measurement.
Furthermore, with somewhat recent changes, note that we're now also relying even *more* on the browser to obtain information about fonts used for the textLayer; see e.g. https://github.com/mozilla/pdf.js/blob/d285580f486178a41a316d615f3157ec7e1afcb3/src/display/text_layer.js#L51-L116

---

This is probably the sort of thing that belongs in a *custom* implementation/fork of the PDF.js library, given the somewhat specialized use-case outlined in https://github.com/mozilla/pdf.js/issues/8575#issue-238494962.
All-in-all, I do believe that this issus as filed should now be closed as WONTFIX.
