### ISSUE TITLE
Scrolling is slow on hardware accelerated canvas on chrome compared to non HWA canvas

### ISSUE THREAD

**Issue by vinaynb** [mozilla/pdf.js#8577]
Link to PDF file (or attach file here):
same pdf as used in https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: chrome  59.0.3071.109
- Operating system and its version: ubuntu 14.04
- PDF.js version: i could not find which version the online [demo](https://mozilla.github.io/pdf.js/web/viewer.html) uses but i am using 1.8.462 in my local env and the issue appears there as well.
- Is an extension:no

Steps to reproduce the problem:
1. Open the [demo](https://mozilla.github.io/pdf.js/web/viewer.html) in chrome first with GPU 2d canvas acceleration on. Observe the scrolling performance
2. Now open the same demo with GPU 2d acceleration off (uses software rendering) and check the 
performance. Shows noticeable difference and is smoother than GPU enabled counterpart.
3. If this info helps -> opening the demo on firefox and scrolling is smooth. I checked firefox preferences and `use hardware acceleration when available` flag is true. I could not find out if the canvas is HWA.

What is the expected behavior? (add screenshot)
With HWA canvas on chrome scrolling should be as smooth as we have on non HWA canvas.
What went wrong? (add screenshot)
Low FPS and scrolling with visual degradation.

**Comment by timvandermeij** [comment]
Since this most likely indicates a Chrom bug, I'm labeling it as such for now. You might want to open a bug in Chrome's bug tracker as well.

**Comment by vinaynb** [comment]
chrome bug tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=737079#

**Comment by Snuffleupagus** [comment]
> Since this most likely indicates a Chrom bug, I'm labeling it as such for now. You might want to open a bug in Chrome's bug tracker as well.

Given that this issue is both browser and setting *specific*, is it actually meaningful to keep it open here?
