### ISSUE TITLE
Characters are missing

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#8586]
Configuration:
- Google Chrome and  59.0.3071.115
- Windows 10

Steps to reproduce the problem:
1.  Open in Adobe Reader
2. Open in https://mozilla.github.io/pdf.js/web/viewer.html

I have opened it in Pdfjs viewer and Adobe reader, but both displayed differently. I have attached a pdf and an image. In image I have marked around the words which are displaying well in Adobe reader but not in Pdfjs viewer.  Following example from page no 3.

[272103.pdf](https://github.com/mozilla/pdf.js/files/1112782/272103.pdf)

![image](https://user-images.githubusercontent.com/11785531/27698956-53055c9e-5d16-11e7-97b1-84d6b6dce9a4.png)

**Comment by amitpareek** [comment]
Hi,
We use this in production and this issue is causing us a lot of trouble. Is there a possible solution for this already, or is it a bug in the system. Will appreciate if someone can suggest a solution for this.

Thanks,
