### ISSUE TITLE
How to scale / use millimeters.

### ISSUE THREAD

**Issue by SPlatten** [mozilla/pdf.js#8588]
Hi, I've downloaded pdf.js version, not sure how I tell which version it is, it was downloaded today (29/06/2017).

I'm developing on iMAC, using node.js, I want to scale the PDF to millimeters and produce bounded rectangles for all text in the document.

Is this possible to do?  Sorry, I know I could spend some time and find out myself, I was hoping for a quick answer.

**Comment by yurydelendik** [comment]
> I want to scale the PDF to millimeters and produce bounded rectangles for all text in the document.

PDF.js operates in PDF units (= 1/72 inch) -- you will need to adjust scale to transform that to mm.

See also https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js and https://github.com/mozilla/pdf.js/blob/master/examples/text-only/pdf2svg.js examples.

Closing as answered.
