### ISSUE TITLE
Fails on to open pdf (Invalid PDF structure)

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#8593]
Link to PDF file (or attach file here): https://ora.ox.ac.uk/objects/uuid:dd8473bd-2d70-424d-881b-86d9c9c66b51/datastreams/bine2aea0d2-0f9c-43a5-b551-c9570284d9f0

Configuration:
- Web browser and its version: Version 61.0.3144.0 (Official Build) canary (64-bit)
- Operating system and its version: Win 10 64b 10.0.1.1493 Build 14393
- PDF.js version: 1.6.293
- Is an extension: Yes

Steps to reproduce the problem:
1. Open link
2.

What is the expected behavior? (add screenshot)
File should open

What went wrong? (add screenshot)
Invalid or corrupted PDF file.
PDF.js v1.6.293 (build: 9295114)
Message: Invalid PDF structure

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Works for me, using the latest version of PDF.js (which as of this writing is `1.8.503`).

> PDF.js version: 1.6.293

This version is outdated, and I'd recommend updating to a newer release; see https://github.com/mozilla/pdf.js/releases.

Closing, since nothing appears to be broken here.

**Comment by qwer1304** [comment]
Problem is I'm using the Chrome extension from Google Store and the version there is stuck at 1.6.293.
Is there anywhere a fresher version?
