### ISSUE TITLE
New needs some help plz

### ISSUE THREAD

**Issue by SPlatten** [mozilla/pdf.js#8595]
I am quite new to pdf.js, this is what I'm trying to do:

- Read PDF document for processing

- Convert PDF to mm

- Extract the X & Y coordinates for each text item with the origin 0,0 top left of the page

Can anyone give me some pointers on how to go about this please or if there is a good source of documentation, perhaps point me to that?

Thank you,

**Comment by timvandermeij** [comment]
This is really a custom usecase, so there is no clear documentation for it. The examples at https://github.com/mozilla/pdf.js/tree/master/examples should help a lot. For the text layer, take a look at https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js.

**Comment by timvandermeij** [comment]
For more questions, please use the IRC channel as the issue tracker is really only meant for reporting bugs or features, not for general questions.
