### ISSUE TITLE
[suggestion] Script to replace the pdf plugin

### ISSUE THREAD

**Issue by yurivict** [mozilla/pdf.js#8601]
Some websites expect a browser to have the pdf plugin:

```
<object data="myfile.pdf" type="application/pdf" width="100%" height="100%">
  <p>Alternative text - include a link <a href="myfile.pdf">to the PDF!</a></p>
</object>
```

But some browsers don't have the pdf plugin, webkit for example.
It should be possible to rewrite such code and replace it to use pdfjs.
Is such script available? Or can the pdfjs project provide such script?

**Comment by Snuffleupagus** [comment]
I've not tried, but it seems that https://pdfobject.com/ may be able to do what you ask.
Closing, since this is out of scope for the PDF.js project.

**Comment by yurivict** [comment]
PDFObject embeds pdf into the page using the 'embed' clause, or iframe with prepared html. It doesn't replace embeds/iframes to use pdfjs.
