### ISSUE TITLE
Fails on to open pdf (Invalid PDF structure)

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#8602]
Link to PDF file (or attach file here): https://ora.ox.ac.uk/objects/uuid:dd8473bd-2d70-424d-881b-86d9c9c66b51/datastreams/bine2aea0d2-0f9c-43a5-b551-c9570284d9f0

Configuration:

Web browser and its version: Version 61.0.3144.0 (Official Build) canary (64-bit)
Operating system and its version: Win 10 64b 10.0.1.1493 Build 14393
PDF.js version:  1.8.507
Is an extension: Yes
Steps to reproduce the problem:

Open link
What is the expected behavior? (add screenshot)
File should open

What went wrong? (add screenshot)
Invalid or corrupted PDF file.
PDF.js v1.8.507 (build: 9e4dcf1)
Message: Invalid PDF structure

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by jakehockey10** [comment]
I'm having this issue as well.  I'm using `pdfjs` and `pdfjs-dist` in my nodejs application.  For the first time, I ran into a file that won't open when I use `pdfjs-dist`'s `getDocument(...)` method.  I'm not sure how to troubleshoot or what to do at this point?

**Comment by Snuffleupagus** [comment]
Loads just fine in Firefox Nightly 67, which includes PDF.js version `2.1.228`.

> Web browser and its version: Version 61.0.3144.0 (Official Build) canary (64-bit)

Most likely this is/was a Chrome-specific issue, since there appears to be nothing wrong with the PDF file.

**Comment by timvandermeij** [comment]
It also loads fine with the version in Firefox 64.0.2. I'm guessing this is fixed by a previous pull request.
