### ISSUE TITLE
PDFJS.getDocument - Unable to catch thrown Error when file is corrupted

### ISSUE THREAD

**Issue by ironal** [mozilla/pdf.js#8608]
Link to PDF file (or attach file here):
[BrokenPdf.pdf](https://github.com/mozilla/pdf.js/files/1122988/BrokenPdf.pdf)

Configuration:
- Web browser and its version: Chrome 59.0.3071.115
- Operating system and its version: Mac OSX Sierra 10.12.5
- PDF.js version: 1.7.225
- Is an extension: NO

Steps to reproduce the problem:
1. Try _PDFJS.getDocument(fileReader.result).then( ... ).catch( ... )_ with the attached "corrupted file"

What is the expected behavior? (add screenshot)
As the file is corrupted, Pdf.js thrown an Error (Error: page dictionary kid reference points to wrong type of object). 

![screen shot 2017-07-04 at 17 18 04](https://user-images.githubusercontent.com/4924744/27842066-d1a7dd14-60dc-11e7-905c-e0c5d7b9b1ce.png)

What went wrong? (add screenshot)
I am trying to catch this error in the promise, but its never being caught.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Simplifying, I have similar scenario (found in the web):

http://jsbin.com/qulinaweho/1/edit?html,console,output

But when the file is corrupted, the library prints the error in the console log, and I am not able to catch it in order to handle the error.

Thank you.

**Comment by Snuffleupagus** [comment]
> Try PDFJS.getDocument(fileReader.result).then( ... ).catch( ... ) with the attached "corrupted file"

> I am trying to catch this error in the promise, but its never being caught.

Considering that the error in question, `FormatError: page dictionary kid reference points to wrong type of object`, isn't thrown when calling `getDocument` it's expected that you cannot catch it like that.

Please note that the error originates in [src/core/obj.js#L492-L493](https://github.com/mozilla/pdf.js/blob/0c95bc7d839f778528e4b5c9480ba1a642f74313/src/core/obj.js#L492-L493), i.e. as a result of a [`PDFDocumentProxy.getPage()`](https://github.com/mozilla/pdf.js/blob/0c95bc7d839f778528e4b5c9480ba1a642f74313/src/display/api.js#L559-L566) call. In order to catch this error, you'll need to add `catch` handlers to *those* calls; e.g. something like this (using your sample code):
```javascript
PDFJS.getDocument(fileReader.result).then((pdfDocument) => {
  // Fetching a page, e.g. the first.
  pdfDocument.getPage(1).then((pdfPage) => {
    // The page is now available for use...
  }).catch((ex) => {
    // This will catch errors such as:
    // "FormatError: page dictionary kid reference points to wrong type of object"
  });
}).catch( ... )
```

**Comment by ironal** [comment]
Hi @Snuffleupagus, thank you for your response. 
Yes I have tried to put the catch in the getPage. Actually when i was testing I put a catch in all the promises, but none of them was catching the issue, it was like the code was continuing the normal flow (apart that pdf.js was printing the error in the Console and stopping to work). Unfortunately doesn't go inside the catch and the library throws an exception in the pdf.worker.js:

// Fatal errors that should trigger the fallback UI and halt execution by
// throwing an exception.
function error(msg) {
  if (verbosity >= VERBOSITY_LEVELS.errors) {
    console.log('Error: ' + msg);
    console.log(backtrace());
  }
  throw new Error(msg);
}

Thanks.

**Comment by yurydelendik** [comment]
Do you have to same issue with newer version of PDF.js?

**Comment by ironal** [comment]
@yurydelendik I am using version 1.7.225 which I have download a couple of months ago. Didn't try with newer versions (if any).

**Comment by yurydelendik** [comment]
Please also notice that new version PDF.js has [stopAtErrors setting](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L138)

**Comment by Snuffleupagus** [comment]
> I am using version 1.7.225 which I have download a couple of months ago. Didn't try with newer versions (if any).

Please note that I specifically mentioned at the end of https://github.com/mozilla/pdf.js/issues/8608#issuecomment-320069449 that you need at least version `1.8.564` for this to work :-)

**Comment by yurydelendik** [comment]
@ironal WFM at http://jsbin.com/quqinecojo/edit?html,console

**Comment by ironal** [comment]
Thanks both for the info. 
Looking at the documentation I see that the beta version released today is 1.8.188 and stable is the one that I am using.
Would it be a risk to use 1.8.564 in Prod? Probably better that is released?

**Comment by yurydelendik** [comment]
> Would it be a risk to use 1.8.564 in Prod?

Maybe. This risk might have a lower cost than the defect you are experiencing. It's up to you to judge.

**Comment by ironal** [comment]
Ok I will evaluate what's better ;-)
