### ISSUE TITLE
PDF margins?

### ISSUE THREAD

**Issue by SPlatten** [mozilla/pdf.js#8629]
I'm trying to work out why the position of the text doesn't match the position on paper and that given in GIT, it seems there are margins and if yes, what are they and how to I get access to read them?

This is the height and width returned by pdf.js for an A4 document:

        width: 37.188, height: 52.625

I am internally scaling this to mm, based on an A4 being 210mm wide and 297 mm high

My scaling:

        scale factor X = 210 / 37.188 = 5.646982897708938
        scale factor Y = 297 / 52.625 = 5.643705463182898

I then apply this to each x and y coordinate in each text object:

      text x = text x * scale factor X
      text y = text y * scale factor Y

Whilst the calculated results look correct, there is a difference between what I see in GIMP using mm and what I'm calculating.  It looks like there is a fixed offset.

**Comment by davehouse** [comment]
@SPlatten could you post a link for an example pdf document and explain what you are comparing? What program are you using to print the pdf? Screenshots from pdf.js and Gimp could help show the offset or difference also.

If it is not a problem with pdf.js (You might compare with Acrobat Reader), then the "page boundaries" section in the pdf spec may explain what you are seeing in terms of printed region versus on-screen display: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=962

**Comment by SPlatten** [comment]
Here is a sample PDF I've been using to test my code:
[sample.pdf](https://github.com/mozilla/pdf.js/files/1167270/sample.pdf)

Screen shot from gimp, showing highlighted top right coordinates of text item:
<img width="585" alt="gimpscreen" src="https://user-images.githubusercontent.com/11973906/28490336-7d86df5e-6ecf-11e7-8a55-fd4fb865980a.png">

The coordinates as returned from the script for this item are:
        { topleft: { x: 25.420588235294122, y: 29.463669833729206 }
         , botright: { x: 44.77588235294118, y: 33.69644893111638 }
        , text: 'LINE START' },

**Comment by Snuffleupagus** [comment]
Closing for now, since without a *runnable example* it's unfortunately somewhat difficult to assist here; please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
