### ISSUE TITLE
Browser Margin Must Be zero

### ISSUE THREAD

**Issue by shireen22** [mozilla/pdf.js#8635]
![untitled](https://user-images.githubusercontent.com/15665520/28055582-041a175c-6633-11e7-9a98-00b420342593.png)

**Comment by shireen22** [comment]
<iframe src="/modules/cases/js/my.pdf#view=fit&zoom=100&toolbar=0&navpanes=0" frameborder="0" id="mframe" height="800px" id="fraViewDocumentsPDFViewer" runat="server"
                        width="800px"></iframe>

**Comment by Snuffleupagus** [comment]
That screen-shot does *not* actually show PDF.js, but rather shows PDFium (which is the PDF viewer that is embedded in Google Chrome).
Closing as out of scope, since we cannot provide support for *another* PDF viewer.
