### ISSUE TITLE
externalLinkTarget set to iframe

### ISSUE THREAD

**Issue by xmasmc** [mozilla/pdf.js#8639]
Could I set the externalLinkTarget to a specific iframe ?
like in html: target="MyFrame1"

I am using pdfjs-1.7.225-dist and have integrated the viewer in my testpage.
I have no problems to change the target with:
"externalLinkTarget": PDFJS.LinkTarget.SELF

Is there a way to change the externalLinkTarget to a specific iframe on my page ?

Would be very important for my development.

**Comment by Snuffleupagus** [comment]
> Is there a way to change the externalLinkTarget to a specific iframe on my page ?

No, there isn't, since this is not a use-case that is relevant for the default viewer.
You'll have to modify the PDF.js code in your custom implementation to do accomplish this; closing as answered.
