### ISSUE TITLE
can't render this pdf file correctly

### ISSUE THREAD

**Issue by liuyutao** [mozilla/pdf.js#8644]
Link to PDF file (or attach file here):
[bad.pdf](https://github.com/mozilla/pdf.js/files/1145277/bad.pdf)

Configuration:

- Web browser and its version: chrome 58.0.0
- Operating system and its version:win7
- PDF.js version:1.0.0
- Is an extension:no

Steps to reproduce the problem:
1. copy this file to pdfjs directory
2.view it in the browser  , location like  'http://localhost:8888/web/viewer.html?file=bad.pdf'

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2098770/28168250-0d3662d4-6811-11e7-9435-0a036bc3fd0d.png)

What went wrong? (add [screenshot)]
![image](https://user-images.githubusercontent.com/2098770/28168265-1d22ff40-6811-11e7-9651-6b51f13f87c0.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by liuyutao** [comment]
After the study, this document is developed by founder software, and they use a set of encryption algorithms to edit the file, every text is given a font, this software to edit the result is not the same with ordinary documents. I don't think this problem can be solved.

**Comment by liuyutao** [comment]
Here is some keyword I found,　
Font Library CID5.0
 fzbookmaker
方正 PdfCreator3.0
FYI

**Comment by THausherr** [comment]
Your type1 fonts are all broken, here's an example:
```
%!FontType1-1.0: /REHISM+FzBookMaker21DlFont210536873400 001.003
12 dict begin
/Fontinfo 9 dict dup begin
/FullName (FzBookMaker21DlFont21) readonly def
/FamilyName (FzBookMaker21DlFont21) readonly def
/Weight (Normal) readonly def
/ItalicAngle 0 def
/isFixedPitch true def
/UnderlinePosition 574 def
/UnderlineThickness 12 def
end readonly def
/FontType 1 def
/FontMatrix [0.001 0 0 0.001 0 0] readonly def
/FontName /REHISM+FzBookMaker21DlFont210536873400 def
/FontBBox {0 0 1 1} readonly def
/PaintType 0 def
/Encoding 256 array 0 1 255 {1 index exch /.notdef put} for
dup 124 /G7C put
dup 125 /G7D put
readonly def
/Encoding StandardEncoding def
currentdict end
currentfile eexec

```
There are at least 2 errors:

1. The keyword is "FontInfo" and not "Fontinfo"
2. The "9" promised 9 entries. But there are only 7.
