### ISSUE TITLE
Webpack build breaks for versions 1.8.527 and 529

### ISSUE THREAD

**Issue by daredevil82** [mozilla/pdf.js#8645]
@yurydelendik has a [sample project](https://github.com/yurydelendik/pdfjs-react) to demonstrate how to use pdfjs in React.  It uses the 1.8.432 build released last month.

If you update the `pdfjs-dist` version to one of the the last two releases (529 and 527), you will see the error below.  Reverting back to the 525 build results in the document loading as expected.

![pdfjs-error](https://user-images.githubusercontent.com/1406974/28184492-9d19a1c0-67e1-11e7-8932-0e53deec51d0.PNG)

**Comment by yurydelendik** [comment]
Regression from https://github.com/mozilla/pdf.js/pull/8630

**Comment by daredevil82** [comment]
that was quick, thanks!
