### ISSUE TITLE
strange pdf not open in phone's browser but pc worked fine

### ISSUE THREAD

**Issue by iyuan** [mozilla/pdf.js#8654]
Link to PDF file (or attach file here): http://jlb-storage.inmindglobal.com/30e7297b8c2d48d0981252cb94dfdc35.pdf

Configuration:
- Web browser and its version: ios10.2 chrome/safari
- Operating system and its version:
- PDF.js version: 1.5.188
- Is an extension:  

Steps to reproduce the problem:
1. change viewer.js HOSTED_VIEWER_ORIGINS: add http://jlb-storage.inmindglobal.com
2. open /?file=http://jlb-storage.inmindglobal.com/30e7297b8c2d48d0981252cb94dfdc35.pdf

What went wrong? (add screenshot)
always loading on phone's browser but pc worked.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The file draws a bit slowly on my PC as well, so I'm guessing the phone does not have the performance required to render the file.

**Comment by iyuan** [comment]
@timvandermeij i test it with the newest git master, pdf.js version: 1.8.550 . 
mac safari work too slowly more than 20 minutes.. but chrome work fine.

ios10 phone safari could draw with direct pdf url fine but not work with pdf.js show.
any suggestion?

thank you!

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here): http://jlb-storage.inmindglobal.com/30e7297b8c2d48d0981252cb94dfdc35.pdf

The link no longer works. Furthermore, given the age of this issue, is it really meaningful keep this issue open (especially when it seems to be platform/browser-related)?
