### ISSUE TITLE
Update chrome extension to use white-listed javascript actions

### ISSUE THREAD

**Issue by bruzie** [mozilla/pdf.js#8658]
Configuration:
- Web browser and its version: Chrome 59.0.3071.115
- Operating system and its version: Windows 10 64-bit
- PDF.js version: 1.6.293
- Is an extension: Yes

Steps to reproduce the problem:
1. Open PDF with app.launchURL() javascript action
2. Attempt to click hotspot with javascript action

What is the expected behavior? (add screenshot)
White-listed javascript action executed (e.g. destination link opens in new tab)

What went wrong? (add screenshot)
No link available

Relevant commit: https://github.com/mozilla/pdf.js/commit/6d8a404a9c3fefd0a2f26389e5a0ca5d1545291d

**Comment by yurydelendik** [comment]
@bruzie please provide PDF (reference)

**Comment by bruzie** [comment]
I won't have access to the authoring software to create a test file for a couple of days, but will do so then.

**Comment by bruzie** [comment]
Try this one: [LinkTest.pdf](https://github.com/mozilla/pdf.js/files/1160890/LinkTest.pdf)

The first box is a standard "Open a Web Link" action generated by the Microsoft PDF generator. 

The other two boxes have been edited in Acrobat to change the action to Run a JavaScript with the first one opening the link in the current window and the second to open in a new window. These two links do not work in Chrome using the native PDF viewer.

Up until a couple of days ago they did not work in the Chrome Extension, but I now see that the extension has been updated and that these links do work as intended. This means that this issue can be Closed as resolved (or whatever the terminology is). :) 👍
