### ISSUE TITLE
Link fails to open in Chromium+PDF.js, but does open in Firefox

### ISSUE THREAD

**Issue by edgimar** [mozilla/pdf.js#8662]
The following link shows up as an "invalid or corrupted PDF file" when trying to open in Chromium (59.0.3071.109) with PDF.js (1.8.557), but it opens fine in Firefox (54.0):

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.108.3250&rep=rep1&type=pdf

**Comment by Snuffleupagus** [comment]
The link no longer appears to work. (Furthermore this issue appears to be about the Chromium extension, which unfortunately isn't actively maintained now; see #13669.)
