### ISSUE TITLE
Xamarin Android PDF Displays, But Does Not Download

### ISSUE THREAD

**Issue by KBR-Rmsapp08** [mozilla/pdf.js#8665]
Can be any PDF

Configuration:
- Assuming Android Native Browser
- Android 6.0.1 Marshmallow
- v1.5 through 1.8:

Steps to reproduce the problem:
1. I am following the example given here: [](https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/display-pdf/)
2. Everything works fine, except for the download button. Once clicked, does nothing.  Has anyone been able to get the download button to work within an Android application?

What is the expected behavior? PDF Download to Physical Device from with Android Application.  Works fine in Chrome.

What went wrong? Nothing happens when download button clicked.

**Comment by Snuffleupagus** [comment]
This sounds like a browser/platform issue rather than a PDF.js library one; closing since this issue doesn't seem like something that can/should be fixed here?
