### ISSUE TITLE
How to pass the http:// pdf url for view in pdf.js viewer

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8669]
Basically i have a pdf url link so i just need to open in pdf viewer on web page so how i will pass the url in param to open pdf file . 
url : https://www.dropbox.com/s/fzzjj41ybym8ule/angular-4.pdf?dl

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file -- via encoded file= parameter. Closing as answered.

**Comment by SOftEngrAtta** [comment]
<a href="./web/viewer.html?file=https://www.dropbox.com/s/fzzjj41ybym8ule/angular-4.pdf?dl=0">
    View PDF File
</a> 

Error : 
Uncaught (in promise) Error: Invalid or corrupted PDF file.
    at getDocumentError (viewer.js:1627)
    at <anonymous>

how to resolve this error

**Comment by yurydelendik** [comment]
http://mozilla.github.io/pdf.js/web/viewer.html?file=http://cdn.mozilla.net/pdfjs/tracemonkey.pdf works for me

**Comment by SOftEngrAtta** [comment]
on which browser you will run

**Comment by SOftEngrAtta** [comment]
sorry this url is not working my google chrome :(

**Comment by SOftEngrAtta** [comment]
my html file 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="./web/viewer.html?file=http://www.axmag.com/download/pdfurl-guide.pdf">View PDF File</a>
</body>
</html>


where i am doing mistake ?

**Comment by andreadd** [comment]
The PDF file to use must be on the same server due to JavaScript limitations

**Comment by sassiala** [comment]
@yurydelendik 
@andreadd 
@SOftEngrAtta 
why does'nt work when I access to pdf-file outside my root directory?  
when I create " ?file=file:///C:/folder_name/file_name.pdf " nothing displayed ( no exception , no pdf content)

and when I create " file:///C:/project_name/web/viewer.html?file=../file2_name.pdf " 
an exception be launched 
=>    PDF.js v1.9.426 (build: 2558a58d)
         Message: Missing PDF "file:///C:/project_name/file2_name.pdf " 
and I am sure that file (2.pdf) is located in C:/project_name/file2_name.pdf

I need help

**Comment by robert-john-concepcion** [comment]
is this posible to pass a base64 pdf?

**Comment by Lyn203** [comment]
Is it posible to pass url with its params through file param?

**Comment by bpetty-formfast** [comment]
@yurydelendik - this should probably be re-opened because it is no longer true.

> https://mozilla.github.io/pdf.js/web/viewer.html?file=http%3A%2F%2Fmozilla.github.io%2Fpdf.js%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf

Encoding the path will not work.  It is either a defect or it is no longer supported.

**Comment by shivarajnaidu** [comment]
Is there any way to use external links with viewer.html ?
