### ISSUE TITLE
Text layer divs are not split upon changes in char/word spacing

### ISSUE THREAD

**Issue by audunhalland** [mozilla/pdf.js#8670]
Link to PDF file (or attach file here):
[test.pdf](https://github.com/mozilla/pdf.js/files/1158969/test.pdf)

Configuration:
- Web browser and its version: Chrome 59
- Operating system and its version: macOS 10.2.5
- PDF.js version: pdfjs-dist 1.8.508
- Is an extension: ?

Steps to reproduce the problem:
1. Load the attached file "test.pdf" in pdf.js viewer
2. inspect the ".textLayer > div" rule in dev mode, and comment out "color: transparent"
3. text layer now shows as a transparent overlay, and reveals the bug.

Alternative way to reproduce, without messing with any css:
1. Load the attached file "test.pdf" in pdf.js viewer
2. Enter find mode, and type "oversikt" (Norwegian).
3. The highlighted section in the document extends beyond the size of that word. The whole div is stretched because of the extended character spacing of the following periods. The word and the dots should have been two separate divs.

What is the expected behavior? (add screenshot)
<img width="696" alt="screen shot 2017-07-19 at 13 55 03" src="https://user-images.githubusercontent.com/5767935/28365722-ed1b9c76-6c89-11e7-898c-de740bf90aeb.png">

What went wrong? (add screenshot)
<img width="691" alt="screen shot 2017-07-19 at 13 53 37" src="https://user-images.githubusercontent.com/5767935/28365684-c7885ddc-6c89-11e7-9106-1a0b0fe70b4e.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by audunhalland** [comment]
Created pull request: https://github.com/mozilla/pdf.js/pull/8671

**Comment by timvandermeij** [comment]
Closing since this is fixed now.
