### ISSUE TITLE
Exact Text Search

### ISSUE THREAD

**Issue by Timmytbone93** [mozilla/pdf.js#8675]
Link to PDF file (or attach file her
[1990-09-13.pdf](https://github.com/mozilla/pdf.js/files/1160368/1990-09-13.pdf)
e):

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 7
- PDF.js version: Newsest
- Is an extension: NO

Steps to reproduce the problem:
1. Search for the word John
2. Search results include Johnny and other words that have the characters John in them 

What is the expected behavior? (add screenshot)
Should find all instances of John on the HTML page and highlight them, NOT PARTIAL SEARCHES
What went wrong? (add screenshot)
Highlights Johnny, Johnathan, etc instead of just John
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
PDF text extraction is not precise process, e.g. for some document the "Johnisagoodguy" can be extracted even is visually it is a separate words. We cannot fix it for the demo viewer and not to regress existing application, but developers who are building custom viewers can add this feature by analyzing the [getTextContent](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L980) result and modify existing demo viewer's logic at (PDFFindController](https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js)

Closing as won't fix.

**Comment by yurydelendik** [comment]
Here is good example from your document, but I'm using Mac OSX Preview:

<img width="1209" alt="screen shot 2017-07-19 at 3 57 59 pm" src="https://user-images.githubusercontent.com/1523410/28389290-241de592-6c9b-11e7-9868-aecb7b517a0f.png">

Notice that Jonh appears as JohnS in search results.
