### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by DietmarBlue** [mozilla/pdf.js#8677]
Hello: Please help with the following issue:

We want to use your great lib in our typo3 pageflip extension clientside, we do not have node running on the apache webserver, and ran into the following problem:

Configuration:
- Web browser and its version: Apache WITHOUT node!!
- Operating system and its version: Linux
- PDF.js version: 1.8.557

Steps to reproduce the problem:
1. Installed pdfjs-dist with bower install pdfjs-dist
2. included in html file
![includes](https://user-images.githubusercontent.com/18737276/28407123-47b3841a-6d33-11e7-95fb-a095169b156e.PNG)
 

What went wrong? (add screenshot)
![exports-is-undefined](https://user-images.githubusercontent.com/18737276/28407015-e32000c8-6d32-11e7-879c-ddbb9eca71c0.PNG)

this is **ui_utils.js**

![problematic-code](https://user-images.githubusercontent.com/18737276/28407497-a40733dc-6d34-11e7-83aa-87f158df01db.PNG)

**Comment by DietmarBlue** [comment]
I am one step ahead,

obviously bower is not a good choice for downloading the dist files.

i now installed it with **npm install pdfjs-dist**, then i installed browserify , did a 
**node_modules/.bin/browserify node_modules/pdfjs-dist/lib/pdf.js  > bundle.all.js** and included this file to my html.

Unfortunately i get an error _Uncaught TypeError: Cannot read property 'WorkerMessageHandler' of undefined_ in the following function.

![error](https://user-images.githubusercontent.com/18737276/28412677-3369ad38-6d45-11e7-9cef-dbeea9b5de4a.PNG)
![worker-error](https://user-images.githubusercontent.com/18737276/28412748-6d851930-6d45-11e7-8aa4-7ebf9c1b6ef9.PNG)

My questions now are:
1) Do i need the Worker, if not, howto deactivate it
2) if i need the worker, how do i bundle pdf.worker.js with pdf.js to get rid of the errors

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/tree/master/examples/browserify and https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website#with-browserify

> Do i need the Worker

Yes

> how do i bundle pdf.worker.js with pdf.js to get rid of the errors

Follow the example/instructions above.

Closing as answered.
