### ISSUE TITLE
Figure shows garbage inside (e001 shows up)

### ISSUE THREAD

**Issue by photoszzt** [mozilla/pdf.js#8680]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Firefox 54 and Nightly
- Operating system and its version: macos
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. open https://www.usenix.org/system/files/conference/fast15/fast15-paper-verma.pdf
2. look at figure 1

What is the expected behavior? (add screenshot)
<img width="315" alt="correct" src="https://user-images.githubusercontent.com/1476795/28443013-5acffd5a-6d68-11e7-8158-86823d1d93f2.png">

What went wrong? (add screenshot)
<img width="391" alt="wrong" src="https://user-images.githubusercontent.com/1476795/28442992-448fea64-6d68-11e7-9283-20afbe1cd32c.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Fixed by #9340.
