### ISSUE TITLE
Is there any way drag PDF from left menu and drop to right hand side viewer ? 

### ISSUE THREAD

**Issue by Galaba563** [mozilla/pdf.js#8683]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since it's really impossible to understand what's being asked here given the lack of details.

**Comment by Galaba563** [comment]
Hi @Snuffleupagus  I am just asking to you,  [](https://mozilla.github.io/pdf.js/web/viewer.html), open that page we have left hand side panel showing the pages. is there any way to drag from left panel and drop to pdf viewer page

**Comment by Snuffleupagus** [comment]
> open that page we have left hand side panel showing the pages. is there any way to drag from left panel and drop to pdf viewer page

So what you're really asking here is if it's possible open the sidebar (to show the thumbnails), and then drag thumbnails them into the viewer?
If so, the answer is no (and I don't really understand the use-case here). However, the thumbnails can obviously be clicked to show the corresponding page in the viewer.

**Comment by Galaba563** [comment]
@Snuffleupagus , can Know How implement in my project same left panel and viewer, could you please help me that, I am very thankful to you.
