### ISSUE TITLE
Hand Tool Disable 

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8685]
i created new button for close hand tool but how can i do this ?

**Comment by timvandermeij** [comment]
You can call https://github.com/mozilla/pdf.js/blob/master/web/pdf_cursor_tools.js#L80 with `CursorTool.SELECT` to not use the hand tool anymore. This is also what we do in the default viewer.

**Comment by SOftEngrAtta** [comment]
yeh got it closed
