### ISSUE TITLE
flickering on scroll - knockout groups

### ISSUE THREAD

**Issue by mmjaeger** [mozilla/pdf.js#8686]
Hello
when scrolling within the pdf container, I get some grayish box next to the container that flickers badly - is this a known issue - how can I prevent that.

I also get some console messages: Knockout groups not supported - what's that all about?
<img width="704" alt="screen shot 2017-07-22 at 2 51 27 pm" src="https://user-images.githubusercontent.com/1554580/28495305-389f355c-6efd-11e7-8c5f-87bf9c9808a2.png">
<img width="1130" alt="screen shot 2017-07-22 at 1 32 23 pm" src="https://user-images.githubusercontent.com/1554580/28495306-38b84362-6efd-11e7-896b-7e0dd32e63a5.png">

Thanks

**Comment by timvandermeij** [comment]
Closing since the required information from the issue template is not provided, most notably a PDF file that shows the issue. There is already an open issue (#3136) that should cover this problem.
