### ISSUE TITLE
google's translate of pdf 

### ISSUE THREAD

**Issue by urosaria** [mozilla/pdf.js#8693]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 1.7.225
- Is an extension:

Steps to reproduce the problem:
1.  I hope use to google's translator to translate the pdf.
2. I can't translated contents but i can watched it through the development tool in browser.
3. Contents and source code are different. 
4. I want to loading the page after translate.
    Is it possible? 

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/1840855/28513568-9c4145b0-7091-11e7-81ca-642027c5f600.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
The PDF format does not allow to apply google translate as is, e.g. it is near to impossible to layout translated text using the same fonts. Closing as won't fix.
