### ISSUE TITLE
Text Near Right Margin Truncated During Printing

### ISSUE THREAD

**Issue by DavidRoss** [mozilla/pdf.js#8701]
PDF file contains personal identification that can be used for identity theft.  Thus, I have not attached it.  
Configuration:
- Browser:  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 SeaMonkey/2.48
- Operating system and its version:  Windows 7 Ultimate SP1 (x64)
- PDF.js version:  1.8.579
- Is an extension:  yes

Steps to reproduce the problem:
1.   Logon to Southern California Edison.  
2.   View current bill, which is presented in PDF.js as a PDF file.  
3.   Print page 1 of the bill.  

What is the expected behavior? (add screenshot)
All text on the page should print.  

What went wrong? (add screenshot)
The cents in the amount due near the right margin is truncated.  

Note:  The cents -- and the rest of the page -- are fully displayed by PDF.js.  The problem occurs during printing.  Requesting the page to print at 95% does not resolve the problem; that shrinks not only the page but also the margins and still truncates the cents.  

Also note:  I saved the PDF file and printed it with Adobe Reader 11.0.20.17 WITHOUT any adjustment to the page size.  The whole page printed okay, including the cents.  

If necessary, I could likely construct a PDF file that demonstrates this problem without revealing any personal information.  

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by DavidRoss** [comment]
I decided to create a PDF file that demonstrates this problem without waiting to be asked.  See [http://www.rossde.com/test/PDF_truncated_print.pdf].  Print it with pdf.js.  Then download it and print it with Adobe Reader.

**Comment by ousia** [comment]
@DavidRoss, would it be possible that _Adobe Reader_ fits printing area to printing margins by default?

Sorry, but i don’t have a printer myself and I cannot check it.

**Comment by ousia** [comment]
@DavidRoss, I tried to print to a PDF file and I got this:

![print-1](https://user-images.githubusercontent.com/203767/29752992-9b05b14e-8b68-11e7-873a-c0070b6b0334.png)

But the printing dialog in _Linux_ includes the following:

![print-options](https://user-images.githubusercontent.com/203767/29753010-f655836c-8b68-11e7-896c-9155ea0d7564.png)

In that case, I think it would be important to have a default printing mode to fit content to printer margins only when needed.

**Comment by DavidRoss** [comment]
I was able to reproduce ousia's "print-1" results.  I opened [http://www.rossde.com/test/PDF_truncated_print.pdf] via pdf.js and printed it to a new PDF file via doPDF.  There was no truncation.  Thus, I conjecture the problem is in the interface between pdf.js and Mozilla's Printing component of its Core product.  I somewhat doubt the problem is between Mozilla's Printing component and my print drivers because the problem is observed only when pdf.js prints.

**Comment by DavidRoss** [comment]
This is still a problem with PDF.js 1.9.658.

**Comment by DavidRoss** [comment]
This is still a problem with PDF Viewer 2.0.159.

**Comment by DavidRoss** [comment]
This is still a problem with PDF Viewer 2.0.159.

**Comment by DavidRoss** [comment]
I did not mean to close this.  This is still a problem with PDF Viewer 2.0.305.

**Comment by DavidRoss** [comment]
I did not mean to close this.  This is still a problem with PDF Viewer 2.0.305.

**Comment by timvandermeij** [comment]
Closing since we merged quite a few printing fixes recently and this prints out just fine for me. If there are still problems they are most likely upstream and can therefore not be fixed here; in that case please open a ticket on Bugzilla.
