### ISSUE TITLE
pdf converted powerpoint (.ppt) files with hidden layer shows as blank on PDFjs viewer 

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#8702]
Link to PDF file (or attach file [here):]([url])
[2_Test.pdf](https://github.com/mozilla/pdf.js/files/1175758/2_Test.pdf)

Configuration: 
- Web browser and its version: All Modern browsers
- Operating system and its version: winXX / latest
- PDF.js version: latest
- Is an extension:

Steps to reproduce the problem:
1. take a powerpoint (.ppt) files with hidden layer 
2. convert that ppt to pdf via acrobat
3. then try to view through pdfjs viewer

What is the expected behavior? (add screenshot)
should show exact contents
What went wrong? (add screenshot)
shows blank page

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
PDFium, in Google Chrome, also fails to load the document (with an Error dialog shown).
Furthermore, when trying to open the PDF file in Adobe Reader, there's a warning dialog shown explaining that opening the document will transmit user data to a (random) web-server; hence I'm not even going to try to open it with Adobe Reader.

**Comment by yurydelendik** [comment]
The same for Mac OSX Preview:

<img width="1233" alt="screen shot 2017-07-26 at 8 16 22 am" src="https://user-images.githubusercontent.com/1523410/28622604-c3b3dd16-71da-11e7-8b0e-ea3230153f68.png">

Closing as invalid.

**Comment by venusakthiv** [comment]
sorry. that was applied with rights.
please take the latest test file.
[2_Test_latest.pdf](https://github.com/mozilla/pdf.js/files/1176841/2_Test_latest.pdf)
