### ISSUE TITLE
missing worker giving errors? 

### ISSUE THREAD

**Issue by tdmoneybanks** [mozilla/pdf.js#8705]
I am having an issue requiring and using the pdf lib that i outlined in this slack link. Can anyone give me help on what im missing?

https://stackoverflow.com/questions/45329816/issue-using-pdfjs-dist-to-open-pdf

**Comment by yurydelendik** [comment]
Hard to tell without details requested by [issue template](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md). Please use examples at the examples folder as a based and provide complete example to reproduce the problem. Closing as incomplete.
