### ISSUE TITLE
IOS application developed using Angular and Cordova is crashing because of heavy memory usage

### ISSUE THREAD

**Issue by ravikant31** [mozilla/pdf.js#8706]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: ios application using angular and cordova
- Operating system and its version: IOS
- PDF.js version: 1.7.225
- Is an extension:

we are using pdf.js and instead of displaying as a pdf, we are displaying the whole pdf as images in a canvas. It works fine but the main issue that we are facing is that the application is crashing on this page because of heavy memory usage. 
Everytime i remove the related code that creates canvas the application does not crash. The number of pages is too 25 and above.

So, is there any way that we can reduce the memory consumption so that app doesn't crash. 
Note : it works fine in desktop browsers.
![pdf using canvas](https://user-images.githubusercontent.com/11021706/28629203-6b126b4a-7244-11e7-9b69-9fb02a035c8f.PNG)

**Comment by timvandermeij** [comment]
Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster. Closing since no more information is provided for this issue to be actionable.
