### ISSUE TITLE
Spaces are render as dots

### ISSUE THREAD

**Issue by Kerumen** [mozilla/pdf.js#8707]
Link to PDF file (or attach file here): [07_2017_managery (21).pdf](https://github.com/mozilla/pdf.js/files/1177525/07_2017_managery.21.pdf)

Configuration:
- Web browser and its version: Chrome 59.0.3071.115
- Operating system and its version: macOS Sierra v10.2.5
- PDF.js version: 1.8.579
- Is an extension: No

Steps to reproduce the problem:
1. Generate the PDF

What is the expected behavior? (add screenshot)

The PDF should render normally with all the spaces.
<img width="412" alt="screen shot 2017-07-26 at 19 30 47" src="https://user-images.githubusercontent.com/5436545/28634978-3e2af698-7239-11e7-9856-c12c6d3a190b.png">

What went wrong? (add screenshot)

Every spaces are replaced by a dot.

<img width="273" alt="screen shot 2017-07-26 at 18 11 34" src="https://user-images.githubusercontent.com/5436545/28634852-d6d431da-7238-11e7-9f73-d6904fb4965d.png">

I tested with an old version of PDF.js (`1.7.235`) and it works well. So I guess it's a regression.

**Comment by Snuffleupagus** [comment]
This regressed in PR #8580 (and it doesn't look like PR #8681 will help here, unfortunately).

**Comment by Kerumen** [comment]
cc @ebourmalo 🔥

**Comment by mikelweb** [comment]
This didn't solve my problem... :(
