### ISSUE TITLE
I am getting issue in pdf pre-flight validation status is verification is failed and PDF/A-2b pre-flight validation is also failed its showing error like character reference .notdef glyph (1 match 1 page)

### ISSUE THREAD

**Issue by BYugandhar** [mozilla/pdf.js#8709]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Adobe DC
![untitled](https://user-images.githubusercontent.com/21058410/28657817-4d5dd148-72c6-11e7-9eb2-0abcad0d7c54.png)

- Operating system and its version: windows 10 
- PDF.js version: PDF/A-2b
- Is an extension:PDF

Steps to reproduce the problem:
1. Scan a copy and select file type as PDF/A
2.Open the PDF file Adobe DC and perform validation in Preflight 

What is the expected behavior? (add screenshot)
I have attached screen shot
What went wrong? (add screenshot)
validation is failed 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
There's nothing that indicates that this is an issue with the PDF.js library, since the (very) limited information provided only refers to "Adobe DC" and there's no PDF file provided either.
Closing as invalid, and incomplete.
