### ISSUE TITLE
this._map[charCode].charCodeAt is not a function

### ISSUE THREAD

**Issue by tdmoneybanks** [mozilla/pdf.js#8711]
Link to PDF file (or attach file here): https://mozilla.github.io/pdf.js/examples/

Configuration:
- Web browser and its version: chrome latest
- Operating system and its version: osx latest
- PDF.js version: 1.8.579
- Is an extension: no

Steps to reproduce the problem:
1. use PDFJS to render the data from the base64 hello world example 
2.

What is the expected behavior? (add screenshot)
PDF should show on the canvas. 
What went wrong? (add screenshot)
This error was printed to the console: 
Warning: Error during font loading: this._map[charCode].charCodeAt is not a function
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
https://jsfiddle.net/pdfjs/cq0asLqz/?utm_source=website&utm_medium=embed&utm_campaign=cq0asLqz wfm

**Comment by yurydelendik** [comment]
<img width="1155" alt="screen shot 2017-07-27 at 11 31 44 am" src="https://user-images.githubusercontent.com/1523410/28681464-37e78be4-72bf-11e7-9d04-d20e569505a6.png">

**Comment by kanoshin** [comment]
@yurydelendik I'm reproducing the same error and pdf rendering issues in project with this pdf https://gist.github.com/kanoshin/769ece0f7ddd02a865a9de3e121ffc9c (it's base64 encoded).

When I'm using jsfiddle you referenced above - it is rendering just fine. Do you have any ideas what might cause such error in different environments.

**Comment by yurydelendik** [comment]
> Do you have any ideas what might cause such error in different environments.

Without seeing the complete example, I can only suggest to check pdf.js version and see if other third-party libraries modifying Object.prototype or Array.prototype and exposing extensions as public properties.
