### ISSUE TITLE
Annotation creation with json object

### ISSUE THREAD

**Issue by thavaamm** [mozilla/pdf.js#8725]
Hi All,

Is there any way to create a new annotation? If it is there, please provide me sample code.

**Comment by yurydelendik** [comment]
Not sure if the problem related to PDF.js. Closing as incomplete.

**Comment by Thavaprakash** [comment]
Hi Yurydelendik,

I can able to render the existing annotation with my pdf file, if i want to add new annotation what need to be done. It would be great if you guide me to achieve this functionality.

**Comment by yurydelendik** [comment]
It sounds like a feature request. I would recommend to start prototyping the proposal. Currently PDF.js implements subset of PDF32000 spec annotations. You can find their rendering logic at https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js.
