### ISSUE TITLE
Error using URL object in safari

### ISSUE THREAD

**Issue by dennererthal01** [mozilla/pdf.js#8726]
Configuration:
- Web browser and its version: Safari Version 10.1.1 (12603.2.4)
- Operating system and its version: macOS Sierra Version 10.12.5
- PDF.js version: 1.8.593
- Is an extension: No

Steps to reproduce the problem:
1. Include pdf.js on any html file and load that file
2. Open developer console and paste the following code: 
`new URL(location).searchParams.get('param')`

What is the expected behavior? 
The browser should check if the provided URL has the specified parameter (screenshot from Google Chrome).
![screen shot 2017-07-31 at 12 44 03](https://user-images.githubusercontent.com/23263506/28785953-2e97c432-75ee-11e7-9fab-48c74d6d6fab.png)

What went wrong?
On safari, it changes the URL and redirects it, breaking the page.
![screen shot 2017-07-31 at 12 44 40](https://user-images.githubusercontent.com/23263506/28786065-72dbb55e-75ee-11e7-98ef-9df3a385b799.png)

**Comment by caub** [comment]
https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js#L1875 .searchParams is a getter, so it's skipped there

**Comment by GinjiBan** [comment]
@dennererthal01 Did you fix your problem ?

I have the same issue but the fixing PR has been closed.

**Comment by dennererthal01** [comment]
@GinjiBan currently I stopped using URL().searchParams, which seems to be the only method broken. I'm using both URLSearchParams() and URL().search.

**Comment by St3v3n-D** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try :)

**Comment by timvandermeij** [comment]
@St3v3n-D Nobody indicated that they're working on it, so it's yours!

**Comment by rob-murray** [comment]
This URL polyfill breaks some other parts of my application - my temporary work-around for this is to include another polyfill after pdf.js is required so older browsers (and safari) is polyfilled twice but ends up with a working version!

**Comment by timvandermeij** [comment]
Fixed by #9868.
