### ISSUE TITLE
pdf.js uri syntax for bookmarks

### ISSUE THREAD

**Issue by abrasat** [mozilla/pdf.js#8728]
how does the url syntax look like, when accessing bookmarks (not named destinations !) inside the pdf file ?

**Comment by timvandermeij** [comment]
If by bookmarks you mean the document outline, then it is handled here: https://github.com/mozilla/pdf.js/blob/master/web/pdf_outline_viewer.js#L72

**Comment by pzanwar03** [comment]
Is there added Bookmark?
