### ISSUE TITLE
[question] Can PdfJs document be instantiated without an iframe?

### ISSUE THREAD

**Issue by yurivict** [mozilla/pdf.js#8729]
The recommended way to use PdfJs is an ```iframe``` with ```src="https://mozilla.github.io/pdf.js/web/viewer.html?file={pdf-URL}"```

However, ```iframe``` is a difficult element to work with in JavaScript: it doesn't allow to traverse elements from the upper document, it doesn't allow setting ```keypress``` callback.

Is there a way, an API, to use PdfJs without the ```iframe```, so that it would become a DOM sub-tree under a ```div``` element?

There should be javascript that builds what viewer.html has into the ```div``` element.

**Comment by timvandermeij** [comment]
You can just render the canvases and show them in any way you like. Take for instance the hello world example at https://github.com/mozilla/pdf.js/blob/master/examples/helloworld/hello.js which just renders the canvas. The mobile viewer example is more elaborate, but the idea is the same.
