### ISSUE TITLE
Bold strings not shown in Mac/Safari

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#8730]
Link to PDF file (or attach file here):
[AN_1175370.pdf](https://github.com/mozilla/pdf.js/files/1189561/AN_1175370.pdf)

Configuration:
- Web browser and its version: Safari 10.11
- Operating system and its version: MacOS X 10.11.6
- PDF.js version: latest (demo site)
- Is an extension:

Steps to reproduce the problem:
1. Open the attached PDF with PDF.js demo site
2. You will see below

What is the expected behavior? (add screenshot)
![2017-08-01 14 11 47](https://user-images.githubusercontent.com/7111820/28810714-2a56fe78-76c6-11e7-971b-027ccc27de03.png)

What went wrong? (add screenshot)
![2017-08-01 14 12 17](https://user-images.githubusercontent.com/7111820/28810732-3662c01c-76c6-11e7-85e6-5da3d3067f7c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by jonalvarezz** [comment]
Hi. 

Tested on macOS 10.12.5; Safari 10.1.1 and it is working fine. 

I am using your attached file

**Comment by Snuffleupagus** [comment]
Is it really meaningful to keep this (very) old issue open, when everything points to a platform/browser bug (rather than a PDF.js one), since this doesn't seem like something that can be fixed *here*?
