### ISSUE TITLE
Extracting form values from PDF in the default viewer

### ISSUE THREAD

**Issue by LubenZA** [mozilla/pdf.js#8731]
Good day,

I am new to pdf.js and I know the form functionality is currently in development.
The example at the link below provides a great way of extracting all form element names and their respective values.
https://github.com/mainegreen/pdf.js/tree/master/examples/forms

My question is how can I include this functionality in the main viewer?
I have enabled forms by setting renderInteractiveForms to true but that only allows interaction with the form elements. I need to be able to extract them and save them eventually. Including forms.js in the viewer also does not work.

Thanks in advance.
Luben

**Comment by timvandermeij** [comment]
It's an open question that is tracked in https://github.com/mozilla/pdf.js/projects/1. The `renderInteractiveForms` setting take care of parsing and rendering the form elements, but saving/printing entered information is not implemented yet. Once the fields have a unique identifier, you may be able to loop over all form elements and get their contents, but this has to be thought out properly before we can include it in the main viewer. It is, however, on the roadmap for the forms implementation.
