### ISSUE TITLE
Headers are no longer being added to requests

### ISSUE THREAD

**Issue by Tomino2112** [mozilla/pdf.js#8734]
We have been running PDFjs in our project for well over two years now, and the basic works of it didn't change for at least a year. 

This is our piece of code to get the document:

```
headers = {
    'Authorization': 'Bearer SOME_TOKEN',
    'x-ipp-device-uuid': 'SOME_UUID',
    'x-ipp-client': 'SOME_ID',
    'x-ipp-client-version': 'SOME_VERSION'
};


docLoadingTask = PDFJS.getDocument({
    url: url,
    httpHeaders: headers
});
```

Just until recently this was working just fine, but from today (might have been longer issue, since I saw some reports in our system about this earlier last week) headers are not being send, and because of the way our system is setup it means PDFs are not loaded.

I have tried and debugged as far as I could, and it seems that `httpHeaders` object is being passed along just fine all the way up to the actual request. I could not get as deep as to the actual request call, but was very close (around NetworkManager) and headers object with correct headers was still there.

Any suggestions?

**Comment by mukulmishra18** [comment]
I can also reproduce this issue locally. I see we are setting right httpHeaders here: https://github.com/mozilla/pdf.js/blob/master/src/display/network.js#L108, but as mentioned in the issue, headers are not sent with `xhr.send()` call.

**Comment by yurydelendik** [comment]
@Tomino2112 can you provide entire example and way to reproduce the issue?

**Comment by Tomino2112** [comment]
@yurydelendik @timvandermeij as @mukulmishra18 said you can reproduce it with minimal code, Our codebase is more complicated it would take me a while to put together exactly what we do, but we don't do anything extra when requesting document, pretty much identical to what I already provided in first report

**Comment by mukulmishra18** [comment]
I can see `httpHeaders` being added to the request header with current master(maybe due to [fetch_stream](https://github.com/mozilla/pdf.js/pull/8768) support). I am doing something like:
```javascript
var docLoadingTask = PDFJS.getDocument({
  url: 'http://localhost:8080/tracemonkey.pdf', 
  httpHeaders: {
    'Accept': 'application/pdf',
    'Origin': '',
    'Accept-Language': 'en-US',
    'Authorization': 'Basic Some_Token',
    'X-ipp-device-uuid': 'SOME_UUID'
  },
});
```

@Tomino2112 can you check if problem still persists for you? I am thinking if response headers actually contains `Access-Control-Allow-Headers:Authorization, X-ipp-device-uuid` ?

**Comment by yurydelendik** [comment]
@Tomino2112 we made few changes to the code base to improved support of the network request. I can observe custom headers are coming to the server side locally (when fetch or XHR is used).

Can you provide all requested information including:

* complete example that indicate behavior
* information/version about browser

**Comment by timvandermeij** [comment]
Closing since no more information has been provided.

**Comment by tomadj** [comment]
Same issue ! 
Headers are no longer being added to requests. 

Any solution ?
