### ISSUE TITLE
Jumbled text when rendered in HTML canvas

### ISSUE THREAD

**Issue by coletrumbocole** [mozilla/pdf.js#8735]
Link to PDF file: 
[myListingFlyer.pdf](https://github.com/mozilla/pdf.js/files/1191473/myListingFlyer.pdf)

Configuration:
- Web browser and its version: Chrome Version 60.0.3112.78 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version:
  - PDFJS.version = '1.3.50';
  - PDFJS.build = '376788f';

- Is an extension: No

Steps to reproduce the problem:
-1. Use FPDI, FPDF, TCPDF in a custom solution to generate a pdf on an existing blank pdf file.
1. Make a webpage with a canvas element `<canvas id="myCanvas" ... ></canvas>`
2. Use a code block like this to render the custom pdf in the canvas (roughly copied from https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html): 
```
<script src="/path/to/pdf.js"></script>
<script src="/path/to/pdf.worker.js"></script>
<script type="text/javascript">
    PDFJS.getDocument("/path/to/pdf/Example.pdf").then(function(pdfFile) {
        var pageNumber = 1;
        pdfFile.getPage(pageNumber).then(function(page) {
            var scale = 1;
            var viewport = page.getViewport(scale);
            var canvas = document.getElementById('myCanvas');
            var context = canvas.getContext('2d');

            canvas.height = viewport.height;
            canvas.width = viewport.width;
            var renderContext = {
                canvasContext: context,
                viewport: viewport
            };

            page.render(renderContext);
        });
    });
</script>
```

What is the expected behavior? I expect the fonts to render like they do in the pdf. 
![expected](https://user-images.githubusercontent.com/8063288/28840792-b5a645ce-772a-11e7-84f3-cef09c0f6cce.PNG)

What went wrong? The fonts were jumbled. They seem to take up half of the width they should be taking up. 
![result](https://user-images.githubusercontent.com/8063288/28841508-1253e360-772d-11e7-872b-291bcded9a3f.PNG)

Link to a viewer: http://coletrumbo.com/pdf_examples/canvasViewer.html
Just a heads up, my site is super slow in general, and it takes a long time to load.

**Comment by coletrumbocole** [comment]
I have been trying to work on this myself, but I don't understand the documentation here very well, and the irc.mozilla.org is down. I think if I could just get some help to learn the debugging tools, I could make a lot of progress.

**Comment by yurydelendik** [comment]
@coletrumbocole looks fine in 1.8.xx version. did you try updating pdf.js library?

**Comment by coletrumbocole** [comment]
@yurydelendik Wow, rookie mistake. Thank you, that worked!
