### ISSUE TITLE
Angular(@latest) - cli implementation

### ISSUE THREAD

**Issue by MrBananaGuard** [mozilla/pdf.js#8736]
Configuration:
- PDF.js version: 1.8.593

Hi,

Not really sure where to raise this, but I am having issues using Pdf.js with Angular-cli. I kinda got it working in chrome, but on IE and edge it just doesn't load and throws an exception. I am sure i am not implementing it correctly. 

In the .angular-cli.json i have implemented the following scripts:
![image](https://user-images.githubusercontent.com/18513849/28860903-c712ded8-775e-11e7-9e7e-1470c97af569.png)

In my component i have imported the following:
![image](https://user-images.githubusercontent.com/18513849/28860923-e5407686-775e-11e7-96ec-6f0ed7e57dac.png)

And obviously in my index.html I have put the following Meta tag
`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`

In edge i get the following error:
![image](https://user-images.githubusercontent.com/18513849/28861061-80326050-775f-11e7-8bc1-12149661360a.png)

Which seems to be when trying to stream the PDF data into scope. In IE pollyfills seems to be giving the issue:
![image](https://user-images.githubusercontent.com/18513849/28861126-d1cfcfd8-775f-11e7-82c5-f472f777f22a.png)

Thanks,
Justin

**Comment by yurydelendik** [comment]
Can you provide complete source code for the example that reproduces the issue?

**Comment by MrBananaGuard** [comment]
Hi, 

My company is blocking stuff like plunker. I will have to reproduce at home. Is there no documentation that demonstrates a step by step CLI integration with the viewer and thumbnail control.

Thanks,
Justin Darmanovich

**Comment by timvandermeij** [comment]
Closing since no response has been provided and specific Angular questions are out of scope for PDF.js itself. Note that we have a Webpack example at https://github.com/mozilla/pdf.js/tree/master/examples/webpack, which may help you.
