### ISSUE TITLE
Weak Encryption detected by Fortify scans

### ISSUE THREAD

**Issue by lmcguffee** [mozilla/pdf.js#8737]
In our current version this is the file with issues. pdfviewer/build/pdf.worker.js line 7744, line 7745, and line 7763
In the latest version I just pulled down hoping that this was fixed and it isn't, this is the file now: pdf.js-master\src\core\crypto.js line 23 line 24, and line 41

Summary
The call to ARCFourCipher_encryptBlock() at pdf.worker.js line 7763 uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.The identified call uses a weak encryption algorithm that cannot guarantee the confidentiality of sensitive data.

Explanation
Antiquated encryption algorithms such as DES no longer provide sufficient protection for use with sensitive data. Encryption algorithms rely on key size as one of the primary mechanisms to ensure cryptographic strength. Cryptographic strength is often measured by the time and computational power needed to generate a valid key. Advances in computing power have made it possible to obtain small encryption keys in a reasonable amount of time. For example, the 56-bit key used in DES posed a significant computational hurdle in the 1970's when the algorithm was first developed, but today DES can be cracked in less than a day using commonly available equipment.

Instance ID: 76DBA5DF23B75AFD4D7D14B21B49F543
Primary Rule ID: C8EDE160-7B48-42C6-8D4B-051B35E47BD9
Standards and Best Practices
OWASP 2013
A6 - Sensitive Data Exposure
OWASP 2014 Mobile
M6 - Broken Cryptography
PCI 3.2
6.5.3 - Insecure Cryptographic Storage
DISA STIG 4.1
APSC-DV-002010 CAT II
APSC-DV-002040 CAT II
FISMA
MP

This is coming up as a critical issue and we need to upgrade to a version that is corrected with current standards of encryption asap. This will be a issue from more people real soon as they get these scans on the software.

**Comment by yurydelendik** [comment]
PDF.js does not produce PDFs with weak encryption. So the issue looks unrelated.

The issue does not provide/document expected behavior of PDF.js in case if user wants to open PDF with weak encryption. Closing as incomplete.

**Comment by lmcguffee** [comment]
Please look at this again... If you look at the files in question and looked at the encryption methods you are using and read the rest of the original post you will see that you are using a deprecated encryption methods. I am asking for you to update your encryption methods to the latest standards.
Thanks,

**Comment by yurydelendik** [comment]
> I am asking for you to update your encryption methods to the latest standards.

@lmcguffee I'm not sure what do you mean by "pdate your encryption methods to the latest standards". In this case you just asking to stop using encryption and not to follow PDF32000 specification. This means legacy PDF will not be shown for end users. Is it expected behavior?

**Comment by lmcguffee** [comment]
If you read this link and look at the code in the line mentioned you might understand what I'm meaning. 
https://security.stackexchange.com/questions/26765/what-are-the-differences-between-the-arcfour-arcfour128-and-arcfour256-ciphers
The ARCfourCipher is what you are using and it is deprecated.

**Comment by yurydelendik** [comment]
> The ARCfourCipher is what you are using and it is deprecated.

Yes, I understand this part. What I'm asking from you what will be the expected behavior for the viewer if PDF document encrypted using RC4? What you are asking is to remove RC4 support, which mean PDF.js will no longer be capable to read the legacy PDFs.

**Comment by lmcguffee** [comment]
hum... guess that isn't feasible from your prospective. At some point we just can't support vulnerable apps. We will have to move to a different app that isn't vulnerable. At some point more and more of the people using this app will have to do the same. So I'd look at your user base and determine what is best for all. Even Microsoft says we are not supporting older systems.  If the legacy apps are vulnerable then can you realistically support that? I'm hoping that you are looking to move forward. Let me know what you figure out. For now you can close this.

**Comment by yurydelendik** [comment]
> At some point we just can't support vulnerable apps. We will have to move to a different app that isn't vulnerable. 

Any PDF viewer contains code RC4 -- it will not be possible to remove, e.g. you can observe it in Chrome https://pdfium.googlesource.com/pdfium/+/master/core/fdrm/crypto/fx_crypt.cpp#156 . It also can be found in Reader and Mac OSX Preview.

> At some point more and more of the people using this app will have to do the same.

It's their choice. As alternative, we provide source code as open source, so people can easily to remove parts they don't like and deploy custom version of PDF.js instead.

>  If the legacy apps are vulnerable then can you realistically support that?

There is no proof that PDF.js is legacy or vulnerable. You provided proof of existence of ARCFour in our code base, but you did not provide proof that PDF.js uses this algorithm to expose sensitive data that is not already accessible by other means. PDFs are generated by other software which means, which means the sensitive data can be exposed without PDF.js.

**Comment by yurydelendik** [comment]
> Let me know what you figure out.

@lmcguffee I tried contacting Fortify about the false detection. But they require to be a paid customer (?) to provide any support. It will be helpful for the purpose of this report to provide details why they decided to flag PDF.js product as dangerous. So we cannot provide additional information on our side.

**Comment by yurydelendik** [comment]
I received response from Fortify, which somewhat confirms my comments above. To make the response complete, I should probably to be clear in following areas:

- Mozilla's PDF.js, demo viewer or pdfjs-dist as it is packaged, does not encrypt any customers PDF.
- PDF.js (or any other viewers) needs to use RC4 to check if user has particular rights and/or if user provided correct password for some PDF (see the PDF32000 standard specification).
- Good portion of PDFs are encrypted or protected by RC4, so disabling or removing this algorithm will prevent a PDF viewer from opening these PDFs.
- Fortify only detects presence of antiquated encryption algorithms, but it does not detect how algorithm is used, whether it is disabled, or a condition when it's invoked; so the Fortify is merely provides a warning about these algorithms presence. The decision how a particular threat is mitigated falls on its users -- it can be looking into how the algorithm is used, removing it or just not support of PDF viewing.

**Comment by mdutta** [comment]
@yurydelendik  - Any update on Fortify Technical Support case number #00273796 ?

**Comment by ttaylor29** [comment]
Hello, we have this finding as well with our Fortify results. Is there a way to get a copy of this .js file that will ignore this functionality?

**Comment by paru-ramya** [comment]
Hi, was anyone able to find a solution to this problem?
