### ISSUE TITLE
Demo website broken on Edge

### ISSUE THREAD

**Issue by sandorfr** [mozilla/pdf.js#8740]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Microsoft Edge 40.15063.0.0
- Operating system and its version: Windows 10 10.0.15063 Build 15063
- PDF.js version: not sure, but it's the version currently used on the demo website
- Is an extension: no

Steps to reproduce the problem:
1. Open Microsoft Edge
2. Navigate to the demo website : https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot)
display the sample pdf file as on other brothers

What went wrong? (add screenshot)
An error occurs : Function expected, pdf.worker.js (1144,1)
![image](https://user-images.githubusercontent.com/2660262/28906627-2db8122c-785c-11e7-8cef-a4a0f15742ed.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
I'm wondering if the issue might be that IE Edge is passing this check: https://github.com/mozilla/pdf.js/blob/master/src/shared/streams_polyfill.js#L16, despite not actually implementing *proper* streams support?

@sandorfr Could you please check, in the console, what `typeof ReadableStream` returns in Edge?

**Comment by sandorfr** [comment]
Thanks a lot for the quick fix.
