### ISSUE TITLE
Black boxed around links

### ISSUE THREAD

**Issue by sorenfalch** [mozilla/pdf.js#8742]
Link to PDF file (or attach file here):
http://soap.plansystem.dk/pdfarchive/20_1057347_APPROVED_1193694109382.pdf

Configuration:
- Web browser and its version:  
        FireFox 54.0.1 (64-bit) [Does not work]
        Chrome Version 59.0.3071.115 (Official Build) (64-bit) [Works fine]
- Operating system and its version:
        macOS Sierra 10.12.6 (16G29) 
        (Problem is also reproducible on Windows computers)
- PDF.js version:
        1.8.593
- Is an extension:
We are seeing this problem when opening the document directly in FireFox 54 as well as on Chrome when using PDF.JS (both version 1.8.254 and 1.8.593) in our Angular 2 project.
Opening the document directly in Chrome, using the build in viewer, in Acrobat DC (Build: 17.9.20044.222436), or in macOS 'Preview' (Version 9.0 (909.18))  renderes the PDF correctly.

Steps to reproduce the problem:
1. Open the pdf referenced above in FireFox, use internal viewer (PDF.JS)
2. Scroll down to page 2 to see the table of contents. Notice that each line containing a link is enclosed in a black box in FireFox/PDF.JS, in other browsers it is not.

What is the expected behavior? (add screenshot)
Images from Chrome 
![image](https://user-images.githubusercontent.com/2655958/28909626-854dd8b0-7829-11e7-8310-529a095a9a07.png)

What went wrong? (add screenshot)
From FireFox 54 (sorry for the bad scaling):
![image](https://user-images.githubusercontent.com/2655958/28910597-dbc9dbf4-782d-11e7-8eee-b28a50fc5bf7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as invalid, since it looks identical in Adobe Reader:

![link_borders](https://user-images.githubusercontent.com/2692120/28913521-a12562e2-7838-11e7-8850-e3a1a7197740.png)

**Comment by sorenfalch** [comment]
Yes, I see that, didn't check for this issues with Acrobat, but only with Chrome and macOS Preview.
