### ISSUE TITLE
pdfjs@master (f83bd72) incorrect hyphen rendition in Chrome with Font Face disabled

### ISSUE THREAD

**Issue by evadne** [mozilla/pdf.js#8755]
Link to PDF file (or attach file here): 
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/1203350/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Chrome 60.0.3112.90
- Operating system and its version: macOS 10.12.5
- PDF.js version: master (f83bd72)
- Is an extension: No

Steps to reproduce the problem:
1. Pull PDF.js repository locally and run `gulp server`
2. Open two tabs:
  - http://localhost:8888/web/viewer.html?file=%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf#disablefontface=true
  - http://localhost:8888/web/viewer.html?file=%2Fweb%2Fcompressed.tracemonkey-pldi-09.pdf

What is the expected behaviour?
The title area should render correctly in either setting

What went wrong?
Chrome  + Font Face disabled produces incorrect title rendition

ps.
Safari OK
Firefox OK
https://mozilla.github.io/pdf.js/web/viewer.html#disablefontface=true is OK in Chrome as well

![screen shot 2017-08-06 at 20 04 06](https://user-images.githubusercontent.com/104086/29006180-be6c2c58-7ae2-11e7-94ea-cbb16d9a07cf.png)

**Comment by Snuffleupagus** [comment]
WFM, when testing with PDF.js version `2.9.350`, in Google Chrome Beta `91.0.4472.77` on Windows.

If this is still an issue e.g. on MacOS, that'd suggest a platform and/or browser specific bug that we unfortunately cannot fix *here*.
