### ISSUE TITLE
internet explorer print 404 page in iframe 

### ISSUE THREAD

**Issue by salihdemirog** [mozilla/pdf.js#8758]
Sample:    <iframe src="http://mozilla.github.io/pdf.js/web/viewer.html"></iframe>

In chrome no problem

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 8
- PDF.js version: 1.7.225

**Comment by yurydelendik** [comment]
See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12349663/ and https://stackoverflow.com/questions/44547861/ie11-windows-7-print-issue-after-kb4021558

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
