### ISSUE TITLE
Detect page orientation

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8759]
Hi, is there a property in PDF.JS where we can identify if a page's orientation is portrait or landscape?

i figure detecting the width and height is not enough. what if there is a square page so that would not help identify its orientation

please advise

**Comment by Snuffleupagus** [comment]
There's no property in the PDF specification that signal if a page uses portrait/landscape orientation, you'll simply have to compare the width and height yourself (and decide how you want to handle square pages).

Closing as answered.

**Comment by MikeDabrowski** [comment]
@Snuffleupagus I am not entirely convinced. There is also `rotate` attribute. 

The normal portrait A4 pdf has 
```ts
rotate: 0,
width: 595.276,
height: 841.89
```
The same pdf but rotated using acrobat tool:
```ts
rotate: 270,
width: 595.276,
height: 841.89
```
And a pdf created via google docs in landscape mode
```ts
rotate: 0,
width: 842,
height: 596,
```
when opening such pdf in browser reader or acrobat the second and third show as landscape. And should be rendered that way. But if you only compare the width/height it will not appear as 'landscape'
