### ISSUE TITLE
Some PDF's not displaying text properly on Desktop Safari/iOS Safari

### ISSUE THREAD

**Issue by buzzyboy** [mozilla/pdf.js#8760]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Safari 10.1.1 & iOS (10)s Safari
- Operating system and its version: Mac OS Sierra 10.12.5
- PDF.js version: All
- Is an extension: No

Steps to reproduce the problem:
1. Open attached PDF in PDFJS
2. Notice some text isn't displayed and that hearts and rendered in iOS Safari.

What is the expected behavior? (add screenshot)
<img width="958" alt="screen shot 2017-08-07 at 2 57 42 pm" src="https://user-images.githubusercontent.com/7034667/29047512-d27dfb10-7b80-11e7-8dcd-e72b7cd160eb.png">

What went wrong? (add screenshot)

Desktop:
<img width="1463" alt="screen shot 2017-08-07 at 2 59 10 pm" src="https://user-images.githubusercontent.com/7034667/29047554-ff06419c-7b80-11e7-9950-5fd604d01112.png">

iOS Safari: 
![screen shot 2017-08-07 at 3 22 54 pm](https://user-images.githubusercontent.com/7034667/29048208-55aad5dc-7b84-11e7-8849-da9611f1dbfc.png)

Here is the PDF File:

[HeartsIssue.pdf](https://github.com/mozilla/pdf.js/files/1206326/HeartsIssue.pdf)

**Comment by timvandermeij** [comment]
Related to #8267?

**Comment by buzzyboy** [comment]
@timvandermeij I took a look at #8267 and it appears the same fix fixes my issue as well. We can close this issue already! Thank you!
