### ISSUE TITLE
viewer.html not loading demo pdf in Microsoft Edge

### ISSUE THREAD

**Issue by luminousmg** [mozilla/pdf.js#8763]
Hello,

I have cloned the latest master on Ubuntu 16.04 and installed the prerequisites.  

I am able to view the demo pdf  with the web viewer on chrome, (/pdf.js/web/viewer.html) but not on Microsoft's Edge browser.  (Microsoft Edge 38.14393.1066.0)

The viewer itself renders on Edge, but the PDF never renders.  No errors appear in the developer console.

Any idea what could be going on?  Something I could have missed in setup?

Thanks in advance for any insight!

Best Regards

**Comment by timvandermeij** [comment]
Did you clone this recently? Just a few days ago a fix has been pushed specifically for Edge after a big change in core logic landed (https://github.com/mozilla/pdf.js/commit/6beb925f0baabc5abba0397d372932055b8fb459). Does the demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html work in Edge for you?

**Comment by luminousmg** [comment]
Hello,

https://mozilla.github.io/pdf.js/web/viewer.html works for me in Edge.

I cloned it yesterday with no luck in Edge.  (I cleared Edge's cache etc..)  I double checked the code changes in src/shared/streams_polyfill.js and they are there.

In the top title of the Edge's tab, I can see the title flash from "PDF.js Viewer" to "PDF.js Viewer (not responding)", then the file name of the demo pdf appears, but the pdf itself does not render.

A warning also appears in the console:

`DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
viewer.html`

I'm wondering if there is something strange going on with my server config?

Thanks again for your insight.

**Comment by timvandermeij** [comment]
The demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html works in Edge, so it must be something related to your build or your server. You can try running PDF.js locally in Edge using the steps in https://github.com/mozilla/pdf.js#getting-the-code. If that works, then at least you know that it's a server issue. If that doesn't work, most likely Edge has problems processing non-built PDF.js versions. You can follow the steps at https://github.com/mozilla/pdf.js#building-pdfjs to build the code, or use the pre-built version at https://github.com/mozilla/pdfjs-dist which is updated everytime code is merged.

Closing as answered.
