### ISSUE TITLE
How to print pdf via pdf.js

### ISSUE THREAD

**Issue by abramhum** [mozilla/pdf.js#8766]
Link to PDF file (or attach file here):
https://cdn.rawgit.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf
Configuration:
- Web browser and its version: chrome
- Operating system and its version: windows 10
- PDF.js version: 1.7.225
- Is an extension:

I use pdf.js to show the pdf in the browser, but faced with a problem. How can I print the pdf via a print button, acting as the print function in view.js.

**Comment by timvandermeij** [comment]
The default viewer uses `PDFPrintService` for printing. Refer to https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js and `app.js` for how to use it.

**Comment by abramhum** [comment]
Thanks a lot.

**Comment by Mmax2048** [comment]
kjkjkjh
