### ISSUE TITLE
chunk.worker.js not found

### ISSUE THREAD

**Issue by chrisbenseler** [mozilla/pdf.js#8769]
Hi

I'm using PDFJS in an Angular 4 app, it works fine, expect for the fact that the browser always outputs this error:

 GET http://localhost:4200/10.chunk.worker.js 404 (Not Found)
![screenshot from 2017-08-10 11-12-49](https://user-images.githubusercontent.com/1225447/29174494-e36caa5a-7dbc-11e7-9bbe-3979848f9ae6.png)

The script is searching for this 10.chunk.worker.js in the '/' 
I don't know how to deal with it. Can't find anything in the docs about some configuration or something related.
Could anyone help me about this? Am I missing something?

**Comment by chrisbenseler** [comment]
I can do something like:

const workerSrc = require('pdfjs-dist/build/pdf.worker');
const pdfjsWorkerBlob = new Blob([workerSrc]);
const pdfjsWorkerBlobURL = URL.createObjectURL(pdfjsWorkerBlob);

The error does not appear anymore, but then the console throws those warnings:

> The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
> pdf.js:346 Warning: Setting up fake worker.

**Comment by timvandermeij** [comment]
I have not seen that error before. Did you build PDF.js according to https://github.com/mozilla/pdf.js#building-pdfjs, or do you use https://github.com/mozilla/pdfjs-dist?

**Comment by timvandermeij** [comment]
Closing since no response has been provided and specific Angular questions are out of scope for PDF.js itself. The mentioned links should give enough instructions on how to get PDF.js working in the general case.
