### ISSUE TITLE
PDF reflow (not an issue)

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#8772]
This is not an issue, but a notification of a new feature.
I used PDFJS to reflow PDFs in the browser.
You can search for PDFs from https://docushow.com and see an example document here:
https://docushow.com/viewdoc?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fresearch%2Fwp-content%2Fuploads%2F2016%2F02%2FMobileHCI2011-Panjwani-reflow.pdf&title=Script-Agnostic%20Reflow%20of%20Text%20in%20Document%20Images%20-%20Microsoft#0

Would it be something useful for PDFJS?

Laurent

**Comment by timvandermeij** [comment]
I don't think this should be included in PDF.js by default, but please feel free to add your project to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications. It may be useful for other people that want to work on a mobile/responsive viewer. Thank you!

**Comment by rmhrisk** [comment]
@ldenoue is there a PR with your changes anywhere? I am interested in this.

**Comment by ldenoue** [comment]
@rmhrisk No, I decided to continue work on this on my own at the moment.

**Comment by epitron** [comment]
This would be an amazing feature!

It's incredibly rare to find PDF viewers which do this (I only know of one, and it's was discontinued 5 years ago), but it makes reading documents far more enjoyable. I hate having to continually reposition the page while reading, and many PDFs are unusable on certain devices (mobile, ebook) without this feature.

**Comment by ldenoue** [comment]
What was that app that was discontinued 5 years ago?
For now you can use DocuShow.com to view your PDFs on mobile.
But I'm also working on a native iOS app. Would Android be useful?

**Comment by epitron** [comment]
The app is called QuickOffice: https://play.google.com/store/apps/details?id=com.quickoffice.android

You activate reflow mode by going to "Reading View" in the hamburger menu. Google bought up the company that made it, then ditched it a few years later.

DocuShow is very nice! It works well on the desktop, but I was having trouble running it in Brave on Android. It was coming up blank.

One immediate feature I'd like is the ability to upload a PDF without supplying the URL.

(Maybe we should take this conversation to the DocuShow issue tracker... :)

**Comment by AntonOfTheWoods** [comment]
Has the situation changed at all on this feature? @ldenoue , was the stuff you were working on open source at all? I am interested in something basic that works for relatively simple cases. Basically if it can keep paragraphs separate then it would be reasonably fit-for-purpose. I also came across https://github.com/JSTOR-Labs/reflowit but that doesn't really do what I need (I need HTML like PDF.js produces, not another PDF or an image), and also hasn't seen any activity in half a decade...

**Comment by ldenoue** [comment]
@AntonOfTheWoods not open sourced and my tech cuts out page images into small word images to perform reflow, adding back a text inside each.
I since moved the web demo and released an iOS app called PDF Reflow here https://www.appblit.com/pdfreflow
