### ISSUE TITLE
Get page number of document pdf in WebView android

### ISSUE THREAD

**Issue by Henqsan** [mozilla/pdf.js#8773]
Configuration:
- Web browser and its version: WebView Android
- Operating system and its version: Android 4.1 or +
- PDF.js version: pdfjs-1.7.225

Steps to reproduce the problem:
1. I can not get the page number from the pdf file and move to the android webview

What is the expected behavior? (add screenshot)

I need to get the page number from the pdf file and move to the android webview.

**Comment by timvandermeij** [comment]
You can get the page number using https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L154. To set it, use https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L161.
