### ISSUE TITLE
New line not recognised and instead combines words together without a space

### ISSUE THREAD

**Issue by pchasty** [mozilla/pdf.js#8777]
We are trying to implement our own search into viewer.js that avoids partial matches. 
However we are not getting accurate results as the var 'pageContent' string contains words that have been joined together due to pdf.js not recognising or dealing with new lines. 
This is also observed when copying and pasting text that includes new lines from the pdf rendered by pdf.js, and contrasts with behaviour shown by Adobe with dealing with new lines. 

Bug can be observed on the pdf.js demo.

Configuration:
- Google Chrome 54.0.2840.99 m (64-bit)
- Windows 7 Enterprise 6.1.7601
- pdfjs-1.8.188 and viewable in demo PDF.js: 

Steps to reproduce the problem:
1. Copy and paste from the title of the demo pdf, or anywhere where a new line can be observed
2. Paste into a text editor 

What is the expected behavior?
The pasted text should be:
Trace-based Just-in-Time Type Specialization for Dynamic Languages

What went wrong?
The pasted text is:
Trace-based Just-in-Time Type Specialization for DynamicLanguages
(where the words 'Dynamic' and 'Languages' have been joined together rather than separated by space)

**Comment by timvandermeij** [comment]
This a known issue and I think previously a patch was proposed to fix this (#5783), but it was never finished. If someone likes to work on that, please feel free to do so.

**Comment by Siddhinita** [comment]
@timvandermeij , I want to work on this issue.

**Comment by timvandermeij** [comment]
It's yours! Contact us on IRC if you have questions.

**Comment by rossdash** [comment]
has any progress been made with this issue?

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
