### ISSUE TITLE
PDF.js doesn't work in IE11 - Error: Access is Denied/This page is accessing information that is not under its control.

### ISSUE THREAD

**Issue by kherbertc** [mozilla/pdf.js#8782]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Internet Explorer 11
- Operating system and its version: Windows 7
- PDF.js version: 1.7.225
- Is an extension:

Steps to reproduce the problem:
1. Open Internet Explorer 11
2. Open a file using the viewer

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/31042874/29324787-5f7c8378-81b3-11e7-9e93-5ca9c836bbb8.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/31042874/29324773-539a6016-81b3-11e7-9482-6c530cfd0a92.png)

The line below is causing a cross domain request in Internet Explorer . If you change it to the following, pdf.js works:

pdf.worker.js
Current
![image](https://user-images.githubusercontent.com/31042874/29324885-ac28d3ca-81b3-11e7-86ae-a31665a8ec4d.png)

Fix
![image](https://user-images.githubusercontent.com/31042874/29325068-62022e8a-81b4-11e7-8dff-eb0fe720e7ee.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
'moz-chunked-arraybuffer' is mostly Firefox specific and will be replaced by fetch() soon. I recommend to add user agent sniffing (or other means), and if it's not Firefox derived browser skip the check.

**Comment by kherbertc** [comment]
Thanks, I’ll update my instance of the code.

Best,

Keith

**Comment by Siddhinita** [comment]
@kherbertc  Can I work on this issue?

**Comment by kherbertc** [comment]
I'm just making this change for my web application.

**Comment by Rud156** [comment]
@kherbertc Is this issue resolved?? Else I would love to work on it.

**Comment by timvandermeij** [comment]
AFAIK PDF.js is now using the Fetch API, so I'm not sure if this is still relevant?

/cc @yurydelendik @mukulmishra18

**Comment by hallvors** [comment]
The code is now here and no longer references example.com :
https://github.com/mozilla/pdf.js/blob/75dc2bbd359990ebb1c1484f204acf66c3cb8221/src/display/network.js#L56 
The fix: https://github.com/mozilla/pdf.js/commit/a05115d2ec27866ccf16cc4c550f225f054037fd

**Comment by hallvors** [comment]
@timvandermeij I don't have permissions to close this issue but per my comment above it is fixed :)

**Comment by timvandermeij** [comment]
Thank you for the confirmation! I'm closing the issue then.
