### ISSUE TITLE
I am getting a 500 error when trying to use blob url in internet explorer with PDFjs works fine in all (non IE) browsers

### ISSUE THREAD

**Issue by judsonmusic** [mozilla/pdf.js#8784]
Link to PDF file (or attach file here):
![screenshot 2017-08-16 12 07 26](https://user-images.githubusercontent.com/2080617/29373209-7f0ea090-827b-11e7-8486-a78244aab949.png)

Configuration:
- Web browser and its version: ie11
- Operating system and its version: windows 10
- PDF.js version: v1.8.188
- Is an extension:

Steps to reproduce the problem:
1. open view with blob URL in internet explorer
2.http://localhost:9001/pdfjs/viewer.html?file=blob%3Ahttp%3A%2F%2Flocalhost%3A9001%2Fb42fb21f-5758-42d2-a154-43807b013195

What is the expected behavior? 
I shoud see a PDF.

What went wrong? (add screenshot)
i get the error as you see in screen shot

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): n/a

**Comment by yurydelendik** [comment]
Complete example is needed.

**Comment by timvandermeij** [comment]
Closing until the example is provided. There is nothing we can do with this right now.

**Comment by judsonmusic** [comment]
I got it working thanks.

**Comment by vinsee** [comment]
May I know how you make it works?
