### ISSUE TITLE
How to receive complete message when the canvas is drawing completed via using PDF.js

### ISSUE THREAD

**Issue by abramhum** [mozilla/pdf.js#8786]
Link to PDF file (or attach file here):
PDF.js

I using PDF.js to parsing PDF and show the result on the web pages. The main problem is the 
rendering method is much like working via thread, that means I can't know when the canvas is 
drawing completed. 
the code snippet is like following:
`
   var context = canvas.getContext('2d');
                    var viewport = page.getViewport(1);
                    canvas.height = viewport.height;
                    canvas.width = viewport.width;
                    canvas.style.height = "1000px";
                    canvas.style.width = "900px";
                    var renderContext = {
                            canvasContext: context,
                            viewport: viewport
                        };
                  page.render(renderContext);
`
I hope to get the DataURL of canvas when the page is render complete, but how to do that by 
programming? thanks a lot.

**Comment by timvandermeij** [comment]
You can use `page.render(renderContext).then(...)` to perform actions after rendering is completed. Refer to https://github.com/mozilla/pdf.js/blob/c26e49724400fb2c463f3348c8322daefc9539ed/examples/learning/prevnext.html#L74 for example.

**Comment by abramhum** [comment]
Thanks a lot.
