### ISSUE TITLE
Listen to custom event of parent document in pdf.js iframe

### ISSUE THREAD

**Issue by divyameher** [mozilla/pdf.js#8787]
I have a custom event created in parent document and I need to listen to that event and on every trigger of the event I need to show or hide a button inside iframe
I have tried as following inside iframe:
```
$(window).on('customEvent',function(){
alert("Event triggered");
})
```
This code block is executing only on loading of full page or on refresh but not for every event triggering

**Comment by timvandermeij** [comment]
It really looks like this is not related to PDF.js specifically, but rather to listening for events in IFrames in general. PDF.js should not override anything related to this. Closing since no example code is provided to investigate further.
