### ISSUE TITLE
Can you add a distance tool?

### ISSUE THREAD

**Issue by donnyv** [mozilla/pdf.js#8791]
Viewing CAD drawings in PDF is very common. It would be aswesome if you guys/girls could add a distance tool with the ability to change the scale ratio. Like in Adobe Acrobat, it would be extremely handy. 
![capture](https://user-images.githubusercontent.com/2224189/29471897-bec33e9e-841f-11e7-9002-8be3b4d32526.PNG)

**Comment by Snuffleupagus** [comment]
This feature seems like enough of a special use-case that it's most likely *not* worth the added code/complexity to try and implement something like this; closing as WONTFIX.

**Comment by donnyv** [comment]
Maybe as a plugin?
