### ISSUE TITLE
change path of PDFJS imageResourcesPath 

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8793]
i tried to set it like this

PDFJS.imageResourcesPath  = '/folder/web/images/';

but when i rescale the zoom value, it does not use the annotation-comment.svg

when or where do we need to override the value for this so that a different image folder path is used?

please advise

**Comment by Snuffleupagus** [comment]
> PDFJS.imageResourcesPath

Note that in PDF.js version `2.0` the global `PDFJS` object has been removed, and this option has been changed to an `AnnotationLayer ` parameter; see https://github.com/mozilla/pdf.js/blob/ecbdc508f7d872d2a734932ce12cb96153b004aa/src/display/annotation_layer.js#L32-L33

> when or where do we need to override the value for this so that a different image folder path is used?

Without a complete, and importantly runnable, example it's basically impossible to help here; refer to https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md.

**Comment by timvandermeij** [comment]
Closing since this is answered above. Otherwise, please provide more information to reproduce the issue.

**Comment by chitgoks** [comment]
example here is the folder structure

./www
    ./myviewer
        ./pdfjs
        ./custom_images

so all files are in the pdfjs folder (build, web). when i run the viewer in ..../pdfjs/web/viewer.html i would like to set the folder for the images that your annotation layer uses programmatically.

is that possible? thank you

**Comment by timvandermeij** [comment]
Yes, this is outlined in https://github.com/mozilla/pdf.js/issues/8793#issuecomment-430591745, i.e., you can give the `imageResourcesPath` parameter.
