### ISSUE TITLE
Some pdf contents are pictures,and header and footer could not be show

### ISSUE THREAD

**Issue by hymne** [mozilla/pdf.js#8798]
Link to PDF file (or attach file here):
the problem pdf is,use pdf tool show is fine
[output_34.pdf](https://github.com/mozilla/pdf.js/files/1241137/output_34.pdf)
i use the pdf.js example demo code show result like thise
![image](https://user-images.githubusercontent.com/25024419/29493041-358469b2-85c0-11e7-834d-57efc1a007a0.png)

Configuration:
- Web browser and its version: chrome 60.0.3112.101 
- Operating system and its version:win7
- PDF.js version:pdfjs-1.8.188-dist
- Is an extension:

Steps to reproduce the problem:
1. both open the problem pdf use pdfjs example and other pdf tools,compare the diffrents
2. under the search，i found that the problem pdf contents are pictures,and thier had been combined
What is the expected behavior? (add screenshot)
show the header and footer

What went wrong? (add screenshot)
couldn't show header and footer

**Comment by THausherr** [comment]
This file contains an inline image. These are meant to be 4KB or less, see page 214 of the PDF 32000 specification. Yours is 74KB. Btw you forgot to compress it. Now inline images have the problem that it is tricky to detect their end. This is "EI". However sometimes big images have "EI" in the image sequence, so more heuristics are needed. In your image, after the "EI" there is a space, then a zero, then a "Q". Why the zero? I suspect that it fools the heuristics.

**Comment by hymne** [comment]
@timvandermeij thx for you answer.I'm a new guy for this,I try to compress the pdf use https://smallpdf.com ,it’s worked,but i don't know the compress algorithm which their use.How can i compress it use pdf.js,can you show  a exmample or function ?  thanks for sincerely.

**Comment by THausherr** [comment]
@hymne your text is unclear. Was the file you attached modified with smallpdf.com? Does the original file display here? Then contact them and point them to page 214 of the PDF 32000 specification. Your file was created last friday and modified yesterday.

**Comment by hymne** [comment]
@timvandermeij ok,thx your suggest.The problem page is just one page in original pdfs.I splited it use iText.The original file also can't display in this page,but adobe reader display well...

**Comment by THausherr** [comment]
Yes, Adobe does its best to displays bad files. Was the original page created in your company, and what software was used?

Btw I am not "timvandermeij" I'm "THausherr".

**Comment by hymne** [comment]
@THausherr oh! sorry sorry，the original pdf was not created by my company,we just splited it into pages,i try to contact them what they use.

**Comment by THausherr** [comment]
Thanks... my hope is that they're just starting at this, so that they can fix this weird file by not using inline images this way, and so we don't get such files into the wild.

Btw I don't speak for PDF.js. I'm with a different project (pdfbox) and your file fails there too :-)  (Likely, because many developers think similarly)

**Comment by hymne** [comment]
@Snuffleupagus Thank you for your resolved the isuue,i update your version,it works well.Today is my projoect's deadline,and...umh....I appreciate your help,your are a very very very good person.

**Comment by hymne** [comment]
sorry for client's required,the pdf Involving confidentiality,i have to remove the pdf link...  if somebody want to test,you can contact me by hymne@qq.com.

**Comment by Snuffleupagus** [comment]
> sorry for client's required,the pdf Involving confidentiality,i have to remove the pdf link...

First of all, the fact that you've removed the link does not mean that the file is suddenly unavailable. It's actually still available via GitHub, and the link is now checked in to the repo (see https://github.com/mozilla/pdf.js/pull/8800/files#diff-c8d67ab2dbcb03ca57b7ccd6d5ab7c9f).
Second of all, as part of fixing the display of corrupt PDF files like this one, it's absolutely *imperative* that we add regression tests since otherwise this could easily break again at any time.

@hymne If you want the file completely removed, then you'll probably need to contact GitHub support to inquire about that. However, I'd ask that you please do *not* do that *unless* you're able to produce a replacement file (displaying the same issue) that we can use for testing!

**Comment by THausherr** [comment]
I'll try to create one. Hopefully tonight.

**Comment by sinosoft-shie** [comment]
@Snuffleupagus get it.I remove the screenshot and link from the isuue's description.Just let my customers seems to their have bean removed.I'm sorry for trouble u,and hope it will not affectting the test

**Comment by THausherr** [comment]
[PDFJS-8798-test1.pdf](https://github.com/mozilla/pdf.js/files/1249365/PDFJS-8798-test1.pdf)
[PDFJS-8798-test2.pdf](https://github.com/mozilla/pdf.js/files/1249366/PDFJS-8798-test2.pdf)
PDFJS-8798-test1.pdf: Diagonal line doesn't appear in old version, appears in new version.

PDFJS-8798-test2.pdf: that is the file I created first and so I wondered why one image was missing. It shows a flaw in the "EI" detecting strategy, which you may or may not want to correct. The difference to the first file is that this one has several inline images.

The inline images are rendered blurry, see #8245.

The files were created by myself for the PDFBox project and modified by myself and are Apache licensed.

**Comment by Snuffleupagus** [comment]
@THausherr Thanks a lot for your help with reduced test-cases!
For the remaining issue, can you please file a new issue about that (since we want to limit each one to just *one* problem)?
