### ISSUE TITLE
uncaught exception: Error: bad XRef entry

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8799]
This only happens in Firefox because probably of the default pdf.js viewer. but even then, after i disabled it and used acrobat reader as the default pdf viewer same error messages shows up and does not load the pdf.

i have my own custom html file that loads pdf.js libraries. and then i get that error

anyone has ideas?

**Comment by yurydelendik** [comment]
Hard to tell without PDF and the example that reproduces the problem. Closing the issue as incomplete.
