### ISSUE TITLE
Zoom is too sensitive on OS X

### ISSUE THREAD

**Issue by staktrace** [mozilla/pdf.js#8802]
(Filing this as an upstream bug for https://bugzilla.mozilla.org/show_bug.cgi?id=1392361)

Link to PDF file (or attach file here): https://www.library.yorku.ca/spark/books_journals_more/PARCA%20Test_Final.pdf (or any PDF)

Configuration:
- Web browser and its version: Firefox 55+
- Operating system and its version: OS X 10.11.6
- PDF.js version: Whatever's in Firefox now
- Is an extension: no?

Steps to reproduce the problem:
1. Load PDF
2. Pinch zoom on macbook trackpad, or scroll using ctrl+two finger pan

What is the expected behavior? (add screenshot)
Page zooms gradually

What went wrong? (add screenshot)
Page zooms far too much

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by lizzard** [comment]
I'm also seeing this problem on MacOS 10.12.6 with default zoom/pinch system settings.

**Comment by schneeschmelze** [comment]
For the record: No change in Firefox 60. :(

**Comment by davidanderle** [comment]
I'm having the same issue on Windows 10. Zooming with pinch is too sensitive.

**Comment by dimonoid** [comment]
Windows 10 1703, still a the same. Carbon X1 4th gen

**Comment by lxieyang** [comment]
Same on macOS 10.14. Too sensitive.

**Comment by Nariety** [comment]
Firefox 68.0b3, the issue still persists. The pdf touchpad zooming is too sensitive to the point where it's unusable.

**Comment by bubblefoil** [comment]
I may have a related issue. I use a Logitech mouse with smooth scroll feature. With Logitech SetPoint extension the browser correctly interprets mouse wheel events with decimal deltaY, e.g. 0.025, and scrolls perfectly smoothly. It also handles ctrl-wheel zoom quite well. But PDF viewer does not. It does either nothing or zooms way too much.
I've tried logging wheel events. Indeed, there is many of them with small delta.

**Comment by dimonoid** [comment]
Can confirm. It is still an issue on ThinkPad x1 carbon 4th gen. Whel using either track point or trackpad. When I use mouse wheel instead, it works just fine.

**Comment by namasaki** [comment]
still not fixed

**Comment by locness3** [comment]
Yeah, still present, firefox 75

**Comment by ViacheslavLabs** [comment]
Still not fixed, firefox 78

**Comment by dimonoid** [comment]
Windows 1909, ThinkPad x1 carbon 4th gen, still not fixed

**Comment by Shararazer** [comment]
Still there in MacOS 10.15.6 and Firefox 78.0.2 and no update from Firefox support either.

**Comment by locness3** [comment]
:O

**Comment by bubblefoil** [comment]
In the version linked in the pull request, mouse wheel zoom on Windows does not work at all.

**Comment by staktrace** [comment]
> In the version linked in the pull request, mouse wheel zoom on Windows does not work at all.

Can you provide more specific details - Are you using pdf.js standalone, or in Firefox? If so, what version of Firefox? What kind of mouse hardware do you have?

**Comment by bubblefoil** [comment]
> 
> 
> > In the version linked in the pull request, mouse wheel zoom on Windows does not work at all.
> 
> Can you provide more specific details - Are you using pdf.js standalone, or in Firefox? If so, what version of Firefox? What kind of mouse hardware do you have?

I opened the first of the 2 links in this post in the latest FF version by that time. It just updated to 80.0 so the one before that.
https://github.com/mozilla/pdf.js/pull/12203#issuecomment-673301757

I have Logitech M705 with enabled smooth scrolling.
