### ISSUE TITLE
Improve development workflow of examples/node/pdf2svg.js

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#8803]
pdf2svg.js depends on a built version of PDF.js, as follows:

https://github.com/mozilla/pdf.js/blob/7e4c69eccfd5ad841054ca179ae17369ba4b8de6/examples/node/pdf2svg.js#L16-L17

This seems acceptable for end users, but it is a nightmare for development. It takes too long (in the order of minutes?) to finish `gulp dist-install`. Is it possible to have a workflow where we can have:

1. Edit PDF.js core file
2. (optionally, some very short step in between - at most a few seconds)
3. Run pdf2svg.js

**Comment by timvandermeij** [comment]
Isn't it much easier to just use the default viewer and run `PDFViewerApplication.preferences.set('renderer', 'svg');` in the console? After a refresh, it will be using the SVG back-end. That's how I use the SVG back-end for development.

**Comment by Rob--W** [comment]
That could work for environment-agnostic logic, but not when debugging issues that are specific to Node.js, e.g. the absence of mocked DOM APIs, or conditional logic for Node.js such as:
https://github.com/mozilla/pdf.js/blob/5a52ee0a795ca41f27ede587dc494cd304dc81e1/src/display/svg.js#L108-L141
