### ISSUE TITLE
Chrome: Text rendered with SVG backend looks like garbage & text disappears while scrolling

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#8804]
Chromium (60.0.3112.90, Linux) seems to have a difficulty with rendering a PDF with the SVG backend: https://www.pdflib.com/fileadmin/pdflib/Cookbook/pdf/footnotes_in_text.pdf (from #8796). (looks fine in Firefox 55)

Steps to reproduce the problem:
1. Open the viewer: https://mozilla.github.io/pdf.js/web/viewer.html?file=https://cors-anywhere.herokuapp.com/https://www.pdflib.com/fileadmin/pdflib/Cookbook/pdf/footnotes_in_text.pdf
2. Change rendering backend to SVG: Run `PDFViewerApplication.preferences.set('renderer', 'svg');` in the console.
3. Reload the page (this opens the viewer with the above PDF. Alternatively, if you haven't set `file=`, you can save the PDF, and use the "Open file" button to open the file).

Look at the result. There are two bugs:

1. Text looks like garbage.
2. Scroll up and down, and the text seems to flash away and back beyond a certain point.

Both bugs go away if you change the browser zoom, window size, or the zoom level in PDF.js.

![chrome-60-pdf-svg](https://user-images.githubusercontent.com/1365071/29541906-7930aff0-86d7-11e7-9d1e-31e79903edd7.gif)

For bug 2, I guess that it might have something to do with compositing layers. I enabled the "Composited render layer borders" flag at `chrome://flags` (visit `chrome://flags/#composited-layer-borders` ) and indeed, the point where the text disappears/appears is exactly the edge of a compositing layer:

![chrome-60-pdf-svg-with-frames](https://user-images.githubusercontent.com/1365071/29542085-f5edad94-86d8-11e7-962a-09ee1450c072.gif)

I think that this might be a bug in Chrome, since it looks good in Firefox 55.

**Comment by Rob--W** [comment]
This seems like a regression in Chromium:

- 53.0.2785.116 - bug-free
- 54.0.2840.90 - bug 1 (text looks like garbage)
- 55.0.2883.75 - bug 1 (text looks like garbage)
- 56.0.2924.87 - bug 1 (text looks like garbage)
- 57.0.2987.110 - both bugs are present
- 60.0.3112.9 - both bugs are present (this is the current stable version of Chrome)

For bug 1, I did a bisect on Chrome using bisect-builds.py. The result does not show any obvious offenders...:
>You are probably looking for a change made after 407005 (known good), but no later than 407027 (first known bad).                                                                                                                                                              
>CHANGELOG URL:                                                                                                                                                                                                                                                                 
>  https://chromium.googlesource.com/chromium/src/+log/f0829bf6d80a9109b399580fe48d8c3e1c66eeed..dc5d0632171363ab683aa84754db3b35d6ed39a8

**Comment by vpegado** [comment]
The character spacing looks like a white space preservation issue affecting the result of the values in the `svg:tspan[x]` attribute.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space

if you inspect the document, select one of the `svg:tspan` and set the style attribute `white-space: pre;`, does it make things look better?

**Comment by Rob--W** [comment]
@vpegado No, applying `white-space:pre` does not help.

I tested as follows:

1. Open the viewer (with the SVG renderer enabled as in step 1).
2. Type the following in the console:

    ```javascript
    document.body.insertAdjacentHTML('beforeend', '<style>svg{white-space:pre}</style>');
    ```
3. Refresh the page (F5) and press Enter in the console as soon as the page has loaded (but before the PDF has rendered)

If you change the style when the SVG has already been rendered, then the styles are recalculated and you would mistakenly believe that changing the style fixes the issue (similar to how resizing/zooming also removes the buggy effect, as reported in the initial report).
