### ISSUE TITLE
Change text displayed in browser?

### ISSUE THREAD

**Issue by pixels-dude** [mozilla/pdf.js#8805]
This is more of a newbie question rather than an issue: I just started playing with pdf.js few days ago and I'd like to hook into it to change the displayed text in the browser.

I'm NOT trying to modify the PDF, just hook into pdf.js to modify the text shown in browser, nothing more.

I spent at least 20 hours looking at the source code, the best I could come up with is change `canvas.js > CanvasGraphics_showText()` to modify the `glyphs` array, ie.

`        let obj = {
            accent: null,
            fontChar: "k",
            isInFont: true,
            isSpace: false,
            operatorListId: undefined,
            unicode: "k",
            vmetric: undefined,
            width: 513
        };
        glyphs.unshift(obj);`

It almost works (text selection is screwed, of course), I really think I can come up with a better solution if I keep looking

Is that possible? At this point, I'm so desperate I'd be OK if I have to fork my own copy of pdf.js just to change few lines to suit my needs.

Thanks in advance!

**Comment by yurydelendik** [comment]
PDF just contains list of glyphs (codes) that PDF.js prints in right location. CanvasGraphics_showText is right place. You need to adjust text layer for right selection as well (PDF.js is trying to convert glyphs to proper unicodes/text using different algorithm). There is no better solution. I'll close this issue as answered.

**Comment by pixels-dude** [comment]
Thank you very much Yury,

Glad to know I'm on the right track, adding just one char to the glyphs list screw up the text layer font *size*, so that why I'm looking for the "source", ie. where (in which function / line) does pdf.js read those glyphs.

My idea is if I can hook into pdf.js after it reads the glyphs but *before* it calculate other parameters (like width), then I'll reach my goal of changing the displayed PDF.

Can you please guide me where pdf.js read those glyphs?

Thanks in advance!
