### ISSUE TITLE
pdf file won't load

### ISSUE THREAD

**Issue by Yldreath** [mozilla/pdf.js#8811]
I am currently building a search engine using elasticsearch. My query takes the path of my local file and hyperlinks it to my page. My query is working fine but when I click on the link, it gives me this error

PDF.js v1.8.188 (build: ad1023ff)
Message: file origin does not match viewer's

file:///home/server/documents/test.pdf is the file needed to be loaded.

Below is my code :
{ 

	$path  = $response['hits']['hits'][$i]['_source']['file']['url'];
	$title  = $response['hits']['hits'][$i]['_source']['meta']['title'];

	?>

	<div>

		<a href = "web/viewer.html?file=<?php echo $path?>"><?php echo $title?></a>

	</div>

	<br>

	<?php
						
}

**Comment by Rob--W** [comment]
If `$path` really looks like `file:///home/.../test.pdf`, then that is the issue. It is a security feature of browsers to not permit `file:`-URLs from being loaded from web pages.

If the file and server are hosted on the same system, then you need to make the PDF accessible via the HTTP server, and refer to the public URL of the PDF at your server.
