### ISSUE TITLE
Can I become viewer.html into viewer.php to get languages variables? My project is multilingual

### ISSUE THREAD

**Issue by gusbemacbe** [mozilla/pdf.js#8814]
Configuration:

- Web browser and its version:
  - Firefox Mozilla 54
  - Google Chrome 60
  - Safari 10.1.2
- Operating system and its version:
  - macOS Sierra 10.12.6
  - Manjaro Linux 17
- PDF.js version:
  - 1.9 Beta
- Is an extension:
  - No

For example;

- In the file folders, there are different languages files:

  - en.php:

    ```
    $language = 'en;
    ```

  - fr.php:

    ```
    $language = 'fr;
    ```

- In the file view.php, instead of html:

```
    <script type="text/javascript">
      PDFJS.locale = '<?php echo $language?>';
    </script>
```

- In the file index.php:

```
        <iframe src="viewer.php#zoom=page-width" width="100%" height="400" style="border: 1px solid black;"/>
```

**Comment by yurydelendik** [comment]
yes, that's correct way to do it, or (depends on `<script>` location):

```
  <script type="text/javascript">
      window.PDFJS = { locale :'<?php echo $language?>' };
    </script>
```

Closing as answered.
