### ISSUE TITLE
Prebuilt version missing compatibility.js

### ISSUE THREAD

**Issue by juhajokela** [mozilla/pdf.js#8818]
Prebuilt version should have a file web/compatibility.js
(documented on page: https://mozilla.github.io/pdf.js/getting_started/)

However, when I download either stable or beta version, the file seems to be missing.

**Comment by Snuffleupagus** [comment]
With PR #8102, `compatibility.js` is now bundled directly into `pdf.js` and `pdf.worker.js` thus removing the need for a standalone file in custom deployments.

The FAQ was updated to mention this, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, but it appears that we forgot to also update the document that you refer to.
