### ISSUE TITLE
Extract Text with complete html tags 

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8827]
I need to get complete text format with tags or extract data in json format but only text is appear in logs so who to get text with complete tags or in json format ?

**Comment by timvandermeij** [comment]
You can only get the full text using e.g., https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js. There is no possible output as JSON or with HTML tags. This is mainly because the PDF format does not always allow us to tell if e.g., text is bold/underlined. Closing as answered.

**Comment by SOftEngrAtta** [comment]
Ok thanks
