### ISSUE TITLE
Force Download with Encrypted PDF Files

### ISSUE THREAD

**Issue by lovedota** [mozilla/pdf.js#8833]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 60
- Operating system and its version: MacOS 10.12.6
- PDF.js version: Latest
- Is an extension: Chrome Extension

Steps to reproduce the problem:
1.  Open this PDF (it is encrypted)

What is the expected behavior? (add screenshot)
- ![https___uat_dev_aws_ansarada_com_project-phoenix_7c209_67_viewdocumentfile_asp_filecode_doc_fileid_45378_isadobepluginenabled_false_ischromepdfviewerenabled_true_os_macintel_willuseadobeplugin_false_ghostviewsecuritygroupid_746](https://user-images.githubusercontent.com/417914/29764426-3ca2948e-8c01-11e7-86c8-fee769b5e62a.png)
- It should download the encrypted files so that user can use Adobe PDF to open it.

What went wrong? (add screenshot)
- ![168_typescript-for-c-sharp-programmers-final_pdf](https://user-images.githubusercontent.com/417914/29764410-313fe470-8c01-11e7-915a-38c13a5ec182.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): 
[168 TypeScript-for-C-sharp-Programmers-Final (6).pdf](https://github.com/mozilla/pdf.js/files/1255452/168.TypeScript-for-C-sharp-Programmers-Final.6.pdf)

**Comment by yurydelendik** [comment]
FWIW, none of my readers can open this file except Adobe Reader.

**Comment by lovedota** [comment]
@yurydelendik so that why we want if pdf.js can't view this file, we should automatically trigger download this and user then can open it by Adobe Reader

**Comment by yurydelendik** [comment]
> we should automatically trigger download this and user then can open it by Adobe Reader

Your sever can tell that it's not a PDF using different mime type, which technically is not, from point of view of many PDF readers. It will save the file, but preserve the extension -- you can open it using the Finder.

PDF.js provides download button in its UI. Does it work for you?

**Comment by lovedota** [comment]
@yurydelendik Thanks
It is fine, we will tell customer to use this button when they try to view a encrypted pdf.
