### ISSUE TITLE
Pdfjs-dist doesn't include all external libraries for web viewer (pdfjs-dist/lib/external) in lib/external folder

### ISSUE THREAD

**Issue by DmitriyOnypko** [mozilla/pdf.js#8838]
Hello, I'm trying to run web viewer js component just like in the demo in my angular 4 app via import & run from  pdfjs-dist/lib/web components. Embedding iframe does not suit me.  Is it expected to be used in such way? More below.

Link to PDF file (or attach file here): any

Configuration:
- Web browser and its version: not applicable
- Operating system and its version: not applicable
- PDF.js version: 1.9.491
- Is an extension: no
- stack: typescript@2.4.2, node@6.11.2,  npm@4.2, etc

Steps to reproduce the problem:
1. Include pdfjs-dist in package.json
2. Import web viewer components
```
...
import 'pdfjs-dist';
const pdfjsWebApp = require('pdfjs-dist/lib/web/app');
require('pdfjs-dist/lib/web/genericcom');
...
```
3. Build

What is the expected behavior? (add screenshot)
I'd expect web viewer files have a meaning in pdfjs-dist package in lib/web folder. As of now they're unusable since there are some hardcoded dependencies relative to lib/web folder (i.e. external/webL10n should be in lib/external folder and is required by genericcom).

What went wrong? (add screenshot)
Error while compiling
```
ERROR in ./node_modules/pdfjs-dist/lib/web/genericl10n.js
Module not found: Error: Can't resolve '../external/webL10n/l10n' in '/app/node_modules/pdfjs-dist/lib/web'
resolve '../external/webL10n/l10n' in '/app/node_modules/pdfjs-dist/lib/web'
using description file: /app/node_modules/pdfjs-dist/package.json (relative path: ./lib/web)
   after using description file: /app/node_modules/pdfjs-dist/package.json (relative path: ./lib/web)
   using description file: /app/node_modules/pdfjs-dist/package.json (relative path: ./lib/external/webL10n/l10n)
      no extension
      /app/node_modules/pdfjs-dist/lib/external/webL10n/l10n doesn't exist
      .ts
      /app/node_modules/pdfjs-dist/lib/external/webL10n/l10n.ts doesn't exist
      .js
         /app/node_modules/pdfjs-dist/lib/external/webL10n/l10n.js doesn't exist
      as directory
        /app/node_modules/pdfjs-dist/lib/external/webL10n/l10n doesn't exist
 [/app/node_modules/pdfjs-dist/lib/external/webL10n/l10n]
 [/app/node_modules/pdfjs-dist/lib/external/webL10n/l10n.ts]
 [/app/node_modules/pdfjs-dist/lib/external/webL10n/l10n.js]
 [/app/node_modules/pdfjs-dist/lib/external/webL10n/l10n]
 @ ./node_modules/pdfjs-dist/lib/web/genericl10n.js 24:0-35
 @ ./node_modules/pdfjs-dist/lib/web/genericcom.js
```

**Comment by Snuffleupagus** [comment]
> Hello, I'm trying to run web viewer js component just like in the demo in my angular 4 app via import & run from pdfjs-dist/lib/web components. Embedding iframe does not suit me. Is it expected to be used in such way?

The short answer here is *no*.

The longer answer is that the main purpose of pdfjs-dist is to make the *core* library available in such a way that it can be (more easily) used in custom implementations, but this does *not* cover the full functionality of the default viewer (i.e. the one found at https://mozilla.github.io/pdf.js/web/viewer.html).
The fact that all of the `web` files are present in pdfjs-dist is mostly to facilitate running various unit-tests with Travis (using Node.js).

Closing as answered.

**Comment by yurydelendik** [comment]
@DmitriyOnypko I do not know angular. It's possible to use pdfjs-dist to build a viewer using pdfjs-dist/web classes. See my attempt to use them in react https://github.com/yurydelendik/pdfjs-react/
