### ISSUE TITLE
extended printing features?

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#8839]
I’d rather ask this question in advance to know whether it makes sense to report the individual issues.

All of them are related to printing. For (almost) all of them, a new printing dialog would be needed.

PDF.js prints the file fine when the page size the PDF document uses is the same as the paper size in the printer.

There are other options that PDF.js should implement:

* Shrink page contents to printer margins. It would be better that this option is triggered only when minimization is really needed. (Already reported in #8832).

* Use document paper dimensions.

* Print in duplex or simplex mode.

These are also keys in the `/ViewerPreferences` dictionary:

* `/PrintScaling /None` disables page scaling to fit printer margins.

* `/PickTrayByPDFSize true` sets paper size from PDF document not from printer (essential when having to print with different paper sizes fed from paper tray).

* `/Duplex` which can have three possible values:

    * `/DuplexFlipShortEdge` for vertical duplex printing.

    * `/DuplexFlipLongEdge` for horizontal duplex printing.

    * `/Simplex` for single-sided printing (important when printer is set by default to duplex printing).

The implementation would be twofold:

1. Read the information from the `/ViewerPreferences` and print accordingly.

1. Add a printing dialog (such as other viewers have) that allows the user to select those options.

Could be these features implemented in PDF.js?

**Comment by timvandermeij** [comment]
The challenge here is to actually send that data to the browser's print dialog/the printer. As far as I know there is no way to control e.g., the paper dimensions through JavaScript. Before attempting to implement this, I'd suggest to first look into if all this is even possible with JavaScript, mainly because we had issues with it before. Keep cross-browser support in mind as well.

**Comment by ousia** [comment]
After looking for JavaScript and duplex printing, I have the impression that it might take years before such printing options might be available in JS.

After all, its origins are a scripting language for web browsers. There is nothing wrong with that. Fine tuning in printing options is an extremely particular case for it.

**Comment by DemiMarie** [comment]
What about allowing a user to pass a custom printing callback?

That would allow extended printing to be enabled in environments (perhaps as the built-in PDF viewer in Mozilla products) that support them, while falling back to the current behavior otherwise.

**Comment by timvandermeij** [comment]
Closing since we merged quite a few printing improvements since this issue was opened (better quality and page layout). There is nothing more we can really do here until browsers provide us with better printing APIs since we cannot control most of the points from this issue through JavaScript now.

**Comment by DemiMarie** [comment]
> Closing since we merged quite a few printing improvements since this issue was opened (better quality and page layout). There is nothing more we can really do here until browsers provide us with better printing APIs since we cannot control most of the points from this issue through JavaScript now.

In general yes, but on Mozilla platforms `pdf.js` is part of the browser and so could have access to private APIs.

**Comment by timvandermeij** [comment]
Not only would that make user experience between the various builds inconsistent, it's also not something we can fix _here_ and should be filed upstream in Bugzilla then.
