### ISSUE TITLE
pagechange

### ISSUE THREAD

**Issue by xiangzidetiandi** [mozilla/pdf.js#8841]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since there's no information provided; please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md before opening an issue, and also that you actually fill out the issue template.
