### ISSUE TITLE
TypeError: styleSheet is null - When rendering pdf page within dotnet project

### ISSUE THREAD

**Issue by WouterJanson** [mozilla/pdf.js#8842]
Configuration:
- Web browser and its version:
Firefox 55.0.3 (32-bit)
- Operating system and its version:
Windows 10
- PDF.js version:
1.9.491

When I want to render a pdf page I get the following error in my browser console:
`TypeError: styleSheet is null` on line 13925 of pdf.js

pdf.js:
``` javascript
    var styleElement = this.styleElement;
    if (!styleElement) {
      styleElement = this.styleElement = document.createElement('style');
      styleElement.id = 'PDFJS_FONT_STYLE_TAG_' + this.docId;
      document.documentElement.getElementsByTagName('head')[0].appendChild(styleElement);
    }
    var styleSheet = styleElement.sheet;
    styleSheet.insertRule(rule, styleSheet.cssRules.length); // <- line 13925
```

I'm using the example code from the [official examples](https://mozilla.github.io/pdf.js/examples/).

I know my pdf is loaded correctly because I can readout the amount of pages in the pdf document and the canvas is resized to the proper dimensions. However the pdf page can not be rendered.

**Comment by yurydelendik** [comment]
> I'm using the example code from the official examples.

Please provide complete example. Looks like the official examples were modified or not completely copied.

**Comment by timvandermeij** [comment]
Closing since no more information has been provided.

**Comment by aeromac** [comment]
Likely to be because styleElement needs a type of "text/css": 

MDN: An [StyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet) is always associated with a [HTMLStyleElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement), unless its type attribute is not text/css.
