### ISSUE TITLE
PDF with images are not rendering in Internet Explorer 

### ISSUE THREAD

**Issue by ndimn** [mozilla/pdf.js#8843]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 7
- PDF.js version: all versions (pdfjs-1.7.225, pdfjs-1.8.188 and pdfjs-1.9.426). Screenshots are from 1.9.426.
- Is an extension: No

Steps to reproduce the problem:
1. Choose any .PDF file with images
2. Render the .PDF file in Internet Explorer

What is the expected behavior? (add screenshot) 
Screen should load same as .PDF.
Screenshot from Chrome
![image](https://user-images.githubusercontent.com/156261/29872106-cb24cb86-8dab-11e7-9fb2-3f980f003c90.png)

What went wrong? (add screenshot) Screenshot from IE11
Images were not displaying on screen.
![image](https://user-images.githubusercontent.com/156261/29872129-e86d4bbe-8dab-11e7-9ea1-154df24478c1.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Not available

Processed .PDF file attached (ImageAndText.pdf)
[ImageAndText.pdf](https://github.com/mozilla/pdf.js/files/1263529/ImageAndText.pdf)

**Comment by colforbin13** [comment]
This has become an issue for me as well. Any updates?

**Comment by ndimn** [comment]
Actually this is not an issue but a scenario. Please check you graphic card display driver. mine were 4 years old. I updated to latest drivers and it started working fine.
This issue should not be observed on all machines.
