### ISSUE TITLE
Warning: parseDestDictionary: Unsupported Action type "GoToE"

### ISSUE THREAD

**Issue by tarekeldeeb** [mozilla/pdf.js#8844]
[FileAttached.pdf](https://github.com/mozilla/pdf.js/files/1264140/FileAttached.pdf)

Configuration:
- Chrome
- Windows 10 64-bit
- PDF.js version: Latest master
- Is an extension: no

Steps to reproduce the problem:
1. Produce the file using pdflatex as in [here](https://tex.stackexchange.com/questions/19025/embed-link-to-an-embedded-file)
2. Just open the file (Has embedded attachment + Link to that) 
3. Warning comes out: parseDestDictionary: Unsupported Action type "GoToE"

What is the expected behavior?
Open the attached file, this is perfectly working with Adobe reader.

What went wrong? 
Nothing Happens when the link is clicked

**Comment by yurydelendik** [comment]
FWIW, nothing is happening when link is clicked when viewer in Mac Preview or Chrome.
