### ISSUE TITLE
Added blank page at end when printing

### ISSUE THREAD

**Issue by Kasmysh** [mozilla/pdf.js#8849]
Link to PDF file with normal A4 sizes:  https://yadi.sk/i/Q0Xf-tg43MUfQv
Link to PDF file with reduced height to 841pt:  https://yadi.sk/i/Lex0uk9g3MWAhX

Configuration:
- Web browser and its version: Firefox 54.0(64-bit) for Ubuntu
- Operating system and its version: ubuntu 16.04 LTS
- PDF.js version: v1.9.426

Steps to reproduce the problem:
1. Open pdf document (A4, Portrait (210 × 297 mm)) with viewer.html
2. Click at viewer print button and print this document

Blank page will added at end when printing.

This trouble I think came from v1.7 when you began insert document pdf to img
instead of canvas for printing.
Interesting, if pdf height equals to 841pt Firefox will print it without added blank page,
but Chrome will add blank page at end when printing.
I attached tow links on pdf with normal A4 sizes and with reduced height to 841pt.

**Comment by Snuffleupagus** [comment]
WFM, when testing in PDF.js version `2.9.94` (via https://github.com/mozilla/pdf.js#online-demo) in both Firefox Nightly 89 *and* Chrome Beta 90.0.4430.72; most likely this was fixed by the recent round of printing patches.
