### ISSUE TITLE
Enable "read with streaming" test in test/unit/network_spec.js

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#8851]
The "read with streaming" test looks like this:
https://github.com/mozilla/pdf.js/blob/a4cc85fc5f5cb144b6ee7a7978dc83e906677233/test/unit/network_spec.js#L67-L77

There are two issues here:
- Lines 74 - 76 should use `pending('Streaming not supported by user agent');` instead of an incorrect `done()` call.
- With #8768, it seems that the test can be enabled for other browsers (Chrome).

@yurydelendik Can the test be enabled for other browsers?

**Comment by yurydelendik** [comment]
> Can the test be enabled for other browsers?

Yes. I don't see why not.

**Comment by aryanshar** [comment]
Hi. I would like to solve this issue. Please assign me this. And also, please guide me how do i move forward in contributing more to this repository !

**Comment by Rob--W** [comment]
@aryanshar That's fast, I was still typing the motivation for the good-beginner-bug label. Here it goes:

This bug consist of two parts. The first part is fully explained in the original report.

For the second part, we need to update the if condition to logic along the lines of "if (!isFirefoxWithMozChunkedEncodingSupport && !isFetchWithStreamSupport)` (choose shorter but understandable variable if you wish). The first variable name is based on the current content of the if-statement (by the way, that has a flaw too. If Firefox 90 becomes available, the condition is incorrect). The second variable should indicate whether ReadableStream is supported (see e.g. cd95b426c730108a529fbf6ab48b3192e22922dd).

**Comment by kushagra189** [comment]
Is the issue still up? I would like to solve if it is. 
PS: Noob here.

**Comment by timvandermeij** [comment]
There is a PR above, but there was no response since 24 October. You're welcome to use that PR, and in particular the comments there, as inspiration to create a new PR so we can hopefully merge it soon.

**Comment by JavierPons** [comment]
Hi there!
Do you need help for a "beginners" :p Can you explain  more  concretely where do you need help? I see that this issue is for @kushagra189. Do you have an other one where I can participate?

**Comment by choilmto** [comment]
Under the section titled "[Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)", there is a summary of native browser support across desktop and mobile platforms. What does 'streaming response body' refer to, and is it relevant to our needs? Under whatwg's streams standard, a readable stream is a class that uses chunks...is that what line 70 in the code cited above refers to?

As an aside, instead of checking for browser support of fetch() by looking at the user-agent header for information on the browser version, can we do something like `expect('fetch' in window).toBe(true);`?

**Comment by Rob--W** [comment]
@choilmto I have updated the MDN pages to be more clear. Take another look if you want to get a better understanding.

Line 70 in the above code refers to the non-standard way of obtaining a response stream in Firefox, via the `xhr.responseType = "moz-chunked-arraybuffer"` (where `xhr` is a `XMLHttpRequest` instance) (so the comment has a typo, "array" should be "arraybuffer").

> As an aside, instead of checking for browser support of `fetch()`

`fetch` support does not equate support for streaming responses (see the note at the end of https://github.com/mozilla/pdf.js/issues/6126#issuecomment-130572300). Checking for existence of `ReadableStream` would be sufficient though (this was also done in the proposed pull request at #9050).

The user agent line is still necessary; Alternatively, feature detection can be used, as shown at:
https://github.com/mozilla/pdf.js/blob/edaf4b3173607cf19664ab764e5be0742b51c5a4/src/display/network.js#L55-L72

**Comment by manmeet0307** [comment]
Hi. I would like to solve this issue. Please assign me this. And also, please guide me how do i move forward in contributing more to this repository !

**Comment by s1iqbal** [comment]
Resolved!
