### ISSUE TITLE
Gaps in dotted line in Safari

### ISSUE THREAD

**Issue by rijk** [mozilla/pdf.js#8856]
Link to PDF file: 
[170822_DB_Postkarte_Positives-Denken lsdy.pdf](https://github.com/mozilla/pdf.js/files/1267386/170822_DB_Postkarte_Positives-Denken.lsdy.pdf)

Configuration:
- Web browser and its version: Safari Version 10.1.2 (12603.3.8)
- Operating system and its version: OS X 10.12.6
- PDF.js version: pdfjs-dist@1.9.491 
- Is an extension: no

What is the expected behavior? (screenshot from Chrome)

<img width="728" alt="screen shot 2017-08-31 at 16 26 38" src="https://user-images.githubusercontent.com/159500/29928434-4cf728b2-8e69-11e7-80b2-eace0225e73b.png">

What went wrong? (screenshot from Safari)

<img width="725" alt="screen shot 2017-08-31 at 16 26 47" src="https://user-images.githubusercontent.com/159500/29928444-5421c318-8e69-11e7-878a-34c37743f97f.png">

**Comment by Snuffleupagus** [comment]
If this really is Safari-specific, it seems to point to a bug in its `canvas` implementation rather than in the PDF.js library; closing since this issue doesn't seem like something that can be fixed here?
