### ISSUE TITLE
Translucent effect has wrong color

### ISSUE THREAD

**Issue by sknorr** [mozilla/pdf.js#8860]
Link to PDF file (or attach file here): https://assets.cdn.sap.com/sapcom/docs/2016/05/827c26ba-717c-0010-82c7-eda71af511fa.pdf

Configuration:
- Web browser and its version: Firefox 55
- Operating system and its version: Linux
- PDF.js version: (as included with Firefox 55)
- Is an extension: no

Steps to reproduce the problem:
1. open file
2. look at first slide

What is the expected behavior? (screenshot from Evince)
![evince](https://user-images.githubusercontent.com/5476547/29939282-a5f429ca-8e8b-11e7-8091-1d1548a99288.png)

What went wrong? (screenshot of PDF.js/Firefox)
![pdf.js](https://user-images.githubusercontent.com/5476547/29939275-a0769fa0-8e8b-11e7-8b60-e3b2d885597f.png)

**Comment by THausherr** [comment]
The translucent effect is a really pattern based on a chess-like b/w image mask of size 1x1.
