### ISSUE TITLE
How to use blob (pdf saved in database in binary format) directly in pdf.js viewer?

### ISSUE THREAD

**Issue by SanjanaShende** [mozilla/pdf.js#8861]
I have my pdf stored in mysqldb, i want to open it on viewer.html of pdf.js directly without storing it in web folder 

Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
> I have my pdf stored in mysqldb, i want to open it on viewer.html of pdf.js directly without storing it in web folder

Provide URL of the server script that retrieves data from the DB. See e.g. https://stackoverflow.com/search?q=pdf+blob+from+database for the ideas. Closing as answered.
