### ISSUE TITLE
SVG render incorrect when override * font-family

### ISSUE THREAD

**Issue by mix5003** [mozilla/pdf.js#8867]
when override font-size and font-family in  * css rule, svg render will incorrect.

step to reproduce 
1. add css rule like  
```css
* { font-size: 50px} 
```
2. view pdf with svg renderer
3. see output

example: https://jsfiddle.net/arnkfrzp/1/

**Comment by timvandermeij** [comment]
Closing since this is expected. The SVG back-end calculates the positioning of the glyphs given the font data in the PDF file. If you change the font size, these calculations become invalid.
