### ISSUE TITLE
Latest version of pdf.js does not work with blobs

### ISSUE THREAD

**Issue by drweb86-work** [mozilla/pdf.js#8870]
We had to revert version back from
"pdfjs-dist": "^1.9.484",

to

"pdfjs-dist": "1.9.476",

because of error 200.

**Comment by jorawarsingh** [comment]
same here.

**Comment by yurydelendik** [comment]
man, so many people using `blob:` to pass the PDF data

**Comment by wojtekmaj** [comment]
@yurydelendik I'm curious, shall I read it as a general complain? Do you consider blob a bad thing and wish people would pass the data to pdfjs in a different way?

**Comment by yurydelendik** [comment]
> shall I read it as a general complain? Do you consider blob a bad thing ...

I consider this on somewhat on the par with "data:" (probably a little bit better though). PDF.js is optimized to work with ranged/random access to the data, e.g. I played with getinfo.js node example, which now is using range reads, and via logging I noticed metadata is ready way before main/full file read is completed. IMHO loading of full PDF data in memory delays a first page presentation to the end user, which is big performance issue.

> and wish people would pass the data to pdfjs in a different way?

The right way is to provide URL to the resource and enable HTTP range request support (if custom script is used). Benefits are native browser caching, instant first page display, less strain on server.

**Comment by wojtekmaj** [comment]
Thanks for your input! Incredibly helpful :)

**Comment by svenyonson** [comment]
Yury, I am confused about how to do random access. The getinfo.js says that 
// Loading of the first page will wait on metadata and subsequent loadings
// will wait on the previous pages.

I do get an error if I try to load a page without first loading all of the prior pages. Can you give an example of the correct way to open a pdf and then read a page from the middle of the document?

**Comment by jimmywarting** [comment]
It would just be easier if getDocument where able to accept a blob instead.
