### ISSUE TITLE
Checkbox in interactive form not showing up with renderInteractiveForms enabled

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#8875]
Link to PDF file (or attach file here): 
[f1040 copy.pdf](https://github.com/mozilla/pdf.js/files/1279220/f1040.copy.pdf)

Configuration:
- Web browser and its version: Chrome 60.3112.113, Safari 10.1.2, Firefox 55.0.3
- Operating system and its version: macOS Sierra 10.12.6
- PDF.js version: 1.9.450
- Is an extension: No

Steps to reproduce the problem:
1. Use pdf.js, turn on `renderInteractiveForms` and load the file. Or visit https://cloud.box.com/s/snwp6gyhdk6wh2m9x46p81ubs73829vj
2. See that the checkbox for `Single` under Filing Status is not checked

What is the expected behavior? (add screenshot)
![2017-09-05_16-09-18](https://user-images.githubusercontent.com/689351/30087278-9e894388-9254-11e7-8690-ba71600422cf.png)

What went wrong? (add screenshot)
![2017-09-05_16-09-59](https://user-images.githubusercontent.com/689351/30087295-ba68feea-9254-11e7-9fdf-82888eecf31b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://cloud.box.com/s/snwp6gyhdk6wh2m9x46p81ubs73829vj

Looks like this issue only happens when `renderInteractiveForms` is enabled. Other non-checkbox type fields are filled in. When `renderInteractiveForms` is turned off, checkboxes render correctly. 

This looks potentially related to https://github.com/mozilla/pdf.js/issues/8159, but that might refer to rendering without interactive forms?

**Comment by timvandermeij** [comment]
The functionality works in the sense that the checkbox has the attribute `checked="true"`, but for some reason the custom styling is broken in at least recent Firefox and Chrome versions. If I remove the `-moz-appearance: none;` style, then the checkboxes are indeed checked (just not styled). I wonder what broke this, because this worked back when I implemented this...

**Comment by timvandermeij** [comment]
It looks like we miss the `:checked` styles (see this fiddle: https://jsfiddle.net/VWC76/391/). Somehow this worked before without it, but we should add it. I'll check it out.

**Comment by tonyjin** [comment]
Thanks! I really appreciate the quick fix :)
