### ISSUE TITLE
Rendering PDF using URL is not working

### ISSUE THREAD

**Issue by mbharodia** [mozilla/pdf.js#8876]
Version: 1.8.557
PDF rendering using URL works because of a valid request generated as shown in the screen capture (2). 

Version: 1.9.228
PDF rendering using URL fails because the request is missing cookie and it is not XHR type. Please see screen capture (1). As it is missing cookie, the server redirects the request to login page.

I am wondering how I can fix the issue. Am I supposed to change the method? I have provided a snippet (typescript) of the code I have been using so far to render the document. I think method "getDocument(.. ..)" is having this problem.

 ```
PDFJS.getDocument(this.pdfServiceUrl).then(this.setupPdf, (reason) => {
            //some code here to handle the error message
        });   

 private setupPdf: (PDFDocumentProxy) => void = (pdfDoc) => {
        this.isWaitCursorVisible = true;
        this.pdfDocument = pdfDoc;
        this.selectedPageNumber = 1;
        this.totalPages = this.pdfDocument.numPages;
        this.queuePageRendering(this.selectedPageNumber);
        this.canDownload = true;
    };

```
1) Image: Request made from the 1.9.228 missing request type and cookie; has HTTP redirect with 302

![renderfailed1](https://user-images.githubusercontent.com/10344641/30130451-6dd91da0-9306-11e7-97ec-53eda45348f3.png)

2) Image: Request made from 1.8.557 has valid request type (XHR) and valid cookie

![renderworked1](https://user-images.githubusercontent.com/10344641/30130452-6ddcba0a-9306-11e7-9d41-cb823f973a7b.png)

![renderworked2](https://user-images.githubusercontent.com/10344641/30130453-6de0283e-9306-11e7-8791-f0914b24d17a.png)

Thanks a lot for your help in advance!

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Closing until the requested information is provided.
