### ISSUE TITLE
Problems with (correct) external links in PDFs on mobile.

### ISSUE THREAD

**Issue by MatsEx** [mozilla/pdf.js#8878]
PDF: 
https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf

Configuration:
IOS: 10.3.3 , Safari 10 (and other versions)
Cordova:7.01
Angular: 1.5.8
PDF.js: 1.7.354 *)

Expected behavior:
Be able to click external links which then opens the browser that goes to the url.

We are Working on a project (a mobile app) where the customer needs to trigger video inside PDFs. 
The app is developed with Cordova and Angular. 

We have made tests on a regular website and it works fine.
The link is working and we can fetch the URLs and rewrite them.
(We have to rewrite them to point them to right local URL on the mobile).

The problem is when we try to do the same on a smartphone. 
The links wont work and we can't fetch the URLs. pdf.js just seems to ignore rendering them.

We have discovered that this is a problem with most PDF-reader-apps (Acrobat Reader etc.) on smartphones when trying to use links to files and media but external links always works.
Therefore we are using external links but it still doesn't work.

Can this be a security issue..? 
If so,  is it something we can change in pdf.js?
Found this, https://github.com/mozilla/pdf.js/issues/1778 but we can't get it to work (and actually don't know if its a working solution for our problem). 

Other than that we don't have a clue how to get it to work (and why it isn't working).

I have read every post I can find about links but can't find anything that seems to help.
Mostly it seems that the problems is about faulty links in the PDF.
To be sure that isn't the we also have been testing it with "sample-link_1.pdf" mention here:
https://github.com/mozilla/pdf.js/issues/7082

We really would appreciate if anyone can help us and point us in the right directions!

I know mobiles and mobile browsers isn't fully supported. Maybe our problems can't be solved (please let us know if thats the case).

Thanks in advance!

**Comment by Snuffleupagus** [comment]
> We have made tests on a regular website and it works fine.
> The link is working and we can fetch the URLs and rewrite them.
> (We have to rewrite them to point them to right local URL on the mobile).
> 
> The problem is when we try to do the same on a smartphone.
> The links wont work and we can't fetch the URLs. pdf.js just seems to ignore rendering them.
> 
> We have discovered that this is a problem with most PDF-reader-apps (Acrobat Reader etc.) on smartphones when trying to use links to files and media but external links always works.
> Therefore we are using external links but it still doesn't work.

Based on the above I'm not sure how/if this is actually a PDF.js issue, it rather seems to be an issue with particular platforms (given that it apparently works sometimes).

Furthermore, when developing custom solutions based on PDF.js, as asked for in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), you  need to provide access to a working example (and clear STR) since otherwise we cannot help.

**Comment by MatsEx** [comment]
Thanks, your answer tells me that it shouldn't be a security issue or any simple configuration change that would help. Guess we just doing it wrong somehow.  I make sure we provide an example next time (at the moment we have the complete project almost finished and was just trying to include pdf.js and I don't want to give away all of it..  If we doesn't find a solution soon we will make a separate testproject that we can share. Closing this.
