### ISSUE TITLE
pdf-dist/webpack fails to register pdf.worker.js and build fails.

### ISSUE THREAD

**Issue by distante** [mozilla/pdf.js#8879]
I have found this problem with the webpack version of pdfjs-dist. When using the `--prod` flag that runs Uglifyjs the build fails because it can not find the generated worker. Without the `--prod flag` or importing `pdfjs-dist/web/pdf_viewer.js` the error is gone but some things like the worker does not work as expected in an Webpack project.

The error yields:
```
 [15:54:52]  uglifyjs started ...
    (node:29259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
    Error: ENOENT: no such file or directory, open '/Users/me/Documents/Projekte/apps/ionic3.myApp/www/build/a389ed33aa2794575fa2.worker.js'
    Error: ENOENT: no such file or directory, open '/Users/me/Documents/Projekte/apps/ionic3.myApp/www/build/a389ed33aa2794575fa2.worker.js' in undefined at line undefined, col undefined, pos undefined
    Segmentation fault: 11
```

Steps to reproduce the problem:
1.  install pdfjs-dist
2. import it using `import { PDFJS as PDFJSViewer } from 'pdfjs-dist/webpack';`
3. try to use PDFJSViewer in someplace (even just with `console.log(PDFJSViewer)`)

Repo: https://github.com/distante/pdf-dist-webpack-does-not-build

I have found [this problem with Uglify ](https://github.com/mozilla/pdf.js/issues/7326) but looks like it is another problem.

The project has this Uglify versions installed:

```
├─┬ @ionic/app-scripts@2.1.4
│ ├── uglify-js@3.0.28
│ └─┬ webpack@3.5.6
│   └─┬ uglifyjs-webpack-plugin@0.4.6
│     └── uglify-js@2.8.29
└─┬ webpack@2.7.0
  └── uglify-js@2.8.29
````

**Comment by valentinchevalier** [comment]
Hi,

I have the exact same issue. Do you found a solution to build with prod flag and pdf.js?

Thanks

**Comment by distante** [comment]
I can not see the code right now, but as far as I was able to found, the problem is in the library that registers the web worker.

**Comment by Snuffleupagus** [comment]
> I have found this problem with the webpack version of pdfjs-dist. When using the `--prod` flag that runs Uglifyjs the build fails because it can not find the generated worker.

Since that minifier isn't supported by the PDF.js project any more, this issue thus seem out-of-scope; closing as INVALID?

**Comment by timvandermeij** [comment]
Yes, we now use Terser.
