### ISSUE TITLE
Relatively small file loaded forever...

### ISSUE THREAD

**Issue by DrorSegev** [mozilla/pdf.js#8883]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome and IE
- Operating system and its version: Windows
- PDF.js version: Latest

Steps to reproduce the problem:
1.  Load the attached file
2. In Canvass mode 
3. In SVG mode 

In Canvass mode the resolution is bad. when zooming in the browser stuck forever
In SVG mode It  takes 1 minute to load.
Is there an option to reduce loading time by simplifying the PDF?

Any help will be appreciated.

Dror

[1440-00-1- 500.pdf](https://github.com/mozilla/pdf.js/files/1284737/1440-00-1-.500.pdf)

**Comment by THausherr** [comment]
The "relatively small" file has 5MB and is pure vector graphics. You could make it faster to have recurrent elements like trees as graphics.

**Comment by DrorSegev** [comment]
Hi.
The file is generated by AutoCad, so I have no control on the content.
Is there a tool to "simplify" the PDF ?
 How can I know the file is "pure vectors"?
I have a 40M files that load fast (even in SVG) mode.
Dror

**Comment by THausherr** [comment]
Maybe look whether the PDF export has options. Or ask AutoCAD about it, if you're a paying client.
I don't know if there are tools to "simplify" the PDF.
The vector thing I can tell because I looked at the PDF with PDFDebugger and because I know parts of the PDF specification. (Just believe me :-))

**Comment by yurydelendik** [comment]
> Relatively small file loaded forever...

Please add numbers/times to the report. For some people 5 seconds is forever, for some 30 seconds is acceptable. It takes 14 seconds for Mac Preview to repaint stuff after zoom, Adobe Reader "knows" something more however still takes 2-4seconds to refresh, Chrome freezes for 5 sec to perform scroll or zoom, PDF.js here takes 14 seconds.

Thank you for the test case. I think we can close it in favor of #6419

**Comment by DrorSegev** [comment]
It Takes 50 seconds on Chrome+win10v(I7+ 16G memory) on SVG Mode.
It Takes 15 seconds on Chrome+win10v(I7+ 16G memory) on Canvass Mode. Then zooming take another 20-30 seconds

It get Out Of Memory on IE11......


Dor

**Comment by yurydelendik** [comment]
Long ago to find out that SVG is and will be slow because of the web browsers limitation (memory and CPU reasons). (I hope Servo can make a progress for this problem) So are pursuing SVG backend only for printing capabilities -- SVG backend is not a solution for this problem.

**Comment by DrorSegev** [comment]
On the other hand SVG backend provide a really good zooming behavior for PDF with images.
The canvass becomes blued when zooming in 

Dror

**Comment by yurydelendik** [comment]
> The canvass becomes blued when zooming in

Correct, that's bug #6419. You can remove this limit for your custom solution.

**Comment by Snuffleupagus** [comment]
Given that this document, as outlined in https://github.com/mozilla/pdf.js/issues/8883#issuecomment-328065981, contains nothing except "regular" path-rendering operators there's unfortunately very little that can be done here. Hence there's no repeated Images/ColorSpaces/ExtGStates or similar that could e.g. be cached to improve performance.

Furthermore https://github.com/mozilla/pdf.js/issues/8883#issuecomment-328161264 mentions the SVG-backend, which as explained above is (still) neither feature complete nor officially supported; this is now also mentioned in the Wiki: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

All-in-all, given that this works *sort-of OK* in the default canvas-backend and that there's really nothing we can do here except for possibly issue #6419, I'd thus suggest closing this as a duplicate. /cc @timvandermeij
