### ISSUE TITLE
v1.9.528 doesn't include credentials on chrome

### ISSUE THREAD

**Issue by tsalufe** [mozilla/pdf.js#8888]
We had this code to get pdf through authenticated url 
`PDFJS.getDocument(url)`
that breaks with version 1.9.528 on Chrome because it doesn't include CSRF-TOKEN in the request. However, it works on firefox and safari. Now I have to fix it by enforce withCredentials: true. Does new version set the default of withCredentials to false?

**Comment by yurydelendik** [comment]
We are switching to more efficient fetch() instead of XHR. The defaults might change, let us know which default in https://developer.mozilla.org/en-US/docs/Web/API/Request/Request affects CSRF-TOKEN. If it's possible we will try to address this. Also notice that we don't want to make PDF.js less secure (even if we supported this in the past)

**Comment by tsalufe** [comment]
I'm not sure about that. Maybe `credentials` ?

> credentials: The request credentials you want to use for the request: omit, same-origin, or include. The default is omit. In Chrome the default is same-origin before Chrome 47 and include starting with Chrome 47.

**Comment by mukulmishra18** [comment]
> I'm not sure about that. Maybe credentials ?

We are including `credentials`, if `withCredentials` is set, see: https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/fetch_stream.js#L29

I think that is why it works when you set `withCredentials: true`.

**Comment by tsalufe** [comment]
I think so.

**Comment by yurydelendik** [comment]
Okay, from reading https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials, I have impression that to be compatible with XHR we need to use 'same-origin' instead of 'omit' there. I think it is safe in our context.

**Comment by tsalufe** [comment]
I think `include` definitely works for me since it's the setting of credentials when I set withCredentials to true. `same-origin` might limit the pdf on the same site, i.e not allowing authenticated access to pdf's on another site?

**Comment by yurydelendik** [comment]
> same-origin might limit the pdf on the same site, i.e not allowing authenticated access to pdf's on another site

That's how XHR worked before we introduced fetch().
