### ISSUE TITLE
How to view a "binary" string?

### ISSUE THREAD

**Issue by betacar** [mozilla/pdf.js#8894]
This is more a question rather than an actual issue (bumping this question from the [vue-pdf repo](https://github.com/FranckFreiburger/vue-pdf/issues/6#issuecomment-321568139).

So, we load the PDF document from the server through a browser request. The `binary/octect-stream` response comes as:
```
%PDF-1.4
1 0 obj
<<
/Title (��PDF)
/Creator (��wkhtmltopdf 0.12.3)
/Producer (��Qt 4.8.7)
/CreationDate (D:20170720154012Z)
>>
endobj
3 0 obj
<<
/Type /ExtGState
/SA true
/SM 0.02
/ca 1.0
/CA 1.0
/AIS false
/SMask /None>>
endobj
4 0 obj
[/Pattern /DeviceRGB]
endobj
9 0 obj
[0 /XYZ 28.3200000  
813.679999  0]
endobj
10 0 obj
[0 /XYZ 171.359999  
809.839999  0]
endobj
11 0 obj
[0 /XYZ 42.7199999  
645.679999  0]
endobj
12 0 obj
[0 /XYZ 42.7199999  
567.919999  0]
endobj
5 0 obj
<<
/Type /Page
/Parent 2 0 R
/Contents 13 0 R
/Resources 15 0 R
/Annots 16 0 R
/MediaBox [0 0 595 842]
>>
endobj
15 0 obj
<<
/ColorSpace <<
/PCSp 4 0 R
/CSp /DeviceRGB
/CSpg /DeviceGray
>>
...
```

However, I'm not sure how to pass the response to the PDF.js instance. I've tried almost [every attribute](https://github.com/mozilla/pdf.js/blob/8ff1fbe7f819513e7d0023df961e3d223b35aefa/src/display/api.js#L117-L151).

Any ideas?

*Configuration:*
- Web browser and its version: N/A
- Operating system and its version: N/A
- PDF.js version: `1.7.418`
- Is an extension: [vue-pdf](https://github.com/FranckFreiburger/vue-pdf)

**Comment by Snuffleupagus** [comment]
Provided that the PDF data is *actually* a plain string as indicated above, and not [Base64-encoded](https://github.com/mozilla/pdf.js/blob/ba219965760d8521a7f3794184b653f93c65c5b9/src/display/api.js#L102-L103), then using `PDFJS.getDocument({ data: 'pdfAsStringHere...', });` should work. And as can be seen in https://github.com/mozilla/pdf.js/blob/ba219965760d8521a7f3794184b653f93c65c5b9/src/display/api.js#L239-L243 a plain string will be converted to a `Uint8Array` holding the PDF data.

> I've tried almost every attribute.

Unfortunately that doesn't tell us *exactly* what you have tried, so it's difficult to know what could have gone wrong. If you need further assistance, then as asked for in both the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide a complete (and self-contained) example.

> Is an extension: vue-pdf

Extension here refers to either of the two *browser* extensions listed here: https://github.com/mozilla/pdf.js#browser-extensions. Please keep in mind that we cannot support third-party implementations of the PDF.js library, so please ensure that the issue you're facing is present in *this* library.

Closing as answered.
