### ISSUE TITLE
Applying multiple buffering techniques to PDF rendering

### ISSUE THREAD

**Issue by dancodes** [mozilla/pdf.js#8896]
Hello,

I've been playing with `pdf.js` and even though it works great in general, there's a small nitpick which I think I can solve but I thought I'd ask here first.

Every time I call the `render()` method (with its proper `renderContext` argument), the canvas' contents get erased for a few milliseconds before the next page appears on the screen. This is how it looks visually: [https://gfycat.com/EasygoingPopularAntbear](https://gfycat.com/EasygoingPopularAntbear).

I'm running Windows 8.1 and Google Chrome 61.0.3163.79.

I believe this is due to `pdf.js` rendering the next page's contents on the same canvas the current one is being displayed. Could this be solved by using [Double Buffering](https://en.wikipedia.org/wiki/Multiple_buffering), by rendering to a second (invisible) canvas and switching them once the task is done? 

If this is correct and I'm not working on a corner case, I believe this should be implemented into the library and I'd be more than happy to do it myself. I'd like to know your thoughts about this.

Thanks!

**Comment by yurydelendik** [comment]
Yes, for you custom solution you can apply a double buffering. We also recommend to use different canvases for different visible pages, which will give the same effect if canvas will be replaced after painting. The demo viewer already applies this technique during zoom operations. Closing as answered.
