### ISSUE TITLE
how to render all pages at one time using the default demo  

### ISSUE THREAD

**Issue by kuiran** [mozilla/pdf.js#8898]
i need to render all pages of a pdf file in the first time without scrolling when using the default demo.So,how to modify the demo?
thank you for your advice.

**Comment by Snuffleupagus** [comment]
Please be aware that doing this is really *not* a good idea; as explained in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages that would have a *very* bad effect on both memory an CPU usage, which is why we advise against it.

If you insist on rendering all pages, then you'll need to modify https://github.com/mozilla/pdf.js/blob/ba219965760d8521a7f3794184b653f93c65c5b9/web/pdf_viewer.js#L806 to always return all pages of the document.

Closing as answered, since this isn't functionality that the default viewer will support.

**Comment by kuiran** [comment]
I am so embarrassed that i don't know how to return all pages of the document.Can you help me.It's so difficult for me now.

**Comment by yurydelendik** [comment]
See also https://stackoverflow.com/questions/25162554/how-to-render-whole-pdf-document-using-pdf-js-library/41875420#41875420 or https://stackoverflow.com/questions/16480469/how-to-display-whole-pdf-not-only-one-page-with-pdf-js/41174415#41174415

**Comment by kuiran** [comment]
Thank you for your advice,I have solve the problem.But a new problem occurs. I want to save the web page which has rendered the PDF file as a html file.Then i open the html file.But it doesn,t work.The textlayer seems transparent.So,could you tell me how to solve this problem.I'm so sorry for having so many problem.
The problem seems like 
![sy87 v y3q x51d 485zx_s](https://user-images.githubusercontent.com/25083462/30532261-e5955132-9c85-11e7-831b-9b29c27e0962.png)

**Comment by Crackiii** [comment]
@kuiran how did you solve the issue?

**Comment by anees042** [comment]
`_getVisiblePages() {

          /* load all pages */

          let visible = [];
          let currentPage = this._pages[this._currentPageNumber - 1];
          for (let i=0; i<this.pagesCount; i++){
            let aPage = this._pages[i];
            visible.push({ id: aPage.id, view: aPage, });
          }
          return { first: currentPage, last: currentPage, views: visible, };
        }`

**Comment by RiteshAryal** [comment]
Nice solution is here https://stackoverflow.com/questions/16480469/how-to-display-whole-pdf-not-only-one-page-with-pdf-js

**Comment by ascott18** [comment]
Updated solution for current versions using the default viewer:

``` ts
        pdfViewer = new pdfjsViewer.PDFViewer({
          // ... options
        });
        pdfViewer._getVisiblePages = function () {
          let visible = [];
          const ids = new Set();
          let currentPage = this._pages![this._currentPageNumber - 1];
          for (let i = 0; i < this.pagesCount; i++) {
            let aPage = this._pages![i];
            ids.add(aPage.id);
            visible.push({ id: aPage.id, view: aPage });
          }
          return { first: currentPage, last: currentPage, views: visible, ids };
        };
```
