### ISSUE TITLE
PDF.js toolbar is missing.

### ISSUE THREAD

**Issue by nabber** [mozilla/pdf.js#8906]
I am trying to use pdf.js to send a base64 encoded string and have it display my PDF.  I am following the interactive example provided by pdf.js [here](http://mozilla.github.io/pdf.js/examples/index.html#interactive-examples)

The issue I'm having is the PDF toolbar is missing, so my users would have no way to save the PDF.

Here is the toolbar from the demo:
![image](https://user-images.githubusercontent.com/3247525/30398196-267750f0-9895-11e7-82bd-957580d0689d.png)

Here is what my PDF looks like:
![image](https://user-images.githubusercontent.com/3247525/30398270-6cce84ec-9895-11e7-9877-be3d9a271510.png)

I am using window.open()  and am wondering if that maybe isn't supported?

Configuration:
- Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- Windows 10 Enterprise version 1703
- PDF.js version: v1.8.188

**Comment by yurydelendik** [comment]
I don't think what you see at the bottom screenshot is PDF.js. Looks like Chrome's PDF Viewer. Without public link to the complete example, it's hard to tell. I'll close it as incomplete. Please provide link to re-open the issue.

**Comment by timvandermeij** [comment]
Moreover, the interactive examples only render the PDF itself and do not provide a full viewer. The toolbar is part of the full viewer in https://github.com/mozilla/pdf.js/tree/master/web.

**Comment by sreedy** [comment]
Is there anywhere we can see interactive examples with the full viewer?  This would be extremely helpful.

**Comment by marsrobertson** [comment]
I was looking for ways how to integrate more advanced toolbar...

Found this: https://stackoverflow.com/questions/12748747/mozilla-pdf-js-without-fullview

Use an iframe!

If you really want to build your own, here is an example of adding extra buttons: https://stackoverflow.com/questions/27607526/zoom-on-simple-pdf-js-viewer/54762483
