### ISSUE TITLE
Is it allowed to add a button with a link to the top bar?

### ISSUE THREAD

**Issue by adrians75** [mozilla/pdf.js#8916]
Hi,
Is it allowed to add a button with a link to the top bar?
Or add it to the right-hand menu (>>).
How to add a button (link) like this: [miky-ltd.clientaccount.com]
Thanks!

Regard,
Adrian

**Comment by Snuffleupagus** [comment]
> Is it allowed to add a button with a link to the top bar?

It's not really clear what "allowed" actually means in this case!

If you ask if you could add a custom button to the toolbar (or secondary toolbar) of the default viewer, as present at https://mozilla.github.io/pdf.js/web/viewer.html, then the answer would be a definite *no*.

If your question actually concerns a custom implementation of the default viewer (i.e. one running on your own website), the you're obviously free to customize the viewer. In fact you're even encouraged to do so, as explained in e.g. https://mozilla.github.io/pdf.js/getting_started/
> *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

As for how a new button would be implemented, I'd suggest looking at the following files to see what pattern is used for the existing buttons:
https://github.com/mozilla/pdf.js/blob/master/web/viewer.html
https://github.com/mozilla/pdf.js/blob/master/web/viewer.js
https://github.com/mozilla/pdf.js/blob/master/web/toolbar.js
https://github.com/mozilla/pdf.js/blob/master/web/secondary_toolbar.js

Closing as answered.
