### ISSUE TITLE
All Internet Archive links, used in reference testing, are broken

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#8920]
Apparently the [Internet Archive](http://archive.org/web/), which we depend on for a *very* large number of (linked) reference test-cases, has recently changed how they serve PDF files.

Previously, a URL such as http://web.archive.org/web/20160112115354/http://www.fao.org/fileadmin/user_upload/tci/docs/2_About%20Stacks.pdf would return a PDF file directly. However, now a HTML file is returned instead (which then points to the actual PDF file).
For someone cloning the PDF.js repo, and attempting to set-up testing for the first time, this means that *all* linked test-cases will now fail. Furthermore, it also means that we cannot use the Internet Archive when adding new test-cases.

Since the HTML file returned *does* contain a direct link to the PDF file, embedded in an `<iframe>` tag, we could perhaps add special-casing for Internet Archive URLs in [test/downloadutils.js](https://github.com/mozilla/pdf.js/blob/master/test/downloadutils.js), such that the HTML file is first downloaded and parsed to obtain a direct PDF link.

**Comment by timvandermeij** [comment]
It looks like we can just update all links to add `if_` after the ID in the URL. For example, this is current linked test case (`issue1127.pdf.link`):

https://web.archive.org/web/20160114105739/https://vmp.ethz.ch/pdfs/diplome/vordiplome/Block%201/Algorithmen_%26_Komplexitaet/AlgoKo_f08_Aufg.pdf

This can be changed to:

https://web.archive.org/web/20160114105739if_/https://vmp.ethz.ch/pdfs/diplome/vordiplome/Block%201/Algorithmen_%26_Komplexitaet/AlgoKo_f08_Aufg.pdf

to get the direct link.

I have tested this with a number of linked testcases and it seems to work for all of them.

**Comment by Snuffleupagus** [comment]
> It looks like we can just update all links to add if_ after the ID in the URL. For example, this is a current linked test case (issue1127.pdf.link):

I've noticed that as well, but I'm not sure if we really want to assume that the format will be constant in the future (it *could* potentially even depend on e.g. load balancing or similar things). I'd hate for us to do search-and-replace on all `*.pdf.link` files now, just to have to redo it in a couple of months time.

**Comment by timvandermeij** [comment]
Correct, but doesn't the same apply for HTML parsing? If the markup changes, we may get the same problem. Personally I'm fine with either solution by the way, because I'm really on the fence about which one is faster/more future-proof.

**Comment by timvandermeij** [comment]
There is also fallback code at https://github.com/mozilla/pdf.js/blob/master/test/downloadutils.js#L40 which I assume does not work anymore. I also think we should remove that because silently handling errors does not sound right in the context of testing.

Since we have Internet Archive-specific code there anyway, I think I'm fine with handling this over there. Let's try to consolidate the code in one block as much as possible.

**Comment by Snuffleupagus** [comment]
> I'd rather have things fail loudly so we know there is an error and can fix it properly.

Just FYI: I attempted to implement something along those lines in PR #7947, but the resulting discussion indicated that failing hard wasn't really desirable behaviour here.

**Comment by timvandermeij** [comment]
I have one more solution for this. It's a bit of a hybrid approach for the two solutions. How about in `test/downloadutils.js` we detect that we are dealing with an Internet Archive URL and perform the `if_` transformation there? That we we don't have to search/replace and can easily adjust the code if the Internet Archive were to change its format again (or implement HTML parsing there later on)?

**Comment by Snuffleupagus** [comment]
@timvandermeij https://github.com/mozilla/pdf.js/issues/8920#issuecomment-330047410 seems like a good compromise for now! Time permitting, do you want to take a stab at implementing it (since the current state isn't great for someone attempting to run tests for the first time)?

**Comment by timvandermeij** [comment]
Yes, I'm hoping I can take a look at this in the coming weekend.
