### ISSUE TITLE
when I compress pdf.js ,it's wrong

### ISSUE THREAD

**Issue by BEFORE-4** [mozilla/pdf.js#8923]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:  
- Operating system and its version:  windows 7

- PDF.js version:   1.9.564
- Is an extension:

Steps to reproduce the problem:
1.  when I use yuicompressor.jar   compress my pdf.js file ,it's wrong 
2.it told me syntax error 

What is the expected behavior? (add screenshot)
![error](https://user-images.githubusercontent.com/22853610/30528197-433f6c96-9c63-11e7-8e96-60be3af3da2d.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 #****

**Comment by Snuffleupagus** [comment]
> when I use yuicompressor.jar compress my pdf.js file ,it's wrong

We only support UglifyJS, please see the wiki: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#minified.

Closing as answered.
