### ISSUE TITLE
printing in chrome on ios 10 fails when pdf was loaded by blob

### ISSUE THREAD

**Issue by grd2345** [mozilla/pdf.js#8934]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: **chrome 61.0.3163.73**
- Operating system and its version: **ios 10**
- PDF.js version: **1.9.575**
- Is an extension: **no**

Steps to reproduce the problem:
1. **Just load a pdf from blob in the viewer**
2. **Click print button**

What is the expected behavior? (add screenshot)
**Expecting the print preview menu to open up containing the pdf.**

What went wrong? (add screenshot)
**After printing progress, nothing opens up.**

Notes:
**I was debugging this and the issue seems to be something in pdf.js after the viewer calls pdfPage.render(renderContext).promise under function renderPage the scratchCanvas.toDataURL() doesn't return the string representation of the image. I tested this in all other platforms like Safari, chrome on desktop, chrome on android and the scratchCanvas.toDataURL() return the string representation of the page canvas and renders fine, but seems in chrome ios 10, this is not occurring.**

**Comment by jackiewu** [comment]
We also get this issue, then our solution is:
1. add `print.call(window)` before` setTimeout(...print.call(window)..., 0)`
2. comment `setTimeout(resolve, 20)`

```js
    return new Promise(function (resolve) {
      if (/(crios).+safari/i.test(navigator.userAgent || '')) {
        print.call(window);
      }
      setTimeout(function () {
        if (!_this2.active) {
          resolve();
          return;
        }
        try {
          window.document.execCommand('print', false, null);
        } catch (e) {
          print.call(window);
        }
        // for safari (do not auto close this progress dialog)
        if (!/(version|mwendo|crios).+safari/i.test(navigator.userAgent || '')) {
          setTimeout(resolve, 20);
        }
      }, 0);
    });
```

reference issue#7597: https://github.com/mozilla/pdf.js/issues/7597#issuecomment-370443800

**Comment by Snuffleupagus** [comment]
> I tested this in all other platforms like Safari, chrome on desktop, chrome on android and the scratchCanvas.toDataURL() return the string representation of the page canvas and renders fine, but seems in chrome ios 10, this is not occurring.

Given that this is specific to a *particular* platform/browser, it seems to point to a browser bug rather than a PDF.js one; should this issue be closed as INVALID since there's probably not much to be done here?
