### ISSUE TITLE
Multiple spaces in PDF being squashed to single space in iOS during SVG conversion

### ISSUE THREAD

**Issue by SnailCoil** [mozilla/pdf.js#8935]
Link to PDF file (or attach file here): 
[double_spaces.pdf](https://github.com/mozilla/pdf.js/files/1315807/double_spaces.pdf)

Configuration:
- Web browser and its version: AppleWebKit/603.3.8 Version/10.0 Mobile/14G60 Safari/602.1
- Operating system and its version: iOS 10.3.3
- PDF.js version: pdfjs-dist@1.9.575
- Is an extension: I'm not sure the answer to this. I'm using a small wrapper library in my web app that's specifically for Angular 2+, https://github.com/VadimDez/ng2-pdf-viewer

Steps to reproduce the problem:
1. Convert the attached PDF, or any PDF that contains multiple spaces in a row, to SVG
2. Observe multiple spaces being squashed to a single space

What is the expected behavior? (add screenshot)
![chrome_desktop_spaces](https://user-images.githubusercontent.com/379022/30615466-ed2bc606-9d43-11e7-9e24-7a275e5b4446.png)
Here is the PDF generated on desktop. The double spaces in the PDF are mirrored here.

What went wrong? (add screenshot)
![safari_ios_spaces](https://user-images.githubusercontent.com/379022/30615782-dd339f52-9d44-11e7-9294-f0a2a091e1fa.png)

iOS is automatically squashing multiple spaces to a single space. I verified that the SVG converter generated the correct glyphs, but when the correct string ("double&nbsp;&nbsp;spaces&nbsp;&nbsp;double&nbsp;&nbsp;spaces") was assigned to the svg element's text content, the double spaces disappeared. The reason for this is logical: multiple spaces in HTML are considered to be no different than a single space. 

However, desktop chrome conveniently ignores this, and renders multiple spaces with no problem. Is there a way that we can trick iOS into inserting the multiple spaces? I wondered if we could use non-breaking spaces in place of spaces to get the same functionality...

**Comment by yurydelendik** [comment]
> multiple spaces in HTML are considered to be no different than a single space.

SVG is an XML format. `xml:space="preserve"` shall preserve the spaces.

**Comment by SnailCoil** [comment]
Perhaps it could be a symptom of https://bugs.webkit.org/show_bug.cgi?id=112032

**Comment by yurydelendik** [comment]
> Perhaps it could be a symptom of https://bugs.webkit.org/show_bug.cgi?id=112032

That is the exact issue you are documenting here. The bug above lists a workaround to add xml:space="preserve" to each tspan, but this will increase document size and memory usage.

**Comment by SnailCoil** [comment]
I made a pull request that will prevent the spaces from collapsing, but the overhead is of course unnecessary unless using webkit

**Comment by Snuffleupagus** [comment]
I'm not sure if this issue is still relevant after PR #9340, even beside the fact that the SVG-backend isn't officially supported; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

With PR #9340, which fixed a *very large* number of font bugs, we're now moving all glyphs to the Private Use Area (PUA) since that both fixes and prevents a large number of glyph mapping issues.
Hence, even with the SVG-backend you'd now need to use a *separate* `textLayer` (same as with the `canvas`-backend) in order for e.g. text-selection to work correctly. As such, this issue is likely no longer relevant and can be closed as WONTFIX.
