### ISSUE TITLE
Text horizontally mirrored

### ISSUE THREAD

**Issue by psdevel** [mozilla/pdf.js#8940]
Link to PDF file (or attach file here):
[github_example.pdf](https://github.com/mozilla/pdf.js/files/1321283/github_example.pdf)

Configuration:
- Web browser and its version:
Chrome 60.0.3112.113, IE 11.0.9600.18792, Firefox ESR 38.4.0
- Operating system and its version:
Windows 10
- PDF.js version:
1.8.188
- Is an extension:
no

Steps to reproduce the problem:
1. open the attached PDF document in the demo viewer (https://mozilla.github.io/pdf.js/web/viewer.html)

What is the expected behavior? (add screenshot)
Should view two text elements "MUSTER" and "VORANSICHT VORANSICHT" (Overlapping is OK).
![2017-09-21 15_19_48-github_example pdf - adobe reader](https://user-images.githubusercontent.com/32161979/30697804-74c6da7c-9ee0-11e7-8238-b6cc5b3fc4d1.png)

What went wrong? (add screenshot)
Both texts are horizontally mirrored and on the top of the document.
![2017-09-21 15_38_00-32d10e34-f34d-4a50-a6af-7f9a747c2134](https://user-images.githubusercontent.com/32161979/30698670-e947a5a0-9ee2-11e7-8c14-3bc09f3136b7.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

Regards
Philipp

**Comment by THausherr** [comment]
The pattern matrix (which has a y flip) 

![clipboard01](https://user-images.githubusercontent.com/6665575/30852035-c11d5644-a2aa-11e7-8d85-e8b8ff79aaa0.png)


influences the position + size of the glyphs, which it should not, it should only influence their "color". Proof: Replacing the "0 0 0 /P0 scn" in the content stream with "1 0 0 rg" puts the glyphs at the correct position + size.
[PDFJS-8940_red.pdf](https://github.com/mozilla/pdf.js/files/1332435/PDFJS-8940_red.pdf)

**Comment by psdevel** [comment]
Thanks a lot! As a workaround we changed the color to black, now the behaviour is normal.
I'll leave this issue open, for fixing.
