### ISSUE TITLE
"Worker was destroyed" error message after consecutive loading PDF files

### ISSUE THREAD

**Issue by stefanos113** [mozilla/pdf.js#8942]
Hello,

when I load a pdf into the standard viewer.js and after this I load another one (each time by using the base64 encoded content of the pdf), I got a error message displaying "Worker was destroyed".

The functions/concepts of PDF.js which I use seem to work correctly, even if the error message displays, but I dont know what really happens in the background. Can you help me, avoiding the error?

Below is my code to load a pdf from base64. I just call the "openPdfFromBase64()" function and then the described error occurs.

-----------------------------------------------------------
function openPdfFromBase64(base64) {
    var arr = base64ToArrayBuffer(base64);
    PDFViewerApplication.open(arr);
}

function base64ToArrayBuffer(base64) {
    var binary_string = window.atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}
--------------------------------------------------------

Technical Information:
- PDF.js Version 1.7.225 (build: 17d135f)
- Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0

Related issue:
https://github.com/mozilla/pdf.js/issues/3737

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
