### ISSUE TITLE
I don't think textContentItem.height should be * by textContentItem.textAdvanceScale

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#8945]
This line should be removed: textContentItem.height *= textContentItem.textAdvanceScale
https://github.com/mozilla/pdf.js/blob/abc864fca9547627b1a85c894f2edd24c5a52d11/src/core/evaluator.js#L1425

**Comment by yurydelendik** [comment]
As it's stated this issue is not actionable. Please provide all requested information.

**Comment by ldenoue** [comment]
I made a mistake. Looking at https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js#L79 I now can get the accurate bounding box of text items.
