### ISSUE TITLE
Failure to open url with "C:\" in url

### ISSUE THREAD

**Issue by rr326** [mozilla/pdf.js#8946]
Configuration:
- Web browser and its version:
Electron 1.6
- Operating system and its version:
Windows 10
- PDF.js version:
(These are pdfjs-dist)
Works: v1.9.426
Doesn't work: Latest - eg: 1.9.583
- Is an extension: No

Steps to reproduce the problem:
1. Try to open a file url: "file://C:\Users\John Doe\test.pdf"
PDFJS.getDocument( "file://C:\Users\John Doe\test.pdf")... 
2.ENOENT: no such file or directory, lstat 'C:\C:\Users\John%20Doe\test.pdf"

I've spent a bunch of time on this, and I think there are two issues:
1) the encoded space, which is fixed in 8907
2) the file://C:\... gets transformed to file:///C:\... (extra slash), and then it later sees the / for the filesystem, and adds another c:\ to the front.

Note - this whole file://c:\... works as expected in v1.9.426 (even with the encoded space).

**Comment by mukulmishra18** [comment]
Similar to https://github.com/mozilla/pdf.js/issues/8907 . We have to decode the url using `decodeURI` to get the correct file system path. There is a PR for this issue #8928 .

**Comment by juncaixinchi** [comment]
this error still exists ... `decodeURI` is not working

path before decodeURI: `/C:/User/1234/Desktop/a.pdf`

after decodeURI, path is still the same

fs.lstat would transfrom it to `C:\C:\User\1234\Desktop\a.pdf` and then this error occurred
