### ISSUE TITLE
Wrong letters in text layer when selecting and copying to clipboard

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#8948]
Link to PDF file (or attach file here):
[cpam.pdf](https://github.com/mozilla/pdf.js/files/1326526/cpam.pdf)

Configuration:
- Web browser and its version: Chrome Version 61.0.3163.79 (Official Build) beta (64-bit)
- Operating system and its version: MAC 10.12.6 (16G29)
- PDF.js version: online version as of September 23, 2017
- Is an extension:

Steps to reproduce the problem:
1. load the attached PDF
2. Select the first paragraph "Pour bénéficier de la prise en charge..."
3. Copy to clipboard
4. Error=some letters are not correct in the text: "**3**our **E**énéficier de la prise en char**J**e des frais de santé en cas de maladie ou de maternité vous deve**]** travailler en**)**rance    ou si vous **r**tes sans activité résider en **)**rance de maniqre sta**E**le et ré**J**uli**q**re"

What is the expected behavior? (add screenshot)
The correct text should be "Pour bénéficier de la prise en charge des frais de santé en cas de maladie ou de maternité, vous devez travailler en France ou, si vous êtes sans activité, résider en France de manière stable et régulière"

What went wrong? (add screenshot)
Wrong text

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.7.345`.

**Comment by timvandermeij** [comment]
Yes, this got fixed by a patch since this issue was opened; WFM too, so closing.
