### ISSUE TITLE
when I use chrome, Warning: "Indexing all PDF Object"

### ISSUE THREAD

**Issue by BEFORE-4** [mozilla/pdf.js#8953]
here's my pdf file 
[guidbook.pdf](https://github.com/mozilla/pdf.js/files/1328482/guidbook.pdf)

Configuration:
- Web browser and its version: chrome 56.0.2924.87
- Operating system and its version: win  7
- PDF.js version: v1.9.524

Steps to reproduce the problem:
1. when i use pdfjs in my web project, it can't work in chrome browser,but can work in IE browser.
2.i use pdfjs as a plugin. only add js files and css files。I havn't added *.bcmap, *.properties,  etc files。I added pdf.js.map, pdf.worker.js.map. but it can't work yet.
![error2](https://user-images.githubusercontent.com/22853610/30793797-c21ac09a-a1f6-11e7-97b7-8cc906c78e4a.png)
What went wrong? (add screenshot)
when I use chrome browser ,it told me warn .besides, Invalid or corrupted PDF file.
PDF.js v1.9.524 (build: cd25a51a)
Message: Invalid PDF structure
![error1](https://user-images.githubusercontent.com/22853610/30793875-6e6192c0-a1f7-11e7-9093-623a96ca8af1.png)
i tried to change any pdf, but it couldn't work .

here's browser infos. i can open pdf with request URL
Request URL:http://localhost:8080/main/temp/boardstorage/news/1506308893651.pdf
Request Method:GET
Status Code:302 Found
Remote Address:127.0.0.1:8080
Response Headers
view source
Content-Length:0
Expires:Thu, 01-Jan-1970 00:00:00 GMT
Location:http://localhost:8080/main/login/index.jhtml;jsessionid=fb85wdnwjkti8ucsglga3o30
Server:Jetty(6.1.26)
Set-Cookie:JSESSIONID=fb85wdnwjkti8ucsglga3o30;Path=/main
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:zh-CN,zh;q=0.8
Connection:keep-alive
Host:localhost:8080
Referer:http://localhost:8080/main/financeView/queryNewsList.action?appCode=A45
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

`    attachmentUrl = "http://localhost:8080/main/temp/boardstorage/news/1506308893651.pdf";
animationStartedClosure();
    PDFViewerApplication.animationStartedPromise.then(function () {
	 PDFViewerApplication.open({
	   url: attachmentUrl
	 });
	});	`

can anybody give me some suggestions?

**Comment by yurydelendik** [comment]
The provided PDF, when downloaded, work for me (e.g. via http://mozilla.github.io/pdf.js/web/viewer.html) Looks like a problem with your custom deployment and/or HTTP server you are using. Closing as incomplete, since your to custom deployment of the library is not provided
