### ISSUE TITLE
Links are not clickable with the pdf.js viewer

### ISSUE THREAD

**Issue by rivsc** [mozilla/pdf.js#8956]
Link to PDF file (or attach file here):
[example_link.pdf](https://github.com/mozilla/pdf.js/files/1331992/example_link.pdf)

Configuration:
- Web browser and its version: Chrome 60.0.3112.113 (Build officiel) (64 bits) or Firefox 54.0.1 (64 bits)
- Operating system and its version: Mac OS X El Capitan
- PDF.js version: stable (1.8.188) or beta (1.9.426)

Steps to reproduce the problem:
1. Use pdf.js to render the pdf : https://jsfiddle.net/rivsc/7Lxw5dwr/2/
2. Click on link "Prawn wiki" doesn't work

What is the expected behavior? (add screenshot)
Follow the link when I click on it.

What went wrong? (add screenshot)
Nothing happens when I click on a link.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://jsfiddle.net/rivsc/7Lxw5dwr/2/

On firefox with his integrated viewer, the link are clickable.

**Comment by MyRomance0312** [comment]
8n。trL。i98

发自我的vivo智能手机

Claudel Sylvain <notifications@github.com>编写：

**Comment by Snuffleupagus** [comment]
The [helloworld examples](https://github.com/mozilla/pdf.js/tree/master/examples/helloworld) only demonstrates basic PDF rendering. If you want other features such as annotation/text layer support, please refer to the [pageviewer (or simpleviewer) examples](https://github.com/mozilla/pdf.js/tree/master/examples/components).

Closing as answered.

**Comment by rivsc** [comment]
Thanks for this answer ! I did not see the difference between PDF rendering and text layer support.
