### ISSUE TITLE
Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer

### ISSUE THREAD

**Issue by ash-recommind** [mozilla/pdf.js#8960]
Link to PDF file (or attach file here):
[TheBlueLights_chapter1_DIE_ZWEITE_UND_LÄNGERE_VERSION.PDF](https://github.com/mozilla/pdf.js/files/1323725/TheBlueLights_chapter1_DIE_ZWEITE_UND_LANGERE_VERSION.PDF)

**Configuration**:
- Web browser and its version: Firefox (55.0.3 (32-bit)) and Chrome (Version 60.0.3112.113 (Official Build) (64-bit))
- Operating system and its version: Windows 10 and Windows Server 2012
- PDF.js version: 1.9.600 (build: b8371870)
- Is an extension: no

**Steps to reproduce the problem**:
Load the attached PDF into the pdf.js viewer

**What is the expected behavior?**
Expected is that the text in the PDF is rendered with the font used in the loaded PDF, like it is the case when opening the PDF with another tool like e.g. Adobe Reader:
![pdf_in_adobe_reader](https://user-images.githubusercontent.com/13733259/30922406-55586a7a-a3a9-11e7-88ca-67f1aa3c1b47.png)

**What went wrong?**
A warning occurs in the JS console using Chrome (Version 60.0.3112.113 (Official Build) (64-bit)):
`Warning: Failed to load font "g_d1_f1": SyntaxError: Invalid font data in ArrayBuffer.`

As a result the PDF is rendered with a different font:
![font_loading_error](https://user-images.githubusercontent.com/13733259/30922424-6760eba2-a3a9-11e7-91c0-6123c6f894cd.png)

Using Firefox (55.0.3 (32-bit)) the JS console shows related errors:
```
downloadable font: rejected by sanitizer (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

downloadable font: font load failed (font-family: "g_d1_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
and the rendered result looks similar to loading the PDF into the pdf.js viewer using Chrome.

Note: In IE10 and IE11 the PDF seems to be loaded without any font loading issue - at least there are no font-related warnings/errors in the JS console and in turn it looks similar to opening it in e.g. Adobe Reader.

**Comment by Snuffleupagus** [comment]
The exact browser console messages, in Firefox Nightly 58, using PDF.js version `1.9.600`:
```
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  1323725
downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  1323725
downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64,T1RUTwAJAIAAAwAQQ0ZGIK2um+oAAACcAAAcJk9TLzJFiipkAAAcxAAAAGBjbWFwxfsnUQAAHSQAAADmaGVhZKsnT/0AAB4MAAAANm … AHIAcwBpAG8AbgAgADAALgAxADEAVQBuAGsAbgBvAHcAbgBVAG4AawBuAG8AdwBuAFUAbgBrAG4AbwB3AG4AAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  1323725
```

**Comment by drweb86-work** [comment]
Could you please fix it. Its important for project im working on too.

**Comment by brendandahl** [comment]
@drweb86-work the fix is in progress in the above PR.
