### ISSUE TITLE
Word lookup feature

### ISSUE THREAD

**Issue by samurdhilbk** [mozilla/pdf.js#8961]
I have been working on a word lookup feature where the user simply selects a word (or term) they want to find the meaning of and presses a shortcut key to bring up its meaning within the viewer itself.

![image](https://user-images.githubusercontent.com/13288129/30952017-7e916f0a-a443-11e7-8bc9-0e7d29ce749f.png)

I have already implemented a test version of which a screenshot of a sample result is attached. Any possibility this feature could be incorporated into pdf.js?

**Comment by Snuffleupagus** [comment]
While you may implement something like this in a custom deployment of the PDF.js viewer, I don't think this is something we'd want in the main repo for two reasons. First of all that information isn't present in the PDF file *itself*, and secondly getting it would thus require looking it up at a remote server (which we have no control over). The point of PDF.js is that all of its JavaScript runs in the browser, without the need for external resources in this way.

Closing as answered.

**Comment by timvandermeij** [comment]
Feel free to add your project to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications once it's finished though so it can serve as inspiration for other users.

**Comment by samurdhilbk** [comment]
@timvandermeij I have finished the project. How can it be added to the Wiki?

**Comment by timvandermeij** [comment]
There is an `Edit` button at the top right of the page. If it does not work, you can also add the link here and we'll add it for you.

**Comment by samurdhilbk** [comment]
This is the my fork of the project https://github.com/samurdhilbk/pdf.js. I haven't done it as a separate project since everything except the word lookup feature is the same as pdf.js.

**Comment by timvandermeij** [comment]
Thank you! I have updated the page to add your link and remove dead links.
