### ISSUE TITLE
Some text lines disappear at most zoom levels

### ISSUE THREAD

**Issue by gavinfoley** [mozilla/pdf.js#8967]
## Link to PDF file (or attach file here)
[disappearing-lines.pdf](https://github.com/mozilla/pdf.js/files/1342177/disappearing-lines.pdf)

## Configuration
- Web browser and its version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Version 1703
- PDF.js version: 1.8.188, 1.9.426, 1.9.602
- Is an extension: No

## Steps to reproduce the problem
1. Open the attached PDF in the PDF.JS viewer
2. Set the zoom level to 100%

## What is the expected behavior?
All lines are visible
![sumatrapdf_all-lines-visible](https://user-images.githubusercontent.com/6389719/30988604-c9a69f86-a468-11e7-84e0-25385f15ea7d.png)

## What went wrong?
Some lines are not visible.  Which lines are visible varies depending on the zoom level.  (Attached screenshot is at 100% zoom level.)
![pdf js_some-lines-not-visible](https://user-images.githubusercontent.com/6389719/30988329-1d8e6ca6-a468-11e7-8f54-0dffb5aad1d3.png)

## Link to a viewer
Tested 1.8.188 and 1.9.426 locally, but issue can be reproduced at http://mozilla.github.io/pdf.js/web/viewer.html (which was running 1.9.602 at the time this issue was filed).

**Comment by mxiao6** [comment]
I have re-verified this issue against current Demo (https://mozilla.github.io/pdf.js/web/viewer.html) and observed that this issue is still occurring.

**Comment by stevebingsoo** [comment]
Any updates on this?  I see this bug was reported a few years back and it still occurs on Chrome 78 and pdfjs version 2.3.200.  This is a major impact to me

**Comment by Snuffleupagus** [comment]
WFM, when testing with PDF.js version `2.9.96` in Google Chrome Beta 90.0.4430.72 on Windows.
If this issue still exists, in some platform/browser combination, that clearly suggests a *browser* bug rather than a PDF.js one (and unfortunately that's not something that we can fix here).

**Comment by samsmith-workday** [comment]
Also looking for some updates on this issue. During testing we've noticed this issue. It seems to correlate with default zoom level, but we're hoping to see if PDF.JS was planning any improvements in this area.

**Comment by haysj** [comment]
We have the same issue.  Doesn't happen in FireFox but happens in Chrome and Edge.  Workaround we've been using is setting the initial zoom to 80% via #zoom=80  110% seems to work as well.
