### ISSUE TITLE
hi i have installed pdfjs in angular2 project based webpack the error :Cannot find name 'PDFSource'

### ISSUE THREAD

**Issue by eyaconsulting** [mozilla/pdf.js#8969]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by eyaconsulting** [comment]
hi i have installed pdfjs in angular2 project based webpack the error :
"pdfjs-dist": "^1.7.244"
the error : Cannot find name 'PDFSource'

**Comment by timvandermeij** [comment]
There is no `PDFSource` in the codebase of PDF.js. Aren't you confusing PDF.js with another library? No example project is provided, so we cannot do anymore verification at this point.
