### ISSUE TITLE
Consider updating to worker-loader 1.0

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#8970]
Hey,

just a quick heads-up - worker-loader, one of your dependencies, has just released version 1.0.0. You might want to use it to avoid package duplication for folks that are keeping their dependencies up to date.

Have a good day!

**Comment by timvandermeij** [comment]
Good point. I'll try to go over the dependencies soon to update them.

**Comment by timvandermeij** [comment]
The packages have all been updated to the most recent versions in the PR above.
