### ISSUE TITLE
Unable to open pdf from my domain-demandtechreports.com

### ISSUE THREAD

**Issue by SanjanaShende** [mozilla/pdf.js#8973]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:Chrome '59.0.3071.104'
- Operating system and its version: windows 8
- PDF.js version:Version 2.0
- Is an extension:

Steps to reproduce the problem:
1. web/viewer.html?file=http://www.Demandtechreports.com/IBMResources/fulfilling-the-promise-of-omnichannel-retailingS.pdf
2.

What is the expected behavior? (add screenshot)
Should display pdf stored in folder(folder is stored on domain-demandtechreports.com)

What went wrong? (add screenshot)
-Error
1.Unexpected Server Response
PDF.js v1.8.188 (build: ad1023ff)
Message: Unexpected server response (0) while retrieving PDF "http://www.demandtechreports.com/IBMResources/fulfilling-the-promise-of-omnichannel-retailingS.pdf"

![error](https://user-images.githubusercontent.com/31538809/31004570-918762fc-a512-11e7-9500-a07cbd79a9e3.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr . Closing, since based on provided information, the library works as expected.
