### ISSUE TITLE
Text Selection not complete

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#8974]
Link to PDF file (or attach file here):
[answer.pdf](https://github.com/mozilla/pdf.js/files/1344526/answer.pdf)

Configuration:
- Web browser and its version: Chrome 
- Operating system and its version: Mac 
- PDF.js version: online as of today
- Is an extension: No

Steps to reproduce the problem:
1. select and copy any text that contain the little circled numbers
2. paste to see the result: little numbers are missing from the pasted text

What is the expected behavior? (add screenshot)
Correct text should include the numbers, but the string is missing them

What went wrong? (add screenshot)
The numbers are displayed later in the PDF, and the string around uses spaces, so visually the line looks complete, but we need to merge strings. PDFBox works well on this PDF.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
FWIW Adobe Reader does not copy and paste the text with ① as well.

**Comment by calixteman** [comment]
Likely fixed thanks to https://github.com/mozilla/pdf.js/pull/13257.

**Comment by Snuffleupagus** [comment]
Unfortunately this is still *not* fixed, however the description of the bug is quite unclear since this refers to *one particular* line; please try copying the outlined sentence:

![copy](https://user-images.githubusercontent.com/2692120/118296188-f7e95180-b4dc-11eb-8bce-52d83ad7e7c9.png)

**Comment by calixteman** [comment]
Correct, I checked with the first circled 1.
Anyway, the circled numbers are drawn only at the end of the page: they aren't in the normal flow (I mean from a left-to-right-top-to-bottom pov).

**Comment by Snuffleupagus** [comment]
Looking at this issue once more, and noticing that it's *similarly* broken in both Adobe Reader (i.e. the PDF reference implementation) and PDFium (as shipped in Google Chrome) the conclusion is that it's a bug in the PDF document *itself*; all-in-all let's close this as WONTFIX instead.
