### ISSUE TITLE
How to get page wise base64

### ISSUE THREAD

**Issue by GaikwadVikas** [mozilla/pdf.js#8995]
I want to show thumbnail with zoom preview effect of each page. While showing each page I want base64 string of that page. How I can achieve it?

One thing, I need PDF base64. So, Canvas to image base64 will not solve my issue.

Please, help me. Thanks in advance.

**Comment by yurydelendik** [comment]
This does not look like valid PDF.js issue. Closing as invalid.

**Comment by GaikwadVikas** [comment]
Hello, is there any solution?
ᐧ

Regards,
Vikas Gaikwad

**Comment by yurydelendik** [comment]
It's not clear what you are asking. I can just guess. It's not possible to use PDF.js to split one PDF into several PDFs and encode result as base64.

**Comment by GaikwadVikas** [comment]
Thanks for reply.

I want to display pdf pages preview ones it is browsed.


//Convert Pdf to Base64 Array
        var convertDataURIToBinary = function (dataURI) {
            var BASE64_MARKER = ';base64,';
            var base64Index = dataURI.indexOf(BASE64_MARKER) +
BASE64_MARKER.length;
            var base64 = dataURI.substring(base64Index);
            var raw = window.atob(base64);
            var rawLength = raw.length;
            var array = new Uint8Array(new ArrayBuffer(rawLength));
            for (i = 0; i < rawLength; i++) {
                array[i] = raw.charCodeAt(i);
            }
            return array;
        }


var showInCanvas = function (url) {
            try {
                var pdfAsArray = convertDataURIToBinary(url);
                PDFJS.getDocument(pdfAsArray).then(function (pdf) {
                    TotalPagesCount = $this.TixSeatsObject.length +
pdf.numPages;
                    for (var i = 1; i <= pdf.numPages; i++) {
                        pdf.getPage(i).then(function (page) {
                            CreatePage(page);
                        });
                    }
                }, function (ex) {
                    SU.Loading(false, "Page");
                    SU.ShowAlert(LocalLocalizer.Get("Fail"),
LocalLocalizer.Get(ex.message), null, "warning alertDialog zIndex9999");
                });
                var $Dialog = $(Dialog.RootElement).dialog("widget");
                $("#Remove", $Dialog).show();
            } catch (e) {
                CheckPreviewProcess();
            }
        }


        var CreatePage = function (page) {
            var viewport = page.getViewport(2.5);
            var canvas = document.createElement('canvas');
            var ctx = canvas.getContext('2d');
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            var renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };

            page.render(renderContext).then(function () {

                ctx.globalCompositeOperation = "destination-over";
                ctx.fillStyle = "#ffffff";
                ctx.fillRect(0, 0, canvas.width, canvas.height);
               * var imgSRC = canvas.toDataURL();*
                var SeatId = Math.random().toString(36).substr(2, 9);

                $this.TixSeatsObject.push({
                    SeatId: SeatId,
                    Seat: "",
                    PdfStatus: Enumerations.ArtifactStatus.NotAvailable.Name
,
                    BarcodeStatus:
Enumerations.ArtifactStatus.NotAvailable.Name,
                    Barcode: "",
                    SeatStatus: Enumerations.SeatStatus.Any.Name,
                    Base64String: imgSRC,
                    Action: "Browsed",
                    Barcodes: []
                });

                CheckPreviewProcess();
            });
        }



Please, check above code. In *CreatePage* function after *page.render* I
get base64 of image (*canvas.toDataURL*). But, I need base64 of pdf page.

Please, help me.


ᐧ

Regards,
Vikas Gaikwad

**Comment by GaikwadVikas** [comment]
Please, try to understand I am struggling from last one week.
ᐧ

Regards,
Vikas Gaikwad

**Comment by Snuffleupagus** [comment]
> In *CreatePage* function after *page.render* I get base64 of image (*canvas.toDataURL*). But, I need base64 of pdf page.

PDF.js is only a *viewer*, where rendering happens on a `<canvas>` element, and does not contain any functionality to extract a page in PDF format; as was already been explained in https://github.com/mozilla/pdf.js/issues/8995#issuecomment-334469902.

**Comment by Welquer** [comment]
Hi @GaikwadVikas. Did you find any solution?

**Comment by GaikwadVikas** [comment]
No, my bad luck
