### ISSUE TITLE
PDF js only showing upto 3 pages and after that showing only the loader

### ISSUE THREAD

**Issue by Param-Harrison** [mozilla/pdf.js#8998]
Attach (reccomened) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- Operating system and its version: Mac OS
- PDF.js version: npm latest pdfjs-dist

Steps to reproduce the problem:
1. Loading a dynamic pdf url served by node js server causes this issue

What is the expected behavior? (add screenshot)

![expected](https://user-images.githubusercontent.com/2607519/31279855-34e94faa-aab3-11e7-869a-0eeb397852d2.png)

What went wrong? (add screenshot)
![actual](https://user-images.githubusercontent.com/2607519/31279864-3ae75f32-aab3-11e7-9196-184de926891d.png)

**Comment by yurydelendik** [comment]
Not enough information provided to reproduce the issue. Please publish entire example online.

**Comment by Param-Harrison** [comment]
@yurydelendik I figured out the issue, it is not related to pdfjs. It is related to my custom theme for the pdfjs. I sorted that out. So closing the issue.
Thanks for responding fast.
