### ISSUE TITLE
file attachments within the PDF are inaccessible

### ISSUE THREAD

**Issue by libBletchley** [mozilla/pdf.js#9004]
Attach (reccomened) or Link to PDF file here:

[container_of_files.pdf](https://github.com/mozilla/pdf.js/files/1363847/container_of_files.pdf)

Configuration:
- Web browser and its version:

Produced in Firefox 38.8 and 52.  No other FF version was tested.

- Operating system and its version:

Debian/jessie and debian/stretch

- PDF.js version:

Not sure how to find out.  There is no "about" feature.  I'm using the browser stock version anyway.

- Is an extension:
?

Steps to reproduce the problem:
1. open the pdf
2. click on one of the attachments.  Nothing happens in firefox 38.8 or 52.  But version FF 52 does seem to recognize that there is an attachment, because hovering the mouse over it reveals the metadata.  Also right-clicking gives an option to save the whole PDF container, not the file that's being clicked on.

What is the expected behavior? (add screenshot)

I expect to be able to open the attached files.  In particular, it's important to be able to extract them from the PDF container and save them separately so external tools can open them.  I also expect to see a list of attached files when I open the sidebar, and click on the attachments tab.  In this case, clicking on the attachments tab gives no response (in ff 38.8 and ff 52).

What went wrong? (add screenshot)

The attached sample is a PDF containing PGP keys, with "application/pgp" as the MIME type.  No action happened when these attachments were clicked on.  Right-clicking on a link to an attachment also failed to give any options to act on that object. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
^ not sure what's being asked there.  I will say that the Evince PDF viewer does the correct thing for this file.

**Comment by yurydelendik** [comment]
Attached files can be downloaded:
1. Via file attachments panel
2. Or using double-click (similar to Adobe Reader)

I think it's just a confusion with UI.

**Comment by libBletchley** [comment]
> Via file attachments panel

The paperclip is grayed out for me.

> Or using double-click (similar to Adobe Reader)

ah, double click worked in FF 52.  I find that unintuitive.  The only reason to require a double click is if single click has another meaning.  Anyway, certainly a grayed out attachment panel is a defect.

**Comment by yurydelendik** [comment]
WFM in FF55 and 56
<img width="646" alt="screen shot 2017-10-06 at 3 59 01 pm" src="https://user-images.githubusercontent.com/1523410/31298334-51fe3d20-aaaf-11e7-8cf4-7a17c5f05e61.png">

**Comment by libBletchley** [comment]
apparently that was fixed after 52.4.0.
