### ISSUE TITLE
Worker not working (?

### ISSUE THREAD

**Issue by fgilio** [mozilla/pdf.js#9005]
Hi!

I'm working in a project that's using PDF.js and a viewer built on top of the default one (though highly customized). I encountered this problem when doing some tests today.

---

Attach (reccomened) or Link to PDF file here: https://labs.fgilio.com/pdfjs/generic/web/annual_report_2009.pdf (this is just a random PDF I found online, but the behaviour is the same for all PDFs I tested)

Configuration:
- Web browser and it's version: Chrome version 62.0.3202.45 (Official Build) beta (64-bit)
- Operating system and its version: macOS High Sierra 10.13.1 Beta (17B25c)
- PDF.js version: 1.9.629
- Is an extension: No

Steps to reproduce the problem:
1. Load https://labs.fgilio.com/pdfjs/generic/web/viewer.html
2. Check dev tools and the requests to fetch the PDF are not made by the worker: https://www.dropbox.com/s/2hyyoi93sxv8ztm/Screenshot%202017-10-06%2021.04.31.png?dl=0 https://www.dropbox.com/s/aktjw7e6i6jcz74/Screenshot%202017-10-06%2021.05.02.png?dl=0
In previous versions: https://www.dropbox.com/s/l38x4w8q7t3hmpp/Screenshot%202017-10-06%2020.59.59.png?dl=0

What is the expected behavior? (add screenshot)
PDF.js to use the worker (?
What went wrong? (add screenshot)
PDF.js is not using the worker
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://labs.fgilio.com/pdfjs/generic/web/viewer.html

---

PD 1: I don't know if make another issue for this. Is the PDF file, in that same (example)[https://labs.fgilio.com/pdfjs/generic/web/viewer.html] downloaded twice? I see one big `200` request, and a lot of `206` after that one. The first one does seen to download the entire file. I'm pretty sure I'm missing something here.

PD 2: Just so you know, I made 2 small modifications to the default build:
- [Allow it to download files from any domain](https://www.dropbox.com/s/3cldtmy90mpxx07/Screenshot%202017-10-06%2021.11.27.png?dl=0)
- [A relative quick way to change the PDF without touching viewer.js](https://www.dropbox.com/s/ndjm0wzdtsvhkqs/Screenshot%202017-10-06%2021.11.57.png?dl=0)

EDIT: Thanks for reading all this :)

**Comment by yurydelendik** [comment]
PDF.js in new 1.9 requesting file from main page (not from the worker as in the past version). Also, we enabled steams for Chrome, so PDF.js does not stop the main request and issues smaller range requests (206) to fetch data it needs sooner. Does it answer your questions?

**Comment by fgilio** [comment]
>  Does it answer your questions?

All! Thank you! 🙌🏼
