### ISSUE TITLE
ECCN 

### ISSUE THREAD

**Issue by zugzwang1919** [mozilla/pdf.js#9012]
My apologies if this is not the correct mechanism for asking questions.  I have searched for the info, but have been unable to find it.  What is the ECCN for pdf.js?

**Comment by timvandermeij** [comment]
I have no idea what that is. Could you elaborate?

**Comment by zugzwang1919** [comment]
First, thanks for the very quick response.  While I'm not an ECCN expert, I'll give it a shot.  :)  Software leaving the United States needs to declare what type of encryption technologies are being used in the product.  The ECCN classifies the encryption technology.  As an example, here is a link to a page where Apache describes the ECCN for its projects... http://www.apache.org/licenses/exports/   ... for those that build products with those specific projects.  I'm guessing/hoping that this project (pdj.js) has been used many times inside other products and already has an ECCN associated with it.  For the more formal definition of ECCN see... https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn

**Comment by timvandermeij** [comment]
I don't think PDF.js has that. Maybe @yurydelendik or @brendandahl knows?

**Comment by dkwakkel** [comment]
pdf.js seems to use aes256, which is symetric is en accoring to this pagina falls under category 5 part 2: https://www.bis.doc.gov/index.php/policy-guidance/encryption/2-items-in-cat-5-part-2/a-5a002-a-and-5d002-c-1/ii-key-length

I think you have to follow https://www.bis.doc.gov/index.php/documents/new-encryption/1652-cat-5-part-2-quick-reference-guide/file to know what classification applies (or maybe better ask someone from legal from mozilla to do this for you).

**Comment by yurydelendik** [comment]
> (or maybe better ask someone from legal from mozilla to do this for you).

it is in process, yes
