### ISSUE TITLE
Can't fetch file system ionic 2

### ISSUE THREAD

**Issue by daitd** [mozilla/pdf.js#9018]
Hi,

I use the PDFJS to display the pdf file and handle some gesture event in that file. When the app is in offline mode, the libs can't fetch the file i was store in file system (read/write permission). It's show the error "UnknownErrorException: Failed to fetch". See the attach images for more details about this error.

Could any one help me? Thanks in advance.
![screenshot_1](https://user-images.githubusercontent.com/31686613/31421764-710a8774-ae73-11e7-9261-a0f8fa64e6e0.png)
![screenshot_2](https://user-images.githubusercontent.com/31686613/31421765-7172ab60-ae73-11e7-8a67-c8a3ef78f061.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you first read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) and that you provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).

Please keep in mind that it's generally impossible to provide any meaningful assistance when only a screen-shot, and no other information, is provided.
If you want help you'll need to provide access to a complete example, but please keep in mind that the PDF.js contributors cannot be assumed to have knowledge of specific JavaScript frameworks (such as Ionic).

**Comment by daitd** [comment]
Sorry, My bad. I convert image to string base64 data and it works. Please close this issue. Thanks.
