### ISSUE TITLE
Failure to open local file in windows platform

### ISSUE THREAD

**Issue by juncaixinchi** [mozilla/pdf.js#9020]
Configuration:

- Web browser and its version: 
Electron 1.7.8 ( use webpack and set `target: 'electron-renderer'`)
- Operating system and its version:
Windows 10
- PDF.js version:
pdfjs-dist: 1.9.640
- Is an extension:
no

Steps to reproduce the problem:
1. try to open `C:/User/1234/Desktop/a.pdf`
2. window.location transform it to `file:///C:/User/1234/Desktop/a.pdf`
3. PDFNodeStreamFsFullReader get `/C:/User/1234/Desktop/a.pdf`
4. ENOENT: no such file or directory, lstat `C:\C:\User\1234\Desktop\a.pdf`

What went wrong?

the pr https://github.com/mozilla/pdf.js/pull/8928 is not working

path before `decodeURI`: `/C:/User/1234/Desktop/a.pdf`. Howerver, after `decodeURI`, path is still the same.

see also 
https://github.com/mozilla/pdf.js/issues/8946

**Comment by pcad** [comment]
@juncaixinchi - We had a similar issue. PDFJS switched in the 1.9 release to the fetch api.  Fetch doesn't work the same way as XHR wrt the file:// protocol.

https://github.com/electron/electron/issues/9474#issuecomment-301810762

**Comment by juncaixinchi** [comment]
@pcad if you use webpack, you can set `target: 'electron-renderer'` or `target: 'electron` in `webpack.config.js`, then PDFJS will using Node Stream to load local file rather than fetch api.

However, due to the bug I refered in this issue, it's only working in Linux or Mac platform, failed in windows.
About fetch, `file:// protocol` was refused to add to fetch api.  ╮(￣ . ￣)╭

https://github.com/github/fetch/pull/92#issuecomment-140665932

**Comment by matteodem** [comment]
So what's the solution to this problem?

**Comment by juncaixinchi** [comment]
@matteodem  A PR(https://github.com/mozilla/pdf.js/pull/9323) has been added to solve this problem, you can try the latest release, it should be OK.

**Comment by matteodem** [comment]
@juncaixinchi I get following error:

``` 
fetch_stream.js:96 Fetch API cannot load file:///C:/Users/demichma/Downloads/ZH_BD_CD_07773.pdf. URL scheme must be "http" or "https" for CORS request.
```

see http://jsfiddle.net/9engc9mw/2601/

Does the build version have to be updated too?

**Comment by juncaixinchi** [comment]
@matteodem 

That's becasue the fetch api does not support `file` protocol (https://github.com/github/fetch/pull/92#issuecomment-140665932).

You should use `http` protocol: http://jsfiddle.net/9engc9mw/2611/.

If you are electron and webpack user, see https://github.com/mozilla/pdf.js/issues/9020#issuecomment-337106091

**Comment by matteodem** [comment]
@juncaixinchi ...so this means this is not possible? as in the original issue is unresolved / unresolvable?

**Comment by juncaixinchi** [comment]
@matteodem It's not possible to use the fetch api to load local files via `file protocol`. However, the pdf.js supports reading local files if you are in NodeJS environment.
