### ISSUE TITLE
Text doesn't render properly 

### ISSUE THREAD

**Issue by kevin-MarshallWork** [mozilla/pdf.js#9024]
Attach (reccomened) or Link to PDF file here:
https://drive.google.com/open?id=0B2Z7u3CUJ0-NSkJPNTd1NThkWUk

chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://drive.google.com/a/texthelp.com/uc?id=0B2Z7u3CUJ0-NSkJPNTd1NThkWUk&export=download&filename=bad%20pdf.pdf&share=true

Configuration:
- Web browser and its version: Version 61.0.3163.100 (Official Build) (64-bit)
- Operating system and its version: mac v10.13
- PDF.js version:  1.8.557
- Is an extension: yes

Steps to reproduce the problem:
1. the text gets drawn on top of other text

What is the expected behavior? (add screenshot)
![screen shot 2017-10-13 at 14 22 32](https://user-images.githubusercontent.com/16896708/31548264-364fa258-b022-11e7-9352-f2cafc42f2e9.png)

What went wrong? (add screenshot)
![screen shot 2017-10-13 at 14 21 37](https://user-images.githubusercontent.com/16896708/31548269-3d2ccab0-b022-11e7-8d08-02fe112e0b83.png)

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #8938.
