### ISSUE TITLE
Problem "Save picture as" on IE

### ISSUE THREAD

**Issue by Camille** [mozilla/pdf.js#9025]
Configuration:
- Internet Explorer : 11.0.9600.18762
- Windows 7
- PDF.js version: 1.9.640

I can not find "Save picture as" on IE (see attachment)

![ie](https://user-images.githubusercontent.com/2562937/31548947-dff2ed60-b02c-11e7-9e63-1dadb72b0d63.png)

This is ok for Chrome and Firefox.

![chrome](https://user-images.githubusercontent.com/2562937/31548993-043f0c76-b02d-11e7-9c7c-adb6ed091330.png)
![firefox](https://user-images.githubusercontent.com/2562937/31548999-0965636c-b02d-11e7-8e2e-bf32f77ddebb.png)

Is it possible to correct this anomaly?

Camillio

**Comment by yurydelendik** [comment]
Closing as incomplete. Not enough details provided. Also, looks like out of scope of this project -- viewer is designed to display pages content and not re-save it as an image.

**Comment by Camille** [comment]
Okay, 

I ask you a question: From the viewer, is it possible to download the images?

Thank you for your reply

**Comment by yurydelendik** [comment]
> From the viewer, is it possible to download the images?

We don't provide the UI to that in the demo viewer. You can add this functionality, if possible, to your customized version.

**Comment by Camille** [comment]
Thanks :-)
