### ISSUE TITLE
Add event during print preview

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#9030]
hi. if it is possible to request having an event triggered when pdf.js renders pages for print preview.

i dont understand the inner workings and while i have successfully added some drawings on the pdf.js page to be shown during print preview, it tends to lag and hang  since the drawing is not done asyncrhonously.

if events are fired after a pdf.js page is created and rendered during print preview at least drawing to its canvas will also be part of the promise

**Comment by yurydelendik** [comment]
it is the same events that triggered during printing: "beforeprint" and "afterprint" (see https://developer.mozilla.org/en-US/docs/Web/Events/beforeprint). The PDF.js relies on these events, so it does not see difference between print or print preview. Closing as answered.
