### ISSUE TITLE
Where the get file attribute in Pdfjs?

### ISSUE THREAD

**Issue by sofvlad** [mozilla/pdf.js#9042]
I have a task and I have a question to implement it, who better to ask here.
I in the attribute file I insert an encrypted link to a PDF document.
Where does Pdfjs receive this file attribute, so I will be able to implement the decryption?

Thanks in advance. 
_P.S: sorry for my English._

**Comment by timvandermeij** [comment]
I think this is what you're looking for: https://github.com/mozilla/pdf.js/blob/c80237729c840b2e1abe4da8d2ffc62a0f43ddd9/web/app.js#L1833

**Comment by sofvlad** [comment]
I downloaded from the [official website](https://mozilla.github.io/pdf.js/) on the "download" button. And that's all I have in the directory.
![default](https://user-images.githubusercontent.com/23077203/31741961-f50aeece-b477-11e7-9906-22abad3307b6.JPG)

**Comment by timvandermeij** [comment]
In that case it should be in `viewer.js`. Search for `openFile` for `fileInput`.
