### ISSUE TITLE
Intermittent failure on f1040 form reftests

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#9047]
Looks like the intermittent is back (see https://github.com/mozilla/pdf.js/pull/9045#issuecomment-337963970).

Old bug #8334

**Comment by timvandermeij** [comment]
It looks like this happens intermittently for all reference tests that render AcroForms. I suspect the SVG rasterizer is somehow not completing in time/at all for the tests. Another instance of this is https://github.com/mozilla/pdf.js/pull/9730#issuecomment-393422179.

**Comment by timvandermeij** [comment]
Closing since this has not happened in a while now.
