### ISSUE TITLE
PDFJS - memory shoots up to 1 GB and does not decrease even after destroying the loadingTask

### ISSUE THREAD

**Issue by Srinithi-23** [mozilla/pdf.js#9048]
Attach (recommended) or Link to PDF file here:
I am developing an ember application - pdf viewer. I use the ember addon - ember-pdf-js. Here I have created a component that uses the 'PDFJS' object to render the pdf.( I dont use the addon's component). I load the document using 'getdocument(url)' method of PDFJS. Here while scrolling through the pdf, in the task manager I noticed that the memory shoots upto 1 - 1.5 GB. 
pdf - 
[1000_Java_Tips_low copy_1 (1).pdf](https://github.com/mozilla/pdf.js/files/1401883/1000_Java_Tips_low.copy_1.1.pdf)

Even after destroying the component, the memory consumed still does not decrease quickly. Also memory does not clear up if the byte-range requests in pending are aborted while destroying the component.
I destroy the PDFLoadingTask. Kindly let me know if any other object should be cleaned up. 
Configuration:
- Web browser and its version: Chrome v61.0.3163.100 
- PDF.js version: 1.7.331
- Is an extension: ember-pdf-js - https://www.npmjs.com/package/ember-pdf-js

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, when asking questions about custom implementations of PDF.js you really need to provide a complete (and preferably small and self-contained) example that can be used to easily reproduce the issue.

> I am developing an ember application - pdf viewer. I use the ember addon - ember-pdf-js.

Note that it's really difficult for us to provide support for third-party project that embed PDF.js, hence the need for complete examples. 

> PDF.js version: 1.7.331

Is the issue reproducible with the *latest* version of PDF.js?

> Is an extension: ember-pdf-js - https://www.npmjs.com/package/ember-pdf-js

I see how that question might be confusing, but it's actually referring to https://github.com/mozilla/pdf.js#browser-extensions.

**Comment by Srinithi-23** [comment]
I have written a ember component to view PDFs. 

The method to load the document:
`load (url) {
			let self = this;
		      
		    let loadingTask = window.PDFJS.getDocument(url);
		    set(self,'pdfLoadingTask',loadingTask); 
		    
		    loadingTask.onPassword = (updateCallback, reason) => {		 
		    		set(self, 'updateCallback', updateCallback);
		    };	
		    
		    loadingTask = loadingTask.then((pdfDocument) => {
		    	
		    	self.send('setPdfViewer');
			    let viewer = get(self,'pdfViewer');
				viewer.setDocument(pdfDocument);
				let linkService = get(self,'pdfLinkService');
				linkService.setDocument(pdfDocument);

			}).catch(function(){
					/**
					 * To handle cases where the PDF might be of invalid structure
					 */			
			});
		}

The willDestroyElement hook called upon destroying the component

willDestroyElement() {
		let self=this;
		self._super(...arguments);
		get(self,'pdfLoadingTask').destroy(); //To destroy the requests once the component is destroyed
		set(self,'pdfLoadingTask',null); //No I18N
	}`

I need to know if there is any other object to be cleaned up.

> Is the issue reproducible with the latest version of PDF.js?

I tried with version 1.9.658 still the same. The memory occupied does not decrease

**Comment by Srinithi-23** [comment]
https://github.com/Srinithi-23/Pdfjs-viewer

This is the sample ember app I have developed where the issue is reproducible. Kindly please let us know if anything else has to be cleaned up.

**Comment by wangyunshuo** [comment]
Yes, I have encountered this problem Is there a good solution?

**Comment by dschissler** [comment]
I'm using pdf.js for one-page PDFs so that they can be loaded in as the viewer scrolls.  I've noticed that Chrome and Chromium appear to never be able to release memory when a webworker is used and so I'm currently working around this by disabling a webworker when using Chrome.  Try disabling webworker with `PDFJS.workerSrc = false` and then seeing if the memory usage decreases after destroying the views and elements.

**Comment by UlricW** [comment]
@dschissler I tried your solution but I don't see any effect

**Comment by prasad-nagabathula** [comment]
Hi @dschissler, in which block we need to disable it?

**Comment by maitzeth** [comment]
Take a look of this

`PDFJS.getDocument(url)
  .then(function(pdf) {
    window.currentPDF = pdf;
  })`

Then you can access to that property everywhere and destroy that PDF and kill the current thread.

I know is a bad practice, but you know what I mean.

**Comment by retrazil** [comment]
Is this still an issue ?

**Comment by dschissler** [comment]
I'd love to look into this when I can get PDF v2 going in my project.  I've been able to successfully integrate it into my test kit.  If I had to guess either PDF.js or Chrome has changed during all of this time.

**Comment by dschissler** [comment]
Unfortunately I'm still having this issue on Chrome with `2.1.266` (pre-release).  I'm currently trying to figure out how to disable web workers in this new version.  When I set the webworker src to false as before then the browser refreshes each time.  I've been able to get a "fake web worker" working on Firefox by using a security extension that disallows it.  I can't figure out how to disable it through the API.

**Comment by josephernest** [comment]
Same problem here; can someone summarize the solution for this?

```
loadingTask = pdfjsLib.getDocument(typedarray);
        loadingTask.promise.then(function(pdf) {  
            getNextPage(pdf, 1);
        });
```

and

```
loadingTask.destroy();
```
when all pages are done inside `getNextPage`.

**Comment by peterzanetti** [comment]
any update on this? Using react-pdf and memory is never released at all. every additional re-render adds memory and it is never released, unmounting the component does nothing and it is never released.

**Comment by Snuffleupagus** [comment]
Closing this old issue, since it's unfortunately quite difficult to "fix" this:
 - Given that it's talking about using the PDF.js library within a framework, in this case Ember, which the PDF.js contributors don't really know. Furthermore, it's also *possible* that the Ember-framework somehow contributes to the issue.
 - Given the lack of a small and *reduced* test-case, which using the PDF.js library directly (without a framework on top), means that any debugging becomes quite difficult.
