### ISSUE TITLE
Bug 767692 - Previous/Next Page button icons remind me of undo/redo/refresh because of bending

### ISSUE THREAD

**Issue by vikasmahato** [mozilla/pdf.js#9051]
The Page switching buttons in Aurora, Evince (apparently Tango) and Okular.

The icons on the “Previous Page” and “Next Page” buttons remind of “Undo” and “Redo” buttons because of the curves.

[Screenshot](https://bug767692.bmoattachments.org/attachment.cgi?id=636060)

**Comment by vikasmahato** [comment]
@jdm @jviereck 
This bug was open on  Bugzilla and I wanted to work on this one. Can you guide me on how to proceed?

**Comment by thisisabhinay** [comment]
@vikasmahato @jdm @jviereck  Resolved the issue. Check this pull request:[https://github.com/mozilla/pdf.js/pull/9056]( https://github.com/mozilla/pdf.js/pull/9056)

**Comment by Snuffleupagus** [comment]
I believe that https://github.com/mozilla/pdf.js/pull/10673#issuecomment-475874671 applies equally well here too; closing this issue as WONTFIX?
