### ISSUE TITLE
pdfjs 1.9.426 hang on iOS Safari

### ISSUE THREAD

**Issue by wxspku** [mozilla/pdf.js#9053]
Attach (recommended) or Link to PDF file here:
[55359876-E.pdf](https://github.com/mozilla/pdf.js/files/1403995/55359876-E.pdf)
[89976168-E.pdf](https://github.com/mozilla/pdf.js/files/1403996/89976168-E.pdf)

Configuration:
- Web browser and its version: Safari in iPhone
- Operating system and its version: iOS 10.0.2、10.3.3、11.0.3
- PDF.js version:  pdfjs-1.9.426
- Is an extension: no

Steps to reproduce the problem:
1. Deploy pdf.js on apache tomcat in my server 192.168.1.188;
2. Read the atached pdf file from http://192.168.1.188:8080/pdfjs/web/viewer.html?file=55359876-E.pdf via three iPhones;
3: The file rendering hangs as screenshot in all the three iphones;
4: Another file 89976168-E also hangs on the same three iphones;
5: Remote debug via weinre, no error report found;
6: The error files can be read from Andriod phones via the same url;

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![768193328660768723](https://user-images.githubusercontent.com/29788419/31850810-cf97fa72-b68b-11e7-9f9c-5b7f0a88a5af.jpg)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by amaianti** [comment]
Also downgrading the pdf.js version to an older version (like 1.8.527) doesn't resolve the problem.
With Safari 9.1 the library works. So it seems that the problem is related to safari >=10

**Comment by THausherr** [comment]
@wxspku did you create these files yourself? If yes then make sure all non standard 14 fonts are embedded. The font STSong-Light isn't, which can lead to weird results. (I don't know if this is the cause of your problem).

**Comment by wxspku** [comment]
@THausherr The files are created by myself using iText. I don't think the  font STSong-Light is the reason for the bug  because other files with the font can be displayed correctly. As @amaianti  said, the bug is related to safari 10, I can display the incorrect file in early iOS safari.
[68898408-S.pdf](https://github.com/mozilla/pdf.js/files/1418130/68898408-S.pdf)

**Comment by wxspku** [comment]
The problem is caused by none standard font which is not embedded in pdf file. 
![fonts](https://user-images.githubusercontent.com/29788419/33643674-95eee650-da7b-11e7-9744-e6dc627e2a37.png)
The font is a Chinese font.  We meet the same problem with other Chinese font such as simsun or simhei.
I think the reason for the problem is unsuccessful font substitution in iOS safari 10+.

**Comment by THausherr** [comment]
That's why you should always embed such fonts. Then there's no substitution.
https://stackoverflow.com/questions/5660781/how-to-subset-the-fonts-used-in-a-pdf-with-itextsharp

**Comment by wklu** [comment]
In IOS, the default fonts are divided into three categories:

1: STHeiti-Light.ttc and STHeiti-Medium.ttc represent Chinese characters.

2: _H_Helvetica.ttc and _H_HelveticaNeue.ttc represent English and digital fonts.

3: LockClock.ttf stands for lock screen time fonts.

If PDF has other fonts, IOS will take a long time.
Solution: please change the font or insert the font

**Comment by roinheart** [comment]
后来问题解决了吗？

**Comment by roinheart** [comment]
我也遇到了这个问题，安卓上一点问题没有，IOS就不行了。后来你是怎么解决得啊？

**Comment by wxspku** [comment]
这个是iOS对中文字体的处理造成的。
我们是用于呈现自己生成的PDF，所以直接将字体内嵌就没OK了！
但是阅读其他人提供的含中文字体的PDF仍然有问题，建议直接调用iOS内嵌的PDF阅读器！

________________________________
wxs_pku@hotmail.com

**Comment by roinheart** [comment]
谢谢提供思路啊，安卓弄好了，Apple这里卡两天了！

**Comment by Snuffleupagus** [comment]
Please stop spamming this bug tracker with non-English (and only tangentially relevant) posts!

**Comment by wxspku** [comment]
不客气！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: roinheart <notifications@github.com>
发送时间: Wednesday, March 13, 2019 9:53:50 PM
收件人: mozilla/pdf.js
抄送: wxspku; Mention
主题: Re: [mozilla/pdf.js] pdfjs 1.9.426 hang on iOS Safari (#9053)


谢谢提供思路啊，安卓弄好了，Apple这里卡两天了！

―

**Comment by timvandermeij** [comment]
I have removed all non-English comments. Please only post English and relevant comments.

**Comment by Snuffleupagus** [comment]
This looks like a platform/browser bug, rather than a PDF.js one, hence this unfortunately doesn't seem like something that can be fixed *here*.
