### ISSUE TITLE
Release an updated stable version (v1.8.x) with worker-loader@^1.0.0

### ISSUE THREAD

**Issue by elliottsj** [mozilla/pdf.js#9059]
I'm working on upgrading a project from webpack@2 to webpack@3, but pdfjs-dist is preventing us from upgrading:
* We're using pdfjs-dist@^1.8.183, and we want to stay on the stable release to avoid potential bugs; upgrading to 1.9.x is not an option for us.
* pdfjs-dist@^1.8.183 depends on worker-loader@^0.8.0, which has a [peerDependency on webpack@^2.2.0](https://github.com/webpack-contrib/worker-loader/blob/v0.8.0/package.json#L31), making webpack@3 incompatible.
* We're using npm shrinkwrap, but [npm has an issue which prevents using shrinkwrap with mismatched peer dependencies](https://github.com/npm/npm/issues/12909).

If it's convenient for you guys to release a v1.8.x version with worker-loader@^1.0.0, that would make my life a bit easier since I won't have to maintain my own fork of pdfjs-dist.

Thanks!

**Comment by yurydelendik** [comment]
> upgrading to 1.9.x is not an option for us.

Can you explain this statement? Why you cannot upgrade to 1.9.x?

> convenient for you guys to release a v1.8.x version with worker-loader@^1.0.0, that would make my life a bit easier since I won't have to maintain my own fork of pdfjs-dist.

This is not a regression or breaking change. We don't want to put much effort in backporting a patch without a really good reason and taking a risk of breaking something else. If you cannot use 1.9, I'm afraid you have to maintain your own fork.

**Comment by elliottsj** [comment]
Ok, that's fair.

I think we can technically upgrade to 1.9.x, though it'll require some more testing. One thing that stopped working after trying 1.9.x was our call to `PDFViewer.setDocument()`, since it [no longer returns a promise](https://github.com/mozilla/pdf.js/commit/d0e93721ae300bbac0f0f08461a59bef8a069430). It was a fairly simple fix (see below), but I'm a bit worried about finding other undocumented breaking changes.

```diff
// 1.8.x:
-this._viewer.setDocument(pdf).then(() => { /*...*/ });
// 1.9.x:
+this._viewer.setDocument(pdf);
+this._viewer.firstPagePromise.then(() => { /*...*/ });
```

**Comment by timvandermeij** [comment]
You can now use version 1.9 as stable version (see https://github.com/mozilla/pdf.js/releases) since we released it yesterday. This should allow you to upgrade and still use a stable release. The fix for `worker-loader`, together with other improvements, is on schedule for version 1.10. Hopefully this helps a bit.
