### ISSUE TITLE
Scrolling with up-down arrow keys broken

### ISSUE THREAD

**Issue by HFriberg-mosek** [mozilla/pdf.js#9063]
I am seeing weird behavior in all PDF documents:

1. Up/down-arrow keys change page instead of scrolling.
2. Page-down (FN + down-arrow on my keyboard) scroll correctly down first time, but jumps to the top of the current page the second time. Alternating behavior.
3. Page-up (FN + up-arrow on my keyboard) always jump to the top of the entire document.

I am using Firefox 56.0 (64-bit) on Ubuntu 16.04 LTS, and have been using pdf.js for a long time on this macbook without issues of any kind -- so it must be a fairly recent regression somewhere.

Plugins:
OpenH264 Video Codec
Shockwave Flash

Extensions (I only manually added the first):
After the deadline
Safe Browsing Version 4 (temporary add-on)
Ubuntu Modifications

**Comment by timvandermeij** [comment]
I cannot reproduce any of this using Firefox 56.0.1 (64-bit) on Arch Linux. Does it also happen with the demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html, or only with the built-in version in Firefox?

**Comment by HFriberg-mosek** [comment]
In demo viewer with text selector mode:
1. As explained.
2. As explained.
3. PageUp jumped to the top of the document a few times, more often it got stuck in an alternating loop as PageDown, but most frequently it jumped to the first paragraph of the previous page.

In demo viewer right after a switch hand mode:
1. As explained.
2. PageDown always jumps to the top of the document.
3. PageUp always jumps to the top of the document.

In demo viewer after double-clicking on a page in hand mode:
Behavior is now comparable to text selector mode. In my first attempt a blinking cursor appeared in the top right corner of the page (did not allow me to type anything), but I cannot reproduce this cursor myself anymore.

**Comment by HFriberg-mosek** [comment]
Sorry, this may not be pdf.js after all. I just noted that the blinking cursor haunts me on other websites too, also this github page if I click any text element, and causes weird up/down arrow key behavior (I usually scroll with my mouse so I didn't notice). Since my PageUp and PageDown action happens via FN + one of these arrow keys, my guess is that Firefox messes up the events.

**Comment by HFriberg-mosek** [comment]
Yes! The blinking cursor was the smoking gun. Its called caret browsing (see https://support.mozilla.org/en-US/questions/974774) and disabling it turned pdf.js back to normal. I guess I have accidentally pressed F7 at some point recently which is the shortcut for caret browsing in Firefox.
