### ISSUE TITLE
PDFJS.getDocument().then is not working, no file is loaded, no errors in console

### ISSUE THREAD

**Issue by Tapaswini1** [mozilla/pdf.js#9064]
I am upgrading the version from 1.4.20 to 1.9.426
But it is not going to this method "PDFJS.getDocument().then" from version "1.5.188" onwards
I tried all the following versions but it doesn't work
Seems like some generic issue, please suggest

My pdf works fine in helloworld example in firefox but throws below error in chrome:
pdf.js:6270 Failed to load file:///D:/PdfJs/debug/example/sample.pdf: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

same with any pdf file

Configuration:
- Google chrome Version 62.0.3202.62 (Official Build) (64-bit)
- Windows 10 pro
- pdf.js version 1.9.426

**Comment by timvandermeij** [comment]
The `getDocument` API endpoints returns a loading task (see https://github.com/mozilla/pdf.js/issues/7763#issuecomment-329751723). Hence, you should use `PDFJS.getDocument(...).promise.then(...);`.

**Comment by Tapaswini1** [comment]
Thank you for your suggestion
I already tried with '.promise' - it did not worked for me and my file is on web server
I am getting this message in console from version "1.5.188" onwards : "Error in downloading file require:null"
Is this something to do with domain, any fix for it
Thank you

**Comment by yurydelendik** [comment]
> Is this something to do with domain, any fix for it

Please provide entire app and data online, so we can look at it. Otherwise, as stated, this issue is incomplete.
