### ISSUE TITLE
ElasticSearch

### ISSUE THREAD

**Issue by JoseCavalcanti** [mozilla/pdf.js#9065]
Hi, I don´t know if it´s the right place, but I want to know if PDF.js can show ElasticSearch results (Hits).

Regards,

**Comment by yurydelendik** [comment]
> PDF.js can show ElasticSearch results

No, PDF.js does not contain any interface or implements specific search algorithms. All PDF.js can do is to return text content of the PDF pages. The demo viewer performs some basic search over this content (without indexing). That is the scope of this project. Closing as answered.

**Comment by JoseCavalcanti** [comment]
Yury, thanks for your reply.
Do you know a solution for my problem?


Regards,

José Augusto Cavalcanti

[https://gallery.mailchimp.com/256b42ea159c38a639e608eca/images/4514cde8-e00c-46d7-bdb9-3afb63156958.png]<http://www.edocs.com.br/>

jose.cavalcanti@edocs.com.br<mailto:jose.cavalcanti@edocs.com.br>
http://www.edocs.com.br<http://www.edocs.com.br/>
Av. Rio Branco, 156/Sala 2134
20040-003 - Rio de Janeiro - RJ
(21) 3958-7702

De: Yury Delendik [mailto:notifications@github.com]
Enviada em: terça-feira, 24 de outubro de 2017 14:53
Para: mozilla/pdf.js <pdf.js@noreply.github.com>
Cc: José Augusto Cavalcanti (eDocs) <jose.cavalcanti@edocs.com.br>; Author <author@noreply.github.com>
Assunto: Re: [mozilla/pdf.js] ElasticSearch (#9065)


PDF.js can show ElasticSearch results

No, PDF.js does not contain any interface or implements specific search algorithms. All PDF.js can do is to return text content of the PDF pages. The demo viewer performs some basic search over this content (without indexing). That is the scope of this project. Closing as answered.
