### ISSUE TITLE
Rectangular selection, can't get x/y/width/height for each text layer element 

### ISSUE THREAD

**Issue by Vi-dot** [mozilla/pdf.js#9074]
Hello,

Configuration:
- Web browser and its version: **Firefox 56.0 and Chromium 62.0.3202.62**
- Operating system and its version: **Ubuntu 16.04 LTS**
- PDF.js version: **1.9.602** inside angular4 project
- Is a browser extension: **No**

**Steps to reproduce the problem:**

```javascript
function getElementsInRect(rectSelection, targetPageNumber) {
    var pages = document.getElementsByClassName('page');
    var targetPage = pages[targetPageNumber];

    var resList = [];

    searchElementsInRect(targetPage, rectSelection, restList);
}

function searchElementsInRect(element, rectSelection, restList) {

    var style = window.getComputedStyle(element);
    var transform = new WebKitCSSMatrix(style.webkitTransform);
    var vstyle = {
      left: parseFloat(style.left),
      top: parseFloat(style.top),
      width: parseFloat(style.width),
      height: parseFloat(style.height),
      scaleX: transform.a,
      scaleY: transform.d
    };

    var rectElement = {
      x: vstyle.left,
      x2: vstyle.left + vstyle.width*vstyle.scaleX,
      y: vstyle.top,
      y2: vstyle.top + vstyle.height*vstyle.scaleY
    };

    console.log(element.offsetWidth, element.clientWidth, element.getBoundingClientRect().width, element.style.width, style.width, vstyle.width, $(element).width());
	//  shows 0 0 0 auto NaN 0

    if (
      (rectElement.x >= rectSelection.x)
      && (rectElement.x2 <= rectSelection.x2)
      && (rectElement.y >= rectSelection.y)
      && (rectElement.y2 <= rectSelection.y2)
    )
      restList.push(element);

    for (var i=0 ; i<element.children.length ; i++)
      searchElementsInRect(element.children[i], rectSelection, restList);
 }
```

**What is the expected behavior?**
I would retrieve x/y/width/height of each text layer element to know what is concerned by a rectangular selection. The best way would be using [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), because it apply directly scale transformations. This [gist](https://gist.github.com/yurydelendik/2a1879aa4f7575a3ca00) from @yurydelendik shows an example, but it doesn't work any more.

**What went wrong?**
`getBoundingClientRect()` doesn't work with `textLayer` elements but works nice with `annotationLayer`.
In the code above "Steps to reproduce the problem", there is a way to get X, Y, ScaleX and ScaleY, using `window.getComputedStyle(element)`.
But it's still missing Width and Height.

**Comment by Snuffleupagus** [comment]
Unfortunately this issue isn't really actionable as-is, and it doesn't really seem like a bug in the PDF.js library as such; please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
