### ISSUE TITLE
Zoom level is not maintained after Back navigation

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#9080]
Attach (recommended) or Link to PDF file here: 
[10.1093@bjps@axu026.pdf](https://github.com/mozilla/pdf.js/files/1425013/10.1093.bjps.axu026.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 64.0.3252.0 (Official Build) canary (64-bit)
- Operating system and its version: Win 10 10.0.16299 Build 16299
- PDF.js version: 1.8.557
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open document
2. Click on a cross-reference (e.g., Barkow et al.[1992] on p.2)
3. Click on the Back arrow

What is the expected behavior? (add screenshot)
You're supposed to be taken back to p.2 with the **original** zoom
![back_before](https://user-images.githubusercontent.com/2311076/32143690-070b74a4-bcb6-11e7-8f6b-f77c0182386d.jpg)

What went wrong? (add screenshot)
The zoom level is wrong (that of the reference)
![back_after](https://user-images.githubusercontent.com/2311076/32143695-20479876-bcb6-11e7-851d-8b91eb406316.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Closing as fixed by PR #8775.
