### ISSUE TITLE
filename/url with params

### ISSUE THREAD

**Issue by jeffbeagley** [mozilla/pdf.js#9085]
I have a url that grabs image data from the database and then returns it as a pdf header type in another file, however the url needs a parameter filled out like so

`https://www.example.com/portal/plugins/pdfjs-dist/web/viewer.html?file=https://www.example.com/portal/imageload.php?i=123`

I'm using the viewer to display the pdf, which is working fine, however I had to change some code within viewer.JS to get it to work

Old code
```
function parseQueryString(query) {
  var parts = query.split('&');
  var params = Object.create(null);
  for (var i = 0, ii = parts.length; i < ii; ++i) {
    var param = parts[i].split('=');
    var key = param[0].toLowerCase();
    var value = param.length > 1 ? param[1] : null;
    params[decodeURIComponent(key)] = decodeURIComponent(value);
  }
  return params;

}

```

had to be changed to 

```
function parseQueryString(query) {
  var parts = query.split('&');
  var params = Object.create(null);
  for (var i = 0, ii = parts.length; i < ii; ++i) {
    var param = parts[i].split('file=');
    var key = "file";
    var value = param.length > 1 ? param[1] : null;
    params[decodeURIComponent(key)] = decodeURIComponent(value);
  }

  return params;
  
}
```

All of this works fine, but I just wanted to check to see if this is most appropriate or if there is an easier way without having to modify the viewer.js

**Comment by yurydelendik** [comment]
> All of this works fine, but I just wanted to check to see if this is most appropriate or if there is an easier way without having to modify the viewer.js

It's true, you need to modify the demo viewer to make it work for your app. Closing as answered.

The current algorithm is needed to support all types of URLs. (In your case you cannot provide URL like https://www.example.com/portal/imageload.php?i=123&j=45)

**Comment by anrananran** [comment]
I think we can modify the parseQueryString function as below:
`function parseQueryString(query) {
            let parts = query.split('&');
            let params = Object.create(null);
            for (let i = 0, ii = parts.length; i < ii; ++i) {
                let temp = parts[i];
                let equalIndex = temp.indexOf('=');
                
                if(equalIndex > -1) {
                    let key = temp.substr(0,equalIndex).toLowerCase();
                    let value = temp.substr(equalIndex + 1);
                    
                    if(key) {
                        params[decodeURIComponent(key)] = decodeURIComponent(value);
                    }
                }
            }
            return params;
        }`

**Comment by miguelgonch** [comment]
This worked for me. Practically is passing all arguments to the viewer.

```
function parseQueryString(query) {
  var params = Object.create(null);
  var param = query.split('file=');
  var key = "file";
  var value = param.length > 1 ? param[1] : null;
  params[decodeURIComponent(key)] = decodeURIComponent(value);
  console.info(params);
  return params;
}
```
