### ISSUE TITLE
how i get the actual size of pdf in small viewport device

### ISSUE THREAD

**Issue by isJudy** [mozilla/pdf.js#9086]
pdf.js is so great that i clone it down and developing a web-stamp page.I need to get the actual widt/height to scale my stamp img relatively.

I've search the api and solution over github & stackoverflow (
 
http://jsbin.com/pdfjs-prevnext-v2/edit?html,output 
 
but it told me page is undefined),the pdf.js as well,and failed..It's very kind of to to show me how I get the actual size of the pdf shown.Thank you very much

**Comment by xuych** [comment]
already done,thx

**Comment by aerionTech** [comment]
What did you do to get the correct size?
