### ISSUE TITLE
ocr-ed pdfs from tesseract not searchable.

### ISSUE THREAD

**Issue by metodski** [mozilla/pdf.js#9096]
Attach (recommended) or Link to PDF file here: https://github.com/tesseract-ocr/tesseract/files/947838/2.pdf

Configuration:
- Web browser and its version: Google Chrome Version 61.0.3163.91 (Official Build) (64-bit)
- Operating system and its version:Ubuntu 16.04.3 LTS
- PDF.js version: v1.8.188
- Is a browser extension:yes

Steps to reproduce the problem:

1. Download the attached pdf file (It's a file that has been ocred by tesseract that they use for testing, but it can be reproduced with all ocred from tesseract pdf files).
2. Open http://mozilla.github.io/pdf.js/web/viewer.html
3. Open the downloaded pdf file
4. Search by "components of"

What is the expected behavior? (add screenshot)
"components of" text should be found - first line in the document

What went wrong? (add screenshot)
"components of" text is not found. When inspecting the generated html, each word is split into a new div tag. I'm guessing this is the problem.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
 http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Rob--W** [comment]
The keyword is "tesseract", and this bug may be related to #6863 and/or #6509 .

I received a report from another user about search that fails to work with two words. Spacing between adjacent words appear to disappear.

Here are two examples:
PDF: [9410_005.3B_tesseract.pdf](https://github.com/mozilla/pdf.js/files/1746004/9410_005.3B_tesseract.pdf)
Test case: Open the PDF file, search for "real property".
Expected: the text in the second line should be highlighted.
Actual: Not found (If I search for "realproperty" instead, the text is found).

PDF: [9410_006.3B_tesseract.pdf](https://github.com/mozilla/pdf.js/files/1746005/9410_006.3B_tesseract.pdf)
Test case: Open the PDF file, search for "file timely".
Expected: the text in the first line should be highlighted.
Actual: Not found (If I search for "filetimely" instead, the text is found, but the highlight is incorrect. Maybe bug #6863 ?)

Here is more information from the user:

> they are PDF renderings using ocrmypdf and under the hood tesseract 3/4.  The original tifs are from https://github.com/tesseract-ocr/tesseract/wiki/UNLV-Testing-of-Tesseract.  This issue tried to understand why PDF.js behaves in the way while other viewers get the word boundaries and copy and paste data right:
> 
> https://github.com/jbarlow83/OCRmyPDF/issues/133

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
