### ISSUE TITLE
Unhandled rejection: TypeError:The object does not support the replace

### ISSUE THREAD

**Issue by gonzager** [mozilla/pdf.js#9102]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11.0.9600.18816
- Operating system and its version: Windows 7 64 bits
- PDF.js version: PDF.js v1.9.426 (build: 2558a58d)
- Is a browser extension: no

And I'm using base64 stream, and transcoding(var array = new Uint8Array(new ArrayBuffer(rawLength));)

var base64 = atob("${base64}");

function base64ToUint8Array(base64) {
	var raw = base64; 
	var uint8Array = new Uint8Array(new ArrayBuffer(raw.length));
	for(var i = 0; i < raw.length; i++) {
	uint8Array[i] = raw.charCodeAt(i);
	}
	return uint8Array;
	}

Its works OK IN Chrome  and FF but under IE browser, An error:'Unhandled rejection: TypeError:The object does not support the "replace" property or method'

What went wrong? (add screenshot)

![error](https://user-images.githubusercontent.com/23745713/32390114-eae0b290-c0ab-11e7-8658-a24d9cdf095d.png)

**Comment by timvandermeij** [comment]
It looks like this bug is in the URL polyfill.

**Comment by gonzager** [comment]
I have been investigated but don't find a the solution,
There is some workaround?

**Comment by Snuffleupagus** [comment]
It would be most helpful if you, as requested in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), published a *complete* example online. Please keep in mind that only code snippets aren't that helpful, since it doesn't provide a complete picture of the issue.

**Comment by gonzager** [comment]
Here are a complete example on line with the same pdf used on the demo; https://mozilla.github.io/pdf.js/web/viewer.html  

This example searchs on the back-end the pdf. The back-end returns base64 to the view.
http://186.122.155.132/fd-js/?c=XPQxmJ3MhgpClF1DRcBLdA2 

The view convert base64ToUint8Array and set de DEFAULT_URL = base64ToUint8Array(base64);

I hope you can help me. Thanks.

**Comment by Snuffleupagus** [comment]
It appears that you've attempted to put a `Uint8array` into the `DEFAULT_URL` constant in the default viewer. That one can *only* hold a `string` containing a URL, which explains why things break; and please note that a `Uint8array` really cannot be considered to be a URL.

For information about how you can (programmatically) open a file in the default viewer, please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file.

Closing as answered.

**Comment by ylg58** [comment]
I changed the official demo 
pdf.js 
row:13764
// According to your url operation.
//url  = encodeURI(url);
url = decodeURI(url);
and changed  the official demo 
viewer.js
row:1996
if (file && JSON.stringify(file).lastIndexOf('file:', 0) === 0)

 can solve this issue
