### ISSUE TITLE
What does PDF.js do?

### ISSUE THREAD

**Issue by gidmeister2** [mozilla/pdf.js#9108]
The site doesn't make clear what PDF.js does.
I'd like to use JavaScript in Edge or Chrome to capture user highlights on PDF files.
Is this something PDF.js does?

**Comment by Snuffleupagus** [comment]
> The site doesn't make clear what PDF.js does.

Quoting from the [README](https://github.com/mozilla/pdf.js#pdfjs) (emphasis mine): "PDF.js is a Portable Document Format (PDF) ***viewer*** that is built with HTML5."
Further down in the same [README](https://github.com/mozilla/pdf.js#online-demo), there's an example of the default viewer; see https://mozilla.github.io/pdf.js/web/viewer.html.

> I'd like to use JavaScript in Edge or Chrome to capture user highlights on PDF files.
> Is this something PDF.js does?

Based on the (limited) information provided, the answer is no. See also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations.

Closing as answered.
