### ISSUE TITLE
Memory issues with print in IE 

### ISSUE THREAD

**Issue by z1500060** [mozilla/pdf.js#9111]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: IE 11 (11.0.9600.18816)
- Operating system and its version: Win7 64
- PDF.js version: v1.10.88 (or DEMO)
- Is a browser extension:

Steps to reproduce the problem:
1. Open  https://mozilla.github.io/pdf.js/web/viewer.html  in IE
2. Click Print

What is the expected behavior? (add screenshot)
Print PDF
What went wrong? (add screenshot)
memory shoots up to 400MB (and done print)  
if more pages PDF file (maybe 60?)  memory shoots up to 1GB (print_progress_percent will hidden and print didn't work)
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
