### ISSUE TITLE
PDF IN READ-ONLY MODE

### ISSUE THREAD

**Issue by legreco** [mozilla/pdf.js#9113]
Hello,
is it possible to show pdf in read-only mode?

**Comment by yurydelendik** [comment]
PDF.js demo viewer does not allow to change the PDF. I guess it's a "read-only mode". Closing as answered.

**Comment by legreco** [comment]
Sorry, i just realize that i used the wrong term to express my thougth.
I want to share a  confidential pdf on a intranet website and i want to disable all functionnality allowing copy, printing etc..

**Comment by latuminggi** [comment]
you may try this [pdf.js_readonly](https://github.com/latuminggi/pdf.js_readonly)
here's a bit of its [demonstration](https://latuminggi.github.io/pdf.js_readonly/generic/web/viewer_readonly.html)

**Comment by Ntumane** [comment]
@latuminggi I can't use pdf.js_readonly says:
PDF.js v2.13.5 (build: 41dab8e7b)
Message: Missing PDF "file:///C:/Users/USER/Desktop/pdf.js_readonly-master/mobile-viewer/web/compressed.tracemonkey-pldi-09". Can you help me, I've tried everything I can but it wasn't possible, I've even adjusted the paths, but nothing
