### ISSUE TITLE
customizing when it comes to zooming a specific pdf file in linux

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9114]
<What went wrong? (add screenshot)>
![image](https://user-images.githubusercontent.com/28240330/32609609-90ce0a3a-c5a3-11e7-983c-34d669d2e40c.png)

 When browsing the pdf file using pdf.js viewer, I found out that when it comes to zooming, 
there are the selected options (e.g 50%, 75%, 100%, etc).
how can I zoom in the file while using customized zooming version? (e,g 53% 20%)

<What is the expected behavior?>
 There are no personally customized zooming options
Using the customized option , it would be much helpful for the ones who want to see the pdf file based on what they want to see the slide with the size they need 

`pdf-options`

**Comment by Snuffleupagus** [comment]
If you need a *specific* zoom level, the easiest solution is to append e.g. `#zoom=20` (or whatever value you need) to the URL; please see https://github.com/mozilla/pdf.js/wiki/Viewer-options for additional details.

**Comment by SehyunPark** [comment]
![image](https://user-images.githubusercontent.com/28240330/32614218-23d8081a-c5b0-11e7-9d8c-2001a2bb37a4.png)
Thanks for the reply, and after entering (e.g 17%) in URL, it works.

**Comment by SehyunPark** [comment]
![image](https://user-images.githubusercontent.com/28240330/32614490-bb51a7fa-c5b0-11e7-8894-7cba302ab1f3.png)
and after giving several tries, found out the file is zoomed with the %(up to second decimal place)
(e.g #zoom = 80.50923 -> 80.51%; as shown above)
