### ISSUE TITLE
when run gulp generic,it doesn't generate pdf.js and pdf.worker.js

### ISSUE THREAD

**Issue by jcao07** [mozilla/pdf.js#9115]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. operate follow https://github.com/mozilla/pdf.js
2.when run gulp generic,it doesn't generate pdf.js and pdf.worker.js.
   it generates a directory build/generic/web but not build/generic/build

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by SehyunPark** [comment]
did you check  the build/generic/build/ directory inside? both .js files are in this directory

**Comment by Snuffleupagus** [comment]
Works for me, and without *any* of the requested information provided we won't be able to help.
Are there any error messages printed? If so you need to provide them as well!

Please keep in mind that by default, when running `gulp generic`, the code will be transpiled using Babel. In some environments, e.g. on Windows, that part can take a while (of the order of minutes).
Are you sure that the build step actually finished, before you concluded that it didn't work?

As is, this issue will be closed as incomplete.

**Comment by jcao07** [comment]
Thanks a lot ,according to Snuffleupagus's proposal,I wait for a few minutes and it actually generates the folder build which includes .js.
Thanks again!
