### ISSUE TITLE
adding a video guide link to the READ.ME file

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9117]
https://www.youtube.com/watch?v=TstpR_gGb-4
as a viewer, installing the pdf.js viewer, this video helped me a lot.
I do hope a lot of users who are trying to install mozilla's excellent pdf.js viewer could get a lot of help from watching this video
I'd be really grateful if you could let me use PR for appending the video link in READ.ME  file :), thank you all :)

**Comment by Snuffleupagus** [comment]
In general, I don't think it's a good idea to include a link to a third-party resource (that we have no control over) in the README, since we have no way of keeping such resources up to date (nor fix any potential errors).

Closing as answered.

**Comment by SehyunPark** [comment]
I didn't know that was a third-party resource, sorry for my misunderstanding.
I do agree with the infringing copyrights, I'll keep this mind to it.
