### ISSUE TITLE
Question: What is new in 2.0?

### ISSUE THREAD

**Issue by aaronshaf** [mozilla/pdf.js#9119]
I see a commit (7fbc9dbdc337e5f5c8dd1dc8fa15ef3a81958426) with the major version bump, but it's not clear why it would be needed. Thanks!

**Comment by yurydelendik** [comment]
Please follow the project planning at https://github.com/mozilla/pdf.js/projects/5. Closing as answered.

**Comment by wlipa** [comment]
I have looked at that, and there is a lot of bug tracking and other stuff there.  However, what would be great is a high level description (like one paragraph) that talks about what the main goals / benefits / changes of 2.0 are.  Does that exist anywhere?

**Comment by timvandermeij** [comment]
Not yet, that would be part of writing the migration guide in https://github.com/mozilla/pdf.js/projects/5.

**Comment by jampy** [comment]
Half a year later - is now such a description somewhere?
