### ISSUE TITLE
Support using WebGL on IE11, Edge

### ISSUE THREAD

**Issue by dmichon-msft** [mozilla/pdf.js#9121]
IE11 and Edge both support WebGL, but expose the context as `'experimental-webgl'` rather than `'webgl'`. If one were to modify `generateGL()` from:
```
currentGL = currentCanvas.getContext('webgl', { premultipliedalpha: false });
```
to
```
var options = { premultipliedalpha: false };
currentGL = currentCanvas.getContext('webgl', options) || currentCanvas.getContext('experimental-webgl', options);
```
then PDF.js will also be able to leverage WebGL on IE11 and Edge.

**Comment by Snuffleupagus** [comment]
Please note that we, as a general rule, don't allow browser-specific compatibility hacks in the main code. Such code needs to be placed in https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js.

Also, keep in mind that WebGL is *not* enabled by default (see e.g. https://github.com/mozilla/pdf.js/issues/5161#issuecomment-109593055), and that even when enabled it's currently only used to speed up a couple of rendering operations.

**Comment by AforAnonymous** [comment]
@dmichon-msft will you and/or MSFT originate an appropriate pull request?

**Comment by Snuffleupagus** [comment]
> 'experimental-webgl'

Given that this kind of prefixing (be it vendor or otherwise) has turned out to actually *hurt* the Web, see e.g. the note at the top of https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix:
> Browser vendors are working to stop using vendor prefixes for experimental features. Web developers have been using them on production Web sites, despite their experimental nature. This has made it more difficult for browser vendors to ensure compatibility and to work on new features; it's also been harmful to smaller browsers who wind up forced to add other browsers' prefixes in order to load popular web sites.
>
> Lately, the trend is to add experimental features behind user-controlled flags or preferences, and to create smaller specifications which can reach a stable state much more quickly.

I really don't think it's a good idea to, at this point in time, add support for anything other than "proper" WebGL implementations; hence I'd suggest to WONTFIX this issue. /cc @timvandermeij

**Comment by timvandermeij** [comment]
I agree. We have #5161 open for tracking regular WebGL support.
