### ISSUE TITLE
Printing relatively smaller page makes it shift to top left instead of centre and other scaling issues with large pdfs

### ISSUE THREAD

**Issue by prophet1996** [mozilla/pdf.js#9123]
Attach (recommended) or Link to PDF file here:
https://nofile.io/f/63J7PtR6eFw/thealgodesignmanual.pdf
Configuration:
- Chrome
- Ubuntu 16.04
- PDF.js 1.9.426:

Steps to reproduce the problem:
1. A PDF with cover page relatively smaller in size or scale
2.Print 

What is the expected behavior? 
Position in centre by default.

What went wrong? 
![screenshot from 2017-11-12 00-40-27](https://user-images.githubusercontent.com/16836510/32692686-a541abc0-c742-11e7-8715-0cded54d659e.png)
![screenshot from 2017-11-12 00-40-22](https://user-images.githubusercontent.com/16836510/32692687-a9bf621e-c742-11e7-9cb4-11b499179c1a.png)

![screenshot from 2017-11-12 00-48-26](https://user-images.githubusercontent.com/16836510/32692741-a1260666-c743-11e7-93ac-91c304a29ace.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since the file is no longer available.
