### ISSUE TITLE
Cannot view pdf from citeseerx.ist.psu.edu 1st time

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#9128]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome Version 64.0.3266.0 (Official Build) canary (64-bit)
- Operating system and its version: Win 10 10.0.1.16299
- PDF.js version: 1.10.92, 1.8.557
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Click a pdf link from citeseerx, e.g. http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.6352&rep=rep1&type=pdf
2.

What is the expected behavior? (add screenshot)
pdf should open the 1st time

What went wrong? (add screenshot)
Error:
Invalid or corrupted PDF file.
PDF.js v1.10.92 (build: 1294247)
Message: Invalid PDF structure

pdf opens if a refresh is hit

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
I tried and the PDF is cut off after 24576 bytes. IMHO this is a broken web server.

**Comment by qwer1304** [comment]
> I tried and the PDF is cut off after 24576 bytes. IMHO this is a broken web server.

Except that it's all fine in e.g. Edge and in Chrome w/o pdf.js

**Comment by qwer1304** [comment]
> I tried and the PDF is cut off after 24576 bytes. IMHO this is a broken web server.
Except that it's all fine in e.g. Edge and Chrome w/o pdf.js.

**Comment by THausherr** [comment]
My problem was with firefox. But I just tried again and this time it worked. (maybe because I just updated to FF57 ?)

**Comment by qwer1304** [comment]
> My problem was with firefox. But I just tried again and this time it worked. (maybe because I just updated to FF57 ?)

The error manifests itself **every** time I try.

**Comment by dorasun** [comment]
I just attempted to recreate this problem with Chrome 65.0.3325.162, MacOS 10.12.5, and I had the same thing happen to me with the browser extension:
<img width="1280" alt="screen shot 2018-03-20 at 6 43 33 pm" src="https://user-images.githubusercontent.com/10905385/37686758-23e5661a-2c6f-11e8-8ba3-ec7a5b5583e3.png">

Despite the error saying invalid or corrupted PDF file, I was able to close the error and still download the PDF, and it opened up fine with the web viewer. I recreated the problem again and hit the More Information button and got the following: 
<img width="1280" alt="screen shot 2018-03-20 at 6 48 58 pm" src="https://user-images.githubusercontent.com/10905385/37686844-872a3f70-2c6f-11e8-990f-2d2684268cd6.png">

As mentioned in the initial report, the PDF opened properly after I hit refresh, sometimes requiring a few refreshes.

**Comment by timvandermeij** [comment]
If I click the PDF link (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.6352&rep=rep1&type=pdf) it works all the time for me in Firefox. The link provided in the original post does look broken, because http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.58.6352 gave me unknown URL, download limit exceeded and the actual page as responses on random refreshes. This really does look like a server-side problem and not something PDF.js-related.

**Comment by dorasun** [comment]
After you mentioned the random refreshes, I tried refreshing more and got a different error: 
<img width="1279" alt="screen shot 2018-03-20 at 7 34 15 pm" src="https://user-images.githubusercontent.com/10905385/37688345-fad585be-2c75-11e8-9855-bbe155740dcf.png">

so you may be right about the server-side problem.

**Comment by timvandermeij** [comment]
Thank you for verifying that. In short, Im not seeing anything in this issue that is actionable for PDF.js, so I'm closing it as invalid.
