### ISSUE TITLE
How to Display Microsoft Reporting (.rdlc) in pdf.js using MVC

### ISSUE THREAD

**Issue by rizwan123456** [mozilla/pdf.js#9135]
Hi to all,

I create a mvc application but i want to use old (.rdlc) file in my application using mozila pdf.js.  but i am not able to show (.rdlc) report to pdf.js.

**Comment by Snuffleupagus** [comment]
PDF.js is, as the name suggests, a *PDF viewer*; support for other file formats is explicitly out of scope.

**Comment by rizwan123456** [comment]
Hurray!

I do it, 

i explain all off you for your info and help. first i export (.rdlc) to pdf format using following code then i show converted pdf to mozila pdf.js viewer.

LocalReport report = new LocalReport();
                    report.ReportPath = System.Web.HttpContext.Current.Server.MapPath("~/") + "App_Data//" + strReportName;
                    ReportDataSource rds = new ReportDataSource();
                    rds.Name = "DataSet1";//This refers to the dataset name in the RDLC file
                    rds.Value = GetStudents();//EmployeeRepository.GetAllEmployees();
                    
                    ReportParameter prmFromDate = new ReportParameter("FromDate", strFromDate);
                    ReportParameter prmToDate = new ReportParameter("ToDate", strToDate);
                    ReportParameter rptCurrentDate = new ReportParameter("SystemDate", DateTime.Now.ToString());
                    report.SetParameters(new ReportParameter[] { prmFromDate, prmToDate, rptCurrentDate});
                    report.DataSources.Add(rds);                   

                    Warning[] warnings;
                    string[] streamids;
                    string mimeType;
                    string encoding;
                    string extension;

                    byte[] bytes = report.Render("PDF", null, out mimeType, out encoding, out extension, out streamids, out warnings);
                    using (FileStream stream =System.IO.File.OpenWrite(Path.GetTempFileName()))
                    {
                        stream.Write(bytes, 0, bytes.Length);
                    }

                    Response.Buffer = true;
                    Response.Clear();
                    Response.ContentType = mimeType;
                    Response.AddHeader("content-disposition", "attachment; filename=" + "abc" + "." + extension);
                    Response.BinaryWrite(bytes); // create the file
                    Response.Flush(); // send it to the client to download 

Thank,

**Comment by Snuffleupagus** [comment]
The code in https://github.com/mozilla/pdf.js/issues/9135#issuecomment-344574955 doesn't seem to have anything to do with PDF.js, and please understand that we cannot provide support for other i.e. the non-PDF.js parts, of your application.

Also, as mentioned in both https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, for issues with custom implementations of PDF.js you need to provide a link to the complete implementation (since only code snippets aren't that useful).
