### ISSUE TITLE
Text in Pdf File is Not Visible

### ISSUE THREAD

**Issue by drweb86-work** [mozilla/pdf.js#9137]
Hello

Upon converting file
[file_from.docx](https://github.com/mozilla/pdf.js/files/1474738/file_from.docx)
to pdf with UseOffice
[file_to.pdf](https://github.com/mozilla/pdf.js/files/1474739/file_to.pdf)
I'm seeing nothing when using Pdf.Js as viewer instead of text
![nothing at viewer](https://user-images.githubusercontent.com/29063147/32837142-6d1556f6-ca1d-11e7-99ee-02c1b08309b8.png)

**Comment by Snuffleupagus** [comment]
WFM, when opening that file with https://mozilla.github.io/pdf.js/web/viewer.html.

From the screen-shot, this appears to be a custom PDF.js implementation. However, since most of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is missing, it's difficult to help here.
Please provide all of the requested information, and if this issue is limited to a custom implementation you'll need to provide a *working* example.

**Comment by drweb86-work** [comment]
Hello

Web browser and its version: Chrome 61.0.3163.100 (Official Build) (64-bit)
Operating system and its version: Windows 10
PDF.js version: pdfjs-dist 1.10.97

**Comment by Snuffleupagus** [comment]
Please try opening your file with the default viewer available at https://mozilla.github.io/pdf.js/web/viewer.html (using the "Open file" button on the right-hand side of the toolbar); does it render correctly there?

Again, based on your screen-shot, if this is *only* an issue with a custom PDF.js implementation, you'll need to provide access to it (as requested in both https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).

**Comment by Snuffleupagus** [comment]
> Warning: Error during font loading: this._map[charCode].charCodeAt is not a function

Based on this edit, the issue seems to be that you're using some library that adds properties to Arrays (or maybe Objects) in an *incorrect* way.
Please refer to the discussion in issues such as #7064, #8495, #8711, of which is is thus a duplicate.

**Comment by drweb86-work** [comment]
Hi
I manged to fix this issue

The problem was that pdf.js does not render pdf by itself (!). There was a file app.worker.js which was needed to be added (!!!)

https://github.com/mozilla/pdf.js/issues/7612

I followed instructions of  wojtekmaj  and it started working!
