### ISSUE TITLE
PDF if not showing in the viewr

### ISSUE THREAD

**Issue by sriharikallam** [mozilla/pdf.js#9141]
Hi,
I am using pdf.js to display my pdf files. but the pdf is not displaying in the viewer. but able to print and download the pdf and was able to view in presentation mode also. here is the reference URL
http://nendrasys.com.au/ktw/Spares/spareparts.html

The issue occurring on windows in all browsers (Chrome, FF & IE)

Can anyone help me what went wrong in my development.

Thanks
Srihari

![image](https://user-images.githubusercontent.com/33717972/32888875-c9fe27f4-caee-11e7-90c1-c8f625d3c325.png) - Normal View (pdf is not showing)

![image](https://user-images.githubusercontent.com/33717972/32888863-bf839b42-caee-11e7-9c54-9ae46ab7d7b1.png) - Presentation view (able to view pdf)

**Comment by sriharikallam** [comment]
![image](https://user-images.githubusercontent.com/33717972/32888802-86b4ef14-caee-11e7-950a-0013f2b4730f.png) - normal view

![image](https://user-images.githubusercontent.com/33717972/32888814-8f97b0da-caee-11e7-87f7-ab738c315586.png) - Presentation view

**Comment by timvandermeij** [comment]
It gives the fallback bar with "Missing PDF file http://nendrasys.com.au/ktw/Spares/test.pdf" for me. Indeed, that link does not exist. Therefore, this really looks like a custom integration problem. Can you open the file with https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by timvandermeij** [comment]
The link is changed by the owner. The PDF displays just fine now. Because it does and it's a different PDF file than shown in the image above, I'm closing this as fixed.
