### ISSUE TITLE
Display pdf as byte-array

### ISSUE THREAD

**Issue by abrasat** [mozilla/pdf.js#9142]
Is it possible to display a pdf from a byte-array in memory, instead from a Uri ?

**Comment by timvandermeij** [comment]
Yes, refer to https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html for example.

**Comment by ekjuanrejon** [comment]
I was following the example and pdfjs rendered a png instead of a pdf... any ideas?
