### ISSUE TITLE
PDF.js Chrome extension does not send cookies

### ISSUE THREAD

**Issue by PandaWhisperer** [mozilla/pdf.js#9143]
## Background

I'm working on an app that dynamically renders PDF documents. When requesting such a document, the server checks the submitted cookie to ensure that an authorized user is logged in. This works when using Chrome's built-in PDF viewer, however, when using PDF.js, an empty document is displayed, with a red error bar showing a `401 Unauthorized` error.

This appears to be caused by the PDF.js extension not sending any cookies when requesting the document (see details below).

## Expected Behavior

Any cookies for the requested URL are sent as if Chrome was requesting the page.

## Actual Behavior

No cookies are sent.

## Detailed Analyis

When inspecting the PDF requests in the Web Inspector, I noticed that PDF.js does not send any cookies with the request. Chrome's built-in PDF viewer, however, does, as does PDF.js in Firefox (see screenshots below).

### Chrome PDF viewer (built-in)

<img width="778" alt="screen shot 2017-11-16 at 11 40 01 am" src="https://user-images.githubusercontent.com/749244/32912098-e4c0d1e4-cac2-11e7-8195-90c1d07c03ad.png">

### PDF.js Chrome extension

<img width="778" alt="screen shot 2017-11-16 at 10 49 50 am" src="https://user-images.githubusercontent.com/749244/32911295-9d7b5306-cac0-11e7-9ddd-b754abd2bbc4.png">

### PDF.js Firefox

<img width="779" alt="screen shot 2017-11-16 at 11 31 27 am" src="https://user-images.githubusercontent.com/749244/32911925-7b962426-cac2-11e7-84de-10f1f4b2069b.png">

## Version Information

This behavior was observed using the following versions:

- Chrome Version 62.0.3202.89
- Firefox Version 57.0
- PDF.js Version 1.8.557 (Chrome)

**Comment by Rob--W** [comment]
Fixed by #9541. I wish that I had seen this report earlier.
