### ISSUE TITLE
omitted Space bar key in the Keyboard Shortcut section 

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9148]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions
(in the Keyboard Shortcut section, 

**question) What are the PDF.js keyboard shortcuts?
next page: n, j, right arrow key, click in presentation mode**
(upon several attempts opening the pdf file, I found out after entering space bar key, it also works the same function (moving to the next page) as entering other keys (n,j,right arrow key)

I want to insert space bar key in the sentence, would you please give me the permission to edit the file?

**Comment by Snuffleupagus** [comment]
> I want to insert space bar key in the sentence, would you please give me the permission to edit the file?

Unfortunately we cannot give you edit permissions, since we were forced to limit editing to people with commit access because of a high amount of spam in the Wiki.

Closing, since I've edited the relevant section of the Wiki now; thank you!
