### ISSUE TITLE
editing Frequently-Asked-Questions section

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9149]
You can use raw binary data to open a PDF document: use Uint8Array instead of URL in PDFViewerApplication.open call or the DEFAULT_URL variable value. If you have base64 encoded data, please decode it first -- not all browsers have atob or data URI scheme support. (The base64 conversion operation uses more memory, **so we recommend to deliver raw PDF data as typed array in first place.**)

 First, you need to prepare your fork and setup the development environment. Don't forget to read the Contributing page. Second, make yourself familiar with the PDF format and PDF.js internals. Third, if you don't already have a certain issue you want to fix, choose one from the open issues labeled 5-good-beginner-bug. Last, submit a pull request for the review. During any part of the process **we recommend to communicate with the PDF.js team on #pdfjs IRC channel at irc.mozilla.org** if you have questions or need to find a reviewer.

**_

> two bold parts of "recommend to ~" needs to be fixed to "recommend ~ing" in a grammatical order.

_**
Since this FAQ section is widely used among users throughout the world, I want to make it this part clear.
:)

**Comment by Snuffleupagus** [comment]
Closing as fixed; thank you!
