### ISSUE TITLE
/PageMode /FullScreen not honored by latest released version

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#9159]
This issue is related to #8657 (I wonder whether it might be a regression).

Here you have an [uncompressed PDF document](http://pdf.ousia.tk/full-screen.pdf), which contains the following object:

```
19 0 obj
<</Type/Catalog/Pages 11 0 R /Metadata 12 0 R /PageLabels << /Nums [ 0 << /S /D /St 0 >> ] >> /PageMode /FullScreen /Version /1.7>>
endobj
```

But pdf.js doesn’t display the document at fullscreen.

I’m on Fedora 25 (32bit), using Firefox Quantum 57.0. From [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1398347), I guess that pdf.js version is latest released version.

**Comment by Snuffleupagus** [comment]
Please refer to https://github.com/mozilla/pdf.js/pull/8673/files#diff-529d1853ee1bba753a0fcb40ea778723R2309.

Closing as answered.

**Comment by ousia** [comment]
Here is the text for reference:

    + * Converts API PageMode values to the format used by `PDFSidebar`.
    + * NOTE: There's also a "FullScreen" parameter which is not possible to support,
    + *       since the Fullscreen API used in browsers requires that entering
    + *       fullscreen mode only occurs as a result of a user-initiated event.

I didn’t know that. I wonder how Flash presentations (http://www.free-culture.tk, to name one) can start at full screen.

In any case, how about showing a message to the user that the document is intended to be displayed at full screen?
