### ISSUE TITLE
 PDFJS.DefaultAnnotationLayerFactory is not a constructor

### ISSUE THREAD

**Issue by SamerShahin** [mozilla/pdf.js#9160]
Configuration:
- Web browser and its version: chrome - latest (62)
- Operating system and its version:  W10
- PDF.js version: 1.9.426
- Is a browser extension: no 

Hello Everyone ,
i am using the pre-build version which i downloaded from this location : http://mozilla.github.io/pdf.js/getting_started/

I am trying to render a single page view with annotation layer . but i am getting the following error :  
PDFJS.DefaultAnnotationLayerFactory is not a constructor
the scripts that i am loading are ": 
1. pdfjs-dist/build/pdf.js
2.pdfjs-dist/web/viewer.js (note there is no pdf_viewer.js in the pre build version)
3.pdfjs-dist/build/pdf.worker.js

i was able to run the examples that is provided in the full source , and it works currectly . but i  want to use the pre-build version ,because it's smaller in size and more efficient.

What am i doing wrong ? should i just use the full source version ? is there other ways to render the annotationLayer?

many thanks
 

sniplet of the code : 
`var container = document.getElementById('pageContainer');
PDFJS.getDocument(DEFAULT_URL).then(function (pdfDocument) {
  // Document loaded, retrieving the page.
  return pdfDocument.getPage(PAGE_TO_VIEW).then(function (pdfPage) {
    // Creating the page view with default parameters.
    var pdfPageView = new PDFJS.PDFPageView({
      container: container,
      id: PAGE_TO_VIEW,
      scale: SCALE,
      defaultViewport: pdfPage.getViewport(SCALE),
      // We can enable text/annotations layers, if needed
      annotationLayerFactory: new PDFJS.DefaultAnnotationLayerFactory()
    });
    // Associates the actual page with the view, and drawing it
    return pdfPageView.draw();
  });
});
`

**Comment by SamerShahin** [comment]
any updates on the subject? thanks

**Comment by Snuffleupagus** [comment]
> i am using the pre-build version which i downloaded from this location : http://mozilla.github.io/pdf.js/getting_started/

As mentioned there, "Pre-built - Includes the generic build of PDF.js and the viewer." that download doesn't contain the viewer components that you're apparently attempting to access here.

> .pdfjs-dist/web/viewer.js (note there is no pdf_viewer.js in the pre build version)

The viewer components are provided pre-built in https://github.com/mozilla/pdfjs-dist (or can be build from source using `gulp components`), where the `pdf_viewer.js` file is present in the `/web` folder.

So, for building your own (components based) viewer, https://github.com/mozilla/pdfjs-dist is the correct source. Note that it's also usable with e.g. NPM, see https://www.npmjs.com/package/pdfjs-dist.

Closing as answered.
