### ISSUE TITLE
some fonts  not support 

### ISSUE THREAD

**Issue by jiuyuehe** [mozilla/pdf.js#9161]
I'm test a pdf 

the font is  ```楷体_gb2312```   or   ```仿宋_gb2312```  show  gibberish

like 
![image](https://user-images.githubusercontent.com/4385903/33000166-6516d160-cde1-11e7-8c50-290a971244c9.png)

the right is :  
![image](https://user-images.githubusercontent.com/4385903/33000176-7a1fe86c-cde1-11e7-889e-2cb1c7975e59.png)

but the explor is  right 

![image](https://user-images.githubusercontent.com/4385903/33000222-b70c0bfc-cde1-11e7-9516-7e7442986649.png)

who to do it ?

#

Configuration:

browser : all support browser;
Operating system and its version: win7  ,win 10
PDF.js version: all versjion
Is a browser extension: no

**Comment by SehyunPark** [comment]
you're talking Chinese character is turning into weird ones?

**Comment by Snuffleupagus** [comment]
As it stands, this issue is missing *all* of the required information in order to be actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by jiuyuehe** [comment]
@SehyunPark  yes

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since we cannot help if the problematic PDF file isn't attached to the issue.

**Comment by Thj007** [comment]
hello, are you solve your issue?
