### ISSUE TITLE
Subject & Keywords

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9163]
Attach (recommended) or Link to PDF file here:
[1.pdf](https://github.com/mozilla/pdf.js/files/1487878/1.pdf)

Configuration:
- Web browser and its version: Mozilla firefox
- Operating system and its version: Ubuntu Linux 16.04.2 LTS
- PDF.js version: the latest version
- Is a browser extension: yes

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/28240330/33022045-1f2034ce-ce47-11e7-8b65-2155c8bdc14b.png)

--> There's no keywords and subjects (all those two lines are empty)

What is the expected behavior? (add screenshot)
--> I want to know the real function of 'keywords' and 'subjects'
and I'm curious if those two parts are truly customized on entering any words by us users, /
or if those are totally determined by the author (which those have authorized access).

Kind explanation are truly grateful for me. Thank you.

**Comment by Snuffleupagus** [comment]
> There's no keywords and subjects (all those two lines are empty)

This information is fetched from the `Info` dictionary of the PDF file *itself*, and in that particular file that information isn't provided. You can open the file with http://brendandahl.github.io/pdf.js.utils/browser/, which is a tool that allow you to explore the structure/contents of PDF files.

Also, please refer to the [PDF specification](http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf) for further details on the PDF format in general. And in this particular case: http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#M13.9.24061.1Heading.82.Info.Dictionaries.

> or if those are totally determined by the author (which those have authorized access).

Yes, this information is provided (or not) by the person/software that create the PDF file.

Closing as answered.
