### ISSUE TITLE
modified time / creation time

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9165]
upon seeing the document properties from the pdf file, I found out this one:

![image](https://user-images.githubusercontent.com/28240330/33023170-a5b62b80-ce4a-11e7-99f5-a40f26e0bf11.png)

modification **_date_** and creation **_date_** are ranging from second measurement up to year measurement

but I found out that according to Cambridge Dictionary, date only includes the day of the month, not the second

<url: https://dictionary.cambridge.org/dictionary/english/date>

(screenshot)

![image](https://user-images.githubusercontent.com/28240330/33023305-0a83afce-ce4b-11e7-8a9c-c56df6ad4454.png)

### ## what I suggest to the contributors and workers is changing **_date_** into **_time_** 
(which time includes the second up to year scale)

after going into l10 folder's en-US folder, opening viewer.properties file:
<url: https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/viewer.properties>

among many codes, I found out these two code lines:

![image](https://user-images.githubusercontent.com/28240330/33023433-7ca1d982-ce4b-11e7-9540-00602fc20466.png)

### what I suggest is to change Creation Date into Creation Time / Modification Date into Modified Time

(I know Adobe Flash Player uses Creation Date & Modification Date, but as I wrote, I'm quite certain that these words are wrong!, and I'm pretty sure Mozilla's pdf.js viewer is more effective than Adobe Flash viewer so I think we should solve this problem :) 
and I'm pretty sure Mozilla's pdf.js viewer is more effective so I think we should solve this problem :) )

If you think this needs to be fixed, hope this could be fixed or to be allowed the code lines' words should be fixed
(the variation and struct.name need to be renamed accordingly)

I want to know you guys' opinion

**Comment by Snuffleupagus** [comment]
Please keep in mind that localizers are free to translate those strings as they see fit, for a given locale.

Note that updating the string names would invalidate *every single* existing translation, thus forcing the localizers to re-translate those entries (even if the meaning doesn't even change in a particular locale).
Hence it seems, at least to me, that in this particular case it's not really worth it to change this, given that the change would be minor and the work required significant.
