### ISSUE TITLE
DataCloneError: Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by uuggene** [mozilla/pdf.js#9166]
This issue is reproduced in Angular2+ application with PDF.JS.
Here's the link where you can reproduce it.
https://github.com/VadimDez/ng2-pdf-viewer

Only one step to reproduce:
set url for non-existing pdf (which returns 404 Not found)

Here's error message:
> ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': function (delegate, current, target, task, applyThis, applyArgs) {
>             try {
>                 onEnter(zo...<omitted>... } could not be cloned.
> Error: Failed to execute 'postMessage' on 'Worker': function (delegate, current, target, task, applyThis, applyArgs) {
>             try {
>                 onEnter(zo...<omitted>... } could not be cloned.
>     at MessageHandler.postMessage (util.js:1620)
>     at sendStreamRequest (util.js:1450)
>     at Object.error (util.js:1484)
>     at eval (api.js:1629)
>     at ZoneDelegate.invoke (zone.js:392)
>     at Object.onInvoke (ng_zone.ts:296)
>     at ZoneDelegate.invoke (zone.js:391)
>     at Zone.run (zone.js:142)
>     at zone.js:873
>     at ZoneDelegate.invokeTask (zone.js:425)
>     at MessageHandler.postMessage (util.js:1620)
>     at sendStreamRequest (util.js:1450)
>     at Object.error (util.js:1484)
>     at eval (api.js:1629)
>     at ZoneDelegate.invoke (zone.js:392)
>     at Object.onInvoke (ng_zone.ts:296)
>     at ZoneDelegate.invoke (zone.js:391)
>     at Zone.run (zone.js:142)
>     at zone.js:873
>     at ZoneDelegate.invokeTask (zone.js:425)
>     at resolvePromise (zone.js:824)
>     at zone.js:876
>     at ZoneDelegate.invokeTask (zone.js:425)
>     at Object.onInvokeTask (ng_zone.ts:288)
>     at ZoneDelegate.invokeTask (zone.js:424)
>     at Zone.runTask (zone.js:192)
>     at drainMicroTaskQueue (zone.js:602)
>     at ZoneTask.invokeTask [as invoke] (zone.js:503)
>     at invokeTask (zone.js:1540)
>     at XMLHttpRequest.globalZoneAwareCallback (zone.js:1566)

Because of NgZone, one new property '__zone_symbol__currentTask' has been added, and it tries to serialize this property to send the message.
![missingpdfexception](https://user-images.githubusercontent.com/11631048/33029111-6af11b38-ce20-11e7-81eb-b45002c6ec5e.png)

Here's release when it started failing:
https://github.com/mozilla/pdfjs-dist/commit/f8b6be139338c324a669da0cc003270a6ea4a79f
And these changes cause error above:
https://github.com/mozilla/pdf.js/commit/343b4dc2b61c88f9b549f212b5d91a8b7acd4209

**Comment by timvandermeij** [comment]
I'm not really seeing how PDF.js is at fault here. It looks like Angular is injecting a non-serializable property in an otherwise serializable message, so I think you should find out why Angular is doing that instead.

**Comment by uuggene** [comment]
I created pull request that I think solves the problem.
https://github.com/mozilla/pdf.js/pull/9175
Sorry, If I did something wrong, this is my first pull request in github.

**Comment by snovos** [comment]
@uuggene  Was your commit merged? Im having same issue, and this error is not handled by onError handler(. Please keep me posted.

**Comment by Snuffleupagus** [comment]
Closing, since this should be fixed in Angular now; see https://github.com/angular/zone.js/pull/980.
