### ISSUE TITLE
Selection flickering reduction - overkill?

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#9168]
I found that PDF.js viewer prevents selection flickering by creating additional `<div>` called endOfContent and expanding it dynamically on mouse down.

I have found out that flickering can be equally well prevented by adding `pointer-events: none` to textContent and `pointer-events: all` to textContent's children.

I played around and found out that it makes absolutely no difference on Firefox (still perfect), as well as on other browsers (still broken).

Here's my branch...
https://github.com/wojtekmaj/pdf.js/tree/change/pointer-events-instead-of-endOfContent

So, am I missing something?

**Comment by yurydelendik** [comment]
@wojtekmaj did you try to use "enhanceTextSelection" preference instead?

**Comment by yurydelendik** [comment]
> I have found out that flickering can be equally well prevented by adding pointer-events: none to textContent and pointer-events: all to textContent's children.

I don't see how https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events helps based on its documentation. We don't use or handle any events from text. Can you provide more insights?

**Comment by wojtekmaj** [comment]
I was surprised too, but it was the first thing that came to my mind. You can check out my implementation here:

http://projekty.wojtekmaj.pl/react-pdf/

As you can see, without endOfContent, selection does not jump. You can also try default PDF.js file on it and it also does not jump. However, as soon as you disable pointer-events CSS-es on textContent and all its children (one-liner: `[...document.querySelectorAll('.ReactPDF__Page__textContent, .ReactPDF__Page__textContent > div')].forEach(el => el.style.pointerEvents = null)`), the selection starts to jump.


Here's how I think it works:

1. Normally, when selecting text, if you see these layers **from the side**, it'd look like this.

```
  text text text    text text text         texttext
paperpaperpaperpaperpaperpaperpaperpaperpaperpaperpaper
^ A                 ^B            ^C              ^ D
```

If you want to select lines between B and D, and you start to drag your mouse:
1. First, you drag over text. Nothing unusual happens.
2. Then, in point C, you start dragging over the "paper". As "paper" itself has no text, for selection algorithm it's just a single point somewhere. It's the point A. So selection flickers and now text from C to A is selected.
3. Then, you hover over point D. The browser again knows the specific points in text between which the selection shall be made.

So, to fix that, I'm applying `pointer-events: none` to the "paper". As a result, again the same situation:
1. First, you drag over text. Nothing unusual happens.
2. Then, in point C, you start dragging over the "paper". This time pointer events, including dragging with mouse, is turned off. So, the browser thinks "huh, nothing here. I guess I'll just keep text from B to C selected".
3. Then, you hover over point D. Text selection continues.

I can't see it working on PDF.js viewer at the moment, something else must be causing selection issues as well or I'm missing something, but it *is* an interesting find, I think.

**Comment by wojtekmaj** [comment]
Found it! This comment will have a full script in a minute.

**Comment by wojtekmaj** [comment]
Found it!

1. Run https://mozilla.github.io/pdf.js/web/viewer.html
2. In the console, run:
    ```
    [...document.querySelectorAll('.textLayer')].forEach(el => { el.style.pointerEvents = 'none'; el.style.overflow = 'unset' });
    [...document.querySelectorAll('.textLayer div')].forEach(el => el.style.pointerEvents = 'all');
    [...document.querySelectorAll('.endOfContent')].forEach(el => el.parentElement.removeChild(el))
    ```
3. Try selecting text. Still works!

**Comment by maxoizs** [comment]
@timvandermeij would this [Fix ](https://stackoverflow.com/questions/22875167/prevent-text-selection-from-jumping-to-top-when-dragging-over-whitespace-in-pd) help you with white space flickering issue

**Comment by Snuffleupagus** [comment]
Based on the discussion, see e.g. https://github.com/mozilla/pdf.js/issues/9168#issuecomment-345864530, it's not entirely clear that we'd want to make the changes suggested here; hence closing as WONTFIX for now.

**Comment by Mvsvh** [comment]
Hi all,

have been looking for a solution for a long time. @wojtekmaj Thanks for writing down the detailed explanation of the situation, this gave me the idea for the following: What finally fixed it for me is the following simple solution. 

```
.textLayer span,
.textLayer br {
  min-height: 1000px;
  // ...
}
```

As long as you don't need the precise dimensions of the text layer rendered, there shouldn't be a problem. 

Hope that helps some of you as well.

<img width="292" alt="image" src="https://github.com/mozilla/pdf.js/assets/19476943/d2f9850e-6985-4a39-8543-0bb78e869593">

**Comment by xhay1122** [comment]
I found a new solution, which is to set the `user-select` property of `endOfContent` to `text`.

```
.endOfContent {
    ....
    user-select: text;
} 
```
