### ISSUE TITLE
Pdf.js doesn't render any thing with IE10 and IE11, but it works fine in Edge.

### ISSUE THREAD

**Issue by zy4944796** [mozilla/pdf.js#9171]
When I ran my html with IE10 and IE11 ,there was only gray background in the page.Then I tried it with Microsoft Edge ,The "Hello world" pdf was displayed correctly.I have spent all the noon to fix this problem,but unfortunately I failed.Who can help me?
Here is my HelloWorld code : 

[pdf_test.zip](https://github.com/mozilla/pdf.js/files/1491005/pdf_test.zip)

**Comment by Snuffleupagus** [comment]
Given the lack of details regarding *how* you're actually loading that code in the browser, it's difficult to tell from a distance what could be wrong.

> When I ran my html with IE10 and IE11 ,there was only gray background in the page.

Did you by any chance try to access the code using a `file://` URL?
If so, that is a known limitation of certain browsers (such as IE), and the work-around is to use a local server (as is mentioned in https://github.com/mozilla/pdf.js#getting-the-code).

If the above suggestion doesn't help, you'll need to provide a lot more details.
Closing as answered for now.
