### ISSUE TITLE
error occurred after following the link

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9173]
upon opening this file (file url is seen below):
https://github.com/mozilla/pdf.js/blob/master/docs/contents/getting_started/index.md

![image](https://user-images.githubusercontent.com/28240330/33082667-ac716c88-cf20-11e7-9620-af0d96d1278b.png)

neither of  two version keys are not working upon entering each of those keys..

the result page is seen as captured (below):

![image](https://user-images.githubusercontent.com/28240330/33082803-ff60d9ec-cf20-11e7-8ef5-4ea46f3db7d6.png)

**Comment by Snuffleupagus** [comment]
> https://github.com/mozilla/pdf.js/blob/master/docs/contents/getting_started/index.md

That file is the *template* that is used to generate http://mozilla.github.io/pdf.js/getting_started/ at build time. Please refer to the history of that file, in https://github.com/mozilla/pdf.js/commits/master/docs/contents/getting_started/index.md, and you'll find a reference to PR #4585 which introduced the file.

Closing as invalid.

**Comment by SehyunPark** [comment]
didn't know the template and also the reference. I'll check that. Thanks for the explanation
