### ISSUE TITLE
Run viewer.html outside web folder

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#9177]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Closing as incomplete -- not enough details were provided

**Comment by chitgoks** [comment]
So i cannot edit original post in mobile version of this site so i an pasting it here

Is there a way for viewer.html to run outside web folder? I noticed version 1.9.426 does not make this happen anymore

Reason is not to be dependent placing all custom files in the web folder

**Comment by yurydelendik** [comment]
> Is there a way for viewer.html to run outside web folder?

Personally, I don't understand what does it even mean in web application context.

See if https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#gh-pages helps

**Comment by chitgoks** [comment]
Hi yuri. i mean i want to place viewer.html outside the web folder. then just change the path of viewer.js and pdf.js in the code to point it to the correct path.

Before it used to work but now in v1.9.426 it does not

This is the structure i wish to have now

build/
web/
viewer.html

**Comment by yurydelendik** [comment]
If viewer.html and viewer.js is properly modified, that it's possible to "Run viewer.html outside web folder"

**Comment by chitgoks** [comment]
hi yuri ok
ill see what i can do

my purpose is to avoid modifying viewer.js so that there would be no need it to do that for every new pdfjs update in the future

i thought perhaps there is some way to override the paths of the js files used by viewer.js from outside its context

**Comment by chitgoks** [comment]
Solved this using base tag.
