### ISSUE TITLE
What happened to PDFViewerApplication.handTool ?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#9178]
Prior to version 1.9.426 I am able to get the handTool property via

PDFViewerApplication.handTool

but now, it is undefined. I looked at the code in viewer.js and now you call it via 

PDFViewerApplication.pdfCursorTools.handTool

But enterPresentationMode() is now gone. what is the new version's equivalent for this now?

Please advise

**Comment by Snuffleupagus** [comment]
The correct way to switch between cursor tools, is to either:
 - Call https://github.com/mozilla/pdf.js/blob/6f52fafdc0d5476db049e41140a6c82ca84eaaaa/web/pdf_cursor_tools.js#L66, i.e. `PDFViewerApplication.pdfCursorTools.switchTool(/* value here */);`, providing one of the values from https://github.com/mozilla/pdf.js/blob/6f52fafdc0d5476db049e41140a6c82ca84eaaaa/web/pdf_cursor_tools.js#L18
 - Dispatch the `switchcursortool` event on the current `EventBus` instance, i.e. `PDFViewerApplication.eventBus.dispatch('switchcursortool`, { tool: /* value here */ });`

Checking the *currently* active tool is done using https://github.com/mozilla/pdf.js/blob/6f52fafdc0d5476db049e41140a6c82ca84eaaaa/web/pdf_cursor_tools.js#L57, which returns a value from https://github.com/mozilla/pdf.js/blob/6f52fafdc0d5476db049e41140a6c82ca84eaaaa/web/pdf_cursor_tools.js#L18

Closing as answered (and note compared to the API, there's no guarantee regarding interface stability of the default viewer).

**Comment by chitgoks** [comment]
hi snuffle. thank you. i forgot to edit the title. i was actually after enterPresentationMode() but this function does not seem to exist anymore, I looked at the old pdf.js version on what is inside this function and decided to call it manually.
