### ISSUE TITLE
cloudflare Business CDN with pdf.js and Chrome

### ISSUE THREAD

**Issue by sapq** [mozilla/pdf.js#9181]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
google chrome last one 
- Operating system and its version:
windows 7
- PDF.js version:
last one
- Is a browser extension:

Steps to reproduce the problem:
1. i use cloudflare Business CDN the proplem  is File does not open quickly
the link : https://goo.gl/GS3VC5

before Everything works well use cloudflare Free

now it is take like 6 seconds to start open file 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
This loads instantly for me without any delays using Firefox 57. Marking as Chrome-specific for now.

**Comment by Snuffleupagus** [comment]
> i use cloudflare Business CDN the proplem is File does not open quickly
>     the link : https://goo.gl/GS3VC5
> 
> before Everything works well use cloudflare Free

Based on the above, it really sounds like this is a configuration issue with Cloudflare.
Please understand that we cannot provide support CloudflarePlease keep in mind that we cannot provide support for

**Comment by Snuffleupagus** [comment]
> i use cloudflare Business CDN the proplem is File does not open quickly
>     the link : https://goo.gl/GS3VC5
> 
> before Everything works well use cloudflare Free

Based on the above, it does sound like this is a configuration issue with Cloudflare itself (rather than PDF.js).
Please understand that we really cannot provide support for various CDNs, or other hosting services, and that such support queries rather need to be directed at the appropriate vendor.

**Comment by sapq** [comment]
timvandermeij thank you 

yes firefox work good  but the proplem with google chrome

**Comment by sapq** [comment]
i fix this proplem 

i remove the Https and work fast

**Comment by timvandermeij** [comment]
Closing since this does not look like it's related to PDF.js, but rather to Cloudflare/Chrome.
