### ISSUE TITLE
Text selection color is ugly

### ISSUE THREAD

**Issue by fitojb** [mozilla/pdf.js#9184]
I find the text highlight color highly unsatisfactory; it reminds me of Windows 95's default theme. Can we change it to a nicer blue? I recommend #b9eaff or something similar.

**Comment by bansalnitish** [comment]
@timvandermeij I would like to work on this issue. Can you just suggest what color are you looking for ?

**Comment by timvandermeij** [comment]
Let's first talk this over on IRC with `yury` or `bdahl` to see if this is actually something we want to fix. Personally I find the current color just fine.

**Comment by fitojb** [comment]
I won’t be able to use IRC with you guys, but a more permanent medium (such as a GitHub issue _wink_ would be great, as it’s not constrained by timezones and stuff. I bet this will get reworked anyway if you ever implement more Quantum-like visuals.

**Comment by Snuffleupagus** [comment]
> Personally I find the current color just fine.

Agreed, and calling the existing colour "ugly" is highly subjective anyway; closing as WONTFIX?
