### ISSUE TITLE
PDF Search Issue: Not able to search with two words has space  

### ISSUE THREAD

**Issue by nadeermalangadan** [mozilla/pdf.js#9186]
Attach (recommended) or Link to PDF file here:
PDF is [Sample lease contract 26.pdf](https://github.com/mozilla/pdf.js/files/1500985/Sample.lease.contract.26.pdf)

Steps to reproduce the problem:
I am using [https://mozilla.github.io/pdf.js/web/viewer.html](url) to preview pdf by opening the pdf.

now am searching for "**made is**" but its not showing in the pdfjs

and while selecting and copying pdf  text it has no space in b/w words

**Comment by retrazil** [comment]
Searching for 'made' gives results but searching for 'is made' (present on first line of the document after heading) does not give any results. Removing the space between 'is' and 'made', i.e., 'ismade' makes no difference either. 

This issue still seems to persist.

**Comment by shadowboxingskills** [comment]
> Searching for 'made' gives results but searching for 'is made' (present on first line of the document after heading) does not give any results. Removing the space between 'is' and 'made', i.e., 'ismade' makes no difference either.
> 
> This issue still seems to persist.

+1

**Comment by calixteman** [comment]
The string for `is made` is `\u200Bis\u200B \u200Bmade` and `\u200B` is a zero-width space (see https://en.wikipedia.org/wiki/Zero-width_space).
