### ISSUE TITLE
can't render this pdf file correctly in only win7 & chrome

### ISSUE THREAD

**Issue by KimDal-hyeong** [mozilla/pdf.js#9193]
win7 & firefox, win10 & chrome is not problem.
but can't render correctly in win7 & chrome. Only.

Attach (recommended) or Link to PDF file here:
[fail-docu.pdf](https://github.com/mozilla/pdf.js/files/1506196/fail-docu.pdf)

Configuration:
- Web browser and its version: chrome 62.0.3202.94
- Operating system and its version: Window7
- PDF.js version: 1.9
- Is a browser extension: no

Steps to reproduce the problem:
1. open pdf in pdf.js online demo (https://mozilla.github.io/pdf.js/web/viewer.html)

What is the expected behavior? (add screenshot)
<img width="614" alt="2017-11-27 11 31 33" src="https://user-images.githubusercontent.com/16788797/33271892-dd6dd3bc-d3cb-11e7-82d1-871f37cc3f3c.png">

What went wrong? (add screenshot)
<img width="478" alt="default" src="https://user-images.githubusercontent.com/16788797/33271910-e8cbd86c-d3cb-11e7-8e32-fc4af07854ad.PNG">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by KimDal-hyeong** [comment]
I updated IE8 to IE11 and it works fine in Chrome too.
How does this happen?

Does Chrome on Windows 7 use IE's features?

**Comment by yurydelendik** [comment]
Closing as resolved.

> I updated IE8 to IE11 and it works fine in Chrome too.
> How does this happen?

When you update IE, the Windows also updates operating system, drivers, etc. So it's possible that you had non-updated OS.
