### ISSUE TITLE
All characters from attached file are displayed incorrectly insie Firefox browser and plugin

### ISSUE THREAD

**Issue by asmolka** [mozilla/pdf.js#9195]
Attached PDF file here:
[testfile.pdf](https://github.com/mozilla/pdf.js/files/1506940/testfile.pdf)

Configuration:
- Web browser and its version: Firefox 57.0 PL (64-bit)
- Operating system and its version: Windows 10 Fall Creators Update
- PDF.js version: 1.9.583
- Is a browser extension: No

Steps to reproduce the problem:
1. Simply open attached pdf file in browser. 
2. All is displayed wrongly

What is the expected behavior?
The expected behaviour can be observer in any other browser, chrome or edge or standalone PDF viewer.
Screenshot:
![screen good](https://user-images.githubusercontent.com/34038015/33280978-050abe6c-d3a4-11e7-82b9-78f8c86ffa49.png)

What went wrong?
On Firefox it looks like this:
![screen bad](https://user-images.githubusercontent.com/34038015/33281034-28c9b6c8-d3a4-11e7-94e8-fd1c16a6ed9c.png)

**Comment by Snuffleupagus** [comment]
The `ToUnicode` data in the PDF file is malformed, which is why we cannot render the file correctly (applies to *all* fonts in the file). As can be seen in the screen-shot below, taken using http://brendandahl.github.io/pdf.js.utils/browser/, there's `NUL` bytes before *every* single character.

![null-bytes](https://user-images.githubusercontent.com/2692120/33288940-296e222a-d3be-11e7-962a-1b25922dc645.png)

**Comment by msmolka** [comment]
But all other viewers (and browsers opens file correctly)
I've checked Chrome, Opera, Edge. All native viewers like Foxit Reader and Adobe opens file correctly.

The only viewer that has problem with this file is Firefox.

**Comment by asmolka** [comment]
But all other viewers opens the file correctly
I've checked Chrome, Opera, Edge.
Native windows viewers like Foxit Reader or Adobe.

I found that the only issue is on Firefox browser. Nowhere else.

**Comment by Snuffleupagus** [comment]
> But all other viewers opens the file correctly

I'm not sure how that's relevant here, since it doesn't change the fact that the PDF file is corrupt and that other readers have had to implement ways of dealing with such data.

**Comment by asmolka** [comment]
This relevant in the way, that if Firefox wants to compete with other browsers, should do things as good as other ones.

**Comment by THausherr** [comment]
Ghostscript fails. Chrome can display the file but text extraction fails. Same for Adobe. An invoice should support text extraction IMHO so that one doesn't have to do OCR. The culprit is Fineco Software v2.05.
