### ISSUE TITLE
DataCloneError on Windows 10 Pro version 1607

### ISSUE THREAD

**Issue by sherburne** [mozilla/pdf.js#9196]
I'm running into a DataCloneError exception when opening a PDF document on Windows 10 version 1607 (aka "Anniversary Update") with IE Edge (38.14393). This error does not occur with Windows 10 version 1709. This error occurs with any PDF document, including the PDF.js sample document (download, then try to view it with the demo's "open" feature.)

The obvious answer here is to upgrade to Windows 1709 or later, but I have a situation where that's not possible.

Attach (recommended) or Link to PDF file here: See PDF.js demo page (download demo PDF document, then open it).

Configuration:
- Web browser and its version: IE Edge 38.14393
- Operating system and its version: Windows 10 Pro version 1607
- PDF.js version: Latest (demo site)
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit PDF.js demo website using Windows 1607/Edge 38.x
2. Note the sample document loads without errors
3. Download the sample document to local filesystem
4. Open the sample document from the local filesystem
5. Note the document never appears
6. Open debugging tools and enable exception breakpoints
7. Reload Demo and attempt to open document
8. Eventually you'll hit a DataCloneError exception in PDF.js

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by sherburne** [comment]
A bit more investigation into this reveals the exception is reported on line 1309 of util.js, however this looks like a symptom of reporting a preceding TypeMismatchError that may be thrown while handling the ReaderHeadersReady event in api.js.

**Comment by sherburne** [comment]
FWIW it's my best guess this is related to the ReadableStreams polyfill, but the state of Edge debugging tools makes it impossible for me to narrow down the exact cause. The code that led me to this issue was passing PDF data into PDF.js as a data URI which triggers the TypeMismatch exception. Passing the PDF data to getDocument as Base64-encoded string (simply by stripping off the leading "data:...;base64,") is enough for me to work around the issue.

**Comment by Snuffleupagus** [comment]
> I'm running into a DataCloneError exception when opening a PDF document on Windows 10 version 1607 (aka "Anniversary Update") with IE Edge (38.14393). This error does not occur with Windows 10 version 1709.

Given that the bug has apparently been fixed upstream, in newer versions of Edge, the likelihood of PDF.js maintainers wanting to add a *version specific* browser compatibility hack might not be that great unfortunately. (Especially when it's not entirely easy to pin-point *exactly* where the issue occurs.)

> FWIW it's my best guess this is related to the ReadableStreams polyfill, but the state of Edge debugging tools makes it impossible for me to narrow down the exact cause.

If it's an issue with the `ReadableStream` polyfill *itself*, then that would need to be reported upstream in https://github.com/whatwg/streams/tree/master/reference-implementation. However, I do appreciate  that doing is difficult without being able to come up with a reduced test-case.

For reference, please also note that based on reports of *completely* broken `ReadableStream` support in older versions of Edge, PR #8744 added better feature detection for native `ReadableStream` support.

**Comment by timvandermeij** [comment]
I'm going to close this issue because it doesn't look like there is anything we can do about this on the PDF.js side based on the above.
