### ISSUE TITLE
Feature request: include font information in properties

### ISSUE THREAD

**Issue by cfr42** [mozilla/pdf.js#9199]
Attach (recommended) or Link to PDF file here: N/A (feature request)

Configuration:
- Web browser and its version: Firefox 57.0 (64 did)
- Operating system and its version: Arch Linux - no version, updated from stable 2017-11-27
- PDF.js version: built into FF
- Is a browser extension: no - built in

Steps to reproduce the problem: No problem. Display PDF properties.

What is the expected behaviour? (add screenshot) Behaves as expected, but I would like it to include font information when showing the document properties. This is a common feature in PDF viewers. Preferably: name, embedded or not, type (OTF/TTF etc.), path to substitute font if not embedded for all fonts

What went wrong? (add screenshot) Nothing. But it is not possible to tell whether a missing font is responsible for characters missing or incorrectly displayed in PDFs. And it is not possible to tell if ugly text is the result of system font substitution choices or a design feature.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by bansalnitish** [comment]
@timvandermeij May I work on this !

**Comment by timvandermeij** [comment]
@bansalnitish It's yours!

**Comment by Snuffleupagus** [comment]
Most of this is already available through the debugger, see https://github.com/mozilla/pdf.js/wiki/Debugging-pdf.js, since this isn't something that most users will ever care about.
However, I'd personally question if it's really worth all the added complexity of giving this a more prominent place in the default viewer UI.

**Comment by bansalnitish** [comment]
@Snuffleupagus Can you just get me started on this ?

**Comment by Snuffleupagus** [comment]
As outlined in https://github.com/mozilla/pdf.js/issues/9199#issuecomment-355408218, I'd suggest closing this as WONTFIX.
