### ISSUE TITLE
How to calculate each div transform?

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#9205]
I am a newbie in pdf.js. I want to know how to calculate transform of each div of pdf?

I want to know about how to find following object of div in pdfjs?

![image](https://user-images.githubusercontent.com/11785531/33328180-4caf9220-d47f-11e7-9b70-3264cc4e175e.png)

**Comment by Snuffleupagus** [comment]
Given the lack of details, it's almost impossible to understand what *actually* being asked here; I'd suggest closing this issue as INCOMPLETE.
