### ISSUE TITLE
RenderingCancelledException when quick(middle mouse button) scrolling

### ISSUE THREAD

**Issue by rkni9ht** [mozilla/pdf.js#9221]
Attach (recommended) or Link to PDF file here: https://acumereview.azurewebsites.net/static/web/viewer.html

Configuration:
- Web browser and its version: firefox 58.0b5
- Operating system and its version: windows 10
- PDF.js version: Not sure think its 2.0.169
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the page
2. Middle mouse button and drag up and down to scroll on the tracemonkey pdf it takes a few times but on about 200 page pdfs it does it as the user is trying to get to the bottom of the document.

What is the expected behavior? (add screenshot)
Not to have a pop up and to render all the pages

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/15227621/33441336-5b44cb5e-d5ea-11e7-9f6b-f9fc81bca08d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://acumereview.azurewebsites.net/static/web/viewer.html

**Comment by Snuffleupagus** [comment]
When loading your custom viewer, I see the following in the console:
```
PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 2.0.169) viewer.js:6870:7
TypeError: javaScript is null [Learn More] viewer.js:6798:1
```
That error, combined with errors you're reporting above, the existence of now removed/changed UI elements (compare e.g. the area around page number input of your viewer with https://mozilla.github.io/pdf.js/web/viewer.html), and a quick look into your `viewer.js` file suggests that you're attempting to use an older version of the default viewer together with the latest `pdf.js`/`pdf.worker.js` files.
Doing that will generally not work (as you've discovered), and is explicitly *not* supported.

Please make sure that you update the *viewer* code as well, and not just the `pdf.js`/`pdf.worker.js` files, and these issues will go away!

Closing as answered.
