### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by singhvaibhavram** [mozilla/pdf.js#9226]
Need to update minimatch and graceful-fs dependencies!

**Comment by timvandermeij** [comment]
Closing since we cannot fix this. These are dependencies of other packages we use; those packages have all been updated on our side already, but those dependencies need to be updated upstream first before we can update. Contact the maintainers of those packages if you want to speed up the process.

**Comment by Snuffleupagus** [comment]
> Need to update minimatch and graceful-fs dependencies!

In addition to https://github.com/mozilla/pdf.js/issues/9226#issuecomment-348699207, please remember to provide more information/context when opening an issue, since a sentence like the one above doesn't provide nearly enough information about *why* such a change would be necessary.
