### ISSUE TITLE
Incorrect Fonts used for rendering text

### ISSUE THREAD

**Issue by bdely** [mozilla/pdf.js#9233]
I am using the pdfjs-dist version 2.0.163 with all browsers on windows 10

The text is not rendering with the correct fonts 
![image](https://user-images.githubusercontent.com/2165209/33566775-0cb81f42-d8ef-11e7-918c-71f4481a77a4.png)

I have tested it in the demo and it is rendering correctly
![image](https://user-images.githubusercontent.com/2165209/33566839-453d9842-d8ef-11e7-8f9e-74bbf1fd73d8.png)

I have tried setting cMapPacked to true and set cMapUrl to the location were the cmaps folder is located
I also changed to verbosity to VERBOSITY_LEVELS.infos and there is no extra information then would I get on the demo site.

Is the any other options that would help to get the fonts to render

**Comment by Snuffleupagus** [comment]
> I have tried setting cMapPacked to true and set cMapUrl to the location were the cmaps folder is located

Without a *complete* example, as asked for in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), we cannot provide any assistance since it's impossible to tell from a distance what's wrong in your implementation.

**Comment by bdely** [comment]
I am not able to provide a complete working example because it is internal software. 
I have inserted the code, it is React.js and TypeScript


`import * as React from 'react';
import * as ReactDom from 'react-dom';
import { Spinner, SpinnerSize } from '../../../Common/SVG';

PDFJS.disableRange = true;
PDFJS.verbosity = PDFJS.VERBOSITY_LEVELS.errors;

class PDF extends React.Component<props, state> {
    private pdfViewer: any;
    private pdfFindController: any;

    private pdfContainer: HTMLElement;

    private scale: string;
    private pdfDocument: any;
    private unmounted: boolean;

    constructor(props: props) {
        super(props);
        this.state = {
            loading: true
        };
    }
    private DestroyDocument() {
        if (this.pdfDocument) {
            this.pdfDocument.destroy();
            delete this.pdfDocument;
        }

        if (this.pdfFindController) {
            clearTimeout(this.pdfFindController.findTimeout);
            delete this.pdfFindController;
        }

        if (this.pdfViewer) {
            delete this.pdfViewer;
        }
    }

    private InitializePDF() {
        this.DestroyDocument();
        this.setState({ loading: true });

        this.pdfViewer = new PDFJS.PDFViewer({
            container: this.pdfContainer
        });

        this.pdfFindController = new PDFJS.PDFFindController({
            pdfViewer: this.pdfViewer
        });

        this.pdfFindController.onUpdateResultsCount = (matchCount: number) => {
            this.props.onSearchComplete(matchCount);
        };

        this.pdfViewer.setFindController(this.pdfFindController);

        PDFJS.getDocument(this.props.src).then((pdfDocument: any) => {
            this.pdfDocument = pdfDocument;

            if (this.unmounted)
                this.DestroyDocument();
            else
                this.pdfViewer.setDocument(pdfDocument);

        });
    }

    private GetHighlightOffset(navIndex: number) {
        let pageIdx = 0;
        let matchIdx = navIndex;
        if (navIndex >= this.pdfFindController.matchCount) {
            pageIdx = this.pdfFindController.offset.pageIdx;
            matchIdx = -1;
        }
        else if (navIndex >= 0) {
            try {
                this.pdfFindController.pageMatches.forEach((pageMatches: any[], pageIndex: number) => {
                    pageIdx = pageIndex;
                    if (matchIdx - pageMatches.length >= 0)
                        matchIdx -= pageMatches.length;
                    else
                        throw true;
                });
            }
            catch (error){ }
        }

        return { pageIdx, matchIdx };
    }

    private updateViewer(nextProps?: props) {
        let props = nextProps ? nextProps : this.props
        if (!nextProps || this.props.search !== nextProps.search) {
            this.props.onSearchComplete(0);
            this.pdfFindController.executeCommand('find', { query: props.search, phraseSearch: false, highlightAll: true });
        }

        if (this.pdfViewer.currentPageNumber !== props.currentPage) {
            this.pdfViewer.currentPageNumber = props.currentPage;
        }

        if (nextProps && nextProps.navigableHitIndex !== this.props.navigableHitIndex) {
            this.UpdatedSelectHighlight(props.navigableHitIndex);
        }

        if (!nextProps || nextProps.zoomLevel !== this.props.zoomLevel) {
            let scale = props.zoomLevel;
            this.scale = '';
            if (typeof props.zoomLevel === 'string') {
                switch (props.zoomLevel) {
                    case 'pagewidth':
                        scale = 'page-width';
                        break;
                    case 'pageheight':
                        scale = 'page-height'; 
                        break;
                    case 'page':
                        scale = 'page-fit'; 
                        break;
                }
                this.scale = scale as string;
            }
            this.pdfViewer._setScale(scale);

            if (typeof scale === 'string') {
                this.props.onZoomAdjust(this.pdfViewer._currentScale);
            }
        }

        if (!nextProps || nextProps.rotationAmount !== this.props.rotationAmount) {
            this.pdfViewer.pagesRotation = props.rotationAmount * -1;
        }
    }

    componentDidMount() {
        let window = (this.refs['container'] as HTMLIFrameElement).contentWindow;
        
        window.onload = () => {
            let document = (this.refs['container'] as HTMLIFrameElement).contentDocument;
            document.getElementsByTagName('head')[0].innerHTML = '<link href="/Content/Plugins/pdf_viewer.css" rel="stylesheet" type="text/css">';
            let body = document.getElementsByTagName('body')[0] as HTMLElement;
            body.innerHTML = '<div class="container"><div id="viewer" class="pdfViewer"></div></div>';
            this.pdfContainer = body.getElementsByClassName('container')[0] as HTMLElement;

            window.addEventListener('resize', _.debounce(() => {
                if (!this.state.loading && this.scale !== '')
                    this.pdfViewer._setScale(this.scale);
            }, 100));

            this.pdfContainer.addEventListener('pagesinit', () => {
                this.pdfViewer.firstPagePromise.then(() => {
                    if (!this.unmounted) {
                        this.props.onDocumentCompleted(this.pdfViewer.pagesCount);
                        this.setState({ loading: false });
                        this.updateViewer();
                    }
                });
            });

            this.pdfContainer.addEventListener('pagechange', () => {
                this.props.onPageChanged(this.pdfViewer.currentPageNumber);
            });

            this.InitializePDF();
        };
    }

    componentWillUnmount() {
        this.unmounted = true;
        this.props.onSearchComplete(0);
        this.DestroyDocument();
    }

    shouldComponentUpdate(nextProps: props, nextState: state) {
        if (this.props.src !== nextProps.src) {
            this.InitializePDF();
        }
        else if (!nextState.loading) {
            this.updateViewer(nextProps);
            if (this.props.isActive != nextProps.isActive) {
                this.toggleCommentLink(!nextProps.isActive);
            }
        } 
        return nextState.loading !== this.state.loading;
    }

    render() {
        return <div style={{ width: '100%', height: '100%' }}>
            <iframe ref="container" src="/Content/Blank.htm" style={{ width: '100%', height: '100%', visibility: this.state.loading ? 'hidden' : 'visible' }} />
            {this.state.loading ?
                <Spinner size={SpinnerSize.LARGE} center={{ vertical: true, horizontal: true }} />
                :
                null}
        </div>;
    }
}
`

**Comment by Snuffleupagus** [comment]
I'm not finding `PDFJS.cMapPacked = true;` and `PDFJS.cMapUrl = 'some/path/to/the/cmaps/';` anywhere in https://github.com/mozilla/pdf.js/issues/9233#issuecomment-349095992, despite https://github.com/mozilla/pdf.js/issues/9233#issue-279084915 mentioning attempting to set those.

> I am not able to provide a complete working example because it is internal software.
> I have inserted the code, it is React.js and TypeScript

The only suggestion is to ensure that you set the CMAP options *before* calling `getDocument`, but without a complete example there's unfortunately nothing we can do here.

**Comment by bdely** [comment]
Sorry I copied my original code both lines were just before `PDFJS.disableRange = true;`
I will try to create an example

Thanks.

**Comment by kkisseljov** [comment]
Got the same issue, but managed to fix that. My problem was that wro4j somehow messed up the pdf.worker.js script and seems like it was crashing silently at some point. I got it working when loaded  it directly to my index.html, this solved all problems.
pdf.js is working fine as it is, though.
