### ISSUE TITLE
How to disable Print and Download buttons?

### ISSUE THREAD

**Issue by mshlin99** [mozilla/pdf.js#9238]
I removed the <button> tags for both, in  <div id="secondaryToolbarButtonContainer">and/or <div id="toolbarViewerRight">. But the webpage cannot load the pdf file. And no response when click Tools button.
Can anyone teach me what else I need to do?
The Viewer is run on Windows Server 2012 IIS.
- Web browser and its version: IE10 and Chrome 62.0
- Operating system and its version: Windows 7, Windows Server 2012
- PDF.js version: 1.9.426
- Is a browser extension: No

**Comment by Snuffleupagus** [comment]
Please see e.g. https://github.com/mozilla/pdf.js/issues/7537#issuecomment-239427098; closing as answered.
