### ISSUE TITLE
web/pdf_viewer.js cannot load build/pdf.js

### ISSUE THREAD

**Issue by szabocsabi** [mozilla/pdf.js#9239]
Configuration:
- Web browser and its version: Chrome, Version 62.0.3202.94 (Official Build) (64-bit)
- Operating system and its version: Win 10
- PDF.js version: 2.0.185, installed from npm

I'm using TypeScript with requirejs and trying to use pdfjs library.

My configuration is:
```
require.config({
  paths: {
    'pdfjs-dist': 'libs/pdfjs-dist',
  }
  shim: {
    'pdfjs-dist/web/pdf_viewer': {
      deps: ['pdfjs-dist/build/pdf']
    }
  }
});

```
The imports are:
```
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
import * as PDFJSWorker from "pdfjs-dist/build/pdf.worker";
```

The problem is that when pdf_viewer tries to load the "../build/pdf.js" with require from the "else" branch:

```
var pdfjsLib = void 0;
if (typeof window !== 'undefined' && window['pdfjs-dist/build/pdf']) {
  pdfjsLib = window['pdfjs-dist/build/pdf'];
} else {
  **pdfjsLib = require('../build/pdf.js');**
}
module.exports = pdfjsLib;
```

...but it throws the following error
![image](https://user-images.githubusercontent.com/6990999/33599778-73d8e950-d9a7-11e7-9840-24ff11d6def1.png)

Since requirejs is using its own config one possible solution could be that giving the path defined in the require.config section.
`**pdfjsLib = require('pdfjs-dist/build/pdf');**`

**Comment by Snuffleupagus** [comment]
> The imports are:
> 
> import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
> import * as PDFJSWorker from "pdfjs-dist/build/pdf.worker";

First of all, why are you importing the `pdfjs-dist/build/pdf.worker.js` file? That file cannot be loaded in the main thread, and should (as the name suggests) only be used in a Web Worker. For the worker file, you need to set the [`PDFJS.workerSrc`](https://github.com/mozilla/pdf.js/blob/f299473697dab586946bbbe4e1aa288aaffc0ec6/src/display/global.js#L140-L147) option to contain the path to that file.

If you fix the second import above to e.g. `import * as PDFJSMain from "pdfjs-dist/build/pdf";`, does that work?
If not, then as asked for in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide a *complete* example since only code snippets aren't very helpful.

**Comment by szabocsabi** [comment]
Sorry for that.
Here's a simple project. I tried to keep the structure as I have in my real project.
https://github.com/szabocsabi/pdfjs_issue
Hope it helps

**Comment by Snuffleupagus** [comment]
Looking at your [example](https://github.com/szabocsabi/pdfjs_issue/blob/0fdafc7669e87736fcafd6f901962163f69db1da/src/modules/Main/Main.ts), you haven't actually addressed any of the points mentioned in https://github.com/mozilla/pdf.js/issues/9239#issuecomment-349258523.

So, please replace https://github.com/szabocsabi/pdfjs_issue/blob/0fdafc7669e87736fcafd6f901962163f69db1da/src/modules/Main/Main.ts#L3 with e.g. `import * as PDFJSMain from "pdfjs-dist/build/pdf";`

Then, as mentioned above, and in the docs, https://github.com/szabocsabi/pdfjs_issue/blob/0fdafc7669e87736fcafd6f901962163f69db1da/src/modules/Main/Main.ts#L7 *must* be a string with the path to the worker file, i.e.
`PDFJSMain.PDFJS.workerSrc = 'string/containing/the/path/to/pdf.worker.js';`.

**Comment by szabocsabi** [comment]
Thank you for the quick reply.
I will change the code as you mentioned but the problem is "build/pdf.js" doesn't contain "PDFViewer" and "PDFLinkService".

That is the reason I imported "web/pdf_viewer.js" which imports "build/pdf.js" and that's the point where it fails.

**Comment by Snuffleupagus** [comment]
> I will change the code as you mentioned but the problem is "build/pdf.js" doesn't contain "PDFViewer" and "PDFLinkService".

Have you tried the following import order instead?
```javascript
import * as PDFJSMain from "pdfjs-dist/build/pdf";
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
```

**Comment by szabocsabi** [comment]
Yes, I tried the following imports:
```
import * as PDFJSMain from "pdfjs-dist/build/pdf";
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
```
```
import * as PDFJS from "pdfjs-dist/build/pdf";
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
```
```
import "pdfjs-dist/build/pdf";
import { PDFJSViewer } from "pdfjs-dist/web/pdf_viewer";
```
...but the error is still appear.

Error location:
```
pdfjs-dist/web/pdf_viewer.js
line 102: pdfjsLib = require('../build/pdf.js');
```

**Comment by szabocsabi** [comment]
@anirudhk sorry for the delay and thanks for your answer.
The problem is that I don't really want to store any 3rd party lib in my project. I get all the libs from npm.

**Comment by anirudhk** [comment]
Oh ok. So the real issue is in pdf.worker.js there is a version check. So everytime a version changes or an update happens this issue will re occur. I had to comment that piece when I stored it locally

**Comment by szabocsabi** [comment]
Found a temporary solution.
```js
<script>
    require(["pdfjs-dist/build/pdf"], function (pdfjs){
        window["pdfjs-dist/build/pdf"] = pdfjs;
        require(['app'], function (app) {
            new app.App();
        });
    });
</script>
```
Loading the pdfjs before bootstrapping the Application and attaching it to window

Since pdf_viewer.js has the following code this will work:
```js
var pdfjsLib = void 0;
if (typeof window !== 'undefined' && window['pdfjs-dist/build/pdf']) {
    pdfjsLib = window['pdfjs-dist/build/pdf'];
} else {
    pdfjsLib = require('../build/pdf.js');
}
```

**Comment by anirudhk** [comment]
Hmm..nice

**Comment by szabocsabi** [comment]
@Snuffleupagus I would have another question.

I would like to the Print functionality but I found that the PDFPrintService is not exported as part of pdf.js or pdf_viewer.js

So my question is how can I import and use that?

Thanks in advance.

**Comment by priyajeet** [comment]
Maybe those lines in pdf_viewer.js should just be changed to

```
var pdfjsLib = require('pdfjs-dist/build/pdf');
module.exports = pdfjsLib;
```
If `pdfjs-dist/build/pdf` has been required before, that should ideally be a noop?

If not that, then at least the`require('../build/pdf.js')` in those lines should be changed to the AMD module name `require('pdfjs-dist/build/pdf')`, and not a relative path, since that relative path is not mapped to the actual pdf.js.

That way the following code will work:

```js
require.config({
  paths: {
    'pdfjs-dist': 'https://path/to/my/version/of/pdfjs-dist/'
  }
});

require([
	'pdfjs-dist/build/pdf',
	'pdfjs-dist/web/pdf_viewer'
], function() {
	// Do stuff with PDFJS
});
```

**Comment by moawadallah** [comment]
i was trying to make a component with it and now you can use it like this.

`import pdfjs from "pdfjs-dist/build/pdf";
import 'pdfjs-dist/web/pdf_viewer';`

**Comment by timvandermeij** [comment]
Closing since this seems to be answered.
