### ISSUE TITLE
Some characters not rendered well in pdf that converted from a web page

### ISSUE THREAD

**Issue by poseidon8254** [mozilla/pdf.js#9240]
Attach (recommended) or Link to PDF file here:
[html table convert to pdf.pdf](https://github.com/mozilla/pdf.js/files/1530903/html.table.convert.to.pdf.pdf)

Configuration:
- Web browser and its version: Chrome Version 62.0.3202.94（Official Build） （64-bit）
- Operating system and its version:Microsoft Windows 10
- PDF.js version:v1.9.426
- Is a browser extension:no

Steps to reproduce the problem:
1.load attached pdf
2.see how the characters are not rendered well

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/22388855/33604942-b34f9b42-d9f2-11e7-8f82-bdbd8a7dd1d1.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/22388855/33604922-a61c05be-d9f2-11e7-92da-bc42560b4a72.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Works for me, using PDF.js `2.0.185` in Firefox Nightly 59 (with HWA on) on Windows 7 (64-bit).

![9240](https://user-images.githubusercontent.com/2692120/33605985-2353a474-d9bc-11e7-89f4-9950cabdf002.png)

**Comment by poseidon8254** [comment]
Thanks a lot.The problem is resloved
