### ISSUE TITLE
An annotation 'add' or 'del' function provided by the edge browser is very useful when reading a pdf file.

### ISSUE THREAD

**Issue by sl0000** [mozilla/pdf.js#9251]
An annotation 'add' or 'del' popup-menu item provided by the edge browser is very useful when reading a pdf file.

**Comment by Snuffleupagus** [comment]
It's somewhat difficult to understand exactly what's being asked/reported here, but the following is my best guess: As mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, PDF.js is a PDF reader and does support adding annotations.

Closing as out-of-scope.
