### ISSUE TITLE
help!! I'm using angular js and the previous developer is used iframe to present the pdf.  Is it a good idea? I'm trying to get the text from the .textlayer class but the iframe calls the  

### ISSUE THREAD

**Issue by AvdiuAndin** [mozilla/pdf.js#9257]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
There is an example for getting the text content: https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js

Other than that, we cannot provide support for custom Angular.js code.
