### ISSUE TITLE
help!! NOT AN ISSUE !! The project is build on angular js and the previous developer presented the pdf in iframe.  Is it a good idea? 

### ISSUE THREAD

**Issue by AvdiuAndin** [mozilla/pdf.js#9258]
I'm trying to get the text from the .textlayer class but the iframe on LOAD returns the .textLayer partially completed. I need to highlight the some parts of the text. I wanted to know if pdf find controller will ease the job for me. If some text is found what the controller will return? Can i somehow initialize it on angular js controller from the iframe.

**Comment by timvandermeij** [comment]
As stated in the other issue, we cannot provide support for Angular-specific issues. The find controller will allow you to highlight parts of the text, but you need to wait until the entire page is loaded.
