### ISSUE TITLE
Japanese characters incorrectly rendered

### ISSUE THREAD

**Issue by generiscorp** [mozilla/pdf.js#9262]
Attach (recommended) or Link to PDF file here:
![pdfjs-error](https://user-images.githubusercontent.com/22979918/33832857-f2d7bc88-de7d-11e7-8064-4c289e6505aa.png)
[Sample file_from_docbase.pdf](https://github.com/mozilla/pdf.js/files/1547881/Sample.file_from_docbase.pdf)

Configuration:
- Web browser and its version: Latest chrome, also IE 11
- Operating system and its version: Mac and Windows
- PDF.js version: Latest demo site - 1.9
- Is a browser extension: No

Steps to reproduce the problem:
1.  Goto https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the attached PDF and open also in Acrobat Reader
3. Compare text - some characters are different - see the attached screenshot

What is the expected behavior? 
Characters rendered correctly as in Acrobat

What went wrong? 
Incorrect character in viewer - Acrobat shows the correct one

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
```
PDF 91d7d110e0edd2aeed3b25db4e68f818 [1.7 www.adlibsoftware.com: CTP (5.4.0.30881) OS (Windows 2012,2,0,64); modified using iText 2.1.7 by 1T3XT / Microsoft Word(15.0)] (PDF.js: 2.0.203)   viewer.js:1607:7
Warning: FormatError: Required "loca" table is not found   pdf.worker.js:340:5
```

**Comment by generiscorp** [comment]
@Snuffleupagus can you explain what that comment mean? :) Thank you.

**Comment by THausherr** [comment]
Here's an explanation of the "loca" table:
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6loca.html

**Comment by THausherr** [comment]
PDFBox shows a different error, "head is mandatory". That table is needed too. I can see "head" and "loca" in the byte sequence. Saving MSMincho and opening it with DTL OTMaster fails. However it succeeded when I renamed it the file to *.ttc. It's a font collection.

**Comment by THausherr** [comment]
@generiscorp The software you have used ("www.adlibsoftware.com: CTP (5.4.0.30881) OS (Windows 2012,2,0,64); modified using iText 2.1.7 by 1T3XT") has embedded the whole truetype collection, instead of embedding just a truetype font, or better, a font subset. Check the options or contact their support. Font subsetting makes the files much smaller.

**Comment by generiscorp** [comment]
@THausherr  thank you, but the PDF should still be displayed correctly in PDF.js as in Acrobat, right?

**Comment by Snuffleupagus** [comment]
> It's a font collection. (I noticed that the byte sequence started with "ttcf").

The specification can be found at https://www.microsoft.com/typography/otspec/otff.htm, under the "Font Collections" heading.

**Comment by THausherr** [comment]
@generiscorp Adobe displays a lot of broken files. Nevertheless, your file is incorrect. You put a font **collection** at a place where **one** font is expected. And having a one page PDF with no image and just a few lines of text grow to a size of 23MB should give you a hint that something is wrong, and fix your PDF production. Such a file should have a size of less than 100KB.

**Comment by generiscorp** [comment]
@THausherr I understand. This is though a file generated by Adlib rendering tool and we have no impact on it's format. Anyway, since the font is embedded all the characters should be displayed correctly, right? Is it going to be fixes or is the only way to fix it is fixing the fonts being embedded?

**Comment by THausherr** [comment]
@generiscorp You could complain to Adlib, or check whether you're using the correct options with their software, maybe also ask them why they are using iText 2.1.7 which is from 2009. 

I don't speak for PDF.js. I work with a different project (pdfbox) and that one has the same problem.

**Comment by THausherr** [comment]
The chrome pdf viewer and ghostscript have the same problem.

**Comment by Snuffleupagus** [comment]
I haven't had time to run any tests yet, but it looks like this ought to work: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:TrueType-Collection
One thing to note though is that the performance isn't that great, but that's probably to be expected since we're forced to parse more than 20 MB of font data (re https://github.com/mozilla/pdf.js/issues/9262#issuecomment-351336064).
