### ISSUE TITLE
Warning while loading unpacked extension in Chrome

### ISSUE THREAD

**Issue by amit7010** [mozilla/pdf.js#9264]
After building Chrome extension in local `gulp chromium` then loading the (unpackaged) extension from the
directory `build/chromium` it shows a warning as shown in image below : 

- 'fileBrowserHandler' is not allowed for specified platform.

Configuration:
- Web browser and its version: 62.0.3202.94 (Official Build) (64-bit)
- Operating system and its version: Windows 10 , 64-bit OS, x64-based processor
- PDF.js version: 2.0.193
- Is a browser extension:yes

![capture3](https://user-images.githubusercontent.com/22027941/33847323-20464f02-ded0-11e7-9cbf-b558d769ef4b.PNG)

After opening a local file,it failed to load the pdf file.

![2](https://user-images.githubusercontent.com/22027941/33847734-8e6aac8e-ded1-11e7-8130-f90eb69a8639.PNG)

Steps to reproduce the problem:

- Run command `gulp chromium` in local directory.

- Then open Chrome, go to `Tools > Extension`

- Load the (unpackaged) extension from the directory `build/chromium`

**Comment by Rob--W** [comment]
`fileBrowserHandler` is only for Chrome OS; You can ignore that warning.

What do you see in the console?

**Comment by Rob--W** [comment]
I reproduced the issue of not being able to open local files, and created a new issue here: #9361

The warning about `fileBrowserHandler` can be ignored, so I'll close this issue.
