### ISSUE TITLE
Google Noto Serif CJK JP font is not rendered properly in Mozilla firefox

### ISSUE THREAD

**Issue by arunbhati** [mozilla/pdf.js#9278]
Attach (recommended) or Link to PDF file here: [FirefoxBugDocument.pdf](https://github.com/mozilla/pdf.js/files/1559178/FirefoxBugDocument.pdf)

Configuration:
- Web browser and its version:
 Firefox (57.0.1)
- Operating system and its version:
 Mac OS X (52.4.1)
- PDF.js version:
 1.6.315
- Is a browser extension:
 No

Steps to reproduce the problem:
1. Open attached pdf (FirefoxBugDocument.pdf) in firefox browser and This pdf file won't render properly.

What is the expected behavior? (add screenshot)
It should show "This text should be in bold" text in **bold**.
<img width="896" alt="properlyrenderedpdf" src="https://user-images.githubusercontent.com/6111411/33993026-dab657b6-e0fa-11e7-8961-f6d2f6cba66e.png">

What went wrong? (add screenshot)
Firefox console throws exception while rendering PDF.
```
downloadable font: OS/2: first char index 65535 > last char index 65534 in os2 (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source:   document.pdf

downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source:   document.pdf

downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source:  document.pdf
```

**Comment by timvandermeij** [comment]
Fixed by #9340.
