### ISSUE TITLE
Is it possible to directly open the Pdf file in full screen mode(presentation mode) using iframe. 

### ISSUE THREAD

**Issue by SunnyAbhi** [mozilla/pdf.js#9281]
I have a requirement that demands viewing  a pdf file in iframe which can open directly in full screen mode. I did some digging and found that the requestfullscreen function in viewed.js can only be initiated by a user gesture. My question is quite simple, Can we open the pdf document directly in full screen mode ?

**Comment by may583** [comment]
เมื่อ วันศุกร์ที่ 15 ธันวาคม ค.ศ. 2017, SunnyAbhi <notifications@github.com>
เขียนว่า:

**Comment by Snuffleupagus** [comment]
> I did some digging and found that the requestfullscreen function in viewer.js can only be initiated by a user gesture. Can we open the pdf document directly in full screen mode ?

No; the Fullscreen API that is used in browsers requires, for security reasons, that entering fullscreen mode is a *user* initiated event.

Closing as answered.
