### ISSUE TITLE
pdf.js and cache 

### ISSUE THREAD

**Issue by sapq** [mozilla/pdf.js#9290]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. i have 1000 pdf on my website using pdf.js the proplem is When I review pdf Example load page number 9 When I come back to pdf must page open on number 9 Because I activated the cache for 1 Month but When I review 10 pdf file anf i back to that pdf  open on page 9 is back to number 1
the pdf.js just can save 10 pdf file  ???

2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by sapq** [comment]
I will pay 100 $ to fix this proplem

**Comment by Snuffleupagus** [comment]
> i have 1000 pdf on my website using pdf.js the proplem is When I review pdf Example load page number 9 When I come back to pdf must page open on number 9 Because I activated the cache for 1 Month but When I review 10 pdf file anf i back to that pdf open on page 9 is back to number 1
> the pdf.js just can save 10 pdf file ???

It's somewhat difficult to understand what you're actually asking here (and the fact that the rest of the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is empty doesn't help either).

However, the following is assuming that you're using the default viewer, i.e. the one found at https://mozilla.github.io/pdf.js/web/viewer.html, and that what you're asking is it it's possible to remember the last viewed position for a PDF file.
If so, then please note that the (current) default is to store information about `20` PDF files, please see https://github.com/mozilla/pdf.js/blob/6bbe91079b1f20e9daa88f2d103d57ffb2bb341f/web/view_history.js#L16
In custom deployments of the default viewer, you can edit that code to change the value. (Another thing to note here is that the `ViewHistory` data is stored using `localStorage`, so if the `localStorage` is cleared in the browser itself then the `ViewHistory` data will be removed as well.)

Closing as answered; if the above isn't sufficient you'll need to provide more *and* clearer information about the problem.

**Comment by TigerLiv** [comment]
> I will pay 100 $ to fix this proplem

hi，guys,pdfjs cache memory ,are you solve it？ can you tell me how to solve it?

**Comment by sapq** [comment]
yes i fix it 

const DEFAULT_VIEW_HISTORY_CACHE_SIZE = 20; 

i make  this  like  this

const DEFAULT_VIEW_HISTORY_CACHE_SIZE = 9000;

**Comment by sapq** [comment]
hi Snuffleupagus  you want  100$ 

coz i say i will pay for fix you  help 

how i can i send  this  to you  ???

**Comment by Snuffleupagus** [comment]
> hi Snuffleupagus you want 100$
> 
> coz i say i will pay for fix you help
> 
> how i can i send this to you ???

If you, or anyone else for that matter, would like to send me money I've got a PayPal account using the same email address as the one that's found in my [GitHub profile](https://github.com/Snuffleupagus).
(Any further communication on this matter should probably happen in private though.)

**Please keep in mind:** Sending me money is *obviously* completely voluntary, and it also doesn't come with any sort of guarantees regarding my future contributions to e.g. the PDF.js project.
