### ISSUE TITLE
[Printing] Blank Page on Chrome

### ISSUE THREAD

**Issue by demonslord** [mozilla/pdf.js#9295]
Attach (recommended) or Link to PDF file here:
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/1572316/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Chrome 63.0.3239.108 (oficial) (64 bits)
- Windows 10 Pro
- PDF.js version: 1.10.88
- Is a browser extension: No

Steps to reproduce the problem:
1. Press print button on pdfjs viewer

What is the expected behavior? (added video)

- Printing ONE page

What went wrong? (added video)

- Blank page on end of document

[2017-12-19_16-12-16.zip](https://github.com/mozilla/pdf.js/files/1572329/2017-12-19_16-12-16.zip)

Additional Notes:
- Works as expected in FireFox 57.0.2 (64-bit)
- Works as expected in IE EDGE 40.15063.674.0
- If you open the pdf in browser directly (as I show in attached video), the default print dialog of chrome show only ONE page.

Best Regards,
Alexander

**Comment by valeriysuhorukov** [comment]
I also have this problem, tell me the solution?

**Comment by kenwhale** [comment]
We have met the same problem. How can we fix it ?

**Comment by kenwhale** [comment]
Hi，all. We found out it's pdf file's problem.When the pdf file's MediaBox exceed A4 paper's size,it will print blank pages. It's none of pdf.js bussiness.

**Comment by demonslord** [comment]
@kenwhale
Don't sure if the problem in MediaBox, because if you try to print my attached pdf directly from chrome printer dialog, its doesn't create/show the second blank page.

**Comment by demonslord** [comment]
Any news about this issue? :)

**Comment by timvandermeij** [comment]
Not yet, but we have had several reports of this. I'm marking this as a good beginner bug because I hope it shouldn't be too hard to at least find out why it happens.

**Comment by ashish10677** [comment]
Hi,
I am new to Open Source and I would like to contribute to pdf.js
Can you please help me get started?

**Comment by timvandermeij** [comment]
You can set up the development environment using the steps on https://github.com/mozilla/pdf.js/wiki/Contributing. Then you need to find out why the extra blank page is generated in Chrome, by for example checking the page width/height and if/why it gets out of bounds.

**Comment by jessepeterman** [comment]
It looks like in Chrome it is reading the test file in Portrait mode instead of in Landscape.

**Comment by jessepeterman** [comment]
Nevermind it still works correctly in test-plusminus.pdf... Where is the code that tells the file to print in the source, and the settings it is sending? I'm having trouble finding it

**Comment by mkenigs** [comment]
I'll try to take a look at this if no one else is working on it

**Comment by mkenigs** [comment]
Looks like this happens for MediaBox [0 0 842 >=534], and the same error occurred when I tested it with another pdf. It also occurs for the file given in #10094 which has MediaBox [0, 0, 841.92, 595.32]. Will try to track down why but would appreciate any pointers

**Comment by tushroy** [comment]
I am also having similar issue on Chrome.
Any updates regarding this?

**Comment by mirefly** [comment]
It looks like an bug in Chrome. https://bugs.chromium.org/p/chromium/issues/detail?id=918791

**Comment by Rob--W** [comment]
Another example:
[SKM_C25819040211380.pdf](https://github.com/mozilla/pdf.js/files/3033571/SKM_C25819040211380.pdf)

It has `MediaBox [ 0 0 595 841 ]`

Reduced test case (HTML only, using red rectangle instead of actual page content):

```
data:text/html,<!DOCTYPE html><style>@page{margin:0;size: 595pt 841pt;}*{margin:0;padding:0}.pc{height:100%}.pc>div{position:relative;top:0;left:0;width:1px;height:1px;overflow:visible;page-break-after:always;page-break-inside:avoid;}</style><div class=pc><div><img src=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEX/AAD///9BHTQRAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNgAAAAAgAB9HFkpgAAAABJRU5ErkJggg== style="width:793px;height:1121px;"></div></div>
```

**Comment by aces2808** [comment]
had same issues, worst is, upon print preview it crashes, any fix on this?

**Comment by Snuffleupagus** [comment]
WFM, when testing in PDF.js version `2.9.94` (via https://github.com/mozilla/pdf.js#online-demo) in Chrome Beta 90.0.4430.72; most likely this was fixed by the recent round of printing patches.
