### ISSUE TITLE
Feature Request: Ability to interrogate xref trailer for IRM metadata

### ISSUE THREAD

**Issue by dmichon-msft** [mozilla/pdf.js#9300]
### Scenario
When opening a PDF file that is protected by Microsoft Information Rights Management (e.g. one protected using Microsoft Azure Information Protection), pdf.js (correctly) displays a page that identifies that the reader does not support the IRM. This is facilitated by the pdf containing said page alongside an encrypted container that the reader does not recognize and therefore does not attempt to process.

In the interests of providing a better user experience (the application may have more useful options available for IRM'd pdf files), I would like to be able to detect when a PDF contains such a container; however, the necessary information is currently only available to the pdf worker thread.

### Detection
The presence of the encrypted container is denoted by the xref trailer containing a dictionary called "Wrapper" that contains a field called "Type" with value "MicrosoftIRMServices". I am looking for some supported mechanism to ask pdf.js if a loaded PDF contains such a field in its xref trailer.

The simplest path to do so would be to add the following to `PDFDocument` in `src/core/document.js`:
```diff
+   get wrapperType() {
+     var trailer = this.xref.trailer;
+     var wrapperType;
+     if (trailer.has("Wrapper")) {
+       var wrapperDict = trailer.get("Wrapper");
+       if (wrapperDict.has("Type")) {
+         var value = wrapperDict.get("Type");
+         wrapperType = (typeof value !== string ? value : stringToPDFString(value));
+       }
+     }
+
+     return shadow(this, 'wrapperType', wrapperType);
+   },

    getPage: function PDFDocument_getPage(pageIndex) {
      return this.catalog.getPage(pageIndex);
    },
```
### Exposure
The easiest way to get at this information would be to expose it as part of `loadDocument` in `src/core/worker.js`:
```diff
+       var wrapperTypePromise = pdfManager.ensureDoc('wrapperType');
        Promise.all([numPagesPromise, fingerprintPromise,
-                     encryptedPromise]).then(function onDocReady(results) {
+                     encryptedPromise, wrapperTypePromise]).then(function onDocReady(results) {
          var doc = {
            numPages: results[0],
            fingerprint: results[1],
-           encrypted: !!results[2]
+           encrypted: !!results[2],
+           wrapperType: results[3]
          };
          loadDocumentCapability.resolve(doc);
        },
        parseFailure);
```
Alternatively, one could add a separate pathway to get at this data, but that seems like a lot of work for little gain, unless there are a number of other scenarios that involve inspecting the xref trailer for different values.

Is this a scenario the project would be open to accepting a PR for?

**Comment by yurydelendik** [comment]
> Is this a scenario the project would be open to accepting a PR for?

Generally, no, if the "Wrapper" is not part of the PDF32000 specification. Can it be done via spec friendly attributes, e.g. some JavaScript or Metadata presence? We have similar problem with XFA form files and it will be nice to develop more generic solution.

Can you also attach test/example PDF to this issue?

**Comment by Snuffleupagus** [comment]
@timvandermeij Given https://github.com/mozilla/pdf.js/issues/9300#issuecomment-353212350, should this issue simply be closed as WONTFIX?

**Comment by timvandermeij** [comment]
Yes, indeed.
