### ISSUE TITLE
How to use the getselection method on pdf file on any web browser.

### ISSUE THREAD

**Issue by jsjspapa** [mozilla/pdf.js#9301]
I’m trying to get a word from a PDF file on a web page when I select the word with the mouse on the pdf. 
It is very helpful for you to show me the full code that starts with <htlm> and ends with </html>.
I'm just like a novice.
Please use the alert() function to show the word.

**Comment by Snuffleupagus** [comment]
Unfortunately it's quite difficult to understand what you're asking here.

Please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md and also that you provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

For questions regarding custom implementations of PDF.js, as outlined in the links above, you'll need to provide a complete (and runnable) example for the issue to be valid.

Closing as incomplete for now.
