### ISSUE TITLE
pdf.js in mobild not work 

### ISSUE THREAD

**Issue by yclnycl** [mozilla/pdf.js#9307]
Hello, I found pdf.js on mobile not work, iframe DOM is empty,  the DOM not wokr too Is there a solution?

**Comment by Snuffleupagus** [comment]
Closing as incomplete; please read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) before opening an issue and make sure that you provide all of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).
