### ISSUE TITLE
text selection offset

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#9316]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 64.0.3282.39 (Official Build) beta (64-bit)
- Operating system and its version: MAC High Sierra 10.13.1 (17B1003)
- PDF.js version: online as of Dec 26, 2017
- Is a browser extension:

Steps to reproduce the problem:
1. upload attached PDF to view with online PDF viewer
2. notice how every text line is selectable ABOVE the displayed glyphs

What is the expected behavior? (add screenshot)
The textlayer should be over the actual glyphs.

What went wrong? (add screenshot)
The textlayer are created with a wrong offset (vertically offset by something like one line).
[Soo Hostetler-2006 iDMAa Full Paper.pdf](https://github.com/mozilla/pdf.js/files/1587645/Soo.Hostetler-2006.iDMAa.Full.Paper.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by RickyWong33** [comment]
the same problem

**Comment by bryanph** [comment]
Here is another example that has the same issue:
[example.pdf](https://github.com/mozilla/pdf.js/files/2358561/example.pdf)

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.

**Comment by nikolalukovic** [comment]
@timvandermeij sooo, when are we going to see a next release with this fix included?

**Comment by timvandermeij** [comment]
It's periodically pushed to Firefox Nightly. In terms of `pdfjs-dist` releases, there is no exact date determined yet.

**Comment by nikolalukovic** [comment]
Okay, thanks for the info 👍
