### ISSUE TITLE
Is thre a way of using this module on server only to convert pdf to text.

### ISSUE THREAD

**Issue by MagSag** [mozilla/pdf.js#9317]
Configuration:
- Web browser and its version: I am not using a browser, I just want to convert and save the text in the datbase
- Operating system and its version: centos 6 (passenger)
- PDF.js version: any pdf file
- Is a browser extension: I am not using a browser

**Comment by timvandermeij** [comment]
Refer to the Node.js example at https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L51. Closing as answered.
