### ISSUE TITLE
Is there any way to find 'WHEN' a PDF starts rendering? like we have "PAGERENDERED" event!

### ISSUE THREAD

**Issue by AnanthaRamaKrishnan47** [mozilla/pdf.js#9319]
After a page finished rendering we can find out by adding event listener for "PAGERENDERED". Like that is there any event triggered for start of a PDF rendering?

**Comment by timvandermeij** [comment]
Check the `dom_events.js` file at https://github.com/mozilla/pdf.js/blob/f83bd721fc0fbc382f0059903e1f16a410401732/web/dom_events.js. There is, for example, the `documentload` event and the `pagesloaded` event, which I think is what you need. That file lists all the available events, so check their usages. Closing as answered.
