### ISSUE TITLE
Remove undefined PDFJS.isValidUrl property

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#9322]
The `isValidUrl` function in `src/dom_utils.js` was deprecated in 71a781ee5c9e548c16d8e612f41fbc45f1082fc5 and removed in 0f90d5130c9b4c847d5efecac9a727c151156883.
However, the source code still contains references to it in display/global.js:

https://github.com/mozilla/pdf.js/blob/fe30d4d468237864eb5a0609658a8372bfaa3ca0/src/display/global.js#L18-L19

https://github.com/mozilla/pdf.js/blob/fe30d4d468237864eb5a0609658a8372bfaa3ca0/src/display/global.js#L70

This `isValidUrl` import and `PDFJS.isValidUrl` property should be removed.

**Comment by Snuffleupagus** [comment]
Yes, this was an oversight of mine in PR #9028, however it's already being taken care of as part of PR #9185.

**Comment by shikhar-scs** [comment]
So, this issue is closed now ?

**Comment by timvandermeij** [comment]
No, we'll keep it open until that pull request is merged.

**Comment by shikhar-scs** [comment]
Oh ok Thanx for replying :+1:

**Comment by shikhar-scs** [comment]
@timvandermeij if no one is working on this may I try ?

**Comment by Snuffleupagus** [comment]
> if no one is working on this may I try ?

The previously provided information still stands; please refer to https://github.com/mozilla/pdf.js/issues/9322#issuecomment-355822632 and https://github.com/mozilla/pdf.js/issues/9322#issuecomment-354175949, which mentions that this will be addressed by (the currently open) PR #9185.

**Comment by shikhar-scs** [comment]
I'm very sorry, just didn't notice it somehow. Apologies for all the disturbance
