### ISSUE TITLE
why some PDF files only loaded the first page，and the other pages loading for a long time?

### ISSUE THREAD

**Issue by gooczy** [mozilla/pdf.js#9326]
Attach (recommended) or Link to PDF file here:
https://github.com/gooczy/pdf.js/blob/master/test2.pdf

Configuration:
- Web browser and its version: safari  
- Operating system and its version: iphone 5s，IOS version: 11.1
- PDF.js version:  the newest and the 2016 version
- Is a browser extension:

Steps to reproduce the problem:
1. I tested a pdf file https://github.com/gooczy/pdf.js/blob/master/test2.pdf，this file can render the first page,but the other pages keep loading for a long time,even for many hours.
2. I have tested Android mobile，chrome，and virtual devices in chrome，and pdfJS works well.  but my iphone 5s（IOS 11.1） and my workmate's iphone 6s（IOS 10） suffered this problem.
3. And I test network condiction，2G network works well in other devices.
4. I test different PDF files，some PDF render well，but some PDF suffering such problem，and upper file is one of them.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/20809970/34441973-080212c2-ecfa-11e7-9c64-b547d255b283.png)

What went wrong? (add screenshot)
can not load other pages except the first page
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by gooczy** [comment]
I tested '/pdfJS/examples/mobile-viewer/viewer.html' with the same PDF file. Chrome cannot load this file too, and console warns '(5) util.js:276 Warning: Image exceeded maximum allowed size and was removed.'
but not the same behavior. I don't know does it matters.

**Comment by wklu** [comment]
In IOS, the default fonts are divided into three categories:

1: STHeiti-Light.ttc and STHeiti-Medium.ttc represent Chinese characters.

2: _H_Helvetica.ttc and _H_HelveticaNeue.ttc represent English and digital fonts.

3: LockClock.ttf stands for lock screen time fonts.

If PDF has other fonts, IOS will take a long time.
**Solution: please change the font or insert the font**
