### ISSUE TITLE
examples/learning/prevnext.html use local num instead of global pageNum

### ISSUE THREAD

**Issue by andreip** [mozilla/pdf.js#9328]
This is just a logic enhancement in the `examples/learning/prevnext.html` code, as well as the JSFiddle gh-pages branch corresponding to same file.

So:

https://github.com/mozilla/pdf.js/blob/9e0559264ce8a782b5a82c6e479e6c3903cdb2cc/examples/learning/prevnext.html#L85

changed to

```nodejs
document.getElementById('page_num').textContent = num;
```

There `pageNum` is used, but since `renderPage` received a `num` parameter, that could be used instead of the outside variable. I guess it doesn't make much of a difference anyway, since `pageNum` is kept in sync all the time, but then `renderPage` could just as easily use `pageNum` from outside instead of receiving a parameter.

It's definitely a `5-good-beginner-bug` tag. It's clear to me that a PR branched off master could modify `examples/learning/prevnext.html` file, but I'm not clear how to update JSFiddle, since the url from [gh-pages has `/pdfjs/` in it](https://github.com/mozilla/pdf.js/blob/gh-pages/examples/index.html#L87), so who has permission could update that jsfiddle directly w/o needing to change the link in github pages? Or regenerate it so it keeps `pdfjs` in url `//jsfiddle.net/pdfjs/<newcode>`.

**Comment by himanish-star** [comment]
I would like to do this change

**Comment by andreip** [comment]
go for it 👍
