### ISSUE TITLE
Hello  Getting this error on LG webos 

### ISSUE THREAD

**Issue by hilalbhat** [mozilla/pdf.js#9332]
TypeError: Expected at least one argument .  viewer.js : 405

![image](https://user-images.githubusercontent.com/24771801/34475237-2a01c576-efb0-11e7-9779-10537fc3c232.png)

Tested on browsers Chrome , Mozilla , Safari .... Working there same code.

But not on webos (LG)

**Comment by Snuffleupagus** [comment]
> Tested on browsers Chrome , Mozilla , Safari .... Working there same code.
>
> But not on webos (LG)

Unfortunately we don't support that browser, hence the recommendation would be to use one of the standard browsers (e.g. the ones you listed above).

Closing as answered.
