### ISSUE TITLE
excellent would be killer feature when adding pdf annotations

### ISSUE THREAD

**Issue by homberghp** [mozilla/pdf.js#9333]
No problem, feature request.
Being able to annotate (text, marks, scribles) and be able to save as pdf would be a killer feature for this plugin and firefox (assumin firefox is using it).

**Comment by Snuffleupagus** [comment]
As explained in the Wiki, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, adding annotations is out-of-scope for PDF.js.

Closing as answered.

**Comment by THausherr** [comment]
This guy has something:
http://tech.chitgoks.com/2015/03/30/how-to-create-annotations-in-pdf-js/

**Comment by chitgoks** [comment]
Thanks @THausherr 

URL has moved. https://annotationeer.netlify.app/
