### ISSUE TITLE
pdf.worker.js version mismatch

### ISSUE THREAD

**Issue by svenyonson** [mozilla/pdf.js#9337]
Problem: Whenever there is a new build of pdf.worker.js, it breaks my page because the pdf.js that I load is older than the current pdf.worker.js.

If I include `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.246/pdf.min.js`, it will then load http://mozilla.github.io/pdf.js/build/pdf.worker.js, which is now at 2.0.250. How can I pre-empt having pdf.js load pdf.worker.js and instead explicitly load both files from my server so that the versions will match forever until I update my html file?

**Comment by yurydelendik** [comment]
> If I include https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.246/pdf.min.js, it will then load http://mozilla.github.io/pdf.js/build/pdf.worker.js, which is now at 2.0.250. 

Why it does not load https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.246/pdf.worker.min.js ? There is no reason to load pdf.js and pdf.worker.js from different locations. Please adjust logic in your html file to load these files from the same location. Closing as answered.

**Comment by svenyonson** [comment]
I tried this and it does  not work.  You can see that I explicitly load both files from the distribution, and then further down, pdf.worker.js is loaded again from mozilla.github.io. It will work one day and then fail when mozilla.github.io has a newer build.
![pdf js](https://user-images.githubusercontent.com/369966/34567407-618399b4-f11f-11e7-8488-7505de6e4be6.png)

**Comment by yurydelendik** [comment]
>  You can see that I explicitly load both files from the distribution,

If you are loading pdf.worker.js via script tag in html stop doing it.

> pdf.worker.js is loaded again from mozilla.github.io.

That's not supposed to happen. If PDFJS.workerSrc is specified, it supposed to load worker from specified location.
