### ISSUE TITLE
Text duplicated in wrong location on iPhone Safari

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#9347]
This PDF displays correctly on the desktop browsers we've tried, including Safari on Mac:

[A3-Menu-Leaflet-lr.pdf](https://github.com/mozilla/pdf.js/files/1612374/A3-Menu-Leaflet-lr.pdf)

I've been trying it on the latest version of the pdf.js test viewer at https://mozilla.github.io/pdf.js/web/viewer.html

On Safari 11.0.2 for desktop Mac, for example, it looks like this: 

![screen shot 2018-01-08 at 16 58 41](https://user-images.githubusercontent.com/786238/34682277-5166d5c6-f496-11e7-8715-9ba8b3b532c6.png)

However, on iPhone X it has this duplication of text problem:

<img width="409" alt="screen shot 2018-01-08 at 16 59 41" src="https://user-images.githubusercontent.com/786238/34682289-5cbe1e66-f496-11e7-8abb-b46c0dc4bbbb.png">
<img width="403" alt="screen shot 2018-01-08 at 17 00 12" src="https://user-images.githubusercontent.com/786238/34682292-60784d2e-f496-11e7-8cbb-68a3bcbf316d.png">

Operating system iOS 11.2
Browser size 724 x 375
Screen size 375 x 812 (Retina)

This was on Apple's iPhone simulator, but the same behavior has been seen on other iPhones too.

The PDF was created on Adobe InDesign.

Thank you!

**Comment by brendandahl** [comment]
Some warnings from the simulator console:

```
[Warning] Canvas area exceeds the maximum limit (width * height > 16777216).
[Warning] Canvas area exceeds the maximum limit (width * height > 16777216).
```

from putBinaryImageData canvas.js:513
and
CachedCanvases_getCanvas canvas.js:320

**Comment by jegjessing** [comment]
I get this warning, and I'm lost...
Did you get any reply on the warning?
Is there no way to "disable" hidpi on the canvas or something else?

**Comment by Snuffleupagus** [comment]
Given that this issue seem limited to a *particular* browser/platform, it's unfortunately not clear that this is an actionable issue *here* and it's more likely to be e.g. a `canvas`-bug in browser itself (since otherwise it should be consistently broken everywhere).

> Some warnings from the simulator console:
> 
> ```
> [Warning] Canvas area exceeds the maximum limit (width * height > 16777216).
> [Warning] Canvas area exceeds the maximum limit (width * height > 16777216).
> ```

That *should* be unrelated, and furthermore note that we have code which reduces the `maxCanvasPixels` value for e.g. iOS in https://github.com/mozilla/pdf.js/blob/master/web/viewer_compatibility.js
