### ISSUE TITLE
Adding print button to component examples

### ISSUE THREAD

**Issue by EricG-Personal** [mozilla/pdf.js#9348]
If I am correct, the component examples would demonstrate how I can take PDF.js and wrap it in a React component. 

Currently, the component examples do not include the print button, etc. of the HelloWorld example. 

What would be involved to in order to get the print button to show up for one of the component examples?

**Comment by timvandermeij** [comment]
The hello world example (refer to https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) also has no print button. This button is only in the default viewer in the `web/` folder. Including that is definitely not part of the components examples, which allow you to create a basic viewer yourself for people who don't want to have all functionality of the default viewer. Printing is a more advanced feature, so you either have to implement that yourself or (re)use (parts of) the default viewer.
