### ISSUE TITLE
Invalid State Error

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#9351]
Issue is specific to Mac Safari.
Renders ok in Chrome on Mac and WIndows

Using PDFJS 1.6.263
Compatibility is loaded

Safari 11.02
macOS HighSierra

DOM Exception 11 - drawImage line 7192.

Attach (recommended) or Link to PDF file here:
[Test.pdf](https://github.com/mozilla/pdf.js/files/1619083/Test.pdf)

The error seems to eventually go away after several attempts to reload, so it maybe connected to it then being cached and it loading faster as initially for some reason it loaded very slowly form the client site.

**Comment by Snuffleupagus** [comment]
> Using PDFJS 1.6.263

That version is quite old, and also not an official release. Please test this with the *latest* version, which can be found at https://github.com/mozilla/pdf.js/releases, to ensure that this issue is still present.

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.

**Comment by blackmambahk** [comment]
OK have updated all our users, still same problem.

The API version "undefined" does not match the Worker version '2.0.22.0'
