### ISSUE TITLE
Poor print quality of precise pattern compared to Acrobat DC

### ISSUE THREAD

**Issue by Shinkan** [mozilla/pdf.js#9357]
Attach (recommended) or Link to PDF file here:
[FontDots.pdf](https://github.com/mozilla/pdf.js/files/1622816/FontDots.pdf)

Configuration:
- Web browser and its version: FF 57.0.4
- Operating system and its version: W10
- PDF.js version: latest, downloaded today
- Is a browser extension: problem occurs both as web extension and as installed locally.

Steps to reproduce the problem:
1. open the pdf in PDF.js and Acrobat DC
2. zoom in and compare how PDF.js and Acrobat DC show the file
3. come back here and help please :)

What is the expected behavior?
The pattern seen in the file needs to be printed precisely - as Adobe Acrobat does. On previous versions of FF, where Acrobat in-page plugin was used there was no problem. But after FF has stopped supporting plugins, I have a problem with the PDF.js library. It destroys the quality of the pattern for printing. Unfortunately it has to be printed from within the webpage (opening in Acrobat is not an option).
See below how it should be:
![obraz](https://user-images.githubusercontent.com/1094497/34830044-f0e4527e-f6e2-11e7-8c84-526e5d69bd71.png)

What went wrong?
Preview in PDF.js:
![obraz](https://user-images.githubusercontent.com/1094497/34829145-026b1e5e-f6e0-11e7-988d-5989e526ab51.png)
Print from PDF.js on Microsoft print to PDF (printing on a physical printer looks even worse):
![obraz](https://user-images.githubusercontent.com/1094497/34829234-4b89448a-f6e0-11e7-9901-88c582c53452.png)

**Comment by Shinkan** [comment]
Anyone?
Mozilla killing off Adobe Reader plugin for Firefox has caused a huge problem in one of our projects. We have to make it work with PDF.js (or alternative if possible) somehow..

**Comment by Hawex** [comment]
Hi
I've got similar issue. Do anyone know how to improve print quality??

**Comment by c-e-p-x-u-o** [comment]
Is it a dup for #2750?

**Comment by timvandermeij** [comment]
Yes, it's a duplicate.
