### ISSUE TITLE
Cannot view local files in Chrome extension with fetch API

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#9361]
I have built the latest version of the extension, and tried to open a local PDF file. It won't open, the console shows the following error:

> pdf.js:8302 Fetch API cannot load file:///path/to/file.pdf. URL scheme must be "http" or "https" for CORS request.

To fix this, the Chrome extension must only use PDFFetchStream for http(s) schemes, and PDFNetworkStream for other schemes (file, ftp).

**Comment by mukulmishra18** [comment]
I don't think this is just a chrome specific issue. We can't use `fetch` to open local file as we do with `XHR`. So maybe firefox will also give same issue while opening local files?

**Comment by Rob--W** [comment]
@mukulmishra18 When you talk about "Firefox", are you referring to the built-in viewer of Firefox?
(The current Firefox add-on of the project does not work in the latest Firefox (57) because it is not written using the WebExtensions API.)

**Comment by mukulmishra18** [comment]
> When you talk about "Firefox", are you referring to the built-in viewer of Firefox?

Yes, right.

**Comment by Rob--W** [comment]
But the built-in viewer in Firefox doesn't use `fetch`, does it? The logic responsible for switching to the `fetch` implementation is disabled for the Firefox build: https://github.com/mozilla/pdf.js/blob/master/src/pdf.js#L32-L41

**Comment by mukulmishra18** [comment]
Oh! I got it. Sorry.
