### ISSUE TITLE
pdf rendered completely wrong

### ISSUE THREAD

**Issue by gHensges** [mozilla/pdf.js#9367]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 63.0.3239.132 
- Operating system and its version: Windows 10
- PDF.js version: using your official demo project
- Is a browser extension: No

Steps to reproduce the problem:
1.  Just load attached pdf
2.

What is the expected behavior? (add screenshot)
[E-WG18_105147.pdf](https://github.com/mozilla/pdf.js/files/1634833/E-WG18_105147.pdf)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/29802177/34986271-3ca71a5c-fab7-11e7-95e8-1739dda3cd04.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
This file makes use of three TrueType fonts (Tahoma/Tahoma,Bold/Tahoma,Italic), none of which are embedded.
