### ISSUE TITLE
Pdfjs width and header of page

### ISSUE THREAD

**Issue by Thj007** [mozilla/pdf.js#9370]
1.what can I get messages of the file of pdf，such as header of page，bottom of page 
2.why the viewport.width aways bigger of the width of canvas？

**Comment by yurydelendik** [comment]
> 1.what can I get messages of the file of pdf，such as header of page，bottom of page

PDF document don't have information about what's header or bottom. You have to use getTextContent and detect it yourself.

> 2.why the viewport.width aways bigger of the width of canvas？

Not true. You can create a canvas that is bigger than viewport.width, or create viewport with smaller scale.

Closing as answered.
