### ISSUE TITLE
Need Mobile Version of  PDF.js for display inline PDF inside app

### ISSUE THREAD

**Issue by ruchiverma6** [mozilla/pdf.js#9371]
**I need Mobile Version of PDF.js for display inline PDF inside app.**

I found one link for Mobile PDF.js support:
https://wiki.mozilla.org/Mobile/Projects/PDF.js_support
 
But there is no mobile version of PDF.js at that link.

I found following at github:
https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer

I tried to integrate it in mobile app code for inline PDF display. But using above files for PDF.js, blank PDF viewer is getting open but PDF content is not getting displayed.

**Can anyone please help how can I found mobile version of PDF.js**

**Reason for need of mobile version of PDF.js:**
We are working on Xamarin.form app development.
 
We have a requirement to display inline PDF inside app.
 
As per suggested link from Xamarin:
 
https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/display-pdf/
 
We can use PDF.js library for displaying inline pdf inside app.
I downloaded PDF.js from following link:
 
https://mozilla.github.io/pdf.js/
 
This PDF.js is of size 5.50 MB which is very large in size from mobile apps perspective.
 
I found few following links suggesting to use Mobile version of PDF.js:
https://stackoverflow.com/questions/41176549/open-pdf-file-in-xamarin-forms/41180688#41180688
 
I found one link for Mobile PDF.js support also:
https://wiki.mozilla.org/Mobile/Projects/PDF.js_support
 
But unable to find Mobile version of PDF.js anywhere.
 
Please help.
Thanks

**Comment by FranklinSilva** [comment]
This article must help you with your issue

https://docs.telerik.com/platform/knowledge-base/how-to/how-to-open-pdf-in-app

**Comment by yurydelendik** [comment]
> This article must help you with your issue

> https://docs.telerik.com/platform/knowledge-base/how-to/how-to-open-pdf-in-app

Thanks. Closing as answered.
