### ISSUE TITLE
How to migrate pdf.js to electron framework

### ISSUE THREAD

**Issue by nerverBeenEasy** [mozilla/pdf.js#9372]
Hello pdf.js authors!

As the project describes, the pdf.js is normally used to render PDF in web, it performs well and outstandingly. 
My question is that is it possible to migrate pdf.js to ELECTRON framework and render the PDF in desktop application? If yes, what is the basic procedures to achieve this task ?

Thank you so much!

**Comment by Snuffleupagus** [comment]
> My question is that is it possible to migrate pdf.js to ELECTRON framework and render the PDF in desktop application?

It might be possible, but that's out-of-scope for the PDF.js project. Furthermore I don't think that any of the core contributors are experts in Electron.

Finally, please note that these sort of broad questions (and requests for help) are unfortunately not really actionable; refer to [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) from which I'm quoting the relevant section below.
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by Snuffleupagus** [comment]
> My question is that is it possible to migrate pdf.js to ELECTRON framework and render the PDF in desktop application?

It might be possible, but that's out-of-scope for the PDF.js project. Furthermore I don't think that any of the core contributors are experts in Electron.

Finally, please note that these sort of broad questions (and requests for help) are unfortunately not really actionable; refer to [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) from which I'm quoting the relevant section below.
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by nerverBeenEasy** [comment]
Understood. I am sorry to post this board questions (and requests for help) because it is really out of the scope of PDF.js project, thank you so much for your rely !

**Comment by janumedia** [comment]
PDF.js worked well with Electron as long as you're not using `app://` protocol which is currently not supported or maybe it won't.
