### ISSUE TITLE
pdf2png error using a file that contains an Image - ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by ale00** [mozilla/pdf.js#9373]
Link to PDF file:
[QP 22 - Aprile 2016.pdf](https://github.com/mozilla/pdf.js/files/1639293/QP.22.-.Aprile.2016.pdf)

## Configuration:
- Node.js v8.9.0
- Operating system and its version: macOS 10.13.2
- PDF.js version: pdfjs-dist v2.0.269

## Steps to reproduce the problem:
1. Add attached _QP 22 - Aprile 2016.pdf_ file in `functions` folder
2. Change pdfURL in `examples/node/pdf2png/pdf2png` to point to `./QP 22 - Aprile 2016.pdf`
3. Add this line after `pdfjs-dist` import as workaround for #8489 : 
`pdfjsLib.PDFJS.disableFontFace = true;`
4. Run the pdf2png.js example

## What is the expected behavior?
Create an image of the first page of the PDF file.

## What went wrong?

- No image created
- The log returned from the execution is:

```
# PDF document loaded.
(node:1459) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: Image is not defined
(node:1459) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Snuffleupagus** [comment]
For environments without native `Image` support, such as e.g. Node.js, you need to set the `nativeImageDecoderSupport` option in `getDocument` to avoid these kind of errors; please refer to PR #8350 and the API docs in https://github.com/mozilla/pdf.js/blob/97faedba0cd74d9f5899c2ffa33bb20103ffa8f8/src/display/api.js#L137-L144
