### ISSUE TITLE
Pdf header of page

### ISSUE THREAD

**Issue by Thj007** [mozilla/pdf.js#9374]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. I want to known the header of page and bottom of page，how can I known

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Thj007** [comment]
header of page

**Comment by yurydelendik** [comment]
Closing as incomplete.
