### ISSUE TITLE
Some styles in viewer.css do change styles outside of the pdf container

### ISSUE THREAD

**Issue by kaljak** [mozilla/pdf.js#9376]
I embed the pdf viewer on a website.

Some styles in viewer.css do change styles outside of the pdf container.
E.g. https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L22
https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L27
https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L34
https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L41
https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L1381

The selectors should be improved to not change elements outside the pdf.js container.

**Comment by Snuffleupagus** [comment]
Closing as duplicate of issue #6706.
