### ISSUE TITLE
Custom build for the web - Users don't get it

### ISSUE THREAD

**Issue by adadgio** [mozilla/pdf.js#9377]
Configuration:
- Web browser and its version: all
- Operating system and its version: MAC OS
- PDF.js version: 2

I am sorry if this question has already been partially answered, but here it is.

Simply trying to set up a custom webviewer with the following features:
- Simple canvas or svg rendering
- Text layers rendering

and have been through the examples in the components (simpleviewer.js, gulp generic, getting dist-pdfjs, gulp dist-install, as stated everywhere).

Still no example have been able to work, i think files and components architecture are **very** confusing on how and what to included to create a custom web build.

So what is the way to go for a custom implementation and which files to include from the *multiple* files created by gulp int he dist folder ?

Trying to play including with the combined, minified or multiple component files result in `require is not defined error`, `PDF.PageView`, `TextLayerBuilder`depending ont the example i follow.

**QUESTION 1** 

- What are `pdf_viewer.js`, `text_layer_builder`, `pdf.combined.j`s, `pdf.js`(and other comps) and how do they work together/how do they related to each other ? 

**QUESTION 2** 

What files to include in the index.html for the following build ?

- Canvas rendering and/or SVG rendering
- Text layer just like in the main example

Just this... just this...

**Comment by sliceofbytes** [comment]
+1

**Comment by horacioj** [comment]
+10

**Comment by horacioj** [comment]
Call me lazy... by I just want a simple (not full of features) viewer. It would be great if the release file (pdfjs-xxxx-dist.zip) includes working versions of the examples, besides the main viewer (/web/viewer.html).

**Comment by dschissler** [comment]
For me everything breaks down when I try to gain access to the text builder functionality.  I've *mostly* been unable to extract that functionality from the full app.  I use pdf.js with a custom viewer that displays single page documents so that they can be streamed over on demand.  The gain access to that functionality I've needed to result to hacky steps and manually editing compiled source.

**Comment by Snuffleupagus** [comment]
*Given the age of this issue, closing it for now.*

If there's still problems here, please open a *new* issue with a detailed description of what you tried and what did/didn't work; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
