### ISSUE TITLE
Default font for UI elements on iOS

### ISSUE THREAD

**Issue by prohtex** [mozilla/pdf.js#9392]
iOS devices display the toolbar elements (page count, zoom level) in Times New Roman rather than the sans-serif default seen on Desktop.

![img_0829](https://user-images.githubusercontent.com/12946938/35244911-a6d41024-ff76-11e7-902d-429b49cc609c.PNG)

**Comment by shishirkulkarni** [comment]
Hello,
My name is Shishir. I am looking for projects where I can make some open source contributions. I was hoping to take up this issue. This issue also affects the current view option available on smaller screens. The fix that I am thinking of is adding a font-family declaration with value `Arial, Sans-Serif`. If this sounds alright and no one is looking at the issue, Can I take this up?

**Comment by prohtex** [comment]
Hi @shishirkulkarni, that would be great!

**Comment by Snuffleupagus** [comment]
Given that it works correctly in Mozilla Firefox (and also in e.g. Google Chrome), this unfortunately looks like a platform/browser specific issue rather than a PDF.js one; hence closing this as WONTFIX.

---

Also, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
