### ISSUE TITLE
Viewer don't load pdf file in iOS 11.2.2 system  

### ISSUE THREAD

**Issue by sardelcn** [mozilla/pdf.js#9393]
Hello,
I'm working in iOS and Android APP using Cordova/Phonegap.

I use following plugins:
"phonegap-version" value="cli-7.1.0"
"cordova-plugin-file" spec="6.0.1"
"cordova-plugin-wkwebview-engine" spec="1.1.4"
"cordova-plugin-whitelist" spec="1.3.3"
cordova-plugin-wkwebview-file-xhr(2.1.1);

Configuration:
Operating system and its version: iOS 1.2.2
PDF.js version: 1.9

iOS Result:
![ios](https://user-images.githubusercontent.com/23129003/35245871-f4967506-ffc4-11e7-8333-45fcce059a3a.PNG)

Android Result:
![android](https://user-images.githubusercontent.com/23129003/35245881-001f31ce-ffc5-11e7-8353-803d5a2f09eb.PNG)

Steps to reproduce the problem:
`

        // Function to read PDF from external server
        var urlpdf='http://www.servicepe.org/test.pdf';
        var pdfjsframe = document.getElementById('pdfViewer'); 
        PDFJS.workerSrc = 'lib/pdf.js/build/pdf.worker.js';
        var oReq = new XMLHttpRequest();
        // Make sure you add the domain name to the Content-Security-Policy <meta> element.
        oReq.open("GET", urlpdf, true);
        // Define how you want the XHR data to come back
        oReq.responseType = "blob";
        oReq.onload = function (oEvent) {
            var blob = oReq.response; // Note: not oReq.responseText
            if (blob) {
                // Create a URL based on the blob, and set an <img> tag's src to it.
                // Or read the data with a FileReader
                var reader = new FileReader();
                reader.readAsArrayBuffer(blob);
                reader.onloadend = function (evt) {
                    pdfjsframe.contentWindow.PDFViewerApplication.open(new Uint8Array(evt.target.result));
                };
            } else alert('we didnt get an XHR response!');
        };
        oReq.send(null);

In Android works, but in iOS the viewer appear, but pdf is not load.
Can you help me please?
Many Thanks.

Carlo

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.9

Is this issue reproducible with the *latest* version of PDF.js, which as of this writing is `2.0.290`?
Does the default viewer, which can be found at https://mozilla.github.io/pdf.js/web/viewer.html, and which always uses the same version work in environment you're testing in?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.9

Is this issue reproducible with the *latest* version of PDF.js, which as of this writing is `2.0.290`?
Does the default viewer, which can be found at https://mozilla.github.io/pdf.js/web/viewer.html, and which always uses the same version work in environment you're testing in?

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided. If iOS provides console message, also provide those. Without any working example, it's hard to find out what's causing this (and I think there are similar issues for this already open).
