### ISSUE TITLE
Form field names with dot are not retrieved correctly

### ISSUE THREAD

**Issue by arnaldof** [mozilla/pdf.js#9394]
I have a form in a PDF with text fields named like: Fx.y (where x and y are integer numbers)

Only "y" is extracted as field id, the rest is missing.

**Comment by yurydelendik** [comment]
Not complete report, please provide all requested information.

**Comment by ArnaldoSovos** [comment]
I'm using this library along with pdf2json.

This is the PDF file, with names like fx.y and others (like f_month)
![image](https://user-images.githubusercontent.com/35730366/35276284-ab2adf3a-0021-11e8-93d2-dabba1365ace.png)


This is the json with field names: id field "2" is not present (belongs to f10.2 maybe?)

![image](https://user-images.githubusercontent.com/35730366/35276382-fe91fece-0021-11e8-82a5-5fbafbb01af6.png)

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md to provide all requested information.

> I'm using this library along with pdf2json.

What is pdf2json?

**Comment by timvandermeij** [comment]
In order to look into this issue, we need at least a PDF document that shows the issue for debugging purposes. Without the actual PDF file, this issue is not actionable. For all we know, it may also be `pdf2json` that is causing issues.

**Comment by timvandermeij** [comment]
Closing until a PDF file is provided for debugging the issue.

**Comment by ArnaldoSovos** [comment]
[test_form_fields.pdf](https://github.com/mozilla/pdf.js/files/1667994/test_form_fields.pdf)
Heres a example pdf, fields are:
address.1
address.2
Country
option.1
option2

**Comment by yurydelendik** [comment]
PDF.js works as expected, getAnnotations() returns the field names specified above:

<img width="916" alt="screen shot 2018-01-26 at 10 20 48 am" src="https://user-images.githubusercontent.com/1523410/35449465-b25d40dc-0282-11e8-9a59-507e7cbe18d3.png">
