### ISSUE TITLE
Could not retrieve text

### ISSUE THREAD

**Issue by Koundi10** [mozilla/pdf.js#9396]
Attach (recommended) or Link to PDF file here:
[scansmpl.pdf](https://github.com/mozilla/pdf.js/files/1654802/scansmpl.pdf)

Steps to reproduce the problem:
1. Could not retrieve text from the pdf

**Comment by Snuffleupagus** [comment]
> Could not retrieve text from the pdf

That PDF file only contains a *scanned* image, but no text; hence the issue as filed is invalid.
Please keep in mind that PDF.js is a PDF *viewer*, and does not contain any kind of OCR functionality.

Closing as answered.
