### ISSUE TITLE
pdfpage random code

### ISSUE THREAD

**Issue by Thj007** [mozilla/pdf.js#9402]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Open Chinese document pages to display random code

What is the expected behavior? (add screenshot)
i want to chinese document pages can show normal,like this
![right](https://user-images.githubusercontent.com/30485600/35366761-00645540-01b6-11e8-863c-20846d266af5.png)

What went wrong? (add screenshot)
![error](https://user-images.githubusercontent.com/30485600/35366743-e7c01740-01b5-11e8-9140-acffce82dcd1.png)
Link to a viewer (
sted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
bbbb

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> 
> Configuration:
> 
>  - Web browser and its version:
>  - Operating system and its version:
>  - PDF.js version:
>  - Is a browser extension:
> 
> Steps to reproduce the problem:
> 
>   1. Open Chinese document pages to display random code
> 

Closing as incomplete, since all the necessary details are missing here (as can be seen above).
