### ISSUE TITLE
Canvas Scale makes drawing disappear

### ISSUE THREAD

**Issue by Mahus1991** [mozilla/pdf.js#9404]
So  I am using PDFjs on an iPad with cordova. Since it's a retin Display I need to scale my canvas with the given DevicePixelRatio.

But when I do drawings or even Colors will relocated and disappear.
Screenhots are provided.

My Code is:

      `var factor = window.devicePixelRatio;

        if (factor > 1)
            factor = 1.7;

        var width = $('#pdfContainer').width();
        var height = $('#pdfContainer').height();

        canvas.width = width;
        var viewport = page.getViewport(width / (page.getViewport((1)).width));
        canvas.width = viewport.width * factor;
        canvas.height = viewport.height * factor;
        $(canvas).css('width', viewport.width);
        $(canvas).css('height', viewport.height);

        if (viewport.height > height) {
            canvas.height = height;
            var viewport = page.getViewport(height / (page.getViewport(1).height));
            canvas.width = viewport.width * factor;
            canvas.height = viewport.height * factor;
            $(canvas).css('width', viewport.width);
            $(canvas).css('height', viewport.height);

        }

        var canvas2 = document.getElementById('PdfData');
        var context2 = canvas2.getContext('2d');
		
		context2.scale(factor,factor)`

Since scaling did not work i tried doing it without scaling but then i can't properly use the TextLayer anymore.

Problem is asked on Stackoverflow:

https://stackoverflow.com/questions/48439734/pdfjs-textlayer-does-not-position-text-correctly

![1pdfjs](https://user-images.githubusercontent.com/8557032/35401426-c48c21b2-01f9-11e8-818d-d9558b72a2b2.png)
![2pdfjs](https://user-images.githubusercontent.com/8557032/35401432-c5c55b8e-01f9-11e8-9d87-6e0bb1491a10.png)

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
