### ISSUE TITLE
Print 100 pages file issue

### ISSUE THREAD

**Issue by ssnrcnpio** [mozilla/pdf.js#9407]
Configuration:
- Web browser and its version:IE 11
- Operating system and its version: Win 7
- PDF.js version:1.10.88

I have more then 100 pages of **horizontal** pdf, 
View file is ok , but when I press the print button,
Have some problems:
1. the loading 1~100% to print very slow.
2. some times loading to ?% is stop, then IE shot down!
1. specify printing 25 page,but print page 22.
1. printing 1 to 20 pages, the 1 to 15 pages is fine, but the 16 to 20 pages is empty.

I guess whether it is related to memory or insufficient buffer
thanks

**Comment by yurydelendik** [comment]
To print, PDF.js has to render and store each page due the the Web (browser) API limitations. See also [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages) about performance of this. Closing as answered.
