### ISSUE TITLE
How to get page width and height in pdf.js?

### ISSUE THREAD

**Issue by gzliudan** [mozilla/pdf.js#9408]
How to get page width and height for each page in pdf.js?

**Comment by timvandermeij** [comment]
Refer to https://github.com/mozilla/pdf.js/blob/25c7a8c215fe5eccc6a14ab209a8bbea226e9520/examples/learning/prevnext.html#L64. Closing as answered.

**Comment by pavex** [comment]
Try this:
```
pdf.getPage(page_index).then(page => {
	console.log(page.view);
});
```

**Comment by afidosstar** [comment]
@pavex what is unit of coordinates.it is a px or pt ??

**Comment by pavex** [comment]
@afidosstar pixels

**Comment by pengliheng** [comment]
hi, it is means canvas document size.
but i want the whole pagesize...

**Comment by Narretz** [comment]
the data is in `page.view: [left, top, width, height]`

**Comment by asiby** [comment]
Here is an example that I have used. This will scale the PDF viewer to have a full page width. Then, it will resize the canvas to match the full size of the PDF page.

```
pdfDoc.getPage(num).then(function(page) {
    canvas.width = document.body.clientWidth;
    let scale = (canvas.width / page.view[2]);
    let viewport = page.getViewport({scale: scale});
    canvas.height = page.view[3] * scale;
    
    // Render PDF page into canvas context
    var renderContext = {
      canvasContext: ctx, // Initialized in a higher scope using: ctx = canvas.getContext('2d');
      viewport: viewport
    };
    var renderTask = page.render(renderContext);

    // etc.
}
```

**Comment by sebastian-schmitt** [comment]
also take a look at this piece of code (the input parameter is expected to be a page):
https://github.com/mozilla/pdf.js/blob/46e4a305ebb4a2ce9078e0ffbbc5451fafaf2bf7/web/ui_utils.js#L331

**Comment by gzliudan** [comment]
Thanks.
