### ISSUE TITLE
pdf font error

### ISSUE THREAD

**Issue by Thj007** [mozilla/pdf.js#9413]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 63.0.3239.84
- Operating system and its version: window 8.1, window 10
- PDF.js version:  using your official demo project
- Is a browser extension:no

Steps to reproduce the problem:
1. Just load attached pdf
2.

What is the expected behavior? (add screenshot)
![right](https://user-images.githubusercontent.com/30485600/35480622-3ef23ea0-044d-11e8-9e7e-15340600bc26.png)

What went wrong? (add screenshot)
![error](https://user-images.githubusercontent.com/30485600/35480627-4eb3589c-044d-11e8-9b1f-74461ee3ab15.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[老年食养食疗.pdf](https://github.com/mozilla/pdf.js/files/1670962/default.pdf)

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Just load attached pdf

There's no PDF file attached to this issue.

**Comment by Thj007** [comment]
[老年食养食疗.pdf](https://github.com/mozilla/pdf.js/files/1670959/default.pdf)

**Comment by SehyunPark** [comment]
I think the Chinese character itself has more than 2 bytes than any other characters, which caused trouble while converting it.

**Comment by Thj007** [comment]
What I can do ?

**Comment by Thj007** [comment]
This phenomenon occurs only when the Pdf file is displayed

**Comment by Snuffleupagus** [comment]
> What I can do?

Fix the PDF file, by embedding all the fonts in the PDF file itself (as is required by the PDF specification when using non-standard fonts).
Unless you've got the fonts in question installed locally, then even Adobe Reader cannot display the file properly; see the following screen-shot (with an error message saying that the font cannot be found/loaded).

![issue9413](https://user-images.githubusercontent.com/2692120/35483466-a532631c-0442-11e8-91d3-5ce0b3234e76.png)

**Comment by Thj007** [comment]
I found that, then What should I do? Can I turn it into a song?
![tip](https://user-images.githubusercontent.com/30485600/35490521-186011b6-04db-11e8-8a4c-4b0a3793a3a3.png)

**Comment by timvandermeij** [comment]
Closing since the PDF file does not properly embed its fonts and even Adobe Reader (the reference implementation) cannot render it, so there is not much we can do.
