### ISSUE TITLE
bad XRef entry

### ISSUE THREAD

**Issue by abasan1** [mozilla/pdf.js#9418]
hello

I have problems with rendering of the attached PDF file. When I open it using the official viewer at http://mozilla.github.io/pdf.js/web/viewer.html I get the following error:

`PDF.js v2.0.303 (build: 55e3f97a)
Message: bad XRef entry`

this file is generated from an application and I can open that  in adobe reader.
I hope pdf.js can open this file.

[Drawing2.pdf](https://github.com/mozilla/pdf.js/files/1676637/Drawing2.pdf)

thank's

**Comment by THausherr** [comment]
Ghostscript cannot open it, PDFBox cannot open it, Chrome build in pdf viewer can open it.

The file has /Root 1 0 R/Info 18 0 R

At 1 0 o there is the /Info ... at 18 0 o there is "1560". The real root (document calalog) is at 2 0 o. There has been some incremental saving done here, and it went wrong. If you created this file then you might want to contact Aspose support.
