### ISSUE TITLE
The PDF generated by the wkhtmltox tool previews with PDF.JS, and the Chinese font will have a problem

### ISSUE THREAD

**Issue by chineseITMonkey** [mozilla/pdf.js#9422]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome : Version 63.0.3239.132 (Official Build) (64-bit)
- Operating system and its version:Windows 10 x64
- PDF.js version:1.9.426
- Is a browser extension:No

Steps to reproduce the problem:
1. Using the wkhtmltox tool generated by the HTML PDF, preview with PDF.JS, Chinese font will have a problem, display incomplete
2.Open PDF with Adobe, Chinese display normal

What is the expected behavior? (add screenshot)
![2](https://user-images.githubusercontent.com/32893827/35604036-305b99ec-067b-11e8-90e5-ca9b0fbeb279.png)

What went wrong? (add screenshot)
![1](https://user-images.githubusercontent.com/32893827/35603917-b1d2229e-067a-11e8-9557-88af9d4e326a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Without access to the PDF file in question, the issue will be closed as incomplete.

**Comment by Thj007** [comment]
PDFJS.cMapUrl = './static/my-module/cmaps/'
        PDFJS.cMapPacked = true

**Comment by Thj007** [comment]
你的有出现乱码吗？

**Comment by Thj007** [comment]
因为缺少字体

**Comment by timvandermeij** [comment]
Closing since this issue is incomplete.
