### ISSUE TITLE
Get Pdf Dict data

### ISSUE THREAD

**Issue by LubenZA** [mozilla/pdf.js#9429]
Good day,

My document has 'Info' and 'Root' dictionaries which I need to access.
I am using: pdf.worker.js, pdf.js, and viewer.js (pulled from git June 2017)

I've read this issue but it doesn't help my case:
https://github.com/mozilla/pdf.js/pull/5117

Any help would be greatly appreciated.

**Comment by LubenZA** [comment]
This is how I solved it.
In pdf.worker.js:
    infoDict = this.xref.trailer.get('Info');
    console.dir(infoDict); //displays contents of object
    console.log("getting docInfo : " + infoDict.map.whateverDictField);

**Comment by rehmat11872** [comment]
how to generate pdf from the dict of javascript?
