### ISSUE TITLE
pdf.js报错，不能使用相同的canvas进行渲染操作。使用不同的画布或确保以前的操作被取消或完成。

### ISSUE THREAD

**Issue by pmjhcf** [mozilla/pdf.js#9430]
连续点击下一页，重复生成canvas报错。怎么解决？Uncaught (in promise) Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.

**Comment by Snuffleupagus** [comment]
As the error message explains, you need to use a *new* `canvas` for every render operation rather than re-use an existing one; please see PR #8519 and issue #5636 for additional details.

Closing as answered.
