### ISSUE TITLE
PDFDocumentLoadingTask.onProgress not work in IE9

### ISSUE THREAD

**Issue by blitheinsz** [mozilla/pdf.js#9438]
`pdfApplication = PDFJS.getDocument(opt.url);
        
pdfApplication.onProgress = function(progressData) {
            var progressNum = (Number(progressData.loaded) / Number(progressData.total)) * 100;
            console.log(progressNum + '%');
}`

Chrome,  firefox  is OK,
console.log:    1%,  3%, 11% ...........,   100%;

but in  IE9,
only console.log:   100%;

**Comment by Snuffleupagus** [comment]
With PDF.js version `2.0`, we'll no longer support IE9 (nor older browsers in general); hence closing as invalid.
