### ISSUE TITLE
Request failed with status 404

### ISSUE THREAD

**Issue by ppimple** [mozilla/pdf.js#9445]
In Firefox i have facing below warnings from pdfjs and some clients pdf is not visible

*Issues:
1)Source map error: request failed with status 404
Resource URL: https://direct.morningstar.com/research/js/pdfjs-helper/compatibility-6cda4c3c9a.js
Source Map URL: compatibility.js.map

2)Source map error: request failed with status 404
Resource URL: https://direct.morningstar.com/research/js/pdfjs-lib/pdf-f22ff1c654.js
Source Map URL: pdf.js.map

3)Source map error: request failed with status 404
Resource URL: https://direct.morningstar.com/research/js/intl/dist/Intl-63ad5aed70.min.js
Source Map URL: Intl.min.js.map

4)Source map error: request failed with status 404
Resource URL: https://direct.morningstar.com/research/js/pdfjs-lib/pdf.worker.js
Source Map URL: pdf.worker.js.map
Attach (recommended) or Link to PDF file here:

*Versions:
-OS: "Windows 7"
-Browser: "Firefox Quantum 58.0.1 (64-bit)"
-pdf.js: "mozilla/pdf.js#^1.10.88",

What is the expected behavior? (add screenshot)
-> Expected to Load pdf without warnings
What went wrong? (add screenshot)
-> Showing above warnings 4 warnings. (refer *Issues)

**Comment by Rob--W** [comment]
Have you tried uploading the source maps to the server?

**Comment by ppimple** [comment]
Yes

**Comment by Rob--W** [comment]
If you did then there should not be any 404 errors. Check whether they are at the right place.

**Comment by timvandermeij** [comment]
This does not look like a PDF.js problem, but rather a server configuration one, so I'm closing this issue.
