### ISSUE TITLE
Mass removal of Ci, Cr, Cc, and Cu

### ISSUE THREAD

**Issue by amccreight** [mozilla/pdf.js#9449]
I just landed a patch to mass remove definitions of Ci, Cr, Cc and Cu in bug 1432992:
  https://hg.mozilla.org/integration/autoland/rev/b38d59f71915
These are automatically defined on chrome scopes now. There are 5 pdfjs files affected by these changes.

**Comment by Snuffleupagus** [comment]
This is currently blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1230369, and the release of an updated version of https://www.npmjs.com/package/eslint-plugin-mozilla, such that we can upstream these changes without lots of `no-undef` ESLint errors.

**Comment by brendandahl** [comment]
@Standard8 Do you know when a new release will be put on npm?

**Comment by Standard8** [comment]
@brendandahl Sorry for the delay, I meant to do that yesterday (I also thought that the definitions had already been published).

I'm currently trying to push, but npm publish is not doing what is says.... I'll figure it out with their support or something, and update this when I know.

**Comment by Standard8** [comment]
@Snuffleupagus @brendandahl npm publish decided to work today with a new version (0.8.1) so you should be able to update to that now.
