### ISSUE TITLE
l72 in network.js displaying warning in Chrome 64.0.3282.140 (32-bit) Windows

### ISSUE THREAD

**Issue by idevtech** [mozilla/pdf.js#9451]
When loading a page referencing pdfjs.js Chrome reports the following:

The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
supportsMozChunkedClosure @ network.js:71
_typeof2 @ network.js:61
__w_pdfjs_require__ @ bootstrap b5fe8ab6eb949fc98816:19
_typeof @ pdf.js:34
__w_pdfjs_require__ @ bootstrap b5fe8ab6eb949fc98816:19
Object.defineProperty.value @ bootstrap b5fe8ab6eb949fc98816:65
(anonymous) @ bootstrap b5fe8ab6eb949fc98816:65
webpackUniversalModuleDefinition @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:10

**Comment by Snuffleupagus** [comment]
That's only a warning, and it can be safely ignored; see e.g. https://github.com/mozilla/pdf.js/issues/6306#issuecomment-130416712.

Closing as answered.
