### ISSUE TITLE
save parsing or conversion works of last time for next time’s usage

### ISSUE THREAD

**Issue by redstoneleo** [mozilla/pdf.js#9452]
It happens frequently that we need to open a pdf file a second time to finish reading it, in order to make pdf.js load pdf fast when loading the same pdf file a second time, I suggest pdf.js to save those common tasks such as parsing or conversion of last time for next time’s usage.

**Comment by Snuffleupagus** [comment]
Given the lack of details, closing as a duplicate of issue #5720.

*For future reference:* Please make sure than you provide the details requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md), and that you read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) before opening an issue.
