### ISSUE TITLE
PDF viewer steals keydown events

### ISSUE THREAD

**Issue by kaljak** [mozilla/pdf.js#9455]
I embed the pdf viewer on a website.

Some eventlisteners should not be added on window element but on the container element.
E.g.: The pdf viewer is changing the pages if the cursor buttons are pressed on the website.
https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1416

The eventlisteners (wheel, click, keydown) should be added to the container element.

**Comment by Snuffleupagus** [comment]
The default viewer was created as the UI for the PDF viewer that's included in Firefox, and for browser extensions within the project; please refer to e.g. https://mozilla.github.io/pdf.js/getting_started/.
As such, the viewer wasn't really designed to be used stand-alone; hence I'd suggest embedding the viewer in an `iframe` to avoid these issues.

Closing as answered.
