### ISSUE TITLE
Pdf is loaded only once? iOS

### ISSUE THREAD

**Issue by darkotuning** [mozilla/pdf.js#9457]
I'm making an ionic application where I use pdf.js, but there is a problem on the iOS platform when I want to look at pdf again. Pdf is loaded only once. Did anyone have this kind of problem? Thank you

**Comment by timvandermeij** [comment]
We have not heard of that before, but the issue lacks most required details (as asked for in the issue template) in order to be actionable, so I'm closing this as invalid for now.
