### ISSUE TITLE
First page is mixed with the last page

### ISSUE THREAD

**Issue by TyDraniu** [mozilla/pdf.js#9462]
Could you take a look on this file. The first page is mixed with the last page.

[cb7e7bd2362328f37fe97dc8dff151a3.pdf](https://github.com/mozilla/pdf.js/files/1706865/cb7e7bd2362328f37fe97dc8dff151a3.pdf)

Configuration:
- Firefox Nightly 60
- Windows 7

**Comment by Snuffleupagus** [comment]
Closing as duplicate of issue #269.
