### ISSUE TITLE
PDF.js doesn't work in IE9 and IE10

### ISSUE THREAD

**Issue by jazzy-em** [mozilla/pdf.js#9467]
**Configuration:**
- IE 11 in emulation mode (IE9/IE10)
- Windows 8
- PDF.js version: last

**Steps to reproduce the problem:**
1. Open demo page (https://mozilla.github.io/pdf.js/web/viewer.html) in IE11
2. Press F12 and change mode to IE10 (or IE9)

**What is the expected behavior?**
PDF.js works correctly. According https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support IE9/IE10 are supported.

**What went wrong?**
PDF.js doesn't load the document. There are some errors in console.

Does PDF.js still support IE10/IE9?

**Comment by jazzy-em** [comment]
Tested also real IE9, the same situation.

**Comment by Snuffleupagus** [comment]
> According https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support IE9/IE10 are supported.

That information is accurate for the *latest* official release, which can be found at https://github.com/mozilla/pdf.js/releases.

For the (upcoming) release of PDF.js version `2.0`, see https://github.com/mozilla/pdf.js/projects/5, we'll no longer support older browsers such as e.g. IE 9/10.

Closing as answered.

**Comment by jazzy-em** [comment]
@Snuffleupagus Thanks for clarifying and quick response

**Comment by dep-darkLonely** [comment]
@jazzy-em  why pdf.js v1.9.426 not supprot IE9？what should I do to run IE9？
[
![image](https://user-images.githubusercontent.com/30953224/39174227-af21c22a-47d9-11e8-91af-48b99e566876.png)
](url)
