### ISSUE TITLE
Landscape printing 

### ISSUE THREAD

**Issue by engineoss** [mozilla/pdf.js#9469]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:

IE11, Edge, FireFox

- Operating system and its version:

Windows 10

- PDF.js version:

? It's included in CGDevtools

- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

PDF Should be printed in Landscape

What went wrong? (add screenshot)

Only chrome prints fine in landscape, all others print in A4!,
Only Chromes adds a additional empty page at the end

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by engineoss** [comment]
[
[Uploading Printen logboek portal.pdfHi…]()
](url)

Hi forgot a file to show, the first page is how Acrobat shows the file when downloaded, also printing is fine, just 1 page.

Then you get Chrome, printin is fine (landscape) but an additional page. Then we get IE 11, Edge and FireFox, all Show correct but fail when printing landscape

Eric

**Comment by timvandermeij** [comment]
Closing since this is fixed by #12023.
