### ISSUE TITLE
Pdf scanned at 600dpi does not load

### ISSUE THREAD

**Issue by kavisherlock** [mozilla/pdf.js#9474]
Attach (recommended) or Link to PDF file here: 
[pdf600dpi.pdf](https://github.com/mozilla/pdf.js/files/1717166/pdf600dpi.pdf)

Configuration:
- Web browser and its version: Safari, Chrome (latest)
- Operating system and its version: iOS 11.2 (on iPad and iPhone)
- PDF.js version: 1.10.97 (or whatever's on https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the pdf.js demo page on an iPad/iPhone (https://mozilla.github.io/pdf.js/web/viewer.html)
2. Upload the above pdf (or any other pdf scanned at 600 dpi)

What is the expected behaviour? (add screenshot)
Pdf loads (the screenshot is from desktop browser)
<img width="1679" alt="screen shot 2018-02-12 at 11 25 55 am" src="https://user-images.githubusercontent.com/23285466/36110242-8e85f0ec-0fe7-11e8-931e-37c9ff5630ff.png">

What went wrong? (add screenshot)
Pdf does not load and gives the following: warning in the console "Canvas area exceeds the maximum limit (width * height > 16777216)."
The issue is because the pdf was scanned at 600 dpi from an A4-size page, making the canvas area 600 * 8.5 * 600 * 11, which is indeed greater than 16777216. This works properly on my desktop browsers, but not on iPad or iPhone.
iPad:
![img_0252](https://user-images.githubusercontent.com/23285466/36110019-e0a74bce-0fe6-11e8-84ee-86cbc8611032.PNG)

iPhone:
![img_0641](https://user-images.githubusercontent.com/23285466/36110020-e0b9e4be-0fe6-11e8-84fa-a47c7ebf4512.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by uncleramsay** [comment]
Hi, is there any update on this issue? I'm facing the same problem.

I see that a PR was opened, but was never merged - is there any guidance on how we can deal with this issue?

Thanks

**Comment by lorkel** [comment]
Also facing this issue - is there any way to set the maximum canvas size?

**Comment by KeiBontakun** [comment]
I got the same issue with current pdf.js demo page.
My Mac is a bit old: MacOS 10.11.6(El Capitan) with Safari 11.2.

**Comment by amit777** [comment]
Just testing PDFJS and this PDF loaded fine for me with the online demo which seems to be 

```
const pdfjsVersion = '2.7.90';
const pdfjsBuild = '6728c8fa6';
```

**Comment by marco-c** [comment]
Dupicate of #6741.
