### ISSUE TITLE
can we  disable all functionality allowing copy, printing, and share

### ISSUE THREAD

**Issue by Demokumar** [mozilla/pdf.js#9476]
I want to disable all functionality allowing copy, printing, and share and also disable presentation mode

**Comment by Rob--W** [comment]
You can create a custom viewer and paint the PDF on a canvas. See https://github.com/mozilla/pdf.js/tree/master/examples for examples (the helloworld is very minimal and is a good start).

There is no 100% way to prevent users from copying the content of the PDF though... Even if you completely lock down the screen, a user could just grab their smartphone and take a picture of the screen.

**Comment by timvandermeij** [comment]
Moreover, there is the `disableTextLayer` preference (https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L13), but as indicated it's only making it harder to copy, not impossible. Closing as answered.

**Comment by Demokumar** [comment]
is it possible to directly remove secondaryToolbarButton from the viewer
