### ISSUE TITLE
Unexpected server response (401) while retrieving PDF 

### ISSUE THREAD

**Issue by menahel4u** [mozilla/pdf.js#9478]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Version 53.0.2785.116 m
- Operating system and its version: windows server 2008 R2 standard
- PDF.js version:
- Is a browser extension: pdf viewer Version: 2.0.301

Steps to reproduce the problem:
 click on a link to a pdf attachment

What is the expected behavior? (add screenshot) to see a pdf preview

What went wrong? (add screenshot) i got the following error:

PDF.js v2.0.301 (build: fd242ad2)
Message: Unexpected server response (401) while retrieving PDF "http://localhost:8081/Miracle/ViewAttachment.aspx?guid=29b7899e15f144b5af1473b4ca91e6d8".

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
thank you

**Comment by timvandermeij** [comment]
Response status 401 happens when the request in unauthorized. It's a problem in your local configuration, either your application that requires authentication or CORS is not configured properly. Since there is no more information provided, I'm closing this as answered.
