### ISSUE TITLE
Trying to understand use of viewer.html?file=   

### ISSUE THREAD

**Issue by carducci000** [mozilla/pdf.js#9487]
I understand you'd require a file to be on the same server as the viewer/pdf.js file in order to render within the viewer.  

What I'm trying to do is stream an octet stream from a WebAPI back to Javascript, then load the bytes into the viewer.  Is this possible, and if so, could someone please point me in the direction of detailed examples that are necessary?  Debugging is unclear also...I need to enable debugging in my querystring in order to debug, or is that something else?

**Comment by Rob--W** [comment]
Have you seen https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer ?

Here is the documentation for `PDFViewerApplication.open`:
https://github.com/mozilla/pdf.js/blob/a89071bdefb90733fc2e671fcca61f6d03964e04/web/app.js#L707-L716

**Comment by timvandermeij** [comment]
Using the `PDFViewerApplication.open` call is indeed the correct way to do this and should allow you open a PDF file using raw binary data (use typed arrays). Closing as answered.

**Comment by capegreg** [comment]
I need an example usage for PDFViewerApplication. It just blows up!

var pdfjsLib = window['pdfjs-dist/build/pdf'];
pdfjsLib.PDFViewerApplication.open(pdfData);
