### ISSUE TITLE
how to disable right click (contextmenu) inside iframe in pdf js

### ISSUE THREAD

**Issue by Jsurya1** [mozilla/pdf.js#9488]
Is there a way to disable the right click event (contextmenu) on the pdf.

I tried the following code,

`$("#viewer").on("contextmenu", function (e) {
	return false;
});`

**Comment by timvandermeij** [comment]
I think you need to use `e.preventDefault()` (see e.g., https://github.com/mozilla/pdf.js/blob/538dda1096b36d76d75af9eb63a3675fedbe2d19/web/ui_utils.js#L371). Closing as answered since this is out of scope for PDF.js.

**Comment by Jsurya1** [comment]
Thanks
