### ISSUE TITLE
The library does not render some Unicode characters

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#9495]
Attach (recommended) or Link to PDF file here:
[CHIR-CHIR-MENU.compressed.1.pdf](https://github.com/mozilla/pdf.js/files/1735715/CHIR-CHIR-MENU.compressed.1.pdf)

Configuration:
- Web browser and its version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
- Operating system and its version: Windows 7
- PDF.js version: 2.0.0 (latest)
- Is a browser extension: no

Steps to reproduce the problem:
1.  Render the attached PDF with the library.

What is the expected behavior? (add screenshot)
![1](https://user-images.githubusercontent.com/18655020/36364821-79e3abb4-1557-11e8-9668-e8f071681c12.png)

What went wrong? (add screenshot)
![2](https://user-images.githubusercontent.com/18655020/36364855-abae8f92-1557-11e8-9045-746a28ff063a.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://3dflipbook.net/

**Comment by Snuffleupagus** [comment]
*There should be an error printed in the console, explaining why it doesn't work correctly and how to fix it.*

You need to include the CMap files, and set the following options accordingly
https://github.com/mozilla/pdf.js/blob/75dc2bbd359990ebb1c1484f204acf66c3cb8221/src/display/global.js#L101-L112
See how that's done in e.g. the `simpleviewer` components example
https://github.com/mozilla/pdf.js/blob/75dc2bbd359990ebb1c1484f204acf66c3cb8221/examples/components/simpleviewer.js#L27-L30

Closing as answered.
