### ISSUE TITLE
Corrupted print output when printing PDF with font ligatures

### ISSUE THREAD

**Issue by richcocks** [mozilla/pdf.js#9500]
[Attach (recommended) or Link to PDF file here:
](url)

[Firefox PDFjs Test Pages.pdf](https://github.com/mozilla/pdf.js/files/1741009/Firefox.PDFjs.Test.Pages.pdf)

Configuration:
- Firefox (multiple versions)
- Windows 10
- PDF.js: 2.0.288 (and others)

Steps to reproduce the problem:
1. Print the attached Test Pages pdf to a printer or print to file (pdf)

What is the expected behavior? (add screenshot)
Headers are printed without font corruption

What went wrong? (add screenshot)
Headers and footers are corrupted on multiple pages. This appears to be related to font ligatures. Some pages are rendered as canvas elements are are unaffected but others are rendered without the correct fonts. Attached here is a copy of one that has been printed to file from firefox in this way. Different computers experienced different corruption (at seemingly random) even just printing the same document at different computers or even the same computers at different times.

It appears to be related to font-ligatures, and has been reproduced in comic sans and calibri which are both installed the system.

[Firefox PDFjs Test Pages Output.pdf](https://github.com/mozilla/pdf.js/files/1741008/Firefox.PDFjs.Test.Pages.Output.pdf)

**Comment by gpcf** [comment]
related: #9721

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
