### ISSUE TITLE
Strange Glyphs Displayed in Particular Screen Sizes / Zoom Levels

### ISSUE THREAD

**Issue by jmarks1992** [mozilla/pdf.js#9502]
Attach (recommended) or Link to PDF file here:
[HB0141.pdf](https://github.com/mozilla/pdf.js/files/1742278/HB0141.pdf)

Configuration:
- Web browser and its version: Chrome 63.0.3239.132
- Operating system and its version: Mac OSX 10.13.2
- PDF.js version: v1.9.426
- Is a browser extension: No

What is the expected behavior? (add screenshot)
The expected behavior is rendering the PDF attached to this issue.

What went wrong? (add screenshot)
When loading the page, the PDF.js viewer looked like this screenshot. Upon resizing the page or changing the zoom level of the PDF, the text rendered correctly.

![screen shot 2018-02-20 at 6 19 25 pm](https://user-images.githubusercontent.com/5679099/36454694-0a053bb8-166b-11e8-8256-632b36cf8765.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.7.345` in Firefox Nightly 86.

> Web browser and its version: Chrome 63.0.3239.132
> Operating system and its version: Mac OSX 10.13.2

Given the age of both the browser and PDF.js versions, not to mention that the screen-shot shows a *custom* default viewer, I'd suggest closing this issue.

**Comment by timvandermeij** [comment]
WFM too now, so let's close this as fixed.
