### ISSUE TITLE
IE 11 - Header/Footer cutted off

### ISSUE THREAD

**Issue by cuffahd** [mozilla/pdf.js#9503]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: IE 11 version 11.909.15063.0
- Operating system and its version: Win10 
- PDF.js version: Last one (Issue happening on the DEMO)
- Is a browser extension:

Steps to reproduce the problem:
1. Go to the DEMO page ( https://mozilla.github.io/pdf.js/web/viewer.html ) using IE11
2. Print the demo

What is the expected behavior? (add screenshot)
The demo should print the entire header and footer.
What went wrong? (add screenshot)
The demo prints the header and footer cutted off.
![header footer](https://user-images.githubusercontent.com/19753635/36483509-1da2d164-16f5-11e8-9004-95b5d92c5853.JPG)

The image attached is not from the DEMO, but is happening in the demo.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
