### ISSUE TITLE
PDF.js Does Not Work with SeaMonkey

### ISSUE THREAD

**Issue by DavidRoss** [mozilla/pdf.js#9506]
Windows 7 Ultimate SP1 (x64)
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 SeaMonkey/2.49.2
pdf.js 2.0.389

Today, I updated from pdf.js 2.0.305 tp 2.0.389.  On a Web page that contained a link to a PDF file, I selected that link.  I could only get the option to download the file instead of displaying the file in my browser window.  I have reverted to 2.0.305.  

A test Web page is at http://www.rossde.com/test/test_pdf.html

**Comment by timvandermeij** [comment]
As indicated in the README:

```
The extension may also work in Seamonkey, provided that it is based on a Firefox version as above [..], but we do not guarantee compatibility.
```

Moreover, note that 2.0 is not officially released yet and recent changes in the add-on make it only work for Nightly versions of Firefox (see https://github.com/mozilla/pdf.js/pull/9433). Closing as answered.
