### ISSUE TITLE
New text selection algorithm

### ISSUE THREAD

**Issue by arturadib** [mozilla/pdf.js#951]
As has been pointed out in #937 we need a new text selection algorithm, because of (a) performance, and (b) character code incompatibility.

Let's collect some thoughts here on how we can improve our algorithm.

/cc @ironymark

**Comment by zhsc** [comment]
Is there an existing effort that can be found somewhere for the "SVG approach" that @saebekassebil mentioned 12/24/2011?  The blocking bug in FF does seem to be resolved as of 06/29/2013 (https://bugzilla.mozilla.org/show_bug.cgi?id=292498)  Thanks

**Comment by timvandermeij** [comment]
Well, we have an SVG backend already (https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js), but it needs some more work. See #5159 and http://107.21.233.14:8877/f4c875977c84e08/web/viewer.html#svg=true to test it.

**Comment by timvandermeij** [comment]
Closing as resolved as the current text selection algorithm is much more performant now. Open a new issue for any new ideas for improvement.
