### ISSUE TITLE
Warning: FormatError: Required "loca" table is not found in Internet Explorer

### ISSUE THREAD

**Issue by jurgentreep** [mozilla/pdf.js#9514]
Attach (recommended) or Link to PDF file here:
http://edelman.amsterdam/wp-content/uploads/Terms_Conditions_NL.pdf

Configuration:
- Web browser and its version: Internet Explorer 11 version 11.248.16299.0
- Operating system and its version: Windows 10 Home version 1709 build 16299.248
- PDF.js version: 2.0.391
- Is a browser extension: no

Steps to reproduce the problem:
1. Render the pdf in internet explorer

What is the expected behavior? (add screenshot)
The pdf renders like it does in Chrome
![Image of pdf in Chrome](https://i.imgur.com/ZNZdws4.png)

What went wrong? (add screenshot)
The pdf doesn't render the font correctly and renders all sorts of random characters.
![Image of pdf in Internet Explorer](https://i.imgur.com/SG725th.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
If the information provided isn't enough I'm willing to create an example.

**Comment by DanDeMicco** [comment]
+1 seeing same issue

**Comment by janpe2** [comment]
This may be related to issue #9516.

https://github.com/mozilla/pdf.js/blob/97faedba0cd74d9f5899c2ffa33bb20103ffa8f8/src/core/fonts.js#L1319-L1321

The polyfilled `Array.prototype.incudes` always returns false, so all TrueType tables are skipped.

**Comment by timvandermeij** [comment]
Could someone check if `Array.prototype.includes()` is provided by IE11? The polyfill only kicks in if `Array.prototype.includes()` is undefined, but perhaps IE11 ships its own (broken) version instead.

**Comment by janpe2** [comment]
IE11 does not seem to provide that function
![kuva](https://user-images.githubusercontent.com/26090208/36755492-13bc6b90-1c15-11e8-9d47-44dba0a6d644.png)

If I open the PDF.js demo viewer, then I get:
![kuva](https://user-images.githubusercontent.com/26090208/36755532-2a583b2c-1c15-11e8-94f9-f0d73ef21ee5.png)

**Comment by Snuffleupagus** [comment]
It appears that both `Array.includes` *and* `String.includes` are affected here.
Since https://github.com/zloirock/core-js are used for in number of existing polyfills in `compatibility.js`, it might be an issue with how we're attempting to load these *specific* ones in https://github.com/mozilla/pdf.js/blob/97faedba0cd74d9f5899c2ffa33bb20103ffa8f8/src/shared/compatibility.js#L128-L144
