### ISSUE TITLE
IE10 Some PDFs with images (especially PNG are not working)

### ISSUE THREAD

**Issue by mazikwyry** [mozilla/pdf.js#9515]
Attach (recommended) or Link to PDF file here:
[dupaa.pdf](https://github.com/mozilla/pdf.js/files/1763202/dupaa.pdf)

**Configuration:**
- Web browser and its version: IE 10.0.9200.17609
- Operating system and its version: Windows 7
- PDF.js version: 2.0.395
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Download attached PDF.
2. Copy it to `/examples/learning`
3. Change url variable in `/examples/learning/prevnext.html` to `var url = './dupaa.pdf';`
4. run `npm install pdfjs-dist --save`
5. run `npm install`
6. run `gulp server`
7. In IE10 go to `http://localhost:8888/examples/learning/prevnext.html`

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/1079965/36733840-297e5c9c-1bd2-11e8-9c36-fbb776ea9dfe.png)

**What went wrong?**
PDF page is not rendering. 
Error in console: `SCRIPT438: Object doesn't support property or method 'set'`

![image](https://user-images.githubusercontent.com/1079965/36728624-aaf1af92-1bc1-11e8-9c19-ee35ef63f444.png)

**What is causing the issue?**
After investigation I found a problem in `canvas.js`

https://github.com/mozilla/pdf.js/blob/25bbff46927cb91cb72f62cbd681a20535d914f6/src/display/canvas.js#L524

The problem starts https://github.com/mozilla/pdf.js/blob/25bbff46927cb91cb72f62cbd681a20535d914f6/src/display/canvas.js#L463 where in IE10 `createImageData` returns `DataImage` instance, but `data` is `CanvasPixelArray` where the code assumes it is `Uint8ClampedArray`. Then it uses `set` method which is not implemented for `CanvasPixelArray`.

**How can I workaround**

Add this to your code:
```javascript
if (window.CanvasPixelArray) {
  CanvasPixelArray.prototype.set = function(arr) {
      var l=this.length, i=0;

      for(;i<l;i++) {
          this[i] = arr[i];
      }
  };
}
```
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since IE10 is no longer supported since PDF.js 2.0.

**Comment by bestvist** [comment]
so cool!!
```
if (window.CanvasPixelArray) {
  CanvasPixelArray.prototype.set = function(arr) {
      var l=this.length, i=0;

      for(;i<l;i++) {
          this[i] = arr[i];
      }
  };
}
```
