### ISSUE TITLE
wrong polyfill with IE11 ?

### ISSUE THREAD

**Issue by cvlmtg** [mozilla/pdf.js#9516]
<img width="649" alt="schermata 2018-02-27 alle 15 11 26" src="https://user-images.githubusercontent.com/6401008/36733374-ac53b5ec-1bd0-11e8-8950-e4f42273c3d4.png">

Configuration:
- Web browser and its version: IE11
- Operating system and its version: Windows 7
- PDF.js version: not sure, but probably >= 2.0.0
- Is a browser extension: no

Steps to reproduce the problem:
1. open https://mozilla.github.io/pdf.js/web/viewer.html
2. try to use Array.prototype.includes()

What is the expected behavior? (add screenshot)

[1,2].includes(1) should return true, not false

**Comment by yurydelendik** [comment]
fwiw, the polyfill comes from core-js library

**Comment by cvlmtg** [comment]
@yurydelendik unless I completely misunderstood something, according to the core-js author the fault is not in his polyfill:

https://github.com/babel/babel/issues/7419

(please look the last comment on that issue)
