### ISSUE TITLE
The selected range jumps in chrome when drag to blank(correct in edge or firefox)

### ISSUE THREAD

**Issue by jayzhen521** [mozilla/pdf.js#9517]
It's not easy to select the range that I want to select.
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome(seems that appear only in Chrome)
- Operating system and its version:64.0.3282.167
- PDF.js version:v2.0.391
- Is a browser extension:No

Steps to reproduce the problem:
1. go to the site: https://mozilla.github.io/pdf.js/web/viewer.html
2. use mouse drag to select text until mouse point to the blank point of web.

What is the expected behavior? (add screenshot)
![right](https://user-images.githubusercontent.com/36140554/36759360-09b280fc-1c52-11e8-9218-b712f2ca9f84.jpg)

What went wrong? (add screenshot)
![wrong](https://user-images.githubusercontent.com/36140554/36759178-7ffe762c-1c51-11e8-95cb-1d8965d0e286.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Let's dupe this to #9843, since it appears to be similar enough.
