### ISSUE TITLE
Arabic characters in text-layer are not correct

### ISSUE THREAD

**Issue by XiMiXgit** [mozilla/pdf.js#9523]
When I render a text-layer over a canvas the characters of the text-layer do not match exactly with the text rendered in the canvas.
Here I do not mean the position, but the content. So e.g. if I copy out the text, it is not exactly like the original text.

In the provided screenshot.png you can see both layers simultan. The dark text is the one rendered in the canvas, the light grey one is the text rendered in the text-layer.
I marked a position where the text differs.

When I examine the Byte-Stream of the document I see that there are from time to time short sequences where the order of the characters is in the wrong way. The first char is the last one.
There are also short sequences where there are complete different characters. For more details see file UnicodeCharComparring.txt

I think that this has to do something with arabic ligatures. But I am not sure because I am not confirm with the arabic language.

Appendix:
-	Screenshot.png
-	UnicodeCharComparring.txt
-	Yoga-ar.pdf
![screenshot](https://user-images.githubusercontent.com/13855914/36894588-2bfa375c-1e0c-11e8-987d-7ba264b7e9a8.png)
[UnicodeCharComparring.txt](https://github.com/mozilla/pdf.js/files/1774652/UnicodeCharComparring.txt)
[Yoga-ar.pdf](https://github.com/mozilla/pdf.js/files/1774653/Yoga-ar.pdf)

**Comment by Snuffleupagus** [comment]
Most likely fixed by PR #13424 (as far as I can tell not speaking Arabic, and without the issue clearly stating what page(s) the problem occur at).
