### ISSUE TITLE
bind javascript events

### ISSUE THREAD

**Issue by issy123** [mozilla/pdf.js#9527]
How can I bind javascript events on this:

https://mozilla.github.io/pdf.js/web/viewer.html

I want to bind events on when it's done rendering and when there is something else being rendered.
Because I want to create pdfjs annotations on top of the rendered pdf file.

**Comment by timvandermeij** [comment]
You can listen for events fired on the event bus (such as https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/web/app.js#L155).

**Comment by issy123** [comment]
@timvandermeij I am talking about the prebuild version, not from sources.
```
document.addEventListener("resize",function(){console.log("resize pdfjs!");});
document.addEventListener("pagechanging",function(){console.log("pagechanging pdfjs!");});
```

this doesn't work

**Comment by diwakar1911** [comment]
set "eventBusDispatchToDOM": true in viewer.js why isn't anyone telling this!

**Comment by alexandrzavalii** [comment]
@diwakar1911 Thanks!
how do you set this setting?

**Comment by irokhes** [comment]
@issy123 how did you finally solve this? I need to do the same thing (catch events using the prebuild version)

thanks!

**Comment by ismail-codinglab** [comment]
I think I changed the event listener names like so:

```javascript
document.addEventListener("scalechange",function(){console.log("resize pdfjs!");});
document.addEventListener("pagechange",function(){console.log("pagechanging");});
```

**Comment by technicaltitch** [comment]
["The `eventBusDispatchToDOM` option/preference is deprecated, add event listeners to the EventBus instance rather than the DOM."](https://github.com/mozilla/pdf.js/blob/master/web/ui_utils.js#L797)

How do I know when the eventBus will exist? I'm trying to log each event by adding at [viewer.js:220](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L220):

`window.PDFViewerApplication.eventBus.addEventListener("documentload", function () { console.log('documentload fired') });`

Which raises:

> Uncaught TypeError: Cannot read property 'eventBus' of undefined at HTMLDocument.webViewerLoad

**Comment by technicaltitch** [comment]
["The `eventBusDispatchToDOM` option/preference is deprecated, add event listeners to the EventBus instance rather than the DOM."](https://github.com/mozilla/pdf.js/blob/master/web/ui_utils.js#L797)

How do I know when the eventBus will exist? I'm trying to log each event by adding at [viewer.js:200](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L200):

```javascript
  app.PDFViewerApplication.eventBus.addEventListener(
    "documentload",
    function() {
      console.log("documentload fired");
    }
  );
```

And similarly (`pdfjsWebApp.PDFViewerApplication.eventBus.addEventListener`) at [viewer.js:219](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L219)

These raise:

> Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null at attachEventListeners (viewer.js:189)

**Comment by technicaltitch** [comment]
I have the deprecated method working.

I added *above* the run call

```javascript
      window.PDFViewerApplicationOptions.set("disablePreferences", true);
      window.PDFViewerApplicationOptions.set("eventBusDispatchToDOM", true);
      attachEventListeners();
      app.PDFViewerApplication.run(config);
```

Then `attachEventListeners` just attaches to the global events:

```javascript
function attachEventListeners() {
  console.log("attachEventListeners called");
  document.addEventListener("documentload", function() {
    console.log("documentload fired");
  });
  document.addEventListener("pagerendered", function() {
    console.log("pagerendered fired");
  });
  document.addEventListener("textlayerrendered", function() {
    console.log("textlayerrendered fired");
  });
  document.addEventListener("pagechange", function() {
    console.log("pagechange fired");
  });
  document.addEventListener("pagesinit", function() {
    console.log("pagesinit fired");
  });
  document.addEventListener("pagesloaded", function() {
    console.log("pagesloaded fired");
  });
  document.addEventListener("scalechange", function() {
    console.log("scalechange fired");
  });
  document.addEventListener("updateviewarea", function() {
    console.log("updateviewarea fired");
  });
  document.addEventListener("find", function() {
    console.log("find fired");
  });
  document.addEventListener("attachmentsloaded", function() {
    console.log("attachmentsloaded fired");
  });
  document.addEventListener("sidebarviewchanged", function() {
    console.log("sidebarviewchanged fired");
  });
  document.addEventListener("pagemode", function() {
    console.log("pagemode fired");
  });
  document.addEventListener("namedaction", function() {
    console.log("namedaction fired");
  });
  document.addEventListener("presentationmodechanged", function() {
    console.log("presentationmodechanged fired");
  });
  document.addEventListener("outlineloaded", function() {
    console.log("outlineloaded fired");
  });
```

I would still love to do this properly using the eventBus, if anyone has any ideas, as I'll be building this out substantially.

**Comment by Snuffleupagus** [comment]
Regarding https://github.com/mozilla/pdf.js/issues/9527#issuecomment-604157830, please see the *first* section of https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage for the correct way of waiting for the viewer to load/initialize; hence waiting for e.g. the "documentloaded" event is done like so:
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplication.initializedPromise.then(function() {
    PDFViewerApplication.eventBus.on("documenloaded", function(event) {
      console.log("The document has now been loaded");
    });
  });
});
```

**Comment by technicaltitch** [comment]
Enormous thanks @Snuffleupagus and sorry I have corrected a typo in [my comment](https://github.com/mozilla/pdf.js/issues/9527#issuecomment-604157830).

If I add your code above (or below) the [`app.PDFViewerApplication.run(config)`](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L199) call the event handler is never called.

My theory is that if I search across the repo for `webviewerloaded` the only match is [viewer.js#L214](https://github.com/mozilla/pdf.js/blob/master/web/viewer.js#L214), so it *seems* to be raised if and only if `PDFJSDev.test("PRODUCTION") && PDFJSDev.test("GENERIC")` and on my development machine I am running the `!PDFJSDev.test("PRODUCTION")` branch of that `if` statement. Should the `webviewerloaded` event be raised in `!PRODUCTION && GENERIC` environments too?
