### ISSUE TITLE
JsFiddle Demos do not work

### ISSUE THREAD

**Issue by N-M** [mozilla/pdf.js#9529]
Example on http://jsfiddle.net/pdfjs/9engc9mw/ provided in [interactive examples](http://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) does not work. 
`PDFJS is not defined` error is presented

**Comment by yurydelendik** [comment]
Updated, waiting for cache to catch up

**Comment by yurydelendik** [comment]
@timvandermeij can you verify if I used proper API to access worker settings?

**Comment by timvandermeij** [comment]
Looks good to me! Closing as fixed.

**Comment by Rob--W** [comment]
@yurydelendik The jsfiddle example imports PDF.js using `window['pdfjs-dist/build/pdf']`.
That is very unidiomatic. There is also a global symbol called `pdfjsDistBuildPdf`, which would be more natural, but still the name is a bit verbose. Can you replace the former with the latter, at least?

While writing documentation (#9528), I came across the fact that there is no short and obvious name for to access the library. Before submitting a documentation update, I have opened a new ticket to request a better name at #9545.
