### ISSUE TITLE
Cannot open pdf in chrome

### ISSUE THREAD

**Issue by drgkt** [mozilla/pdf.js#9531]
Attach (recommended) or Link to PDF file here:
open ebill pdf
Configuration:
- Web browser and its version: chrome 49
- Operating system and its version: xp sp2
- PDF.js version: PDF.js v2.0.301 (build: fd242ad2)
- Is a browser extension: yes

Steps to reproduce the problem:
1. just click on link
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing since no PDF file is attached. Without the PDF file, we cannot do anything to help debugging this, unfortunately. This can be reopened once a PDF file is uploaded.
