### ISSUE TITLE
Ho to catch text selection event in the pdf viewer?

### ISSUE THREAD

**Issue by crisciunas** [mozilla/pdf.js#9532]
I need to catch the text selection event from another js file and include the selected text in a form on my website. I have tried many suggestions, including document.addEventListener('textlayerrendered', function (event) but it doesn't work. Is it possible to be done from another js file?

**Comment by timvandermeij** [comment]
I don't think we dispatch any event on text selection. Perhaps you can work with https://developer.mozilla.org/en-US/docs/Web/Events/selectionchange, but that is out of scope for PDF.js itself.
