### ISSUE TITLE
Using Xamarin, am unable to open pdf downloaded to temp folder

### ISSUE THREAD

**Issue by Mason11987** [mozilla/pdf.js#9535]
Attach (recommended) or Link to PDF file here: Not opening with any pdf I've tested, from blank ones to larger ones.

Configuration:
- Web browser and its version:
- Operating system and its version: Android emulator for Xamarin
- PDF.js version: Not sure how to find this.
- Is a browser extension: no

Steps to reproduce the problem:
1. Using this setup here: https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/display-pdf/
2. But the file I'm downloading is being stored in the temporary folder provided by System.IO.Path.GetTempPath(), which is `/data/user/0/com.duke_energy.MobileCAS/cache/fileName.PDF`.

What is the expected behavior? (add screenshot)

The pdf viewer to load, and the pdf to load inside of it

What went wrong? (add screenshot)

the pdf does not load, screenshot attached

![image](https://user-images.githubusercontent.com/1509065/37034785-688f36fe-2118-11e8-853a-9da04c77e49c.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): not hosted.

I believe the problem is either A) pdfjs can't access the data/user folder, or for some reason I'm passing the path of that folder improperly into the viewer.html file.

The code involved is below:

`
            protected override void OnElementChanged(ElementChangedEventArgs<WebView> e)
            {
            base.OnElementChanged(e);

            var customWebView = Element as CustomWebView;
            if (File.Exists(customWebView.Uri))
            {
                //"/data/user/0/com.duke_energy.MobileCAS/cache/ADMN - NGD - NPM - CHAPTER 11 - 003 - ISSUED.PDF"
                if (e.NewElement != null)
                {
                    Control.Settings.AllowUniversalAccessFromFileURLs = true;
                    Control.LoadUrl(string.Format("file:///android_asset/pdfjs/web/viewer.html?file={0}", string.Format("file:///{0}", WebUtility.UrlEncode(customWebView.Uri))));
                }
           }
        }
`

Thanks!

**Comment by Mason11987** [comment]
After a week of having issues and then posting it, I figured it out 15 minutes later, heh.


This is my new code:

            base.OnElementChanged (e);

            var customWebView = Element as CustomWebView;
            if (File.Exists(customWebView.Uri))
            {
                Java.IO.File myFile = new Java.IO.File(customWebView.Uri);
                Java.Net.URL url = myFile.ToURI().ToURL();
                if (e.NewElement != null)
                {
                    Control.Settings.AllowUniversalAccessFromFileURLs = true;
                    Control.LoadUrl($"file:///android_asset/pdfjs/web/viewer.html?file={url}");
                }
            }

I believe the problem may have been the prefix and/or that I was encoding the slashes in the path, instead of just the filename.

**Comment by VishnuPrabhu** [comment]
@Mason11987 Thanks man, you are a genius. Searching for this for more than a week and found this. This is working great
