### ISSUE TITLE
Full PDF doc loaded before single page could be rendered

### ISSUE THREAD

**Issue by mustafa0x** [mozilla/pdf.js#9537]
I understood from the FAQ that [pdf.js only downloads what it needs](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range), however, using the [sample code from the docs](https://mozilla.github.io/pdf.js/examples/#interactive-examples), I noticed, via Chrome DevTools' network panel, that the entire document was loaded first, even though a single page was drawn.

Some things I tried to no avail:
- Run it on my server.
- Run it on another pdf file.
- Run `qpdf --linearize` on that pdf file.
- Try HEAD, which gave the same results but the doc _was_ downloaded in 64kb chunks.

My use case is displaying specific pages from very long PDF files (1000+ pages). If **pdf.js** is not the right tool please let me know.

Related issues: #1108, #2719, #1923, #1375, #2470, #3461, #6104.

**Comment by timvandermeij** [comment]
The default range chunk size is https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/src/display/api.js#L37; only PDF files larger than that will use range (chunked) loading. The server must support range requests and the PDF file must be optimized for web (linearized). If that is the case, then range loading should work just fine for your use case.

**Comment by mustafa0x** [comment]
Thanks @timvandermeij!

See: http://159.89.108.117/pdfjs-1.10.88/web/load-single.html. I'm using the PDF spec: http://159.89.108.117/PDF32000_2008.pdf.

In HEAD it rendered the first page when ~4.5MB was downloaded, but it did continue to download the entire file (22.5MB). See: http://159.89.108.117/pdf.js-master/examples/helloworld/load-single.html

**Comment by mustafa0x** [comment]
I ran `pdfinfo` on `PDF32000_2008.pdf`, and it told me `Optimized: no`, so I downloaded a PDF which _was_ optimized (http://159.89.108.117/annual_report_2009.pdf) but the results didn't change

**Comment by mustafa0x** [comment]
@timvandermeij Mind giving some input on this?

**Comment by timvandermeij** [comment]
Your example does use range requests (indicated by response codes 206 in the network tab of the console), so that looks fine to me. I think you may want to disable auto-fetching; see: https://github.com/mozilla/pdf.js/blob/e0fb18a339fac7f065f9d9165c634d3a895d3ac5/src/display/api.js#L175

>  Disable pre-fetching of PDF file data. When range requests are enabled PDF.js will automatically keep fetching more data even if it isn't needed to display the current page. The default value is `false`. NOTE: It is also necessary to disable streaming, see above, in order for disabling of pre-fetching to work correctly.

**Comment by pravid** [comment]
Will this work in case of pdf stored on other domain?
My pdf is stored on cloud server, all the headers are set properly. It loads the pdf completely before rendering. I'm using normal function,
`pdfjsLib.getDocument({
		url: DEFAULT_URL,
		password: "abc",
		disableStream: false,
		disableAutoFetch: true,		
	})`

Am I missing any parameters here, how can I specify 'range' here?

**Comment by Hao-Wu** [comment]
> Will this work in case of pdf stored on other domain?
> My pdf is stored on cloud server, all the headers are set properly. It loads the pdf completely before rendering. I'm using normal function,
> `pdfjsLib.getDocument({ url: DEFAULT_URL, password: "abc", disableStream: false, disableAutoFetch: true, })`
> 
> Am I missing any parameters here, how can I specify 'range' here?

Hi @pravid , Did you make it work with pdf being stored on other domains?

**Comment by pravid** [comment]
@Hao-Wu , Yes in a way. I used cors proxy to sort this issue.
So, while setting default_url, I had to prefix proxy path to it.
Check this link : [https://github.com/Rob--W/cors-anywhere](https://github.com/Rob--W/cors-anywhere) (Node JS proxy server)
For more details on CORS : https://humanwhocodes.com/blog/2010/05/25/cross-domain-ajax-with-cross-origin-resource-sharing/

Hope this helps.

**Comment by shivamsharmabtp** [comment]
Hi, @pravid i am loading pdf from different source using url /pdfjs/web/viewer.html?file=<pdf-url> . It is working fine but loading entire pdf before rendering it. Is it possible to start rendering pdf before complete load? Thank you.

**Comment by pravid** [comment]
Yes, check above answer for details. https://github.com/mozilla/pdf.js/issues/9537#issuecomment-508490851
I used CORS to solve this loading issue.
You need to set up nodejs proxy server (ex. https://myproxyserver.com) and
while calling your pdf, set file path as,
` var pdfPath = "https://myproxyserver.com/" + "https://mypdffilepath.com/my.pdf";`

Hope this helps.

**Comment by shivamsharmabtp** [comment]
Sorry, i didn't get. For example you can look at this link of my website [https://www.collegeeks.com/read?doc=cs11001-programming-and-data-structure-lecture-slides-week1&v=1xh60cj30ok13m7qwc](link) . It loads pdf from gcp bucket and perfectly renders it. But the only issue is, it loads complete pdf before rendering it. For large pdfs it takes some time and the reader is blank for minutes. As i understood i should use _https://myproxyserver.com/https://storage.googleapis.com/..._  pdf url instead of _https://storage.googleapis.com/..._  which is working fine.. i am not able to understand how this will help and how to implement it. I hope you understood my doubt. Thank you.

**Comment by pravid** [comment]
Have you setup your node js server?
Pls go through the link to understand how CORS works. They have also given sample files to check for. https://github.com/Rob--W/cors-anywhere (Node JS proxy server)
'https://myproxyserver.com' will be the url of your server you set. 
Also do note that, your pdf also should be optimized.
