### ISSUE TITLE
Have any way to customize title without request

### ISSUE THREAD

**Issue by lichunbin814** [mozilla/pdf.js#9539]
Hello everyone, I'm using viewer.html with version v1.9, have any way to customize title without request's fileName or title of pdf from the stream because I can't control backend it sometimes returns a random number, so I want to dynamic set it from javascript by quertyParams(e.x. title), like below:

http://mozilla.github.io/pdf.js/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf&title=MyTitle

its title will show **MyTitle**

**Comment by timvandermeij** [comment]
You can use the following method for that: https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/web/app.js#L629
