### ISSUE TITLE
PDF viewer unable to open certain PDFs

### ISSUE THREAD

**Issue by sampdf** [mozilla/pdf.js#9540]
Attach (recommended) 
[Problem.pdf](https://github.com/mozilla/pdf.js/files/1793688/Problem.pdf)
r Link to PDF file here:

Configuration:
- Web browser and its version: FireFox version 58.0.2 (64-bit) 
- Operating system and its version:  Windows 8.1 Enterprise
- PDF.js version:  Using the the inbuilt viewer for Firefox which I beleive is PDF.js
- Is a browser extension: No extension

Steps to reproduce the problem:
1.  Just viewing the attached PDF in Firefox results in the error.

What is the expected behavior? (add screenshot) PDF should be displayed.

What went wrong? (add screenshot) 
A blank screen in viewer is displayed. The console has the below error

details: "FormatError: page dictionary kids object is not an array" message: "page dictionary kids object is not an array" name: "UnknownErrorException" stack: "UnknownErrorExceptionClosure@resource://pdf.js/build/pdf.js:441:37\n@resource://pdf.js/build/pdf.js:435:38\n__w_pdfjs_require__@resource://pdf.js/build/pdf.js:45:12\n@resource://pdf.js/build/pdf.js:4998:23\n__w_pdfjs_require__@resource://pdf.js/build/pdf.js:45:12\n@resource://pdf.js/build/pdf.js:88:18\n@resource://pdf.js/build/pdf.js:26:18\nwebpackUniversalModuleDefinition@resource://pdf.js/build/pdf.js:24:59\n@resource://pdf.js/build/pdf.js:16:11\n"

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
*The following is **completely** untested, and is based solely on a very quick look at the actual PDF file.*

```diff
diff --git a/src/core/obj.js b/src/core/obj.js
index c7058689..8854ce9e 100644
--- a/src/core/obj.js
+++ b/src/core/obj.js
@@ -501,20 +501,35 @@ var Catalog = (function CatalogClosure() {
           }
 
           count = currentNode.get('Count');
-          // Cache the Kids count, since it can reduce redundant lookups in long
-          // documents where all nodes are found at *one* level of the tree.
-          var objId = currentNode.objId;
-          if (objId && !pageKidsCountCache.has(objId)) {
-            pageKidsCountCache.put(objId, count);
-          }
-          // Skip nodes where the page can't be.
-          if (currentPageIndex + count <= pageIndex) {
-            currentPageIndex += count;
-            continue;
+          if (Number.isInteger(count) && count >= 0) {
+            // Cache the Kids count, since it can reduce redundant lookups in
+            // documents where all nodes are found at *one* level of the tree.
+            var objId = currentNode.objId;
+            if (objId && !pageKidsCountCache.has(objId)) {
+              pageKidsCountCache.put(objId, count);
+            }
+            // Skip nodes where the page can't be.
+            if (currentPageIndex + count <= pageIndex) {
+              currentPageIndex += count;
+              continue;
+            }
           }
 
           var kids = currentNode.get('Kids');
           if (!Array.isArray(kids)) {
+            // Prevent errors in corrupt PDF documents that violate the
+            // specification by *inlining* Page dicts directly in the Kids
+            // array, rather than using indirect objects (fixes issue9540.pdf).
+            if (isName(currentNode.get('Type'), 'Page') ||
+                (!currentNode.has('Type') && currentNode.has('Contents'))) {
+              if (currentPageIndex === pageIndex) {
+                capability.resolve([currentNode, null]);
+                return;
+              }
+              currentPageIndex++;
+              continue;
+            }
+
             capability.reject(new FormatError(
               'page dictionary kids object is not an array'));
             return;
diff --git a/web/pdf_link_service.js b/web/pdf_link_service.js
index 91df4632..2e4662f0 100644
--- a/web/pdf_link_service.js
+++ b/web/pdf_link_service.js
@@ -354,6 +354,9 @@ class PDFLinkService {
    * @param {Object} pageRef - reference to the page.
    */
   cachePageRef(pageNum, pageRef) {
+    if (!pageRef) {
+      return;
+    }
     let refStr = pageRef.num + ' ' + pageRef.gen + ' R';
     this._pagesRefCache[refStr] = pageNum;
   }
```

**Comment by THausherr** [comment]
Issue created: https://github.com/cjwl/cocotron/issues/14
