### ISSUE TITLE
About IOS opening the PDF problem

### ISSUE THREAD

**Issue by hanyan123** [mozilla/pdf.js#9543]
I come from China.The problem I encountered was that IOS opened the PDF with the electronic signature, PDF content was always loaded, the loading diagram was turning, the content of the PDF was not shown.

**Comment by timvandermeij** [comment]
Closing since most of the required information from the issue template is not provided, in particular an example PDF file to reproduce the issue and the exact browser/OS versions. Note that digital signatures are not supported by PDF.js yet and that's already tracked in a different issue.
