### ISSUE TITLE
Bad end offset on slow connections

### ISSUE THREAD

**Issue by blemaire** [mozilla/pdf.js#9544]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 64.0.3282.186
- Operating system and its version: MacOs HighSierra 10.13.3
- PDF.js version: 1.2.63
- Is a browser extension: No

Steps to reproduce the problem:
1. In chrome network tab, DO NOT check disable cache
2. Throttle network connection to Slow 3G
3. Open PDF file (any file over 200kb)
4. notice Bad end offset Error in the console

**Comment by Rob--W** [comment]
Can't reproduce with the above steps, but when I do the following in Chrome 64, I can reproduce the issue:

1. Clear the cache via `chrome://settings/clearBrowserData`
2. Open the DevTools (optional - I open it to get longer async stack traces).
3. Visit https://mozilla.github.io/pdf.js/web/viewer.html  (currently version 2.0.426 @ https://github.com/mozilla/pdf.js/tree/58cda43b294027399f1de486783a2858b0838da4)
4. Look at the DevTools and observe the following error:

```
Uncaught (in promise) Error: Bad end offset: 65282
    at Object.ChunkedStream_onReceiveData [as onReceiveData] (chunked_stream.js:68)
    at ChunkedStreamManager_onReceiveData [as onReceiveData] (chunked_stream.js:477)
    at chunked_stream.js:328
    at <anonymous>
```

The value of the offset differs for every request.

The long stack trace is:
```
ChunkedStream_onReceiveData	@	chunked_stream.js:68
ChunkedStreamManager_onReceiveData	@	chunked_stream.js:477
(anonymous)	@	chunked_stream.js:328
Promise.then (async)		
ChunkedStreamManager_sendRequest	@	chunked_stream.js:324
ChunkedStreamManager_requestChunks	@	chunked_stream.js:380
ChunkedStreamManager_requestRange	@	chunked_stream.js:403
ensureHelper	@	pdf_manager.js:194
(anonymous)	@	pdf_manager.js:199
NetworkPdfManager_ensure	@	pdf_manager.js:178
BasePdfManager_ensureDoc	@	pdf_manager.js:56
loadDocument	@	worker.js:431
pdfManagerReady	@	worker.js:596
Promise.then (async)		
setupDoc	@	worker.js:637
wphReady	@	worker.js:857
MessageHandler._onComObjOnMessage	@	util.js:1294
```

**Comment by Rob--W** [comment]
I tried again and got "Bad end offset: 32595".

This is definitely a bug in Chrome...

The relevant request headers:
```
GET /pdf.js/web/compressed.tracemonkey-pldi-09.pdf
range:bytes=0-65535
```

The relevant response headers:
```
206 Partial Content (from disk cache)
accept-ranges:bytes
cache-control:max-age=600
Content-Length:32595
Content-Range:bytes 0-32594/32595
content-type:application/pdf
date:Fri, 09 Mar 2018 17:44:17 GMT
expires:Fri, 09 Mar 2018 12:28:39 GMT
last-modified:Thu, 08 Mar 2018 22:27:50 GMT
```

Note that PDF.js requested 65535 bytes, but got only 32595 from the browser. Chrome is at fault here.

**Comment by Rob--W** [comment]
I created a minimal test case and reported the bug upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=820599

This bug probably explains why I often encounter non-loading PDF files in the Chrome extension, that load anyway when I open the DevTools (in my DevTools configuration I have disabled the cache).

Chrome's cache seems unreliable, #9022 is another bug related to caching & range requests.

**Comment by Rob--W** [comment]
The upstream bug has been fixed. @blemaire Can you run Chrome Canary (https://www.google.com/chrome/browser/canary.html) and report whether the issue has been resolved?

**Comment by blemaire** [comment]
Issue resolved using Chrome v67.0.3375.0 5 (Current Canary). Thanks a lot

**Comment by nicolas-schreiber** [comment]
Well, I just tried it with Version 67.0.3379.0 and I still get the `Bad end offset` message.

**Comment by Rob--W** [comment]
@nicolas-schreiber Can you provide an example (URL) where this issue is consistently reproduced, or (if the issue is not easily reproducible), try to capture a NetLog, as described at https://www.chromium.org/for-testers/providing-network-details ?

**Comment by nicolas-schreiber** [comment]
I used following steps (Without developer tools open) in the Canary Version 67.0.3379.0:
1. Clear everything with chrome://settings/clearBrowserData
2. Visit: https://mozilla.github.io/pdf.js/web/viewer.html
3. Open Developer Tools and get following output:
<img width="1780" alt="screen shot 2018-03-26 at 11 49 31" src="https://user-images.githubusercontent.com/34018356/37939491-f835d6a6-319d-11e8-8990-b5e2364990c9.png">

**Comment by Rob--W** [comment]
@nicolas-schreiber I followed the same steps with 67.0.3380.0 and the problem does not occur. Please provide the requested NetLog.

**Comment by nicolas-schreiber** [comment]
I am sorry for the late reply, but now with 67.0.3386.0 I can't replicate the problem anymore.
