### ISSUE TITLE
IOS can't render certain PDFs

### ISSUE THREAD

**Issue by hanyan123** [mozilla/pdf.js#9546]
Configuration:

Web browser and its version: Safari Latest
Operating system and it
s version: iOS 11.1.1
PDF.js version: latest
Steps to reproduce the problem:

Load attached file in any pdf.js renderer or viewer.
What is the expected behavior? (add screenshot)
Rendering of PDF

What went wrong? (add screenshot)
Blank white canvas is shown rather than the pdf.
This only happens on iOS browsers. It works on all browsers for windows and all browsers for MacOS. It also works on Google Chrome on an Android device.

**Comment by Snuffleupagus** [comment]
> Load attached file in any pdf.js renderer or viewer.

There isn't any PDF file attached, hence this issue is (currently) not actionable and will be closed as incomplete.

**Comment by timvandermeij** [comment]
Closing since required information is missing. This can be reopened once it is provided.
