### ISSUE TITLE
PDF's not rendering/printing in Google Chrome latest version 65.0

### ISSUE THREAD

**Issue by Maitri-108** [mozilla/pdf.js#9550]
Configuration:

Chrome 65.0.3325.146 (oficial) (64 bits)
Windows 10 Pro
PDF.js version: 1.8.188

Steps to reproduce the problem:
I updated Version of Google chrome from 63.0.3239.132 TO 65.0.3325.146.
Press print button on pdfjs viewer
What is the expected behavior? 

Printing Pages

What went wrong? (added Screenshot)
![printerror](https://user-images.githubusercontent.com/32386165/37286125-14ce54aa-2627-11e8-9d31-75cb15993d97.png)

Blank pages. Nothing is printed

Additional Notes:

Works as expected in FireFox
Works as expected in IE EDGE 

Does anyone have a solution for this problem please?

Best Regards,
Maitri

**Comment by Nathan143522** [comment]
I am also having this issue, I get an image in the printpreview but it does not print. If I walk through the code after clicking the print button with a breakpoint on onPrintButtonClick_: function() { 
and walk through it, the pdf will print, but if I just click the print button without walking through the code, it does not print. How can I get different results between walking through the code and just clicking print without breakpoints? This issue occured after updating to Chrome 65.

**Comment by Maitri-108** [comment]
Hi,

I solved problem by my self. 

If you are using PDF viewer and Iframe to display Cv or some content, then you need to explicitly give some css to Iframe, SPECIALLY WHEN YOU ARE RUNNING YOUR APPLICATION IN GOOGLE CHROME VERSION 65. 

You need to give css to iframe for example,

<iframe Style="display:block">

This above line solved my problem.

Hope this help you.

Thanks,
Maitri
