### ISSUE TITLE
Nodejs example

### ISSUE THREAD

**Issue by ahmdsolmn** [mozilla/pdf.js#9551]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Nodejs v9
- Operating system and its version: Ubuntu Xenial (16.04LTS)
- PDF.js version: 2.0.0
- Is a browser extension: No

Steps to reproduce the problem:
1. Steps listed in [README.md](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/README.md)

What is the expected behavior? (add screenshot)
Create an image from the `helloworld` pdf

What went wrong? (add screenshot)
Multiple errors were thrown.

Possible fixes:
1) run `gulp dist-install` so now you can require `pdfjs-dist` in the exampe.
2) change `new Canvas()` to `Canvas.createCanvas()` in file  [pdf2png.js](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js)

**Comment by timvandermeij** [comment]
Closing since the example now works. Indeed we changed to using `gulp dist-install` and made other improvements so you can use it again using the steps in the README file.
