### ISSUE TITLE
Hyper link not working in PDFjs

### ISSUE THREAD

**Issue by ravinder-logiciel** [mozilla/pdf.js#9553]
I have a pdf in witch there is a link of website(Google). With PDFjs it now working. Please tell me the reason and solution.

![capture image](https://user-images.githubusercontent.com/15511939/37331977-d7d092fc-267b-11e8-8483-b1030d636b23.png)

**Comment by THausherr** [comment]
Please attach the PDF.

**Comment by ravinder-logiciel** [comment]
[link.pdf](https://github.com/mozilla/pdf.js/files/1806375/link.pdf)

Here is the PDF.

**Comment by THausherr** [comment]
It works for me. BTW, URLs usually start with "https://" and not with "www".

**Comment by timvandermeij** [comment]
This works just fine with the latest viewer at https://mozilla.github.io/pdf.js/web/viewer.html. From the screenshot, it's a custom deployment (not even sure it's PDF.js). Most likely annotations have been disabled there. Closing since support for customized versions of PDF.js is out of scope.
