### ISSUE TITLE
Accessible text flow

### ISSUE THREAD

**Issue by MarioBatusic** [mozilla/pdf.js#9554]
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL
- PDF.js version: Last
- Is a browser extension:

Steps to reproduce the problem:
1. Use a Screen Reader software such as NVDA or JAWS to hear the speech output of the document content.

What is the expected behavior? (add screenshot)
Complete words, sentences and no unlogical new lines caused by deliberate <div>s.
What went wrong? (add screenshot)
Current text output coding causes Screen reader software to break text unnaturally in lines. Every `<div>` means a line of text in the screen reader reading mode in the browser. Navigatin through the text of pdf.js demo by JAWS or NVDA line by line produces e.g. speech output or braille output such as:

T
race

for Trace, and brakes in many occasions a sentence to single words positioned on their own lines.

A possible solution: 
Using `<span>`s instead of `<div>`s and providing appropriate inter-word spacing with blanks (x0020).

Technical:
```
<!-- Original:  -->
<div style="left: 574.5122468749998px; top: 467.7072037109373px; font-size: 8.616399999999999px; font-family: sans-serif;">T</div>
<div style="left: 579.46px; top: 467.707px; font-size: 8.6164px; font-family: sans-serif; transform: scaleX(0.93105);">race</div>

<!-- Optimized: -->
<span style="left: 574.5122468749998px; top: 467.7072037109373px; font-size: 8.616399999999999px; font-family: sans-serif;">T</span><span
style="left: 579.46px; top: 467.707px; font-size: 8.6164px; font-family: sans-serif; transform: scaleX(0.93105);">race</span>
```

CAUTION: Don't let any spaces between "T" and "race".

**Comment by Snuffleupagus** [comment]
> Using `<span>`s instead of `<div>`s and providing appropriate inter-word spacing with blanks (x0020).

Given that `divs` are no longer used since PR #10197, it seems that the issue as filed should actually be fixed now.

(Furthermore, there's also work in progress elsewhere to improve both text-selection and general accessibility.)
