### ISSUE TITLE
Tab order

### ISSUE THREAD

**Issue by MarioBatusic** [mozilla/pdf.js#9557]
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL
- PDF.js version: Last

Steps to reproduce the problem:
1. In the HTML mark-up elements have tabindex attributs set to positive values.

Don't use positive tabindex values such as tabindex="10". By dynamic changes through JavaScript DOM manipulation such as showing and hideng contents, this coding causes inconsistancies and the keyboard focus does not move through the content as expected.

Inplement appropriate ARIA landmark roles to enable screen reader users and users of other ARIA browser add-ons to better navigate in the document content:
* set the role="main" on the parent element for the document content,
* Set the role="navigation" (or `<nav>` tag instead of `<div>`) for the parent element of the navigational toolbar with buttons Back, Forward, etc.

**Comment by marco-c** [comment]
Also filed on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855695.
