### ISSUE TITLE
Case of a PDF with misaligned characters

### ISSUE THREAD

**Issue by luca76** [mozilla/pdf.js#9569]
Here is a case of a PDF with misaligned characters in many slides:

Attach (recommended) or Link to PDF file here: http://foss4g-it2018.gfoss.it/data/20_febbrario/1_Osgeo/01_Brovelli_aime_neteler_OSGeo_It.pdf

Configuration:
- Web browser and its version: Firefox 58
- Operating system and its version: Fedora Linux 27
- PDF.js version: the one built in Firefox 58
- Is a browser extension: no

**Comment by suyasha0** [comment]
I'm unsure if this is an issue with pdf.js itself, because this pdf has misaligned characters on other pdf viewers as well.

**Comment by timvandermeij** [comment]
Closing since this renders exactly the same in PDF.js as in other viewers (such as Evince). The PDF file is not embedding its TrueType fonts, which is not something we can fix.
