### ISSUE TITLE
Is fullscreen mode supported in IE11?

### ISSUE THREAD

**Issue by Ada323** [mozilla/pdf.js#9572]
If yes, are any special configurations necessary to set it up? Thank you!

**Comment by timvandermeij** [comment]
Yes, full screen is only disabled in IE11 if it's embedded in for example an `iframe` (refer to https://github.com/mozilla/pdf.js/blob/538dda1096b36d76d75af9eb63a3675fedbe2d19/web/viewer_compatibility.js#L25). Otherwise it should work.

**Comment by Ada323** [comment]
Thank you for responding so quickly! Ours is in an iframe so that explains the problem.
