### ISSUE TITLE
℞ symbol not rendered correctly

### ISSUE THREAD

**Issue by droidzone** [mozilla/pdf.js#9575]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 65.0.3325.146 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 17.10
- PDF.js version:1.3.5
- Is a browser extension:No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? I need to insert the symbol ℞.

I tried:
`doc.text('℞', 20, 60);`

It is rendered as a single exclamation mark.

**Comment by timvandermeij** [comment]
You're confusing PDF.js with the `jsPDF` library. Please file your issue there instead.
