### ISSUE TITLE
Safari: only one try to print

### ISSUE THREAD

**Issue by hand-coding** [mozilla/pdf.js#9578]
Attach (recommended) or Link to PDF file here:
http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf
_This problem occurs with every documents I tested._

Configuration:
- Web browser and its version: Safari 11.0.3 and Safari Preview r51
- Operating system and its version: macOS 10.13.3
- PDF.js version: 2.5.3
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit the pdf.js live demo at http://mozilla.github.io/pdf.js/web/viewer.html
2. Click the “print“ icon (or command+P)
3. Wait for the modal dialog to show then click “Cancel”
4. Click the “print“ icon again (or command+P)

What is the expected behavior?
The Print window should show a preview for the first page and I should be able to browse all of the 14 pages thumbnails like the first time I tried.

![pdf-js-report-1](https://user-images.githubusercontent.com/37498020/37564395-7e551112-2a95-11e8-9dd1-a9cb5fa6209e.png)

What went wrong?
A modal window appears reading: _This web page ask to be printed. Do you want to proceed?_
_Cancel - Print_

![pdf-js-report-2](https://user-images.githubusercontent.com/37498020/37564412-ddc4739a-2a95-11e8-87fc-32c14b5d6104.png)

Clicking Print shows a one page empty preview

![pdf-js-report-3](https://user-images.githubusercontent.com/37498020/37564434-3585ce4e-2a96-11e8-97d5-2cc77b7266a3.png)

All subsequent tries will fail the same way until the user reload the page.

**Comment by hand-coding** [comment]
That seems to be a Safari printing issue which occurs also with other js library. I’m not sure anybody should spend any time on it.
I decided to implement the “nativePrint” method used by pdf-highlighter.com and described here: https://pdf-highlighter.com/pdfjs-printing-issue-use-browser-support/.
Works well in Safari, Opera, Chrome and Windows Edge.
IExplorer (without plug-in) will use pdf.js print method (as well as Firefox, unfortunately, since FF sees the iframe content as cross-origin, even if it's not, and thus forbid printing).

**Comment by tohvanah** [comment]
How can the native printing in a child iFrame be accomplished with a base64 data URL?

**Comment by hand-coding** [comment]
Please start a new thread.

**Comment by timvandermeij** [comment]
Closing since this is fixed by #12315.
