### ISSUE TITLE
getDocument hangs in Jest/JSDom environment

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#9579]
On PDF.js 2.0.385 and later, running the following simplest example:

```js
pdf.getDocument({ data: arrayBufferData })
  .then(() => console.log('Success'))
  .catch() => console.log('Fail'));
```

runs fine on Node.js, obviously.

Running the same piece in Jest, as in this example (simplified, please ignore the fact the tests should be async):

```js
describe('Test', () => {
  it('does something', () => {
    pdf.getDocument({ data: arrayBufferData })
      .then(() => console.log('Success'))
      .catch() => console.log('Fail'));
  });
}
```

* if `testEnvironment` is set to `"node"`, succeeds.
* if `testEnvironment` is set to `"jsdom"` (default), hangs and never reaches `.then()`.

On PDF.js 2.0.305 and earlier this is not an issue, because you can easily disable workers manually.

Now that there's no way of doing that via config as of #9385, **all projects using PDF.js and Jest/JSDom will be unable to test anything PDF.js-related**. Switching `testEnvironment` to `"node"` is usually not an option as this will cause virtually everything else on front-end to fail.

**Comment by Snuffleupagus** [comment]
*As mentioned in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md):*
For issues with custom implementations, you need to provide access to a complete, and small, runnable example for the issue to be actionable. And please don't assume that people are familiar with various JS frameworks, in this case "Jest".

Without any context or code, the following questions comes to mind:
Are workers supported, and if so have you tried to set the `workerSrc` option and just run tests with workers enabled?
Have you tried using the `workerPort` option to load the worker file? Keep in mind that it's also possible to pass a worker to `getDocument`, see https://github.com/mozilla/pdf.js/blob/0d391daccc2f4e4b9c91268e719bd10fe63a49ae/src/display/api.js#L129-L130

**Comment by wojtekmaj** [comment]
Hi, thanks for your reply. 

Jest is a testing environment. It simulates browser environment using Node/JSDom. This obviously tricks PDF.js into thinking it's working in a browser. This means it begins to load the worker file.

Jest/Node/JSDom environment does not support Workers. I can only rely on poorly written shims, so I'd be better of without any.

I am aware of workerSrc and workerPort options. Nothing that looked promising worked, here's some of the things I've tried:

```js
// 1. Error: terminate not supported (thrown by Worker shim)
pdfjs.GlobalWorkerOptions.workerSrc = require.resolve('pdfjs-dist/build/pdf.worker.js');

// 2. Error: only absolute urls are supported (thrown by node-fetch)
pdfjs.GlobalWorkerOptions.workerPort = new Worker(require.resolve('pdfjs-dist/build/pdf.worker.js'));

// 3. TypeError: e.match is not a function (thrown by Worker shim)
const workerFile = fs.readFileSync(require.resolve('pdfjs-dist/build/pdf.worker.js'));
const workerURL = URL.createObjectURL(new Blob([workerFile]));
pdfjs.GlobalWorkerOptions.workerPort = new Worker(workerURL);

// 4. TypeError: Invalid value used as weak map key
const workerFile = fs.readFileSync(require.resolve('pdfjs-dist/build/pdf.worker.js'));
const workerURL = URL.createObjectURL(new Blob([workerFile]));
pdfjs.GlobalWorkerOptions.workerPort = workerURL;

// 5. Error: terminate not supported (thrown by Worker shim)
const workerFile = fs.readFileSync(require.resolve('pdfjs-dist/build/pdf.worker.js'));
const workerURL = URL.createObjectURL(new Blob([workerFile]));
pdfjs.GlobalWorkerOptions.workerSrc = workerURL;

// 6. TypeError: comObj.addEventListener is not a function
const workerFile = fs.readFileSync(require.resolve('pdfjs-dist/build/pdf.worker.js'));
pdfjs.GlobalWorkerOptions.workerPort = workerFile;

// 7. TypeError: comObj.addEventListener is not a function
import Worker from 'jest-worker';
pdfjs.GlobalWorkerOptions.workerPort = new Worker(require.resolve('pdfjs-dist/build/pdf.worker.js'));

// Or even shenanigans like this:
// 8. 
global.windowBackup = global.window;
global.window = null;
const pdf = await pdfjs.getDocument({ data: pdfFile.arrayBuffer });

page = await pdf.getPage(1);
global.window = global.windowBackup;
```

At this point I really surrendered. This makes me super upset. I wouldn't like to leave my users (react-pdf package, 55k downloads/mo) forever on older version of PDF.js. Everything works perfectly, but I can't give up unit testing :(

Here's what I'm on at the moment:
https://github.com/wojtekmaj/react-pdf/tree/pdfjs-larger-than-2.0.305

This repo is pretty simple to use.
```
npm install
npm run test-jest
```
should do the trick. During the second step you will encounter errors because of PDF.js being misconfigured.

The entry file that all tests are using/I have an issue configuring to disable workers/make them magically working on Node is this one:
https://github.com/wojtekmaj/react-pdf/blob/pdfjs-larger-than-2.0.305/src/entry.jest.js

Any suggestions?

**Comment by wojtekmaj** [comment]
I've managed to deal with it! For those stuck like me, do NOT set `pdfjs.GlobalWorkerOptions.workerSrc` or `pdfjs.GlobalWorkerOptions.workerPort`. Instead, use pdf.worker.entry.js file - simply import it and you're done!

**Comment by p-mcgowan** [comment]
The above solution didn't work for me, instead I had to configure jest to use node instead of jsdom (enabled by default)

Adding this to the top of my spec file solved it
```
/**
 * @jest-environment node
 */
```

**Comment by sem4phor** [comment]
For me none f the above solutions are working. Im using vue-cli with jest tests

**Comment by zzzachzzz** [comment]
This issue is a bit older, and I ran into different problems when running in Jest, though I got it working with a couple solutions:
1. ```The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream`); please use a `legacy`-build instead.```

**Solution:** Install a [polyfill for `ReadableStream`](https://www.npmjs.com/package/web-streams-polyfill), and import it before your test: `import 'web-streams-polyfill/es2018';`

2. `TypeError: _pdfWorker.default is not a constructor`

**Solution:** Conditionally configure the `PdfjsWorker`:
```js
if (process.env.NODE_ENV !== 'test') {
  pdfjs.GlobalWorkerOptions.workerPort = new PdfjsWorker();
}
```
