### ISSUE TITLE
l10n get() not as a promise

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#9582]
is there an option to have this not as a promise?

**Comment by timvandermeij** [comment]
No, we don't have such an option. It is recommended that you use the asynchronous version since it was part of larger changes in #8394. It you really need this to be a synchronous process, you should implement that yourself.

**Comment by Snuffleupagus** [comment]
> It you really need this to be a synchronous process, you should implement that yourself.

I'm not sure if that could even work, since the l10n files are purposely loaded asynchronously; hence the l10n data cannot be assumed to be immediately available.
