### ISSUE TITLE
pdf.js default view to "page width" without using options after the #

### ISSUE THREAD

**Issue by bsoldiers** [mozilla/pdf.js#9583]
hi everyone,

its possible to make pdf.js default view to "page width" but without using options after the
http://mozilla.github.io/pdf.js/web/viewer.html#zoom=page-width

if its possible what should i do?

thanks everyone

**Comment by hand-coding** [comment]
In web/viewer.js line 109
Change `var DEFAULT_SCALE_VALUE = 'auto';`
to `var DEFAULT_SCALE_VALUE = 'page-width';`

**Comment by timvandermeij** [comment]
Closing as answered.
