### ISSUE TITLE
Window resize displaces the currently viewed page

### ISSUE THREAD

**Issue by arunvenu87** [mozilla/pdf.js#9589]
Settings:

Zoom: Page Fit
Hand tool enabled
Browser version:
Chrome - Version 65.0.3325.162 (Official Build) (64-bit)

Steps to reproduce the issue :

Search for a word in pdf
Once the search word is highlighted, Scroll page using hand tool to next page or more.
Resize chrome window to a lower size
Expected Result
The PDF stays in currently viewed page.

Actual Result
PDF moves back to the last search result page

**Comment by ashley-hu** [comment]
I can confirm this issue on Chrome (Version 64.0.3282.186 (Official Build) (64-bit)). I had to resize from full window size to about 1/4 of the original window size before the bug happened.

**Comment by arunvenu87** [comment]
is there any update on this issue?

**Comment by Snuffleupagus** [comment]
> Search for a word in pdf
> Once the search word is highlighted, Scroll page using hand tool to next page or more.
> Resize chrome window to a lower size
> Expected Result
> The PDF stays in currently viewed page.

@timvandermeij This should have been fixed by PR #10220, so I think this can be closed now.
