### ISSUE TITLE
How to implement search functionality in the pdf in Typescript?

### ISSUE THREAD

**Issue by RaviGprec** [mozilla/pdf.js#9591]
Hi There,

I'm using Angular5 to implement PDF viewer with this PDF.JS. 
I'm done with the UI part. I'm unable implement search functionality inside PDF Viewer.

Any suggestions?

Thanks in Advance!!

Regards,
Ravi Kumar

**Comment by timvandermeij** [comment]
Take a look at the example that uses search: https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L58

You can also check how it's done in the default viewer (check `PDFFindController` and `PDFFindBar`).
