### ISSUE TITLE
Safari: cannot to show the pdf document

### ISSUE THREAD

**Issue by elvisqi** [mozilla/pdf.js#9597]
Attach (recommended) or Link to PDF file here:

http://res.wisedu.com/FS/error/safari_cannot_be_shown.pdf

Configuration:
- Web browser and its version:  Safari 11.0.3 (13604.5.6)
- Operating system and its version: macOS 10.13.3
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. upload attachment in viewer on safari
2.

What is the expected behavior? (add screenshot)
![snip20180322_149](https://user-images.githubusercontent.com/3584916/37762580-a7dc5332-2df7-11e8-9087-ed65caa4f8e3.png)

What went wrong? (add screenshot)
![snip20180322_148](https://user-images.githubusercontent.com/3584916/37762508-70154cc4-2df7-11e8-9a88-641d1dc8cf85.png)
cannot shown on safari, but chrome can be shown

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by roinheart** [comment]
这老外看到CJK字符直接自动过滤，所以还是只有我们自己想办法

**Comment by Snuffleupagus** [comment]
This looks like a platform/browser bug (perhaps related to font-loading), rather than a PDF.js one, hence this unfortunately doesn't seem like something that can be fixed *here*.
