### ISSUE TITLE
IE11 to many requests

### ISSUE THREAD

**Issue by sifmaster** [mozilla/pdf.js#9598]
Configuration:
- IE11
- Windows 10
- PDF.js version: latest

I use the PDF.js to display PDF's on our webpage. The problem is, that IE11 send to many requests to the PDF link and Antiloris is blocking the client. (the amount of requests depens on the pdf filesize).

Is this a known issue? is there a fix for this?

Thanks!

**Comment by timvandermeij** [comment]
PDF.js uses chunked loading (range requests) if the server supports it, which is causing many smaller requests instead of one big one. The advantage is that PDF files render faster that way. You can disable this using the `disableRange` option.
