### ISSUE TITLE
TypeError: Cannot read property 'PDFViewer' of undefined (pdfjs-dist ^2.0.419)

### ISSUE THREAD

**Issue by Kanthavel-Securibox** [mozilla/pdf.js#9600]
Configuration:
- Web browser and its version: Chrome 62.0.3202.94
- Operating system and its version: Linux Mint 18.2
- PDF.js version: Issue appears on pdfjs-dist from release 2.0.419 onwards. No issue with 2.0.402.
- Is a browser extension: No

I'm building a react app having pdfjs-dist as one of the dependencies.
I guess some of the modification/ refactoring done on 2.0.419 (namely the api_compatibility.js logic) fails to play along well with webpack v3 
~~~~ 
TypeError: Cannot read property 'PDFViewer' of undefined
(anonymous function)
/home/trabbagghiu/securibox/parse/parse-react-widget/dist/parse-widget.js:416
  413 | 
  414 | function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
  415 | 
> 416 | if (!_pdf_viewer.PDFJS.PDFViewer || !_pdf_viewer.PDFJS.getDocument) {
  417 |   alert('Please build the pdfjs-dist library using\n' + '  `gulp dist-install`');
  418 | }
  419 | 
View compiled
__webpack_require__
/home/trabbagghiu/securibox/parse/parse-react-widget/dist/parse-widget.js:21
  18 | /******/ 		};
  19 | /******/
  20 | /******/ 		// Execute the module function
> 21 | /******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
  22 | /******/
  23 | /******/ 		// Flag the module as loaded
  24 | /******/ 		module.l = true;
 ~~~~

**Comment by Snuffleupagus** [comment]
> Issue appears on pdfjs-dist from release 2.0.419 onwards. No issue with 2.0.402.

If you update the core files, i.e. `pdf.js` and `pdf.worker.js`, then you need to update the code that's calling the core library as well to avoid issues like these.
See the *latest* version of e.g. the `simpleviewer` component example, available at https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js

**Comment by timvandermeij** [comment]
Closing based on the answer above.

**Comment by moffsugita** [comment]
me too. did you resolve?
