### ISSUE TITLE
Extracting images with node.js "Warning: Native JPEG decoding failed -- trying to recover: Image is not defined"

### ISSUE THREAD

**Issue by svenyonson** [mozilla/pdf.js#9603]
Unable to get this to work. Looking at other issues here, I tried adding 'disableNativeImageDecoder', but to no avail.
Error for each page is: "Warning: Native JPEG decoding failed -- trying to recover: Image is not defined"

Note: If I cut and paste this code into an interactive node.js session, it works because of `var Image = require('canvas').Image;`. But it doesn't help when running the following code as a script.

```
var PDFJS = require('pdfjs-dist');
var Canvas = require('canvas');
var Image = require('canvas').Image;

function proc(filename) {

	var fs = require('fs');
	var extractDir = 'extract/';

	if (!fs.existsSync(extractDir)){
	    fs.mkdirSync(extractDir); 
	}
	if (!fs.existsSync(filename)) {
		console.log("File not found: "+filename);
		return;
	}

    (async () => {
    	try {
			var doc = await PDFJS.getDocument({url: filename, disableNativeImageDecoder: true});
			var pages = doc.pdfInfo.numPages;

			for (let i=1; i <= pages; i++) {
				var page = await doc.getPage(i);
				var ops = await page.getOperatorList();
				for (let j=0; j < ops.fnArray.length; j++) {
			        if (ops.fnArray[j] == PDFJS.OPS.paintJpegXObject) {
			            var op = ops.argsArray[j][0];
			            img = page.objs.get(op);
			            // Fix resolution
              			var scale = img.width / page.pageInfo.view[2];
              			var viewport = page.getViewport(scale);
			            var canvas = new Canvas(img.width, img.height);
    					var context = canvas.getContext('2d');

    					await page.render({canvasContext: context, viewport: viewport});
              			
					    var imageData = canvas.toBuffer();
					    var ordinal = ("00" + i).slice (-3);
				    	fs.writeFile(extractDir+'image-'+ordinal+'.png', imageData, function (error) {
					        if (error) {
					          throw error;
					        }
					    });
			        }
				}
			}
			console.log('done');
			
    	} catch(e) {
    		console.log(e);
    	}

    })();
}

proc("testfile.pdf");
```

**Comment by Snuffleupagus** [comment]
> I tried adding 'disableNativeImageDecoder', but to no avail.

Please note that that parameter was deprecated in PR #8350, and was subsequently removed in PR #8982.

For environments without native `Image` support, such as e.g. Node.js, you need to set the `nativeImageDecoderSupport` option (to `'none'` in this case) in `getDocument` to avoid these kind of errors; please refer to the *latest* API docs in https://github.com/mozilla/pdf.js/blob/97faedba0cd74d9f5899c2ffa33bb20103ffa8f8/src/display/api.js#L137-L144

**Comment by svenyonson** [comment]
Thanks for the quick reply - that fixed the warning, but the extraction still fails:
 - I added `nativeImageDecoderSupport: 'none'` to getDocument
 - This causes the operator list to include `OPS.paintImageXObject` instead of `OPS.paintJpegXObject`
 - I changed the test to `OPS.paintImageXObject`
 - `page.render` now fails with "ReferenceError: HTMLElement is not defined"

**Comment by svenyonson** [comment]
Tim, not sure why this is closed. I was not trying to use `font-face`, so I don't think I would need to pass this switch, but I tried it anyway. While I no longer get "Image not defined", using the switch `nativeImageDecoderSupport: 'none'` causes the error "HTMLElement is not defined". This simple example fails:

```
var PDFJS = require('pdfjs-dist');
var Canvas = require('canvas');
const {promisify} = require('util');
const fs = require('fs');
const writeFile = promisify(fs.writeFile); 

function proc(filename) {

    (async () => {
    	try {
			var doc = await PDFJS.getDocument({url: filename, nativeImageDecoderSupport: 'none', disableFontFace: true});
			var pages = doc.pdfInfo.numPages;

			for (let i=1; i <= pages; i++) {
				var page = await doc.getPage(i);
				var ops = await page.getOperatorList();

				for (let j=0; j < ops.fnArray.length; j++) {
			        if (ops.fnArray[j] == PDFJS.OPS.paintJpegXObject || ops.fnArray[j] == PDFJS.OPS.paintImageXObject) {
			            var op = ops.argsArray[j][0];
			            var img = page.objs.get(op);
              			var scale = img.width / page.pageInfo.view[2];
              			var viewport = page.getViewport(scale);
			            var canvas = new Canvas(img.width, img.height);
    					var context = canvas.getContext('2d');

    					await page.render({canvasContext: context, viewport: viewport});
              			
					    var imageData = canvas.toBuffer();
					    var ordinal = ("00" + i).slice (-3);
					    await writeFile('image-'+ordinal+'.png', imageData);
			        }
				}
			}
			console.log('done');
    	} catch(e) {
    		console.log(e);
    	}
    })();
}

proc("test.pdf");

```

**Comment by svenyonson** [comment]
Here is a small test file (4 pages)
[test.pdf](https://github.com/mozilla/pdf.js/files/1866432/test.pdf)

**Comment by timvandermeij** [comment]
The `HTMLElement is not defined` error is fixed by #9588, so there should be no remaining issues here, which is why it was closed (automatically). If after applying #9588 and #9618 there are still problems, please open a new issue.

**Comment by shartoo** [comment]
Hi there @svenyonson ,there is a blog which could parse image from PDF successful. Hope this could help
https://codepen.io/Sphinxxxx/pen/MxwGQZ

**Comment by cetinsert** [comment]
[<img src="https://webpdf.pro/.svg" width="64">](https://webpdf.pro)
[Web**PDF**.*pro*](https://webpdf.pro)

---

@shartoo, @svenyonson – here is another way: https://lab.webpdf.dev/#src=//try.httpfs.net/github.com/mozilla/pdf.js:/files/1866432/test.pdf (`♊ PDFium`, `🦊 PDF.js`)

- for bitmap, right-click on any empty space of a page to save/copy image<br><img src=https://user-images.githubusercontent.com/27027/132442088-a1fb8d7b-9e63-4a5c-8477-dae766521cc8.png width=512>
  - requires `debug=1` (`1` by default; toggle with ⌨ <kbd>d</kbd>)
- for `💎 SVG`, (https://lab.webpdf.dev/#src=//pdf.ist/web.pdf)
  - hit ⌨ <kbd>v</kbd> to toggle `💎 SVG` on
  - with `<pdf-page ⋯ svg>` `==` `$0`
  - use `$0.constructor.XML.serialize($0.imageElement)` <img src=https://user-images.githubusercontent.com/27027/132445234-88888cdb-66ff-4791-8e50-acfbf2847eb1.png width=512>

**Comment by cetinsert** [comment]
@mozilla – by which policy, was this (https://github.com/mozilla/pdf.js/issues/9603#event-5270235617) action taken?

**Comment by cetinsert** [comment]
@mozilla – 😡, can somebody please elucidate the policy leading to the discrepancy between

- keeping [this](https://github.com/mozilla/pdf.js/issues/9603#issuecomment-913063930)
- deleting [this](https://github.com/mozilla/pdf.js/issues/9603#event-5270235617) and [this](https://github.com/mozilla/pdf.js/issues/9603#event-5270319498)

comments?

**Comment by Snuffleupagus** [comment]
Regarding https://github.com/mozilla/pdf.js/issues/9603#event-5270235617 and https://github.com/mozilla/pdf.js/issues/9603#event-5270319498:
Sorry, but this is a bug tracker and not an advertising space for other software projects. Especially when your project is a commercial one, which you're charging people money for using!

**Comment by cetinsert** [comment]
@Snuffleupagus – Thank you for responding and sorry to take *your* time again!

> Sorry, but this is a bug tracker and not an advertising space for other software projects

- That is why I have only commented under an already closed issue.<br>(I will further refrain from doing so in the future!)

- We offer non-commercial licensing: https://webpdf.pro/#🎁.


> Especially when your project is a commercial one, which you're charging people money for using!

- I have every intent to offer more of our components for free.<br>(Most likely non-WASM rendering and basic `<pdf-file>`, `<pdf-page>` elements without annotations (forms, etc.).)
