### ISSUE TITLE
PDf.js in Angular 5.

### ISSUE THREAD

**Issue by RaviGprec** [mozilla/pdf.js#9605]
Hi there,

**I'm trying to Develop PDF Viewer Application in Angular 5 using PDF.js
I'm able to view the document. But don't know how to implement the operation (like pageUp, Pagedown, ZoomIN, ZoomOut, print, download, rotate, search etc) in the viewer**. 

Anyone has any suggestions??

Thanks in Advance!!

Regards,
Ravi Kumar

**Comment by timvandermeij** [comment]
You should look at the viewer code in https://github.com/mozilla/pdf.js/blob/master/web/app.js since it does all that. You can either create a minimal viewer with this functionality or adapt `app.js` to remove functionality you don't need.
