### ISSUE TITLE
IE11 : Incorrect image shapes displayed

### ISSUE THREAD

**Issue by Epoks** [mozilla/pdf.js#9608]
Hello,

There is a rendering bug in IE11.

Configuration:
- Web browser and its version: IE11 - all version
- Operating system and its version: windows 8/10 - all version
- PDF.js version: Demo version available at [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: no

Steps to reproduce the problem:
1.  Just open [the attached pdf CharteInfrabel_FR.pdf](https://github.com/mozilla/pdf.js/files/1856761/CharteInfrabel_FR.pdf) into [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html) with IE11 browser.
Works fine with other browsers.

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/20066148/38041566-55652772-32b2-11e8-877c-2febb16ed489.png)

What went wrong?
![image](https://user-images.githubusercontent.com/20066148/38041581-5fae7a26-32b2-11e8-9ed5-9bca8b675372.png)

Thanks,
Epoks

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
