### ISSUE TITLE
How to give Uint8array data to viewer.js instead of Defualt_URL?

### ISSUE THREAD

**Issue by RaviGprec** [mozilla/pdf.js#9615]
I'm developing PDF Viewer in Angular 5. I'm using viewer.js in my Angular 5 project. Right now I'm giving locale pdf (from /assets folder) to viewer.js .

But I want to give uint8array data in place of locale file path. I've referred to [https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file) but there they only mentioned that we can provide uint8array as an alternative to Default_url but now the example .

If there is any example for "adding uint8array to viewer.js" it would be great for me!!

Thanks inadvance!!

**Comment by timvandermeij** [comment]
Yes, refer to https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js#L21 for example.

**Comment by RaviGprec** [comment]
Hi @timvandermeij ,

I have the Uint8array in Typescript file, since I'm developing in Angular 5. My question is how to pass the date from typescript to javascript. 

i.e., I have data in typescript file and how to send this data to java script function. And aslo 
PDFViewerApplication is taking default_url , how to provide uint8array in place of default_url. 

This uint8array is in my .ts file. how to give this uint8array from ts. file to viewer.js  (https://github.com/mozilla/pdf.js/blob/master/web/viewer.js)

Please help me !!

Thanks in Advance!!

**Comment by timvandermeij** [comment]
Passing `UInt8Array` data is not what `viewer.js` supports since it's the default viewer in Firefox and it doesn't need that capability. You'll have to make a custom viewer, for example based on https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js.

**Comment by ageis** [comment]
This script pdf2svg.js is throwing ```Error: Error: Invalid SVG dimensions``` for me.
