### ISSUE TITLE
Uncaught (in promise) Error: Cannot read property 'require' of undefined

### ISSUE THREAD

**Issue by zhzhang** [mozilla/pdf.js#9617]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 65.0.3325.181
- Operating system and its version: Ubuntu 16.04.4 LTS
- PDF.js version: v0.33.8
- Is a browser extension: no

Steps to reproduce the problem:
1. Clone the repo, follow instructions in README under "Getting the Code" until ~$ gulp server
2. Go to http://localhost:8888/examples/helloworld/index.html

What is the expected behavior? (add screenshot)
helloworld.pdf should render in the canvas.

What went wrong? (add screenshot)
Got the error in the title, and a blank rectangle.
![screenshot from 2018-03-31 15-27-26](https://user-images.githubusercontent.com/2108214/38168100-46338152-34f8-11e8-8f40-81feb6b1a481.png)

**Comment by timvandermeij** [comment]
Closing since this is fixed by the pull request above. Thank you for reporting this; it looks like it's an upstream issue in SystemJS and I've now filed a bug in their bug tracker for it.
