### ISSUE TITLE
How to get the canvas view port coordinates from the native pdf coordinates

### ISSUE THREAD

**Issue by prabhatraja** [mozilla/pdf.js#9622]
Hi,
I am using pdf.js to display the pdf in my browser. I want to highlight certain areas in pdf based on the native pdf coordinates I get from OCR from Nuance. Currently I am drawing a rectangle(by creating a div and adding it to the parent element.). However the rectangle I draw is always off from the intended position.

Can somebody help me on how to transform the native pdf coordinates to the exact position on the canvas viewport so that I can place my div on the right position to highlight the correct area. 
Any help would be greatly appreciated.
The following is the code I am using:
function HiglightContent(page, viewport, canvas)
    {
        var pageNumber = 1;
        //native pdf coordinates in the following order - [top,left,bottom, right]
        var pdfRect = [2486, 1272,2640, 3538 ];
        
        //var pageView = window.PDFViewerApplication.pdfViewer.getPageView(1);
        var pageView = page;
        //var screenRect = pageView.viewport.convertToViewportRectangle(pdfRect);
        var screenRect = viewport.convertToViewportRectangle(pdfRect);

        var x = Math.min(screenRect[0], screenRect[2]), width = Math.abs(screenRect[0] - screenRect[2]);
        var y = Math.min(screenRect[1], screenRect[3]), height = Math.abs(screenRect[1] - screenRect[3]);
        
        var pdfPoints = viewport.convertToPdfPoint(x, y);
        x = pdfPoints[0];
        y = pdfPoints[1];
        // note: needs to be done in the 'pagerendered' event
        var overlayDiv = document.createElement('div');
        overlayDiv.setAttribute('id','dvHighlightRect');
        overlayDiv.setAttribute('style', 'background-color: rgba(0,255,0,0.3);position:absolute;' +
          'left:' + x + 'px;top:' + y + 'px;width:' + width + 'px;height:' + height + 'px;');
        //pageView.div.appendChild(overlayDiv);
        canvas.parentElement.appendChild(overlayDiv)
        // scroll
        //scrollIntoView(pageView.div, { top: y });
        //scrollIntoView(overlayDiv, { top: y });
    }

**Comment by Sofiane000** [comment]
I implemented the example Hello world using base64 : https://jsfiddle.net/pdfjs/cq0asLqz/
I am trying to add a print button to it.
I am looking into pdf_print_service.js but I did not know how to incorporate it in my example.
Do I need to use the pdf viewer and if yes how would I do that?
Thanks

**Comment by dipakkolhe** [comment]
Thanks in advance!

i have same issue . how you solved that issue. Please give me any solutions.

**Comment by prabhatraja** [comment]
I solved it by calculating based on the ratio

var canvasWidth = __CANVAS.width;
    var canvasHeight = __CANVAS.height;

    var top, left, bottom, right, width, height;

    top = pdfTop / pdfHeight * canvasHeight;
    left = pdfLeft / pdfWidth * canvasWidth;
    bottom = pdfBottom / pdfHeight * canvasHeight;
    right = pdfRight / pdfWidth * canvasWidth;

    width = right - left;
    height = bottom - top;

    top = top + __CANVAS.offsetTop;
    left = left + __CANVAS.offsetLeft;

    __overlayDiv.setAttribute('style', 'background-color: rgba(255, 255, 0,0.399);position:absolute;' +
      'left:' + left + 'px;top:' + top + 'px;width:' + width + 'px;height:' + height + 'px;');

I think the variable names used in the above code are self explanatory. The pdfHeight and pdfWidth are the theoretical width and height that you get in the nuance xml

**Comment by prabhatraja** [comment]
Let me know if it solves your problem

**Comment by timvandermeij** [comment]
Closing since it looks like this is fixed.
