### ISSUE TITLE
Scroll Listener is not working on pdf.js 

### ISSUE THREAD

**Issue by AhmMhd** [mozilla/pdf.js#9626]
Webview scroll listener is not working on the webview when i load a pdf via PDFjs. 
Is there any solution to it?

**Comment by timvandermeij** [comment]
Closing since all information from the issue template is missing. It's not clear what "Webview" is. Assuming Android's webview, this should work if the browser supports it.

**Comment by rounakpolley** [comment]
Sorry @timvandermeij how can I get the scrollTop() of the pdf I'm  rendering?
