### ISSUE TITLE
ios device does not support lazy loading

### ISSUE THREAD

**Issue by razmaimon** [mozilla/pdf.js#9628]
using the viewer 
https://mozilla.github.io/pdf.js/web/viewer.html
example, i can see that on android / pc /mac running firefox and chrome first page loads and the rest loads in lazy (chunks)
but if i open it on ios webview within my application or in a safari browser on a mac machine the browser/webview waits until the entire document is downloaded .
it has a lot more affect in larger(huge) pdf's .

my viewer links are generated on the fly, so i can't attach a link to my system...

is this a known issue?
can you please assist?

**Comment by timvandermeij** [comment]
Yes, this is disabled for Safari 6.0+ and iOS because they have problems with range requests. Refer to https://github.com/mozilla/pdf.js/blob/c33bf800cc87941cc681c3c54279ab1b9745650d/src/display/api_compatibility.js#L42. Closing since we cannot fix this; it's an upstream problem.
