### ISSUE TITLE
Not able to Integrate viewer that is provided by Mozilla in our own HTML

### ISSUE THREAD

**Issue by manojpersonal** [mozilla/pdf.js#9631]
We are trying to integrate Mozilla's ready made pdf viewer in our application. 
In our application inside one Div tag we want this viewer to get loaded with the PDF. Our application is Single page application. 

In the samples that we have downloaded we have one viewer.html which internally uses viewer.js to show the PDF. In this viewer.html if we add any Div tag in the root then rendering of PDF is not working.  Is there any dependency of viewer on html hierarchy. Can we integrate this viewer in our own HTML structure to show PDF.

**Comment by timvandermeij** [comment]
The easiest approach is probably to embed the viewer using an `iframe` (make sure you're using the latest release). Alternatively, you can create your own (minimal) viewer using the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components.
