### ISSUE TITLE
Fix pdf.js ESLint issues

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#9633]
If I remove all pdf.js whitelisting from the mozilla-central .eslintignore, I see some errors in pdf.js code:
https://queue.taskcluster.net/v1/task/QI9gXOQKQdqkf2iYrS-60g/runs/0/artifacts/public/logs/live_backing.log

TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:2 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:24 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:24:54 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:25:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:25:3 | 'module' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:7 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:28 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:26:42 | 'define' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:27:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:27:3 | 'define' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:7 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:28:29 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:29:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:29:3 | 'exports' is not defined. (no-undef)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:30:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:31:2 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:32:20 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:33:8 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:34:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:34:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:35:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:35:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:36:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:37:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:37:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:38:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:38:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:39:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:40:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:40:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:41:12 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:42:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:42:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:43:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:43:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:44:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:44:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:45:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:45:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:46:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:46:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:47:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:47:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:48:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:48:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:49:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:49:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:50:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:51:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:51:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:52:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:52:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:53:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:54:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:54:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:55:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:55:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:56:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:57:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:57:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:58:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:58:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:59:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:59:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:60:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:61:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:62:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:62:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:63:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:63:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:64:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:65:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:65:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:66:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:66:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:67:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:68:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:68:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:69:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:69:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:70:12 | Expected space(s) after "if". (keyword-spacing)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:71:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:71:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:72:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:72:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:73:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:73:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:74:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:74:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:75:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:75:11 | Unexpected tab character. (no-tabs)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:76:1 | Expected space or tab after '/**' in comment. (spaced-comment)
TEST-UNEXPECTED-ERROR | content/build/pdf.js:76:11 | Unexpected tab character. (no-tabs)

**Comment by rvandermeulen** [comment]
Also:
TEST-UNEXPECTED-ERROR | content/web/debugger.js:17:1 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:22:23 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:24:42 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:24:67 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:27:23 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:31:42 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:31:67 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:34:23 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:38:42 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:38:67 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:39:53 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:42:30 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:42:51 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:47:44 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:51:49 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:64:9 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:65:11 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:70:26 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:70:35 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:71:40 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:72:28 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:73:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:76:38 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:80:27 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:89:40 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:92:43 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:99:47 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:101:43 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:102:44 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:105:44 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:112:43 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:112:51 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:114:41 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:115:41 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:117:45 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:127:30 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:128:42 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:129:20 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:130:27 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:131:30 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:135:43 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:136:27 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:136:35 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:138:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:138:50 | 'select' is already declared in the upper scope. (no-shadow)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:138:58 | 'fontName' is already declared in the upper scope. (no-shadow)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:145:48 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:147:48 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:173:9 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:174:11 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:179:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:179:40 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:180:48 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:181:47 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:182:39 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:186:43 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:189:34 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:190:57 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:199:36 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:200:32 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:207:42 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:208:18 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:209:26 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:210:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:212:38 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:213:23 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:233:41 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:235:38 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:246:30 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:263:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:266:45 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:268:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:271:9 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:278:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:289:12 | 'Stepper' is already declared in the upper scope. (no-shadow)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:301:23 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:301:30 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:302:21 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:305:25 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:307:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:307:37 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:308:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:308:37 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:309:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:309:37 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:310:31 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:310:37 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:337:22 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:338:26 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:344:27 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:345:22 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:346:21 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:347:26 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:354:28 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:357:20 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:363:34 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:367:39 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:374:35 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:378:28 | Strings must use doublequote. (quotes)
TEST-UNEXPECTED-ERROR | content/web/debugger.js:379:28 | Strings must use doublequote. (quotes)

**Comment by Snuffleupagus** [comment]
Note that PDF.js is bundled with Webpack, hence there's limited control of the *exact* output of the built files. Therefore, even though a large number of ESLint rules are enforced on the source files, that unfortunately doesn't necessarily translate perfectly to the built files :-(

The one exception here is the `Strings must use doublequote. (quotes)` errors, which could be fixed quite easily (assuming that it's actually a desired change). Fixing that would, basically, be as simple as changing https://github.com/mozilla/pdf.js/blob/c2cbeaa34d81bbb7cced856e2888867df587a1fa/.eslintrc#L145 to `"quotes": ["error", "double"],` and then running ESLint with the `--fix` flag set.

**Comment by Snuffleupagus** [comment]
Following up on https://github.com/mozilla/pdf.js/issues/9633#issuecomment-393478177 there's really only *one* thing that's actionable here, i.e. the `Strings must use doublequote. (quotes)` errors with basically two options:
 1. Do nothing, and just close the issue as WONTFIX. The argument for choosing this would be that given the Webpack bundling, it's simply impossible to fix *all* of ESLint "errors" and these files shouldn't be edited directly in `mozcentral` anyway.
 2. Change the PDF.js style guide to require double quotes everywhere instead, since this is inline with the [general Mozilla coding-style](https://searchfox.org/mozilla-central/rev/465dbfe030dfec7756b9b523029e90d48dd5ecce/tools/lint/eslint/eslint-plugin-mozilla/lib/configs/recommended.js#332-337), and then close the issue as FIXED.
*Note:* This process can be mostly automated, with the `eslint --fix` option.

**Comment by Snuffleupagus** [comment]
@timvandermeij Sorry to bother you again here, but do you have an opinion on https://github.com/mozilla/pdf.js/issues/9633#issuecomment-457822856?

**Comment by timvandermeij** [comment]
I'm a bit on the fence here. On the one hand, I'm not really sure if it's worth it touching most lines of code only to change quotes. On the other hand, it would be good to be consistent with the Mozilla coding style for JavaScript. My feeling is that for the longer term it would be better to synchonize with the Mozilla coding style, so if this conversion can be automated, I'm not opposed to it.

/cc @yurydelendik @brendandahl Any opinions from your side on this?

**Comment by timvandermeij** [comment]
Closing after the discussion in #10755.

**Comment by timvandermeij** [comment]
@rvandermeulen Just a heads-up: in #11446 PDF.js started using Prettier for code formatting across the entire code base, which `mozilla-central` also adopted, so we should now use (practically) the same coding style as `mozilla-central`. I don't know if anything needs to be changed on the `mozilla-central` side in terms of ESLint ignore rules, but if so, could you do that/make a bug ticket so it can be picked up? Thank you!

**Comment by rvandermeulen** [comment]
I'm off for the holidays, but I'll run it through Try when I'm back and let
you know.

**Comment by Snuffleupagus** [comment]
> [...] so we should now use (practically) the same coding style as `mozilla-central`.

While that's certainly true for the source code itself, please note that this unfortunately doesn't necessarily translate 100% to the *built* code which is being included in mozilla-central (i.e. the output of `gulp mozcentral`, where Webpack will re-format things a bit).

In practice though, since *this* GitHub repository is the canonical PDF.js source, given that the PDF.js files shouldn't be edited directly in mozilla-central the remaining differences are unlikely to matter much :-)

**Comment by timvandermeij** [comment]
> I'm off for the holidays, but I'll run it through Try when I'm back and let you know.

@rvandermeulen That's perfect. Enjoy your holidays!

> the remaining differences are unlikely to matter much

@Snuffleupagus True. Thanks, I forgot that Webpack also does some modifications. Hopefully the effect of that is also minimized now, and otherwise those changes can indeed be ignored upstream.
