### ISSUE TITLE
Module not found: Error: Can't resolve 'exports' in 'ProjectFolder\node_modules\pdfjs-dist\build'

### ISSUE THREAD

**Issue by MuhammadMohsin** [mozilla/pdf.js#9634]
![image](https://user-images.githubusercontent.com/8535395/38357548-6a5c29e8-38dc-11e8-8690-a74775f2663a.png)

**Comment by timvandermeij** [comment]
Closing since none of the information from the issue template is provided. In particular, we need exact steps to reproduce the issue.
