### ISSUE TITLE
Missing background and some other aspects

### ISSUE THREAD

**Issue by deepj** [mozilla/pdf.js#9635]
Attach (recommended) or Link to PDF file here:
https://newsroom.intel.com/wp-content/uploads/sites/11/2018/04/8th-gen-intel-core-h-series-press-deck.pdf

Configuration:
- Web browser and its version: Firefox 60.0b9
- Operating system and its version: macOS 10.13.4
- PDF.js version: 2.0.402

What is the expected behavior? (add screenshot)
![screen shot 2018-04-05 at 12 12 18](https://user-images.githubusercontent.com/33736/38360613-2e7050a2-38ba-11e8-9246-6e874915220b.png)

What went wrong? (add screenshot)
![screen shot 2018-04-05 at 12 11 55](https://user-images.githubusercontent.com/33736/38360615-306ff006-38ba-11e8-8655-2a2192d57520.png)

**Comment by timvandermeij** [comment]
I cannot reproduce this using Arch Linux, Firefox 59.0.2 (64 bit) and PDF.js 2.0.288. Are you also able to reproduce this in the stable version of Firefox, to exclude the beta being possibly broken?

**Comment by deepj** [comment]
@timvandermeij I use always only betas of Firefox (never stable versions) but it seems to be OK in the Nightly (PDF.js 2.0.480)

**Comment by THausherr** [comment]
Works for me on W7, FF 50.0.2 and latest pdf.js version. I could reproduce the effect yesterday with same FF version but built-in pdf.js version, but cannot reproduce it today.

**Comment by SamyCookie** [comment]
Works for me too with FF 59.0 (64 bits) and PDF.js PDF.js: 2.0.288 on Debian testing.
