### ISSUE TITLE
Any limitations for rendering complex layered PDF files

### ISSUE THREAD

**Issue by manojpersonal** [mozilla/pdf.js#9636]
Hi,

We are going through the pdf viewer provided by you. We tried couple of pdf files and all of them worked.  But while going through different articles we found one article saying there could be issues in rendering pdf using pdf.js. Please find the [link](https://blog.pdftron.com/2013/08/08/how-to-integrate-a-pdf-viewer-in-html5-apps/) for the same.

Could you please confirm whether pdf.js supports all type of complex layered pdf rendering in all aspects like text/ graphics and colors of graphics object/background.

**Comment by timvandermeij** [comment]
The article you linked is from four years ago and is not accurate anymore. Colorspaces and blend modes, for example, are all supported. There are some open issues for shading patterns, but most of them render just fine and they're not very common in PDF files. I can only think of layers that we don't support (search in the open issues to find those tickets), but that's also not too common.
