### ISSUE TITLE
Position of some textelements is wrong

### ISSUE THREAD

**Issue by haraldundandrea** [mozilla/pdf.js#9639]
Attach (recommended) or Link to PDF file here: https://shop.the-flying-condors.de/index.php/404/oa-b%C3%A4lle-f%C3%BCr-b%C3%A4llebad,-70-st%C3%BCck-im-netz-detail?tmpl=component&format=pdf

Configuration:
- Web browser and its version: Firefox, 59.0.2 (64-Bit)
- Operating system and its version: Windows 8.1, Version 6.3.9600 Build 9600
- PDF.js version: I don't know, where I can find this information
- Is a browser extension:

Steps to reproduce the problem:
every time I try to see the PDF-version of a product page from my shop, some text elements were displayed at the same position, so that it can't be read...

What is the expected behavior? (add screenshot)

![right layout](https://user-images.githubusercontent.com/38179112/38465916-c9ba35f0-3b21-11e8-88a7-42aca3c78252.JPG)

What went wrong? (add screenshot)

![wrong layout](https://user-images.githubusercontent.com/38179112/38465911-b253cab6-3b21-11e8-9ad1-0deeadc7fe91.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): I don't know what I have to do here...

Thanks for watching, I hope this problem can be fixed...

**Comment by timvandermeij** [comment]
The PDF file renders exactly the same in e.g., Okular. Your screenshots are comparing the web rendering with the PDF rendering, which is not a valid comparison since your PDF creator, TCPDF, seems to mess up the text positioning here. Closing since this is a problem of TCPDF.
