### ISSUE TITLE
Fonts are incorrectly printed on page 3 onward

### ISSUE THREAD

**Issue by OndraM** [mozilla/pdf.js#9641]
Attach (recommended) or Link to PDF file here:
https://www.dropbox.com/s/5gm56r2lnik4ihy/firefox-print-broken-from-page-3.pdf?dl=0

Configuration:
- Web browser and its version: Firefox 59.0.2
- Operating system and its version: Arch Linux
- PDF.js version: builtin PDF.js: 2.0.288
- Is a browser extension: no

Steps to reproduce the problem:
1. Print attached document
2. Starting from page 3, the font rendering is broken (some generic font with broken kerning is being used, instead of Trebuchet)

What is the expected behavior? (add screenshot)
All the pages should be printed the same.

What went wrong? (add screenshot)
![2018-04-08 22 20 24](https://user-images.githubusercontent.com/793041/38472114-45a56ad2-3b7b-11e8-9e03-8200836b1233.jpg)

The upper page (which is #1 or #2 from the document) is printed properly, with Trebuchet MS being used.
The bottom one is third page in the document. Trebuchet is not used. 
There is no difference if the page three (or four etc.) is being printed separately. No matter what, the page 1 and 2 from the document are ok, pages 3 and onward are not.

All pages are displayed properly, the problem is only when they are printed.

The document was created using pdftk, by concatenating the one same pdf page four times.

**Comment by Snuffleupagus** [comment]
This is an upstream bug, and the solution will require patching of Firefox; please refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1524640#c1.

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
