### ISSUE TITLE
l10n.js - locale.properties 404 (Not Found)

### ISSUE THREAD

**Issue by tfierens** [mozilla/pdf.js#9643]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: All main browsers (Edge, Chrome, Opera, Firefox)
- Operating system and its version: Windows 7 Pro
- PDF.js version: pdfjs-1.9.426-dist
- Is a browser extension: ?

Steps to reproduce the problem:
1. I have the pdf.js called in an IFrame that's calling the following code:

`<script>
    $(document).ready(function () {
        $('#fileList li').click(function (e) {
            var fileName = $(this).html();
            var url = '~/Scripts/pdfjs-dist/Web/viewer.html?file=' + fileName
            $('#iframePdfViewer').attr('src', url);
        });
    });
</script>`

2. When the pdf gets loaded, note that everything is working as expected but I would like to get rid of these errors/warning if possible but I'll deal with this one first as the rest of my issues are warnings rather than an error. This is the error I'm getting:

> /MyApp/Scripts/pdfjs-dist/web/locale/locale.properties Failed to load resource: the server responded with a status of 404 (Not Found)

The attached snapshot provides additional information:

![capture](https://user-images.githubusercontent.com/13773041/38497073-54f7ba70-3bef-11e8-8ccc-0dcc75abd625.PNG)

Note that my locale.properties is definitely available.

What is the expected behavior? (add screenshot)

No error generated.

Any ideas?

Thanks

**Comment by timvandermeij** [comment]
Did you run `gulp locale`? Either the file is not in the specified path or XHR cannot access it due to rights issues. This is an issue of the custom deployment and not something we can help with without access to a minimal example that shows the issue.

**Comment by tfierens** [comment]
Hi,

I haven't ran "gulp locale". I don't actually know what it's for and will research it further. You mentioned "Either the file is not in the specified path or XHR cannot access it" and I've checked and there is definitely a path for http:\\localhost\myapp\Script\pdfjs-dist\web\locale but there is no file called l110n.js in it. 

There are numerous sub-folders for languages i.e. ach, be, cs, en-GB, etc... and in the root, there is a locale.properties but no .js file

I've literally just copied the folders/files that were available in the pdf.js zip file that I downloaded and copied them into my Scripts folder. I then modified a few path in order to get it to work. As mentioned, while getting this single error and numerous warnings, everything appears to work very well in all major browsers but I just would like to get rid of this error if possible and eventually work my way up to get rid of the warnings as well.

Will running "gulp locale" create additional files? This is used on a Windows 7 pro in an ASP.NET MVC project btw.

Thanks.

**Comment by tfierens** [comment]
I don't know if this is helpful in any way, but just below the error, there was a warning with the following:

![capture](https://user-images.githubusercontent.com/13773041/38549333-afc83e7c-3cab-11e8-9f15-207c75c508a1.PNG)

**Comment by timvandermeij** [comment]
Given your stack trace, I don't think that `l10n.js` is missing, but rather that it is not able to find the `locale.properties` file.

> I then modified a few path in order to get it to work.

Please provide exact steps to reproduce the issue, i.e., what you did after you downloaded the ZIP file.

**Comment by tfierens** [comment]
Thanks Tim for re-opening the case.

I'll try to quickly create a new project and see if I can reproduce the issue.  Note that I created a simple test.html in the same location as the local.properties file and I was able to access it.

I'll get back to you as soon as I'm done.

Thanks

**Comment by tfierens** [comment]
Hi Tim,

I've managed to reproduce the issue using the following steps:

1. Create new asp.net mvc app (with no authentication)
2. Create pdfjs-dist folder in Scripts folder 
3. Extract 1.9.426.zip to folder 1.9.426 (on desktop)
4. Create pdfjs-dist folder in Scripts folder in asp.net mvc app
5. Copy web & build folders from folder 1.9.426 to Scripts folder in asp.net mvc app
6. Exclude build folder from project located in Scripts folder and Include it again so that all files within the folder get included in project.
7. Exclude web folder from project located in Scripts folder and Inclde it again so that all sub-folders & files get included in project
8. Create a new empty MVC 5 Controller in the Controllers folder.
9. Create a new view called Index.cshtml in the PdfViewer folder located in the Views folder (Use Layout Page selected)
10. Add the following code to Index.cshtml

`<div style="width: 800px; height: 500px;">
    <iframe width="800" height="500" id="iframePdfViewer" seamless="seamless" scrolling="no" src="~/Scripts/pdfjs-dist/web/viewer.html"></iframe>
</div>
`
11. Run project and go to http://localhost:40007/PdfViewer/Index
12. Same error and a lot of warnings
 
I've create a screencast that highlights:

1. web & build folder included in project
2. locale.properties file is available in /Scripts/pdfjs-dist/web/locale/
3. Controller created
4. View created containing iFrame that's calling the viewer.html located in /Scripts/pdfjs-dist/web/
5. Run project
6. Error & warnings visible in Chrome's debug window


[Screencast](https://www.screencast.com/t/PX4mpMpZstYx)
[Asp.net MVC project ((contains full project with all dependencies including pdf.js))](https://1drv.ms/u/s!AhEmXx95_8mQutIvr7BjLUTr-8p-ig)

Note that I didn't have to change any path in this project as previously mentioned so I'll check my other project tomorrow but I think that element is not important as I managed to reproduce the problem using all the standard pdf.js files.

Hopefully, it is something straight forward to figure out. Let me know if you need anything else from me.

Thanks.

**Comment by tfierens** [comment]
@timvandermeij 

I found the solution. Not only does it remove the error, it also removes the 200+ warnings I had.

All I had to do was to add a new MIME type in IIS 7:

File name Extension: .properties
MIME Type: application/octet-stream

That's it.

**Comment by atreyuandartax** [comment]
Hello guys!

I'm struggling exactly with the same issue that @tfierens had (locale.properties file and the whole cascade of warnings). I am working on a MVC architecture/environment as well (known as EPiServer), so I have developed a very similar code you did @tfierens. 

But additionally, I am getting an even worse issue, since the first time the application is get loaded, the  PDF shows fine within the iFrame, but when I (or a user) reload the page is throwing the following error:
"The page cannot be displayed because an internal server error has occurred."
And this error keeps showing over and over again after several page reloads, but after a minute (more or less) has passed the viewer.html interface and the PDF are get loaded fine again.

Any idea guys?

Please advise!

![image](https://user-images.githubusercontent.com/33551472/70726443-b2ab6980-1cc3-11ea-82d8-f38608f0d2dc.png)

![image](https://user-images.githubusercontent.com/33551472/70726523-d79fdc80-1cc3-11ea-859c-0250689a4856.png)

**Comment by benwinding** [comment]
If you're using the pdf.js viewer, then here's the fix:

**1. Download locale for a specific language you need**
I'm using `en-US` https://github.com/mozilla/pdf.js/tree/master/l10n/en-US

**2. Save as `locale.properties`** on your server

**3. Make the locale link points to that file**
``` html
    <link rel="resource" type="application/l10n" href="locale.properties">
```
This got rid of all warnings and errors in my case

**Comment by alpha027** [comment]
@benwinding Can you please elaborate on the 3rd step ? where exactly shall I add the link tag ? ( <link rel="ressource" ... >) ?
Thanks for your help !

**Comment by benwinding** [comment]
Depends how your script is included within your site.

Basically you need to include the `<link>` tag, before you load the `pdf-viewer` script, here's how I include it in our site.

``` html
<link rel="resource" type="application/l10n" href="locale.properties">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pdfjs-dist-viewer-min@2.6.347/build/minified/web/viewer.css" />
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
<script src="https://mozilla.github.io/pdf.js/build/pdf.worker.js"></script>
<script>
  // The workerSrc property shall be specified.
  pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.worker.min.js';
</script>
<script src="https://mozilla.github.io/pdf.js/web/viewer.js"></script>
```
