### ISSUE TITLE
SVG renderer does not implement setTextRenderMode, beginAnnotations and endAnnotations

### ISSUE THREAD

**Issue by blerner** [mozilla/pdf.js#9647]
Attach (recommended) or Link to PDF file here: http://cs.brown.edu/~sk/Publications/Papers/Published/lepk-verif-ext-pbm/paper.pdf

Configuration:
- Web browser and its version: Firefox latest
- Operating system and its version: Ubuntu 16.0
- PDF.js version: 2.0.487
- Is a browser extension: no

Steps to reproduce the problem:
Render the file with SVG versus canvas.

Most of the pages come up with solid blocks of color, rather than text.  The console is full of many messages, 
```
19:39:21.887 Warning: Unimplemented operator beginAnnotations
pdf.min.self.js:1:2288
19:39:21.888 Warning: Unimplemented operator endAnnotations
pdf.min.self.js:1:2288
19:39:22.066 Warning: Unimplemented operator setTextRenderingMode
```
which makes sense, since the text rendering mode clearly affects the coloring of the page.  (I know that particular PDF uses rendering modes to implement optional content groups, which seem to work properly in the canvas output.)  I have no idea what the beginAnnotations and endAnnotations are used for.

**Comment by timvandermeij** [comment]
The begin/end annotation operators are used for drawing annotations (sticky notes, lines, et cetera) on the page, which is not really relevant for this issue. The text rendering modes indeed need to be implemented.
