### ISSUE TITLE
Corrupted displaying of attached file

### ISSUE THREAD

**Issue by evgeniy-kunitsa** [mozilla/pdf.js#9650]
Link to PDF file here:
[Kred.Eingangsrechnungen.pdf](https://github.com/mozilla/pdf.js/files/1898753/Kred.Eingangsrechnungen.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 17.10
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Open demo https://mozilla.github.io/pdf.js/web/viewer.html
2. Open attached file

What is the expected behavior?
Correct opened file
![image](https://user-images.githubusercontent.com/11280208/38625193-93e6522c-3db2-11e8-8bc1-b97c4368d963.png)

What went wrong?
Something wrong with displaying
![image](https://user-images.githubusercontent.com/11280208/38625273-bcdf34aa-3db2-11e8-9aea-336063e2353a.png)

**Comment by timvandermeij** [comment]
The PDF file renders exactly the same in Okular on Linux, so it's not entirely PDF.js-specific, but that doesn't make its rendering less weird. The text layer is also positioned correctly and the text can be copied. Thank you for filing this; this definitely needs more research to find out what's going on here.

**Comment by THausherr** [comment]
The real image size is 3307 x 4676, but in the image dictionary it is 2480 x 3507.

**Comment by FStapenhorst** [comment]
I extracted the images from the pdf using a comercial SDK (www.gdpicture.com) and I got those two images attached. They look just fine and their size is 2480 x 3507.
[Images.zip](https://github.com/mozilla/pdf.js/files/1904567/Images.zip)

**Comment by THausherr** [comment]
Your images are cut off (compare the bottom right). Here's the .JP2 image as it is in the PDF and it is 3307 x 4676:

[image.zip](https://github.com/mozilla/pdf.js/files/1904678/image.zip)

**Comment by THausherr** [comment]
Adobe Reader and Chrome display the image but cut it off. MS Edge and Apache PDFBox display the full image.
