### ISSUE TITLE
pdf.js with firefox for android

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mozilla/pdf.js#9651]
Hello.

This is really not a bug.
Some times ago pdf.js was and addon (which works on android).
Now it is included in firefox. But when I try to open pdf firefox just downloads it.

**Comment by timvandermeij** [comment]
Most likely the PDF opening action has been changed. Follow the steps on https://support.mozilla.org/en-US/kb/change-firefox-behavior-when-open-file to reset PDF to `Preview in Firefox` to fix that.

**Comment by c-e-p-x-u-o** [comment]
I'm talking about firefox for android but this instruction is for the desktop one.

**Comment by c-e-p-x-u-o** [comment]
https://mozilla.github.io/pdf.js/web/viewer.html works fine on android.
What is the real problem to build it into android or make an add-on?
Is this a political decision?
I have never developed firefox addon or javascript. (Only linux, c, networks etc.)
Is it hard to adopt the old android addon to the nowadays pdf.js and android versions?
Is the work already started?
Could you reopen the bug, please, until there no solution for android.

**Comment by brendandahl** [comment]
The main reason is it takes work to properly integrate the viewer and there is no one currently working on it. There's more work happening for Firefox on android this year, but I'm unaware of a pdf viewer being a priority.

We have issue #6136 for supporting Firefox(fennec) on android.

**Comment by c-e-p-x-u-o** [comment]
Thank you!
