### ISSUE TITLE
How to trigger the print event in viewer.js from viewer.html by clicking the external button

### ISSUE THREAD

**Issue by karthickDhanapal** [mozilla/pdf.js#9652]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You can put the `print` event on the event bus to trigger the printing action. That is also what the print button does on click (https://github.com/mozilla/pdf.js/blob/8512596508e31a72eb3d22e3a1c669e5d9ee4a7d/web/app.js#L1376).

**Comment by karthickDhanapal** [comment]
@timvandermeij  Thank you so much... but what is the eventBus in pdf.js

**Comment by timvandermeij** [comment]
It is defined here: https://github.com/mozilla/pdf.js/blob/master/web/ui_utils.js#L523

Basically it allows components to communicate in a generic way using events. If a component dispatches the print event, other components that listen for it can trigger and perform an action.

**Comment by karthickDhanapal** [comment]
@timvandermeij  thank you so uch
