### ISSUE TITLE
Open certain bookmark when pdfviewer opened

### ISSUE THREAD

**Issue by alihut** [mozilla/pdf.js#9653]
I'm trying to show certain bookmark when pdfviewer opened. Now we open certain page with

_PDFViewerApplication.initialBookmark = "page=72";_

How can i open a bookmark named **bookmark1** for example?

**Comment by Snuffleupagus** [comment]
> Now we open certain page with
> 
> PDFViewerApplication.initialBookmark = "page=72";
> 
> How can i open a bookmark named bookmark1 for example?

Based the quoted code, did you actually try simply using `PDFViewerApplication.initialBookmark = "bookmark1"`; instead since that should work?

**Comment by timvandermeij** [comment]
I think that should indeed just work. If not, please provide an example PDF file with such a bookmark because otherwise the issue is not actionable. We can reopen this if the problem persists and a PDF file is provided. Thanks.
