### ISSUE TITLE
Problem in getting the displaying the PDF all pages once.

### ISSUE THREAD

**Issue by RaviGprec** [mozilla/pdf.js#9656]
Hi ,

Please have a look into the stackoverflow question that I raised .
[https://stackoverflow.com/questions/49774780/getting-all-the-pages-at-once-using-pdf-js](url)

I'm getting the pages side by side except first page. If the screen is in minimized state then I everything works fine but if it is maximized state then problem comes.

Any solutions or suggestions would be grateful.!!
Thanks in Advance!!

Regards,
Ravi kumar

**Comment by timvandermeij** [comment]
I agree with the posted answer that you this is a CSS problem. Make sure the pages do not have `display: inline-block` or similar. Since no CSS is posted and it's not really PDF.js-related, I'm closing this.
