### ISSUE TITLE
Cannot add custom header to getDocument?

### ISSUE THREAD

**Issue by Kailash43** [mozilla/pdf.js#9658]
Configuration:
- Web browser and its version:  65.0.3325.181
- Operating system and its version: Windows 10
- PDF.js version: 1.7.225
- Is a browser extension: Allow-Control-Allow-Origin

Steps to reproduce the problem:
Trying to add custom headers to the pdfjs getDocument request.

Based on the [GitHub ](https://github.com/mozilla/pdf.js/issues/3852) suggestion have tried to add it.

Even while Debugging it is being shown in **this.httpheaders** but I am not sure why it is not working.

Below is my js code

`var parameter = {
  url: this.url,
  httpHeaders: { Authorization: password },
  withCredentials: true,
} 
var loadingTask = pdfjsLib.getDocument(parameters);`

Need to show pdf file sample.js

But it is showing the authorized issue.

This is my chrome network request
![sample](https://user-images.githubusercontent.com/9428585/38671098-16ab0c2e-3e68-11e8-836c-d143b5c1b710.PNG)

**Comment by tomadj** [comment]
Same issue ! 
Headers are no longer being added to requests. 

Any solution ?

**Comment by timvandermeij** [comment]
Closing until the requested information is provided and it's actually clear that this is an issue in PDF.js and not in a custom implementation.
