### ISSUE TITLE
once the search bar is closed it should be clear the next time it's opened.

### ISSUE THREAD

**Issue by shradha-khapra** [mozilla/pdf.js#9663]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:1.4
- Is a browser extension:

Steps to reproduce the problem:
1. search for any text in the pdf-viewer
2.close the search bar and re-open it

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by shradha-khapra** [comment]
Hey @timvandermeij , I would like to work on this issue . Can this issue be assigned to me?

**Comment by shradha-khapra** [comment]
@timvandermeij  can you please tell me the location in the repository where I can find the JS code written for the search button? Because I was unable to find it in the viewer.js file.

**Comment by shradha-khapra** [comment]
Never mind. I found the JS file.

**Comment by Snuffleupagus** [comment]
> once the search bar is closed it should be clear the next time it's opened.

This is *not* how the native findbar works in Firefox, so why should the PDF.js (built-in) findbar behave any different here!? Having different behaviours for the native/built-in findbars seems very confusing, and will result in a bad UX; hence I'd suggest that WONTFIX is an appropriate resolution here.

**Comment by Snuffleupagus** [comment]
> once the search bar is closed it should be clear the next time it's opened.

This is *not* how the native findbar works in Firefox, so why should the PDF.js (built-in) findbar behave any different here!? Having different behaviours for the native/built-in findbars seems very confusing, and will result in a bad UX; hence I'd suggest that WONTFIX is an appropriate resolution here.

**Comment by timvandermeij** [comment]
Good point. Now that I'm looking at this again and having tried both the native find bar and the PDF.js find bar, it indeed wouldn't make sense for them to differ in behavior, so let's close this.
