### ISSUE TITLE
Specific pdf file is not rendered correctly in Chrome

### ISSUE THREAD

**Issue by uuggene** [mozilla/pdf.js#9664]
Attach (recommended) or Link to PDF file here:
[AMS2921833.pdf](https://github.com/mozilla/pdf.js/files/1907470/AMS2921833.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 65.0.3325.181 (Official Build) (64-bit);
- Operating system and its version: Windows 10 x64 1709;
- PDF.js version: pdfjs-dist 2.0.491;
- Is a browser extension: no;

Steps to reproduce the problem:
1. Upload attached file.
2. Data in grid on first page is not rendered.

What is the expected behavior?
![expected](https://user-images.githubusercontent.com/11631048/38736967-627bad4c-3f36-11e8-8a40-878500fb5111.png)

What went wrong?
![actual](https://user-images.githubusercontent.com/11631048/38736984-6c200b9a-3f36-11e8-9ee2-354081aeaf02.png)

**Comment by Rob--W** [comment]
Looks good to me in Chrome 65.0.3325.146 on Linux, PDF.js 2.0.491. Do you see any errors in the console?

**Comment by uuggene** [comment]
> Looks good to me in Chrome 65.0.3325.146 on Linux, PDF.js 2.0.491

I don't have Linux to check it. But it's also reproduced on macOS High Sierra 10.13.1, Chrome 63.0.3239.84

> Do you see any errors in the console?

Only 1 warning:
`Warning: AcroForm/XFA is not supported`

**Comment by tfierens** [comment]
Tried it on Chrome Version 65.0.3325.181 (Official Build) (64-bit) on Windows 7 pro and getting the same problem.

Same as @uuggene - No errors just warning: 'Warning: AcroForm/XFA is not supported'.

Work with Firefox and IE11
Fails with Opera (same behaviour as Chrome).

**Note:** that printing in Landscape cuts off the right inside of the page.

**Comment by KheeWong** [comment]
Same issue on
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
macOS High Sierra 10.13.6
PDF.JS version 2.0.489

**Comment by Lucasus** [comment]
I have exactly same problem on:
Chrome Version 68.0.3440.84 (Official Build) (64-bit)
Microsoft Windows 10 Pro, 10.0.16299
PDF.js: 2.0.752

**Comment by brendandahl** [comment]
Using the pdfBug stepper you can see that the text is drawn correctly at first, but then something gets screwed up when doing the RadialAxial fill.

```
403 | shadingFill | [["RadialAxial","axial",[[0,"transparent"],[0.000001,"rgb(255,204,0)"],[0.1,"rgb(255,209,26)"],[0.2,"rgb(255,214,51)"],[0.30000000000000004,"rgb(255,219,77)"],[0.4,"rgb(255,224,102)"],[0.5,"rgb(255,229,128)"],[0.6,"rgb(255,235,153)"],[0.7,"rgb(255,240,178)"],[0.7999999999999999,"rgb(255,245,204)"],"..."],[0,61],[0,72],null,null]]
```

**Comment by Lucasus** [comment]
Hello, @brendandahl, thanks for looking into this problem! Is there any chance this issue will be fixed in foreseeable future? I'd really appreciate it.

**Comment by uuggene** [comment]
I think it can be closed. It seems to be fixed.

**Comment by timvandermeij** [comment]
Works for me on Firefox too. Let's close this as it seems to be fixed upstream.
