### ISSUE TITLE
Reference Error: document is not defined when extracting images (ref: #9603)

### ISSUE THREAD

**Issue by svenyonson** [mozilla/pdf.js#9667]
Opening a new issue as a follow on to #9603, which was marked as closed with build 9588 & 9516.

I did the following in the pdf.js repo: 
- git pull
- npm install
- gulp dist-install
- replaced my project's node_modules/pdfjs-dist folder with pdf.js/build/dist 

Running the following example returns "Reference Error: document is not defined". 

```
var PDFJS = require('pdfjs-dist');
var Canvas = require('canvas');
const {promisify} = require('util');
const fs = require('fs');
const writeFile = promisify(fs.writeFile); 

function proc(filename) {

    (async () => {
        try {
            var doc = await PDFJS.getDocument({url: filename, nativeImageDecoderSupport: 'none', disableFontFace: true});
            var pages = doc.pdfInfo.numPages;

            for (let i=1; i <= pages; i++) {
                var page = await doc.getPage(i);
                var ops = await page.getOperatorList();

                for (let j=0; j < ops.fnArray.length; j++) {
                    if (ops.fnArray[j] == PDFJS.OPS.paintJpegXObject || ops.fnArray[j] == PDFJS.OPS.paintImageXObject) {
                        var op = ops.argsArray[j][0];
                        var img = page.objs.get(op);
                        var scale = img.width / page.pageInfo.view[2];
                        var viewport = page.getViewport(scale);
                        var canvas = new Canvas(img.width, img.height);
                        var context = canvas.getContext('2d');

                        await page.render({canvasContext: context, viewport: viewport});

                        var imageData = canvas.toBuffer();
                        var ordinal = ("00" + i).slice (-3);
                        await writeFile('image-'+ordinal+'.png', imageData);
                    }
                }
            }
            console.log('done');
        } catch(e) {
            console.log(e);
        }
    })();
}

proc("test.pdf");
```

Am I missing something?

**Comment by svenyonson** [comment]
[test.pdf](https://github.com/mozilla/pdf.js/files/1912994/test.pdf)

**Comment by svenyonson** [comment]
Do you actually get data in your jpegs? Without the render, you will have an empty canvas, and then extract the data from that empty canvas and write it to disk.

**Comment by RafaPolit** [comment]
For this to work in the backend, I believe that the render context needs also a canvasFactory (not only a canvasContext).

This example mostly works:
https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js

**Comment by svenyonson** [comment]
@RafaPolit - which part of it doesn't work?

**Comment by RafaPolit** [comment]
I have reported the error here: #9675

**Comment by svenyonson** [comment]
Any traction on this? Still unable to extract PNG images in a node application

**Comment by svenyonson** [comment]
If there is a new way to do this, please let me know. Any sample code that will extract PNG files from the uploaded file `test.pdf` would be greatly appreciated

**Comment by hdwatts** [comment]
Bumping, getting this same error from following the example

**Comment by markb-trustifi** [comment]
It fails because `FontLoader.prototype.insertRule` form some reason uses `document.createElement('style')`.
I'm wondering, if this example is given especially for NodeJS how come it is using the browser objects?

**Comment by svenyonson** [comment]
It's been a while since I've worked with this code - which was derived from samples I had found. If there is a way to extract images from test.pdf using purely server side node.js, I'll be very happy. But so far I haven't found any successful code example.

**Comment by ckshekhar** [comment]
It works with canvasFactory (https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js). 
Create canvas factory from above link and pass it to render function.
Sample code
```javascript
// Canvas factory
function NodeCanvasFactory() {}
NodeCanvasFactory.prototype = {
  create: function NodeCanvasFactory_create(width, height) {
    // assert(width > 0 && height > 0, 'Invalid canvas size');
    var canvas = createCanvas(width, height);
    var context = canvas.getContext("2d");
    return {
      canvas: canvas,
      context: context
    };
  },

  reset: function NodeCanvasFactory_reset(canvasAndContext, width, height) {
    // assert(canvasAndContext.canvas, 'Canvas is not specified');
    // assert(width > 0 && height > 0, 'Invalid canvas size');
    canvasAndContext.canvas.width = width;
    canvasAndContext.canvas.height = height;
  },

  destroy: function NodeCanvasFactory_destroy(canvasAndContext) {
    // assert(canvasAndContext.canvas, 'Canvas is not specified');

    // Zeroing the width and height cause Firefox to release graphics
    // resources immediately, which can greatly reduce memory consumption.
    canvasAndContext.canvas.width = 0;
    canvasAndContext.canvas.height = 0;
    canvasAndContext.canvas = null;
    canvasAndContext.context = null;
  }
};

const page = await pdf.getPage(1);
const viewport = page.getViewport({ scale: 1.0 });
const canvasFactory = new NodeCanvasFactory();
const canvasAndContext = canvasFactory.create(
   viewport.width,
   viewport.height
);

await page.render({
    canvasContext: canvasAndContext.context,
    viewport,
    canvasFactory
});

const imageData = canvasAndContext.canvas.toBuffer();
```

**Comment by ckshekhar** [comment]
@svenyonson Hope above example will solve your problem

**Comment by mitchell-frost** [comment]
I am new to mozilla. Can I work on this?

**Comment by Snuffleupagus** [comment]
The PDF document from https://github.com/mozilla/pdf.js/issues/9667#issuecomment-381413724 seem to work just fine with either of the `pdf2png` or `pdf2svg` examples, see https://github.com/mozilla/pdf.js/tree/master/examples/node, when testing against the `master` version of the PDF.js library.

Given that this issue is over two years old, and that many improvements have been made since then (e.g. PR #11601 may *indirectly* have fixed this); is it meaningful to keep this issue open?

**Comment by svenyonson** [comment]
Thanks Tim/Jonas.

I will try my example with the latest version and if I have any issues I’ll let you know.
