### ISSUE TITLE
presentation-mode should have arrows as navigation is unclear

### ISSUE THREAD

**Issue by shradha-khapra** [mozilla/pdf.js#9669]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:1.4
- Is a browser extension:

Steps to reproduce the problem:
1. get into presentation-mode
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Given that it's, at least to me, *completely* unclear what's actually being reported/asked here and that the [issue template](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) is left mostly blank, I'd suggest closing this issue as incomplete.
