### ISSUE TITLE
Print is not working properly

### ISSUE THREAD

**Issue by RaviGprec** [mozilla/pdf.js#9671]
Hi there,
I'm developing PDF Viewer in Angular 5.

I'm facing problem while print the content.
Pages are broken when I try print button.

Please have a look here:
![inkedwindows server 2012 vanila vm-2018-04-17-15-13-33_li](https://user-images.githubusercontent.com/35065303/38862260-15368934-4252-11e8-9e5c-abfaa8304446.jpg)
![inkedwindows server 2012 vanila vm-2018-04-17-15-11-38_li](https://user-images.githubusercontent.com/35065303/38862343-4410a08c-4252-11e8-9fe1-286a2a6be8dd.jpg)

Even If I save, the pdf will be saved in the same format (i.e., broken pages)

Please suggest me any fixes.

Thanks in advance!!
Regards,
Ravi Kumar

**Comment by RaviGprec** [comment]
Hi @timvandermeij ,

Are you people working on this print issue or solution is already there?. Actually I'm waiting for the fix for this question for past one week .

Thanks 
Ravi Kumar

**Comment by timvandermeij** [comment]
I don't think anyone is working on this right now. Anyone is free to contribute a fix.

**Comment by zeel-pathak** [comment]
Hello, I am looking in this issue, and might soon come up with solution...

**Comment by Snuffleupagus** [comment]
> I'm developing PDF Viewer in Angular 5.

Given that *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is missing, the fact that we know nothing about "Angular" here (and generally cannot help without access to runnable code), and finally that the web-platform doesn't have great support for controlling printing via e.g. JavaScript; is it really meaningful to keep this issue open!?
