### ISSUE TITLE
Pdf is not fully loaded at once. 

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#9672]
Configuration:

Web browser and its version: Google Chrome : Version 63.0.3239.132 (Official Build) (64-bit)
Operating system and its version: Windows 10 x64
PDF.js version: 1.9.426
Is a browser extension: No

Issue: PDF is not fully loaded at once. Currently when we scroll the page at that time the current page of PDF is rendered. So I can't get html of whole PDF without scrolling . I want to render whole PDF at once when browser page is load.

Is there any method for render whole PDF at once without scrolling?

**Comment by timvandermeij** [comment]
You can just loop over all pages and render them explicitly, for example like we do in the SVG viewer example:

https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer/viewer.js#L15

**Comment by ice0526** [comment]
I have same Question, the answer do not give me a tip @timvandermeij

**Comment by damianfabian** [comment]
Any idea on how to do this on the current version? I'm using this code to load the PDF:

```
loadPDF(url) {
    const loadingTask = pdfjsLib.getDocument({
      url: url,
      cMapUrl: this.CMAP_URL,
      cMapPacked: this.CMAP_PACKED,
    });

    loadingTask.promise.then((pdfDocument) => {
      this.pdfDocument = pdfDocument;
      this.pdfLinkService.setDocument(pdfDocument, null);
      this.pdfViewer.setDocument(pdfDocument);
    });
  }
```

and this is how I'm trying to load the rest of the pages

```
loadAllPages() {

    const stop = this.pdfDocument.numPages || 3;
    const loadPage = (page) => {
      if(page === stop) { return; }
      this.pdfDocument.getPage(page).then(() => loadPage(page + 1))
    }
    loadPage(3)
  }
```
