### ISSUE TITLE
Drawing on Chrome get incrementally slower per page

### ISSUE THREAD

**Issue by StefanFeederle** [mozilla/pdf.js#9674]
Configuration:
- Web browser: Chrome 66
- OS: Win10 Pro 1709
- PDF.js version: CDN **//mozilla.github.io/pdf.js/build/pdf.js** and also **pdfjs-dist@2.0.104**
- Is a browser extension: No

Steps to reproduce the problem:
1. Draw 2-3 pages of a technical drawing on a high scale
2. Notice slowdown on Chrome

What is the expected behavior?
Consistent drawing performance over multiple pages.

What went wrong?
In chrome the drawing performance slows down with every page. My example takes 7sec to run on Chrome and 3sec on Edge. [JSFiddle](http://jsfiddle.net/6L0ggx1j/216/)

PDF used in the fiddle: [sample-pdf](http://stahlbau-feederle.de/large_pdf_drawing.pdf)

**Comment by Snuffleupagus** [comment]
> PDF used in the fiddle: [sample-pdf](http://stahlbau-feederle.de/large_pdf_drawing.pdf)

The PDF document is no longer accessible.

However, given that this issue seem to be platform/browser specific, rather than general PDF.js bug, it's unfortunately unlikely to be an actionable issue *here*.
