### ISSUE TITLE
PDF requires user interaction to load Android

### ISSUE THREAD

**Issue by Jhanbury** [mozilla/pdf.js#9678]
Configuration:
- Web browser and its version: Xamarin.Android browser
- Operating system and its version: Android 7.0
- PDF.js version: 1.10.88
- Is a browser extension: no

Steps to reproduce:
https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/display-pdf/

I am trying to load a PDF which is stored locally on a mobile device in the browser via a WebView.
When the PDF is loaded the viewer appears and a blank white screen is displayed.
When the user performs a user action i.e. zoom the PDF rerenders and appears as normal.
Is there any way for me to programmatically refresh the UI so that this can be avoided?

**Comment by timvandermeij** [comment]
Closing since we don't explicitly support the Xamarin implementation. Any questions should be directed to them.
