### ISSUE TITLE
pdf rendered completely blank

### ISSUE THREAD

**Issue by gHensges** [mozilla/pdf.js#9679]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 65
- Operating system and its version: windows 10
- PDF.js version: actual demo project
- Is a browser extension: no
[K BIS.PDF](https://github.com/mozilla/pdf.js/files/1929531/K.BIS.PDF)

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The image cannot be loaded: `Warning: Unable to decode image: JpegError: JPEG error: unexpected marker ffd9`

**Comment by timvandermeij** [comment]
Closing since this is fixed by the pull request above.
