### ISSUE TITLE
Extra blank page printed after each page on IE 11

### ISSUE THREAD

**Issue by IvanBoutin** [mozilla/pdf.js#9682]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11, 11.0.9600.18977
- Operating system and its version: Windows 7 Entreprise, Service pack 1
- PDF.js version: 1.9.426
- Is a browser extension: no

Steps to reproduce the problem:
1. Open PDF file linked to the issue
2. Print it on a printer, or in a file with the print button of the viewer

What is the expected behavior? (add screenshot)
No blanks pages

What went wrong? (add screenshot)
Extra blank page printed after each page of the PDF document attached. Don't have this problem in Chrome  64.0.3282.167. Don't see any blank page in the viewer. 

[DOC_191469.PDF](https://github.com/mozilla/pdf.js/files/1932732/DOC_191469.PDF)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
