### ISSUE TITLE
[chrome]Printing destination selection is not saved for the next use

### ISSUE THREAD

**Issue by Vimos** [mozilla/pdf.js#9683]
Each time I use printing in pdf.js, I have to select the printing option again. Can it be automatically saved for the next time?

The detailed information for my chrome
```
Version 66.0.3359.117 (Official Build) (64-bit)
```
PDF Viewer
```2.0.466```

There are `save to google drive` options in my printing destination, and printing preview is a bit slow.

**Comment by timvandermeij** [comment]
This option cannot be set form JavaScript, so this cannot be fixed here. If this is not yet fixed in the meantime, please report the bug to the Chrome bug tracker.
