### ISSUE TITLE
working in Chrome but not IE 11

### ISSUE THREAD

**Issue by rwu2359** [mozilla/pdf.js#9684]
HTML file attached which has embedded Base64 PDF

On Windows Server 2012 running in AWS land with IE 11.0.97

This file will render perfectly in Chrome but on IE, and also tested on windows 10 machines, this renders the chrome but a black document with apparently no content.

Using pdfjs ver 1.9.426

[viewer_63659903873045.html.zip](https://github.com/mozilla/pdf.js/files/1934408/viewer_63659903873045.html.zip)

**Comment by sameerg10** [comment]
I had this issue but solved it by disabling GPU rendering.

Internet Options > Advanced > "Use software rendering instead of GPU rendering*". Check this and see if it works after restarting IE. If it's checked, try un-checking and restart.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
