### ISSUE TITLE
why not support IE9? I want to run on IE9，what should I do ？

### ISSUE THREAD

**Issue by dep-darkLonely** [mozilla/pdf.js#9686]
How can pdf.js run on IE9?
this is important to me！what should I do？

**Comment by dep-darkLonely** [comment]
[
![image](https://user-images.githubusercontent.com/30953224/39174068-30b32c62-47d9-11e8-8282-5d83e3fa4a5d.png)
](url)

**Comment by brendandahl** [comment]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
