### ISSUE TITLE
PDF print incorrectly on linux

### ISSUE THREAD

**Issue by cdowen** [mozilla/pdf.js#9687]
Attach (recommended) or Link to PDF file here:
[PDF Here](https://arxiv.org/pdf/1704.07813.pdf)
Configuration:
- Web browser and its version: Firefox Desktop 59.0.2(64-bit) BuildId: 20180404120016
- Operating system and its version: Ubuntu Linux 16.04
- PDF.js version: PDF.js: 2.0.288

- Is a browser extension:Yes

Steps to reproduce the problem:
1. Try to print the document
2. Formulas on page 3 don't render correctly

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/2178804/39174206-9e2629b6-47d9-11e8-9ebc-a78639966108.png)

What went wrong? (add screenshot)
![screenshot from 2018-04-24 16-08-08](https://user-images.githubusercontent.com/2178804/39174313-fb400144-47d9-11e8-85eb-8659ba859490.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is an upstream bug, and the solution will require patching of Firefox; please refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1524640#c1.

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
