### ISSUE TITLE
Mark as webpack 4 compatible 

### ISSUE THREAD

**Issue by lorefnon** [mozilla/pdf.js#9688]
The [webpack version](https://github.com/mozilla/pdfjs-dist/blob/master/package.json#L19) in pdfjs-dist is currently  "^2.0.0 || ^3.0.0" though it works well with "^4.0.0" as well. 

Can you please mark this as 4.x compatible ? 

Webpack 4 has been out for a while and my applications currently using webpack 4.x are using pdfjs-dist without any problems but when I run npm install I get a spurious peer dependency version mismatch warning which I'd like to get rid of.

**Comment by timvandermeij** [comment]
I tried upgrading to Webpack 4 before and even though it worked locally, the testing infrastructure choked on it for reasons still unknown to me. Perhaps we should try again.

**Comment by lorefnon** [comment]
Hi Tim, thanks for looking into this. 

If you could point me to the build errors (with webpack 4) I might be able to help with the investigation.

**Comment by timvandermeij** [comment]
There were no build errors locally, but the test bots timed out after not being able to start the tests after 120 seconds, both on Windows and Linux. I do not recall having seen any errors in those logs.

**Comment by d4nc3r** [comment]
@timvandermeij is there anything we can do to help? I am also running into this problem - and since I'm at a very large company we need to use a shrinkwrap file, and can't shrinkwrap with errors or warnings :(

**Comment by jasco** [comment]
Currently debugging a case where webpack 4 production output of pdfjs-dist worker appears to render a mangled font in one particular case.  Using a debug build of the worker works fine.  Have not yet verified webpack 3 behavior because downgrading my config is proving troublesome.

**Comment by Codii** [comment]
@jasco Any news on this issue ? Did you find hints on what causes the mangled fonts ?

**Comment by jasco** [comment]
@codii yes, actually I did resolve the issue. It was tied to using webpack production optimizations on the PDF worker script. I ended up using the pdfjs-dist distribution's minified worker script as-is without running it through webpack.

**Comment by timvandermeij** [comment]
Fixed by the pull request above.

**Comment by DenisKrasnov** [comment]
Hi, when I switched to webpack 4 and changed the way to set up worker from `import pdfjsLib from "pdfjs-dist/webpack";` to `pdfjsLib.GlobalWorkerOptions.workerSrc = "/resources/pdf.worker.js";` I faced a problem that worker doesn't work. Despite the fact that the file pdf.worker.js exists in the bundle and is accessible I see the warning in the console `Warning: Setting up fake worker.`. Did I missed something? Does anyone have any ideas? 🤔

**Comment by Kailaash-Balachandran** [comment]
@DenisKrasnov I'm facing similar issue. How did you resolve this?

**Comment by Maskik** [comment]
Looks like it resolved in [this solution](https://github.com/plangrid/react-file-viewer/blob/master/src/components/drivers/pdf-viewer.jsx#L4)

try this:
```
import { PDFJS } from 'pdfjs-dist/build/pdf.combined';
import 'pdfjs-dist/web/compatibility';
```
_maybe you need to use lower version "pdfjs-dist": "1.8.357"_

**Comment by DenisKrasnov** [comment]
@Kailaash-Balachandran I have just downgraded the webpack to the version 3 but it was 12 months ago and didn't work with it anymore.
