### ISSUE TITLE
WARNING: MD5 of file "pdfs/file.pdf" does not match file.

### ISSUE THREAD

**Issue by brianholle** [mozilla/pdf.js#9691]
Configuration:
- Web browser and its version: Firefox 56.0.2
- Operating system and its version: Ubuntu 14.04.5 LTS / macOS 10.13.3
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1.   - npm install -g npm@latest
2.   - npm install -g gulp-cli
3.   - git submodule init
4.   - git submodule update
5.   - npm install
6.   - npm update
7.   - gulp makeref

What is the expected behavior? (add screenshot)
    A successful test run.

What went wrong? (add screenshot)
    We received the following MD5 match failures.

### Creating reference images
WARNING: MD5 of file "pdfs/bug1142033.pdf" does not match file. Expected "1d9afd397e89a0f52c056f449ec93daa" computed "404b3e5ad162360bf67235eaa53227ab"
WARNING: MD5 of file "pdfs/bug867484.pdf" does not match file. Expected "347af7b0ef7279b1a7f43b03bfda4548" computed "5851a2c2976a663e014ba7543bb2ac4d"
WARNING: MD5 of file "pdfs/bug1064894.pdf" does not match file. Expected "22971b6a24912bca9c773379c10ef18a" computed "592814c576880e9a2b97fee5bb6bb5f0"
WARNING: File was not downloaded. See "pdfs/issue2442.pdf.error" file.
WARNING: MD5 of file "pdfs/annotation-as.pdf" does not match file. Expected "e51500c8adc9edcdcc8ebc6a575c90ab" computed "36b0277275b6ad1ffa1b42edf5e1216b"
WARNING: MD5 of file "pdfs/bug888437.pdf" does not match file. Expected "93370cd589a08732a05601441c899bcb" computed "636737d52f969f7d8bc4e32481f5019a"
WARNING: MD5 of file "pdfs/bug1077808.pdf" does not match file. Expected "4a4bfc27e3fafe2f74e7a4a4cd04b8dc" computed "662710f3aa3188e2e812154a5727b7d2"
WARNING: MD5 of file "pdfs/bug1108753.pdf" does not match file. Expected "a7aaf92d55b4602afb0ca3d75198b56b" computed "5846a1791dab9c80be94d0fbc0734da4"
WARNING: MD5 of file "pdfs/bug865858.pdf" does not match file. Expected "7a81bd987dc1d95e9a0be46b7c3f2e18" computed "ee46c260967bd974770ae7a2cc3a78fd"
Unable to verify the checksum for the files that are used for testing.
Please re-download the files, or adjust the MD5 checksum in the manifest for the files listed above.

Is there a reason I am getting these warnings? Is there a way to make sure I have the latest and correct files?

**Comment by brendandahl** [comment]
Unfortunately, the files that are downloaded from various sites change over time. You'll likely be okay if you don't have all of the exact files.

**Comment by AbhimanyuVashisht** [comment]
I am also facing the same issue

**Comment by timvandermeij** [comment]
The issue mentioned above is now tracking this problem.
