### ISSUE TITLE
WARNING: MD5 of file "pdfs/file.pdf" does not match file. Tied to Browser Test Errors.

### ISSUE THREAD

**Issue by brianholle** [mozilla/pdf.js#9696]
https://github.com/mozilla/pdf.js/issues/9691
I posted this issue the other day and it was resolved saying that these warnings were not an issue. Upon further inspection I determined that these same files that triggered warnings were the same files involved in browser tests that were failing.

Running these tests are very important for the continuous integration of PDF.js into our project. Is there a solution to resolve any issues with these files? Below is the output of our test run:

`WARNING: MD5 of file "pdfs/bug1142033.pdf" does not match file. Expected "1d9afd397e89a0f52c056f449ec93daa" computed "204834c4f6f6d583145b67b3b66aceb6"
WARNING: MD5 of file "pdfs/bug867484.pdf" does not match file. Expected "347af7b0ef7279b1a7f43b03bfda4548" computed "6e404d563cb900b3e65ffc6c6e7e215d"
WARNING: MD5 of file "pdfs/bug1064894.pdf" does not match file. Expected "22971b6a24912bca9c773379c10ef18a" computed "fa3cee6e309396d1c38700612ea129fd"
WARNING: MD5 of file "pdfs/annotation-as.pdf" does not match file. Expected "e51500c8adc9edcdcc8ebc6a575c90ab" computed "93e8cb621a56b5de9513431e1b6c5e63"
WARNING: MD5 of file "pdfs/bug888437.pdf" does not match file. Expected "93370cd589a08732a05601441c899bcb" computed "5509a18dec7b4fc74358a5f0ca0f293a"
WARNING: MD5 of file "pdfs/bug1077808.pdf" does not match file. Expected "4a4bfc27e3fafe2f74e7a4a4cd04b8dc" computed "c9014662800b5e5af049847878f705be"
WARNING: MD5 of file "pdfs/bug1108753.pdf" does not match file. Expected "a7aaf92d55b4602afb0ca3d75198b56b" computed "a2ce6b0bc27d289133b15d6c38c77aca"
WARNING: MD5 of file "pdfs/bug865858.pdf" does not match file. Expected "7a81bd987dc1d95e9a0be46b7c3f2e18" computed "5f45bb10395a08806497d610351307e6"`

`TEST-UNEXPECTED-FAIL | test failed bug1142033 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug867484 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug1064894 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed annotation-as | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug888437 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug1077808 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug1108753 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure
TEST-UNEXPECTED-FAIL | test failed bug865858 | in Firefox | page1 round 1 | Loading PDF document: InvalidPDFException: Invalid PDF structure`

**Comment by timvandermeij** [comment]
It looks like the links to the PDF files on Bugzilla have changed. For example, `pdfs/annotation-as.pdf` (https://github.com/mozilla/pdf.js/blob/master/test/pdfs/annotation-as.pdf.link) links to https://bug741239.bugzilla.mozilla.org/attachment.cgi?id=611315, but that gives a webpage rather than the PDF file itself. That now appears to live at https://bug741239.bmoattachments.org/attachment.cgi?id=611315. This should definitely be fixed on our side by updating these links.

**Comment by timvandermeij** [comment]
Closing since this is fixed by the pull request above.
