### ISSUE TITLE
PDF.js should abort fetch requests during teardown

### ISSUE THREAD

**Issue by johnhok** [mozilla/pdf.js#9698]
Steps to reproduce the problem:
1. Fetch a document with streaming enabled.
2. Destroy the document loading task
3. Observe that the fetch request is not aborted.

What is the expected behavior?
Fetch request should be aborted when cancel is called on `PDFFetchStreamReader` and `PDFFetchStreamRangeReader`.

**Context**
It seems when fetch was implemented (https://github.com/mozilla/pdf.js/issues/6126#issuecomment-130572300) `abort` on fetch was still in flux. 

It seems now that has settled and chromium has also implemented aborting fetch requests in 66 (https://bugs.chromium.org/p/chromium/issues/detail?id=750599)

**Comment by Rob--W** [comment]
Sounds good to me. Make sure to use feature detection before using `AbortController`.

**Comment by mukulmishra18** [comment]
> Make sure to use feature detection before using `AbortController`.

Okay, sure. I will try to create a PR for this tonight.
