### ISSUE TITLE
Photon design

### ISSUE THREAD

**Issue by nt1m** [mozilla/pdf.js#9702]
It would be nice if PDF.js's design would be in line with Firefox's.

To do that, here are some quick changes that would be possible:
* Remove background gradients/textures
* Use photon colors: https://design.firefox.com/photon/visuals/color.html#grey (use visual layering to pick shades of gray: https://mozilla.invisionapp.com/share/J6GQCZR2PZY#/screens/289803032_Desktop_Common)
* Use photon icons: https://design.firefox.com/icons

**Comment by Huluti** [comment]
It's true that the reader looks very outdated... compared to the browser

**Comment by timvandermeij** [comment]
Fixed by #11077.
