### ISSUE TITLE
Chinese characters being clipped on Edge/360Chrome

### ISSUE THREAD

**Issue by yume-chan** [mozilla/pdf.js#9703]
Attach (recommended) or Link to PDF file here:

[1148.pdf](https://github.com/mozilla/pdf.js/files/1978781/1148.pdf)

Configuration:
- Web browser and its version: Microsoft Edge 42.17134.1.0 / 360Chrome 9.0.1.156 (based on Chromium 55.0.2883.87)
- Operating system and its version: Windows 10 1803 / Windows 10 1607
- PDF.js version: 2.0.493 / 1.9.426
- Is a browser extension: No / No

Steps to reproduce the problem:
1. Open the attached pdf file with Microsoft Edge or 360Chrome browser

What is the expected behavior? (add screenshot)

![image](https://user-images.githubusercontent.com/1330321/39689320-ed34a3dc-5208-11e8-8375-eb07ba92146f.png)
(Chromium 55.0.2883.87)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/1330321/39689600-fc7fe300-5209-11e8-9cc0-837252d01edd.png)
(Microsoft Edge)

![image](https://user-images.githubusercontent.com/1330321/39689406-3a6c2fc6-5209-11e8-8e53-04d4fb842831.png)
(360Chrome)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

N/A

**Comment by yume-chan** [comment]
I can workaround this issue by appending `<script>pdfjsDistBuildPdf.PDFJS.disableFontFace = true;</script>` after `
<script src="../build/pdf.js"></script>` in `viewer.html`, seems relates to font rendering.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Microsoft Edge 42.17134.1.0 / 360Chrome 9.0.1.156 (based on Chromium 55.0.2883.87)

@timvandermeij Given that all other IE Edge issues have now been closed and that we've never claimed to support [360Chrome](https://en.wikipedia.org/wiki/360_Secure_Browser), combined with the fact that this looks entirely like a platform/browser bug, should this issue just be closed as WONTFIX?
