### ISSUE TITLE
Print as pdf from google docs not being parsed correctly by pdfjs

### ISSUE THREAD

**Issue by Nnamdi101** [mozilla/pdf.js#9709]
Attach (recommended) or Link to PDF file here:
[test_google_2.pdf](https://github.com/mozilla/pdf.js/files/1989663/test_google_2.pdf)

Configuration:
- Web browser and its version: Google chrome Version 65.0.3325.181
- Operating system and its version: Mac OS High Sierra version 10.13.4
- PDF.js version: 2.0.489
- Is a browser extension: yes

Steps to reproduce the problem:
1. Create a document on google docs with hyphens in it
2. Go to print->save->save as pdf(or use attached pdf)
3. Use pdf js to extract text. Example snippet that extracts text below
```js
function retrieveTextContent(page) {
    var params = {
      normalizeWhitespace: true,
      disableCombineTextItems: true
    }
    return page.getTextContent(params).then(joinTextContent);
  }
```
What is the expected behavior? (add screenshot)
all characters including hyphens are extracted

What went wrong? (add screenshot)
Hyphens are omitted

<img width="568" alt="screen shot 2018-05-09 at 5 42 56 pm" src="https://user-images.githubusercontent.com/17769444/39842668-58baaaea-53b5-11e8-95d5-3ebbae754d78.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A because of extension

**Comment by Nnamdi101** [comment]
@timvandermeij any word back about this?

**Comment by timvandermeij** [comment]
Unfortunately not, this needs to be investigated.

**Comment by calixteman** [comment]
I just copied/pasted the string containing hyphens and everything works fine so it should be the same with `getContent`.
For your information, the "hyphens" are represented by "soft hyphens" (see https://en.wikipedia.org/wiki/Soft_hyphen) and it seems that Firefox devtools doesn't show them (the same in Chrome, just try `(s="\u00AD",[s, s.charCodeAt(0).toString(16)])` to reproduce).
