### ISSUE TITLE
viewer.html not loading demo pdf in Microsoft Edge

### ISSUE THREAD

**Issue by greddyatpt** [mozilla/pdf.js#9711]
This issue was there a while ago but it was closed.  Not sure if it's a regression or was never fixed... it's happening again in Edge.  The demo doc doesn't load if you clone the latest code but it does work in the stable build.

**Comment by greddyatpt** [comment]
The latest code works in Chrome but seems to be a lot slower than the stable build.

**Comment by timvandermeij** [comment]
If it doesn't load, are there any messages in the browser's console?

**Comment by timvandermeij** [comment]
Closing since the issue is not actionable without more information.
