### ISSUE TITLE
PDF.js loaded asynchronous is giving error

### ISSUE THREAD

**Issue by Motard** [mozilla/pdf.js#9712]
I am using pdf.js and I am having the following problem:

When I load the pdf.js with `<!--<script src="vendor/js/pdfjs/pdf.js"></script>-->` I have no issue.

But when I try to load the file in a asynchronous way like this `(function(){
        var bsa = document.createElement('script');
        bsa.type = 'text/javascript';
        bsa.async = true;
        bsa.src = 'vendor/js/pdfjs/pdf.js';
        (document.getElementsByTagName('body')[0]).appendChild(bsa);
    })();`

I have an error in this `this.viewer = options.viewer || options.container.firstElementChild;` both viewer and container are null.

And the strange thing is I added a breakpoint in that line of code.

So when I load the file with `<!--<script src="vendor/js/pdfjs/pdf.js"></script>-->` that breakpoint does not happen. It only happens when I select a file to be seen with the pdf-viewer.

But when I load the pdf.js asynchronously as soon as the file finishes loading that breakpoint is called.

Do you have any ideia why this is happening?

Thx
Paulo Martins

**Comment by Snuffleupagus** [comment]
Generally speaking, if the `pdf.js` file hasn't already been loaded by the time that the `viewer.js` file (or `pdf_viewer.js` file if you're using the components) then things will simply not work correctly since the viewer depends on being able to access properties/functions exported by `pdf.js`. 

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
