### ISSUE TITLE
The copy of a selected text part in the viewer loose line breaks

### ISSUE THREAD

**Issue by RuelleAnthony** [mozilla/pdf.js#9714]
**Attached PDF:**
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/1994600/compressed.tracemonkey-pldi-09.pdf)

**Configuration:**
- Latest version of pdf js ==> https://mozilla.github.io/pdf.js/web/viewer.html

**Steps to reproduce the problem:**
1.  Copy part of text on several lines. Example: 
![image](https://user-images.githubusercontent.com/37692552/39915923-8092e65e-5509-11e8-8aec-64f4923a50c4.png)

2. Paste in document text editor. 

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/37692552/39916063-d650c00c-5509-11e8-9742-40f5b487bf12.png)

Acrobat Reader do this

**What went wrong?**
All text is on same line...

![image](https://user-images.githubusercontent.com/37692552/39916048-cc5a62ce-5509-11e8-8c1e-eeb79325f746.png)

**Comment by Snuffleupagus** [comment]
WFM, most likely fixed by PR #13257.
