### ISSUE TITLE
Bad rendering result on Mac

### ISSUE THREAD

**Issue by rlisario** [mozilla/pdf.js#9715]
Dear all,
I've used pdf.js library to have a preview of PDF files in my Java application.

On same Mac  (MacBook Pro with MACOSX 10.12.6) I have a problem with rendering result.

As see in attached, it seems all doubled.

![screenshot_20180510-222405](https://user-images.githubusercontent.com/34242916/39919155-0f5024e8-5513-11e8-9e90-74d3e3a84934.jpg)

Somebody have any suggestions?

Bye,
Rinaldo

**Comment by THausherr** [comment]
Please attach your PDF and try with https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
Closing since the issue is not actionable without more information. It can be reopened once a PDF file is attached.
