### ISSUE TITLE
Take advantage of linearization dictionary to get the first page

### ISSUE THREAD

**Issue by johnhok** [mozilla/pdf.js#9716]
In the base viewer example `pdfDocument.getPage(1)` is used to size the viewport. 

When PDF.js gets the first page, it doesn't take advantage of the linearization dictionary, instead it relies on grabbing the full page tree (in a large PDF, this could be a performance issue due to multiple range requests being made to grab the table).

What is the expected behavior?
It seems, PDF.js should take advantage of the linearization dictionary when available to speed up getting the first page.

**Comment by sahil107** [comment]
be

**Comment by johnhok** [comment]
I have an implementation of this, I could take a stab at opening a PR soon that will do as described.
