### ISSUE TITLE
Printing failing with mathematical characters.

### ISSUE THREAD

**Issue by ericrboidi** [mozilla/pdf.js#9721]
Attach (recommended) or Link to PDF file here: 
[before.pdf](https://github.com/mozilla/pdf.js/files/1998548/before.pdf)

Configuration:
- Web browser and its version: FF 60.0 Quantum
- Operating system and its version: Win10 Pro Ver 1709 Build 16299.431
- PDF.js version: I think 2.0.402?
- Is a browser extension: From FF

Steps to reproduce the problem:
1. Open document
2. Attempt printing,

What is the expected behavior? The printing reproduces the PDF file faithfully.

What went wrong? Random box characters, wrong text formatting: 
[after.pdf](https://github.com/mozilla/pdf.js/files/1998569/after.pdf)

(this is from the MS PDF printer, but it happened on my real life printer too)

**Comment by gpcf** [comment]
I can confirm that this happens. While printing http://www1.itp.tu-berlin.de/schaller/download/ELDN.pdf, this happens: 
[mozilla-bug.pdf](https://github.com/mozilla/pdf.js/files/2534838/mozilla-bug.pdf)

**Comment by ChronicLynx** [comment]
I can confirm, I've experienced this as well on several documents.

**Comment by Snuffleupagus** [comment]
This is an upstream bug, and the solution will require patching of Firefox; please refer to https://bugzilla.mozilla.org/show_bug.cgi?id=1524640#c1.

**Comment by Snuffleupagus** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1524640, which is now in the latest Nightly.

To easily verify this, run `PDFViewerApplication.cleanup()` in the web console before printing the PDF file.
