### ISSUE TITLE
Build on Win10: JavaScript heap out of memory

### ISSUE THREAD

**Issue by pgill1** [mozilla/pdf.js#9723]
Just trying to build latest on Win10.  I followed the instructions but the build fails after running for moreb than 30 minutes with error "JavaScript heap out of memory".  Here's what I get:

C:\WINDOWS\system32>**cd \pdf.js**

C:\pdf.js>**node-v8.11.1-win-x64\nodevars.bat**
Your environment has been set up for using Node.js 8.11.1 (x64) and npm.

C:\pdf.js>**git clone git://github.com/mozilla/pdf.js.git**
Cloning into 'pdf.js'...
remote: Counting objects: 52452, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 52452 (delta 0), reused 0 (delta 0), pack-reused 52443
Receiving objects: 100% (52452/52452), 70.46 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (36614/36614), done.

C:\pdf.js>**cd pdf.js**

C:\pdf.js\pdf.js>**npm install -g gulp-cli**
C:\pdf.js\node-v8.11.1-win-x64\gulp -> C:\pdf.js\node-v8.11.1-win-x64\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@2.0.1
added 238 packages in 11.013s

C:\pdf.js\pdf.js>**npm install**
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN notice [SECURITY] minimatch has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.2.14 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=1.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=2.0.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\pdf.js\pdf.js\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1431 packages in 79.769s

C:\pdf.js\pdf.js>**gulp generic**
[21:41:31] Using gulpfile C:\pdf.js\pdf.js\gulpfile.js
[21:41:31] Starting 'buildnumber'...

### Getting extension build number
[21:41:31] Starting 'locale'...

### Building localization files
Extension build number: 495
[21:41:31] Finished 'buildnumber' after 291 ms
[21:41:31] Finished 'locale' after 766 ms
[21:41:31] Starting 'generic'...

### Bundling files into pdf.js
[21:41:48] Version: webpack 3.12.0
        Asset    Size  Chunks                    Chunk Names
    viewer.js  382 kB       0  [emitted]  [big]  main
viewer.js.map  652 kB       0  [emitted]         main

<--- Last few GCs --->

[6608:000001CDE9137230]  3946673 ms: Mark-sweep 4112.8 (4233.9) -> 4112.8 (4192.4) MB, 4002.7 / 0.0 ms  last resort GC in old space requested
[6608:000001CDE9137230]  3950498 ms: Mark-sweep 4112.8 (4192.4) -> 4112.8 (4192.4) MB, 3824.3 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000CC94E257C1 <JSObject>
    2: _parseMappings(aka SourceMapConsumer_parseMappings) [C:\pdf.js\pdf.js\node_modules\babel-core\node_modules\source-map\lib\source-map-consumer.js:463] [bytecode=000002499332D161 offset=190](this=0000008957123C99 <BasicSourceMapConsumer map = 000002D0DFC442B1>,aStr=000000895710ECA1 <Very long string[126322]>,aSourceRoot=000001AF74C02201 <null>)
    3: computeColumnSpans(aka SourceMapConsu...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 6: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 7: v8::internal::StringTable::LookupString
 8: v8::internal::StringTable::LookupString
 9: v8::internal::SourcePositionTableIterator::Advance
10: v8::internal::SourcePositionTableIterator::Advance
11: 000001FB3A0843C1

C:\pdf.js\pdf.js>

**Comment by timvandermeij** [comment]
Closing since this is fixed by #9759.
