### ISSUE TITLE
Printing - IE11 - content is pushed and cropped

### ISSUE THREAD

**Issue by O-Massol** [mozilla/pdf.js#9724]
Configuration:
- Web browser and its version: IE11 - version 11.0.9600.18978 - update version 11.0.56 (KB4092946)
- Operating system and its version: Windows 8.1 professional
- PDF.js version: 1.10.88 & 1.9.426
- Is a browser extension: no

Steps to reproduce the problem:
1. Opening the pdf file
2. Printing the pdf file
You may use the original.pdf file for testing purpose. 
[original.pdf](https://github.com/mozilla/pdf.js/files/2001339/original.pdf)

What is the expected behavior? (add screenshot)
The printed document looks like the pdf file.
Please see expected.pdf. 
[expected.pdf](https://github.com/mozilla/pdf.js/files/2001333/expected.pdf)

What went wrong? (add screenshot)
The printed document is altered : On each page, there is a PDF.js viewer indication top left, a page count top right, a filename down left and a date down right.
The content is cut on the right and the extra text (pdf.js mention, page count, filename and date) push some content to the next page.
Please see wrong.pdf. 
[wrong.pdf](https://github.com/mozilla/pdf.js/files/2001330/wrong.pdf)

**Comment by Coyote555** [comment]
Hello, 

I saw here (https://github.com/mozilla/pdf.js/issues/3983) that there was printing fixes in 1.10.88. 
Even using this pre-release version, i have the aforementionned behavior. 

Is there any workaround for this kind of problem ?

Best regards, 
Olivier

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
