### ISSUE TITLE
I would like to prevent the text in pdf from being dragged and copied.

### ISSUE THREAD

**Issue by choidroid** [mozilla/pdf.js#9725]
good after noon

I would like to prevent the text in pdf from being dragged and copied.
Or I want to prevent the selection of text in pdf.
The purpose is to prevent security problems by copying / pasting the text in pdf.

Thank you again today.

**Comment by timvandermeij** [comment]
You can set https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L12 (the text layer mode preference) to `0` to disable text layer rendering.
