### ISSUE TITLE
how to detect vector shapes in pdf pages

### ISSUE THREAD

**Issue by darkworks** [mozilla/pdf.js#9728]
Attach (recommended) or Link to PDF file here: 
[test4.pdf](https://github.com/mozilla/pdf.js/files/2007516/test4.pdf)

Configuration:
- Web browser and its version:  chrome latest
- Operating system and its version:  win 7
- PDF.js version: latest from mozilla cdn
- Is a browser extension:  no

i can detect text , images in pdf pages but do not know how to detect vector shapes , i checked wiki pages but no found any useful related to it 

so any idea how to detect vectors in pdf that page have vectors or not , like the pdf i attached , page 1 have text , page 2 have vector shapes , and page 3 have image. so am stuck with page 2 vector shape detection that page have it or not .

examples 

with page 1 to detect text am doing something like

```
      page.getTextContent({ normalizeWhitespace: true }).then(function (textContent) {
        textContent.items.forEach(function (textItem) {
	//	console.log(textItem.str);	  
        });
      });
```

with page 3 to detect images doing something like

```
				var ops = await page.getOperatorList();						
				for (let j=0; j < ops.fnArray.length; j++) {
			        if (ops.fnArray[j] == pdfjsLib.OPS.paintJpegXObject || ops.fnArray[j] == pdfjsLib.OPS.paintImageXObject) {
				   var op = ops.argsArray[j][0];
			            var img = page.objs.get(op);
}
}
```
page 2 .... problem 

thanks

**Comment by timvandermeij** [comment]
Vector shapes are not one entity in PDF documents, but are instead composed of various operations, such as line drawing and filling (see https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js#L174 for the list of existing operations), hence there is no easy way to extract vector shapes unfortunately.

**Comment by darkworks** [comment]
hmmmm how about just detection that this pdf page have line or other drawing ,
thanks

**Comment by darkworks** [comment]
ok thanks

**Comment by timvandermeij** [comment]
In that case the rectangle and circle are drawn onto the annotation layer, which are already SVG elements. Refer to https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L898-L938 for how they're drawn.
