### ISSUE TITLE
Incorporate search and other functions into core viewer

### ISSUE THREAD

**Issue by risoms** [mozilla/pdf.js#9731]
Hello. From the looks of what I’ve seen so far this looks like a nice product.
I have (hopefully) a simple question. 
I’m interested in using the core application but I’m interested in including a search function and a few other things. If I wanted to make a build of this for the browser (not using the viewer) incorporating the modules/plugins/? pdf_find_controller, debugger, and download_manager what would be the best way to do it? 

Trying to parse how viewer.js works is rather difficult so I’m hoping to apply this with the core viewer as seen here https://mozilla.github.io/pdf.js/examples/

Thank you again for your work on this!

**Comment by timvandermeij** [comment]
From your description I think the easiest way is to build your own viewer from our viewer components. There is actually an example in the codebase that looks like it matches your expectations quite a bit: https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js#L58

**Comment by risoms** [comment]
Thanks. I’ll try it out and report back if there’s any issues. Otherwise great job!
