### ISSUE TITLE
How to get the raw lines' text content?

### ISSUE THREAD

**Issue by betterRunner** [mozilla/pdf.js#9732]
Hello mozilla, I got a problem about the text content.

As we know, the function `page.getTextContent()` returns a list of text, but they are not actually the raw lines of text of pdf (for example, if line 9 in page1 contains more than one font type, it will be seperated into multiple lines like "I", ''', "m a student.").
So is there any function to get the text of raw line of pdf?

Thank you so much.

**Comment by skyjust** [comment]
no way, beacause two text operator belong diffrent operator instance. do it youself

**Comment by Snuffleupagus** [comment]
Given that there's not really any concept of "lines" in the PDF specification, and that glyphs are rather positioned absolutely, there's (generally) no way to get the desired output from `getTextContent` here; hence I'd suggest closing this issue since it isn't actionable.
