### ISSUE TITLE
Attempt to remove usage of `makeSubStream` in src/core/type1_parser.js

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#9735]
*I was recently sorting through and throwing out old notes, when I found this and figured it wouldn't hurt to at least submit an issue.*

In `Type1Parser`, there's currently two usages of `makeSubStream` that seem completely unnecessary; see https://github.com/mozilla/pdf.js/blob/7ba50448fdef660d22b799b5814af36ad63407c4/src/core/type1_parser.js#L562-L566 and https://github.com/mozilla/pdf.js/blob/7ba50448fdef660d22b799b5814af36ad63407c4/src/core/type1_parser.js#L585-L589

Using `makeSubStream` in that fashion makes the code look more convoluted than necessary, and should also be less efficient since it causes a new `Stream` to be initialized when all that's really needed here is to get a known number of bytes from the already available stream.

At least in theory, although testing is *obviously* required, it should be possible to replace each of those blocks with the following code instead
```javascript
lenIV = program.properties.privateData['lenIV'];
encoded = this.readCharStrings(stream.getBytes(length), lenIV);
```

Since this issue could potentially be a candidate for the `5-good-beginner-bug` label, I'm including a link to https://github.com/mozilla/pdf.js/wiki/Contributing for good measure. Especially the sections "Generating reference images" and "Run testing" is of particular importance, for anyone wanting to work on this.

**Comment by dominictwlee** [comment]
I'll give this a shot! Will report back in a couple of days.

**Comment by dominictwlee** [comment]
Ran ```gulp makeref``` and got this:
```
### Creating reference images
WARNING: MD5 of file "pdfs/bug1142033.pdf" does not match file. Expected "1d9afd397e89a0f52c056f449ec93daa" computed "12a48b558ef7d5b09857e993be6dad56"
WARNING: MD5 of file "pdfs/bug867484.pdf" does not match file. Expected "347af7b0ef7279b1a7f43b03bfda4548" computed "5ee3cd2701fab66f9c7ab6317df9d3da"
WARNING: MD5 of file "pdfs/bug1064894.pdf" does not match file. Expected "22971b6a24912bca9c773379c10ef18a" computed "22a2f350970ac7c7874c454149a4d163"
WARNING: File was not downloaded. See "pdfs/issue2442.pdf.error" file.
WARNING: MD5 of file "pdfs/annotation-as.pdf" does not match file. Expected "e51500c8adc9edcdcc8ebc6a575c90ab" computed "0d9b822e9f3e5c6174a73fe583ef1b69"
WARNING: MD5 of file "pdfs/bug888437.pdf" does not match file. Expected "93370cd589a08732a05601441c899bcb" computed "0359572a5a925902dd8f8ab772b676e0"
WARNING: MD5 of file "pdfs/bug1077808.pdf" does not match file. Expected "4a4bfc27e3fafe2f74e7a4a4cd04b8dc" computed "9adaf2defa4553c909e5d168792a2dac"
WARNING: MD5 of file "pdfs/bug1108753.pdf" does not match file. Expected "a7aaf92d55b4602afb0ca3d75198b56b" computed "33634b8d5d0b5a4577e2dbeac24a13a8"
WARNING: MD5 of file "pdfs/bug865858.pdf" does not match file. Expected "7a81bd987dc1d95e9a0be46b7c3f2e18" computed "b8d1f128948c15577b223e1985721c31"
Unable to verify the checksum for the files that are used for testing.
Please re-download the files, or adjust the MD5 checksum in the manifest for the files listed above.
```

How do I go about re-downloading those files?

**Comment by timvandermeij** [comment]
It requires #9696 to be fixed first. I'd say for now you can ignore those files because our test bot has them and we'll trigger the test bot for a pull request anyway.

**Comment by AbhimanyuVashisht** [comment]
Is this particular issue still pending?

**Comment by timvandermeij** [comment]
No, there is already a pull request submitted above.

**Comment by AbhimanyuVashisht** [comment]
Is there any issue in the PR? why is this issue not closed till now if everything is sorted?

**Comment by timvandermeij** [comment]
The pull request itself looks good, but we are having some problems with our testing infrastructure that prevent us from merging it. After that's done, this issue will be closed automatically.
