### ISSUE TITLE
PDF is not rendering properly. Getting console warning Failed to load font "g_d0_f21".

### ISSUE THREAD

**Issue by iamsojha** [mozilla/pdf.js#9747]
Attach (recommended) or Link to PDF file here:
Link to pdf = https://firebasestorage.googleapis.com/v0/b/test-68d26.appspot.com/o/notrenderingproperly.pdf?alt=media&token=8e5ba4bf-1fe0-4826-97c2-875c0f82336c

password to pdf: NTg0MjljYzg5NTg4YTM1ZjBiOTUyNzFk

Configuration:
- Web browser and its version: Google Chrome, Version 66.0.3359.181 (Official Build) (64-bit)

Steps to reproduce the problem:
1. go to https://jsfiddle.net/ssojha95/hgpmcqyo/1/ this fiddle and run the fiddle. it is the exact same as pdfJs example fiddle(https://jsfiddle.net/pdfjs/9engc9mw/?utm_source=website&utm_medium=embed&utm_campaign=9engc9mw). in both the places it is not working and pdf is not rendering properly.

2.But if i go to pdfjs demo (https://mozilla.github.io/pdf.js/web/viewer.html) and download and upload the pdf it is working fine. 

3. I am getting warning in the console failed to load some fonts. I am unable to figure out what is the issue.

What is the expected behavior? (add screenshot)
![screen shot 2018-05-22 at 2 46 11 pm](https://user-images.githubusercontent.com/20751006/40353356-f0e16340-5dce-11e8-9940-16e78b1f06fb.png)

What went wrong? (add screenshot)
![screen shot 2018-05-22 at 2 47 11 pm](https://user-images.githubusercontent.com/20751006/40353418-1b90f786-5dcf-11e8-8cbd-7a32ea126024.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by SamyCookie** [comment]
@iamsojha the PDF file is not accessible anymore, could you reupload it ?

**Comment by SamyCookie** [comment]
That was I tried to verify, and it also renders fine on my computer with last pdf.js, I think this issue can be closed !

**Comment by timvandermeij** [comment]
Thank you for verifying this! Closing.

**Comment by iamsojha** [comment]
Thanks. WIth latest pdf.js dist its working fine.
