### ISSUE TITLE
PDFJS.getDocument - advanced exception/error handling

### ISSUE THREAD

**Issue by demonslord** [mozilla/pdf.js#9750]
Hello,
I've the simple question, how I can handle the error exception when do PDFJS.getDocument?
I have some validations on server, on request of pdf file, and throw exception on fail. Also, the server pass the error exception json in header and HTTP status = 500.

What I have:

```javascript
pdfjsLib.getDocument().then(function(pdfdoc){...}).catch(function(error){...});
```
After my check, I noticed in fetch_stream.js this code:

```javascript
    fetch(url, createFetchOptions(this._headers, this._withCredentials)).
        then((response) => {
      if (!validateResponseStatus(response.status)) {
        throw createResponseStatusError(response.status, url);
      }
      this._reader = response.body.getReader();
      this._headersCapability.resolve();
      ...
    }).catch(this._headersCapability.reject);
```
After the validation of status code, the pdf.js throw exception ("createResponseStatusError") but pass response.status only.
If I set the breakpoint and debug, I can see my exception in :

```javascript
response.headers.get("exception")
```
So, how I can handle/get the response in catch?

```javascript
.catch(function(error){...});
```

**Suggestion:**
Pass the `response` object into the exception (promise reject). Also, will be useful if something come in response body:

```javascript
if (!validateResponseStatus(response.status)) {
  throw createResponseStatusError(response.status, url, response);
}
```

Thanks.

Best Regards.
Alexander

**Comment by timvandermeij** [comment]
The `getDocument` API endpoint returns a loading task, not a regular promise. How to catch the exception is excellently explained here: https://github.com/mozilla/pdf.js/issues/7763#issuecomment-329751723

**Comment by demonslord** [comment]
@timvandermeij 
I'm sorry...I cut the code too much...you're right about the loaderTask.
But still have problems with catching the request.

Alex

**Comment by timvandermeij** [comment]
Thank you. I have reopened the issue to track enriching the response object.

**Comment by demonslord** [comment]
@timvandermeij

> I have reopened the issue to track enriching the response object.

Yes, I think it will be useful receive the response object on promise reject and/or createResponseStatusError function.

Best Regards,
Alexander

**Comment by alexnez96** [comment]
Any chance the network response could be included in the error object? It could be under a prop e.g. `originalError`. This will help with error handling on the front-end.

**Comment by Snuffleupagus** [comment]
> It could be under a prop e.g. `originalError`. This will help with error handling on the front-end.

Unfortunately that's not possible, since it would cause breaking `DataCloneError: The object could not be cloned.` errors because `Response` objects cannot be serialized.

Hence I'd suggest closing this issue as WONTFIX, since this cannot be fixed.
