### ISSUE TITLE
can not find the pdf file in the first time,and in the next time is ok

### ISSUE THREAD

**Issue by Mengbuxiu** [mozilla/pdf.js#9760]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  I used this model "http://mozilla.github.com/pdf.js/web/viewer.html?file=compressed.tracemonkey- 
     pldi-09.pdf" to get my pdf on server. The pdf.js can not find the pdf file in the first time,and in the 
     next time is ok 
2. response message is can not found pdf file.
3. now I try catch the error ,and reload the page,but..it doesn't work. can u help me?

**Comment by timvandermeij** [comment]
There is not nearly enough information for us to work with. Please provide a minimal example that shows the issue. It sounds like your server is not always responding correctly, or it doesn't get range request right.
