### ISSUE TITLE
how to implement the rotation??? 

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [mozilla/pdf.js#9761]
how to implement the rotation??
i want to image rotation in my project.
but i have many issue.
this project was implemented the rotation that the image makes rotated image.. 
this function use libaray??
please help me...

**Comment by timvandermeij** [comment]
Closing since this is incomplete. You did not provide any example code that shows the problems you have. Rotation of pages is available in e.g., the default viewer.
