### ISSUE TITLE
Looking up annotation's destination

### ISSUE THREAD

**Issue by jsjolen** [mozilla/pdf.js#9762]
# Problem description

Given an InternalLink annotation with some id such as 2R how do you most efficiently look up what page this annotation is pointing at?

# My solution

Given an id and a page, the following code does the lookup:

```
pdfDocument.getPage(page).then((p) => {
    p.getAnnotations((annots)=> {
// Just iterate the annotation and find the one with the same ID as the ID provided
        let a = utils.find(annots, id, (a) => a.id); 
        if(a) {
            let dst = a.dest; // Some long ID like 'YSCDB916BIB1'
            pdfDocument.getDestination(dst).then((lookingFor) => {
                // By now we've got {num,gen} object and need to
                // iterate through all the pages and access the .pageInfo property
                // to find which one is equal to lookingFor
            });
        }
    });
});
```

There must be a better way of doing this, I can't find the equivalent code in the example viewer.

**Comment by Snuffleupagus** [comment]
> ```
> pdfDocument.getDestination(dst).then((lookingFor) => {
>   // By now we've got {num,gen} object and need to
>   // iterate through all the pages and access the .pageInfo property
>   // to find which one is equal to lookingFor
> ```

There's no need to iterate anything here, since assuming that you've managed to obtain a Reference (i.e. an object with `num` and `gen` properties) you can simply use the `getPageIndex` method; please refer to https://github.com/mozilla/pdf.js/blob/c2cbeaa34d81bbb7cced856e2888867df587a1fa/src/display/api.js#L612-L620

**Comment by timvandermeij** [comment]
@jsjolen Is the above enough to answer this question or is there more you want to know here?

**Comment by jsjolen** [comment]
@timvandermeij  I am satisfied with this answer! Thank you.


@Snuffleupagus Thank you for the link!
