### ISSUE TITLE
Background portrait in PDF not rendered in pdf.js

### ISSUE THREAD

**Issue by kicktheken** [mozilla/pdf.js#9763]
Attach PDF file here: [tatertots-portrait.pdf](https://github.com/mozilla/pdf.js/files/2060602/tatertots-portrait.pdf)

```
Title:          PowerPoint Presentation
Creator:        Acrobat PDFMaker 18 for PowerPoint
Producer:       Adobe PDF Library 18.9.66
CreationDate:   Sun Jan 21 20:41:25 2018 PST
ModDate:        Thu May 31 17:42:32 2018 PDT
Tagged:         yes
UserProperties: no
Suspects:       no
Form:           AcroForm
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      1920 x 1080 pts
Page rot:       0
File size:      995873 bytes
Optimized:      no
PDF version:    1.6
```

Configuration:
- Web browser and its version: Chrome OSX 66.0.3359.181, Firefox 60.0.1 (64-bit)
- Operating system and its version: macOS High Sierra 10.13.4
- PDF.js version: Latest in https://mozilla.github.io/pdf.js/web/viewer.html as of 2018-05-31 
- Is a browser extension: no

Steps to reproduce the problem:
1. Open attached file in Mac PDF viewer or via Chrome 66.0.3359.181
2. View attached file in Firefox 60.0.1 or on Chrome 66.0.3359.181 via  https://mozilla.github.io/pdf.js/web/viewer.html

Expected:
![tatertots-portrait_good](https://user-images.githubusercontent.com/74350/40815620-934ff856-64fc-11e8-91b7-9c0935d7ff0f.png)

Actual:
![tatertots-portrait_bad](https://user-images.githubusercontent.com/74350/40815646-af779782-64fc-11e8-9ef3-0fcf376d2d53.png)

**Comment by janpe2** [comment]
The background portrait is a tiling pattern that has huge steps: `/XStep 2147480000.0 /YStep 2147480000.0`

**Comment by Snuffleupagus** [comment]
> The background portrait is a tiling pattern that has huge steps: /XStep 2147480000.0 /YStep 2147480000.0

Given the above analysis, PR #6606 might be relevant here!?
