### ISSUE TITLE
jquery.ajax request server return filestream(200MB),client browser google prompt memory insufficient

### ISSUE THREAD

**Issue by tenglongwentian** [mozilla/pdf.js#9767]
jquery.ajax request server return filestream(200MB),client browser google prompt memory insufficient

**Comment by Hyoutei** [comment]
666

**Comment by Hyoutei** [comment]
six,six,six

**Comment by Hyoutei** [comment]
It may be caused by the lack of browser virtual memory. Try to modify the browser's virtual memory and hope to help you.

**Comment by timvandermeij** [comment]
Yes, this is not something that looks like it can be fixed on the PDF.js side. Otherwise, please provide the PDF file for analysis.
