### ISSUE TITLE
Character disorder near Japanese bracket start

### ISSUE THREAD

**Issue by futot1** [mozilla/pdf.js#9775]
Attach (recommended) or Link to PDF file here:
[AN_1404252._p51-67.pdf](https://github.com/mozilla/pdf.js/files/2066552/AN_1404252._p51-67.pdf)

Configuration:
- Web browser and its version: IE11/Firefox/Chrome
- Operating system and its version: Windows 7/10
- PDF.js version: current (demo)
- Is a browser extension:

Steps to reproduce the problem:
1. Open the attached PDF
2. Please look at the area indicated in below screen shot

What is the expected behavior? (add screenshot)
![an_1404252_ok](https://user-images.githubusercontent.com/7111820/40893679-3385ef2c-67de-11e8-89bb-5015780c21d4.png)

What went wrong? (add screenshot)
![an_1404252_disorder](https://user-images.githubusercontent.com/7111820/40893687-45063b8a-67de-11e8-8dd8-f2a516249c5b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The file does not match the images, but the file does not have any issues anymore in the latest version as far as I can tell.

**Comment by Snuffleupagus** [comment]
This *may* be a duplicate of issue #7687, in which case re-opening this one wouldn't be necessary.
