### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by pchiriot** [mozilla/pdf.js#9776]
Attach (recommended) or Link to PDF file here: https://drive.google.com/file/d/1W9SybAqqKg2MDkgT1yp6hnmNGLrquj6r/view?usp=sharing

Configuration:
- Web browser and its version: Firefox 60.0.1
- Operating system and its version: Window 10
- PDF.js version:  
       PDFJS.version = '1.8.188';
       PDFJS.build = 'ad1023ff';

- Is a browser extension: No

Steps to reproduce the problem:
1.  Open the PDF with PDFJS
2. Click on a link (page 4 or 5)

What is the expected behavior? (add screenshot)
You should have move to the correct page. Open the PDF on adobe acrobat reader to see the expected behavior

What went wrong? (add screenshot)
Most of the link are not clickable. If they are, you are redirected to the page page 1

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Thanks in advance.

**Comment by timvandermeij** [comment]
I looked into this and found that the links are not link annotations, but actually button widget annotations. The console shows the following warnings:

```
Warning: Push buttons without action dictionaries are not supported
Warning: parseDestDictionary: Unsupported Action type "Hide".
```

**Comment by timvandermeij** [comment]
I debugged this a bit and found that the annotations don't have the `A` dictionary, which is why we stop parsing. However, they do have the `AA` (additional actions) dictionary, which we don't support but does contain the actions.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
