### ISSUE TITLE
set option disableFontFace

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [mozilla/pdf.js#9778]
How do set the option disableFontFace to false ? It is not an option in PDFJS anymore you can see at #6742, and then im falling into #4244.

It says - "We will remove any PDFJS.xxxx properties in the future. This one is probably belong to render() parameters." So, how do it works? I wasnt able to go through with this.

Configuration:
- Chrome 66.0.3359.181 64 bits
- MacOS High Sierra 10.13.4
- 2.0.489 from CDN URL;
- No

**Comment by timvandermeij** [comment]
You can pass `disableFontFace` as a parameter to the `getDocument` API call. Refer to https://github.com/mozilla/pdf.js/commit/0ecc22cb04b54e57bbe0e498791f9a604c8c2e57#diff-304ad4918827181a1d1f52f5803717cdL64 for an example.

**Comment by diego-lipinski-de-castro** [comment]
I'm doing it like 
```javascript
pdfjsLib.getDocument(url, { disableFontFace: true }).then(doc) => {}
```

but seems like nothing changed, it does not fallback, or what should I expect?

**Comment by diego-lipinski-de-castro** [comment]
I'm fucking dumb, thanks for the help, you're right, i didnt pay attention to that

**Comment by timvandermeij** [comment]
No worries, and good luck!
