### ISSUE TITLE
I want to load only 10 pages...

### ISSUE THREAD

**Issue by youlook** [mozilla/pdf.js#9785]
Attach (recommended) or Link to PDF file here:

Configuration:

Web browser and its version: IE 11
Operating system and its version: windows 7
PDF.js version: 1.9.426
Is a browser extension:
Steps to reproduce the problem:
One.

When the pdf file has more than 700 pages, I want to render the initial 2 pages first.

What is the expected behavior? 

sample file : http://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf

What went wrong?

Currently, only the first page is rendered first. If you go to page 2, you have to wait until all the pages are rendered. We currently have 10 minutes to wait.

**i want...

I want to load only 10 pages. Full page loading is not required. Is there a way?**

**Comment by timvandermeij** [comment]
You need to enable range requests on the server to only render pages in view instead of all pages (see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range).
