### ISSUE TITLE
Does pdfjs supports for windows10 applications, pdf is not loaded windows app

### ISSUE THREAD

**Issue by Jayesh26** [mozilla/pdf.js#9786]
we are using pdfjs for loading pdf on canvas, as we are working on cordova we have created android application where pdfjs loads the pdf on canvas properly.
To test same functionality on Windows 10 we created windows build but windows unable to load the pdf 
Does pdfjs supports windows ?

**Comment by timvandermeij** [comment]
It should work just fine if it's a browser (backend) that supports the required features. Check https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsers-are-supported for the browser compatibility.

**Comment by Jayesh26** [comment]
@timvandermeij, I am talking about windows mobile application. I have created windows mobile application using cordova and we have used pdfjs for loading the pdf on canvas but its not working on windows surface but same code is working on Android device.
