### ISSUE TITLE
built-in pdf viewer shows PDF incorrectly

### ISSUE THREAD

**Issue by YuliaPe** [mozilla/pdf.js#9787]
Attach (recommended) or Link to PDF file here:
https://www.rexultihcp.com/sites/g/files/qhldwo536/files/2018-04/Downloadable_Dosing_Guide_SZv4.pdf

Configuration:
- Web browser and its version: FireFox Quantum, v. 60.0.2
- Operating system and its version: Wind 10
- Is a browser extension: built-in pdf viewer

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/40029542/41100796-ebb49d9e-6a6a-11e8-9d07-70179424e48a.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/40029542/41100869-19ae9f4c-6a6b-11e8-9e44-9dbc74eeacb7.png)

**Comment by Jan02** [comment]
[1_split_Untangling the Web.pdf](https://github.com/mozilla/pdf.js/files/2201443/1_split_Untangling.the.Web.pdf)

![sumatrapdf_2018-07-17_07-46-47](https://user-images.githubusercontent.com/2181218/42815522-9ad8c072-8995-11e8-8558-9b3e48ad6cb8.png)

![firefox_2018-07-17_07-52-17](https://user-images.githubusercontent.com/2181218/42815775-60724b1e-8996-11e8-8720-d779ac0c4636.png)

**Comment by brendandahl** [comment]
Original PDF link is no longer available. Closing for now, will reopen if link is found again. 

@Jan02 you issue is different. Please file a separate bug.
