### ISSUE TITLE
Why is version 2.0.550 marked as 2.0.301?

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#9788]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by brendandahl** [comment]
Where is it marked as 2.0.301? In the pdf.js file I see pdfjsVersion = '2.0.550'

**Comment by timvandermeij** [comment]
Make sure to download the source from https://github.com/mozilla/pdf.js/releases/tag/2.0.550. If you still see 2.0.301 somewhere, please state *exactly* where you found it before we do not see it. Thanks.

**Comment by qwer1304** [comment]
I downloaded sources from 2.0.550 tag.

**I built Chrome extension as shown in instructions.**

In pdf.worker.js and pdf.js I can see the lines:
var pdfjsVersion = '2.0.301';
var pdfjsBuild = 'fd242ad';

The files are in:
pdf.js\build\chromium\content\build

The files date is my build date.
