### ISSUE TITLE
Pdf is not rendering in iframe and throwing error "Invalid or corrupted file"

### ISSUE THREAD

**Issue by ykonathalalatest** [mozilla/pdf.js#9789]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE/FF/Chrome
- Operating system and its version:windows 2008
- PDF.js version:1.9.426
- Is a browser extension:no

Steps to reproduce the problem:
1. added an iframe for viewer.html with a relative url that actually streams the pdf as shown below
<iframe id="pdfdoc" src="~/web/viewer.html?file=/webroot/ProfileDwnld.asp?filename=@HttpUtility.UrlEncode(docurl)"></iframe>
2. Instead of rendering pdf its throwing error "Invalid or corrupted file"

What is the expected behavior? (add screenshot)
Instead of rendering pdf its throwing error "Invalid or corrupted file"

What went wrong? (add screenshot)
Does the viewer.html supports a streaming url like shown above??

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): Apologies that I cannot post the online links as that's not in public facing.

**Comment by timvandermeij** [comment]
In the issue template it's stated that we cannot help without a running example that shows the issue. We cannot see what `ProfileDwnld.asp` returns, and it looks like it returns invalid PDF data. You can check if the data returned is in fact a valid PDF file.

**Comment by ykonathalalatest** [comment]
Here is the url for testing this 

https://staging.brassring.com/JetStream/500/Presentation/Template/ASP/Candidate/Todo/CandidateProfileDwnld.asp?eTransID=@q5xvC5VbPRwwys2B4x3YJg==&filename=%4051fTmrBt1EP%2bB1pIFyCCrUX6sVhD87g7ml1rMQptHIv13jY1X%2fPXOAJAhchY8kIsaO0OhjtGWzeVubvDLxpEDiBcnXKozGxBYKAZKTLozPzMQWKqgTOuA8RfzRxEl4a4TD15PtTgir1zsmHGg138GsUN4sD1UHkjyWNS6GH6%2fbiDrvH5vjiaXJwPblbCXg7qiSMV0Ls2T79ePjUXpUYUNFDQGygpf9AbOOv%2fBaD3nTb2sPomL1wO7A%3d%3d&EmailTemplate=true

Please let me know if you need more details.

Thanks,

**Comment by ykonathalalatest** [comment]
Yes what I say is this url is good and its working directly, but its only failing when embed with pdf.js using this ~/web/viewer.html?. So want a reason on why its throwing error when used by pdf.js

Can you please review the code once again as I posted initially and let me know if I need to alter something to make it work.

Note: I know it works fine with iframe but the main reason why I am using pdf.js is to make it consistent accross all the browsers like desktop and mobile as well..

Thanks,

**Comment by ykonathalalatest** [comment]
Can I get an update to the question that I posted above??

**Comment by timvandermeij** [comment]
Without a working example on e.g., JSFiddle it's impossible to tell. I think it's because the `file` query parameter perhaps expects a direct link to a file, not to a file stream.

**Comment by ykonathalalatest** [comment]
Does the viewer.html supports any other query parameter so that it allows me to do what I am trying here?? I always get a url that streams the pdf to the browser and I need to use that url in pdf.js

Please do suggest me if any alternatives can be done to achieve what I am looking for?

Just to re-iterate this is what I am trying but its always throwing error "Invalid pdf structure"

<iframe src="~/web/viewer.html?file=/jetstream/500/presentation/template/asp/Candidate/Todo/CandidateProfileDwnld.asp?filename=@HttpUtility.UrlEncode(docurl)"></iframe>

Thanks,

**Comment by KALAMEGAMV** [comment]
where i can add html file
