### ISSUE TITLE
Scrolling and Spreads options not available

### ISSUE THREAD

**Issue by utopianknight** [mozilla/pdf.js#9790]
Attach (recommended) or Link to PDF file here: [Link](https://mozilla.github.io/pdf.js/web/viewer.html)

Configuration:
- Web browser and its version: **Firefox Developer Edition 61.0b11 (64-bit)**
- Operating system and its version: **Windows 10  1803 Build 17134.81**
- PDF.js version: **Built-in**
- Is a browser extension: **No**

Steps to reproduce the problem:
1. Open any PDF file from PC ('Menu>Open File...' or Drag and drop PDF file into browser window)

What is the expected behavior? (add screenshot)
<img width="571" alt="goodviewer" src="https://user-images.githubusercontent.com/25604837/41146203-a6ef1f50-6b13-11e8-8240-bb89811fd9dd.PNG">

What went wrong? (add screenshot)
<img width="554" alt="badviewer" src="https://user-images.githubusercontent.com/25604837/41146213-ad0eb7c4-6b13-11e8-9007-e50ccbeabb2b.PNG">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by timvandermeij** [comment]
The scrolling modes are merged quite recently, so they will most likely be in a later Firefox version, probably Firefox 62.

**Comment by timvandermeij** [comment]
Note that there is a version 2 pre-release now: https://github.com/mozilla/pdf.js/releases/tag/2.0.550
