### ISSUE TITLE
Enable the missing PDF unit test for the API in NodeJS

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#9791]
The objective is to remove https://github.com/mozilla/pdf.js/blob/master/test/unit/api_spec.js#L166-L170 by fixing up `src/display/node_stream.js` to throw `MissingPDFException` when a PDF file is not found. Right now, this file is not handling errors in a consistent or even correct way compared with `src/display/network.js` and `src/display/fetch_stream.js`. Using the `createResponseStatusError` utility function might not make much sense in a Node.js environment. However, at the very least it seems that `MissingPDFException` or `UnknownErrorException` when we cannot tell that a PDF file is missing should be thrown manually. As is, the API (i.e., `getDocument`) is not returning the expected errors when loading fails in Node.js environments (as evident from this pending API unit test).

**Comment by AbhimanyuVashisht** [comment]
I am working on it

**Comment by RonLek** [comment]
@timvandermeij Do you think using `https.get(sourceUrl, callback)` as used here: 
 https://nodejs.org/api/https.html#https_https_get_options_callback over here https://github.com/mozilla/pdf.js/blob/7e139776692789fee4b2cedb443715665c5adebe/src/display/node_stream.js#L31
and throwing a `MissingPDFException` if `res.statusCode===404 || res,statusCode === 0 && /^file:/.test(sourceUrl)` would help?

**Comment by timvandermeij** [comment]
I think the problem is that you're requesting the file twice then: once for this check and once to actually load the file. It's probably better to handle this in the spot where we're actually attempting to load the file. Perhaps it would help to enable the test locally, see where it breaks and backtrace from there.
