### ISSUE TITLE
Replace deprecated `new Buffer(string, 'base64')` constructor with `Buffer.from(string, 'base64')`

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#9797]
There's two remaining instances of `new Buffer` which need to be updated:
https://github.com/mozilla/pdf.js/blob/0e0fa489dd7aaa59fcae159501f5485aafac6a5c/test/test.js#L323
https://github.com/mozilla/pdf.js/blob/0e0fa489dd7aaa59fcae159501f5485aafac6a5c/test/font/ttxdriver.js#L65

For additional details, please refer to this previous issue: https://github.com/mozilla/pdf.js/issues/9739#issue-324622017.

**Comment by yungRoz** [comment]
Put up a PR with updates for these areas here #9801
