### ISSUE TITLE
Can I get a link in the wiki?

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#9799]
I just released this and would like a link in the wiki:

https://github.com/burtonator/polar-bookshelf

https://www.inputneuron.io/polar-bookshelf-a-cross-platform-ebook-system-for-incremental-reading-and-spaced-repetition/

**Comment by timvandermeij** [comment]
I just added the link to your project to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications. I think it's a nice idea and it's really good to see another useful custom deployment of PDF.js. Thank you!
