### ISSUE TITLE
not allowed to request resource

### ISSUE THREAD

**Issue by MichaelDarKnight** [mozilla/pdf.js#9803]
Sometimes it work well with PDF.js, but sometimes I can't open pdf file. It just display "not allowed to request resource" in app browser. I don't know what's the matter with PDF.js. Wish someone could give me some suggestions, thanks !

**Comment by timvandermeij** [comment]
In that case the browser is blocking access to the resource, so it's not really PDF.js who is at fault here. Without any of the details from the issue template, I'm closing this as out of scope for PDF.js.
