### ISSUE TITLE
Add unique id for all div's in renderTextLayer

### ISSUE THREAD

**Issue by Avartil** [mozilla/pdf.js#9804]
Hello, I'm looking for a way to add a unique ID for every div in text layer.
I'm using current PDF.js and viewer.html / viewer.js

I want to have something like that:

    <div style="left=...., top=...," id="div1"> text </div>
    <div style="left=...., top=...," id="div2"> text </div>

Right now I was able to add this:

    for (var i = 0; i < task._textDivs.length; i++) {
        textDiv.setAttribute('id', 'd'+i);
    }

inside of: function appendText(task, geom, styles) (inside pdf.js) 

It works, but only for 1 page pdfs. If pdf have more that 1 page, first div on first page gonna have the same ID as first div on secound page etc. 

I would like to know how to (if thats even possible) to assign unique ID for all divs on all pages.

**Comment by timvandermeij** [comment]
The text layer is rendered per page, so keeping a local counter will not work. If you make it a global counter, then it should work as expected, i.e., don't use just `i`, but increment a global counter instead.
