### ISSUE TITLE
Slow rendering pdf

### ISSUE THREAD

**Issue by kavisherlock** [mozilla/pdf.js#9810]
Attach (recommended) or Link to PDF file here: 
[pdfExample10.pdf](https://github.com/mozilla/pdf.js/files/2098818/pdfExample10.pdf)

Configuration:
- Web browser and its version: Safari, Chrome (latest)
- Operating system and its version: iOS 11.3 (on iPad)
- PDF.js version: latest (or whatever's on https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Save the above pdf on an iOS device (in our case: iPad)
2. Load the pdf in a browser on the iPad using the pdf.js demo (https://mozilla.github.io/pdf.js/web/viewer.html)

What is the expected behavior? (add screenshot)
Pdf loads in a reasonable amount of time
![fullsizeoutput_5ca](https://user-images.githubusercontent.com/23285466/41361767-731d1eee-6ef5-11e8-8ef4-c91eafe5ac24.jpeg)

What went wrong? (add screenshot)
Pdf loads very slowly, one line at a time, taking up to 45 seconds at times.
![fullsizeoutput_5cb](https://user-images.githubusercontent.com/23285466/41361781-7abaf3ba-6ef5-11e8-8a31-859cd65a016c.jpeg)

Some background
I've tried going through the pdf.js code to see what might be causing the slow rendering, and the only thing I can guess is the font that this particular pdf uses. File size and the amount of text doesn't seem to affect the rendering speeds (I have other, larger pdfs that load fine). This pdf was made using MS Word and the font type is TrueType, if that helps.
I'm primarily hoping for a reason why this pdf might be loading slowly and possibly a fix that I can do on my side (I've tried changing preferences listed in your preferences_schema and that doesn't seem to help. If there are code changes that might be needed on your side, if you can guide me in the direction of what code might need the change, I would really appreciate that

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by akshay-bhagat** [comment]
Do you have any images in your source PDF file??

I am also facing the same slow loading of PDF file in web page..

Please share if you got something on it..

**Comment by kavisherlock** [comment]
No. I don't. It's text only. However, while unrelated to this, I do recall seeing some slowness in rendering if the image is of high quality (scanned at a high dpi for instance). Not sure if that's your case

**Comment by PSpSynedra** [comment]
We have similar issues with rendering a PDF on iOS (11.4.1).
Blocks/Lines are drawn onto the target canvas very slowly ...

**Comment by Snuffleupagus** [comment]
This issue is quite old, but given that it appears to only affect a *particular* platform (iOS) it seems *very* unlikely to be actionable/valid in the PDF.js project. More likely, there are/were problems either with font loading and/or canvas rendering in iOS, which we however cannot really do anything about.

Given that this renders more-or-less instantly in e.g. Firefox, I'd suggest closing this issue since it doesn't seem actionable *here*.

**Comment by mmroden** [comment]
I'm now seeing this error when trying to render the attached PDF on Firefox through hugo (via https://github.com/anvithks/hugo-embed-pdf-shortcode) on a mac.  I realize the tech stack may be a bit esoteric, but I've never seen such a slow render.  From what I can read of his code, he's just straight loading the mozilla pdf.js code to display the pdf.
[D-TET-001103-0 Fan Box Drawing.pdf](https://github.com/mozilla/pdf.js/files/6200992/D-TET-001103-0.Fan.Box.Drawing.pdf)
