### ISSUE TITLE
DEFAULT_URL

### ISSUE THREAD

**Issue by prohtex** [mozilla/pdf.js#9812]
I need to be able to define DEFAULT_URL via a php script. My script is based on viewer.html, but it gets a filename from a database with an ID, and defines that in the header:

`echo "var DEFAULT_URL = '".$file."'";`

This doesn't seem to be working for me in 2.0 - how would I go about defining DEFAULT_URL now? Exposing the location of the pdf file in the URL is simply not an option for me, nor is defining it in the viewer.js file.

**Comment by timvandermeij** [comment]
The `DEFAULT_URL` global is removed in version 2.0. Instead, you should give the default URL via the `defaultUrl` app option. Refer to:

https://github.com/mozilla/pdf.js/blob/3bfc797bc718a367f4b79d7bccb789f9f45bb406/web/app_options.js#L36-L40

You can probably do something like this to set it:

https://github.com/mozilla/pdf.js/blob/7ba50448fdef660d22b799b5814af36ad63407c4/web/viewer.js#L200

**Comment by prohtex** [comment]
If I try to set this in the header of viewer.html:

`pdfjsWebAppOptions.AppOptions.set('defaultUrl', '<?=$file;?>');`

I get this error:

`ReferenceError: Can't find variable: pdfjsWebAppOptions`

**Comment by prohtex** [comment]
> You can modify the defaultUrl app option in the web/app_options.js file 

What app_options.js file? This is not in the web dir. If I add it, and set a custom file, it has no effect. If I explicitly include it in viewer.js, it has no effect.

**Comment by prohtex** [comment]
@Snuffleupagus I tried placing this code in the header of viewer.html:

`PDFViewerApplication.open('<?=$file;?>');`

It has no effect and throws no errors.
