### ISSUE TITLE
Rendering all pages(not intended) in Angular 5 but not (intended) on pure HTML/JS

### ISSUE THREAD

**Issue by sinsau** [mozilla/pdf.js#9817]
Pdf: https://media.readthedocs.org/pdf/flask-cors/latest/flask-cors.pdf

Configuration:
- Web browser and its version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 16.04 LTS
- PDF.js version: 2.0.550

Steps to reproduce the problem:
1. clone the repo https://github.com/sinsau/pdfjsAngCli
2. run "ng serve" and also open "pdfViewer.html" in browser

What is the expected behavior?
All pages should should not be rendered i.e. "data-loaded=true" should not appear for all pages.

What went wrong? 
All pages are rendered i.e. "data-loaded=true" appear for all pages.

I tried the same code for a pure HTML file and it worked as intended, but when using in angular 5 project all pages are rendered at once which is not required in my case. I have attached the link of dummy repo
with "pdfViewer.html" as pure html file which works fine and "localhost:4200" after "ng serve" gives the different behaviour.

The repo is based on simpleViewer of [pdfjs component exapmle](https://github.com/mozilla/pdf.js/tree/master/examples/components)
I tried different way of doing it from many examples but the behaviour remained same.
I also tried setting "disableAutoFetch": false but didn't work

**Comment by Snuffleupagus** [comment]
Using e.g. the `simpleviewer` example *as-is* works for me, see https://github.com/mozilla/pdf.js/tree/master/examples/components. Most likely, either the `pdf_viewer.css` file isn't being used or there's other CSS rules which end up overriding the necessary ones. Closing, since this shouldn't be a PDF.js issue as such?
