### ISSUE TITLE
Scaling of thumbnails does not work with larger files

### ISSUE THREAD

**Issue by iansaun** [mozilla/pdf.js#9820]
Attach (recommended) or Link to PDF file here:  [pdf.js.test.7.pdf](https://github.com/mozilla/pdf.js/files/2107559/pdf.js.test.7.pdf)

Configuration:
- Web browser and its version: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Version 1803 (OS Build 17134.112)
- PDF.js version: The 'demo' version at https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: No

This does not seem to be platform / browser specific - I reproduced it on:
- Android Google Chrome
- Windows Internet Explorer

Steps to reproduce the problem:
1. Use a device with a device pixel ratio > 1
2. Upload the attached file somewhere publicly accessible with appropriate CORS headers
3. View the attached document via demo URL https://mozilla.github.io/pdf.js/web/viewer.html?file=blah
4. Open the sidebar to view the thumbnails - some will be the correct size, other will not have been scaled properly

My desktop has a device pixel ratio of 1.25. 

The resultant output looks like this: ![thumbnail_scaling_error](https://user-images.githubusercontent.com/22152472/41490819-b35a19ea-70ed-11e8-83d3-ea6d7bfc4e27.png)

The pages are all black. I have added an arrow to show the white area that indicates that the thumbnail image has not been scaled to fit the space.

My Android phone has a device pixel ratio of 2. The result looks even worse!

This isn't a CSS or styling issue - the generated dataURL appears to be wrong, as though the scaling has been ignored. Here's one of the dodgy thumbnails:
![thumbnail_with_scaling_error](https://user-images.githubusercontent.com/22152472/41491275-ff37903e-70ef-11e8-8311-e0020c31bb09.png)

**Comment by iansaun** [comment]
Note, this doesn't happen consistently - a file with fewer pages seems to work fine.

**Comment by marcosignacio** [comment]
+1

**Comment by subgenere** [comment]
+ 1

**Comment by cmh1996** [comment]
> Note, this doesn't happen consistently - a file with fewer pages seems to work fine.

Do you have any solution to solve this problem?Thanks!

**Comment by cmh1996** [comment]
I also encountered this problem.

**Comment by YipingRuan** [comment]
Turns out this will happen if the thumbnail is generated by calling draw() in pdf_thumbnail_view.js (If you quickly scroll to page behind during loading, then the page 1 thumbnail will go wrong)

![image](https://user-images.githubusercontent.com/5492274/99042987-a103cd80-25c8-11eb-8ebc-cb068bdb8528.png)
