### ISSUE TITLE
Is it possible to get server response in pdf file?

### ISSUE THREAD

**Issue by KrYpToDeN** [mozilla/pdf.js#9823]
Hello.
I would like to get response from serverside to my PDF file, after send request form to server (such as AJAX in JS),
I can use GET/POST requests. It doesn't matter.

Is it possible to do? Or, Could you tell me, please, what way can i use to released it?

Thank you

**Comment by timvandermeij** [comment]
This is out of scope for the PDF.js project, but if you render the PDF server-side, you can stream it to the client and use the `getDocument` API to open it, which accepts raw data too.
