### ISSUE TITLE
'Setting up fake worker.' is showing only on ios safari

### ISSUE THREAD

**Issue by csKangGdcomm** [mozilla/pdf.js#9826]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: ios safari
- Operating system and its version: ios
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Open cordova app on device.   
2. pdfjsLib.getDocument( ... )  works fine for the first rendering.
3. lock the device
4. unlock the device
5. pdfjsLib.getDocument( ... )  show 'Setting up fake worker' message and pdf is now rendering.

**Question**.
I want to know what situation the 'fake worker' should show.
I just found the comment that '// Either workers are disabled, not supported or have thrown an exception.' I cann't get it...
It only happens on ios device, not ios simulator not android device, not android simulator...

Actually I solve the problem. First time, I create worker and save it into the javascript (memory). and than use the saved worker every next time...

**Comment by Snuffleupagus** [comment]
This really sounds like a platform/browser issue rather than a PDF.js one; should this issue simply be closed?
