### ISSUE TITLE
Define default PDF file in viewer.html

### ISSUE THREAD

**Issue by prohtex** [mozilla/pdf.js#9828]
My application requires defining the default pdf file in viewer.html (not in viewer.js). I need to be able to hit a database and return the URL of the pdf file without exposing it (in an obvious way) to the user. I cannot use "?file=" in the URL of my application, for a number of reasons.

Previously, I defined DEFAULT_URL in the header of viewer.html. According to documentation for 2.0, this is deprecated:

https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file

The documentation states "The viewer can be started without any PDF loaded by setting the defaultUrl app option to an empty string." Logic follows that by setting defaultUrl to a different pdf file, that file would be loaded by default.

HOW do I set the defaultUrl app option in viewer.html?

I have tried:

`set defaultUrl = '<?=$file;?>';`
`pdfjsWebAppOptions.AppOptions.set('defaultUrl', '<?=$file;?>');`
`PDFViewerApplication.open('<?=$file;?>');`

These do not work. Thank you in advance for any assistance.

**Comment by prohtex** [comment]
Please, anyone? The solution must be a simple one but it is beyond me.

**Comment by timvandermeij** [comment]
I'm not sure how to do it through PHP, but setting https://github.com/mozilla/pdf.js/blob/master/web/app_options.js#L38 or using `AppOptions.set('defaultUrl', 'file.pdf');` should just work. How to set it with PHP is out of scope for the project, but I'll leave it open so others can chime in if they have any ideas.

**Comment by prohtex** [comment]
The issue has nothing to do with PHP—I tried setting defaultUrl as you suggest in the header of viewer.html and it has no effect!

**Comment by timvandermeij** [comment]
Closing since this is tracked in #9846, which is more specific. Please keep the discussion there and don't open multiple issues for the same question.
