### ISSUE TITLE
DataCloneError: Failed to execute 'postMessage' on 'Worker'

### ISSUE THREAD

**Issue by MateEke** [mozilla/pdf.js#9840]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Electron 2.0.3
- Operating system and its version: Windows 10
- PDF.js version: 2.0.489
- Is a browser extension: no

Steps to reproduce the problem:
Create Ellectron app with angular 6 + pdfjs

What is the expected behavior? (add screenshot)
PDF gets displayed

What went wrong? (add screenshot)
```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
```

In Google Chrome everything works fine.

VadimDez/ng2-pdf-viewer#326

**Comment by Snuffleupagus** [comment]
> app with angular 6

This looks like a duplicate of issue #9166, which was bug caused by a bug in Angular (rather than PDF.js); please refer to https://github.com/angular/zone.js/pull/980.

**Comment by MateEke** [comment]
This issue is related to non-existent PDF - I have an existing PDF, and the error only occurs in electron app. In Google Chrome everything works fine in my case.

**Comment by timvandermeij** [comment]
I don't think we can do anything on the PDF.js side without more information, most notably a running demo that shows the issue. Moreover, make sure `zone.js` is updated per the issue above.

**Comment by timvandermeij** [comment]
Closing since no information shows that this is caused by PDF.js itself. All signs point to the Angular issue mentioned above, and there have been more reports of it there.

**Comment by giridharkannan** [comment]
The issue is not what the error message says, it's actually something else. Since error handling faced another exception while reporting, things got messed up.

The reason for the issue is, Http module misses "require" method to be precise both Http and Https modules are empty.

When using pdf.js in Chrome browser, it uses PDFFetchStream to read data whereas when using pdf.js in Electron it uses PDFNodeStream. When in Electron, to resolve Http request PDFNodeStream uses Node's Http module ( require('http') ), somehow the http variable got overwritten.

Moving Http import inside PDFNodeStreamFullReader and PDFNodeStreamRangeReader solves the issue that we face.

I don't know why http variable got overwritten or who is responsible for this issue as am very new to frontend development but it would be helpful if someone helps us out to resolve this problem.

**Comment by Farbod29** [comment]
@giridharkannan I have same issue but I don't know how to move Http report to both PDFNodeStreamFullReader and PDFNodeStreamRangeReader.

**Comment by giridharkannan** [comment]
@Farbod29 
It's been long and I forgot the context, but I can share my working code snippet. Hope this will be helpful

```typescript
       if(isElectronBuild()) {
            pdfjsDisplayAPI.setPDFNetworkStreamFactory((params) => {
                return new PDFFetchStream(params);
            });
            task = getDocument(pdfUrl);
        } else {
            task = getDocument(pdfUrl);
        }
`

**Comment by Farbod29** [comment]
![Screenshot 2019-04-06 21 26 46](https://user-images.githubusercontent.com/17232450/55674309-634ea700-58b3-11e9-81da-37c31c3578b2.png)

**Comment by Farbod29** [comment]
@giridharkannan  thanks for prompt response,I just added task = getDocument(pdfUrl); here but I don't really know how PDF.js working didn't fix yet.

![Screenshot 2019-04-06 21 31 31](https://user-images.githubusercontent.com/17232450/55674319-782b3a80-58b3-11e9-86e8-4d5d4a953126.png)

**Comment by Farbod29** [comment]
![Screenshot 2019-04-06 21 37 31](https://user-images.githubusercontent.com/17232450/55674384-61d1ae80-58b4-11e9-93f8-d590ab320915.png)
![Screenshot 2019-04-06 21 37 55](https://user-images.githubusercontent.com/17232450/55674385-61d1ae80-58b4-11e9-803e-7e5f603b9943.png)
![Screenshot 2019-04-06 21 31 31](https://user-images.githubusercontent.com/17232450/55674386-61d1ae80-58b4-11e9-8dac-8e2abdb6f642.png)
![Screenshot 2019-04-06 18 45 59](https://user-images.githubusercontent.com/17232450/55674387-626a4500-58b4-11e9-9428-6776185e4c1d.png)
![Screenshot 2019-04-06 21 25 04](https://user-images.githubusercontent.com/17232450/55674388-626a4500-58b4-11e9-9fda-a8ae18cbbbdb.png)
![Screenshot 2019-04-06 18 42 36](https://user-images.githubusercontent.com/17232450/55674389-626a4500-58b4-11e9-823c-22b5119989de.png)

**Comment by giridharkannan** [comment]
@Farbod29 If it's not a overkill, please do share your code snippet to my mail id. And the code snippet that I gave is not be added on pdf.js's code base, rather on your code.

**Comment by xuyanzhuqing** [comment]
const loadPDF = async () => {
  pdfDoc.value = await PDFJS.getDocument({
    // 在加载 PDF 时，对 ArrayBuffer 做切片拷贝，确保每次传递给 Worker 的是独立实例，避免原缓冲区被分离后复用。
    data: props.fileState.data.slice(0)
  }).promise
  // 更新页码信息
  fileHubManager.updateFile(props.fileState.filepath, 'readingProgress', {
    total: pdfDoc.value?.numPages || 0,
    current: props.fileState.readingProgress.current
  })
}

数据切片复制就能解决这个bug
