### ISSUE TITLE
Some portion of the page is not being rendered properly in Chrome new update (version 67)

### ISSUE THREAD

**Issue by rhood2548** [mozilla/pdf.js#9842]
Configuration:
- Web browser and its version: Chrome v67
- Operating system and its version: macOs High Sierra v10.13.2, Windows v10, Windows v8.1 
- PDF.js version: 1.10.100, 2.0.550
- Is a browser extension: No

Steps to reproduce the problem:
1. Scroll down any PDF with more than 10 pages having images in it

<img width="1021" alt="screen shot 2018-06-26 at 6 11 40 pm" src="https://user-images.githubusercontent.com/17524966/41915175-836fd4b6-796e-11e8-84a1-00a3de91ac1c.png">
<img width="1016" alt="screen shot 2018-06-26 at 6 08 43 pm" src="https://user-images.githubusercontent.com/17524966/41915176-83a4c8e2-796e-11e8-968a-067afd65d67e.png">

**Comment by timvandermeij** [comment]
You should provide a PDF file that shows the issue so we can try to reproduce it. Moreover, this really looks like a driver issue, so please upgrade your graphics drivers.

**Comment by rhood2548** [comment]
It's not a driver issue, it was working fine a week ago (before updating chrome). It still works fine in other browsers (Safari & Firefox), the only issue is in Chrome v67.

https://arxiv.org/pdf/1805.04405.pdf

**Comment by Snuffleupagus** [comment]
> [...] it was working fine a week ago (before updating chrome). It still works fine in other browsers (Safari & Firefox), the only issue is in Chrome v67.

Given that this sounds like a browser specific bug, probably connected with general `canvas` rendering, and not related to the PDF.js library as such; should this issue be closed since it's highly unlikely to actually be a bug anywhere in this repository?
