### ISSUE TITLE
Progressive loading/rendering of PDFs

### ISSUE THREAD

**Issue by vikas-jagga** [mozilla/pdf.js#9851]
Link to PDF file :
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf

Configuration:
- Web browser and its version: Firefox or Chrome latest
- Operating system and its version: Windows 10
- PDF.js version: 1.10.100
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open the PDF using viewer.html i.e. http://mozilla.github.io/pdf.js/web/viewer.html?file=https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf

 Expected behavior -:

As, PDF file is linearized / "web-optimized" and  server supports range requests which can be verified by directly opening the pdf "https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf" in firefox browser.

When we directly open the pdf  "https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf" progressive rendering is happening. First page gets displayed before the complete pdf is downloaded.

But when we open the PDF using viewer.html provided in PDFjs on GitHub eg. "http://mozilla.github.io/pdf.js/web/viewer.html?file=https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf"

whole pdf will get downloaded and displayed at once.

What went wrong -:

Progressive rendering should have happened on using custom viewer.html

**Comment by Vibhor20-Singhal** [comment]
I have same issue. I have never been able to load the pdf progressively using the web version of viewer.js

**Comment by Vibhor20-Singhal** [comment]
It looks to me that the XHR request that fetches pdf file in from the 'file=' parameter doses not handle the stream correctly. It fetches the full file at once and then opens it using PdfJS. 
Correct me if this is not the case.

**Comment by yurydelendik** [comment]
This issue is invalid. Demo viewer cannot access https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf. Please provide correct links to the customized viewer.  Will be re-opened then.

**Comment by yurydelendik** [comment]
> It fetches the full file at once and then opens it using PdfJS.
> Correct me if this is not the case.

Not the case.

**Comment by yurydelendik** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range

**Comment by vikas-jagga** [comment]
@yurydelendik use [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en)  Chrome extension to toggle CORS

**Comment by jayKeerthi** [comment]
my requirement is slightly different, i need to call an external web service to get the pdf document, i'm reading in chunks using an inputstream and writing it to the http response's output stream. The document get's rendered on the browser but there is a lag of around 5 secs for a 15 mb document as it waits for the entire document to be recieved before painting it. Any suggestion on how it can be rendered progressively.

**Comment by sanioka** [comment]
I have the same problem. Linearization demo doesn't work. It does download all document with 200 code.

I'm using chrome with --allow-running-insecure-content --disable-web-security arguments.

**Comment by yetyman** [comment]
we are opening local files in a locally running server and web page, large files do not load content on request but rather are loading from start to the point requested. I believe this is the same issue

**Comment by legistek** [comment]
> we are opening local files in a locally running server and web page, large files do not load content on request but rather are loading from start to the point requested. I believe this is the same issue. I am running vanilla PDF.JS in either plain IE or Chromium/Electron

Having the same issue. Is this expected behavior?

**Comment by yetyman** [comment]
> > we are opening local files in a locally running server and web page, large files do not load content on request but rather are loading from start to the point requested. I believe this is the same issue. I am running vanilla PDF.JS in either plain IE or Chromium/Electron
> 
> Having the same issue. Is this expected behavior?

Short answer is yes as far as my research led us(i am not a pdf.js dev).  you can get a speed boost by compressing/web optimizing a large pdf, but in my own experience, pdf.js will not perform like the chrome or electron built in pdf reader, speed wise. We have switched to the electron built in and taken ie 11 out of the equation

**Comment by legistek** [comment]
@yetyman I believe you're correct. I stepped through the code when loading a later page in a PDF and it linearly looped through each PDF resource between the current page and the one I wanted. Not sure why it NEEDED to do that but alas.

If anyone is serving PDFs from their own server application, the best solution might be to break up the PDFs into their individual pages, 1 page per "document", and serve each one as requested.
