### ISSUE TITLE
Issues with PDFFetchStream and range requests (Chrome)

### ISSUE THREAD

**Issue by robotlovesyou** [mozilla/pdf.js#9862]
Configuration:
- Web browser and its version:
Chrome 67.0.3396.99

- Operating system and its version:
Mac OS 10.12

- PDF.js version:
2.0.550

- Is a browser extension:
No

I've been trying to track down why range requests seem to work for us in FF but not in Chrome.

Chrome seems to have problems with range requests when using PDFFetchStream. When it is enabled the range requests appear to block waiting for the initial (non-range) request to complete

<img width="1105" alt="behavior-with-fetch" src="https://user-images.githubusercontent.com/883991/42135913-8554c768-7d52-11e8-95b1-e271210a7614.png">

If I modify the built pdfjs code to disable PDFFetchStream (by commenting out where it is returned from the pdfNetworkStreamFactory) forcing pdfjs to use the PDFNetworkStream then the behaviour is as expected

<img width="729" alt="behavior-without-fetch" src="https://user-images.githubusercontent.com/883991/42135938-f55725b0-7d52-11e8-94e2-29e6eaf68305.png">

It's likely that this is a Chrome problem rather than a pdfjs problem but I thought someone here may have some insight into the issue. 

I've not yet set up a demo viewer which displays the problem but I can do if necessary.

**Comment by JulianoGTZ** [comment]
hi, does this still happen?

**Comment by Snuffleupagus** [comment]
This issue is over a year old, and given that there's no runnable test-case provided here it's quite difficult to event attempt to reproduce this problem. @timvandermeij Closing as incomplete for now?
