### ISSUE TITLE
Pdf to svg garbled

### ISSUE THREAD

**Issue by xxh950501** [mozilla/pdf.js#9864]
Attach (recommended) or Link to PDF file here:
[wi6tugwkh4o-1530346012584.pdf](https://github.com/mozilla/pdf.js/files/2153499/wi6tugwkh4o-1530346012584.pdf)

Configuration:
- Web browser and its version: 
    Google Chrome  67.0.3396.99
- Operating system and its version:
 window 10
- PDF.js version:
   The latest version

Steps to reproduce the problem:
1.  Download the source code in github
2. Run the source code locally using webstrom, change the pdf path in examples/svgviewer/viewer.js in the source code, as shown in the figure
![image](https://user-images.githubusercontent.com/24908666/42142413-dcb98964-7de1-11e8-8c7e-54c89a49bf00.png)

What is the expected behavior? (add screenshot)
   Convert to svg to display properly in browser
What went wrong? (add screenshot)
  Garbled characters appear in the browser after conversion, but it is not garbled to open pdf locally.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Works for me, using the latest version of the example as found at https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer.
