### ISSUE TITLE
The PDF generated with Previous/Next example is a little fuzzy, compared to the PDF of viewer.HTML

### ISSUE THREAD

**Issue by sundeji** [mozilla/pdf.js#9871]
1. latest Chrome
2. pdf.js 1.9.426

Screenshot 1 is more ambiguous than screenshot 2. Screenshot 1 is 'Previous/Next example', while screenshot 2 is 'viewer.html '  What's the reason? Where does it need to be adjusted

<img width="474" alt="screenshot1" src="https://user-images.githubusercontent.com/20887046/42299959-9793a8a4-8040-11e8-8a35-d4105ee6ea3a.png">

<img width="523" alt="screenshot2" src="https://user-images.githubusercontent.com/20887046/42299972-a1e487e2-8040-11e8-8f9e-2c053576c1f7.png">

**Comment by timvandermeij** [comment]
Closing since this is answered above. Moreover, notice that the scale is also a bit lower in that example: https://github.com/mozilla/pdf.js/blob/master/examples/learning/prevnext.html#L43
