### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by weickdev** [mozilla/pdf.js#9872]
I follow the README under examples/mobile-viewer:
1. run ```gulp dist```
2. run ```gulp server```
3. open link http://localhost:8888/examples/mobile-viewer/viewer.html

But I get this error in console:
```
 pdfjsLib is not defined
```
So how can I let it work?

**Comment by ngopal1995** [comment]
It may be that you did not include the pdf.js file. Could help if you added any code to simulate this.

**Comment by timvandermeij** [comment]
I think you need to use `gulp dist-install` instead. Could you check if that works? If so, we need to adjust the instructions.

**Comment by weickdev** [comment]
```gulp dist-install```  works well, thank you. @timvandermeij

**Comment by timvandermeij** [comment]
Thank you for the feedback. I have opened a follow-up issue to correct the instructions.
