### ISSUE TITLE
[Question] How to add event listener on annotation clicked

### ISSUE THREAD

**Issue by MatthAddax** [mozilla/pdf.js#9882]
Hi,

I'm doing some research regaring PDF Viewers for the company I'm working for. One of the use cases I need to take in consideration is the ability to have a custom action when an user click on an annotation.

I've looked on the web, ine the source code and in the example but I could not manage to find a clue about it.

Is it possible with PDF.JS?

If yes, where should I look to understand it more?

Thank you,
Cordially,
Matthieu

**Comment by timvandermeij** [comment]
You can make a custom version of PDF.js where you implement a click handler for the annotations. They are created in the display layer for viewing, for example the link annotation is created here: https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L285

**Comment by MatthAddax** [comment]
Thank you,  I'll check this out :)
