### ISSUE TITLE
webpack 2 sever rendering `window is not defined`

### ISSUE THREAD

**Issue by IzaGz** [mozilla/pdf.js#9888]
i am using webpack 2.
constantly see error on server sider rendering
` UnhandledPromiseRejectionWarning: ReferenceError: window is not defined`
how can i import pdfjs-dist dynamicly, when window defined?

**Comment by Snuffleupagus** [comment]
> UnhandledPromiseRejectionWarning: ReferenceError: window is not defined

One instance of such errors were fixed in dcc7f33ee7ee0790ee34e2106a8d04254bc66c8c; but considering that *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is currently missing, that's just a guess at what the actual problem might be.

**Comment by timvandermeij** [comment]
The information from the issue template is indeed missing, making this issue not actionable. Note that we switched to Webpack 4 and fixed some of these issues in newer versions, so please consider upgrading.

**Comment by IzaGz** [comment]
@timvandermeij  i also switched to webpack 4.
I got this error when server rendering with node-
