### ISSUE TITLE
PDFJS show loading always  in IOS10 and Safari

### ISSUE THREAD

**Issue by LTFRANK** [mozilla/pdf.js#9889]
Attach (recommended) or Link to PDF file here: http://ovkylgru5.bkt.clouddn.com/242561514968393.pdf;
http://www.ltxfwh.org//public/lt/mobile/pdf/pdf.html?pdf=http://ovkylgru5.bkt.clouddn.com/242561514968393.pdf

Configuration:
- Web browser and its version: Safari 11.0.3 (13604.5.6)
- Operating system and its version: MACOS 10.12 (915)
- PDF.js version:1 .0.712/1.10.88
- Is a browser extension:

Steps to reproduce the problem:
1. it is works well before i used PDFJS  1.0.712 Version, but recently it has a different in Android and IOS, Chrome and Safari.Android, Chrome works well, but wrong in IOS and Safari. 
2.  IOS and Safari will show loading always  if i use the above PDF file or link.
3. if i download this file and save as ,and test with my local server used 1.0.712 version or 1.10.88, it can works well, so is there any solutions for that.thank you

What is the expected behavior? (add screenshot)
![20180712152124](https://user-images.githubusercontent.com/12975515/42618343-4ac1b7d0-85e7-11e8-8586-78d641ff4055.png)

What went wrong? (add screenshot)
![20180712151903](https://user-images.githubusercontent.com/12975515/42618351-53f9796e-85e7-11e8-8e42-245e830a5cfb.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html to see if the issue is there too?

**Comment by LTFRANK** [comment]
thanks for your tips.yes, i had tried to do that.i download the demo   to my local server, then put my file instead of the default.but it's still loading but not to show on Safari. However, if i  open this file and save with my Mac PDF version, it can  works well.  i resolved issue temporary .but it's has another ways to deal  that ?

**Comment by freefzl** [comment]
@LTFRANK @timvandermeij  Has that been fixed? I've seen the same thing on ios where if you only have one page it's going to show up but if you have more it's going to keep loading and it's not going to show up

**Comment by Snuffleupagus** [comment]
Given that this sounds more like an issue with a *particular* platform/browser, rather than a PDF.js library bug, is it really meaningful to keep this open? /cc @timvandermeij 

> PDF.js version: 1.0.712/1.10.88

Furthermore, these versions are *really* old and are consequently no longer supported.
