### ISSUE TITLE
textLayer div selection is not selected correctly and cannot be selected as desired

### ISSUE THREAD

**Issue by fclemonschool** [mozilla/pdf.js#9892]
Attach (recommended) or Link to PDF file here:
[180509_cubeTMF_JP.pdf](https://github.com/mozilla/pdf.js/files/2190844/180509_cubeTMF_JP.pdf)

Configuration:
- Web browser and its version: Chrome canary 69.0.3488.0
- Operating system and its version: Windows 10 Home 17134.165
- PDF.js version: 2.0.676 online demo
- Is a browser extension: no

Steps to reproduce the problem:
1. Use Pdf.js demo page.
2. Open pdf file and drag the mouse to select any word.
3. Not selected in the correct location and can not be selected as desired.

What is the expected behavior? (add screenshot)

Selected area in correct position.
![image](https://user-images.githubusercontent.com/18299676/42667363-0e32ce40-8686-11e8-978e-d9f8eae9f758.png)

What went wrong? (add screenshot)

Not selected in the correct location and can not be selected as desired.
![image](https://user-images.githubusercontent.com/18299676/42667392-44ab222e-8686-11e8-9744-dd8d3d42a41b.png)

**Comment by iswear1987** [comment]
do you have some css attributes changed the styles of `canvas` tag? or from inherit.
eg: `margin-top`、`padding-top`、`top`、white-space...

**Comment by fclemonschool** [comment]
> `canvas`태그 의 스타일을 변경 한 CSS 속성이 있습니까? 또는 상속에서. 
> 예를 들면 `margin-top`: `padding-top`, , `top`, 공백 ...

**Comment by fclemonschool** [comment]
I tested again with the latest online version(PDF.js: 2.2.191)
And the result is as follows.
![image](https://user-images.githubusercontent.com/18299676/58621881-4c519180-8305-11e9-8fae-239d869257b8.png)

**Comment by fclemonschool** [comment]
I tested again with the latest online version(PDF.js: 2.4.174)
And Window Version is Windows 10 Home 18363.476
And Chrome Canary Version 81.0.3989.0
And the result is as follows.

![image](https://user-images.githubusercontent.com/18299676/70400647-4506ff80-1a6f-11ea-816d-33557c1e8572.png)

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.
