### ISSUE TITLE
How to get text from an editable pdf?

### ISSUE THREAD

**Issue by xXAligatorXx** [mozilla/pdf.js#9894]
getTextContent does not give me the text in editable fields, even though they are filled. Is there any way to do this with this library?(or in conjunction with other libraries)

**Comment by brendandahl** [comment]
You probably want getAnnoations()
https://github.com/mozilla/pdf.js/blob/646d81cd09eb3c1880ec26c9305a855d02550bd2/src/display/api.js#L902

**Comment by timvandermeij** [comment]
Yes, for example widget annotations (which the editable fields are) have a `fieldValue` property: https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L585

**Comment by xXAligatorXx** [comment]
Does that also give me the location of the editable field just like getTextContent gives me location of text?

**Comment by timvandermeij** [comment]
Yes, the annotations have a rectangle property (https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L247-L260) which is where they are drawn on the page. This is also what our display layer uses to draw them: https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L211-L215
