### ISSUE TITLE
the demo web site on edge browser , is not presetting the printing dialog 

### ISSUE THREAD

**Issue by duduav** [mozilla/pdf.js#9899]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- edge version: Microsoft Edge 41.16299.547.0  Microsoft EdgeHTML 16.16299
- Operating system and its version: windows 10 enterprise 
- PDF.js version: the version that is on the demo website
- Is a browser extension: no

Steps to reproduce the problem:
1. open the demo site 
2.press print button 
3. i can see that preparing the document for print 
4.cannot see the printing dialog 

What is the expected behavior? cannot see the printing dialog as i can see in other browser

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/9057454/42796338-1eadacf8-89a7-11e8-95c6-d4dff78b8d3f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
