### ISSUE TITLE
How to enable AcroForm renderInteractiveForms

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#9907]
1) I noticed it is found in PDFViewerApplication.pdfViewer.renderInteractiveForms as a variable. How do i enable this? Without having my own code to render it with forms but just setting some value in the variable.

2) Also, checkbox do not get clicked. is there some variable needed to be set in order for these to receive click events?

**Comment by chitgoks** [comment]
hi tim

i saw the example code but it requires to call rerendering the page with
that optiom set to true

i overrode the code in pdf.js as a quick workaround without having to
rerender

you are right, i did read the thread about saving values not supported yet.

my issue is the checkbox when clicked, nothing happens. unlesd i remove the
buttonWidgetAnnotation class then the real checkbox element shows up but
its too big

ill attach the pdf so you guys can see it

**Comment by chitgoks** [comment]
here is the file

notice checkbox cant be clicked. but if i remove the buttonWidgetAnnotation class the checkbox element showz up but it is not styled[
[1532267353830_form_b101.pdf](https://github.com/mozilla/pdf.js/files/2217059/1532267353830_form_b101.pdf)

](url)

**Comment by smit-modi** [comment]
> You should pass the `renderInteractiveForms` parameter like in the AcroForms example: https://github.com/mozilla/pdf.js/blob/master/examples/acroforms/acroforms.js#L41. If you are not using the viewer components, you can set it to `true` at https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L16. Checkbox support is implemented, however we do not support saving any values, only rendering them.

Is there any support for saving the filled acroforms using download button? Also when I click on print and save as pdf, it doesn't retain the values.

**Comment by timvandermeij** [comment]
Closing since both rendering interactive forms and the checkboxes (also for the posted file) work in the default viewer.
