### ISSUE TITLE
How to watch gulp server?

### ISSUE THREAD

**Issue by PranjalAgni** [mozilla/pdf.js#9909]
Everytime after making changes I need to restart the gulp server is there any way to watch for changes?

**Comment by Snuffleupagus** [comment]
There really isn't nearly enough information provided here, but assuming that you followed *all* of the steps outlined in https://github.com/mozilla/pdf.js#getting-the-code then it should be sufficient to simply reload the local viewer[1] in the browser once changes have been made to a file.

Given that no additional information is provided (nor steps to reproduce), and that it works for other people, there's not really much that can be done here unfortunately.
Please remember to read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, and to provide as much of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md as possible, when opening an issue.

---
[1] I.e. the one opened with http://localhost:8888/web/viewer.html, as outlined in the instructions.
