### ISSUE TITLE
A White blank Screen displays on Device with Android API Level below 19

### ISSUE THREAD

**Issue by ghost1372** [mozilla/pdf.js#9911]
I'm using mozilla pdf.js in Android WebView to Show PDF files.
Code is working fine in Android API Level 19 and above But it's not working on Android API Level 18 and below.
A White blank Screen displays on Device.
Is there any way to resolve this issue?
```
filename = extra.getString("FILE_NAME");

            webview = (WebView) findViewById(R.id.webview);
            WebSettings settings = webview.getSettings();
            settings.setJavaScriptEnabled(true);
            settings.setAllowFileAccessFromFileURLs(true);
            settings.setAllowUniversalAccessFromFileURLs(true);
            settings.setBuiltInZoomControls(true);
            webview.setWebChromeClient(new WebChromeClient());
            webview.loadUrl("file:///android_asset/pdfjs/web/viewer.html?file=" + filename);
```

**Comment by Snuffleupagus** [comment]
Please refer to the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, which mentions that Android 4 (and below) is *explicitly unsupported*; furthermore [according to Wikipedia](https://en.wikipedia.org/wiki/Android_version_history#Android_4.3_Jelly_Bean_(API_18)), `API 18` thus corresponds to an explicitly unsupported version of Android.
