### ISSUE TITLE
Rotating a pdf causes a crash because of memory leak  on High(400%) Zoom scenarios

### ISSUE THREAD

**Issue by GeorgeVovos** [mozilla/pdf.js#9912]
You can reproduce it on the demo page
https://mozilla.github.io/pdf.js/web/viewer.html

Set the zoom level to 400% and then just keep pressing "R" on you keyboard

See also the attached video in the zip file
[PdfViewerRotate.zip](https://github.com/mozilla/pdf.js/files/2216925/PdfViewerRotate.zip)

Update 23/07/2018.
I tried this on Chrome and firefox and assumed that it's the same everywhere but I was wrong
Internet explorer 11 (haven't tried older ones) and Edge seem to be OK with this

**Comment by timvandermeij** [comment]
Doing this gives me the following error:

```
PDF.js v2.0.690 (build: 7e139776)
Bericht: 
Stack: beginDrawing@https://mozilla.github.io/pdf.js/build/pdf.js:10425:7
initializeGraphics@https://mozilla.github.io/pdf.js/build/pdf.js:8965:7
PDFPageProxy_render/<@https://mozilla.github.io/pdf.js/build/pdf.js:7893:9
```

**Comment by Snuffleupagus** [comment]
Testing this now, with PDF.js version `2.10.43`, I'm not seeing either crashes or even any console errors; closing as WORKSFORME.
