### ISSUE TITLE
create png from pdf

### ISSUE THREAD

**Issue by ipprokopiev** [mozilla/pdf.js#9916]
i have uploaded pdf files on my server now i want to create a preview page and for that i need to preate png files. pdfs are in dir uploads/files. how to make that?

**Comment by timvandermeij** [comment]
The example to convert PDF to PNG is found at https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png.

**Comment by ipprokopiev** [comment]
i found it but i cant understand how to use it

**Comment by timvandermeij** [comment]
The page is rendered onto a canvas, which you then dump to a PDF file. This is the gist of it: https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js#L75-L78.

**Comment by ipprokopiev** [comment]
But where is the file saved and how to just display the png

**Comment by timvandermeij** [comment]
In the same folder as `output.png`. It only converts the first page (https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js#L64), but you can extend it to convert all pages. Please refer to the code itself for how it works exactly.
