### ISSUE TITLE
Files missing from the pdf.js folder structure

### ISSUE THREAD

**Issue by craigmiller71** [mozilla/pdf.js#9918]
I have a Xamarin solution that has pdf.js as a sub-module. I'm trying to build it through VSTS and it failed so I pulled it down to my PC.

Steps to reproduce the problem:
1. Pull the code down in Visual Studio
2. npm install
3. gulp generic
4. Build the solution

Error MSB3030: Could not copy the file   "Assets\pdf.js\build\generic\web\compatibility.js" because it was   not found.
Error MSB3030: Could not copy the file   "Assets\pdf.js\build\generic\web\l10n.js" because it was not found.
Error MSB3030: Could not copy the file "Assets\pdf.js\build\pdf.js" because it was not found.
Error MSB3030: Could not copy the file   "Assets\pdf.js\build\pdf.worker.js" because it was not found.

The gulp file doesn't create these files, although they do get put in other places in the folder structure. If I manually copy them the solution builds in Visual Studio but the VSTS build still fails.

**Comment by timvandermeij** [comment]
It looks like you're using an old version of PDF.js because `web/compatibility.js` was removed quite a while ago and I'm not that `web/l10n.js` ever existed. I would suggest upgrading to the latest release and changing your build scripts accordingly.

**Comment by craigmiller71** [comment]
Sorry for the n00bness but how do I update the version? All I can see in the submodule reference is this:

[submodule "src/Investor.Droid/Assets/pdf.js"]
	path = src/Investor.Droid/Assets/pdf.js
	url = https://github.com/mozilla/pdf.js.git

As you can tell this is the first time I've worked with all this stuff,

**Comment by craigmiller71** [comment]
I followed the steps on this page:

https://stackoverflow.com/questions/8191299/update-a-submodule-to-the-latest-commit

but I still get the same errors.

**Comment by craigmiller71** [comment]
I deleted and re-added the submodule and it still gets the same errors.

**Comment by timvandermeij** [comment]
You need to build PDF.js after you have pulled it. Use e.g., `gulp generic` for that; refer to https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#build-pdfjs-from-source.

**Comment by craigmiller71** [comment]
It turns out that the problem was in the Visual Studio project, not pdf.js. The project file had AndroidAsset entries that expected files in the locations of the old version. Once I updated it to where they are in the new version it was all good.

Thanks for your help, Tim.
