### ISSUE TITLE
Printing on IE11 and MS Edge is incorrect - too big scale of image to print

### ISSUE THREAD

**Issue by KarolBialyKainos** [mozilla/pdf.js#9919]
Image of canvas send for printing is too big and doesn't fit printing viewport. That affects with extra page containing only footer, so for PDF with 2 pages as a result we have 4 pages.

Reducing width and height by 10% here: https://github.com/mozilla/pdf.js/blob/31012570ea90e47a947067f3a0dbe4e8f3232198/web/pdf_print_service.js#L35 resolves that issue (quick workaround for tests).

Attach (recommended) or Link to PDF file here:
Input PDFs:
[footer_example.pdf](https://github.com/mozilla/pdf.js/files/2222405/footer_example.pdf)
[simple_content.pdf](https://github.com/mozilla/pdf.js/files/2222406/simple_content.pdf)

Broken output PDFs (from printing):
[footer_example_output.pdf](https://github.com/mozilla/pdf.js/files/2222409/footer_example_output.pdf)
[simple_content_output.pdf](https://github.com/mozilla/pdf.js/files/2222410/simple_content_output.pdf)

Configuration:
- Web browser and its version:
Not working on:
IE 11.0.9600.19078 (Windows 8.1) 
![win8ie11_pageprintoptions](https://user-images.githubusercontent.com/13270407/43123608-fd5f4f38-8f24-11e8-8d63-c2972d517dec.png)

MS Edge 42.17134.1.0 (Windows 10)

Working on:
Chrome 67.0.3396.99 (MacOS 10.13.4)
Safari 11.1 (MacOS 10.13.4)
Firefox 61.0.1 (MacOS 10.13.4)

- PDF.js version:

Latest (2.0.694) on https://mozilla.github.io/pdf.js/web/viewer.html

- Is a browser extension:

Steps to reproduce the problem:
1. Open PDF files from this issue 
2. Click `Print` button

What is the expected behavior? (add screenshot)
<img width="433" alt="screen shot 2018-07-24 at 09 25 22" src="https://user-images.githubusercontent.com/13270407/43123167-9a3beac0-8f23-11e8-8abf-afe1af7e4b7c.png">

What went wrong? (add screenshot)
<img width="486" alt="screen shot 2018-07-24 at 09 25 12" src="https://user-images.githubusercontent.com/13270407/43123173-9db0ea48-8f23-11e8-9c2e-77f8d955f486.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
---

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
