### ISSUE TITLE
What is the appropriate scale value for the variable DEFAULT_SCALE for rendering pages fast?

### ISSUE THREAD

**Issue by kshantanu94** [mozilla/pdf.js#9921]
Attach (recommended) or Link to PDF file here:

https://d3cfn34s6l242i.cloudfront.net/news-paper/Andhra%20Jyothi58c278072ff375db6540cfd9/c4wp1532470006004-page_full.pdf
password  - 58c278072ff375db6540cfd9

Configuration:
- Web browser and its version: Mobile device browsers - Chrome mostly
- Operating system and its version: Android 
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the particular pdf on a site from a mobile browser where pdfjs lib has been used and observe rendering

What is the expected behavior? (add screenshot)
Pdf should load faster. 

What went wrong? (add screenshot)
Font loads slowly, sometimes line by line 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
It looks like the password is incorrect. Most likely the file is not optimized for web; refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize for optimization tips.
