### ISSUE TITLE
PDF pages get cut off 

### ISSUE THREAD

**Issue by VictoriaSarycheva** [mozilla/pdf.js#9922]
Attach (recommended) or Link to PDF file here:
https://drive.google.com/file/d/1LC_yAkFXtVza2aWisMNQbyetjv8Fzij-/view?usp=sharing

Configuration:
- Web browser and its version: **is actual for all browsers**
- Operating system and its version:
- PDF.js version: **latest**
- Is a browser extension:

Steps to reproduce the problem:
1. open pdf file by link
2. download file and open on your demo page
3. compare the images

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot) **The right side of the pictures is getting cut off, and the red part at the bottom goes up higher than it should.**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This looks like another issue where PR #6606 might be relevant.
