### ISSUE TITLE
Angular 6: can't resolve zlib

### ISSUE THREAD

**Issue by ErikNijland** [mozilla/pdf.js#9923]
Configuration:
- Web browser and its version: **Chrome 67**
- Operating system and its version: **OSX 10.13.5**
- PDF.js version: **pdfjs-dist@2.0.489**
- Is a browser extension: **No**

Steps to reproduce the problem:
1. Create a new Angular CLI (v6.1.0) project 
2. Include and use something from pdfjs (example https://github.com/ErikNijland/pdfjs-test/commit/18d8fd886d7b8cde80f06b8d46e662146b904883)

**Expected behavior**
No errors in the `ng serve` and `ng build` process.

![screen shot 2018-07-26 at 12 06 51](https://user-images.githubusercontent.com/7983484/43256235-6bd8b83e-90cc-11e8-9599-d433858ba809.png)

**Actual behaviour**
![screen shot 2018-07-26 at 10 27 37](https://user-images.githubusercontent.com/7983484/43256252-78c75474-90cc-11e8-8417-cefb3b4ab0bf.png)

Demo project: https://github.com/ErikNijland/pdfjs-test/commits/master

**Comment by yurydelendik** [comment]
Resolved by #9924

**Comment by vaidd4** [comment]
Hi,
I'm wondering why is the issue closed if it isn't resolved in any released version yet ?
Could we have any info on a possible new release ?
Thank you in advance
