### ISSUE TITLE
Dynamically changing language of pdf viewer

### ISSUE THREAD

**Issue by T0mazz** [mozilla/pdf.js#9926]
I wanted to configure chunk size on pdf.js so instead of opening pdfs with the link i'm opening them when the iframe of the viewer is initialized with the open function from viewer.js:
`open: function open(file, args) {...`
`$(element)[0].contentWindow.PDFViewerApplication.open(viewerUrl(), { rangeChunkSize: chunkSize() });`

This works fine, but the problem is that i don't know how to set the local language dynamically. I managed to do it with the function setLanguage (`$(element)[0].contentWindow.document.webL10n.setLanguage("sl-SI");`), but this changes only 1 part (see the picture)
![image](https://user-images.githubusercontent.com/14927095/43265072-10b1a670-90e8-11e8-90c7-130eff467662.png)

Is there a better way to do it ?

**Comment by T0mazz** [comment]
Still haven't found a solution to this. If anyone has any solution or a workaround to this problem, I would appreciate a lot.

**Comment by timvandermeij** [comment]
If you are using the generic viewer, you should use https://github.com/mozilla/pdf.js/blob/master/web/app_options.js#L221 to set the default locale. Otherwise, you can try using `setLanguage("sl");` instead since that is how the language is called in the `l10n` folder. I cannot really explain why only a part is translated in your image, but I guess it has to do with the asynchronous way of fetching the translations. If you set it too late, some parts will and some parts won't be translated.

**Comment by T0mazz** [comment]
Thank you for your answer. But how (or rather when) can I set the locale property, ? I guess before the iframe is loaded, since pdf.js is inside the iframe ?

The iframe looks like this:
`<iframe sandbox="allow-scripts allow-same-origin allow-modals" data-bind="attr:{src: 'lib/pdfjs/viewer.html?file=', id: id}, 
            IframeBinding: {styleSheetLink: stylesheetForIframe, viewerUrl: viewerUrl, chunkSize: chunkSize, viewerUrlChanged: viewerUrlChanged()}, style: {height: iframeHeight}" runat="server" style="width: 100%;" class="indoc_rightContent_inherit_height">
    </iframe>`

I tried changing it inside "IframeBinding" which appneds stylesheet to iframe head on load ifram event, but i guess it's too late.

**Comment by timvandermeij** [comment]
I'm not really sure how it would work in `iframe`s, so I would always suggest to set it before loading it in the `iframe` (i.e., fixed in the app options). Now that I come to think of it, there is also the `locale` hash parameter that you can probably use: https://github.com/mozilla/pdf.js/blob/master/web/app.js#L263

**Comment by T0mazz** [comment]
The locale in hash doesn't suit my case, since I want to manipulate chunk size thus i'm using .open function to pass pdf's url.
To solve my problem with localisation I modified source file (viewer), since there were no other solution.
Thank you for your help.

**Comment by docwarems** [comment]
> viewer.html?file=foo.pdf&locale=sl
This doesn't work as of today: neither http://mozilla.github.io/pdf.js/web/viewer.html#locale=fr nor http://mozilla.github.io/pdf.js/web/viewer.html?locale=fr

**Comment by segl84** [comment]
Any idea how to change this dynamically without having debug mode enabled and patching the original sources?

**Comment by ZeviLiao** [comment]
viewer.html link add locale query parameter , pdf/web/viewer.html?locale=${langCode}&file=
then in 
viewer.js  add two lines in class GenericL10n constructor
class GenericL10n {
  constructor(lang) {
    const urlParams = new URLSearchParams(window.location.search);
    lang = urlParams.get('locale');
    this._lang = lang;
    
it works for me.

**Comment by EugenMayer** [comment]
You should rather patch it this way, change the initialization in `_initializeL10n`

```javascript
  async _initializeL10n() {
    // HACK START
    const urlParams = new URLSearchParams(window.location.search);
    let urlParamLocale = urlParams.get('locale');
	// HACK END

    this.l10n = this.externalServices.createL10n({
       // HACK START
      locale: urlParamLocale || _app_options.AppOptions.get("locale")
	  // HACK END
    });
    const dir = await this.l10n.getDirection();
    document.getElementsByTagName("html")[0].dir = dir;
  },
```
