### ISSUE TITLE
Incorrect pattern positioning

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#9927]
Attach (recommended) or Link to PDF file here:
[pop-bugzilla41462.pdf](https://github.com/mozilla/pdf.js/files/2232812/pop-bugzilla41462.pdf)

poppler issue:
https://bugs.freedesktop.org/show_bug.cgi?id=41462

Configuration:
- Web browser and its version: FF 61.0.1 64bit
- Operating system and its version: W7
- PDF.js version: latest

Steps to reproduce the problem:
1. start pdf.js viewer url
2. open file

What is the expected behavior? (add screenshot)
![clipboard02-ar](https://user-images.githubusercontent.com/6665575/43275878-5b240bd8-9103-11e8-9bb5-dee122fddec7.png)

What went wrong? (add screenshot)
![clipboard01-pdfjs](https://user-images.githubusercontent.com/6665575/43275884-5feae074-9103-11e8-88b1-87101b2cff9c.png)

**Comment by Snuffleupagus** [comment]
This looks like another issue where PR #6606 might be relevant.
