### ISSUE TITLE
Transparent shape missing

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#9928]
Attach (recommended) or Link to PDF file here:
[pop-bugzilla48453.pdf](https://github.com/mozilla/pdf.js/files/2232840/pop-bugzilla48453.pdf)

From poppler issue:
https://bugs.freedesktop.org/show_bug.cgi?id=48453
"When the gstate has both an smask and a constant opacity < 1, the cairo backend ignores the constant opacity", this may or may not apply.

Configuration:
- Web browser and its version: Microsoft Edge 42.17134.1.0
- Operating system and its version: W10 home
- PDF.js version: latest

Steps to reproduce the problem:
1. start viewer in browser
2. open file

What is the expected behavior? (add screenshot)
![clipboard01-ar](https://user-images.githubusercontent.com/6665575/43276378-bf6170a8-9104-11e8-8cdf-7e2c700a3384.png)

What went wrong? (add screenshot)
![clipboard01-pdfjs](https://user-images.githubusercontent.com/6665575/43276382-c3d2b840-9104-11e8-9b29-2841776a4f46.png)

**Comment by Snuffleupagus** [comment]
This looks like another issue where PR #6606 might be relevant.
