### ISSUE TITLE
PDF.js does not render most .pdf files in Firefox Quantum 61.0.1

### ISSUE THREAD

**Issue by toddsh88** [mozilla/pdf.js#9930]
PDF.js does not render most .pdf files in Firefox Quantum 61.0.1

Configuration:
Firefox Quantum 61.0.1 (64-bit)
Windows 7 Pro (64-bit)

- PDF.js version:
Not sure how to determine the version of PDF.js since I believe it's built into Firefox

- Is a browser extension:

Steps to reproduce the problem:
1. Go to the following link:
https://www.nasa.gov/sites/default/files/atoms/files/nasa_2018_strategic_plan.pdf

2.Or go to this link instead:
https://www.nasa.gov/sites/default/files/files/FY15_White_House_NASA_Fact_Sheet.pdf

What is the expected behavior?
The PDF file should render completely and not have the spinning wheel displayed continuously.

What went wrong?

![image](https://user-images.githubusercontent.com/41761875/43290695-e29e7b90-90fc-11e8-9424-88f40e083fb4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
Do you have any warnings/errors in the console? You can open it with Ctrl + Shift + K in Firefox.

Moreover, check if your graphics drivers are up-to-date and install any updates if they are available.

**Comment by toddsh88** [comment]
![image](https://user-images.githubusercontent.com/41761875/43360821-1a6b8900-928d-11e8-8bcc-9543dab4166e.png)


And here is the actual text from the above screen capture:

Web fonts are disabled: unable to use embedded PDF fonts. viewer.js:1903:7
PDF 3217f581ec67cc45a1c2e92d24224515 [1.6 Adobe PDF Library 15.0 / Acrobat PDFMaker 15 for Word] (PDF.js: 2.0.491) viewer.js:1628:7
[Show/hide message details.] Error: Requesting object that isn't resolved yet Helvetica_path_ pdf.js:6087:15
PDFObjects_get
resource://pdf.js/build/pdf.js:6087:15
FontFaceObject_getPathGenerator
resource://pdf.js/build/pdf.js:6356:20
paintChar
resource://pdf.js/build/pdf.js:7458:21
CanvasGraphics_showText
resource://pdf.js/build/pdf.js:7605:13
CanvasGraphics_executeOperatorList
resource://pdf.js/build/pdf.js:7008:11
InternalRenderTask__next
resource://pdf.js/build/pdf.js:6238:30
InternalRenderTask__next self-hosted:983:17

**Comment by toddsh88** [comment]
And here's some additional console output from a different problematic link:

![image](https://user-images.githubusercontent.com/41761875/43360847-8f8406a4-928d-11e8-98ee-c397eb79b14c.png)

And here is the actual text from the above 2nd screen capture:

Web fonts are disabled: unable to use embedded PDF fonts. viewer.js:1903:7
PDF 16dcf1e675b511749b8c3ad7de017c81 [1.4 iText 2.1.7 by 1T3XT / TopLeaf 7.6.037] (PDF.js: 2.0.491) viewer.js:1628:7
[Show/hide message details.] Error: Requesting object that isn't resolved yet Helvetica_path_L
pdf.js:6087:15
PDFObjects_get
resource://pdf.js/build/pdf.js:6087:15
FontFaceObject_getPathGenerator
resource://pdf.js/build/pdf.js:6356:20
paintChar
resource://pdf.js/build/pdf.js:7458:21
CanvasGraphics_showText
resource://pdf.js/build/pdf.js:7605:13
CanvasGraphics_executeOperatorList
resource://pdf.js/build/pdf.js:7008:11
InternalRenderTask__next
resource://pdf.js/build/pdf.js:6238:30
InternalRenderTask__next self-hosted:983:17

**Comment by toddsh88** [comment]
In addition, I stumbled across this recent bug report that I think might be someone else reporting the same problem while attempting to view on-line PDFs:

Bug 1478469
Subject: Firefox saving but not displaying pdfs
https://bugzilla.mozilla.org/show_bug.cgi?id=1478469

**Comment by peteroupc** [comment]
This can happen if the preference "Allow pages to choose their own fonts, instead of your selections above" is disabled; see also [this issue](https://github.com/mozilla/pdf.js/issues/9885).

**Comment by timvandermeij** [comment]
Yes, I think that is what's causing this. The warning `Web fonts are disabled: unable to use embedded PDF fonts` is also in the logs.
