### ISSUE TITLE
Rendering completely broken

### ISSUE THREAD

**Issue by quthla** [mozilla/pdf.js#9937]
https://media.lidl-flyer.com/28e23461-8bf2-11e8-ab94-005056ab0fb6/Wochenprospekt-Unsere-Angebote-der-Woche-01.pdf

FF 61.0.1 Windows x64 builtin PDF.js

https://screenshots.firefox.com/YBs0YTEavfPfQ9Er/media.lidl-flyer.com

Console (not sure if related):
```
PDF 0a571803d6ac463387e7927265b551dc [1.6 Adobe PDF Library 15.0 / Adobe InDesign CC 2015 (Macintosh)] (PDF.js: 2.0.491) viewer.js:1628:7
Warning: Unsupported header type 1885564018 (pclr) pdf.worker.js:349:5
Warning: Unsupported header type 1668112752 (cmap) pdf.worker.js:349:5
Warning: Unsupported header type 1885564018 (pclr) pdf.worker.js:349:5
Warning: Unsupported header type 1668112752 (cmap) pdf.worker.js:349:5
Warning: Unsupported header type 1885564018 (pclr) pdf.worker.js:349:5
Warning: Unsupported header type 1668112752 (cmap) pdf.worker.js:349:5 
```

**Comment by timvandermeij** [comment]
Yes, those warnings are very much related. It looks like this is thrown by the JPX decoder (https://github.com/mozilla/pdf.js/blob/d21eecefc19907540c686c3635390150b53893ee/src/core/jpx.js#L119). Thank you for reporting this.
