### ISSUE TITLE
Silent printing 

### ISSUE THREAD

**Issue by BlackWhiteValley** [mozilla/pdf.js#9939]
Attach (recommended) or Link to PDF file here:
[pdfjs.zip](https://github.com/mozilla/pdf.js/files/2240773/pdfjs.zip)

Configuration:
- Web browser and its version: IE, rest of browsers are fine
- Operating system and its version: Win 7 or Win 10
- PDF.js version: 1.9
- Is a browser extension:No

Steps to reproduce the problem:
Hello
I'm trying to setup silent printing of pdf.js document without opening pdf.js viewer for user.
It works fine for Chrome and FF, but not for IE. in IE whole the parent page is printed

What is the expected behavior? (add screenshot)
Print o pdf.document

What went wrong? (add screenshot)
Whole the page is printed

In attachment is complete source, but I think the most important part is here:

`
<html>
	<head>
		<script>
			function printPdf(){
				var url = 'test.pdf'; // thi is the pdf I want to print
        
				var viewerUrlurl = 'web/viewer.html?file=' + url;
        
				document.getElementById('iframe').src = viewerUrlurl;

				
				var printContentWindow = function () {
					var iframe = document.getElementById('iframe');
					if (iframe.contentWindow!=null && iframe.contentWindow.PDFViewerApplication !=null 
						&& iframe.contentWindow.PDFViewerApplication.overlayManager 
						&& iframe.contentWindow.PDFViewerApplication.pdfViewer.pageViewsReady) {
						
						console.info('pdf loaded and ready for printing');
					   
					    iframe.contentWindow.print();
					} else {
						window.setTimeout(printContentWindow);
						
					}
				}
				
				printContentWindow();
			}
		</script>
	</head>
	<h1>Test page for pdf.js printing</h1>
	<div>
	<input type="button" onclick="printPdf()" value="print test.pdf">
	</div>
	
	<div>
		Content of the page is not supposed to be printed at all
	</div>
	<iframe id="iframe" width="0" height="0">
</html>`

Chrome and FF works fine (pdf is printed) but in IE parent page is printed
Note that plan is to make frame hidden (which as well works in Chrome and IE right now)

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
