### ISSUE TITLE
Incorrect characters are rendered when using unicode font

### ISSUE THREAD

**Issue by jeremypress** [mozilla/pdf.js#9941]
Attach (recommended) or Link to PDF file here:
[FILE A.pdf](https://github.com/mozilla/pdf.js/files/2242769/FILE.A.pdf)

Configuration:
- Web browser and its version:
Chrome 68.0.3440.75 Affecting other browses as well
- Operating system and its version:
MacOS Sierra
- PDF.js version:
pdfjsVersion = '2.0.104';
pdfjsBuild = '012d0756';
Also reproducible in latest demo build

- Is a browser extension:
no
Steps to reproduce the problem:
1. Preview the PDF

What is the expected behavior? (add screenshot)
Fonts should render correctly

<img width="1026" alt="screen shot 2018-07-30 at 1 23 51 pm" src="https://user-images.githubusercontent.com/2474027/43421509-d0c8455c-93fb-11e8-8317-7561437c3680.png">

What went wrong? (add screenshot)
Fonts are garbled 
<img width="1014" alt="screen shot 2018-07-30 at 1 23 19 pm" src="https://user-images.githubusercontent.com/2474027/43421520-da738832-93fb-11e8-91c7-71d2b442d76e.png">

Fonts render incorrectly

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Reproducible in demo

PDF was created by "Nitro"

**Comment by timvandermeij** [comment]
It looks like this is related to font conversion. Okular tells me that the font `ArialUnicodeMS` is not embedded in the PDF file.

**Comment by jeremypress** [comment]
hey @timvandermeij, thanks for looking into this. I will embed the font directly.

**Comment by timvandermeij** [comment]
No problem! For reference, embedding fonts is always better because it ensures that the PDF file is displayed the same across platforms, because if the font is not embedded it may result in font substitution with a possibly unintended font or other rendering problems.
