### ISSUE TITLE
Use JS font loading API on Firefox

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#9945]
After [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1473742) lands we should be able to use the font loading API on Firefox. Unfortunately, there's not really a way to feature detect, so we'll have to check the Firefox version number.

**Comment by timvandermeij** [comment]
It looks like https://github.com/mozilla/pdf.js/blob/280f20bf3cfd2ae2d0a4c77d0510e313100a3a38/src/display/font_loader.js#L114-L117 is related to this. Really good news if we can use the font loading API!

**Comment by timvandermeij** [comment]
The fix landed for Firefox 63, so we can continue this.
