### ISSUE TITLE
Problem displaying PDF file with embedded fonts

### ISSUE THREAD

**Issue by fschutt** [mozilla/pdf.js#9949]
I am working on the PDF library [printpdf](https://github.com/fschutt/printpdf) and noticed that Firefox doesn't display the fonts example correctly.

This could be a bug in pdf.js or a bug in my library. However, all other PDF viewers I've tested so far display the file correctly:

Evince:

![image](https://user-images.githubusercontent.com/12084016/43585047-678c6530-9664-11e8-830a-aa86713dd44c.png)

Google Chrome:

![image](https://user-images.githubusercontent.com/12084016/43584865-e5c77cec-9663-11e8-9c4d-02483456ace8.png)

Adobe Reader:

![image](https://user-images.githubusercontent.com/12084016/43584791-b2ae90a2-9663-11e8-9e84-33babf438056.png)

Foxit Reader:

![image](https://user-images.githubusercontent.com/12084016/43585004-4886fb6e-9664-11e8-9cfd-a9cf8e32e189.png)

xpdf:

![image](https://user-images.githubusercontent.com/12084016/43585634-e631052a-9665-11e8-92f1-691a0adf5564.png)

Sumatra PDF:

![image](https://user-images.githubusercontent.com/12084016/43593604-8841ccd4-9678-11e8-89f9-f6677486d805.png)

... but Firefox:

![image](https://user-images.githubusercontent.com/12084016/43593294-b173f5a6-9677-11e8-97cb-13528d485c9f.png)

Here is the corrupt PDF file: [test_fonts.pdf](https://github.com/mozilla/pdf.js/files/2254027/test_fonts.pdf)

The code that generated the PDF file is here: https://github.com/fschutt/printpdf/blob/master/examples/fonts.rs - if you want to reproduce this from source, clone the repository and run `cargo run --example fonts`.

I do get an error in the console, but it's very non-descriptive:

```
util.js:29 Warning: Error during font loading: Cannot read property 'length' of undefined
```

Configuration:
- Web browser and its version: Both Chrome 67.0.3396.99 and Firefox 61.0.1 (64-Bit)
- Operating system and its version: Windows 8.1
- PDF.js version: master @ 716acf63d489bad06c9453f81f155546e4d77912
- Is a browser extension: No

Steps to reproduce the problem:
1. Set up the build system as in the README
2. Open the `test_fonts.pdf` file

I've tried to debug this error. Again, it could be that something is wrong with my code, but I don't know Javascript too well to debug the problem. So far my notes were:

```
- message_handler.js:123 - "action[0].call(action[1], data.data);": action[1] is undefined for whatever reason, data.data is null
- worker.js:685 - "RenderPageRequest" - I think this is where the crash happens
- worker.js:686 - "page" variable seems to have an empty font cache - where are the fonts loaded?
- worker.js:686: It seems that page.getOperatorList is not executed correctly
```

The example itself embeds a font + a Unicode dictionary. The respective code for doing so is [here](https://github.com/fschutt/printpdf/blob/b362afa6caf735e566b52aba0d2b98dbdb0738c5/src/types/plugins/graphics/two_dimensional/font.rs#L157-L350), maybe a PDF expert can tell me what's wrong with this. Adobe Acrobat doesn't throw any errors aside from complaining about layers - the PDF validates for PDF/X3:2002 (except that it uses layers).

I could debug this further, but I find the architecture of pdf.js very complex and I am not very good in debugging JavaScript, so I wanted to ask if anyone could help on why this example doesn't work. Thanks in advance.

**Comment by brendandahl** [comment]
Looks like the font is marked as CIDFontType0 in the font dictionary, but the font is really a true type font.

PDF.js could handle this more gracefully by either falling back to a system font or we need to add a heuristic and look into the font data to see if it is really a CFF font or a true type font.

**Comment by fschutt** [comment]
As what type should it be marked if not CIDFontType0?

**Comment by fschutt** [comment]
Okay, marking the font as `CIDFontType2` instead on `CIDFontType0` resolves this. I mean, pdf.js is technically correct about this, it is technically a broken PDF. I'll fix this in my library - all other PDF viewers seem to be a bit more lenient about what they accept.

**Comment by timvandermeij** [comment]
Thank you for fixing it in the library. The two pull requests above also make the bad PDF file render so we're behaving the same as other viewers.
