### ISSUE TITLE
PDF Corrupetd

### ISSUE THREAD

**Issue by thiagoreri** [mozilla/pdf.js#9950]
Configuration:
- Web browser and its version:Chrome
- Operating system and its version: Win10
- PDF.js version: 2.0.489
- Is a browser extension:

After loading pdf:

let blob = new Blob([response.data], { type: 'application/pdf' }),
 url = window.URL.createObjectURL(blob)
 window.open(url)

Related error: Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 239"

**Comment by timvandermeij** [comment]
You need to provide all information requested in the issue template, especially attaching the PDF file that is failing. Without it, this issue will be closed as incomplete.

**Comment by timvandermeij** [comment]
Closing for now until the requested information is provided.

**Comment by depiction** [comment]
I had the same problem. I fixed it by changing the response type on the API request that gets the file to 'blob'. The default is 'application/json'.

**Comment by hansaniii** [comment]
I'm having the same problem but I fixed the API request into  'blob' and default as 'application/json'. I got only the exact page count with empty pages.
