### ISSUE TITLE
PDF rendered incorrectly: white gap lines between neighbouring rectangles

### ISSUE THREAD

**Issue by ousia** [mozilla/pdf.js#9953]
Attach (recommended) or Link to PDF file here:
https://gitlab.gnome.org/GNOME/evince/uploads/3593c890420275992e8bceb4bb5f3d88/frame-on-background.pdf

Configuration:
- Web browser and its version: Firefox 61.0.1
- Operating system and its version: Fedora 28
- PDF.js version: I don’t know.
- Is a browser extension: No

Steps to reproduce the problem:

The linked PDF file (created with OpenOffice) contains adjacent same-colored rectangles (see https://bz.apache.org/ooo/show_bug.cgi?id=127828 for further information).
When opened with PDF.js, thin white gap lines are visible between the rectangles.

PDF.js should display the [following output](https://bugs.freedesktop.org/attachment.cgi?id=140938), but it gives [this one](https://bugs.freedesktop.org/attachment.cgi?id=140939).

**Comment by timvandermeij** [comment]
Most likely related to #3351.

**Comment by ousia** [comment]
Subscribed to both  #3351 and  #3331.

Closing the issue myself.
