### ISSUE TITLE
How to use PDF.JS for checking password protected/corrupted file or not?

### ISSUE THREAD

**Issue by vinothkt** [mozilla/pdf.js#9957]
How can we use PDF.JS to just to check selected PDF is password protected or corrupted?
Based on this validation, I want to do my own implementation.

**Comment by timvandermeij** [comment]
To check if a PDF file is password-protected, you can use the `loadingTask.onPassword` handler (see https://github.com/mozilla/pdf.js/blob/d19e13ee2e938052c2c3a776eb94a930813a5125/web/app.js#L682-L685). To check if a PDF file is (possibly) corrupted, you should catch any errors when loading: https://github.com/mozilla/pdf.js/blob/d19e13ee2e938052c2c3a776eb94a930813a5125/web/app.js#L696-L722

**Comment by vinothkt** [comment]
Thanks, but i just need this validation should happen synchronously, so rest of execution works depends on this validation. 

How to turn off async?

**Comment by timvandermeij** [comment]
I don't think you can because PDF.js itself is mostly asynchronous due to the nature of PDF file parsing.
