### ISSUE TITLE
Chrome Failed to load resource: net::ERR_CACHE_OPERATION_NOT_SUPPORTED

### ISSUE THREAD

**Issue by dsk12356** [mozilla/pdf.js#9963]
I use PDF.js library to display PDFs on my website. The documents are usually 2-5 MB in size and contain tutorial work for the classes I teach.

Recently I noticed on Chrome (Mac), whenever I try to load my documents, I get the following error in the development console:

Failed to load resource: ERR_CACHE_OPERATION_NOT_SUPPORTED

But when I try the website form Incognito mode (Chrome Mac), the PDF displays instantly, and this error never comes up.

The error is present at the moment with Chrome (Mac), other browsers work fine (Safari, Opera, Firefox). A few days ago it was present on the PC version of Chrome as well, but now I can't seem to produce it again.

I deleted all extensions, and same results. I even reset Chrome and the same error comes on the Mac version of Chrome.

I did notice that if you keep clicking, randomly the document will load, but it can take anywhere from 1 click to 10 clicks.

Documents on the left side, PDF viewer in the middle: https://i.stack.imgur.com/oJJOG.png
Console on Mac Chrome with error: https://i.stack.imgur.com/qzCTH.jpg
Console on PC Chrome with no error: https://i.stack.imgur.com/D0ctP.png

PDF.js version: 1.9.426

**Comment by mr47** [comment]
@dsk12356 It's a chrome issue can read more about it https://github.com/webtorrent/webtorrent/issues/1193#issuecomment-388008037

PDF.js not responsible for this.

**Comment by timvandermeij** [comment]
Closing since this does not look related to PDF.js. You can file an upstream bug in Chrome's bug tracker if the issue persists.

**Comment by avirtum** [comment]
Have the same issue on Chrome Version 68.0.3440.106 and PDFjs version 1.9.426. In incognito mode work fine, very strange.

**Comment by dsk12356** [comment]
@avirtum Worked like a charm! Thank you so much!

**Comment by philsher93** [comment]
> Have the same issue on Chrome Version 68.0.3440.106 and PDFjs version 1.9.426. In incognito mode work fine, very strange. To fix this issue I just disabled the range request in my plugin PDFJS.disableRange=true, after this all work as expected.

Yes worked great thanks!!!!!

**Comment by esteves67** [comment]
> Have the same issue on Chrome Version 68.0.3440.106 and PDFjs version 1.9.426. In incognito mode work fine, very strange. To fix this issue I just disabled the range request in my plugin PDFJS.disableRange=true, after this all work as expected.

Thank you!
