### ISSUE TITLE
Rendering PDF UA compatible PDFs

### ISSUE THREAD

**Issue by grpramod** [mozilla/pdf.js#9966]
Hi,

Can this framework renders PDF UA compatible PDFs? 

Please let me know if it supports, thanks!!

**Comment by timvandermeij** [comment]
I think you can render the PDF files, but PDF.js does not yet support the accessibility features. I think this is also known as a "tagged PDF" and we have open issues for that; see https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-tagged-pdf.
