### ISSUE TITLE
ReferenceError: PDFJS is not defined

### ISSUE THREAD

**Issue by atnsm** [mozilla/pdf.js#9967]
In summary I get two errors in two different versions of pdfjs in pdf-annotate.js project:

Version 1.10.100: **Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.**

Version 2.0.550
**ReferenceError: PDFJS is not defined**

Configuration:
- Web browser and its version: Firefox Quantum 62.0b14  & Chrome 67
- Operating system and its version: Win SP1
- PDF.js version: two versions mentioned above

Steps to reproduce the problem:
1. clone https://github.com/instructure/pdf-annotate.js/
2. change pdfjs-dist version to 2.0.550 or 1.10.100 in package.json
3. npm install
4. npm start

What went wrong?
It does not render the pdf correctly.

Do you think the problem is from pdfjs or the render function in pdf-annotate.js project?

**Comment by timvandermeij** [comment]
The `pdf-annotate.js` project is at fault here. First of all, it's not possible to just swap version 1.x and 2.x since the latter contains backwards incompatible changes, most notably the removal of the global `PDFJS` object, which is what the error indicates. The code must be adapted to work for PDF.js 2.0 when it's released as a stable version (currently it's a pre-release). For version 1.x, you should do every rendering operation on a new canvas if possible because reusing the old one can lead to race conditions if drawing is not yet completed.

**Comment by atnsm** [comment]
Thank you for the quick reply. 
Regarding the 1.x, could you elaborate more on rendering on a new canvas? I am relatively new to pdfjs. Do you know  any similar code sample?

**Comment by timvandermeij** [comment]
If you're building your own viewer, or developing a library, you can make use of our viewer components to render a PDF file. The `pdfViewer` component does all the heavy lifting for you; look at https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js#L70 for example. Otherwise, if you do it yourself, you have to render every page on its own canvas and not reuse existing canvases. For example, see https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L50-L54 to see how the page is rendered onto its own canvas (context). Refer to #5636 for more information.

**Comment by atnsm** [comment]
As a follow up question:

Using latest pdfjs version (2.0.550) I get the following error:
 **Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.**

The code I am using for rendering is as follow:
I don't know how to fix it!

```javascript
function renderPage(pageNumber, renderOptions) {
                var documentId = renderOptions.documentId;
                var pdfDocument = renderOptions.pdfDocument;
                var scale = renderOptions.scale;
                var rotate = renderOptions.rotate;
                // Load the page and annotations
                return Promise.all([pdfDocument.getPage(pageNumber), _PDFJSAnnotate2.default.getAnnotations(documentId, pageNumber)]).then(function (_ref) {
                    var _ref2 = _slicedToArray(_ref, 2);
                    var pdfPage = _ref2[0];
                    var annotations = _ref2[1];
                    var page = document.getElementById('pageContainer' + pageNumber);
                    var svg = page.querySelector('.annotationLayer');
                    var canvas = page.querySelector('.canvasWrapper canvas');
                    var canvasContext = canvas.getContext('2d', {alpha: false});
                    var viewport = pdfPage.getViewport(scale, rotate);
                    var transform = scalePage(pageNumber, viewport, canvasContext);// Render the page
                    return Promise.all([pdfPage.render({canvasContext: canvasContext, viewport: viewport, transform: transform}), _PDFJSAnnotate2.default.render(svg, viewport, annotations)]).then(function () {
                        // Text content is needed for a11y, but is also necessary for creating
                        // highlight and strikeout annotations which require selecting text.
                        return pdfPage.getTextContent({normalizeWhitespace: true}).then(function (textContent) {
                            return new Promise(function (resolve, reject) {// Render text layer for a11y of text content
                                var textLayer = page.querySelector('.textLayer');
                                var textLayerFactory = new pdfjsViewer.DefaultTextLayerFactory();
                                var textLayerBuilder = textLayerFactory.createTextLayerBuilder(textLayer, pageNumber - 1, viewport);
                                textLayerBuilder.setTextContent(textContent);
                                textLayerBuilder.render();// Enable a11y for annotations
                                // Timeout is needed to wait for `textLayerBuilder.render`
                                setTimeout(function () {
                                    try {
                                        (0, _renderScreenReaderHints2.default)(annotations.annotations);
                                        resolve();
                                    } catch (e) {
                                        reject(e);
                                    }
                                });
                            });
                        });
                    }).then(function () {// Indicate that the page was loaded
                        page.setAttribute('data-loaded', 'true');
                        return[pdfPage, annotations];
                    });
                });
            }
```

**Comment by Anandks1993** [comment]
@atnsm Did you solve this error? I am facing the same problem now. If so, can you please let me know how to fix it?
