### ISSUE TITLE
Expose the document permissions via API

### ISSUE THREAD

**Issue by pdfhandler** [mozilla/pdf.js#9972]
Does PDF.js have an API to retrieve the document permissions?

We would like to see if the document is printable or is editable.
This will be used for verification and be categorized.

If there are not, what is the plan for introducing the ability to retrieve this information.

**Comment by timvandermeij** [comment]
No, we don't handle document permissions yet. Could you provide some example PDF files for us to work with?

**Comment by pdfhandler** [comment]
Attached is a file set with different permissions. 
[sleep_no_document_editing.pdf](https://github.com/mozilla/pdf.js/files/2277445/sleep_no_document_editing.pdf)
[sleep_no_printing.pdf](https://github.com/mozilla/pdf.js/files/2277446/sleep_no_printing.pdf)
[sleep_no_copying.pdf](https://github.com/mozilla/pdf.js/files/2277447/sleep_no_copying.pdf)
