### ISSUE TITLE
simpleviewer Example - Adding id to each div tag

### ISSUE THREAD

**Issue by atnsm** [mozilla/pdf.js#9978]
In the [component/simpleviewer](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js) example, 
pdfViewer.setDocument(pdfDocument) function render each pages of pdf in a single div tag.
I would like to add an id to each of these tags. 

Do you have any suggestion for doing so?

**Comment by Snuffleupagus** [comment]
> Do you have any suggestion for doing so?

You should be able to utilize the already existing [`data-page-number` attributes](https://github.com/mozilla/pdf.js/blob/1268aea2b62f6cdedc63c639c332fa2d3bc5af7a/web/pdf_page_view.js#L111), to identify/lookup pages in the DOM. (If that, for some reason, isn't sufficient you'll have to modify the source code yourself.)
