### ISSUE TITLE
how to not includes the header and footer texts when using .getTextContent()

### ISSUE THREAD

**Issue by havenht** [mozilla/pdf.js#9979]
Hi, When I get all the texts using .getTextContent() , I get the footer and header within the content. Such as the number of the pages or the title of the pdf book that is in the header/footer of each page.. Is there a setting or a way to not get footer and header texts? Thanks

**Comment by timvandermeij** [comment]
The PDF format does not allow us to know what a header or footer is in the document; for the format every text is just a series of glyphs with a position. I can only imagine that you can request the coordinates along with the text and strip any text above or below a certain point, but that's about as far as you can go with the PDF format.
