### ISSUE TITLE
blurring of pdf on pinch to zoom 'only' on iOS based devices

### ISSUE THREAD

**Issue by kshantanu94** [mozilla/pdf.js#9983]
PFA screenshots on both Android and iOS devices of pdfs rendered with pdf.js.

iOS - https://imgur.com/a/2KkPAdj
Android - https://imgur.com/a/UImRNab

As can be observed, on pinch to zoom iOS devices face a significant loss in sharpness while Android maintains the clarity. Is there a way around it?

**Comment by timvandermeij** [comment]
Closing since this is a duplicate of #6419.
