### ISSUE TITLE
DefaultTextLayerFactory in v2.0.550

### ISSUE THREAD

**Issue by atnsm** [mozilla/pdf.js#9992]
Previously, I used the following code using pdfjs v.1.x with no problem:

PDFJS.workerSrc = 'pdf.worker.js';
...
var textLayerFactory = new PDFJS.DefaultTextLayerFactory();
_________________________________________

Now, in version 2.x with the following modifications:
pdfjsLib.GlobalWorkerOptions.workerSrc = 'pdf.worker.js';
...
var textLayerFactory = new pdfjsLib.DefaultTextLayerFactory();

I get the following error:
**pdfjsLib.DefaultTextLayerFactory is not a constructor**

How can I fix this issue?

**Comment by timvandermeij** [comment]
You most likely need to use `pdfjsViewer.DefaultTextLayerFactory()`; see https://github.com/mozilla/pdf.js/blob/63c7aee11211f071af382892f1664fe90f56b9e4/examples/components/pageviewer.js#L54.
