### ISSUE TITLE
The API version does not match the worker version

### ISSUE THREAD

**Issue by danharris627** [mozilla/pdf.js#9997]
Hi, I'm trying to generate a PDF from a Unit8Array but am getting the following message & am not sure what it means:

FfomxtAXZDQQEEX5m:1 Uncaught (in promise) UnknownErrorException {name: "UnknownErrorException", message: "The API version "2.0.489" does not match the Worker version "2.0.775".", details: "Error: The API version "2.0.489" does not match the Worker version "2.0.775"."}

here is my code:

import pdfjs from 'pdfjs-dict';

Meteor.call('ideas.export', FlowRouter.getParam('id'), (err, pdf) => templateInstance.pdfArray.set(pdf));

    setTimeout(() => {
      console.log(templateInstance.pdfArray.get());
      pdfjs.GlobalWorkerOptions.workerSrc = 'http://mozilla.github.io/pdf.js/build/pdf.worker.js';
      var canvasContainer = document.getElementById('myCanvasContainer');
      var options = options || { scale: 1.5 };

      function renderPage(page) {
          var viewport = page.getViewport(options.scale);
          var canvas = document.createElement('canvas');
          var ctx = canvas.getContext('2d');
          var renderContext = {
            canvasContext: ctx,
            viewport: viewport
          };

          canvas.height = viewport.height;
          canvas.width = viewport.width;
          canvasContainer.appendChild(canvas);

          page.render(renderContext);
      }

      function renderPages(pdfDoc) {
          for(var num = 1; num <= pdfDoc.numPages; num++)
              pdfDoc.getPage(num).then(renderPage);
      }

      pdfjs.disabledWorker = true;
      pdfjs.getDocument(templateInstance.pdfArray.get()).then(renderPages);
      }, 10000)
  }

and my package.json:

    "ng2-pdf-viewer": "^5.1.1",
    "pdfjs-dist": "^2.0.550",

**Comment by wwwhatley** [comment]
Why was this closed?

**Comment by aureooms** [comment]
Use

```js
import pdfjs from 'pdfjs-dist';
const WORKER_URL = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;
if (pdfjs.GlobalWorkerOptions.workerSrc === '') {
    pdfjs.GlobalWorkerOptions.workerSrc = WORKER_URL;
}
```

**Comment by igortas** [comment]
> Quite literally, the API version does not match the worker version. Use
> 
> ```js
> import pdfjs from 'pdfjs-dist';
> if (!pdfjs.GlobalWorkerOptions.workerSrc) {
>     const WORKER_URL = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;
>     pdfjs.GlobalWorkerOptions.workerSrc = WORKER_URL;
> }
> ```
> 
> where the part that says `${pdfjs.version}` makes the worker version match the API version.

outdated, having the same issue with the latest pdfjs version. crap library.
