### ISSUE TITLE
Both text and path are rendered overlapping each other in SVG mode

### ISSUE THREAD

**Issue by valerii-cognite** [mozilla/pdf.js#9999]
Attach (recommended) or Link to PDF file here:
[TEST.PDF](https://github.com/mozilla/pdf.js/files/2311069/TEST.PDF)

Configuration:
- Web browser and its version: Crome 68, Firefox 61.0.2, reproduces on others as well
- Operating system and its version: Os X 10.13, reproduces on others as well
- PDF.js version: pdfjs-dist: 2.0.489
- Is a browser extension: no

Steps to reproduce the problem:
Just the basic svg configuration should be taken into account:
```
import pdfjs from 'pdfjs-dist';

pdfjs
  .getDocument(url)
  .then(pdf => pdf.getPage(1))
  .then(page => {
    const viewport = page.getViewport(1);
    // Get div#the-svg
    const container = document.getElementById('the-svg');

    // Set dimensions
    container.style.width = `${viewport.width}px`;
    container.style.height = `${viewport.height}px`;

    // SVG rendering by PDF.js
    page
      .getOperatorList()
      .then(opList => {
        const svgGfx = new pdfjs.SVGGraphics(page.commonObjs, page.objs);
        return svgGfx.getSVG(opList, viewport);
      })
      .then(svg => {
        container.appendChild(svg);
      });
  });
```

What is the expected behavior? (add screenshot)
![screen shot 2018-08-22 at 17 43 03](https://user-images.githubusercontent.com/38251534/44474498-18896300-a633-11e8-9928-033d92f9e94a.png)
If to open the document with Chrome.

What went wrong? (add screenshot)
![screen shot 2018-08-22 at 17 42 00](https://user-images.githubusercontent.com/38251534/44474508-1e7f4400-a633-11e8-844b-d916bee00482.png)
If to render the pdf document with pdf.js

So it seems both text and path are rendered at the same time overlapping each other.

Are there any ideas on why could that happen?

**Comment by valerii-cognite** [comment]
Any input on this?

**Comment by timvandermeij** [comment]
Sorry, we haven't had the time to look at this yet. It could be that we draw both the text and the path, but they should be separate SVG elements in that case. You can check with the inspect element feature if that is the case. It could also be a hidden path that we actually draw with the wrong color.

**Comment by janpe2** [comment]
The PDF file uses the operator `Tr` (text rendering mode) to draw hidden text on top of the paths. However, `Tr` hasn't been implemented in the SVG backend, so the text becomes visible.
